### ISSUE TITLE
Remote REPL (remote management of actors)

### ISSUE THREAD

**Issue by jboner** [akka/akka#10072]
imported from https://www.assembla.com/spaces/akka/tickets/72

Would work nice with the: 
actor ! HotSwap(PF)

Can perhaps even wrap it in a more high-level manager for actors.

**Comment by rkuhn** [comment]
I think this ticket is no longer valid. We will implement more targeted monitoring and management, but not as a REPL.

**Comment by hepin1989** [comment]
seems like embed ssh.
