### ISSUE TITLE
Write bench for remote communication/network protocol

### ISSUE THREAD

**Issue by jboner** [akka/akka#11797]
imported from https://www.assembla.com/spaces/akka/tickets/1797

Performance testing for remoting and clustering; localhost for dev laptop or jenkins plus real networking on moxie cluster.
- one-to-many ping pong tests, for latency (tell & ask)
- saturation throughput for small, medium and large messages

√: add recipients at different depths in the actor hierarchy

**Comment by patriknw** [comment]
This was done in the Artery work
