### ISSUE TITLE
Implement support for DOWNING a node that is reachable

### ISSUE THREAD

**Issue by jboner** [akka/akka#11907]
imported from https://www.assembla.com/spaces/akka/tickets/1907

for maintenance etc.
tricky part is that he will still be able to gossip, but not receive gossip so his failure detector will detect all nodes as 'unreachable'
how to force him to go through JOINING phase again? 

Now we have 'ClientDowningNodeThatIsUpMultiJvmSpec' test. But it doesn't test: 
* rejoining after being DOWNed
* managing the gossip while being DOWN

**Comment by patriknw** [comment]
I think this is solved, at least we have a test for it NodeDowningAndBeingRemovedSpec
