### ISSUE TITLE
Research 'Interval Tree Clocks' and 'Dotted Version Vectors' as a replacement for our current VectorClock implementation

### ISSUE THREAD

**Issue by jboner** [akka/akka#11956]
imported from https://www.assembla.com/spaces/akka/tickets/1956

Both 'Interval Tree Clocks' and 'Dotted Version Vectors' keep the size of the history down a lot. 
So we would not need to implement VectorClock pruning, which is both hard to impl and can never be fully correct.

h1. Interval Tree Clocks
Paper: http://thor.info.uaic.ro/~vidrascu/MasterSD2/papers/cap3/itc2008.pdf
Two different Java implementations that we could use or port to Scala: 
* https://github.com/haf/Interval-Tree-Clocks
* http://code.google.com/p/itc4j/

h1. Dotted Version Vectors
Paper: http://gsd.di.uminho.pt/members/vff/dotted-version-vectors-2012.pdf
How Riak was improved: http://gsd.di.uminho.pt/members/tome/papers/inforum2011.pdf
Erlang implementation we could port to Scala: https://github.com/ricardobcl/Dotted-Version-Vectors

**Comment by patriknw** [comment]
Related #16020
