### ISSUE TITLE
Change cluster protocol to use a Push-Pull mechanism

### ISSUE THREAD

**Issue by jboner** [akka/akka#12107]
imported from https://www.assembla.com/spaces/akka/tickets/2107

Instead of only current Push. 
To minimize data sent across the wire. 
See the cluster spec. 

Split up in two groups: 
1. membership set, unreachable set and seen table
2. meta-data

1) has a single digest for everything, should not change often so it should be fine

2) can change much more frequent (probably all the time) - here we should have one digest per meta-data entry. 
Here we should consider using Scuttlebutt reconciliation. See attached paper: "Efficient Reconciliation and Flow Control
for Anti-Entropy Protocols"

**Comment by patriknw** [comment]
Related #16019

**Comment by patriknw** [comment]
Closing this, since the remaining part of sending deltas is tracked by another ticket.
