### ISSUE TITLE
DOC: document blocking database actors pattern

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#12190]
imported from https://www.assembla.com/spaces/akka/tickets/2190

This question comes up over and over, as I've mentioned before, it would really help adoption of the framework if such a very common use case most people will encounter is well understood through documentation and examples. 
 
here is a recent example of trying to establish a "best practices" pattern: https://groups.google.com/d/msg/akka-user/_t1ER27Df78/NpHpzCPKGrYJ

using a separate dispatcher for the db representing router & routees sounds like a great (and necessary!) idea, good call. 

older discussions:

https://groups.google.com/d/msg/akka-user/4F0wQNnMHUE/h0T-ZzsxRFkJ
https://groups.google.com/d/msg/akka-user/EDKA2aTigho/NcTiJ6ZWggYJ

**Comment by patriknw** [comment]
I think this is done
