### ISSUE TITLE
Create topology-aware routers

### ISSUE THREAD

**Issue by jboner** [akka/akka#12243]
imported from https://www.assembla.com/spaces/akka/tickets/2243

Similar to Voldermort's Zones: https://github.com/voldemort/voldemort/wiki/Topology-awareness-capability
Would allow spreading the risk by routing to different instances on different racks or datacenters. 

Also see Cassandras RackAwareStrategy: http://wiki.apache.org/cassandra/Operations#Replication
Cassandra's config is like this, with 'Data Center:Rack' mapped to host:port:
<pre>
#Cassandra Node IP:Port=Data Center:Rack
192.168.1.200\:7000=dc1:r1
192.168.2.300\:7000=dc2:rA
</pre>
Parsed by: http://svn.apache.org/repos/asf/cassandra/tags/cassandra-0.6.1/contrib/property_snitch/src/java/org/apache/cassandra/locator/PropertyFileEndPointSnitch.java

But I think I prefer Voldemort's scheme. Let's think about what is most useful in our env and come up with our own.

**Comment by helena** [comment]
In digging into how Cassandra does its topology awareness across datacenters (dc,rack, various cloud providers), I've started writing some Snitches that could possibly go toward an akka-cluster-topology in akka-contrib. Will update here if this proves do-able.

**Comment by patriknw** [comment]
thanks
