### ISSUE TITLE
DOC: add section on what the user should think about to allow rolling upgrades of his system

### ISSUE THREAD

**Issue by jboner** [akka/akka#12434]
imported from https://www.assembla.com/spaces/akka/tickets/2434

* serialization - protobuf etc instead of java serialization - also explain that Akka's system network protocol supports it
* more?

**Comment by rkuhn** [comment]
I think this is more a topic for higher-level tools like ConductR, WDYT?

**Comment by ktoso** [comment]
When we stabilize protocol we'll likely have a section explaining that bit, other than that I think you're right

**Comment by helena** [comment]
@patriknw I think we can close it because we have published quite a bit on this and much more coming, all with their own more recent tickets.

**Comment by patriknw** [comment]
Ok
