### ISSUE TITLE
Write a specification for the redesigned remoting

### ISSUE THREAD

**Issue by drewhk** [akka/akka#12481]
imported from https://www.assembla.com/spaces/akka/tickets/2481

Comvert the existing design document draft to a documentation of the architecture of the new remoting and a specification of the new Akka protocol.

**Comment by ktoso** [comment]
Noting down a slightly related use case from the community, about [Serializing ActorIdentity](https://groups.google.com/forum/#!topic/akka-user/z9_5LjwLLn8). Since it's now still serialized using java-serialization, clusters must be on the same scala version because of binary diff in `Option`.

**Comment by hepin1989** [comment]
so the remote spi will redesign,will this happen for akka 2.4?
https://github.com/akka/akka/issues/16307

I know that akka 2.5/3 will make the remoting based on stream,and then the io streaming it's self based on akka io.

**Comment by patriknw** [comment]
It will not happen for 2.4

**Comment by hepin1989** [comment]
redesign should based on http2.
