### ISSUE TITLE
Think about long running performance and stability tests

### ISSUE THREAD

**Issue by drewhk** [akka/akka#12533]
imported from https://www.assembla.com/spaces/akka/tickets/2533

To improve stability we should get more insight of the long-term behavior of Akka.

 - How long can we afford to run tests? 
 - Do we want to run these tests for different versions, or the latest, or latest released? Periodic snapshots of master? (two-week, or such) 
 - Ideal would be tests that run  "infinitely long", and have weekly automatic reports (some leaks might materialize as a very slow drift of memory usage so they don't result in crashes).
 - Also, a realistic and sufficiently complex system is needed -- a simple ping-pong might not do the trick.
 - A good opportunity to dogfood Atmos

Let's Discuss!

**Comment by patriknw** [comment]
of course a great idea but there is only so many things we can maintain
