### ISSUE TITLE
Create Akka IO based Transport driver

### ISSUE THREAD

**Issue by drewhk** [akka/akka#12621]
imported from https://www.assembla.com/spaces/akka/tickets/2621

Create a Transport implementation based on Akka IO support to provide a TCP connection. It should be compatible with the Netty driver.

**Comment by hepin1989** [comment]
I am currently implement this via an io extension(using netty,but with similar command as akka io),and I found that when implement the transport via the actor way the current SPI seems odd,so may I assume that when the akka is going to implement the akka remote transport via the akka stream based io,then the transport SPI need a change/new design right?

**Comment by drewhk** [comment]
Yes, we did attempt to replace the current SPI and Netty drivers because we are planning to use reactive streams based drivers instead. Since RS is now a "standard" (kind-of) that seems to be the best bet.

**Comment by hepin1989** [comment]
Thanks for that info,so any transport implemented for the akka 2.4 will be stream based too,nice.

**Comment by patriknw** [comment]
This work will not make it into 2.4, as far as I know. Don't always believe the Milestone of open tickets.

**Comment by hepin1989** [comment]
@patriknw thanks ,you guys have so many work to do.:(

**Comment by patriknw** [comment]
yes, lots of fun work ahead

**Comment by hepin1989** [comment]
I think this should be based on http2.
the priory of the stream ,binary protocal,flow control,security,and the cluster could associated via a naming server and so on.
