### ISSUE TITLE
Remove math.uncommons dependency

### ISSUE THREAD

**Issue by drewhk** [akka/akka#12636]
imported from https://www.assembla.com/spaces/akka/tickets/2636

math.uncommons is used to implement a crypto provider to replace the flawed SecureRandom based seed generator in Java. It could be completely replaced by a small amount of Scala code.

**Comment by gosubpl** [comment]
Is the random.org dependency still needed? If not, the InternetSeedGenerator could be implemented with SecureRandom instead and uncommons dependency removed entirely. If yes, then uncommons dependency can be removed from the not deprecated code that doesn't use ISG and the dependency in the project scope - after whole (deprecated) ISG is removed. Which implementation would you advise?

**Comment by gosubpl** [comment]
Made some progress with the simplest variant of this task, a.k.a. replace `AES256CounterSecureRNG` with something not using `org.uncommons.maths` code, but executing the same algorithm. _Hope_ to be done with PR by the end of the week. As `InternetSeedGenerator` is deprecated, uncommons removal could go into `2.5`.

**Comment by patriknw** [comment]
thanks

**Comment by gosubpl** [comment]
This ticket can be closed now :)

**Comment by patriknw** [comment]
thanks
