### ISSUE TITLE
Create Network Latency Load Balancing Router

### ISSUE THREAD

**Issue by helena** [akka/akka#12639]
imported from https://www.assembla.com/spaces/akka/tickets/2639

All preliminary metric work is completed 
- evaluation of smoothed data values to get the node with either min or max, depending
- extraction of the data w/out metric logic in the router package
- creation of NetworkLatencyLoadBalancer

To Do
- complete the algorithm for either min or max: see test/akka.cluster.router.NetworkLatencyLoadBalancer

**Comment by patriknw** [comment]
interesting feature, but closing due to lack of interest
