### ISSUE TITLE
Network utilization metrics

### ISSUE THREAD

**Issue by patriknw** [akka/akka#12700]
imported from https://www.assembla.com/spaces/akka/tickets/2700

I thought we could implement the network throughput utilization metrics as part of #2547, but sigar doesn't provide the max speed info of the network interfaces on linux.

http://communities.vmware.com/thread/356304
https://jira.hyperic.com/browse/SIGAR-220

Therefore this metrics is postponed to later.

The interesting methods of the sigar api for this:
* getNetInterfaceList - names of the network interfaces
* getNetInterfaceStat - the stats
  * getRxBytes - inbound bytes
  * getTxBytes - outbound bytes
  * getSpeed - the max speed, which is not implemented for linux

Note that getRxBytes and getTxBytes returns the total number of bytes, so calculation of throughput rate between observations needs to be implemented manually.

**Comment by rkuhn** [comment]
@Andrei-Pozolotin Does this pique your interest?

**Comment by Andrei-Pozolotin** [comment]
@rkuhn sure.

1) kamon does this already 
https://github.com/kamon-io/Kamon/blob/master/kamon-system-metrics/src/main/scala/kamon/metrics/NetworkMetrics.scala

2) probably it would help to produce module to be shared by akka + kamon

3) I need a vacation from metrics :-)

**Comment by rkuhn** [comment]
The link to Kamon is a good point.

**Comment by patriknw** [comment]
interesting feature, but closing due to lack of interest
