### ISSUE TITLE
DOC: Help users and Google find latest stable docs

### ISSUE THREAD

**Issue by richdougherty** [akka/akka#12760]
imported from https://www.assembla.com/spaces/akka/tickets/2760

A search for "akka scheduler" doesn't show the latest stable release in the top results. It shows 2.0.3 and snapshot, but the current release is 2.0.4.

Maybe we could help Google (and users) find the best docs by including a link at the top of each old 2.0.x release pointing them to the latest one.

Could also consider using <link rel="canonical" href="..."> to point to current versions of docs, but that might be a bit aggressive.
http://googlewebmastercentral.blogspot.se/2009/02/specify-your-canonical.html

**Comment by rkuhn** [comment]
One part has been done in #19844, sitemap remains to be done. We should also retrofit the canonical links for the already published docs.

**Comment by patriknw** [comment]
done
