### ISSUE TITLE
create ProtoBuf serialization formats for all system messages

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#12789]
imported from https://www.assembla.com/spaces/akka/tickets/2789

This includes SystemMessage as well as all Akka-defined user-level messages. And everything required for Props.

**Comment by huntc** [comment]
Here are the messages that I quickly found by enabling `akka.actor.serialize-messages`:

```
[akka.actor.SystemGuardian$RegisterTerminationHook$] [akka.cluster.InternalClusterAction$GetClusterCoreRef$]
[akka.cluster.InternalClusterAction$PublisherCreated]
[akka.actor.StopChild]
[akka.actor.Terminated]
```

I'm sure that there are more though.

**Comment by patriknw** [comment]
I'm not sure about StopChild, but the others are only used locally (and can be marked as such)

**Comment by patriknw** [comment]
this is done as far as I know
