### ISSUE TITLE
DOC: Set up site maps to make our search results better and allow us to index docs beforehand

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#12796]
imported from https://www.assembla.com/spaces/akka/tickets/2796

Google Webmaster Tools have been set up, but we need to understand and create sitemaps for akka.io and doc.akka.io

Information should go into othe internal wiki:
https://wiki.typesafe.com/mediawiki/index.php/Google_Webmaster_Tools_for_akka.io

Relates to #12760

**Comment by rkuhn** [comment]
included in #12760
