### ISSUE TITLE
Akka OSGi / Aries / 2.10.0-RC3 versions

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#12792]
imported from https://www.assembla.com/spaces/akka/tickets/2792

As per request I am creating this ticket from the [[url:https://mail.google.com/mail/ca/u/0/#inbox/13b875c71a08d808|discussion]] in the mailing list.

Essentially I needed to change the bundle manifest in one of the Akka bundles to get the Aries Blueprint support running in my container:

I ll try to find time to upload the test case, but for some reason, scalatest didn't work in pax-exam for me. I ll revisit that as soon as i find time. 

Andreas

From the thread :

---->> snip 

Hi Roland, 

I have changed the manifest of the bundle akka-osgi-aries by removing the import package for org.apache.aries.blueprint.reflect. 
I spent some time yesterday looking for that particular package as it was in the original manifest as in imported package. 
The package is in the library of org.apache.aries.blueprint/org.apache.aries.blueprint/0.4, but it is not exported. Looking at the code, 
I believe that is correct as that package only contains Implementation classes and IMHO shouldn't be exported. 

This is why I have tried to fix it by modifying the manifest and remove the package, which did the trick for me. 

Perhaps I was using the wrong bundle combination in terms of versions, but earlier versions of blueprint also did not export that package. 

As for fixing it: Depending on what you use for generating your manifests, sometime a misplaced import statement generates wrong import package, which might have happened in that case. I got bitten by that a million times or more. 

For completeness, my manifest is now:

Manifest-Version: 1.0
Bnd-LastModified: 1353971408960
Bundle-ManifestVersion: 2
Bundle-Name: com.typesafe.akka.osgi.aries
Bundle-SymbolicName: com.typesafe.akka.osgi.aries
Bundle-Version: 2.1.0.RC3
Created-By: 1.6.0_35 (Apple Inc.)
Import-Package: akka.actor;version="[2.1,2.2)",akka.osgi;version="[2.1,2
 .2)",com.typesafe.config;version="[0.4.1,1.1.0)",org.apache.aries.bluep
 rint;version="[0.3,1)",org.apache.aries.blueprint.mutable;version="[0.3
 ,1)",org.osgi.framework;version="[1.5,2)",org.osgi.service.blueprint.co
 ntainer;version="[1.0,2)",org.osgi.service.blueprint.reflect;version="[
 1.0,2)",org.w3c.dom,scala;version="[2.10,2.11)",scala.collection;versio
 n="[2.10,2.11)",scala.collection.generic;version="[2.10,2.11)",scala.co
 llection.immutable;version="[2.10,2.11)",scala.collection.mutable;versi
 on="[2.10,2.11)",scala.reflect;version="[2.10,2.11)",scala.runtime;vers
 ion="[2.10,2.11)"
Include-Resource: /Users/viktorklang/Documents/workspace/akka/akka/akka-
 osgi-aries/src/main/resources,/Users/viktorklang/Documents/workspace/ak
 ka/akka/akka-osgi-aries/target/resource_managed/main
Private-Package: akka.osgi.aries.blueprint
Tool: Bnd-1.50.0

And I am using the following pax-runner configuration to start up my test container (this only works for me if the version of akka-osgi-aries in the local maven repo has my modified manifest).

scan-bundle:mvn:net.sourceforge.cglib/com.springsource.net.sf.cglib/2.2.0

scan-bundle:mvn:org.slf4j/slf4j-api/1.6.4
scan-bundle:mvn:org.slf4j/slf4j-simple/1.6.4

scan-bundle:mvn:org.apache.felix/org.apache.felix.configadmin/1.2.8

scan-bundle:mvn:org.ops4j.pax.logging/pax-logging-api/1.6.0
scan-bundle:mvn:org.ops4j.pax.logging/pax-logging-service/1.6.0
scan-bundle:mvn:org.ops4j.pax.url/pax-url-wrap/1.2.5
scan-bundle:mvn:org.ops4j.pax.url/pax-url-mvn/1.2.5

scan-bundle:mvn:org.apache.aries/org.apache.aries.util/0.4
scan-bundle:mvn:org.apache.aries.blueprint/org.apache.aries.blueprint/0.4
scan-bundle:mvn:org.apache.aries.proxy/org.apache.aries.proxy/0.4

scan-bundle:wrap:mvn:org.scala-lang/scala-library/2.10.0-RC3$Bundle-SymbolicName=Scala&Bundle-Version=2.10&Export-Package=*;version=2.10
scan-bundle:mvn:com.typesafe/config/1.0.0

scan-bundle:mvn:com.typesafe.akka/akka-actor_2.10.0-RC3/2.1.0-RC3
scan-bundle:mvn:com.typesafe.akka/akka-osgi_2.10.0-RC3/2.1.0-RC3
scan-bundle:mvn:com.typesafe.akka/akka-osgi-aries_2.10.0-RC3/2.1.0-RC3

I am happy to test another version / combination of versions if you want me to, but as far as I understand I am now using the versions Victor suggested earlier in the thread. If you are interested I can also provide a test case that would should the faulty behavior. 

---<< snap

**Comment by briantopping** [comment]
Does akka-osgi-aries even exist any more?
