### ISSUE TITLE
ThrottlerTransportAdapter provides slower speed when lending tokens

### ISSUE THREAD

**Issue by drewhk** [akka/akka#12825]
imported from https://www.assembla.com/spaces/akka/tickets/2825

ThrottlerTransportAdapter uses a token bucket to implement throttling. One tradeoff when setting up a token bucket is that the larger capacity it has, the less precise (more bursty) it becomes -- although it always maintains the average rate properly. To overcome this problem, the current implementation allows smaller capacities and "lends" tokens if the capacity is too low. The "lent" tokens will be "repayed".

The problem is that lending does not work accurately, and gives lower rates than it should, causing timeouts in some tests (ReliableProxySpec revealed this). The current workaround is to have a higher token bucket capacity.

**Comment by patriknw** [comment]
closing this due to lack of demand to fix it
