### ISSUE TITLE
Support node discovery through multicast

### ISSUE THREAD

**Issue by jboner** [akka/akka#13051]
imported from https://www.assembla.com/spaces/akka/tickets/3051

As an alternative to using seed nodes. The only need for seed nodes is to have a solution that works in virtualized envs (EC2 etc.). Using seed nodes is complicated and our impl have some startup rules hard to understand and use.

I think that we should also provide node discovery through standard multicast, as an option. It is a lot simpler to deal with.

**Comment by patriknw** [comment]
I'm surprised that nobody in the community has picked up this, but I'm closing it since it would be possible to do as an external project.

**Comment by ktoso** [comment]
AFAIR @bambuchaAdm had it almost working – is that effort alive any longer Bucza?
