### ISSUE TITLE
DOC: Introduce flow-control concepts and approaches for Actors

### ISSUE THREAD

**Issue by drewhk** [akka/akka#13083]
imported from https://www.assembla.com/spaces/akka/tickets/3083

Flow control comes up every now and then on the mailing list, and it is an important topic. Things to be covered:

 - What flow control is?
 - When does it matter?
 - Why does it matter?

 - What is buffering, why does it matter?
 - Dropping policies
 - Backpressure
 - Source rate control (tokens, throttling, etc.)
 - Sink based rate control (pulling, etc.)

also document sending to self to measure inbox size

**Comment by rkuhn** [comment]
Streams are the packaged solution for this problem, and their documentation already covers these aspects.
