### ISSUE TITLE
Adaptive branching factor for gossiping

### ISSUE THREAD

**Issue by drewhk** [akka/akka#13149]
imported from https://www.assembla.com/spaces/akka/tickets/3149

My draft, quick-shot proposal (change however you want):

Every gossip wire level message contains branching factor BF
There is a variable in every node, current branching factor CBF
There is a configurable initial branching factor IBF
There is a configurable dampening factor 0.0 < DF < 1.0
There is a configurable minimum branching factor MBF >= 1

On events that change my current version:
 - If I bump my version (fork) -> CBF := IBF
 - If I merge an external gossip G -> CBF := G.BF (or should CBF := max(CBF, G.BF) ?)
 - if no change -> CBF = MBF

On a gossip timer tick
 - Send CBF number of gossip messages, each having G.BF = max(CBF * DF, MBF)
 - Set CBF := MBF

There are some cases to be considered when multiple changes are disseminated at the same time, but I think it should work.

**Comment by patriknw** [comment]
Related #13530

**Comment by drewhk** [comment]
No, it is actually related to: #13658

**Comment by patriknw** [comment]
also interesting, but out of any near time scope
