### ISSUE TITLE
Improve JavaDoc

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13152]
imported from https://www.assembla.com/spaces/akka/tickets/3152

read through the whole of it, making sure that no formatting mistakes prevent information transmission; also transfer documentation from TestKit to JavaTestKit (mostly copy-paste).

**Comment by Captain1653** [comment]
The issue was created 8 years ago. Is it still needed?

**Comment by johanandren** [comment]
Let's close it and open up individual issues if there are more concrete problems with the Javadoc.
