### ISSUE TITLE
rethink cluster joining procedure

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13384]
imported from https://www.assembla.com/spaces/akka/tickets/3384

scenario:

* Join is sent from A to member B
* Welcome is sent from B to A but lost
* A is formally part of the cluster, will transition to UP and then UNREACHABLE
* the cluster cannot reach convergence without DOWNing A
* A cannot join the cluster anymore (because it is quarantined)

possible solution:

* make JOINING phase symmetric to LEAVING by adding a JOIN_REQUESTED which is similar to EXITING in its function, making sure that the transition to UP only happens if A has seen itself JOINING_REQUESTED
* possibly optimize this away by having A put itself into the Welcome gossip instead of letting B do it

**Comment by patriknw** [comment]
I think this is issue is obsolete. The original problem scenario is anyway fixed.

**Comment by hsn10** [comment]
In which Akka version its fixed?

**Comment by patriknw** [comment]
Have you tried 2.3.12? If you still see something that is not as you expect I suggest that we start a new discussion at akka-user followed by a new issue if we agree that there is something wrong.
