### ISSUE TITLE
either make akka-kernel really useful or drop it

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13476]
imported from https://www.assembla.com/spaces/akka/tickets/3476

currently it does not add all that much value: it would need to be a one-stop deployment solution to make sense, including handling for starting as a daemon on common operating systems, shutting down and possibly hot-adding JARs.

**Comment by rkuhn** [comment]
deprecate akka-kernel and document migration to sbt-native-packager

**Comment by patriknw** [comment]
Related #15677

**Comment by patriknw** [comment]
This is done, as far as I know.
