### ISSUE TITLE
DOC: describe our general pattern for writing an extension

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13489]
imported from https://www.assembla.com/spaces/akka/tickets/3489

like with IO, Cluster or anything which creates a “manager” actor and uses config to populate a Settings object

**Comment by Captain1653** [comment]
The issue is really old. I have found some documentation [Classian Akka Extension - Applicability](https://doc.akka.io/docs/akka/current/extending-akka.html#applicability) and [Extending Akka](https://doc.akka.io/docs/akka/current/typed/extending.html#extending-akka).

Is it still needed?

**Comment by patriknw** [comment]
I marked it as obsolete but missed to close it. Thanks.
