### ISSUE TITLE
Add support for joining UDP multicast groups to Akka IO

### ISSUE THREAD

**Issue by athempel** [akka/akka#13490]
imported from https://www.assembla.com/spaces/akka/tickets/3490

The Akka IO API should provide a means of using the functionality exposed by the java.nio.DatagramChannel.join operations in Java 7:

http://docs.oracle.com/javase/7/docs/api/java/nio/channels/MulticastChannel.html#join(java.net.InetAddress, java.net.NetworkInterface)

Without access to this functionality, it is not possible to receive UDP datagrams addressed to multicast addresses.

**Comment by rkuhn** [comment]
@athempel While figuring out the binary compatibility story for 2.4 (which tries to be backwards compatible with 2.3) we stumbled across this and AFAICS the simplest fix is to revert this change: I’m not sure why we did not discuss this option, but there is a `getChannel` method on all interesting types (Socket, ServerSocket and DatagramSocket) which means that the 2.3 callbacks are actually enough to access Java 7 features. Am I missing something?

**Comment by patriknw** [comment]
Related issue: #15626 with PR https://github.com/akka/akka/pull/15627

**Comment by rkuhn** [comment]
more discussion in #1867

**Comment by athempel** [comment]
@rkuhn I didn't see that possibility. Thanks for pointing it out.

**Comment by rkuhn** [comment]
Meanwhile some more memories came trickling in: I remember considering this and thinking “even so, the Java 7 API is nicer” because at the time we had not yet decided to go for binary compatibility. So in the end it is all my fault ;-)

**Comment by patriknw** [comment]
what is missing?
http://doc.akka.io/docs/akka/2.4.4/scala/io-udp.html#UDP_Multicast
