### ISSUE TITLE
allow configuration of whole actor sub-trees

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13493]
imported from https://www.assembla.com/spaces/akka/tickets/3493

e.g. setting the dispatcher for all descendants of some actor path; the difficulty is how to express “this one and all its descendants” with an obvious yet non-repetitive syntax

**Comment by hepin1989** [comment]
+1,how about attach some meta data for that path too  ?

**Comment by patriknw** [comment]
Closing in favor of #19872
