### ISSUE TITLE
Link to the reactive manifesto from the documentation frontpage

### ISSUE THREAD

**Issue by jboner** [akka/akka#13514]
imported from https://www.assembla.com/spaces/akka/tickets/3514

...and explain why and how Akka is reactive and fits into this blueprint. 
Will perhaps take a page or half a page. But I think it is important that we do it. 

Also fix: https://github.com/akka/akka.github.com/issues/50

**Comment by rkuhn** [comment]
it is already linked from «What is Akka?»
