### ISSUE TITLE
investigate load-balancing routers based on latency or backlog size

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13530]
imported from https://www.assembla.com/spaces/akka/tickets/3530

from a blog post comment on http://letitcrash.com/post/56958418119/2-2-spotlight-adaptive-load-balancing-based-on-cluster:

    Would latency, or backlog size be better default metrics for adaptive routing? If the heap is large, or the CPU usage is high you might assume that the node is slow, but surely it's better to just measure if the node is slow?

**Comment by ktoso** [comment]
Oh, while not exactly that we have gotten a nice contrib quite similar in concept to this.
Linking for reference: https://github.com/akka/akka/pull/18357 ( MetricsBasedResizer )
