### ISSUE TITLE
API marker for "Scala only"

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13560]
imported from https://www.assembla.com/spaces/akka/tickets/3560

Suggestion by Jonas:
Should we not state clearly "Scala API only" for the classes that are not intended for the Java API and vice versa? Ideally we should hide it, don't think the tools support that.
We need to make sure none is favoured. Apply the least common denominator principle. Present things in a generic way if possible.
What to do with code samples for the common classes? Make sure we have both Java and Scala versions everywhere?

**Comment by rkuhn** [comment]
This should be boy-scout rule: touch a method, fix the ScalaDoc (if not yet perfect).

/cc @drewhk @ktoso @johanandren @2m
