### ISSUE TITLE
Make all modules serialize-messages friendly

### ISSUE THREAD

**Issue by drewhk** [akka/akka#13561]
imported from https://www.assembla.com/spaces/akka/tickets/3561

Currently modules akka-actor-tests, akka-remote, akka-remote-tests, akka-cluster and akka-contrib are able to run with these settings. This needs to be extended over time to akka-camel, akka-zeromq, etc. This mostly means excluding tests and marking internal messages as NoSerializationVerificationNeeded.

**Comment by patriknw** [comment]
this is an really old ticket that probably was completed at some point, but I would guess that it must be revisited for the new modules akka-stream*, akka-http*

**Comment by drewhk** [comment]
Streams has it enabled afaik
2016. márc. 18. 8:27 ezt írta ("Patrik Nordwall" <notifications@github.com

**Comment by drewhk** [comment]
akka-stream and akka-http-core has serialization checks enabled.

**Comment by ktoso** [comment]
I guess this makes it closeable hm

**Comment by drewhk** [comment]
not all http modules have it enabled, but I think only http-core matters here.

**Comment by ktoso** [comment]
Yeah, I think so too.

**Comment by patriknw** [comment]
great, thanks for the update
