### ISSUE TITLE
ePub output is broken

### ISSUE THREAD

**Issue by drewhk** [akka/akka#13611]
imported from https://www.assembla.com/spaces/akka/tickets/3611

For some reason the ePub file is corrupted and only the contents can be viewed properly in ebook readers. The problem is reproducable with the Calibre ebook reader. If the file is unzipped, the html output is correct, so it seems like the metadata itself is somehow wrong.

**Comment by rkuhn** [comment]
Nobody seems to care enough and I can’t reproduce—should we remove ePub output?

**Comment by patriknw** [comment]
let's close as obsolete

**Comment by rkuhn** [comment]
but then we should also actually remove the epub, no?

**Comment by patriknw** [comment]
We don't know if it's broken or not, or if it's only a problem in certain environments. I would like more evidence that it is actually broken before removing, i.e. if someone care they should reopen or create a new issue.

**Comment by rkuhn** [comment]
affirmative

**Comment by ktoso** [comment]
Chat users report that it works in both ibooks and calibre (checked), not sure we should do anything here.
