### ISSUE TITLE
add tests for akka-camel in OSGi

### ISSUE THREAD

**Issue by chpache** [akka/akka#13622]
imported from https://www.assembla.com/spaces/akka/tickets/3622

in akka-camel, the Camel component resolver in OSGi should be able to use deployed Camel Components. This would tend to proove a better OSGification of the akka-camel module.

**Comment by briantopping** [comment]
@rkuhn Seems like one could use [setApplicationContextClassLoader](https://camel.apache.org/maven/camel-2.15.0/camel-core/apidocs/org/apache/camel/CamelContext.html#setApplicationContextClassLoader(java.lang.ClassLoader)) with `akka.camel.DefaultContextProvider#getContext`, but it would be horribly inefficient. BundleDelegatingClassLoader is O(logN) and I think it's only used for configuration resolution at the present time.

If there's still demand for this, I could dig further. OSGi and Camel are well-behaved together outside of Akka, so there should be a reasonable solution to this.

**Comment by rkuhn** [comment]
How does Camel load classes? We have so far refrained from adding OSGi dependencies to anything except akka-osgi, meaning that using the ActorSystem’s configured ClassLoader should either work here or we’d have to consider pulling in a whole host of dependencies.

**Comment by briantopping** [comment]
That would be a good direction to look. IIRC, there's an environment-dependent context that is created, I'd imagine the context contains the loader.
