### ISSUE TITLE
Limit the number of gossip targets using some notion of distance

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#13658]
imported from https://www.assembla.com/spaces/akka/tickets/3658

If we have a concept of distance in the Members of the cluster, maybe depending on position in the ordered set, we could limit the addresses we gossip to based on this "distance".

**Comment by rkuhn** [comment]
@drewhk said: a possibility would be to form a hyper-cube (with missing edges according to the node count) with dimension ceil(log2(N)).

**Comment by patriknw** [comment]
a lot of interesting things can be done ;-)
