### ISSUE TITLE
Tcp.Abort command getting stuck until next socket activity

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13686]
imported from https://www.assembla.com/spaces/akka/tickets/3686

http://stackoverflow.com/questions/19469515/akka-connection-abort

**Comment by patriknw** [comment]
is this still relevant?

**Comment by drewhk** [comment]
I think this is a duplicate

**Comment by patriknw** [comment]
ok, then I close it. I don't know what the duplicated issue is.
