### ISSUE TITLE
move cluster tools in akka-contrib to separate modules

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13711]
imported from https://www.assembla.com/spaces/akka/tickets/3711

We need to determine how we want people to interact with the cluster. My intuition is that things like PubSub and Singleton are good candidates to consider for canonicalization.

**Comment by jboner** [comment]
I like that structuring. I think that all high-level modules that build on top of akka-cluster should be in their own modules. There will be many more of these in the future.
