### ISSUE TITLE
Create a PropsFactory that reuses the reflective constructor

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#13754]
imported from https://www.assembla.com/spaces/akka/tickets/3754

To speed up things and consume less memory when creating actors with argument lists, we should create a PropsFactory that reuses the reflective constructor for a class and only validates the supplied arguments for each successive call.

**Comment by hepin1989** [comment]
How about making use of https://github.com/EsotericSoftware/reflectasm/?

**Comment by patriknw** [comment]
I'd rather move away from using reflection. Better to use real real constructors with the props factory method idiom.
