### ISSUE TITLE
Watching remote ask sender logs "actorFor is deprecated"

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13864]
imported from https://www.assembla.com/spaces/akka/tickets/3864

Because the temp path of the PromiseActorRef doesn't contain uid.
It's only debug logging and therefore not a big deal, but still confusing.

The RemoteWatcher will ignore such refs. Not sure if that is a problem.

**Comment by hepin1989** [comment]
@patriknw @ktoso should this be closed?

**Comment by patriknw** [comment]
Not sure this is completely solved. We still have debug log "actorFor is deprecated, and watching a remote ActorRef acquired with actorFor is not reliable".

Would be good to check if that is still logged for the case mentioned in the this issue, i.e. "remote ask sender". Perhaps we could just adjust that log message?

**Comment by patriknw** [comment]
done
