### ISSUE TITLE
ConcurrentModificationException in java.util.Map MDC

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13866]
imported from https://www.assembla.com/spaces/akka/tickets/3866

User report: https://groups.google.com/d/msg/akka-user/3JrDRdCQiIA/R_5c8cVlF-kJ

We should create a copy when converting to the scala immutable Map in DiagnosticLoggingAdapter.setMDC

**Comment by hepin1989** [comment]
one for release-2.3 and one for master

**Comment by rkuhn** [comment]
Upon closer inspection this ticket is not valid: we are indeed already making a copy during `setMDC`, which is also clearly visible in the original mailing list report. The CME was caused by the user through concurrent updates to the map, that is not something we can fix.

**Comment by hepin1989** [comment]
I don't think so.the scala api accept a immutable map.but the java one just accept a Map,which maybe a mutable one.

**Comment by rkuhn** [comment]
What I meant was that `jMdc.asScala.toMap` already does a copy, so there is nothing further for us to fix.

**Comment by hepin1989** [comment]
@rkuhn yes.I don't realize that.thanks,then should close them :P

**Comment by patriknw** [comment]
my bad when creating the ticket, thanks

**Comment by hepin1989** [comment]
my bad too for don't notice the ```toMap``` call ...
