### ISSUE TITLE
SSL/TLS: Add client-side certificate verification to akka-remote

### ISSUE THREAD

**Issue by RayRoestenburg** [akka/akka#13874]
imported from https://www.assembla.com/spaces/akka/tickets/3874

SSL/TLS client-authentication / client-side certificate verification

Also some other improvements:
- Make the configuration settings of security (SSL/TLS) less mandatory (sane defaults) so that you can run with default key and trust stores if you wish (on platforms like heroku it's not so easy to know where the defaul trust store is for instance) (#21667)
- Hostname verification. The JSSE spec says that when you use a raw SSLEngine you should do hostname verification yourself. 
- Support for SSL certificate pinning. (#21669)

**Comment by drewhk** [comment]
I am reviving this ticket from backlog. 

@wsargent  I think we should look at the TLS related things together in Amsterdam in person.

**Comment by wsargent** [comment]
@drewhk sounds good!

**Comment by EronWright** [comment]
Would this be possible today with a custom transport?    As a workaround until built-in support arrives.

**Comment by wsargent** [comment]
Hi @EronWright this is being worked on at https://github.com/typesafehub/ssl-config now.

**Comment by EronWright** [comment]
@wsargent will ssl-config cover the akka-remote scenario?   I see only mention of akka-http so I want to double-check with you.

**Comment by wsargent** [comment]
It's the goal -- there are some things that ssl-config doesn't cover right now from the server end, like disallowing client initiated renegotiation and so forth.

Right now if you want to use HTTPS with akka-remote, I would recommend https://github.com/square/ghostunnel as a wrapper.

**Comment by curreli** [comment]
+1

**Comment by wsargent** [comment]
Also see https://github.com/akka/akka-meta/issues/16 for Akka Artery, a custom Akka remoting transport layer.

**Comment by jrudolph** [comment]
I wonder how important host name verification is for akka-remote. 

For comparison: with https, host name verification means that a certificate authority certifies that a server is allowed to respond to requests for a certain hostname. This solves the scaleability problem that a client cannot potentially know the identity, roles and certificates of all servers up front. In other words: the certificate confirms that a peer has been verified by a trusted CA, the hostname in the certificate confirms that the peer also has a particular role, namely, to serve requests for that hostname. It prevents that two peers that are both certified by a trusted CA can impersonate each other.

(With ssh, you usually don't setup a PKI and use pinned public keys, instead. I.e. servers know the public keys of all the clients beforehand and clients learn the server public key on first use.)

So, do we need host name verification in akka-remote as well? I.e. when connecting to a peer, is it enough to know that it was certified by the trusted CA or do we also have to make sure that the peer we talk to is actually the one we intended to talk to? That would require that whatever authority issues the certificates has to know hostnames / ip-addresses of the nodes a service will later run on.

For akka-remote, I'd recommend the following two solutions:
 1) peers verify each other by requiring a certificate that was issued by a trusted CA (i.e. setup a PKI) but don't do hostname verification, nodes might impersonate each other
 2) peers are specified using a tuple (IP/Hostname, self-signed certificate (signature)) and verify that the peer reports the right certificate, i.e. is in possession of the private key statically associated with its address

WDYT?

**Comment by EronWright** [comment]
Please support (1) at minimum; in the age of containerized services there clearly are scenarios where hostname verification must be disabled.

**Comment by wsargent** [comment]
This is sort of covered in [RFC 2818](https://tools.ietf.org/search/rfc2818#section-3.1) if the client knows what the expected identity may be through other means: 

> If the client has external information as to the expected identity of the server, the hostname check MAY be omitted. (For instance, a client may be connecting to a machine whose address and hostname are dynamic but the client knows the certificate that the server will present.) In such cases, it is important to narrow the scope of  acceptable certificates as much as possible in order to prevent man in the middle attacks.  In special cases, it may be appropriate for the client to simply ignore the server's identity, but it must be  understood that this leaves the connection open to active attack.

The problem here is that hostname verification is expected, and users may operate under the assumption that nodes cannot and will not impersonate each other.  If peers verify that they are peers, but don't verify which peer is which, then there's no way (through TLS) to securely rely on the peer certificate being from the given peer -- but users may get access to the SSLSession anyway under that assumption.  

This is a use case that Play has specifically, i.e. https://github.com/playframework/playframework/pull/5737 and there are authentication / authorization checks that rely specifically on the provided certificate.  It may not matter if nodes are fungible, but they don't have to be.  It's better to have full on RFC 2818 / RFC 6125 service identity checks, even if there is an option to disable them.

**Comment by mnordie** [comment]
Hello.
What is the status of this issue? It is still marked as open, is anyone actively working on it?
I'm working on a project that use Akka that now requires all connections to be mutually authenticated with hostname validation.
Thanks

**Comment by jrudolph** [comment]
From the points above 1) was implemented but there's no hostname validation so far.

One reason, hostname validation is not implemented is that we don't have enough information about the particular certification management setups people might want to use.

@mnordie can you explain how your setup would look like? Do you have a PKI with a custom CA and distribute different certificates for every node? What is the threat scenario that checking hostnames would prevent against?

**Comment by mnordie** [comment]
Yes, private PKI with our own CA.
I guess the main threat is internal fraud. You shouldn't be able to copy a keystore from one node and start an illicit instance on another node.
The main driver for this is policy where all communication should comply with a given security checklist.
I'm evaluating the cost of implementing this in our Akka components.

**Comment by jrudolph** [comment]
> You shouldn't be able to copy a keystore from one node and start an illicit instance on another node.

But how would other nodes connect to that illicit node? There are two possibilities:
 * either DNS is compromised as well and the illicit node can be found under the old name (in which case host name verification won't help at all)
 * or the illicit node is the active part in the remote connection

If the illicit node is the active part in the remoting connection, TLS host name verification doesn't apply as that usually only runs on the client (= the illicit node) and not the server side.

Or are you asking for another feature not on the TLS level but on the remoting level that enforces that incoming connections are not allowed to spoof their own address? How would that work (something like TCP syn cookies?)?

**Comment by jrudolph** [comment]
> How would that work (something like TCP syn cookies?)?

Disregarding IP spoofing or DNS spoofing, maybe it could suffice to check that the host name that the remote node announces at least resolves to the sender IP address. That would still allow to run an illicit node on the same IP address under another port.

**Comment by jrudolph** [comment]
Let's discuss the remaining issue of host name validation in the new ticket #23565.
