### ISSUE TITLE
ActorClassification should unsubscribe terminated subscribers

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#13893]
imported from https://www.assembla.com/spaces/akka/tickets/3893

This task emerged during impl of https://www.assembla.com/spaces/akka/simple_planner#/ticket:3623 (EventStream using death watch instead of isTerminated).
ActorSelection based buses should work the same way with unsubscribing actors that terminate as EventStream does.

Related pull request: https://github.com/akka/akka/pull/2037

Suggested to schedule for 2.4 (by @rkuhn https://github.com/akka/akka/pull/2011#issuecomment-35864011 ),
since it's breaking API (ActorClassification now requires an ActorSystem). Could be rewritten to use an init method though - but the "require actor system" style feels more natural IMO.

**Comment by patriknw** [comment]
Implemented in ManagedActorClassification
