### ISSUE TITLE
Akka persistence - retrieve processor id from journal

### ISSUE THREAD

**Issue by agourlay** [akka/akka#13892]
imported from https://www.assembla.com/spaces/akka/tickets/3892

As discussed here https://groups.google.com/forum/#!topic/akka-user/Y8HNrGqVZ-g, it would be really useful to have an API on the Journal to retrieve the id of processors which have state within the Journal.

**Comment by ktoso** [comment]
This query will be one of the example queries in the new Query Side (experimental in 2.4):
https://github.com/akka/akka/issues/16541

However it means that journals may or may not implement this feature.

**Comment by patriknw** [comment]
@ktoso is this done (via the query PR)?
The actual impl for leveldb is in #18191

**Comment by ktoso** [comment]
Yes, thanks for closing.
