### ISSUE TITLE
FAILED: UdpIntegrationSpec couldn't bind to port

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#13908]
imported from https://www.assembla.com/spaces/akka/tickets/3908

https://jenkins.akka.io:8498/job/pr-validator-per-commit/1995/consoleFull

<pre><code>
[info] UdpIntegrationSpec:
Coroner Thread Count starts at 33 in akka.io.UdpIntegrationSpec
[info] The UDP Fire-and-Forget implementation
[info] - must be able to send without binding (14 milliseconds)
[info] - must be able to send several packet back and forth with binding *** FAILED *** (31 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected Bound(/127.0.0.1:58102), found CommandFailed(Bind(Actor[akka://UdpIntegrationSpec/system/testActor343#1436806301],/127.0.0.1:58102,List()))
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:328)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:314)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:707)
[info]   at akka.io.UdpIntegrationSpec.bindUdp(UdpIntegrationSpec.scala:22)
[info]   at akka.io.UdpIntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(UdpIntegrationSpec.scala:49)
[info]   at akka.io.UdpIntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(UdpIntegrationSpec.scala:45)
[info]   at akka.io.UdpIntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(UdpIntegrationSpec.scala:45)
</code></pre>

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2084/

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9005/
