### ISSUE TITLE
Remove deprecated STM Support for Agents

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13921]
imported from https://www.assembla.com/spaces/akka/tickets/3921

**Comment by hepin1989** [comment]
will remove ```akka-agent```?

**Comment by patriknw** [comment]
No (not that I'm aware of). This is only about removing the STM support from Agents.

**Comment by hepin1989** [comment]
then agent become only a safety cell for value right?

**Comment by ktoso** [comment]
Updated - we'll deprecate agents in 2.5 (not remove yet though)

**Comment by patriknw** [comment]
Is it too much work to remove the STM support and we just keep it until we remove all of agents?

**Comment by ktoso** [comment]
I'll give it a look - this we could remove right away in 2.5 you mean?

**Comment by ktoso** [comment]
I checked, it's a bit involved, not a few hours thing (I wouldn't be confident we provide the same semantics..).
So since we have it for 2.12 anyway (it's not blocking anything) I vote for keeping it until we remove.

**Comment by patriknw** [comment]
let's keep it, and remove all together

**Comment by patriknw** [comment]
meaning we can close this ticket
