### ISSUE TITLE
Hot standby PersistentActor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13938]
imported from https://www.assembla.com/spaces/akka/tickets/3938

A PersistentActor that operates in read-only, replay-only mode, similar to a View, but can then be promoted to a normal writing PersistentActor.
The purpose is to have a hot standby that can take over quickly without performing full recovery.
Originally discussed here: https://groups.google.com/d/msg/akka-user/EDDbRYgEKQ8/HDQBiOq36RkJ

We should evaluate if this feature is needed, or if it's too special.

**Comment by patriknw** [comment]
Here is a link to the recovery logic: https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L467

When looking at this now I think we should not use persistent query for this, since the ordinary replay has its own protocol (set of messages) to the journal. The hot standby should use the same protocol to ensure that it ends up in the same state.

**Comment by pearlson** [comment]
I assume that there would be some dependency on Akka clustering in this context. 

Replay protocol interactions would be confined between actors and store 

But, to transition active to standby and vice-versa, should failure-detection as "sensed" by clustering to act as "trigger" point for standby to active transitioning or vice versa - Some sort of "role-change-command" mechanism baked-in  

There are other aspects such as 
1. Startup roles of actors of same persistence-id - what would be the initial role and how it can be configured - starting with common role and running stuff like elections would make this extremely complicated - so a simpler mechanism would be required
2. Announcing Active <-> Standby transitions "role-changed-event" as Cluster events for a given persistence Id once the transition is made successfully

These requirements look like tying up this functionality closer to clustering. 

Thoughts ?

Regards
Muthu

**Comment by patriknw** [comment]
I don't mind tying it to cluster. It can be in `akka-cluster-sharding`, which is also much about persistence.

**Comment by patriknw** [comment]
Can be done with Replicated Event Sourcing
