### ISSUE TITLE
Remote deployment not carrying over Props.Mailbox nor Deploy.Mailbox

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13932]
imported from https://www.assembla.com/spaces/akka/tickets/3932

Originally reported here: https://groups.google.com/d/msg/akka-user/xv-7JhGCub8/Y2LHndLdxyIJ

**Comment by sachag678** [comment]
I'm wondering is there a workaround for this to be able to specify to the remote actor the Mailbox type?
