### ISSUE TITLE
BundleDelegatingClassLoader randomly loads classes from wrong classloader when running Pax Exam tests in native container

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#13977]
imported from https://www.assembla.com/spaces/akka/tickets/3977

The problem occurs when we are running tests using Pax Exam and in the Native Container.

The findTransitiveBundles method returns a list of bundles to use when loading classes specified in the configuration. This list is unordered and when bundle 0 is first in the list the classes will be loaded from the JVM classloader which then causes a ClassCastException. This causes the integration tests to be unstable. One simple solution is to sort this list in a descending order.

**Comment by briantopping** [comment]
This should be resolved by #19323, I didn't realize this issue existed before creating it. Should I close that one out and move the discussion here?

**Comment by patriknw** [comment]
@briantopping is this solved?

**Comment by patriknw** [comment]
Obsolete, see https://github.com/akka/akka/issues/28304
