### ISSUE TITLE
Incorrect reference to pluggable transport trait in documentation

### ISSUE THREAD

**Issue by borice** [akka/akka#13990]
imported from https://www.assembla.com/spaces/akka/tickets/3990

On this page: http://doc.akka.io/docs/akka/snapshot/scala/remoting.html
In the *Pluggable transport support* section, the reference to *akka.remote.Transport* is incorrect;  should be *akka.remote.transport.Transport*

It's possible that the 2nd example in that section may need fixing... not sure whether the reference below is correct...
<pre><code>
applied-transports = ["akka.remote.mytransport"]
</code></pre>

**Comment by hepin1989** [comment]
@bantonsson @borice 
should close this one by https://github.com/akka/akka/pull/16302

**Comment by 2m** [comment]
Thanks!
