### ISSUE TITLE
ScatterGatherFirstCompletedPool parameters

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#15039]
It's a common pattern to first list all parameters without a default value and then those with default. This makes it possible to omit all arguments for which defaults are available.

ScatterGatherFirstCompletedPool, on the other hand, defines the second parameter with default and the third without. Therefore one cannot write `ScatterGatherFirstCompletedPool(10, 1 second)`, instead one must write `ScatterGatherFirstCompletedPool(10, None, 1 second)` or `ScatterGatherFirstCompletedPool(10, within = 1 second)`.

Could the second and third parameter be switched, please? In order to maintain compatibility there could be an auxiliary constructor with the current list.

**Comment by patriknw** [comment]
I still agree, but can't see that we can change it
