### ISSUE TITLE
Java 8 API for Agents

### ISSUE THREAD

**Issue by jboner** [akka/akka#15055]
Can we add support for lambdas for Agents?

**Comment by jlprat** [comment]
If this is still relevant, I would like to take this issue :)

**Comment by patriknw** [comment]
We are actually going to deprecate agents in 2.5 and eventually remove it. If you are interested in maintaining Agents it could be an excellent  small library outside of Akka core.

**Comment by jlprat** [comment]
Actually, I was now checking, and this issue already "done". As of Scala 2.12, Function1 can be written with a Java lambda.

**Comment by jlprat** [comment]
I could update the docs, if you want. I will think about maintaining it as an outside library

**Comment by ktoso** [comment]
We're deprecating agents - please feel free to think about this and perhaps maintain it outside of akka :-) We'd gladly direct people towards it.

**Comment by ktoso** [comment]
See here for deprecation PR https://github.com/akka/akka/pull/21913

**Comment by patriknw** [comment]
@ktoso make sure that you check the milestone when closing such tickets, so it's not confused with that we have actually fixed it.

**Comment by ktoso** [comment]
Oh, I specifically put it on 2.5 hm, sorry - will not put them onto 2.5 if I find such tickets.
