### ISSUE TITLE
docs: EventBus should extend ActorEventBus since 2.3.0

### ISSUE THREAD

**Issue by TimPigden** [akka/akka#15052]
in the examples on the EventBus page all extend  EventBus but actually duplicate the code from

```scala
trait ActorEventBus extends EventBus {
  type Subscriber = ActorRef
  protected def compareSubscribers(a: ActorRef, b: ActorRef) = a compareTo b
}
```

so should really extend `ActorEventBus` instead.

**Comment by hepin1989** [comment]
I don't this this issue is valid .should be close.

**Comment by patriknw** [comment]
yes, it looks like this has been solved
