### ISSUE TITLE
add `wireTap` combinator for monitoring

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15077]
A `tee` produces to an external consumer, but does not propagate back pressure from this consumer into the main stream, instead it only copies items to the monitoring stream whenever that has signaled demand as well, dropping items on that output otherwise.

**Comment by rkuhn** [comment]
Reviving this ticket after a change in FlowOps policy.

**Comment by drewhk** [comment]
Yeah, but this is still a rather specialized construct. Do you think it is worth to put it on FlowOps?

**Comment by viktorklang** [comment]
@drewhk It seems generally useful though? It is an excellent way of chaining Sinks unto a Flow/Source while still allowing it to be meaningfully composed.

**Comment by drewhk** [comment]
I am not sure we are talking about the same thing. The original ticket says this:

> A tee produces to an external consumer, but does not propagate back pressure from this consumer into the main stream, instead it only copies items to the monitoring stream whenever that has signaled demand as well, dropping items on that output otherwise.

I.e. this is a non-backpressured broadcast. While it is a useful pattern for sure, I am not sure about how general it is.

**Comment by viktorklang** [comment]
@drewhk Good point. I'm talking about sugar for Broadcast.

**Comment by drewhk** [comment]
Yeah I know, but that is #17827 right?

**Comment by viktorklang** [comment]
Yeah, true.
Thinking about this Issue specifically I'm not sure if this feature should be made easy, since it injects side-effects and encourages the wrong kind of programming (just as I don't recommend people to use Future.onComplete/onFailure/onSuccess)

**Comment by drewhk** [comment]
I think this proposal will still accept a Sink (i.e. not as much as onComplete, but more a rate-detached operation), the difference is that it does not delay the "main-arm" if this side-sink is not ready, instead just drops. So in terms of the in-line broadcast sugar, this boils down to do an in-line broadcast with a droppy buffer on one-arm.

**Comment by viktorklang** [comment]
@drewhk But if we introduce the equivalent of `alsoTo(s: Sink)` the question is if we shouldn't just recommend people to do: `alsoTo(Flow[X].buffer(n, drop).to(yadda)`

**Comment by drewhk** [comment]
I think we are talking about the same thing. Given an in-line broadcast, this ticket is just a simple pattern which probably does not deserve a specific sugar method.

**Comment by viktorklang** [comment]
Yep, we agree on that :)

**Comment by viktorklang** [comment]
Since we have `alsoTo` now, I deem this closeable.

**Comment by rkuhn** [comment]
The “not propagating back-pressure” part is not included in `alsoTo`, and I also think that Broadcast has the wrong termination semantics for this kind of usage, making it impossible to use `alsoTo` to implement `wireTap`. Therefore I am not yet convinced that we can close this.

**Comment by viktorklang** [comment]
@rkuhn What about `alsoTo(Flow[X].buffer(n, drop).to(Sink.theBismarck()))`

**Comment by rkuhn** [comment]
That does not terminate once the other (i.e. the real) sink is no longer interested. Would you like your logging statement to keep the stream running when everybody else already jumped ship?

**Comment by viktorklang** [comment]
@rkuhn Now that, my friend, is a very good argument.

**Comment by rkuhn** [comment]
Thinking about that: maybe `wireTap` should end up just being an additional argument to `alsoTo` that controls the “importance” of the other Sink in terms of termination. It depends on which is more discoverable.

**Comment by drewhk** [comment]
I more like the `tap` combinator than an additional argument.

**Comment by viktorklang** [comment]
@rkuhn @drewhk Isn't that consistent with an `eagerComplete` flag we have for merge?

**Comment by drewhk** [comment]
Not really. In case of broadcast `eagerCancel` would mean if one cancels, then the bcast cancels and stops too. In this case we don't want the cancellation of the logger for example to propagate. I.e. this is more like the analgoue of PreferredMerge (not completely though).
