### ISSUE TITLE
create test: CSV processor

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15078]
Create a test that runs for a configurable amount of time (X) that consists of a Producer that generates CSV records and sends them downstream (fan-out), then have Y number of processors that processes separate records and then sends their results downstream when the upstream completes, have an aggregator step that is a Consumer of the results of the processors (fan-in).

The purpose of this test is to simulate the parallel processing of a large CSV file at high speed and with stability.

**Comment by johanandren** [comment]
Doesn't seem useful to keep this ticket around anymore.
