### ISSUE TITLE
add flattening for streams: merge

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15089]
Merge elements from a configurable maximum number of simultaneously open substreams, using a configurable merge strategy (see #15079). Fail as soon as a substream fails.

**Comment by sirthias** [comment]
We need this now for HTTP.

(Simplified) use case: 
A connection pool to a host has this signature: `Flow[HttpRequest, HttpResponse]`.
The top-level API has the same signature, takes on arbitrary requests and is essentially implemented as:

```scala
requestFlow
  .groupBy(hostOfRequest)
  .map { case (host, hostRequests) => hostRequests via connectionPoolFlow(host) }
  .flatten(FlattenStrategy.Merge) // crucial!
```

/cc @jrudolph

**Comment by drewhk** [comment]
The above code would not preserve the order. Is this what you want?

**Comment by sirthias** [comment]
Yes. Order is not preserved anyway as we are on top of connection pools. I have simplified the signature maybe a bit too much above, in reality every request is accompanied by an opaque user-specified context object which serves for request/response association.

--

**Comment by rkuhn** [comment]
This will be based upon #17090

**Comment by loicdescotte** [comment]
+ 1 for `FlattenStrategy.Merge`, it would be really useful!

**Comment by atamborrino** [comment]
+ 1

**Comment by manuelbernhardt** [comment]
+1, this would be really quite useful. Is anyone aware of a workaround that could be used for the moment, or is there no easy workaround?

**Comment by loicdescotte** [comment]
@manuelbernhardt I think the easiest workaround is : 

```scala
val streams: Array[Source[A]] = ...

val mergedStream = Source[A]() { implicit builder =>
  val merge = builder.add(Merge[A](streams.length))
  for (i <- 0 until streams.length) {
    builder.addEdge(builder.add(streams(i)), merge.in(i))
  }
  merge.out
}
```

**Comment by pkinsky** [comment]
+1, any workarounds for turning a Source[Source[T]] into a Source[T] while merging elements would be really awesome

**Comment by ddispaltro** [comment]
Yes that would be great!

**Comment by jypma** [comment]
My current workaround for doing this involves combining the fanout part (`Source[T] -> Source[Source[U]]`) and the merge part (`Source[Source[U]] -> Source[U]`) into a single utility. I couldn't find a way to do it as an actual graph transformation, so I instead chose to provide a `Sink[T]` to put the source elements into, take a function `T => Source[U]`, and expose a `Source[U]` that provides the result for further processing.

An example is implemented in the [`FanoutAndMerge` class of akka-persistence-cassandra-query](https://github.com/jypma/akka-persistence-cassandra-query/blob/master/src/main/scala/akka/persistence/cassandra/streams/FanoutAndMerge.scala). That one has a few more semantics, but I'm sure it can be generalized.

**Comment by rkuhn** [comment]
I’m about to implement the real thing, possibly today.

**Comment by viktorklang** [comment]
@rkuhn Pics or it didn't happen

**Comment by pkinsky** [comment]
:heart:

**Comment by rkuhn** [comment]
finally!
