### ISSUE TITLE
Create streaming framing codecs for IO

### ISSUE THREAD

**Issue by drewhk** [akka/akka#15101]
Provide frame-length and delimiter-based framing codecs similar to the deprecated pipelines

**Comment by luksow** [comment]
Hey, any update on this one (or on which branch code for this feature lives)?

**Comment by bantonsson** [comment]
Hi @luksow, the full code pipeline replacement is still being worked on. There are some fundamental building blocks that needs to fall into place first.

If you just want to split a stream of ByteStrings at a certain delimiter, then there is a sample in the Streams Cookbook http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/scala/stream-cookbook.html#Parsing_lines_from_a_stream_of_ByteStrings 

There is also a recipe for splitting ByteStrings at certain sizes as well http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/scala/stream-cookbook.html#Chunking_up_a_stream_of_ByteStrings_into_limited_size_ByteStrings

**Comment by luksow** [comment]
Thaks @bantonsson for the links, I must have overlooked them while reviewing docs. I wrote this code several times before and it'd be just very nice to have it in std lib. I'm especially interested in synergy of  framing and Akka's serialization to have the possibility to 'push case classes' to TCP socket and receive them on the other side. Kind of scala-ish abstraction layer on bytes sends over the wire, just like in Akka actors.

**Comment by rkuhn** [comment]
This only requires to move my doc sample for BidiFlow into the library proper.

**Comment by rkuhn** [comment]
this is done
