### ISSUE TITLE
ClusterSingletonProxy should optionally drop messages instead of stashing

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#15110]
Currently I don't see any way to disable the stashing of messages when the cluster singleton isn't available. There should be an option to disable stashing, i.e. drop messages.

**Comment by patriknw** [comment]
It should probably not use stash at all, to make the buffering more explicit with a buffer size parameter. Drop oldest messages also makes more sense.

**Comment by patriknw** [comment]
Similar for ClusterClient, I think
