### ISSUE TITLE
Actor#postRestart should call aroundPreStart instead of preStart

### ISSUE THREAD

**Issue by mpilquist** [akka/akka#15126]
The current implementation of the `postRestart` method directly calls `preStart` instead of calling `aroundPreStart`. As a result, any lifecycle hooks defined in `aroundPreStart` are not called. As such, in order to hook actor start, the following is needed:

```scala
  abstract override def aroundPreStart() {
    super.aroundPreStart()
    initialize()
  }

  abstract override def aroundPostRestart(cause: Throwable) {
    super.aroundPostRestart(cause)
    initialize()
  }
```

Tested with Akka 2.3.2.

**Comment by patriknw** [comment]
We can't change this for compatibility reasons, and I think current way is good for the reasons mentioned earlier.

**Comment by ktoso** [comment]
Hah, I just found out about this the hard way last week ;-)
Yeah, current scheme gives more control... I'm ok with not changing.
