### ISSUE TITLE
Publisher from: `() => Future`

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15135]
Polling for next element returns a Future, completed (possibly later) with the element or error. Useful for tailing a resource when the elements might not be available yet.

The Future must also somehow be able to communicate normal completion of the stream.

**Comment by viktorklang** [comment]
Reinvention is the mother of reinvention!

**Comment by viktorklang** [comment]
No news here?

**Comment by drewhk** [comment]
This is in the 1.x milestone, we did not schedule it for 1.0.

**Comment by viktorklang** [comment]
Fixed by both unfoldAsync (also supports more than one result) and Source.single(() => Future(…)).mapAsync(identity) + asPublisher

**Comment by ktoso** [comment]
We should somehow document those more explicitly in the cookbook then. It's
simple once you know it but for beginners it's not trivial to realise that
what they're looking for is a trivial source and mapAsync.

Lets add a mini cookbook entry for such?
