### ISSUE TITLE
include failed requirement type in mailbox configuration error message

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15159]
Currently it says

~~~
produced message queue type [class akka.dispatch.UnboundedPriorityMailbox$MessageQueue] does not fulfill requirement for actor class [class services.CourseActor]
~~~

and it would be helpful to state what the requirement was.

**Comment by michaelahlers** [comment]
Just ran into this problem, too. The limitation isn't clear from any documentation I've seen.

**Comment by devisaneer** [comment]
I also just ran into this exact same problem - I'm not complaining in any way at all (good vides from me about akka), though a one liner limitation in the Mailbox section of the doco could be cool. As a side note/Q?  Is there any out-of-the-box way to use Stash with a Priority in  2.4 snapshot?
