### ISSUE TITLE
Add documentation about RecoveryFailure to FSM and PersistentActor docs

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15171]
As described here, https://groups.google.com/d/msg/akka-user/bxiPjRsItqc/hI1DwBkkCmwJ you need to handle RecoveryFailure in your FSM or else your FSM will just swallow the failure and keep stashing forever.

Add some docs with a `whenUnhandled` to account for that.

**Comment by patriknw** [comment]
I think I improved this in 2.4-M2
http://doc.akka.io/docs/akka/2.4-M2/scala/persistence.html#Failures
http://doc.akka.io/docs/akka/2.4-M2/scala/persistence.html#Journal_plugin_API
and a few other places inlined in the docs.
