### ISSUE TITLE
Make ByteString Serializable

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15170]
The ByteString class itself isn't serializable, only a subcategory called CompactByteString (things referencing a contiguous chunk of memory) is serializable. Why this difference was introduced isn't clear from the comments or the pull request #402.

There is also the question of what it exactly means to serialize a ByteString. Do you expect it to become one big contiguous array automatically?

**Comment by colinrgodsey** [comment]
submitted PR #17070

**Comment by colinrgodsey** [comment]
@bantonsson to answer your question about compactness: I implemented the serialization to produce a compact bytestring, but of the originating type still. Given that we have to serialize to an array anyways, it doesnt make sense to hold on to the 'sparseness'

**Comment by bantonsson** [comment]
@colinrgodsey I completely agree. That is the way that makes most sense.
