### ISSUE TITLE
Fully asynchronous snapshot store SPI

### ISSUE THREAD

**Issue by krasserm** [akka/akka#15188]
Simplified example [here](https://github.com/krasserm/akka-persistence-cassandra/blob/v-0.3/src/main/scala/akka/persistence/cassandra/snapshot/CassandraSnapshotStore.scala#L24).

**Comment by ktoso** [comment]
An interesting point we may want to discuss soon. 
// cc @akka/akka-team

**Comment by ktoso** [comment]
Read through the details of what was meant here, yes absolutely we'll have to change `delete` to return a Future.
