### ISSUE TITLE
add `bunch` combinator

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15237]
This one has a surprising versatility which we will need to adequately expose to the user; the best I could come up with so far is a `mode` argument:
~~~scala
sealed trait Mode
case object VariableWindow extends Mode // this does not limit the element rate
case object FixedWindowDropping extends Mode // limiting rate by dropping
case object FixedWindowBackpressure extends Mode // limiting rate without dropping

def bunch(maxElements: Int, maxWindow: FiniteDuration, mode: Mode)
~~~
We might drop the dropping one in favor of prepending a buffering/dropping element in from of this one where required.

**Comment by rkuhn** [comment]
This may be a very interesting thing to add once we have solved #16342.

**Comment by rkuhn** [comment]
Actually it is #16410

**Comment by viktorklang** [comment]
Isn't this "feature" available already with grouped and groupedWithin (+buffer?)

**Comment by rkuhn** [comment]
No, the reaction of excess rate is not yet modeled by the existing combinators. It is possible to implement using tick source, conflate, etc. but we might want to consider a shrink-wrapped solution, still.

**Comment by rkuhn** [comment]
this is done (and called `batch`)
