### ISSUE TITLE
Control last emit from TimerTransformer

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15306]
As pointed out by @rkuhn when the TimerTransformer and groupedWithin operator was introduced (#15091): a TimerTransformer cannot control when the last emission happens: think a buncher that strictly gathers things and emits every 5s, if upstream is completed 1s into the interval then the last bunch will be emitted 4s early.

**Comment by rkuhn** [comment]
This will be solved by the AsyncStages #16275.

**Comment by ktoso** [comment]
Async stage ticket is now: https://github.com/akka/akka/issues/17090

**Comment by drewhk** [comment]
And there are now GraphStages with timer support (and there is no AsyncStage, yay).

**Comment by drewhk** [comment]
Put it on M2 since we just documented the timer support, and AsyncStage was not official - so it is fair to say this was fixed now.
