### ISSUE TITLE
FAQ: cannot exit REPL

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15314]
point out that ActorSystem must be shutdown, otherwise REPL will wait indefinitely for its thread pools to shut down

**Comment by hepin1989** [comment]
should be this one?
https://github.com/sbt/sbt/issues/1697

**Comment by hepin1989** [comment]
same like this ?
https://github.com/xitrum-framework/xitrum/issues/502

**Comment by rkuhn** [comment]
The linked sbt ticket seems unrelated because that is only about `System.exit()` not doing what it is supposed to do within sbt. The same goes for the xitrum ticket. This ticket is only about starting a REPL, launching an ActorSystem, typing `:q` and seeing the sbt process hang indefinitely.
