### ISSUE TITLE
akka.io.tcp.{max-received-message-size and received-message-size-limit} both must be defined to be effective

### ISSUE THREAD

**Issue by pstrzelczak** [akka/akka#15326]
I suspect in the following code the string checked should be the same:
akka-actor/src/main/scala/akka/io/Tcp.scala:
(...)
    val ReceivedMessageSizeLimit: Int = getString("max-received-message-size") match {
      case "unlimited" ⇒ Int.MaxValue
      case x           ⇒ getIntBytes("received-message-size-limit")
    }
(...)

A suggested fix would be to introduce something similar to spray.io:
  def getPossiblyInfiniteIntBytes(path: String): Int = underlying.getString(path) match {
    case "infinite" ⇒ Int.MaxValue
    case x          ⇒ getIntBytes(path)
  }

Using it there would be no threat of strings inconsistency.

**Comment by patriknw** [comment]
Looks like this was fixed in https://github.com/akka/akka/commit/c8c07e7a9f8aa4a9b65a9a75e3eb29ea24a99f1f
