### ISSUE TITLE
stream: add more general `zip`

### ISSUE THREAD

**Issue by sirthias** [akka/akka#15341]
We have one problem in HTTP which we cannot properly solve with only the currently available stream operations. It's not extremely critical, i.e. we can continue as is, but nevertheless the issue should be addressed ideally before akka-http M1.

Helicopter perspective on the server-side HTTP pipeline:

              [TCP Bytes]
                  |
                  V
            Request Parser
              /        \
             /          \
      [HttpRequest]   [RequestCtx]
           /              \
          /                \
    User Application      Bypass
          \                /
           \              /
      [HttpResponse]  [RequestCtx]
             \          /
              \        /
             Bypass FanIn
                  |
                  V
            [HttpResponse]
                  |
                  V
           Response Renderer
                  |
                  V
              [TCP Bytes]

The renderer needs context data from the parser in order to be able to properly render an HTTP response. Since we don't want to tunnel these data through the user application we transport them via a dedicated bypass around the application and combine them with the applications response stream in the *Bypass FanIn*.

For the normal mode of operation the *Bypass FanIn* can be implemented with a simple `zip` followed by a `transform`. However, there is another use case for the *Bypass FanIn*: request parsing errors. If the parser determines a problem with the request it needs to trigger an error response. In these cases the error info flows through the bypass *without* the user application seeing any request, which means that the *Bypass FanIn* must produce an `HttpResponse` from an element coming in from the bypass side *without* waiting for a response from the user application (because there won't be one).

Since a `zip` always waits for one element from both upstreams we have currently implemented the *Bypass FanIn* as a `merge` followed by a `transform`. This works but requires potentially unbounded queues in the `transform` which is undesirable.
The problem is that `merge` always requests from both upstreams at max rate, which is not what we really want here.

What we want is a `zip` which, for certain elements, immediately dispatches to its downstream without waiting for the other upstream to produce an element.

One solution could be something like this:

    trait Flow[A] {
      def zipWithShortcut[B](
        other: Flow[B],
        leftShortcut: A => Option[B] = _ => None,
        rightShortcut: B => Option[A] = _ => None): Flow[(A, B)]
    }

This is a `zip` which, for certain kinds of upstream elements, allows me to conjure up an element for the other side which is then used to immediately complete the tuple to be produced to downstream.

There are probably other solutions to the problem (like an even more general fan-in operation), we are open for your proposals.

**Comment by rkuhn** [comment]
This has been successfully solved in HTTP using FlexiMerge.
