### ISSUE TITLE
TcpStream actors do not properly start up until both streams are connected

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15340]
see [mailing list discussion](https://groups.google.com/d/msg/akka-user/F8sUJ6dRtXs/I624TONQM_wJ); we should decide on what sensible semantics are

**Comment by rkuhn** [comment]
What Endre said.

**Comment by rkuhn** [comment]
Meaning: the current behavior is correct, but we need to document it adequately.

**Comment by drewhk** [comment]
Types and runtime checks disallow partially connected components now, this ticket is from the age where RS interfaces where directly exposed and no explicit materialization step was needed.
