### ISSUE TITLE
Fusing of operators over arbitrary graphs

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15364]
Performance optimisation. Especially simple and efficient to do with single element transform #15363. See experiment at https://github.com/akka/akka/pull/15305

**Comment by drewhk** [comment]
Now this is promoted to graph based fusing due to https://github.com/akka/akka/issues/16902

**Comment by drewhk** [comment]
Fusing will be done after M1

**Comment by drewhk** [comment]
@2m this is the ticket you actually work on :)

**Comment by rkuhn** [comment]
done in #19104
