### ISSUE TITLE
Relocate `akka.http.util.DateTime` to more appropriate place

### ISSUE THREAD

**Issue by sirthias** [akka/akka#15389]
Review discussion regarding `akka.http.util.DateTime`:

> @patriknw 
> is it motivated that we provide this util in Akka? (question for @rkuhn)
> 
> @drewhk
> This will be a controversial addition anywhere (might be accused of NIH). I am not against it, but we should carefully document the intended scope if we include this.
> 
> @sirthias
> We are certainly not against using something else that has equivalent perf characteristics.
> However, since rendering a Date header is required for all server responses (and we parse a Date header for all responses received) something light, fast (and immutable) is needed, i.e. java.util.Date et al are out of the picture.
> 
> @patriknw
> My intention was only to consider if it should be public. I understand that you need it internally. Is it also needed by users? I don't doubt that some will find it useful, but is it crucial in the context of using akka-http?
> 
> @sirthias
> It needs to be public because it is part of the model. E.g. here is the definition of a few headers relying on DateTime:
> 
> case class Date(date: DateTime) extends ModeledHeader
> case class `Last-Modified`(date: DateTime) extends ModeledHeader
> case class `If-Modified-Since`(date: DateTime) extends ModeledHeader
> 
> @patriknw
> ok, then it is all good, as public
> 
> @rkuhn
> Please open a ticket for investigating the (placement) options later.

**Comment by jrudolph** [comment]
This was done in 144830780946779512853712f7ed03d041a14065.
