### ISSUE TITLE
Move `akka.http.util.EnhancedXXX` features to `akka.util`

### ISSUE THREAD

**Issue by sirthias** [akka/akka#15387]
For example the methods currently in  `akka.http.util.EnhancedConfig` should really live in `akka.util.ConfigOps`.

**Comment by ktoso** [comment]
Once we've moved to master. 
And remove "StreamUtils" etc

**Comment by jrudolph** [comment]
Ticket moved to github.com/akka/akka-http
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
