### ISSUE TITLE
Release akka-zeromq 2.3.x for Scala 2.11

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15455]
when zeromq-scala-binding for Scala 2.11 has been published.

I tried to help by creating a [zeromq-scala-binding pull request](https://github.com/valotrading/zeromq-scala-binding/pull/27), but no response.

**Comment by kostya-sh** [comment]
It looks like that starting from version 2.3.7 akka-zeromq is available for Scala 2.11 thanks to a custom 2.11 build of zeromq-scala-binding created by Spark team: http://mvnrepository.com/artifact/com.typesafe.akka/akka-zeromq_2.11/2.3.7
