### ISSUE TITLE
Enable JavaDoc generation in akka-http-core

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15452]
JavaDoc generation is currently disabled in akka-http-core since it needs access to nested objects which isn't generated properly.

See typesafehub/genjavadoc#41

**Comment by rkuhn** [comment]
… and then make sure that the docs actually make sense.

**Comment by jrudolph** [comment]
I think I can fix this for now by disabling doc generation for a single file. I created #18056 to track the remaining issue.

**Comment by jrudolph** [comment]
PR in #18057.
