### ISSUE TITLE
Support Java 8's CompletableFuture & Option classes in Typed Actors

### ISSUE THREAD

**Issue by mmc41** [akka/akka#15483]
I would like to use a few Typed Actors in my Java 8 based project but without polluting my domain interfaces with Akka Dependencies (I belive it is an anti-pattern to make domain/business objects/interfaces depend on infrastructure stuff). Instead I would like to use plain (new) java interfaces with Java 8's Future/CompletableFuture and Option classes. I.e. my domain interfaces should be plain interfaces with NO direct dependencies to Akka or other 3rd party libraries. So I would like to consider Akka an implementation detail only. I would like Akka to support this (+ maybe some helper methods to convert between Java Futures/CompletableFuture/Options etc. and the Akka versions).

**Comment by rkuhn** [comment]
Given the current progress towards type-safe “normal” Actors (see #16665) we are planning on phasing out TypedActors, so fixing this issue is not a priority for us.
