### ISSUE TITLE
OSGI alternative to ActorSystemActivator

### ISSUE THREAD

**Issue by mmc41** [akka/akka#15485]
I would like to use Akka Actors in OSGI without having my Activator inherit from ActorSystemActivator. I have my own base classes that I would like to use and I do not like it when any library forces itself to be a "center of the universe". Instead I would like Akka's OSGI support to leave me and my own application in control, yet make it easy to integrate with Akka by offering an utility class (instead or in addition to the base class) that I can call into to active/deactive akka in OSGI.

**Comment by briantopping** [comment]
I did some of this kind of thing as well and am now going back to using `ActorSystemActivator`, if for no other reason than a means to clean it up a little by using it. 

One of the challenges and mistakes I made in the last few years was having a poor model of integrating the OSGi and Akka lifecycles. I think they make a lot more sense in the context of a Akka Cluster. If you compare the documentation pages of Persistence or Clustering and OSGi, there's no reason we couldn't improve them to the same level. Similarly, there's many ways to accomplish the same goals, so hopefully we can drum up some discussion on this if you're still interested.

**Comment by mmc41** [comment]
Sorry, not doing java stuff at the moment.

**Comment by atooni** [comment]
Hi there, we are working on an application, which is an integration framework based on Akka / Camel / OSGi. Our repo [1] is open source, perhaps it is of interest for others trying to use OSGi and Akka together. 

[1] https://github.com/woq-blended/blended
