### ISSUE TITLE
Snapshot section in akka-persistence docs should use PersistentActor

### ISSUE THREAD

**Issue by ktoso** [akka/akka#15508]
As per https://groups.google.com/forum/#!topic/akka-user/Wesmwd7DYWc

Update http://doc.akka.io/docs/akka/snapshot/scala/persistence.html#snapshot to use `PersistentActor`. 

This is part of the big `persistence` cleanup - creating explicit task so maybe the community would help us out here.

**Comment by rkuhn** [comment]
this seems to have been fixed
