### ISSUE TITLE
FAILED: RemotingSpec - using UDP transport

### ISSUE THREAD

**Issue by 2m** [akka/akka#15506]
One-off failure of `RemotingSpec`:
 - must be able to use multiple transports and use the appropriate one (UDP)

Failed with:

    java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for 42

Before the failure there was a bunch of `ERROR` log messages:

    [ERROR] [07/05/2014 05:50:47.616] [RemotingSpec-akka.remote.default-remote-dispatcher-7] [akka.test://RemotingSpec@localhost:12345/system/endpointManager/reliableEndpointWriter-akka.udp%3A%2F%2Fremote-sys%40localhost%3A33391-8/endpointWriter] dropping message [class akka.actor.ActorSelectionMessage] for non-local recipient [Actor[akka.udp://remote-sys@localhost:33391/]] arriving at [akka.udp://remote-sys@localhost:33391] inbound addresses are [akka.test://RemotingSpec@localhost:12345, akka.tcp://RemotingSpec@localhost:33155, akka.udp://RemotingSpec@localhost:33450, akka.ssl.tcp://RemotingSpec@localhost:54981]

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1179

**Comment by hepin1989** [comment]
encounter this too when the seed node is bound to `0.0.0.0:6666` and on another node,connect it via `192.168.0.125:6666`
![image](https://cloud.githubusercontent.com/assets/501740/12195137/02f1cda2-b630-11e5-87aa-d867cbaac5e7.png)
