### ISSUE TITLE
In akka-remote EndpointWriter NonFatal exception is not logged at error level.

### ISSUE THREAD

**Issue by beethere** [akka/akka#15530]
When using akka-remote in our prototype project we got a warn message "Failed to write message to the transport" without a clear stack of exception reason. The exception is just sent to the event stream. Subscribe to the event stream to get the exception reason is one choice. But during daily development an explicit detail error message will help a lot.

**Comment by patriknw** [comment]
Backporting to release-2.3 also: https://github.com/akka/akka/pull/17060
