### ISSUE TITLE
Doc: Improve java documentation about after pattern

### ISSUE THREAD

**Issue by ktoso** [akka/akka#15547]
The lack of call-by-name causes confusion about "when does this future actually start executing", as seen on: http://stackoverflow.com/questions/24772999/akka-scheduling/24780282#24780282

We should also show the 2nd api that works as expected (equivalent to scala's callbyname version).

**Comment by rkuhn** [comment]
The non-Callable method signature should be deprecated and removed, it is counter-intuitive and does not express the intent of the `after` pattern.
