### ISSUE TITLE
Fix "Contents" link in HTML documentation pages

### ISSUE THREAD

**Issue by ctoomey** [akka/akka#15556]
Per https://groups.google.com/d/msg/akka-user/qZRD-iU_9N8/L4YVmFMdz40J: Something that would improve the usability of the (generally great!) documentation for me at least would be to have the "Contents" link go to the main contents page for whichever language (Scala or Java) documentation is being viewed, rather than going up 2 levels to the page that has links to the Scala and Java documentation table of contents pages, such that I have to click the Scala or Java link to get back to the table of contents page.

E.g., once I've visited http://akka.io/docs/, decided to view the Scala HTML documentation and clicked through to the Scala table of contents page http://doc.akka.io/docs/akka/2.3.4/scala.html, then clicked through to a particular topic (e.g., http://doc.akka.io/docs/akka/2.3.4/scala/actors.html) , when I click the Contents link I should go back to the table of contents page for Scala not to a page that prompts me to choose Scala or Java again.

**Comment by rkuhn** [comment]
@ctoomey sorry for not seeing this earlier: I would definitely find the two-link proposal appealing and I have not yet investigated how to make that work.

**Comment by richard-imaoka** [comment]
I added the above pull request. The change looks like below. Does it look good?

Before:
![content-old](https://cloud.githubusercontent.com/assets/7414320/13913603/cd9a461c-ef8b-11e5-9f8b-f966a60aca02.png)

After:
![content-new](https://cloud.githubusercontent.com/assets/7414320/13913604/cfb22c76-ef8b-11e5-9a68-194c209be04d.png)

**Comment by ctoomey** [comment]
Thanks all for getting this done.
