### ISSUE TITLE
Add single-argument versions of persist et al. 

### ISSUE THREAD

**Issue by mikea** [akka/akka#15555]
I suggest adding single-argument versions of `persist`, `persistAsync` and `defer` to be able to write `.match(Event.class, persist(e -> doSomething))` instead of two levels of lambda I have to write currently `.match(Event.class, e -> persist(e, e1 -> ...))`

**Comment by ktoso** [comment]
Thanks for the feedback!
It's certainly doable (I verified if inference works as we'd need it to here, and it's ok), only question being if it's useful or confusing.

Here's example usages:

```java
        @Override
        public PartialFunction<Object, BoxedUnit> receiveCommand() {
          return ReceiveBuilder
            .match(String.class, in -> persist(in, e -> updateState(e)))
            .match(String.class, persist((String e) -> updateState(e)))
            .match(String.class, persist(e -> updateState(e)))
            .match(String.class, persist(this::updateState))
            .build();
        }

        public void updateState(String event) {
          // handle persisted event here
        }
```

```scala
final def persist[A](handler: Procedure[A]): FI.UnitApply[A]
```

I can see it being useful, esp. when many events will probabbly be handled like `persist(this::updateState)`, curious on others feedback on this API addition though, does it pull it's weight?

// cc @rkuhn @patriknw

**Comment by rkuhn** [comment]
This looks like command-sourcing to me: how frequently does this happen in an event-sourced application?

**Comment by ktoso** [comment]
Hm, very true - it is encouraging command sourcing.
AFAIR we want to not encourage this style which would render this ticket invalid.

**Comment by ktoso** [comment]
Coming back to it after a while I'd vote to close - as dicussed above, it's not what we want to encourage.
