### ISSUE TITLE
FAILED: presistence.PerformanceSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#15576]
One after another, then stabilised again

- https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1235/testReport/junit/akka.persistence/PerformanceSpec/An_event_sourced_persistent_actor_should_have_some_reasonable_throughput_under_failure_conditions/
- https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1236/testReport/junit/akka.persistence/PerformanceSpec/An_event_sourced_persistent_actor_should_have_some_reasonable_throughput_with_stashing_and_unstashing_every_3rd_command/

`akka.persistence.PerformanceSpec.An event sourced persistent actor should have some reasonable throughput with stashing and unstashing every 3rd command`

failed with: 
```
assertion failed: timeout (100 seconds) during expectMsg: 
```

**Comment by patriknw** [comment]
last comment one year ago, closing

**Comment by ktoso** [comment]
:+1:
