### ISSUE TITLE
Discuss / Investigate: switch LevelDB to a similar DB for Persistence

### ISSUE THREAD

**Issue by ktoso** [akka/akka#15585]
We keep having "random" and very hard to investigate timeouts with LevelDB.

Looking for similar problems on the net I found that write stalling seems to still be a popular problem with LevelDB (basically: compacting can't keep up, so stalls everyone sometimes). The Riak guys have forked and patched LevelDB because of this: https://github.com/basho/leveldb ( http://riak-users.197444.n3.nabble.com/high-99-9-latencies-with-leveldb-backend-td4025818.html )

Some reasearch is in this task too: https://github.com/akka/akka/issues/15575

Related test failures:
- https://github.com/akka/akka/issues/15407
- https://github.com/akka/akka/issues/15575
- https://github.com/akka/akka/issues/15097
- https://github.com/akka/akka/issues/15559

Candidates to check: 
- Basho's LevelDB: https://github.com/basho/leveldb
- RocksDB: https://github.com/facebook/rocksdb/wiki/RocksJava-Basics
- HyperLevelDB http://hyperdex.org/performance/leveldb/ (I actually read a paper about them last week, the hyperspace hashing is interesting to be honest)

This issue is meant as *discussion thread* - please share your thoughts. Would be good to decide before `2.4`.

**Comment by ktoso** [comment]
Note: we won't be rewriting the sample journal (well basically that's what the LevelDB one is), in `2.4`.

**Comment by hepin1989** [comment]
then how about this:https://github.com/linkedin/PalDB

**Comment by patriknw** [comment]
It's a write once db :-)

Can you open a store for writing subsequent times?

No, the final binary file is created when StoreWriter.close() is called.

**Comment by hepin1989** [comment]
I haven't looked much into it:)

**Comment by drewhk** [comment]
My favourite is LMBD, but that is optimized for reads, not writes (although it gets still impressive write throughput): http://symas.com/mdb/

source code: 
https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/lmdb.h
https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c

10000 lines in total :D

**Comment by patriknw** [comment]
I don't think we should spend time on local only journals, and for testing leveldb seems to be good enough nowadays.
