### ISSUE TITLE
Scheduler sometimes increments delay by a tick when rounding up

### ISSUE THREAD

**Issue by jroper** [akka/akka#15598]
The following code should produce a value that is equal to the maximum time you can wait for the scheduler:

``` scala
val tickNanos = config.getDuration("akka.scheduler.tick-duration", TimeUnit.NANOSECONDS)
(tickNanos * Int.MaxValue).nanos
```

When you pass this number to the scheduler though, it throws an exception saying it's too far in the future.  Why?  Because the `roundUp` function in the scheduler is incrementing the delay by 1 tick, even though the delay is exactly divisible by the tick (thus it's breaking its contract).  This is because it uses `FiniteDuration./`, which returns a double, and then converting that back to a long, which through the wonders of imprecise floating point arithmetic, results in a delay that is one tick greater than it should be.

`roundUp` should not use `FiniteDuration./`, it should use a precise method, such as converting all values to nanoseconds, and then using a standard `long` divide.

**Comment by viktorklang** [comment]
Also, to the person addressing this Issue, please reduce the allocations in `roundUp` to ideally 1.

**Comment by hepin1989** [comment]
@patriknw This one should be closed.

**Comment by patriknw** [comment]
thanks
