### ISSUE TITLE
Util.mapTo with typed collections

### ISSUE THREAD

**Issue by matiwinnetou** [akka/akka#15607]
When working with Akka and Java API often type is lost on collections.

There is a Util.mapTo which is often used after evaluating a Future object and casting an object to desired type. The problem is that it does not work with typed collections.

Gson has a solution to this problem using: http://google-gson.googlecode.com/svn/tags/1.1.1/docs/javadocs/com/google/gson/reflect/TypeToken.html

which returns:

 java.lang.reflect.Type	getType() 
          Gets underlying Type instance.

Is there support planned for this in Akka at some point? Using Scala is not always an option.

**Comment by rkuhn** [comment]
Good point @patriknw & @ktoso, I agree that more descriptive types will both solve this issue and improve the code.
