### ISSUE TITLE
OSGi imports for akka-http-core broken, module unusable

### ISSUE THREAD

**Issue by alexparvulescu** [akka/akka#15628]
akka-http-core has a dependency to _akka-parsing-experimental_2.11 0.4_, but the OSGi import expects packages with the 2.3.x naming scheme, ex: _akka.parboiled2;version="[2.3,2.4)"_
I think this might be generated from the generic akka imports [0], and the same issue might apply to the stream dependency.
I'll try to come up with a solution, but I'm not too familiar with sbt :)

[0] https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-0.4/project/AkkaBuild.scala#L1234

**Comment by rkrzewski** [comment]
Fixed in #17979

**Comment by ktoso** [comment]
Thanks for the ping here, I missed it initially.
