### ISSUE TITLE
Add Java(8) API to contrib pattern ReceivePipeline

### ISSUE THREAD

**Issue by ktonga** [akka/akka#15642]
Now,  the ReceivePipeline pattern for chaining Actors interceptors is only usable for Scala. Once the Java8 is widely supported in Akka we could add API to the pattern that plays nicely with Java taking advantage of lambdas.

**Comment by harsh86** [comment]
I dont see it as part of 2.4.7 . When will this java API be available?

**Comment by ktoso** [comment]
The ticket is open as you can see, feel free to contribute it (it has the `community` tag, by which we encourage external contributions to this issue). Thanks in advance

**Comment by richard-imaoka** [comment]
I'm trying to understand the connection between Java 8 lambda and ReceivePipeline patterns. If I understand this correctly, lambdas can be passed to `pipelineInner()` and `pipelineOuter()`, using 
[Akka Java lambda patterns](http://doc.akka.io/docs/akka/current/java/lambda-actors.html#receive-messages) ?

[Receive Pipeline Pattern](http://doc.akka.io/docs/akka/2.4.9-RC2/contrib/receive-pipeline.html)

>//Scala ver.
>pipelineInner { case i: Int ⇒ Inner(i + 1) }

I haven't even compiled below but it is like this?

>//Java ver. 
>pipelineInner { match( Integer.class, i -> Inner(i + 1) ) }

**Comment by hepin1989** [comment]
move to https://github.com/akka/alpakka ?

**Comment by ktoso** [comment]
No, since Alpakka is strictly "connectors to things (using streams)"
The receive pipeline still exists here so the ticket is about adding Java API it seems

**Comment by jiminhsieh** [comment]
I found `ReceivePipeline` was deprecated since 2.5.0. Maybe we could consider closing this issue.

**Comment by raboof** [comment]
I agree, thanks!
