### ISSUE TITLE
Nested "persists" fail silently

### ISSUE THREAD

**Issue by DomBlack** [akka/akka#15640]
I accidentally ended up having nested persists within my Processor. My tests where failing due to timeouts, and it took me a while to figure out. It appears if you nest a persist within another persist's handler, it will silently fail.

Either this behaviour should be supported or an `IllegalStateException` should be thrown. The documentation isn't clear either way on what the intended behaviour should be.

Test Actor (added within PersistentActorSpec)
-----------------------------------------------------------
```scala
class NestedPersistProcessor(name: String) extends ExamplePersistentActor(name) {
    val receiveCommand: Receive = commonBehavior orElse {
      case Cmd(data) ⇒
        persist(Evt(s"${data}-a")) { event =>
          updateState(event)
          persist(Evt(s"${data}-b")) { _ =>
            updateState(event)
          }
        }
    }
  }
```

Test Method
-----------------
```scala
"nested persists works" in {
      val p = system.actorOf(Props(classOf[NestedPersistProcessor], "NestedTest"))
      p ! Cmd("1")
      p ! GetState
      expectMsg(List("1-a", "1-b"))
    }
```

Result of Test
-------------------
```
assertion failed: timeout (10 seconds) during expectMsg while waiting for List(1-a, 1-b)
```

**Comment by ktoso** [comment]
@DomBlack this has been fixed - nesting persists now works (`2.4-M2`), and we're releasing right now.
