### ISSUE TITLE
Add Source of Sources producer with back-off strategy

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15659]
In order to implement retry of producing from a source (e.g. by reconnecting to a live stream) we should add a factory that takes `() => Flow[T]` and produces elements while keeping track of failure rates and maintaining maximum reconnect rates etc. The outgoing flow can then be transformed (e.g. recovered) and flattened as needed.

---

remark: this is old: Flow means Source

**Comment by rkuhn** [comment]
this is one particular case of #19950

**Comment by drewhk** [comment]
Shouldn't this closed as a duplicate?

**Comment by 2m** [comment]
We now have `RestartSource.withBackoff` that takes a `Source` factory and supports backoff.
