### ISSUE TITLE
Restructure our dependencies

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15656]
As described by @sirthias:
akka-http itself wouldn't really need a dep on scala xml.
However, we do provide default (un)marshallers to and from NodeSeq (e.g. here, and because these currently live in companion-object-implicit-scope we do have a dependency.

What we could/should do:
Move the (un)marshallers for NodeSeq out into a dedicated trait/object and switch the dependency to provided scope.

**Comment by jrudolph** [comment]
This issue has been superseded by more recent decisions on how to structure modules.
