### ISSUE TITLE
Clarify that loglevel=DEBUG should be set when using slf4j

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15678]
Add to the documentation that no debug level events will be passed to slf4j if loglevel=INFO.

**Comment by johanandren** [comment]
Something like this in the SLF4j section?

Note that if you set the `loglevel` to a higher level than "DEBUG", any DEBUG events will be filtered
out already at the source and will never reach the logging backend, regardless of how it the backend
is configured.

**Comment by patriknw** [comment]
yes
