### ISSUE TITLE
Check server certificate CN/SAN against the actual hostname (once TLS is implemented)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15687]
See [RFC 2818](http://tools.ietf.org/html/rfc2818)

Other implementations:
 * Apache CXF: https://github.com/apache/cxf/blob/master/rt/transports/http/src/main/java/org/apache/cxf/transport/https/CertificateHostnameVerifier.java
 * async-http-client: https://github.com/AsyncHttpClient/async-http-client/blob/master/api/src/main/java/org/asynchttpclient/util/DefaultHostnameVerifier.java

**Comment by jrudolph** [comment]
With JDK 7 this can be implemented by adding one line using https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String). This would have the advantage that we don't need to implement a half-assed and potentially insecure x509 certificate parser to support SAN.

The links above have become invalid because most libraries have moved to Java 7. Can we assume Java 7 for akka-http (before the akka 2.4 merge)? Otherwise, if Java 6 compatibility is needed, we could use a reflective solution that enables endpoint verification on Java 7+ and requires a flag to switch it off for old clients?

**Comment by RichardBradley** [comment]
> Can we assume Java 7 for akka-http (before the akka 2.4 merge)?

(Please don't -- we're using akka-http with Java 6.)
