### ISSUE TITLE
Provide host-level client-side API

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15681]
Currently, only the connection-level client API is implemented. 

The host-level API allows to specify settings per host and provides a connection pool for requests sent to this host.

The request-level API is used to execute one-off HTTP requests without having to care for any details.

See also spray's documentation of this topic: http://spray.io/documentation/1.2.1/spray-can/http-client/

Related topics to keep in mind for this feature:
  * automatic redirection handling
  * proxy support
  * proper timeouts (see outstanding spray/spray#769)

**Comment by jrudolph** [comment]
If support for proxy servers and automatic redirection is added when implementing this feature, the interplay between both need to be addressed. See spray/spray#953.

**Comment by jrudolph** [comment]
This is part of the bigger initiative to support a high-level HTTP client interface as tracked as #16856.

**Comment by hepin1989** [comment]
connection pool in netty https://github.com/netty/netty/issues/3218 too
