### ISSUE TITLE
PersistentView isn't neither logging or passing the failures

### ISSUE THREAD

**Issue by khronnuz** [akka/akka#15694]
`PersistentView` is not doing anything with the cause on `onReplayFailure(receive: Receive, await: Boolean, cause: Throwable)`

When implementing a read model on a different project, some classes needed to deserialise events where missing, but the view was failing silently.

Only after adding the following code to my view I was able to track the issue:

```
package akka.persistence
class MyView extends PersistentView with ActorLogging {
...
  private[persistence] override def onReplayFailure(receive: Receive, await: Boolean, cause: Throwable): Unit = {
    log.error(cause, s"Failure during replay of PersistentView $viewId")
    onReplayComplete(await)
}
```

Please let me know if I should create a PR for this. I would love to contribute :)

**Comment by ktoso** [comment]
This needs a decision if we fix it now (I guess so, because PV may stay for a bit - even if we deprecate it, and the fix seems simple?)

**Comment by patriknw** [comment]
Taken care of in https://github.com/akka/akka/pull/17634
