### ISSUE TITLE
sync up benchmarks

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15693]
we need to pull all benchmarks from release-2.3 and release-2.3-dev forward to master before M1

**Comment by patriknw** [comment]
@ktoso do you know what this ticket is about?

**Comment by ktoso** [comment]
It sounds like it's about the fact that different branches have different benchmarks, we do not have all of them on master for example. It should be a simple copy paste to bring them in to master.

**Comment by patriknw** [comment]
doesn't sound urgent

**Comment by ktoso** [comment]
Not really, nope.

-- 
Cheers,
Konrad `ktoso` Malawski
Akka @ Typesafe

On 18 August 2015 at 11:59:00, Patrik Nordwall (notifications@github.com) wrote:

doesn't sound urgent
