### ISSUE TITLE
Revisit stream actor naming and hierarchy

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15707]
Naming and hierarchy was changed here: https://github.com/akka/akka/pull/15701
Tests were removed there, might be useful to bring them back when the proper naming and hierarch is in place.

**Comment by rkuhn** [comment]
Discussion of the supervision semantics resulted in the conclusion that the current way is very likely the right one, but we should still revisit the actor naming to make sure that it is good.

**Comment by drewhk** [comment]
Naming should be probably reflecting the nested nature of the streams blueprint, see https://github.com/akka/akka/issues/16902

**Comment by patriknw** [comment]
note that default names of sources and sinks should be named correctly, now they contain "unknown-operator"

**Comment by drewhk** [comment]
throw an exception where this default name is used, and see where it fails. This might work.
