### ISSUE TITLE
Establish logging policy in cases of error and propagation of actual exceptions

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15714]
E.g. in `HttpManager` we react differently on network errors caused by `Http.Connect` and `Http.Bind` commands:
  - an error during `Http.Connect` is DEBUG-logged and then it's reported to the commander containing the remote address in question
  - an error during `Http.Bind` is WARNING-logged and the singleton `BindFailedException` is reported to the commander

In both cases, neither the actual exception nor the message are reported back to the commander. This means it isn't possible for the commander to actually take responsibility for handling or reporting the error and thus it's easy to get into the old Java double logging anti-pattern.

I would propose a scheme where errors/exceptions are generally reported to the commander including the underlying message and if they are logged then only with DEBUG-level, to let the commander decide what to do with them.

It's probably not too useful to also send the stacktraces/original exceptions around, but there should be at least some way to log the stacktraces somewhere before they are discarded for debugging purposes.

/cc @sirthias

**Comment by jrudolph** [comment]
Also, see the suggestions in #16842, spray/spray#243 and https://groups.google.com/forum/?fromgroups#!forum/spray-user:

> * ERROR for unexpected internal conditions
> * WARN for remote peer triggered errors

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27
If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
