### ISSUE TITLE
Create Testkit for Streams

### ISSUE THREAD

**Issue by ktoso** [akka/akka#15748]
Expose and document `akka.stream.testkit` for users.

Goals of the testkit:
- [ ] supply tools for verifying stream pipelines
- [ ] supply docs for how to go about testing
- [ ] supply tools for verifying own transformations
- [ ] supply scaffolding for benchmarking pipelines
- [ ] maybe (??): supply easy way to include TCK verification of implemented elements?
- [ ] ActorSubscriber which one can drive from the outside

Notes: maybe reuse the normal testkit more than we do currently?

**Comment by drewhk** [comment]
Haven't this been done?

**Comment by 2m** [comment]
`akka.stream.testkit` has been released as a separate artifact. We still have docs to write which is covered by #17291. I'll close this one.
