### ISSUE TITLE
Akka TCP on server side might not signal Closed events if client goes away silently

### ISSUE THREAD

**Issue by drewhk** [akka/akka#15766]
Reported by user on ML: https://groups.google.com/forum/#!topic/akka-user/WdXWjcnVWiQ

It seems like that ServerChannel might not signal close in certain cases if nothing is written to the socket. We should try to reproduce the issue and see what we can do about it if it is reproducible.

**Comment by bantonsson** [comment]
This needs to stay on the 2.3.7 milestone since it was released there.

The better workaround has its own ticket #17000

**Comment by drewhk** [comment]
Superceded by ticket: https://github.com/akka/akka/issues/17122
