### ISSUE TITLE
DOC: Extend dispatcher docs to explain their usage in practice

### ISSUE THREAD

**Issue by drewhk** [akka/akka#15773]
Our dispatcher docs are currently very raw and do not say anything about when and how to split up a system between dispatchers, and when do you need some of the specialized ones.

**Comment by Captain1653** [comment]
The issue is really old. I have found [typed/dispatcher.md](https://github.com/akka/akka/blob/031886a7b32530228f34176cd41bba9d344f43bd/akka-docs/src/main/paradox/typed/dispatchers.md) . Is it still needed?

**Comment by patriknw** [comment]
Yes, it has been expanded. Let's close.
