### ISSUE TITLE
create ask() variant that can be used without sender()

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15819]
Currently `ask` can only be used with Actors that reply to `sender()` since the PromiseActorRef is not exposed for other usage. We should offer support for both variants:
~~~scala
val p = PromiseActorRef(system, timeout, "name")
target ! Cmd("hello", p)
val f: Future[Any] = p.future
~~~
and
~~~scala
implicit val timeout = ...
val f: Future[Any] = target ? Cmd("hello", _)
~~~

**Comment by hepin1989** [comment]
+1 for make PromiseActorRef public.

**Comment by drewhk** [comment]
Well, maybe not make PromiseActorRef public itself (can be hidden by a factory methods), but the idea +1

**Comment by rkuhn** [comment]
also see #17747 for another use-case

**Comment by ataraxer** [comment]
There is a problem with this use case:
```scala
val p = PromiseActorRef(system, timeout, "name")
target ! Cmd("hello", p)
val f: Future[Any] = p.future
```

When `ask` is used via a method or `?` operator timeout setup and dispatch of the message is essentially transactional, while the code above introduces a possibility to split those operations up.

Consider this example:
```scala
val p = PromiseActorRef(system, timeout, "name")
val data = longComputation()
target ! Cmd(data, p)
val f: Future[Any] = p.future
```

if `longComputation` takes more than `timeout`, than the promise will be completed with failure even before we send the `Cmd` message.

Possible solutions:
- use `PromiseActorRef` without timeout;
- add some kind of `withTimeout` method to `PromiseActorRef` which actually initiates a timeout, and should be used as follows:
```scala
val p = PromiseActorRef(system, timeout, "name")
val data = longComputation()
target ! Cmd(data, p withTimeout 5.seconds)
val f: Future[Any] = p.future
```

**Comment by hepin1989** [comment]
just switch the code order will fix the problem you provided.
```
val data = longComputation()
val p = PromiseActorRef(system, "name")
```
for the without timeout user case,I think Duration.Inf is OK.
