### ISSUE TITLE
add ByteStringBuilder.isEmpty method

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15825]
… and also nonEmpty, for convenience.

**Comment by hepin1989** [comment]
the current development is on branch release2.3-dev,so there are no this method.

**Comment by ktoso** [comment]
To be precise the "streams development branch is `release2.3-dev`, work does happen on master as well as release2.3.

Did not close this ticket yet as you can see, need to check if it needs backport or not.

**Comment by rkuhn** [comment]
no back-port needed
