### ISSUE TITLE
Fix TcpConnectionSpec on Windows 8.1

### ISSUE THREAD

**Issue by drewhk** [akka/akka#15823]
Currently the test  "forward incoming data as Received messages instantly as long as more data is available" is failing on Windows 8.1, very likely due to different OS side buffering -- i.e. this is not a bug, but the test is depending on actual OS buffering details that just happened to be working with Win7.

**Comment by patriknw** [comment]
@drewhk is this still a problem, or close?

**Comment by drewhk** [comment]
This is still a problem that test is AFAIK is still disabled.

**Comment by patriknw** [comment]
ok, thanks

**Comment by raboof** [comment]
I noticed "forward incoming data as Received messages instantly as long as more data is available" will succeed setting `akka.io.tcp.direct-buffer-size` to anything less than `128 KiB`.

If we're confident this is not a problem with the production code but simply the test making assumptions about the OS we might want to just update that setting - that's hard for me to say, though.
