### ISSUE TITLE
Add extractor for matched path

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15839]
There is currently only an extractor for the yet unmatched path, but for some things it is really useful to see what has been matched so far (e.g. to generate the right URLs for some responses).

**Comment by catalin-ursachi** [comment]
This doesn't necessarily seem like a trivial change. While it's easy to imagine what the 'matched path' should be taken to mean if you simply match path prefixes as you go along during routing, it's a much less well-defined concept if you:

* Match path suffixes as well as path prefixes;
* Having matched some path prefixes, call 'mapUnmatchedPath' to change the path to something else entirely; or, call 'withUnmatchedPath' on the RequestContext;
* Call 'pathPrefixTest' (or 'pathSuffixTest'), which looks at the path prefix (or suffix) without removing them from the unmatched path.

One option is to add to the Request context the following parameters: 'matchedPathPrefix' and 'matchedPathSuffix'; each of which is extended by one of 'pathPrefix' and 'pathSuffix', but unaffected by path tests or by unmatched path mappings. However, this would clutter the interface a fair bit, and could be potentially misleading if the path is manipulated in any non-obvious way.

**Comment by rkuhn** [comment]
Good points, @catalin-ursachi ! Would it make sense to clear the matched path pieces within the path mapping directive(s)? It seems that applying a transformation on the whole URL would invalidate that information, but on the other hand most routing structures do not do this at all—the common case will just do prefix matches.

**Comment by ktoso** [comment]
Closing as obsolete, we did not find a strong use case for it.
