### ISSUE TITLE
Report error if received `HttpEntity` is subscribed to twice

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#15835]
I'm using commit `4c4b6ee2` from the `w/init-http-routing` branch in anticipation of the new Http Streams API.

In Spray 1.3.1, `HttpResponse` was an immutable class, and it was safe to call `response.entity.asString` multiple times (and some of my test code does).

The comparable expression in the new API is something like:

    def getResponseBody(response: HttpResponse): Future[String] = {
      response.entity.toStrict(...).map { e =>
        e.data.decodeString(e.contentType.charset.nioCharset.toString())
      }
    }

(Separate but more minor issue: this charset handling needs improving.)

I have found that if I call "`getResponseBody`" twice on the same `HttpResponse`, that the the second and subsequent calls return an empty string, without error or warning.

I think this is a bug: if Akka disallows streaming the same response twice (which seems fair enough), then it ought to return a failed Future when calling `toStrict`.

(This highlights how `HttpEntity` is now effectively stateful / mutable (in Spray 1.3.1, the entity was immutable), but that’s unavoidable AFAICT. This should perhaps be highlighted in the docs, as it superficially appears to be immutable, given that it is declared as a case class.)

**Comment by rkuhn** [comment]
In order to get a stack trace that points to the right location (instead of some library code) we should just wrap the Entity’s Source with a MaterializableOnceSource that directly throws an exception during materialization.

**Comment by drewhk** [comment]
Superceded by https://github.com/akka/akka/issues/18080
