### ISSUE TITLE
Solve the circular dependency between internal ActorPublisher and its backing actor in a better way.

### ISSUE THREAD

**Issue by drewhk** [akka/akka#15859]
The most likely approach that could work is to reverse the responsibilities, instead of ActorPublisher being pushed into the actor via ExposedPublisher it should be the actor that pushes its ref into its corresponding ActorPublisher. Rationale:

 - ActorPublisher already needs to handle concurrent state
 - An actor might back multiple Publishers while a Publisher is usually backed by one actor

**Comment by rkuhn** [comment]
This is an internal cleanup and has nothing to do with the ActorRefPublisher.

**Comment by patriknw** [comment]
also related to the stash workaround

**Comment by patriknw** [comment]
Removed usage of stash mailbox in #16769, but leaving this ticket since it covers more than that.
For example I think we can take advantage of that most of the internal publishers only supports one subscriber.

**Comment by rkuhn** [comment]
Discussion: this is not that big of an issue to warrant a fix, especially since no grandiose improvements come readily to mind.
