### ISSUE TITLE
Turn on build parallelization by default

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15868]
It's currently switched off by default. See also this comment:
https://github.com/akka/akka/commit/47d65774e312afb540d88d1ff8f4e1687a641d6f#commitcomment-7753292

**Comment by ktoso** [comment]
Note: Not directly addressed (parallel not enabled currently) however we now have the dependency-changed-then-build ValidatePR task: https://github.com/akka/akka/pull/17397

**Comment by jrudolph** [comment]
Closing as a duplicate of the new issue #19512.
