### ISSUE TITLE
Fix OSGI for all akka-http projects

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15870]
Also see #15628

**Comment by drewhk** [comment]
/cc @sirthias @jrudolph 
Can we fix this until 1.0?

**Comment by sirthias** [comment]
Well, I can't. I don't know any OSGi foo. I guess we'll need the help of some OSGi expert.
Maybe @hseeberger can help?

**Comment by hseeberger** [comment]
<rant>Any library that uses class loaders explicitly is not OSGi friendly. That includes Akka. I have said numerous times that I would remove OSGi "support".</rant>

Having said that, I don't consider myself an OSGi expert any more. That was long ago in some dark ages ...

**Comment by rkrzewski** [comment]
I've managed to get Spray running in OSGi environment as a hobby project: https://github.com/rkrzewski/spray-osgi. I found myself jumping through a lot of flaming hoops to get it to run (see  [1] and the rest of the package). I concur that Akka is not the most OSGi friendly library around...
I guess I could help with getting the streams/http OSGi headers straight, but are you sure that there are people out there that want to use those as bundles? ;)

[1] https://github.com/rkrzewski/spray-osgi/blob/master/com.typesafe.akka.osgi.ds/src/akka/osgi/ds/impl/ActorFacade.scala

**Comment by rkrzewski** [comment]
I've produced a set of bundles for Scala 2.10 over the weekend: streams, http(-core) and marshallers. 
I'll post a PR for review tonight.

**Comment by ktoso** [comment]
Sounds excellent! We are preparing to release `1.0` today actually.
If you'd make the PR before "very late" I think it could make it into this cut. Let me know if this sounds realistic :-)

**Comment by rkrzewski** [comment]
Oh. I'm at the office right now, but in this case I'll do the PR ASAP.

**Comment by ktoso** [comment]
Thanks a lot and don't worry, we can wait a bit for this to come in, I'll happily delay the release until evening if we can fix osgi in 1.0 thanks to that :-)

**Comment by rkrzewski** [comment]
It's in. Handling `scala.xml` in 2.11 still needs fixing though.
