### ISSUE TITLE
LevelDB dependency

### ISSUE THREAD

**Issue by ahjohannessen** [akka/akka#15884]
LevelDB ought to be a separate dependency, e.g. "akka-persistence-leveldb", as most people likely will use something else in production.

**Comment by hepin1989** [comment]
+1 for moving out to a separate project

**Comment by Andrei-Pozolotin** [comment]
@patriknw please make repo or choose module name for the leveldb plugins

**Comment by patriknw** [comment]
it should be module `akka-persistence-leveldb` (akka-persistence-leveldb-experimental)
