### ISSUE TITLE
TLS support should do peer verification

### ISSUE THREAD

**Issue by wsargent** [akka/akka#15883]
TLS needs some kind of peer verification in order to be secure, but that verification generally exists on the application protocol layer (HTTPS, LDAPS, ESMTPS) rather than the TLS layer itself.  Typically the peer is verified through the DNS hostname against the X.509 certificate -- see http://tersesystems.com/2014/03/23/fixing-hostname-verification/ for details.

JSSE provides the SSLEngine / SSLSocket layer for protocol developers, but notes that anyone using SSLSocket must verify the peer themselves:
http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#ciphersuitechoice

SslTlsCipher uses SSLEngine directly and does not verify the peer, so either it needs a warning or a HostnameVerifier on it:

https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/io/SslTlsCipher.scala

Please check any fixes against a DNS proxy such as dnschef for verification -- see http://tersesystems.com/2014/03/31/testing-hostname-verification/ for details.

**Comment by ktoso** [comment]
This is hostname validation right?
We do it since inclusion of ssl-config.

**Comment by wsargent** [comment]
Yeah, this was pre-ssl-config.  Closing.

**Comment by ktoso** [comment]
Excellent, thanks!
