### ISSUE TITLE
Add TCK test of persistent snapshot with same seqNr

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15889]
A snapshot journal must be able to handle save of two snapshots with same sequence number, i.e. no persist in-between.

**Comment by ktoso** [comment]
Expected behaviour being overwriting the old snapshot I presume.
Previously our old filebase snapshot store would actually store multiple files with a timestamp,

**Comment by patriknw** [comment]
The behavior could also be ignoring the second attempt, i.e. idempotent. I'm not sure if there are any pros and cons implementation wise for plugins?
