### ISSUE TITLE
Create marshallers for interacting with JSON data

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15917]

**Comment by jrudolph** [comment]
Added #16812 to provide json4s support.

**Comment by ktoso** [comment]
PlayJson support is a community project now: https://github.com/guillaumebreton/play-json-support

**Comment by ktoso** [comment]
Related notes: since play support will live outside, we should use this style for all support traits - including spray-json. // or alternatively bring "spray-json" in as "akka-json" - this sounds less likely though?

This should probably be addressed before 1.0

// discussed this with @hseeberger

**Comment by ktoso** [comment]
We have finally reached a final consensus about where marshallers shall live.

We can not include play-json in akka itself. We do want to support Spray and the existing marshallers.
We will encourage the community to build and support external marshallers as separate repositories, such as @guillaumebreton's play support module.

This means that:
- current marshallers stay in akka/akka. We support them.
- akka-http-play is maintained by the community person, in his own repository // https://github.com/akka/akka-http-marshallers/issues/7
- If a customer will need support with play-json we'll see how to solve it then.
- akka-http-marshallers goes away.
- we close the this meta ticket, as we will not include more marshallers in akka itself. They should be community repos.
