### ISSUE TITLE
Add Java DSL for HTTP routing

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15911]
ideas:
~~~java
path("foo", segment, "bar", amount,
     get(new Completer {
         RouteResult run() {
           // do something with the current contents of segment and amount
         }}),
     put( ... ));
~~~
The extractions are handled by objects that are declared outside of the route and which receive their current values during the traversal of the route structure, to be usable within the Completer. The DSL itself if evaluated eagerly in full, building an AST that is verified type-wise before starting to run the route. This covers cases of user errors that are not accessible to compile-time verification, as in the path matchers shown above (which is implemented as `Object... args`).

**Comment by jrudolph** [comment]
The first step in this direction has been merged as https://github.com/akka/akka/pull/16308. Adding support for the remaining directives is tracked as #16436.

**Comment by jrudolph** [comment]
As #16436 has been fixed as well, I consider this fixed (pending upcoming documentation).
