### ISSUE TITLE
Port AnyParamDirectives from spray

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15934]
Use https://github.com/spray/akka/tree/w/init-http-routing/akka-http/src/main/scala/akka/http/routing/directives as a (probably outdated but previously already working) reference for the port.

**Comment by jrudolph** [comment]
If it is decided that those will be ported to akka-http as well then we need to fix the issue with default values described in spray/spray#981.

**Comment by ktoso** [comment]
Feedback from akka-user (Matthew Adams):

>> Do you have strong feelings towards having it forward-ported, i.e. an example use case where it indeed is very useful?
> Not in production code.  Only demoware.  Port forward as resources allow.

**Comment by sirthias** [comment]
Just my 2 cents here: I also deem the `AnyParamDirectives` quite heavy for the benefit they provide.
My guess is that they are rarely used and their implementation is somewhat complex.
If there is no strong need for them from "important" users I'd simply leave them where they are...

**Comment by ktoso** [comment]
Thanks for chiming in! Sounds like a good plan :)
