### ISSUE TITLE
Document way to unbind a HTTP connection

### ISSUE THREAD

**Issue by rklaehn** [akka/akka#15945]
Currently it seems to be impossible to unbind a HTTP connection. Or if it is possible, it is not straightforward to figure out how it works.

There should be a mechanism to unbind a HTTP connection and also some documentation like a webserver with proper setup and teardown. 

This example could be brought up to date and completed with unbind. http://doc.akka.io/docs/akka-stream-and-http-experimental/0.7/scala/http-core-server.html

**Comment by RichardBradley** [comment]
> Cancelling ServerBinding.connectionStream will unbind the socket. This needs to be documented properly. I changed the title to reflect that.

We'd like to be able to do a "graceful shut down" of an Akka HTTP server, i.e. to unbind from the TCP port so as to stop accepting new requests, but to allow the currently open requests to complete (for up to a configurable timeout).

See [https://groups.google.com/forum/#!msg/spray-user/Sfh8x5yWibU/I1gDhwoULYsJ] for the equivalent feature in Spray 1.3.1

Can we get Spray-equivalent support via cancelling the connectionStream?

**Comment by jrudolph** [comment]
AFAICS the documentation bits are in sync with what's currently implemented. Let's track the remaining feature request for a graceful unbinding with #16894.
