### ISSUE TITLE
Persistence: SnapshotSelectionCriteria and deleting Snapshots with a lower bound

### ISSUE THREAD

**Issue by corradio** [akka/akka#15955]
Hi,

This related to Akka persistence.
Why isn't it possible to delete snapshots with a lower bound using SnapshotSelection Criteria (http://doc.akka.io/api/akka/2.3.2/index.html#akka.persistence.SnapshotSelectionCriteria)?
It seems useful to be able to delete snapshots after a certain point, if e.g. a state update function had a bug in a certain version, and we want to replay all messages to recreate snapshots.

Thanks!

**Comment by ktoso** [comment]
Not sure if this should be included in 2.4. Deleting concrete snapshots is always possible with `deleteSnapshot(seqNr)`, needs some discussion
