### ISSUE TITLE
Add support for elastic routing

### ISSUE THREAD

**Issue by sirthias** [akka/akka#15959]
While working on HTTP ticket #15681 it became clear that implementing an HTTP connection pool is actually not much more than a certain configuration of an "(possibly elastic) router" for HTTP requests, that looks somewhat like this:

```
               elastic routing element                
         +- - - - - - - - - - - - - - - - -+          

         |  +-----> sub-stream 1 +------+  |          
            |                           |             
         |  +-----> sub-stream 2 +------+  |          
Requests    |                           |    Responses
+-----------------> sub-stream 3 +------------------->
            |                           |             
         |  +----->    ...       +------+  |          
            |                           |             
         |  +-----> sub-stream n +------+  |          

         +- - - - - - - - - - - - - - - - -+          
```

Ideally it'd be possible to add and remove sub-streams dynamically, however, even a static router with a given fixed number of sub-streams would probably be good enough.

Making a router like the depicted fully configurable would entail enabling (semi-)custom logic for these four key points:
- Distribute incoming elements into the sub-streams
- Merge demand of the sub-streams into the upstream
- Merge sub-stream result elements into the downstream
- Distribute demand from the downstream into the sub-streams

Cancellation appears to be relatively straight forward:
- if the downstream cancels we cancel all sub-streams and our upstream
- if a sub-stream cancels we either remove it (and run with the remaining ones, if any) or immediately cancel all remaining sub-streams as well as our upstream

Simple static router API using a potentially stateful `RouterLogic`:

```
type =>>[A, B] = ProcessorFlow[A, B]

def route[A, B](router: RouterLogic[A, B]): A =>> B

trait RouterLogic[A, B]() {
  type Key
  def subStreams: Map[Key, A =>> B] // only called once
  def onNext(value: A): Key
  def request(n: Long): Map[Key, Long]
}
```

With this design the two merge operations (merging sub-stream demand into the upstream as well as merging sub-stream results into the downstream) would be straight merges and not be user-configurable.

**Comment by freskog** [comment]
I have a use-case that looks somewhat similar to this. I have a stream of messages coming in from a RabbitMQ queue to a consumer node, and using akka persistence + sharding messages are sent to worker nodes for some stateful processing. Each worker node effectively has one actor representing the state for each user on a website. The state can be queried using HTTP directly from these worker actors.

This is all working at the moment, but it'd be great to use akka streams for applying back pressure the messages coming in from RabbitMQ and having the stream dynamically split based on group by (i.e., each new stream is processed in parallel) and even better would be if it integrated with the sharding approach.

**Comment by rkuhn** [comment]
This should now be done, we have all the GraphStage tools to make it nice (including SubSource/SubSink and SubFusingMaterializer plus local interpreter short-circuit messaging). It also ties into #19950.

**Comment by ktoso** [comment]
We also implemented `PartitionHub` http://doc.akka.io/docs/akka/2.5/scala/stream/stream-dynamic.html#using-the-partitionhub

Closing I think we're complete here?
