### ISSUE TITLE
add `ByteString::decodeString(java.nio.Charset): String` overload

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15965]
From https://github.com/akka/akka/blob/release-2.3-dev/akka-http/src/main/scala/akka/http/unmarshalling/PredefinedFromEntityUnmarshallers.scala#L41:

```scala
// FIXME: add `ByteString::decodeString(java.nio.Charset): String` overload!!!
```

/cc @sirthias

**Comment by ktoso** [comment]
Would be good to keep this one on our radar, we can do it once moved to JDK7+
