### ISSUE TITLE
Avoid saturating the remoting channel with large payloads

### ISSUE THREAD

**Issue by huntc** [akka/akka#15968]
In order to avoid saturating the remoting channel with large payloads (such as the contents of a file), an alternate channel could be provided.

Some background first: https://github.com/akka/akka/issues/15840#issuecomment-55052609

My recommendation is to consider using http and Multipart/Formdata as the protocol to communicate large payloads. One advantage of using multipart is that multiple large payloads (files even) can be transmitted using a well-known-protocol. A proprietary protocol built on top of Tcp could also be considered, but I suspect that this would be just re-inventing Http.

Perhaps such a service could in fact be provided as one of akka-http's higher level apis. For example perhaps `StreamingServer` and `StreamingClient` style actors could be provided where the server is offered streams to be provided for ephemeral access. The sequence of events could be something like:

1. A `PublishStream` message is sent by a caller to a`StreamingServer`. The message contains a `Flow[Part]` object where each Part is a descriptor consisting of a name, a map containing some user-required metadata, and a `Flow[ByteString]` representing the stream. This information can translate nicely to an underlying http multipart formdata implementation without exposing http or multipart to the user of the `StreamingServer`.
2. The `StreamingServer` acks the request with `StreamAvailable` which contains a `uri` to be used by a `StreamingClient`.
3. The caller messages a remote actor that then communicates the `uri` from the `StreamAvailable` message to a `StreamingClient` by sending a `SubscribeStream` message.
4. The `StreamingClient` will issue a `GET` request on the `uri` provided and then a `StreamSubscribed` message is replied to the remote actor. This message contains a `Flow[Part]` member that the remote actor can then use to consume the stream.

I have code that implements the above. :-)

**Comment by rkuhn** [comment]
I think this is tackled in lots of different places: Lagom provides its own support for streaming messages and the remoting rewrite will also take this into account.
