### ISSUE TITLE
Switch to sbt/sbt-protobuf plugin

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15988]
https://github.com/sbt/sbt-protobuf

**Comment by hepin1989** [comment]
i think using sbt-protobuf is a good choice,we are using it ,it works great.
just one more thing is to keep the protoc's version match the protobuf version defined in the build,and make sure the target folder only contains the generated classes files

**Comment by patriknw** [comment]
we might revisit once we have a problem with the current approach, but right now it just works
