### ISSUE TITLE
Akka FSM StateTimeout should have higher priority

### ISSUE THREAD

**Issue by simao** [akka/akka#16036]
Hello,

I am not sure this is a real problem and should be changed, or if there is kind of a workaround for this, any help would be appreciated.

Assuming that:

- I am using the `FSM` trait
- My Actor is receiving a very high number of Messages, `M`
- The Actor changes it state using `forMax(t)` in response to receiving one of this messages
- The new state expects to `Event(StateTimeout)` event after `t` seconds

The problem is that the `StateTimeout` message gets lost in the `M` and so `StateTimeout` gets delayed by much, much more than `t`, actually it ends up never happening in my case. My actor gets stuck in this state and `forMax` is never respected.

Is there a way to give `StateTimeout` a higher priority? Shouldn't this be the default?

Thank you!

**Comment by rkuhn** [comment]
StateTimeout is a ReceiveTimeout, so if messages are received then it does not trigger. Regular timers are different, and of course they need to go through the mailbox, so if the FSM is not responsive (a.k.a. overloaded) then timers will also not work right. I don’t think we should do something generically about this, if you want to use a PriorityMailbox then you can always do so (with the drawback of losing Akka’s message ordering guarantee, obviously).
