### ISSUE TITLE
Increase timeouts and add dilated to HTTP test durations

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16054]

**Comment by rkuhn** [comment]
This is important and should be done soon—many HTTP tests have unsuitably short timeouts that lead to CI flakiness.

**Comment by ktoso** [comment]
I agree, will do it next week

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
