### ISSUE TITLE
allow graceful ShardRegion shutdown

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16050]
For maintenance purposes it may be necessary to passivate all entries on a given node; this is internally implemented for HandOff, but currently not exposed to the user.

**Comment by dragisak** [comment]
+1

**Comment by hannesstockner** [comment]
+1

**Comment by prettynatty** [comment]
:+1:

**Comment by dcaoyuan** [comment]
+1

**Comment by anderius** [comment]
+1

**Comment by patriknw** [comment]
Hi all supporters,

I invite you to take a look at the [pull request](https://github.com/akka/akka/issues/17527) for this feature and verify that the functionality match your expectations.

**Comment by anderius** [comment]
Sorry if it is obvious somewhere, but is this now due for the next milestone release?

I am eager to test it out! :-)

**Comment by patriknw** [comment]
It will be in 2.4-M2, but that is a few weeks away, due to ScalaDays.
You can try it out with tomorrow's timestamped snapshot, you will find it here: http://repo.akka.io/snapshots/com/typesafe/akka/akka-cluster-sharding_2.11/
