### ISSUE TITLE
Figure out how to write generic code for Flow / Source (or: how to extend FlowOps)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16055]
As we ourselves currently aren't able to figure it out: https://github.com/akka/akka/pull/16049/files#r18580195

**Comment by rkuhn** [comment]
We should definitely figure out whether our API inhibits such extensions in an avoidable fashion.

**Comment by rkuhn** [comment]
We have revisited this and figured it out: the problem is that Scala will not be able to infer the necessary type constructors to make this work, and method overloading actually is a workable solution—at least it is much simpler than employing the magnet pattern or writing type lambdas by hand.

**Comment by jrudolph** [comment]
I don't think I understand. The current "solution" is duplicating all the code if you want a custom operation to be available both for Sources and Flows.

In the motivating example, however, the operation itself (`headAndTail`) can be modeled as a `Flow`. So, for that case the simple solution is to just provide the operation as a `Flow` and change the usages from `.headAndTail` to `.via(headAndTailFlow)` which works both for Sources and Flows and is still succinct enough IMO.

This should work in general as long as the operations are in a form that can be consumed by `via`, or `to`, etc. which should already cover most cases. So, I agree that this ticket can be closed :)

**Comment by rkuhn** [comment]
Thanks for this elaboration, I fully agree.

**Comment by drewhk** [comment]
Is there any example where an operation that is both available in Source and Flow that cannot be modeled as a Flow? I don't know of any except the terminator operations like .to, but they would return types that are not Source or Flow but RunnableFlow or Sink, which makes generalization hard. So I guess the overload+via method is the easiest.

**Comment by jrudolph** [comment]
@drewhk I agree. You could imagine something that wants to finish the pipeline and run it but in many cases it seems this wouldn't be the best way of abstracting things. Flows and graphs are the basic  abstraction to model stream operations so abstracting functionality into a flow should be considered the best practice.

**Comment by drewhk** [comment]
Well, thanks for the .via idea, because we missed that totally :D

**Comment by rkuhn** [comment]
This issue is finally understood and fixed in #19317.
