### ISSUE TITLE
strive to remove usage of `return` from Scala sources

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16074]
We have not been completely vigilant: there are two Coroner implementations, each of which contains a gratuitous `return` usage that can just go. The other two remaining uses are in parboiled2, where it looks like removing them would lead to less efficient byte-code, but that should be investigated.

**Comment by johanandren** [comment]
Cant find any other use of return than in Coroner in Akka 2.4

**Comment by patriknw** [comment]
parboiled2 is in (or was in) the release-2.3-dev branch (akka-http), but I don't think we should touch that
