### ISSUE TITLE
Support Cache-Control and Vary in the conditional directive

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16115]
This is a potential improvement that could be implemented for the CacheConditionDirectives.

`Vary`: http://tools.ietf.org/html/rfc7231#section-7.1.4

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
