### ISSUE TITLE
Add support for proxying HTTPS server connections on the client side

### ISSUE THREAD

**Issue by sirthias** [akka/akka#16153]
Required for one connection:

1. Establish plain-text connection to proxy
2. Send plain-text `CONNECT target.host:443 HTTP/1.1` request to the proxy
3. Wait for `2xx` response (afterwards all communication on the connection will be directly tunneled through to the target host)
4. Start SSL handshake, i.e. upgrade the connection to TLS/SSL
5. Send the actual requests, read actual responses

This feature should likely be implemented on the level of host-level client-side API as in most cases you'll want a managed connection pool to the proxy.

Some pointers:

- http://tools.ietf.org/html/rfc2817#section-5.2 (The other "upgrading a connection" parts of that RFC appear to be rarely used)
- http://stackoverflow.com/questions/6594604/connect-request-to-a-forward-http-proxy-over-an-ssl-connection/6594880#6594880

**Comment by salanki** [comment]
+1

**Comment by jkew** [comment]
+1

**Comment by rikardNL** [comment]
+1

**Comment by gonstr** [comment]
+1

**Comment by bdwashbu** [comment]
+1

**Comment by ktoso** [comment]
Relates to https://github.com/akka/akka/issues/17976

**Comment by nilsga** [comment]
+1

**Comment by carl297r** [comment]
+1

**Comment by ktoso** [comment]
Logging a "very big" +1 here, we may want to think how and when we could address this.

**Comment by ktoso** [comment]
Bumping to `pick-next`.

**Comment by ashugupt** [comment]
+1

**Comment by Madder** [comment]
+1

**Comment by mirelon** [comment]
+1

**Comment by ktoso** [comment]
Logging another +1

**Comment by andrasp3a** [comment]
+1

**Comment by rahulsinghai** [comment]
+1

**Comment by mlangc** [comment]
+1

**Comment by lregnier** [comment]
+1

**Comment by lregnier** [comment]
+1

**Comment by douglaz** [comment]
+1000

**Comment by ktoso** [comment]
Akka team won't be able (time wise) to pick up this issue in the short-term, so we'd like to encourage you to try to contribute this feature, or contact us if you'd like sponsor its development.

**Comment by nanothermite** [comment]
+1

**Comment by greenhost87** [comment]
+1

**Comment by nemccarthy** [comment]
+1

**Comment by Yeitijem** [comment]
+1

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by joolfe** [comment]
+1

**Comment by ktoso** [comment]
This ticket was moved, upvoting here won't do anything ;-)
Please use the 👍  icon on the first post of an issue to upvote, instead of posting +1 - thanks :)
