### ISSUE TITLE
Allow access to the MaterializedMap inside the Flow

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16168]
This is needed e.g. for an IO server API like the one sketched in #16162 and #16166 where it is hard to access per-materialization data inside the flow. One use case is that in akka-http we need to provide the remote address to the user.

To show this in a simpler example, an echo server could be implemented like this:

```scala
val echoFlow = Flow[ByteString].map(ByteString("Hello ") ++ _)
Tcp.generalBind(addr)(conn => conn.handleWith(echoFlow))
```

Now, you may want to access the remote address inside the Flow which handles a request:

```scala
val echoFlow = Flow[ByteString].map(ByteString("Hello ") ++ _ ++ ByteString(" at address ???"))
Tcp.generalBind(addr) { conn => 
  // there's conn.remoteAddress(MaterializedMap) but we don't have a MaterializedMap
  conn.handleWith(echoFlow)
}
```

One idea would be to provide an overload for the `transform` combinator which passes the `MaterializedMap` when the transformer gets instantiated:

```scala
def transform[T](mkTransformer: MaterializedMap ⇒ Transformer[Out, T]): Repr[T]
```

Then, the above (or something similar) could be implemented as:

```scala
val echoFlow = Flow[ByteString].map(ByteString("Hello ") ++ _ ++ ByteString("at address ???"))
Tcp.generalBind(addr) { conn => 
  conn.handleWith {
    Flow[ByteString].transform { matMap =>
      new Transformer[ByteString, ByteString] {
         def onNext(b: ByteString): Seq[ByteString] = Seq(b, ByteString(conn.remoteAddress(map).toString))
      }
    }
  }
}
```

/cc @sirthias

**Comment by rkuhn** [comment]
A proposal for how this could work can be found [here](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/stream-design.html#The_finer_points_of_stream_materialization). We’ll need to figure this out before 1.0.

**Comment by rkuhn** [comment]
This will likely be solved by offering the materialized value of a graph as a Source within that graph’s FlowGraph.Builder.

**Comment by drewhk** [comment]
@sirthias @jrudolph there is a PR for this: https://github.com/akka/akka/pull/17097

You can look at the test cases to see how it works: https://github.com/akka/akka/pull/17097/files#diff-f1e18fd8ee3a5d3436daae570bffd03d
