### ISSUE TITLE
Remove backwards compatible workaround in SnapshotSerializer?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16197]
When fixing #16009 I kept it backwards compatible, i.e. it can read old snapshots with the header in Java serialization format. That has a performance consequence (and code complexity).

Are we allowed to remove that workaround in 2.4?
If not, we should perhaps hide it behind a configurable flag (for performance reasons).

**Comment by patriknw** [comment]
I don't think we should touch this for 2.4. We could add a feature flag for optimizing it, it feels like we need a customer specific request before spending time on that.

**Comment by ktoso** [comment]
Agree on not touching it until required to. Move to backlog or 2.5?

**Comment by ortigali** [comment]
I think that this issue was solved in PR #16660, or is there something left to do?

**Comment by patriknw** [comment]
@ortigali This issue is about removing that hack as mentioned here https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/serialization/SnapshotSerializer.scala#L125

The reasoning is that by now everyone should have stored new snapshots with Scala 2.11 and therefore we don't need the workaround for snapshots that were stored with versions based on Scala 2.10. The motivation is to simplify the code of SnapshotSerializer and it might have a performance benefit also.
