### ISSUE TITLE
Introduce unbuffered Zip version

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16209]
If Zip is used for timing purposes an unbuffered version is needed. Basically the same Impl just buffer size set to 1 independently of materializer settings.

**Comment by rkuhn** [comment]
We should just have factory methods for Zip for both purposes—both are zipping things.

**Comment by viktorklang** [comment]
@rkuhn isn't it better to force to put a buffer in front of it if you want buffered behavior?

**Comment by drewhk** [comment]
Not exactly the same. The size of internal buffers set the maximum request() that is possible to send. For larger buffers request() traffic can be amortized more, less message sends. The Flow lewel buffer() element does not know about the RS API so even fusing it to the zip would not help (well, unless we detect that it is a buffer and as a special case we unfold it to an RS aware buffer).

**Comment by patriknw** [comment]
We decided to not add any new factory methods for this (at least not now).
