### ISSUE TITLE
DISCUSSION: Would >> be a better operator for linear flows than ~>

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16228]
@viktorklang at some point proposed using `>>` in linear flows (it would be an alias to `via`/`to`), semi-jokingly perhaps :wink:;
I was inspired by watching some CPPCON talks last evening to bring back this discussion before 1.0, proposal goes like:

```scala
import akka.stream.scaladsl.FlowImplicits._ // new implicits obj?

val flow = Flow[Int].map(_.toString)
val runnable = Source(List(1, 2, 3) >> flow >> Sink.future[String]

val runMe = Source(List(1,2,3)) >> (_.toString) >> (_.head) >> Sink.future[Char]
runMe.run()

val f: Flow[Int, String] = Flow[Int] >> (_.toString)
```

Upsides:
* anyone who has even seen a hello world in C++ immediately gets this (my guess is that this is "a lot of people") 
* this proposal also smuggles in `def >>(f: O => O2) = source.map(f)`
* mini upside: slightly nicer to type (IMO at least)

Downsides:
* so... we'd keep `~>` for non linear (graph) things I guess, so we have 2 operators now; maybe good, maybe bad
* how does this relate to our goal of "everything is a graph"

**Comment by rkuhn** [comment]
Is there really a patch on this shed that has only 13 layers of paint yet?

Seriously, though: I think that only Graphs should be Graphical.

On the upside: adding more syntax later is a non-breaking change.
