### ISSUE TITLE
Resurrect FileBodyPart

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#16257]
According to @jrudolph removed in https://github.com/akka/akka/pull/16183

**Comment by rkuhn** [comment]
Is this still needed given Akka Streams File Sources?

**Comment by jrudolph** [comment]
Only, if zero-copy file -> network transfer is still a goal.

**Comment by sirthias** [comment]
Yes, but even then a more general solution in the context of akka-stream / akka-io is probably more warranted than something http-specific.

**Comment by jrudolph** [comment]
Actually, this is completely unrelated to what I thought it was. Forget my comment.

This is about having a nice extractor to access multipart (formdata) BodyParts that contain files.

**Comment by sirthias** [comment]
Ah, I see.
This shouldn't be hard to do, I think.

**Comment by ktoso** [comment]
@hseeberger is this something you still care about?
We added some high level directives in `FileUploadDirectives` to help with files, but yeah those don't help if you use the low level apis - was that your use case?

**Comment by hseeberger** [comment]
Fine for me, that was for ConductR anyway.

**Comment by ktoso** [comment]
I see, thanks for the info. Keeping closed for now then :)
