### ISSUE TITLE
Automate API test coverage check for Java & Scala DSL

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16259]

**Comment by rkuhn** [comment]
We also need to re-enable the DSL consistency specs.

**Comment by ktoso** [comment]
Note:
- we have consistency specs enabled again
- keeping around since we want full coverage for javadsl, which I don't think we have at the current point (at least touching all APIs).

**Comment by drewhk** [comment]
This is too flaky to do manually, we probably need a coverage tool configured to only look for the usage of API methods.

**Comment by drewhk** [comment]
Is this ticket really needed anymore? If someone has a concrete proposal, please open a separate ticket. I mean we can have a ticket called "Improve Akka Streams" and keep it open forever :)
