### ISSUE TITLE
measure Streams performance for HTTP use case

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16260]
and tune IF unreasonable

**Comment by ngbinh** [comment]
The performance of `akka-http-experimental` 1.0-M5 is still about 15-20% of spray 1.3.3. I am wondering if there is something I can do to improve its perf? 

Thanks

**Comment by rkuhn** [comment]
Thanks for wanting to help! While we are still focusing on getting a stable feature release out, you could look into the worst offenders and see if there are some low-hanging fruit to be harvested. We do have plans to attack the following:

* substream handling will be made more efficient using AsyncStage
* fusing of linear operations into the same Actor
* eventually also fusing of junctions with linear stages in the same Actor

Much of the overhead stems from Actor creation, the performance difference is not so big for larger requests or responses (i.e. more long-lived connections), therefore reducing the number of created Actors will help in common benchmark scenarios.

**Comment by ngbinh** [comment]
Thanks, I will try to benchmark with more realistic scenario.

**Comment by drewhk** [comment]
Please understand that we will not do significant performance engineering before the 1.0 release, our current plan is to reach a stable API surface with minimal amount of bugs. Performance will be one of the focus of the post 1.0 roadmap.

**Comment by ngbinh** [comment]
@drewhk got it! Thanks for the clarification.

**Comment by jrudolph** [comment]
FTR: making fire at home will be much simpler with upcoming JDKs: http://techblog.netflix.com/2015/07/java-in-flames.html

**Comment by viktorklang** [comment]
Someone must create an sbt-plugin and call it fireplace.

**Comment by jrudolph** [comment]
:+1:

**Comment by rkuhn** [comment]
… and since 2.0 we had reports of HTTP being nearly as fast as Spray for normal cases :-)
