### ISSUE TITLE
Performance degraded when upgrading From Akka 2.3.6 to Akka 2.3.7

### ISSUE THREAD

**Issue by adamhonen** [akka/akka#16295]
I’ve upgraded to 2.3.7 and tried running a very basic performance test I do for the sake of sanity from time to time.
It’s something that I use to find big glaring performance bugs – I have my application run using a local database (Couchbase) on my own PC, as well as a small client simulator (also written using Akka) and just check how many operations a second it’s doing. So while this setup cannot be used to do any serious tuning, it is useful for spotting stuff like forgetting the logs in DEBUG.

I’ve tried running with 2.3.6 and 2.3.7 several times (going back and forth) and as basic as this test is, the results are consistent.
I get ~11K ops/sec with 2.3.6 and ~7.3K with 2.3.7.
The version of Akka is of course the only difference between each of the runs.

Looking at the thread view of visualvm I see one immediate difference between the two versions.
With Akka 2.3.6, the dispatcher threads seem to be spending less time in park state.
Of course, I’m not familiar at all with the internal Akka implementation, so maybe that doesn’t mean anything at all – it just looks to me as a useful hint.

Let me know what additional information I can supply in order to investigate this.

![dispatcher-threads](https://cloud.githubusercontent.com/assets/6965115/5018015/526f7cce-6abb-11e4-9f52-e013f5effee1.JPG)

**Comment by t3hnar** [comment]
I can see the same issue, reported in https://github.com/EventStore/EventStore.JVM/issues/30

**Comment by drewhk** [comment]
Superceded by new ticket: https://github.com/akka/akka/issues/17122
