### ISSUE TITLE
FlowGraphBuilder.connect() does not type-check as expected

### ISSUE THREAD

**Issue by maiflai** [akka/akka#16311]
Re: https://groups.google.com/d/msg/akka-user/rrsYhVhbktI/hUjO6S6fN0IJ

I expected a connection between an UnknownSink[A] and UnknownSource[A] to break when I accidentally changed it to the incompatible UnknownSink[A] ~> UnknownSource[_B_].

Martynas has experimented with changing the signature of FlowGraphBuilder.connect in this gist: https://github.com/2m/scala-sandbox/blob/296410007df8eb1bfa78e026a8295ab46401c307/src/test/scala/TypeParameterInference.scala

I think this looks ok - for my particular use-case I do not require an additional Vertex between the Sink and Source as it is a mechanism for me to connect directly-compatible partial graphs.

Thanks,
Stu.

**Comment by rkuhn** [comment]
I’m pretty certain that this is fixed with the new Graph DSL that relies only upon the ~> arrows.

**Comment by maiflai** [comment]
thanks very much - we'll upgrade to M4 and check

**Comment by drewhk** [comment]
Is this valid in M4?

**Comment by rkuhn** [comment]
FlowGraphBuilder.connect does not exist in this form anymore.
