### ISSUE TITLE
HttpEntity.Chunked transformDatabytes fails when a 'LastChunk' is present

### ISSUE THREAD

**Issue by Joe-Edwards** [akka/akka#16319]
The `transformDatabytes` method for a chunked entity will produce a stream that fails on the last chunk if it is an instance of `LastChunk`

e.g.
```
val entity = HttpEntity.Chunked(`text/plain`, Source(List(Chunk(ByteString("some text")), LastChunk)))

val transformedEntity = entity.transformDataBytes(() => new Transformer[ByteString, ByteString] {
    override def onNext(element: ByteString): Seq[ByteString] = element :: Nil
})

// stream in the entity
val strictEntityF = transformChunked.toStrict(timeout)

// throws IllegalArgumentException
Await.result(strictEntityF, timeout)
```

It looks like it creates a new Chunk from `byteTransformer.onTermination`, but if this is Nil (which is the default!) then it's creating a new empty chunk which throws an IllegalArgumentException.

A similar effect occurs if `byteTransformer.onNext` produces an empty (when joined) ByteString, though this is arguably more reasonable.

**Comment by jrudolph** [comment]
AFAICS this was fixed in the transformation from Transformer to Stage. If you can still reproduce @Joe-Edwards, please reopen.
