### ISSUE TITLE
ActorSelection use in AtLeastOnceDelivery

### ISSUE THREAD

**Issue by ryandbair** [akka/akka#16339]
AtLeastOnceDelivery's delivery method currently only accepts an ActorPath as the destination. From there, it internally creates an ActorSelection which is then used to actually send the message. 

When working with ActorSelections, this causes some unnecessary acrobatics as there isn't an easy way to go from ActorSelection to ActorPath. The two methods I am aware of is either sending an Identify message and dealing with the potential failure or taking the hack approach of `ActorPath.fromString(actorSelection.toSerializationFormat)`. 

Adding an overload of deliver that accepts an ActorSelection would improve usability significantly.

**Comment by ktoso** [comment]
@ryandbair, question related to supporting `ActorSelection` in `AtLeastOnceDelivery` – we agree it should be supported (and I'm finishing up a PR which does so). I was curious if you were also thinking of using it with wildcard selections? I found that it gets overly complex on ack-tracking thus deciding for now that we'll not support wildcard actor selections here, unless very strong community demand around it comes up.

PR coming soon :)

**Comment by ryandbair** [comment]
I have no need for wildcard selection support. I agree that it would add quite a bit of complexity to support an unlikely case. Conversely, its nice to limit runtime surprise. 

I'll take a look at your PR today. I'm looking forward to seeing this one in 2.4.
