### ISSUE TITLE
akka-* : warnings cleanup

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16334]
in recent pr
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/1304/

I observed that `[warn]` build entries comprise 552K out of 5.7M or 5365 of 36319 or 15% of lines of plain text build log. As a result of watching through this a dozen times,  faith in akka code quality starts to fade :-)

I am curious if every milestone/release should have a "50% warning reduction" goal,
till they reach 0.1%?

**Comment by jiminhsieh** [comment]
Is this issue still valid? I want to try this one. However, Akka is a big project, it's not easy to do all of them one time. My ideas is that I could list all sub-projects at checkbox then do it sub-project by sub-project.

**Comment by jrudolph** [comment]
Thanks a lot for tackling this, @jiminhsieh.

Yep, it's definitely worthwhile to try to reduce the number of warnings. As @ktoso mentioned, we won't be able to get rid of all of them but there are still a lot that could be fixed and maybe even some bugs may be lurking somewhere.

There are multiple ways to approach and divide the work. In any case, it's a good practice to keep the PRs small and separate obvious from potential contentious changes for a quick turnaround.

I'd also suggest to build with Scala 2.12 which has more and better warnings than Scala 2.11.

**Comment by jiminhsieh** [comment]
@jrudolph Thanks for your reminder and suggestion! I will start to see warning messages from 2.12.

I think I will start from `Unused import`, since it is less impact of the current code base. I also found there are 661 of warning about this. If I remove this, it could remove 1983 lines of warning messages. I guess it would be really helpful. :)

**Comment by jrudolph** [comment]
Sounds good!

**Comment by helena** [comment]
Closing this old one because it will be resolved by [#26088](https://github.com/akka/akka/issues/26088)
