### ISSUE TITLE
Akka allocates new socket for each unsuccessful connection attempt to a quarantined system

### ISSUE THREAD

**Issue by svozniuk** [akka/akka#16346]
I'm using Akka 2.3.4 running on Java 1.7.0_72 in Ubuntu 14.04 (also observed on CentOS and Mac)

I'm reproducibly falling into the situation when a remote system is quarantined and for each unsucessful attempt to connect to that remote system a new socket is allocated but never disposed. Eventually this leads to reaching the operating system limits on the number of open sockets (and files --> Too many open files in the system).

You can find a minimal project and a description how to reproduce the situation in this thread
https://groups.google.com/forum/#!topic/akka-user/IKWCjXMpV4A

**Comment by patriknw** [comment]
@ktoso Did you reproduce this? Do you have an environment where you can run the reproducer? We might have fixed this in later versions?

**Comment by ktoso** [comment]
I did not reproduce the issue (did not attempt to yet), just made sure to link to the reproducer @svozniuk had prepared, see here: https://github.com/akka/akka/issues/16346#issuecomment-63799726

**Comment by svozniuk** [comment]
@ktoso @patriknw I have just followed the instructions I provided using the reproducer project. The problem is still there. I also tried with version 2.3.9 - same behavior as before. E.g. these are the sockets opened during 5 minutes after reaching quarantined state. And it's growing

```
tcp6       0      0 127.0.0.1:2552          :::*                    LISTEN      9852/java       
tcp6       0      0 127.0.0.1:53182         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53113         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53148         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53195         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53182         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53201         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53195         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53111         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53171         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53198         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53198         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53114         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53120         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53148         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53190         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53114         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53192         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53194         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53171         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53201         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53113         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53120         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53203         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53190         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:2552          127.0.0.1:53203         ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53111         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53192         127.0.0.1:2552          ESTABLISHED 9852/java       
tcp6       0      0 127.0.0.1:53194         127.0.0.1:2552          ESTABLISHED 9852/java  
```

**Comment by svozniuk** [comment]
@ktoso @patriknw 
Just in case - I'm using Ubuntu 14.10 with Oracle JVM 1.7_72

**Comment by drewhk** [comment]
We have to look into this. Thanks for reporting!

**Comment by patriknw** [comment]
I was able to reproduce on OS X using pfctl instead of iptables. More important, it is easy to reproduce with any such tools. Here is a multi-node test: https://github.com/akka/akka/commit/e35350f4cbb2239b43b15a8df5883fdc53746d78
Note that the test will not fail but you can observe netstat while it is running, see println in the test `=====> Observe: netstat`.

**Comment by drewhk** [comment]
Depending on the nature of the bug we might be able to make a reproducing test, by subclassing NettyTransport and adding some test-hooks. I will try

**Comment by seshendra** [comment]
We have experience this problem in production with akka 2.3.6. Any suggestions or workaround until the fix is available?

**Comment by patriknw** [comment]
I hope we can release 2.3.10 next week

**Comment by patriknw** [comment]
For the record, here is the "manual" test that was used for reproducing the issue:

    /**
     * Copyright (C) 2015 Typesafe Inc. <http://www.typesafe.com>
     */
    package akka.remote

    import scala.concurrent.duration._
    import akka.actor.Actor
    import akka.actor.ActorRef
    import akka.actor.ExtendedActorSystem
    import akka.actor.Props
    import akka.actor.RootActorPath
    import akka.remote.testconductor.RoleName
    import akka.remote.testkit.MultiNodeConfig
    import akka.remote.testkit.MultiNodeSpec
    import akka.remote.testkit.STMultiNodeSpec
    import akka.testkit._
    import com.typesafe.config.ConfigFactory

    object QuarantineLeakSpec extends MultiNodeConfig {
      val first = role("first")
      val second = role("second")

      commonConfig(debugConfig(on = false).withFallback(
        ConfigFactory.parseString("""
          akka.loglevel = INFO
          akka.remote.log-remote-lifecycle-events = INFO
          akka.remote.quarantine-systems-for = 1 d
          akka.remote.gate-invalid-addresses-for = 0.5 s
          """)))

      class Subject extends Actor {
        def receive = {
          case "identify" ⇒ sender() ! (AddressUidExtension(context.system).addressUid, self)
        }
      }

    }

    class QuarantineLeakMultiJvmNode1 extends QuarantineLeakSpec
    class QuarantineLeakMultiJvmNode2 extends QuarantineLeakSpec

    abstract class QuarantineLeakSpec extends MultiNodeSpec(QuarantineLeakSpec)
      with STMultiNodeSpec
      with ImplicitSender {

      import QuarantineLeakSpec._

      override def initialParticipants = roles.size

      def identify(role: RoleName, actorName: String): (Int, ActorRef) = {
        system.actorSelection(node(role) / "user" / actorName) ! "identify"
        expectMsgType[(Int, ActorRef)]
      }

      "QuarantineLeakSpec" must {

        "demonstrate memory leak" taggedAs LongRunningTest in {

          runOn(first) {
            system.actorOf(Props[Subject], "subject")
            enterBarrier("actors-started")

            // Acquire uid from second system
            val (uidSecond, subjectSecond) = identify(second, "subject")
            enterBarrier("actor-identified")

            // Manually Quarantine the other system
            RARP(system).provider.transport.quarantine(node(second).address, Some(uidSecond))

            Thread.sleep(1000)
            enterBarrier("quarantine-in-place")
          }

          runOn(second) {
            val firstAddress = node(first).address
            val addr = system.asInstanceOf[ExtendedActorSystem].provider.getDefaultAddress
            system.actorOf(Props[Subject], "subject")
            enterBarrier("actors-started")

            enterBarrier("actor-identified")
            enterBarrier("quarantine-in-place")

            println(s"""=====> Observe: netstat -an | egrep '${addr.port.get}|${firstAddress.port.get}' | wc -l """)
            // Quarantine is up -- Cannot communicate with remote system any more
            for (_ ← 1 to 100) {
              system.actorSelection(RootActorPath(firstAddress) / "user" / "subject") ! "identify"
              expectNoMsg(2.seconds)
            }
          }

          within(4.minutes) {
            enterBarrier("done")
          }

        }

      }
    }

**Comment by letitcrash** [comment]
@patriknw , Can you please tell us the steps to run the above scala test ?

**Comment by patriknw** [comment]
I copied it to akka-remote-tests and then in sbt
project akka-remote-tests
multi-jvm:testOnly akka.remote.QuarantineLeak

It will print instructions for what ports to use for netstat, `=====> Observe: netstat...
`
