### ISSUE TITLE
Add shapeless adapter module

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16343]
To bring back shapeless based patterns that were possible with spray but aren't any more with the tuple-based approach. We'll need some use-cases from users to see what was lost in the transition so we can provide it in the new module.

/cc @sirthias

**Comment by ktoso** [comment]
Would be a nice very community contribution, any takers?

**Comment by ktoso** [comment]
This would be better as 3rd party project I think, so it can move fast to follow shapeless.
It's something we'd love to see though :)
