### ISSUE TITLE
akka-build: load time

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16350]
while adding a new dependency for #16121 

I discovered that it takes "forever" to debug every little change on reload:

```
time sbt help
....
real    2m53.904s
user    3m52.673s
sys     0m6.056s
````

I am curious is it just me? :-)

```
grep -c processor /proc/cpuinfo
8
```

**Comment by rkuhn** [comment]
We’re going to remove the samples from the “outer” build and run them separately in the future, so we will be working on this within the next few weeks. Thanks for raising this issue!
