### ISSUE TITLE
Consider moving variables in StageBase into the interpreter

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16351]
See previous discussion https://github.com/akka/akka/pull/16287#discussion-diff-20578903

/cc @drewhk

**Comment by drewhk** [comment]
I wanted to put the state of an Op where it is most convenient to access from the interpreter and does not have additional cost. It is technically possible to move these states (currently called "bits") to some external array, especially since it is just an Int now.

**Comment by drewhk** [comment]
With GraphStage this is now differently done and this no longer applies. These state variables are gone as we just simply emulate the old stages over the new interpreter.
