### ISSUE TITLE
kamon sigar-loader: new akka dependency

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16355]
many projects need sigar, yet sigar provisioning is a pain;
while working on #16121 we came up with the idea of sigar agent:
https://github.com/kamon-io/Kamon/tree/master/kamon-sigar
now we suggest that akka, rather then kamon maintains it in the ```akka-sigar-agent``` module

**Comment by hepin1989** [comment]
should be closed via https://github.com/akka/akka/pull/16475

**Comment by Andrei-Pozolotin** [comment]
@patriknw 
remaining legacy sigar dependency is still pending legacy metrics removal from akka-cluster
https://github.com/akka/akka/blob/master/project/Dependencies.scala#L37
feel free to close this

**Comment by patriknw** [comment]
thanks
