### ISSUE TITLE
Split stream akin to groupBy while allowing an element to go into multiple groups

### ISSUE THREAD

**Issue by oscar-broman** [akka/akka#16363]
As discussed here: https://groups.google.com/forum/#!topic/akka-user/mPFOv6yGiYM

It is not always possible to foresee how the stream will be divided when it is created. A way to dynamically route the elements into one or more sub-streams would be useful in many scenarios.

**Comment by rkuhn** [comment]
There is a cookbook entry describing how this can be achieved with the current tooling. Leaving this open in case we want to package it up as a single operation.

**Comment by drewhk** [comment]
we can add a variant on that cookbook recipe that instead of using a synchronous topic mapper function uses an async Future returning one

**Comment by ktoso** [comment]
Here's the existing cookbook: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/scala/stream-cookbook.html#Sorting_elements_to_multiple_groups_with_groupBy

**Comment by rkuhn** [comment]
I think the currently documented version is simple enough to be used.
