### ISSUE TITLE
Added keys that are materialized in a graph don't respect the order.

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16379]
The added keys on Sources and Flows are materialized at the Pipe level, and hence not materialized from Source to Sink for the whole graph.

**Comment by rkuhn** [comment]
Which order should it be? I thought it was just a map?

**Comment by bantonsson** [comment]
You can add a new key that depends on an existing key in your existing flow, so they should be materialized from Source to Sink, which they are but only at the Pipe level, which breaks down if you materialize pipes inside the graph, which now also will materialize all the extra keys even though the preceding part of the graph and the corresponding keys haven't been materialized yet.

**Comment by rkuhn** [comment]
Ah, this is invalid, see my reasoning [here](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/stream-design.html#The_finer_points_of_stream_materialization).

**Comment by drewhk** [comment]
Superceded by: https://github.com/akka/akka/issues/16902
