### ISSUE TITLE
Change the FlowGraph representation so that Flows are also nodes

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16377]
As @drewhk noted when working on the new IO we need to move the FlowGraph representation to something where a Flow is a node and not an edge. Right now it is very hard to represent several things (including active flows #16376) that loop back to oneself, so a number of workarounds with identity nodes and processors have been added.

**Comment by drewhk** [comment]
Superceded by: https://github.com/akka/akka/issues/16902
