### ISSUE TITLE
Active flows (Processors) should not be a special AST op

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16376]
Right now in the new IO the Processor that looks like a flow is a special AST op. It should probably be moved to a SinkSource type that extends Flow and that is a special type of Pipe and treated specially in the FLowGraph since we know that it is both a Sink and a Source.

**Comment by drewhk** [comment]
I am not sure this is relevant anymore

**Comment by drewhk** [comment]
This is no longer relevant, TCP actors are gone, and TLS is in progress removing all need for such special handling.
