### ISSUE TITLE
The flow graph should know if a node is a sink or source, and not the graph library

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16381]
The method isSink is a the graph library implementation level.

**Comment by rkuhn** [comment]
I agree with Endre: we are moving away from a generic graph library to just representing what we need.

**Comment by bantonsson** [comment]
So has this magically been fixed, or is the decision if something is a sink still done in parts of the code that doesn't know enough to give the correct answer?

**Comment by patriknw** [comment]
Could you enlighten us when it is not correct?

**Comment by bantonsson** [comment]
So if I remember correctly the code in the graph library used the assumption that if you had one incoming edge and no outgoing edges, then you are a `Sink` which was not really the case with the Processor like TCP node, which is both a `Source` and a `Sink` and that forced some of the weird special casing in the graph with identity pipes for no good reason.

It might be correct to close this ticket on the merit that there should be only one representation where we have all the information, but is that #16462

**Comment by rkuhn** [comment]
I see what he means: consider a TCP connection, which is a Sink and a Source, but those are obviously materialized together. If we model them separately in the graph then we’ll have to somehow recognize that the Source has already been materialized when materialization reaches it. If we model them as a Graph vertex and don’t start materialization here then there are graphs which simply cannot be materialized.

**Comment by patriknw** [comment]
That is great information, thanks. Opening again, so that we don't miss it, even though it might be some overlap with other things. Minimal thing that this ticket could cover is to rename the method to `isLeaf` if current impl remains.

**Comment by drewhk** [comment]
A TCP connection should not be modelled as a Source and Sink that is magically linked. It should be a vertex with two edges (ports). For materialization it *is* exactly the problem that it looks like a Sink and Source while they actually need only one materialization step. In the new model every atomically materializable entity will be stored as a vertex, and we will not rely on sinks being present in the graph as starting nodes. So this is a problem now, and we should put a workaround there, but there is no graph library, we just have a data structure that we can modify as we see fit.

**Comment by drewhk** [comment]
Just to document the full issue because I am not sure our future-selves will decode it:
 - Current graph materialization needs sinks to start from
 - A simple TCP echo setup will be surely a cycle, therefore now it is modeled as a Sink and Source
 - This violates the assumption that a leaf in the cycle can be materialized atomically

add corrections if I missed something

**Comment by drewhk** [comment]
Very likely superceded by https://github.com/akka/akka/issues/16902
