### ISSUE TITLE
Add `recover` operation

### ISSUE THREAD

**Issue by sirthias** [akka/akka#16394]
Recovering from stream failures with

    Flow[A, B]::recover[C >: B](PartialFunction[Throwable, C]): Flow[A, C]

appears to be a basic operation that is still missing.

**Comment by rkuhn** [comment]
We also need its big brother (corrected signature from @smlin above):
~~~scala
def recoverWith[C :> B](PartialFunction[Throwable, Source[C]): Flow[A, C]
~~~

**Comment by ktoso** [comment]
RecoverWith ticket: https://github.com/akka/akka/issues/18045
