### ISSUE TITLE
Replace (now hidden) TimerTransform

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16410]
As part of https://github.com/akka/akka/issues/16393 we hid `TimerTransform` (it's the "old style transformer"), we need to replace it with a "new-style" TimerTransformer ( see this PR: https://github.com/akka/akka/pull/16287 for what I mean by "new" )

**Comment by ktoso** [comment]
This should be solved by AsyncStage: https://github.com/akka/akka/issues/16410

**Comment by hepin1989** [comment]
shouldn't  this be replaced by something like TimerStage?shouldn't this be a part of the 1.0 release ?

**Comment by ktoso** [comment]
By `AsyncStage` and yes it is planned to be done.

**Comment by viktorklang** [comment]
How about adding a `defer` method on `AsyncContext`which returns a `Future[Unit]`?

**Comment by viktorklang** [comment]
misclick

**Comment by ktoso** [comment]
I was tinkering with exposing a method like `schedule(when, theAsyncInput)` to `AsyncContext`

**Comment by viktorklang** [comment]
when == delay?

perhaps 'def defer[T](delay: FiniteDuration, value: T): Future[T]'

-- 
Cheers,
√

**Comment by ktoso** [comment]
Yes, `delay`.
Why Future though? We want the input to come in to the `def onAsyncInput(event: Ext, ctx: AsyncContext[Out, Ext]): Directive` method.

**Comment by viktorklang** [comment]
Then you need to produce the Ext _before_ deferring it, but perhaps that is
what one needs all the time?

-- 
Cheers,
√

**Comment by ktoso** [comment]
I think most of the uses would need a "tick" from this method (that was my use case as well), but very good point!
