### ISSUE TITLE
add BidirectionalFlow

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16416]
This is the piece that has two inputs and two outputs, allowing the modeling of an arbitrary protocol layer on top of a Source–Sink pair (a.k.a. Flow):
~~~scala
trait BidirectionalFlow[In1, Out1, In2, Out2] {
  def join[T, U](other: BidirectionalFlow[Out1, T, U, In2]): BidirectionalFlow[In1, T, U, Out2]
  def join(flow: Flow[Out1, In2]): Flow[In1, Out2]
  // plus matching method on FlowOps for the left side
}
~~~
The “flows” 1 and 2 are going in opposite directions, 1 being on the top (left to right) and 2 being on the bottom (right to left).

**Comment by reid-spencer** [comment]
:+1: This would be helpful for me.

**Comment by drewhk** [comment]
This can be done immediately after https://github.com/akka/akka/issues/16902

**Comment by drewhk** [comment]
This can be closed now right?
