### ISSUE TITLE
add graphical combinators for flows and stages

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16441]
This is a proposal for discussion: we had part of this discussion briefly a few weeks ago and concluded that `~>` mutates a FlowGraphBuilder and therefore it should not be used for concatenating Flow topologies (i.e. `f1 append f2`), but I’m not that sure anymore.

The trigger for this discussion is that we will soon have BidirectionalFlow (#16416) and then we’ll need some nice DSL for writing up protocol stacks like
~~~scala
handler <~> serialization <~> framing <~> encryption <~> StreamTcp.connect(...)
~~~
Using `join` as the operator here sounds too unspecific, not graphic enough. We must in addition to nicer Scala syntax also find a better name, since that is all that Java is going to get.

Now to make that consistent, we might also want to have
~~~scala
val f4 = f1 ~> f2 ~> f3
~~~ 
There should not be confusion here because that expression cannot do different things within or without a FlowGraph block, since we can keep the argument types separate. Everything that does not involve Junctions returns a new Flow and does not perform side-effects, while everything that does involve Junctions does not work without the proper implicits, including the FlowGraphBuilder that is mutated—because interacting with Junctions in a pure fashion is not meaningful anyway.

For me it currently looks like
~~~scala
Flow { implicit b =>
  input ~> flow1 ~> flow3 ~> output
}
~~~
is not confusing even though the first and third `~>` mutate the graph while the second one does not. It should be pretty clear that
~~~scala
Flow { implicit b =>
  flow1 ~> flow2
}
~~~
does not really do anything. But I might also be completely wrong, so please let me know what you think!

**Comment by rkuhn** [comment]
@smlin Sorry for the long pause, we have just discussed this gain and this is what we came up with:

* there are atomic elements like open inputs/outputs and junctions which need to have an identity, i.e. you need to explicitly copy them when you want two
* there are blueprints—partial graphs—that are always copied when imported in a larger graph
* the blueprints always come with open inputs/outputs that are also copied during import

So, to use a compound element within a graph needs an explicit “import” step that performs the copy, otherwise everything is an atomic element with proper identity.

**Comment by smlin** [comment]
@rkuhn Thank you for response. 
For clarifying only! 
 I think graph is just a collection of nodes. And it is possible to combine any two or more graphs if we have defined the rules for this. 
First: all nodes need identities except keyed nodes.
Second: nodes with equals identities would be folded to a single node. 
Third: there are three kind of nodes: 
 1) nodes in blueprints - identities for them unique in bounds of a current graph. After import to a larger graph identities for them will be regenerated to be unique inside new graph. So "that are always copied when imported in a larger graph" is true.
 2) atomic nodes with explicitly defined identities (by user). Such nodes is reusable, but identities for them is not changed after import to a larger graph.
 3) not reusable, keyed nodes. Such nodes could not be materialized twice and identity checking for them eventually is not applicable.
 
So I think that if you need two atomic elements then you must explicitly set different identity to them.
```
val b0 = Broadcast()
val b1 = Broadcast("b1")
val b2 = Broadcast("b2")
val other2 = Broadcast("b2")
```
b2 and other2 will be materialized into single node with identity "b2".

P. S. That all only is my opinion and I only trying to help.

**Comment by rkuhn** [comment]
The simpler the rules, the better: if users have to keep in mind that certain kinds of nodes behave differently to others then this opens up a large potential for confusion (and subsequent frustration). The simplest ruleset is:

* everything uses object identity—no two JVM objects are considered equal when representing parts of a stream topology graph
* (partial) graphs can be copied into other graphs—this is the blueprint nature of Akka Streams

Whether something is keyed or atomic does not matter in this proposal, and that makes life easier for all users.

@drewhk WDYT?

**Comment by viktorklang** [comment]
@rkuhn Resonates very well with me, Roland!

**Comment by smlin** [comment]
@rkuhn Sounds really simple! I think you know what are you doing:)

I think object identity (hashCode?) will be hard to import to the string representation (if user can define name of the node, then two different nodes could have equal names).
Also if you will need the serialization of a graphs then object identity will be not applicable (two graphs with a one shared node will have different nodes after deserialization).

**Comment by drewhk** [comment]
@rkuhn +1

> if user can define name of the node, then two different nodes could have equal names

Different nodes are different objects, no problem there.

> Also if you will need the serialization of a graphs then object identity will be not applicable

If you include a graph into another, it will be copied, otherwise it would violate the identity principle.

**Comment by smlin** [comment]
@drewhk 
If you compose two graphs, then this is implicitly means that these graphs are intersected. Otherwise such operation is meaningless - it is like addition of the real number to the irrational one. 
So you need to have global unique identity for each node, like UUID. Of course it is possible to override hashCode :).

**Comment by drewhk** [comment]
> If you compose two graphs, then this is implicitly means that these graphs are intersected. 

No, it means that you are creating a *distinct union* of the two graphs. Connecting them is another operation.

> So you need to have global unique identity for each node, like UUID.

Object identity (reference identity) is enough.

**Comment by smlin** [comment]
@drewhk Ok. As you wish.

**Comment by rkuhn** [comment]
So, in conclusion: this is considered to be covered by the current Graph DSLs.
