### ISSUE TITLE
fix equality of Source/Flow/Sink/Graph

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16440]
Since all elements are by default reusable pieces it makes sense to define their default equality to mean “describing the same flow topology”. This means that (Partial)FlowGraph needs to compare the set of vertices it contains and the structure of the edges—but not the insertion order (i.e. some IDs). This means that Sources, Sinks, Keys, Pipes, and AstNodes need to abide by the same rules as well. Of course different instances of the same closure will not compare equal even if the function that is represented is the very same one, but that is not something that we can fix anyway.

We will need this in order to write tests for flow optimizers later.

**Comment by drewhk** [comment]
It is not easy to solve, and it is not clear what this feature would be used for.
