### ISSUE TITLE
Harmonize naming of java/scala apis

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16458]
There is a naming miss match between akka-stream and akka-http when it comes to where the java/scala apis live.

In akka-stream we have `akka.stream.scalads.*` and `akka.stream.javadsl.*` while we in akka-http have `akka.http.server.*` and `akka.http.server.japi.*`.

We should try to harmonize the naming.

/cc @sirthias @jrudolph

**Comment by rkuhn** [comment]
@sirthias This is the ticket about the package names; we have discussed the HTTP model and why that works differently, but when it comes to the routing DSL we should follow the lead of Streams and move to `scaladsl` and `javadsl` package names. This needs to be done before 1.0-RC1.

**Comment by ktoso** [comment]
Sanity check so we don't forget by accident: what about `akka.stream.javadsl.japi` - keep as is? (It's the Function's with added variance, we should move them to akka proper at some point - breaking source compat).

**Comment by rkuhn** [comment]
@ktoso That package is not relevant here, but a good point; we should move it ASAP but without breaking source or binary compatibility—by adding the variant forms with different names.

**Comment by rkuhn** [comment]
see also #17279
