### ISSUE TITLE
add `Source.repeated(...)`

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16454]
~~~scala
def repeated[T](elems: T*): Source[T] = {
  // emit the sequence, then start over, ad nauseam
}
~~~

**Comment by agolubev** [comment]
It's an old ticket @rkuhn  are we sill good with just using `Source(Iterator.continually(mySource)).flatten(Concat)` and buffer = 1  (instead of creating graph stage)?

Perhaps can be labeled `easy to contribute`

**Comment by rkuhn** [comment]
Actually it would be `Source.repeat(mySource).flatMapConcat(identity)`, but I think that’s tolerable, so this ticket might as well be closed.

**Comment by patriknw** [comment]
closing then, thanks
