### ISSUE TITLE
Flatten graph to primitive operations when materializing

### ISSUE THREAD

**Issue by 2m** [akka/akka#16463]
This should allow whole-graph optimizations. Related to #16462.

When flattening, a structure of the nested graph can be retained by adding corresponding attributes to the primitive operations. This additional information can for example be used when debugging or visualizing graph topology.

**Comment by drewhk** [comment]
This is superceded by https://github.com/akka/akka/issues/16902

**Comment by drewhk** [comment]
and also didn't meant to close this one yet
