### ISSUE TITLE
Apply `max-content-length` setting also to chunked encoding

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16472]
If we keep this setting for the purpose of guarding against `toStrict` blowing up the heap, then we must seal all ways into that particular hell. If we don’t, then we must apply this setting _only_ when calling `toStrict`.

**Comment by sirthias** [comment]
Yes, this is something that we meant to do in spray as well eventually.
Applying the configured limit also to chunked messages (on the server-side as well as the client-side) is the way to go.

**Comment by jrudolph** [comment]
PR in #18049

**Comment by rkuhn** [comment]
Is this client/server symmetric or should it be?

**Comment by jrudolph** [comment]
It is symmetric and you can configure it separately using `akka.http.{server,client}.parsing.max-content-length`.

**Comment by jrudolph** [comment]
Fixed in #18049.
