### ISSUE TITLE
Make pushAndFinish available in the termination handlers

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16480]
Currently this is not possible, although this is a common scenario. The solution is fortunately simple:

 - make the type of pushAndFinish to be TerminationDirective
 - override the pushAndFinish method in the Completing, Failing states
 - when called, these methods should replace the current op with simply a SingleElementOp containing the last element to be pushed while keeping the isTerminating, and pushAllowed flags
 - call the super method that will call onPull on the new op whenever allowed

**Comment by lolski** [comment]
is this issue still on the list? if so i'd like to give it a shot

**Comment by drewhk** [comment]
Good point. No, this ticket is no longer relevant since `GraphStage` provides the necessary flexibility.

**Comment by drewhk** [comment]
you can find stream issues for community contrib with these filters: https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Acommunity-contrib+label%3At%3Astream

Happy *hakking*!

**Comment by lolski** [comment]
got it. thanks!

**Comment by hepin1989** [comment]
@lolski go with akka-stream 2.0,then we can quick have it merge to master:)
