### ISSUE TITLE
TickSource is not freely shareable

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#16492]
We need to change it from `() => T` to `T` since the function may side effect (and its test rely on the side-effectedness)

**Comment by rkuhn** [comment]
So, what we want is `() => () => T`?

**Comment by viktorklang** [comment]
() => Future[() => Future[() => Future[() => … ;-)

**Comment by rkuhn** [comment]
I prefer this to be solved in conjuction with #16685 (by moving the stateful part into a transformation that is appended to a completely pure value-based tick source.

**Comment by viktorklang** [comment]
@rkuhn Agreed
