### ISSUE TITLE
Decide and document how to test actors that interact with HTTP or TCP

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16493]
Code using `StreamTcp().connect(...)` and friends can currently not be mocked, it will always perform TCP connections. This may or may not be a problem depending on how we want to tell users that they shall test their actors:

  * No mocking means that you’ll test exactly what is used in production, but it requires all such tests to be end-to-end.
  * Being able to reroute the API towards TestProbes or similar means that the test can be kept shorter, with less boiler-plate code and without the need to create a communication partner just for the test procedure.

**Comment by ktoso** [comment]
This relates to https://github.com/akka/akka/issues/18469

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
