### ISSUE TITLE
BUG: Remoting sends AddressTerminated a bit too eagerly

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16505]
The remoting code that gates an address when there is a connection failure also eagerly sends an AddressTerminated event which it shouldn't. This can lead to remote death watch firing even though the node has only been Gated and not Quarantined, and the node subsequently coming back.

**Comment by drewhk** [comment]
Hey, this was not forward ported to master

**Comment by drewhk** [comment]
forward ported
