### ISSUE TITLE
Add better test coverage of PersistentActor stashing

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16528]
Try various scenarios, involving restarts, user stashing/unstashing etc

**Comment by johanandren** [comment]
What is already covered is:
* stashing a single message
* stashing multiple messages
* stashed messages survives failure/restart

**Comment by ktoso** [comment]
Here's an edgy scenario I'm not completely sure that it's handled correctly:

```
M1 comes in
persistAsync(E1) it
M2 comes in
stash (M2)
persistAsync callback (E1)
message M3 comes in
persist(E2) it
unstashAll()  // <<<<< unstashes M2
???  // <<< I think the message should not be handled before the persist callback is triggered
```

Could you try testing this @johanandren? It's a bit crazy, but we should make sure that persist's guarantee

**Comment by johanandren** [comment]
Edgy scenario covered (and worked as it should)!
