### ISSUE TITLE
Consider removing some fault handling options in PersistentActor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16524]
Right now: PersistenceFailure is emitted to user receive handler, if it is unhandled it throws ActorKilledException, which by default supervision strategy stops the actor but can be intercepted differently by user

I'm not sure what the best solution is, but right now it feels like there are too many alternatives. The default of stopping the actor is good though.

**Comment by ktoso** [comment]
If we invent an replacement I feel it should be able to "continue replaying in presence of corrupted events". In the current schema this is doable by handling `PersistenceFailure` and for example logging `"whoops, 2323 seems to be in a bad state?"`, the actor then continues replay.

**Comment by patriknw** [comment]
Regarding "continue replaying in presence of corrupted events": that is also some kind of migration issue, and I think it can be solved by the `EventSeq` as proposed in #17616, i.e. the exception is handled in the serializer instead of in PersistentActor.
