### ISSUE TITLE
Introduce a min-nr-of-members concept for Cluster Singleton

### ISSUE THREAD

**Issue by ckaratza** [akka/akka#16535]
At the moment Cluster Singleton functionality doesn't deal with network partitions (split brain issues). A concept of min-nr-of-members for a Cluster Singleton to be started should be introduced so in case the original cluster is split in to 2 or more individual clusters the condition min-nr-of-members should be checked to decide if Cluster Singleton will be running.
Example case:
Cluster with 5 nodes each one with a Cluster Singleton. 3 switches interconnect them
1 top switch connects 2 switches which connect 2 and 3 nodes respectavely.
Cluster singleton runs under switch with 2 nodes.
Top switch breaks and 2 clusters are formed with cardinality of nodes 2 and 3.
If min-nr-of-members is set to 3 then already running Cluster Singleton stops it starts on cluster with membership size of 3.

**Comment by nilsga** [comment]
+1. Would be a really nice feature.
