### ISSUE TITLE
Unnecessary memory allocation AskSupport.scala

### ISSUE THREAD

**Issue by Arneball** [akka/akka#16538]
Running akka on Android i can see that there are a couple of unnecessary allocations. So far i've seen at least two spots that could be easily fixed. Namely PromiseActorRef$#apply and  PromiseActorRef#stop.

I can submit a PR.

**Comment by hepin1989** [comment]
@patriknw This one could be closed now.

**Comment by raboof** [comment]
Thanks for finding this issue/PR relationship!
