### ISSUE TITLE
Document how to use Protobuf (or something else) as a MediaType

### ISSUE THREAD

**Issue by aiyanbo** [akka/akka#16548]
We used Protobuf encoding objects on my project. I marked data format as a MediaType, like this: 
```
Content-Type: application/x-protobuf
```

**Comment by rkuhn** [comment]
This is already possible within the marshaling infrastructure, so this ticket should be regarded as a request to document how that works.

**Comment by kostya-sh** [comment]
Documentation with examples will certainly be very useful.

As a relative beginner with scala and akka I find it very hard to figure out how to set response content type in the following example:

```
complete {
   """{"a": 1}"""
} 
```
How to tell akka-http to set content type to application/json here?

**Comment by sirthias** [comment]
@kostya-sh The server-side routing DSL provided by akka-http is very similarly to the one from spray.
You might want to check out this chapter from the spray docs for some info on how marshalling works:
http://spray.io/documentation/1.2.2/spray-httpx/marshalling/

**Comment by kostya-sh** [comment]
@sirthias Thank you for the link to the docs.

I figured out that I can do something like
```
complete {
    // do not import other implicit marshallers!
    implicit val marshaller = PredefinedToEntityMarshallers.stringMarshaller(MediaTypes.`application/json`)
    """{"a": 1}"""
}
```
to implement my requirement.

To be honest this solution looks a bit ugly to me and I guess there might be a better way to do it. This brings us back to the point of docs (with examples!).

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
