### ISSUE TITLE
Improve the Query Side

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16541]
[Akka Persistence on the Query Side: The Conclusion](https://groups.google.com/forum/#!topic/akka-user/MNDc9cVG1To)

also discussed in [Improving Akka Persistence wrt CQRS/ES/DDD](https://groups.google.com/forum/#!msg/akka-user/SL5vEVW7aTo/KfqAXAmzol0J) and [Event Stores for Akka Persistence for CQRS?](https://groups.google.com/forum/#!msg/akka-user/4kbYcwWS2OI/hpmAkxnB9D4J)

**Comment by ktoso** [comment]
Should be possible to ship a version of it with M3 (experimental).
