### ISSUE TITLE
Add testkit for HTTP client side

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16546]
We currently have a nice testkit for routing and marshaling, but the capabilities of testing an HTTP client are not yet ideal. We can of course just create a test server that the client connects to, serving the interesting part of an API for a certain test case (and including mocked test data), but what about cutting out the TCP middle-man? This might already be possible (in which case it is just a matter of documentation).

Concretely: Actor which uses HTTP client is configured with a transport flow factory `() => Flow[ByteString, ByteString]` and wraps that using `Http.transportToConnectionClientFlow`. In a test case the configured factory uses `Http.serverFlowToTransport` to bypass TCP. This will only get easier when BidirectionalFlow is implemented.

/cc @sirthias @jrudolph @2m @huntc

**Comment by jrudolph** [comment]
But why would you want to include any akka-http stuff at all when testing a client? If you want to mock something you could always do this with an arbitrary `Flow[HttpRequest, HttpResponse]`?

**Comment by ktoso** [comment]
One can just make a mock `Flow[HttpRequest, HttpResponse]`
