### ISSUE TITLE
Never completed, no element Source

### ISSUE THREAD

**Issue by adamw** [akka/akka#16547]
As per this forum topic: https://groups.google.com/forum/#!topic/akka-user/E46rSCLpZYI, sometimes a source which never produces an elements (but also doesn't complete) is useful e.g. when using TCP streams, where only one side transmits, and the reverse stream is only used to detect broken connections.

**Comment by rkuhn** [comment]
It should materialize to a `Future[Unit]` that is fulfilled upon cancellation.

**Comment by rkuhn** [comment]
Or it should materialize to a `Promise[Unit]` that allows external termination as well.

Or this should be fused with FutureSource to provide all this functionality.
