### ISSUE TITLE
TcpStream doesn't complete incoming stream

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16553]
This is related to #16552: if `ConfirmedClosed` is never generated the input stream of the Tcp connection will never be completed.

However, even with a fix for #16552 it still doesn't work because the TcpStreamActor shuts itself down before the completion is signaled to both, the input and the output stream, i.e. it doesn't properly coordinate the closing of incoming and outgoing streams.

**Comment by Alien2150** [comment]
Hi, i am not sure if that is related too. But when I use the SSLCipherActor I don't get any completion signals but what I do see is an log-entry: 

[INFO] [01/07/2015 14:12:53.549] [app-akka.actor.default-dispatcher-15] [akka://
app/system/IO-TCP/selectors/$a/1] Message [akka.io.Tcp$Abort$] from Actor[akka:/
/app/system/IO-TCP-STREAM/server-1-%2F0.0.0.0%3A16500/$a#-536894325] to Actor[akka://app/system/IO-TCP/selectors/$a/1#-1566861189] was not delivered. [1] dead l
etters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

This is the code i am using: https://www.google.com/url?q=https%3A%2F%2Fgist.github.com%2FAlien2150%2F9468c871135fd94869a2&sa=D&sntz=1&usg=AFQjCNEanvTVgDgxtLdTfdy88exEUkbfJQ

Regards,
Thomas

**Comment by drewhk** [comment]
Ok, I am testing with a special probe for now that will ping the selector with a ResumeReading before fishing for a connection event. That will help to fix the stream issues, and later by removing the "ping" code we can test the underlying Akka IO fix.

**Comment by drewhk** [comment]
I will need the fix for https://github.com/akka/akka/issues/16723
