### ISSUE TITLE
TcpConnection: ConfirmedClose doesn't work with `pullMode = true`

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16552]
That's because, no read interest is registered and therefore the closing of the connection is missed.

/cc @sirthias

**Comment by drewhk** [comment]
While fixing a related ticket https://github.com/akka/akka/issues/16553 I added a special method in tests that will ping the test connection actor with a ResumeReading before expecting a close message. This comment here is just a remainder that once this ticket is fixed the above mentioned workaround in akka.stream.io.TcpHelper should be removed.

**Comment by drewhk** [comment]
Superceded by ticket: https://github.com/akka/akka/issues/17122
