### ISSUE TITLE
FlowGraphBuilder doesn't correctly set flags when importing graphs

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16571]
As noted in PR #16567 the FlowGraphBuilder needs to allow cycles et.c. when importing a graph that allows cycles.

**Comment by drewhk** [comment]
The proper solution is to maintain the cycles and disallow *new* cycles unless enabled.

**Comment by drewhk** [comment]
Related are: https://github.com/akka/akka/issues/16377 https://github.com/akka/akka/issues/16214

**Comment by drewhk** [comment]
This will be handled in a different way. We change the internal representation in https://github.com/akka/akka/issues/16902 and soon hiearchic graph analytics will be added (cycle detection in varios nesting levels)
