### ISSUE TITLE
Drop /user prefix in group router configuration?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#16588]
If one wants to configure an actor externally, i.e. via `akka.actor.deployment`, the path to identify an actor starts with a "top level actor", i.e. one created via `ActorSystem.actorOf`; in particular on has to omit the "/user" prefix which would be needed for a local actor path. The reason is that only user actors are amenable to external configuration.

Now, if one wants to define the routees of a group router, one needs to provide the full local actor paths, including the "/user" prefix. This inconsistency has caused a lot of confusion in various training classes. Therefore it might make sense to drop the the "/user" prefix for the `paths` configuration setting of a group router.

Of course this means that one can't ever send messages to the rest of the actor tree, i.e. to system, remote or any other actors. AFAIK this isn't possible anyway, right?

**Comment by patriknw** [comment]
The intention is that it should be allowed to use actorSelection for system actors also. I'm pretty sure we use it internally, e.g. cluster actors are system actors and they use actor selection.

My opinion is that the deployment section should use the full path (including /user), but I'm not sure we can change it.

**Comment by hseeberger** [comment]
All right, so it seems to be OK to select system actors. What does that mean for the `path` configuration setting of a group router? If group routers should never have non-user (e.g. system) routees, then we could drop the "/user" prefix; else not.

**Comment by patriknw** [comment]
I think it would be easiest to understand if there were no special cases, i.e. always full path (including /user).

We might (internally) want to use a group router together with a system actor, so I don't see why that should be forbidden.

**Comment by rkuhn** [comment]
Unfortunately I cannot think of a completely consistent solution that covers all bases, since in the deployment section `/user` does not make sense at all while programmatically it will always be needed. Another impediment is that we cannot change in either direction without breaking people’s configurations. Thus the conclusion is that we are stuck with the current way of doing things.
