### ISSUE TITLE
Cluster heartbeats should have a dispatcher that has an incredibly high thread priority

### ISSUE THREAD

**Issue by derekwyatt** [akka/akka#16581]
I've been thinking about my recent issues with clustering heartbeats and I'm curious about the sharing of the CPU.  Clearly if we hog the CPU in unfriendly function calls (e.g. function calls that last for minutes without sharing the CPU) then clustering is going to die.  However, if we have 4 cores and 64 FJ threads (which is the maximum on the default) then aren't we still going to starve the clustering dispatcher?

Is it possible to set the thread priority on the clustering dispatcher's pool to ultra-high?  I'd like to see _every_ effort placed into the clustering heartbeat strategy to ensure that it can't get starved for any resource, ever.  (within reason... the above CPU hogging scenario can't be dealt with).

**Comment by rkuhn** [comment]
Setting thread priorities is not really supported on the JVM, and even O/S kernels usually do not do what you’d want them to (apart from realtime priorities where available). I’d recommend keeping the thread count of a CPU-bound dispatcher strictly below the number of available cores—that is the only thing that works reliably.

**Comment by derekwyatt** [comment]
Hold on, so you're not even willing to try?  So it might not help, but it can't hurt, right?

If I have a four core box, you're asking me to eliminate 25% of the CPUs so I can send and receive heartbeats every few seconds.  That's a really expensive solution to the problem.

**Comment by rkuhn** [comment]
If you have a thread that is not doing anything most of the time and just wakes up for a millisecond occasionally, then all decent O/S will make an effort to run that thread ASAP unless you completely swamp the box. So, if you run 4 CPU bound threads on that box I would be surprised if scheduling of the cluster thread is a problem. OTOH adding a feature to Akka that does nothing (while documenting the opposite) does not feel right to me.

The other issue is that not only the clustering, also the remoting must wake up in a timely fashion, memory bandwidth and network must be available, etc. Setting thread priorities strongly smells like homeopathy. If you want bulk-headed resources then that means giving exclusive resources to compartments (like “this CPU core is responsible for keeping the cluster alive”). Unix RT priority is a way to give certain tasks exclusive CPU access, but that is not available to the JVM at all.

**Comment by derekwyatt** [comment]
It just sounds like, you're not 100% sure it's going to have a decent effect on things, so you're not even willing to try.  Thread priorities do exist, and while I'm not a fan of them in general, in this case it would seem that even a marginal improvement, would validate the idea of giving it a go.

**Comment by hepin1989** [comment]
@derekwyatt Set the priority is not supported on some jvm,even it's supported ,the OS could ignore it too.
Back to the issue.You could set the time to a little logger ,we solve this problem via this,cause when the load going high,even you set a dedicated dispatcher for the ```remoting``` and ```heartbeats```,they may not have the chance to run too.

We have a cluster with 24 physical nodes,so trust me ,you need tune the configuration.:P
may this help.

please see this section :```Failure Detector``` for detail.

**Comment by derekwyatt** [comment]
I get it.  I was just hoping for an attempt.  We're on 16 core machines now, and I've reserved a core for clustering and remoting, but I'm trying to get the system down to 4 core machines.  The machines are stateful, so when we lose a node we lose the number of customers that were allocated to that node until they get brought back to life and rebalanced on some other set of nodes.

But, with a 4 core node, I have less CPUs to play with and keeping (essentially) one idle just to handle pings is _painful_.  I've got the pause timeout set really high right now, but it would be better if I could tighten it down, and between the transport sharing between normal and system akka traffic, the susceptibility of the heartbeats to CPU hogging, and so forth, I'm pretty wary of moving the value.

But I guess the bottom line is that it's not going to happen.  Maybe if the heartbeats go to UDP (which will give us an entirely different transport, with less overhead) I might get a bit more breathing room.

**Comment by hepin1989** [comment]
@derekwyatt I just comes up an idea about that could we let the akka's system adjust the arguments for the ``` Failure Detector``` dynamically ,and then gossip these argument in the cluster .then the cluster would not going down/separate with temporary high load.
@drewhk

**Comment by rkuhn** [comment]
A more fair summary (instead of “you don’t even try”) would be that we have a lot more things to do than we have time for, so picking this issue will kick out something else. In order to have me do that you’d need to convince me that it is worthwhile, otherwise the onus is on you to try it out and come back with hard data. In this case the change itself is rather trivial but the assessment of whether it has an effect is hard and time-consuming—and you are in a better position than me to run such tests as you have a concrete case to work on.

So, please don’t think that I’m not valuing your input or that I am ignoring you.

**Comment by derekwyatt** [comment]
Well, in my defense, the ticket was _closed_.  I'll try and schedule some time to try it out myself, but Akka doesn't make it easy to do, since the thread factory isn't configurable.

**Comment by patriknw** [comment]
If you spend time on trying it you should know that it's not only the cluster heartbeat sender and receiver actors that must be given higher priority to make this a work. It's also the remoting actors, the scheduler thread, and netty. That is only inside the jvm. More things are probably competing on the OS and virtualization level.

Also, note that GC need some cpu time as well.

On thought for the 4 cpu case; would it be possible to make the cpu bound tasks not run at 100%, i.e. inject some idle (non-cpu) tasks once in a while to help the OS to schedule time for other threads.

**Comment by hepin1989** [comment]
@patriknw for the GC,it's true,I just forgot to mention that.we have node with 32 GB RAM，and we are using ```-mem 29GB``` to start our jar. we are using``` G1```,and when it ```Full GC```,pause the world 20~30 seconds.then you know, without consider this,the cluster is down

**Comment by derekwyatt** [comment]
Yup, I've already accounted for all of this stuff. I'm not looking for a silver bullet here... all I'm hoping for is that it might _help_, not solve the world.  If thread priority is supported on a certain JVM / OS combination, then it certainly can't hurt.

Ultimately, I'm still hoping for a stream-based implementation, using UDP, separate dispatchers (which we already have) and (hopefully) a simpler config where the cluster tuning and remoting tuning affect each other (i.e. setting one doesn't mean I have to screw with another, or one can't clobber another, etc...), and as a final hope, that thread priority can somehow give these critical subsystems a boost. Failing thread priority, then something inside Akka itself that will ensure these things get some priority (outside of horrid things like GC's for example).

Ultimately, ripping the cluster apart makes it very hard to find errors in your app, because your app stops doing the thing that was killing the cluster.

Hell, even some configuration samples would be good... e.g. _"For testing systems that are bahaving poorly w.r.t. clustering, set this config will make it bullet proof, letting the system live long enough for you to profile it and see what's going on"_
