### ISSUE TITLE
FAILED: LeveldbPersistentViewSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16592]
The error is https://jenkins.akka.io:8498/job/akka-multi-node/952/consoleFull:

    [info] - must take snapshots *** FAILED ***
    [info]   java.lang.AssertionError: assertion failed: expected replicated-b-2, found replicated-c-3
    [info]   at scala.Predef$.assert(Predef.scala:179)
    [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:354)
    [info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
    [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
    [info]   at akka.persistence.PersistentViewSpec$$anonfun$2$$anonfun$apply$mcV$sp$15.apply$mcV$sp(PersistentViewSpec.scala:321)
    [info]   at akka.persistence.PersistentViewSpec$$anonfun$2$$anonfun$apply$mcV$sp$15.apply(PersistentViewSpec.scala:313)
    [info]   at akka.persistence.PersistentViewSpec$$anonfun$2$$anonfun$apply$mcV$sp$15.apply(PersistentViewSpec.scala:313)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    [info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)

**Comment by bantonsson** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/988/consoleFull

Not the same failure, but still the same test case:
```
[info] - must take snapshots *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for snapped
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
[info]   at akka.persistence.PersistentViewSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply$mcV$sp(PersistentViewSpec.scala:322)
[info]   at akka.persistence.PersistentViewSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(PersistentViewSpec.scala:317)
[info]   at akka.persistence.PersistentViewSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(PersistentViewSpec.scala:317)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   ...
```

**Comment by patriknw** [comment]
Here is another one of the timeout (10 seconds): https://jenkins.akka.io:8498/job/akka-multi-node/1000/consoleFull

**Comment by 2m** [comment]
Another one of the timeout: https://jenkins.akka.io:8498/job/akka-multi-node/1023/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2402/consoleFull

**Comment by patriknw** [comment]
I looked at this. The "only" way it can fail like this is if the writing to the snapshot file takes more than 10 seconds. That sounds rather unlikely. I don't know what it can be.

**Comment by hepin1989** [comment]
I have noticed this,sometime the persistent drop to 200~ ops.
It's the last year when I was using akka persistent and doing some stress.
sometime it was about ~20k,but sometime it was only 200~. So I think that maybe a bug of the leveldb it's self not akka.

**Comment by patriknw** [comment]
thanks, this test failure doesn't have anything with leveldb to do, it is the file based snapshot store

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
