### ISSUE TITLE
release test-jars

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16605]
I asked this before #15320 and I found 
that we are still forced to copy/paste great many test components
from akka-remote, akka-cluster/multi-jvm, etc. 

We ask again: please release all test-jars to maven central.

**Comment by patriknw** [comment]
@Andrei-Pozolotin please describe what test components that you are missing. We will not publish test jars to maven central (because we want to have full freedom to change them), but we can consider moving specific things to corresponding testkit.

**Comment by Andrei-Pozolotin** [comment]
recent example of copy/paste
[cluster](https://github.com/carrot-garden/akka-persistence-chronicle/tree/master/src/multi-jvm/scala/akka/cluster)
[remote](https://github.com/carrot-garden/akka-persistence-chronicle/tree/master/src/multi-jvm/scala/akka/remote/testkit)
[testkit](https://github.com/carrot-garden/akka-persistence-chronicle/tree/master/src/test/scala/akka/testkit)
but there is more. I will try to go back and find it

**Comment by patriknw** [comment]
thanks, some comments:
- we can't have dependencies to scalatest
- the MultiNodeClusterSpec contains a lot of cruft that normal users should not use for testing, they have evolved for testing akka cluster itself
- using FailureDetectorPuppet feels like testing on the wrong level
- is coroner really useful? we added it because we had stability problems in our large test suite when running in some environments

**Comment by Andrei-Pozolotin** [comment]
> thanks, some comments:
>
>   * we can't have dependencies to scalatest
>
I do not follow, even for test-kit?
>
>   * the MultiNodeClusterSpec contains a lot of cruft that normal users
>     should not use for testing, they have evolved for testing akka
>     cluster itself
>
we do not like to be called "normal" :-) . we find MultiNodeClusterSpec
useful time after time.
>
>   * using FailureDetectorPuppet feels like testing on the wrong level
>
ok, agreed
>
>   * is coroner really useful? we added it because we had stability
>     problems in our large test suite when running in some environments
>
we like to see our thread counts during tests

**Comment by patriknw** [comment]
>>we can't have dependencies to scalatest
> I do not follow, even for test-kit?

no, akka testkit(s) are test framework agnostic, otherwise we would have to support a few more frameworks also (and managing dependencies)

**Comment by patriknw** [comment]
> we find MultiNodeClusterSpec useful time after time.
it might have same utilities that are useful, but then those must be extracted, packaged and documented properly

**Comment by Andrei-Pozolotin** [comment]
I see. I guess I am barking on the wrong tree. will continue to copy/paste. feel free to close.

**Comment by patriknw** [comment]
My point is that it is not as easy as just releasing what we have in our internal test classes.
There might be pieces that can be extracted, please open more specific issue/pull request for such things. E.g. the coroner.
