### ISSUE TITLE
actorcell size is exactly 64 bytes? 

### ISSUE THREAD

**Issue by MQ-EL** [akka/akka#16603]
Hi!
 
  I measured ActorCell Object footprin is 88 bytes in windows7 & jdk8, using JOL tools. 
BUT ://ACTORCELL IS 64bytes and should stay that way unless very good reason not to (machine sympathy, cache line fit) in ActorCell source comment.
  
  What's wrong with my test? The akka-actor version is 2.11-2.3.8

The test code follows:==>

               object Main extends App {
                     println(VMSupport.vmDetails)
                     val cell = getClass.getClassLoader.loadClass("akka.actor.ActorCell")
                     println(ClassLayout.parseClass(cell).toPrintable)
               }

Console print out :==>

Running 64-bit HotSpot VM.
Using compressed references with 3-bit shift.
Objects are 8 bytes aligned.
Field sizes by type: 4, 1, 1, 2, 2, 4, 4, 8, 8 [bytes]
Array element sizes: 4, 1, 1, 2, 2, 4, 4, 8, 8 [bytes]

akka.actor.ActorCell object internals:
 OFFSET  SIZE              TYPE DESCRIPTION                                                            VALUE
      0    12                   (object header)                                                        N/A
     12     4   ActorSystemImpl ActorCell.system                                                       N/A
     16     8              long ActorCell.akka$actor$dungeon$Children$$_nextNameDoNotCallMeDirectly    N/A
     24     4  InternalActorRef ActorCell.self                                                         N/A
     28     4             Props ActorCell.props                                                        N/A
     32     4 MessageDispatcher ActorCell.dispatcher                                                   N/A
     36     4  InternalActorRef ActorCell.parent                                                       N/A
     40     4             Actor ActorCell._actor                                                       N/A
     44     4          Envelope ActorCell.currentMessage                                               N/A
     48     4              List ActorCell.behaviorStack                                                N/A
     52     4     SystemMessage ActorCell.sysmsgStash                                                  N/A
     56     4          ActorRef ActorCell.akka$actor$dungeon$FaultHandling$$_failed                    N/A
     60     4               Set ActorCell.akka$actor$dungeon$DeathWatch$$watching                      N/A
     64     4               Set ActorCell.akka$actor$dungeon$DeathWatch$$watchedBy                     N/A
     68     4               Set ActorCell.akka$actor$dungeon$DeathWatch$$terminatedQueued              N/A
     72     4           Mailbox ActorCell.akka$actor$dungeon$Dispatch$$_mailboxDoNotCallMeDirectly     N/A
     76     4 ChildrenContainer ActorCell.akka$actor$dungeon$Children$$_childrenRefsDoNotCallMeDirectly N/A
     80     4            Tuple2 ActorCell.akka$actor$dungeon$ReceiveTimeout$$receiveTimeoutData        N/A
     84     4                   (loss due to the next object alignment)
Instance size: 88 bytes (estimated, the sample instance is not available)
Space losses: 0 bytes internal + 4 bytes external = 4 bytes total

**Comment by rkuhn** [comment]
Sorry for the vacation-induced delay.

Avoiding false sharing was never the focus, because we cannot control the alignment of these 64 bytes; adding padding to avoid sharing would add 128 bytes to the size, which is unacceptable unless it is demonstrated to have a large effect on performance. In practice we probably won’t see ActorCells allocated next to each other because each Actor consists of several objects (ActorCell, Actor, Mailbox, behavior stack, …).

**Comment by MQ-EL** [comment]
Thanks for your interpretation.

**Comment by patriknw** [comment]
We'll close this when the pull request is merged.

**Comment by ktoso** [comment]
Resolved via #16645
