### ISSUE TITLE
Use log-remote-lifecycle-events in ReliableDeliverySupervisor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16615]
Currently the supervisionStrategy logs at warning level without checking log-remote-lifecycle-events.
See https://groups.google.com/d/msg/akka-user/EmLK1mEMb3U/G5adxGoeIWQJ

I don't know why that is treated differently than other logging in the endpoint writers. Perhaps there is a good reason (and we can close this without action).

**Comment by Captain1653** [comment]
This issue is quite old. Class `ReliableDeliverySupervisor` was removed in [this PR](https://github.com/akka/akka/pull/31765/files#diff-46e0a9d8effa0fdad1b576f8113b5dc35bd033305b12818054037ea8af4bbe92L216).

Should this issue be closed?

**Comment by patriknw** [comment]
yes, thanks. Everything related to classic remoting should be closed. I'll make an attempt to search for such.
