### ISSUE TITLE
CircuitBreaker should provide statistics like Netflix Hystrix does

### ISSUE THREAD

**Issue by fkoehler** [akka/akka#16617]
It would be great if the akka CircuitBreaker would provide some kind of metrics stream like the Netflix Hystrix framework so we forward these to i.e. statsd or write a dashboard like https://github.com/Netflix/Hystrix/tree/master/hystrix-dashboard

I think this would help to get insight into the state of a running system and react to problems. See the hystrix docu for more information.

**Comment by patriknw** [comment]
Thanks for the idea. Sounds like it would be a great community contribution.

**Comment by maciekciolek** [comment]
Hello, I am interested in implementing this statistics.

My first idea was to extend current implementation of CircuitBreaker and add the method which will return the Source[CircuitBreakerEvent], but it will require the dependency of akka-stream in core.

Maybe it would be great to extend current implementation with additional listeners for specific situation (timeout etc.) and in akka-contrib module implement CircuitBreakerWithMetrics which will use above listeners internally in order to expose stream of events and some extras for aggregation? 

What do you think, maybe you have some better design solutions?

**Comment by patriknw** [comment]
That sounds great, thanks for picking it up.
Maybe the stream part can start out in https://github.com/akka/akka-stream-contrib ?

**Comment by maciekciolek** [comment]
akka-stream-contrib looks good to me. I will collect all my ideas, as regards type of events which we would like to support for CircuitBreaker.

**Comment by maciekciolek** [comment]
I collected all events, which seems to be useful for CircuitBreaker. What do you think about the idea for adding time and tags to each event? Time will be useful to accurately solve problems, if they occur. Tags can be helpful to group events during processing eg. for metrics / dashboards / notifications.

```
/**
  * Basic trait for CircuitBreaker events.
  */
sealed trait Event {
  def time: Date

  def tags: List[String]
}

sealed trait FailureCause

case object Timeout extends FailureCause

case object BreakerOpen extends FailureCause

case object BreakerHalfOpen extends FailureCause

/**
  * Emitted when new CircuitBreaker invocation started.
  */
case class ExecutedEvent(time: Date, tags: List[String]) extends Event

/**
  * Emitted after successful CircuitBreaker invocation.
  */
case class SuccessEvent(time: Date, tags: List[String]) extends Event

/**
  * Emitted after failed CircuitBreaker invocation.
  */
case class FailureEvent(cause: FailureCause, time: Date, tags: List[String]) extends Event

/**
  * Emitted when CircuitBreaker goes into open state.
  */
case class OpenedEvent(time: Date, tags: List[String]) extends Event

/**
  * Emitted when CircuitBreaker goes into half-open state.
  */
case class HalfOpenedEvent(time: Date, tags: List[String]) extends Event

/**
  * Emitted when CircuitBreaker goes into closed state.
  */
case class ClosedEvent(time: Date, tags: List[String]) extends Event
```

**Comment by patriknw** [comment]
what is `ExecutedEvent`? isn't it more interesting to emit events for successful and failed calls, including the duration for the calls. In Lagom with defined this SPI for circuit breaker metrics: https://github.com/lagom/lagom/blob/master/spi/src/main/java/com/lightbend/lagom/internal/spi/CircuitBreakerMetrics.java

**Comment by maciekciolek** [comment]
I finally decided to removed this ExecutedEvent as you also noticed. It comes from Hystrix metrics documentation, but it is not necessary. I also added duration to Success / Failure event in order to support calculating average latency etc. So, I am working on that and make PR as soon as it is possible :)

**Comment by maciekciolek** [comment]
Initial implementation which can be than used to expose metrics has been done by me here #22244

**Comment by maciekciolek** [comment]
@patriknw I am currently working on exposing those metrics with Akka Streams at akka-contrib. As soon as #22244 is merged I will create PR with CircuitBreakerMetrics. WIP can be checked here: https://github.com/maciekciolek/akka/pull/1/files.

**Comment by patriknw** [comment]
First part done, but keeping the ticket open for more

**Comment by maciekciolek** [comment]
Exactly, I will contribute the rest of this soon

**Comment by maciekciolek** [comment]
@patriknw could you please take a look at this PR: https://github.com/akka/akka/pull/22725?

**Comment by ihostage** [comment]
If we talk about metrics of CircuitBreakers, it looks like a part of #30241
