### ISSUE TITLE
Missing scheduled AttemptSysMsgRedelivery

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16616]
Setup cluster.
Blackhole between node1 and node2.
Watch between actors on node1 and node2. (this system message is dropped because of blackhole)
Pass through again between node1 and node2.
Stop the watched actors.
Expected Terminated is never received. (the Watch system message is not delivered)

It looks like the reason is that scheduled AttemptSysMsgRedelivery is missing there somewhere.
It works if sending another system message after the pass through.

**Comment by drewhk** [comment]
This sounds bad. How come that there is no test covering this case? Anyway, I can pick this one.

**Comment by patriknw** [comment]
I have created a test case for it (needs some cleanup). There is another (more urgent) thing I would like your help with when you start working again. I'll email you.

**Comment by patriknw** [comment]
It is probably good to fix this together with #16623

**Comment by drewhk** [comment]
The AttemptSysMsgDelivery is ignored in Gated because the Ungate message will be used instead. I made the system message delivery stressspec much, much more aggressive and there is no problem resending. What is the test you used? You say that you watch between the two actors, and then you stop them, but then there is noone there to receive a Terminated.  Do you have a code snippet?

**Comment by patriknw** [comment]
When I was finding it I had changed SurviveNetworkInstabilitySpec to something like this.

    "heal after a broken pair" taggedAs LongRunningTest in within(45.seconds) {
      system.actorOf(Props[Echo], "echo1")
      system.actorOf(Props[Echo], "echo2")
      enterBarrier("echo1-started")
      system.actorSelection(node(first) / "user" / "echo1") ! Identify(None)
      val firstRef: ActorRef = expectMsgType[ActorIdentity].ref.get
      system.actorSelection(node(second) / "user" / "echo1") ! Identify(None)
      val secondRef: ActorRef = expectMsgType[ActorIdentity].ref.get

      runOn(first) {
        testConductor.blackhole(first, second, Direction.Both).await
      }
      enterBarrier("blackhole-2")

      runOn(first) {
        watch(secondRef)
      }
      runOn(second) {
        watch(firstRef)
      }
      runOn(third) {
        watch(secondRef)
      }

      runOn(first) { assertUnreachable(second) }
      runOn(second) { assertUnreachable(first) }
      runOn(third, fourth, fifth) {
        assertUnreachable(first, second)
      }

      enterBarrier("unreachable-2")

      runOn(first) {
        testConductor.passThrough(first, second, Direction.Both).await
      }
      enterBarrier("repair-2")

      // This test illustrates why we can't ignore gossip from unreachable aggregated
      // status. If all third, fourth, and fifth has been infected by first and second
      // unreachable they must accept gossip from first and second when their
      // broken connection has healed, otherwise they will be isolated forever.

      enterBarrier("after-2")
      assertCanTalk(first, second, third, fourth, fifth)

      println(s"# healed again") // FIXME

      runOn(first) {
        system.actorSelection("/user/echo1") ! PoisonPill
      }

      runOn(second) {
        system.actorSelection("/user/echo1") ! PoisonPill
      }
      runOn(third) {
        system.actorSelection("/user/echo1") ! PoisonPill
      }

      runOn(first) {
        expectTerminated(secondRef)
      }
      runOn(second) {
        expectTerminated(firstRef)
      }
      runOn(third) {
        expectTerminated(secondRef)
      }

      enterBarrier("after-2-final")
    }

**Comment by drewhk** [comment]
Thanks I will look at it then later.

**Comment by patriknw** [comment]
I will write a proper test for this.

**Comment by drewhk** [comment]
thanks, I guess I see a possible problem
