### ISSUE TITLE
akka-persistence: JournalProtocol/SnapshotProtocol should extend 3 marker traits

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16612]
Currently [JournalProtocol](https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/JournalProtocol.scala) and [SnapshotProtocol] (https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/Snapshot.scala#L115) do not extend any  marker traits.

This is problematic for persistence plugin development, when custom Journal and Snapshot actors
need process other in-band commands, such as cluster replication.

[For example, here](https://github.com/carrot-garden/akka-persistence-chronicle/blob/master/src/main/scala/akka/persistence/chronicle/Journal.scala#L273) wildcard case will potentially forward wrong commands down to the persistence supertype.

Solution is to provide 3 marker traits and have relevant messages extend them:
```
sealed trait PersistenceCommand
sealed trait PersistenceJournalCommand
sealed trait PersistenceSnapshotCommand
```

**Comment by patriknw** [comment]
sounds like a good addition, thanks

**Comment by Andrei-Pozolotin** [comment]
see https://github.com/akka/akka/pull/16633
