### ISSUE TITLE
Include best-practice tip on messages in companion object in docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16614]
We do say in the docs that putting `props` into the companion object is a good practice, but I think we also should say this about actor messages. It should be mentioned in actors/best-practices: http://doc.akka.io/docs/akka/2.3.8/scala/actors.html#recommended-practices

Idea came from SO discussion: http://stackoverflow.com/questions/27767008/where-should-messages-be-declared/27768457?noredirect=1#comment43952849_27768457

**Comment by jaceklaskowski** [comment]
Just found it that might be of use in the issue - in another question on StackOverflow [How to restrict actor messages to specific types?](http://stackoverflow.com/q/5547947/1305344) @viktorklang [said](http://stackoverflow.com/a/5551034/1305344):

> The common practice is to declare what messages an Actor can receive in the companion object of the Actor, which makes it very much easier to know what it can receive.

It was almost **four** years ago (!)

**Comment by meln1k** [comment]
Here is the PR https://github.com/akka/akka/pull/16668

**Comment by ktoso** [comment]
Great, thanks!

-- 
Konrad 'ktoso' Malawski
(sent from my mobile)
