### ISSUE TITLE
akka-persistence-chronicle: new plugin contribution

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16619]
please consider new persistence plugin
[akka-persistence-chronicle](https://github.com/carrot-garden/akka-persistence-chronicle)
for inclusion under terms #16618

**Comment by patriknw** [comment]
sounds like a great persistence plugin, you are welcome to submit it to http://akka.io/community/

**Comment by Andrei-Pozolotin** [comment]
Unless akka has some form of  #16618 I do not think we are going to bother.

**Comment by rkuhn** [comment]
Adding a link to the community page will not hurt in any case, if only for later-on seeding the Akka modules space. Would you mind opening a PR?

**Comment by Andrei-Pozolotin** [comment]
ok. pending 2.4 release: https://github.com/akka/akka.github.com/pull/179
