### ISSUE TITLE
persistence - redeliveryTick may cause problems with receiveTimeout

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16629]
Have not confirmed it, but seems plausible as I didn't bump into much special-handling of the tick.

Feedback collected from: http://jdgoldie.github.io/blog/2015/01/07/reliable-delivery-in-akka-and-number-9/

> Each actor using AtLeastOnceDelivery sets up a redeliveryTick system timer to trigger a check for unconfirmed messages. This timer fires even when the actor has no unconfirmed messages. The tick has the side effect of making receiveTimeout unusable. On a recent project that used the cluster sharding extension with passivation support, this conflict prevented actors from passivating correctly. Actors using AtLeastOnceDelivery with no unconfirmed messages would refuse to passivate as long as they were receiving the redeliveryTick.

We should verify if this is in fact the case and improve upon it if it is.

**Comment by hekailiang** [comment]
I have the same problem when I tried to use AtLeastOnceDelivery and receiveTimeout together on one actor. But I found a workaround which is to setReceiveTimeout on an child actor of the AtLeastOnceDelivery one, and send heart beat message to the child actor when AtLeastOnceDelivery one receive message. When child actor receive ReceiveTimeout message, it will send the passivation message to its grand parent actor.
