### ISSUE TITLE
Add the actor system name to the Slf4jLogger context

### ISSUE THREAD

**Issue by raboof** [akka/akka#16630]
It would be nice to add the current actor system name to the MDC in https://github.com/akka/akka/blob/master/akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala

**Comment by ktoso** [comment]
Could be useful indeed, if you have multiple actor systems in one app for some reason. I'm guessing that's the use case you're having or is there something else?

**Comment by raboof** [comment]
Correct!

**Comment by ktoso** [comment]
In general we tend to recommend having multiple dispatchers in one actor system instead of multiple actor systems. But I guess adding the system name to the MDC could be useful anyway. Thanks for reporting!

**Comment by meln1k** [comment]
Dear hAkkers,

I'm a newcomer who wants to contribute. I think I'll be able to do this issue.

If I not mistaken, in this issue I should add an actorSystem field in akka.event.Logging.LogEvent trait, and then put it's value in MDC in akka.event.slf4j.Slf4jLogger#withMdc method.

I'd be glad to know if I'm missing something.

**Comment by raboof** [comment]
I don't think you need to change LogEvent, as the Slf4jLogger is an actor and thus has access to the actorsystem

**Comment by hepin1989** [comment]
but the logSource contains the actorSystem's name already

**Comment by meln1k** [comment]
@raboof shame on me. I forgot that logging is local to actorSystem, and I thought that I can't use Slf4jLogger's actorSystem here. Now it seems much more clear to me.

**Comment by meln1k** [comment]
Unless I'm missing something it's a small fix. Before submitting a PR, I'd like to know if I got the flow mostly right.

https://github.com/meln1k/akka/compare/wip-16630-add-actor-system-name-to-Slf4jLogger-context-meln1k

If this looks good I'll make the PR, otherwise I happy to get corrected.

**Comment by meln1k** [comment]
@hepin1989 I've updated the branch according to your comment.

**Comment by meln1k** [comment]
Can anyone tell me please what should I do next? Should I make a pull request?

**Comment by patriknw** [comment]
@meln1k thanks for contributing. Yes, please create a pull request.

**Comment by meln1k** [comment]
Here is the pull request. 
https://github.com/akka/akka/pull/16649

**Comment by ktoso** [comment]
Merged, thanks a lot for the contribution! :-)
Resolved by @meln1k in https://github.com/akka/akka/pull/16649
