### ISSUE TITLE
Enable FlexiMerge/FlexiRoute to validate which ports are connected

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16631]
While writing up docs on FlexiMerge / FlexiRoute I bumped into a case where I thought:
"I wish I could only blow throw an exception in `inputHandles` if the `important` port is not connected, I don't really care how many ports are connected - it's at least two, the `important` one and one of the additional ports".

API would be something like:

```scala
      val important = createInputPort[A]()
      val additional = createInputPort[A]()
      val stats = createInputPort[Stats]()

      def createMergeLogic = new MergeLogic[(A, B)] {
// currently:
//         override def inputHandles(inputCount: Int) = {
//           require(inputCount == 2, s"Zip must have two connected inputs, was $inputCount")
//          Vector(important, additional, stats)
//        }
         override def inputHandles(connected: ConnectedInputs) = {
          require(connected(important), s"The `important` port must be connected! Connected inputs: $connected") // well, this would be just ints I guess?
          Vector(important, additional, stats)
        }
// ...
```

Same could be done for `FlexiRoute`.

Probably not very high on our priority list, but does seem useful (unless I missed something).

**Comment by drewhk** [comment]
After https://github.com/akka/akka/issues/16902 this might be not relevant
