### ISSUE TITLE
serialization: move identifier into reference.conf both for akka and for plugins

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16632]
as discussed here https://github.com/akka/akka/pull/16475
move ```akka.serialization.Serializer.identifier()``` into ```reference.conf``` 
both for akka and for plugins

**Comment by hepin** [comment]
+1

**Comment by Andrei-Pozolotin** [comment]
need to come up with config name space contract, for example:
```
akka {
   serialization {
      identifier {
         "akka.serialization.NullSerializer" = 0
         "akka.serialization.JavaSerializer" = 1
         "akka.serialization.ByteArraySerializer" = 4
         "akka.cluster.metrics.protobuf.MessageSerializer" = 10
      }
   }
}
```
@patriknw WDYT?

**Comment by hepin** [comment]
how about this?
```
      serializers {
        kryo {
          identifier = 20
          clazz = "akka.serialization.KryoSerializer"
        }
        proto {
          identifier = 21
          clazz = "akka.remote.serialization.ProtobufSerializer"
        }
      }
```

**Comment by patriknw** [comment]
@hepin1989 I like your suggestion, but we can't change current format.
We currently have:

    akka.actor.serializers {
      java = "akka.serialization.JavaSerializer"
      bytes = "akka.serialization.ByteArraySerializer"
    }

    akka.actor.serialization-bindings {
      "[B" = bytes
      "java.io.Serializable" = java
    }

I think we can use your proposal @Andrei-Pozolotin, but prefixin with something closer to what we have. E.g. 

    akka.actor.serialization-identifiers {
         "akka.serialization.NullSerializer" = 0
         "akka.serialization.JavaSerializer" = 1
         "akka.serialization.ByteArraySerializer" = 4
         "akka.cluster.metrics.protobuf.MessageSerializer" = 10
    }

**Comment by hepin1989** [comment]
```
akka.actor.serialization-identifiers {
  java = 1
  bytes = 4
}
```
I think just using the name is ok.we don‘t need repeat that again
