### ISSUE TITLE
akka-http-marshallers are not published

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16646]
Reported by Gerald Mixa via akka-user:

> Hi,
> i want to report a inconsisty of the akka documentation.
> the folloing class should be in akka http
http://doc.akka.io/api/akka-stream-and-http-experimental/1.0-M2/index.html#akka.http.marshallers.sprayjson.SprayJsonSupport
> 
> at least to the scaladoc documentation.
> 
> Due to the javadoc documentation it is not.
> 
> In the jar files its not contained. Seems there is som flaw in the doc and code publishing process

Seems that publishing did not include akka-http-marshallers somehow: http://search.maven.org/#search%7Cga%7C1%7Ca%3Aakka-http-*

Even though it is included as aggregate on streamAndHttp aggregates httpParent: https://github.com/akka/akka/blob/release-2.3-dev/project/AkkaBuild.scala#L335
And httpParent aggregates these marshallers projects: https://github.com/akka/akka/blob/release-2.3-dev/project/AkkaBuild.scala#L345

Doesn't seem intentional to not publish them, investigating now.

// cc @jrudolph @sirthias

**Comment by jrudolph** [comment]
http-marshallers is only an aggregation project for sbt. You need to use the `akka-http-spray-json-experimental` or `akka-http-xml-experimental` projects separately as outlined in #15656.

**Comment by ktoso** [comment]
And it's even listed on http://search.maven.org/#search%7Cga%7C1%7Ca%3Aakka-http-* ...
Sorry, having a very bad day today. Closing as invalid.
