### ISSUE TITLE
Convert stream reference docs to java

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16652]

**Comment by patriknw** [comment]
Let's collaborate on this. Write a note in this ticket of which section you are grabbing.

**Comment by patriknw** [comment]
I start with with introduction and quick start, including setting up the java8 project for the code.

**Comment by drewhk** [comment]
I take "basics and working with flows"

**Comment by patriknw** [comment]
I take "Working with Graphs"

**Comment by patriknw** [comment]
@drewhk what is the status of "basics and working with flows"? Do you have anything that I or @ktoso can continue on?

**Comment by patriknw** [comment]
I grab "Buffers and working with rate"

**Comment by patriknw** [comment]
I grab "Custom stream processing"

**Comment by ktoso** [comment]
Picking the next one then: stream-integrations

**Comment by patriknw** [comment]
Custom stream processing was added by: https://github.com/akka/akka/commit/9c843fb0cc71426bd3009ec3b5c7eb5366ce61da

**Comment by patriknw** [comment]
I'm working on "Basics and working with Flows" (took over from Endre)

**Comment by patriknw** [comment]
I'll continue with "Working with streaming IO"

**Comment by rkuhn** [comment]
remaining: cookbook (tracked in #16787)
