### ISSUE TITLE
HTTP Form upload hangs if the server has been port scanned with nc (GNU netcat 0.7.1)

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16653]
So we now have an issue where if we check for server availability from the outside by using nc, the following curl upload will fail.

This fails on Linux with GNU netcat 0.7.1 and on OS X if you install GNU netcat by doing `brew install netcat`. The default OS X nc command doesn't provoke this behavior.

Reproducer coming shortly.

/cc @sirthias @jrudolph

**Comment by patriknw** [comment]
merged to master and release-2.3
