### ISSUE TITLE
Add formFieldMap , formFieldMultiMap & formFieldSeq Directives

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#16651]
need add ``` formFieldMap``` , ```formFieldMultiMap``` & ```formFieldSeq```, which will be very handy just like the parameter ones

**Comment by ktoso** [comment]
This will be very similar to https://github.com/akka/akka/blob/release-2.3-dev/akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala#L25 so somone could pick it up :-)

**Comment by wjur** [comment]
If no one is working on this I'd like to investigate this more and, afterwards, try to implement the directives.

**Comment by ktoso** [comment]
Thanks for stepping up @wjur! Please have a look at the above linked directives, the ones we'll need here are very similar in design and should be not too hard to implement. Let me know if you need any more help or pointers, I'll gladly help out.

// Marking as in progress :-)
