### ISSUE TITLE
Inconsistent NodeMetrics message order in ClusterMessageSerializer

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#16667]
I notice the issue when I was developing the cluster metrics monitor tool for our cluster.I simply based it on the current tools provided by akka,but finally we found the metrics data is messed up once in a while.

cause,the time stress,I didn't report it very soon,I just simple implement one,yes rebuild the wheel.back the issue.

issue:
if you subscribe the ClusterMetricsChanged event,and trying to use id via ```nodeAddress -> Seq[NodeMetrics]```,then you will finally find the ```Inconsistent``` for the mapping.
eg.``` address A -> nodeMetrics A``` you expected,but may got  ```address A -> nodeMetrics B```

cause:
https://github.com/akka/akka/blob/release-2.3/akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala#L353
and 
https://github.com/akka/akka/blob/release-2.3/akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala#L354
will cause the same problem that just not show up

the problem is caused by that ```iterating a set is inconsistent```

will fire a PR later

**Comment by hepin1989** [comment]
PR attached

**Comment by patriknw** [comment]
merged to release-2.3, pending forward port to master

**Comment by hepin1989** [comment]
will update later for the master

**Comment by hepin1989** [comment]
https://github.com/akka/akka/pull/16748 for master
