### ISSUE TITLE
Bug in Stream Documentation- a link in the documentation is bad

### ISSUE THREAD

**Issue by LogicalTime** [akka/akka#16670]
On this page:
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/scala/stream-quickstart.html

In this sentence:
For convenience a number of common Sinks are predefined and collected as methods on the :class:Sink companion object. 

The link does not work:
http://doc.akka.io/api/akka-stream-and-http-experimental/1.0-M2-SNAPSHOT/#akka.stream.scaladsl.Sink$

The link should be:
http://doc.akka.io/api/akka-stream-and-http-experimental/1.0-M2/#akka.stream.scaladsl.Sink$

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by ktoso** [comment]
Was along the way by https://github.com/akka/akka/commit/7b54b8e9d691f34dcdad814c320f28737e1228b4

**Comment by 2m** [comment]
This is still not right. Currently [M5 docs](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M5/scala/stream-quickstart.html) page points to [M4 scaladoc](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M5/scala/stream-quickstart.html). It needs to be replaced with `@version@`.
