### ISSUE TITLE
Add cookbook recipes for integration with various 3rd party, non-stream API

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16682]
Just a few small examples that we can point people to: 
- API with backpressure, giving back a Future
- API with backpressure, calling a callback (convert to a Future, doh)
- Blocking API
- API with no backpressure whatsoever (async, fire-and-forget)
- API that needs some context (session, threadlocals)

We don't need to write all, but at least give some pointers.

**Comment by 13h3r** [comment]
I think example about integration external API as managed source will be useful. For example - how to emit elements from servlet api (put you api here) requests to existing flow.

**Comment by johanandren** [comment]
Covered by the Akka blog articles from last fall.
