### ISSUE TITLE
Rename GraphFlow

### ISSUE THREAD

**Issue by 2m** [akka/akka#16687]
Even if `GraphFlow` is not in public API it is still a bit confusing since there is `FlowGraph` and `FlowGraphBuilder` as well.

Related discussion: https://groups.google.com/forum/#!topic/akka-user/CZdPnQE6ILg

**Comment by ktoso** [comment]
Do we have any ideas how to call this guy now (`GraphFlow`)? 
I'm drawing a blank currently - as confusing as the name may be it is pretty accurate.

**Comment by drewhk** [comment]
GraphBackedFlow? That gives me all the information that I need:
 - It is a Flow
 - inside it is backed by a Graph

**Comment by ktoso** [comment]
`GraphBackedFlow` seems good. 
Any votes for other names? // cc @patriknw @rkuhn 
I'll go ahead with this one in a sec

**Comment by patriknw** [comment]
I'm fine with `GraphBackedFlow`

**Comment by bantonsson** [comment]
:+1:
