### ISSUE TITLE
Bug in Stream Documentation: StatefulStage

### ISSUE THREAD

**Issue by kodemaniak** [akka/akka#16683]
I think there is a bug in the StatefulStage documentation (http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/scala/stream-customize.html#Using_StatefulStage). The example overrides the initial state as a val, but that leads to a null pointer exception. Using a def resolves that issue.

**Comment by kodemaniak** [comment]
BTW, where are the sources for the stream docs. I was unable to find them.

**Comment by patriknw** [comment]
akka-docs-dev/rst/ in release-2.3-dev branch

**Comment by kodemaniak** [comment]
Thanks! I totally missed that directory.

**Comment by ktoso** [comment]
Thanks for reporting @kodemaniak! Resolved now and shipping with M3 :)
