### ISSUE TITLE
Fix all the FIXMEs in streams and http

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16699]
(the same holds for all TODOs)

**Comment by Bernd-Vogt** [comment]
I'm really looking forward to the new Http-Manager Java API.

And really really hope that the code shown in [JavaTestServer](https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-M3/akka-http-core/src/test/java/akka/http/model/japi/JavaTestServer.java) can be used soon.
