### ISSUE TITLE
add document of how to setup development environment

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#16696]
https://github.com/akka/akka/blob/master/CONTRIBUTING.md this document don't talk about how to setup the development environment.
like how to publishLocal ,how to crossBuild ,how to add dependencies like ```graphviz``` and ```sphinx``` and so on.

It would be handy for the new coming contributions.

**Comment by 2m** [comment]
There is a [page in documentation](http://doc.akka.io/docs/akka/2.3.9/dev/building-akka.html#building-akka) that talks about how to build akka. Feel free to improve it with the missing information.

**Comment by hepin1989** [comment]
ok.I will try :P
