### ISSUE TITLE
Improve junctions documentation and specs

### ISSUE THREAD

**Issue by 13h3r** [akka/akka#16716]
We need to improve documentation on existing junctions like broadcast, merge and so on. 
Things to be described explicitly for every junction:
- how backpressure works
- how errors propagated
- how junction completes

Also I propose to implement this behavior in existing specs.

**Comment by rkuhn** [comment]
Thanks, makes sense. This should be in the respective ScalaDoc and there should be an overview table in the reference docs.

**Comment by drewhk** [comment]
See the PR: https://github.com/akka/akka/pull/17164
