### ISSUE TITLE
Use case class when exposing undefined-ports when building Flow/Sink from Graph

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16715]
As discussed in https://github.com/akka/akka/pull/16702#discussion_r23388580

It would be nice to expose the "undefined ports" more nicely when building a Flow or Source or Sink from a graph, example to make the case (current api):

```scala
Flow[Int, String]() { implicit builder ⇒
          import FlowGraphImplicits._

          val in = UndefinedSource[Int]
          val out = UndefinedSink[String]

          in ~> Flow[Int].map(_.toString) ~> out

          (in, out) // this tuple may be confusing
```

Proposals made so far:
* `FlowEndpoints(in, out)`
* `ExposedFlow(in, out)`
* `Ports(fromUpstream = in, toDownstream = out)`As discussed in https://github.com/akka/akka/pull/16702#discussion_r23388580

It would be nice to expose the "undefined ports" more nicely when building a Flow or Source or Sink from a graph, example to make the case (current api):

```scala
Flow[Int, String]() { implicit builder ⇒
          import FlowGraphImplicits._

          val in = UndefinedSource[Int]
          val out = UndefinedSink[String]

          in ~> Flow[Int].map(_.toString) ~> out

          (in, out) // this tuple may be confusing
```

Proposals made so far:
* `FlowEndpoints(in, out)`
* `ExposedFlow(in, out)`
* `Ports(fromUpstream = in, toDownstream = out)`

**Comment by 13h3r** [comment]
This proposals only covers situation with one input and one output. What about improving API to expose complex flows with several inputs/outputs?
Right now it looks so verbose both on declaring and using.

**Comment by ktoso** [comment]
This is because this issue is aimed at improving special construction methods to "construct a Source from a graph" and "construct a Flow from a graph" where we can guarantee typesafety between `Source[T]` and the exposed `UndefinedSink[T]`, specifically these 3 APIs:

```scala
val so: Source[Int] = 
  Source() { b ⇒ /* ... */ UndefinedSink[Int] }
      
val si: Sink[Int] = 
  Sink() { b ⇒ /* ... */ UndefinedSource[Int] }
      
val fl: Flow[Int, Int] = 
  Flow() { b ⇒ /* ... */ (UndefinedSource[Int], UndefinedSink[Int]) }
```

What you seem to be asking for is improving the exposing of arbitrarily many undefined ports? We have discussed this a while ago, and in summary - it's way more useful to expose these as user-land defined objects instead of something built-in, here is an example of this style (see `Lego`): https://github.com/akka/akka/blob/release-2.3-dev/akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphOpsIntegrationSpec.scala
You're right however that we have not yet documented this. 

Would you mind opening a new ticket @13h3r in which we'll talk about either documenting or helping in some way to expose multiple ports? IMO documenting a certain style of doing this would be of greatest value.

**Comment by drewhk** [comment]
> it's way more useful to expose these as user-land defined objects instead of something built-in,

Well, I don't think this is true in general. There needs to be built-in support that allows to build the user layer abstractions. I thought that we unify n-port abstractions at some point?

**Comment by ktoso** [comment]
My initial thought was about "we won't be able to abstract over type-arity nicely", but I think I have a nice idea to make this nicer in user API now actually. Will PR a draft soon for comments. 
It's along the idea of what `Enumeration` does, so a "builder" and way to iterate over all values, the PartialFlowGraph building can then validate if all ports are included or not and such validations.

**Comment by 13h3r** [comment]
What if we pass required input/output together with `builder`? Then we can get rid of this repeatable parts:

```
          val in = UndefinedSource[Int]
          val out = UndefinedSink[String]
```

and API will looks like

```
Flow[Int, String]() { (b, in, out) ⇒
          implicit val builder = b
          import FlowGraphImplicits._

          in ~> Flow[Int].map(_.toString) ~> out
```

What we get:
- no repeatable and useless `UndefinedSource` and `UndefinedSink` declarations
- no last confusing tuple 

What we loose:
- we should declare builder as implicit explicitly ;). May be there is some kind of more elegant solution. I am not pro with building implicit scala API

What remains the same:
- still no way to validate that `in` and `out` are bound.

**Comment by 13h3r** [comment]
# Idea 2
Also, what if we will extend builder with trait that provides `in` and `out`?

```scala
Flow[Int, String]() { implicit b ⇒
          import FlowGraphImplicits._

          b.in ~> Flow[Int].map(_.toString) ~> b.out
```

Looks like this is more clear and simple, but still no checking for `in` and `out` are bound.

**Comment by drewhk** [comment]
This is superceded by: https://github.com/akka/akka/issues/16902
