### ISSUE TITLE
add quick-restart support for akka cluster

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#16726]
how about automatically down a node that is unreachable now when a new join attempt is made for same ```{ host:port}``` with different uid?
by this way, a node could quick restart and then rejoin the cluster again.
ref to https://github.com/akka/akka/issues/16224

otherwise it takes long time to maintain/hot fix.

**Comment by behrad** [comment]
+1

**Comment by drewhk** [comment]
Probably a good idea since the same host port is then proved to be unaccessible with the old UID.

**Comment by patriknw** [comment]
I agree. This is a nice feature. The way I think we should implement it is that a join attempt with different UID is received we down the old member and let the normal downing/removal procedure continue. The new new node will have to try joining again, and eventually when the old has been removed it will be accepted.

**Comment by hepin1989** [comment]
@patriknw Yes,the issue here https://github.com/akka/akka/issues/16224 seems after a quick restart.some nodes see the rejoining one ```UP```and someone see it ```UNREACHABLE```，then there seems have a blocker.

**Comment by patriknw** [comment]
backport to 2.3
