### ISSUE TITLE
add Extensions to akka.typed.ActorSystem

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16738]
Currently not possible and I don’t want to expose the untyped ActorSystem to do it.

**Comment by patriknw** [comment]
To be decided if they are needed, or should be replaced by ordinary actor. We have used extensions in many places where there is a need for some shared thread-safe component, so I don't see that an actor can replace that.

**Comment by johanandren** [comment]
I think they are unavoidable, even if one less concept sounds tempting, so I'll start adding/porting untyped extensions.

**Comment by patriknw** [comment]
I agree, we could start with making them internal if we are uncertain
