### ISSUE TITLE
figure out ActorSystem.registerOnTermination

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16743]
We have unified and expressed ActorSystem termination as a `Future[Terminated]` that can be obtained from `system.whenTerminated`. The `shutdown` and `awaitTermination` methods have been deprecated since they are superseded by this, but registerOnTermination could just as well be expressed using Future composition.

Either we deprecate registerOnTermination or we add it to the `typed.ActorSystem` as well.

**Comment by johanandren** [comment]
I vote for deprecating `registerOnTermination`. No useful distinction between it and hooking onto `whenTerminated` (except for needing/being able to provide an execution context it will run on).

For things whose shutdown should delay the `ActorSystem` termination I think the new graceful shutdown makes more sense to hook into.

**Comment by patriknw** [comment]
sounds good

**Comment by johanandren** [comment]
After playing around with this for a bit I came to the following insight:

We do not need to deprecate it in untyped to not support it in typed. So I'll just close this ticket and watch some cat videos instead of deprecating anything.
