### ISSUE TITLE
add periodic scheduling to typed ActorSystem

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16742]
… or ActorContext.

**Comment by patriknw** [comment]
For actors we should have the "safe" scheduling facilities similar to `FSM` and `TimerGraphStageLogic`

**Comment by patriknw** [comment]
Something to consider is that timer messages should typically not be part of the ordinary public message protocol and therefore those should perhaps be signals.

**Comment by rkuhn** [comment]
Timers are part of the business logic of the actor, they have meaning in the domain. For that reason I think modeling them as messages that are sent after a delay is both fitting and a very flexible approach. Deferring a message is an operation that is needed anyway, and it happens to solve the timer use-case as well, so I’m against creating two features where one would suffice.

**Comment by patriknw** [comment]
We know what pain [scheduling of periodic messages](http://doc.akka.io/docs/akka/2.5/scala/howto.html#scheduling-periodic-messages) can be in classic actors and we know how to do it better with things similar to FSM and TimerGraphStage timers.

My main reason for suggesting signals was my work on the backoff restarter: https://github.com/akka/akka/pull/22765/files#diff-316585e7880ab75553d0b7f0548fa4e5R210
