### ISSUE TITLE
Akka remoting protocol version negotiation

### ISSUE THREAD

**Issue by huntc** [akka/akka#16746]
Akka needs to be backwardly compatible in support of differing protocol versions. I believe that clusters such as that offered by Riak provide an interesting solution where new cluster members advertise their capability in terms of the protocol versions that they support. The cluster then operates at the lowest version supported by all members of a cluster. This strategy is re-evaluated each time a member joins or leaves the cluster.

Akka-remoting based applications should also be able to leverage a similar approach whereby their application protocol concerns can be similarly negotiated.

**Comment by drewhk** [comment]
Akka remoting protocol has not changed for a long time, only optional fields have been added. Clustering, and additional services have changed their message types over time. The remoting protocol is just a tiny part of the whole stack that needs to remain compatible. Potentially every Akka API message is remote protocol.

**Comment by huntc** [comment]
Thanks @drewhk. Great to hear that the protocol hasn't changed in a long time, although I'm sure you'll agree that it still has the potential for change. Thank you also for describing the wider issue of cluster and other messages. This is what I was alluding to with the following paragraph:

> Akka-remoting based applications should also be able to leverage a similar approach whereby their application protocol concerns can be similarly negotiated.

In hindsight, perhaps "applications" was the wrong word to use. However I do feel that akka-cluster based applications require a means to manage version negotiation. These applications may not be so lucky as the Akka remoting protocol in terms of their potential for change. It feels as though that a solution for Akka in this respect may lead to a solution for akka-cluster based applications.

WDYT?

**Comment by rkuhn** [comment]
I think that this is indeed something that we’ll need to tackle once 2.4.0 is out.

**Comment by drewhk** [comment]
We will need some remote version negotiation, but paradoxically that might be the first version change since 2.2.0 :) It won't get into 2.4 as far as I see.

**Comment by huntc** [comment]
I'll leave the decision on when this gets done to you guys. I'm happy that it is acknowledged. :-)

Meanwhile we'll see if my app needs something as a prelude. Perhaps we can collaborate and share ideas on this problem.

Thanks again.

**Comment by patriknw** [comment]
We have a version in Artery header. Adding support for full negotiation of any application or akka internal (e.g. cluster membership) protocol is out of scope. We are carefully evolving the protocols in a compatible way instead.

**Comment by rkuhn** [comment]
Which level of serialization compatibility is this meant to imply?
