### ISSUE TITLE
Streams docs clarifications re: backpressure and stateful stage thread safety

### ISSUE THREAD

**Issue by sourcedelica** [akka/akka#16765]
I read through the streams docs on the train home from NEScala.  Amazing job guys!  Really outstanding documentation.

A few things that need to be clarified:
- What specifically do "asynchronous" and "non-blocking" mean in the context of "asynchronous non-blocking back-pressure"?  That phrase is used a lot so it would be good to have a definition of the terms.
- Is a `StatefulStream` thread-safe?  That is, do you need to synchronize access to state variables in a stage?

**Comment by drewhk** [comment]
Thanks, we need to clarify these points. I answer here though quickly:

> What specifically do "asynchronous" and "non-blocking" mean in the context of "asynchronous non-blocking back-pressure"? That phrase is used a lot so it would be good to have a definition of the terms.

It means that faster producers are slowed down by slower producers without using blocking calls, i.e. the backpressure signal is not implemented by blocking the producers thread but by asyncronous messaging in the background.

> Is a StatefulStream thread-safe? That is, do you need to synchronize access to state variables in a stage?

Yes, it is safe. It is like an Actor in that sense that it is unsafe to refer to its internals from the outside, but all internal state can be accessed internally safely. Just like Actors where the only safe way to change state of another actor is via send, in stages the safe ways to change state of another stage is by push, pull or the completion handlers.
