### ISSUE TITLE
Make it possible to create your own (Keyed)ActorFlowSource/Sink

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16762]
As described here https://groups.google.com/forum/#!topic/akka-user/qXD1vw_LZlc the methods needed to do materialization in `ActorFlowMaterializer` are akka private and can't be used.

Should we allow outside use of them, or at least provide some mechanism where you declare the Materialization type, and construct a props on the fly, and return the materialized value, so you can inject something into an actor that the user will be able to retrieve from the materialized map?

**Comment by drewhk** [comment]
This is partially enabled by https://github.com/akka/akka/issues/16902. There are now hooks to expose materialized values from Stages, and in fact many of the predefined Sinks now are a Stage and a Sink.ignore.
