### ISSUE TITLE
Convert Cookbook to Java

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16787]

**Comment by ktoso** [comment]
I'll start with a few here - picking up recipies from the tip.

**Comment by patriknw** [comment]
@ktoso isn't this done?

**Comment by ktoso** [comment]
No, Sadlly the APIs changed so much, that I was unable to update my PR last week for M4.
The most recent is https://github.com/drewhk/akka/pull/22 but doesnt compile yet for M4.
