### ISSUE TITLE
FAILED: StatsSampleSingleMasterSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16782]
https://jenkins.akka.io:8498/job/akka-nightly/1965/consoleFull

akka.tcp://StatsSampleSingleMasterSpec@localhost:35340/user/singleton/statsService
[JVM-3] - must show usage of the statsServiceProxy *** FAILED ***
[JVM-3]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class sample.cluster.stats.StatsMessages$StatsResult
[JVM-3]   at scala.Predef$.assert(Predef.scala:165)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:438)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:420)
[JVM-3]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:738)
[JVM-3]   at sample.cluster.stats.StatsSampleSingleMasterSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply$mcV$sp(StatsSampleSingleMasterSpec.scala:122)
[JVM-3]   at sample.cluster.stats.StatsSampleSingleMasterSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(StatsSampleSingleMasterSpec.scala:120)
[JVM-3]   at sample.cluster.stats.StatsSampleSingleMasterSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(StatsSampleSingleMasterSpec.scala:120)
[JVM-3]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:269)
[JVM-3]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:280)
[JVM-3]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:738)

**Comment by patriknw** [comment]
are we sure that this failure didn't happen while the machines were upgraded (see email from Toni)?

**Comment by drewhk** [comment]
Probably a fluke during upgrade of build servers

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2086/

**Comment by patriknw** [comment]
here is another one: https://jenkins.akka.io:8498/job/akka-nightly/2336/consoleFull

**Comment by ktoso** [comment]
Again https://jenkins.akka.io:8498/job/akka-nightly/2603/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2940/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2642/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2942/consoleText

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2662/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2668/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2719/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2721/consoleFull

this one is really failing a lot, we must do something about it

**Comment by patriknw** [comment]
funny, this looks very much as the what I fixed yesterday: https://github.com/akka/akka/pull/18746

**Comment by 2m** [comment]
Failed 6 days ago: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3081/consoleFullhttps://jenkins.akka.io:8498/job/akka-multi-node-nightly/3081/consoleFull

**Comment by patriknw** [comment]
yeah, we have still not merged https://github.com/akka/akka/pull/18746

**Comment by patriknw** [comment]
merged, so this should also be fixed now
