### ISSUE TITLE
Server Sent Event consumption support for Akka-Http client

### ISSUE THREAD

**Issue by ruseinov** [akka/akka#16783]
Hello fellows, 

I'm not sure how to file a feature request, so I will just leave it here.
It would be nice to have SSE consumption support for Akka-Http client, since
there's demand and a lack of java/scala SSE clients. The only client I know is a part of
Jersey-http.

**Comment by patriknw** [comment]
cc @jrudolph

**Comment by jrudolph** [comment]
Server-side ticket: #16843

**Comment by rkuhn** [comment]
This will just be a stream processing stage that chunks the stream of bytes into a stream of events, I take it?

**Comment by jrudolph** [comment]
@rkuhn Couldn't you say this of any network protocol which is implemented with streams? :) The specifics in this case are that you interpret the HTTP entity byte stream in a certain way as specified for the `text/event-stream` MIME type: http://www.w3.org/TR/eventsource/

So, in the end you will probably have something like this:

```scala
case class ServerSentEvent(dataLines: Seq[String], event: String = "", id: String = "", newRetryMillis: Option[Int])

object SSE {
  def parser: Flow[ByteString, ServerSentEvent] = ???
}
```

which you can use to parse the HTTP entity bytes. The specs contain a bit more of information about how a client should actually establish and retry connections so it may make sense to create a higher-level API that deals with reconnections, connection state, etc. automatically as described in the document.

**Comment by rkuhn** [comment]
@jrudolph indeed, thanks for the elaboration :-)

**Comment by ktoso** [comment]
Server side is implemented by @hseeberger in https://github.com/hseeberger/akka-sse
We don't implement it so far, but perhaps would be a nice contrib to akka-sse?

**Comment by hseeberger** [comment]
akka-sse does have client support

**Comment by ktoso** [comment]
Even better, let's close this ticket then, thanks @hseeberger !
