### ISSUE TITLE
Persistence should hook into the shutdown process

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16784]
Just like remoting tries to flush buffered messages (up to a timeout) persistence should somehow be able to control system.awaitTermination as in it should try to flush pending writes (up to a timeout) before awaitTermination triggers.

**Comment by ktoso** [comment]
We're unsure about what safety this would add, since it's not a proper clean shutdown anyway...

**Comment by patriknw** [comment]
I think this can be difficult and there are so many things that are just stopped when system.shutdown so I doubt that adding something extra for persistence will solve the whole user problem.
Ok to close?
@drewhk @ktoso

**Comment by ktoso** [comment]
Agree on closing. 
I don't think we can do much, and users depending on whatever we would try to provide/guarantee seems fishy anyway.

When the world ends, it does so in mysterious ways ;-)
