### ISSUE TITLE
include akka-data-replication

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16799]
think about how and where to pull in Patrik’s library

**Comment by ktoso** [comment]
We had some thoughts on this in this ticket https://github.com/akka/akka/issues/13711#issuecomment-65658295 either as a) separate module b) in the cluster tools grab bag would work

**Comment by patriknw** [comment]
this should be a separate module, especially since it will be experimental and the others will not

**Comment by bantonsson** [comment]
@patriknw :+1: my thoughts exactly
