### ISSUE TITLE
HTTP client not robust

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16795]
client deadlocks after a few requests, see https://groups.google.com/d/msg/akka-user/Gp0TezTei94/x5py6rcY1RIJ

**Comment by sirthias** [comment]
@luksow @CptnKirk I just tried to reproduce the issue based on the latest code and have so far failed.
Have you tried things again with 1.0-M4 release?

**Comment by luksow** [comment]
@sirthias I've run extensive tests with both my demo & bigger app (M5) and it looks like this issue is fixed. Thanks!

**Comment by CptnKirk** [comment]
I also see this as fixed in M4/5. Thanks!

-Jim

-- Sent from my mobile device

**Comment by rkuhn** [comment]
Thanks for checking and reporting!

**Comment by sirthias** [comment]
I'll still issue a PR against this ticket, since we've apparently been missing a test.

**Comment by rkuhn** [comment]
Ah, I missed that aspect, reopening it then.
