### ISSUE TITLE
scala global ExecutionContext and scheduler

### ISSUE THREAD

**Issue by algobardo** [akka/akka#16790]
One of my actor is hanging because of i'm importing
```
 import scala.concurrent.ExecutionContext.Implicits.global 
```
and using 

```
schedule.schedule(3 seconds, self, Message)
```
does not give me any warning, but the message is never delivered.

Is this the supposed warning if i'm not supplying the system.dispatcher execution context ?
If so, since it is quite counterintuitive, can the scheduler raise a runtime warning or smth ?
It has been quite hard to debug, the system was just stuck.

**Comment by algobardo** [comment]
Akka 2.11 -- 2.3.9 and 2.4-SNAPSHOT

**Comment by patriknw** [comment]
You can use `scala.concurrent.ExecutionContext.Implicits.global` as excecution context to `schedule`. It must be something else in your application that is the reason for that the message is not delivered.

**Comment by algobardo** [comment]
I tried to reproduce on a minimal example, and now i have a more clear idea of what's going on.
Perhaps, it is my fault.
The point is that the dispatchers are bounded, and here the dispatchers are working with my Futures, so they are not ready to dispatch the scheduled message.
Is it that right ?

```
import akka.actor.{ActorSystem, Actor, Props}
import akka.event.Logging
import com.typesafe.config.ConfigFactory
import scala.concurrent.Future
import scala.concurrent.duration._
import scala.concurrent.ExecutionContext.Implicits.global


class MyActor extends Actor {
  val log = Logging(context.system, this)
  def receive = {
    case "test" => 
      Future {
        Thread.sleep(1000000)
      } onComplete {x => println("Completed")}
      context.system.scheduler.scheduleOnce(2 seconds, self, "test")
      log.info("received test")
  }
}

object Hi {
  def main(args: Array[String]) = {

    val system = ActorSystem("System")
    var a = 0
    for(a <- 0 to 115) {
      val queue = system.actorOf(Props(classOf[MyActor]), name = "MyActor"+a)
      queue ! "test"
    }
  }
}
```

**Comment by patriknw** [comment]
yes, a dispatcher / execution context has a thread pool and new tasks will be queued if all threads are busy/blocking. Blocking must be carefully managed by running such things on a dedicated dispatcher (never on akka default dispatcher and never on Implicits.global).
