### ISSUE TITLE
Make sure TLS ServerNameIndication extensions works (> Java 7)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16796]
It seems this is available starting from Java 7. Without SNI on the client side it isn't possible to connect to HTTPS servers with "virtual hosts" (i.e. servers listening on one IP address but responding differently depending on the domain name).

See http://en.wikipedia.org/wiki/Server_Name_Indication and [RFC6066](http://tools.ietf.org/html/rfc6066). It seems it should work out-of-the-box [starting with Java 7](http://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html) when the SSLEngine is created with the correct hostname.

See also spray/spray#993.

/cc @sirthias

**Comment by shayangz** [comment]
any plans for addressing this issue?

**Comment by ktoso** [comment]
We recently solved https://github.com/akka/akka/issues/19287 which may be directly relared.
This ticket needs verification with the HEAD of master then.

**Comment by shayangz** [comment]
I don't think it has. Here is a repro in Akka-2.4.2:

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

hitting `https://i-d.vice.com/en_au` using `Http().superPool` results in this failure

```
javax.net.ssl.SSLException: Received fatal alert: handshake_failure
```

even though the SSL cert is fine (it works with URL.openConnection)

**Comment by jrudolph** [comment]
@shayangz the fix has not yet been released. It unfortunately missed 2.4.2 by a few days.

**Comment by rkuhn** [comment]
could we make sure of this before 2.4.3 is released? /cc @patriknw

**Comment by patriknw** [comment]
What needs to be tested? @jrudolph mention a fix, is it in master?

**Comment by ktoso** [comment]
I (likely) fixed this in https://github.com/akka/akka/issues/19287
Will verify it.

**Comment by jrudolph** [comment]
It needs to be tested that an Https request includes the SNI extension in
the TLS handshake. Otherwise requests to an IP hosting several domains
doesn't know which certificate to deliver. #19287 was an observation that
it didn't work in the past but was now fixed. With this fixed I think we
can close this ticket.
Am 23.03.2016 21:10 schrieb "Patrik Nordwall" <notifications@github.com>:

**Comment by patriknw** [comment]
thanks @ktoso, then I assign this to you

**Comment by ktoso** [comment]
Happy to report the above mentioned test url that failed previously now works (on 2.4.3 - to be released)
