### ISSUE TITLE
Rename defer to deferAsync, or clarify the difference in some other way

### ISSUE THREAD

**Issue by anderius** [akka/akka#16797]
I find the semantics of "defer" confusing.

I thought defer was the same as persist, except the given message was not persisted. Now today, when a bug got me to read the doc again, it states that defer has the same semantics as persistAsync.

My first thought was that "defer" should be renamed "deferAsync", to communicate the relation to persistAsync. Both are async, but the point is that persist is executed before the next command is processed, while persistAsync is not.

**Comment by patriknw** [comment]
thanks
