### ISSUE TITLE
Scala.* package imports in OSGi have an improper version range

### ISSUE THREAD

**Issue by jgulotta** [akka/akka#16791]
Since release 2.3.7 the OSGi manifest imports too large a version range for `scala.*` packages.

**scala.* imports for akka-actor_2.10-2.3.6**
```
Import-Package: scala.collection.convert;version="[2.10,2.11)"
Import-Package: scala.collection.generic;version="[2.10,2.11)"
Import-Package: scala.collection.immutable;version="[2.10,2.11)"
Import-Package: scala.collection.mutable;version="[2.10,2.11)"
Import-Package: scala.collection.parallel.immutable;version="[2.10,2.11)"
Import-Package: scala.collection.parallel;version="[2.10,2.11)"
Import-Package: scala.collection;version="[2.10,2.11)"
Import-Package: scala.concurrent.duration;version="[2.10,2.11)"
Import-Package: scala.concurrent.forkjoin;version="[2.10,2.11)"
Import-Package: scala.concurrent.util;version="[2.10,2.11)"
Import-Package: scala.concurrent;version="[2.10,2.11)"
Import-Package: scala.math;version="[2.10,2.11)"
Import-Package: scala.reflect;version="[2.10,2.11)"
Import-Package: scala.runtime;version="[2.10,2.11)"
Import-Package: scala.sys;version="[2.10,2.11)"
Import-Package: scala.util.control;version="[2.10,2.11)"
Import-Package: scala.util.hashing;version="[2.10,2.11)"
Import-Package: scala.util.matching;version="[2.10,2.11)"
Import-Package: scala.util;version="[2.10,2.11)"
Import-Package: scala;version="[2.10,2.11)"
```

**scala.* imports for akka-actor_2.10-2.3.7**
```
Import-Package: scala.collection.convert;version="[2.10,2.101)"
Import-Package: scala.collection.generic;version="[2.10,2.101)"
Import-Package: scala.collection.immutable;version="[2.10,2.101)"
Import-Package: scala.collection.mutable;version="[2.10,2.101)"
Import-Package: scala.collection.parallel.immutable;version="[2.10,2.101)"
Import-Package: scala.collection.parallel;version="[2.10,2.101)"
Import-Package: scala.collection;version="[2.10,2.101)"
Import-Package: scala.concurrent.duration;version="[2.10,2.101)"
Import-Package: scala.concurrent.forkjoin;version="[2.10,2.101)"
Import-Package: scala.concurrent.util;version="[2.10,2.101)"
Import-Package: scala.concurrent;version="[2.10,2.101)"
Import-Package: scala.math;version="[2.10,2.101)"
Import-Package: scala.reflect;version="[2.10,2.101)"
Import-Package: scala.runtime;version="[2.10,2.101)"
Import-Package: scala.sys;version="[2.10,2.101)"
Import-Package: scala.util.control;version="[2.10,2.101)"
Import-Package: scala.util.hashing;version="[2.10,2.101)"
Import-Package: scala.util.matching;version="[2.10,2.101)"
Import-Package: scala.util;version="[2.10,2.101)"
Import-Package: scala;version="[2.10,2.101)"
```

This causes Akka 2.10 to resolve Scala 2.11 classes when both Scala 2.10 and 2.11 are in use.

There is a similar problem for akka-actor_2.11-2.3.7+ where the version range is `[2.11,2.111)`, which would experience the same issue if run in an environment with Scala 2.12+ (whenever that exists).

Since Akka 2.10 imports to 2.101 and 2.11 imports to 2.111, I suspected a string concatenation instead of numerical addition. So far I have traced the cause to [here](https://github.com/akka/akka/blob/master/project/OSGi.scala#L62), which does indeed do concatenation instead of addition.

```
val ScalaVersion = """(\d+)\.(\d+)\..*""".r
val ScalaVersion(epoch, major) = version
versionedImport(packageName, s"$epoch.$major", s"$epoch.${major+1}")`
```

This code was introduced on 2014-11-30 in [this pull request](https://github.com/akka/akka/pull/16371/files#diff-f862909d2853386601985172466fd7f6L9). Prior to that, the epoch and major version were converted to integers with `toInt`.

I expect the trivial change below will set the import range correctly, through I've not yet tried to build the artifacts with the change to verify.

```
versionedImport(packageName, s"$epoch.$major", s"$epoch.${major.toInt+1}")
```

**Comment by patriknw** [comment]
@jgulotta thanks for reporting. Would you like to open a pull request? Then target it to `release-2.3` branch.

**Comment by jgulotta** [comment]
Looks like the `release-2.3` branch does not have `OSGi.scala` as in the `master` branch, but there is the same problem in `AkkaBuild.scala`.

I made the one line change on both branches and validated it fixes the imports. Are there any tests I can update?

I'd like to be sure the fix makes it to all the necessary places in all the necessary branches. Should I send two PRs, one for `release-2.3` and one for `master`? Do any other branches require the fix?

**Comment by patriknw** [comment]
two PRs please

the test/sample is https://github.com/akka/akka/tree/master/akka-samples/akka-sample-osgi-dining-hakkers

There is an issue with the sample on the release-2.3 branch: https://github.com/akka/akka/issues/16703

> I tried the same on master but the artifacts do not seem to build for OSGi by default.

I don't know what that means. As far as I know it is supposed to work with normal `publishLocal` and `publishM2`

**Comment by jgulotta** [comment]
Ah, `publichLocal`. I was using `package`. I don't know if `publishLocal` is normal as I've neither used sbt nor built Akka before yesterday.

What I meant by "do not seem to build for OSGi" was, on `release-2.3` the `package` command results in jars that have an OSGi manifest. On `master`, the `package` command results in jars that do not have an OSGi manifest. I didn't know about `publishLocal`.

But `publishLocal` does work and I've now validated the fix on `master` as well.

I'll look into the tests and see if the import version range can be validated there. I should have the PRs up in a couple hours either way, after lunch.

**Comment by jgulotta** [comment]
Well, yesterday got busier than expected and I wasn't able to find a good way to add a test for this fix, but the PRs are open now.

**Comment by jgulotta** [comment]
@patriknw Just out of curiosity, what happens now that the PRs have passed the CI tests? I see a number of other PRs in that state. How/when do they get merged and issues closed?

**Comment by patriknw** [comment]
we will merge them, or ask for adjustments, when we have reviewed
thanks!
