### ISSUE TITLE
No serialization-bindings for akka.persistence.journal.AsyncWriteTarget$WriteMessages

### ISSUE THREAD

**Issue by cowboy129** [akka/akka#16802]
akka persistence 2.3.9 wrapped the persistent event with `WriteMessages`.
When the journal actor is a remote actor, the system try to use `akka.remote.MessageSerializer` to serialize the `WriteMessages`, and it finally choose the default `JavaSerializer`.

And then, if the user's persistent event is not Serializable, the serialization will fail.

**Comment by patriknw** [comment]
Thanks for reporting. To clarify for other readers; a remote journal/store is only used for testing, e.g. `SharedLeveldbStore`.
