### ISSUE TITLE
Prevent unnecessary reverse DNS lookups when creating client SSLEngine

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16808]
See spray/spray#993.

On the client side the SSLEngine needs to created with the target hostname so that the TLS SNI extension works (starting from Java 7). If `InetSocketAddress.getHostName` is called for this purpose with an IP address, a unnecessary reverse DNS lookup will be initiated. Using `InetSocketAddress.getHostString` would be the right solution but is only available from Java 7, so using reflection may be the best solution.

**Comment by RichardBradley** [comment]
See also #17059 -- please check that HTTP connections also don't do a reverse DNS lookup to generate the `Host` header when connecting to a host by IP address.

**Comment by agolubev** [comment]
Hey there,
I checked DNS lookup problem with HTTP connection. The problem exists for HTTP as well.
Following snippet is used
```scala
val conn=Http().outgoingConnection("74.125.226.70")
(Source.single(HttpRequest()) via conn runWith Sink.head).onComplete(println(_))
```
Issue is in [http-core HttpRequestRendererFactory line 96](https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-RC1/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpRequestRendererFactory.scala#L96) that's creating Host with InetSocketAddress 
Solution that I can see will be similar to what was done for spray/spray#993. 

Still reflection maybe not the best solution here. Is it an option to change RequestRenderingContext?

**Comment by jrudolph** [comment]
@agolubev I think that's what @RichardBradley also commented on above.

I don't think it would suffice to change `RequestRenderingContext`. Instead, it would be necessary to replace all usages of `InetSocketAddress` from the API-layer up to this place. 

I'd say we can go with the reflective solution for akka 2.3 and when support for Java 1.6 is dropped (which AFAIK will be done with Akka 2.4 which is due soon enough) this hack can be removed again. WDYT?

**Comment by agolubev** [comment]
Ok, let me create reflective fix and I'll do pull request then.
Also will try to reproduce the same scenario with HTTPS. There is no documentation on this point so would appreciate any hint

**Comment by agolubev** [comment]
My bad. I switched SBT to 1.6 in a wrong way. That's why the issue was reopened.
Just made two version of fix (and did two pull requests). They both work with 1.8 and 1.6

**Comment by jrudolph** [comment]
@agolubev I've already pushed a somewhat more involved patch here: https://github.com/akka/akka/pull/17658

**Comment by agolubev** [comment]
ok =(
