### ISSUE TITLE
Document json4s marshaller support

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16812]
Make sure to provide a type-class based solution that prevents that the json4s marshallers will be used for any kind of data.

See spray/spray#990 for an issue of the old spray based design.

**Comment by jrudolph** [comment]
Is json4 marshaller support still in scope? If yes, where would it live?

**Comment by ktoso** [comment]
Hm, after the last huge discussion around JSON things I'm under the impression we do not want to add any more marshallers to the akka repo, and they're ok to live outside. Is there a strong reason to include json4s in the akka repo? // cc @rkuhn

**Comment by jrudolph** [comment]
As I have understood it it definitely shouldn't live in the akka repo. The question is who would create the spray port and if there's already place to put it.

**Comment by hepin1989** [comment]
I think how about thing like
https://github.com/guillaumebreton/play-json-support
and create a project akka-http-marshallers,I think the marshallers should split from the akka core.

**Comment by 2m** [comment]
There is https://github.com/hseeberger/akka-http-json which supports Play Json and Json4s.

**Comment by rkuhn** [comment]
So is this just a doc issue (pointing to external impl) then?

**Comment by ktoso** [comment]
Correct, which is kind of done: https://github.com/akka/akka.github.com/pull/205/files

**Comment by ktoso** [comment]
And we should probably close or merge this one https://github.com/akka/akka.github.com/pull/200
(In general they implement the same thing, AFAIR @guillaumebreton was ok with converging with @hseeberger impl).

**Comment by rkuhn** [comment]
Energize!

**Comment by filosganga** [comment]
Great idea to left Marshalling implementation live outside.

**Comment by hepin1989** [comment]
play-json,spray-json,maybe this been merge to akka-json?!

**Comment by ktoso** [comment]
> play-json,spray-json,maybe these been merge to akka-json?!
No, we do not want to keep these in the akka repository (causes all kinds of head aches, esp. since play uses akka, so we don't want akka to use play things). We're more than happy to link to external libs as seen here: http://akka.io/community/#extensions-to-akka-http

This ticket is just a docs ticket about explaining this nowadays I think (and should be renamed).

**Comment by jrudolph** [comment]
@ktoso how exactly would you like to have that documented? Should we just add a link from the marshaller / json marshaller documentation page to http://akka.io/community/#extensions-to-akka-http? It probably would make sense to have only one list of third-party modules, right?

**Comment by ktoso** [comment]
Yeah, I think we should show "these are built in, but hey there's tons more on the  http://akka.io/community/#extensions-to-akka-http page". Sounds good?

**Comment by jrudolph** [comment]
Yes, thanks for the confirmation.
