### ISSUE TITLE
Provide a "Performance Tuning" documentation section

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16817]
There are lots of knobs to turn to configure a common environment for high-performance networking e.g. on a Linux server. The spray community already collected lots of advice about how to do this. It could make sense to collect all of this information into a guide to get around the most common misconfigurations.

See the list of topics @RichardBradley already collected in spray/spray#917.

/cc @sirthias

**Comment by arubalcaba** [comment]
@jrudolph do you have a link to some of the resources for Performance Tuning?

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
