### ISSUE TITLE
Add reverse routing support

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16815]
See spray/spray#941 and the original post on the mailing list: https://groups.google.com/d/msg/spray-user/LoR5oorelCc/oNkMxQTsFWEJ

This would probably tie in with a future metadata effort where it becomes possible to extract details of the route structure at runtime.

/cc @sirthias

**Comment by reid-spencer** [comment]
:+1:

**Comment by reid-spencer** [comment]
When generating HTML href links from dynamically computed routes, this would be a very handy feature to have. Currently I use "convention" but I'd rather have akka-http give me the exact URL for a given scenario.

**Comment by marcuslange** [comment]
Yes please. This would be very helpful for hyper media support.

**Comment by rkuhn** [comment]
Another answer for this in the meantime is: “Use Play!”

**Comment by ktoso** [comment]
It's not something Akka HTTP is geared towards, if you want "website" use Play, we're "raw APIs".

**Comment by chris-zen** [comment]
Hi @ktoso , what about the use case @marcuslange was commenting for hyper media REST APIs ?
I understand the need to clean the backlog but the response was not very convincing to me :-P

**Comment by ktoso** [comment]
I'd be more than happy to review such contribution :smile:

**Comment by im-tollu** [comment]
Here are some design thoughts.
What we effectively need is some `UriTemplate[TupleN] ` based on some subset of [RFC6570](https://tools.ietf.org/html/rfc6570)
We then can use it to map templates to handlers:
`UriTemplateMapper[TupleN](UriTemplate[TupleN], HttpMethod, Handler[TupleN])`

In UriTemplateMapper implementation we can then generate appropriate PathMatcher and get Route, while UriTemplate can have method `UriTemplate.withParams(Params[TupleN]): RequestContext => Uri`.

After that we can make an RoutingBuilder, to which we would iteratively flatMap all UriTemplateMappers and foldLeft a combined Route.

These are just some initial thoughts, but I find it useful to share, so we could collectively figure out a descent design to this problem.

**Comment by flevour** [comment]
I'm total newbie, but I'm wondering about this as well. My use case would building a tool to cross-check consistency between our akka-http routes and our swagger documentation.

I was thinking to build a tool that would use reflection to build a route AST that could be used to generate the route structure.

Do you think there are other ways (besides reflection) to build the route structure?

**Comment by ghengeveld** [comment]
I'm implementing a REST API and would like to use reverse routing to send a `Location` header with a 201 Created response when a new resource is created. Reverse routing would make it trivial to know the correct location of the newly created resource (assuming there is a route to it).

Reverse routing clearly has a relevant use case for APIs, so I think it deserves to exist in Akka HTTP.

**Comment by anzecesar** [comment]
FWIW and for those who land here from a Google search, this was added at some point: https://doc.akka.io/docs/akka-http/10.0.10/scala/http/routing-dsl/directives/basic-directives/extractUri.html#extracturi

**Comment by Mahoney** [comment]
I'm sorry to see this closed; my use case is to have a seamless way to capture metrics for completed routes but by URI template rather than actual URI, on the assumption that it is interesting to know how `/user/<userid>/data/<dataid>` performs in general, rather than how `/user/1/data/1` and `/user/2/data/14` each perform in particular. I'd been hoping to use a method something like this:

```scala

def measure(method: HttpMethod, template: UriTemplate, status: StatusCode) = ???

def completeWithMetrics(m: ⇒ ToResponseMarshallable): Route = {
  (extractMethod & extractMatchedTemplate) { (method, template) ⇒
    mapResponse { response ⇒
      measure(method, template, response.status)
      response
    }(complete(m))
  }
}
```
