### ISSUE TITLE
Allow user access to the remote peer port through the Remote-Address header

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16818]
Currently, only the remote IP address will be reported.

See spray/spray#905

**Comment by sirthias** [comment]
Actually, we first need to close https://github.com/akka/akka/issues/16641, in whose fix we should probably also tackle this ticket here right away.

**Comment by rkuhn** [comment]
see also #16168

**Comment by jrudolph** [comment]
Fixed in #17658.
