### ISSUE TITLE
Http, client: Provide high-level support for response decompression

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16813]
See spray/spray#987

In spray, you could add a `decode(...)` clause to your pipeline to add support for a single decoder. As noted in the ticket it would make sense to provide also an automatic solution that tries all known decodes.

/cc @sirthias

**Comment by RichardBradley** [comment]
In case it helps anyone, I am using the following code which works around this issue by trying all known coders and decoders:

```
 /**
   * This method takes a route and wraps it to support request/response compression.
   */
  def handleCompression(route: Route): Route = {
    decompressRequest(Gzip, Deflate, NoCoding) {
      compressResponse(NoCoding, Gzip, Deflate) {
        route
      }
    }
  }
```

See also #16998

**Comment by 2beaucoup** [comment]
This ticket discussed generic *client side* response decompression so I think it's only remotely related to your referenced issue.

**Comment by RichardBradley** [comment]
Sorry, I misunderstood the issue here. There is a parallel problem for server-side handling of decompression of requests and compression of responses.

**Comment by 13h3r** [comment]
+1

**Comment by 13h3r** [comment]
I am start looking how can I implement this.
There are few questions I want to ask:
1. In which abstraction should we implement decoding? IMO we should make it like a Flow[Response, Response]. This flow should check headers and replace entity in response if needed.
2. At which level we should put this decoding? Sure we should not push this into Connection Level API. Sure we should make this available in Host Level API. What do you think about Request Level API? Should we push it into singleRequest for example?
3. For the first round I want just implement decoding without tests and submit this code for feedback. Is it ok?

**Comment by sirthias** [comment]
@13h3r I think it makes sense to approach this together with request encoding.
For example, you could extend the existing `akka.http.scaladsl.client.RequestBuilding` trait with something like

```scala
def encodeRequest(coder: Coder): RequestTransformer
```

Then you could add a `ResponseTransformation` trait (and object) containing something like

```scala
def decodeResponse: ResponseTransformer
```

Making the decoding logic available as a pipeline stage (i.e. `Flow[HttpResponse, HttpResponse]`), as you say, would probably also make sense.

**Comment by 2beaucoup** [comment]
@sirthias Speaking of `RequestBuilding`: Does it have a future? It's currently used in tests only and I wonder if another way of doing things (`RequestTransformer`/`ResponseTransformer` sound like stream abstractions) won't confuse users. What's the advantage compared to transforming/wrapping the `outgoingConnection` flow?

See also https://github.com/akka/akka/issues/18550#issuecomment-146793910

**Comment by sirthias** [comment]
Currently it's all we have. Eventually we will probably need to have something better (as discussed several times in the context of spray) but since this ticket is about one very specific feature I'd probably put it close to the existing `RequestBuilding` stuff at this point, so we don't open up a new area that will have to be moved to the shiny new client-side DSL world we'll have later... :)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
