### ISSUE TITLE
Try several IP addresses for one host if one fails

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16827]
From spray/spray#746:

> The easiest strategy would be to try all the available addresses in a round-robin fashion on failed connection attempts and probably make the strategy configurable.

See https://groups.google.com/d/msg/spray-user/d6XNRVfjGpo/Y3UURzz4mewJ

/cc @sirthias

**Comment by strobe** [comment]
Hi,
I will try to do this

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
