### ISSUE TITLE
Support partial parsing of cookie header

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16828]
From spray/spray#737:

> Following up on the discussion in #702 I propose to improve the header parser for Cookie headers in the following way:
  * parse all cookies in the header value independently
  * create a Cookie header holding all cookies that have been successfully parsed
  * create a RawHeader("Cookie", ...) holding the raw values of all invalid cookies

The rationale behind this request is to make it easy to access particular cookies even in the presence of other, malformed cookies (which e.g. often happens during testing on localhost).

/cc @sirthias

**Comment by huanwuji** [comment]
java.lang.IllegalArgumentException: requirement failed: ',' not allowed in cookie content ('Hm_lvt_abd6bec572d8b044e12f13b5f135a169=1434529279,1434607188; Hm_lpvt_abd6bec572d8b044e12f13b5f135a169=1434607188')

**Comment by jrudolph** [comment]
Here's a description of a recent security issue in netty (which affected Play) that shows that being lenient is maybe not the way to go:

https://engineering.linkedin.com/security/look-netty%E2%80%99s-recent-security-update-cve%C2%AD-2015%C2%AD-2156

The result was to tighten the parsing rules in netty (netty/netty#3748).

In this light (and with the discussions we already had in several proposals for spray and the internal one surrounding the security issue), I'd vote for not changing the behavior at all for now.

That is, at least, as long there's no sufficient evidence that one of the major and current browsers regularly sends broken cookies so that akka-http users would start to write hand-written parsers which could be a security issue in itself.

**Comment by huanwuji** [comment]
Thank you for your answer.
I'm already hand-written parsers by cookie and send email to software provider happen them correct it.

**Comment by jrudolph** [comment]
@rkuhn @sirthias @jroper would anyone object to closing this issue? It seemed the learning from the netty/play issue was that any custom or clever handling of cookies is prone to introduce ambiguities that open the door for hard-to-foresee security issues. So, I'd vote for keeping the strict behavior.

**Comment by jroper** [comment]
I'll have to look into it a bit further, but I think there may be issues with some third party cookies (eg, Google analytics). I can't remember when or where this came up, but it would be a show stopper if one bad Google analytics cookie prevented all cookies from being accepted.

**Comment by jrudolph** [comment]
I tested with Firefox and Chromium and it seems RFC 6265 is just ignored by browsers. That's also what [a popular stackoverflow answer](http://stackoverflow.com/a/1969339/7647) suggests.

Instead, they follow a very lenient form of [the old netscape spec](http://curl.haxx.se/rfc/cookie_spec.html). The rule seems to be this: any octet is allowed aside from `'\r'`, `'\n'`, and `';'` (and maybe other whitespacy control characters). No interpretation is done, especially no interpretation regarding quoting or escaping.

The RFC, instead, tries to streamline cookie syntax with the rest of HTTP by being stricter and giving DQUOTES a special status as if quoting was actually possible. At the same time it tries to shatter that illusion by preventing backslashes in the cookie value.

In a weird way, the old spec leaves less questions open than the RFC because it really treats the cookie value as the OPAQUE string (of allowed symbols) it should be. It is just strict enough to prevent ambiguities about which octets belongs to which cookie (or which header).

The important thing is that AFAICS both specs only define a set of symbols allowed in the cookie value but don't define any kind of interpretation like how to encode a string of ASCII characters, a string of bytes, or a string of unicode codepoints.

Where does that leave us?
 * Our encoding of cookie values as a Java `String` = string of UTF16 is treacherous as we can neither encode any character nor apply any decoding of the incoming octets to create unicode codepoints. I propose to change the type of the value to `ByteString` and check that only allowed octets are used.
 * We could accept the very lenient form of cookies unambiguously by just splitting on semicolons. We would also need to open up the header parser for more control characters if they should be supported as well (browser do support them, as well as bytes > 0x7F). This handling would be unambiguous not because of anything we do, but instead because browsers don't allow semicolons in cookie values as far as I tested and prevent cookie names to contain `'='`.
 * At the same time, we could be more strict about cookie values we create by checking that they obey the stricter rules of the RFC. We still need to define an escape hatch that allows the same set of symbols we allow in the parser to allow round-trips.
 * As cookies are usually opaque to the client we are free to provide some kind of encoding to support the common use cases like putting unicode strings or JSON data into cookies on a higher-level. In any case, we should make a clear separation between this processing and what HTTP provides on a lower level.

WDYT?

**Comment by jrudolph** [comment]
Alternatively, and more in line with the original purpose of this issue we could implement a "small solution": 
 * we don't change the model at all
 * instead we only allow a "reasonable set of octets", i.e. all ASCII characters from 0x20 to 0x7e without the semicolon and check the value to contain only characters in that range
 * let the parser
   * split pairs by semicolon
   * remove special handling of the quoting syntax defined in the RFC
   * for all cookies that use any excluded octets above (or use illegal octets in the cookie name), either (silently?) drop them or provide them as a special kind of opaque `ByteString` cookie
   * requests that contain a Cookie header that contains octets < 0x20 will still be completely rejected by the general HTTP header parsing logic

This could be a compromise that would increase the set of supported cookie values already somewhat without the need to make the core header parsing infrastructure more lenient.

**Comment by jrudolph** [comment]
I started with the small solution last week but it quickly became not-so-small any more. I'll have to try a bit more to see how to contain it.

**Comment by jrudolph** [comment]
I will solve this by introducing a new settings "cookie-parsing-mode" which can either be `rfc-6265` in which case strict rules apply, or `raw` in which case laxer rules apply. Cookie pairs that don't comply with the rules are always dropped. This should work for most applications as they will be able to access reasonably well-formed cookies and even some more. You won't get roundtrips for cookie headers that contain illegal (by the configured rule) cookie pairs but this is the trade-off we make by not introducing a model for illegal cookie pairs.

@sirthias I tried to implement this using a new rule like this which tries to parse and drop illegal cookie pairs as a fallback:

```scala
def `optional-cookie-pair`: Rule1[Option[HttpCookiePair]] = rule {
    `cookie-pair` ~> (Some(_: HttpCookiePair)) |
      zeroOrMore(CharPredicate.All -- ";\r\n" -- EOI) ~ push(None)
  }
```

However, it seems the parser never backtracks to try the alternative. Any idea why this would be the case? My parsing / parboiled2 experience seems a bit rusty by now.

Here's the error message including traces:

```
[info]   Illegal HTTP header 'Cookie': Invalid input ',', expected cookie-octet-rfc-6265, '\r', WSP, ';' or 'EOI' (line 1, column 8)
[info]   
[info]   5 rules mismatched at error location:
[info]     cookie / oneOrMore / optional-cookie-pair / cookie-pair / cookie-pair-rfc-6265 / cookie-value-rfc-6265 / | / capture / zeroOrMore / cookie-octet-rfc-6265
[info]     cookie / oneOrMore / optional-cookie-pair / cookie-pair / cookie-pair-rfc-6265 / cookie-value-rfc-6265 / OWS / optional / CRLF / '\r'
[info]     cookie / oneOrMore / optional-cookie-pair / cookie-pair / cookie-pair-rfc-6265 / cookie-value-rfc-6265 / OWS / oneOrMore / WSP
[info]     cookie / oneOrMore / ';'
[info]     cookie / 'EOI'
[info]   
[info]   z=0;a=1,b=2
[info]          ^
```

**Comment by sirthias** [comment]
I'll look into the backtracking problem.
Thanks for pushing this forward!

**Comment by jrudolph** [comment]
Any idea here?

**Comment by drewhk** [comment]
I like the switchable behavior, I guess it boils down to backtrack support now?

**Comment by jrudolph** [comment]
Yes, it's an implementation detail and backtracking should work AFAIK but I guess I forgot about some details of PEG-parsing that prevent from backtracking to kick in at this point.

**Comment by jrudolph** [comment]
Here are some of the changes I've made so far: https://github.com/spray/akka/commit/51f3dcabde235084ede9c94ef3d8caa2fd2a27e2

**Comment by sirthias** [comment]
Started looking into the backtracking issue...
Something looks fishy, so I'll update our internal copy of parboiled2 from version 2.0.0-RC2 which we had so far to the most recent 2.1.0 release first. This is a good idea anyway. I'm sure we'll make better progress after this is done (which should be by tomorrow).

**Comment by sirthias** [comment]
Found the source of the backtracking problem. Will comment in your branch, @jrudolph.

**Comment by ktoso** [comment]
Resolved in #18958 by @jrudolph, thanks a lot!

**Comment by ktoso** [comment]
Duh, validation passed before some changes got merged and now it's failed; I'll fix that (just simple renames we merged)

**Comment by jrudolph** [comment]
Thanks, Konrad.

**Comment by ktoso** [comment]
Wasn't this PRs fault actually, don't worry about it :) Fixed https://github.com/akka/akka/pull/18961
Let me know what you're up to next akka-http wise :-)
