### ISSUE TITLE
Ensure that UTF-8 filenames in multipart/formdata file uploads are unmarshalled properly

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16821]
See spray/spray#840

/cc @sirthias

**Comment by jrudolph** [comment]
This doesn't work yet. It seems header parsing doesn't support non-ASCII characters. We need to check the MIME and Http specs to decide how to proceed.

**Comment by jrudolph** [comment]
Here's a good overview over the involved specs:

http://stackoverflow.com/a/20592910/7647

Though, that doesn't say that browsers and/or servers would implement it the same way.

**Comment by 2beaucoup** [comment]
Some browsers simply derive the encoding of their form headers (without setting the charset in the reuqest headers) from the parent document if it isn't explicitly set. Therefore it's not always possible to correctly detect the encoding which we cannot necessarily expect to be UTF-8.

We should reuse the `defaultContentType` of the unmarshaller in such cases.

**Comment by jrudolph** [comment]
@2beaucoup  yes and I guess it's also not a given that a browser will apply the same behavior it applies to the actual content in the same way to the metadata... Do you know of any survey where you can check how servers behave in that regard?

**Comment by 2beaucoup** [comment]
> Do you know of any survey where you can check how servers behave in that regard?

@jrudolph No really. Being explicit (like [`setCharacterEncoding`](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#setCharacterEncoding(java.lang.String))) seems to be the only sane option in these cases.

**Comment by jrudolph** [comment]
Here's the [HTML 5](http://www.w3.org/TR/html5/forms.html#multipart-form-data) spec for multpart/form-data form submission.

**Comment by jrudolph** [comment]
So, it seems the browser is using some algorithm to figure out the charset and then 

> If the entry's name is "_charset_" and its type is "hidden", replace its value with charset.

Huh? So, the foolproof way of signalling the actual charset to the server is by adding a hidden form field with the name `_charset_` that will receive the charset used.

**Comment by 2beaucoup** [comment]
Although we can't rely on the presence of the `_charset_` field, interpreting it doesn't hurt.

Maybe we should simply add (or link to) some best practices re. multipart encodings?

**Comment by jrudolph** [comment]
Regardless of how we figure out the charset of a `multipart/form-data` request the `BodyPartParser` needs to able to parse it with any charset. Especially, it needs to be able to parse headers that are encoded with any encoding.

@sirthias how hard would it be to parse headers with non-ASCII encoding?

**Comment by jrudolph** [comment]
@2beaucoup this field could be anywhere in the form and we need a charset to decode it itself...

**Comment by 2beaucoup** [comment]
@jrudolph would be intersting to see if browser put this field first (online examples seem to indicate that but I didn't verify).

proposal: use the "default encoding" until finding a `_charset_` header and then switch to that on the fly.

**Comment by jrudolph** [comment]
I tested with firefox which just puts it wherever it is defined in the form.

**Comment by 2beaucoup** [comment]
Ouch. That's not very helpful from a streaming POV...

I guess we have to settle for the charset of the `Content-Type`header and fall back to the "default" charset.

**Comment by jrudolph** [comment]
There will be no charset provided in the `Content-Type`...

**Comment by 2beaucoup** [comment]
You a right, I mixed up request and response headers. Looks like this leads nowhere.

So we are back were we started: Be explicit in what you expect and make sure your pages are encoded the same way. `accept-charset`, `enctype="multipart/form-data;charset=..."` and `_accept_` are just unreliable hacks with inconsistent browser support.

**Comment by jrudolph** [comment]
I suggest we make the charset a parameter of the unmarshaller with the implicit instance one using UTF8.

This is currently blocked on #18121.

**Comment by drewhk** [comment]
+1
