### ISSUE TITLE
Support user-specified Server header to override configured value

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16820]
See spray/spray#857.

/cc @sirthias

**Comment by sirthias** [comment]
This issue has already been taken care of when we ported the initial response rendering code from spray. Here are the respective tests:
https://github.com/akka/akka/blob/298ea60fa15f8fd9bb20a06a9bd202e3a831659c/akka-http-core/src/test/scala/akka/http/engine/rendering/ResponseRendererSpec.scala#L307-L327
