### ISSUE TITLE
Provide documentation about how to configure TLS for the client and server side

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16829]
In spray we had only very sparse documentation about this topic and referred to the general SSL configuration of Java. It may make sense to provide proper documentation about this topic or at least provide working examples showing how to configure SSL in the most common situations.

 * configure server certificates
 * configure certain ciphers on the server and client side
 * add a custom CA certificate to the client side
 * disable certificate checking for testing purposes

/cc @sirthias 

Also see spray/spray#721.

**Comment by rkuhn** [comment]
see also https://www.playframework.com/documentation/2.4.0-M2/WsSSL for inspiration

**Comment by jrudolph** [comment]
Yes, this is a very good reference. Maybe it could even make sense to extract the TLS configuration code from Play WS and make it available for use with akka-http or other TLS applications.

**Comment by rkuhn** [comment]
Indeed, I’ll look into that.

**Comment by rkuhn** [comment]
we should make sure to have good docs over at https://github.com/typesafehub/ssl-config and point to those from the Akka docs

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
