### ISSUE TITLE
Add `max-requests-per-connection` config setting on the server side

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16837]
Similar to what Apache provides with its [`MaxKeepAliveRequests`](http://httpd.apache.org/docs/2.4/mod/core.html#maxkeepaliverequests) setting.

See spray/spray#320

/cc @sirthias

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
