### ISSUE TITLE
Security audit: slow HTTP DoS attacks

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16831]
E.g. with https://code.google.com/p/slowhttptest/

spray/spray#708

/cc @sirthias

**Comment by rkuhn** [comment]
maybe include in t:http:next?

**Comment by rkuhn** [comment]
This ticket can be removed from `t:http:next` once we have made sure that all timeouts and maximum concurrent request limits are otherwise in place. Then this ticket is about discussing further options for mitigating classes of DoS attacks.

**Comment by drewhk** [comment]
Proper timeout support is on the way, I hope I get it out this week.

**Comment by jrudolph** [comment]
Cool :)

**Comment by rkuhn** [comment]
are we there yet?

**Comment by ktoso** [comment]
Lifted the http:next here, I believe we have all limits in pace.
We should spend some time on specifically hardening and documenting more for this case though

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
