### ISSUE TITLE
Profile performance cost of directives and extractions

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16836]
See also spray/spray#342

Also see [this thread](https://groups.google.com/forum/#!topic/spray-user/CgC7ftxlBmM).

/cc @sirthias

**Comment by ktoso** [comment]
And document the patterns we discover here in https://github.com/akka/akka/issues/16817

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
