### ISSUE TITLE
Clarify status of `akka.http.client.parsing.uri-parsing-mode`

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16834]
since it is only used on the server-side.

Imported from spray/spray#555

/cc @sirthias

**Comment by rkuhn** [comment]
from discussion: this ticket may well be turned around in making the full power of URI parsing also available on the client side (e.g. for Location headers)

**Comment by rkuhn** [comment]
please elaborate

**Comment by jrudolph** [comment]
Fixed in #18120.
