### ISSUE TITLE
Automatic "cancellation" of rejections produced by failed alternatives in `|` chain

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16832]
François Vatel on spray-user https://groups.google.com/d/msg/spray-user/Y6OH-EmEviY/r9I-TPKbPwgJ

> Ideally - what we could assume - if 2 directives are combined with OR ( | ) and the 2nd of them passes (the 1st fails), there should not be any rejections from the 1st (failed) "authenticate" _inside_ this combined block (and so we should not cancel them manually). I think the problem here is that "authenticate" can raise any rejections, not only AuthenticationFailedRejection, so it is difficult to implement cancellation inside implementation of "|" (combined directive). The only way I see is to somehow remember which rejections (concrete instances) were raised inside a combined directive - if the whole construct passes, we could reset these rejections (do not pass further). But this may be a bit complicated.

Migrated from spray/spray#707.

/cc @sirthias

**Comment by rkuhn** [comment]
please elaborate

**Comment by jrudolph** [comment]
I don't think this is a valid ticket as it would change the consistency between the `|`-operator on directives and `~` on routes which both collect all rejections they encounter. This is something that some rejection handlers currently rely on (AuthenticationFailedRejection, UnsupportedRequestEncodingRejection).

As this was requested only once and since it should be possible to build an operator like this manually if needed I'm going to close this ticket for now. If someone disagrees please reopen or discuss.
