### ISSUE TITLE
Add `uploadedFile` directive/unmarshaller to handle file upload

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16841]
@stanpalatnik in spray/spray#252:

>  Create an `uploadedFile` directive that unmarshals the request entity and parses all information about any files posted. 

> Returns: 

> An array of uploaded file content represented as a `FormFile` similarly to how Play does it: http://www.playframework.com/documentation/2.0.2/JavaFileUpload

> As discussed here: https://groups.google.com/d/msg/spray-user/qjzHJMFmXoo/aMvLfAJvUpMJ

/cc @sirthias

**Comment by nykolaslima** [comment]
+1

**Comment by yanivby** [comment]
+1

**Comment by Mullefa** [comment]
+1

**Comment by ktoso** [comment]
// cc @johanandren could be this ticket.

**Comment by johanandren** [comment]
After a discussion with @ktoso the scope is a bit narrower than the initially proposed, signature will be like this ```def uploadedFile(destination: File): Directive1[Try[FormFile]]``` - accepting just one file rather than a list of files

**Comment by yanivby** [comment]
Thank you for your work on this, @johanandren.
Will this directive support uploading of large files, meaning, will the directive provide a stream of the uploaded content rather than holding all of it in memory?

**Comment by ktoso** [comment]
Of course :-) It boils down to: `entityBytes to Sink.file() run()`, so streaming right from the network into the file.

**Comment by 2beaucoup** [comment]
https://github.com/akka/akka/issues/17665#issuecomment-139176589 also contains some API suggestions

**Comment by ktoso** [comment]
Initial directives merged, thanks @johanandren!
Please give the new directives a ride in M2 soon and provide feedback  :)

**Comment by nykolaslima** [comment]
Awesome! Thanks @ktoso and @johanandren

**Comment by yanivby** [comment]
Great!
So I assume it can be streamed from the network into any target stream, not
just files on disk? For example, in my use case I would like to upload
files directly into MongoDB GridFS (using ReactiveMongo which provides
a play.api.libs.iteratee.Iteratee object to consume the stream).

On Mon, Nov 16, 2015 at 6:15 PM, Konrad Malawski <notifications@github.com>
wrote:

> Of course :-) It boils down to: entityBytes to Sink.file() run(), so
> streaming right from the network into the file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/16841#issuecomment-157084604>.
>



-- 
Thanks,
Yaniv

**Comment by 2beaucoup** [comment]
@yanivby Yes. Just use the `fileUpload` directive  (vs. the `uploadedFile` directive which works via temp files).
