### ISSUE TITLE
Add support for "Server-Sent Events"

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16843]
Originally requested as spray/spray#203

Client side ticket: #16783

/cc @sirthias

**Comment by viktorklang** [comment]
Perhaps relevant: https://github.com/hseeberger/akka-sse

**Comment by rkuhn** [comment]
This is solved by Heiko for now.

**Comment by Codier** [comment]
what is Heiko? How is this solved? Any examples?

**Comment by patriknw** [comment]
It's in Alpakka http://developer.lightbend.com/docs/alpakka/current/sse.html

**Comment by hseeberger** [comment]
Actually Alpakka just adds some convenience stuff on top of Akka SSE: https://github.com/hseeberger/akka-sse.

Akka SSE will merged into Akka HTTP soon, but currently it's a 3rd party library.

**Comment by Codier** [comment]
thanks a lot for the pointer
