### ISSUE TITLE
Add support for websockets

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16848]
**For technical discussion on the server side, see #16887
For technical discussion/progress for the client side implementation, see #17275**

I've got the honor to be the first one to request websocket support for akka-http. This would be a very useful addition and would fit well into the streaming nature of akka-http. 

In evaluating the importance of this request, please also consider the overwhelming support a similar request for the predecessor of akka-http, spray, has received in spray/spray#134 ;). In summary:

+1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1! +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 again and again +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1!! +1 +1 +1 +1! +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 -1 +100 :+1: :+1: :+1: :+1: :+1:

**Comment by twillouer** [comment]
:+1:

**Comment by reid-spencer** [comment]
:+1: :+1:  :+1: :+1:  :+1: 

@jrudoph - I think one of the things you should add to your "to do" list is to find a way to automatically transport all the +1 comments from a Spray issue to the corresponding akka-http issue. :P :)

**Comment by salanki** [comment]
:+1:  :+1:

**Comment by dimitrion** [comment]
:+1:

**Comment by t3hnar** [comment]
+1

**Comment by smlin** [comment]
+1

**Comment by hepin1989** [comment]
:+1:

**Comment by kardapoltsev** [comment]
+1

**Comment by analytically** [comment]
+1

**Comment by megothss** [comment]
+1

**Comment by dborovikov** [comment]
+1

**Comment by Tvaroh** [comment]
+1

**Comment by dnrusakov** [comment]
+1

**Comment by levkhomich** [comment]
+1

**Comment by viktorklang** [comment]
:+1:

**Comment by jrudolph** [comment]
I created #16887 to discuss technical details of the server side implementation so that we don't need to disrupt the much appreciated stream of incoming encouragement and support here.

**Comment by richdougherty** [comment]
:cake:

**Comment by TrustNoOne** [comment]
:+1:

**Comment by danellis** [comment]
+1

**Comment by ratulmukh** [comment]
+1

**Comment by borag** [comment]
+1

**Comment by weihsiu** [comment]
+1

**Comment by michaelHampel** [comment]
+1

**Comment by aloiscochard** [comment]
:+1:

**Comment by RamonBeast** [comment]
+1

**Comment by gantamk** [comment]
+1

**Comment by Solimen** [comment]
+1

**Comment by bfil** [comment]
+1

**Comment by zhijun** [comment]
+1

**Comment by SF-300** [comment]
+1

**Comment by chad** [comment]
:heart:

**Comment by duncan** [comment]
xoxoxo +1 +1 +1zillion!

**Comment by javierg1975** [comment]
+1

**Comment by dleclere** [comment]
+1

**Comment by rklaehn** [comment]
+1

**Comment by afiskon** [comment]
+1

**Comment by ezoerner** [comment]
+1

**Comment by malchmih** [comment]
:+1:

**Comment by erlangxk** [comment]
+1

**Comment by thoughtpoet** [comment]
+1

**Comment by Magua** [comment]
@patriknw In progress sweet, will you be pushing today? :laughing:


But seriously will you??? :laughing:

**Comment by jrudolph** [comment]
I'm at it and you will see results soon

**Comment by jlprat** [comment]
+1

**Comment by antoinecomte** [comment]
Awesome!

**Comment by pedrosnk** [comment]
+1

**Comment by dpsoft** [comment]
+1

**Comment by sap1ens** [comment]
+1

**Comment by nishanpatel** [comment]
Excellent :+1:

**Comment by juanjovazquez** [comment]
+1

**Comment by felixbr** [comment]
+1

**Comment by graph1zzlle** [comment]
+1 :)

**Comment by gonstr** [comment]
+1

**Comment by meln1k** [comment]
:+1:

**Comment by netoho** [comment]
+1

**Comment by TrustNoOne** [comment]
+1 (again lol), are we looking to a first release in the RC1?

**Comment by ScalaWilliamTG** [comment]
+1

**Comment by rkuhn** [comment]
Thanks for all the +1’s, people! Since we now (mostly) have WebSockets, we’ll track what is missing in separate tickets.
