### ISSUE TITLE
Add non-blocking DNS resolution

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16846]
From spray/spray#73:

> netty has already invested quite a bit of time/work into a proper solution,
> check out these two PRs:
> - https://github.com/netty/netty/pull/1354 which was later superceded by
> - https://github.com/netty/netty/pull/1622
> 
> @normanmaurer merged the latter one into [this branch](https://github.com/netty/netty/tree/dns) just three days ago.
> 
> I haven't looked at the code at all so far, but seeing the amount of discussion and review that the PRs have received I trust there is something interesting there.
> 
> Related tickets:
> - https://www.assembla.com/spaces/akka/tickets/2591 (akka)
> - https://github.com/playframework/playframework/issues/1997 (play)

/cc @sirthias

**Comment by viktorklang** [comment]
:+1:

**Comment by wsargent** [comment]
4.1.0.CR is out http://netty.io/news/2016/01/25/4-1-0-CR1.html so dns-resolver should be out with it real soon now: http://netty.io/4.1/api/io/netty/resolver/dns/package-summary.html

**Comment by TimMoore** [comment]
Can this be closed, now that the `async-dns` resolver is available in Akka 2.5.14 and later?

**Comment by patriknw** [comment]
indeed, thanks
