### ISSUE TITLE
Investigate how to implement local and global request-throttling in a stream setting

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16847]
See also spray/spray#11

/cc @sirthias

**Comment by ktoso** [comment]
I wonder if we could reuse some of the Play work on the commercial feature they have - the Rate Limiter.

// cc @patriknw

**Comment by patriknw** [comment]
maybe, sounds like `nice-to-have` at the moment

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
