### ISSUE TITLE
Add `reverseProxy` directive

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16844]
to enable simple proxying of single requests to an (internal) remote backend.

This has some security implications: What to do with cookies, authentication data, etc.? So, it may make sense to provide some safe-guards preventing people from simply relaying requests e.g. by requiring to whitelist potential targets in the configuration or something similar.

See the discussions in the original ticket spray/spray#145 and an existing PR spray/spray#764.

/cc @sirthias

**Comment by rkuhn** [comment]
TBH: it should be called `reverseProxy`.

**Comment by ktoso** [comment]
This should actually not take more than a few lines, contributions are welcome!

**Comment by TobiasPfeifer** [comment]
I'd like to help implementing this feature.
I experimented around a bit but I'm not sure if I'm on the right track. I think I need some guidance with this one.
Here is what I did so far (see comments for open questions): 6e06049f2f2dbbadc0763fda0103119b1f98fba4

**Comment by ktoso** [comment]
I added some comments, continue working on it and send in a PR and we'll discuss more then :)
Would indeed be a fun directive to have

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
