### ISSUE TITLE
Add support for an "authentication store" on the HTTP client side

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16854]
For requests to be automatically authenticated, an authentication store would be convenient. Especially, in combination with other high-level client side features like redirection it would be nice if those requests could be automatically authenticated if the server requests authentication and the store contains authentication data or an authenticator to use.

This is part of the bigger initiative to support a high-level HTTP client interface as tracked as #16856.

/cc @sirthias

**Comment by rkuhn** [comment]
Let’s check whether Play’s WS or AsyncHttpClient support this, I’m not sure whether we want our client to become a web browser.

**Comment by ktoso** [comment]
AFAICS Play's WS only has 

https://www.playframework.com/documentation/2.3.x/ScalaWS#Request-with-authentication 
`.withAuth(user, password, WSAuthScheme.BASIC)` (well, and OAuth)

but no facilities to store the auth data.

Could you confirm @jrudolph @wsargent? Thanks!

**Comment by wsargent** [comment]
This is correct.  Persistence is up to the end application

Sent from Outlook




On Tue, Oct 20, 2015 at 2:14 AM -0700, "Konrad Malawski" <notifications@github.com> wrote:












AFAICS Play's WS only has 



https://www.playframework.com/documentation/2.3.x/ScalaWS#Request-with-authentication 

.withAuth(user, password, WSAuthScheme.BASIC) (well, and OAuth)



but no facilities to store the auth data.



Could you confirm @jrudolph @wsargent? Thanks!

**Comment by ktoso** [comment]
Thanks, so we won't build it in either.

**Comment by ktoso** [comment]
Unless you see a strong need to keep it around as community contrib @jrudolph I'd like to close this one.
