### ISSUE TITLE
Add cookie store for the HTTP client side

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16855]
If configured, the store would automatically pick up cookies from responses and add them to requests. Also, it would make sure that the security rules about which cookies to apply in which situations would be applied.

This is part of the bigger initiative to support a high-level HTTP client interface as tracked as #16856.

/cc @sirthias

**Comment by ktoso** [comment]
Investigating if other libraries do this. This is starting to become pretty web-browser-ish.

**Comment by ktoso** [comment]
My research indicates WS does not do this => we probably shouldn't as well (at least not as a first thing to jump on unless people start demanding it furiously).

**Comment by robsonpeixoto** [comment]
@ktoso it's is very useful to write deep web(behind forms) crawlers.

**Comment by intracer** [comment]
As low as JDK does this https://docs.oracle.com/javase/7/docs/api/java/net/CookieManager.html
Some web API (such as Wikipedia - https://phabricator.wikimedia.org/T124252) require non-basic cookie handling

**Comment by cppexpert** [comment]
```
val newCookies = response.headers.filter(_.isInstanceOf[`Set-Cookie`]).map { v =>
  val cookie = v.asInstanceOf[SetCookie].cookie()
  HttpCookiePair.apply(cookie.name(), cookie.value())
}
val cookie = Cookie(newCookies)
```

Gentlemen, is there elegant way of constructing Cookie header out of Set-Cookie headers ? Currently I have to cast to java `SetCookie` in order to get raw value. Scala version returns rendered value with path from `value()`. Is there right way to do it ? I'm on 2.4.4

**Comment by ktoso** [comment]
Anywhere:

```scala
response.header[`Set-Cookie`]
```

Server: 


```scala
headerValue[`Set-Cookie`] { setCookie => 

}
```

**Comment by cppexpert** [comment]
Oh, it's not routing DSL. I'm making client call.

**Comment by ktoso** [comment]
That's why I've shown both examples :) see "anywhere"

**Comment by cppexpert** [comment]
I see. `response.header[`Set-Cookie`]` returns only first header though. It would be nice to have `response.headers[`Set-Cookie`]`

**Comment by ktoso** [comment]
Fun idea, I fear we can't just add it like that though because name already used, some helper might be a fun idea, please open a ticket.

For now it's: `val setCookies = response.headers.collect { case c: Set-Cookie => c }`

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by unoexperto** [comment]
@ktoso What new issue represents request to implement cookie store ? https://github.com/akka/akka-meta/issues/27 is not the one it seems. It's just general discussion.

**Comment by ktoso** [comment]
Each new ticket links back to the one that it superseeds.
That part we have automated, forward linking would take more time to implement so it's manual so only a generic message is there.

You can find out which issue it is by looking right above my comment on each issue:
![add_cookie_store_for_the_http_client_side_ _issue__16855_ _akka_akka](https://cloud.githubusercontent.com/assets/120979/18358573/f73bb438-75f5-11e6-9834-c71dd2bc7aad.png)
