### ISSUE TITLE
Write beginner friendly documentation for HTTP client

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16859]
Migrated from spray/spray#676 which contains several ideas about how to improve the existing (spray) documentation and what beginners would expect when starting with an HTTP client API.

/cc @sirthias

**Comment by sirthias** [comment]
Main point is probably:
- add examples and explain them
- add helpers on how to choose which client-side API level

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
