### ISSUE TITLE
Add support for HTTP proxy servers on the client side

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16853]
In spray, there's support for connecting to HTTP servers through an HTTP proxy (https://github.com/spray/spray/issues/102). This needs to be implemented for akka-http as well.

An important part of this is how to provide the configuration which requests to proxy and where to get the proxy configuration from. Spray allows configuration in the config file but also tries to pick up the well-known Java properties.

There's another ticket to enable proxying of https connections (#16153).

This is part of the bigger initiative to support a high-level HTTP client interface as tracked as #16856.

/cc @sirthias

**Comment by RichardBradley** [comment]
(+1 from me. This can be very helpful in development, as it lets you pass Akka HTTP traffic through debugging proxies like [Fiddler](http://www.telerik.com/fiddler) which is easier to play with than WireShark.)

**Comment by tjdett** [comment]
:+1:. I wondered why while porting my app from Spray to Akka-HTTP why my [Betamax](https://github.com/robfletcher/betamax) tests stopped working.

Respecting system properties `http.proxyHost` et al is rather important.

**Comment by rkuhn** [comment]
What’s the status here, if this was in Spray then it should be in http:next, no?

**Comment by jrudolph** [comment]
IIRC in February, we decided together to remove it from next.

**Comment by sirthias** [comment]
Also important to remember: spray only support non-encrypted client-side proxying, which is loosing importance quickly. So this ticket really should be tackled together with #16153.

**Comment by rkuhn** [comment]
Ah, right. Now we have all the needed context on this ticket :-)

**Comment by ktoso** [comment]
Another instance of need for it: :point_up: [January 5, 2016 1:28 PM](https://gitter.im/akka/akka?at=568bb6df5dd644c75b6dfd30)

Spray did have it so it's tricky to claim feature parity (for non-encrypted) hm...

**Comment by weda** [comment]
Hi,

We try to make corporate world interested with akka http, but it really resides behind the proxy server. Is there a chance that this functionality will be released  in next future .-)

**Comment by AlexGilleran** [comment]
Could the config for this be removed or at least the lack of the feature noted in the docs? (http://doc.akka.io/docs/akka/2.4.9/scala/http/configuration.html). Just spent a very confused half-hour trying to set up a proxy only to come to github and find it isn't implemented at all :(.

**Comment by ktoso** [comment]
Good point. Done.

Again, any help on getting this done is very welcome.

**Comment by nemccarthy** [comment]
+1 this is a real killer, we'd love to use it but without proxy support we are back to spary

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
