### ISSUE TITLE
Prebuilt Source with simple synchronous API

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16851]
Ticketified discussion from: https://groups.google.com/forum/#!searchin/akka-user/viktor$20externally$20source/akka-user/MiFVq_BF2Bc/g5poN4mgpqwJ

Turns out sometimes it is useful to have a source which can be "synchronously triggered" to signal certain things. Things to think of are how to react to "someone called emit()" but downstream can not consume (blow up / buffer / blow up, as adding a buffer element solves this) etc.

Note: this sounds similar to what exists in streams-testkit – ManualPublisher etc.

**Comment by rkuhn** [comment]
This has large overlap with #16520 .

**Comment by ktoso** [comment]
I spun something a while ago, API wise this issue is talking about:

```scala
final case class EmitterSource[Out]() extends KeyedActorFlowSource[Out, Emitter[Out]] {
  override def attach(flowSubscriber: Subscriber[Out], materializer: ActorFlowMaterializer, flowName: String) = {
    val (ref, emitter) = create(materializer, flowName)
    ref.subscribe(flowSubscriber)
    emitter
  }

  override def isActive: Boolean = true

  override def create(materializer: ActorFlowMaterializer, flowName: String) = {
    val impl = materializer.actorOf(Props[EmitterActor], s"$flowName-0-emitter")
    val emitter = new Emitter[Out](impl)

    ActorPublisher[Out](impl) -> emitter
  }
}

class Emitter[A](emitter: ActorRef) {
  def emit(a: A): Unit = emitter ! a
  def emit(a: A): Future[Unit] = emitter ? a // TODO fail the future if unable to emit
  def complete(): Unit = emitter ! EmitterActor.Complete // maybe boolean
  def fail(thr: Throwable): Unit = emitter ! EmitterActor.Fail(thr) // maybe boolean
}
```
