### ISSUE TITLE
section does not apply inputBuffer attributes

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16869]
Trying to make the akka-stream-scala Activator sample emit 1 prime per second instead of 2 per 2 seconds with the following ought to work but does not:
~~~scala
val slowConsumer = Flow[Int].section(OperationAttributes.inputBuffer(1, 1))(_.map(<output and sleep>)).to(BlackholeSink)
~~~
Incidentally, the tutorial should explain the timing and buffering aspects better because they can easily mystify or even flummox newbies (or tech leads for that matter ;-) ).

**Comment by drewhk** [comment]
Section attributes now map to submodule attributes in the ongoing rewrite, and I think this is no longer an issue.

**Comment by drewhk** [comment]
Fixed by: https://github.com/akka/akka/issues/16902
