### ISSUE TITLE
Add support for TLS ALPN

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16861]
[RFC 7301](http://tools.ietf.org/html/rfc7301)

This is a prerequisite to implement HTTP/2 (#16862) if it should be hosted on port 443 together with https fallback (which is recommended).

Ultimately, this needs support in the JDK. For now there's a [jetty initiative](https://github.com/jetty-project/jetty-alpn) to add ALPN to the existing implementation.

/cc @sirthias

**Comment by ktoso** [comment]
Jetty's docs on the ALPN lib: (as mentioned by Johannes, they copied and changed one of JDK's classes with changes, thus to use it it has to be first on the classpath): http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html

**Comment by ktoso** [comment]
HTTP2 is not on the near-term roadmap, moving to backlog (though I'd love to work on it).

**Comment by timcharper** [comment]
This project is using Jetty's ALPN:

https://github.com/http4s/blaze

Looks like there's a nice HPack module that Twitter released, too.

**Comment by ktoso** [comment]
Yup, we're aware of those :-) I read both and they look v. good.
Thanks for the info nevertheless.

**Comment by timcharper** [comment]
Wonderful! Feeling anxious to see this start materializing, and I'd like to help. I know there's lots of important things to do, though. I noticed a mentorship request was declined because you guys are too busy, and maybe my attempts at helping would be more harm than help because you already have a clear idea of how you want to see it implemented.

**Comment by ktoso** [comment]
Help certainly is very welcome! The mentorship you mention was a student project which while I think is great, sadly at that point in time was very scalaz and other libraries dependent so it would have been very hard to pull it into akka (we try to be as dependency free as possible).

I'll keep you updated once we have a battle plan. January is performance and Java 8 month :-)

**Comment by hepin1989** [comment]
https://github.com/trustin/jetty-alpn-agent

**Comment by ktoso** [comment]
This one I did not know, thanks @hepin1989! :-) Sadly enabling ALPN will continue to need such hacks :<

**Comment by hepin1989** [comment]
https://github.com/netty/netty/pull/3481 another link about this.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment)
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
