### ISSUE TITLE
Fold, Foreach, etc. should fail the exposed Future if the passed function throws

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#16866]
The following test fails with a timeout, but I think it should pass.
I am using akka-http-experimental 1.0-M3.

```
import akka.actor.ActorSystem
import akka.stream.ActorFlowMaterializer
import akka.stream.scaladsl.{Sink, Source}
import org.specs2.mutable.Specification
import scala.concurrent.Future

class ExceptionDuringFoldSpec
  extends Specification {

  private implicit val system = ActorSystem()
  private implicit val fm = ActorFlowMaterializer()

  "an exception during a Flow fold" should {
    "result in a failed Future containing the exception" in {

      val output: Future[List[Int]] = Source(List(1,2,3,4))
        .runWith(Sink.fold(List[Int]()) { (xs, x) =>

        if (x == 3) throw new Exception("test exception")

        xs :+ x
      })

      output must throwAn[Exception].like {
        case e => e.getMessage mustEqual "test exception"
      }.await()
    }
  }
}
```

**Comment by drewhk** [comment]
I confirm. It fails properly when an upstream element fails, but not if the folding function fails.

**Comment by drewhk** [comment]
Btw, this is not a problem for Map, Filter, etc. because they have a downstream to propagate to the error, but here fold is a Sink and the only thing to propagate to is the Promise. The following code:

        override def onPush(elem: T, ctx: Context[U]): Directive = {
          aggregator = f(aggregator, elem)
          ctx.pull()
        }

should be something like 

        override def onPush(elem: T, ctx: Context[U]): Directive = {
          try { 
             aggregator = f(aggregator, elem)
             ctx.pull()
          } catch { case e => promise.tryFailure(e); ctx.fail(e) } 
        }

**Comment by drewhk** [comment]
Same is probably ture for Foreach

**Comment by viktorklang** [comment]
@drewhk More like:

~~~scala
catch { case NonFatal(e) => promise.tryFailure(e); ctx.fail(e) }
~~~

**Comment by drewhk** [comment]
the "should be something like" meant to imply that :)
