### ISSUE TITLE
Add akka-http routing "guided tour"-style tutorial

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16860]
Migrated from spray/spray#698 which contains several very good ideas about how to present an entry tutorial for the routing DSL.

/cc @sirthias

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
