### ISSUE TITLE
document that HTTP route construction must not close over Actor state

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16871]
The pattern we show should be inspired by the Props recommendation: build the Route in a function within the companion object to make sure that nothing is pulled in accidentally, all captured values are explicit.

**Comment by ktoso** [comment]
If you're looking for work @johanandren this one would be nice to fix :)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
