### ISSUE TITLE
fix cancellation of substreams in MultiStreamOutputProcessor

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16870]
Currently when downstream cancels, this will just remove the substream from the processor and also (erroneously) call onComplete on it. This is problematic when sorting an incoming TCP connection into substreams (think HTTP and requests) because then the processor will just hang and not process the remaining elements that should have been delivered to this substream. What should happen instead is that the cancelation is propagated to the main upstream component.

OTOH it should be valid to take only the first five elements of a groupBy substream, but to make that work correctly (i.e. without canceling upstream) we would just provide a stage that turns cancellation into blackholing.

**Comment by drewhk** [comment]
I am not sure I understand this. Subclasses of this class take care of substream cancellation in their own specific ways. For example groupBy allows cancellation of substreams by simply ignoring those groups in the future. We have a test-case for that. What am I missing?

**Comment by rkuhn** [comment]
The missing part is that cancelation now serves two distinct purposes:

* “I am not interested in more data”
* “This stream is going DOWN”

The former is nice and easy, but by using cancelation to effect TCP stream shutdown we have introduced interesting cross talk of the latter kind. Cancelation works in the right way for all linear stages that do not produce substreams, it obviously works differently for broadcast (which I deem okay), so my point is that substream cancelation should always be propagated to the (linear) input because we have given it more semantic meaning than only “I am not interested in more data”.

**Comment by drewhk** [comment]
So what you recommend here is that the default should be that substream cancellation means cancelling the master input stream, and to have the substream cancellation (as in ignore) we create a special element that can be used attached to the substreams?

**Comment by rkuhn** [comment]
Yes, that is what I'm saying — I could of course be wrong or missing something.

**Comment by drewhk** [comment]
That would work, except that Stages now does not really support absorbing downstream termination, I need to think about that.

**Comment by rkuhn** [comment]
Discussion result: groupBy and friends should have a configuration flag that sets up the cancellation-blackhole-processor so that we don’t have to expose that (dangerous) element to the general public.

**Comment by rkuhn** [comment]
This ticket is invalid: we’ll solve this by Sink concatenation and AsyncStage.
