### ISSUE TITLE
Streams: the "only fanout" publisher which can not be canceled "by downstream" 

### ISSUE THREAD

**Issue by oseval** [akka/akka#16873]
I have a custom publisher which produce events from JMS MQ. I need to connect the user sessions to it when session is created (session is subscriber). When the application is started i creates my custom publisher and appends the FanoutPublisherSink to it.
1) First user session start the flow and all works fine. But if there are no any user online then all downstreams will be canceled and fanout also stopped. As workaround I was created dummy subscriber which connects to fanout on the application start and never will be canceled. But it is ugly. It possible that I missed anything but I can not find any other solution for this.

So I think it will be helpful if the fanout publishers could be stay alive when all downstreams canceled.

2) After the user session is connected to the fanout then it will receive events from the fanout buffer. But these events was targeted to the other users by definition (by application logic user can not to receive an event before session is created and connected). Of course these events will be filtered, but it strange behaviour.

Second part is not critical for me, but seems to be a some kind of logic inconsistency. And to fix it I need have the `FanoutPublisherSink[Out](0, 0)` or simple `UnbufferedFanoutPublisherSink`.

**Comment by drewhk** [comment]
This was planned at some point, but I don't remember if there is a ticket. Yes, this is a useful element for so many things (Imagine a logging source, where you can just attach and detach sinks dynamically). I am not sure a FanoutPublisher is the best answer here since that exposes RS API, probably we can make a high-level API feature out of this.

**Comment by blawlor** [comment]
I'd like to see this kind of 'always on' publisher too. The problem with the dummy subscriber to keep the fanout publisher from being cancelled is that it should generate zero demand when there are no other subscribers, but then generate demand at some rate between the lowest and highest of the other subscribers - and that's a lot of code for a dummy.

**Comment by agolubev** [comment]
I'm taking this one

**Comment by ktoso** [comment]
Thanks!

**Comment by agolubev** [comment]
OK, so the approach will be to create Sink.asNonCancellablePublisher (along with existing asPublisher). It will be a graph stage. Graph stage logic will extends SubscriberManagement as it has big portion of spreading elements through list of subscribers.
Perhaps at the end we can remove FanoutPublisherSink, PublisherSink, maybe VirtualPublisher

**Comment by agolubev** [comment]
Any feedback is welcome.

**Comment by agolubev** [comment]
This ticket must be closed per discussion in PR #20422

**Comment by ktoso** [comment]
Okey, thanks for hacking on that PR and sorry that one did not make it in!
