### ISSUE TITLE
docs.akka.io doesn't resolve any more

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16883]
Because the documentation has been moved to http://akka.io/docs. Still it would have make sense to point the old DNS entry to anything (e.g. permanent redirect to the new address).

**Comment by drewhk** [comment]
didn't you mean doc.akka.io? Since that works perfectly.

**Comment by jrudolph** [comment]
Yes, you are right. Strange, I thought this came from my browser history and worked before but I guess it was just a user-error. Sorry for the hiccup.
