### ISSUE TITLE
splitAfter combinator

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16885]
For Websockets (#16887), a `splitAfter` combinator would be useful. The difference to `splitWhen`:

 * `splitWhen` **begins** a new substream when the predicate is true (each substream looks like this wrt the predicate: `true`, `false`, `false`, `false`, ...)
 * `splitAfter` **ends** the current substream when the predicate is true (each substream looks like this wrt the predicate: `false`, `true`, `true`, ...)

Is it possible to emulate the wanted behavior with the existing combinators? I thought we once discussed a generalized split combinator but I cannot find any reference any more.

#### Background for Websockets

In websockets, on the low level the incoming data is a stream of data frames that look like this:

```scala
case class DataFrame(data: ByteString, fin: Boolean)
```

where a stream of `DataFrame`s needs to be transformed into a stream of `Message`s that look like this:

```scala
case class Message(data: Source[ByteString])
```

with the combinator the implementation would look like this:

```scala
def assemble(frames: Source[Frame]): Source[Message] =
  frames
    .splitAfter(_.fin)
    .map(frames: Source[Frame] => Message(frames.map(_.data)))
```

**Comment by drewhk** [comment]
I don't think you can conveniently emulate it, but it should not be hard to add this extra op.

**Comment by ktoso** [comment]
Slipping into RC2, seems there is yet another semantic diff between impls that surfaces in http tests.
