### ISSUE TITLE
change failure detector defaults to be more lenient

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16889]
The user should have to tighten them to make the system respond more quickly instead of  having to loosen them up for common deployment conditions.

**Comment by patriknw** [comment]
I think this is mostly, perhaps only, for the remoting failure detectors.

**Comment by patriknw** [comment]
We should also increase the default for the system message buffer.

**Comment by drewhk** [comment]
No, remoting failure detector time is fine:       

    acceptable-heartbeat-pause = 20 s

We changed that a while ago, and we also switched for a simple deadline based FD instead of the accrual.

**Comment by patriknw** [comment]
what we have seen lately is overflow of system message buffer, perhaps this ticket should cover that and be renamed

**Comment by drewhk** [comment]
Yes, I mentioned that in the related ticket: https://github.com/akka/akka/issues/16888

**Comment by patriknw** [comment]
good, then I think we can close this ticket and fix what is needed in the other one

**Comment by patriknw** [comment]
done, I think
