### ISSUE TITLE
FAILED: TheArithmeticServiceShouldSurviveIllegalExpressions

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16881]
Failed tests:   TheArithmeticServiceShouldSurviveIllegalExpressions(supervision.ArithmeticServiceTest): assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.Status$Failure

https://jenkins.akka.io:8498/job/akka-nightly/1983/console

Though probably just a normal timeout due to our recently slowish jenkins machines?

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
