### ISSUE TITLE
Websockets Server side API and implementation discussion

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16887]
**To signal your approval or support for websockets please go to #16848, this ticket is reserved for technical discussion.**

Specs: http://tools.ietf.org/html/rfc6455
Chapter from "High Performance Browser Networking": http://chimera.labs.oreilly.com/books/1230000000545/ch17.html

/cc @sirthias

**Comment by jrudolph** [comment]
First server-side API design preview at #16891.

**Comment by sirthias** [comment]
I'd say the first goal should be to come up with a complete basic implementation (without implemented extensions) that passes the Autobahn testsuite: http://autobahn.ws/testsuite/

**Comment by sirthias** [comment]
Also interesting: Netty's implementation here: https://github.com/netty/netty/tree/master/codec-http/src/main/java/io/netty/handler/codec/http/websocketx

**Comment by sirthias** [comment]
Maybe the single most important extensions that might be in scope once we have the basic implementation done:
Compression: https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-19

**Comment by jrudolph** [comment]
Here's a diagram of how the server pipeline would look like with Websocket included:

![server-pipeline-with-websocket dot](https://cloud.githubusercontent.com/assets/9868/6318150/617226a2-ba81-11e4-9b33-b0f98c7483ec.png)

Color code:
 - blue: HTTP
 - red: Websocket
 - green: user-supplied

**Comment by dnrusakov** [comment]
Also interesting: https://github.com/wandoulabs/spray-websocket
Pass all Autobahn test cases (both ws and wss)

**Comment by drewhk** [comment]
Looking at the graph picture you posted, we need to make a little tool that extracts a StreamLayout in a format that graphviz can use it. It would be very useful to have automated architecture docs, also possibly be able to link from the graph elements to the scaladoc or the code itself (just like scaladoc inheritance diagrams).

**Comment by drewhk** [comment]
@jrudolph with github.com/akka/akka/pull/17300 merged I can close this?

**Comment by jrudolph** [comment]
Yep.

**Comment by jrudolph** [comment]
Merged in #17300 and released with RC1.
