### ISSUE TITLE
Enable configuration of TCP closing modes

### ISSUE THREAD

**Issue by sirthias** [akka/akka#16899]
Currently closing the outgoing side of a TCP stream triggers a "confirmed close" underneath, i.e. calling `shutdownOutput` (sending of a FIN) and then waiting for the FIN from the peer on the incoming side.

While this is often a good way to close it is not the only way and we should enable users to configure two other close modes, specifically:
- an "abort" (setting SO_LINGER to 0 before calling `close`)
- an "normal" close (not setting SO_LINGER before calling `close`)

One application of this is handling early HTTP responses on the server side, where we cannot rely on the usual confirmed closing, since the client is still trying to send us heaps of data which we do not want to read (#16898).

Since the streams abstraction does not allow qualified closing (we only have the single "complete" signal) we need another (side-)channel for configuring the close mode.
I'd suggest giving the connection APIs (on the incoming and outgoing side) another method `setCloseMode(...)` which allows one to set the close mode for this connection *at any time*, i.e. also after the connection is already live (e.g. by setting an `AtomicInteger` underneath). The default setting for a connection should be the one configured when the connection is requested (outgoing) or when the server is bound (incoming). Both of these settings should themselves be configurable via the application config.

**Comment by drewhk** [comment]
This is a very good idea and an important ticket. Abort is accessible, as an onError triggers an Abort, but "normal" close is not. In fact this is a DoS vector currently.

**Comment by sirthias** [comment]
Even if `onError` currently triggers abort this does not mean that we shouldn't still provide a proper "abort" close mode that can be configured alongside the other modes.
The reason is that (as we have already discussed at length somewhere else) `onError` is not properly usable as a channel for application data, as it can leapfrog regular stream elements.
There are cases where I might want to abort-close without the risk of loosing data elements (even though a TCP reset might cause just that in the TCP level but that is a different question).

**Comment by rkuhn** [comment]
ping @bantonsson ?

**Comment by bantonsson** [comment]
Yes, it's on my list still.

**Comment by rkuhn** [comment]
Ah, the question was mostly whether you have already started working on it or whether someone else shall pick it up.

**Comment by bantonsson** [comment]
Yes, started a bit. I'll finish this.

**Comment by rkuhn** [comment]
Thanks!

**Comment by bantonsson** [comment]
I pushed the current state of the close mode. The dependencies between the pumps and the TCP messages where a bit more complicated than I had hoped. I'll need to put this ticket back for now. This is the current state:

* Anything but CloseMode.Confirmed breaks TcpStreamSpec
* Two of the shutdown cases needs CloseMode.Confirmed, but the echo tests break in strange ways

**Comment by drewhk** [comment]
Echo test cannot work without half-close, that should be ignored for full-close modes. And the spec has lots of tests that only make sense in half-close mode.

**Comment by drewhk** [comment]
Currently I added support for static configuration only, and only choices are full-close and half-close. This is enough to be more safe on the server side, we can add the more dynamic feature in 1.x

**Comment by drewhk** [comment]
New ticket for the dynamic version: https://github.com/akka/akka/issues/17788
