### ISSUE TITLE
javadsl.japi?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16908]
Reminder about the variance issue with akka.japi, and the javadsl.japi copy. Do we want to release 1.0 with javadsl.japi?

**Comment by patriknw** [comment]
@ktoso do you know if there is something left to do here?

**Comment by ktoso** [comment]
Skimmed Java related tickets and code we have in `japi` – I think we're good here.

// thought https://github.com/akka/akka/issues/18181 might have been related but it's not.
