### ISSUE TITLE
Speed up final removal of nodes leaving the cluster (happy case)

### ISSUE THREAD

**Issue by michael---s** [akka/akka#16903]
When a node explicitly leaves the cluster it lasts very long until the rest gets the MemberRemoved event depending on the failure detection configuration.

For example with acceptable-heartbeat-pause=30 s final removal lasts 35 seconds.
If also changing min-std-deviation=10s final removal lasts 96 seconds.

Please see also discussion and documentation [in the Akka User List](https://groups.google.com/d/msg/akka-user/Tta7TbSxsVk/AW0hy6PMH10J).

[Patrik Nordwall said there](https://groups.google.com/d/msg/akka-user/Tta7TbSxsVk/DQNv5lD7Z9YJ):
>It is correct that the final removal is performed when it is verified that the leaving node has been shutdown, and this is done with the ordinary failure detector.
>It might be possible to speed up this, at least for the happy case.

**Comment by patriknw** [comment]
thanks

**Comment by patriknw** [comment]
This should be improved by #21537. The leaving node is sending a direct message to next potential leader(s) when it's shutting down. The leader can then based on this acknowledgment remove the member without waiting for failure detector.
