### ISSUE TITLE
Run tests for java8 projects before releasing

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16906]
pr validation of java8 projects has been disabled. Run the following manually.

**akka-http-java8-tests-experimental**

    sbt
    akka > project akka-http-java8-tests-experimental
    akka-http-java8-tests-experimental > test

Verify that it actually runs the tests, e.g. "Test run finished: 0 failed, 0 ignored, 6 total, 1.126s"

On osx it is supposed to find java8 home automatically. Otherwise you have to set the environment variable AKKA_BUILD_JAVA8_HOME

**akka-docs-java-lambda**

    sbt publishM2
    cd akka-samples/akka-docs-java-lambda/
    mvn clean test

**Comment by rkuhn** [comment]
okay, done
