### ISSUE TITLE
FAILED: StreamTcpSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16912]
Failed once on local run

    [info] - must work when remote closes write, then client closes write
    [WARN] [02/19/2015 19:15:38.871] [StreamTcpSpec-akka.actor.default-dispatcher-4] [akka://StreamTcpSpec/system/IO-TCP-STREAM/client-5-%2F127.0.0.1%3A49521] received dead letter from Actor[akka://StreamTcpSpec/system/IO-TCP/selectors/$a/13#29142708]: Closed
    [WARN] [02/19/2015 19:15:38.871] [StreamTcpSpec-akka.actor.default-dispatcher-4] [akka://StreamTcpSpec/system/IO-TCP/selectors/$a/13] received dead system message: DeathWatchNotification(Actor[akka://StreamTcpSpec/system/IO-TCP-STREAM/client-5-%2F127.0.0.1%3A49521#1490572050],true,false)
    [WARN] [02/19/2015 19:15:38.918] [StreamTcpSpec-akka.actor.default-dispatcher-5] [akka://StreamTcpSpec/system/IO-TCP-STREAM/client-6-%2F127.0.0.1%3A49523] received dead letter from Actor[akka://StreamTcpSpec/system/IO-TCP/selectors/$a/16#261394652]: Closed
    [WARN] [02/19/2015 19:15:38.918] [StreamTcpSpec-akka.actor.default-dispatcher-5] [akka://StreamTcpSpec/system/IO-TCP/selectors/$a/16] received dead letter from Actor[akka://StreamTcpSpec/system/IO-TCP-STREAM/client-6-%2F127.0.0.1%3A49523#-560647325]: Terminated(Actor[akka://StreamTcpSpec/system/IO-TCP-STREAM/client-6-%2F127.0.0.1%3A49523#-560647325])
    [WARN] [02/19/2015 19:15:38.919] [StreamTcpSpec-akka.actor.default-dispatcher-5] [akka://StreamTcpSpec/deadLetters] received dead letter from Actor[akka://StreamTcpSpec/user/$g/$a#1647028449]: ErrorClosed(Broken pipe)
    [WARN] [02/19/2015 19:15:38.919] [StreamTcpSpec-akka.actor.default-dispatcher-5] [akka://StreamTcpSpec/user/$g/$a] received dead letter from Actor[akka://StreamTcpSpec/deadLetters]: PingClose(Actor[akka://StreamTcpSpec/system/testActor749#136815273])
    [info] - must work when client closes read, then client closes write *** FAILED ***
    [info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during fishForMessage, hint:
    [info]   at scala.Predef$.assert(Predef.scala:179)
    [info]   at akka.testkit.TestKitBase$class.recv$1(TestKit.scala:386)
    [info]   at akka.testkit.TestKitBase$class.fishForMessage(TestKit.scala:390)
    [info]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:718)
    [info]   at akka.stream.io.TcpHelper$ServerConnection.expectClosed(TcpHelper.scala:146)
    [info]   at akka.stream.io.StreamTcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply$mcV$sp(StreamTcpSpec.scala:160)
    [info]   at akka.stream.io.StreamTcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(StreamTcpSpec.scala:133)
    [info]   at akka.stream.io.StreamTcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(StreamTcpSpec.scala:133)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)

**Comment by drewhk** [comment]
This is being fixed in #16902
