### ISSUE TITLE
add stream supervision for ZipWith

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16915]
(and other junctions)

**Comment by rajish** [comment]
+1 Please implement it! <CEOmode> How hard could it be? Is it rocket science?</CEOmode> :wink:

**Comment by drewhk** [comment]
It can be rocket science, yes ;)

**Comment by rkuhn** [comment]
As the official team rocket scientist I can confidently say that this is probably as hard as rocket science :-)

But we’ll do supervision differently anyway: #19950
