### ISSUE TITLE
add stream supervision for Sinks and Sources

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16916]
e.g. iterator source and fold sink

**Comment by patriknw** [comment]
think about ActorPublisher and ActorSubscriber also

**Comment by patriknw** [comment]
remember that the supervision should also influence if the promise of `fold` and `foreach` is to be completed with the failure

**Comment by cppexpert** [comment]
Just found this bug. Looks like it covers what I reported on SO: http://stackoverflow.com/q/32290285/226895

**Comment by hepin1989** [comment]
I encounter this problem when using reactive-kafka 0.7.0,so If this is added,then should be nice for further use case.

**Comment by patriknw** [comment]
There is a fat warning in the docs: "Warning
ZipWith, FlexiMerge, FlexiRoute junction, ActorPublisher source and ActorSubscriber sink components do not honour the supervision strategy attribute yet."

**Comment by cppexpert** [comment]
Perhaps it's not fat enough. I didn't see it in actor integration page of documentation and wasted significant amount of time debugging this.

**Comment by patriknw** [comment]
ok, should be mentioned in that page also (@2m could you fix that ?)

**Comment by patriknw** [comment]
ActorPublisher and ActorSubscriber actually supports ordinary ordinary parental actor supervision without loosing the internal stream state.

**Comment by cppexpert** [comment]
@patriknw Could you please demonstrate how I can "resume" the stream that is generated by `ActorPublisher` ? I'm getting very long list of XML items. Some items I can't parse but I'd like to continue instead of stopping paginated REST API replies.

**Comment by patriknw** [comment]
I'm not sure I understand. You get the XML as an external message to the ActorPublisher and when you handle that message an exception is thrown. That should by default restart the actor and, but not stop the stream.

**Comment by hepin1989** [comment]
ok,recheck the title,seems the fat warning should always be fat there :).

**Comment by hepin1989** [comment]
@patriknw I encounter the problem is that once the protobuf message is corrupted,the subscriber will failed.but that bytes just was dirty data.A better way I think should do a map before it.but the reactive-kafka don;t have that.

**Comment by ktoso** [comment]
Heard more demand for it recently, from @kciesielski

**Comment by kciesielski** [comment]
+1 I'm working on [Reactive Kafka](https://github.com/softwaremill/reactive-kafka). Kafka's API is  synchronous, so an `ActorPublisher` pulls elements (in a blocking manner) from the queue. When there are errors, it would be great to be able to allow users to react to them in some way in their custom supervision strategy, plugged in with some nice DSL.

**Comment by rkuhn** [comment]
superseded by different approach: #19950
