### ISSUE TITLE
Investigate commented out test case in FlowSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16924]

**Comment by bantonsson** [comment]
What are we talking about here? The FIXME comment that is as old as the file itself (12:th Sep 2014)? I can't see anything else that is commented out.

**Comment by drewhk** [comment]
that is the part, yes, and it is old, yes :)

**Comment by drewhk** [comment]
"We get a processor actor terminated abruptly" failure to the 3rd subscriber. It should be "processor actor shut-down" at that point.
