### ISSUE TITLE
expose redeliveryBurstLimit for local override

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16928]
The AtLeastOnceDelivery trait makes the interval and max outstanding settings locally overridable, and the burst limit is missing

**Comment by patriknw** [comment]
@rkuhn `def redeliveryBurstLimit: Int` is defined in `AtLeastOnceDelivery`. Could it be that you looked at release-2.3 and not master? This is a new feature.

**Comment by rkuhn** [comment]
You’re right, I must have mixed up branches, sorry for the noise.
