### ISSUE TITLE
DistributedPubSub vs ClusterClient

### ISSUE THREAD

**Issue by behrad** [akka/akka#16922]
They both seem the simplest way to achieve location transparency in a clustered middleware in Akka, however I have some questions that couldn't be answered by documentation.

in a peer2peer (path based) req/res (`sender() ! "ACK"`) scenario this is enough (no need for Subscribing to a topic) 

1. DistributedPubSub

```scala
// in an actor with path /user/service
val mediator = DistributedPubSubExtension(context.system).mediator
```

```scala
val mediator = DistributedPubSubExtension( context.system ).mediator
mediator ! Send( "/user/service", "Serve ME", localAffinity = false )
```

2. ClusterClient

```scala
ClusterReceptionistExtension(context.system).registerService(self)
```

```scala
val initialContacts = Set( context.system.actorSelection( context.system / "receptionist" ) )
val c = context.system.actorOf(ClusterClient.props(initialContacts))
c ! ClusterClient.Send( "/user/service", "Serve ME", localAffinity = true )
```

now, considering all nodes are in the same cluster always

1) whats the difference between the two? What more you gain with ClusterClient sample? Why should I prefer the second over the first, inside a cluster?

2) initialContacts is enough to be only self node address to contact all other nodes inside the same cluster?

3) When reading about stashing messages in ClusterClient I first thought it could be "DistributedPubSub" + "AtleastOnceDelivery" in a way... but when I started my service actor system with delay, it didn't get sent messages from client. What am I miss understanding about?

**Comment by patriknw** [comment]
ClusterClient provides similar features as DistributedPubSub, but ClusterClient is only intended to be used from actor systems that are not part of the cluster, or from nodes that are part of another cluster.

When all nodes are part of the same cluster you should use DistributedPubSub (1).

I'll keep this issue open as a reminder that this should be made more clear in the documentation.

**Comment by behrad** [comment]
thank you @patriknw 
Is there any constraints or timing limitations in calling  above first snippet (DistributedPubSub) to work?

In a different project my node A was unable to Send to node B.

1) Should I call `val mediator = DistributedPubSubExtension(context.system).mediator` on each actor? once in boot class? on node up?
2) Which actors will `val mediator = DistributedPubSubExtension(context.system).mediator` expose as destinations for other nodes `Send` to be successful!?

**Comment by patriknw** [comment]
Registered actors are eventually spread to other nodes, i.e. will take a while until they are known in all places. 

This type of question would be better asked at akka-user so that others can learn from it.

**Comment by patriknw** [comment]
@behrad thanks for closing, but I would actually like to keep this issue open as a reminder that this should be made more clear in the documentation.

**Comment by behrad** [comment]
:+1:

**Comment by hepin1989** [comment]
@behrad in fact I think you could using https://github.com/patriknw/akka-data-replication to develop a ```ClusterEventStream``` or ```ClusterServiceRegistry```,both is more easy to use than the ```ClusterClient  ```and the ```DistributedPubSub```.have to say,akka-data-replication is really great.

**Comment by behrad** [comment]
haven't heart of that... great module thank you for mentioning @hepin1989 
actually I'm using `DistributedPubSub` for location-transparent communication between my nodes, but a light lid up for me on my `DistributedIdempotentRepository` :bulb:

**Comment by hepin1989** [comment]
we are using it like this
```
trait ServiceRegistry {
  def registryLocally(service: Service): Future[Service]

  def registerAsync(service: Service, timeout: FiniteDuration): Future[Service]

  def registerAsync(service: Service, timeout: Long, timeUnit: TimeUnit): Future[Service] = {
    registerAsync(service, FiniteDuration(timeout, timeUnit))
  }

  def lookupLocally(name: String): Future[Set[Service]]

  def lookupAsync(name: String, timeout: FiniteDuration): Future[Set[Service]]

  def lookupAsync(name: String, timeout: Long, timeUnit: TimeUnit): Future[Set[Service]] = {
    lookupAsync(name, FiniteDuration(timeout, timeUnit))
  }

  def unregisterLocally(service: Service): Future[Service]
}
```
and
```
abstract class ClusterEventStream extends ActorEventBus {
  override type Classifier = String

  override type Event = ClusterEventStreamMessage

  def publish(to: Classifier, message: AnyRef)

  def send(event: Event)

  def send(to: Classifier, message: AnyRef)

  def send(event: Event, as: ActorRef)

  def send(to: Classifier, message: AnyRef, as: ActorRef)

  def sendWithReply(event: Event, timeout: FiniteDuration): Future[Any]

  def sendWithReply(to: Classifier, message: AnyRef, timeout: FiniteDuration): Future[Any]

  def subscribe(subscriber: Subscriber, to: Classifier, timeout: FiniteDuration)

  def subscribeAsync(subscriber: Subscriber, to: Classifier, timeout: FiniteDuration): Future[Boolean]

  def unsubscribe(subscriber: Subscriber, from: Classifier, timeout: FiniteDuration): Boolean

  def unsubscribeAsync(subscriber: Subscriber, from: Classifier, timeout: FiniteDuration): Future[Boolean]
}
```
I think that's OK,maybe the signature not nice,but it works fine.

**Comment by behrad** [comment]
any snippet of your implementation? whats `Service`? in it's most simple scenario I should replicate a `name` associated with it's `actorPath` hmm?

**Comment by hepin1989** [comment]
```
  sealed trait Service {
    def endPoint: ActorRef

    def name: String

    def version: Version

    def description: String
  }
```

**Comment by behrad** [comment]
thank you @hepin1989

**Comment by patriknw** [comment]
Added the doc note in https://github.com/akka/akka/pull/17869
