### ISSUE TITLE
Respect Content-Transfer-Encoding in BodyPartParser

### ISSUE THREAD

**Issue by kswmsw** [akka/akka#16921]
`akka.http.engine.parsing.BodyPartParser` in akka-http-core-experimental 1.0-M3 ignores the `Content-Transfer-Encoding` header when parsing the entity. This means that currently if a client uploads a body part with `Content-Transfer-Encoding quoted-printable` or `base64`, the wrong data is passed to the application with no error or warning.

Instead, Akka should respect this header, and use its value to decode the bytes of the incoming stream when constructing the bytes of the body part. The `dataBytes` of the parsed body part should be the decoded bytes of the body part, not the raw bytes of the multipart entity.

The relevant standards are [RFC2046 section 5.1](https://tools.ietf.org/html/rfc2046#section-5.1) and [RFC2045 section 6](http://tools.ietf.org/html/rfc2045#section-6). According to these, each part of a multipart entity may have a Content-Transfer-Encoding. If this has value `quoted-printable` or `base64`, then the content of the body part has been encoded with the named encoding. If it is `7bit`, `8bit`, `binary`, or omitted, then no encoding has been applied.

Apache Commons has `Base64` and `QuotedPrintableCodec` which may be applicable in an implementation.

**Comment by sirthias** [comment]
Thanks for this nice ticket description and the references to the relevant RFCs!

/cc @jrudolph

**Comment by kswmsw** [comment]
:-) thanks!

**Comment by kswmsw** [comment]
Hi, can you give me an idea of where this is in your queue? Thanks.

**Comment by sirthias** [comment]
Unfortunately this is not on our high-priority list at the moment.
There are quite a few tickets that likely affect more users and are thus more crucial to get done ASAP.

**Comment by kswmsw** [comment]
That's fine, thanks for letting me know. I appreciate all the great work you do.

**Comment by ktoso** [comment]
Moving to `1.x`, sounds like we should do it however it's not urgent.

**Comment by kw217** [comment]
Thanks.

**Comment by kswmsw** [comment]
Thanks.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
