### ISSUE TITLE
Revive optimization support

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16939]
Currently optimizations are disabled because they relied on the old representation. However, they can be now implemented in a more throughout and systematic way then before.

**Comment by jrudolph** [comment]
I think this has accidentally moved to the http milestone?

**Comment by drewhk** [comment]
yes, moved now.

**Comment by drewhk** [comment]
As per discussion in Frankfurt, this is no longer considered relevant and fully superceded by https://github.com/akka/akka/issues/15364
