### ISSUE TITLE
Increase testing coverage of StreamLayout and MaterializerSession

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16936]
We have the luxury now to test the internal representation and its materializaton traversal in isolation. There are a couple of tests already but it is not comprehensive.

**Comment by rkuhn** [comment]
Part of this will likely be done during #16940 .

**Comment by rkuhn** [comment]
Things are kind-of fixed in place by Fusing and related tests, leaving the rest to all the nice boy-scouts.
