### ISSUE TITLE
Busy wait in IO(Tcp)

### ISSUE THREAD

**Issue by PalePrime** [akka/akka#16942]
After using IO(Tcp) to create a basic TCP connection (Bind + Connect), one thread runs 100% cpu even with no data being transferred. See enclosed TestKit code, where the busy wait occurs during the main Thread.sleep. Note that the test passes, this was just the most compact way I could create code to provoke the busy wait issue.

This was run using Scala 2.11.5 and Akka 2.3.9 and with both Java 7 and 8. It happens on both Windows 7 and Windows 8.1 (not tried on other OS).

Using Java VisualVM to profile during the main thread sleep indicates 99% of cpu cycles spent in akka.io.SelectionHandler$ChannelRegistryImpl$$anon$3.tryRun()

If I go back to Scala 2.10.4 and Akka 2.2.4 there is virtually no cpu load during the main thread sleep.

I am quite baffled by this behaviour, we have used Akka 2.2.x IO(Tcp) a lot and not seen anything like this. After porting to new versions, we saw very high cpu load from code that used to work just fine.

```scala
  test("Akka TCP busy wait") {
    var ss, cc, sc: Option[ActorRef] = None
    val address = new InetSocketAddress("localhost", 1234)
    IO(Tcp) ! Bind(self, address)
    expectMsgPF(3.seconds) {
      case Bound(local) =>
        ss = Some(lastSender)
    }
    IO(Tcp)  ! Connect(address)
    val connectMessages = receiveWhile(15.seconds, 10.seconds, 2) {
      case Connected(r, _) if r==address =>
        lastSender ! Register(self)
        cc = Some(lastSender)
      case Connected(_, l) if l==address =>
        lastSender ! Register(self)
        sc = Some(lastSender)
    }
    assertResult(2)(connectMessages.length)
    Thread.sleep(10000) // During this sleep one thread runs 100% cpu!!!
    cc map (_ ! Close)
    sc map (_ ! Close)
    val closeMessages = receiveWhile(15.seconds, 10.seconds, 2) {
      case c: ConnectionClosed =>
    }
    assertResult(2)(closeMessages.length)
    ss map (_ ! Unbind)
    expectMsgPF(3.seconds) {
      case Unbound =>
        ss map (_ ! PoisonPill)
    }
  }
```

**Comment by drewhk** [comment]
Hi,

See this thread (among others):
https://groups.google.com/forum/#!topic/akka-user/WHLhL47a6Kw

You just need to turn off a configuration setting. We will make this off by
default in 2.3.10, and hopefully we will be able to remove the Windows
related workaround.

-Endre

**Comment by PalePrime** [comment]
Big thanks for the pointer! Setting "akka.io.tcp.windows-connection-abort-workaround-enabled" to false does indeed make the problem go away.

Sorry for reporting an a known issue, but I searched for several hours before writing the bug report and did not come up with anything useful... Now that I know to search for the setting you mentioned, I am of course able to find several reports on the issue.

A bit strange that the solution to this Windows specific issue is to turn off a Windows specific work-around, isn't it!?

Thank you again!

**Comment by drewhk** [comment]
Hi,

On Thu, Feb 26, 2015 at 1:02 PM, PalePrime <notifications@github.com> wrote:

> Big thanks for the pointer! Setting
> "akka.io.tcp.windows-connection-abort-workaround-enabled" to false does
> indeed make the problem go away.
>
> Sorry for reporting an a known issue, but I searched for several hours
> before writing the bug report and did not come up with anything useful...
> Now that I know to search for the setting you mentioned, I am of course
> able to find several reports on the issue.
>
> A bit strange that the solution to this Windows specific issue is to turn
> off a Windows specific work-around, isn't it!?
>
Just to give the context, the original report was that after TCP RST, if
there was no reads pending (using ResumeReading mode) then the disconnect
event was never detected. The original PR was this:
https://github.com/akka/akka/pull/15814

We experimented some and come up with the workaround which made the
relevant tests pass, but unfortunately it had the unintended side effect of
this CPU usage, which we did not see. Thankfully we made the workaround
switchable, but now you have to live with the fact that if you never read
anything from a connection while using "pullMode" then NIO will never
notify us of a potential close event on Windows.

This is also a related ticket: https://github.com/akka/akka/issues/16552
which intends to solve this and similar issues by reading *ahead* from TCP
before the user actually asks for it. That hopefully enables us to catch
these close events, but generally, NIO is not very friendly to us in this
regard.

-Endre

**Comment by PalePrime** [comment]
@drewhk Thanks again for elaborating and sorry for letting out som frustration in my comment above.

It is kind of fascinating that this kind of an issue can arise from someting as widely used as Tcp on top of NIO.

I am closing the ticket as it is obviously a duplicate.
