### ISSUE TITLE
Akka 2.4-SNAPSHOT ConcurrentModificationException during Serialization

### ISSUE THREAD

**Issue by jeffrey-aguilera** [akka/akka#16956]
```
| 3685 | 2015-0227 | 08:48:27.111 | WARN  | akka.remote.ReliableDeliverySupervisor                       | Association with remote system [akka.tcp://jetstream@ec2-54-197-165-153.compute-1.amazonaws.com:2551] has failed, address is now gated for [5000] ms. Reason: [Failed to write message to the transport] Caused by: [java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
classLoader (akka.actor.ReflectiveDynamicAccess)
dynamicAccess (akka.dispatch.DefaultDispatcherPrerequisites)
prerequisites (akka.dispatch.DispatcherConfigurator)
configurator (akka.dispatch.Dispatcher)
executionContext (akka.actor.LightArrayRevolverScheduler$TaskHolder)
timer (jetstream.Registry$Registration)
hd (scala.collection.immutable.Stream$Cons)
$outer (scala.collection.immutable.Stream$$anonfun$map$1)
tlGen (scala.collection.immutable.Stream$Cons)
endpoints (jetstream.Registry$Replace)]
```

**Comment by jeffrey-aguilera** [comment]
Akka 2.3.9 did not generate these exceptions. Using Chill/Kryo for serialization (without a version change from 2.3.9 to 2.4-SNAPSHOT.)

**Comment by bantonsson** [comment]
Hi @jeffrey-aguilera, thanks for reporting this.

Is this easy to reproduce for you? Would it be possible to create a stand alone reproducer?

**Comment by jeffrey-aguilera** [comment]
Encountered this again tonight after using 2.4-SNAPSHOT successfully for a few weeks.  Similar trace

 WARN  | akka.remote.ReliableDeliverySupervisor                       | Association with remote system [akka.tcp://jetstream@ec2-54-161-225-25.compute-1.amazonaws.com:2551] has failed, address is now gated for [5000] ms. Reason: [Failed to write message to the transport] Caused by: [java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
classLoader (akka.actor.ReflectiveDynamicAccess)
dynamicAccess (akka.dispatch.DefaultDispatcherPrerequisites)
prerequisites (akka.dispatch.DispatcherConfigurator)
configurator (akka.dispatch.Dispatcher)
executionContext (akka.actor.LightArrayRevolverScheduler$TaskHolder)
timer (jetstream.Registry$Registration)
hd (scala.collection.immutable.Stream$Cons)
$outer (scala.collection.immutable.Stream$$anonfun$map$1)
tlGen (scala.collection.immutable.Stream$Cons)
endpoints (jetstream.Registry$Replace)]

Do not have a simple test fixture to reproduce this.

**Comment by rkuhn** [comment]
CME is not thrown by the Scala library, what kind of `Seq` are we talking about here? My first guess would be that you are using some mutable Java collection and retain a reference to it while sending it in a message—then if you modify the collection from within your local Actor while the remote message is serialized you’ll get this exception.

The other thing I’m wondering about is that there are many things in the trace that should not be serialized at all: what exactly is a “serialization trace”?

**Comment by drewhk** [comment]
This exception comes just right at the point where serialization happens and the message becomes a chunk of bytes. I think @rkuhn might be right and you are modifying something while the serializer also tries to access it.

**Comment by bantonsson** [comment]
+1 for that. The `Seq` is not immutable by default.

**Comment by drewhk** [comment]
Doesn't the case class close over the enclosing object somehow and retaining reference to something mutable?

**Comment by rkuhn** [comment]
No, an `object` is a static scope, no hidden `$outer` references needed.

**Comment by drewhk** [comment]
If the case class is really as simple as in the snippet then yes. I just wanted to warn if the actual case class does more than it is shown here.

**Comment by rkuhn** [comment]
assuming that our guess was correct, please reopen if not
