### ISSUE TITLE
disentagle DSLs and ActorFlowMaterializer

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16951]
Currently we do not support other materializers because OperationAttributes directly require ActorFlowMaterializerSettings. We should remove those settings from the API and only use OperationAttributes on the surface. The materializer can take arbitrary other parameters during its construction, but there should not be “FlowMaterializerSettings” that play a user-visible role.

OperationAttributes must also be rethought in that they are part of the DSL and pertain therefore only to the semantic requirements of the graph sections they apply to, they must not be materializer specific. If we need such a feature, we’ll need to properly abstract that out (i.e. properly make it extensible). We cannot lock ourselves into ActorFlowMaterializer.

**Comment by drewhk** [comment]
... and OperationAttributes are not really extensible either. It would make sense to have some generic settings, and then specific materializers can use subclasses of the Attributes class if they recognize one, or just fall back to the generic logic if a generic attributes is found.

**Comment by patriknw** [comment]
This should be sufficient:

* remove `sealed` from `trait Attribute`
* move `OperationAttributes.Dispatcher` and `OperationAttributes.SupervisionStrategy` and corresponding factory methods to `object ActorOperationAttributes`

**Comment by patriknw** [comment]
Why do we have both scaladsl and javadsl OperationAttribtues? The api of those are not fancy enough to motivate that, as far as I can see. WDYT?

**Comment by patriknw** [comment]
I have this ready, but need to merge https://github.com/akka/akka/pull/17175 first
