### ISSUE TITLE
If there is a PushPullStage, OnComplete is sent only if a request is made

### ISSUE THREAD

**Issue by TrustNoOne** [akka/akka#16966]
Since M4, the following example only prints 
```
pulling
absorbing
42
```
but not "finishing". onPull() is never called with isFinishing == true

```scala
import akka.actor.ActorSystem
import akka.stream.ActorFlowMaterializer
import akka.stream.scaladsl.{Keep, Sink, Source}
import akka.stream.stage.{ Context, Directive, PushPullStage, TerminationDirective }
import scala.concurrent.Await

object TestBug extends App {

  class MyStage[T] extends PushPullStage[T, T] {
    override def onPush(elem: T, ctx: Context[T]): Directive = {
      ctx.push(elem)
    }

    override def onPull(ctx: Context[T]): Directive = {
      if (ctx.isFinishing) {
        println("finishing")
        ctx.finish()
      } else {
        println("pulling")
        ctx.pull()
      }
    }

    override def onUpstreamFinish(ctx: Context[T]): TerminationDirective = {
      println("absorbing")
      ctx.absorbTermination()
    }
  }

  implicit val system = ActorSystem()
  implicit val mat = ActorFlowMaterializer()

  val f = Source.single(42).transform(() => new MyStage).toMat(Sink.head())(Keep.right).run()

  println(Await.result(f, 10.seconds))
}

**Comment by TrustNoOne** [comment]
Ok maybe it's not a bug? currentOp is not allowed to push because the sink.head downstream is interested in only 1 element? 

``scala
    if (currentOp.allowedToPush) currentOp.onPull(ctx = Pulling)
      else exit()

**Comment by ktoso** [comment]
Can you try that with a Sink.foreach? Sink.head issues exactly one demand - so there is nothing to cause the 2nd onPull.

**Comment by ktoso** [comment]
Oh I see you answered yourself already :-) was being slow as replying from my phone :-)

**Comment by TrustNoOne** [comment]
Thanks! Anyway I still have a bug in my code since M4 (finish is not called, but this time it should), but it's using an ActorProducer as a source. I'll investigate and post more detail later

**Comment by TrustNoOne** [comment]
yep sorry about that :)  I still have tests failing in my code because after upgrading to M4 I don't receive OnComplete anymore (I'm using a test probe "borrowed" from some internal testkit)

I'll investigate why I have this problem and let you know if I find anything

**Comment by TrustNoOne** [comment]
Ok I got what the problem is: 
If I add the stage (the one in the post above), OnComplete is sent **only if a request is made**.
OnComplete messages should not be sent only reacting to pull requests afaik. The behaviour is inconsistent anyway, if I remove the stage, OnComplete is sent eagerly even if I only request 1 item.

```scala
      Source.single(42).transform(() => new MyStage)
        .runWithProbe { p =>
          p.expectSubscription().request(1)
          p.expectNext(42)
          //This is received only if i request(2) or if remove the stage
          p.expectComplete()
      }

**Comment by patriknw** [comment]
a `Publisher` is allowed to wait with signalling `onComplete` until there is a request, e.g. some publishers may be lazy and do nothing until there is a request

The `Sink.head` cancels the subscription when the first element is received

**Comment by drewhk** [comment]
Yes, and this is completely fine:
 - If the Subscriber needs data it signals demand
 - If the Publisher cannot fulfill requests, it signals onComplete
 - The Publisher **MAY** signal onComplete even if there are no demand pending, but this is merely an optimization and does not change the semantics of completion at all
