### ISSUE TITLE
add generalized UnzipWith

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16965]
This should be a more approachable form of FlexiRoute that works using a single function:
~~~scala
def unzip[A, B] = UnzipWith((p: (A, B)) => (p._1 :: Nil, p._2 :: Nil))
~~~
meaning that upon receiving an input each of the outputs receives zero or more (strictly available) elements. The real Unzip will of course not be implemented like this in order to avoid the extra allocations, but as user feature this is way easier than having to worry about demand and a RouteLogic implementation.

**Comment by ktoso** [comment]
In process by @agolubev in https://github.com/akka/akka-meta/issues/4
