### ISSUE TITLE
Set inputSize attributes on Sinks where the maximum number of elements consumed is known

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16967]
Like, head, take. With the new handling of attributes this can be done very easily.

**Comment by agolubev** [comment]
@drewhk is it just declarative? can you give an example or use case?

**Comment by ktoso** [comment]
We have `DefaultAttributes` in `akka.stream.impl.Stages`, in there for `head` etc we could define that:
`val headSink = name("headSink") and inputBuffer(initial = 1, max = 1)`.

**Comment by agolubev** [comment]
hm, it maybe will not be safe to set buffer max to N in case of take(N), as it can be really big.

**Comment by agolubev** [comment]
ah, it's input buffer

**Comment by ktoso** [comment]
Yeah, input buffer for "head" can safely be `1` :)

**Comment by agolubev** [comment]
should it be something for  cancelledSink and ignoreSink?

**Comment by drewhk** [comment]
For take it might not make sense unless N is small. For cancelledSink it does not matter since it is not backed by an actor (and does not have a buffer), and the same is true for ignoreSink.

**Comment by agolubev** [comment]
Pull request for this ticket is already merged #18094.
Can someone close the ticket?

**Comment by ktoso** [comment]
Good catch, thanks @agolubev!
This is solved by both #18094 and https://github.com/akka/akka/issues/18091
