### ISSUE TITLE
1.0-M4 spray-json: Better error for missing ActorFlowMaterializer implicit

### ISSUE THREAD

**Issue by francisdb** [akka/akka#16968]
Hi, not sure if there is a solution for this.
Project using akka-http-spray-json-experimental

I got this compile error in my project:
```scala
could not find implicit value for parameter um: akka.http.unmarshalling.FromRequestUnmarshaller[xxx.MyCaseClass]
```

After a lot of searching (replacing implicits with explicit code) I found the actual problem:
```scala
could not find implicit value for parameter mat: akka.stream.ActorFlowMaterializer
[error]                         sprayJsonUnmarshaller[MyCaseClass]
```

I had an implicit FlowMaterializer in scope where I needed a ActorFlowMaterializer.

Would there be a way to let the compiler directly return the second error?

**Comment by francisdb** [comment]
I suppose this is somewhat related to #16963

**Comment by rkuhn** [comment]
These are very tricky to improve, but at least this concrete case will go away, see #16963. We’ll keep the ticket in any case in order to improve things, though the only measure that could really help is by way of using a macro … and those are an experimental feature :-(

**Comment by ktoso** [comment]
This was solved by @jrudolph by removing the need for the implicit parameter entirely in commit: 195650ff7eaea7a922bb6fc0da95f3b1368f669e
