### ISSUE TITLE
PredefinedFromEntityUnmarshallers.stringUnmarshaller needs ActorFlowMaterializer

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#16963]
In 1.0-M3 it required an implicit FlowMaterializer only. Is it really necessary to have an ActorFlowMaterializer here?

**Comment by rkuhn** [comment]
thanks for raising, this is an oversight

**Comment by hseeberger** [comment]
Tja, kann auch den Besten passieren ;-)

**Comment by rkuhn** [comment]
@sirthias @jrudolph please review our recent HTTP changes and in particular make sure that the type ActorFlowMaterializer is not used within HTTP

**Comment by sirthias** [comment]
@rkuhn Ok, will do.

**Comment by sirthias** [comment]
@rkuhn Would this usage of `ActorFlowMaterializer` be an example of something awry?:
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/engine/server/HttpServer.scala#L53

**Comment by sirthias** [comment]
Btw: A quick grep shows me 30 non-import uses of `ActorFlowMaterializer` in `akka-http-core/src/main`. Are all of these to be replaced with `FlowMaterializer`?

**Comment by drewhk** [comment]
https://github.com/akka/akka/issues/16934

**Comment by drewhk** [comment]
yes, it is just a side-effect of a rename during merge.

**Comment by sirthias** [comment]
@drewhk Ok, thanks. I'll put in quick PR then to get this done for HTTP. So I have a clean base to work off from.

**Comment by drewhk** [comment]
Thanks for that! It helps us a lot.

**Comment by rkuhn** [comment]
@sirthias The example you linked to is an internal one, but you’ll probably find yourself forced to change that one when changing all the user-visible implicits as well.

**Comment by TrustNoOne** [comment]
Hi, I had the same problem with the formFields(...) extractor in M4 (I guess it uses the same unmarshaller?), @ktoso suggested me to let you guys know so that you don't miss it: https://groups.google.com/forum/#!topic/akka-user/Xp2cMvvpfso

:+1:

**Comment by ktoso** [comment]
I believe this was solved in 195650ff7eaea7a922bb6fc0da95f3b1368f669e
