### ISSUE TITLE
Props.create must not check for STATIC flag

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16969]
The presence of this flag for anonymous classes inside static methods was a [bug](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8034044) that will be fixed.

Proposal from Steve Ramage on the mailing list: «a better check would be is to look at the getDeclaredConstructors and see if there is an implicit constructor that matches the arguments provided, if it was static then it should exist, otherwise it will have an implicit argument for the outer class.»

**Comment by ktoso** [comment]
Stashed it for now.

**Comment by sgwerder** [comment]
Prevents Akka on Eclipse IDE. See: https://groups.google.com/forum/#!topic/akka-user/YVYTYTdVRLQ

**Comment by patriknw** [comment]
Thanks for the reminder. Marked as bug to give it more attention. If someone has some spare cycles to fix it a pull request is welcome. Starting point: https://github.com/akka/akka/issues/17412

**Comment by drewhk** [comment]
@ktoso what is the story here? I don't remember what the original issue was, or what is still missing.

**Comment by ktoso** [comment]
I think I remember: it's about currently not being able to create an Actor via Props, when the actor class is an inner static class. Previously that _class_ would have the STATIC flag set, however that was a bug in the JDK, and nowadays is fixed. Instead we should check for a constructor that we can use, and not just the static flag (as it prevents some legal uses of Actors)

**Comment by patriknw** [comment]
I'm trying to revive this old chap

**Comment by ktoso** [comment]
Thanks @patriknw
