### ISSUE TITLE
Http().bindAndStartHandlingWith does not work

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16972]
there’s a `.run()` missing

**Comment by TrustNoOne** [comment]
and a typo (lowercase s in start) in the method name

**Comment by danielwegener** [comment]
Just ran into this one too. As a workaround, one could use:
```
//FIXME: Workaround https://github.com/akka/akka/issues/16972 is fixed
    Http().bind(interface = "localhost", port = 8081 /* ... */ ).toMat(Sink.foreach { conn ⇒
    conn.flow.join(myRoute).run()
    })(Keep.left).run()
```

**Comment by rkuhn** [comment]
`.toMat(...)(Keep.left)` can in all cases be simplified to `.to(...)`, but otherwise thanks for adding this here.

**Comment by hseeberger** [comment]
As the name has to be changed anyway, because of the lowercase "s" in "start", why not align the method name with StreamTcp, i.e. call it "bindAndHandle". Or vice versa.

**Comment by richdougherty** [comment]
:+1: This got me too.
