### ISSUE TITLE
Watch the connection actor from the Stream actor

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16973]

**Comment by patriknw** [comment]
is this about the configuration property `akka.io.tcp.register-timeout`? how should that be exposed, more than being a config property?

**Comment by drewhk** [comment]
It is about the TCP stream actor responding properly to registration timeout.

**Comment by drewhk** [comment]
Actually, there is no such thing as a registration timeout message, the TCP actor just stops. What is missing though is watching the connection actor from the TCP stream actor.
