### ISSUE TITLE
FAILED: GraphBalanceSpec, waitForAllDownstreams seems to have no effect

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16978]
https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/2043/

```
- must fairly balance between three outputs *** FAILED *** (525 milliseconds)
[info]   7953 was not 10000 plus or minus 2000 (GraphBalanceSpec.scala:139)
```

The test sets `waitForAllDownstreams = true ` and I thought that meant it wouldn't start producing to the downstreams until they where all "connected" but they get marked during construction, and it starts as soon as possible.

**Comment by drewhk** [comment]
That is a bug then. I was under the impression that that setting will force it to wait for all downstream subscriptions.

**Comment by bantonsson** [comment]
Misread the Balance code while filing the bug. It actually waits for all downstreams to have demand. Probably just unfair scheduling that made the test fail.
