### ISSUE TITLE
BUG: If a single Op flow fails more than once it is stopped no matter what the Supervision.Decicder says

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16982]
It seem like the code in `OneBoundedInterpreter.execute` skips using the decider for all but the very first exception it encounters for single op flows.

See question here https://groups.google.com/d/msg/akka-user/PEf2HUZtXkk/G_HQg7HAuJkJ

**Comment by drewhk** [comment]
It looks like the double-fault handling kicked in.

**Comment by bantonsson** [comment]
Yes, I know, but is that by design that you can only ever fail once in the entire stream for a simple map?

**Comment by drewhk** [comment]
No, see:

          lastOpFailing = activeOpIndex
          decide(e) match {
            case Supervision.Stop   ⇒ state.fail(e)
            case Supervision.Resume ⇒ state.pull()
            case Supervision.Restart ⇒
              pipeline(activeOpIndex) = pipeline(activeOpIndex).restart().asInstanceOf[UntypedOp]
              state.pull()
          }

**Comment by drewhk** [comment]
when resume or restart is used then lastOpFailing has to be reset to -1.

**Comment by bantonsson** [comment]
So what purpose does lastOpFailing serve then? Either you fail or you reset it.

**Comment by drewhk** [comment]
The purpose is to avoid infinite loops when fail fails -- double fault.

**Comment by bantonsson** [comment]
Ah, check we fork the fail(...) call, and that can of course fail.

**Comment by drewhk** [comment]
yes, this was quite hard to get right. We can make this smarter though, probably the best place to reset this marker is after any successful op event (fail, pull, etc), not in the above part. I am not sure though, whomever picks this needs to try.

**Comment by l15k4** [comment]
Seems to be a duplicate https://github.com/akka/akka/issues/16979

**Comment by bantonsson** [comment]
@l15k4 Yes indeed. Thanks again for reporting.

**Comment by drewhk** [comment]
Thanks @l15k4, I will close that one since this contains important discussions

**Comment by drewhk** [comment]
Ah @bantonsson was quicker. But I still think we should keep this one, not the other :)

**Comment by drewhk** [comment]
btw, the "Cause: java.lang.IllegalStateException: Processor actor terminated abruptly" exception happens exactly because the interpreter just throws, does not produce an onError (since it considers itself inconsistent)

**Comment by l15k4** [comment]
Hey,

I have a feeling that it is broken again in a different way, I cannot reproduce it in a test case but after I upgraded to RC1 then if an exception is thrown in `mapAsync` then the last code executed is `Supervision.Resume` in `Supervision.Decider` and then it gets stuck indefinitely...
```
sudo jstack 16120
16120: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding
```

```
sudo jstack -F 16120 > dump.out
```
[dump.out | uploaded via ZenHub](https://files.zenhub.io/554a972b8fd825ae6d3e1aa0)

**Comment by drewhk** [comment]
I don't think the above problem is related to the one described in this ticket per se, can you open a new ticket?

**Comment by l15k4** [comment]
I think it is because it gets stuck on the third exception, it survives 2 exceptions in a row but on the third one it gets stuck

**Comment by patriknw** [comment]
anyway, `mapAsync` is implemented in another way now, so please open a new issue
