### ISSUE TITLE
Http().bind documentation

### ISSUE THREAD

**Issue by richdougherty** [akka/akka#16989]
A couple of suggestions:
* Update [HttpServerExampleSpec](https://github.com/akka/akka/blob/e30c3e6492fdffb20ee8baa488611213b5a66755/akka-docs-dev/rst/scala/code/docs/http/HttpServerExampleSpec.scala) so it shows how to get the `ServerBinding` object. It took me a while to work this out, because I'm a noob at Akka Streams. :) Since 1.0-M4 I see the docs are a bit clearer because there's now a `bindingFuture` variable. To make it even easier for noobs like me, it may help to add a type annotation to this variable, i.e. `Future[ServerBinding]`.
* Either remove [TestServer](https://github.com/akka/akka/blob/e30c3e6492fdffb20ee8baa488611213b5a66755/akka-http-tests/src/test/scala/akka/http/server/TestServer.scala) or update it to follow current best practice for binding. In 1.0-M4, TestServer doesn't work because of #16972 and it took me a while to find the docs (and `HttpServerExampleSpec`) with the correct information.

**Comment by bantonsson** [comment]
Thanks. Agree that the code/docs need to be updated.

**Comment by drewhk** [comment]
> To make it even easier for noobs like me, it may help to add a type annotation to this variable, i.e. Future[ServerBinding].

Good point!

> Either remove TestServer or update it to follow current best practice for binding. In 1.0-M4, TestServer doesn't work because of #16972

The bug needs to be fixed, not the doc updated (the next doc update can only happen at the next milestone release -- our docs are part of the release).

**Comment by richdougherty** [comment]
Thanks!
