### ISSUE TITLE
Parsing RawHeaders with names containing header separator

### ISSUE THREAD

**Issue by richdougherty** [akka/akka#16988]
`RawHeader` parsing should fail when the header name contains a sequence of a colon and a space (`": "`). Currently parsing returns an invalid result with the `": "` characters moving into the `RawHeader` value field. Instead of returning an invalid result, a parse error should be returned.

An example test case:
```scala
HeaderParser.parseHeader(RawHeader("X: ", "a")) shouldEqual Left(ErrorInfo("Illegal header `X: ` contains invalid character: `:`"))
```

This test fails with:
```
Right(X: : a) did not equal Left(ErrorInfo(Illegal header `X: ` contains invalid character: `:`,))
```

**Comment by mehmeteking** [comment]
Is this issue not resolved already by https://github.com/akka/akka/pull/17001?

**Comment by sirthias** [comment]
Yes, indeed. Thanks!
