### ISSUE TITLE
stream cancellation leaks actors

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16986]
Currently ActorInterpreter will not shut down after receiving cancellation from downstream (it will pass on the cancel signal though). Fixing this will mean that OnSubscribe events can go to dead letters, which will mean that upstream flows will just hang around unless we introduce a timeout. We need to fix all angles to this—belt and suspenders.

This is possibly also related to #16900.

**Comment by drewhk** [comment]
Why is this so hard to fix? Isn't this then also a problem with ordinary ActorProcessor? Or if not, why is it harder to fix it here?

**Comment by rkuhn** [comment]
Yes, this would affect all Actors that we create. Your proposal of just keeping them alive until the `OnSubscribe` comes in would take care of this issue, I’ll try it out and close this issue if successful.

**Comment by rkuhn** [comment]
Fixed for ActorInterpreter, still need to look at other ActorProcessors.

**Comment by patriknw** [comment]
yes, the new TCK detected this for PrefixAndTail

**Comment by drewhk** [comment]
Hasn't this been fixed already?

**Comment by patriknw** [comment]
I don't think so. My workaround (// FIXME  unreference real subscriber, should not be needed after #16986) in StreamOfStreamProcessors.scala is still there and the tck-tests (required_spec313_cancelMustMakeThePublisherEventuallyDropAllReferencesToTheSubscriber) fail without it.

**Comment by drewhk** [comment]
What is the issue there? I don't remember the details.

**Comment by patriknw** [comment]
I don't remember the details. :(

**Comment by drewhk** [comment]
also https://github.com/akka/akka/issues/15191

**Comment by rkuhn** [comment]
many custom processors will be removed in the wake of #17090

**Comment by patriknw** [comment]
Solved the issue with stream of streams in #17212, but that was not an actor leak. So more to do here.
