### ISSUE TITLE
akka-http: DELETE method should accept non-empty HTTP entity

### ISSUE THREAD

**Issue by kostya-sh** [akka/akka#16981]
Currently isEntityAccepted = false for HttpMethod.DELETE meaning that akka http client cannot send a DELETE HttpRequest with body.

According to the discussion (with the links to the relevant specifications) at http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request body for DELETE method is not explicitly disallowed.

I think both client and server implementations should support non empty entity in DELETE request.

**Comment by sirthias** [comment]
The [current spec](http://tools.ietf.org/html/rfc7231#section-4.3.5) says:

> A payload within a DELETE request message has no defined semantics;
> sending a payload body on a DELETE request might cause some existing
> implementations to reject the request.

If the entity has no defined semantics it doesn't appear to make sense to attach one.
What's your use case?

/cc @jrudolph

**Comment by kostya-sh** [comment]
I am developing a client for a proprietary HTTP service that uses DELETE request with payload for some of API calls. While it is probably not very common there are other applications with similar APIs. E.g. Elasticsearch: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-delete-by-query.html

Disallowing payload for DELETE method makes akka-http client library unusable for communicating with such services.

**Comment by sirthias** [comment]
Ok, thanks for providing this example.
Apart from further watering down an already very watery standard I don't see much harm in setting `isEntityAccepted = true` for DELETE.

**Comment by kostya-sh** [comment]
Great, thanks!

**Comment by analytically** [comment]
Relevant: https://blogs.dropbox.com/developers/2015/03/limitations-of-the-get-method-in-http/

**Comment by sirthias** [comment]
Thanks for the pointer, @analytically, interesting!

**Comment by sirthias** [comment]
Superseded by #17214.
