### ISSUE TITLE
Automate copyright header updates with sbt-header

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16990]
https://github.com/sbt/sbt-header

**Comment by valydia** [comment]
Won't such a plugin violate the guideline `Never delete or change existing copyright notices, just add additional info.`  as some of the headers don't share the same year? Would it matter if all the headers are update to the same year range for instance 2009-2016 (or any other), in which case, i could submit a PR? If not, we'll have to wait for [sbt/sbt-header#23](https://github.com/sbt/sbt-header/issues/23) to be fixed.
