### ISSUE TITLE
Is FlattenStrategy placed in right package?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16993]
`abstract class FlattenStrategy` is used in both javadsl and scaladsl, but the concrete `concat` for the javadsl is in `javadsl.FlattenStrategy` and the concrete `concat` for the scaladsl is in `stream.FlattenStrategy`.

I think it would be most consistent to not have anything of this in the `stream` package, i.e. two separate classes in `javadsl` and `scaladsl`.

**Comment by patriknw** [comment]
@rkuhn thoughts?

**Comment by rkuhn** [comment]
Yes, I think the DSLs have evolved a little differently than we foresaw back then.

**Comment by drewhk** [comment]
has this been done?

**Comment by patriknw** [comment]
Not completely, see comments in PR #17019
