### ISSUE TITLE
"decompressRequest" routing directive converts Default entities to Chunked entities

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#16998]
The "`akka.http.server.CodingDirectives.decodeRequest`" method calls `mapEntity` on the request entity.

When the request has a `Default` or `Strict` entity, this will always convert the entity to a `Chunked` entity, even if the `NoCoding` coding is used.

This discards the `Content-Length` information from the request.

I have the following code in my routing DSL:

```
  /**
   * This method takes a route and wraps it to support request/response compression.
   */
  def handleCompression(route: Route): Route = {
    decompressRequest(Gzip, Deflate, NoCoding) {
      compressResponse(NoCoding, Gzip, Deflate) {
        route
      }
    }
  }
```

The issue described above means that all my requests now appear to be chunked, and I cannot determine the request `Content-Length` without streaming in the request body.

I think that either the `NoCoding` decoder should preserve the `HttpEntity` type of the request, or there should be some other way to optionally decompress a request.

**Comment by RichardBradley** [comment]
Can I elaborate on what I'm trying to do, and why this is a problem for me?

I have an Akka HTTP app with multiple endpoints. I want all endpoints to support optional request / response compression, so all routes are wrapped by the above helper.

Some endpoints have a maximum allowed request length (and the length can vary by endpoint). How should I enforce this?

I have a custom stream `Flow` stage which aborts the upload after the limit, which caters for `Chunked` requests.

However, it would be nice for performance if I could reject `Default` requests after receiving just the `Content-Length` header. But what about compressed requests?

I was thinking I need to do the following:

 * Write a custom decompression helper which a) preserves the `Content-Length` header for uncompressed requests and b) adds a custom `X-Compressed-Content-Length` header for compressed requests
 * In an endpoint with max upload size N, reject any requests which are `Default` and have `Content-Length` > N or which are `Chunked` and have `X-Compressed-Content-Length` > N. Also, insert my custom `Flow` stage which aborts the upload after N bytes, to catch the other cases.

Does that sound sensible to you? Do you think Akka should help with any of that, or is it a niche requirement?

Thanks,


Rich

**Comment by jrudolph** [comment]
Thanks @RichardBradley for reporting. The request for `NoCoding` not to change the request is obviously valid. I'm not so sure about what else Akka HTTP could provide to help you in compressed cases as what you propose seems to be just one possible scheme for how to deal with it. E.g. you could deal with it on the routing layer by doing the length check before doing decompression without any extra logic needed.

**Comment by RichardBradley** [comment]
>  I'm not so sure about what else Akka HTTP could provide to help you in compressed cases 

I think ideally it would add [non-printing headers](https://github.com/akka/akka/issues/16084) like "`X-Compressed-Content-Length`" and perhaps even "`X-Estimated-Uncompressed-Content-Length`" to the request as it modifies it. This info is useful to the application layer, and it is currently only available to the decoder.

There's not really any precedent in Akka HTTP for that kind of annotation though, so maybe I'll write my own helpers which do that and leave this issue as just fixing `NoCoding`.

**Comment by sirthias** [comment]
I think Rich's request to somehow (optionally) allow access to Content-Length as it was before (de)compression through a special is a valid thing.
@RichardBradley Would you want to open a dedicated feature ticket for this?

I also agree with the take that `NoEncoding` shouldn't change the message entity at all.

**Comment by jrudolph** [comment]
Couldn't you easily provide this as a custom directive:

```scala
def addRawLengthHeader: Directive0 =
    mapRequest { req ⇒
      req.entity match {
        case u: UniversalEntity ⇒ req.addHeader(RawHeader("X-Raw-Content-Length", u.contentLength.toString))
        case _                  ⇒ req
      }
    }
```

This would always add such a header if the incoming content-length is known. What else would you need @RichardBradley ?

**Comment by RichardBradley** [comment]
> Couldn't you easily provide this as a custom directive:

I can work around all this in user-code, yes.
I think the built-in directives are a bit broken in this regard though, hence this ticket.

**Comment by RichardBradley** [comment]
> I think ideally it would add non-printing headers like "X-Compressed-Content-Length" to the request as it modifies it. This info is useful to the application layer, and it is currently only available to the decoder.

Actually this isn't very useful -- most compressed uploads are Chunked, as the client usually doesn't know the compressed stream length in advance, but is gzipping an input stream as it comes. 

Let's not bother with that part, let's just fix that NoEncoding shouldn't change the message entity at all.

Sorry for the confusion.

**Comment by jrudolph** [comment]
@RichardBradley yes, I think that's something we should do in any case. I created #17068 to track this. I am closing this one for now. Thanks for the discussion.

**Comment by RichardBradley** [comment]
OK, thanks.

(Why close this one and open a new ticket tracking the same thing? Just to summarise the conversation so far?)

**Comment by jrudolph** [comment]
Yes, my intention was to have a clean working item.
