### ISSUE TITLE
akka-persistence-2.3.8: Duplicate messages while auto-update persistent view

### ISSUE THREAD

**Issue by marcuslinke** [akka/akka#17007]
When ```autoUpdate``` a ```PersistentView``` duplicate messages  may occur in the receive logic when the autoUpdate is still in progress while another autoUpdate is triggered. This is because the ```def lastSequenceNr``` used for the outer update doesn't reflect the last sequence number that has been pushed to the actors mailbox already.

One solution would be to filter messages with sequence numbers lower than ```lastSequenceNr```before passing it to the receive logic. Should i file a PR?

**Comment by patriknw** [comment]
@marcuslinke did you find the problem and all is good, or do we need to improve something?

**Comment by marcuslinke** [comment]
@patriknw I found the problem in my own code already so sorry for the false alert. Thanks anyway!

**Comment by patriknw** [comment]
thanks
