### ISSUE TITLE
Add `FlexiRoute.DemandFromNone` DemandCondition

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17004]
I have a `FlexiRoute` use case where I need to distribute elements from upstream to an Outlet selected by a property of the *incoming element*.
This means that I need to first request an element from upstream *and then* decide which output to await demand from.
Currently I can't do that. What I can do is await `DemandFromAny` to get hold of an upstream element, but then I'd have to await `DemandFrom(selected)` to be sure that there actually is demand from the selected outlet. However, this await will only be fulfilled when the *second* upstream element arrives.

What we need to introduce is another `DemandCondition` called `DemandFromNone`, which allows me to request an upstream element without any demand from downstream. Of course, in the handler for this I would not be allowed to call `ctx.emit`.

**Comment by rkuhn** [comment]
What you actually want is a FlexiKraken, but as a workaround you can use a doubler stage in front of the FlexiRoute in order to implement the scheme you sketched: demandFromAny to get the element (because if there is no demand whatsoever then you don’t need the element anyway), then demandFromX to do the real routing.

**Comment by sirthias** [comment]
Yeah, I just realized that the `DemandFromNone` doesn't suffice. It's really easy to implement (just did it), but then I'd need another `DemandFrom` variant that *doesn't* await another upstream element (because I already have one). Maybe the current design of `FlexiRoute` isn't good enough for routing based on any property of the input elements. Which is somewhat of a pity. Since the "flexi" then isn't that flexi at all.
I'll go with the doubler stage approach you proposed. Thank you for that idea!
