### ISSUE TITLE
On connection failure, a TcpStreamActor doesn't shut down

### ISSUE THREAD

**Issue by catalin-ursachi** [akka/akka#17008]
(This was encountered in a project using streams-1.0-M3; however, M4 doesn't obviously appear to have fixed it.)

If a TCP connection fails, and the TcpStreamActor managing it receives an error (e.g. ErrorClosed), the .fail(e) method is called. This method cancels the inputs and outputs, but the actor is never shut down.

The tryShutdown() method is only called if the stream completes gracefully - i.e., if .pumpFinished() is called on either the readPump or the writePump.

(If .pumpFailed(e) is called on either pump, that also simply calls fail(e) without shutting down the actor.)

Adding the line: "tryShutdown()" at the end of the .fail() method appears to solve the problem.

(Possibly related to https://github.com/akka/akka/issues/16986, https://github.com/akka/akka/issues/16900 ?)

**Comment by drewhk** [comment]
Thanks for reporting!
