### ISSUE TITLE
Akka HTTP app crashes when repeatedly polled with a socket connection

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#17015]
I have an Akka HTTP 1.0-M3 app which is crashing when one of our "uptime monitoring" systems repeatedly opens and closes a Socket connection to the app.

I have uploaded a repro to https://gist.github.com/RichardBradley/bc44724a7d1ac8f02601

To reproduce the issue, start the app with "`sbt run`" in one console.
In a second console, run "`sbt 'run poll'`"
After a little while, the server will crash. (This takes about 1-3 minutes on my Windows dev machine, or 10-30 minutes on our linux servers.)

Due to some combination of #17010 and likely some other issues, this demo app does not print a stack trace, it just exits.

The stack trace printed if you include the workaround from #17010 looks like:
```
java.lang.AssertionError: assertion failed: takePendingSubscribers must not be called after shutdown
	at scala.Predef$.assert(Predef.scala:165)
	at akka.stream.impl.ActorPublisher.takePendingSubscribers(ActorPublisher.scala:67)
	at akka.stream.impl.SimpleOutputs$$anonfun$downstreamRunning$1.applyOrElse(ActorProcessor.scala:202)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.stream.impl.io.TcpStreamActor.aroundReceive(TcpConnectionStream.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I have tried to figure out what the bug is, but I didn’t get anywhere :-)

I'd be very interested in a short-term workaround for this issue as well as a proper fix, as this is causing us trouble in the short term.

Thanks,

Rich

**Comment by bantonsson** [comment]
Thanks  a lot for reporting this issue and attaching a reproducer.

**Comment by drewhk** [comment]
I think one change related to this is in here: https://github.com/akka/akka/pull/16987
This assertion might be simply wrong and removed.

**Comment by RichardBradley** [comment]
Is a fix for this scheduled any time soon? This seems like a serious bug and a possible DOS avenue.

**Comment by sirthias** [comment]
@RichardBradley I just tried to reproduce this problem with your gist against RC1 under Linux and was unsuccessful. Even through I increased the polling frequency from 1 Hz to 50 Hz everything is still running smoothly after 2 hours.

Could you verify from your end (as your reported Windows to be more prone to error out early)?

(Btw: Thanks for providing a self-contained testing application. Very much appreciated!)

**Comment by RichardBradley** [comment]
This only seems to happen on slow or overloaded machines.

Since I uploaded this, I've upgraded from a Windows 7 dev machine to a much faster Windows 8 machine and now it doesn't repro for me either on my primary machine (still running OK after 40 mins). It used to repro almost immediately on my old machine.

I tried this on a fast (real) RHEL 6.5 server, and it's still running fine after 20 mins.

I was beginning to think that this had mysteriously gone away, but then I tried it on one of our RHEL 6.5 Virtual Machines we use for CI, and it crashed after 13 minutes (including reproducing #17010).

The VM is 4 cores: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz with 16 GB RAM.
I ran "master" (d5b807d3c036d) from the linked Gist.
The machine is using Java 6:
```
java version "1.6.0_20"
Java(TM) SE Runtime Environment (build 1.6.0_20-b02)
Java HotSpot(TM) 64-Bit Server VM (build 16.3-b01, mixed mode)
```

Let me know if I can give any further info to help diagnose this.

(Maybe add some Thread.sleeps to suspicious looking bits of the TCP code to see if it reproduces more easily?)

**Comment by jrudolph** [comment]
@RichardBradley did you already upgrade to RC1?

**Comment by RichardBradley** [comment]
No, that test was run on the 1.0-M3 code. Should I retest on RC1? Has anything relevant changed?

**Comment by sirthias** [comment]
Our first goal should be to somehow establish a reliable way to reproduce this problem quickly. Your tester helps but is a bit slow in triggering the problem. 20+ mins is simply too long to properly debug this thing.
What happens if you increase the polling frequency to 50 or 100 Hz on your CI VM? Does it bring down the time-to-failure from 13 mins?

> I ran "master" (d5b807d3c036d) from the linked Gist.

Ok. Can you upgrade to RC1?
Here is the patch for your gist: http://spray.io/files/0001-Upgrade-to-RC1.patch
(Somehow I can't push into your gist.)

**Comment by sirthias** [comment]
Or rather: here is my fork of your gist: https://gist.github.com/sirthias/cd95700d090fd0644d20

**Comment by RichardBradley** [comment]
> What happens if you increase the polling frequency to 50 or 100 Hz on your CI VM?

I ran the RC1 version at 1000 Hz for 25 mins without failure.

I have set it back to 1 Hz and have run it for 20 mins so far without failure.

Perhaps it is fixed on RC1? Have there been any relevant changes?

**Comment by sirthias** [comment]
> Perhaps it is fixed on RC1? Have there been any relevant changes?

Yes, there have been a ton of changes on pretty much all fronts.
Theoretically we could bisect the commit history to try and identify the actual fix but I don't think that the value of the gained information would offset the amount of effort required.
So, if you can't reproduce the problem in any of the environments that previously demonstrated the issue I'd vote for simply closing the ticket.

**Comment by RichardBradley** [comment]
OK, give me a few more hours to try to repro it, then I'm happy to close as presumed fixed.

**Comment by sirthias** [comment]
Great! Thanks again, Richard!

**Comment by drewhk** [comment]
for example actor leaks has been fixed since then

**Comment by RichardBradley** [comment]
Recent runs on my RHEL VM:

 time | version | poll frequency | result 
--- | ---- | --- | ---
 15:10 | RC1 | 1000 Hz | no crash after 25 min
 15:40 | RC1 | 1 Hz | no crash after 20 min
 16:13 | 1.0-M3 | 1 Hz | no crash after 11 min
 16:25 | 1.0-M3 | 50 Hz | crashed after 16 seconds
 16:26 | 1.0-M3 | 50 Hz | crashed after 22 seconds
  16:27 | RC1 | 50 Hz | no crash after 5 min
  16:33 | RC1 | 50 Hz | .no crash after 22 min

It looks likely fixed to me. Thanks.

**Comment by sirthias** [comment]
Excellent! Thanks again, Richard!
