### ISSUE TITLE
Document logic governing server-side connection closing

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17021]
and `Connection` header rendering.

Essentially we need to explain the logic driving this specification table:
https://github.com/akka/akka/pull/17020/files#diff-917a8a50814111f32d4174e73bffb813R370

**Comment by ktoso** [comment]
Yeah we should document it, closing connections is confusing people a lot recently

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
