### ISSUE TITLE
Create a "standard" forward actor available for tests

### ISSUE THREAD

**Issue by bambuchaAdm** [akka/akka#17023]
`TestActors.EchoActor` is great, but not only one which is very usefull in test. 

Forward actor is very usefull also. It would be nice if testkit would provide implementation of forward actor.

**Comment by ktoso** [comment]
Hi @bambuchaAdm, would you mind explaining your case in the issue as you explained to me in real life? That was more understandable (for the benefit of other hakkers) :-)

As I understood it, you want to have a `Props` available of something that is a test probe, so that you can test "an actor who starts children of given props"? I'm not sure you got you right, so let's look at your exact use case, thanks in advance!

**Comment by bambuchaAdm** [comment]
Hi. `ForwardActor` would be very useful in testing hierarchy of actors. Let's consider simple example actor which takes props of worker in constructor
```
class MasterActor(props: Props) extends Actor {

	  val worker = context.actorOf(props)

	  def receive = {
	  	  case Job => worker forward  Job
	  }
}
````
and now I want to write test to it. Because `TestProbe` and `TestKit` doesn't expose their actors and  they aren't extends Actor trait either I couldn't use `Props.apply( => A)`. I figure out that i can use simple actor which could forward received message to `TestKit` or `TestProbe`. 
```
class Forwarder(ref: ActorRef) extends Actor {
  override def receive: Receive = {
    case msg => ref forward msg
  }
}
```
at end test
```
class OptimaCommunicationSystemTest extends TestKit(ActorSystem("test")) with ImplicitSender with WordSpecLike with Matchers with BeforeAndAfterAll {
  override def afterAll: Unit = {
    TestKit.shutdownActorSystem(system)
  }
  
  val forwarderProps = Props(classOf[Forwarder], testActor)
  val materProps = Props(classOf[MasterActor], forwarderProps)

  "Master actor" must "delegate work to workers" in {
    val masterActor = system.actorOf(masterProps)
    master ! Job
    expectMsg(Job)
  }
}
```
And would be nice to have that `Forwarder` build in into test-kit like `EchoActor`.

**Comment by mehmeteking** [comment]
I actually felt the need for such an actor during tests, and decided to go on and implement as @bambuchaAdm suggested.

**Comment by ktoso** [comment]
Looks good! Would you mind submitting that commit as a pull request? Thanks!

**Comment by mehmeteking** [comment]
On which branch should I open the PR? Sorry, I am new :)

**Comment by drewhk** [comment]
I think master is fine

**Comment by ktoso** [comment]
Yeah on `master` please. 
The commit message is already according to our commit guidelines, thanks for reading those through! :-)

**Comment by mehmeteking** [comment]
Thanks for writing those documents in the first place :)
I opened the PR.

**Comment by ktoso** [comment]
Thanks! Let's do the review in the PR then :)

**Comment by patriknw** [comment]
Thank you @mehmeteking

**Comment by mehmeteking** [comment]
No, thank you all! This contribution is trivial, I hope to do more with your guidance :)

**Comment by ktoso** [comment]
Sounds good, looking forward to it! :)
