### ISSUE TITLE
ByteString performs too many copies on reasonably immutable data

### ISSUE THREAD

**Issue by colinrgodsey** [akka/akka#17028]
PR ~~#17069~~ offers some improvements to ByteString, mostly related to internal array copying. 
PR ~~#17144~~ has changes to allow serialization across all ByteStrings.
(previous PRs: ~~#17029~~, ~~#17070~~)

Relating to conversation here: 
https://groups.google.com/forum/#!topic/akka-dev/wgEe0ERrqVo

Assumptions
- A readonly ByteBuffer wrapper of internal Array in ByteString is safe as the underlying array is not accessible. 
- ~~It is faster to use a wrapped ByteBuffer with NIO directly (asByteBuffer) than copying it to a temporary buffer~~ https://gist.github.com/colinrgodsey/9bc606d09d035ba2334c
- ~~A ByteString(1) produced for a String should be able to hit NIO as a wrapped ByteBuffer with no array copies done besides the original generation of the Array from the String.~~
- It is faster to produce a ByteString1 from an IndexedSeq by copying the contents to a new Array instead of resizing the temp buffer in ByteStringBuilder (#17069)

Future Considerations
- Allow creation of sparse ByteString(1) from a _safe_ IndexedSeq (Vectors, etc if possible)
- Allow reading from an NIO channel directly with ByteString (0-copy read for known sizes, safe ByteString creation)
- Package-private base classes for possible extension under the _akka_ namespace

Other Observations
- Optimizations of TraversableOnce#copyToArray does expose the internal Array to potentially unsafe APIs extending TraversableOnce (existing)
- ~~No serialization for ByteString1, leaving ByteString (as an abstract class) not serializeable (#15170, #17070).~~

**Comment by colinrgodsey** [comment]
@rkuhn I was wondering if I could get some input on the 'other observations' towards the end there. 

I can see why ByteString1 isnt serializable (default ser would copy the entire underlying referenced array), but it could be possible with an (albeit messy) custom ser. As far as I can tell its only safe to send a compact ByteString over the wire, and this seems odd to me. Was wondering if there's some other reason for this im not seeing.

@ktoso hey again

**Comment by rkuhn** [comment]
We’re currently all traveling in preparation for ScalaDays, so our response latency might not be as good as we want it to be.

**Comment by colinrgodsey** [comment]
Woops, this was addressed a few years ago.
