### ISSUE TITLE
make OneBoundedInterpreter pausable/resumable

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17025]
Currently it can only sensibly be paused when the ball has exited at a BoundaryStage (which is implemented in ActorInterpreter). Once we implement more complex fusing we will want to limit the number of steps performed per actor invocation in order to retain the ability to get input elements or termination signals into it.

**Comment by hepin1989** [comment]
you are going to remove ```OneBoundedInterpreter``` in https://github.com/akka/akka/pull/18677,so this one is invalid right?

**Comment by drewhk** [comment]
Yes, this is correct

**Comment by drewhk** [comment]
will close after merged my PR

**Comment by drewhk** [comment]
done
