### ISSUE TITLE
Source.concat is difficult to use now that streams have the materialized type annotation

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#17039]
In HTTP 1.0-M4, all the HTTP body streams are of type `Source[ByteString, Unit]` 
(Why not `Source[ByteString, _]`?).

This means that the "concat" helper for Sources is difficult to use:

```
  def preamble: Source[ByteString, Unit] = ...
  def body: Source[ByteString, Unit] = ...
  def postamble: Source[ByteString, Unit] = ...

  val data = preamble ++ body ++ postamble

  val myResponse = HttpResponse(
    entity = HttpEntity.Chunked.fromData(contentType, data)
```

This used to work in 1.0-M3, but now I get
```
Error:(228, 43) type mismatch;
 found   : akka.stream.scaladsl.Source[akka.util.ByteString,((Unit, Unit), Unit)]
 required: akka.stream.scaladsl.Source[akka.util.ByteString,Unit]
```

What's the correct fix here?
Even `Keep.left` doesn't work, due to tuple wrapping (or something?)
```
    preamble 
      .concat(body).mapMaterialized(Keep.left[Unit,Unit])
      .concat(postamble).mapMaterialized(Keep.left[Unit,Unit])
```
gives:
```
Error:(229, 64) type mismatch;
 found   : (Unit, Unit) => Unit
 required: ((Unit, Unit)) => ?
      .concat(body).mapMaterialized(Keep.left[Unit,Unit])
                                                               ^
```

The only thing I can get to work is:
```
    preamble 
      .concat(body)
      .concat(postamble)
      .mapMaterialized(_ => ())
```
which feels clumsy.

 1. Is there a better way of using "++" or "concat" which avoids this issue, but which I missed?
 2. If not, does the DSL need rejigging so that "++" is nicer? Or is "++" expected to be rare?

Thanks,

Rich

**Comment by ktoso** [comment]
Thanks for reporting, sounds like something we could improve upon... we'll give it some thought!

**Comment by RichardBradley** [comment]
I've written a helper to work around this for now which looks like this:

```
  implicit def ignoreMaterializedValues[T](self: Source[T, _]): Source[T, Unit] =
    self.mapMaterialized(_ => ())
```

You could add something similar to the `Source` companion?

**Comment by rkuhn** [comment]
We should definitely fix all places where we consume graphs to not require Unit where we in fact ignore the materialized type. This should be rather easy since graphs are covariant in their materialized type, so using `Any` should work fine. Thanks for bringing this up!

**Comment by viktorklang** [comment]
Great point @rkuhn

**Comment by RichardBradley** [comment]
Thanks
