### ISSUE TITLE
no response to http request with akka-http 1.0-M4 

### ISSUE THREAD

**Issue by oliviercooper** [akka/akka#17034]
Hi,

I've just updated my code from 1.0-M2 to 1.0-M4 (ActorFlowMaterializer, Http().bindAndstartHandlingWith, ...).

Even with the TestServer from akka-http-tests (https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-M4/akka-http-tests/src/test/scala/akka/http/server/TestServer.scala), I don't have any response to my requests from browser (waiting for response ... indefinitely), same behaviour from postman tool.

In Debug level, I have only this in the eclipse console : 
[DEBUG] [03/12/2015 13:07:21.077] [main] [EventStream(akka://ServerTest)] logger log1-Logging$DefaultLogger started
[DEBUG] [03/12/2015 13:07:21.078] [main] [EventStream(akka://ServerTest)] Default Loggers started
Server online at http://localhost:8080/
Press RETURN to stop...
[DEBUG] [03/12/2015 13:07:21.871] [ServerTest-akka.actor.default-dispatcher-4] [akka://ServerTest/system/IO-TCP/selectors/$a/0] Successfully bound to /127.0.0.1:8080
[DEBUG] [03/12/2015 13:07:33.587] [ServerTest-akka.actor.default-dispatcher-4] [akka://ServerTest/system/IO-TCP/selectors/$a/0] New connection accepted

Any idea ?

Thanks
Oliver

**Comment by oliviercooper** [comment]
Ok #16972 gives the workaround : 

  //val bindingFuture = Http().bindAndstartHandlingWith({
  val myRoute=
    get {
      path("") {
        complete(index)
      } ~
        path("secure") {
          HttpBasicAuthentication("My very secure site")(auth) { user ⇒
            complete(<html><body>Hello <b>{ user }</b>. Access has been granted!</body></html>)
          }
        } ~
        path("ping") {
          complete("PONG!")
        } ~
        path("crash") {
          complete(sys.error("BOOM!"))
        }
    }
  //}, interface = "localhost", port = 8080)

  Http().bind(interface = "localhost", port = 8080 /* ... */ ).to(Sink.foreach { conn ⇒
    conn.flow.join(myRoute).run()
  }).run()

**Comment by ktoso** [comment]
Hi Oliver,
Thanks for reporting. You've bumped into a bug in bind and handle that we
have reported as https://github.com/akka/akka/issues/16972
It'll be fixed in the upcoming release.
