### ISSUE TITLE
using external ip address in akka-remoting

### ISSUE THREAD

**Issue by behrad** [akka/akka#17030]
I don't want to edit my `application.conf` on each node of my cluster and set `hostname` to the external ip of that machine, instead I expected this to work:

```scala
remote.netty.tcp {
//      hostname = "192.168.100.194"
      bind-hostname = "0.0.0.0"
      port = 2551
}
```

however I saw 
`Cluster Node [akka.tcp://adp@127.0.1.1:2551] - Started up successfully`
in my logs and node is not being able to be contacted via `adp@192.168.100.194`.

Is there any solution to this? this seems a typical scenario that one wants to deploy the same app on many nodes and they should cooperate with the external ip addresses, however we don't want to handle the per node based remoting ip addresses :)

**Comment by hepin1989** [comment]
it's apart of akka2.4
not 2.3

what's the adp protocal?apart of ArubaOS?

**Comment by behrad** [comment]
Can I easily upgrade to 2.4 on scala 2.10.4 or should I consider something @hepin1989 
Haven't read release notes yet :)

`adp` is simply my actor system name ;)

**Comment by hepin1989** [comment]
sorry .I mess it up with ```akka.adp//```
yes,you could upgrade the snapshort build.
https://github.com/akka/akka/blob/master/akka-remote/src/main/resources/reference.conf#L359

**Comment by 2m** [comment]
Closing as invalid, because the feature you requested is in upcoming Akka 2.4 version.
