### ISSUE TITLE
Add `Route` element

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17038]
I've come across the need for this element several times already, so here is the ticket for it:

We need a graph element with one input and >= 2 individually typed outputs, essentially with these signatures:

```scala
object Route {
  def apply[I, O0, O1](f: I => (Option[O0], Option[O1]))
    :Graph[FanOutShape2[I, O0, O1], Unit] = ...

  def apply[I, O0, O1, O2](f: I => (Option[O0], Option[O1], Option[O2]))
    :Graph[FanOutShape3[I, O0, O1, O2], Unit] = ...

  ...
}
```

This would allow me to easily route an `Either` into two different sub-streams like this:

```scala
Route[Either[A, B], A, B] {
  case Left(a) => Some(a) -> None
  case Right(b) => None -> Some(b)
}
```

Of course it'd be great if we could use HLists to abstract over the arity, but I guess this is out of the question.

For the either splitting a more restrictive variant that only ever lets me output to exactly one of the downstreams would suffice, but the proposal here is more powerful.

Demand management could work as follows:

1. Request(1) from upstream independently of demand from downstream.
2. Run `f` and determine which outputs need to receive an element.
3. Await demand from the respective outlets and output as soon as possible.
4. If all outlets have demanded and received their elements: goto (1)

/cc @jrudolph

**Comment by agolubev** [comment]
Is it something like unzipWithOption?

**Comment by rkuhn** [comment]
was done in #19176
