### ISSUE TITLE
More symmetry between StreamTcp and Http

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#17031]
I could ask why there's the "Stream" prefix for `StreamTcp` but not for "Http". More relevant, though, is the signature of the respective `outgoingConnection` methods: For TCP you have to provide (an ugly) `java.net.InetSocketAddress` whereas for HTTP you can simply specify host and port.

**Comment by drewhk** [comment]
Fair enough.

**Comment by ktoso** [comment]
AFAIR we decided to remove the `InetSocketAddress`, however do we want to do something about the `Stream` prefix?

To be consistent we either prefix both or none: `StreamTcp / StreamHttp` vs. `Tcp / Http` (my vote goes for prefixing).

**Comment by rkuhn** [comment]
fixing the InetSocketAddress is definitely good, concerning the “Stream” prefix: the thinking was that there is another Tcp extension which works differently, but maybe having different package names is already enough?

**Comment by hseeberger** [comment]
Different package names is certainly enough for my palate.
