### ISSUE TITLE
Router Actor of type Group crashes when an added routee stops

### ISSUE THREAD

**Issue by ummels** [akka/akka#17040]
When creating a router actor with e.g. the `RoundRoubinGroup` configuration and adding routees to it using the `AddRoutee` message, the router actor stars watching them for lifecycle changes, but does not handle the `Terminated(actor)` message sent by a routee on termination. This leads to a `DeathPactException` when the routee stops and subsequently the router actor's crash so that it does not route any new messages. Even when trying to remove the routee from the router inside the routee's `onStop` method, the exception still occurs since the `RemoveRoutee` message seems to arrive after the `Terminated(...)` message.

The following code demonstrates the problem:

```scala
class PingActor extends Actor with ActorLogging {
  def receive = {
    case msg: String => log.info(msg)
  }

  def onStop() = ApplicationMain.router ! RemoveRoutee(ActorRefRoutee(self))
}

val props = Props[PingActor]
val system = ActorSystem("MyActorSystem")
val actor1 = system.actorOf(props, "routee1")
val actor2 = system.actorOf(props, "routee2")
val router = system.actorOf(RoundRobinGroup(List("/user/routee1")).props(), "router")
router ! AddRoutee(ActorRefRoutee(actor2))
Thread.sleep(500)
router ! "ping"
system.stop(actor2)
Thread.sleep(500)
router ! "test"
Thread.sleep(500)
System.exit(0)
```

When running this program, an exception occurs after stopping `actor2` and the `test` message is not logged:

```
background log: info: Running com.example.ApplicationMain 
background log: info: 22:40:59.943 [MyActorSystem-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
background log: info: 22:41:00.478 [MyActorSystem-akka.actor.default-dispatcher-2] INFO  c.example.ApplicationMain$PingActor - ping
background log: info: 22:41:00.489 [MyActorSystem-akka.actor.default-dispatcher-2] ERROR akka.actor.OneForOneStrategy - Monitored actor [Actor[akka://MyActorSystem/user/routee2#-2006595686]] terminated
background log: info: akka.actor.DeathPactException: Monitored actor [Actor[akka://MyActorSystem/user/routee2#-2006595686]] terminated
```

This problem does not occur with actors of type Pool that do handle the `Terminated(...)` message, as can bee seen in [RoutedActorCell.scala](https://github.com/akka/akka/blob/8485cd2ebb46d2fba851c41c03e34436e498c005/akka-actor/src/main/scala/akka/routing/RoutedActorCell.scala#1L188).

**Comment by patriknw** [comment]
That is a good finding, and should indeed be fixed. However, a group is supposed to be used with `ActorSelectionRoutee`, not `ActorRefRoutee`. When using `ActorSelectionRoutee` it will not have this problem.
