### ISSUE TITLE
Akka actors are not scheduled for message handling by Java FJ pool with 1 thread on 8u40 

### ISSUE THREAD

**Issue by plokhotnyuk** [akka/akka#17045]
How to reproduce:
1. Install and check that JDK 8u40 is used (both $PATH and $JAVA_HOME should point to the same JDK):
`java -version`
`$JAVA_HOME/bin/java -version`
2. Clone following project and checkout configuration with CMS GC (with G1GC it much harder to reproduce):
`git clone https://github.com/plokhotnyuk/actors.git`
`git checkout 7c1465ab134f702822bebb815ed2063d9fcbcbbf`
3. Run benchmarks with Java FJ pool that sized to 1 thread, by following 
`mvn -B -Dbenchmark.poolSize=1 -Dbenchmark.executorServiceType=java-forkjoin-pool test`
4. See that it hangs in `Multi-producer sending` tests with Akka mailboxes.

Switching to older JDK (8u31 or older) or to FJ from Scala or Akka library fix the problem.
Hanging occurs in tests with other (non-Akka) actors and with 8u31 when latest jsr166.jar used in bootclasspath, so it seems that this bug should be fixed in JDK (JSR166 sources). 

I propose to add some warning to log or System.err when using of dispatcher that backed by latest versions of Java FJ pool is detected.

**Comment by plokhotnyuk** [comment]
I have found that changes which lead to hanging of tests was introduced in commit to JSR166 sources with comments "Overhaul throttling; other internal refactorings" (07.07.2014).
Both versions of `ForkJoinPool.java`, `ForkJoinTask.java` and `ForkJoinWorkerThread.java` before and after that commit are copied to `java-fjp` branch.

How to reproduce for JDK 8u31 or older updates:
1. Clone the project and checkout the branch:
`git clone https://github.com/plokhotnyuk/actors.git`
`git checkout java-fjp`
2. Run benchmarks with Java FJ pool that sized to 1 thread, by following 
mvn -B -Dbenchmark.poolSize=1 -Dbenchmark.executorServiceType=java-forkjoin-pool cletest
3. See hanging of `Single-producer sending` or `Multi-producer sending` tests.

**Comment by plokhotnyuk** [comment]
@viktorklang Now I see that initial proposition above to detect some how broken version of Java FJ pool is hard to implement because changes that was introduced in affected version are in private or package scope. Should I try to write minimal java test for that bug and publish it to JSR166 mailing list instead?

**Comment by plokhotnyuk** [comment]
Here is minimal Java code to reproduce missed submissions in Java FJ pool:
`import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.atomic.AtomicBoolean;

public class ForkJoinPoolTest {
    public static void main(String[] args) {
        ForkJoinPool e = new ForkJoinPool(1);
        AtomicBoolean b = new AtomicBoolean();
        final boolean[] bs = {false};
        for (int i = 0; i < 100000; i++) {
            bs[0] = true;
            e.execute(new Runnable() {
                @Override
                public void run() {
                    bs[0] = false;
                }
            });
            do {
                b.get();
            } while (bs[0]);
        }
        e.shutdown();
    }
}
`

**Comment by rkuhn** [comment]
Thanks a lot for the detective work, Andriy! Given that Akka itself does not provide the option to use the JDK’s FJP implementation I don’t see what we could do other than posting a news item that 8u40 is to be avoided for these purposes. WDYT?

**Comment by plokhotnyuk** [comment]
I posted my findings to JSR166 mailing list http://cs.oswego.edu/pipermail/concurrency-interest/2015-April/014240.html
And I hope for fast fix from them.

**Comment by viktorklang** [comment]
Nice catch, looking forward to a fix, and glad Akka doesn't suffer from this due to using the embedded Scala version of FJ

**Comment by plokhotnyuk** [comment]
I'm impressed by quick fix from Doug Lea: http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/concurrent/ForkJoinPool.java?r1=1.240&r2=1.241
It seems that this putOrderedInt intrinsic bug can affect any other code...

**Comment by viktorklang** [comment]
Great that it has been addressed already!

**Comment by rkuhn** [comment]
Closing: there seems to be nothing to do on our side.
