### ISSUE TITLE
DOC: obsolete "allowCycles" reference in the 1.0-M4 docs

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#17046]
The documentation for 1.0-M4 still [says](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M4/scala/stream-graphs.html)

```
 (the presence of cycles is enabled by calling allowCycles() on the builder).
```

but this method has been removed in 1.0-M4.

AFAICT, "allowCycles" is no longer needed, so this aside should just be deleted from the docs.

**Comment by patriknw** [comment]
thanks for reporting
