### ISSUE TITLE
DOC: Confusing example in Stream-IO documentation

### ISSUE THREAD

**Issue by reid-spencer** [akka/akka#17056]
The code example provided here:
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M4/scala/stream-io.html
is confusing because:
- It won't compile (duplicate definitions)
- Seems to be redundantly doing similar things
- Is missing symbols (what is a RecipeParseLines?)
- Is likely the result of a merge or change error

It took me a while to recognize that this wasn't just my inability to comprehend it.

**Comment by patriknw** [comment]
thanks for reporting

**Comment by ktoso** [comment]
Hi Reid, thanks for the feedback.
I'm not completely sure how to act it though as:

1) It's multiple chunks of code that are commented and explained in docs, each contains the section it is talking about, multiple parts talk about creating connections so they include such line. Making it `connections2` doesn't seem (to me) to address any problem.

2) Do you mean the server being implemented in 2 ways? It is explained in the docs why it is done so - in one case the server does not start sending data immediately, in the 2nd example it does.

3) It is explained and linked to where we take the recipe in the documentation right before this code snippet: `we use the parseLines
recipe from the :ref:`cookbook-parse-lines-scala` Akka Streams Cookbook recipe to chunk the inputs up into actual lines of text.`

Thanks for the feedback that it's current state causes confusion, we'll see to improve it, but I'm not sure about some of the points mentioned (see above).

**Comment by reid-spencer** [comment]
For clarity, I'm talking about the code in he section that has this URL:
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M4/scala/stream-io.html#Connecting__REPL_Client

i.e. the "Connecting__REPL_Client" anchor

I brought this up because it is one of the *main* hinderances to my understanding how to write a StreamTCP client. 

1) Separating the two examples with narrative would help the reader understand that we are looking at two different ways to do the same thing. When the examples are all mashed together, especially with consecutive line numbers, it gets difficult to recognize that the code ought to be considered as two separate compilation units. 

2) The example occurs in a section that is explaining a REPL *client*, not a server. I do not see the explanation you suggest is there (about sending data immediately). 

3) The snippet you quote comes from the section BEFORE the one I'm referencing. Please look for the anchor noted above and consider my comments relative to that section only. 

Thanks.

**Comment by johanandren** [comment]
Closing this as it is so old and I think the current docs are valid, please reopen or ping to reopen if you disagree.

Current docs: http://doc.akka.io/docs/akka/current/scala/stream/stream-io.html#connecting-repl-client
