### ISSUE TITLE
HTTP Client doesn't support "//" at the beginning or a URL path

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17064]
Akka HTTP equivalent of this ticket: https://github.com/spray/spray/issues/1019
All that's required is a forward-port of this PR: https://github.com/spray/spray/pull/1026

/cc @jrudolph

**Comment by wjur** [comment]
If this is only a forward-port and none of you is working on it then I can do it.

**Comment by sirthias** [comment]
Excellent! Thanks @wjur!
