### ISSUE TITLE
update Typesafe config to 1.3.0-M3

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17071]
from Havoc:

Here's what's new:
https://github.com/typesafehub/config/blob/master/NEWS.md#130-m1-march-6-2015

It probably makes sense to move current dev versions of akka and play
to this release and see if anything explodes. I would do a 1.3.0 final
before your projects go final, of course.

At this time all the open issues are feature requests or I couldn't
reproduce them. I don't know of anything that's broken. So if you find
anything let me know.

I think akka was implementing the `Config` interface, which has new
methods added, so it probably will not compile. `Config` is "sealed by
documentation" by the way since Java doesn't have sealed. :-)

However, the optimizations to path parsing in this release may mean
the caching you were doing isn't needed anymore. Details of those
optimizations are at https://github.com/typesafehub/config/issues/205
in case you feel like deleting code. I think even more optimization
could be possible but it's already fast so you will have to tell me if
it matters to you.

**Comment by hepin1989** [comment]
+1 for that.and maybe the cachedConfig is no longer needed

**Comment by hepin1989** [comment]
then it should be1.3.0-M2 :P

**Comment by rkuhn** [comment]
@patriknw This should be done soon as well.

**Comment by ktoso** [comment]
Requires minor changes in code on our side, I'll solve it

**Comment by patriknw** [comment]
Great, later we might want to try to remove the caching workaround. Havoc said that the new version might be fast enough. Please create a new ticket for that task.

**Comment by ktoso** [comment]
I checked if we need `CachingConfig` still, and yeah I think we do:

```
@Benchmark def deep_config  = deepConfig.hasPath(deepKey)
@Benchmark def deep_caching = deepCaching.hasPath(deepKey)

[info] Benchmark                                            Mode  Samples       Score  Score error   Units
[info] a.d.CachingConfigBenchmarkBenchmark.deep_caching    thrpt       40  146234.778     3638.332  ops/ms
[info] a.d.CachingConfigBenchmarkBenchmark.deep_config     thrpt       40    3165.616      140.646  ops/ms
```

**Comment by ktoso** [comment]
Should I create the ticket anyway, to revisit at some point in the future?

**Comment by patriknw** [comment]
awesome, if you have already checked we don't need a ticket
