### ISSUE TITLE
405 response message incorrect

### ISSUE THREAD

**Issue by pjrharley** [akka/akka#17082]
Using akka http routing, when you make a request with an unsupported message to an endpoint the error message reads:

HTTP method not allowed, supported methods: HttpMethod(GET)

Whereas it should just say:
HTTP method not allowed, supported methods: GET

Looks like an easy one - in akka-http/src/main/scala/akka/http/server/RejectionHandler.scala, it does:

"HTTP method not allowed, supported methods: " + methods.mkString(", ")

so I guess it needs a ".map(_.name)"

**Comment by sirthias** [comment]
Thanks for the report!
