### ISSUE TITLE
Memory leak with context.watch and pattern.ask involved

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#17087]
Hi guys,
Here is a simple example of use case when PromiseActorRef is leaking when get watched.

```scala
import akka.actor.{Actor, ActorSystem, Props, Terminated}
import akka.pattern.ask
import akka.util.Timeout
import scala.concurrent.duration._

object MemoryLeak extends App {
  val system = ActorSystem()
  val actor = system.actorOf(Props[MyActor])
  implicit val timeout = Timeout(3.seconds)
  while (true) {
    Thread.sleep(100)
    actor ? "Request"
  }
}

class MyActor extends Actor {
  def receive = {
    case Terminated(actor) => context unwatch actor
    case "Request"         =>
      val actor = sender()
      context.watch(actor)
      actor ! "Response"
  }
}
```

I can see two possible solutions: 
* `context.watch` should ignore `PromiseActorRef`
* Watchers should receive `Terminated`

**Comment by patriknw** [comment]
Thanks for reporting.

**Comment by ktoso** [comment]
Thanks for noticing there's something fishy going on here @t3hnar!
I've submited a fix https://github.com/akka/akka/pull/17102 and will also backport it to 2.3.

More details on the pull request, but in essence Terminated() was being triggered, but contained a wrong actor ref.
