### ISSUE TITLE
FAILED: NettyTransportSpec cannot bind to 127.0.1.1 on OS X

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17084]
Fails on my mac. I guess it is because 127.0.1.1 is not defined (as on linux).

    [info] - should bind to specified tcp address *** FAILED *** (2 milliseconds)
    [info]   java.net.BindException: Can't assign requested address
    [info]   at sun.nio.ch.Net.bind0(Native Method)
    [info]   at sun.nio.ch.Net.bind(Net.java:414)
    [info]   at sun.nio.ch.Net.bind(Net.java:406)
    [info]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    [info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    [info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
    [info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [info]   at java.lang.reflect.Method.invoke(Method.java:483)
    [info]   at akka.TestUtils$$anonfun$temporaryServerAddresses$2.apply(TestUtils.scala:34)
    [info]   at akka.TestUtils$$anonfun$temporaryServerAddresses$2.apply(TestUtils.scala:29)
    [info]   at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
    [info]   at akka.TestUtils$.temporaryServerAddresses(TestUtils.scala:29)
    [info]   at akka.TestUtils$.temporaryServerAddress(TestUtils.scala:26)
    [info]   at akka.remote.transport.netty.BindBehaviour$$anonfun$theOneWhoKnowsTheDifferenceBetweenBoundAndRemotingAddress$2.apply$mcV$sp(NettyTransportSpec.scala:148)
    [info]   at akka.remote.transport.netty.BindBehaviour$$anonfun$theOneWhoKnowsTheDifferenceBetweenBoundAndRemotingAddress$2.apply(NettyTransportSpec.scala:146)

**Comment by ktoso** [comment]
One solution would be to instruct mac users to add `ifconfig lo0 alias 127.0.1.1` (and others) to their scripts run at startup... do we consider this a solution?

**Comment by patriknw** [comment]
That can work for me, but we should not put extra burden on external contributors. If there is no other way we should make the test optional, i.e. not fail if 127.0.1.1 is undefined.

**Comment by 2m** [comment]
Can you `ping 127.0.0.2` in OSX?

**Comment by ktoso** [comment]
Sadly nope (unless you configure a loopback alias like shown above). OSX doesn't follow the idea or 127.x.x.x being localhost at all it seems (except 127.0.0.1 ofc).
