### ISSUE TITLE
akka-http support for PlayJson

### ISSUE THREAD

**Issue by mrkaspa** [akka/akka#17106]
In akka-http is there something similar to akka.http.marshallers.sprayjson.SprayJsonSupport._ but for the PlayJson Library?

**Comment by ktoso** [comment]
Hi @mrkaspa,
not currently, but it would be very simple to roll your own, take a look at how the spray traits look like: https://github.com/akka/akka/blob/release-2.3-dev/akka-http-marshallers/akka-http-spray-json/src/main/scala/akka/http/marshallers/sprayjson/SprayJsonSupport.scala#L39

My immediate feeling is that these support traits need not neccessarily live inside the akka/akka repository, what do you think @akka/akka-team?

**Comment by mrkaspa** [comment]
@ktoso I've done it, should i make a branch and a PR or do I create my own library?

**Comment by jrudolph** [comment]
We once decided to support these kinds of integrations each with a small module like the one for spray-json. There's a meta-ticket for adding more integration for json libraries at https://github.com/akka/akka/issues/15917

**Comment by hepin1989** [comment]
maybe like json4s?which have different backend

**Comment by mrkaspa** [comment]
I’ve forked and downloaded the akka repository on my mac, I’ve opened the project in Intellij. I’ve created a new scala module inside the akka-http-marshallers for the play json support but the imports fot the akka libraries don’t work, how can I fix this, and I have to add the the dependency to the play-json library where should it go?, thanks

**Comment by jrudolph** [comment]
@mrkaspa you need to add the project in the sbt build file first and then update IntelliJ with the changes (however you do that). See this commit https://github.com/akka/akka/commit/db3fc16f4cfedef1d815f1cb8ac27b1f16f61fab which introduced the spray-json support as a template.

**Comment by ktoso** [comment]
We have discussed this module in depth in the [https://github.com/akka/akka/pull/17387#issuecomment-99606569](discussion here [#17387]).

**Summary:** because of lifecycles of projects this module should best live outside of akka and play projects - in order to be able to keep up with either version update.

Closing and expecting @guillaumebreton to roll his library out soon! :-)
