### ISSUE TITLE
Akka git repository cannot be pushed to an empty repository

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17115]
This is a strange issue. I'm putting it here FTR but it seems there is no immediate solution available.

It seems the akka repository got corrupted early on in 2009. I.e. it contains some invalid trees that cannot be pushed:

```
> git push test origin/master
Counting objects: 182176, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (47566/47566), done.
remote: error: object 7e60023c9857597ca13ed0959faed7cdfd4e9c8a:contains zero-padded file modes
remote: fatal: Error in object
error: pack-objects died of signal 13
```

In fact, there are lots of those trees in a freshly checked-out repository:

```
> git fsck
Checking object directories: 100% (256/256), done.
warning in tree 7e60023c9857597ca13ed0959faed7cdfd4e9c8a: contains zero-padded file modes
warning in tree 080d4fcb6fb44f28f7e0c727edf8332814e72403: contains zero-padded file modes
warning in tree 874094e8828d2a395bab05434c102c6ce8423c61: contains zero-padded file modes
warning in tree 666dbcd46e18ab84d233a43da5fdeda98f35f654: contains zero-padded file modes
warning in tree e874e014c24babbeae474e12a5623682ae00cdf3: contains zero-padded file modes
warning in tree 6d202abdc9912cb147e43c47b497b3fff657326a: contains zero-padded file modes
warning in tree 3ee6a5a1c09e035aa42076e80d0362efc15f8efe: contains zero-padded file modes
warning in tree 4d6f187281ff2d1ae53678bbb296c45a5675b522: contains zero-padded file modes
warning in tree c0a79f9072254ddd64597e9f4f0a3cc74f922c2e: contains zero-padded file modes
warning in tree 32629bf9caa4411ed703d8f474de47c52f3706c8: contains zero-padded file modes
warning in tree 755b3fb061d9e9b9e80e81d5bdfd7e6cd70269b2: contains zero-padded file modes
warning in tree d5ec8641ea3ff7fdeb70e9c96f3eca995f97fd79: contains zero-padded file modes
warning in tree 6203c66c166a259e58da17ed1702ca3f6535050d: contains zero-padded file modes
warning in tree 659620e1b578638a0269978fee9bf1feb32ccedd: contains zero-padded file modes
warning in tree 538bdd34008c512a2ad19e06bf0a6a4c34f477ed: contains zero-padded file modes
warning in tree 894e664321cc6e718f0446e1019a0dfa598be79b: contains zero-padded file modes
warning in tree 822fb39e8eba8481d8a09fc367535c8820027ca5: contains zero-padded file modes
warning in tree c07a08c9ed3f140eb70780ada49e55394f7ceb8a: contains zero-padded file modes
warning in tree fb54b2ef17b730274101659aec469fe91d6fc558: contains zero-padded file modes
warning in tree 2991d8b4464e92af23b5435cc3dd6bfe55c94724: contains zero-padded file modes
warning in tree 862f5b78bf5cb62777a5571fb68f7c8b55832939: contains zero-padded file modes
warning in tree 84da903896254ccfc5768a4e35e56bc1f4387013: contains zero-padded file modes
warning in tree d9ffc1c44b3487547b49b4f2063fe99af9814df5: contains zero-padded file modes
warning in tree 6043feffbe70926b9932e69f3557efab11930dac: contains zero-padded file modes
warning in tree 6d91066b77232555dcccd15e41de63410dd12bc5: contains zero-padded file modes
warning in tree 8a44db3c49ff6645ca8f35261c5e9a4705c4798b: contains zero-padded file modes
warning in tree ba67af9d5278d1cff6f361fc1d7f7a13d0109efc: contains zero-padded file modes
warning in tree 189427f8cc52789e0ad1610404a7b4dabc976f7e: contains zero-padded file modes
warning in tree 1b30e4d7d30ff5b82b7c63ef17d580eb2d756e53: contains zero-padded file modes
warning in tree 66884066143c032bdca3b8ded784faafb3680116: contains zero-padded file modes
warning in tree adf73d0b941ca9972614ad22ad82f5f519e293e8: contains zero-padded file modes
warning in tree 1f9613812f2cc53ea075ac5c319512662829fe22: contains zero-padded file modes
```

All these trees seem to be part of the early history of the master branch. All the real "solutions" I found consisted of rewriting the complete history fixing the broken objects which is not an option here.

The only workaround I know is not trying to push into empty git repositories but to create the target repository by cloning from the original one (my use case was to create a private mirror of the Akka repository for backing up private branches). So, that's basically the same process as cloning the repository on github. It isn't possible, though, to create an empty (i.e. non-forked) repository on github or gitlab and push the current akka history into it.

**Comment by rkuhn** [comment]
This is very strange, I did exactly what you describe last year and it worked without any issues. Are you sure that you tried this on a fresh clone?

**Comment by jrudolph** [comment]
FTR: I don't mind closing this, but this is still broken (and cannot be fixed). Cloning the repository works but pushing into an empty repository fails.

**Comment by rkuhn** [comment]
I closed it since you didn’t reply: a few months ago I did just what you describe and it worked.

**Comment by rkuhn** [comment]
In any case, I don’t see a way to fix this since it seems to be due to github changing some things (how else could it have been pushed before?).

**Comment by alexeystrakh** [comment]
Have same issue while pushing mirrored repo to the empty repo. Any advises?

> remote: error: object xxx:contains zero-padded file modes
> remote: fatal: Error in object

**Comment by jrudolph** [comment]
@rkuhn AFAIU the problem was that at some point a long time ago a faulty (if interpreted strictly) client produced illegal tree objects with "zero-padded file modes". At some point git started to enforce its specs more strictly which leaves us in the position where the Akka commit history contains some illegal objects deep down in the history chain.

Since a while (it seems) the server checks for illegal objects if you want to push something into the repository. It currently doesn't seem to happen for cloning but if that should be changed as well at some point the consequences could be worse.

Since a while there's `git replace` which could help with things like that but AFAIU it would still require a rewrite of at least part of history so I'm not so sure it would be feasible.

**Comment by rkuhn** [comment]
Is it possible to figure out which commits exactly are affected? Are they ancestors of current master?

**Comment by jrudolph** [comment]
Yes, I just forgot how. You need to find commits that reference one of the above tree objects. And yes, they are ancestors, I checked it explicitly for one of the above and also otherwise they wouldn't be pushed.

**Comment by rkuhn** [comment]
Hmm, so the question is: how can we fix this without

* losing the history
* breaking all the things?

We cannot push the current contents into an “akka-backup” repo, so we would need to rename the repo, but then we’d have to migrate all the tickets to the cleaned-up clone. I think we’ll need professional help here …
