### ISSUE TITLE
Give a little bit of thought on "mat" abbreviation on method names.

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17123]
*I added this to RC1 because this might mean a larger API breakage*

Having abbreviation in method names is not a clean style, but "materialized" is too long to be practical in most of the DSL methods. So there are choices:

 - consistently use "mat" everywhere (this means mapMaterialized might need a rename to mapMat)
 - use the full name everywhere
 - or use additional tricks (whatever ideas you have)

I personally *slightly* lean towards "mat everywhere" since that is the least amount of work, and while it adds an initial cognitive burden to users, it is not hard to get used to that convention.

**Comment by patriknw** [comment]
I prefer to rename the type parameter to `M`. We don't use that letter for other things so it should be easy to learn.

**Comment by ktoso** [comment]
For method names I think I'd stay with `mapMat` and similar ones.

**Comment by patriknw** [comment]
Here are some of the names we use

`mapMaterialized`
`combineMat`
`[Mat]`
`andThenMat`
`atopMat`
`viaMat`
`matValue`
`joinMat`
`concatMat`
`toMat`

I don't have a strong opinion.

**Comment by viktorklang** [comment]
"Consistency is dog."

**Comment by rkuhn** [comment]
Okay, for consistency:

  * all operations whose primary purpose is something else (atop, via, join, etc.) we stick with the “Mat” suffix, which signifies that in addition to doing X we also care about the materialized value
  * operations that care about the materialized value itself as their primary concern shall use the full length name “materializedValue”, properly camel-cased according to context

Then it should be obvious what the difference is between `transformMat` (which will probably be added soon) and `mapMaterializedValue`. Thoughts / critique?

**Comment by viktorklang** [comment]
One thing that you may want to think about is autocompletes/autosuggest/IntelliSense, there's no way of filtering out one or the others when typing. If I want to see all things that does either, it's not really possible with the proposed structure. Perhaps this can be ignored, but it's something to keep in mind IMO, especially if there's going to be a "myriad" of permutations on the same type.

**Comment by rkuhn** [comment]
WDYM? The method names that are affected by this decision are all listed by Patrik above, what is the issue you see with those?

**Comment by viktorklang** [comment]
@rkuhn my point is if I type "flow.mat" do I get all the methods listed that does the same category of things with the mat, contrasted the "materializedValue". I.e. it would be nice to be able to "select" one of the categories by prefix. Not essential, but in my experience that helps users.

**Comment by drewhk** [comment]
I don't see any reason why someone would want to see mat*, since you always decide on the type of combinator first (.to/.join, etc), and then you decide whether you care about the materialized value or not.
