### ISSUE TITLE
http server blueprint is reused but cannot be

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17129]
The server blueprint currently isn't reusable but it actually is reused in `HttpExt.bind`. Because reusage isn't prevented currently this currently introduces hard to detect errors.

The short-term solution should be not to reuse the HTTP server blueprint.

In the long-term it should be attempted to make the server blueprint reusable. Currently this isn't possible because it needs to access the ActorRef of the token source for Expect 100 support but there's no way to access it currently (can hopefully be fixed when #16168 is implemented). So, the token source writes the ActorRef into a mutable volatile var that is shared over all connections (!). Currently, the cell is overwritten which each new materialization of the blueprint, i.e. Expect 100 support only works on the latest connection and can be disrupted by older connections also trying to use Expect 100 support.

Also, for similar reasons initial websocket support won't be reusable for now.

**Comment by sirthias** [comment]
Yes. Hopefully https://github.com/akka/akka/pull/17097 will be merged soon and we can fix this properly.
