### ISSUE TITLE
StringIndexOutOfBound Exception in TcpConnectionSpec when in none English env

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#17135]
this code will cause the StringIndexOutOfBound Exception when in none English env
https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/io/TcpConnectionSpec.scala#L73

like In when the result is returned as "拒绝连接"，then that it

so delete the substring?

**Comment by ktoso** [comment]
or `take(15)`, which won't NPE. Would you like to submit a PR for this?

**Comment by hepin1989** [comment]
okay.

**Comment by patriknw** [comment]
a note: it was not really related to the language, but it was wrong usage of substring, not capping the `endIndex` to the length of the string

**Comment by patriknw** [comment]
this bug should be backported to 2.3 in my opinion, I will do that
