### ISSUE TITLE
doc: clarify AtLeastOnceDelivery resiliency

### ISSUE THREAD

**Issue by Horusiath** [akka/akka#17139]
I've encountered a following problem - I'm saving an actor's undelivered messages during `postStop` to be able to recover from them when actor eventually restarts. I use default `LocalSnapshotStore` for persistence. Unfortunately it seems, that snapshot store responds for `LoadSnapshot` request from recovering actor just before it saves it's snapshot on the local file system. Therefore `LoadSnapshotResult` is empty and unconfirmed deliveries are forgotten until persistent actor will try to recover later.

Example, which exposes the problem: https://gist.github.com/Horusiath/bd00d33a130e4add2491
Just as you can see, *foo* message is unconfirmed, but it's stored in snapshot just before actor crashes. But then actor immediately restarts and receives an empty snapshot as a result (because it has not been saved yet). As result *foo* messages will not be confirmed until next program run.

I believe this is not a desired behavior. I don't know if this should be treat as a general issue or only the `LocalSnapshotStore` bug. If second one, my proposition is to extend a `loadAsync` method to first check if requested snapshot is not on the list of `saving` snapshots before reaching snapshots on local file system.

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by patriknw** [comment]
@ktoso @Horusiath saveSnaphot is an async operation and in this case the restart is quicker than completing the save and therefore the the snapshot is not loaded. I'm not sure if this usage of saveSnapshot should be encouraged. The example is not resilient for jvm crashes, anyway, and it is not using AtLeastOnceDelivery in the way we intended.

Your suggestion with including the `saving` in the result would require us to keep the snapshot data around also (as replacement for `load` for those that are in progress).

I'm on the fence what to do here. On one hand I can understand that it is somewhat expected to see "your own write", but on the other hand it feels wrong to grab it from memory. What if the save failed? Then you loaded something that will not load in next attempt.

**Comment by aprooks** [comment]
@patriknw what's the intended use of AtLeastOnceDelivery? Actually that's what I was trying to achieve by creating use case with snapshots

**Comment by Horusiath** [comment]
@ktoso @patriknw How about check list of pending writes on load snapshot request, and if matching snapshot metadata was found, set a continuation on associated write operation future (they need to be remembered this way), so that when it completes successfully, it becomes immediately loaded and send back as `LoadSnapshotResult`?

**Comment by patriknw** [comment]
@aprooks The difference in this example and the [documentation sample](http://doc.akka.io/docs/akka/2.3.9/scala/persistence.html#At-Least-Once_Delivery) is that we persist the intent of delivering the message: `persist(MsgSent(s))`. Same with confirmations: `persist(MsgConfirmed(deliveryId))`. That is not done with the snapshot based approach, which means that if the JVM crash the message is lost. 

Note that when the `persist` callback is invoked you know that this intent is durable and will be retried, and it is only then you can acknowledge to the first sender that you will take care of the request.

**Comment by patriknw** [comment]
@Horusiath That could work

**Comment by aprooks** [comment]
@patriknw I was confused by this one `The AtLeastOnceDelivery trait holds messages in memory until their successful delivery has been confirmed.`

**Comment by patriknw** [comment]
The resilient part comes from that you save the intent of delivering the message, by using `persist` method.
That intent will be replayed when starting up new JVM and thereby retried if it has not been confirmed.
Documentation of this aspect can definitely be improved.

**Comment by aprooks** [comment]
@patriknw thank you for your help. Persisting before making a call make a lot more sense than relying on snapshots
