### ISSUE TITLE
Change default materialization placeholder type from `Unit` to `Any`

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17132]

**Comment by ktoso** [comment]
Sounds like a duplicate of https://github.com/akka/akka/issues/17039 ? scheduled for this sprint already

**Comment by sirthias** [comment]
Ah, ok, thanks. I was looking for a ticket for this thing but couldn't find it.
I already have the change done, wanted to put in a PR and needed a ticket to hang it onto.
Should I ref this ticket or #17039 from the PR?

**Comment by ktoso** [comment]
Hm and then there's also https://github.com/akka/akka/issues/16933 which sounds more like what you're working on right now? Let's ref https://github.com/akka/akka/issues/16933 and close this one. 
We'll see about the concat one separately (though the issue is very related), sounds good?

**Comment by sirthias** [comment]
I have completed the change from `Unit` to `Any` for *akka-stream* as well as *akka-http*.
So I think we can close #16933 as well as #17039 with my PR. Let's continue the discussion [in the PR](https://github.com/akka/akka/pull/17133).
