### ISSUE TITLE
Akka-FSM stateTimeout ignores forMax Duration.Inf

### ISSUE THREAD

**Issue by folex** [akka/akka#17140]
Code to reproduce:

```scala
sealed trait State
import scala.concurrent.duration._
import akka.actor._

sealed trait Data
case object Initial extends State
case object Waiting extends State
case object Empty extends Data

class FSMActor extends LoggingFSM[State, Data] {
      startWith(Initial, Empty)
     
      when(Initial) {
        case Event("Wait", _) => goto(Waiting)
      }

      when(Waiting, stateTimeout = 5.seconds) {
        case Event("Message", _) => 
          println(self.path.name + " got message")
          stay() forMax (Duration.Inf)

        case Event(StateTimeout, _) => 
          println(self.path.name + " got StateTimeout :(")
          stay()
      }
}

val system = ActorSystem("system")
val fsm = system.actorOf(Props(new FSMActor), "fsm")
fsm ! "Wait"
fsm ! "Message"
```

Actor shouldn't receive `StateTimeout` message since `stay()` was called with `forMax(Duration.Inf)`.

Version is `2.4-SNAPSHOT`, bug appeared after update on Apr 02.

Related thread on akka-user: https://groups.google.com/forum/#!topic/akka-user/NsAoqPZ2Svo

**Comment by kevinmeredith** [comment]
Hi @ktoso, per Dr. Kuhn's comment (https://groups.google.com/forum/#!topic/akka-user/NsAoqPZ2Svo), this seems to be a no-fix. No?

/cc @folex

**Comment by ktoso** [comment]
I looked at this a bit more in detail and agree that this is unexpected behaviour. Roland's concerns were mostly about if we need to break compatibility to fix such edge-case when other workarounds would work just as well.

I was able to solve it without breaking source or binary compatibility though, so I think we'll resolve this issue properly, here's the PR: https://github.com/akka/akka/pull/17152 :-)
