### ISSUE TITLE
Isolate different materializations

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17143]
Currently we attach every stream actor to the supervisor actor of the materializer. Instead, I propose to create a child to this supervisor when materialize() is called, and attach all the actors belonging to that materialization to this child.

This will alow us to catch exceptions during materialization and before rethrowing them sending a PoisonPill to the sub-supervisor for this materialization run, which in turn will cleanup all the actors dangling there.

**Comment by rkuhn** [comment]
good point, that thought had crossed my mind as well (but didn’t make it to the surface—a.k.a. github), thanks for putting these two pieces together!

**Comment by viktorklang** [comment]
:+1:

**Comment by johanandren** [comment]
Is this still valid?

**Comment by drewhk** [comment]
Yes, it kind-of is. Although I think this is not that much useful in itself, more like paving the path towards full stream supervision. I think this can be safely closed anyway.

**Comment by johanandren** [comment]
Thanks for clarifying, closing for now then.
