### ISSUE TITLE
"Akka Persistence Samples with Scala" dependency issue

### ISSUE THREAD

**Issue by havocp** [akka/akka#17141]
Forwarding issue https://github.com/typesafehub/activator/issues/998

`com.typesafe.akka#akka-persistence-experimental_2.10;2.3-SNAPSHOT: not found`

**Comment by patriknw** [comment]
@odwrotnie thanks for reporting. I have re-published the template and it is now with correct 2.3.9 dependency.

**Comment by patriknw** [comment]
I have no clue how we ended up with 2.3-SNAPSHOT dependency in akka-sample-persistence-java and akka-sample-persistence-scala. I verified several of the other samples and they did not have this issue. The zip files for 2.3.9 that we use from the publish script were correct, i.e. with 2.3.9 dependencies.

Anyway, re-publishing solved it.
