### ISSUE TITLE
Resurrect constructor to create Flow from Sink and Source

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17145]
(or maybe I just couldn't find it but @rkuhn encouraged me to create a ticket).

**Comment by drewhk** [comment]
There isn't any right now, but it is easy to add.

**Comment by drewhk** [comment]
(added to RC1 due to its simplicity)

**Comment by drewhk** [comment]
This is invalid, there is already a wrap method.

**Comment by drewhk** [comment]
but the Java counterpart is missing

**Comment by jrudolph** [comment]
Maybe because it has already been merged?

**Comment by jrudolph** [comment]
And yes, the Java counterpart is missing.

**Comment by drewhk** [comment]
I fix this ticket in the scope of this, since exactly those method's signature will change: https://github.com/akka/akka/issues/17254

**Comment by drewhk** [comment]
Fixed
