### ISSUE TITLE
Performance with RARP is different from CARP when routers are used

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17171]
User reported here: https://groups.google.com/forum/#!topic/akka-user/xPHB5e_G0xI

It seems weird, at least it worth a look.

**Comment by jknight12882** [comment]
Here is a sample config I am using (with some corp info redacted)

    akka {
      actor {
        provider = "akka.remote.RemoteActorRefProvider"
    
        deployment {
          /db-router {
            router = round-robin-group
            routees.paths = ["akka.tcp://xxx@192.168.1.5:2552/user/db-engine"]
          }
    
          /nosql-router {
            router = round-robin-group
            routees.paths = ["akka.tcp://xxx@192.168.1.6:2552/user/nosql-engine"]
          }
    
          /publisher-router {
            router = round-robin-group
            routees.paths = ["akka.tcp://xxx@192.168.1.7:2552/user/publisher-engine"]
          }
        }
      }
    
      remote {
        netty.tcp {
          hostname = "192.168.1.4"
        }
      }
    }
    
    //akka {
    //  actor {
    //    provider = "akka.cluster.ClusterActorRefProvider"
    //
    //    deployment {
    //      /db-router {
    //        router = round-robin-group
    //        routees.paths = ["/user/db-engine"]
    //
    //        cluster {
    //          enabled = on
    //          allow-local-routees = off
    //          use-role = db
    //        }
    //      }
    //
    //      /nosql-router {
    //        router = round-robin-group
    //        routees.paths = ["/user/nosql-engine"]
    //
    //        cluster {
    //          enabled = on
    //          allow-local-routees = off
    //          use-role = nosql
    //        }
    //      }
    //
    //      /publisher-router {
    //        router = round-robin-group
    //        routees.paths = ["/user/publisher-engine"]
    //
    //        cluster {
    //          enabled = on
    //          allow-local-routees = off
    //          use-role = publisher
    //        }
    //      }
    //    }
    //  }
    //
    //  remote {
    //    netty.tcp {
    //      hostname = "192.168.1.4"
    //    }
    //  }
    //
    //  cluster {
    //    roles = [cce]
    //    seed-nodes = [
    //      "akka.tcp://xxx@192.168.1.5:2552",
    //      "akka.tcp://xxx@192.168.1.4:2552"
    //    ]
    //  }
    //}
