### ISSUE TITLE
FlexiRoute `defaultCompletionHandling` and `eagerClose` broken

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17173]
Currently both implementations neither propagate completion nor errors to downstream.
They should do what the scaladoc already (correctly) says:

> Error or completion from upstream are immediately propagated.

**Comment by patriknw** [comment]
sounds bad, thanks for finding

**Comment by patriknw** [comment]
@sirthias Doesn't the following this case cover that scenario https://github.com/akka/akka/blob/release-2.3-dev/akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphFlexiRouteSpec.scala#L360 ?

There is also one for the error https://github.com/akka/akka/blob/release-2.3-dev/akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphFlexiRouteSpec.scala#L379

**Comment by sirthias** [comment]
Well, then it looks like something is not quite right in this test's infrastructure.
Because [the current implementation](https://github.com/akka/akka/blob/35eb3ffe2273a9b5580a87015dd0d251bd407de9/akka-stream/src/main/scala/akka/stream/scaladsl/FlexiRoute.scala#L158-L159) clearly doesn't propagate completion or errors.

**Comment by patriknw** [comment]
It is completed here: https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/impl/FlexiRouteImpl.scala#L51

The scaladoc is wrong. Leftover from refactoring.

**Comment by jrudolph** [comment]
So, what is the actual behavior?

**Comment by patriknw** [comment]
It will always propagate completion and error from upstream. It's not optional as it was in some early implementation. So the scaladoc is not wrong, just misplaced.

**Comment by patriknw** [comment]
I have clarified the scaladoc: https://github.com/akka/akka/pull/17192
