### ISSUE TITLE
Provide SimpleSender UDP Sink

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17185]
I needed this in another project, and seems it should be universally useful as well, so PRing here.
Typical use case would be just dumping statistics or logs to some udp address for collection.

It's just the unconnected "simple sender" version. We could/should also provide the Connected one if we think it's valuable (maybe then as `udp(target, connected = true)`?).

**Comment by ktoso** [comment]
Work on this ticket has been stashed (until we ship RC1). It's final resolution will contain more than just a simple Sink.

**Comment by drewhk** [comment]
Please find the stashed attempt in the closed PR.

**Comment by NeQuissimus** [comment]
Is there any new info / progress on this?

**Comment by ktoso** [comment]
We'd be happy to take a contribution for it, you could base it on my old PR which is linked here.

**Comment by NeQuissimus** [comment]
Thanks for the quick response. I may give it a shot, just started digging into Akka Streams.

**Comment by radekg** [comment]
Seems like some help would be welcomed here. How can I help then?

**Comment by patriknw** [comment]
@radekg that would be awesome. I think this should be added to Alpakka https://github.com/akka/alpakka

**Comment by NeQuissimus** [comment]
@radekg Please do :) I had intended to do this but have been pulled in other directions... Take a look at the commit to my Akka fork above, which is based on @ktoso's work. It may give you a good place to start.

**Comment by radekg** [comment]
I'll have a go at the first part over the coming weekend. 👍

**Comment by radekg** [comment]
It's been a busy couple of weeks. I hope to have a first swipe ready for Monday, 3rd of April.

**Comment by ktoso** [comment]
Would be nice, thanks :)

**Comment by radekg** [comment]
@ktoso apologies for the delay once again, paid work 🙄
Did a very simple draft of a sink here, not sure if it works but generally looking for a feedback if the direction is okay: https://github.com/radekg/alpakka/commit/525cbeb4332f2e36cee05a0812a48d6fadaf9a2a#diff-6a5622f155a9302eacdc2aa8cc67826fR1
If the direction is okay, I'll progress with packaging it all nicely, scaladoc, tests and such.

**Comment by ktoso** [comment]
Hi @radekg, please submit a PR :) I would have almost lost this ping already, and will be offline for a bit now. Someone else could review it this week perhaps. If not, I'll get to it later :)

Thanks for your efforts!

**Comment by gortiz** [comment]
Hi there!

It seems that PR has been never made, right?

**Comment by ktoso** [comment]
It would seem so, yes. If you'd like to take it over please do!

**Comment by 2m** [comment]
UDP connector is now a part of Alpakka since `0.20`: https://developer.lightbend.com/docs/alpakka/current/udp.html
