### ISSUE TITLE
Replace errorLogger in HTTP by using built in log() stage

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17184]
Since we now have built in logging, see https://github.com/akka/akka/pull/17162

It would now also be possible to replace the custom errorLogger HTTP uses, like this: https://github.com/ktoso/akka/commit/4fbb610b02c3b10c6afe76de541f53a8f7143ad0

Using `ZeroLevel` to avoid slowing down the normal pass-elements-through case would be advised ofc.

**Comment by miciek** [comment]
@ktoso Is this still relevant? Where is the `errorLogger` used?

**Comment by ktoso** [comment]
Good catch, AFAICS this can be closed now. 
We have an errorLogger stage but it's using the passed in logger correctly.

If you want to help out a bit there's a nice low hanging fruit in that area though:
The usage of transform+pushstage in: https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L251
and https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/util/package.scala#L92 
should be rewritten to be a `GraphStage`, let me know if you'd like to fix that :-)

**Comment by ktoso** [comment]
I made it a separate ticket https://github.com/akka/akka/issues/19899
