### ISSUE TITLE
Make jackson marshallers adapt Jackson's best practices

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17181]
From https://groups.google.com/d/topic/akka-dev/rTuiiNFr_ZM/discussion

> a new ObjectMapper is allocated on each call, which goes against a jackson best practice (and will degrade performance).
It also doesn't allow the outside user to tweak with Jackson configuration comfortably (e.g. we use the mapper to globally disable the inclusion of non default values for documents that are about to be stored in the DB).

**Comment by ktoso** [comment]
Closing, we now share one mapper across all marshalling calls
