### ISSUE TITLE
Attempt cleaning of DirectByteBuffer iso relying on GC of native mem

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#17194]
http://stackoverflow.com/questions/1854398/how-to-garbage-collect-a-direct-buffer-java

apply to https://github.com/akka/akka/blob/release-2.3-dev/akka-actor/src/main/scala/akka/io/DirectByteBufferPool.scala

**Comment by jrudolph** [comment]
WDYM? 

As there's no specified way of securely releasing a direct buffer the only way is relying on GC.

The pool will only over-allocate buffers( which later need to be GC'd) if the system is under serious load (i.e. for Akka IO more concurrent IO is going on than the size of the pool). If your application needs to live under those conditions you need to tweak settings anyway.

**Comment by viktorklang** [comment]
@jrudolph The point is that under high load it will generate garbage that lives in a more limited heap and takes longer to free—exactly conditions that are suboptimal. Having a means of -trying- to do it more reliably can't be bad?

**Comment by jrudolph** [comment]
@viktorklang Fair enough. What remains would be a trade-off where instantly deallocating the buffer would introduce even more work under high load but which admittedly is the safer and more predictable solution (because it is less likely to OOM fatally), against a more fundamental solution which would entail sizing the pool appropriately to the expected load.

**Comment by viktorklang** [comment]
@jrudolph Under ideal circumstances it would adaptively resize itself to a local optimum, but statically sizing the pool seems to require a "total view", which can be hard for developers and possibly impossible for Ops. I am of course open to alternative solutions, the one outlined in the Issue seems to be quite unintrusive / easy to reason about.

**Comment by jrudolph** [comment]
Yes, I think I can agree on that. 

To clarify: the outlined solution in SO is trying to use `sun.misc.Cleaner` reflectively to clean a direct buffer instead of just dropping the reference.

**Comment by viktorklang** [comment]
Affirmative

**Comment by hepin1989** [comment]
https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/Cleaner0.java for direct and https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L415 for unsafe
