### ISSUE TITLE
Secure cookie deprecated?

### ISSUE THREAD

**Issue by Lasering** [akka/akka#17197]
The [reference.conf for the akka-remote](https://github.com/akka/akka/blob/master/akka-remote/src/main/resources/reference.conf) states:
```
akka {
  remote {
    # Deprecated since 2.4-M1
    secure-cookie = ""
  }
}
```

However, I can't find anywhere in the code the reason for this deprecation, nor which alternative to use?

**Comment by patriknw** [comment]
It was decided in https://github.com/akka/akka/pull/16530
