### ISSUE TITLE
Clarify behavior of prefixAndTail wrt errors

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17203]
The question is whether the error is both signaled on the substream and on the main stream (I guess so) but it isn't in the Scaladocs nor in the tests (which only check that it is signaled on the substream).

/cc @sirthias

**Comment by jrudolph** [comment]
Also, maybe the Scaladoc could be improved which currently says "Takes up to `n` elements from the stream" which sounds as if the actual number of elements could be any arbitrary number smaller than `n` but will only be for the last substream.

**Comment by drewhk** [comment]
It is in the test, but not in the docs.

**Comment by drewhk** [comment]
well, either the main stream signals error, but then there is no substream yet, or the substream errors, but in that case the main already completed. I add this to the doc.
