### ISSUE TITLE
doc: clarify how attributes are used

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17233]
E.g.

    .map(identity).named("first").withAttributes(ActorOperationAttributes.dispatcher("disp1"))
    .map(identity).named("second").withAttributes(ActorOperationAttributes.dispatcher("disp2"))

as expected disp1 is used for the first map stage and disp2 is used for the second

but

    .map(identity).named("first")
    .map(identity).named("second").withAttributes(ActorOperationAttributes.dispatcher("disp2"))

then disp2 is used for both the first and the second map stages, which I did not find completely intuitive

**Comment by drewhk** [comment]
Superceded by ticket: https://github.com/akka/akka/issues/17337
