### ISSUE TITLE
Buffer / Window Flow

### ISSUE THREAD

**Issue by sirinath** [akka/akka#17236]
Like ZipWith is it possible equivalent to deal with buffers and windows.

**Comment by sirinath** [comment]
This would be similar to Buffer and Window in Rx

**Comment by drewhk** [comment]
Can you explain in a little more detail what these should look like?

**Comment by sirinath** [comment]
Buffer - takes n items at a time and pass this to a function n
Window - takes a moving window of n items and pass this to a function n

**Comment by drewhk** [comment]
these can be implemented with custom stages right now. We will see if we want to provide these out-of-the-box or not.

**Comment by sirinath** [comment]
Out of the box is more convenient.

**Comment by drewhk** [comment]
Yes, but we don't want to follow RX in providing a huge number of combinators, only a subset and extensible behavior. Users can build and share their libraries of useful combinators as separate projects.

**Comment by adamw** [comment]
+1 for a `sliding` combinator. I agree that it's probably a good idea not too have too many combinators but a basic subset corresponding where possible to the Scala collections API would be definitely good to have without the need for another library.

**Comment by drewhk** [comment]
So our approach is to first stash these requests, then write a cookbook entry to point people in the right direction, then if pressure is still high enough, we package it in the official library ;)

**Comment by drewhk** [comment]
the buffer is btw just a simple grouped(N).map (or mapConcat) but for window you currently need to write a stage.

**Comment by adamw** [comment]
I'm providing the forward-pressure then ;-)

**Comment by drewhk** [comment]
yes, noted :)

**Comment by sirinath** [comment]
I am right behind you Adam in the pressure department :-)

**Comment by sirinath** [comment]
Is it possible to consider this for 1.0?

**Comment by rkuhn** [comment]
we have FlowOps.sliding now
