### ISSUE TITLE
Loop Back Sink and Source

### ISSUE THREAD

**Issue by sirinath** [akka/akka#17235]
It it possible to have a loop back construct which takes N items from sink and feeds it back to the source which takes M items in addition to the loop back items. 

The loop back will have to have a identity to distinguish between different loop back points.

**Comment by rkuhn** [comment]
You can create loops in your graphs already, just use Broadcast and Merge junctions; Concat can also work depending on your use-case but make sure to add a buffer into the cycle that is big enough to hold the “first round” of elements.

**Comment by sirinath** [comment]
What I had in mind was Zip / ZipWith like functionality you carate a tuple / pass in as parameters to a function with N new and M old values. 

Something when calculating a filter with N input history and N past values.

**Comment by drewhk** [comment]
You can already use transform() and a custom stage to do windowed filtering etc.
