### ISSUE TITLE
Think about VirtualPublisher.realPublisher nulling

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17245]
When fixing memory leak in prefixAndTail (and friends) the realPublisher field of VirtualPublisher was cleared to break the references to the subscriber when subscription is cancelled.

`X -> V -> P -> S`

X is user code. V is the VirtualPublisher, P is the MultiStreamOutputProcessor$SubstreamOutput publisher, and S is the Subscriber. 

Some concerns were raised about the introduced marker interface `SupportingMultipleSubscribers`.

It will remove the multi-subscribe support from a thirdPartyPublisher in`Source(thirdPartyPublisher).runWith(Sink.publisher)`.

It would be possible to turn the marker interface the other way around.

On the other hand one could argue that Sink.publisher must always return a single-subscription publisher to avoid surprises. We have even documented it as "can handle one [[org.reactivestreams.Subscriber]]".

Without the `SupportingMultipleSubscribers ` marker the following tests will fail:

* Failed Source must emit error immediately
* Empty Source must complete immediately
* Singleton Source must produce elements to later subscriber
* A Flow based on a Future must produce elements with multiple subscribers
* A Flow based on a Future must produce elements to later subscriber
* A Flow based on a Future must allow cancel before receiving element

**Comment by rkuhn** [comment]
This ticket can probably be closed again, or are there open questions remaining?

**Comment by drewhk** [comment]
Nope, slay it!

**Comment by patriknw** [comment]
done
