### ISSUE TITLE
java.io.Serializer should not supercede a customer serializer.

### ISSUE THREAD

**Issue by rcoh** [akka/akka#17252]
I recently ran into a pretty surprising behavior in akka serialization -- if your parent class does not inherit from java.io.Serializable, akka will choose arbitrarily between the two! This "feature" is [documented](http://www.google.com/url?q=http%3A%2F%2Fdoc.akka.io%2Fdocs%2Fakka%2Fsnapshot%2Fscala%2Fserialization.html&sa=D&sntz=1&usg=AFQjCNFgyjhi3OzqGto9cCwHMknWkhxFtA) but it's pretty odd, and definitely not what I would expect as a user. `Product` in scala implements java.io.Serializable leading to the conflict. The current behavior is a warning message about the conflict.

A much more reasonable behavior seems like it would be always picking a user defined serializer if appropriate and falling back on Serializable only if no user defined serializers match. It's very counterintuitive that to _disable_ the java serializers, you must inherit from them. The random choice behavior seems like the right thing to do if two user defined serializers both apply.

**Comment by patriknw** [comment]
thanks

**Comment by patriknw** [comment]
We need to discuss the exact solution more, but the problem is interesting.

**Comment by rcavalcanti** [comment]
We have a similar issue in Lagom (https://github.com/lagom/lagom/issues/786). 

Lagom offers the possibility to define serialisers build from play-json serializers (you guys probably not how it works). 

It turns out that if we have a `Format` for a base trait, akka will give precedence to java serializer because a trait doesn't not implement `java.io. Serializable`.

```
sealed trait UserEvent
case class UserUpdatedEvt(...) extends UserEvent
object UserEvent {
  implicit val format: Format[UserEvent] = new Format[UserEvent] {
    override def reads(json: JsValue): JsResult[UserEvent] = // omitted for conciseness
    override def writes(o: UserEvent): JsValue = // omitted for conciseness
  }
}

object UserSerializerRegistry extends JsonSerializerRegistry {
  override def serializers: Seq[JsonSerializer[_]] = Seq(
    JsonSerializer[UserEvent]
  )
}

```
When attempting to persist an Event, we get:
```
[warn] a.s.Serialization(akka://account-service-impl-application) - Multiple serializers found for class com.account.impl.UserUpdatedEvt, choosing first: Vector((interface java.io.Serializable,akka.serialization.JavaSerializer@36a7e601), (interface com.account.impl.UserEvent,com.lightbend.lagom.scaladsl.playjson.PlayJsonSerializer@73a57eb1
[warn] a.s.Serialization(akka://account-service-impl-application) - Using the default Java serializer for class [com.account.impl.UserUpdatedEvt] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
```

**Comment by rcavalcanti** [comment]
Would it be a good solution to simply give lower priority to `JavaSerializer`? 

Obviously, if there is a conflict between two user defined serializers, we have no other option then emit a warning and pick the first one. But since everybody agrees that `JavaSerializer` should be avoided, we could at least use it as last resort. 
(which means never in case of conflict)

**Comment by rcavalcanti** [comment]
Hmm, that would break backward compatibility. Damm!

**Comment by crfeliz** [comment]
@rcavalcanti You're right. It would seems that having the user's base traits extend serializable (in lagom via Jsonable) is the only short term solution to this.

I do find one thing kind of worrisome about this issue: the warning that alerts the user that java serialization is being used only happens once per entity type (entity meaning the object being serialized). If the user went through the process of configuring serializers for classes which do not extend Serializable it is entirely possible that the warning goes unnoticed and their service continues using java-serialization indefinitely. Its also possible that a user might see the warning - try again - see that there is no warning - and then incorrectly conclude that akka didn't pick up their custom serializer until after the first message. The potential to miss or misinterpret these logs is especially true for scala/akka new-comers that may still be getting used to the generally verbose logging produced by the scala compiler, akka, etc.

**Comment by patriknw** [comment]
What we could do is to add another setting:
```
make-java-serialization-least-specific = off
```
and when that is enabled JavaSerializer is treated as least specific for those cases. We must keep the old behavior in Akka for backwards compatibility (at least in patch 2.5.x releases).

**Comment by patriknw** [comment]
btw, naming can be better

**Comment by patriknw** [comment]
@renatocaval I got around implementing this, see https://github.com/akka/akka/pull/24002

**Comment by renatocaval** [comment]
Ah great! I have completely forgotten this one. 
Thanks!
