### ISSUE TITLE
Provide JDK7 AsynchronousFileChannel backed FileSource/Sink

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17269]
As follow up to https://github.com/akka/akka/pull/17211#issuecomment-95279417 and [#15588 - streams: Provide basic streams for files and from InputStream etc.](https://github.com/akka/akka/issues/15588).

We will want to re-visit SynchronousFileSource and SynchronousFileSink and possibly reimplement using AsynchronousFileChannel (it won't necessarily be faster).

We also want to re-visit `SynchronousFileSource`, about:
- can we reimplement it as a stage (yes we can, but:) and it will be fused (needs fusing API exposed nicer to user land, so that users can put fuse blocks etc)
- do we need to read-ahead? if yes can we read-ahead better? (see here for a [discussion on read-ahead](https://github.com/akka/akka/pull/17211#discussion_r28886575))
- compare perf with asyncchanel based (I remember the async one getting to almost the same perf as synchronous)

**Comment by zaharidichev** [comment]
@ktoso I would like to give that one a shot if its free to grab. I wonder however, if benchmarking does not show any significant improvement, what is the rationale for moving to asynchronous channel ?

**Comment by zaharidichev** [comment]
@ktoso I would like to give that one a shot if its free to grab. I wonder however, if benchmarking does not show any significant improvement, what is the rationale for moving to asynchronous channel ?

**Comment by johanandren** [comment]
For reference: PR exploring this #21801

**Comment by ktoso** [comment]
Here it's most important to think and confirm if there are gains from the rewrite or not.
The blocking one will likely have (as found in the other PR) better raw throughput, but then we end up putting it on the IO dispatcher. The async one could remain on the default dispatcher perhaps (?). So another question is about the scalability - what happens if we write to 1000 files at the same time, which impl does better then?

**Comment by ktoso** [comment]
This is being worked on by @agolubev

**Comment by agolubev** [comment]
There is almost a decision to close this PR and stay with sync approach https://github.com/akka/akka/pull/21801 as there is similar performance (sync and async) but async is limited with regards to thread pool configuration (which will be external to Akka).
Ref: https://github.com/akka/akka/pull/23217#issuecomment-323351104

**Comment by ktoso** [comment]
AFAIR we should close this as we went with https://github.com/akka/akka/pull/21801 after tons of benchmarking
