### ISSUE TITLE
Make ForkJoinPool asyncMode configurable

### ISSUE THREAD

**Issue by richdougherty** [akka/akka#17274]
The [`asyncMode` argument in the `ForkJoinPool` constructor](https://github.com/scala/scala/blob/77437ffa521a6d1b073283624a722848a8c0b33c/src/forkjoin/scala/concurrent/forkjoin/ForkJoinPool.java#L2852-L2857) switches the pool between LIFO and FIFO scheduling. The JRE/Scala default is FIFO (`asyncMode = false`) and [Akka's default is LIFO](https://github.com/akka/akka/blob/00f6a58e7c1e4795ad8920745c01916cc26947ca/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala#L379) (`asyncMode = true`).

I've [switched](https://github.com/playframework/playframework/pull/4278) to use FIFO scheduling in Play, but the value isn't configurable through Akka's configuration, so I needed to [implement](https://github.com/playframework/playframework/pull/4278/files) a custom configurator. It would be great if Akka itself made the `asyncMode` option configurable via a normal setting. E.g.

```
fork-join-executor {
  ...
  async-mode = true
  ...
}
```

**Comment by drewhk** [comment]
Hmm, I didn't know this setting exists. It would be interesting to see how
streams behave performance wise when LIFO or FIFO is used or if they are
sensitive to it at all.

-Endre

**Comment by hepin1989** [comment]
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala#L379

**Comment by richdougherty** [comment]
@drewhk, yes this setting may have an effect on stream behaviour. It would be good to make it configurable so we can experiment with different settings for different workloads.

**Comment by patriknw** [comment]
sounds interesting

**Comment by hepin1989** [comment]
in fact ``` asyncMode ? FIFO_QUEUE : LIFO_QUEUE``` so I think @richdougherty 's comment is wrong.
and akka's default is true so will be FIFO_QUEUE and JDK is false will be LIFO_QUEUE

**Comment by drewhk** [comment]
yes, thanks for clarifying. would be interesting to see what happens when we change the value.

**Comment by richdougherty** [comment]
@hepin1989, you're right, I got the terms FIFO and LIFO backwards. I wanted to use the JRE default of `false` to get stack (LIFO) scheduling since it should make scheduling cheaper, at the risk of starvation in some cases. It should work well for Play's sequential task-oriented code. Akka uses queue (FIFO) scheduling by default.

**Comment by hepin1989** [comment]
@richdougherty in fact netty is using this way.LIFO,you could check the code.

**Comment by richdougherty** [comment]
LIFO is a pretty good choice for Netty/Play style applications.

**Comment by drewhk** [comment]
It might also work with streams since there is no risk of starvation due to the backpressure channel

**Comment by richdougherty** [comment]
Thanks guys!
