### ISSUE TITLE
Previously quarantined restarted system cannot connect immediately

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17271]
Found here: https://github.com/akka/akka/pull/17263/files#r28882146

First message is not lost, just very delayed.

It seems like there must first be a transport failure detector timeout, that triggers "No response from remote. Handshake timed out or transport failure detector triggered"

**Comment by drewhk** [comment]
This is an interesting twist.

**Comment by patriknw** [comment]
perhaps we should mark it as bug?

**Comment by drewhk** [comment]
Yes, thanks

**Comment by patriknw** [comment]
I think this failure is related to this issue: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2564/consoleFull

**Comment by drewhk** [comment]
So far, I only found that in the error case the non-restarted system thinks it has a writer, and tries to use that, to send messages (which ends up in the void) while it does not yet dispatch messages for the incoming read connection from the restarted system  (but it accepted the TCP connection).

 I guess it is the funky handoff code again.

**Comment by drewhk** [comment]
Meh, I still don't know what the issue is. I put it back for today.

**Comment by patriknw** [comment]
if we find the reason for this it should probably be backported, but setting the milestone to 2.4.x for now

**Comment by patriknw** [comment]
hm, with the available information I don't see how we can find this problem
