### ISSUE TITLE
Websocket Client Side API

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17275]
Subticket of #16848 to add client-side websocket support. The existing (#17248) websocket implementation can be completely be used with the client-side of the handshake and the actual API still missing.

**Comment by fommil** [comment]
this one is rather important for testing a websocket server, if nothing else

**Comment by jrudolph** [comment]
I think for testing it would suffice if you could access the registered websocket handler Flow to test it without going through the network. This would be consistent with the rest of testing which also doesn't involve parsing / networking / rendering.

**Comment by fommil** [comment]
@jrudolph I like to have a small sample of tests on the actual socket as well. It does catch things.

**Comment by jrudolph** [comment]
I don't object. There will be client-side websocket support but we will add better support for testing Websocket routes to the testkit before that. I created https://github.com/akka/akka/issues/17914 to track this.

**Comment by jrudolph** [comment]
Slowly getting there:

![screenshot from 2015-09-29 15 22 49](https://cloud.githubusercontent.com/assets/9868/10165155/fa68a316-66bd-11e5-8545-0e4d49ce15df.png)

**Comment by ktoso** [comment]
Awesome, thanks for the status update :+1: Almost there now.. :-)

**Comment by spangaer** [comment]
At the risk of coming across inpatient, any idea when you'd submit something?
I'm currently looking at building an http reverse proxy on top of akka http. For allowing WebSocket forwarding, having a client API seems like the shortest road to success (might not be the cleanest). I was just starting to think about what I would need to break open to get it to work when your update came along.

**Comment by ktoso** [comment]
Hi @jrudolph, what's the status here - much work still needed to get it over the finish line?

FYI we're planning a `1.1` release end of this week, it's mostly in order to ship all the things that we've fixed since `1.0`. The next release will merge with Akka 2.4 and thus require JDK8+.

**Comment by jrudolph** [comment]
Thanks, @ktoso. Good to know, I'll try to get it in at least in a first version.

**Comment by ktoso** [comment]
Would be great, thanks!

**Comment by spangaer** [comment]
FYI, checked out your branch and used it in reverse proxy via:
UpgradeToWebsocket.handleMessages(Http().websocketClientFlow(...)) and it works like a charm.
(technically it's a bit more complex as I replicate the websocketClientFlow via websocketClientLayer and so on so I can separately connection address from URI, so I'm grateful that those calls are public)

I tried to do something myself that would allow generic upgrade through the reverse proxy, with late binding ByteString streams, but that didn't really fly. Proxying at the message level also has advantages though, e.g. allows injecting messages.

**Comment by jrudolph** [comment]
@spangaer aha, nice, thanks for the report! Yes, generic proxying is hard to do, we have to jump through hoops even for the concrete cases in the HTTP server and client implementation.

**Comment by ktoso** [comment]
@jrudolph the 1.1 is slipping from today sadly (too much internals changes going on (graph interpreter, removal of flexi merge etc)), still would be awesome to get our hands on this soon - I see there's commits already in your branch :smile:

**Comment by jrudolph** [comment]
I figured that it would slip a bit so I kept improving on it. Will try to put an PR out today.

**Comment by ktoso** [comment]
Sounds great, thanks!

**Comment by fommil** [comment]
@jrudolph I'm on holiday for 3 weeks so take your time (sips another pina colada)

**Comment by ktoso** [comment]
Awesome work @jrudolph, thanks!

**Comment by tdrozdowski** [comment]
Is this in 2.0.3?  The docs point here, but the ticket is closed...

**Comment by spangaer** [comment]
Don't know about 2.0.3, though I'm guessing yes. It certainly is in 2.4.2-RC1. I upgraded from akka-http 1 especially because this web sockets client now has custom headers, which was exactly what I was missing :)

**Comment by jrudolph** [comment]
Yes, only the docs were still missing but [have been filled](http://doc.akka.io/docs/akka/snapshot/scala/http/client-side/websocket-support.html) for RC3 in https://github.com/akka/akka/pull/19543.
