### ISSUE TITLE
Remove Scala recommendation in docs for Java TestKit?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17288]
We have seen confusion regarding this note in the docs at least twice:

Note: Due to the conciseness of test DSLs available for Scala(ScalaTest,Specs2,ScalaCheck),it may be a good idea to write the test suite in that language even if the main project is written in Java. If that is not desirable, you can also use TestKit and friends from Java, albeit with more verbose syntax which is covered below. Munish Gupta has published a nice post showing several patterns you may find useful. 

https://groups.google.com/d/msg/akka-user/_pBh3GQxOXk/ZNsWyPJ7_NkJ

**Comment by drewhk** [comment]
+1

**Comment by ktoso** [comment]
Yes, completely agreed it gives beginners the wrong impression.
Maybe at the end of the page we can say "oh by the way the scala one is nicer to read", but not in such wording.
