### ISSUE TITLE
Discuss: ActorPublisher / Subscriber - stop behaviours

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17286]
We should discuss in detail how we want ActorPublisher and Subscriber to handle stopping.
@sirthias had an use case where not-stopping was helpful, in the file publishers stopping as in "in preStart I noticed a problem, I signal error and want to stop once signalled" made more sense. 

Currently we provided both to move forward with merging tickets without large rework.
- Ticker on issue where stopping caused errors: https://github.com/akka/akka/issues/17284
- Patch which adds `onErrorThenStop()` and friends: https://github.com/ktoso/akka/commit/c214ce7ec98dbb7932180a5e856211f0a4b6cfcc
- Original issue where we decided stopping should be default: https://github.com/akka/akka/issues/17229

**Comment by patriknw** [comment]
ActorSubscriber doesn't (currently) stop automatically when it receives OnComplete/OnError. There are some use cases when it is needed to not stop, but I think we should change the default behaviour to stop.

**Comment by rkuhn** [comment]
is this still valid?

**Comment by drewhk** [comment]
Not sure.

**Comment by patriknw** [comment]
We should clarify docs. 

User code in `ActorPublisher` is responsible for cleanup and stop when it receives `Cancel` and `SubscriptionTimeoutExceeded`.

User code in `ActorSubscriber` is responsible for cleanup and stop when it receives `OnComplete` and `OnError`.
