### ISSUE TITLE
Log() improvement: include guardian in logged info?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17298]
We could expose the given streams guardian and include it's name in the log messages - such that messages from two Materializers are distinguishable.

**Comment by patriknw** [comment]
I think the streams supervisor actor doesn't have a name, but the materialization instance has, including a configurable prefix

**Comment by rkuhn** [comment]
What I meant was the stream supervisor’s path (which it always has).

**Comment by ktoso** [comment]
One question here:

Since in ActorInterpreter "the op is in an actor", I may be interested in monitoring that actor somehow.
If we just log the guardian and not "the actor which is hosting the op" it may be confusing, as if I'm using akka streams I know "an op is in an actor, that's what docs told me so if i see:

```
[DEBUG] [05/26/2015 23:02:11.474] [FlowLogSpec-akka.test.stream-dispatcher-6] [akka.stream.Log[/user/$a](akka://FlowLogSpec)] [my-debug] Element: 1
```

that path must be that actor hosting the op!". Though it would be the supervisor in the simple impl...

Should we: 
- expose like in the above snippet
- expose both the supervisor and the "path which is running that op in the actor interpreter" (easy, since prestart could include it somehow in the Lifecycle context..)
- both?

**Comment by ktoso** [comment]
I'm probably overthinking it on the other hand.

**Comment by rkuhn** [comment]
Exactly; and I’d rather print the usual URI format (`[akka.stream.Log(akka://FlowLogSpec/user/$a)]`)
