### ISSUE TITLE
Log() improvement: use preStart() to initialize logger

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17299]
As the `preStart` for Stages did not make it in time for RC1 let's revisit Log() and make it use `preStart` once https://github.com/akka/akka/issues/17290 is implemented

This should give a perf benefit for the log stage.

Log impl: https://github.com/akka/akka/pull/17162
Pre start ticket: https://github.com/akka/akka/issues/17290

**Comment by drewhk** [comment]
This will need preStart in the first place

**Comment by drewhk** [comment]
@ktoso this needs your preStart/postStop work

**Comment by drewhk** [comment]
ok, this was fixed in: https://github.com/akka/akka/pull/17439

**Comment by ktoso** [comment]
@drewhk it can be made even a bit faster I think, but out of scope of this ticket. 
Thanks for keeping an eye on these :)
