### ISSUE TITLE
failed: TlsSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17301]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2481/consoleFull

    [info] - must work in mode ClientInitiatesViaTcp while sending EmptyBytesFirst *** FAILED *** (4 seconds, 897 milliseconds)
    [info]   java.lang.AssertionError: assertion failed: expected no StreamSupervisor children, but got [Actor[akka://TlsSpec/user/$a/flow-33-7-unknown-operation#1592718400]]
    [info]   at scala.Predef$.assert(Predef.scala:179)
    [info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Utils.scala:29)
    [info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:26)
    [info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:26)
    [info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:254)
    [info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:265)
    [info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:718)
    [info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply$mcV$sp(Utils.scala:26)
    [info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
    [info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
    [info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:296)
    [info]   at akka.testkit.TestKit.within(TestKit.scala:718)
    [info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:310)
    [info]   at akka.testkit.TestKit.within(TestKit.scala:718)
    [info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
    [info]   at akka.stream.io.TlsSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$6$$anonfun$apply$1.apply$mcV$sp(TlsSpec.scala:365)
    [info]   at akka.stream.io.TlsSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$6$$anonfun$apply$1.apply(TlsSpec.scala:365)
    [info]   at akka.stream.io.TlsSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$6$$anonfun$apply$1.apply(TlsSpec.scala:365)

**Comment by patriknw** [comment]
Ran it locally. No failures in 32 rounds.

**Comment by patriknw** [comment]
another one in "mode ServerInitiatesViaTcp while sending SessionRenegotiationBySender"
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2484/consoleFull

**Comment by 2m** [comment]
Another one for:
```
must work in mode ServerInitiatesViaTcp while sending EmptyBytesInTheMiddle
must work in mode ServerInitiatesViaTcp while sending EmptyBytesLast
```
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2520/consoleFull

**Comment by rkuhn** [comment]
see also #17326

**Comment by drewhk** [comment]
It seems like that Tls is violating the spec at least in one scenario.

**Comment by drewhk** [comment]
hmm, no my mistake

**Comment by drewhk** [comment]
Currently it works with the latest changes. We should reopen the ticket as soon as we see this kind of issue in the wild.

**Comment by ktoso** [comment]
Awesome to see this closed, hope it stays so!
