### ISSUE TITLE
Seems like obsolete config property name `allow-core-pool-timeout`

### ISSUE THREAD

**Issue by savulchik** [akka/akka#17316]
In `akka-actor/src/main/resources/reference.conf`
<pre>
...
io {
  pinned-dispatcher {
    thread-pool-executor.allow-core-pool-timeout = off
  }
}
...
</pre>
<pre>
...
  thread-pool-executor {
    allow-core-timeout = on
  }
...
</pre>
I believe `allow-core-pool-timeout` should be renamed to `allow-core-timeout`.

**Comment by patriknw** [comment]
looks like a bug, thanks

**Comment by ktoso** [comment]
Good catch, thanks a lot for reporting!
I verified that that's the right setting and submitted PRs to fix it - https://github.com/akka/akka/pull/17319

**Comment by patriknw** [comment]
LGTM
