### ISSUE TITLE
Provide "Line by Line" either Source or parseLines as built-in op

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17310]
When updating activator templates we realised `FileSource` is not exactly enough for the common use case, we still need the Cookbook `parseLines` recipe for it to be useful for CSV processing.

We should ship `parseLines` or something similar as built-in - because line-by-line text processing is a super common use case.

**Comment by patriknw** [comment]
we might also want to investigate if a `BufferedReader.readLine()` source is more efficient, but I don't know if there is a corresponding thing for async io

**Comment by drewhk** [comment]
This is somewhat related to the other ticket of framing support https://github.com/akka/akka/issues/15101
