### ISSUE TITLE
Doc: Harmonize spelling in akka-stream docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17329]
We sometimes use the UK spelling of "signa**ll**ing" and sometimes the US spelling "signaling" etc.
As we use "materiali**z**ed" in APIs we probably should stick to US spelling.

This is a minor issue, but wanted to write it down so in case of a lazy-day someone may want to sed-replace the current docs / scaladocs.

**Comment by kukido** [comment]
Should this issue be closed or more work needs to be done?

**Comment by ktoso** [comment]
Not sure yet, will do a sanity run through the code base (there was also a mix of spellings in scaladoc as far as I remember).

**Comment by kukido** [comment]
@ktoso which branch should I use as the base for the pull request?

**Comment by ktoso** [comment]
`release-2.3-dev` for streams things, thanks! :-)
