### ISSUE TITLE
add OutputStreamSource and InputStreamSink

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17338]
these materialize to the `java.io` types in order to interface with legacy libraries that are based on them; propagating back-pressure will block those libraries

**Comment by agolubev** [comment]
@drewhk there are three approaches I can see here (further speculations are about ```OutputStreamSource``` as ```InputStreamSink``` would be similar):
1. Simplest one is to use ```InputStreamPublisher``` and ```PipedOutputStream```. So the ```OutputStreamSource``` and ```InputStreamSink``` will be syntax sugar (need to keep additional buffer though).
2. Second option is to create ```OutputStreamSourcePublisher``` the similar way as ```InputStreamPublisher(is: InputStream, completionPromise: Promise[Long], chunkSize: Int, initialBuffer: Int, maxBuffer: Int)```. Meaning synchronize only with chunks of fixed size. Method ```write``` will block only when buffer is full. Flush will do nothing
3. As third option there can be implemented something manageable like: 
a) chunk size can vary depends on what was sent via write methods
b) send downstream when buffer is full or when flush is called (when got back-pressure event)
c) block when buffer is full, when flush is called, or on every write method (unblock when data is sent  to down stream)

**Comment by drewhk** [comment]
I think it is important to have flush() actually block until all the buffered things have been passed via onNext. It is probably also nice to not block on write when there is enough space in the buffer. I would not use PipedOutputStream.

**Comment by agolubev** [comment]
Spent some time on this and came to the point when need to organize concurrent access to buffer.
From one side publisher (similar to InputStreamSource) will hold this buffer and respond to back pressure messages. From another - XxxxxStreamAdapter needs to update it and block calls if needed. 

The simplest and most consistent way is to make both publisher and adapter as actors. 
But here I'm not sure from governance standpoint. I mean - is it safe to create custom actor along with publisher actor within stream hierarchy. Is there any example of such custom actor in existing code?

If this strategy is not right it requires a lot of synchronizations around buffer.

**Comment by ktoso** [comment]
Sounds to me like it would be better implemented inside one actor, otherwise it'll get a bit weird, trying to coordinate who can touch what when.

**Comment by agolubev** [comment]
Got it. Thanks

**Comment by agolubev** [comment]
@ktoso One more question... If I do publisherActorRef.ask(message, timeout) from non actor - does it mean I'm creating second actor in system?
Right now I have publisher (actor) and StreamAdapter (implemented OutputStream). StreamAsapter returns as result of materialization. Consequently need to organize interaction between these two.
I believe I cannot make publisher implement stream interface cause I cannot return instance to client (akka is managing instantiation here). 
From other perspective some third object can be used simultaneously by publisher and streamAdapater and it can do synchronization, data buffering and blocking.

**Comment by ktoso** [comment]
I'm not sure I understood the entire question, but let's go one-by-one:

- does using ask create an additional actor – yes, it always does. It's a pretty lightweight one but yes, it creates an actor. it lives until timeout or completion happens.
- I didn't quite understand (maybe it's me being tired) who materializes what.. Could you re-cap this in Types?

**Comment by agolubev** [comment]
Hello, have a question about #17338 OutputStreamSource and InputStreamSink. I’m implementing BlockingQueue for data transfer between sink and Input/OutputStreamAdapters (as @rkuhn suggested). For OutputStreamSubscriber it actually looks pretty nice. However, for InputStreamSubscriber(InputStreamSink) it’s not. If nothing to consume from sharedQueue I need to send request message from Adapter to Subscriber, block until getting response (this means we got something from upstream and put in queue), poll from sharedQueue data, and then send another message to trigger backpressure. This looks complex and until don’t get other ideas would like to stick to sending data with messages (not via shared queue) at least for InputStreamSink. @ktoso and @viktorklang reviewed akka/akka#17995 so maybe you have some opinion?

**Comment by viktorklang** [comment]
@agolubev Could you link to the code that you think looks too complex?

**Comment by agolubev** [comment]
@viktorklang, let me fix few issues there to have passed test and I'll push it to PR

**Comment by agolubev** [comment]
@viktorklang, ok it stays with two commits. First is with all fixes but with no shared queue, second commit is with shared buffer.
I added test to show messages that come to InputStreamSubscriber (https://github.com/akka/akka/pull/17995/files#diff-bf29fed8b988c23e7d8ec08f5917486eR235)
Having shared buffer requires to send two messages (instead of one) and wait for response (blocking calls with ask from InputStreamAdapter to Subscriber) 

We need first message to block and wait for data (response can also contains "complete received" flag). In case something is in buffer we don't need this message.
Second step is about reading from shared buffer
Third step is about sending another message to InputStreamAdapter. We need this for backpressure and to receive "complete received" or error message.

So my doubt is about having additional message to send and that this additional message has to be blocking as well.

**Comment by drewhk** [comment]
I think this scheme is more complicated than it needs to be. Can't you use the blocking queue as a "mailbox" for the InputStream, i.e. not just put ByteStrings in there but onComplete/onError too? You only need to allocate one more space over the normal buffer size. 

What would be also worth a try to implement these one of these (Sink or Source) as a GraphStage to see how it compares with the actor based one.
