### ISSUE TITLE
Not all akka stream Sinks receive the emitted data

### ISSUE THREAD

**Issue by raisercostin** [akka/akka#17339]
When running an akka streaming FlowGraph not all the emitted Chars are received by all Sinks.

I created two sinks one with a pause of 200 one with 300 and the laziest one doesn't receive all the emitted data but nevertheless the flow finishes.

The full details are on stackoverflow question. I don't know if I should repeat the content here. http://stackoverflow.com/q/29903676/99248
To give a hint the flow is something like this
```scala
val materialized = FlowGraph.closed(consoleSink1, consoleSink2)((x1, x2) => x1) { implicit builder =>
      (console1, console2) =>
        import FlowGraph.Implicits._
        val broadcast = builder.add(Broadcast[Char](2))
        countSource ~> broadcast ~> console1
        broadcast ~> console2
    }.run()
```

**Comment by drewhk** [comment]
You wait only on Sink1 to finish, then you call shutdown on the system which prevents Sink 2 to be completed. In your function where you combine the two materialized values (x1, x2) => x1 you ignore the second future.

**Comment by jrudolph** [comment]
Well spotted @drewhk. I looked 10 minutes at the code at stackoverflow this morning but didn't see it and then redirected @raisercostin here. 

Replacing `(x1, x2) => x1` e.g. with `(x1, x2) => x1 zip x2` fixes the issue.

**Comment by 2m** [comment]
I think `_ zip _` should work as well.
