### ISSUE TITLE
Add "timeout" stage wrapping a "1-for-1" sub-stream

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17346]
Required functionality:
For every element going into the sub-stream expect a response element coming out within a given time period. Upon timeout close the stream with a timeout error.

Important use case: client-side request timeouts in akka-http.
Original discussion on akka-dev:
https://groups.google.com/d/msg/akka-dev/_8lleSackcc/SDvhMDOH6uUJ

/cc @jrudolph @richardbradley

**Comment by drewhk** [comment]
How does this look like in API?

**Comment by sirthias** [comment]
Figuring this out is part of the job of this ticket... :)

**Comment by drewhk** [comment]
Yes, but I want to understand this ticket. What does 1-for-1 substream mean here?

**Comment by sirthias** [comment]
By "1-for-1 substream" I mean a `Flow[A, B]` which emits exactly one `B` for every `A`. An HTTP client flow (`Flow[HttpRequest, HttpResponse]`) would be one such example.

The timeout functionality asked for in this ticket would allow me wrap such a 1-for-1 flow, e.g. like this:

    withTimeout[A, B](period: Duration, flow: Flow[A, B]): Flow[A, B]

Type-wise nothing changes but I would have the guarantee that the produced flow generates a `B` at most `period` after receiving an `A`. Otherwise it would be completed with an error.

**Comment by drewhk** [comment]
I see. I was confused by the "substream" word, since this just embeds a Flow in the same materialization domain (the same graph). Now it is clear.

**Comment by sirthias** [comment]
Once this feature is implemented we should also update the "HTTP / client-side / connection-level / timeouts" section with an example of how to use it.

**Comment by drewhk** [comment]
@sirthias isn't this ready?

**Comment by sirthias** [comment]
Yes, I guess it is.

**Comment by ktoso** [comment]
Great, closing.

**Comment by saucam** [comment]
Hi,

Could anyone please point me to an example implementation using this feature?
Do we now have client side per request time outs implemented  ?
Best Regards
Yash
