### ISSUE TITLE
HTTP client - setting "max-connections = 65535" causes all requests to time out

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#17345]
I wanted to remove the limit on "max-connections" from my client pool, as my downstream server is another Akka server.

The code enforces `"max-connections must be > 0"`, but how do I turn off this limit at all?

I tried setting `"max-connections = 65535"`, but it seemed to cause all HTTP client requests to never respond.

The same thing happens for 10,000. The system seems to cope if I set the limit to 1,000.

/cc @sirthias

**Comment by sirthias** [comment]
Interesting.
When you create a host connection pool the pool logic creates `max-connections` "slots", each managing a potential HTTP connection. All slots are tied into a single stream structure with a `FlexiRoute` branching out to them and a `merge` behind them.

I could imagine that the effect you are seeing is the overhead in these stream operations becoming apparent. Maybe a `FlexiRoute` with 10K outlets and/or a merge with 10K inlets is currently just too slow to start/run to be able to get any work done before the test is stopped.

If that's the case you should see a gradual degradation in performance as you increase `max-connections`.

**Comment by RichardBradley** [comment]
> If that's the case you should see a gradual degradation in performance as you increase max-connections.

Yes, noticeably so. 
Setting up the connection pool takes less than 450ms when "max-connections" is "4", and over 3000ms when "max-connections" is "1000"


Is there any way to disable connection limiting without paying this cost?

**Comment by sirthias** [comment]
> Is there any way to disable connection limiting without paying this cost?

No. And I actually don't think that you really want a limit that is very high.
You *do* want to limit the number of current TCP connections to the target host, no matter what type of host it is. Every connection takes up quite a bit of resources and is expensive to set up.

What's your use case? Why would you want 1000 parallel connections?

**Comment by RichardBradley** [comment]
> What's your use case? Why would you want 1000 parallel connections?

We have a SOA style system with several servers handling different aspects of the functionality.
They are all Akka HTTP REST API servers (and Cassandra).
The web-facing frontend server can expect 100s of concurrent requests from clients, and it needs to make requests to the backend servers to serve each.

At the moment, we are using a "connection per request" client based on the Akka connection-level API (see e.g. #17057). Under moderate load, we are seeing an average of 50 concurrent connections to one of our services, with peaks of 100 concurrent connections. We expect to scale that up by around 10x.

I was hoping to be able to drop in the connection pooling client instead, and save TCP setup costs. I think I need a max connection limit of at least 100, and ideally no limit, to avoid queueing requests at the "HTTP client" bottleneck.

> You do want to limit the number of current TCP connections to the target host, no matter what type of host it is. 

I don't think that's true in all cases. if a connection represents a concurrent operation (no pipelining here, as the operations are not idempotent) then applications may choose to pay some extra cost to allow more concurrency, rather than queueing requests to meet some arbitrary connection limit.

> Every connection takes up quite a bit of resources and is expensive to set up.

It seems fairly cheap to me. We have been making a new connection for each request for a while now awaiting the connection pooling HTTP client, and it seems to work fine at even fairly high loads.

We do see "TIME_WAIT" port exhaustion at very high throughputs with connection-per-request, so we'd like to be able to use connection pooling, but ideally without artificially limiting the max concurrent requests.

**Comment by sirthias** [comment]
Ok, thanks for the details.
I think you should start out with configuring no more than 100 max-connections and see how things go. The benefit of a pool is that request can be scheduled onto *any* of the pools connections, so no queuing would take place unless *all* connections are concurrently busy.
Also, if you know that the backend servers are able to perform HTTP pipelining (as akka-http does) I'd recommend to enable pipelining with an initial limit of, say 8. This will greatly increase throughput across the pool's connections, provided a large part of the requests are idempotent.

If you find that a single pool is not able to properly take the load you can start to schedule the load across several independent pools, if you must. This should suffice to handle any load that the machines can take.

**Comment by RichardBradley** [comment]
> I think you should start out with configuring no more than 100 max-connections and see how things go. 

OK, I have done.
I initially didn't increase "max-open-requests", leaving it at its default of 32, and I saw
```
java.lang.RuntimeException: Exceeded configured max-open-requests value of [32}]
        at akka.http.impl.engine.client.PoolInterfaceActor$$anonfun$receive$1.applyOrElse(PoolInterfaceActor.scala:108)
```
(Note the slight typo in the exception message.)

I found the config instructions confusing:

```
      # The maximum number of open requests accepted into the pool across all
      # materializations of any of its client flows.
      # Protects against (accidentally) overloading a single pool with too many client flow materializations.
      # Note that with N concurrent materializations the max number of open request in the pool
      # will never exceed N * max-connections * pipelining-limit.
      # Must be a power of 2 and > 0!
```

What is a "client flow materialization" here?
What will "N" be for me?

Should I set this value to 256 (taking N = 1)?
The defaults would suggest that N = 8. Is that deliberate? Do I need to set this to 1024 then?

**Comment by sirthias** [comment]
The docs for the Akka HTTP client-side (which are currently in the works) will explain "pool client flow materializations". A "pool client flow" is a `Flow` you get back from `Http.cachedHostConnectionPool`.
If your app calls this method 3 times (with the same endpoint and settings) it will get back 3 different client flow instances for the same pool. If each of these client flows is then materialized 4 times (concurrently) you'll have an `N` of 12, i.e. 12 concurrent pool client flow materializations.
All of these share the resources of the single pool.

Increasing `max-open-requests` to something like 1024 is not a problem. This is setting serves mainly as a protection against erroneous connection pool use, e.g. because the application is materializing too many client flows that all compete for the same pooled connections.

(Thank you for spotting the type in the exception message. Just got fixed.)

**Comment by jrudolph** [comment]
I quickly checked where the process is slow and it's here:

```
	at akka.stream.impl.StreamLayout$Module$class.validate(StreamLayout.scala:169)
	at akka.stream.impl.StreamLayout$CompositeModule.validate(StreamLayout.scala:266)
	at akka.stream.impl.StreamLayout$Module$class.grow(StreamLayout.scala:93)
	at akka.stream.impl.StreamLayout$CompositeModule.grow(StreamLayout.scala:266)
	at akka.stream.impl.StreamLayout$Module$class.grow(StreamLayout.scala:90)
	at akka.stream.impl.StreamLayout$CompositeModule.grow(StreamLayout.scala:266)
	at akka.stream.scaladsl.FlowGraph$Builder.add(Graph.scala:323)
	at akka.http.impl.engine.client.PoolFlow$$anonfun$apply$1$$anonfun$2.apply(PoolFlow.scala:80)
```

where for each `Builder.add` graph validation is run which is probably the source of the quadratic runtime behavior.

**Comment by rkuhn** [comment]
Ah, right, we left this on as a diagnostic helper in case something went wrong, we’ll switch it off in RC3. Thanks for checking, @jrudolph!

**Comment by RichardBradley** [comment]
(See also #17332 -- I think I was running with "`StreamLayout.debug = false`" for the above measurements. I think the "validate" calls identified above are outside of the "if (debug)" markers.)

**Comment by RichardBradley** [comment]
I retested after removing the "validate()" calls outside of the "if (debug)" markers.
This is the time it takes to make the first HTTP request via `Http().singleRequest`:

"max-connections" setting | 1.0-RC1 with #17332 | 1.0-RC1 with all validate() calls removed
--------|---------|--------
10 | 554ms | 582ms
100 | 754ms | 790 ms
1000 | 5535ms | 2991ms
10000 | timeout | timeout

So it looks like "validate()" is not the sole culprit here.

My estimate above for the number of connections we need was a bit out -- our app currently needs 1050 concurrent connections, which might just about work with the new pooling HTTP client (it was working fine with a connection per request). 
We were hoping to scale this up to about 20,000 concurrent connections, which is pushing the O/S limit on a single server port. We might need to split the traffic across several ports in addition to fixing this issue with the HTTP client to hit that.
(I appreciate this use case is a bit odd. We are hosting a COMET long polling server for lots of users, and the work is delegated across a HTTP connection to a different server in our SOA design.)

**Comment by RichardBradley** [comment]
Perhaps we should split our traffic -- an Http() client for most of our traffic, with ~100 concurrent connections, and a connection-per-request client for our long polling traffic.

**Comment by jrudolph** [comment]
> So it looks like "validate()" is not the sole culprit here.

Yep, that's what I found out as well. There are at least these other things going on:
 * `connect` accesses `inPorts` and `outPorts` at each step which includes a slow `toSet` conversion 
 * `connect` uses `filterNot` at each step to remove connected ports
 * `validate` will still be called once at materialization

At least the first two are likely to show quadratic behavior as well.

**Comment by rkuhn** [comment]
@drewhk we might want to fix these; I remember thinking “we need to benchmark to see whether `lazy val` would be better than `def`”

**Comment by drewhk** [comment]
But it is a lazy val. If you reuse a module then inPorts and outPorts set conversion happens exactly once. The filterNot issue is valid, but again, if flows are reused then only shallow copy will be used, which will only build sets for the external facing ports, the internals will be left intact. I.e. if you reuse a Flow, no matter how complex it is inside, the cost of creating it is only the cost of making a copy of the two exposed ports. 

I can do some benchmark and optimize whatever I find. I just need confirmation that this is priority now.

**Comment by rkuhn** [comment]
Well it is all relative; I do agree that we still have more important things to fix first, and the “unlimited connections” use-case still sounds dubious to me—why would you use a pool in that case at all? But we should eventually get rid of such non-linear behavior where possible.

**Comment by jrudolph** [comment]
Currently, it doesn't even work with 5000 connections, so this is far from "unlimited connections" :) Not performing is one thing, not being able to scale a different one...

**Comment by rkuhn** [comment]
Yes, of course. What I meant was that to me the purpose of a connection pool (as implemented) is to obey API limits, and those usually are pretty low, like a handful of connections. Otherwise you can simply create new connections and use them, there’s the HTTP connection API for that.

If we can make something magic that works for all cases (a so-called silver bullet—which makes my prejudice quite obvious ;-) ) then I’m all for it, but I won’t hold off 1.0 for this unless you convince me that this is an absolute must-have. For the OP using a pool seems to be a pure optimization AFAICS.

**Comment by jrudolph** [comment]
@rkuhn I agree, we actually made very similar arguments for the spray client infrastructure which had its own share of scaling problems.

On the other hand, I wouldn't say the sole purpose of a pool is to obey limits but usually it's a performance optimization that has a sweet spot at some number of concurrent connections depending on the environment and we shouldn't make too many assumptions about the kinds of environment this piece of software will eventually run in... Pushing the limits will often bring the most interesting results and removing scaling bottlenecks will often have beneficial effects on the more moderate use cases as well.

**Comment by RichardBradley** [comment]
> For the OP using a pool seems to be a pure optimization AFAICS.

Yes, we were hoping for a perf improvement from the pooling client. We can use the connection-per-request API for now.

There is another significant benefit to using a pooling client for us -- if we use a new connection for each request then the "TIME_WAIT port exhaustion" O/S limit will give a hard limit on the max request rate we can make to a single server, of (very roughly) 300 requests / second. 

If we want to go above that limit (and we do), then we need to either use multiple server ports (which is a bit ugly and fiddly) or implement some kind of connection reuse. We were hoping to be able to use this connection pool to do the latter, but I appreciate that max-connections=65536 may not be a mainline use case compared to max-connections=8 :-)

**Comment by rkuhn** [comment]
Okay, thanks for the details. As I said, I do think that this should be improved, the more scalable we can make it the better, but we will likely only get to this one in 1.1.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
