### ISSUE TITLE
Error-close client-side response stream if there are responses pending at connection end

### ISSUE THREAD

**Issue by sirthias** [akka/akka#17344]
Currently the low-level client-side connection stream simply completes the response stream if the underlying HTTP connection is cleanly closed, even if there are more (potentially pipelined) responses pending.

This ticket proposes to change this behavior to signal the premature closing of a connection, with (potentially pipelined) responses still pending, as a "truncation error" rather than a clean stream completion.

Supersedes #16865.

/cc @jrudolph @richardbradley

**Comment by jrudolph** [comment]
The hard part, here, is to achieve proper coordination of stream completion through the bypass between both ends of the Request->Response pipe.

Here's a sketch how this could be implemented:

 * In `ResponseParsingMerge` don't complete on `StreamEnd` but deliver `StreamEnd` literally
 * Get StreamEnd through responsePreparation and signal the termination backchannel in the termination fanout
 * Then, terminationMerge will close the bypass
 * Back in `ResponseParsingMerge` observe if the bypass delivers more elements (= truncation) or if it finished immediately (= regular close)

I guess the usual cancellation race condition also applies here where a request may already be in flight when the terminationMerge cancels its inputs.

An alternative solution would piggyback on a general streams element that wraps one-to-one flows and to enforces the one-to-one mapping by counting and comparing the number of ingoing and outgoing elements.

**Comment by drewhk** [comment]
I opt for the one-to-one mapping enforcement.
