### ISSUE TITLE
BUG: conflate followed by map maps the conflate seed instead of the aggregate

### ISSUE THREAD

**Issue by jtanner** [akka/akka#17359]
`map` is behaving strangely when followed by `conflate`.

To reproduce add the following spec to `FlowConflateSpec.scala`:

```
    "conflate and map elements while downstream is silent" in {
      val publisher = TestPublisher.probe[Int]()
      val subscriber = TestSubscriber.manualProbe[Int]()

      Source(publisher)
        .conflate(seed = i ⇒ i)(aggregate = (sum, i) ⇒ sum + i)
        // should print 5050 and add 1
        .map(i => {println(i); i + 1})
        .to(Sink(subscriber)).run()
      val sub = subscriber.expectSubscription()

      for (i ← 1 to 100) {
        publisher.sendNext(i)
      }
      subscriber.expectNoMsg(1.second)
      sub.request(1)
      subscriber.expectNext(5051)
      sub.cancel()
    }
```

The `println` prints `1` to the console and the expectation fails because it's receiving `2`:

```
java.lang.AssertionError: assertion failed: expected OnNext(5051), found OnNext(2)
```

I would expect `map` to receive `5050` instead of `1`, am I using `conflate` and `map` incorrectly in this context?

**Comment by jtanner** [comment]
This could be related to #16408

**Comment by drewhk** [comment]
This is not a bug. All stages buffer, so map requests automatically a certain number of elements in the beginning. I.e. conflate is not backpressured immediately but only after these "prefetch" requests has been fulfilled. See this page in the docs: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC2/scala/stream-rate.html

**Comment by jtanner** [comment]
Thanks for the help. It makes much more sense now.

**Comment by l15k4** [comment]
Guys what about this [behavior](https://gist.github.com/l15k4/3f4590f1d6c2ce1628fc)? I probably don't fully understand the concept of `conflate` because I can't explain it to myself. Also the result is nondeterministic ...

**Comment by drewhk** [comment]
@l15k4 

Conflate works like a fold while the downstream backpressures, i.e. it is by nature nondeterministic since wether it folds or not depends on the downstream backpressure state. In your example you effectively implemented a dropping 1-element buffer stage which drops on backpressure the previously  buffered element element (since your folding function depends only on the new element, and drops the value of acc).
