### ISSUE TITLE
Http().shutdownAllConnectionPools() is too verbose

### ISSUE THREAD

**Issue by samueltardieu** [akka/akka#17353]
It looks like `Http().shutdownAllConnectionPools()` logs a message with level `INFO`, while `DEBUG` would probably be more appropriate. In my application, with a `loglevel` set to `INFO`, this is the only message from Akka that I see:

```
INFO] [04/30/2015 13:42:58.895] [run-main-6] [ActorSystem(default)] Initiating orderly shutdown of all active host connections pools...
```

**Comment by hakuch** [comment]
This logging message appears to still be set at the `INFO` level as of the 1.0 release.

**Comment by ktoso** [comment]
Right, thus the ticket still being open :-)

Would you like to contribute a PR to change the log level here @hakuch? 
That would be very welcome, thanks in advance!

**Comment by hakuch** [comment]
@ktoso Sure, I can give it a go. :-)

**Comment by ktoso** [comment]
Thanks! The code resides on branch `release-2.3-dev` and here's some more info about contributing: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages
