### ISSUE TITLE
Stage: onUpstreamFinish is (or may be?) called after previous ctx.pushAndFinish

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17351]
It's then even possible to inject more elements in onUpstreamFinish. I'd say this is a bug as explicitly finishing should cancel upstream which is racy in reactive streams semantics wrt receiving extra elements (or onComplete) but I don't find it natural in Stage semantics that such a race isn't prevented.

**Comment by drewhk** [comment]
Once you completed the stage with pushAndFinish it should never result in a new onUpstreamFinish -- it is synchronous. In fact, calling pushAndFinish rewrites the internal stage pipeline to contain a special Finished op at the place of the original op. If you are right, then this is a bug, but currently it is hard to see how this can happen. Do you have a reproducer?

**Comment by drewhk** [comment]
This might be related to forking in pushAndFinish.

**Comment by jrudolph** [comment]
Ok, then we agree about the semantics. I'll try to come up with a reproduction.

**Comment by drewhk** [comment]
I might know where the bug is. There is a FIXME even :) When an pushFinish is called and the next stage also calls pushFinish, then that op is not replaced with a Finished op, which is a bug.

**Comment by drewhk** [comment]
but I would still like to see your reproducer because I am not sure that bug can cause what you see, unless you fuse stages, which as far as I know is not done.

**Comment by drewhk** [comment]
I think this is the bug. Upstream boundary stage can call pushAndFinish, and if your code also calls it, then it will fail in the way you observed.

**Comment by jrudolph** [comment]
Yep, this doesn't even seem to be a race condition.

I wrote this failing test in FlowStageSpec:

```scala
    "not trigger onUpstreamFinished after pushAndFinish" in assertAllStagesStopped {
      val in = TestPublisher.manualProbe[Int]()
      val flow =
        Source(in)
          .transform(() ⇒ new StatefulStage[Int, Int] {

            def initial: StageState[Int, Int] = new State {
              override def onPush(element: Int, ctx: Context[Int]) =
                ctx.pushAndFinish(element)
            }
            override def onUpstreamFinish(ctx: Context[Int]): TerminationDirective =
              terminationEmit(Iterator(42), ctx)
          })
          .runWith(Sink.publisher)

      val inSub = in.expectSubscription()

      val out = TestSubscriber.manualProbe[Int]()
      flow.subscribe(out)
      val outSub = out.expectSubscription()

      inSub.sendNext(23)
      inSub.sendComplete()

      outSub.request(1) // it depends on this line, i.e. generating backpressure between buffer and stage execution

      out.expectNext(23)
      out.expectComplete()
    }
```

**Comment by drewhk** [comment]
Yes, you need a buffered complete in the upstream and one buffered element, while downstream has still no demand. Then the ActorInterpreter boundary stage will immediately after the initial pull call pushAndFinish.

**Comment by drewhk** [comment]
Seems like not as simple to fix as I hoped. I will need to investigate more.

**Comment by jrudolph** [comment]
I pushed the failing test to a branch in case you want to use it. See https://github.com/spray/akka/commit/9a04bee3dc361386c8c10b9f2a5f12ed96dad3fd

**Comment by drewhk** [comment]
I have an internal test for it now that is against the interpreter directly, without actors involved.

**Comment by drewhk** [comment]
@jrudolph this has been (hopefully) fixed, so you are unblocked now.

**Comment by jrudolph** [comment]
Cool, thanks, will rebase #17367 on top of it.
