### ISSUE TITLE
Stream quick start guide misprints

### ISSUE THREAD

**Issue by agolubev** [akka/akka#17358]
Reactive tweets guide that is available here (http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC2/scala/stream-quickstart.html#stream-quickstart-scala) has few word duplications:  "can can" and "element element" it's in "Broadcasting a stream" section and in the following one.

**Comment by ktoso** [comment]
Thanks a lot for reporting! 
I'll have a look, also please feel free to submit PRs fixing such typos right away - it's pretty simple to do this from on github :-)

**Comment by ktoso** [comment]
Thanks for reporting! Fixed by @2m in #17637
