### ISSUE TITLE
update to Scala 2.11.6

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17357]
on all active branches

**Comment by drewhk** [comment]
Umm, is this for streams?

**Comment by rkuhn** [comment]
As it says: _all active branches_ (which includes `master`, `release-2.3` and `release-2.3-dev`)

Thanks to Heiko for pointing out that our Streams & HTTP releases didn’t use the newest version!

**Comment by rkuhn** [comment]
(of course for Streams the default is still 2.10, but this is about the 2.11 version to be used when releasing)

**Comment by drewhk** [comment]
ah, I see.
