### ISSUE TITLE
collapse java/scala artifacts into one and document content assist filters

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17361]
In particular `akka-http-{java,scala}` and `akka-http-testkit-{java,scala}` shall be merged into one project each. The reason is that the split is not complete anyway (with the Java parts depending on their Scala counterparts) and the javadsl/scaladsl packages need to be filtered by the user or in the IDE in any case since third-party dependencies may pull in the wrong flavor as well.

The thought behind this is consistency: the users shall always get the same look and feel. Doing a best-effort split will just be confusing for those parts where a split is not feasible or where it is broken accidentally.

/cc @sirthias @jrudolph

Just to be clear: no code movements are implied, this is only about the published artifacts (and therefore the project layout).

We will then also have to document how to filter out the undesired half of the DSL in IntelliJ or Eclipse, respectively.

**Comment by drewhk** [comment]
I think we should try to do this in RC3. @sirthias @jrudolph any of you want to pick this up, or should I attempt it myself? This affects mergeability of your branches so your call.

**Comment by jrudolph** [comment]
To understand the implications: why would it affect mergeability if no code is moved around? What is the suggested approach?

**Comment by drewhk** [comment]
Let's ask @rkuhn what "therefore the project layout" exactly means in this context given "no code movements are implied" ;)

**Comment by jrudolph** [comment]
:)

**Comment by rkuhn** [comment]
What I meant is that no classes move to different packages, but of course lots of files will move around in the repository :-)

**Comment by rkuhn** [comment]
To maximize git-friendliness this should be done as a completely separate action that does not change any code (to make rename-detection more efficient).

**Comment by jrudolph** [comment]
Ok, good to know. I understood that only class-files would be merged together during the publishing process.

Then, I'd say please do the renaming and we care for the merge problems which are hopefully only few thanks to git's overall greatness.
