### ISSUE TITLE
FAILED: RemoteNodeRestartDeathWatch

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17369]
https://jenkins.akka.io:8498/job/akka-nightly/2221/consoleFull

[JVM-1] - must receive Terminated when remote actor system is restarted *** FAILED *** (15 seconds, 736 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsg while waiting for shutdown-ack
[JVM-1]   at scala.Predef$.assert(Predef.scala:165)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:339)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
[JVM-1]   at akka.remote.RemoteNodeRestartDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$5.apply(RemoteNodeRestartDeathWatchSpec.scala:92)
[JVM-1]   at akka.remote.RemoteNodeRestartDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$5.apply(RemoteNodeRestartDeathWatchSpec.scala:90)

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
