### ISSUE TITLE
rethink naming of ClusterSharding

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17368]
While the term is technically accurate, we might want to think about whether there is a term that better describes its applicability, i.e. when should I reach for this abstraction?

**Comment by jboner** [comment]
One interesting data point on this is reading through the Akka vs Orleans doc that Roland wrote up. ClusterSharding is referenced a lot, but always in places where it is doing a lot more than just sharding, mapping to more intuitive naming in Orleans and therefore often accompanied with an explanation. A good name should give you the intent and an intuitive feel for what it is good for. It has turned into the main workhorse in the cluster library toolkit and move way beyond sharding.
