### ISSUE TITLE
failed: akka-docs-udp-multicast

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17371]
akka-docs-udp-multicast is not included in samples aggregate, i.e. not verified

It fails for me locally:

    [INFO] [05/04/2015 11:46:20.086] [JavaUdpMulticastTest-akka.actor.default-dispatcher-2] [akka://JavaUdpMulticastTest/user/$a] Bound to /0:0:0:0:0:0:0:0:64379
    [INFO] [05/04/2015 11:46:20.102] [JavaUdpMulticastTest-akka.actor.default-dispatcher-2] [akka://JavaUdpMulticastTest/user/$b] Sending message to /ff02:0:0:0:0:0:c638:395a%awdl0:64379
    [INFO] [05/04/2015 11:46:20.157] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-3] [akka://ScalaUdpMulticastSpec/user/$a] Bound to /0:0:0:0:0:0:0:0:64381
    [INFO] [05/04/2015 11:46:20.161] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-2] [akka://ScalaUdpMulticastSpec/user/$b] Sending message to /ff02:0:0:0:0:0:8fd5:3e5f%awdl0:64381
    [info] Test run started
    [info] Test docs.io.JavaUdpMulticastTest.testUdpMulticast started
    [error] Test docs.io.JavaUdpMulticastTest.testUdpMulticast failed: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ohi
    [error]     at scala.Predef$.assert(Predef.scala:165)
    [error]     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
    [error]     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
    [error]     at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
    [error]     at akka.testkit.JavaTestKit.expectMsgEquals(JavaTestKit.java:378)
    [error]     at docs.io.JavaUdpMulticastTest$1.<init>(JavaUdpMulticastTest.java:62)
    [error]     at docs.io.JavaUdpMulticastTest.testUdpMulticast(JavaUdpMulticastTest.java:33)
    [error]     ...
    [info] Test run finished: 1 failed, 0 ignored, 1 total, 3.466s
    [info] ScalaUdpMulticastSpec:
    [info] listener
    [info] - should send message back to sink *** FAILED ***
    [info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ohi
    [info]   at scala.Predef$.assert(Predef.scala:165)
    [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
    [info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
    [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
    [info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ScalaUdpMulticastSpec.scala:38)
    [info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
    [info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
    [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
    [info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

**Comment by patriknw** [comment]
Here is one, but probably not the same problem as I have locally: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2641/consoleFull

**Comment by patriknw** [comment]
@ktoso does `ScalaUdpMulticastSpec` this fail for you when running test in akka-docs on osx, or is it only me?

**Comment by ktoso** [comment]
Yes, I'm getting that failure on macos, manifests as:

```
[info] ScalaUdpMulticastSpec:
[info] listener
[INFO] [07/01/2015 10:00:07.945] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-2] [akka://ScalaUdpMulticastSpec/user/$a] Bound to /0:0:0:0:0:0:0:0:57172
[INFO] [07/01/2015 10:00:07.957] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-4] [akka://ScalaUdpMulticastSpec/user/$b] Sending message to /ff02:0:0:0:0:0:e16f:e049%awdl0:57172
[info] - should send message back to sink *** FAILED *** (3 seconds, 61 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ohi
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ScalaUdpMulticastSpec.scala:38)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at docs.io.ScalaUdpMulticastSpec.withFixture(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at docs.io.ScalaUdpMulticastSpec.org$scalatest$BeforeAndAfter$$super$runTest(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
[info]   at docs.io.ScalaUdpMulticastSpec.runTest(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
```

Not sure since when, but sounds similar to the test where on macos the `127.x.x.x` space isn't bound by default, only here it's IPv6?

**Comment by patriknw** [comment]
ok, good, then we need to find a way to skip this test for such environments, unless we can change it to bind to something that is universally available

**Comment by johanandren** [comment]
If i force it to bind to lo0 or en0 rather than the first found IPv6 enabled (which is awdl0 on my machine) then it works. Not quite sure how I can do this without breaking other platforms though.

**Comment by patriknw** [comment]
that would be great, can you force it on mac only?

**Comment by johanandren** [comment]
The best I could come up with is to filter out the "awdl0" interface name from selection, should work on all platforms.

**Comment by ktoso** [comment]
Filtering it out sounds safe I guess (in case you want OSX only: `System.getProperty("os.name")`)

**Comment by hepin1989** [comment]
```
def isUnix: Boolean = File.separatorChar == '/' 
def isMacOSX: Boolean = isUnix && osName.startsWith("Mac") || osName.startsWith("Darwin")
```?

**Comment by ktoso** [comment]
Yeah, pretty much so @hepin1989 :)
