### ISSUE TITLE
add well-configured default SSLContext for SslTls

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17388]
The SSLContext is used to cache established sessions and provide defaults for session negotiation. We should provide one that implements @wsargent’s best practices and that is used as a default—with the possibility for users to pass their own when needed. The default context can be a global singleton AFAIK, please research whether there may be potential problems; it should at least be global to the ActorSystem.

When introducing the factories which default to the global context, also remove the firstSession parameter (there is a default value for that one in NegotiateNewSession already).

**Comment by wsargent** [comment]
Also note there is a new RFC 7525 on TLS configuration: https://tools.ietf.org/html/rfc7525

**Comment by rkuhn** [comment]
Thanks @wsargent!

**Comment by drewhk** [comment]
Should we aim to get this into RC3? How much work is this? I am clueless about the fine details of TLS configuration. @wsargent can you help us here somehow?

**Comment by rkuhn** [comment]
The only thing we need to provide is a global singleton SSLContext that we use when the user does not provide one (overloaded methods to be created), and this default needs to be configured sensibly according to Will’s links and recommendations. We should also point to the excellent section in the Play documentation that he wrote about these things.

**Comment by wsargent** [comment]
I'll set up a project in 1.8 with a default config -- it'll be easy.

**Comment by wsargent** [comment]
Okay, take a look at https://github.com/wsargent/java-rfc7525 -- will add tests and such.

**Comment by drewhk** [comment]
Um, but we need Java 6 support. Is there a Java6 version I can look up?

**Comment by wsargent** [comment]
Well, that's the thing -- Java 1.6 doesn't have any kind of checkers built in.  Most of the work in WS was in adding it: https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/AlgorithmChecker.scala

**Comment by rkuhn** [comment]
this is in typesafehub/ssl-config
