### ISSUE TITLE
Regression in 2.3.10 DirectByteBufferPool

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17391]
https://github.com/akka/akka/pull/17258 introduced a performance regression for Spray. Reported by @jrudolph.

The proper solution is described in #17281 and #17194 but we need to fix the regression asap and with minimal and safe code changes.

**Comment by patriknw** [comment]
The proposed interim solution is to switch to `synchronized`.

**Comment by rkuhn** [comment]
Agreed, other solutions are too risky without proper testing. We should get the right solution into 2.4-M1 if possible.
