### ISSUE TITLE
add boilerplate remover for fan-in junctions

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17399]
Currently users need to build a graph when the only thing they need is just one junction. We can fix this by adding something like
~~~scala
object Source {
  ...
  def combine[T, U](inputs: Source[T, Any]*)(strategy: Int => Graph[UniformFanInShape[T, U], Any]): Source[U, Unit]
~~~
that would allow elegant code like
~~~scala
Source.combine(s1, s2, s3)(Merge)
~~~
This could replace `Source.concat` since it subsumes it.

**Comment by rkuhn** [comment]
Should also provide the mirror operation of combining Sinks.

**Comment by agolubev** [comment]
@drewhk, I believe this ticket should be closed?

**Comment by rkuhn** [comment]
This was done in #17865.
