### ISSUE TITLE
akka-http ignores charset in ContentType

### ISSUE THREAD

**Issue by TimothyKlim** [akka/akka#17409]
Hi!

Why akka-http-core ignores charset for ContentType if I set it explicitly: `.withCharset(UTF-8)`?

https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-RC1/akka-http-core/src/main/scala/akka/http/scaladsl/model/ContentType.scala#L75

If application works through cloudflare(or any other) then without charset in header it will cause problem on client with charset for text because of `Transfer-Encoding: chunked` header added by cloudflare.
This is not explicit behaviour of akka-http DSL.

**Comment by jrudolph** [comment]
It doesn't ignore the charset. The line you marked just means that if the media-type defines a fixed charset, the user-defined charset must match that fixed charset and that charset mustn't be mentioned in the `Content-Type` header.

Note, that this line isn't used with text content types which don't have a fixed charset.

So, you need to provide more information what exactly is wrong. I.e. what did you do, what behavior did you expect and what happened instead?

/cc @sirthias

**Comment by TimothyKlim** [comment]
I'm trying to set charset within HttpResponse as:
```scala
path("test") {
  pathEndOrSingleSlash {
    get { ctx =>
      val res = HttpResponse(200, entity = HttpEntity(ContentTypes.`application/json`.withCharset(HttpCharsets.`UTF-8`), ""))
      ctx.complete(res)
    }
  }
}
```
and I get unexpected response without charset in `Content-Type` header:
```
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: application/json
Date: Fri, 08 May 2015 08:53:32 GMT
Server: api-server
```

**Comment by sirthias** [comment]
The `application/json` media-type implicitly defined UTF-8 as the only valid encoding.
So, everything will be UTF-8 encoded but the mediatype doesn't have to contain a `charset=UTF8` parameter.

**Comment by jrudolph** [comment]
The content-type of `application/json` is fixed to UTF-8 and doesn't allow a charset parameter by its spec. 

http://tools.ietf.org/html/rfc7158#section-11
http://stackoverflow.com/questions/13096259/can-charset-parameter-be-used-with-application-json-content-type-in-http-1-1#13098683

**Comment by jrudolph** [comment]
Ah, @sirthias was faster :)

**Comment by TimothyKlim** [comment]
Ok, thank you.
