### ISSUE TITLE
Fix broken tests in GzipSpec that regressed during streams changes in #16902

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17419]
Commit e30c3e6492fdffb20ee8baa488611213b5a66755 introduced those lines in GzipSpec during changes in the streams infrastructure:

```scala
pending // FIXME: unbreak
```

The tests still fail which means that gzip support is currently broken for some cases.

/cc @sirthias

**Comment by drewhk** [comment]
@jrudolph  This has been fixed, right?

**Comment by jrudolph** [comment]
No, this is some streams problem that was introduced during the Transformer => Stage migration.

**Comment by drewhk** [comment]
ok
