### ISSUE TITLE
doc: ReceivePipeline and PersistentActor don't play nicely

### ISSUE THREAD

**Issue by MaxWorgan** [akka/akka#17414]
ReceivePipeline must be mixed in before PersistentActor for them to work.

They both override ```aroundReceive``` but whereas ReceivePipeline calls ``super.aroundReceive``, PersistentActor doesn't. 

Consequently this works as expected:
```scala
 class PersistentReplierActor extends PersistentActor with ReceivePipeline {...}
```
but this doesn't:
```scala 
 class PersistentReplierActor extends ReceivePipeline with PersistentActor {...}
```

**Comment by ktoso** [comment]
This is more of an type linearization problem however I agree it can be documented more explicitly. 
Thanks for reporting!

**Comment by patriknw** [comment]
I agree. I don't see that we can make PersistentActor work in any mixin order. It should be documented.
