### ISSUE TITLE
[akka-http-core] issues with overriding `max-uri-length` param

### ISSUE THREAD

**Issue by viktortnk** [akka/akka#17422]
I'm trying to define `max-uri-lenght` param (akka.http.parsing.max-uri-length = 10k), but still have issues with request parsing which highlighting default value (2048)

```
[WARN] [05/07/2015 22:05:45.977] [whisk-connect-akka.actor.default-dispatcher-23] [ActorSystem(whisk-connect)] Illegal request, responding with status '414 Request-URI Too Long': URI length exceeds the configured limit of 2048 characters
```

This is coming from 

https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-RC1/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala#L105

However, if I try to instantiate `ServerSettings` or `ParserSettings` myself ( `ServerSettings(system)` ), I see correct value. Any idea where the value from config can get lost?

Thanks,
Viktor

**Comment by jrudolph** [comment]
@viktortnk you need to set the setting under `akka.http.server.parsing.max-uri-length`. The `akka.http.parsing` branch of the configuration is imported to `akka.http.server.parsing` and `akka.http.client.parsing` before user changes will be merged in, so you need to change the target values directly under the `server`/`client` namespace.

(If this doesn't work, please reopen)

**Comment by viktortnk** [comment]
@jrudolph Yes, I tried that yesterday as well

my config was

```
akka.http {

  server {
    remote-address-header = on
    parsing.max-uri-length = 10k
  }
  parsing.max-uri-length = 10k

  host-connection-pool.max-open-requests = 64
}
```

**Comment by jrudolph** [comment]
Hmm, it works here so somehow the setting isn't applied in your case. Try setting the value to an invalid value (e.g. string value) which should provoke an error message to see if the configuration is applied.

**Comment by viktortnk** [comment]
Sorry for that, must've messed with testing after setting server entry. :( Thanks!

**Comment by jrudolph** [comment]
No problem, glad it works now :)

**Comment by drcimux** [comment]
I have the same problem. I had this configuration, i use play 2.6 and i cant use Netty and POST:
` play.server.akka{
    http.server.parsing.max-uri-length = 16k
    http.client.parsing.max-uri-length = 16k      
    http.host-connection-pool.client.parsing.max-uri-length = 16k      
    http.max-uri-length = 16k
    max-uri-length = 16k
}

akka.http {
  parsing {
    max-uri-length = 16k
  }
}`
I had also in sbt file 
`PlayKeys.devSettings := Seq("play.akka.dev-mode.akka.http.parsing.max-uri-length" -> "1m")`
But i've read that it works only in development mode.
There a way to fix this problem in prod mode, inside configuration, without use this string on command line or in java_home ?
`-Dakka.http.parsing.max-uri-length=16k`
I had also this string in conf file but it doesn't work.

Thank you

**Comment by colomain** [comment]
Hi  @drcimux, have you found a working solution? Same problem here....

**Comment by fabianedl777** [comment]
Hello 

I found a hint to a fallback configuration where the user has the opinion to override the default akka http properties.

 _Modify to tweak default parsing settings. 
 IMPORTANT:
 Please note that this sections settings can be overriden by the corresponding settings in: `akka.http.server.parsing`, `akka.http.client.parsing` or `akka.http.host-connection-pool.client.parsing`._

Please try with this property **akka.http.server.parsing.max-uri-length = 10K** for me working this property.

**Comment by ranjithv** [comment]
I too have the same problem and it shows up as WARN in my logs:

`WARN [application-akka.actor.default-dispatcher-3] a.a.ActorSystemImpl [Slf4jLogger.scala:77] Illegal request, responding with status '414 Request-URI Too Long': URI length exceeds the configured limit of 2048 characters`

**Comment by jrudolph** [comment]
I think it would make sense to file this issue at https://github.com/playframework/playframework/ since it seems like a configuration issue in play.
