### ISSUE TITLE
FAILED: ClusterShardingLeavingSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17428]
https://jenkins.akka.io:8498/job/akka-release-2.3/179/consoleFull

[JVM-4] [WARN] [05/07/2015 21:07:23.091] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-14] [akka://ClusterShardingLeavingSpec/user/sharding/Entity] unhandled message from Actor[akka://ClusterShardingLeavingSpec/deadLetters]: MemberExited(Member(address = akka.tcp://ClusterShardingLeavingSpec@localhost:46490, status = Exiting))
[JVM-1] - must recover after leaving coordinator node *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg: Terminated Actor[akka://ClusterShardingLeavingSpec/user/sharding/Entity#-1175941464]
[JVM-1]   at scala.Predef$.assert(Predef.scala:179)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:356)
[JVM-1]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:718)
[JVM-1]   at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:368)
[JVM-1]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:718)
[JVM-1]   at akka.contrib.pattern.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10$$anonfun$apply$mcV$sp$12.apply$mcV$sp(ClusterShardingLeavingSpec.scala:178)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.contrib.pattern.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply$mcV$sp(ClusterShardingLeavingSpec.scala:176)
[JVM-1]   at akka.contrib.pattern.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply(ClusterShardingLeavingSpec.scala:171)
[JVM-1]   at akka.contrib.pattern.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply(ClusterShardingLeavingSpec.scala:171)
[JVM-1]   ...
[JVM-3] [INFO] [05/07/2015 21:07:24.083] [ClusterShardingLeavingSpec

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2419/consoleFull

**Comment by patriknw** [comment]
noticed this locally, to me it looks like a too short timeout (5.seconds) for the leaving to complete

**Comment by patriknw** [comment]
the timeout was increased in https://github.com/akka/akka/pull/17634
