### ISSUE TITLE
Make Serializer more friendly with persistence

### ISSUE THREAD

**Issue by ahjohannessen** [akka/akka#17434]
I intend to use protobuf to serialize all my domain events in our akka applications and would like to have a clear separation between types used in the domain and the types used for serialization. So it goes something like this (where  DT is domain type and PBT is protobuf type):

 persist(DT) -> ... -> Akka MessageSerializer -> Select serializer based on DT -> .. MySerializer that knows how to DT<->PBT -> Akka MessageSerializer -> .. -> Storage

As it works today, if I say that I wish to use manifest then Akka MessageSerializer will use the manifest from DT and not what I wish, PBT.

If we could have a `def provideManifest(payload: AnyRef)` method on `Serializer` that had a default implementation, doing what akka otherwise does today, then Akka MessageSerializer would delegate to the selected serializer to provide a manifest. In MySerializer I would get DT in and provide manifest for the corresponding PBT.

**Comment by ahjohannessen** [comment]
One solution is to wrap akka `MessageSerializer` in order to get the manifest of the protobuf type, but I see that more like a workaround, because then I need to make sure that my wrapper is in sync with Akka `MessageSerializer` when Akka is upgraded etc.

**Comment by patriknw** [comment]
sounds interesting

**Comment by patriknw** [comment]
@ahjohannessen please take a look at the proposed solution of a new `SerializerWithStringManifest` in https://github.com/akka/akka/pull/17601
Is that what you need?

**Comment by ahjohannessen** [comment]
Thanks @patriknw :+1:
