### ISSUE TITLE
Document handling failure in PersistentActors in more depth

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17442]
We may want to explain in more depth what the different options for handling persistence failure are. 
The current docs explain it, but rather briefly in just a few words.

**Comment by patriknw** [comment]
related to https://github.com/akka/akka/issues/16524

**Comment by patriknw** [comment]
I think I improved this in 2.4-M2
http://doc.akka.io/docs/akka/2.4-M2/scala/persistence.html#Failures
http://doc.akka.io/docs/akka/2.4-M2/scala/persistence.html#Journal_plugin_API
and a few other places inlined in the docs.
