### ISSUE TITLE
failed: RemoteReDeploymentSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17440]
when using java8

`timeout (3 seconds) during expectMsg while waiting for HelloParent`

Looks like something bad happens before this point. Slightly different log messages in the different runs.

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/9990/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/10008/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/10015/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/10020/consoleFull

**Comment by patriknw** [comment]
here is one with debug logs: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/10039/consoleFull

**Comment by patriknw** [comment]
RemoteReDeploymentSpec did not fail one single time of tonights 90 repeat runs. The fix is only to increase the timeouts, so we should anyway investigate why that is needed but it is not as urgent.
https://github.com/akka/akka/commit/ea5a4fa3e806bab25db683b6c6917af974c46fe4

I suspect that it is the same or similar problem as we have observed in #17314, i.e. new connection is stuck and after some timeout/retry it works again.

**Comment by ktoso** [comment]
Sounds reasonable! Thanks for investigating with timeouts

**Comment by drewhk** [comment]
This one have not failed in a while right? The ticket #17733 is something else?

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
