### ISSUE TITLE
When prefixAndTail() is called on a stream with a lazy empty tail, and prefixAndTail() is called again on the tail, the stream hangs.

### ISSUE THREAD

**Issue by catalin-ursachi** [akka/akka#17453]
(This problem has appeared as of RC1; we didn't encounter it in previous versions of Akka Streams)

Say we've got a source, as given by:

`val source = Source.single(Elem) concatMat Source.lazyEmpty[Elem.type] (...)`

We apply .prefixAndTail(1) on the source, and complete the promise materialized from the "lazy empty source". We then have a prefix and a tail; the tail, if ran, would turn out to contain no elements.

We then call .prefixAndTail(1) on the tail. We run the resulting source with a Sink.head, getting a Future[Seq[...], Source[...]]. We wait for the future to complete.

If we repeat the above 10,000 times, the future completes in some 9,970. It hangs in the other 30.

Funnily enough, if before calling .prefixAndTail(1) the second time, we precede it by .map(identity) (which, in principle, should of course do nothing), then the stream *does* complete 100% of the time.

The following set of tests illustrates the issue. All three tests should pass; but only the first and third do. The second fails with e.g. `'9980' is not equal to '10000'` (i.e. 0.2% of attempts failed)

```
package test

import akka.actor.ActorSystem
import akka.stream.ActorFlowMaterializer
import akka.stream.scaladsl.{Sink, Source}
import org.specs2.mutable.Specification
import org.specs2.time.NoTimeConversions
import scala.collection.immutable.Seq
import scala.concurrent.Await
import scala.concurrent.duration._
import scala.util.Try

class PrefixAndTailHangingErrorSpec
  extends Specification
  with NoTimeConversions {

  implicit val system = ActorSystem()
  implicit val materializer = ActorFlowMaterializer()
  
  case object Elem

  def foldSourceToList[T](source: Source[T, _]): List[T] =
    Await.result(source.runFold(List.empty[T])(_ :+ _), 5.seconds)

  // A source containing a single element, but which doesn't complete until the materialized promise is completed.
  def sourceWithLazyTail() =
    (Source.single(Elem) concatMat Source.lazyEmpty[Elem.type])((_, promise) => promise)

  // We apply prefixAndTail to the source, and complete the materialized promise.
  def applyOnce() = {
    val (promise, future) = sourceWithLazyTail()
      .prefixAndTail(1)
      .toMat(Sink.head)((_, _))
      .run()

    promise.success(())

    future
  }

  // We check that the prefix is a single-element list, and the tail is empty.
  def checkApplyOnce() = Try {
    // Given
    val prefixAndTailFuture = applyOnce()

    // When
    val (prefix, tail) = Await.result(prefixAndTailFuture, 5.seconds)

    // Then
    prefix mustEqual Seq(Elem)
    foldSourceToList(tail) mustEqual Nil
  }

  // We apply prefixAndTail to the tail. We check that the first prefix is a single-element list,
  // the second prefix is Nil, and the tail is empty.
  def checkApplyTwice() = Try {
    // Given
    val prefixAndTailFuture = applyOnce()

    // When
    val future = prefixAndTailFuture.flatMap { case (prefix, tail) =>
      tail
        .prefixAndTail(1)
        .runWith(Sink.head)
        .map { case (newPrefix, newTail) =>
        (prefix, newPrefix, newTail)
      }
    }

    val (firstPrefix, secondPrefix, tail) = Await.result(future, 5.seconds)

    // Then
    firstPrefix mustEqual Seq(Elem)
    secondPrefix mustEqual Nil
    foldSourceToList(tail) mustEqual Nil
  }

  // As above, except we call a (theoretically redundant)
  // .map(identity) on the tail before calling .prefixAndTail on it.
  def checkApplyTwiceWithIdentityMap() = Try {
    // Given
    val prefixAndTailFuture = applyOnce()

    // When
    val future = prefixAndTailFuture.flatMap { case (prefix, tail) =>
      tail
        .map(identity)
        .prefixAndTail(1)
        .runWith(Sink.head)
        .map { case (newPrefix, newTail) =>
        (prefix, newPrefix, newTail)
      }
    }

    val (firstPrefix, secondPrefix, tail) = Await.result(future, 5.seconds)

    // Then
    firstPrefix mustEqual Seq(Elem)
    secondPrefix mustEqual Nil
    foldSourceToList(tail) mustEqual Nil
  }

  "Prefix and tail" should {

    "successfully be applied once; succeed 10,000 times" in {
      // Given
      (1 to 10000).par.map(_ => checkApplyOnce()).count(_.isSuccess) mustEqual 10000
    }

    "successfully be applied twice; succeed 10,000 times" in {
      // Given
      (1 to 10000).par.map(_ => checkApplyTwice()).count(_.isSuccess) mustEqual 10000
    }

    "successfully be applied twice, with identity map; succeed 10,000 times" in {
      // Given
      (1 to 10000).par.map(_ => checkApplyTwiceWithIdentityMap()).count(_.isSuccess) mustEqual 10000
    }
  }
}
```

**Comment by drewhk** [comment]
This is either a bug, or one of those crazy but valid deadlock situations with stream-of-stream type operations. Will take a look.

**Comment by drewhk** [comment]
Thanks for reporting!

**Comment by drewhk** [comment]
I think you forgot to consume the tail in checkApplyTwiceWithIdentityMap.

**Comment by catalin-ursachi** [comment]
There seems to be a `foldSourceToList(tail) mustEqual Nil` at the end of the test - I think that consumes the tails in all 3 of them.

**Comment by drewhk** [comment]
Yes, but

    val (firstPrefix, secondPrefix, tail) = Await.result(future, 5.seconds)

    // Then
    firstPrefix mustEqual Seq(Elem)
    secondPrefix mustEqual Nil
    foldSourceToList(tail) mustEqual Nil

looks fishy, because in order to Await.result to return, the stream must be completed, but the stream will not complete, unless all the tails have been consumed.

Anyway, I will look into this in more detail later, currently I just randomly guessing.

**Comment by catalin-ursachi** [comment]
Hm, but, I would've thought that if you do:

```
val future = originalSource
  .prefixAndTail(5)
  .runWith(Sink.head)

val (headSequence, tailSource) = Await.result(future, 5.seconds)
```

Then the future does complete irrespective of whether the tailSource is consumed - indeed it can't even be accessed <i>until</i> the future completes - because prefixAndTail(N) + runWith creates demand for the first N elements (which go into the sequence) and doesn't need demand for the tail (which is returned as a source).

In any case, do mind that tests 1 and 3 do pass; it's 2 that fails 0.2% of the time.

**Comment by drewhk** [comment]
> Then the future does complete irrespective of whether the tailSource is consumed - indeed it can't even be accessed until the future completes

It can be accessed if you put a map between runWith and the Sink.head. I.e. you can move the consumption of the tail from the end of the test (after the Await) to the stream itself. That would settle that question. Also, I don't really remember, maybe prefixAndTail *does* complete the stream when the pair has been emitted.

> In any case, do mind that tests 1 and 3 do pass; it's 2 that fails 0.2% of the time.

That is why I need to actually run this and not just speculate :) I will revisit this ticket once I have time.

**Comment by drewhk** [comment]
Interesting enough, now an earlier test case fails, too, on my system.

**Comment by drewhk** [comment]
I put this back for now, but will revisit on Thursday.

**Comment by drewhk** [comment]
The rabbit hole might go deeper actually. I found weird problems with the original tests, but it seems to be currently related to Source(iterable). Will see if the two are related or not.

**Comment by drewhk** [comment]
There is no need for lazyEmpty btw, it fails also with Source.empty

**Comment by drewhk** [comment]
This is the correct reproducer:

      val pub = TestPublisher.manualProbe[Int]()
      val sub = TestSubscriber.manualProbe[Int]()

      val f = Source(pub).prefixAndTail(1).runWith(Sink.head)
      val s = pub.expectSubscription()
      s.sendNext(0)

      val (_, tail) = Await.result(f, 3.seconds)
      s.sendComplete()

      val tailPub = tail.runWith(Sink.publisher)

      tailPub.subscribe(sub)
      sub.expectSubscriptionAndComplete()

Fails with:

    expected class akka.stream.testkit.StreamTestKit$OnSubscribe, found class akka.stream.testkit.StreamTestKit$OnComplete$

The issue is that in those cases where prefixAndTail does not immediately see the upstream completed after the first element, then it opens a proper substream (otherwise it just uses Source.empty, since it already knows there will be no more elements). However, this substream does not obey the RS spec properly, because on completion it immediately sends an onComplete instead of sending an onSubscribe first. This was valid in the spec a while ago, but now it is no longer valid, and we rely on the first signal being onSubscribe.

**Comment by drewhk** [comment]
The fix should
 - make the actors barf on invalid onComplete/onError signals instead of ignoring them and getting stuck
 - make the substream implementation obey the spec

**Comment by drewhk** [comment]
A heads up for /cc @jrudolph @sirthias since Http makes use of stream-of-stream operations heavily.
