### ISSUE TITLE
In ActorInterpreter / ActorProcessor exceptions are created in postStop that may not be used

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17465]
Not sure what the purpose of those is. It seems they are catch-all fallbacks to make sure that downstreams are notified of an unexpected death of the actor backing a Publisher. As `postStop` is also called for the expected shutdown (and usually in much bigger volume) creating an exception including stacktrace is costly if the exception is thrown away right afterwards.

I propose to make the exception extend from `NoStackTrace` (the stack trace from `postStop` is probably not useful anyway) and/or restrict the creation of those exceptions to cases where it is still possible to relay it to downstream (i.e. downstream isn't completed yet).

(This turned up during benchmarking last week with percentages <10% but still significant, so I thought I post it here so it doesn't get lost for later optimization attempts.)

**Comment by drewhk** [comment]
Thanks, makes sense.
