### ISSUE TITLE
mapConcat is unnecessary strict with requiring a Seq. An Iterable would be fine, too.

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17464]

**Comment by patriknw** [comment]
Iterator does not have a bounded size. No problem?

**Comment by drewhk** [comment]
I think it isn't. Since we don't store the thing just pull out values as needed it can even stream an infinite amount of elements if someone desires so. Also, currently Sets don't work although they are strict.

**Comment by drewhk** [comment]
Funny enough, this would make implementation of IterableSource a

    Source.empty.mapConcat(iterable)

:)
