### ISSUE TITLE
ValidatePR must run multi-jvm tests

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17468]
Depends on https://github.com/sbt/sbt-multi-jvm/issues/9 sbt-multi-jvm becoming an AutoPlugin.
Then we should manually <<= it.

**Comment by ktoso** [comment]
lol, it actually already is an AutoPlugin, @hseeberger converted it a while ago :-)
No blockers here then!

**Comment by hseeberger** [comment]
If you want to know how to use it as an auto-plugin, take a look at
https://github.com/hseeberger/reactive-flows/blob/master/project/Build.scala#L15
https://github.com/hseeberger/reactive-flows/blob/master/build.sbt

**Comment by patriknw** [comment]
this is fixed, as far as I know
