### ISSUE TITLE
Would be good to have Https() (similar to Http()) as part of http-core DSL 

### ISSUE THREAD

**Issue by agolubev** [akka/akka#17489]
Right now there is no short and clear way in API to create https connection and use it as a source.
Per my understanding would be good to have something similar to:
```scala
val conn = Https().outgoingConnection("someDomainName.com")
Source.single(HttpsRequest()) via conn ...
```

**Comment by drewhk** [comment]
This is a duplicate, the current approach is in: https://github.com/akka/akka/pull/17471
