### ISSUE TITLE
would akka extension have lifecycle?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#17497]
would the ```Extension``` have methods like 
```
preStart()
postStop()
```
then we hook it to the actor system?

**Comment by hepin1989** [comment]
I think I could just hook to the terminate lifecycle by self via the system.registerOnTerminate.so This issue seems invalid.

**Comment by patriknw** [comment]
yes, use the ActorSystem hooks, closing since you have already came to the same conclusion
