### ISSUE TITLE
Numbered reference looks weird in rendered docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17505]
rst code like:

```
.. [1] See `The Magnet Pattern`_ for an explanation of magnet-based overloading.

// akka-docs-dev/target/sphinx/html/scala/http/routing-dsl/directives/form-field-directives/formFields.html#formfields
```

looks a bit weird currently: 
![formfields_ _akka_documentation](https://cloud.githubusercontent.com/assets/120979/7681188/2de906ea-fd6e-11e4-9ae6-1bd7c736a29e.png)

We should update the css styles so it does look nice.

**Comment by kukido** [comment]
Will something like that work:
![footnote](https://cloud.githubusercontent.com/assets/1329454/7900744/caa3dda4-071c-11e5-8142-1acbf666249e.png)

**Comment by ktoso** [comment]
Yes exactly, thanks!
