### ISSUE TITLE
Boiler plate reductions in working with and connecting Graphs - Fan In, Fan Out patters.

### ISSUE THREAD

**Issue by sirinath** [akka/akka#17509]
Can you consider following usages:

```
b.add(Broadcast[Int](2)(A ~> B, C ~> D))

b.add(Broadcast[Int](2)(A ~> B, C ~> D)(out1))
```

```
b.add(ZipWith[Int, Int, Int](math.max _)(in1, in2, in3))
```

``` 
... broadcast(2) ...

broadcast.out(A ~> B, C ~> D)
```

```
b.add(partGraph.wire(in1, in2, in3)(out))
```

Similarly for fan in patters, but 2nd curry will be for out the next curry is not specified.

Alternatively,

```
b.add(ZipWith[Int, Int, Int](math.max _).wire(in1, in2, in3)(out1))
```

Maybe you can pass the builder also in which case you do not need `b.add( ... )`

**Comment by sirinath** [comment]
There are 2 ways to approach the Graph creation: 

 - top down - start with big picture and workyourself down - currently supposed
 - bottom up - start with components and connections and work out the Graph - this needs to be supported also. This is more convenient in some cases especially in complicated cyclical graphs. Also closer to OO concepts.

**Comment by drewhk** [comment]
> bottom up - start with components and connections and work out the Graph - this needs to be supported also. This is more convenient in some cases especially in complicated cyclical graphs. Also closer to OO concepts.

This is fully supported. You can create partial graphs and reuse them, embed them in larger graphs etc.

**Comment by sirinath** [comment]
This is not what I meant. Connectors,  part graphs  has the mechanism to specifyconnections like in the above example.

**Comment by sirinath** [comment]
The wiring process is inverted.

**Comment by drewhk** [comment]
I don't understand what do you mean here.

**Comment by sirinath** [comment]
Instead of using builder.add Edge the component wires itself to the connections as above.

**Comment by sirinath** [comment]
I think the a fluent `wire` method which implicitly takes the builder and does the wiring is the best of the option. Few more characters but more convenient for bottom up wiring and reducing lines of code in come cases

**Comment by sirinath** [comment]
```
A ~> merge ~> C
D ~> merge 
G ~> merge 
```

becomes
```
B.wire(A, D, G)(C)
```

**Comment by sirinath** [comment]
Also to consider is:

```
A ~> merge ~> B  ~> merge ~> C  ~> broadcast ~> D ~> broadcast ~> E
        merge                                   <~  broadcast 
```

When the 2nd broadcast has connect to the 2nd merge.

It is good to have: `merge.input(1).wire(broadcast.output(1))` and `broadcast.output(1).wire(merge.input(1))`. Using one of the 2 should do the trick though both should be provided.

**Comment by drewhk** [comment]
I see what you mean now. You can already do these by making graphs dynamically, but some built-in patterns can make sense

**Comment by sirinath** [comment]
This might be worth to address this with the UX issue in builder

**Comment by sirinath** [comment]
Is it possible to see if you can consider this for 1.0?

**Comment by rkuhn** [comment]
I have not yet understood the issue; it seems “nice to have” in a low-priority kind of way—i.e. if someone were to open a PR there would be lots of bike-shedding :-)
