### ISSUE TITLE
Investigate if uncommons-maths can/should be updated

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17517]
Perhaps 
`val uncommonsMath = "io.gatling.uncommons.maths" % "uncommons-maths" % "1.2.3"`

**Comment by patriknw** [comment]
It can be problematic to change when the artifact group/name has changed though, because users might end up with duplicate classes on the classpath

**Comment by patriknw** [comment]
Another candidate, but jumping from version 1. to 3. sounds implausible

    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-math3</artifactId>
        <version>3.5</version>
    </dependency>

**Comment by guidomedina** [comment]
You guys are using version commons-math v2.2 atm for test I think, the 3 at the end is an old Apache convention, why? Like all the other Apache commons like lang, beanutils, etc.

**Comment by guidomedina** [comment]
I personally don't need maths for my project even with akka-remote so I have such dependency excluded anyway, I peek the code and I think that's only for SSL with Akka nodes so the question would be: Which would perform faster while preserving the intended security? Benchmark of two forks with SSL should answer that.

**Comment by drewhk** [comment]
we only use this library in remoting, in SSL support, for some RNG sources. We should eliminate these dependencies, there is no nee for them.

**Comment by patriknw** [comment]
see #12636
