### ISSUE TITLE
Http: control the number of connections accepted in parallel

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17512]
Current `Http.bindAndHandle` uses `Sink.foreach`. This has two downsides:

 * it allows an unlimited number of connections to be handled at the same time
 * it introduces a bottleneck where the code inside of `Sink.foreach` is serialized over all concurrently incoming connections

The suggested solution is to switch to use `mapAsyncUnordered` with a configured parallelism factor which returns a `Future` that only completes when the connection has been closed.

The second problem was reported in #17395 and #17508.

**Comment by drewhk** [comment]
Shouldn't the Future complete when the connection pipeline is established instead of when it is closed?

**Comment by drewhk** [comment]
See also https://github.com/akka/akka/issues/17461

**Comment by jrudolph** [comment]
It depends on whether you want to increase the number of connections concurrently being established or if you want to limit the total number of connections currently open. The first one is the less important one when the performance problems are gone, the second one would provide back-pressure on the number of concurrent connections which is currently missing in the API.

**Comment by drewhk** [comment]
Isn't there a configuration key for that?

**Comment by jrudolph** [comment]
Not yet, I created this ticket to find a solution.

**Comment by drewhk** [comment]
Ah ok, then it makes sense. We can also do buffer.mapAsyncUnordered, so buffer does the backpressure part, while mapAsyncUnordered parallelism level can be lower and used just to parallelize materialization. I think connection source on the IO level does the backpressuring properly.

**Comment by drewhk** [comment]
well, buffer is not enough to limit the connections open itself, sorry.

**Comment by jrudolph** [comment]
Fix merged with #17553.
