### ISSUE TITLE
Persistence: difference in failure signals between persist and saveSnapshot

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17518]
A customer recently pointed out that the variety in error reporting and callback styles in persistence is a bit confusing, examples:

- `persist() { ... callback ... }` yet `saveSnapshot() + get a SaveSnapshotSuccess() later`
- `PersistenceFailure` sounds like it's for all persistence failures, yet it's only for `persist` failures, the other ones are `ReplayFailure` and `SaveSnapshotFailure`

We should discuss these APIs before we freeze them in 2.4

**Comment by ktoso** [comment]
Relates to https://github.com/akka/akka/issues/17573 in which we discuss failing the Actor on `PersistenceFailure`.

We're OK with the response to saveSnapshot() being a message, as it's a more rare operation than `persist()`. We will make Recover consistent with this style: ____

**Comment by ktoso** [comment]
First thing to decide about this week I'd say :)

**Comment by patriknw** [comment]
My opinion (still), use messages for `saveSnapshot`, `deleteSnapshot`, `deleteSnapshots`, `deleteMessages`. All should have Success and Failure messages. Warning logging of Failure messages in unhandled.

`persist` and friends have callbacks `onPersistFailure` and `onPersistRejected`.

**Comment by ktoso** [comment]
Right, that sounds good. Current deviations which need to be fixed than are:

- [ ] remove `onDeleteMessagesFailure`
- [ ] just keep the `DeleteMessagesFailure()`
- [ ] add `DeleteMessagesSuccess()`
- [ ] make sure docs are good about `DeleteSnapshotsSuccess` (`deleteSnapshot(criteria)`) and `DeleteSnapshotSuccess` (`deleteSnapshot(seqNr)`)

**Comment by patriknw** [comment]
+1
