### ISSUE TITLE
Use assertAllStagesStopped in Http tests

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17524]
@patriknw created this helper method (in stream.testkit.Utils) which helped to uncover many of the leaks we had in streams-core. We whould use this in Http tests, too (where applicable).

**Comment by drewhk** [comment]
Be sure to base it on most recent head (after the fix in https://github.com/akka/akka/pull/17514)

**Comment by sirthias** [comment]
Is this closed by #17529?

**Comment by drewhk** [comment]
I think it covers only a subset. You should validate where it makes sense to use it in other places. If you find that all relevant tests are covered then this ticket can be closed.

**Comment by ktoso** [comment]
Let's add the checks soon, in 1.1.

**Comment by ktoso** [comment]
That's a nice one to pick up if you had the time @johanandren :) // tomorrow of course

**Comment by johanandren** [comment]
Adding closeNetworkInput/expectNetworkClose/assertAllStagesStopped to HttpServerSpec
    test makes it fail with ```assertion failed: expected OnComplete, found OnSubscribe(...)`. Not sure if it is because I have no idea what I am doing or there actually is something weird going on.

Tried using ```netOut.probe.fishForPF``` for ```OnSubscribe => false``` + ```OnComplete => true```, but then it just fails because of never getting the ```OnComplete```

**Comment by johanandren** [comment]
Would be happy for some feedback from @jrudolph or @sirthias about this.

**Comment by ktoso** [comment]
The PR under discussion is https://github.com/akka/akka/pull/18749/files

**Comment by jrudolph** [comment]
@johanandren  funny, that you find that just now. I think this is directly related to a change I just proposed: https://github.com/akka/akka/pull/18748/files#diff-f3a816c2a9e353d4e7c075320c6f53ceR599

Automatic probes are not smart enough to expect subscription first and then completion.

**Comment by jrudolph** [comment]
Related to this issue, there's still #18005 open.

**Comment by johanandren** [comment]
Tried applying https://github.com/spray/akka/commit/fa6f13783b716875823cd11de09c66636e96a6a8 first, then it fails because it never gets any ```OnComplete``` (the same as my try with ```fishForPF```)

**Comment by johanandren** [comment]
#18005 would be later, when ```expectNetworkClose()``` has not failed and the actual ```assertAllStagesStopped``` logic as far as I understand

**Comment by jrudolph** [comment]
@johanandren wrt #18005 I didn't mean your current issue but the original issue tracked here.

**Comment by jrudolph** [comment]
Your issue might be that completion is blocked by missing demand.

**Comment by johanandren** [comment]
Hmm. Tried to force demand by making probe on `netOut` accessible and calling `request(10)` on it without success. I'm going to give up for now and set this issue back to "pick next".

**Comment by ktoso** [comment]
Let's have a look at this during one of the bug-days and close then

**Comment by johanandren** [comment]
Actual resource leak bug found #20298, there is a second test failing that I haven't looked into yet.
