### ISSUE TITLE
failed: MultiNodeSample

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17537]
https://jenkins.akka.io:8498/job/akka-nightly/2267/consoleFull

    [JVM-2] A MultiNodeSample
    [JVM-2] - must wait for all nodes to enter a barrier
    [JVM-1] - must wait for all nodes to enter a barrier
    [JVM-1] - must send to and receive from a remote node *** FAILED ***
    [JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for pong
    [JVM-1]   at scala.Predef$.assert(Predef.scala:165)
    [JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
    [JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
    [JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(MultiNodeSample.scala:49)
    [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MultiNodeSample.scala:45)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeSample.scala:44)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeSample.scala:44)
    [JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2268/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2271/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2272/consoleFull

**Comment by ktoso** [comment]
Failed again a few times, I'm expecting this to be just timing sensitive - nothing complex going on in the tests there.
I'll increase the timeout.
