### ISSUE TITLE
Rerouting streams based on content

### ISSUE THREAD

**Issue by rcgoodfellow** [akka/akka#17548]
Hi,

I am trying to use Akka-Streams to do some content based routing of TCP streams. I have attached a simplified complete and runnable example [here](https://gist.github.com/rcgoodfellow/67b060dd8f4f39b33f18), but the key part I think is the following

```scala
  //create a flow that redirects a stream to a port based on a content prefix
  val flw =
  Flow[ByteString]
    .groupBy { _.utf8String.take(4) } //routing prefix is first 4 chars of stream
    .map { case (port, src) =>
      println(s"OUT++> $port")  //debug - this part is working
      src via Tcp().outgoingConnection("localhost", port.toInt) //connection gets created but no flow
    }
    .flatten(FlattenStrategy.concat) //not sure about this part

  //create a TCP entry point for the stream to come in
  val primaryIn = Tcp().bind("0.0.0.0", 6666)
  val primaryHandler =
  primaryIn runForeach { connection =>
    println(s"primary connection from ${connection.remoteAddress}")
    connection handleWith flw
  }
```
The ```groupBy ``` works just fine, I get the content I need to perform the route, and create the ```Tcp().outgoingConnection``` just fine. However, as data comes into the ```primaryIn``` it does not make it to the ```outgoingConnection``` created in the map. What am I missing here?

Also a note: I tried implementing this in a ```PushStage``` in which I was able to push the data downstream but I was getting a new ```Tcp().outgoingConnection``` for each ```ByteString``` chunk.

**Comment by drewhk** [comment]
First of all, you need to run the internal flow, i.e:

    src.via(outgoingConnection).to(Sink.ignore).run()

You just wired a source to it but didn't run. 
Also, flattening a groupBy is an inherently dangerous combination, and if you don't know what you are doing you will deadlock with 99% probability (I just made up the number ;) ). You should look into this recipe which describes the deadlock scenario: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC2/scala/stream-cookbook.html#Implementing_reduce-by-key

**Comment by drewhk** [comment]
Ah, forget my first comment, you don't run it because you use the flattening on the resulting source. But the second comment is still relevant.

**Comment by rcgoodfellow** [comment]
Thanks @drewhk! Your comments about deadlock and the link provided were quite helpful in aiding my understanding of nested streams. Based on that link I think I should be able to put together something that works.

One further question, in this implementation each ```ByteString``` coming across a TCP data stream must contain the routing data. Is it possible to do this only for the first ```ByteString``` that comes across a TCP connection. Or is this objective outside the scope of Akka-Streams. Essentially what I would be after is to inspect a few of the leading bits of the stream and then redirect to remaining data as it comes in based on the results of the inspection.
