### ISSUE TITLE
Review setting paths in akka-http for consistency with package names

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17541]
Currently there's

 * `akka.http.server` and `akka.http.client` for the core settings (makes sense as they are shared between java and scala)
 * `akka.http.routing` to configure routing things which will probably also be shared between scala and java side but there's no code package `akka.http.routing`, so this may be confusing on first sight

/cc @sirthias

**Comment by ktoso** [comment]
Would be good to do in `1.1` though I don't think it's *that* confusing, as long as we always give full paths in docs people will learn it quickly.

TODO: check docs if they explain full paths of config options.

**Comment by ktoso** [comment]
We have a new offender here – in new javadsl marshalling lives in javadsl and in scaladsl it lives in scaladsl.marshalling, we should make those consistent.

**Comment by ktoso** [comment]
Those were made consistent recently - moved javadsls
