### ISSUE TITLE
Missing runWithMat for RunnableFlow

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17559]
I had a case where I just need to expose the materialized values of a source and sink, nothing else.
This is doable via `toMat + run()`, however it is not possible to `runWithMat(sink)(Keep.both)`.

```scala
val (ref, pub) = 
  Source.actorRef(Int.MaxValue, OverflowStrategy.fail)
    .toMat(Sink.publisher)(Keep.both)
    .run()
```

With `runWithMat` it would be: 

```scala
val (ref, pub) = Source.actorRef(...).runWithMat(Sink.publisher)(Keep.both)
```

**Comment by drewhk** [comment]
ok, makes sense to me

**Comment by rkuhn** [comment]
Reasoning: `run` is somewhat outside of the normal DSL scope and `runWith` is some “strange” convenience method. The API is too big already, so let’s not add new methods.
