### ISSUE TITLE
SingleConsumerOnlyBoundedMailbox using LMAX disruptor

### ISSUE THREAD

**Issue by guidomedina** [akka/akka#17558]
I was following up an old discussion and found that the proposed LMAX disruptor mailbox was a bit out of context and when I tested it was blocking, also being compared against a wrong counter-part `SingleConsumerOnlyUnboundedMailbox`

LMAX disruptor has its limitations and proper usage scenarios, in my case I'm using it on a very low latency single consumer actors with several producers, and I don't want unlimited mailbox size nor block if mailbox is full so I created a `SingleConsumerOnlyBoundedMailbox` based from the original proposed by ***Igor Konev*** with the following properties/mods:

* It is almost a copy of `BoundedMailbox` except that it doesn't try to offer with a timeout until there is either space on the mailbox or times out so it just fail-fast by dropping the envelope into the dead letters.
* It is designed to be `SingleConsumerOnly` with multiple producers just like `SingleConsumerOnlyUnboundedMailbox`
* It is written in Java 8 so it needs a Scala volunteer to port it.
* Buffer size must of a power of 2 *-LMAX disruptor design requirement-* and buffer is pre-allocate it making it not so good for many mail boxes with a big buffer unless you have the world's RAM.

So here is my forked and modified version of the original: https://github.com/guidomedina/akka-disruptor

**Note:** I know I need to sign an agreement for contributing but in this case, the code is in Java and needs *someone else* to port it.

**Comment by drewhk** [comment]
Thanks, sounds awesome!

**Comment by guidomedina** [comment]
Ummm, after some digging I have come to the conclusion that LMAX disruptor are good for inter-process communication, which reserving a buffer makes sense, so now I'm unsure if following the same strategy as you have in `AbstractNodeQueue<T>` would make more sense, it would be nice to have a bounded single consumer mailbox with fail-fast characteristics, just borrow it again as you did for `SingleConsumerOnlyUnboundedMailbox`, I think the current Bounded is not as good:

```
/**
 * Lock-free MPSC linked queue implementation based on Dmitriy Vyukov's non-intrusive MPSC queue:
 * http://www.1024cores.net/home/lock-free-algorithms/queues/non-intrusive-mpsc-node-based-queue
 */
```

**Comment by guidomedina** [comment]
Closing issue, I was able to create this type of mailbox by using JCtools.

**Comment by ktoso** [comment]
Feel free to share it :-)

**Comment by guidomedina** [comment]
Let me Gist it, will remove this comment as soon as it is done.

**Comment by guidomedina** [comment]
Gist: https://gist.github.com/guidomedina/ddd729492c8fb8148032
