### ISSUE TITLE
Decide the fate of UntypedPersistentActor vs. AbstractPersistentActor

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17563]
We should decide if we keep both or not. 
Akka 2.4 requires JDK8, so in theory everyone using 2.4 can use `AbstractPersistentActor`.

Do we want to remove `UntypedPersistentActor` or keep it around?
Relates to deciding about `UntypedActor`

**Comment by patriknw** [comment]
Interesting question, and it relates to if we will remove the experimental label from `AbstractActor` now.

**Comment by ktoso** [comment]
AFAIR decision was to keep both for now.

Reasoning:
- using the PartialFunction builder has some performance overhead
- AbstractActor is not yet out of experimental, we may revisit this topic once we promote it to stable (could well be during 2.4).
