### ISSUE TITLE
Source(Seq(1,2,3)) doesn't compile

### ISSUE THREAD

**Issue by kostya-sh** [akka/akka#17578]
Scala docs (http://doc.akka.io/api/akka-stream-and-http-experimental/1.0-RC3/index.html#akka.stream.scaladsl.Source$) mention that a `Source` can be created from an `Iterable` like this `Source(Seq(1,2,3))`. However I get the following compilation error:

```
[ERROR] MySandboxScalaMadness.scala:6: overloaded method value apply with alternatives:
  [T](future: scala.concurrent.Future[T])akka.stream.scaladsl.Source[T,Unit] <and>
  [T](iterable: scala.collection.immutable.Iterable[T])akka.stream.scaladsl.Source[T,Unit] <and>
  [T](f: () => Iterator[T])akka.stream.scaladsl.Source[T,Unit] <and>
  [T](publisher: org.reactivestreams.Publisher[T])akka.stream.scaladsl.Source[T,Unit] <and>
  [Out, Mat](g1: akka.stream.Graph[akka.stream.Shape,Mat])(buildBlock: akka.stream.scaladsl.FlowGraph.Builder[Mat] => (g1.Shape => akka.stream.Outlet[Out]))akka.stream.scaladsl.Source[Out,Mat]
 cannot be applied to (Seq[Int])
[ERROR]   Source(Seq(1, 2, 3))
[ERROR]   ^

```

```Source(List(1,2,3))``` works though

I am using Scala 2.11.6 and akka-streams 1.0-RC3

**Comment by drewhk** [comment]
That is because it accepts an immutable.Iterable, while the Seq imported from Predef is not immutable. Import the immutable.Seq and it will work.

**Comment by kostya-sh** [comment]
Is there any reason why only immutable.Iterable can be used to create a Source?

I think changing the sample in docs to use List instead of Seq will make it less surprising.
