### ISSUE TITLE
suppress Tcp.CloseCommand from deadLetters logging

### ISSUE THREAD

**Issue by fommil** [akka/akka#17572]
As requested from the mailing list. I trust you agree that Close-style messages are more likely than most to arrive in deadLetters and are hence more likely to be spam than something the user wants to hear about.

Please note that it is quite difficult for me to make changes to the akka repo due to #17570

This is an issue equivalent of #17571 as I am not signing the Typesafe CLA in light of the direction taken by Slick Extensions.

```
diff --git a/akka-actor/src/main/scala/akka/io/Tcp.scala b/akka-actor/src/main/scala/akka/io/Tcp.scala
index d9cc16a..1f9e621 100644
--- a/akka-actor/src/main/scala/akka/io/Tcp.scala
+++ b/akka-actor/src/main/scala/akka/io/Tcp.scala
@@ -172,8 +172,12 @@ object Tcp extends ExtensionId[TcpExt] with ExtensionIdProvider {
 
   /**
    * Common interface for all commands which aim to close down an open connection.
+   *
+   * These messages are suppressed from dead letters as they are
+   * highly likely to be received on actor paths that have recently
+   * been terminated.
    */
-  sealed trait CloseCommand extends Command {
+  sealed trait CloseCommand extends Command with DeadLetterSuppression {
     /**
      * The corresponding event which is sent as an acknowledgment once the
      * close operation is finished.
```

**Comment by cowboygneox** [comment]
+1

**Comment by carlosvilchez** [comment]
+1

**Comment by stsatlantis** [comment]
+1

**Comment by jozic** [comment]
+1

**Comment by ktoso** [comment]
With so many +1 I'd have thought one would submit this one-liner patch :smile: No takers? :-)

**Comment by fommil** [comment]
I'd actually recommend this for the next 2.3.x release. It's a real pain.

**Comment by douglaz** [comment]
+1

**Comment by patriknw** [comment]
I share @ktoso thoughts. Strange, but I will do it now.

**Comment by fommil** [comment]
thanks for including in 2.3.12!

**Comment by fommil** [comment]
:smile:
