### ISSUE TITLE
upgrade scalariform

### ISSUE THREAD

**Issue by fommil** [akka/akka#17570]
your version of sbt-scalariform is old and anyone using a more recent version in their user config will trump it (and reformat a lot of files). I recommend changing https://github.com/akka/akka/blob/master/project/plugins.sbt#L14 to

```
addSbtPlugin("org.scalariform" %% "sbt-scalariform" % "1.4.0")
```

(note change of groupId)

I would have sent a PR but I can't do a clean `sbt compile test:compile it:compile` etc owing to missing snapshots that you depend on.

**Comment by patriknw** [comment]
sounds good

missing snapshots? please elaborate

**Comment by fommil** [comment]
```
sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-persistence-experimental_2.10;2.4-SNAPSHOT: not found
```

and many more...

**Comment by patriknw** [comment]
ah, that is from the sample projects
yeah, we are breaking out those from the build
until then you have to first do a publishLocal (hm is there a cycle here?)

**Comment by 2m** [comment]
Alternatively you can leave out sample builds from the aggregate build by starting sbt like so:
```
sbt -Dakka.build.aggregateSamples=false
```

**Comment by patriknw** [comment]
I don't think it was the samples. At least not for master. _2.10 is not something we use in master (unless it has been forgotten somewhere) and I tried a clean build (removed ivy cache) without problems.
