### ISSUE TITLE
Scalariform link on contributing.md to point to new Scalariform repository

### ISSUE THREAD

**Issue by jjvester** [akka/akka#17587]
Scalariform has moved to a new repository location and to avoid confusion, I think it prudent we correct the navigation link on the contributing.md guide to point to the new location.

The new location is https://github.com/daniel-trinh/scalariform

**Comment by ktoso** [comment]
Excellent catch @jjvester, agreed!
Would you like to submit the PR?

**Comment by jjvester** [comment]
Sure would love to, my first contribution, would be my pleasure :)

**Comment by ktoso** [comment]
Awesome, please make the change on the `master` branch :)

**Comment by jjvester** [comment]
Novice question here, how do I attach my pull request to this issue or can I simply submit a pull request?

I have created a branch on my fork with the issue number as a prefix to the branch name and am ready to submit the pull request diff'ing the original master with my fork/branch

**Comment by ktoso** [comment]
Cool :-) You open the PR independently, then in the comments we add "Refs #17587" which establishes a link between those. 

Afterwards:
In the PR we do code review if needed, then merge and close the linked ticket. The ticket is assigned to the Milestone on which it will be released.

**Comment by jjvester** [comment]
OK thank you, I submitted the pull request.

**Comment by ktoso** [comment]
Thanks again for the contribution! :-)
