### ISSUE TITLE
PersistentActor can't become receiveCommands handler during recovery

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17581]
We acknowledge this limitation however do not have plans to address it within the current `PersistentActor` API. Future persistence APIs, perhaps the AkkaTyped one, should revisit this ticket and see if/how to provide this capability.

The effect of this limitation is that passing state from recovery to normal operation must be done as state (var) within the actor.

**Comment by ktoso** [comment]
@patriknw you think this is actionable? I'm not sure it is actually.
I mean it could be documented but doesn't gain anything until we have the Typed API to show as "hey look, here's a pure way to do it".

Or make it a persistence+typed ticket?

**Comment by patriknw** [comment]
I agree. This is a limitation we can live with in `PersistentActor`, and nice if we can solve in akka-typed.

**Comment by patriknw** [comment]
keeping this for Akka Typed

**Comment by patriknw** [comment]
For this reason we don't support become in typed PersistentActor
