### ISSUE TITLE
Investigate safety of persists mixed with saveSnapshot

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17585]
There *may be* an issue with how we bump sequence numbers when calling persist, and how `saveSnapshot` uses this information. 

Make sure saveSnapshot is always safe to use or throws/signals failure if it is unsafe.

**Comment by patriknw** [comment]
I looked at the code for this, and I can't see any hole. saveSnapshot is using `lastSequenceNr`, which is updated during replay and immediately before the persist handler callback is invoked (when receiving WriteMessageSuccess).

**Comment by ktoso** [comment]
I have looked into it previously and did not find problems, I'll give it a last skim and close this week then.
