### ISSUE TITLE
Shouldn't PersistentActor be notified if deleting a snapshot fails?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17586]
Currently it would be silently ignored.

This relates to https://github.com/akka/akka/issues/15188 in which we should change the SnapshotStore such that `def delete(metadata: SnapshotMetadata)` returns a `Future[Unit]` and not `Unit` like now.

Yes it's a rare case I agree, but feels a bit weird that we don't provide any info if it fails.

**Comment by patriknw** [comment]
makes sense to have same messages as for saveSnapshot
