### ISSUE TITLE
Create overload for UpgradeToWebsocket.handleMessages that takes separate source and sink

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17609]
Just for cosmetic reasons to supply those separately if both ends of the bidirectional websocket channel aren't logically linked.

See http://stackoverflow.com/questions/30479777/integrating-an-ack-based-actor-with-akka-stream?noredirect=1#comment49124618_30479777 for a bit of background.

/cc @sirthias

**Comment by fommil** [comment]
I'd be happy with it taking a `Flow` if there was a simple one liner to convert a Sink/Source to a Flow for this purpose.

**Comment by drewhk** [comment]
Flow.wrap is what you are after

**Comment by fommil** [comment]
`Flow.wrap` takes a `Graph`

**Comment by fommil** [comment]
can this then be closed?

**Comment by jrudolph** [comment]
Let's keep it open to either add the overload or at least a documentation comment how to achieve the same with `Flow.wrap`.

**Comment by fommil** [comment]
hold on

```
wrap[I, O, M1, M2, M](sink: Graph[SinkShape[I], M1], source: Graph[SourceShape[O], M2])(f: (M1, M2) ⇒ M)
```

That means providing  function. This isn't as convenient as I thought it was.

**Comment by jrudolph** [comment]
You can use one of the `Keep.XXX` for the function.

**Comment by drewhk** [comment]
And Source/Sink are subclasses of Graph[SourceShape]/Graph[SinkShape]

**Comment by fommil** [comment]
neither the `f` nor the `Keep` is documented, so I can only guess as to what it means. Assuming `M1` and `M2` are the `Outgoing` and `Incoming` messages, respectively, then I don't see when one would ever have to choose between such messages.

**Comment by danielwegener** [comment]
@jrudolph Just as I stumbled upon this and its kind of the same place: Is there yet any user api to negotiate the ws-protocol between server and the client?  `handleWebsocketMessages` does seem to deal only with an unspecified protocol (and rejects any other). The following does the trick somehow but it might pretty much be the wrong place.

```scala
def handleWebsocketMessagesWithProtocol(protocol: String, handler: Flow[Message, Message, Any]): Route =
      extractFlowMaterializer { implicit mat ⇒
        optionalHeaderValueByType[UpgradeToWebsocket]() {
          case Some(upgrade) if !upgrade.requestedProtocols.contains(protocol) ⇒ complete(upgrade.handleMessages(handler, None))
          case Some(upgrade)                                                   ⇒ complete(upgrade.handleMessages(handler, Some(protocol)))
          case None                                                            ⇒ reject(ExpectedWebsocketRequestRejection)
        }
      }
```

**Comment by fommil** [comment]
@danielwegener :+1: and also the ability to ensure that the WebSockets connection is using message compression.

**Comment by jrudolph** [comment]
@fommil compression is currently unsupported. I created #17725 to track adding support for compression.

**Comment by jrudolph** [comment]
@danielwegener right. This is an oversight and is now tracked by #17726.

**Comment by jrudolph** [comment]
The original issue was fixed in #17660. For the other issues raised here new tickets were created, right?

**Comment by fommil** [comment]
@jrudolph is this in an RC or milestone release that I can play with? Although I don't feel that akka-stream's WebSockets is "there yet" for my day job, it's probably good enough for ENSIME (we have no burning need for compression or backpressure) so I'd like to start using it in the next week.

**Comment by fommil** [comment]
uuh, do we have a websocket client in akka-stream that I can use for testing?

**Comment by fommil** [comment]
crying out to be used here...

https://github.com/fommil/ensime-server/blob/websocket/server/src/main/scala/org/ensime/server/WebServer.scala#L41
