### ISSUE TITLE
should log exceptions when start the actor system.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#17607]
I think should add some exception log here.
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L671

**Comment by patriknw** [comment]
Isn't that exception rethrown to the one who is creating the actor system?

**Comment by hepin1989** [comment]
yes,I don't log the exception.will close ,thanks.

**Comment by patriknw** [comment]
good
