### ISSUE TITLE
Akka-stream throughput checking Flow [feature-request]

### ISSUE THREAD

**Issue by l15k4** [akka/akka#17614]
Hey,

I think a lot of people would appreciate a Flow that would seamlessly help dealing with strange throughput decreases/issues. Either in form of logging & profiling capabilities or throwing exceptions that would reveal the culprit.

Imagine having a stream of 10 components using 5 different remote services and the stream suddenly looses 50% of original throughput, there is almost no way of targeting this problem right now which leads to a whole day of troubleshooting because you don't know whether it is caused by the services, by akka version upgrade or by a new feature you added. It's madness unless you are an akka-stream guru :-)

Based on these 2 discussions : 

[stream-idling-on-suddenly-slowed-down-services](https://groups.google.com/forum/#!topic/akka-user/D5Nw1s9DVF4)

[profiling-options](https://groups.google.com/forum/#!topic/akka-user/emBAWO2rxsU)

**Comment by rkuhn** [comment]
Within a stream we can at best create combinators that measure throughput and allow reactions to the measured values, but in a back-pressured system this will not tell you where the problem lies—it could even be downstream. This concern will need to addressed by external holistic monitoring tools.
