### ISSUE TITLE
Improve UX of looking for javadoc failures in PR validation

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17611]
The way javadoc reports errors is rather confusing, and bound to confuse contributors.
Maybe we could include our script to find the real errors in the validation job or improve the task somehow to be more helpful?

For reference the perl script that helps to find errors:

``` perl
#!/usr/bin/perl

use strict;
use warnings;

my $active = 0;
my $print = 0;
while (<>) {
  $active = 1, next if /Generating.*\.html/;
  $active = 0, next if /Genjavadoc Java API documentation successful\./;
  $print = 1 if /^\[error].*error:/;
  $print = 0 if /warning:/;
  print if $active && $print;
}
```

**Comment by rkuhn** [comment]
Yes, we should somehow include this in the Jenkins job, not sure how, though.

**Comment by ktoso** [comment]
I guess 066a0bd  addresses this somewhat, closing for now
