### ISSUE TITLE
Incorrect documentation for the tell method in class akka.actor.ActorRef

### ISSUE THREAD

**Issue by dodnert** [akka/akka#17618]
The documentation for the [tell](http://doc.akka.io/api/akka/2.3.9/index.html#akka.actor.ActorRef@tell(msg:Any,sender:akka.actor.ActorRef):Unit) method in class `akka.actor.ActorRef` reads as follows.

> Sends the specified message to the sender, i.e. fire-and-forget semantics, including the sender reference if possible.

This sentence should be corrected to explain that the message is sent to the actor identified by `this` actor reference, not to the sender.

**Comment by patriknw** [comment]
thanks

**Comment by dodnert** [comment]
This issue has been fixed by commit 2d8cb3764eaa9efca89db93362b84ca0df022ebc

**Comment by ktoso** [comment]
Seems fixed, by the commit @dodnert points out. Closing.
