### ISSUE TITLE
Create a variant of `Source.actorRef` that uses simple acking for backpressure

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17610]
This would allow a simpler migration path for systems which have used an application-level Ack-based model in the past and would like to update parts of the processing pipeline to streams without having to convert everything at one go or having to implement `ActorPublisher` manually.

One possibility would be to introduce another overload

``` scala
def actorRef[T](bufferSize: Int, ack: AnyRef): Source[T, ActorRef]
```

which responds to a message with an `ack` as long as (or as soon as) buffer space is available.

See also http://stackoverflow.com/questions/30479777/integrating-an-ack-based-actor-with-akka-stream?noredirect=1#comment49124723_30479777

**Comment by drewhk** [comment]
This is actually similar to mapAsync but reversed. It would be interesting to see if this can be implemented in a more generic way making it a Flow instead (which then can be used to create the desired Source in turn) using the new AsyncStage.

**Comment by jrudolph** [comment]
The point is to expose an `ActorRef` target, how would that work with a Flow?

**Comment by fommil** [comment]
a `Sink` variant would also be good.

It would be good if the actual ack message could be defined, as it is in akka-io.

**Comment by fommil** [comment]
btw, I don't care about the buffer here. If the underlying actor sends a message without having received an `Ack` that's an API error.

**Comment by drewhk** [comment]
> The point is to expose an ActorRef target, how would that work with a Flow?

It could only work if there is a separate registration message, true.

**Comment by fommil** [comment]
@jrudolph I thought you were also going to create a ticket to allow the user to provide a source and sink to a WebSockets handler, without having to construct a `Flow` explicitly?

**Comment by fommil** [comment]
@jrudolph are you going to scaladays? Give me a ping if you are (I'll be talking about ENSIME, sadly at the same time as sirthius)... I'll owe you a few beers if you're working on this :smile:

**Comment by loicdescotte** [comment]
I'm not sure to understand why you need a ack parameter, but it would be definitely great to be able to get an ActorRef from a Source, without writing one manually.   
Especially for generic cases like that : http://stackoverflow.com/a/29077212/591922  
For more specific strategies (e.g. keep a max amount of item in the list), it makes more sense to write a custom ActorPublisher.

**Comment by drewhk** [comment]
@loicdescotte, what is wrong with this: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/stream-integrations.html#Source_actorRef ?

**Comment by jrudolph** [comment]
> Especially for basic cases where the ActorPublisher simply stores source items in a simple bounded list.

The `ack` is the mechanism by which you can make the upstream sender of items stop sending more items if the bounded list is full.

As @drewhk says, there's already `Source.actorRef` which operates on a bounded buffer but which isn't able to communicate to the upstream sender when the list is full. That's why there's this ticket.

**Comment by loicdescotte** [comment]
@drewhk @jrudolph Sorry my comment was not clear at all :)  

The problem I see with Source.actorRef, but I must be misunderstanding how it works, is that when you define a source like this : 

``` val source = Source.actorRef[Item](Int.MaxValue, OverflowStrategy.fail)```

Then to get the ref, you need to do something like this to get the actor ref : 

```
  val ref = Flow[Item].to(Sink.ignore).runWith(source)
```

You can replace `Sink.ignore` by any Sink, but if you don't want to define the way the source will be consumed right now, it's a problem. For example if I want to keep the source without consuming items and merge it with another source later, in my understanding it's not possible with Source.actorRef.

So I think it would be handful to be able to get a "default" ActorPublisher like this one, to be able to elements into a source : http://stackoverflow.com/a/29077212/591922

Did I miss something?

**Comment by drewhk** [comment]
You can only get the ActorRef after materialization. Before that, the Source is not running, there is no actor to get the reference of. Therefore, if you want to reuse that Source in various settings, you need to handle its materialized value via the xMat methods, and propagate it to the use site.

**Comment by jrudolph** [comment]
@loicdescotte the topic of materialization is conceptually separate from the topic of how to implement a source / publisher. Materialization allows you to reuse a `Source`. Any hand-written reusable `ActorPublisher` would exhibit the exact same problem with materialization as `Source.actorPublisher` also gives you the `ActorRef` only after materialization.

So, either you go with reusability and, as @drewhk said, feed the result of materialization back to where it's needed, or if you don't care for reusability you can use this trick to create a one-time Source and instantly get to the `ActorRef` (which is still a lot better than writing your own `Publisher`):

```scala
val (ref, publisher) = Flow[Item].toMat(Sink.publisher)((a, b) => (a, b) /* or `Keep.both` */).runWith(source)
val source = Source(publisher)
```

**Comment by drewhk** [comment]
Maybe reverse it (no need for Flow):

     val (ref, publisher) =  Source.actorRef[Item].toMat(Sink.publisher)(Keep.both).run()
     val source = Source(publisher)

Btw, it might make sense to expose this pattern as a built-in method

   val (ref, source) = Source.actorRef[Item].preMaterialize()

**Comment by jrudolph** [comment]
(Of course, I just stupidly copied the code from above)

**Comment by drewhk** [comment]
Added ticket for built-in support: https://github.com/akka/akka/issues/17769

**Comment by loicdescotte** [comment]
@drewhk @jrudolph thanks this is great!

**Comment by drewhk** [comment]
I still recommend propagating the materialized value explicitly though.

**Comment by loicdescotte** [comment]
Sorry, I hope I'm not polluting the issue... 

@jrudolph 
"Any hand-written reusable ActorPublisher would exhibit the exact same problem with materialization as Source.actorPublisher also gives you the ActorRef only after materialization." 
In  fact , if I use a custom actor like in [this exemple](http://stackoverflow.com/a/29077212/591922), I can use the source to merge it with another and it's working very well. I can consume a merged stream in the end with data from several sources.

@drewhk 
"I still recommend propagating the materialized value explicitly though." 
I need to go deeper in the API to udnerstand how to do this.  Thanks a lot for your help.

**Comment by jrudolph** [comment]
> In fact , if I use a custom actor like in this exemple, I can use the source to merge it with another and it's working very well. I can consume a merged stream in the end with data from several sources.

The example uses `Source(ActorPublisher[Int](actorRef))` which means the resulting `Source` isn't reusable, i.e. you start with the `actorRef` to the publisher and create a one-time `Source` from it. You could use `Source.actorPublisher(props)`, instead, which would make it reusable but would give you `actorRef` after materialization...

**Comment by loicdescotte** [comment]
@jrudolph What does reusable mean for a source ? 
With Source.actorPublisher(props), I need materialization, for example with Sink.ignore, that will drop the items in the source.  I've tried to use the source after that but there is no more elements inside... 
Thanks :)

**Comment by jrudolph** [comment]
A `Publisher` can only be subscribed to once whereas a `Source` is thought to be materialized several times.

See this document for more information:

http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/stream-design.html

**Comment by loicdescotte** [comment]
Thanks for the link and sorry again for spamming in the issue :)

**Comment by rkuhn** [comment]
The Sink.actorRefWithAck has been implemented, the Source should be added as a matter of symmetry.

**Comment by gortiz** [comment]
It seems that at some point the topic changed to the materialization problem and the ACK problem was forgotten. Did I miss something? It would be great to have a Source.actorRefWithAck (and something similar with typed actors)

**Comment by nvollmar** [comment]
I quickly implemented a version with back-pressure based upon the new graph stage implementation (See #26633)

**Comment by nvollmar** [comment]
I quickly implemented a version with back-pressure based upon the new graph stage implementation  (see #26054)
