### ISSUE TITLE
Http cachedHostConnectionPoolTls hangs if TLS is not available remotely

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17628]
For example if you try to connect to port 80 instead of 443 it just silently hangs on request:

    Await.result(
      Source.single((HttpRequest(HttpMethods.GET, uri = Uri("/")), ()))
        .via(Http(system).cachedHostConnectionPoolTls[Unit]("www.google.com", 80))
        .runWith(Sink.head),
      3.seconds)

**Comment by rkuhn** [comment]
We need to ensure that we test all nine combinations (on either side there can be a TLS server, TLS client or no TLS). We have only three cases in the tests so far (client–server and server–client and plain–plain) and the others need to be made such that they properly error out (possibly with timeout).

**Comment by jrudolph** [comment]
The last output with this example from SslTls seems to be 

```
[DEBUG] [08/04/2015 12:31:42.050] [ServerTest-akka.test.stream-dispatcher-11] [akka://ServerTest/user/$a/flow-2-21-actorPublisherSource] SSLException during doUnwrap: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
```

afterwards, nothing happens any more. So, this seems to be caused by some instance of #18058. Once that is fixed I can have another look.

**Comment by jrudolph** [comment]
When #18058 is fixed we should add a test that runs this specific test with Http to prevent regressions for common user scenarios like this.

**Comment by jrudolph** [comment]
FTR here are the debugging changes I did: https://github.com/spray/akka/commit/c9ff03618430bfe9e8aef658237ce128be4a08f8

**Comment by drewhk** [comment]
Fixed
