### ISSUE TITLE
FAILED: PersistenceFSMActorSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17630]
[info] Persistent FSM Actor
[info] - must function as a regular FSM  (817 milliseconds)
[info] - must function as a regular FSM on state timeout *** FAILED *** (1 second, 164 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (1099411045 nanoseconds) during expectMsg while waiting for Transition(Actor[akka://PersistenceSpec/user/$b#2115551935],Shopping,Inactive)
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
[info]   at

https://jenkins.akka.io:8498/job/akka-multi-node/1078/consoleFull

**Comment by patriknw** [comment]
@leonidb in case you have some spare cycles, otherwise we'll look into it. Note that our CI environment is not very predictive when it come to timing sensitive tests (e.g. rather long 1 second GC pauses are not uncommon).

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2488/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2487/consoleFull

**Comment by leonidb** [comment]
@drewhk , @patriknw 
I'm looking at it

**Comment by leonidb** [comment]
@patriknw 
Looks like a timeout related issue.
There are also failures in tests not related to timeouts, but I think that they are affected by previous test failures.

Those tests do pass locally, but are probably too strict for CI environment.

I can change the acceptable timeout behavior from:
```scala
      within(0.9 seconds, 1.1 seconds) {
        expectMsg(Transition(recoveredFsmRef, Shopping, Inactive))
      }
```
to 
```scala
      within(0.5 seconds, 1.5 seconds) {
        expectTerminated(recoveredFsmRef)
      }
```

If that's not enough, we can use longer timeouts in the test actor - 2 seconds and then make the test check if the timeout is ```within(1 seconds, 3 seconds)``` - but it will make the tests run slightly longer.

Tell me what you think.

**Comment by patriknw** [comment]
yes, `within(0.5 seconds, 1.5 seconds)` looks good
1 second stop the world GC at any point is possible.
We have sometimes longer pauses than that, but accounting for that everywhere is not possible as it would slow down the tests considerably, but for normal expectMsg we use at least 3 seconds timeout

You should also mark such tests with `taggedAs TimingTest` so that they are not run at all in pr-validation and some other environments that are even more unpredictable.

**Comment by patriknw** [comment]
wait, things will not run too early, so if you know that it is at least `0.9` you should use that as lower bound, `0.9 - 1.9`

**Comment by leonidb** [comment]
OK, I'll change the timeouts.

**Comment by leonidb** [comment]
@patriknw 
Commited

**Comment by ktoso** [comment]
Thanks!
