### ISSUE TITLE
add ActorContext.getChild that returns Optional

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17635]
This works better with Java 8 lambdas (`orElseGet` instead of `getOrElse`).

**Comment by patriknw** [comment]
would be nice, but there is already a `def getChild(name: String): ActorRef` in `AbstractActorContext`. Rather messy to add yet another variant (`getChildOptional`).

`Optional.ofNullable(getContext().getChild(name))`  is good enough in my opinion.

**Comment by hepin1989** [comment]
Still found I need this sometime, maybe with a getChildOptional? Or change it in Akka 3?

**Comment by patriknw** [comment]
you could also use Akka Typed
