### ISSUE TITLE
FAILED: TypedActorSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17631]
https://jenkins.akka.io:8498/job/akka-nightly/2300/consoleFull

[WARN] [05/31/2015 21:38:14.759] [TypedActorSpec-akka.actor.default-dispatcher-8] [akka://TypedActorSpec/deadLetters] received dead letter from Actor[akka://TypedActorSpec/user/$n#-279691249]: Some(Pigdog)
[info] - must be able to use balancing dispatcher *** FAILED *** (5 seconds, 9 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [1183699 nanoseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.actor.TypedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$33$$anonfun$apply$mcV$sp$34$$anonfun$apply$mcV$sp$52.apply(TypedActorSpec.scala:424)
[info]   at akka.actor.TypedActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$33$$anonfun$apply$mcV$sp$34$$anonfun$apply$mcV$sp$52.apply(TypedActorSpec.scala:424)
[info]   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[info]

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
