### ISSUE TITLE
Unexpected behavior in akka.routing.TailChoppingPool

### ISSUE THREAD

**Issue by dodnert** [akka/akka#17649]
The behavior of class `TailChoppingPool` is either incorrect, or it is inconsistent with the Scaladoc description. What I see in the source code and what seems to be confirmed by my unit testing, is that the pool of routees is re-shuffled every time a message is sent to the pool. The documentation suggests that all routees will receive one message before any routee is sent a second message.

I think that the problem is due to the `send` method in class `TailChoppingRoutees` re-shuffling the routees list on every call to that method. But I'm not sure that I am understanding the intended behavior of this class correctly.

The reason I noticed this issue is that I am working on clarifying the documentation for this class (to resolve issue #17640) and I wanted add an explanation about what happens after all routees have been sent one message. This led me to write a small test program to see what the class is actually doing.

If this is just a documentation issue, we can close this issue and I will add the clarification as part of my fix for issue #17640.

**Comment by patriknw** [comment]
@dodnert For each message that is sent to the pool it should sends the message to a first, random picked, routee, then wait a specified `interval` and then send to a second, random picked, and so on till one full cycle.

For another message it will use another random sequence (hence the shuffling).

Do you see another behavior than this?

It would be great if you can improve the documentation.

**Comment by dodnert** [comment]
@patriknw Yes, the behavior that I see is different from what you are describing. I have a small test program that creates a `TailChoppingPool` of size 3. Then, I send 9 messages to pool. If the `TailChoppingPool` were implemented as you are suggesting, then each of the Actors in the pool should receive exactly 3 requests - because the first 3 request will be distributed in some random order to the 3 Actors, and then next 3 requests should be distributed again in a (possibly) different order, and so on. But what I observe is that on some test runs one Actor receives more than 3 messages while others receive less than 3. My guess is that this is a defect in the implementation of `TailChoppingPool`, but I still do not understand the intended behavior of the class well enough to say for certain if it is a defect, or simply my misunderstanding of what this type of pool is supposed to do. What do you think? I can post the source code for my test program if you think that would help.

**Comment by dodnert** [comment]
@patriknw - I think that I may be misunderstanding what is supposed to happen if multiple messages are sent to the pool within a shorter duration than the pool's `interval`. (This is what my test is doing.) In your earlier response, you wrote that "for another message, it will use another random sequence". Just to make sure that I understand, can you clarify what the documented behavior of the `TailChoppingPool` should be in this case?

**Comment by patriknw** [comment]
@dodnert If you send msg1 and msg2 to the router the picked routees are completely independent for the two messages. You can see it here: https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/routing/TailChopping.scala#L51

The list of routees is shuffled (randomly) for each message.

**Comment by dodnert** [comment]
@patriknw - Thanks for the clarification. We can close this issue as a misunderstanding. I will make an attempt to clarify the documentation (see issue #17640.)

**Comment by patriknw** [comment]
thanks

**Comment by dodnert** [comment]
@patriknw - Can you provide any insight into what type of problem this router was intended to solve? Or in what type of situation this router would be a good choice? It's not obvious to me.

**Comment by ktoso** [comment]
@dodnert It's for optimising tail-latencies – thus "tail chopping". The technique it employs is rather popular in distributed databases (including Cassandra, the original BigTable and others) where it is most often referred to as "backup requests".

The idea originated from Jeff Dean's (et al) work on BigTable, here's a slidedeck with some info: http://static.googleusercontent.com/media/research.google.com/en//people/jeff/Berkeley-Latency-Mar2012.pdf
I talk a bit about them in my [The Need for Async](https://vimeo.com/122085562) talk, from minute 29. (Tail latency is defined earlier in the talk, a few minutes in)
