### ISSUE TITLE
Akka Streams / HTTP API documentation link for Java broken

### ISSUE THREAD

**Issue by markusjura** [akka/akka#17642]
The Java link for [API documentation](http://doc.akka.io/japi/akka-stream-and-http-experimental/1.0-RC3/?_ga=1.24932153.200360858.1423997385) and [Reference documentation](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/java.html?_ga=1.24932153.200360858.1423997385) are broken on  http://akka.io/docs/#akka-streams-and-http.

**Error**

> Not Found  
>   The requested URL /japi/akka-stream-and-http-experimental/1.0-RC3/_ga=1.255086219.200360858.1423997385 was not found on this server.
>   Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

The Scala link is working. Seems like a Google Analytics problem. The link is working if I remove the `_qa` query parameter: http://doc.akka.io/japi/akka-stream-and-http-experimental/1.0-RC3/

**Comment by ktoso** [comment]
Thanks, seems like a real problem.
Surprisingly RC1 and RC2 work with the google analytics link.

I suspect it's javadoc doing something weird since `1.6.0_65` (RC3 was generated using it), since `1.6.0_45` generated RC2 works fine.

**Comment by ktoso** [comment]
ping

**Comment by ktoso** [comment]
Was about links in 1.0, closing
