### ISSUE TITLE
Error in documentation for akka.routing.TailChoppingPool

### ISSUE THREAD

**Issue by dodnert** [akka/akka#17640]
The documentation for class `TailChoppingPool` begins as follows.

> A router poll thats sends the message to a first, random picked, routee, then wait a specified interval and then send to a second, random picked, and so on till one full cycle..

The word *poll* should be replaced with *pool*. Also, the extra period at the end of the sentence should be deleted.

**Comment by ktoso** [comment]
Good catch, thanks for noticing! Would you like to submit a PR to fix the typos?

**Comment by dodnert** [comment]
I could do that, but it's not something I've done before. Are there any Akka-specific instructions that I will need to know about?

**Comment by ktoso** [comment]
Not much, just prepare the fix, issue an PR to `master` and please make sure that the commit message matches our guidelines so in this example it would be `=act #17640 fixed typo in TailChoppingPool scaladoc`.

There's a [contributing.md](https://github.com/akka/akka/blob/master/CONTRIBUTING.md) which explains things in more detail.

Thanks very much in advance!

**Comment by dodnert** [comment]
I am waiting for resolution of issue #17649 before finishing my proposed change to resolve this issue.

**Comment by patriknw** [comment]
@dodnert What is the status here? Did we find anything else that should to be improved apart from the poll vs pool typo?

**Comment by dodnert** [comment]
Sorry for the delay. I am planning to add a couple of additional sentences to the class description to better explain the expected behavior. I'll try to get this done either today or Monday.

**Comment by patriknw** [comment]
Thanks, that would be great.

**Comment by dodnert** [comment]
@patriknw - Here is the description that I am planning to use for `class TailChoppingPool`. Can you please review this for accuracy and clarity?
 
> A router pool that sends messages to the routees using the following selection algorithm. The first message is forwarded to a randomly selected routee. Then, for each subsequent message that is sent with at least `interval` time since the previous, that message is forwarded to another randomly selected routee. This process repeats until all routees in the pool have been forwarded a message. Once all routees have been selected, the routees are reshuffled and the selection algorithm restarts. When a message is sent to the pool and `interval` time has not passed since the previous send, the routee pool is immediately reshuffled and the selection algorithm restarts as if that message were the first.

**Comment by dodnert** [comment]
@patriknw - Please disregard my previous message. As you can see, I still didn't quite understand what this class was doing. But I've now run some tests and read the code and I think I understand it better now. Here is my latest draft:

> A router pool with retry logic. As each message is sent to the pool, the routees are randomly reordered. The message is sent to the first routee. If no response is received before the `within` duration has passed, and at least `interval` has passed, the same message is sent to the next routee. This process continues until either a response is received, the routees in the pool are exhausted, or until the `within` duration has passed since the first attempt.

If I am understanding the code correctly, it seems that the `within` value is used for two different purposes: it is both the timeout value on the `ask` when the message is sent to a routee and it is also used as the overall time given for any of the routees to deliver a response. This feels wrong. If the first routee returns no response within the `within` duration, none of the other routees will be sent that message. Can you please comment?

**Comment by dodnert** [comment]
If you have feedback on my documentation changes, please comment on pull request https://github.com/akka/akka/pull/18457.
