### ISSUE TITLE
docs: HTTP client examples should include output of response body

### ISSUE THREAD

**Issue by briantopping** [akka/akka#17651]
An HTTP client generally requires two flows, one for the request/response cycle and another to fetch the body. But there are differences depending on whether one is using the high level or low level interfaces,  and the means of recovering the response body is slightly different in each of them (i.e. removing the response discriminator). It would add clarity if all the examples ended at a common state, such as the Source for the response body.

*In looking at the example source, it might be useful if clicking the source jumped the browser to the page on Github that the example was generated from. So as an alternative, such additional code might be in the ScalaTest, but outside the `//#` tags so as to keep the published documentation lightweight.* <- this is #17650

**Comment by jrudolph** [comment]
@briantopping which differences do you mean exactly? Between the future and the flow based variants?

Your second suggestion was just filed as #17650.

**Comment by briantopping** [comment]
@jrudolph Yes, that's the major difference I know so far. I'm not confident I know it to be a complete set though. By having the examples resolve to the same outcome (same type as well as data), the nuances between the APIs should become more easily evident. 

I guess what I am trying to describe might be captured as an example code test harness. The harness would provide mock endpoints (both client and server) for example requests or data as well as matchers that could easily match against the requests/data that are provided by the endpoints.

There's not an overwhelming number of core concepts in Streams and HTTP, but the combinatorics are a bit overwhelming to get started. If a user spent time learning these matchers and the mock endpoints they operated against, the example code becomes "novel plumbing" that connects the two in illustrative ways. 

As a poor example, nobody would wash their car with only a rigid pipe that was anchored to a wall, and unless they had seen a rubber hose, they might just use a bucket and carry the water to the car. In some situations, the latter is not degenerate – we just simply can't get a hose to the car. If the two constants are the water supply and the car to be washed (i.e. the example test framework providing the Source and the validating Sink), how can the plumbing between those two endpoints most easily be demonstrated by core developers and understood by users that want to see things in action?

**Comment by briantopping** [comment]
Maybe a different illustration is at https://github.com/akka/akka/blob/48b69a01811ebd91bdb797ffae9afee390a41905/akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala#L236-254. This is a very comprehensive test for the build, but would be very difficult for a user in search of a practical example. 

Were example tests to be maintained, I presume they would trade the rigor of a comprehensive test for the clarity of patterns that a user will be more likely to use in the field.

**Comment by ktoso** [comment]
We'll want to improve docs in this area in general, closing this ticket for now though. 
The feedback is great and I see your point - hope address it in docs rewrite
