### ISSUE TITLE
Stream Scala Documentation issues for 1.2 Quick Start Guide

### ISSUE THREAD

**Issue by agolubev** [akka/akka#17655]
1. Task description (“In our case let’s say we want to find all twitter handlers”) is too far from the beginning of chapter.
2. "Both Sources and Flows provide stream operations that can be used to transform the flowing data, a Sink however does not since its the “end of stream” - in following chapter there is Sink.fold() - per my understanding it’s transforming data.
3. For 1.2.1 need to make snippet of code that we can copy and paste into REPL and run. This will simplify understanding and will provide general vision.
4. It’s good to have images for:
  1. flattening sequence (1.2.2)
  2. broadcasting stream (1.2.3)
  3. fun-in and fun-out
5. In code snippet for 1.2.3 it’s not clear what FlowGraph.closed() is and there is no comment on this
6. 1.2.5 introducing term FoldSink - it’s confusing. There is no such class or entity in API, value name is sumSink - consequently no exact matches
7. “Remember those mysterious type parameters” 1.2.6 - no coma between Source and Flow. Also need to add generics them as well. 
8. In Quick start chapter there is no example for Flow. We can see Sink, Source and Flow Graph
9. Would be good to have Glossary with terms and descriptions
10. In 1.2.5 there is mention of Keep.right - which is logical but confusing part that it’s not clear what left is doing and why it’s important to have both.

**Comment by drewhk** [comment]
Thanks, great feedback! I will try to pick this up before 1.0, but if you want to add some improvements on your own feel free to submit a PR (does not need to address all problems at once).
