### ISSUE TITLE
OperationAttributes name is confusing

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17661]
*Back in my days...* (:wink:) we used to call stages "ops", from that time we have `OperationAttributes`.
We do not really use the word operation anywhere in akka streams - it's all "stages/junctions/flows" now, 
so OperationAttributes sounds a bit off.

We should rename before 1.0.

// cc @drewhk

**Comment by drewhk** [comment]
I think it was renamed at one point from Attributes. I think that was the cleanest so far.
