### ISSUE TITLE
FAILED: ClusterShardingSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17679]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/18/consoleText

[JVM-4] [INFO] [06/07/2015 08:28:55.033] [ClusterShardingSpec-akka.actor.default-dispatcher-4] [akka.tcp://ClusterShardingSpec@a5.moxie:58244/user/PersistentCounterCoordinator] Timeout in BecomingOldest. Previous oldest unknown, removed and no TakeOver request.
[JVM-4] [INFO] [06/07/2015 08:28:55.033] [ClusterShardingSpec-akka.actor.default-dispatcher-4] [akka.tcp://ClusterShardingSpec@a5.moxie:58244/user/PersistentCounterCoordinator] Singleton manager [akka.tcp://ClusterShardingSpec@a5.moxie:58244] starting singleton actor
[JVM-4] [INFO] [06/07/2015 08:28:55.035] [ClusterShardingSpec-akka.actor.default-dispatcher-4] [akka.tcp://ClusterShardingSpec@a5.moxie:58244/user/PersistentCounterCoordinator] ClusterSingletonManager state change [BecomingOldest -> Oldest]
[JVM-1] [ERROR] [06/07/2015 08:29:37.742] [ClusterShardingSpec-akka.actor.default-dispatcher-15] [akka://ClusterShardingSpec/user/controller/barriers] timeout while waiting for barrier 'after-8' (akka.remote.testconductor.BarrierCoordinator$BarrierTimeout)
[JVM-1] - must recover coordinator state after coordinator crash *** FAILED ***
[JVM-1]   java.lang.RuntimeException: barrier failed: after-8
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:211)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:186)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:652)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:147)
[JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:788)
[JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:147)
[JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:646)
[JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:640)
[JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:475)

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3115/consoleFull

**Comment by drewhk** [comment]
This is very old, do you think @patriknw that this is still relevant?

**Comment by patriknw** [comment]
yeah, that was very old, closing
