### ISSUE TITLE
HttpMessageParser aggregates input in `continue`

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17683]
This leads to a temporary memory leak and increasing parsing times for long messages where the `input` ByteString starts to consist of more and more elements leading to bad performance because of linear scanning in `ByteString.slice`.

/cc @sirthias

**Comment by drewhk** [comment]
Yes, you need to compact at some point. You can set a threshold though, then you can amortize the compact.

**Comment by jrudolph** [comment]
This was only somewhat related to ByteString/compaction, as we didn't use "ByteString.drop" but instead kept an increasing index into a growing ByteString that we always appended the new data to.

The right solution is to really rely on ByteString to provide an efficient `drop`-implementation.

**Comment by jrudolph** [comment]
Fixed in #17684.
