### ISSUE TITLE
[akka-http] Allow directive for matching on HttpEntity type or extracting content-length

### ISSUE THREAD

**Issue by mhamrah** [akka/akka#17680]
I'd like to create a directive that matches when the request.entity is of type HttpEntity.Default. Specifically, I'd like to know when the Content-Length header is set and extract the Content-Length header value.

Content-length does not appear in request.headers (which seems like a bug), but is only set as a property of the http entity property, depending on the type of entity, and not all entities have a Content-Length property (maybe Content-Length could be an Option[Long] on the HttpEntity trait?

Here are some other ideas:

* Filtering on Content-Length being set in a header in a route
* Calling extractRequest, but only if the request.entity is of HttpEntity.Default
* Adding a directive matching on HttpEntity.Default.
* Making contentLength Option[Long]

Originally from https://groups.google.com/forum/#!searchin/akka-user/hamrah/akka-user/8LnoBrRPDz4/sOKFDJv9o40J

**Comment by briantopping** [comment]
I responded a little more at length on the list, but what if it were possible to provide a directive like http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/http/routing-dsl/directives/basic-directives/mapRouteResultPF.html#maprouteresultpf that accepted a partial function for matching pretty much anything in the request closure relatively easily? (I don't think I have the skills to write this, just tossing out ideas..)

I also just ran across http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/http/routing-dsl/directives/header-directives/headerValuePF.html#headervaluepf.

**Comment by jrudolph** [comment]
I see where you are coming from. We need to be careful not to encourage brittle code, though. Requiring a default entity means, that you cannot reliably accept clients from behind a proxy (which is allowed to change the transfer-encoding to chunked) or decompressed content of which only the compressed size would be known and for which the entity type is changed by the decoding directives. Also, both Strict and Default entities have a content-length defined and which of those you get is undefined.

Could you explain what's the motivating use-case for such a directive and what you would do with the other requests? You could, of course, make it part your API specification to preclude requests without a content-length set. Do you know of REST APIs which have such a kind of spec? What would be the goal doing this?

**Comment by mhamrah** [comment]
The specific use-case is for a proxy to S3; under certain circumstances I need to tell S3 the content-length before I begin an upload. In the proxy I want to reject any request without a content-length, and I want to pull out the content-length to pass downstream.

I don't necessarily care about the HttpEntity.Default; it's only a means to the content-length. I can't pull content-length out of the request.headers property from extractRequest or via the context because it's not there; it's only set depending on the HttpEntity as a property of the respective entity.

It would be nice to have it as an entry in the request.headers object (after all, that's how the client sends it) or make HttpEntity.contentLength an Option, so you know if it's set or not regardless of the entity.

**Comment by jrudolph** [comment]
Yes, we should add a `contentLength: Option[Long]` member.

As for providing more support I think there's a conflict between a) not encouraging breaking HTTP (by only accepting a subset of possible HTTP functionality which the client may have no control over (e.g. transparent proxying in company networks or mobile broadband which may change the transfer encoding) and b) going out of the way letting the users of the HTTP library do what they want to do.

With this in mind it may make sense to add such a directive if only to provide an anchor to put up a documentation sign that you may break access for some clients by filtering HTTP in a way like this.

**Comment by mhamrah** [comment]
I understand this could be one of those "be careful what you wish for". For
my use case, contentLength: Option[Long] works perfectly and doesn't
involve the complexities or consequences of other alternatives.
