### ISSUE TITLE
Superfluous type parameter

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#17687]
The type parameter for `sprayJsValueMarshaller` is superfluous:

- https://github.com/akka/akka/blob/release-2.3-dev/akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala#L34
- https://github.com/akka/akka/blob/release-2.3-dev/akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala#L35

**Comment by jrudolph** [comment]
Yes, thanks. It seems the `writer` is superfluous as well.

/cc @sirthias

**Comment by jrudolph** [comment]
Fixed in #17689.
