### ISSUE TITLE
Provide automatic aggregation of chunks in parser

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17694]
Just an idea I wanted to put out of my head.

By throwing away the additional information of chunk boundaries (if configured) we can aggregate all data the parser currently has available instead of having to emit entity parts in chunk sizes as dictated by the peer.

This was a real issue in my FileUpload example where the SynchronousFileSource produces chunks of only 8kb while the parser on the other side will get the data at chunk sizes determined by the direct buffers of the TCP layer (128k / 8k = 16 times streaming overhead).

/cc @sirthias

**Comment by jrudolph** [comment]
Correction: the conversion would be to `CloseDelimited` or `IndefiniteLength` as the length is not known.

This could also prevent two other unfortunate scenarios:
  - The peer sends only chunks of size 1 leading to additional resource usage due the big number of streaming elements sent around
  - The peer sends big chunks that currently need to be aggregated in the parser. With the automatic conversion incoming data could be dispatched as soon as possible.

One problem with this suggestion is that `CloseDelimited` entities currently aren't allowed for requests.

**Comment by jrudolph** [comment]
To get around the entity type issue the simplest solution would be **not to change** the entity type at all but just aggregate small chunks from the network into bigger chunks coming out of the API. In all cases where the transfer-encoding is just used as that: an implementation detail of transferring data over the connection this aggregation should be fine. If you rely on chunking to carry semantics (e.g. the chosen chunk boundaries or by adding chunk extensions), then you would need to turn aggregation off, but this seems like the less frequent use-case (also cf. the discussion around changing the entity type wrt. compression).

**Comment by rkuhn** [comment]
What does the spec say? Is it not allowed for proxies to re-chunk anyway? If so then I’m all for this proposal.

**Comment by sirthias** [comment]
So far I haven't found anything completely authoritative, but this is what a [section of RFC6202](http://tools.ietf.org/html/rfc6202#section-3.2) says:

> The separation of the response stream into application messages needs
> to be performed at the application level and not at the HTTP
> level.  In particular, it is not possible to use the HTTP chunks
> as application message delimiters, since intermediate proxies
> might "re-chunk" the message stream (for example, by combining
> different chunks into a longer one).

**Comment by jrudolph** [comment]
It would be useful in any case and as @sirthias basically confirms, the default should probably be on aggregating chunks. The question would then be if also the also direction would make sense where half-received chunks are dispatched if the rest is still missing.

**Comment by rkuhn** [comment]
The latter is actually more interesting to me since large chunks are a DoS vector otherwise.

**Comment by sirthias** [comment]
The only problem that I see with aggregation is that we'll need some kind of heuristic to decide whether we should wait for another chunk to be aggregated or dispatch what we have right now. Latency vs. throughput once again.

**Comment by rkuhn** [comment]
IIUC the proposal was to always emit as many bytes as the current ByteString permits, re-chunking randomly, no heuristics needed.

**Comment by sirthias** [comment]
Ah, yes, I see. That makes sense. Sorry for the noise.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
