### ISSUE TITLE
Provide a "Source.queue" as an alternative to `Source.actorRef` that can reject elements

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17693]
`Source.actorRef` basically implements a queue (by setting buffer sizes) that may overflow at any time. In case of overflow, only the consumer of the elements can be notified but not the sender.

If you need a queue that can reject elements if it overflows you need to implement it yourself.

See http://zuchos.com/blog/2015/06/10/more-reactive-publisher-aka-publisher-vol-2/ and https://github.com/Zuchos/akka-http-with-streams/blob/blogpost2/src/main/scala/pl/zuchos/example/actors/DataPublisher.scala

A possible signature could look like this:

```scala
def queue[T](bufferSize: Int): Source[T, T => Future[Boolean]] 
```

It would materialize to a function that can be used to try adding an element to the queue and returns a future that indicates if adding the element was successful.

**Comment by jrudolph** [comment]
Also, it could make sense to abstract over the queue, so that you could use a PriorityQueue etc.

**Comment by drewhk** [comment]
Make sense to me. We can provide a Sink version of this that has a similar materialized type, but returns a Future when the next element is available for consumption. These two simple abstractions would allow integration with existing send-ack actor patterns without much hassle.

**Comment by fommil** [comment]
sweet! I'll definitely have to look at this in the next RC

**Comment by ymeymann** [comment]
This would come handy, as we are trying to use Akka Http to receive data and push it to Kafka with https://github.com/softwaremill/reactive-kafka

**Comment by cppexpert** [comment]
It doesn't work for me in 2.4.4. Could you please take a look ?
http://stackoverflow.com/questions/37113877/how-can-i-use-and-return-source-queue-to-caller-without-materializing-it

**Comment by drewhk** [comment]
What do you mean does not work? Do you have a reproducer and a detailed bug description?

**Comment by cppexpert** [comment]
I mean that I don't receive values from the stream in `.runFold/.runForEach`. In edit of my SO question I added self-contained code snippet in which I reproduced the issue. It doesn't even work with `Sink` for me. Maybe I'm using it incorrectly but in the past I used actorPublisher sink without any problems. So apparently it's something about `Source.queue` I don't understand. Code is this

```
val source = Source.queue[String](50, backpressure)
val sink = Sink.seq[String] // Sink.queue[String]()
val queue = source.toMat(sink)(Keep.left).run()
val queue1: SourceQueueWithComplete[String] = queue
for (i <- 1 until 10) {
  println(s"Pushing $i to queue")
  queue.offer(i.toString)
}
println("Queue is completed")
queue.complete()

val result = source.runFold(List[String]())((result, article) => article :: result)
result.onComplete { case tried: Try[List[String]] =>
  println(tried)
}
```

**Comment by drewhk** [comment]
You don't even use the result of your enqueueals. You materialize the source again when you use fold, so that has nothing to do with your queue that you enqueued elements into.

**Comment by cppexpert** [comment]
Cool. Then we came to my original question on SO. How can I get instance of `SourceQueue` in my function so I can push items via calling `SourceQueue.offer` thus allowing caller of my function to materialize returned `Source` ?

**Comment by drewhk** [comment]
> But ideally I'd like to return Source from my library and not to materialize anything on my side. I want client of my code to materialize Source.

This, at least without further information makes not too much sense actually. It might be that you return the Source and no one will materialize it, or it could be materialized multiple times, but your above snippet expects a single queue to enqueue things in. Are you trying to achieve some kind of dynamic broadcast?

**Comment by cppexpert** [comment]
Client code is written by me too :) So I do materialize on returned `Source`. Here is my function

```
def findArticlesByTitle(text: String): Source[String, SourceQueue[String]] = {

  val source = Source.queue[String](100, backpressure)

  source.mapMaterializedValue { case queue =>

    val url = s"http://.....&term=$text"
    httpclient.get(url).map(httpResponseToSprayJson[SearchResponse]).map { v =>
      v.idlist.foreach { id =>
        queue.offer(id)
      }

      queue.complete()
    }
  }

  source
}
```

client code materializes it like this

```
// There is implicit ActorMaterializer somewhere
val stream = plugin.findArticlesByTitle(title)
val results = stream.runFold(List[String]())((result, article) => article :: result)
```

Code  inside `mapMaterializedValue` is never called. Maybe I shouldn't use `mapMaterializedValue` at all but then how I can get instance of `SourceQueue` in my function so I can push items via `.offer()` ?

**Comment by drewhk** [comment]
First of all, source is immutable, hence if you call `source.mapMaterializedValue`, then you need to store it in a new variable, it does not mutate the original source. 

Second, I don't really get why you even need a queue for this, can't you just use Akka Http?

Even if you don't want to use Akka Http, you can do this much simpler, assuming that `httpclient.get` returns a `Future`:

```
Source.fromFuture(
  httpclieng.get(url).map(httpResponseToSprayJson[SearchResponse])
).mapConcat(_.idlist)
```

... and here you go, you have a Source of IDs.

**Comment by drewhk** [comment]
@cppexpert did that solve your issue? If you tell me the returned type of `httpClient.get()` then I can likely give you a one-liner that avoids the queue altogether and also more idiomatic regarding streams usage.

**Comment by cppexpert** [comment]
Yes, it was quite lame :(
1) I wasn't returning new instance of source from `mapMaterializedValue`;
2) I had exception within my Future that was silently eaten and gave appearance of hanging.

Earlier you asked me why I even need to bother with `Source`. I didn't want blast community with tons of code but my code is a bit trickier than just getting IDs. I receive paginated stream of articles for big date range (hundred of thousands articles that are being  downloaded over few hours). I currently use actorPublisher (https://gist.github.com/cppexpert/4e86862b46bb3bc4fbeb3202e6cdc884) but thought that I can simplify my code if I rewrite it using `Source.queue`.

Thank you, guys!
