### ISSUE TITLE
No consistency in actorSelection for ActorPath & String

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#17690]
Does work
```scala
val path = RootActorPath(address, "/user/sharding/*Coordinator/singleton/*")
system.actorSelection(   path.toString   ) ! Identify("singleton")
```

Does NOT work
```scala
val path = RootActorPath(address, "/user/sharding/*Coordinator/singleton/*")
system.actorSelection(   path   ) ! Identify("singleton")
```

**Comment by patriknw** [comment]
@t3hnar Thanks for reporting. That is unexpected, and I'm not sure if there is a reason for this inconsistency. `elements` in `RootActorPath` is implemented as `ActorPath.emptyActorPath`.

I think the normal usage of `RootActorPath` is:

    RootActorPath(address) / "user" / "sharding" / "*Coordinator" / "singleton" / "*"

**Comment by t3hnar** [comment]
Yes I know about that `sugar`, however in my case those are taken as string from `.conf` file

**Comment by patriknw** [comment]
Then you might want to use `ActorPath.fromString`. I agree that the inconsistency is bad.

**Comment by t3hnar** [comment]
Thx! I'll give it a try to `ActorPath.fromString`

**Comment by ktoso** [comment]
@t3hnar I had a deeper look into this, and came to the conclusion that the fact constructing an RootActorPath like so: `RootActorPath(address, "/user/booom")` is illegal, since this element is a `name` (same as path elements), and may not contain slashes. The toStringed version worked by accident - since the toString is "address + name", which in the above example matched the path, however we should not allow these.

Instead please use `ActorPath.fromString` as @patriknw mentioned :-)

**Comment by t3hnar** [comment]
@patriknw @ktoso 
How should I get `actorSelection` when `address` in cluster is something known at runtime, local `path` is something known from `.conf` ?

Is this a correct approach ?
```scala
val path = ActorPath.fromString(conf)
system.actorSelection(path) 
```

**Comment by ktoso** [comment]
Yeah, exactly like that :)

**Comment by ktoso** [comment]
```scala
      val addr = Address("akka.tcp", "mysys", "localhost", 1234)
      val p = ActorPath.fromString("akka://mysys/user/boom/*")
      val p2 = p.toStringWithAddress(addr)
      info(s"p  = $p")  // p  = akka://mysys/user/boom/*
      info(s"p2 = $p2") // p2 = akka.tcp://mysys@localhost:1234/user/boom/*
```

**Comment by t3hnar** [comment]
So I have to made up an `system name` to have it worked...not a very nice solution.

**Comment by patriknw** [comment]
no, you have to concatenate the address and the "logical" path.

    ActorPath.fromString(address + conf)

It would have been convenient with

    RootActorPath(address).addPathWithoutAddress(p)

**Comment by t3hnar** [comment]
`ActorPath.fromString(address + conf)` - ok
Will `addPathWithoutAddress` be in `2.4` ? :)

**Comment by patriknw** [comment]
I don't think we can add all methods that are nice to have when there is a reasonable other way of doing it. You could also split the conf on `/`, and use foldLeft to append them with the `/` operator. Just saying, there are many ways.
