### ISSUE TITLE
Provide an API for Cluster Sharding state retrieval

### ISSUE THREAD

**Issue by 2m** [akka/akka#17695]
Would be great to have a user API where one could subscribe for Cluster Sharding state changes.

**Comment by patriknw** [comment]
Do you have any other use case in mind than logging?

**Comment by 2m** [comment]
This could enable a monitoring tool to provide an overview of what shard regions are in what nodes. What sharded entries are active and what passivated.

**Comment by patriknw** [comment]
ok, thanks for clarifying, makes sense

**Comment by 2m** [comment]
Oh. I thought you started working on it right away. :)

**Comment by patriknw** [comment]
no, wrong label
