### ISSUE TITLE
File upload with akka http

### ISSUE THREAD

**Issue by nykolaslima** [akka/akka#17706]
Hello guys,

This is much a doubt than a issue, can you guys provide some example on uploading a file with akka http?

Thank you and I'm sorry for opening this.

**Comment by briantopping** [comment]
There are two streams you need to consider here. One is the stream of `HttpRequest` objects that form the connection cycle. Within the connection cycle, there is another stream for the supply of data for the request body.

IIRC, there are four `HttpEntity` subtypes, you most likely want https://github.com/akka/akka/blob/57eeed74c26f3c1030c9c23b4063efc84d991f48/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala#L192-198. As you construct the request, you are going to assign a `Source` to `dataEntity` that generates streaming content from the file you are uploading. http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/stream-io.html#Streaming_File_IO is going to give you the template for that `Source`.

I'm sorry I don't have some exact code handy to give you, but once you do this the first time, it will become effortless. Plan to spend a couple days on it on your first try and if you can get it in a couple of hours, great! Once there's some more experiences like this, the docs can grow. HTTP client doc is definitely very sparse at the moment.

One last hint: I'd read the docs at http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala.html from start to end. There's a lot of information in the http section that ASSUMES you are completely familiar with the basics of streams in the first section. If you just skip to HTTP, you'll likely be frustrated. 

Hope that helps!

**Comment by jrudolph** [comment]
Thanks @briantopping for helping. The documentation is indeed still lacking in this regard so we already created #17665 to better document client-side file uploads, so I'm closing this one here.

**Comment by ktoso** [comment]
Agree with @jrudolph here, docs are on their way, however here's a mini file-upload example you @nykolaslima may find useful: https://github.com/ktoso/scaladays2015/blob/master/src/main/scala/com/typesafe/TheDemo.scala#L41

**Comment by briantopping** [comment]
Yep, no criticism there, just a tiny contribution while bigger priorities are accommodated. This also encapsulates where I got hung up in learning. Once the distinction between the command stream and the payload stream was clear, things became a lot clearer.

It seems like a graphical map of the documentation might be useful, a FSM diagram for documentation if you will. The exit states would be the kind of application or use cases that the user wants to accomplish and the inputs would be the dependency tree of documentation that the user should learn and in what order.
