### ISSUE TITLE
ActorSubscriber ignores Supervision.Decider

### ISSUE THREAD

**Issue by DomBlack** [akka/akka#17700]
I have a stream which uses an `ActorSubscriber` as a `Sink`, the sink can throw an exception, in it's receive, when the connection to the remote resource breaks, and can be just fixed by restarting, however the `Supervision.Decider` is never getting called.

This was with Akka Streams 1.0-RC3 and Akka 2.3.11

### Example
In the below example *if* the Supervision.Decider was being used, I would expect to see "Restart!" or at least "Stop!" in the console, I see neither.

```scala
class InputSender extends ActorSubscriber {
  override protected def requestStrategy: RequestStrategy = ZeroRequestStrategy
  override def receive: Receive = {
    case OnNext(str: String) if str == "throw" ⇒ 
      self ! "throw" // simulated talking to an async service

    case "throw" =>
      println("Will throw")
      throw new UpstreamGoneException("Gone!")

    case OnNext(str: String) ⇒
      println(s"sinking $str")
      request(1)
  }

  override def preStart(): Unit = {
    super.preStart()
    request(1)
  }
}

val decider: Supervision.Decider = {
  case _: UpstreamGoneException ⇒ println("Restart!"); Supervision.Restart
  case _ ⇒ println("Stop!"); Supervision.Stop
}

implicit val mat = ActorFlowMaterializer(
  ActorFlowMaterializerSettings(system).withSupervisionStrategy(decider)
)

val sink = Sink.actorSubscriber[String](Props(new InputSender()))
  .withAttributes(ActorOperationAttributes.supervisionStrategy(decider))

val src = TestSource.probe[String]
  .to(sink)
  .withAttributes(ActorOperationAttributes.supervisionStrategy(decider))
  .run()

src.sendNext("hello") // prints: "sinking hello"
src.sendNext("throw") // nothing printed
src.expectNoMsg(1 second span) // errors due to cancellation
```

**Comment by rkuhn** [comment]
We should improve the documentation around stream supervision: it does not in fact use Actor supervision to perform its duties, stream supervision is implemented in the Interpreter that executes the Stages. What we could do, though, is to allow the supervisorStrategy of the FlowMaterializer’s guardian Actor to be configured. Not sure how useful that would be in practice, though.

**Comment by patriknw** [comment]
cc @drewhk I have no clue why he labeled this 0-new

**Comment by drewhk** [comment]
I think because it has been not decided what we should do here. We will do a run on tickets next Monday, so I triage it for now and assign it to a milestone. Then on Monday we can decide its fate.
