### ISSUE TITLE
respondWithHeaders not working

### ISSUE THREAD

**Issue by nykolaslima** [akka/akka#17708]
I'm using `respondWithHeaders` method inside my route definition but the defined headers are not being returned.

Am I using it in a wrong way or is it a bug?

```
val routes = {
    (options) {
      respondWithHeaders(`Access-Control-Allow-Origin`.*, `Access-Control-Allow-Methods`(GET, POST, DELETE, PUT, OPTIONS),
        `Access-Control-Allow-Headers`("Origin, X-Requested-With, Content-Type, Accept, Authorization"))
      complete("")
    }
  }
```

**Comment by jrudolph** [comment]
You need to nest directives, so that your inner block looks like this:

```scala
respondWithHeaders(`Access-Control-Allow-Origin`.*, `Access-Control-Allow-Methods`(GET, POST, DELETE, PUT, OPTIONS),
        `Access-Control-Allow-Headers`("Origin, X-Requested-With, Content-Type, Accept, Authorization")) {
  complete("")
}
```

**Comment by nykolaslima** [comment]
Is there a way to set some headers to all requests?

**Comment by jrudolph** [comment]
You can put the directive wherever you want in your route structure, so if you put it at the root, all your requests will contain the header(s).

**Comment by nykolaslima** [comment]
Thank you @jrudolph :+1:
