### ISSUE TITLE
Move EnhancedInetSocketAddress support to 2.3 from akka-http

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17701]
Adds getHostString support for Java 6, see: https://github.com/akka/akka/pull/17658/files

**Comment by drewhk** [comment]
I think this should entail actually using this, for example in remoting. I move it to 2.3.13 and fix it next cleanup day

**Comment by ktoso** [comment]
i.e. not working on it right now? (lables seem to state the opposite)

**Comment by drewhk** [comment]
I scheduled myself for the next round, preemptively. I can remove the labels if you prefer.

**Comment by ktoso** [comment]
Ok ok, no problem :)

**Comment by viktorklang** [comment]
Is it reasonable that this ticket is "in progress"?

**Comment by drewhk** [comment]
this is no longer necessary on master and would break compat on 2.0.x.
