### ISSUE TITLE
Akka distribution - incorrect line endings in scripts

### ISSUE THREAD

**Issue by jasongoodwin** [akka/akka#17713]
Hey, 
I noticed that bin/akka-cluster in the akka distribution seems to have the incorrect newline encoding for unix/linux systems.

Jasons-MacBook-Air:bin jason$ ./akka-cluster
-bash: ./akka-cluster: /bin/bash^M: bad interpreter: No such file or directory

I corrected this with vi:

vi ./akka-cluster
:set fileformat=unix
:wq!

**Comment by drewhk** [comment]
Hi, which version? I think it might be my last release, maybe git autocrlf messed it up for me again...

**Comment by patriknw** [comment]
The problem is in 2.3.11. Ok in 2.3.10.

**Comment by drewhk** [comment]
yep, it was me, and git autocrlf was not turned off.

**Comment by patriknw** [comment]
@drewhk is there something we should do here, apart from changing your settings?

**Comment by drewhk** [comment]
No, I don't think so.

**Comment by patriknw** [comment]
ok, then I'm closing it
