### ISSUE TITLE
htp= Alias `RouteDirectives.reject` to `Route.Empty`

### ISSUE THREAD

**Issue by briantopping** [akka/akka#17715]
Given an `routes: Iterator[Route]`, I'd like to be able to aggregate those routes with `~`. This is pretty simple with `val uberRoute = routes.foldLeft(RouteDirectives.reject) { _ ~ _ }`. 

Could comprehension be improved if there was an alias for `RouteDirectives.reject` as `Route.Empty`?

**Comment by jrudolph** [comment]
If you know that `routes` is non empty you could also use `routes.reduce(_ ~ _)` which would also prevent an extra indirection in the normal case. Maybe, we could just put the comprehension somewhere? If you would add a PR that adds that to `RouteConcatenation` or `Route`, we'd be happy to add it.

/cc @sirthias

**Comment by sirthias** [comment]
Another case where I think a `NotEmptyList` or `NotEmptySeq` in the standard lib would really help.
Anyway... :)

**Comment by briantopping** [comment]
@jrudolph Yes, I was initially using `routes.tail.foldLeft(routes.head) { _ ~ _ }` when I couldn't find a `.Empty` for routes. I guess my idea is the `.Empty` is a pretty common idiom with collections, and my brain naturally searched for that when building this out. Seemed like something others would might do as well.

**Comment by rkuhn** [comment]
So, is there a Monoid for Route, then? :-)

**Comment by sirthias** [comment]
One related thing:
We already define `Directive.Empty` as "A Directive that always passes the request on to its inner route (i.e. does nothing)".
If `Route.Empty` is then "always reject", maybe users might be confused as to what "empty" means in the context of routes and/or directives?

**Comment by briantopping** [comment]
@sirthias: I see your point. The inverse is actually why I suggested this, that `RouteDirectives.reject` is not intuitive as something that one would start a fold with. So I'm not sure what the answer is here. When one has a firm grasp of rejections, this makes sense. Maybe people who aren't fully aware of rejections shouldn't be folding routes.. :)

**Comment by rkuhn** [comment]
Maybe it should be called `Route.undefined` then, in the spirit of not containing the definition of any processing logic.

**Comment by rkuhn** [comment]
Or we call it `RouteMonoid.Zero` :-)

**Comment by briantopping** [comment]
I can only imagine that conversation, haha

**Comment by sirthias** [comment]
How about we simply call it what it is: `Route.reject` ? :)
