### ISSUE TITLE
Support websocket compression

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17725]

**Comment by fommil** [comment]
btw, be careful that you don't end up accidentally using JDK 7 API features when implementing this. Wandoulabs is Java 7+ because of this.

**Comment by jrudolph** [comment]
@fommil actually, the full spec cannot be implemented with the JDK versions of zlib at all and AFAIR this doesn't change with the newer JDKs (you need to be able to set the compression window size). Netty chose to use another zlib wrapper because of that.

**Comment by ktoso** [comment]
We're currently not aiming to work on the extension mechanisms for websockets.
We'll revisit this topic once more demand for it shows up

**Comment by malibuworkcrew** [comment]
Doesn't look like this has been talked about in a while but wanted to throw in my hat for wanting support for this feature. We're incidentally having to pull spray back in (gross, I know) and revert our websocket code.

**Comment by malibuworkcrew** [comment]
In case anyone ends up here, we were able to implement our own compression on websocket response data that seems to be working alright. The code is open sourced here: https://github.com/oracle/wookiee-akka-http/blob/master/src/main/scala/com/webtrends/harness/component/akkahttp/websocket/AkkaHttpWebsocket.scala#L74

**Comment by fommil** [comment]
Thanks @malibuworkcrew what license is that using? I can't see one anywhere, not even in the pom.

**Comment by malibuworkcrew** [comment]
Ah it's Apache 2, added to the README
https://github.com/oracle/wookiee-akka-http
Note that currently my implementation doesn't return the Content-Encoding header correctly (still trying to figure out how to attach this to the initial handshake response) but should be compressing just fine. Should have that fixed in next couple days.

**Comment by ktoso** [comment]
Interesting, thanks for sharing @malibuworkcrew! I'll re-open the ticket so we can remember this

**Comment by jrudolph** [comment]
In any case, it's the wrong repo, can you move that ticket over to akka-http?

Nice that this solution works for you, @malibuworkcrew. However, it seems that such a custom compression mechanic would only work if you control both the server and the client.

The websocket compression was to implement websocket compression as specified in the given RFCs so that it will work with any browser that supports the standard.

**Comment by ktoso** [comment]
Hmm, I see -- I wrongly assumed @malibuworkcrew actually implemented what we talked about here, the RFC one.

Indeed should remain closed then, esp since such ticket nowadays should live in https://github.com/akka/akka-http

**Comment by malibuworkcrew** [comment]
Note that it's somewhat difficult to return the content encoding header since akka http websockets build an explicit response here: https://github.com/akka/akka-http/blob/42236687f686d815f923df6c662e74a4d9788758/akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala#L151
