### ISSUE TITLE
"Remembered" shards aren't balanced upon restart

### ISSUE THREAD

**Issue by TimW2014** [akka/akka#17730]
I'm doing some tests on cluster sharding with "rememberEntries" set to true (using 2.4-M1), running a test where I do a failover and then restart the cluster.  

I've noticed that if I have N nodes, one fails over, and then all restart, the "remembered" sharded actors are only restarted on N-1 nodes (seemingly corresponding to (but not identical to) their last locations) -- leaving one with nothing to do.  With large clusters, this is probably not a huge deal, but it can be quite significant on small clusters (4 or fewer nodes).

(Eventually, a bit of rebalancing occurs, but just a little...)

**Comment by rkuhn** [comment]
This is mostly a result of distributed computing: the ShardCoordinator needs to keep track of what is where across crashes and after a restart it will have to assume that everyone else is still working. Not sure how much we can change this, but thanks for the ticket.

**Comment by patriknw** [comment]
@TimW2014 It might also be due that not all nodes are Up at the same time after the restart. Using `min-nr-of-members` might help. http://doc.akka.io/docs/akka/2.3.11/scala/cluster-usage.html#How_To_Startup_when_Cluster_Size_Reached

Perhaps you can reduce the `rebalanceThreshold` of the `LeastShardAllocationStrategy` to rebalance more eagerly.
