### ISSUE TITLE
Easy to Use Pickled Components

### ISSUE THREAD

**Issue by sirinath** [akka/akka#17739]
I feel one of the main success factors streams is how easy you can store, retrieve, manipulate and use the components.

Hence it would be good to have a mechanism specifically tailored to pickle / unpickle pre materialisation components. 

E.g.
```
@Componenet("EMA")
FlowGraph.partial() { ... }

....

val g = StreamComponenet.get[TheShape]("EMA")
```

**Comment by rkuhn** [comment]
Since Graphs are just normal immutable values you can use whichever repository mechanism you like (including DI frameworks or the like). Is there a reason to bake one such mechanism into Akka when all are applicable?

**Comment by sirinath** [comment]
I am thinking something lightweight and specific to the use of streams. Also it should work properly with no hiccups. So a internal pickling and DI may be a good option as a well tested wrapper which is easy to use and idiomatic. Above example is just to give a flavour, there might be more idiomatic ways to do this.

May be https://github.com/scala/pickling, and borrowing the new DI experiance from Play also might help the cause.

**Comment by ktoso** [comment]
Why not "just use https://github.com/scala/pickling"? API wise it's pretty simple with the built-in pickler :-) 
It's a project which's sole existence is about making serialization both fast and simple to use.

**Comment by sirinath** [comment]
For starters all the simple to use examples use the same reference to the pickling object which might not be available when you want to unpick. If you want to refer to a component by a name or string there is no much documentation on these aspects. Also not sure about stability or readiness. Also documentation is next to nothing. So maybe some wrapper to refer by name and also unpicking without the original picking reference can be something you can add to the wrapper. Similarly a stander DI wrapper.

**Comment by sirinath** [comment]
For text based picking you can have a standardised formats that works everywhere.

**Comment by rkuhn** [comment]
Paraphrasing, you want a light-weight DI solution that works without hiccups. This seems to be out of scope for Akka or Streams since it is a much more general problem that does not get simpler by restricting it to Graphs. We need to draw the line somewhere, and HTTP itself is already pushing it :-)

**Comment by sirinath** [comment]
I am looking for a graph representation like how it is done in the http://noflojs.org/.

**Comment by sirinath** [comment]
In order to do the above you need to be able to define and load the components. This has some overlap in DI and pickling (load and then inject). If you have such define format then you can perhaps define a visual editor to specify and manipulate the relationship between the defined components. The above (http://noflojs.org/) project has a Visual Editor. There are other projects which piggy bank on this editor. Also there are other frameworks which you can use to define the graphs visually like: http://www.jointjs.com/, https://github.com/bpmn-io/diagram-js.

**Comment by sirinath** [comment]
Also I am you should have your own but you should have a wrapper. E.g. Play! Framework has DI wrapper to which you can add any JSR 330 compliant DI framework. In this cause you need either 2 such wrappers or 1 wrapper covering both DI and serialisation (in this case defined and persisted components so slightly beyond just pure low level serialisation). This would just reduce boilerplate and also give consistent access to any underlying implementation.
