### ISSUE TITLE
failed: another RemoteReDeploymentSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17733]
https://jenkins.akka.io:8498/job/akka-multi-node/1083/consoleFull

We already have #17440, but I think this is something else

**Comment by drewhk** [comment]
Weird:

[JVM-2] [WARN] [06/12/2015 16:24:44.331] [RemoteReDeploymentMultiJvmSpec-akka.actor.default-dispatcher-4] [akka.remote.transport.FailureInjectorTransportAdapter(akka://RemoteReDeploymentMultiJvmSpec)] FailureInjectorTransport is active on this system. Gremlins might munch your packets.

then later

[JVM-1] [WARN] [06/12/2015 16:24:45.575] [RemoteReDeploymentMultiJvmSpec-akka.actor.default-dispatcher-4] [akka.remote.transport.FailureInjectorTransportAdapter(akka://RemoteReDeploymentMultiJvmSpec)] FailureInjectorTransport is active on this system. Gremlins might munch your packets.

then:

[JVM-2] [ERROR] [06/12/2015 16:24:47.516] [RemoteReDeploymentMultiJvmSpec-akka.remote.default-remote-dispatcher-6] [akka.trttl.gremlin.tcp://RemoteReDeploymentMultiJvmSpec@a4.moxie:56864/remote/akka.trttl.gremlin.tcp/RemoteReDeploymentMultiJvmSpec@a5.moxie:42444/user/parent/hello] swallowing exception during message send (akka.remote.RemoteTransportExceptionNoStackTrace)

and then:

[JVM-2] [WARN] [06/12/2015 16:24:47.575] [RemoteReDeploymentMultiJvmSpec-akka.actor.default-dispatcher-4] [akka.remote.transport.FailureInjectorTransportAdapter(akka://RemoteReDeploymentMultiJvmSpec)] FailureInjectorTransport is active on this system. Gremlins might munch your packets.

Why does JVM-2 log *twice* that it has Gremlin enabled? And what is that swallowed exception before?

**Comment by drewhk** [comment]
So RemoteTransportExceptionNoStackTrace is only thrown from the Remoting class, and only when the manager actor is not available! (and the "swallowing exception during ..." part probably comes from RemoteActorRef)

**Comment by drewhk** [comment]
This reminds me of an earlier case where it seemed to be two JVMs running in the same test somehow, mixed up. It is said that ther INFO level is not logged here so we could see the initialization log from remoting showing the address.

**Comment by drewhk** [comment]
And previous test's JVMs have reported shut down...

**Comment by patriknw** [comment]
I think this is the only test we have that is using testconductor's `startNewSystem`. There might be a bug in that code, since the test fails on the barrier "cable-cut".

**Comment by drewhk** [comment]
Aaaah. That can explain it.
