### ISSUE TITLE
failed: PersistentFSMActorSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17734]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2531/consoleFull

Looks like too tight timeout.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1088/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1090/consoleFull

**Comment by patriknw** [comment]
@ktoso is this same as the one you have been working on?

**Comment by ktoso** [comment]
Oh it had a ticket – yes that's the same problem.
Did not find it when splitting out from the large ticket into https://github.com/akka/akka/issues/18162

**Comment by ktoso** [comment]
Closing as duplicate
