### ISSUE TITLE
In akka-http-RC3 formFields some times lose on IOS

### ISSUE THREAD

**Issue by huanwuji** [akka/akka#17740]
when visit ios on akka http server, It will lose formFields irregularly

right:

```
Request : HttpRequest(HttpMethod(POST),http://url/login,List(Host: yunwan2.3322.org:57099, Cookie: JSESSION=2165f1e3-50db-4dd2-b234-2cd42bbff4fa; JSESSION       ID=52AF7464AB6BCFB4C3E5732EB773836B, Connection: keep-alive, Accept: */*, User-Agent: WDG0123/com.shuyun.WDG0123 (1.02; OS ban ben 8.3 (ban hao 12F69)), Accept-Language: en, f       r;q=0.9, de;q=0.8, zh-Hans;q=0.7, zh-Hant;q=0.6, ja;q=0.5, Accept-Encoding: gzip, compress;q=0.5),HttpEntity.Strict(application/x-www-form-urlencoded,ByteString(112, 97, 115,        115, 119, 111, 114, 100, 61, 49, 50, 51, 52, 53, 54, 38, 117, 115, 101, 114, 110, 97, 49, 55, 54, 52, 49, 57, 55, 48)),HttpProtocol(HTTP/1.1))
```

wrong:

```
Request : HttpRequest(HttpMethod(POST),http://url/login,List(Host: yunwan2.3322.org:57099, Connection: keep-alive, Accept: */*, User-Agent: WDG0123/com.sh       uyun.WDG0123 (1.02; OS Version 8.3  (Build 12F70)), Accept-Language: zh-Hans, Accept-Encoding: gzip, compress;q=0.5),HttpEntity.Default(application/x-www-form-urlencoded,36,ak       ka.stream.scaladsl.Source@7b5f9fbf),HttpProtocol(HTTP/1.1))
```

**Comment by mengfanhong** [comment]
O solve this problem

**Comment by sirthias** [comment]
From the ticket description it is not clear what the problem is.
@huanwuji Maybe you expect all entities to be of type `HttpEntity.Strict`?
This is not and cannot be the case. Depending on the way the network chunks the request into packets you will see `HttpEntity.Default` instances as well.

**Comment by huanwuji** [comment]
@sirthias 
This is use the same interface
android and browse request don't have problem
But in IOS The same request, It will be occurred some times, right part is normal, wrong part I see the log, It may be lose,
I only use like this,
(path("login") & post & formFields('username, 'password) & optionalCookie(sessionName) & headerValueByType[`User-Agent`]())
if lose form, I can't match this path

**Comment by sirthias** [comment]
What error or rejection do you get in the "wrong" case?

**Comment by huanwuji** [comment]
Don't have any error, only can't match, because request has lose params.
This don't found on spray. Then I rewrite it by akka http, it's occurred.

**Comment by sirthias** [comment]
If you could provide us with an [SSCCE](http://sscce.org/) for the problem we'd be happy to investigate it and fix any potentially existing issues.

**Comment by rkuhn** [comment]
@sirthias I think this is “fixed” by the more deterministic strict entity behavior we implemented in Manchester: now it will fail or succeed universally.

**Comment by jrudolph** [comment]
What is Manchester?

**Comment by sirthias** [comment]
@rkuhn Yes. This is the ticket: https://github.com/akka/akka/issues/18540.
@jrudolph Manchester Airport. It was the location where @rkuhn, @matsluni and myself came up with #18540.

**Comment by rkuhn** [comment]
Indeed, thanks @sirthias for filling in the details!
