### ISSUE TITLE
Exceptions thrown in Subscription are not gracefully handled

### ISSUE THREAD

**Issue by jroper** [akka/akka#17759]
The following source:

```scala
  def errorSource[T] = Source(new Publisher[T] {
    def subscribe(s: Subscriber[_ >: T]) = {
      s.onSubscribe(new Subscription {
        def cancel() = ()
        def request(n: Long) = sys.error("error")
      })
    }
  })
```

As you can see request simply throws an error, rather than passing an error to the subscriber.  If I then:

```scala
Await.result(errorSource[Int].runFold(0)(_ + _), 5.seconds)
```

I expected that code to throw some sort of exception, but it doesn't, it times out.

**Comment by drewhk** [comment]
I think RS Spec rule 2.13 is relevant here:

> onSubscribe, onNext, onError or onComplete MUST return normally except when any provided parameter is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations the only legal way for a Subscriber to signal failure is by cancelling its Subscription. In the case that this rule is violated, any associated Subscription to the Subscriber MUST be considered as cancelled, and the caller MUST raise this error condition in a fashion that is adequate for the runtime environment.

**Comment by drewhk** [comment]
Ah, sorry it is 3.16: 

> Calling Subscription.request MUST return normally. The only legal way to signal failure to a Subscriber is via the onError method.

**Comment by ktoso** [comment]
You may want to use the TCK ( https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck ) when implementing Publisher or Subscriber manually, there's a lot of weird corner cases one would notmally not think of - those tests should help you implement a valid Publisher.

**Comment by jroper** [comment]
@ktoso did you mean @jroper? :smile:

I know it's not implemented correctly, but there's implementing the spec, and then there's gracefully handling spec non conformance. The first is the happy case, any old implementation can do that.  The second is about robustness, and is the difference between libraries that don't have a good development experience and libraries that provide an excellent development experience, it's about helping developers understand what they've done wrong when they've done something wrong, by providing a meaningful error message at a pertinent location.

**Comment by ktoso** [comment]
argh sorry guys, hit `@j` and `[enter]` :wink:

**Comment by jrudolph** [comment]
No worries, I just recently tried to build a custom reactive stream processor at which point the TCK came very handy. (For saving time, that is. In the end I threw away my custom implementation and went with a combination of akka-stream components because I couldn't get the TCK to pass with reasonable effort)

**Comment by drewhk** [comment]
It is impossible to protect against all spec violations, since many of the requirements are about concurrency, visibility, etc. In this particular case I can look at what I can add, but in general RS is very low level and requires *quite* a lot of work and understanding from the implementor.

**Comment by jroper** [comment]
Well, @rkuhn just mentioned he was surprised that I didn't get `AbruptTerminationException`, so asked me to file this ticket.

**Comment by drewhk** [comment]
This is why I said "In this particular case I can look at what I can add," :)

**Comment by drewhk** [comment]
So the fold is not reporting any error because the actor fails during prefetch, i.e. *before* the actual fold logic and the underlying interpreter has been initialized. The actor *do* pass the error to the downstream, however, in this particular case there is no downstream to pass to, only the materialized value, which will not be completed because the logic is not yet even there.

**Comment by rkuhn** [comment]
Right, so we need to catch errors that occur during prefetch and pass them into the interpreter once started up.

**Comment by drewhk** [comment]
yep, that is what I am doing now.

**Comment by drewhk** [comment]
added fix
