### ISSUE TITLE
Provide Sink.flatten without requiring a materializer

### ISSUE THREAD

**Issue by jroper** [akka/akka#17758]
Play needs to be able to flatten futures of Sinks to be Sinks without a FlowMaterialzer.  This could be done by providing the following method on `Sink`:

```scala
flatten[T, M](Future[Sink[T, Future[M]]): Sink[T, Future[M]]
```

Use case described here:

https://github.com/akka/akka/issues/16923#issuecomment-112602881

**Comment by drewhk** [comment]
I am not sure about the generality of this, but I keep it here for discussion. Maybe we can call it Sink.lazy(creator: () => Future[Sink]).

**Comment by rkuhn** [comment]
This would be solved by adding a `Sink.dynamic`:
~~~scala
def dynamic[T, M](f: T => Future[Sink[T, Future[M]]]): Sink[T, Future[M]]
def flatten[T, M](f: Future[Sink[T, Future[M]]]): Sink[T, Future[M]] = dynamic(_ => f)
~~~
(see #20129)
