### ISSUE TITLE
Latest version of Sphinx breaks PDF generation task

### ISSUE THREAD

**Issue by kukido** [akka/akka#17752]
After following documentation instructions from http://doc.akka.io/docs/akka/snapshot/dev/documentation.html I was not able to generate PDF and was getting the following error:

```
[debug] ! Undefined control sequence.
[debug] <argument> \node@class@name
[debug]
[debug] l.18759 ...ection{Partitioning \DUspan{}{{[}*{]}}}
[debug]
[debug] ?
[debug] ! Emergency stop.
[debug] <argument> \node@class@name
[debug]
[debug] l.18759 ...ection{Partitioning \DUspan{}{{[}*{]}}}
[debug]
[debug] !  ==> Fatal error occurred, no output PDF file produced!
[debug] Transcript written on AkkaJava.log.
[debug] make: *** [AkkaJava.pdf] Error 1
```

As it was my workstation, I tried to repeat the procedure in "clean room" environment of VM. Followed the instructions and got exactly the same error.

Obviously, something was wrong. With help from @rkuhn and @ktoso was able to eliminate MacTeX, and the only variable left was Sphinx. Since HTML generation was fine, it was never a main suspect :-)

@ktoso mentioned his version of Sphinx - `1.2.3`, while the latest automatically installed by `pip` is `1.3.1`.

```
You are using pip version 6.1.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Sphinx (1.2.3)
```

I was able to restore the build by forcing `1.2.3` version of Sphinx with `pip`. Will submit the documentation patch shortly.

**Comment by patriknw** [comment]
Thanks for sharing the problem and solution. It would be great if we could make it work with latest, so that we are not stuck on an old version.

**Comment by kukido** [comment]
The following two lines in cluster.rst are causing the generation to fail:

```
Partitioning :ref:`[*] <niy>`
=============================
...
Stateful Actor Replication :ref:`[*] <niy>`
===========================================
```

Looking into Sphinx documentation to see what was changed.

**Comment by kukido** [comment]
The first version of Sphinx not working with current docs is `1.3`

 Looking at version `1.3` [changelog](http://sphinx-doc.org/changes.html#release-1-3-released-mar-10-2015) I see only one change which could have an effect: [Error building sphinx_rtd_theme demo docs with pdf target](https://github.com/sphinx-doc/sphinx/issues/1745)

Now, back to akka documentation. It seems that taking "footnotes" from sections titles solves the issue.

**Comment by kukido** [comment]
Updated PR to work with the latest version of Sphinx. IMHO the build server should be updated with version `1.3.1` and MacTeX `2015`.

**Comment by kukido** [comment]
Any suggestions, comments?

**Comment by 2m** [comment]
Looks great! I have backported your changes to 2.3 branch (#17945) and will rebase to master.

**Comment by 2m** [comment]
Thanks @kukido for a fix! It has been merged to `release-2.3` and `master`. I am not sure how you figured it out, but it would have taken me ours to pinpoint such a little detail. :)

**Comment by kukido** [comment]
@2m Figured it out mostly by looking at the logs and experimentation. Trying to find a workaround was more time consuming, but at the end the simplification has won :-)

**Comment by ktoso** [comment]
Thanks for the help!
