### ISSUE TITLE
add ActorMaterializer.shutdown

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17765]
to clean up all resources when not needed any longer—the lifecycle might need to be shorter than its parent actor’s, especially when using an `ActorSystem` to create it

**Comment by drewhk** [comment]
Also related: https://github.com/akka/akka/issues/17143

**Comment by drewhk** [comment]
@rkuhn what should be the exact semantics here? Shut down all current children of the materializer, in this case it is reusable, or invalidate the materializer -- looks messy to me.

Also, is this a general FlowMaterializer feature, or only ActorFlowMaterializer should have it?

**Comment by rkuhn** [comment]
Only the ActorMaterializer should have it and yes, it shuts it down completely (non-reusable). This is for resource management when creating Materializers dynamically and the parent context is long-lived.

**Comment by drewhk** [comment]
Ok
