### ISSUE TITLE
Add method for prematerializing Sink/Source/Flow etc.

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17769]
For example

    val (ref, source) = Source.actorRef[Int].preMaterialize(materializer)

Will return the materialized value, and a non-reusable source wrapping a running Publisher obtained form the original Source.

**Comment by loicdescotte** [comment]
Use case example :   

   * I'm writing a library that provides an Akka Stream `Source`. 
   * I need to push elements dynamically into this source (via an actor) 
   * but I don't know what clients will do with the source when they get it 
     * maybe transform it with `map`, merge it with another source, split it to several sources...

So need to materialize the actor to be able to send elements into the source.

I could just do 

```scala
val source = Source.actorRef[Item](Int.MaxValue, OverflowStrategy.fail)
val actorRef = Flow[Item].to(Sink.xxx).runWith(source)
```

But I don't want to consume the source elements directly by sending them into a Sink, as the source will be used later by my lib clients. 

In this case, `preMaterialize` method can help.

**Comment by loicdescotte** [comment]
Is it still needed in Akka Streams 2?  Do we have something like a channel to push elements dynamically into a source?

**Comment by drewhk** [comment]
Source.queue?

**Comment by loicdescotte** [comment]
@drewhk Indeed it is exactly what I was looking for!  Many  thanks :)   
I guess the issue can be closed?

**Comment by loicdescotte** [comment]
Sorry you can ignore my previous comment, it might be useful for example if we need to get a reference to a source from a SourceQueue before it's materialized. 
Just a use case example : Play Framework is now using Akka Streams, and it can automatically stream elements from a source to the browser using `Status(httpCode)(source)`.
So Play defines its own Sink and it can be useful to be able to push elements into a source before it's materialized by Play.

**Comment by qpiny** [comment]
If I understand correctly, `Status(httpCode)` should not ask for a `Source` but should be a `Sink`.
Then you can get the actorRef by doing:
```
val actorRef = source.runWith(Status(httpCode))
```

**Comment by loicdescotte** [comment]
Hi @qpiny ,
Sorry my message was certainly not very clear.  
I need to materialize the queue to get a source, I'm not trying to get an actor.
With Play I need a source to use this method : https://www.playframework.com/documentation/2.5.x/api/scala/index.html#play.api.mvc.Results$Status@chunked[C](content:akka.stream.scaladsl.Source[C,_])(implicitwriteable:play.api.http.Writeable[C]):play.api.mvc.Result
But it is just a use case example.

**Comment by qpiny** [comment]
Hi,
I understand. I agree, A solution to get "prematerialized" value of a source would be useful, even if it breaks source reusability.
I also use Play with stream and I'm annoyed that materialized value is inaccessible.
For you specific use case, you can construct a queue with a poll method that returns a future of the next element and make a source using
```
Source.unfoldAsync(queue) { q ⇒ q.poll.map(e ⇒ (Some(q, e))) }
```

**Comment by loicdescotte** [comment]
@qpiny right now I'm solving this like this : 

```scala
def sourceQueue = Action{

    val (queue, pub) = Source.queue[String](10, OverflowStrategy.fail).toMat(Sink.asPublisher(false))(Keep.both).run()

    //stupid example to push elements dynamically
    val tick = Source.tick(0 second, 1 second, "tick")
    tick.runForeach(t => queue.offer("tick"))

    Ok.chunked(Source.fromPublisher(pub))
  }
```

**Comment by patriknw** [comment]
@drewhk is this still relevant?

**Comment by drewhk** [comment]
Relevant it is, but I am hesitant to put this into the stream library. This is something users should deal with IMHO and write their own helper if needed. There is too much opportunity of self-foot-blasting.

**Comment by loicdescotte** [comment]
@drewhk so your advice is to use Sink.asPublisher as a bridge in our utils libs? 
Thanks :)

**Comment by drewhk** [comment]
Hm, there is an alternative:

```scala
def peekMatValue(src: Source[T, M]): (Source[T, M], Future[M]) = {
   val p = Promise[M]
   (src.mapMaterializedValue { m => p.trySuccess(m) }, p.future )
}
```

The above does not do any prematerialization and gives back the materialized value in a Future which completes once the Source has been materialized.

**Comment by loicdescotte** [comment]
@drewhk Thanks it's great I'll try to play with that!

**Comment by loicdescotte** [comment]
@drewhk 
I did not manage to slove my source queue with your tip : 

```
def message = Action.async {
      implicit val system = ActorSystem("queue")
      implicit val materializer = ActorMaterializer()

      val queueSource = Source.queue[String](10, OverflowStrategy.fail)
      val futureQueue = peekMatValue(queueSource)

      futureQueue.map{ queue =>
        println("queue is ready")
        val tick = Source.tick(0 second, 1 second, "tick")
        tick.runForeach(t => queue.offer("tick"))
        Ok.chunked(queueSource)
      }

    }


    def peekMatValue[T,M](src: Source[T, M]): Future[M] = {
     val p = Promise[M]
     src.mapMaterializedValue { m =>
       println("queue is materialized")
       p.trySuccess(m)
     }
     p.future
   }
```

Both of the two println are never printing. 
The previous example with the intermediate publisher was working (see https://github.com/akka/akka/issues/17769#issuecomment-205283582) 

Please tell me if it's not the right place to discuss about that...
Thanks :)

**Comment by qpiny** [comment]
Hi,
It doesn't work because `peekMatValue` is call when the source is started (connect to sink) and you return the source when the pre-materialized value is complete.
The following code should work (not tested) :
```scala
def sourceQueueAction = Action {
      val queueSource = Source.queue[String](10, OverflowStrategy.fail)
      val futureQueue = peekMatValue(queueSource)

      futureQueue.map { queue =>
        println("queue is ready")
        val tick = Source.tick(0 second, 1 second, "tick")
        tick.runForeach(t => queue.offer("tick"))
      }
      Ok.chunked(queueSource)
}
```

**Comment by loicdescotte** [comment]
@qpiny not working better :( 
thanks anyway :)

**Comment by qpiny** [comment]
Right !
Sources are immutable. You must used source returns by mapMaterializedValue in OK.chunked.
The working code (tested) is :
```scala
def sourceQueueAction = Action {
    val (queueSource, futureQueue) = peekMatValue(Source.queue[String](10, OverflowStrategy.fail))

    futureQueue.map { queue =>
      Source.tick(0.second, 1.second, "tick")
        .map(println)
        .runForeach { _ => queue.offer("tick"); () }
    }
    Ok.chunked(queueSource)

  }

  def peekMatValue[T, M](src: Source[T, M]): (Source[T, M], Future[M]) = {
    val p = Promise[M]
    val s = src.mapMaterializedValue { m =>
      println("queue is materialized")
      p.trySuccess(m)
      m
    }
    (s, p.future)
  }
```

**Comment by loicdescotte** [comment]
@qpiny @drewhk awesome it's working !! 
Many thanks :) :)

In my opinion the issue can be closed...

**Comment by loicdescotte** [comment]
@qpiny @drewhk 
Just to understand the difference between the 2 versions, if I'm not using the source from the mapMaterializedValue but the original source does it mean that my sourceQueue is not linked to the queue? 
I don't really understand the reason behind this....

Thanks :)

**Comment by drewhk** [comment]
The Source is an immutable description of the thing that will be executed, it is not running yet (apart from a few exceptions, like when you prematerialize somthing and re-wrap in a Source). All modifications to this description results in a new description which is a new Source instance - i.e. the original Source is not modified.

In fact, you can usually (and should) design your code exposing these reusable compontents/descrptions like Sources Sinks, Flows, etc. They can be cached, reused arbitrary many times and composed in any ways possible safely. Think of them as composable, immutable factories
