### ISSUE TITLE
More typesafety for ReplicatedData#merge

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17770]
As discussed in https://github.com/akka/akka/pull/17499/files#r32720845
It is possible to make the merge function on a distributed data type "only merge apples with apples, and oranges with oranges" by using *self recursive type parameters* (F-bounds).

Here's some docs I did on the pattern: http://ktoso.github.io/scala-types-of-types/#self-recursive-type

```scala
class Data[T] extends Data[Data[T]] {
  def merge(d: T): T = ???
}
```

usage in java:
```java
  static class X extends Data<X> { }
  static class Y extends Data<Y> { }
  {
    X x = new X();
    Y y = new Y();

    x.merge(x);
    y.merge(y);
    x.merge(y); // good, compilation fails: merge(X) cannot be applied to Y
    y.merge(x); // good, compilation fails: merge(Y) cannot be applied to X
  }
```

So this could be improved in next versions for Java I think :-)
Maybe a ticket?

This would possibly make it possible to get rid of `AbstractReplicatedData` and only have `ReplicatedData`, while improving type-safety.

**Comment by patriknw** [comment]
I tried with `abstract class AbstractReplicatedData[D <: AbstractReplicatedData[D]] {`

I'm stuck on one annoying thing when merging the values in `ORMap`. 
https://github.com/akka/akka/commit/482aca115081f95af1e4fabdcebcb4ce7c927094#diff-e15b95357b14e8543fb6bab6f7408abdR165
`type mismatch; found : thatValue.type (with underlying type A) required: _$6`

I can't find a way to work around it with casts, either.
