### ISSUE TITLE
A little question: Why routerConfig withFallback itself?

### ISSUE THREAD

**Issue by MQ-EL** [akka/akka#17781]
```scala
def actorOf(system: ActorSystemImpl, props: Props, supervisor: InternalActorRef, path: ActorPath,
              systemService: Boolean, deploy: Option[Deploy], lookupDeploy: Boolean, async: Boolean): InternalActorRef = {
    props.deploy.routerConfig match {

     ...

    case router ⇒
        val lookup = if (lookupDeploy) deployer.lookup(path) else None
        val fromProps = Iterator(props.deploy.copy(routerConfig = props.deploy.routerConfig   withFallback router))
        val d = fromProps ++ deploy.iterator ++ lookup.iterator reduce ((a, b) ⇒ b withFallback a)
        val p = props.withRouter(d.routerConfig)
```

The Line729 located In ActorRefProvider.scala:

```scala
val fromProps = Iterator(props.deploy.copy(routerConfig = props.deploy.routerConfig withFallback router))
```

The router is the same object as props.deploy.routerConfig IMO, did it has some deep implicit meaning?

The code in Line 730 doesn't needed with fallback of deploy, just fallback of deploy.routerConfig is enough? 
```scala
val d = fromProps ++ deploy.iterator ++ lookup.iterator reduce ((a, b) ⇒ b withFallback a)
```

Maybe refactor to this(?):
```scala
val c = props.deploy :: deploy.toList ::: lookup.toList reduce ((a,b) ⇒ b.routerConfig withFallback a.routerConfig)
```
Do i something wrong or miss some key knowledge?

**Comment by MQ-EL** [comment]
Hi! Is this question too simple to answer?(may be i have a little Clumsy), could some body help me?

**Comment by patriknw** [comment]
Thanks for asking, reporting. I have swapped out how the deploy fallbacks works at the moment.

Have you found anything that is not working as expected or is a just a matter of code cleanup?

**Comment by MQ-EL** [comment]
1. For avoid unnesscery fallback of deploy object, do routerConfig fallback is enough IMO.
2. router is as the same object as props.deploy.routerConfig, so doesn't need fallback itself 

 It may be refactor as follows, 

```scala
val lookup = if(lookupDeploy) deployer.lookup(path) else None
val r = props.deploy :: deploy.toList ::: lookup.toList reduce ((a,b) ⇒ b.routerConfig withFallback a.routerConfig)
val p = props.withRouter(r)

 if (!system.dispatchers.hasDispatcher(p.dispatcher))
    throw new ConfigurationException(s"Dispatcher [${p.dispatcher}] not configured for routees of $path")
 if (!system.dispatchers.hasDispatcher(r.routerDispatcher))
    throw new ConfigurationException(s"Dispatcher [${p.dispatcher}] not configured for router of $path")

```

It's just about code cleanup.
Am i right?

**Comment by patriknw** [comment]
I agree with your assessment. `props.deploy.routerConfig withFallback router` is rather funny. Would you like to create a pull request?

**Comment by MQ-EL** [comment]
Hi @patriknw, could you check my commit? I cannot find that the cause is because of my commit.

**Comment by MQ-EL** [comment]
Hi @patriknw, please check my pr when you have time off :)
