### ISSUE TITLE
Enable dynamic configuration of TCP close modes

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17788]
See original ticket: https://github.com/akka/akka/issues/16899

Configurable close modes was implemented in https://github.com/akka/akka/pull/17787 in a more limited fashion, this ticket is about enabling dynamic configuration of the close mode.

**Comment by rkuhn** [comment]
Why and how?

**Comment by drewhk** [comment]
I have no clue, maybe no longer relevant
