### ISSUE TITLE
Inconsistent NodeMetrics message order in ClusterMessageSerializer

### ISSUE THREAD

**Issue by gds718** [akka/akka#17785]
if you subscribe the ClusterMetricsChanged event,and trying to use id via nodeAddress -> Seq[NodeMetrics],then you will finally find the Inconsistent for the mapping.
eg.address A -> nodeMetrics A you expected,but may got address A -> nodeMetrics B

https://github.com/akka/akka/issues/16667

The BUG still exists in version 2.3.11

**Comment by rkuhn** [comment]
It seems that at least a test is missing for the previous fix.

**Comment by patriknw** [comment]
The fix in #16667 for the serializer looks correct. @gds718 can you provide some more information about the problem you are seeing? Is there a way to reproduce it?

**Comment by patriknw** [comment]
@gds718 any update here, otherwise I will close this as invalid.

@hepin1989 are you using metrics, do you think this issue is valid?

**Comment by hepin1989** [comment]
@patriknw I can't test this now,one of my cowork leave,and I don't know how to setup the GM app.
@gds718 could you please tack a deep look at the problem ?

**Comment by patriknw** [comment]
@hepin1989 no problem, I just wanted to check if you already knew that this was a real bug

**Comment by gds718** [comment]
https://gist.github.com/gds718/daf18565e2f68ce7fffa

**Comment by patriknw** [comment]
@gds718 Thanks for a good reproducer test case. That must be a bug.

    (akka.tcp://test@10.1.0.129:2552,Some(Metric(processors,8,None)))

**Comment by hepin1989** [comment]
@gds718 are you building some monitoring ?In fact after that bug,we starting to send the metrics to a center server,btw,you cloud add the qq group:```257534530```.

I see the gist,it shows up,yeah,must be somewhere missed.

**Comment by patriknw** [comment]
@gds718 I see that some things have been changed in the merging of the metrics in the new metrics module in 2.4.0-RC1. Could you try http://doc.akka.io/docs/akka/2.4.0-RC1/scala/cluster-metrics.html
Note that you must disable the old metrics and enable the new one with configuration, see migration guide http://doc.akka.io/docs/akka/2.4.0-RC1/project/migration-guide-2.3.x-2.4.x.html#New_Cluster_Metrics_Extension

**Comment by gds718** [comment]
@patriknw @hepin1989 
I used the wrong version of akka in the test environment.
It's not a  bug.
I'm sorry to bother you.

**Comment by patriknw** [comment]
ok, thanks for the update
