### ISSUE TITLE
Update Documentation for Cluster Client - Missing Client Config

### ISSUE THREAD

**Issue by jasongoodwin** [akka/akka#17794]
Cluster Client Documentation should be updated.

The client should not have this config in the documentation:

    akka.contrib.cluster.client {
      mailbox {
        mailbox-type = "akka.dispatch.UnboundedDequeBasedMailbox"
        stash-capacity = 1000
      }
    }

It should instead have this config:

    akka {
      actor {
        provider = "akka.cluster.ClusterActorRefProvider"
      }
      contrib.cluster.client {
        mailbox {
          mailbox-type = "akka.dispatch.UnboundedDequeBasedMailbox"
          stash-capacity = 1000
        }
      }
    }

This is insanely confusing because the client won't operate without changing the provider.

**Comment by patriknw** [comment]
ok, it should also work with the RemoteActorRefProvider

thanks for reporting

**Comment by patriknw** [comment]
It was already mentioned in docs in 2.4-M2
