### ISSUE TITLE
Remove permanent flag in deleteMessages

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17799]
As per discussion with @ironfish the soft-delete is a pain to implement and we don't see the purpose of it.

I think this also means that deleted flag in PersistentRepr can be removed.

**Comment by patriknw** [comment]
cc @ktoso

**Comment by ktoso** [comment]
Sounds good, users can always first migrate data to some other store if they want to keep it after deletion in the used-by-akka-journal.
