### ISSUE TITLE
Cookbook pattern: restartable child process of ActorPublisher/Subscriber

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17807]
If the Source/Sink needs to do some error recovery in the background then it might make sense to separate it to a child actor of the ActorPublisher. This way the streaming state persists even after a failure happens in the risky operation - the risky child process can be restarted independently.

**Comment by patriknw** [comment]
note that the internal stream state is actually restored when ActorPublisher is restarted

**Comment by patriknw** [comment]
same with ActorSubscriber, by the way

**Comment by drewhk** [comment]
Ah, ok. but it does not restore state like "which are the still pending requests from IO source X", so I think it still helps to keep this state in the parent, and the actual IO work in the child, so the parent knows which requests to retry after child restart.

**Comment by patriknw** [comment]
yes, that is a good pattern

**Comment by rkuhn** [comment]
Not sure about this one: shouldn’t ActorPublisher/ActorSubscriber be hidden in the closet under the stairs?

**Comment by drewhk** [comment]
I dunno. Back then there were no GraphStages. The idea here was a pattern where you separate your dangerous task (reading from something flaky) to a child so it can be restarted without losing backpressure data which is kept in the parent.
