### ISSUE TITLE
Provide inline broadcast

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17827]
Sounds to me me as a pretty common case, to broadcast to multiple Sinks "in line".

A naive implementation below:

```scala
  val sink = Sink.foreach[Int](i => println("sink: " + i))
    
    Source(1 to 2)
      .inlineOnComplete(_ => println("done"))
      .runWith(sink)

    Source(1 to 2)
      .inlineBroadcast(Sink.onComplete(_ => println("done")))
      .runWith(sink)
    
    implicit class OnCompletePassThrough[T](s: Source[T, Unit]) {
      def inlineOnComplete(callback: Try[Unit] => Unit): Source[T, Unit] =
        inlineBroadcast(Sink.onComplete(callback))

      def inlineBroadcast[M](_sink: Sink[T, M]): Source[T, M] =
      Source(_sink) { implicit b => sink =>
        import FlowGraph.Implicits._
        val m = b.add(Broadcast[T](2))
        s ~> m.in
        m.out(0) ~> sink
        m.out(1)
      }
```

**Comment by agolubev** [comment]
@ktoso, actually all (ok, at least many) fan out transformations can be applied, mirroring #18411

**Comment by ktoso** [comment]
We'll need to think it through holistically, we've have been very strict to keep the APIs as minimal as they can be and then "add by need".

@viktorklang and @rkuhn have strong opinions on that, however at the same time things like `tap`, `broadcast` etc definitely we'll want to bring back onto Flow. Let's see, for now `broadcast` is definitely coming back onto Flow

**Comment by rkuhn** [comment]
Yes, we are currently re-evaluating the FlowOps API volume based on user feedback (read: there are a few things missing that frequently tripped people up and we’ll definitely fix those).

**Comment by viktorklang** [comment]
Although I love the name `tap` I also would not like to miss out on the opportunity to call a method `snoop`.

**Comment by agolubev** [comment]
@viktorklang, I found something about ```tap`` (http://doc.akka.io/api/akka-stream-and-http-experimental/0.9/index.html#akka.stream.scaladsl2.Tap), but cannot find anything about ```snoop```. Is it something from existing API hidden somewhere?

**Comment by rkuhn** [comment]
Viktor was making a little joke here :-) The old docs you link to describe roughly the right idea but unfortunately the API has changed significantly so that nothing concrete will be reusable.

**Comment by viktorklang** [comment]
@rkuhn haha, I was only half-joking, (and your recent email to akka-user confirms my point):

`tap` is ambiguous in the context (you used it to mean faucet on akka-user) but it is also "wiretap" and there's a crucial difference: "tapping" means removing whereas in our case we'd be "diverting" if we used it in a "faucet" sense. `snoop` doesn't carry the diverting/control aspect of a faucet.

I'm not sold on `snoop` but `tap` is definitely problematic. #namingishard

**Comment by rkuhn** [comment]
Ah, right, thanks for the correction: Tap was indeed the wrong tap! The feature @agolubev was asking about started out being named “monitor” during a walk to a lunch in Philly last year. But I’m not sure that makes is easier to find ;-)

So, to remove all confusion: this is about #15077.

**Comment by viktorklang** [comment]
Monitor is good but also overloaded.

Since we are talking about something that adds Sinks, what about 'alsoTo'
or something that reuses the Sink verbiage.

-- 
Cheers,
√

**Comment by viktorklang** [comment]
I propose:

~~~scala
def snoop(that: Graph[SinkShape[Out], _]): Repr[Out, Mat] = snoopMat(that)(Keep.left)
  def snoopMat[Mat2, Mat3](that: Graph[SinkShape[Out], Mat2])(matF: (Mat, Mat2) ⇒ Mat3): Repr[Out, Mat3] =
    this.viaMat(Flow(that) { implicit b ⇒
      r ⇒
        import FlowGraph.Implicits._
        val bcast = b.add(Broadcast[Out](2))
        bcast.out(1) ~> r
        (bcast.in, bcast.out(0))
    })(matF)
~~~

**Comment by rkuhn** [comment]
snoop, v: *investigate or look around furtively in an attempt to find out something, especially information on someon’s private affairs*

So, no, I don’t think this is an appropriate name. If `broadcast` does not work, then the only other reasonable proposal has been `alsoTo`.

**Comment by viktorklang** [comment]
`alsoTo` is a good compromise.

**Comment by ktoso** [comment]
AFAICS this also solved https://github.com/akka/akka/issues/18510
