### ISSUE TITLE
Move BackoffSupervisor from akka persistence package

### ISSUE THREAD

**Issue by Horusiath** [akka/akka#17842]
Right now a [BackoffSupervisor](https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/BackoffSupervisor.scala) is implemented inside akka.persistence package. Since it doesn't depend on anything persistence-specific, the idea is to move it into akka core under akka.pattern module.

**Comment by patriknw** [comment]
thanks for the ticket

**Comment by patriknw** [comment]
If we do this we should also remember to add a description of it in the actor Fault Tolerance documentation section.

**Comment by ktoso** [comment]
I think it's a nice idea, back-off is a very nice universally useful tool to have :)

**Comment by patriknw** [comment]
ok, let's do it

**Comment by michaelom** [comment]
Exponential backoff during restart is a very useful feature (particularly in a CQRS setup).
+1

**Comment by ktoso** [comment]
// cc @Horusiath, we moved this class to `akka.pattern`
