### ISSUE TITLE
deletingMessagesTo should signal success/failure back to the Actor

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17845]
Since all our methods yield some status this one should as well (esp. since we have this information from the `Future[]` returned by `deleteMessagesTo`, and we do this style for deleting snapshots).

Original discussion: https://github.com/akka/akka/commit/b09c3cece05124f096545d183460b0f27894eb87#commitcomment-11878253

**Comment by ktoso** [comment]
See discussion https://github.com/akka/akka/commit/b09c3cece05124f096545d183460b0f27894eb87#commitcomment-11878253

**Comment by ktoso** [comment]
Failure is already signalled, as callback `onDeleteMessagesFailure`, but we don't have a "successfully deleted" message / callback. This could be useful when someone wants to shut down the app once successfully deleting some data etc.

**Comment by patriknw** [comment]
I agree. We should make this consistent with snapshots, and that might mean removing the `onDeleteMessagesFailure` and using messages instead. I think we should have some kind of default warning logging of these failures, also for snapshots.

**Comment by ktoso** [comment]
For snapshots we went with messages because we assume they are "rare", and message things have these callback.. Need to draw out how we signal each situation to make it consistent somehow

**Comment by ktoso** [comment]
Will be addressed as part of https://github.com/akka/akka/issues/17518
