### ISSUE TITLE
Revisit default journal dispatcher configuration

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17844]
We should also mention something about dispatchers in the plugin api documentation, e.g. what dispatcher to use for spawning futues. 

We normally use thread-pool-executor for blocking dispatchers.

If the plugin writes are implemented synchronously it will be a single writer (pinned dispatcher) for the entire journal. Nothing wrong with that, but we should describe it in the docs, so that it is clear.

**Comment by ktoso** [comment]
Good points, marking as docs ticket.
