### ISSUE TITLE
Akka scheduler thread references the wrong ClassLoader

### ISSUE THREAD

**Issue by benmccann** [akka/akka#17857]
When running a Play server if you repeatedly edit a file and reload your browser the server will crash with an out of memory error. See https://github.com/playframework/playframework/issues/4649. This problem can be traced back to Akka by using jstack with Play as described in https://github.com/playframework/playframework/issues/4469

The thread leaks being reported by jstack look like:

>"application-akka.actor.default-dispatcher-9" #402 prio=5 os_prio=0 tid=0x00007f5af0841800 nid=0x3833 waiting on condition [0x00007f5ac73bb000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f8c20278> (a akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinPool)
	at scala.concurrent.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2075)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

This is happening in Play 2.4.x which uses Akka 2.3.11. If the bug is fixed in master, I'd really appreciate a backport to the 2.3.x branch. This is a pretty frustrating problem for Play users unfortunately since it happens to all users and having your server crash repeatedly during development is a real productivity killer

**Comment by viktorklang** [comment]
@benmccann Do you mean Scheduler thread or Dispatcher thread?

**Comment by benmccann** [comment]
Hmm, I don't really know. I'm not familiar with Akka at all. @richdougherty @jroper @planetenkiller do you guys have any idea?

**Comment by richdougherty** [comment]
I think it's the scheduler thread. From what I saw, here's what I think happened:

* Start `ActorSystem` in `ClassLoader` A. This `ActorSystem` will be shared across multiple reloads of Play.
* Start Play in `ClassLoader` P1.
* Reload Play application in `ClassLoader` P2.
* Notice that Akka scheduler thread holds a reference to `ClassLoader` P1 — it should reference `ClassLoader` A instead.

My theory is that the scheduler thread picks up the _contextClassLoader_ of the thread where the first operation is scheduled from, `ClassLoader` P1 in this example. I think it should always use the `ActorSystem` `ClassLoader` instead, i.e. `ClassLoader` A.

**Comment by viktorklang** [comment]
Interesting!

Are you passing in the ClassLoader to the ActorSystem.apply?

On Sun, Jun 28, 2015 at 11:26 AM, Rich Dougherty <notifications@github.com>
wrote:

> I think it's the scheduler thread. From what I saw, here's what I think
> happened:
>
>    - Start ActorSystem in ClassLoader A. This ActorSystem will be shared
>    across multiple reloads of Play.
>    - Start Play in ClassLoader P1.
>    - Reload Play application in ClassLoader P2.
>    - Notice that Akka scheduler thread holds a reference to ClassLoader
>    P1 — it should reference ClassLoader A instead.
>
> My theory is that the scheduler thread picks up the *contextClassLoader*
> of the thread where the first operation is scheduled from, ClassLoader P1
> in this example. I think it should always use the ActorSystem ClassLoader
> instead, i.e. ClassLoader A.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/17857#issuecomment-116238021>.
>



-- 
Cheers,
√

**Comment by richdougherty** [comment]
Yes, we're passing in a `ClassLoader` when we create the `ActorSystem`. The main dispatcher threads use the correct `ClassLoader`, but the scheduler thread doesn't.

**Comment by viktorklang** [comment]
@richdougherty This is much surprising given that that thread is created using the exact same ThreadFactory as the rest, which sets the Thread's context class loader to the one that was passed into the ActorSystem construction.

**Comment by richdougherty** [comment]
@viktorklang, my mistake. In Play's dev mode we're actually [creating a second `ActorSystem` which uses a separate `ClassLoader`](https://github.com/playframework/playframework/issues/4649#issuecomment-116797384). I implemented this, but completely forgot about it! Sorry about the noise.

**Comment by viktorklang** [comment]
Great catch, Rich!

-- 
Cheers,
√
