### ISSUE TITLE
Don't publish akka-bench-jmh

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17855]
Got validation error from sonatype:
validation failure: Invalid POM: /com/typesafe/akka/akka-bench-jmh/2.4-M2/akka-bench-jmh-2.4-M2.pom: Project URL missing, License information missing

We should perhaps add that license thing anyway

**Comment by ktoso** [comment]
What is bull :-) (build I guess :wink:)

Yes, and stop it from being published as well.

**Comment by patriknw** [comment]
:-)
