### ISSUE TITLE
StatefulStage terminationEmit sometimes replaces previously emitted elements

### ISSUE THREAD

**Issue by mvdz** [akka/akka#17853]
The following code fails on Akka Streams 1.0-RC4 (with Akka 2.3.11 and Scala 2.11.6).

I would expect the elements given to `terminationEmit` to be emitted after the elements given in the last `emit`. This works as expected when there is enough demand to emit all elements immediately. However in the case below there is only enough demand for the first element and the upstream finishes before the second element is emitted. The result is that the second element is never emitted, replaced by the `terminationEmit`.

```scala
def testStage() = new StatefulStage[String, String] {
  override def initial = new State {
    override def onPush(elem: String, ctx: Context[String]) =
      emit(Iterator(elem, elem), ctx)
  }
  override def onUpstreamFinish(ctx: Context[String]) =
    terminationEmit(Iterator("byebye"), ctx)
}

Source.single("hi")
  .transform(testStage)
  .runWith(TestSink.probe[String]())
  .request(1) // works when requesting more than 1 here
  .expectNext("hi")
  .request(2)
  .expectNext("hi")
  .expectNext("byebye")
  .expectComplete()
```

**Comment by drewhk** [comment]
Yes, it looks like it overwrites the previous emit state instead of chaining. Thanks for reporting. As a workaround you can use PushPullStage directly (it might be slightly less convenient, depends on your use case).
