### ISSUE TITLE
Issues importing docs into Dash

### ISSUE THREAD

**Issue by briantopping** [akka/akka#17860]
Not sure if this is just me or a general issue. I've noticed some of the doc sets are not compatible with Dash. Dash reports the attached error. I see this for akka-http-testkit and akka-streams, probably a few others. Seems like it would be nice to resolve for the final release. 

Go team go! :)

![downloads](https://cloud.githubusercontent.com/assets/158115/8398684/be7ec3a2-1dad-11e5-90b7-cbd73204f3c6.png)

**Comment by ktoso** [comment]
Good catch, I'm not sure what on our side might have been the reason... 
Might be a good idea to reach out to support@kapeli.com and see what the problem is in Dash

**Comment by briantopping** [comment]
I reached out to them back then and don't remember exactly why they said it wasn't their fault. Hum. Closing issue...
