### ISSUE TITLE
http: getFromResourceDirectory fails if the absolute path to the server contains a space

### ISSUE THREAD

**Issue by stanch** [akka/akka#17873]
Example:
```scala
pathPrefix("assets") {
  getFromResourceDirectory("public")
}
```
Note the space in `/path/player 2/lib/...`:
```
[ERROR] [06/30/2015 23:28:01.375] [player-akka.actor.default-dispatcher-13] [ActorSystem(player)] Error during processing of request HttpRequest(HttpMethod(GET),http://localhost:8080/assets/stylesheets/common.css,...)
java.io.FileNotFoundException: /path/player%202/lib/player_2.11-0.1-SNAPSHOT-web-assets.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:121)
	at akka.http.scaladsl.server.directives.FileAndResourceDirectives$ResourceFile$.apply(FileAndResourceDirectives.scala:210)
```

This is happening in this method: https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-RC4/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala#L199.

Looks like it’s a [known problem with `j.u.z.ZipFile`](https://code.google.com/p/reflections/issues/detail?id=99). I was able to reproduce it on Windows 7 and on Ubuntu. *akka-http* version `RC4`.

**Comment by drewhk** [comment]
/cc @sirthias @jrudolph 

Although I am not sure what to do if the bug is in ZipFile

**Comment by stanch** [comment]
I should add that this also happens with other percent-encoded characters, not just with spaces.

**Comment by stanch** [comment]
And more context: http://stackoverflow.com/questions/9873845/java-7-zip-file-system-provider-doesnt-seem-to-accept-spaces-in-uri. That page contains some workarounds.

**Comment by stanch** [comment]
Here’s a simple reproduction: https://github.com/stanch/akka-http-spaces. It has both spaces and non-latin characters.
