### ISSUE TITLE
Missing Java-API for Cluster.joinSeedNodes

### ISSUE THREAD

**Issue by michaelom** [akka/akka#17870]
Cluster.get(system).joinSeedNodes takes a Seq as argument.

Apparently there are some workarounds for this issue as described here:
http://stackoverflow.com/questions/6784593/how-to-create-a-scala-collection-immutable-seq-from-a-java-list-in-java

Please add a more idiomatic version of joinSeedNodes.

**Comment by ktoso** [comment]
Hi @michaelom,
good catch, I think you're right about it deserving an explicit java API as it's a pretty important method - will add it right away (to master).

In the mean time you can use it from java as documented in it's javadoc:

```java
   * JAVA API: Use akka.japi.Util.immutableSeq to convert a java.lang.Iterable
   * to the type needed for the seedNodes parameter.
   */
  def joinSeedNodes(seedNodes: immutable.Seq[Address]): Unit = // ...

// joinSeedNodes(immutableSeq(myList))
```

**Comment by ktoso** [comment]
Submitted PR to address this: https://github.com/akka/akka/pull/17874
Thanks for bringing it up!
