### ISSUE TITLE
Akka Persistence migration guide should explain sender is not available in recovery

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17885]
The change https://github.com/akka/akka/pull/17744 means that we do not have the sender (from the serialized reference) available during recovery. There might be code which assumed that the sender is an actual sender (well it would be weird to rely on this, but for limited cases it perhaps even worked).

We should document that sender() in `receiveRecover` is now always `deadLetters`

Reported by @chbatey, thanks!

**Comment by patriknw** [comment]
That is a valid point. I don't think it ever was documented what sender should be during recovery.
Here is the pull request by the way: https://github.com/akka/akka/pull/17744
