### ISSUE TITLE
Integration with reactive streams Processors

### ISSUE THREAD

**Issue by jroper** [akka/akka#17891]
Akka streams should provide mechanisms for working with Reactive Streams processors.

Here's a real world use case that I've just had to do.  Let's say I have a `Processor`, and I want to add an Akka flow step to it:

```java
Processor<HttpRequest, HttpResponse> processor = ...
Flow<List<String>, HttpRequest> myFlow = ...

Pair<Subscriber<List<String>>, Publisher<HttpRequest>> pair = 
    Source.<List<String>>subscriber()
    .via(myFlow)
    .toMat(Sink.<HttpRequest>publisher(), 
        Keep.<Subscriber<List<String>>, Publisher<HttpRequest>>both())
    .run(materializer);
pair.second().subscribe(processor);
Processor<List<String>, HttpResponse> newProcessor = 
    new DelegateProcessor<>(pair.first(), processor);
```

And that's assuming that you've already written this class:

```java
public class DelegateProcessor<In, Out> implements Processor<In, Out> {

    private final Subscriber<In> subscriber;
    private final Publisher<Out> publisher;

    public DelegateProcessor(Subscriber<In> subscriber, Publisher<Out> publisher) {
        this.subscriber = subscriber;
        this.publisher = publisher;
    }

    @Override
    public void subscribe(Subscriber<? super Out> s) {
        publisher.subscribe(s);
    }

    @Override
    public void onSubscribe(Subscription s) {
        subscriber.onSubscribe(s);
    }

    @Override
    public void onNext(In in) {
        subscriber.onNext(in);
    }

    @Override
    public void onError(Throwable t) {
        subscriber.onError(t);
    }

    @Override
    public void onComplete() {
        subscriber.onComplete();
    }
}
```

What it should look like is this:

```java
Processor<HttpRequest, HttpResponse> processor = ...
Flow<List<String>, HttpRequest> myFlow = ...

Processor<List<String>, HttpResponse> newProcessor = Flow.from(() -> processor)
    .via(myFlow)
    .toProcessor(materializer);
```

Note that `Flow.from()` takes a zero arg function, since flows can be reused, but processors can't - though in this case it's fine to return the same processor in each time, because the flow is converted to a processor, and so will only ever be used once.

**Comment by ktoso** [comment]
2 features:

- via existing Processor
- given a Flow attach subscriber/publisher sink/source and expose a Processor

**Comment by drewhk** [comment]
The only difference I made is that toProcessor gives a RunnableGraph[Processor] instead of materializing the Processor right away. The reason is that you can still just call run() to get the Processor, but now you are not forced to propagate Materializers where they might not belong otherwise, and the RG also works as a factory.
