### ISSUE TITLE
ByteString.toString is very dangerous in logging

### ISSUE THREAD

**Issue by fommil** [akka/akka#17898]
I've encountered this problem a couple of times, e.g. https://github.com/spray/spray/issues/1060

If a `ByteString` ends up in a log message somewhere it basically blows up the log. GB log entries are not uncommon when sending MB-sized messages.

Often the logging happens deep within the akka.io or spray/etc frameworks and it is not possible to selectively tune the logging.

A safe solution would be to implement a `ByteString.toString` that does something like `take(100).toString`

**Comment by 2beaucoup** [comment]
see  #13709 (and #16395)

**Comment by fommil** [comment]
yes they are somewhat related, but having a "safe" `toString` for `ByteString` would certainly be a good and simple first step.

**Comment by jrudolph** [comment]
+1

**Comment by fommil** [comment]
Is there any possibility of getting this bumped in priority for the next RC or stable release?

I basically can't trust akka-io in production environments until this is fixed, because any network error anywhere in the system, can potentially produce logging **events** (even at WARNING level) that are GB large.

I can't see any usecase for actually calling the current `toString` as it is effectively unreadable.

**Comment by viktorklang** [comment]
While I can definitely sympathize with the situation, it may not be as simple as it is made out to be.

Given that ByteString does not currently override toString, it should be safer to change it in a dot-release, but I am weary against potentially breaking current code that somehow relies on the current behavior.

Things to consider are `ByteString`s compared by string representation (deduplication or otherwise, which is why I'd be against `take(100).toString` etc).

(keep in mind that all invocations of `toString` on something of `AnyRef` type may end up creating a String of size Integer.MAX_VALUE)

My 2¢

**Comment by fommil** [comment]
@viktorklang I'd be ok with a call to the super implementation for `toString` which would have the object ref and avoid the problem you raised (although anyone who's doing that should probably be sent straight to hell)

**Comment by patriknw** [comment]
We are careful with not invoking `toString` on messages (`AnyRef`), for the same reasons. If there iare any places where we do that on `ByteString` in the Akka code base we should fix that.

That said, I agree with that we should implement a more safe `toString` in 2.4, but I'm also not sure about changing this in 2.3.x

**Comment by viktorklang** [comment]
@fommil That suggestion would break all code that considers the toString-representation equality as equality. ByteString("foo").toString == ByteString("foo").toString would suddenly be `false`.

**Comment by fommil** [comment]
@patriknw the problem is things like `LoggingReceive` so this is a really big problem. I'm currently struggling to diagnose a `Tcp.Write` problem because everytime I go near `DEBUG` level the logs blow up.

**Comment by fommil** [comment]
In light of how dangerous this is, I definitely vote for a 2.3.x fix.

**Comment by hepin1989** [comment]
maybe we need something like this
https://github.com/netty/netty/blob/master/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java

**Comment by patriknw** [comment]
I'd not use debug level in production.
Thanks for reporting.

**Comment by fommil** [comment]
@patriknw this happens at WARNING level in spray. See the first linked message.

Also, logging out at DEBUG even in DEV is impossible when each log line is multi-GB.

**Comment by fommil** [comment]
@patriknw and besides, it's a perfectly sensible thing to dynamically switch to full debugging in production environments when diagnosing an issue.

**Comment by patriknw** [comment]
I don't argue that it needs improvement.

**Comment by drewhk** [comment]
I don't see why we can't change the toString in a minor. I don't think comparison by toString is a good idea, especially since ByteString has a proper equality check. There are bugs that if fixed might change some very unfortunate code that relies on the existence of it.

**Comment by viktorklang** [comment]
@drewhk It's not about not being a good idea, it's about possibly silently breaking other people's already tested and working code.

**Comment by fommil** [comment]
You're making a mountain out of a molehill. There's a real issue here and anyone abusing java 101 (don't use toString programmatically) most likely has bigger problems to worry about.

**Comment by viktorklang** [comment]
If nobody uses toString programmatically then this ticket is moot, isn't it?

**Comment by hepin1989** [comment]
add a ```ByteStringUtil``` for safe dump?

**Comment by fommil** [comment]
After speaking with my colleagues, we believe that sending abusers of `toString` straight to hell is a bit extreme. A beating with a rubber hose should suffice.

**Comment by drewhk** [comment]
I have no strong feelings for inclusion in 2.3.x or not.

**Comment by fommil** [comment]
I'll be upgrading just for this fix :-)

**Comment by ktoso** [comment]
:+1: :-)
