### ISSUE TITLE
LoggingAdapter need support more args

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#17895]
maybe using a generator to generate some code.to support more arity for `debug,info,error,warning`,
current the arity is limited to 4.

**Comment by ktoso** [comment]
Sounds good to me, since we now have the boilerplate plugin on master in akka-user anyway we could make use of it for this.

**Comment by 2beaucoup** [comment]
Is it possible to switch to varargs?

**Comment by ktoso** [comment]
varargs costs an array allocation - and this api tries to avoid additional allocations :)

**Comment by 2beaucoup** [comment]
I see. The boilerplate seems like the way to go.

**Comment by patriknw** [comment]
Would it be possible to use varargs for cases with more than 4 args?

**Comment by hepin1989** [comment]
I think it may be not need to be 22 args,but I think 5 or 6 at least.

**Comment by patriknw** [comment]
yes, I think we should explore alternatives before boilerplating it, allocation overhead would be alright for the rare cases of > 4

**Comment by kukido** [comment]
Could it be something like:

```scala
  def error(cause: Throwable, template: String, arg1: Any, arg2: Any, arg3: Any, arg4: Any, arg: Any*): Unit = {
    if (isErrorEnabled) {
      notifyError(cause, format(template, Seq(arg1, arg2, arg3, arg4) ++ arg))
    }
  }
```

**Comment by patriknw** [comment]
That was what I had in mind. If the overloading works out I think that would be a good solution.

**Comment by kukido** [comment]
@patriknw I believe now I have enough time to finish this item, which branch I should I work from?

**Comment by ktoso** [comment]
@kukido, please work on the `master` branch for `2.4.x` features :-)

**Comment by drewhk** [comment]
Moved due next version due to various binary compat issues.

**Comment by hepin1989** [comment]
@kukido Ping:),will you take this up again?

**Comment by patriknw** [comment]
@hepin1989 @2beaucoup @kukido I looked closer at the logging with many args. We actually already have support for this, but it's not documented. You can use the method with one arg and pass in an array there, and it will be unwrapped into args. We have a test for it here: https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/java/akka/event/LoggingAdapterTest.java#L64-L72

I'll update the documentation tomorrow.

**Comment by patriknw** [comment]
It was actually documented in reference docs, but I have improved the API docs in PR https://github.com/akka/akka/pull/22386
