### ISSUE TITLE
stashing/unstashing messages in AbstractPersistentView seems broken

### ISSUE THREAD

**Issue by michaelom** [akka/akka#17896]
I am using akka 2.3.11 with lambda support.

My actor is stashing messages of type X via `stash`, scheduling a tick-message to itself and switching its message handler. Upon receiving the tick-message, my actor calls `unstashAll()` and `context().unbecome()`. I use this technique to wait for a message for a certain amount of time without blocking the actor.

UnstashAll() does exactly what it should do - it prepends all stashed messages to the actor's inbox. Unfortunately all unstashed messages are wrapped in a ReplayedMessage. I was expecting the stashed message type to be preprended to the mailbox (type X). Instead I find a ReplayedMessage.

So in order to get my stashed message I have to call ReplayedMessage.persistent().payload(). I consider this a bug.

Am I using the API in a way it is not designed for? If so, what's the right way to stash und unstash messages in an AbstractPersistentView? Please advise.

**Comment by ktoso** [comment]
Hi @michaelom,
`PersistentView` is going away, we're replacing it with a solution which uses Akka Streams (PR coming any day now). While the View will most likely still be around for a bit (deprecated though), I would not recommend building apps around it.

Having that said, thanks for the report, I think this is most likely a bug.
We have tickets for increasing the coverage of stashing tests in PersistentActor (which shares some of the ideas with PersistentView), so we may well fix it during that ticket: https://github.com/akka/akka/issues/16528

**Comment by michaelom** [comment]
Hi @ktoso 

Thank you for your quick reply.
Looking at your roadmap, PersistentView will be around for some time to come. Working around PersistentView is not really an option right now.

I assume this means no fix for 2.3.x and no fix for 2.4? Can you confirm please.

**Comment by ktoso** [comment]
Persistence changes will not be backported to 2.3, correct. It is an experimental module on 2.3 and unless critical bugs, we won't backport changes there.

**Comment by patriknw** [comment]
We can absolutely fix bugs in PersistentView in 2.4 even though it is phased out (via deprecation). Especially if you can help us track down the issue.
