### ISSUE TITLE
add sample() combinator

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17904]
An operation which "drops every n-th element", useful when for example you just want to log some progress every 1000 elements etc: broadcast to the logging stream then `sample().log()`

Another use case: I want to migrate my data from X to Y, the migration is resumable, writes are idempotent, I sometimes need to write my offset, every 100 writes or so. `sample().map(e => store(e.offset)` (also known as mini-spark)

**Comment by patriknw** [comment]
sounds like something for akka-stream-contrib
