### ISSUE TITLE
properly represent IPv6 addresses

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17911]
Currently we just grab any InetAddress from the socket and use its string representation, which may end up looking like `fe80::1:2:3:4%17` (the `%17` is the scope identifier for non-global addresses). Using this address directly within a URI will lead to interpreting the whole authority part as a blob without discerning host and port, RFC2732 specifies that IPv6 addresses must be enclosed in brackets within URIs.

Since `InetAddress.getByName` supports the bracket-enclosed syntax for literal addresses the proper fix is to mandate that `Transport.listen` must return an `Address` with a valid host part (i.e. `NettyTransport.addressFromSocketAddress` must treat IPv4 and IPv6 differently). Perhaps `Address` should guard against common problems by rejecting `host` portions that contain `:` but do not start and end with brackets.

**Comment by rkuhn** [comment]
We should also document that `akka.remote.netty.tcp.host` must follow this format.

BTW: this was noticed only on JDK8 which seems to use different means of obtaining the local host address—JDK6 returned 127.0.0.1.

**Comment by ktoso** [comment]
Sounds like something to do for `2.4.0`, right?

**Comment by ktoso** [comment]
Oh, or M3, I don't mind either way I guess, has to be done.

**Comment by patriknw** [comment]
See also https://groups.google.com/d/msg/akka-user/K9eOHzbUQ8I/1yaqYhtEAwAJ

**Comment by ktoso** [comment]
Actually not fixed, @johanandren is on it.

**Comment by johanandren** [comment]
I started on a fix, but got stuck with problems because the host name encoded in actor path and then decoded later on the remote.
