### ISSUE TITLE
Unmarshaler that returns Future[T] instead of T makes it impossible to use it

### ISSUE THREAD

**Issue by cppexpert** [akka/akka#17912]
Guys, could you please elaborate how custom unmarshaller should be written so it works ?

The fact that Unmarshaler returns Future[T] instead of T forces me to write code like this

```scala
  implicit def xmlUnmarshaller[T](implicit marsh: Unmarshaller[NodeSeq, T], mat: Materializer): FromEntityUnmarshaller[T] = {
    implicit val exec = mat.executionContext
    defaultNodeSeqUnmarshaller.map(v => {
      val future: Future[T] = Unmarshal(v).to[T]
      future.value.get.get
    })
  }
```

But it doesn't work because I have to return concrete `T`.

How should it be rewritten ?

Details:
http://stackoverflow.com/questions/31223016/why-akka-http-unmarshaler-returns-futuret-instead-of-t

**Comment by jrudolph** [comment]
There's `flatMap`, so this might work:

```scala
implicit def xmlUnmarshaller[T](implicit marsh: Unmarshaller[NodeSeq, T]): FromEntityUnmarshaller[T] = 
  defaultNodeSeqUnmarshaller.flatMap(implicit ec => xml => Unmarshal(xml).to[T])
```

The reason it needs to return a `Future` is because an entity isn't always strictly available.
