### ISSUE TITLE
Verify the Protocol marker traits make sense still in Persistence

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17918]
We introduced marker traits at some point in persistence to make it easier to know which message is internal and which not. Seems to me that they don't really relay this information nowadays, as both the below messages extend the "internal" marker, though one of them is very much user API:

```scala

  /**
   * Reply message to a successful [[WriteMessages]] request. For each contained [[PersistentRepr]] message
   * in the request, a separate reply is sent to the requestor.
   *
   * @param persistent successfully written message.
   */
  final case class WriteMessageSuccess(persistent: PersistentRepr, actorInstanceId: Int)
    extends Response // INTERNAL

  /**
   * Reply message to a failed [[DeleteMessagesTo]] request.
   */
  final case class DeleteMessagesFailure(cause: Throwable, toSequenceNr: Long)
    extends Response // THIS ACTUALLY IS USER API
```

The ticket we added those in is #16612

**Comment by ktoso** [comment]
Relates to #17518

**Comment by ktoso** [comment]
It's about moving `DeleteMessagesSuccess` and friends out of the persistence private object.

**Comment by patriknw** [comment]
@ktoso I'll take over this one, since I guess you have not started

**Comment by ktoso** [comment]
Did not touch it code-wise, nope. Thanks! https://github.com/akka/akka/issues/17918#issuecomment-128389425 mostly explains what it's about
