### ISSUE TITLE
InputStreamSource should carry its own dispatcher

### ISSUE THREAD

**Issue by jroper** [akka/akka#17928]
From a discussion with @rkuhn:

> One thing to be aware of is that the InputStreamSource should be configured to run on a dedicated dispatcher since it is of course blocking.

The problem with doing this is that you can't always control which materializer is used when the source is run.  Consider Akka HTTP, a server is a stream of HttpRequests to HttpRespones, and an HttpResponse may have a Source for the entity - Akka HTTP materialises the source, the user has no control over that, so if the user wants to serve a file by returning an `InputStreamSource`, that is going to be materialised with the same dispatcher that the rest of Akka HTTP uses.

The built in file serving directives used by Akka HTTP actually does carry a dispatcher, it does this by creating its own source:

https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0-RC4/akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala#L181

However, as the comment suggests, InputStreamSource is meant to replace that utility, but since it doesn't take its own dispatcher, it doesn't.

**Comment by jrudolph** [comment]
Akka HTTP has recently been migrated to use `InputStreamSource` in #17900 and now also uses the configured dispatcher. So, it *is* possible to choose a dispatcher but the question is if it is prominently enough enforced for the `InputStreamSource` where the normal dispatcher should usually never be used to prevent it to become a source of thread starvation issues.

**Comment by drewhk** [comment]
You can use the dispatcher attribute to use this. Once you set an attribute on a module, all of its submodules will inherit it, unless they override it themselves, see: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-composition.html#Attributes

We should document this for IO that
 - users supposed to provide a dispatcher for blocking IO based sources
 - how attributes inheritance is involved

**Comment by rkuhn** [comment]
This has been done, right @2m @ktoso?

**Comment by ktoso** [comment]
Yes, we set those:

```scala
    val inputStreamSource = name("inputStreamSource") and IODispatcher
    val outputStreamSource = name("outputStreamSource") and IODispatcher
    val outputStreamSink = name("outputStreamSink") and IODispatcher
    val inputStreamSink = name("inputStreamSink") and IODispatcher
    val fileSink = name("fileSource") and IODispatcher
```
