### ISSUE TITLE
Dispatcher aliases

### ISSUE THREAD

**Issue by jroper** [akka/akka#17929]
It should be possible to alias dispatchers.  Consider the case of a library/framework built on top of Akka.  You may have several different kinds of situations where you use dispatchers, so you might define one for example called `filesystem-io-dispatcher`, and another one called `database-io-dispatcher`.  This affords users the most power, since they can now configure both of these independently, and assign different resources to them.  But for most use cases, it's overkill to have two different dispatchers there, they should be the same for efficient resource use (that is, to limit the number of threads created).  In this case, it would be nice if Akka supported aliases for dispatchers, so I could do something like this:

```
my-blocking-dispatcher {
  ...
}
filesystem-io-dispatcher {
  type = "Alias"
  alias = "my-blocking-dispatcher"
}
database-io-dispatcher {
  type = "Alias"
  alias = "my-blocking-dispatcher"
}
```

**Comment by ktoso** [comment]
I wonder if the same can't be achieved by typesafe-config substitutions? 
Have you looked into solving this using: https://github.com/typesafehub/config#factor-out-common-values ?

**Comment by jroper** [comment]
The problem with typesafe-config substitutions is that that will result in having two different dispatchers (thread pools) with the same configuration - that doesn't solve the problem, it's not the configuration that I want to share, it's the threads.

**Comment by ktoso** [comment]
Ah I see what you mean. Marking as triaged but not sure when we'll have time to give it a shot.

**Comment by ktoso** [comment]
Second opinion from @rkuhn if available on monday would be nice.

**Comment by rkuhn** [comment]
We have solved this problem slightly differently in other locations: the library would not provide an overridable dispatcher section at a fixed location, it would instead read the dispatcher name from the configuration property. This means that users can simply point all those entries to the same name (or even to `akka.actor.default-dispatcher` if they love starvation) if they want to coalesce thread pools.

Given that this works already I’d want to avoid adding yet another possible indirection.

**Comment by jroper** [comment]
The difficulty there is that then, you can't statically refer to the dispatcher, since you need to look up from configuration what the actual dispatcher should be.

So, in Play, you can create an HTTP response from a file. Currently, all helpers to create responses are static.  So this is a static call in Play:

```scala
val result: Result = Ok.sendFile(file)
```

Underneath, we ensure the users safety by automatically using a particular dispatcher for reading the file, using this helper method:

```scala
  /**
   * Convert the given input stream callback to a Akka streams source.
   */
  def inputStreamToSource(is: () => InputStream, chunkSize: Int = InputStreamSource.DefaultChunkSize): Source[ByteString, _] = {
    InputStreamSource(is, chunkSize)
      .withAttributes(ActorAttributes.dispatcher("play.akka.blockingIoDispatcher"))
  }
```

Since these methods are all static, it is not possible to read a dispatcher name from a configuration property without relying on global state.  And we would rather not introduce a requirement to have some sort of injected result factory just to create results from it.

So there is a tension here I think caused by Akka - flows/sinks/sources carry a fixed reference to the name of a dispatcher, however, there are cases where dispatcher references need to be dynamic.  So, to fulfil that requirement, either dispatcher names need to be dynamic by supporting dispatcher aliases, or maybe the dispatcher name carried by the flow needs to be dynamic, essentially supporting aliases at the flow level.

**Comment by jrudolph** [comment]
Arguably this kind of configuration should be supplied by the materializer which also supplies all other kind of runtime details. So, maybe it would make sense to allow some kind of indirection that allows to specify a dispatcher (or maybe even other (arbitrary?) attributes) by "symbol" and then configure the materializer with actual settings for all the symbols possibly requested by stream components.

(On the other hand, I find it quite remarkable that you can create responses statically without any context in play.)

**Comment by jroper** [comment]
The current structure of a Play response:

```scala
Result(
  header: ResponseHeader(
    status: Int,
    headers: Map[String, String]
  ),
  body: Enumerator[Array[Byte]]
)
```

What would context be needed for?

**Comment by rkuhn** [comment]
The ability to enumerate the bytes for the response in a non-blocking fashion will always require resource allocation. If you don’t want to make resources globally available then context is needed, independent of Akka Streams.

**Comment by jrudolph** [comment]
@jroper yes, that's simple enough. I agree just for creating a response it would be nice not having to supply a context. In akka-http routing the lines are a blurred between creating a response and transforming it. For many transformations, we need at least some settings from the context. Then, there's marshalling which happens before creating the actual response and which needs an ExecutionContext for asynchronous execution.

**Comment by jroper** [comment]
@rkuhn yes, but the question is which context? For example, end user code may decide to send a resource from the classpath. They use the classloader of their own class - and they can do that safely because they know that the resource is in the same jar as their class.  Or, they may send a file, which has a path to look the file up from injected. But this is additional context on top of that - and the question is, is injecting some additional context into their controllers for the sake of this worth it?  Especially when the context that is needed is not the resource itself, if it was the resource itself, then that would be different, but when it's nothing more than a logical name for the resource, requiring that to be injected, rather than supporting aliasing, feels too much to me.  We want to avoid, in Play, having either a list of 100 dependencies to inject just to serve hello world, or the other extreme, inject a god context object.  Akka tends to favour the god context object, that being the ActorSystem.  In an actor focussed world where everything is an actor, that's ok.  In a world where everything is just plain old objects, god objects are very bad.  So, the less context needed, the better.

**Comment by rkuhn** [comment]
No, the resource that is needed (and that we were discussing) is a thread pool, plain and simple. That needs to come from somewhere, so if you want your method that creates that response to be static then you’ll need to use a global thread pool. Again quite simple.

Since we seem to be talking past each other I wonder what it is that I am missing?

**Comment by jroper** [comment]
I'd be happy with passing a thread pool. Though, `InputStreamSource` doesn't allow passing a thread pool, it only lets passing the name of a thread pool, see #17928.

**Comment by patriknw** [comment]
Interesting discussion, the dispatcher alias would be rather easy to implement.

**Comment by rkuhn** [comment]
I’m still having doubts about the net value of supporting dispatcher aliases generically within the configuration layer, that might be a can of worms plus an opportunity to create a configuration management nightmare at the user’s end. Re-reading the whole thread now I see that Johannes probably nailed it when saying that the Materializer should more flexibly interpret the dispatcher names when turning a Graph into Actors. This could be a simple `Map[String, String]` that can be used to map different flow pieces onto the same dispatcher, and if no mapping is present then we just use the name as a config key directly (as we do now).

WDYT?

**Comment by patriknw** [comment]
I agree that it would great if the Materializer would carry such thing. I thought James didn't only talk about Akka Streams.

**Comment by rkuhn** [comment]
Graphs are the only resource-relevant things that users can create outside of an ActorSystem in the Akka universe now, which leads to the difficulty described at the top of this thread. I’d say that whatever mechanism brings an object from outside an ActorSystem inside of it shall be responsibly for doing this resource mapping.

**Comment by patriknw** [comment]
I see, makes sense.

**Comment by patriknw** [comment]
Then I move this to streams.
cc @drewhk

**Comment by patriknw** [comment]
done
