### ISSUE TITLE
Streams: constructor parameter initialBuffer is not used in SynchronousFilePublisher

### ISSUE THREAD

**Issue by agolubev** [akka/akka#17922]
it's internal API though

**Comment by drewhk** [comment]
initialBuffer is not used at this point, only the maximum. We planned to have dynamic buffer sizing, and this was supposed to control it. We will revisit that at some point, but currently it is unused.

**Comment by agolubev** [comment]
I see. Should some comment be added to publisher just to clarify this in place?

**Comment by rkuhn** [comment]
We should clean up these attributes overall: there should be only a single `bufferSize` that is used, because that is what we currently do. Later we can expand.

**Comment by rkuhn** [comment]
now that we have entered binary compatibility land my conclusion is the opposite: don’t touch things!

**Comment by agolubev** [comment]
:)
