### ISSUE TITLE
Confusing documentation for formFields directive

### ISSUE THREAD

**Issue by notxcain** [akka/akka#17938]
It is not clear from [the documentation](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC4/scala/http/routing-dsl/directives/form-field-directives/formFields.html#formfields): 
1. If it can extract `FormFields` from non-POST requests 
2. If it requires addition of `post {}` to work properly

**Comment by ktoso** [comment]
Thanks for reporting and the discussion on gitter @notxcain!

**Comment by ktoso** [comment]
// cc @sirthias @jrudolph 

Useful snippet from the discussion we had on gitter:

```
I’ve found a snippet that confused me http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC4/scala/http/routing-dsl/directives/form-field-directives/formFields.html#formfields

 val route =
  formFields('color, 'age.as[Int]) { (color, age) =>
    complete(s"The color is '$color' and the age ten years ago was ${age - 10}")
  }

Post("/", FormData("color" -> "blue", "age" -> "68")) ~> route ~> check {
  responseAs[String] shouldEqual "The color is 'blue' and the age ten years ago was 58”
}

So I assumed that formFields expects POST by default.
```

**Comment by jrudolph** [comment]
I agree this should be clarified in the documentation. `formFields` is orthogonal to the HTTP method used.

**Comment by sirthias** [comment]
Well, actually all directives are orthogonal to the HTTP methods, except for the method directives and the `getFromXXX` directives. I don't know why the user assumed that `formFields` expects POST by default. There doesn't appear to be anything hinting towards that.

**Comment by jrudolph** [comment]
I agree for the test but the description of `formFields` in the documentation has this description:

> Extracts fields from POST requests generated by HTML forms.

**Comment by sirthias** [comment]
Ah, yes. There is the basis for the assumption. Makes sense.
I agree, this needs to be fixed.

**Comment by jrudolph** [comment]
The `formFields` documentation also needs an update to the new unmarshalling infrastructure and some infos about `StrictForm`.

**Comment by ktoso** [comment]
This was documented more in the https://github.com/akka/akka/issues/18684 PR, it's now fixed IMO.
