### ISSUE TITLE
AkkaStreams: create test to verify that Java API does not have scala classes

### ISSUE THREAD

**Issue by agolubev** [akka/akka#17946]
Actually it will return for Flow, Sink and Source something like:
* akka.stream.javadsl.Source$.elements(scala.collection.Seq) has parameter type from scala: scala.collection.Seq 
* akka.stream.javadsl.Source$.from(scala.concurrent.duration.FiniteDuration,scala.concurrent.duration.FiniteDuration,java.lang.Object) has parameter type from scala: scala.concurrent.duration.FiniteDuration 
* akka.stream.javadsl.Source$.from(scala.concurrent.duration.FiniteDuration,scala.concurrent.duration.FiniteDuration,java.lang.Object) has parameter type from scala: scala.concurrent.duration.FiniteDuration 
* akka.stream.javadsl.Source$.from(scala.concurrent.Future) has parameter type from scala: scala.concurrent.Future 
* akka.stream.javadsl.Sink$.foreachParallel(int,akka.japi.function.Procedure,scala.concurrent.ExecutionContext) has parameter type from scala: scala.concurrent.ExecutionContext

**Comment by ktoso** [comment]
From the above list only `elements` is wrong, we do need `FiniteDuration` as well as scala's `Future` currently. And elements is tracked in another ticket: https://github.com/akka/akka/issues/17923

Doing the full-in jump involves quite some pain so we need to think about it intensely and decide when/how. Here's the ticket about making japi use all the java8 things: https://github.com/akka/akka/issues/16247

(for example java Duration does not have "infinite")

**Comment by ktoso** [comment]
So while I think it's a great idea, it doesn't really apply just yet.

**Comment by ktoso** [comment]
I made a link to this ticket from the grouped java8 ticket, and closing this for now. Thanks for the idea in general though!
