### ISSUE TITLE
PersistentFsmActor persists StateChangeEvent on stay - intended behavior?

### ISSUE THREAD

**Issue by bardurdam** [akka/akka#17959]
I've noticed that `PersistentFsmActor` persists `StateChangeEvent` even when the state does not change. Is this intended behavior?

I am aware that `FSM` changes state for every message is processed, handled or not. And that `stay` actually means `goto(currentState)`.

I guess that redundant persistence of `StateChangeEvent`s can be avoided by making `def applyState(nextState: State)` in `PersistentFsmActor` only append the `StateChangeEvent` when the state actually changed. This might be accomplished by by comparing `nextState` with `currentState`, if `currentState`was made accessible or possibly by comparing `stateName` with that of `nextState.stateName`. 
I'm not sure how to take timeouts into account without `currentState` being accessible from `PersistentFsmActor`.

The example below produces the following events:
```scala
IncreaseCount
StateChangeEvent("Open", None)
StateChangeEvent("Open", None)
StateChangeEvent("Open", None)
StateChangeEvent("Open", None)
```

Example:

```scala
object Demo extends App {
  val system = ActorSystem("demo")
  val door = system.actorOf(Props(new PersistentDoorFsm()))

  door ! OpenDoor
  door ! OpenDoor
  door ! "foo"
  door ! "bar"
}

object PersistentDoorFsm {

  sealed trait State extends FSMState

  case object Open extends State {
    def identifier: String = "Open"
  }
  case object Closed extends State {
    def identifier: String = "Closed"
  }

  sealed trait Data
  case class Count(int: Int) extends Data

  sealed trait Evt
  case object IncreaseCount extends Evt

  case object OpenDoor
  case object CloseDoor
}

class PersistentDoorFsm(implicit val domainEventClassTag: ClassTag[Evt])
  extends PersistentFsmActor[State,Data,Evt] {

  def persistenceId: String = "door-fsm-stream"

  startWith(Closed, Count(0))

  when(Closed) {
    case Event(OpenDoor, _)  ⇒ 
      goto(Open) applying IncreaseCount
  }

  when(Open) {
    case Event(CloseDoor, _) ⇒ 
      goto(Closed) applying IncreaseCount
  }

  // unhandled will call stay

  def applyEvent(domainEvent: Evt, currentData: Data): Data = {
    (domainEvent, currentData) match {
      case (IncreaseCount, Count(cnt)) ⇒ Count(cnt+1)
      case _                           ⇒ currentData
    }
  }
}
```

**Comment by bardurdam** [comment]
//cc @leonidb

**Comment by ktoso** [comment]
Good catch @bardurdam! 
I think you're right that stay should not emit a change state event.

I'm not yet quite sure if we never want to store such event, maybe it could be used as "how many times I was pinged" in an event-sourced manner... 

Since https://github.com/akka/akka/pull/15561 `stay()` is not exaclty the same as `goto(same)`, since it does not invoke the transition handler (the reason being that the "intent is different"). When I go, I want to actually "go" (even to the same state), and when I stay I really want to do nothing. I think this thinking could be extended to here - if we stay we don't store an event, and if we goto we do. 

Sounds like an feasible idea?

**Comment by ktoso** [comment]
PS: Help on this would be much appreciated, I think it's a reasonably sized ticket to pick up by the community and we'd definitely need a helping hand to ship 2.4 as soon as we can :-)

**Comment by leonidb** [comment]
@ktoso
I can take this one.

**Comment by ktoso** [comment]
Super! Thanks for staying engaged with this one, it has loads of potential
:-)

On Fri, Jul 10, 2015 at 1:34 AM, leonidb <notifications@github.com> wrote:

> @ktoso <https://github.com/ktoso>
> I can take this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/17959#issuecomment-120174450>.
>



-- 
Cheers,
Konrad 'ktoso' Malawski
Akka <http://akka.io/> @ Typesafe <http://typesafe.com/>

**Comment by leonidb** [comment]
@ktoso
Sure, happy to see a real user feedback :)

**Comment by Akii** [comment]
Why emit a change state event at all? State is something that should be completely derived from (domain) events, not through "pseudo" events injected from Akka.

One aspect to think about is migration, both code and event. You'd have to migrate state change events away if they don't fit in anymore.

Does Akka internally need those events? If so, why?
