### ISSUE TITLE
Create a variant of `Sink.actorRef` that uses simple acking for backpressure

### ISSUE THREAD

**Issue by fommil** [akka/akka#17967]
The complement of #17610 to ease migration paths without having to go full-on `ActorSubscriber` / `ActorPublisher`.

It would be good to have a way of creating a `Sink` from an existing `actor: ActorRef` that will only send a message to the underlying `actor` when it receives an `Ack` from that actor.

This will require some initial "Subscribe" message from streams to the actor, with an `Ack` response. All failure cases should just result in a `PoisonPill` (or whatever `Sink.actorRef` currently does).

If the user's actor sends a message without an `Ack`, fail... it's an illegal state.

**Comment by rkuhn** [comment]
ping @drewhk

**Comment by agolubev** [comment]
@drewhk, I can take this.
Please let me know if all in ticket description make sense and making something similar to ActorRefSink is a right direction for implementation.

**Comment by rkuhn** [comment]
fixed in #18773
