### ISSUE TITLE
Add support for automatic pinging in WebSocket server implementation with configurable rate

### ISSUE THREAD

**Issue by fommil** [akka/akka#17968]
@jrudolph I just realised there doesn't appear to be a way to specify the ping rate from the server to the client. This is not something that the application level code should be concerned with.

It's actually a really big pain in the wandoulabs implementation because even if the user's code uses proper backpressure, then protocol layer `Ping`/`Pong`s can still blow up the network stack and that means a lot more error handling is required a lot higher up the stack than desirable. I worked around this in https://github.com/smootoo/simple-spray-websockets/commit/17ea453cf453af522255206cd971835fa897293d (note that we forked wandoulabs, because it seems to be a zombie project)

**Comment by jrudolph** [comment]
Automatic server-side ping is not mandatory in the spec and it's not implemented so far.

In any case, just setting the rate would always help for one specific networking setup. The only robust solution is providing backpressure throughout the whole processing chain. For Websocket this means that there needs to be some frame sending management that organizes how data from these three sources should be sequenced and backpressured:

 * outgoing user data
 * auto-generated PINGs (maybe only on idle connections?)
 * PONG answers in response to peer PINGs

User-data will be back-pressured through the existing streaming API, PONG answers will effectively start to backpressure the incoming side, and auto-generated PING could theoretically be dropped if there's backpressure from the network.

**Comment by jrudolph** [comment]
So, for the user-code the rule is that it needs to support the backpressure from the streams API. 

Relying on the rest of the stack (server-side websocket, server-side networking configuration and implementation, network, peer-side networking configuration and implementation, peer-side websocket implementation, peer-side application) to provide any guarantees on being backpressure-free will always be brittle. Even if things seems to work in the good cases (localhost, big enough buffers, good enough network, etc.) it will fail rarely and unexpectedly under load.

**Comment by ktoso** [comment]
Doesn't sound like we have a clear idea how to solve this yet, such that PINGs don't starve the actual user-code etc... right?

Marking as 1.x for now.

**Comment by ktoso** [comment]
Doesn't sound like we have a clear idea how to solve this yet, such that PINGs don't starve the actual user-code etc... right?

Marking as 1.x for now // cc @rkuhn @sirthias @jrudolph

**Comment by drewhk** [comment]
It is simple to do with a GraphStage. I planned to have an "idle-inject" stage which is the counterpart of the "idle-timeout" stage.

**Comment by ktoso** [comment]
We nowadays have keepAlive, we can investigate how to apply it here perhaps.

**Comment by ktoso** [comment]
Auto ping also requested by people from Play community BTW https://github.com/akka/akka/issues/18126#issuecomment-129270050

**Comment by ianclegg** [comment]
Some kind of support for ping/pong frames in Akka Http would be nice - at the moment we have to handle this much higher up at the application level with ping binary messages and our own sequence numbers. It certainly requires some careful thought, but it would be useful to have. :+1:

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
