### ISSUE TITLE
WebSockets should use standard marshallers via TextMessage

### ISSUE THREAD

**Issue by fommil** [akka/akka#17969]
When using the new `handleWebsocketMessages` it is probably pretty reasonable to expect that the same marshallers will be used here as in the REST API (and at least the user could provide an implicit `ToResponseMarshallable` in the scope). However, `handleWebsocketMessages` expects a `Flow[Message, Message, _]` which demands that users manually implement the marshalling. 

This results in this level of boilerplate:

```scala
        val flow = Flow[Message].collect {
          case TextMessage.Strict(msg) =>
            msg.parseJson.convertTo[RpcRequestEnvelope]
          // ignores everything else
        }.via(Flow.wrap(sink, source)((_, _) => ())).map {
          case e: RpcResponseEnvelope =>
            TextMessage.Strict(e.toJson.prettyPrint): Message
        }
```

**Comment by ktoso** [comment]
Agree that we should the marshalling infra work well with WS.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
