### ISSUE TITLE
Improve error message when Http response has missing `phrase`

### ISSUE THREAD

**Issue by nechaevv** [akka/akka#17971]
Some web APIs omits HTTP reason phrase after status code, i.e. `HTTP/1.1 200\n` instead of `HTTP/1.1 200 OK\n`. In this case, HttpResponseParser fails with "Illegal response status code" error.

**Comment by 2beaucoup** [comment]
The space after the status code is mandatory. From http://tools.ietf.org/html/rfc7230#section-3.1.2:

```
The first line of a response message is the status-line, consisting
of the protocol version, a space (SP), the status code, another
space, a possibly empty textual phrase describing the status code,
and ending with CRLF.

  status-line = HTTP-version SP status-code SP reason-phrase CRLF
```

**Comment by nechaevv** [comment]
Yes, but, in fact, not all API implementers strictly follow this spec, and only Akka HTTP fails when last space is omitted with reason phrase.

**Comment by jrudolph** [comment]
@nechaevv it would certainly be possible to be a bit more lenient. However, every such change makes the code a tiny bit more complicated, so we usually need some evidence that this is a problem that affects enough people (e.g. de-facto standard because some popular server implements it like this) to warrant a change. This seems to be the first time this is reported for spray or akka, so I'd currently vote against changing it. Have you tried contacting the server operator?

**Comment by nechaevv** [comment]
Yes, i'm talking with their support about this problem, hope they'll fix their API implementation.

**Comment by 2beaucoup** [comment]
https://github.com/2beaucoup/akka/commit/81d974cc7e7fb69d57474d58627e72a074302a87 has the necessary changes.

**Comment by ktoso** [comment]
I agree with @jrudolph that we should be cautious when relaxing the parser like this, to not end up in death-by-thousand-small-deviations-from-the-spec ;)

I wonder how this specific API vendor reacted - @nechaevv did they fix their APIs?

Let's keep this ticket open, and collect feedback if more APIs do the wrong thing.

**Comment by ktoso** [comment]
Oh, and thanks @2beaucoup for providing the commit! We'll see if we can use it...

**Comment by nechaevv** [comment]
@ktoso This vendor fixed their API after bug report. I think that it will be more convenient to improve error report - i spent a lot of time debugging it.

**Comment by ktoso** [comment]
Sounds like something we could look at - as long as it wouldn't hurt performance.
Keeping triaged in 1.x

**Comment by 2beaucoup** [comment]
The patch contains fixes for the case of a missing reason phrase (allowed by the spec) and missing whitespace (not allowed) and can be easily modified to still fail for the latter.

Shouldn't be too hard to improve the error msg.

**Comment by ktoso** [comment]
That'd be a great contrib @2beaucoup, thanks!

**Comment by 2beaucoup** [comment]
I've pushed an update.

**Comment by ktoso** [comment]
This was solved but ticket wasn't closed, closing
