### ISSUE TITLE
Memory leak when running Akka on Tomcat

### ISSUE THREAD

**Issue by pkubowicz** [akka/akka#17978]
To reproduce:
1. write a Servlet-based webapp using Akka ([minimal example](https://github.com/pkubowicz/akka-tomcat-leak))
2. start Tomcat with the webapp
3. connect `jvisualvm` to the Tomcat instance
3. redeploy the webapp several times (for example, visit http://localhost:8080/manager and use the 'Reload' button)

Bug: PermGen (Java 7) or Meta space (Java 8) increases with every redeploy.
Without Akka, redeploying does cause more memory to be used for class loading.

Environment:
- Akka 2.3.12
- Oracle's Java 1.8.0_45-b14 and 1.7.0_80-b15 64-bit
- Tomcat 8.0.24

Related discussion: [ThreadLocal not being cleaned up? on akka-user](https://groups.google.com/forum/#!topic/akka-user/v4JXZtJYl_U) ended up with saying "Either this is a false alert by Tomcat, or there is a bug in the ForkJoinPool ". Well, it seems at least the first part of this sentence is not true, as redeploying causes Tomcat to show warning:

    13-Jul-2015 13:27:39.186 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7ce4ee5e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter] (value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@556fefbd]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    13-Jul-2015 13:27:39.187 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7ce4ee5e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter] (value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@ea27d50]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    13-Jul-2015 13:27:39.188 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [scala.concurrent.forkjoin.ThreadLocalRandom$1] (value [scala.concurrent.forkjoin.ThreadLocalRandom$1@5125fc4a]) and a value of type [scala.concurrent.forkjoin.ThreadLocalRandom] (value [scala.concurrent.forkjoin.ThreadLocalRandom@41196a29]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

and you can see in the heap dump that the nearest GC root for non-GC-collected WebappClassLoader is either an instance of ForkJoinPool$Submitter or ThreadLocalRandom.

**Comment by ktoso** [comment]
Thanks for reporting, we'll investigate soon

**Comment by viktorklang** [comment]
@ktoso Even better—anyone is free to investigate whenever they want!

**Comment by ktoso** [comment]
True, we'd definitely need some more eyes/hands :-)

**Comment by patriknw** [comment]
I tried your sample application in tomcat 9.0.0.M4. I have verified that Akka threads are stopped after redeploy and meta space is growing and then shrinking. I can't see that this is an Akka bug.
