### ISSUE TITLE
publish scaladocs to maven

### ISSUE THREAD

**Issue by fommil** [akka/akka#17970]
As requested / discussed here https://groups.google.com/d/msg/akka-user/l06DPhv1WT4/0NizXBRu4TkJ

**Comment by ktoso** [comment]
Summary:
- we publish gen-javadoc generated javadocs in the `-javadoc` jar (this is cool / nice)
- ensime expects scaladocs in `-javadoc`
- maybe we can publish `-scaladoc` as well.

**Comment by fommil** [comment]
@ktoso ENSIME can handle javadocs just fine. But they are javadocs, it would be nice to have the scaladocs there --- if not just for the fact that there are a lot of rendering bugs in the javadocs.

**Comment by ktoso** [comment]
Oh, so I misunderstood the problem slightly - thanks for correcting. 
On our end it doesn't change the question - if / how / where should we publish scaladoc artifacts.

**Comment by patriknw** [comment]
Other opinions here would be useful.

-javadoc is "standard" for Java IDEs I guess, so using that for scaladoc where we have javadoc would make it worse for our Java users.

On the other hand current -javadoc makes the experience for Scala users not optimal.

Can other Scala IDEs pick up -scaladoc files if we would be able to publish that?

**Comment by fommil** [comment]
I believe javadocs in hardcoded into most places, including SBT. It would actually be really easy for us the handle this in ensime-sbt but not sure about other build tools and ides. Maybe check with Eugene and Josh?

**Comment by MasseGuillaume** [comment]
Another advantage of publishing scaladoc would be to have scaladoc available at javadoc.io

https://www.javadoc.io/doc/com.typesafe.akka/akka-http-experimental_2.11/2.4.4
