### ISSUE TITLE
http: Multipart parser fails on files with non-ASCII names

### ISSUE THREAD

**Issue by stanch** [akka/akka#17973]
Non-ASCII strikes back! Here’s the entity I’m getting when uploading a file with a Cyrillic name through a form (I decoded it with `ctx.request.entity.dataBytes.runFold("")(_ + _.decodeString("UTF-8")).foreach(println)`):

```
------WebKitFormBoundaryQ4eUWGu4eNQx0Riq
Content-Disposition: form-data; name="file-field"; filename="тест.txt"
Content-Type: application/octet-stream


------WebKitFormBoundaryQ4eUWGu4eNQx0Riq
Content-Disposition: form-data; name="other-field"


------WebKitFormBoundaryQ4eUWGu4eNQx0Riq--
```

And here is the server response when I try to parse `entity(as[FormData])`:

```
The request content was malformed:
multipart/form-data part must contain `Content-Disposition` header with `name` parameter
```

Given that the filename decodes correctly in UTF-8, the browser (Chrome) does not seem to follow [RFC 2231](http://tools.ietf.org/html/rfc2231), right? It should either send ASCII or encode it as `filename*=utf8''...`.

So assuming I’m understanding the issue correctly, the questions are:
1) Does akka-http support RFC 2231? If not, should it?
2) If the browser chooses to ignore it, can akka-http be less pessimistic and try to decode in UTF-8?

**Comment by stanch** [comment]
So it seems that I was too optimistic about this issue and in fact no one implements it correctly on either side: http://greenbytes.de/tech/tc2231/. Another useful piece of information is [Appendix D of RFC 6266](https://tools.ietf.org/html/rfc6266#appendix-D).

**Comment by 2beaucoup** [comment]
Duplicate of https://github.com/akka/akka/issues/16821?

**Comment by stanch** [comment]
@2beaucoup Yes, I think so.

**Comment by jrudolph** [comment]
@stanch in any case thanks for the additional links. Very helpful.

**Comment by 2beaucoup** [comment]
Yeah, nice links @stanch! An equivalent overview for upload behaviour would be nice.

**Comment by jrudolph** [comment]
Yes, agreed, upload behavior may differ because HTTP headers and MIME headers are covered by different RFCs (at least in theory).

**Comment by stanch** [comment]
I think one good step forward would be to parse the filename in some way (however mangled), rather than just reject the request entirely.

**Comment by jrudolph** [comment]
Is it currently rejected? If yes, that's actually a bug. The header should either be provided as a `RawHeader` or if that's not possible at least the complete request entity should be available in some form (which may be hard to achieve due to streaming).

**Comment by stanch** [comment]
It’s rejected upon `entity(as[FormData])`, as I mentioned in the issue. The rejection text is as follows:
```
The request content was malformed:
multipart/form-data part must contain `Content-Disposition` header with `name` parameter
```
Should we reopen this then?

**Comment by jrudolph** [comment]
I'm not sure if this could be fixed easily which would entail that we somehow parse only part of the `Content-Disposition` header.

What I meant is that you should still be able to access the data as `Multipart.BodyPart.Strict` and access the `RawHeader` manually to decide what to do. 

It would be better, though, if we could fix it well enough so that it works with major browsers and charset settings.

**Comment by stanch** [comment]
> What I meant is that you should still be able to access the data as `Multipart.BodyPart.Strict` and access the `RawHeader` manually to decide what to do.

For that the entity would still have to be parsed as `Multipart.FormData`, right?

From there the result depends on whether the `name*` and/or `filename*` fields are present. If they are, they should be decoded per *RFC 2231*, and the ASCII versions should be disregarded (but still be accessible from the raw headers). If no, then perhaps the non-asterisk versions should be available as byte buffers, so that the user can decode them as they wish.
