### ISSUE TITLE
Provide guide for migration from spray to akka-http

### ISSUE THREAD

**Issue by fommil** [akka/akka#17972]
Unfortunately, the following is just a `TODO`: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC4/scala/http/migration-from-spray.html

This should definitely be a prerequisite for the akka-http 1.0 release.

I'm not sure if you track this independently. It's good to have a ticket for this so that I can at least be notified of updates.

FYI, I'm currently fumbling in the dark to get `ensime-server` to use `akka-http` (I've used spray for years) because we'd like to use the WebSocket support. Use us as guinea pigs, as input from you helps us as well.

**Comment by jrudolph** [comment]
@fommil yes, thanks for the reminder. Would you mind posting a few bullet points of items that you stumbled over? We have many answers but it's often hard to come up with the right questions to be answered.

**Comment by fommil** [comment]
I think I have everything working now, but probably the biggest problem was working out which implicits I needed in scope. All the simple examples conveniently had all the correct implicits in scope (e.g. converting `Route => Flow[HttpRequest, HttpResponse]`). Importing `Directives` instead of extending the trait, no such thing as `HttpService` anymore. Still to do my testing, so that might bring up some new things.

**Comment by kcberg** [comment]
+1 I'll add my findings here as I convert from spray to akka-http.

**Comment by ktoso** [comment]
Thanks, that's much appreciated @kcberg!

**Comment by drewhk** [comment]
@kcberg do you have something to share already? All inputs are very welcome!

**Comment by monkeygroover** [comment]
I used to be able to use the Actor props as a form of dependency injection when instantiating the Actor that runs the route. The current examples i've seen just have trait Foo extends Directives.  if you try to use a class, you then struggle adding (implicit system: ActorSystem, materializer: Materializer)  etc etc.  An example of how to nicely structure routes and directives that need to be parameterised on instantiation would be nice.

**Comment by mutazmq** [comment]
Hi
I'm struggling to get this working, can you please advise?

  def perRequestActor(message: RestMessage): Route = {
    ctx: RequestContext => system.actorOf(propsCreator(ctx, message), "per-req-actor")
  }
 
 val route: Route = 
  get {
    perQuotationRequestActor(new RestMessage("someVal"))
  }

**Comment by ktoso** [comment]
A great post by Zalando was published, https://tech.zalando.de/blog/migrating-spray-akka-http/ some of the points we should directly include in our guide

**Comment by meln1k** [comment]
Hi @ktoso 
I created a PR for this issue: https://github.com/akka/akka/pull/20511

**Comment by ktoso** [comment]
Initial guide was provided actually. Let's close this and improve on-demand,

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
