### ISSUE TITLE
Provide the ability to create a ContentType from a String

### ISSUE THREAD

**Issue by jroper** [akka/akka#17982]
The `ContentType` companion object should provide a `parse` object, in a similar fashion to `MediaType`, to make it simple to create content types from Strings.

Consider a situation where you're integrating with a third party library, let's say some sort of file repository, and for each file, it includes a content type property as a String, and you want to serve these files using Akka HTTP.  Akka HTTP, as far as I can see, provides no means to create a `ContentType` from a String, you can create a `ContentType` from a `MediaType` and a `HttpCharset`, and both of these can be parsed from strings, but using that would first require parsing the value to extract both the media type and the charset out, if it exists.  The only way I can see to do this is via a round about method of mocking a header map, parsing it, then trying to get the content type header from that parsed map.

**Comment by jrudolph** [comment]
There's currently this:

```scala
scala> import akka.http.scaladsl.model.MediaTypes
import akka.http.scaladsl.model.MediaTypes

scala> MediaTypes.getForKey(("application", "gnutar"))
res1: Option[akka.http.scaladsl.model.MediaType] = Some(application/gnutar)
```

but I agree adding a properly documented method that would parse from a complete string would be nice as well.

**Comment by jrudolph** [comment]
Ah, you mean you want to parse from a complete ContentType = MediaType + Charset string?

**Comment by jrudolph** [comment]
PR in #17983.

**Comment by jrudolph** [comment]
Merged.
