### ISSUE TITLE
(2.4) Actor discarding messages sent to its hostname:port, indicates the message is being dropped because it doesn't conform to hostname:bindport

### ISSUE THREAD

**Issue by benjaminabbitt** [akka/akka#17981]
After configuring bind-hostname and bind-port in application.conf, as specified by the Akka FAQ, and bringing up the cluster, I'm receiving an error:

    [ERROR] [07/09/2015 19:54:24.132] [default-akka.remote.default-remote-dispatcher-20] [akka.tcp://default@54.175.105.30:2552/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fdefault%4054.175.105.30%3A2552-757/endpointWriter] dropping message [class akka.actor.ActorSelectionMessage] for non-local recipient [Actor[akka.tcp://default@54.175.105.30:32810/]] arriving at [akka.tcp://default@54.175.105.30:32810] inbound addresses are [akka.tcp://default@54.175.105.30:2552]
What this seems to say is that the actor has received a message destined for port 32810 (the external port) but its dropping it because the internal port (2552) doesn't match.

The relevant portions of the file are:

    hostname = 54.175.105.30
    port = 32810

    bind-hostname = 172.17.0.44
    bind-port = 2552

I've tried this on 2.4-M1, 2.4-M2, and 2.4-SNAPSHOT, all with the same effect.

[Stackoverflow link](http://stackoverflow.com/questions/31326690/akka-cluster-with-bind-port-and-bind-hostname)

**Comment by 2m** [comment]
I have posted an answer to SO thread. My main question would be, have you configured address translation from `54.175.105.30:32810` to `172.17.0.44:2552` in your network configuration?

**Comment by benjaminabbitt** [comment]
This was a mistake in my code.   I had some boilerplate overriding the bind-port.

Sorry for the erroneous bug report.

**Comment by ktoso** [comment]
No problem at all - glad you figured it out!
Happy hakking!
