### ISSUE TITLE
unclear streams testing / testkit docs

### ISSUE THREAD

**Issue by fommil** [akka/akka#17993]
In the streams testing section http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC4/scala/stream-testkit.html is the suggestion to use `TeskKit` and `pipeTo`. Thanks to https://issues.scala-lang.org/browse/SI-8673 this is a particularly difficult setup to get right, so I encourage adding the following implicit imports to the section:

```scala
  import system.dispatcher
  import akka.pattern.pipe
```

**Comment by ktoso** [comment]
Sure, makes sense; would love a PRs with this such things, would help us a lot.
I'll hope to get to it for the 1.0 though

**Comment by fommil** [comment]
yeah, I keep getting hassled about the CLA everytime I raise a PR :smile:

**Comment by ktoso** [comment]
As do Apache and other projects as well :wink: 
I fixed it -> https://github.com/ktoso/akka/commit/c030bd2bb1af01127566382be38c3ae809fc94a8

Now on to releasing that fella

**Comment by fommil** [comment]
That's not true, I contribute to spark and don't get asked for trivial things like documentation. And that's beside the point: Typesafe have set a precedent of closing down sources, so I refuse to sign their assignment. I'd be happy to do so for other organisations that have my trust.
