### ISSUE TITLE
WebSockets represented as a BidiFlow not a Flow

### ISSUE THREAD

**Issue by fommil** [akka/akka#18008]
This describes WebSockets far better than Flow:

http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/java/stream-graphs.html#Bidirectional_Flows

Can we please have a change in the WebSockets API to be a BidiFlow instead of a Flow? @jrudolph 

Incidentally, this would really help with the marshalling because Out1/In2 are both in the user's domain model whereas Out2/In1 are both `Message`.

**Comment by rkuhn** [comment]
How could a WebSocket be a BidiFlow? It represents a single TCP connection, which means that it has exactly one input and exactly one output—hence it is topologically a Flow. There must be a misunderstanding at work here, could you please elaborate?

**Comment by fommil** [comment]
@rkuhn there is one input and one output on the client side, but there is also one input and one output (potentially independent) on the server side. WebSockets are actually more like TWO flows, not one. It is not typically used as a request/response protocol, which is what `Flow` is modelling.

Classic example of Websockets: a stock market ticker push, with client requests to add/remove subscriptions. This is also similar to how ENSIME behaves, and I can say with experience that hacking `Flow` to behave as independent source/sink on the server side was a real pain.

**Comment by fommil** [comment]
@rkuhn FYI, this is how we hacked it to work https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/server/WebSocketBoilerplate.scala

**Comment by rkuhn** [comment]
Please take a step back and consider that the client needs its own representation of the end of the bidirectional WebSocket as well as the server does—this is in no way representable as a BidiFlow, though, because two openings are at the client machine and two of them are on the server machine. For each of these participants it looks like only one input and one output, nothing more. So, this ticket is clearly invalid.

What you show in your (needlessly emotionally commented) code example is just that you may of course want to represent the JSON (un)marshalling stage as a BidiFlow to be plugged between the real WebSocket `ws` (which indeed is a Flow) and the application code `app` (which again is a Flow—even if the reading and writing ports do not communicate, that is not mandated for Flows at all). Code:
~~~scala
val json = BidiFlow.wrap(
    Flow[Outgoing].map(o => TextMessage.Strict(o.toJson.toString(printer))),
    Flow[Message].collect { case TextMessage.String(m) => m.parseJson.convertTo[Incoming] }
  )
...
app.join(json).join(ws).run()
~~~
(no crazy boilerplate needed)

**Comment by fommil** [comment]
Yes, the separation of the marshalling is exactly the benefit of exposing this as a `BidiFlow`. Surely that is more fitting with the `routing` approach taken elsewhere such that an implicit marshaller takes care of user
domain <=> `TextMessage` mappings in much the same was as the `ToMarshallable` stuff works for `HttpRequest` / `HttpResponse`.

The comments are addressed to the members of the ensime team, to whom this file **is** a crazy amount of indecipherable boilerplate. Feel free to skip those words and move on.

You can find a corresponding test for the file in https://github.com/ensime/ensime-server/blob/master/server/src/test/scala/org/ensime/server/WebSocketBoilerplateSpec.scala which also shows that if the endpoint were a `BidiFlow` then the testing would be significantly easier.

**Comment by rkuhn** [comment]
I showed you how to properly use a BidiFlow to factor out the marshalling stage, beyond that there is nothing about WebSockets that lends itself to this treatment. If you still are convinced that I am missing something then please be very explicit and write down the API method signatures that you want to see changed to BidiFlow (if you do this then you’ll really have to write them down here—saying “just change all” does not achieve the same effect, the onus is on you to prove that your proposal makes sense).

One more thing: if “the endpoint were a `BidiFlow`” then which four streams should be wired into it and by whom? An endpoint is at the end of something, not in the middle.

**Comment by fommil** [comment]
OK, fair enough from the exposed API it could remain as `Flow`, in which case you could use a `BidiFlow` internally to do the marshalling on the `In1` / `Out2` side as suggested... but this would be best in the framework (much as `ToMarshallable` is in the REST routes) rather than something the user has to do.

The BidiFlow wrapper you've given is useful for testing, thanks.

I'm happy to close as a dupe of https://github.com/akka/akka/issues/17969

**Comment by rkuhn** [comment]
Right, allowing nice usage of Marshallers in the routing directives for WebSockets is a good point. Thanks for the discussion!

**Comment by fommil** [comment]
@viktorklang so I see this tweet https://twitter.com/viktorklang/status/625631174648569856 and was about to respond with how we're using it in ENSIME now for REST and WebSockets but I see this:

![2015-07-28-204256_1918x1078_scrot](https://cloud.githubusercontent.com/assets/1914041/8941743/4c00ef5c-3569-11e5-9ef5-4bfe021fd650.png)

Really?? I mean, I've given more feedback on the release than anyone else:

- Source backpressure: https://github.com/akka/akka/issues/17610
- Sink backpressure: https://github.com/akka/akka/issues/17967
- marshalling https://github.com/akka/akka/issues/17969
- ping rate: https://github.com/akka/akka/issues/17968
- compression: https://github.com/akka/akka/issues/17725
- testing https://github.com/akka/akka/issues/17914

and I read the docs at various stages of the milestone plan and was a big advocate of akka-streams all the way back to https://groups.google.com/d/msg/akka-user/1TlAy-oqOk8/TIglnJDcSBAJ before that I was involved in setting up some of the earlier parallel processing examples in RxJava https://github.com/ReactiveX/RxJava/issues/840 and later benchmarking against scalaz-stream

 https://groups.google.com/d/msg/akka-user/PwasDZTFef4/VGRJwhorMKYJ

so, what gives? My feedback not good enough for you? Do you take offense at me saying that I needed to come up with some boilerplate (that nobody on the team understands) to use `Flow` when I already had all my code using `Actor`s?

**Comment by viktorklang** [comment]
@fommil It seems like this is not only the incorrect place for this discussion, but also a conflation of topics. Let me know if you want to continue in private. Thanks, Sam.

**Comment by fommil** [comment]
@viktorklang you can email me at sam.halliday@gmail.com for I have no way of contacting you it would seem.

**Comment by fommil** [comment]
(and I replied here simply becaus it is the only discussion I could possibly think of that caused you'd to block me)

**Comment by viktorklang** [comment]
@fommil I haven't seen this issue prior to my very recent mention so unlikely :)

**Comment by fommil** [comment]
(Insert picture of man scratching head)
