### ISSUE TITLE
Document how to properly avoid sending a 100-continue response

### ISSUE THREAD

**Issue by jroper** [akka/akka#18013]
The following test shows the problem:

```scala
      implicit val system = ActorSystem()
      implicit val mat = ActorMaterializer()

      val requested = new AtomicLong()
      val cancelled = new CountDownLatch(1)
      val sink = Sink.cancelled[String]
      val source = Source(List("foo", "bar"))

      val sourceAsPublisher = source.runWith(Sink.publisher)
      val sinkAsSubscriber = sink.runWith(Source.subscriber[String])

      val probedPublisher = new Publisher[String] {
        def subscribe(subscriber: Subscriber[_ >: String]) = sourceAsPublisher.subscribe(new Subscriber[String] {
          def onError(t: Throwable) = subscriber.onError(t)
          def onSubscribe(s: Subscription) = subscriber.onSubscribe(new Subscription {
            def cancel() = cancelled.countDown()
            def request(n: Long) = requested.addAndGet(n)
          })
          def onComplete() = subscriber.onComplete()
          def onNext(t: String) = subscriber.onNext(t)
        })
      }
      val mappedPublisher = Source(probedPublisher).map(identity).runWith(Sink.publisher[String])
      mappedPublisher.subscribe(sinkAsSubscriber)

      cancelled.await()
      assert(requested.get() == 0, "Requested was " + requested.get())
```

Since the subscriber at the end of the chain is a cancelled sink, there should never be any requests for anything issued anywhere in the chain, however the assertion fails.

Removing the map fixes the problem, as does feeding the probed publisher directly to a cancelled Sink.

This particularly causes a problem for Play, which depends on the absence of a request from a cancelled Sink resulting in the eventual Netty reactive streams publisher not receiving a request in order to know not to send a 100 continue message.

**Comment by jroper** [comment]
Adding `.withAttributes(Attributes.inputBuffer(0, 16))` after the `.map(identity)` also works around the problem.  But it seems odd to me that by default, Akka would introduce a buffer here.

**Comment by jroper** [comment]
Sorry, adding that doesn't work, it just throws an exception, saying the initial input buffer size must be greater than 1.  So... there's no work around for this issue that I can see.

**Comment by ktoso** [comment]
yes, there always must be a buffer of at least size one (for the incoming element).
Every stage in akka streams has a pre-fetch currently (related to that buffer). I'm curious to understand the case how sending the requests breaks the netty reactive streams publisher? I didn't quite grasp why it's a problem - could you explain that part a bit?

**Comment by jroper** [comment]
The problem is in correctly implementing support for `Expect: 100-continue`.  If an HTTP request sends this header, then the client will not send the body until the server responds with a `100 continue` response.  If it sends any other response, then the client won't send the body.  This is to allow the server to short circuit receiving the body, for example, if the client has a 1GB body to send, but authentication failed, the server will know immediately that the request is going to fail, but HTTP, being a half duplex protocol, doesn't allow sending the failed response until the full request is received, so 100 continue adds a way for the client to check whether it's ok to send the body or not first.  So, how do you implement this on the server side?  The most straight forward way, and the way that both Play and Akka HTTP implement it, is to send `100 continue` when the subscriber/sink makes a request for demand.  If the server isn't interested in the body, it should return a subscriber/sink that never requests demand.  So, if Akka streams introduces its own requests for demand, then that's a problem.

**Comment by jroper** [comment]
We currently work around this problem in Play using this:

https://github.com/playframework/playframework/blob/master/framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/MaterialiseOnDemandPublisher.scala

**Comment by viktorklang** [comment]
@jroper Are you TCK validating those implementations?

**Comment by jroper** [comment]
The MaterialiseOnDemandPublisher? No, it's not validated. For now it just exists to work around a problem, once we fix this, it will be deleted.

**Comment by viktorklang** [comment]
Right, I do encourage TCK validation anyway, just to not replace one buggy
impl with another :)

**Comment by rkuhn** [comment]
@jroper This ticket cannot be fixed because doing (small) buffering and prefetch is ingrained in the Akka Streams design philosophy—relying on getting a graph assembled in which not a single part will ever do a request (unless some event X happens) is not a winning proposition. The way to use the Akka HTTP 100-continue API is to not materialize the request payload Source unless you already know that you will read it. We can help with how to do that, but this ticket is “won’t fix”.

**Comment by jroper** [comment]
Fair enough, but then perhaps Akka HTTP's 100 confinue support should be modified to send 100 continue on materialisation, not on request. At the moment, it's on request, which makes it an implementation detail of Akka streams as to whether 100 continue is actually sent or not. I think it would be better to have completely specified and documented behaviour there, so that it's clear how to get 100 continue support right when using Akka HTTP.

**Comment by rkuhn** [comment]
Good point, this must be properly documented.

The current behavior is that it is request-triggered and the only guaranteed way to never send a request is to not materialize it (although it is obviously also not guaranteed that materialization will lead to a request …).

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
