### ISSUE TITLE
DOCS: show how to mock server responses in HTTP client tests

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18022]
from the [mailing list](https://groups.google.com/d/topic/akka-user/-rsD467ADC4/discussion):

> I have an actor that is sending outbound http request.
I would like top  test that actor ,is there an option to mock that call ? what is the correct way for doing that ? 

My answer in that thread:

> in order to switch out the actual HTTP part you’ll have to configure your Actor with this part, e.g. by providing a function “HttpRequest => Future[HttpResponse]” or a “Flow[HttpRequest, HttpResponse, _]” or similar. Then in your production code you plug in the HTTP client pool and in your tests you can simply stub it out by a function that provides canned answers.

**Comment by drewhk** [comment]
Ah, this is a documentation section. I thought that there is a feature missing.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
