### ISSUE TITLE
DOCS: make sure to document needed implicits

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18021]
From the [mailing list](https://groups.google.com/forum/#!topic/akka-user/GOvEwFhSVRk):

> I got hit by this stuff today when moving some tests from one package to another disabled responseAs[String] completely (earlier, it worked in some endpoints, but not in others). The answer is to import akka.http.scaladsl.unmarshalling.Unmarshaller._ in tests, which mixes in PredefinedFromEntityUnmarshallers, which contain an unmarshaller to string. Second, it is necessary to import akka.http.scaladsl.marshalling.Marshaller._ in the file where the route is defined, so that string responses are marshalled correctly (if you don't do it, your response bodies unmarshalled in tests will contain an extra set of double quotes).

**Comment by drewhk** [comment]
Maybe add one dedicated section too, kind of an "imports cheat-sheet"? I also have to sometimes look into the akka-http tests to remember what imports I will need and which I don't, implicits or simply model entities :)

**Comment by patriknw** [comment]
+1

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
