### ISSUE TITLE
DOCS: links to source in akka streams scaladoc no longer work

### ISSUE THREAD

**Issue by AnIrishDuck** [akka/akka#18030]
For example, the link [here](http://doc.akka.io/api/akka-stream-and-http-experimental/1.0/?_ga=1.7414258.1365931584.1431708042#akka.stream.FanInShape2) to [github](https://github.com/akka/akka/tree/release-2.3-dev//akka-stream/target/src_managed/main/akka/stream/FanInShape.scala) is broken.

This worked a couple days ago, and was very useful when trying to figure out how things worked under the covers.

**Comment by ktoso** [comment]
Thanks for reporting! Very weird... I used the usual process for publishing them hm.
Will look into it

**Comment by AnIrishDuck** [comment]
AFAICT it's working now. Cheers.

**Comment by AnIrishDuck** [comment]
Aaaand [it's broken again](http://doc.akka.io/api/akka-stream-and-http-experimental/1.0/#akka.stream.FanInShape2).

**Comment by ktoso** [comment]
Or rather still :-) did not yet get the chance to work on it. Thanks for
reporting again :-)

**Comment by AnIrishDuck** [comment]
OK. FWIW it definitely started working again for an hour or so, which may mean it's a misconfiguration in publishing that's not universal.

**Comment by 2m** [comment]
This is a generated scala file from a template. It should be fixed to point to the boilerplate file [here](https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/boilerplate/akka/stream/FanInShape.scala.template).

**Comment by ennru** [comment]
This report is outdated and the source links are present.
Eg. on https://doc.akka.io/api/akka/current/akka/stream/scaladsl/Flow.html
