### ISSUE TITLE
Hook on PersistentActor after message is persisted

### ISSUE THREAD

**Issue by jgordijn** [akka/akka#18032]
I want to extend the behaviour of the `PersistentActor` such that a function is called (with the persisted event) every time a message is persisted. If the `PersistentActor` provided a hook `onPersistSuccess` it would be possible to extend the behaviour.

The use case is that I want to publish every persisted message on a bus. I would like to mixin a trait into the existing actors to provide this behaviour, but that means that the existing Actor needs to call a new function `persistAndPublish` instead of `persist`. I would like to use this hook so that mixing in this trait is enough.

**Comment by michaelom** [comment]
+1

**Comment by rkuhn** [comment]
I’m not convinced that this is a good idea: it is yet another way in which PersistentActor gets more convenient for the case of keeping variable(s) in the Actor which are acted upon by callbacks instead of properly containing state-dependent information in different behaviors. The common pattern is to have an `applyEvent` method that either updates a variable or transforms a given state into a new state and this method would be the place to put the publishing action (or any cross-cutting concern). Adding a second but invisible way to do the same thing is probably not a good idea.

**Comment by michaelom** [comment]
>The common pattern is to have an applyEvent method that either updates a variable or transforms a given state into a new state and this method would be the place to put the publishing action (or any cross-cutting concern). Adding a second but invisible way to do the same thing is probably not a good idea.

After working on an ES-solution with Akka for almost a year, my experience is, that PersistentActors get very, very complex. Some of the complexity also comes from state/behaviors-dependent actions when persisting events. Yet some actions are executed irrespective of the actors state or behaviour. 

e.g. for state A:
 ```persist(event, persistedEvent -> {
                actionA();
                applyEvent(persistedEvent);
                actionC();
                actionX();
            });```

e.g. for state B:
 ```persist(event, persistedEvent -> {
                applyEvent(persistedEvent);
                actionD();
                actionX();
            });```

Currently we have to repeat `actionX()` for each state. There is no way to declare cross-cutting actions.

By the way, the `appyEvent`-method is not the place I put my publishing logic in. :-)
`appyEvent` does exactly what it says it does.

**Comment by jgordijn** [comment]
@rkuhn I understand your hesitation, but there is no other way to define behaviour that should always be performed for every event. 

Implementing the publish logic fine when I was to implement this for 1 PersistentActor, but when I have many actors I prefer to extend `PublishingPersistentActor` (which would use the `onPersistSuccess`) instead of `PersistentActor` and focus on the business logic inside my actor.

Furthermore, I agree with @michaelom that I would not put publish logic in `applyEvent`. `applyEvent` will also be called on playback by `ReceiveRecover` and in that case I do not want to publish the event.

**Comment by patriknw** [comment]
We have been discussing and thinking about this several times, but in the end we don't think it is worth expanding the api surface for this. Adding hooks for cross cutting concerns at all places is not feasible. I'm sure  many similar hooks are needed in other places in akka if we go that route.

**Comment by jgordijn** [comment]
Hi @patriknw,

It's a pity the feature is declined as this would really make my library much easier to use. The PersistentActor is not open for extension in any other way.

Anyway, I can understand your reasoning. Thanks for the feedback on the PR and the time you all took to look at it.

Jeroen

**Comment by ktoso** [comment]
We may revisit making persist not final though. It would make it possible for you to wrap the handler with the publish-to-bus code.
WDYT @patriknw?

-- 
Cheers,
Konrad 'ktoso’ Malawski
Akka @ Typesafe

On 7 August 2015 at 21:28:26, Jeroen Gordijn (notifications@github.com) wrote:

Hi @patriknw,

It's a pity the feature is declined as this would really make my library much easier to use. The PersistentActor is not open for extension in any other way.

Anyway, I can understand your reasoning. Thanks for the feedback on the PR and the time you all took to look at it.

Jeroen

**Comment by jgordijn** [comment]
@ktoso, my reasoning was that foregoing the final would not be permissible. But if dropping final is an option, it would definitely solve my issue.

**Comment by patriknw** [comment]
I don't mind removing final on those.

**Comment by jgordijn** [comment]
Does https://github.com/akka/akka/pull/18148 cover it? I'm a bit uncertain if I should also remove `final` in the UntypedPersistentActor?

**Comment by ktoso** [comment]
It would also have to remove `final` from `UntypedPersistentActor` as well as `AbstractPersistentActor`, as well as from `deferAsync` for consistency.
Thanks for picking it up!

-- 
Cheers,
Konrad 'ktoso’ Malawski
Akka @ Typesafe

On 7 August 2015 at 23:02:45, Jeroen Gordijn (notifications@github.com) wrote:

Does #18148 cover it? I'm a bit uncertain if I should also remove final in the UntypedPersistentActor?

**Comment by ktoso** [comment]
Resolved by https://github.com/akka/akka/pull/18148 by making `persist*` and `deferAsync` overrideable. 
Happy hakking!
