### ISSUE TITLE
Add recoverWith(Source)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18045]
Was needed in community as well as I think it'd be very useful for simple in-line recovery mechanisms.

**Comment by 2beaucoup** [comment]
[This](https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala#L312-L321) could be DRYed up on the way.

**Comment by rkuhn** [comment]
Shouldn’t it rather be `Throwable => Source()`?

**Comment by ktoso** [comment]
Yeap, right

**Comment by hepin1989** [comment]
```PartialFunction[Throwable, Source[T]]```?

**Comment by agolubev** [comment]
Started this ticket
