### ISSUE TITLE
HTTP/1.0 requests without Host header fail noisily with 500

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18044]
Http 1.0 and 1.1 requests take different code paths if the request is missing a `Host` header. An Http/1.1 request fails in https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala#L195 while an Http/1.0 request gets through the parser to https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L71 where it fails uncontrolled and noisily when no `defaultHostHeader` is defined.

It would probably be easiest to move the `defaultHostHeader` processing to the parser as well, so we can fail there in all cases.

See https://groups.google.com/d/topic/akka-user/_fG27EJCZJA/discussion

/cc @2beaucoup @sirthias

**Comment by 2beaucoup** [comment]
Why do we require the URIs to be absolute in the first place? This will fail valid HTTP/1.0 requests.

From http://www.w3.org/Protocols/HTTP/1.0/spec.html#Request-URI:

> The most common form of Request-URI is that used to identify a resource on an origin server or gateway. In this case, **only the absolute path of the URI is transmitted**.

Host headers are only sped'd since HTTP/1.0.

**Comment by jrudolph** [comment]
AFAICS the reasoning is that akka-http mostly implements a HTTP/1.1 server for which an effective URI can always be established. For legacy reasons we still support HTTP/1.0 but to be able to support an HTTP/1.1 API we need some host to "complete" the target URI. You can either provide that by setting the `default-host-header` setting or otherwise HTTP/1.0 requests will be unsupported.

As HTTP/1.0 requests should be quite rare by now I wouldn't complicate things and just adapt the logic in RequestParser to fail with 400 if an HTTP/1.0 header is received without a default-host-header being set. WDYT?

**Comment by 2beaucoup** [comment]
Mmh, why not the other way around: Remove [this line](https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L71) and get rid of `default-host-header` along the way? Folks who need it can always call `HttpRequest.withEffectiveUri`with whatever host they see fit. (TBH I don't see where that would be needed.)

After a quick test it seems that only the tests would fail where we explicitly expect the URIs th be absolute.

**Comment by jrudolph** [comment]
@2beaucoup the main reason for keeping `default-host-header` is to keep the current API where incoming request URIs can be expected to be absolute in every case i.e. you never have to deal with a `Host` header manually but can rely on akka-http-core providing absolute URLs. So, IMO my last comment describes a good enough solution for now.

The reason that not more tests fail is that we don't have many HTTP/1.0 tests which e.g. test the `host` directive.

**Comment by jrudolph** [comment]
Fixed in #18194.

**Comment by 2beaucoup** [comment]
> the main reason for keeping `default-host-header` is to keep the current API where incoming request URIs can be expected to be absolute in every case

I wasn't aware of this. Is this documented somewhere?

**Comment by sirthias** [comment]
@2beaucoup You are right, we should document this.
I agree with @jrudolph here in that having the "akka-http always delivers full URIs" invariant is a valuable thing to have that IMHO is worth the complexity cost of the extra `default-host-header` config setting.
