### ISSUE TITLE
Reenable genjavadoc for Access$minusControl$minusAllow$minusOrigin$ in akka-http-core

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18056]
While fixing #15452, there remained a single file with errors for which doc generation will be disabled for now.

It currently fails with these kind of errors:

```
[error] /home/johannes/git/opensource/akka-streams/per-branch-targets/w_15452-fix-gen-scala-doc/akka-http-core-experimental/java/akka/http/scaladsl/model/headers/Access$minusControl$minusAllow$minusOrigin$.java:10: error: <identifier> expected
[error]   public  akka.http.scaladsl.model.headers.Access$minusControl$minusAllow$minusOrigin null () { throw new RuntimeException(); }
[error]                                                                                      ^
```

Here are the generated files and logs:

https://gist.github.com/jrudolph/6147585cf713444aee82

**Comment by jrudolph** [comment]
The problem is that there's a symbol with the name "null" in backticks:

```scala
object `Access-Control-Allow-Origin` extends ModeledCompanion[`Access-Control-Allow-Origin`] {
  val `null` = forRange(HttpOriginRange())
  // ...
}
```

How does genjavadoc handle similar issues with backticked symbol names that are keywords in Java?

**Comment by jrudolph** [comment]
Btw. this file is part of the scaladsl, so there's not much gained by fixing this.

**Comment by 2beaucoup** [comment]
I'd be interested in details of your `per-branch-targets` layout. :)

**Comment by jrudolph** [comment]
It's seriously low-tech. I put up quick instructions here: https://gist.github.com/jrudolph/c79777cf374fbd3d2d1a

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
