### ISSUE TITLE
Shade protobuf in akka

### ISSUE THREAD

**Issue by clockfly** [akka/akka#18055]
Akka use protobuf 2.5, it will be very difficult if user app depends on older protobuf version.

For example, hadoop (before version 2.1) use  protobuf version 2.4.1. When user app want to send message to hadoop service in akka Actor, then there will be serialization error, due to incompatible protobuf version.

Akka is an infrastructure platform, I think it is reasonable for akka to shade external dependencies like protobuf, so that there are less chance of jar conflict in user app.

**Comment by ktoso** [comment]
Thanks for the reminder, we totally agree.
We're aware of this and had tried to repackage once already (sadly that effort died down);

The ticket we track this with is: https://github.com/akka/akka/issues/13783
