### ISSUE TITLE
Integrate EventAdapters to the Query side

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18050]
Since EventAdapters can be used to detach the data model from the domain model, they must be a first class citizen in the query side as well.

**Idea 1:**
~~Make configurable (same as the write side, transparently) and tuneable via:~~

```scala
ReadJournal {
  def query...
  def withEventAdapters(config: Config): ReadJournal
  def withEventAdapters(adapters: (Class[_], EventAdapter)*): ReadJournal
```

~~ReadJournals do not have to implement anything to make this possible, however the methods would be nicely accessible for users on ReadJournal.~~

**Idea 2:**
Make it easy enough to obtain `EventAdapters` such that it can be applied as a map step. This again needs construction in code as `(Class[_] -> EventAdapter)*`. So similar to the first idea, however detached from the readjournal. 

**Idea 3:**
Something else?

**Comment by ahjohannessen** [comment]
Would it make sense to define `EventAdapter` in terms of `EventReadAdapter` and `EventWriteAdapter`:

```scala
trait EventReadAdapter {
  def fromJournal(event: Any): ...
}
trait EventWriteAdapter {
  def toJournal(event: Any): ...
}
```
where current `EventAdapter` would extend both, but the `ReadJournal` would only require `EventReadAdapter` and thus minimizing the API surface area to only relevant methods.

**Comment by ktoso** [comment]
Yes good point!
It initially was 2 interfaces like above actually, but there we only thought about the write side still;
Since the read side needs it as well, splitting up makes sense I think (can imagine something starting out as `EventAdapter` and then the "very old code" gets moved to only the read side's adapters).

**Comment by ahjohannessen** [comment]
The thing that prompted me was this: https://github.com/akka/akka/pull/18051/files#diff-ff86a6201dd1acf1ec044cffadbaabfcR69 :)

**Comment by ktoso** [comment]
True true :smile:

**Comment by ktoso** [comment]
1) We'll make more or less like so `stream.map(EventAdapters.apply)`, so no additional API on the journal
2) we'll make it two interfaces https://github.com/akka/akka/issues/18137

**Comment by patriknw** [comment]
I don't think event adapters should be used in the stream transformations because `fromJournal` takes a manifest parameter and that is typically not known at that point.

I think event adapters should be applied by the journal query plugin. That is already done by the leveldb query plugin.
Such an plugin can grab the event adapters via `Persistence(system).adapterFor`. Nothing more needed for this, except from making `EventAdapters` public.
