### ISSUE TITLE
SslTls gulps any exceptions and just completes the stream

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18058]

**Comment by drewhk** [comment]
Can you give a reproducer? That would help :)

**Comment by jrudolph** [comment]
Ah, yes, I agree :)

See this test: https://github.com/akka/akka/pull/18062/files#diff-2453cd0d85f7231698125cab6f8a6b66R37

The exceptions falling out here are the wrong ones. What currently happens is that the `SslTls` stage completes regularly in case of an error.

In the tests, the exceptions only turn up because the layer on top of TLS expect more data so that they fail with some kind truncation exception.

Users that have actual TLS problems (like broken certificate chains, broken hostname verification, or being unable to negotiate ciphers) will have a hard time finding out what's going wrong because all of this won't turn up anywhere.

**Comment by jrudolph** [comment]
#17628 shows a more severe problem where in a specific error case SslTls just stops processing. 

#17628 also contains [this comment](https://github.com/akka/akka/issues/17628#issuecomment-111981672) from @rkuhn:

> We need to ensure that we test all nine combinations (on either side there can be a TLS server, TLS client or no TLS). We have only three cases in the tests so far (client–server and server–client and plain–plain) and the others need to be made such that they properly error out (possibly with timeout).

So, I guess the SslTls stage needs a few more tests which tests more combinations of errors.

**Comment by AnIrishDuck** [comment]
@drewhk - just saw you changed the status on this. How far along are you? I've been working on a fix myself, but have just got past the stage of adding a test for my issue.

**Comment by drewhk** [comment]
@AnIrishDuck feel free to work on it, I didn't progress much on this, I will revisit it again in a couple of days. If you have something, I am happy to look at it.

**Comment by AnIrishDuck** [comment]
OK. The big remaining issue with my branch is that the actors don't seem to terminate properly (hence 81eae47 which is a hack to get tests working). I'm going to be on vacation until next Tuesday, but will pick this up when I get back. Unless you get to it first, of course :)

**Comment by francisdb** [comment]
I'm sure a lot of early akka http client adopters will run into this and waste quite some time on it. This issue needs some love and a release :-)

**Comment by drewhk** [comment]
@francisdb We will fix it I promise :)
