### ISSUE TITLE
Streams: SourceTest.mustBeAbleToRecover failes from time to time

### ISSUE THREAD

**Issue by agolubev** [akka/akka#18066]
```SourceTest.mustBeAbleToRecover failed: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1```
This happens because error event outruns data events. I will fix the test.

**Comment by ktoso** [comment]
Thanks a lot!

I reported it here: https://github.com/akka/akka/issues/18002
Let's track using that issue number and close this one as duplicate.

**Comment by agolubev** [comment]
Ok, NP
