### ISSUE TITLE
FormFieldDirectives (and maybe ParameterDirectives as well) still depend on compilation order on Scala 2.10

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18070]
This seemed to be fixed with #17552 but has reappeared. It can be reproduced by removing the explicit `FieldMagnet` import in https://github.com/spray/akka/commit/195650ff7eaea7a922bb6fc0da95f3b1368f669e

/cc @sirthias

**Comment by jrudolph** [comment]
This problem doesn't seem to appear with 2.11.x, so maybe it's an already (in 2.11.x) fixed problem with implicit resolution (in relation with dependent method types?).

**Comment by 2m** [comment]
Should be solved with a documentation note in FormFieldDirectives and ParameterDirectives.

**Comment by jrudolph** [comment]
Fixed with a comment added in #18143.
