### ISSUE TITLE
TestActorRef doesn't have apply() method to specify supervisor without specifying name

### ISSUE THREAD

**Issue by mattinbits** [akka/akka#18077]
TestActorRef has an apply method where the name and supervisor are set for you,  one where the name can be specified, and one where name and supervisor can be both be specified. But there isn't one where you specify the supervisor but let the method take care of using a random name. I've been resorting to using things like `Random.nextString` when I want to set the supervisor but don't care what the name is and want it to be unique.

I'm happy to work on the fix for this one, assuming it's a valid issue. Could look at #13980 at the same time it's in the same part of the code base.

**Comment by ktoso** [comment]
Sounds valid based on what you describe. Place a add the missing overload
and issue a PR, thanks!
