### ISSUE TITLE
Nightly job failures

### ISSUE THREAD

**Issue by 2m** [akka/akka#18071]
Nightly jobs became somewhat flaky. Lots of different tests suites that fail. Could be something with CI machines.

- [x] akka.cluster.routing.AdaptiveLoadBalancingRouter
  https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/54/consoleFull

- [x] akka.remote.RemoteRestartedQuarantinedSpec
  https://jenkins.akka.io:8498/job/akka-nightly/2430/consoleFull

- [x] akka.remote.RemoteReDeploymentMedium
  https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/59/consoleFull

- [x] akka.persistence.fsm.LeveldbPersistentFSMActorSpec
  https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2655/consoleFull

- [x] sample.distributeddata.ReplicatedMetricsSpec
  https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2656/consoleFull

- [x] sample.distributeddata.ReplicatedCacheSpec
  https://jenkins.akka.io:8498/job/akka-nightly/2440/consoleFull

- [x] akka.actor.LightArrayRevolverSchedulerSpec
  https://jenkins.akka.io:8498/job/akka-nightly/2449/consoleFull

**Comment by patriknw** [comment]
hmm, indeed a lot of failures

**Comment by ktoso** [comment]
The `AdaptiveLoadBalancingRouter` fails with 

```

[JVM-1] [WARN] [07/15/2015 08:17:21.060] [AdaptiveLoadBalancingRouterSpec-akka.actor.default-dispatcher-17] [akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794/system/cluster/core/daemon] Cluster Node [akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022, status = Up)]
[JVM-3] [WARN] [07/15/2015 08:17:21.142] [AdaptiveLoadBalancingRouterSpec-akka.actor.default-dispatcher-14] [akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022/system/cluster/core/daemon] Cluster Node [akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794, status = Up)]
[JVM-1] [INFO] [07/15/2015 08:17:21.784] [AdaptiveLoadBalancingRouterSpec-akka.actor.default-dispatcher-17] [akka.cluster.Cluster(akka://AdaptiveLoadBalancingRouterSpec)] Cluster Node [akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794] - Ignoring received gossip status from unreachable [UniqueAddress(akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022,765315385)] 
[JVM-1] - must prefer node with more free heap capacity *** FAILED *** (21 seconds, 248 milliseconds)
[JVM-1]   2284 did not equal 3000 (AdaptiveLoadBalancingRouterSpec.scala:188)
[JVM-1]   org.scalatest.exceptions.TestFailedException:
[JVM-1]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$7.apply$mcV$sp(AdaptiveLoadBalancingRouterSpec.scala:188)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(AdaptiveLoadBalancingRouterSpec.scala:174)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(AdaptiveLoadBalancingRouterSpec.scala:162)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(AdaptiveLoadBalancingRouterSpec.scala:162)
[JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

I'll investigate it deeper

**Comment by ktoso** [comment]
The scheduler spec failed tight around the timeout:

```
akka.actor.LightArrayRevolverSchedulerSpec

[info] - must not be affected by long running task *** FAILED *** (5 seconds, 521 milliseconds)
[info]   4.002183008913953 did not equal 4.4 plus or minus 0.3 (SchedulerSpec.scala:254)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
```

this was on `a0`

**Comment by ktoso** [comment]
I have split out all of these into separate tickets, closing this one and will investigate them individually

**Comment by 2m** [comment]
More failures from last two weeks. A summary gives a bit more information on frequency, specs, and nodes that failures happen.

|Date     |Node|Job                                                                                |Failed                                   |
|---------|----|:---------------------------------------------------------------------------------:|:---------------------------------------:|
|14, 7:14 |a4  |[multi-node](https://jenkins.akka.io:8498/job/akka-multi-node/1156)                |RemoteNodeShutdownAndComesBack           |
|14, 8:21 |a0  |[release-2.3](https://jenkins.akka.io:8498/job/akka-release-2.3/213)               |FSMTimingSpec                            |
|14, 11:19|a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2773)|LeveldbPersistentFSMSpec                 |
|15, 3:17 |a0  |[nightly](https://jenkins.akka.io:8498/job/akka-nightly/2521)                      |LeveldbPersistentFSMSpec                 |
|15, 4:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2775)|LeveldbPersistentFSMSpec                 |
|15, 6:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2776)|ddata.PerformanceSpec                    |
|19, 4:19 |a0  |[multi-node](https://jenkins.akka.io:8498/job/akka-multi-node/1162)                |cluster.NodeChurn                        |
|19, 6:10 |a0  |[multi-node](https://jenkins.akka.io:8498/job/akka-multi-node/1163)                |cluster.{NodeChurn,ddata.PerformanceSpec}|
|19, 9:17 |a0  |[nightly](https://jenkins.akka.io:8498/job/akka-nightly/2534)                      |akka-persistence-tck                     |
|19, 11:19|a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2793)|leveldb.EventsByPersistenceIdSpec        |
|20, 1:17 |a0  |[nightly](https://jenkins.akka.io:8498/job/akka-nightly/2535)                      |akka-persistence-tck                     |
|20, 3:17 |a0  |[nightly](https://jenkins.akka.io:8498/job/akka-nightly/2536)                      |leveldb.EventsByPersistenceIdSpec        |
|20, 9:17 |a0  |[nightly](https://jenkins.akka.io:8498/job/akka-nightly/2537)                      |DDataClusterSharding                     |
|21, 3:17 |a0  |[nightly](https://jenkins.akka.io:8498/job/akka-nightly/2539)                      |leveldb.EventsByPersistenceIdSpec        |
|21, 6:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2800)|LeveldbPersistentFSMSpec                 |
|21, 7:18 |a0  |[multi-node-nightly2](https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/91)|ddata.PerformanceSpec                    |
|22, 3:17 |a0  |[nightly](https://jenkins.akka.io:8498/job/akka-nightly/2542)                      |ReplicatedMetricsSpec                    |
|22, 6:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2804)|LeveldbPersistentFSMSpec                 |
|23, 2:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2806)|LeveldbPersistentFSMSpec                 |
|23, 7:18 |a0  |[multi-node-nightly2](https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/93)|cluster.{NodeChurn,ddata.PerformanceSpec}|
|24, 2:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2810)|LeveldbPersistentFSMSpec                 |
|24, 7:18 |a0  |[multi-node-nightly2](https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/94)|*many*                                   |
|26, 7:18 |a0  |[multi-node-nightly2](https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/96)|AdaptiveLoadBalancingRouter}             |
|26, 11:19|a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2821)|*many*                                   |
|27, 7:18 |a0  |[multi-node-nightly2](https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/97)|ddata.PerformanceSpec                    |
|27, 3:45 |a3  |[release-2.3](https://jenkins.akka.io:8498/job/akka-release-2.3/216)               |RemoteRestartedQuarantinedSpec           |
|27, 11:19|a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2825)|*many*                                   |
|28, 6:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2828)|LeveldbPersistentFSMSpec                 |
|28, 11:19|a0  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2829)|AdaptiveLoadBalancingRouter              |
|29, 2:19 |a3  |[multi-node-nightly](https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2830)|PersistentClusterShardingLeaving         |

**Comment by patriknw** [comment]
@2m thanks for compiling that list
