### ISSUE TITLE
Include persistenceId in AtomicWrite

### ISSUE THREAD

**Issue by chbatey** [akka/akka#18076]
If the AtomicWrite included the ~~partitionId~~ persistenceId it would make it explicit that an AtomicWrite contains entries for a single persistenceId.

Also the min/max seqNr on the AtomicWrite would be useful. Not a biggy but would make my life a little easer when deciding the persistence strategy for Cassandra to best achieve atomicity.

**Comment by ktoso** [comment]
Thanks for the issue Chris! Will look into it soon :-)

**Comment by scullxbones** [comment]
Good call on the ticket.  I'm seeing some of the same complexities re: persistenceId & min/max sequence.  I modeled my 2.4 journal to support N persistenceIds per, forcing a single will simplify my schema quite a bit.  Thank you!

**Comment by ktoso** [comment]
Great to hear some confirmation for the need here, thanks @scullxbones! :-)
Have you seen the PR https://github.com/akka/akka/issues/18085 - should address all the needs right?

**Comment by scullxbones** [comment]
That's where I found this ticket, from the PR.  Looks like exactly what I need - for each AW, the triplet of `persistenceId`, min sequence, max sequence.  So glad I didn't release with the multi-persistenceId-per-AW data model, so complicated. :smile:

Thanks @ktoso!

**Comment by ktoso** [comment]
Great, thanks for chiming in! :-)
