### ISSUE TITLE
Streams: stream.io classes have DefaultAttributes as local values

### ISSUE THREAD

**Issue by agolubev** [akka/akka#18086]
SynchronousFileSink, SynchronousFileSource, OutputStreamSink, InputStreamSource have ```final val DefaultAttributes``` - should use Stages.DefaultAttributes instead

**Comment by ktoso** [comment]
Yes that might be a good idea, with one twist though - it should probably be in `akka.stream.io.impl.Stages` or something like that, not in the top level Stages (we want to keep the io package separated).

**Comment by ktoso** [comment]
Sounds irrelevant nowadays, closing
