### ISSUE TITLE
Replace Source.apply overloads with explicit factories

### ISSUE THREAD

**Issue by mushtaq** [akka/akka#18083]
Commonly used factory methods for Source should be non-overloaded methods with names that are easy to discover in IDEs (like Source.fromIterable, Source.fromIterator, Source.fromFuture etc).

**Comment by jeroenr** [comment]
+1

**Comment by viktorklang** [comment]
I'm sympathetic to this change, I've thought the same thing myself a couple of times.
Would love to hear more opinions on this topic.

**Comment by ktoso** [comment]
I'd enjoy it as well, it's more dog (consistent) as "for some we have the named ones, yet for some we have apply". I found myself sometimes wondering which ones deserve the name and which not.

**Comment by viktorklang** [comment]
misclick

**Comment by rkuhn** [comment]
This is being done in #18700 .
