### ISSUE TITLE
Reuse EnhancedInetSocketAddress.getHostStringJava6Compatible in more places

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#18098]
It currently resides in http and therefore can't be reused in io/remote.

We could wait until Java6 gets unsupported and remove it altogether as well. ;)

**Comment by jrudolph** [comment]
@2beaucoup in #18062:

> I think that we should even move getHostStringJava6Compatible to akka.io or akka.util as there are a lot of TODOs all over the place.

We already use this methods currently in akka-http(-core) wherever possible but the suggestion was to move it up a few layers to make use of it in akka-actor and akka-stream.
