### ISSUE TITLE
PersistentFSM uses onRecoveryCompleted vs PersistentActor's RecoveryCompleted

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18103]
PersistentFSM uses `onRecoveryCompleted` and PersistentActor uses the message `RecoveryCompleted`.
This ticket is a note to remember sanity check if this is OK or if we want them to be consistent.

Since there's multiple states in FSM, maybe keeping the method makes sense since it's "one place" to handle it.

**Comment by patriknw** [comment]
FSM is callback based, e.g. `onTransition` and it does not have ordinary receive, so I think `onRecoveryCompleted` is fine.

**Comment by ktoso** [comment]
Yeap, now that I've spent some time in it today I agree as well. Closing as invalid.
