### ISSUE TITLE
Documentation describes non-existing method preRestart for normal actors

### ISSUE THREAD

**Issue by vitaliis** [akka/akka#18107]
Hello,

I found that some part of documentation doesn't comply with the latest sources.

Referring to documentation at http://doc.akka.io/docs/akka/2.3.12/scala/fault-tolerance.html
and using
```
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.3.12"
```
I am missing 
```
  // override default to kill all children during restart
  override def preRestart(cause: Throwable, msg: Option[Any]) {}
```

This is probably already somehow refactored or removed.

And the second thing is that the comment can be misleading (if I understood it correctly). I suppose what meant is: override default and not kill all children during restart

**Comment by ktoso** [comment]
Hi @vitaliis,
all the docs code snippets are compiled and tested before publishing so it's unlikely we'd reference a missing method :-)

`preRestart` exists, and is defined on Actor: https://github.com/akka/akka/blob/v2.3.12/akka-actor/src/main/scala/akka/actor/Actor.scala#L530
