### ISSUE TITLE
Improve Java DSL in JavaTestKit (Java 8)

### ISSUE THREAD

**Issue by michaelom** [akka/akka#18109]
Testing asynchronous code is a challenging task per se. Testing actors is even more challenging mostly due to the nature of the actor model (very tight encaspulation, message passing, parent-child-relations/supervision,...)

I think JavaTestKit does an excellent job in making actor tests possible. But I think **parts** of the current DSL are not very intuitive, can be very verbose and suffer from poor readability. With Java 8, most assertions could be a one-liner. Consider the following DSL from https://github.com/jayway/awaitility/wiki/Usage#example-7---java-8

`await().atMost(5, SECONDS).until(userRepository::isNotEmpty);`

vs the suggested way with JavaTestKit:

```
new AwaitAssert(duration("5 seconds")) {
                @Override
                protected void check() {
                    assertThat(repository, is(notEmpty)));
                }
            };
```

To most people it is not clear what this code block tries to assert. Adding a polling interval to the constructor or having enclosing within-blocks makes it event worse.

Testing logging output with akka.testkit.TestEventListener is an awesome feature. The DSL to use it not so much. It is completely non-obvious what the following code does:

```
new EventFilter<Void>(ActorKilledException.class) {
    protected Void run() {
      victim.tell(Kill.getInstance(), ActorRef.noSender());
      return null;
    }
  }.from("akka://TestKitDocTest/user/victim").occurrences(1).exec();
```

Here I see 6 lines of code with absolutely no reference to what assertion is made or what behaviour is tested. 

I care a lot about testing and currently Akka is giving me a hard time. Please consider a new API with an improved DSL for a future (Java-8-only) release.

**Comment by ktoso** [comment]
Akka 2.4 (`master` branch) is Java 8 only, so we could bring in more lambda-nice APIs there.
Would you be interested in submitting a PR or two to improve the status quo, like you explained above?

**Comment by michaelom** [comment]
Hi @ktoso ,

interested - yes, but it's very unlikely I can start anytime soon.

**Comment by johanandren** [comment]
Also, see the notes in #21858

**Comment by johanandren** [comment]
Not sure if some of this maybe was done in #22240

**Comment by patriknw** [comment]
This is done, afaik
