### ISSUE TITLE
SubscriberEvent in stream-testkit is not visible

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18111]
SubscriberEvent is used as parameter in for example `receiveWhile`, but it is defined in `private[testkit] object StreamTestKit`

Might be similar problem with `PublisherEvent`.

**Comment by patriknw** [comment]
please also add `expectNextPF`

**Comment by agolubev** [comment]
@patriknw, can you give more details about expectNextPF? (not sure what PF means)

**Comment by patriknw** [comment]
it is a partial function (pattern match), we have similar in actor testkit

**Comment by agolubev** [comment]
Got it - thanks
