### ISSUE TITLE
Backport permgen fix to 2.3

### ISSUE THREAD

**Issue by benmccann** [akka/akka#18115]
Can you please backport https://github.com/akka/akka/commit/49e6e7f38cb6e738e839f4763189531a5c0c3351 to the 2.3 branch? Play 2.4 uses Akka 2.3.11 and crashes frequently in development mode with OutOfMemoryError, which we believe we've traced to this issue.

**Comment by benmccann** [comment]
I'm not sure what the difference is between the release-2.3 branch and release-2.3-dev, so I've submitted PRs to backport to both branches

release-2.3: https://github.com/akka/akka/pull/18116
release-2.3-dev: https://github.com/akka/akka/pull/18117

**Comment by ktoso** [comment]
Hi @benmccann,
thanks for the PRs. `release-2.3` is the right one to target this to, as `release-2.3-dev` is only for akka streams and http. Thanks!

**Comment by benmccann** [comment]
Fixed. THanks!
