### ISSUE TITLE
Do we need a PersistentView 1:1 replacement?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18123]
Or just docs?
It's super simple to do with the query side.

**Comment by patriknw** [comment]
I don't think we should implement anything right now. Let's see user feedback first.
Several alternatives, depending on what you need.
* `Sink.actorRef` (back-pressure is lost)
* `mapAsync` + `ask`
* `ActorSubscriber`

I'll start with deprecating it and mention those alternatives in migration guide.

@ktoso

**Comment by ktoso** [comment]
+1, yes deprecation with explaining these options sounds very good.


On 13 August 2015 at 17:06:16, Patrik Nordwall (notifications@github.com) wrote:

I don't think we should implement anything right now. Let's see user feedback first.
Several alternatives, depending on what you need.

Sink.actorRef (back-pressure is lost)
mapAsync + ask
ActorSubscriber
I'll start with deprecating it and mention those alternatives in migration guide.

@ktoso
