### ISSUE TITLE
Allow parsing of UTF8 header values

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18121]
@sirthias can you check what is needed to enable this? It may be a simple fix to [scanHeaderValue](https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala#L482).

This is needed so we can fix #16821.

**Comment by jrudolph** [comment]
How hard would it be to allow specifying any kind of charset?

**Comment by sirthias** [comment]
I think we should simply enable UTF8 decoding for header values.
This would let us to use something like the [logic in the spray-json parser](https://github.com/spray/spray-json/blob/master/src/main/scala/spray/json/JsonParser.scala#L305) which shouldn't have any perceivable performance implications. I guess we could more or less copy the logic from spray-json.

I don't think support for other charsets is important enough to warrant the added complexity of configuration and implementation as well as the probably higher perf cost.

**Comment by drewhk** [comment]
I agree with @sirthias, UTF-8 should be enough in practice
