### ISSUE TITLE
[akka-http] Incorrect rejection is sent to the client

### ISSUE THREAD

**Issue by cppexpert** [akka/akka#18125]
I suspect it might be a bug. I have unauthenticated routes and authenticated routes in my Akka-Http DSL. Below is simplified version of the code

```scala
val nakedRoutes = pathPrefix("user") {
  post {
    entity(as[UserNew]) { user =>
      (validate(EmailValidator.getInstance().isValid(user.email), s"Invalid email address ${user.email}") & validate(!user.password.isEmpty, "Password should not be empty")) {
          complete {
            UserWire(new ObjectId(), user.firstName, user.lastName, user.email, user.company, user.role, new ObjectId())
            }
        }
    }
  }
}

val myAuthorization: Directive[Tuple1[String]] = (headerValueByName("X-API-Token") | parameter("token")).tflatMap[Tuple1[String]]{
    case Tuple1(token) => if (!token.isEmpty) provide(token.reverse) else complete(StatusCodes.Forbidden -> "API token is not provided")
  }

val authenticatedRoutes = myAuthorization { user =>
  get { complete { "" } }
}

val routes = (decodeRequest & encodeResponse) {
    authenticatedRoutes ~ nakedRoutes
  }
```

The idea is that user makes POST /user request, gets token and uses it for authenticated routes.

The problem I have is that when validation of email fails I get incorrect rejection

```
Request is missing required HTTP header 'X-API-Token'
```

Why doesn't it throw last occurred rejection ? How does it pick what rejection to return to the client ?

If I refer to [old Spray's doc](http://spray.io/documentation/1.2.3/spray-routing/key-concepts/rejections/#rejection-cancellation) I'd expect rejections generated by `myAuthorization` to be canceled because `post` directive allowed the request to pass.

http://stackoverflow.com/questions/31843253/incorrect-rejection-is-sent-to-the-client

**Comment by jrudolph** [comment]
You could see this as a general ambiguity problem in your code, expanding your route leads to:

```scala
val routes = 
  myAuthorization { user =>
    get { complete { "" } }
  } ~
  post {
    entity(as[UserNew]) { user =>
      (validate(EmailValidator.getInstance().isValid(user.email), s"Invalid email address ${user.email}") & 
       validate(!user.password.isEmpty, "Password should not be empty")) {
          // ...
       }
    }
  }
```

Both route alternatives generally apply but are rejected for different reasons. The logic of rejection cancellation you cite is that a former rejection *of the same kind* can be cancelled if a later directive *of the same kind* passes. 

But that's not the case here as authorization and validation produce different kinds of rejections. In this case the default behavior is to *handle the first rejection* that occurred. As you have found out yourself you can override the rejection handling behavior in many ways. 

Usually, you can also achieve the desired effect by reordering your directives in a way that puts the most important discriminators on outer levels while nesting more specific discriminators. 

In your case, your quite specific `myAuthorization` will be invoked in a catch-all manner that would apply to all requests. Instead, you could "guard" authentication by a path directive that prevents other requests from running into the authentication problem.

AFAICS this is no bug, so I'm closing this for now but feel free to continue the discussion here, on the ML, or on SO.

/cc @sirthias

**Comment by cppexpert** [comment]
Thank you for detailed answer! What do you mean by guarding authentication with path ? Do you mean putting auth endpoints under another URI segment such as `/authenticated/user` ?

Also could you please explain why following code fixes my problem ?

```scala
val myAuthorization: Directive[Tuple1[String]] = (headerValueByName("X-API-Token") | parameter("token")).tflatMap[Tuple1[String]]{
  case Tuple1(token) => if (!token.isEmpty) provide(token.reverse) else complete(StatusCodes.Forbidden -> "API token is invalid")
}.recover {
  case rejections => reject(ValidationRejection("API token is not provided"))
}
```

When I use code above I get proper rejections when use passed malformed email. Also out of curiosity I tried rejecting as `case rejections => reject(rejections.head)` and it resulted in wrong behavior again. So it's quite confusing.

**Comment by jrudolph** [comment]
> Do you mean putting auth endpoints under another URI segment such as /authenticated/user ?

Yes.

```scala
.recover { case rejections => reject(ValidationRejection("API token is not provided")) }
```

This means that you are discarding any existing rejections and replace them with your `ValidationRejection("API token is not provided")`. 

`recover { case rejections => reject(rejections.head) }` is almost the definition of the default behavior which you don't like. If you want some rejections to take precedence over other ones you need to inspect the complete list of rejections and choose one that suites your needs.

**Comment by cppexpert** [comment]
I'm not sure I understand. When I make post with malformed email I get two rejections in `.recover` block - `MissingHeaderRejection(X-API-Token)` and `MissingQueryParamRejection(token)`. `post` block generates `ValidationRejection(email)`.

So we have 3 scenarios

1) `MissingHeaderRejection(X-API-Token)` and `MissingQueryParamRejection(token)` vs. `ValidationRejection(email)`
2) `ValidationRejection("API token is not provided")` and `ValidationRejection(email)`
3) In in case of `rejections.head` we have `MissingHeaderRejection(X-API-Token)` and `ValidationRejection(email)`

To me scenarios 2 and 3 seem equivalent. Why Akka-Http chooses wrong rejection in case 3 as if `MissingHeaderRejection` has more weight than `ValidationRejection` ?

**Comment by jrudolph** [comment]
Yes, you are right. The logic changed from spray where the default rejection handler would prefer a rejection based on when it occurred. Now, the order of how rejections are handled depends on the order of handlers as defined in `RejectionHandler.Default`.

See this comment where I noticed the change: https://github.com/akka/akka/pull/16949#issuecomment-76368718

In any case, there are several ways to customize rejection handling and you have to choose one if the existing doesn't suite your needs.
