### ISSUE TITLE
Websocket: support reporting of close codes as they are received over the wire

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18129]
Small solution proposal: introduce a special exception that may carry the close code and will be reported by `onError` on the message stream. Regular closing of the connection will still be reported by `onComplete`.

/cc @jroper

**Comment by jrudolph** [comment]
The same mechanic could be used to actively close the connection by failing the stream with this exception parameterized with close code and reason.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
