### ISSUE TITLE
Akka Streams need a BackoffRequestStrategy

### ISSUE THREAD

**Issue by ckaratza** [akka/akka#18124]
Besides MaxInFlightRequestStrategy, OneByOneRequestStrategy, WatermarkRequestStrategy, ZeroRequestStrategy a backoffrequeststrategy could be handy in cases where infinite sources return no data and we don't want to spin on polling.
e.g. A kafka source using a SimpleConsumer will spin when topic has no data if using a  WatermarkRequestStrategy. A backoffrequeststrategy (exponential or not) could help

**Comment by drewhk** [comment]
I am not sure I understand what is the issue here. There is nothing in the Actors that does spinning, where does that come from? These request strategies about managing batches of requests to keep the receive buffer filled. There is no spinning anywhere.

**Comment by ckaratza** [comment]
Its not a bug sorry for the misunderstanding. Its a feature request that the backof strategy could be implemented as an out of the box option as WatermarkRequestStrategy, e.t.c. when publisher
sends no content.
At the moment I have used ZeroRequestStrategy and applied backouff my self after the OnNext message.

**Comment by drewhk** [comment]
Sorry, but I still not get the problem. Can you share a small code snippets that demonstrates your issue? I feel that there is a misunderstanding of the underlying model here.

**Comment by drewhk** [comment]
ActorPublisher and ActorSubscriber both implement proper backpressure, the request strategies only define when the next batch is requested to keep the internal buffer filled. It *always* respects backpressure, there is no need for backoff. I suspect that there is a misunderstanding here of the mechanics. I would be happy to help if there is actual code. I close this ticket though, let's discuss on the ML your problem if it is still relevant.
