### ISSUE TITLE
Sink.actorSubscriber() should verify the props?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#18133]
I think the props should be verified for the Actor should be a ActorSubscriber,or it was design to like that.

**Comment by ktoso** [comment]
Good catch, we can't always do it (if `Props(new ...)`) but for the class based one we can :)

**Comment by hepin1989** [comment]
then should make producer method privite[akka]

**Comment by agolubev** [comment]
@ktoso, should it be just verification if actor given in ActorSubscriberSink.props inherits ActorSubscriber?
Should the same be done for ActorPublisherSource?

**Comment by ktoso** [comment]
@agolubev both would benefit from doing such check (for their respective classes).

**Comment by hepin1989** [comment]
this one should be close now.

**Comment by ktoso** [comment]
True, thanks @hepin1989!

**Comment by hepin1989** [comment]
Why I am asking ```producer``` is once I really encounter that the type return ```Actor```,I just cann't rememer,maybe the java side.we will see :)
