### ISSUE TITLE
Make EventAdapter into ReadEventAdapter and WriteEventAdapter

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18137]
See here https://github.com/akka/akka/issues/18050#issuecomment-123756225

**Comment by patriknw** [comment]
@ktoso looks like this is related to #18050, so let's do those together after 2.4-M3

**Comment by ktoso** [comment]
Yes, let's do that.
The task here seems simple, though it has some implications on the code obtaining adapters, so it's a bit more involved thanjust "split the interface"
