### ISSUE TITLE
ActorSelection that addresses a TestProbe sporadically fails

### ISSUE THREAD

**Issue by swachter** [akka/akka#18149]
In an integration test I have a TestProbe that expects a message that is sent by a callback in an Actor called `ExecManager`. The ActorRef of the TestProbe is persisted using a string by

```java
String nextPath = TestProbe.ref().path().toStringWithoutAddress()
```

and later used in the callback to send a message to the TestProbe using

```java
ActorSelection as = context().system().actorSelection(nextPath);
as.tell(continueMsg, self());
```

The test iterates and uses the same TestProbe repeatedly. Sometimes the `as.tell` instruction fails the first time by sending the ```continueMsg``` straight to the dead letter box. Some other times the test iterates for a number of times successfully and suddenly fails.

Interestingly, it makes a difference, where the `exeManager` is instantiated. If the `execManager` is instantiated in the constructor of the test class then the test fails sporadically. If the `execManager` is instantiated in the test method then the test iterates 1000 times and does not fail. Here is the complete test class:

```java
@RunWith(classOf[JUnitRunner])
class ExecManagerIt extends TestKit(ActorSystem("test", ConfigFactory.load())) with FunSuiteLike
with BeforeAndAfterAll
with ImplicitSender  {
  
  //  when the execManager is created here, then the test sporadically fails
  val execManager: ActorRef = system.actorOf(Props[ExecManager], "execManager")

  test("a timed out execution") {

    // when the execManager is created here then test does not fail
//    val execManager: ActorRef = system.actorOf(Props[ExecManager], "execManager")

    val log = Logging.getLogger(system, "test")
    implicit val ec = system.dispatcher

    log.debug(s"############################ test a timed out execution ###")

    val nextActor = TestProbe()
    val nextActorRef = nextActor.ref
    val nextActorPathString = nextActorRef.path.toStringWithoutAddress
    log.debug("nextActorPathString: " + nextActorPathString)

    val actorSelection = system.actorSelection(nextActorPathString)

    log.debug(s"nextActor: ${nextActorRef.path}")

    println("started")
    for (i <- 1 to 1000) {

      actorSelection.resolveOne(1 seconds).onComplete {
        case scala.util.Success(r) => log.debug(s"actor selection could be resolved - as: $actorSelection")
        case scala.util.Failure(t) => log.error(t, s"actor selection could not be resolved - as: $actorSelection")
      }

      // the execution must have a short timeout value because we will wait for the timeout below
      execManager ! new RegisterMsg(nextActorRef, 1000)
      val execId = expectMsgType[String]

      log.debug(s"************ wait for ContinueMsg - execId: $execId")

      // expect a ContinueMsg

      try {
        println(s"i: $i")
        val continueMsg = nextActor.expectMsgType[ContinueMsg](10 seconds)

        log.debug("waited for ContinueMsg")

        assert(execId === continueMsg.execId)

      } finally {
        val as = system.actorSelection(nextActorPathString)
        as.resolveOne(1 seconds).onComplete {
          case scala.util.Success(r) => log.debug(s"actor selection could be resolved #2 - as: $as")
          case scala.util.Failure(t) => log.error(t, s"actor selection could not be resolved #2 - as: $as")
        }
      }
    }

  }

}
```

The described behaviour exists using Java 8 both, under Windows 7 and under Ubuntu 12.04.

Unfortunately the ```ExecManager``` needs a Mongo database in order to show the described behaviour. I tried hard to minimize it to no avail (e.g. use a ScheduledExecutorService in order to mimic the Mongo callbacks).

Maybe someone can still have a look on the problem. The complete test code is available under:
https://github.com/swachter/actor-selection

**Comment by patriknw** [comment]
I don't think it's guaranteed that an actor selection will see the destination actor immediately after it is created. It's more strange that you say that it first works and then suddenly fails. Anyway, we need a minimized reproducer without dependencies to external infrastructure to be able to investigate.
