### ISSUE TITLE
Streams Flow.mapAsync needs eager error capability on actor termination

### ISSUE THREAD

**Issue by DomBlack** [akka/akka#18142]
When you've got a mapAsync within a graph and the actor which has is being asked has been terminated, it would be very nice if we could eagerly error the stream, rather than waiting for the next element to trigger a timeout. (thus loosing the element).

This would allow supervision code outside of the stream, to watch for the actor termination, create a new instance and start a new instance of said stream.

**Comment by drewhk** [comment]
I think this is needs a more general solution, as in providing some better patterns for integration of external actors than mapAsnc+ask with richer capabilities (like DeathWatch).

**Comment by rkuhn** [comment]
This should come in two varieties:
~~~scala
def viaActor[T](props: Props): Repr[T] // will be more awesome with Akka Typed
def viaActor[T](ref: ActorRef): Repr[T] // same here
~~~
And these would watch the actor to propagate termination, and the first one would terminate the actor upon stream termination.

**Comment by drewhk** [comment]
viaActor[T](ActorRef) will prescribe a certain protocol I presume?

**Comment by rkuhn** [comment]
No, these are exactly like mapAsync but with lifecycle control.

**Comment by drewhk** [comment]
Ah, so the message is just forwarded to the actor, and any reply is just emitted unmodified? This is not exactly same as mapAsync as it does not handle parallelism (and ordering).

**Comment by rkuhn** [comment]
right, I simplified the signatures, sorry about that ;-)
