### ISSUE TITLE
failed: AdaptiveLoadBalancingRouterSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18156]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/78/consoleFull

**Comment by ktoso** [comment]
Different instance of the failure in https://github.com/akka/akka/issues/18071

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/54/consoleFull

**Comment by ktoso** [comment]
The `AdaptiveLoadBalancingRouter` fails with 

```

[JVM-1] [WARN] [07/15/2015 08:17:21.060] [AdaptiveLoadBalancingRouterSpec-akka.actor.default-dispatcher-17] [akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794/system/cluster/core/daemon] Cluster Node [akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022, status = Up)]
[JVM-3] [WARN] [07/15/2015 08:17:21.142] [AdaptiveLoadBalancingRouterSpec-akka.actor.default-dispatcher-14] [akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022/system/cluster/core/daemon] Cluster Node [akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794, status = Up)]
[JVM-1] [INFO] [07/15/2015 08:17:21.784] [AdaptiveLoadBalancingRouterSpec-akka.actor.default-dispatcher-17] [akka.cluster.Cluster(akka://AdaptiveLoadBalancingRouterSpec)] Cluster Node [akka.tcp://AdaptiveLoadBalancingRouterSpec@a0.moxie:33794] - Ignoring received gossip status from unreachable [UniqueAddress(akka.tcp://AdaptiveLoadBalancingRouterSpec@a6.moxie:37022,765315385)] 
[JVM-1] - must prefer node with more free heap capacity *** FAILED *** (21 seconds, 248 milliseconds)
[JVM-1]   2284 did not equal 3000 (AdaptiveLoadBalancingRouterSpec.scala:188)
[JVM-1]   org.scalatest.exceptions.TestFailedException:
[JVM-1]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$7.apply$mcV$sp(AdaptiveLoadBalancingRouterSpec.scala:188)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(AdaptiveLoadBalancingRouterSpec.scala:174)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(AdaptiveLoadBalancingRouterSpec.scala:162)
[JVM-1]   at akka.cluster.routing.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(AdaptiveLoadBalancingRouterSpec.scala:162)
[JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

I'll investigate it deeper;

---

I blame this on the environment... since the nodes become unreachable the test will fail, it's not that the behaviour is wrong. We could tweak settings I guess...?

**Comment by ktoso** [comment]
Here it's always that UNREACHABLE gets triggered in the middle of the test.
Here as well: https://jenkins.akka.io:8498/job/akka-multi-node/1134/consoleFull

The nodes can get reachable again, though that's not really helping as the requests were lost, so the count won't match up hm.

**Comment by ktoso** [comment]
Keeping as is – failures caused due to network issues on jenkins env.

**Comment by patriknw** [comment]
Here is another one. This time in `akka.cluster.metrics.AdaptiveLoadBalancingRouterSpec`
https://jenkins.akka.io:8498/job/akka-multi-node/1138/consoleFull

No unreachable, but some rather long GC

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/83/consoleFull

some unexpected unreachable again

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/95/consoleFull

ran on a0, but its a multi-node test so a5 and a6 are involved as well.
I think this test failure is very interesting to investigate for understanding the environment instability (or whatever it is). Why do we get unreachable here?

    Marking node(s) as UNREACHABLE

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/96/consoleFull

**Comment by patriknw** [comment]
The GC printing was not enabled on all those nightly jobs, but the akka-multi-node shows some heavy GC that might be the reason for the unreachable. I'll increase the failure detector timeout, since this tests is supposed to stress the memory.

**Comment by patriknw** [comment]
It still fails after the increased failure detector timeout. Still unreachable.
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2829/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2640/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2756/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2846/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2950/consoleFull
