### ISSUE TITLE
FAILED:  sample.distributeddata.ReplicatedCacheSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18159]
https://jenkins.akka.io:8498/job/akka-nightly/2440/consoleFull

// split out from https://github.com/akka/akka/issues/18071

**Comment by patriknw** [comment]
that link does not exist (for me)

**Comment by ktoso** [comment]
Hmmm... me neither actually. Copied it from the ticket linked, not sure what's wrong here, closing I guess.

**Comment by patriknw** [comment]
yup
