### ISSUE TITLE
Docs: More prominently document how to use Akka behind NAT

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18163]
We have it explained in http://doc.akka.io/docs/akka/2.4-M2/general/remoting.html#Peer-to-Peer_vs__Client-Server however it seems it's hard to find there. It deserves it's own section in `remoting.rst`

**Comment by patriknw** [comment]
@johanandren was this issue on your list? Could you do it? Rather important since this is new feature in 2.4.

**Comment by johanandren** [comment]
Absolutely!
