### ISSUE TITLE
PersistentFsmActor should look more like actor.FSM

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18168]
Some small fixups to make PersistentFSM more consistent with FSM:

- For normal actors users write `A extends FSM[]` (note not Actor in there),
the persistent version should therefore be `A extends PersistentFSM[]` (not `PersistentFsmActor`).
- Improve placement of `State` etc classes. In the plain version they are all accessible when `import FSM._`, in the persistent version it was confusing because the class was `PersistentFsmActor`, yet all messages were defined in `persistence.fsm.FSM`, thus you extended `PersistentFsmActor` but needed to import `FSM._`; This is solved by moving all types to the `PersistentFSM` companion object

**Comment by ktoso** [comment]
@leonidb I needed to move some classes around to increase consistency between FSM impls, hope this makes sense :) These changes are the 2nd commit in https://github.com/akka/akka/pull/18166

**Comment by leonidb** [comment]
@ktoso 
```PersistentFSM``` extends ```PersistentFSMBase```:
```scala
trait PersistentFSM[S <: FSMState, D, E] extends PersistentActor with PersistentFSMBase[S, D, E] with ActorLogging {
```
At the same time ```PersistentFSMBase``` imports the classes inside ```PersistentFSM``` companion object
```scala
trait PersistentFSMBase[S, D, E] extends Actor with Listeners with ActorLogging {

  import akka.persistence.fsm.PersistentFSM._
```
Although companion object is technically not related to inheritance, I find this kind of confusing, I'm not familiar enough with Scala's best practices. Is this OK?

**Comment by ktoso** [comment]
Thanks for chiming in! Allow me to explain why I wanted to introcude this change - I was more concerned about "what users need to know to use this API" in this change.

I.e. previously:
- user knows FSM
- user wants to use kind-a-like-FSM but for persistence
- needs to realise it's PersistentFsmActor (2 unexpected changes: FSM -> Fsm and Suddenly Actor in the name)
- for getting the `State` class etc, user needs to realise that they are defined in `akka.persistence.fsm.FSM` and import that (so it's surprising)

After the change:
- user knows FSM
- user wants to use kind-a-like-FSM but with Persistence
- user knows that `Actor + persistence = PersistentActor`, can guess that `FSM + persistence = PersistentFSM` may be it. (consistent)
- now user needs to import messages, is used to importing "companion" (from his point to view at least), so `import PersistentFSM._` (consistent)
- for Java API it is not directly the same, inside `AbstractPersistentFSM` one has to import `PersistentFSM`, but I'd argue that's simple to get as well "simply strip the Abstract" as users know that this is how we roll Java APIs for Actors :)

From our perspective you're right that the "Base" is using things from not "it's own companion" ("companion" is a well defined term = the `object` with the same name (in same compilation unit) as a `class`), but I think that's Ok.

Down the line I'd like to maybe be able to scratch the Base class... we'll see if that's possible during our cleanups I guess :-)

Hope this makes sense :-)

**Comment by leonidb** [comment]
Yes, it does male sense, thanks.

**Comment by ktoso** [comment]
Cool, glad it makes sense and I'm not just imagining it :-)
