### ISSUE TITLE
FAILED: LightArrayRevolverSchedulerSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18160]
https://jenkins.akka.io:8498/job/akka-nightly/2449/consoleFull

Split out from https://github.com/akka/akka/issues/18071

**Comment by ktoso** [comment]
The scheduler spec failed tight around the timeout:

```
akka.actor.LightArrayRevolverSchedulerSpec

[info] - must not be affected by long running task *** FAILED *** (5 seconds, 521 milliseconds)
[info]   4.002183008913953 did not equal 4.4 plus or minus 0.3 (SchedulerSpec.scala:254)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
this was on a0
```

It's a pretty timing sensitive test:

```scala
      val startTime = System.nanoTime
      val n = 22
      val latch = new TestLatch(n)
      system.scheduler.schedule(225.millis, 225.millis) {
        Thread.sleep(80)
        latch.countDown()
      }
      Await.ready(latch, 6.seconds)
      // Rate
      n * 1000.0 / (System.nanoTime - startTime).nanos.toMillis should ===(4.4 +- 0.3)
```

I'd leave as is as it has not reappeared

**Comment by ktoso** [comment]
cc @patriknw

Leave as is or increase tolerance?

**Comment by 2m** [comment]
Still failing: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2976/consoleFull

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time

**Comment by jrudolph** [comment]
Happened once again:

https://jenkins.akka.io:8498/job/akka-nightly/5203/testReport/junit/akka.actor/LightArrayRevolverSchedulerSpec/A_Scheduler_must_not_be_affected_by_long_running_task/

**Comment by raboof** [comment]
This test is indeed rather timing-sensitive and was already tagged 'timing' - perhaps we want to `-Dakka.test.tags.exclude=timing` on Jenkins?

**Comment by jrudolph** [comment]
But where would they run instead?

**Comment by patriknw** [comment]
obsolete
