### ISSUE TITLE
FAILED: LeveldbPersistentFSMActorSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18162]
Split out from https://github.com/akka/akka/issues/18071
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2655/consoleFull

// also `a0`

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2766/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2838/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2844/consoleFull

**Comment by ktoso** [comment]
Related one is: https://github.com/akka/akka/issues/18236#issuecomment-136366239 (closed it as duplicate)

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
