### ISSUE TITLE
Add eagerFinish option to Merge

### ISSUE THREAD

**Issue by jroper** [akka/akka#18175]
Similarly to the way `Broadcast` has an `eagerCancel` option, `Merge` could have an `eagerFinish` option.  My use case is for when I have a third party provided `Flow`, and I want to wrap it with something that allows messages to bypass the user provided `Flow`.  I apply an `In => Either[FlowIn, Out]` function, broadcast the stream, `collect` the bypassed side and feed it straight into a merge, and collect the non bypassed side and feed it through the third party provided `Flow` then into the merge.  The problem is, when the third party flow finishes, nothing happens, since my bypass flow doesn't finish, and has no way of knowing that the third party flow has finished.

The current work around I have in place for this is to fail the stream with a particular exception, and then recover after the merge to transform that exception into a finish, it looks like this:

```scala
  /**
   * Using the given splitter flow, allow messages to bypass a flow.
   *
   * If the splitter flow produces Left, they will be fed into the flow. If it produces Right, they will bypass the
   * flow.
   */
  def bypassWith[In, FlowIn, Out](splitter: Flow[In, Either[FlowIn, Out], _]): Flow[FlowIn, Out, _] => Flow[In, Out, _] = { flow =>

    splitter via Flow[Either[FlowIn, Out], Out]() { implicit builder =>
      import FlowGraph.Implicits._

      val broadcast = builder.add(Broadcast[Either[FlowIn, Out]](2, eagerCancel = true))
      val merge = builder.add(Merge[Out](2))

      
      // This is needed because Merge does not have an eagerFinish option, it won't finish until all
      // upstreams are finished.
      val convertFinishToFailure = Flow[Out].transform(() => new PushStage[Out, Out] {
        def onPush(elem: Out, ctx: Context[Out]) = ctx.push(elem)
        override def onUpstreamFinish(ctx: Context[Out]) = ctx.fail(EagerFinish)
      })

      // Converts the EagerFinish failure from the above flow back to a normal finish.
      val convertFailureToFinish = Flow[Out].transform(() => new PushStage[Out, Out] {
        def onPush(elem: Out, ctx: Context[Out]) = ctx.push(elem)
        override def onUpstreamFailure(cause: Throwable, ctx: Context[Out]) = cause match {
          case EagerFinish => ctx.finish()
          case other => ctx.fail(other)
        }
      })
      
      // Normal flow
      broadcast.out(0) ~> Flow[Either[FlowIn, Out]].collect {
        case Left(in) => in
      } ~> flow ~> convertFinishToFailure ~> merge.in(0)

      // Bypass flow, need to ignore downstream finish
      broadcast.out(1) ~> Flow[Either[FlowIn, Out]].transform(() => new PushStage[Either[FlowIn, Out], Out] {
        def onPush(elem: Either[FlowIn, Out], ctx: Context[Out]) = elem match {
          case Right(out) => ctx.push(out)
          case Left(_) => ctx.pull()
        }
        override def onDownstreamFinish(ctx: Context[Out]) = ctx.absorbTermination()
      }) ~> merge.in(1)

      broadcast.in -> (merge.out ~> convertFailureToFinish).outlet
    }
  }

  private case object EagerFinish extends RuntimeException(null, null, false, false)
```

**Comment by jroper** [comment]
Unfortunately, I've just found the work around posted above doesn't work - the failure is able to overtake messages sent by the same flow.  I'll have to implement something where the completion is sent as a regular message.

**Comment by drewhk** [comment]
Can't you use a FlexiMerge for this?

**Comment by jrudolph** [comment]
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/ws/Websocket.scala#L100

**Comment by jroper** [comment]
@drewhk Thanks for pointing this out, here's the code if anyone needs it:

```scala
  private case class EagerFinishMerge[T](inputPorts: Int) extends FlexiMerge[T, UniformFanInShape[T, T]](new UniformFanInShape[T, T](inputPorts), Attributes.name("EagerFinishStage")) {
    def createMergeLogic(s: UniformFanInShape[T, T]): MergeLogic[T] =
      new MergeLogic[T] {
        def initialState: State[T] = State[T](ReadAny(s.inSeq)) {
          case (ctx, port, in) ⇒ ctx.emit(in); SameState
        }
        override def initialCompletionHandling: CompletionHandling = eagerClose
      }
  }
```

**Comment by jrudolph** [comment]
Ah, the use-case for the stage I posted above was actually the other way round: it was necessary to prevent that other stages are completed or cancelled eagerly.

**Comment by drewhk** [comment]
new, more flexible (and more dangerous ;) ) custom graph processing stage support is coming (in progress already), so it will be easier to do custom variations on existing things, or creating arbitrary new stages. I hope I can get it in soon, so it makes both of your lifes easier :)

**Comment by jroper** [comment]
Upgrading to Akka streams 2 now - question, how does `GraphStage` make the 9 lines of code that I implemented above simpler?  It looks like to use it I have to reimplement hundreds of lines of code that `FlexiMerge` used to do for me.

**Comment by jroper** [comment]
Actually, I can see that this feature request was actually implemented in Akka streams 2, so I don't need to implement a custom merge.

That said, I have an OnlyFirstCanFinshMerge that I wrote, and that looks like it's going to be a lot harder to do.

**Comment by jroper** [comment]
Yes, it doesn't seem that stages like Merge are composable, since I can't intercept or replace handlers at all, which means anyone that used to have a simple custom merge with just a small modification to behaviour such as how finish is triggered, now has to reimplement all the logic in Merge in order to achieve that.  Or am I wrong?

**Comment by drewhk** [comment]
> Yes, it doesn't seem that stages like Merge are composable

Stages are composable. Stage internals are not. Slight but important difference.

> since I can't intercept or replace handlers at all, which means anyone that used to have a simple custom merge with just a small modification to behaviour

You can do these thing. In fact there are quite a lot of helper methods (`emit` and friends) that actually do these. Unfortunately the reference docs do not yet mention these, but this will be fixed.
