### ISSUE TITLE
Parallelism incorrect on http super pool

### ISSUE THREAD

**Issue by ryandbair** [akka/akka#18174]
The parallelism value in clientFlow is set as the product of ConnectionPoolSettings' pipeliningLimit and maxConnections[1] which are both defined as being per host. 

superPool only creates one client flow for all connected hosts so the parallelism becomes global to the superPool instead of per host. 

[1] https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0/akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala#L481

**Comment by jrudolph** [comment]
I have just glanced over the code but it seems you are right. I wonder if this can be fixed in code or if it's just the documentation / definition of `max-connections` needs to be updated.

/cc @sirthias

**Comment by sirthias** [comment]
@ryandbair Yes, you are right. Things are not quite right currently in this respect.
IMHO the perfect solution would be to use a superpool parallelism factor that is the sum of the `max-connection` settings of all pools that are currently being used by the super-pool flow.
However, this would require dynamic adjustment of the parallelism factor, which is currently not supported by `mapAsync`. We need to set a static parallelism factor a priori, *before* knowing how many pools will actually be used concurrently by the user (via the produced client-flow).

It doesn't look like there is a good heuristic to spare the user from supplying this superpool parallelism herself. I guess we'll have to add an explicit `parallelism` parameter to the `superPool` method.

**Comment by ktoso** [comment]
Sounds like this can be split into two steps,
1) document current behaviour to not cause confusion 
2) we could make the dynamic version if we get a "dynamic parallelism" mapAsync

WDYT on the 2nd point? // cc @drewhk

**Comment by sirthias** [comment]
What about adding a new `parallelism` parameter to the `superPool` method?

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
