### ISSUE TITLE
[akka-streams] Java DSL: FlattenStrategy.concat() cannot be called on Source<T, ?>

### ISSUE THREAD

**Issue by jypma** [akka/akka#18181]
We're doing an akka http request for every element in a stream, where the response is mapped into a nested source. Since the return type (in the Java DSL) for `HttpResponse.entity().getDataBytes()` is `Source<ByteString, ?>`, I now have a stream of type `Source<Source<ByteString, ?>, M>`. The latter M is of no consequence.

I'd like to flatten the stream. However, the signature of `javadsl.FlattenStrategy.concat` is defined as 

```
def concat[T, U]: FlattenStrategy[Source[T, U], T]
```

which poses two problems:
- Since the generic method arguments don't directly translate to generic type arguments on the return type, Java won't use type inference, and you have to spell out the types in an expression like `FlattenStrategy.<ConcreteT,ConcreteU>concat()`.
- There is no way to express `ConcreteU` for a `Source<T, ?>` that has an existential type on it.

Since we can't make Java's type inference smarter, I think the only solution is to have `HttpResponse.entity().getDataBytes()` return a concrete materialized type, even if `Unit`. That'll allow us to at least have a valid expression when calling `.concat()` later.

**Comment by drewhk** [comment]
Is this fixed by https://github.com/akka/akka/pull/18809 ?

**Comment by ktoso** [comment]
Yes, I think so, it's the same problem as https://github.com/akka/akka/issues/18806 which  https://github.com/akka/akka/pull/18809 resolved
