### ISSUE TITLE
Investigate semantics of state timeouts in PersistentFSM

### ISSUE THREAD

**Issue by leonidb** [akka/akka#18207]
Related to #17959, mentioned in  https://github.com/akka/akka/pull/17974#issuecomment-130554047 and https://github.com/akka/akka/pull/17974#issuecomment-130559219:

In the regular `FSM` every command handled by the actor resets the timeout, and then the new state either sets the timeout again or leaves it as is - undefined or state default.

`PersistentFSM` stores the defined state timeout as part of `StateChangeEvent`. Following the #17959 fix, `PersistentFSM` doesn't store a `StateChangeEvent` if `PersistentFSM` stays in the same state, doesn't emit any domain events and does not set a state timeout. 

Example of the difference between `FSM` and `PersistentFSM` timeout behavior, based on `akka.persistence.fsm.PersistentFSMSpec.WebStoreCustomerFSM`:
1. `AddItem` is handled -> `StateChangeEvent` is persisted, setting a timeout to 1 sec
2. `GetCurrentCart` is handled -> `StateChangeEvent` is not persisted since the event doesn't cause a state to change, doesn't emit any domain events and doesn't set the timeout to anything.
   In `FSM` flow not setting timeout resets the previously set timeout.
   Following the #17959 bug fix `PersistentFSM` doesn't store the `StateChangeEvent`, leading to recovery with the timeout of 1 sec.

Alternatively, this can be considered a valid behavior, since in `PersistentFSM` events that don't affect domain and don't change state shouldn't normally reset receive timeout.

**Comment by ktoso** [comment]
Thanks for the ticket @leonidb!
