### ISSUE TITLE
failed: NodeChurnSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18211]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/84/consoleFull

**Comment by patriknw** [comment]
It's a timeout when joining (12 did not equal 18). I could just increase the timeout at L65, but it's strange that it takes more than the default 25 seconds. Might be due to similar test env slugginess as we have seen in other tests.

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/88/consoleFull

**Comment by patriknw** [comment]
this can probably be explained by the too small ReservedCodeCacheSize, closing
