### ISSUE TITLE
Enhance documentation on "how to import akka project with IntelliJ"

### ISSUE THREAD

**Issue by Tooa** [akka/akka#18221]
Hi,

I suggest to improve the documentation here  [1] - See section: *Using Akka with IntelliJ IDEA*. Adding additional comments on where (which folder) to execute the `gen-idea` command on and the fact that the root project needs to be **opened** (not imported) instead of one of the sub-projects. 

I struggled myself to import the akka project with IntelliJ. Thanks to the nice akka developers in the channel ;)

[1] http://doc.akka.io/docs/akka/snapshot/intro/getting-started.html

**Comment by ktoso** [comment]
Thanks for the ticket :)
Seems like we can recommend to use the latest intellij and there `import` just works (as discussed on gitter).
