### ISSUE TITLE
PersistenceQuery: ReadJournal plugin API discussion

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18229]
Please put your thoughts and ideas on improving the ReadJournal plugin api here.
We're not happy yet with the API and it might change according to gathered feedback.

**Comment by ktoso** [comment]
Feedback from @scullxbones

 > Probably not the ideal spot to discuss, but the context of the discussion between @ktoso and @rkuhn is helpful.
> 
> I started to implement a `ReadJournal` today for my mongo journal and the `query` method seemed a bit off.  The casting wasn't great, but also I didn't really like communicating with the user that a query was not supported via exception.  More type-safety would be nice.
> 
> Intuitively this seems like a good spot for typeclasses.  I'm thinking that the (read) journal implementers would provide implicit objects as witnesses for the queries they support, e.g.
(Excuse the hastily put together pseudo-pseudocode, there must be a better signature to remove the extra T & M parameters on the trait)

> ```scala
package akka.persistence.query
abstract class ReadJournal { 
...
trait SupportedQueryWitness[A <: Query[T,M],T,M]
}
> 
package my.read.journal
object SupportedQueries {
  implicit object allPids extends SupportedQueryWitness[AllPersistenceIds,String,Unit]
}
```
> 
> Then `ReadJournal.query` could require a witness for that `Query[T,M]` to be in implicit scope.  The downside of this I see is that the user of the read journal needs a compile-time dependency on the journal implementation, rather than the typical run-time approach.  Of course they may need this anyways for more interesting `Query[T,M]`s.
> 
> Anyways, just some initial reactions.  Thanks for all the work you do, it's greatly appreciated!

**Comment by ktoso** [comment]
Note to self / food for thought: Maybe if we take the `match` part upon ourselves we could provide a well typed DSL for handling the messages... It would also deal with "whoops, this journal does not support X" better.

**Comment by scullxbones** [comment]
Somewhat unrelated, but for portability between plug-in implementations, I can see that the tagging support in 

https://github.com/akka/akka/pull/18277

Could be useful to move into the core. 

My thought process is that users start off with level db in development and move on to something else as their product requires for scale. As part of this process it would be nice to not have to reintegrate with different ways of doing tagging. The event adapter / tag approach is pretty clean from what I saw.

**Comment by patriknw** [comment]
I agree with @scullxbones . Moving `Tagged` to `akka.persistence.journal` would make it easier to align journal implementations, but it should still be an optional way of doing tagging.

**Comment by scullxbones** [comment]
What I'm discovering as I write queries for `ReadJournal` is that there's an opportunity here to unify Read & Write on the plugin side.  This simplifies the plugin writer's job, and carries the added bonus of adding backpressure (via streams) to both the batch append as well as recovery.  Right now I provide backpressure via `CircuitBreaker` and it has proved counter-intuitive to users as to how to handle breaker-open exceptions.  That said I just found `BackoffSupervisor` in the docs, which will simplify this use case quite a bit in 2.4.

The unified interface might look something like:

```scala
trait AsyncJournal extends ... {
// ...elided...

  // Replaces asyncWriteMessages, not sure about the parameter - was thinking ActorRef might be too restrictive
  def writeMessages[T]: Sink[AtomicWrite,T]

  // Replaces asyncReplaceMessages in AsyncRecovery with back-pressure plus gives EventsByPersistenceId implementation( using from 0L and to Long.MaxValue)
  // EventEnvelope or PersistentRepl?  There's something to be said for consistency
  def queryEventsByPersistenceId(persistenceId: String, fromSequenceNr: Long, toSequenceNr: Long): Source[EventEnvelope,Unit]

  // Support for AllPersistenceIds query from read side
  def queryAllPersistenceIds: Source[String,Unit]

  // Current ReadJournal interface.  Possibly keep this separated for only custom queries implemented by journal?
  def query[T, M](q: Query[T, M], hints: Hint*): Source[T, M]

  // Existing AsyncWriteJournal method
  def asyncReadHighestSequenceNr(processorId: String, fromSequenceNr: Long): Future[Long] 

  // Existing AsyncWriteJournal method
  def asyncDeleteMessagesTo(persistenceId: String, toSequenceNr: Long): Future[Unit]

  // Existing AsyncWriteJournal method
  def receivePluginInternal: Actor.Receive
}
```

There may be a way to stick tagging in here as well, but that may be too much for some journals to support.  Between `AllPersistenceIds` and `EventsByPersistenceId`, there should be enough support to create necessary read projections with less custom code than 2.3.x.

WDYT?

**Comment by ktoso** [comment]
Thanks a lot for the continued feedback! Sadly on this idea I don't think we'll be able to consider it (for 2.4.0), for a number of reasons: 
1) the write-side must really be stable right now, it is too late to breakingly change this API once more – we can introduce new ones for writing in the future though (see note below)
2) streams are still experimental, which makes them impossible to use in a stable module (which is why it is not streams based currently)

Making the write-side a Sink is something we'd like to provide, though it would probably be a new feature/api instead of changing the existing one (in API breaking ways), we have discussed it a bit in https://github.com/akka/akka/issues/16332 (and also in the cassandra plugin impl, can't find the ticket right now though) - it's code name is `PersistentWriter`, but we have not prototyped it yet.

**Comment by scullxbones** [comment]
@ktoso thanks, the need to keep things stable makes sense to me.

And now @patriknw 's comment about `PersistentWriter` I understand much better.  Sometimes the first time things don't stick, but the second time around is much better :smile: 

For now I think I will just go ahead and implement the Sink in my journal extension.  Perhaps my users may have some generally-useful feedback for the team.

**Comment by ktoso** [comment]
> For now I think I will just go ahead and implement the Sink in my journal extension. Perhaps my users may have some generally-useful feedback for the team.

Cool idea, the more feedback we gather the better and can converge on the writer API from that :smile:

**Comment by patriknw** [comment]
I think the idea with implicit witness is interesting, but it becomes a bit complicated with the types as far as I can see.
We can't do that for the Java API anyway and there might be interop problems between java scala implementations/users.

I think we should start out simple and see where this goes. It's experimental after all.

I can't see that the runtime check is a big problem in practise since the semantics of the queries may be different between different implementations anyway and you must therefore consult documentation anyway, and that is very much intentional.

A read journal implementation is free to define its own query types, also for the prescribed "standard" queries.

An alternative approach would be to not have any concrete query types, but make the "standard" query types abstract and thereby require that the journal impl provide the concrete impl if it supports the query.

**Comment by scullxbones** [comment]
Fair enough.  Your java point is well taken.  I had one more thought on the type-safe approach before I let it go, because I think lots of developers use their IDE code completion as documentation :smile:

What if each of the standard query types, instead of being a case class were represented as a single-method interface, e.g.

```scala
trait AllPersistenceIdsQuery {
  def allPersistenceIds(hints: Hint*): Source[String,Unit] 
}

trait EventsByPersistenceIdQuery { 
  def eventsByPersistenceId(persistenceId: String, from: Long, to: Long, hints: Hint*): Source[EventEnvelope,Unit] 
}

trait EventsByTagQuery { 
  def eventsByTag(tag: String, offset: Option[Long] = None, hints: Hint*): Source[EventEnvelope,Unit] 
}
```

The read journals would choose which of these interfaces to mix in, and the application could then perform direct dispatch.  This would require some casting somewhere along the line, possibly as part of the `PersistenceQuery(system).readJournalFor` call.

```scala
val readJournal = PersistenceQuery(system).readJournalFor[MyCoolReadJournal]("akka.persistence.query.my-cool-read-journal")

// Instead of this:
val blueThings: Source[EventEnvelope, Unit] = readJournal.query(EventsByTag("blue"))

// Support this:
val blueThings: Source[EventEnvelope, Unit] = readJournal.eventsByTag("blue")
```

I don't know what would be done with `ReadJournal` at that point.  Custom queries implemented by journals would and could be type-safe, but there would only be a loose guideline that they return a `Source` and take `Hint`s as one of the parameters.  I don't have a fully formed thought on that yet.

**Comment by patriknw** [comment]
@scullxbones I like that idea. I would perhaps go one step further and remove the `PersistenceQuery.readJournalFor` altogether and let the query plugin implement an ordinary [Akka Extension](http://doc.akka.io/docs/akka/2.4.0-RC2/scala/extending-akka.html)

Then it would look like:

    val readJournal = MyCoolReadJournal(system)

    val blueThings: Source[EventEnvelope, Unit] = readJournal.eventsByTag("blue")

The MyCoolReadJournal extension can implement the standard query interfaces that it supports and it can add more methods.

The only issue is Java/Scala interop (again). A query plugin should support both java and scala api, and it should be possible to implement in both java and scala. The `akka.stream.scaladsl.Source` is a different type than `akka.stream.javadsl.Source`.

Those have nice converter methods `asScala` and `asJava` but that is probably not something the user should care about. So the query extension need two methods for each query, or provide two different extensions. Anyway, I don't think that is a big deal.

**Comment by rkuhn** [comment]
The solution we have in store for the Java/Scala aspect is called `Graph[SourceShape[T], M]`; I also like this idea better than the Query/Hint style.

**Comment by patriknw** [comment]
There is one (maybe small?) drawback with using ordinary extension. That is that it's not possible to have more than one query plugin instance for the same backend, e.g. you might have two different Mongo instances with different configuration.

A nice thing with the `PersistenceQuery.readJournalFor` is that it is possible to do this:

    val tagQuery = PersistenceQuery(system).readJournalFor[EventsByTagQuery]("akka.persistence.query.my-cool-read-journal")

**Comment by rkuhn** [comment]
Yes, agreed. And the type parameter then achieves the same level of type-safety.

**Comment by patriknw** [comment]
@scullxbones I took a stab at this, please take a look at PR https://github.com/akka/akka/pull/18464

**Comment by patriknw** [comment]
@rkuhn I don't see how `Graph[SourceShape[T], M]` would help here. End user want access to the flow ops.

**Comment by rkuhn** [comment]
There should be a `Source.wrap()` that turn that Graph into a proper Source for the respective DSL; it’s either that or having the plugin implement both variants. For Scala we can even provide an implicit conversion that does the wrapping (but that should be imported explicitly since it is an actual conversion with object allocations).

**Comment by patriknw** [comment]
ok, I think the best for the user is to have separate scaladsl and javadsl api to be able to hand out proper `Source`. The downside is some duplication on our side, and plugin implementor must implement both, one via delegation to the other.

**Comment by rkuhn** [comment]
Makes sense, let’s try that first.

**Comment by patriknw** [comment]
this has been solved by other issues
