### ISSUE TITLE
Code restructuring to help Akka.js

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18234]
This ticket outlines our strategy that we'll want to follow to include [akka.js](https://github.com/unicredit/akka.js) needed changes into the akka/akka repository such that we can:
- understand the total impact of these changes before merging into `master`
- keep akka/akka's `master` branch during our `2.4.0-RC#` phase undisturbed by any PRs which are not strictly related to the RC,
- and at the same time do not block the development of akka.js while do so.

As discussed, we do want to help akka.js in the effort, however need to do this without impacting the RC phase of 2.4.0.

The plan is:
- to use the **[akka-js-dev](https://github.com/akka/akka/tree/akka-js-dev) branch on akka/akka** as target for app PRs which are needed for Akka.js to proceed swiftly
- target Akka.js PRs to that branch (can be as one long-running PR, or as multiple ones), in order to get an overview how much impact it has
  - if there is some PR we can not accept, we can safely not merge it there and other ones we can merge ASAP

We commit to:
- review the incoming PRs as they come in (early feedback),
- rebase the `akka-js-dev` branch regularly (or cherry-pick to it) such that it does not get out of sync with `master` too much,
- eventually (most likely after RC phase?) merge in as much of the changes as possible (with the caveat that we may not be able to include all PRs, we'll try to include as much as we can though)

Some references to previous discussions:
- https://github.com/unicredit/akka.js/issues/23 - explains techniques used by akka.js to keep compat
- https://github.com/unicredit/akka.js/issues/14 some good ideas how the impact could be minimised with some sbt magic (in the akka.js projects)

// pinging interested parties: @andreaTP @yawnt @patriknw and FYI @rkuhn (on vacation :tropical_drink: currently :wink:)

**Comment by andreaTP** [comment]
:+1:

**Comment by yawnt** [comment]
looking good! thank you :+1:

**Comment by ktoso** [comment]
I'm happy that you're happy with the plan :smile: 
Let's make it a reality then :-)

**Comment by ktoso** [comment]
**Strategy update:**

- we're going to cherry pick the changes from the akka-js branch onto master (I'll do that)
- akka.js team can issue PRs onto `master` from now on :-)
  - and we'll work on getting them in

Good luck on the presentation @andreaTP, liked the demo, there clearly is a lot of potential there! :-)

**Comment by andreaTP** [comment]
That's great!
:satisfied:

**Comment by ktoso** [comment]
I'll close this ticket, cherries are on master now and feel free to submit more PRs onto master.

**Comment by andreaTP** [comment]
great I'm currently working on ActorSystem, it will take ;-)

**Comment by ktoso** [comment]
good luck and godspeed :smile:
