### ISSUE TITLE
AbstractActorWithStash#unstashAll not usable with Java 8

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18244]
> I would like to use in a AbstractStashActor in java unstashAll(Predicate) . unstashAll((a) -> a == 7) doesn't work. What class should I use in java for the predicate?

**Comment by ktoso** [comment]
Copying my reply from gitter:

seems like an omission in the overloads... would you mind opening a ticket for it?
one answer is "once we compile using Scala 2.12 that should work", another answer is we can add an overload in the RC this friday  please open a ticket and we'll decide

// cc @jvieten

**Comment by patriknw** [comment]
unstashAll(Predicate) is INTERNAL API

**Comment by ktoso** [comment]
Oh, I missed that somehow. Since internal, this ticket is invalid.
AFAIR it's internal to prevent stash abuse?

// cc @jvieten
