### ISSUE TITLE
New 2.3.x release

### ISSUE THREAD

**Issue by benmccann** [akka/akka#18249]
Hi, can we get a new 2.3.x release? I'm hoping to use the permgen fix that was recently committed. Thanks!

**Comment by patriknw** [comment]
We will release it when we have accumulated enough critical things. In the mean time you can use the timestamped snapshot with version number `2.3-20150818-194852` that I triggered for you yesterday. In repo: http://repo.akka.io/snapshots/

Or use 2.4-M3

**Comment by ktoso** [comment]
This is more of a question than a ticket. Please direct questions to akka-user instead.
Timelines @patriknw explained so I'll go ahead and close the ticket.

**Comment by benmccann** [comment]
Thanks. I appreciate the snapshot release. Unfortunately, we can't typically depend on snapshot releases in Play, but it is helpful for testing. Hopefully, we can get a final release soon as well. I'll post on the users list next time

**Comment by hepin1989** [comment]
@benmccann You could pulish locally I think.

**Comment by benmccann** [comment]
@hepin1989 yes, I could, but that would only work for me. We're looking to fix this in Play for all Play users

**Comment by hepin1989** [comment]
@benmccann Akka 2.4.0 final release is comming,so does Play 2.5.0,so I think that should works,and for the akka 2.3.13,I think you should just waiting for a little logger,I think.

**Comment by benmccann** [comment]
@hepin1989 Play 2.5 is supposed to come out in November (unless I missed a schedule change). And it uses Akka 2.3 anyway. Plus we will need to fix older versions of Play regardless. Play 2.4 will never be upgraded to Akka 2.4, so we will need a new Akka 2.3 release eventually

**Comment by patriknw** [comment]
You can change to a newer Akka version that is backwards binary compatible with the version that Play was built with.

Akka 2.4.x is backwards binary compstible with Akka 2.3.x.

In other words you should be able to use Play 2.4 with Akka 2.4!

2.3.13 will be released soon, but we are in progress of verifying one bug fix first.

**Comment by hepin1989** [comment]
I am using akka 2.4 rc1 with cluster tool with play 2.4 without any probleam.

**Comment by benmccann** [comment]
Thanks for the update!
