### ISSUE TITLE
Port Specs2RouteTest from spray

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18246]
This would require at least a `provided` dependency on spec2(-core) from `akka-http-testkit`. That's no problem right now but it was hinted that Scala dependencies are problematic when akka-http is merged into master.

Providing a specs2 route testing module would simplify migration from spray a lot (we alone spent weeks just porting tests from specs2 to scalatest), also see the [ML](https://groups.google.com/d/topic/akka-user/Ml1pM652_e8/discussion). Until the merge to master, we could provide the simple glue code directly in `akka-http-testkit`. For the merge to master this code could be split out to an extra out-of-repository module.

WDYT?

/cc @sirthias

**Comment by ktoso** [comment]
A `provided` dependency should not be a problem actually I think, it should not affect our build too much (well, a bit more downloading but that's it).

I'd +1 this, since it would ease the migration path for existing projects.

**Comment by drewhk** [comment]
I think in this case we can live with the provided dependency.

**Comment by adamdecaf** [comment]
FYI I've had some good success with porting it over in my application until this is resolved. Here's a minified example: https://gist.github.com/adamdecaf/f83c7000d1b69bc29c4d

**Comment by jrudolph** [comment]
@ktoso previous reasoning was that external Scala dependencies aren't allowed in akka master because then the Scala stack couldn't be released without third parties updating their libraries first => circular dependency. Has that changed? Or is there an exception for akka-http until it is merged to master?

**Comment by ktoso** [comment]
The vicious cycle like you explain it exists for `akka-actor` AFAIK only, so it should not be a problem for other modules.

**Comment by jrudolph** [comment]
Ok, nice, then it can be easily fixed.

**Comment by 2m** [comment]
Also Scala 2.12 does not have this circular dependency anymore since it does not include actors.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
