### ISSUE TITLE
Add overload for HttpEntity for unknown length stream

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18250]
A "streaming" http echo currently looks like this:

```scala
val httpEcho = Flow[HttpRequest].map(r ⇒ 
  HttpResponse(entity = Chunked.fromData(octetStream, r.entity.dataBytes)))
```

As HttpEntity does not have an overload that does not take a stream length (there is `(contentType, length, source)`).

We should add:

```scala
def apply(contentType: ContentType, data: Source[ByteString, Any]): Chunked =
    Chunked.fromData(contentType, data)
```

to allow:

```scala
val httpEcho = Flow[HttpRequest].map(r ⇒ 
  HttpResponse(entity = HttpEntity(octetStream, r.entity.dataBytes)))
```

Should `    def fromData(contentType: ContentType, chunks: Source[ByteString, Any]): Chunked =` also be exposed as `apply()`? It's not marked as Java API (fromData), but looks a bit weird for Scala DSL

**Comment by ktoso** [comment]
Sounds good or did I miss something @sirthias @jrudolph @drewhk ?

**Comment by sirthias** [comment]
Yes, I think that'd be a good thing to have!

**Comment by ktoso** [comment]
Ok, I'll PR it in a bit, have it prepared. :-)
