### ISSUE TITLE
ActorRef serialisation cannot handle unknown remote transport causing persistence to fail

### ISSUE THREAD

**Issue by DomBlack** [akka/akka#18252]
Imagine you are running a system in production using the TCP remote transport and are persisting ActorRefs.

If you then move over to a completely TLS based transport and wish to disable TCP to prevent untrusted connections, you will disable the TCP transport.

However when the system restarts, it will try to recover and resolve the old ActorRefs and throws an exception that it doesn't know what the TCP protocol is causing recovery to fail. The only way to solve this is to keep the TCP transport enabled.

This negates the point of trying to enable TLS transports.

(Note: I discovered this over a year ago, and only just remembered so it may no longer cause the same failures)

**Comment by patriknw** [comment]
As far as I can see it logs the exception at error level with full stack trace, but then it returns EmptyLocalActorRef, which is a ref for actors that does not exist. For example, if you watch that ref you will get Terminated immediately.

So as far as I can see it works, but logs will be very noisy. Recovery should not fail.

I can change the error log to a warning without stack trace.

@DomBlack let me know if you have a different understanding.

**Comment by DomBlack** [comment]
Sorry Patrik, I must of remembered wrong. I agree with changing the log level down to a warning.

**Comment by patriknw** [comment]
no worries, thanks for reporting
