### ISSUE TITLE
Handle subscription timeout in HTTP

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18274]
See http://stackoverflow.com/questions/32085345/how-to-configure-akka-http-to-return-http-503-in-case-of-request-timeouts

Not sure which publisher timed out in that specific case but if we are able to return a 500 response we should be able to deliver a 503 as well.

/cc @sirthias

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
