### ISSUE TITLE
Scheduler Task With Long initialDelay Never Triggers

### ISSUE THREAD

**Issue by omervk** [akka/akka#18276]
When my scheduler has a long initial delay (hours, etc.), the task is never executed. After reading [this thread from two years ago](https://groups.google.com/forum/#!topic/akka-user/OBmHObGJYa0), I found out that this is simply not supported behavior, but that fact is not reflected anywhere in the documentation.

1. What is the maximum amount of delay that the scheduler accepts?
2. Should I use a task that "ticks" and waits until the delay has been reached and then runs the task itself?
3. Are there any other cases in which the task will not be invoked?
4. Is this the intended behavior with interval, too? Can I set it to a day? a week? a month?

**Comment by ktoso** [comment]
AFAIR the scheduler throws an exception in case you give it a "too large" delay - is this not matching your experience?
For such very long timeouts you need to persist the schedule somehow anyway so it becomes non-trivial (i.e. needs to persist state in case the app dies between scheduling, and the target time of triggering).

For such very large timeouts we usually recommend Akka Quartz https://github.com/enragedginger/akka-quartz-scheduler as Quartz's entire focus is long-term scheduling. You can (should) hook it up with persistence as well.

Does this answer your question or did I miss something?

**Comment by omervk** [comment]
It does, except that I did not receive any such exception when I gave it an initial delay of ~22 hours.

**Comment by patriknw** [comment]
That sounds strange. It should reject durations >= 21474836470 milliseconds (~5965 hours) with the default settings. Smaller durations should work.

Max is:

    tick-duration * Int.MaxValue

**Comment by omervk** [comment]
I'll add some more information - the schedule was set inside a servlet container (Tomcat 8). This might be the reason the scheduler never started working.

I've since moved to Akka Quartz as @ktoso suggested and am very happy it :)
