### ISSUE TITLE
add callback hook to OverflowStrategy once it get involed?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#18272]

**Comment by ktoso** [comment]
Is the use case for example for logging or do you want to make a decision in the callback as well?

**Comment by hepin1989** [comment]
I want to passing the element affected for the specified strategy and react to it.

**Comment by ktoso** [comment]
This got another upvote from recent discussions I've had. I can see it be useful for logging the dropped element for example, in order to identity when the overload starts happening etc.

// cc @akka/akka-team

**Comment by drewhk** [comment]
We can add a "beforeDrop" callback, but the issue here is that there is very limited things that you will be able to do there. 
 - You are not allowed to call any of the Directives there
 - It is not thread-safe to call just anything outside
 - You can send actor messages, but then you need to close over the ActorRef at construction and the stage will become non-reusable 

I recommend using a custom DetachedStage instead and deal with the necessary semantic implications in the custom implementation where all the assumptions are clear.

**Comment by rkuhn** [comment]
Good point, Endre.

**Comment by ktoso** [comment]
Hmm, good points - would it be interesting enough to make it configurable that we log before dropping though? 
I can see how this could be useful when debugging and looking for "where do my elements get dropped?". It could be configured as Attribute.

**Comment by rkuhn** [comment]
If dropping is not desired then use a failure strategy; otherwise this is more monitoring than logging I think, and we don’t have monitoring in Akka Streams right now (and we shouldn’t start baking in a half-assed logging version).

**Comment by hepin1989** [comment]
what if I just want to keep as more element as I can to protect the dropping from the period high load?I just want to keep more but to the failure all the stream.which means this is a improvement,not a 0 and 1.
for the custom implement from the DetachedStage.I think that should be a waste of code from such a simple request.

I think at least make it configurable should be fine,and maybe callback ,at least a logging.the there is callback just a boolean check for logging.

**Comment by rkuhn** [comment]
If you want to keep “just one more element in case of emergency” then this is absolutely identical to enlarging the buffer by one element. The argument against making it configurable is that we already have a huge number of knobs and levers and every one of them adds to (new) user confusion: we need to be really careful to not let the API grow into a wild mess. A buffer should be a simple thing and a callback is a means to add arbitrary behavior (which usually results in something that is not simple anymore in real-world usage).

**Comment by ktoso** [comment]
I'm also against the more complex use case explained in https://github.com/akka/akka/issues/18272#issuecomment-136641929, and was convienced by the argument that this would be going into the direction of a poor-man's monitoring solution. 

So let's not implement it as we'll want to solve it by adding proper monitoring to streams eventually.
Shall we close the ticket?

**Comment by hepin1989** [comment]
@ktoso I think it should be fine to close it.just as @rkuhn said,this would make the akka stream more complex,and in fact this case should be covered if there is a monitoring system.thanks for your comment.

**Comment by hepin1989** [comment]
And I can see that there in fact have many benefits to keep the akka stream core simple:)

**Comment by ktoso** [comment]
Thanks, let's close then and investigate monitoring options once we work on that front.

**Comment by hepin1989** [comment]
@ktoso Yes,akka stream is your epic work and definitely should has a monitoring,currently I am investigating Hystrix for our system too. looking forward for that,even it is commercial:).
