### ISSUE TITLE
HTTP: closing the Source of HTTP requests has inconsistent behaviour re closing the Flow of responses

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#18292]
Most of the Akka HTTP examples which send a single HTTP request down the connection Flow and expect a single HTTP response use `Sink.head`, e.g.

From http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/client-side/connection-level.html#opening-http-connections

    val connectionFlow: Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] =
      Http().outgoingConnection("akka.io")
    val responseFuture: Future[HttpResponse] =
      Source.single(HttpRequest(uri = "/"))
        .via(connectionFlow)
        .runWith(Sink.head)

I was looking into whether I could replace "Sink.head" with a sink which asserts that the stream produces only a single element re https://github.com/akka/akka/pull/18267 and I have found that the behaviour of the "connectionFlow" regarding closing the output stream when the input stream is closed is inconsistent and varies based on the size of the request / responses.

The following test demonstrates that the "connectionFlow" will close the Stream of responses when the Stream of requests is closed if the message bodies are small, but will not do so if the message bodies are large:

    import akka.actor.ActorSystem
    import akka.http.scaladsl.Http
    import akka.http.scaladsl.model.{HttpResponse, Uri, HttpRequest}
    import akka.stream.ActorFlowMaterializer
    import akka.stream.scaladsl.{Source, Flow, Sink}
    import org.specs2.mutable.Specification
    import scala.concurrent.{Awaitable, Await}
    import scala.concurrent.duration._
    import akka.http.scaladsl.client.RequestBuilding._
    
    class HttpStreamCloseBehaviourSpec
      extends Specification {
    
      implicit val actorSystem = ActorSystem()
      import actorSystem.dispatcher
      implicit val materializer = ActorFlowMaterializer()
    
      val server = Await.result(
        Http().bind("127.0.0.1", 0).to {
          Sink.foreach { incomingConnection =>
            incomingConnection.handleWith(Flow[HttpRequest].map { request =>
              request.uri.path match {
                case Uri.Path("/reflect") =>
                  HttpResponse(entity = request.entity)
              }
            })
          }
        }.run(),
        10.seconds)
    
      val host = "localhost"
      val port: Int = server.localAddress.getPort
    
      "Http().outgoingConnection" should {
    
        "close the connection if the source of requests is closed - small requests" in {
          checkConnectionIsClosedAfterSingleRequestSourceCloses(
            "Test HTTP entity")
        }
    
        "close the connection if the source of requests is closed - large requests" in {
          checkConnectionIsClosedAfterSingleRequestSourceCloses(
            "Test HTTP entity" * 10 * 1024)
        }
      }
    
      def checkConnectionIsClosedAfterSingleRequestSourceCloses(entityString: String) = {
        val request = Post(s"http://$host:$port/reflect", content = entityString)
    
        val connection = Http().outgoingConnection(host, port)
    
        val responses = Source.single(request).via(connection).grouped(100).runWith(Sink.head)
    
        await(responses) must beLike[Seq[HttpResponse]]{
          case Seq(resp) =>
            val entity = await(resp.entity.toStrict(10.seconds))
            entity.data.decodeString("utf8") mustEqual entityString
        }
      }
    
      private def await[T](x: Awaitable[T]): T =
        Await.result(x, 10.seconds)
    }

On my machine (Windows 8, Java 6), this test passes for "small requests" and fails for "large requests". 
If I replace `.grouped(100).runWith(Sink.head)` with `.runWith(Sink.head)`, then both tests pass.

I have looked at the TCP traffic, and the TCP stream is closed by the Akka client in the "small requests" case and left open in the "large requests" case.

I would expect the behaviour to be consistent between the two cases.

**Comment by RichardBradley** [comment]
The docs say:
 
> An application can actively trigger the closing of the connection by completing the request stream. In this case the underlying TCP connection will be closed when the last pending response has been received.

So I think this is a bug

**Comment by jrudolph** [comment]
Interesting. Thanks for reporting, @RichardBradley.

**Comment by rkuhn** [comment]
I think this might be related to strict entities making some things work “magically” that were not supposed to work.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
