### ISSUE TITLE
Document Flow.wrap of independent Source and Sink more explicitly

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18291]
It seems to be a common case for "I'm never going to emit anything" etc when handling websockets for example.

It should be documented explicitly how to use `Flow.wrap(source, sink)`

**Comment by rauanmaemirov** [comment]
:+1:

**Comment by ennru** [comment]
I assume this became [fromSinkAndSource](https://doc.akka.io/docs/akka/current/stream/operators/Flow/fromSinkAndSource.html) later on.
