### ISSUE TITLE
Persistence - Register event adapters @ runtime

### ISSUE THREAD

**Issue by q42mark** [akka/akka#18299]
I think it's quite common to tag events per aggregate type. With the current setup, you would need to write a EventAdapter per aggregate type. If you have several aggregate types, this results in boilerplate code. I've made an attempt to cut that down by introducing a `Tag` type which contains a tag name as string and the actual type. It would be possible create a the `WriteEventAdapter` at runtime by using the `Tag`. See the example below: 

```scala
implicit val actorSystem = ActorSystem()
implicit val journal = PersistenceQuery(actorSystem).readJournalFor(LeveldbReadJournal.Identifier)

// Containing the return type + the tag name
trait Tag {
  type Type
  val manifest: Manifest[Type]
  val tag: String
}

object Tag {
  def apply[T : Manifest](t: String) = new Tag {
    type Type = T
    val manifest = implicitly[Manifest[T]]
    val tag = t
  }
}

//A event type persisted by a PersistentActor
sealed trait UserEvent {
  val userId: Int
}

//Create a Tag for userEvent
val userEvent = Tag[UserEvent]("userEvent")

//Utility function to create a WriteEventAdapter based on tag
def tagType(t: Tag) = new WriteEventAdapter {
  override def manifest(event: Any): String = ""
  override def toJournal(event: Any): Any = {
    //not sure if this works, but we cannot use match/case here (type erasure)
    if(t.manifest.canEqual(event)) Tagged(event, Set(t.tag))
    else event
  }
}


//Would be nice to register this WriteEventAdapter to persistence, however it's not a class
val userEventAdapter = tagType(userEvent)

//This is a utility function to get a stream of events by the Tag, just to illustrate the use of Tag
def eventsBy(tag: Tag, offset: Long = 0L)(implicit readJournal: ReadJournal) =
  readJournal.query(EventsByTag(tag.tag, offset)).map(_.event.asInstanceOf[tag.Type])

//Query userEvents
eventsBy(userEvent).map(_.userId)
```

However we cannot register a `WriteEventAdapter` at runtime. At the moment its only possible to register EventAdapters by using the HOCON config: http://doc.akka.io/docs/akka/2.4.0-RC1/scala/persistence.html#event-adapters-scala

Would it be possible to have `Persistence(system).registerWriteAdapter(t: WriteEventAdapter)` or something like that?

**Comment by ktoso** [comment]
Good idea about dynamically registering adapters. This was not implemented yet but definitely was the intent.
I'll give it a spin. I'm not sure about the usage example you posted though, not sure if that'd work.

**Comment by ktoso** [comment]
Not including it for now, added complexity is not paying off in additional capabilities actually here.
One can do the same with registering a "Dynamic Adapter".
