### ISSUE TITLE
Persistence - AsyncRecovery readHighestSequenceNr clarification

### ISSUE THREAD

**Issue by chbatey** [akka/akka#18296]
At the moment the asyncReadHighestSequenceNr fromSequenceNr parameter is described as a hint where to start searching from, it would be nice to specify exactly what will be passed in in the presence/absence of snapshots.

I could be wrong but for akka 2.4-M2 for a persistenceId with no snapshots 0 was passed in, as of 2.4-RC1 1 is passed in. The cassandra journal previously returned the fromSequenceNr if it found no events either because it is a new persistenceId or all messages have been deleted/snapshotted which led to new persistenceIds starting at sequence number 2 rather than 1. 

WDYT?

**Comment by patriknw** [comment]
This might have changed, yes. Now the fromSequenceNr param is 1 or snapshotSeqNr + 1. That makes sense for the asyncReplayMessages but I agree that readHighestSequenceNr should have one less.

**Comment by patriknw** [comment]
Thanks a lot for reporting, by the way :-)
