### ISSUE TITLE
HTTP: Discuss chunking support

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#18315]
see discussion in #18144.

/cc @jrudolph @sirthias

**Comment by jrudolph** [comment]
@2beaucoup your last comment was 

> On the other hand maybe we should think about the value of chunking in the context of streaming WithoutKnownLength request/response entities.

What kind of support do you have in mind here? I.e. what is special about `WithoutKnownLength` content streams?

(Also this needs to be considered with #17694 in mind.)

**Comment by 2beaucoup** [comment]
I was thinking about auto chunking response entities without a known length as an alternative to closing the connection.

**Comment by jrudolph** [comment]
I see.

**Comment by ktoso** [comment]
Somewhat related to https://github.com/akka/akka/issues/17694 but as I understand it "the other way around", right?

Do you think this is something to keep as triaged for now @jrudolph @2beaucoup or shall we close?

**Comment by 2beaucoup** [comment]
Looks like this is already supported ([source](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala#L248-L255)).

**Comment by ktoso** [comment]
Thanks, totally missed that :)
