### ISSUE TITLE
failed: ClusterMetricsDisabled

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18312]
timeout 1 second

https://jenkins.akka.io:8498/job/akka-nightly/2550/consoleFull

**Comment by johanandren** [comment]
The failure is actually on the initialization of TestKit.testActor rather than something specific to `ClusterMetricsDisabledSpec`

**Comment by johanandren** [comment]
Would it make sense to dilate the hard coded 1 second timeout waiting for the testActor to initialize?

**Comment by patriknw** [comment]
Yes, dilate it, and increase the timeout to 3 seconds. No reason, I guess, to use a short timeout.
We run without dilation so dilation alone will not help us.
