### ISSUE TITLE
Intermittent ArrayIndexOutOfBoundsException in OneForOneStrategy

### ISSUE THREAD

**Issue by reavowed** [akka/akka#18319]
I have an HTTP server that is intermittently returning 500 responses due to an exception somewhere in the Akka internals:

> 2015-08-25 14:55:30,039 13:55:30.038UTC ERROR akka.actor.OneForOneStrategy akka://MyServer/user/$a/MyServer-21471-39-map-map-Broadcast-stageFactory - null
java.lang.ArrayIndexOutOfBoundsException: null
> 2015-08-25 14:55:30,040 13:55:30.039UTC ERROR akka.actor.ActorSystemImpl ActorSystem(MyServer) - Internal server error, sending 500 response
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://MyServer/user/$a/MyServer-21471-39-map-map-Broadcast-stageFactory#-674228150]] terminated abruptly

None of our application flows look like this, so I'm assuming it's one of the flows around our HTTP binding?

I've also seen a similar thing happen in a flow that we've put together ourselves, in a unit test:
> 2015-08-25 09:15:44,996 13:15:44.991UTC ERROR akka.actor.OneForOneStrategy akka://ConnectionTimeoutFlowSpec/user/$a/ActorSystemScopeMaterializer-1-3-actorRefSource-Broadcast-stageFactory - -1
> java.lang.ArrayIndexOutOfBoundsException: -1
>         at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$currentOp(Interpreter.scala:216)
>         at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.getAsyncCallback(Interpreter.scala:314)
>         at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.getAsyncCallback(Interpreter.scala:434)

Any idea what's going on here?

**Comment by drewhk** [comment]
We need a reproducer, otherwise it is hard to say anything. Probably one of the stream processing stages not properly respecting demand?
