### ISSUE TITLE
persistence plugin starting sequenceNr

### ISSUE THREAD

**Issue by kpbochenek** [akka/akka#18320]
I tried to match CassandraPersistencePlugin with Akka 2.4-M3 (the same with 2.4.0-RC1) and encountered strange change.

All tests expected first sequenceNr from AkkaPersistence to be equal to 1.
But with mentioned akka versions first sequenceNr provided to CassandraPersistencePlugin equals to 2.

Is it expected behaviour?
Can Persistence implementation expect some constant sequenceNr or not really?

**Comment by patriknw** [comment]
This was not an intended change in the fromSeqNr param in readHighestSeqNr. We will fix it in RC2. Thanks for reporting.

**Comment by kpbochenek** [comment]
Okay just realized this is a duplicate of #18296
