### ISSUE TITLE
Orderly cluster node shutdown needs to cover multiple states

### ISSUE THREAD

**Issue by wsargent** [akka/akka#18344]
When a node in the cluster is started in its own JVM, there needs to be some logic involved in an orderly shutdown so that when a JVM shutdown occurs, the node can disengage from the cluster and leave cleanly without the other nodes gating the IP for being unavailable.

```
system.registerOnTermination(System.exit(-1)) // exit when the actorsystem is done
sys.addShutdownHook {
   shutdown(shutdownManager, system)
}

def shutdown(shutdownManager: ActorRef, system: ActorSystem): Any = {
  try {
    shutdownManager ! Shutdown
    system.awaitTermination(15 seconds)
  } catch {
    case e: InterruptedException =>
      shutdown(shutdownManager, system)
    case e: Exception =>
      // If the system throws a timeout exception, kill it.
      e.printStackTrace()
      System.exit(-1)
  }
}
```

The shutdown manager needs to do different things depending on the state of the cluster.  If the cluster has `akka.cluster.min-nr-of-members` > 1, then the state of the node is JOINING.  This means that the `MemberRemoved`/`MemberExited` message will never be sent.  A work around is to determine if the member is up, and if it isn't send, use `cluster.down` immediately, which will force a `MemberRemoved`.

```
case Shutdown =>
if (memberUp) {
     // Leave doesn't do anything if the node isn't up (you can't leave if you're
     // still joining)
     log.debug(s"Shutdown -- member is still in ${cluster.state}, sending a LEAVE")
     cluster.leave(cluster.selfAddress)
  } else {
   // Down will cause the system to receive MemberRemoved in a JOINING state.
  log.debug(s"Shutdown -- member is still joining, sending a DOWN")

  cluster.down(cluster.selfAddress)
}

case MemberRemoved(member, previousStatus) =>
      if (member.address == cluster.selfAddress) {
        context.stop(self)
      }
```

at which point the shutdown actor can get on with shutting down the ActorSystem.

```
override def postStop(): Unit = {
   cluster.unsubscribe(self)
  context.system.shutdown()
}
```

The behavior of `cluster.leave` / `cluster.down` needs to be documented so that nodes can be shut down even when they are not in an UP state.

Also see https://github.com/akka/akka/issues/16224 and https://github.com/akka/akka/issues/16736

Also see the existing documentation for shutting down a cluster node: http://doc.akka.io/docs/akka/snapshot/scala/cluster-usage.html#How_To_Cleanup_when_Member_is_Removed

**Comment by choffmeister** [comment]
I am currently also stumbling about this. I noticed that even though waiting for `MemberRemoved` has been raised on the leaving node, one still needs some grace period before actually leaving the cluster. It is not guaranteed, that also all other nodes also know this (as far as I know it is only guaranteed that the leader knows this).

Or is there a way, to get notified when the information about one nodes leaving has become converged knowledge all around the cluster via gossiping?

**Comment by choffmeister** [comment]
Hmm. From reading http://doc.akka.io/docs/akka/current/common/cluster.html#Membership_Lifecycle I understand, that the `MemberRemoved` should come _after_ convergence. But testing using `DistributedPubSubMediator` I still get messages after `MemberRemoved` for some more seconds.

Do I have to inform the mediator explicitly to drop a removed member also from pubsub?

**Comment by choffmeister** [comment]
I opened a question on google groups regarding akka cluster leave and distributed pub sub mediator:

https://groups.google.com/forum/#!topic/akka-user/bc3DgD2bOd8

**Comment by patriknw** [comment]
Solved by https://github.com/akka/akka/issues/21537
