### ISSUE TITLE
Documentation for DistributedPubSubExtension needs to be clearer

### ISSUE THREAD

**Issue by wsargent** [akka/akka#18343]
In the "Distributed Publish Subscribe in Cluster" chapter http://doc.akka.io/docs/akka/snapshot/scala/distributed-pub-sub.html -- the documentation is unclear when it comes to registration.  This is the entirety of the docs:

> You register actors to the local mediator with DistributedPubSubMediator.Put or DistributedPubSubMediator.Subscribe. Put is used together with Send and SendToAll message delivery modes. The ActorRef in Put must belong to the same local actor system as the mediator. Subscribe is used together with Publish. Actors are automatically removed from the registry when they are terminated, or you can explicitly remove entries with DistributedPubSubMediator.Remove or DistributedPubSubMediator.Unsubscribe.

This should be detailed in a section called "Registration" with sub sections "Registering Actor with Send" and "Registering Actor with Publish".  These sections should go into the lifecycle of registering and unregistering the actor, and say that `Remove` should use `toStringWithoutAddress`.

In addition, there should be an example showing registration with `Send` /  `SendToAll` using `Put`, followed by a Remove:

```
mediator ! Put(self)
mediator ! Send(...)
mediator ! Remove(self.path.toStringWithoutAddress)
```

in the same style as http://doc.akka.io/docs/akka/snapshot/scala/distributed-pub-sub.html#A_Small_Example.

Another alternative might be to have two top level sections on "Send" and "Publish" and then put matching examples under each section (i.e. Send -> "Registration" / "Example" and "Publish" -> Registration / Example).

**Comment by patriknw** [comment]
I agree, this can be improved.

BTW, normally you don't have to Remove, since that is done automatically when the actor is terminated.
