### ISSUE TITLE
Provide TLS session details in custom TlsSessionInfo header

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18349]
See also #13749

**Comment by analytically** [comment]
+1

**Comment by mpilquist** [comment]
FYI, I just ran in to this when attempting to move from Spray to Akka Http, and this completely blocks me from upgrading. A big +1 for this making the 2.0 release -- even if renegotiation isn't supported in 2.0.

**Comment by ktoso** [comment]
http:next tickets are deemed required for feature completeness with spray, so we're on the same page about how important it is, thanks for voicing the feedback though!

**Comment by mpilquist** [comment]
:+1:

**Comment by LogicalTime** [comment]
I was really hoping this would be in the 2.0 release. I'm guessing this has been a tricky issue to resolve? Perhaps the solution that the Spray team had doesn't translate well with the new abilities like chunked data etc? Just curious about what the issue looks like from the developer standpoint.

**Comment by ktoso** [comment]
Please read the PR for this issue if you're interested in details: https://github.com/akka/akka/issues/19210
Basically the problem is "so much stuff, so little time", we will get it in for the stable release in january though, don't worry :)

**Comment by ktoso** [comment]
@LogicalTime FYI we've merged this and it will be in the next streams/http release this around end-of-January/beginning-of-February.

**Comment by LogicalTime** [comment]
Excellent! very much looking forward to it
