### ISSUE TITLE
Document scheduler behaviour when given runnable throws

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18346]
The scheduler docs do not explain what happens if given a runnable, and the code inside throws, we should document that. This is about the "repeating scheduled task", i.e. if 2nd time throws, will there be a 3rd time (AFAIR no, there won't).

via: http://stackoverflow.com/questions/32255919/akka-scheduler-stops-on-exception-is-it-expected

**Comment by hepin1989** [comment]
how about add some meta data to the scheduling and when a exception throw,invoke a callback?
eg :
schedule*(meta:Option(Any) ...) and when there is an exception,invoke a callback like 
scheduler.exceptionHandler(cause:Throwable,meta:Option[Any])?
and user could register a exception handler to the scheduler,I think this should be useful.

**Comment by ktoso** [comment]
I'd rather want to keep it very simple. We do not encourage the "schedule a runnable" style anyway, it's better to schedule a message to an actor.

**Comment by hepin1989** [comment]
I don't know why even I have add quartz to our project,our team mate keep using akka's default scheduler for game long scheduling,maybe it's too convenient.

**Comment by ktoso** [comment]
Akka's scheduler is definitely not built for long-term scheduling, it's optimised for "a lot of events, frequently" (i.e. the usual actors case - when many want to do something periodically). 

If you want "long term" definitely go for quartz or something else (that's schedule would survive shutting down apps).

**Comment by hepin1989** [comment]
I know that,them just use it for all.:(,I think there should be more developer do it like this.
