### ISSUE TITLE
"Leaving cluster" documentation needs clearer address reference

### ISSUE THREAD

**Issue by wsargent** [akka/akka#18345]
The documentation for leaving a cluster http://doc.akka.io/docs/akka/snapshot/scala/cluster-usage.html#Leaving shows this code example:

```
Cluster(system).leave(address)
```

This is misleading, because a user could assume this meant:

```
Cluster(system).leave(self.address)
```

A better example would be:

```
val cluster = Cluster(system)
cluster.leave(cluster.selfAddress)
```

The ultimate fix would be to have `ClusterAddress` be a sub type of `Address` so that a `self.address` cannot be passed in.

**Comment by patriknw** [comment]
great catch, we should indeed make `Cluster(system).leave(self.address)` work (that is not difficult, just need to check if host/port is missing and then treat that as cluster.selfAddress)
