### ISSUE TITLE
Circuit breaker is awkward to use

### ISSUE THREAD

**Issue by wsargent** [akka/akka#18347]
The circuit breaker uses the following example:

http://doc.akka.io/docs/akka/snapshot/common/circuitbreaker.html#Call_Protection

```
def dangerousCall: String = "This really isn't that dangerous of a call after all"
 
def receive = {
  case "is my middle name" =>
    breaker.withCircuitBreaker(Future(dangerousCall)) pipeTo sender()
  case "block for me" =>
    sender() ! breaker.withSyncCircuitBreaker(dangerousCall)
}
```

This works great when the call is wrapping a future with direct response.  However, if the actor is expecting a message back or `ReceiveTimeout`, then using the circuit breaker is awkward -- there's no way to access the circuit breaker's current state, or signal a failure or success directly.

As a result, if the code crosses several messages, the way to signal failure seem to be:

```
case ReceiveTimeout =>
  breaker.withCircuitBreaker(Future.failed(new TimeoutException()))
```

If `fail` / `succeed` and `state` methods are exposed on the circuit breaker would make it easier.

**Comment by patriknw** [comment]
We could absolutely expose those things.

Just a few comments.

It works fine with ask, but that is not always what you want to use.

For fire-forget messaging it is more difficult. One way is to create a Promise corresponding to the Future of the `withCircuitBreaker`, that you keep around in the actor and when you get reply messages corresponding to the request you would complete the promise with success or failure.

**Comment by richard-imaoka** [comment]
Hi, let me pick this up if no one is assigned yet?

I assume the first thing to do is to implement success, failure and state methods as explicitly mentioned by @wsargent.

I am not sure yet about the promise part ... So will dig into it.
