### ISSUE TITLE
Metrics based resizer for routers

### ISSUE THREAD

**Issue by kailuowang** [akka/akka#18356]
Based on discussion with @ktoso and @richdougherty, implement a Resizer that can auto scale the routee pool based on performance metrics.  

Basically it should perform three resizing operations periodically:
1. downsize after it hasn't seen all routees fully utilized for a period of time.
2. explore to nearby pool sizes to collect metrics 
3. optimize to a nearby pool size that has better performance metrics

When the pool is full, it randomly choose between exploring and optimizing.

**Comment by patriknw** [comment]
Shouldn't this be closed?

**Comment by ktoso** [comment]
Right, thanks @patriknw
