### ISSUE TITLE
Allow configuration of HTTP server to request client certificates

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18350]
Part of #13749.

**Comment by jrudolph** [comment]
There might be nothing to do here. `Http.bind` already allows to pass in an HttpsContext where you can set the `clientAuth` parameter as needed.

**Comment by ktoso** [comment]
True, I'd reclassify it to a docs ticket then.
I'm in the middle of working on https://github.com/ktoso/ssl-config which we should use to make such things simpler.

**Comment by rkuhn** [comment]
Yes, this is already possible.
