### ISSUE TITLE
Provide Marshallers to be able to Stream JSON for Source[A, _]

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18358]
It should be possible to implement AFAICS,
like for Futures http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/common/marshalling.html#http-marshalling-scala

**Comment by jrudolph** [comment]
Wouldn't this have the same problem as providing a marshaller for `Seq[A]`? I.e. that there's no inherent (or common) representation of a "collection" that could be used to serialize a stream or a collection of elements to the bytes of an HTTP message entity.

**Comment by ktoso** [comment]
I was playing around with this over the weekend and realised the ticket is too generic, the use case still valid though: namely "[JSON Streaming](https://en.wikipedia.org/wiki/JSON_Streaming)" where we simply emit one json-object-per-line (without any wrapping it in "[]" etc).

**Comment by jrudolph** [comment]
Yes, that makes sense. It could then also serve as an example for other "framing" or "collection" marshallers.

**Comment by ktoso** [comment]
Indeed :+1: I think I'll try to poke around it some evening to wrap my head around the marshalling infrastructure.

**Comment by ktoso** [comment]
// Note to self: Heard feedback from a user that they'd need this.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
Also, I think this is solved since we added FramedEntityStreaming https://github.com/akka/akka/issues/18484
