### ISSUE TITLE
Cannot find method "section" and class OperationAttributes in Akka-Streams

### ISSUE THREAD

**Issue by cppexpert** [akka/akka#18354]
I cannot find method `section` and class `OperationAttributes` in Akka-Streams described on this page

http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M4/scala/stream-error.html

Were they renamed ?

**Comment by ktoso** [comment]
The `section(attrs)(section)` was removed (during Milestone phase we did aggressively change APIs), and the equivalent is using nesting and `.withAttributes(attrs)` to achieve the same.

You can read more in the `1.0` docs (1.0-M4 is a bit old now) about stream errors: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-error.html and about how modules work (i.e. http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-composition.html ), that should help.
