### ISSUE TITLE
cluster - restarted downed node cannot join cluster

### ISSUE THREAD

**Issue by elyrank** [akka/akka#18368]
I have a cluster of 3 nodes, 
one node was marked as down and is no longer visible at the members map (in JMX)

the downed node was restarted , and then it is trying to join again.
the node that deceived the request gives this log:

[Cluster(akka://ActorSystem)             ]   Cluster Node [akka.tcp://ActorSystem@a053.test:2553] - New incarnation of existing member [Member(address = akka.tcp://ActorSystem@a055.test:2553, status = Down)] is trying to join. Existing will be removed from the cluster and then new member will be allowed to join.   |TAGS|sourceThread=ActorSystem-akka.actor.default-dispatcher-19, akkaTimestamp=11:58:37.517UTC, akkaSource=Cluster(akka://ActorSystem)

but the downed node is never removed and thus the restarted node with new UID can never join the cluster

when I remote debugged the server - I saw that the latestGossip has a members list of 3 nodes , including the down node
but the overview had only the 2 active nodes

trying to down or leave the node using JMX does not help
so now the only way to fix this is to stop the whole cluster and then start the nodes again - which means down time.

**Comment by patriknw** [comment]
Which version of Akka?

**Comment by elyrank** [comment]
we are using 2.3.11

**Comment by hveiga** [comment]
We had the same issue but we tried with 2.4.0-RC1 and it seemed to be solved.

**Comment by elyrank** [comment]
do you know what solved the problem? waiting for 2.4 release is currently not an option for us, can this fix be merged to 2.3.x ?

**Comment by patriknw** [comment]
@elyrank I would be interested to take a look at the logs. Especially the log message "Leader can currently not perform its duties..." contains some interesting information. It might take around a minute until this is logged.

**Comment by elyrank** [comment]
this log message does not appear - since the cluster is converged. there are no unreachable nodes,
and when I debugged it I saw that the gossip contains  the members map had two nodes with status UP and one node (the problematic one) with status DOWN and in the overview it had only the 2 up nodes

**Comment by patriknw** [comment]
any update here? otherwise I will close the issue

**Comment by hveiga** [comment]
I can confirm this is working in 2.4.0. We have tried various different scenarios with our 9 node cluster.

**Comment by nelsonblaha** [comment]
We are having this problem exactly as @elyrank describes in 2.5.9

**Comment by greenrd** [comment]
So are we. I think we will need to raise a new issue.

**Comment by patriknw** [comment]
@greenrd @nelsonblaha Did you create a new issue? I still think we would need to see logs to be able to help or confirm that it's an issue.
