### ISSUE TITLE
Document sharding with Supervisor or allow SupervisionStrategy for Cluster Sharing

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18370]
Sometimes in ClusterSharding it may be useful for the actors to be stopped on some exceptions, and restarted on other ones. This is achievable currently by providing a Supervisor Props to `ClusterSharding` that's only purpose in life is to start the child and monitor it given a specific strategy.

We should either document this pattern explicitly, or allow passing in supervision strategies.

**Comment by patriknw** [comment]
Good point, it should be documented how to use a supervisor props.

Note that there is not much difference between a restart and a stop for cluster sharding, since it will be started up again when the next message arrives.
