### ISSUE TITLE
Ease graceful leaving from Cluster (for Cluster Singleton)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18373]
Leaving a Cluster gracefully is currently not as simple as it could be.
Simply calling `cluster.leave(cluster.selfAddress)` is the easy part, then one should wait for the `MemberRemoved` event of "myself". This could perhaps be exposed as `cluster.leaveGracefully(): Future[_]` where the future completes once successfully left the cluster.

An additional thing this could do is to manage ClusterSingletons etc migrating to other nodes before we signal "ok, now you can shutdown the jvm". For singletons it's a perf optimisation, not a correctness change, since otherwise failure detection could kick in and migrate them anyway for example.

**Comment by patriknw** [comment]
Ok, we have added http://doc.akka.io/docs/akka/2.4.0-RC1/scala/cluster-usage.html#How_To_Cleanup_when_Member_is_Removed, but perhaps something more is needed?
That sample is slightly confusing, see https://github.com/akka/akka/issues/18245

See also:
https://github.com/akka/akka/issues/18344
https://github.com/akka/akka/issues/18345

**Comment by patriknw** [comment]
Solved by the coordinated shutdown #21537
