### ISSUE TITLE
Small typos in Streams docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18378]
> "a simple Twitter fed stream" s/fed/feed ?

> The code sample in "Broadcasting a Stream" seems to be different than the text that follows describing it. For example: "using the addEdge method". There is no addEdge in the code.

> Also, the text mentions: "Once we have the FlowGraph in the value g".  There is no "g" in the code.

Noticed by @edburns, thanks!

**Comment by ktoso** [comment]
// cc @2m @drewhk

**Comment by hepin1989** [comment]
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/stages-overview.html
s/upervision/supervision
