### ISSUE TITLE
add circuitbreaker to akka stream?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#18375]
I am reading some [blog](http://techblog.netflix.com/2012/02/fault-tolerance-in-high-volume.html) about Netflix's Hystrix,and think the diagram below could be implemented via akka stream too,and there is a feedback channel which is supported by akka stream.

add the circuitbreaker support directly to akka stream would enable many great thing.

**Comment by hepin1989** [comment]
https://github.com/akka/akka/issues/18229 here is a use case.

**Comment by hepin1989** [comment]
https://github.com/akka/akka/issues/15307

**Comment by ktoso** [comment]
Thanks, closing as duplicate.

**Comment by ktoso** [comment]
m
