### ISSUE TITLE
Consider logging warnings if Java Serialization is used

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18371]
We keep explaining that using Java Serialization for prod is not a good idea, however people still forget about it or don't read the docs, or just "get something working and start writing benchmarks" :wink: 

We could consider logging warnings when Java Serialization is used, unless a setting like "yes-im-using-java-serialization-willingly-please-dont-nag-me" is set. One thing to consider is that we sometimes use Java Serialization internally (right?) so that should be silenced somehow.

**Comment by patriknw** [comment]
Good point

**Comment by johanandren** [comment]
This might break tests if users has got remoting tests that depend on the log stream (as happened in https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/3738/)

**Comment by omervk** [comment]
Hi @ktoso, I stumbled across this thread thanks to the warning you placed in the logs.
I've failed to find the docs you're referring to and would appreciate it if you could send me their way.
Another question is what would be the recommended alternative to Java's serializer? This is not specified in the warning and would be a great help if it were. If there are multiple alternatives, when would you recommend each of them?

Many thanks in advance.

**Comment by ktoso** [comment]
It depends on use-cases, which is why we're not recommending a specific one.
For example, `protobuf` https://developers.google.com/protocol-buffers/?hl=en are very good at protocol evolution, however are a pain to maintain, `kryo` for example is much easier to use, but sacrifices protocol evolution (compatibility) somewhat – you may want to have a look at: https://github.com/romix/akka-kryo-serialization

**Comment by omervk** [comment]
Thank you, I'll take a look at Kryo, which looks more like what I need.
