### ISSUE TITLE
Distributed Data should take advantage of WeaklyUp members

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18399]
Distributed Data should gossip to WeaklyUp members.
It should not use those for the direct replication for Update and Get, e.g. WriteMajority.

WeaklyUp was introduced by https://github.com/akka/akka/issues/13584

**Comment by netcomm** [comment]
hi patriknw, there is a question: why Update and Get couldn't use the WeaklyUp members? just because the gossip convergence is not finished, what are the behind reasons?

**Comment by netcomm** [comment]
add a pull request https://github.com/akka/akka/pull/20634

**Comment by patriknw** [comment]
I'm not sure how the semantics of `Update` and `Get` should be for this. I was thinking that often you use `WriteMajority` / `ReadMajority` to ensure that a read always reflects the most recent write and that you want to use those on stable membership information. WDYT?

Perhaps we could include the weakly in `WriteTo` and `WriteAll`, but not in `WriteMajority` (same for the reads)?

**Comment by netcomm** [comment]
from my opinion, the precodition is the weakly nodes eventually be a normal Up node, this stage's time is unpredictable. so if the initial reason for weakly nodes is to use them as soon as possible, perhaps we should include all the Update and Get operation to be aware of weakly nodes.
