### ISSUE TITLE
Access to materialized value when using HttpEntity.Chunked

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18392]
For example you want to get the actor ref of a Source.actorRef if that is used as source of the HttpEntity.Chunked

**Comment by ktoso** [comment]
We'll want to at least document it, maybe add a mini directive, we'll see

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
