### ISSUE TITLE
doc:Add document about ExtensionKey

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#18405]
Document about ```ExtensionKey``` in [Akka Extensions](http://doc.akka.io/docs/akka/2.4.0-RC2/scala/extending-akka.html) is missing.

**Comment by patriknw** [comment]
Good point, it has one flaw though. Such extensions cannot be used from Java because of wrong type of `get`. That is why we don't use it for any of the extensions in Akka.

That is why we always do:

    override def get(system: ActorSystem): CountExtensionImpl = super.get(system)

This is also worth documenting, of course.

**Comment by patriknw** [comment]
I don't think we should promote `ExtensionKey` since it has this flaw.
