### ISSUE TITLE
Make it easier to discover/expose Source from FlowGraph

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18400]
We teach users that this is how they can expose "partial graphs", and also we say that a Source is-a partial graph:

```
FlowGraph.partial() { implicit b =>
  SourceShape(cvStage.out)
}
```

It would be great if this could be exposed as `Source[_, _]` (for example when I have someone's API that wants to receive a Source).

We could do this either by `Implicits._` providing a conversion from a Graph of Source shape to Source, or maybe `FlowGraph.source` which is equivalent to `Source() { b => o }` yet easier to convert to once you start with streams and think "hey, i actually need to expose a Source".

Or maybe like a `FlowGraph.source { b => SourceShape }`, since the `FlowGraph.partial { b => Shape }` yet `Source() () { => outlet }`. It's a bit inconsistent

**Comment by rkuhn** [comment]
This is addressed differently by making the process more consistent in #18700 .
