### ISSUE TITLE
Sink.source

### ISSUE THREAD

**Issue by jroper** [akka/akka#18406]
If you have an API that takes a `Sink` to consume a stream, and another that takes a `Source` to produce a stream, and you want the stream from the first API to be connected to the stream in the second API, the only way to currently do that in Akka streams is using `Sink.publisher`, and then mapping the materialized value to convert the publisher to a `Source`, and then use it.

There's nothing too difficult about doing this, except that is a major optimisation could happen if there was a `Sink.source` method that returned `Sink[T, Source[T, Unit]]`, since when such a source was run, materialization could be made a noop that simply returned the passed in `Source`.  Now that may not sound interesting, but it does get interesting if you map the materialized value, at that point, you'll be able to materialize the source to the API that accepts the source.

A concrete use case of this is if you have `Sink` to consume an HTTP request body (as you do in Play), and you want to proxy that request to another location through an HTTP client, which takes a `Source` for the request body.  Essentially your code could look like this:

```scala
def myAction = EssentialAction { req => 
  Sink.source[ByteString].mapMaterializedValue { source =>
    ws.url("http://example.org").post(source).map { _ =>
      Ok("Successfully proxied request!")
    }
  }
}
```

**Comment by drewhk** [comment]
Hmm, interesting. We see more and more creative uses of "mapMaterializedValue" :) 
The only thing I would modify here is to not put this on Sink/Source but on a different class not to confuse beginners. Or find a better name for this funcitonality (although I would prefer now not adding to Sink/Source but opening new objects for this purpose).

**Comment by drewhk** [comment]
> There's nothing too difficult about doing this, except that is a major optimisation could happen if there was a Sink.source method that returned Sink[T, Source[T, Unit]], since when such a source was run, materialization could be made a noop that simply returned the passed in Source

Um, but what you get is a Sink, which means that it will need a Publisher anyway. There is not much optimization that can happen here compared to the original solution you use.

**Comment by rkuhn** [comment]
This ticket is invalid as per the discussion in https://github.com/akka/akka/pull/18494/files#r41512546.

**Comment by drewhk** [comment]
What would be needed to achieve the desired goal is similar to Graph but unlike that, which represents a complete module, it is representing a part. It's signature would be similar `Part[S <: Shape, G <: Graph]`, but the end result of a fluid dsl is not a `RunnableGraph[M]` but a `CompletePart[G]` and instead of having a `run` method it can have a `unwrap` which returns the graph `G`. The problem though that it is hard to express in types that when you turn a graph into a part, then the unwrappable graph will be at least one port smaller, i.e. the Shape type would change.

**Comment by rkuhn** [comment]
… which is to say that solving this scenario with the characteristics @jroper suggests would mean a complete overhaul of Akka Streams abstractions (if I understand @drewhk correctly), which in turn is what led me to close this issue as invalid.
