### ISSUE TITLE
doc: Next/previous navigation in some doc pages does not match content structure

### ISSUE THREAD

**Issue by johanandren** [akka/akka#18409]
Went through 2.3.13 to create this list, but I noticed the error in 2.4.0-RC1 so I guess it's the same for both:

**Scala docs**
* Use-case and Deployment Scenarios: next is "HowTo: Common Patterns", should be "Examples of use-cases for Akka"
* Akka Typed: next is "External Contributions" should be "Fault Tolerance"
* Persistence Query: next is "Akka Typed", should be "Persistence Query for LevelDB"

**Java docs**
* Use-case and Deployment Scenarios
* Akka Typed (also, some mismatch between TOC and actual section name?)
* Persistence Query
* FSM: "Persistence Query", goes to scala docs
* Cluster Specification: ”Cluster Usage" goes to scala docs
* Use-case and Deployment Scenarios: ”HowTo: Common Patterns” goes to Scala docs
* FSM (Java with Lambda Support): ”Persistence Query” goes to Scala docs

**Comment by patriknw** [comment]
good, thanks

**Comment by johanandren** [comment]
Really weird, the `.rst` files for those sections and the `index.rst` files that generates the TOC and sub-TOCs looks correct. The TOC generated by sphinx is correct but the next-chapter-link gets what seems like a random destination (although consequently the same wrong one).

**Comment by patriknw** [comment]
is that for those that are linked several times? e.g. experimental modules?

**Comment by johanandren** [comment]
Not sure, linked several times - like have links to them on multiple pages?

**Comment by patriknw** [comment]
yes, or several places in the TOC, I think Akka Typed is included in the TOC of both Actors and Experimental Modules

**Comment by johanandren** [comment]
"intro/deployment-scenarios" not only gets "HowTo: Common Patterns" as its next link but the same is true for the inverse, "HowTo: Common Patterns" has got use-case as its previous link.

If I remove the anchor name ".. _use-cases:" from the beginning of deployment-scenarios.rst that fixes the problem (but makes it impossible to link to I guess).

**Comment by patriknw** [comment]
if it's very difficult to solve this I guess we have to live with it not being perfect

**Comment by johanandren** [comment]
Yeah, I have searched the inter webs for the same problem with no success and spent a couple of hours on it now, so maybe let it be for now. Maybe someone more python/sphinx savvy can pick it up in the future.

**Comment by patriknw** [comment]
yes, thanks for trying
