### ISSUE TITLE
FAILED: cluster.StressSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18417]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2859/consoleFull

**Comment by drewhk** [comment]
Another: https://jenkins.akka.io:8498/job/akka-nightly/2586/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3616/consoleFull

**Comment by patriknw** [comment]
The failing test step is "must use many actors with normal throughput" and that is verifying that no messages are lost, but

    [JVM-3] [INFO] [09/08/2015 15:31:15.217] [StressSpec-akka.remote.default-remote-dispatcher-6] [akka.tcp://StressSpec@a6.moxie:44812/system/transports/akkaprotocolmanager.tcp0/akkaProtocol-tcp%3A%2F%2FStressSpec%4010.0.1.233%3A38964-3] No response from remote. Handshake timed out or transport failure detector triggered.


    [JVM-1] [WARN] [09/08/2015 15:31:15.232] [StressSpec-akka.remote.default-remote-dispatcher-5] [akka.tcp://StressSpec@a3.moxie:51023/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FStressSpec%40a6.moxie%3A44812-1] Association with remote system [akka.tcp://StressSpec@a6.moxie:44812] has failed, address is now gated for [5000] ms. Reason: [Disassociated] 
    [JVM-1] [WARN] [09/08/2015 15:31:15.236] [StressSpec-akka.actor.default-dispatcher-17] [akka://StressSpec/deadLetters] received dead letter from Actor[akka://StressSpec/user/master-node-1#-577384404]: TreeJob(97,[B@3ce7b6e3,1,4,4)

**Comment by drewhk** [comment]
Similar, but now with `must use many actors with high throughput`

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3181/consoleFull

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
