### ISSUE TITLE
add FlowOps.zip() / FlowOps.zipWith() operator

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18411]
`zipWith` should allow immediate transformation to allow efficient operation.

**Comment by agolubev** [comment]
Is implementation suppose to use StageModule mechanism along with existing ZipWith.apply and FlowGraph.partial()?

**Comment by viktorklang** [comment]
@agolubev I was thinking something like the following, if you'd want to build upon it (needs some documentation and tests, and Java API but works for me at the moment):


~~~patch
diff --cc akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
index 720d970,0c73fef..0000000
--- a/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
+++ b/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
@@@ -985,6 -986,20 +985,26 @@@ trait FlowOps[+Out, +Mat]
    def log(name: String, extract: Out ⇒ Any = _identity)(implicit log: LoggingAdapter = null): Repr[Out, Mat] =
      andThen(Stages.Log(name, extract.asInstanceOf[Any ⇒ Any], Option(log)))

 -  /*
 -    trait FlowOps[+Out, +Mat] {
 -    import akka.stream.impl.Stages._
 -    type Repr[+O, +M] <: FlowOps[O, M]
 -   */
 -
+   def zip[U](right: Graph[SourceShape[U], _]): Repr[(Out, U), Mat] = zipMat(right)(Keep.left)
+
 -  def zipMat[U, Mat2, Mat3](right: Graph[SourceShape[U], Mat2])(matF: (Mat, Mat2) ⇒ Mat3): Repr[(Out, U), Mat3]
++  def zipMat[U, Mat2, Mat3](right: Graph[SourceShape[U], Mat2])(matF: (Mat, Mat2) ⇒ Mat3): Repr[(Out, U), Mat3] =
++    this.viaMat(Flow(right) { implicit b ⇒ r ⇒
++        import FlowGraph.Implicits._
++        val zip = b.add(Zip[Out, U]())
++        r ~> zip.in1
++        (zip.in0, zip.out)
++    })(matF)
+
+   def zipWith[U, Out2](right: Source[U, _])(f: (Out, U) ⇒ Out2): Repr[Out2, Mat] = zipWithMat(right)(f)(Keep.left)
+
 -  def zipWithMat[U, Out2, Mat2, Mat3](right: Graph[SourceShape[U], Mat2])(f: (Out, U) ⇒ Out2)(matF: (Mat, Mat2) ⇒ Mat3): Repr[Out2, Mat3]
++  def zipWithMat[U, Out2, Mat2, Mat3](right: Graph[SourceShape[U], Mat2])(f: (Out, U) ⇒ Out2)(matF: (Mat, Mat2) ⇒ Mat3): Repr[Out2, Mat3] =
++    this.viaMat(Flow(right) { implicit b ⇒ r ⇒
++        import FlowGraph.Implicits._
++        val zip = b.add(ZipWith[Out, U, Out2](f))
++        r ~> zip.in1
++        (zip.in0, zip.out)
++    })(matF)
+
    def withAttributes(attr: Attributes): Repr[Out, Mat]

    /** INTERNAL API */
~~~

**Comment by viktorklang** [comment]
Thinking about it, the following would be nice to have there too:

~~~scala
 def merge[U >: Out](right: Graph[SourceShape[U], _]): Repr[U, Mat] = mergeMat(right)(Keep.left)
  def mergeMat[U >: Out, Mat2, Mat3](right: Graph[SourceShape[U], Mat2])(matF: (Mat, Mat2) ⇒ Mat3): Repr[U, Mat3] =
    this.viaMat(Flow(right) { implicit b ⇒
      r ⇒
        import FlowGraph.Implicits._
        val merge = b.add(Merge[U](2))
        r ~> merge.in(1)
        (merge.in(0), merge.out)
    })(matF)
~~~

**Comment by agolubev** [comment]
Thanks, I'll add concat as well

**Comment by viktorklang** [comment]
@agolubev Concat already exists

**Comment by agolubev** [comment]
Yes, concat implemented for Source and Flow separately but can be moved to FlowOps.
Also concat does keep.both for materialization (but all others do only keep.right). Is it some idea behind keeping both Mats for concat?

**Comment by viktorklang** [comment]
@agolubev Yes, good point. Moving it to FlowOps would be much better. As for the default materialization, I have not real opinion, I figure Keep.both makes sense since it is not a linear flow but a junction. @rkuhn @drewhk @ktoso ?

**Comment by ktoso** [comment]
`Keep.both` sounds good to me for non linear things, not a very strong opinion though.

**Comment by viktorklang** [comment]
If we assume that "consistency is dog" we should either A) have the same default *everywhere* or the rule is that *linear transformations* have one default and junctions another. the rule must be simple though.

**Comment by rkuhn** [comment]
Fully generic descriptions are available via explicit parameters or (in the extreme cases) the Graph DSL. Otherwise the rule should be that we deal in a linear, fluid DSL, meaning that `Keep.left` should be the default everywhere apart from `runWith` (which is very much intentional as well as intuitive). This is the most simple and intuitive thing we can do.

**Comment by viktorklang** [comment]
Ok, let's run with Keep.left *always* being the default?

-- 
Cheers,
√

**Comment by rkuhn** [comment]
Just to be clear: “always” means everything except for `runWith`, right? `runWith` is there precisely to override such that its argument defines the materialized value, regardless of whether this is logically to the left or to the right of the Flow.

**Comment by viktorklang** [comment]
I guess an exception can be made for any *run* op.

On Wed, Sep 23, 2015 at 8:32 PM, Roland Kuhn <notifications@github.com>
wrote:

> Just to be clear: “always” means everything except for runWith, right?
> runWith is there precisely to override such that its argument defines the
> materialized value, regardless of whether this is logically to the left or
> to the right of the Flow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/18411#issuecomment-142690323>.
>



-- 
Cheers,
√

**Comment by rkuhn** [comment]
Right, my mistake!
