### ISSUE TITLE
http: formField(s) and multipart/form-data

### ISSUE THREAD

**Issue by stanch** [akka/akka#18426]
It seems that `formField` and `formFields` directives fail to read the fields from `multipart/form-data` if their arguments (i.e. field names) are specified not in the same order as they are in the data. I don’t have a distilled reproduction yet, but I observed this behavior several times and managed to switch it on and off by rearranging the field names. Unfortunately the order is by no means reliable. It seems that even the same browser can choose to send the same fields in a different order. The error message is:
```
The form field X was malformed. Unexpected end of multipart entity
```

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
