### ISSUE TITLE
CRDT Registry that is optimized for Cluster Singleton

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18434]
When writes are done by a Cluster Singleton we should be able to use the cluster membership information to decide which data to use when merging. This is more safe than LWWRegistry for that that use case.

Then we can use this in the ddata mode of Cluster Sharding.

**Comment by smlin** [comment]
@patriknw Do you mean we must prefer to data from the younger singleton?

**Comment by patriknw** [comment]
yes, that should be the latest writer

**Comment by patriknw** [comment]
After some thinking my conclusion is that LWWRegister is safe to use from Cluster Singleton, so we don't need another implementation. I have clarified this in the docs in PR https://github.com/akka/akka/pull/21612
