### ISSUE TITLE
PersistentRepr.manifest cleaned up by IdentityEventAdapters

### ISSUE THREAD

**Issue by Horusiath** [akka/akka#18439]
`WriteJournalBase.adaptToJournal` method uses event adapters to map PersistentRepr &rArr; PersistentRepr instance. Unfortunately I've seen that manifest is always taken from event adapters, and never retained from an original message. In default configuration - `IdentityEventAdapters` - this means, that the input message manifest is always erased.

**Comment by patriknw** [comment]
Normally there is no manifest in the incoming PersistentRepr, but as @Horusiath explained to me for test purposes one may want to send `WriteMessages` directly to the journal.

**Comment by ktoso** [comment]
Good catch, thanks for reporting @Horusiath!
