### ISSUE TITLE
Investigate Aalto async (pushpull) XML parser

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18444]
Allows streaming, async XML parsing. Not anactive project though.

https://github.com/FasterXML/aalto-xml

**Comment by jypma** [comment]
We actually started working on a (very basic) XML parser that basically transforms a `Source[ByteString]` into a `Source[XMLEvent]`. Let me know if the aalto parser turns out hard to integrate, I'm sure we can release our XML parsing code.

**Comment by drewhk** [comment]
Looking at their interfaces it should be rather easy to embed it in the PushPullStage, but I have not tried in practice.

**Comment by agolubev** [comment]
Perhaps #18620 solving this in general way

**Comment by drewhk** [comment]
This parser I mentioned is non-blocking though and fits our model perfectly.

**Comment by ennru** [comment]
This idea became one of the first things for [Alpakka](https://doc.akka.io/docs/alpakka/current/data-transformations/xml.html).
