### ISSUE TITLE
Configure "eagerness" for tcp connection pipelining

### ISSUE THREAD

**Issue by divijan** [akka/akka#18456]
My application.conf has this:

    http.host-connection-pool {
      max-connections = 1
      pipelining-limit = 2
    }

and requests get pipelined across the connections. However, if I change max-connections to something else than 1 and make as many parallel requests, akka-http will create several connections. Is there a way to tell it to try and saturate the pipeline first?

**Comment by jrudolph** [comment]
No, the strategy to select a slot is currently hard-coded. See here: https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala#L166

**Comment by ktoso** [comment]
Do I understand correctly that making it configurable would be a "nice to have", but doesn't seem very critical to me, right?

**Comment by jrudolph** [comment]
At least the logic is centralized somewhere so customizing strategies and make them configurable shouldn't be too hard. So, yes, I think prioritizing whether or when to do the work would be the hardest part ;)

**Comment by divijan** [comment]
Thanks for the feedback! It is not critical.

**Comment by rkuhn** [comment]
To me this sounds very much “nice to have” as in “not really important unless someone really wants to contribute it”. I’d vote to close and wait for someone to reopen it when submitting a PR.

**Comment by ktoso** [comment]
I agree, don't see a strong incentive to work on this for now. 
Closing as obsolete
