### ISSUE TITLE
Typo in the documentation for AKKA 2.4.RC2 ?

### ISSUE THREAD

**Issue by angelcervera** [akka/akka#18458]
In the documentation of AKKA 2.4.RC2 (http://doc.akka.io/docs/akka/2.4.0-RC2/intro/getting-started.html) said:

> Prerequisites
> Akka requires that you have Java 8 or later installed on you machine.
> Typesafe provides versions of Akka that are compatible with Java 6, 7 and 8.

Maybe it is a typo. In the first line said that AKKA need Java 8 or later but in the next said that AKKA is compatible with Java 6 and Java 7.

Is it a type? Or Typesafe distribute other different version of AKKA?

Maybe is good clear it in the documentation.

**Comment by ktoso** [comment]
Hi @angelcervera,
good point that it may need better wording in there, I'll fix that.

Akka 2.4 indeed requires Java 8. For customers we provide an Reactive Platform (RP for short) version of Akka which is based on 2.3 however has some of the 2.4 features, which for example means that you get the a new feature which would have been Java 8 only, backported to a 2.3.x-like build of Akka (as part of RP). Here's the feature matrix for it: http://www.typesafe.com/products/typesafe-reactive-platform

Also, I did a webinar on the subject (and features of Akka 2.4 and the RP version) 2 weeks ago which should clear up what these versions mean and how it works: https://www.typesafe.com/resources/video/akka-2-4-plus-new-commercial-features-in-typesafe-reactive-platform

**Comment by ktoso** [comment]
Merged the docs miprovement.
