### ISSUE TITLE
Weirdness with akka-http path matching in routes

### ISSUE THREAD

**Issue by alias1** [akka/akka#18460]
So i'm not 100%, but after an hour or few trying to figure out what I was doing wrong, it seems that directly nested calls to `path` (or similar) will cause a route to not match.

Doesn't work:
```
path(JavaUUID) { id =>
  path("edit") {
    post {
      complete("ok")
    }
  }
}
```

Works:
```
path(JavaUUID / "edit") { id =>
  post {
    complete("ok")
  }
}
```

I get that the latter looks 'nicer' in this instance, but for composability (or at least my sanity) I would have expected the first to work still. Am I missing something obvious, or is this an unintended 'feature'?

Edit: Re-reading the description of `path` I think the solution to my problem is `pathPrefix` Please close if that's the case.

**Comment by jrudolph** [comment]
Yes, you need to use `pathPrefix` on outer route parts and use `path` only in the most nested routes where you want to make sure that you matched the complete path. Closing.
