### ISSUE TITLE
Akka HTTP: LdapAuthenticator - community project

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18472]
This class https://github.com/spray/spray/blob/master/spray-routing/src/main/scala/spray/routing/authentication/LdapAuthenticator.scala#L39

It's rather simple but was not really heavily maintained. Question to ask ourselves here is if we want to support it or leave up to the ecosystem to pick it up.

**Comment by ktoso** [comment]
Note to self, sadly not documented in spray: http://spray.io/documentation/1.2.2/spray-routing/security-directives/authenticate/#from-ldap

**Comment by ktoso** [comment]
We have reviewed and discussed the above mentioned piece of code.
We do not want to pull it into Akka HTTP, it was not properly maintained nor tested in Spray, it does not seem to have been used a lot as well. We would like to ask the community to step up and take care of it if possible (it can be based on the above code, it's a simple spot to start out from).

**Comment by patriknw** [comment]
sounds like an external project
