### ISSUE TITLE
Http: Document or simplify "json metadata and file upload" pattern

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18471]
From a discussion on gitter: we should document or make it even simpler if it's too hard to get multiple multipart form upload and json (AFAICS this is possible, maybe just hard to discover).

Use case is "uploading JSON metadata about the file, and the file right next to it". 
This may actually be a problem if the metadata comes after the file in the request, so may need explicit hints and docs.

Here's how to test using curl: http://stackoverflow.com/questions/3938569/how-do-i-upload-a-file-with-metadata-using-a-rest-web-service

**Comment by jrudolph** [comment]
I think the main problem with recommending anything like this is that there are multiple ways of doing something like that that may be equally valid. IMO the goal should be to make users aware of the primitives of HTTP so that they can use them in the way that suites their use case best.

A few ways of how you could post metadata aside from using several `multipart/form-data` fields:

 * use custom headers per part that carries a file similar to how the filename is transported in the first place
 * use regular query parameters along with a `multipart/form-data` payload

Both approaches would have the advantage that you don't depend on the ordering of parts to receive the metadata along with the actual data.

**Comment by ktoso** [comment]
Good hints, thanks @jrudolph! I think this will end up being a docs page about file uploads, explaining the techniques.

**Comment by ktoso** [comment]
@jrudolph Thanks for the answer on akka-user, I'll copy it here so I can refer to it while writing the docs:

```
Hi,

the approach that Konrad showed will work, however, the problem with the suggested approach is that it will load the complete file into memory which limits the number of concurrent uploading requests severely. Any multipart entity is a natural stream of parts so your original approach is a good start.

On Friday, September 11, 2015 at 4:12:02 PM UTC+2, lucian enache wrote: 
...

What do you mean by "split"? If you post them as multipart you will have several parts which are split automatically and will be delivered as elements on the `parts` stream. Inside of your `mapAsync` you can inspect the metadata (like the filename of a part, or the field name for which it was posted) before doing anything with the data (but then don't do `.map(_.entity.dataBytes)` first), so there's no really the need to "split" processing but just decide which processing you want to do based on the metadata of each part. If you need to correlate both parts with some context things will be a bit harder, I would then suggest to return some result for each part inside of mapAsync (e.g. the filename of the part together with the future representing the result of processing that part) and then collect all these result and do whatever is necessary before completing.

Here's a sketch:

case class ProcessingResult(partFileName: String, result: Result)
def processBinaryPart(part): Future[ProcessingResult] = ...
def processJsonPart(part): Future[ProcessingResult] = ...

entity(as[Multipart.FormData]) { (formData) =>
  val processedParts = formData.parts.mapAsync(1) { part =>
    part.filename match {
      case Some("xyz.bin") => processBinaryPart(part)
      case Some("abc.json") => processJsonPart(json)
    }
  } // result of mapAsync is Source[ProcessingResult, ...]
  // now collect all results into a map for further processing
  .runFold(Map.empty[String, ProcessingResult])((map, res) => map += res.partFileName -> res)
  // result is a Future[Map[String, ProcessingResult]]
  
  // wait for processing to have finished and then create response
  onSuccess(processedParts) { resultMap =>
    complete { ...
    }
  }
}
```

**Comment by johanandren** [comment]
Related: #16841

**Comment by ktoso** [comment]
Steps:
- [ ] document - https://github.com/akka/akka/issues/18893
- [ ] simplify - https://github.com/akka/akka/pull/18946

**Comment by nykolaslima** [comment]
@ktoso since #18946 is merged, we can mark your checkbox as done, right? :dancer: 

BTW, thanks @johanandren for the implementation, I was following this issue and the solutions looks nice and easy to me :smile:

**Comment by ktoso** [comment]
Probably wrong milestone though?

**Comment by johanandren** [comment]
Ah, good catch, thanks!
