### ISSUE TITLE
Uri parsing error

### ISSUE THREAD

**Issue by RomanIakovlev** [akka/akka#18479]
I see the following exception when creating the `Uri` object:

    akka.http.scaladsl.model.IllegalUriException: Illegal URI reference: Invalid input '=', expected '+', query-char, '%', '&', '#' or 'EOI' (line 1, column 35): /?EVENT=itemGroup&GROUP=10380?page=2
                                  ^
	at akka.http.scaladsl.model.IllegalUriException$.apply(ErrorInfo.scala:40) ~[com.typesafe.akka.akka-http-core-experimental_2.11-1.0.jar:na]
	at akka.http.scaladsl.model.Uri$.fail(Uri.scala:748) ~[com.typesafe.akka.akka-http-core-experimental_2.11-1.0.jar:na]
	at akka.http.impl.model.parser.UriParser.fail(UriParser.scala:61) ~[com.typesafe.akka.akka-http-core-experimental_2.11-1.0.jar:na]
	at akka.http.impl.model.parser.UriParser.parseUriReference(UriParser.scala:33) ~[com.typesafe.akka.akka-http-core-experimental_2.11-1.0.jar:na]
	at akka.http.scaladsl.model.Uri$.apply(Uri.scala:204) ~[com.typesafe.akka.akka-http-core-experimental_2.11-1.0.jar:na]
	at akka.http.scaladsl.model.Uri$.apply(Uri.scala:176) ~[com.typesafe.akka.akka-http-core-experimental_2.11-1.0.jar:na]

The stack trace is provided from the first entry of Akka library.

I'm not responsible for producing the uri, `/?EVENT=itemGroup&GROUP=10380?page=2`, but it looks valid to me, if strange.

Akka version is 2.4-RC1. I tried to search for similar issues, but haven't found any.

**Comment by 2beaucoup** [comment]
Is the second "?" supposed to be a "&"? The parser groups the query params separated by "&" and sees the second param as `GROUP=10380?page=2` which is invalid as it has two "="s.

**Comment by RomanIakovlev** [comment]
I guess it is, but, again it's not my url, I'w writing a web crawler in Akka and that was one of the failed cases I've found. Nevertheless, this URL is valid, because subsequent entries of `?` are supposed to be parsed as data within the query component, as per http://tools.ietf.org/html/rfc3986#section-3.4.

I see 2 options here. First one is to treat `?` as `&`, i.e. add new parameter. Second one is to parse the value of `GROUP` parameter as `10380?page=2`.

**Comment by 2beaucoup** [comment]
In that case you should use

```scala
new UriParser(input, uriParsingMode = ParsingMode.RelaxedWithRawQuery)
```

directly. See https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/resources/reference.conf#L211-L213.

**Comment by RomanIakovlev** [comment]
Okay, thanks. While `UriParser` class is private, one can use `Uri#apply(input: ParserInput, mode: Uri.ParsingMode)` with `Uri.ParsingMode.RelaxedWithRawQuery` as the second parameter to achieve the same result.

I still think it's a workaround rather than proper solution though. Question marks and equal signs are not prohibited inside the query. Just sayin'.

**Comment by ktoso** [comment]
Hi @RomanIakovlev,
thanks for reporting and linking the right section of the RFC. I agree, multiple question marks are allowed, and the second question mark is simply part of the key/value then, it's a bit weird but seems to be consistent with the spec and other libraries.

**Comment by 2beaucoup** [comment]
As pointed out above the problem here isn't the "?". By default the parser tries to group the query into key-value-pairs but chokes on the double "=".

**Comment by ktoso** [comment]
Ah now I see the actual problem char... Thanks for pointing it out.
Still though it seems the current parser is too restrictive, as:

```
   query         = *( pchar / "/" / "?" )
   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
   pct-encoded   = "%" HEXDIG HEXDIG
   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
   sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "=" 
```

**Comment by jrudolph** [comment]
As the query grammar isn't part of the RFC, you need to choose how to interpret the `'='` characters which isn't unambiguously possible. So, I'd say everything works as intended. Either, you have a query which conforms to the de-facto-standard of using well-formed key value pairs, so the strict parser can translate it into key value pairs, or you don't have such queries and in such case you configure the relaxed mode in which case you can choose any parsing you like.

**Comment by 2beaucoup** [comment]
As this comes up from time to time we should either improve the documentaton or support this case better by providing easier access to the raw (RFX-compliant) query and/or not failing by default if parameter extraction fails.

WDYT?

/cc @sirthias

**Comment by RomanIakovlev** [comment]
If you want my opinion, maybe it would make sense to try parsing the query string first, but fall back to providing it as a single value in case it's formatted in a non-standard way. Or, alternatively, parse what it's possible to parse, and provide the unparse-able remainder as-is.

**Comment by ktoso** [comment]
To me it sounds like strict has it's own benefits - it's indeed strict by the de facto standard how these are being used in most applications, and this more relaxed mode also makes sense (though `relaxed` is taken for including non-printable chars AFAIR), so how about making this mode that would accept still only printable chars, however allow these `=` etc?

**Comment by RomanIakovlev** [comment]
So you mean something like `StrictWithRawQuery`, as opposed to `RelaxedWithRawQuery`? I think it makes sense. Another thing is, maybe the exception message could suggest using such method if query parsing fails with the default, strict parsing? This opportunity is not easily discoverable now.

**Comment by 2beaucoup** [comment]
An alternative solution to making URI parsing more robust would be to model the query of an URI as a plain string that is checked for RFC compliance and do the actual parsing in the parameter directives or by a method that parses key value pairs on demand.

This way usages where to uri is simply forwarded or ignored don't pay the price of parsing (and failing). That is only done when explicitly requested (by a directive).

WDYT @jrudolph @sirthias?

**Comment by drewhk** [comment]
That is an interesting idea, kind of like it. Although I expect some people be tripped up by needing an explicit directive to do the query parsing.

**Comment by 2beaucoup** [comment]
The good think is that we already have [ParameterDirectives](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/parameter-directives/index.html#parameterdirectives).

We can maintain `Uri.query` support by replacing it with a method or a lazy val.

**Comment by jrudolph** [comment]
I kind of like that proposal, as well, @2beaucoup . I guess we would need to check how it plays out with compatibility but if we can make sure that failing in the `parameters` directive produces similar output on  non-standard queries as the request parser does now, it would probably be fine.

**Comment by jrudolph** [comment]
So, for standard URIs and people using either the parameter directives or which would be accessing the now lazy query field, semantics wouldn't change at all (aside from the parsing being deferred).

**Comment by 2beaucoup** [comment]
@jrudolph Exaclty! :)

It seems that all that's required is making `Uri.query` lazy.

**Comment by 2beaucoup** [comment]
Would be nice if we could get rid of `Uri.ParsingMode.RelaxedWithRawQuery` on the way which seems to be a source of confusion and whose result is hard to access.

**Comment by sirthias** [comment]
+1 from my side for @2beaucoup's "deferred parsing" idea.
Having the parsing errors be triggered in the routing layer rather than in the low-level parser also increases user flexibility in how to deal with problem.

The only thing that we have to make sure is that we don't move the parsing logic into the directive itself, since then it wouldn't be available to users that don't want to rely on the routing DSL.
There needs to be a way to invoke the query parser from userland even without the routing DSL.
