### ISSUE TITLE
Half-closed HTTP connection by the peer should not keep hanging indefinitely

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18482]
Currently, the stream is kept hanging (i.e. a resource leak) if a response entity stream has not yet completed.

The situation is this:

 - client makes request
 - server starts streaming entity (but currently no data is available)
 - client closes the connection

Closing in this case means, that the client half-closes its side of the connection and goes away. In the server pipeline the network input side dispatches completion but it has not yet discovered that the other side isn't there any more (and it will never as long as it doesn't try to send something). In the best case it will be detected when the next package is answered with a RST but if the peer is just not answering any more we never cleanup.

Arguably, this is bad behavior for an HTTP client to go away only half-closing the connection when there is still data pending. It should cancel a connection if it goes away from as this is the only way to notify the peer that it will not read any more.

I don't think this can be fixed other than by enforcing idle-timeouts on the connection. I just wanted to document this particular case here.

/cc @sirthias

**Comment by drewhk** [comment]
Timeout stages are coming: https://github.com/akka/akka/pull/18467

**Comment by jrudolph** [comment]
Yes, I know :) I added this ticket more for reference than as an actual task to fix it here.

Also, as always, the line between a very slow peer and a peer that has gone away is usually very thin, so the scenario of having an infinite stream that may not send anything for a prolonged period of time, is maybe not a good use of a TCP-based protocol in the first place: if you rely on cleaning up resources if the peer goes away you have to send something from time to time to probe that the peer is still there (like TCP keep-alive, websocket pings, or a manual ping protocol).

**Comment by drewhk** [comment]
I will probably add a keepAliveInject stage as a counterpart to the idle-timeout stage. I guess we need a throttle stage, too.

**Comment by ktoso** [comment]
I think that's closed since we introduced idle timeouts for all connections.
