### ISSUE TITLE
Source.subscriber's Subscriber should log errors if subscribed more than once

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18486]
This was posted to akka-user:

```scala
object Main2 extends App{
  implicit val system = ActorSystem("streamakka")
  implicit val materializer = ActorMaterializer()
  val sub1=Source.subscriber[String].to(Sink.foreach(println)).run()

  val pub1=Source.repeat("p1").runWith(Sink.publisher)
  val pub2=Source.repeat("p2").runWith(Sink.publisher)

  pub1.subscribe(sub1)
  pub2.subscribe(sub1)
}
```

Supposedly this does not throw, but only takes from one of the streams. Instead it should error on the 2nd subscription.

**Comment by drewhk** [comment]
fat fingers, meant 1.1 at the first time, not invalid

**Comment by ktoso** [comment]
Update: instead of throwing we should log an error that a subscriber was onSubscribe-ed multiple times,
as explained in detail here: https://github.com/akka/akka/pull/18521/files#r41328256

(otherwise we'd violate the RS spec).

**Comment by drewhk** [comment]
Reopened, since it is not fully solved yet.

**Comment by rkuhn** [comment]
This loses out against the rock (RS spec) and the hard place (being light-weight for VirtualProcessor).
