### ISSUE TITLE
Cluster Sharding persistent state deletion utility

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18485]
We want to simplify the task of "oh, my sharding data got corrupted! I know it's safe to delete it. How can I do that?"

It should be a stand-alone tool that can be run by ops / devs on the journal to clean up the data before starting the app. 

It would quite smart if it could be still packaged together with the sharding jar though, since one could then simply from sbt (as one has the proper db/journal config in application.conf already) issue `runMain akka.cluster.sharding.DeleteOldShardingData` or something like this.

For more background see here: https://github.com/akka/akka/pull/18436/files#diff-ad4d26653ea95b6bbfa0d84b90497355R292

**Comment by ktoso** [comment]
It could also check the old persistenceId, and say "hey, you're now on 2.4 but have old 2.3 data persisted - that's not used anyway, but want me to delete it?"

**Comment by patriknw** [comment]
I like this, would be good to make it before 2.4.0.

**Comment by patriknw** [comment]
remember to update migration guide "Cluster Sharding internal data"
