### ISSUE TITLE
Add contentSizeLimit(...) directive

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18493]
As suggested by @drewhk in https://github.com/akka/akka/pull/18491#issuecomment-140740155
Maybe we could implement a simple directive that limits the allowed max allowed upload entityBytes length, per path instead of only relying on the global setting.

For example one path can take 2GB, but another one only 100MB.

Most likely doable by decorating the context's bytes Source with a size counting + aborting stage.

**Comment by jrudolph** [comment]
Also see #16468.

**Comment by ktoso** [comment]
Thanks for the cross-ref! Kind of the same thing... Here we're considering to make this a directive, in that thread the conclusion seems to be to apply a limiter on the stream itself. I'll keep both open for now and see which one makes most sense when picking this up.

**Comment by ktoso** [comment]
I believe this is solved:

```
  /**
   * Fails the stream with [[akka.http.scaladsl.model.EntityStreamSizeException]] if its request entity size exceeds
   * given limit. Limit given as parameter overrides limit configured with `akka.http.parsing.max-content-length`.
   *
   * Beware that request entity size check is executed when entity is consumed.
   *
   * @group misc
   */
  def withSizeLimit(maxBytes: Long): Directive0 =
    mapRequestContext(_.mapRequest(_.mapEntity(_.withSizeLimit(maxBytes))))

  /**
   *
   * Disables the size limit (configured by `akka.http.parsing.max-content-length` by default) checking on the incoming
   * [[HttpRequest]] entity.
   * Can be useful when handling arbitrarily large data uploads in specific parts of your routes.
   *
   * @group misc
   */
  def withoutSizeLimit: Directive0 = MiscDirectives._withoutSizeLimit
```
