### ISSUE TITLE
Idea: Slick directives

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18504]
Interesting idea via @adamw : https://github.com/softwaremill/slick-eventsourcing/blob/master/example/src/main/scala/com/softwaremill/example/api/RoutesSupport.scala#L95

Some very simple Slick integration directives. Could live outside of Akka of course, for example as a community project :)

**Comment by ktoso** [comment]
// cc @szeiger do you think this may make sense?

**Comment by szeiger** [comment]
I can't really offer a useful opinion because I don't know anything about the design of akka-http. Where do you hide the sources for that anyway?

**Comment by ktoso** [comment]
> I can't really offer a useful opinion because I don't know anything about the design of akka-http.
> Where do you hide the sources for that anyway?

Sources are here: https://github.com/akka/akka/tree/release-2.3-dev :smile:  Until we merge with master (2.4.x)

**Comment by ktoso** [comment]
Closing this, it could be a separate project if needed but the Future/Source directives should be mostly enough to work nicely with Slick already
