### ISSUE TITLE
Fix scaladoc warnings (release-2.3-dev)

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18500]
Mostly link problems

**Comment by drewhk** [comment]
There are 150 warnings

**Comment by agolubev** [comment]
@drewhk, as far as I understand it's about 
>[warn] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-stream/target/java/akka/stream/io/Implicits.java:20: warning - Tag @link: reference not found: Source
and this must be fixed by adding package like: [[Source]] -> [[akka.stream.scaladsl.Source]]

**Comment by wlk** [comment]
There is also a number of warnings that appear when running `sbt doc` locally that are not logged on jenkins, for example:
```
[warn] /home/w/projects/akka/akka-actor/src/main/scala/akka/io/Inet.scala:120: Could not find any member to link for "java.net.Socket#setSendBufferSize".
```
This error basically means that it's unable to find Java class, and in the result there is no clickable link.

Or something like that:
```
[warn] /home/w/projects/akka/akka-actor/src/main/scala/akka/actor/ActorSystem.scala:290: The link target "ActorSystem#actorSelection" is ambiguous. Several members fit the target:
[warn] (path: akka.actor.ActorPath): akka.actor.ActorSelection in class ActorSystem [chosen]
[warn] (path: String): akka.actor.ActorSelection in class ActorSystem
```

In this case the link is clickable, but can lead to wrong version of the method.

**Comment by wlk** [comment]
I'll start off with fixing what is reported in jenkins, and will move my previous comment to new issue

**Comment by wlk** [comment]
I'm fixing those warnings in PR #20000

**Comment by wlk** [comment]
Small update: I have went through the first iteration of fixing link problems.

But after a while I have noticed that warnings reported by jenkins are actually Javadoc warnings, not Scaladoc warnings

I'm preparing another PR where I fix the rest of warnings.

**Comment by ktoso** [comment]
Right :)
Thanks a lot (you know how to get javadocs right? via genjavadoc)

**Comment by ktoso** [comment]
I'm not sure if all is fixed, so keeping open still.

**Comment by rkuhn** [comment]
I’d vote for adding a ticket that makes ScalaDoc or JavaDoc warnings fail PR validation—and then getting that across the PR merge process :-) And I think that this particular ticket should be closed.

/cc @patriknw

**Comment by patriknw** [comment]
I'm all for enforcing no warnings if would be possible to tell that some should be ignored.

For example "link target is ambiguous" is something that I never get the hang of, the "Quick crash course" is not possible (for me) to understand and sometimes it simply doesn't work no matter what I try. Yeah, I know @rkuhn described some addition things around it, and I even have that note left, but it doesn't always work.

This is my old note:

> the link target is first split at all dots (ALL of them, except when escaped with \). Then each of the parts can end either with ! (classes / types), $ (objects) or * (methods). If omitted, it is $ for package names and ! for classes.

> for the * part everything up to the * is taken and matched to the beginning of the string representation of the full method signature (as printed in the “helpful” message but sans the spaces)

> example:

> ```
[[akka.typed.ActorContext!.watch[U]* watch typed actors]]
[[akka.typed.ActorContext!.watch(akka\.actor* watch untyped actors]]
```

Then we have `Could not find any member to link for "java.lang.Iterable"` or similar cross-references.

I vote for closing this and spend the effort on cleaning up master. @wlk has already done some great contributions.
