### ISSUE TITLE
Document how HTTP 413 works when too large payload

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18509]
Reported in akka-user thread: [No response is returned when the request payload exceeds the configured max-content-length](https://groups.google.com/forum/#!topic/akka-user/9khtYYO0UtQ)

It seems we don't render a 413 response when the max-content-length is exceeded according to that report.
We definitely should IMHO, so let's make sure we do

**Comment by ktoso** [comment]
Works for me, tested using the `akka.http.scaladsl.TestServer`, response is proper:

```
$ http POST 127.0.0.1:9001/ hello=1212121212121212121212121212121212
HTTP/1.1 413 Request Entity Too Large
Connection: close
Content-Length: 74
Content-Type: text/plain; charset=UTF-8
Date: Thu, 17 Sep 2015 16:58:20 GMT
Server: akka-http/2.3.12

Request Content-Length of 47 bytes exceeds the configured limit of 1 bytes
```

**Comment by jrudolph** [comment]
The problem may be that clients cannot deal with an "early response" i.e. one received before the complete request entity has been sent. To test this, you would need to make sure that the sent entity is bigger than any intermediate buffers, i.e. that some bytes are still in `curl`'s application-level buffers.

That said, you demonstrated that akka-http does send the response. Any remaining issues are likely due to clients not being able to read them (and it's not clear if they should be able to read them because behavior like this isn't really specified in HTTP).

**Comment by ktoso** [comment]
Thanks a lot the for the additional info/thoughts :)

**Comment by 2beaucoup** [comment]
https://tools.ietf.org/html/rfc7230#section-6.5 states
```
A client sending a message body SHOULD monitor the network connection
for an error response while it is transmitting the request.  If the
client sees a response that indicates the server does not wish to
receive the message body and is closing the connection, the client
SHOULD immediately cease transmitting the body and close its side of
the connection.
```

**Comment by jrudolph** [comment]
Ah, yes, thanks @2beaucoup for looking that up. Unfortunately, clients using a blocking API will have a hard time implementing this suggestion and then they will still need to decide if the response is valid or if it should be thrown away. Also, it is likely to run into the usual FIN / RST race conditions where the client may discard the response buffers unread when it tries to send on a connection that is being aborted by the other side.

**Comment by ktoso** [comment]
Maybe that's actually something worth documenting... I'll reopen the ticket and and some docs in case people run into this.

**Comment by ktoso** [comment]
(Or make it a different ticket once my laptop has power again, opening so I don't loose track of it)

**Comment by 2beaucoup** [comment]
Thx @jrudolph for the additional infos.

BTW: How does the akka-http client behave in such a scenario?

**Comment by RichardBradley** [comment]
(Related discussion re aborting large uploads part-way-through: https://github.com/akka/akka/issues/18203#issuecomment-139192071

Once that has been resolved, I think there could be a new section added to the docs to explain all this, that can be cited when this comes up.)

**Comment by ktoso** [comment]
Changed this into a documentation ticket, to explain how the HTTP 413 response code is generated, and that single threaded client libraries may not be smart enough to stop writing even though we've sent the response.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
