### ISSUE TITLE
Akka Streams & HTTP 1.0 - Issue with HttpHeader

### ISSUE THREAD

**Issue by gzoller** [akka/akka#18512]
Hello,

I noticed that in the scaladsl the HttpRequest takes a seq headers of type 
akka.http.scaladsl.model.HttpHeader in the constructor, but the addHeader() method accepts javadsl.model.HttpHeader.   What's going on here?  Seems like that should accept scaladsl.model.HttpHeader here.

**Comment by ktoso** [comment]
As you probably noticed, this'll work properly since:

```scala
// scaladsl:
abstract class HttpHeader extends javadsl.model.HttpHeader 
```

So the method can take either, scala or javadsl.

**Comment by gzoller** [comment]
Yeah.... but its not quite as seamless as that.
```
val h = HttpRequest(uri=url).addHeader(headers.ProductVersion(version="2.0"))
```
produces
```
[error]  found   : akka.http.scaladsl.model.headers.ProductVersion
[error]  required: akka.http.javadsl.model.HttpHeader
[error] 			val h = HttpRequest(uri=url).addHeader(headers.ProductVersion(version="2.0"))
```

If the hierarchy is working, shouldn't ProductVersion be a HttpHeader in this use case?  If I use asInstanceOf[] to force it to being a javadsl.modl.HttpHeader it will compile but goes boom with a cast exception when run.
