### ISSUE TITLE
Parameters does not accept Seq[String] as a parameter type

### ISSUE THREAD

**Issue by jasonmartens** [akka/akka#18518]
The following code fails to compile:

```scala
val logReaderRoute =
    pathPrefix("actions" / "logreader") {
      pathPrefix(JavaUUID) { mediauuid =>
        parameters("startTime".as[Long].?, "endTime".as[Long].?, "messageTypes".as[Seq[String]].?)
        { (startTime, endTime, messageTypes) =>
          onSuccess(queryLog(MediaId(mediauuid.toString))) { source =>
            val entity = HttpEntity.Chunked.fromData(ContentTypes.`application/json`, source)
            val response = HttpResponse(status = StatusCodes.OK, entity = entity)
            complete(response)
          }
        }
      }
    }
```

With the error:
```
Error:(20, 19) too many arguments for method parameters: (pdm: akka.http.scaladsl.server.directives.ParameterDirectives.ParamMagnet)pdm.Out
        parameters("startTime".as[Long].?, "endTime".as[Long].?, "messageTypes".as[Seq[String]].?)
                  ^
```

**Comment by ktoso** [comment]
Hi @jasonmartens,
The reason is that you can not simply say `messageTypes.as[Seq[String]]` since we the marshaller is not sure how to unmarshal this, sometimes seqs are represented as "`a,b,c`" in requests, and sometimes it's represented as "`a;b;c`" or maybe event "`messageTypes[0]=a&messageTypes[1]=b`" or other encoding schemes.

What's the encoding you're using?
Is there a encoding setting we could standardise on and provide an optional trait with unmarshalling for it?

// cc @sirthias @jrudolph @rkuhn

**Comment by jasonmartens** [comment]
I found this after a bit of searching:
http://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string

It seems there is not a well-defined standard way to do this. Personally, I prefer ```?cars=Saab,Audi``` since it is the most compact and makes it clear there are multiple values for one named query parameter. 

This is a new API I'm building, so I don't have anything existing I need to interoperate with.

**Comment by julienrf** [comment]
What if the value you want to pass contains a comma? You would have to escape it. IMHO the best way is `?cars=Saab&cars=Audi`.

**Comment by ktoso** [comment]
For the record:
- there is no standard
- Spring MVC does `phone=2&phone=3 => Array(2,3)` http://stackoverflow.com/questions/9768509/can-spring-mvc-handle-multivalue-query-parameter
- Some APIs I've seen use `things=a,b,c`
- Play uses the "bound to the same name" pattern (I've seen it some times as well in the wild), like Spring MVC does http://stackoverflow.com/questions/11291136/play-framework-2-use-arraystring-in-route
- PHP uses `things[]=a,things[]=b`

So it's hard for us to pick "the one", though if we were to pick one, it seems the Spring and Play used one would be most consistent with that play/java people may expect. I would **not** make it default though, but an optional type.

**Comment by ktoso** [comment]
@jrudolph @sirthias AFAICS it's not quite possible to implement the `as[Seq...]` for the `things=1&things=2` directly, would be better served as a directive? Or I'm missing something.

**Comment by ktoso** [comment]
So while I'm not yet sure how to impl the `things=1&things=2`, the "CSV-style params" are very simple to do, so you can just add this trait 

Feel free to copy and use this trait for now @jasonmartens, until we decide what to do about it (at least, it'll be in the docs, at most, it may be an optional trait available soon):

```scala
      trait CsvParameters {
        implicit def csvSeqParamMarshaller: FromStringUnmarshaller[Seq[String]] =
          Unmarshaller(ex ⇒ s ⇒ Future.successful(s.split(",")))

        implicit def csvListParamMarshaller: FromStringUnmarshaller[List[String]] =
          Unmarshaller(ex ⇒ s ⇒ Future.successful(s.split(",").toList))
      }
      object CsvParameters extends CsvParameters


// and a test
    "as[Seq[String]]" in {
      import CsvParameters._
      Get("/example?names=a,b,c") ~> {
        parameter('names.as[List[String]]) { names ⇒
          complete(names.toString())
        }
      } ~> check {
        responseAs[String] shouldEqual "List(a, b, c)"
      }
    }

```

**Comment by ktoso** [comment]
In fact, the `cars=one&cars=two` is already implemented as well, see `ParameterDirectives`:

```scala
      Get("/person?age=19&hobby=cooking&hobby=reading") ~> {
        parameter('hobby.*) { echoComplete }
      } ~> check { responseAs[String] === "List(cooking, reading)" }
```

And here are the docs: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/parameter-directives/parameters.html#Description

Sorry I did not realise right away, still loading all of Http into my brain...

So I assume this to be fixed, just left to decide if we want to provide the csv style (probably not though).

**Comment by jasonmartens** [comment]
Great, thanks for the help. Feel free to close this issue.

**Comment by ktoso** [comment]
Merged support for `as(CsvString)` // cc @jasonmartens
