### ISSUE TITLE
Consider adding `broadcast(to:_*)` to Source/Flow

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18510]
I see people very soon in their journey into streams need to broadcast, it's a rather basic thing you end up needing very soon. Yet currently we need to drop down to the FlowGraph level, which for complete beginners is a bit too much at the same time I think (from observations of users on the mailing list and gitter).

Imagine I'm beginning to learn streams (or I've seen Rx), I kind of understood I need to broadcast explicitly (not obvious for some), this I still get (during my "first steps"):

```scala
Source.single(1).broadcast(someSink, someFlow) 
// TODO can we easily allow flows/sinks here? or has to be one type?
```

yet dropping into the full-power FlowGraph API is a bit scary for "my 30m hour with akka streams":

```scala
val g = FlowGraph.closed() { implicit builder: FlowGraph.Builder[Unit] =>
  import FlowGraph.Implicits._
  val in = Source(1 to 10)
  val out = Sink.ignore
 
  val bcast = builder.add(Broadcast[Int](2))
  val merge = builder.add(Merge[Int](2))
 
  val f1, f2, f3, f4 = Flow[Int].map(_ + 10)
 
  in ~> f1 ~> bcast ~> f2 ~> merge ~> f3 ~> out
              bcast ~> f4 ~> merge
}
```

What I propose is only for the most common one – `broadcast`, other fan-out junctions would stay in FlowGraph land, but then we can explain that that's a more advanced one and you need the "full power".

// See this discussion for a case of the usual confusion: https://gitter.im/akka/akka?at=55faf530aef03edd3ed10ada

**Comment by drewhk** [comment]
There are already `combine()` methods on Sink and Source that can take an arbitrary UniformFanInShape or UniformFanOutShape and do similar what you did.

We can provide some named version of these (like `concat` and `broadcast`) but it is best to have a general version.

**Comment by ktoso** [comment]
Duplicate of https://github.com/akka/akka/issues/17827

**Comment by viktorklang** [comment]
`alsoTo` solves this for the "single sink attach" and `combine` solves it for the multisink attach.
