### ISSUE TITLE
failed: SteppingInMemPersistentActorStashingSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18527]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2914/consoleFull

    [info] - should handle async callback not happening until next message has been stashed *** FAILED *** (117 milliseconds)
    [info]   java.lang.AssertionError: assertion failed: expected List(a, c, b), found List(a)
    [info]   at scala.Predef$.assert(Predef.scala:165)
    [info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:351)
    [info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
    [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
    [info]   at akka.persistence.SteppingInMemPersistentActorStashingSpec$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp(PersistentActorStashingSpec.scala:167)
    [info]   at akka.persistence.SteppingInMemPersistentActorStashingSpec$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(PersistentActorStashingSpec.scala:147)
    [info]   at akka.persistence.SteppingInMemPersistentActorStashingSpec$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(PersistentActorStashingSpec.scala:147)

**Comment by patriknw** [comment]
cc @johanandren

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2623/consoleFull

**Comment by johanandren** [comment]
Hmm, that shouldn't be race:y, it should either nto reach the assert at all or succeed...

**Comment by patriknw** [comment]
Here is another one, looks slightly different I think: https://jenkins.akka.io:8498/job/akka-nightly/2639/consoleFull

**Comment by johanandren** [comment]
Hmm, pretty sure thats unrelated, its in in `akka.typed.ActorContextSpec`

**Comment by patriknw** [comment]
Sorry, I misread, StepWise is not the same as the stepping journal :-)
