### ISSUE TITLE
Akka Typed documentation issues

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#18522]
Referring to 2.4.0-RC3:

In the "Hello World" example an implicit timeout is missing, so it doesn't compile. I also suggest to rename `future` to `response` or something more specific.

In the chat room example, I suggest to rename `behavior` to `chatRoom` and apply necessary downstream changes.

**Comment by patriknw** [comment]
thx

**Comment by patriknw** [comment]
probably obsolete, we will revisit the documentation
