### ISSUE TITLE
ActorContext.stop only for child actors?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#18524]
The parameter of `ActorContext.stop` is called `child` – is it not possible to stop other actors?

Also, maybe it would be nicer to use a polymorphic method to avoid `ActorRef[Nothing]`:

``` scala
def stop[A](actor: ActorRef[A]): Boolean
```

**Comment by patriknw** [comment]
It must be a child, otherwise nothing happens.

I wonder if an actor can stop itself, or if that also must go via parent? (that method will not do it currently)

**Comment by hseeberger** [comment]
OK, the fact that the actor to be stopped has to be a child is a major change from how stopping an actor currently works. I think the documentation not only should make this change much more explicit, but also describe the reasons behind it.

**Comment by johanandren** [comment]
Should it maybe even throw `IllegalArgumentException` for non children rather than return a boolean as it does now?

**Comment by hseeberger** [comment]
Maybe call it stopChild?

**Comment by patriknw** [comment]
If throwing then it should only be done when clearly not a child which would have to be done by inspecting the actor path. Non-existing (or already stopped) possible child should not throw.

spawn/stop belongs together, and it's only for children (perhaps stop can be used for self also?)
otherwise it should be spawnChild/stopChild
I vote for the shorter names, it's just a wrong design in untyped that you can stop anything from anywhere.

**Comment by johanandren** [comment]
Ok, so:
* keep the name (the parameter is already named `child`)
* update the docs saying explicitly must be a child
* throw IllegalArgument if not a child actor ref
* return without doing anything if it was a previous child that is already stopped
* remove the returned boolean (as it doesn't make sense anymore)

**Comment by hseeberger** [comment]
Really throw? I don‘t like that.

**Comment by johanandren** [comment]
Because if you thought your code could stop like that it is broken and you'd want to know that it is, not for it to be silently ignored.

**Comment by hseeberger** [comment]
Hmm ... I think that throwing is broken itself.

**Comment by raboof** [comment]
I don't see a (convenient) way to catch this at compile time, but we would want to signal that this is incorrect use of the API. At run time, we could also consider logging an error rather than throwing?
