### ISSUE TITLE
Problem with unmarshalling json content with  entity(as[T]) 

### ISSUE THREAD

**Issue by redlion99** [akka/akka#18535]
I'm trying to use the entity router to unmarshall a request with json content,  A compile error said:

```scala
Error:(26, 18) could not find implicit value for parameter um: akka.http.scaladsl.unmarshalling.FromRequestUnmarshaller[Template]
        entity(as[Template]){
                 ^
```

in MarshallingDirectives I found:

```scala
def as[[T]] [(implicit um: FromRequestUnmarshaller[T])]  = um
```

although in SprayJsonSupport only unmarshaller for FromEntityUnmarshaller provided

```scala
implicit def sprayJsonUnmarshaller[T](implicit reader: RootJsonReader[T], mat: Materializer):FromEntityUnmarshaller[T] =
    sprayJsValueUnmarshaller.map(jsonReader[T].read)
```

**Comment by ktoso** [comment]
Hi @redlion99,
did you read about how Spray JSON works? https://github.com/spray/spray-json#providing-jsonformats-for-case-classes

You'll need to provide a format for your case-class, like this: 

```scala
trait MyJsonProtocol extends DefaultJsonProtocol {
  implicit val templateFormat = jsonFormat4(Template)
}
object MyJsonProtocol extends MyJsonProtocol

import MyJsonProtocol._
import spray.json._

// will make use of the implicit templateFormat
as[Template]
```

**Comment by ktoso** [comment]
I'll actually improve the docs file:///Users/ktoso/code/akka/akka-docs-dev/target/sphinx/html/scala/http/common/json-support.html to show a full example how to utilise this

**Comment by redlion99** [comment]
@ktoso  To answer your question, yes, I have import the format for Template, which is in file JsProtocol like this:

             import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport._
             import akka.http.scaladsl.server.Directives._
             import com.convertlab.channel.email.core.models.JsProtocol._
             import com.convertlab.channel.email.core.models.{EmailTables, Template}

My question is when I use as[Template]  an `implicit um: FromRequestUnmarshaller[T]` is required. But I can not find implementation of a `FromRequestUnmarshaller`, instead I only find  an unmarshaller named `FromEntityUnmarshaller` in `SprayJsonSupport`, I guess that's why I got that error.

**Comment by redlion99** [comment]
by the way, the version I'm using is 1.0  from Maven

<dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-http-experimental_2.11</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-http-spray-json-experimental_2.11</artifactId>
            <version>1.0</version>
        </dependency>

**Comment by ktoso** [comment]
`FromRequestUnmarshaller` is a type alias:
`type FromRequestUnmarshaller[T] = Unmarshaller[HttpRequest, T]` @ https://github.com/akka/akka/blob/release-2.3-dev/akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/package.scala

I'll dig more into the problem you describe tomorrow, cheers

**Comment by ktoso** [comment]
In the meantime, if you could provide a minimized example that shows the problem you're having that'd help a lot!

**Comment by redlion99** [comment]
It's ture that;

The SprayJsonSupport trait provides a FromEntityUnmarshaller[T] and ToEntityMarshaller[T] for every type T that an implicit spray.json.RootJsonReader and/or spray.json.RootJsonWriter (respectively) is available for.


But what I need is `FromRequestUnmarshaller[T]` not `FromEntityUnmarshaller[T]`, isn't it?


The format is in JsProtocol:

		object JsProtocol extends DefaultJsonProtocol {

		implicit val templateFormat = jsonFormat4(Template)

Here is the route

		package com.convertlab.channel.email

		import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport._
		import akka.http.scaladsl.server.Directives._
		import com.convertlab.channel.email.core.models.JsProtocol._
		import com.convertlab.channel.email.core.models.{ Template}


		object RestService {
		  def route = {
		    path(""){
		      post{
		        entity(as[Template]){
		          template: Template=>
		            complete("")
		        }
		      }
		    }
		  }
		}

When I use `entity(as[Template])`



			  def entity[T](um: FromRequestUnmarshaller[T]): Directive1[T] =
			    extractRequestContext.flatMap[Tuple1[T]] { ctx ⇒
			      import ctx.executionContext
			      import ctx.materializer
			      onComplete(um(ctx.request)) flatMap {
			        case Success(value) ⇒ provide(value)
			        case Failure(Unmarshaller.NoContentException) ⇒ reject(RequestEntityExpectedRejection)
			        case Failure(Unmarshaller.UnsupportedContentTypeException(x)) ⇒ reject(UnsupportedRequestContentTypeRejection(x))
			        case Failure(x: IllegalArgumentException) ⇒ reject(ValidationRejection(x.getMessage.nullAsEmpty, Some(x)))
			        case Failure(x) ⇒ reject(MalformedRequestContentRejection(x.getMessage.nullAsEmpty, Option(x.getCause)))
			      }
			    } & cancelRejections(RequestEntityExpectedRejection.getClass, classOf[UnsupportedRequestContentTypeRejection])

			  /**
			   * Returns the in-scope [[FromRequestUnmarshaller]] for the given type.
			   */
			  def as[T](implicit um: FromRequestUnmarshaller[T]) = um

In my understanding, I need to bring a converter like this to the scope. 

			implicit def sprayJsonUnmarshallerConverter[T](reader: RootJsonReader[T])
        (implicit mat: Materializer): FromRequestUnmarshaller[T] 


I import SprayJsonSupport, where is a converter for `FromEntityUnmarshaller` only

			implicit def sprayJsonUnmarshallerConverter[T](reader: RootJsonReader[T])
        (implicit mat: Materializer): FromEntityUnmarshaller[T]

**Comment by ktoso** [comment]
Hi there @redlion99,
I added some more docs as you'll notice in the #18578 PR.

Also I checked your example and it's all fine:

```scala

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport
import akka.http.scaladsl.server.{ Directives, Route }
import akka.stream.ActorMaterializer
import spray.json.{ DefaultJsonProtocol, JsObject }

//////

case class Template(a: String, b: String, c: Int, d: Int)

object RestService extends App with Directives with SprayJsonSupport {
  import DefaultJsonProtocol._

  implicit val sys = ActorSystem()
  implicit val mat = ActorMaterializer()
  import sys.dispatcher

  implicit val templateFormat = jsonFormat4(Template)

  def route: Route = {
    post {
      entity(as[Template]) { // unmarshaller applied
        template: Template =>
          complete {
            template // marshaller applied
          }
      }
    }
  }

  Http().bindAndHandle(route, "127.0.0.1", 8080)

  readLine()
  sys.shutdown()
}
```

```
$ http -v POST 127.0.0.1:8080 a=name b=thing c:=1 d:=12
POST / HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 44
Content-Type: application/json
Host: 127.0.0.1:8080
User-Agent: HTTPie/0.9.2

{
    "a": "name",
    "b": "thing",
    "c": 1,
    "d": 12
}

HTTP/1.1 200 OK
Content-Length: 54
Content-Type: application/json
Date: Fri, 02 Oct 2015 10:10:39 GMT
Server: akka-http/2.3.12

{
    "a": "name",
    "b": "thing",
    "c": 1,
    "d": 12
}
```

The chain is:

```
def entity[T](um: FromRequestUnmarshaller[T]): Directive1[T] = // needs a FromRequestUnmarshaller
def as[T](implicit um: FromRequestUnmarshaller[T]) = um // so this only "brings in" the um

// and:
type FromRequestUnmarshaller[T] = Unmarshaller[HttpRequest, T]

// so we use:

  implicit def messageUnmarshallerFromEntityUnmarshaller[T](implicit um: FromEntityUnmarshaller[T]): FromMessageUnmarshaller[T] = // from LowerPriorityGenericUnmarshallers 
// which needs FromEntityUnmarshaller

// which is provided by SprayJsonSupport:
implicit def sprayJsonUnmarshallerConverter[T](reader: RootJsonReader[T]): FromEntityUnmarshaller[T] 
=
// which needs a RootJsonReader

// which finds your 
    implicit val templateFormat = jsonFormat4(Template)

// done!
```

Hope this explains things, happy hakking!

**Comment by redlion99** [comment]
@ktoso Thanks for your explain.

FromEntityUnmarshaller is converted to FromMessageUnmarshaller in LowerPriorityGenericUnmarshallers
            implicit def messageUnmarshallerFromEntityUnmarshaller[T](implicit um: FromEntityUnmarshaller[T]): FromMessageUnmarshaller[T]

**Comment by cwei-bgl** [comment]
@ktoso I spotted a strange thing that these marshallers/unmarshallers have source code declaration order requirement. If you move the declaration of Item, Order and JsonSupport to the bottom of MyJsonService in SprayJsonExampleSpec.scala, you will get the error -  could not find implicit value for parameter um: akka.http.scaladsl.unmarshalling.FromRequestUnmarshaller.

Do you know if this is Scala limitation or something else?

**Comment by ktoso** [comment]
Yes they have that requirement, because order in these matters because of how implicit resolution works.

Please ask such questions on the akka-user mailing list or gitter chat. Github is for issues, especially please open new tickets if you have something to report rather than reviving closed threads, thanks!
