### ISSUE TITLE
Akka HTTP: document / point to community / show CORS

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18530]
Patrick Ting has provided a snippet here: https://gist.github.com/pcting/2e65c36f868c5cee7d6a

See discussions: 
- https://groups.google.com/forum/#!searchin/akka-user/cors/akka-user/msJfSkHDCxA/foDrnQPBx2gJ
- https://groups.google.com/forum/#!searchin/akka-user/cors/akka-user/5RCZIJt7jHo/lII0dUJhuIsJ

**Comment by kukido** [comment]
Found this tickets during my research on adding CORS for one of our projects. Is the idea here to add CORS support to the library or just describe how it can be done?

**Comment by ktoso** [comment]
As a first step document, however if we deep it needed enough this one I think we may end up pulling in.
I think someone in the community has it implemented and shared on akka-user already: https://groups.google.com/forum/#!topic/akka-user/5RCZIJt7jHo so you can use that for now.

Any feedback about if that impl seems to be working fine or is not enough etc would be excellent, thanks!

**Comment by lomigmegard** [comment]
I have been working on a CORS implementation recently and wanted to share it here.

https://github.com/lomigmegard/akka-http-cors

It follows the recommendation from the W3C (https://www.w3.org/TR/cors/), defining a new `cors` directive that enables cross origin requests. I also had to create a new Rejection and a couple of helper classes. There are definitely some implementation choices that can be discussed though.

Let me know if you would be interested in having this published to maven. Also do you think this would benefit the core project? I can work on a pull request if yes. 

Compared to the other existing directives, this one is more complex and requires multiple settings. The CORS mechanism is not a core feature of http and as such should perhaps not be in akka-http. However, it is a very common use case when building APIs and a simplistic implementation can easily be full of bugs.

**Comment by ktoso** [comment]
Hi @lomigmegard, sorry that this issue fell through the cracks!
Yes I think it would be pretty cool if we could point towards your project in the official docs even - would you like to submit a PR adding it to the docs?

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
