### ISSUE TITLE
Introduce `auto-to-strict` config setting on client- and server-side

### ISSUE THREAD

**Issue by sirthias** [akka/akka#18540]
Currently the core layer only strictifies incoming message entities if the response bytes are fully contained in the chunk of bytes that have currently been read from the receive buffer.
Since this is non-deterministic the user always has the responsibility for "draining" the entity bytes from the connection in order to free it up for subsequent messages.

The proposal is to introduce a new config setting called `akka.http.parsing.auto-to-strict` which increases user convenience for the standard case (when the entity is "small") and at the same time removes all non-determinism.

Possible values for the setting:

* `off`
  The parser *never* creates strict entities, even if the bytes are "already there".

* `on`
  The parser always strictifies unchunked entities. Boundedness is achieved solely via the `max-content-length` setting.

* `<int value>`
  The content-length threshold up to which the parser automatically strictifies the entity.

**Comment by jrudolph** [comment]
This ties in with the proposals in #17694 and should probably approached "holistically". 

In general, several parsing modes are possible that would determine what kind of entities the user can expect when receiving an HttpMessage:
 * the current behavior, with entity types very closely fitting what comes in on the wire
   * one disadvantage is the somewhat unnatural and non-deterministic distinction between Strict and Default
   * each chunk is currently aggregated before it is dispatched
 * only Strict messages (this ticket, I like the proposed configuration options)
 * only streamed messages (either with or without content-length available), see #17694
  * Chunked entities would be auto-converted to Default-ones to prevent having to collect full chunks

**Comment by ktoso** [comment]
Thanks a lot for reporting this and the insights, makes a lot of sense, marking triaged for now.

**Comment by ktoso** [comment]
Triaged. Also, one of the things which might impact our behaviour in raw throughput benchmarks I think.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
