### ISSUE TITLE
Review potential cross-site security issue wrt Websocket

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18549]
@fommil reminded me that browsers may not be strict enough in preventing cross-site scripting to prevent malicious sites from opening up websocket connections on the behalf of the browser user.

We need to check in which situations this can lead to problems and how to prevent insecure access (e.g. by changing the server-side Websocket API to force the developer to provide an `Origin` checker to accept incoming Websocket requests).

**Comment by jrudolph** [comment]
E.g. see this overview: https://gist.github.com/subudeepak/9897212#websockets---security-overview

**Comment by jrudolph** [comment]
Here's another one: http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by jrudolph** [comment]
The RFC has a short section as well: http://tools.ietf.org/html/rfc6455#section-10

**Comment by ktoso** [comment]
Thanks for bringing it up, definitely should be looked into - thanks!

**Comment by ktoso** [comment]
AFAIR @wsargent looked into something similar in his "check the origin header" fixup in the Play websocket examples recently?

**Comment by ktoso** [comment]
Thus would be addressable by https://github.com/akka/akka/issues/20535

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
