### ISSUE TITLE
Section 3.6.4, Broadcast to Router

### ISSUE THREAD

**Issue by rosshsr** [akka/akka#18545]
In the documents (Section 3.6.4) the code for Broadcasting to all routees of a router is

`router ! Broadcast("Watch out for Davy Jones' locker")`

However, I found that in order to get it to work, I needed to use

`router.route(Broadcast("Watch out for Davy Jones' locker"), sender)`

**Comment by johanandren** [comment]
'!' is part of the Scala API, the Java API would be the `tell` method described here: http://doc.akka.io/docs/akka/2.3.14/java/routing.html#Broadcast_Messages

(Note that there are different docs for Java and Scala)

**Comment by rosshsr** [comment]
The trouble I was having was with Scala. The example in the documentation is trying to illustrate how to send a Broadcast message to all routees of a Router at once. However, it seems that the `!` is not a member of Router. In order to accomplish that task I had to use the latter bit of code from my original post. 

From subsequent discussion of my problem, I found that it may be possible that the former line of code from my original post may be valid with a router Actor (I haven't tested this), but it just seems a little unclear on the topic.

**Comment by johanandren** [comment]
In the first section which is about using a `Router` directly it says: 
> "Sending messages via the router is done with the route method, as is done for the Work messages in the example above."

http://doc.akka.io/docs/akka/2.3.14/scala/routing.html#A_Simple_Router


The subsequent sections are under the header "A Router Actor", so there `!` is more correct.

http://doc.akka.io/docs/akka/2.3.14/scala/routing.html#A_Router_Actor

I can see how that can be missed, but I think it is clear enough, no?

**Comment by rosshsr** [comment]
It's clear if not for the special blue Note section under A Simple Router. It links directly to the bit of code that I found to not work. I don't mean to split hairs, I just figured I'd point it out since I found it a little confusing. 

Since a Broadcast message is a special scenario, I can see how it might confuse someone into thinking that it has a slightly different syntax than the regular `Router` routing code.

**Comment by johanandren** [comment]
Yeah, I guess we could make it more clear by noting the differences in the "info" block. Thanks for explaining how you found it unclear!

**Comment by ktoso** [comment]
Please try to not cross-post questions right away (for reference: http://stackoverflow.com/questions/32748412/value-is-not-a-member-of-akka-routing-router ), it's a bit troublesome to find the solution afterwards, if the question is in 3 places, and the answer was only posted in 1 place for example. Thanks!

**Comment by rosshsr** [comment]
Sorry about that, didn't realize the github and SO would be tied together
