### ISSUE TITLE
Issues with Akka and slf4j+log4j2

### ISSUE THREAD

**Issue by constantin-ungureanu-github** [akka/akka#18544]
When using Java and Akka 2.4.0-RC3 I encounter logging issues.

There is a logging configuration flag called additivity in log4j2, so that when a log event is picked by a logger, that log event does not propagate upper to parent logger (or ultimately to the root logger).
Witl latest RC when using this it works for some time and then it breaks something so that I get all unwanted logs that should have gone to somewhere else. Tested with 2.3.12 and this does not reproduce. I suspect there is something broken in akka-slf4j. This is severe issue.

Can reproduce constantly this issue at https://github.com/constantin-ungureanu-github/simulator .

There is another problem that when terminating (or shutdown in 2.3.12), if using AsyncLoggers I always get some exception
SEVERE: Exception processing: 8286 org.apache.logging.log4j.core.async.RingBufferLogEvent@75ab2868
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
        at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
        at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

For this issue I suspect the getContext().system().terminate() method should properly close.
Anyway, is good improvement since getContext().system().shutdown() that caused remaining logs to not be recorded.

Please fix this issues.

**Comment by constantin-ungureanu-github** [comment]
For the second problem, the next can be added before calling the terminate()

org.apache.logging.log4j.core.async.AsyncLogger.stop()

**Comment by constantin-ungureanu-github** [comment]
For the first problem, including some serious memory increases caused by the logging, I could bypass it simply by eliminating akka-slf4j and akka support for logging.

**Comment by patriknw** [comment]
@hseeberger For [akka-log4j](https://github.com/hseeberger/akka-log4j) you might be interested in the second problem described here. I guess you have the possibility to call `org.apache.logging.log4j.core.async.AsyncLogger.stop()` in postStop of the logger.

**Comment by patriknw** [comment]
@constantin-ungureanu-github how can I reproduce the first problem? I tried commit https://github.com/constantin-ungureanu-github/simulator/commit/b80c9ef96dc0b97ac032edea2d5b1c8f074f580a

sbt "run 10000 100 10"

Can't see any problems.

**Comment by hseeberger** [comment]
@patriknw, thanks, but I don't use async logging at all in akka-log4j. Should I?

**Comment by patriknw** [comment]
I don't know if that makes sense. For example logback has an async appender that can also drop debug and info messages when becoming "full". That has the advantage that the logger mailbox doesn't grow. Might be something similar for log4j?

**Comment by constantin-ungureanu-github** [comment]
@patriknw Thanks for the response.
To reproduce this first problem on the commit that you mentioned run with a larger number of actors:
sbt "run 100 1000 100000" -mem 4096

Also, there are serious memory issues when using akka logging, in the sense that it keep increasing, until it reaches the specified limit, and then it gets much more slower as probably gets into some garbage collecting. Please notice that if I remove my only logging message (in class Subscriber.class, log.info("{}", message);), all those issues do not appear. Also notice the performance increase. Logging should not affect the application performance, excluding of course some disk IO operations.

Latest commit ec8a1c0dbd20f4794165bb84771257ccbd7bcc3e it relays only on slf4j and log4j2 and also those issues do not happen.

**Comment by constantin-ungureanu-github** [comment]
@hseeberger Please read:
https://logging.apache.org/log4j/2.x/manual/async.html
http://www.grobmeier.de/log4j-2-performance-close-to-insane-20072013.html

Async loggers in log4j2 use that disruptor library that when running in a concurrent environment it will perform much better because it reduces the cost of locking on data structures that hold those logs before they get written on disk.

If you're using log4j2 it makes sense you will use async loggers before anything else, unless doing some kind of audit and need to have sync loggers.

**Comment by hseeberger** [comment]
I wonder if there are any potential issues with having some component like the Disruptor which creates its own threads alongside or within an Akka application. Probably not, at least in this case where the number of threads used for logging seems to be constrained (to one background thread?). Any thoughts?

**Comment by constantin-ungureanu-github** [comment]
@hseeberger For the log4j2 and the disruptor itself, other than the issue described here, when terminating the actor system, I am not expecting.

**Comment by hseeberger** [comment]
@constantin-ungureanu-github, sorry, but I don't understand what you said in your last comment. Could you please rephrase that?

**Comment by patriknw** [comment]
If you produce log event faster than they are consumed by the logging backend memory will of course grow (messages are queued in the mailbox of the logger actor). When that hits full GC and even full heap things will slow down and even completely stall.

Using an async logging backend moves the problem one step. If the async backend end is faster than the synchronous logging it improves the situation. In the end I think you can always produce log events faster than what can be written to disk, so you should use your logging with care.

What I like with the logback async appender is that it can drop events when it becomes full. That is the only way to completely protect against these issues. We could of course implement such a mailbox in akka to be used in front of the logger actor.

**Comment by constantin-ungureanu-github** [comment]
@hseeberger I am referring about the exception that you can see in my first comment, that was solved by invoking org.apache.logging.log4j.core.async.AsyncLogger.stop() before getContext().system().terminate();

**Comment by constantin-ungureanu-github** [comment]
@patriknw The disruptor uses a circular buffer and the memory doesn't grow.
Dropping log events when the buffer becomes full is a hack and for me is not acceptable.

**Comment by constantin-ungureanu-github** [comment]
One aspect I noticed is that when using only slf4j and log4j2 is that the application is limited by the CPU processing capabilities. Disk writing operation for logging is not an issue. Of course, maybe there is some drawback when waiting for flushing that ring buffer, however it is not noticeable.

**Comment by patriknw** [comment]
What do you think will happen when the circular buffer becomes full? It will either drop or block. I'm pretty sure that the default strategy for log4j2 async appender is to block, i.e. if used directly from your actors it will block the actors, if used via akka-slf4j it will block the logger actor.

**Comment by hepin1989** [comment]
@constantin-ungureanu-github What I am doing with akka-stream and kafka-logger is that I will drop logging message when the kafka producer could not catch up the logging event.we have encounter 8~10k logging event per seconds at info level,I don;t think you could keep all the logging event and then pray your server will behavior right at very high load.

**Comment by constantin-ungureanu-github** [comment]
The point is that logging is working just fine without akka-slf4j. If you want to acknowledge and address the issues that akka-slf4j is causing I am happy to help.

**Comment by hepin1989** [comment]
@patriknw with disruptor,then the ring buffer is full,it will block,then the logging actor will full of the logging event message,then OOM,I think.

the logging actor seems could not specified the mailbox for now.

**Comment by hepin1989** [comment]
@constantin-ungureanu-github We are using log4j2 and kafka logger,both in house solution,but both we would drop under high load.I don't think I could keep all the logging event and keep the server happy.

**Comment by constantin-ungureanu-github** [comment]
@hepin1989 I understand what you are saying, however this is not the problem for me. But 8-10 k of logging event per second doesn't seems that much compared to the disk IO speed.

**Comment by patriknw** [comment]
@hepin1989 In 2.4 you can:

      # The LoggerMailbox will drain all messages in the mailbox
      # when the system is shutdown and deliver them to the StandardOutLogger.
      # Do not change this unless you know what you are doing.
      logger-queue {
        mailbox-type = "akka.event.LoggerMailboxType"
      }

**Comment by hepin1989** [comment]
@constantin-ungureanu-github so you want to write to the disk and then what?using a collector to streaming to elk? we are streaming to kafka directly.even the disk speed is fast enough,we still need to do some page cache and then using to much of memory.and finally you will still be OOM.

Yes,you could save as much you can,but I think the worst just the best,and for you problem.I encounter that when I was kill it too.

@patriknw Thanks,I missed that:).

**Comment by hepin1989** [comment]
@constantin-ungureanu-github akka's logging is async,I think you may need to using log4j2 directly if you want to relay on it and need more control ,then I think it may blocking your actor then.
