### ISSUE TITLE
DOC: RequestBuilding needs to be documented explicitly in client docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18550]
Only mention of the `RequestBuilding` trait is currently around the testkit, making it hard to discover for new users who just want to use the Http client: http://stackoverflow.com/questions/32757605/idiomatic-way-to-create-a-basic-http-post-request-with-akka-http?utm_source=twitterfeed&utm_medium=twitter

Add docs and examples using RequestBuilding explicitly in the client side docs.

**Comment by 2beaucoup** [comment]
Some methods on RequestBuilding looks redundant. Do we want to provide three different ways to change headers for example:
```scala
Get("/") ~> `Remote-Address`(RemoteAddress("192.168.3.12"))
```

**Comment by ktoso** [comment]
IF... we decide to make it actual API. 
Still to be decided.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
