### ISSUE TITLE
add `throttle` combinator

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18555]
Even with Source.zipWith there is still considerable boilerplate in defining a throttling stage, we should make that available cleanly.

**Comment by drewhk** [comment]
You can use the new GraphStage for that. I would also recommend adding a keepalive-inject next to it (injects a predefined element if: for x seconds there was no traffic, and there is downstream demand).

**Comment by drewhk** [comment]
maybe we should also document that the throttle can be efficiently combined with a buffer to add policies:
 - backpressure on violation
 - drop on violation
 - fail on violation

**Comment by drewhk** [comment]
Also, if it was not clear, I mentioned the keepalive-idle-inject thing here because it provides a minimum rate, while throttle sets a maximum rate.

**Comment by rkuhn** [comment]
Yes, that makes perfect sense, thansk!

**Comment by agolubev** [comment]
keepAlive combinator is added in here #18735
