### ISSUE TITLE
why does the websocket code include a UTF8 codec?

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18558]

**Comment by ktoso** [comment]
AFAICS we need it because a WS TextMessage may arrive *unfortunately* chunked up, yet we want to parse it as "a whole".

Note: As @rkuhn and @drewhk mentioned on gitter, this is actually not very WS specific, and we should port this to akka.io.stream, as it's as useful for streaming TCP as it is here.

**Comment by jrudolph** [comment]
The main reason is that the UTF8 decoder from the JDK isn't able to report some kinds of errors but will fall back to using replacement chars in those cases. As I wanted to have as many autobahn test cases to succeed as possible, I took the same path as many of the other (Java) WS implementations to include a custom UTF8 decoder but in a more principled way: other implementations use the JDK decoder but then add basically the same code I added but only for checking that stream contents are valid UTF8. As this does exactly the same amount of work as actually decoding the bytes, I just added the few additional lines to decode. 

As a result we've now got a decoder that is much easier to use than the JDK one in the streaming use-case, which is probably faster, and which is somewhat more correct than the JDK one. It comes with a few tests and also the autobahn test suite validates some of the trickier UTF-8 edge cases.

See here, where I reported the original issues: https://github.com/akka/akka/pull/17131#issuecomment-93481965

**Comment by ktoso** [comment]
Thanks for the info!

@jrudolph Which reminds me - think we should set up autobahn tests on jenkins somehow, to make sure something we touch in WS does not accidentally break it? It's as simple as directing wstest to an ws echo server, right?

**Comment by jrudolph** [comment]
I thought about including the autobahn suite. I think the main challenges are:
 * whoever runs the tests needs the suite to be installed (or it must be installed every time from scratch, or e.g. be run from a docker container, not sure if someone already tried to package it up in that way)
 * you need to parse the result and feed it back to the build tool
 * you need to specify the set of tests run and maybe tweak which ones need to be strictly passed and which ones doesn't, I found a few issues where I think the test suite is too strict in what it accepts (IIRC this was about race conditions that affected the closing behavior)

**Comment by ktoso** [comment]
Thanks! I'll make it a ticket for now then

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
