### ISSUE TITLE
DOC: Explicitly explain how to run https and http from the same app

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18551]
It's pretty simple, just `Http().bind...` once using TLS to 433 and once without TLS to 80, in the same app – done.

However it is not clear to developers it this is the way to go or not.

**Comment by ktoso** [comment]
Very simple documentation ticket - look at the sample of running HTTPS and explain that running "both" means running two servers (binding twice)

**Comment by richard-imaoka** [comment]
Let me have a look - I will submit a PR in a week or two
