### ISSUE TITLE
Persistence: Behaviour of asyncReadHighestSequenceNr after delete messages

### ISSUE THREAD

**Issue by mattinbits** [akka/akka#18559]
It seems to be unclear what the operation of `asyncReadHighestSequenceNr` should be after a delete old messages call has been made, and the TCK does not have a test for the scenario where:

- I persist several events to the journal
- I take a snapshot
- I issue a call to delete old messages up to the  point of the snapshot

At this point, there are no messages in the journal. I believe that `asyncReadHighestSequenceNr` should keep a memory of the highest sequence number that has been used (per persistence-id), rather than reset to 0, otherwise on Recovery, the snapshot will appear newer than events which were in fact created after the snapshot.

The Cassandra plugin behaves as per my interpretation: https://github.com/krasserm/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraRecovery.scala#L28 while this JDBC one does not: https://github.com/okumin/akka-persistence-sql-async/blob/master/core/src/main/scala/akka/persistence/journal/sqlasync/ScalikeJDBCWriteJournal.scala#L73

However both pass the TCK. 

So, this issue is to clarify the expected behaviour, and extend the TCK with a test for it.

**Comment by ktoso** [comment]
Thanks for reporting! We'll need to look into this then, definitely may be worth specifying / testing.

**Comment by patriknw** [comment]
That is an important point. 

Normally, when recovering from a snapshot the sequence number of the snapshot is passed in as the `fromSequenceNr` in `asyncReadHighestSequenceNr`, but that is just a hint, and if user is not recovering with snapshot it will not work unless journal keeps track of highest.

We should enforce this with the TCK and clarify docs.

**Comment by patriknw** [comment]
I'm setting this to 2.4.0 for now, not sure if it will make it. Anyway it will not require any changes in akka-persistence itself.

**Comment by okumin** [comment]
@patriknw Could you tell me what problems exist if journal doesn't keep the highest numbers?
I have understood that `fromSequenceNr` helps me if a part of state is restored from snapshot.
Not using snapshot, is there any problem when a sequence number is rewound?

**Comment by patriknw** [comment]
It should not be any problems if snapshots are not used, as far as I can see. It's really strange usage that would trigger problems, but it makes a lot of sense to not reuse sequence numbers anyway.

Here is one scenario that I can think of.

* persist A-seqnr-1
* persist B-seqnr-2
* persist C-seqnr-3
* snapthot-seqnr-3
* delete all up to seqnr 3
* recover without snapshot
* persist D-seqnr-1
* persist E-seqnr-2
* recover with snapshot

That would mean that after the last recovery the state corresponds to snapthot-seqnr-3 and D-seqnr-1 and E-seqnr-2 are not replayed even though they were persisted after the snapshot. Super weird usage, I know.

**Comment by okumin** [comment]
Thanks for an example.
I agree that it is natural not to rewind sequence numbers and I thought that reusing may confuse followers, such a PersistenceView or PersistenceQuery.
