### ISSUE TITLE
add combinator for termination notification

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18565]
For context see [this discussion](https://groups.google.com/d/msg/akka-user/l8ACEw6ndsA/ZK2UCmqNBQAJ).

[...] Perhaps we should offer a combinator whose only purpose is to complete a Future upon termination, but otherwise it just sends all elements downstream, like

    def completionProbe[M](combine: [Mat, Future[Unit]] => M): Repr[Out, M]

Then this problem could be solved independent of the chosen Source:

    val (completion, sinkFuture) = source.completionProbe(Keep.right).toMat(sink)(Keep.both).run()

For this combinator (and possibly others of its kind) I would not want to provide a default scheme for treating the materialized value since adding such a value is its only purpose.

**Comment by drewhk** [comment]
Isn't the issue with this is that the completion of this stage does not translate to the completion of the downstream?

**Comment by viktorklang** [comment]
@drewhk Great point.

WARNING: PREMATURE IDEA BELOW

What if Sinks are "simply" result-projectors instead of doing "actual" work.

In that case the "Writing of a File" would be a Flow[ByteString, (Try[Unit], Long), Unit] which gives:

~~~scala
Source(file) via WriteBytes(file) to Sink.head
~~~

**Comment by rkuhn** [comment]
@drewhk That is not an issue here since the user is just interested in whether the stream has successfully flowed past this point in its entirety, which has well-defined semantics and is probably useful elsewhere.

@viktorklang Your proposal would ruin the necessary write-count value that the sink should emit regardless of whether the stream terminated successfully or not. I do maintain that my proposal has the right structure, but please do keep beating on it :-)

**Comment by rkuhn** [comment]
Ah, and the name needs some love, as you noted on the mailing list.

**Comment by viktorklang** [comment]
@rkuhn since it is a Flow it obeys the same rules as a Processor, in which case it can recover from a failure and signal (Try[Unit], Long) and then complete ;)

**Comment by rkuhn** [comment]
I take the smiley to imply that you acknowledge that providing a generic solution is better than complicating every single Sink.

**Comment by drewhk** [comment]
I think @viktorklang's idea is actually quite nice. Maybe not expressed as a Flow, but the idea of providing some baseline support for sink completion is appealing.

**Comment by kutchar** [comment]
Since we are on this topic, I think there are a few other things that need to be addressed:
1. Upstream failure handling. For example, if a file source fails, then the failure should be propagated downstream.

2. Ability to "convert" the failures before propagating them downstream. For example, instead of sending down a Future.failed(FileNotFoundException), there should be a way to say Future.failed(SomeOtherBusinessLogicException(cause=FileNotFoundException))

Point 2 is specially important when building APIs. Consider a "BlobStore" trait.
```
trait BlobStore {
  def get(id: String): Source[ByteString, Future[Unit]]
  def put(id: String): Sink[ByteString, Future[Unit]]
}
```

Two plausible implementations for BlobStore might be a FileSystemBlobStore and AwsS3BlobStore. You wouldn't want the downstream sinks/flows to care about0 "FileNotFoundException", but rather some abstract "NonExistentBlobException".

**Comment by agolubev** [comment]
@rkuhn, thought a little about this. So few points below (hope they will be useful)
1. It would be good to have termination notification in format of Future[Unit]
2. It's good to have such ```Future``` for the whole stream. I'm thinking of having ```runnableGraph.withTerminationProbe(promise)```. User can do ```graph.withTerminationProbe(...).run()```
3. It also would be good to add probe like this to any flow branch (like get notification when first out of two flows for concat is finished). So similar to ```withAttribute``` can be ```.withTerminationProbe(promise)```. Would be easy to implement with GraphStage but will require to add logic to each stage.
Let me know if it makes sense.

**Comment by rkuhn** [comment]
@agolubev Since our streams are distributed (at least across actors) there is no single place where “overall termination” could be observed, I maintain that users know best which parts they want to monitor. Your third point seems to support this view as well: simply attach a completionProbe between the first input and the concatenate junction.

BTW: `Future[Unit]` can be a rather dangerous type given that Scala happily adapts any code block by having it return `()` when it feels like it (which means discarding the intended return value without any error message). But I don’t have another brilliant idea for this right now.

**Comment by viktorklang** [comment]
weeeell, we could use j.l.Void and reflectively create an instance for it.
*ducks*

-- 
Cheers,
√

**Comment by agolubev** [comment]
as far as we are moving to ```GraphStage``` direction that's providing automatic error handling and handling closing as well. Perhaps we can add prob functionality on this level.

>there is no single place where “overall termination” could be observed

Another reason may be that user can have materialization value (as ```Future``` for example) from the middle of the flow. So it's not so important to track last point of messages - at Sink

**Comment by patriknw** [comment]
> j.l.Void and reflectively create an instance for it.

null is a valid Void value, as far as I know
(... hides again)
