### ISSUE TITLE
Example of confusion when using FlowGraph

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18561]
An example of difficulties getting a FlowGraph right:

https://gist.github.com/gzoller/ffdbe3f4676e61b61998

**Comment by drewhk** [comment]
Is this any ways relevant now? The DSL is more explicit in many ways, for example in expecting an explicit shape to be returned. FlexiStuff is also gone. I am closing this for now; please reopen with more explanation if you still think this is relevant.
