### ISSUE TITLE
Include Autobahn WS tests in the build

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18563]
They're an external python implemented testsuite, we could include them in the build somehow.

autobahn.ws/testsuite/installation.html#testing

@jrudolph's hints on that:

> I thought about including the autobahn suite. I think the main challenges are:
> 
> - whoever runs the tests needs the suite to be installed (or it must be installed every time from scratch, or e.g. be run from a docker container, not sure if someone already tried to package it up in that way)
> - you need to parse the result and feed it back to the build tool
> - you need to specify the set of tests run and maybe tweak which ones need to be strictly passed and which ones don't, I found a few issues where I think the test suite is too strict in what it accepts (IIRC this was about race conditions that affected the closing behavior)

**Comment by ktoso** [comment]
(Claiming it as a "pet project", if someone else wants to jump in and help please ping here)

**Comment by ktoso** [comment]
Note to self: https://github.com/jrudolph/dockerfiles/tree/master/autobahn-testsuite dockerized autobahn suite

**Comment by ktoso** [comment]
I want to do this this week, hopefully won't be too painful to set up.

**Comment by ktoso** [comment]
This is now solved and running as a nightly task.

Tasks performed here:
- some infra cleanups to make it possible to run @jrudolph's autobahn images 
- the job is: https://jenkins.akka.io:8498/job/akka-http-websockets

How it works: 
- basically as described in: https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/RunWebsocketAutobahnTestSuite.md
  - for client: we run the test server image, then run test app using sbt, download results, then stop the container
  - for server: we start the server (in a weird way, in background, in subshell), we run the test client against it, thanks to `--net=host`, results are generated via `-v` mounted filesystem
- results are reported and stored using the static html reports jenkins plugin
- it's currently set up to run on a4, but all nodes are able to run it (made sure via cheffing all the same way)

Results are accessible as HTML pages:
- here: https://jenkins.akka.io:8498/job/akka-http-websockets/35/
  - client: https://jenkins.akka.io:8498/job/akka-http-websockets/35/Autobahn_TCK_%E2%80%93_WebSocket_Client/
  - server https://jenkins.akka.io:8498/job/akka-http-websockets/35/Autobahn_TCK_%E2%80%93_WebSocket_Server/

Build fails with:

```
+ echo '\033[0;31mServer tests report available: https://jenkins.akka.io:8498/job/akka-http-websockets/47/Autobahn_TCK_%E2%80%93_WebSocket_Server/ \033[0m'
\033[0;31mServer tests report available: https://jenkins.akka.io:8498/job/akka-http-websockets/47/Autobahn_TCK_%E2%80%93_WebSocket_Server/ \033[0m
+ echo Summary:
Summary:
++ cat reports/index.json
++ grep --ignore-case -n -B1 -A3 fail // actual command different now
+ echo '3077-         "behavior": "OK",     // <---- imagine this said FAILED
3078:         "behaviorClose": "FAILED BY CLIENT",
3079-         "duration": 1002,
3080-         "remoteCloseCode": 1002,
3081-         "reportfile": "autobahnpython_case_7_3_6.json"'
3077-         "behavior": "OK",
3078:         "behaviorClose": "FAILED BY CLIENT",
3079-         "duration": 1002,
3080-         "remoteCloseCode": 1002,
3081-         "reportfile": "autobahnpython_case_7_3_6.json"
+ exit -1
```

NON-STRICT and UNIMPLEMENTED do not fail the build.

**Comment by ktoso** [comment]
Aaaaand.... we have green! :green_heart (well, blue): 

![akka-http-websockets__49__jenkins_](https://cloud.githubusercontent.com/assets/120979/11561783/e8e741f8-99c9-11e5-9089-f99141dfb92d.png)

**Comment by jrudolph** [comment]
Wow, very nice!

**Comment by ktoso** [comment]
Thanks a lot @jrudolph for the docker images with the autobahn specs inside, that saved me a lot of pain :-)
