### ISSUE TITLE
Akka HTTP, docs: Document the Spray's one-actor-per-request equivalent

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18569]
It's a fairly common pattern in Spray and was considered best-practice.
We should document what to do with this pattern when using Akka HTTP.

User feedback was:
:point_up: [September 26, 2015 3:04 PM](https://gitter.im/spray/spray?at=560697d0dae2d316227b4b43)

> I couldn't get the pattern to work without refactoring significantly. Previously by BridgeActor (i.e. the per-request actor, could complete the request by calling req.requestor ! SomeSerializableClass however in Akka-Http there is no requestor and calling req.complete doesn't finish the request because it was initiated by an Ask which expects a response

> I have def myRouteDirective(): Route = ctx => { but I can't figure out in there how to do an Ask on an actor and get back to a Future[RouteResult]. i.e. my Ask returns a Future[MyThing] or Future[MyError], and I can't fugure out how to complete or fail with the ability to serialize my objects and specify the http response code

**Comment by ktoso** [comment]
Maybe this should be covered directly by the "from Spray migration guide" https://github.com/akka/akka/issues/17972

**Comment by giannoug** [comment]
Any updates on this?

**Comment by dgomezs** [comment]
Any update on this? i'm starting to migrate my spray applications and I was using the actor per request pattern. Any alternative was to accomplish the same with akka http?

**Comment by ktoso** [comment]
We're focused on polishing internals, performance and such things currently. I think it's not terribly hard to port the original https://github.com/NET-A-PORTER/spray-actor-per-request/tree/master/src/main/scala/com/netaporter/routing code to Akka HTTP, so if you had time to attempt it that would be a lovely blog post many people would benefit from.

Can't promise we'll have time to focus on explaining that case right now, depends how quickly we reach our goals this sprint.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
