### ISSUE TITLE
Publish MemberJoined event

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#18575]
As discussed with @patriknw, add `MemberJoined` to the `ClusterEvent`s.

**Comment by patriknw** [comment]
I agree that it is no point in hiding these things. Joining members are anyway included in the `CurrentClusterState`.

The use case we discussed was to find a way to know when a join attempt is successful.

**Comment by hseeberger** [comment]
Any chance this is going to happen in 2.4.1? If help needed, I could probably come up with a PR.

**Comment by ktoso** [comment]
If you could PR I think we can surely include it :)

**Comment by hseeberger** [comment]
Fair enough. So there are no compatibility concerns?

**Comment by hseeberger** [comment]
Looks like this won't break binary compatibility, i.e. I'll create a PR.

**Comment by patriknw** [comment]
That would be great.

**Comment by patriknw** [comment]
This was fixed in 2.4.1, right? wrong milestone

**Comment by hseeberger** [comment]
Yep.
