### ISSUE TITLE
Akka Streams, doc: Document awaiting for completion, when multiple sinks involved

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18573]
Came up on gitter :point_up: [September 27, 2015 7:34 AM](https://gitter.im/akka/akka?at=56077fc82652445532ce6001)

Let's say my FlowGraph has many sinks. We should explain that in order to safely call `system.shutdown()` after "completion" one should await on all of them (i.e. take them into the materialized value of the graph and `Await.ready(Future.sequence(m1, m2), ...)`).

**Comment by rkuhn** [comment]
This is covered by #20069 .
