### ISSUE TITLE
Support WriteFile / transferTo

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18576]
As mentioned in https://github.com/akka/akka/issues/18571#issuecomment-143671349 we have decided to not port this feature in the initial round of porting features from Spray, however at some point we may want to re-visit this decision if given good reasons.

**Why not support it right away:**
It would require bypassing the entire streaming infrastructure and we back-pressure guarantees along with it etc. 

**Current replacement API:**
For users who were using `WriteFile` support we recommend feeding the HttpResponse using the [SynchronousFileSource](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-io.html#Streaming_File_IO).

**Comment by jrudolph** [comment]
See here for the original PR that would add support for "bytes from file" to ByteString: https://github.com/akka/akka/pull/2110

**Comment by ktoso** [comment]
Thanks for linking!

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
