### ISSUE TITLE
How to cleanup after response in akka-http

### ISSUE THREAD

**Issue by adamretter** [akka/akka#18571]
I am using the routing DSL in Akka HTTP.

I extract a file from a Multipart form upload request and write it to a temporary location on disk, I then process that file which creates a second temporary file.

I return the second temporary file as my response to the user. However, once the response has been sent to the user, I would like to delete the two temporary files that I created.

My route contains something like this:

```
encodeResponse {
  complete(HttpResponse(OK, entity = HttpEntity(`application/pdf`, pdfResult.jfile: File)))
}
```

My question is how do I know when the response has been fully sent to the client so that I can delete the temporary `pdfResult` file from disk?

**Comment by ktoso** [comment]
Seems like we're missing a replacement for the `withAck` feature.
Sadly Source completion signal can not be used here, as it's too early. We need the sink's completion.

This is how it was in spray: http://spray.io/documentation/1.2.2/spray-can/common-behavior/#acked-sends

```scala
req.responder ! HttpResponse(OK, HttpEntity(`application/pdf`, HttpData.fromFile(pdfResult.path))).withAck(ResponseComplete) //stream result back to client
// where req is a spray.routing.RequestContext
```

**Comment by ktoso** [comment]
// cc @sirthias @jrudolph ping, in case you've had thoughts on this already

**Comment by jrudolph** [comment]
> Sadly Source completion signal can not be used here, as it's too early.

Why would it be too early? We don't use `WriteFile` any more, so, after the SynchronousFileSource flagged completion, it should have closed the file, right?

**Comment by ktoso** [comment]
Hm, now that you mention it here it should be fine. The use-case I understood here was phrased as "once the response has been written completely, I want to delete the file". It's slightly different, and maybe the file example is not the best, but imagine a "successful downloads counter", it'd want to update the count after emitting the entire data to the connection, not after reading the entire file.

**Comment by jrudolph** [comment]
@ktoso, yes, that's exactly what changed between spray and akka-http. In spray we used Akka IO's `WriteFile` which delays reading the file and uses `FileChannel.transferTo` to read the file only in Akka IO. In that case, you have to rely on the acknowledgement to be sure that you can delete the file. Very early in the development process of akka-stream/akka-http it was decided that this optimization (support for `WriteFile`/`transferTo`) won't be carried over to akka (for the time being), so now the responsibility for keeping the file is now properly encapsulated in the original `SynchronousFileSource`.

The use-case you described cannot be modeled by a single HTTP protocol exchange. The notion of "emitting the entire data to the connection" is not really useful. You cannot observe if the peer has received the complete data just by observing your side of the connection. You can observe some parts of the pipeline but there's still the send buffer on your side, the network, the receive buffer on the peer side, and the complete peer side application stack between your application logic and the peer's. If you need to be sure the other side has received all data, you need to build an application-level protocol that semantically acknowledges that the peer *application* has received all the data.

**Comment by ktoso** [comment]
> The notion of "emitting the entire data to the connection" is not really useful. You cannot observe if the peer has received the complete data just by observing your side of the connection.

Right, that's true as well... It's false confidence in any case (source's completion, or write completion).

> Very early in the development process of akka-stream/akka-http it was decided that this optimization (support for WriteFile/transferTo) won't be carried over to akka (for the time being), so now the responsibility for keeping the file is now properly encapsulated in the original SynchronousFileSource.

Hm, I see. True that it's not representable using plain streams (maybe some custom graph hackery), so not something we'll want to jump on right now. I'll see if we have a ticket for it.

**Comment by sirthias** [comment]
I fully agree with @jrudolph here.
Watching for completion of the response entity stream and using that as a trigger for deleting the file should work fine in the OP's use case. The stream DSL doesn't yet make this task as easy as it could be but the approach should work fine.

**Comment by ktoso** [comment]
In that case I think we'll be able to solve it by extending the Streams DSL, something like `source.tap(Sink.onComplete { file.delete })` would be good enough here. // cc @rkuhn @drewhk

**Comment by ktoso** [comment]
Note @adamretter that for now you could use a Stage to listen for completion like this:

```scala
    val theFile = new File("")
    val s = SynchronousFileSource(theFile)
    
    s.transform(() => new PushStage[ByteString, ByteString] {
    override def onPush(elem: ByteString, ctx: Context[ByteString]): SyncDirective = {
      ctx.push(elem)
    }

      override def onUpstreamFinish(ctx: Context[ByteString]): TerminationDirective = {
        theFile.delete()
        super.onUpstreamFinish(ctx)
      }
      override def onDownstreamFinish(ctx: Context[ByteString]): TerminationDirective = {
        theFile.delete()
        super.onUpstreamFinish(ctx)
      }
    })
```

**Comment by jrudolph** [comment]
Couldn't you also use the newish `postStop` method of `PushStage` for this?

**Comment by ktoso** [comment]
Good catch! Look at me, like an old man: "*back in my days we had to override both (!)  `onUpstreamFinish` and `onDownstreamFinish`!*" :wink:

**Comment by adamretter** [comment]
Thanks guy. Just heading on holiday for a week. Will give it a go when I return

**Comment by ktoso** [comment]
Have a nice one!

**Comment by adamretter** [comment]
@ktoso Thanks and sorry for the delay, I am now back and looking at this again.

Just wondering how to return the `SynchronousFileSource` as the result of the request. At present I have something like:

```scala
complete(HttpResponse(OK, entity = HttpEntity(`application/pdf`, theFile)))
```

However, I cannot just replace `theFile` with `s` as, `HttpEntity` does not seem to allow a SynchronousFileSource as a parameter type, any ideas?

**Comment by ktoso** [comment]
@adamretter that will actually work now in Akka HTTP 1.1 - fixed in this commit https://github.com/akka/akka/commit/eeb20bee809c94f255d8b230933c448fa730215e :smile: 
On 1.0 you can say ` Chunked.fromData(ContentType, Source)` or stick with the known-size method on `HttpEntity(ContentType, ContentLength, Source)`

**Comment by ktoso** [comment]
Also, please check out the `fromFile` directive, it internally uses a SynchronousFileSink and is much easier to use :-)

**Comment by adamretter** [comment]
@ktoso Perfect thanks. As 1.1 isn't released yet, I have to stick with 1.0.

Just a note... I couldn't find the `fromfile` directive, even when I looked at the latest snapshot docs?

**Comment by ktoso** [comment]
Ah right, sorry – it's `getFromFile` and more documentation for it is up to be merged on monday (spent the entire week on writing docs ;-)).

Here's the new docs (in a PR, to be merged monday): https://github.com/akka/akka/pull/18684/files#diff-0dae3418fcdb6ad7e7c18fb5f4633a98R3
And examples: https://github.com/akka/akka/pull/18684/files#diff-e76b3bb2133707d4103e5b7462d9b562R14

-- 
Cheers,
Konrad 'ktoso’ Malawski
Akka @ Typesafe

On 27 September 2015 at 00:10:25, Adam Retter (notifications@github.com) wrote:

I am using the routing DSL in Akka HTTP.

I extract a file from a Multipart form upload request and write it to a temporary location on disk, I then process that file which creates a second temporary file.

I return the second temporary file as my response to the user. However, once the response has been sent to the user, I would like to delete the two temporary files that I created.

My route contains something like this:

encodeResponse {
  complete(HttpResponse(OK, entity = HttpEntity(`application/pdf`, pdfResult.jfile)))
}

My question is how do I know when the response has been fully sent to the client so that I can delete the temporary pdfResult file from disk?

**Comment by adamretter** [comment]
@ktoso Ah right, I was already familiar with the older `getFromFile`. In this case though I am responding to a POST. Basically my file is a generated PDF using Apache PDFBox and I need to send that back to the client.

What would be interesting perhaps would be a `fromFile` which could be more general than `getFromFile`, also perhaps fromFile could take an argument to cleanup temporary files as it seems to me that this is likely a common use case e.g.

```
fromFile(theFile, delete = true)
```

Of course `fromFile` could then still be used inside `get`, `post` and the other method directives.

**Comment by ktoso** [comment]
I think such directive can be very simply built in user land. Akka HTTP tries to include a rather minimal set of directives that are easy to build-upon, and this case sounds like a more specific need so I'd first like to keep it outside, and if more people seem to need it we may eventually pull it in.

In any case: As mentioned above, you can do this already, feed the HttpEntity with a SynchronousSource and broadcast to a completion Sink in which you delete the file. If you could share this directive as a project or gist, people could benefit from it etc :-)

We're thinking how to encourage such contributions more, i.e. we want a lot of cool directives, but not neccessarily in Akka's core - as outside they can be released and developed much more independently. Hope this sounds interesting to you as well :-)

**Comment by adamretter** [comment]
@ktoso Hmmm... wouldn't `fromFile` which is applicable to any HTTP method, be a more general building block that `getFromFile` which is limited to just the GET method?

Regardless, I just wanted to say thank you for all your support, truly excellent :-)

Of course if there was a place to put these things, I would put in the few I have built. I have some kinda nice(?) examples for extracting lots of parameters (optional and mandatory) from multipart form bodies.

**Comment by ktoso** [comment]
If you don't mind I'd like to keep this open until we have the pattern documented, it's likely others will bump into similar questions like you had @adamretter. Would be even more awesome if you could package up the solution as a directive and we'll find a place to put it (will discuss this next week).

**Comment by adamretter** [comment]
Would I be correct in thinking that with Akka HTTP 2.4.2 then the same solution would look like:

```scala
val src = FileIO.fromFile(file.jfile).watchTermination() { (mat, futDone) =>
  futDone.onComplete { done =>
    file.delete()
    debug(s"Deleted temporary result file: ${file.path}")
  }
  mat
}
```

I then use it like so:

```scala
file
      .size
      .map(size => HttpEntity(contentType, size, src))
      .getOrElse(HttpEntity.Chunked.fromData(contentType, src))
```

**Comment by ktoso** [comment]
Something like that looks to be in the direction of the right thing :) get it to compile and please contribute a docs example? That would be awesome if you could :)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
