### ISSUE TITLE
Notification when ClusterClient can't reconnect

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18577]
The ClusterClient should stop itself if the reconnect attempts with know contact points are not successful after a configured timeout. Then it can be watched to know that it failed and must be started again with new contact points.

The use case is that the server cluster is completely restarted and bound to new addresses. Then the ClusterClient will never be able to reconnect with the old contact points. Application might be able to lookup new contact points from some service discovery facility and start new ClusterClient with fresh information.

**Comment by huntc** [comment]
Thanks for raising this - so just to clarify - there's presently no way of detecting that a cluster client cannot connect to its list of previous endpoints?

**Comment by patriknw** [comment]
I don't see a nice workaround. The app can of course send some kind of heartbeats or ack messages and when those don't arrive it can interpret that as this connection issue.
