### ISSUE TITLE
Streams: Props(new ...) should be used as it's faster and safer

### ISSUE THREAD

**Issue by agolubev** [akka/akka#18582]
based on @rkuhn comment https://github.com/akka/akka/pull/17995/files#r40461233

**Comment by ktoso** [comment]
The perf difference wasn't that big if I remember correctly, however it's something we could try out and see the impact on materialization, why not :)

**Comment by hepin1989** [comment]
At least it will be more safer right:)?

**Comment by agolubev** [comment]
@hepin1989, even happy path unit test will handle this.

**Comment by agolubev** [comment]
@ktoso, I verified that this is done for streams project. Should title be changed for targeting other projects?

**Comment by rkuhn** [comment]
No, let’s fix things when they are recognized as problematic. Thanks @agolubev !
