### ISSUE TITLE
add value-based groupedWithin

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18587]
Like groupBy but actually closing substreams when done—relying on the ordering of elements in the incoming stream.

**Comment by drewhk** [comment]
I miss some details here. What is the exact semantics?

**Comment by rkuhn** [comment]
This was triggered while talking about logical clocks and how we can use them in streams. We have groupedWithin for batching up based on size or wall clock time, but batching up based on some quality of the data elements would be needed for logical time batches—where logical may well be “some timestamp that was taken when the data entered our system”.

**Comment by rkuhn** [comment]
So, I am not yet sure about whether it should be strict (like groupWithin) or streaming (like groupBy), but that is not the most important part for me right now.

**Comment by rkuhn** [comment]
I think supporting logical time is a bigger effort than this, it might be an entirely different materializer.
