### ISSUE TITLE
Create lightweight graph DSL alternatives

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18588]
For example:

     src.broadcast2( (src1, src2) =>
        src1.map().filter...
        src2.via(...)...
     )

Where, src1-2 are FlowOps but not Graph[SourceShape] otherwise it would be possible to materialize them separately.

This is just a rough idea, the point is that src.broadcast(sink1, sink2) might force a certain construction order which is not always desirable.

**Comment by rkuhn** [comment]
We have merge(Sorted), zip(With), alsoTo for attaching another Source or Sink; do we need to add variants that take more arguments?

**Comment by drewhk** [comment]
no one asked for it so far.
