### ISSUE TITLE
Possible Bug in LeveldbStore.asyncWriteMessages 

### ISSUE THREAD

**Issue by gavares** [akka/akka#18581]
Class: LeveldbStore.scala
Branch: master (currently at commit f0edeeeadf67400c9dfadd6c34e81890d9d6eac4)

In function `asyncWriteMessages`, a call is made to `addToMessageBatch`. For each of the tags associated with the PersistentRepr passed to `addToMessageBatch`, a call to `nextTagSequenceNr` will be made which mutates the map `tagSequenceNr` by incrementing the sequence number for the supplied tag.

If an exception is throw when the `withBatch` block created in `asyncWritesMessages` attempts to persist the batch, the exception will be wrapped in a `Failure` and returned to the caller but the `tagSequenceNr` map remains in it's updated state. That is, each of the tags in the batch will have had it's next sequence number incremented k times where k is the number of occurrences of that tag in the batch. 

Subsequence calls to `asyncWriteMessages` containing the same tag will be assigned sequence number n+k where they should have been assigned sequence number n.

Maybe this case is being handled further up the stack? I can see some action being taken [here](https://github.com/akka/akka/blob/40936e8333a11d7a2dd6854e82a9631dcfc36e01/akka-persistence/src/main/scala/akka/persistence/journal/AsyncWriteJournal.scala#L107) but it seems that some place further up the stack would then need to force the LeveldbStore actor to halt in order to recover properly.

If this isn't being handled, one simple fix might be to do away with the `tagSequenceNr` map and call `readHighestSequenceNr` once for each tag in the batch. 

Another option is to delay the mutation of the `tagSequenceNr` map until after the batch has been successfully persisted.

**Comment by patriknw** [comment]
Thanks for the observation. Do you see any other negative consequences than that there can be holes in the used sequence numbers for the tagged events?

**Comment by gavares** [comment]
I don't think so. I have, in the past, used holes in seq. numbers to determine if messages have been lost or delivered out of order as it was always my assumption that as well behaving system wouldn't have holes. 

I only noticed this because I'm currently implementing the various query traits for another persistence plugin. If this behavior is acceptable then I'll likely proceed with a similar approach.

**Comment by patriknw** [comment]
I don't think we explicitly say anywhere that the sequence number series must be without holes. I'm not sure if we should require that or not.

Anyway, this is an interesting topic, but not mandatory to fix in 2.4.0. If anything must be done it can go into an upcoming 2.4.x, as far as I can see.

**Comment by patriknw** [comment]
We allow [rejections](http://doc.akka.io/docs/akka/2.4.0-RC3/scala/persistence.html#Failures) so there can definitely be holes in ordinary persist of events, so I see no reason to require something else for tagged events.

**Comment by patriknw** [comment]
when reading this again I think the conclusion is that we shouldn't change anything, please reopen if other opinion
