### ISSUE TITLE
IllegalRequestException.status should allow ServerError statusCodes

### ISSUE THREAD

**Issue by analytically** [akka/akka#18593]
Currently IllegalRequestException only accepts ClientError status codes. I'd like to return eg. 500 ISE to some requests using IllegalRequestException.

**Comment by ktoso** [comment]
I'm not convinced that's the way to go.
If you're throwing exceptions, make them carry meaning, and then provide an implicit `ExceptionHandler` that is able to convert them into the right error responses.

See here for an example: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/exception-handling.html

// cc @sirthias @jrudolph

**Comment by ktoso** [comment]
// In theory the ExceptionWithErrorInfo is a public class so you could write your own exception type extending it which would carry the error code you want.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
