### ISSUE TITLE
http: formField(s) and HttpEntity.Default

### ISSUE THREAD

**Issue by stanch** [akka/akka#18591]
Hi,

I have an endpoint that works for most clients, but for two of them `formField` fails with `Request is missing required form field`. Requests from clients that don’t have issues are using `HttpEntity.Strict` with `application/x-www-form-urlencoded`:
```scala
HttpEntity.Strict(application/x-www-form-urlencoded,ByteString(97, 110, 115, 119, 101, 114, 61, 38, 115, 107, 105, 112, 112, 101, 100, 61, 116, 114, 117, 101, 38, 104, 97, 115, 104, 61, 101, 48, 54, 98, 49, 97, 98, 55))
```
The failing ones however are using `HttpEntity.Default`:
```scala
HttpEntity.Default(application/x-www-form-urlencoded,11,akka.stream.scaladsl.Source@4a0a448a)
```
This makes me think that something in the interaction between `formField` and `HttpEntity.Default` is not right. What could be the reason for a different entity type? Chunking/compression? Is there any simple workaround I can implement on my side?

**Comment by stanch** [comment]
Actually I don’t think this has to do with chunking. Here are the full requests logged by `logRequest`:
```
// GOOD
HttpRequest(
   HttpMethod(POST),
  <URL>,
  List(
    Remote-Address: <ADDRESS>,
    Host: <HOST>,
    Connection: keep-alive,
    Cache-Control: max-age=0,
    Accept: text/html, application/xhtml+xml, application/xml;q=0.9, image/webp, */*;q=0.8,
    Origin: <ORIGIN>,
    Upgrade-Insecure-Requests: 1,
    User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36,
    Referer: <REFERER>,
    Accept-Encoding: gzip, deflate,
    Accept-Language: ru-RU, ru;q=0.8, en-US;q=0.6, en;q=0.4
  ),
  HttpEntity.Strict(application/x-www-form-urlencoded,ByteString(97, 110, 115, 119, 101, 114, 61, 38, 115, 107, 105, 112, 112, 101, 100, 61, 116, 114, 117, 101, 38, 104, 97, 115, 104, 61, 52, 51, 52, 102, 50, 102, 100, 56)),
  HttpProtocol(HTTP/1.1)
)

// BAD
HttpRequest(
  HttpMethod(POST),
  <URL>,
  List(
    Remote-Address: <ADDRESS>,
    Host: <HOST>,
    Connection: keep-alive,
    Cache-Control: max-age=0,
    Accept: text/html, application/xhtml+xml, application/xml;q=0.9, image/webp, */*;q=0.8,
    Origin: <ORIGIN>,
    Upgrade-Insecure-Requests: 1,
    User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36,
    Referer: <REFERER>,
    Accept-Encoding: gzip, deflate,
    Accept-Language: ru-RU, ru;q=0.8, en-US;q=0.6, en;q=0.4
  ),
  HttpEntity.Default(application/x-www-form-urlencoded,11,akka.stream.scaladsl.Source@4a0a448a),
  HttpProtocol(HTTP/1.1)
)
```

**Comment by jrudolph** [comment]
The distinction between Strict and Default is probably a red herring. You don't show the entity data of the BAD request which seems to have length of 11 which seems to be less than for the good request. Maybe you can post the data of the failing requests as well?

**Comment by stanch** [comment]
I see. I wish I had it in the logs, but I don’t. What is the safest way to consume the entity for logging purposes, without affecting the rest of the code?

**Comment by stanch** [comment]
@jrudolph I looked a bit deeper and in fact those requests are from slightly different pages. The page for the BAD request *does* send an 11-byte entity, which looks like `ByteString(104, 97, 115, 104, 61, 49, 55, 48, 48, 54, 48)` or `hash=170060`. The value of `hash` is constant for that page. So it is very likely that the content inside `HttpEntity.Default` is legit. The funny thing is that `hash` is exactly the field that is reported as not found :)

**Comment by stanch** [comment]
This seems to be an issue with an antivirus (!). Still have to collect the augmented logs to see what form data actually reaches the server.

**Comment by stanch** [comment]
Just noticed this one: https://github.com/akka/akka/issues/17740. Sounds really similar. I wonder what the root cause is.

**Comment by stanch** [comment]
Replacing `formFields(...)` with `entity(as[FormData]) { entity => /* use entity.fields */ }` fixes the issue. I logged the results obtained that way and all of them have the `hash` field, which was reported as missing in the original implementation. Therefore I think this might be a legitimate issue (to which having an antivirus on the client side might or might not contribute to some extent). I would like to help, but unfortunately I can’t reproduce it. I tried sending various strict and streamed entities through the test kit, and of course all the tests passed :)

**Comment by jrudolph** [comment]
Yes, I guess a reproducer would be a prerequisite of someone looking into it seriously.

**Comment by ktoso** [comment]
Indeed @jrudolph. If you could provide a reproducer than I'll be able to look into the problem @stanch.
Thanks in advance!

**Comment by longshorej** [comment]
I think I am running into this too. I threw the minimal code up at https://gist.github.com/longshorej/954485dc6697d8de6569

I see 404 rejections for this in all current versions of Safari (OSX and iOS) intermittently. Maybe 80% of the form submits work properly in this simple case but it's more like 20% in our complex app where I first noticed the issue.

I have yet to reproduce it with any other browsers nor HTTP client libraries but using entity(as[FormData]) makes the problem go away for Safari.

Hopefully someone has some ideas. Maybe #18540 is related? Or maybe I'm just missing something fundamental?

**Comment by marcelhoekstra** [comment]
i have the same problem and preproduced it with a performance test. 
The entity(as[FormData]) is a workaround that works

**Comment by ktoso** [comment]
Thanks for reporting. Was this on 2.0-M1?

**Comment by marcelhoekstra** [comment]
I've also reproduced the bug in the 2.0-M1 version

**Comment by ktoso** [comment]
Thanks for confirming @marcelhoekstra! Will have a look.

**Comment by 2beaucoup** [comment]
[Here](https://gist.github.com/2beaucoup/773a58a10a11107a678b) is the reproducer and the stacktrace is

```
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$3.setCB(StreamOfStreams.scala:509)
        at akka.stream.impl.fusing.SubSource$$anon$3.preStart(StreamOfStreams.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:468)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:365)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:504)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:539)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:472)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:495)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I guess the problem lies within `akka.http.scaladsl.common.StrictForm` which seems to have trouble with large payloads.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
