### ISSUE TITLE
HttpEntity.toStrict should not collect unlimited amounts of data and piggy back on generic ByteString aggregation stage

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18592]
I.e. it should get another parameter with the maximum number of bytes it should aggregate before failing.

**Comment by ktoso** [comment]
Very good point, thanks

**Comment by drewhk** [comment]
good point. It is now a GraphStage anyway, called ToStrict, and lives in the http.impl.util package object.

**Comment by jrudolph** [comment]
I just commented on that `ToStrict` part... See https://github.com/akka/akka/pull/18467/files#r40669033

**Comment by ktoso** [comment]
The `aggregateBytes(timeout, maxBytes)` is an awesome idea, and it'd also solve a common case people are bumping into with the Http Client - they actually *do* want to get it back in a strict collected `ByteString` (came up today as well).

**Comment by ktoso** [comment]
Yes we still want this

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
