### ISSUE TITLE
Sanity check: model.MessageEntity = RequestEntity

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18601]
I wanted to sanity check this piece of code:

```scala
package akka.http.scaladsl

package object model {
  /** An entity that can be used for every HttpMessage, i.e. for requests and responses. */
  type MessageEntity = RequestEntity
}
```

It made some javadsl interop rather tricky, is this indeed meant to be `RequestEntity` and not `HttpEntity`?

Please have a look @sirthias: https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/scaladsl/model/package.scala

The problems show around `MessageTransformations` (javadsl) and its `Self withEntity(RequestEntity entity);` which sounds like it should be any entity - both request and response?

I can't get this to compile properly:

```java
Source<ByteString, ?> bytes = request.entity().getDataBytes();
HttpEntity entity = HttpEntities.create(ContentTypes.TEXT_PLAIN, bytes); // <?> breaks down here, needs to be cast to (Source<ByteString, Object>) to compile 
HttpResponse.create()
  .withEntity(entity); // it's HttpEntity, yet it wants either RequestEntity or ResponseEntity
```

**Comment by ktoso** [comment]
ping in case this is something you've thought about already @sirthias @jrudolph (you're traveling AFAIR, right? no worries, just pinging)

**Comment by sirthias** [comment]
IMHO the `MessageEntity` is defined correctly like this. It denotes all `HttpEntity` sub-classes that can serve as entities in HTTP messages, i.e. requests as well as responses.
The thing to remember is that `RequestEntity extends ResponseEntity`, i.e. all request entities can also be used for responses, but not the other way around.

I didn't quite understand the problem you are having currently. Could you explain again?

**Comment by ktoso** [comment]
Hah, now I see what I did wrong - I actually fixed the type to HttpEntity (which is the super class of all) in the above example: `HttpEntity /* <- bad to fix it to HttpEntity*/ entity = HttpEntities.create(ContentTypes.TEXT_PLAIN, bytes);`

But if the proper type is retained, i.e.: `HttpEntityChunked chunked = HttpEntities.createChunked(ContentTypes.APPLICATION_JSON, single);`

Then `HttpResponse.create().withEntity(chunked)` works as expected, because
`public abstract class HttpEntityChunked implements RequestEntity, ResponseEntity`.

I can see devs being tripped up by this, I'll look for a place to provide a hint about this in docs / javadocs.

**Comment by sirthias** [comment]
Ah, cool! Glad that you figured it out!

**Comment by ktoso** [comment]
Yep, thanks for the help!

**Comment by ktoso** [comment]
Closing as is.
