### ISSUE TITLE
add “async” variants of stream combinators

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18603]
at least the stateful ones like fold and scan

**Comment by hipposlam** [comment]
I'd like to take a stab at this. Are the below signatures correct?
```
def scanAsync[T](zero: T)(f: (T, Out) ⇒ Future[T]): Repr[T]

def foldAsync[T](zero: T)(f: (T, Out) ⇒ Future[T]): Repr[T]

def reduceAsync[T >: Out](f: (T, T) ⇒ Future[T]): Repr[T] 
```

**Comment by ktoso** [comment]
I'm terribly sorry we didn't notice this comment @ghost!

The signatures are almost correct, for `Async` variants of operations we always require the parallelism (i.e. how many of the futures may be pending at the same time), like here:

```
def mapAsync[T](parallelism: Int)(f: Out ⇒ Future[T]): Repr[T]
```

so the above methods would also need that param, other than that the `f` type is correct.

Again, sorry we let this slip through the cracks, would still be awesome if you would want to contribute these!

**Comment by gaydenko** [comment]
Here https://groups.google.com/forum/#!topic/akka-user/suN2eKGALuM takes place discussion about async folding sink. Giovanni has suggested implementation. Also I have got tiny modification, also for the case zero is Future[U] rather U (real use case).

**Comment by TrustNoOne** [comment]
@gaydenko My solution was a simple application-level implementation. That's not the solution you would want in production, if you want a proper implementation you need to create a custom stage like this one: 
https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala#L607

I really don't have time to do it, but it looks like @ghost is working on it ;)

**Comment by gaydenko** [comment]
@TrustNoOne , thanks for clarification. Then a suggestion is to add also a sink folding with `zero: Future[U]`. That is to say `foldAsyncAsync` - don't know how to name it :)

Why does your suggested implementation can not be used in production? It is both sufficient in speed and humble in resources consumption in comparison with most imaginable application logic. I have tried few stress tests in real application and haven't noticed drawbacks yet. Am going to deploy :)

**Comment by p-swift** [comment]
If no one is currently working on this, I'll try to pick up where ghost left off.

Just to clarify, @ktoso and @viktorklang, it looks like we'd want to add `scanAsync`, `foldAsync`, and `reduceAsync` in the scaladsl and javasdl flows, and then implement the logic as `GraphStage`s. 

Is this what you have in mind for scaladsl `FlowOps`?
```
def scanAsync[T](parallelism: Int, zero: T)(f: (T, Out) ⇒ Future[T]): Repr[T]
def foldAsync[T](parallelism: Int, zero: T)(f: (T, Out) ⇒ Future[T]): Repr[T]
def reduceAsync[T >: Out](parallelism: Int)(f: (T, T) ⇒ Future[T]): Repr[T]
```

**Comment by drewhk** [comment]
I don't think parallelism makes much sense here, these are sequential operations

**Comment by ktoso** [comment]
Hah, you're right; disregard my comment on those needing parallelism, must have been too tired to notice

**Comment by p-swift** [comment]
I think parallelism could make sense if operator is associative -- think of a parallel `fold`.  It looks like the existing `fold` is more like `foldLeft`, though, and so it may be confusing if `foldAsync` is different.

**Comment by ktoso** [comment]
Yeah, our fold is foldLeft actually, so let's be consistent with that. :+1:

**Comment by drewhk** [comment]
> I think parallelism could make sense for an associative operator -- think of a parallel fold

It could, but the signature is not right for that.

**Comment by p-swift** [comment]
I don't know the signature problem. But I do know that omitting the parallelism makes for an easier implementation, so I'm going with that :)

**Comment by drewhk** [comment]
the signature problem is that `(zero: T)(f: (T, Out) ⇒ Future[T])` means that you can always work on an element and the current aggregate and such cannot parallelize since if two messages, M1 and M2 are applied to the same aggregate state S then what should be the end result?

**Comment by p-swift** [comment]
Ohhh. I get it now. You'd need something like `T >: Out`. Thanks!

**Comment by aloiscochard** [comment]
I was actually looking for a `filterAsync`, I thought it could make sense to mention it here. cheers!

**Comment by viktorklang** [comment]
@aloiscochard You mean like map(t => Future[(T, Boolean)]).filter(_._2) ?

**Comment by drewhk** [comment]
Almost, you want `map(t => Future[(T, Boolean)]).filter(_._2).map(_._1)` ;)

**Comment by viktorklang** [comment]
@drewhk Almost, you want `map(t => Future[(T, Boolean)]).collect({ case (t, true) => t })`

:D

**Comment by drewhk** [comment]
I want a :coffee: ;)

**Comment by rkuhn** [comment]
Almost :-)

~~~scala
mapAsync(f: T => Future[(T, Boolean)]).collect { case (t, true) => t }
~~~

**Comment by viktorklang** [comment]
@rkuhn LOL

**Comment by jypma** [comment]
I actually found myself needing a `filterAsync` as well just now, and on the Java side, where it's a bit more cruft:
```java
            .mapAsync(parallelism, e -> check(e).thenApply(v -> Tuple.of(e,v)))
            .filter(t -> t._2)
            .map(t -> t._1)
```

**Comment by mateusduboli** [comment]
I made a implementation for `ScanAsync` which is useful in my use case, which would otherwise need a `Await` to work with the synchronous version or to wait for all my elements to be processed if used `foldAsync`.

The issue is closed and by the discussion I couldn't understand if it will be implemented or not, should I create another issue or continue on this one?

**Comment by johanandren** [comment]
My bad it seems, I probably thought it was tracking only that FoldAsync PR. As it is in a released milestone now, please open a new ticket about those and reference that in your PR if you submit one @mateusduboli, thanks!
