### ISSUE TITLE
FAILED: FutureSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18607]
https://jenkins.akka.io:8498/job/akka-nightly/2656/consoleText

[info]     Expected exception java.util.concurrent.TimeoutException to be thrown, but no exception was thrown. (FutureSpec.scala:543)
[info]     org.scalatest.exceptions.TestFailedException:
[info]     at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:495)
[info]     at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:56)
[info]     at org.scalatest.Assertions$class.intercept(Assertions.scala:1014)
[info]     at akka.testkit.AkkaSpec.intercept(AkkaSpec.scala:56)
[info]     at akka.dispatch.FutureSpec$$anonfun$2$$anonfun$apply$mcV$sp$21$$anonfun$apply$mcV$sp$57$$anonfun$apply$mcV$sp$58.apply$mcV$sp(FutureSpec.scala:543)
[info]     at akka.dispatch.FutureSpec$$anonfun$2$$anonfun$apply$mcV$sp$21$$anonfun$apply$mcV$sp$57$$anonfun$apply$mcV$sp$58.apply(FutureSpec.scala:543)
[info]     at akka.dispatch.FutureSpec$$anonfun$2$$anonfun$apply$mcV$sp$21$$anonfun$apply$mcV$sp$57$$anonfun$apply$mcV$sp$58.apply(FutureSpec.scala:543)
[info]     at akka.testkit.EventFilter.intercept(TestEventListener.scala:110)
[info]     at akka.testkit.package$.filterException(package.scala:37)
[info]     at

**Comment by viktorklang** [comment]
@johanandren Was this fixed?

**Comment by johanandren** [comment]
Hmm. Thought there was a PR merged with this...

**Comment by johanandren** [comment]
Found it, https://github.com/akka/akka/commit/ea22eca7fddb546340c6385237187fbfe0009ca0

Hasn't happened since, merge, so I'll close it.

**Comment by viktorklang** [comment]
@johanandren Danke!
