### ISSUE TITLE
Remove akka.stream.io.Timeouts and move the essential functionality into FlowOps

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#18608]
Rationale:

1. It is not IO related (but it can be very useful *for* IO work)
2. It has discoverability issues (how does the beginner, or even in my case, contributor, know that it exists and where to find it?)
3. It has a lot of use-cases (i.e. it is to be considered a `general` utility/behavior)

**Comment by drewhk** [comment]
Ok, everything time related will be migrated to FlowOps

**Comment by viktorklang** [comment]
No, not everything time related, the essential functionality. I.e. adding BidiFlow ops to FlowOps would be weird?

**Comment by drewhk** [comment]
Obviously you cannot add it to FlowOps. How would that work even?

**Comment by viktorklang** [comment]
No idea, so let's *not move everything* time related :)
