### ISSUE TITLE
Akka HTTP, docs: Document all directives for Java 8

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18609]
This: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/java/http/routing-dsl/directives/index.html
needs those: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/alphabetically.html

It's like an [giant enemy crab](https://www.youtube.com/watch?v=pJElsNaC6yQ&feature=youtu.be&t=19s), we'll need to tackle together at some point (for critical damage).

**Comment by oagostinho** [comment]
Hi,

@ktoso: How can I help here?  

Cheers,

**Comment by ktoso** [comment]
Thanks for stepping up @oagostinho ! :-)
Here's a list of all the things that need to be documented: https://github.com/akka/akka/issues/18657

Pull requests should look similar to this one: https://github.com/akka/akka/pull/18663
So a directive or request-val needs docs and examples.

(Actually this ticket is a duplicate, so let's continue over there).

**Comment by ktoso** [comment]
Closing as more details are in issue https://github.com/akka/akka/issues/18657

**Comment by oagostinho** [comment]
@ktoso : I will try. ;-)

**Comment by ktoso** [comment]
Let us know in the other ticket if you pick one of them to document, so we won't spend time on the same one, thanks :)
