### ISSUE TITLE
Manage stream lifecycle externally

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18612]
It is commonly asked to be able to shut down streams from the outside, gracefully or ungracefully, and also react to stream completion (i.e. completion of a set of relevant sinks).

As a sidenote, I think this is related somewhat to streams "supervision" which actually supervises streams (as opposed to stages - what we have right now). Just an idea though.

**Comment by viktorklang** [comment]
Isn't this already possible by creating an ActorMaterializer for that materialization and then shutting it down when desired?

**Comment by drewhk** [comment]
That is the non-graceful version. This is about more graceful options.

**Comment by viktorklang** [comment]
As in cancellation or as in trying to figure out whether one can inject onCompletes?

**Comment by drewhk** [comment]
There are two parts of it (these are ideas, nothing concrete):
 - Flows that share a common Cancellable and are injected after relevant sources. Upon calling cancel on the cancellable() these cancel the upstream sources and complete the downstreams.
 - Some other mechanism that simplifies getting the completion from sinks, i.e. the event that "all elements have been properly processed and flushed"

I am not sure on the technical details, it is the pattern that matters here. This is among the most commonly asked features so we should think about how we can simplify it.

**Comment by viktorklang** [comment]
fat fingers

**Comment by rkuhn** [comment]
I think we have all angles covered: materializer shutdown in #20069, `watchTermination` already exists, and #19892 for the KillSwitch.
