### ISSUE TITLE
Possible performance regression in ConsistentHashingPool

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18613]
Not fully confirmed, but looks like it happens during initialization, maybe some resize gone n^2?

See user report on ML: https://groups.google.com/forum/#!topic/akka-user/p344JTPpIh8

**Comment by patriknw** [comment]
I don't think it's a problem with ConsistentHashingPool specifically, but with all pools configured with many routees. It looks like the time is spent in 

Here is some trace logging inside RepointableActorRef `sendSystemMessage` the for 10 routees. Each system message must iterate the queue until the next last element. You can imagine how that explodes for 100k.

    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$a#2121480742],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$a#2121480742],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$b#-1926314642],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$b#-1926314642],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$b#-1926314642],false)
    # queue.add insertIntoIndex 2 queue.size = 3  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$b#-1926314642],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$c#310134968],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$c#310134968],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$c#310134968],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$c#310134968],false)
    # queue.add insertIntoIndex 3 queue.size = 4  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$c#310134968],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$d#1339691123],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$d#1339691123],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$d#1339691123],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$d#1339691123],false)
    # tryEnqueue insertIntoIndex 4 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$d#1339691123],false)
    # queue.add insertIntoIndex 4 queue.size = 5  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$d#1339691123],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$e#-1548418219],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$e#-1548418219],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$e#-1548418219],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$e#-1548418219],false)
    # tryEnqueue insertIntoIndex 4 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$e#-1548418219],false)
    # tryEnqueue insertIntoIndex 5 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$e#-1548418219],false)
    # queue.add insertIntoIndex 5 queue.size = 6  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$e#-1548418219],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # tryEnqueue insertIntoIndex 4 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # tryEnqueue insertIntoIndex 5 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # tryEnqueue insertIntoIndex 6 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # queue.add insertIntoIndex 6 queue.size = 7  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$f#-456291702],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex 4 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex 5 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex 6 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex 7 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # queue.add insertIntoIndex 7 queue.size = 8  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$g#1143863724],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex 4 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex 5 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex 6 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex 7 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex 8 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # queue.add insertIntoIndex 8 queue.size = 9  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$h#1034342171],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 4 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 5 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 6 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 7 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 8 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex 9 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # queue.add insertIntoIndex 9 queue.size = 10  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$i#-1766362034],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex -1 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 2 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 3 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 4 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 5 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 6 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 7 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 8 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 9 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # tryEnqueue insertIntoIndex 10 Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)
    # queue.add insertIntoIndex 10 queue.size = 11  Supervise(Actor[akka://ConsistentHashingRouterSpec/user/router1/$j#-516659276],false)

**Comment by patriknw** [comment]
I think it would be easy to optimize for the normal case where there is only system messages by using a flag for that. The queue is protected by a lock anyway.

**Comment by drewhk** [comment]
I was not sure how much this use case is relevant though, so that's why this is not tagged triaged, just new.

**Comment by patriknw** [comment]
it's unnecessarily inefficient for small pools also, I think we should fix it

**Comment by viktorklang** [comment]
+1, it needs fixing.
