### ISSUE TITLE
Sealing routes should be documented near Routes section

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18617]
Sealing routes is not documented very explicitly in the routes page.

It has a more in depth explanation in `testkit.rst` http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/testkit.html#Sealing_Routes

I think this should be moved to routes as well as exception handling - gathered all the info already, need to dump it into the docs now.

**Comment by stanch** [comment]
The other day I realized that my cookies were not set because the route inside `setCookie` was not sealed and the rejections were handled outside. This could make a tip for those who want to set their cookies once a certain part of the routing tree is hit, regardless of the response.

**Comment by ktoso** [comment]
Any help on documenting this anyone? Would be lovely!

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
