### ISSUE TITLE
attachChild creates RepointableActorRef

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18619]
In ActorMaterializerImpl we use attachChild. https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/impl/ActorMaterializerImpl.scala#L243

Note that this creates a RepointableActorRef. Might not be a bottleneck, but perhaps a bit wasteful.

**Comment by patriknw** [comment]
cc @drewhk @rkuhn

**Comment by rkuhn** [comment]
Yes, this is necessary to make things work reliably.

**Comment by drewhk** [comment]
we use attachChild to keep materialization synchronous

**Comment by patriknw** [comment]
ok, closing as invalid. I just wanted to point it out so that it is not accidental that we don't use the most performant actor refs for the stream actors.
