### ISSUE TITLE
PersistentActor in 2.4.0 does not auto recover

### ISSUE THREAD

**Issue by Centaur** [akka/akka#18618]
Just migrated my application from 2.3.14 to 2.4.0, and these are what I have done: 

1. Implement `recovery` method of the `PersistentActor`as `override def recovery: Recovery = Recovery()`
1. Migrate old `PersistentView` subclass to `Persistence Query` because of the deprecation.
1. Confirmed that my `PersistentActor` has implemented `persistenceId` method

the `PersistentActor` and the new `Persistence Query` instance use the same leveldb storage.
It turns out that on application startup the `Persistence Query` instance runs as expected, receives all event history but the `receiveRecover` of the `PersistentActor` never received a message and throws no error.

Did I miss something important?

**Comment by ktoso** [comment]
I think you mean to ask that the read-side journal does not recover, not the PersistentActor (title / content of ticket mismatch)?

If so, then we're missing information about which method you're using. 
Each query is provided as auto-refreshing https://github.com/akka/akka/blob/master/akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/scaladsl/LeveldbReadJournal.scala#L166 and as "current" https://github.com/akka/akka/blob/master/akka-persistence-query/src/main/scala/akka/persistence/query/journal/leveldb/scaladsl/LeveldbReadJournal.scala#L177
The `current*` methods indeed won't refresh, but complete the source upon completion, by design.

This is documented in the docs: http://doc.akka.io/docs/akka/current/scala/persistence-query.html#AllPersistenceIdsQuery_and_CurrentPersistenceIdsQuery

Can you please fill in more information about what you're doing exactly and what's not as you expect it to be?

**Comment by patriknw** [comment]
That's not how I interpret the description: "Persistence Query instance runs as expected, receives all event history but the receiveRecover of the PersistentActor never received a message and throws no error."

How did you implement the `recovery` method? For normal recovery you don't need to implement the method at all.

**Comment by Centaur** [comment]
In the old 2.3.14 version, I did not implement the `recovery` method, the PersistentActor just did recover automatically on startup. In 2.4.0 version, I add it as described in the original post after I realized the auto recovery did not happen.

For reference,   here are the old and new code: 

2.3.14: [ConfigPersister.scala](https://github.com/Centaur/repox/blob/master/src/main/scala/com/gtan/repox/config/ConfigPersister.scala) [ConfigView.scala](https://github.com/Centaur/repox/blob/master/src/main/scala/com/gtan/repox/config/ConfigView.scala) [application.conf](https://github.com/Centaur/repox/blob/master/src/main/resources/application.conf)

2.4.0: [ConfigPersister.scala](https://github.com/Centaur/repox/blob/akka2.4.0/src/main/scala/com/gtan/repox/config/ConfigPersister.scala) [ConfigQuery.scala](https://github.com/Centaur/repox/blob/akka2.4.0/src/main/scala/com/gtan/repox/config/ConfigQuery.scala) [application.conf](https://github.com/Centaur/repox/blob/akka2.4.0/src/main/resources/application.conf)

**Comment by patriknw** [comment]
@Centaur I can't see anything wrong there. How do you test and observe that the recovery is not running? We have numerous tests for this so I have a hard time thinking that something such fundamental would be broken.

**Comment by Centaur** [comment]
@patriknw  Thank you for taking time. This actor has the responsibility to load config data at startup. Every event is a `UseDefault` or `ConfigChanged`, and on `RecoveryCompleted` this application's main actor `Repox.requestQueueMaster` gets notified a message `ConfigLoaded`. As you can see in the code, I added debug log on each `ConfigChanged` event and also on a "catch all" case, but none of these log showed up. And after application started up, the `Config` data remains `null` and `Repox.requestQueueMaster` never received the `ConfigLoaded` message.  I also tried setting breakpoints on each case of `receiveRecover` but none was triggered.

**Comment by patriknw** [comment]
The ExamplePersistentActor in https://typesafe.com/activator/template/akka-sample-persistence-scala works fine. Run `sample.persistence.PersistentActorExample` and you will see that the recovery works.

I'm afraid that I don't have the bandwidth to debug your code. If you think there is a bug in Akka persistence I suggest that you create a mimimized reproducer.

**Comment by Centaur** [comment]
Incorrect configuration of `akka.persistence.snapshot-store` in `application.conf` caused this problem. Auto recovery works after changing to 
```
    snapshot-store {
      plugin = "akka.persistence.snapshot-store.local"
    }
```
or just remove this part since there is no snapshot saved.

**Comment by ktoso** [comment]
Thanks for reporting the solution!

**Comment by patriknw** [comment]
Thanks for the update
