### ISSUE TITLE
add Source.blocking() for legacy API integration

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18620]
This shall construct a Source that defaults to the blocking dispatcher (like file IO) and includes construction as well as cleanup, possibly used like so:
~~~scala
Source.blocking(
  () => new BufferedReader(new FileReader("...")),
  file => Option(file.readLine()),
  file => file.close())
~~~
The important part is that the cleanup after normal and exceptional termination as well as cancellation.

**Comment by drewhk** [comment]
Before attacking the one-liner, I would also recommend adding a more flexible API using the GraphStage internally:

    Source.blockingStage { () => new BlockingStage {
         val file = new BufferedReader(new FileReader("..."))

         def onPull(): Unit = {
            val line = file.readLine
            if (line ne null) push(line) // we can add sugar for emitting multiple elements in one go
            else complete()
         }

         override def postStop() = file.close
      }
    }

**Comment by rkuhn** [comment]
BTW: the `emit` sugar is coming in #18605

**Comment by hepin1989** [comment]
```Source.resource```?

**Comment by agolubev** [comment]
Start working on this.
