### ISSUE TITLE
PR validation failures due to SSH permission problems

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18624]
Seems like some jenkins slaves don't trust the master anymore :wink: 

```

+ ssh a5.local rm -rf /localhome/jenkinsakka/pr-validator-per-commit-jenkins/3790
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
Build step 'Execute a set of scripts' changed build result to FAILURE
Build step 'Execute a set of scripts' marked build as failure
```

**Comment by patriknw** [comment]
that's strange, I noticed something similar previously and then I logged in as jenkinsakka and tried the commands without problems

**Comment by drewhk** [comment]
Is this something related? 

https://jenkins.akka.io:8498/job/akka-docs-dev/1/console

**Comment by ktoso** [comment]
Closing since this hasn't happened recently
