### ISSUE TITLE
Akka HTTP: effectiveUri should check port

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#18632]
`HttpMessage.effectiveUri()` currently doesn't check if the authority port of the request URI matches the `Host` header's port.

**Comment by ktoso** [comment]
Thanks for the ticket and research!

Copying your note from akka-user for reference:

> ports in Host headers should be fine (see http://tools.ietf.org/html/rfc7230#section-5.4) and be supported by akka-http. Just make shure that both host and port of the request URI are the same as in the Host header.
