### ISSUE TITLE
JournalSpec reject non-serializable events

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#18639]
It is not possible to satisfy `JournalSpec reject non-serializable events` eventstore journal, as it expects events to have incremented sequence number.

So basically the case with `6L` missed and then `7L` is written is not valid for this particular journal.
I'm still wondering whether it is expected to be a valid case for other journals?

```scala
      probe.expectMsgPF() {
        case WriteMessageRejected(PersistentImpl(payload, 7L, Pid, _, _, Actor.noSender, WriterUuid), _, _) ⇒
          payload should be(notSerializableEvent)
      }
      probe.expectMsgPF() {
        case WriteMessageSuccess(PersistentImpl(payload, 8L, Pid, _, _, Actor.noSender, WriterUuid), _) ⇒ payload should be(s"b-8")
      }
```

**Comment by patriknw** [comment]
There will be holes in the sequence numbers when events are rejected. Akka Persistence itself has no problems with holes. However, it should not be mandatory for a plugin to implement rejections, it should be allowed to fail in stead. Serialization is very specific business of the journal and we should not mandate anything around that.

We should relax this part of the TCK. Thanks for reporting.

**Comment by patriknw** [comment]
@ktoso Would you be able to fix this TCK adjustment, so that it's included in 2.4.1?

**Comment by ktoso** [comment]
I'll take care of it

**Comment by ktoso** [comment]
It is now possible to skip these tests.
