### ISSUE TITLE
FAILED: EventStreamSpec: must not allow initializing a TerminatedUnsubscriber twice

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18630]
[info] - must not allow initializing a TerminatedUnsubscriber twice **\* FAILED **\* (47 milliseconds)
[info]   true did not equal false (EventStreamSpec.scala:353)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6277)
[info]   at akka.event.EventStreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$21.apply$mcV$sp(EventStreamSpec.scala:353)
[info]   at akka.event.EventStreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$21.apply(EventStreamSpec.scala:343)
[info]   at akka.event.EventStreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$21.apply(EventStreamSpec.scala:343)
[info]   at 

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2965/consoleFull

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time

**Comment by raboof** [comment]
It happens on GitHub Actions though: https://github.com/akka/akka/pull/30415/checks?check_run_id=3163395945

**Comment by raboof** [comment]
Again at https://github.com/akka/akka/runs/3249665952?check_suite_focus=true

**Comment by andreaTP** [comment]
https://github.com/akka/akka/runs/3251302380?check_suite_focus=true

**Comment by raboof** [comment]
let's close tentatively assuming #30676 fixes it, reopen when we encounter it again
