### ISSUE TITLE
Are unbounded priority mailboxes _really_ blocking?

### ISSUE THREAD

**Issue by dimbleby** [akka/akka#18636]
I see that 3036012e deprecated (among others) the `UnboundedPriorityMailbox` and the `UnboundedStablePriorityMailbox`, on the grounds that they are blocking.

(Aside: these are only described as deprecated in the scala docs.  The java docs merely say "Aditional [sic] implementations exist which can be potencially [sic] blocking on pushing into the queue, however they can be configured...".  Surely the two sets of documentation should agree?)

Anyway, I think that this is probably a mistake:

- While it's true that the unbounded priority mailboxes are backed by a `PriorityBlockingQueue`, this is not blocking for pushing to the queue.  
- It's only `take()` that is actually blocking for a `PriorityBlockingQueue`, and akka doesn't care about that.

Therefore the unbounded priority mailboxes should be marked as not blocking, and be un-deprecated.

**Comment by patriknw** [comment]
@dimbleby Thanks for reporting. That must be a mistake. The conclusion from the first PR which was not merged was that we should warn but not deprecate: https://github.com/akka/akka/pull/18280
but it looks like some deprecation leaked into the documentation anyway: https://github.com/akka/akka/pull/18283

I also agree that the documentation is wrong regarding `Blocking: Yes` for `UnboundedPriorityMailbox`
