### ISSUE TITLE
Add non-trivial flow graph examples, preferably to Scaladoc

### ISSUE THREAD

**Issue by asarkar** [akka/akka#18638]
I'm cutting my teeth on Akka streams and I like it so far. However, the lack of non-trivial examples and reliance on "tribal knowledge" is making it a herculean task to actually get something useful out of it. One of the reasons people stick to Java is the excellent Javadoc. For example, look at the excellent [Pattern](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) API.

I've read [Working with Graphs](http://doc.akka.io/docs/akka-stream-and-http-experimental/current/scala/stream-graphs.html#Constructing_Flow_Graphs) and [Modularity, Composition and Hierarchy](http://doc.akka.io/docs/akka-stream-and-http-experimental/current/scala/stream-composition.html), both of which are excellent write-ups. They, unfortunately, fall short of what's required by a long shot.

If the project is to take off, there needs to be real code examples, preferably with Scaladocs. Speaking for myself, I'm trying to attach [2 subscribers to a fan out publisher](https://groups.google.com/forum/#!topic/akka-user/UznPhKEjLWA) and there's no code example about that I could find. None whatsoever. Examples available on the internet are either outdated or uselessly simple. Really, if I wanted to double a stream of integers, I'd not need a new library to do that.

**Comment by jrudolph** [comment]
Wrt `fanoutPublisher`, see also #18505.

**Comment by ennru** [comment]
[Working with Graphs](https://doc.akka.io/docs/akka/current/stream/stream-graphs.html) documents this well.
