### ISSUE TITLE
Double wrapping of PersistentRepr in JournalSpec

### ISSUE THREAD

**Issue by nilsga** [akka/akka#18646]
I'm trying to write a persistence plugin that has `supportsAtomicPersistAllOfSeveralEvents = false`, but I'm having some issues running the TCK for this scenario. It appears that the `PersistentRepr` is wrapped double, and I'm wondering if it could be a bug in this line in the `JournalSpec`: https://github.com/akka/akka/blob/master/akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala#L74

Doesn't this double-wrap, since `persistentRepr(i)` already creates an instance of `PersistentRepr`?

**Comment by patriknw** [comment]
That looks very much as a bug in the TCK. Thanks for reporting, @nilsga
