### ISSUE TITLE
Add Http().gracefulShutdown() which mimics Spray's CloseAll

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18649]
Implement a graceful shutdown which eventually closes connections (which is more than unbind does).

All details in the #18475 PR.

**Comment by ktoso** [comment]
Triaged to mark I've gon through here, however we won't work on it - up for grabs

**Comment by krzemin** [comment]
Hi, I'm interested in grabbing this. I assume that scope of the feature is basically what @sirthias wrote in https://github.com/akka/akka/pull/18475#issuecomment-145767909. However I will need some guidance to get started.

Let's consider server-side part first. I expect that pools shutdown is not an option here. Instead, we have to rather unbind all listening sockets, and then wait for all connections being processed to finish. Could you explain in a bit more details how to achieve it?

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
