### ISSUE TITLE
Clarify parsing / handling of `authority-form` of request target

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18643]
As detected in https://github.com/akka/akka/pull/18642#issuecomment-145501475 it seems that akka-http doesn't parse request targets correctly if the target is given in [`authority-form`](http://tools.ietf.org/html/rfc7230#section-5.3.3) which is only valid for `CONNECT` requests (that aren't supported by akka-http) anyway.

In an [akka-user post](https://groups.google.com/d/topic/akka-user/eAgsGyUzMu4/discussion), the error message was

```
akka.http.scaladsl.model.IllegalUriException: 'Host' header value of request to `openoox.com:8080` doesn't match request target authority: Host header: Some(Host: openoox.com:8080) request target authority:
```

which translates to

```
uri.toString == "openoox.com:8080"
hostHeader.toString == "Some(Host: openoox.com:8080)"
uri.authority == ""
```

So, this means the request probably was a CONNECT request and looked like this:

    CONNECT openoox.com:8080 HTTP/1.1

In this case the uri is parsed as

```
uri.scheme == openoox.com
uri.path == 8080
```

which doesn't make any sense.

akka-http should either properly parse this into a model representing the authority form or outright reject requests like this.

**Comment by ktoso** [comment]
Sounds like we may want to fail explicitly for CONNECT requests?
This was somewhat discussed and the ticket here created: https://github.com/akka/akka/issues/17976

**Comment by jrudolph** [comment]
I think what happens is that in the URI-parser the `request-target` rule is ambiguous:

```scala
// http://tools.ietf.org/html/rfc7230#section-5.3
  def `request-target` = rule(
    `absolute-path` ~ optional('?' ~ query) // origin-form
      | `absolute-URI` // absolute-form
      | authority) // authority-form or asterisk-form
```

because an `authority` request-target can also be parsed as an `absolute-URI`.

@ktoso if we fail CONNECT requests, we should probably also restrict request targets not to parse as `authority-form`.

**Comment by ktoso** [comment]
Since we don't support CONNECT properly, I think it's fair to fail explicitly with this information (maybe hide it behind a flag though?). Some people seem to be trying to implement such proxy as their hello world's for some reason, so failing explicitly will at least let them know what's going on.

Summing up the thoughts around this one... to resolve the general issue here we:
- detect and fail CONNECT requests?
  - hide this behaviour behind a "power user" flag (?)
- in the parser you mean simply dropping the `authority` from this rule @jrudolph?

Did I miss something / is there some downside I'm not taking into account (since we don't support CONNECT anyway, I'm not seeing any)?

For reference: https://tools.ietf.org/html/rfc7231#section-4.3.6

**Comment by 2beaucoup** [comment]
I think we should define what CONNECT-support means: If we define it as providing a correctly parsed CONNECT message on the server (#18643) and supporting proxies client-side (#17976), that should be doable.

The user should then be responsible for handling such messages server-side (fail or proxy) as they would do for other message types.

**Comment by jrudolph** [comment]
@2beaucoup this isn't possible because `CONNECT` doesn't follow the usual protocol after the first exchange of messages. You need to switch out the complete parsing/rendering pipeline which isn't possible for user-applications at this point.

**Comment by sirthias** [comment]
I agree with @2beaucoup here, we should *parse* CONNECT requests correctly and deliver them to the application, which can then decide how to deal with them.
If we have an issue in the URI parser causing request targets in authority-form or asterisk-form to be parsed incorrectly then this should be fixed.
Maybe a simple reordering of the alternatives in the `request-target` will already do the trick?

**Comment by sirthias** [comment]
@jrudolph Yes, but the user can still decide on how exactly to signal the error to the client.
She cannot handle CONNECT requests fully on her side alone, that's true.

**Comment by jrudolph** [comment]
What would be the value of leaving this to the user?

Should we then check that the authority form is used only with CONNECT requests? And that absolute URIs have a proper scheme set?

**Comment by sirthias** [comment]
The benefit would be that we can maintain the separation between request parsing and semantic request interpretation as strictly as possible. Every time we have to mix the two the code becomes more complex (e.g. for `Expect: 100-continue` support).

But I can see that the value to the user is in fact small or even negative, so maybe we should indeed prevent CONNECT requests from reaching the application by turning them into a `MessageStartError` that flows across the `HttpServerBluePrint` bypass and causes a respective error response to be rendered.

In any case I think we should still fix the URI parser to properly recognize authority-form or asterisk-form.

**Comment by johanandren** [comment]
I spent some time on this issue, but didn't really get anywhere since the internal logic in `HttpRequestParser` expects "normal" requests, making the following test case: 

```
"with authority request target" in new Test {
        // we parse it correctly, but then we require Host header to be
        // present which isn't true for CONNECT, so it always fails with an error
        // about that
        """CONNECT example.com:80 HTTP/1.1
          |
        """ should parseTo(
          HttpRequest(CONNECT, Uri(authority = Authority(Uri.Host("example.com"), 8080)), protocol = `HTTP/1.1`))
        closeAfterResponseCompletion shouldEqual Seq(true)
      }
```

Fail with "Request is missing required `Host` header".

Leaving this issue for now as I don't want to complicate the parsing logic with further semantics.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
