### ISSUE TITLE
Document Http RequestVals for Java

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18657]
The root Java page is: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/java/http/routing-dsl/directives/index.html
(Notice that it's currently linking to the Scala documentation.)

The Scala version of this ticket is: https://github.com/akka/akka/issues/18496
(There I'm ticking off done directives - I'll merge those in a minute or two so you can work on top of those).

Here's how a directive docs page looks in java: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/java/http/routing-dsl/directives/path-directives.html#pathdirectives-java
Compared with Scala http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/ there's more going on in the Scala one here.

Most directive docs look like this though: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/header-directives/headerValuePF.html so that's what we need to port.

**Comment by patriknw** [comment]
I'll guess we can just make notes in this ticket for missing implementations and someone can extract later.

Missing impl: `pass`, `extractHost`, regexp variant of `host`

**Comment by ktoso** [comment]
Yeah, let's do that as we go and then make tickets.

I found missing `FutureDirectives`, trying to implement them now, if stuck for a longer time I'll drop it.

**Comment by ktoso** [comment]
`complete` is lacking a type-safe `Future` variant.

**Comment by drewhk** [comment]
Taking `PathDirectives`

**Comment by patriknw** [comment]
`extractHost` is not missing, it's in `RequestVals.host`

**Comment by patriknw** [comment]
I'm grabbing MethodDirectives

**Comment by ktoso** [comment]
I'm dropping FutureDirectives, we won't do them as the scala-dsl does, because in javadsl route construction is completely separate from handling.

**Comment by ktoso** [comment]
I'll document `RequestVals - Headers`

**Comment by jrudolph** [comment]
> regexp variant of host

This one is called `RequestVal.matchAndExtractHost`

**Comment by jrudolph** [comment]
`pass` is not really a useful directive by itself, it is used to build other directives. We decided that the Java DSL would not be able to be as flexible as the Scala DSL when it comes to composing pre-defined directives into custom ones.

**Comment by jrudolph** [comment]
So, `pass` doesn't make any sense as you cannot build custom directives or custom routes for now. 

The reason are 1) that the RouteStructure hierarchy is fixed to prevent custom extension which would prevent a future inspection feature of the route structure and 2) the `Route` type itself is opaque to the user, so while you can create custom routes using the `handleWith` methods, you currently cannot execute subroutes manually.

**Comment by ktoso** [comment]
Picking formFields directives (request vals)

**Comment by ktoso** [comment]
I guess this ticket is not really valid, right @johanandren?

**Comment by ktoso** [comment]
Or let's keep as a reminder to get/keep feature parity...

**Comment by ktoso** [comment]
Closing as invalid, we documented many back in the day, now moving to new DSL though
