### ISSUE TITLE
Remove sugar APIs for FlowGraph construction and introduce canonical alternative

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#18659]
Rename:
FlowGraph.partial => create (Java) & apply (Scala)
FlowGraph.closed => runnable (Java) & runnable (Scala)

Remove:
SinkApply
SourceApply
FlowApply
BidiFlowApply
SinkCreate
SourceCreate
FlowCreate
BidiFlowCreate

This is not an exhaustive list, the end goal is to create a very small surface-area for the FlowGraph-builder so that it's easy to know what to use and how to use it.

**Comment by drewhk** [comment]
Optimally the fluid DSL should gain new powers as well, providing the most common use cases where the specialized apply methods were used.

**Comment by viktorklang** [comment]
@drewhk Which fluid DSL?

**Comment by drewhk** [comment]
FlowOps

**Comment by viktorklang** [comment]
@drewhk Right, I wasn't sure if you mean that or FlowGraph.Implicits._!

**Comment by rkuhn** [comment]
This was done in #18700.
