### ISSUE TITLE
Confirm dropped: SecurityDirectives, from-configuration

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18651]
Hi again guys @sirthias @jrudolph,
I'm doc-ing the `SecurityDirectives` and noticed we don't have the form-config style directives ported.

Seems they haven't been much used nor are they secure in any case - thus the decision of not porting them, did I get that right?

I mean those: http://spray.io/documentation/1.2.2/spray-routing/security-directives/authenticate/#from-configuration

This ticket is meant for documenting that it's on purpose not forward ported.

**Comment by sirthias** [comment]
Yes, keeping user info in the app config appeared to us as too insecure for inclusion in Akka.
Users can easily build stuff like this themselves, should they decide to go down that route, but we didn't want to bless this kind of approach by including a predefined implementation for it.

Also note that the design of the security directives has changed somewhat over what we had in spray.

**Comment by ktoso** [comment]
Great, thanks for confirming @sirthias :) Now people can google-up this issue in case they're looking for it :wink: 

> Also note that the design of the security directives has changed somewhat over what we had in spray.

Yup, I'm digging into it and documenting them right now.

**Comment by ktoso** [comment]
Closing, nothing to do here.
