### ISSUE TITLE
Do we need `Http.OutgoingConnection`?

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18653]
It is basically a copy of `Tcp.OutgoingConnection` that needs to be mapped. 

Couldn't it be a type alias instead?

/cc @sirthias

**Comment by ktoso** [comment]
Note: It's stable now, so if we care to remove it would have to go over deprecation cycle.
Most likely does not cost enough to care to remove I think thogh.

**Comment by ktoso** [comment]
Too late to remove it now,
