### ISSUE TITLE
Clarify: Why FormField.fromString need the class parameter

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18666]
Hi guys @sirthias @jrudolph,
I'm not completely sure I get why the following (`javadsl.FormFields`) method needs the `clazz` param:

```scala
  def fromString[T](name: String, convert: Function[String, T], clazz: Class[T]): FormField[T] = {
    implicit val tTag: ClassTag[T] = ClassTag(clazz)
    FormFieldImpl(name.as(Util.fromStringUnmarshallerFromFunction(convert)))
  }
```

Since we're providing the entire `String => T`, what is there to do for the marshalling infrastructure such at we need to involve it? I think I'm missing a piece of the puzzle here hm.

**Comment by jrudolph** [comment]
It's for `FormFieldImpl` which extending from `RequestVal` requires a class as metadata. I don't think it's currently used. Again, this is part of the future infrastructure which would allow inspecting routing tree and this kind of runtime type metadata seemed useful.

**Comment by jrudolph** [comment]
As it serves no purpose for now, maybe it would make sense to remove these from all the RequestVal implementations?

**Comment by ktoso** [comment]
Yep, I'll remove. If we need it we can always add methods.

**Comment by jrudolph** [comment]
Do you remove it in the whole hierarchy starting from `RequestVal`?

**Comment by ktoso** [comment]
That would be more tricky I guess... it's used for the `handleReflectively`. I was hoping to be able to remove it from the `fromString` methods (just starting that attempt now).

**Comment by ktoso** [comment]
On the other hand... much hassle but little gain, I'll leave but then would like to rearrange the parameter list to be `name, clazz, convert` as that matches how we have it in APIs like that in Streams.

**Comment by jrudolph** [comment]
I see, I forgot about `handleReflectively` for which it is certainly nice to be able to give errors while building the routes.
