### ISSUE TITLE
Use effectiveUri in Java route testkit

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18661]
On the Scala side of the testkit, each request is run through `effectiveUri` before it is dispatched to the route to mimic the behavior of akka-http-core to join relative URIs and the host header to an absolute URI.

See here:

https://github.com/akka/akka/blob/release-2.3-dev/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala#L146

For consistency, we should do the same on the Java side.

**Comment by patriknw** [comment]
remember to update `HostDirectivesExamplesTest.java` together with this fix

**Comment by ktoso** [comment]
@johanandren if you're looking for tasks that would be nice to fix https://github.com/akka/akka/issues/18661

**Comment by ktoso** [comment]
It's an inconsistency between testkit's, so it may trip people up
