### ISSUE TITLE
Akka HTTP: Directives Docs are hard to maintain

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#18660]
There's currently a lot of duplication between the directives docs and their implementation and examples. Ensuring consistency of both docs and code is hard.

A possible solution could be to generate the docs from the code (impl + samples + ScalaDoc) as follows:

- one folder per directive trait: [TRAIT-NAME]-directives with
- one index.rst file with a list of all directive methods + ScalaDoc of the trait
- one [METHIOD-NAME].rst file with [METHOD-NAME] as headline and the folowing paragraphs:
  - "Signature" with the extracted signature of the method
  - "Desription" constisting of the method's ScalaDoc
  - "Examples" with the snippets with id [METHIOD-Name]-[0..n] from [TRAIT-NAME]ExampleSpec.scala

The method's ScalaDoc could further be split so that the first part (separated by a blank line) is used as a summary (that could be added to the index) and rest for the "Description". 

This was sketched for the Scala docs but could work similarly for Java. The outcome would be constistent docs without manually mirroring the structure of the directives traits in the docs project.

Possible Problems:
- Does ScalaDoc cover all functionality that is currently used in the RSTs?
- Magnet Pattern vs. simplified signatures
- Where do additional paragraphs reside (e.g. `formFields` has "Unmarshalling" and "Details"")
- Some examples have additional text. Where do these come from?
- Generating additional categories like in `basic-directives/index.rst`. (By intrdoducing new traits?)

WDYT?

/cc @sirthias @jrudolph

**Comment by rkuhn** [comment]
solutions to this problem would surely be welcome!

**Comment by ktoso** [comment]
Any help on this front would be crazy awesome :)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
