### ISSUE TITLE
FormData and marshalling, easier/possible to use

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18665]
Let's say I'm in Java and want to test a route which deals with `FormData` (I actually really do :wink:), I'd want to say:

```java
    final HttpRequest request =
      HttpRequest
        .POST("/") // the below method does not exist (FormData also does not exist in javadsl)
        .withFormData(FormData.create(Pair.create("name", "Kapi"), Pair.create("age", "42")));
```

but can't since HttpRequest (or even `HttpMessage`) is not aware of FormData (i.e. the method withFormData does not exist). We also can't provide it on the type since it's in `akka-http-core` and we'd need marshallers, which are in `akka-http` (`PredefinedToEntityMarshallers`).

I don't have a good idea how to solve this simply...? One would have to manually call marshalling and use `withEntity` I guess now...? Open to other ideas (are we need a full DSL for request building for java?)

**Comment by ktoso** [comment]
// cc @rkuhn @sirthias @jrudolph

**Comment by ktoso** [comment]
Maybe providing a Marshaller of `FormData => Entity` would be enough, in javadsl `Marshallers`?

**Comment by jrudolph** [comment]
In any case, `withFormData` isn't enough to specify the request because it could either be url encoded or multipart formdata.

**Comment by jrudolph** [comment]
On the other hand, there's also still https://github.com/akka/akka/issues/15674 which is somewhat of a pain to port because of all the complexity that's inside, so having a simple solution that works for forms with textual data would really be nice.

**Comment by ktoso** [comment]
Right, that's true as well.
So what do you propose for now for Java users - should marshalling infra be called explicitly?
Then we must provide the ToEntityMarshaller for FormData in an accessible way for Java anyway.
Or am I missing some way of doing this already?

**Comment by ktoso** [comment]
Ah right, yeah if definitely links to #15674 in some ways.

**Comment by jrudolph** [comment]
At some point I added `Multipart.FormData.toEntity` already, so that's already usable from Scala without needing any marshallers. I think we should also add a `model.FormData.toEntity`, to simplify this as well.

Having done that, it would be easy to add the helper methods to the Java side HttpMessage even if the model itself is still missing on the Java side.

**Comment by jrudolph** [comment]
It's only a little bit of code that move have to move to `FormData`: https://github.com/akka/akka/blob/release-2.3-dev/akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala#L56

**Comment by ktoso** [comment]
Ok, so we don't feel it's against the purity of the core or sth like that ;-)
I'll give the move a shot then.

Again, huge thanks for all the hints @jrudolph - it's really invaluable.

**Comment by ktoso** [comment]
Managed to solve it by reusing the hinted at code :)
