### ISSUE TITLE
How to access non-"upgraded" http request header before Websocket connection is initialized in Java

### ISSUE THREAD

**Issue by thjaeckle** [akka/akka#18678]
Hi.
I am on Java, Akka 2.4.0 and Akka Http 1.0 and I use Websockets with the Routing DSL (code-snippet see below).

Now I would like to access the initial HTTP request's header fields (containing Authentication information set by my reverse proxy) before the Websocket connection is established / it is "Upgraded" to Websockets.

Can this currently be done? If yes, it would be cool to have this added to documentation. If not: Would love to see this feature :)

```
...
   @Override public Route createRoute() {
      return path("greeter").route(handleWebsocketMessages(greeter()));
   }

   public static Flow<Message, Message, Object> greeter() {
        return
            upcastMaterializerToObject(Flow.<Message>create()
                .collect(new JavaPartialFunction<Message, Message>() {
                    @Override
                    public Message apply(Message msg, boolean isCheck) throws Exception {
                        if (isCheck)
                            if (msg.isText()) return null;
                            else throw noMatch();
                        else
                            return handleTextMessage(msg.asTextMessage());
                    }
                }));
    }
    // needed because of #18028, see https://github.com/akka/akka/issues/18028
   @SuppressWarnings("unchecked")
   public static <T, U> Flow<T, U, Object> upcastMaterializerToObject(final Flow< T, U, ?> flow)
   {
      return (Flow<T, U, Object>) flow;
   }
    public static TextMessage handleTextMessage(TextMessage msg) {
        if (msg.isStrict()) // optimization that directly creates a simple response...
            return TextMessage.create("Hello "+msg.getStrictText());
        else // ... this would suffice to handle all text messages in a streaming fashion
            return TextMessage.create(Source.single("Hello ").concat(msg.getStreamedText()));
    }
...
```

**Comment by ktoso** [comment]
As I see it we're missing a possibility to get any RequestVals combined with using websockets currently.

The API would need to allow getting request vals, and the creation of the flow might depend on such a header (auth maybe), so it must be a factory, something like this perhaps:

```java
            path("greeter").route(
                handleWebsocketMessages(Headers.byClass(Location.class), (l) -> {
                    return greeter(l)
                })
            );
```

// cc @jrudolph @sirthias @rkuhn

**Comment by jrudolph** [comment]
Maybe we could add a `RequestContext.handleWebsocketMessages`, so that we could use the existing handler infrastructure instead of having to rebuild basically the same stuff again...

**Comment by ktoso** [comment]
Sounds promising - I'd love to not generate any more 1-22 versions of anything... :wink: 
My above proposal had no intent to bind to an API, just show the problem we need to solve. :)

**Comment by thjaeckle** [comment]
Is there a known work-around how to get that working now with 2.0?

**Comment by ktoso** [comment]
We should revisit this question given the new DSL

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
