### ISSUE TITLE
Community Project: AWS HttpRequest signing

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18696]
Fun community project would be to implement AWS request signing:
http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

Mentioned by @jasonmartens

// note: We're currently not planning to implement this ourselves, this is to inspire community members to maybe pick it up :)

**Comment by JoaoVasques** [comment]
Interesting project @ktoso . Right now, I'm working on a Apache Spark module for Play Framework using Akka. Will definitely look into it after it :)

**Comment by jasonmartens** [comment]
FYI, we have begun work on this here: https://github.com/dronekit/AkkaHttpAWSAuth
Not complete yet, but basically functional.

**Comment by JoaoVasques** [comment]
Thanks @jasonmartens ;)

**Comment by patriknw** [comment]
sounds like an external project

**Comment by ktoso** [comment]
Yeah, and AFAIR @jasonmartens's work is pretty far in that direction :)
