### ISSUE TITLE
WebSocket Extensions

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18709]
We currently do not support websocket extensions (i.e. registering "an extension" in the server, or requesting one in the client).

Currently we see no strong need to provide this functionality.
If you have a strong use case for it, please comment here.

**Comment by jrudolph** [comment]
There's already #17725 to support compression.

**Comment by ktoso** [comment]
Thanks for the cross-ref @jrudolph! This is a pre-req for compression, so I'll keep it around (smaller tickets = happier me).

**Comment by jrudolph** [comment]
Yes, definitely, we would need some lower-level support in the handshake etc. to make implementing extensions really extendable.

**Comment by ktoso** [comment]
Re-opening since we can't provide per message compression for people using socket.io unless we support extensions.

**Comment by johanandren** [comment]
I'll move this on over to akka-http

**Comment by ktoso** [comment]
Oh, I'm blind... thanks!

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 15 December 2016 at 14:08:13, johanandren (notifications@github.com)
wrote:

I'll move this on over to akka-http

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/18709#issuecomment-267323330>, or mute
the thread
