### ISSUE TITLE
[persistence-query] Read journal constructor exceptions are swallowed

### ISSUE THREAD

**Issue by jypma** [akka/akka#18708]
I'm writing a cassandra read journal:
```
class CassandraReadJournal(
    system: ExtendedActorSystem,
    config: Config
) extends ReadJournal with EventsByTagQuery {
```
Since it's not done, its constructor throws an exception (invalid cassandra query).

However, [PersistenceQuery](https://github.com/akka/akka/blob/master/akka-persistence-query/src/main/scala/akka/persistence/query/PersistenceQuery.scala#L82) catches any constructor exception and then tries to find alternative constructors (which don't exist), finally throwing a generic exception. There's no way to even get a try/catch in between the constructor, since most initialization typically happens in `val` assignments.

I'd recommend `PersistenceQuery` chaining the constructor attempts using a `recover { case x:NoSuchMethodException => ...try next... } `, so exceptions on constructors that were found propagate correctly.

**Comment by ktoso** [comment]
Good observation @jypma, thanks!
Would you like to submit a PR to fix this (basically what you describe sounds like the right thing to do)? :-)

**Comment by jypma** [comment]
Sure. To which branch should I target the PR?

**Comment by ktoso** [comment]
Target `release-2.3-dev` please, that's where we currently develop streams / http (will change soon, we'll move to master).

Thanks!

**Comment by jypma** [comment]
`PersistenceQuery` doesn't seem to exist in [release-2.3-dev](https://github.com/akka/akka/tree/release-2.3-dev) , are you sure about that as target branch?

**Comment by ktoso** [comment]
Ouch sorry @jypma, had an hour of sleep today :(
Persistence is on `master` (related it with streams in my mind, which is 2.3-dev indeed).
