### ISSUE TITLE
Warnings or auto-draining about not touched HttpRequest dataBytes

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18716]
In the bypass merge we can figure out that once the user has applied the Request => Response,
we require the dataBytes source to have been materialized.
If it's not, we log a warning, and we could drain the dataBytes.

Split when will need to emit a special source, that we can inspect and see if it's been materialized or not.

**Comment by drewhk** [comment]
warnings *and* auto-draining.

**Comment by ktoso** [comment]
We're working on fusing and things around Http, and this idea came up.
We'll be able to warn or consume the dataBytes for the users if the user forgot to drain the data from the request.

// cc @sirthias @jrudolph

**Comment by jrudolph** [comment]
You may want to look at existing tickets. There are some that suggest similar things but don't mention the technical approach.

> "Single actor Http pipeline, here we come!"

So, `concatAll` will be fusable?

**Comment by ktoso** [comment]
Both concat and splitWhen will be mergable (i.e. in general streams of streams will be)

**Comment by drewhk** [comment]
this ticket actually has nothing to do with fusing though, it just happened that we discussed this during our fusion discussion.

**Comment by sirthias** [comment]
Interesting.
Note that auto-draining might not always be what I want, though!
For example, if the request contains an entity with a content-length that it beyond the configured threshold I want to send an error response and *NOT* drain the incoming byte stream.
So, this auto-draining would definitely have to have a config switch (which could default to *on*).

**Comment by drewhk** [comment]
yes, that makes sense. We also want to log a Warning though, so it is not as much *on* vs *off, but instead *warn* vs *fail*?

**Comment by sirthias** [comment]
Wouldn't it be something like

```
request-auto-drain = on-with-warning # or `off`
```

?

**Comment by drewhk** [comment]
maybe that. I am not sure, I think we will see how it works in practice in the end anyway. This is just a high level idea so far.

**Comment by ktoso** [comment]
For reference, bypassMerge is gone, but the idea of this ticket is still valid.

**Comment by rkuhn** [comment]
In addition to the discussed possibilities it could make sense to add an option that auto-drains the request entity for successful “early” responses, but not for unsuccessful ones—in the latter case it would emit the error and close the connection (because continuing afterwards would not be legal for HTTP). This yields the following list of possibilities:

* no detection (current behavior)
* warning for unconsumed entities
* auto-drain unless rejected, in which case early response and close (should be default)
* auto-drain always

**Comment by ktoso** [comment]
Relates to https://github.com/akka/akka/issues/19602

**Comment by ktoso** [comment]
ping @rkuhn, if you have any new ideas please share :-)
We have not been working on this so far btw.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
