### ISSUE TITLE
Review Websocket server-side invalid handshake handling

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18711]
Currently, a request is either accepted, in which case the `UpgradeToWebsocket` header is added, or the handshake fails in which case we just pass the original request through to the application. Therefore, we leave any specialized error processing like returning a `Sec-Websocket-Version` containing the acceptable websocket versions to the user. This is flexible if you want to customize errors but it is  inconvenient if you expect akka-http to handle Websocket handshake errors transparently.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
