### ISSUE TITLE
docs: Balancing Dispatcher missing in Java-Docs

### ISSUE THREAD

**Issue by michaelom** [akka/akka#18712]
http://doc.akka.io/docs/akka/snapshot/java/dispatchers.html

> There are 4 different types of message dispatchers:

Yet, there are only three bullets. No mention of BalancingDispatcher.

**Comment by ktoso** [comment]
Thanks for reporting! We just were fixing things around there AFAIR, hm hm... //cc @patriknw

**Comment by patriknw** [comment]
Balancing dispatcher should not be used directly, it's an implementation detail of the BalancingPool

**Comment by ktoso** [comment]
Ah right, voting to close then.

**Comment by ktoso** [comment]
Would you like to submit the fix for this @michaelom? We don't want to document the BalancingDispatcher here explicitly.

**Comment by michaelom** [comment]
Hi @ktoso 

right, `4` should be a `3` to avoid confusion for Non-Hakkers.

Going through the hassle of cloning the project and submitting an PR just to change a `4` into a `3` seems a bit inefficient. ;-)

**Comment by ktoso** [comment]
@michaelom why clone? Click here: https://github.com/akka/akka/edit/master/akka-docs/rst/scala/dispatchers.rst do the change, and you'll get kudos as being listed as contributing in our logs :-)

Instant profit!

**Comment by ktoso** [comment]
(need to be clicked through all the way through to create the PR though :-))

Thanks @michaelom !

**Comment by michaelom** [comment]
Two clicks to instant fame. Guess I have to update my résumé now. :-)

I accidentally pushed https://github.com/michaelom/akka/tree/patch-1 though...

**Comment by ktoso** [comment]
Merged as https://github.com/akka/akka/commit/1be320fab9ce057d9d4c68d22035ebdb4b68c970

Time to pop the champagne ;)
