### ISSUE TITLE
Make Intersperse a GraphStage instead of StatefulStage

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18736]
It's possible to make it a PushPullStage: https://github.com/akka/akka/pull/18734/files#diff-3203199ba389ee802eef94486f26dc88R242

**Comment by lolski** [comment]
I'll give it a try

**Comment by ktoso** [comment]
Cool, thanks! Marking as in progress

**Comment by drewhk** [comment]
@lolski I recommend to go for a `GraphStage` directly instead. Can you do that?

**Comment by ktoso** [comment]
+1 to Endre's GraphStage point, as I've mentioned about this ticket already over the weekend: :point_up: [November 29, 2015 1:56 PM](https://gitter.im/akka/dev?at=565af5f549e74fad21eb96f8)

**Comment by lolski** [comment]
No problem, I'll give it a try (and maybe ask a couple of questions along the way).
