### ISSUE TITLE
FAILED: ClusterClientSpec on release-2.3

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18741]
https://jenkins.akka.io:8498/job/akka-release-2.3/219/consoleFull

Note that this is on the release-2.3 branch

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4570/consoleFull

**Comment by bantonsson** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4609/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.3/225/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5138/consoleFull
