### ISSUE TITLE
akka-jmh-bench included in 2.4.0 scaladoc

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#18744]
Why?

http://doc.akka.io/api/akka/2.4.0/?_ga=1.16514806.1579561034.1353497989#akka.persistence.PersistPersistentActor

**Comment by ktoso** [comment]
AFAIR we fixed this after releasing 2.4 will find the fix PR later.

**Comment by patriknw** [comment]
I don't think this is fixed. Snapshot docs also includes benchmarks: http://doc.akka.io/api/akka/snapshot/#akka.persistence.PersistPersistentActor

**Comment by ktoso** [comment]
Will look into it this cleanup-day.
