### ISSUE TITLE
Somewhat confused about maxRetries in SlotSelector

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18763]
Hi @sirthias @jrudolph,
I'm somewhat confused by the value `maxRetries` not being used in:

```
private class SlotSelector(slotCount: Int, maxRetries: Int, pipeliningLimit: Int, log: LoggingAdapter)
```

Omission or left-over from something?

I'm working around the areas of idleTimeouts and also trying to help @huntc with a problem they're experiencing.

**Comment by ktoso** [comment]
We do see it retrying though, so I'm digging through what/where handles these reconnections.

**Comment by ktoso** [comment]
It starts to make sense: That retry is on the Http level, and what Chris asked me about is on the TCP level so it's not that setting, but the TCP IO's stuff... digging more.

**Comment by sirthias** [comment]
This is indeed a left-over and can be removed (the parameter).
This is where the retry setting is really applied:
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala#L145

**Comment by ktoso** [comment]
Thanks for confirming! I'll clean it up then.
