### ISSUE TITLE
Transparent exponential back off supervisor

### ISSUE THREAD

**Issue by henrymai** [akka/akka#18766]
The existing back off supervisor (`akka.pattern.BackoffSupervisor`) requires the child to be stopped in order for the supervisor to restart the child. This seems inconsistent with the behavior of normal supervision, where the child will be automatically restarted upon an exception occurring (subject to the decider on the SupervisorStrategy).

This requires the child actor being supervised to be aware of this semantic, which means that it has to catch any exceptions that occur and cause itself to be terminated in order for it to be restarted.
This seems cumbersome and loses some of the niceties provided by normal supervision such as automatic logging of exceptions.

I ended up creating my own backoff supervisor in order to get the behavior mentioned above and I wanted to check in with you guys to see if this is useful:
https://github.com/henrymai/akka-transparent-exponential-backoff-supervisor

**Comment by patriknw** [comment]
This looks like a duplicate of https://github.com/akka/akka/issues/18487

**Comment by patriknw** [comment]
closing as duplicate, you are welcome to contribute with a pull request

**Comment by patriknw** [comment]
I'm opening this again, since it seems that it should not be aligned with existing BackoffSupervisor.

**Comment by henrymai** [comment]
https://github.com/akka/akka/pull/18776 has been merged. Closing this issue.
