### ISSUE TITLE
Cluster Sharding - GracefulShutdown malfunction

### ISSUE THREAD

**Issue by kpbochenek** [akka/akka#18762]
ShardRegion:
```
case GracefulShutdown ⇒
      log.debug("Starting graceful shutdown of region and all its shards")
      gracefulShutdownInProgress = true
      sendGracefulShutdownToCoordinator()
```
and
```
def sendGracefulShutdownToCoordinator(): Unit =
    if (gracefulShutdownInProgress)
      coordinator.foreach(_ ! GracefulShutdownReq(self))
```
On each Shard termination ShardRegion checks if there are no more shards alive and when there are not it shuts itself down.
But when there are no shards at all no trigger will be sent and ShardRegion will never stop.

condition that checks that is:
```
if (gracefulShutdownInProgress && shards.isEmpty && shardBuffers.isEmpty)
        context.stop(self) // all shards have been rebalanced, complete graceful shutdown
````

And I think it should also be checked on receiving GracefulShutdown.

**Comment by patriknw** [comment]
Good catch! Would you like to [contribute](https://github.com/akka/akka/blob/master/CONTRIBUTING.md) by creating a pull request?

**Comment by kpbochenek** [comment]
I will have to check CLA but besides that I can do that

**Comment by kpbochenek** [comment]
#18805 <-PR
