### ISSUE TITLE
Update to a regular MiMa release

### ISSUE THREAD

**Issue by 2m** [akka/akka#18765]
After https://github.com/akka/akka/pull/17761 master uses MiMa prerelease version. Update when new MiMa version is cut.

**Comment by ktoso** [comment]
Ok! :)

**Comment by 2m** [comment]
Also remove issue filter from [here](https://github.com/akka/akka/blob/ac8235407778ce8366e6323e89519f3a294e2902/project/MiMa.scala#L569) which was a problem of MiMa reporter which now has been fixed.

**Comment by ktoso** [comment]
Great, thanks!
