### ISSUE TITLE
Quote Content-Disposition filename param in http client 

### ISSUE THREAD

**Issue by relgames** [akka/akka#18788]
I tried the sample from https://github.com/akka/akka/issues/17665 (with some modifications):
```
  def createFileUploadEntity(len: Long, source: Source[ByteString, Any], ec: ExecutionContext): Future[RequestEntity] = {
    implicit val executionContext = ec

    val formData =
      Multipart.FormData(
        Source.single(
          Multipart.FormData.BodyPart(
            "file",
            HttpEntity(MediaTypes.`image/jpeg`, len, source),
            Map("filename" -> "avatar.jpg"))))
    Marshal(formData).to[RequestEntity]
  }
```    

Turned out it generates following HTTP request:
```
Content-Type: image/jpeg
Content-Disposition: form-data; filename=avatar.jpg; name=file
```

According to <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html">RFC 2616</a>, part 19.5.1 Content-Disposition: 
disposition-parm = filename-parm | disp-extension-parm
filename-parm = "filename" "=" quoted-string
disp-extension-parm = token "=" ( token | quoted-string )

So filename must be quoted. This causes issues with some HTTP servers not accepting such requests.
Workaround is to add some char and force quoting, but it is not really correct.

**Comment by ktoso** [comment]
Thanks for the research on this! We'll look into it.

// cc @sirthias @jrudolph

**Comment by sirthias** [comment]
RFC2616 is obsolete now. I think the latest RFC governing this particular header is [RFC 6266](http://tools.ietf.org/html/rfc6266) whose [section 4.1](http://tools.ietf.org/html/rfc6266#section-4.1) says this:

> content-disposition = "Content-Disposition" ":" disposition-type *( ";" disposition-parm )
> 
> disposition-type    = "inline" | "attachment" | disp-ext-type
>                  ; case-insensitive
> disp-ext-type       = token
> 
> disposition-parm    = filename-parm | disp-ext-parm
> 
> filename-parm       = "filename" "=" value
>                  | "filename*" "=" ext-value
> 
> disp-ext-parm       = token "=" value
>                  | ext-token "=" ext-value
> ext-token           = <the characters in token, followed by "*">
> 
> Defined in [RFC2616]:
> 
> token         = <token, defined in [RFC2616], Section 2.2>
> quoted-string = <quoted-string, defined in [RFC2616], Section 2.2>
> value         = <value, defined in [RFC2616], Section 3.6>
>            ; token | quoted-string

So it appears to me as if plain tokens are ok for the filename parameter. Only if the filename parameter value contains non-token chars are quotes required.
This is in fact how the current rendering behaves.

Do you have some more information about what servers exactly you experienced trouble with?

**Comment by relgames** [comment]
The issue appears with BaasBox. Thanks for pointing to the correct RFC, I will open an issue in their tracker. Will have to use a workaround for now...

**Comment by sirthias** [comment]
Cool! Thanks!

**Comment by ktoso** [comment]
Closing as we seem to do the right thing

**Comment by relgames** [comment]
Returning back to this, BaasBox is still having issues parsing Akka POST request.
Browsers, Apache Http Client - all send quotes:
```
Content-Disposition: form-data; name="file"; filename="photo.jpg"
```

Is there a quick way to force Akka to use quotes? I have to use Apache Mime lib to manually create ByteString for multipart POST, it is really annoying.

**Comment by ktoso** [comment]
@relgames, there is an open ticket as you can see: https://github.com/akka/akka-http/issues/386

The fastest way is to pull akka, apply the change, and we'll merge and release :-)
Please pull/PR http://github.com/akka/akka-http
