### ISSUE TITLE
Allow ValidationRejection to customize status code

### ISSUE THREAD

**Issue by analytically** [akka/akka#18780]
It would be handy if validate and ValidationRejection would support a custom status code.

**Comment by ktoso** [comment]
That's what rejection handling is for:

```scala
implicit val rejectionsHandler = RejectionHandler.newBuilder().handle({
    case ValidationRejection(msg, cause) =>
    complete((StatusCodes.NotFound, "Oh man, what you are looking for is long gone."))  // anything you want here
  }).result()
```

**Comment by ktoso** [comment]
To learn more about rejections see here: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/rejections.html

Unless I'm missing something in your requirement, it's certainly possible to do what you want already :)

**Comment by analytically** [comment]
That doesn't make it easy to reuse ValidationException. Then you can't vary the status code per rejection.

**Comment by analytically** [comment]
@sirthias?

**Comment by ktoso** [comment]
I don't see what you mean by "reuse ValidationException", an example would help here..
I guess you mean that for different `validate()` you want to result in different response codes if it fails?
I guess that'd be doable by sealing with appropriate RejectionHandlers, or extending the `ValidationRejection` to carry a "proposed response code", but I'm not sure that's a good idea... Feedback from @sirthias or @jrudolph definitely welcome

**Comment by analytically** [comment]
Other rejections also carry HTTP specific data, like headers, challenges, parameter names. ValidationRejection is the generic one, but Akka sets it's status code to 400, which is not very flexible if you want to reuse ValidationException in multiple cases (eg. 400 if bad request, 429 if rate limited).

**Comment by analytically** [comment]
My use case (let's not go into the why): if parameter uid or user present, OR valid basic auth, pass, otherwise reject with 403 Forbidden.

**Comment by analytically** [comment]
```
(optionalHeaderValueByName("uid") & optionalHeaderValueByName("email")) { (pi, uid, email) =>
  authenticateBasicPF(realm, authenticator).optional { user =>
    pi.orElse(uid).orElse(email).orElse(user) match {
      case Some(username) =>
        ...
      case None => reject(ValidationRejection("forbidden??"))
    }
  }
}
```

**Comment by sirthias** [comment]
If you have special requirements for validation and the resulting renderings, would it be an option to introduce your own rejection type and custom handling for it?

**Comment by analytically** [comment]
True, that's a possibility. But using ValidationException for this would be really handy.

**Comment by sirthias** [comment]
My concern is that, if we further generalize `ValidationRejection`, then it won't really add much value anymore and will simply be the "general rejection" that can mean anything.
In your case, when you want to return a 429 response, one could argue that `ValidationRejection` really is the wrong rejection type and you actually want a `ExcessiveRateRejection` or sth like that.

**Comment by analytically** [comment]
Ok, a little less DRY but agreed.
