### ISSUE TITLE
Make support for testing stages available in the testkit

### ISSUE THREAD

**Issue by sattvik** [akka/akka#18799]
Currently, there is no relatively good way to test the functionality of an implementation of an `AsyncStage`.  The best I have been able to do use a `Flow.transform` between a test source and a test sink.  However, this is somewhat less than ideal as prefetching/buffers before and after stage make direct testing more difficult.

It looks like there is an [InterpreterSpecKit](https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-1.0/akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSpecKit.scala) that approaches the functionality that I would like.

**Comment by rkuhn** [comment]
AsyncStage is dead, long live GraphStage!

**Comment by rkuhn** [comment]
… and that can well be completely tested using TestSource.probe and TestSink.probe.

**Comment by sattvik** [comment]
Just as a note, even with test probes,  the fact that there are still automatic buffers being added to the test flow makes testing of buffering and the like within the stage trickier.
