### ISSUE TITLE
Expose LoggingAdapter in GraphStage and Stage

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#18793]
as for add logging for ``Buffer`` ,it shows up very cumbersome for doing that.
```
  def isActorMaterializer(materializer: Materializer):Boolean = materializer match {
    case _:ActorMaterializer => true
    case _ => false
  }

  private val log:LoggingAdapter = if (ActorMaterializer.isActorMaterializer(context.materializer)){
    val system = context.materializer.asInstanceOf[ActorMaterializer].system
    Logging(system,context)
  } else null
```
and then ```if(log ne null) log.debug(...)```.
So how about add logging support for stage?

refs https://github.com/akka/akka/pull/18791 part is not complete, need ``Buffer`` to do.

**Comment by drewhk** [comment]
Basically everything is there, it only needs to be exposed properly to user API.

**Comment by patriknw** [comment]
I agree, this is needed. The problem is what to do if it's not an ActorMaterializer? 
Alternatives:
1) Returning an `Option[LoggingAdapter]` could work
2) throw exception
3) require that the materializer implements something like `getLoggingAdapter`

**Comment by ktoso** [comment]
Option of adapter is somewhat heavy, if someone does not support they can always to a trivial println or logback adapter ... or throw.

We can consult this one with the GearPump guys as it's the current other materializer, but they'd simply provide ActorLogging anyway I think since they have Akka?

**Comment by patriknw** [comment]
For inspiration: https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/StageLogging.scala

**Comment by ktoso** [comment]
Remember to fix copied class in Akka HTTP once this is resolved https://github.com/akka/akka-http/pull/398/files#diff-50f5a82f9011ae81f34f9fa8f4a3ddb6R14

**Comment by patriknw** [comment]
There is one in akka-stream-kafka also ;-)
