### ISSUE TITLE
Add fuzzing mode to the interpreter

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18798]
The solution is to expose a configuration option `akka.stream.interpreter.fuzzing-mode` that defaults to off, and when it is on
 - the interpreter should ignore the given eventLimit parameter and always use *1* instead
 - on dequeue() internally, it should pick a random slot for the to be dequeued connection id, put it in the random slot, and dequeue the previous connection id from that random slot instead.
 - the ActorGraphInterpreter should sometimes suspend itself even when there is an external event to be processed

These three conditions together will ensure a great depth of fuzzing of both internal and external events. I think this will be safe, since order dependent events like complete-after-push are encoded in the state bitfield instead in the FIFO queue of connection IDs, but I might be wrong about this.

Some tests will need this setting off:
 - low level interpreter tests, mostly in `akka.stream.impl.fusing` which depend on ordering
 - benchmarks

**Comment by drewhk** [comment]
at the same time, add a `event-limit-max` parameter and apply it in `ActorGraphInterpreter`

**Comment by drewhk** [comment]
Preliminary results: only these tests failed for me:

     akka.stream.scaladsl.FlowConflateSpec
     akka.stream.scaladsl.FlowZipSpec
     akka.stream.scaladsl.GraphZipSpec
     akka.stream.scaladsl.FlowIdleInjectSpec

**Comment by 2m** [comment]
LGTM
