### ISSUE TITLE
Akka-Http-Client request failing after `Outgoing request stream error` (akka.stream.AbruptTerminationException)

### ISSUE THREAD

**Issue by georgeyanev** [akka/akka#18797]
I have created a test case with a FSM actor using akka-http-client to consume some http service.
There are two tests each of which creates a new instance of the FSM actor and executes a http request. Both tests are using a single actor system.
Tests finish successfully when run one by one separately (involving actor-system shutdown and restart for each test) but the second test (in execution order) fails when run both one after another in the same actor system.
When running each of the tests, although it finishes correctly, an error `Outgoing request stream error (akka.stream.AbruptTerminationException)` is generated. And I think that error is the reason the second test to fail. 
I'm attaching a small maven project demonstrating the issue. You can find it here: 
https://github.com/georgeyanev/akka-http-client-test

Can you provide some sort of workaround? I could not use akka-http otherwise.

Oracle java1.8.0_25, maven 3.2.1, akka 2.3.14, Ubuntu 14.04

**Comment by ktoso** [comment]
Thanks for preparing a reproducer, I'll give it a look.

**Comment by georgeyanev** [comment]
Hi Konrad. Is there any progress here? 
In fact I can not make a second http request to the same host:port from one actor system.

**Comment by ktoso** [comment]
Lack of updates is due to lack of work on this specific ticket – this week is bit busy with other things... 
I'll get to it eventually, but was not able to do so yet.

**Comment by johanandren** [comment]
Tried to see if it is the same on the Scala side of the client, nope, works fine. (minimal non-reproducer) https://gist.github.com/johanandren/482f4244e72848d0ee88

**Comment by johanandren** [comment]
NVM my previous comment, misunderstood the problem.

**Comment by johanandren** [comment]
The test contains a race condition though, both test cases write to the test class field fsmActor which should mean that it is probable that both tests will actually send their messages to the same instance of your actor.

**Comment by johanandren** [comment]
In your code you created a separate materializer every time an instance of the actor was started, and when it was shut down you shut the materializer down causing the error. Now, I'm not sure exactly why, but I am guessing something in the cached connection pool is created with that materializer that you shut down and can no longer be used. @ktoso can probably explain it with higher certainty.

Externalizing the materializer instead of creating one in each actor (and shutting that one down on actor stop) fixes the problem. See: https://github.com/johanandren/akka-http-client-test/commit/713aa2700423f5871f491622e2e4b318ecdde195

**Comment by georgeyanev** [comment]
So I can use the same instance of the materializer even with multiple actors making http requests?
Is this safe?

**Comment by ktoso** [comment]
> So I can use the same instance of the materializer even with multiple actors making http requests?
Is this safe?

Yes. I did not yet read into the sample, but if it's as Johan found that you shut down the materializer, then yes it will shut down the underlying connection pools and an error might be printed (most likely will) then.

**Comment by drewhk** [comment]
@georgeyanev materializers are completely thread-safe, and relatively heavy-weight (not as much as an ActorSystem though). If there is no reason to use more Materializers (isolation of lifecycles, or ability to shut down a set of streams separately) then you are safe to use one.

**Comment by georgeyanev** [comment]
OK, thanks for the info. I will give it a try. 
In the example provided I shutdown explicitly the materializer when the http request is complete. However if I don't do it the error still persists. Seems that the materializer is shutdown implicitly on actor stop as noted by johanandren.

**Comment by johanandren** [comment]
I think that is because you created it using the actor context, which is bound to the actor life cycle.

**Comment by georgeyanev** [comment]
A made some tests and indeed it works fine with global materializer.
@johanandren, @ktoso, @drewhk, thank you for bringing attention to this issue.
Nevertheless is there something to be done further with the materializer shutdown process, or should I close this issue?

**Comment by rkuhn** [comment]
No, materializer shutdown seems to work as designed AFAICS, but thanks for the discussion!
