### ISSUE TITLE
Is TCP internals exposing Processor indicating missing API?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18801]
Something @viktorklang noticed while reviewing https://github.com/akka/akka/pull/18770#discussion-diff-43173541R163

Maybe it's "OK since internals", but keeping ticket for discussion

**Comment by viktorklang** [comment]
Thanks for opening this, Konrad.

**Comment by drewhk** [comment]
What does this ticket mean?

**Comment by ktoso** [comment]
This ticket is about this line https://github.com/akka/akka/pull/18770#discussion-diff-43173541R163 i.e. if we're missing something in our APIs or not.

**Comment by rkuhn** [comment]
TCP stages are now all fusable.

**Comment by drewhk** [comment]
@ktoso that time TCP still used Pump, etc. This is no longer relevant.

**Comment by ktoso** [comment]
Ah I see, thanks
