### ISSUE TITLE
Docs: strange example for TestKit in Akka documentation

### ISSUE THREAD

**Issue by amorfis** [akka/akka#18804]
In docs about testing (http://doc.akka.io/docs/akka/snapshot/scala/testing.html#Asynchronous_Integration_Testing_with_TestKit), there is this example of code:

```scala
class MySpec(_system: ActorSystem) extends TestKit(_system) with ImplicitSender
  with WordSpecLike with Matchers with BeforeAndAfterAll {
 
  def this() = this(ActorSystem("MySpec"))
```
Why is there auxillary parameterless constructor? Couldn't it be simplified to this:

```scala
class MySpec() extends TestKit(ActorSystem("MySpec")) with ImplicitSender
  with WordSpecLike with Matchers with BeforeAndAfterAll {
```

Is there any reason for that auxillary constructor?

**Comment by rkuhn** [comment]
Hmm, I can’t see a good reason either; would you mind trying out and proposing a change?

**Comment by amorfis** [comment]
Do you mean pull request? I can change the tests in the code here on github, but I can't find the docs text. I think it's not here in the akka repository?

**Comment by 2beaucoup** [comment]
@amorfis it's here: https://github.com/akka/akka/blob/master/akka-docs/rst/scala/testing.rst#asynchronous-integration-testing-with-classtestkit
