### ISSUE TITLE
akka-stream AbstractStage#preStart is called after first elements pass through

### ISSUE THREAD

**Issue by l15k4** [akka/akka#18800]
Hey,

I have a FlowProvider that wraps flows and does some initialization/cleanup logic : 
```
fp.flow.transform(() => PrePostCallback(() => fp.beforeAll(), () => fp.afterAll()))
```

```
case class PrePostCallback[A](pre: () => Unit, post: () => Unit) extends PushStage[A, A] with LazyLogging {
  def callbackSafely(cb: () => Unit) = Try(cb()).recover {
    case NonFatal(ex) =>
      logger.error("PrePostCallback threw an exception", ex)
  }
  def onPush(elem: A, ctx: Context[A]): SyncDirective = ctx.push(elem)

  override def preStart(ctx: LifecycleContext) = callbackSafely(pre)
  override def postStop() = callbackSafely(post)

}
```

Basically each of my flows starts with this transform stage. `postStop` works as expected and never executes before the last element passes through the flow. But `preStart` doesn't. It executes after some elements are already pushed down the stream.

Is it a misuse on my part or is it actually a bug?

**Comment by drewhk** [comment]
Do you have a reproducer? This might be a bug, but I am not sure without context, there might be some threading issue here. In fact I find it quite unlikely that preStart is execued late, due to how it is called, but a reproducer would help to see if there is a bug of not.

**Comment by l15k4** [comment]
I guess you are right about the threading issue, it is probably a racing condition because I'm setting up global state by `preStart` which is "then" used by flow execution thread... 

Is it a difference between : 
```
flow.transform(() => PrePostCallback(() => fp.beforeAll(), () => fp.afterAll()))
```

and

```
    Flow[I]
      .transform(() => PrePostCallback(() => fp.beforeAll(), () => ()))
      .via(flow)
      .transform(() => PrePostCallback(() => (), () => fp.afterAll()))
```

?? It both seem to behave exactly the same...

**Comment by rkuhn** [comment]
I added a test to guard against this last week, so I’m pretty sure that what you are seeing is caused by the particulars of your setup.
