### ISSUE TITLE
Finalize Java Api for GraphStage

### ISSUE THREAD

**Issue by 2m** [akka/akka#18817]
Main problem as I can see so far is creating [In/Out handlers](https://github.com/akka/akka/blob/5f89029b7e60919bc9e5b325dbf379e4cdcc87e8/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L783-L826) from Java as they are now traits with default implementations.

What should be done:
  Remove InHandler's GraphStageLogic var
  Remove OutHandler's GraphStageLogic var
  Make the callback methods on InHandler and OutHandler take a GraphStageLogic parameter
  Make GraphStageLogic.{ EagerTerminateInput, IgnoreTerminateInput, ConditionalTerminateInput, TotallyIgnorantInput, EagerTerminateOutput, IgnoreTerminateOutput, ConditionalTerminateOutput } objects wherever possible and final when not intended for user inheritance.

**Comment by viktorklang** [comment]
@2m The fix sounds like it is to make them abstract classes (since they have vars etc I think that's the sanest solution anyway.

**Comment by drewhk** [comment]
Hm, that makes it impossible to have the same class extend both :( (one
more object header per PushPullStage)

**Comment by drewhk** [comment]
Strictly speaking, there is no reason for them to have default implementations other than convenience (the finish methods default to finishing the stage -- so the stage must be injected to the handlers, therefore the var). I.e. one option is to have the Java side suffer by always having to implement all callbacks ;)

**Comment by viktorklang** [comment]
May I ask why they are separate types at all?

**Comment by drewhk** [comment]
Because they encapsulate different set of callbacks. For an input port you have these events:
 - onPush()
 - onUpstreamFinish()
 - onUpstreamFailure()

and for an output port you have these events:
 - onPull()
 - onDownstreamFinish()

These interfaces collect these callbacks together. You can't use the same type for both ports (at least not without serious hackyness).

**Comment by viktorklang** [comment]
@drewhk have you considered putting the `GraphStageLogic` as a parameter to the callbacks instead of using the var?

**Comment by viktorklang** [comment]
Added the following to the description:

~~~txt
What should be done:
Remove InHandler's GraphStageLogic var
Remove OutHandler's GraphStageLogic var
Make the callback methods on InHandler and OutHandler take a GraphStageLogic parameter
Make GraphStageLogic.{ EagerTerminateInput, IgnoreTerminateInput, ConditionalTerminateInput, TotallyIgnorantInput, EagerTerminateOutput, IgnoreTerminateOutput, ConditionalTerminateOutput } objects wherever possible and final when not intended for user inheritance.
~~~

**Comment by rkuhn** [comment]
yep, exactly

**Comment by drewhk** [comment]
Taking the GraphStageLogic as a parameter is very boilerplatey, plus, it means that people need to cast it down to access any functionality on subclasses. Or, of course close over it *and* get it as a parameter, but that is not really optimal.

**Comment by rkuhn** [comment]
What should be done is:

* make remove the instance variable
* create abstract base classes for Java (AbstractInHandler, AbstractOutHandler, AbstractInOutHandler)
* implement default behavior for Scala using a ThreadLocal instead of passing the stage logic around everywhere

**Comment by drewhk** [comment]
So Java users always have to implement the closing calls?
