### ISSUE TITLE
Add case object format helper to SprayJsonSupport

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18811]
@agemooij has a useful helper for formatting case objects we could provide in `SprayJsonSupport`.
Should be documented in `/Users/ktoso/code/akka/akka-docs-dev/rst/scala/http/common/json-support.rst` as well

The relevant gitter discusion is :point_up: [October 29, 2015 9:45 AM](https://gitter.im/spray/spray?at=56324d10b1bb53dd7572674c)

**Comment by ktoso** [comment]
Now that i think about it, maybe this should be implemented in spray-json directly instead, i.e. "Support for unmarshalling strings into case objects".

WDYT @sirthias @jrudolph?
We got an actual request to help out with this, so would be nice to get it done.

**Comment by agemooij** [comment]
You're right, this should really be a spray-json PR instead of an akka-http one. @sirthias & @jrudolph do you agree?

FYI, the code I have is the following:

```scala
import spray.json._
import scala.reflect.ClassTag

/**
 * A custom version of the Spray DefaultJsonProtocol with an additional
 * formatter for ADT's of only case objects.
 */
trait CaseObjectSerializationSupport extends DefaultJsonProtocol {

  def caseObjectJsonFormat[T: ClassTag](objects: T*)(implicit tag: ClassTag[T]) = new RootJsonFormat[T] {
    /** A mapping from object names to the objects */
    private val mapping = objects.map(obj ⇒ key(obj) -> obj).toMap

    override def read(json: JsValue): T = (json match {
      case JsString(value) ⇒ mapping.get(value)
      case _               ⇒ None
    }).getOrElse(deserializationError(s"Unknown json value found when converting to $tag: $json"))

    /** The toString value of a case object is its name */
    override def write(value: T): JsValue = JsString(key(value))

    private def key(input: T): String = SimpleClassNameExtractor(input.getClass)
  }

}

object CaseObjectSerializationSupport extends CaseObjectSerializationSupport

object SimpleClassNameExtractor {
  def extractSimpleClassName(input: String) = input.split("\\.").last.split("\\$").last
  def apply[T](input: Class[T]): String = extractSimpleClassName(input.getName)
}
```

That class name extraction stuff is to get predictable clean simple class names for case objects. @ktoso referred to the `akka.event.Logging.simpleName` function but for a simple raw case object `Foo` that would produce `"$read$Foo$"`, which is not exactly pretty for use in JSON.

**Comment by patriknw** [comment]
sounds like this should be in spray json
cc @ktoso

**Comment by ktoso** [comment]
Yes, moved to https://github.com/spray/spray-json/issues/186
