### ISSUE TITLE
Logging.getLogger(UntypedActor) cannot be used in AbstractActor

### ISSUE THREAD

**Issue by thjaeckle** [akka/akka#18818]
I use Akka with Java and the `AbstractActor` base class for actors.

For obtaining a `DiagnosticLoggingAdapter` it is necessary to use `akka.event.Logging#getLogger` which takes an `UntypedActor`.
But that won't work when using the Java8 optimized `AbstractActor` as base class.

**Comment by patriknw** [comment]
good catch, thanks for reporting

**Comment by patriknw** [comment]
Until fixed you can use `akka.event.Logging#apply`.
By the way, pull requests are welcome.

**Comment by lolski** [comment]
Is this a priority? I can take care of it

**Comment by hepin1989** [comment]
@lolski there is an attach https://github.com/akka/akka/pull/18803

**Comment by ktoso** [comment]
@lolski it would be very nice if you could give it a shot, thanks!
@hepin1989 that's not quite the same issue; here we just want to change the getLogger signature.

**Comment by hepin1989** [comment]
@ktoso haha,I will delete it ,it's the wrong refs,sorry :(.

**Comment by lolski** [comment]
How about modifying `getLogger` to simply accept `Actor`? Is there any particular downside to that? 

The other solution is to add yet another overload: `getLogger(logSource: AbstractActor)` to go along with `getLogger(logSource: UntypedActor)`. I think this solution is more conservative, though I prefer the former

**Comment by patriknw** [comment]
Depends on if the signature change is binary backwards compatible. Please create a pull request and our tooling will tell you.

**Comment by johanandren** [comment]
Thank you for the contribution @lolski !
