### ISSUE TITLE
DNS extension shall not FromConfig a /system router

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18814]
Currently fails on 2.4.0; how can that be, are there no tests?

**Comment by patriknw** [comment]
This is probably the same as https://github.com/akka/akka/issues/18650
I looked at that briefly previously and the deployment config for `/IO-DNS/inet-address` in reference.conf is indeed used, so I never understood what it was all about.

An interesting feature we have is that deployment config is not used for system actors at the top level but for non top level it is used, as in this case.
