### ISSUE TITLE
context.watch(self) doesn't send Terminated message 

### ISSUE THREAD

**Issue by l15k4** [akka/akka#18822]
Hey,

as `ActorRef#isTerminated` is deprecated, is it possible to death-watch itself? It doesn't work for me, here is a repro https://gist.github.com/l15k4/bb80037343187d448e8c

Basically I want to stop scheduler via `Cancellable` on Actor termination, but `Terminated(_)` message never comes and scheduler keeps sending messages to dead-letter mailbox ..

Please close this issue if the death-watch  feature requires 2 actors.

**Comment by l15k4** [comment]
It doesn't work even if Parent Actor supervises Child actor. I suspect it is some sort of akka TestKit problem ....

**Comment by ktoso** [comment]
Watching `self` sounds like a rather weird thing to do – I mean, the once Terminated is sent, the actor is stopped, so it can't act upon the Terminated message.

I'd suggest handling the cancellable in `postStop` instead, sounds good?

**Comment by ktoso** [comment]
See here: http://doc.akka.io/docs/akka/snapshot/scala/actors.html#Stop_Hook

**Comment by l15k4** [comment]
Yeah even if I do it by Stop Hook it is still leaking dead letters from the async callbacks :
https://gist.github.com/l15k4/bb80037343187d448e8c#file-akkastreamcron-scala-L42

I don't like using akka base libraries that are leaking dead letters so I'm trying not to release such libraries myself... Which is kind of hard now without the deprecated `isTerminated` https://github.com/akka/akka/issues/13922 ... 

I could check the reference by `isTerminated` in the async callback to not send another message, but without  `isTerminated` it is really hard...

**Comment by ktoso** [comment]
If you want to avoid causing `deadLetters` by this message, you can mark it as `with DeadLetterSuppression`, as explained here: http://doc.akka.io/docs/akka/snapshot/scala/event-bus.html#Dead_Letters

The messages will not cause dead letters then :)

**Comment by l15k4** [comment]
Cool, I didn't know about `DeadLetterSuppression`, thanks !
