### ISSUE TITLE
SharedLevelDbJournal - simplify store initialization

### ISSUE THREAD

**Issue by talp-traiana** [akka/akka#18839]
In order to use the SharedLevelDbJournal, the setStore method has to be called. This has to be done after the actor system creation but before any PersistentActors are created. However, the documentation isn't very clear about this, and in any case it's just boilerplate. As such, I think this should be done automatically during the plugin initialization (based on config).

(see https://groups.google.com/forum/#!topic/akka-user/bJwhzGkwMI4 )

**Comment by patriknw** [comment]
@talp-traiana I actually have the need to use a journal proxy for another journal than leveldb, so I also started thinking about this. AsyncWriteProxy is complicating things a lot, as far as I can see. I have instead tried to implement a journal proxy, that forwards at the journal message protocol level. A lot easier, and would work with any journal.

I can add the automatic discovery of the target journal to this utility also.

**Comment by talp-traiana** [comment]
@patriknw Yeah, that sounds like it could simplify things quite a bit there. I've been going over how the LeveldbReadJournal works and whether it should work with a SharedLeveldbJournal, and the AsyncWriteProxy is making it hard to figure out...

Since I started working on this yesterday, I just want to make sure - there's no point in me continuing to work on this, right? Is there anything else I can help with?

**Comment by patriknw** [comment]
Contributions are very much welcome, and we have plenty of issues that would be great if you can help out with. If you are interested in persistence, take a look at this list: https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.4.x+label%3At%3Apersistence

For the journal proxy, I think I'm rather close to a working solution. I'll create a pull request in a few days, and it would be great if you can review it to see that it meets your expectations. I'll ping you.
