### ISSUE TITLE
Http: replace bypass with graph stage

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18830]
Note to remember to replace bypasses in Http with a GraphStage, should make it faster *and* simpler to reason about.

**Comment by drewhk** [comment]
@ktoso they have been replaced right? I mean there are no FlexiXXX anymore.

**Comment by ktoso** [comment]
Not quite, there still is this quite elaborate dance concerning these:

```
val bypassFanout = b.add(Broadcast[RequestOutput](2).named("bypassFanout"))
val bypassMerge = b.add(new BypassMerge(settings, log))
val bypassOneHundredContinueInput = bypassMerge.in1
val bypassApplicationInput = bypassMerge.in2
```

We chatted with @sirthias and think it could be replaced with one graph stage instead, which should make things a bit simpler there.

My notes (to self, and FYI) why the bypass is needed:

- when responding to a HEAD request response may not contain response body, and similar situations like that
- 100-continue, since we generate 2 responses, 1st to accept the continue,
- short circuiting when parsing etc fails and we gen a response without invoking user code

**Comment by drewhk** [comment]
You mean replacing larger constructs with a single GraphStage? Ok that might make sense if it simplify things. Where it does not, don't bother though, the goal is to fuse them anyway.

**Comment by ktoso** [comment]
Yeah, it's more for simplifying the logic if "oh, it was a HEAD request, so when writing the response I have to ...". This logic can then be contained in one stage, instead of being spread all over the place using the bypass fanout/merge

**Comment by jrudolph** [comment]
One of the main advantages would be that you could prevent the race conditions between bypass and user-handler more easily. Fusing alone may make it more deterministic but it cannot probably give you any additional hard guarantees. With graph stages you can maintain one shared state before and after the user-handler.

**Comment by sirthias** [comment]
Just as a heads up:
I'm currently in the process of doing this refactoring for the server side, as it makes the solution to #16898 much easier. Doesn't appear to be too hard so far.

**Comment by ktoso** [comment]
Cool, thanks for the heads up!
