### ISSUE TITLE
Investigate potential bug in UTF-8 support for header values

### ISSUE THREAD

**Issue by sirthias** [akka/akka#18831]
This is a follow-up to #18389 and https://github.com/spray/spray-json/issues/162.

The support for UTF8-encoded header values that we just put in (https://github.com/akka/akka/pull/18654) is based on the logic in spray-json and thus might suffer from the same problem as https://github.com/spray/spray-json/issues/162.
This ticket is for verifying and potentially fixing this issue.

**Comment by sirthias** [comment]
It turns out that #18389 was caused by spray/spray-json#148, which was already fixed before we transplanted the code from spray-json to the HTTP header parsing.
So all is well.

**Comment by ktoso** [comment]
Excellent, thanks for checking @sirthias !
