### ISSUE TITLE
GraphStage does not call AsyncCallback method after got onComplete

### ISSUE THREAD

**Issue by agolubev** [akka/akka#18835]
this is use case from #17967 ticket.
See test case below:
```scala
  class TestSinkStage() extends SinkStage[Int, () ⇒ Future[Int]]("TestSink") {

    override def createLogicAndMaterializedValue(inheritedAttributes: Attributes): (GraphStageLogic, () ⇒ Future[Int]) = {
      val buffer = new util.LinkedList[Int]()
      val logic = new GraphStageLogic(shape) {
        private val callback: AsyncCallback[Promise[Int]] = getAsyncCallback((p: Promise[Int]) ⇒ {
          p.success(buffer.pop())
          if (buffer.isEmpty) completeStage()
        })

        def pull(): Future[Int] = {
          val p = Promise[Int]()
          callback.invoke(p)
          p.future
        }

        override def preStart() = pull(in)

        setHandler(in, new InHandler {
          override def onPush(): Unit = {
            buffer.add(grab(in))
            if (buffer.size() < 3) pull(in)
          }

          override def onUpstreamFinish(): Unit = if (buffer.isEmpty()) completeStage()
        })
      }
      (logic, logic.pull)
    }
  }

  "GraphStage asyncCallback" must {
    "must work after onComplete received" in {
      val (probe, pull) = TestSource.probe[Int]
        .toMat(Sink.fromGraph(new TestSinkStage()))(Keep.both)
        .run()
      probe.sendNext(1)
      probe.sendNext(2)
      probe.sendComplete() //if comment out this line - test passes
      // test fails here as AsyncCallback never executes after received onComplete
      Await.result(pull(), 300.millis) shouldBe (1)
      Await.result(pull(), 300.millis) shouldBe (2)
    }
  }
```

**Comment by rkuhn** [comment]
There is nothing we can do on the library side here: only your stage knows that it is not yet finished, but you call `completeStage()` anyway (in `onUpstreamFinish`).

**Comment by drewhk** [comment]
Well, a GraphStage will receive the callbacks until all of its ports are closed when it is implicitly shut down. I was tempted to add an overridable parameter that allows keeping alive a stage even if there are no open ports, but that felt quite risky (easy to leak actors and stages).

**Comment by rkuhn** [comment]
Also: closing all ports means that nothing can be done anymore afterwards—the incoming async notification cannot have an observable effect within the stream. I thought about this as well while working on GraphStageLogic and this was my conclusion.

**Comment by drewhk** [comment]
yes, the ActorInterpreter should ignore async events for a stopped Stage (if that is what you meant).

**Comment by drewhk** [comment]
I guess this can be closed then?

**Comment by agolubev** [comment]
>There is nothing we can do on the library side here: only your stage knows that it is not yet finished, but you call completeStage() anyway (in onUpstreamFinish).

The point here is that stage got onComplete but we did not call completeStage() as have something in the buffer.

**Comment by agolubev** [comment]
We have two contexts: external (pull()) and internal (inside callback).
With having asyncCallback stop working suddenly (onComplete) and lack of synchronization we can not be sure that ```callback.invoke(p)``` ever will be executed

**Comment by agolubev** [comment]
Now checking if getting onComplete closing ```in``` port (as it's sink)

**Comment by drewhk** [comment]
I see. @rkuhn I think we need to introduce a flag that allows a stage to keep running after all external ports are closed. This is a Sink, so this is necessary (btw, now I remember that I wanted this feature for TCP anyway).

**Comment by agolubev** [comment]
Yes, this is also the case for  #17338  So common problem for IO

**Comment by agolubev** [comment]
For OutputStreamSource it also make sense as need to interact with external context. I'll doublecheck if implementation is using asyncCalls (not blockingQueues). So maybe this case is also valid or Source

**Comment by agolubev** [comment]
Ok, OutputStreamSource uses AtomicReference for status. So OutputStreamSource will have no issue

**Comment by drewhk** [comment]
This is not as simple to fix as I assumed. I guess we need to postpone this.

**Comment by agolubev** [comment]
Hm, than perhaps this PR needs to be reverted #18707 as it's not fully functioning

**Comment by drewhk** [comment]
There are more serious problems currently anyway, as this https://github.com/akka/akka/issues/18844 is serious.

**Comment by agolubev** [comment]
Ok, got it.

**Comment by agolubev** [comment]
Just checked -  #18707 is Ok for not having this fixed
