### ISSUE TITLE
FlowShape should get of() method to make it nicer for Java use

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18840]
Most of our Java API has `of(...)` methods etc, to avoid having to write `new Thing<>(...)`, we should provide the same for built-in Shapes.

Discussed here: https://github.com/akka/akka/pull/18834/files#r43752464

**Comment by drewhk** [comment]
Also SinkShape, SoucreShape, etx

**Comment by 2beaucoup** [comment]
`akka.japi.Pair.of(...)` would've been nice... :(

In http there are a lot of `create(...)`s. Maybe we should switch them, too.

**Comment by ktoso** [comment]
hm `akka.japi.Pair` has `create()`, I guess my `of()` favouritism on that word was overruled at some point ;)

**Comment by 2beaucoup** [comment]
And that's shame! ;)
