### ISSUE TITLE
Persistence documentation needs some english language corrections 

### ISSUE THREAD

**Issue by okthatsneat** [akka/akka#18849]
I've stumbled over a few things like duplicated words, missing characters, missing words, and grammatical mistakes. Instead of bitching about it, I'll do something about it.

**Comment by ktoso** [comment]
> I'll do something about it.

Awesome, thanks! Looking forward to the PR :-)

**Comment by okthatsneat** [comment]
I've noticed a fair amount of duplication between the java and scala docs for persistence, apparently some copy & paste has been happening here in the past ( duplicated mistakes ). Who can point me in the right direction on how to remove this duplication and DRY things up with the documentation framework you're using?

**Comment by ktoso** [comment]
We're not de-duplicating content between java/scala parts of the documentation – yes, it is `copy & adapt-to-java-style-and-wording & paste`.

**Comment by okthatsneat** [comment]
@ktoso got it. I'd like to set a pull request for the scala part, but am not allowed to push the feature branch yet ```ERROR: Permission to akka/akka.git denied to okthatsneat.``` I've confirmed this is a repo specific error by successfully pushing to one of my own projects. Please advise :)

**Comment by ktoso** [comment]
> I've confirmed this is a repo specific error by successfully pushing to one of my own projects.

That's how PullRequests work :-) All is fine. You should fork the akka repo (such that it's `okthatsneat/akka`), push your changes on a branch there, and then you can submit a PR from that branch into the `akka/akka` repo. I use that workflow as well, even though I have write access to akka/akka btw, makes things easier to track IMO :) (it shows up as [ktoso  wants to merge 2 commits into akka:release-2.3-dev from ktoso:mwip-more-idleTimeout-client-tests-ktoso](https://github.com/akka/akka/pull/18854))

**Comment by okthatsneat** [comment]
Cool, on it. Do you think this falls under noob problem, or should this be mentioned in the contribution guide?

**Comment by ktoso** [comment]
If you read [CONTRIBUTING.md](https://github.com/akka/akka/blob/master/CONTRIBUTING.md) and found it confusing I think we should add it explicitly, thanks! 
I'll add some words.

**Comment by okthatsneat** [comment]
I've read it, which doesn't mean I didn't miss that part. Here's the PR: https://github.com/akka/akka/pull/18855

**Comment by ktoso** [comment]
I'll try to give the guide a rewording, thanks for the feedback! :)
And thanks for the PR! Will look at it soon

**Comment by okthatsneat** [comment]
as the PR is merged, should this issue be closed? @ktoso

**Comment by ktoso** [comment]
Indeed, thanks for noticing (and the PR)! :-)
