### ISSUE TITLE
potential double-replay bug when PersistentActor is restarted during recovery

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18850]
see akkadotnet/akka.net#1403

**Comment by ktoso** [comment]
@Horusiath / @rkuhn this sounds like 2.3 behaviour; in 2.4 we _unconditionally_ `context.stop(self)` the actor if recovery fails; so there is no restart in that sense.

Relevant snippet:
```
Eventsourced.super.aroundReceive(recoveryBehavior, p)
        } catch {
          case NonFatal(t) ⇒
            try onRecoveryFailure(t, Some(p.payload)) finally context.stop(self)
```

// FYI @patriknw

**Comment by patriknw** [comment]
@ktoso You are right, it's not a bug in 2.4.
