### ISSUE TITLE
TestKitBase java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by WayneKeith** [akka/akka#18859]
I'm writing a test with TestKitBase like:

    class Test extends TestKitBase with Specification {
      override implicit val system = ActorSystem("test")
      ...
    }

When run, it will throw `java.lang.NullPointerException: null`

The problem is due to the code in TestKitBase:

     trait TestKitBase {

      import TestActor.{ Message, RealMessage, NullMessage }

      implicit val system: ActorSystem
      val testKitSettings = TestKitExtension(system)

The last line depends on the value of system. However, when initiating, the system is null.

Wish this could be fixed.

**Comment by WayneKeith** [comment]
I see that in [akka document for testing](http://doc.akka.io/docs/akka/2.4.0/scala/testing.html#Different_Testing_Frameworks)
I have to set system as `lazy val`.
Sorry for open issue easily.

**Comment by ktoso** [comment]
Not a problem, thanks for reading up on the docs :-)
Yes, `lazy val` is the way to go there.

Happy hakking!
