### ISSUE TITLE
Cluster JMX only supports one MBean, multiple clusters per node not supported

### ISSUE THREAD

**Issue by snarra40** [akka/akka#18872]
We have 3 Akka clusters running on one each node (JVM) on separate ports. Enabling JMX shows only the cluster status of the last cluster out of the 3. Looking at the source code it seems like the assumption is that only one cluster would be running on a single JVM. 
This is in production and we would like to down nodes when they are stuck and not able to rejoin using command line with JMX. 
It seems like changing the name of MBean to be based on actorsystem name would allow multiple MBeans (one for each cluster) to be created.

**Comment by drewhk** [comment]
Makes sense to me. Thanks for the suggestion @snarra40.

**Comment by patriknw** [comment]
I agree, should probably also include the port

**Comment by richard-imaoka** [comment]
Lemme work on this.

**Comment by patriknw** [comment]
Excellent, thanks
