### ISSUE TITLE
Akka HTTP and Streams should depend on Akka 2.4

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#18883]
Currently they depend on 2.3.12

**Comment by hepin1989** [comment]
@hseeberger I think it would once it release akka-stream 2.0 final and join the master.

**Comment by drewhk** [comment]
No, it should depend on 2.3.14, since 2.4 is binary compatible with 2.3 but not the other way around. I.e. the current build is compatible with 2.3.x and 2.4.x. As @hepin1989 mentioned we will eventually fork off and the man streams package will be simply part of the 2.4 series.

**Comment by hseeberger** [comment]
Got it, thanks.
