### ISSUE TITLE
Make ReceiveBuilder a real mutable builder

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18894]
Currently, it encourages a fluent api, that just becomes an ugly long call train and it is not intuitive that it can be split up to several statements. `UnitPFBuilder` is mutable, so `ReceiveBuilder` is only playing the role of bootstrapping the first `match`.

I would prefer (in addition to current api):
```
    UnitPFBuilder<Object> b = ReceiveBuilder.create();

    b.match(SomeMessage.class, ...);

    b.match(SomeOtherMessage.class, ...);

    receive(b.build());
```

i.e. small sugar for `new UnitPFBuilder<Object>()`

I would actually also prefer to have an abstract method that subclass must implement to return the initial behavior, instead of calling `receive` from constructor. It's impossible to know that `receive` should be used without looking in the documentation. Unfortunately this would be a breaking change.

**Comment by wojtasskorcz** [comment]
Is it still a thing? If so, I'd like to take it. Seems like a good issue for a first contribution.

**Comment by patriknw** [comment]
That would be great, thanks @wojtasskorcz
