### ISSUE TITLE
Polish Source.queue

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18890]
It's not quite complete yet, open questions:

- how to signal completion (there's only offer, we need some form of complete as well)
- how to signal error (there's only offer, we need some form of complete as well)
- offer returns a Future[Boolean] but it can return spurious true because early termination
-  it is very unclear how the user is supposed to encode their sender, should they do some async-tailcall-based thing?
- creating the SourceQueue should not take a timeout, and especially not one with an arbitrary timeout value (5 seconds in the current source tree), if anything the entity which calls `offer` needs to specify any timeouts. It can also be argued that this functionality does not need to be embedded within the SourceQueue at all.

**Comment by viktorklang** [comment]
Also, there is a bit of possible overlap with `Source.maybe`

**Comment by viktorklang** [comment]
Updated the Issue description to also consider timeouts

**Comment by agolubev** [comment]
starting this if no objections.
This should be migrated to graph stage.

**Comment by hepin1989** [comment]
+1,we are migrating to GraphStage anyway.

**Comment by drewhk** [comment]
@agolubev go ahead!
