### ISSUE TITLE
add Attributes.withMaterializer(…)

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18900]
In order to hook in other materializers it makes sense to mark out partial graphs (modules) such that the ActorMaterializer will delegate the materialization process to them. This should use no magic, the concrete materializer instance must be part of the attribute.

**Comment by drewhk** [comment]
One difficulty would be the interaction with fusing here. I guess this attribute should imply (subclass?) an AlwaysAsync attribute.

**Comment by viktorklang** [comment]
TBH I wonder if this is the appropriate approach for this.
What are the alternative solutions?

**Comment by patriknw** [comment]
Perhaps such things should be separated via reactive streams Publisher/Subscriber? It's like integration between two diffent libraries.

**Comment by viktorklang** [comment]
@patriknw Or perhaps by having a Materializer which wraps other Materializers and delegates different subgraphs to them.

**Comment by kkasravi** [comment]
@viktorklang The motivation is where partial graphs need to be materialized remotely. There are no doubt possible alternatives, however this has a certain elegance where the blueprint or 'plan' (runnable graph) deployment can be delegated to materializers - each one handling a partial graph. Effectively partial graphs have matching materializers and both are composable. @drewhk The approach is to currently subclass Materializer, and it would imply async. @rkuhn We would be happy to take a pass at Attributes.withMaterializer along with a short design - perhaps added here or within a PR. Remote materialization of a partial graph may imply certain assumptions in order to fuse like code provisioning if stages are customized, etc. I think some of this may jive with current simplification being done within 2.0-M1+ ...

**Comment by viktorklang** [comment]
@kkasravi Your description looks like a perfect start at a requirements description. A concern I have with `withMaterializer` is that it complects the description of the graph with the materialization of the graph. It also makes lifecycle management of the Materializers virtually impossible. How about we focus on the objective rather than a specific/proposed solution, and rename the ticket accordingly and the description with requirements?

**Comment by kkasravi** [comment]
+1 @viktorklang - the two (graph description and how it is materialized and where) should be treated separately - addding `withMaterializer` on Attributes would mean that the graph is now including deployment details orthogonal to its description. @rkuhn Perhaps we can rename to something like 'Add support/design for partial graph materializers'? I imagine this would be an umbrella task... for example #18901 would likely be a sub task. @viktorklang  I agree there are lots of issues related to Materializer and MaterializerContext lifecycle management that should be delineated within this task. The initial approach was to indicate if a partial graph were remote or local - slicing up the runnable graph in this way. This could be considered a materialization detail as well unless one were to consider `Attributes.withLocation(Remote|Local)` as being reasonable. To some degree hints need to be provided within the graph that influence materialization as noted by @drewhk (async or sync). Note that requiring a materializer to be defined implicitly suggests some awareness on part of the user of materialization context - although @patriknw's suggestion is applicable (delegation to alternative materializers created within the scope of the wrapping materializer. This way the type of materializer is offloaded from the user and determined by hints within the graph attributes).

**Comment by rkuhn** [comment]
@viktorklang The materializer lifecycle is a very good point that I overlooked. The objective is to have a Graph contain enough information for collaborative materialization by different materializers to work. The basic issue here is where these materializers shall come from, think about providing a `Source[ByteString, Unit]` for an HTTP response entity that pulls data out of a remotely materialized stream. This source will be materialized by the materializer that was used to create the HTTP endpoint, which means that this must either be capable enough (i.e. not a simple ActorMaterializer) or it must be able to locate auxiliary materializers (which is a lifecycle nightmare—no matter whether the references are included in the Graph itself or in some other statically accessible location (ewwww!)).

So, in light of these findings I think the only solution is for e.g. a remote materialization library to provide a specific materializer that delegates to the local ActorMaterializer for all parts that are not marked up as remote components via custom Attributes. The problem here is that this would require a non-trivial transformation of the module tree because a nested module needs to be ripped out and protected from being processed by the ActorMaterializer. We could define a supertype for a class of Attributes that have this effect and include an internal API in the ActorMaterializerImpl that can be used to hook in specific extensions, e.g. something like
~~~scala
def registerBreakOut[T <: BreakOutAttribute](attrType: Class[T], mat: Materializer)
~~~
on ActorMaterializer. Then another materializer can internally create an ActorMaterializer and delegate to that one after having registered itself as a break-out module (or extension—names can be picked later).

WDYT?

**Comment by clockfly** [comment]
We have a solution at https://github.com/gearpump/gearpump/tree/akkastream/experiments/akkastream
It solves every problem above.

I don't  think it is good idea to provide "Attributes.withMaterializer", I think it is up to the custom materializer to decide how to parse the module tree. Custom Materializer can choose to delegate partial graph to ActorMaterializer inside their implementation. 

Our implementation looks like this:
```
  override def materialize[Mat](graph: ModuleGraph[Mat]): Mat = {
    val subGraphs = new GraphCutter(strategy).cut(graph)
    val matValues = subGraphs.foldLeft(Map.empty[Module, Any]){(map, subGraph) =>
      map ++ subGraph.materialize(map, system)
    }
    graph.resolve(matValues)
  }
```

It use a GraphCutter to divide the graph to partial graph, and then materialize each sub-graph remotely, or locally. And combine all materialized value by calling "graph.resolve(matValues)"

**Comment by clockfly** [comment]
@rkuhn 

About this:
```
The problem here is that this would require a non-trivial transformation of the module tree because a nested module needs to be ripped out and protected from being processed by the ActorMaterializer
```

If we transform the Module tree to Atomic Module graph, then it is no longer difficult to divide the graph.

**Comment by clockfly** [comment]
Here is my proposal:
1) Change the materializer interface to the following BaseMaterializer:
```
abstract class BaseMaterializer extends akka.stream.Materializer {

  override def withNamePrefix(name: String): Materializer = throw new UnsupportedOperationException()

  override implicit def executionContext: ExecutionContextExecutor = throw new UnsupportedOperationException()


  def materialize[Mat](graph: ModuleGraph[Mat]): Mat

  override def materialize[Mat](runnableGraph: Graph[ClosedShape, Mat]): Mat = {
    val graph = ModuleGraph(runnableGraph)
    materialize(graph)
  }
}
```
The difference is that it accept a ModuleGraph instead of a Module tree (RunnableGraph).


2) Replace ModuleTree with ModuleGraph for the inputs to materializers. 

ModuleGraph is a graph of atomic modules. It flatten the module tree. It makes it easier to do transformation and optimization on the module tree, and make it trivival for user to divide the graph to partial ones.

```
/**
 *
 * ModuleGraph is a transformation on [[akka.stream.scaladsl.RunnableGraph]].
 * It carries all the information of [[akka.stream.scaladsl.RunnableGraph]], but
 * represents it in a different way.
 *
 * Here is the difference:
 *
 * RunnableGraph
 * ==============================
 * [[akka.stream.scaladsl.RunnableGraph]] is represented as a [[Module]] tree:
 *             TopLevelModule
 *                   |
 *          -------------------
 *          |                 |
 *      SubModule1         SubModule2
 *          |                    |
 *   ----------------           ----------
 *   |              |                    |
 * AtomicModule1 AtomicModule2  AtomicModule3
 *
 * ModuleGraph
 * ==============================
 * [[ModuleGraph]] is represented as a [[util.Graph]] of Atomic [[Module]]:
 *
 *        AtomicModule2 -> AtomicModule4
 *         /|                    \
 *       /                        \
 *     /                           \|
 * AtomicModule1           AtomicModule5
 *     \                   /|
 *      \                 /
 *       \|              /
 *         AtomicModule3
 *
 * Each vertex in the Graph is a [[Module]], each [[Edge]] in the Graph is a tuple
 * ([[OutPort]], [[InPort]]). [[OutPort]] is one of upstream Atomic Module
 * output ports. [[InPort]] is one of downstream Atomic Module input ports.
 *
 *
 * Why use [[ModuleGraph]] instead of [[akka.stream.scaladsl.RunnableGraph]]?
 * =========================
 * There are several good reasons:):
 * 1. [[ModuleGraph]] outlines explicitly the upstream/downstream relation.
 *   Each [[Edge]] of [[ModuleGraph]] represent a upstream/downstream pair.
 *   It is easier for user to understand the overall data flow.
 *
 * 2. It is easier for performance optimization.
 *  For the above Graph, if we want to fuse AtomicModule2 and AtomicModule3
 *  together, it can be done within [[ModuleGraph]]. We only need
 *  to substitute Pair(AtomicModule2, AtomicModule4) with a unified Module.
 *
 * 3. It avoids module duplication.
 *  In [[akka.stream.scaladsl.RunnableGraph]], composite Module can be re-used.
 *  It is possible that there can be duplicate Modules.
 *  The duplication problem causes big headache when doing materialization.
 *
 *  [[ModuleGraph]] doesn't have thjis problem. [[ModuleGraph]] does a transformation on the Module
 *  Tree to make sure each Atomic Module [[ModuleGraph]] is unique.
 *
 *
 * @param graph a Graph of Atomic modules.
 * @param mat is a function of:
 *             input => materialized value of each Atomic module
 *             output => final materialized value.
 * @tparam Mat
 */
```

**Comment by clockfly** [comment]
In our custom GearpumpMaterializer, we will materialize patial graph locally, and paritial graph remotely. Here is our details:
1) Define a strategy, which maps Module to Location.
```
  sealed trait Location
  object Local extends Location
  object Remote extends Location

  type Strategy = PartialFunction[Module, Location]
```

2) The custom Materializer can use this strategy to decide how to divide a graph to sub-graphs.
```
class GearpumpMaterializer(system: ActorSystem, strategy: Strategy = GraphCutter.AllRemoteStrategy)
    extends BaseMaterializer {

  override def materialize[Mat](graph: ModuleGraph[Mat]): Mat = {
    val subGraphs = new GraphCutter(strategy).cut(graph)
    val matValues = subGraphs.foldLeft(Map.empty[Module, Any]){(map, subGraph) =>
      map ++ subGraph.materialize(map, system)
    }
    graph.resolve(matValues)
  }
}
```

3) Each Sub-Graph materializer can materialize its own part, and generate its own materialized values:
```
/**
 * [[SubGraph]] is a partial part of [[akka.stream.ModuleGraph]]
 *
 * The idea is that by dividing [[akka.stream.ModuleGraph]] to several
 * [[SubGraph]], we can materialize each [[SubGraph]] with different
 * materializer.
 */

trait SubGraph {
  /**
   *
   * @param matValues Materialized Values for each module before materialization
   * @param system
   * @return Materialized Values for each Module after the materialization.
   */
  def materialize(matValues: Map[Module, Any], system: ActorSystem): Map[Module, Any]

  /**
   * the [[Graph]] representation of this SubGraph
   * @return
   */
  def graph: Graph[Module, Edge]
}
```

The materialized value for sub-graph is Map[Module, Any]

4) Then the final materializer can combine all materialized values from all sub-graphs, and convert it to final materialized value.

```
class ModuleGraph[Mat](val graph: util.Graph[Module, Edge], val mat: MaterializedValueNode) {

  def resolve(materializedValues: Map[Module, Any]): Mat = {
    MaterializedValueOps(mat).resolve[Mat](materializedValues)
  }
}

class MaterializedValueOps(mat: MaterializedValueNode) {
  def resolve[Mat](materializedValues: Map[Module, Any]): Mat = {
    def resolveMaterialized(mat: MaterializedValueNode, materializedValues: Map[Module, Any]): Any = mat match {
      case Atomic(m) => materializedValues.getOrElse(m, ())
      case Combine(f, d1, d2) => f(resolveMaterialized(d1, materializedValues), resolveMaterialized(d2, materializedValues))
      case Transform(f, d)    => f(resolveMaterialized(d, materializedValues))
      case Ignore             => ()
    }
    resolveMaterialized(mat, materializedValues).asInstanceOf[Mat]
  }
}
```

**Comment by kkasravi** [comment]
@rkuhn If I understand your approach correctly - particular boundaries (breakout modules) are defined within the module tree that allow a different materializer to 'take over'. Within this materializer it deploys this sub-tree remotely where a local ActorMaterializer it created. The local ActorMaterializer may cross another boundary (breakout module) that causes yet a another different materializer to take over - and so on. There are strong similarities in both approaches - the notable differences being (see @clockfly's code snippets above):
* the module tree is always flattened to a Graph[Module, Edge]. Are there use cases where flattening to atomic modules would pose a problem?
* the materializer does not create a local ActorMaterializer at the remote location. Modules are handled per MaterializedValueNode and materialized within GraphTasks subtypes (BroadcastTask, UnZip2Task, BalanceTask, etc).

**Comment by drewhk** [comment]
There are other approaches that can work, too. For example it might be possible to have a composite materializer:

     CompositeMaterializer(whichMaterializer: PartialFunction[Attributes, Materializer], default: Materializer)

This would need some changes in the MaterializerSession, but due to the hierarchic construction it should work. In a way it is a dynamic flattening, where an Attribute chooses a materializer, and a composite module is turned into an atomic one and "returned" to the outer scoped materializer.

**Comment by drewhk** [comment]
An example usage would be:

     val remoteProcessing: Flow = (...).withAttributes(GearPumpDeployed)
     // above can be wrapped in DSL (apply simply attaches the attribute if not present):
     val remoteProcessing: Flow = GearPumpDeployed(Flow.bla)
     val fullPipeLine = Source(...).via(localProcessing).via(remoteProcessing)...

     val gearpumpMat  = ...
     val localMat = ...
     val mat = CompositeMaterializer ({case GearPumpDeployed => gearPumpMat}, localMat)

So the attributes are still passive, symbolic only annotations, the actual binding is in the materializer itself (can come from config even if we want it). The boundaries are aligned with module boundaries, i.e. the graph cut is always a boundary.

**Comment by clockfly** [comment]
@drewhk I agree the point of adding a new attribute which give a hint about materializer.

I am not sure what you mean about "CompositeMaterializer". Suppose I am the custom materializer library provider, do I also need to write a custom  CompositeMaterializer? or CompositeMaterializer is a final class provided by akka-stream?

**Comment by drewhk** [comment]
I was thinking providing such materializer from Akka. Probably supported materializers would need to extend some subclass of Materializer though that is capable of materializing an arbitrary module, not just a closed graph.

**Comment by clockfly** [comment]
Then, that will be some problem 

Suppose CompositeMaterializer is a final class, and not customizable.

Consider graph: local_A -> remote_B, to materialize it, we need to rewrite the graph to two sub-graph like this:
local_A-> local_bridge, remote_bridge->remote_B

The local_bridge/remote_bridge impl can be very different for different materializer pair. That requires CompositeMaterializer to be customizable.  <- conflict with Assumption.

Maybe it is not viable to provide a generic CompositeMaterializer which can support all sub-graph materialziers.

**Comment by kkasravi** [comment]
@drewhk if the CompositeMaterializer composes an arbitrary Materializer which in turn is typed by a BreakOutAttribute as @rkuhn suggests you could use a typeclass approach since Materializers are implicitly resolved.

```
trait BreakOutAttribute extends Attributes.Attribute
trait MaterializerWithAttribute[_<:BreakOutAttribute] {...}
class CompositeMaterializer[M[_<:BreakOutAttribute]<:MaterializerWithAttribute[_<: BreakOutAttribute]]{...}
```

```
class RemoteAttribute extends BreakOutAttribute {...}
object RemoteMaterializer extends MaterializerWithAttribute[RemoteAttribute] {
  override def withNamePrefix(name: String): Materializer = ???
  override implicit def executionContext: ExecutionContextExecutor = ???
  override def materialize[Mat](runnableGraph: Graph[ClosedShape, Mat]): Mat = ???
}
```

It depends if the akka team wants to only provide a known set of Materializers (from Akka) or you allow an arbitrary materializer to be added to the CompositeMaterializer based on an arbitrary Attribute - both not known (or defined) beforehand. The latter provides the best flexibility and would be more in line with leveraging scala's type system similar to shapeless or cats.

**Comment by kkasravi** [comment]
I should note - even the above suggestion is amenable to what @clockfly has outlined where GearPump would be a specific Materializer and would be resolved based on the presence of a specific 'GearPump' attribute as dictated by the typeclass pattern.

**Comment by rkuhn** [comment]
This has dropped from my radar last November, sorry about that! Since Gearpump is alive and kicking (and working!) what is the status here? Do we need to add or fix things or is the current design good enough?

**Comment by kkasravi** [comment]
Hi @rkuhn - thanks for the followup! We had a short meeting with @patriknw last week and we're going to open an issue and submit a PR either this week or next suggesting some refactoring to MaterializerSession and GraphIntepreterShell that make it easier for a different Materializer to control subgraphs.

**Comment by rkuhn** [comment]
Cool, looking forward to seeing that!
