### ISSUE TITLE
2.0-M1 reference documentation contains references to `builder.addEdge`, `partial`, `closed`, and others

### ISSUE THREAD

**Issue by dotta** [akka/akka#18917]
I went through the Scala reference doc for 2.0-M1 and noticed the text hasn't been fully updated. See for instance http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M1/scala/stream-quickstart.html, which contains references to non existing methods `builder.addEdge`, `partial`, and `closed`. Or http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M1/scala/stream-graphs.html, which also contains references to  `partial`, `closed`, and also text that I believe is plain wrong now, e.g., `In order to create a Source from a partial flow graph Source provides a special apply method that takes a function that must return an Outlet[T] [...]`.

These are just a couple of examples, there are likely more places where the text needs to be updated.

**Comment by ktoso** [comment]
Thanks for noticing!

**Comment by drewhk** [comment]
oops! Thanks for reporting!

**Comment by ktoso** [comment]
Thanks for fixing @johanandren !
