### ISSUE TITLE
[akka-http] Java route DSL should follow scala route DSL more closely

### ISSUE THREAD

**Issue by jypma** [akka/akka#18919]
In order to improve consistency, and to help devs re-use knowledge between Java and Scala, I've created a prototype Java routing DSL that follows the scala routing DSL almost exactly. It's currently in a different [repository](https://github.com/jypma/scala-japi/pull/1) (built on top of the scala routing DSL + java http model).

This alternative has the following advantages over the current Java DSL:
- Routes are completely composable and reusable, without the need to separate routing from implementation using `handleWith`. Every directive just extracts values, and calls an inner route with them.
- Extractions can be made directly as function arguments, without needing a `RequestVal` construct.
- All Scala constructs can be immediately re-exposed in Java 8-friendly API's by adapting function arguments to their equivalents in `java.util.function`.

An example route is given in [RouteSpec](https://github.com/jypma/scala-japi/pull/1/files#diff-6f20875b165bbcb14a14d523d0ffe1f7R219), here's a short extract:
```
        return route(
            path("documents", () ->
                path(UUID(), id -> // type inferred as UUID
                    complete("document " + id)
                )
            ),
            path("people", () ->
                path(name -> // type is String
                    complete("person " + name)
                )
            ),
            path("notreally", () ->
                rejectWith(new MissingFormFieldRejection("always failing"))
            ),
            path("shouldnotfail", () ->
                handleExceptions(xHandler, () ->  // re-using PFBuilder for making ExceptionHandler
                    onSuccess(() -> throwExceptionInFuture(), value -> 
                        complete("never reaches here")
                    )
                )
            ),
            path("cookies", () ->
                param(INT(), "amount", amount ->  // routes can be picked by query parameter type, just like Scala
                    complete("cookies " + amount)
                )
            ),
            path("cookies", () ->
                param(STRING(), "amount", amount -> 
                    complete("cookies (string) " + amount)
                )
            ),
            path("bar", () ->
                extract(CUSTOM_EXTRACT, value -> 
                    complete("bar " + value)
                )
            ),
            path("custom_response", () ->
                complete(HttpResponse.create().withStatus(StatusCodes.ACCEPTED))
            ),
            path("uuid", () -> route(
                put(() ->
                    entityAs(UUID_FROM_BODY, value ->  // actual wrapped Scala Unmarshaller 
                        complete("uuid " + value)
                    )
                ),
                get(() -> {
                    UUID id = UUID.fromString("80a05eee-652e-4458-9bee-19b69dbe1dee");
                    return complete(id, UUID_TO_BODY);   // actual wrapped Scala Marshaller 
                })
            )),
```

**Comment by jypma** [comment]
@ktoso @viktorklang here's the alternative Java API attempt we talked about earlier. It's completely built on top of the public Scala routing API + Java HTTP model only. Feedback is welcome :-)

**Comment by 2beaucoup** [comment]
Looks cool @jypma! Nice to see what's possible with Java 8. :)

BTW: Why did you wrap the collections instead of using `scala.collection.JavaConverters`?

**Comment by jypma** [comment]
@2beaucoup Collections, option, etc. are wrapped instead of converted for the following reasons:
- Most of this stuff is going to be async, flows, futures, etc., and I wanted to make it crystal clear on a type level that the collections are immutable and hence safe.
- Immutable collections work best with lamda concepts, but you can't (yet) use a Java 8 lambda to express a Scala `FunctionN`. And I didn't want a wrapper for each lambda. So scala collections couldn't be exposed directly.
- The closest thing inside Java 8 that might apply are the Java 8 streams, but streams aren't collections, and either way the combinators on streams are much less rich than what's available with scala collections.

Of course, if this lib is to get closer to akka's core, something might need to be done. It's always easier to target Java 8-only, when you don't have to carry around existing Java interop from akka's own java layer. Now we have `scala.Option`, `akka.japi.Option`, `java.util.Optional` and the `Option` in here. However, of these, only the latter currently works comfortably with lamda expressions.

**Comment by ktoso** [comment]
This looks very intriguing @jypma!
I'll find the time to review this in detail but it does seem quite promising from the outside, thanks for sharing!

**Comment by ktoso** [comment]
(Assigned myself to this ticket so I don't forget about it, definitely want to give it a proper read soon)

**Comment by jypma** [comment]
@ktoso Thanks for taking the time to look into this. I don't know your schedule for getting akka-streams into master, but would you consider at least not marking the current `akka.http.javadsl.server` Java DSL non-experimental, until a direction on this has been chosen?

**Comment by ktoso** [comment]
Streams and HTTP will be experimental even once merged to master. They have to survive a full major release cycle as part of "main Akka" to become non-experimental. We are free to change the DSL – there is time, don't worry about that.

**Comment by ktoso** [comment]
Again, I'm very sorry this slipped through again. I will definitely review soon, as it looks nice and we may want to simply include it instead of the current one (not sure yet, but a possibility).

**Comment by jypma** [comment]
Let me know if/when you get closer to considering it for inclusion. I'd be happy to turn this into a PR.

When that time comes we should probably have a discussion about what to do with the collection + future wrappers. The way I did it here makes both of them _much_ nicer to deal with in Java (exact reasons given above).

**Comment by ktoso** [comment]
Reviewing it now, sorry for the delays – were very focused on getting out 2.0.

**Comment by ktoso** [comment]
I like it a lot – we'd have January to bring it up to feature parity with the Scala DSL and could ship it there.
Some of the directives will need yak-shaving, like for example how we'll express `parameters` etc, but it looks very promising, and much more familiar to the ScalaDSL than the RequestVals which is a good thing I believe.

I hope I did not miss something fundamental which would be impossible in this style of API, but I think not.

Would you be able to make this into a PR, and we'll track feature parity and progress in there then?
Thanks a lot and once again sorry reviewing this took me so long!

**Comment by ktoso** [comment]
@sirthias @jrudolph could you have a look at there here linked repo?
I like that DSL proposal, did I miss something it could not express?

**Comment by jypma** [comment]
Sure thing. I'm on vacation at the moment, but I'll probably be able to work on turning this into a proper PR starting from next week, Jan 11.

What direction should we take on the wrapping of collections, futures, etc.? The decision to wrap all of them has had a very positive impact on our ability to write Java 8 lambdas to comfortably interact with the DSL. The wrappers are in a [different library](https://github.com/jypma/scala-japi/tree/master/scalaLib/src/main/scala/com/tradeshift/scalajapi).

**Comment by ktoso** [comment]
Thanks for pointing out that part, I'll have a deeper look at those. 
Going as far as we can with raw JDK8 types would be preferable - the entirety of Akka/Streams/Http APIs will go in that direction for Java APIs

**Comment by ktoso** [comment]
For our reference, here are the mentioned types (checked box means I've read through and we have a decision what to do about it):

- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/collect/Either.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/collect/Map.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/collect/Option.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/collect/Seq.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/collect/Set.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/collect/SortedSet.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/collect/Try.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/concurrent/Await.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/concurrent/Concurrent.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/concurrent/Future.scala
- [ ] scalaLib/src/main/scala/com/tradeshift/scalajapi/function/Functions.scala - doesn't seem to be really needed. Also, very simple to put into Akka's `Functions.scala` if we find any need for such methods.

**Comment by jypma** [comment]
@ktoso To help me understand the impact of the wrapping decisions here, could we have a look at the expected timelines of:
- Getting a PR for this merged in (probably a month or so?)
- 2.12 being released and akka supporting it (2.12 roadmap does say "Jan 2016"...)

As to using the Java collection libraries: I do understand that it's not akka's role to release / expose collection libraries. However, that being said, the current contents of the JDK8 is a mess w.r.t. immutable / async / functional programming, making any plain JDK usage very cumbersome:
- There are no type-safe obviously immutable collections
- Using collection transformation expressions requires roundtrips through `.stream().xxx().collect(...)`
- Java's new Option is [generally](https://developer.atlassian.com/blog/2015/08/optional-broken/) being [viewed](https://medium.com/@bgourlie/java-8-s-new-optional-type-is-worthless-448a00fa672d#.caq8fsu4r) as [broken](http://blog.jooq.org/2014/03/28/java-8-friday-optional-will-remain-an-option-in-java/). There are a lot of reasons; personally I find the lack of `.orElse(Option b)` most hurting.

I'm hesitant to evaluate decisions based on the assumption that "interop might get better" with 2.12. Yes, lambdas might fit more naturally. But operators like `$plus$plus` remain, and API's that have implicit parameters are still a mess to use from Java (e.g. `Future.map`).

I do realize however that the plain DSL should probably stick as close to plain Java as possible.

**Comment by ktoso** [comment]
Also relates to https://github.com/akka/akka/issues/19019

**Comment by ktoso** [comment]
> Getting a PR for this merged in (probably a month or so?)

Timeline of a month sounds reasonable yes. We're currently in the middle of switching development of streams to the `master` branch and finishing up for streams stable release, so after that merging this makes sense. 

> 2.12 being released and akka supporting it (2.12 roadmap does say "Jan 2016"...)

There was a roadmap update, it's mid-2016 now: 
http://scala-lang.org/news/2016-schedule/

> , and API's that have implicit parameters are still a mess to use from Java (e.g. Future.map).

Does not apply to Java API though... since `CompletionStage`.

**Comment by ktoso** [comment]
Whoops, I've hit comment to early; addressing all points.

**Comment by ktoso** [comment]
Replied to all points I think. Let me know if anything's unclear; The PR should be targetted to the master branch *once we're done migrating streams there* – which is happening now as we speak. There will be a ping on akka/dev about it once we're ready, thanks!

**Comment by jypma** [comment]
OK with trying a PR of this DSL bound to the standard Java collections. @ktoso let me know when master is ready to receive it. No rush from my side.

**Comment by ktoso** [comment]
`master` is ready :-) You're free to fork off and start hacking! Thanks a lot in advance.

note: I'll be offline the next 2 weeks, ping @rkuhn or @drewhk if something needs quick response during those.

**Comment by jypma** [comment]
OK, starting some work now.

**Comment by ktoso** [comment]
Awesome, let us know if stuck or need tips/help on anything :)

**Comment by chadselph** [comment]
I know this is part of the `experimental` package, but I didn't see anything calling out that moving from `segmentStringToPathMatcher` to `_segmentStringToPathMatcher` broke binary compatibility.

**Comment by ktoso** [comment]
No binary guarantees are made about experimental modules. 
That's the single thing `-experimental` means.

What's your case that you got struck by the DLS part to have changed in such way btw? 
The DSL project I'd imagine be mostly used in "end user" (as in, actual "app" which is rebuilt) setting in which you build when you bump.

It's documented on their page http://doc.akka.io/docs/akka/snapshot/experimental/index.html and we've been sticking to this rule all along.

**Comment by chadselph** [comment]
We have an internal framework which depends on akka-http, one feature it provides is an admin interface, based on dropwizard's admin. There's a `/healthcheck` endpoint that used the  Scala routing DSL. Since the implicit was renamed, the when a downstream end user project upgraded to 2.4.5 and the library was still built against 2.4.4, we got a `segmentStringToPathMatcher` method not found exception. 

It wasn't a huge problem, but it doesn't seem like there was an reason to change the name anyway.
