### ISSUE TITLE
Depends on Akka git project ref

### ISSUE THREAD

**Issue by andreaTP** [akka/akka#18922]
Trying to put this in a plain sbt project:
```
lazy val akka = ProjectRef(uri("git://github.com/akka/akka.git#master"), "akka")
```
Fail with:
```
fatal: remote error:
  akka/akka-samples/akka-sample-camel-java is not a valid repository name
  Email support@github.com for help
java.lang.RuntimeException: Nonzero exit code (128): git clone --depth 1 git://github.com/akka/akka-samples/akka-sample-camel-java /Users/andrea/.sbt/0.13/staging/c106b727f177c676bb38/akka-sample-camel-java
```

**Comment by ktoso** [comment]
Hm no idea why this might be actually... AFAIR we do clone --depth 1 on our jenkins. Does it work outside of sbt?

**Comment by andreaTP** [comment]
no even from command line:
```
git clone --depth 1 git://github.com/akka/akka-samples/akka-sample-camel-java
```
result in:
```
Cloning into 'akka-sample-camel-java'...
fatal: remote error:
  akka/akka-samples/akka-sample-camel-java is not a valid repository name
  Email support@github.com for help
```

**Comment by andreaTP** [comment]
ok, couldn't understand why this command is triggered by sbt... this is obviously not correct, maybe is a bug there?

**Comment by ktoso** [comment]
Huh, now I see what you want. git can't do "sub folder checkouts", by construction.
You have to clone an entire repo.

**Comment by ktoso** [comment]
If you want that you can try a submodule for akka, and symlink into it - to the directory.
