### ISSUE TITLE
BidiFlow.reverse is broken

### ISSUE THREAD

**Issue by drewhk** [akka/akka#18928]
It simply replaces the shape, but this reorders ports compared to what order they were enumerated before. This breaks one of the internal assumptions and leads to class-cast execeptions. Basically it rotates the exterior of the stage while keeping the interior unrotated.

/cc @rkuhn

**Comment by drewhk** [comment]
Solution is simply:
```
  def reversed: BidiFlow[I2, O2, I1, O1, Mat] = {
    BidiFlow.fromGraph(FlowGraph.create(this) { implicit b ⇒
      reversed ⇒
        BidiShape(reversed.in2, reversed.out2, reversed.in1, reversed.out1)
    })
  }
```

The import autaomatically handles the remapping that is needed.

**Comment by drewhk** [comment]
this will be included in my PR here: https://github.com/akka/akka/pull/18918

**Comment by viktorklang** [comment]
Nice catch, @drewhk

**Comment by ktoso** [comment]
Fix now ripped out from @drewhk's Tls work and part of my PR https://github.com/akka/akka/pull/18973 here
