### ISSUE TITLE
the akka-zeromq demo  has a bug

### ISSUE THREAD

**Issue by sunqb** [akka/akka#18923]
when use final ,the timestamp will never have a value

```Java
 public class Heap implements Serializable {
     private static final long serialVersionUID = 1L;
     public final long timestamp;
     public final long used;
     public final long max;

      public Heap(long timestamp, long used, long max) {
          this.timestamp = timestamp;
          this.used = used;
          this.max = max;
     }
 }
```

**Comment by johanandren** [comment]
I'm not sure but I am guessing you are referring to the example in the 2.3-docs (http://doc.akka.io/docs/akka/2.3.14/java/zeromq.html)

Blank final fields are valid Java, they must be assigned a value in the constructor though, if they are not you will get a compile error, so this guarantees that they have a value after the object is constructed but can never change after that.

http://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.3.1.2

**Comment by johanandren** [comment]
Additional note: The zeromq-extension is no longer a part of Akka, it has been removed in 2.4

**Comment by sunqb** [comment]
@johanandren 
ok, i see ,thank you!
