### ISSUE TITLE
entitySizeLimit high-level directive

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18929]
A follow up to https://github.com/akka/akka/issues/16468 which was solved in https://github.com/akka/akka/pull/18888 (on the low-level).

We'll want to expose a simple directive which does the right thing (maps the request applying the limit)

**Comment by ktoso** [comment]
This is a rather simple directive one could contribute, it should transform the request entity by using extractEntity and withSizeLimit(...) on it.

**Comment by note** [comment]
I am willing to take this one.

**Comment by ktoso** [comment]
Great, please do :)
Let me know if you have any questions.

It should *more or less* look like this:

```scala
withoutEntitySizeLimit { 
  extractEntity { e ...
  }
}
```

**Comment by ktoso** [comment]
Thanks @note!
