### ISSUE TITLE
enhancement: "Draining a stream to a strict collection" / Sink.toSeq / Stream.limit

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#18921]
See lots of discussion on the aborted PR #18267

The ["Draining a stream to a strict collection" recipe](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M1/scala/stream-cookbook.html#Draining_a_stream_to_a_strict_collection) could do with replacing with a builtin `Sink.toSeq` sink helper, for a number of reasons:

 * magic numbers: avoiding users needing to guess in advance how long their stream might be
 * correctness: enforcing that the stream ends (the recipe linked above will ignore without error any elements after "MaxAllowedSeqSize")
 * ease of use for a common operation
 * performance

There is some controversy over whether "draining a stream to a strict collection" is a legitimate thing to want to do (see e.g. @drewhk's and @ktoso's comments on #18267), but after much back-and-forth which I won't try to summarise here, @rkuhn said:

> Sorry, I’m late to the party: it is obvious that collecting a finite stream into a sequence is a popular operation, I think we should support it. I’d recommend keeping the concerns orthogonal:
>
>    val single = source.limit(1).runWith(Sink.head)
>    val seq = source.limit(65536).within(5.seconds).runWith(Sink.toSeq)
>
> This implies that Sink.single is superfluous as shown above (limit will have to assert completion before emitting the final element in order to live up to its expectations). Does that work for everyone?
> 
> Side remark: instead of having an unusual alias in the Java DSL we should instead recognize this difference in the consistency spec.

**Comment by rkuhn** [comment]
Yes, thanks.

**Comment by lolski** [comment]
Can I give a shot?

**Comment by drewhk** [comment]
Yes, go ahead!

**Comment by lolski** [comment]
Before I commence, what is the status of @RichardBradley's PR here: https://github.com/akka/akka/pull/18267. Since it would overlap with my work, I would like to check if it is still actively being developed

**Comment by lolski** [comment]
@rkuhn @drewhk @ktoso 
the problem I see with `source.limit(65536).within(5.seconds).runWith(Sink.toSeq)` is that there's no stopping unsuspecting users into calling `source.runWith(sink.toSeq)` since it's not enforced by the type.

If we enforce the parameter i.e, `Sink.toStrict(maxCount: Int, atMost: FiniteDuration)` I think it will be safer overall. What do you guys think?

**Comment by RichardBradley** [comment]
> I think it will be safer overall if we enforce the parameter i.e, Sink.toStrict(maxCount: Int, atMost: FiniteDuration). What do you guys think?

We discussed this at length on #18267 -- please could you skim that thread?

There's no need to add the "atMost: FiniteDuration", because the return type is a Future[Seq], so you'll need to add timeouts later if you want them. (Unless you're discussing cancelling the awaited value? None of the other builtin Sinks have cancellation support, e.g. Sink.head.)

The problem with "maxCount: Int" is that it encourages magic numbers. No other "toSeq" operator takes such a param (e.g. TraversableOnce.toSeq). I suppose it would be better than the current `x.grouped(n).runWith(Sink.head)` if the maxCount were at least enforced. I still vote against it.

**Comment by RichardBradley** [comment]
> there's no stopping unsuspecting users into calling source.runWith(sink.toSeq)

This keeps coming up in this thread. Why would you think that Scala users are delicate flowers who need protecting against calling code that might not return?
No-one thinks that `TraversableOnce.toSeq` or `while(f())` or `Sink.fold` should be banned just because they can't be proven to terminate at compile-time.
&lt;/rant>

**Comment by rkuhn** [comment]
I’m with @RichardBradley here, and the “magic numbers” argument is the right one: we provide all the tools people need and they are more useful if they remain orthogonal. The method should be called `toSeq` without parameters and we should document it always in the context of `.limit(N).takeWithin(x)` so that the limits are on peoples’ minds.

**Comment by drewhk** [comment]
The only think is that it is not `takeWithin` but `completionTimeout` what people likely want (i.e. error out if time elapsed). The `limit` op does not exist yet AFAIK.

I think this pattern of limiting in both time ane element count deserves a place in the cookbook.

**Comment by rkuhn** [comment]
Well, that underlines my point: the user gets to choose between `takeWithin`, `completionTimeout` or whatever they want.

**Comment by lolski** [comment]
OK, it is agreed then. Work have just been started and will push a WIP by tomorrow.

**Comment by rkuhn** [comment]
Great, thanks!

**Comment by RichardBradley** [comment]
There are a few issues which are missing from this merged PR, in my opinion:

 * Loads of "stream.grouped(n).runWith(head)" expressions in Akka (mainly in test) can now be replaced with "stream.runWith(seq)" -- see #18267
 * The current implementation of "Sink.seq" will silently do the wrong thing if the stream is longer than INT.MAX_VALUE. I think this deserves fixing, or at the very least a note in the docs. Notably, "limit" and other length operators take a Long, so Akka does seem to allow streams longer than Int.MAX_VALUE.
 * The `stream-cookbook.rst` hasn't been updated, and still suggests the old recipe. See #18267 for a fix.

**Comment by ktoso** [comment]
Can you open a top-level ticket with those comments @RichardBradley ? Thanks!

**Comment by lolski** [comment]
@RichardBradley right. thanks for noticing
