### ISSUE TITLE
Shard [..] already allocated

### ISSUE THREAD

**Issue by jsuchenia** [akka/akka#18936]
During a system full restart (to deploy new version of a code, so all nodes are down, they are starting one-by-one) we observed a lot of exceptions like that:
```
Nov 16 10:36:44 core-01 sh[10792]: java.lang.IllegalArgumentException: requirement failed: Shard [89529958] already allocated: State(Map(89529958 -> Actor[akka://Scada/system/sharding/Plc#-21125606]),Map(Actor[akka://Scada/system/sharding/Plc#-21125606] -> Vector(89529958), Actor[akka.tcp://Scada@172.17.8.102:2552/system/sharding/Plc#2077931377] -> Vector(), Actor[akka://Scada/system/sharding/Plc#-1996414802] -> Vector()),Set(),Set())
Nov 16 10:36:44 core-01 sh[10792]: at scala.Predef$.require(Predef.scala:219) ~[scala-library-2.11.7.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.cluster.sharding.ShardCoordinator$Internal$State.updated(ShardCoordinator.scala:278) ~[akka-cluster-sharding_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.cluster.sharding.PersistentShardCoordinator$$anonfun$receiveRecover$1.applyOrElse(ShardCoordinator.scala:714) ~[akka-cluster-sharding_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.persistence.Eventsourced$$anon$3$$anonfun$1.applyOrElse(Eventsourced.scala:438) ~[akka-persistence_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.cluster.sharding.PersistentShardCoordinator.akka$persistence$Eventsourced$$super$aroundReceive(ShardCoordinator.scala:680) ~[akka-cluster-sharding_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:481) ~[akka-persistence_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:158) ~[akka-persistence_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.cluster.sharding.PersistentShardCoordinator.aroundReceive(ShardCoordinator.scala:680) ~[akka-cluster-sharding_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525) [akka-actor_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.actor.ActorCell.invoke(ActorCell.scala:494) [akka-actor_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.0.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
Nov 16 10:36:44 core-01 sh[10792]: at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
```

**Comment by smlin** [comment]
@jsuchenia I think you needed to remove old persisted sharding data from your database. That happens since the `ShardCoordinator` stores data about shards in database with help of `akka-persistence`. And I not think that is real issue since after full restart of a cluster you has an incorrect info about shards in database. If you want avoided use the `akka-persistence` then you would set `akka.cluster.sharding.state-store-mode="ddata"` to force the `ShardCoordinator` use the `akka-distributed-data` as a store. But of course `akka-distributed-data` is experimental and you need to add it as dependency explicitly.

**Comment by jsuchenia** [comment]
@smlin But:
1. I'm using it on my development environment (Vagrant + akka-persistence-cassandra) so data in database was populated just few minutes before a restart
2. I want to use 'rememberEntries' flag, to start actors at the beginning of shard lifecycle  - so i want to persist them

**Comment by jsuchenia** [comment]
There could be an issue that I didn't override `min-nr-of-members` where all IPs were passed as seed-nodes - with this settings it works fine

**Comment by smlin** [comment]
@jsuchenia Using the `ddata` mode do not restricts you from using the `akka-persistence`, just forces the coordinator do not use it. So you can use the `rememberEntries` flag together with `ddata`.

**Comment by jsuchenia** [comment]
@smlin I tested shard with both: `ddata` and `rememberEntries` set and it doesn't work. From logs it looks like actors in a shard were not started after a restart.

**Comment by smlin** [comment]
@jsuchenia If you are using the `ddata` mode then the coordinator do not know about shards right after restart. But `rememberEntries` flag force the shards to store info about entries. So `ddata+rememberEntries` is a kind of "lazy persistent shards" from some point of view. You need to send message to any entry inside the persistent shard to init the replay process of this shard. 

@patriknw I think that case is slightly confusing and have to be clarified in the docs.

**Comment by patriknw** [comment]
I agree, very confusing. I created a separate issue for that: https://github.com/akka/akka/issues/19003
