### ISSUE TITLE
Support other than `websocket` in switching protocols for akka-http.

### ISSUE THREAD

**Issue by TimothyKlim** [akka/akka#18935]
Hello hAkkers,

I'm trying to work with docker http api response like this:

```
HTTP/1.1 101 UPGRADED
Content-Type: application/vnd.docker.raw-stream
Connection: Upgrade
Upgrade: tcp

{{ STREAM }}
```

with akka-http:

```scala
import akka.stream.scaladsl._
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.http.scaladsl.model.headers.{UpgradeProtocol, Upgrade}

Source
  .single(
    HttpRequest(
      HttpMethods.POST,
      "/containers/mongo/attach?stream=1&stdout=1&stderr=1",
      headers = List(Upgrade(List(UpgradeProtocol("tcp"))))
    )
  )
  .via(Http().outgoingConnection("coreos", 2375)) // docker api
  .runWith(Sink.head)
  .flatMap { res =>
    println(res.headers) // => List(Connection: Upgrade, Upgrade: tcp)
    println(res.entity.isCloseDelimited(), res.entity.isIndefiniteLength()) // => (false, false)
    res.entity.dataBytes.runForeach(println) // => ByteString()
  }
```

this example implicitly did close without waiting for data to print. Any ideas how to stop implicitly connection close?
Thank you.

**Comment by danielkza** [comment]
I second this request: I'm implementing HTTP/2 and it would be really nice if I could keep as much of the original HTTP machinery as possible and only get in after an upgrade. Right now I have to use the HTTP parsing but redo mostly everything else.

**Comment by ktoso** [comment]
Hi @TimothyKlim, could you provide some background who uses this and why you need it?
`Upgrade: tcp` sounds somewhat weird, but I guess you've seen it in the wild in existing APIs?

**Comment by ktoso** [comment]
// cc @sirthias @johanandren

**Comment by TimothyKlim** [comment]
Hi @ktoso, this approach is used by docker in [attach to a container api](http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#attach-to-a-container).
I need this because I'm writing library for work with docker api.

**Comment by ktoso** [comment]
Very weird upgrade header, I don't see any reasoning behind using it in these docs (it's not explained why needed...).

But you can use the websocket API currently right away right: http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#attach-to-a-container-websocket ?

**Comment by TimothyKlim** [comment]
>But you can use the websocket API currently right away right: http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#attach-to-a-container-websocket ?
Yes, currently I use websockets for new versions of their api.

**Comment by ktoso** [comment]
I thought about it a bit and I'll mark as triaged but it's a rather low priority ticket for us at this point in time.

**Comment by ktoso** [comment]
Marking as obsolete, won't currently work on it.
