### ISSUE TITLE
[akka-http] Expose HttpsContext in Java route DSL

### ISSUE THREAD

**Issue by rasa-silva** [akka/akka#18930]
The low level apis expose HttpsContext to enable HTTPS but, as far as I can tell, this is not currently exposed in the high level route API.

Something like an overload for bindRoute with that param would be enough I think...

**Comment by ktoso** [comment]
Thanks for reporting, it may indeed be missing Api... I'll investigate
early next week.

**Comment by ktoso** [comment]
AFAICS this is not really valid, HttpsConnectionContext is passed into the bind methods, so it is available. When looking at java api this week I'll make sure that we're on feature parity with scala in directives.
