### ISSUE TITLE
[akka-stream] Optional eagerClose parameter for FlowOps.merge and mergeMat

### ISSUE THREAD

**Issue by Athelionas** [akka/akka#18948]
I have a fairly simple case where I have to merge several sources and stop processing when any of them is completed. Currently I have to use a custom flow to merge inputs, because the underlying Merge object's eagerClose parameter in the implementation of FlowOps.merge and mergeMat is not exposed via the API. These methods could be much more useful if they had optional parameters to set eagerClose. Default could be false to reflect current behaviour without code breakage.

I would gladly contribute the little piece of code needed for this to work if there's no objection ;)

**Comment by drewhk** [comment]
Ok, sounds like a good idea.
