### ISSUE TITLE
[akka-cluster-sharding] ShardRegion doesn't kill shard actors on HandOff

### ISSUE THREAD

**Issue by msosnicki** [akka/akka#18945]
Hi,

This is a follow-up from the topic that can be found [here] (https://groups.google.com/forum/#!topic/akka-user/AF8P9i_MlUY) (you can skip the first post). 

To summarize, when ShardRegion receives the *HandOff(shard)* message, it should stop all the entities for that shard. But it makes the decision based on this fragment:
```scala  
if (shards.contains(shard)) {
   handingOff += shards(shard)
   shards(shard) forward msg
} else
   sender() ! ShardStopped(shard)
```
The *shards* map however, doesn't necessarily have all the shards in that ShardRegion, because this property is updated only from the constructor of Shards (*remember-entities=off*), of after successful recovery of a PersistenceShard (*remember-entities=on*).
In both cases it leaves a small gap (the problem is much bigger issue with PersistentShard though, because the recovery times might be significant), during which when receiving HandOff message will not cause the Shards to be stopped (the *ShardStopped* is sent immidiately without forwarding HandOff to a shard).
This leads to situations, where you can have multiple, same entities running in the same cluster.

Do you think that updating atomically both *shards* and *shardsByRef* would solve the problem (for example in the *getShard* method)? Or is the current behaviour valid for some scenarios that I'm missing here?

Cheers,
Marcin

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by patriknw** [comment]
You are correct. The regression was introduced by this refactoring: https://github.com/akka/akka/pull/17871
I'm trying to figure out the reason.

**Comment by patriknw** [comment]
@msosnicki There is one test failure when I move the update of `shards`. That is because it should try to buffer messages during the startup and not enqueue them to the mailbox, which will be lost when persistent recovery fails. At least that is what the test relies on.

I suggest that we update of `shardsByRef` and `shards` together again, in `getShard`. Then we also introduce a new `var startingShards: Set[ShardId]` for the purpose of keeping track of shards that are in progress of starting up, i.e. `getShard` should return `None` when its in that set.

Would you like to do the honors of creating a pull request with the fix?

**Comment by msosnicki** [comment]
@patriknw Great, thanks for the update and the reasoning behind the current implementation. 
I will implement the solution you suggested and create a pull request.

**Comment by msosnicki** [comment]
@patriknw 
I added the code changes that you've mentioned, and all the tests seem to pass fine. 
But I have the problem with writing tests. I try to find a way to slow down the PersistentShard recovery, as I have to test against the scenario that allowed me to reproduce the bug:
* the recovery times for the PersistentShard are really slow
* move a *Shard1* to a *Node1*
* during recovery a HandOff is received for the *Shard1* by *Node1*
* check if the actor that was recovering is dead

What would be the best approach to that? Blocking communication from that *Node1* with the journal (even if journal is on a different node than controller) looks like a bad idea, because the controller can't coordinate the HostShard & HandOff message for the shard. 

Thanks for any hints :)

**Comment by patriknw** [comment]
Yeah, that is a tricky one to test. Perhaps you can use the [SteppingInmemJournal](https://github.com/akka/akka/blob/master/akka-persistence/src/test/scala/akka/persistence/journal/SteppingInmemJournal.scala)?
If it turns out to be too complicated we have to accept that we don't have a test for it.

**Comment by patriknw** [comment]
To be able to use the SteppingInmemJournal in multi-node tests you would need the new JournalProxy https://github.com/akka/akka/pull/18949

**Comment by msosnicki** [comment]
Thanks for your suggestions. 
When do you thing the Journal Proxy feature will be in master? I could then create the test that you've mentioned. I would have to move ```SteppingInmemJournal``` out of test sources though.
For now, the only idea that I have for testing this would be to send a ```HandOff``` and immidiately after check the state with ```GetShardRegionState```. After the fix, the state would already have the shard, whereas before it would still be recovering. I don't think that this test would add any value though, it's testing some internals that currently are related to the bug, but might not be in the future. Also, it's not deterministic, it's relying on receiving ```GetShardRegionState```faster than ```PersistentShard``` recovery.

Would you be happy to accept the lack of the test for now? Once the JournalProxy is merged, I can try to test it with SteppingInmemJournal

Thanks!

**Comment by patriknw** [comment]
I agree, that test adds to much complexity. Let's skip it.

**Comment by msosnicki** [comment]
Ok. I created a pull request [18984](https://github.com/akka/akka/pull/18984). Thanks.

**Comment by ktoso** [comment]
Thanks a lot for the PR @msosnicki!
