### ISSUE TITLE
Body Part Parser contains hardcoded config defaults, should be loaded from reference.conf

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18958]
As mentioned here https://github.com/akka/akka/pull/18941#discussion_r44984789
It's as simple as making the same config object populated form reference.conf instead of defaults in code.

**Comment by raam86** [comment]
In reference.conf `maxHeaderValueLength` is 8k, however the constructor expects an Int and so does the require check. Should I just add a comment that it is in (kilobytes?)

**Comment by ktoso** [comment]
What's to be done here is mostly explained in the comments here: https://github.com/akka/akka/pull/18941#discussion-diff-44984789

Find the TODO (on branch `release-2.3-dev`) and move the hardcoded defaults to ones loaded from reference.conf.

**Comment by raam86** [comment]
@ktoso I have read and I think I understood the link however the type in the config mismatches the config in reference.conf file (8k is a String and 8 is an Int)

**Comment by ktoso** [comment]
"8k" in reference.conf is not a string, it's a number. `k` means thousand. Learn more about it here: https://github.com/typesafehub/config :)

**Comment by raam86** [comment]
:0 silly me. Not sure why I am getting
```
Cause: com.typesafe.config.ConfigException$WrongType: reference.conf: 273: max-header-value-length has type STRING rather than NUMBER
```

**Comment by ktoso** [comment]
that's weird, pretty sure `k` is understood by typesafe config. What's the code that throws

**Comment by raam86** [comment]
I've added the code that throws to read frim config. 
Naked ints work with getInt. 
I tried getInt and getNumber with the same result.  
I will look further into it.

**Comment by raam86** [comment]
Aha. Seems like only getByte parses sizes

'''
getBytes(java.lang.String path)
Gets a value as a size in bytes (parses special strings like "128M").
'''

**Comment by ktoso** [comment]
:+1: glad you found it, sorry I did not remember about getBytes imediadtly

**Comment by rkuhn** [comment]
@johanandren this should be closed, right?

**Comment by johanandren** [comment]
I think so
