### ISSUE TITLE
Sharding is using only latest snapshot

### ISSUE THREAD

**Issue by jsuchenia** [akka/akka#18955]
Sharding is using a snaphots, so for a very dynamic sharding configuration we have a lot of snaphosts, where for a recovery only a latest one will be used.

I think that after successful snapshot creation shard should delete the previous one.

Or even better, we should have a common solution that after successful snapshot all the previous journaled messages and snaphosts should be deleted

**Comment by patriknw** [comment]
sounds good

**Comment by patriknw** [comment]
I mean, deleting old snapshots sounds good, I'm against all deleting events.

**Comment by jsuchenia** [comment]
@patriknw Will they ever be used? When you have latest snapshot only this snapshot and messages created after that..

**Comment by patriknw** [comment]
Snapshots should only be seen as an optimization, the truth is in the events. There will not be any extreme volumes here so there is no reason to remove events.

**Comment by patriknw** [comment]
done
