### ISSUE TITLE
[akka-http] Java DSL cannot create custom media types

### ISSUE THREAD

**Issue by jypma** [akka/akka#18953]
In `akka.http.javadsl.model.MediaTypes`, ([source](https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/java/akka/http/javadsl/model/MediaTypes.java#L185)) there's the method
```
    public static MediaType custom(
            String mainType,
            String subType,
            boolean compressible,
            akka.http.scaladsl.model.MediaType.Encoding encoding,
            Iterable<String> fileExtensions,
            Map<String, String> params) { ... }
```
But it's not possible to refer to a `akka.http.scaladsl.model.MediaType.Encoding` from Java, since it's a nested object. When trying to refer to e.g. `Encoding.Binary`, all Java compilers complain with _The nested type akka.http.scaladsl.model.MediaType$Encoding$Binary$ cannot be referenced using its binary name_.

The particular encoding case objects can probably be declared in some constants inside javadsl `MediaTypes` directly.

**Comment by ktoso** [comment]
Thanks for reporting! Seems like a bug indeed, we'll provide java api.

**Comment by ktoso** [comment]
// cc @jrudolph @sirthias in case I missed something

**Comment by rkuhn** [comment]
@sirthias didn’t you fix this recently?

**Comment by ktoso** [comment]
Oh good catch, I can quickly check...

**Comment by sirthias** [comment]
Yes, the signature of `akka.http.javadsl.model.MediaTypes.custom` now looks like this:

```java
public static MediaType custom(String value, boolean binary, boolean compressible)
```

So I think it should be usable from the Java side.

**Comment by ktoso** [comment]
Yup, all good AFAICS
