### ISSUE TITLE
High level Java API for authentication and authorization

### ISSUE THREAD

**Issue by johanandren** [akka/akka#18966]
Neither `RequestVals` nor `AllDirectives` contains anything like the `SecurityDirectives` in the Scala API.

**Comment by jrudolph** [comment]
There's https://github.com/akka/akka/blob/release-2.3-dev/akka-http/src/main/scala/akka/http/javadsl/server/values/HttpBasicAuthenticator.scala

and https://github.com/akka/akka/blob/release-2.3-dev/akka-http/src/main/scala/akka/http/javadsl/server/values/OAuth2Authenticator.scala

**Comment by johanandren** [comment]
Sorry, my bad not looking in the right places!

**Comment by ktoso** [comment]
Should have been closed back then
