### ISSUE TITLE
WS: Configurable setting `closeTimeout` for akka-http websocket client

### ISSUE THREAD

**Issue by TimothyKlim** [akka/akka#18970]
I have noticed that akka-http ws client (2.0-M1) is closing connection by hard coded parameter (closeTimeout = 3.seconds) ignoring a client settings:
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebsocketClientBlueprint.scala#L40
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/ws/Websocket.scala#L34

Another question is: does akka-http websocket client support idle/long-time connections? Because now it drops a connection to docker after 3 seconds since a last received data.

Thanks.

**Comment by ktoso** [comment]
Looks like a bug, thanks for noticing @TimothyKlim! Let's remove the default param there to avoid such mistakes.

> Another question is: does akka-http websocket client support idle/long-time connections? Because now it drops a connection to docker after 3 seconds since a last received data.

I'll have to verify, not sure from the top of my head.

**Comment by TimothyKlim** [comment]
Hi @ktoso, I forgot about connection closing automatically when source is empty.
If I add a promise to source then it works as expected:
```scala
val closeP = Promise[TextMessage]()
// ...
.runWith(Source(closeConnectin.future).drop(1), Sink.foreach(println))
// ...
```
Sorry for disturb you.

**Comment by johanandren** [comment]
The last comment is what we are looking into in #19957

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
