### ISSUE TITLE
Deafness of akka-remote over tcp 

### ISSUE THREAD

**Issue by lemmsh** [akka/akka#18975]
Hi.

I have a bunch of actor systems running on different hosts. Let's name them A, B, C, D;
each system sends messages to all of the others. 

Sometimes under heavy load some system stops to receive messages from one of the others. For instance the A system sends messages to and receives them from B, but B does not receive anything from A. B does receive everything from C and D, and A receives everything from anyone.

The deafness seems more likely to happen after the A is restarted, but I've seen it once without any restart. 

I didn't manage to reproduce it in a synthetic test, but I've added some logging into the akka code and reproduced it in our test environment:
* `TcpSupport.scala: akka.remote.transport.netty.TcpAssociationHandle#write`, I've logged sending together with local and remote sockets. 
* `TcpSupport.scala: akka.remote.transport.netty.TcpHandlers#onMessage`, I've logged socket addresses as well.

So, on the B system I could see that `TcpHandlers::onMessage` is executing, so messages from A are delivered to B. But I didn't see any logs from `akka.remote.DefaultMessageDispatcher` (RemoteMessage...). In healthy systems I can see both logs subsequently.

There are some disassociation events in the system logs, but they all are like
`Association with remote system ... has failed, address is now gated for [5000] ms. Reason: [Disassociated]` and not necessary mention the B system (they appear after restarts).

I've checked existence of 
`system/endpointManager/reliableEndpointWriter-akka.tcp<the A system address>/endpointWriter/endpointReader-akka.tcp<the A system address>` by actorSelection and it responses to `Identify()`. So it seems to be running.

All this looks like a bug somewhere in the EndpointReader logic or around. Please tell me what else I can check to narrow the scope 

Thanks,
Pavel

**Comment by viktorklang** [comment]
Hi Pavel,

What version?

**Comment by lemmsh** [comment]
2.3.14, built for scala 2.11. I have tried to tell Kill to the endpointReader and this brought the system back to a normal state. So I suspect the problem is there

**Comment by drewhk** [comment]
Interesting. Thanks for reporting!

**Comment by lemmsh** [comment]
I cannot reproduce it anymore. The only difference now is that our network is working better, so transport layer may be a kind of trigger. I'll write more debug here as soon as I have any

**Comment by patriknw** [comment]
We will not be able to find the problem without more information or a way to reproduce. Please reopen or create new issue if you find something more.
