### ISSUE TITLE
After sharding handoff the shard allocation should be lazy

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18978]
I'm pretty sure it was lazy (first message) originally, but when checking the ShardCoordinator it looks like it's not. Perhaps it was changed due to the remember-entities feature. I think it should be lazy when remember-entities is not used.

Also verify that we don't grow the State when shards are deallocated (`unallocatedShards`).

**Comment by rkuhn** [comment]
This should be closed, right?

**Comment by ktoso** [comment]
No, it's missing a full blown integration test that will be added next week.

**Comment by rkuhn** [comment]
@ktoso please create a new ticket for the integration test

**Comment by ktoso** [comment]
Okey, here it is: https://github.com/akka/akka/issues/19033

**Comment by patriknw** [comment]
No, you are mixing it up with the other issue about BackoffSupervisor

**Comment by ktoso** [comment]
Ouch, yes indeed; sorry about that
