### ISSUE TITLE
Attempt replacing immutable.Queue with ArrayDeque

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18994]
In HTTP we use an immutable.Queue in the internals, benchmark and replace with https://docs.oracle.com/javase/8/docs/api/index.html?java/util/ArrayDeque.html if it indeed is faster.

> This class is likely to be faster than Stack when used as a stack, and faster than LinkedList when used as a queue.

See https://github.com/akka/akka/pull/18979/files#diff-623ef36775342f2db6b86855f7ffea64R154

_// Somewhat of a pet project I want to try out_

**Comment by drewhk** [comment]
Makes sense

**Comment by ktoso** [comment]
I tried this a bit ago and actually was not able to prove an immediate improvement, though perhaps the benchmark is too noisy (commit is: https://github.com/ktoso/akka/commit/e34aac61d6a4033e26efa996d98daedf75dea61a ).

```
[info] Benchmark                                                 (it)       Mode  Cnt      Score      Error  Units
[info] BodyPartParserBenchmark.large                       ArrayDeque       thrpt   20   1059.961 ±  270.834  ops/s
[info] BodyPartParserBenchmark.two                         ArrayDeque       thrpt   20  15412.878 ± 3080.270  ops/s
[info] BodyPartParserBenchmark.withoutEntityMissingHeader  ArrayDeque       thrpt   20  20224.935 ± 2357.290  ops/s
[info] BodyPartParserBenchmark.large                       immutable.Queue  thrpt   20   1777.642 ±  144.613  ops/s
[info] BodyPartParserBenchmark.two                         immutable.Queue  thrpt   20  28597.521 ± 2014.324  ops/s
[info] BodyPartParserBenchmark.withoutEntityMissingHeader  immutable.Queue  thrpt   20  25808.112 ± 2702.026  ops/s
```

So it needs more measurements before we apply or drop this one.

**Comment by ktoso** [comment]
Closing for now, should come out of normal performance investigatieon
