### ISSUE TITLE
HTTP: Make sure we're documenting complete(actor ? question)) properly

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18990]
There is a number of questions and best practives around this pattern.
Even though some might argue "don't use ask", it often is a very convenient way to start out or keep simple APIs like `(db ? query(...)).mapTo[]` around.

**Comment by drewhk** [comment]
Maybe we should also do an overload reduction for `complete` like we did for streams?

**Comment by ktoso** [comment]
`complete` is using the magnet pattern - there is "one" overload, yet there are infinite numbers of actual overloads ;-)

I don't think we can / should touch its signature - the way it is now you can "complete with anything that there is a response marshalling in scope; it can be futures, strict collections, streams (soon) etc". This ticket is more about documenting the entire "here's how you use ask, and here's how you reply to it from an actor". People coming into Akka through Akka HTTP, may not be completely familiar with Actors etc.

**Comment by drewhk** [comment]
argh, ok.

**Comment by ktoso** [comment]
No worries :) I know HTTP is pretty weird/specific at places, your suggestion was very good but very streams-api influenced :smile:

**Comment by ktoso** [comment]
This is basically the per request actor, closing as duplicate of https://github.com/akka/akka/issues/18569
