### ISSUE TITLE
Make sure that Akka Http only exports the API types

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#18993]
Go through the javadoc/scaladoc and make sure that internal types don't leak to the user.

**Comment by ktoso** [comment]
Good thought; do you mean in general or did you notice a specific leakage that made you open this ticket already?

**Comment by viktorklang** [comment]
@ktoso I meant in general, given how many types it currently exports we need to make sure that we're not adding insult to injury by exporting things that shouldn't be exported. :)

**Comment by ktoso** [comment]
Yep, definitely something to do soon.

**Comment by ktoso** [comment]
cc @rkuhn technically something to do before 2.4.2 or it's too late.

**Comment by drewhk** [comment]
I updated the labels to reflect this. Can be moved out if we decide to pass.

**Comment by johanandren** [comment]
The only offender I found:
`akka.http.scaladsl.Http.HostConnectionPool` takes a `akka.http.impl.settings.HostConnectionPoolSetup` to its public constructor. I don't think it is meant to be instantiated outside of akka-http so perhaps we could just `private[http]` it? @ktoso

**Comment by ktoso** [comment]
It's not meant to be created by users however it is exposed API and they can/should call shutdown on it for example. So its not really internal in that sense. Is just the type linked as a `class name`? If so that's fine.
