### ISSUE TITLE
HTTP: RequestBuilder: blocking marshalling of RequestEntity

### ISSUE THREAD

**Issue by markusjura** [akka/akka#18992]
The [RequestBuilder](https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-2.0-M1/akka-http/src/main/scala/akka/http/scaladsl/client/RequestBuilding.scala#L47) can be used to create an `HttpRequest` object. One `apply` method uses `Await.result` to marshal the scala object to a `RequestEntity`. This means that this blocks the current thread on the execution context provided: https://github.com/akka/akka/blob/releasing-akka-stream-and-http-experimental-2.0-M1/akka-http/src/main/scala/akka/http/scaladsl/client/RequestBuilding.scala

Instead we could return a `Future[RequestEntity]` for the apply methods which pass in the `content` as `T` and not directly as `RequestEntity`.

**Comment by ktoso** [comment]
Thanks for reporting; I'm not sure we'll want to change that, let's see about pros and cons:

The `RequestBuilding` trait is designed to be simple to use for writing tests for example, like so: `Get("/", Some(value)) ~> routes ~> check {}`. This is it's primary use.

If we make it return a Future, we'll  have to block in the `~>` anyway, since we want to run the `check{}` phase still on the same thread - since otherwise the test would complete before we apply our checks.

Do you have a specific case in mind where the blocking here really hurt?

**Comment by markusjura** [comment]
Thanks for explanation. I wasn't aware that the RequestBuilder only should we be used during tests.

We use the RequestBuilder currently in ConductR to send HTTP requests to the ConductR server. So you are recommending to use the `HttpRequest` case class directly and therefore do the marshalling to a `RequestEntity` beforehand?

**Comment by ktoso** [comment]
`RequestBuilding` is in this weird state of not being an official client api, yet on the other hand we don't have anything better than it. 

Do you actually see the blocking there be a problem, or are we optimizing too early?

If you want async construction you can: `Marshal(value).to[...] map { v => HttpRequest(entity = v) }` or something like it?

**Comment by markusjura** [comment]
Yes, we will use `Marshal(value).to[...]` in ConductR instead. My main point was that we shouldn't provide a API in Akka HTTP which blocks underneath. As long as the RequestBuilder is not an official API and is mainly used in testing I guess it is fine to leave it as it is.

**Comment by drewhk** [comment]
If it is not clear then it should be documented that this is a testing class. Maybe put it into test scope?

**Comment by markusjura** [comment]
> If it is not clear then it should be documented that this is a testing class. Maybe put it into test scope?

+1 (to put it into the test scope and optionally to document it)

**Comment by ktoso** [comment]
We have tickets around that: https://github.com/akka/akka/issues/18550 and most notably https://github.com/akka/akka/issues/16856

It is not clear yet if RequestBuilding becomes the client side, or if we remove it.

**Comment by jrudolph** [comment]
In spray, we had the [Transformer syntax](https://github.com/spray/spray/blob/master/spray-httpx/src/main/scala/spray/httpx/TransformerPipelineSupport.scala) which allowed to compose both synchronous and Future-returning functions. Together with [`marshal`](https://github.com/spray/spray/blob/master/spray-httpx/src/main/scala/spray/httpx/marshalling/package.scala#L28) it allowed to specify client side pipelines quite nicely.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
