### ISSUE TITLE
DistributedPubSub: put messages without route into the dead letters

### ISSUE THREAD

**Issue by maqdev** [akka/akka#19009]
Currently if you publish message using `publishToEachGroup` and there is no subscribers on this topic that message is just lost. It would be much better to be able to handle this situation and put the message into the dead letter for the further debugging and processing.

To achieve this result for myself I created a new class that inherits `DistributedPubSubMediator` and implemented it like this:

```
override def publishToEachGroup(path: String, msg: Any): Unit = {
    val prefix = path + '/'
    val lastKey = path + '0' // '0' is the next char of '/'
    val hasAtLeastOneReceiver = registry.exists(_._2.content.range(prefix, lastKey).nonEmpty)
    if (hasAtLeastOneReceiver) {
      super.publishToEachGroup(path, msg)
    } else {
      context.system.deadLetters ! DeadLetter(msg, sender(), context.self)
}
```

Also there is other sending methods that have to be modified like `Send`, `SendToAll`, `Publish`, etc.

**Comment by rkuhn** [comment]
one remark: “further processing” sounds scary—you do know that deadLetters are not reliable, right?

**Comment by maqdev** [comment]
Yes, I do :-)

**Comment by rkuhn** [comment]
good :-)
