### ISSUE TITLE
FlowOps.intersperse(delimeter: Out): Repr[Out, Mat]

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#19002]
Add an `intersperse` combinator (and associated AST node) to inject delimeters into a stream.

**Comment by ktoso** [comment]
I did that already though? https://github.com/akka/akka/pull/18734/files#diff-a4d5987f74d69093ccf1264366e4bbc1R466

**Comment by viktorklang** [comment]
ERMAGHERD! I should've checked the current release-2.3-dev! *doh*

**Comment by ktoso** [comment]
No problem :-)

`release-2.3-dev`
![](http://i.ytimg.com/vi/eh7lp9umG2I/hqdefault.jpg)

**Comment by viktorklang** [comment]
Heeeyeeeeyeeeyeye, heeeyeeye, I said Hey! What's going on?
