### ISSUE TITLE
A void source

### ISSUE THREAD

**Issue by jroper** [akka/akka#19007]
Akka streams provides an empty source, but this terminates the stream immediately.  Some APIs expose a way to create a client that returns a Flow, such as Akka's own `TCP` API.  If you only want to read from these APIs, the only option that Akka streams currently gives out of the box is to feed `Source.empty` into it.

This is problematic, since `Source.empty` will complete the stream immediately, triggering closure the connection, and preventing anything from reading.  Even for TCP, which supports half closure, it's still a problem, as not all servers implement half closed support, a notable example is Netty 3.x, which does not support half closure at all, and even in Netty 4.x half closure is turned off by default, so when Netty detects that the incoming stream is closed, it also closes the outgoing stream.  But then there are many protocols that have no concept of half closed, for example WebSockets (although WebSockets does go over TCP, graceful closure of a WebSocket requires some protocol negotiation first, meaning you can't just half close the TCP socket, and this negotiation does not support half closure).

So `Source.empty` is not sufficient for working with APIs that return `Flow` when you only want to read.  What is rather needed is a void source, that is, a source that does not send any signals at all.  This use case has come up for me several times in a number of different circumstances, I think it's enough to warrant built in support for it in Akka streams.

Here's the current crude implementation that I use:

```scala
def voidSource = Source(Promise[Nothing]().future)
```

**Comment by hepin1989** [comment]
` that is, a source that does not send any signals at all.` like `Source.never`?

**Comment by jroper** [comment]
I was thinking `Source.void`, though a different method would be needed for Java.

**Comment by jrudolph** [comment]
There's `Source.maybe` (previously called `Source.lazyEmpty`) for that purpose: https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L264

**Comment by drewhk** [comment]
Yes 1.0 has `Source.lazyEmpty` and 2.0 has `Source.maybe`.

**Comment by jroper** [comment]
Not sure how I missed `lazyEmpty`, thanks!

**Comment by drewhk** [comment]
No worries, we probably will need some table or high level overview of the available stuff there.
