### ISSUE TITLE
HTTP: Rewrite SlotProcessor (and friends) to GraphStage to simplify it

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19001]
SlotProcessor, and other ActorProcessors implemented manually can be replaced with GraphStages, we should do so as they're less error prone. Start with this one: https://github.com/akka/akka/pull/18973/files#diff-73aae9988dae4fe8c6dd320291984c74R91

In general grep for "ActorPublisher with ActorSubscriber" (or the other order), we'll want to get rid of all of these.

**Comment by ktoso** [comment]
This was done AFAICS

**Comment by 2beaucoup** [comment]
Doesn't `SlotProcessor` still `extends ActorSubscriber with ActorPublisher`?
