### ISSUE TITLE
sharding ddata + rememberEntries => entities not started after a restart.

### ISSUE THREAD

**Issue by patriknw** [akka/akka#19003]
Reported in another unrelated issue: https://github.com/akka/akka/issues/18936#issuecomment-158891099

it looks like actors in a shard were not started after a restart.

If you are using the ddata mode then the coordinator do not know about shards right after restart. But rememberEntries flag force the shards to store info about entries. So ddata+rememberEntries is a kind of "lazy persistent shards" from some point of view. You need to send message to any entry inside the persistent shard to init the replay process of this shard.

This is rather confusing, and if it can't be fixed it should be documented.

**Comment by jaapterwoerds** [comment]
Is there a way / workaround so that we can trigger loading of shards by addressing the shards instead of individual entries?

**Comment by patriknw** [comment]
This will be fixed by #22154
