### ISSUE TITLE
fill in `interpreter` from ThreadLocal during stage logic creation

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19015]
otherwise async input may see `null`

**Comment by ktoso** [comment]
Oh, good catch.

**Comment by rkuhn** [comment]
Further investigation shows that this is fundamentally impossible. We must instead warn people against sharing callbacks and StageActorRefs from the constructor—unfortunately we cannot forbid the use of methods from certain places.

**Comment by ktoso** [comment]
Ah nein!

**Comment by rkuhn** [comment]
Okay, so what we’re doing instead is to throw an exception if the stageActorRef is accessed while `.interpreter == null` (initialization with a behavior is allowed, though). For ordinary getAsyncCallback there is nothing we can do.

**Comment by drewhk** [comment]
@rkuhn is there any extra action necessary here?

**Comment by rkuhn** [comment]
no, that exception actually does exist already (albeit with a bit more generic error message)
