### ISSUE TITLE
DistributedPubSub - race condition regarding children/topic actor liveness

### ISSUE THREAD

**Issue by Adebski** [akka/akka#19017]
When new subscriber arrives to `DistributedPubSubMediator` for given topic the child/topic actor is looked up using  `context.child(encTopic)`, if actor exists message is forwarded, if not the child actor is created, registered in `registry` and then message is forwarded. 

Topic actors stop themselves when all their subscribers are either terminated (death watch by topic actor on subscriber) or they just unsubscribe themselves from the topic.

There could be a situation where
* `Subscribe` message is sent to mediator from `SubscriberA`
* At the same time `SubscriberB` is terminated and this message arrives to topic actor.
* Topic actor stops itself using `context.stop(self)`
* At the same time parent/mediator actor performs lookup of child and decided that topic actor is alive and forwards him `Subscribe` message
* `Subscribe` message goes to dead letters because topic actor is already dead, mediator does not inform subscriber that something went wrong and/or do not try to retry sending Subscribe message to new version of topic actor.

According to http://stackoverflow.com/questions/23629159/get-or-create-child-akka-actor-and-ensure-liveness the solution would be to send kind-of Terminated message to mediator so `Subscribe` and `Terminated` messages are processed serially, also watching out for the fact that stopping actor is async operation so even if we invoke `context.stop(child)` from context of parent there is no guarantee that path is immediately.

**Comment by ktoso** [comment]
Thanks for reporting. We'll follow up here shortly.

// cc @patriknw

**Comment by ktoso** [comment]
Having that said, the Akka pub-sub has the same guarantees as usual Actor messaging - messages can get lost, if you want to guarantee they don't, you need to use `AtLeastOnceDelivery` or build ACKs into your protocol. It seems that's what you're after here?

**Comment by Adebski** [comment]
I was not thinking about total guarantee, more like reducing the possibility of such by handling the termination of a child actor in a way that eliminates this particular factor from a chance of losing a message.

**Comment by patriknw** [comment]
I agree with @Adebski
This is about subscription messages, which we don't handle in the best possible way.

**Comment by Adebski** [comment]
Ok, my idea is to store some additional state inside mediator that basically says to us "for how many subscribers we sent `Subscribe` to `Topic` actor but not received confirmation". If we have this kind of information we can do something like:

* when `Prune` message arrives to Topic actor and it sees that for this point in time it has no subscribers it sends some new kind of message to the parent (e.g. `PruneNotification`)
* parent receives `PruneNotification` from `Topic`. If for given topic we are not waiting for `Subscribed` message it means that we can kill topic actor w/o fear of losing confirmation/subscription messages. We can then unwatch topic actor, call `context.stop(topicActorRef)` and remove information about this actor from registry.
* on the other hand if during the time it took to deliver `PruneNotification` message to mediator some new subscriber arrived we can see it and we just ignore the `PruneNotification` message and already existing topic actor will accept new subscription and everything will work fine.

Now there is single problem left: we could try to create new topic actor before path to the old one is free. We could buffer messages to given topic until we receive Terminated message or somehow make sure that each topic actor has unique path. My idea was to create topic actor not like `context.actorOf(Props(classOf[Group], emptyTimeToLive, routingLogic), name = encGroup)` but also add version number from `nextVersion` call (we still have normal topic names as mappings in `registry`). 

Personally I was thinking about second approach and don't check if we have children left using `context.child(encTopic)` but just check our local `registry` if we want to make sure that `Topic` actor for given `Topic` is alive.

Also it seems that there is the same problem with `Topic`/`Group` actors because for some group we are just checking if child managing given group exists so the same bit of state would have to be introduced to `Topic` actor when managing `Group` child actors.

**Comment by patriknw** [comment]
Shouldn't this be solved in the same way as it is solved in Cluster Sharding, when an entity actor sends a  `Passivate` message to the parent? Incoming messages are buffered until the child is terminated, and then if there are any buffered messages they are delivered to a new child actor.

**Comment by Adebski** [comment]
Yes, it is also possible to store messages during transition period and then transmit them to receiver. I wanted to find a solution that would not involve some intermediate message buffer because then you have to worry about storing them (preferably with some max buffer size) and dropping them in case configured buffer size is reached.

Assuming that usually we won't have to store many messages in the intermediate buffers so the chance of dropping message due to reaching limit of configured buffer size is small I think that both of the solutions will solve the race condition problem.

**Comment by patriknw** [comment]
We know that the stopping will be quick so there should not be a problem with buffer limits.

**Comment by drewhk** [comment]
This is actually in progress right?

**Comment by patriknw** [comment]
yes
