### ISSUE TITLE
BackoffSupervisor can't be used with ClusterSharding passivation

### ISSUE THREAD

**Issue by masterzen** [akka/akka#19016]
Despite 3f3642337eeaf90c66e550ff6848723ec3527145 that implements forwarding back messages from the child to the parent of the `BackoffSupervisor` (which is useful for passivation), this can't work because:
1. The actor (protected by a `BackoffSupervisor`) needs to stop
2. it sends a `Passivate` message to its parent `BackoffSupervisor`
3. the parent `BackoffSupervisor` forwards it to the `Shard`
4. the `Shard` sees the `sender()` as the real actor  and not the `BackoffSupervisor` and finally executes calls [passivate](https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala#L155)
5. which in turn ends in this code with `entity` as the original passivation starter actor (the child of the `BackoffSupervisor`):

``` scala
  def passivate(entity: ActorRef, stopMessage: Any): Unit = {
    idByRef.get(entity) match {
      case Some(id) if !messageBuffers.contains(id) ⇒
        log.debug("Passivating started on entity {}", id)

        passivating = passivating + entity
        messageBuffers = messageBuffers.updated(id, Vector.empty)
        entity ! stopMessage

      case _ ⇒ //ignored
    }
  }
```

The forwarded `sender()` can't be in the `idByRef` Map, since it's not the direct child of the `Shard` but the child of the `BackoffSupervisor`, so passivation is not started.

A related issue, if this aforementioned one is solved is that the real actor receiving the passivation return message will have to stop itself, but also to stop its ancestor (the `BackoffSupervisor`) otherwise this one will restart it.

In a word, passivation needs to be built-in in the `BackoffSupervisor` (or in a Cluster Sharding specific supervisor system), for it to work correctly.

**Comment by ktoso** [comment]
(note to self - keeping open until test added)

**Comment by nvollmar** [comment]
strange to see this in the release notes when the pull request has been merged 3 years ago already?

**Comment by chbatey** [comment]
The PR was #25933

**Comment by nvollmar** [comment]
Right, thanks for the hint. Did I understand correctly that we now should set `.withFinalStopMessage(_ == StopMessage)` to get passivation working properly?

**Comment by nvollmar** [comment]
Right, thanks for the hint. 

I looked through the change and tried to understand the impact of it. It only affects the backoff type `StopImpliesFailure` but the API suggests it applies to `RestartImpliesFailure` as well.

To have a more self-documenting API I would have expected it to be on the `StopImpliesFailure` as a case class instead or at least the documentation should make this more obvious.

**Comment by patriknw** [comment]
@nvollmar thanks for feedback. Could you open a PR with the improvements?

**Comment by nvollmar** [comment]
@patriknw I'll look into it

**Comment by nvollmar** [comment]
@patriknw I've created a proposal: PR #26135
