### ISSUE TITLE
StageActorRef is local only currenctly

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19014]
We decided to keep the `StageActorRef` currently a "local only, special ActorRef".
We can make it work with remoting (register it in the ActorRefProvider), but opted not to do so currently.

This ticket is about making it not "local only".

**Comment by ktoso** [comment]
See this PR for details https://github.com/akka/akka/pull/18973
and here for a discussion :point_up: [November 25, 2015 4:01 PM](https://gitter.im/akka/dev?at=5655cd4263bfb30b58e45b8c)

**Comment by drewhk** [comment]
Just to document, the reason we opted to not do it is because it will need a 2.3.x and 2.4.x release to make a new internal API available. This will be done, but not before the M2 milestone.

**Comment by drewhk** [comment]
This is not possible to backport as it relies on features in akka-actor.
