### ISSUE TITLE
Application/octet-stream doesn't support compressing

### ISSUE THREAD

**Issue by vans239** [akka/akka#19036]
I recently found that Media type application/octet-stream couldn't be gziped due uncompressible flag. What cause of such behavior? I didn't find any info in rfc. Thanks

**Comment by jrudolph** [comment]
I agree, the current compressibility heuristic seems inaccurate and a bit inflexible.

The current way to configure what to compress is by creating your own instances of `Gzip` or `Deflate` and pass a `MessageFilter` that suits your needs.

**Comment by vans239** [comment]
Thank's for idea of custom encoder))

**Comment by viktorklang** [comment]
For clarity, are we saying that:

~~~scala
val `application/octet-stream`                                                  = abin("octet-stream", NotCompressible, "a", "bin", "class", "dump", "exe", "lhx", "lzh", "o", "psd", "saveme", "zoo")
~~~

ought to be changed to:

~~~scala
val `application/octet-stream`                                                  = abin("octet-stream", Compressible, "a", "bin", "class", "dump", "exe", "lhx", "lzh", "o", "psd", "saveme", "zoo")
~~~

**Comment by vans239** [comment]
Yes, i mean this. But i don't sure that it should be changed to compressible. I want understand cause of such behaviour. For example, *.class could be compressed well.

**Comment by viktorklang** [comment]
@ktoso @jrudolph Thoughts?

**Comment by ktoso** [comment]
Seems valid, bumping to see if anyone objects.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
