### ISSUE TITLE
add Source.cycle

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19039]
There is a repeat def `Source.repeat[T](element: T)` and I think a `cycle` should be handy too ,as `Source.cycle[T](T:*)` .

`Sourcel.cycle(1,2,3)` will emit `1,2,3,1,2,3,1,2,3...`

**Comment by hepin1989** [comment]
I think I could implement that via `Source(() => Iterator.continually(Seq(1,2,3).flatten)`

**Comment by ktoso** [comment]
I was about to open a ticket about it yesterday :)
+1, I think it's very useful.

**Comment by viktorklang** [comment]
Or: `Source.repeat(Seq(1,2,3)).mapConcat(identity)`

**Comment by ktoso** [comment]
Random thought... I seem to remember Scala's Range was "pretty heavy" though can't recall completely in what way...? So since `javadsl.Source.cycle(1, 10)` wants to be the equivalent of `scaladsl.

**Comment by ktoso** [comment]
mis-clicked, sorry.

**Comment by viktorklang** [comment]
I don't want to be the person who is that person, but how about we name it `repeatAll` so that it autocompletes nicely?

**Comment by ktoso** [comment]
cycle seems to be Rx wording. I don't mind either of them.

**Comment by viktorklang** [comment]
I'm fine with `cycle` too, I was more concerned by the user.

**Comment by rkuhn** [comment]
Cycling is what I do sometimes (but not often enough) :-)

**Comment by agolubev** [comment]
is it similar to #16454?
