### ISSUE TITLE
add Pipe[T]

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19035]
```class Pipe[T] extends GraphStage[FlowShape[T, T]] ```

which will be useful to instead of ```Merge[T](1)/Broadcast[T](1)```

**Comment by drewhk** [comment]
What does this exatly mean? What should this stage do? Can you explain, or show a snippet how the usage should look like?

**Comment by hepin1989** [comment]
```
            val resultMerge = b.add(Merge[SubmitResult](3))
            val inputPipe = b.add(Pipe[OriginalData])
            // format: OFF
            inputPipe   ~>  verify   ~>  verifyBranch.in
                          resultMerge  <~  verifyBranch.left
                                           verifyBranch.right ~> enhance ~> persist ~> persistBranch.in
                                                                        resultMerge <~ persistBranch.left
                                                                                       persistBranch.right ~> notify ~> update ~> updateReceiptLogSink
                          resultMerge  <~  feedback           <~ persistedBroadcast
            // format: ON

            FlowShape(inputPipe.in,resultMerge.out)
```

**Comment by hepin1989** [comment]
I could use `Flow[T]` here too

**Comment by hepin1989** [comment]
I see there is code `akka.stream.stage.SourceStage` and `akka.stream.stage.SinkStage`,would be grate to have a `FlowStage` there，and maybe a `PipeStage` too.

**Comment by drewhk** [comment]
I still don't see it :( What does this Pipe do here? Flow[T] will give you exactly the same semantics.

**Comment by viktorklang** [comment]
Closing as Won'tFix until proven wrong :)

**Comment by hepin1989** [comment]
yes,this is not needed:),I forgot to close it.
