### ISSUE TITLE
FlowGraph is a little confusing name.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19037]
With the conversation on gitter:

>Why there is a word `Flow `in the `FlowGraph`?

And @rkuhn said:
>I would like to call it Graph but unfortunately that is not possible, the name clashes with trait akka.stream.Graph
So, what else should we call it?

We could create `Graph[SouceShape]` and `Graph[SinkShape]`from a `FlowGraph.create`,not just `Graph[FlowShape]`,in fact we could create arbitrary `Graph[ArbitraryShape] ` with that.

Code like `RunnableGraph.fromGraph(FlowGraph.create...)`  make you think you are creating a `RunnableGraph` from a `FlowGraph`.

So a little documenting about it or a rename to something like `StreamGraph` would be better,It confused me a while,thanks.
.

**Comment by viktorklang** [comment]
I'd want to have the name reflects its power level.

Perhaps: "CustomGraph" or something similar.

**Comment by rkuhn** [comment]
Hmm, that's also quite good. Keep the good suggestions coming, people!

**Comment by johanandren** [comment]
+1 (I started the same discussion a couple of days ago on akka-dev)

**Comment by ktoso** [comment]
-1 for `StreamGraph`, we don't use the word "Stream" in any of our APIs.
If we find some nice name I'd be ok with changing from FlowGraph though

**Comment by johanandren** [comment]
I first thought that `CustomGraph.create` sounded really good, because you are creating a custom graph. But then we talk about the simple APIs as `Flow`s in the docs, and what are we creating here if not custom Flows by way of a graph, so now I'm not so sure that `FlowGraph` is so bad any more...

**Comment by rkuhn** [comment]
Looking up synonyms for “composite” I find “complex”, and I like that a lot: it signals that these graphs are not the “simple” ones, they are one level up.

So, it is time to cast your veto or forever hold your peace: I propose *ComplexGraph.create()*.

**Comment by drewhk** [comment]
I was thinking `Network`. Even though it can be confused with computer network I don't think its that bad. `ComplexGraph` is not bad either, and it already conveys that it is complex, so use it with care.

**Comment by viktorklang** [comment]
Pardon my French, but to me, this is not about coming up with the most semantically correct name, it's about what our users will understand when they read it. `Network` would not score high here.

`ComplexGraph` does have a nice ring to it, and someone would hesitantly go and create something complex, i.e. it has a nice deterrence effect.

**Comment by drewhk** [comment]
I think it is simply not true that a name can completely convey all the semantics of a programming concept. In fact, sometimes more abstract names help because they establish less preconceptions that are likely wrong. If I imagine what mental image a Network brings up and what a `ComplexGraph`, for me `Network` scores better since I already see a graph with communication happening - i.e. it does not feel static to me.

**Comment by viktorklang** [comment]
@drewhk Sure, but the name is not for you and me, it's for the thousands of developers who'll be exposed to it. Just look at  Monad for an example of something that used a more abstract name with virtually 0 preconceptions and the number of monad tutorials out there. Association is powerful.

**Comment by drewhk** [comment]
I think it is way overrated. But if it is not for me and you, then why don't create a survey about names?

**Comment by viktorklang** [comment]
@drewhk We already have! See this Issue, anyone can come in here and :+1: a proposal or propose something for themselves. Given deadlines and lead time, we may have to make decisions based on partial knowledge though. Also, we must not forget the cost and risk of bikeshedding.

**Comment by hepin1989** [comment]
For that is what we are build ,I think `CustomGraph` is really a good name.`ComplexGraph` is not that really ,cause we could build a simple one with it too.

The new doc added by @drewhk  about `GraphStage` says that `GraphStage` is 
>a counterpart of the ``FlowGraph.create()`` method which creates new stream processing stages by composing others.

So I +1 for the `CustomGraph` here,cause it's more straightforward. 

@johanandren  For the old document about `Constructing Flow Graphs`http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M1/scala/stream-graphs.html#Constructing_Flow_Graphs ,after the rename,we could change the title to `Constructing Custom Graphs` which is more clear.

**Comment by drewhk** [comment]
But GraphStage is also a CustomGraph...

**Comment by hepin1989** [comment]
Then we are building `CustomGraph` with different way.

I think we should add document about how to build `CustomGraph` too,with both pros and cons.

**Comment by viktorklang** [comment]
@drewhk Agreed. ComplexGraph might be better to disambiguate.

**Comment by drewhk** [comment]
Let's have `ComplexGraph` then.

**Comment by rkuhn** [comment]
I’ll give it two more hours for people to weigh in and then I’ll start working on it.

**Comment by viktorklang** [comment]
@rkuhn Should be ample marination.

**Comment by ktoso** [comment]
Random observation: 
`ComplexGraph` is inviting all kinds of jokes about akka streams to happen... just sayin', it may not be a good name PR wise when we're trying to show how simple it is.

I can already see various competitors doing a joke out of it - "*yeah there's akka streams. but it's so complex they even had to put it in the name lol*". The conference world is full of taking things out of context, and followers of tech X, love such jokes to keep bashing tech Y.

**Comment by rkuhn** [comment]
The point is that we should not show this to beginners at all—it is supposed to be the second tier. “This is not simple and we won’t lie to you about that” is a message I would rather give than “it’s all rainbows and unicorns”. As long as we also make the actually simple things easy, which we are.

**Comment by jypma** [comment]
having a type `ComplexGraph` would have me try and find `SimpleGraph` or just `Graph`. Would there even an inheritance relationship (_is-a_) between `ComplexGraph` and `Graph`? If a complex graph _isn't_ a graph, it shouldn't have the same name. 

It seems to me that in the current code `FlowGraph` is just a namespace to house its `Builder`; it isn't really a type that can be instantiated. So shouldn't the discussion be about what to call that builder instead? And for that, I'd just go with `GraphBuilder` since there is only 1 builder for graphs in akka (well, 2, scala and java).

**Comment by ktoso** [comment]
That's very true I guess, and we're working continuously to keep people away from the need to drop down to it for most things... Maybe it's OK then. Just wanted to mention it so we take it into account explicitly.

**Comment by drewhk** [comment]
@jypma `FlowGraph` returns a `Graph` so the is-a relationship is kind of there. We decided to not call it builder because:

```
val graph = FlowGraphBuilder.create { builder => ... } 
```

You don't create a builder, you create a graph. And the builder is passed to you, it is not the FlowGraphBuilder at all which is the builder.

**Comment by viktorklang** [comment]
`BespokeGraph` *drops mic*

**Comment by hepin1989** [comment]
We could call it `CustomGraph` before if we don't have the powerful `GraphStage` shows up,now we need to deal with `GraphStage`. How about `GraphDSL`?

**Comment by jypma** [comment]
@drewhk It's still a function then though, so let's make that explicit through `apply()`, in Scala:
``` val graph = ComplexGraph { builder => ... } ```
and Java:
``` graph = ComplexGraph.build ( builder -> { ... } ) ```

**Comment by rkuhn** [comment]
now `GraphDSL` actually beats all the proposals for me, thanks!

**Comment by drewhk** [comment]
`GraphDSL` is nice.

**Comment by hepin1989** [comment]
@rkuhn The problem is that it live in `akka.stream.scaladsl`?
then we have `akka.stream.scaladsl.GraphDSL` and  `akka.stream.javadsl.GraphDSL`,maybe that should be fine.but as there is the `~>` and `<~`,maybe a `GraphDSL` would be fine.

**Comment by drewhk** [comment]
@jypma What is wrong with `create`? We don't use apply though because various overload hell scenarios.

**Comment by jypma** [comment]
@drewhk to me I expect `ComplexGraph.create { ... }` to return an instance of `ComplexGraph`, but you'd be getting a `Graph`. Hence I proposed using `apply` to make it look more like an arbitrary function / DSL part.

**Comment by drewhk** [comment]
`apply` is out of question unfortunately.

**Comment by viktorklang** [comment]
What about:

`akka.stream.scaladsl.Stream.customGraph()`?

**Comment by hepin1989** [comment]
>There are only two hard things in Computer Science: cache invalidation and naming things.
<br>
-- Phil Karlton

**Comment by drewhk** [comment]
naming cache invalidation?

**Comment by viktorklang** [comment]
cache invalidation of names

**Comment by jypma** [comment]
OK with `GraphDSL.create`. Like @rkuhn explained, this is also a DSL to create custom graph shapes i.e. DSLs.

**Comment by hepin1989** [comment]
@drewhk in akka context the other part shoud be `Exactly Once Delivery`.

**Comment by hepin1989** [comment]
>`Such graph is simple to translate to the Graph DSL since each linear element corresponds to a Flow, `

Found in the doc,maybe `GraphDSL` is good.

**Comment by viktorklang** [comment]
While we're still contemplating messing around with FlowGraph, I think it is the right time to also consider how we could solve the inconvenience of having to remember to explicitly import FlowGraph.Implicits AS WELL as remembering to have the builder being implicit.

**Comment by lshoo** [comment]
GraphDSL +1

**Comment by Mumutu** [comment]
GraphDSL + 1

**Comment by ktoso** [comment]
GraphDSL +1 :wink:

**Comment by rkuhn** [comment]
fixed in #19051
