### ISSUE TITLE
Akka HTTP examples still use ActorSystem.shutdown

### ISSUE THREAD

**Issue by analytically** [akka/akka#19046]
http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M1/scala/http/routing-dsl/index.html

```
...
bindingFuture
    .flatMap(_.unbind()) // trigger unbinding from the port
    .onComplete(_ ⇒ system.shutdown()) // and shutdown when done
}
```

**Comment by ktoso** [comment]
Yes, because Akka Streams are on Akka 2.3 currently, so terminate is not available.

This will change once we merge with the master branch and Akka Streams requires 2.4.

**Comment by ktoso** [comment]
It is a valid observation though, I've put it on the `stream-http-master` milestone, thanks @analytically!
