### ISSUE TITLE
make akka.dispatch.ExecutionContexts.sameThreadExecutionContext public

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19043]
I think this is handy ,currently it's `private[akka]`,but it extends `akka.dispatch.BatchingExecutor` which is  `private[akka]` too.

**Comment by ktoso** [comment]
I think it's very easy to shoot yourself in the foot by using it though, and I can imagine Akka newbies slapping it onto many problems... 
I had a team once who'd to "Future without threads" all the time, and that would cause deadlocks etc.

**Comment by ktoso** [comment]
cc @rkuhn

**Comment by drewhk** [comment]
I also wanted to use this exact same thing in another project of mine, and was very disappointed that I couldn't. I find it unlikely that people find this class by accident though (maybe some will, maybe looking at some Akka code, but I don't find this as a high risk).

**Comment by rkuhn** [comment]
It is a tricky thing; I’d be loathe to expose it under any different name than `sameThreadExecutionContextYesIKnowWhatIAmDoing`. Whoever wants to use it can do so already by just copying the source.

**Comment by drewhk** [comment]
Well, except benefiting from upstream bugfixes :)

**Comment by hepin1989** [comment]
Sometime we just need to use something like this to avoid context switch / reschedule for some work thing.Copy and paste work,but a default one will helps too,reduce some work for everyone.

**Comment by ktoso** [comment]
> reduce some work for everyone.

Yes and no. Refer to my point about people now knowing what they're doing (beginers) and slapping it onto everything where they get concurrency issues – I've seen such teams and making it easier to go down this wrong aproach is not something we should do.

If, however, you know what you're doing you'll find and copy that class, then it's your responsibility that you took it in, not "but Akka has it, so we'll use it!".

**Comment by drewhk** [comment]
I have to admit that I am starting to get tired of not exposing nice functionality because there might be possible abuse for them :(

**Comment by ktoso** [comment]
I don't know then... I'll leave it up to @rkuhn to make the call

**Comment by viktorklang** [comment]
:-1: It's a bandaid, the real fix is to improve the implementation of Future.

**Comment by hepin1989** [comment]
Then that's your work again :).

**Comment by viktorklang** [comment]
@hepin1989 I don't have much if any time to do that. You are of course free to donate your time or money to help out :)

I did make a bit of changes for 2.12 already: https://github.com/scala/scala/commit/fa0743c32338f147eaf7a5d69566bbc15d193f85

**Comment by hepin1989** [comment]
then how about close this issue,and maybe mention some practce in the `akka promise/future` doc section that ` for some small/simple task,should use the samethread/callerthread execution context to avaoid pertential overhead`?

**Comment by viktorklang** [comment]
@hepin1989 I'd advise against that because it is premature optimization. The tradeoff is not visible safety vs performance (http://blog.ometer.com/2011/07/24/callbacks-synchronous-and-asynchronous/), and I'd much rather have those who don't know how to make that tradeoff to be safe first and foremost so when performance is improved in the implementation, they get it for free. I'm sorry if that's not what you want to hear, but I've seen way too many people getting themselves into issues due to using sameThreadExecutionContext that it's not even funny :/

**Comment by hepin1989** [comment]
thanks for that,somethime like the `cast` or just convert from one model to another should use that.but as you just talk ,this need more careful too,thanks for that advice,and really helpful.

**Comment by hepin1989** [comment]
I think it should be fine to close this issue now.for two reason:
1. it's easy to implement
2. premature optimization may be cause issue ,and something like this especially need care.

useful link:http://blog.ometer.com/2011/07/24/callbacks-synchronous-and-asynchronous/

**Comment by viktorklang** [comment]
@hepin1989 As for casts, there is mapTo which casts the type without needing an EC.

**Comment by hepin1989** [comment]
@viktorklang It's for the java side,I see a lot of map then cast on the java api,we have a hyper code base.like the ask return an `Object` and then a map to cast.

**Comment by viktorklang** [comment]
tell the Java devs to use mapTo, static-import Util.classTag from here:
http://doc.akka.io/api/akka/2.3.14/index.html#akka.japi.Util$

and do

mapTo(classTag(String.class))

-- 
Cheers,
√

**Comment by hepin1989** [comment]
thank you.

**Comment by viktorklang** [comment]
You're most welcome!

On Tue, Dec 1, 2015 at 2:47 PM, kerr <notifications@github.com> wrote:

> thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/19043#issuecomment-160974666>.
>



-- 
Cheers,
√
