### ISSUE TITLE
Add deterministic `interleave` operation

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#19041]
Proposal:

Add a deterministic merge, which takes N elements per Source, in-order of inputs, and emits them downstream and then cycles/"wraps-around" the inputs.

Name: Interleave
Interleave definition:
> TELECOMMUNICATIONSCOMPUTING
> mix (digital signals) by alternating between them.

Example:

~~~scala
val s1 = Source(1 to 4)
val s2 = Source(5 to 8)
s1.interleave(s2, 2) isIsomorphicTo Source(Seq(1, 2, 5, 6, 3, 4, 7, 8))
~~~

Signature:
~~~scala
final class Interleave[T] private (val inputPorts: Int, val request: Int, val eagerComplete: Boolean)
~~~

Add inline representation to FlowOps:
~~~scala
def interleave[U >: Out, Mat2](that: Graph[SourceShape[U], Mat2], request: Int): Repr[U, Mat]
def interleaveMat[U >: Out, Mat2, Mat3](that: Graph[SourceShape[U], Mat2], request: Int)(matF: (Mat, Mat2) ⇒ Mat3): Repr[U, Mat3]
~~~

**Comment by hepin1989** [comment]
I think a better way should by provide a strategy for how to merge.
`Fair`,`Random`,`Prioritized`,`Preferred` and so on.

**Comment by viktorklang** [comment]
@hepin1989 Sadly it just adds noise:

~~~scala
source.interleave(source2, 5)
~~~

vs

~~~scala
source.merge(source2, MergeStrategy.Fair(5))
~~~

And it creates an insignificant amount of extra boilerplate. (Compare the code needed to deal with FlattenStrategy in 1.0 compared to concat in 2.0-M1)

**Comment by hepin1989** [comment]
@viktorklang I see,thanks,I just recover the `FlattenStrategy`,I jsut found that @rkuhn have opened an issue like this too https://github.com/akka/akka/issues/18962.

The `FlattenStrategy` is removed so we need to apply the same contract though,thanks for that information .:)

BTW,I think we may need collect them on one place,especially in the doc.

**Comment by viktorklang** [comment]
@hepin1989 I agree completely. I think we need some sort of use-case guide in a single document:

I want to X => code for X

**Comment by drewhk** [comment]
This is a variant on the strict round-robin merge. I guess it can be useful.

**Comment by rkuhn** [comment]
While I agree with the usefulness I’d like to register my protest against the word “merge” for deterministic operations, we should keep this term reserved for non-deterministic aggregation from multiple inputs.

Another nitpick of mine is that we should not ever use the word “fair”—even in cases where there is a theoretically sound definition this word is too easily misinterpreted by users of the API. We can use the word “unfair” though in certain cases which unambiguously are unfair in all conceivable interpretations.

**Comment by viktorklang** [comment]
@rkuhn I completely agree.

**Comment by agolubev** [comment]
working on it

**Comment by viktorklang** [comment]
@agolubev awesome, let me know if you want a second pair of eyes on it later.

**Comment by agolubev** [comment]
PR is merged - should ticket be closed?

**Comment by ktoso** [comment]
Thanks for noticing!
