### ISSUE TITLE
Add batching to Stream TCP

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19048]
The previous stream TCP impl did batching, the current one does not which likely has lessened its performance. 

In essence we want to have a generic stage that can collapse multiple incoming ByteStrings into one bigger one. This is likely useful on it's own, but esp. in the Tcp pipeline.

**Comment by drewhk** [comment]
On the other hand, this is what TCP_NODELAY off is for (default is on), so I think we should bench.

**Comment by rkuhn** [comment]
If we can avoid system calls then we should: smart batching (i.e. `conflate`) sounds like something that will be beneficial.

**Comment by drewhk** [comment]
Not conflate but `batch` since it has a cap (and cost function). It was designed for exactly these situations.

**Comment by drewhk** [comment]
and it should be measured whether there is a performance effect or not.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
