### ISSUE TITLE
Make HttpServerBlueprint reusable and actually reuse it

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19050]
As discussed at https://github.com/akka/akka/pull/18979#issuecomment-159315798

Currently, we think the performance benefit is small under the assumption that the (then-reusable) pre-materialization cost is small in relation to the actual materialization. IIUC this may change in the future if part of the fused infrastructure can be prepared before materialization.

Current obstacles:
 - [ ] Dynamically supplying a websocket user-handler: this requires to feed the materialized value of the provided user-handler stubs into the HTTP renderer (which later instantiates the WS user-handler). The suggested solution of accessing the materialized value during building a graph is still quite complicated and prone to race conditions.
 - [x] The remote address of the peer is currently passed to the parser during creation, removing this obstacle would need a method to parameterize materialization. The suggested workaround of materializing a function or promise (or any kind of cell) to pass the value in *after* materialization is again prone to race conditions (or would complicate the target stage with extra waiting code to receive the value).
- [ ] Actually reuse the blueprint // added @ktoso 

/cc @sirthias

**Comment by drewhk** [comment]
Can't the remote address passed in as an Attribute? Not the most elegant, I admit, and has its own issues, but as a first approach it might work.

**Comment by ktoso** [comment]
Thanks a lot for the hints @jrudolph – I'll start investigating this right away, and for this week in general.

**Comment by ktoso** [comment]
Point 2) addressed in: https://github.com/akka/akka/issues/19060
Point 1) ready to be worked on with the security blancket of the Autobahn tests now running on jenkins as well: https://github.com/akka/akka/issues/18563

**Comment by ktoso** [comment]
AFAIR this has been done @drewhk @rkuhn ?

**Comment by drewhk** [comment]
It is reusable, but it is not reused.

**Comment by ktoso** [comment]
This ticket was only about make reusable AFAICS, closing then.

**Comment by drewhk** [comment]
Then make a ticket about reusing it. and put it into 2.4.2 since this is the most relevant optimization.

**Comment by ktoso** [comment]
Ok, made it so

**Comment by ktoso** [comment]
Realised we have another ticket about the exact same thing: https://github.com/akka/akka/issues/19232
Closing this one
