### ISSUE TITLE
Doc search bar broken

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19059]
Search bar in docs never find anything matching:

![](https://files.gitter.im/akka/dev/8PiY/Sk_rmavbild-2015-12-01-kl.-13.48.37.png)

**Comment by ktoso** [comment]
Yeah, I believe it's confused because of paths probably? It doesn't work in streams docs.

**Comment by ktoso** [comment]
Yeah, I believe it's confused because of paths probably? It doesn't work in streams docs.
If you could try investigating that would really help a lot!

**Comment by johanandren** [comment]
Wat. Is only broken in 2.4.1 and the streams docs. Even 2.4.0 works. O.o

**Comment by johanandren** [comment]
Ok, now 2.4.1 works, I'm guessing it just wasn't indexed by google yet. Will look if there is somewhere we can post to trigger google to re-index the new docs faster upon release.

**Comment by ktoso** [comment]
Do streams work though?

**Comment by johanandren** [comment]
Argh, no, none of the streams works, what the...

**Comment by johanandren** [comment]
Aha! https://www.google.com/?gfe_rd=cr&ei=U_NeVq6tJpGr8wfs67WwBw#q=site:doc.akka.io%2Fdocs%2Fakka-stream-and-http-experimental%2F2.0-M2%2F

**Comment by ktoso** [comment]
So we most likely need webmaster tools request adding it to the index explicitly. // cc @rkuhn

**Comment by johanandren** [comment]
There is something going on with the query addition in the search bar as well, because pre streams 2.0 docs is searchable directly through google but not through search bar.

**Comment by johanandren** [comment]
Or, maybe there is something about akka-streams-and-http-etc not being added in the right place.

**Comment by patriknw** [comment]
I found that it jumbed to 2.4.0-RC1 when searching 2.4.2 docs. I guess all this will be fixed when we change to the new search engine.

**Comment by ktoso** [comment]
Correct, I'll close this once the new search is pushed a bit more (not just on snapshot), I want to do that today

**Comment by ktoso** [comment]
Solved, we have a search :]
