### ISSUE TITLE
Comply with new sbt-dependency-graph(0.8.0)

### ISSUE THREAD

**Issue by kpbochenek** [akka/akka#19054]
Hi,

I have in my .sbt/0.13/plugins/plugins.sbt a fresh version of sbt-dependency-graph that is picked up by sbt on akka project.
Unfortunately akka relies on older version(0.7.5), we could align to the newest one.
These changes introduced issue: 
https://github.com/jrudolph/sbt-dependency-graph/commit/7a5126ef875ee24f364c7b0be591893fd5d80d4a

**Comment by ktoso** [comment]
Gladly :-) 
Would you like to submit a PR to bump those dependencies? 

Thanks in advance!

**Comment by ktoso** [comment]
I assume you mean the master branch - right?
On `release-2.3-dev` it doesn't make much sense to change things in the build right now as it will soon be going away (being merged into master)

**Comment by kpbochenek** [comment]
Yes and right :)

**Comment by jrudolph** [comment]
Actually, by now the common practice is not to depend on sbt-dependency-graph from projects at all but use a global configuration if the plugin is needed.

**Comment by ktoso** [comment]
I'd :+1: removing it from our dependencies then.

**Comment by kpbochenek** [comment]
But the issues is you actually rely on specific version and use objects like "IvyGraphMLDependencies" in ValidatePullRequest.scala

I think in general you should add plugins like "sbt-dependency-graph", "ensime-sbt", "sbt-revolver" etc. that provide additional tools to ~/.sbt/
but when you use entities in your code from plugin you should explicitly include it with version.

Because I know that if my plugin version is incompatible I can comment out it from ~/.sbt and correct version will be used from project/plugins.sbt

**Comment by ktoso** [comment]
Hm, for `ValidatePullRequest.scala` don't we depend on it as a library for the "build project" instead of as a plugin though? Needs some investigation. `ValidatePullRequest` definitely needs to stay though.

**Comment by jrudolph** [comment]
Ah, I see. I moved things around but nothing was lost, so it should be easy to adapt to 0.8.0.
