### ISSUE TITLE
expose internal HttpRequest rendering API to users

### ISSUE THREAD

**Issue by aappddeevv** [akka/akka#19062]
There are needs to render HTTPRequest objects to text independent of sending them through a connection. The HttpRequest rendering API could be exposed. The key class to expose is RequestRendererFactory. This may require exposing the RequestRenderingContext.

Here's the link to the google-group post describing this: [google-group](https://groups.google.com/forum/#!msg/akka-user/X374C-s8B-I/e-r6E37PAwAJ).

Another approach is to allow an EntityBody to be composed of HttpRequests and have the rendering happen e.g. expose the rendererer as a Marshaller somehow since the rendering can be represented as a flow inside a Marshaller.

**Comment by ktoso** [comment]
// cc @sirthias @jrudolph for opinion

**Comment by sirthias** [comment]
We've had this request before but actually declined opening up the HTTP internals to the public, because this would significantly decrease our flexibility to improve things internally.
Now that we have the nice streamification though, it becomes quite easy to run the HTTP layer independently from TCP: Simply use the HTTP BidiStage in your own streams and do what you like.
Essentially it forms a graph stage that you put `HttpMessage` instances in and `ByteStrings` come out.
Should be very close to what you want.

**Comment by aappddeevv** [comment]
I'll try that. However, we need to both render and parse a HttpEntity as a HttpRequest or HttpResponse in order to satisfy some protocols.

I'll give your suggest a try once I understand it enough to code it.

**Comment by aappddeevv** [comment]
The recommendation from https://github.com/akka/akka/issues/19062 is to use a http Bidi to handle the rendering in a nice non-api exposing way. The idea is to get a ByteString that is the result of the http layer rendering a HttpRequest.

You can do something like this to get a bidi flow:

val cl = Http().clientLayer(Host("blah.com"))
val noSslTls = SslTlsPlacebo.forScala
val test1 = cl atop noSslTls join Flow[ByteString].map{x => println(x.utf8String); x}
val response = Source.single(HttpRequest()).via(test1).runWith(Sink.head)

The out from running this is:
GET / HTTP/1.1
Host: blah.com
User-Agent: akka-http/2.3.12


response: Future[HttpResponse] = scala.concurrent.impl.Promise$DefaultPromise@6159c8be


But you really get back an exception for each HttpRequest you put into this. The ByteString of the rendered body is on out1.

Await.result(response, 1 second)
akka.stream.scaladsl.One2OneBidiFlow$OutputTruncationException$

So I need to turn-off 1/2 of the bidi or map or route around the out2 so that I get a ByteString as an output from this bidi. 

Is there anyway to do this? As soon as I do a join the out1 and in2 get connected and there is no way to turn that off. I need to make sure that 1/2 of the bidi never runs because I only care about the HttpRequest to ByteString rendering.

**Comment by sirthias** [comment]
The OutputTruncationException is the result of your "server side" (the `Flow[ByteString]`) not behaving like a real server. You server doesn't produce a proper response before the stream is closed, which makes the HTTP layer throw the error.
There are several ways to solve this, with the easiest probably being to send back the request bytes as the entity of a proper response.

Here is one way to do it:

```scala
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.http.scaladsl.unmarshalling.Unmarshal

implicit val system = ActorSystem()
implicit val materializer = ActorMaterializer()
import system.dispatcher

val requestRendering =
  Http()
    .clientLayer(headers.Host("blah.com"))
    .atop(akka.stream.io.SslTlsPlacebo.forScala)
    .join {
      Flow[ByteString].map { x ⇒
        val response = s"HTTP/1.1 200 OK\r\nContent-Length: ${x.size}\r\n\r\n"
        ByteString(response) ++ x
      }
    }
    .mapAsync(1)(Unmarshal(_).to[String])

Source.single(HttpRequest(uri = "/foo"))
  .via(requestRendering)
  .runWith(Sink.head)
  .onComplete {
    case Success(requestSource) ⇒
      println(requestSource)
      system.shutdown()
    case Failure(ex) ⇒
      ex.printStackTrace()
      system.shutdown()
  }
```

**Comment by aappddeevv** [comment]
I'll give that a try as well as converting a multipart response back into individual responses using serverLayer. Once I do that, we should be able to close the issue.

**Comment by aappddeevv** [comment]
I'm not sure this is possible using akka-http. I've tried a bunch of approaches but the problem is that to convert a string into a HttpResponse (that is, to parse a string and create a response object) does not seem possible using either the client or server layer bidis.

Using a client layer:
```scala
{
                        val x1 =  Http()
                            .clientLayer(headers.Host("blah.com"))
                            .atop(akka.stream.io.SslTlsPlacebo.forScala)}
x1: BidiFlow[HttpRequest, ByteString, ByteString, HttpResponse, Unit] = akka.stream.scaladsl.BidiFlow@3bd1f546
me@ x1
res126: BidiFlow[HttpRequest, ByteString, ByteString, HttpResponse, Unit] = akka.stream.scaladsl.BidiFlow@3bd1f546
me@ x1.reversed
res127: BidiFlow[ByteString, HttpResponse, HttpRequest, ByteString, Unit] = akka.stream.scaladsl.BidiFlow@656d4d2b
```
and the server layer does not help either:
```scala
val t1 = Http().serverLayer().atop(SslTlsPlacebo.forScala)
me@ t1
res128: BidiFlow[HttpResponse, ByteString, ByteString, HttpRequest, Unit] = akka.stream.scaladsl.BidiFlow@27f4795b
me@ t1.reversed
res129: BidiFlow[ByteString, HttpRequest, HttpResponse, ByteString, Unit] = akka.stream.scaladsl.BidiFlow@2596fa08
```

If I am getting a string parsed into a HttpResponse, then I can use x1.reversed. But then I have to write a join for a HttpResponse => HttpRequest which gets translated back into a string, but I want a HttpResponse object in the end. If I use x1 directly by creating a synthetic HttpRequest whose body is the response's string I want to convert to a HttpResponse, then I have to manually parse a request string myself which is not the right approach either.

**Comment by sirthias** [comment]
I think the the snippet I shows in my last reply above should give you all you need:

1. Render an `HttpRequest` instance into a `ByteString` or `String`
(that what the snippet does as is)

2. Render an `HttpResponse` instance into a `ByteString` or `String`
Use the same snippet above and simply emit your response instance in the `requestRendering` join flow.

3. Supply response as a raw String
Convert the `String` into a `ByteString` and use that as the response in the `requestRendering` join flow.

4. Supply the request as raw String
Change the snippet to use the server-layer. The basic approach stays the same.

What exactly do you have trouble with?

**Comment by aappddeevv** [comment]
I may have caused confusion. To satisfy odata batch protocol, I have to (1) take a sequence of HttpResponses and render them to strings. The strings go into a multipart body in the "batch request." Hence the need to convert HttpRequest objects into a string for each indivdual HttpRequest before sending the batch HttpRequest. 

The other way around is when I receive a batch response that has individual response bodies in it structured as a multipart. I have a (2) sequence of response strings that I need to change back into HttpResponses so I can process the individual responses to the original individual requests. Hence the need to convert a string, representing a single http response, into an individual HttpResponse object.

1. Agreed. That's what your snippet does. Since you run Unmarshal on the final response object and the "rendered HttpRequest  string" is the body of the response, then I get the what I want. That's good. This addresses (1).

2. Agreed, but I don't think I need to do that for the odata protocol.

3. I did as you described, but because I need to get a "response as string" into the flow, I have to first attach the "response string" to a HttpRequest's entity because the body is the "response string". Once it hits the join part of the flow, I have a request object rendered into a string but  I don't know where the "response body" part starts. It's the body but I have all those request headers in the string. I added a keyword "__SNIP__" before the response string content to find the response body itself. That was the only way I could reliable find the start of the "response string."

There is only one type signature on the clientLayer/serverLayer flows that return a real HttpResponse object. This addresses (2). But I had to stick a marker __SNIP__ in to find the boundary. It was this issue that prompted my reply. It works, but I was wondering if I was missing something.

4. Agreed, but I don't think I need to do that for the odata protocol.

If there is no other cleaner way for (3) then my approach is the only way to take a String => HttpResponse object using the akka-http response parsing machinery.

You have been marvelously helpful with this issue.

**Comment by sirthias** [comment]
Ok, thanks for the additional detail, @aappddeevv!
I think I now get the gist of your use case.

You are right in that it's not completely obvious how to separate the request headers from the request body containing the response bytes in your point (3). However, it's also not very hard and you shouldn't need an additional "SNIP" marker.
In HTTP the header block is always separated from the message entity by a double CR LF sequence, which is all that you need to find. So, the message entity starts right after the first "\r\n\r\n" string you can find in the request.

**Comment by ktoso** [comment]
Exposing this more nicely can be useful, triaged

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
