### ISSUE TITLE
Framing.lengthField with LITTLE_ENDIAN byte order issue

### ISSUE THREAD

**Issue by maciej** [akka/akka#19064]
`Framing.lengthField` fails to a stream frame when using a 4 byte `LITTLE_ENDIAN` length field (or I've got something completely wrong regarding endianness!) resulting in 4 byte frames produced. It works well when using `ByteOrder.BIG_ENDIAN`, though.

Here is the link to the example code and its output: https://gist.github.com/maciej/310e574a62f4d2b80fef

I'm using Akka 2.4.1, Streams 2.0-M2, Oracle JDK 8u60, OSX 10.11.1.

**Comment by ktoso** [comment]
Hej Maciej, thanks for reporting; we'll have a look.

**Comment by ktoso** [comment]
Fixed, thanks @jrudolph !

**Comment by maciej** [comment]
:+1: thanks @jrudolph!
