### ISSUE TITLE
Inverse concat operation

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19069]
`Flow.concat` allows to inject elements from another source *after* the elements produced by this flow. I found myself wanting for the inverse operation: I want to inject elements from another source *before* the elements produced by this flow.

Is there a reason only one of those operations is included and not the other way round?

Here's the flow I use as a workaround:

```scala
      def inject[U](source: Source[U, Unit]): Flow[U, U, Unit] =
        Flow.fromGraph(FlowGraph.create() { implicit b ⇒
          import FlowGraph.Implicits._

          val concat = b.add(new Concat[U](2))

          source ~> concat.in(0)

          FlowShape(concat.in(1), concat.out)
        })

// to be used like this
flow.via(inject(source))
```

**Comment by drewhk** [comment]
It makes sense, I also considered it at some point. With source concat it is easy to change the order of sources but with flow that is not possible.
