### ISSUE TITLE
Http.singleRequest leaking?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19065]
Reported by @hseeberger 

> Akka team, I’m observing a nasty issue with the Akka HTTP: I’m using HttpExt.singleRequest on a periodic basis (once every 30 seconds) and after a while (5 to 30 minutes) the CPU load goes up to 100% (one core on my 4 core machine). Sampling with VisualVM tells me that bazillions of instances of CallbackRunnable, Future##anonfun$flatMap$1 and PoolGateway$$anonfun$apply$2 are created, which didn’t happen before. Any ideas?

> @ktoso, clone https://github.com/hseeberger/demo-akka-cluster. Look at the README, in particular start etcd (easiest by c&p the snippet from README, if you have Docker installed), run the application using (reStart --- -D…, using the properties from README, assuming you are using sbt-revolver). Then wait. Watch CPU consumption. Once the logging warns you that communication with coordination (etcd) went wrong, CPU consumption should go up to 1 full core. This might take a while, mabye consuming a lot of CPU otherwise can speed it up.

> Thanks a lot for looking into this.

> BTW, the IP addresses 192.168.99.100 work for me, not sure if they are the same for you. If you are on a Mac using Docker Toolbox they probably will work.

> The app is using https://github.com/hseeberger/constructr, namely https://github.com/hseeberger/constructr/blob/master/constructr-akka/src/main/scala/de/heikoseeberger/constructr/akka/Constructr.scala#L64 for HTTP.

> you might have to use resolvers += Resolver.bintrayRepo("hseeberger", "maven“), BTW.

**Comment by hseeberger** [comment]
@ktoso, thanks for creating the ticket. I have tried to minify the issue, but I wasn't successful. I think the issue might be related to the HTTP server not responding. Seemingly (the issue only shows after some time) I was able to work around the issue by using the connection-level API (`HttpExt.outgoingConnection`).

**Comment by ktoso** [comment]
Thanks for the hint that outgoingConnection seems fine @hseeberger. Let us know if you find out more

**Comment by hseeberger** [comment]
BTW, if you want to reproduce, you have to use commit 7b57594 from demo-akka-cluster (https://github.com/hseeberger/demo-akka-cluster/commit/7b5759458c93e8508103bd3880be6d54b15539c3) which uses a version of ConstructR which is still using `HttpExt.singleRequest`.

**Comment by ktoso** [comment]
404 @ https://github.com/hseeberger/demo-akka-cluster/commit/7b5759458c93e8508103bd3880be6d54b15539c3

Sanity check... this was on M2?

**Comment by hseeberger** [comment]
Yes, M1 and M2 showed the same behavior.

**Comment by ktoso** [comment]
Thanks, I think the previous bug is indeed fixed, but we have another one:
See here: https://github.com/akka/akka/pull/18476

**Comment by hseeberger** [comment]
Where is the fix?

**Comment by ktoso** [comment]
As I explained a number of times – we fixed a bunch of problems in M2. 
This is a new problem (or previously undiscovered problem).

**Comment by hseeberger** [comment]
Oops. Sorry for asking. I just haven't seen any explanations here.

**Comment by ktoso** [comment]
Sorry, I thought I had explained it here but seems not in this issue.
We had an actor leak problem, a wrong bidistage and rare race condition in Tcp handling.
Those are fixed in M2, they also "locked up" the requests, so the effect is similar like here.

Today I reproduced #18476 which may well be related to what you're seeing...
This one is when you'd see:

> [ERROR] [12/04/2015 16:07:59.539] [ClientSpec-akka.actor.default-dispatcher-10] [akka://ClientSpec/user/PoolInterfaceActor-0] Host connection pool to 127.0.0.1:12345 has shut down with error java.lang.IllegalArgumentException: requirement failed: Cannot pull port twice

Perhaps there's something else still. I'm working on making the connection handling more stable there, so any hints that you may find will be helpful, thanks for reporting again; I hope to nail this one soon!

**Comment by hseeberger** [comment]
No worries. This seems very tricky work to do, because when I tried to minimize the issue I spend two or three hours but could not reproduce it in a simple way.

**Comment by johanandren** [comment]
As we can't reproduce this and there was some improvements done to the connection pool in 81579bd I'm crossing my fingers and hoping this is resolved. Please re-open if this is seen again.
