### ISSUE TITLE
Can't create actor then stop it, infinitely

### ISSUE THREAD

**Issue by celetium** [akka/akka#19076]
-- I have a test like this:

object ActorLeak extends App {
  val system = ActorSystem("ActorLeak")
  val times = 100000000
  for (i <- 1 to times) {
    val myActor = system.actorOf(Props(classOf[TryActor], i), name = s"TryActor-$i")
    myActor ! StopCmd
    if (i % 10000 == 0)
      println(s"Completed $i")
  }
  println(s"Creating and stopping $times end.")
}
case object StopCmd
class TryActor(no: Int) extends Actor {
  def receive = {
    case StopCmd => context stop self
  }
}

-- run it like this: java -Xms1024m -Xmx1024m -cp ...
-- When completed about 3.8 millions, the test die: no actor is created again, but the CPU is 0% free.

**Comment by patriknw** [comment]
perhaps creation is faster than stopping, you can try by adding a sleep in the loop where you println

**Comment by johanandren** [comment]
I think I replied to this on SO the other day, is it a cross post?
http://stackoverflow.com/questions/34060210/memory-leak-of-akka-actor

**Comment by viktorklang** [comment]
Seems answered
