### ISSUE TITLE
stream: GraphStage onPull is called too many times even if limited by take(n)

### ISSUE THREAD

**Issue by etaty** [akka/akka#19071]
Hi,

``` scala
class NumbersSource extends GraphStage[SourceShape[Int]] {
  val out: Outlet[Int] = Outlet("NumbersSource")
  override val shape: SourceShape[Int] = SourceShape(out)

  override def createLogic(inheritedAttributes: Attributes): GraphStageLogic =
    new GraphStageLogic(shape) {
      // All state MUST be inside the GraphStageLogic,
      // never inside the enclosing GraphStage.
      // This state is safe to access and modify from all the
      // callbacks that are provided by GraphStageLogic and the
      // registered handlers.
      private var counter = 1

      setHandler(out, new OutHandler {
        override def onPull(): Unit = {
          println("onPull " +counter)
          push(out, counter)
          counter += 1
        }
      })
    }
}

val s = Source.fromGraph(new NumbersSource).take(10).runFold(List.empty[Int])(_ :+ _)
s.foreach(println)
```

```console
[info] onPull 1
[info] onPull 2
[info] onPull 3
[info] onPull 4
[info] onPull 5
[info] onPull 6
[info] onPull 7
[info] onPull 8
[info] onPull 9
[info] onPull 10
[info] onPull 11
[info] onPull 12
[info] onPull 13
[info] onPull 14
[info] onPull 15
[info] onPull 16
[info] onPull 17
[info] onPull 18
[info] onPull 19
[info] onPull 20
[info] onPull 21
[info] onPull 22
[info] onPull 23
[info] onPull 24
[info] List(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```

I thought i would receive only 10 `onPull` calls. It's sad to waste 14 iterations :(

Is there a way to mitigate that?

**Comment by drewhk** [comment]
Hi @etaty,

All stages prefetch, they have a buffer for that. I think there was an internal setting for `take` to not prefetch more than its limit, but might have been accidentally removed. Nevertheless, this is in general to be expected, prefetch is to reduce asynchronous communications and allow batching.

You can explicitly change the buffer size of `take` if you want to change it: http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M2/scala/stream-rate.html#Internal_buffers_and_their_effect

**Comment by etaty** [comment]
So I changed the code as you advised :
```scala
Source.fromGraph(new NumbersSource).take(10).withAttributes(Attributes.inputBuffer(initial = 1, max = 1)).runFold(List.empty[Int])(_ :+ _)
```

```console
[info] onPull 1
[info] onPull 2
[info] onPull 3
[info] onPull 4
[info] onPull 5
[info] onPull 6
[info] onPull 7
[info] onPull 8
[info] onPull 9
[info] onPull 10
[info] onPull 11
[info] List(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```

So there is still an 11th call ...
I would like something `pull` based not `push`

**Comment by drewhk** [comment]
It is pull based, not push based. It just pulls *ahead*. This is similar to reading from disk, where the OS fetches more bytes than it was requested, and then serving subsequent requests from that buffer. Since passing thread boundaries is costly, elements are requested in batches. This behavior is documented in the linked doc page I shared. Just like every optimization, it can sometimes do unnecessary work. For example if you read only one byte from a file, then close it, then all the other bytes read by the OS were read unnecessarily. In this case, `take` prefetches more elements than it needs.

**Comment by adrianlyjak** [comment]
Seems like there should be some mechanism to let streams not buffer ahead. Streams are a nice interface, but it restricts the usefulness of using them when doing anything expensive.
