### ISSUE TITLE
Provide API for Java users to create ByteStringBuilders.

### ISSUE THREAD

**Issue by jroper** [akka/akka#19085]
```java
ByteStringBuilder builder = ByteString.newBuilder();
```

doesn't compile:

```
[error] /home/jroper/src/reactive-services-platform/jackson/src/main/java/com/typesafe/service/javadsl/jackson/JacksonExceptionSerializer.java:48: non-static method newBuilder() cannot be referenced from a static context
[error] ByteString.newBuilder
```

because the `ByteString` class extends `scala.collection.generic.HasNewBuilder`, which already defines the `newBuilder` method, so the `newBuilder` on `ByteString$` can't be duplicated on the `ByteString` class as a static method.  So, currently the only way for Java users to create a `ByteStringBuilder` is on the `ByteString$` module instance:

```java
ByteStringBuilder builder = ByteString$.MODULE$.newBuilder();
```

**Comment by ktoso** [comment]
Thanks for reporting, sounds valid.

**Comment by patriknw** [comment]
I can confirm that it's an api bug. It's probably because the ByteString class defines:

    override protected[this] def newBuilder: ByteStringBuilder = ByteString.newBuilder

**Comment by ktoso** [comment]
Removing the override is not something we can do I think, but how about adding `createBuilder` for java in the object?

**Comment by ktoso** [comment]
Fixed. Will be out in 2.4.2 
// cc@jroper
