### ISSUE TITLE
Actor Testkit needs some Java 8-stylization

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19081]
It should be possible to make it a bit nicer to use thanks to lambdas etc.

// reported by @patriknw and @jboner

**Comment by patriknw** [comment]
yeah, not only a bit

**Comment by patriknw** [comment]
don't expect this to be done in 2.4.2, though

**Comment by ktoso** [comment]
Right, moving to `2.4.x`

**Comment by michaelom** [comment]
related to #18109

**Comment by patriknw** [comment]
Thanks for pointing that out @michaelom. This is a duplicate.

**Comment by ktoso** [comment]
Thanks, true! I'll close this one.
