### ISSUE TITLE
Websocket: provide API to collect streamed messages automatically

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19089]
Most applications deal only with small Websocket messages in which case it is feasible to aggregate all frames of a message and only dispatch Strict messages. 

E.g. see this thread: https://groups.google.com/d/msg/akka-user/LtxcEZtUhdI/hAY7F4LLAwAJ

It is currently quite hard to achieve this manually and a solution on top of the current implementation is inefficient because first a streamed message is created containing a substream that needs to be aggregated afterwards which (at least right now) introduces considerable overhead.

A solution would be to introduce an alternative entrypoint in `UpgradeToWebsocket` where the user can directly supply a `Flow[Message.Strict, Message, Any]` and thus only has to handle strict messages. This could be implemented efficiently by never even trying to create streamed messages and so get rid of `headAndTail` etc.

**Comment by ktoso** [comment]
Makes sense thanks for the ticket Johannes!
I'll soon be digging around the area of WS so will get more insights there.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
