### ISSUE TITLE
Add a helper method to Cluster extension to get full ActorPath

### ISSUE THREAD

**Issue by kosii** [akka/akka#19086]
Currently there is no other way to get the full path with address of an actor identified by `actorRef` than     

`ActorPath.fromString(actorRef.path.toStringWithAddress(Cluster(system).selfAddress))`

By adding a helper method to the Cluster extension class, we could do something much simpler, like this:

`Cluster(system).getPath(actorRef)`

Or if there is a way to programmatically get the `actorRef`'s system through some private API, then it would also be possible adding a method to the companion object:

`Cluster.getPath(actorRef)`

With the second method it would be possible to make sure that the user doesn't pass a wrong ActorSystem as parameter (I'm not sure it's a huge issue, in most cases there is only one system, right?)

What do you think, which one do you prefer?

**Comment by ktoso** [comment]
Thanks for reporting

How about:

`Cluster(system)` // because consistently everything "in the extension", and you consciously obtain the extension
`.pathOf(actorRef)` // because somewhat nicer to read?

Somewhat related to: https://github.com/akka/akka/issues/17690

**Comment by kosii** [comment]
Though I've read the other issue, and the conclusion was that the team can't add all methods that are nice to have. Is this feature nice enough?
