### ISSUE TITLE
Akka artifact weird on bintray

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19096]
Only sources, no jar: https://jcenter.bintray.com/com/typesafe/akka/akka-stream-testkit-experimental_2.11/2.0-M2/

Maven central is fine: http://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-experimental_2.11/2.0-M2/

and M1 is also fine on bintray:

https://jcenter.bintray.com/com/typesafe/akka/akka-stream-testkit-experimental_2.11/2.0-M2/

**Comment by rkrzewski** [comment]
The missing jar showed up on jcenter.bintray.org

**Comment by rkuhn** [comment]
Thanks for the update, Jfrog support has managed to clear up this issue.
