### ISSUE TITLE
Noticed in the wild: accept(MediaType)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19108]
I noticed such a directive in the wild, it rejects if the accept content type does not contain a given media type.

It's more or less:

```scala
/**
  * Continues to the inner route only if the `Accept` header
  * contains the given media type.
  */
  def accept(mediaType: MediaType): Directive0 =
    optionalHeaderValueByType[Accept](()).flatMap { accept => ...
```

In one way, it smells like an anti-pattern, on the other hand though:

Technically, marshalling can be avoided using content-negotiation in our marshalling infra (I provide marshalling to xml or json, and one gets picked), however perhaps there's more work being done before and I could avoid doing that work (i.e. collecting data to assemble the ToResponseMarshallable in the first place) – so it has it's uses, even though parts of the uses are covered by content negotiation. WDYT about including it, or am I missing something why it's a bad idea?

**Comment by ktoso** [comment]
cc @sirthias @jrudolph

**Comment by sirthias** [comment]
I wouldn't argue against such a directive being effective and useful in certain application scenarios, just like a high number of other specialized directives that users can easily write themselves.

However, IMHO our stance shouldn't be to include everything that someone might ever need in certain use cases. Rather I'd say that we should

1. include all the primitives that make writing your own directives possible and convenient
2. include all the higher-level constructs that are widely (enough) used and fit the "best-practice" style of writing RESTful APIs

I'd say that the `accept` directive you show here falls into neither category.

**Comment by ktoso** [comment]
Thanks for the feedback here @sirthias!
Yeah, you're right about keeping stuff out as always here yet again, thanks!
