### ISSUE TITLE
Http: `DeflateCompressor.compressAndFinish` uses unbounded buffer for data compression

### ISSUE THREAD

**Issue by ataraxer** [akka/akka#19119]
Original discussion can be found at #19100.

Possible solutions:
- add upper bound for buffer size;
- allow to configure buffer size in a similar to `DeflateDecompressor` way for consistency and transparency (would require incompatible changes, might be a good idea to squeeze this one before 2.0 releases);
- add scaladoc warning about potential extensive memory footprint for large inputs.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
