### ISSUE TITLE
fix "Java API" docs

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19122]
It is rather unhelpful to only have `Java API` as the summary in the JavaDoc output, the first sentence needs to contain the actual one-sentence summary. See e.g. the docs for [AbstractActor](http://doc.akka.io/japi/akka/2.4.0/akka/actor/AbstractActor.html).

Also make sure that `Scala API` marker is used symmetrically to `Java API`.

**Comment by patriknw** [comment]
it should be `Java API: ....` and we have that in many places
not sure anyone will go through all of it though, but something to consider when touching other things
