### ISSUE TITLE
Move File IO stream factories

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19129]
After much and long discussions in the team, the new home of the file input and output streams (and the Java blocking ``InputStream``/``OutputStream``) will be FileIO.

**Comment by johanandren** [comment]
*Sigh* some serious naming consensus problems here, dropping this again.

**Comment by ktoso** [comment]
Reopening, still will be done :wink:

**Comment by viktorklang** [comment]
There's a bigger picture here: Devise a strategy for where things are added such that As A User I Know Where To Look For Them.

**Comment by 2m** [comment]
The current consensus is to put all file and IO related Source and Sink factories under `FileIO` factory object which is going to have the following methods:
```scala
akka.stream.scaladsl.FileIO {
  def fromInputStream(in: () ⇒ InputStream, ...): Source[ByteString, Future[Long]]
  def asOutputStream(...): Source[ByteString, OutputStream]

  def toOutputStream(out: () ⇒ OutputStream): Sink[ByteString, Future[Long]]
  def asInputStream(...): Sink[ByteString, InputStream]

  def fromFile(f: File, ...): Source[ByteString, Future[Long]]
  def toFile(f: File, ...): Sink[ByteString, Future[Long]]
}
```

This is alligned with `akka.stream.scaladsl.Tcp`, `akka.stream.scaladsl.Http`,  factories.

Java DSL would be in `akka.stream.javadsl.FileIO` with appropriate overloads for default arguments and appropriate functional interfaces.

**Comment by johanandren** [comment]
:+1: (but you already knew that)

**Comment by hepin1989** [comment]
I think `FileIO` is a bad name.and the `InputStream` and `OutputStream` may not from a `File` too.
If I would go with this,I will go `IO`,not the `FileIO`.

**Comment by drewhk** [comment]
`IO` is already used. We have discussed this several times, in and out. The discussion is closed and the decision has been made.

**Comment by hepin1989** [comment]
Or
```
IO.TCP
IO.HTTP
IO.Stream
IO.File
```

**Comment by 2m** [comment]
@hepin1989 we thought about that too and the problem is when importing `...IO.File` it shadows `java.io.File`, which is especially problematic in Java.

**Comment by viktorklang** [comment]
I agree with the argument that not only is File*IO* inconsistent, but the InputStream and OutputSTream are not connected to Files.

**Comment by viktorklang** [comment]
Perhaps JavaIO is more appropriate because both java.io.File and java.io.InputStream and java.io.OutputStream live in "JavaIO".

**Comment by drewhk** [comment]
This discussion has been done before and is closed now. This train is gone, the name is what is indicated in this ticket.

**Comment by rkuhn** [comment]
I might be getting old, and this debate does as well, so I will point out that none of you are right:

* file-related sources and sinks go into `FileIO` (because that is what it does)
* java.io-stream related sources and sinks go into `StreamConverters`

This is what we agreed after an amount of debate that _by far_ outweighs the benefits of any potentially chosen name. Please stop the discussion now.

**Comment by hepin1989** [comment]
@2m https://github.com/pathikrit/better-files/blob/master/core/src/main/scala/better/files/File.scala wdyt?

**Comment by viktorklang** [comment]
@rkuhn I like that solution. :)

**Comment by hepin1989** [comment]
yes,separate.

**Comment by ktoso** [comment]
Make it so ;)
