### ISSUE TITLE
Inconsistency with names of accessors for Inlets and Outlets

### ISSUE THREAD

**Issue by marioosh** [akka/akka#19137]
`SourceShape`, `FlowShape` or `SinkShape` use `inlet` or `outlet` for its input/output ports. But junctions like `Balance`, `Zip`, etc. uses `in` or `out`, what is inconsistent. IMO all structures should use one name for its `Inlet`/`Outlet`s.

**Comment by jrudolph** [comment]
+1 that's something I've stumbled over a lot of times. Especially, if you combine it with the fact that IntelliJ often isn't able to correctly infer all types in graph building code.
