### ISSUE TITLE
Rename all occurrences of `mat` as abbreviation for `Materializer`

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#19142]
It is very confusing that `mat` and `*Mat` are not abbreviations for the same thing.

Least invasive change is to be clear about a `Materializer` being assigned to a `materializer` val/var/parameter rather than `mat`.

This mostly applies to documentation but also examples and tests etc.

**Comment by jboner** [comment]
Thanks Viktor. I understand that it might be too late, but I would prefer to change *Mat* to *MatVal*. This abbreviation got me, and I don't find it intuitive. But changing the docs like you suggest is better than nothing.

**Comment by viktorklang** [comment]
@jboner I find `MatVal` too debilitating horizontally and would suggest `MV` over `Mat`/`MatVal`.

But I think the ship has sailed there so I propose to make things less confusing by being more candid about the type of something that points to a `Materializer`.

**Comment by jboner** [comment]
Yes. `toMV` sounds good to me.

**Comment by hepin1989** [comment]
MV like Music Video or Movie

**Comment by viktorklang** [comment]
or MUTABLE VARIABLE!! :D

On Thu, Dec 10, 2015 at 11:50 AM, kerr <notifications@github.com> wrote:

> MV like Music Video or Movie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/19142#issuecomment-163577316>.
>



-- 
Cheers,
√
