### ISSUE TITLE
GraphStage / SourceStage consistency w.r.t. mat value

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19141]
They're not consistent in the sense of:

- GraphStage - no mat value
- GraphStageWithMaterializedValue - needs mat value
- SourceStage / SinkStage / FlowStage - needs mat value

Shouldn't we have SourceStageWithMaterializedValue etc?

**Comment by hepin1989** [comment]
that's inconsistent makes wondering a while why the `GraphStage` extends `GraphStageWithMaterializedValue` when it don't have a `MaterializedValue`.

**Comment by ktoso** [comment]
Yeah, it's inconsistent, but it seems we're removing them for now anyway – #19156 ;)
