### ISSUE TITLE
Failed: FlowGroupBySpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19145]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4461/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4467/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4464/consoleFull

**Comment by viktorklang** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4474/
