### ISSUE TITLE
stream (2.0-M2): bug in Flow.sliding

### ISSUE THREAD

**Issue by beyonix** [akka/akka#19149]
Follow up on: https://groups.google.com/forum/#!topic/akka-user/fhlCbYJ8kOc

Flow.sliding does not correspond exactly with the Seq.sliding behaviour, as was apparently intended. A  minimised example for this bug is:

```scala
Source(Stream.from(0)).take(2).sliding(1, 3)
```
This will place two elements on the stream: {0} and {0, 1}. The correct behaviour would only have placed the former on the stream.

Because I had it lying around by now, a test that should fail for all generated test-cases, but right now succeeds for all of them. Perhaps this will prove useful:
```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.Source
import akka.testkit.TestKit
import org.scalacheck.{Gen, Shrink}
import org.scalatest.concurrent.{Eventually, ScalaFutures}
import org.scalatest.prop.GeneratorDrivenPropertyChecks
import org.scalatest.{FlatSpecLike, Matchers}

import scala.concurrent.Future

/**
 * Created by merlijn on 10/12/15.
 */
class SlidingWindowTest extends TestKit(ActorSystem("test")) with FlatSpecLike with Matchers with GeneratorDrivenPropertyChecks with Eventually with ScalaFutures {

  implicit def noShrink[T]: Shrink[T] = Shrink.shrinkAny[T]

  implicit val materializer = ActorMaterializer()

  def test(count: Int, window: Int, step: Int): Future[Seq[Seq[Int]]] = Source(Stream.from(0))
    .take(count)
    .sliding(window, step)
    .runFold(Seq.empty[Seq[Int]]) { case (total, slice) =>
      total :+ slice
    }

  "Sliding" should "never pass this test" in {
    val windowStep = for {
      window <- Gen.choose(1, 10)
      step <- Gen.choose(window + 2, 20)
    } yield (window, step)

    forAll(windowStep) {
      case (window, step) =>

        val incompatibleElementCount = for {
          n <- Gen.choose(1, 20)
          count <- Gen.choose(step * n + window + 1, step * (n + 1) - 1)
        } yield count

        forAll(incompatibleElementCount) { count =>
          whenReady(test(count, window, step)) { testResult =>
            testResult.last.size should be > (window) //For correct behaviour, this test should pass by reversing the assertion: testResult.last.size should be <= (window)
          }
        }
    }
  }
}
```

In essence, the problem pops up (as far as I observed) when the next step in sliding exceeds the last available element in the stream, and some of the elements of the terminated stream were not included in the previous window. In that case, it will create a new window with the same lowerBound as the previous window, and include all elements up to the last one.

**Comment by viktorklang** [comment]
Sounds like it's about time to rewrite fusing.Sliding in GraphStage.

**Comment by viktorklang** [comment]
@beyonix Thanks for raising this issue, I think I both fixed it and managed to improve the verification to align with the standard library: see #19153

**Comment by beyonix** [comment]
My pleasure really, even though i feel bad for having logged this Friday at the end of the work-day, making you fix bugs in your weekend :) Thanks for following up on this so fast!

**Comment by viktorklang** [comment]
@beyonix No worries, I needed a break from the kids.
