### ISSUE TITLE
`SourceStage`, `SinkStage` and `FlowStage` aren't "worth it"

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19156]
As we would need to have six traits to cover `WithMaterializedValue` as well (see #19141), and they only save you three lines of code, whilst stopping you from giving the inlets/outlets stage speific names.

Discussion: https://gitter.im/akka/dev?at=566d8fd5d09f613936200efa

**Comment by johanandren** [comment]
Ok, not quite true with the names, they do require a inlet/outlet `name`-prefix

**Comment by ktoso** [comment]
Meh, I would actually like to complete the full set of these helper traits... 
It gets a bit not-DRY when we remove those I think (and removes my 6 words answer of to "how do I do a very complex Sink?": "extend FlowStage and follow the types" :wink:).

But LGTM and we can add them back later once we see the need for it more.
