### ISSUE TITLE
Typo in GraphStageLogic (?)

### ISSUE THREAD

**Issue by maciej** [akka/akka#19152]
In Akka Streams 2.0-M2:

```scala
abstract class GraphStageLogic/* … */ {
  final protected def emitMultipe[T](out: Outlet[T], elems: Iterator[T]): Unit = emitMultiple(out, elems, DoNothing)
}
```

The method emitting multiple elements and taking the arguments as above shouldn't be called `emitMultiple`, not `emitMultipe`?

**Comment by ktoso** [comment]
Thanks, and fixed already on the branch :)

**Comment by maciej** [comment]
:+1:
