### ISSUE TITLE
make ActorGraphInterpreter input buffers configurable per GraphStage attributes

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19179]
currently only uses defaults for GraphModule

**Comment by rkuhn** [comment]
@drewhk this is indeed going to be a hindrance when trying to optimize things; the proposal of folding dispatcher and buffering aspects together with async boundary attributes would make sense, I think

**Comment by drewhk** [comment]
I don't understand what this ticket is about or your comment above.

**Comment by rkuhn** [comment]
When fusing, inputBuffer attributes are currently ignored; this ticket is about making buffers configurable again.

**Comment by drewhk** [comment]
Ah, you mean that the ActorGraphInterpreter should use buffer sizes on the boundary inlets corresponding to those stages that correspond to those external inlets?

**Comment by rkuhn** [comment]
That is a little more convoluted than what I meant: currently the input buffer sizes are defined by the ActorMaterializer’s defaults, and this ticket is about making it possible again to deviate from these defaults for a given part of the blueprint. How exactly this is done is not yet fully settled.

**Comment by drewhk** [comment]
ok.

**Comment by ktoso** [comment]
Closing this, a bit old ticket and we're currently working on rethinking them: https://github.com/akka/akka/issues/22523
