### ISSUE TITLE
Unify naming scheme for persistence queries

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#19174]
In Akka Persistence Query most of the predefined queries are named according to the scheme foo and currentFoo. One exception is allPersistenceIds and currentPersistenceIds. I suggest to either drop the "all" prefix from the former or apply it to all predefined queries.

**Comment by patriknw** [comment]
Good catch, then it should be `persistenceIds` and `currentPersistenceIds`.

**Comment by patriknw** [comment]
Note that the following PR (with breaking changes) should also be included: https://github.com/akka/akka/pull/20830

**Comment by ktoso** [comment]
I'm on this.

**Comment by ktoso** [comment]
Done
