### ISSUE TITLE
Add Partition Graph Stage

### ISSUE THREAD

**Issue by israel** [akka/akka#19176]
Add a partition stage from 1 inlet to n outlets 
![drawing](https://cloud.githubusercontent.com/assets/239588/11787502/aa1c6cae-a294-11e5-9e14-51d20f486348.png)

Excuse my drawing skills... :-)

**Comment by wlk** [comment]
it seems that this can be closed? can you confirm?

**Comment by ktoso** [comment]
Right, closing
