### ISSUE TITLE
String interpolation performance in Streams

### ISSUE THREAD

**Issue by richdougherty** [akka/akka#19180]
When testing Play performance recently I noticed that about 4% of request processing time was spent with string interpolation within Akka Streams. The following methods showed up:

* `akka.stream.impl.ActorMaterializerImpl$$anon$3.stageName(Attributes) ActorMaterializerImpl.scala:78`
* `akka.stream.impl.ActorMaterializerImpl.akka$stream$impl$ActorMaterializerImpl$$createFlowName() ActorMaterializerImpl.scala:53`

I thought it might be possible to improve performance by avoiding the string interpolation or by making it lazy.

This was with Akka Streams **1.0**. We will be upgrading to Akka Streams 2.0 soon, so there's no need to change the code in v1.0. However, it would be great if you could check on the string interpolation code in 2.0 and see if it can be optimised.

Cc @wsargent.

**Comment by drewhk** [comment]
I would bet that in this case materialization costs dwarf the name calculation logic.

**Comment by wsargent** [comment]
How expensive is materialization?

**Comment by richdougherty** [comment]
The absolute numbers aren't particularly significant, but in short-lived streams about 25% of materialization time is spent on `stageName` method and about 8% on `createFlowName`.

Here are some raw timing numbers from serving a few million requests. Columns are "method", "source file", "time (including methods called)", "time (excluding methods called)".

```
akka.stream.impl.ActorMaterializerImpl.materialize(Graph) ActorMaterializerImpl.scala 48208 231
akka.stream.scaladsl.RunnableGraph.run(Materializer) Flow.scala 48208 0
akka.stream.impl.MaterializerSession.materialize() StreamLayout.scala 40619 660
akka.stream.impl.ActorMaterializerImpl$$anon$3.stageName(Attributes) ActorMaterializerImpl.scala 12088 1767
akka.stream.impl.ActorMaterializerImpl.akka$stream$impl$ActorMaterializerImpl$$createFlowName() ActorMaterializerImpl.scala 4181 821
```

**Comment by drewhk** [comment]
I found this weird, we usually see attachChild as the most significant "leaf-level" cost. With fusing these numbers will be quite different, so let's wait until then.

**Comment by richdougherty** [comment]
Yes it is weird. Here's the data for `attachChild`:

```
akka.actor.ActorCell.attachChild(Props, String, boolean) ActorCell.scala 42 0
```

**Comment by drewhk** [comment]
I think it is better to redo these measurements on 2.0 which will be out soon, since there were tons of changes since 1.0.

**Comment by rkuhn** [comment]
With fusing the number of actors (and therefore names) will be considerably lower. We’ll look at the profiles when we get there, in the meantime we’ll close this issue—we will naturally see this again when looking with a profiler if it remains relevant. But thanks for raising it!
