### ISSUE TITLE
Source.inputStream must emit bytes eagerly without batching

### ISSUE THREAD

**Issue by fsat** [akka/akka#19193]
The default behaviour of `Source.inputStream()` is to block until the internal buffer is filled up.

Since we won't be able to tell the length of the data in advance, the sensible default behaviour is to send data as soon as it's available from the Source, instead of waiting until the buffer is filled.

This can be achieved at the moment with the following snippet - (thanks @2m):

```
Source.inputStream(() => input).withAttributes(Attributes.inputBuffer(1, 1))
```

We should have the `Attributes.inputBuffer(1, 1)` as the default behaviour.

**Comment by rkuhn** [comment]
No, we should actually fix the `Source.inputStream` implementation to not do the wrong thing, changing the title of the ticket.
