### ISSUE TITLE
Memory Leak within Akka HTTP low level API

### ISSUE THREAD

**Issue by fsat** [akka/akka#19196]
We've encountered memory leak when issuing HTTP request against an HTTP endpoint that is either down or not yet available. This behaviour is observed using Akka HTTP low level API.

The affected version is 2.0-M2.

We have a reproducer to show this behaviour:

https://github.com/fsat/akka-stream-http-test-stuff

The setup of the reproducer can be found at https://github.com/fsat/akka-stream-http-test-stuff/blob/master/README.md

**Comment by rkuhn** [comment]
I suspect that the single-use outgoing connection fails to properly shut down all its actors, which should be simple to verify with a smaller test case using `assertAllStagesStopped`.

**Comment by fsat** [comment]
Checked again with the reproducer after building `release-2.3-dev` with merged change - everything looks good, OOM has been fixed:

<img width="473" alt="akka-http-tcp-manager-fix" src="https://cloud.githubusercontent.com/assets/1665611/11887029/48e7e92a-a584-11e5-816c-1cb1518b1434.png">

**Comment by rkuhn** [comment]
Thanks@
