### ISSUE TITLE
Add HttpEntity.ignoreDataBytes convenience method

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19195]
for ignoring any payload so that no timeouts need to happen; should be a nop for strict entities

**Comment by ktoso** [comment]
Also relates to the automatic applying of this as described in: https://github.com/akka/akka/issues/18716
(This ticket is the first step, the other one is automatic applying of it)

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
