### ISSUE TITLE
wrong documentation for max-pool-size-*

### ISSUE THREAD

**Issue by patriknw** [akka/akka#19201]
```
        # Minimum number of threads to cap factor-based max number to
        # (if using a bounded task queue)
        max-pool-size-min = 8

        # Max no of threads (if using a bounded task queue) is determined by
        # calculating: ceil(available processors * factor)
        max-pool-size-factor  = 3.0

        # Max number of threads to cap factor-based max number to
        # (if using a  bounded task queue)
        max-pool-size-max = 64
```

This has always made me think that max-pool-size-* properties does not matter if you use an unbounded task queue. That is wrong. The pool will be capped by the `maximumPoolSize`

I think we should automatically set the `maximumPoolSize` to at least the value of `corePoolSize`, so that a fixed size pool can be configured by the `core-pool-size-min` and `core-pool-size-max` settings.

**Comment by richdougherty** [comment]
I agree that all the `(if using a bounded task queue)` comments are confusing. They probably mean `this is a useful setting if you want to bound the size of the thread pool`.
