### ISSUE TITLE
akka-http - Authorization header parser seems off

### ISSUE THREAD

**Issue by tdrozdowski** [akka/akka#19204]
I'm attempting to implement the Hawk authorization protocol with akka-http.  My hang up currently seems to be around where and how the Authorization header is being parsed.

When I set the Authorization header value to be something like:

Hawk id="KZE5zYr9saeOhaTon", ts="1450294511840", nonce="01m4jVDgWh4yE", mac="IgGa4xw2z/cHnedceio7bqq4ve1rr08fAnRlYMIzyeQ="

by the time I extract the Authorization header via the optionalHeaderValueByName("Authorization") I receive a value that looks like this:

Hawk id=KZE5zYr9saeOhaTon, ts=1450294511840, nonce=01m4jVDgWh4yE, mac="IgGa4xw2z/cHnedceio7bqq4ve1rr08fAnRlYMIzyeQ="

Which is to say its the same header value before, with the Hawk scheme, but the parameters are all unquoted - except for the final one.

I'm not sure if this is a parsing issue/bug with the way things are handled, but it seems to be that this behavior shouldn't be happening.

**Comment by ktoso** [comment]
Thanks for reporting!
Not sure yet, we'll have a look.

// cc @sirthias @jrudolph

**Comment by sirthias** [comment]
When rendering header values akka-http only applies quotes when required by the spec, otherwise they are left out. The spec requires quotes if a value contain non-token characters, which the last one in your example does (the '/' is not a token char), hence the behavior you are seeing.
Why is it a problem in your case?

**Comment by drewhk** [comment]
Please reopen if there is an actual issue, or an action item that results from the discussion.
