### ISSUE TITLE
Akka cluster remote netty port binding: Address already in use

### ISSUE THREAD

**Issue by bitsofinfo** [akka/akka#19207]
So I am trying to start 2 instances of an Akka app on my local machine (in separate JVMs).

When instance1 starts isSeedNode = true (so port is bound to 2552)

When instance 2 starts isSeedNode = false (so port should bind to 9999)

Instance1 starts fine, but when instance instance2 starts, I get the exceptions below, which indicate it is not obeying my port settings...? What am I doing wrong

```
boolean isSeedNode = true;

Config remotingConf = ConfigFactory.parseString(
                  "  remote {"+
                  "    enabled-transports = [\"akka.remote.netty.tcp\"]\n"+
                  "    netty.tcp {"+
                  "       hostname = \"192.168.0.208\"\n"+
                  "       port = "+ (isSeedNode ? 2552 : 9999)+"\n"+
                  "       bind-port = "+ (isSeedNode ? 2552 : 9999)+"\n"+
                  "     }"+
                  " }");

Config combined = remotingConf.withFallback(appConfConfig);

system = ActorSystem.create(name,ConfigFactory.load(combined));
```

My application.conf

```
akka {

actor {
  provider = "akka.cluster.ClusterActorRefProvider"
    debug {
    autoreceive = on
    lifecycle = on
    unhandled = on
    }
  }
}
```

EXCEPTION thrown from instance2 (when instance1 is already running). I even tried always setting the port and bind-port to 9999 but not matter what it always trys to bind to 2552. I am wondering if I am using this dynamic config incorrectly.

Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /192.168.0.208:2552 Caused by: java.net.BindException: Address already in use

**Comment by drewhk** [comment]
>                   "  remote {"+
                  "    enabled-transports = [\"akka.remote.netty.tcp\"]\n"+
                  "    netty.tcp {"+
                  "       hostname = \"192.168.0.208\"\n"+
                  "       port = "+ (isSeedNode ? 2552 : 9999)+"\n"+
                  "       bind-port = "+ (isSeedNode ? 2552 : 9999)+"\n"+
                  "     }"+
                  " }");

Missing `akka` prefix in front of remote. It should be `akka.remote`.

**Comment by bitsofinfo** [comment]
Thanks!
