### ISSUE TITLE
Sink.inputStream OutOfBoundsException

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19215]
Inside `getData`:

```
        val size = data.size - skipBytes
        if (size + gotBytes <= length) {
          System.arraycopy(data.toArray, skipBytes, arr, begin, size)
          skipBytes = 0
          detachedChunk = None
          if (length - size == 0)
            gotBytes + size
          else
            getData(arr, begin + size, length - size, gotBytes + size)
        } else {
          System.arraycopy(data.toArray, skipBytes, arr, begin, length) 
          skipBytes = length
          gotBytes + length
        }
```

The first arraycopy is wrong, since it tries to copy `size` bytes which can be larger than the `length` clients requested. ping @agolubev

**Comment by ochrons** [comment]
As a work-around you can use `PipedOutputStream`

For example working with the AWS S3 client:

```scala
Sink.outputStream { () =>
  val is = new PipedInputStream(1024*1024)
  val os = new PipedOutputStream(is)
  Future {
    val metadata = new ObjectMetadata()
    metadata.setContentLength(length)
    s3Client.putObject(bucketName, id, is, metadata)
  }
  os
}
```

**Comment by agolubev** [comment]
I will look into this on weekend

**Comment by viktorklang** [comment]
Also, Is there a reason why arraycopy + ByteString.toArray is used? (ByteString.copyToArray would seem much cheaper)

**Comment by agolubev** [comment]
yeah, will use copyToArray as it only iterates through requested array length no the whole data set

**Comment by agolubev** [comment]
>The first arraycopy is wrong, since it tries to copy size bytes which can be larger than the length clients requested.

Condition one line above says ```size + gotBytes <= length```, where gotBytes >=0 so it's impossible size > length

**Comment by agolubev** [comment]
found two other bugs but non of them relates to first arraycopy directly

**Comment by drewhk** [comment]
Ok, thanks for investigating.
