### ISSUE TITLE
Make it possible to expose HTTP requests as Sink

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19218]
What is needed is roughly:

```
val uploadSink = Flow[ByteString].lift.map(<put Source in HttpRequest>).via(http).to(Sink.ignore)
```

Where lift is the magic that makes `Source[T]` to `Source[Source[T]]`.

**Comment by ktoso** [comment]
Discussed here: :point_up: [December 17, 2015 1:04 PM](https://gitter.im/akka/akka?at=5672a4bb69a89a8f552ef5b0)

**Comment by drewhk** [comment]
Maybe we need `liftToEntity`?

**Comment by jrudolph** [comment]
To me it seems the question was how to implement such a function:

```scala
def uploader(requestCreator: Source[ByteString, Any] => HttpRequest): Sink[ByteString, Future[HttpResponse]]
```

I wonder if the given solution with `Source[Source[T]] ` really is the simplest or most straightforward solution to implement such a function. If you treat `Sink[ByteString, Future[HttpResponse]` as the function `(Source[ByteString, Any], Materializer) => Future[HttpResponse]` the original function could be written much simpler as 

```scala
def uploader(requestCreator: Source[ByteString, Any] => HttpRequest): (Source[ByteString, Any], Materializer) => Future[HttpResponse] = (source, mat) => Http().singleRequest(requestCreator(source))(mat)
```

So, the only thing that is needed to return a `Sink` is a generic utility function that converts a function

```scala
(Source[T, Any], Materializer) => Mat
```

to a `Sink[T, Mat]`.

**Comment by drewhk** [comment]
Well, the original function was the current workaround, but lift is something we don't want to expose, hence the ticket (if it was not clear). That Sink converter is an interesting idea though, it might be what we need.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
