### ISSUE TITLE
Clarify why NegotiateNewSession.clientAuth is an option

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19213]
It seems that `ClientAuth` itself has its own `None` type. If this is by design the difference between 

```scala
NegotiateNewSession.clientAuth = None
```

and

```scala
NegotiateNewSession.clientAuth = Some(ClientAuth.None)
```

should be explained in the ScalaDoc.

**Comment by jrudolph** [comment]
Any action should also be applied to `HttpsContext`.

**Comment by ktoso** [comment]
For reference, it's not quite a None/Some, it is:

```
  case object None extends ClientAuth
  case object Want extends ClientAuth
  case object Need extends ClientAuth
```
