### ISSUE TITLE
Bump default TLS version for remoting

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19228]
It's currently defaulting to `protocol = "TLSv1"` (because JDK6) but on master we don't care about 6 anymore. We should default to `TLSv1.2`, see also: https://github.com/ktoso/ssl-config/blob/master/core/src/main/resources/reference.conf#L25

The setting is `akka.remote.netty.ssl.security.protocol`

**Comment by drewhk** [comment]
absolutely
