### ISSUE TITLE
Option to eagerly initialize persistence journal backend connection

### ISSUE THREAD

**Issue by merlijn** [akka/akka#19221]
We are using akka 2.4 with persistent actors in combination with cluster sharding.

On joining a new node to the cluster that node gets assigned shards with persistent actors. The problem is that these actors immediately receive messages while the (cassandra) connection is not yet established. This results in much delayed response times for those actors.

Currently we are initializing a dummy persistent actor before joining the cluster to circumvent this (see below). Would it be an idea to have a configuration option to eagerly initialize this connection? (before member up)

```
  def createDummyPersistentActor()(implicit system: ActorSystem) = {
    val dummyId = java.util.UUID.randomUUID().toString
    system.actorOf(Props(new PersistentActor() {
      override def persistenceId: String = s"dummy-$dummyId"
      override def receiveRecover: Receive = Map.empty
      override def receiveCommand: Receive = Map.empty
      context.self ! PoisonPill
    }), dummyId)
  }
```

**Comment by patriknw** [comment]
I think it is a good idea. It would be easy to do for the default journal, but requires some kind of config list of eagerly loaded plugins if it is to be supported for other plugins than the default. Pull request is welcome.

**Comment by talp-traiana** [comment]
@patriknw Is this what you had in mind, or do you think a list with plugin IDs would be better?

**Comment by patriknw** [comment]
That has the limitation that it's only working for the default plugin. I think we should use a list instead.
