### ISSUE TITLE
make HttpServerBlueprint fully reusable

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19232]
… and do not require an implicit Materializer

**Comment by drewhk** [comment]
This supercedes https://github.com/akka/akka/issues/19231

**Comment by ktoso** [comment]
This is solved, right @rkuhn ?

**Comment by rkuhn** [comment]
Yes, it works.

**Comment by rkuhn** [comment]
Oh, actually: while it is reusable, the implicit Materializer has not yet been removed and it is not actually reused by the convenience methods, so let’s keep this open.

**Comment by ktoso** [comment]
I'm happy to tackle this in the next weeks, I'll read up on the PR and see if I get what's pending then (i.e. where to rip it out).

**Comment by drewhk** [comment]
What exactly is missing here?

**Comment by rkuhn** [comment]
It is not actually reused, and the implicit materializer arguments should all be removed.

**Comment by drewhk** [comment]
ok I see.

**Comment by drewhk** [comment]
Should the blueprint wrapped in a an async boundary? I would opt for wrapping it with async when it is used in the sugar methods (bind, bindAndHandleWith, etc.), but if one needs a fusable one he can use the blueprint directly.

**Comment by rkuhn** [comment]
Why? What happens on one connection can well be handled by a single actor, unless the user wants some separation around their handler flow—which they can add themselves.

**Comment by drewhk** [comment]
Hm, I had a bad feeling about sharing an actor with user code :) But yes, the user can wrap his route in an async wrapper if he wants, but he needs to know how to make a route a flow and wrap it. Maybe not an issue given how other frameworks work (and therefore what people expect).

**Comment by ktoso** [comment]
Still open, because of the implicit materializer mentioned above, right @drewhk ?

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
