### ISSUE TITLE
HttpEntity change interface: add withNoLimit

### ISSUE THREAD

**Issue by jgordijn** [akka/akka#19237]
HttpEntity has a method: `HttpEntity.withSizeLimit`, but it has no way to indicate that there should be no limit. It is possible to configure `infinite` in the `application.conf`, but then it would apply to all entities.

A workaround is to set `HttpEntity.withSizeLimit(Long.MaxValue)`, which is near infinite. Having `HttpEntity.withNoLimit()` and/or `HttpEntity.withSizeLimit(-1)` would make it more explicit.

For the discussion see: https://groups.google.com/forum/m/#!topic/akka-user/DIZ2WY97dnA

**Comment by viktorklang** [comment]
`withoutSizeLimit`?

**Comment by ktoso** [comment]
`withoutSizeLimit ` :+1: 
Would you like to contribute that one @jgordijn ?

**Comment by jgordijn** [comment]
I hope I find time to look into it. `withoutSizeLimit` is indeed better.

**Comment by ktoso** [comment]
Hi @jgordijn, I took this one over as I've just noticed it related to moving around the withSizeLimit API itself to make it accessible for JavaDSL and has a few cycles available to pull it though.

If you'd find the time and would like to contribute back to Akka let me know – there's plenty tickets (check small or community-contrib) which are up for grabs :-)

**Comment by jgordijn** [comment]
That's fine @ktoso. I will look into it when I have more time on my hands. Cheers.
