### ISSUE TITLE
BackoffSupervisor: automatic and manual reset

### ISSUE THREAD

**Issue by RayRoestenburg** [akka/akka#19246]
(Description copied from post on akka user)
There seems to be no way for the child to tell the `BackoffSupervisor` that everything is ok again, the back-off is automatically reset based on a duration of no errors:

https://github.com/akka/akka/blob/v2.4.1/akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala#L204
https://github.com/akka/akka/blob/v2.4.1/akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala#L207-L208

The `minBackoff` is both used as minimal back-off duration and as this automatic reset duration. Which actually makes the `minBackoff` hard to set correctly, since it depends on the types of errors (and the speed at which the errors occur) in the child, and it makes it a bad idea to set it too low, since the back-off can then get stuck in repeating per `minBackoff` if the child does not crash fast enough the first time (within `minBackoff`), which means it will not properly back-off.

The user should be able to choose between an automatic reset and a manual reset (where the child sends a message to the supervisor to indicate success).

Also, there are currently two implementations of back-off supervisor, which should both reside in `akka.pattern`, the `BackoffSupervisor` props methods can create the correct implementation.

Discussion thread here: https://groups.google.com/d/msg/akka-user/rWNMM62fy9M/TT_5n4YDCgAJ

**Comment by ktoso** [comment]
Thanks for collecting the info in a ticket

**Comment by RayRoestenburg** [comment]
You're welcome. I'm starting on this today since I have some time before the holidays..

**Comment by ktoso** [comment]
Great, thanks. I'm online most of december so will be will be able to review :)

**Comment by RayRoestenburg** [comment]
Cool :-)

**Comment by RayRoestenburg** [comment]
@ktoso so I'm thinking of making the following changes, which I want to run by you (let me know if you disagree with any of this so the review will cause a little less rework).

This is mostly about hiding both current `BackoffSupervisor` and `TransparentExponentialBackoffSupervisor` behind a 
`BackoffSupervisor` object that creates a back-off supervisor as required.

- The back-off supervisor is put in front of the child and behaves exactly like the child actor, so I want to drop the 
`GetCurrentChild` and `CurrentChild` messages (unless there is some use case for it I can't immediately think of?).

- The `BackoffSupervisor` takes a `SupervisorStrategy`, the `TransparentExponentialBackoffSupervisor` a `Decider`.
I'm going to have both just take a `Decider`, since the difference between `AllForOneStrategy` and `OneForOneStrategy` don't make sense
here, there is only ever one child to supervise. 

- I don't think the three args to the strategies 
(`maxNrOfRetries, withinTimeRange, loggingEnabled`) will be important for a user in this case. (but if that would be important, I could add them as arguments when creating the back-off supervisor without the need to pass in a `SupervisorStrategy`)

- The `BackoffSupervisor` does not stash, the `TransparentExponentialBackoffSupervisor` does. I'll implement stash on both so less messages 
are lost during a long back-off period. (A message that causes the child to fail will obviously be lost, but that will be expected).
That might cause an OOME if many messages are sent during a very long back-off period. But since it is already done in the 
`TransparentExponentialBackoffSupervisor` and you guys were happy with it there :) it's probably more intuitive to also have it in the other? I could try and make stashing optional in both (so the user can choose) which is possible since neither use `preRestart`.

- The `TransparentExponentialBackoffSupervisor` terminates itself when the child actor terminates, The `BackoffSupervisor` does not. I'm not changing that, in the one case you want something close to 'transparent' supervision, where terminating all makes sense, in the other case you use `Stop` to indicate failure, so it is obvious that the supervisor will not get killed. 

- Instead of thinking of good names for several `props` methods to create the different implementations, I think it would make more sense here to create a `BackoffOptions` type with a tiny fluent interface, below an example:

```scala
val options = BackoffOptions.onStop // instructing to create the `BackoffSupervisor`, stop == failure
                            .forChild(childProps, childName)
                            .withDecider(decider)
                            .withBackoff(minBackoff, maxBackoff, randomFactor)
                            .withAutoReset(resetBackoff) // or withManualReset for instance

val ref = BackoffSupervisor.create(options)
```
Any objections to this idea?

Oh and by the way, I think there is an error in the current code, what was intended here?
```scala
case msg if sender() == childRef ⇒
      // use the supervisor as sender
      context.parent ! msg
```
since `context.parent` points to the parent of the `BackoffSupervisor`? (Am I missing something here?)

**Comment by patriknw** [comment]
GetCurrentChild is useful for testing (and you can't break backwards binary compatibility in akka-actor)

SupervisorStrategy is more flexible than Decider, e.g. logging. I think there was another reason also, yeah, I think it was that then we can have same java and scala api.

I'm not sure stashing is good, since it can be a long duration and risk of OOME. Since it will be easy to loose some messages anyway I think it is fine to just drop messages so there is no doubt that it is not reliable. If you have anohter opinion it should be implemented with an internal buffer with limited size.

BackoffOptions sounds good, but `BackoffSupervisor.create` should return `Props`, and the convention is to name it `props`. You must keep the old one for backwards compatibility.

The `BackoffSupervisor`delegates all messages from the child to the parent of the `BackoffSupervisor`, with the supervisor as sender. That is intended for cluster sharding passivation, but it doesn't cover everything, see https://github.com/akka/akka/issues/19016

**Comment by RayRoestenburg** [comment]
@patriknw thanks, exactly the kind of feedback I was hoping for. I hadn't thought of backwards compatibility. Re: strategy, right, because of `JDecider`, agreed. I'll use `SupervisorStrategy` in both.

I'll remove stashing. A limited buffer is a good idea, although what would you do, drop messages that can't fit? It's probably best to leave out for now. 

I'll use `props` and leave the old ones for backwards compatibility.

Aha, those 'messages from the child' are messages initiated by the child, ok makes sense.

**Comment by patriknw** [comment]
Thanks for doing this!

**Comment by RayRoestenburg** [comment]
You're welcome :)
