### ISSUE TITLE
PersistenceQuery java example

### ISSUE THREAD

**Issue by jansoren** [akka/akka#19259]
Hi, 

Now I have gone through [akka-sample](https://github.com/akka/akka/tree/master/akka-samples/akka-sample-persistence-java) and [akka-doc](https://github.com/akka/akka/tree/master/akka-docs/rst/java/code/docs/persistence) and still need help setting up a PersistenceQuery. 
Do anyone know if there is an example that shows this in a simple manner implemented in java?

**Comment by ktoso** [comment]
What specifically are you asking for - how to use Persistence Query?
Have you read though: http://doc.akka.io/docs/akka/snapshot/java/persistence-query.html ?

This sounds more like an akka-user ( https://groups.google.com/forum/#!forum/akka-user ) question than a ticket, I'll close for now.
