### ISSUE TITLE
Support Broadcast with just one output

### ISSUE THREAD

**Issue by hbf** [akka/akka#19257]
My code builds a graph by calling

    builder.add(Broadcast.create(writers.size()));

If `writers.size()` is 1, I obtain 

    java.lang.IllegalArgumentException: requirement failed: A Broadcast must have more than 1 output ports

I understand that a `Broadcast` with 1 output is semantically meaningless. However, it simplifies my code – and I'm sure the code in many other situations – if `Broadcast` allowed one output.

Can we support that case?

(Tested with _com.typesafe.akka:akka-stream-experimental_2.10:2.0_.)

**Comment by hepin1989** [comment]
@hbf you could using `Flow` instead.

**Comment by drewhk** [comment]
We supported it back then, and then we changed to require at least two outputs. You can put an `if ` around that part where you construct your broadcast, simply replacing it with nothing when the outputs are one.

**Comment by hbf** [comment]
@hepin1989, @drewhk Thanks for the suggestion. I understand that I can use a `Flow` here – my point is about making the `Broadcast` API generic: Not allowing the case of single output forces users to do special casing when they write algorithms based on streams.

**Comment by hepin1989** [comment]
@hbf I asked that once,you could see the conversation here https://github.com/akka/akka/issues/19028

**Comment by hbf** [comment]
@hepin1989 Thanks for the link! Ok, looks like this was discussed at length. I may be missing something but I'd have preferred this special case to be optimized away behind the scenes and allow API users to write simple code. – Just my 2 cents, so feel free to close this issue.

**Comment by hepin1989** [comment]
@hbf we are the community,and learn from each other:)

**Comment by ktoso** [comment]
I'll leave it open until the rest of the team comes back and we decide on it. 
I for one am not that happy with not allowing broadcast(1) (due to not optimising it away currently)

**Comment by lespea** [comment]
+1 this would really simplify some of my code

**Comment by viktorklang** [comment]
I think about it like this: if we could have a constraint type on Int which limited it to `greater-than-two` we would.

Should we also support Broadcast(-1) or Broadcast(Int.MinValue)?

**Comment by hbf** [comment]
My thinking is this: `Broadcast(n)` is meaningful for _n_ >= 0, and the semantics are straightforward and most likely intuitively clear to the user of this API. To me, that speaks for allowing these cases. I'd throw an exception if _n_ < 0. 

On the other hand, restricting to _n_ > 1 makes it hard to write generically reusable algorithms involving flows. If I exaggerate completely for a moment then it's like a programming language whose `for`-loop requires you to make at least one iteration. You _can_ of course use an `if` in front of the loop to catch that case but often, your code will not be so readable.

**Comment by lespea** [comment]
I don't see how you jumped from supporting a broadcast of 1 to saying we should also support -1... they're completely different.  hbv's loop example is perfect; this is needed for dynamically generating flows when you don't know at compile time how many things you'll need to broadcast to, without having to do a whole bunch of manual checking of the size.  I mean it isn't that hard obviously but it's just a bunch of extra code that shouldn't be needed.

**Comment by drewhk** [comment]
The case for allowing 0 is to simplify code that is generic to some 1..N range, the case for allowing only >= 1 is to not allow people to add the overhead of a broadcast when it is not needed. I slightly more like the allow zero option.

**Comment by viktorklang** [comment]
@drewhk If we can make sure the broadcast is optimized away when downstreams are > 1 then I think we should allow 0..N. So I see this as encouragement for smarter materialization :)

**Comment by drewhk** [comment]
That does have extra performance cost though when materializing. Nothing is for free :)

**Comment by viktorklang** [comment]
@drewhk Of course, I wrote an optimizer before, y'know ;)

**Comment by drewhk** [comment]
Things were much simpler then though since there were no graphs. So you have to rethink it to be applicable and fast at the same time.

**Comment by viktorklang** [comment]
well yes and no, we have a self-contained builder now, so there is
opportunity for simplification pre-materialization.

-- 
Cheers,
√

**Comment by ktoso** [comment]
Please close this when solved @drewhk, I remember you touching that area recently right?

**Comment by drewhk** [comment]
No, I did not.
