### ISSUE TITLE
support Prefer header: http://www.ietf.org/rfc/rfc7240.txt

### ISSUE THREAD

**Issue by aappddeevv** [akka/akka#19263]
It does not appear that akka-http has the Prefer header included.

http://www.ietf.org/rfc/rfc7240.txt

**Comment by ktoso** [comment]
What other web servers have it built-in and what would supprt mean in terms of your request - just having the header modeled or implementing some of it's semantics automagically? I skimmed the RFC and don't think there's much support needed from Akka itself to be able to adhere to Prefer headers.

If it's about just modeling it, it's really fairly simple to use any header you want in Akka HTTP, the model is very extensible: http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0/scala/http/common/http-model.html#Custom_Headers

**Comment by ktoso** [comment]
// cc FYI @sirthias @jrudolph (I hope you won't mind that I ping you on HTTP related tickets over the holidays? Feel free to enjoy holidays ofc ;-))

**Comment by sirthias** [comment]
@ktoso No, ofc, just ping away. It might be that reaction time is a bit longer though, but I'll try to react ASAP.

Concerning this ticket: Adding a proper model for a common header is no problem, IMHO.
Prerequisite would be the RFC detailing the syntax and then we need to add

1. The model classes, along the lines of what we already have.
2. The parser rules for the new header
3. The tests

I think it should make for a good starting point for new contributors.

**Comment by aappddeevv** [comment]
I agree there is not much needed for akka itself other than modeling the headers for the request and response. I thought the tricky part is that you can specify one preference per Prefer header or bundle them up separated by semi-colons (I think it was ';').

There's actually some returned Prefer headers in the response that need to be parsed though to make them more convenient e.g. if a preference was used, it is returned in a comma separated list.

I'm not sure I'm up quite yet to contributing as I am still ramping on the "use it to get stuff done" part still :-)

I think that section is now in the 2.0 docs, so I'm glad its there...I've pored over the code already to understand it a bit already.

**Comment by ktoso** [comment]
We'd be happy to accept a PR adding the header I think - thanks for reporting! 
Let us know if you (or someone else) would like to contribute

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
