### ISSUE TITLE
make sure that withAttributes and addAttributes are overridden in all subclasses

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19261]
to make fluent FlowOps composition work across them (most notably for asyncBoundary)

**Comment by hepin1989** [comment]
@rkuhn for this part ,I think we could do something like what's will get into Elixir 1.3,the `Stream.async()/0` which put an asyncBoundary like :
```
CSV.parse(path)
|> ...
|> Stream.async()
|> ...
|> Stream.async()
|> ...
|> Stream.async()
|> ...
|> Stream.run()
```
