### ISSUE TITLE
stream-io.rst remove PushStage usage?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19278]
It's using `PushStage` but it seems we removed PushStage documentation in favour of GraphStage.
So now it linked "and now go and learn more about puss stage" and the link was dead.

```
This is implemented by using a custom :class:`PushStage`
(see :ref:`stream-using-push-pull-stage-scala`) which completes the stream once it encounters such command.
```

**Comment by hepin1989** [comment]
@ktoso 
>me :  see the PushStage ,PullStage and PushPullStage in the stream-customize section have been removed.
but that seems not mentioned in the migration guide
<br>
>roland: eventually there will only be GraphStage—why should we have multiple ways of doing the same thing?
But removing those will take some more time since almost all built-in linear combinators are based on them.

**Comment by ktoso** [comment]
Yup, thanks @hepin1989 !

**Comment by ktoso** [comment]
Seems this was solved
