### ISSUE TITLE
Consider using scala.math.Numeric for limitWeighted

### ISSUE THREAD

**Issue by lolski** [akka/akka#19292]
In order to be really usable, the method `limitWeighted` should be generic enough to accept all numeric types (i.e. Int, Long, Float, and Double) instead of just `Long`. This should be achievable using `scala.math.Numeric`.

As per @rkuhn's comment https://github.com/akka/akka/pull/18965#issuecomment-166109976, we should consider if this improvement is warranted.

**Comment by rkuhn** [comment]
In a sense `long` is the most expressive and precise numeric type that the JVM exposes, can you give an example of where it is not enough?

**Comment by lolski** [comment]
In some cases, the user may want the cost function to evaluate to a whole number, e.g, `long`. In other cases, a fractional e.g., `double`.

**Comment by drewhk** [comment]
In those cases you can simply multiply the cost by something like 1000, convert to long, and scale the capacity accordingly. Or build a custom stage. I don't want to use floating point stuff in streams unless strictly necessary.

**Comment by lolski** [comment]
NOTE: Updated incorrect ticket title from `limitWithin` to to `limitWeighted`

I suggested this ticket because I was under the assumption that accurate cost calculation (up to that which is supported by `double`) will be needed for algorithm correctness.

@drewhk May I know what's the reason why FP isn't a good idea? Is it speed or is there other reasons as well?

**Comment by rkuhn** [comment]
Writing a correct algorithm using `double` precision is actually quite hard because precision does not equate accuracy. In the example of `limitWeighted` you might discover that adding very small values to a large accumulated weight does not result in a change for the accumulation—a `double` has less bits of precision than a `long` does.
