### ISSUE TITLE
ActorLogging maybe have GC problem

### ISSUE THREAD

**Issue by celetium** [akka/akka#19290]
I have a project with several Actor using ActorLogging trait. When I did performance testing, I found that it's ok if low pressure. But it will be OutOfMemory on high pressure. Analysing the GC log, Old Gen grows fast.

I change to SLF4JLogging, all is ok.

**Comment by ktoso** [comment]
It's somewhat hard to say anything here without reproducer or more data from your end.
What logging level was enabled, what exactly was the config etc?

**Comment by celetium** [comment]
akka {
  loglevel = "INFO"
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  actor {
    debug {
      receive = on
      lifecycle = on
    }
...
no more setting on Logging of the project.
