### ISSUE TITLE
Fix remaining issues in Sink.seq, Flow.limit and Flow.limitWithin

### ISSUE THREAD

**Issue by lolski** [akka/akka#19293]
As found by @RichardBradley, PR https://github.com/akka/akka/pull/18965 has some lingering issue that needs to be fixed. To quote https://github.com/akka/akka/issues/18921#issuecomment-166253591:

- Loads of `stream.grouped(n).runWith(head)` expressions in Akka (mainly in test) can now be replaced with `stream.runWith(seq)` -- see #18267
- The current implementation of `Sink.seq` will silently do the wrong thing if the stream is longer than `INT.MAX_VALUE`. I think this deserves fixing, or at the very least a note in the docs. Notably, `limit` and other length operators take a `Long`, so Akka does seem to allow streams longer than `Int.MAX_VALUE`.
- The `stream-cookbook.rst` hasn't been updated, and still suggests the old recipe. See #18267 for a fix.
- Possible incorrect "emits when" description for `limit` and `limitWithin`
- `Sink.seq` (Scala DSL) should return `immutable.Seq` rather than `Seq`

**Comment by ktoso** [comment]
> Loads of "stream.grouped(n).runWith(head)" expressions in Akka (mainly in test) can now be replaced with "stream.runWith(seq)" -- see #18267

Please be aware of https://github.com/akka/akka/pull/18503 which is there since a long time (test kit support for `toStrict`)

**Comment by lolski** [comment]
@ktoso I assume we want to replace those calls with `seq` as well?

**Comment by lolski** [comment]
Added another issue where `Seq` is returned instead of `immutable.Seq`

**Comment by ktoso** [comment]
Are you planning to pick those up @lolski? Thanks in advance if so :)

**Comment by lolski** [comment]
@ktoso Yup, already about half-way on it.
