### ISSUE TITLE
some problem when I build a akka.stream.scaladsl.Source

### ISSUE THREAD

**Issue by cjuexuan** [akka/akka#19309]
when I  want to new a Source ,I try apply ,because I find the the doc is
```scala
 * Helper to create [[Source]] from `Iterable`.
   * Example usage: `Source(Seq(1,2,3))`
   *
```
so I try:
```scala
val x = Source(Seq(1,2))
```
but it can't work ,I also try 
```scala
val x = Source(Seq(1,2).toIterable)
```
oh no, the funcation like my Engilsh ,so bad,
until I try
```scala
val x = Source(Seq(1,2).toVector)
```
so I think ,why not we try  a better understanding way to rename it like Source.fromIterable,

**Comment by hepin1989** [comment]
As @viktorklang have renamed most of the `apply(*)` to follow the `from*` pattern,at the first time I try out this API,I start to follow the IDE autocomplete with typing `Source.from<see what shows off>` ,but this way do not help the situation here,where the only method left is `Source.apply` for scaladsl and `Source.from` for javadsl.

Maybe for name consistence,and the consistence between javadsl and scaladsl,rename both to `Source.fromIterable` would help,but maybe this is a little late,cause @ktoso said we just keep some `apply` and we at at `2.0` now.

but still have a chance,cause we are `2.0-experimental` :)

**Comment by viktorklang** [comment]
@cjuexuan I suspect your problem is that the `Seq` alias is `scala.collection.Seq` instead of `scala.collection.immutable.Seq`.

I'll opportunistically close this Issue, please reopen if my guess is wrong!

**Comment by hepin1989** [comment]
@viktorklang What he really want to say is change the `apply` method to `Source.fromIterable`，just euphemized:)

**Comment by cjuexuan** [comment]
yeah,why not we try a better understanding way to rename it like Source.fromIterable

**Comment by viktorklang** [comment]
@hepin1989 That I agree with. :-)
