### ISSUE TITLE
Update session stream parallelism in akka streams docs

### ISSUE THREAD

**Issue by matheuslima** [akka/akka#19303]
http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.1/scala/stream-parallelism.html
"Akka Streams processing stages (be it simple operators on Flows and Sources or graph junctions) are executed concurrently by default. This is realized by mapping each of the processing stages to a dedicated actor internally." After fusing stages implementation this concept is out of date.

**Comment by ktoso** [comment]
Must be revised before merging to master.

**Comment by rkuhn** [comment]
hasn’t this been done by @johanandren ?

**Comment by johanandren** [comment]
Duplicated and fixed by #20051
