### ISSUE TITLE
Configuring HTTP server for SSL

### ISSUE THREAD

**Issue by tindzk** [akka/akka#19306]
I am trying to get my Akka HTTP server to accept encrypted connections:

```scala
  val httpsContext = {
    val ks = KeyStore.getInstance("JKS")
    ks.load(new FileInputStream(new File("certs/keystore.jks")), password)

    val keyManagerFactory = KeyManagerFactory.getInstance(
      KeyManagerFactory.getDefaultAlgorithm)
    keyManagerFactory.init(ks, password)

    val context = SSLContext.getInstance("TLSv1.2")
    context.init(keyManagerFactory.getKeyManagers, null, new SecureRandom)

    HttpsContext(context)
  }

  def server(): Future[ServerBinding] =
    Http().bindAndHandle(route,
      interface = Configuration.serverInterface,
      port = Configuration.serverPort,
      httpsContext = Some(httpsContext))
```

It turns out that the server is unable to negotiate a suitable cipher with the client. I have tried to connect with Chromium and Mozilla Firefox, and both indicate `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` (or `ssl_error_no_cypher_overlap` respectively).

**Comment by jrudolph** [comment]
Try setting the JVM property `-Djavax.net.debug=all` which prints out lots of information about what is going on internally. You could also try to connect using `openssl s_client -connect <host>:<port>` and see what its output is.

Potential issues are either missing cipher implementations in your JDK setup or a mismatch between ciphers and key material.

**Comment by tindzk** [comment]
Thanks! I set the JVM option (`set javaOptions in run += "-Djavax.net.debug=all"`), but I don't receive any debug messages when connecting.

Here's the OpenSSL output:

```
$ openssl s_client -connect localhost:8080
CONNECTED(00000003)
140587138959000:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 318 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1452271732
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

Do you happen to have a working example with SSL enabled that I could have a look at?

**Comment by ktoso** [comment]
Won't that `javaOptions in run += "-Djavax.net.debug=all"` only work if you `fork` though? I.e. you perhaps are not really running with this option.

Apply it to the JVM hosting SBT (`sbt -Djavax.net.debug=all`, if using sbt-extras).

**Comment by tindzk** [comment]
I tried this as well, but it doesn't show any debug messages either.

**Comment by ktoso** [comment]
You should be able to obtain printouts like attached by @johanandren here: https://github.com/akka/akka/issues/19287#issuecomment-169725081
That would help a lot in debugging your problem, thanks in advance!

**Comment by tindzk** [comment]
Is there a way to set this flag in code? As stated above, passing the parameter to sbt-extras' `sbt` didn't yield any results. I even set `javax.net.debug=all` in my `application.conf`, to no avail.

**Comment by johanandren** [comment]
You could probably:
```
sys.props += "javax.net.debug" -> "true"
// or the Java API
System.setProperty("sys.props", "true")
```
However I'm not sure when the network stack is initialized, so it might be too late in your code.

From sbt if you use run to start it, you could do:
```
fork in run := true // to kick off a new JVM
javaOptions in run := "-Djavax.net.debug=all" // with these options
```

**Comment by tindzk** [comment]
Thanks. I've tried out these commands, but SSL connections still don't get logged. Is it possible that ssl-config overrides my settings?

**Comment by johanandren** [comment]
I don't think so, I actually used neither of these two methods but instead got output just running small sample apps in IntelliJ with the flags to the JVM.

**Comment by jrudolph** [comment]
In sbt, try

```
show run::javaOptions
```

and

```
show run::fork
```

before invoking `run` to make sure the settings were actually applied. It's easy to mess things up in sbt by setting keys in the wrong scope or sometimes just because of the order in which settings are applied (doesn't matter when using `+=` or `++=` but is sometimes a problem when using `:=` in sbt).

**Comment by ktoso** [comment]
We're cleaning up tickets today, as this is a discussion more than a feature request / ticket.

This is tracked as issue here:
- https://github.com/akka/akka/issues/19294
- and here: https://github.com/akka/akka/issues/19275

Closing for now but happy to keep the discusion.
For future discusion would be better to keep on akka-user, not as ticket.
