### ISSUE TITLE
Websocket client documentation is missing

### ISSUE THREAD

**Issue by danarmak** [akka/akka#19315]
Websocket client support was [added](https://github.com/akka/akka/pull/18693) to 2.0, but the [docs](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.1/scala/http/client-side/websocket-support.html) still say it's unsupported.

**Comment by ktoso** [comment]
Thanks for reporting.

**Comment by ktoso** [comment]
// cc @sirthias @jrudolph
