### ISSUE TITLE
Add combinators; contramap and contraConcat to `Sink`

### ISSUE THREAD

**Issue by Fristi** [akka/akka#19318]
I found myself using `alsoTo` a lot and in some cases you want to log (or event source even) something. A small example:

```scala

//Create a actor sink which consumes a sealed trait `Software.Command`
val softwareSink =
    Sink.actorSubscriber[Software.Command](...)

//now contramap or contraConcat a list of commands to 
val addGithubInfo = softwareSink
  .contraConcat[(GithubRepos, Set[ScalaJsArtifact])] { case (repo, arts) =>
    arts.toList.map { art =>
      Software.Command.AddGithubInfo(Project(art.groupId, art.artifactId), repo.stargazers_count, repo.description, LocalDateTime.now())
    }
  }

someStream.alsoTo(addGithubInfo)
```

Implementation is pretty straightforward (don't mind the materializers as Any, didn't know how to make this nicer for the time being. Suggestions are welcome). `contramap` comes from contravariant functors as it consumes a `U` to create a `Sink[T]` which we already have available

```scala

implicit class RichSinkObject[T](val sink: Sink[T, Any]) {
    def contramap[U](f: U => T): Sink[U, Any] = Flow[U].map(f).to(sink)
    def contraConcat[U](f: U => List[T]): Sink[U, Any] = Flow[U].mapConcat(f).to(sink)
  }
```

**Comment by viktorklang** [comment]
How about:

~~~scala
implicit class RichSinkObject[T,M](val sink: Sink[T, M]) {
    def contramap[U](f: U => T): Sink[U, M] = Flow[U].map(f).toMat(sink)(Keep.right)
    def contraConcat[U](f: U => scala.collection.immutable.Iterable[T]): Sink[U, M] = Flow[U].mapConcat(f).toMat(sink)(Keep.right)
  }
~~~

**Comment by Fristi** [comment]
Nice to fix the materialized type @viktorklang :+1:  

Would you like these combinators in akka aswell?

**Comment by viktorklang** [comment]
@Fristi Np. I'm personally against adding more API which does the exact same thing as something existing, as well as introduces even more names. (Consider having to add *Mat versions of said methods etc.

**Comment by Fristi** [comment]
Well that's quite common amongst libs. Basic combinators plus a lot of combinators which are built on top of that which make things easier to cope with :smile: I agree with the fact that you introduce more names + overloads (for the Mat versions..) which makes it harder to take in for newcomers. 

Personally I was surprised by the amount of combinators which were there (lot's compared to version 1). A good example is that I wrote `alsoTo` myself a few weeks ago. After watching a talk of Konrad about akka-streams I noticed he was using `alsoTo`, so that was a nice thing to replace with a one liner. My point being, it's nice to offer lot's of combinators, as they are tested, reviewed and makes it easier to express problems.

**Comment by viktorklang** [comment]
@Fristi Having lots of methods *which do the same thing* is not good tho :)

**Comment by drewhk** [comment]
@Fristi we have a defensive stance when adding new combinators, and only add a new one when there is enough pressure or convincing arguments -- to balance the amount of sugar and minimality in an opportunistic fashion.

**Comment by Fristi** [comment]
I can fully understand. I find these two combinators useful for this use case, not sure if others also find these combinators useful. Leaving this open for now, if others would want this , they are free to opt-in here ;) If I would find more useful combinators we could start a akka-streams-contrib project maybe ;)

**Comment by patriknw** [comment]
Perhaps something to contribute to [akka-stream-contrib](https://github.com/akka/akka-stream-contrib)?
Closing it here.
