### ISSUE TITLE
fix throttle implementation

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19316]
* it uses currentTimeMillis instead of nanoTime
* it assumes perfect scheduling accuracy
* it does not correctly work at higher rates than the scheduler frequency
* it accesses the clock more often than necessary
* the constant cost function should be reused instead of allocated per use

**Comment by drewhk** [comment]
> it assumes perfect scheduling accuracy

How? It just assumes that scheduled events are not scheduled early. Throttle can overthrottle somewhat, and since it is token bucket based scheduling only happens when bucket is empty.

> it does not correctly work at higher rates than the scheduler frequency

How so? You just need to add a proper burst size and then the scheduler is not even hit, only tokens are calculated for each incoming element.

> it accesses the clock more often than necessary

Might be, but if I take this ticket I would not know what do you mean here. 

Can you please elaborate on these points, since this is too terse in this form.

**Comment by rkuhn** [comment]
Thanks for looking at this and sorry for the terse form, I needed to dump my thoughts while concentrating on something else entirely ;-) I sent you the description of a slightly differently targeted throttling algorithm that happens to differ from this one in each of the points above (as part of chapter 15 of Reactive Design Patterns), I’ll revisit this one after recovering from the final writing push.

**Comment by drewhk** [comment]
I am not sure I see the difference. Fractional tokens are accounted in the current implementation, see the 1024*1024 scaling. Of course it can accumulate, but I don't see a big issue there. I also do not see how your implementation differs in the above points. Are we talking about this code: https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/impl/Throttle.scala ?

**Comment by drewhk** [comment]
(except the currentTimeMillis of course)

**Comment by drewhk** [comment]
Well, OK, there is one optimization though, that the time does not need to be queried if there are enough tokens in the bucket already, only when it is running out. And this also improves precision.

**Comment by drewhk** [comment]
anyway, I have not read fully your doc, but I will. It might make sense though to include the version we have since it is a very direct implementation, and then add the optimized version and explain the improvements.

**Comment by agolubev** [comment]
@rkuhn, @drewhk, I'd like to start this ticket if you don't mind.

**Comment by rkuhn** [comment]
Thanks @agolubev! Unfortunately I haven’t had the time to come back to this ticket yet, but the other implementation I was talking about is [here](https://github.com/ReactiveDesignPatterns/CodeSamples/blob/master/chapter15/src/main/scala/com/reactivedesignpatterns/chapter15/ThrottlingPattern.scala#L139).

**Comment by agolubev** [comment]
rkuhn, thanks. 
Not pretty clear what you mean by 

>the constant cost function should be reused instead of allocated per use

Do you have some particular function in mind? (it was not in the above discussion)

**Comment by rkuhn** [comment]
That comment refers to [this line](https://github.com/akka/akka/blob/72eb3f539deead8a60675f3af3ac47597d42785d/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L1293) (which allocates one function per call).

**Comment by ktoso** [comment]
> > the constant cost function should be reused instead of allocated per use
> 
> Do you have some particular function in mind? (it was not in the above discussion)

It should use `akka.stream.impl.ConstantFun`

**Comment by agolubev** [comment]
thanks

**Comment by agolubev** [comment]
> there is one optimization though, that the time does not need to be queried if there are enough tokens in the bucket already, only when it is running out.

Still we need to calculate how many tokens left so need to get current time for calculating this.

**Comment by rkuhn** [comment]
this has been done in by @agolubev
