### ISSUE TITLE
Resource resolution in BundleDelegatingClassLoader is non-deterministic

### ISSUE THREAD

**Issue by briantopping** [akka/akka#19323]
After working briefly with `BundleDelegatingClassLoader`, it became apparent that it's resource resolution is non-deterministic because it uses `Set` instead of `Seq`. Any change to dependencies or key hash will result in a different order of resolution for classes or resources. 

Should fix #18846. PR to follow...

**Comment by viktorklang** [comment]
:+1:

**Comment by briantopping** [comment]
First part of this PR complete as a deterministic breadth-first discovery of transitive dependencies. It's only called on bundle startup so the performance hit of replacing `Set` with `Seq` shouldn't create any issues (and may improve performance once loaded due to the better ordering of the bundle list by distance). This doesn't solve all the issues and I don't think some of them are easily solvable, so I'd like to better document what's going on as a second part of the PR. 

Refresher on OSGi: A Bundle is a Java JAR that has additional MANIFEST.MF entries documenting dependencies and how to interact with those dependencies. For this discussion, we mostly care about the `Import-Package` header. Unfortunately, [bndtools](http://bnd.bndtools.org) (which tools link against for generating manifest entries) sorts the imports alphabetically, not by graph distance. This isn't a huge disadvantage WRT monolithic JVM apps since `ClassLoader` makes no guarantees on search result ordering. In turn, if `BundleDelegatingClassLoader` were to start doing so, it doesn't mean we should rely on it. 

So with that in mind, there's an important subtlety of the use case with OSGi: As bundles are composed into applications, it's pretty easy to unexpectedly pick up configuration from the transitive closure of direct dependencies when using `BundleDelegatingClassLoader`. Once again, this isn't different than a monolithic app, but the ease of mixing and matching bundles makes it a lot more likely. There is certainly a need for prioritization of configuration, but it's probably adequate to document the use of `akka.osgi.ActorSystemActivator#getActorSystemConfiguration` with some examples and use cases. Maybe

Sound reasonable so far? :)

**Comment by briantopping** [comment]
Here's a start of doc, interested in feedback. TMI? 

I think the next steps are generating `ActorSystemActivator` examples at various degrees of usage, both with and without Blueprint, which is a pretty common deployer.

[Akka in OSGi — Akka Documentation.pdf](https://github.com/akka/akka/files/76800/Akka.in.OSGi.Akka.Documentation.pdf)

**Comment by briantopping** [comment]
Ok, getting back to this. The intent of #19330 is that dependency resolution and construction of configuration is repeatably distance based and deterministic.

To refresh, `BundleDelegatingClassLoader` starts with the bundle referenced by `BundleContext#getBundle` and using `Set` to avoid duplicates, walks the tree of dependencies defined by the OSGi "bundle wiring". This is fine for general purpose class resolution, but when this undefined classloader resolution order is used for loading configs, behavior is unpredictable. 

Example: A module needs to set `akka.cluster.roles`. In some cases, the configuration that is defined in the `reference.conf` of Akka Cluster is defined early with fallback of the local module later. In turn, the role is empty when it should be defined. 

Thoughts?

**Comment by briantopping** [comment]
bump

**Comment by briantopping** [comment]
I'm going to experiment again with using `application.conf` to prioritize configuration for this and will reopen if necessary, thanks.

**Comment by viktorklang** [comment]
I fany OSGi expert wants to have a look here, ping @briantopping.

**Comment by patriknw** [comment]
Thanks, @briantopping!
Your contributions are very valuable!

**Comment by briantopping** [comment]
Hey thanks for the encouragement, guys! I have some full-time work starting last week, but they are receptive so far to me using Akka, fingers crossed. :)
