### ISSUE TITLE
Akka HTTP: Cannot access the received secret when using basic auth

### ISSUE THREAD

**Issue by cb372** [akka/akka#19321]
I'm trying to port a Spray app to Akka HTTP 2.0.1, and I'm having trouble porting some code that uses Spray's `authenticate` directive.

The problem is that the process for verifying the received password is hardcoded to a string equality check:

```
// akka.http.scaladsl.server.directives.Credentials
def apply(cred: Option[HttpCredentials]): Credentials = {
  cred match {
    case Some(BasicHttpCredentials(username, receivedSecret)) ⇒
      new Credentials.Provided(username) {         
        def verify(secret: String): Boolean = secret secure_== receivedSecret
      }
    // ...
  }
}
```

I want to be able to customise this verification logic. For example, in this particular app we take the received password, hash it using scrypt, then compare it with a hash retrieved from the DB.

I can work around it for now by not using the `Credentials.apply` method, but that means I need to copy-paste and tweak the whole `authenticateBasicAsync` directive. It would be nice if there was a way to pass in my own verification predicate, with a type something like `(user, receivedSecret) => Boolean`.

**Comment by jrudolph** [comment]
I agree. We had a previous suggestion how to solve the issue here: #18858. Would that also work for you?

**Comment by ktoso** [comment]
ping @cb372, would the API proposed in #18858 work for you (so we can collapse them into one ticket)?

**Comment by cb372** [comment]
Sorry, I missed that reply. Yes, #18858 sounds fine to me. Feel free to close this issue.

**Comment by ktoso** [comment]
Great, thanks – closing here, and will eventually resolve the other one :+1:
