### ISSUE TITLE
Akka Streams: FlowOpsMat Repr should be elevated to at least FlowOpsMat

### ISSUE THREAD

**Issue by timcharper** [akka/akka#19336]
In [FlowOpsMat](https://github.com/akka/akka/blob/akka-stream-and-http-experimental-2.0/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L1602), `Repr` is left as it was inherited from [FlowOps](https://github.com/akka/akka/blob/akka-stream-and-http-experimental-2.0/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L339).

I think if you are using an interface that implements FlowOpsMat, it's safe to assume that the `Repr` will implement FlowOpsMat, also.

This is an issue because if you implement a class which contains an object that implements `FlowOpsMat`, and then call `map` on the generic object, what you get back is a `FlowOps` interface and can't call any materialization methods.

**Comment by timcharper** [comment]
I marked the pull request as API breaking, since it is possible (but I think extremely unlikely) for this to cause code to no longer compile.

There's potentially even more remote possibility this could lead to a binary compatibility issue, but not directly, but I can't come up with a concrete example of how it would break.

**Comment by timcharper** [comment]
I'm working around it, for now; perhaps seeing this workaround will provide any missing context as to why I feel this is an issue.

https://github.com/timcharper/acked-stream/blob/akka-issue-19336/src/main/scala/com/timcharper/acked/AckedFlowOps.scala#L581

**Comment by rkuhn** [comment]
The provided example does not show the problem, though, because the type of `wrappedRepr` is `Flow` (which works fine) and not `FlowOpsMat`, right?

I just pushed an update to #19317 that should fix this issue (and a few more).

**Comment by timcharper** [comment]
WrappedRepr is at least a FlowOpsMat

**Comment by rkuhn** [comment]
Yes, but the value that is mapped (`wrappedRepr`) is a `Flow` and not a `WrappedRepr`.

**Comment by timcharper** [comment]
I'm sorry Roland, I'm really trying hard to figure out where the miscommunication is happening.

wrappedRepr (defined [here](https://github.com/timcharper/acked-stream/blob/akka-issue-19336/src/main/scala/com/timcharper/acked/AckedFlowOps.scala#L43) is of type WrappedRepr, which is constrained in FlowOpsMat to be <: FlowOpsMat [here](https://github.com/timcharper/acked-stream/blob/akka-issue-19336/src/main/scala/com/timcharper/acked/AckedFlowOps.scala#L562).

wrappedRepr could be an `Source` or a `Flow`, as both implement `FlowOpsMat`.

The issue is that when I do an operation on an instance of FlowOpsMat, it gets downgraded to a FlowOps, and the materialized value modifying operations become unavailable.

**Comment by rkuhn** [comment]
Ah, I see now, got confused by the many very similar names in that file, you're right. Anyway, my PR should fix it, right?

**Comment by timcharper** [comment]
Yeah, your pr will fix it nicely.

**Comment by timcharper** [comment]
Resolved by https://github.com/akka/akka/pull/19317
