### ISSUE TITLE
`FileAndResourceDirectives#getFromResourceDirectory` fails under OSGi

### ISSUE THREAD

**Issue by briantopping** [akka/akka#19331]
`FileAndResourceDirectives#getFromResourceDirectory` with a classloader set to that of a bundle eventually calls https://github.com/akka/akka/blob/a19050dbcbb7b28a7533a5db1019d9b521ffc210/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala#L206-L227 with a URL using a `bundle` scheme under Karaf. 

Under OSGi, a bundle does not have reliable access to the filesystem to open a bundle in the way that a JAR is being opened here. I may not be able to fix this one, but I am very curious to understand why registered URL handlers were avoided in this manner.  

What can I do to help here?

**Comment by rkuhn** [comment]
I have no clue. @sirthias @jrudolph why does this not just use `ClassLoader.getResourceAsStream`? @briantopping would that fix it? (I assume so, but my understanding of OSGi is that it is broken in interesting ways ;-) )

**Comment by briantopping** [comment]
Thanks Roland, that would definitely fix it in a manner that is impervious to any quirks that exist across implementations.

**Comment by 2beaucoup** [comment]
We used `classLoader.getResource` but switched to the current impl while fixing #17495.

Maybe we should use URL handlers just for the default case?

**Comment by briantopping** [comment]
Oh interesting, makes sense. Yes, default case would be fine I'm sure. Shall I cook up a PR? Or I can test on this end once one is put together. Thanks!

**Comment by briantopping** [comment]
I've been having weird problems with the build all day and haven't been able to test the patch I have together. I believe changing the `file` case in https://github.com/akka/akka/blob/a19050dbcbb7b28a7533a5db1019d9b521ffc210/akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala#L208-L225 to the default case will solve the issue and should solve it for any other interesting cases that arise. :)

**Comment by rkuhn** [comment]
@briantopping what kind of problems? If you are reasonably sure of the patch, you can also submit it as a PR and have the validator test it, but we should definitely sort out any build issues that prevent contributors from contributing!

**Comment by ktoso** [comment]
Let me know what exactly blows up for you @briantopping and should be able to help out. Not sure why you compile using `+compile` during development?
PR very welcome here ofc, should retain current semantics etc :)

**Comment by briantopping** [comment]
Wanted to bump this up, is it possible to get a resolution before 2.4.2 final? I can keep building akka-http separately, but it probably ought to be noted in release documents that akka-http doesn't work with containers that depend on custom URI handlers if so.

**Comment by rkuhn** [comment]
The team is currently quite reduced in numbers, we do intend to fix this before the release, though.

**Comment by briantopping** [comment]
No worries, thanks Roland. I'm testing M1 out today on Karaf (Felix-based) and will raise any new issues I find..
