### ISSUE TITLE
`ReadJournal` for inmem journal

### ISSUE THREAD

**Issue by ale64bit** [akka/akka#19339]
Is it possible to obtain a `ReadJournal` from the `akka.persistence.journal.inmem`? It would be very useful in order to test `PersistentActor`s, to assert that they actually emit the correct domain events without having to use a `PersistentView` (which is deprecated/limited) or some artificial mechanism.

**Comment by patriknw** [comment]
There are several inmem journal plugins for testing purposes listed here: http://akka.io/community/

**Comment by ale64bit** [comment]
@patriknw Fair enough. Thanks!
