### ISSUE TITLE
NPE from ActorGraphInterpreter

### ISSUE THREAD

**Issue by jroper** [akka/akka#19338]
This is probably the fault of my code, but the exception doesn't leave me any wiser as to what the problem could be:

```
java.lang.NullPointerException: null
	at akka.stream.impl.fusing.ActorGraphInterpreter$ActorOutputBoundary.subscribePending(ActorGraphInterpreter.scala:262) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:421) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:547) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.1.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.1.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.1.jar:na]
```

**Comment by jroper** [comment]
Actually, this looks like it might be a legitimate Akka streams bug, I'm guessing `exposedPublisher` is `null`, and while other methods guard access to `exposedPublisher` with a null check, `subscribePending` doesn't.

This is in Akka streams 2.0.1 by the way.

**Comment by ktoso** [comment]
Thanks for reporting, will look into it soon!

**Comment by patriknw** [comment]
This looks like a bug to me. `ExposedPublisher` is supposed to be the first message, but `SubscribePending` is received first.

@jroper do you have a pointer to the code that triggers this bad behavior?

**Comment by jroper** [comment]
It's probably a bit complex, but here we go.

Firstly, I *think* this is being thrown on the client side, but I'm not 100% sure.  We're using Akka streams both in the client and on the server here (in the same JVM, and actor system even).  The exception doesn't say which stream it was thrown from.  But we do get the following exception from the client:

    akka.stream.AbruptTerminationException: Processor actor [Actor[akka://application/user/StreamSupervisor-13/flow-3-4-unknown-operation#757072000]] terminated abruptly

The other thing that says this is probably the case is that it happens both with the Akka HTTP server backend and the Netty backend server.  The client is a simple low level WebSocket client built on Netty that we wrote purely for testing (we wrote our own so that we can easily send illegal things and test the server handling of it, hard to do illegal behaviour with a proper client).  It uses Netty reactive streams, if you need to see that, here's the [Publisher](https://github.com/typesafehub/netty-reactive-streams/blob/master/netty-reactive-streams/src/main/java/com/typesafe/netty/HandlerPublisher.java) and the [Subscriber](https://github.com/typesafehub/netty-reactive-streams/blob/master/netty-reactive-streams/src/main/java/com/typesafe/netty/HandlerSubscriber.java).  The client itself is [here](https://github.com/jroper/playframework/blob/streams-2/framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala).

One interesting thing about it that just occurred to me that could mess with the ordering of messages that you're expecting, it has a cycle.  The WebSocket is exposed as a flow, messages in go to the server, messages from the server come out of the flow.  The WebSocket protocol requires that when the server initiates close by sending a close message, the client has to ack it by sending the close message back.  So this is implemented by putting a merge before the send to the server, and a broadcast after, and one of the outputs of the broadcast goes through a filter and back into the merge.

Finally, here's the code that runs the flow:

```scala
Source.empty[ExtendedMessage].via(flow).runWith(Sink.ignore)
```

All this test is doing is checking that when the client closes the WebSocket, everything on the server side is terminated correctly.

**Comment by drewhk** [comment]
this looks like a legitimate bug.

**Comment by rkuhn** [comment]
Thanks for the very detailed report, @jroper, I think we have a pretty good idea of what is causing this and @drewhk is working on a fix. Would you be able to test-drive before we merge the PR? This might be really difficult to reproduce in a compact test case.

**Comment by drewhk** [comment]
here you are: https://github.com/akka/akka/pull/19411

**Comment by jroper** [comment]
The NPE appears to be fixed, thanks!

Interestingly, some tests that weren't failing before now seem to be failing consistently.  I'll have to look into this a little deeper to work out what's going on.

**Comment by drewhk** [comment]
Yes, that is expected. The bug happened when the stages wrapped by the actor failed earlier than the actor was fully initialized. I actually wanted to comment here that you have to expect new failures that might have been masked by this, but forgot :(
