### ISSUE TITLE
Use splitAfter in Websocket.scala

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19348]
As commented there it should simplify the flows a bit:

```scala
.splitWhen(_.isMessageEnd) // FIXME using splitAfter from #16885 would simplify protocol a lot
```

https://github.com/spray/akka/commit/6980a0ba61291cb71064267c1b7864de96ddd01a#diff-32111086a8e0b3bf2b812bda44d7c0a1R116

**Comment by jrudolph** [comment]
I wonder if that's still the best way to go or if we should rather go the same way as with http (#19255) to replace splitWhen/prefixAndTail with a graph stage doing the same.

**Comment by ktoso** [comment]
Good idea, GraphStage may indeed be nicer.

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
