### ISSUE TITLE
FAILED: akka.persistence.fsm.LeveldbPersistentFSMSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19343]
Multiple test failures

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3333/consoleFull

**Comment by drewhk** [comment]
Haven't been reported in 7 months, closing.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2101/changes
