### ISSUE TITLE
[akka-http] closing websocket connection doesn't send on complete message to the underlying sink

### ISSUE THREAD

**Issue by Tvaroh** [akka/akka#19346]
I create `sink` and `source` separately to serve websocket connections using akka-http:

```scala
val in: Sink[Message, Unit] = ???
val out: Source[Message, Unit] = ???
upgrade.handleMessagesWithSinkSource(in, out)
```

Input sink is defined as follows:

```scala
val in = flowImpl(connection.id, responder)
  .to(Sink.actorRef[CommandContext](protocolHandler, CloseConnection(connection.id, connection.userId, responder)))

// parses incoming JSON messages
def flowImpl(connectionId: ConnectionId, responder: Responder): Flow[Message, CommandContext, Unit] = ???
```

The problem is that when websocket connection is closed no `CloseConnection` is sent to the `protocolHandler` actor behind the sink.

On the other hand, if I transform input flow with a `PushStage` and do `ctx.finish()` in its `onPush` method, then `CloseConnection` is sent as expected. It is counter-intuitive that this doesn't work for the former case though.

**Comment by Tvaroh** [comment]
In meantime I'm interested in a workaround for detecting when websocket connection is closed.

**Comment by jrudolph** [comment]
This may be related to #19340. Did that work with 2.0-M3?

**Comment by jrudolph** [comment]
Which side closes the connection in your case?

**Comment by Tvaroh** [comment]
@jrudolph can't tell about 2.0-M3, it's a fresh code using 2.0.1 version. Regarding the closing side... I'm not sure - either Chrome's websocket client or akka-http itself.

**Comment by jknight12882** [comment]
Seeing the same thing in #19285

**Comment by jrudolph** [comment]
I published a version with the fix for #19340 to https://oss.sonatype.org/content/repositories/netvirtual-void-1037. You need to include the resolver and then adapt the organization name for akka-http/akka-stream artifacts like this:

```scala
resolvers += "Staging" at "https://oss.sonatype.org/content/repositories/netvirtual-void-1037"

libraryDependencies += "net.virtual-void" %% "akka-http-core-experimental" % "2.0.1-ws-fix"
```

Could you check if that fixes it?

**Comment by Tvaroh** [comment]
@jrudolph sure, will check it tonight.

**Comment by Tvaroh** [comment]
@jrudolph no difference.

**Comment by jrudolph** [comment]
As @ktoso explained in #19285 you need to finish the outgoing side (the Source side) to finally close the connection. Can you explain what you did exactly in the case where it worked?

**Comment by jrudolph** [comment]
I created #19359 to discuss further measures to ensure that WS connection are actually closed when the peer closed the connections.

**Comment by Tvaroh** [comment]
It never worked, only if I close connection from the server side using `PushStage` (both in and out):

```scala
  def mkCloseConnectionStage(responder: Responder,
                             connection: Connection): Stage[CommandContext, CommandContext] =
    new PushStage[CommandContext, CommandContext] {
      override def onPush(command: CommandContext, ctx: Context[CommandContext]): SyncDirective =
        if (command.commandType == CommandType.Disconnect) {
          responder.finish()
          ctx.finish()
        } else {
          ctx.push(command)
        }
    }
```

But I have no option to know that the connection is closed out of my control.

**Comment by rkuhn** [comment]
This definitely smells like a bug, if it still persists.

**Comment by Tvaroh** [comment]
@rkuhn and it definitely needs giving a kick for someone to fix. :)

**Comment by ktoso** [comment]
I don't think kicking anyone will get this resolved :-)
Self contained reproducer would help us get started on it once we get to it though.

**Comment by rklaehn** [comment]
I got the same problem. Is there a workaround or a fix in sight?

**Comment by danslapman** [comment]
Same, need a fix!

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
@danielhopkins if you need this feature the best way to see it happen is contributing it :-)
Thanks in advance!
