### ISSUE TITLE
Grammatical error in akka-docs/rst/scala/futures.rst

### ISSUE THREAD

**Issue by kubukoz** [akka/akka#19355]
Change
"it can sometimes become quite complicated and hard read"
to
"it can sometimes become quite complicated and hard **to** read"

**Comment by ktoso** [comment]
Please submit a PR to fix it :-)

https://github.com/akka/akka/edit/master/akka-docs/rst/scala/futures.rst 
and https://github.com/akka/akka/edit/master/akka-docs/rst/java/futures.rst

Please title the commit as `=doc #19355 fix typo in docs`.

Thanks!

Btw so cool to see you here, how do you like Akka so far? :)

**Comment by kubukoz** [comment]
I like it a lot, although I'm still going through the docs.

Thanks for the title ;)

**Comment by kubukoz** [comment]
Also, this error doesn't exist in the Java version of the docs.

**Comment by ktoso** [comment]
Oh, awesome then :)
