### ISSUE TITLE
Consider auto-closing of WS connections on receipt of Close frame

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19359]
Currently, the client handler can choose when to close a Websocket connection by issuing completion on the outgoing side of the Websocket handler flow. This is also valid when the peer already tried to close the connection.

In #19285 and #19346 (and myself in https://github.com/jrudolph/akka-http-scala-js-websocket-chat) people have shown to expect that the WS connection is closed automatically when the peer tries to close it.

Effectively, it boils down to the question whether WS supports half-closed connections. [RFC 6455](http://tools.ietf.org/html/rfc6455#section-5.5.1) says

> If an endpoint receives a Close frame and did not previously send a Close frame, the endpoint MUST send a Close frame in response.  (When sending a Close frame in response, the endpoint typically echos the status code it received.)  It SHOULD do so as soon as practical.  An endpoint MAY delay sending a Close frame until its current message is sent (for instance, if the majority of a fragmented message is  already sent, an endpoint MAY send the remaining fragments before sending a Close frame).  However, there is no guarantee that the endpoint that has already sent a Close frame will continue to process data.

So, that's not really a definite answer as well.

It may still make sense to implement (optional but default?) auto-closing of the WS connection when the peer has closed the connection.

**Comment by ktoso** [comment]
Thanks a lot for collecting the instances and RFC together.
I agree that this should be: implemented, optional, yet default.

That seems to be the most typical use case and when someone wants to do the "I'm still streaming my stuff and will close soon" they'll start looking and find the other version.

API wise WDYT about having options on the `handleWebsocketMessages` method?
I'm happy to take this on if you'd prefer to focus on some other ticket from the :next ones?

**Comment by rklaehn** [comment]
+1

**Comment by marekzebrowski** [comment]
+1 for optional, default close

**Comment by ktoso** [comment]
Triaged, let's do it – should not be too hard. If someone is interested in contributing this one let us know!

**Comment by danslapman** [comment]
@ktoso I want to fix it :-) I just checked `UpgradeToWebSocket.scala` and some other sources but didn't understand, how connection is handled, can You help me a bit?

**Comment by danslapman** [comment]
+1, please do it!

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
