### ISSUE TITLE
GREAT GETTING STARTED TICKET: Replace all StatefulStage usages with GraphStages

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19361]
AFAICS (the last remaining ones live mostly in HTTP)

- [ ] FrameOutHandler
- [x] Duplicator
- [x] ChunkTransformer
- [x] HandlerStage
- [x] FrameOutHandler - https://github.com/akka/akka/pull/19362
- [x] FrameEventRenderer - https://github.com/akka/akka/pull/19362
- [x] Masker - done by @zhxiaogg 
- [x] UpgradeStage - https://github.com/akka/akka/pull/20835
- [x] ByteStringParserStage - done by @agolubev 
- [x] Duplicator2

**Comment by talp-traiana** [comment]
So if I want to try one of these, I should just open a PR for it?
Any suggestion on which one will be an easy one to start with?

**Comment by ktoso** [comment]
Yup, pick any one you like and translate to a GraphStage :)
I'm almost done with `FrameOutHandler` so not that one, other than that all are fair game - thanks for the help!

Duplicator should be very simple actually - the one in `FlowStagesSpec`. Since we have other Duplicator impls that are GraphStages :)

**Comment by hepin1989** [comment]
@ktoso you could add an (WIP by x)

**Comment by ktoso** [comment]
sure, please declare what you're working on guys :)

**Comment by talp-traiana** [comment]
OK, I'll start with Duplicator (in its various incarnations), and take it from there.

**Comment by agolubev** [comment]
Will start ByteStringParserStage if you don't mind

**Comment by agolubev** [comment]
Ok, so making http.impl.util.ByteStringParserStage is actually about removing this class (as new already exist io.ByteStringParser) and migrating DeflateDecompressor to new parent ByteStringParser #16529

**Comment by talp-traiana** [comment]
While trying to convert Duplicator2 to GraphStage, I ran into a small issue.
It appears that Java doesn't like InHandler and OutHandler - despite only having 1 abstract method, Java does not consider them functional interfaces and, what's more, claims that the methods that are already implemented (e.g.: onUpstreamFailure) also need to be (re)implemented.

**Comment by rkuhn** [comment]
@talp-traiana InHandler / OutHandler are indeed not functional interfaces, lambda syntax would not be appropriate for them.

**Comment by rkuhn** [comment]
What you were probably asking (sorry for being slow): you can use AbstractInHandler and friends if you want to use the default termination behavior.

**Comment by talp-traiana** [comment]
@rkuhn Yeah, that's what I was looking for, thanks. I'm not sure why I didn't see it myself...

**Comment by agolubev** [comment]
moved following to GraphStages:
* ByteStringParserStage 
* DeflateDecompressorBase
* GzipDecompressor
* DeflateDecompressor
* StreamUtils.limitByteChunksStage
* DummyDecoder.newDecompressorStage

now fixing tests

**Comment by agolubev** [comment]
@ktoso, what about PushStages from Ops.scala like Map, Filter, TakeWhile?

**Comment by agolubev** [comment]
@ktoso, can you mark Duplicator and Duplicator2 as done or remove them from list - there are no such classes anymore

**Comment by ktoso** [comment]
Sure, thanks :)

**Comment by poojadshende** [comment]
I am working on ChunkTransformer and HandlerStage and I will make a PR

**Comment by zhxiaogg** [comment]
I'll try Masker, if no one is working on it.

**Comment by pchordia15** [comment]
I'll work on UpgradeStage.

**Comment by pchordia15** [comment]
Class | Assignee | PR
ChunkTransformer | poojadshende | 
HandlerStage | poojadshende |
Masker | zhxiaogg |
UpgradeStage | pchordia15

**Comment by poojadshende** [comment]
@ktoso I am working on issue #19361(replacing statefulStage usage with graph stage). I am trying to replace it for ChunkTransformer class.
I am getting error in onUpstreamFinish. Below is original code
```
override def onUpstreamFinish(ctx: Context[ByteString]): TerminationDirective =
      terminationEmit(Iterator.single(defaultLastChunkBytes), ctx)
```
what should i use for terminationEmit in below modification
```
override def onUpstreamFinish(): Unit = {

    }
```

**Comment by ktoso** [comment]
Thanks @zhxiaogg for the Masker impl :-)

Now only remaining is the `FrameOutHandler` :-)

**Comment by gosubpl** [comment]
Is `FrameOutHandler` still free to take? Would be happy to work on it.

**Comment by agolubev** [comment]
@gosubpl, seems like it's the only that left. (it's not simple though)

**Comment by gosubpl** [comment]
@agolubev simple seems to be the opposite of fun :) let me have a crack at it...

**Comment by gosubpl** [comment]
@ktoso can you please check whether you haven't done `FrameOutHandler` already in #19362

**Comment by gosubpl** [comment]
Working on `FrameOutHandler`.

**Comment by gosubpl** [comment]
@ktoso @agolubev I did a bit of digging and found PR 19362 with all the necessary code. If that is fine - I'll be very happy to submit a PR.

**Comment by gosubpl** [comment]
This ticket looks to be fully done.

**Comment by ktoso** [comment]
That's super cool :-) Thanks for noticing!
