### ISSUE TITLE
Cleanup: GraphStage-directly vs. andThen SymbolicStage

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19360]
We currently have a mix of styles how we create stages:

``` scala
  def grouped(n: Int): Repr[immutable.Seq[Out]] = andThen(Grouped(n))

// vs.

def groupedWithin(n: Int, d: FiniteDuration): Repr[immutable.Seq[Out]] = {
    // ... 
    via(new GroupedWithin[Out](n, d).withAttributes(name("groupedWithin")))
  }
```

Use of `Stages.DefaultAttributes` also is not consistent in recent GraphStage impls.

// via @viktorklang

**Comment by ktoso** [comment]
// cc @rkuhn @drewhk (once you're back, no hurry)

**Comment by rkuhn** [comment]
This is an interesting question: do we regard the GraphStage as an AST node as well as an implementation? If so, we need to make all relevant parameters accessible so that different implementations are possible. If not then we need to create SymbolicStage nodes for everything. I’m leaning towards the first option.

**Comment by drewhk** [comment]
The first seems to be more simple to follow and more maintainable, so +1 on that. Btw, andThen works on PushPullStage and since earlier stages were not rewritten to GraphStage you cannot use `via` directly, but you need to wrap the stage first -- exactly what andThen does.

**Comment by viktorklang** [comment]
@drewhk @rkuhn First proposal sounds more easily maintainable to me. Do we need to clarify something in GraphStage to make sure users don't shoot themselves in the foot if they create custom GraphStages? (i.e. they must be immutable etc)

**Comment by rkuhn** [comment]
Yes, good point @viktorklang, we should make it clear that a GraphStage is a reusable blueprint and should behave as such. Could you ticketify and/or do that? Thanks a lot!

**Comment by viktorklang** [comment]
@rkuhn Done

**Comment by rkuhn** [comment]
I removed the `discuss` label because we have set a course, now we only need to implement it :-)

**Comment by He-Pin** [comment]
@patriknw should this one be closed now?

**Comment by johanandren** [comment]
I believe this discussion was resolved.
