### ISSUE TITLE
Docs should indicate support for Persistence Query

### ISSUE THREAD

**Issue by acjay** [akka/akka#19374]
I'm working on a new project using Akka Persistence, but I'm at a bit of a loss as to how to implement my query side. It's an awkward time, because the docs list Persistent View as deprecated, but the replacement in Persistence Query is experimental, and not universally supported. For my application, throughput isn't going to be extreme, so the chosen backend DB for the journal is almost arbitrary. I'm trying to figure out the simplest option to choose that would be production-worthy from a standpoint of having proper backups and a simple failover story. The docs don't give a whole lot of guidance. It's unclear even [which plugins](http://akka.io/community/#journal-plugins) support Persistence Query.

**Comment by patriknw** [comment]
[akka-persistence-cassandra-3x](https://github.com/krasserm/akka-persistence-cassandra) has support for queries

**Comment by ktoso** [comment]
Yeah this is a good point, though we don't maintain those so we'll need to skim the libraries or ask the authors to update the entries.

I wanted to update our community site so it's easier to search etc, I'd do that in one sweep with updating the list I think. 

Thanks for reporting!

**Comment by ktoso** [comment]
I opened a related ticket on the website repo:  chttps://github.com/akka/akka.github.com/issues/275
Closing this one here.
