### ISSUE TITLE
Document how to integrate other JSON libs via Support traits explicitly

### ISSUE THREAD

**Issue by acjay** [akka/akka#19378]
(cross-posted here http://stackoverflow.com/questions/34669848/akka-http-accept-application-json-in-post-requests)

I'm trying to use [circe][1] to do my JSON (de)serialization in an Akka-Http app, rather than spray-json. For that reason, I want to use the [`entity`][2] directive with `as[String]` to get the string representation of the request body, and then do my own deserialization. But it seems that `entity` is too smart for its own good, and is rejecting anything that does not have the Content-Type `text/plain`.

My understanding from the docs is that implicit magic should let me be able to do something like: 

    import akka.http.scaladsl.model.ContentTypes
    entity(as[String].forContentTypes(ContentTypes.`application/json`))

But the compiler is not doing the whole thing of inferring that I want `as` to resolve to a `FromEntityUnmarshaller[String]`, which has that implicit method `forContentTypes`, whose result should be converted to a `FromMessageUnmarshaller[String]`, which (due to contravariance) should satisfy the need for a `FromRequestUnmarshaller[String]`.

However, even holding the compilers hand by doing:

    val jsonRequestToStringUnmarshaller: FromRequestUnmarshaller[String] = 
      messageUnmarshallerFromEntityUnmarshaller(implicitly[FromEntityUnmarshaller[String]].forContentTypes(ContentTypes.`application/json`))
    entity(jsonRequestToStringUnmarshaller)

my server is *still* rejecting `application/json` requests.

What gives?

  [1]: https://github.com/travisbrown/circe
  [2]: http://doc.akka.io/docs/akka-stream-and-http-experimental/current/scala/http/routing-dsl/directives/marshalling-directives/entity.html#entity

**Comment by ktoso** [comment]
This is more of an akka-user question than a ticket, but in general – it's exactly as answered on SO.
forContentTypes is not used for that, it's for narrowing. Instead you want to implement the same kind of "support trait" like we have for SprayJson: https://github.com/akka/akka/blob/master/akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala

As you see the core of it is `FromEntityUnmarshaller[JsValue]`, you'll need the same but `[circe-target-type-here]`. Hope this helps!

Closing this as it's not really a ticket we can work on, but I'm happy to reply and or help you get this solved nevertheless!

I'd love to see a small CirceSupport library, it's a great project! Would be cool if you could share what you come up with :-)

**Comment by ktoso** [comment]
Or I'll open but mark it an documentation ticket, we should explain how to integrate other JSON libs better.

**Comment by acjay** [comment]
Thanks! For ease of experimenting with multiple libraries, I'm trying to centralize my library coupling, which means not deserializing directly to a library-specific type in my routes. So I actually do still want to go to `String` first, with content type `application/json`. But I think I probably have the tools to make my correct marshaller now. I'll probably OSS my decoupling library, because I think that might be of some use to others, too!

It would seem to me though that it should be easier to modify existing marshallers in this way, although perhaps there would be dangers to this that I'm not seeing.

**Comment by ktoso** [comment]
Also related, circe is in fact integrated already in @hseeberger's library here: https://github.com/hseeberger/akka-http-json/blob/master/akka-http-circe/src/main/scala/de/heikoseeberger/akkahttpcirce/CirceSupport.scala

**Comment by ktoso** [comment]
Would be very nice to see some contribs around this :)

**Comment by hseeberger** [comment]
@ktoso, are you suggesting to add documentation on how to use akka-http-json, e.g. for Circe?

**Comment by ktoso** [comment]
Yes, I think let's embrace that

**Comment by hseeberger** [comment]
Cool. I put it into my backlog.

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
