### ISSUE TITLE
some problem in akka stream Graph cycles 

### ISSUE THREAD

**Issue by cjuexuan** [akka/akka#19379]
In akkastream doc 
![doc](http://7xnz7j.com1.z0.glb.clouddn.com/doc.png)

but when I run the example , my code is :
```scala

  implicit  val system = ActorSystem("hhh")
  implicit  val mat = ActorMaterializer()
  val source = Source(1 to 10)
  // WARNING! The graph below stops consuming from "source" after a few steps
  RunnableGraph.fromGraph(GraphDSL.create() { implicit b =>
    import GraphDSL.Implicits._

    val merge = b.add(MergePreferred[Int](1))
    val bcast = b.add(Broadcast[Int](2))

    source ~> merge ~> Flow[Int].map(_ * 2) ~> bcast ~> Sink.foreach(println)
    merge.preferred <~ bcast
    ClosedShape
  }).run()

````

but it doesn't work ,,it like in a deadlock,I  watch thread with jconsole:
![jconsole](http://7xnz7j.com1.z0.glb.clouddn.com/jconsole.jpg)

**Comment by cjuexuan** [comment]
```scala

// WARNING! The graph below stops consuming from "source" after a few steps
RunnableGraph.fromGraph(GraphDSL.create() { implicit b =>
  import GraphDSL.Implicits._
 
  val merge = b.add(MergePreferred[Int](1))
  val bcast = b.add(Broadcast[Int](2))
 
  source ~> merge ~> Flow[Int].map { s => println(s); s } ~> bcast ~> Sink.ignore
            merge.preferred              <~                  bcast
  ClosedShape
})
```
I also try the code in doc,can't work too.

**Comment by cjuexuan** [comment]
the problem also in ：
```scala

RunnableGraph.fromGraph(GraphDSL.create() { implicit b =>
import GraphDSL.Implicits._
val zip = b.add(ZipWith((left: Int, right: Int) => left))
val bcast = b.add(Broadcast[Int](2))
val concat = b.add(Concat[Int]())
val start = Source.single(0)
source ~> zip.in0
zip.out.map { s => println(s); s } ~> bcast ~> Sink.ignore
zip.in1 <~ concat <~ start
concat <~ bcast
ClosedShape
})

```

**Comment by cjuexuan** [comment]
```scala

 implicit val mat = ActorMaterializer(ActorMaterializerSettings(system).withAutoFusing(false))


```

**Comment by ktoso** [comment]
There's a big warning above that piece of code which you copied as well:
`// WARNING! The graph below stops consuming from "source" after a few steps`

It is exactly that, a sample showing how a deadlock could occur in a cycle.
Just a few lines below that code snippet the solution is explained (`.. includecode:: ../../../akka-samples/akka-docs-java-lambda/src/test/java/docs/stream/GraphCyclesDocTest.java#dropping`)

Hope this explains things :)

**Comment by cjuexuan** [comment]
@ktoso  thanks

**Comment by cjuexuan** [comment]
@ktoso  the demo just means make the the stream flow or create a balance stream? but i think in my production  environment we should choose method `buffer` instead of make `fuse` off?

**Comment by ktoso** [comment]
Yes, this example showcases the need of using `.buffer()` when you have situations like this.
