### ISSUE TITLE
potential MessageDispatcher leak

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19371]
With the `def lookup(id: String): MessageDispatcher` implement currently,
The `MessageDispatcherConfigurator`
```
  private val instance = new Dispatcher(...)
```
Should use `lazy val` for safety and simple or keep the `lookup` synchronized.

**Comment by patriknw** [comment]
Note this comment in `lookupConfigurator`:

```
// It doesn't matter if we create a dispatcher configurator that isn't used due to concurrent lookup.
// That shouldn't happen often and in case it does the actual ExecutorService isn't
// created until used, i.e. cheap.
```

**Comment by ktoso** [comment]
AFAICS non-issue, closing.
