### ISSUE TITLE
Akka Http: Parsing of X-Forwarded-For should avoid DNS lookups if possible

### ISSUE THREAD

**Issue by cmbaxter** [akka/akka#19388]
As mentioned in this forum post:

https://groups.google.com/forum/#!topic/akka-user/e5cl-TjGqNg

I think it's a good idea to try and avoid DNS lookups when parsing the X-Forwarded-For header.  The InetAddress.getByName method is smart enough to see if the value supplied is an ip vs a host, but if it is a host, it will result in a DNS lookup. For our own purposes, we dispose of hosts in the XFF as we consider that fishy as none of our proxy layers would ever append a host and therefore we throw that component of the XFF out.  I don't know if this will be the case for everyone, so my thinking is that maybe you guys can introduce a setting that controls whether host filtering is done on the XFF header values.  If enabled, then I think a simple filter operation on the list of Strings that can consult a regex or multiple (ipv4, ipv6, ipv6 hex compressed) regexes first to drop items that are not deemed to already be IPs.  It can still use InetAdress.getByName after going through the filtering as you are hedging that you won't get a DNS lookup now because all you have left are IPs.  That would keep things pretty simple as opposed to having to take the next step, which is converting the addresses to Array[Byte] and going through InetAddress.getByAddress instead.

I played around with this using the following regexes and things worked well:

      val ipv4 = """^(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$""".r
      val ipv6 = "^(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$".r
      val ipv6HexComp = "^((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)::((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)$".r

**Comment by ktoso** [comment]
Thanks for noticing and reporting!

**Comment by ktoso** [comment]
Sounds like a good move in general, but I fear slapping a regex in there – I remember having recently optimised actor path validation how even simple regex can quickly blow up to being very slow (or literally blow up). Parsing IPs not that hard, so we should perhaps parse them using parboiled properly.

Would you be interested in hacking on this @cmbaxter and contributing?

**Comment by ktoso** [comment]
// cc @jrudolph @sirthias

**Comment by jrudolph** [comment]
Wouldn't it be enough to make sure there is a `RemoteAddress` constructor which takes an IP address (String) but which will never try to resolve it?

**Comment by cmbaxter** [comment]
@jrudolph, that's actually a really good idea.  I personally don't need the RemoteAddress to be able to give me an InetAddress.  All I really want is the raw string address.  So maybe change the constructor for RemoteAddress.IP to take the raw String and defer the creation of the InetAddress until someone calls toOption, or not at all, depending if you want to remove that relationship entirely.  That way it becomes an explicit choice by the caller to want an InetAddress and with that choice comes the potential for a DNS lookup.

**Comment by ktoso** [comment]
Less work sounds even better :+1: :wink: 
Sounds relatively easy, would you like to pick it up @cmbaxter ?

**Comment by cmbaxter** [comment]
Absolutely.  I will pick this up on Monday of next week if that's okay with you guys.  I will take a look at the contributing page (https://github.com/akka/akka/blob/master/CONTRIBUTING.md) and let you know if I have any questions.

**Comment by ktoso** [comment]
Awesome, thanks! Wanted to know if I should allocate time to hack on it or if you'd like to help out – thanks a lot in advance :)

**Comment by cmbaxter** [comment]
@ktoso, no problem.  Should have a PR on Monday

**Comment by cmbaxter** [comment]
@ktoso, @jrudolph, hey guys, I have a couple of quick questions before I get started:

* What branch should I pull down and then create my feature branch from.  I'm assuming it's master now as that's where I see the http/streams code event though the Contributing docs say to use "release 2.3-dev" for http (note this branch no longer exists)
* The Contributing docs describe three types of changes and thus 3 possible prefixes on the commit comment: breaking api, non breaking api addition and neutral api change.  My intention here is to change the constructor of the IP class to no longer take an InetAddress and instead take a String for the ip.  I will also have to change and/or remove some of the apply methods in the RemoteAddres object.  As such, I consider this a breaking api change.  Do you agree?

I'm going to pull down master and assume that's the right branch unless I hear otherwise.  Let me know what you think about these two questions.

**Comment by ktoso** [comment]
Hi @cmbaxter,
we're in the middle of moving streams development to the `master` branch (today) and have not updated the CONTRIBUTING.md yet, sorry about that.

Your PR should target `master` but the branch is not ready yet, so you can develop on `streams-http-2.0` for now and we'll move it to master (or you retarget the PR to master after I've fixed the build today).

This is a breaking change, yes – it will land on `master` but not on the 2.0 branch.

**Comment by cmbaxter** [comment]
@ktoso, thanks for the heads up.  Just ping me when you are done with the moving of the branches.  I'll wait until then before getting started.

**Comment by cmbaxter** [comment]
@ktoso, once I started digging into the code changes, I started to realize that this might not actually be prone to the issue that I initially stated.  It looks like the header for X-Forwarded-For is parsed via this code in the `akka.http.impl.model.parser.SimpleHeaders` trait:

    def `x-forwarded-for` = {
      def addr = rule { (`ip-v4-address` | `ip-v6-address`) ~> (RemoteAddress(_)) | "unknown" ~    push(RemoteAddress.Unknown) }
      rule { oneOrMore(addr).separatedBy(listSep) ~ EOI ~> (`X-Forwarded-For`(_)) }
    }

If you then look at the rule definitions for `ip-v4-address` and `ip-v6-address` you can see that both vet the input against each respective specification and if they match, then the byte[] variant of the address is supplied to the `RemoteAddress.apply` method and not the `String` variant.  In this case, the safe `InetAddress.getByAddress` is called instead of the less safe `InetAddress.getByName`.  It also looks like, according to that rule logic, that if you supply something that is not an address (host name) then the entire `X-Forwarded-For` is ignored and is treated like it wasn't supplied in the first place.

It looks like the `String` variant of the `apply` from `RemoteAddress` is only used in this method from the `X-Forwarded-For` companion:

   def  apply(first: String, more: String*)

This code does not appear to be used in the server parsing of the headers anywhere and appears to just be convenience code for perhaps testing where you are applying that header to a request that you want to test against some routing logic.

So I'm not sure any change is really required here.  Thoughts?

**Comment by rkuhn** [comment]
Based on your findings I would suggest:

* to remove the convenience method in the companion that is currently unused
* to write a test that verifies that a hostname in that header is actually ignored

**Comment by cmbaxter** [comment]
Okay, can I create my branch off of master now or do I still need to use stream-http-2.0?

**Comment by ktoso** [comment]
You can start on `master` and if we need to / can we'll backport (cherry pick to 2.0) @cmbaxter.
In general master is the development branch now, and 2.0 is only important fixes – as it's the last JDK6 compatible streams.

**Comment by cmbaxter** [comment]
@ktoso, sorry I took so long on this.  Was very busy with work.  Here is the PR.  Let me know if I need to change anything:

https://github.com/akka/akka/pull/19584

**Comment by ktoso** [comment]
No problem at all, thanks for hacking on it!

**Comment by cmbaxter** [comment]
I see the build failed based on my changes due to a compilation issue.  I'll take a look and amend the PR with an additional commit

**Comment by cmbaxter** [comment]
This appears to be the `extractClientIP` directive.  In it, if no XFF and no RemoteAddress headers, it looks for one called x-real-ip.  Because this is not model parsed and is a raw header, the value here is a string and is trying to use the no longer existing String `apply` from `RemoteAddress`.  

    headerValuePF { case h if h.is("x-real-ip") ⇒ RemoteAddress(h.value) }

So this is closer to the problem the original issue was trying to protect against.  If some attacker send x-real-ip headers on requests and sent them as hostnames, the old code would perform DNS lookups.  Ideally here, I would leverage the same code used in the header parsing rules to vet the string to make sure it's either an ipv4 or ipv6 address and then use the byte[] based `InetAddress.getByAddress`.  Need to see if something like that is feasible.  @ktoso or @drewhk, thoughts?

**Comment by drewhk** [comment]
I think that is an excellent idea to use the `byte[]` version.

**Comment by ktoso** [comment]
Thanks, very nice change and just in time before stabilized API :)
