### ISSUE TITLE
FAILED: GroupByTest.required_spec309_requestZeroMustSignalIllegalArgumentException

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19385]
Too tight timeout, 500ms?

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4737/consoleFull

**Comment by patriknw** [comment]
SplitWhen required_spec309_requestZeroMustSignalIllegalArgumentException

https://jenkins.akka.io:8498/job/akka-multi-node/1302/consoleFull

**Comment by patriknw** [comment]
VirtualProcessorSingleTest required_spec309_requestZeroMustSignalIllegalArgumentException
https://jenkins.akka.io:8498/job/akka-nightly/3013/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3020/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3021/consoleFull

**Comment by drewhk** [comment]
I increased the timeout before, so these might be real issues?

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3026/consoleFull

**Comment by drewhk** [comment]
another one: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5215/consoleFull

**Comment by 2m** [comment]
More `akka.stream.tck.VirtualProcessorSingleTest` failures:

(Mar 6, 2016 3:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3118/consoleFull
(Mar 4, 2016 4:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3564/consoleFull
(Mar 4, 2016 3:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3112/consoleFull
(Mar 3, 2016 9:17:00 PM) https://jenkins.akka.io:8498/job/akka-nightly/3110/consoleFull
(Mar 2, 2016 3:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3106/consoleFull
(Mar 1, 2016 3:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3103/consoleFull
(Mar 1, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3102/consoleFull

**Comment by patriknw** [comment]
@rkuhn you fixed something with VirtualProcessor. Does that mean that tck failure tickets related to that should be closed?

**Comment by drewhk** [comment]
I check when that was merged

**Comment by drewhk** [comment]
Merged March 9, so if there were no new failures this can be closed.

**Comment by drewhk** [comment]
https://github.com/akka/akka/pull/19864

**Comment by patriknw** [comment]
no more failures after the merge, so closing
