### ISSUE TITLE
sharding + ddata + rememberEntities without akka-persistence?

### ISSUE THREAD

**Issue by jamesmulcahy** [akka/akka#19389]
I may be overlooking some details here, but it seems to me like it ought to be possible to use this combination without needing akka-persistence.

For the "cluster starting from scratch" scenario, I'd still need to manually start the shard regions, of course.  But for the rebalance scenarios, it ought to be possible for the cluster to store sufficient state in ddata such that the shards will auto-restart after a the rebalance.

Is this feasible, if so, please consider this as a feature request.  If it's not, I'd be interested to know what I'm overlooking.

**Comment by patriknw** [comment]
That is currently not implemented, but it should be possible. Some thoughts will be required to handle many entities in an efficient way.

**Comment by patriknw** [comment]
This is solved by #22154

**Comment by jamesmulcahy** [comment]
Fantastic!  Thank you, @patriknw
