### ISSUE TITLE
should EndPoint verify the recipientAddress?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19387]
I encounter this problem because my coworker bind at 0.0.0.0,but I connet him at 192.168.0.118.
```
      case r @ (_: RemoteRef | _: RepointableRef) if !r.isLocal && !UntrustedMode ⇒
        if (LogReceive) log.debug("received remote-destined message {}", msgLog)
        if (provider.transport.addresses(recipientAddress))
          // if it was originally addressed to us but is in fact remote from our point of view (i.e. remote-deployed)
          r.!(payload)(sender)
        else
          log.error("dropping message [{}] for non-local recipient [{}] arriving at [{}] inbound addresses are [{}]",
            payloadClass, r, recipientAddress, provider.transport.addresses.mkString(", "))
```
It give me a 
![image](https://cloud.githubusercontent.com/assets/501740/12199060/332b4d16-b650-11e5-803e-b33cced46129.png)
if we need to verify the `recipientAddress` how about dispatch the verification first by different `protocol`,and then via the sub `host: Option[String], port: Option[Int]` section?
for the TCP I use,I think I think bind to `0.0.0.0` should be valid.otherwise 
the akka.remote.transport.Transport#listen should return a Future[(Seq[Address], Promise[AssociationEventListener])]

and for security,we have ssl,why have this check then?

**Comment by patriknw** [comment]
I think binding to `0.0.0.0` is possible with the new `bind-hostname` / `bind-port` http://doc.akka.io/docs/akka/2.4.2/scala/remoting.html#remote-configuration-nat
