### ISSUE TITLE
request.completeWithStatus(NOT_FOUND) results in 406 Not Acceptable

### ISSUE THREAD

**Issue by QMay** [akka/akka#19397]
A handler that completes a request with `request.completeWithStatus(NOT_FOUND)` when the incoming request has `Accept: application/json` results in a `406 Not Acceptable` response and entity "Resource representation is only available with these types: text/plain".

This is also the case when completing with `completeWithStatus(NOT_FOUND.intValue())`.

The correct behavior in this case should be the `NOT_FOUND` status code with no entity.

**Comment by QMay** [comment]
The behavior is the same even when completing with a custom StatusCode containing no entity:

```java
StatusCodes.custom(NOT_FOUND.intValue(),                                  
                                  NOT_FOUND.reason(),
                                  null,
                                  NOT_FOUND.isSuccess(),
                                  false)
```

**Comment by QMay** [comment]
"com.typesafe.akka" % "akka-http-core-experimental_2.11" % "2.0.1"
"com.typesafe.akka" % "akka-http-experimental_2.11" % "2.0.1"

**Comment by ktoso** [comment]
That's because it was rejected _sooner_ than your complete with status could be applied, due to content type negotiation AFAICS.

Thanks for reporting, this is more of an docs ticket to explain how this works.

**Comment by jrudolph** [comment]
I think this is a bug. AFAIU Content-Type negotiation only applies to representations of the actual resource and, therefore, should only be used for successful responses (= status code 200).

**Comment by ktoso** [comment]
Thanks for chiming in @jrudolph! I'll promote it to a bug so we look into it sooner rather than later

**Comment by ktoso** [comment]
I'm looking into fixing this and so far only found `If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.` in the RFC, looking for something that would indicate the "only applies to representations of the actual resource", hm hm.

**Comment by jrudolph** [comment]
I'd say this is part of the "Proactive" vs. "Reactive" negotiation distinction in RFC 7231. Maybe @sirthias can remember where this was specified exactly.

http://tools.ietf.org/html/rfc7231#section-3.4.1
