### ISSUE TITLE
[akka-stream] some tls long links questions

### ISSUE THREAD

**Issue by huanwuji** [akka/akka#19391]
I use tls to data transfer for a long time.
 If I get a SessionTruncated, the stream when interrupt,So I must create a new connection to continue it. I try to send message to publisher actor and then call onCompleteThenStop to closed the stream, The connection will not clean make OutOfMemory.
Then I try set the timeout parameters for tcp, It will autoclosed and send a Cancel to publisher, but it's not closed immediately when occured SessionTruncated. It's will wait related by timeout paramters.
Having any other good idea to do this or SessionTruncated can be resumeing?

**Comment by ktoso** [comment]
Would you be able to share more details how you're using this and what exact stacktrace you're getting? Thanks in advance!

**Comment by ktoso** [comment]
// cc @sirthias @jrudolph @rkuhn

**Comment by huanwuji** [comment]
```scala
  def outgoingConn = clientTls(Closing.ignoreComplete) join Tcp()
    .outgoingConnection(remoteAddress = new InetSocketAddress(host, port), connectTimeout = 5.minutes, idleTimeout = 5.minutes)
```
```scala
      center.source(sourceName)
        .grouped(100)
        .mapAsyncUnordered(4) {
          x ⇒
            Future {
              val bs = ByteString fromArray KafkaProtoDataList(x).toByteArray
              TcpComponent.addLengthHeader(Gzip.encode(bs))
            }
        }
        .map(SendBytes)
        .via(outgoingConn)
        .map {
          case SessionBytes(a, b) ⇒ b
          case SessionTruncated ⇒
            log.info(s"$sourceName sessionTruncated")
            self ! StreamInterrupt(sourceName)
            ByteString.empty
          case x ⇒ log.info(x.toString); ByteString.empty
        }
        .via(TcpComponent.lengthFraming(10 * 1024 * 1024))
        .to(Sink.foreach {
          case x: ByteString ⇒
            x.toArray.grouped(TId.length).foreach {
              bytes ⇒
                val tId = TId.keyFromBytes(bytes)
                center.actor(tId.persistenceId).actorRef ! tId
            }
          case x ⇒ log.warning(s"$x transfer errors"); self ! StreamInterrupt(sourceName)
        }).run()
```
This is the kafka stream transfer to other client. So it's must keep a long links.
`SessionTruncated` will interrupt it.
The first when I get `SessionTruncated`, I will send message to source actor, then call `onCompleteThenStop `, It's will OutOfMemory when restart mutiple times. Then I dump the heap, Found the `TcpOutgoingConnection` is also exists. This means the connection haven't clear.
I give up it. Then I set timeout parameters. Then I found it's will send `Cancel` to publisher when timeout. But it's can't timely return `Cancel` call me to restart it.
Having any smarter method?

**Comment by huanwuji** [comment]
I'm resolved questions. 

It's must be add timeout arguments to release bad connections.  
And use source.tick send message for KeepAlive.
And then use watchTermination to listen connections closed and reconnection it.
On public network, I'm use it transfer 30million/per day meessages and already run 3 months. Don't restart it.
