### ISSUE TITLE
Create Sink.recent that allows to read latest element received from stream

### ISSUE THREAD

**Issue by agolubev** [akka/akka#19390]
I'm thinking about something similar to Sink.queue, but instead of SinkQueue `recent` will return monitor object that has latest element received from stream as well as stream status.

```scala
def recent[T](): Sink[T, SinkMonitor[T]]

trait SinkMonitor[T]{
   getState():StreamState[T]
}

sealed trait StreamState[+T]

case object NonInitialized  extends StreamState[Nothing]
case object Initialized  extends StreamState[Nothing]
final case class Recived[+T](result: T) extends StreamState[T]
final case class Failure(cause: Throwable) extends StreamState[Nothing]
case object StreamCompleted  extends StreamState[Nothing]
```
Use case I'm thinking is to send some statistics to such sink, like number of requests or throughput.

let me know if this makes sense.

**Comment by agolubev** [comment]
also such sink can have initialization-termination notifications:
```StreamState.terminationNotification():Future[Unit]``` and ```StreamState.initializationNotification():Future[Unit]```
similarly to #18565 termination notification combinator

**Comment by rkuhn** [comment]
Yes, this sounds useful: materializing to something that has a `get()` method and behaves like an AtomicReference that is updated from the stream.

**Comment by talp-traiana** [comment]
Is anyone working on this, or should I give it a shot?

**Comment by rkuhn** [comment]
no, it’s available as far as I can see, thanks!

**Comment by talp-traiana** [comment]
So I've been thinking about this a bit, and was wondering if it wouldn't be more useful to provide some sort of composite Sink (or Source, or any Flow for that matter) that wraps a sink and allows monitoring of the inner sink.
Something like:
def recent[T, M](inner: Sink[T, M]): Sink[T, (M, SinkMonitor[T])

What do you think?

**Comment by drewhk** [comment]
@talp-traiana well, create a flow, and then decorating a Sink becomes just an application for that Flow.

**Comment by talp-traiana** [comment]
@drewhk Not sure I understand what you mean (or maybe I don't understand what @agolubev was asking for).

The way I understand it, if I have a sink (e.g.: that writes messages to RabbitMQ) and I want to be able to monitor it (know what the last processed message is, check the sink state, etc.), how would I do it with API suggested in the OP? Won't I end up with 2 sinks, and no useful way to connect them (broadcasting messages to both sinks will give different results than wrapping)?

**Comment by drewhk** [comment]
My point was that if the required functionality is implemented as a Flow, then your use case of monitoring a Sink is just as simple as `monitoredSink = monitorFlow.to(originalSink)`

**Comment by talp-traiana** [comment]
I think generalizing this to something that can monitor general flows is a good idea, but I'm not sure that just adding it as an intermediate stage would achieve the original purpose. How would the flow know the sink somewhere downstream completed, or which message it processed last without wrapping it?

**Comment by drewhk** [comment]
everything that goes to the sink would flow through that flow. In terms of your proposed signature:
```scala
def recent[T, M](inner: Sink[T, M]): Sink[T, (M, SinkMonitor[T]) = monitorFlow[T].to(inner)
```

**Comment by talp-traiana** [comment]
But wouldn't it be processed by the flow *before* actually being processed by the sink? This would create a race condition where I the monitor might give me "premature" results.

**Comment by drewhk** [comment]
That is impossible to do in general. That only the Sink implementation can now as this is completely specific to that particular sink.

**Comment by talp-traiana** [comment]
Hmm... Couldn't I do something like a GraphStage that calls the sink's onPush, and then does the bookkeeping after it returns?

**Comment by drewhk** [comment]
That doesn't work that way, but it would be possible to check when the Sink pulls the next. However, this still does not translate to what you actually want:
 - the Sink might drop. You never know what it actually did, it is a black box
 - it might batch things before it does an action, hence consumption of elements from upstream are not necessarily tied to actually processing them
 - it might launch asynchronous tasks in the background
 - the Sink might be a composite, hiding a complex graph underneath

etc.

**Comment by talp-traiana** [comment]
I think that depends on the definition of "recent" in this context - there is value in providing the most recent message that the sink received (even if it hasn't finished processing), or even the most recent message that had its "message processing" part done.
Still, if there's no way to achieve it then it's a moot point. I'll just go ahead and implement it as a flow like you suggested.

**Comment by drewhk** [comment]
> the most recent message that the sink received (even if it hasn't finished processing), 

The issue is how do you define *received*? Have been put into a buffer? Processing has been started? Putting just a flow in front recording messages as they pass by (and carefully fusing it into the Sink!) is not semantically weaker than putting a hook immediately before onPush, because the only strong semantical definition of *received* can be by the Sink implementation itself. And of course non-atomic, graph based Sinks complicate this even further.

Your options are either to use the flow and accept the somewhat weaker semantics, or you have to put hooks into the Sink implementation itself, providing a semantically stronger domain dependent signal.

**Comment by talp-traiana** [comment]
> The issue is how do you define received?
That seems fairly straight-forward to me - every actor is defined by a receive method, and once receive(msg) returns, I can assume it received it (or maybe I should say I know it reacted to it). Did it launch some task asynchronously, or send a bunch of messages downstream? Possibly, but (at least in my experience) I don't usually care - they're the sink's responsibility to manage. And if I do care about them, then that's when I need the sink to provide the domain-dependent hooks/signals.

> Putting just a flow in front ... (and carefully fusing it into the Sink!)
What if the user disables fusing? Do you think I should explicitly fuse the monitor to the sink? It has the advantage of more closely matching what the we are trying to achieve here, but it might also be a little surprising...

**Comment by rkuhn** [comment]
It is unclear what you are really hoping to achieve here: processing within different stream processing elements is inherently concurrent, but that is nothing compared to an unsynchronized outside observer who reads some volatile field to get “recent” data—there is absolutely no guaranteed relationship between this observer and the stream and nothing you do will change that. Whether or not an observation point is fused to the Sink does not change this, it only may change the amount of temporal displacement. But since that displacement is not observable to an outsider, how can that be a problem?

**Comment by rkuhn** [comment]
BTW: knowing that the behavior of an Actor has been invoked is quite meaningless, I cannot imagine which kind of system you could build upon this knowledge unless that system also breaks Actor encapsulation.
