### ISSUE TITLE
Akka streams operation: dedupe

### ISSUE THREAD

**Issue by Horusiath** [akka/akka#19395]
This is the proposal of a new graph stage - reflected also in `FlowOps` DSL - which should filter out consecutive duplicates from the stream of events, working on similar rules as Rx [distinctUntilChanged](http://rxmarbles.com/#distinctUntilChanged) method works.

I'd like to contribute with this feature.

**Comment by drewhk** [comment]
Sure, nice contribution! The only thing we need to decide whether this is provided as a Flow, or added to the DSL as a method. (We usually don't like to add new DSL methods to avoid a mess there. Flows are reusable units, they can be organized into packages, etc.)

**Comment by viktorklang** [comment]
@Horusiath Thanks for picking up the ball here!

I found this in my git stash, which may serve as inspiration:

~~~scala
private[akka] final class Deduplicate[T](equiv: Equiv[T]) extends GraphStage[FlowShape[T, T]] {
  override val shape = FlowShape(Inlet[T]("deduplicate.in"), Outlet[T]("deduplicate.out"))
  val in = shape.in
  val out = shape.out
  override def initialAttributes: Attributes = DefaultAttributes.deduplicate
  override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) {
    setHandler(in, new InHandler {
      private[this] var lastPushed: T = null.asInstanceOf[T]
      override def onPush(): Unit = {
        val last = lastPushed
        val newIn = grab(in)
        if (last == null || !equiv.equiv(last, newIn)) {
          push(out, newIn)
          lastPushed = newIn
        } else pull(in)
      }
    })

    setHandler(out, new OutHandler {
      override def onPull(): Unit = pull(in)
    })
  }
  override def toString = "Deduplicate"
}
~~~

**Comment by rkuhn** [comment]
There was a lot of discussion in #19408, with the conclusion being that this kind of deduplication is too narrow a use-case to justify a combinator on FlowOps. More generic ones would be counting the running sequences of equivalent elements (compressed to `(Out, Long)`) and full hysteresis support.

**Comment by 2beaucoup** [comment]
Is this solved by `statefulMapConcat`?

**Comment by drewhk** [comment]
yes. Also, if someone wants to make a ready-made version of this, the right place would be: https://github.com/akka/akka-stream-contrib

**Comment by drewhk** [comment]
Added a ticket there instead.

**Comment by cnnickolay** [comment]
An alternative solution with using sliding

```
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl._

object Dedup extends App {

  implicit val actorSystem = ActorSystem("streamer")
  implicit val materializer = ActorMaterializer()

  val source = Source(List(1, 1, 1, 2, 2, 2, 2, 2, 3, 4, 4, 5, 6))

  val flow = Flow[Int]
    .sliding(2, 1)
    .mapConcat { case prev +: current +: _=>
        if (prev == current) Nil
        else List(current)
    }

  // this value should be prepended to the source in order to avoid losing the first value
  val ignoredValue = Int.MinValue
  val prependedSource = Source.single(ignoredValue).concat(source)
  prependedSource.via(flow).runWith(Sink.foreach(println))
}
```

Output:
```
1
2
3
4
5
6
```
