### ISSUE TITLE
Websocket server leaks inner stream when peer closes connection (without sending close frame first)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19398]
As reported in https://groups.google.com/forum/#!topic/akka-user/8tozN2SX--g

This is a regression probably introduced in https://github.com/akka/akka/commit/cdee221b1565f18f809312daf028f8632728bdd3. Completion from `ProtocolSwitchStage.fromNet` triggers a completion of the whole stage. Previously, this also closed `toWS` and cancelled `fromWS`. These were replaced by a dedicated substream in cdee221b1565f18f809312daf028f8632728bdd3 which now needs to be completed/cancelled manually as well when the stage shuts down.

In this case it can probably quite simply be fixed. The question remains whether this is a more general problem with substreams created in a GraphStage. One one hand, it can certainly make sense to keep substreams around longer than the stage that created them but it seems to be prone to leaks like seen here.

**Comment by jrudolph** [comment]
The leak probably only happens if the Websocket connection is closed without sending WS close frames. Close frames reach the substream and trigger cleanup independently in that case.

@cleliofs provided a very helpful reproduction demonstrating the problem: https://github.com/cleliofs/websocket-stream

**Comment by cleliofs** [comment]
Thanks @jrudolph for raising a ticket for that. I will keep an eye on future milestone releases with a fix for that. Cheers.

**Comment by rkuhn** [comment]
I’m starting with incorporating the reproducer as a test case.

**Comment by rkuhn** [comment]
I’m having trouble with the reproducer: AFAICS the websocket session is never closed, so it is entirely correct that the flows don’t shut down. If I try it with Akka HTTP websocket client, then nothing leaks. If I add a `session.close()` for the client then nothing leaks. How can I get this to demonstrate the problem?

**Comment by jrudolph** [comment]
The client process needs to be shut down, for me this closed the TCP connection cleanly but without sending the Websocket close frame.

**Comment by rkuhn** [comment]
Oh, I see. I’ll try to somehow make that happen in a test case without spawning another JVM …

**Comment by drewhk** [comment]
This needs multiple things to backport #19430 and #19488 (which in turn contain multiple commits)

**Comment by drewhk** [comment]
This has been backported already, see https://github.com/akka/akka/pull/19430/files
