### ISSUE TITLE
HTTP().bindAndHandle() does not enforce the max connection setting

### ISSUE THREAD

**Issue by fsat** [akka/akka#19404]
It seems HTTP().bindAndHandle() no longer enforces the max connection setting. Consider the following setup:

```
val customSettings = ServerSettings(actorSystem).copy(maxConnections = 1)
Http(actorSystem)
  .bindAndHandle(routeToMount, host, port, settings = customSettings)
```

Given the setup above, I would expect the max number of HTTP connection that the server would accept will be capped to `1`. However the limit doesn't seem to be enforced, i.e. I can open more than 1 connection.

Please find the reproducer attached:

https://github.com/fsat/akka-http-max-connection-test-stuff

**Comment by ktoso** [comment]
Thanks for reporting, will have a look.

**Comment by ktoso** [comment]
Not yet investigated, I've moved it to current version (and we'll backport if there's something to be fixed here_

**Comment by johanandren** [comment]
Tried to reproduce using this little guy:
```
 implicit val system = ActorSystem()
  import system.dispatcher
  implicit val mat = ActorMaterializer()

  val customSettings = ServerSettings(system).withMaxConnections(1)
  val counter = new AtomicInteger(0)
  Http()
    .bindAndHandle(Flow[HttpRequest].mapAsync(8) { req =>
      val id = counter.getAndIncrement()
      println(s"Req $id received")
      Future {
        Thread.sleep(5000)
        println(s"Req $id completed")
        HttpResponse()
      }

    }, "127.0.0.1", 8080, settings = customSettings)
```

Works as expected with one request being processed at a time. I guess this was solved by other changes since january.

**Comment by ktoso** [comment]
That's excellent to hear.
