### ISSUE TITLE
adapt contributing guidelines to omit project prefix from commit messages

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19413]
There was some discussion—although I cannot find it anymore on the internet—about the utility of the first part of our commit message convention:

    +str #XXXX <your message goes here>

The most important parts are the actual descriptive commit title and the issue number, we have so far not used the compatibility classification (the first character) nor the project abbreviation in any mission-critical fashion—unless I’m simply not aware of such use. @akka/akka-team please comment here whether we want to keep this or not.

/cc @2beaucoup

**Comment by drewhk** [comment]
The project prefix was kind of useful, but not much the flag. Alternative is tagging PRs, but that is more clicky-clicky. Or we just drop it.

**Comment by ktoso** [comment]
I enjoy it, but don't feel the need to enforcing it for external contributors.
I'd personally likely keep it in my PRs but don't mind if no-one else does – would someone mind that?

**Comment by patriknw** [comment]
I'm in favor of simplifying the commit message rules, especially for making it easier for contributors. This is how I adjusted it for akka-persistence-cassandra: https://github.com/akka/akka-persistence-cassandra/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages

**Comment by rkuhn** [comment]
Makes sense to me, @patriknw.

@ktoso I would mind anyone adding more things to the commit title, if it stays shorter than 60 characters.

**Comment by ktoso** [comment]
Would or wouldn't, second part of sentence sounds to imply wouldn't hmm

**Comment by ktoso** [comment]
Patriks rules sound 👌 ok

**Comment by rkuhn** [comment]
hah, you’re right of course: I meant to write “wouldn’t” :-)

**Comment by ktoso** [comment]
Ok cool, simplified guidelines sound good then :)

**Comment by hepin1989** [comment]
We could take a look at how netty do this.

http://netty.io/wiki/writing-a-commit-message.html

it tells why,how,and result.

**Comment by rkuhn** [comment]
In addition to the Netty style we do like to have the issue number in there if there was one (and there should be one in almost all cases).

**Comment by drewhk** [comment]
All I ask is to forget about the "imperative present tense" madness. It makes no sense at all. (*ducks*)
