### ISSUE TITLE
[akka-http] Client API for manually resolving hostnames to IP addresses

### ISSUE THREAD

**Issue by mpilquist** [akka/akka#19419]
Some web services require HTTP clients to perform client-side failover by resolving the hostname to a list of IP addresses and then trying each IP in succession in event of failure. Other services use a weak form of load balancing, where clients are required to make a request to a random IP from the DNS resolution.

Both of these cases can be supported with Akka HTTP 2.0 by manually resolving the hostname via `InetAddress.getAllByName` and then creating `HttpRequest` objects for each IP. However, constructing URLs with resolved IPs breaks HTTPS hostname verification, unless the server certificate has subject alternative name extensions for each of its nodes. As such, the only way to handle these use cases with Akka HTTP 2.0 is to disable hostname verification at an actor system level, which is a security vulnerability.

Instead, clients should be able to optionally specify the IP of the server on a per-request basis, where the IP is used instead of resolving the hostname in the request URL.

See https://gitter.im/akka/akka?at=569552acee13050b38a32091 for some short discussion.

**Comment by ktoso** [comment]
Thanks for reporting, use case makes sense.

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
