### ISSUE TITLE
add Sink.count

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19422]
but first clarify what it should materialize to: should it just fail on failures or should it still signal the number of successfully received element?

**Comment by drewhk** [comment]
The most general would be to always signal the number.

**Comment by rkuhn** [comment]
… which means a materialized value of type `Future[(Long, Try[Done])]`

**Comment by viktorklang** [comment]
What's the semantics?

**Comment by rkuhn** [comment]
how about
~~~scala
f.onComplete {
  case Success((count, Success(_))) => // stream completed normally
  case Success((count, Failure(ex))) => // stream completed with exception ex
  case Failure(_) => // the count stage itself failed
}
~~~

**Comment by rkuhn** [comment]
This is related to #19446: IOResult has been added and should be used.

**Comment by patriknw** [comment]
There was an attempt in https://github.com/akka/akka/pull/20353 but we decided that it was not worth adding such a specialized stage, since `fold` can be used.
