### ISSUE TITLE
add duplicate message detection support

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19421]
For me I think it should have a `cache`, a `feedback port` and a `TTL` of the element in the cache.like 
https://docs.jboss.org/hornetq/2.3.0.Final/docs/user-manual/html/duplicate-detection.html

**Comment by rkuhn** [comment]
you mean a Stream stage? (the description is a little light ;-) )

**Comment by hepin1989** [comment]
yes.I think it maybe like this 
``` 
val deduplicatedFlowAndFeedbackSink = Deduplicated(...)

source
 .via(deduplicatedFlowAndFeedbackSink.flow)
 .via(processing)
 .asloTo(deduplicatedFlowAndFeedbackSink.sink)
```

**Comment by rkuhn** [comment]
This cannot work: how would the `flow` and `sink` be connected internally? This component would not be reusable which leads to unpleasant surprises for users. The API should probably use the SubFlow infrastructure to ensure that the graph can be built consistently.

In any case, I think this is a good ticket to investigate, thanks for raising it!

**Comment by drewhk** [comment]
I don't get it why a feedback loop is needed. I thought that this is just a stage with memory and a TTL and simply drops elements that it had seen before.

**Comment by rkuhn** [comment]
Yes, that would also be useful; different setups are needed for at-most-once and at-least-once.

**Comment by hepin1989** [comment]
Yes,that api is not right,but I just copy from the kafka manually offset commit,in the akka side,what I want this is for helping achieve exactly once delivery ,once the message handling is not idempotent,we need something like this.

Still I think another part of this could be `sequencer` thing ,which attach a monotone increasing SeqNr or unique identity to the message ,which could be used latter.

Even not using the TTL,this pattern could be implemented by query the handled table in a transaction,and the table using the SeqNr/UID as the primary key.

I think this would help for which the message could be redelivery but the message must not be rehandling when it's not idempotent.

**Comment by rkuhn** [comment]
Hmm, thinking some more: this might not be as useful for the described use-case because what users want is to avoid processing something a second time—independent of whether the system crashed in between or not. Providing ephemeral in-stream deduplication will rarely be useful because upon failure the whole stream will need to be restarted and therefore lose its memory of what has been done already. This needs more thought.

**Comment by drewhk** [comment]
I disagree. You are thinking about one use-case and hence throw away a whole set of other use cases, like filtering out duplicates streamed from a storage (file) which has nothing to do with ephemeral streams more about large datasets that don't fit in memory. Those don't need any crash tolerance.

**Comment by rkuhn** [comment]
A generic deduplication stage will take space proportional to the stream size, so we’ll need to make this point a bit more specific: I can see the usefulness of both a sequencer (based on a sequence number extraction function for the incoming messages—with the assumption of contiguous sequence number usage) and a bounded equality-based deduplication stage (i.e. it will permit duplicates if they are too far from each other in the input stream). Are there others?

**Comment by drewhk** [comment]
Yep, there are probabilistic ones (i.e. Bloom filter like, hashes, etc.), too. I am not sure this is something we need for Akka Streams though, more specialized libraries should provide these. I opt for closing this ticket.

**Comment by rkuhn** [comment]
Good point.
