### ISSUE TITLE
enable MiMa for akka-protobuf, akka-osgi, akka-persistence-tck, akka-cluster-metrics

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19432]

**Comment by ktoso** [comment]
I don't think akka-protobuf was ever meant for anyone's except "Akka's" consumption, thus bin compat is not really something that people should care about there.

Instead we should:
- include akka-protobuf in our notice in release notes like we do with testkit that "Binary compatibility is not maintained for the following: akka-testkit and akka-multi-node-testkit" << add akka-protobuf here
- explain that if you want to use protobuf, use the "real" one, this one we only have here to a) use it ourselves and b) not conflict with other libraries
- it's not really our lib, we just repackage it to avoid classpath problems – why would we guarantee bin compat on it (as there may be a mismatch between their versioning / guarantees and ours).

**Comment by 2m** [comment]
Enabled MiMa checks for cluster-metrics and osgi projects in #19563.
