### ISSUE TITLE
add extractClientAddress to keep the ip and port

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19439]
Currently at http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.1/scala/http/routing-dsl/directives/misc-directives/extractClientIP.html#extractclientip
it only support extract the ip address,but I just encounter that the third party payment notification server need us to verify the port too.

**Comment by ktoso** [comment]
Sounds reasonable, thanks for reporting!
Would you want to fix that one?

**Comment by hepin1989** [comment]
after recheck it ,the current implement have had the `port`,sorry for the mis issued.
https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/RemoteAddress.scala#L34

**Comment by hepin1989** [comment]
I was check the spray part first,haha,much improved.

**Comment by ktoso** [comment]
That's very good to hear :smile:
