### ISSUE TITLE
Remove Java 6 Compatibility

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#19447]

**Comment by drewhk** [comment]
A bit more info would be nice :)

**Comment by ktoso** [comment]
`akka.http.impl.util.Java6Compat` :smile:

**Comment by 2beaucoup** [comment]
among others... ;)

**Comment by 2beaucoup** [comment]
I'll update the description once I'm through this.

**Comment by ktoso** [comment]
Thanks @2beaucoup !

**Comment by 2beaucoup** [comment]
Should I remove `HandlerX`/`AsyncHandlerX` in `akka.http.javadsl.server` and replace usages with lambdas?

**Comment by ktoso** [comment]
Usages for sure can be replaced with lambdas in all places.

Now thinking if we remove the interfaces too then. The only thing they help with is not having to write the `RequestContext, RouteResult` part of the handler functions, so Handler1 is 1 param etc. In case anyone sees them explicitly I think they may be helpful to keep - WDYT @jrudolph?

Note: We're also considering the other javadsl (closer to scaladsl), nothing decided yet yet though.
