### ISSUE TITLE
create StreamConverters form java.util.stream.Stream

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19443]

**Comment by drewhk** [comment]
Do you remember what where the conversion names we came up with?

**Comment by rkuhn** [comment]
something like `asJavaStream` and `fromJavaStream`, I think

**Comment by drewhk** [comment]
putting it back

**Comment by drewhk** [comment]
here is the in-progress PR: https://github.com/akka/akka/pull/19456

**Comment by drewhk** [comment]
Anyone, feel free to take my PR and finish this ticket.

**Comment by agolubev** [comment]
taking it if no objections

**Comment by rkuhn** [comment]
sure, thanks @agolubev !

**Comment by agolubev** [comment]
@drewhk, it seems for me that Sink.javaCollector (from here: https://github.com/akka/akka/pull/19456/commits/72a60674e782426d66de7e43bb75a57e352bd381#diff-fb0fa8a4e622c766a811e2af3a9a3289R226) will  not be so useful in case we implement materialization to java.util.stream.Stream (that's what I'm going to do). You suggested this in comment here: https://github.com/akka/akka/pull/19456#issuecomment-171686122

Do you want to keep Sink.javaCollector anyway?
