### ISSUE TITLE
convert from Scala Future to CompletionStage for javadsl packages

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19440]
This will need the scala-java8-compat library.

**Comment by jypma** [comment]
@rkuhn Maybe I'm a bit late to the party, but how is one to do a `flatMap` equivalent in Java when all you're getting out of the conversion is a `CompletionStage` instead of a `CompletableFuture`? `CompletionStage.thenCompose` takes a function of `T => CompletableFuture`, not `T => CompletionStage`.

For example (based on the current Future-based DSL):
```
   CompletionStage<HttpResponse> f1 = FutureConverters.toJava(akkaHTTP.singleRequest(...));
   CompletionStage<HttpResponse> f2 = f1.thenCompose ( response -> {
       // derive a second HTTP request based on [response]
       HttpRequest rq2 = ...;
       return FutureConverters.toJava(akkaHTTP.singleRequest(rq2)); 
       // ^^^ the above would be a compile error, since it does not return CompletableFuture
       // and .toCompletableFuture can't be used as explained in FutureConverters.
   }
```

**Comment by drewhk** [comment]
are you sure? Looking at this: https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html

I see:

<U> CompletionStage<U>	thenCompose(Function<? super T,? extends CompletionStage<U>> fn)
Returns a new CompletionStage that, when this stage completes normally, is executed with this stage as the argument to the supplied function.

<U> CompletionStage<U>	thenComposeAsync(Function<? super T,? extends CompletionStage<U>> fn)
Returns a new CompletionStage that, when this stage completes normally, is executed using this stage's default asynchronous execution facility, with this stage as the argument to the supplied function.

**Comment by jypma** [comment]
You're right. Nevermind, I was looking at an old post (http://www.nurkiewicz.com/2013/05/java-8-definitive-guide-to.html). Nothing to see here, sorry for the confusion.
