### ISSUE TITLE
simplify the signature of FlowOps.conflate

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19445]
The currently included mapping step conflates this stage with a `map`. Instead it should just reduce two elements into one whenever there is no demand:
~~~scala
def conflate(f: (Out, Out) => Out): Repr[Out]
~~~
All necessary mapping for special cases should be done by a `map` stage before or after this combinator—we want the primitives to be mostly orthogonal.

**Comment by drewhk** [comment]
I don't like this. The extra type `S` allowed to create a proper state type for stateful transformations, which now can be expressed by mapping the element first to a state, and then define merging states (`f`). I find this much less intuitive when expressing stateful logic.

**Comment by rkuhn** [comment]
I guess we don’t agree on the purpose of conflate, then. For me it is just a way to fold two elements into one, nothing else. This is needed where `.buffer(1, dropSomething)` does not cut it because the combination needs to modify the element that is to be preserved. What is your definition?

**Comment by drewhk** [comment]
My definition is that conflate is a fold, which is only folding if it is necessary. In your above signature, it is more like a reduce.

**Comment by rkuhn** [comment]
But to be useful as a fold, it would in general need to pass state across emissions, which the current one does not do. And the resulting signature would be rather complex. Do you think there is no value in providing a simple conflate? We might add the BFG as well, but that is for different things.

**Comment by drewhk** [comment]
No, it is a fold *between* emissions, not across. The current two proposals are similar and probably can emulate each other, but if you imagine your rollup as a `fold` (i.e. in terms of an B += A) instead of a `reduce` (A = A + A) then this expression requires some mental gymnastics. Maybe we should not have the name "conflate" but more precise names:
 - foldWhileBackpressured
 - reduceWhileBackpressured

(we can keep conflate for compatibility if we need, and just deprecate it)

**Comment by rkuhn** [comment]
Since the difference between the two is just the initial map (and the semantics of a collection foldLeft is slightly different since it provides a strict zero value), what is so bad about the following:
~~~scala
.conflate(reducer) // reduceWhileBackpressured
.map(initial).conflate(reducer) // foldWhileBackpressured
~~~
The latter even saves characters, and it requires the exact same number of function literals—it’s basically like making the currying of the current `conflate` more explicit.

**Comment by rkuhn** [comment]
another thought: `FlowOps.fold` also takes a strict initial value, not an initial transformation function, so naming it `foldSomething` would be slightly confusing—the signature of a `fold` is well established

**Comment by drewhk** [comment]
It is not about which can emulate the other. I can also say that yours is just simply:

```
.conflate(identity)(f) // reduce
```

This is not the point. The scala library also has `reduce` and `fold` even if they are very similar concepts. The point is that in your example I must express an otherwise aggregation logic (B += A) as a merge logic (A + A) which reads differently. It is all about intent.

**Comment by drewhk** [comment]
I personally think it is a very general fold, Scala or not. It has a "lift" method, and an accumulator method. Of course if you omit the seed method, and you just add a dummy seed value, which you check in the accumulator function and then provide the lifting yourself. So it does not change what is possible.

**Comment by rkuhn** [comment]
The impetus here comes from the desire of removing pieces which feel out of place: I’ve had to add `identity` in too much places, so I started thinking whether our base combinator might be the wrong one. Splitting off that first argument list into another base combinator that we already have gives the exact same API, just with one word between the parentheses. Therefore my conclusion was that what I propose now is more “basic” than what we currently have.

**Comment by rkuhn** [comment]
or another way: the question is whether the initial map should be opt-in or opt-out

**Comment by drewhk** [comment]
> The impetus here comes from the desire of removing pieces which feel out of place: I’ve had to add identity in too much places,

This does not imply the removal of the current signature.

> or another way: the question is whether the initial map should be opt-in or opt-out

I proposed to have both, just as Scala library has both `fold` and `reduce`.

**Comment by rkuhn** [comment]
So it boils down to that I like to mention “conflate–expand” as a pair :-) And I also do not like creating a fold that deviates from the usual fold signature.

So, we can agree on the signatures and that we’d add both, but the names remain TBD. I need to look into other things now.

**Comment by drewhk** [comment]
> So it boils down to that I like to mention “conflate–expand” as a pair

Since expand is unfold, you currently make it a non-pair.

> And I also do not like creating a fold that deviates from the usual fold signature.

As I mentioned, if you remove the lifting function and take a constant instead, you can still emulate the current functionality, so that is not essential (although I find it much more convenient this way).

**Comment by rkuhn** [comment]
Yes, we agree on the desired signatures, but not (yet) on the names.

**Comment by rkuhn** [comment]
Okay, settling on Batch as the new basis this ticket can be seen as sugar: just provide a default argument for the seed function (or an overload for Java).

**Comment by drewhk** [comment]
@johanandren you can add this simply to https://github.com/akka/akka/pull/19564 I think it better fits there.

**Comment by drewhk** [comment]
Ok, change in plans. Let's get this in indepentently of anything else.
