### ISSUE TITLE
simplify the signature of FlowOps.expand

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19444]
Instead of including an initial mapping step it is easier to use
~~~scala
def expand[T](f: Out => Iterator[T]): Repr[T]
~~~
which allows the most common case to be expressed as `.expand(Iterator.continually)`. It also allows interesting semantic extensions by having the Iterator stop emitting when it runs out of extrapolation power—in which case it waits for the next upstream element before proceeding.

**Comment by drewhk** [comment]
This is a good idea.
