### ISSUE TITLE
add IOResult type and use it for FileSink/Source

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19446]
~~~scala
case class IOResult(count: Long, status: Try[Done])
~~~
The meaning of the `count` member needs to be defined by the stage that emits or materializes to such an element, for byte streams it should be the number of bytes, but for a `Sink.count` it could also be the number of elements encountered (or individually scaled by a weight function).

**Comment by ktoso** [comment]
Type looks good, who's adding the `Done` first then :-)

**Comment by rkuhn** [comment]
that would be #19442
