### ISSUE TITLE
create Akka.Done and Akka.NotUsed types and use them instead of Unit

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19442]
This affects all APIs in Streams & HTTP, for Scala and Java. Wherever `Unit` is a type parameter (most notably but not exclusively as materialized value or in a `Future`) it should be replaced:

  * if the intent is to signal successful completion, use `Done`
  * if the intent is to signal no useful value, use `NotUsed`

This means that materialized values should generally be `NotUsed` instead of `Unit` and `Future[Done]` instead of `Future[Unit]`.

Users should not be able to create instances of these two singleton types. The type names should be as given, and for Scala they should also be singleton objects.

**Comment by drewhk** [comment]
Wait, so we change the type signatures for Scala too? Could this be a Java enum?

**Comment by drewhk** [comment]
hm, putting back, too much merge conflict possibility with the current pending PR. I take something else.

**Comment by drewhk** [comment]
Still taking, starting with the stream part -- that shouldn't have that much conflicts

**Comment by rkuhn** [comment]
Yes, this is for Scala signatures as well, and no, it cannot be an enum because that does not introduce the proper types.

**Comment by drewhk** [comment]
Why? What do you mean does not introduce the proper types?
```java
public enum NotUsed {
  INSTANCE
}
```

**Comment by rkuhn** [comment]
Ah, I thought you meant
~~~java
public enum NoValueTypes {
  NotUsed,
  Done
}
~~~
which would also have allowed idiomatic usage from Scala. How would we fix that? My thinking was more like
~~~scala
sealed abstract class NotUsed
object NotUsed extends NotUsed {
  def getInstance(): NotUsed = this
  override def toString = "NotUsed"
}
~~~

**Comment by drewhk** [comment]
I have a thing for enum singletons, scala or not :)

**Comment by hepin1989** [comment]
refs: new issue https://github.com/akka/akka/issues/19442
