### ISSUE TITLE
Add `Flow.auto` and `Sink.contramap`.

### ISSUE THREAD

**Issue by aloiscochard** [akka/akka#19452]
I would like to suggest a few combinators, I already have a PR ready with those:

Flow.auto (name taken from an other streaming lib I was using, I'm open to a suggestion that fit better the naming scheme of the project)
```
  /**
   * Helper to create `Flow` from a function.
   */
  def auto[A, B](f: A ⇒ B): Flow[A, B, Unit] = apply[A].map(f)
```

Sink.contramap
```
  def contramap[In2](f: In2 ⇒ In): Sink[In2, Mat] = Flow.auto(f).toMat(this) { (_, m) ⇒ m }
```

**Comment by drewhk** [comment]
So the benefit of `auto` is basically type inference?

**Comment by aloiscochard** [comment]
@drewhk yes exactly, forgot to explain the motivation on that one...

I can of course rewrite `contramap` without using `auto` if you feel the latter is unwanted.

**Comment by ktoso** [comment]
"`auto`" though under various different names has come up a number of times already.
Note that it used in isolation the type A needs to be spelled out anyway, as in `Source(a: A => a.toB)`,
yet it's pretty useful when lifting a method: `Source(method _)`

**Comment by rkuhn** [comment]
`contramap` should really be `def prepend[T](f: Flow[T, In]): Sink[T]`, should it not? Our algebra is that of stream combinators, which means that a bare function is a “foreign” element.

**Comment by drewhk** [comment]
At lest we should have `prepend`. Of course `flow.to(sink)` is exactly the same as `sink.prepend(flow)`, but it seems like people looking for this functionality in `Sink` and not `Flow`.

**Comment by aloiscochard** [comment]
@rkuhn good point, I can see both as being useful (I'll probably use more often `contramap`, as I use value classes a lot, that's the original reason for this PR).

I suppose we could then implement `contramap` in term of `prepend` then.

Also the naming `contramap` give intuition for the contravariant functor "interface", where one might intuitively expect working with a "pure" function.

References to some definitions of contramap:
- http://docs.typelevel.org/api/scalaz/nightly/index.html#scalaz.Contravariant
- https://github.com/non/cats/blob/master/core/src/main/scala/cats/functor/Contravariant.scala#L10
- https://dwhjames.github.io/datomisca/api/0.7.x/index.html#datomisca.functional.ContraFunctor
- https://hackage.haskell.org/package/contravariant-1.3.3/docs/Data-Functor-Contravariant.html

**Comment by rkuhn** [comment]
I guess there is enough reason for both methods; we removed them because we wanted to make the DSL flow only from left to right, IIRC. One could ask why only the `map` combinator should get special treatment then, though. Are there other “contra”-things to be considered?

**Comment by drewhk** [comment]
I only mentioned prepend, which does not need to explode like contramap could (as in why not others). And the only reason I mentioned prepend because people somehow expect it on Sink instead of Flow (I like the Flow.to version better nowadays, but fan service :) ).

**Comment by aloiscochard** [comment]
@rkuhn as `Flow` is isomorphic to `Function1`, I realize it would make sense to have `Flow#contramap` which works on the input parameter, agree?

**Comment by rkuhn** [comment]
No, Flow is not isomorphic to Function1, not at all. My gut feeling is that contramap would feel a bit outlandish and might want to stay in an external library for now. It is easier to add something later than to remove something once finalized.

**Comment by aloiscochard** [comment]
@rkuhn Yeah sorry about the wrong iso statement, I'm tired.

I'm surprised about your opinions regarding `contramap`, but I would love to understand:
For instance, following your reasoning why do you have `Flow.map` instead of `Flow#append[T](f: Flow[Out, T]): Flow[In, T, _]`?

That does not feel consistent to me, and that impact how I use the API because it feel counter-intuitive and not symmetric.

**Comment by rkuhn** [comment]
Well, we have a _huge_ number of combinators on FlowOps, all designed for a left-to-right DSL. `contramap` would be the only exception, the odd one out, therefore I ask whether it really has that high value that it must be included. This is why I also asked whether there are others, but I don’t think “contrafilter” or “contragrouped” make much sense. BTW: it cannot be on FlowOps because that can only express changes to the RHS of the Flow.

Another consideration:
~~~scala
Flow[Int].filter(_ > 42).contramap(String.valueOf).map(_.toString)
~~~
I find that confusing to the point of not wanting to let users write that … which is another way of saying that we’d need a really good reason to make that possible. This same argument applies to `prepend` as well, BTW (but not on Sink).

**Comment by aloiscochard** [comment]
@rkuhn thanks for the explanation, I now understand your reasoning based on how the DSL is read.

I suppose I have different opinions as I'm coming from `machines` where there is operators to use the library in any direction (left to right or right to left, weirdly enough the later is my favorite!), I surely understand the motivation to favor one other the over for simplicity sake.

I still believe the name `contramap` is well suited for `Sink` in the same way `map` is a nice name for what it does on `Flow`/`Source`, do you agree?

Also, that is really where I want to use it. My concrete use case: I have a `Sink[Foo]` and a newtype `Bar` that wrap `Foo`, and I want to make my sink works for `Bar`, I have this use-case a lot.

**Comment by rkuhn** [comment]
Yes, that is what I meant: a Sink can grow only in one direction, so there we might contemplate it—while Flow is pretty much locked down to left-to-right notation. This is also less of a problem because Sink does not have combinators right now anyway, so adding one is not that inconsistent as it would be for Flow.

I’d prefer the name lifting a function into a Flow to be `fromFunction` (to be symmetrical with BidiFlow). A PR with that plus `Sink.{prepend,contramap}` would be welcome.

**Comment by aloiscochard** [comment]
@rkuhn great! thanks for taking time sharing your design choices for the DSL.

I'll adapt my PR and push it asap.

**Comment by drewhk** [comment]
I have to admit I don't like contramap (not super against it, but slightly). I only proposed prepend because of discoverability, and my experience that people do not expect somehow `flow.to(sink) == sink`.
