### ISSUE TITLE
emitMultiple in GraphStage does not call andThen if iterator is empty

### ISSUE THREAD

**Issue by prettynatty** [akka/akka#19457]
https://github.com/akka/akka/blob/7ee50d18ae9793e21960e6d4d00f6fb3ed0cf4fa/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L760

`emitMultiple` does check `if (element.hasNext)` and if it is false it does nothing but should call `andThen`.

**Comment by drewhk** [comment]
Ok, this will get into 2.0.2 if I am quick enough

**Comment by prettynatty** [comment]
Thanks!
