### ISSUE TITLE
Failure using `Builder` to create `ByteString`

### ISSUE THREAD

**Issue by briantopping** [akka/akka#19466]
https://github.com/briantopping/akka/tree/wip-ByteString-builder has an extra test in `akka/util/ByteStringSpec.scala`. It demonstrates that when a `Builder` is created for a `ByteString`, a `Vector` is produced. Which is fine, but the `result` should return a `ByteString`. Instead, it returns a `Vector`.

Is this correct behavior? Should this test be turned into a PR?

**Comment by luben** [comment]
Putting a little bit more into it.

ByteString implements Traversable through IndexedSeq <: GenericTraversableTemplate. One of the the trait methods is "genericBuilder" that should return new builder for the collection. Currently ByteString does not implement this method and inherits the implementation from GenericTranversableTemplate that gets it from companion.newBuilder but ByteString do not provide also the "companion" method so it gets it from IndexedSeq that defaults to returning VectorBuilder (as the most generic IndexedSeq).

This represents a problem when trying to generically serialize/deserialize scala Traversable collections: deserializing through the genericBuilder of ByteString results in Vector[Byte] that is not expected.

The right solution is to add "companion" method to the ByteString sealed abstract class that returns the ByteString companion object. Another option is to implement directly the "genericBuilder" method.

**Comment by briantopping** [comment]
Awesome, thanks! My brain is pretty fried from learning the guts of Kryo this week :) 

I think you did most of the work here, do you want to gen the PR or shall I take a swing at it?

**Comment by luben** [comment]
Yes, I'll do it.

**Comment by luben** [comment]
I took a closer look - it looks like a hard task to reconcile the standard library expectations and the ByteString implementation. The main difficulties:

- the companion method should return GenericCompanion[IndexedSeq] and it expect the collection itself to be parametic over the item type.

- in the similar way the genericBuilder requires Builder of generic collection which ByteString isn't

You can give it a try if you have an idea how to solve it.

**Comment by patriknw** [comment]
@luben sounds like there were no solution here, shall I close the ticket?

**Comment by briantopping** [comment]
This may have been a PBKAC on my part, closing.

**Comment by luben** [comment]
Yes, sorry for not closing it earlier. We took care of the exception on the akka-kryo-serialization library side creating a specialized serializer for ByteString

**Comment by patriknw** [comment]
thanks
