### ISSUE TITLE
ReceivePipeline needs a Handled Delegation

### ISSUE THREAD

**Issue by DomBlack** [akka/akka#19463]
At the moment if a trait using ReceivePipeline adds a deathwatch on another actor, it has a choice to make when receiving the Terminated:

1, Return HandledCompletely and possibly block the underlying actors or other pipelines deathwatches
2, Return Inner(msg) and possibly cause a DeathPactException

There needs to be a third Delegation which is `Handled` which acts like Inner and allows inner pipelines or the base behaviour to execute, however does not trigger the unhandled logic if the base behaviour doesn't do anything with the message.

**Comment by rkuhn** [comment]
I’m not sure we should do this: Akka Typed provides a more principled way of composing behaviors, and it has types as well, so it may make sense to get that ready for prime time instead. WDYT?
