### ISSUE TITLE
=osgi Fix version imports

### ISSUE THREAD

**Issue by briantopping** [akka/akka#19462]
Now that version numbers are unified, clean up version range generators for OSGi.

**Comment by ktoso** [comment]
Thanks! And thanks even more since PR coming up it seems :)

**Comment by briantopping** [comment]
all good m8. I'm dying to get through this serialization issue, really taking the starch out of me, but learning a lot on the path. "marathon, not a race"...

**Comment by briantopping** [comment]
bump

**Comment by briantopping** [comment]
I'm pretty sure this was resolved in another issue, closing.
