### ISSUE TITLE
Akka streams TCP support silently handles failures

### ISSUE THREAD

**Issue by jroper** [akka/akka#19469]
When Akka streams' TCP stage handler gets an upstream failure, it sends an abort message to the stream, but drops the exception, leaving the user in the dark about why the connection was reset.  This is particularly frustrating if the bug that is causing the failure is not in the end users code, for example, if the bug is in Akka HTTP, eg as in #19467, because there's nothing the user can do, short of diving into Akka streams internals with a debugger, to work out what is going wrong.  Akka streams should log any failure exceptions when it aborts the connection.

**Comment by jroper** [comment]
Problem code is here:

https://github.com/akka/akka/blob/stream-http-2.0/akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala#L271

**Comment by drewhk** [comment]
Hm, the only reason why it does not call a failStage right there because it waits first on the `Aborted` response. But then it already loses the original exception. The questions I have here:
 - is it enough to fail the stage (i.e. it will fail its output port if it is open)
 - if not, then which loglevel should it be logged?

So if we know what we want here it is an easy fix.

**Comment by rkuhn** [comment]
Different question: every failure will be logged at ERROR level where it originates, is that not enough?

**Comment by jroper** [comment]
That's not the current behaviour is it?  If you're referring to changing things such that when a GraphStage does the wrong thing, eg pull from a closed stream, then it should be logged then and there, yes, I think that's fine, since that will always be a bug, and being noisy about bugs is good.  Just make sure the stack trace is logged too.

**Comment by drewhk** [comment]
I marked this for possible backport, since this can help debug issues reported on the 2.0.x line. We can remove the tag if we decide to leave this out.
