### ISSUE TITLE
GraphStage must be documented to be a reusable blueprint

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#19471]
This in order to increase the chances that internal and user-defined implementations will conform to expectations. Also see #19360

**Comment by drewhk** [comment]
I would add one more step: let's compile a minidoc for contributors on when, how and where to add new combinators. There are many questions here that needs at least some fuzzy initial guidance:
 - what combinators do we accept? Of course this is not definable, but sometimes it is easier to show some counterexamples that are trivially no-go
 - if a combinator is to be accepted, where should it go? I.e. FlowOps, Source, Sink or external object
 - if accepted and goes into the FlowOps/Source/Sink APIs then describe all the places where modifications needs to be done
 - establish a guideline for testing these and documenting these

**Comment by drewhk** [comment]
(since these are common contributions)

**Comment by rkuhn** [comment]
Contributions are out of scope for this ticket, @drewhk please open a new one.

**Comment by drewhk** [comment]
ok, here it is: https://github.com/akka/akka/issues/19793
