### ISSUE TITLE
Conflicting or ambiguous document regarding actor restarting process

### ISSUE THREAD

**Issue by oklahomer** [akka/akka#19470]
In the current version of [documentation about actor supervision and restarting](https://github.com/akka/akka/blob/ecc916abfd9253b42a002d345277f28366c4b8ff/akka-docs/rst/general/supervision.rst#what-restarting-means), there is a section that describes the restarting sequence in detailed steps.

In step 3, it says "wait for all children which were requested to terminate (using context.stop()) during preRestart to actually terminate; this—like all actor operations—is non-blocking, the termination notice from the last killed child will effect the progression to the next step."

However, in step 6, the document reads "send restart request to all children which were not killed in step 3"

So in step 3 it's saying the restarting actor waits till the last killed child to respond, but step 6 indicates the chance of existing undead child actor. So I'm a bit confused. Does this have something to do with [the ```Terminated``` message being sent independently from actual termination process](https://github.com/akka/akka/blob/ecc916abfd9253b42a002d345277f28366c4b8ff/akka-docs/rst/java/untyped-actors.rst#lifecycle-monitoring-aka-deathwatch)? It would be nice if the documentation is updated and clear out ambiguity.

Other than this part those detailed steps were really helpful, and I appreciate that.

Thanks in advance.

**Comment by drewhk** [comment]
> So in step 3 it's saying the restarting actor waits till the last killed
child to respond, but step 6 indicates the chance of existing undead child
actor. So I'm a bit confused. Does this have something to do with the
Terminated message being sent independently from actual termination process
<https://github.com/akka/akka/blob/ecc916abfd9253b42a002d345277f28366c4b8ff/akka-docs/rst/java/untyped-actors.rst#lifecycle-monitoring-aka-deathwatch>?
It would be nice if the documentation is updated and clear out ambiguity.

No, it is not that. In `preRestart` you are allowed to explicitly kill your
children, in your code (i.e. user code). Step 6 simply states that all the
actors that you have not killed manually in that hook will be restarted,
and this happens strictly after the actors that you explicitly killed has
been all stopped.

There are no undead actors. By default every actor in the tree underneath
is restarted, but you are free to override this behavior by calling
`context.stop()` on children you want to kill. Every actor is either killed
this way or restarted by the system.

-Endre

**Comment by oklahomer** [comment]
Thanks, I got it now. I completely misread it.

So what this section is saying is that we can optionally control if the child actor(s) should stop or restart; Either by calling ```context.stop()``` manually in ```preRestart``` to have them stopped, or wait till Step 6 to have them restarted.
And it is guaranteed that all restarting process is done after the completion of ```context.stop()```, so there won't be any confliction such as to-be-stopped actor accidentally gets restarted in step 6 before its stoppage.

**Comment by drewhk** [comment]
yes, exactly.

-Endre
