### ISSUE TITLE
add websocket directive that defers to an ActorRef

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19475]
using #19474 this should place a rate limiter on the inbound messages and pipe to/from the Actor

**Comment by ktoso** [comment]
Would be an excellent candidate for a contrib

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
