### ISSUE TITLE
startPosition option for FileIO.fromFile

### ISSUE THREAD

**Issue by prettynatty** [akka/akka#19483]
`FileIO.fromFile` should accept `startPosition` option to make it possible not to read the whole file when only part of it is needed. I propose this change to improve `getFromFile` route in akka-http to make it not to read the whole file if client requested only a part of it.

**Comment by prettynatty** [comment]
I've made changes in my fork: https://github.com/akka/akka/compare/master...prettynatty:file-io-from-file-start-position-prettynatty

**Comment by hepin1989** [comment]
why not a range ?

**Comment by prettynatty** [comment]
shouldn't startPosition be enough because client which needs range will request only needed bytes and complete itself?

**Comment by ktoso** [comment]
I agree adding the option to skip a part of a file makes sense, however I'd like to add it via a new options setting rather than such a very specific parameter. We also need to change API here to make it possible to use `OpenOptions` since we're now JDK8+ so we could smuggle it through using an OpenOption hm... Will look more into it soon, thanks for the issue and PR!

**Comment by ktoso** [comment]
Note to team: marking this as `stream-http-master` as this is something that touches API and is likely to be resolved via changes which we need to do "because JDK8" anyway

**Comment by prettynatty** [comment]
I discovered another one problem with `FileIO.fromFile`: as it uses `java.io.File` it has problems with unicode filenames on some linux deployments. It's hard to make a test which 100% reproduces in every test environment but there are many evidences that `java.io.File` works terrible with unicode paths. 

Migrating from `java.io.File` to `java.nio.Path` and / or `java.nio.Path` has to solve problem.

**Comment by ktoso** [comment]
It uses File because we were JDK6 compatible :wink: 
Now we can (and want to) move to Path, sure.

**Comment by mkiedys** [comment]
What should be available in `OpenOptions` besides `startPosition`?

**Comment by Korbik** [comment]
What is the status of the issue ? 
I've made a new patch using the modification from @prettynatty for the FileIO#toPath and FileIO#fromPath [diff](https://github.com/akka/akka/compare/release-2.4...Korbik:wip-file-io-startPosition) The associated PR : #22657

**Comment by ktoso** [comment]
Thanks, it seems others have dropped the ball on this issue - thanks for picking it up again @Korbik

**Comment by patriknw** [comment]
This was never included in 2.5.0, it will be in 2.5.1.
It's also in 2.4.x.
