### ISSUE TITLE
[Akka Typed] Rename Behavior.management (and message)

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#19492]
In my opinion `management` is counter-intuitive. As the purpose of this method is handling (it's a handler) signals, I suggest renaming it `handleSignal` or `onSignal`.

In addition, I think `message` should also be renamed: `handleMessage` or `onMessage`.

**Comment by rkuhn** [comment]
good suggestion

**Comment by patriknw** [comment]
or receiveMessage receiveSignal ?
