### ISSUE TITLE
[Akka Typed] Should behaviors really be case classes?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#19491]
While it might be convenient for whatever reason to make `Static`, `Full`, etc. case classes, I'm a bit on the fence with this choice:
- First, case classes indicate "this is a value object" (in the DDD sense), but behaviors aren't
- Second, these classes take a (partical) function as argument and hence one of the core features or case classes – equality and hashing – works unexpectedly

I suggest to change these to normal classes and promote the class parameters to vals where needed.

**Comment by rkuhn** [comment]
Your argument about equality is a good one, and it would be cool if we could solve that: a Behavior is indeed just a piece of data that describes a reaction to a given input. As such I’d like to treat it as a value.

Idea: match on which PartialFunction implementation class it is and also compare the values it has closed over. This needs reflection, but it would be so nice …

**Comment by hseeberger** [comment]
What exactly do you mean with "PartialFunction implementation class"?

**Comment by rkuhn** [comment]
~~~
scala> class A extends Actor { def receive = { case m => println(m) } }
defined class A

scala> :javap A
[...]
  public scala.PartialFunction<java.lang.Object, scala.runtime.BoxedUnit> receive();
    Code:
       0: new           #88                 // class A$$anonfun$receive$1
       3: dup
       4: aload_0
       5: invokespecial #92                 // Method A$$anonfun$receive$1."<init>":(LA;)V
       8: areturn
~~~
Every close definition site creates a class. While it is in general not possible to decide whether two definitions describe the same behavior, we can certainly say that the same definition generates the same behavior if all values it captured are the same as well. This could be done by looking at the fields of class `A$$anonfun$receive$1`.

**Comment by patriknw** [comment]
I think this is also important for making it easier to evolve these in a binary compatible way.
