### ISSUE TITLE
HTTP: Move away from case classes for configuration classes

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19514]
Because we'll have to binary compatible with http-core we need to move away from case classes for configuration objects ASAP.

More info via @patriknw :

>  January 18, 2016 4:28 PM @ktoso re case classes, yeah they are a nightmare to evolve, and settings classes are expected to be expanded over time. I abandoned case classes for all settings classes in cluster tools, e.g. https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ClusterShardingSettings.scala

**Comment by ktoso** [comment]
FYI @sirthias @jrudolph 
It's not a pleasant change but we'll need to make it, I think I'll be able to make it this week

**Comment by sirthias** [comment]
Ok. Unpleasant indeed but I can certainly see the benefits.
Looking forward to what you cook up.

**Comment by ktoso** [comment]
For reference, and maybe someone has a great idea, what I'm battling with since a bit is trying to address this TODO: https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala#L295 while making configs non-case classes (not directly related, but related "enough" I felt, and may touch APIs - well in DSLs though).

Here's a tricky place:
![fileuploaddirectives_scala_-_akka_-____code_akka__-_intellij_idea__minerva__iu-143_1820_1](https://cloud.githubusercontent.com/assets/120979/12465551/dc4e8a0c-bfce-11e5-8c04-4af2a0defca4.png)

Ideas to fixing it include requiring an implicit materializer, from which we can obtain the config, though it then may break existing code in non nice ways... Ideas how we could make it nice?

**Comment by ktoso** [comment]
(WIP is here: https://github.com/ktoso/akka/tree/wip-config-non-case-class-ktoso )

**Comment by jrudolph** [comment]
I would vote against introducing new implicit parameters for configuration. We tried hard to get rid of them where possible. But, I think it should be possible without. I think you can get there by rearranging the definitions in MultipartUnmarshallers. It should work because an unmarshaller has access to a Materializer.

The only thing that may be needed is changing `multipartUnmarshaller` approx. like this:

```scala
def multipartUnmarshaller[...](..., parserSettingsOverride: Option[ParserSettings]): ... =
  Unmarshaller.withMaterializer { implicit ec => materializer =>
    val parserSettings = parserSettingsOverride.getOrElse(ParserSettings.fromMaterializer(materializer)
    ...
  }
```

You could then add non-implicit but default `parserSettingsOverride` parameters to the actual implicits. WDYT?

**Comment by ktoso** [comment]
> UPDATE: non-implicit default parameters won't work of course. So, maybe just add non-implicit definitions that allow to specify ParserSettings explicitly which would allow people to define their own implicit Unmarshaller to use custom settings.

Right, and I'll document the need of doing so, should be good enough while keeping it clean.

**Comment by ktoso** [comment]
Thanks for chiming in, I'm giving it a shot now.
