### ISSUE TITLE
[akka-http] Complete async request with empty body and status 204

### ISSUE THREAD

**Issue by DanielaSfregola** [akka/akka#19510]
Hi all,
I am building a simple CRUD service using Akka-Http (you can see the code [here](https://github.com/DanielaSfregola/quiz-management-service/blob/master/tutorial-5/src/main/scala/com/danielasfregola/quiz/management/resources/QuestionResource.scala#L33)). 
When deleting a resource, I would like to actually delete the resource and once completed I'd like to return an empty response with status 204.

So far, only `complete(204, None)` seems to work. If I try to do things asynchronously or if my method returns `Unit`, i.e. I try to use any of the following:
- `complete(204, Future(None))`
- `complete(204, Unit)`
- `complete(204, Future(Unit))`

I get the following error:
```ERROR [ActorSystemImpl]: Error during processing of request HttpRequest(HttpMethod(DELETE),http://localhost:5000/questions/test,List(Host: localhost:5000, User-Agent: curl/7.43.0, Accept: */*),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
java.lang.IllegalArgumentException: requirement failed: Responses with this status code must have an empty entity```


Shouldn't be `HttpEntity.Strict(none/none,ByteString())` be recognised as an entity with empty body? 
Any suggestions/workaround on how to fix my issue is extremely appreciated.

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
Actually found a way of doing it:

```
onSuccess(Future(None)) {
  complete(204, _)
}
```

**Comment by jpdenford** [comment]
Stumbled across this issue looking for the same thing, here's another way to do this is
`complete(StatusCodes.NoContent, HttpEntity.Empty)`
