### ISSUE TITLE
Unpublish 2.4-SNAPSHOT from Sonatype — was: GetClusterShardingStats issues

### ISSUE THREAD

**Issue by jamesmulcahy** [akka/akka#19523]
ref: http://doc.akka.io/docs/akka/snapshot/scala/cluster-sharding.html

The documentation at the end of that page references a number of classes inside `ClusterSharding`, when checking the akka source, these classes actually exist inside the `ShardRegion` object.  I'm guessing the documentation is a little out of date?

Despite finding these referenced in the snapshot docs, and seeing them in the source, I'm unable to find them in the 2.4-SNAPSHOT jars.  Do the released jars lag the released documentation?

**Comment by jamesmulcahy** [comment]
For reference, I'm using the 2.4-SNAPSHOT that was released yesterday, 18th January.

**Comment by jamesmulcahy** [comment]
Apologies, the classes are in the Jar.  Our artifact proxy is caching an old version of the Jar.

The documentation issue (re: package/object naming) is still valid though, I believe.

**Comment by patriknw** [comment]
I suggest that you use the timestamped snapshots instead.

**Comment by jamesmulcahy** [comment]
Thanks for the suggestion, though it turns out that wouldn't have helped in this case.  Our proxy was mirroring from https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/akka/akka-cluster-sharding_2.11/2.4-SNAPSHOT/ which doesn't seem to have those anyway, and is in general, very out of date.

We've started mirroring the official akka repo directly now.

**Comment by patriknw** [comment]
Yeah, snapshots are published to http://repo.akka.io/snapshots/

**Comment by rkuhn** [comment]
Hmm, we should try to delete those snapshots—how did they get published in the first place?

**Comment by patriknw** [comment]
I have deleted the snapshots from sonatype!

**Comment by rkuhn** [comment]
Thanks Patrik!
