### ISSUE TITLE
Deprecate or remove the old `*Stage`'s

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19529]
Since we want `GraphStage` to be our low level API we should deprecate or remove the old stage APIs to make the user surface smaller (before removing experimental flag).

**Comment by drewhk** [comment]
This means doc examples need to be changed as well.

**Comment by ktoso** [comment]
An effort for removing StatefulStage is in progress here: https://github.com/akka/akka/issues/19361
So let's use this ticket for the other ones

**Comment by ktoso** [comment]
I'm doing it: https://github.com/akka/akka/pull/21919

**Comment by patriknw** [comment]
@ktoso Do you know the status here? How much is left?

**Comment by ktoso** [comment]
This is solved, missed to close the ticket it seems
