### ISSUE TITLE
Support proxy protocol

### ISSUE THREAD

**Issue by prettynatty** [akka/akka#19541]
Akka HTTP lacks proxy protocol support.
There already was a demand in spray/spray#846. It's impossible to implement anti-flood scenarios in case of plain tcp connections when there is no way to determine real client ip via HTTP headers passed from reverse proxy.

**Comment by jrudolph** [comment]
Here's a previous discussion on the mailing list: https://groups.google.com/d/msg/akka-user/TdrTq_3ebK8/31vj4MzPCAAJ

**Comment by sclasen** [comment]
:+1: please add.

**Comment by sclasen** [comment]
prior netty art  http://netty.io/4.1/api/io/netty/handler/codec/haproxy/HAProxyMessage.html

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
