### ISSUE TITLE
Add Akka Streams 1.0-2.x migration instructions about `transform` -> `via`

### ISSUE THREAD

**Issue by rcoh** [akka/akka#19545]
If you had an async stage in 1.0 and converted it to a GraphStage in 2.0, the following pattern will no longer work:
`xxxx.transform(() => myGraphStage)`

It should be replaced by:
`xxxx.via(myGraphStage)`

**Comment by drewhk** [comment]
Thanks, this slipped through, we will update the docs!

**Comment by rcoh** [comment]
While you're at it, in the section about `FlexiMerge` it would probably be helpful to mention the new mergeSorted builtin and give a use example (at least in my case, that was why I was using FlexiMerge in the first place).

**Comment by rcoh** [comment]
And I'm not positive that the MapAsyncOne example actually works. Comparing it to the MapAsync, I think that you need to pull at least once in onPull to create demand otherwise it just hangs.

**Comment by drewhk** [comment]
A `pull()` is indeed missing, a `preStart()` with a `pull()` is necessary.

**Comment by hepin1989** [comment]
yes,that is needed,when I implement my sink via GraphStage,I missed that at first too.

**Comment by rkuhn** [comment]
The world may have moved on: it seems this slipped through previously, but we (and hopefully everyone else) are concentrating on 2.4.x.
