### ISSUE TITLE
PersistentActor crashed when internalStash  throwing overflow exception 

### ISSUE THREAD

**Issue by MQ-EL** [akka/akka#19551]
Just need to drop incoming messages than crashed for persistent actor in some time. May be we can support this feature?

**Comment by MQ-EL** [comment]
When PA recoverying, the nr of bussiness domain msg received up to ```stash-capacity``` sometime , so crashed. then PA start recoverying again -> stash overyflow -> crashed ... I need do more work to prevent PA  restart repeatly in somewhere, just drop bussiness domain msgs in PA is more natual?

**Comment by MQ-EL** [comment]
```scala
  private def recovering(recoveryBehavior: Receive) = new State {
    ...
    override def stateReceive(receive: Receive, message: Any) = message match {
      case ... ⇒ ... 
      case other ⇒
        internalStash.stash()  // throw exception, cause recovery failure
    }
  }
```
Give a chance to catch this exception to ignore incomming bussiness domain message?

**Comment by patriknw** [comment]
Perhaps you can handle the exception in the parent (supervisor) actor? Perhaps use the `BackoffSupervisor`?

That said, I think you are right that we should improve the default behavior here.

**Comment by MQ-EL** [comment]
I used ```BackoffSupervisor``` to prevent some true exception, because it impacts performance to system(db or bussiness system used PA)  when PAs restart, especially when a large nr of PAs restart. However the worst is it will let some live PAs persist failure , which will make more restarted PAs.

 I mean we should avoid PA restart as mush as possible.

may be we can add  config ```ignore-stash-overflow``` in persistent config? and add ```def tryStash(): Boolean ``` in ```Stash``` trait to avoid try catch exception every time when stash full.

**Comment by patriknw** [comment]
yeah, but you should configure the `BackoffSupervisor` to stop the PA in case of such exceptions, it will then start it up again after backoff. That is new feature in 2.4.1.

**Comment by MQ-EL** [comment]
Drop business msgs directly will promote performce, becasue it avoid insignificance recovery time or cpu. 

IMO, it can be used with ```BackoffSupervisor``` together for better protect PAs

**Comment by patriknw** [comment]
I agree

**Comment by MQ-EL** [comment]
May i create a PR to add ```tryStash()``` method & ```ignore-stash-overflow``` config ? Or waiting a better solution?

**Comment by patriknw** [comment]
PR is very much welcome (that is often the quickest way to get things done ;-))
