### ISSUE TITLE
Google widget does not work on stream doc 2.0.2 page

### ISSUE THREAD

**Issue by agolubev** [akka/akka#19567]
- if open http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.2/scala.html
- type stream in google search widget
- it returns no results
<img width="935" alt="screenshot 2016-01-21 14 58 45" src="https://cloud.githubusercontent.com/assets/461456/12492696/7b97e038-c04f-11e5-9731-f96fe4b4a4b5.png">

**Comment by ktoso** [comment]
We're aware of it, duplicate of: https://github.com/akka/akka/issues/19059
I also am trying to get us a more cool search engine, will keep everyone updated.

**Comment by agolubev** [comment]
ok, thanks
