### ISSUE TITLE
Stream Validator

### ISSUE THREAD

**Issue by briantopping** [akka/akka#19571]
Potentially difficult idea here, but thought I would share it. #16830 and a conversation @rcoh started on Gitter about akka-cluster-sharding got me thinking about this. @ktoso was a part of this convo as well.

Since the lifecycle of the various subsystems in the stack need to be wired properly, it's pretty difficult to express all that in documentation and the actors involved are all messaging, what if there was some kind of tap (either stream or dispatcher based) that could feed well-known events into a rules engine like Drools so that bad protocol sequences could be flagged for user applications? Maybe a better example would be what Snort does in the intrusion detection space.

In the end, conversations like that would simply result in a rule being added to the debugging rule base and developers would run their stack with this rules engine watching for suboptimal states to pop up.

**Comment by rkuhn** [comment]
This goes into the same direction as formulating conversation structure using Session Types and deriving a state machine from that which can be used to validate runtime behavior. I should say that this is currently an active area of academic research.

**Comment by drewhk** [comment]
I don't think it is necessarily that complex, one can have simpler rules that work well in practice, session types or not. The larger issue here is that this needs a tap to relevant events, which is the realm of Typesafe Monitoring.

**Comment by patriknw** [comment]
it's an interesting idea, but I don't see that we can work on it any time soon. Community research is welcome. Closing for now.
