### ISSUE TITLE
No flushing in StreamConverters.fromOutputStream

### ISSUE THREAD

**Issue by ochrons** [akka/akka#19589]
When using `StreamConverters.fromOutputStream` to create a stream from an `OutputStream`, the implementation provides no way to flush after writes. This is a problem, for example, when writing to STDIN of a child process (at least on Windows), where flushing does not automatically take place.

A workaround is to wrap the `OutputStream` in a `PrintStream` using its `autoFlush` feature.
```scala
StreamConverters.fromOutputStream(() => new PrintStream(process.getOutputStream, true))
```

However it would be better if `StreamConverters.fromOutputStream` would provide this option directly.

**Comment by rkuhn** [comment]
Thanks for the pointer. Putting it on backlog because I cannot promise that we will get to it before 2.4.2, but if somebody were to submit a PR then that would be awesome.

**Comment by drewhk** [comment]
I don't think this needs to be backported, this is a new feature.

**Comment by ktoso** [comment]
It could be seen as consistency of writes feature, though it does not really guarantee anything anyway, and yeah "feature".

It has a workaround documented here so I'm ok with not backporting until someone really has a case where it's not possible to work around it
