### ISSUE TITLE
Potential race condition in FileSubscriber

### ISSUE THREAD

**Issue by ochrons** [akka/akka#19593]
When Akka Stream `FileSubscriber` completes with an error, the `Promise` is completed before closing the channel (and file). This will generate a race condition where a client wanting to delete the file upon the promise completion will fail (on some systems) because the file is still open.

Solution is to _always_ close the channel before completing the promise.

**Comment by hepin1989** [comment]
It's not implemented in GraphStage.

**Comment by drewhk** [comment]
Which version of streams is this? Is it true for 2.0.2?

**Comment by drewhk** [comment]
Ok, I see there is a PR, this answers my question :)
