### ISSUE TITLE
ShardRegion.GetClusterShardingStats stops returning valid data when a node is removed

### ISSUE THREAD

**Issue by jamesmulcahy** [akka/akka#19601]
I'm finding that the ClusterShardingStats returned by a ShardRegion.GetClusterShardingStats() message end up being empty after a node leaves (downed + removed from) the cluster.  Even if that node subsequently returns, the sharding stats never return.

I'm seeing this on the latest Akka 2.4-SNAPSHOT.  

Here's a walkthrough of the relevant log messages.  I'll put together an example which can reproduce this, too.

If I have a 3 node cluster, I see sharding active normally, and the returned stats reflect all three nodes.

e.g.

`[INFO] [01/24/2016 18:49:46.162] [ClusterSystem-akka.actor.default-dispatcher-21] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/singletonactor/singleton] Received stats: ClusterShardingStats(Map(akka://ClusterSystem -> ShardRegionStats(Map(63 -> 1)), akka.tcp://ClusterSystem@127.0.0.1:2552 -> ShardRegionStats(Map(86 -> 1)), akka.tcp://ClusterSystem@127.0.0.1:2553 -> ShardRegionStats(Map(96 -> 1))))
`

**Now if I killed the node listening on port 2553, I see the cluster down and remove the node.  After that, Sharding Stats fails to operate correctly.**

`[INFO] [01/24/2016 18:50:03.984] [ClusterSystem-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Leader is auto-downing unreachable node [akka.tcp://ClusterSystem@127.0.0.1:2553]
[INFO] [01/24/2016 18:50:03.985] [ClusterSystem-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Marking unreachable node [akka.tcp://ClusterSystem@127.0.0.1:2553] as [Down]
`
**Cluster removes unreachable now**
`[INFO] [01/24/2016 18:50:04.964] [ClusterSystem-akka.actor.default-dispatcher-29] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Leader is removing unreachable node [akka.tcp://ClusterSystem@127.0.0.1:2553]
`
**One ShardCoordinator removes the node @ 2553**
`[INFO] [01/24/2016 18:50:04.967] [ClusterSystem-akka.actor.default-dispatcher-29] [akka.tcp://ClusterSystem@127.0.0.1:2551/system/sharding/AuthorListingCoordinator] Member removed [akka.tcp://ClusterSystem@127.0.0.1:2553]
[INFO] [01/24/2016 18:50:04.967] [ClusterSystem-akka.actor.default-dispatcher-34] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/singletonactor] Member removed [akka.tcp://ClusterSystem@127.0.0.1:2553]
`
**Another ShardCoordinator removes the node @ 2553**

`
[INFO] [01/24/2016 18:50:04.967] [ClusterSystem-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSystem@127.0.0.1:2551/system/sharding/PostCoordinator] Member removed [akka.tcp://ClusterSystem@127.0.0.1:2553]
`

**But now, when I see my singleton initiate the request for stats, I notice the request being sent to node 2553.  This seems odd, given it was removed.  The relevant log messages follow:**

**My log entry regarding the request for stats being initiated**
`
[INFO] [01/24/2016 18:50:06.152] [ClusterSystem-akka.actor.default-dispatcher-21] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/singletonactor/singleton] About to request stats
`

**Akka log message re: sending of a message to a gated node; the node @ 2553 which we removed.**

`[WARN] [01/24/2016 18:50:06.158] [ClusterSystem-akka.remote.default-remote-dispatcher-28] [akka.tcp://ClusterSystem@127.0.0.1:2551/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FClusterSystem%40127.0.0.1%3A2553-3] Association with remote system [akka.tcp://ClusterSystem@127.0.0.1:2553] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://ClusterSystem@127.0.0.1:2553]] Caused by: [Connection refused: /127.0.0.1:2553]
`

**Then I get back an empty ClusterShardingStats() response, with no data.**

`[INFO] [01/24/2016 18:50:06.172] [ClusterSystem-akka.actor.default-dispatcher-18] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/singletonactor/singleton] Received stats: ClusterShardingStats(Map())
`

From this point on, I never get any valid data back from ClusterShardingStats -- even if I re-add the node at port 2553, I always get back an empty stats object.

**Comment by jamesmulcahy** [comment]
I've pushed my example, which is based on the akka cluster sharding activator template, to my github profile here: https://github.com/jamesmulcahy/activator-akka-cluster-sharding-scala/commit/599daeace62cda8d0a5d105e66d3fa0ab813b682

**Comment by jamesmulcahy** [comment]
I've root caused this, and have a one line fix. Will push shortly

**Comment by rkuhn** [comment]
Thanks!
