### ISSUE TITLE
How does restarting cluster actor (Actor added to cluster using DistPubSUbMediator) effect the cluster ?

### ISSUE THREAD

**Issue by letitcrash** [akka/akka#19600]
What state does the cluster node get into when the cluster actor (actor added to cluster using DistPubSUbmediator) is restarted ? Does it even effect the cluster state by any chance ??

**Comment by letitcrash** [comment]
Does the restart cause heartbeat to fail and eventually cause failure detection to kick in and mark the node as unreachable etc.. ?? Currently we are using 2.3.10 and we are facing clustering issues where a cluster actor restart is causing nodes going out of cluster and never rejoining and eventually cluster is marking them as down.

**Comment by johanandren** [comment]
Hi @letitcrash, please do not use our issue system for asking questions, instead use the gitter channel or the mailing list. Thanks, closing as it does not really belong here, if it turns out to be a bug or something concrete to improve, please open a new ticket!
