### ISSUE TITLE
ensure that HttpResponse entities are consumed or cancelled

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19602]
HTTP responses may often come from resources that need to be cleaned up, and in order to determine the HTTP response status code the resources will usually have been allocated already before the entity is materialized. This means that we must ensure that entities do not get dropped to the floor when the HTTP client closes the connection.

A solution sketch:

  * we wrap Sources passing towards the network through akka.http.impl.engine.server.HttpServerBluePrint.ControllerStage such that we can track their materialization
  * when the ControllerStage sees downstream termination it will try to cancel all previously wrapped Sources, failing silently for those that have already been materialized—this is sufficient because after materialization the TCP connection’s cancellation signal will propagate upstream to close the resource

/cc @jroper

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
