### ISSUE TITLE
akka-http occasionally throws akka.stream.scaladsl.One2OneBidiFlow$OutputTruncationException$: null when using https  

### ISSUE THREAD

**Issue by FrankvanMeeuwen** [akka/akka#19617]
We have build a client using akka-http which sends a single request to a rest api on demand. This is working fine when using http with the cachedHostConnectionPool. However when using https, with the cachedHostConnectionPoolTls, occasionally we receive the `akka.stream.scaladsl.One2OneBidiFlow$OutputTruncationException$: null` exception. I found that preceding the error, the server initiates to close the connection by sending a [FIN,ACK]. (It does not send a close_notify first, which is not according to the specifications but seems to be used by more servers.) 

When turning on debug logging i can see that javax.net.sll throws an exception when the closeInbound() is called, which might be related to the problem. 

```
plugin-framework-akka.actor.default-dispatcher-248, called closeInbound()
plugin-framework-akka.actor.default-dispatcher-248, fatal error: 80: Inbound closed before receiving peer's close_notify: possible truncation attack?
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
%% Invalidated: [Session-3, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256]
plugin-framework-akka.actor.default-dispatcher-248, SEND TLSv1.2 ALERT: fatal, description = internal_error
```

The problem is that quite some request fail with this `akka.stream.scaladsl.One2OneBidiFlow$OutputTruncationException$: null exception`, as if they still use the connection which the server wants to close. With wireshark i could see that no request are even send to the server when this exception occurs. 

As a workaround, i found out that, because the server closes connections after 5 seconds of inactivity, if i use the configuration setting: {akka.http.idle-timeout = 4 seconds} the problem disappears.

**Comment by rkuhn** [comment]
Thanks for raising this; it looks a bit fishy that the servers don’t close the connection properly, but I’ll let @sirthias and @jrudolph chime in on what the policy should be in this case.

**Comment by ktoso** [comment]
Related to the sovled https://github.com/akka/akka/issues/19777 ?

**Comment by FrankvanMeeuwen** [comment]
It indeed seems to be related as it also has to do with the server closing the connection. Unfortunately it is hard for me to reproduce locally, but I will try if the latest akka version fixes this for the client.

**Comment by eswenson1** [comment]
I'm running into this issue, too, on akka-2.4.8.

**Comment by FrankvanMeeuwen** [comment]
Recently the customer where the error showed up, tested again with akka 2.4.8 using https and the cachedHostConnectionPoolTls. Now the following errors show up in the logfile:

`ERROR akka.actor.RepointableActorRef - Error in stage [One2OneBidi]: Inner stream finished before inputs completed. Outputs might have been truncated.`

So we switched back to not using the connectionPool, by opening a connection for each request, and the error did not show up anymore.

**Comment by FrankvanMeeuwen** [comment]
I managed to reproduce a similar scenario when connecting to another https server, which seems to have the same behaviour. It closes the connection after 5 seconds of inactivity, and probably also does not send an close_notify first. (Did not verify this)
To trigger the error, set the interval of the tickSource higher than 5 seconds.
This is with the latest akka 2.4.8 release.

```
import akka.actor.{ActorSystem, Cancellable}
import akka.event.Logging
import akka.http.scaladsl.Http
import akka.http.scaladsl.Http.HostConnectionPool
import akka.http.scaladsl.client.RequestBuilding._
import akka.http.scaladsl.model.{HttpRequest, HttpResponse}
import akka.http.scaladsl.unmarshalling.Unmarshal
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Flow, Source}

import scala.concurrent.Future
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

object OutputTruncationHttps extends App {
  implicit val system = ActorSystem()
  implicit val mat = ActorMaterializer()
  implicit val executionContext = system.dispatcher
  val log = Logging(system, this.getClass)

  val connectionPool = Http().cachedHostConnectionPoolHttps[Int]("www.openssl.org", 443)

  Source.tick(0.seconds, 7.seconds, Unit)
    .scan(0)((prev, _) => prev + 1)
    .map(attempt => Get("/") -> attempt)
    .via(connectionPool)
    .mapAsync(1) {
      case (Success(r), attempt) =>
        Unmarshal(r.entity).to[String].map(_ => s"Succesfully unmarshalled" -> attempt)
      case (Failure(e), attempt) =>
        Future.successful(s"No response obtained for request $attempt. ${e.getMessage}" -> attempt)
    }
    .runForeach {
      case (msg, attempt) => log.info("Materialized #{}:{}",attempt, msg)
    }
}
```

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
