### ISSUE TITLE
AbstractBoundedNodeQueue also suffers from nepotism

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#19614]
The `AbstractBoundedNodeQueue` was added in Akka 2.4 and suffers from the same issues as `AbstractNodeQueue` described here #19216

Reported by @MQ-EL in #17547

**Comment by drewhk** [comment]
does this need a backport?

**Comment by patriknw** [comment]
no, the bounded version doesn't exist in 2.3, that's why it was missed in the original fix

**Comment by drewhk** [comment]
ok, thanks.
