### ISSUE TITLE
`Access-Control-Allow-Methods` and `Access-Control-Allow-Headers` should be ResponseHeader

### ISSUE THREAD

**Issue by notxcain** [akka/akka#19628]
The same goes for `Access-Control-Allow-Origin`
As for now they extend `RequestHeader`
This bug was introduced in https://github.com/akka/akka/commit/7eed4a34a50ad0094d70ef9d9b79ed3d0d3c06fc

**Comment by notxcain** [comment]
@johanandren  Can I send a PR for this?

**Comment by johanandren** [comment]
That would be great!

**Comment by notxcain** [comment]
Will do then :+1:
