### ISSUE TITLE
ClusterShardingStats node names vary in unpredictable ways

### ISSUE THREAD

**Issue by jamesmulcahy** [akka/akka#19622]
Lets say I have three nodes, A, B and C.  If I start A, then have B and C join, I get ClusterShardingStats responses which represent three regions:

akka://ClusterName  (A)
akka.tcp://ClusterName@127.0.0.1:2552 (B)
akka.tcp://ClusterName@127.0.0.1:2553 (C)

But now if I fail A, then restart it, the responses end up looking like

akka.tcp://ClusterName@127.0.0.1:2551 (A)
akka.tcp://ClusterName@127.0.0.1:2552 (B)
akka.tcp://ClusterName@127.0.0.1:2553 (C)

It looks to me like the implementation is going to some effort to do the re-write in the original case, but that doesn't persist for all future cases (perhaps when the co-ordinator is on a separate node to the one that is initiating the GetClusterShardingStats) request.

So my questions are:  Is this intentional, and if not, is there anything tricky about making this "predictable" - i.e. always use the fully specified name (as per the post-failover) requests.

As it stands, it makes consuming this data a bit of a pain.

**Comment by johanandren** [comment]
Sounds like a bug to me, the code clearly tries to use the self-address but there must be something wrong with that logic.

**Comment by johanandren** [comment]
Any chance you could try to solve and provide a pull request for this? We are currently very busy with streams and http for 2.4.2 so I can't foresee we have time to fix it until a later Akka version if not.

**Comment by patriknw** [comment]
I agree that it sounds better to fill in the full address. Here is how to do that:
```
def fillLocal(address: Address): Address = {
    // local address might be used if grabbed from actorRef.path.address
    if (address.hasLocalScope && address.system == selfAddress.system) selfAddress
    else address
  }
```

**Comment by jamesmulcahy** [comment]
I was just about to push something myself, but you beat me to it :) Thanks @talp-traiana !
