### ISSUE TITLE
Spurious warning when accepting a WebSocket request

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19639]
See https://groups.google.com/d/topic/akka-user/i9fe0-K-onM/discussion

```
WARN  akka.actor.ActorSystemImpl - HTTP header 'UpgradeToWebSocketResponseHeader: ' is not allowed in responses
```

Probably introduced in 7eed4a34a50ad0094d70ef9d9b79ed3d0d3c06fc

/cc @sirthias

**Comment by ktoso** [comment]
Thanks, good catch.

**Comment by johanandren** [comment]
This sample I did for another ticked related to WebSockets consistently repeats the error on every WebSocket connection: https://gist.github.com/johanandren/964672acc37b84caca40

**Comment by rkuhn** [comment]
@2m or does this need a backport?

**Comment by 2m** [comment]
Nope. 7eed4a3 is not in `streams-http-2.0` branch.
