### ISSUE TITLE
FileIO.toFile does not create file if does not exists

### ISSUE THREAD

**Issue by prettynatty** [akka/akka#19635]
in Akka 2.4.2-RC1

**Comment by ktoso** [comment]
More details in :point_up: [January 28, 2016 6:45 PM](https://gitter.im/akka/dev?at=56a9e31d8fbaf4220af9ce6e)

> the file sink/source needs a serious rehoul since we're in JDK8 now, it must expose https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardOpenOption.html in the API, such that semantics about CREATE/CREATE_NEW etc can be expressed cc @prettynatty @johanandren The problem just mentioned is a problem indeed and should be fixed along with changing the API to take those, and then do "the right thing" ™

**Comment by ktoso** [comment]
This would be very nice to do before 2.4.2 IMHO, not super terrible if we do afterwards... can be added as new methods I guess.

**Comment by prettynatty** [comment]
test case: https://github.com/akka/akka/pull/19636

**Comment by viktorklang** [comment]
A workaround is to create the file in mapMaterializedValue?

**Comment by rkuhn** [comment]
We do not need to expose the flags, but we must create the file—it would be rather strange API otherwise.

**Comment by viktorklang** [comment]
@rkuhn agreed.

**Comment by ktoso** [comment]
Creating the file – yes, of course.
Exposing the flags – I'd really prefer that insted of what we currently have (a boolean to append or not, which feels like a hack, since there is a well typed Option to represent this) => IMHO exposing the options should be done as well, together with removing the `append: Boolean` in favour of those options.

**Comment by drewhk** [comment]
I agee with @ktoso, there is a well-typed alternative that is also properly documented, so let's use it instead of inventing our types/parameters and semantics.

**Comment by drewhk** [comment]
This adds a new feature (passed in flags, which happen to be also > Java 7 only) so no backport here
