### ISSUE TITLE
FAILED: BackoffSupervisorSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#19645]
```
[info] - must support custom supervision strategy *** FAILED *** (3 seconds, 220 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.pattern.BackoffSupervisor$CurrentChild
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:408)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:735)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1$1.apply$mcV$sp(BackoffSupervisorSpec.scala:85)
```

(Jan 29, 2016 3:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3007/consoleFull
(Jan 28, 2016 7:18:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/246/consoleFull

**Comment by 2m** [comment]
This is after a fix attempt: https://github.com/akka/akka/pull/19579

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3016/consoleFull

**Comment by drewhk** [comment]
Hm, trying this again.

**Comment by drewhk** [comment]
Well, strictly speaking one of the issues *were* fixed, this failure is a second kind (the previous ticket mixed the two).

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3449/consoleFull

**Comment by drewhk** [comment]
This is totally weird, it looks like the "supervisor" actor somehow does not get the GetCurrentChild message, which is weird since it got it not much before for another send. I.e. the GetCurrentChild is lost somehow and hence no reply comes. Now I need to figure out how this can happen, but so far this is rather hairy.

**Comment by drewhk** [comment]
Argh, was looking at the wrong actor.
