### ISSUE TITLE
Confusing behavior of Uri when using default protocol port

### ISSUE THREAD

**Issue by notxcain** [akka/akka#19650]
```
scala> Uri("example.com").withPort(80).authority.port
res1: Int = 80
scala> Uri("http://example.com").withPort(80).authority.port
res2: Int = 0
scala> Uri("http://example.com").withPort(9000).authority.port
res3: Int = 9000
```
It feels like a bug that `res2 = 0`.

**Comment by ktoso** [comment]
Thanks for reporting! Seems a bit off indeed. The special handling of 80 could be done latter in the pipeline I think (http requests to 80 must not include the port, which is why the special handling of 80 comes from)

**Comment by notxcain** [comment]
@ktoso maybe it worth making `Uri#effectiveUri` public. I faced this bug/feature when was trying to proxy request using `cachedHostConnectionPool(uri.authority.host.address, uri.authotity.port)`. Oh maybe you would suggest a workaround?

**Comment by ktoso** [comment]
Making effective port public is something I have considered but not done
recently. I think it makes sense but will revisit that next week :) thanks
form your patience!

**Comment by jrudolph** [comment]
I agree. That the port can be `0` is an implementation artifact and shouldn't show up in the public API.

**Comment by notxcain** [comment]
As far as I understand. It is used to generate proper `Host` header. So maybe it should move there.

**Comment by jrudolph** [comment]
I think we still need it there to be able to distinguish between http://host:80/ (with an explicit port given) and http://host/. But it should have a proper API. Right now it's just an undocumented field with an explained magic default value.

**Comment by notxcain** [comment]
Of course. I was talking about mapping of protocol to default port.

**Comment by Steiny69** [comment]
I hit this same problem and was quite confused for a while. There seem to be two compounding problems here.

1. Providing an explicit port will be set to 0 when it matches the default for the scheme.
2. The connection pool functions do not use the default when given a port of 0.

I would expect the following examples to connect to port 443:

    val explicitPortAuthority = Uri("https://example.com:443").authority
    Http().cachedHostConnectionPoolHttps(explicitPortAuthority.host.address(), port = explicitPortAuthority.port)

    val implicitPortAuthority = Uri("https://example.com").authority
    Http().cachedHostConnectionPoolHttps(implicitPortAuthority.host.address(), port = implicitPortAuthority.port)

The best solution I have so far is a little ugly and I have to remember to use it whenever creating a new pool:

    val port = authority.port
    val pool = if (port == 0)
      Http().cachedHostConnectionPoolHttps(authority.host.address())
    else
      Http().cachedHostConnectionPoolHttps(authority.host.address(), port = port)

Ideally I don't want to ever have to manually handle the defaults myself. `Authority.port` really ought to be an `Option[Int]` or even `Option[Port]` where `Port` is a new type that ensure valid port numbers. I understand this may be a bigger ask since this changes the API.

A compromise could be to change `cachedHostConnectionPoolHttps` (and the others) to have a default port of 0 and then in the body of the function replace 0 with the default.

**Comment by ktoso** [comment]
I was pretty sure all APIs handle `0`, but if it's as you say @Steiny69 then we have a bug here - thanks for reporting, will have a look at it sooner then.

**Comment by johanandren** [comment]
I agree that the best™ solution would be to `Option[Int]` port on authority, but as far as I see binary compatibility stops us from changing that, so there is no way to hide the `0`-means-not-provided from the API by now. We can only document it.

The only idea I come up with is to _not_ normalize the port upon creation of `Uri`, to keep the original value intact and make sure all places that use `authority.port` use `effectiveUri` instead (the mentioned connection pools for example)

Any opinions about this?

**Comment by patriknw** [comment]
would it help to add `apply` overload with `Option[Int]`? (it has default param values so that might also not be easy)

adding `isPortDefined: Boolean` might also mitigate the problem somewhat

**Comment by ktoso** [comment]
Isn't a simple solution simply to expose `effectivePort`? I've seen the need to use it quite a few times personally, so I think it makes sense to expose, esp. given the special `0` semantics...

- We expose `effectivePort`, which addresses the issue somewhat – and is binary compatible.
- Then document the special 0 value on `authority.port` and explain that one should use `effectivePort` instead in most cases.

An alternative solution is to not "normalise" as you mention it @johanandren, however then special handling of http:// without port will end up be sprinkled around in many places, so I'm not sure we want that.

**Comment by johanandren** [comment]
I'll go with @ktoso s advice
