### ISSUE TITLE
make use of ControlAwareMailbox and mark the control message with  ControlMessage

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19651]
As we have some control message about the remoting is control message which crossed the wire and is writed in protobuf format,I think we could mark the generated message with `ControlMessage` and make use of the `ControlAwareMailbox` for the `EndpointActor` to optimise the control message passing under high load.

A hint is at `http://trueaccord.github.io/ScalaPB/customizations.html` which has a section of how to mark the generated messages with multiple `Custom base traits`.

Another random idea is that we may reimplement the remoting transport on top of HTTP/2,which have multiple streams and priorities.

**Comment by rkuhn** [comment]
There are many thing we could consider, especially when thinking about a completely new foundation for remoting—for example based on Akka Streams in order to ease the formulation of such concerns as back-pressuring one kind of traffic while expediting another.
