### ISSUE TITLE
bind-timeout docs say it supports inifite duration but is parsed with FiniteDuration

### ISSUE THREAD

**Issue by matthughes** [akka/akka#19663]
Docs say this about bind-timeout: http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.3/scala/http/configuration.html

```
    # The time period within which the TCP binding process must be completed.
    # Set to `infinite` to disable.
    bind-timeout = 1s
```

However, the code parses this setting with getFinite: https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala#L68

**Comment by drewhk** [comment]
Thanks for reporting. I think this should simply not take an infinite value so the fix is to change the documentation.
