### ISSUE TITLE
Framing.delimiter does not include delimiter

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19664]
In the docs it says:

> The decoded frames will include the separator sequence. If this is not desired, this Flow can be  augmented with a simple ''map'' operation that removes this separator.

But with this test case you can see that it actually strips out the delimiter:

```Scala
val f = Source(List(ByteString("a\n")))
  .via(Framing.delimiter(ByteString("\n"), 256))
  .runFold(ByteString())(_ ++ _)

Await.result(f, 3.seconds) should be(ByteString("a\n"))
```

**Comment by drewhk** [comment]
Yes, it does. The docs needs to be fixed.

**Comment by alexeysirenko** [comment]
Is there a way to include a delimiter?

**Comment by johanandren** [comment]
Not with the operator itself, you'd have to reintroduce the delimiter with `.map` for example. If you think that is too much overhead please open up a separate issue for adding such functionality to the framing operator.
