### ISSUE TITLE
Http.singleRequest creates a new pool each time if no settings are specified.

### ISSUE THREAD

**Issue by Joe-Edwards** [akka/akka#19662]
When you don't specify the `ConnectionPoolSettings`, `Http.singleRequest` will create a new instance of them (using the actor system config). These _are not equal_, so will get their own entries in the hostPoolCache - i.e. the pools aren't reused.

The problem seems to be in `ParserSettings` - it has 2 function parameters (`customMethods` & `customParameters`) which will compare differently for different instances, even if they use the default `_ => None` function. Perhaps they should be maps instead?

As an workaround you can store the default settings yourself, e.g.
```
val first = http.singleRequest(req)
val second = http.singleRequest(req) // Uses a different pool

val settings = ConnectionPoolSettings.default
val third = http.singleRequest(req, settings = settings)
val fourth = http.singleRequest(req, settings = settings) // Uses the connection pool from the third
```
The description of the method simply says
>Fires a single HttpRequest across the (cached) host connection pool for the request's effective URI

so I don't think this is expected.

**Comment by drewhk** [comment]
This seems to be not easily backportable anymore. Skipping.
