### ISSUE TITLE
Variadic route concatenation function

### ISSUE THREAD

**Issue by acjay** [akka/akka#19678]
As [noted in the docs](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.1/scala/http/routing-dsl/directives/index.html#Composing_Directives), using the `~` combinator for route concatenation is error prone. Any time someone uses curly braces to group routes in the inner route part of a directive, it's a very easy mistake to make to omit the `~`. Less importantly, most formatters attempt to indent all but the first directive, which in most cases would be the desired formatting, but feels weird for routes. This makes me suspect that an infix operator for route concatenation may not be the most natural thing, and perhaps not the ideal thing to recommend in the docs.

Would the project be amenable to a PR that adds a variadic route concatenation function to the [RouteConcatenation](https://github.com/akka/akka/blob/f008a932c381013f6060ee00a731862bafed2be7/akka-http/src/main/scala/akka/http/scaladsl/server/RouteConcatenation.scala#L10) trait? I'm not an expert on whether there's any downside to this, but in my project, I'm using the following:

```
def all(routes: Route*): Route = routes.foldLeft[Route](reject())(_ ~ _)
```

(I think that empty `reject()` is the correct semantics?) I'm open to suggestions on any improvements and the name.

**Comment by johanandren** [comment]
I'm not sure I'm convinced it is big enough a problem that we should provide an additional way to do the same, especially given that it is so easy to introduce your own "fix" for it in a project.

Note on your solution, as the `all` directive does not really make sense for less than two routes I'd make the signature `def all(route1: Route, route2: Route, rest: Route*)` instead. With your example `all()` and `all(route)` are valid calls which might not really make sense.

Let's wait for @ktoso to come back from vacation and see what he thinks about this.

**Comment by acjay** [comment]
To me, the big advantage to adding this to the library is getting to remove that big warning bubble in the docs. And when I was in the early stages of my project, I definitely fell victim to the forgotten `~`, so I can say first hand that it happens.

I think leaving it fully variadic is probably best, even though it adds no direct utility in those cases. Suppose you applied it to a collection of `Route` instances defined elsewhere, or composed it with other logic  in some other way. It seems like make in 2+ arity would just make it more difficult to deal with.

**Comment by ktoso** [comment]
Hi there,
It's an interesting idea I guess. The worrying aspect is that I don't think we'd recommend that one by default and we'd end up with 2 styles to do the same thing hm...

WDYT @rkuhn @sirthias @jrudolph ?

**Comment by acjay** [comment]
Other than the obvious fact that it would be a change, and changes require nontrivial amounts of energy, why not recommend a non-infix concatenator as the default?

**Comment by acjay** [comment]
(Reopening for consideration, per [Gitter chat](https://gitter.im/akka/akka?at=56fea724d9b73e635f6861fe))

**Comment by ktoso** [comment]
Yeah let's think about it since we have such operator now in JavaDSL (new API)

**Comment by dhoepelman** [comment]
Seems like good utility, might not be applicable in every use-case but can definitely solve problems when specifying a large "list" of routes.

I would name it `concatenate` or `sequence` instead of `all`.
`all` is less clear to me, as a beginner I would expect all routes to be executed (this doesn't make sense, I'm just indicating potential confusion).
`concatenate` makes is clearer that the infix concatenate operator semantics still apply.

Simply mentioning it in the docs as an alternative would seem more prudent to me than making it the default.

**Comment by acjay** [comment]
Not at all attached to `all`.

With `concat` especially, and perhaps `seq`, my only concern is whether this is putting the operational detail above the semantics? The strength of the DSL is that it reads like a description of the routing process, from the perspective of a request flowing through. After all, `parameters` isn't `deconstructQueryString`. In that sense, I wonder if `tryEach` makes more sense?

Or if you think of it less sequentially, `routes` or `routeGroup`, perhaps?

**Comment by ktoso** [comment]
The most scala idiomatic name that comes to mind here is `sequence` - as it's similar to Future.sequence in a way. Most definitely not `seq` as that implies `Seq` whereas we want to imply "apply routes in sequence" (which is pretty much what is happening internally)

**Comment by acjay** [comment]
The only thing I'd say there is that `Future.sequence` is so named because it's exchanges the order of a two type higher-kinded types. I can't remember the rules for each. See [this page](http://typelevel.org/cats/tut/traverse.html) in the Cats docs. I'm not an expert in the category theoretical stuff, but just want to make sure using `sequence` wouldn't be appropriating term with a specific meaning. Maybe not, if you squint at it!

**Comment by ktoso** [comment]
Let the bike-shedding begin...! :wink: Anyone else have opinions here?

// cc @patriknw @viktorklang @johanandren

**Comment by acjay** [comment]
Haha. I'll work with `sequence` for now, and if a new consensus emerges, it's an easy change.

**Comment by viktorklang** [comment]
What about `routes`?

**Comment by ktoso** [comment]
`Route.routes` you mean?

**Comment by viktorklang** [comment]
Or continuing the Metallica-theme: Route.emAll(routes: Route*): Route /cc @rkuhn

**Comment by ktoso** [comment]
```
Route._66()
```

I still like sequence ;)

**Comment by acjay** [comment]
In the branch I'm implementing this on, I dropped it into `trait RouteConcatenation`, no there'd be no need to prefix.

**Comment by viktorklang** [comment]
perhaps `group` or `conjoin` or `concatAll` ?

**Comment by ktoso** [comment]
Good point actually... if without prefix then I'm ok with `routes` :+1: 
Would you submit a PR with this?

**Comment by ktoso** [comment]
Oh wait... that could be a bit confusing since many people currently like to do: `val routes = a ~ b ~ c`

**Comment by acjay** [comment]
It occurred to me as I'm reusing the tests from `~`, the semantics of this are really, "try each of the following routes in order, and take the first successful one". In that sense, this is really more like `Future.firstCompletedOf` than it is `Future.sequence`.

**Comment by acjay** [comment]
`val routes = firstMatchOf(a, b, c)` or `val routes = tryEach(a, b, c)`?

**Comment by ktoso** [comment]
`Route.sequence` – it's not quite it, I do like it somehow
`routes` – in danger of conflicting with existing code causing confusion
`firstMatchOf`, `tryEach` – sound like we're actually running the thing here, while we just concac them

going back full circle, as @viktorklang suggested and is in the trait name `RouteConcatenation ` – let's go with `concat`, WDYT?

**Comment by acjay** [comment]
`concat` it is. I still think that's looking at it from the wrong side, operationally instead of semantically...but you're right that it is consistent with existing usage.

**Comment by ktoso** [comment]
And it's in! Thanks for the contrib and discussion @acjay!
