### ISSUE TITLE
Impossible to parse cyrillic Uri

### ISSUE THREAD

**Issue by RomanIakovlev** [akka/akka#19677]
Consider this:

```"com.typesafe.akka" %% "akka-http-experimental" % "2.4.2-RC1"```

```
import akka.http.scaladsl.model.Uri

scala> Uri("http://президент.рф/", Uri.ParsingMode.Relaxed)
akka.http.scaladsl.model.IllegalUriException: Illegal URI reference: Invalid input 'п', expected 'EOI', '#', '?', path-abempty or authority (line 1, column 8): http://президент.рф/
       ^
  at akka.http.scaladsl.model.IllegalUriException$.apply(ErrorInfo.scala:40)
  at akka.http.scaladsl.model.Uri$.fail(Uri.scala:741)
  at akka.http.impl.model.parser.UriParser.fail(UriParser.scala:62)
  at akka.http.impl.model.parser.UriParser.parseUriReference(UriParser.scala:33)
  at akka.http.scaladsl.model.Uri$.apply(Uri.scala:209)
  at akka.http.scaladsl.model.Uri$.apply(Uri.scala:199)
  ... 43 elided

```

Any insights on how to tackle this?

**Comment by johanandren** [comment]
If you read the docs of `Uri.apply` they say 

>"Parses a valid URI string into a normalized URI reference as defined by http://tools.ietf.org/html/rfc3986#section-4.1. Percent-encoded octets are decoded using the given charset (where specified by the RFC). If strict is false, accepts unencoded visible 7-bit ASCII characters in addition to the RFC"

So this means you will need to transform the unicode hostname into ascii before passing it to apply or construct your `Uri` instance manually instead of parsing it, like this: `Uri(scheme = "http", authority = Uri.Authority(Uri.NamedHost("президент.рф")))`. `NamedHost` will perform the required "punicode" encoding of the IDN (https://en.wikipedia.org/wiki/Internationalized_domain_name).

**Comment by johanandren** [comment]
We should discuss if we can improve this when @ktoso is back.

**Comment by RomanIakovlev** [comment]
Thanks, understood. While it works, it is a workaround of sorts, because if I use the `akka.http.scaladsl.model.Uri#apply(input: ParserInput): Uri`, it would automatically distinguish between absolute and relative URIs, a functionality on which I rely. I'm writing a web crawler, and it's nice to just throw `org.jsoup.nodes.Element#select("a[href^=\"/\"]")` to the aforementioned `Uri#apply` method and allow it figure out if it's absolute or relative one.

**Comment by rkuhn** [comment]
RFC 3986 is very strict on what is allowed within a URI, so I would conclude that the attribute values extracted by JSoup need to be sanitized before they can be used in this context. Adding that code to `Uri.apply()` does not seem right to me.

**Comment by johanandren** [comment]
I agree, my thoughts was that there will be people who will want to parse URI:s that contain IDN host parts, and maybe we should/could provide a _separate_ way to do that easily.

**Comment by RomanIakovlev** [comment]
@johanandren my thoughts exactly. And it's not only about the hosts, there are non-ASCII characters in other URI components, like paths, in the wild.

**Comment by rkuhn** [comment]
Yes, true. What makes me wonder (in general) is why this punycode thing was even invented, given percent encoding.

**Comment by drewhk** [comment]
Because it is for DNS, and % was a no-go for backwards compatibility (if I
understand correctly).

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
