### ISSUE TITLE
UnboundedControlAwareMessageQueueSemantics not working

### ISSUE THREAD

**Issue by iouwon** [akka/akka#19704]
```Scala
object UnboundedControlAwareMailbox {
  class MessageQueue extends ControlAwareMessageQueueSemantics with UnboundedMessageQueueSemantics {
    val controlQueue: Queue[Envelope] = new ConcurrentLinkedQueue[Envelope]()
    val queue: Queue[Envelope] = new ConcurrentLinkedQueue[Envelope]()
  }
}
```
probably should be

```Scala
object UnboundedControlAwareMailbox {
  class MessageQueue extends UnboundedControlAwareMessageQueueSemantics with UnboundedMessageQueueSemantics {
    val controlQueue: Queue[Envelope] = new ConcurrentLinkedQueue[Envelope]()
    val queue: Queue[Envelope] = new ConcurrentLinkedQueue[Envelope]()
  }
}
```
without it trying to do:
```Scala
extends RequiresMessageQueue[UnboundedControlAwareMessageQueueSemantics]
```
fails with:

>Caused by: java.lang.IllegalArgumentException: produced message queue type [class akka.dispatch.UnboundedControlAwareMailbox$MessageQueue] does not fulfill requirement for actor class [class sap.out.order.SapOrderEndpointConsumer]. Must be a subclass of [interface akka.dispatch.UnboundedControlAwareMessageQueueSemantics].

However, doing extends `RequiresMessageQueue[ControlAwareMessageQueueSemantics]` does work but is not quite right I feel

**Comment by virsox** [comment]
Opened a Pull Request for this issue https://github.com/akka/akka/pull/19705
