### ISSUE TITLE
Timeout.zero is treated as a negative timeout

### ISSUE THREAD

**Issue by stepbeek** [akka/akka#19709]
When using askable actors, asking an actor with a timeout of zero results in a failed future wrapping an IllegalArgumentException with message "Timeout length must not be negative...".

I'm a bit wary of relying on this being how Timeout.zero is handled, since it seems to be a slightly different case. Zero timeout seems more akin to asking for a task without a suitably long timeout (guaranteed to fail, but still valid), rather than a negative timeout (an invalid argument entirely).

Could you confirm whether this is by design, or should zero be handled as a special case?

(This behaviour is defined [here](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/pattern/AskSupport.scala#L411))

Thanks,
Stephen

**Comment by ktoso** [comment]
I don't think allowing a zero timeout is helpful for `ask` - if you want to test "thing did not make it in time" it's also doable with `1.nanos` - very sure you won't get a reply in time with such timeout as well.

I suppose we should fix the exception message though, to match reality – it should be *positive*.

**Comment by patriknw** [comment]
fix exception message

**Comment by Chuwiey** [comment]
please close according to #20321

**Comment by ktoso** [comment]
Thanks!
