### ISSUE TITLE
Avoid allocations in Java unfoldAsync

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19707]
Currently there is three transformations taking place in each unfold invocation: `Future` => `CompletionStage`, `Option` => `Optional` and `Tuple2` => `Pair`. We should be able to avoid this somehow.

**Comment by rkuhn** [comment]
This might well be implemented by creating a specialized implementation—most other cases are pretty trivially adapted but this one is really costly.

**Comment by hepin1989** [comment]
I will try to take this.

**Comment by hepin1989** [comment]
@johanandren I think this can be closed now.

**Comment by johanandren** [comment]
Yes, thanks for the ping
