### ISSUE TITLE
Should streaming IO reword the "once we can use Java 8" section?

### ISSUE THREAD

**Issue by skestle** [akka/akka#19723]
I've just found the [file streaming API](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.2/scala/stream-io.html#Streaming_File_IO) but states:

> Once Akka is free to require JDK8 (from 2.4.x) these implementations will be updated to make use of the new NIO APIs (i.e. AsynchronousFileChannel).

Akka is at 2.4 and on Java 8; this much should be clarified; does the streaming api use `AsynchronousFileChannel`s? (I presume not, otherwise that would be 2.1+ right?)

**Comment by ktoso** [comment]
It's not yet using `AsynchronousFileChannel`

**Comment by ktoso** [comment]
This was solved in #19907
