### ISSUE TITLE
spec bug in Persistence TCK

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19728]
The current TCK does the following:

* persist single events 1 to 3
* persist an atomic write of 4 and 5

Then the test case `"replay messages using a lower and upper sequence number bound"` requests events 2 to 4, expecting to receive all of them.

The point of AtomicWrites is that replay shall give us either none or all of them and the TCK violates this contract. In fact, it prevents journals from implementing it correctly.

Changing this will declare all existing journal implementations as invalid, but I doubt that any user relies upon the broken behavior. How do we go about this?

**Comment by patriknw** [comment]
I'm not sure I agree. The point is to save all or nothing. It should still be possible to replay with a upper seq number bound 4, and only get 2, 3, 4. I specifically remember Greg's comment in https://github.com/akka/akka/issues/15377

> Also be careful of an anti-pattern that many of the frameworks have done here. The writing of multiple events does not affect how they are read. EG if I write 7 events atomically they are still read as 7 distinct events not as a "batch of 7 events".

**Comment by patriknw** [comment]
And note that `persistAll` is an optional feature, it might be too hard to implement with some journals. See `supportsAtomicPersistAllOfSeveralEvents`

**Comment by ktoso** [comment]
Was about to reply here but Patrik got here first :)
Agree with Patrik that persistAll is about "persist all or nothing" and it should not have any impact on replayability (other than if it did not persist, then we can replay anything, if we did, then we can replay either to 4 or 5).

A replaying journal can obtain the "atomically stored bunch of objects" and emit the events from it, and also it can cease emitting from it if it notices that "oh, replay was asked only to 4, so no need to emit the rest of that bunch".

**Comment by rkuhn** [comment]
I strongly disagree: what is the point of the storage guarantee if reads are allowed to break it? The only point for storing the events is that they can be read—and if they are read then either the whole bunch or none of them. Without this, it makes no sense to have any atomicity at all.

Greg’s note is about something else: I am not arguing for presenting a batch as a unit during replay, events shall still be presented individually to the reader of the journal.

**Comment by rkuhn** [comment]
Formulated from another angle: `persistAll` is used so that recovery of the Actor never leaves it in a state that includes only a subset of the changes. QED.

**Comment by rkuhn** [comment]
Hmm, perhaps my wording above was a bit too forceful, apologies. But I maintain that “atomic” only makes sense in one way, and that way is not currently implemented.

On the topic of different journals possibly having issues supporting `persistAll` I am happy to report that this does not present a challenge to any storage engine that is capable of either performing a single item write or failing it, i.e. single item atomicity iis sufficient. And every journal must support that.

**Comment by patriknw** [comment]
Replaying to a specific sequence number is a power user feature and there are much more dangerous things that can be done when in that mode than getting the event that was explicitly asked for.

**Comment by rkuhn** [comment]
Okay, so the conclusion is that the TCK shall be changed such that an implementation may or may not replay partial atomic batches—this is the best option since it does not change any implicit or explicit guarantees that are currently in place.

**Comment by ktoso** [comment]
Right, agreed :+1:
