### ISSUE TITLE
A more consistent and succinct way to mark async boundaries

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19732]
`.withAttributes(Attributes.asyncBoundary)` is verbose given that it is something one would expect to do pretty often. I propose that we introduce a shortcut `{Source,Flow,Sink}.async` just like `.named()` which exists already and remove `Flow.viaAsync(flow)` which will then instead be `Flow.via(flow.async)`

**Comment by johanandren** [comment]
Discussion on gitter: https://gitter.im/akka/dev?at=56bb0e980fda6e254372e251

**Comment by hepin1989** [comment]
the elixir way😃
