### ISSUE TITLE
optionMarshaller - is None returning a 200 what we really want?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19740]
Hi @sirthias @jrudolph,
I was reading this blogpost : http://danielasfregola.com/2016/02/07/how-to-build-a-rest-api-with-akka-http/

And realised that when we have an `Option[String]` for example, and we `complete` with a `None` the default `EmptyValue[]` mechanism kicks in and the response will be a `200` response. Is there some deeper reason behind that? I would have thought a 404 would be more appropriate to model the `None` case.

Code in question:

```scala
  implicit def optionMarshaller[A, B](implicit m: Marshaller[A, B], empty: EmptyValue[B]): Marshaller[Option[A], B] =
    Marshaller { implicit ec ⇒
      {
        case Some(value) ⇒ m(value)
        case None        ⇒ FastFuture.successful(Marshalling.Opaque(() ⇒ empty.emptyValue) :: Nil)
      }
    }
```

Let me know if there's a story behind the 200 response there or if we simply should fix it, thanks a lot in advance!

// Yup I'm back from vacation, was great (now a bit sick though), so back to hacking full speed now :-)

**Comment by sirthias** [comment]
I don't think there is generally "correct" semantic for marshalling `None`.
Depending on the application `None` could rendered to a `200 Ok`, `204 No Content`, `404 Not Found` or any other kind of response.

Note that in the case you want a `404` response you can use the `rejectEmptyResponse` directive which was inherited from spray (http://spray.io/documentation/1.2.2/spray-routing/misc-directives/rejectEmptyResponse/) and is part of the `MiscDirectives`.

**Comment by ktoso** [comment]
That's true as well that the right answer is "it depends" here hm...
Instead of changing behaviour I'll document how to change the none case by providing an `EmptyValue` implicitly and mention `rejectEmptyResponse` then.

**Comment by ktoso** [comment]
Closing for now as obsolete
