### ISSUE TITLE
fix the release script to allow a successful run after a dry-run

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19767]
Why does the release script call `publishM2` at all?

**Comment by drewhk** [comment]
well, this would be technically similar to what I proposed, namely to make major release steps individually executable. That would mean that after the dry-run only the remaining steps needs to be executed.

**Comment by rkuhn** [comment]
You propose an enhancement while I point out a bug :-)

**Comment by drewhk** [comment]
ok, I misread the ticket then :) (I thought that you just don't want to reexecute everything after a dry-run but reuse the produced results)

**Comment by ktoso** [comment]
I think you're right it does not have to publishM2 nowadays anymore.
AFAIR we needed it because Java8 samples, which are built via maven, depended on the released M2 Akka this way. Now we don't need that anymore?

**Comment by drewhk** [comment]
wasn't it the OSGi tests that needed it?

**Comment by 2m** [comment]
OSGi tests need it, but we are not running tests during a release.

**Comment by rkuhn** [comment]
two things:

* the publishing should only happen when actually running the tests, currently it is linked to the wrong task
* the artifacts should be published to a temporary repository unter `target/` that is wiped afterwards
