### ISSUE TITLE
Investigate connection processing speed in HTTP/TCP

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19765]
I suspect that the ConnectionSourceStage is the main bottleneck here. This can be decided by:

Take the connection processing code from Http.bindAndHandle and feed it with a source of dummy connection stages that are not TCP connections. This part should be fast enough. If this is indeed fast, then the only bottleneck can be upstream.

Benchmark the TCP connection source and see what speed it can provide. If it is not enough, then the bottleneck has been confirmed, and the stage must be redesigned.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by jrudolph** [comment]
Don't think that this is a http(-only) ticket. Reopened here.

**Comment by ktoso** [comment]
Okey 👍

**Comment by ktoso** [comment]
Okey, 👍 mark as triaged then as well
