### ISSUE TITLE
implicit value missing for default types example List[Int]

### ISSUE THREAD

**Issue by Saheb** [akka/akka#19770]
```
scala> responseFuture onSuccess { case response => Unmarshal(response.entity).to[List[Int]]}
Main.scala:371: could not find implicit value for parameter um: akka.http.scaladsl.unmarshalling.Unmarshaller[akka.http.scaladsl.model.ResponseEntity,List[Int]]
responseFuture onSuccess { case response => Unmarshal(response.entity).to[List[Int]]}
```
http://www.typesafe.com/activator/template/akka-http-microservice#code/src/main/scala/AkkaHttpMicroservice.scala

The above issue occurred while trying to deserialize HttpResponse.entity using Unmarshal to default collection types. Similar to the case class deserialization done in example in the above link.

**Comment by jrudolph** [comment]
This is expected because it's not clear how an entity should be unmarshalled to `List[Int]`. What kind of serialization format do you have in mind (and which `Content-Type`)?

**Comment by Saheb** [comment]
Let us remove the response.entity and pass "[1,2,3]" as argument to Unmarshal. It still fails with same error.

While using spray-json and using DefaultJsonProtocol, I could simply get it done like this:

```
@ "[1,2,3]".parseJson.convertTo[List[Int]]
res24: List[Int] = List(1, 2, 3)
```
How should I get this done with Unmarshal abstraction?

**Comment by ktoso** [comment]
You'd have to go via JsValue since otherwise we have no idea that's the way you want to unmarshal it - the types are not enough. `Unmarshal(ByteString).to[JsValue]` etc

**Comment by ktoso** [comment]
You could provide an Unmarshaller of type Unmarshaller[ByteString, List[Int]] and inside do the json things, then the `Unmarshal()` infra could pick it up by type and do what you want from it.
