### ISSUE TITLE
Multiple FilePublisher debug messages that there no more bytes available to read 

### ISSUE THREAD

**Issue by kazuhiro** [akka/akka#19775]
Due to lack of validation if `EOF` has been already encountered, `akka.stream.impl.io.FilePublisher` reports `No more bytes available to read (got `-1` from `read`), marking final bytes of file ...` multiple times (as many as it is required to empty chunks buffer). This could suggest user that the file was read multiple times, which is not true.

This could be easily fixed by adding an additional condition in `readAhead` conditional statement. Let me know if you would like me to create a PR.

**Comment by ktoso** [comment]
Thanks, a PR would be most welcome. Thanks

**Comment by kazuhiro** [comment]
https://github.com/akka/akka/pull/19779
