### ISSUE TITLE
silence Java serialize warning for java.lang.String

### ISSUE THREAD

**Issue by patriknw** [akka/akka#19789]
I think all `java.lang.*` should be silenced, at least `String` and primitive types.

**Comment by johanandren** [comment]
Is that because it is annoying in the tests? Isn't it still a bad idea, even for primitives and `String`?

**Comment by patriknw** [comment]
Yes, it's annoying in tests, but Java serialization of String should not be too bad. The format will not change and performance should be alright since it is defined specially in the [Java Serialization Protocol](https://docs.oracle.com/javase/7/docs/platform/serialization/spec/protocol.html#8299).
