### ISSUE TITLE
[akka-stream] Transpose a sources sequence

### ISSUE THREAD

**Issue by rbelouin** [akka/akka#19782]
I cannot find an elegant way of transposing a sources sequence by `Source.combine()` in Akka Stream.

I mean transpose as in [`Data.List.transpose`](http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-List.html#v:transpose) in Haskell, or [`Bacon.zipAsArray()`](http://baconjs.github.io/api.html#bacon-zipasarray) in Bacon.js. It is like a `ZipN` handling sequences instead of tuples.

Would you agree to let me add a new `Graph` subclass and a `transpose` method to the `Source` object for this purpose? Or is my use-case too specific to be worth submitting a pull-request?

Exemples given:

``` scala
scala> val sources = Seq(
     | Source(List(1, 2, 3, 4)),
     | Source(List(10, 20, 30, 40)),
     | Source(List(100, 200, 300))
     | )
sources: Seq[akka.stream.scaladsl.Source[Int,Unit]] = List(akka.stream.scaladsl.Source@67a54547, akka.stream.scaladsl.Source@4ee81e76, akka.stream.scaladsl.Source@479918)

scala> Source.transpose(sources).runWith(Sink.seq)
res2: scala.concurrent.Future[Seq[Seq[Int]]] = scala.concurrent.impl.Promise$DefaultPromise@22f4103

scala> res2.value
res3: Option[scala.util.Try[Seq[Seq[Int]]]] = Some(Success(Vector(Vector(1, 10, 100), Vector(2, 20, 200), Vector(3, 30, 300))))
```

``` scala
scala> Source.combine(
     | Source(List(4, 5, 6)),
     | Source(List(40, 50, 60)),
     | Source(List(400, 500, 600))
     | )(n => Transpose(n))
res5: akka.stream.scaladsl.Source[Seq[Int],Unit] = akka.stream.scaladsl.Source@5af484f5

scala> res5.runWith(Sink.seq)
res6: scala.concurrent.Future[Seq[Seq[Int]]] = scala.concurrent.impl.Promise$DefaultPromise@5f7def96

scala> res6.value
res7: Option[scala.util.Try[Seq[Seq[Int]]]] = Some(Success(Vector(Vector(4, 40, 400), Vector(5, 50, 500), Vector(6, 60, 600))))
```

**Comment by drewhk** [comment]
Isn't that simply `flatMapConcat`?

**Comment by rbelouin** [comment]
`flatMapConcat` returns a `Repr[T]`, and I actually need a `Repr[Seq[T]]`.

**Comment by drewhk** [comment]
`sources.mapAsync(_.runWith(Sink.seq))`

**Comment by rbelouin** [comment]
Your solution is concatenating the sequence representation of each source. I want to zip them, but by handling sequences instead of tuples.

**Comment by drewhk** [comment]
I see.

**Comment by johanandren** [comment]
What about `ZipWithN`?

Not quite as generic, but maybe enough?

```Scala
val one = Source(List(1, 2, 3, 4))
val two = Source(List(10, 20, 30, 40))
val three = Source(List(100, 200, 300))

GraphDSL.create(){ implicit b =>
  import GraphDSL.Implicits._
  val zip = b.add(new ZipWith3[Int, Int, Int, List[Int]](List.apply(_, _, _)))

  one   ~> zip.in0
  two   ~> zip.in1
  three ~> zip.in1

  SourceShape(zip.out)
}
```

**Comment by johanandren** [comment]
Ah, you explicitly said "sources sequence" in the title, I saw now.

**Comment by rkuhn** [comment]
IIUC this would be solved by introducing a true `ZipWithN` that works with collections and not tuples, no need to add API on the `Source` side.
