### ISSUE TITLE
StreamSubscriptionTimeoutTerminationMode is ignored

### ISSUE THREAD

**Issue by gelisam** [akka/akka#19791]
According to the [documentation](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.3/stream-configuration.html), akka can be configured to react in three different ways when a subscription timeout occurs: mode `cancel` triggers an error, mode `warn` logs a warning, and `noop` does nothing. Instead, all three modes trigger an error.

You can confirm this by changing the mode in the following test:

https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowPrefixAndTailSpec.scala#L114

The `cancel` mode is the only one which is tested. The `cancel` mode is set, then a timeout is intentionally triggered, and then the test expects an error. However, if we set the mode to `warn` or `noop` instead, the test still passes, indicating that an error still occurs regardless of the chosen mode.

**Comment by gelisam** [comment]
Versions tested: akka-stream 2.0.2 and HEAD (10d3af14785970ba584e15effa4b7472fc1f39d5)

**Comment by ktoso** [comment]
You're right, and it came with the rewrite of how we handle substreams. I have a patch but have mixed feelings about it, will PR it soon.

**Comment by ktoso** [comment]
Can't push on this network :( Will push for discussion in a bit from a different wifi
