### ISSUE TITLE
FAILED akka.stream.tck.VirtualProcessorTest

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19790]
```
- required_spec309_requestZeroMustSignalIllegalArgumentException *** FAILED ***
[info]   java.lang.AssertionError: Expected onError(java.lang.IllegalArgumentException) within 800 ms
[info]   at org.testng.Assert.fail(Assert.java:78)
[info]   at org.reactivestreams.tck.TestEnvironment.flopAndFail(TestEnvironment.java:180)
[info]   at org.reactivestreams.tck.TestEnvironment$Receptacle.expectError(TestEnvironment.java:930)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:484)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:476)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:464)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:459)
[info]   at org.reactivestreams.tck.PublisherVerification$21.run(PublisherVerification.java:862)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1092)
[info]   at org.reactivestreams.tck.PublisherVerification.required_spec309_requestZeroMustSignalIllegalArgumentException(PublisherVerification.java:858)
[info]   at org.reactivestreams.tck.IdentityProcessorVerification.required_spec309_requestZeroMustSignalIllegalArgumentException(IdentityProcessorVerification.java:350)
```

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5250/consoleFull

**Comment by ktoso** [comment]
Another one https://jenkins.akka.io:8498/job/akka-nightly/3053/console

[error] 	akka.stream.tck.VirtualProcessorSingleTest

**Comment by drewhk** [comment]
I think I know this one. So VirtualProcessor does not report this failure itself, it just delegates the requests to the upstream. While there is no upstream, it accumulates requests, and then dispatches it to the upstream once available. At that point it might simply ignore it if it was zero:
```
    def closeLatch(): Unit = {
      val requested = getAndSet(-1)
      if (requested > 0) s.request(requested)
    }
```

**Comment by drewhk** [comment]
another issue is that it also accumulates requests while the upstream is not there, hence if a sequence:
```
request(0)
request(1)
```
arrives before upstream registration, then there won't be any error reported since the second valid request will mask the zero one.

**Comment by 2m** [comment]
(Mar 6, 2016 6:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3573/consoleFull
(Mar 4, 2016 2:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3563/consoleFull
(Feb 29, 2016 9:17:00 PM) https://jenkins.akka.io:8498/job/akka-nightly/3101/consoleFull
