### ISSUE TITLE
AkkaSpec Dependance Miss

### ISSUE THREAD

**Issue by darionyaphet** [akka/akka#19801]
hi @rkuhn I reading [Quick Start Guide: Reactive Tweets](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.3/scala/stream-quickstart.html#stream-quickstart-scala)  and try to running [TwitterStreamQuickstartDocSpec](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/code/docs/stream/TwitterStreamQuickstartDocSpec.scala) . 

But I could't found `import akka.stream.testkit.AkkaSpec` and I had add some dependance. 

```
dependencies {
    compile 'com.typesafe.akka:akka-actor_2.10:2.3.14'
    compile 'com.typesafe.akka:akka-agent_2.10:2.3.14'
    compile 'com.typesafe.akka:akka-cluster_2.10:2.3.14'
    compile 'com.typesafe.akka:akka-kernel_2.10:2.3.14'
    compile 'com.typesafe.akka:akka-slf4j_2.10:2.3.14'
    compile 'com.typesafe.akka:akka-zeromq_2.10:2.3.14'
    compile 'com.typesafe.akka:akka-testkit_2.10:2.3.14'
    
    compile 'com.typesafe.akka:akka-http-experimental_2.10:2.0.3'
    compile 'com.typesafe.akka:akka-stream-experimental_2.10:2.0.3'
    compile 'com.typesafe.akka:akka-stream-testkit-experimental_2.10:2.0.3'
    compile 'com.typesafe.akka:akka-stream-testkit_2.11:2.4.2-RC3'
     
    compile 'com.google.code.gson:gson:2.5'
    compile 'com.google.guava:guava:18.0'
    compile 'com.typesafe:config:1.3.0'
    compile 'com.typesafe.play:play_2.10:2.4.6'
}
```

Should I append any more ?  thank you ~~

**Comment by rkuhn** [comment]
I’m currently adding a new QuickStart guide (see #19800), but besides that: AkkaSpec is not published and you should not need it. It is just a WordSpec with a few standard traits on top and an ActorSystem inside.

**Comment by darionyaphet** [comment]
Nice , `AkkaSpec` will be abandon at new released ? [Quick Start Guide: Reactive Tweets](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.3/scala/stream-quickstart.html)  maybe need update for new beginner . thank you for you great work :)

**Comment by rkuhn** [comment]
Indeed, I’ll avoid using AkkaSpec in the new QuickStart guide, thanks for raising this!
