### ISSUE TITLE
IndexOutOfBoundsException in scaladsl.Merge

### ISSUE THREAD

**Issue by thomas-holmes** [akka/akka#19806]
After processing `Int.MaxValue` elements in a merge the `Int` counter shown [here](https://github.com/akka/akka/blob/5d3a8256c1d4d742b999676bb5050737b7a45ce4/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala#L68) wraps around and causes an `IndexOutOfBoundsException` on the line above. This is due to modulus arithmetic resulting in a negative index used in accessing the `pendingQueue` Array.

I think this should probably use a `mutable.Queue`, reassign the index to the result of the mod each iteration, or maintain a head/tail index in a more traditional circular buffer implementation.

I believe the same problem also exists [here](https://github.com/akka/akka/blob/5d3a8256c1d4d742b999676bb5050737b7a45ce4/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala#L73) where the elements are being dequeued.

**Comment by drewhk** [comment]
Also in FixedSizeBuffer (ModuloFixedSizeBuffer)

**Comment by rkuhn** [comment]
Thanks for the report, very timely! :-)

**Comment by thomas-holmes** [comment]
Appreciate the quick fix :)
