### ISSUE TITLE
StackOverflowError while materializing stream

### ISSUE THREAD

**Issue by MartinSeeler** [akka/akka#19816]
When creating a `Broadcast` and `Merge` with a lot of outputs, I get an `StackOverflowError`. This happens for me with akka-stream version `2.0.3` and `2.4.2`, although the errors are different.

The steps to reproduce in `2.0.3`:
```scala
implicit val system = ActorSystem("error-reproduction-demo")
implicit val mat = ActorMaterializer()

import system.dispatcher

val numbers = Source(1 to 1000)
val numberOfFlows = 5000

Source.fromGraph(GraphDSL.create() { implicit builder: GraphDSL.Builder[Unit] =>
  import GraphDSL.Implicits._

  val bcast = builder.add(Broadcast[Int](numberOfFlows))
  val merge = builder.add(Merge[Int](numberOfFlows))

  numbers ~> bcast

  for (x ← 0 until numberOfFlows) {
    bcast.out(x) ~> Flow[Int].map(x ⇒ x * x) ~> merge.in(x)
  }

  SourceShape(merge.out)
  }).runForeach(println).onComplete(_ ⇒  system.shutdown())
```

There is just the following Exception with no output:

```
Exception in thread "main" java.lang.StackOverflowError
	at akka.stream.impl.fusing.Fusing$.rewriteMat(Fusing.scala:415)
	at akka.stream.impl.fusing.Fusing$.rewriteMat(Fusing.scala:415)
	at akka.stream.impl.fusing.Fusing$.rewriteMat(Fusing.scala:415)
	at akka.stream.impl.fusing.Fusing$.rewriteMat(Fusing.scala:415)
	at akka.stream.impl.fusing.Fusing$.rewriteMat(Fusing.scala:415)
        .......
```

With version `2.4.2`, the code is the same:

```scala
implicit val system = ActorSystem("error-reproduction-demo")
implicit val mat = ActorMaterializer()

import system.dispatcher

val numbers = Source(1 to 1000)
val numberOfFlows = 5000

Source.fromGraph(GraphDSL.create() { implicit builder: GraphDSL.Builder[NotUsed] =>
  import GraphDSL.Implicits._

  val bcast = builder.add(Broadcast[Int](numberOfFlows))
  val merge = builder.add(Merge[Int](numberOfFlows))

  numbers ~> bcast

  for (x ← 0 until numberOfFlows) {
    bcast.out(x) ~> Flow[Int].map(x ⇒ x * x) ~> merge.in(x)
  }

  SourceShape(merge.out)
  }).runForeach(println).onComplete(_ ⇒  system.terminate())
```

But here, the Error is not constant. Sometimes, it's the same error as with `2.0.3`, but sometimes get the following error:

```
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.collection.mutable.StringBuilder.<init>(StringBuilder.scala:49)
	at scala.collection.mutable.StringBuilder.<init>(StringBuilder.scala:54)
	at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:669)
	at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:669)
	at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:669)
       ....
```
and after that, the output from the flows, so the stream is running. I did not find a way to reproduce the situation of running / failing graph.

**Comment by drewhk** [comment]
It seems like the fusor blows up. As a workaround you can turn off fusing.

**Comment by johanandren** [comment]
This error will happen when writing very large graphs since we are doing a recursive tree-transformation internally when fusing. It is not an infinite recursion, rather the graph makes the tree deep enough for the stack to run out. Fixing this is non-trivial.

 As @drewhk one workaround is to turn off fusing (this can be done with `ActorMaterializerSettings(system).withAutoFusing(false)` when creating your materializer), another workaround is to increase your stack size using something like `-Xss3m`

**Comment by ktoso** [comment]
Isn't this solved by the latest improvements @rkuhn did in materialized value computation?

**Comment by rkuhn** [comment]
Fixing this requires a rewrite of the fusing algorithm’s module tree traversal to use trampolining.

**Comment by johanandren** [comment]
So the two example cases are actually resolved already. You can get a `StackOverflowException` if you create a chain of materialized value computations longer than the stack size, which would be solved by #20436. However, since that is a pretty artificial or at least very uncommon use case and materialization speed is very important to us I will close this ticket as solved, and close the PR.

**Comment by drewhk** [comment]
Maybe we should add the test-case to our tests though?

**Comment by johanandren** [comment]
I think we have test coverage for large graphs in `StreamLayoutSpec` already

**Comment by drewhk** [comment]
Ah ok.

**Comment by patriknw** [comment]
Thanks for investigating this, @johanandren
