### ISSUE TITLE
and SubscribeAllKey feature

### ISSUE THREAD

**Issue by netcomm** [akka/akka#19819]
hello @patriknw, i just want to add SubscribeAllKey feature, then actor can subscribes all date items. i have read the Replicator.scala source.now the problem is the "subscriptionKeys" Map miss all the KeyR values,i have some ideas:
1. is it can through ReplicatedData instances and string id to construct one corresponding KeyR instance?
2. modify normalReceive function's Update/Write/ReadRepair case branch, but Write/ReadRepair's key are String Type not KeyR, and maybe it can involved some performace loss?
if i miss something, please correct it, thanks!

**Comment by patriknw** [comment]
yeah, now I remember why I didn't include this feature when importing from https://github.com/patriknw/akka-data-replication

The type of the key is not known. The replicator only knows about the string identifiers, and that is what is transferred between the nodes. Anything else would be too complicated and add too much overhead.

For example, client subscribes to AllKeys from node-1. A new key is added on node-2 and that string identifer is gossiped to node-1, but at node-1 there no knowledge about the key type.

Just subscribing to the to the string idententifiers does not make sense. I don't think we can support this feature.

Instead, I think the application should store the keys that it is interested in to a separate value, e.g. a GSet. Perhaps we can add a special data type for storing keys?

**Comment by netcomm** [comment]
"For example, client subscribes to AllKeys from node-1. A new key is added on node-2 and that string identifer is gossiped to node-1, but at node-1 there no knowledge about the key type."

**Comment by netcomm** [comment]
By the way, Is akka team have a plan to visit china and have some conferences in 2016? We will be very welcome your arrival !

**Comment by patriknw** [comment]
> maybe the keys entire information also gossip to each other nodes

I consider that too complicated and would add too much overhead.
