### ISSUE TITLE
Unhandled akka.actor.Status.Failure in RemoteActorRefProvider in state WaitTransportShutdown

### ISSUE THREAD

**Issue by 412b** [akka/akka#19824]
When RARP is being shutdown in state WaitDaemonShutdown it pipes call result of transport shutdown to self [here](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala#L57). `pipeTo` transforms `scala.util.Failure` into `akka.actor.Status.Failure` [here](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/pattern/PipeToSupport.scala#L20)

Which could still be ok, but [here](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/Remoting.scala#L159) map is used on Future, which is applied only to **Success**, so when we get a failure it has following flow:
[ask] => scala.util.Failure => [pipeTo] => akka.actor.Status.Failure => unhandled message [here](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala#L61)

Filed match for me under heavy load with VisualVM sampling and profiling at the same time brought me
> [WARN] [02/18/2016 09:36:04.442] [lp-akka-cluster-local-test-remote-dispatcher-29] [akka.tcp://lp-akka-cluster-local-test@XXX:2549/system/remoting-terminator] unhandled event Failure(akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://lp-akka-cluster-local-test/system/endpointManager#-2071163190]] after [10000 ms]. Sender[null] sent message of type "akka.remote.EndpointManager$ShutdownAndFlush$".) in state WaitTransportShutdown

There are 3 possible ways to fix it:
1. simply replace `map` with `andThen` - simple and fast, currently failure is not propagated anyway
2. add match for `akka.actor.Status.Failure` in RARP
3. use `akka.actor.Status.Success` (some simple case object can fit) and `akka.actor.Status.Failure` as messages for communication - that way failure can be propagated (I'm not sure, if that's needed anyway) and it looks cleaner for me than using `()` as message, option 2 is required for that to work, of course.

**Comment by drewhk** [comment]
Thanks for reporting! I think the simple solution is fine, maybe with the addition of sandwitching in a step that just logs the shutdown error if any.

**Comment by 412b** [comment]
is "simple solution" relating option 1?
for me all of the ways look pretty simple and it's more about flow preferred.

**Comment by 412b** [comment]
@drewhk I dived in a bit more and can submit a PR for 2nd option, which:
- logs smth like "Remoting shut down with error:.."
- doesn't try to shutdown transport again, because it can be a race and I'm not sure about the effect of publishing `RemotingShutdownEvent` more than one time
- notify system guardian and stop

the reason behind is that otherwise timeout won't be logged anywhere (as I see no log messages from `Remoting`).
