### ISSUE TITLE
The event-adapter-bindings doesn't support inner classes.

### ISSUE THREAD

**Issue by matef** [akka/akka#19826]
I was trying to bind an event to my EventAdapter, but it gave me ClassNotFoundException, however it worked when I extracted the event from the companion object. Here is my code:
```
object  BusinessObject{
  sealed trait Command
  case class UpdateBO(id:String, _type:String, payload: Map[String,Any]) extends Command 

  sealed trait Event
  case class BOUpdated(id:String, _type: String, payload: Map[String,Any]) extends Event
}
```
```
event-adapters {
          tagging = "evt.BOEventAdapter"
        }

        event-adapter-bindings {
          "cmd.BusinessObject.BOUpdated" = tagging
        }
```

It gives me
 ```java.lang.ClassNotFoundException: cmd.BusinessObject.BOUpdated```

**Comment by johanandren** [comment]
I think that is because the string should actually be the Java class name, the Scala compiler will generate a field called `MODULE$` that will be the singleton, which means the object will actually be named `cmd.BusinessObject.MODULE$.BOUpdated`

**Comment by rkuhn** [comment]
No, this has nothing to do with Scala: on the JVM the class name would also for Java be `cmd.BusinessObject$BOUpdated`.
