### ISSUE TITLE
Clarify Accept header handling in comparision to Spray

### ISSUE THREAD

**Issue by ahjmorton** [akka/akka#19842]
Hi there,

I would like the behaviour of how akka-http handles the Accept header clarified. Possibly in the spray-migration guide as the behaviour appears to be different.

Given the following routes structure in either Spray / Akka-http :
```scala
pathPrefix("test" / LongNumber) { number =>
   get {
      complete {
          //Imagine some other validation occuring
          if(number > 100) {
              BadRequest -> "Currently we don't support numbers greater than 100"
          } else {
              OK -> service.retrieveJsonFor(number)
          }
      }
   }
}
```
Now say I make the following call
```
GET test/101
Accept: application/json
```
Spray will return
```
400 Bad Request
Content-Type: text/plain
Currently we don't support numbers greater than 100
```
Whereas akka-http will return
```
406 Not Acceptable
Content-Type: text/plain
Resource representation is only available with these types:
application/json
```
This difference should be highlighted somewhere in the documentation at least. The behaviour causes the lose of the BadRequest error message / changing of status codes which is a bit of a gotcha when moving an existing Spray app to akka-http.

Kind regards,

am

**Comment by jrudolph** [comment]
See also https://github.com/akka/akka/issues/19397.

**Comment by patriknw** [comment]
@ktoso is this a bug?

**Comment by ktoso** [comment]
Correct, I consider it a bug and I did a fix already :) 
https://github.com/akka/akka/issues/19849 need to get to merging it
