### ISSUE TITLE
Lightbend rebranding

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19851]
All occurrences of Typesafe (Inc.) to be rewritten to Lightbend (Inc.); ~~also change the groupId for publishing to `com.lightbend.akka`.~~

**Comment by patriknw** [comment]
Don't you think there will be issues with transitive dependencies when changing the groupId in a minor patch version? Users will end up with both com.typesafe.akka and com.lightbend.akka in their classpath and nobody knows what version that is actually used.

**Comment by rkuhn** [comment]
Would that be solved by waiting, though? It would only be “safe” if we make such breaking changes that nothing works until you fix all the dependencies, but do we intend to make such a change anytime soon?

**Comment by patriknw** [comment]
It's about expectations. A minor patch version should be a drop-in, and all transitive dependencies should just work. Strictly speaking it should be a 3.0, since we are on the binary compatibility track for all 2.5, but I think we could do such change in 2.5.

**Comment by rkuhn** [comment]
Thinking some more about it, our hand is actually forced by Play, and since [that will only switch in version 3.0](https://www.reddit.com/r/scala/comments/474kqy/typesafe_changes_name_to_lightbend/d0a7laf) we will have to align our 3.0 with theirs to make this transition work—otherwise Play users will run into serious troubles when also including Akka (essentially it is our binary compatibility promise that will lure people onto the ice).

So, ticket description amended to not change groupId at this point.

**Comment by patriknw** [comment]
+1
