### ISSUE TITLE
remove “experimental” from Akka Distributed Data 

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19852]
The module is stable enough, so we are taking the opportunity of #19851 requiring build definition adaptations to sneak in this change as well.

**Comment by rkuhn** [comment]
@patriknw WDYT?

**Comment by patriknw** [comment]
I have no problem with that, but I'm concerned about #19851.
In hindsight we should not have used `experimental` as part of the artifact name.

**Comment by rkuhn** [comment]
Okay, unfortunately our hands are tied as discussed over there.
