### ISSUE TITLE
Standardize on code inclusion mechanism in docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19856]
Now we switch between `:includecode:` and `:includecode2:` possibly without reasons.

Some vague discussion in gitter: https://gitter.im/akka/dev?at=56cc6b91bd660af56c7270da

I just followed orders creating this ticket, not sure I have an opinion ;)

**Comment by viktorklang** [comment]
includecode2 has to get a nomination for worst feature name.

**Comment by viktorklang** [comment]
Almost at the level of VARCHAR2

**Comment by ktoso** [comment]
Basically I think we want `includecode` the name, but `includecode2` the impl ;-)

**Comment by viktorklang** [comment]
@ktoso What does that mean in practice? (i.e. is it a lot of work?)

**Comment by ktoso** [comment]
copy & paste (5 minutes) + checking if it breaks things (tricky, some skimming of docs needed).
but its not hard per se.

**Comment by 2m** [comment]
A simple copy would break in places where @johanandren was having problems yesterday where `includecode2` was including more than `includecode`.

**Comment by patriknw** [comment]
what are the differences?

**Comment by ktoso** [comment]
Things I remember, includecode2 does in addition to what the normal one does:

- smart concating of "same prefix" (include "bla" would include bits from "bla-start" and "bla-end" concatted etc).
- it can include a snippet based on the string of the test (i.e. include `#bob` would include the test body of `"bob" in {`)
- AFAIR we made it fail is a snippet is not existing, not just warn (good thing, but make sure that's the current semantics)
- if :snippet: is a method name, it includes the method signature (no body) - used in HTTP to show "this is the signature of the directive" a lot

AFAIR that's it

**Comment by patriknw** [comment]
Thanks for clarifying. Sounds good, apart from that I'm not convinced about the "smart prefix". Same can be achieved by having multiple sections of same tag.

**Comment by ktoso** [comment]
Yeah, agreed - we should be able to remove that feature

**Comment by patriknw** [comment]
it's not important to remove that if it's already heavily used in http docs, but we must make sure we don't break any existing code (e.g. add some println when testing the conversion)

**Comment by drewhk** [comment]
Isn't it not just simply concatenate with the prefix feature but also filter out nested tags?

**Comment by ktoso** [comment]
I think you're right @drewhk, I forgot about that part of the feature

**Comment by Captain1653** [comment]
The issue was created 5 years ago. Is it still needed? Maybe it relates to [the comment](https://github.com/akka/akka/issues/17650#issuecomment-869982562) . I'm not sure.

Kind regards

**Comment by johanandren** [comment]
Another archival find, this was the previous doc tool we used. Let's close.
