### ISSUE TITLE
FAILED: ClusterShardingGetStatsSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19863]
https://jenkins.akka.io:8498/job/akka-nightly/3083/consoleFull

```
[JVM-3] - must return stats after a node leaves *** FAILED ***
[JVM-3]   0 did not equal 2 (ClusterShardingGetStatsSpec.scala:217)
[JVM-3] [WARN] [02/23/2016 22:43:59.735] [ClusterShardingGetStatsSpec-akka.actor.default-dispatcher-18] [akka.tcp://ClusterShardingGetStatsSpec@localhost:56753/system/sharding/Ping] Trying to register to coordinator at [Some(ActorSelection[Anchor(akka://ClusterShardingGetStatsSpec/), Path(/system/sharding/PingCoordinator/singleton/coordinator)])], but no acknowledgement. Total [4] buffered messages.
```

**Comment by johanandren** [comment]
Possibly related to #19601 that got merged two days ago.

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3091/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3535/consoleFull

**Comment by 2m** [comment]
(Mar 7, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3120/consoleFull
(Mar 4, 2016 11:19:00 PM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3566/consoleFull
(Mar 4, 2016 9:17:00 PM) https://jenkins.akka.io:8498/job/akka-nightly/3113/consoleFull
(Mar 4, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3111/consoleFull
(Mar 3, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3108/consoleFull
(Mar 2, 2016 6:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3557/consoleFull
(Mar 1, 2016 11:19:00 PM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3554/consoleFull
(Mar 1, 2016 4:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3552/consoleFull
(Feb 29, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3099/consoleFull
(Feb 28, 2016 9:17:00 PM) https://jenkins.akka.io:8498/job/akka-nightly/3098/consoleFull
(Feb 28, 2016 1:17:00 AM) https://jenkins.akka.io:8498/job/akka-nightly/3096/consoleFull
(Feb 26, 2016 4:47:09 PM) https://jenkins.akka.io:8498/job/akka-multi-node/1368/consoleFull

**Comment by 2m** [comment]
Note that this issue has a pending PR that fixes it.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1384/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3583/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3127/consoleFull

variation though:
```
[JVM-2] - must return stats after a node leaves *** FAILED ***
[JVM-2]   2 did not equal 4 (ClusterShardingGetStatsSpec.scala:218)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1385/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3586/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/3129/consoleFull

**Comment by ktoso** [comment]
Again https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3596/consoleFull
