### ISSUE TITLE
Provide built-in header and document HSTS (Strict-Transport-Security)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19861]
It's a fairly easy thing to do and is quite nice from a security perspective.

On our end we should:
- [ ] provide a modeled header for `Strict-Transport-Security` (those are used like so `Strict-Transport-Security: max-age=31536000`)
- [ ] document how returning it helps security
- technically we could always add such header if configured to do so, but that's an extra, not really needed as part of this ticket.

Read more: 

- https://tools.ietf.org/html/rfc6797
- https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

**Comment by jrudolph** [comment]
:+1:
