### ISSUE TITLE
[breaking] Consider allowing backoff supervision in place of usual supervision

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19866]
This would have to be in Akka 3 as it changes much.
In general we could be able to make supervision have a backoff mechanism, as @patriknw states on why it's not built in currently:

> The original reason there was no backoff supervision was that suspending the actor during the backoff might result in unbounded queuing of messages, but it's an interesting idea if its fine to drop messages during backoff and we could let the mailboxes know about it somehow.

But with dropping messages during backoff time we could consider it. 
Yay / Nay?

**Comment by ktoso** [comment]
Assigned to `3.x` as this change is a rather big change that would require breaking things, so it'd have to be in 3.0.

**Comment by patriknw** [comment]
Backoff supervision is part of normal supervision in Akka Typed, so I think we'll not touch the untyped and rather recommend using typed.
