### ISSUE TITLE
'Inherit' parent actor deploy options

### ISSUE THREAD

**Issue by vkrot** [akka/akka#19872]
It would be nice to have ability to inherit deploy options of parent actor. Real inheritance might not work with remote systems, as they may be configured differently, but what I would like to have is path `/my-actor/*` to match all actors under `/my-actor` - `/my-actor/child` and `/my-actor/child/child` and so on. 
Now only `/my-actor/child` is matched by `/my-actor/*` so I have to write something like
```
'/my-actor/*' { .. config }
'/my-actor/*/*' { .. config }
'/my-actor/*/*/*' { .. config }
```

This can be implemented by just changing `WildcardTree`. I can submit a pull request, but just wonder what it the better way to implement it - it seems that changing current behavior is not good as it may break existing configurations. I'd suggest using ant path style - use one wildcard to match exactly one actor path element and two wildcards to match any number of elements in the path.

What do you think?

**Comment by patriknw** [comment]
I think this has been requested several times. A contribution for `**` sounds great.

**Comment by patriknw** [comment]
@vkrot sorry for the delay, contribution would be great
