### ISSUE TITLE
New Java API: creating Encoder

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19882]
The old JavaDSL does not allow creating Encoder instances in javadsl.
The new one will be able to, we just need to add it ;-)

**Comment by ktoso** [comment]
See https://github.com/akka/akka/pull/19632/files#r52922741 for context

**Comment by jypma** [comment]
Same holds for `Decoder` as well.

**Comment by ktoso** [comment]
Right, thanks :)

**Comment by agolubev** [comment]
@ktoso, as far as I understand enum akka.http.javadsl.server.Coder should be changed to be able to create custom Coder like described in https://blogs.oracle.com/darcy/entry/enums_and_mixins ?
Also can Java 8 create instance of trait akka.http.scaladsl.coding.Coder (that extends Encoder with Decoder)? If the anser is -no-, than need to look to another approach with splitting encoder and decoder in Java API

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
