### ISSUE TITLE
Current way of passing settings to sbt projects is obsolete and may produce compatible problems

### ISSUE THREAD

**Issue by strobe** [akka/akka#19887]
I just found that current approach of passing settings to sbt projects is little obsolete 
and may produce compatible issues with some of sbt plugins at global sbt context.
(for instance ```Cannot add dependency 'org.scala-lang\#scala-compiler;2.11.7' to configuration 'ensime-internal'"`` with ensime-sbt (https://github.com/ensime/ensime-sbt/issues/140)).

Following files affected:
- project/AkkaBuild.scala
- akka-samples/akka-sample-cluster-java/build.sbt
- akka-samples/akka-sample-cluster-scala/build.sbt
- akka-samples/akka-sample-distributed-data-java/build.sbt
- akka-samples/akka-sample-distributed-data-scala/build.sbt
- akka-samples/akka-sample-multi-node-scala/build.sbt

Currently settings passed by `Project(settings = Seq(...))` but it looks like at some cases `settings` should be modified at `Project` construction (probably by AutoPlugins).
Is exist alternative approach of passing settings by method: `Project().settings(Seq(...))`, which append settings sequence to project (sbt documentation currently used this approach http://www.scala-sbt.org/0.13/docs/Using-Plugins.html).

From sbt sources:
```scala
/** Appends settings to the current settings sequence for this project. */
def settings(ss: Def.SettingsDefinition*): Project = copy(settings = (settings: Seq[Def.Setting[_]]) ++ Def.settings(ss: _*))
```

Also Defaults.defaultSettings & Project.defaultSettings has been used at those files, but both is deprecated now (`(@deprecated("Use Defaults.coreDefaultSettings instead, combined with AutoPlugins.", "0.13.2"))`).

(I have PR with fix - will create it soon)

**Comment by 2m** [comment]
Fixed in #19888
