### ISSUE TITLE
akka peristence: if the message is not serializable, plugin failed to persist without giving any error

### ISSUE THREAD

**Issue by TimPigden** [akka/akka#19891]
NB this is a bug in a specific plugin. My argument is that a test should be part of the TCK

If the object that is being persisted turns out not to be serializable, then the store fails. However, no warning is given, the thing simply is not there on a recovery operation. 
I presume this is not part of the TCK (and will probably raise it as an issue there).

running the program gives:

assertion failed: expected GotBack(Some(Thing(2))), found GotBack(None)
java.lang.AssertionError: assertion failed: expected GotBack(Some(Thing(2))), found GotBack(None)

config settings

akka {
loglevel = DEBUG
logger-startup-timeout = 30s
logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
actor.debug.fsm = true
loggers = ["akka.event.slf4j.Slf4jLogger"]

extensions = ["com.romix.akka.serialization.kryo.KryoSerializationExtension$"]

persistence {
// journal.plugin = "akka-persistence-sql-async.journal"
// snapshot-store.plugin = "akka-persistence-sql-async.snapshot-store"
journal.plugin = "inmemory-journal"
snapshot-store.plugin = "inmemory-snapshot-store"
journal-plugin-fallback {
replay-filter {
mode = fail
}
}
}

//----------------- Kryo config ----------------------

actor {
serialize-messages = off

serializers {
  java = "akka.serialization.JavaSerializer"
  # Define kryo serializer
  kryo = "com.romix.akka.serialization.kryo.KryoSerializer"
}

serialization-bindings {
  "java.io.Serializable" = java
}

kryo {
  type = "nograph"
  idstrategy = "default"
  kyro-trace = true
}
}
}

source code below (since I can't attach a scala program)

=======================
package com.optrak.vrp.ddd

import java.util.UUID

import akka.actor.{ActorLogging, PoisonPill, Props}
import akka.persistence.PersistentActor
import com.optrak.opkakka.test.TestSupport.AkkaTestkitContext
import com.optrak.vrp.ddd.SimplePersistor.PersistMe
import org.specs2.mutable.Specification

/**

Created by tim on 21/02/16. */
object SimplePersistor {
  case class PersistMe(k: AnyRef)

  case class GotBack(kOpt: Option[AnyRef])

  case object Request

  def props = Props(new SimplePersistor("hello"))
}
import SimplePersistor._

case class SimplePersistor(persistenceId: String) extends PersistentActor with ActorLogging {

  var local: Option[AnyRef] = None

  def handler(msg: PersistMe) = {
    local = Some(msg.k)
  }
  override def receiveRecover: Receive = {
    case pm: PersistMe =>
      local = Some(pm.k)
  }

  override def receiveCommand: Receive = {
    case pm: PersistMe =>
      persist(pm)(handler)
    case Request =>
      sender ! GotBack(local)

  }

}

class TestAkkaSerializability extends Specification {
  sequential //our set always has the same persistence id, so have to

  trait Checkit extends AkkaTestkitContext {

    def checkItOut(k: AnyRef) = {
      val persy1 = system.actorOf(SimplePersistor.props)
      persy1 ! Request
      expectMsg(GotBack(None))

      persy1 ! PersistMe(k)
      persy1 ! Request
      expectMsg(GotBack(Some(k)))

      persy1 ! PoisonPill
      Thread.sleep(200)

      val persy2 = system.actorOf(SimplePersistor.props)
      persy2 ! Request
      expectMsg(GotBack(Some(k)))

    }
  }

  "persistent set" should {
    "work with String" in new Checkit() {
      checkItOut("ho")
    }

    "fails with unserializable" in new Checkit() {
      val x = 1
      case class Thing(y: Int)
      val tricky = new Thing(2) {
        def xMe = x
      }

      checkItOut(tricky)

    }
  }

}

=========================== 
sbt

name := "akkautil"

scalaVersion := "2.11.7"

credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")

updateOptions := updateOptions.value.withCachedResolution(true)

publishTo := Some("Optrak snapshots" at "http://office.optrak.com:8080/nexus/content/repositories/snapshots/")

scalacOptions := Seq("-feature" , "-deprecation" , "-encoding", "utf8" , "-Xlint", "-language:postfixOps")

javaOptions in Test ++= Seq("-Xmx2000M", "-XX:MaxPermSize=2000M")

resolvers ++= Seq(
    "dnvriend at bintray" at "http://dl.bintray.com/dnvriend/maven",
    "Artima Maven Repository" at "http://office.optrak.com:8080/nexus/content/repositories/artima/",
    "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"
)

addCompilerPlugin("com.artima.supersafe" %% "supersafe" % "1.0.0")

libraryDependencies ++= {
  val akkaVersion = "2.4.2"
  val integration = "latest.integration"
  Seq(
    "com.typesafe.akka" %% "akka-actor" % akkaVersion,
    "com.typesafe.akka" %% "akka-agent" % akkaVersion,
    "com.typesafe.akka" %% "akka-testkit" % akkaVersion % "test",
    "com.typesafe.akka" %% "akka-slf4j" % akkaVersion,
    "com.typesafe.akka" %% "akka-persistence" % akkaVersion,
    "com.github.romix.akka" %% "akka-kryo-serialization" % "0.4.0",
    "com.okumin" %% "akka-persistence-sql-async" % "0.3.1",
    "com.github.mauricio" %% "postgresql-async" % "0.2.16",
    "com.typesafe.akka" %% "akka-http-experimental" % akkaVersion,
    "com.typesafe.akka" %% "akka-http-core" % akkaVersion,
    "com.typesafe.akka" %% "akka-stream" % akkaVersion,
    "com.typesafe.akka" %% "akka-http-testkit" % akkaVersion % "test",
    "com.typesafe.akka" %% "akka-http-xml-experimental" % akkaVersion,
    "org.scala-lang.modules" %% "scala-xml" % "1.0.5",
    "org.specs2" %% "specs2-core" % "3.6.2" % "test" ,
    "com.optrak" %% "scalautil" % integration,
    "com.github.dnvriend" %% "akka-persistence-inmemory" % "1.2.6",
    "org.apache.directory.api" % "api-all" % "1.0.0-M31"
  )
}

parallelExecution in Test := false

exportJars := true

fork in Test := true

**Comment by patriknw** [comment]
We added this to the TCK as far as I recall
