### ISSUE TITLE
Replace errorLogging with GraphStage

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19899]
If you want to help out a bit there's a nice low hanging fruit in that area though:
The usage of transform+pushstage in: https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L251
and https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/util/package.scala#L92 
should be rewritten to be a GraphStage

**Comment by miciek** [comment]
@ktoso Happy to help out with this :)

**Comment by ktoso** [comment]
Excellent thanks!

**Comment by miciek** [comment]
Created PR #19905
