### ISSUE TITLE
Sharding: MessageExtractor receiving SaveSnapshotSuccess after enabling 'remember-entities'

### ISSUE THREAD

**Issue by mbknor** [akka/akka#19893]
Akka 2.4.1

When  'akka.cluster.sharding.remember-entities' is enabled, the sharding MessageExtractor  sometimes wrongly receives SaveSnapshotSuccess-messages like this:

SaveSnapshotSuccess(SnapshotMetadata(/sharding/xxxxxxShard/7,10999,1456458481541))

The written snapshots are of type 'akka.cluster.sharding.Shard$State' and basically contains the list of allive actors in that shard.

More info can be found here: https://groups.google.com/forum/#!topic/akka-user/DiduqWnQeLI

**Comment by drewhk** [comment]
thanks for reporting!
