### ISSUE TITLE
Add support for Google gRPC

### ISSUE THREAD

**Issue by rock59** [akka/akka#19900]
Add support for Google gRPC

**Comment by ktoso** [comment]
How would you imagine that in more detail? :)

**Comment by tjdett** [comment]
It would be good to have support for this once #16862 is completed, as it would avoid using two separate HTTP stacks in Akka-based apps.

**Comment by xuwei-k** [comment]
https://github.com/akka/akka-grpc

**Comment by ktoso** [comment]
Yup, it indeed is happening. It will be put on top of Akka HTTP; We will add HTTP/2 to the client side of Akka HTTP thanks to that :)
