### ISSUE TITLE
[akka-http] DebuggingDirectives should not toString() if log level not enabled

### ISSUE THREAD

**Issue by jypma** [akka/akka#19914]
The `log*` directives in `DebuggingDirectives` right now always invoke the `LoggingMagnet`'s function, which in turn always operates on a `LogEntry` case class that just `toString`s its argument.

We should only `toString` (and preferably only invoke any custom "show" closures) when the log level is actually enabled. This could be done inside the `LogEntry` class, or maybe in the directives themselves.

**Comment by jypma** [comment]
@ktoso This might affect https://github.com/akka/akka/pull/19632, although it can probably done in an API-compatible way. I'll assume that #19914 is in fact done though while working on #19632's API.

**Comment by ktoso** [comment]
Thanks for reporting, did not yet confirm but if that's what happens I think you're right

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
