### ISSUE TITLE
function to quickly reach the most specific existing ActorRef for a Path

### ISSUE THREAD

**Issue by bblfish** [akka/akka#19919]
### Statement of the problem

I am writing an Http Server where each resource on the file system is the responsibility of an actor. 
To keep it simple, we can say that there are at least two types of actors: one responsible for directories and one responsible for files. Directory actors will be actors with children and files will be actors without. Each directory contains actors named after the file it contains, and mapping in an obvious way to the servers URL space.

Now clearly we don't really want to load all actors for the whole file system in one go, as it could be huge, and would make starting servers very slow. So I'd like to have actors appear as they are requested. 

This architecture requires every actor from the root directory on up to be able to receive `HttpRequest` messages and pass them on to child actors - which may be started up at that point - if the container is not the destination of the message. (see [very initial functioning code](https://github.com/co-operating-systems/SoLiD/blob/be7b8326d42c723289321552d413489f8ba4f05a/src/main/scala/co/os/App.scala))

But as this grows we want to avoid the root actor and every intermediary having to receive all the messages, as that would be a bottleneck, actors being able only to treat one message at a time. We'd like as far as possible to be able to send the message directly to the existing actor, or as close to that actor as possible.

### Hand Rolled Solution

One way to deal with this without changing akka would be to have on each JVM a data structure that
is globally available to all actors and that contains as best possible a set of paths of actors that are up at that point (perhaps even a map to actor refs). It may only need to keep this up to a certain depth (3 or 4 directories deep) for servers where load is quite well balanced across all resources. This would just require one actor to keep that data structure up to date.

### Akka based solution

But a lot of that information is actually allready available to akka.  Perhaps that could be used to create a function on a context that would work a bit like `context.actorFor(path)` used to work, but that would perhaps be called `actorReach` that would find either the actor or its most specific existing manager on the local system. Then one could send that actor the `HttpRequest` and it could either create the actor for the existing file or directory and then send it the message, or create the resource and the actor (in case of a `PUT`), or forward the message to a remote actor if it is remote link.

One can think of applications built this way as following the philosophy that managers should always be able to at least cope with messages their workers can cope with, even if it is to pass those messages on to them (after creation). This way managers can in case of worker failure or on startup manage messages destined to their workers.

**Comment by bblfish** [comment]
Is this something one should use [Custom Routers](http://doc.akka.io/docs/akka/snapshot/scala/routing.html#Custom_Router) with a [Pool](http://doc.akka.io/docs/akka/snapshot/scala/routing.html#Pool) or a [Group](http://doc.akka.io/docs/akka/snapshot/scala/routing.html#Group]

**Comment by patriknw** [comment]
We will not add such traversal into Akka itself. I suggest that you create an [Akka Extension](http://doc.akka.io/docs/akka/2.4.3/scala/extending-akka.html) and keep the mapping there. Each actor can register when it's started. It can handle the smart lookup logic. Everything must be thread safe, though.
