### ISSUE TITLE
Make it easier to send a Multipart.FormData request

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19916]
@sirthias @jrudolph did I miss some API or that's the current way to put it?

```scala
val formData = Multipart.FormData(BodyPart("lol", HttpEntity(MediaTypes.`application/pdf`, new File("example.txt"))))
  val requestEntity = Await.result(Marshal(formData).to[RequestEntity], 1.second)
  val req = HttpRequest(HttpMethods.POST, uri = "http://example.com", entity = requestEntity)
  Http().singleRequest(req)
```

**Comment by sirthias** [comment]
The `RequestBuilding` trait/object makes things easier here.
It's used in most of the higher level tests, for example in the FileUploadDirectivesSpec.

With it you can do sth like:

```scala
import akka.http.scaladscl.client.RequestBuilding._

val formData = Multipart.FormData(BodyPart("lol", HttpEntity(MediaTypes.`application/pdf`, new File("example.txt"))))
Http().singleRequest(Post("http://example.com", formData))
```

**Comment by ktoso** [comment]
I see hm... On the other hand, we're somewhat reluctant to tell people to use the `RequestBuilding` trait, as we may be heading towards a real client hm... 

Thanks a lot for the hint, will figure out what to do about it.
For starters if "nothing", then we should document this perhaps instead.

**Comment by jrudolph** [comment]
There's [`Multipart.toEntity`](https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala#L59) which creates an entity immediately, so the original example becomes:

```scala
val formData = Multipart.FormData(BodyPart("lol", HttpEntity(MediaTypes.`application/pdf`, new File("example.txt"))))
val req = HttpRequest(HttpMethods.POST, uri = "http://example.com", entity = formData.toEntity())
Http().singleRequest(req)
```

**Comment by jrudolph** [comment]
Previous ticket: #17664

**Comment by ktoso** [comment]
Marked as pick next, will want to fix it sooner.

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
