### ISSUE TITLE
Error in fixed-pool-size example

### ISSUE THREAD

**Issue by RayRoestenburg** [akka/akka#19926]
fixed-pool-size does not configure the size of the pool, but is used to switch a fixed pool size on or off: http://doc.akka.io/docs/akka/snapshot/scala/dispatchers.html#More_dispatcher_configuration_examples

From reference.conf:

        # Define a fixed thread pool size with this property. The corePoolSize
        # and the maximumPoolSize of the ThreadPoolExecutor will be set to this
        # value, if it is defined. Then the other pool-size properties will not
        # be used.
        fixed-pool-size = off

**Comment by ktoso** [comment]
It does, see more details in https://github.com/akka/akka/pull/19927

**Comment by ktoso** [comment]
Thanks for reporting in any case, could we improve wording somehow?
