### ISSUE TITLE
NameReceptacle[T].as[B] should take Unmarshaller[T, B] instead of FromStringUnmarshaller

### ISSUE THREAD

**Issue by kubukoz** [akka/akka#19929]
Even though `as[B]` can be chained, if you use 
```scala
"id".as[Int].as(...)
```
you still need a `FromStringUnmarshaller`, which, IMO, in this case should be an `Unmarshaller[Int, B]`.

**Comment by ktoso** [comment]
This piece of code would need `String => Int` and `Int => B`,
what does not work here?

Can you prep a reproducer?

**Comment by kubukoz** [comment]
Hmm... maybe it changed since I submitted. I'll see soon-ish

**Comment by kubukoz** [comment]
```scala
case class UserId(id: Int)

case object UserIdUnmarshaller extends Unmarshaller[Int, UserId]

val routes = {
  logRequestResult("akka-http-microservice") {
    get {
      parameters("id".as[Int].as(UserIdUnmarshaller)) { id: UserId =>
//                               ^^^^^^^^^^^^^^^^^^
        complete(id.toString)
      }
    }
  }
}
```
The higlighted part gives me this:

```scala
Error:(91, 31) overloaded method value as with alternatives:
  [B](unmarshaller: akka.http.scaladsl.unmarshalling.FromStringUnmarshaller[B])akka.http.scaladsl.common.NameUnmarshallerReceptacle[B] <and>
  [B]=> akka.http.scaladsl.common.NameReceptacle[B]
 cannot be applied to (Service.this.UserIdUnmarshaller.type)
      parameters("id".as[Int].as(UserIdUnmarshaller)) { id: UserId =>
                              ^
```

Which means the second `as` expected a `FSU` and got, well, you know what :)

**Comment by ktoso** [comment]
This should be fixable, the first as must return a new type, and there has to be a different `as` on that one to allow the chaining :)

We won't be able to focus on that part of the APIs right now, so if you would be able to contribute that'd be awesome. I'm available to help / guide / review, just let me know :)

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by jrudolph** [comment]
This was actually fixed in https://github.com/akka/akka/pull/20667.
