### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by matthewadams** [akka/akka#19922]
The 5th code example beginning at http://doc.akka.io/docs/akka/2.4.2/scala/stream/stream-graphs.html#Bidirectional_Flows uses symbol `codec` which is undefined.  The closest thing is in the 2nd code example after http://doc.akka.io/docs/akka/2.4.2/scala/stream/stream-graphs.html#Bidirectional_Flows at line 13 called `codecVerbose`, which is what I *think* you meant, but I'm not sure.

**Comment by ktoso** [comment]
Hmm... isn't codec well defined in the docs as 

```

// this is the same as the above
val codec = BidiFlow.fromFunctions(toBytes _, fromBytes _)
```

?

**Comment by matthewadams** [comment]
Yes, it is.  I must've blown by that after ingesting `codecVerbose`.
