### ISSUE TITLE
Consider adding mapError

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19928]
similar to `recover { x => throw }` however will not automatically log the error (like throwing in a stage does)

**Comment by patriknw** [comment]
still relevant?
akka-stream-contrib?

**Comment by ktoso** [comment]
I'd want to revisit the logging behaviours, so it's a keeper though could be solved with nothing perhaps.

**Comment by patriknw** [comment]
ok

**Comment by ilucker** [comment]
Implemented in #22001

**Comment by ktoso** [comment]
Yay, excellent. Closing as duplicate
