### ISSUE TITLE
Make materialized value computation faster

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19932]
Back then, we used to simply prune subtrees in the materialized value computation tree when a Keep.left or a Keep.right was encountered. Unfortunately, this pruned `mapMaterialized` calls which produced a side effect which is not desirable. However, we can still "compress" the tree heavily by observing the following:
 - leaves of the tree are materialized values. There are no side-effects possible in these leaves during the evaluation of the final materialized value since any side-effecting was already done by the stage itself (if any) when it created the materialized value. This means that any path in the tree that leads to a leaf without containing a transformation apart Keep.left or Keep.right can be pruned without losing side-effects (since there is none in that subtree)
 - traversal of Keep.left and Keep.right along a path from an internal node which path contains some potentially side-effecting computation can be "jumped" over, directly jumping to the actual computation without traversing the Keep.left/right chains directly. After the transformation in the path, this same procedure can be applied on the subtree rooted at the potentially side effecting computation.

As a result, the final tree will be compressed heavily, containing nodes that are either
 - leaves
 - user defined (potentially side effecting computations) transformations
 - Keep.X nodes which has *at least one* side-effecting child

**Comment by drewhk** [comment]
I think I have the correct rule, and it can be implemented at graph construction time:
 - whenever a subtree is mapped, apply the mapper node
 - whenever two subtrees are combined with an arbitrary function, apply the node as usual, having the two combined computation as subtrees
 - whenever a Keep.left/right is introduced, and one of the children is Atomic, then either just return the non-atomic subtree (if that is the side kept), or add a mapper node mapping to NotUsed

**Comment by rkuhn** [comment]
This was done in #20016 (sorry, had forgotten about this ticket).
