### ISSUE TITLE
Consider adding a method to allow anonymous unmarshallers in Receptacles

### ISSUE THREAD

**Issue by kubukoz** [akka/akka#19930]
Enable calls like
```scala
case class UserId(i: Int)

"id".as[Int].as(i => UserId(i))
```

**Comment by ktoso** [comment]
Nice one to contribute, would you be up to it? @kubukoz ?

**Comment by kubukoz** [comment]
Seems like something I can do :)

**Comment by kubukoz** [comment]
Depends on #19929 - right now it would only be acceptable if `i` was a `String`

**Comment by kubukoz** [comment]
I'd wait for #20667 to merge before this - I'll gladly do it, then

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
