### ISSUE TITLE
Illegal request, responding with status '505 HTTP Version Not Supported': The server does not support the HTTP protocol version used in the request.

### ISSUE THREAD

**Issue by coder-han** [akka/akka#19937]
http server error mesaage:`Illegal request, responding with status '505 HTTP Version Not Supported': The server does not support the HTTP protocol version used in the request.`

**How compatible http1.0**
**akka-http version:2.4.2**

**Comment by coder-han** [comment]
@timcharper

**Comment by coder-han** [comment]
Plase Help Me !!!!!

**Comment by coder-han** [comment]
check url.

**Comment by ktoso** [comment]
Please show the request which caused this.
We implement HTTP 1.0 or 1.1, if your request is malformed this error is reported, as expected:

```scala
c(7) match {
        case '0' ⇒ `HTTP/1.0`
        case '1' ⇒ `HTTP/1.1`
        case _   ⇒ badProtocol
      }

```

**Comment by coder-han** [comment]
@ktoso 
Thanks. Because there is a /n
