### ISSUE TITLE
Give specific names to inlets/outlets of built in stages

### ISSUE THREAD

**Issue by 2m** [akka/akka#19933]
so errors featuring the names are not confused with the user code.

**Comment by rkuhn** [comment]
One thing here is to note that port names cannot practically be altered later-on when graphs are built up, unless we make it so (i.e. requires some changes, in particular also to Fusing—otherwise it will quite likely undo the renaming).

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
