### ISSUE TITLE
Document existence and handling of idle-timeout in WebSocket

### ISSUE THREAD

**Issue by roldugin** [akka/akka#19945]
After upgrading to `Akka Streams 2.0.3` from `1.0` I see that the WebSocket connection times out after 1.1 minutes of inactivity.

I was able to reproduce it with with the example program from the docs:
https://github.com/akka/akka/blob/akka-stream-and-http-experimental-2.0.3/akka-docs-dev/rst/scala/code/docs/http/scaladsl/server/WebsocketExampleSpec.scala

For the above program a workaround is to add the following step to `greeterWebsocketService`:
```scala
.keepAlive(30.seconds, () => TextMessage("keepalive"))
```

**Comment by ktoso** [comment]
Hi there, and while it may sound a bit weird: It's a feature, not a bug – really.
This is configured by the `akka.http.server.idle-timeout` setting, and does as expected: if nothing happens on a connection got over a minute, the connection should be torn down – this is to prevent a gazillion clients from connecting and not ever doing anything, thus using up your resources and killing the server eventually.

Configure the idle-timeout to suit your needs (read the docs around it please) or inject a keepAlive indeed – those are the exact two solutions we recomment

**Comment by roldugin** [comment]
Thanks for the quick reply!

Perhaps it could be put in the WebSocket Support docs or the migration guide?

http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.3/scala/http/routing-dsl/websocket-support.html

http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.3/scala/migration-guide-1.0-2.x-scala.html

**Comment by ktoso** [comment]
Good idea, would you like to help us out and contribute a note on that?

**Comment by ktoso** [comment]
Note here: we now have a timeouts section in the docs, add there

**Comment by roldugin** [comment]
Will do

**Comment by ktoso** [comment]
Awesome, thanks!

**Comment by ktoso** [comment]
Ping @roldugin, are you still interested in contributing this? 
Slipping until next release for now.
