### ISSUE TITLE
java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by pchordia15** [akka/akka#19946]
Getting this issue while running test cases, I am getting below exception. java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace. How to set metaspace size for SBT?

**Comment by johanandren** [comment]
Up until Java 7 the Metaspace was Permgen which was specified separately from the heap, but in Java 8 it is just a part of the heap, so to increase it you just have to increase the heap which can be done using the `-mem 2000` parameter to SBT, where 2000 is megabytes, or by setting the `SBT_OPTS` environment variable (which then is direct JVM flags, should look something like `-Xmx2G`)

As this is not really an Akka question I'm closing it
