### ISSUE TITLE
slow first message to shardRegion

### ISSUE THREAD

**Issue by kpbochenek** [akka/akka#19955]
1) ActorSystem is created
2) ClusterSharding(system).start(...) is called
3) sleep doesn't change anything in this step
4) message to shardRegion is sent, log with DEBUG:
[DEBUG] [03/07/2016 00:30:06.715] [CarFactory-akka.actor.default-dispatcher-26] [akka.tcp://CarFactory@127.0.0.1:2557/system/sharding/carproducer] Request shard [3] home
[WARN] [03/07/2016 00:30:14.769] [CarFactory-akka.actor.default-dispatcher-20] [akka.tcp://CarFactory@127.0.0.1:2557/system/sharding/carproducer] Trying to register to coordinator at [Some(ActorSelection[Anchor(akka://CarFactory/), Path(/system/sharding/carproducerCoordinator/singleton/coordinator)])], but no acknowledgement. Total [1] buffered messages.
[WARN] [03/07/2016 00:30:16.766] [CarFactory-akka.actor.default-dispatcher-20] [akka.tcp://CarFactory@127.0.0.1:2557/system/sharding/carproducer] Trying to register to coordinator at [Some(ActorSelection[Anchor(akka://CarFactory/), Path(/system/sharding/carproducerCoordinator/singleton/coordinator)])], but no acknowledgement. Total [1] buffered messages.
[WARN] [03/07/2016 00:30:18.766] [CarFactory-akka.actor.default-dispatcher-31] [akka.tcp://CarFactory@127.0.0.1:2557/system/sharding/carproducer] Trying to register to coordinator at [Some(ActorSelection[Anchor(akka://CarFactory/), Path(/system/sharding/carproducerCoordinator/singleton/coordinator)])], but no acknowledgement. Total [1] buffered messages.
[DEBUG] [03/07/2016 00:30:20.288] [CarFactory-cassandra-snapshot-store.default-dispatcher-43] [akka.tcp://CarFactory@127.0.0.1:2557/system/cassandra-snapshot-store] initialized CassandraSession successfully
[DEBUG] [03/07/2016 00:30:20.322] [CarFactory-cassandra-journal.default-dispatcher-45] [CassandraReadJournal] initialized CassandraSession successfully
[DEBUG] [03/07/2016 00:30:20.413] [CarFactory-cassandra-query-journal.default-dispatcher-64] [akka.actor.LocalActorRefProvider(akka://CarFactory)] resolve of path sequence [/system/sharding/gpsproducer#2122998903] failed

Should it take ~16 seconds for first message to reach actor in ActorRegion?
What happens in that period of time? Can I somehow speed this up?
Sleep also doesn't help, I assume this must be happening lazily, can I enforce somehow initialization?

**Comment by ktoso** [comment]
The answer is most likely in your logs already – `[DEBUG] [03/07/2016 00:30:20.322] [CarFactory-cassandra-journal.default-dispatcher-45] [CassandraReadJournal] initialized CassandraSession successfully`

Journal initialization is lazy, first making connections may take more time, understandably.

Try to initialize the journal plugin eagerly, which is documented in the last paragraph of http://doc.akka.io/docs/akka/snapshot/scala/persistence.html#Storage_plugins

**Comment by kpbochenek** [comment]
Thanks for a tip, worked like a charm :)

But for peace of mind I checked on simple project cassandra driver initialization and it takes ~500ms.
When I add  `PersistencePluginProxy.start(system)` and create shard region and start sending messages first one gets delivered quickly (2 sec delay? pretty understandable)

But when I don't use eager initialization and create shard region and then start sending messages a first one is delivered after ~15 sec. And I can see these warning during these 15 sec.
``` [WARN] [03/07/2016 20:54:11.301] [CarFactory-akka.actor.default-dispatcher-2] [akka.tcp://CarFactory@127.0.0.1:2557/system/sharding/CarProducer] Trying to register to coordinator at [Some(ActorSelection[Anchor(akka://CarFactory/), Path(/system/sharding/CarProducerCoordinator/singleton/coordinator)])], but no acknowledgement. Total [1] buffered messages.
```

I am happy with eager initialization so this can be closed but I also think something is not right with lazy initialization.

**Comment by ktoso** [comment]
Sounds like this last paragraph would be better as separate section – would you like to contribute such small update to the docs before we close here? That'd be awesome :)

**Comment by kpbochenek** [comment]
Sure I can move it to separate section I will create PR.
I though you would be more interested finding out why there is this long initialization when cassandra is not eager initialized but I guess there are other things to do :)

**Comment by ktoso** [comment]
Docs are important – you didn't notice the feature, fixing the docs should follow: one step at a time. ;)

**Comment by ktoso** [comment]
And the slow init should be reported and discussed in the plugin's repository I think.

**Comment by patriknw** [comment]
I agree that it would be interesting to investigate where that time is spent. I don't see an obvious explanation. It would be cool if you can investigate it by adding more debug logging in the startup, recovery of the `ShardCoordinator`.
