### ISSUE TITLE
HttpBenchmark needs rework as performance range is too wide

### ISSUE THREAD

**Issue by agolubev** [akka/akka#19951]
currently it shows increase performance for each iteration.
```
[info] # Run progress: 50.00% complete, ETA 00:00:17
[info] # Fork: 1 of 1
[info] # Warmup Iteration   1: 60.567 ops/s
[info] # Warmup Iteration   2: 260.883 ops/s
[info] # Warmup Iteration   3: 345.503 ops/s
[info] # Warmup Iteration   4: 465.680 ops/s
[info] Iteration   1: 567.226 ops/s
[info] Iteration   2: 644.375 ops/s
[info] Iteration   3: 788.081 ops/s
[info] Iteration   4: 935.435 ops/s
[info] Iteration   5: 945.579 ops/s
[info] Iteration   6: 1059.876 ops/s
[info] Iteration   7: 1333.566 ops/s
[info] Iteration   8: 1559.816 ops/s
[info] Iteration   9: 1458.277 ops/s
[info] Iteration  10: 1467.240 ops/s
[info] 
[info] 
[info] Result "single_request_pool":
[info]   1075.947 ±(99.9%) 543.872 ops/s [Average]
[info]   (min, avg, max) = (567.226, 1075.947, 1559.816), stdev = 359.738
[info]   CI (99.9%): [532.075, 1619.819] (assumes normal distribution)
```

**Comment by pjazdzewski1990** [comment]
Hi @agolubev 
Do you plan to work on this ticket? If not, I would be glad to tackle this issue. Could you explain with more detail what you dislike about the current `HttpBenchmark` and what should be "reworked"? 
If I understood correctly, you are concerned about the quality of the benchmark, because of the results you are seeing. Is this correct?

**Comment by agolubev** [comment]
@pjazdzewski1990 I believe it's two options here: 
* there is some state created during each iteration which is not released, so that's why the first iteration is 60 ops/s and the last one 64 times longer
* also maybe it's some problem inside http code itself but it's very low probability.
I'll try to look in code closer further today, maybe will be able to spot the problem

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
