### ISSUE TITLE
No response produced after number of requests reach max-connections value

### ISSUE THREAD

**Issue by kstokoz** [akka/akka#19953]
I observe some issue with managing http connection pool in akka-http v2.4.2, 
I`m executing requests one after another in sequence, initial requests succeed and produce response until number of requests reach max-connections configuration value afterwards all requests timeout.

Some other info: https://groups.google.com/forum/#!topic/akka-user/Dw1MgZ6vgzI  

Below you can find a reproducer for this strange behavior:

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.HttpRequest
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.Route
import akka.stream.{ActorMaterializer, ActorMaterializerSettings}
import com.typesafe.config.ConfigFactory
import org.apache.commons.io.IOUtils
import org.apache.http.client.methods.HttpGet
import org.apache.http.impl.client.HttpClientBuilder

object AppConfig {
  val actorSystemConfig = ConfigFactory.parseString(
    """
      akka {
        loglevel = DEBUG
        loggers = ["akka.event.slf4j.Slf4jLogger"]
        actor {
          default-dispatcher {
            executor = "fork-join-executor"
            fork-join-executor {
              parallelism-min = 8
              parallelism-factor = 2.0
              parallelism-max = 8
            }
          }
        }
        http {
          server.parsing.max-content-length = 2048m
          client.parsing.max-content-length = 2048m

          host-connection-pool {
           max-connections = 2
           max-retries = 5
           max-open-requests = 2048
         }
       }
    }
    """
  )
}

object ReproducerApp extends App {

  implicit val system = ActorSystem("actor-system", AppConfig.actorSystemConfig)
  implicit val materializer = ActorMaterializer(ActorMaterializerSettings.create(system).withDebugLogging(true))(system)

  val route: Route = {
    (path("test") & get) {
      val response = Http().singleRequest(HttpRequest().withUri("https://gist.github.com/rklaehn/d4d3ee43443b0f4741fb"))
      complete(response)
    }
  }

  val bindingFuture = Http().bindAndHandle(route, "localhost", 12345)

  System.in.read()
  system.shutdown()
  system.awaitTermination()
}

object ReproducerClientApp extends App {

  val url = "http://localhost:12345/test"
  val client = HttpClientBuilder.create().build()

  (1 to 5).foreach { i =>
    val get = new HttpGet(url)
    val response = client.execute(get)
    println(IOUtils.toString(response.getEntity.getContent()))
  }
}
```

As a result i`m getting:
``` 
response 2 times
...
The server was not able to produce a timely response to your request.
Please try again in a short while!
The server was not able to produce a timely response to your request.
Please try again in a short while!
The server was not able to produce a timely response to your request.
Please try again in a short while!
```

**Comment by kstokoz** [comment]
I would think that this is quite severe bug in akka, i would appreciate any feedback. @patriknw @ktoso maybe you can comment on this issue? Thanks in advance.

**Comment by Falmarri** [comment]
I've been playing with your repro case, and it's reproducible, but only using the Apache client. If you run it via curl `for i in `seq 1 10`; do curl "http://localhost:12345/test"; done` It works fine. Although I do see `Error in stage [One2OneBidi]: Inner stream finished before inputs completed. Outputs might have been truncated.` in the logs.

Taking a look at the other ticket, https://github.com/akka/akka/issues/19996, it seems like this might be an issue with interaction between apache's PoolingHttpClientConnectionManager and akka

**Comment by TrustNoOne** [comment]
Have you tried enabling debug logging?

I get this after a while
[DEBUG] [03/10/2016 23:43:36.674] [default-akka.actor.default-dispatcher-10] [akka://default/system/IO-TCP/selectors/$a/0] Unbinding endpoint /127.0.0.1:1234
[DEBUG] [03/10/2016 23:43:36.677] [default-akka.actor.default-dispatcher-10] [akka://default/system/IO-TCP/selectors/$a/0] Unbound endpoint /127.0.0.1:1234, stopping listener

**Comment by TrustNoOne** [comment]
I found out about the bug in my load tests using gatling.

Have you tried enabling debug logging?

I get this after a while
[DEBUG] [03/10/2016 23:43:36.674] [default-akka.actor.default-dispatcher-10] [akka://default/system/IO-TCP/selectors/$a/0] Unbinding endpoint /127.0.0.1:1234
[DEBUG] [03/10/2016 23:43:36.677] [default-akka.actor.default-dispatcher-10] [akka://default/system/IO-TCP/selectors/$a/0] Unbound endpoint /127.0.0.1:1234, stopping listener

**Comment by Falmarri** [comment]
I've tracked this down a little further. So here's some more details. The problem is that the request slots in `akka.http.impl.engine.client.PoolConductor.SlotSelector` are not being completed. Here's a screenshot of my IDE with `max-connections = 10` and this is the 11th request.
![image](https://cloud.githubusercontent.com/assets/463948/13690487/124cbd40-e6ee-11e5-8d9b-a6b02f419885.png)

It seems like it's filling up the slots, then backpressuring. But there's something going on where the SlotSelector isn't being notified of open slots.

**Comment by kstokoz** [comment]
@Falmarri when i was investigating i can see similar behavior that something is wrong with releasing slots, so gatewayFuture in Http object is never complete and just times out.

I tried to enable debug logging in akka and even recompile it with debug flag in GraphInterpreter enabled to see Pull/Push stages but it does not give any hints into where the problem is.

**Comment by kstokoz** [comment]
@TrustNoOne I think #19996 you`ve submitted and my issue have same root cause as it seems that akka under the hood uses same code to handle incomming and outgoing http requests

**Comment by leachbj** [comment]
Looking at this same problem, although the singleReponse() value is returned the connection is never returned to the PoolConductor as the trigger for the request complete never triggers.  To fix the problem I manually read the original response body and then passed that to the complete().

E.g. change your route code to;

```
      val response = Http().singleRequest(HttpRequest().withUri("https://gist.github.com/rklaehn/d4d3ee43443b0f4741fb")).flatMap { r =>
        Unmarshal(r).to[String].map { body =>
          r.withEntity(HttpEntity.Strict(r.entity.contentType, ByteString(body)))
        }
      }
      complete(response)
```

**Comment by curreli** [comment]
@ktoso @leachbj @kstokoz  FYI - this is still happening on latest akka `v2.4.10` when flooding the server with lots of connections (> `server.max-connexion`).

```
[2016-09-22 14:26:55.790] ERROR [efault-dispatcher-15] akka.actor.RepointableActorRef - Error in stage [One2OneBidi]: Inner stream finished before inputs completed. Outputs might have been truncated.
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$: Inner stream finished before inputs completed. Outputs might have been truncated.
```

Following requests yield `503 Service Unavailable`:
```
The server was not able to produce a timely response to your request.
Please try again in a short while!
```

Can this issue be re-opened? Should I create a new one?

**Comment by kstokoz** [comment]
I haven`t seen any issue so far. I bet you are not releasing streams properly. 
Check this out http://doc.akka.io/docs/akka/2.4.10/scala/http/implications-of-streaming-http-entity.html

**Comment by curreli** [comment]
Hmm, looks like every route is unmarshalling the request entity to an object type...

What about rejecting the request? Do we need to discard the entity bytes when we call `reject` in a custom directive? Because that could explain it, otherwise I do not understand where this may come from and should probably try to come up with a minimal example.

**Comment by scullxbones** [comment]
@curreli - a backstop i'm using on the server side is wrapping my routes in `toStrictEntity` to disable entity streaming/backpressure.  This has worked well so far in load testing for me, and I saw a similar (lock-up) problem in akka-http `2.4.2` before adding `toStrictEntity`.

Of course, I can only get away with this because I know I have enough RAM to hold the entities in heap and have no "file upload"-style use cases to support.  I'm looking forward to the `auto` [solution](http://doc.akka.io/docs/akka/2.4.10/scala/http/implications-of-streaming-http-entity.html#Pending__Automatic_discarding_of_not_used_entities).

It's also not clear to me whether rejections discard the entity.  Logically they *should*, but I haven't dug deep enough into the source to be sure.  If that's in the docs I've missed it.

**Comment by curreli** [comment]
My bad, I discovered an infinite loop in my code thanks to `jstack`. Fixing it resolved the problem. Sorry about it and thanks for your replies!
