### ISSUE TITLE
[akka-http] complete(NO_CONTENT) should not care about Accept header

### ISSUE THREAD

**Issue by jypma** [akka/akka#19969]
This might be a more generic problem, but the following use case is clearly wrong:

When completing a route using `complete(StatusCodes.NO_CONTENT)`, an implicit empty string is taken as response body, and an implicit marshaller to render that string as `text/plain`. This means that if the request contained an `Accept: application/json` header, the request will actually fail. 

It shouldn't however, since the response _has_ no content and shouldn't even get a `Content-Type` header.

**Comment by johanandren** [comment]
@ktoso any opinions/ideas about this?

**Comment by ktoso** [comment]
Hmm, I think I know the mechanism behind that, it's the "empty value provider" thingy most likely.
Yes, we should investigate, the given example is a good test case.

// cc @jrudolph @sirthias

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
