### ISSUE TITLE
Consider to allow users to specify list of classes that won't log Java serialization warnings

### ISSUE THREAD

**Issue by wlk** [akka/akka#19963]
This is followup after https://github.com/akka/akka/issues/19789 
We can add setting, for example `akka.actor.silence-serialization-warnings-for-classes` that will accept a list of class names for which we won't log Java serialization warnings.

Please let me know if this is OK todo and I'll create a PR (I have code almost ready for that)

Maybe this could replace `akka.actor.warn-about-java-serializer-usage = on` but that depends on what is the most common use case, just a thought (without really knowing a lot about most common use cases and pitfalls)

**Comment by patriknw** [comment]
An alternative is to skip the warning for messages marked with the existing `NoSerializationVerificationNeeded`. wdyt?

**Comment by ktoso** [comment]
Hm, also good idea. 

Question is if disable warnings isn't used for "someone else messed up and I don't want warnings", then the configuration would make more sense. I did not see any comments about silencing scenarios on akka-user though so it's hard to say.

**Comment by ktoso** [comment]
> Maybe this could replace akka.actor.warn-about-java-serializer-usage = on but that depends on what is the most common use case, just a thought (without really knowing a lot about most common use cases and pitfalls)

I don't think this ticket is about replacing the `java.lang.*` case, that one should be optimised with a fast path (the `&& !...startsWith("java.lang.")` that you contributed)

**Comment by patriknw** [comment]
@wlk are you interested in contributing here? I think the `NoSerializationVerificationNeeded` alternative is easier and good enough

**Comment by richard-imaoka** [comment]
Hi sorry to jump in, but is it ok for me pick this up, or does @wlk work on this? (Assuming we'd go with the `NoSerializationVerificationNeeded` way, suggested by @patriknw)

**Comment by ktoso** [comment]
Have not heard back from @wlk so contributions would be very welcome, thanks in advance!
