### ISSUE TITLE
feature parity of creating MediaTypes for JavaDSL

### ISSUE THREAD

**Issue by pawel-kaminski-krk** [akka/akka#19976]
I am using java dsl for akka-http. the original question is here https://groups.google.com/forum/?hl=en-GB#!topic/akka-user/19GPYsUzpSk but I try to summarize it :

I cannot use RawHeader for headers like contentType, contentLength when constructing httpResponse are ignored (as pointed in documentation). 

setting content-type using HttpEntity#create is just pain in java. It is super easy for common types like application/json but for a custom one to convert my, string mime back to ContentType I need to decide whether it is binary or not. 

I tried ```ContentTypes.create(MediaTypes.custom()) ``` but it creates MediaType rather than Binary, WithFixedCharset instances and there is no way to get ContentType from such custom MediaType. 

then I tried 

    ContentType.WithFixedCharset contentType = ContentTypes.create(
        **akka.http.scaladsl.model.**MediaType.applicationWithFixedCharset(
            "my-own", 
            HttpCharsets.UTF$minus8(), 
            ?)); // <---- I dont know event how to create empty Seq in java

but it suddenly is a scaladsl and I need to pass some scala charsets / scala collection ... and there is no equivalent in javadsl.

Why ContentTypes.create isn't just consume string??? maybe rawHeader??

I dont understand the hierarchy of the ContentType, the benefit of having Binary, applicationWithFixedCharset, applicationWithOpenCharset, and so on. this is not explained nowhere in docs.

**Comment by ktoso** [comment]
Thanks for reporting, we'll need to add the more specific factories to javadsl. Will revisit the rest of the ticket then as well.

**Comment by pawel-kaminski-krk** [comment]
If I can add one more thing, I found it quite hard to work with constant values as they are not attached directly do ContentType but to ContentTypes. even though there is a pattern other frameworks usually uses static public fields or methods directly on a type that should be passed to method.

**Comment by lolski** [comment]
Can I have a go on this issue?

**Comment by ktoso** [comment]
That would be great if you could pick this one up @lolski.
What has to be done here is to add methods to `javadsl.MediaTypes` that correspond to the scaladsl ones, such as:

```
object MediaType {

  def applicationBinary(subType: String, comp: Compressibility, fileExtensions: String*): Binary =
```

etc. There's quite a few of them, but porting should be rather simple, thanks in advance @lolski!

**Comment by ktoso** [comment]
I'll mark as in progress to note @lolski is working on it

**Comment by lolski** [comment]
My remark:

1. `ContentType` javadsl has way less functionality than the scaladsl counterpart, so they need to be added
2. We don't have `MediaType.Compressibility` javadsl, which is needed as well

**Comment by ktoso** [comment]
Yeah, would you mind addressing those in your PR too?

**Comment by lolski** [comment]
Yes, was just making sure I didn't miss anything obvious.

**Comment by pawel-kaminski-krk** [comment]
could you consider adding method to parse string and get ContentType out of it. OR update documentation explaining what are trade-offs of using each ContentType (Binary/WithFixedCharacter, etc) - is this only convenient for developer or akka-http is heavily depending on it, so you gonna break processing by passing wrong content-type object.

**Comment by ktoso** [comment]
Keeping open as reminder to self that I need to adjust one thing in there (javadsl for Compressibility)

**Comment by pawel-kaminski-krk** [comment]
cool. I guess it is in some release candidate so I can import it and see if changes are ok??

**Comment by ktoso** [comment]
We don't do RC for minors, it's just a minor update scheduled for tomorrow - not long to wait for it.

**Comment by pawel-kaminski-krk** [comment]
can you update me in this conversation about next version?

**Comment by ktoso** [comment]
Just update tomorrow... For a personal hot-line you can get support ;-)

Releases are announced on http://akka.io/news/ and twitter. 
You can IFFT news from there to emails if you like push notifications etc
