### ISSUE TITLE
ActorGraphInterpreter leaks Subscribers when encountering RS spec violation

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19978]
We need to rethink the way we use SpecViolation exceptions:

* imagine an ActorGraphInterpreter with multiple Subscribers, all running
* imagine one of them throwing an exception in onNext
* now tryOnNext will wrap this in SignalThrewException before re-throwing
* failStage will pass this exception to the other outputs, where it results in IllegalStateException
* other (non-violating) Subscribers will therefore not be informed of the violent stream termination

**Comment by drewhk** [comment]
> failStage will pass this exception to the other outputs, where it results in IllegalStateException

Does it? I am not sure that this is true. Why would it throw an ISE? Anyway, I can try out.

**Comment by drewhk** [comment]
Ok, I guess interpreterShell.receive might need a try-catch

**Comment by drewhk** [comment]
Ok, so now we catch the SpecViolation at the ActorGraphInterpreter level, then re-wrap in an ISE and abort all stages, resulting in an orderly shutdown of innocent Publishers and Subscribers.
