### ISSUE TITLE
add Source.fromStream

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19977]
For java 8.

eg. I am using jooq,which return a query result as a `Stream`
```java
    public final Stream<R> fetchStream() {
        return getDelegate().fetchStream();
    }

```

**Comment by ktoso** [comment]
There's a few libs using the name "Stream", do you mean `java.util.Stream`?

**Comment by ktoso** [comment]
For Java Streams we had it in progress already: https://github.com/akka/akka/pull/19456

**Comment by ktoso** [comment]
Closing as duplicate of #19443 (see above PR for almost done impl)

**Comment by hepin1989** [comment]
@ktoso yes.
then please mark this as duplicated:)
