### ISSUE TITLE
Provide issue/pr github template

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19975]
We can include a bunch of "did you check X" etc in these templates, see here: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by patriknw** [comment]
How often do we get issues that are of bad quality? It's a nice idea, but is it a problem?

Lagom has a very [comprehensive template](https://github.com/lagom/lagom/issues/new) and I would probably not fill in all those things.

**Comment by ktoso** [comment]
Yeah, opened up the ticket when the feature was introduced. I don't think we need it that much.

**Comment by ktoso** [comment]
What we did recently on a project I maintain is this:

```
<!--- Please follow the instructions below -->

<!--- Provide a brief summary of the issue in the title above -->

<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->
```


https://github.com/ktoso/maven-git-commit-id-plugin/issues/new

Which then actually does not show up in the issue view (!) We could at least add links to akka-http and alpakka repos there in such way perhaps hm
