### ISSUE TITLE
Subscription timeouts not working

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19980]
These tests need to be added to TimeoutsSpec and the implementation needs to pass them:

``` scala
  "Subscription timeouts" must {

    implicit val materializer = ActorMaterializer(
      ActorMaterializerSettings(system).withSubscriptionTimeoutSettings(
        StreamSubscriptionTimeoutSettings(
          StreamSubscriptionTimeoutTerminationMode.cancel, 100.millis)))

    "be effective for dangling downstream (no fanout)" in Utils.assertAllStagesStopped {
      val upstream = TestPublisher.probe()
      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
      upstream.subscribe(sub)
      upstream.expectCancellation()
    }

    "be effective for dangling downstream (with fanout)" in Utils.assertAllStagesStopped {
      val upstream = TestPublisher.probe()
      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(true))
      upstream.subscribe(sub)
      upstream.expectCancellation()
    }

    "be effective for dangling upstream" in Utils.assertAllStagesStopped {
      val downstream = TestSubscriber.probe[String]()
      val (sub, pub) = Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
      pub.subscribe(downstream)
      downstream.ensureSubscription()
      downstream.expectError() shouldBe a[SubscriptionTimeoutException]
    }

    "be effective for dangling Processors" in Utils.assertAllStagesStopped {
      Flow[Int].map(_.toString).runWith(Source.asSubscriber, Sink.asPublisher(false))
    }

  }
```

**Comment by patriknw** [comment]
@drewhk is this is progress, otherwise unassign?

**Comment by drewhk** [comment]
unassigned

**Comment by drewhk** [comment]
Taking this one.

**Comment by ilganeli** [comment]
I'll take this on

**Comment by ktoso** [comment]
Cool, thanks let us know if you're stuck.

**Comment by ilganeli** [comment]
@ktoso Thanks :) At least there's already test cases!

**Comment by ilganeli** [comment]
Some graph primitives: ```GroupBy```, ```PrefixAndTail```, ```TCP``` explicitly read the timeout settings and and then create the appropriate timer, but apparently not all, e.g. FlattenMerge. The corresponding tests actually demonstrate timeouts working appropriately for those primitives. The ```Flow``` class does no such thing. The solution is likely to figure out where to add this in the ```Flow``` class. 

There also appears to be a class which should be deprecated: ```StreamSubscriptionTimeoutSupport``` which was used only in ```ActorPublisher```, which is already deprecated.

**Comment by ilganeli** [comment]
@ktoso @rkuhn 

Digging through the code, it's unclear as to where the change should be made to add subscriptions. Subscriptions were previously handled by the ActorPublisher which is no longer used and is replaced by the Graph implementation. The ActorPublisher previously defined:
1) A callback handler for a SubscriptionTimeoutExceeded message
2) A timer that sent a SubscriptionTimeoutExceeded message that is run at preStart

The test cases above create stream graphs using the Flow interface, connecting sources and sinks. Nominally, a Sink is a publisher, and would therefore be responsible for handling subscription timeouts. However, in the new API, everything is resolved via the Materializer and executed in the GraphInterpreterShell.  Nothing at the moment has the above two functions so my question is where it would make sense to add this. Should this live in the GraphInterpreterShell or are there more pieces of the puzzle that I'm still missing?

Would love some help or advice on how to proceed, thank you!

**Comment by drewhk** [comment]
Sorry for not chiming in earlier, this is a very tricky issue, and mostly because an identity processor is attached to almost all stages when you expose them as Publishers and hence it simply "removes" the timeout anyway. There is a reason why I haven't already fixed this :(

**Comment by ilganeli** [comment]
@drewhk That makes me feel slightly better - I'd still like to understand if I'm missing something. What is an identity processor and why does it remove the timeout? Where does that happen?
