### ISSUE TITLE
cachedHostConnectionPoolHttps "stops after a while"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19985]
Reported via mailing list: https://groups.google.com/forum/#!searchin/akka-user/cachedHostConnectionPoolHttps/akka-user/R9dnsOa7liA/aafkz6Z6IQAJ

> We're using 2.4.2 version of akka-http-core, akka-stream.
> however, after some time, the graph becomes unresponsive & stops passing messages.
> 
> Attached are entire debug logs for running graph & once it stops running completely.
> Can someone from the akka-stream developer group inspect & help us out. Seems like a bug in cachedHostConnectionPoolHttps.

.

> Here is a UT, which shall be helpful in recreating the error.
> https://gist.github.com/kingster/ff3be13feb7afb54ecc5
> This behavior is specifically seen for Non 2XX response from http-servers

**Comment by ktoso** [comment]
[streamInitiallyWorks.txt](https://github.com/akka/akka/files/165257/streamInitiallyWorks.txt)
[streamStopsWorking.txt](https://github.com/akka/akka/files/165256/streamStopsWorking.txt)

**Comment by kingster** [comment]
Hi

We did figure out something in this context, This was specifically happening if the resultant httpResponse stream is not being read, or being drained. For now if we did

```scala
downstream.expectNext().entity.dataBytes.to(Sink.ignore)
```

It doesn't get stuck as for now.

**Comment by ktoso** [comment]
Hah, yes that's correct. Did not read enough into the code to notice that, just opened a ticket to revisit later.

Yes, entities must be consumed, otherwise back-pressure kicks-in as it should (this is *the* feature).
In this ticket we could investigate about the auto-draining we considered once... Not a bug though.

// cc @patriknw @rkuhn

**Comment by viktorklang** [comment]
I vote for closing this one (it is a know issue?)

**Comment by ktoso** [comment]
Yeah, I agree, since this is not "the bug", and there is another ticket about auto-draining: https://github.com/akka/akka/issues/18716

FYI: We're in the middle of cleaning up tickets right now.
