### ISSUE TITLE
silence debug logging of "resolve of path sequence"

### ISSUE THREAD

**Issue by patriknw** [akka/akka#19991]
deserialization of persistent events containing ActorRef

**Comment by johanandren** [comment]
Silence it completely or hide behind configuration?

**Comment by renatocaval** [comment]
@patriknw / @johanandren, can we clarify what is the desired action here? 

I identified that this issue refers to an old log that existed inside `ActorRefProvider.resolveActorRef`. This is now replaced by this:

https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala#L608-L622

In any case, what do you mean by silencing it? 

If we are deserializing an event containing a reference to an ActorRef it will probably be an invalid one, but how could we silence it only when deserializing events? 

I do find it useful to have the debug logging. At least users will get to understand why that old reference is not working.

**Comment by patriknw** [comment]
Maybe make sure we use a good logger name for these so it can silenced with logback configuration?
