### ISSUE TITLE
Issue with `sample.persistence.PersistentActorExample`

### ISSUE THREAD

**Issue by briantopping** [akka/akka#20005]
Helping someone learn via `sample.persistence.PersistentActorExample`, seems that it is not stable if run as-is. For some reason, there needs to be a `Thread.sleep` after the creation of the `PersistentActor` or the commands are not delivered. 

Not sure if it matters, this was on OS X 10.11.3, 2.5 GHz Intel Core i7.

**Comment by ktoso** [comment]
Thanks for reporting, will have a look!

**Comment by patriknw** [comment]
I can't see anything wrong with the example and it runs fine for me. How do you observe that it is not stable?

**Comment by patriknw** [comment]
By the way, what version of Akka is that? Try to change to 2.4.3 if that is not already the case.

**Comment by briantopping** [comment]
At the time, it seemed to be shutting down the actor system before the mailboxes were processed.

**Comment by patriknw** [comment]
Then I understand what you mean, thanks. I'll fix that.
