### ISSUE TITLE
check for mutable state in GraphStage

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#20009]
… which must of course be moved to the GraphStageLogic

We must also do an audit of all stages to fix remaining issues of this kind—I have spotted many of them during PR review, but I have not reviewed all PRs.

This particular case was found by @viktorklang long after it had been introduced.

**Comment by viktorklang** [comment]
Thanks @rkuhn

**Comment by johanandren** [comment]
But, it is still an open pull request that introduced that bug, why a separate ticket?

**Comment by rkuhn** [comment]
Yep, that is an aspect that I overlooked—will change this ticket to only audit (because I am genuinely afraid of such a thing having slipped through).

**Comment by drewhk** [comment]
AFAIK Throttle has similar problem. I just need to finish my PR though.

**Comment by johanandren** [comment]
Went through 95 impls of `GraphStageWithMaterializedValue`, including tests and docs.

Found suspects: 
* `SubSink`, StreamOfStreams.scala:L391, internal, AtomicReference
* `SubSource`, StreamOfStreams.scala:L476, internal, AtomicReference
* `MaterializedValueSource` GraphStages.scala:L253, internal only, clearly says non-reusable
* `ConnectionSourceStage` TcpStages.scala:44, internal, has AtomicLong
* `IncomingConnectionStage`, TcpStages.scala:292, internal, AtomicBoolean

General sneaky:
* `ActorRefBackpressureSinkStage`,`InputStreamSinkStage`,`OutputStreamSourceStage` calculates an attribute outside of the `GraphStageLogic` (in the inputstream/outputstream cases we did this to fail fast on invalid buffer size attributes)

**Comment by johanandren** [comment]
crap. that was the 2.0.3 sources. starting over on master.

**Comment by johanandren** [comment]
Went through 178 impls of `GraphStageWithMaterializedValue`, including tests and docs:

Bad:
* `limitByteChunksStage` in StreamUtils.scala:L118, internal akka http, `var ByteString` (!!)
* `Idle`, Timers.scala:L79, internal, var (!!)

Probably safe (but _might_ be fishy with multiple materializations):
* `QueueSource`, Sources.scala:23, internal, Promise
* `MaterializedValueSource`, GraphStages.scala:L253, internal only, clearly says non-reusable
* `SubSink`, StreamOfStreams.scala:L410, internal, AtomicReference
* `SubSource`, StreamOfStreams.scala:L495, internal, AtomicReference
* `ConnectionSourceStage`, TcpStages.scala:L44, internal, AtomicLong
* `IncomingConnectionStage`, TcpStages.scala:L295, internal, AtomicBoolean

**Comment by johanandren** [comment]
Marking this as resolved, the two "Bad" has been fixed but the "Probably safe" are, well, probably safe, and internal.

**Comment by rkuhn** [comment]
QueueSource is a bug, the completion promise needs to be per materialization.

ConnectionSourceStage is a bug as well.

IncomingConnectionStage is the canonical example of a non-bug :-)
