### ISSUE TITLE
akka-http-client - Exceeded configured max-open-requests

### ISSUE THREAD

**Issue by danpersa** [akka/akka#20004]
I'm using akka-http-client to call a service every second or so. After half of a day of doing that, I get:

```
Exceeded configured max-open-requests value of [128]
```

The service I'm calling is up and running, answering to requests from other clients in less than 1 sec.

My `application.config` file contains:
```
akka {
  loglevel = DEBUG
  
  http {
    client {
      connecting-timeout = 1s
      idle-timeout = 5 s
    }
    
    host-connection-pool {
      max-open-requests = 128
      idle-timeout = 5 s
      client {
        connecting-timeout = 1s
        idle-timeout = 5 s
      }
    }
  }
}
```

I'm using a connection pool:

```
val pool = ConnectionPoolFactory(uri)(actorSystem, materializer)

val futureResponse = Source.single(
      HttpRequest(
        uri = uri,
        method = method,
        headers = headersForToken(token)
      ) -> 1
    ).via(pool)
      .completionTimeout(1.second)
      .runWith(Sink.head)
      .flatMap {
        case (Success(r: HttpResponse), _) ⇒ Future.successful(r)
        case (Failure(f), _)               ⇒ Future.failed(f)
      }
```

Can somebody help me?

**Comment by ktoso** [comment]
Sounds like you're not consuming the response entity?
You must run: `r.entity.dataBytes.runWith(...)` otherwise back-pressure kicks in (as designed) keeping the connection open, and not reading data from it until there's actual demand for it (i.e. you run the databytes stream)

**Comment by ktoso** [comment]
We'll look into it nevertheless, just saying that customer things are given priority (luckily here I realised you're a subscriber :-)).

Will report back soon!

**Comment by danpersa** [comment]
@ktoso, any progress with this issue? :)

**Comment by ktoso** [comment]
Not yet, work week just started... :wink:

**Comment by danpersa** [comment]
as soon as you have a timeline, please let me know :+1: we also need to do some planning

**Comment by ktoso** [comment]
If you need quicker help on this one can we take it over our support channel?
I don't think this is a bug but rather untypical usage of the client, will try to look into it soon (ping via support portal would help me a lot to keep track easier and get back to you sooner).

**Comment by danpersa** [comment]
thanks for the tip :)
