### ISSUE TITLE
Would it be possible to idleTimeout set in a directive

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20007]
Interesting question, as we have RequestTimeouts, however idleTimeout is confusing a lot of people nowadays. We'll not log DEBUG soon already, but with websockets people most likely will want to have long lived ones actually... 

We should investigate what it would take to have a `withoutIdleTimeout {}` directive etc.

:point_up: [March 11, 2016 12:35 AM](https://gitter.im/akka/akka?at=56e204be9f24605773d7189d)

// I did not think it through from an impl perspective, but idea is interesting.

**Comment by rkuhn** [comment]
Such a directive only makes sense for requests that govern the whole remainder of the connection’s lifecycle—normal requests are ephemeral and have nothing to say on the more long-lived connection. Since websockets are the only example, it would make sense to leave idleTimeout handling of websocket connections to the websocket code.

**Comment by ktoso** [comment]
Yes, it only makes sense for by-definition one-request on this connection, however there's a popular style of API those represent: streaming responses.

One prominent example of such APIs that might end up being idle for quite a while (i.e. I want longer timeout for these) are APIs that are like Twitter's [statuses/filter](https://dev.twitter.com/streaming/reference/post/statuses/filter) - if I filter for `#akka` and no one is tweeting that, I don't want to be disconnected after a minute, for others 1 minute of inactivity would be weird and I'd like to disconnect for example.

Some endpoints might be set up to be long polling ready, others not.

So I think we need it not only for websockets, but also for normal request/response – esp. since we keep talking about streaming :-)

**Comment by rkuhn** [comment]
Ah, right, I see. This calls for the ability to send a SetIdleTimeout messages through the response pipeline to reconfigure the timeout handling stage.

**Comment by ktoso** [comment]
We won't be able to focus on this ticket soon. Up for grabs! Anyone? :)

**Comment by rleibman** [comment]
I'd like to take a look at it. Would you mind telling me what you have in mind and any implementation ideas you have?

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
