### ISSUE TITLE
Remove Collect.NotApplied

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#20019]
There is no need to use this,eg,for Collect,we could rewrite with 

If(pf.isDefinedAt(elem)) ctx.push(pf.apply(elem)) else ctx.pull()

**Comment by hepin1989** [comment]
So does the Recover.

**Comment by viktorklang** [comment]
@hepin1989 :-1: since then you evaluate the guard twice.

**Comment by viktorklang** [comment]
Ok to close?

**Comment by ktoso** [comment]
Ok to close I think, yeah.
Please use the obsolete tag when closing tickets like that (new thing we're applying nowadays).

**Comment by viktorklang** [comment]
Is obsolete == wontfix?

**Comment by ktoso** [comment]
Pretty much, though we wanted to keep the "reopen if necessary" in the name, to be able to aggresively apply this tag and close issues instead of leaving them lingering around. If people care strongly about one, we encourage reopening and discussing again.

**Comment by patriknw** [comment]
Well obsolete was intended for tickets that had grown old/inactive. This is new.

**Comment by viktorklang** [comment]
Assigning it to milestone Invalid might be enough here?

**Comment by ktoso** [comment]
Ok, I guess so – removing obsolete.

**Comment by hepin1989** [comment]
@viktorklang why?

**Comment by viktorklang** [comment]
Why what?

-- 
Cheers,
√

**Comment by hepin1989** [comment]
How could that lead to eval twice？

**Comment by hepin1989** [comment]
@viktorklang ,I know it know,thanks.

**Comment by viktorklang** [comment]
Np! :)

-- 
Cheers,
√
