### ISSUE TITLE
compress materialized value computation tree

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#20015]
When performing 10000 map operations in a row, there is no reason for the resulting graph module to have a materialized value computation tree of depth 10000: all composition nodes just do `Keep.left` anyway.

Solving this ticket will take the immediate pressure off our materialization and fusing algorithms to trampoline the tree traversals, which is rather tricky to do. A graph with materialized value computation depth of several thousand levels is considered a special use-case that requires tuning the JVM stack size.

**Comment by drewhk** [comment]
Have you tried the stress-test which uncovered this?

**Comment by rkuhn** [comment]
ah, damn, I knew I had forgotten to add something; will do
