### ISSUE TITLE
figure out whether TickSourceCancellable.cancel returning true is a bug

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#20028]
the cancellation logic is a rather complicated dance—quite possibly more complex than it needs to be

**Comment by samueltardieu** [comment]
See PR https://github.com/akka/akka/pull/20076.

**Comment by samueltardieu** [comment]
For reference, the current state before the fix is:
- `cancel()` will return `true` even after the first time it is called;
- a tick might be emitted after `cancel()` has returned;
- `isCancelled` can return false after `cancel()` has returned.
