### ISSUE TITLE
CircuitBreakerOpenException remainingTimeout is not the correct amount of time till HalfOpen state

### ISSUE THREAD

**Issue by badbeeker** [akka/akka#20029]
It seems that the remainingTime in CircuitBreakerOpenException class is incorrect when the CircuitBreaker changes state to Open.

The following code is triggered when the Open state is invoked:

``` 
   private object Open extends AtomicLong with State {

    /**
     * Fail-fast on any invocation
     *
     * @param body Implementation of the call that needs protected
     * @return Future containing result of protected call
     */
    override def invoke[T](body: ⇒ Future[T]): Future[T] =
      Promise.failed[T](new CircuitBreakerOpenException(remainingDuration())).future

    /**
     * Calculate remaining duration until reset to inform the caller in case a backoff algorithm is useful
     *
     * @return duration to when the breaker will attempt a reset by transitioning to half-open
     */
    private def remainingDuration(): FiniteDuration = {
      val diff = System.nanoTime() - get
      if (diff <= 0L) Duration.Zero
      else diff.nanos
    }

    /**
     * No-op for open, calls are never executed so cannot succeed or fail
     *
     * @return
     */
    override def callSucceeds(): Unit = ()

    /**
     * No-op for open, calls are never executed so cannot succeed or fail
     *
     * @return
     */
    override def callFails(): Unit = ()

    /**
     * On entering this state, schedule an attempted reset via [[akka.actor.Scheduler]] and store the entry time to
     * calculate remaining time before attempted reset.
     *
     * @return
     */
    override def _enter(): Unit = {
      set(System.nanoTime())
      scheduler.scheduleOnce(resetTimeout) {
        attemptReset()
      }
    }

    /**
     * Override for more descriptive toString
     *
     * @return
     */
    override def toString: String = "Open"
  }
```

In the _entry() method, we are setting the current entry time to the method.  If a call comes in during this state, invoke() is called and fails the future with a new CircuitBreakerOpenException and sets the remaining duration by calling remainingDuration().

In remainingDuration(), the calculation is not taking the resetTimeout into account.  Instead it just returns the difference between now and when we entered the Open state.

Shouldn't the remainingDuration value be the amount of time until the HalfOpen state is triggered?

**Comment by patriknw** [comment]
Good catch. I think you are correct. Would you like to contribute with a pull request?

**Comment by badbeeker** [comment]
Sorry, just got back to this.  I can contribute some code to this issue.  I will try to get something ready in the next week.

**Comment by patriknw** [comment]
that would be great, thanks

**Comment by richard-imaoka** [comment]
Hi @badbeeker, sorry to cut in, but if you are still busy, could I make a contribution to this issue? I think this is 1 or 2 lines of fix.
