### ISSUE TITLE
Emphasise singleRequest more in docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20030]
As it's the simplest and most likely the API most people should be using.
Currently docs come in order from "lowest level to" "request level", which noone understands that that is the "simple one".

**Comment by marekzebrowski** [comment]
... but singleRequest is buggy, or at least not obvious to use it right - it overflows connection pool immediately, as  in https://groups.google.com/forum/?fromgroups#!searchin/akka-user/singleRequest/akka-user/t2pGKXclxMo/lB0swlYzDgAJ
, `Http().cachedHostConnectionPool` is working default for now.

**Comment by danischroeter** [comment]
I did not find a bug about BufferOverflowException for Http().singleRequest but i just happened to run into the same problem.
Is there a bug open?
I just wonder how using Http().cachedHostConnectionPool can actually prevent having too many requests open if used by several independent actors?

**Comment by 2beaucoup** [comment]
`cachedHostConnectionPool` provides a flow which can apply backpressure to the upstream request source while `singleRequest` fills its internal buffer up to max-open-requests and then gives up. A workaround would be to await a response before the next request is send but that wouldn't properly utilize the pool.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
