### ISSUE TITLE
"become non-full after head dropped from full buffer" from the FixedBufferSpec's checks wrong behavior

### ISSUE THREAD

**Issue by Silv3rcircl3** [akka/akka#20039]
I'm currently porting these tests to Akka.net and found a copy paste issue. 

The  [become non-full after head dropped from full buffer](https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/impl/FixedBufferSpec.scala#L76) spec doesn't check dropHead but rather dropTail from the previous spec.

**Comment by johanandren** [comment]
Thanks for reporting!

**Comment by patriknw** [comment]
not `bug`
