### ISSUE TITLE
Akka website margins messed up

### ISSUE THREAD

**Issue by Falmarri** [akka/akka#20044]
The combination of the negative top margin of the .main container and the overflow:auto are causing the page to be right aligned instead of center aligned.

![image](https://cloud.githubusercontent.com/assets/463948/13796179/79570de2-eac2-11e5-9cbe-15026d212aa8.png)

vs

![image](https://cloud.githubusercontent.com/assets/463948/13796155/5619fdc6-eac2-11e5-85e9-a775f841afc2.png)

**Comment by ktoso** [comment]
Thanks for figuring that out!
Seems like you have the change ready, could you submit a PR?

the css files are here: https://github.com/akka/akka/blob/master/akka-docs/_sphinx/themes/akka/static/docs.css

**Comment by Falmarri** [comment]
@ktoso I'll submit a PR, but this seems to be a chromium specific bug. -18px works on firefox. However -17px shouldn't break anything else

**Comment by ktoso** [comment]
Right, chromium is usually a bit iffy to judge by but such small tweak should be OK.

**Comment by ktoso** [comment]
Thanks again @Falmarri !
