### ISSUE TITLE
headerValueByType fails to match

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#20052]
At least when using a `ModeledCustomHeader`, the directive `headerValueByType` fails to match. To reproduce the error, take a look at the following test case from akka-sse and replace the working `headerValueByName` with the commented `headerValueByType`: https://github.com/hseeberger/akka-sse/blob/master/akka-sse/src/test/scala/de/heikoseeberger/akkasse/headers/LastEventIdSpec.scala#L45

**Comment by ktoso** [comment]
Look Ma, I fixed it!
https://github.com/akka/akka/pull/20055

**Comment by hseeberger** [comment]
Nice!

**Comment by drewhk** [comment]
I always read the title of this ticket as "headerValueByType fails too much" :)

**Comment by ktoso** [comment]
> I always read the title of this ticket as "headerValueByType fails too much" :)

:grinning: Day of mis-reading stuff? I just read "soviet model" instead of "servlet model" on twitter somewhere ;-)
