### ISSUE TITLE
Explain blocking in context of Akka HTTP

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20066]
People seem to be coming to Akka HTTP instead of Spray because it's less Actors exposed, 
and they forget that the infra is still Actors – thus forgetting that and blocking inside the routes etc.

Document blocking in the akka http docs somewhere, so that it's simple to find.
Should also point to: http://doc.akka.io/docs/akka/2.4.2/general/actor-systems.html#blocking-needs-careful-management

And use my SO answer maybe to explain it visually? http://stackoverflow.com/questions/34641861/akka-http-blocking-in-a-future-blocks-the-server/34645097#34645097

**Comment by ktoso** [comment]
Moving from private to github:

> Hi Konard, I'm interested to work on some issues. One of the issue that I was considering is #20066 akka/akka#20066
> My understanding about this issue till now is that the blocking is done incorrectly and you want to document the correct way to do blocking in akka http related document.
> Could you tell me if I have understood the issue correctly and if I can proceed with the documentation.

This ticket is about creating a section (page - see inside `akka-docs`)  which would explain how to handle blocking operations. Perhaps the best would be a new page that we call "Handling blocking operations in akka http routes", and in there explain the problem and solution (as I did in the SO answer).

I think you can get started and submit a PR once you have it in a reviewable state and we'll review then :-) Thanks in advance for your help!

**Comment by meghanamancheela** [comment]
Thanks @ktoso. I'll start working on creating new page and submit a PR asap.

**Comment by ktoso** [comment]
Great, thank you!

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
