### ISSUE TITLE
Utility for creating a source that needs resources to be released

### ISSUE THREAD

**Issue by hbf** [akka/akka#20079]
_Akka Stream_ 2.4.2's `Source` provides

    def from[O](iterable: java.lang.Iterable[O]): javadsl.Source[O, NotUsed]

which is very useful. I often run into the situation, however, that I'm construction an iterator whose resources need to be _released_ on stream completion.

Currently, I'm doing something like

```java
final MyCloseableIterator iterator = new ...;
return Source.from(() -> iterator) // (*)
    .mapMaterializedValue(__ -> whatever)
    .watchTermination((whatever, onComplete) -> {
        onComplete.whenComplete((__, ___) -> iterator.close());
        return whatever;
    });
```

Ideally, we would _construct_ the iterator in the lambda at `(*)`. The only way that comes to my mind to achieve this would be a `Source.from()` static method that takes a lambda returning both the iterator and a materialized value.

Thoughts?

**Comment by johanandren** [comment]
This is already being worked on in #18620
