### ISSUE TITLE
Akka stream secured incoming TCP connections not completing

### ISSUE THREAD

**Issue by roldugin** [akka/akka#20092]
I have a long running Akka stream server and client communicating over secured TCP. If the client dies, the server never notices that the connection dropped.

I have experimented with `Closing` setting of `SslTls` and the `halfClose` setting, but as far as I understand, they won't help here.
## Reproducing the issue

I have prepared a sample program to demonstrate the behaviour: https://github.com/roldugin/akka-stream-ssltest

If `SslTlsPlacebo` is used, the server will notice the client disconnecting:

```
$ sbt "run server placebo"
[info] Server started, listening on: /127.0.0.1:6000
[info] Client connected from: /127.0.0.1:60312
[info] Client disconnected
```

```
$ sbt "run client placebo"
[info] Simulating client crashing
```

However, if a proper SSL/TLS connection is established, the graph handling the incoming connection will never terminate.

```
$ sbt "run server ssl"
[info] Server started, listening on: /127.0.0.1:6000
[info] Client connected from: /127.0.0.1:60289
```

```
$ sbt "run client ssl"
[info] Simulating client crashing
```

**Comment by drewhk** [comment]
What OS are you using?

**Comment by roldugin** [comment]
OS X Yosemite (10.10) and some homegrown version of linux.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by raboof** [comment]
(This was accidentally moved to the akka-http project)

**Comment by raboof** [comment]
Sorry to leave this open for so long. Thanks for the reproducer! I was able to use it to verify this indeed failed for me as well for this version, but works when updated to Akka 2.5.23. For the updated reproducer see https://github.com/raboof/akka-stream-ssltest/tree/updateAkka .
