### ISSUE TITLE
Better "collect Strict" specifically for WebSockets Flow

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20096]
This is what people do (and I'd do so myself):

```scala
        val flow = Flow[Message].collect {
          case TextMessage.Strict(msg) =>
            msg.parseJson.convertTo[Anything]
```

which can randomly break "almost work", due to even the smallest message sometimes ending up as `Streamed` (I've seen this with msg as small as `"Hello world"`).

"Almost work" here is defined as – small message comes in, but ends up being streamed, the collect here drops it, processing is stalled until subscription timeout triggers killing the `textStream` of the streamed message.

We should provide a safe way to "I know these will be strict, or force them to be". 
This is somewhat related to the "auto drain" feature for HttpRequests too, however likely a different trick will have to be applied.

For reference, this is what I ended up with in a project I hackked on:

```scala
  implicit class flowTweaks[M](val wsInput: Source[Message, M]) {
    def forceTextStrict: Source[Strict, M] = wsInput
      .collect {
        case TextMessage.Strict(text)             ⇒ Future.successful(text)
        case TextMessage.Streamed(textStream)     ⇒ textStream.runFold("")(_ + _)
        case BinaryMessage.Strict(binary)         ⇒ Skip
        case BinaryMessage.Streamed(binaryStream) ⇒ binaryStream.runWith(Sink.ignore); Skip
      }
      .filterNot(_ == Skip)
      .mapAsync(1)(ConstantFun.scalaIdentityFunction)
      .map(TextMessage.Strict)
    }
```

**Comment by ktoso** [comment]
This was already brought up in a somewhat similar issue: https://github.com/akka/akka/issues/19089

**Comment by rkuhn** [comment]
I think it is a mistake to allow users to pattern-match on strict entities, this opens up all kinds of scenarios that “work fine” in tests but fail in production. The reason is that whether something is strict or not depends on random interactions of TCP flow control and buffer sizes, strictness is a low-level implementation detail and not dependable for user-space.

Of course I can already hear the screams of the benchmark crazies that care less about correctness and more about arcane optimizations and general geekiness.

Therefore the probable solution is that we provide a proper (i.e. working but also configurably bounded) implementation of how to convert incoming websocket messages into their strict representation.

**Comment by ktoso** [comment]
> The reason is that whether something is strict or not depends on random interactions of TCP flow control and buffer sizes, strictness is a low-level implementation detail and not dependable for user-space

Yeah, very true - it's not predictable. One can't even assume it is Strict for a really small message ("Hello").

Also, then it seems we do not want to: https://github.com/akka/akka/pull/20087 (currently it is impossible to do the draining even - since you can't match on `Streamed`), so most if not all impls are wrong - assuming Strict.

We could turn our thinking about it upside down a bit, and say one should never match on either Strict or Streamed, and provide DSL or directives to do the right thing. As @jrudolph notices in the other thread, one usually works with small messages so to-strict-ing incoming messages may not be as bad as in the general setting, so we could provide directives:

```scala
handleWebSocket[TextMessage.Strict](flow)
```

instead... WDYT?

**Comment by rkuhn** [comment]
Yes, that’s good as well, but it should also have an upper bound on message size—and if deviations are wanted on a per-case basis then handing the full protocol should be possible (as you note, this requires users to be able to actually do that).

**Comment by ktoso** [comment]
> Yes, that’s good as well, but it should also have an upper bound on message size

Yeah good point, a default from config though, otherwise a bit too clunky

**Comment by mmacfadden** [comment]
+1 on this issue.  I think in addition to adding functionality an example somewhere in the docs on handling streamed vs strict messages would also be great.

**Comment by antonkulaga** [comment]
yes, the bug is very annoying, cause seame messages are almost always Strict  on localhosts and tests but often Streamed in production enviroments =(

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
I'm so sorry about the duplicates >_>
