### ISSUE TITLE
Akka HTTP authenticateOAuth2* directives fail to follow the specs for WWW-Authenticate

### ISSUE THREAD

**Issue by chris-zen** [akka/akka#20102]
When the OAuth2 token validation fails for the directives ```authenticateOAuth2*```, the content for the ```WWW-Authenticate``` doesn't follow the RFC at https://tools.ietf.org/html/rfc6750#section-3

> All challenges defined by this specification MUST use the auth-scheme  value "Bearer".

I get:
```
WWW-Authenticate: Basic realm="my-realm"
```
but it should be:
```
WWW-Authenticate: Bearer realm="my-realm"
```

The specs also allow to put more ```auth-param values``` a part from the ```realm``` one, such the required scope of the access token for accessing the requested resource, as well as error information:

> If the protected resource request included an access token and failed
> authentication, the resource server SHOULD include the "error"
> attribute to provide the client with the reason why the access
> request was declined.
> ...
> HTTP/1.1 401 Unauthorized
> WWW-Authenticate: Bearer realm="example", error="invalid_token", error_description="The access token expired"

Is there any plan/way to add all this information ? actually the ```Authenticator[T]``` only allows yes or not responses by expecting an ```Option``` in return, but it would be more useful to have an ```Either``` where the left side is an error object that contains all these extra pieces of information needed to build the ```WWW-Authenticate``` header properly.

One last thing is that in my use case I don't know the required realm until the token is validated. Having the ```Either``` with a left error object would allow me to put it there when I really have the information instead of when I use the directive
```
def authenticateOAuth2Async[T](realm: String, authenticator: AsyncAuthenticator[T]): AuthenticationDirective[T]
```
Akka version 2.4.2

**Comment by ktoso** [comment]
Thanks for reporting Chris!
The Basic => Bearer is a rather simple fix, the 2nd part of the question I'd have to look into (should also not be that hard).

The first can be solved by making such fixup in `SecurityDirectives`:

```scala
case None    ⇒ AuthenticationResult.failWithChallenge(challengeFor(scheme = "Bearer", realm = realm))
```

Would you want to help us out and prep a contrib PR to fix that?

**Comment by chris-zen** [comment]
Of course, it looks simple.
As soon as I get familiarized with the contribution policies and figure out what CLA applies to me I'll start with it.

My plan is to PR the fix for the scheme first and get familiarized with the contribution details. Then we can start to discuss about whether to include a new directive for addressing the 2nd part concerns. I already have a working implementation in my code, I just created my own directive based on the existing implementation.

```scala
type AsyncAuthenticatorWithChallenge[T] = Credentials => Future[Either[HttpChallenge, T]]

def authenticateOAuth2Async[T](authenticator: AsyncAuthenticatorWithChallenge[T]): AuthenticationDirective[T]
```

**Comment by ktoso** [comment]
Sounds great, looking forward to the PR!
Let me know if you'd need to discuss something or need help about anything in there.

**Comment by pchordia15** [comment]
Since there is no PR created for the first part. I'll create one for it. Also if there isn't any progress working on the second question, I would like to work on that too.

**Comment by chris-zen** [comment]
@pchordia15, great to hear you are interested in it, I have too many things ongoing and this went to my long backlog ;-)
Thanks

**Comment by pchordia15** [comment]
@chris-zen, No problem. Thanks for letting me move forward with working on this issue.
