### ISSUE TITLE
Use ScalaDoc @groups to make FlowOps / Directives nicer to navigate

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20103]
ScalaDoc has this undocumented feature of `@group*`, see in in action here: http://www.scala-lang.org/api/2.11.8/scala-reflect/index.html#scala.reflect.api.Types (notice how sections have titles and descriptions).

More details and how to impl: https://twitter.com/SethTisue/status/712001440466804736

**Comment by ktoso** [comment]
It only needs a `-groups` flag set via unidoc to get it working: https://twitter.com/runarorama/status/715643902959751168

**Comment by ktoso** [comment]
Done for HTTP directives by @larsrh in #20207, we should do the same for streams ops.

**Comment by poojadshende** [comment]
@ktoso, I have started working on this change, but I have questions.
while creating a group we provide groupname and groupprio.
I understood for groupname (its group name and discription), but what is groupprio. I think it's something about priority, but how do I decide it fro each group

**Comment by pchordia15** [comment]
@poojadshende i am halfway through solving this issue.

**Comment by poojadshende** [comment]
@pchordia15 Ok. Do. Do mention from next time on issue page.

**Comment by pchordia15** [comment]
@poojadshende Oh yes. I'll make sure about it.

**Comment by ktoso** [comment]
@poojadshende if you'd still want to contribute this then please do so in the akka-http repository :-)
Thanks in advance!

----

Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
