### ISSUE TITLE
Alternative fishForMessage that returns result of partial function

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#20118]
Akka TestKit contains a method with this signature:

``` scala
def fishForMessage(max: Duration = Duration.Undefined, hint: String = "")(f: PartialFunction[Any, Boolean]): Any
```

Is there a reason there's no alternative version which looks like this:

``` scala
def fishForMessage[T](max: Duration = Duration.Undefined, hint: String = "")(f: PartialFunction[Any, T]): T
```

**Comment by jrudolph** [comment]
Is it possible to use the existing methods to do the same? `receiveWhile` and `expectMsgPF` look very similar but not quite.

Here's a possible implementation:

```scala
  def fishForMessageAndReelIn[T](max: Duration = Duration.Undefined, hint: String = "")(f: PartialFunction[Any, T]): T = {
    val _max = remainingOrDilated(max)
    val end = now + _max
    @tailrec
    def recv: T = {
      val o = receiveOne(end - now)
      assert(o ne null, s"timeout (${_max}) during fishForMessageAndReelIn, hint: $hint")
      if (f.isDefinedAt(o)) f(o) else recv
    }
    recv
  }
```

**Comment by drewhk** [comment]
I guess the reason why it did not take a type `T` is was because most of the use-cases were when a message must be "fished out" from a flow of mostly unrelated message types, i.e. the type was inferred to be `Any` in those cases. But I see no reason against including new variants.

**Comment by drewhk** [comment]
Ah, never mind my comment above, there is a PartialFunction there. I guess it is an oversight simply.

**Comment by patriknw** [comment]
sounds useful with that version, if you can come up with a good name for it ;-)

**Comment by miciek** [comment]
@patriknw @drewhk @ktoso We need this function. I can do it.

**Comment by patriknw** [comment]
sounds good, @miciek
