### ISSUE TITLE
Looks like implementation of WSProbe is incorrect

### ISSUE THREAD

**Issue by Mullefa** [akka/akka#20122]
In the `WSProbe` returned by `WSProbe.apply` the `inProbe` and `outProbe` are defined as:

```scala
def inProbe: TestSubscriber.Probe[Message] = subscriber
def outProbe: TestPublisher.Probe[Message] = publisher
```
whereas I think it should be:

```scala
def inProbe: TestSubscriber.Probe[Message] = publisher
def outProbe: TestPublisher.Probe[Message] = subscriber
```

Also the documentation for the two methods in the `WSProbe` is duplicated:

```scala
  /**
   * The underlying probe for the ingoing side of this probe. Can be used if the methods
   * on WSProbe don't allow fine enough control over the message flow.
   */
  def inProbe: TestSubscriber.Probe[Message]

  /**
   * The underlying probe for the ingoing side of this probe. Can be used if the methods
   * on WSProbe don't allow fine enough control over the message flow.
   */
  def outProbe: TestPublisher.Probe[Message]
```

**Comment by jrudolph** [comment]
Thanks, @Mullefa. You are correct, of course, that the documentation was just copied and needs to be fixed. I think the implementation, though, is correct. `inProbe` is the probe that gets data in from the peer and must therefore be a subscriber. `outProbe` is the probe that allows you to push data to the peer and is therefore the publisher. Why do you think it is wrong?

**Comment by ktoso** [comment]
Ended up forgetting to reply here last night.

Yeah, agree with @jrudolph – it's just that it takes some wrapping your head around these things.
Drawing a box like this usually helps to "get" it :wink::

```
publisher ~> [ subscriber(inProbe) publisher(outProbe) ] ~> subscriber
```

**Comment by poojadshende** [comment]
@ktoso, can you tell the file in which document for above is listed. I can fix it and submit a PR.

**Comment by ktoso** [comment]
It's about the javadoc comments on the probes AFAIR, thanks!
