### ISSUE TITLE
Provide an example for how to implement Http long polling

### ISSUE THREAD

**Issue by agemooij** [akka/akka#20121]
Quoted from a Gitter discussion:

>Hey hakkers. I'm still pretty new to doing complex things with streams and akka-http. Does anyone have an example of how to implement long polling with the client-side part of akka-http? I've got a Consul client written as Spray actors that I'm thinking of moving to akka-http but the conceptual model is (unsurprisingly) very different indeed.

>The docs mention long polling a bunch of times when discussing the higher (i.e. connection pooling) API levels but I can't find any real information (docs, examples, blogs, SO questions, etc.) on how I would go about implementing a long polling client using akka-http and streams.

>For instance: I want to poll forever but how do I automatically recreate the http connection produced by Http().outgoingConnection when it closes? And that method produces a Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] but how do I turn that into a loop of requests where every next request is based on the response to the previous one (i.e. polling forchanges since the index that got sent with the previous change). Both of these are basically circular/recursive internal graph stages but conceptually what I want is a Source[ConsulChangeEvent].

**Comment by drewhk** [comment]
Isn't long polling simply like:

```scala
Source.repeat(pollRequest).via(Http().outgoingConnection(url)).flatMapConcat(_.entityBytes)
```

I.e. continuously feed requests into the Http connection, returning a response once there is one.

**Comment by ktoso** [comment]
+ reconnecting

**Comment by drewhk** [comment]
Then use `Source.repeat(pollRequest).mapAsync(1)(Http.singleRequest)` for now

**Comment by agemooij** [comment]
The URI of each next request depends on the response to the previous request. An example API call:

    GET /v1/health/service/blaze-canary-service?index=3232540&wait=300s&passing

Here, `index` is a value that comes from the previous response. Also, indeed, when the connection gets dropped, it should recreate it again. The `wait` param specifies the server-side max wait (i.e. 300 seconds). After that the connection gets dropped and it should be recreated.

The docs strongly state that using the shared pool for long-polling requests is not encouraged. AFAIK `Http().singleRequest` uses the super pool.

**Comment by agemooij** [comment]
The target API is this [Consul](https://www.consul.io/docs/agent/http.html) (see the top section about "blocking queries")

**Comment by agemooij** [comment]
A Spray implementation as a reference for what I'm trying to achieve using streams:

```scala
package rfs.blaze.gateway.config
package consul

import scala.concurrent.duration._
import scala.util._

import akka.actor._
import akka.io.IO

import spray.can._
import spray.can.client._
import spray.http._
import spray.httpx.RequestBuilding._
import spray.json._

object Consul {
  def startWatching(endpoint: ConsulEndpoint, sender: ActorRef)(implicit actorRefFactory: ActorRefFactory): ActorRef = {
    val encodedUri = endpoint.baseUri.path.toString.replaceAllLiterally("/", "-")
    val name = s"consul-watcher${encodedUri}"
    val watcher = actorRefFactory.actorOf(Props[ConsulEndpointWatcher], name)

    watcher.tell(ConsulEndpointWatcher.StartWatching(endpoint), sender)
    watcher
  }
}

object ConsulEndpointWatcher {
  case class StartWatching(endpoint: ConsulEndpoint)
  case object Reconnect

  case class ConsulValueChanged(value: AnyRef)
  case object InvalidConsulResponse
  case class ConsulEndpointUnreachable(endpoint: ConsulEndpoint)
}

/**
 *
 */
class ConsulEndpointWatcher extends Actor with ActorLogging {
  import ConsulEndpointWatcher._
  import context.dispatcher
  import Http._

  def receive = notConnected

  def notConnected: Receive = {
    case StartWatching(endpoint) ⇒ {
      context.become(connecting(sender(), endpoint, None, None))
      connect(endpoint)
    }
  }

  def connecting(controller: ActorRef, endpoint: ConsulEndpoint, previousIndex: Option[Long], previousValue: Option[AnyRef]): Receive = {
    case _: Connected ⇒ {
      log.debug("Connected")

      val connection = sender()

      context.watch(connection)
      context.become(watching(controller, connection, endpoint, previousIndex, previousValue))
      watch(connection, endpoint, previousIndex)
    }

    case CommandFailed(Connect(address, _, _, _, _)) ⇒ {
      log.error(s"Failed to connect using address ${address}")

      controller ! ConsulEndpointUnreachable(endpoint)

      // TODO: is reconnect always the correct strategy?
      // TODO: implement a backoff strategy
      // shouldn't we leave this to the supervision hierarchy?
      context.system.scheduler.scheduleOnce(1 second, self, Reconnect)
    }

    case Reconnect ⇒ {
      log.debug("Connecting...")

      connect(endpoint)
    }

    case Terminated(actor) ⇒ log.debug(s"Received Terminated event in 'connecting' state. Deceased: $actor")
  }

  def newIndex(headers: Seq[HttpHeader]) =
    headers.find(_.is("x-consul-index")).map(_.value.toLong)

  def consulIndexAlreadySeen(previousIndex: Option[Long], headers: Seq[HttpHeader]) =
    previousIndex.isDefined && previousIndex == newIndex(headers)

  def watching(controller: ActorRef, connection: ActorRef, endpoint: ConsulEndpoint, previousIndex: Option[Long], previousValue: Option[AnyRef]): Receive = {
    case HttpResponse(_, _, headers, _) if consulIndexAlreadySeen(previousIndex, headers) ⇒
      log.debug(s"x-consul-index ${newIndex(headers)} already seen")
      watch(connection, endpoint, newIndex(headers))

    // TODO: deal with other non-200 status codes?
    case HttpResponse(status: StatusCodes.ServerError, entity, _, _) ⇒ {
      log.warning(s"Received status $status from consul: $entity")
      watch(connection, endpoint, previousIndex, delay = 1 second)
    }

    case HttpResponse(status, entity, headers, _) ⇒ {
      readResponseValue(entity, endpoint.reader) match {
        case Success(newValue) ⇒ {
          if (previousValue.forall(_ != newValue)) {
            log.debug(s"Received new value $newValue on endpoint $endpoint")
            controller ! ConsulValueChanged(newValue)
            context.become(watching(controller, connection, endpoint, newIndex(headers), Some(newValue)))
          } else {
            log.debug(s"Received unchanged value $newValue on endpoint $endpoint")
          }

          watch(connection, endpoint, newIndex(headers))
        }

        case Failure(error) ⇒ {
          log.error(s"Error while reading response value. Error: ${error.getMessage}, status code: ${status}")
          controller ! InvalidConsulResponse
          watch(connection, endpoint, newIndex(headers), delay = 1 second)
        }
      }
    }

    case event @ (SendFailed(_) | Timedout(_) | Aborted | Closed | PeerClosed | ErrorClosed(_) | Terminated(_)) ⇒ {
      log.debug(s"Disconnected from $endpoint due to $event, reconnecting")
      context.become(connecting(controller, endpoint, previousIndex, previousValue))
      context.system.scheduler.scheduleOnce(1 second, self, Reconnect)
    }

    case Reconnect ⇒ log.warning("Received a Reconnect event in 'watching' state.")
  }

  // ==========================================================================
  // Implementation details
  // ==========================================================================

  /** Overridable for test purposes */
  private[consul] def connect(endpoint: ConsulEndpoint): Unit = {
    IO(Http)(context.system) ! Connect(
      host = endpoint.host,
      port = endpoint.port,
      settings = Some(ClientConnectionSettings(context.system).copy(
        idleTimeout = endpoint.watchTimeout + endpoint.clientTimeoutBuffer,
        requestTimeout = endpoint.watchTimeout + endpoint.clientTimeoutBuffer
      ))
    )
  }

  private def watch(connection: ActorRef, endpoint: ConsulEndpoint, previousIndex: Option[Long], delay: FiniteDuration = 0 seconds): Unit = {
    context.system.scheduler.scheduleOnce(delay, connection, requestFor(endpoint, previousIndex))
  }

  private def requestFor(endpoint: ConsulEndpoint, previousIndex: Option[Long]): HttpRequest = {
    Get(endpoint.uri(previousIndex)) ~> addHeader(HttpHeaders.Connection("Keep-Alive"))
  }

  private def readResponseValue(entity: HttpEntity, reader: ConsulResponseReader): Try[AnyRef] = {
    entity.toOption.map { data ⇒
      Try(reader.read(JsonParser(data.asString)))
    }.getOrElse(Failure(new RuntimeException("Empty http entity!")))
  }
}
```

**Comment by agemooij** [comment]
And @drewhk I would love for there to be a "don't be stupid, just use this one-liner" answer to this because the complexity of this in Spray was exactly the reason why I started looking at how this would work in akka-http :smile:

**Comment by drewhk** [comment]
> The docs strongly state that using the shared pool for long-polling requests is not encouraged. AFAIK Http().singleRequest uses the super pool.

I guess the host based connection pool can be used then:

```scala
Source.repeat(pollRequest).via(Http().cachedHostConnectionPool(...))
```

This will do reconnects AFAIK at the pool level, and since this is a dedicated pool it won't interfere with the rest of the system.

The final solution might be a bit more complicated and need a Graph cycle if you need to limit the poll count bounded. For example (pseudocode):

```scala
Graph.create {
  Source.single(pollRequest) ~> merge ~> cachedConnectionPool ~> bcast ~> out
                                                   merge <~ map(_ => pollRequest) <~ bcast
}
```

will keep the number of outstanding polls exactly one (as there is one poll circulating in the loop). Of course above needs error handling.

**Comment by agemooij** [comment]
Thanks. That looks like something that might work. I'll go figure it out and report back. That DSL sure takes some time to get used to :smile:

**Comment by agemooij** [comment]
Finally got some time to experiment with this again. An update on my progress so far:

- the approach sketched above by @drewhk works in essence, although it required some tweaks here and there
- the details of the cached host connection pool make things a bit more complex due to the type of the flow returned, i.e. `Flow[(HttpRequest, T), (Try[HttpResponse], T), HostConnectionPool]`. For now I've gone for using the request itself as the identifying `T`
- if I don't immediately consume the response entity, the whole thing grounds to a halt. This means I will have to map the output  `HttpResponse` to one using a `HttpEntity.Strict` entity to make sure the source doesn't get blocked by consumers that forget to read the entity. In the example below I've just drained it to `Sink.ignore` for now.
- I'm still curious about whether/how this could work using the connection-level API, mostly because the use of the cached host connector pool makes it very tricky to make sure that the same cached pool is not used by other code, which might also be long pooling. I think whoever wrote those warnings in the docs about not misusing shared pools for long polling was correct. I'll dive deeper into this.

Here's what I have so far. All feedback/comments/suggestions would be very welcome.

```scala
object AkkaHttpLongPolling {
  def longPollingSource(host: String, port: Int, uri: Uri, maxWait: Duration)(implicit s: ActorSystem, fm: Materializer): Source[HttpResponse, NotUsed] = {
    import GraphDSL.Implicits._

    val connectionPoolSettings = ConnectionPoolSettings(s)

    Source.fromGraph(GraphDSL.create() { implicit b ⇒
      val init = Source.single(createRequest(uri, maxWait, None))
      val merge = b.add(Merge[HttpRequest](2))
      val broadcast = b.add(Broadcast[(Try[HttpResponse], HttpRequest)](2))
      val tupler = b.add(Flow[HttpRequest].map(r ⇒ (r, r)))
      val http = b.add(Http().cachedHostConnectionPool[HttpRequest](host, port, connectionPoolSettings).mapMaterializedValue(_ ⇒ NotUsed))

      val outbound = b.add(Flow[(Try[HttpResponse], HttpRequest)].collect {
        case (Success(response), _) ⇒ {
          // TODO: map to HttpEntity.Strict
          response.entity.dataBytes.runWith(Sink.ignore)
          response
        }
      })

      val feedback = b.add(Flow[(Try[HttpResponse], HttpRequest)].map {
        case (Success(response), _) ⇒ {
          val index = response.headers.find(_.is("x-consul-index")).map(_.value.toLong)
          println(s"Success. New index = ${index}.")
          createRequest(uri, maxWait, index)
        }
        case (Failure(cause), _) ⇒ {
          println("Failure: " + cause.getMessage)
          createRequest(uri, maxWait, None)
        }
      })

      // format: OFF
      init ~> merge ~> tupler ~> http ~> broadcast ~> outbound
              merge <~ feedback       <~ broadcast
      // format: ON

      SourceShape(outbound.out)
    })
  }

  private def createRequest(baseUri: Uri, maxWait: Duration, index: Option[Long]): HttpRequest = {
    HttpRequest(
      uri = baseUri.copy(
        rawQueryString = Some(s"wait=${maxWait.toSeconds}s&index=${index.map(_.toString).getOrElse("0")}")
      )
    )
  }
}
```

The query parameters on the request are specific to the Consul API but I expect every long-polling endpoint has some form of those same two parameters.

I plan to turn this into a blog post once I've figured some more things out and handled all the corner cases. 

Would this fit anywhere in the akka-http docs?

**Comment by agemooij** [comment]
Some more progress. I tired using the connection-level flow in combination with `flatMapConcat` but so far it doesn't reuse the resulting connection but start a new one every time. Also, just like the above version using the cached pool, the resulting flow does not recover from network errors and collapses on the first failure.

```scala
object LongPollingHttpClientUsingSingleConnection {
  def longPollingSource(host: String, port: Int, uri: Uri, maxWait: Duration)(implicit s: ActorSystem, fm: Materializer): Source[HttpResponse, NotUsed] = {
    Source.fromGraph(GraphDSL.create() { implicit b ⇒
      import GraphDSL.Implicits._
      import s._

      val settings = ClientConnectionSettings(s).withIdleTimeout(maxWait * 1.2)

      val initSource: Source[HttpRequest, NotUsed] = Source.single(createRequest(uri, maxWait, None)).log("outer 0", out ⇒ s"Sending request...")
      val httpFlow: Flow[HttpRequest, HttpResponse, NotUsed] =
        Flow[HttpRequest]
          .flatMapConcat(request ⇒
            Source.single(request)
              .via(Http().outgoingConnection(host, port, settings = settings))
          )
          .mapMaterializedValue(_ ⇒ NotUsed)

      val outboundResponsesFlow: Flow[HttpResponse, HttpResponse, NotUsed] =
        Flow[HttpResponse] // TODO: add size limit
          .mapAsync(1)(response ⇒ response.entity.toStrict(5.seconds).map(strictEntity ⇒ response.copy(entity = strictEntity)))
          .withAttributes(ActorAttributes.supervisionStrategy(Supervision.resumingDecider)) // TODO: turn into log-and-resume

      val feedbackResponsesFlow: Flow[HttpResponse, HttpRequest, NotUsed] =
        Flow[HttpResponse]
          .map { response ⇒
            log.debug(s"Success. Response: ${response.copy(entity = HttpEntity.Empty)}.")
            val index = response.headers.find(_.is("x-consul-index")).map(_.value.toLong)
            log.debug(s"New index: ${index}.")
            createRequest(uri, maxWait, index)
          }

      val init = b.add(initSource)
      val http = b.add(httpFlow)
      val merge = b.add(Merge[HttpRequest](2))
      val broadcast = b.add(Broadcast[HttpResponse](2))
      val outbound = b.add(outboundResponsesFlow)
      val feedback = b.add(feedbackResponsesFlow)

      // format: OFF
      init ~> merge ~> http     ~> broadcast ~> outbound
              merge <~ feedback <~ broadcast
      // format: ON

      SourceShape(outbound.out)
    })
  }

  private def createRequest(baseUri: Uri, maxWait: Duration, index: Option[Long]): HttpRequest = {
    HttpRequest(
      uri = baseUri.copy(
        rawQueryString = Some(s"wait=${maxWait.toSeconds}s&index=${index.map(_.toString).getOrElse("0")}")
      )
    )
  }
}
```

I think the docs could use some sections on stream resiliency and failure recovery in more complex cases such as this.

I think I'll dive into custom graph stages next, since they are the only code I've seen so far that has access to upstream completion/failure events.

**Comment by agemooij** [comment]
I hope my efforts at slowly clawing my way towards enlightenment provide some insight into the struggles of people trying to figure out how this stream stuff works :smile:

**Comment by ktoso** [comment]
Awesome research here, thanks for sharing it and sorry I wasn't able to comment in depth yet, a bit overloaded last week. Hope to investigate here this week :)

**Comment by agemooij** [comment]
Hi @ktoso . Any hints towards directions to take in my research. I'm hoping to dig a little deeper this weekend so if you have any ideas, I'd love to hear them and try them out.

**Comment by agemooij** [comment]
I have discovered `PoolInterfaceActor` and `PoolFlow`. Studying them now...

**Comment by ktoso** [comment]
Had some time now while wife was shopping ;)
The initial code looks pretty good I think its the rights direction. I'll need to get to a pc tough to give more detailed feedback :)

**Comment by agemooij** [comment]
Hi @ktoso and the rest of the akka team. I've been diving into the implementation of http core and streams and I'm very curious about the design decisions that went into the current design and about your ideas about the direction things are going.

In the current design, http connection management has been directly linked to stream materialization and there are no hooks at all in the API for dealing with events and state changes on the connection. The stream just stops and the surrounding code will have to detect this in some way, which is not entirely trivial since AFAIK there are no easy prebuilt stages for dealing with "normal" stream completion. 

This means that in order to build streams that deal with connection loss, transparently reconnecting, etc., you will need to break our of the akka-stream context and dive into the implementation layer and the underlying actors. 

This is exactly how the host connection pools in http core have been implemented, i.e. a Flow implemented by an actor that internally uses more actors to rematerialize nested connection Flows when they complete.

 Unfortunately a lot of that work is private and very deeply entwined with complex implementation details. I'm attempting to strip out and copy the parts I would need to implement a persistent, resilient long polling connection Source but a lot of those implementation details are still not entirely obvious to me.

I'm wondering whether this topic, i.e. exposing connection management in http core as a higher level abstraction, has been discussed in the team and whether there are plans to provide such a thing in the future.

**Comment by agemooij** [comment]
FYI: the current version of the long polling code I'm experimenting with can be found here: https://github.com/agemooij/stream-experiments/blob/master/src/main/scala/scalapenos/experiments/streams/LongPollingHttpClientUsingSingleConnection2.scala

Next step, strip out some of the `PoolInterfaceActor` implementation details in an attempt to get an http connection Flow that transparently reconnects (or find some way to implement this using a unique single-connection host connector pool per long polling operation, but then that warning in the Akka docs definitely needs to be rewritten 😄 )

**Comment by agemooij** [comment]
After writing that last bit in the above comment, I tested an implementation using a custom, non-shared pool configured to only allow on single connection and that seems to work, including resilience across connection failures.

It seems that as long as you make sure the pool is not used by anyone else, using a single-connection host pool is actually the best solution for long polling since it stops you from having to implement all the rematerialization stuff hidden behind the pool interface.

Latest implementation now here: https://github.com/agemooij/stream-experiments/blob/master/src/main/scala/scalapenos/experiments/streams/LongPollingHttpClient.scala

**Comment by ktoso** [comment]
I figured it's about time I spend a considerable chunk of time on this, to appreciate your effort here – I'm diving in now, thanks for keeping at it!

**Comment by ktoso** [comment]
So I've read through but need to give it a spin to notice exact semantics, some things that are missing you pointed out. API style actually is something we could provide - exacly such extension.

I also noted:
`                        nextRequest: HttpResponse ⇒ HttpRequest, // yeah, this makes a lot of sense, possibly a default could be identity (imagine stateful endpoint, like twitter stream)`

`      import s._ // avoid importing everything from system`

`          .collect { case Success(response) ⇒ response } // probably log failures though?`

`          .mapAsync(1)(response ⇒ response.entity.toStrict(5.seconds).map(strictEntity ⇒ response.copy(entity = strictEntity))) // we'd likely want to the toStrict and combine with "json streaming" (once i finally finish it)?`

`          .withAttributes(ActorAttributes.supervisionStrategy(Supervision.resumingDecider)) // TODO: turn into log-and-resume` supervision in its current form is not that good, not sure if this is very needed here, if possible working without it would be preferable

the materialized value to control it is obviously a key feature to add.

single-connection host pool likely makes sense for this scenario, I think agree, this way we don't impact anyone else; but will try to verify with others.

We'll meet with the team on monday and I hope to have a look together at this and how it could move forward btw.

Hope the comments some sense and we'll be back here soon :)

**Comment by ktoso** [comment]
I'll assign myself here to keep it on my radar

**Comment by jrudolph** [comment]
@agemooij how easy would it be to implement your use-case using `singleRequest` over a dedicated pool? Maybe that's the core abstraction that is missing?

**Comment by agemooij** [comment]
@jrudolph good idea. I think the main problem with using `singleRequest` is how to make sure that the pool used for the long polling connections is not shared with "normal" http client code to the same host/port. 

Some kind of way to make absolutely sure the pool is unique, like an optional name field in `ConnectionPoolSettings` would fix that.

If isolation can be guaranteed, then the remaining problem comes down to configuring the maximum number of pool connections for a situation in which connections get hogged for very long periods and the number of needed connections is very variable. Just setting the number to be pretty high (i.e. just guessing) would be perfectly acceptable to most users I guess.

**Comment by agemooij** [comment]
> I also noted:
`nextRequest: HttpResponse ⇒ HttpRequest, // yeah, this makes a lot of sense, possibly a default could be identity (imagine stateful endpoint, like twitter stream)`

Good idea. The default value should be `initialRequest` then, which requires splitting the argument list. The API then becomes:

```scala
  def longPollingSource(host: String, port: Int,
                        initialRequest: HttpRequest,
                        connectionSettings: ClientConnectionSettings = ClientConnectionSettings(system))
                       (nextRequest: HttpResponse ⇒ HttpRequest = _ => initialRequest)
                       (implicit m: Materializer): Source[HttpResponse, NotUsed] = {
```

> `.collect { case Success(response) ⇒ response } // probably log failures though?`

I'd log it on the feedback side, since the output side is only meant for reporting successfully received responses.

> `import s._ // avoid importing everything from system`

Is this a best practice I'm unaware of? What's the danger?

> `.mapAsync(1)(response ⇒ response.entity.toStrict(5.seconds).map(strictEntity ⇒ response.copy(entity = strictEntity))) // we'd likely want to the toStrict and combine with "json streaming" (once i finally finish it)?`

I'm not sure what you mean. Are you suggesting adding API for this on `HttpResponse`?

Having to always drain the response entities to prevent blocking the main flow is certainly inconvenient for building user-proof APIs, so I'd prefer some easier, safely bounded way to implement response transformation in cases such as this; i.e. you have a certain knowledge of the types of responses you will likely receive and you don't want to bubble up this responsibility to the API user.

**Comment by jrudolph** [comment]
> I think the main problem with using singleRequest is how to make sure that the pool used for the long polling connections is not shared with "normal" http client code to the same host/port.

I think using a dedicated single-connection pool is the right solution. The responsibility of the "pool" is the connection state handling.

The abstraction (not the functionality) which is currently missing is something which provides `singleRequest` given an arbitrary `Flow[(T, HttpRequest), (T, HttpResponse)]`.

This is something quite generic. Think about the burger chain where in the backend you have a pipeline of (burger stacking) cooks, basically a `Flow[Order, Burger]`. For organizational reasons, this simple linear pipeline may not be good enough, so the backend is implemented behind an interface of the kind `Flow[(OrderId, Order), (OrderId, Burger)]` (could be a simple, linear pipeline, or a number of on-duty cooks / pipelines waiting in a pool for more work which some algorithm scheduling pipelines intelligently (like reusing existing cooks/pipelines before getting cooks from the pool which have to dry themselves first, etc.)). On top of that the sales process is that the customer makes the order at the vending machine, getting a token of future completion in form of a receipt containing the order ID. So, we have several components, the actual backend implementation, the queueing / scheduling / multiplexing component, and an interface where you can issue orders to the queue, instantly receiving a token for future completion.

In akka-http, we have some implementations of those components but not abstraction that you could easily plug together.

**Comment by agemooij** [comment]
@jrudolph 👍  akka-http is still pretty low-level, especially the current client-side APIs.

Are #15909 and #16856 still being worked on? I guess this is (or should be) part of #16856, right?

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by asarkar** [comment]
For people like me who might stumble across this, https://github.com/akka/akka-http/issues/63 is this issue in akka-http.
