### ISSUE TITLE
Timeout-Access header always contains incorrect value "<function1>"

### ISSUE THREAD

**Issue by nartamonov** [akka/akka#20120]
Following path returns response "Timeout-Access = \<function1\>":

```scala
  path("test") {
    get {
      optionalHeaderValueByName("Timeout-Access") { timeout =>
        complete(s"Timeout-Access = ${timeout.get}")
      }
    }
  }
```

It's because [`TimeoutAccessImpl`](https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L309) does not override `toString` which inherited by default from `scala.Function1`.

**Comment by ktoso** [comment]
I'm not quite sure it should print everything it has inside it - it's mostly very internal things (and the entire HttpRequest etc).

I assume you saw it by printing the HttpRequest somewhere - which contains the Timeout-Access header, which contains the impl... 

I'd actually say that
1) we don't want to render internals of Timeout-Access - maybe just replace with "..."
and 2) perhaps we should even hide this header from being rendered, it is an implementation detail that we transmit it like that to user code.

**Comment by nartamonov** [comment]
@ktoso, ok, I understand. But how can I retrieve value of timeout from this header? According to [official documentation](http://doc.akka.io/docs/akka/2.4.2/scala/http/configuration.html), "the HTTP server layer attaches a `Timeout-Access` header to the request, which *enables programmatic customization of the timeout period and timeout response for each request individually*". What I want is to extract value of timeout from header to use it later in request processing. For example, to specify timeout when *ask*-ing some actor. headerValueByName() directive gives me 'String', not direct access to `TimeoutAccess` instance.

**Comment by ktoso** [comment]
The `Timeout-Access` header is more designed to control the timeout, not read it. So you're right that there's no clean way to access it currently. I agree it would be good to make this inspectable, even for debugging reasons etc, marking as triaged.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
