### ISSUE TITLE
Deprecate recoverWith and create two variants with repeating and non-repeating semantics

### ISSUE THREAD

**Issue by Falmarri** [akka/akka#20123]
Scala version 2.11.7 (OpenJDK 64-Bit Server VM, Java 1.8.0_74)
Akka 2.4.2

```
scala> 
Source.failed(
    new Exception("An original failure")
).recoverWith{ 
    case e => Source.single(10).concat(Source.failed(e))
}.runForeach(println)
res3: scala.concurrent.Future[akka.Done] = 
scala.concurrent.impl.Promise$DefaultPromise@127a7272

scala> 10
10
10
10
10
10
10
10
10
10
10
10
...
```

**Comment by drewhk** [comment]
Why is this a bug?

**Comment by ktoso** [comment]
Hm... it is weird, isn't it?

I'd expect:
`failed(ex) => no failure downstream since recovered => single(10) => the failure ex`

**Comment by drewhk** [comment]
it depends on the intended semantics. I am not sure what is the expected semantic here, is it to apply the recoverWith *every time*, or just once. The every time semantic is useful because for example it allows to implement reconnect style logic. I marked this as "new" until it is figured out what recoverWith should actually mean.

**Comment by drewhk** [comment]
It says in the doc:
"RecoverWith allows to switch to alternative Source on flow failure. **It will stay in effect after
a failure has been recovered so that each time there is a failure it is fed into the `pf` and a new
Source may be materialized.**"

**Comment by drewhk** [comment]
So it does what it advertises

**Comment by ktoso** [comment]
Huh whoa, I did not realise that's the semantics we have, missed reviewing that one maybe :-/
It is rather weird... The other one should be allowed as well IMO

**Comment by drewhk** [comment]
Why is it weird? The single recover is as simple as:

```scala
src.recover { case ex => Dummy }.filter(_ != Dummy).concat(recoverSrc)
```

While the recoverWith behavior cannot be expressed by built-in combinators.

**Comment by drewhk** [comment]
Hm, not exactly because above always concats the second source.

**Comment by drewhk** [comment]
Maybe we can add an additional parameter capping the restart count.

**Comment by ktoso** [comment]
> Maybe we can add an additional parameter capping the restart count.

Yeah (or play with naming). In general recoverWith for me is all about the Source inside - which could be another http call etc, and I'd want to retry only once etc.

**Comment by drewhk** [comment]
we cannot rename it

**Comment by ktoso** [comment]
sure, but we could `recoverOnceWith`, that is discoverable and highlights the difference between those two when ctrl-spacing through the combinators.

**Comment by rkuhn** [comment]
I must admit that I find the current semantics of `recoverWith` a little disturbing as well: for continuously retrying some Source I would prefer a combinator that did not require me to provide that Source twice (once before and once after the `recoverWith` word). This completely escaped my attention back then.

Is it conceivable that we might try to change this or not? `recoverWith` has a different meaning in prior usage (see for example Future and Try).

**Comment by drewhk** [comment]
We have to maintain binary compatibility now, so I don't think that this can be changed.

**Comment by ktoso** [comment]
Well, such change would be binary compatible. It would not be semantically the same though.
Question is, are we fixing bad behaviour "perceived bug" - let's do this, 
or is this "well, unexpected but documented"

I do lean towards the first actually, before causes more confusion / stays around for longer.

**Comment by drewhk** [comment]
> Well, such change would be binary compatible. It would not be semantically the same though.

That stretches the meaning of binary compatibility ;)

> Question is, are we fixing bad behaviour "perceived bug" - let's do this,

Is it bad behavior? It does what it documents. Btw the tests were also pretty explciit: https://github.com/akka/akka/pull/19648/files#diff-86ef837fd646270f44200babeb6559e8R86

**Comment by rkuhn** [comment]
While we are splitting hairs: binary compatibility promises only the absence of LinkageError (and is therefore not all that useful by itself).

But I agree that it might be a stretch to change semantics like that in a patch release. The proper solution to this ticket might be to deprecate `recoverWith` and introduce two replacements, one that is single-shot and one that repeats. The latter might want to be a Source instead of a FlowOps combinator.

**Comment by drewhk** [comment]
Well, technically the repeating version should be done for arbitrary graphs and called supervision ;) (and have some upper limit on restarts, absolute or windowed).

**Comment by rkuhn** [comment]
Yep, we already have a ticket for that :-)

**Comment by drewhk** [comment]
Ok, I triaged this ticket then,

**Comment by Falmarri** [comment]
How do you guys assign issues? Is this something I could/should issue a pull request for?

**Comment by ktoso** [comment]
Any ticket that is not being worked on (this isn't yet) is free to pick up and hack on it.
If you'd like to help out on this one that'd be great - thanks in advance. There will be some naming bikesheding I guess, otherwise it should be rather simple.

**Comment by viktorklang** [comment]
Keep recoverWith as-is and also introduce fallbackTo?

**Comment by patriknw** [comment]
@Falmarri looking forward to your contribution, thanks

**Comment by Falmarri** [comment]
@ktoso I think this test might be why this behavior is surprising.

```    
"terminate with exception if alternative source failed" in assertAllStagesStopped {
      Source(1 to 3).map { a ⇒ if (a == 3) throw new IndexOutOfBoundsException() else a }
        .recoverWith {
          case t: IndexOutOfBoundsException ⇒
            Source(List(11, 22)).map(m ⇒ if (m == 22) throw ex else m)
        }.runWith(TestSink.probe[Int])
        .request(2)
        .expectNextN(List(1, 2))
        .request(1)
        .expectNextN(List(11))
        .request(1)
        .expectError(ex)
    }
```

That's pretty misleading imo. The reason that the stream terminates is because it's not matched by the partial function, not because the alternative source fails.

**Comment by Falmarri** [comment]
So I kept recoverWith undeprecated, and changed the underlying class to support retry attempts. https://github.com/akka/akka/pull/20137

**Comment by ktoso** [comment]
Slipping to 2.4.4
