### ISSUE TITLE
add Sink.dynamic and Flow.dynamic

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#20129]
These should create the real Sink/Flow upon receiving the first element. There should be async versions as well.

**Comment by viktorklang** [comment]
IMO, terrible name though.
Alternatives?

**Comment by rkuhn** [comment]
Let the bike-shedding begin! We need names for the following signatures:
~~~scala
object Sink {
  def x1[T, M](f: T => Sink[T, M]): Sink[T, Future[M]]
  def x2[T, M](f: T => Sink[T, Future[M]]): Sink[T, Future[M]]
  def y1[T, M](f: T => Future[Sink[T, M]]): Sink[T, Future[M]]
  def y2[T, M](f: T => Future[Sink[T, Future[M]]]): Sink[T, Future[M]]
}
~~~
and equivalent for Flow. We might compress this to one name by using the magnet pattern; this has pros and cons, obviously.

**Comment by viktorklang** [comment]
what about lazy[Sink|Flow|Source] and lazy[Sink|Flow|Source]Async?

**Comment by viktorklang** [comment]
Btw, does that signature make sense? What happens for empty and/or failed streams? (where there is no initial element, which I presume that T is?)

**Comment by rkuhn** [comment]
I think it is reasonable to not create a Sink if there are no elements. An alternative would be to have a second function that is invoked in these cases (of type `Try[Done] => Unit`).

**Comment by patriknw** [comment]
do we need all those variants? would it be enough with only the most powerful?

**Comment by viktorklang** [comment]
@patriknw Seconded, let's try to expand API surface by need rather than by greed. :)

**Comment by rkuhn** [comment]
Yes, that’s a possibility; since it may not be immediately obvious, the most powerful one is y1.

**Comment by viktorklang** [comment]
@rkuhn yep. flatMap(identity) or flatten (2.12.x) in case of y2 use-cases

**Comment by agolubev** [comment]
Taking this task.

**Comment by patriknw** [comment]
great, @agolubev
