### ISSUE TITLE
Missing 'markdown' extension in MediaType text/markdown entry

### ISSUE THREAD

**Issue by venilnoronha** [akka/akka#20138]
Currently, only `md` extension is available with the `text/markdown` `MediaType` entry. The RFC document however specifies `markdown` also as an alternate extension.

**Comment by ktoso** [comment]
Already resolved, see: https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala#L428

Thanks for noticing :)

**Comment by ktoso** [comment]
Ah, of course you're right about that one, sorry I didn't notice :)
Thanks again!
