### ISSUE TITLE
ShardRegion.GetClusterShardingStats not available in Java API

### ISSUE THREAD

**Issue by pkubowicz** [akka/akka#20132]
`GetClusterShardingStats` is the only kind of `ShardRegionQuery` that is not available in the Java API, although it seems that it should be: its reply (`ClusterShardingStats`) contains a method done exclusively for the Java API.

A method similar to `getCurrentRegionsInstance` should be added to ShardRegion so that Java users will be able to create instances of `GetClusterShardingStats`.

**Comment by johanandren** [comment]
`GetClusterShardingStats` is a regular class, so the API from Java is the same as that from Scala.

**Comment by johanandren** [comment]
(the reason some of the other messages has methods is that they are singletons, which leads to a weird name if accessed from Java)

**Comment by ktoso** [comment]
Simply do `new GetClusterShardingStats(new FiniteDuration(10, TimeUnit.SECONDS))`, it does not need Java API. The reason `CurrentRegions` has a getter like that is because it is a singleton object - which otherwise one would not be able to access.

**Comment by ktoso** [comment]
Meh, Johan was quicker to explain :)

**Comment by johanandren** [comment]
Given this explanatory babble I will close the ticket.
