### ISSUE TITLE
Akka Streams: pool of workers doesn't work as expected when auto-fusing enabled

### ISSUE THREAD

**Issue by Mihai238** [akka/akka#20146]
As described in [akka streams documentation](http://doc.akka.io/docs/akka/2.4.2/scala/stream/stream-cookbook.html#Balancing_jobs_to_a_fixed_pool_of_workers) I tried to create a pool of workers (flows):

    def balancer[In, Out](worker: Flow[In, Out, NotUsed], workerCount: Int): Flow[In, Out, NotUsed] = {
        import GraphDSL.Implicits._
    
        Flow.fromGraph(GraphDSL.create() { implicit b =>
          val balancer = b.add(Balance[In](workerCount))
          val merge = b.add(Merge[Out](workerCount))
    
          for (_ <- 1 to workerCount) {
            balancer ~> worker ~> merge
          }
          FlowShape(balancer.in, merge.out)
        })
      }

then I used this function to run a flow in parallel: 

    def main(args: Array[String]) {
        val system = ActorSystem()
        implicit val mat = ActorMaterializer.create(system)
    
        val flow = Flow[Int].map(e => {
          println(e)
          Thread.sleep(1000) // 1 second
          e
        })
    
        Source(Range.apply(1, 10).toList)
          .via(balancer(flow, 3))
          .runForeach(e => {})
      }

I get the expected output `1, 2, 3, 4, 5, 6, 7, 8, 9` but the numbers appear at a rate 1 per second (no parallelism).

Without auto-fusing I get the desired behavior (flow is executing in parallel) but I cannot find any way to specify async boundaries via `.async` to get the same result.

**Comment by drewhk** [comment]
You need to put the `.async` on the worker flow. This will put a boundary around the worker, so each worker flow instance will be a dedicated actor.

**Comment by drewhk** [comment]
the docs on this were outdated but they will be updated in 2.4.3

**Comment by drewhk** [comment]
To clarify, your code will look like:

```
def main(args: Array[String]) {
    val system = ActorSystem()
    implicit val mat = ActorMaterializer.create(system)

    val flow = Flow[Int].map(e => {
      println(e)
      Thread.sleep(1000) // 1 second
      e
    }).async

    Source(Range.apply(1, 10).toList)
      .via(balancer(flow, 3))
      .runForeach(e => {})
  }
```

**Comment by TrustNoOne** [comment]
@drewhk I tried that but that behaviour doesn't change, it keeps printing 1 2 3 4 5 6 7 8 9 10 every second in order

**Comment by drewhk** [comment]
Tried it out and it really does not print what is expected. I elevate this to bug.

**Comment by drewhk** [comment]
AAAH, I know now. So if you make the worker flow async then it will gain a buffer. The default size is 16 for that buffer. Now balance will try to send messages to those stages that have buffer space available, but in this case all the messages fit in that buffer space of 16, i.e. balance sends all the numbers to a single worker. Try out with a larger number and it will work as expected (balancing kicks in as the buffers start to get full). Alternatively, you can set the workers buffer size to one:`.async.addAttributes(Attributes.inputBuffer(1, 1))`

**Comment by TrustNoOne** [comment]
brilliant, I'll try to remember there's buffering involved in async stages

thanks for the clarification!

**Comment by Mihai238** [comment]
That was tricky to find out by myself. Thanks a lot for explanation!
