### ISSUE TITLE
HttpService in JavaDSL uses raw bind instead of bindAndHandleWith

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20145]
Btw, why is there even such a base class like HttpApp? /cc @ktoso

**Comment by ktoso** [comment]
I think we may want to deprecate that class actually with the new DSL coming now.
I'll assign this to myself to check if we can remove HttpApp (it's proven to be confusing to people on twitter, as it's again something different than scaladsl)

**Comment by ktoso** [comment]
Closing since new JavaDSL dropped this class
