### ISSUE TITLE
takeWithin should fail the stream instead of completing it after the timeout

### ISSUE THREAD

**Issue by Falmarri** [akka/akka#20147]
```
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Sink, Source}
import scala.concurrent.duration._
implicit val system = ActorSystem("system")
implicit val materializer: ActorMaterializer = ActorMaterializer()
import system.dispatcher

Source.single(1).delay(30 seconds).takeWithin(5 seconds).runWith(Sink.ignore).onComplete{println}

scala> Success(Done)
```

The docs do imply that there's no error, but imo they're not clear.

>Terminate processing (and cancel the upstream publisher) after the given
>   * duration.

And regardless, there should either be an option or another method that fails the stream after the timeout instead of completing it.

**Comment by drewhk** [comment]
There is a `completionTimeout` which does what you need. TakeWithin is a sister of take as it does not fail anything it just limits the number of outputted elements whether in count or time (and can be of course combined to limit both).

**Comment by Falmarri** [comment]
@drewhk maybe the doc language could be a little bit more clear? I'm not sure that "Terminate" is the best word. I would have expected "complete" instead.

**Comment by Falmarri** [comment]
@drewhk also `completionTimeout` doesn't do the same thing. I don't want to fail if the stream hasn't completed in that amount of time. I want it to fail if the first element hasn't been seen in that amount of time.

**Comment by drewhk** [comment]
> I'm not sure that "Terminate" is the best word. I would have expected "complete" instead.

You can submit a PR ;)

> also completionTimeout doesn't do the same thing. I don't want to fail if the stream hasn't completed in that amount of time. 

Then what you need has nothing to do with a failing version of TakeWithin.

> I want it to fail if the first element hasn't been seen in that amount of time.

Thankfully we have that, too: http://doc.akka.io/api/akka/2.4.2/index.html#akka.stream.scaladsl.FlowOps@initialTimeout(timeout:scala.concurrent.duration.FiniteDuration):FlowOps.this.Repr[Out]
