### ISSUE TITLE
[Feature] DistributedData DataDeleted msg should also provide requestor context

### ISSUE THREAD

**Issue by clockfly** [akka/akka#20140]
**Current interface:**

```
DataDeleted(key: Key)
DeleteSuccess(key: Key)
ReplicationDeleteFailure(key: Key)
```

**Desired interface:**

```
DataDeleted(key: Key, request: Some[Any])
DeleteSuccess(key: Key, request: Some[Any])
ReplicationDeleteFailure(key: Key, request: Some[Any])
```

So  that we can response to the correct client without using actor ask pattern.

Sean

**Comment by patriknw** [comment]
I agree, that must be an oversight. It will a bit difficult to add it in a binary backwards compatible way, but if we can't find a reasonable solution for that we are allowed to break binary compatibility here, because it's an experimental module.

Would you like to contribute with a pull request?

**Comment by clockfly** [comment]
Sure, I can. Thanks @patriknw

**Comment by patriknw** [comment]
great, thank you

**Comment by filosganga** [comment]
@clockfly are you actively working on that?

**Comment by patriknw** [comment]
The [PR](https://github.com/akka/akka/pull/20527) for this stalled, i.e. contributions are still welcome.

**Comment by patriknw** [comment]
let's do this for 2.5.0, since it's a small api change

**Comment by inakov** [comment]
OK guys, I'm taking this one. @patriknw are you have any suggestions how to preserve the backwards compatibility? I think the clockfly's suggestion is good, because Get and Update already done this way and the API will be consistent.

**Comment by patriknw** [comment]
Thanks for taking it. We can do this small change of the API in Akka 2.5 (master branch) without keeping backwards compatibility.

**Comment by inakov** [comment]
@patriknw I made the change for the delete command. I also added a new msg for the subscribers this way both API are going to be separate and cleaner. I think the request context is inapplicable for the subscribers. If you agree with my changes I'm going to update the doc and create a PR.

**Comment by patriknw** [comment]
Sounds good, please PR and I comment on details after the holidays.

**Comment by inakov** [comment]
PR number is #22068.
