### ISSUE TITLE
Make sure starting an Https server is well documented for Java DSL too

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20154]
See this discussion: https://twitter.com/ktosopl/status/714725071206617091?cn=ZmF2b3JpdGU%3D&refsrc=email

Seems `HttpApp` is somewhat hurting us and concealing that it's actually pretty similar to Scala DSL.
This should be done after new DSL merged; Perhaps deprecating HttpApp?

**Comment by jrudolph** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
