### ISSUE TITLE
If-None-Match header is parsed as RawHeader

### ISSUE THREAD

**Issue by akiradeveloper** [akka/akka#20151]
When I send a GET request with "If-None-Match" header, the server parses it as `RawHeader("if-none-match", xxx)` and then failed to match at

```scala
        def step3(): Route =
          header[`If-None-Match`] match {
            case Some(`If-None-Match`(inm)) if eTag.isDefined ⇒
              if (!matchesRange(eTag.get, inm, weakComparison = true)) step5()
              else if (isGetOrHead) complete304() else complete412()
            case None ⇒ step4()
          }
```

I think it should be Some case matched but None actually.

This is because it expects not RawHeader but `If-None-Match` Header type.

What I see in WireShark is:
```
If-None-Match: 769942be3bbfa7ba03fdac0de564673e\r\n
```

What I see in IntelliJ debugger (after Akka-HTTP's parsing) is:
```
HttpRequest(HttpMethod(GET),http://localhost:10946/a.b/myobj.txt,List(Host: localhost:10946, if-none-match: 769942be3bbfa7ba03fdac0de564673e, authorization: AWS BCDEFGHIJKLMNOPQRSTA:vN6UCKnuPCpN7ZaYLHK6IgqgV+Q=, user-agent: aws-sdk-java/1.10.49 Mac_OS_X/10.10 Java_HotSpot(TM)_64-Bit_Server_VM/25.45-b02/1.8.0_45, Date: Mon, 28 Mar 2016 12:58:51 GMT, Connection: Keep-Alive, Timeout-Access: <function1>),HttpEntity.Strict(application/octet-stream,ByteString()),HttpProtocol(HTTP/1.1))
```

I reported this as a particular case because I don't know if more general bug report is already raised. Sorry if there is more general one.

**Comment by ktoso** [comment]
Where did you get the `header` method from? It's not one of the directives: http://doc.akka.io/docs/akka/2.4.2/scala/http/routing-dsl/directives/header-directives/index.html

You should use the above mentioned directives for extracting values in a route, i.e. these:

- headerValue
- headerValueByName
- headerValueByType
- headerValuePF
- optionalHeaderValue
- optionalHeaderValueByName
- optionalHeaderValueByType
- optionalHeaderValuePF

In your case, see `headerValueByType` :)

**Comment by ktoso** [comment]
There is a `header` defined in the http testkit, aren't you ending up using that one by accident?

**Comment by akiradeveloper** [comment]
@ktoso  I should have said that I am using `conditional` directive. I didn't extract the header by any one of the methods but the directive directly refers to the HttpRequest object that was parsed by akka-http.

**Comment by ktoso** [comment]
Could you post a more complete example then? I'm not sure I see how you're combining things, it certainly looks a bit weird so far.

**Comment by akiradeveloper** [comment]
@ktoso The complete code is here: https://github.com/akiradeveloper/akashic-storage . I am not writing a sample program to hit this problem.

I am using `conditional` in the `service.GetObject`. The particular part of the code is:

```scala
      conditional(EntityTag(meta.eTag), lastModified) {
        complete(StatusCodes.OK, headers, HttpEntity.Default(ct, filePath.getAttr.length, filePath.getSource(1 << 20)))
      }
```

eTag and lastModified is type-checked and certainly correct when I see it on debugger.

I found this bug when I am writing this test (it's ignored because it fails):

```scala
  ignore("conditional get test") { p =>
    import p._
    client.createBucket("a.b")
    val f = getTestFile("test.txt")
    val putRes = client.putObject("a.b", "myobj.txt", f)

    val get = new GetObjectRequest("a.b", "myobj.txt")
      .withNonmatchingETagConstraint(putRes.getETag)
    try {
      client.getObject(get)
      assert(false)
    } catch {
      case _: Throwable =>
    }
  }
```

The client in this test certainly issues `If-None-Match` as I saw in the WireShark but when it's reached to `conditional` after parsing. It's RawHeader.

**Comment by akiradeveloper** [comment]
@ktoso I found I am breaking this rule

```scala
   * Note: if you want to combine this directive with `conditional(...)` you need to put
   * it on the *inside* of the `conditional(...)` directive, i.e. `conditional(...)` must be
   * on a higher level in your route structure in order to function correctly.
```

I am putting withRangeSupport ahead of conditional. Why isn't this allowed?

**Comment by 2beaucoup** [comment]
Hi @akiradeveloper. Parsing `If-None-Match` headers is tested [here](https://github.com/akka/akka/blob/6d3bb94d091d239a34c6de0d5b418fee2db14bc5/akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala#L304-L310). Maybe you can play around with your own values and see if it still succeeds. Do you see any illegal header warnings in the logs?

@ktoso `header[...]` is defined on `HttpMessage` and is accessible because of `import request._`. It seems to work for the other header types.

**Comment by ktoso** [comment]
> @ktoso header[...] is defined on HttpMessage and is accessible because of import request._. It seems to work for the other header types.

Ah that one, yeah we got that one; such imports mislead when reviewing a lot... 

I'll mark this issue as triaged, will need to look deeper into it than just from the top of my head. Thanks in advance for any more details @akiradeveloper

**Comment by akiradeveloper** [comment]
@2beaucoup I found a illegal request header log!

```
7408  20160329 17:10:16.696 [akashic-storage-akka.actor.default-dispatcher-2] WARN  akka.actor.ActorSystemImpl [Slf4jLogger.scala:76] - Illegal request header: Illegal 'if-none-match' header: Invalid input '7', expected ws or entity-tag (line 1, column 1): 769942be3bbfa7ba03fdac0de564673e
```

But the WireShark actually tells me If-None-Match is in a correct form.

<img width="874" alt="2016-03-29 17 11 49" src="https://cloud.githubusercontent.com/assets/785824/14101753/64ee7de4-f5d1-11e5-8269-2e730fad4bf7.png">

So, maybe the error message is due to the lack of double quotes in the header value?

```
Invalid input '7', expected ws or entity-tag (line 1, column 1): 
```

**Comment by akiradeveloper** [comment]
I changed the etag from

```
      .withNonmatchingETagConstraint(putRes.getETag)
```

to

```
      .withNonmatchingETagConstraint(s""""${putRes.getETag}"""")
```

then the parsing is OK! Thanks!

**Comment by akiradeveloper** [comment]
This is solved and I will close

**Comment by ktoso** [comment]
Hah yeah indeed, `"` are required as per the spec.
Glad you found that, happy hakking.

**Comment by 2beaucoup** [comment]
:+1:

**Comment by kajmagnus** [comment]
Better spec that clearly states that `"` are required:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match#Syntax

 (in the w3.org the quotes are just in a paragraph entitled *Example: ...*, felt a bit unclear to me)
