### ISSUE TITLE
Document http server shutdown semantics in low level docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20177]
We should have an explicit section about shutting down semantics.
Remember that we have graceful shutdown (doesn't kill connections) by default and by design currently.
The other one is `shutdownNow` which we do not have nowadays but can be emulated with KillSwitch-es.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
