### ISSUE TITLE
Manual HEAD handling and content length check in akka-http

### ISSUE THREAD

**Issue by TimothyKlim** [akka/akka#20182]
Hello hAkkers,
I can't manually handle response for `HEAD` request with custom content length and empty source because of `CheckContentLengthTransformer `.

```scala
val route = head {
    complete(HttpEntity.Default(
      ContentTypes.`application/octet-stream`,
      12345L,
      Source.empty
    ))
  }
```

In akka sources ( https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala#L237-L241 ), data length verified through CheckContentLengthTransformer with content length as an argument. Source.empty will throw an exception, with Source.maybe client will receive headers and wait for body until akka streams throw an exception No elements passed.

Gitter log of discussion: [March 30, 2016 2:07 PM](https://gitter.im/akka/akka?at=56fbb38c76b6f9de194c7348)

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by pjazdzewski1990** [comment]
I'm considering trying to squash this bug as community contrib, but I can't reproduce it.
If I understand the issue above - when manually completing a head request, an exception is thrown. 
I wrote a small test (starting in the current `master` branch) to reproduce the issue:
```
"head" should {
    val headRoute = head {
      complete(HttpEntity.Default(
        ContentTypes.`application/octet-stream`,
        12345L,
        Source.empty
      ))
    }
    "allow manual complete" in {
      Head() ~> headRoute ~> check {
        status shouldEqual StatusCodes.OK
      }
    }
  }
```
It works fine. Is it possible that it was fixed since it was reported? Or am I missing something here? cc: @TimothyKlim

**Comment by TimothyKlim** [comment]
@pjazdzewski1990 Looks like this already fixed in akka 2.4.7 (triggered in 2.4.2).

Thanks!

**Comment by ktoso** [comment]
Thanks for checking both @TimothyKlim and @pjazdzewski1990!
I think it would be nice to include a specific test for it as you did here @pjazdzewski1990.
Would you be able to PR it?

// It's a very quick test, so I'd rather have it than not, even if tested on a different layer already

**Comment by pjazdzewski1990** [comment]
@ktoso Sure. Give me a sec. I will open a PR today
