### ISSUE TITLE
Materializer used for cached connection pools should be configurable

### ISSUE THREAD

**Issue by samueltardieu** [akka/akka#20188]
(applicable after #20082 is merged, in the meantime the first materializer provided by the user is used for a cached connection pool even if it terminates early, causing the cached pool and future instances of it to fail forever)

The materializer used to create cached connection pools should be configurable.

**Comment by samueltardieu** [comment]
This is a followup to #20032.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
