### ISSUE TITLE
Documentation for `getFromDirectory`is misleading

### ISSUE THREAD

**Issue by mlangc** [akka/akka#20186]
The examples in the documentation of `Directives.getFromDirectory` and `Directives.getFromResourceDirectory` don't work as they are. They should be changed to use `pathPrefix` instead of `path`, that is
```scala
val route =
  pathPrefix("examples") {
    getFromResourceDirectory("/examples")
  }
```
instead of 
```scala
val route =
  path("examples") {
    getFromResourceDirectory("/examples")
  }
```

**Comment by poojadshende** [comment]
Hi Matthias,

I am working on this issue. However, I am not able to find section in java or scala documentaion in which below code is present 

val route =
  path("examples") {
    getFromResourceDirectory("/examples")
  }

Thank You,
Pooja

**Comment by mlangc** [comment]
Take a look [here](http://doc.akka.io/docs/akka/2.4.3/scala/http/routing-dsl/directives/file-and-resource-directives/getFromDirectory.html#getfromdirectory) and [here](http://doc.akka.io/docs/akka/2.4.3/scala/http/routing-dsl/directives/file-and-resource-directives/getFromResourceDirectory.html#getfromresourcedirectory).

**Comment by ktoso** [comment]
Thanks, good fix!
