### ISSUE TITLE
Why we cannot access Content-Length header via HttpResponse.headers ?

### ISSUE THREAD

**Issue by YoEight** [akka/akka#20183]
Greetings, 

As the title says it, we're currently unable to access `Content-Length` header through `HttpResponse.headers`. Is there a reason for this ?

Here the code where `akka-http` decided to not add it => https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala#L146

I'm willing to contribute a patch if it's only a mistyping

Cheers

**Comment by 2beaucoup** [comment]
The line you linked just ignores duplicated `Content-Length` headers. What you can see here is that it's not added to the list of headers in both cases but is "consumed" by `parseEntity` instead.

The reason for this is explained [here](http://doc.akka.io/docs/akka/2.4.2/scala/http/common/http-model.html#http-headers):
> The Content-Type of an HTTP message is modeled as the contentType field of the HttpEntity. The Content-Type header therefore doesn't appear in the headers sequence of a message.

**Comment by YoEight** [comment]
I'm sorry but I kindly disagree. That isn't remotely a good a reason and here an example. If you interact with WebHDFS, and you want to read a big file, you will need do do several request (passing the offset accordingly of course). In order to increment the offset correctly, you need to know what was the response `Content-Length` hadoop sent you back.

I don't think it's a good call to assume too much on how an user use an lib, specially on trival things like this.

Thanks for time

**Comment by 2beaucoup** [comment]
The linked doc section explains how you can read the length of the content anyway via the entity.

**Comment by YoEight** [comment]
Yes, I saw it but unfortunately in my case, it's always returning `None` while `Content-Length` header is present.

**Comment by 2beaucoup** [comment]
Then let's find out why. ;) Can you share the complete response headers?

**Comment by YoEight** [comment]
Sure ! Thanks for taking the time

```
```

**Comment by YoEight** [comment]
Sure ! Thanks for taking the time :-)

```
$ curl -i "http://haestrom:50075/webhdfs/v1/license.txt?op=OPEN&namenoderpcaddress=localhost:9000&length=10&offset=0"
HTTP/1.1 200 OK
Cache-Control: no-cache
Expires: Wed, 30 Mar 2016 13:50:14 GMT
Date: Wed, 30 Mar 2016 13:50:14 GMT
Pragma: no-cache
Expires: Wed, 30 Mar 2016 13:50:14 GMT
Date: Wed, 30 Mar 2016 13:50:14 GMT
Pragma: no-cache
Content-Length: 10
Content-Type: application/octet-stream
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Server: Jetty(6.1.26)
```

**Comment by 2beaucoup** [comment]
Mmh, from the headers I dont' see why the content length isn't available.

What's the type of the entity in this case? You can use `toStrict` to have the length available but that doesn't scale for large payloads.

Having said that it's in general not a good idea to rely on the info in the header which is explained here: https://github.com/akka/akka/issues/17680#issuecomment-109771792

The correct way seems to manually count the length while processing the (possibly non-strict) entity stream. For example see `FileIO.toFile` which provides an `IOResult`.

**Comment by YoEight** [comment]
Thanks for your time and advises, I close the issue then
