### ISSUE TITLE
Http client stalls when response type is not matching expected one

### ISSUE THREAD

**Issue by lpiepiora** [akka/akka#20192]
When executing following piece of code:

```scala
implicit val system = ActorSystem("Sys")
implicit val materializer = ActorMaterializer()
implicit val executor = system.dispatcher

val source = Source(1 to 100)
val sink = Sink.foreach(println)

case class Example(x: String)
implicit val exampleFormat = jsonFormat1(Example)

source.mapAsync(1) { x =>
  Http().singleRequest(HttpRequest(uri = "http://example.com")).map { x =>
    Unmarshal(x).to[Example]
  }
}.runWith(sink)
```

The client will stall after couple of requests. The reason for that seems to be that the `Unmarshal` throws an exception without consuming the content. I am not sure, if this is a bug, because although it seems counter intuitive it is somewhat consistent with the documented behaviour, meaning if the entity is not consumed the connection will stall.

I can workaround this via changing the code to something like that:

```scala
Unmarshal(x).to[Example].recoverWith {
  case ex =>
    x.entity.dataBytes.runWith(Sink.ignore).flatMap(_ => Future.failed(ex))
}
```

Which will consume the response. I think if this is normal behaviour it should be explicitly documented somewhere in the  (unless it is and I overlooked it).

**Comment by ktoso** [comment]
Thanks for reporting, we should improve the situation here definitely.

**Comment by ktoso** [comment]
Another workaround would be to:

```scala
response => Unmarshal(response.entity.dataBytes.runFold(ByteString.empty)(_ ++ _)).to[Example]
```

or something in that direction

**Comment by ktoso** [comment]
Note to self: should the marshalling infra provide a way to "consume if unable to unmarshal" because we might end up stalling connections otherwise

**Comment by chessman** [comment]
I have a similar situation with unsuccessful requests:
```scala
    request(...).flatMap({
      case HttpResponse(StatusCodes.OK, _, entity, _) => Unmarshal(entity).to[...]
      case HttpResponse(code, _, _, _) => throw new Error(code)
    })
```
After a few non-200 responses the client stalls. The workaround is:
```scala
    request(...).flatMap({
      case HttpResponse(StatusCodes.OK, _, entity, _) => Unmarshal(entity).to[...]
      case HttpResponse(code, _, entity, _) => {
        entity.dataBytes.runFold(ByteString.empty)(_ ++ _)
        throw new Error(...)
      }
    })
```

This example follows the [official documentation](http://doc.akka.io/docs/akka/2.4.7/scala/http/client-side/request-level.html) (but there is exception instead of log).

**Comment by ktoso** [comment]
I realised our examples show "the wrong way", I'll fix the examples.
The automatic draining feature is something we don't yet have, but will have, please track this issue for it: https://github.com/akka/akka/issues/18716 https://github.com/akka/akka/issues/18540

I'll update our docs to resolve this specific issue right now though.

**Comment by ktoso** [comment]
Please see the documentation merged in https://github.com/akka/akka/issues/20852
