### ISSUE TITLE
Directive which allows asynchronous calls via a CircuitBreaker

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20198]
Basically something like this:

```scala
path("/path") {
   post {
      handleAsyncWithBreaker(circuitBreaker) {
        ... // async handling here
      }
   }
}
```

**Comment by ktoso** [comment]
Sounds good. Some notes in case someone wants to take a swing at it: 
when breaker open we should immediately reply with something like EnchanceYourCalm (configurable via implicit value). Also remember to drain incoming databytes if rejecting because open circuit breaker.

**Comment by drewhk** [comment]
marked it for external contrib if someone is interested.
