### ISSUE TITLE
Compressability Java Type

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20199]
Follow up to https://github.com/akka/akka/issues/19976 which added API but did not change the types.
We should add javadsl versions of `Compressability` and make the scaladsl extend the javadsl

**Comment by lolski** [comment]
Referring to https://github.com/akka/akka/pull/20181#discussion_r57873215, we'll need to reorder `customBinary` Scala DSL too. WDYT?

**Comment by ktoso** [comment]
We can't just reorder param order because binary compatibility.
We'll need to add a new method if we need to change arg lists

**Comment by lolski** [comment]
So with that in mind we'll need to keep the old methods that accepts `boolean compressible`, am I correct?

**Comment by lolski** [comment]
@ktoso PR submitted. Please have a look :)

**Comment by ktoso** [comment]
I'm on it :-)
