### ISSUE TITLE
change semantics of PreStart signal in Akka Typed

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#20205]
Given that it is even more of a passive hook than in untyped actors, the outcome of processing the PreStart message should not have any effect on the lifecycle status of the actor. This means that a failure in PreStart that resulted in the actor being stopped should also trigger PostStop.

The semantics of `Actor.preStart()` shall remain the same as it is now: it is regarded as part of the transition into “created” status, meaning that failures do prevent `postStop()` from being invoked.

**Comment by johanandren** [comment]
I'll close this as we are removing `PreStart`
