### ISSUE TITLE
Should PersistentFSM trigger transition handlers on startWith() call?

### ISSUE THREAD

**Issue by abesanderson** [akka/akka#20204]
I noticed while investigating something in one of my persistent actors that the transition handlers are not called when replaying the journal of StateChangeEvent's.  I may be able to rework the code to make it a bit more resilient to this, at the moment I'm relying on the transition to create some child actors which do some process that is not really related to the state of the parent.  I thought about using the transition to send the parent itself a message, but then I would need to store that change also as a domain event, and it seems a bit complex for the use case.  Not sure if the transition triggering on replay is a good idea, or I'm just avoiding the storage of domain state with the child actors.

**Comment by patriknw** [comment]
@leonidb what is your opinion?

**Comment by leonidb** [comment]
I think transition handlers are more suitable for handling side effects and shouldn't be replayed during recovery.
@abesanderson  can you figure out what actions should be done based on the recovered state data? If so, you can start the child actors in  ```onRecoveryCompleted``` method.

**Comment by abesanderson** [comment]
@leonidb onRecoveryCompleted completely spaced me for some reason.  I was doing some work arounds for when I got a SnapshotOffer already, but the case where no snapshot existed was choking up.  Thanks very much, I think for the specific case I had, I can handle it by inspecting state after recovery.

**Comment by leonidb** [comment]
@abesanderson glad I was able to help!

**Comment by abesanderson** [comment]
I do have another thought, though, related to working with PersistentFSM.  It would be nice to have a hook to call for onSnapshotOffer that implementors of PersistentFSM can call.  With PersistentActor it's not as bad, since the implementors are expected to define receiveCommand/receiveRecover, but in the fsm version, these are a bit more hidden.

**Comment by leonidb** [comment]
@abesanderson it would be interesting to get your feedback on using snapshots with PersistentFSM. You should probably open a separate issue for that.

**Comment by patriknw** [comment]
we can close this, right?
