### ISSUE TITLE
doc not generated under python3.5

### ISSUE THREAD

**Issue by kpbochenek** [akka/akka#20210]
As stated in title.

Stacktrack with logLevel := debug

`akka > sphinx:generateHtml`

```
[debug] Exception occurred:
[debug]   File "~/github/akka/akka-docs/_sphinx/exts/includecode.py", line 118, in run
[debug]     tabshift = min(tabcounts) if tabcounts else 0
[debug] ValueError: min() arg is an empty sequence
[debug] The full traceback has been saved in /tmp/sphinx-err-lyg_y3aa.log, if you want to report the issue to the developers.
```

For testing I removed condition and left 0, doc was generated just fine.

**Comment by ktoso** [comment]
Does the fix you did yield proper docs?
Could you contribute it as PR?

Thanks!

**Comment by kpbochenek** [comment]
It doesn't unfortunately.
This code should as I can see remove indentation if all lines have it but it is not happening.

but I will figure it out in a minute :)
