### ISSUE TITLE
Disabling per-connection SNI doesn't work as of akka 2.4.5

### ISSUE THREAD

**Issue by nodefactory-bk** [akka/akka#20214]
Hi!

In some cases I need to disable SNI entirely when using akka-http.
In 2.4.2 I used this code to create a custom connection context:
```
  protected def httpsContext: HttpsConnectionContext =
  {
    val ctx = sslContext
    val params = ctx.getDefaultSSLParameters

    /* Disable SNI if asked to */
    if (!sniEnabled) {
      params.setServerNames(Nil.asJava)
      params.setSNIMatchers(Nil.asJava)
    }

     new HttpsConnectionContext(ctx, sslParameters = Some(params))
   }
```

However as of 2.4.3 this no longer works and gives an "andshake alert:  unrecognized_name" error.

It seems this is due to https://github.com/akka/akka/pull/19858
that overrides the serverNames that I have set.

This seems like an unintended consequence, or am I missing something?

**Comment by ktoso** [comment]
It could be an unintended consequence, thanks for reporting.
I guess this could be done via ssl-config hm, will look into it, thanks!

**Comment by nodefactory-bk** [comment]
Is there a way to work around it for the time being?

**Comment by ktoso** [comment]
Staying on 2.4.2, I'll dig into this one soon and maybe find another workaround,
but having that said 2.4.4 will be released rather soon so that'll want to have this fixed.

**Comment by ktoso** [comment]
I'd like to confirm your use case – why do you need to disable SNI?
Looking into it in the mean time..

**Comment by nodefactory-bk** [comment]
Because some servers under some circumstances (bad config, whatever) respond with unrecognized_name WARNING when the servername sent via SNI doesn't match what the server thinks it should be.

Unfortunately java treats this as an error although the server just sends a warning and bails out and the java people refuse to fix this:
  http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7127374

This is my  use case, however there might be other reasons to want to disable SNI. 
For me personally, fixing the handling of unrecognized_name would be enough but I still think it's a good idea to allow users to disable SNI for certain requests/connections if they need it for some other reason.

**Comment by ktoso** [comment]
The thing is, I also err on the reasoning states inside the JDK issue you link to – disabling these things is scary as hell. I also agree with the commenter's statement there that browsers indeed do not trust the example link you showed.

Having that said, a workaround should be available (as is for the raw JDK, and explained in above ticket), thus here's a PR which makes it possible to disable SNI: https://github.com/akka/akka/pull/20252 it has some dependencies that need to be released first though.

Note that doing it globally is *highly* discouraged, please instead disable it for the specific connections where you know you "have to".

**Comment by nodefactory-bk** [comment]
Indeed, disabling SNI should be done with care. But don't worry, I have a backgrond in web hosting =)
That's also why I don't want to use the system property to kill SNI for everything but instead used a custom ssl-context for the requests that needed it.
This should probably be clearly documented for the disabling step.

About the JDK issue reasoning I should clarify that the unrecognized_name alert can be sent both as a warning and as a fatal alert. Java treats both as fatal though.
If you need it for testing I'd be happy to set up a server that gives the warning, works in browsers but causes java to bail.

**Comment by nodefactory-bk** [comment]
Hi!
I can't get this to work per conection or per request in 2.4.4
It works great if I disable SNI globally in configuration, but not per ConnectionContext

It seems the TLSActor only checks the global SNI flag in applySNI:
```
...
if !sslConfig.config.loose.disableSNI
  } yield { 
 ...
```

and sslConfig is defined above as:
`val sslConfig = AkkaSSLConfig(context.system)`

I also couldn't find any local SNI flag in the HttpsConnectionContext class.

**Comment by ktoso** [comment]
Did you follow the docs http://doc.akka.io/docs/akka/2.4.4/scala/http/client-side/https-support.html#Disabling_TLS_security_features__at_your_own_risk ?

> I also couldn't find any local SNI flag in the HttpsConnectionContext class.

The flag is not copied over to HttpsConnectionContext - the connection context can be created from sslConfig, which you can configure like shown in above docs.

Let me know if I missed something, though I hope not.

**Comment by nodefactory-bk** [comment]
Yes I have tried it that way.
I'm attaching a scalatest test case that I've set up with a test host.
When I run the attached program I get:

> [info] AkkaSni:
> [info] sni
> [WARN] [04/15/2016 13:10:28.509] [pool-1-thread-1-ScalaTest-running-AkkaSni] [AkkaSSLConfig(akka://default)] You are using ssl-config.loose.disableSNI=true! It is strongly discouraged to disable Server Name Indication, as it is crucial to preventing man-in-the-middle attacks.
> [info] - should off *** FAILED ***
> [info]   The future returned an exception of type: javax.net.ssl.SSLProtocolException, with message: handshake alert:  unrecognized_name. (AkkaSni.scala:39)
> [info]   org.scalatest.exceptions.TestFailedException:
> 

If I specify this in application.conf for the test:

> akka.ssl-config {
>     loose {
>         disableSNI = true
>     }
> }

then SNI is properly disabled. 
However I noticed that the certificate is still not accepted even though i set 'acceptAnyCertificate' and disableHostnameVerification.

I have purposely set up the host with a bad cert and incorrect SNI.
However a browser will gladly display it if you ignore the certificate warning.

In akka 2.4.2 I used the SSLParams to turn off certificate verification and SNI for these servers, and had no problems with it. 
In 2.4.4 I can disable hostname and certificate validation using SSLParams as in 2.4.2, however I can only disable SNI globally as far as I can tell.
[AkkaSni.scala.txt](https://github.com/akka/akka/files/220839/AkkaSni.scala.txt)

**Comment by ktoso** [comment]
Thanks a lot for the feedback and sorry it's not completely solved yet then. Reopening and will look into it soon.

**Comment by nodefactory-bk** [comment]
Btw, I would also note that the warning is incorrect.
Unlike hostname-verification disabling SNI doesn't actually cause any security issues. It may however cause the server to choose the wrong certificate which would fail the certificate and hostname checks if the server needs SNI. However those servers I've come across with incorrect SNI configs have the certificat bound to the IP address so it still works.

**Comment by ktoso** [comment]
Thanks a lot for the comment @nodefactory-bk and sorry I took so long to loop back to this one, was crunching tickets.
Adjusting message now

**Comment by ktoso** [comment]
Changed ticket title and yes, sadly there was one more missing step to allow per-connection changes of that kind. Have an ugly draft which I'll polish over the next days.

**Comment by ktoso** [comment]
Will be fixed in 2.4.7, thanks for reporting!

**Comment by michaelyaakoby** [comment]
This fix have introduced a "debug print" which or every new connection writes "sslConfig.config.loose.disableSNI = false" to stdout.
(Search for "println" in 55684fb)

**Comment by ktoso** [comment]
Ouch, I'm sorry this slipped through review. Submitted a fix: https://github.com/akka/akka/pull/20769
