### ISSUE TITLE
groupedWithin does not emit a last element when n == 1

### ISSUE THREAD

**Issue by TanUkkii007** [akka/akka#20232]
In the following code, the first example should print up to 10, but gets up to 9.

```scala
Source(0 to 10).groupedWithin(1, 1 seconds).runForeach(println)
/*
Vector(0)
Vector(1)
Vector(2)
Vector(3)
Vector(4)
Vector(5)
Vector(6)
Vector(7)
Vector(8)
Vector(9)
*/

Source(0 to 10).groupedWithin(2, 1 seconds).runForeach(println)
/*
Vector(0, 1)
Vector(2, 3)
Vector(4, 5)
Vector(6, 7)
Vector(8, 9)
Vector(10)
*/
```

I confirmed this happened in Akka 2.4.2 and 2.4.3.

**Comment by TanUkkii007** [comment]
*Updates*

When I make Source as async, a last element is emitted.

```scala
Source(0 to 10).async.groupedWithin(1, 1 seconds).runForeach(println)
/*
Vector(0)
Vector(1)
Vector(2)
Vector(3)
Vector(4)
Vector(5)
Vector(6)
Vector(7)
Vector(8)
Vector(9)
Vector(10)
*/
```

Is it expected as normal behavior that non-async `Source` does not emit a last element when combined with `groupedWithin`?
Can anyone explain this?

**Comment by patriknw** [comment]
looks like a bug to me, thanks for reporting

**Comment by drewhk** [comment]
This is very likely a bug, and the reason because it behaves differently in async and non-async versions is because one exposes the race condition better than the other.

**Comment by 13h3r** [comment]
For me `groupWithin` does not emit elements from time to time. I can reproduce it in complex system but can not provide minimum example. For me it looks like it can just hangs at some time. I will try to provide minimum reproducible example, but not sure that I can extract all complex graph logic from it in reasonable time.

**Comment by drewhk** [comment]
Ok thanks, I look at this now.

**Comment by drewhk** [comment]
@TanUkkii007 I cannot reproduce it on 2.4.3, for me your code snippet works. Are you sure this fails on 2.4.3?

**Comment by 13h3r** [comment]
@drewhk I can confirm that it does not work:

```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.Source

import scala.concurrent.duration.DurationInt

object X extends App {
  implicit val as = ActorSystem()
  implicit val m = ActorMaterializer()

  Source(0 to 10).groupedWithin(1, 1 seconds).runForeach(println)
}
```

```
Vector(0)
Vector(1)
Vector(2)
Vector(3)
Vector(4)
Vector(5)
Vector(6)
Vector(7)
Vector(8)
Vector(9)
```

```scala
val akkaVersion = "2.4.3"
```

**Comment by TanUkkii007** [comment]
@drewhk I'm sure it reproduces on 2.4.3. The first code print from Vector(0) to Vector(9) but not Vector(10).
In case I will try it in clean environment. Because I checked it inside my project.

**Comment by TanUkkii007** [comment]
> In case I will try it in clean environment. Because I checked it inside my project.
@13h3r You've already tried. Thanks. It spares my work.

**Comment by drewhk** [comment]
Interesting, it does not fail on my machine...

**Comment by drewhk** [comment]
I tried this:
```
      Source(1 to 10).groupedWithin(1, 1 seconds)
        .runWith(Sink.seq).futureValue should ===((1 to 10).map(List(_)))
```

and it works fine. Aren't you shutting down the system earlier than expected?

**Comment by drewhk** [comment]
i.e. are you awaiting on the Future returned by `Sink.foreach`?

**Comment by drewhk** [comment]
ok, I got a failure it seems

**Comment by drewhk** [comment]
aand, since in a fused section such races are not possible, this points to some mistake in the timer handling

**Comment by drewhk** [comment]
this version fails reliably for me:

```
      Source(1 to 10)
        .groupedWithin(1, 1.second)
        .throttle(1, 110.millis, 0, ThrottleMode.Shaping)
        .runWith(Sink.seq).futureValue should ===((1 to 10).map(List(_)))
```

**Comment by drewhk** [comment]
oops, didn't want to close

**Comment by TanUkkii007** [comment]
@drewhk 
You are right. I didn't wait Future returned by Sink.foreach.
Now I make it await the test below passed.

```scala
val result = Await.result(Source(0 to 10).groupedWithin(1, 1 seconds).toMat(Sink.seq)(Keep.right).run(), 5 seconds)

assert(result == (0 to 10).map(Vector(_)))
```

**Comment by drewhk** [comment]
Doesn't matter, there is a bug anyway
