### ISSUE TITLE
Header parsing behavior for custom modeled headers in akka 2.4.3

### ISSUE THREAD

**Issue by cmbaxter** [akka/akka#20246]
This ticket is in reference to a post I put up on the user's group:

https://groups.google.com/forum/#!topic/akka-user/2epFS5nfqqk

When using a custom modeled header in akka 2.4.3, the HeaderMagnet used for that type of header in `headerByType` supplied the `.toString` of the header to the `.apply` on the companion, which in turn calls `.parse`.  This results in the header name, semi colon and value all being passed into the `.parse` method on the modeled companion where my expectation was that it would only be the value itself and not include the header name and semi colon.

**Comment by ktoso** [comment]
@johanandren do you remember if we fixed this already?

**Comment by johanandren** [comment]
I don't think this was fixed, I think we repeated checks for the same behavior for the Java DSL.

**Comment by ktoso** [comment]
Thanks for checking!

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
