### ISSUE TITLE
Provide means to handle Marshal and Unmarshal errors graciously.

### ISSUE THREAD

**Issue by kanuku** [akka/akka#20249]
Hi all, 
I am creating a `http-client` using `akka-http-experimental` to marshal and unmarshal some json data. 

As the method below shows, it accepts an `implicit unmarshaller`. You can provide your own using `jackson`, `spray-json` or even `play-json`.
In this case I am using `spray-json`. The problem is that when a deserialization attempt fails(` Unmarshal(entity).to[T].map(in => Right(Option(in))) `), it throws a **spray.json.DeserializationException**, which is a bit of a problem. I would prefer to handle the error graciously with a more general `UnmarshallException` because I don't know which deserialization framework will be used.
Right now wrapping the Unmarshalling in a Try() catch works, but using the Throwable feels
wrong because I want to catch only the UnmarshalException and let all other exceptions slide.

```scala
def mapToEither[T](response: HttpResponse)(implicit unmarshaller: FromEntityUnmarshaller[T], m: Manifest[T]): Future[Either[ClientError, Option[T]]] = {
 logger.debug("received [response={}]", response)
    response match {
      case HttpResponse(status, headers, entity, protocol) if (status.isSuccess()) =>
        logger.info("Result is successfull ({}) ", status.intValue().toString())
        Unmarshal(entity).to[T].map(in => Right(Option(in)))  
      case HttpResponse(status, headers, entity, protocol) if (status.isRedirection()) =>
        val msg = "An error occurred with http-status (" + status.intValue() + "}) and reason:" + status.reason()
        logger.info(msg)
        Future.successful(Left(ClientError(msg, Some(status.intValue()))))
      case HttpResponse(status, headers, entity, protocol) if (status.isFailure()) =>
        val msg = "An error occurred with http-status (" + status.intValue() + "}) and reason:" + status.reason()
        logger.warn(msg)
        Future.successful(Left(ClientError(msg, Some(status.intValue()))))

    }
}
```

I would have thought that handling an error as a result from a `Marshal/Unmarshal` attempt would have been more appropriate when using an error object defined on the same level as the Marshal and Unmarshal traits.

Something in this fashion as the  `json-play` framework. :
```scala
Unmarshal(entity).to[T].map {
case Success(in) => in
case UnmarshallError(error) => Left(ClientError(error.getMessage, Some(status.intValue())))
}
```

**Comment by ktoso** [comment]
This is not really an issue for Akka itself though I think?
You have a Lightbend subscription and such things we're happy to give in and help out as part of the support offering, shall we continue more in detail over there?

**Comment by kanuku** [comment]
Hi @ktoso thank you for your quick answers. I think I haven't expressed the problem clear enough.
I am asking if by creating a separate UnmarshalError/MarshalError would have given us the `akka-http-experimental` users better means for handling Marshalling and Umarshalling Errors.

**Comment by ktoso** [comment]
I see, so you're asking to wrap exceptions in another layer hiding the actual impl's exception...
But why – it returns a `Future[B]` anyway so you can `onComplete { case Success(v) => case Failure(e) => }` in any case – what would adding another layer of exceptions gain us here?

>  it throws a spray.json.DeserializationException, which is a bit of a problem. 

Why?

> I would prefer to handle the error graciously with a more general UnmarshallException because I don't know which deserialization framework will be used.

Nor do you care what exception it was I'd say even – log or bubble up, esp since it's carried in the Future anyway, no-one has to inspect it and I dont see how another layer would help here?

**Comment by kanuku** [comment]
Hi @ktoso, I also don't think that an exception is the right answer! I think having the means to graciously handle the error on the same level as the used Marshal/Unmarshal could have given us a bit more flexibility. 
An example is how the `play-json` lib does it. It has a `validate` (example [here](https://github.com/playframework/playframework/blob/9a06b9a0a6ea7d1299e61ea3c1f37a08b714297e/framework/src/play-integration-test/src/test/scala/play/it/http/parsing/JsonBodyParserSpec.scala)) function which gives you more freedom to handle parsing errors in your own fashion, without forcing you to mess with exceptions. 
Isn't that an appropriate and neat solution?

**Comment by ktoso** [comment]
Cleaning up tickets a bit, closing for now as obsolete.
Please re-open if concrete proposal at hand, thanks
