### ISSUE TITLE
Snapshots with PersistentFSM

### ISSUE THREAD

**Issue by abesanderson** [akka/akka#20257]
We've been using persistent fsm in production for a few months, and it's been holding up pretty well, but
there are a few things that would make it easier to work with PersistentFSM and snapshots:
  - A standardized message format for current fsm state/data(not sure how useful timeout, etc, information is)
  - During recover, trigger startWith() on any SnapshotOffer fitting the above format
  - Alternatively, a onSnapshot() hook added to the PersistentFSM receiveRecover method

**Comment by leonidb** [comment]
@abesanderson If I understand correctly, you suggest to add an option to save state name and state data as a snapshot and load it on recovery, before replaying the following domain events/state change events?
Do you currently use snapshots with ```PersistentFSM```? If so, how?

**Comment by abesanderson** [comment]
Yep, that's correct.

Right now, I have constructed a class to encapsulate the stateName and stateData(PersistentFSMSnapshot[S <: FSMState, D <: Serializable]), so that I can easily jump to the snapshotted state(similar to how StateChangeEvent works).  Initially this was set up because we were using a persisted snapshot store, but a ephemeral journal, but that has since changed to accommodate a distributed system backed by cassandra persistence.  In theory, this may work similarly to truncating the journal on every StateChangeEvent, but there is some value for us to be able to control when snapshots happen(like snapshotting when we come down cleanly, even if there were no state changes).  There is also value to keeping the journal around just in case we have to do some recovery if our snapshots are somehow corrupted.  The journal also has some benefits as an audit trail, but snapshotting should give us a quick means to restore without playing back a potentially very large journal.

**Comment by patriknw** [comment]
I think we should add that. Didn't know that it wasn't supported.

**Comment by leonidb** [comment]
Thanks for the details, @abesanderson.
@patriknw Starting to work on this one.
