### ISSUE TITLE
Do not reply with Transfer-Encoding: chunked if the request was HTTP 1.0

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#20253]
see https://github.com/akka/akka/issues/20236#issuecomment-206778281

**Comment by 2beaucoup** [comment]
This actually works as expected (impl is [here](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala#L248-L255)). Seems like I mixed up the HTTP versions while unit testing and testing via the browser.

**Comment by ktoso** [comment]
I love tickets which close themselfs <3
