### ISSUE TITLE
Dilation for expectNoMessage has unintended consequences

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20255]
The issue is that the assertion that "nothing arrives in the next T period" does not imply "nothing arrive in the next T \* N period", which is exactly what dilation does to `expectNoMessage`. This makes testing message arrival intervals impossible with dilation.

I am not sure it makes sense to apply dilation to expectNoMsg calls.

**Comment by patriknw** [comment]
I agree. Also, I don't think `remaining` should be used for `expectNoMsg`. It's a different kind of timeout and should have a different default, or no default at all.

**Comment by patriknw** [comment]
*we can probably not change it without deprecation, new name, and such*

**Comment by ktoso** [comment]
It could be changed with a configuration flag hm...
Not sure if we want that, just an idea
