### ISSUE TITLE
NPE in ConsistentHashingRouter for SimpleDnsManager

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20263]
```
2016-04-08T04:22:43Z ChristophersMBP.lan WARN  ConsistentHashingRoutingLogic ConsistentHashingRoutingLogic(akka://conductr) - Couldn't route message with consistent hash key [logs2.papertrailapp.com] due to [null]
```

Reported by @huntc

**Comment by patriknw** [comment]
A workaround, until next release is out, is to use a a round robin pool instead.
In config:
```
akka.actor.deployment {
  /IO-DNS/inet-address {
    mailbox = "unbounded"
    router = "round-robin-pool"
    nr-of-instances = 4
  }
}
```

**Comment by huntc** [comment]
Thanks for this. Do I need that configuration now then for every Lagom service, every Play 2.5 app and every Akka http based service?

**Comment by patriknw** [comment]
I don't think so. This dns router id not used much, it seems. Note that it was not working at all in Akka 2.4.2 with ClusterActorRefProvider and we didn't see many complaints about that.

I think the usage in conductr is a special, that triggers it in the startup. I think application.conf in conductr will be enough, but you have to try it.

**Comment by drewhk** [comment]
backported
