### ISSUE TITLE
akka-http: HttpMessageParser swallows IllegalHeaderException

### ISSUE THREAD

**Issue by atemerev** [akka/akka#20272]
When HTTP headers with additional fields are encountered:

(e.g.: Strict-Transport-Security: "max-age=15552000; includeSubDomains; preload" — "preload" field is not included in current headers model)

HttpMessageParser#parseBytes silently swallows IllegalHeaderException:

```scala
  final def parseBytes(input: ByteString): Output = {
    @tailrec def run(next: ByteString ⇒ StateResult): StateResult =
      (try next(input)
      catch {
        case e: ParsingException ⇒ failMessageStart(e.status, e.info)
        case NotEnoughDataException ⇒
          // we are missing a try/catch{continue} wrapper somewhere
          throw new IllegalStateException("unexpected NotEnoughDataException", NotEnoughDataException)
      }) match {
        case Trampoline(x) ⇒ run(x)
        case x             ⇒ x
      }
```
(IllegalHeaderException is not included in catch clause)

To reproduce: run websocket client example with the following URI: wss://ws-feed.exchange.coinbase.com

Proposed solutions: 

* include IllegalHeaderException into catch clause;
* make IllegalHeaderException extending ParsingException;
* relax header parsing requirements to allow optional fields not defined in the model.

See also: #20271

**Comment by ktoso** [comment]
Thanks for reporting, will have to look a bit deeper into this (tomorrow) before I can +1 one of the proposals.

**Comment by atemerev** [comment]
@ktoso Any decision on that?

**Comment by ktoso** [comment]
Went back to this ticket, sorry for the delay.
So we've fixed the special case of `strict-transport-security`, yet the question remains.
I think that we should include the exception in the catch clause for now, if we see more instances of the problem we should re-visit it then.

**Comment by pjazdzewski1990** [comment]
@ktoso If you don't mind I could grab this ticket.

**Comment by ktoso** [comment]
Great, yes please

**Comment by pjazdzewski1990** [comment]
I've tried to reproduce the issue with no luck.
Here are some tests https://github.com/akka/akka/commit/8466679c7e8b223cc72389ec01b7ecf4ff6a817d
Both pass and the new `catch` is never triggered - additional data is silently ignored. It makes sense in the context of https://github.com/akka/akka/issues/20271#issuecomment-208212760
Not sure if we want to proceed with this ticket (so custom values in headers will fail) or close it.

**Comment by atemerev** [comment]
I fixed it for Strict-Transport-Security, but the issue might still be valid for other headers.
