### ISSUE TITLE
akka-http: Strict-Transport-Security header should include "preload" optional field

### ISSUE THREAD

**Issue by atemerev** [akka/akka#20271]
As per https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security , there is a "preload" field which is not included yet in akka-http headers model. This leads to parse errors in akka-http websocket client code.

Can be encountered in the wild, e.g. on CloudFlare services.

Example (Websocket URI): wss://ws-feed.exchange.coinbase.com 

Proposed solution: update headers model in akka-http-core Java DSL and Scala DSL to include "preload" optional field.

**Comment by atemerev** [comment]
Created pull request

**Comment by ktoso** [comment]
Thanks a lot for the issue and PR, it's a good idea to fix this I agree.
We'll need to figure out if we're able to do so without breaking binary compatibility

**Comment by jmhofer** [comment]
Actually, [RFC 6797](https://tools.ietf.org/html/rfc6797#section-6.1) says in 6.1:

> 5.  If an STS header field contains directive(s) not recognized by
>        the UA, the UA MUST ignore the unrecognized directives, and if
>        the STS header field otherwise satisfies the above requirements
>        (1 through 4), the UA MUST process the recognized directives.

This means that that this header should not only be extended to accept `preload`, it should be fixed so that it ignores other values it doesn't know about (instead of failing with a parse error).

**Comment by atemerev** [comment]
OK — I don't have the expertise of writing it correctly with Shapeless/Parboiled2, but it should be parsed as one or more tokens separated by ';', where max-age=<int> is required, includeSubDomains is optional, and the rest (including preloaded) can be safely ignored.

**Comment by atemerev** [comment]
Corrected the PR to maintain binary compatibility.
