### ISSUE TITLE
ExecutionContext in Marshal/Unmarshal#to could be optional

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20276]
Given:

```scala
def to[B](implicit um: Unmarshaller[A, B], ec: ExecutionContext, mat: Materializer): Future[B] = um(value)
```

`ec` could have a default value (well, null), in which case we'd use `mat.executionContext`.

Yay or Meh – Discuss :wink: 

**Upside** is making marshalling infra less confusing – if people forget the execution context it fails to compile in mystical ways now.
**Downside** do we actually want the materializer dispatcher be used for the marshalling future here? Hm....

**Comment by ktoso** [comment]
Due to bin compat this would be good to decide before un-experimentaling akka-http.

**Comment by viktorklang** [comment]
If the ec is optional, why is it in the signature then? Shouldn't the need for the eC be encoded in the thing that needs the EC?

**Comment by ktoso** [comment]
It's not that it's "completely optional", we always need one, however it has a readily available fallback in another parameter that we already use.
Goal is to make these APIs easier to use in simple use (they confuse the hell out of people–each implicit adds to that burden), while still keeping it as configurable as is currently.

Like mentioned in the first comment here, the question is primarily if the default materializer dispatcher is ok to be used for these or not.

**Comment by viktorklang** [comment]
The problem with having the default is that if people don't do anything, and don't know they even needed an EC, they'll never configure one of their own, leading to everything running on the default EC. default parameter values considered harmful IMO.

**Comment by ktoso** [comment]
I wouldn't paint it as black vs. white in general, but ok with dropping this one–it's one of the less confusing ones.
