### ISSUE TITLE
Akka 2.4.3 and persistent connection issue

### ISSUE THREAD

**Issue by huntc** [akka/akka#20270]
I can now confirm that my Akka client code is closing the connection when built with rp16s01p04 (Akka 2.4.3). I do not believe that it should, and when built with rp16s01p03 (Akka 2.4.2) it does not. Something appears to have changed for Akka http clients and persistent connections in rp16s01p04.

Here is a Wireshark capture using rp16s01p03. All is well - you can see SSE events from the server in messages 25, 31, 37 and so forth:

![screen shot 2016-04-10 at 3 47 14 pm](https://cloud.githubusercontent.com/assets/694893/14408635/4a2f585c-ff40-11e5-815f-e9718431113e.png)

Here is the capture for the same code when built with rp16s01p04:

![screen shot 2016-04-10 at 3 44 04 pm](https://cloud.githubusercontent.com/assets/694893/14408636/560e9bf6-ff40-11e5-904a-7b4ce69baddc.png)

You can see the client now closing the connection at message 19.

I do not believe the problem to be on the server side as I used an Akka http server built with rp16s01p04 for both runs.

In case it helps, here’s my Akka http related code (commented out unrelated code):

```scala
private final val bundlesEventsRequest =
  Get(s"$VersionPrefix/bundles/events?events=config&events=execution")
    .addHeader(`Cache-Control`(`no-cache`))

protected def createBundlesEventsConnection(host: String, port: Int) = Http().outgoingConnection(host, port)

private def consumeBundlesEvents(connector: ActorRef, connection: Connection)(
  implicit ec: ExecutionContext, mat: ActorMaterializer): Unit =
  Source
    .single(bundlesEventsRequest)
    .via(connection)
    //      .alsoTo(
    //        Sink.head.mapMaterializedValue(_.foreach { response =>
    //          if (response.status.isSuccess())
    //            connector ! GetBundles
    //        })
    //      )
    //      .mapAsync(1) { response =>
    //        Unmarshal(response)
    //          .to[Source[ServerSentEvent, Any]]
    //          .flatMap { sseSource =>
    //            sseSource
    //              .filter(_.data != "")
    //              .runForeach(connector ! _)
    //          }
    //      }
    .runWith(
      Sink.onComplete {
        case outcome => connector ! ConsumeBundlesEventsOutcome(outcome)
      }
    )
```

I’m also presuming that nothing additional needs to be done with Akka http when a persistent connection is required… and I understand that the HTTP 1.1 spec assumes that connections are persistent by default, so no additional headers. I also couldn’t find anything in our Akka http docs relating to how persistent connections should be configured. I’ve scanned the issues addressed for Akka 2.4.3 and cannot find anything related.

**Comment by huntc** [comment]
Related issue: https://github.com/hseeberger/akka-sse/issues/98

**Comment by huntc** [comment]
Looks related: https://github.com/akka/akka/pull/20254

Indeed building with Akka off master appears to have resolved the issue. Testing further.

**Comment by ktoso** [comment]
This is confirmed fixed in 2.4.4, looking at workaround.

**Comment by patriknw** [comment]
this is fixed, right

**Comment by huntc** [comment]
Yes, I believe so.
