### ISSUE TITLE
Great getting started ticket: Replace all PushPullStage with GraphStage

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20288]
PushPullStage is deprecated and must go.
This is a sister ticket to https://github.com/akka/akka/issues/19361 which talks about StatefulStage.

Progress is tracked in: https://github.com/akka/akka/issues/20288#issuecomment-210937880

well and of course then `PushStage` and `PullStage` (likely another ticket for those.

**This is a great ticket to get started contributing to Akka, let us know if you'd like to translate one of the Stages from PushPullStage into GraphStage, it's pretty simple :-)**

Here are the docs how to write a GraphStage: http://doc.akka.io/docs/akka/2.4.2/scala/stream/stream-customize.html#graphstage-scala

Please do one stage per PR to make reviewing smooth and nice, thanks!

- [x] Rechunker             
- [x] BodyPartParser    
- [x] DelimiterFramingStage
- [x] LengthFieldFramingStage
- [x] Recover                      
- [x] Scan                         
- [x] Fold                         
- [x] Grouped                  
- [x] Sliding                     
- [x] Completed              
- [x] InvalidAbsorbTermination
- [x] Doubler                      
- [x] KeepGoing                 
- [x] RestartTestStage       
- [x] OneToManyTestStage
- [x] NaiveTake                   
- [x] ByteStringBatcher       
- [x] BodyPartRenderer

**Comment by pchordia15** [comment]
I would like to contribute to the issue referenced in this ticket. This is the first time I would be contributing to Akka. So could you please guide me through for how should I begin with the issue.

Thanks.

**Comment by naferx** [comment]
Hi @ktoso !, 
I'm interested in contributing with this issue.

**Comment by ktoso** [comment]
Hi @pchordia15 @naferx :-)
It's as simple as picking which class you'd like to work on, then finding it in the codebase (for example with scan: https://github.com/akka/akka/search?utf8=%E2%9C%93&q=%22class+Scan%22&type=Code ), 
and then rewriting it as a GraphStage. All logic should remain semantically the same, we just want to implement them using the new API.

These usually already come with existing tests, so it should be relatively simple to verify you did it right – then simply submit a PR and we'll review and take it from there.

**Comment by danxmoran** [comment]
I'd like to grab a few of these!  Picking out of the blue, I'll start with `RestartTestStage` and `OneToManyTestStage`.

**Comment by ktoso** [comment]
Great, thanks! Looking forward to the PR :)

**Comment by zhxiaogg** [comment]
I'd like to try Doubler and KeepGoing if you don't mind.

**Comment by ktoso** [comment]
Hakk away :-) Thanks in advance!

**Comment by danxmoran** [comment]
Hey @ktoso, I started on this last night and have a question.  I'm struggling to replicate [setting the supervision strategy](https://github.com/akka/akka/blob/bd8fcc9d9aeafc2c49745e7519d13b3e0abc18e6/akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSupervisionSpec.scala#L31).  It [looks like](http://doc.akka.io/docs/akka/2.4.3/scala/stream/stream-error.html) the recommended strategy for external users of streams is to call `.withSupervisionStrategy` on a flow / materializer, but for this test class it'd be nice to still have the supervision strategy hard-coded within the stage itself.  Is that still something we can do with a `GraphStage`?  I've tried fiddling with setting `initialAttributes` but nothing has stuck as of yet.

**Comment by zhxiaogg** [comment]
@danxmoran I don't know if it's the right solution but I just removed tests in `InterpreterSupervisionSpec`,  because I think the `GraphInterpreterFailureModesSpec` is enough for testing the GraphStage failures.

**Comment by danxmoran** [comment]
@zhxiaogg I'm hesitant to remove tests because the stages I volunteered for only exist in the `InterpreterSupervisionSpec`, so removing their tests would amount to deciding they're no longer relevant.

**Comment by danxmoran** [comment]
Since I'm stumped for now on the two test stages, I'm going to try my luck with NaiveTake and ByteStringBatcher while waiting for advice from the powers-that-be.

**Comment by viktorklang** [comment]
Scan is here: https://github.com/akka/akka/pull/20325/files

**Comment by zhxiaogg** [comment]
Doubler, KeepGoing is ok, see #20307

I'll moving on with Fold, Grouped and Sliding

**Comment by pchordia15** [comment]
I wil go with Completed and Rechunker

**Comment by ktoso** [comment]
@pchordia15 @zhxiaogg Thanks!

**Comment by richard-imaoka** [comment]
Hi @ktoso , what is still remaining? If 

- DelimiterFramingStage, and
- RestartTestStage 

are still open, I would like to take them.

Are these correct below?

| Class                       | assignee  | PR        |
| --------------------------- |:---------:| -----:|
|BodyPartParser               |danxmoran  | https://github.com/akka/akka/pull/20327 |
|DelimiterFramingStage        |           | |
|LengthFieldFramingStage      |           | |
|Recover                      |           | |
|Scan                         |viktorklang| https://github.com/akka/akka/pull/20325 |
|Fold                         |zhxiaogg   | https://github.com/akka/akka/pull/20336 |
|Grouped                      |zhxiaogg   | https://github.com/akka/akka/pull/20336 |
|Sliding                      |zhxiaogg   | https://github.com/akka/akka/pull/20336 | 
|Completed                    |pchordia15 | PR to be opened |
|Rechunker                    |pchordia15 | PR to be opened |
|InvalidAbsorbTermination     |           | |
|Doubler                      |zhxiaogg   | https://github.com/akka/akka/pull/20307 |
|KeepGoing                    |zhxiaogg   | https://github.com/akka/akka/pull/20307 |
|RestartTestStage             |           | |
|OneToManyTestStage           |           | |
|NaiveTake                    |danxmoran  | https://github.com/akka/akka/pull/20327 | 
|ByteStringBatcher            |danxmoran  | https://github.com/akka/akka/pull/20327 |

**Comment by zhxiaogg** [comment]
@richard-imaoka Good job!
I'll start working on LengthFieldFramingStage and Recover.

**Comment by danxmoran** [comment]
@richard-imaoka I've also got RestartTestStage and OneToManyTestStage; I've got a few more ideas on how to get around the roadblocks I was hitting earlier.

**Comment by richard-imaoka** [comment]
@danxmoran thanks for letting me know. I updated the table in my comment. 

Let me then work on DelimiterFramingStage and InvalidAbsorbTermination if they are still open.

**Comment by pchordia15** [comment]
#20288 Convert Completed to GraphStage #20454

**Comment by pchordia15** [comment]
#20454

**Comment by drewhk** [comment]
Amazingly nice work is going on here, kudos to all contributors!

**Comment by ktoso** [comment]
`DelimiterFramingStage` done, thanks @richard-imaoka !

**Comment by ktoso** [comment]
`LengthFieldFramingStage` done, thanks @zhxiaogg!

**Comment by danxmoran** [comment]
Sorry I've dropped the ball a bit on `RestartTestStage` and `OneToManyTestStage`, my free time got squashed for a few weeks.  I should have time to dig into it again starting tonight!

**Comment by ktoso** [comment]
>  I should have time to dig into it again starting tonight!

Woot, welcome back :-)

**Comment by danxmoran** [comment]
Hey @ktoso, is the `OneToManyTestStage` still relevant? AFAICS the [test that uses it](https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/impl/fusing/InterpreterSupervisionSpec.scala#L333) is testing that supervision strategies are ignored when an exception is thrown during that stage's `onPull`. Currently the supervision logic is [handled by a superclass](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/stage/Stage.scala#L55) which also applies to "real" stages so it's good to cover, but once `OneToManyTestStage` is ported to a `GraphStage` it looks like it won't inherit anything related to supervision. Is it worth implementing and testing supervision in the ported `OneToManyTestStage` when that stage only exists in a single spec? Or should I just delete the stage?

**Comment by ktoso** [comment]
I guess it could be deleted then, could you check @drewhk ?

**Comment by drewhk** [comment]
I think it can be deleted.

**Comment by danxmoran** [comment]
@ktoso @drewhk awesome :) PR is at #20629.

So, now I have the same question about the `RestartTestStage`.  Its tests look slightly more interesting since they also involve `Map`, but I'm still wondering if we need it on top of per-stage supervision tests.

**Comment by ktoso** [comment]
Thanks all involved here for the awesome PRs :-)
It's so great to see we were able to pull it off so quickly with your help!

Just one more outstanding, but already has a PR :)

**Comment by agolubev** [comment]
should this be finally closed?

**Comment by ktoso** [comment]
Thanks everyone for helping on this!
