### ISSUE TITLE
Verify and/or remove de-sugared complete() magnets in docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20280]
in the `complete.rst` docs we have manually desugared magnets, make sure they're valid or remove.

**Comment by poojadshende** [comment]
@ktoso, can you give details on what is to be done.

**Comment by ktoso** [comment]
This is just about looking at the sample snippet in `complete.rst` and making sure they actually all work - because the signatures as-is never exist in the actual code.

If they work we can close this ticket :)

**Comment by svezfaz** [comment]
Apologies @poojadshende , I had a stale browser window open on this issue, didn't see you were taking a look as well.

**Comment by agolubev** [comment]
@ktoso, should this be cosed

**Comment by johanandren** [comment]
My bad, missed to close. Thanks @svezfaz
