### ISSUE TITLE
Invalid Jar file in /akka-2.4.3/lib/akka/ in latest Akka version

### ISSUE THREAD

**Issue by camachomaria** [akka/akka#20287]
Akka release: Akka 2.4.3 (Scala 2.11 and Java 8+)
Downloaded file: akka_2.11-2.4.3.zip
Downloaded from: http://akka.io/downloads/
Invalid jar file: i have späces.jar
Path to file: /akka-2.4.3/lib/akka/

**Comment by ktoso** [comment]
Thanks for reporting, that one should probably not end up in the distro in any case, AFAIR we just use it to check if resources can be served from such jar.

Does this hinder you from anything though? We recommend using sbt/maven/something to resolve dependencies in any case, not so much the download :)

**Comment by camachomaria** [comment]
Not for now.
Are you planning to have a new distro any time soon?

**Comment by ktoso** [comment]
Not really (actually I'm not that sure why one would use that distro instead of dependencies via sbt or maven), so it'd be about fixing the current process.

Thanks for reporting!

**Comment by patriknw** [comment]
As long as we publish that zip we should make sure it doesn't contain invalid things, and that test jar doesn't belong there.

Starting point if someone wants to take a stab at it: https://github.com/akka/akka/blob/master/project/Dist.scala

**Comment by 2beaucoup** [comment]
`akka-http-tests` as a whole shouldn't be part of the dist, right?

**Comment by patriknw** [comment]
that is right

**Comment by pchordia15** [comment]
@ktoso @patriknw @2beaucoup I could see the same invalid file(I have späces.jar) in the latest version of akka(akka-2.4.4).

**Comment by ktoso** [comment]
Well, the ticket is not closed as you can see so not change is to be expected.
We'd happily accept a PR helping out with this :)

**Comment by pchordia15** [comment]
Cool. So I have a few questions as i would love to work on it. Just the file mentioned in the comment above need to be changed? As specified above akka-http-tests should be removed, but i couldn't find it in the Dist.scala file

**Comment by 2beaucoup** [comment]
I think all that is needed is to add all modules that have `dontPublishSettings`in their build.sbt [here](https://github.com/akka/akka/blob/c69efe4dd86732d4955c0df30e9cd629cbd3ad7f/project/AkkaBuild.scala#L45-L45).

**Comment by johanandren** [comment]
@2beaucoup I'll mark this ticket as closed so that it gets nicely into the milestone list of changes, lets open a new one for the automagic-detection of non-published projects
