### ISSUE TITLE
Add proper timeouts and error handling for Artery subsystem startup and shutdown

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20317]

**Comment by patriknw** [comment]
I started working on the bind failure scenarios, but have to stash that until next Aeron release. The API for checking subscription status is not released yet. This is what we need https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/main/java/io/aeron/driver/status/ChannelEndpointStatusIndicator.java

**Comment by patriknw** [comment]
I added some basic logging of Aeron errors, so that we are not completely in the dark https://github.com/akka/akka/pull/20544

**Comment by patriknw** [comment]
more scenarios will be handled by other tickets
