### ISSUE TITLE
Issue with Akka 2.4.2 and outbound HTTPS call with Socket Linger setting

### ISSUE THREAD

**Issue by cmbaxter** [akka/akka#20326]
We are using Akka 2.4.2 to make a call to a partner we work withs http service using SSL and we keep getting a connection closed by peer issue exception.  I turned on trace logging with tcp and this is what we see:

[DEBUG] [04/14/2016 11:54:00.752] [test-akka.actor.default-dispatcher-6] [akka://test/system/IO-TCP/selectors/$a/0] Closing connection due to IO error java.io.IOException: Connection reset by peer
[DEBUG] [04/14/2016 11:54:00.755] [test-akka.actor.default-dispatcher-6] [akka://test/system/IO-TCP/selectors/$a/0] setSoLinger(true, 0) failed with [java.net.SocketException: Invalid argument]

The rough code I have spun up to repro the issue is:

    val cf = """
        akka.io.tcp.trace-logging = on
        akka.loglevel = DEBUG
    """
    val baseUri = Uri(vzwUri)
    implicit val system = ActorSystem("test", ConfigFactory.parseString(cf))
    implicit val mater = ActorMaterializer()
    val pool = Http().outgoingConnectionHttps(vzwHost, 22790)
  
    val fut  = Source.single(makeRequest).via(pool).runWith(Sink.head)
    import system.dispatcher

    fut onComplete{
      case util.Failure(ex) => ex.printStackTrace()
      case util.Success(_) => println("horay")
    }

I don't have the makeRequest method here, but it's basically creating a POST request with a `FormData` entity.  Has anyone seen this before and is there a way I can get around this?

**Comment by cmbaxter** [comment]
So it seems like the socket linger issue is a red herring.  What we actually had to do, after luckily stumbling on this via internet searches we found this to work:

    akka.ssl-config{
      protocol = "TLSv1.2"
    }

Adding this to our config worked.  I didn't see any mention to this setting anywhere in the tcp or http config.  How are people to know about this setting?

**Comment by ktoso** [comment]
All TLS/HTTPS things are moving towards being configured via `ssl-config`, which has documentation here: http://typesafehub.github.io/ssl-config/
You're right that we don't link to it from enough places - all HTTPS related pages should point to it very explicitly, I'll add that right away.

Also, since we're on JDK8 now we should be using 1.2 by default so thanks for noticing we still had the "because JDK6" setting for this in there – we'll update the setting to 1.2 right away as well.

**Comment by ktoso** [comment]
Seems resolved
