### ISSUE TITLE
akka-http

### ISSUE THREAD

**Issue by marcuslange** [akka/akka#20339]
i'm curious why my css files are delivered as text/plain vs text/css. Any ideas?

path("browser" / RestPath) {
    rpath => {
      val jsPattern = "(.js)".r
      val cssPattern = "(.css)".r
      val payload = fromInputStream(getClass.getResourceAsStream(s"/halbrowser/$rpath")).mkString
      val contentType = rpath match {
        case jsPattern(rp) => ContentTypes.`application/json`
        case cssPattern(rp) => ContentType(MediaTypes.`text/css`, HttpCharsets.`UTF-8`)
        case _ => ContentTypes.`text/html(UTF-8)`
      }
      get {
        complete(HttpEntity(contentType, payload))
      }
    }
  }

**Comment by 2beaucoup** [comment]
Looks like the `getFromResourceDirectory` directive is what you're after.

**Comment by marcuslange** [comment]
thanks @2beaucoup that totally worked and reduced my code to 

path("browser" / RestPath) { rpath =>
    getFromResource(s"halbrowser/$rpath")
  }

much appreciated.

**Comment by 2beaucoup** [comment]
:+1:
