### ISSUE TITLE
akka-cluster script throws errors

### ISSUE THREAD

**Issue by tadasv** [akka/akka#2033]
The akka-cluster script isn't working. Any command I try to run I get this output:

    ./akka-cluster localhost 9999 is-available
    Error: Error processing file '/dev/fd/0' - Cannot convert result to a string.
    Akka cluster node is not available on localhost, due to

I tried this on OS X and Ubuntu Precise. I start my jar with

    -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

My project deps:

    <dependencies>
            <dependency>
                <groupId>com.typesafe</groupId>
                <artifactId>config</artifactId>
                <version>1.2.0</version>
            </dependency>
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-cluster_2.10</artifactId>
                <version>2.2.3</version>
            </dependency>
            <dependency>
                <groupId>com.typesafe.akka</groupId>
                <artifactId>akka-remote_2.10</artifactId>
                <version>2.2.3</version>
            </dependency>
            <dependency>
                <groupId>org.scala-lang</groupId>
                <artifactId>scala-library</artifactId>
                <version>2.10.3</version>
            </dependency>
        </dependencies>

**Comment by Tolsi** [comment]
I have the same problem, guys, how you solved it? @tadasv @leonardschneider

**Comment by patriknw** [comment]
It looks like the problem exists in the latest 2.3.11 zip.
You can copy the script from http://downloads.typesafe.com/akka/akka_2.10-2.3.10.zip

**Comment by Tolsi** [comment]
@patriknw nothing changed

**Comment by patriknw** [comment]
Ah, I thought this was the ticket about the wrong line endings.

**Comment by ewegene** [comment]
I am seeing a similar problem with akka-2.4.0.

After telling it to leave the cluster:

    $ akka-cluster localhost 9999 leave akka.tcp://ClusterSystem@10.0.0.100:2551
    Scheduling akka.tcp://ClusterSystem@10.0.0.100:2551 to LEAVE cluster

I see that it takes a couple seconds to leave the cluster, if I check it immediately it returns true:

    $ akka-cluster localhost 9999 is-available
    Checking if member node on localhost is AVAILABLE
    true

And eventually it will start throwing up that error (usually within a couple/few seconds within the leave command)

    $ akka-cluster localhost 9999 is-available
    Error: Error processing file '/dev/fd/0' - Cannot convert result to a string.
    Akka cluster node is not available on localhost, due to 

So, what I'd like to know is if this message is appropriate.  Is it telling me that it has left the node, or just that it's unable to check?

Is it possible that I'd get this error and the node would still be part of the cluster?

**Comment by patriknw** [comment]
It is probably because the JMX MBean is removed when the cluster node is removed.

**Comment by raboof** [comment]
I'm seeing this message, too. Perhaps we should at least reopen this issue until it's clear what's going on?

**Comment by drewhk** [comment]
I triaged this. Close if figured out.

**Comment by patriknw** [comment]
I'm not sure what we can do to improve this, but we should take another look at it. If the mbean is removed there is not much we can do from the script.

**Comment by raboof** [comment]
Indeed I don't think we can do much beyond producing a better error message, added a PR for that.
