### ISSUE TITLE
akka-http: InvalidContentLengthException with akka 2.4.4

### ISSUE THREAD

**Issue by matsluni** [akka/akka#20338]
Hi everybody,

I just tried to serve some binary data (a video) with akka-http and I got this exception:

```
app-backend 20:18:19.886 [actorSystem-akka.actor.default-dispatcher-3] DEBUG a.i.TcpListener - Successfully bound to /0:0:0:0:0:0:0:0:9100
app-backend 20:18:21.664 [actorSystem-akka.actor.default-dispatcher-2] DEBUG a.i.TcpListener - New connection accepted
app-backend 20:18:22.014 [actorSystem-akka.actor.default-dispatcher-4] DEBUG a.i.TcpIncomingConnection - Closing connection due to IO error java.io.IOException: Connection reset by peer
app-backend 20:18:22.016 [actorSystem-akka.actor.default-dispatcher-2] DEBUG a.i.TcpListener - New connection accepted
app-backend 20:18:22.025 [actorSystem-akka.actor.default-dispatcher-23] INFO  a.a.LocalActorRef - Message [akka.io.Tcp$Write] from Actor[akka://actorSystem/user/StreamSupervisor-0/$$b#-808484062] to Actor[akka://actorSystem/system/IO-TCP/selectors/$a/1#1730712293] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
app-backend 20:18:22.421 [actorSystem-akka.actor.default-dispatcher-22] DEBUG a.s.i.i.InputStreamPublisher - No more bytes available to read (got `-1` from `read`)
app-backend 20:18:22.434 [actorSystem-akka.actor.default-dispatcher-2] ERROR a.a.ActorSystemImpl - Outgoing response stream error
app-backend akka.http.scaladsl.model.InvalidContentLengthException: HTTP message had declared Content-Length 25656027 but entity data stream amounts to 11323995 bytes less
app-backend 	at akka.http.scaladsl.model.InvalidContentLengthException$.apply(ErrorInfo.scala:50) ~[akka-http-core_2.11-2.4.4.jar:na]
app-backend 	at akka.http.impl.engine.rendering.RenderSupport$CheckContentLengthTransformer$$anon$1.onUpstreamFinish(RenderSupport.scala:97) ~[akka-http-core_2.11-2.4.4.jar:na]
app-backend 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:625) ~[akka-stream_2.11-2.4.4.jar:na]
app-backend 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539) ~[akka-stream_2.11-2.4.4.jar:na]
app-backend 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:469) ~[akka-stream_2.11-2.4.4.jar:na]
app-backend 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:431) ~[akka-stream_2.11-2.4.4.jar:na]
app-backend 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:593) ~[akka-stream_2.11-2.4.4.jar:na]
app-backend 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:604) ~[akka-stream_2.11-2.4.4.jar:na]
app-backend 	at akka.actor.Actor$class.aroundReceive(Actor.scala:482) ~[akka-actor_2.11-2.4.4.jar:na]
app-backend 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:519) ~[akka-stream_2.11-2.4.4.jar:na]
app-backend 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.4.jar:na]
app-backend 	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.4.jar:na]
app-backend 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.4.jar:na]
app-backend 	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.4.jar:na]
app-backend 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.4.jar:na]
app-backend 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
app-backend 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
app-backend 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
app-backend 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
app-backend 20:18:22.435 [actorSystem-akka.actor.default-dispatcher-2] DEBUG a.a.RepointableActorRef - Aborting tcp connection because of upstream failure: HTTP message had declared Content-Length 25656027 but entity data stream amounts to 11323995 bytes less
app-backend akka.http.scaladsl.model.InvalidContentLengthException$.apply(ErrorInfo.scala:50)
app-backend akka.http.impl.engine.rendering.RenderSupport$CheckContentLengthTransformer$$anon$1.onUpstreamFinish(RenderSupport.scala:97)
app-backend akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:625)
app-backend akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
app-backend akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:469)
app-backend akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:431)
app-backend akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:593)
app-backend akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:604)
app-backend akka.actor.Actor$class.aroundReceive(Actor.scala:482)
app-backend akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:519)
app-backend akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
app-backend akka.actor.ActorCell.invoke(ActorCell.scala:495)
app-backend akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
app-backend akka.dispatch.Mailbox.run(Mailbox.scala:224)
app-backend akka.dispatch.Mailbox.exec(Mailbox.scala:234)
app-backend scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
app-backend scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
app-backend scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
app-backend scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I used this Route definition to produce the error:
```scala
trait Routes {

  val route =
      get {
        path("media") {
          getFromResource("VID_20141108_124530.mp4")
        } ~
          pathEndOrSingleSlash {
            complete(OK, "Hello World")
          }
      }
}
```

I got the exception with akka 2.4.4 (Scala 2.11.8) on OS X 10.11.4. I also tried with akka 2.4.3, which worked.

If you need more information just let me know.

Matthias

**Comment by ktoso** [comment]
It's as the message states: `HTTP message had declared Content-Length 25656027 but entity data stream amounts to 11323995 bytes less`

Did the connection get closed or file deleted or something else while transfering the file?

**Comment by 2beaucoup** [comment]
Question is: What's the actual size of `VID_20141108_124530.mp4`?

**Comment by matsluni** [comment]
A `ls`on my machine gives me a size of `26061051` for `VID_20141108_124530.mp4`.
No, I don't do anything with this file during transfer.

What is wondering me is that this works fine with akka 2.4.3.

**Comment by ktoso** [comment]
Got another report about it; promoting to bug and will look into it as soon as we can.

**Comment by ktoso** [comment]
If you find any more details, maybe with debug logging on please share.

**Comment by ktoso** [comment]
Workaround is to return a HttpEntity.Chunked (as this does not include content-lenght header)

**Comment by antonkulaga** [comment]
This bug is super-annoying. I have it with loading PDFs on my app (files like https://github.com/antonkulaga/kappa-notebook/tree/master/files ). What is interesting that the same file one machine may load well and on another machine (esp. sad it is if it is a production server) it causes this weird contentLength exception. 
Regarding Chuncked workaround, I provide files to users by:
```scala
  def loadFiles: Route = pathPrefix("files" ~ Slash) {
    getFromDirectory(files.path.toString)
  }
```
How should I change this function to provide Chuncked instead?

**Comment by ktoso** [comment]
> What is interesting that the same file one machine may load well and on another machine (esp. sad it is if it is a production server) it causes this weird contentLength exception. 

Does this happen consistently on one operating system and not on the other one? What's the operating systems you're using?

**Comment by 2beaucoup** [comment]
The numbers @matsluni provided don't add up at all:.
> <code>app-backend akka.http.scaladsl.model.InvalidContentLengthException: HTTP message had declared Content-Length <b>25656027</b> but entity data stream amounts to <b>11323995</b> bytes less</code>
>
>A lson my machine gives me a size of <b>26061051</b> for VID_20141108_124530.mp4.

I initally suspected problems with JAR-content loading but @antonkulaga used `getFromDirectory`.

Maybe something went wrong in #19913?

**Comment by matsluni** [comment]
@2beaucoup I was looking into it again yesterday and saw that the server replies with 206 (Partial Content). So the client uses Range-Requests to get the whole file. I think thats why we see some length value which are not really related to the real filesize. The determined filesize is correct. I confirmed with debugging.

Maybe #19913 is related. Was the change introduced in 2.4.4?

**Comment by 2beaucoup** [comment]
@matsluni Do you mean that akka-http serves one or more 206s before blowing up? Maybe range requests are the cause here. Can you post the complete headers of the response(s)?

**Comment by jrudolph** [comment]
> So the client uses Range-Requests to get the whole file.

@matsluni what client did you use? (Did you tell me yesterday?) Or, is the server answering non-range requests with a range response?

**Comment by jrudolph** [comment]
Ah, maybe it was the browser video player issuing range requests? That would also fit for interactive PDF browsing...

**Comment by jrudolph** [comment]
I can reproduce the video scenario with mplayer.

**Comment by ktoso** [comment]
Great to have a reproducer then!

**Comment by 2beaucoup** [comment]
Yeah, just reproduced with Chrome + PDF.

**Comment by jrudolph** [comment]
Here's the reproducer I used: 

```diff
diff --git a/akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala b/akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala
index 48fa0d9a..433487fb 100644
--- a/akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala
+++ b/akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala
@@ -5,6 +5,7 @@
 package akka.http.scaladsl.server
 
 import akka.http.scaladsl.marshallers.xml.ScalaXmlSupport
+import akka.http.scaladsl.model.HttpEntity
 import akka.http.scaladsl.model.{ StatusCodes, HttpResponse }
 import akka.http.scaladsl.server.directives.Credentials
 import com.typesafe.config.{ ConfigFactory, Config }
@@ -49,6 +50,11 @@ object TestServer extends App {
         } ~
         path("crash") {
           complete(sys.error("BOOM!"))
+        } ~
+        path("video") {
+          //withChunkedResponse {
+          getFromFile(<video location>)
+          //}
         }
     } ~ pathPrefix("inner")(getFromResourceDirectory("someDir"))
   }, interface = "localhost", port = 8080)
@@ -58,6 +64,12 @@ object TestServer extends App {
 
   bindingFuture.flatMap(_.unbind()).onComplete(_ ⇒ system.terminate())
 
+  /* converts the response entity to a chunked entity */
+  def withChunkedResponse: Directive0 =
+    mapResponseEntity { entity ⇒
+      HttpEntity.Chunked.fromData(entity.contentType, entity.dataBytes)
+    }
+
   lazy val index =
     <html>
       <body>
@@ -67,6 +79,7 @@ object TestServer extends App {
           <li><a href="/ping">/ping</a></li>
           <li><a href="/secure">/secure</a> Use any username and '&lt;username&gt;-password' as credentials</li>
           <li><a href="/crash">/crash</a></li>
+          <li><a href="/video">Video</a></li>
         </ul>
       </body>
     </html>
```

Using chunked entities doesn't work as well and it wasn't broken by #19913.

**Comment by jrudolph** [comment]
Reverting d9f82d71ebd777e4581ffa8edd4e847d42257bee helps. Unabridged it's "d9f82d71ebd777e4581ffa8edd4e847d42257bee", the "bee" in the end should have been a hint that something might have stung... ;)

**Comment by 2beaucoup** [comment]
LOL

**Comment by 2beaucoup** [comment]
This commit was part of the PR (but was squashed): https://github.com/akka/akka/pull/20230/commits/b2cf16cfe29d20b672900c053b4f7ceb8e054601.

**Comment by jrudolph** [comment]
Yup, it's missing to count `toSkip` down in the else-branch so it skips most of the stream.

**Comment by matsluni** [comment]
Hi @jrudolph thanks for investigating. Sounds like you already found the solution as well! 👍

**Comment by 2beaucoup** [comment]
@jrudolph's solution seems to work. :+1:. `StreamUtils` should really have tests. ;)

**Comment by jrudolph** [comment]
Also, `RangeDirectives` should have had tests to find the issue. And, `StreamUtils.sliceBytes` shouldn't have to exist at all because it's super generic. If there were combinators for `Source[ByteString]` (or, in fact, any batched `Source`), `sliceBytes` would be nothing more than `drop(start).take(length)`...

Anyway I currently don't have time to write those tests (or introduce any new combinators) so this fix is up for grabs.

Replacing the data in `RangeDirectiveSpecs` with:

```scala
def completeWithRangedBytes(length: Byte) =
      wrs(complete(HttpEntity.Default(ContentTypes.`application/octet-stream`, length, Source(bytes(length).map(ByteString(_)).toVector))))
```

surfaces the problem for RangeDirectives. It would probably still make sense to add tests for `sliceBytes` as well.

**Comment by ktoso** [comment]
I'll make sure we have this working in 2.4.5 which we'll release rather soon – be it by reverting or fixing current impl. Huge thanks to everyone for finding the root cause here.

**Comment by 2beaucoup** [comment]
@jrudolph If you want me to take over, I could open a PR.

**Comment by jrudolph** [comment]
Yes, thanks, @2beaucoup.

**Comment by 2beaucoup** [comment]
@jrudolph are there currently any combinators just for special types of `Source` (like `ByteString` in this case)?

**Comment by ktoso** [comment]
btw:

> @jrudolph are there currently any combinators just for special types of Source (like ByteString in this case)?

Combinators (if you mean on FlowOps) then no, and we don't want them there actually. Ops on FlowOps should be generic "in type" as well as "usefulness", so the first requirement does not match :) Instead we put all other ones like `Framing` onto collections of nice stages

**Comment by 2beaucoup** [comment]
@ktoso:
> Ops on FlowOps should be generic "in type" as well as "usefulness", so the first requirement does not match :)

Would it be generic enough If we widen it to `Flow[Seq[T]]` (ISO `Flow[ByteString]`)?

**Comment by ktoso** [comment]
I think that would solve it actually, yes 👍
