### ISSUE TITLE
Scala Api with/withoutSizeLimit overrides are still missing on scaladsl HttpEntity 

### ISSUE THREAD

**Issue by TrustNoOne** [akka/akka#20342]
https://github.com/akka/akka/issues/19983 didn't fix them all, the base trait still doesn't have the overrides. 

I bumped into this while trying to fix another issue in akka-sse https://github.com/hseeberger/akka-sse/issues/101

I already fixed it on a branch on my fork (https://github.com/akka/akka/compare/master...TrustNoOne:20342-support-httpentity-withSizeLimit).
I copied the scaladoc from the javadsl version because I guess linking javadsl classes from scaladsl is not desirable, please let me know how you handle this otherwise.

It's my first contribution (very tiny but good to learn all the rules I guess) so please excuse me If I made any mistakes. I haven't opened a pull request because the 'contributing' doc says that I have to wait for estimation and scheduling by you, so I'll wait.

Please let me know if there's anything else I need to do in order to contribute. 

Thanks

**Comment by patriknw** [comment]
Thanks for contributing! Please go ahead and open a pull request.
