### ISSUE TITLE
How to remotely start a Akka actor: akka-in-action\chapter-remoting

### ISSUE THREAD

**Issue by hwandonggit** [akka/akka#20347]
By following Akka documents, I can start two actors(front-end and back-end) on the same machine, and they can talk to each other. However, when I tried to deploy back-end actor to another machine(Linux), I hit error of start remoting: 

============ Multiple main classes detected, select one to run:
 [1] com.goticks.BackendMain  
 [2] com.goticks.BackendRemoteDeployMain  
 [3] com.goticks.FrontendMain  
 [4] com.goticks.FrontendRemoteDeployMain  
 [5] com.goticks.FrontendRemoteDeployWatchMain  
 [6] com.goticks.SingleNodeMain  

Enter number: 2
[info] Running com.goticks.BackendRemoteDeployMain  
INFO  [Slf4jLogger]: Slf4jLogger started  
INFO  [Remoting]: Starting remoting  
ERROR [NettyTransport]: failed to bind to /192.168.1.9:2551, shutting down Netty transport

192.168.1.9 is another machine. 

In backend.conf:
remote {
  enabled-transports = ["akka.remote.netty.tcp"]  
  netty.tcp {  
    #hostname = "0.0.0.0"  
    hostname = "192.168.1.9"  
    port = 2551  
  }  
}  

I have one basic question, when deploy and start a remote actor on remote JVM, do we need user login information to remote machine?

Thanks,

**Comment by johanandren** [comment]
Hi @hwandonggit please use the gitter channel (https://gitter.im/akka/akka) or the mailing list for questions (https://groups.google.com/forum/#!forum/akka-user)

Closing this as it isn't a bug or a feature request but rather a question.
