### ISSUE TITLE
Add HTTP security headers 

### ISSUE THREAD

**Issue by pawelprazak** [akka/akka#20357]
[OWASP](https://www.owasp.org/index.php/List_of_useful_HTTP_headers) lists the most common security related headers:

- X-Frame-Options
- X-Content-Type-Options
- X-XSS-Protection
- Content-Security-Policy
- Public-Key-Pins
- Strict-Transport-Security

Do you plan to add them, or is it out of scope? 

If I would to make a pull request, is this the right place to start:

- `akka.http.scaladsl.model.headers`
- `akka.http.javadsl.model.headers`
- `akka.http.impl.model.parser`

**Comment by ktoso** [comment]
Adding such is a good idea, however they should be backed by a stable RFC (not early draft) as our module needs to guarantee binary compatibility so we don't want to lock a type with a wrong signature.
Please have a look at the headers and feel free to open up a PR with specific ones so we can pull them in case-by-case.

Yes, that's the right spot for them.

Another thing to consider is if the headers need to change server behaviour in any way or not.

**Comment by 2beaucoup** [comment]
Yes. (+ `akka.http.impl.model.parser`)

**Comment by pawelprazak** [comment]
OK, so as far as I understand non of the above qualifies as stable RFC, therefore add them would jeopardize binary compatibility.

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
