### ISSUE TITLE
TcpHandlers hide exception

### ISSUE THREAD

**Issue by wangsan** [akka/akka#20361]
akka version 2.3.9

in trait TcpHandlers

`override def onException(ctx: ChannelHandlerContext, e: ExceptionEvent): Unit = {
    notifyListener(e.getChannel, Disassociated(AssociationHandle.Unknown))
    e.getChannel.close() // No graceful close here
  }`

why not print the exception when e is an exception

**Comment by drewhk** [comment]
Thanks for reporting. Do you want to contribute a fix?
