### ISSUE TITLE
ActorPublisher Request cannot be reused

### ISSUE THREAD

**Issue by durban** [akka/akka#20365]
Since version 2.4.4, the `ActorPublisherMessage.Request` case class is mutable (see #17037, #20225 and commit 85e06b35b13fecdcb2b8b74b865f8774f0de1132). This change results in the `Request` objects not being reusabe, i.e., if my `ActorPublisher` receives a `Request` message, it cannot send it to another one as is (because the message object is mutated in `aroundReceive`, and it will have no effect the second time).

A possible workaround, of course, is to copy the message, like this:
```scala
def copyReq(m: ActorPublisherMessage) = m match {
  case Request(n) => Request(n)
  case _ => m
}
```

**Comment by patriknw** [comment]
Why would you ever send it on to another publisher? That would wrong. Request should only come frome the stream that the publisher is connected to.

**Comment by durban** [comment]
It's _conceptually_ the same stream; my publisher is basically proxying requests/items to another (with some buffering and transformation involved). (BTW, this is not a really big problem, because it's easy to work around.)

**Comment by patriknw** [comment]
but I think you are breaking the Reactive Streams semantics if you do something like that

**Comment by ktoso** [comment]
RS semantics wise it's valid to do so, it's our Akka Request object specifics that make this not work. We should make sure to document it properly if no way around it.

**Comment by patriknw** [comment]
@ktoso what do you mean. If you have `ActorPublisher` A receiving `Request(10)` from its downstream subscriber and you send that as a message to `ActorPublisher` B that would mean that B can push 10 elements to its downstream subscriber even though it has not got any real demand. Have I misunderstood something here?

**Comment by ktoso** [comment]
Protocol wise there's nothing that forbids to send the exact same number of demand upstream as we've got from a downstream - it could assume "right, i'll be fused with them anyway, so I'll just relay demand as is" etc.

So at least specification wise I think it's fine (in a processor, to do so), the questions is no actual implementation and if it makes sense. Since we're inside an ActorPublisher we know we won't be fused, and the requested demand should correlate to our buffer space... so in that sense it's not a good idea, but also not illegal.

**Comment by patriknw** [comment]
There is no upstream for an `ActorPublisher`, it's not a subscriber. 
The setup as I understand it is:
```
P1 <- S1
P2 <- S2
```

`S1` requests for demand to `P1`.
`P1` sends the `Request` to `P2` as an actor message.
`P2` calls `onNext` to `S2`, but `S2` has not requested anything.

In conclusion, the mutable flag unintentionally is good for such abuse. Closing.

**Comment by ktoso** [comment]
Well I was talking about mixing ActorPublisher together with ActorSubscriber, there is an upstream there.
However we don't want people to write such a mix anyway – should write GraphStages instead, so I agree with closing.

**Comment by patriknw** [comment]
Even if that was the setup it would be wrong, then you would use the ActorSubscriber api for making the request. We agree.

**Comment by durban** [comment]
Fair enough, I can certainly accept that this is not recommended / supported.

Although in my specific case it cannot cause a problem, since the demand is real and will be satisfied by the second actor publisher. And yes, what I'm doing is, in a way, combining an ActorPublisher and a Subscriber. It's possible (even likely) that it could be done in a better way. I'll definitely take a look at the GraphStages API, thanks for the pointer! (Unfortunately my case is somewhat complicated further by the fact that I also want to combine it with a typed (as in [akka-typed](http://doc.akka.io/docs/akka/2.4.4/scala/typed.html)) actor.)
