### ISSUE TITLE
Allow registering custom MediaTypes, and do it non-globally

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20379]
In Spray this was done by exposing the `register()` method on `MediaTypes` however this has the downside of being global state – we must register custom types scoped to an ActorSystem.

**Comment by jrudolph** [comment]
Custom status codes and methods can be added by [configuring them in ParserSettings](https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala#L38). Probably that would be way to go for other kinds of customizations as well.

**Comment by ktoso** [comment]
Nice, that might be a nice way to go about it, thanks

**Comment by viktorklang** [comment]
:)
