### ISSUE TITLE
error messages arising from persistenceId duplicates could be more helpful

### ISSUE THREAD

**Issue by TimPigden** [akka/akka#20394]
Currently errors in persistenceId naming lead to nasty internal clashes which get reported through error messages like
Invalid replayed event [1] in buffer from old writer

Since this is an api user error rather than a core akka error, the error should be more obvious or helpful, suggest inclusion of text "possible persistenceId name duplication" in the error text.

Also maybe some paragraph on trouble-shooting in the akka docs. One problem is this error can manifest in different ways but at the time of creating two persistors with conflicting ids you get no warning.

A better solution would be to detect the problem when the it first arises - i.e. first time two active persistors use the same id - but I've no idea whether this is practical

**Comment by poojadshende** [comment]
@TimPigden and @patriknw . I want to start working on this issue, but I am new to akka so can you give some extra details about where and how to start with it.

**Comment by TimPigden** [comment]
In the first instance, merely changing the error message (which you can
easily find by searching the code base) would give people a hint, so I
guess it's really as simple as changing a string and doing a pull request.
But this only will show up a problem in certain circumstances - probably on
simultaneous recovery or something like that.
However, I don't know if the overall design has anywhere you could detect
the problem earlier

On 30 April 2016 at 23:01, poojadshende <notifications@github.com> wrote:

> @TimPigden <https://github.com/TimPigden> and @patriknw
> <https://github.com/patriknw> . I want to start working on this issue,
> but I am new to akka so can you give some extra details about where and how
> to start with it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/20394#issuecomment-215997901>
>



-- 
Tim Pigden
Optrak Distribution Software Limited
+44 (0)1992 517100
http://www.linkedin.com/in/timpigden
http://optrak.com
Optrak Distribution Software Ltd is a limited company registered in England
and Wales.
Company Registration No. 2327613 Registered Offices: Suite 6,The Maltings,
Hoe Lane, Ware, SG12 9LR England
This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Optrak Distribution Software Ltd. If you are not the
intended recipient of this email, you must neither take any action based
upon its contents, nor copy or show it to anyone. Please contact the sender
if you believe you have received this email in error.

**Comment by patriknw** [comment]
Yes, this ticket is about improving the log message and documentation. Contribution is very much welcome.

**Comment by sourcekick** [comment]
We just came accross the same symptom in our application.

**Comment by michaelom** [comment]
#20301 this is somehow related:
