### ISSUE TITLE
Allow using Route Test Kit for testing local/remote web services

### ISSUE THREAD

**Issue by stanch** [akka/akka#20393]
I think Test Kit is great and it’s really a shame that we have to dispense with the nice syntax it offers when testing external web services or doing system tests. In those cases there is no `Route`, but an HTTP client can be used to provide a function `HttpRequest => Future[HttpResponse]`. The problem is that `RouteTestResult`, which is needed for the `check` DSL to work, can only be initialized within the `akka.http.scaladsl.testkit` package. Other than that, it seems straight-forward to initialize `RouteTestResult` from an `HttpResponse`. Here is what it takes:

```scala
implicit def injectIntoPipeline(
  implicit timeout: RouteTestTimeout,
  defaultHostInfo: DefaultHostInfo,
  executionContext: ExecutionContext
): TildeArrow[HttpRequest, Future[HttpResponse]] { type Out = RouteTestResult } =
  new TildeArrow[HttpRequest, Future[HttpResponse]] {
    type Out = RouteTestResult
    def apply(request: HttpRequest, pipeline: HttpRequest => Future[HttpResponse]): Out = {
      val routeTestResult = new RouteTestResult(timeout.duration)
      pipeline(request) foreach { response =>
        routeTestResult.handleResult(RouteResult.Complete(response))
      }
      routeTestResult
    }
  }
```

With this added to `akka.http.scaladsl.testkit.RouteTest`, the following can be done:

```scala
// define your HTTP pipeline (I think this is what it was called in Spray)
def pipeline(
  implicit system: ActorSystem, materializer: Materializer, ec: ExecutionContext
): HttpRequest => Future[HttpResponse] = { request =>
  Http().singleRequest {
    request
      .withUri(???) // add your custom host/port
      .withHeaders(???) // add your custom auth
  }
}

// test away
val request = Json.obj("foo" -> "bar")
Post("/v1.1/api", request) ~> pipeline ~> check {
  // your custom checks
}
```

**Comment by ktoso** [comment]
It's an interesting idea, and we might consider pull requests if you'd like to contribute it as a feature.
In the team we won't be able to focus on this for now - there's more urgent fish to fey.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
