### ISSUE TITLE
Enable serialization for akka.actor.Identify and akka.actor.ActorIdentity

### ISSUE THREAD

**Issue by fsat** [akka/akka#20395]
For the purpose of protocol backward compatibility, the PR #20380 implements the serialization for `akka.actor.Identify` and `akka.actor.ActorIdentity` but they are disabled.

The serialization/deserialization for `akka.actor.Identify` and `akka.actor.ActorIdentity` are required for cluster client to work.

**Enable the serialization/deserialization for these classes when backward compatibility change is introduced in Akka.**

**Comment by ktoso** [comment]
This will be solved in 3.0, by switching on the serialization by default

**Comment by raboof** [comment]
This has been enabled in #21339 (97e0629)
