### ISSUE TITLE
akka-http: documentation broken link

### ISSUE THREAD

**Issue by atemerev** [akka/akka#20409]
Where: http://doc.akka.io/docs/akka/2.4.4/scala/http/routing-dsl/websocket-support.html ("Example" section)

Broken link: http://github.com/akka/akka/tree/v2.4.4/akka-docs-dev/rst/scala/code/docs/http/scaladsl/server/WebSocketExampleSpec.scala

Should be: https://github.com/akka/akka/blob/v2.4.4/akka-docs/rst/scala/code/docs/http/scaladsl/server/WebSocketExampleSpec.scala

**Comment by ktoso** [comment]
Thanks a lot for noticing! Would you like to submit a PR fixing this typo?

**Comment by atemerev** [comment]
Sure! https://github.com/akka/akka/pull/20410

**Comment by ktoso** [comment]
Thank you! :)
