### ISSUE TITLE
Allow different ActorMaterializer subtypes

### ISSUE THREAD

**Issue by kkasravi** [akka/akka#20414]
Small changes in either private[stream] class visibility or private method are required in order to allow other implementations in addition to the existing ActorMaterializerImpl.

**Comment by kkasravi** [comment]
ActorMaterializerImpl is specifically referenced in GraphInterpreterShell's constructor as well as SubFusingActorMaterializerImpl. Other minor changes (private->protected) are required to MaterializerSession. Several private[stream] class definitions need to be removed.

**Comment by patriknw** [comment]
sounds good

**Comment by johanandren** [comment]
Isn't `GraphInterpreterShell` an implementation detail rather than something an alternative `Materializer` would use?

**Comment by johanandren** [comment]
Ah, sorry, my brain autocorrected the title from "different ActorMaterializer subtypes" to "different Materializer subtypes".

**Comment by kkasravi** [comment]
GraphInterpreterShell in some ways is a detail - however we have a local and remote materializer. The local is similar to ActorMaterializerImpl except it looks for certain custom stages that bridge local and remote event flows.

**Comment by drewhk** [comment]
@patriknw should we add this do the current sprint? This is not a hard thing to solve as far as I see, so might just fit.

**Comment by patriknw** [comment]
@kkasravi will submit a pull request that we will review, yes that is in scope of the sprint, no problem

**Comment by kkasravi** [comment]
@drewhk @patriknw thanks.
