### ISSUE TITLE
Akka HTTP Java DSL: com.fasterxml.jackson.databind.exc.InvalidFormatException returns internal server error

### ISSUE THREAD

**Issue by dialtahi** [akka/akka#20417]
Serializing HTTP body with RequestVal.entityAs, if the json is not well formed, Akka HTTP throws 500 - Internal Server Error when com.fasterxml.jackson.databind.exc.InvalidFormatException is thrown. I think it should throw 400 - Bad request like Spring.

`private RequestVal<Command> command = RequestVals.entityAs(Jackson.jsonAs(Command.class));`

**Comment by ktoso** [comment]
RequestVals are on their way out, hopefully to be removed next week.
Thanks for reporting though - please look out for the new JavaDSL, work in progress here: https://github.com/akka/akka/pull/20088

**Comment by ktoso** [comment]
Note that you can register a RejectionHandler that will make this into a 400 :)
