### ISSUE TITLE
Custom modeled headers for the Java DSL

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20415]
In the Scala DSL we have `CustomModeledHeader` and `CustomModeledHeaderCompanion` for creating custom headers that feels and behaves like the built in set of headers, it is also useful for more complicated headers where the value is something more complicated than just a string, something that needs to be parsed.

The Java DSL should provide something that mirrors this. Not quite sure about the requirements (should the Scala DSL parse Java DSL modeled headers etc?). 

Came out of this ticket #20358 (allowing the Java DSL parse custom headers written in Scala)

**Comment by johanandren** [comment]
(Note that this ticket cannot be done until the new Java DSL is merged to master)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
