### ISSUE TITLE
Scheduler stopping after tick-duration * Int.MaxValue

### ISSUE THREAD

**Issue by ecartner** [akka/akka#20424]
I was asked to submit an issue based on this Akka-User thread: [Scheduler overflow](https://groups.google.com/d/msg/akka-user/kElNJvMojLA/Wuq9xA3eBwAJ)

I've got an application with a crude bitrate throttle - a transmitter actor receives a ByteString, writes it to a MulticastSocket and then schedules an acknowledgement that it is ready for more data. The ack goes to whomever sent the ByteString. The transmitter actor schedules delivery of the ack via scheduleOnce using a small delay (typically around 8 ms). In this system I've dropped the scheduler tick duration down to 2ms.

My application runs great except it stops transmitting after approximately 50 days (actually a little under 50 days). The 50 day stop is completely repeatable and happens on both Linux and OS X environments. No exceptions or anything else unusual in the logs. The rest of the application is completely functional. It's just not sending any more data. I keep thinking that it acts like the transmitter has stopped sending acks.

It came to my attention a few days ago that my tick-duration (2ms) when multiplied by Int.MaxValue comes out to be 49 days, 17 hours and change.

As suggested in the Akka-User thread I wrote a test that also seems to indicate the scheduler stops behaving properly after Int.MaxValue ticks. Here is the test that I added to `LightArrayRevolverSchedulerSpec`:

    "correctly wrap around ticks" in {
      val numEvents = 16
  
      // val targetTicks = Int.MaxValue - numEvents - 2   // Passes
      val targetTicks = Int.MaxValue - numEvents - 1    // Fails

      val cfg = ConfigFactory.parseString("akka.scheduler.tick-duration=2ms")
      withScheduler(config = cfg) { (sched, driver) ⇒
        implicit def ec = localEC
        import driver._

        val start = step / 2

        wakeUp(step * targetTicks)
        probe.expectMsgType[Long](50 seconds)

        val nums = 0 until numEvents
        nums foreach (i ⇒ sched.scheduleOnce(start + step * i, testActor, "hello"))
        expectNoMsg(step)
        wakeUp(step)
        expectWait(step)
        nums foreach { _ ⇒
          wakeUp(step)
          expectMsg("hello")
          expectWait(step)
        }
      }
    }

As noted with a comment in the test, if `targetTicks` is `Int.MaxValue - numEvents - 2` or less, the test passes. Values of `targetTicks` above that cause the test to fail.

I will also note that this test is *slow*. On my machine it takes around 45 seconds. The time the test takes when added to the other tests will cause LARSSpec to take longer than 60 seconds. At the one minute mark the test setup makes the assumption that something has gone wrong and interrupts the test process. To get around this I created a separate spec that copied in the pieces it needed from LARSSpec. I've put that spec up as a [gist](https://gist.github.com/ecartner/13fb020d25e67e196eb6d7d62a58f6bb).

E.T.A. - My application is built using Akka 2.3.12 the tests I've been running are using Akka 2.4.4.

**Comment by patriknw** [comment]
Thanks for creating the reproducer @ecartner 
It fails when I try it, but I don't know what is wrong yet.

**Comment by patriknw** [comment]
The task is executed, but after the tick wrap around the `sleepTime` is wrong (negative).

    val sleepTime = start + (tick * tickNanos) - time

**Comment by ecartner** [comment]
I came up with a fix by adding "tickRollovers" as a var to LARS. I thought about making _tick_ a Long but didn't want to risk breaking some of the logic that already assumes rolls over at the Int size.

    val sleepTime = start + (tick * tickNanos) - time

became

    val totalTicks = tickRollovers * 4294967296L + tick
    val sleepTime = start + (totalTicks * tickNanos) - time

and

    tick += 1

became

    if (tick == Int.MaxValue) tickRollovers += 1
    tick += 1

The underlying issue (sleepTime going negative remains) but by my math, even with a 1ms tick-duration rollover won't occur until the scheduler has been running for 150 million years.

**Comment by patriknw** [comment]
great, I also came up with a very similar solution, please review: https://github.com/akka/akka/pull/20435

**Comment by patriknw** [comment]
I think this is serious enough to deserve backport to 2.3.x: https://github.com/akka/akka/pull/20465
