### ISSUE TITLE
sending Status.Success to input Source.actorRef causes exception, stream abortion

### ISSUE THREAD

**Issue by timcharper** [akka/akka#20421]
When I send `Status.Success` to an input `actorRef`, I would expect that the stream would continue to drain whatever elements are inflight (and buffered), and then for the stream to complete successfully.

Instead, what I'm observing (with akka 2.4.4) is that sending this message is causing the stream to come crashing down. This used to work, so I believe this is a regression.

See the gist for a repro case and log output:

https://gist.github.com/timcharper/24aeb204b9587a55cdbc61db969261ae

Notice that the output indicates that dropping element 28, but only up to element 16 is processed. The 11 elements 17-27 (10, plus I presume one element being buffered by the async boundary  or conflate) is dropped. The stream crashes because it's trying to cast `Status.Success` to an `Int`; the documentation ([here](https://gist.github.com/timcharper/24aeb204b9587a55cdbc61db969261ae)) states that I can send `Status.Success` to gracefully stop this ingestion actor:

> The stream can be completed successfully by sending the actor reference an akka.actor.Status.Success message in which case already buffered elements will be signaled before signaling completion, or by sending a akka.actor.PoisonPill in which case completion will be signaled immediately.

Tim

**Comment by johanandren** [comment]
Hi tim, It seems you are sending the companion object of `Success` to the actor rather than a `Success`, which is what causes it to completed.

If you change `Status.Success` to `Status.Success(Done)` you will see that it works.

**Comment by ktoso** [comment]
If you think about it... technically we could accept the companion object too actually, since we drop the value of Success anyway? Reopen and add support for this?

**Comment by timcharper** [comment]
If the Status object itself isn't meant to be a message, in the spirit of "be strict in what you accept" I'd be inclined towards updating the documentation for `Source.actorRef` to make it more clear that `Status.Success` is a case class, and not a case object.

**Comment by johanandren** [comment]
I think `Status.Success(ignoredValue)` was a pretty bad design decision to start with, I think if we fix it in any way it should be adding a distinct and specific singleton message `Complete` or something like that.

Sorry if I was a bit quick to close the ticket.

**Comment by timcharper** [comment]
What if `Status.Success$` is made to implement `Status.Success` ?

**Comment by timcharper** [comment]
I went to help improve the documentation and noticed 34d51dcd001a3917bda3272751195e9f0e863b02. 👍

**Comment by ktoso** [comment]
Hah, yeah I remembered there were improvements in the docs, forgot it's not released yet.
Still thinking if we could support the companion here in any case.

**Comment by timcharper** [comment]
It is possible to have the companion object of a case class extend the class for which it's a companion; however, I get the sense that such an approach may be unidiomatic.

```
scala> case class Thing(n: Int); object Thing extends Thing(0) { }
defined class Thing
defined object Thing

scala> Thing match { case Thing(v) => v }
<console>:15: error: constructor cannot be instantiated to expected type;
 found   : Thing
 required: Thing.type
       Thing match { case Thing(v) => v }
                          ^

scala> Thing.asInstanceOf[Any] match { case Thing(v) => v }
res6: Int = 0
```

It's unfortunate that overriding the companion object causes the `.tupled` method to be removed :( Although, it does seem like such a change could be made without breaking backwards binary compatibility.

Thoughts?

**Comment by patriknw** [comment]
I think we should simply add another receive case that accepts the companion

**Comment by johanandren** [comment]
Two votes against me, let's make it accept the companion object of `Success`
