### ISSUE TITLE
Feature Request: `replay-max` for PersistentActor during recovery

### ISSUE THREAD

**Issue by michaelom** [akka/akka#20437]
There is a configuration property for `PersistentView`s to configure the maximum number of messages to replay per incremental view update. 

```
view {
        auto-update-replay-max = -1
    }
```

However, there is no corresponding property for PersistentActors during *recovery*. Recovery customization has to be configured programmatically:

Java-API:
```
    @Override
    public Recovery recovery() {
        return Recovery.create(SnapshotSelectionCriteria.latest(), Long.MaxValue(), 2000);
    }
```

It would be convenient to be able to configure the `replayMax` property with a configuration entry.

**Comment by patriknw** [comment]
but how often is it that you don't replay the complete history of a persistent actor?

**Comment by michaelom** [comment]
>but how often is it that you don't replay the complete history of a persistent actor?

I fixed the recovery snipped.
It's not about replaying a partial event stream. It's about the 3rd parameter (`replayMax`). For very large event streams I run into problems when using the default `Long.MaxValue()`:

```
Recovery.create(SnapshotSelectionCriteria.latest(), Long.MaxValue(), 2000);
```

**Comment by ktoso** [comment]
What problems specifically?

Replaying the entire stream of events for a PA is the typical case, the "weird odd case" is replaying just a few events, thus it's accessible via code, and not globally.

**Comment by michaelom** [comment]
I misinterpreted the semantics of `replayMax`. Should have read the docs more carefully.
I'll close the issue. 

Thanks for clarifying.

**Comment by ktoso** [comment]
Cool, glad you found it make sense in the end then :-)
Happy hakking!
