### ISSUE TITLE
Http.ServerBinding.unbind should return Future[Done]

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#20438]
Instead of `Future[Unit]`.

**Comment by ktoso** [comment]
Thanks for the ticket, sadly this slipped back then and changing this is not source compatible, so we'll have to do it in Akka 3.0 or introduce a different method and deprecate the current...

I don't have a good alternative name for unbind (for shutdown we did terminate - similar story), so likely to wait a round on this.

**Comment by hseeberger** [comment]
Let's go for 3.0 then. Thanks.

**Comment by poojadshende** [comment]
@ktoso, can we start working on it now or have to wait for 3.x

**Comment by ktoso** [comment]
We don't have a branch for 3.x yet, let's wait with this one for a while.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
