### ISSUE TITLE
Different behavior when turning off auto-fusing

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#20434]
I have created a non-trivial stream topology in Akka SSE (see [ServerSentEventClient](https://github.com/hseeberger/akka-sse/blob/server-sent-event-client-no-auto-fusing-off-bug/akka-sse/src/main/scala/de/heikoseeberger/akkasse/pattern/ServerSentEventClient.scala)) to implement a client pattern which continuously sends another request when the source provided by a request has completed. All goes well with auto-fusing turned on (default), but once turned off the tests fail.

To take a look at the issue go to the [server-sent-event-client-no-auto-fusing-off-bug8](https://github.com/hseeberger/akka-sse/tree/server-sent-event-client-no-auto-fusing-off-bug) branch and run the [ServerSentEventClientSpec](https://github.com/hseeberger/akka-sse/blob/server-sent-event-client-no-auto-fusing-off-bug/akka-sse/src/test/scala/de/heikoseeberger/akkasse/pattern/ServerSentEventClientSpec.scala) test. Auto-fusing can be turned on and off in [application.conf](https://github.com/hseeberger/akka-sse/blob/server-sent-event-client-no-auto-fusing-off-bug/akka-sse/src/test/resources/application.conf).

**Comment by drewhk** [comment]
What is the actual error here? Is it a specific case, or is it because you find it surprising that fusing can alter behavior? 

In general, the presence/absence of fusing might
 - expose or hide races
 - expose or hide deadlocks

Due to differences in buffer sizes, prefetch, and concurrency. These cannot be fixed.

Anyway, a minimized reproducer might be interesting to look at if there is a real underlying bug.

**Comment by hseeberger** [comment]
@drewhk, you are right: I'm not sure where to find the bug, maybe it's in my code. Let's keep this open for a little while, I might get back to it soon.

**Comment by drewhk** [comment]
I am not sure yet whether there is a bug or not, but it would be interesting to see anyway what exactly caused the change in semantics.

**Comment by hseeberger** [comment]
Well, feel free to take a look: I think it's quite minimized.
