### ISSUE TITLE
Observing the state of the cluster client

### ISSUE THREAD

**Issue by huntc** [akka/akka#20446]
We wish to observe changes to the state of contact points in the cluster client. Our use-case is that we persist the list of contact points in the event that the cluster client process is restarted.

We would also prefer to receive a notification of the new list of contact points as changes occur, rather than poll for this data.

**Comment by patriknw** [comment]
Sounds good.
The simplest solution would be to publish the notifications on the eventBus. That also means that the api of the ClusterClient doesn't have to change. An alternative would be to have an explicit subscription registration on the ClusterClient itself.

**Comment by huntc** [comment]
Should the provided eventStream be used for this purpose?

**Comment by patriknw** [comment]
that is perfectly fine usage of the `ActorSystem.eventStream`

**Comment by huntc** [comment]
OK - I'll start a PR now then.

**Comment by patriknw** [comment]
great, thanks
