### ISSUE TITLE
KillSwitches is missing in stages overview

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20441]
stages_overview should contain the various kill switches in `akka.stream.KillSwitches`

**Comment by drewhk** [comment]
Should they? I am not sure everything should be listed there, only the things that are provided by Flow, Source et.al directly. We should rather have a new documentation chapter about dynamic streams handling once Hub is implemented.

**Comment by johanandren** [comment]
The name of the section is `Overview of built-in stages and their semantics` and this is built in stages. 

Currently there is no other one place for users to find all the available built in stages as they are spread out across the `*Ops`, extra factories and some standalone stages. The Java interop stages in `StreamConverters` are for example already listed in there.

That does not mean there should not also be a section about dynamic streams in the future.

**Comment by drewhk** [comment]
There is Framing and TCP for example. I see no point cramming everything
that provides a Flow into that chapter. Originally that page was about
combinators mainly, I don't feel KillSwitch counts as a combinator. I guess
it is a question then what should be the purpose of this page. Maybe we
should create a cheat-sheet instead (although that needs to be a proper PDF
document to be really compact in layout and printable).

-Endre

**Comment by ktoso** [comment]
Separate page sounds good, An index of all of them would also be maybe interesting..

**Comment by agolubev** [comment]
@johanandren should we close this ticket?

**Comment by johanandren** [comment]
Yes, seems like it was missed when merging.
