### ISSUE TITLE
ActorRef compression for new remote messaging

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20455]
Realtes to: https://github.com/akka/akka/issues/20312

Implement [ActorRef Compression](https://github.com/akka/akka-meta/issues/16) as explained on akka-meta.

**Comment by guidomedina** [comment]
One idea:

During a node joining the cluster, the cluster can agree on an identifier for a node, a node can be identified with an `int` (4 bytes) and the actor can be identified with a `long` (8 bytes), both primitives rendering to a total of 12 byes.

The only problem there is to render the toString() of an actor's address.

**Comment by guidomedina** [comment]
Or maybe the node address part can be identified as an `int` and the path part keep it as is for now.
