### ISSUE TITLE
Consider "hot" connection pool option, to always keep at least one connection open

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20456]
This seems to be interesting for users who exactly know with which host they'll be communicating,
and would like to minimise the occasional "longer latency on first request, which causes a new connection to be established".

We could expose an option to Pools that would be the number of hot connections to be kept open perhaps?

I have not seen any other HTTP client provide this option to be honest, however the question did come up a number of times.

**Comment by ktoso** [comment]
Triaged but we won't work on it in the foreseeable future, please feel free to contribute!

**Comment by ktoso** [comment]
Got some community interest in contributing this, I think it makes sense since heard the request of "first request after a while is too slow!" from some customers and people.
It's not something other http clients do, but it's also relatively simple to do for us since pools are explicit.

If anyone wants to veto this would be nice to veto now before contributors start working on it please :-)
@2beaucoup @drewhk @jrudolph

**Comment by 2beaucoup** [comment]
We already have the `max-connections` setting so let's add `min-connections` (default = 0).

Connections are only closed after `idle-timeout` if nr. of connections > `min-connections`. Connections are automatically instantiated on startup or after connection close by peer and nr. of connections < `min-connections`.

WDYT?

**Comment by ktoso** [comment]
Exactly, I think this makes a lot of sense :-)

FYI, up for grabs then @pjazdzewski1990 @note @krzemin @kwyczesany :-) 
Thanks in advance, and let me know if you're stuck or need any hints.

**Comment by pjazdzewski1990** [comment]
I'm looking on this ticket right now - trying to follow the solution proposed above. Could you point me to a place where connections are being managed (created/closed)? 
The closest thing I've found is https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala#L149

**Comment by ktoso** [comment]
Right, almost in the right region there. So those Actors, PoolInterface and the Master are about "the pool" as a whole, here we need to care about the connections inside the pool - so we'll go to PoolFlow (line `PoolFlow(Flow[HttpRequest].viaMat(connectionFlow)(Keep.right), settings, setup.log)`). Check the PoolFlow's diagram to see what's going on there. So we need to keep alive at least min-connections connections there.

Let's go from the outside: 
- the option needs to be added to `ConnectionPoolSettings`, you'll notice that's not trivial, but also not hard; we do this because of binary compatibility.
- instead in the `PoolInterfaceActor` (that's "a connection"), step up to `PoolMasterActor` (that's "the pool")
- boyscout: please make a props method on the PoolInterfaceActor companion and use it instead in-line Props(new) in the Master
- The Interface Actor does not need one change though I think, which is that if min-connections is > 0 we should not trigger the idle timeout on it (the pool shuts down if it's doing nothing, and connections independently can shut down if they do nothing, so we do not want the pool to die since we want to keep the connections)
- inside PoolFlow, we should change the `.tabulate(maxConnections)(PoolSlot(_, connectionFlow, settings))` to create `minConnections` `PoolSlot`'s that will now be notified it they should be hot or not (constructor param), if they're hot, they should not shut down based on the timeout.
- PoolSlot has to know as well if it's "hot" or not, if it is - then we make sure that the actual running thing so the `SlotProcessor`, gets this option as well (needs param), and if it is "hot"
- it should `val (connInport, connOutport) = runnableGraph.run()` _right away_, instead of waiting to do this when the first `OnNext()` arrives (on next signals are "request coming in"), so the current implementation is lazy in that sense that it starts the connection once the first request comes in, with the min-connections we'll start connections ASAP. (again, only minConnections, not more).

There likely is something about timeouts that I just missed, but if you get progress a bit into the direction please share the PR soon (even if it's a draft) and we'll review and help to continue from there :-)
If anything is unclear, ping us on the chat or here :-)

**Comment by ktoso** [comment]
Sure, I'll get to it soon :)

**Comment by 2beaucoup** [comment]
@ktoso:

> - inside PoolFlow, we should change the .tabulate(maxConnections)(PoolSlot(_, connectionFlow, settings)) to create minConnections PoolSlot's that will now be notified it they should be hot or not (constructor param), if they're hot, they should not shut down based on the timeout.
> - PoolSlot has to know as well if it's "hot" or not, if it is - then we make sure that the actual running thing so the SlotProcessor, gets this option as well (needs param), and if it is "hot"

[Had to disagree](https://github.com/akka/akka/pull/20723/files#r65868568) on these two points.

IMO the distinction between hot/cold is unnecessary. The conductor needs to be changed to do the bookkeeping and the slots should basically stay the same.

The slots currently react on `RequestContext`s (via `SwitchCommand`). This could be changed to communicate raw connect cmds without context for eager connects.

**Comment by pjazdzewski1990** [comment]
@2beaucoup You suggest moving the logic to keep connections alive to `akka.http.impl.engine.client.PoolConductor`. So instead the slots knowing that they shouldn't die, they would be managed by PoolConductor in such a way that a certain number is alive, while keeping the slots not aware about their 'hot' nature. Did I understood you correctly?
Part of the task (as I understood) was to start `PoolSlot` eagerly. How would that be done in the approach you suggested? Does your approach also affect `PoolInterfaceActor.shouldStopOnIdle` or is it ok?

**Comment by 2beaucoup** [comment]
> Did I understood you correctly?

:+1: exaclty.

> Part of the task (as I understood) was to start `PoolSlot` eagerly. How would that be done in the approach you suggested?

Inside `SlotSelector` invoke the current `onPush` logic `min-connection` times emitting the new `ConnectCommand` msg instead of `SwitchCommand` resulting in `Idle` slot states.

> Does your approach also affect `PoolInterfaceActor.shouldStopOnIdle` or is it ok?

`shouldStopOnIdle` looks good!

**Comment by ktoso** [comment]
Good points @2beaucoup, thanks!

> The slots currently react on RequestContexts (via SwitchCommand). This could be changed to communicate raw connect cmds without context for eager connects.

Yeah this sounds much cleaner than my proposal 👍

**Comment by pjazdzewski1990** [comment]
Awesome. I will try to move the logic from `PoolSlot` and `PoolFlow` into `PoolConductor`

**Comment by 2beaucoup** [comment]
Maybe @sirthias has any thoughts on this one.

BTW: Wondering if the `easy-to-contribute` label should be removed.

**Comment by ktoso** [comment]
> BTW: Wondering if the easy-to-contribute label should be removed.

Nein. We need to move tickets which the core team has no time to direct attention to into the communities focus. Currently this is how we do so. Also, with @pjazdzewski1990 and others I've agreed to spend more time helping them out so that they can become more proficient with the code base and contribute such things – we need to grow our comitter base (and will make this more official soon) in order to keep this project (akka http specifically, due to large surface) healthy and fast moving as people expect it to.

**Comment by pjazdzewski1990** [comment]
I'm not giving up on this one, if this is what you are afraid ;) (Insert Rick Astley picture here)

**Comment by 2beaucoup** [comment]
Not at all! Was only afraid that the "easy" part could be misleading.

**Comment by ktoso** [comment]
> Not at all! Was only afraid that the "easy" part could be misleading.

Yeah, I totally agree here. We used to have the "community contrib" tag which was renamed to the "easy" one. I think `community-contrib` should make a come-back, in addition to the easy one perhaps?
This is something we'll work out next week.

**Comment by 2beaucoup** [comment]
:+1: sounds perfect!

**Comment by pjazdzewski1990** [comment]
@2beaucoup There's one last thing that I don't I don't understand ...
I took a deep dive into `PoolConductor` trying to follow the plan you outlined. I see that currently the communication looks like this: `SlotSelector` --[SlotCommand being SwitchCommand or SlotShouldConnectCommand]--> `Route` --[RequestContext]--> `SlotProcessor` --- ...
As I understood we want to give a hint to the Slots that they should start immediately. I could inherit from/wrap a `RequestContext`, but it doesn't feel right to send it using the 'main' in-stream. 
I was thinking about adding a dedicated channel for "maintenance", but it might overengineering. Any opinions on that?

**Comment by 2beaucoup** [comment]
I see.

Would changing
```scala
private case class SwitchCommand(rc: RequestContext, slotIx: Int)
```
to
```scala
private sealed trait SlotCommand {def slotIdx: Int }
private case class Dispatch(slotIx: Int, rc: RequestContext)
private case class Connect(slotIx: Int)
```
work?

**Comment by pjazdzewski1990** [comment]
I've managed to get that far. The next step is confusing. Take a look [here](https://github.com/akka/akka/pull/20723/files#diff-0dc3503e2c7e4c93cd4b99e13e236cacR228) -I've pushed my current code.
The output of `PoolConductor` is a stream of `RequestContext`s. After my changes it will produce contexts AND messages causing instant connections. This **AND** is the problem.
I'm not sure how to make it work in an elegant way - I could return something connected to `RequestContext` or create a separate stream to pass this kind of info. I also cannot (I think) just create a fresh `RequestContext` to trick the Slot into connecting.

**Comment by 2beaucoup** [comment]
@pjazdzewski1990 I did a quick experiment [here](https://github.com/2beaucoup/akka/commit/1c89d705db5fc9ada290f4b0b7bedbe7101c066b) but didn't have the time to properly test it.

The `SwitchCommand` wraps a `SlotCommand` which can be `Dispatch[RequestContext]`or `Connect`. The pool conductor's route consumes `SwitchCommand`s and emits `SlotCommand`s.

**Comment by pjazdzewski1990** [comment]
Ok, so I see you would go with modifying the external behaviour of `PoolConductor`. 
I will do as suggested.

**Comment by ktoso** [comment]
Took quite some work, but great feature! Thanks a lot @pjazdzewski1990
