### ISSUE TITLE
Great getting started ticket: write example snippets for Akka HTTP Java DSL

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20466]
The last couple of months we have been hard at work with providing a DSL for Java that is (almost) as neat as the Scala DSL for Akka HTTP. We are now at the point where we have the API in place in master and basic docs but what is missing is examples for each of the directives. 

Providing an example for a directive is a perfect way to start contributing to Akka, each directive is sufficiently isolated, and there is a corresponding Scala example to base the sample on.

How to do it:
* **Select a directive below**, **write a comment** that you will be working on it
* **Read the docs**, [the corresponding Scala directive docs]file(http://doc.akka.io/docs/akka/2.4.4/scala/http/routing-dsl/directives/alphabetically.html#predefined-directives) and make sure you understand what the directive does
* Look at **the Scala example** in `akka-docs/rst/scala/code/docs/http/scaladsl/server/directives` and port it to a Java example in `akka-docs/rst/java/code/docs/http/javadsl/server/directives`. Look at the existing Java samples to see how the tests should be set up
* **Run the test using** `akka-docs/testOnly docs.http.javadsl.server.directives.YourDirective`
* **Include the test in the docs** by adding comments with the label from the `.rst` documentation of the directive. 
* **Generate the docs** using `akka-docs/sphinx:generateHtml` and see that the sample is included in the docs and looks nice (you will find the docs generated as HTML under akka-docs/target/sphinx/html/index.html` so that you can preview in your browser)
* **Make a PR** to have the sample reviewed and merged into Akka HTTP

**Directives to provide samples for**
(all paths relative to `akka-docs/rst/java/http/routing-dsl/directives`)
- [x] basic-directives/cancelRejection.rst thanks @Hawstein!
- [x] basic-directives/cancelRejections.rst thanks @Hawstein!
- [x] basic-directives/extract.rst thanks @Hawstein!
- [x] basic-directives/extractExecutionContext.rst thanks @Hawstein!
- [x] basic-directives/extractLog.rst thanks @Hawstein!
- [x] basic-directives/extractMaterializer.rst thanks @Hawstein!
- [x] basic-directives/extractRequest.rst thanks @Hawstein!
- [x] basic-directives/extractRequestContext.rst thanks @Hawstein!
- [x] basic-directives/extractSettings.rst thanks @Hawstein!
- [x] basic-directives/extractUnmatchedPath.rst thanks @Hawstein!
- [x] basic-directives/extractUri.rst thanks @Hawstein!
- [x] basic-directives/mapInnerRoute.rst thanks @Hawstein!
- [x] basic-directives/mapRejections.rst thanks @Hawstein!
- [x] basic-directives/mapRequest.rst thanks @Hawstein!
- [x] basic-directives/mapRequestContext.rst thanks @Hawstein!
- [x] basic-directives/mapResponse.rst thanks @Hawstein!
- [x] basic-directives/mapResponseEntity.rst thanks @Hawstein!
- [x] basic-directives/mapResponseHeaders.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResult.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultPF.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultStage.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultWith.rst thanks @Hawstein!
- [x] basic-directives/mapRouteResultWithPF.rst thanks @Hawstein!
- [x] basic-directives/mapSettings.rst thanks @Hawstein!
- [x] basic-directives/mapUnmatchedPath.rst thanks @Hawstein!
- [x] basic-directives/pass.rst thanks @Hawstein!
- [x] basic-directives/provide.rst thanks @Hawstein!
- [x] basic-directives/recoverRejections.rst thanks @Hawstein!
- [x] basic-directives/recoverRejectionsWith.rst thanks @Hawstein!
- [x] basic-directives/withExecutionContext.rst thanks @Hawstein!
- [x] basic-directives/withLog.rst thanks @Hawstein!
- [x] basic-directives/withMaterializer.rst thanks @Hawstein!
- [x] basic-directives/withSettings.rst thanks @Hawstein!
- [x] coding-directives/decodeRequest.rst thanks @Hawstein!
- [x] coding-directives/decodeRequestWith.rst thanks @Hawstein!
- [x] coding-directives/encodeResponse.rst thanks @Hawstein!
- [x] coding-directives/encodeResponseWith.rst thanks @Hawstein!
- [x] coding-directives/responseEncodingAccepted.rst thanks @Hawstein!
- [x] cookie-directives/cookie.rst thanks @Hawstein!
- [x] cookie-directives/deleteCookie.rst thanks @Hawstein!
- [x] cookie-directives/optionalCookie.rst thanks @Hawstein!
- [x] cookie-directives/setCookie.rst thanks @Hawstein!
- [x] debugging-directives/logRequest.rst thanks @fagossa!
- [x] debugging-directives/logRequestResult.rst thanks @fagossa!
- [x] debugging-directives/logResult.rst thanks @fagossa!
- [x] execution-directives/handleExceptions.rst thanks @Hawstein!
- [x] execution-directives/handleRejections.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromBrowseableDirectories.rst thanks @Hawstein! 
- [x] file-and-resource-directives/getFromBrowseableDirectory.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromDirectory.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromFile.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromResource.rst thanks @Hawstein!
- [x] file-and-resource-directives/getFromResourceDirectory.rst thanks @Hawstein!
- [x] file-and-resource-directives/listDirectoryContents.rst thanks @Hawstein!
- [x] file-upload-directives/fileUpload.rst thanks @gosubpl!
- [x] file-upload-directives/uploadedFile.rst thanks @gosubpl!
- [x] form-field-directives/formField.rst thanks @Hawstein!
- [x] form-field-directives/formFieldList.rst thanks @Hawstein!
- [x] form-field-directives/formFieldMap.rst thanks @Hawstein!
- [x] form-field-directives/formFieldMultiMap.rst thanks @Hawstein!
- [x] future-directives/completeOrRecoverWith.rst
- [x] future-directives/onComplete.rst
- [x] future-directives/onSuccess.rst
- [x] header-directives/headerValue.rst thanks @zhxiaogg!
- [x] header-directives/headerValueByName.rst thanks @zhxiaogg!
- [x] header-directives/headerValueByType.rst thanks @zhxiaogg!
- [x] header-directives/headerValuePF.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValue.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValueByName.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValueByType.rst thanks @zhxiaogg!
- [x] header-directives/optionalHeaderValuePF.rst thanks @zhxiaogg!
- [ ] marshalling-directives/completeWith.rst
- [ ] marshalling-directives/entity.rst
- [ ] marshalling-directives/handleWith.rst
- [ ] misc-directives/extractClientIP.rst
- [ ] misc-directives/rejectEmptyResponse.rst
- [ ] misc-directives/requestEntityEmpty.rst
- [ ] misc-directives/requestEntityPresent.rst
- [ ] misc-directives/selectPreferredLanguage.rst
- [ ] misc-directives/validate.rst
- [x] parameter-directives/parameter.rst thanks @Hawstein!
- [x] parameter-directives/parameterMap.rst thanks @Hawstein!
- [x] parameter-directives/parameterMultiMap.rst thanks @Hawstein!
- [x] parameter-directives/parameters.rst thanks @Hawstein!
- [x] parameter-directives/parameterSeq.rst thanks @Hawstein!
- [x] path-directives/path.rst thanks @fagossa !
- [x] path-directives/pathEnd.rst thanks @fagossa !
- [x] path-directives/pathEndOrSingleSlash.rst thanks @fagossa !
- [x] path-directives/pathPrefix.rst thanks @fagossa !
- [x] path-directives/pathPrefixTest.rst thanks @fagossa !
- [x] path-directives/pathSingleSlash.rst thanks @fagossa !
- [x] path-directives/pathSuffix.rst thanks @fagossa !
- [x] path-directives/pathSuffixTest.rst thanks @fagossa !
- [x] path-directives/rawPathPrefix.rst thanks @fagossa !
- [x] path-directives/rawPathPrefixTest.rst thanks @fagossa !
- [x] path-directives/redirectToNoTrailingSlashIfPresent.rst thanks @fagossa !
- [x] path-directives/redirectToTrailingSlashIfMissing.rst thanks @fagossa !
- [ ] range-directives/withRangeSupport.rst
- [x] respond-with-directives/respondWithDefaultHeader.rst thanks @felipefzdz!
- [x] respond-with-directives/respondWithDefaultHeaders.rst thanks @felipefzdz!
- [x] respond-with-directives/respondWithHeader.rst thanks @felipefzdz!
- [x] respond-with-directives/respondWithHeaders.rst thanks @felipefzdz!
- [x] route-directives/complete.rst
- [x] route-directives/failWith.rst
- [x] route-directives/redirect.rst
- [x] route-directives/reject.rst
- [x] scheme-directives/extractScheme.rst thanks @fagossa !
- [x] scheme-directives/scheme.rst thanks @fagossa !
- [x] security-directives/authenticateBasic.rst
- [x] security-directives/authenticateBasicAsync.rst
- [x] security-directives/authenticateBasicPF.rst
- [x] security-directives/authenticateBasicPFAsync.rst
- [x] security-directives/authenticateOAuth2.rst
- [x] security-directives/authenticateOAuth2Async.rst
- [x] security-directives/authenticateOAuth2PF.rst
- [x] security-directives/authenticateOAuth2PFAsync.rst
- [x] security-directives/authenticateOrRejectWithChallenge.rst
- [x] security-directives/authorize.rst
- [x] security-directives/authorizeAsync.rst
- [x] security-directives/extractCredentials.rst
- [x] timeout-directives/withoutRequestTimeout.rst thanks @gosubpl!
- [x] timeout-directives/withRequestTimeout.rst thanks @gosubpl!
- [x] timeout-directives/withRequestTimeoutResponse.rst thanks @gosubpl!
- [x] websocket-directives/handleWebSocketMessages.rst
- [x] websocket-directives/handleWebSocketMessagesForProtocol.rst

**Comment by poojadshende** [comment]
@johanandren Can I start working on one of the directory or do I have to wait till JavaDSL is merged to master?

**Comment by johanandren** [comment]
@poojadshende I'm afraid you will have to wait, we expected to merge the Java DSL during Friday, but things didn't go our way. :( Will update ticket as soon as we have the DSL merged.

**Comment by johanandren** [comment]
Now this ticket is ready for some contributing!

**Comment by Hawstein** [comment]
I make a PR for the CookieDirectives example snippet. If that is OK, I will go on for the BasicDirectives.

**Comment by patriknw** [comment]
Sounds great, thanks

**Comment by fagossa** [comment]
I made a PR for the [scheme directive](https://github.com/akka/akka/pull/20586)

**Comment by ktoso** [comment]
Awesome, thanks @fagossa!
1 down, 124 to go...! :-)

**Comment by fagossa** [comment]
@ktoso The `scheme-directives/extractScheme.rst` directive is also shown in [the example](https://github.com/akka/akka/pull/20586/files); so, I think that makes _2 down, 123 to go_!!

BTW I'm working on some other examples

**Comment by ktoso** [comment]
Hah! You're right, awesome :)
Thanks a lot for your help!

**Comment by felipefzdz** [comment]
I'll be working on the ones contained in *RespondWithDirectivesExamplesSpec*. `respondWithHeader`, `respondWithDefaultHeader`...

**Comment by ktoso** [comment]
Great, thanks @felipefzdz !

**Comment by Hawstein** [comment]
Working on BasicDirectives now.

**Comment by ktoso** [comment]
Awesome, thank you!

**Comment by Hawstein** [comment]
Really glad to contribute to Akka. Thanks for providing such a convenient way to contribute to it.

**Comment by zhxiaogg** [comment]
I would try `header-directives` if you don't mind.

**Comment by ktoso** [comment]
Great, thanks a lot :-)

-- 
Konrad `ktoso` Malawski
Akka @ Lightbend

On 26 May 2016 at 00:55:46, John Zhang (notifications@github.com) wrote:

I would try header-directives if you don't mind.

**Comment by fagossa** [comment]
@ktoso I just made a [PR](https://github.com/akka/akka/pull/20651) on the debugging directives. It covers:

- debugging-directives/logRequest.rst
- debugging-directives/logRequestResult.rst
- debugging-directives/logResult.rst

**Comment by ktoso** [comment]
Three more down by @felipefzdz, thanks a lot!

**Comment by zhxiaogg** [comment]
I made a PR #20673  for all the header directives together. And will work on `marshalling` if you don't mind.

**Comment by ktoso** [comment]
That's great, thank you! :-)

**Comment by Hawstein** [comment]
Since basic-directives is finally merged, going to work on execution-directives :)

**Comment by ktoso** [comment]
Thanks a lot :-)
Sorry for the delay, was a bit overwhelmed with so many people contributing last week – nice problem to have :-)

**Comment by Hawstein** [comment]
@ktoso Ahh, more and more people are involved to contribute to Akka. That's really a good news :)

**Comment by hepin1989** [comment]
@Hawstein @zhxiaogg Yes,especially guys like you from China:).

**Comment by ktoso** [comment]
Very grateful to have you guys join the efforts indeed :-)

**Comment by Hawstein** [comment]
Start to work on `security-directives`.

**Comment by Hawstein** [comment]
Working on ` coding-directives`.

**Comment by Hawstein** [comment]
Working on `route-directives`.

**Comment by ktoso** [comment]
You're on fire today :-) Thanks a lot!

**Comment by Hawstein** [comment]
Working on ` form-field-directives`.

**Comment by Hawstein** [comment]
Working on `file-and-resource-directives`

**Comment by gosubpl** [comment]
Working on `timeout-directives`

**Comment by gosubpl** [comment]
Pull request for `timeout-directives` will be ready shortly, moving on to `file-upload-directives`

**Comment by Hawstein** [comment]
working on `parameter-directives`

**Comment by fagossa** [comment]
i'll work on `misc-directives`

**Comment by ktoso** [comment]
Thanks all so far :-) I keep the "thanks....!" post on the top up to date :-)
We're almost there :-)

**Comment by Hawstein** [comment]
Ah, we're almost there and there are only 5 directives left:

* file-upload-directives
* marshalling-directives
* misc-directives
* range-directives
* websocket-directives

`route-directives` and `security-directives` can be marked as done since they have been merged.

**Comment by patriknw** [comment]
Great work everyone!

**Comment by gosubpl** [comment]
Will also work on `range-directives` as this is second part of Java `Multipart` support story.

**Comment by ktoso** [comment]
Thanks for the multipart javadsl @gosubpl!

**Comment by gosubpl** [comment]
Current status:
- [x] `route-directives` merged
- [x] `security-directives` merged
- [x] `file-upload-directives` merged
- [ ] `range-directives` @gosubpl PR created
- [ ]  `marshalling-directives` @zhxiaogg woking on it
- [ ]  `misc-directives` @fagossa working on it
- [ ]   `websocket-directives` up for grabs

**Comment by gosubpl** [comment]
Is anyone working on `websocket-directives` ? I'd be happy to take this on.

**Comment by Hawstein** [comment]
I am afraid you have to wait for issue #21184 to be resolved since there is no java api for ws testkit now.

**Comment by gosubpl** [comment]
@Hawstein I see you have already covered `websocket-directives` Java test in https://github.com/akka/akka/issues/21238 😃

**Comment by Hawstein** [comment]
@gosubpl yup, I wrote the test for java ws testkit to verify its correctness after implementing it . Hope you don't mind 😄

**Comment by gosubpl** [comment]
@Hawstein no, absolutely not 😃
So the current status would be:
- [ ] marshalling-directives @zhxiaogg woking on it
- [ ] misc-directives @fagossa working on it
- [ ] websocket-directives @Hawstein working on it

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
