### ISSUE TITLE
Document that "remote" sends that just happens to be local are not touching remoting

### ISSUE THREAD

**Issue by dhpiggott** [akka/akka#20463]
I can configure Akka Remoting to listen on a hostname like "fakefakefake", and I'm then able to successfully send messages from one actor to another on the same node via an absolute path that contains the unresolvable hostname -- e.g. "akka.tcp://RemoteSystem@fakefakefake:2552/user/EchoActor".

I've put together a minimal test case to demonstrate this -- it's published here: https://gist.github.com/dhpiggott/a39c5b92a85c12e67b970ee49a1b4185.

The first test will fail because I'm asserting there that the observed behaviour should not happen.

I then stepped through that first test's execution with a breakpoint to trace the cause deeper within Akka Remoting. For ease of communication I've converted the observations I made while doing so into a second test that makes some assertions about Akka's internal state via reflection.

This second test will also fail because I'm again asserting there that some of the observed behaviour should not happen.

I did search for documentation that would confirm what the behaviour should actually be but couldn't find anything.

I see the question as this: is the observed behaviour as things are intended to be? I note on the one hand that the observed behaviour is potentially very useful, but on the other hand, it can also be quite surprising.

I should point out that I originally posted at https://groups.google.com/forum/#!topic/akka-user/DB7NbNq7AZQ. I've proceeded with creating this issue because I think that whatever the answer is, there is an improvement that could be made; if this is the way it's meant to be, the documentation could be improved.

**Comment by drewhk** [comment]
When you say the same node, you actually mean the same actorsystem right?

**Comment by dhpiggott** [comment]
Oops, yes, I do. Sorry for the ambiguity.

**Comment by drewhk** [comment]
For local sends we just avoid remoting altoghether. The `!` on `ActorRef` will just simply enqueue the message directly in the recipient's mailbox. It would be a huge performance penalty to touch name resolution or actual network to detect invalid addresses.

**Comment by dhpiggott** [comment]
OK, thanks. I suspected this might be the case. Do you think the published documentation (and/or source comments) are better left as they are, or might there be room for improvement?

**Comment by drewhk** [comment]
Adding a note section somewhere does not hurt. Are you willing to make a PR about it?

**Comment by dhpiggott** [comment]
It could be a few days and up to a week before I have time, but yes I'd be happy to have a go (I've not contributed before, so will need to read up on that first, plus I might be away this weekend).

**Comment by dhpiggott** [comment]
Sorry for the delay with this. I've not forgotten, I just still haven't had time. I should do within the next two to three weeks though.
