### ISSUE TITLE
headerValueByType extracts key&value not just the value

### ISSUE THREAD

**Issue by anilgursel** [akka/akka#20472]
The corresponding unit-test in akka-http-tests can be used to reproduce: https://github.com/akka/akka/blob/master/akka-http-tests/src/test/scala/akka/http/scaladsl/server/ModeledCustomHeaderSpec.scala#L106.

```scala
    "be able to extract in routing DSL via headerValueByType" in {
      val routes = headerValueByType[ApiTokenHeader]() { token ⇒
        val ApiTokenHeader(t) = token
        complete(s"extracted> $t")
      }

      Get().withHeaders(RawHeader("apiKey", "TheKey")) ~> routes ~> check {
        status should ===(StatusCodes.OK)
        responseAs[String] should ===("extracted> apiKey: TheKey")
      }

      Get().withHeaders(RawHeader("somethingElse", "TheKey")) ~> routes ~> check {
        rejection should ===(MissingHeaderRejection("ApiTokenHeader"))
      }

      Get().withHeaders(ApiTokenHeader("TheKey")) ~> routes ~> check {
        status should ===(StatusCodes.OK)
        responseAs[String] should ===("extracted> apiKey: TheKey")
      }
    }
```

The expectations should be `"extracted> TheKey"` not `"extracted> apiKey: TheKey"`.

The problem is introduced in 2.4.3, probably while addressing https://github.com/akka/akka/issues/20052.

This also causes exceptions during parsing if a custom header has non-String values, e.g., `Int` as it calls the companion with the key included.

**Comment by anilgursel** [comment]
I can send a PR.  Here is the commit in my fork: https://github.com/anilgursel/akka/commit/3c700d5f5dc0d59d40fd9670cf340cfdac8d13a6.

**Comment by ktoso** [comment]
Ouch silly bug, yes you're right and the fix looks good,
Please send in a PR with this - thanks a lot for noticing and the fix!
