### ISSUE TITLE
Framing.delimiter fails only if the delimiter was found

### ISSUE THREAD

**Issue by sibex** [akka/akka#20479]
The `Framing.delimeter` exceeds the `maximumFrameLength` (`maximumLineBytes`) until the next occurrence of the specified delimiter. If the delimiter never arrives then the `DelimiterFramingStage` succeeds. This is a critical bug since the stage is pulling data until an `OutOfMemoryError`.

Example:
```
Framing.delimiter(ByteString("#"), 2, allowTruncation = true)

aaAaaaaaaaaaaaaaa#aa
fails, but much too late. Should have failed at the 'A'.

aaAaaaaaaaaaaaaaaaaa
doesn't fail at all. The stage succeeds. Should have failed at the 'A'.
```

**Comment by johanandren** [comment]
Couldn't find a ticket with someone rewriting this to a `GraphStage` but should probably be done at the same time rather than fixing it in the current `PushPullStage` version.

**Comment by sibex** [comment]
Discovered in akka-stream `2.4.2` via Play sbt-plugin `2.5.0`

**Comment by richard-imaoka** [comment]
I could reproduce the issue. Let me fix the issue and also add it as a new test case, in the above-mentioned pull request.

**Comment by ktoso** [comment]
Solved by @richard-imaoka in https://github.com/akka/akka/issues/20367
