### ISSUE TITLE
HTTP: Document how to be able to support custom request methods

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20508]
It's similar to how to do custom content types,
needs to be documented - and shown together with `extractMethod`.

**Comment by richard-imaoka** [comment]
Correct me if I'm wrong please but we are:

* explaining how [def HttpMethod.custom()](https://github.com/akka/akka/blob/4acc1cca6a27be0ff80f801de3640f91343dce94/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMethod.scala#L42) defines a custom HTTP method
* on the [extractMethod](http://doc.akka.io/docs/akka/2.4.7/scala/http/routing-dsl/directives/method-directives/extractMethod.html#extractmethod) page,
* similar to [Registering Custom Media Types](http://doc.akka.io/docs/akka/2.4.7/scala/http/common/http-model.html#Registering_Custom_Media_Types)  in the doc?

**Comment by ktoso** [comment]
Yeah, that's the things to be done here. Thanks for the research!
Can we expect a PR with this coming soon? :-)

**Comment by richard-imaoka** [comment]
Sure, I'm thinking to submit it in a week or two.

**Comment by ktoso** [comment]
Great, looking forward to it :)

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
