### ISSUE TITLE
Disable binary compatibility check for testkits

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20506]
The MiMa check now covers `akka-http-testkit` and `akka-stream-testkit` because we couldn't get it to pass without those when merging the Java DSL, but we don't promise BC for testkits so we should remove them and make MiMa behave and not check them.

**Comment by Captain1653** [comment]
The issue is really old. It was already disabled in `akka-http-testkit` [here](https://github.com/akka/akka-http/commit/d540af0e70e548421d2857a0173ac34006328314#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R156)

I'll disable in akka-stream-testkit.

Kind regards

**Comment by johanandren** [comment]
We had problems in Akka projections testkit because of implicit binary depenency on testkits, so therefore we actually want the bin comp check nowadays.
