### ISSUE TITLE
Document how CompletionStages execute

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20513]
Realized when writing this: https://gitter.im/akka/akka?at=5734d72deea93e5742d15b15

In 2.4.x we have largely migrated to `CompletionStage` instead of `Future` in the Java APIs. The JDK API docs says this: "The execution properties of default and async modes are specified by CompletionStage implementations, not this interface". 

But the neither `scala-java8-compat` library which we use nor the akka docs mention how these two "modes" are executed. We should add it, or make sure it is in the compat docs and link to that from our docs.

**Comment by relgames** [comment]
Looks like thenApplyAsync is indeed used the first time. But then JDK 8 returns native CompletableFuture so all following thenApply are actually synchronous!

I'm not sure where to find jdk8 source (you can open it form your local JDK I guess), this is the best I could find:
https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/util/concurrent/CompletableFuture.java#L1991
https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/util/concurrent/CompletableFuture.java#L610

**Comment by relgames** [comment]
More info for the future PR https://gitter.im/akka/akka?at=582adfc3e097df7575b349e5
