### ISSUE TITLE
Failed: docs.stream.ActorPublisherDocSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20520]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6185/consoleFull

```
[info] - illustrate usage of ActorPublisher *** FAILED *** (6 seconds, 310 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for A
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:349)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:326)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:734)
[info]   at docs.stream.ActorPublisherDocSpec$$anonfun$1.apply$mcV$sp(ActorPublisherDocSpec.scala:91)
```

**Comment by drewhk** [comment]
Looking at this now

**Comment by drewhk** [comment]
This looks rather suspicious, given the simplicity of the test. There might be a bug here...

**Comment by drewhk** [comment]
Hmm, don't see where the error can be. Did some local repeats (running in 100k batches) both with fuzzing and no fuzzing and found nothing so far. The failure looks worrisome though. The only way I can see this fail if somehow demand is lost (or at least the initial demand)

**Comment by drewhk** [comment]
(well, apart form Jenkins weirdness)

**Comment by drewhk** [comment]
I conclude this is a fluke. While a 3 seconds timeout is not too plausible, the code sequences I poked with have only a few options for racing and I think I have tried them. I close this for now and let's see if this happens again.

**Comment by drewhk** [comment]
Hmm, maybe onto something, reopening.

**Comment by drewhk** [comment]
Nope, I just need to learn the difference between `Thread.start` and `Thread.run` ;)
