### ISSUE TITLE
Document or make it easier to "initial migration of data to akka persistence"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20528]
Discussed such case with some people: existing huge number of data, which basically is like a snapshot of data that from now on should be handled by an actor. Basically imagine someone moving from "row per snapshot, given some id" to "event sourcing, with this as the base data, previous id matches persistent actor id".

This could be either documented how to do, or we could make a Sink that one can put data into and it handles the storing of the data (back-pressured by SaveSnapshotSuccess'es arriving).

**Comment by patriknw** [comment]
I'm not sure I understand the difficulty. Read from DB, ask persistent actor to to save, read next from DB and so on. Since it's a migration job you can probably even block on waiting for the ask to complete.

**Comment by ktoso** [comment]
This ticket is the outcome from a customer interaction over ScalaDays.
Effectively they had many millions of rows to migrate into persistence and wanted to avoid spinning up actors for each of those - asking if journal can be used directly.

`journalFor` is akka private so it can't officially but technically it's doable.

Question in this ticket is if we think it's something to document, or if it was a one shot thing.

**Comment by ktoso** [comment]
I'm OK to close in general, hasn't come back since.
