### ISSUE TITLE
Unidoc fails to compile implicit conversions in scaladsl Rejections

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20533]
Got this from unidoc when trying to release 2.4.5:

```
[error] /Users/johan/Code/Lightbend/Akka/master/akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala:253: value asScala is not a member of akka.http.javadsl.server.Rejection
[error]       transform(Util.immutableSeq(t).map(x ⇒ x.asScala)).map(_.asJava).asJava // TODO "asJavaDeep" and optimise?
[error]          
```

File compiles fine with just scalac from sbt (also clean + compile is fine).

Applied workaround in #20532 that hopefully can be reverted when someone figures this out

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
