### ISSUE TITLE
akka-http-experimental 2.4.5 jar in maven central misses akka.http.javadsl.RoutingJavaMapping class

### ISSUE THREAD

**Issue by relgames** [akka/akka#20556]
https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/javadsl/RoutingJavaMapping.scala is missing in the artifact deployed to Maven Central http://mvnrepository.com/artifact/com.typesafe.akka/akka-http-experimental_2.11/2.4.5

It causes java.lang.NoClassDefFoundError: akka/http/javadsl/RoutingJavaMapping$Implicits$ when trying to use complete(HttpResponse.create())

**Comment by ktoso** [comment]
Thanks for reporting, we'll look into it

**Comment by johanandren** [comment]
Can confirm that the class-file is missing from the artifact on maven central :(

**Comment by johanandren** [comment]
The reason for the omission is the osgi-plugin silently deleting things that are not marked as exports in the OSGi config. 

We will provide a 2.4.6 release with this short-term fixed. Long term I think we should PR the OSGi plugin to fail rather than silently drop files.

**Comment by relgames** [comment]
Thanks, version 2.4.6 works.

**Comment by ktoso** [comment]
Thanks a lot for checking and reporting!
Sorry for the trouble caused, we'll improve our pre-release testing process to avoid such problem to happen ever again.
