### ISSUE TITLE
`recoverWithRetries` documentation does not match implementation

### ISSUE THREAD

**Issue by samueltardieu** [akka/akka#20550]
From the Scaladoc, for parameter `attempts`:

> Passing in a negative number will behave exactly the same as  `recoverWith`.

From the source:

``` scala
private[stream] object RecoverWith {
  val InfiniteRetries = -1
}
```

and

``` scala
   def onFailure(ex: Throwable) =
      if ((maximumRetries == RecoverWith.InfiniteRetries || attempt < maximumRetries) && pf.isDefinedAt(ex)) {

```

I would say that the documentation ought to be fixed rather than the source, given that it won't work with what is currently described anyway.

**Comment by ktoso** [comment]
I agree, would you be able to help out by submitting a PR about this one?

**Comment by samueltardieu** [comment]
Created PR #20555.
