### ISSUE TITLE
[akka-testkit] JUnitRouteTest has dependency on scalatest, and is Serializable

### ISSUE THREAD

**Issue by jypma** [akka/akka#20559]
Since 2.4.5, `JUnitRouteTest` pulls in the trait `JUnitSuiteLike` from scalatest. This has two (unintended?) side-effects:

1. Projects using `JUnitRouteTest` must declare a dependency on scalatest themselves, since it's not a declared compile dependency for akka-testkit (apparently).
2. All Java test classes now are marked `Serializable` (since `Suite` is), triggering compiler warnings by default.

**Comment by johanandren** [comment]
@ktoso ;(

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
