### ISSUE TITLE
Tree flattening should be separate from Fusing

### ISSUE THREAD

**Issue by kkasravi** [akka/akka#20553]
During fusing all GraphStages with AsyncBoundary attribute will create separate groups. These groups are bridged by BoundarySubscriber and BoundaryPublisher. However different materializers may not want to inline the nested computations (GraphStageLogic) done in GraphAssembly.materialize within these groups.

**Comment by drewhk** [comment]
Hm, I am not sure I completely understand this ticket. Can you draw a simple image an attach it so we are surely on the same page? Thank you in advance!

**Comment by patriknw** [comment]
Any update here, @kkasravi ?

**Comment by kkasravi** [comment]
@patriknw 
Hi Patrik - I was waiting on https://github.com/akka/akka/pull/20445 which seems to have stalled due to binary compatibility issues. I don't think there is immediate breakage if we keep downcast as is without moving it to a separate object (@drewhk's suggestion). Since I have many other changes maybe I should submit all changes under this issue (it might be easier to review)?

**Comment by kkasravi** [comment]
@patriknw I've renamed the issue to describe what happens in akka.stream.impl.Fusing.
```
    /*
     * Extract the full topological information from the builder before
     * removing assembly-internal (fused) wirings in the next step.
     */
    val info = struct.toInfo
```
Where this part of Fusing can be isolated. We briefly discussed this in our last meeting.

**Comment by drewhk** [comment]
Ok, so what you need is to take this apart in two parts and only use the code that does the flattening, right?

**Comment by kkasravi** [comment]
yes 

    On Wednesday, June 8, 2016 1:52 AM, drewhk <notifications@github.com> wrote:
 

 Ok, so what you need is to take this apart in two parts and only use the code that does the flattening, right?—
