### ISSUE TITLE
originAddress needed to initiate new handshake after restart of receiving system

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20568]
Right now we fake it by using the address of the `sender: ActorRef` . 
`UniqueAddress(sender.path.address, headerBuilder.uid)` in `Decoder`.

Accidentally (I believe) it is currently also working with the sender address when there is no sender, because we use `deadletters` of the sending system, which is not correct.

There is a test for this scenario: `HandshakeRestartReceiverSpec`

**Comment by drewhk** [comment]
Yep, there are some hacks there.
