### ISSUE TITLE
Potential Bug(s) in the Delay Flow

### ISSUE THREAD

**Issue by MichaelZinsmaier** [akka/akka#20573]
Dear Akka Team,

we might have found two bugs in the Delay Flow.

Setup:
Delay flow with buffer size set to 10, delay set to 1 second and backpressure strategy
Source (1 to 10)

Expected Result:
it takes roughly 1-2 seconds for the flow to complete (all 10 elements are delayed, each by 1 second
but since the buffer is large enough the delays do not sum up)

Observed Result: **Bug 1**
it takes roughly 10 seconds, which would be correct for a buffer size of 1

We suspect this line in the onPush method:
`grabAndPull(strategy != Backpressure || buffer.capacity < size - 1)`
something like `buffer.used < size - 1` could be correct.

**Bug2:** 
if I debug the flow the "size" is always set to 16 not to the configured value of 10 but that seems to be a different problem.

Best Michael

[DelayDemo.txt](https://github.com/akka/akka/files/274221/DelayDemo.txt)

**Comment by drewhk** [comment]
As for Bug2, the internal buffer size is always set to a power of two AFAIK, but that should not be an issue as it should not use more than 10 elements. As for Bug1, that seems to be real. We need to check it.

**Comment by MichaelZinsmaier** [comment]
wow that was fast (-:

-> Bug2 I was suspecting some power of two explanation as well but

with this flow
`val delay = Flow[Int].delay(1.second, DelayOverflowStrategy.backpressure)
      .withAttributes(Attributes.inputBuffer(initial = 1000, max = 1000))`

Delay still sets the `size `to 16 in the constructor because the inheritedAttributes contain
a InputBuffer(1000,1000) and afterwards an InputBuffer(16,16)

val size =
      inheritedAttributes.get[InputBuffer] match {
        case None ⇒ throw new IllegalStateException(s"Couldn't find InputBuffer Attribute for $this")
        case Some(InputBuffer(min, max)) ⇒ max
      }

**Comment by drewhk** [comment]
There are multiple buffers involved here, and inputBuffer is not the same as the one that delay uses internally. The inputBuffer attribute is only used if there is an async boundary, otherwise ignored.

**Comment by drewhk** [comment]
Taking this one.

**Comment by MichaelZinsmaier** [comment]
thanks! looks like this solves the problems we ran into can't wait for 2.4.7 (-:

**Comment by drewhk** [comment]
Fix merged.
