### ISSUE TITLE
send PriorityMessage over control stream

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20577]
We should have configuration for priority messages (heartbeats) similar to the large messages that will make them go over the control stream. Since we have dedicated streams it's better to select this per destination and don't mess with message ordering, instead of selecting it by the message type as in old remoting.

**Comment by johanandren** [comment]
Darn, missed the part with "over control stream", have an implementation using a separate substream for priority messages in place locally now.

**Comment by patriknw** [comment]
Yes, the reason is that a completly new stream is probably to cosly, memory wise.
