### ISSUE TITLE
SupervisionStrategy from ActorMaterializerSettings not inherited

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20582]
I would have expected that if I specify a supervision strategy in the ActorMaterializerSettings that would be among the inheritedAttributes (maybe I have misunderstood the purpose of it).

This gist show it:
https://gist.github.com/johanandren/631c9fdf7933fed7fd2bd6fdd15e11a0

Prints `false` when I would have expected `true`.

**Comment by 2beaucoup** [comment]
Fixed working gist here: https://gist.github.com/2beaucoup/f2c2c5e1ef728451fe1f6bc66b1a598d.

This can be closed.

**Comment by johanandren** [comment]
Ah, of course, I was in way to much hurry to do that kind of "throw-something-together" just to check. Thanks @2beaucoup
