### ISSUE TITLE
Artery configuration

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20587]
Define settings classes and configuration.

Also configuration of Aeron settings.

We should also consider if we can have a few high level settings for choosing between different trade-offs, e.g. low latency vs. cpu usage. Low level settings should be derived from these high level settings.

**Comment by 2m** [comment]
Also add `bind-hostname` to config.

**Comment by patriknw** [comment]
and that is issue https://github.com/akka/akka/issues/20946
