### ISSUE TITLE
All versions of JavaDSL complete* should take marsaller to RequestEntity

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20592]
Reported by Daniel from Ocado here: https://groups.google.com/forum/#!topic/akka-user/CmEdLj62gj4

**Comment by jypma** [comment]
As a workaround, wrap the marshaller using [`entityToOKResponse`](https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/javadsl/server/Marshaller.scala#L81).
