### ISSUE TITLE
BackoffSupervisor does not respect maxNrRetries or withinTimeRange of provided supervisor strategy

### ISSUE THREAD

**Issue by Sushisource** [akka/akka#20597]
Here is an example BackoffSupervisor props:

```scala
    BackoffSupervisor.props(
      Backoff.onFailure(
        p,
        childName = actorName,
        minBackoff = minB,
        maxBackoff = maxB,
        randomFactor = 0.2 // adds 20% "noise" to vary the intervals slightly
      ).withAutoReset(reset).withSupervisorStrategy(
        OneForOneStrategy(maxNrOfRetries = maxTries, withinTimeRange = 10 hours) {
          case e: RetryableException =>
            log.warning("RunNode failed with exception and is being retried: {}", e)
            SupervisorStrategy.Restart
          case e: Any =>
            log.warning("Run node failed with exception and is being escalated: {}", e)
            SupervisorStrategy.Escalate
        }))
  }
```

This will retry indefinitely if the "RetryableException" is thrown every time. This behavior is undocumented and non-obvious, if not an outright bug (which I think it is).

The reason it doesn't work appears to be in BackoffOnRestartSupervisor, where the decider's "retry" is translated into "Stop" no matter what. This means the strategy is never able to actually count restart amounts.

This is happening in 2.4.5 to me

**Comment by patriknw** [comment]
I agree, that is confusing. The ordinary restart counting is implemented in `ChildRestartStats`, perhaps it is possible to reuse that in the `BackoffOnRestartSupervisor`? @Sushisource Would you be interested in contributing this improvement?

**Comment by Sushisource** [comment]
@patriknw I would be happy to contribute. I haven't signed the agreements yet, which I'll need to get approved if I do this from work. Otherwise I'll just do it personally at home. Either way I'll check back in when I begin.

**Comment by patriknw** [comment]
great, thanks

**Comment by patriknw** [comment]
Thanks
