### ISSUE TITLE
Explain RejectionHandler in docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20608]
It should be documented that RejectionHandler can be used to change HttpResponse if a rejection happens.

This relates to Route.seal

**Comment by richard-imaoka** [comment]
Hi, 
Looking at the ["Routes" doc](http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/routes.html#routes) and the ["Rejections" doc](http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/rejections.html#rejections), it seems this is somewhat already documented. Did you mean to add more explanation?

Otherwise, add some more examples in ["handleRejections" doc](http://doc.akka.io/docs/akka/2.4.6/scala/http/routing-dsl/directives/execution-directives/handleRejections.html) to highlight how custom handleRejections make different HttpResponse?

**Comment by ktoso** [comment]
Hm, perhaps it's more about adding an explicit example about this story:

```
Guy Dawson @Mullefa May 19 19:13
This message was deleted
I'm as using akka-http (with circe FTW ) to create a JSON API. In the routing DSL I am using entity(as[T]) to unmarshall the request entity to the given type. If the JSON is invalid, the client gets an error, in my case something like:
Content-Length: 73
Content-Type: text/plain; charset=UTF-8
Date: Thu, 19 May 2016 16:52:01 GMT
Server: akka-http/2.4.4

The request content was malformed:
UUID: El(DownField(userId),true,false)
I would like to make the response consistent with the rest of the API - in my case something like {"ok": false, "error": "INVALID_JSON"}, however, the behaviour seems to be hard coded into the entity() function. So... should I either use lower-level functionality i.e. not entity() or should entity() be made configurable via another implicit argument?

Konrad Malawski @ktoso May 19 19:59
read on RejectionHandler

Guy Dawson @Mullefa May 20 00:37
@ktoso Thanks for the pointer - funny how the actual solution is better than either of my solutions  One thing that's worth noting - I had to wrap the route with Route.seal() to ensure the implicitRejectionHandler was used. This requires an implicit RouteSettings which is found as long as an implicit ActorSystem is in scope. If this is indeed the correct way to do it, it might be worth mentioning it in the documentation (for beginner's such as myself ). I was only able to work it out thanks to a nifty trick on implicits I read in one of your blog posts 
```

:point_up: [May 20, 2016 12:37 AM](https://gitter.im/akka/akka?at=573e4023ff441ca333d32d51)

@Mullefa wanted to contribute it actually if given enough hints, let me know what's unclear and we'll help out :) There's a good point to start here https://github.com/akka/akka/blob/master/CONTRIBUTING.md

**Comment by Mullefa** [comment]
Ok, cool. I should be able to do something by this weekend. If it's useful - great, but I won't mind if it's not included.

**Comment by ktoso** [comment]
Thanks a lot :) I'm sure we'll find a nice place for additional docs of it!

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
