### ISSUE TITLE
Java DSL RouteTest imports the wrong RouteResult type

### ISSUE THREAD

**Issue by jypma** [akka/akka#20610]
When extending `akka.http.javadsl.testkit.RouteTest`, implementers are required to import part of the scala DSL. This is because `RouteTest` imports `akka.http.scaladsl.server.RouteResult`, which appears on the abstract `createTestRouteResult` method.

It should probably import `akka.http.javadsl.server.RouteResult` instead.

**Comment by ktoso** [comment]
Would you be able to help out on this one? Thanks in advance!

**Comment by jypma** [comment]
Done. Hope it compiles :)
