### ISSUE TITLE
Document the Raw URI option in reference docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20622]
I'm not sure if we mention it in the reference documentation, likely not.

Description would pretty much be simply a rewording of:

```
# Enables/disables the addition of a `Raw-Request-URI` header holding the
# original raw request URI as the client has sent it.
akka.http.server.raw-request-uri-header = off

and then you'll get a magic header which contains the raw URI in each request.
```

**Comment by pjazdzewski1990** [comment]
@ktoso I would like to work on this. Can you move it to `in-progress`? Thank you

**Comment by ktoso** [comment]
Awesome, thanks a lot :-)

**Comment by ktoso** [comment]
Best to add somewhere at the end of http://doc.akka.io/docs/akka/2.4.6/scala/http/common/http-model.html as a section about URI in general, and then explain the raw mode there. :)
