### ISSUE TITLE
Artery - Ending up with 100% CPU

### ISSUE THREAD

**Issue by mbknor** [akka/akka#20625]
Version: 2.4-ARTERY-M1

I have an existing app using Akka 2.4.6
It uses multiple different sharded persistent actors (5) and many cluster singletons.
The app also uses "remember-entities" but I do not think it is related,

Since our app is currently under developement, I thought that we should try using ARTERY.
When I did some testing I ended up with the app using 100% CPU.
I tried to figure out what was happening, but was unable to do so.. Nothing special being logged at debug-level, and I was not able to get any usefull data using jvisualvm (the app ended up being too slow to operate when profiler was attached)

But this is the simplest way I was able to reproduce it:
Completely empty database (h2) - So everything is starting from scratch:

* Start node 1 and wait for it to create cluster.
* Start node 2 which joins cluster and wait for the cluster to successfully consist of both nodes.
* Stop node 2 gracefully and wait for it to successfully leave the cluster (gracefully).
* Start node 2 again

Now both nodes ends up with 100% CPU.

Note1: Both "nodes" run on localhost on different ports.

Note2:  The app has not sent a single "user" message internally... It is just waiting to get commands via rest which has not happened.

**Comment by patriknw** [comment]
How many cores on that machine? 

There are threads that are spinning (waiting for messages) both in Artery and Aeron media driver. It will be configurable how much cpu you want to burn vs latency demands. Right now it's not configurable and the defaults might be too aggressive.

**Comment by drewhk** [comment]
Also, CPU reporting was not fully reliable for me since Artery spinning threads spend time in parkNanos and friends, which does not actually burn CPU. The behavior is similar how Akka apps usually burn cycles in the ForkJoinPool `scan` method when there is nothing to execute. We have not tuned this part yet, so might be spinning too much right now.

**Comment by mbknor** [comment]
It was running on Windows with 4 cores.. 

The "100% cpu"-claim was not that scientific... It means that the TaskManager icon shows 100% cpu combined on all cores.

I'm pretty sure the app stopped responding when this happened, but I'll re-test that and post back the result.

**Comment by drewhk** [comment]
Well, there can be a bug, too :)

**Comment by mbknor** [comment]
More info:

When the problem happens (as described above) all 4 cores run at max, and the TaskManager reports both nodes (java processed) aprox use 50% each.

The app and cluster is "operational" during this cpu-problem.. I can via rest talk to both node1 and node2 and they operate correctly together..

If I disconnect node2, the cpu stops again, and it goes back to 100% if i yet another time starts node 2 again.

**Comment by patriknw** [comment]
Can you try to connect a profiler to see what is going on, or take a few thread dumps?

**Comment by mbknor** [comment]
This screenshot of yourkit after the CPU problem has occurred is representative.

When I click the thread-timeline, it almost always shows that it is working in akka.remote.artery.TaskRunner.run()

![artery](https://cloud.githubusercontent.com/assets/203254/15556072/30211ac2-22cc-11e6-83ea-66f2f4d2f738.png)

**Comment by patriknw** [comment]
I have checked with `sample.cluster.simple.SimpleClusterApp` and yourkit. For me it's less than 10% per process. I changed the spinning in the TaskRunner and then the cpu usage goes down. We will tune this to find a reasonable default and it will be configurable.

Thanks for reporting.

**Comment by patriknw** [comment]
It's now configurable with `akka.remote.artery.advanced.idle-cpu-level`, see [reference.conf](https://github.com/akka/akka/blob/artery-dev/akka-remote/src/main/resources/reference.conf#L136) for description.
