### ISSUE TITLE
Simpler config of what ActorRefProvider should be used

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20649]
Neither urgent nor a big issue but, something that popped up in my mind the other day

Does anyone else actually implement actorrefprovider, and if not could we just have ”local”, ”remote”, ”cluster” instead of a fully qualified class name which is much easier to spell correctly and remember?

Could be added backwards compatible by still looking for a class if neither of those three "hardcoded" names match.

**Comment by patriknw** [comment]
excellent suggestion, let's do this in `artery-dev`, which will be merged back to master
