### ISSUE TITLE
encodeResponse directive doesn't work inside RejectionHandler

### ISSUE THREAD

**Issue by nastich** [akka/akka#20648]
_akka-http 2.4.6_

It is impossible to encode failed responses using `RejectionHandler` - although all the required `Accept-*` headers are present in request, and the handler accepts a `route`, and it even processes the directive, the result of `encodeReponseWith` gets lost somehow, and only the result of `complete` is visible.

Code example, as of this [stackoverflow question](http://stackoverflow.com/questions/37489741/how-do-i-encode-gzip-the-response-of-a-rejected-path/37489867#37489867)

    import akka.actor.ActorSystem
    import akka.http.scaladsl.Http
    import akka.http.scaladsl.coding.Gzip
    import akka.http.scaladsl.model._
    import akka.http.scaladsl.server.Directives._
    import akka.stream.ActorMaterializer
    
    import scala.concurrent.Await
    import scala.concurrent.duration.Duration
    
    object Test extends App {
    
      implicit val system = ActorSystem("my-system")
      implicit val materializer = ActorMaterializer()
      implicit val executionContext = system.dispatcher
      implicit val rejectionHandler = RejectionHandler.newBuilder()
        .handleNotFound {
          encodeResponseWith(Gzip) { // this has no effect
            complete((NotFound, "Not here!"))
          }
        }.result()
    
      val route =
        encodeResponseWith(Gzip) {
          path("hello") {
            get {
              complete(HttpEntity(ContentTypes.`text/plain(UTF-8)`, "world"))
            }
          }
        }
    
      val bindingFuture = Http().bindAndHandle(route, "localhost", 8080)
    
      Await.result(bindingFuture, Duration.Inf)
    }

**Comment by gosubpl** [comment]
Actually, this is a problem with encoder not encoding (with gzip, deflate, etc.) any other responses than successes. Obviously, this is hard to spot on the happy path, as regular responses are not usually failures. RFC 7231 does not say anything about particular response types not being eligible for encoding/compression. Nginx chose not to compress 5XX (Server error) but is fine to compress 4XX (Client error), on the grounds that in the case of server error we shouldn't trust that the compression will be done properly. However, some people raised objections to this, as compression is particularly useful in case of 5XX responses that frequently contain large stack traces.
Please note that to get back the current behaviour would be trivial - it is enough not to introduce encodeResponseWith directives for anything that is not success.

**Comment by ktoso** [comment]
That's excellent research, thanks Jan!
IMHO it does make sense to compress if we can, so I like the PR you propose.

If anyone feels otherwise ping here or on PR @2beaucoup @jrudolph @sirthias

**Comment by 2beaucoup** [comment]
https://tools.ietf.org/html/rfc7230#section-3.3.1 lists some scenarios in which replying with a `Transfer-Encoding` is forbidden: 1xx, 204 and 2xx for `CONNECT` request.

Should this be enforced in `DefaultFilter`?

**Comment by gosubpl** [comment]
@2beaucoup well spotted the Transfer-Encoding limitation! Will add it to this PR.

**Comment by 2beaucoup** [comment]
@gosubpl While you're at it may be you can also filter HTTP/1.0 requests.
