### ISSUE TITLE
treat some deserialization errors as transient in remoting

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20641]
EndpointWriter is only treating `NotSerializableException` as transient error (message dropped but association remains). `toBinary` of the serializer may throw any kind of exception. `NotSerializableException` is only used for the lookup of the serializer.

For deserialization I can't see that any exception is caught for deserialize. That might be related to https://github.com/akka/akka/issues/13495 but I don't understand that comment

> This is doable only if the lower layers are "reliable" in that sense that framing synch can be assumed to be preserved if a message is passed to the upper layers.

Perhaps that is for system messages, but as far as I can see we can treat them differently by checking `msg.reliableDeliveryEnabled`.

**Comment by drewhk** [comment]
That comment means that in case of deserialization errors it is safer to drop the association, since if the framing layer is corrupted then every subsequent message will fail deserialization, so it is safer to resynch (by opening a new connection).

**Comment by drewhk** [comment]
I don't think we should tread serialization errors as transient, these are serious errors, why should we tolerate them?

**Comment by drewhk** [comment]
at least I want to understand the use case

**Comment by patriknw** [comment]
For rolling upgrade scenarios we might have to be more tolerant to serialization errors and just drop/log them. 

Dropping the association will have the same end user result, message not delivered, but it's much more costly and can result in all kind of side effects such as unreachability and such.
Why would the association be corrupt if user serialization of some messages fail?

By framing layer, do you mean that TCP in old remoting can become corrupted, or what layer do you mean?

**Comment by patriknw** [comment]
@drewhk convinced me that we should not change this for the old remoting. Artery will be like this, though. Thanks for clarifying

**Comment by patriknw** [comment]
New take on this is to catch only a specific exception from deserialization and not others that could be because of byte corruptions.
