### ISSUE TITLE
Monadic implementation of agents

### ISSUE THREAD

**Issue by DellCliff** [akka/akka#20650]
So imo the implementations of the map, flatMap and foreach function in agents is not very intuitive.
For example:
```
val agent1 = Agent(1)

for {
  value <- agent1
} {
  println(value)
}

println("MIDDLE")

for {
  i <- Range(0, 10)
} {
  agent1.send(i)
}

println("END")
```
In the current implementation this will only ever produce the following output:
```
1
MIDDLE
END
```
When (imo) it should really produce:
```
MIDDLE
END
1
0
1
2
3
4
5
6
7
8
9
```

In the current implementation all that the monadic functions do is take the current value, which is kind of a waste for them I think.

**Comment by drewhk** [comment]
Honestly, we should deprecate agents. We thought they are useful in certain cases, but usage of this module is next to 0, so we should think removing it altogether.

**Comment by patriknw** [comment]
@DellCliff what is actually your suggestion for `value <- agent1`? 
would it return a future?

**Comment by DellCliff** [comment]
@drewhk Agents are pretty much all I'm using in akka since I'm not a huge fan of actors. I'd be fine with it if you want to deprecate agents. I'll just roll my own then. I'm only using akka because it's on maven and it's more convenient to include as a dependency.
@patriknw 
``` for { value <- agent1 } {} ``` is translated into foreach, so it returns Unit. It would just attach a callback function onto the agent, that gets called when ever it changes. So ```value``` would always become the newest value of the agent, whenever it changes.

**Comment by patriknw** [comment]
I see. We can't change, that would break compatibility.

**Comment by patriknw** [comment]
@DellCliff I hope you don't mind that I close this. The best for you might be to copy it and roll your own.
