### ISSUE TITLE
Consider long-term consistency/gc/not-filling-up for Compression Table

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20678]
I think it should be able to remove actors which are proven dead, this complicates ID allocation though.

Need to crunch some numbers how to best tackle this: how long would it take in practice to fill the table?

**Comment by drewhk** [comment]
The idea was to advertise a new table every X period, so I am not sure what 5 years mean here? Also, dead actors might be still needed to be compressed since someone might still send messages to it

**Comment by ktoso** [comment]
> The idea was to advertise a new table every X period

Unspoken assumption I think :-) That's perfectly a fine solution too.
In any case, will need to be implemented, first version assumes there's one table that "stays there".

**Comment by ktoso** [comment]
Changed up title a bit

**Comment by ktoso** [comment]
Replaced with https://github.com/akka/akka/issues/20729
