### ISSUE TITLE
Offer migration path from Spray Caching

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20679]
The question keeps coming up, and it's only one simple file https://github.com/spray/spray/tree/master/spray-caching/src/main/scala/spray/caching

We could provide it as separate mini project, declare it community lead.
Please ping me if you'd like to contribute this port so I can create a repo for it.

**Comment by zhxiaogg** [comment]
@ktoso It's about migrating the spray cache directive to Akka HTTP server DSL, right? If so, I would like to give it a try.

**Comment by ktoso** [comment]
Right, and I think it should live outside of the akka/akka repo, but we can host it under the `akka/` organisation perhaps as `akka/akka-http-caching`. I would like to see it be a community by-demand driven project, I don't think we (core team) will spend time on it, and at the same time we do want to allow the HTTP ecosystem to flourish a bit more.

**Comment by zhxiaogg** [comment]
BTW, why a new project? Is it a planned repo to hold all extra directives?

**Comment by ktoso** [comment]
It does not quite fit nor would it be supported by lightbend, so a separate repo makes most sense. 
Yes, I think we'll want to have a repo to encourage more HTTP community participation, I hope to have a detailed plan for that laid out in a few weeks.

**Comment by zhxiaogg** [comment]
Great, looking forward to the plan.

**Comment by hepin1989** [comment]
https://github.com/ben-manes/caffeine/
We could try to make use of this:)

**Comment by ktoso** [comment]
Looks fun!
Another reason to have it as separate repo in which we can experiment
aggresively and deliver a cool extension that's easy to use with Akka HTTP,
rather than being limited by our mantra of not including dependencies into
Akka "core" (which is very valuable for any foundational project like Akka
is) :-)

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 1 June 2016 at 17:13:23, kerr (notifications@github.com) wrote:

https://github.com/ben-manes/caffeine/
We could try to make use of this:)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/20679#issuecomment-223024741>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAHYkyLZNwClg3PMTUGMKuI3LIYP6z-Zks5qHaGFgaJpZM4IrVz0>
.

**Comment by ben-manes** [comment]
Thanks @hepin1989.

Please do prefer Caffeine. I no longer actively develop `ConcurrentLinkedHashMap` (used by Spray Caching) or Guava's cache. If you use the jdk8-scala adapters you might prefer to use an AsyncLoadingCache for future handling. Also note that `ascendingKeys` would use `cache.policy` to obtain the eviction order, though I'm surprised that's being used (intended for warm restart).

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
