### ISSUE TITLE
Work pulling pattern link broken

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20672]
Gives a 404: 
http://doc.akka.io/docs/akka/2.4.6/scala/howto.html#Work_Pulling_Pattern_to_throttle_and_distribute_work__and_prevent_mailbox_overflow

**Comment by gosubpl** [comment]
Works for me. Has this been fixed?

**Comment by 2beaucoup** [comment]
The trailing slash needs to be removed.

@gosubpl This is about the link in the linked page. ;)

**Comment by gosubpl** [comment]
Ok, will fix it
