### ISSUE TITLE
[http] Dead code in Unmarshaller.scala

### ISSUE THREAD

**Issue by kubukoz** [akka/akka#20687]
```scala
//  def contramap[I](f: I ⇒ A): Unmarshaller[I, B] =
//    Unmarshaller.strict(i ⇒ f(i)).flatMap(ec ⇒ mat ⇒ apply(_)(ec, mat))
```

**Comment by ktoso** [comment]
Good catch :) I wanted to smuggle it in at some point I think but got away without needing it.
Let's remove for now, would you submit a PR please?

Thanks a lot!

**Comment by kubukoz** [comment]
There are also a few lines in the java dsl counterpart, marked with `not exposed for Java yet`, do you think it should go away too?

**Comment by kubukoz** [comment]
(and an unused import as well, it seems)

**Comment by ktoso** [comment]
please link to the lines in question :)

**Comment by kubukoz** [comment]
https://github.com/akka/akka/blob/acb71ac4e53d536fcba0ffe0fb0a48c09a63b108/akka-http/src/main/scala/akka/http/javadsl/server/Unmarshaller.scala#L103
two commented out methods, I didn't mention them before

https://github.com/akka/akka/blob/acb71ac4e53d536fcba0ffe0fb0a48c09a63b108/akka-http/src/main/scala/akka/http/javadsl/server/Unmarshaller.scala#L139
the `not exposed for Java yet` lines

https://github.com/akka/akka/blob/acb71ac4e53d536fcba0ffe0fb0a48c09a63b108/akka-http/src/main/scala/akka/http/javadsl/server/Unmarshaller.scala#L120
unused import

**Comment by ktoso** [comment]
- `asScalaToResponseMarshaller` and friend please remove.
- Import I don't really mind, if compiles without OK to remove.
- please file a ticket for https://github.com/akka/akka/blob/acb71ac4e53d536fcba0ffe0fb0a48c09a63b108/akka-http/src/main/scala/akka/http/javadsl/server/Unmarshaller.scala#L139 eventually we may want to provide those
