### ISSUE TITLE
Provide a shortcut for ignoring (but draining) the entity

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20683]
Newcomers to Akka HTTP very often miss out on draining request and/or response entity streams, and therefore stalling the entire connection. We have tickets for warning or autodraining such entities, but implementing that is not trivial, so for now maybe a more discoverable and easier to use `.ignoreEntity()` method on the request/response or `.ignoreBytes()` on the entity would be a good idea.

**Comment by ktoso** [comment]
This requires some research where to put this operation, but likely simply onto HttpRequest / HttpResponse.

It should be an alias to doing something alike `request.entity.dataBytes.runWith(Sink.ignore)`.

This would be an awesome ticket to handle by one of you if you're interested  @pjazdzewski1990 @note @krzemin @kwyczesany

It perhaps needs more explanation, so let me know if you'd like to pick it up and we can go into more details then

**Comment by krzemin** [comment]
Hey, I'll pick it up. 

What about putting `.ignoreEntity()` to HttpMessage? It seems like the best place for such a combinator.

**Comment by ktoso** [comment]
Yup, great place to put it, and since it's DSL agnostic, we can just put the signature right into `akka.http.javadsl.model.HttpMessage` without the need of alternative method name for Scala.

**Comment by krzemin** [comment]
Well, I see 2 issues regarding definition in java model.

* `runWith` requires implicit Materializer. Is it ok to explicitly pass him `NoMaterializer` or we rather have to require implicit parameter (`def ignoreEntity(implicit m: Materializer)`)?
* Inferred result type of the combinator is `scala.concurrent.Future[Done]` (is this even correct?). What about "polluting" java interfaces with scala futures?

Another question: how to approach testing this function properly? By properly I mean testing not only presence on HttpRequest/HttpResponse, but also that actual entity stream was drained after calling it.

**Comment by ktoso** [comment]
> runWith requires implicit Materializer. Is it ok to explicitly pass him NoMaterializer or we rather have to require implicit parameter (def ignoreEntity(implicit m: Materializer))?

NoMaterializer wouldn't run anything :-) It has to be the actual materializer. Seems we need 2 methods anyway, so in the scaladsl HttpMessage simply take an implicit materializer. I'd also suggest the signature of `def ignoreEntity()(implicit m: Materializer)` to allow typing the `()` to indicate a side effect happening.

> Inferred result type of the combinator is scala.concurrent.Future[Done] (is this even correct?). What about "polluting" java interfaces with scala futures?

Meh, right - the return type we do actually want to expose.
I don't have good names for it yet... let's think about it once you PR. As a placeholder you can use ignoreEntityJava in the java one, and we'll figure out a good name afterwards.

> Another question: how to approach testing this function properly? By properly I mean testing not only presence on HttpRequest/HttpResponse, but also that actual entity stream was drained after calling it.

Something like this would do:

```scala
      val p = Promise[Done]()
      val s = Source.fromIterator[ByteString](() => Vector.tabulate(200)(i => ByteString(s"row-$i")).iterator)
        .alsoTo(Sink.onComplete(t => p.complete(t)))  
      
      val res = HttpResponse(entity = HttpEntity(ContentTypes.`text/csv(UTF-8)`, s))
      res.ignoreDataBytes()

      // with ScalaFutures
      p.future.futureValue should === (Done)
```

We can go smarter to see that the stream is not consumed until we trigger ignore.

PS: ignoreDataBytes sounds like a good name

**Comment by krzemin** [comment]
Actually, we can give them the same name since the signatures are slightly different. I mean:

`def ignoreDataBytes()(implicit m: Materializer): Future[Done]` for scaladsl
`public CompletionStage<Done> ignoreDataBytes(Materializer materializer)` for javadsl

Regarding tests, the code you've posted seems to be working for scala, but similar testing code for java dsl results with ClassCastException.

https://github.com/krzemin/akka/blob/feature/ignore_entity/akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDrainingSpec.scala

```
[info] - should drain entity stream after .ignoreDataBytes(mat) call (javadsl) *** FAILED *** (24 milliseconds)
[info]   java.lang.ClassCastException: scala.concurrent.impl.Promise$DefaultPromise cannot be cast to java.util.concurrent.CompletionStage
[info]   at akka.http.scaladsl.model.HttpRequest.ignoreDataBytes(HttpMessage.scala:153)
[info]   at akka.http.scaladsl.model.EntityDrainingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(EntityDrainingSpec.scala:59)
[info]   at akka.http.scaladsl.model.EntityDrainingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(EntityDrainingSpec.scala:40)
[info]   at akka.http.scaladsl.model.EntityDrainingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(EntityDrainingSpec.scala:40)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

Am I doing something entirely wrong or is it a problem with javadsl Sink.ignore (toCompletionStage conversion)?

**Comment by ktoso** [comment]
These methods:

```scala
def ignoreDataBytes()(implicit m: Materializer): Future[Done] for scaladsl
public CompletionStage<Done> ignoreDataBytes(Materializer materializer) for javadsl
```

 both end up being represented as:

```scala
...ignoreDataBytes(Materializer m) ... 
...ignoreDataBytes(Materializer materializer) ... 
```

parameter lists, so it'll be ambigious which one you wanted to call (shouldn't even compile such declarations). As there is no such thing as multiple parameter lists on the JVM, it is desugared into one list.

**Comment by ktoso** [comment]
Could you please post a PR with your in progress work so I can check it out and have a look?

**Comment by krzemin** [comment]
And that was the source of the problem. After renaming javadsl method test started to pass. Thank you for help.

I'll prepare PR soon.

**Comment by 2beaucoup** [comment]
I wonder if it's possible to automagically do this on `complete` if the entity isn't consumed.

**Comment by johanandren** [comment]
There's #18716 for that, so lets keep this one simple for now.

**Comment by 2beaucoup** [comment]
I see. Thx for the ref.

**Comment by ktoso** [comment]
Yup exactly, that's step 2 :-)

**Comment by 2beaucoup** [comment]
But step 2 might make step 1 obsolete. ;)

**Comment by ktoso** [comment]
No, because one might want to a) drain entity in the client APIs b) use the low level APIs, without routing and still have a quick way to drain entities :-)

**Comment by 2beaucoup** [comment]
Got it.
