### ISSUE TITLE
Make imports in documentation snippets complete

### ISSUE THREAD

**Issue by note** [akka/akka#20699]
The problem appears with e.g. first snippet from http://doc.akka.io/docs/akka/2.4.6/scala/http/introduction.html#Routing_DSL_for_HTTP_servers. It misses some neccessary imports. Test for this pass because some imports are declared on file level in `HttpServerExampleSpec`. I guess it would be nice to avoid all non-tests-related imports on file-level and have them on spec-level instead. It will introduce some code (same imports in few places)  duplication but will result in better output for readers of documentation.

This problem appears in other places of akka-http doc. I am trying to dive-in to akka-http by reading docs and I feel it would be great to do sth useful whilst learning.

Let me know if it makes sense.

**Comment by ktoso** [comment]
Yes, great catch!
The snippets should definitely be "copy paste ready", thanks for spotting it.

**Comment by ktoso** [comment]
Very nice cleanups, thanks :)
