### ISSUE TITLE
akka-http connection pool caches DNS resolution forever (regardless of TTL)

### ISSUE THREAD

**Issue by kevincdeng** [akka/akka#20690]
[PoolInterfaceActor](https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala#L63) uses [Http().outgoingConnectionHttps()](https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala#L220) to create a Flow which it then uses to create a [PoolFlow](https://github.com/akka/akka/blob/bc7cd17beea240ea95e3ebf9a8d15c8212bc0c64/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolFlow.scala) (passed in as the `connectionFlow` argument).

As far as I understand, the PoolFlow will then reuse the `connectionFlow` to create connections when necessary, for as long as the pool is alive.

In [Http._outgoingTlsConnectionLayer](https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala#L238),  a jdk `InetSocketAddress` is instantiated and used to create a [Tcp.OutgoingConnection](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala). Ultimately, a [TcpOutgoingConnection](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-actor/src/main/scala/akka/io/TcpOutgoingConnection.scala) will attempt to open the connection.

The problem is, in [TcpOutgoingConnection's ChannelRegistration handler](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-actor/src/main/scala/akka/io/TcpOutgoingConnection.scala#L51), DNS resolution is not performed if `remoteAddress.isUnresolved` is false, but this will always be false since the constructor of `InetSocketAddress` will resolve the host name, save the IP address and return false for `isUnresolved` thereafter forever (based on my reading of the [code](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/net/InetSocketAddress.java?av=f)).

This means that connections opened by the pool will always use the same IP address that was resolved at the time of the `InetSocketAddress`'s construction. The IP address will never be updated, regardless of what the DNS TTL or DNS cache config is. In case of a change in the DNS mapping, the connection pool will continue to open connections to the old IP address, which will fail if the original host is now dead (as will be the case in a fail-over).

We saw this in practice - the host with the original IP address went down, and the http client continues to try connect to that IP address (and fail), even though the DNS mapping has changed.

Monitoring DNS packets with `tcpdump` also confirms this. When the program first starts, a DNS resolution is performed, and subsequently there are no more DNS resolutions, even though the server indicated a TTL of 60 second, the akka DNS cache is configured to have a 30s TTL, and the JVM has `sun.net.inetaddr.ttl` set to 0.

Is this by design or a bug?

**Comment by ktoso** [comment]
Hi Kevin, thanks for the detailed report.
I see how this could cause trouble, and definitely not something by design as far as I can tell.

If you'd be willing to attempt fixing this in a PR that'd be excellent.

**Comment by ktoso** [comment]
LGTM, this PR only adds a correct deprecation message, thus merging.

**Comment by ktoso** [comment]
Commented in wrong place... Chrome on iPad is very weird about navigating "back", sorry

**Comment by alanmcdadeatsky** [comment]
We have recently upgraded to version 2.5.2. We see that when a dns entry is changed the application does not notice unless the application is shutdown or a connection times out.

We expected the change in DNS to be reflected after the positive-ttl period had passed but this does not happen.

This bug appears to be in version 2.5.2 of akka, is it fixed?

**Comment by patriknw** [comment]
@alanmcdadeatsky What version did you update from? 2.4.x or 2.5.1?
I know there was something done around DNS and TTL in https://github.com/akka/akka/pull/22340 but I don't know if it's related.

This ticket is about Akka HTTP, which is now located in https://github.com/akka/akka-http

Please open a new issue.

**Comment by alanmcdadeatsky** [comment]
@patriknw The issue is not related to update. We had it before update, we updated to the 2.5.2 and we the issue is still there. I'll open a new issue and put more details there.

**Comment by jrudolph** [comment]
Seems to be a duplicate of akka/akka-http#1226
