### ISSUE TITLE
Make recoveries that never complete time out

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20698]
Right now each journal plugin is responsible for making sure the replay times out if the store is really slow. We should make this a built in feature where we have a configureable timeout and if it is not met then the replay will fail and stop the persistent actor.

**Comment by ktoso** [comment]
I think we both think about the same thing, but technically the best setting would likely not be about "time of entire replay" but "idle timeout", I think that's what you meant in the chat, but issue didn't quite mention that, right?

**Comment by patriknw** [comment]
yes, it should be timeout for each message (i.e. receive timeout). It can be many, many, events in a replay so it might not be wrong that the whole replay takes long.

**Comment by johanandren** [comment]
Yeah, sorry if that was vague. The timeout would be between replayed events. So that if replay goes partially through but then the datastore goes on hollidays the persistent actor will be informed about that.
