### ISSUE TITLE
Support value classes for Props(Class[_], ...)

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20735]
From gitter, where reported by @denisrosca, not sure if possible to solve.

Using value classes in Scala and the Class/reflection based props factory does not work, since the value class type is rewritten to the value-type during compilation

Reproducer, compiles:
```Scala
case class Session(value: String) extends AnyVal

class TestActor(session: Session) extends Actor {
    ...
}

// somewhere in a test
system.actorOf(Props(classOf[TestActor], Session("some-string")), "my-test-actor")
```

but throws this exception 
```
java.lang.IllegalArgumentException: 
  no matching constructor found on class com.myexample.TestActor for arguments 
  [class com.myexample.Session]
```

**Comment by ktoso** [comment]
This is very tricky, spent some nights on it in the past, here are more details: https://github.com/akka/akka/issues/16444

It works if one unpacks the value class manually AFAIR.

**Comment by drewhk** [comment]
I am not sure this is something we can or should support though.

**Comment by johanandren** [comment]
I figured as much, but thought it would be good to have that stated in a ticket for future reference.

**Comment by denisrosca** [comment]
If this is not supported maybe it should have a warning in the documentation? One of those red warning boxes stating that value classes as parameters are not fully supported.

**Comment by ktoso** [comment]
A doc warning would be good, and explain the workaround (see the other
ticket). PR would be very welcome.

**Comment by denisrosca** [comment]
I'll submit one later when I'm at home.
> A doc warning would be good, and explain the workaround (see the other
ticket). PR would be very welcome.

**Comment by ktoso** [comment]
Small ping here, would be awesome if you could contrib a small doc update :)

**Comment by denisrosca** [comment]
I had some trouble generating the documentation on my machine to see how it looks. I'll spend more time on it this weekend.
BTW what do you think would be the best way to document this? I was planning on adding a "note" in the "Creating actors with props" section.

**Comment by ktoso** [comment]
> I had some trouble generating the documentation on my machine to see how it looks. I'll spend more time on it this weekend.

If you're having trouble here's a guide: http://doc.akka.io/docs/akka/current/dev/documentation.html
Feel free to ask / ping if stuck :)

> BTW what do you think would be the best way to document this? I was planning on adding a "note" in the "Creating actors with props" section.

Yeah that sounds right 👍

**Comment by patriknw** [comment]
the solution was documentation
