### ISSUE TITLE
FAILED: OutputStreamSourceSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20737]
https://jenkins.akka.io:8498/job/akka-nightly/3392/consoleFull

```
[info] - must throw IOException when writing to the stream after the subscriber has cancelled the reactive stream *** FAILED *** (37 milliseconds)
[info]   Expected exception java.lang.Exception to be thrown, but no exception was thrown. (OutputStreamSourceSpec.scala:161)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:495)
[info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1538)
[info]   at org.scalatest.Assertions$.checkExpectedException(Assertions.scala:1582)
[info]   at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:38)
```

**Comment by drewhk** [comment]
Argh, all kinds of threading issues lurking here...

**Comment by drewhk** [comment]
But irregardless of that, I still cannot figure out what code path could even result in the test failure above.

**Comment by drewhk** [comment]
forgot to put this back

**Comment by drewhk** [comment]
Looking at this again.

**Comment by jrudolph** [comment]
Happened again in https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4282/consoleFull

**Comment by jrudolph** [comment]
And here: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4288/testReport/akka.stream.io/OutputStreamSourceSpec/OutputStreamSource_must_throw_IOException_when_writing_to_the_stream_after_the_subscriber_has_cancelled_the_reactive_stream/

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3802/consoleFull
