### ISSUE TITLE
Compression table should be dropped for new incarnation of remote system

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20747]
As we discussed earlier, we need to drop the (outgoing) compression table if a new incarnation of a system comes in (as the new system would not understand the compressed refs).

So we'll want to do this once a new handshake completes.
Would dropping the table in `Association#completeHandshake` the right place for this @patriknw ?

**Comment by patriknw** [comment]
yes, I think that is the place. You should probably keep the tables in the `AssociationState`, since that represents an incarnation (UID).

**Comment by ktoso** [comment]
Resolved in https://github.com/akka/akka/pull/20546#issuecomment-228003444
