### ISSUE TITLE
Akka Cluster dispatcher docs not up to date with most recent thoughts

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20775]
Documentation http://doc.akka.io/docs/akka/current/scala/cluster-usage.html#Cluster_Dispatcher 
is inconsistent with our recommendation nowadays:

We should incorporate the below notice into the documentation:

> Normally it should not be necessary to configure a separate dispatcher for the Cluster. The default-dispatcher should be sufficient for performing the Cluster tasks, i.e. akka.cluster.use-dispatcher should not be changed. If you have Cluster related problems when using the default-dispatcher that is typically an indication that you are running blocking or CPU intensive actors/tasks on the default-dispatcher. Use dedicated dispatchers for such actors/tasks instead of running them on the default-dispatcher, because that may starve system internal tasks. Related config properties: [akka.cluster.use-dispatcher = akka.cluster.cluster-dispatcher]. Corresponding default values: [akka.cluster.use-dispatcher = ].

**Comment by patriknw** [comment]
+1

**Comment by ktoso** [comment]
Thanks @hhimanshu!
