### ISSUE TITLE
[akka-http] Option for Client to ignore bad response header

### ISSUE THREAD

**Issue by mmacfadden** [akka/akka#20771]
We are currently using the akka-http client to make REST calls to another service that we do not own.  That service is responding with an invalid HTTP Header in the response.  Essentially their response mistakenly adds a '\n' to the response.  However, we do not need the header that is in error.

We are doing something like this:

```Scala
Http().singleRequest(HttpRequest(
  method = HttpMethods.GET,
  uri = myURL)) onComplete {
    case Success(r) => 
      debug(r)
    case Failure(f) => 
      f.printStackTrace()
  }
```
The issue is that the client is currently causing an exception (Failure) to come back from the Future.  The error is:

```
akka.http.scaladsl.model.IllegalResponseException: Illegal character '\n' in header value
	at akka.http.impl.engine.client.OutgoingConnectionBlueprint$PrepareResponse$$anon$1.onPush(OutgoingConnectionBlueprint.scala:186)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:590)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:601)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

However, the invalidity of this header is unimportant to us, and we don't have any ability to change the server, since it is not our software.  Is there a way to tell the client to ignore this issue?

Thanks for the awesome work on akka and akka-http!

**Comment by ktoso** [comment]
We don't have such flag currently, would be interesting to add perhaps – if you'd have a bit of time hacking around in `HttpHeaderParser` would be a good place to start.

Technically `\n` could be a bit more tricky... but maybe not really in these cases - what's the header that it contains a \n btw?

**Comment by mmacfadden** [comment]
I can take a stab at this.  One other small comment.  One of the things that made this so hard to debug was that the exception didn't tell me which header had the problem or what the value was that was invalid.  So essentially, it just said "Some header had some value that had a '\n' in it; and I didn't like it".  It  would be nice if it would say header 'SomeHeader' contained a value with an illegal character '\n': SomeHeader: "some value with \n".  Or something to that effect.

The offending header looks like this:

```
Header: some value \n
Header: another value\r\n
```

This particular header is allowed to have multiple values, and hence appear twice.  However the server accidentally separated the lines with just a \n instead of a \r\n, so it is treated all as one value.  There are actually a couple ways one could handle that particular issue.

For now I would just like to be able to ignore the issue, or maybe set it to be a warning; and also improve the error message to be more specific.

As I said I can see if I can get it to work and generate a PR.

**Comment by ktoso** [comment]
> I can take a stab at this. One other small comment. One of the things that made this so hard to debug was that the exception didn't tell me which header had the problem or what the value was that was invalid. So essentially, it just said "Some header had some value that had a '\n' in it; and I didn't like it". It would be nice if it would say header 'SomeHeader' contained a value with an illegal character '\n': SomeHeader: "some value with \n". Or something to that effect.

Totally agreed, that would make a great step 1 in your PR! Thanks a lot in advance :)

**Comment by ktoso** [comment]
> This particular header is allowed to have multiple values, and hence appear twice. However the server accidentally separated the lines with just a \n instead of a \r\n, so it is treated all as one value. There are actually a couple ways one could handle that particular issue.
> 
> For now I would just like to be able to ignore the issue, or maybe set it to be a warning; and also improve the error message to be more specific.

I see. So we'd have to discard anything until the next valid \r\n, which in your case is what you want anyway... I think this makes sense, but hidden under a flag (off by default).

**Comment by mmacfadden** [comment]
> I see. So we'd have to discard anything until the next valid \r\n, which in your case is what you want anyway... I think this makes sense, but hidden under a flag (off by default).

Yes, it would definitely be a flag.  I actually checked the RFCs (specifically 7230). CRLF (\r\n) is the official separator between headers.  So when a line starts, technically the header value is everything up until the CRLF.  This is what akka-http is doing, so we are in good shape there.

A single '\n' was previously valid when using header folding (also defined in RFC 7230), but has been deprecated.

So I think in theory, we could have an option that gave you three options:

1. invalid-response-header-value = error (the default if not set)
2. invalid-response-header-value = warn
3. invalid-response-header-value = ignore

I think you get the idea.

**Comment by zhan-ge** [comment]
Hi guys, I have got the same error:
``` scala
akka.actor.RepointableActorRef - Error in stage [akka.http.impl.engine.client.OutgoingConnectionBlueprint$PrepareResponse@68b09bf]: Illegal character '\u0001' in header value
akka.http.scaladsl.model.IllegalResponseException: Illegal character '\u0001' in header value
```
I'm using Akka-http connection-level client, the version is `2.4.7`, when I download a image when the error is thrown: `http://www.windowscentral.com/sites/wpcentral.com/files/styles/large_wm_blb/public/field/image/2016/06/minix-8.jpg?itok=WQ0qLsWO`.
How can I fix this? Thanks!

**Comment by ktoso** [comment]
@mmacfadden that plan sounds good, looking forward to a contrib!

**Comment by kwyczesany** [comment]
@mmacfadden are you working on this issue? If not I would try to solve it

**Comment by mmacfadden** [comment]
@kwyczesany I got side tracked on another issue.  I hadn't started yet.  I could probably start in a day or two.  But if you are in a hurry or have the cycled, feel free to take a look.

**Comment by Hawstein** [comment]
@ktoso @mmacfadden @kwyczesany The status of this issue stays unchanged for some time so just made a PR for this issue and hope you don't mind.

**Comment by ktoso** [comment]
Thanks a lot @Hawstein :-)

**Comment by Hawstein** [comment]
@ktoso My pleasure :) Learn a lot from Akka by contributing to it !

**Comment by ktoso** [comment]
Thanks @Hawstein, another nice contrib! :-)
