### ISSUE TITLE
Addressing documentation misleading about "path aliases"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20773]
As seen here: http://stackoverflow.com/questions/37757076/akka-how-to-assign-an-actor-an-alias-path

The person asks how to create an "alias path" for actors.

> Blockquote As in some real file-systems there also are “symbolic links”, i.e. one actor may be reachable using more than one path, where all but one involve some translation which decouples part of the path from the actor’s actual supervision ancestor line; these specialities are described in the sub-sections to follow.

**Comment by agolubev** [comment]
should this ticket be closed?

**Comment by Captain1653** [comment]
The issue was created five years ago. The documentation was added there, PR was merged. Is it worth to close the issue?

Kind regards

**Comment by johanandren** [comment]
Thanks
