### ISSUE TITLE
Akka HTTP WWW-Authenticate always renders 'realm', but RFC 7235 makes it optional

### ISSUE THREAD

**Issue by ianclegg** [akka/akka#20786]
I'm trying to implement SPNEGO authentication [rfc 4559](https://tools.ietf.org/html/rfc4559), but is not possible to use or build on any of the http security infrastructure types such as `authenticateOrRejectWithChallenge` or even use the `www-authenticate` header class since `HttpChallenge` requires and renders the 'realm' parameter. The realm parameter is not understood by  Chrome or Firefox when using the 'Negotiate' scheme; they fail with a 401.

It should be noted that as of  [rfc 7235](https://tools.ietf.org/html/rfc7235#section-2) the 'realm' parameter is optional.
> The "realm" parameter is no longer always required on challenges;
> consequently, the ABNF allows challenges without any auth parameters.
> (Section 2)

Finding a way to omit 'realm' from being rendered by HttpChallenge for some schemes would make it possible to support the Negotiate scheme with the most widely used browsers.

Making the realm constructor argument an option would be nice, though a minor breaking change - an alternative constructor or factory might be preferable? Is there any appetite to address this - I am happy to put together a PR

```
final case class HttpChallenge(scheme: String, realm: String,
                               params: Map[String, String] = Map.empty)
```

**Comment by ktoso** [comment]
Good observation - seems like we could indeed loosen up the type there to make the type optional.
An additional constructor would be one thing to add (remember that we must keep binary compat in that module) we may want to expose the field as Option however we must also keep the current API unchanged... (since bin compat).

It would be awesome if you could prep a PR and we'll figure out exactly how to fit it in, thanks a lot in advance!

**Comment by pjazdzewski1990** [comment]
Hi @ianclegg Do you plan to work on this PR? If no, I could try implementing it and then we could discuss on a PR. Does it make sense to you?

**Comment by ianclegg** [comment]
@pjazdzewski1990 sounds great, I'm working on a commercial project and the spnego authentication story which required it has been pushed back a sprint. I think it should be straight forward

**Comment by ianclegg** [comment]
@pjazdzewski1990 did you make a start?

**Comment by pjazdzewski1990** [comment]
@ianclegg I did start, but got pulled into other duties. 
My general idea was to build a separate subclass of Http challenge (that would work without realm), as a way to avoid compatibility issues.

**Comment by ianclegg** [comment]
@ktoso I had to to wait until this issue had worked its way up our backlog internally, perhaps I can put in another PR on a future 2.5 branch to actually make realm an option?

**Comment by ktoso** [comment]
2.5 won't be allowed to break APIs either though. Thus, we should really fix it in a compatible way currently. I'll review your PR soon.

**Comment by ianclegg** [comment]
cool - I'll await your feedback - cheers

**Comment by ktoso** [comment]
Merged! Great catch and contrib, thanks :)
