### ISSUE TITLE
Akka HTTP RequestBuilding should have better configurable timeouts

### ISSUE THREAD

**Issue by zifeo** [akka/akka#20798]
Defining a timeout for `RequestBuilding` is quite verbose as overloaded signatures do not provide all implicit variables, per se revolved to 1 second. This is especially an issue when having route (integration) tests depending on async computations.

Missing signature : [RequestBuilding.scala#L28](https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/scaladsl/client/RequestBuilding.scala#L28)
Complete signature: [RequestBuilding.scala#L43](https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/scaladsl/client/RequestBuilding.scala#L43)

**Comment by ktoso** [comment]
Thanks for noticing, contributions would be very welcome in this :)

**Comment by zifeo** [comment]
I would be happy to help. Another remark is that the testkit is using sometimes implicit `Timeout` and sometimes a implicit `Duration`. Which one should be preferred when correcting this issue to avoid double declaration?
```scala
implicit val timeoutSec = 5 seconds
implicit val timeout = Timeout(timeoutSec)
```

**Comment by ktoso** [comment]
This should be tackled case by case I believe.
Which api there is taking the duration as argument?

**Comment by zifeo** [comment]
https://github.com/akka/akka/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala#L69 is one example.

**Comment by ktoso** [comment]
Thanks for catching that, yeah in testkit indeed there we should be using Timeout

**Comment by zifeo** [comment]
After having looked more deeply, it seems more conceptual. Currently there are also [RouteTestTimeout](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestTimeout.scala) used. Thus it ends up to:
```scala
implicit val timeout1 = 5 seconds
implicit val timeout2 = Timeout(timeout1)
implicit val timeout2 = RouteTestTimeout(timeout1)
```
As `RequestBuilding` is part of main api we cannot use `RouteTestTimeout` for them, requiring at least two timeout definitions or at least a conversion (implicit or overload). I've seen https://github.com/akka/akka/issues/18550, what is the current status of that and `RouteTestTimeout` usage?

**Comment by ktoso** [comment]
Currently I don't think we will be investing in `RequestBuilding`, 
thus perhaps this issue should rather be closed then.

**Comment by zifeo** [comment]
What should be preferred then? `RouteTestTimeout` over `Timeout`?

**Comment by ktoso** [comment]
Preferred in what sense? In non test code Timeout, the RouteTestTimeout is a rather specific thing only in tests. Not really "one or the other"

**Comment by zifeo** [comment]
What is exactly the purpose of having a distinct timeout for tests as the test api is mixing both?
[Here](https://github.com/akka/akka/compare/master...zifeo:20798-requestBuilding-timeouts?expand=1) is a temporary suggestion for the issue.

**Comment by ktoso** [comment]
`RouteTestTimeout` is specifically this one thing - for the awaitResult of the Route.
I don't see it cause harm as is currently?

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
