### ISSUE TITLE
Can't constuct IOResult in test

### ISSUE THREAD

**Issue by rrodseth** [akka/akka#20795]
@jypma Asked me to log this as a ticket. I think he meant here rather than against the IDE.

I made a stream definition nicely parametrized with function parameters, one of which is A => IOResult. I compiled and ran a test in ScalaIDE that replaced this function with one which constructed a mock IOResult. Then I discoverered that I couldn't compile with Maven because the IOResult constructor is private.
error: constructor IOResult in class IOResult cannot be accessed
``
final case class IOResult private[stream] (count: Long, status: Try[Done]) {
``

ScalaIDE never complained.

**Comment by ktoso** [comment]
Yeah, makes sense since one might want to write tests using it.

**Comment by ktoso** [comment]
Happy to take this in as contribution :)

**Comment by Hawstein** [comment]
@ktoso maybe provide an util to generate an `IOResult` or put it in the stream testkit?

**Comment by ktoso** [comment]
I worked on it a bit here: https://github.com/ktoso/akka/commit/6a1e4c3aa47f69267f97c945f4218686d851f30a
