### ISSUE TITLE
Creation of actor with default value fail when using `system.actorOf(Props[MyActor])`

### ISSUE THREAD

**Issue by Lasering** [akka/akka#20794]
Given the following actor class:
```
class MyActor(val arg: Int = 5) extends Actor {
  ...
}
```
Creating an instance of MyActor using either:
```
system.actorOf(Props[MyActor])
system.actorOf(Props(classOf[MyActor]))
```
Throws an 

> IllegalArgumentException: no matching constructor found on MyActor for arguments []

Which is unexpected since the class MyActor should have an empty constructor.

**Comment by ktoso** [comment]
Thanks for reporting, would be a nice isolated contribution to fix this :-)

**Comment by Lasering** [comment]
This isn't that simple to contribute after all. The problem resides in the fact that `classOf[Test].getDeclaredConstructor()` returns a `java.lang.NoSuchMethodException`.
This happens because scala encodes constructors with default arguments using methods defined in the companion object (creating one if one does not exist already). This means one would have to search for the right method inside the companion object, which of course entails first getting a Class[] to the companion object. The best approach to do this would be using the new reflection API for scala but it is still experimental.

**Comment by patriknw** [comment]
Thanks for investigating. I don't think we want to complicate constructor search anyway. It's rather complicated already. Our recomendation is to use a Props factory method and that can have default values.

**Comment by drewhk** [comment]
Does this deserve the `bug` tag?

**Comment by ktoso** [comment]
I guess not really, you're right

**Comment by patriknw** [comment]
What do you think about the issue? Shall we close it since it seems difficult to solve and we have another recommended approach?

**Comment by ktoso** [comment]
We have a note that we don't support value classes already, so we could extend it into a section about "*edge cases where Props[Clazz] does not work*" and list Value Classes as well as default constructor params in there.

Would you want to contribute that docs update @Lasering ?

**Comment by Lasering** [comment]
Yes.

**Comment by ktoso** [comment]
Great, thanks in advance!

**Comment by Lasering** [comment]
I'm trying to create a value class actor to include in the documentation:

```
val system = ActorSystem("Test")
class ValueActor(val magicNumber: Int) extends AnyVal with Actor {
  def receive = {
    case x: Int => sender() ! (x + magicNumber)
  }
}

val edgeCaseProps3 = system.actorOf(Props(classOf[ValueActor], 5))
```

However I'm getting the following errors:

```
Error:(6, 61) illegal inheritance; superclass AnyVal
 is not a subclass of the superclass Object
 of the mixin trait Actor

Error:(6, 8) value class may not be a member of another class
```

What am I missing?

**Comment by ktoso** [comment]
That's just not supported by Scala :)
The Value Class case we mention is this:

```scala
final class Val(val x: Int) extends AnyVal
class ValueActor(magicNumber: Val) extends Actor { /*...*/ }

Props[ValueActor](Val(42))
```

AFAIR this breaks, because constructor is raw Int in bytecode

**Comment by Lasering** [comment]
Contributing guidelines state 

> there are exceptions to these rules, for example minor changes to comments and **documentation**, fixing a broken build etc.

What workflow should I follow? Pull Request against master?

**Comment by ktoso** [comment]
I'm not sure what you're specifically asking about, the guidelines apply as usual, sometimes for "oneliners in docs" we may merge without validation etc, but in general we follow the rules always.

Yes, please PR towards master
