### ISSUE TITLE
Docs wrongly imply that whole actor system needs restart on quarantine

### ISSUE THREAD

**Issue by jypma** [akka/akka#20808]
In `cluster-usage.rst` for both Scala and Java, it says under "Failure Detector":

_If system messages cannot be delivered to a node it will be quarantined [...]. [...] the actor system must be restarted before it can join the cluster again_

However, in fact only the node itself should be restarted, right?

**Comment by ktoso** [comment]
What is the "node itself"? It is the `ActorSystem`. Docs are correct IMO

**Comment by 2m** [comment]
I agree that it is not explicitly mentioned which actor system needs to be restarted. We can fix this quickly by changing the end of the sentence to *the actor system of the quarantined must be restarted before it can join the cluster again*.

**Comment by 2m** [comment]
Just to be clear, the other part of the cluster can be restarted as well to fix the split, but it is probably not what you would normally want.

**Comment by jypma** [comment]
Ah. Thanks a lot for picking this up! So "the actor system" means just the JVM `ActorSystem` instance on the node that got quarantined. I assumed "the actorsystem" meant the whole cluster.

I guess that might be just me then; I keep talking about "a clustered actor system", hence when I see "actor system should be restarted", I conclude it's the whole cluster...

Is there a better term to designate the whole clustered actor system? Should I just say "cluster"?

**Comment by 2m** [comment]
Yes. That is right. Or more concretely "cluster of actor systems".

**Comment by jypma** [comment]
OK great, thanks. I'll update my terminology :-)

I'll leave it up to you guys whether or not to do the docs change.
