### ISSUE TITLE
Add conversion of spaces("%20") in request parameters to actual spaces

### ISSUE THREAD

**Issue by kelebra** [akka/akka#20802]
Hi, guys,

I've been playing around with aka-http and found out that when I have a route like this:

```
get {
    path("something" / Rest) { info =>
              println(info)
              complete(s"You entered: $info")
    }
}
```

and send get to `/something/long%20line` the `info` variable is actually equal to `long%20line`. Maybe it would be nice to add at least implicit method to replace `%20` to actual spaces like `info.withSpaces` or it would be make this king of behavior default?

**Comment by ktoso** [comment]
We could consider having `RestUrlDecoded` for example. 
I'd rather not add implicits.

If you'd like to contrib this please give it a shot

**Comment by kelebra** [comment]
Was contributing for different issue in that area, so will send pr today:)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

Would be great to see a PR for it over there once we finished the migration today :-)
