### ISSUE TITLE
Setting infinite request-timeout should still allow enabling it via directive

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20817]
If one sets `"akka.http.server.request-timeout = infinite"` it seems we disable the entire infra;
it should be still possible to make the `withRequestTimeout` directive work even if globally disabled it before.

See: https://github.com/akka/akka/pull/20812/files#diff-55d7c6940e889a7e37dd51d9a567014bR43

**Comment by gosubpl** [comment]
Thanks @ktoso for creating this. Already done the research, expect PR soon!

**Comment by jrudolph** [comment]
Interesting, this was an explicit feature as (still) documented in the `reference.conf`. It makes sense for that to be an explicit feature as the whole `RequestTimeoutSupport` is quite expensive, even if timeouts are disabled by setting the value to `infinite`.
