### ISSUE TITLE
investigate scalability aspects

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20810]
free resources for idle associations
perhaps we can keep the association but stop the stream

**Comment by patriknw** [comment]
We can probably also use the `ActorSystemTerminating` message as an early signal to free up resources for an association when the other system is terminated normally. It was introduced in https://github.com/akka/akka/pull/20822

**Comment by ktoso** [comment]
Note: we need to see how much memory is used for connections. How much memory does 100 connections use etc?

**Comment by patriknw** [comment]
We have also noticed issues when running some of the cluster multi-jvm tests with many (8) jvms on same machine.

**Comment by patriknw** [comment]
We have implemented closing of streams when associations are quarantined etc.

We have done some testing around this, e.g. running many jvms on same machine sharing one media driver. Full scale tests would require much more infrastructure, and is out of scope for now.
