### ISSUE TITLE
Can't use SettingsCompanion methods from Java

### ISSUE THREAD

**Issue by jypma** [akka/akka#20814]
```java
ClientConnectionSettings settings = ClientConnectionSettings.create(system)
```
^^^ compile error, since `Object` is returned
```java
ClientConnectionSettings settings = ClientConnectionSettings.create(
    system.settings().config())
```
^^^ compiles fine, since that overload is defined in `ClientConnectionSettings` itself.

We should make extra methods like e.g. `override def create(system: ActorSystem): ClientConnectionSettings = create(system.settings.config)` in `ClientConnectionSettings` and friends.

And consider making the one in `SettingsCompanion` abstract.

**Comment by ktoso** [comment]
Will be fixed in 2.4.8 this friday

**Comment by ktoso** [comment]
Thanks @fsat for the fix!

**Comment by fsat** [comment]
You're welcome @ktoso - it's a pleasure!
