### ISSUE TITLE
TestSubscriber.probe doesn't have an expectNext with a duration

### ISSUE THREAD

**Issue by kbrowder** [akka/akka#20815]
There's no def expectNext(d: FiniteDuration) only expectNext() which means you can't really change the duration of the 0 args expectNext() at runtime, instead the only choice is to change akka.test.single-expect-default globally.  Guess it's an easy fix.

The code is located here:
https://git.io/vo6Ix

**Comment by ktoso** [comment]
Good catch, would be a very nice contribution.

Would you like to submit a PR with the `def expectNext(d: FiniteDuration): I`?

**Comment by kbrowder** [comment]
Should be set, also added a requestNext(d: FiniteDuration), let me know if there's anything else I should do to make it better.

**Comment by patriknw** [comment]
good

(it can be good to know that it's also possible to use `within`)
