### ISSUE TITLE
Loop in flow makes stream never end

### ISSUE THREAD

**Issue by cppexpert** [akka/akka#20833]
I'm using akka 2.4.7.

Not sure if it's bug or me but flow seems to be constructed properly. For some reason I never get stream completion event.

Here is topology of my flow. Originally I used mix of `Broadcast` and `filter` to conditionally split stream but then I saw `Partition` in sources.

![GitHub Logo](http://i.stack.imgur.com/xAByR.jpg)

Thus below is simplified version of my code. In example I assume that item == 1 is what I call "links" in schema.

```
val badFlow = Flow.fromGraph(GraphDSL.create() { implicit builder =>
  import GraphDSL.Implicits._

  val mergeEntrance = builder.add(MergePreferred[Int](1))
  val mergePreExit = builder.add(Merge[Int](2))
  val bcast1 = builder.add(Broadcast[Int](2))
  val bcast2 = builder.add(Broadcast[Int](2))

  mergeEntrance.out ~> bcast1.in

  bcast1.out(0) ~> Flow[Int].filterNot(_ == 1) ~> mergePreExit.in(0)

  bcast2.in <~ Flow[Int].collect {
    case v if v == 1 =>
      -1
  } <~ bcast1.out(1)

  mergeEntrance.preferred <~ Flow[Int].filter(_ == 1) <~ bcast2.out(0)

  bcast2.out(1) ~> Flow[Int].filterNot(_ == 1) ~> mergePreExit.in(1)

  FlowShape.of(mergeEntrance.in(0), mergePreExit.out)
})

val completionFut = Source(List(0, 1, 2, 3))
  .buffer(4, OverflowStrategy.fail)
  .via(badFlow)
  .mapAsync(1) {
    case v => Future.successful(v * 10)
  }
  .toMat(Sink.foreach(v => println(s">>> $v")))(Keep.right).run()

for (result <- completionFut)
  println("Stream is over!")
```

What am I missing ?

**Comment by drewhk** [comment]
This is a fairly classical completion deadlock:
 1. merge Entrance cannot stop until bcast2 stops
 2. bcast2 cannot stop until split flow stops
 3. split flow cannot stop until bcast1 stops
 4. bcast1 cannot stop until merge Entrance stops

**Comment by cppexpert** [comment]
@drewhk I see :( Thank you for clarifying. How should it be changed to work ?

**Comment by drewhk** [comment]
For that to answer, I need to understand what is the use case here (simplify please to as simple as possible so I can understand) and when do you expect it to stop (what is the stopping condition).

**Comment by cppexpert** [comment]
@drewhk I'd like to build a flow that extracts `Article` object from one of three types of info

1. article ID (goes to local DB first and then falls back to remote API)
2. article title (same as above)
3. url to article (fetches HTML and extracts article ID or title from Google Schoolar tags OR another link)

Result of `3` goes to `1` again.

**Comment by drewhk** [comment]
You have not yet formulated your completion condition. When do you expect things to complete?

**Comment by cppexpert** [comment]
Sorry, I forgot to add it. Flow is attached to bounded `Source(List(items))`.

**Comment by drewhk** [comment]
This is still not a completion condition. Please state explicitly when do you expect things to complete.

**Comment by cppexpert** [comment]
@drewhk Not sure what you mean then. I create flow with finite number of items passed to `Stream`. When all items from source list are processed I expect `Future` returned from `run()` method of graph to complete.

**Comment by drewhk** [comment]
>  I create flow with finite number of items passed to Stream. 

This is unfortunately not enough. You create potentially infinite elements that you loop back with that merge node. When do you expect that feedback loop to finish? 

> When all items from source list are processed I expect Future returned from run() method of graph to complete.

Define what do you mean by "all items from the source list are processed" given that there is a loop that can run potentially infinite times for each consumed element from the list.

If you prefer, try to answer the reformulated question: When should the entry point Merge state close its output port?
