### ISSUE TITLE
Why does it no come into method : onReceive(Object message) 

### ISSUE THREAD

**Issue by codepython** [akka/akka#20832]
My client send request to server , it has found the server actor by path ,but the server not print something in function onReceive(Object message) .

**Comment by codepython** [comment]
public void onReceive(Object message) {
      System.out.println("onReceive "+message );
}
}

**Comment by drewhk** [comment]
This is too little information to debug the issue. Please first try to create the minimal program that you think reproduces your issue.

**Comment by ktoso** [comment]
Please provide more details, in general these things "just work", so there must be something else around it that made it not work for you, perhaps wrong path etc.

I'm going to close this ticket, but if you provide more details feel free to do so here and reopen, thanks!
