### ISSUE TITLE
Are we sure about the migration-guide-2.4.x-2.5.x.rst File?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20831]
Somewhat surprisingly I stumbled upon a migration guide to 2.5 already: should it indeed be "to 2.5"?

File: https://github.com/akka/akka/blob/master/akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst

**Comment by drewhk** [comment]
It looks rather weird, it even has some content in it. Yet, we don't have a 2.5, nor have a branch for it AFAIK.

**Comment by patriknw** [comment]
What is surprising? We shall ALWAYS write migration guide along with the "breaking" changes we make. It can for example be a new feature replacing an old that becomes deprecated, as for the entry that is in the migration guide so far.

**Comment by ktoso** [comment]
Hm, but it's not a breaking change and we're continuing to release it on the 2.4 mainline, so the confusing bit for me here was that it's the 2.5 migration guide

**Comment by drewhk** [comment]
> We shall ALWAYS write migration guide along with the "breaking" changes we make. 

I fully get that, but currently `master` is 2.4.x. Is there a 2.5 branch where we already started to accumulate breaking changes?

**Comment by patriknw** [comment]
We accumulate them in this file so that the migration guide can be written together with the changes. We can change the title to "Migration Guide 2.4.x to upcoming 2.5.x" if that is what is confusing.

**Comment by drewhk** [comment]
> We accumulate them in this file so that the migration guide can be written together with the changes. 

But that means that the changes are in `master` already, i.e. they are or will be released as a 2.4.x in the short term. Which is still weird for me, since the migration guide is about 2.4-2.5 while it is already in 2.4 so it should be more about 2.3-2.4. Back then it was slightly different because master was usually the breaking branch and we were releasing from the release branches.

**Comment by patriknw** [comment]
That's why the migration guide is so empty ;-) As I said, it can be a new feature and old is deprecated.
Seriously, don't you have bigger problems to solve? Just remove the file if this is such a big deal.

**Comment by drewhk** [comment]
> Seriously, don't you have bigger problems to solve? 

Yes, I do have.

**Comment by patriknw** [comment]
I have renamed the title
