### ISSUE TITLE
Unmarshal() used with http entities is unsafe if it fails (it should toStrict)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20848]
Unmarshal must force a poper full draining of the http response body otherwise we might end up stalling connections. Reported by some users via https://github.com/akka/akka/issues/20192

I'm not 100% certain we do the right thing currently, so this ticket is about making sure that if an unmarshaller fails we do actually consume the entire incoming stream.

**Comment by ktoso** [comment]
Current workaround is pretty much:

```scala
Unmarshal(x).to[Example].recoverWith {
  case ex =>
    x.entity.dataBytes.runWith(Sink.ignore).flatMap(_ => Future.failed(ex))
}
```

**Comment by ktoso** [comment]
Moved to https://github.com/akka/akka-http/issues/17

**Comment by patriknw** [comment]
nice to see things moving :-)
