### ISSUE TITLE
Calling toStrict on an entity makes it very easy to randomly deadlock the request

### ISSUE THREAD

**Issue by Joe-Edwards** [akka/akka#20850]
A newcomer to akka (and routing) might do something like:

```
extractRequest { request =>
  val strictEntity = Await.result(request.entity.toStrict(5.seconds), 10.seconds)
  // do something with the strict entity here
}
```

This appears to completely deadlock when the request isn't already strict, and eventually just times out the request. (Note that this is much worse than blocking on other things, for which you might get some thread starvation, it just hangs completely)

While the code should clearly be changed to avoid the Await, it's surprisingly difficult to debug what's actually happening if you do something like this. I had some test code which used awaits like this and it took a while to figure out why we were getting random requests hanging.

IMO the outcome should be some subset of:
- Put a warning in the routing docs not to do this
- Create a 'strict' Directive which does this for you properly (See also #20096)
- Fix the code so that this is easily diagnosable/doesn't break

I can't work out exactly what's going on, I guess the thread handling the route must be locking on something the TCP/HTTP layer needs to stream the entity.

[Reproducer here](https://gist.github.com/Joe-Edwards/e447f94e948954499325d4b96122f4ee)

**Comment by ktoso** [comment]
Please read this response which explains what you're doing to the server here: http://stackoverflow.com/questions/34641861/akka-http-blocking-in-a-future-blocks-the-server/34645097#34645097 

I agree we should give more guidance, where should we put those docs you think?
Dealing with futures is as simple as *don't block!", and there's the `onComplete(future)` directive.


> Create a 'strict' Directive which does this for you properly (See also #20096)


I like the idea, can you create a ticket specifically for it? Maybe even contribute? It would be rather simple :-)

**Comment by Joe-Edwards** [comment]
> where should we put those docs you think?

Perhaps a warning box at the bottom of the introduction to http://doc.akka.io/docs/akka/2.4.7/scala/http/routing-dsl/routes.html#routes ?

> can you create a ticket specifically for it?

Done. I'll think about making some pull requests, but I need to sort out the CLA first.

**Comment by ktoso** [comment]
> Perhaps a warning box at the bottom of the introduction to http://doc.akka.io/docs/akka/2.4.7/scala/http/routing-dsl/routes.html#routes ?

the Await block is scary. Yes, a note is likely a good idea, we could link from it to: https://github.com/akka/akka/pull/20469 (which I'll attempt to merge)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
