### ISSUE TITLE
Consider: Compression table version could be Byte instead

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20872]
Tables rarely exist in more versions than two between systems (weird edge cases may have 3 however the old one would be dropped). 

Technically then, we don't really need the table versions to be Ints (currently 2 ints, actor refs, manifests = 8 bytes). As the only goal of the table version is to know "the incoming one is newer", we would actually get away with using only a single Byte for the table ids, and implement roll over logic – so tables would use for-future purposes 2 bytes in total (though would occupy an Int slot probably anyway).

Just a random idea I had, feel free to shoot down or comment otherwise :)

**Comment by patriknw** [comment]
sounds good, does it influence the current header structure, i.e. must it be done before we freeze it?

**Comment by ktoso** [comment]
It's a change where we store this information–it is still in the Tag, but would be incompatible to have one system talk the current way and another the new way. Better to be done right now so the envelope has stable and well known format. Also has 2 bytes for extension of tables left in case we need them.

**Comment by patriknw** [comment]
good point
