### ISSUE TITLE
Improve documentation on deferAsync

### ISSUE THREAD

**Issue by notxcain** [akka/akka#20873]
It's not clear from documentation that `deferAsync` could be used with `persist` and `persistAll`.

**Comment by ktoso** [comment]
Thanks for noticing, would you help us out by providing a simple PR that'd add such an example in http://doc.akka.io/docs/akka/snapshot/scala/persistence.html#Deferring_actions_until_preceding_persist_handlers_have_executed ?

Thanks a lot in advance!

**Comment by notxcain** [comment]
@ktoso I will, if it waits until saturday.

**Comment by ktoso** [comment]
I think it will, thanks! :)

**Comment by richard-imaoka** [comment]
Hi sorry for little being side tracked .. can we assume:

* `deferAsync` can be used with `persist`
* `deferAsync` can be used with `persistAsync` too

however,

* Using `deferAsync`,  with `persist` **AND** `persistAsync` doesn't make sense

is that correct or am I just wrong??

## why ?

The difference between `persist` and `persistAsync` is that, 

* `persist` ["*stash*"es](https://github.com/akka/akka/blob/5ee25d9d40b26a526cc78c0ad58f1258c8bc2da8/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L321) (callback) handler execution
  * then, state becomes from `processingCommands` to [`persistingEvents`](https://github.com/akka/akka/blob/5ee25d9d40b26a526cc78c0ad58f1258c8bc2da8/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L680)
* `persistAsyc` [does not *stash*](https://github.com/akka/akka/blob/5ee25d9d40b26a526cc78c0ad58f1258c8bc2da8/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L371#L374) (callback) handler execution
  * then, state stays in [`persistingCommands`](https://github.com/akka/akka/blob/5ee25d9d40b26a526cc78c0ad58f1258c8bc2da8/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L667#L687) un-changed

So if you mix up `persist` and `persistAsyc` (inside a single `case` of the `receiveCommand` method), `persistAsync` **doesn't fulfill its purpose** - `persist` will make your `PersistentActor` wait before moving back to `processingCommand` state although `persistAsync` is supposed to make `PersistentActor` come back to `processingCommand` asap. 

# what to do?

I found test cases ([[1]](https://github.com/akka/akka/blob/5ee25d9d40b26a526cc78c0ad58f1258c8bc2da8/akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala#L260#L264), [[2]](https://github.com/akka/akka/blob/5ee25d9d40b26a526cc78c0ad58f1258c8bc2da8/akka-persistence/src/test/scala/akka/persistence/PersistentActorSpec.scala#L275#L286)) of the mixed use cases. Can we remove these mixed-up test cases from `PersistentActorSpec`?

For the original purpose of this issue, we can add sample code like these in the doc:

```scala
//Actor code with persist
  var internalState: Int = 0
  override def receiveCommand : Receive = {
    case Evt(i) =>
      persistAsync(Evt(i))( _ => { incrementStateBy(i); } )
      persistAsync(Evt(i))( _ => { incrementStateBy(i); } )
      deferAsync(Evt(i))( _ => { sender() ! internalState } )
  }

//Test code
  "A persistent actor" must {
    "keep the order of handler execution with deferAsync" in {
      val persistentActor = system.actorOf(Props[MyPersistentActor])
      persistentActor ! Evt(1)
      expectMsg(2)
      persistentActor ! Evt(1)
      expectMsg(4)
    }
  }
```

```scala
//Actor code with persistAsync
  override def receiveCommand : Receive = {
    case Evt(i) =>
      persistAsync(Evt(i))( _ => { incrementStateBy(i); } )
      persistAsync(Evt(i))( _ => { incrementStateBy(i); } )
      deferAsync(Evt(i))( _ => { sender() ! internalState } )
  }

//Test code is omitted, as it must be same as above
```
