### ISSUE TITLE
Inconsistent ModeledHeader name in headerValueByType's missing header error

### ISSUE THREAD

**Issue by joprice** [akka/akka#20884]
Header names are not cleaned up in headerValueByType when using `ModeledHeader` as they are in `ModeledCompanion`, so headers that contain dashes are rendered with ‘$minus’ in them when the header is missing: `Request is missing required HTTP header 'X$minusAuth$minusToken’`. Relevant files: 

https://github.com/akka/akka/blob/4acc1cca6a27be0ff80f801de3640f91343dce94/akka-http/src/main/scala/akka/http/scaladsl/server/directives/HeaderDirectives.scala#L94
https://github.com/akka/akka/blob/4acc1cca6a27be0ff80f801de3640f91343dce94/akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala#L24

**Comment by ktoso** [comment]
Thanks @joprice!
If you'd have time to whip up a PR for this that'd be awesome, esp. since you located the relevant code pieces already :)

**Comment by ktoso** [comment]
I took a stab at it while I was around that part of the codebase: https://github.com/akka/akka/issues/20884

**Comment by joprice** [comment]
Thanks. Ive been on vacation in Chicago and I didnt get around to it.

**Comment by ktoso** [comment]
Cool, hope you had a nice time there! Right, it's vacation season after all :)
Thanks for reporting again :)
