### ISSUE TITLE
Create a 'strictEntity' directive

### ISSUE THREAD

**Issue by Joe-Edwards** [akka/akka#20881]
From #20850 

A `Directive1[HttpEntity.Strict]` which calls toStrict on the HTTP Entity safely with a specified timeout (to avoid the deadlock in the other ticket). N.B. should also replace the entity in the request context.

**Comment by ktoso** [comment]
Thanks for the ticket, I agree it's better to provide a directive whcih does this "safely" than assuming people will do the right thing (and get 20 "almost correct" impls ;-))

**Comment by ktoso** [comment]
PRs very welcome to this one, should be rather simple :)

**Comment by Hawstein** [comment]
@Joe-Edwards @ktoso I will work on this if you don't mind. And AFAICS, just adding a `extractStrictRequestEntity`  method to `BasicDirectives` solves this issue.  Correct me if I miss something.

**Comment by Joe-Edwards** [comment]
Go for it. If it's any help, what I'd come up with so far was:

```
  def extractStrictEntity(timeout: FiniteDuration): Directive1[HttpEntity.Strict] = {
    Directive { inner => ctx =>
      ctx.request.entity match {
        case strict: HttpEntity.Strict =>
          inner(Tuple1(strict))(ctx)
        case nonStrict =>
          import ctx.{executionContext, materializer}
          nonStrict.toStrict(timeout).flatMap(strict => inner(Tuple1(strict))(ctx.mapRequest(_.copy(entity = strict))))
      }
    }
  }
```

I'm not sure if the optimization in the strict case is really necessary (perhaps using FastFuture will make it redundant anyway?)

**Comment by ktoso** [comment]
The optimisation is not needed, toStrict does the right thing (returns "this") if the entity is Strict already.

I was more thinking of making a directive that works via mapRequest, i.e. it transforms the entity transparently.


```scala
strictEntity { // toStricts, but we can do various things inside
  extractDataBytes { // works since strict already
    // .. 
  } ~ get { 
    extractRequest { r => r.entity.dataBytes .... } 
  }
}
```

**Comment by ktoso** [comment]
For inspiration look at `mapRequest`

```
val route =
      mapRequest(transformToPostRequest) {
        extractRequest { req =>
          complete(s"The request method was ${req.method.name}")
        }
      }
```

**Comment by Hawstein** [comment]
@ktoso just make a PR for this issue.

**Comment by Joe-Edwards** [comment]
The benefit of extracting the entity is that you get don't need to match/cast it. Usually you want a strict entity so you can get the data explicitly:

```
strictEntity(...) {
  extractRequest { request =
    val entity: HttpEntity = request.entity // don't know it's strict yet :(
    entity match {
      strict: HttpEntity.Strict => strict.data // now we do, but have an non-exhaustive match :(
    }
  }
}
```
vs
```
extractStrictEntity(...) { strict =>
  strict.data // immediately available in a type safe way
}
```

**Comment by ktoso** [comment]
Sure, my proposal composes more nicely though, and is beneficial for other directives as well, instead of just this single case.

I stand by the need of doing a directive like I proposed, and optionally adding a `extractStrictEntity`

**Comment by ktoso** [comment]
Thanks a lot @Hawstein for implementing this feature :-)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
