### ISSUE TITLE
Introduce automatic code formatter for Java code

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20891]
We currently don't have that, only Scala code is formatted by Scalariform.
Java code should be formatted using some sbt plugin as well.

2 spaces. No tabs.

**Comment by Chuwiey** [comment]
Looked into implementing this really quick, but it seems @ktoso that you need to get the https://github.com/typesafehub/sbt-java-formatter build to pass first ;-)

**Comment by ktoso** [comment]
Help on fixing the plugin would be great as well though. I'm trying to focus as much as I can on HTTP/2 this month so we can ship it soon.

Would you have a look? It's likely a very simple mistake hm...

**Comment by raboof** [comment]
@Chuwiey sbt-java-formatter 0.3.0 seems OK, would you be interested in giving this another go?

**Comment by TimMoore** [comment]
Looks like this was fixed in #26220.
