### ISSUE TITLE
Slave node cannot automatically join Cluster after seed node restarted

### ISSUE THREAD

**Issue by huskarz** [akka/akka#20907]
Hi, there

The case is based on [akka-sample-cluster-scala](https://github.com/akka/akka/blob/v2.3.9/akka-samples/akka-sample-cluster-scala/src/main/scala/sample/cluster/simple/SimpleClusterApp.scala)

I changed it to only 2 nodes and started them separately: 
A - seed node @ 2551
B - node @ random port

Node A config

```
akka {
  actor {
    provider = "akka.cluster.ClusterActorRefProvider"
  }
  remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "127.0.0.1"
      port = 0
    }
  }

  cluster {
    seed-nodes = [
      "akka.tcp://ClusterSystem@127.0.0.1:2551"]

    auto-down-unreachable-after = off
  }
}
akka.cluster.metrics.enabled=off
akka.extensions=["akka.cluster.metrics.ClusterMetricsExtension"]
akka.cluster.metrics.native-library-extract-folder=${user.dir}/target/native
```

Node B config

```
akka {
  actor {
    provider = "akka.cluster.ClusterActorRefProvider"
  }
  remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "127.0.0.1"
      port = 0
    }
  }

  cluster {
    seed-nodes = [
      "akka.tcp://ClusterSystem@127.0.0.1:2551"]

    auto-down-unreachable-after = off
  }
}

akka.cluster.metrics.enabled=off
akka.extensions=["akka.cluster.metrics.ClusterMetricsExtension"]
akka.cluster.metrics.native-library-extract-folder=${user.dir}/target/native
```

So I

1. start seed node A

```
Querying members via jmx
akka.tcp://ClusterSystem@127.0.0.1:2551
```

2. start node B with random port

```
Querying members via jmx
akka.tcp://ClusterSystem@127.0.0.1:2551,akka.tcp://ClusterSystem@127.0.0.1:64144
```

3. restart seed node A

```
Querying members via jmx
akka.tcp://ClusterSystem@127.0.0.1:2551
```

Node B cannot join A automatically and keep reporting 

`[INFO] [07/07/2016 19:37:33.050] [ClusterSystem-akka.actor.default-dispatcher-19] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:64144] - Leader can currently not perform its duties, reachability status: [akka.tcp://ClusterSystem@127.0.0.1:64144 -> akka.tcp://ClusterSystem@127.0.0.1:2551: Unreachable [Unreachable] (1)], member status: [akka.tcp://ClusterSystem@127.0.0.1:2551 Up seen=false, akka.tcp://ClusterSystem@127.0.0.1:64144 Up seen=true]`

Could anyone help me on this?

**Comment by patriknw** [comment]
Please use https://groups.google.com/forum/#!forum/akka-user for questions
