### ISSUE TITLE
Recommend `new SecureRandom` over `SecureRandom.getInstanceStrong` for HTTPS server

### ISSUE THREAD

**Issue by raboof** [akka/akka#20908]
In the [HTTPS server example code](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/code/docs/http/scaladsl/server/HttpsServerExampleSpec.scala#L55) `SecureRandom.getInstanceStrong` is used to get a random number generator.

On systems with little entropy, this can lead to HTTPS requests timing out after a minute of inactivity, while `SecureRandom` is blocked waiting for entropy - with no useful error message. I suspect this is what the user posting http://stackoverflow.com/questions/37760656/akka-https-ssl-server-with-ssl-conf/38247272#38247272 ran into.

AFAICS `new SecureRandom()` should be sufficiently secure for this use case.

**Comment by patriknw** [comment]
Perhaps use `-Djava.security.egd=file:/dev/./urandom`?

**Comment by raboof** [comment]
That does not appear to have an effect on my system:
```
Welcome to Scala 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_91).
Type in expressions for evaluation. Or try :help.

scala> import java.security._
import java.security._

scala> java.lang.System.getProperty("java.security.egd")
res0: String = file:/dev/./urandom

scala> val rng = SecureRandom.getInstanceStrong
rng: java.security.SecureRandom = java.security.SecureRandom@27abe2cd

scala> rng.getAlgorithm
res1: String = NativePRNGBlocking

scala> rng.nextInt
res2: Int = 411745773

scala> rng.nextInt
res3: Int = 1468169016

scala> rng.nextInt
```

**Comment by raboof** [comment]
Indeed https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SecureRandomImp suggests `` would use `/dev/random` regardless of the entropy gathering device - looks like that's only used to configure `SHA1PRNG`

**Comment by ktoso** [comment]
Do we have an opinion on which Random to recommend @wsargent?

**Comment by wsargent** [comment]
@ktoso yes -- use SecureRandom.getInstance.  

There's no benefit to using getInstanceStrong because pulling from `/dev/urandom` is the correct thing to do, and getInstanceStrong uses `/dev/random`.  Technically SecureRandom.getInstance uses `/dev/random` for the seeding of the internal SHA1PRNG, but that should only happen once on JVM start up anyway, and if it blocks there then your entropy pool is dry and you've got bigger problems.

https://tersesystems.com/2015/12/17/the-right-way-to-use-securerandom/

**Comment by ktoso** [comment]
Thanks a lot for chiming in, Will! Makes sense, thanks a lot. Your blog as always was and remains to be a gold mine :-)

> You can use -Djava.security.debug="provider,engine=SecureRandom" to see what it's doing under the hood if you're interested.

I'll do so for educational purposes then, thanks!

**Comment by wsargent** [comment]
BTW, in this particular instance even if you didn't use new SecureRandom, it will fill it in if you leave the init parameter as null.

* https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html#SSLContext
* http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/sun/security/ssl/SSLContextImpl.java#74
