### ISSUE TITLE
README.md : Link for reference documentation is wrong

### ISSUE THREAD

**Issue by erik-brangs** [akka/akka#20931]
The link for the Java documention currently points to the Scala documentation. AFAICT it should point to the Java documentation at http://doc.akka.io/docs/akka/current/java.html .

**Comment by ktoso** [comment]
You're right, thanks for catching this. Would you be able to submit a fixup PR?
It's pretty easy (even via github ui) and you'll get credit for it :-)

**Comment by erik-brangs** [comment]
Your contribution guidelines say that contributions require signing the CLA and I didn't find any exception for trivial changes. I really don't want to sign the CLA so I'd prefer it if a project member committed the change.

**Comment by ktoso** [comment]
Hm, nothing scary about the CLA but I can respect that. I'll make the change, thanks for reporting.

**Comment by ktoso** [comment]
Done, thanks for reporting
