### ISSUE TITLE
[akka-http, 2.4.8] "Cannot determine request scheme and target endpoint" while using host header in client request level api

### ISSUE THREAD

**Issue by alias1** [akka/akka#20934]
I'm trying to put together some API abstractions using the request level client API, and running into this error message:

```
Cannot determine request scheme and target endpoint as HttpMethod(GET) request to /self/calendar doesn't have an absolute URI
```

I would have expected this should work since I am setting the host header. Cut down example:

```
# Initial Setup/Abstractions
val http = Http(system)
val hostHeader = headers.Host("api.meetup.com")
val request = HttpRequest().withDefaultHeaders(hostHeader)
val get = request.withMethod(HttpMethods.GET)

# Individual Call
val uri = Uri().withPath(Path("/self/calendar"))
val r = get.withUri(uri)
http.singleRequest(r)
```

Printing the request:

```
HttpRequest(HttpMethod(GET),/self/calendar,List(Host: api.meetup.com),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
```

I have also tried using the following, to no avail:

* `val request = HttpRequest().withHeaders(hostHeader)`
* `val request = HttpRequest().withEffectiveUri(true, hostHeader)`
* `.toRelative` on the `uri` chain
* `get.withUri("/self/calendar")`

Though if I use `val request = get.withUri(uri).withEffectiveUri(true, hostHeader)` then the request works.

Am I missing something? Or is there a better way to build up these abstractions? I would have expected that so long as I had the host/effective URL set somewhere in the chain it should work fine.

**Comment by ktoso** [comment]
Would be an interesting improvement, however in general include the entire URI for now in the uri value.

**Comment by alias1** [comment]
Happy to include it for now as a workaround.
I can't remember if it was in the docs, or my assumption, but I got the impression the host header should work (maybe it wasn't for the request level API though..?)
If this is currently functionality as intended, perhaps a note/something in the doco would be useful?
Get Outlook for iOS




On Mon, Jul 11, 2016 at 7:57 PM +1000, "Konrad Malawski" <notifications@github.com> wrote:












Would be an interesting improvement, however in general include the entire URI for now in the uri value.

**Comment by ktoso** [comment]
I agree, clarifying in docs (perhaps scaladoc on withUri as well), would be very good.
Would you be able to submit a small PR like that?

**Comment by alias1** [comment]
Finally had a chance to look at this. I think the part of the doco that confused me was in the [request-level](http://doc.akka.io/docs/akka/current/scala/http/client-side/request-level.html).

> For a super-pool flow this is not the case. All requests to a super-pool must either have an absolute URI **or a valid Host header**, because otherwise it'd be impossible to find out which target endpoint to direct the request to.

I think the issue I was having comes from the way the code stores the URI, and all of the methods that act on those replace the entire URI.

I hacked together some 'fluent api' style helpers to make my life easier, but not sure how best to write up a note about this for the doco.

**Comment by ktoso** [comment]
Yup, I see. Making the model have a fluent builder is not a goal, but having higher level request building DSLs would be great - we have `RequestBuilding` which could grow such features.

**Comment by ktoso** [comment]
Thanks for reporting back there btw!

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
