### ISSUE TITLE
Actors with lambdas may be easy to miss in docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20947]
As it is in it's own section of the docs and not mentioned in the "Actors" (http://doc.akka.io/docs/akka/current/java/untyped-actors.html) chapter, I think we should put a link to the lambda chapter somewhere pretty visible, in the "Defining Actors" section for example.

**Comment by ktoso** [comment]
Yeah, it's about time we slowly expose the lambda ones more and more

**Comment by Captain1653** [comment]
The issue is really old. The link http://doc.akka.io/docs/akka/current/java/untyped-actors.html is invalid.
 I have read [quick start](https://doc.akka.io/docs/akka/current/typed/actors.html#first-example) (java) and it uses method reference and lambdas.  Is it still needed?

Kind regards

**Comment by johanandren** [comment]
Another dusty archive find @Captain1653, thanks, let's close it!
