### ISSUE TITLE
separateOnSlashes should be documented that it doesn't handle open/end slashes

### ISSUE THREAD

**Issue by JustinPihony** [akka/akka#20950]
https://github.com/akka/akka/blob/29029be31d9198ed45c73efbc2d0212651882a94/akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala#L313

**Comment by JustinPihony** [comment]
This was mentioned by a customer when implementing a pathPrefix from a Uri, where they mentioned that they had to strip the leading and trailing slashes. Upon further review of the code, the leading and trailing slashes are indeed kept. So, it would need researched if a pathPrefix will work correctly with a leading slash instead of just the starting value, and the trailing slash was a problem because they were adding to it afterwards, and expecting no slash at the end (otherwise it would result in a double slash). Maybe it's worth noting that the slashes are kept verbatim to the string and the string should follow akka-http rules, but maybe it's too specific and this can simply be closed?

**Comment by ktoso** [comment]
Thanks a lot for reporting Justin. I'm not yet quite sure what to do here.
It needs some pondering and possibly community feedback. Will try to ponder it a bit soon.

**Comment by ktoso** [comment]
Moved to https://github.com/akka/akka-http/issues/1326
