### ISSUE TITLE
Docs "head over to the latest stable version" in docs seems broken, links to index

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20961]
http://doc.akka.io/docs/akka/snapshot/dev/multi-node-testing.html should link to the same page.
Instead, the `We recommend that you head over to the latest stable version instead.` links to scala.html

**Comment by johanandren** [comment]
Works for me!

**Comment by johanandren** [comment]
The "Click here to go to the same page on the latest stable version of the docs"-link that is. The other one just goes to the TOC of latest stable.

**Comment by ktoso** [comment]
Oh interesting, it could be some of my privacy plugins blocking the HEAD request hm

**Comment by ktoso** [comment]
Nope, I was simply mislead which link I should click – we should make it a bit better then.
Let's make the link going to TOC small, maybe just a version number, and the nice one big (and first link)

**Comment by raboof** [comment]
We don't have such a link anymore at all, see #23869 for bringing it back :)
