### ISSUE TITLE
aroundReceive in ActorSubscriber makes it hard to temporarily become and stash

### ISSUE THREAD

**Issue by A1kmm** [akka/akka#20974]
ActorSubscriber implements aroundReceive, which processes messages prior to calling to receive.

A common way of programming actors is to use become to set a different behaviour temporarily, and stash most messages (for example, when first starting up, I might want to stash all messages until I receive a configuration message, and then unstash and have my actor behave as usual).

However, when using ActorSubscriber, if a message like OnComplete is received while in a special behaviour and stashing messages, the aroundReceive still processes the OnComplete and flags the ActorSubscriber as having completed. When OnComplete is unstashed and re-delivered, it is swallowed by the aroundReceive, as the ActorSubscriber is flagged as having been completed.

One way to enable this kind of behaviour would be for ActorSubscriber (or even Actor) to provide an API for the implementation to signal that messages will be stashed and replayed later, and so aroundReceive shouldn't process the message right now (and another call to signal that messages are no longer being stashed).

**Comment by A1kmm** [comment]
I was able to make this scenario work by extending ActorSubscriber and defining StashAwareActorSubscriber - it needs to be in the akka package because aroundReceive is protected[akka], suggesting that this type of code thing should probably be implemented in akka-streams itself.

```
package akka.stream.actor

trait StashAwareActorSubscriber extends ActorSubscriber {
  private[this] var inStashMode : Boolean = false
  
  override def aroundReceive(receive: Receive, msg: Any): Unit =
    if (inStashMode)
      receive.applyOrElse(msg, unhandled)
    else
      super.aroundReceive(receive, msg)
      
  protected def setStashMode(stashMode: Boolean = true) = inStashMode = stashMode
}
```

**Comment by ktoso** [comment]
Please don't use `ActorSubscriber`, it's too low level for 99% of the cases.
Use http://doc.akka.io/docs/akka/2.4.8/scala/stream/stream-customize.html#graphstage-scala instead, which supports everything you need, in a type-safe nice API.

You can write a Sink using GraphStage, and you can access timers too.

**Comment by patriknw** [comment]
yeah, we don't want to add more to ActorSubscriber. It will eventually be removed. Candidate for deprecation in 2.5.
