### ISSUE TITLE
handleMessagesWithSinkSource seems to chop off last two elements

### ISSUE THREAD

**Issue by kornelc** [akka/akka#20989]
Given the following code fragment, a source set up from a blocking q through an iterator will list all ten integers in the q. But when using a web socket as a sink, the last two elements are not generated. It is consistent, in that no matter how long the list is, it is always the last two that are missing. Is there some sort of caching that needs to be flushed? Is there a better pattern to use to publish to WS as sink?
<pre>
  implicit val system = ActorSystem("reactive-tweets")
  implicit val materializer = ActorMaterializer()
  val config = ConfigFactory.load()
  val numbers = 1 to 10
  val q1 = new LinkedBlockingDeque[Int](numbers.asJava)
  val src1= Source.fromIterator(() => Iterator.continually( q1.take() )).map( i=>TextMessage(i.toString) ) runForeach println
  val routes = {
        path("ws") {
          extractUpgradeToWebSocket{ upgrade =>
            val q2 = new LinkedBlockingDeque[Int](numbers.asJava)
            val src2= Source.fromIterator(() => Iterator.continually( q2.take() )).map( i=>TextMessage(i.toString) )
            complete(upgrade.handleMessagesWithSinkSource(Sink.ignore,src2))
          }
        }
  }
  Http().bindAndHandle(routes, config.getString("http.interface"), config.getInt("http.port"))

</pre>

**Comment by johanandren** [comment]
Something with the LinkedBlockingDeque stuff you are doing, this is based on it but works:

```
  implicit val system = ActorSystem("reactive-tweets")
  implicit val materializer = ActorMaterializer()
  val routes = {
    path("ws") {
      extractUpgradeToWebSocket{ upgrade =>
        val numbers = Source(1 to 10).map(i => TextMessage(i.toString))
        complete(upgrade.handleMessagesWithSinkSource(Sink.ignore, numbers))
      }
    }
  }
  Http().bindAndHandle(routes, "localhost", 9090)

  val (ug, _) = Http().singleWebSocketRequest(WebSocketRequest("ws://localhost:9090/ws"), Flow.fromSinkAndSource[Message, Message](Sink.foreach(println), Source.maybe[Message]))

  println("ENTER to terminate")
  StdIn.readLine()
  system.terminate()
```

Please use the mailing list or gitter channel for questions and leave use the ticket system for bugs and improvement tickets, thanks!
