### ISSUE TITLE
Reliable delivery (at-least once) for Akka Typed

### ISSUE THREAD

**Issue by Lasering** [akka/akka#20984]
One can implement a custom redeliver interval in a PersistentActor with AtLeastOnceDelivery by overriding the method `redeliverInterval`. However we do not know how many attempts have been made to deliver the message. It would be helpful to have a function with the following signature:

`def redeliverInterval(attempt: Int): FiniteDuration`

This would allow implementing a redeliver interval with a backoff.

**Comment by johanandren** [comment]
I'm afraid we are stuck with the current redelivery option because of our binary compatibility rules (adding a new method to a trait that user classes inherits would break AFAIR).

**Comment by Lasering** [comment]
So in the best case scenario it would be for 3.X release?

**Comment by ktoso** [comment]
> So in the best case scenario it would be for 3.X release?

Yeah. Although with Scala 2.12 such change would be binary compatible, but we're still supporting 2.11 so we can't do that too quickly.

It could be possible to add this by an additional trait, extending functionality of PersistentActor.
I.e. `trait AdvancedRedeliveryBlaBlaBadName { this: PersistentActor => `

**Comment by patriknw** [comment]
Good idea, but I don't see how we can change it in a compatible way. Marking it for Akka 3.0

**Comment by Lasering** [comment]
Would this be feasible for Akka Persistence Typed since its marked as May Change?

**Comment by ktoso** [comment]
We don't have an AtLeastOnceDelivery trait in Typed yet, but yes in general -- could be done there

**Comment by Lasering** [comment]
@ktoso bumping the issue as discussed in the meetup

**Comment by ktoso** [comment]
Thanks! I see, this one... Would you want to try implementing it for Akka Typed Persistence? We don't have the AtLeastOnceDelivery trait there yet so the new method could indeed be added there as we introduce that APi

**Comment by Lasering** [comment]
I could try to implement it. But I would take a lot of time, since I would have to get some experience using Akka Typed, and understand how AtLeastOnceDelivery is implemented in Untyped Akka.

**Comment by patriknw** [comment]
Thanks for offering help @Lasering 
I think this might not be the best first contribution, since `AtLeastOnceDelivery` might require some design rethinking while we are anyway defining it's API and behavior.

**Comment by patriknw** [comment]
My thinking is that we should see what we can do to simplify usage of `AtLeastOnceDelivery`, perhaps targeted at one single destination?

It's also very heavy since it's typically require persisting all messages and the confirmations. Perhaps we should also provide some lightweight variant that only keeps messages in memory and will not cover the case when sending node crashes.

**Comment by Lasering** [comment]
Would the initial ideia be considered for Akka 3.0?

**Comment by patriknw** [comment]
You mean 2.6.0? Given how many other things we have in scope for 2.6.0 this one might not make it. However, it's something I find important and want to work on as soon as the must haves are done.

**Comment by taeguk** [comment]
Excuse me, there is no plan for this? I really need this feature for my project.

**Comment by patriknw** [comment]
We absolutely want to have a good solution for this. As it looks like now it will be added after the 2.6.0 release. If you want it earlier you can implement it yourself. I’ll try to put together a sketch of how it can look like.

**Comment by patriknw** [comment]
@taeguk Here is an example that you can use as a starting point: https://gist.github.com/patriknw/514bae62134050f24ca7af95ee977e54

**Comment by Lasering** [comment]
@patriknw I think the initial idea got lost:
```scala
def redeliverInterval(attempt: Int): FiniteDuration
```
Looking at the various settings classes:
https://doc.akka.io/api/akka/2.6/akka/actor/typed/delivery/ConsumerController$$Settings.html#withResendInterval(newResendInterval:scala.concurrent.duration.FiniteDuration):akka.actor.typed.delivery.ConsumerController.Settings
https://doc.akka.io/api/akka/2.6/akka/actor/typed/delivery/ProducerController$$Settings.html#withDurableQueueRequestTimeout(newDurableQueueRequestTimeout:scala.concurrent.duration.FiniteDuration):akka.actor.typed.delivery.ProducerController.Settings

I see no way to implement an exponential backoff.

**Comment by patriknw** [comment]
The whole design is very different from classic AtLeastOnceDelivery. It is not pushing redeliveries from the producer side, that is driven by the consumer side. Therefore no need for exponential backoff. If the Consumer is unavailable the Producer will also be idle.

There is one exception to this. The very first message is retried if it's not acknowledged by the Consumer. I see now that the configuration for that resend interval accidentally got hardcoded to 1 second. I have created issue https://github.com/akka/akka/issues/28747 for configuration of that interval.
