### ISSUE TITLE
Allow java.util.concurrent.Duration to be used directly in the scheduler API

### ISSUE THREAD

**Issue by manuelbernhardt** [akka/akka#20988]
At present the Scheduler API enforces the use of a `FiniteDuration`. When working with a `java.util.concurrent.Duration` this means having to create the duration every time using `scala.concurrent.duration.Duration.create`. This also applies to durations read from the Typesafe Config library (which returns Java `Duration`s).

I am wondering whether it wouldn't be an option to provide variations of `schedule` and `scheduleOnce` that accept a java `Duration`.

**Comment by johanandren** [comment]
Since the `Scheduler` trait is a public API, I'm afraid we cannot add methods to it and keep backwards binary compatibility. It would be nice though.

**Comment by ktoso** [comment]
In the past we've had mixed discussions about that topic.
It's easy to get into API surface explosion with adding overloads like that.

I personally would probably want the overloads, but we should discuss if they pull their weight.

**Comment by ktoso** [comment]
(Keeping the new tag to revisit this issue once Patrik is back)

**Comment by patriknw** [comment]
Duration is used in many many places and I don't see how we can change that. It's better that we consistently use it everywhere. Conversion between the two should not be difficult to do in user land when needed.
