### ISSUE TITLE
Identify breaks ReceiveTimeout

### ISSUE THREAD

**Issue by aalleexxeeii** [akka/akka#20998]
An actor configured with `setReceiveTimeout` does not receive `ReceiveTimeout` message if another party periodically resolves its reference via `Identify` message and no other messages fall into its `receive` method.

Expected behavior: Internal messages intercepted by the framework should not reset idle state of actors.

Use case: We need to monitor the size of the Spray client connection pool. Unfortunately, no facilities for diagnostics are implemented natively and all internals are hidden from external access. Fortunately, every pool slot is handled with an actor with a well-known parent. So, it is possible to know current size of the pool by counting actors matching to some path pattern. As far as I know, the only way to do it is to create an actor selection with wildcards, send `Indetify` to it and count distinct `ActorIdentity` responses. The connection pool shrinks when slot actors have been idle for a configured duration. This is implemented by `ReceiveTimeout` functionality. Thus, if we periodically check for availability of these actors, they are never terminated so the pool can only grow and never shrink. Looks like a Schrödinger's Cat issue.

**Comment by ktoso** [comment]
I agree that `Identify` should not affect the receive timeout.
One should also ponder about the other messages extending `AutoReceivedMessage`, for example `PoisonPill` and `Kill` could as well. Though `Terminated` should not be changed.

Solving this is as simple as making `Identify` extend `NotInfluenceReceiveTimeout`.
Would you want to provide a PR with this change?

**Comment by aalleexxeeii** [comment]
I can make a pull request. Which branch?

**Comment by ktoso** [comment]
`master`, see also https://github.com/akka/akka/blob/master/CONTRIBUTING.md
