### ISSUE TITLE
Credentials are None?

### ISSUE THREAD

**Issue by flyrev** [akka/akka#20991]
I have the following:

```scala
def myUserPassAuthenticator(credentials: Credentials): Future[Option[String]] = {
  log.info(credentials.toString)
  credentials match {
    case p@Credentials.Provided(id) if p.verify("a") =>
      log.info("Login success!")
      Future.successful(Some(id))
    case _ =>
      log.info("Login failure!")
      Future.successful(None)
  }
}

val authRoute = path("login") {
  authenticateOAuth2Async(realm = "secure site", myUserPassAuthenticator) { userName =>
    complete(s"The user is '$userName'")
  }
}
```
when navigating to that endpoint and entering credentials, the log line

```scala
log.info(credentials.toString)
```

just becomes `Missing`. What is wrong here?

( http://stackoverflow.com/questions/38053915/akka-authenticateoauth2async-credentials-missing )

**Comment by johanandren** [comment]
Calling that route with 
```
curl -H "Authorization: Bearer a" http://localhost:9095/login
```

gives the expected response: `The user is 'a'`


Please use the mailing list or the gitter channel for question and only use the issue tracker for bugs and improvement tickets, thanks!
