### ISSUE TITLE
Logging directive sample is incorrect

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21009]
The docs (http://doc.akka.io/docs/akka/2.4.8/scala/http/routing-dsl/directives/debugging-directives/logRequestResult.html#signature) use a function `Any => Option[LogEntry]` and then match on `HttpResponse` but what the directive actually provides is the `RouteResult`.

**Comment by soren-schmidt** [comment]
Don't forget to verify 
http://doc.akka.io/docs/akka/2.4.8/scala/http/routing-dsl/directives/debugging-directives/logResult.html
as well.

**Comment by johanandren** [comment]
Thanks, had missed those in the PR!

**Comment by johanandren** [comment]
Heh. I take that back, it's from the same example sources.

**Comment by johanandren** [comment]
This was merged, not sure why it was reopened.

**Comment by ktoso** [comment]
Hm, weird. Perhaps my misclick, though log shows it was opened then closed by me. 
Sorry for confusion caused :)
