### ISSUE TITLE
Provide "tail -f" like FileIO Source

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21004]
It would be fun to have a Source that behaves like "tail -f" so one can monitor a file for changes.

**Comment by Hawstein** [comment]
Seems interesting, would like to give it a try. Any clue now?

**Comment by hepin1989** [comment]
make use of `WatchService`?

**Comment by Joe-Edwards** [comment]
See also: https://github.com/apache/commons-io/blob/trunk/src/main/java/org/apache/commons/io/input/Tailer.java

Perhaps that's been superseded by the WatchService etc.?

**Comment by ktoso** [comment]
Yeah it basically has to not complete the Source once it has reached its "end", but then go into a mode that awaits the WatchService to notify it that the file has changed.

**Comment by drewhk** [comment]
Great idea! probably better for streams-contrib though.

**Comment by patriknw** [comment]
Sound great for contrib. Another useful variant is one that picks up new files in a directory.

**Comment by ktoso** [comment]
Yeah, let's move it over to contrib
