### ISSUE TITLE
Provide a doc example of usage of marshalling/unmarshalling directives

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21001]
See this SO question:
http://stackoverflow.com/questions/38445376/akka-http-using-java-get-string-from-requestentity

**Comment by ktoso** [comment]
Indeed, would be great to show more examples, esp. in Java as it's a bit unfamiliar to those

**Comment by owainlewis** [comment]
+1 this would be very helpful.

**Comment by richard-imaoka** [comment]
* This should be moved to [akka-http](https://github.com/akka/akka-http)?
* And closed as [akka-http #218](https://github.com/akka/akka-http/issues/218) covers this?
* For this specific "entity" directive, [I raised a PR](https://github.com/akka/akka-http/pull/335)

**Comment by ktoso** [comment]
You're right, thanks a lot!

**Comment by youk** [comment]
Unfortunately, the documentation still does not address that SO question. OP explicitly mentioned he has no need to use Routing/Directives and doesn't want to. So the question remains: how to utilize `Unmarshaller.entityToString()` considering that it requires `ExecutionContext` and `Materializer`.

**Comment by ktoso** [comment]
just provide an execution context `import system.dispatcher` and materializer - just create one.

Please don't revive threads in the wrong place, as was explained above this ticket is in the wrong repo. Feel free to open a ticket in the right place (explained above - in akka-http repo), and provide a PR if you want.
