### ISSUE TITLE
[akka-http] route not recognition httpmethod when set 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by huanwuji** [akka/akka#21012]
```scala
  val route =
    pathPrefix("api") {
      (path("atomic") & post & entity(as[AtomicKeyValue])) {
        atomicKY ⇒
          storeGateway.atomicPut(atomicKY.key, atomicKY.expect, atomicKY.update)
          complete(StatusCodes.OK)
      } ~ (path("range") & get & parameters("key", "start".as[Int].?, "limit".as[Int].?)) {
        (key, start, limit) ⇒ {
          complete(storeGateway.range(key, start.getOrElse(0), limit.getOrElse(Int.MaxValue)))
        }
      } ~ (path("id") & get) {
        complete(Map("id" → storeGateway.id()))
      } ~ (get & parameter("key")) {
        key ⇒ complete(storeGateway.get(key))
      } ~ (post & entity(as[KeyValue])) {
        keyValue ⇒
          storeGateway.put(keyValue)
          complete(StatusCodes.OK)
      } ~ (delete & parameter("key")) {
        key ⇒ {
          storeGateway.delete(key)
          complete(StatusCodes.OK)
        }
      }
    } ~ path("ping") {
      complete("pong")
    }

```
This is chrome request info

Request URL:http://172.18.21.98:8081/api
Request Method:OPTIONS
Status Code:405 Method Not Allowed
Remote Address:172.18.21.98:8081
Response Headers
view source
Access-Control-Allow-Origin:*
Allow:GET, POST, DELETE
Content-Length:61
Content-Type:text/plain; charset=UTF-8
Date:Fri, 22 Jul 2016 08:18:13 GMT
Server:akka-http/2.4.8
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:172.18.21.98:8081
Origin:http://172.18.21.98:3001
Pragma:no-cache
Referer:http://172.18.21.98:3001/ns/add
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by 2beaucoup** [comment]
This is a CORS preflight request that Chrome sends but akka doesn't handle automatically.

See e.g. https://github.com/lomigmegard/akka-http-cors how to add support for this.

**Comment by johanandren** [comment]
I'm going to close this as it is more of a question. 

Please us the mailing list (https://groups.google.com/forum/#!forum/akka-user) or the gitter channel (https://gitter.im/akka/akka) for questions and keep the issue tracker for bugs and improvement requests, thanks!
