### ISSUE TITLE
Publish de Akka Stream TestKit utilities

### ISSUE THREAD

**Issue by cchantep** [akka/akka#21028]
... such as [Utils.assertAllStagesStopped](https://gitter.im/akka/akka?at=5794e0a067c448730ef8190a).

_[See discussion](https://gitter.im/akka/akka?at=5794e4bd959ee82b3e4fa67c)_

**Comment by cchantep** [comment]
cc @ktoso

**Comment by ktoso** [comment]
It's worth considering since it might be useful in akka-streams-contrib.

**Comment by patriknw** [comment]
sounds good

**Comment by cchantep** [comment]
Anything new there with the 2.4.9?

**Comment by ktoso** [comment]
If there was, there would be action in the ticket.
You're very welcome to help out moving the utility to contrib :)

**Comment by cchantep** [comment]
Unclear to me... by "be useful in akka-streams-contrib" you means moving the utility code?

**Comment by cchantep** [comment]
See https://github.com/akka/akka-stream-contrib/pull/51

**Comment by johanandren** [comment]
Just to clarify: These are already published in Akka 2.5, so this would be a backport of them being public.

**Comment by johanandren** [comment]
Ah, I was incorrect about this `assertAllStagesStopped` is still in the test sources of the TestKit, not a part of the actual TestKit.
