### ISSUE TITLE
An "orElse" stage

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21024]
Idea came from discussion with @matheuslima on gitter the other day. 

A stage that given an alternative source will only consume that source if the "main" source completes without ever emitting any elements.

Idea of usage:
```
sourceThatMayCompleteEmpty.orElse(fallbackSource).andSoOn...
```

Not 100% sure that it belongs in akka-streams, but it is kind of a core combinator thingie, so let's see what the rest of the team thinks.

**Comment by samueltardieu** [comment]
I think this is called `defaultIfEmpty(value)` and `switchIfEmpty(source)` in RxJava.

**Comment by ktoso** [comment]
Scala has an idiom for it already, `orElse` so the name is good I think.
