### ISSUE TITLE
add redirect to RequestContext

### ISSUE THREAD

**Issue by MasseGuillaume** [akka/akka#21029]
this is my use case:

```scala
pathEnd {
  parameter('code) { code =>
    onSuccess(github.info(code)) { userState =>
      val uuid = java.util.UUID.randomUUID
      users += uuid -> userState
      setSession(refreshable, usingCookies, uuid) {
        setNewCsrfToken(checkHeader) { ctx =>
          ctx.complete(
            HttpResponse(
              status = TemporaryRedirect,
              headers = headers.Location(Uri("/")) :: Nil,
              entity = HttpEntity.Empty
            )
          )
        }
      }
    }
  }
}
```

**Comment by ktoso** [comment]
I see, makes sense. 
I wouldn't mind merging if someone could contribute this change, it's relatively simple:

- move logic that is here https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/RouteDirectives.scala#L38 into context
- make the directive call that

**Comment by bambuchaAdm** [comment]
Should it be implemented also in `javadsl` ?

**Comment by ktoso** [comment]
Yeah, everything has to 😉
