### ISSUE TITLE
Circuit Breaker exponential backoff

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21036]
It should be simple to make a CircuitBreaker that applies exponential backoff.

> I wanted to go into open to half-open to open to half-open ... on a configurable curve (1s, 2s, 4s, 8s, etc) but it wasn't obvious to implement (this was years ago and I haven't tried since, so YMMV)

**Comment by Hawstein** [comment]
I will work on this issue tomorrow, must go to sleep now.

**Comment by ktoso** [comment]
Awesome :-) Thanks!

**Comment by ktoso** [comment]
You can refer to BackoffSupervisor to get some inspiration about implementing backoff

**Comment by Hawstein** [comment]
Super busy days. Finally get some spare time to fix this issue :)
