### ISSUE TITLE
FlowOps operations are missing from akka.io akka-streams documentation

### ISSUE THREAD

**Issue by dnvriend** [akka/akka#21049]
The akka.io akka-streams documentation, http://doc.akka.io/docs/akka/2.4/scala/stream/stages-overview.html is missing the FlowOps operations.

**Comment by ktoso** [comment]
Well "some of the" :-)

**Comment by ktoso** [comment]
Thanks for reporting!

Would you be able to help out by writing the zip one maybe?
We should build a test that checks that all ops are documented there

**Comment by dnvriend** [comment]
Sure, I will give it a try

**Comment by ktoso** [comment]
Thanks!

**Comment by agolubev** [comment]
Do we need to put async, via, to , transform, name? Jus to doublecheck

**Comment by drewhk** [comment]
Maybe not async and name. Transform is deprecated aren't it?

On Thu, Aug 18, 2016 at 5:00 AM, Alexander Golubev <notifications@github.com

**Comment by agolubev** [comment]
Yeah, `via` should be used instead of `transform`
