### ISSUE TITLE
add extractSystem directive to routing DSL

### ISSUE THREAD

**Issue by gaydenko** [akka/akka#21058]
Please, add extractSystem directive to routing DSL - sometimes it can be needed for external API.

**Comment by ktoso** [comment]
I wanted to ask about your use case. Why do you need the actor system?
Is if for creating worker actors? If so then perhaps support for creating actors would be more interesting than exposing the raw system.

**Comment by gaydenko** [comment]
Inside `complete` I need to use external API demanding implicit actor system (as well as ec and mat).

**Comment by ktoso** [comment]
Yeah I guess this can happen with extensions etc.
Any takers on implementing this?

**Comment by Hawstein** [comment]
Will work on this issue.
