### ISSUE TITLE
Provide RecordIO support for streaming APIs and client

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21050]
It basically is `([bytes length][json or proto])*`, we could trivially support it along existing json streaming modes on the server. For the client would be nice to provide a pattern or method to consume such APIs in any case.

http://mesos.apache.org/documentation/latest/scheduler-http-api/#recordio-response-format

**Comment by patriknw** [comment]
Continued here https://github.com/akka/alpakka/issues/145
