### ISSUE TITLE
Http().webSocketClientFlow materialized value doesn't complete when TCP cannot connect

### ISSUE THREAD

**Issue by angiolep** [akka/akka#21051]
Please, try the following client application with akka-stream-2.4.8

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl._
import akka.http.scaladsl.model.ws._
import akka.stream.ActorMaterializer
import akka.stream.scaladsl._
import scala.concurrent.Future

object Issue extends App {
  
  implicit val system = ActorSystem()
  implicit val mat = ActorMaterializer()
  implicit val ec = system.dispatcher
  
  val outgoing = 
    Source.single(TextMessage("hello world!"))

  val webSocketFlow: Flow[Message, Message, Future[WebSocketUpgradeResponse]] =
    Http().webSocketClientFlow(WebSocketRequest("ws://127.0.0.1:9999/no/server/here"))

  val incoming =
    Sink.foreach[Message] {
      case message: TextMessage.Strict =>
        println(message.text)
    }

  // upgradeResponse is a Future[WebSocketUpgradeResponse]
  // and it's expected to complete with success or failure
  val (upgradeResponse, closed) =
    outgoing
      .viaMat(webSocketFlow)(Keep.right)
      .toMat(incoming)(Keep.both)
      .run()
  
  // BUT it doesn't complete with failure as it should
  upgradeResponse.onFailure {
    case t: Throwable => 
      println(s"Connection failed : ${t.getMessage}")
  }
}
```

As I can read in the official [Client-Side WebSocket Support](http://doc.akka.io/docs/akka/2.4.8/scala/http/client-side/websocket-support.html#websocketclientflow) documentation, I'm just holding the ``upgradeResponse`` materialized value of the ``websocketFlow`` and I'm expecting it to behave like a proper ``Future[WebSocketUpgradeResponse]``

That would mean I shall be able to pass an ``onFailure`` partial function that would be invoked when TCP cannot connect ... **but that never happens instead!** Even though I attempt to connect to ``ws://127.0.0.1:9999/no/server/here``

I drilled down the source code and I suspect there could be something missing at 

https://github.com/akka/akka/blob/v2.4.8/akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala#L208

Maybe the ``localAddressPromise`` should be broken on ``CommandFailed`` (in addition to failStage) as there won't be any local address to make the promise succeed because TCP cannot connect a server which does not exists.

```
msg match {
  case CommandFailed(cmd) => 
    val cause = new StreamTcpException(s"Tcp command [$cmd] failed")
    localAddressPromise.failure(cause)
    failStage(cause)
```

**Comment by johanandren** [comment]
I think that sounds like a reasonable fix, maybe it should be done also on receiving `Terminated` while in the `connecting` state.

**Comment by johanandren** [comment]
Turns out that is already handled a bit further down in the Stage. https://github.com/akka/akka/blob/v2.4.8/akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala#L289
