### ISSUE TITLE
Make using EventAdapters nicer in PersistenceQuery

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21065]
It should be easier to apply EventAdapters on the query side.
Currently it is possible, but manual via:

```scala
val eventAdapters = Persistence(system).adatpersFor("journal-id")

  private[akka] final def adaptFromJournal(repr: PersistentRepr): immutable.Seq[PersistentRepr] =
    eventAdapters.get(repr.payload.getClass).fromJournal(repr.payload, repr.manifest).events map { adaptedPayload ⇒
      repr.withPayload(adaptedPayload)
    }
```

**Comment by patriknw** [comment]
We have already discussed this in https://github.com/akka/akka/issues/18050
There the conclusion is that it should be done in the plugins. I have created an issue in the C* plugin: https://github.com/akka/akka-persistence-cassandra/issues/116
