### ISSUE TITLE
Optimise ByteStrings such that it remembers into which byte string what offset addresses

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21067]
While looping through all items of a `ByteStrings` via `bs(i)` we do a lot of scanning to find in which Array we actually want to index into. This is used a lot in JSON parsing, so we issue a .compact there (copy the array):

```scala
val parserInput = new SprayJsonByteStringParserInput(bs.compact)
```

If the `apply(Int)` access would be optimised for linear access if could remember that "oh, last I accessed `n`, and that was the `m`-th Array" so we could speed up the scanning through case.

**Comment by Hawstein** [comment]
Why not just remember that "oh, last I accessed `n`, and the value is `v`", this solution uses exactly the same size of extra space with yours but optimises the access time to `O(1)` after the first access.

**Comment by ktoso** [comment]
We don't care about repeated access to the same value, we care about the _next_ value, as we're iterating over the `ByteStrings` and figuring out each time to which actual `Array[Byte]` to index into. This would make the looking up the byte array constant time

**Comment by ktoso** [comment]
It'd avoid this loop:

```
while (idx >= seen + bytestrings(pos).length) {
          seen += bytestrings(pos).length
          pos += 1
        }
        bytestrings(pos)(idx - seen)
```

**Comment by Hawstein** [comment]
Oh I see. Thanks for making the problem clear to me. As for the problem, keeping the `Array[Byte]` index in another array has no advantage over the `.compact` method call since the initialization of the extra array will cost linear time. However, if I keep the `last access` state in one single variable, it will not help much when multiple threads access the `ByteStrings` at the same time. The feasible solution I can think of is providing another method which take the current index and the `Array[Byte]` index of the pre-elem, return current value and the `Array[Byte]` index of current-elem, for example:

```scala
    ...
    private val accumulatedLength: Seq[Int] = {
      var sum = 0
      val acc = new Array[Int](bytestrings.size)
      val sizes = bytestrings.map(_.length)
      var i = 0
      while (i < bytestrings.size) {
        sum += sizes(i)
        acc(i) = sum
        i += 1
      }
      acc.toSeq
    }

    private def get(idx: Int): (Byte, Int) = {
      if (0 <= idx && idx < length) { 
      var pos = 0
        var seen = 0
        while (idx >= seen + bytestrings(pos).length) {
          seen += bytestrings(pos).length
          pos += 1
        }
        (bytestrings(pos)(idx - seen), pos)
      } else throw new IndexOutOfBoundsException(idx.toString)
    }

    def apply(idx: Int, preElemArrayIdx: Int = -1): (Byte, Int) = {
      if (0 <= idx && idx < length) {
        if (preElemArrayIdx <= -1) {
          get(idx)
        } else {
          if (idx < accumulatedLength(preElemArrayIdx)) { // stay in the same Array with pre-elem
            val seen = if (preElemArrayIdx == 0) 0 else accumulatedLength(preElemArrayIdx - 1)
            (bytestrings(preElemArrayIdx)(idx - seen), preElemArrayIdx)
          } else {
            (bytestrings(preElemArrayIdx + 1).head, preElemArrayIdx + 1)
          }
        }
      } else throw new IndexOutOfBoundsException(idx.toString)
    }
    ...
```

Any suggestions? @ktoso

**Comment by ktoso** [comment]
>As for the problem, keeping the Array[Byte] index in another array has no advantage over the .compact method call since the initialization of the extra array will cost linear time. 

I'm not suggesting any more arrays, just one variable.

> However, if I keep the last access state in one single variable, it will not help much when multiple threads access the ByteStrings at the same time. 

Yes, 1 variable, but with the offset for the linear scan hint.

No, it does not have to care about concurrent access since it would be a view.

`val fast = ByteStrings(...).fastIndexingInto` which contains the offset variable we need.

Anyway, this needs benchmarks otherwise we're just guessing around :-)
If you're interested to work on it please prepare JMH benchmarks in akka-bench-jmh and we can see to optimise the case I talked about

**Comment by Hawstein** [comment]
Yes, I am interested to work on it. However, I still don't get your point how one variable can deal with this problem. We will add one mutable variable, right? If two threads loop through the items of ByteStrings at the same time, they will both modify the variable and it is not guaranteed keeping the last access state for the two threads. So can not properly access the next value in constant time.

Is there anything I have misunderstood?

**Comment by ktoso** [comment]
It's a special case – there will be no 2nd thread accessing this.
We're in a tight `for(i;i<lenght;i++)` loop.

**Comment by Hawstein** [comment]
Hmm, I see. Will work on it tomorrow, must go to sleep now. Thanks for your patient answer :)

**Comment by ktoso** [comment]
Thanks! Would be cool :-)
Happy to help with all the quirks.
The case that we'd hope to speed up here is anything that uses the ByteStringParserInput :)

**Comment by ktoso** [comment]
@Hawstein did an impl of this and turned out not to be worth it.
Thanks a lot for your effort there!
