### ISSUE TITLE
Old remoting: Properly allow disabling TLSv1 by setting "akka.remote.netty.ssl.security.protocol"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21077]
Issue found via mailing list discussion: https://groups.google.com/forum/#!topic/akka-user/JH6bGnWE8kY

We should set the enabledProtocols explicitly when configuring the engine.

**Comment by wsargent** [comment]
You can also call setAlgorithmConstraints directly:

```
val sslParameters = sslContext.getDefaultSSLParameters() // clones new instance from default
val sslEngine = sslContext.createSSLEngine(peerHost, peerPort)
sslParameters.setAlgorithmConstraints(algConstraints)
sslEngine.setSSLParameters(sslParameters)
```

https://docs.oracle.com/javase/8/docs/api/java/security/AlgorithmConstraints.html
