### ISSUE TITLE
webSocketClientFlow does not close input when output is done

### ISSUE THREAD

**Issue by monktastic** [akka/akka#21089]
This flow should close the websocket when the output stream or input stream finishes, according to the doc:
>      val flow = Http().webSocketClientFlow(WebSocketRequest("ws://echo.websocket.org"))

But when the output finishes, the input stream is not shut down (nor is the websocket closed). E.g.:
>       val KeepAliveMsg = TextMessage(JsString("KeepAlive").toString)
>       val src = Source.tick[Message](1.seconds, 1.seconds, KeepAliveMsg)
>       val sink = myPrintFlow[Message].viaMat(KillSwitches.single)(Keep.right).to(Sink.ignore)
>       src.via(flow).runWith(sink).shutdown()

The output is closed, but it keeps sending ticks down the websocket.

**Comment by johanandren** [comment]
I think that is a documentation incorrectness. Half-closed is about the connection staying alive when the writing side is closed.

In this case you are closing the reading side but you will continue to write forever. If you put the killswitch after the source instead of before the sink it should work.

**Comment by johanandren** [comment]
Fixing it should be done by updating the docs from saying "if the either stream completes the entire connection is closed" to "if the writing side"

**Comment by monktastic** [comment]
Ah, thanks. Additionally: if the server requests a close (in my case, I'm guessing it sent a close control frame with status 1003, since it couldn't parse my KeepAlive message -- but I can double check), my Actor sink gets a shutdown message, but the source side does not.

Is that expected?

For now, my solution is to use a TerminationWatcher / KillSwitch combo pair to complete the input and output sides once the other side completes.

**Comment by johanandren** [comment]
When the client sends a close frame, the server closes the incoming connection but it cannot know how to complete your outgoing sink if you have made a disconnect between the incoming and outgoing stream, so you'd have to make sure it completes yourself, just like you describe.

**Comment by monktastic** [comment]
That makes sense. My setup is like this:

On the server side, there's a Play websocket handler being handled by my Actor. Then:

1) Client sends a message the Play cannot parse.
2) Play shuts down Actor.
3) Client read side gets terminated.
4) Client keeps writing, and Play keeps listening (but it has nowhere to forward messages).

It's surprising to me that Play would keep accepting messages forever, but maybe I need to understand the WS spec better....

**Comment by johanandren** [comment]
Agh, sorry, I mixed things up, my previous comment was if you'd had been using the websocket server, not the client.

**Comment by monktastic** [comment]
No prob. So in your understanding, everything's working as expected right?

**Comment by johanandren** [comment]
This is where the logic is: https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameOutHandler.scala#L34

Input was already closed, the `FrameOutHandler` gets a `PeerClosed`, becomes `WaitingForTransportClose`, pushes a close frame, waits for a timeout (3 seconds non configurable right now), and completes the stage. So it should shut down in your described scenario.

**Comment by monktastic** [comment]
My bad! I just tested this again. Indeed if the server requests a close, the client disconnects. It's only the case from my first message that I'm seeing, and now I have a fix for that. Thanks!

**Comment by johanandren** [comment]
Remarking as "new" as I'm a bit unsure if this really is a documentation incorrectness or not.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
