### ISSUE TITLE
Unmarshaller.class invalid dependency

### ISSUE THREAD

**Issue by ppiotrow** [akka/akka#21107]
This error showed in my project after switching to version `2.4.9-RC1`

> [error] missing or invalid dependency detected while loading class file 'Unmarshaller.class'.
> [error] Could not access type Unmarshaller in value akka.http.javadsl.unmarshalling,
> [error] because it (or its dependencies) are missing. Check your build definition for
> [error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic class path.
> [error] A full rebuild may help if 'Unmarshaller.class' was compiled against an incompatible version of akka.http.javadsl.unmarshalling.
> )

**Comment by ppiotrow** [comment]
Seems like a duplicate of https://github.com/akka/akka/issues/21105 which wasn't yet tagged as 2.4.9-RC1

**Comment by ktoso** [comment]
It won't be marked as `2.4.9-RC1` because that's a milestone, not tag, and those we use to mark what features went into a release.

Yes, 2.4.9-RC1 is broken – "thanks osgi!".
We'll fix it, closing this ticket as duplicate though.

Thanks for reporting!
