### ISSUE TITLE
Move IntegrationRoutingSpec to akka-http-testkit

### ISSUE THREAD

**Issue by leachbj** [akka/akka#21102]
Recently I had to test a directive that used the withRequestTimeoutResponse directive but was unable to make it work with a regular ScalatestRouteTest.  I found that  IntegrationRoutingSpec in the akka-http-tests module however worked great for this scenario.  Unfortunately it is private[akka] so I had to copy the code in order to re-use it.

It would be great to have official integration test support like IntegrationRoutingSpec available in akka-http-testkit.

**Comment by ktoso** [comment]
I have not really thought about it's API, that's why it's internal.
Would you help me out here and go over it's API and see if it has everything we need?

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
