### ISSUE TITLE
Missing akka.http.javadsl.unmarshalling.Unmarshaller in distro of Akka 2.4.9-RC1

### ISSUE THREAD

**Issue by dnvriend** [akka/akka#21105]
Missing akka.http.javadsl.unmarshalling.Unmarshaller in Akka 2.4.9-RC1 distro, as akka.http.scaladsl.unmarshalling.Unmarshaller extends the javadsl version, if effectively breaks akka-http when used with the vendor-specific-media-type strategy that uses the Unmarshaller extensively.

**Comment by ktoso** [comment]
Thanks for reporting – we'll fix this right away.
2.4.9-RC1 is indeed dead on arrival – damn you osgi-plugin...!

```
[error] missing or invalid dependency detected while loading class file 'Unmarshaller.class'.
[error] Could not access type Unmarshaller in value akka.http.javadsl.unmarshalling,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with -Ylog-classpath to see the problematic class path.
[error] A full rebuild may help if 'Unmarshaller.class' was compiled against an incompatible version of akka.http.javadsl.unmarshalling.
)
```

**Comment by jycr** [comment]
You can temporary replace in your Maven local cache :
* akka-http-experimental_2.11-2.4.9-RC1.jar
(from http://search.maven.org/remotecontent?filepath=com/typesafe/akka/akka-http-experimental_2.11/2.4.9-RC1/akka-http-experimental_2.11-2.4.9-RC1.jar)
* by this one into official distrib : http://downloads.typesafe.com/akka/akka_2.11-2.4.9-RC1.zip

**Comment by ktoso** [comment]
Thanks for the workaround while we work on fixing this.

The "fun" bug which causes this is: https://github.com/sbt/sbt-osgi/issues/30

**Comment by ktoso** [comment]
Also related https://github.com/akka/akka/issues/20583

**Comment by ktoso** [comment]
I have fixed and released the 3rd party sbt plugin, sbt-osgi: https://github.com/sbt/sbt-osgi
And enabled more checks in the Akka build.
The build will never again allow this nasty and silly issue to happen.

We'll roll a stable 2.4.9 very soon, thanks for checking the RC everyone.

**Comment by ktoso** [comment]
Solution PR posted: #21121

**Comment by hseeberger** [comment]
I say it again: drop silly OSGi support!

**Comment by ktoso** [comment]
We may actively start lobbying that, esp with Java 9 around the corner. ;)

**Comment by njbartlett** [comment]
Oh Heiko, if you can't handle OSGi you're gonna love JPMS!
