### ISSUE TITLE
Default rejection handlers do not discard entity bytes

### ISSUE THREAD

**Issue by mpilquist** [akka/akka#21123]
The default rejection handlers do not discard request entity bytes before completing requests. For example, if a request is rejected with an `AuthorizationFailedRejection`, the default rejection handler will complete the request with a `403`, ignoring the request entity.

I think this will lead to problems but I haven't tried reproducing. I noticed this when updating a code base to properly discard request/response entities on server/client side. Might be worth a mention in the docs on writing custom rejection handlers.

**Comment by ktoso** [comment]
Thanks for reporting, we should definitely look into this.
In general draining handling needs more love and this one is on the edge of being a bug I'd say even, rejecting would cause connections to stall – I'll mark as bug and hope to look at it soon

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
