### ISSUE TITLE
shaded jar-with-dependencies gives No configuration setting found for key 'akka.version'

### ISSUE THREAD

**Issue by dwschulze** [akka/akka#21120]
I've used the plugin given in the [akka docs](http://doc.akka.io/docs/akka/current/general/configuration.html) but when I run my jar-with-dependencies I still get an Exception saying

`No configuration setting found for key 'akka.version'`

I've also tried version 2.4.2 of the maven-shade-plugin with the same results.  My pom.xml is:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>akka</groupId>
	<artifactId>remoting.example</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-remote_2.11</artifactId>
			<version>2.4.8</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-actor_2.11</artifactId>
			<version>2.4.8</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>2.4.2</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>allinone</shadedClassifierName>
							<artifactSet>
								<includes>
									<include>*:*</include>
								</includes>
							</artifactSet>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>reference.conf</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<manifestEntries>
										<Main-Class>akka.Main</Main-Class>
									</manifestEntries>
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<archive>
						<manifest>
							<mainClass>remoting.example.server.ServerActorApp</mainClass>
						</manifest>
					</archive>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id> <!-- this is used for inheritance merges -->
						<phase>package</phase> <!-- bind to the packaging phase -->
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by patriknw** [comment]
The important part is that all reference.conf files are appended. That is done by the `AppendingTransformer` config for `maven-shade-plugin`. I'm not sure what the corresponding setting for `maven-assembly-plugin` is.

**Comment by dwschulze** [comment]
Are you saying that the maven-assembly-plugin has to be changed too?  There's nothing in the akka documentation page above that indicates that.  It just shows a maven <plugin> to create the combined reference.conf.

**Comment by dwschulze** [comment]
Do you have a complete pom.xml that builds a jar-with-dependencies with a correct combined reference.conf?

**Comment by johanandren** [comment]
The original akka-actor jar `reference.conf` contains an include `include "version"`, it is not in the concatenated `reference.conf` in the jar-with-dependencies, that's why it does not work. 

No idea why the AppendingTransformer would omit it though.

**Comment by glorysdj** [comment]
still encounter this issue when i use maven assembly to make a jar with akka-http, akka-stream, akka-actors,

with settings in maven-shade-plugin as below, the reference.conf only has conf in akka-actor.

<configuration>
                       
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                            </transformers>
                        </configuration>
