### ISSUE TITLE
headers.header[`Content-Type`] throws java.lang.ClassCastException

### ISSUE THREAD

**Issue by schmitch** [akka/akka#21127]
actually the following works:
```
    val ct = httpResponse.entity.contentType
    println(ct.value)
```

however this won't:
```
    val ct1 = httpResponse.header[`Content-Type`]
    println(ct1.map(_.value()))
```

Will throw:

java.lang.ClassCastException: akka.http.scaladsl.model.ContentType$WithCharset cannot be cast to akka.http.scaladsl.model.headers.Content$minusType

I guess the following is the problem inside the header method:
```
      case _ if clazz == classOf[`Content-Type`] ⇒ Some(entity.contentType).asInstanceOf[Option[T]]
``` 
entity.contentType is not `Content-Type` so it will fail it would need to be:
```
      case _ if clazz == classOf[`Content-Type`] ⇒ Some(`Content-Type`(entity.contentType)).asInstanceOf[Option[T]]
```
I guess.

**Comment by johanandren** [comment]
I think you are confusing two types:
`akka.http.scaladsl.model.ContentType` is one type which models content types, while `akka.http.scaladsl.model.headers.Content-Type` is a type which models the HTTP header for content types.

They are not the same. The header will have a value of the type `akka.http.scaladsl.model.ContentType` though.

`HttpEntity.contentType` does not return the header but the content type of the entity (which internally comes from the value of the header)

**Comment by schmitch** [comment]
Actually I understand that, but you can't query the Content-Type out of the Header even when `httpResponse.header` contains the following code (internal akka):
```scala
case _ if clazz == classOf[`Content-Type`] ⇒ Some(entity.contentType).asInstanceOf[Option[T]]
```
this will fail with the exception I described and the reason is, is that I query for `akka.http.scaladsl.model.headers..Content-Type` but get back a `akka.http.scaladsl.model.ContentType. That's why I get a `ClassCastException` but that comes from akka and not from me.

**Comment by johanandren** [comment]
Ah, sorry I did not read the description carefully enough, so what you are saying is that `HttpMessage.contentType` on `HttpEntity` is broken for querying it with the `Content-Type` header. Got it.

**Comment by schmitch** [comment]
Actually not `HttpMessage.contentType` is broken `HttpMessage.header[akka.http.scaladsl.model.headers.`Content-Type`]` is broken. 
If it shouldn't be queried via the `header` method than you should at least write something:

`case _ if clazz == classOf[`Content-Type`] ⇒ throw new IllegalStateException("use entity.contentType instead")` instead of giving back a `akka.http.scaladsl.model.ContentType` which is wrong since I wanted the encapsulated header value.

**Comment by schmitch** [comment]
I referenced an PR, this fixes it. Another solution as said would be throwing a IllegalStateException

**Comment by johanandren** [comment]
I just added this test case to master:

```
val contentType = ContentTypes.`text/html(UTF-8)`
val message = HttpRequest(headers = List(`Content-Type`(contentType)))

message.header[`Content-Type`] shouldEqual Some(`Content-Type`(contentType))
```

And it passes both for request and response, so I'm still not clear if this ticket really is a bug or not.

**Comment by johanandren** [comment]
Ah, now I get it, that doesn't actually cover it because it's not among the headers. NVM

**Comment by schmitch** [comment]
yeah probably it's also a bad idea to use the message.header to query the content type since this is obviously also at the entity. but I really really like the typed headers interface.

There is just one problem with that interface you can't easily filter them.
Something like message.headers.filter[Cookie] returning Seq[Cookie] would be really cool.
https://github.com/schmitch/play-ws-akka/blob/master/src/main/scala/play/api/libs/ws/akkaws/AkkaWSResponse.scala#L46
