### ISSUE TITLE
akka-stream Framing.lengthField including size field

### ISSUE THREAD

**Issue by irundaia** [akka/akka#21126]
I'm working on a steaming protocol which sends (most) messages in the following way:
1. 1 byte message identifier
2. 4 byte length indicator (this length equals to the length of the payload in bytes + 4bytes for the length indicator field)
3. payload

I was hoping that we could modify the `Framing.lengthField(fieldLength, fieldOffset, maximumFrameLength, byteOrder)` function to include a length modifier. This modifier would then indicate the number of byte to be added to the value found in the message.
In my case, this would mean that I'd have to pass -4 to the function.

If desirable, I could submit a pull request this evening(-ish)

**Comment by drewhk** [comment]
Looks like a good addition to me. We would really appreciate a PR on this.

**Comment by ktoso** [comment]
This seems to have been completed on #21173

**Comment by wmszeliga** [comment]
I have a similar message framing issue. @irundaia do you have an example of how you used your patch?
