### ISSUE TITLE
Directive extractClientIP broken in 2.4.9-RC2

### ISSUE THREAD

**Issue by clyde-chuang** [akka/akka#21130]
Hi,

Remote-Address header is missing in 2.4.9-RC2 (akka.http.server.remote-address-header = on)
Therefore, directive extractClientIP will never be matched.

It works perfectly in 2.4.8

**Comment by johanandren** [comment]
Hi, what do you mean "is missing" (the class `akka.http.scaladsl.model.headers.Remote-Address` is definitely still there). Can you provide us with a minimal reproducer?

**Comment by johanandren** [comment]
No need for a reproducer, I have reproduced it myself.

**Comment by clyde-chuang** [comment]
Hi,
I mean "Remote Address header" is not injected into RequestContext; therefore, related Directives would never work.
Thaenks for your prompt fix.
