### ISSUE TITLE
FAILED aborted builds

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21144]
This has kept happening for a while (I think @ktoso said it was because hitting a max time of 2 hours).

https://jenkins.akka.io:8498/job/akka-multi-node/1698//consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1697//consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1696//consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1700//consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1701//consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1704//consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1705//consoleFull

**Comment by patriknw** [comment]
@johanandren This seems "fixed" now, right? We have Timeout minutes: 150 in the job.

**Comment by johanandren** [comment]
It seems like that. I'll close.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3735//consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/3736//consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/3742//consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/3743//consoleFull

`Build timed out (after 120 minutes). Marking the build as failed.`

**Comment by patriknw** [comment]
Were these thursday or friday? The config bug caused incredeble long build time.

**Comment by johanandren** [comment]
This night.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3744//consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3748//consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/3749//consoleFull

**Comment by johanandren** [comment]
I'll try to up it 30 minutes for now but I guess we want it to complete faster/find what actually taking so much time

**Comment by johanandren** [comment]
Whoa, it hasn't passed since sept 29 :(

**Comment by johanandren** [comment]
Seems as the increase to 2h 30mins made this stop happening. I'll close it for now.
