### ISSUE TITLE
ShardRestart message can't be processed properly in case of defined messageExtractorId

### ISSUE THREAD

**Issue by 412b** [akka/akka#21145]
In request #17871 `RestartShard` message was added, but it's not working properly [here](https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L416) in case `messageExtractorId` is defined. It ends up with `private` `RestartShard` being exposed to userspace, which can't handle it properly anyway.
The consequence of it all is clearly pretty frustrating, but the fix is really straight forward: just swap order in `match` as `RestartShard` is handled in `deliverMessage`.
I can submit a PR, if needed. But it will also require being covered by test.

**Comment by 412b** [comment]
Ok, I see a problem in the extractor we had used at that moment as well, it wasn't returning null for unknown messages, though documentation is a bit misleading compared to existing impl (`RestartShard` won't be posted as `Unhandled` on the event stream).
Anyway `RestartShard` messages shouldn't reach userspace, imho.

**Comment by patriknw** [comment]
PR is welcome
