### ISSUE TITLE
JsonObjectParser mishandles single quotes in 2.4.9-RC2

### ISSUE THREAD

**Issue by mikesname** [akka/akka#21147]
The `JsonObjectParser` used internally by the `JsonEntityStreamingSupport` framing decoder fails when object keys or values contain unmatched single quotes, e.g:

```json
{
    "text": "'"
}
```

The most obvious culprit appears to be [here](https://github.com/akka/akka/blob/a712f0149a38335c77dbed9d33da22a7a083c8eb/akka-stream/src/main/scala/akka/stream/impl/JsonObjectParser.scala#L20):

    final val DoubleQuote = '\''.toByte

In the case of a single object array such as `[{"text": "'"}]`, the framing decoder will simply not emit the object.

**Comment by mikesname** [comment]
Added a PR since this is the one breaking my stuff :wink:

**Comment by drewhk** [comment]
Great, thanks for the help!
