### ISSUE TITLE
JsonFraming.objectScanner does not handle raw JSON values (contra Scaladoc) 2.4.9-RC2

### ISSUE THREAD

**Issue by mikesname** [akka/akka#21151]
The Scaladoc for `JsonFraming.objectScanner` [state](https://github.com/akka/akka/blob/a712f0149a38335c77dbed9d33da22a7a083c8eb/akka-stream/src/main/scala/akka/stream/scaladsl/JsonFraming.scala#L39):

    Framing raw JSON values (such as integers or strings) is supported as well.

However, this does not currently seem to be the case (at least not how I'd imagine its used, as per below):

```scala
"parse an array of primitive values" in {
  val input = """[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]"""

  val result = Source.single(ByteString(input))
    .via(JsonFraming.objectScanner(Int.MaxValue))
    .runFold(Seq.empty[Int]) {
      case (acc, entry) ⇒ acc ++ Seq(entry.utf8String.toInt)
    }
  result.futureValue shouldBe 0.to(9)
}
```
Current result:

    akka.stream.scaladsl.Framing$FramingException: Invalid JSON encountered at position [1] of [ByteString(91, 48, 44, 32, 49, 44, 32, 50, 44, 32, 51, 44, 32, 52, 44, 32, 53, 44, 32, 54, 44, 32, 55, 44, 32, 56, 44, 32, 57, 93)]

**Comment by johanandren** [comment]
That would be an array though, not a stream of ints?
A stream of ints would be
```
0
1
2
```
No?

**Comment by johanandren** [comment]
NVM! Misunderstood what you wrote!

**Comment by ktoso** [comment]
The name of the scanner is not accidental. It works for objects.
The docs are currently misleading then.

Or we could improve the scanner.
PR going either way very welcome

**Comment by johanandren** [comment]
I'm anyways touching it, so I will remove the doc line in that pr
