### ISSUE TITLE
JsonFraming.objectScanner failed to emit all output objects for some input - 2.4.9-RC2

### ISSUE THREAD

**Issue by mikesname** [akka/akka#21150]
It seems that for certain ByteString inputs, the `JsonFraming.objectScanner` fails to reliably emit all objects. I noticed this when trying to add tests for #21147. For example, the following spec reliably fails for me:

```scala
    "parse an array of small objects" in {
      val input = """[{"a": 0}, {"b":1}, {"c":2}, {"d":3}, {"e":4}]"""

      val result = Source.single(ByteString(input))
        .via(JsonFraming.objectScanner(Int.MaxValue))
        .runFold(0) {
          case (acc, _) ⇒ acc + 1
        }
      result.futureValue shouldBe 5
    }
```

The output count is sometimes 3, sometimes 4 objects, but that last elements do not seem to be consumed.

**Comment by johanandren** [comment]
For the record it is actually not about it being an array of small objects but there being more elements to parse when the upstream completes.
