### ISSUE TITLE
configure the number of shards to hand off when cluster rebalances?

### ISSUE THREAD

**Issue by abesanderson** [akka/akka#21163]
In cluster sharding, there is a rebalance tick that runs at a given interval, but it seems like it's only handing off one shard at a time, even when the simultaneous rebalances is increased.  The net effect of this is if you have a big change to your cluster shards, such as a loss or addition of many nodes, which can happen on startup, rolling restart or a network partition, it takes a very long time to rebalance those shards to other nodes that can handle them(max number of shards to reallocate * interval).  At defaults, if i have 300 shards, 10 nodes, but initial shard assignment goes to the first 5 that came up, 150 shards that need to be reallocated over the remaining 5, 10 seconds to move one shard, that ends up being about 30 minutes before I reach balance.  I'm wondering if another flag is necessary, similar to max-simultaneous-rebalances but allow for multiple RebalanceWorker to be created on the same rebalance interval tick.

**Comment by patriknw** [comment]
Sounds like a good observation. I think we can be much more agressive and kick-off up to max-simultaneous on each tick. No need for additional config. Would you like to create a pull request (that is fastest way to make it happen)?

**Comment by abesanderson** [comment]
The simple solution for this is to grab from the largest region and send back a set of shard ids to handoff.  This does run the risk that shards which are ultimately going to be reassigned back to the original hosting shard region go thru the (potentially expensive) passivate/handoff.  I can pursue other solutions that loop thru the rebalance logic until rebalanceInProgress set contains up to max-simultaneous-rebalance if it is not acceptable to handoff shards such that the largest shard region drops below the average shard count per region.  Thoughts?
