### ISSUE TITLE
Clarify directive complete reponse body rendering

### ISSUE THREAD

**Issue by matheuslima** [akka/akka#21177]
Actually, if we call complete passing only StatusCode as parameter, the reponse will have the StatusCode.toString as body. This is not documented. For example:

```
complete(StatusCodes.OK)
```

will render a response with status code 200 and body "OK"

**Comment by johanandren** [comment]
It does show in the example in the directive docs though, route `b` here:
http://doc.akka.io/docs/akka/2.4/scala/http/routing-dsl/directives/route-directives/complete.html#signature

Could be mentioned for each signature variation what the result will be in the **Signature** code block perhaps?

**Comment by johanandren** [comment]
It's actually not `toString` but the return value of `defaultMessage` of the `StatusCode` instance.

**Comment by jiminhsieh** [comment]
@johanandren @ktoso Is this issue should be move to Akka-HTTP? I could not search this issue in Akka-HTTP. This issue may belong to Akka-HTTP.

**Comment by ktoso** [comment]
Thanks, good point, seems I missed it during moving tickets over to http!
Moved: https://github.com/akka/akka-http/issues/1303
