### ISSUE TITLE
Default DNS provider blocks on default dispatcher

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21170]
The `InetAddressDnsProvider` uses `InetAddress.getAllByName` to resolve dns addresses, which is blocking shouldn't it:

A. run on a separate dispatcher (probably something like a pinned dispatcher
B. not block at all

Additionally, the same pet peeve I have with the Java DNS, shouldn't it use the TTL from the DNS entries rather than a hardcoded global TTL?

**Comment by drewhk** [comment]
The DNS dispatcher is configurable though, it is only that the default is not a separate one.

**Comment by johanandren** [comment]
See also #21171 

I still think the default one should be safer/better.

**Comment by schmitch** [comment]
The question is, is B really that hard to do? UDP calls are cheap. And DNS isn't a "hard" protocol.

I'm willing to give it a try and maybe I can tackle (#16846).

**Comment by drewhk** [comment]
@schmitch the issue is when other things hook into the name resolution process, i.e. Enterprise stuff (it is not "just" DNS AFAIK). I.e. it is safer in some sense to rely on the JDK on these matters than to use DNS directly.

**Comment by schmitch** [comment]
as far as I know, `InetAddress.getAllByName` does "just" DNS. It doesn't support any "Enterprise" stuff or DNSSEC at all.

**Comment by patriknw** [comment]
I agree that it's not nice to run any kind of blocking on the default-dispatcher. I think we should introduce a new `default-blocking-io-dispatcher` in `akka-actor` and perhaps at some point consolidate that with `akka.stream.default-blocking-io-dispatcher`.

**Comment by patriknw** [comment]
Related is that `remoteAddress.getHostName` is done from from `TcpOutgoingConnection`. It's also potentially blocking. Would be nice to at least collect the blocking calls in one place, in the DnsProvider actor.

I think we can/should introduce that `default-blocking-io-dispatcher` in Akka 2.5, and use that as the default for the DnsProvider actor.

**Comment by ortigali** [comment]
`remoteAddress.getHostName` is not blocking if it is unresolved (in `InetSocketAddress` source code) . In  `TcpOutgoingConnection` and other `akka.io` classes `getHostName` was called when it was unresolved.

about DNS TTL, make  them as `positive-ttl=auto` & `negative-ttl = auto`. And it will try to get from `java.security.Security.getProperty("networkaddress.cache.ttl")` & `java.security.Security.getProperty("networkaddress.cache.negative.ttl")` respectively. If it returns null, it is value would be 30s for positive & 10s for negative which are current default value. Is this approach true?
