### ISSUE TITLE
Java API for WS testkit is missing

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21184]
The Scala side of the HTTP Testkit has tools for testing websocket routes, sadly they are missing on the Java side though.

**Comment by ktoso** [comment]
Yes, that plan sounds good.

Note that in scaladsl the Message has `sealed trait Message // FIXME: Why don't we extend akka.http.javadsl.model.ws.Message here?
`
Though I fear we might break binary compatibility if we make them extend one another... I'm not sure, best to give it a try, thanks!
for the model scaladsl should extend javadsl.

**Comment by ktoso** [comment]
> In addition, I think the ws model like Message in scaladsl should extends the counterpart of javadsl. This will make the above WS testkit in javadsl more reasonable.

If not doable in a compatible way, let's make this a separate ticket

**Comment by Hawstein** [comment]
Seems like it's not doable in a compatible way. The `mimaReportBinaryIssues` complained and those API are not INTERNAL so we cannot add filters in `Mima.scala` for it, right?
```scala
[info] akka-http-core: found 4 potential binary incompatibilities while checking against com.typesafe.akka:akka-http-core_2.11:2.4.2  (filtered 181)
[error]  * method asScala()akka.http.scaladsl.model.ws.TextMessage in trait akka.http.scaladsl.model.ws.TextMessage is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.model.ws.TextMessage.asScala")
[error]  * method getStreamedText()akka.stream.javadsl.Source in trait akka.http.scaladsl.model.ws.TextMessage is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.model.ws.TextMessage.getStreamedText")
[error]  * method asScala()akka.http.scaladsl.model.ws.BinaryMessage in trait akka.http.scaladsl.model.ws.BinaryMessage is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.model.ws.BinaryMessage.asScala")
[error]  * method getStreamedData()akka.stream.javadsl.Source in trait akka.http.scaladsl.model.ws.BinaryMessage is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.model.ws.BinaryMessage.getStreamedData")
```

What's the general solution for those issues which cannot be solved in a  compatible way? Waiting for the next big release such 3.x ?

**Comment by Hawstein** [comment]
Not making the scaladsl mode to extend javadsl model, we can also simply imitate the WS testkit in scaladsl to write a javadsl version. so let's do it this way and make the scaladsl model extending javadsl a separate ticket ?

**Comment by johanandren** [comment]
It is special though, because the API is public but it is not public for inheriting, so I think that would be safe as long as the same methods are available to consumers.
