### ISSUE TITLE
The fromStatusCode marshaller ignores allowsEntity

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21182]
When completing a request with `complete(StatusCodes.NoEntity)` the response will have `defaultMessage` "No Content" even though `StatusCodes.NoEntity.allowsEntity == false`, that can't be right.

The marshaller should set an empty/no entity if `allowsEntity` is false.

**Comment by johanandren** [comment]
Should have tried to reproduce first, it's actually filtered out later in the pipeline.

**Comment by ktoso** [comment]
:)
