### ISSUE TITLE
Adding actorOf method to TestKitBase to start actors in testActor's context

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka#21198]
This will help to avoid problems described [here](https://github.com/akka/akka/issues/21195), and will make TestKit's interface more clear without need to start actors from system's global context

**Comment by manonthegithub** [comment]
I could try to implement it

**Comment by jypma** [comment]
I ran into this once again as well, decided to just implement it: https://github.com/akka/akka/pull/21201

**Comment by manonthegithub** [comment]
Closing as duplicate

**Comment by jypma** [comment]
@manonthegithub Duplicate of what? I opened https://github.com/akka/akka/pull/21201 referring to this, which other issue should I make it refer to?

**Comment by manonthegithub** [comment]
duplicate of yours [#21201](https://github.com/akka/akka/pull/21201),
ok ill reopen it
