### ISSUE TITLE
Warning while parsing ETag

### ISSUE THREAD

**Issue by zikolach** [akka/akka#21200]
I'm getting following warning while parsing responses containing ETag header with spaces inside: 
```
Illegal response header: Illegal 'etag' header: Invalid input ' ', expected etagc-base, obs-text or '"' (line 1, column 7): W/"Thu Aug 04 14:46:29 UTC 2016"
```
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11:
```
entity-tag = [ weak ] opaque-tag
      weak       = "W/"
      opaque-tag = quoted-string
```
and https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2
```
quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
qdtext         = <any TEXT except <">>
TEXT           = <any OCTET except CTLs,
                        but including LWS>
CRLF           = CR LF
OCTET          = <any 8-bit sequence of data>
CTL            = <any US-ASCII control character
                        (octets 0 - 31) and DEL (127)>
LWS            = [CRLF] 1*( SP | HT )
CR             = <US-ASCII CR, carriage return (13)>
LF             = <US-ASCII LF, linefeed (10)>
SP             = <US-ASCII SP, space (32)>
HT             = <US-ASCII HT, horizontal-tab (9)>
<">            = <US-ASCII double-quote mark (34)>
```
space is allowed character.

It might be necessary to change `etagc-base` definition [here](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-http-core/src/main/scala/akka/http/impl/model/parser/CharacterClasses.scala#L77) from [Visible](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-parsing/src/main/scala/akka/parboiled2/CharPredicate.scala#L112) to [Printable](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-parsing/src/main/scala/akka/parboiled2/CharPredicate.scala#L113)

**Comment by 2beaucoup** [comment]
> According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11

Please refer to https://tools.ietf.org/html/rfc7232#section-2.3 for the up to date spec.

**Comment by zikolach** [comment]
So it looks like that format of ETag was changed and according to latest RFC it cannot contain spaces.

```
ETag = entity-tag
entity-tag = [ weak ] opaque-tag
etagc = "!" / %x23-7E ; '#'-'~' / obs-text
weak = %x57.2F ; W/
opaque-tag = DQUOTE *etagc DQUOTE
obs-text       = %x80-FF
```
