### ISSUE TITLE
Document "how to use artery"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21209]
External documentation, not internals.

**Comment by patriknw** [comment]
Mention -XX:MaxDirectMemorySize=256m
Especially when using `inbound-lanes > 1` it will require more memory since there are more buffers in flight (buffer size of the BroadcastHub + number of lanes)

**Comment by patriknw** [comment]
include one section explaining quarantine and what can cause it

**Comment by patriknw** [comment]
Mention troubleshoting for "a fault occurred in a recent unsafe memory access operation in compiled Java code"

https://github.com/real-logic/Aeron#troubleshooting

**Comment by patriknw** [comment]
Structure proposal (mostly copied from old docs):

* [ ] Explain new vs old remoting
       * experimental
       * protocol name difference
       * based on Aeron UDP
* [ ] Preparing your ActorSystem for Remoting
* [ ] Looking up Remote Actors
* [ ] Creating Actors Remotely
* [ ] Watching Remote Actors
* [ ] Serialization
       * also mention ByteBufferSerializer
       * mention `enable-additional-serialization-bindings=on` and `additional-serialization-bindings` in the docs for old remoting
* [ ] large-message-destinations
       * maximum-large-frame-size
* [ ] Untrusted Mode
* [ ] Quarantine
* [ ] Routers with Remote Destinations
* [ ] Akka behind NAT or in a Docker container
* [ ] Media Driver
* [ ] Flight Recorder
* [ ] Configuration
       * idle-cpu-level

At the same time, let's remove "Pluggable transport support" section from old docs.

**Comment by magro** [comment]
It would be great to have also a migration guide for a rolling upgrade.

**Comment by drewhk** [comment]
You won't be able to do a rolling upgrade. We broke the wire-level compatibility, for example we use UDP (via Aeron) instead of TCP

**Comment by magro** [comment]
@drewhk well, of course old and new are not compatible. I was thinking more about a higher level solution, e.g. the new app version would run artery additionally on a different port, but keep the old remoting active as well. Some balancer / remoting proxy could balance messages over old or new remoting, preferring the new if it's working. 

Do you think something like that would be possible?
