### ISSUE TITLE
Make sure no message needs Java serialization

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21202]
We have a few messages that still use java serialization.

Create all the serializers and just have a flag.

~~For artery we can make not using java serialization the default~~ https://github.com/akka/akka/issues/21339

**Comment by patriknw** [comment]
Related https://github.com/akka/akka/issues/20507

**Comment by ktoso** [comment]
This ticket wins the worst described ticket competition ;-) 
The last part I'll split out and explain better

**Comment by jrudolph** [comment]
Therefore, a few bits of clarifications:

 * overall goal is to use protobuf serialization instead of Java serialization for all artery messages
 * "just have a flag": use small single letter manifests instead of full class names

**Comment by drewhk** [comment]
> overall goal is to use protobuf serialization instead of Java serialization for all artery messages

Not just for *artery* messages but any message that can go over the wire and provided by Akka. I.e. stuff like PoisonPill, etc.

**Comment by patriknw** [comment]
yes, protobuf instead of Java serialization for everything.

Write the serializers with `SerializerWithStringManifest`, an example is https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala 

See also related ticket #20507

**Comment by patriknw** [comment]
> "just have a flag": use small single letter manifests instead of full class names

I don't understand. I don't see any need for that. We just use single letters for all new serializers.

What Konrad mean is that we can't change serialization for old messages in 2.4.x, but when Artery is enabled we can change the serialization to use the new serializers also for old messages.

Here are some such new serializers that are not enabled by default: https://github.com/akka/akka/blob/master/akka-remote/src/main/resources/reference.conf#L24-L33

**Comment by ktoso** [comment]
We actually had a call discussing this ticket, as it's so badly explained in the writeup ;)

**Comment by patriknw** [comment]
ok, everything clear?

**Comment by jrudolph** [comment]
Ah, looks like I mixed a few things up here. But thanks for the clarifications I think I somewhat understood the end goal by now :)

**Comment by jrudolph** [comment]
With #21380 all internal artery (system) message have been converted to protobuf.

**Comment by patriknw** [comment]
Let's create a list of know classes that require protobuffing:

[ ] all system messages
[ ] PoisonPill and Kill
[ ] RemoteWatcher Heartbeat messages
[ ] akka.actor.Status.* (+ exceptions?)
[ ] Config, used by DaemonMsgCreateSerializer (low priority)
[ ] ??? (run tests)

**Comment by johanandren** [comment]
The remote watcher heartbeating messages is covered (for artery) in #21511

**Comment by drewhk** [comment]
Taking primitive messages, PoisonPill and Kill

**Comment by drewhk** [comment]
Taking RemoteWatcher stuff

**Comment by patriknw** [comment]
Taking `akka.actor.Status`

**Comment by patriknw** [comment]
Added `ActorRef` to the list

**Comment by patriknw** [comment]
Taking ActorRef

**Comment by drewhk** [comment]
Hm, that is an interesting one. I guess compression is out of the question but caching the resolution still might be useful (using the LruCache)?

**Comment by drewhk** [comment]
Taking System messages

**Comment by patriknw** [comment]
yes, I guess it's not that common to send only ActorRefs, but slapping on the cache can't hurt

**Comment by drewhk** [comment]
Btw, what about thread safety when it comes to serializers and state?

**Comment by patriknw** [comment]
ah, yeah, they are concurrent, so I either we synchronize the access to the cache here or we skip the cache?

**Comment by drewhk** [comment]
...or make it ThreadLocal :( Not sure if it is worth it then.

**Comment by drewhk** [comment]
How do other serializers deal with ActorRef (i.e. when embedded in protobuf for example)? Do they just use the internal resolve? Would be nice to consolidate all these variants, and maybe then a ThreadLocal cache is no longer an overkill as it can be shared across all the users.

**Comment by patriknw** [comment]
That is a good point, I think there are many usages like that. I'll take a look.

**Comment by drewhk** [comment]
In fact such a cache can be used by the Decoder stage itself...

**Comment by patriknw** [comment]
Done. There might be a few left related to remote deployment, but since remote deployment is rather insecure in itself we didn't consider that so important (given time constraints)
