### ISSUE TITLE
Figure out how to support parallel serialization in Artery pipeline

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21207]
There are some options.

Current setting is good for latency - 1 synchronous pipeline.

We could have multiple serializer stages, and use a consistent hashing on recipient to preserve order.

On the incoming side it's a partition stage that does the hashing and just fans out.

As possible optimisation use a modified merge hub, to avoid async boundary actor messages

**Comment by patriknw** [comment]
I'll start with this one. First step is to create a real serializer that we can use in the benchmark tests.
