### ISSUE TITLE
Complete Restarter wrapper

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#21217]
* fix the FIXMEs
* add documentation on how the new way differs from akka-actor

**Comment by drewhk** [comment]
Especially OneForOne and AllForOne strategies, recursive restarts, etc.

**Comment by rkuhn** [comment]
There is no such thing as AllForOne: the Restarter only wraps a single behavior and applies its decision in the execution context of that child actor—coordination would be extremely awkward. Another consideration is that I have never seen a use-case for AllForOneStrategy in all six years working on and with Akka, in particular not concerning restarts (stopping everything when one part fails is easily implemented by just escalating).

**Comment by drewhk** [comment]
> There is no such thing as AllForOne:

I know. This is why I mentioned re: "add documentation on how the new way differs from akka-actor"

**Comment by rkuhn** [comment]
Ah, sorry, I used the wrong context for interpreting your comment.

**Comment by patriknw** [comment]
Related https://github.com/akka/akka/issues/19855
