### ISSUE TITLE
test mailboxCapacity restriction and optimize the queue

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#21221]
For small capacities CLQ is overkill, array would do just fine.

It would be great to consider options for runtime self-tuning of the queue based on actual usage, perhaps starting out with a 1–2 cache line size, doubling array size when needed until hitting some maximum, then switch to a rope structure; the challenge is to implement a growth mechanism that retains message order without requiring actual locks.

**Comment by drewhk** [comment]
I recall reading about a resizable Array queue that also supports work stealing. I guess it can be modified to remove the work stealing part.

**Comment by rklaehn** [comment]
Why do you want to switch to a rope? As @drewhk said, a lock-free resizable array queue should work, no?

**Comment by rkuhn** [comment]
I don’t want to, I said “perhaps” to indicate some properties that I think might be desirable in order to get to a solution that basically needs no tuning beyond the maximum capacity. Allocating arbitrarily large arrays is not something I’m intuitively comfortable with, but I could be wrong.

@drewhk do you refer to [Stroustroup’s lock-free linearizable vector](http://www.stroustrup.com/lock-free-vector.pdf)?

**Comment by drewhk** [comment]
> Allocating arbitrarily large arrays is not something I’m intuitively comfortable with, but I could be wrong.

I agree with that, but below a threshold resizing might be the best approach.

> @drewhk do you refer to Stroustroup’s lock-free linearizable vector?

No, it is a queue and not by Stroustroup. I will find it.

**Comment by rkuhn** [comment]
Interesting, that will be very useful once someone picks up this ticket!

**Comment by rklaehn** [comment]
@drewhk: It seems to me that the paper describes a single producer/multiple consumer queue. For akka it would need to be a multiple producer/single consumer queue, right? The consumer thread might change, but due to the nature of actors you will never have more than one consumer at *the same time*.

Downsides of a purely array-based approach:

- for large sizes, you will allocate large arrays when growing the buffer
- unless you use locks for that code path, you will occasionally allocate the array twice and then discard one (two threads grow the buffer at the exact same time)

**Comment by drewhk** [comment]
Are you sure? I am pretty certain it is used as a job queue for a threadpool in the project I linked, which would be multi-producer. I admit I haven't read the article.

**Comment by rklaehn** [comment]
I'm not sure. Maybe I just don't understand it.

But this is the *pushBottom* method from the paper. It doesn't seem to have any mechanism to deal with multiple simultaneous calls to pushBottom.

```java
public void pushBottom(Object o) {
  long b = this.bottom;
  long t = this.top;
  CircularArray a = this.activeArray;
  long size = b - t;
  if (size >= a.size()-1) {
    a = a.grow(b, t);
    this.activeArray = a;
  }
  a.put(b, o);
  bottom = b+1;
}
```

The *steal* method on the other hand does
```java
public Object steal() {
  long t = this.top;
  long b = this.bottom;
  CircularArray a = this.activeArray;
  long size = b - t;
  if (size <= 0) return Empty;
  Object o = a.get(t);
  if (! casTop(t, t+1))
    return Abort;
  return o;
}
```

**Comment by rklaehn** [comment]
Not sure how solid it is, but this would seem to be worth a look:
https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpscChunkedArrayQueue.java

**Comment by drewhk** [comment]
Ok, the Chayse-Lev queue is not single-consumer-multi-producer, but there is a twist:
 - only the worker can **enqueue to the end** or **dequeue from the front**
 - but any number of stealers can **steal from the end**

I think that is useful enough! In dispatcher terms this means that a task running on the current thread can only submit tasks to that same thread, but other threads are able to steal them.

**Comment by drewhk** [comment]
Obviously not for a mailbox though...

**Comment by patriknw** [comment]
Not relevant if we do #24149
