### ISSUE TITLE
consider relationship between Dropped and DeadLetter

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#21227]
it might be good to be able to get both of them via a single subscription on the eventstream (and handle them with a handler of a single type)

**Comment by drewhk** [comment]
Dropped as subclass of DeadLetter? (as it is a special case of undelivered)

**Comment by rkuhn** [comment]
Or the other way around: being dead is one possible reason for dropping.

**Comment by drewhk** [comment]
It all depends I think on the interpretation of the word :) dropped as an explicit action, and deadletters as there is no recipient (so it is lost not dropped). I don't mind any of approached, I am not the one to paint this shed ;)

**Comment by patriknw** [comment]
Not relevant if we do #24149
