### ISSUE TITLE
re-evaluate scheduling strategy in new ActorCell

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#21223]
The currently implemented algorithm is somewhat adaptive and extremely simple, but it might well not be the best one—the caveats and corner cases should be assessed and then possibly fixed.

Another consideration is that the Executor is a much better place to implement scheduling policies, because individual actors cannot make informed decisions that optimize the system as a whole.

**Comment by drewhk** [comment]
I would like to move this to the executor. Btw, if we keep the current approach, then the executor can theoretically alter the activation tokens before and after executing the cell (i.e subtracting and adding). I think this can be done relatively safely (have not fully investigated).

For example, if there are only a handful of actors active, then it can be more aggressive as the existing threads might be enough to ensure fairness. But many other strategies can be useful.

**Comment by patriknw** [comment]
Not relevant if we do #24149
