### ISSUE TITLE
audit ActorPath UID usage in ActorSystemImpl

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#21222]
make sure that all refs really get a random UID as soon as needed—for local-only refs that is not really needed since they cannot be queried anyway, but we’ll need to consider this once adding remoting and thereby local–remote bridging

also consider options for widening the UID to a Long in order to make it practically unforgeable

**Comment by drewhk** [comment]
I would still investigate for local as well. I think ChaCha stream cipher is a reasonable option (https://cr.yp.to/chacha/chacha-20080128.pdf especially see the cycles/byte table in page 2). It has 8, 12 and 20 rounds versions with different level of security-performance tradeoff. The PRNG can be periodically refreshed/reseeded from for example SecureRandom if needed (after a long period).

**Comment by patriknw** [comment]
Not relevant if we do #24149
