### ISSUE TITLE
change the signature for handleWebSocketMessagesForProtocol

### ISSUE THREAD

**Issue by Hawstein** [akka/akka#21239]
This will make it more convenient when people create a flow with `Flow.of` and apply it to `handleWebSocketMessagesForProtocol `.

Currently `handleWebSocketMessagesForProtocol` method in javadsl takes a handler of type `Flow[Message, Message, Any]` as parameter, however you get a `Flow[Message, Message, NotUsed]` when you create a flow with `Flow.of`. You have to do some extra work to make it conform to Flow[Message, Message, Any].

**Comment by johanandren** [comment]
This is what you ended up reverting after my comments, right?

**Comment by Hawstein** [comment]
yup，so this issue can be closed now :)
