### ISSUE TITLE
Add Java Query.create(Iterable<Pair<String, String>>)

### ISSUE THREAD

**Issue by checat** [akka/akka#21232]
At the moment, Java Query can be created from a String, from a Map or from the array/varargs of `Pair<String, String>`. But, converting a `Collection<Pair<String, String>>` to array in order to call varargs method is very inconvenient in the Java code, it looks like:

```
        @SuppressWarnings("unchecked")
        final Pair<String, String>[] queryParamsArray = queryParams.toArray(new Pair[queryParams.size()]);
        Query.create(queryParamsArray);
```

It would be trivial to add `Query.create(Iterable<Pair<String, String>>)` which would hide the conversion.

**Comment by ktoso** [comment]
Good idea, would you be able to contribute this fix? 

It's relatively simple to add here: https://github.com/akka/akka/blob/master/akka-http-core/src/main/java/akka/http/javadsl/model/Query.java#L98

**Comment by pawmot** [comment]
I'd be happy to take this one

**Comment by ktoso** [comment]
Great, thanks in advance - marked as in progress

**Comment by ktoso** [comment]
Thanks for the PR @pawmot !
