### ISSUE TITLE
Akka 2.4.9: ByteString.slice fail with out of bound arguments' values

### ISSUE THREAD

**Issue by ysae** [akka/akka#21237]
With 2.4.8 there is no exception occured with any values passed to `slice` method.
But with 2.4.9 we have exceptions in some cases.
```
scala> val sample = ByteString("abcdef")
sample: akka.util.ByteString = ByteString(97, 98, 99, 100, 101, 102)

scala> sample.slice(5, -15)
res1: akka.util.ByteString = ByteString()

scala> sample.slice(-5, -15)
res2: akka.util.ByteString = ByteString()

scala> sample.slice(0, sample.length + 10)
res3: akka.util.ByteString = ByteString(97, 98, 99, 100, 101, 102)

scala> sample.slice(1, sample.length + 10)
java.lang.ArrayIndexOutOfBoundsException: 6
  at akka.util.ByteIterator$ByteArrayIterator.next(ByteIterator.scala:38)
  at akka.util.ByteIterator.foreach(ByteIterator.scala:454)
  ......

scala> sample.slice(-10, 1)
java.lang.ArrayIndexOutOfBoundsException: 6
  at akka.util.ByteIterator$ByteArrayIterator.next(ByteIterator.scala:38)
  at akka.util.ByteIterator.foreach(ByteIterator.scala:454)
  .....
```

**Comment by ktoso** [comment]
Thanks for reporting, very surprised it passed all our scalacheck tests
during the optimisations work hm...

Will fix, or you can give it a shot if you want to.
Thanks

-- 
Konrad Malawski

From: Andy Legkiy <notifications@github.com> <notifications@github.com>
Reply: akka/akka
<reply@reply.github.com>
<reply@reply.github.com>
Date: 20 August 2016 at 21:42:23
To: akka/akka <akka@noreply.github.com> <akka@noreply.github.com>
Subject:  [akka/akka] Akka 2.4.9: ByteString.slice fail with out of bound
arguments' values (#21237)

scala> val sample = ByteString("abcdef")

**Comment by ysae** [comment]
Thank you for quick answer.
But I have no shot at this time.
I just have updated akka in our project, and have seen that our unit-tests failed (specs2).

**Comment by monkey-mas** [comment]
I think I've fixed the issue, will open a PR soon :)

**Comment by drewhk** [comment]
That would be just great!
