### ISSUE TITLE
Reduce stage may emit null

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21242]
If upstream closes without sending any element downstream it will emit the default value, which may be null.

Should probably be fixed like Scan and Fold

**Comment by agolubev** [comment]
In Reduce stage there are two stages - one before first element and one after.

I believe in case of empty stream it will throw exception:
https://github.com/akka/akka/blob/acc5223d387ff9acdef8b520fe91105e8e2b64b1/akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala#L1355

Let me know if you meant some other case.

**Comment by johanandren** [comment]
Man, now I read Reduce wrong twice! Thanks for pointing it out @agolubev
