### ISSUE TITLE
Akka Distributed Data: Document the impact of continuous 

### ISSUE THREAD

**Issue by longmuir** [akka/akka#21249]
We've had at least two customers fall into this misuse, so I figure the documentation could use some clarification here - probably as an extra note/warning in the Delete section. The misuse is performing repeated update and deletes of top-level entities, not realizing that deleted keys cannot be re-used and thus continue to occupy some space until the application runs out of memory. They were creating a custom ReplicatedData type and repeatedly adding/deleting top-level entries instead of using a smaller number of the pre-built data types (like ORMap).

**Comment by patriknw** [comment]
I agree! If you would like to contribute a PR is welcome.
