### ISSUE TITLE
ClusterSingletonProxySettings is not serializable, consider changing to case class.

### ISSUE THREAD

**Issue by hamsterready** [akka/akka#21257]
Hi, 

In my use case I create Props which includes ClusterSingletonProxySettings as an one of the arguments and pass these props for the remote deployment. 

```scala
def otherProps()(implicit system: ActorSystem): Props = {
  ClusterSingletonProxy.props(
    singletonManagerPath = "/user/master",
    settings = ClusterSingletonProxySettings(system).withRole("master")
  )
}

context.actorOf(Props(classOf[X], otherProps()).
  withDeploy(Deploy(scope = RemoteScope(address))), s"agent-$agentId")
```

I end up with 

```
java.io.NotSerializableException: No configured serialization-bindings for class [akka.cluster.singleton.ClusterSingletonProxySettings]
```

See details here: https://github.com/hamsterready/akka-2.4-cluster-singleton-proxy-settings-serialization

I would say that it was unexpected after migrating from 2.3.15 to 2.4.9.

I guess changing from `final class ClusterSingletonProxySettings` to `final case class ClusterSingletonProxySettings` would solve the problem for me.

**Comment by patriknw** [comment]
It sounds like strange usage to remote deploy a singleton proxy. If you need remote deployment, can't you deploy an ordinary actor, which creates the singleton proxy as a child?

**Comment by hamsterready** [comment]
I could do it but then testing interactions between my remotely deployed actor and the proxy singleton (which is irrelevant from the testing perspective) is getting harder and not so natural as with props passing.

**Comment by patriknw** [comment]
It's not as easy as to slap on `Serializable` though. We are moving away from Java serialization everywhere. Security vulnerability, bad performance, not possible to evolve. We would have to write a custom serializer for `ClusterSingletonProxySettings` and that work/maintenance is not motivated when it's not intended to be used in that way. Sorry. You can write your own serializer for it if it's important.

In fact, when looking at the code I see that it's clearly intended for local usage: https://github.com/akka/akka/blob/master/akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonProxy.scala#L108

**Comment by hamsterready** [comment]
M'kay. Thank you for your comments. Instead of passing Props I pass function from `ActorSystem => Props` which is kind of fine. I could also create ref to singleton locally and via overridable def so tests can still be clean.

Thanks,
