### ISSUE TITLE
Please clean up the output of the akka-cluster utility

### ISSUE THREAD

**Issue by ewegene** [akka/akka#21250]
There's two issues with the output of the akka-cluster utility:
1. It prints out messy json which makes it hard to read (defeating the purpose of using json)
2. It prints out non-json information making it so it can't simply be piped to a json tidy tool

For example please compare this (un-tidied information)

<pre>
Querying cluster status
{ 
  "self-address": "akka.tcp://ClusterSystem@10.11.12.26:12345",
  "members": [
    { 
      "address": "akka.tcp://ClusterSystem@10.11.12.26:12345",
      "status": "Joining",
      "roles": [

      ]
    },
    { 
      "address": "akka.tcp://ClusterSystem@10.11.12.27:12345",
      "status": "Up",
      "roles": [

      ]
    },
    { 
      "address": "akka.tcp://ClusterSystem@10.11.12.28:12345",
      "status": "Exiting",
      "roles": [

      ]
    },
    { 
      "address": "akka.tcp://ClusterSystem@10.11.12.29:12345",
      "status": "Up",
      "roles": [

      ]
    },
    { 
      "address": "akka.tcp://ClusterSystem@10.11.12.30:12345",
      "status": "Up",
      "roles": [

      ]
    }
  ],
  "unreachable": [
    { 
      "node": "akka.tcp://ClusterSystem@10.11.12.25:12345",
      "observed-by": [
        "akka.tcp://ClusterSystem@10.11.12.27:12345",
        "akka.tcp://ClusterSystem@10.11.12.30:12345"
      ]
    },
{
      "node": "akka.tcp://ClusterSystem@10.11.12.28:12345",
      "observed-by": [
        "akka.tcp://ClusterSystem@10.11.12.25:12345",
        "akka.tcp://ClusterSystem@10.11.12.27:12345",
        "akka.tcp://ClusterSystem@10.11.12.29:12345"
      ]
    },
{
      "node": "akka.tcp://ClusterSystem@10.11.12.29:12345",
      "observed-by": [
        "akka.tcp://ClusterSystem@10.11.12.30:12345"
      ]
    },
{
      "node": "akka.tcp://ClusterSystem@10.11.12.30:12345",
      "observed-by": [
        "akka.tcp://ClusterSystem@10.11.12.25:12345"
      ]
    }
  ]
}
</pre>

To this (tidied with `python -m json.tool`):

<pre>
Querying cluster status
{
    "members": [
        {
            "address": "akka.tcp://ClusterSystem@10.11.12.26:12345", 
            "roles": [], 
            "status": "Joining"
        }, 
        {
            "address": "akka.tcp://ClusterSystem@10.11.12.27:12345", 
            "roles": [], 
            "status": "Up"
        }, 
        {
            "address": "akka.tcp://ClusterSystem@10.11.12.28:12345", 
            "roles": [], 
            "status": "Exiting"
        }, 
        {
            "address": "akka.tcp://ClusterSystem@10.11.12.29:12345", 
            "roles": [], 
            "status": "Up"
        }, 
        {
            "address": "akka.tcp://ClusterSystem@10.11.12.30:12345", 
            "roles": [], 
            "status": "Up"
        }
    ], 
    "self-address": "akka.tcp://ClusterSystem@10.11.12.26:12345", 
    "unreachable": [
        {
            "node": "akka.tcp://ClusterSystem@10.11.12.25:12345", 
            "observed-by": [
                "akka.tcp://ClusterSystem@10.11.12.27:12345", 
                "akka.tcp://ClusterSystem@10.11.12.30:12345"
            ]
        }, 
        {
            "node": "akka.tcp://ClusterSystem@10.11.12.28:12345", 
            "observed-by": [
                "akka.tcp://ClusterSystem@10.11.12.25:12345", 
                "akka.tcp://ClusterSystem@10.11.12.27:12345", 
                "akka.tcp://ClusterSystem@10.11.12.29:12345"
            ]
        }, 
        {
            "node": "akka.tcp://ClusterSystem@10.11.12.29:12345", 
            "observed-by": [
                "akka.tcp://ClusterSystem@10.11.12.30:12345"
            ]
        }, 
        {
            "node": "akka.tcp://ClusterSystem@10.11.12.30:12345", 
            "observed-by": [
                "akka.tcp://ClusterSystem@10.11.12.25:12345"
            ]
        }
    ]
}
</pre>

**Comment by patriknw** [comment]
I agree. The reason we are not using a nice json library is to avoid additional dependencies. Fixing the formatting is welcome.

I think the cluster-status query covers all information that the other non-json queries have so I don't think it's needed to mix those two types of queries.

@hveiga has started on a new HTTP based management api, see #21172

**Comment by richard-imaoka** [comment]
Hi, as the JMX cluster management tool is deprecated, and [akka/akka-cluster-management](https://github.com/akka/akka-cluster-management) is preferred, should this still be fixed? (I believe this is specific to the [JMX tool](https://github.com/akka/akka/blob/554d119446ad03a49890c33d3ce91036aface88c/akka-cluster/src/main/scala/akka/cluster/ClusterJmx.scala#L143#L179))

If are we still going to fix this, I will try to work on this.

**Comment by patriknw** [comment]
It's not deprecated yet, so it will stay the full 2.5 release cycle. Therefore it's probably worth fixing if you have ideas of how to do it.

Created an related ticket for the actual deprecation https://github.com/akka/akka/issues/22211

**Comment by richard-imaoka** [comment]
I see, thank you. Thinking to start working on this in a couple of days.

**Comment by patriknw** [comment]
Thanks, by the way, I was thinking of another issue. This is indeed worth fixing since it's the JMX not only the script. I think JMX will not be deprecated.
