### ISSUE TITLE
Change offset type in `eventsByTag` query

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21283]
Perhaps we can change the api of the persistence query `eventsByTag` api to use something like this: https://github.com/lagom/lagom/pull/148.

An `Offset` type with a few concrete implementations, such as `Long` sequence numbers, `Long` timestamp, time `UUID`.

 I have previously not wanted to do that because I only saw `Any` as the possible type, but with a few predefined Offset types it makes more sense.

**Comment by richard-imaoka** [comment]
Hi, I was thinking to submit a PR for this ... does LevelDBJournal need to implement UUID Offset? Or only Long would be sufficient for now?

**Comment by patriknw** [comment]
That would be great, thanks.
Leveldb plugin has a global seq nr series (i think), and then Long should be enough to define a unique position.
