### ISSUE TITLE
Inconsistency with parsing `Authorization` header with empty values

### ISSUE THREAD

**Issue by briantopping** [akka/akka#21281]
Hi guys, back from C++/Embedded land for a bit. :)

I found a problem with [this test](https://github.com/akka/akka/blob/09c656c21dd14c1d9fc2e212f50f268c6de13232/akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala#L141-L142). As the test stands, it works fine, but does not test for a key with an empty value. 

My first stop was to check [RFC 2617](http://www.ietf.org/rfc/rfc2617.txt) to see if I was misunderstanding something, in part 1.2 it seems to indicate that an `auth-param` is `token "=" ( token | quoted-string )`. This seems pretty unambiguous as either a quoted string (i.e. `key=""` or an unquoted token (`key="something"`), but not as a KVP that has an empty, unquoted value (`key=`). 

So I started playing with the test and seeing what I could come up with. I first tried:

```
      """Authorization: Fancy yes=no,foo="",nonce="4\\2"""" =!=
        Authorization(GenericHttpCredentials("Fancy", Map("yes" → "no", "foo" → "", "nonce" → """4\2""")))
```

This gives an error that the rendering of the object form is `'Authorization: Fancy yes=no,foo=,nonce="4\\2"'`. 

Changing the rendered form in the test to this value yields a different error:

```
Input `Authorization: Fancy yes=no,foo=,nonce="4\\2"` failed to parse:
Illegal HTTP header 'Authorization': Invalid input ',', expected OWS or word (line 1, column 18)
Fancy yes=no,foo=,nonce="4\\2"
```

So it seems that the RFC in this case _is_ actually ambiguous.

**Comment by 2beaucoup** [comment]
Keep in mind that parsing/rendering doesn't have to necessarily be symmetric. See the usages of `renderedTo` in the spec.

**Comment by briantopping** [comment]
@2beaucoup thanks for the feedback. I guess another angle of looking at this is "how do I send a null-valued property?" That does not seem possible with the current code. I cannot send either an empty quoted string nor a key with empty property.

**Comment by johanandren** [comment]
In RFC 2616 `quoted-string` is defined as `( <"> *(qdtext | quoted-pair ) <"> )` so I think you are right that empty quoted string should be allowed.

**Comment by johanandren** [comment]
Allowing or not allowing `token` to be empty seems (even) more vague to me.

**Comment by briantopping** [comment]
@johanandren Agreed. There's also the case of other tooling out there that have taken the however ambiguous spec and implemented it differently. I presume this is where the "relaxed" flag comes from elsewhere in the parser. It may be this code should leverage that flag for an empty unquoted token? WDYT?

**Comment by briantopping** [comment]
Something I forgot in making the previous comment is the `params` are `Map[String, String]`. If it's the case that we want to be able to handle `token`s and differentiate between an empty string or a `null`/`None`, this may be inadequate. 

That said, if `params` was a `Map[String, Option[Any]` (or `GenericHttpCredential` was a parameterized type replacing `Any` with a user specified type), how much impact would there be in the field? Does it become a 2.5 series change? Is it even worth going down that rabbit hole?

**Comment by johanandren** [comment]
Yeah, that signature cannot change as far as I can see, OTOH I cannot really see the use case for differentiating between empty-string and empty-token here.

**Comment by johanandren** [comment]
@ktoso you have an opinion on this?

**Comment by 2beaucoup** [comment]
https://tools.ietf.org/html/rfc7235#section-4.2:
```
Authorization = credentials
credentials   = auth-scheme [ 1*SP ( token68 / [ ( "," / auth-param )
    *( OWS "," [ OWS auth-param ] ) ] ) ]
auth-param    = token BWS "=" BWS ( token / quoted-string )
```
https://tools.ietf.org/html/rfc7230#section-3.2.6:
```
token         = 1*tchar
quoted-string = DQUOTE *( qdtext / quoted-pair ) DQUOTE
```

So the `auth-param` value is defined as either a non-empty token or a (possibly empty) quoted string.

**Comment by jrudolph** [comment]
To me it seems as if this were a rendering issue i.e. we should make sure that an empty param value is rendered as an empty quoted string.

**Comment by jrudolph** [comment]
See #21384

**Comment by 2beaucoup** [comment]
This can be closed.

**Comment by ktoso** [comment]
Thanks for noticing!
