### ISSUE TITLE
Add more rel=canonical links to old 1.0 streams docs etc

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21287]
The script is "good enough" I think:

```
for FILE in $(find . -name *.html | grep 1.0) # do it for all though
do 
  sed -i  "/<head>/a    <link rel=\"canonical\" href=\"http://akka.io/docs/akka/current/$(echo $FILE | cut -d"/" -f3-)\" />" $FILE
done
```

It may sometimes point to URLs which don't exist... so it may be a good idea to if / curl before it?

This should be run in `~/www/docs/akka-stream-and-http-experimental`.

This should help getting 1.0 and friends out of google search results

**Comment by ktoso** [comment]
I could not complete this as the files are owned by `ubuntu` whereas I only have access as `akkarepo`.

I think @johanandren may know how to get ubuntu access there.
I would chown all things to `akka-repo`, and then run this.

**Comment by johanandren** [comment]
Hmm. wonder why they are owned by the admin user... Maybe I did something wrong when moving to a larger disk a couple of weeks ago.

I have chowned them now though.

**Comment by ktoso** [comment]
Great, thanks - applied to all old streams docs.
Hope this will help google do the right thing then.

`view-source:http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M2/scala/http/index.html`
