### ISSUE TITLE
UnexpectedDisconnectException using akka-http client against python flask server

### ISSUE THREAD

**Issue by yakticus** [akka/akka#21292]
All the details including reproducing the error are here:
https://github.com/yakticus/akka-UnexpectedDisconnectException

**Comment by 2beaucoup** [comment]
Duplicate of #20570?

**Comment by ktoso** [comment]
Yeah it could be, not closing for now, let's use the reproducer to attempt a fix early next week

**Comment by drewhk** [comment]
Yes, it looks like a duplicate to me. I opt for closing this one in favor of the other, otherwise it will become a mess to track things.

**Comment by ktoso** [comment]
Okey, I'll post the reproducer by @yakticus  in the other ticket.
