### ISSUE TITLE
Provide zipWithIndex, it's common enough that we may provide it

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21290]
Basically `zip(Source.iterator(Longs))`
It's mostly for one-liner-nicennes.

**Comment by ktoso** [comment]
Yeah, mostly for one-liner-nicennes.

**Comment by drewhk** [comment]
Ok I filed one too: https://github.com/akka/akka/issues/21291 Closing that one

**Comment by drewhk** [comment]
Zip is slower than a custom stage though. StatefulMapConcat or Scan might be the fastest without needing a new stage.

**Comment by ktoso** [comment]
True 👍

**Comment by naferx** [comment]
I would like to work on it

**Comment by ktoso** [comment]
Great, thanks a lot! Marked as in progress

**Comment by ktoso** [comment]
Thanks fo closing, please do assign the right milestone when doing so next time :)
