### ISSUE TITLE
leaving or downing information in registerOnMemberRemoved

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21298]
When shutting down the JVM when the cluster member is removed it can be needed to use different exit codes depending on if it was a graceful leaving or downing. Based on the exit code the JVM should be restarted or not.

In code examples like http://doc.akka.io/docs/akka/2.4/scala/cluster-usage.html#How_To_Cleanup_when_Member_is_Removed we can't do that because that information is not available in the `registerOnMemberRemoved`.

One suggestion is to add two more of those convenience methods. `registerOnMemberRemovedAfterLeaving` and `registerOnMemberRemovedAfterDown`.

**Comment by Chuwiey** [comment]
#in-progress

**Comment by patriknw** [comment]
I think we should not complicate this more. https://github.com/akka/akka/issues/21537 adds better options for shutdown sequences already.
