### ISSUE TITLE
Confusion with `discardOld` parameter name in `context.become()`

### ISSUE THREAD

**Issue by tudorzgureanu** [akka/akka#21307]
Method signature: `def become(behavior: Actor.Receive, discardOld: Boolean): Unit`

Having `discardOld` might be a bit misleading, because it may be taken as discard the whole behavior stack, which at some point during a discussion a few people and I thought it will.

What I propose? Changing slightly the parameter name to `discardLast` although `discardCurrent`, `replaceCurrent`, `discardTop` may work as well.  Any better ideas are welcome. I reckon for beginners it will be even more useful.

P.S. I'm happy to come with a PR.

**Comment by johanandren** [comment]
Changing it would not be source compatible as the parameter names are part of the public API in Scala, so I don't think we could change until Akka 3.0 if we wanted.

That aside, I actually never heard anyone think it would discard the entire stack before, it's usually an either-or situation where you always discard or you never - mixing the two in the same actor is probably error prone and confusing (almost an anti pattern I'd say).

**Comment by ktoso** [comment]
Note: The change could be made binary compatible, we have `@deprecatedName('bazinga) lol: String` for that.

I don't have strong feelings about the name, perhaps @patriknw or @drewhk have.

**Comment by tudorzgureanu** [comment]
@johanandren It's seems then it's not just about naming. Is there any use cases of mixing the two in the same actor? If this seems to be more like an anti-pattern maybe it's worth rethinking the way it currently works and probably restrict the user to choose only one of them?  (Although I'm not sure it would be the best solution to be honest)
@ktoso Yeah, you are totally right, in case the team decides a parameter name adjustment, it should be marked as `@deprecatedName`.

**Comment by patriknw** [comment]
The potential ambiguity comes from that it's not clear if `old` refers to the whole stack or the top element in the stack. In my book `last` doesn't define that reference any better. Additionally, if we have the mental picture of a `Stack` it should be called `head` or `top`.

Hmm, don't think it's worth changing. It's clear if you read the documentation.
