### ISSUE TITLE
unclear tcp stream documentation

### ISSUE THREAD

**Issue by BertRobben** [akka/akka#21308]
I think the tcp stream documentation is lacking some basic explanations. Although I'm very familiar with the java socket API, it took me quite a while to understand how the API is supposed to work and to set up a simple working TCP stream based example. The main reason is IMHO that some basic concepts are not explained in the documentation. They are probably explained in other places (e.g. presentations), but as a user I would like to get started quickly by only reading the documentation.

Concretely, I'd like to add a short paragraph that shows how the flows are related to the underlying socket's input and output streams. Also, I'd like to make it very explicit that the stream implementation does not add any additional bytes to the data that is sent over the socket.

I can imagine that these can be derived from what is already there, but if you're new to streams and don't have the time to carefully read everything top-to-bottom then this is far from obvious.
 
PS: I'm happy to make a PR

**Comment by johanandren** [comment]
I may have misread your description, but note that the underlying implementation is not using the old Java Input/OutputStream APIs though, it is based on the Java NIO APIs.

I think that the Akka Streams TCP docs should be allowed to expect people to have read up on and have basic Akka Streams API knowledge, or else we'd have to repeat the entire streams docs on every subtopic in the docs.

That being said, improvements are always welcome so go ahead and PR and we can discuss the actual changes in the PR!

**Comment by johanandren** [comment]
Maybe a "Make sure you have understood Akka Streams basics first [link-to-streams-introduction]" would be enough?

**Comment by BertRobben** [comment]
Hi Johan,

I was thinking on some specific comments on TCP streams, so they are not in
the streams introduction. Unfortunately however, I cannot provide a pull
request. I deeply regret it, but the policy of the company I'm working for
explicitly forbids it.

I'm sorry,

Bert

**Comment by richard-imaoka** [comment]
I raised a PR adding reference to the Streams and HTTP sections from the TCP stream doc.

@BertRobben is it still possible to tell us what comments you wanted to added? I would like to reflect your comments in the PR if possible.

Thanks

**Comment by BertRobben** [comment]
Sure, I'm happy to do so.

* show in a diagram how the flow (input and output) is related to the socket's incoming incoming and outgoing connection. This for both the tcp incoming and tcp outgoing connection. (in my initial expectation, I was thinking of the stream of data that goes from one side to the other as being one stream. If the other side replies, you'd get another stream. Of course,  this does not match with reality, but I was put on the wrong track for a while before I understood this fully).
* explicitly mention that the stream does NOT add any bytes on top of the payload that is flowing into the stream. Consequences of this are that you can connect to any existing socket; the other side does not need to be an akka tcp stream and that flow control is done using TCP built-in flow control and not by sending additional messages. An obvious consequence of this is that the ByteString's that are sent through the outgoing channel do not match on the ByteString's that are coming out on the other end.

**Comment by richard-imaoka** [comment]
Thank you @BertRobben. The comments are more detailed than what I was thinking, so let me dig in a bit more by myself. Especially to illustrate it in a diagram, I'll need to understand the stuff better.

**Comment by richard-imaoka** [comment]
Hi @johanandren could you tell me how diagrams under the [akka-docs/rst/images](https://github.com/akka/akka/tree/master/akka-docs/rst/images) are created? I want to create diagrams like ones on the [stream composition page](http://doc.akka.io/docs/akka/2.4/scala/stream/stream-composition.html). Currently I only have hand-drawn ones which obviously I cannot upload for poor quality :|

**Comment by johanandren** [comment]
@richard-imaoka We don't have a single way, I use omnigraffle (commercial) and export to png and svg. Endre has been using inkscape (free). Not sure what the other guys have been using. I think the most important part is to be able to export both png and svg.

**Comment by richard-imaoka** [comment]
Ok sure, let me create png and svg with my favorite tools. If the quality is not sufficient we can revise them.
