### ISSUE TITLE
mapAsync doesn't fail stream as soon as possible

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21318]
When the Future of the mapAsync fails it's expected that the stream fails immediately, but it looks like the parallelism setting influence when the error is propagated downstreams.

with par=1 it fail the stream after first failed mapAsync element, with par=2 it fails after second

**Comment by drewhk** [comment]
This is unfortunately contradicted by test cases that test this behavior, and the code on the failure path is relatively straightforward. What are the steps to reproduce?
