### ISSUE TITLE
Clarify getStageActor scaladoc

### ISSUE THREAD

**Issue by durban** [akka/akka#21311]
The [scaladoc comment](https://github.com/akka/akka/blob/fa614f0325b786998fb6adbd31c4ae7692613515/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L907) of `GraphStageLogic#getStageActor` is somewhat confusing (to me). It says "_This method **must not** (...) be called after the GraphStageLogic constructor has finished running ..._". While the [documentation](http://doc.akka.io/docs/akka/2.4.9/scala/stream/stream-customize.html#Integration_with_actors) states that "_they cannot be accessed from the constructor of the GraphStageLogic ..._".

It seems to me, that the docstring should say "_This method **must** (...) be called after the GraphStageLogic constructor has finished running ..._". (Although, I realize there could be a misunderstanding on my part due to english not being my first language.)

**Comment by ktoso** [comment]
Great catch, you're right about that. It should be **must**.
Would you submit a PR fixing this up?

Thanks a lot in advance

**Comment by durban** [comment]
See #21323.
