### ISSUE TITLE
Missing API: expectNextPF doesn't take a timeout

### ISSUE THREAD

**Issue by joearasin** [akka/akka#21314]
Per discussion in Gitter with @ktoso, expectNextPF should take a timeout parameter.

**Comment by patriknw** [comment]
If you would like to contribute @joearasin a pull request is welcome.

**Comment by manonthegithub** [comment]
I just trying to implement this, but I've got problem. If I try to add overloading function like this:
```scala
def expectNextPF[T](f: PartialFunction[Any, T]): T = {
    expectEventPF {
        case OnNext(n) if f.isDefinedAt(n) ⇒ f(n)
      }
}

def expectNextPF[T](max: Duration, f: PartialFunction[Any, T]): T = {
    expectEventPF {
        case OnNext(n) if f.isDefinedAt(n) ⇒ f(n)
      }
}
```

 I get compiler Error:
[error] /Users/Kirill/IdeaProjects/akka/akka-stream-testkit/src/test/scala/akka/stream/testkit/TestPublisherSubscriberSpec.scala:57: missing parameter type for expanded function
[error] The argument types of an anonymous function must be fully known. (SLS 8.5)
[error] Expected type was: ?
[error]       an[AssertionError] should be thrownBy downstream.expectNextPF[String] { case e: String ⇒ e }

I think it is bug in compiler. When expectNextPf is overloaded and is executed with explicit type parameter set ([String] for example), this error occurs. If I remove overloaded version or if you execute expectNextPF without explicit type parameter - everything is fine. But someone who uses testkit could have used expectNextPf with explicit type parameter and it will crash his build.
What could you suggest? Maybe for example not overload, but create new function with other name like expectNextPFWithTimeLimit?

**Comment by Chuwiey** [comment]
#in-progress
