### ISSUE TITLE
Make the new typed "actorcell" a queue node.

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21324]
Since we will now tightly control the dispatcher (closed world) we can know what kind of queues it might be added to and simply fuse the queue node role with the actor cell role avoiding any allocation when it needs to be queued for the thread-pool. This change, together with small mailboxes being array backed and no envelope can make many situations completely allocation free. 

/cc @rkuhn @viktorklang

**Comment by rkuhn** [comment]
Yes, that would make sense once we have researched the options and decided upon some scheduling strategies—an ordered queue as represented by linked nodes already makes some assumptions that I am not sure are 100% justified.

**Comment by drewhk** [comment]
> an ordered queue as represented by linked nodes already makes some assumptions that I am not sure are 100% justified.

I agree. I actually wanted to comment that even if not for queues, linked structures involving the cell can be still used in various ways. To give a slightly stupid, but hopefully illuminating example, we can have a linked (likely doubly linked) circle of actorcells where worker threads go along the circle to "hunt" for cells they can execute. Of course this example is a bit naive but it shows how you can schedule actors without a queue.

**Comment by rkuhn** [comment]
Good point, I hadn’t considered that example; what I had in mind is an array-based exchanger between work producers and threads, which would not benefit from built-in link support.

**Comment by drewhk** [comment]
yeah, exchanger is another great option. I was also thinking in introducing links for other stuff, like tracking some "friend" actor so when you take something off from the exchanger, with a certain likelyhood you follow the "friend" link to get a new cell instead of going to the exchanger. Again, this is not a real proposal just an example of the stuff we can hopefully do.

**Comment by patriknw** [comment]
Not relevant if we do #24149
