### ISSUE TITLE
replace artery protocol name with akka

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21338]
Instead of `artery://sys@host:port` we have decided to use `akka://sys@host:port`.

**Comment by hepin1989** [comment]
not `akka.artery`? so it will be the default transport and replace the `akka.tcp` one?

**Comment by ktoso** [comment]
> not akka.artery? 

no, that was a codename as we said in each of the releases.

> so it will be the default transport and replace the akka.tcp one?

Yeah, eventually.

**Comment by patriknw** [comment]
We want to make it clear that it has nothing to do with the old pluggable transport design. This is completely new remoting.
