### ISSUE TITLE
Enable "misc" protobuf serializers by default in artery

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21339]
Relates to https://github.com/akka/akka/issues/21202

We have a number of misc serializers, for Some/None, Identity etc.
However they're not enabled by default as that would break wire compatibility in 2.4.x.
However, if someone is using Artery as transport... we *know* that those serializers are available on both sides, since it's a new transport so.. it's a relatively new version of akka ;)

In other words, if transport is artery then enable misc serializers

**Comment by drewhk** [comment]
... and eventually disable Java serialization as a default in tests. This will ensure that we have everything serializable.

**Comment by patriknw** [comment]
for test messages that we on purpose don't care about we can have a special marker interface that is bound to Java serializer

**Comment by drewhk** [comment]
True, I forgot about that.

**Comment by patriknw** [comment]
Related to https://github.com/akka/akka/issues/20824
