### ISSUE TITLE
add a takeWhileInclusive stage to streams

### ISSUE THREAD

**Issue by kciesielski** [akka/akka#21330]
Sometimes there's need to read from a flow/source while a condition is true and then complete but still emit the last element, which doesn't match the condition. An example can be found here: https://softwaremill.com/replacing-akka-actors-with-akka-streams/

I thought of adding a sort of `takeWhileInclusive()` stage. I'm willing to write a PR but I'd like to know whether such stage will be accepted and whether it should go to core, akka-contrib or some other module.

**Comment by johanandren** [comment]
It is already being worked on in  PR #20374, not far from being completed.

**Comment by kciesielski** [comment]
Great, thanks.

**Comment by johanandren** [comment]
I think we can keep this ticket open because there is no ticket to track the PR afair.

**Comment by kciesielski** [comment]
👍
