### ISSUE TITLE
Serialization woes

### ISSUE THREAD

**Issue by fedenusy** [akka/akka#21346]
Kryo serialization isn't working on my project. I posted a detailed issue here: https://github.com/romix/akka-kryo-serialization/issues/95

Today I tried dropping akka-kryo-serialization in favor of twitter-chill. Once again, I followed the setup instructions closely -- and I still keep seeing the same serialization warnings.

I suspect there's an issue where the serializer and/or serialization bindings don't get registered. Or perhaps it's an issue when using serialization together with DistributedPubSub.

Unfortunately there's no errors or relevant debug statements in the Akka logs. All I see are the same old serialization warnings.

Any pointers on best ways to debug this issue?

**Comment by johanandren** [comment]
You could do it programatically from a test, as described here: http://doc.akka.io/docs/akka/2.4.9/scala/serialization.html#Programmatic and step through the logic that chooses the serializer to see if that helps you figure out why it chooses the default serializer.

**Comment by patriknw** [comment]
Please use [akka-user](https://groups.google.com/forum/#!forum/akka-user) or gitter [akka/akka](https://gitter.im/akka/akka) for questions. We use the issue tracker for issues and feature requests. Thanks.
