### ISSUE TITLE
Java DSL cannot create streaming marshaller / unmarshaller

### ISSUE THREAD

**Issue by jypma** [akka/akka#21340]
The Java `Marshaller` and `Unmarshaller` classes are missing a few of the scala variants that make it impossible to write streaming marshallers and unmarshallers in Java.

I've already written the needed additions for [Marshaller](https://github.com/Tradeshift/ts-reaktive/blob/a25a2c582462a4ea7dce59ded3cee21c9d8855c6/ts-reaktive-akka/src/main/scala/com/tradeshift/reaktive/akka/AsyncMarshallers.scala) and [Unmarshaller](https://github.com/Tradeshift/ts-reaktive/blob/a25a2c582462a4ea7dce59ded3cee21c9d8855c6/ts-reaktive-akka/src/main/scala/com/tradeshift/reaktive/akka/AsyncUnmarshallers.scala).

Shall I create a PR?

**Comment by ktoso** [comment]
Hm, what specifically do you mean saying "streaming marshaller / unmarshaller"?
But yeah, please PR! :)

**Comment by jypma** [comment]
PR created. Turns out the "streaming marshaller" can in fact be written in plain Java. That leaves just the unmarshaller side, plus a few random other fixes.

**Comment by jypma** [comment]
@ktoso tests passed on the PR (https://github.com/akka/akka/pull/21341). How do you feel about the additions?

**Comment by ktoso** [comment]
Had a crazy week, back to reviewing.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27
If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
