### ISSUE TITLE
Akka streams drops messages in 2.4.9 

### ISSUE THREAD

**Issue by wsargent** [akka/akka#21345]
There's a couple of failing specs in Play master which only started happening on the upgrade to 2.4.9:

https://github.com/playframework/playframework/issues/6504

The relevant spec file is 

https://github.com/playframework/playframework/blob/master/framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala

But it appears to be the result of the custom Akka Streams Graph Stage on top of Netty. 

Using the latest 2.4-SNAPSHOT build yielded the same results.

To upgrade to different Akka versions, go to 

https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala#L9

and change the version from there.  You will need to enable the test and run from

```
cd framework
sbt "testOnly play.it.http.websocket.NettyPingWebSocketOnlySpec"
```

**Comment by patriknw** [comment]
Thanks @wsargent. We will look into this asap, before releasing 2.4.10

**Comment by drewhk** [comment]
I didn't find "NettyPingWebsocketOnlySpec" only "NettyWebsocketSpec"

**Comment by schmitch** [comment]
that's the correct one. And the failing tests are in the `PingWebSocketSpec` trait

**Comment by drewhk** [comment]
Ah, I see

**Comment by schmitch** [comment]
but if I add fuzzing-mode  it fails on 2.4.8, too.

**Comment by drewhk** [comment]
ok, interestingly it does not fail for me on 2.4.9 :) So it is a race.

**Comment by schmitch** [comment]
Actually it only fails "some" times. Pretty rare on 2.4.8 with fuzzing mode.

**Comment by drewhk** [comment]
Yeah, fuzzing mode just blindly randomizes things not too intelligently.

**Comment by patriknw** [comment]
Then we are pretty sure that this is not a bug (at least not a regression) in Akka? Would it be fair to ask you for a minimized reproducer if you still think it's something wrong in Akka and not in your stage?

**Comment by drewhk** [comment]
I tried to dig around in the code but I got lost fairly quickly (utility methods are everywhere and I am not familiar with Play). If you can minimize it somehow we can take a look, but it is currently too much to look at for me. Can be a race between cancellation and completion at both sides of your flow?

**Comment by schmitch** [comment]
Actually the "Main Flow" is inside `play.core.server.common.WebSocketFlowHandler.messageFlowToFrameProcessor` I guess that handle's the close related stuff. Everything else is just:
- grab the handler flow from the Router -> Request Handler 
- apply `WebSocketFlowHandler.messageFlowToFrameProcessor.messageFlowToFrameProcessor` 
- send it to netty-reactive-streams and create a WebSocketResponse: [DefaultWebSocketHttpResponse.java#L15](https://github.com/playframework/netty-reactive-streams/blob/master/netty-reactive-streams-http/src/main/java/com/typesafe/netty/http/DefaultWebSocketHttpResponse.java#L15)

**Comment by schmitch** [comment]
I may wonder if that all depends on netty-reactive-streams failure that happen on travis:
https://travis-ci.org/playframework/netty-reactive-streams/builds/156166234#L483
also netty-reactive-streams with fuzzy mode fails 10 tests, too. but they aren't related to websockets.

**Comment by schmitch** [comment]
@drewhk I found the error but I wanted to check if this may still be a akka error.

The error happens here:
https://github.com/playframework/playframework/blob/d6c2673d91d85fd37de424951ee5ad9f4f4cce98/framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala#L185
With completionStage() Netty will Push the connection Close() before the Flush method so that basically the frame will still get onto the wire but the client looses the connection before.

However changing to to use `complete(remoteOut)` and `cancel(remoteIn)` (the last two remaining ports). Will actually make it work. Even on fuzzing-mode. 
Is completionStage() to fast or do I have some wrong assumptions?

**Comment by drewhk** [comment]
You mean `completeStage()`? That should work fine as all it does is just calling complete and cancel on all remaining ports anyway.

**Comment by drewhk** [comment]
To elaborate, `completeStage()` does nothing else than just calls `cancel()` and `complete()` on the remaining ports. I.e. the only thing that you likely changed is the order of these calls. These events by nature are concurrent and the interpreter can execute them in any order, i.e. the cancel or the complete can arrive to a common flow in any order. Fuzzing mode cannot reorder every event, I think in this case it does not expose the race. All in all, this does not look like a bug from the Akka side.

**Comment by viktorklang** [comment]
Vote to close?
