### ISSUE TITLE
Remoting test 10000 messages per second 

### ISSUE THREAD

**Issue by ab2971082** [akka/akka#21358]
I have a test with remoting and the result is 10000 messages per second, why it is so slow ？

**Comment by ab2971082** [comment]
I have a test with remoting and the result is 10000 messages per second, why it is so slow ？

**Comment by patriknw** [comment]
Please use [akka-user](https://groups.google.com/forum/#!forum/akka-user) or gitter [akka/akka](https://gitter.im/akka/akka) for questions. We use the issue tracker for issues and feature requests. Thanks.

You should try the new remoting if you are interested in better throughput. See  https://groups.google.com/d/msg/akka-user/JLbLrLh3vIg/twhLMRg7CQAJ
