### ISSUE TITLE
HTTP server logs entire request on failure

### ISSUE THREAD

**Issue by agboom** [akka/akka#21354]
When an Http Request results in an internal server error, the entire request is logged, including body, headers and all. This means that credentials/tokens for authentication (or other sensitive data) is logged on error level.

```
ERROR [default-akka.actor.default-dispatcher-5746] (akka.actor.ActorSystemImpl): Error during processing of request HttpRequest(
  HttpMethod(POST), 
  http://localhost:9000,
  List(Host: localhost, User-Agent: <redacted>, Cache-Control: no-cache, Authorization: <redacted>, Accept: */*, DNT: 1, Accept-Encoding: gzip, deflate, Accept-Language: en-US, en;q=0.8, nl;q=0.6, X-Forwarded-For: <redacted>, Timeout-Access: <function1>),
  HttpEntity.Strict(... (4847 bytes total)),
  HttpProtocol(HTTP/1.1)
)
```

This can't be turned off by configuring a different log level. One may be able to work around it using an ExceptionHandler (haven't tested it). A relevant question might be whether it is safe to even log the request by default or if it would be safer to make this an "opt-in" feature, for example by using an ExceptionHandler.

**Comment by ktoso** [comment]
This issue was moved to akka/akka-http#16
