### ISSUE TITLE
LoggingReceive doesn't send MDC

### ISSUE THREAD

**Issue by dskrvk** [akka/akka#21361]
In [`LoggingReceive#isDefinedAt`](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-actor/src/main/scala/akka/event/LoggingReceive.scala#L56) the `Debug` message is created without the MDC argument. Is this intentional?

In my code I'm using a `DiagnosticLoggingAdapter` and would like to have the mdc info for incoming messages logged for debugging purposes.

**Comment by patriknw** [comment]
@dskrvk sound good to include the MDC, if available. I think it can do that if `context.isInstanceOf[DiagnosticActorLogging]` or do you have any other idea of from where it should get the MDC? If you would like to contribute it would be great if you create a pull request fixing this.
