### ISSUE TITLE
FAILED akka.stream.io.TcpSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21377]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4157/consoleFull

```
[info] - must not shut down connections after the connection stream cancelled *** FAILED *** (3 seconds, 49 milliseconds)
[info]   akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4256/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1815/consoleFull

**Comment by johanandren** [comment]
Oh, my fix is still not merged?
