### ISSUE TITLE
Rewrite Http client-side PoolFlow / PoolConductor with single GraphStage

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21370]
PoolFlow, PoolConductor, and PoolSlot do a sophisticated dance to send state information around. This could probably be much simplified by having just two GraphStages:

 * the existing PoolSlot
 * another GraphStage which contains all of the remaining logic currently split over several graph elements. This GraphStage could either directly have the shape of a `Flow[HttpRequest, HttpResponse]` and creates the slots internally, or could have the shape of a flow plus additional holes for all of the slots to be filled from the outside.

**Comment by 2beaucoup** [comment]
Would it be safe to share the handlers  between `PoolFlow` and the subflows? The handlers could then be created by the `PoolFlow` and then be injected into the subflows and could directly update the state without an additional state channel.

**Comment by jrudolph** [comment]
You mean to rely on all of the stages being run in the same context so that it would be safe to manipulate state of another stage? I don't think that's a good idea ;) We should try to avoid tricks.

The PoolSlot seems to me like a useful abstraction over a connection that automatically reconnects if the connection gets closed + some meta messages that transport (or manipulate) the current state.

The PoolConductor on top of that tries to keep track of the state of its slots and schedules requests in a best-effort way.

That seems to me like a clean separation.

**Comment by 2beaucoup** [comment]
> You mean to rely on all of the stages being run in the same context so that it would be safe to manipulate state of another stage? I don't think that's a good idea ;) We should try to avoid tricks.

Agreed. `SlotCommand`s in and `SlotEvent`s out it is then.

> The PoolSlot seems to me like a useful abstraction over a connection that **automatically reconnects** if the connection gets closed + some meta messages that transport (or manipulate) the current state.

But the (re-)connection is triggered by the conductor, no?

**Comment by jrudolph** [comment]
> But the (re-)connection is triggered by the conductor, no?

Right now, yes, but we could (and should) change it if it simplifies the protocol.

**Comment by 2beaucoup** [comment]
But only the conductor does really know if a (re-)connection is actually necessary.

**Comment by jrudolph** [comment]
In the simplest case, the slot opens a connection if it has request(s) pending (or if was triggered by `ConnectEagerlyCommand`).

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27
If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
