### ISSUE TITLE
Please release scala 2.12-RC2 build of Akka

### ISSUE THREAD

**Issue by dnvriend** [akka/akka#21386]
6-sept 2016 Scala 2.12-RC1 has been released. It would be nice to have a full build of akka 2.4.9 for Scala 2.12-RC1

**Comment by patriknw** [comment]
We are releasing Akka 2.4.10 today and will try to also publish artifacts for 2.12-RC1

**Comment by maxcom** [comment]
2.12.0-RC2 is released

**Comment by ktoso** [comment]
Thanks for the ping here.

We're closely collaborating with the Scala team to bootstrap the RC2 ecosystem, we'll release RC2 artifacts soon. 
Note that we also handle genjavadoc etc (which Spark and many other projects depend on), which have to come first (and did).

**Comment by bantonsson** [comment]
Isn't this all good now?

**Comment by patriknw** [comment]
yes, it was released
