### ISSUE TITLE
RemoteDeathWatchSpec: Unknown message DeathWatchNotification

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21389]
Seeing this with both Artery and old remoting

```
[WARN] [09/07/2016 08:19:21.401] [other-akka.remote.default-remote-dispatcher-9] [akka.actor.LocalActorRefProvider(akka://other)] Unknown message [DeathWatchNotification(Actor[artery://RemoteDeathWatchSpec@localhost:55822/user],true,false)] received by [Actor[akka://other/remote]]
```

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2153/consoleFull

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3178443393/jobs/5179936204#step:5:3190 (Artery Aeron)

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3216094805/jobs/5257648934#step:5:2379 (Artery Aeron)
