### ISSUE TITLE
Hard-coded config paths in LevelDBJournal, LocalSnapshotStore, ...

### ISSUE THREAD

**Issue by Konstantin-Skachkov** [akka/akka#21394]
LevelDBJournal and LocalSnapshotStore are configured with a hardcoded config path. Makes it hard to have multiple instances write to separate directories.

**Comment by patriknw** [comment]
ouch, would you like to create a pull request fixing this?

**Comment by Chuwiey** [comment]
#in-progress

**Comment by patriknw** [comment]
Note that this was not backported to 2.4.x
