### ISSUE TITLE
Move gzip/deflate decompression Flows from akka-http-experimental to akka-stream

### ISSUE THREAD

**Issue by liff** [akka/akka#21395]
Providing a `Flow` for decompressing gzip streams should be useful outside the HTTP context. For reading gzipped files, for example.

I propose moving the non-HTTP-related gzip and deflate compression and decompression classes from akka-http-experimental to akka-stream.

If that sounds OK, I can open a PR with the necessary changes.

**Comment by ktoso** [comment]
Yes, it's a move we wanted to do since a long time but did not manage to get time to do it.
Would be awesome if you could submit a PR for it, thanks!

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ktoso** [comment]
Great work, thanks @liff !
Now for the Akka HTTP side of it tomorrow :)

**Comment by drewhk** [comment]
Yaaaaay!!
