### ISSUE TITLE
Don't (gzip,...) encode known-to-be-empty entities

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21393]
Even if the content-type would allow it by having `compressible=true` set.

Follow up from #20793.

**Comment by gosubpl** [comment]
Looking into this. The plan is to modify relevant checks or definition of `isCompressible` in `Encoder.scala`, as per previous discussion in #20793

**Comment by gosubpl** [comment]
Ah, I have missed `fromStatusCodeAndHeadersAndValue` marshaller in the fix for #20793 . Will fix in this PR.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http
Rationale for the move discussed here: https://github.com/akka/akka-meta/issues/27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
