### ISSUE TITLE
is the non-local recipient check needed?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21402]
In the MessageDispatcher we have the non-local recipient check, logged as:
```
"dropping message [{}] for non-local recipient [{}] arriving at [{}] inbound addresses are [{}]"
```

That would require that we send the full address of the destination system in each message, which is obviously something we would like to avoid. Currently we are cheating in the Decoder.

Is the check needed? What is the exact scenario when it will catch errors/mistakes?

We can include this address in the `HandshakeReq` message and only verify it for the handshake. That should be enough, or?

**Comment by drewhk** [comment]
Aren't the destination system already in the ActorRef itself? I.e. this check is basically about rejecting anything that does not address the canonical address but some other address through which we happen to be reachable (overlapping DNS entries for example).
