### ISSUE TITLE
Add instruction for akka-samples

### ISSUE THREAD

**Issue by richard-imaoka** [akka/akka#21415]
I assume samples under the akka-samples directory should be run via Lightbend Activator.  
If that is correct, does it make sense to add instruction on how to run them? I think README.md under akka-samples dir is good.

I tried to run those samples by:
* git fetch the entire akka repo 
* sbt from the root akka directory 
* project akka-samples 
* runMain .... -> failed with ClassNotFound exceptions due to incorrect classpath

**Comment by ktoso** [comment]
> If that is correct, does it make sense to add instruction on how to run them? I think README.md under akka-samples dir is good.

Open activator, find by name.

Yes, adding a readme would be nice :)
