### ISSUE TITLE
Things to deprecate in 2.5 master ticket

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21423]
Did not find a master ticket for things to deprecate, so starting a new one:

Deprecate:

- [x] deprecate agents => https://github.com/akka/akka/pull/21913
- [x] keep an eye on akka stream stages: https://github.com/akka/akka/issues/19529
  - StatefulStage etc
- [x] Akka Camel - since Alpakka is the replacement => https://github.com/akka/akka/pull/21925
- [x] ActorDSL, no one is using it
- [ ] akka-contrib - nothing to promote from there
- [x] Remoting with UDP, not useful, we have Artery via UDP now

Delete:
- 🔴  not doing - STM support for agents? Is that still a thing? https://github.com/akka/akka/issues/13921 (goes together with deprecating agents)
- [ ] Anything remaining from MicroKernel
- [x] Cluster Metrics in Akka Cluster - monitoring take over those things
- [x] `PersistentView`

**Comment by ktoso** [comment]
I also propose to deprecate `ActorSubscriber` and `ActorPublisher` in streams.
Have not found a single case where I wouldn't tell people to not use them now that `GraphStage` has all the features.

**Comment by patriknw** [comment]
I agree. The only thing I can think of is when delegating to child actors

**Comment by ahjohannessen** [comment]
`PersistentView` does not have an equivalent replacement (story), as far as I can tell. Here I think about snapshotting and having a view id.

**Comment by patriknw** [comment]
You can delegate the events to a PersistentActor, which could do snapshotting. Normally the purpose of a Persistent Query and PersistentView is to build another representation in an external db that can be used for the end user queries. Then it's also better to store the snapshot/offset in that db.

**Comment by ahjohannessen** [comment]
@patriknw I agree. However, I think it would be prudent to document how one can achieve similar features of `PersistentView` using an `PersistentActor` in combination with a `PersistentQuery`

**Comment by ktoso** [comment]
Sure, agreed - would you pour opinion into a PR to help us out on this one? :)

---

@patriknw we can also remove `BalancingDispatcher` it seems

```
@deprecated("Use BalancingPool instead of BalancingDispatcher", "2.3")
class BalancingDispatcher(
```

**Comment by patriknw** [comment]
We can't remove `BalancingDispatcher` because it is used by `BalancingPool` but we can remove it from user API, i.e. make it `private[akka]`

**Comment by ktoso** [comment]
Ok, done!

**Comment by patriknw** [comment]
I have looked through all `@deprecated` before 2.4.0 and removed what can be removed. Will PR when the AbstractActor PR has been merged (to avoid conflicts).

**Comment by patriknw** [comment]
done, create tickets for other related things
