### ISSUE TITLE
Add protobuf 3 support

### ISSUE THREAD

**Issue by frne** [akka/akka#21437]
Protobuf Java classes generated using `protoc` 3.0.0 fail to load (`ClassNotFoundException`). Details can be found here: https://stackoverflow.com/questions/38887581/could-not-send-protocol-buffer-message-from-akka-cluster-client

The current workaround is, to compile java classes using the `protoc` 2.5 binary.

**Comment by patriknw** [comment]
Akka 2.4.x is internally using a shaded version of Protobuf 2.5 and that should not interfere with your own Protobuf 3.x dependency. Have you added the 3.x runtime dependency to your project?

**Comment by frne** [comment]
Sorry for being unclear. It is not the `protobuf-java` library which causes the problem, but the generated java classes from `protoc` compiler.

The protobuf 3.x compiler generates other classes then 2.x. Generated the same .proto file once using `protoc` v2.5 and once using`protoc` v3.0.0.

The 2.5 generated version works fine.

The 3.0.0 generated version works for parsing a bytestring to object, but when I call `ParentClass.SomeProtocClass.newBuilder()` inside an actor, I get a `ClassNotFoundException`.

**Comment by patriknw** [comment]
what is your runtime classpath?

**Comment by frne** [comment]
@patriknw 

AFAIK, dependencies are loaded...

Protobuf lib: 

```
Attributed(/Users/frank/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-3.0.0.jar)
```

Generated java classes: 

```
Attributed(/Users/frank/git/myproject-server/protocol/target/scala-2.11/classes)
```

Full classpath according to ```sbt "show runtime:fullClasspath"```:

```
[info] securityService/runtime:fullClasspath
[info] 	List(Attributed(/Users/frank/git/myproject-server/service/security-service/target/scala-2.11/classes), Attributed(/Users/frank/git/myproject-server/protocol/target/scala-2.11/classes), Attributed(/Users/frank/git/myproject-server/core/target/scala-2.11/classes), Attributed(/Users/frank/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-enhancer/jars/play-enhancer-1.1.0.jar), Attributed(/Users/frank/.ivy2/cache/org.javassist/javassist/bundles/javassist-3.18.2-GA.jar), Attributed(/Users/frank/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-3.0.0.jar), Attributed(/Users/frank/.ivy2/cache/org.mockito/mockito-core/jars/mockito-core-1.10.19.jar), Attributed(/Users/frank/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.1.jar), Attributed(/Users/frank/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-2.1.jar), Attributed(/Users/frank/.ivy2/cache/org.projectlombok/lombok/jars/lombok-1.16.8.jar), Attributed(/Users/frank/.ivy2/cache/com.google.inject/guice/jars/guice-4.0.jar), Attributed(/Users/frank/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar), Attributed(/Users/frank/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar), Attributed(/Users/frank/.ivy2/cache/com.google.guava/guava/bundles/guava-19.0.jar), Attributed(/Users/frank/.ivy2/cache/org.joda/joda-money/jars/joda-money-0.11.jar), Attributed(/Users/frank/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe/config/bundles/config-1.3.0.jar), Attributed(/Users/frank/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/bundles/scala-java8-compat_2.11-0.7.0.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-remote_2.11/jars/akka-remote_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-protobuf_2.11/jars/akka-protobuf_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/io.netty/netty/bundles/netty-3.10.3.Final.jar), Attributed(/Users/frank/.ivy2/cache/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-cluster_2.11/jars/akka-cluster_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-cluster-metrics_2.11/jars/akka-cluster-metrics_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-cluster-tools_2.11/jars/akka-cluster-tools_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-multi-node-testkit_2.11/jars/akka-multi-node-testkit_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-testkit_2.11/jars/akka-testkit_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-contrib_2.11/jars/akka-contrib_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-persistence_2.11/jars/akka-persistence_2.11-2.4.4.jar), Attributed(/Users/frank/.ivy2/cache/org.mongodb.morphia/morphia/jars/morphia-1.2.1.jar), Attributed(/Users/frank/.ivy2/cache/org.mongodb/mongo-java-driver/jars/mongo-java-driver-3.2.2.jar), Attributed(/Users/frank/.ivy2/cache/cglib/cglib-nodep/jars/cglib-nodep-2.2.2.jar), Attributed(/Users/frank/.ivy2/cache/com.thoughtworks.proxytoys/proxytoys/jars/proxytoys-1.0.jar), Attributed(/Users/frank/.ivy2/cache/org.mongodb.morphia/morphia-logging-slf4j/jars/morphia-logging-slf4j-1.2.1.jar), Attributed(/Users/frank/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar), Attributed(/Users/frank/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.7.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-java_2.11/jars/play-java_2.11-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/build-link/jars/build-link-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-exceptions/jars/play-exceptions-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-iteratees_2.11/jars/play-iteratees_2.11-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/org.scala-stm/scala-stm_2.11/jars/scala-stm_2.11-0.7.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-json_2.11/jars/play-json_2.11-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-functional_2.11/jars/play-functional_2.11-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-datacommons_2.11/jars/play-datacommons_2.11-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.8.1.jar), Attributed(/Users/frank/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.7.jar), Attributed(/Users/frank/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.7.6.jar), Attributed(/Users/frank/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.7.6.jar), Attributed(/Users/frank/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.7.6.jar), Attributed(/Users/frank/.ivy2/cache/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/bundles/jackson-datatype-jdk8-2.7.6.jar), Attributed(/Users/frank/.ivy2/cache/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/bundles/jackson-datatype-jsr310-2.7.6.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-netty-utils/jars/play-netty-utils-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.21.jar), Attributed(/Users/frank/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.21.jar), Attributed(/Users/frank/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.21.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/play-streams_2.11/jars/play-streams_2.11-2.5.6.jar), Attributed(/Users/frank/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-stream_2.11/jars/akka-stream_2.11-2.4.9.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4.9.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe/ssl-config-akka_2.11/bundles/ssl-config-akka_2.11-0.2.1.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe/ssl-config-core_2.11/bundles/ssl-config-core_2.11-0.2.1.jar), Attributed(/Users/frank/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.play/twirl-api_2.11/jars/twirl-api_2.11-1.1.1.jar), Attributed(/Users/frank/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.4.jar), Attributed(/Users/frank/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar), Attributed(/Users/frank/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.4.9.jar), Attributed(/Users/frank/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.10.jar), Attributed(/Users/frank/.ivy2/cache/xerces/xercesImpl/jars/xercesImpl-2.11.0.jar), Attributed(/Users/frank/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.4.01.jar), Attributed(/Users/frank/.ivy2/cache/javax.transaction/jta/jars/jta-1.1.jar), Attributed(/Users/frank/.ivy2/cache/com.google.inject.extensions/guice-assistedinject/jars/guice-assistedinject-4.0.jar), Attributed(/Users/frank/.ivy2/cache/org.yaml/snakeyaml/bundles/snakeyaml-1.16.jar), Attributed(/Users/frank/.ivy2/cache/org.hibernate/hibernate-validator/jars/hibernate-validator-5.2.4.Final.jar), Attributed(/Users/frank/.ivy2/cache/javax.validation/validation-api/jars/validation-api-1.1.0.Final.jar), Attributed(/Users/frank/.ivy2/cache/org.jboss.logging/jboss-logging/jars/jboss-logging-3.2.1.Final.jar), Attributed(/Users/frank/.ivy2/cache/com.fasterxml/classmate/bundles/classmate-1.1.0.jar), Attributed(/Users/frank/.ivy2/cache/javax.el/javax.el-api/jars/javax.el-api-3.0.0.jar), Attributed(/Users/frank/.ivy2/cache/org.springframework/spring-context/jars/spring-context-4.2.7.RELEASE.jar), Attributed(/Users/frank/.ivy2/cache/org.springframework/spring-core/jars/spring-core-4.2.7.RELEASE.jar), Attributed(/Users/frank/.ivy2/cache/org.springframework/spring-beans/jars/spring-beans-4.2.7.RELEASE.jar), Attributed(/Users/frank/.ivy2/cache/org.reflections/reflections/jars/reflections-0.9.10.jar), Attributed(/Users/frank/.ivy2/cache/net.jodah/typetools/bundles/typetools-0.4.4.jar), Attributed(/Users/frank/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-3.0.1.jar), Attributed(/Users/frank/.ivy2/cache/org.apache.tomcat/tomcat-servlet-api/jars/tomcat-servlet-api-8.0.33.jar), Attributed(/Users/frank/.ivy2/cache/org.bitbucket.b_c/jose4j/jars/jose4j-0.5.1.jar))
```

**Comment by frne** [comment]
Added a zip with the .proto definition, the generated java class from ```protoc``` v3 and the generated class from ```protoc``` v2.5.

V2.5 generated class works fine, the V3 generated class throws the following exception:

```
java.lang.RuntimeException: Unable to find proto buffer class: ch.myproject.protocol.SecurityProtocol$MobileLoginResponse
	at com.google.protobuf.GeneratedMessageLite$SerializedForm.readResolve(GeneratedMessageLite.java:1192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1148)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1817)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at akka.serialization.JavaSerializer$$anonfun$1.apply(Serializer.scala:242)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at akka.serialization.JavaSerializer.fromBinary(Serializer.scala:242)
	at akka.serialization.Serialization$$anonfun$deserialize$2.apply(Serialization.scala:124)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.serialization.Serialization.deserialize(Serialization.scala:114)
	at akka.remote.MessageSerializer$.deserialize(MessageSerializer.scala:24)
	at akka.remote.DefaultMessageDispatcher.payload$lzycompute$1(Endpoint.scala:57)
	at akka.remote.DefaultMessageDispatcher.payload$1(Endpoint.scala:57)
	at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:75)
	at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:969)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:439)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: ch.myproject.protocol.SecurityProtocol$MobileLoginResponse
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.google.protobuf.GeneratedMessageLite$SerializedForm.readResolve(GeneratedMessageLite.java:1183)
	... 30 more
```

[protoc_files.zip](https://github.com/akka/akka/files/470494/protoc_files.zip)

**Comment by patriknw** [comment]
@frne I can't understand how this could be an Akka issue. Looks like a problem with your classpath/dependencies. Can you please create a sample project to illustrate how to reproduce it if you still think this is because of something in Akka.

**Comment by ktoso** [comment]
I agree with Patrik, this does not seem to be an Akka issue - you're free to use proto3 with the existing Akka versions.

**Comment by schmohlio** [comment]
I'm experiencing the same issue `Unable to find proto buffer class` @patriknw @ktoso  when using Akka remote after upgrading to protobuf 3 in my runtime. This is only surfacing in Akka, not sure how it's not an Akka issue? @frne did you ever resolve your problem?

**Comment by frne** [comment]
@schmohlio Couldn't solve it. Went away from protobuf, using [romix/akka-kryo-serialization](https://github.com/romix/akka-kryo-serialization) now.

**Comment by schmohlio** [comment]
@frne thanks for update. My workaround as of now is to build with 2.6.1 protoc and then in other projects where I'm user protoc 3 import the proto files and rebuild.

**Comment by raboof** [comment]
A small, working example project showing the problem would be quite useful!

While it's true that Akka uses a 'shadowed' version of protobuf 2 internally, that _should_ not interfere with your own use of protobuf. Indeed, in the stacktraces our 'shadowed' protobuf code does not appear to be touched, it goes from `akka.serialization.JavaSerializer.fromBinary` into `com.google.protobuf` code without passing any Akka protobuf code.

If there is some subtle interference that'd be good to track down, but without a project exhibiting the problem it's hard to figure out.

**Comment by patriknw** [comment]
Why is the Java serializer involved at all?

I think it accidentally works with 2.6 because for historical reasons we bind "com.google.protobuf.GeneratedMessage", but that might be different for protobuf 3?

Write a new serializer class, could perhaps be inspired by https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/serialization/ProtobufSerializer.scala

Configure it in your application.conf, something like this:

```
akka.actor {
  serializers {
    proto3 = "com.mycode.Protobuf3Serializer"
  }
  serialization-bindings {
    "com.google.protobuf.GeneratedMessageLite" = proto3
  }
  serialization-identifiers {
    "com.mycode.Protobuf3Serializer" = 1000
  }
}
```

I'm not sure if `com.google.protobuf.GeneratedMessageLite` is the right class to bind it to. It should be something that all your messages extend/implement.

Read more about how to define your own serializer in docs: http://doc.akka.io/docs/akka/current/scala/serialization.html

BTW, I would not use the protobuf generated classes as messages in my application. Instead I would define domain message classes (case classes) and write my own serializer for those that would map them to the protobuf representation that is used on the wire. Here is an example from akka itself: https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala

**Comment by schmohlio** [comment]
thanks @patriknw @raboof. I'll try to throw together an example. 

In general, though, we define Domain messages classes with protobuf serializer strategies. When we implement our microservices, each service method does the following:
* gets the correct protobuf serializer and serializes to something that extends GeneratedMessage[V3], called say, _message_.
* Patterns.ask(routerRef, _message_, timeout))
* map the CompletableFuture back to another domain message in the response

When use protoc < 3 the serializer created something extends GeneratedMessage, but with protoc >= it's generated something that extends `AbstractMessage` or `GeneratedMessage`. It could be that I'm just not configuring any akka.actor.serializers, and that it worked by accident with 2.6.1?

**Comment by schmohlio** [comment]
binding to `"com.google.protobuf.GeneratedMessageV3" = proto3` worked for me. thanks for the insights

**Comment by raboof** [comment]
:+1: thanks for getting in touch, hunting this down and reporting back - we've been planning a blogpost on using Akka with Protobuf 3, and this would be good to mention explicitly there :)

**Comment by enzeart** [comment]
@patriknw Just curious, why wouldn't you use the protobuf generated classes directly?

**Comment by plutogeek** [comment]
> Protobuf Java classes generated using `protoc` 3.0.0 fail to load (`ClassNotFoundException`). Details can be found here: https://stackoverflow.com/questions/38887581/could-not-send-protocol-buffer-message-from-akka-cluster-client
> 
> The current workaround is, to compile java classes using the `protoc` 2.5 binary.

you can refer to the config file 

akka {

  loglevel = DEBUG
  actor {
    provider = "cluster",

    serializers: {
      "proto": "akka.remote.serialization.ProtobufSerializer",
      **"proto3": "akka.remote.serialization.ProtobufSerializer",**
    },

    serialization-bindings: {

      **"com.google.protobuf.GeneratedMessageV3": "proto3",**

    }



  }
  remote {
    artery {
      enabled = on
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 0
    }
  }

  cluster {
    seed-nodes = [
      "akka://ClusterSystem@127.0.0.1:2551",
      "akka://ClusterSystem@127.0.0.1:2552"]

    # auto downing is NOT safe for production deployments.
    # you may want to use it during development, read more about it in the docs.
    auto-down-unreachable-after = 10s
  }
}

# Enable metrics extension in akka-cluster-metrics.
akka.extensions=["akka.cluster.metrics.ClusterMetricsExtension"]

# Sigar native library extract location during tests.
# Note: use per-jvm-instance folder when running multiple jvm on one host. 
akka.cluster.metrics.native-library-extract-folder=${user.dir}/target/native

**Comment by plutogeek** [comment]
> you can refer to the config file
> 
> ```
> akka {
> 
>   loglevel = DEBUG
>   actor {
>     provider = "cluster",
> 
>     serializers: {
>       "proto": "akka.remote.serialization.ProtobufSerializer",
>       "proto3": "akka.remote.serialization.ProtobufSerializer",
>     },
> 
>     serialization-bindings: {
> 
>       "com.google.protobuf.GeneratedMessageV3": "proto3",
> 
>     }
> 
> 
> 
>   }
>   remote {
>     artery {
>       enabled = on
>       transport = tcp
>       canonical.hostname = "127.0.0.1"
>       canonical.port = 0
>     }
>   }
> 
>   cluster {
>     seed-nodes = [
>       "akka://ClusterSystem@127.0.0.1:2551",
>       "akka://ClusterSystem@127.0.0.1:2552"]
> 
>     # auto downing is NOT safe for production deployments.
>     # you may want to use it during development, read more about it in the docs.
>     auto-down-unreachable-after = 10s
>   }
> }
> 
> # Enable metrics extension in akka-cluster-metrics.
> akka.extensions=["akka.cluster.metrics.ClusterMetricsExtension"]
> 
> # Sigar native library extract location during tests.
> # Note: use per-jvm-instance folder when running multiple jvm on one host. 
> akka.cluster.metrics.native-library-extract-folder=${user.dir}/target/native
> ```

after then, your application like this:

````

system.scheduler().schedule(interval, interval, new Runnable() {
      public void run() {

        String content="hello-" + counter.incrementAndGet();
        TransformationJobOuterClass.TransformationJob.Builder jobMessageBuilder=TransformationJobOuterClass.TransformationJob.newBuilder();
        jobMessageBuilder.setText(content);
        ask(frontend,jobMessageBuilder.build()

            ,
            timeout).onSuccess(new OnSuccess<Object>() {
          public void onSuccess(Object result) {
            System.out.println(result);
          }
        }, ec);
      }

    }, ec);

````

````
your message have to be generated by protobuf util


package sample.cluster.transformation;

public final class TransformationJobOuterClass {
 /**
   * Protobuf type {@code sample.cluster.transformation.TransformationJob}
   */
  public  static final class TransformationJob extends
      com.google.protobuf.GeneratedMessageV3 implements
// @@protoc_insertion_point(message_implements:sample.cluster.transformation.TransformationJob)
      TransformationJobOrBuilder {
    // Use TransformationJob.newBuilder() to construct.

...
}

````
