### ISSUE TITLE
Akka HTTP Java: not override abstract method yeOldeTestNames() in org.scalatest.Suite

### ISSUE THREAD

**Issue by harmeetsingh0013** [akka/akka#21433]
Following are the details for issue with akka http experimental testkit.
http://stackoverflow.com/questions/38864899/akka-http-java-not-override-abstract-method-yeoldetestnames-in-org-scalatest/38895886#38895886

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment)
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
