### ISSUE TITLE
Artery causes JVM segfault

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21430]
`sun.misc.Unsafe.getAndAddLong` which was what I saw when it was touching the mmapped file after closing. Doesn't happen consistently.

https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/14/consoleFull

**Comment by patriknw** [comment]
also in `akka.cluster.MinMembersBeforeUpWithWeaklyUp`

**Comment by patriknw** [comment]
Another thing that can cause the segfaults is that we don't stop the `TaskRunner` gracefully.
We should have a promise that is completed when `taskRunner.stop()` is done, and wait for that in the shutdown procedure. Otherwise there may be tasks still trying to use Aeron while we are closing it.

**Comment by johanandren** [comment]
I snuck a fix for taskRunner stop in #21469

**Comment by patriknw** [comment]
still segfault with latest artery-dev https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/64/consoleText

**Comment by patriknw** [comment]
We had one successful run, but there is still something missing. Segfault in https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/76

**Comment by johanandren** [comment]
Segfault crash dump:

[hs_err_pid888.log.txt](https://github.com/akka/akka/files/481950/hs_err_pid888.log.txt)
