### ISSUE TITLE
Pull Chasing might drop a cancel event

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21446]
This can happen if pull chasing is going on and one stage enqueues both a pull and a cancel, where pull comes first. If we are in a chase, this pull avoids going through the queue, which means that the cancellation flag is not checked for that event, which means that it gets lost. The solution is likely that cancel() should check for being in a chase and then aborting it, switching to ordinary dispatch via the event queue.

It must be checked that similar does not exist for completion.

**Comment by drewhk** [comment]
I need to port the port states spec to exercise pull-push chasing, too.

**Comment by Sciss** [comment]
Thanks, I'll test as soon as 2.4.11 is out

**Comment by drewhk** [comment]
You can also try the nightly tomorrow.

**Comment by drewhk** [comment]
http://repo.akka.io/snapshots/
