### ISSUE TITLE
RouteTest cleanUp does not wait for ActorSystem termination

### ISSUE THREAD

**Issue by mmatloka** [akka/akka#21442]
`RouteTest.cleanup` performs `def cleanUp(): Unit = system.terminate() ` https://github.com/akka/akka/blob/master/akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala#L50 where `  def terminate(): Future[Terminated]`

**Comment by ktoso** [comment]
Please open Akka HTTP tickets in the Akka HTTP repository: http://github.com/akka/akka-http

Rationale for the move discussed here: akka/akka-meta#27
