### ISSUE TITLE
Re-align values in header

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21448]
Since now we made the version a Byte, and use another Byte for the flags, we have an empty space of 2 bytes that we should use somehow or re-align the other writes those 2 bytes up.

**Comment by ktoso** [comment]
See here https://github.com/akka/akka/pull/21378/files#diff-82dac4787416496563ec7e2e6c3fe8ecR347

**Comment by patriknw** [comment]
Should be done together with https://github.com/akka/akka/issues/20872

**Comment by patriknw** [comment]
note that this ticket should also align the header offsets for ActorRefCompressionTableVersionTagOffset and ClassManifestCompressionTableVersionTagOffset, which became Byte instead of Int in https://github.com/akka/akka/pull/21559

**Comment by patriknw** [comment]
one follow up from the other PR: https://github.com/akka/akka/pull/21559/files#r80625853
