### ISSUE TITLE
Clarify delivery guarantees for Distributed PubSub in the reference docs

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#21441]
This space intentionally left blank.

**Comment by ktoso** [comment]
It's at-most-once, as everywhere else by default.
Since there is not ACKing there's no way to make at-least-once there.

For at-least-once we recommend going over our Kafka Akka Streams integration: https://github.com/akka/reactive-kafka

**Comment by richard-imaoka** [comment]
>This space intentionally left blank.
Hi sorry but where is the blank space in the doc? I couldn't find it..

**Comment by ktoso** [comment]
What Viktor means with this witty description is that the title contains all information about the task ;-)

It's not always clear to people what the semantics of the cluster pub sub are.

**Comment by richard-imaoka** [comment]
Ahh, I see. Thanks for making it clear. 

I will try to add it in the doc then.

**Comment by ktoso** [comment]
Awesome, thanks a lot in advance! :)
