### ISSUE TITLE
don't quarantine back

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21450]
We discussed this previously when investigating `SurviveNetworkStabilitySpec`.

When a system gets the `Quarantined` message from another system that has quarantined it we quarantine the other system back. That feels like a logical thing to do but it has a bad consequence with regards to cluster downing.

I thought of this today when debugging Christophers case where he used `kill -STOP`.

It will result in two separate clusters, since quarantine will result in removal of the cluster member.

Instead, I think we should just publish the `ThisActorSystemQuarantinedEvent` to the eventStream and then the downing strategy can do what it thinks is right. SBR could use it as a STONITH signal, i.e. shutdown itself.

Note that we don't do this quarantine in old remoting.

**Comment by patriknw** [comment]
@drewhk do you agree with my conclusion?

**Comment by drewhk** [comment]
This is not an easy question. For clustering I would answer yes, for plain remoting I would probably say no. If the other system quarantined us, then in normal remoting we can signal Terminated for all remotely watched actors if we quarantine it. Given that we don't do it in old remoting we should not change that.

**Comment by patriknw** [comment]
Note that for plain remoting watched actors will be signaled terminated anyway, a bit later, since heartbeats will not get through.

Closing then since I did the change in https://github.com/akka/akka/issues/21449
