### ISSUE TITLE
BasicHttpCredentials can't deal with no password

### ISSUE THREAD

**Issue by elm-** [akka/akka#21457]
While working on the Zendesk API I noticed that it is not possible to use the BasicHttpCredentials without password. Some APIs use only a username that encodes the username / token instead of splitting it up into username and password (besides Zendesk the Google Docker Registry has a similar approach I think).

The difference is that the ":" between username and empty password is not part of the encoded string.

My suggestion therefore is to either create a new header or extend the BasicHttpCredentials to support this case.

```
BasicHttpCredentials(username: String, password: Option[String])
```

I created my own type for now to reflect it (BasicHttpUserCredential(username: String)) that handles this.

Does it make sense to work something into the HTTP model to support this?

**Comment by ktoso** [comment]
Hi there,
we're in the progress of moving Akka HTTP into it's own repository.
Please open tickets related to Akka HTTP (from now on, and in the future) in this repository instead: https://github.com/akka/akka-http/issues/

Thanks for your report and understanding!

**Comment by ktoso** [comment]
Hm, I think it's a missing thing indeed. I've seen such APIs around as well.
Please open the ticket in the right repo and let's take it from there over there :)

**Comment by elm-** [comment]
Raised at https://github.com/akka/akka-http/issues/302

**Comment by ktoso** [comment]
Thanks a lot
