### ISSUE TITLE
failed: ArteryRemoteDeploymentDeathWatchSlow

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21463]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7421/consoleFull

```
[JVM-1] - must be able to shutdown when remote node crash *** FAILED *** (8 seconds, 410 milliseconds)
[JVM-1]   akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://RemoteDeploymentDeathWatchSpec/user/controller#607663445]] after [5000 ms]. Sender[null] sent message of type "akka.remote.testconductor.Terminate".
[JVM-1]   at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
[JVM-1]   at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
[JVM-1]   at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
```

**Comment by drewhk** [comment]
Argh, this is a totally weird failure. Stacktrace is not much help as it ends in LARS. Seems like testcounductor didn't answer to a Terminate command. I am not yet sure if this is Artery related.

**Comment by patriknw** [comment]
@drewhk  Looked at the log. I agree that it's weird. Let's close it, at least until we see it again.

**Comment by drewhk** [comment]
I think it can be related to testconductor.exit. I recall this kind of error from before. Anyway I stop debugging this now.
