### ISSUE TITLE
Ability to use custom MediaTypes with `SprayJsonSupport`

### ISSUE THREAD

**Issue by akauppi** [akka/akka#21471]
The akka-http / Spray json integration is pretty good, but forces one to get generic `application/json` output. Use of more specific data types (e.g. `application/problem+json`) is common, and beneficial. However, I did not find a way to implement that with akka-http 2.4.10.

Suggestion: `SprayJsonSupport` could take an implicit `MediaType` parameter, defaulting to `application/json`.

I will make a local copy of the code and experiment with this approach. Decided to first bring this up as an Issue for discussion - can provide a PR if there's acceptance for such a feature.
 
https://github.com/akka/akka/blob/0ed4a2aae9ecab43ef806025596a5573ddc883ea/akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala

**Comment by akauppi** [comment]
Should probably move this over to [akka-http](https://github.com/akka/akka-http) repo?

**Comment by ktoso** [comment]
Yes, thanks.
