### ISSUE TITLE
".within" method in TestKit doesn't limit the max timeout for expectations called on test probes

### ISSUE THREAD

**Issue by sp-niemand** [akka/akka#21470]
Example:
```scala
within(min, max) {
    testProbe1.expectMsg(msg1)
    testProbe2.expectMsg(msg2)
    testProbe3.expectMsg(msg3)
}
```
Here every expectation on test probes doesn't use `max` set up in `within`. This is a bit counterintuitive.

**Comment by patriknw** [comment]
within is for a specific probe (TestKit instance), so you must do testProbe1.within

**Comment by patriknw** [comment]
@sp-niemand Did you see my reply?

**Comment by sp-niemand** [comment]
@patriknw Yeah, saw it. Actually, the issue is very minor. It's about the... consistency of the API.

In my example you can't just use `testProbe1.within`, because the expectations on other two probes won't use `max` from it.

You must use something like:
```
within(min, max) {
    testProbe1.expectMsg(remaining, msg1)
    testProbe2.expectMsg(remaining, msg2)
    testProbe3.expectMsg(remaining, msg3)
}
```

Having to repeat `remaining` in every expectation doesn't look good.

**Comment by patriknw** [comment]
ah, you have more than one probe. Then you must write it as:

```
testProbe1.within(min, max) {
testProbe2.within(min, max) {
testProbe3.within(min, max) {
    testProbe1.expectMsg(msg1)
    testProbe2.expectMsg(msg2)
    testProbe3.expectMsg(msg3)
}
}
}
```

or do it as you suggested with `remaining`.

It's not much we can do here. The timeout is tied to a specific probe.

**Comment by patriknw** [comment]
or more readable:
```
testProbe1.within(min, max) {
    testProbe1.expectMsg(msg1)
}
testProbe2.within(min, max) {
    testProbe2.expectMsg(msg2)
}
testProbe3.within(min, max) {
    testProbe3.expectMsg(msg3)
}
```

**Comment by sp-niemand** [comment]
@patriknw Oh, didn't think about stacking `within` blocks from several probes.
