### ISSUE TITLE
InboundCompressions should be owned by the Decoder

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21475]
InboundCompressions should be owned by the Decoder stage, and then it doesn't have to be thread-safe.

Now it's a mix, the hit counting is not thread-safe, i.e. only called from Decoder, but scheduling, advertisements and confirmations are handled on the side with concurrent data structures.

Would be more simple to let the decoder handle all things. The drawback might be slowdown of Decoder when preparing tables for advertisement.

**Comment by drewhk** [comment]
I am handing this back, not sure when I will get to this.

**Comment by ktoso** [comment]
Note: A related fix was merged for 2.4.13, however this ticket remains valid to properly solve the issue.

**Comment by ktoso** [comment]
Starting to work on it.
