### ISSUE TITLE
Cluster Sharding with remember-entity restarting a stopped actor

### ISSUE THREAD

**Issue by ajmalbabu** [akka/akka#21487]
We using AKKA 2.4.9 persistent actor, cluster sharding with Cassandra storage and have enabled  remember-entity = true. We need to stop certain persistent actor after a specific time-frame. (few days). The issue is that the actor once stopped gets automatically restarted after 10 seconds. But if remember-entity is set to false it does not restart. The actor stop is performed is tried out (a) from another persistent actor or (b) from the same persistent actor with a scheduled future event to stop itself.  Both cases automatic restart happens.

We are using Spring with AKKA. Interestingly if the persistence actor stop is performed from direct spring code for e.g. on a rest end point (not from an actor code) persistent actor does not get automatically restarted irrespective of the above flag remember-entity = true or false. Can you please provide solution for this,

**Comment by johanandren** [comment]
Hi, please use the mailing list or the gitter channel for questions and use the issue system only for bugs and feature tickets, thanks!
