### ISSUE TITLE
Extract the inline heap in TopHeavyHitters to a separate class

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21496]
As discussed in #21027 and introduced in #21495 there is a stack implementation inlined in heavy hitters which would be nicer if it was a separate class.

**Comment by pawmot** [comment]
I'd be happy to take this

**Comment by patriknw** [comment]
excellent, thanks

**Comment by Captain1653** [comment]
The issue is really old.  I can see some comments, but there are too old. Is it still needed?

**Comment by patriknw** [comment]
Thanks for noticing. I see no point in touching that code now.
