### ISSUE TITLE
Error mapping materialized OutputStream

### ISSUE THREAD

**Issue by halfninja** [akka/akka#21504]
I've written a test to demonstrate what seems like a bug in using StreamConverters.asOutputStream. When using mapMaterializedValue to acquire the resulting OutputStream and write to it.

https://github.com/halfninja/akka/commit/df560dd640125fb37813b1f02d99894cda4db3be

Test fails with exception that suggests this is too early to be working with the stream:

> java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor

Is this just an invalid use of mapMaterializedValue? The use case is to be able to pass a `Source[ByteString, _]` to Play! Framework chunked response, that will write the output from a legacy library that only takes an `OutputStream`. There are some suggestions to call `.run()` to get the `OutputStream`, but as Play! expects a Source to run itself, I don't think that's a solution here.

This works but introduces buffering outside of Akka that doesn't benefit from being part of a reactive stream:
```
val in = new PipedInputStream()
val out = new PipedOutputStream(in)
Future { doWriting(out) }
StreamConverters.fromInputStream( () => in )
```

Reference to related Play! issue: https://github.com/playframework/playframework/issues/6579

**Comment by johanandren** [comment]
Thanks for reporting.

Side effecting from `mapMaterializedValue` like that seems a bit questionable, but I think it actually is a bug. 

I cannot get the test to fail locally however, could you please paste the whole stack trace from the failure here in the ticket?

**Comment by halfninja** [comment]
Hi, thanks for taking a look at it. I've just tried running the test multiple times and it does pass for me some of the time, so I guess there's a race condition where it might end up writing/flushing before or after it's ready.

```
[info] - must map materialized OutputStream *** FAILED *** (2 seconds, 44 milliseconds)
[info]   java.io.IOException: java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor
[info]   at akka.stream.impl.io.OutputStreamAdapter$$anonfun$sendMessage$1.apply$mcV$sp(OutputStreamSourceStage.scala:201)
[info]   at akka.stream.impl.io.OutputStreamAdapter.send(OutputStreamSourceStage.scala:172)
[info]   at akka.stream.impl.io.OutputStreamAdapter.sendMessage(OutputStreamSourceStage.scala:191)
[info]   at akka.stream.impl.io.OutputStreamAdapter.flush(OutputStreamSourceStage.scala:215)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4$$anonfun$10.apply(OutputStreamSourceSpec.scala:72)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4$$anonfun$10.apply(OutputStreamSourceSpec.scala:68)
[info]   at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:959)
[info]   at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:958)
[info]   at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:936)
[info]   at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:882)
[info]   at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:240)
[info]   at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:138)
[info]   at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:350)
[info]   at akka.stream.scaladsl.Source.runWith(Source.scala:81)
[info]   at akka.stream.scaladsl.Source.runReduce(Source.scala:117)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4.apply(OutputStreamSourceSpec.scala:76)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4.apply(OutputStreamSourceSpec.scala:67)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(OutputStreamSourceSpec.scala:67)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(OutputStreamSourceSpec.scala:67)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   Cause: java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor
[info]   at akka.stream.stage.GraphStageLogic.interpreter(GraphStage.scala:242)
[info]   at akka.stream.stage.GraphStageLogic$$anon$2.invoke(GraphStage.scala:885)
[info]   at akka.stream.impl.io.OutputStreamSourceStage$$anon$1.wakeUp(OutputStreamSourceStage.scala:73)
[info]   at akka.stream.impl.io.OutputStreamSourceStage$$anonfun$createLogicAndMaterializedValue$2.apply(OutputStreamSourceStage.scala:154)
[info]   at akka.stream.impl.io.OutputStreamSourceStage$$anonfun$createLogicAndMaterializedValue$2.apply(OutputStreamSourceStage.scala:154)
[info]   at akka.stream.impl.io.OutputStreamAdapter$$anonfun$sendMessage$1.apply$mcV$sp(OutputStreamSourceStage.scala:193)
[info]   at akka.stream.impl.io.OutputStreamAdapter.send(OutputStreamSourceStage.scala:172)
[info]   at akka.stream.impl.io.OutputStreamAdapter.sendMessage(OutputStreamSourceStage.scala:191)
[info]   at akka.stream.impl.io.OutputStreamAdapter.flush(OutputStreamSourceStage.scala:215)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4$$anonfun$10.apply(OutputStreamSourceSpec.scala:72)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4$$anonfun$10.apply(OutputStreamSourceSpec.scala:68)
[info]   at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:959)
[info]   at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:958)
[info]   at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:936)
[info]   at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:882)
[info]   at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:240)
[info]   at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:138)
[info]   at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:350)
[info]   at akka.stream.scaladsl.Source.runWith(Source.scala:81)
[info]   at akka.stream.scaladsl.Source.runReduce(Source.scala:117)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4.apply(OutputStreamSourceSpec.scala:76)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$4.apply(OutputStreamSourceSpec.scala:67)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(OutputStreamSourceSpec.scala:67)
[info]   at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$4.apply(OutputStreamSourceSpec.scala:67)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

In fact, if I run just the one test method then the failures are a different exception - `java.util.NoSuchElementException: reduce over empty stream`. It only seems to give the above exception when running at least the whole spec class, which might suggest test leaking, I don't know.

I run the single test method with this SBT task:
 `akka-stream-tests/test-only akka.stream.io.OutputStreamSourceSpec -- -z "map materialized"`

**Comment by johanandren** [comment]
The problem here is that the `OutputStreamSource` uses an async callback and that cannot be accessed in the materialized value (ticket #20503). This could be fixed by either fixing that ticket or making the graph stage give away a future of the callback instead, and complete that promise when it is safe to call the callback. I don't think it is worth doing this, better to fix the referenced ticket.

**Comment by halfninja** [comment]
Ah, okay. As there's a workaround for _Play!_ (it has a conversion from Enumeratee to Publisher) I'm happy to wait for #20503 to be resolved.

**Comment by johanandren** [comment]
After a thinking a bit more about it I came this realization: If you do blocking write like this in `mapMaterializedValue` you can write at most buffer size chunks before it will deadlock because of the internal `LinkedBlockingQueue` growing full blocking the write call and leading to materialization never completing - and therefore the `Source` may never actually start running. Not sure if there is a materialization timeout in there that will hit.

So even if #20503 is fixed, this will be a dangerous thing to do in practice.

**Comment by johanandren** [comment]
It would be safe to send that work off to a different thread from `mapMaterializedValue` though, and then the other ticket still will be a problem right now.

**Comment by halfninja** [comment]
Interesting. We have experienced an app freeze in production when using this pattern to serve larger files, so it was probably hitting the situation you describe.

**Comment by patriknw** [comment]
@johanandren What is the status here? Was it solved by something else? Close or triage?

**Comment by johanandren** [comment]
We have the other ticket, even with that solved this will be dangerous unless triggering work in another thread. I'll close it.
