### ISSUE TITLE
Let Cluster members with status WeaklyUp participate in Distributed Data

### ISSUE THREAD

**Issue by jgordijn** [akka/akka#21502]
This is a feature request for the feature mentioned in the documentation: 

> Cluster members with status WeaklyUp, if that feature is enabled, will currently not participate in Distributed Data, but that is something that should be possible to add in a future release.

IMHO Distributed Data is used in situations where availability is very important. Therefore allowing to add new nodes while there is a partition actually makes sense. It should receive all known data in the part of the partition it can join. When the partition is healed it will converge again to a consistent state.

**Comment by patriknw** [comment]
It's already implemented in https://github.com/akka/akka/issues/18399. The documentation was not updated. Could you please create a PR to update the documentation.
