### ISSUE TITLE
remove floating point arithmetic in LARS.roundUp method

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21507]

**Comment by BayStallion** [comment]
@patriknw  I might be getting it wrong, but what do you mean by floating point arithmetic in here?
```((d + TickDuration - oneNs) / TickDuration).toLong * TickDuration```
Is it about division that results in a Double value? But then we call toLong on it.

**Comment by patriknw** [comment]
I just copied the title from the pull reuest. Yes, I think it refers to the Duration division
