### ISSUE TITLE
Directory Traversal Attack vulnerability in Akka HTTP's getFrom(Browseable)Directory directive

### ISSUE THREAD

**Issue by roikonen** [akka/akka#21519]
I noticed that when running Akka HTTP server in Windows machine I am able to access all files of the server machine.

**Example**

With route:
`
pass {
   getFromBrowseableDirectory("/some/directory/i/only/want/to/share")
}
`
or
`
pass {
   getFromDirectory("/some/directory/i/only/want/to/share")
}
`

I can request for example:
http://localhost:8080/%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5cwindows/win.ini
...and download the actual win.ini file that exist in C:/windows

In the case of getFromBrowseableDirectory I can also see all the files there is in the server machine.

That is Directory Traversal Attack vulnerability: https://www.owasp.org/index.php/Path_Traversal

**Comment by drewhk** [comment]
This ticket should be moved to https://github.com/akka/akka-http#317

**Comment by roikonen** [comment]
Moved: https://github.com/akka/akka-http/issues/346

**Comment by drewhk** [comment]
Thank you very much! (we moved repos recently, sorry for the inconvenience)
