### ISSUE TITLE
possibly convert akka.typed.EventStream into an ActorRef

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#21525]
The eventStream could be a service just like the receptionist.

There would be two drawbacks:
- obtaining the logLevel would be asynchronous (which makes BusLogging … interesting)
- wrapping calls as messages means one extra allocation per eventStream usage

**Comment by johanandren** [comment]
I stumbled into this while the work on typed now in the beginning of the year and I think that having a message based public API much nicer/more consistent than a specific abstraction (otoh, internally I don't care _that_ much about it). Making it internal for now.

**Comment by johanandren** [comment]
Closing this as we removed the typed event stream (for now).

**Comment by patriknw** [comment]
but it could still be implemented on top of the untyped event stream so I think that is the wrong reason for closing. Not top prio, though.

**Comment by patriknw** [comment]
Also consider the requests in https://github.com/akka/akka/issues/25893

**Comment by vaslabs** [comment]
Hello,
I was looking for a way to do this with Akka typed and ended up to this issue. Apologies if my suggestion is out of date. 

We are also using Akka typed fully in production for the past 6 months but I may have missed a different pattern that may exist to do this, please point it out if I did.

### The problem

I find it quite annoying to use the adapter every time I want to access the event stream. The use cases I find the event stream useful is mostly for monitoring and testing purposes. I think it would be worth to at least make it type safe by adding a helper method to the actor system, something like.

```
private def subscribe[A](actorRef: ActorRef[A])(classTag: ClassTag[A]): Unit =
    toUntyped.eventStream.subscribe(actorRef.toUntyped, classTag.runtimeClass)
```
and 
```
  private def publish[A](message: A)(implicit actorSystem: ActorSystem): Unit =
    actorSystem.eventStream.publish(message)
```
The disadvantage of this is adding two more methods to the typed actor system interface so another approach would be to have something like
```
def eventStream[A]: ActorRef[A]
```
Which would be a wrapper actor around the event stream implementation.
or even something like
```
def eventStream[A]: TypedEventStream[A]
```
which would just be a simple class wrapping the untyped event stream and providing the subscribe and publish methods above.

Please let me know what you think, if nobody is currently working on it I could do some draft implementations to start with.

**Comment by vaslabs** [comment]
ok, so as stated above similar to how the receptionist was implemented, I'll give it a go

**Comment by vaslabs** [comment]
This is my first attempt https://github.com/akka/akka/pull/26810
