### ISSUE TITLE
split out test facilities into akka-typed-testkit

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#21524]
see discussion on #21485

**Comment by Chuwiey** [comment]
@rkuhn are you working on this?

Would recommend adding the following to the description here, to make it more tl;dr:
Create an Akka Typed Testkit facility, copying needed things from the original Testkit and removing the dependency from the akka-typed-experimental package

**Comment by rkuhn** [comment]
No, sorry, I cannot work on this right now. For easier reference, here are the salient points of the previous discussion:

@rkuhn commented on 22 Sep

Okay, then that means creating a TestLogger, placing that in its own artifact and splitting out akka-typed-tests in its own subproject as well.

There is a difference in the philosophy behind Akka Typed: everything is inherently designed for testability and some test utilities like the StubbedActorContext or EffectfulActorContext are even provided already. That is why I included the necessary infrastructure as well—testing failure scenarios without Mute/UnMute is just not tenable.

So the question is which way we go:

* add two new subprojects to the build to keep everything separated while reusing testkit pieces in typed
* keep the dependency on testkit
* copy the message types into the akka.typed namespace

@patriknw commented on 22 Sep

I think there will be a need for an Akka Typed Testkit sooner or later anyway. I don't like mixing testing facilities with production artefacts.

If it's too early to do that split now, I prefer to copy TestEventListener to akka-typed.

@rkuhn commented on 22 Sep

Okay, then I’ll do the split and move out all test facilities. I’d prefer to do that in a different PR, though, and I’ll try to rearrange things such that tests can be run in Eclipse (which cannot cope with merging reference.conf files).

**Comment by rkuhn** [comment]
Please note that I do not think that it is a good idea to copy everything from akka-testkit that can be copied: the approach to testing is different with akka-typed due to the change in philosophy—synchronously awaiting asynchronous events should be a lot less frequently required now. Actors should be tested using other Actors, and behaviors should be tested synchronously in isolation.
