### ISSUE TITLE
Framing object from stream.scaladsl is extremely slow 

### ISSUE THREAD

**Issue by StelaLeon** [akka/akka#21530]
When using the Framing.delimiter is extremely slow when trying to search for the first byte of delimiter. It took almost 1 second calling just 
buffer.indexOf(firstSeparatorByte, from = nextPossibleMatch).

This should be replaced with indexOf from ByteString class so instead of GenericSequence like this: 
```
def indexOf[B >: Byte](str: ByteString, elem: B, from: Int): Int = {
          val res = str.slice(from, str.size).indexOf(elem)

          if (res == -1) -1
          else from + res
        }
```

Also as an improvement when the first separator byte matches but it was not actually a match it makes sense to have ` nextPossibleMatch = possibleMatchPos + 1` instead of ` nextPossibleMatch += 1 `

**Comment by johanandren** [comment]
Or by optimizing `indexOf(Byte, Int)` in ByteString, then we could avoid the extra allocation as well.

**Comment by johanandren** [comment]
I must have not read that sample when I commented, anyways, what I meant was that slice allocates a new ByteString, so it would be better to avoid that and just make a smarter `indexOf`.

**Comment by patriknw** [comment]
@StelaLeon Thanks for reporting. Would you like to create a pull request to improve this?

**Comment by patriknw** [comment]
or, is this already in progress, @johanandren? https://github.com/akka/akka/pull/21539

**Comment by johanandren** [comment]
PR is pretty much done and just waiting for review AFAIR

**Comment by ktoso** [comment]
Cool, reviewing then
