### ISSUE TITLE
Grammar in handling-blocking-operations-in-akka-http-routes

### ISSUE THREAD

**Issue by kubukoz** [akka/akka#21542]
http://doc.akka.io/docs/akka/current/scala/http/handling-blocking-operations-in-akka-http-routes.html

In the highlighted part:

>Handling blocking operations in Akka HTTP
>=========================================
>Sometimes it is difficult to avoid performing the blocking operations and there
>are good chances that the blocking is done inside a Future **execute**, which may
>lead to problems. It is important to handle the blocking operations correctly.

I think there's a bad form of the word *execute*. Should it be "executor" or "execution"? I'm working on a typo-fixing PR currently, might add a fix for this to it.

**Comment by kubukoz** [comment]
Also, later:

>Here ``thread-pool-executor`` is used, which has a hard limit of threads, it can
>**keep** available for blocking operations. The size settings depend on the app
>functionality and the number of cores the server has.

I think it should be **stay** available, but I'm not sure if that's what it's supposed to mean ;)

**Comment by ktoso** [comment]
> keep available for blocking operations. 

Please reword it as:

"it keeps a set number of threads available that allows for safe isolating of the blocking operations."

**Comment by kubukoz** [comment]
Applied the suggestion, squashed in #21544

**Comment by ktoso** [comment]
Thanks! Agree with PR and ticket but this should go into github.com/akka/akka-http
