### ISSUE TITLE
Add scanAsync to Akka Streams, similar to scan but taking a Future

### ISSUE THREAD

**Issue by mateusduboli** [akka/akka#21541]
As pointed out in #18603, there's need for asynchronous versions of combinators, namely `scan`, `fold` and `reduce`.

Since the issue was closed after implementing `foldAsync`, this issue is to track the development of `scanAsync`.

**Comment by mateusduboli** [comment]
@johanandren

**Comment by pawmot** [comment]
I'd be happy to take this
