### ISSUE TITLE
"Using the Future-Based API in Actors" uses Future.toString

### ISSUE THREAD

**Issue by kubukoz** [akka/akka#21546]
http://doc.akka.io/docs/akka/current/scala/http/client-side/request-level.html#Using_the_Future-Based_API_in_Actors

```scala
 def receive = {
    case HttpResponse(StatusCodes.OK, headers, entity, _) =>
      log.info("Got response, body: " + entity.dataBytes.runFold(ByteString(""))(_ ++ _))
    //...
}
```

AFAIK runFold returns a Future, so in this case we might be appending a Future to a String in that logging line. It should probably use the value of the future in a `foreach` or for comprehension.

**Comment by ktoso** [comment]
Moved issue to Akka HTTP repo, see link above
