### ISSUE TITLE
Akka Actor_2.10 uses unsupported/EOLed Scala Library 2.10.4. Akka needs to bump up its Scala Library version to 2.11.8.

### ISSUE THREAD

**Issue by marydzhang** [akka/akka#21545]
Akka Actor 2.3.x (akka actor_2.10.jar) still uses the EOLed version of org.scala-lang:scala-library:jar:2.10.4.  even the latest akka Actor_2.10 uses Scala Library 2.10.4.

However, Scala 2.10.4 went EOL just over a year ago, and it recommends: “We strongly encourage you to upgrade to the latest stable version of Scala 2.11.x, as the 2.10.x series is no longer actively maintained.”.  

We are currently blocked by Akka Actor to upgrade to Scala library 2.11.8. 
Akka Actor_2.10 needs to bump up its Scala Library version from 2.10.4 to 2.11.8. Otherwise, its users are forced to use the unsupported EOLed Scala Library 2.10.4.

**Comment by kubukoz** [comment]
Do you think a library that's meant for use with 2.10.x (Akka Actor_2.10) will work if you compile it with Scala 2.11.x?

**Comment by marydzhang** [comment]
Do you recommend using a new version of akka actor? Does akka have a newer version of akka actor_2.10 that uses scala library 2.11.x?

**Comment by ktoso** [comment]
A few things to note: 
2.3 is outdated.
2.4 is binary compatible with 2.3.
Please upgrade to latest 2.4.
2.3 as well as 2.4 are released for scala 2.11.
It does not matter which 2.11 akka was compiled against, you can use any scala 2.11.x with it.
The _2.10 in the artifact name explains that its compatible with a given Scala version.
So you should use akka 2.4.10, with Scala 2.11

Closing the ticket as there's nothing to do for us here. Please upgrade and happy hakking
