### ISSUE TITLE
Streams: cannot create custom flow splitting stages

### ISSUE THREAD

**Issue by jypma** [akka/akka#21567]
It seems that currently (2.4.10) the only way to get a `SubFlow` is to use one of the built-in `splitWhen`, `splitAfter` or `groupBy`. This makes it hard to write custom (stateful) stages that split a flow into sub-flows. 

For example, we have a use case to split a `Source[ByteString]` into sub-flows of a (almost) fixed size for chunked processing. Our [current approach](https://github.com/bluelabsio/s3-stream/pull/13/files#diff-df939a9b341b94a576872882ae25229eR22) cheats by having a custom stage inject "split markers", splitting when a marker is found, and then filtering them out again:

``` scala
def splitOnSize[I,M](minSize: Long)(in: Flow[I,ByteString,M])
                   : SubFlow[ByteString, M, in.Repr, in.Closed] = 
  in.via(insertMarkers(minChunkSize))
     .splitWhen(_ == NewStream)
     .filter(_.isInstanceOf[ByteString])
     .map(_.asInstanceOf[ByteString])

private def insertMarkers(minChunkSize: Long) = 
    new GraphStage[FlowShape[ByteString,Any]] { ... }
```

It would be nice to have a prettier way of doing this.

**Comment by patriknw** [comment]
@drewhk thoughts?

**Comment by drewhk** [comment]
Stream-of-stream stages are super hard to write and hence there is not much support for them for users. If you can express your logic as splitWhen+filter, then you are likely better served by them than try to roll your own. That said, we might make the SubSource and SubSink interfaces public at some point, but so far we didn't do that.

**Comment by patriknw** [comment]
@jypma Did you see the reply here? Can we close the issue?

**Comment by jypma** [comment]
If this is the recommended approach, does it make sense to move it to the docs / cookbook / sth?
