### ISSUE TITLE
ability to snapshot PersistentFSM after set number of persisted events

### ISSUE THREAD

**Issue by abesanderson** [akka/akka#21563]
I put in some functionality in some of my code to wrap the `PersistentFSM` in order to snapshot after a certain number of applied events(using a mod of `lastSequenceNr`, similar to `PersistentShard`).  However, `StateChangeEvent` can also occur, and the call which persists the journal message is not public.  Any objections to adding a global `snapshot-after` config flag, and adding some check logic in the `persistAll` callback within `PersistentFSM` to call `saveStateSnapshot` after set number of events?

**Comment by patriknw** [comment]
@abesanderson Sounds good. Would you like to create a pull request?

**Comment by abesanderson** [comment]
Yeah, can do that.  Last week-ish has been busy, so it may take a day or two for me to pull things together.

**Comment by richard-imaoka** [comment]
Hi @abesanderson sorry to jump in, but would it still be something you are submitting a PR? If you are busy on something else, I wanted to see if I can pick this up.

**Comment by abesanderson** [comment]
@richard-imaoka I started this but never got far enough for a PR, if you had an idea to contribute, please go ahead.  The solution I was pursuing was fairly straightforward, I'm curious to see how you approach it though.

**Comment by richard-imaoka** [comment]
Sure. I'll need a bit of time to understand how `PersistentFSM` works, but will try to submit a PR.
