### ISSUE TITLE
Use sbt to compile Akka without network

### ISSUE THREAD

**Issue by huangzhendong** [akka/akka#21579]
Since some factors, I have to compile akka in a null network environment, but no matter what I have done (copy the ~/.ivy、~/.sbt、~/.m2 to the null network machine), it failed to compile the project of akka. The fail info follows:
**[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang#scala-library;2.10.2: not found
[warn]  :: org.scala-lang#scala-reflect;2.10.2: not found
[warn]  :: org.scala-lang#scala-swing;2.10.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: 
unresolved dependency: org.scala-lang#scala-library;2.10.2: not found
unresolved dependency: org.scala-lang#scala-reflect;2.10.2: not found
unresolved dependency: org.scala-lang#scala-swing;2.10.2: not found**

Unless I access the internet download the basic jar, then the compile will finish the compile.

But something really make me confused, why I have to download 2.10.2 scala, the akka only use 2.10.4, please tell me why?

**Comment by viktorklang** [comment]
Does this help? http://alvinalexander.com/scala/setting-putting-sbt-into-offline-mode-no-wifi

**Comment by hepin1989** [comment]
@huangzhendong first compile with network,then you could compile it without network,otherwise you could copy the .ivy2 folder to the dev pc.

**Comment by huangzhendong** [comment]
@hepin1989 I have already done as what you have said, but when I offline to compile, it still logged the above errors (What I compile is an Akka project), I really don't know what was missing ! It always want to find the following file.
<br>
`
unreacheable url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-library/2.10.2/ivys/ivy.xml
unreacheable url=http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-lang/scala-library/2.10.2/ivys/ivy.xml
unreacheable url=http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.pom
unreacheable url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-library/2.10.2/ivys/ivy.xml
`
<br>
`
unreacheable url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-reflect/2.10.2/ivys/ivy.xml
unreacheable url=http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-lang/scala-reflect/2.10.2/ivys/ivy.xml
unreacheable url=http://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.2/scala-reflect-2.10.2.pom
unreacheable url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-reflect/2.10.2/ivys/ivy.xml
`
<br>
`
unreacheable url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-swing/2.10.2/ivys/ivy.xml
unreacheable url=http://repo.typesafe.com/scalasbt/sbt-plugin-releases/org.scala-lang/scala-swing/2.10.2/ivys/ivy.xml
unreacheable url=http://repo1.maven.org/maven2/org/scala-lang/scala-swing/2.10.2/scala-swing-2.10.2.pom
unreacheable url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-lang/scala-swing/2.10.2/ivys/ivy.xml
`

**Comment by huangzhendong** [comment]
@viktorklang I'm sorry, what you said is not what I really want, I really don't know why a 2.10.4 akka need 2.10.2 scala environment.

**Comment by hepin1989** [comment]
sbt need that,what are you working for,offline....

**Comment by huangzhendong** [comment]
The problem have been solved by following the site http://stackoverflow.com/questions/22966086/use-sbt-offline-with-file-based-repository @hepin1989

**Comment by ktoso** [comment]
Closing the ticket then. 
It's not really an Akka issue - still glad you found your answer :)
