### ISSUE TITLE
failed: various cluster tests when using multi lanes

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21570]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/165/
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/166/
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/167/
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/168/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7757/consoleFull

**Comment by drewhk** [comment]
I guess this is still relevant as we have not yet enabled multiple-lanes in test?

**Comment by patriknw** [comment]
yes, still valid. the performance improvements doesn't change this.

**Comment by patriknw** [comment]
Obsolete, I guess
