### ISSUE TITLE
websocketClientFlow example does not send TextMessage.Streamed

### ISSUE THREAD

**Issue by angiolep** [akka/akka#21607]
I'm running the example that comes with ``websocketClientFlow`` documentation

http://doc.akka.io/docs/akka/2.4.11/scala/http/client-side/websocket-support.html#websocketclientflow

The only thing I'm trying to do differently is sending a ``TextMessage.Streamed`` (for example a _"huge message"_) rather than a ``TextMessage.Strict("hello world!)``

```scala
// val outgoing = Source.single(TextMessage("hello world!"))
val outgoing = Source.single(TextMessage(Source.single("... huge message ...")))
```

Unfortunately it doesn't work. The client won't send any message. It seems the source is not consumed for reasons I cannot understand :-(

Could that be a bug?

**Comment by patriknw** [comment]
Akka Http has been moved to a separate repository: https://github.com/akka/akka-http. Please create the ticket there.
