### ISSUE TITLE
[http] Support Unicode in URIs

### ISSUE THREAD

**Issue by eiennohito** [akka/akka#21608]
I was playing with Akka Http by writing a small crawler, but found out the hard way that there exist URLs which are utf-8 encoded, but non-escaped.Non-English internet has lots of them.  It seems that the current standard for URLs is https://url.spec.whatwg.org/ and it allows non-escaped utf-8 in URLs. There are internationalized URLs at wild as well.

I had to use another URL parsing library, which was a mixed experience.

**Comment by eiennohito** [comment]
This belongs to http repo at least, sorry.

**Comment by ktoso** [comment]
Yep, thanks for reopening there
