### ISSUE TITLE
ReadMajority/WriteMajority with a minimum cap

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21618]
For small clusters (<7) it the risk of membership changes between a WriteMajority and ReadMajority and is rather high and then it would be nice to specify minimum number of nodes (and cap that by total number of nodes).

E.g. `WriteMajority(minCap = 5)`
N = total number of nodes
N = 3 => 3
N = 4 => 4
N = 5 => 5
N = 6 => 5
N = 7 => 5
N = 8 => 5
N = 9 => 5
N = 10 => 6
N = 11 => 6
N = 12 => 7

This is something we should use in Cluster Sharding ddata mode.

**Comment by inakov** [comment]
PR is #22069. Cheers! :)
