### ISSUE TITLE
Streams-testkit expectNextPF method returning self pointer (Probe.this.Self)

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka#21614]
Sometimes it's needed to pattern match expected object and retain ability to chain streams test methods.
Like this:
```scala
Source.single(SomeCaseClass(1, "someVal"))
.runWith(TestSink.probe)
.expectNextPF{
      case SomeCaseClass(_, "val") => 
}.expectNoMsg()
```
Now expectNextPF returns PF return type, it would be nice to make one more method returning self pointer.

**Comment by manonthegithub** [comment]
I can try implement this if it's ok

**Comment by patriknw** [comment]
@manonthegithub That's very welcome, thanks!

**Comment by manonthegithub** [comment]
what branch is better to pick? release 2.4 or master?

**Comment by manonthegithub** [comment]
or maybe another for fork

**Comment by patriknw** [comment]
For your fork you can create a wip branch from master and the create a Pull Request with master as target.
