### ISSUE TITLE
Memory leak when posting requests to akka-http without consuming the response

### ISSUE THREAD

**Issue by jeroentervoorde** [akka/akka#21621]
Hi,

I think i discovered a memory leak when sending a lot of posts requests to a server without consuming the response and just closing the connection. 

I am using akka-http 2.4.11 and scala 2.11.8

We've ran into in issue because we're using a proxy which duplicates traffic to staging and dev and also does not read the response. Our application goes OOM after a few hours.

I created a project to reproduce the issue here: https://github.com/jeroentervoorde/akka-http-memory-leak.git

This consists of a Client and a Server application. These can be run from Idea

Client posts 10 requests to a socket and closes the socket. This is repeated 4242 times (i used this number to be easily recognizable in yourkit)

For each loop some objects remain allocated and are never garbage collected.

Here are some yourkit screenshots of Server after running the Client:

Initial: 
filtered on "Stage"

![image](https://cloud.githubusercontent.com/assets/3625507/19073221/22daacc2-8a3a-11e6-853a-6191ddfc4ed6.png)

filtered on "Error"
![image](https://cloud.githubusercontent.com/assets/3625507/19073252/4936231a-8a3a-11e6-8800-ebc5bf9224ee.png)

After running Client:  

filtered on "Stage"
![image](https://cloud.githubusercontent.com/assets/3625507/19073998/42619cc8-8a3e-11e6-8d06-5faa4bcd76c8.png)

filtered on "Error"
![image](https://cloud.githubusercontent.com/assets/3625507/19074048/81a474b4-8a3e-11e6-8283-d63917b97a8c.png)

filtered on "Actor"
![image](https://cloud.githubusercontent.com/assets/3625507/19074222/81f83c4c-8a3f-11e6-9af6-ac9a891598b4.png)

**Comment by johanandren** [comment]
Hi @jeroentervoorde thanks for the thorough report, this is however known and documented (see the big red warning box up top in this doc section: http://doc.akka.io/docs/akka/2.4/scala/http/implications-of-streaming-http-entity.html), we have a couple of tickets related to auto-consuming the request/response entities akka/akka-http#88 that you can follow.

Also, note that akka-http now has its own repository and tickets over at https://github.com/akka/akka-http

**Comment by jypma** [comment]
@johanandren Looks like the test code should be consuming the entity correctly, as it unmarshals the whole thing to `String`:
```
pathPrefix("ping") {
      post {
        entity(as[String]) { str =>
          complete( (StatusCodes.OK, "pong") )
        }
      }
    }
}
```
so something might be up here anyways.

**Comment by johanandren** [comment]
I thought the memory leak report is about the client though?

**Comment by jypma** [comment]
Ah. Yes, the issue text does somewhat say that. However, the linked test client isn't even written in akka (it's writing to a plain `Socket`, see [here](https://github.com/jeroentervoorde/akka-http-memory-leak/blob/master/src/main/scala/Client.scala)). @jeroentervoorde is is the client or server that's leaking?

**Comment by johanandren** [comment]
Oh, you are right.

**Comment by johanandren** [comment]
I'll move the ticket over to akka-http though.
