### ISSUE TITLE
Allow customize response that is generated in akka http when a request timeout is exceed 

### ISSUE THREAD

**Issue by matheuslima** [akka/akka#21638]
Today, the response generated looks like:
```
    HttpResponse(StatusCodes.ServiceUnavailable, entity = "The server was not able " +
      "to produce a timely response to your request.\r\nPlease try again in a short while!")
```
I need add some headers to all responses generated from my server, but the directive respondWithHeaders seems not work with timed out responses, due the fact the default response is injected by akka http server.

**Comment by ktoso** [comment]
How bout `mapResponse` though?

**Comment by ktoso** [comment]
Also, you can `addHeaders { Route.seal(my route) }`, forgot actual name for addheaders, but you get the idea. Sealing is important, it'll give the actual response to the outer route instead of a rejection.

Also, please open Akka HTTP issues here: github.com/akka/akka-http, thanks.

**Comment by ktoso** [comment]
I moved the issue to Akka HTTP
