### ISSUE TITLE
move samples to separate repository

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21639]
- [x] (https://github.com/akka/akka-samples) move akka-samples to a separate akka/samples repository
  - [x] (https://github.com/akka/akka/pull/22288) this requires that code inclusion snippets from the samples are moved to akka-docs
- setup build that is using latest snapshot of Akka
- move (copy) Activator templates to same repository (now located in typesafehub)
- publish all those with code sample server
- replace links to Activator templates with links to example code server

**Comment by ktoso** [comment]
FYI @corruptmemory

**Comment by patriknw** [comment]
also, update sbt versions

**Comment by johanandren** [comment]
Also, look into seeds/the recent `sbt new` to create Akka templates

**Comment by ktoso** [comment]
This is done I think?
