### ISSUE TITLE
DData Replicator should avoid unreachable nodes

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21648]
unreachable should be selected last in read/write aggregator

**Comment by jgordijn** [comment]
There is a PR for this: https://github.com/akka/akka/pull/22063

**Comment by jgordijn** [comment]
Can this issue be put on milestone 2.5.0?

**Comment by patriknw** [comment]
Yes, I don't think it's important enough to backport to experimental 2.4.x, unless you have a different opinion.

**Comment by jgordijn** [comment]
I agree under the assumption that 2.5.0 will become available in Q1.

**Comment by patriknw** [comment]
That is in line with my plan. I would like to have most things ready by the end of January, and releasing a milestone then. Then it might be some minor polish left until we ship the first release candidate.

**Comment by jgordijn** [comment]
Awesome, good to hear that.
