### ISSUE TITLE
ThreadPoolExecutorConfigurator could not specify the synchronousQueue

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#21640]
currently the default is only linkedBlockingQueue,If I want to configure some CachedThreadPool like thing,then I can't.

**Comment by patriknw** [comment]
Do you mean this: https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala#L359

It supports "array" and "linked".

It is possible for you to configure another `ThreadPoolExecutorConfigurator`, see https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala#L325

Thereby you can create your own subclass of `ThreadPoolExecutorConfigurator` that supports some other queue.

Does that solve the problem?

**Comment by hepin1989** [comment]
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala#L356

How about set the task queue to `synchronousQueue ` when the size is zero ?

**Comment by patriknw** [comment]
`SynchronousQueue` doesn't look like it's in line with what we would recommend. What is the use case?

**Comment by hepin1989** [comment]
The user case is to retrieve an configured ThreadPoolExecutor with have an upper bound and act as CachedThreadPool,then I could use that to do some blocking IO.but when the it's busy I may want to reject that task or,using caller run witch will block the actor then ASAP.

Another concern is that we could configure the `ThreadPoolConfig` with method call to make it use `SynchronousQueue ` ,but we could not configure it with application.conf,aka,not symmetrical.

**Comment by patriknw** [comment]
I don't want to hand out that gun to users. You can create your own `ThreadPoolExecutorConfigurator` if you need this.

**Comment by hepin1989** [comment]
Yes,then users may shoot them self:),then I think I could close this issue,any way,another user which want to do this kind of thing will found this records too:)
