### ISSUE TITLE
Multipart-Form-Data in akka-http, missing quotes in Content-Disposition field

### ISSUE THREAD

**Issue by KrzyMucha** [akka/akka#21656]
When we use akka-http for http request with following code:
```
Multipart
            .FormData(Multipart.FormData.BodyPart("file",
                HttpEntity.Strict(MediaTypes.`image/jpeg`, ByteString("test")), Map("filename" -> "somefile.jpeg"))).toEntity()
```
Then Http request is as follows
```
User-Agent: [akka-http/2.4.8]
Transfer-Encoding: [chunked]
Host: [localhost:8089]
Content-Type: [multipart/form-data; boundary=xWtacaNwjOWLKFExaR8fOv6Q; charset=UTF-8]

--xWtacaNwjOWLKFExaR8fOv6Q
Content-Type: image/jpeg
Content-Disposition: form-data; filename=somefile.jpeg; name=file

test
--xWtacaNwjOWLKFExaR8fOv6Q--
```
Parameters **filename** and **file** are without quotation marks. However following HTTP specification this params should be quoted. As result some servers (ex. "django" app) are not able to see attached files.

**Comment by ktoso** [comment]
Please open the issue on github.com/akka/akka-http instead, sinve the project has moved.

AFAIR there is no need to quote these according to the https://tools.ietf.org/html/rfc6266 spec

```
     filename-parm       = "filename" "=" value
                         | "filename*" "=" ext-value

       value                   = token | quoted-string
```

notice the `|` there.

Let's please continue in the right repo.
