### ISSUE TITLE
A problem of message performance between cluster nodes

### ISSUE THREAD

**Issue by HuanLinying** [akka/akka#21657]
I‘m using akka system in OpenDaylight SDN controller.  I have made a performance test of cluster work and there were lots of cross-node communication. But I found that the message performance between 2 cluster nodes is just about 10K ping-pong messages per second in our environment, not as good as we expected. Then I did some analysis of the procedure, it seems that the EndpointWriter actor and EndpointReader actor are the bottleneck of whole system.

I've tried to optimize the message de/serialization, but the performance not changed too much.

I'm not clear that the message performance between cluster nodes should be?Or do you guys have any opinion about the performance optimizing.

**Comment by patriknw** [comment]
You should try the new Akka Remoting that we included in 2.4.11. See announcement: https://groups.google.com/d/msg/akka-user/G5kebNNmBjc/u5rQLfi-AAAJ

With that we have measured 630,000 msg/s. See https://groups.google.com/d/msg/akka-user/JLbLrLh3vIg/twhLMRg7CQAJ

**Comment by HuanLinying** [comment]
The new Remoting looks very impressive! I'll do more test on it.

But  I guess the "630,000 msg/s" should not be ping-pong test result.

**Comment by patriknw** [comment]
That is one-way. It is with https://github.com/akka/akka/blob/master/akka-remote-tests/src/multi-jvm/scala/akka/remote/artery/MaxThroughputSpec.scala

**Comment by patriknw** [comment]
Let us know how it goes, e.g. in https://gitter.im/akka/dev. Closing this issue now.
