### ISSUE TITLE
Try Goldy - DTLS proxy for new Artery and document if useful

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21665]
Goldy - DTLS proxy https://developer.ibm.com/open/goldy/

**Comment by ktoso** [comment]
Duplicate of https://github.com/akka/akka/issues/21666

**Comment by volkerstampa** [comment]
I wonder if using goldy makes sense at all?!? As far as I understand it can only act as a _secure_ proxy for a server and thus requires an DTLS enabled client. Unlike ghostunnel (for TLS) it does not have a [client and server mode](https://github.com/square/ghostunnel#full-tunnel-client-plus-server). But maybe I am missing something!?!

**Comment by patriknw** [comment]
@volkerstampa I think you are right. I had the same thought when I read up on it some time ago. Let us know if you know (or find) a better alternative.

**Comment by volkerstampa** [comment]
@patriknw Thanks for confirming. TBH I do not have a better alternative, maybe except for adding a _client_-mode to goldy. However personally I have no plans to tackle this atm.
