### ISSUE TITLE
Try ghostunnel and document if useful

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21664]
https://github.com/square/ghostunnel

For Akka remoting (old)

**Comment by ktoso** [comment]
Similar ticket for the new remoting and a DTLS proxy: https://github.com/akka/akka/issues/21665

**Comment by ktoso** [comment]
Duplicate of https://github.com/akka/akka/issues/21666

**Comment by ktoso** [comment]
See also https://github.com/akka/akka/issues/21666 for Artery

**Comment by raboof** [comment]
This seems to solve something slightly different
