### ISSUE TITLE
Snapshot files showed a size of 0 bytes on restart after shutdown virtual machine

### ISSUE THREAD

**Issue by HeYunBo** [akka/akka#21675]
I‘m using akka system in OpenDaylight SDN controller which is running in a virtual machine(Centos) , shutdown(poweroff) the virtual machine when I was creating 100K entries with test script which triggered save snapshot per 100 entries , and then restart the virtual machine, I found all snapshot files written just before power off showed a size of 0 bytes

This happened only in virtual machine environment but it was normal in physical host environment or restart virtual machine with reboot command

Test results as follows 

virtual machine environment + power  off    Exception
virtual machine environment + reboot          Normal
physical host environment + power off         Normal
physical host environment + reboot              Normal

**Comment by johanandren** [comment]
What snapshot store are you using? The `LocalSnapshotStore` is only provided for use in tests/dev scenarios not for actual use in a production application.

**Comment by johanandren** [comment]
Also in general, please use the [akka-user mailing list](https://groups.google.com/forum/#!forum/akka-user) or the [gitter channel](https://gitter.im/akka/akka) for questions and use the issue tracker only for issues and feature tickets.

This could be a border case, but discussing it on gitter to confirm it actually is a bug before opening a ticket is often a good idea.

**Comment by HeYunBo** [comment]
I am using Akka 2.4.8, but I don't specify the snapshot store plugin in akka.conf,  if The LocalSnapshotStore is only provided for use in tests/dev scenarios, what should I use in a production application

**Comment by johanandren** [comment]
Please use the mailing list or the gitter channel for questions, thanks!
