### ISSUE TITLE
LevelDB journal never removes persistence IDs

### ISSUE THREAD

**Issue by Sushisource** [akka/akka#21677]
I'm not 100% sure that I'm right here, but in my reading of the code it appears that even if you delete all the events for a given persistence ID, the mapping of numerical_id->persistence_id remains in the journal.

In my application (and I suspect this is not uncommon) we will create many actors with unique persistence IDs, which will have a medium lifespan. They rely on the Journal for recovery, but when they terminate successfully they clean up all persistence data, since they will never be needed again.

Obviously, it would take a very very long time or many, many actors -- but the leveldb files would seemingly grow unbounded even though you thought you were cleaning up after yourself, because those id->id mappings are never removed.

Feel free to close if I'm wrong, or this is by design for some reason.

**Comment by ktoso** [comment]
Thanks for reporting.
Have not yet looked at it in depth - heading over to a wedding just now - but wanted to remind you that the leveldb plugin is not intended for production use. It's just for local and "shared journal" testing in multinode specs. This is documented. For prod you should consider cassandra or some other real distributed datastore.

**Comment by Sushisource** [comment]
The docs are pretty clear about not using the shared journal in production, but don't say that you shouldn't use the local journal. http://doc.akka.io/docs/akka/2.4.11/scala/persistence.html#Pre-packaged_plugins

In fact, the docstring here explicitly states the local version can be used in production:
https://github.com/akka/akka/blob/4a7cd147313404eb8137e56163e54f06c23640d0/akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbJournal.scala#L20

That aside, yeah, it's still probably not the best choice for production but in our case it's a great fit for now.

Probably a good choice to update the docs if it is indeed recommended to avoid using it in prod.

In any case, I think the bug is probably still worth fixing. I don't have much experience with the leveldb api but it looks simple. I could contribute a patch if wanted.

Thanks!

**Comment by ktoso** [comment]
> Warning
> A shared LevelDB instance is a single point of failure and should therefore only be used for 
> testing purposes. Highly-available, replicated journals are available as Community plugins.

If you've found where the bug is fixing it definitely would be nice, thanks in advance!

**Comment by Sushisource** [comment]
@ktoso Yes, it clearly says not to use the shared journal - it's not clear that the single-instance journal is not to be used for production. Plus the docstring in the code I linked to says "for production".

I'll take a look at making a PR when I've got some time. Thanks!

**Comment by ortigali** [comment]
In journal api:
> Journal must maintain the highest sequence number and never decrease it.

Automatic determining to clean persistence id is not proper way in deleteMessages method

PersistentActor should support additional method to clean up all persistence data, i.e. journal and snapshot store. It gives a convenience to write temporary PersistentActor.

**Comment by patriknw** [comment]
I agree that it should be a separate api. It would be great to see a proposal for that @ortigali

**Comment by ortigali** [comment]
Add method to PersistentActor

```scala
  def transient: Boolean = false
```
User can ovveride it. if this method returns true, actor sends clearPersistentId message to journal and snapshoter.

**Comment by nick-nachos** [comment]
My team has stumbled across an issue with leveldb journal compaction that may actually be the exact same thing as this issue, so I'm posting here to avoid possible duplication.

We are using leveldb as the "backend" for a persistent actor that persists batches of messages, which are then forwarded to a second actor for consumption. Once consumption is confirmed, the persistent actor deletes these batches from the journal. Running a simulation where 2,000 messages of 1KB in size were being generated per second, and having the consumer actor consume batches of 10,000 messages, we noticed an "explosion" of the journal size. Although the 10K batches were being deleted upon confirmation, the journal ended up reaching an alarming size of 7GB in a matter of a couple of minutes. The expansion of the journal size seemed to lead to a drastic loss of read/write performance as well (persistence and journal query)

After doing some digging into the issue, we came across a leveldb api method named **compactRange** available via JNI, which effectively handles the journal cleanup. We then modified the leveldb related trait included in akka-persistence, and had the **deleteMessages** method execute a **compactRange** every 2-3 calls. The result was astonishing, as the journal size was reduced to a maximum of 150MB (i.e. closer to the actual size of the un-deleted messages in the journal), which in turn restored read/write performance to normal. 

Given the above, we were wondering whether the akka team would consider dealing with the issue in the near future, by including the **compactRange** behavior in the leveldb trait and/or exposing it to the user-space (via configuration for instance) either as part of the **deleteMesages** functionality or as standalone. If not, would you be positive to the possibility of a pull request on this issue?

**Comment by patriknw** [comment]
@nick-nachos That is great finding. A pull request is very welcome
