### ISSUE TITLE
Akka HTTP single requests hang forever when host is invalid/unreachable

### ISSUE THREAD

**Issue by bfil** [akka/akka#21679]
I've managed to strip down the core issue to the following snippet:

```scala
import akka.http.scaladsl.Http
import akka.http.scaladsl.client.RequestBuilding._
0 to 10 map { i =>
  Http().singleRequest(Get("http://someinvaliddomain.com")) map {
    res => println(s"Got Response: $i")
  }
}
```

This looks relatively straightforward, I would expect to get all my 10 responses back, but after 4 responses due to the invalid host no more requests will ever be sent to the specific host.

```
Got Response: 0
Got Response: 3
Got Response: 1
Got Response: 2
```

I've noticed this behaviour when trying to hit a slow service which times out from time to time, after 4 gateway timeouts sent from nginx no more requests were sent to the host. I'm not 100% sure in what case this would get stuck though, some clarification on the matter would be useful.

I've noticed a few related issues like this one: https://github.com/akka/akka/issues/21098

That have been closed and linked to akka meta: https://github.com/akka/akka-meta/issues/27

But I would expect such trivial example and `Http().singleRequest` to take care of the corner cases for me since it returns a `Future[HttpResponse]` rather than a stream.

**Comment by ktoso** [comment]
What's the response though?
Have you read
http://doc.akka.io/docs/akka/2.4.8/scala/http/implications-of-streaming-http-entity.html
?

**Comment by bfil** [comment]
@ktoso don't think so, I'll have a read.

The response of the above is:

```scala
HttpResponse(200 OK,List(Server: nginx, Date: Sun, 16 Oct 2016 13:00:46 GMT, Connection: close, Expires: Sun, 16 Oct 2016 13:10:46 GMT, Cache-Control: max-age=600),HttpEntity.Chunked(text/html; charset=UTF-8),HttpProtocol(HTTP/1.1))
```

Gets stuck after 4, but if I change the host to let's say `http://google.com` then it doesn't get stuck and processes all 10. Can't see the difference there.

**Comment by ktoso** [comment]
I moved this issue to the right spot for it, please track it here: https://github.com/akka/akka-http/issues/397
Akka HTTP has it's own repository.
