### ISSUE TITLE
flatMapConcat ignores dispatcher attributes of substream

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21681]
When providing the dispatcher attribute to stages in the inner graph in `flatMapConcat` those are ignored and the entire inner graph is materialized to run on the same actor as the stage itself (`FlattenMerge`).

Reproducer:

``` scala

  implicit val system = ActorSystem("dispatchers", ConfigFactory.parseString(
    """
      inner {
        type = Dispatcher
        executor = "thread-pool-executor"
        thread-pool-executor {
          fixed-pool-size = 1
        }
      }
    """))
  implicit val materializer = ActorMaterializer()

  val source = Source(0 to 200)
    .flatMapConcat(n =>
      Source.single(n)
        .map { t => println("expected inner: " + Thread.currentThread().getName); t }
        .addAttributes(ActorAttributes.dispatcher("inner")
    )).runForeach(n => println("expected default: " + Thread.currentThread().getName))
```

Will print `expected inner: dispatchers-akka.actor.default-dispatcher-n`

**Comment by johanandren** [comment]
Would like a confirmation from @drewhk on this one, in case there is a good reason why it should behave like this.

**Comment by patriknw** [comment]
ping, @drewhk

**Comment by drewhk** [comment]
It uses the subFusingMaterializer, which simply fuses the materialization into the host actor. I believe this is either the same bug as the ignored dispatcher Attribute, or maybe just a variant on it.

**Comment by drewhk** [comment]
This was actually fixed: https://github.com/akka/akka/pull/21805
