### ISSUE TITLE
error in LoggingAdapter is too polymorphic

### ISSUE THREAD

**Issue by nurumaik** [akka/akka#21683]
It's easy to mix arguments in `error(cause: Throwable, message: String)` and get `error(template: String, arg1: Any)` called instead. I think these functions should have different names to prevent confusion or there should be some sort of warning like:
```scala
@some_annontation_that_generates_warning("Throwable should be first argument if you want to use it as cause")
def error(template: String, arg1: Throwable) = error(template, arg1 asInstanceOf[Any])
```

**Comment by patriknw** [comment]
what annotation would that be? `deprecated` ?

**Comment by johanandren** [comment]
Note that we cannot change the names because that would break backwards compatibility.

**Comment by nurumaik** [comment]
Sorry, I expected scala to have more general annotation for warnings. Custom method with `deprecated` is closest to what I want, but that can cause even more confusion :(

**Comment by ktoso** [comment]
We also had a different discussion (which I can't find now though...) about removing the Akka provided loggin layer in favour of just exposing slf4j or log4j2... Nothing decided yet, but I'd rather change logging things only if there is a high bang-for-buck ratio :)

Propose to close as for this one not sure there's anything really helpful to do right now?
