### ISSUE TITLE
Events are 'stuck' in a persistent actor under low throughput 

### ISSUE THREAD

**Issue by eugenemiretsky** [akka/akka#21689]
When testing a  persistent actor with a low throughput (one command at a time) event sometimes get "stuck" and are not processes until the next command is sent. 

I suspect that it has to do with batching in EventSourced - events get batched before being sent to the persistent store. FlushBatch is getting called inside aroundReceiveComplete, which explains why the batch gets flushed when the 2nd command is sent. 

Is there a way to tune, or turn off batching?

**Comment by ktoso** [comment]
- What persistence journal?
- Are you using persist or persistAsync or a mix?
- What does "low throughput" mean in your case?
- Could you explain more about what you mean with "stuck"? By "command is sent" I assume you mean "event is stored", i.e. persist call happens?

**Comment by eugenemiretsky** [comment]
1) LevelDB
2) Persist
3) low throughput - test load. Generating 1 request at a time manually. 
4) By stuck I mean that all the code before persist() is executed,  however none of the code in the call back is executed. The callback is executed only after I send another command that triggers another persist call.

**Comment by patriknw** [comment]
Sounds interesting. Do you have a reproducer?

**Comment by eugenemiretsky** [comment]
Working on a reproducer. 
Persist is getting called in a Future. Could that be the issue?

**Comment by patriknw** [comment]
Yes, that is not allowed. Must be done in the actor's receive thread. Pipe the result of the future back to the actor and persist from receiveCommand

**Comment by ktoso** [comment]
Not a bug IMHO if persist() was called from a Future, incorrect usage though.
I added a more explicit warning about this: https://github.com/akka/akka/pull/21699
