### ISSUE TITLE
AddressFromURIString in unnecessary restrictive

### ISSUE THREAD

**Issue by akornev** [akka/akka#21680]
Any valid URI should be convertible to an Address. 

It looks like, the current implementation restricts the valid URI forms to just the one supported by Akka Remoting. For example, it doesn't accept "schema://system:port" (due to presence of "port") or "schema://system@host" (due to absence of "port"), etc. Such restriction seems unnecessary and, more importantly, makes the parser unusable with RemoteActorRefProvider implementations that use a different schema to identify the location of the actors.

**Comment by ktoso** [comment]
If you want generic URI's why not use Akka HTTP's URI? That's exactly what it is, whereas the mentioned `AddressFromURIString` is just that, for Akka's use in remoting.

**Comment by akornev** [comment]
Konrad, thanks! 

It's unfortunate that Akka only allows TCP/IP-based implementations of remoting ActorRefProvider. I was hoping that since `AddressFromURIString` and the `Address` class it returns are defined in a supposedly remoting-agnostic akka-actor module I could use any valid URI to represent actor locations. Doesn't seem to be the case. To complicate things even further, it looks like `Address` decides on its scope based only on presence or absence of the host name (see `Address.hasLocalScope` and `Address.hasGlobalScope`) which again seems to be pretty much coupled to Akka's own implementation of Remoting...

What would be my options if I were to provide an ActorRefProvider implementation that uses a different (although JDK's URI-compliant) way of identifying actor resources? For example, the actors are deployed on a collection of logical nodes (identified by some logical names) where the things like hosts and ports are irrelevant.

**Comment by johanandren** [comment]
> if I were to provide an ActorRefProvider implementation

Note that with the new remoting (added in 2.4.11, http://doc.akka.io/docs/akka/2.4.11/scala/remoting-artery.html) we are moving away from pluggable transports, so it might not be a good investment to build such a remoting implementation, if that is what you are thinking of.

**Comment by akornev** [comment]
It's indeed an ActorRefProvider implementation that I have in mind and not a pluggable remoting Transport.

**Comment by patriknw** [comment]
The ActorRefProvider is a very internal thing that is not intended to be pluggable. Can we please take a step back. What is the use case you are trying to solve?

**Comment by akornev** [comment]
Patrik, in what sense is it "very internal"? It looked very much like something that can be extended. Too bad if it's not the case. In any case, my point (for this ticket) is that `AddressFromURIString` and `Address` could be improved by making them less leaky. I felt that too much of the internal implementation bubbles up to the API level (like those URI restrictions, or Address' simplistic scoping logic).

I'm investigating the idea of being able to deploy actors on top a cluster implementation from a third party.

**Comment by patriknw** [comment]
It has several methods to be implemented that don't even have public classes in their signatures (ActorSystemImpl).

You intend to implement your own RemoteActorRefProvider/ClusterActorRefProvider? Also your own network protocol? I think you underestimate that task. Akka is not designed for that.
