### ISSUE TITLE
MergeHub doesn't fail the Source when one of the inputs fails a Sink

### ISSUE THREAD

**Issue by atvictor** [akka/akka#21693]
The `onUpstreamFailure` method of the `MergeHub` stage only throw an exception and doesn't fail the Source as it's written in the ScalaDoc:

> If one of the inputs fails the Sink, the Source is failed in turn

**Comment by jrudolph** [comment]
Thanks @atvictor. It seems the Scaladoc is wrong as there is a test in HubSpec that asserts the opposite:

```scala
    "keep working even if one of the producers fail" in assertAllStagesStopped {
      val (sink, result) = MergeHub.source[Int](16).take(10).toMat(Sink.seq)(Keep.both).run()
      EventFilter.error("Upstream producer failed with exception").intercept {
        Source.failed(TE("faling")).runWith(sink)
        Source(1 to 10).runWith(sink)
      }

      result.futureValue.sorted should ===(1 to 10)

    }
```

**Comment by atvictor** [comment]
Ah too bad, I would prefer the ScalaDoc version: fail the source if one of the input fails.

Maybe a mechanism like the one in Merge with `eagerComplete` can be achieved?
Is it useful for anyone apart me?

**Comment by patriknw** [comment]
You can do that by connecting them with `watchTermination` and `KillSwitch`.

**Comment by atvictor** [comment]
But to obtain the `KillSwitch` I will need to materialize each of the flow going to the `MergeHub` sinks? I don't want that because the unique source of each of my flows open up a connection and I don't want to open N connections.

```
Source -> Partition -> Flow 1, Flow ..., Flow N -> MergeHub Sink
```

Meanwhile I found a solution, I will implement a custom `Partition` stage to make it eagerly complete when one of its output complete.

**Comment by patriknw** [comment]
I was thinking about a shared KillSwitch, but perhaps I misunderstood something

**Comment by atvictor** [comment]
Thanks but I can't see how I can cleanly integrate a shared kill switch to react to stage failures.

Adding an `eagerComplete` flag in the `Partition` stage is much simpler for my use case. And if it's useful for other people I can try the PR way :)

**Comment by nadavwr** [comment]
The MergeHub example in the docs is a publish-subscribe channel. The MergeHub.source() is wired to a BroadcastHub.sink() and is running "hot"—to borrow from Rx parlance.

The materialized sink resulting from the MergeHub is used (together with the source materialized from the BroadcastHub) to form individual subscriptions.

Let's imagine this was used to construct a simple chatroom. A failure between the MergeHub.source() and BroadcastHub.sink() should bring down the whole chatroom (subscription channel stream) and boot out the clients (individual subscription streams). A failure in an individual client subscription stream (from user input up to and including an individual materialized sink, then from materialized source until user output) is a narrow failure—it should fail the individual chat client subscription stream, but leave the subscription channel stream, and all the other live client subscription streams that hadn't failed, up and running.

I don't understand your mention of the Partition stage. As much as you could compare MergeHub and Partition they are almost opposites.

If you require "all or nothing" failure for all streams connected to the MergeHub, you can achieve as @patriknw outlined:

1) Obtain a killswitch for the stream emitting from MergeHub.source:
Either (A) create a SharedKillSwitch (outside the stream), and make sure the stream passes through it; or (B) pass the stream through a KillSwitches.single and keep the materialized UniqueKillSwitch.
2) In all your individual streams connected to the materialized sink, use watchTermination() to materialize a Future[Done]. Whenever that future fails, trigger the killswitch to terminate the subscription channel stream—this should cascade to all streams connected to the MergeHub.

If you want eager completion regardless of failure, you can also trigger the killswitch when the future succeeds. This will have the effect of terminating anything connected to the MergeHub upon completion of the first upstream producer.
