### ISSUE TITLE
make akka.stream.impl.io.ByteStringParser public

### ISSUE THREAD

**Issue by yaroot** [akka/akka#21691]
`akka.stream.impl.io.ByteStringParser` is very useful for writing parsers for binary flows, akka-http internally use it for gzip and deflate decompressors. If people concerned about binary compatibility (mentioned by @johanandren), we could put it in akka-stream-contrib first.

**Comment by johanandren** [comment]
I don't think we could put it in contrib as we have an internal dependencies on it and we do not want to force akka-http to depend on streams-contrib.

WDYT @ktoso?

**Comment by yaroot** [comment]
@johanandren second thought, ByteStringParser is not generic enough, but still it's nice to have some helper for writing decoders (like ByteToMessageDecoder in netty).

I think we could close the ticket now or rename the title to _make a more generic ByteStringParser_

**Comment by ktoso** [comment]
I don't think that specific class should be exposed, instead we should eventually provide better support for decoding/endocing binary protocols. This is something @drewhk was experimenting and had ideas around.

Let's close this ticket and you can open a new one requesting support for better handling of protocols. You can ping @drewhk but he's currently on holidays for a week or two more.
