### ISSUE TITLE
Allow PersistentActor to say "ok, recovered 'enough'" during recovery

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21709]
Interesting idea which relates to replaying to given event time.
Let's say our events contain timestamps. For an app we want to replay to given event time, and then maybe do a simulation from that point on "what would happen if..." etc.
For this to happen the Actor has to get the event, look at the event time, and at some point say "yeah, this far is enough". Current APIs don't allow this since for snapshots we do have time, but it's wallclock time, and for events we don't have time at all - only sequence numbers (for the `Recovery()` object).

Would be interesting to provide such replay capability.

**Comment by ktoso** [comment]
Note: For views we can model this via Persistence Query and doing a `...eventsForPersistenceId` combined with a `.takeWhile(_.event.eventTime <= TargetTime)`.
Perhaps this is also something we could document

**Comment by patriknw** [comment]
Marking as new, until we have decided it is a good idea.

**Comment by ktoso** [comment]
Right, agree - needs some discussion first. Perhaps recommendation should be using Query here, let's chat about it once we have time.

**Comment by patriknw** [comment]
This is a very dangerous feature, in my opinion. If using `persist` after not replaying all events you have a mixed the event stream with old and new events that doesn't make sense if you later replay all events. I don't think we should hand out this gun.

It's already possible if you know what you are doing, by simply ignoring all events after the found point in the replay.

I think such simulations are better done with `eventsByPersistenceId`

**Comment by drewhk** [comment]
Yeah, I agree with @patriknw

**Comment by ktoso** [comment]
Yeah, convinced. Closing then
