### ISSUE TITLE
Content-Type header disappears with custom content type value

### ISSUE THREAD

**Issue by Vadi** [akka/akka#21702]
Given I've a route like this -- 
```
path("sid" / IntNumber) { id =>
    post { ctx =>
      ctx.complete(ctx.request.headers.mkString(","))
    }
}
```
When I execute -
```
> curl -H "Content-Type: application/json" -d'{}' -XPOST http://0.0.0.0:8080/sid/123
```
It returns -
```
Host: 0.0.0.0:8080,User-Agent: curl/7.49.1,Accept: */*,Timeout-Access: <function1>%
```
Notice that `Content-Type` header is not returned. However, check this request &mdash;
```
curl -H "Blah: Blue" -H "Content-Type: moon" -d'{}' -XPOST http://0.0.0.0:8080/deployment/123
```
This one returns `content-type: moon` as expected.
```
Host: 0.0.0.0:8080,User-Agent: curl/7.49.1,Accept: */*,Blah: Blue,content-type: moon,Timeout-Access: <function1>%
```

Not sure what the issue is -- How content type value is disappearing when a valid value is sent out. I am using `headerValueByName` directive to implement a custom content type.

**Comment by ktoso** [comment]
ContentType gets special treatment and is stored in `request.entity.contentType`.
I agree though it can be confusing, perhaps we can simplify this so it's the same for all cases

**Comment by ktoso** [comment]
Notice this is in the wrong repo - please report HTTP issues over here: github.com/akka/akka-http
