### ISSUE TITLE
Multiple foldAsync specs are testing mapAsync.

### ISSUE THREAD

**Issue by Silv3rcircl3** [akka/akka#21711]
https://github.com/akka/akka/blob/09a6d2ede12991c1fc97aa6f0b6fab7c4651289b/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFoldAsyncSpec.scala#L105

https://github.com/akka/akka/blob/09a6d2ede12991c1fc97aa6f0b6fab7c4651289b/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFoldAsyncSpec.scala#L165

**Comment by johanandren** [comment]
Good catch, thanks for letting us know
