### ISSUE TITLE
Long offset int result from EventsByTagQuery2.eventsByTag

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21722]
#21615 Added `EventsByTagQuery2` which take `akka.persistence.query.Offset` for offset rather than a long, however the result is a stream of `EventEnvelope` where offset still is a long. 

Do we need an additional `EventEnvelope2` that contains an `Offset` instead?

Ping @patriknw

**Comment by patriknw** [comment]
Right, then we need another envelope as well.
(Note that these will be cleaned up in 2.5, when we remove experimental)
