### ISSUE TITLE
Java API missing for ActorSelection.resolveOne

### ISSUE THREAD

**Issue by jypma** [akka/akka#21726]
`resolveOne` always returns scala `Future` right now. Possible resolutions:
1) introduce `ActorSelection.resolveOneCS`
2) introduce `ActorSystem.actorSelectionCS` and a Java-centric Java `ActorSelectionJava`

I'm not sure which one would be nicer... both kinda suck :)

**Comment by patriknw** [comment]
Yes, there are probably a rather many places where we use `Future` in APIs. User's can convert to CS with https://github.com/scala/scala-java8-compat (already a dependency in akka-actor).

I think we must look at it from case to case but for this example I think `ActorSelection.resolveOneCS` is most attractive.
