### ISSUE TITLE
Rewrite FileSource/FileSink and InputStreamSource as GraphStages

### ISSUE THREAD

**Issue by agolubev** [akka/akka#21732]
Basically there are more Children of SinkModule/Source module.
So let me know if all of them needs to be migrated.

**Comment by johanandren** [comment]
I started on it a while ago: #21515

**Comment by agolubev** [comment]
@johanandren I can finish it if you don't mind. S3 ticket I have plans on will take some time to coordinate and communicate - too many volunteers :)

**Comment by johanandren** [comment]
I think it's almost done actually, but there is a discussion about whether we should keep the current quirky failure behaviour (which has test coverage) or make it more sensible. Also needs some benchmarking to see if there should be some more clever stuff in there.

Anyways feel free to take it over.

**Comment by agolubev** [comment]
Ok, let me start with benchmarking. And then will check on failure behaviour

**Comment by agolubev** [comment]
Found existing benchmark and run with new and with old Source:
New
[info] Benchmark                                         (bufSize)  Mode  Cnt     Score      Error  Units
[info] FileSourcesBenchmark.fileChannel                       2048  avgt    7  7684.240 ±  831.042  ms/op
[info] FileSourcesBenchmark.fileChannel_noReadAhead           2048  avgt    7  7771.431 ± 3546.935  ms/op
[info] FileSourcesBenchmark.inputStream                       2048  avgt    7  1293.805 ±  392.974  ms/op
[info] FileSourcesBenchmark.naive_ioSourceLinesIterator       2048  avgt    7  3540.850 ± 1708.582  ms/op

Old
[info] Benchmark                                         (bufSize)  Mode  Cnt     Score     Error  Units
[info] FileSourcesBenchmark.fileChannel                       2048  avgt    7  1223.056 ±  97.279  ms/op
[info] FileSourcesBenchmark.fileChannel_noReadAhead           2048  avgt    7  1844.626 ± 224.196  ms/op
[info] FileSourcesBenchmark.inputStream                       2048  avgt    7  2739.164 ± 166.527  ms/op
[info] FileSourcesBenchmark.naive_ioSourceLinesIterator       2048  avgt    7  2866.971 ±  67.701  ms/op

For some reason old is faster. I'll rebase PR and look into

**Comment by johanandren** [comment]
I have a vague memory of someone claiming this in general regarding using nio vs old io APIs.

**Comment by ktoso** [comment]
I did a ton of benchmarks when implementing these file sink/source - yep,
the current was actually fastest AFAIR.

It's more of a question on scalability than on throughput.

-- 
Konrad Malawski

**Comment by agolubev** [comment]
Hm so @ktoso  your recommendation will be to double check this and cancel NIO PR?

**Comment by agolubev** [comment]
Switched to FileChannel instead of AsyncFileChannel and got interesting result:
```
[info] Benchmark                                     (bufSize)  Mode  Cnt     Score     Error  Units
[info] FileSourcesBenchmark.fileChannel                   2048  avgt    4  1956.150 ± 510.738  ms/op
[info] FileSourcesBenchmark.fileChannel_noReadAhead       2048  avgt    4   579.893 ±  49.399  ms/op
```

if we add inputBuffer(4, 16) explicitely it's 4 times faster. Any thoughts?

**Comment by drewhk** [comment]
I am not familiar with the benchmark. Is there fusing going on?

**Comment by agolubev** [comment]
```
[info] Benchmark                                    (bufSize)  Mode  Cnt     Score     Error  Units
[info] FileSourcesBenchmark.fileChannel                  2048  avgt    8  1498.265 ±  88.044  ms/op
[info] FileSourcesBenchmark.fileChannel_fused            2048  avgt    8   667.455 ±  12.548  ms/op
[info] FileSourcesBenchmark.fileChannel_noAhead          2048  avgt    8  1962.751 ±  29.726  ms/op
[info] FileSourcesBenchmark.fileChannel_old              2048  avgt    8  1097.538 ±  26.675  ms/op
[info] FileSourcesBenchmark.fileChannel_oldNoAhead       2048  avgt    8  2260.526 ± 117.649  ms/op
```
