### ISSUE TITLE
outgoingConnectionTls  needs to be updated to  outgoingConnectionHttps 

### ISSUE THREAD

**Issue by LtDan33** [akka/akka#21733]
In the documentation "http://doc.akka.io/docs/akka/2.4.11/scala/http/client-side/client-https-support.html#hostname-verification" it says that outgoingConnectionTls is used, but that method name seems to have changed to outgoingConnectionHttps. 

Is this the case? Should I expect the same results using this?

**Comment by ktoso** [comment]
Thanks for catching this! Yes, it's the same method / behaviour.
Would you submit a pull request fixing that typo? Thanks a lot in advance!

**Comment by ktoso** [comment]
Please submit the change to https://github.com/akka/akka-http as we moved akka http to it's own repository.

**Comment by ktoso** [comment]
Moved issue to Akka-HTTP repository: https://github.com/akka/akka-http/issues/441
(it's absolutely valid though)
