### ISSUE TITLE
Persistence: persist() does not stash when invoked while handling RecoveryCompleted

### ISSUE THREAD

**Issue by jypma** [akka/akka#21736]
I have a `PersistentActor` that wants to self-initialize like such:
```java
    @Override
    public PartialFunction<Object, BoxedUnit> receiveRecover() {
        return ReceiveBuilder
            .match(RecoveryCompleted.class, msg -> {
                if (lastSequenceNr() == 0) {
                    persist(createInitialEvent(), e -> {
                        updateSomeState();
                    });
                }
            })
            .build()
            .orElse(super.receiveRecover());
    }
```
However, incoming commands aren't stashed between persisting the `createInitialEvent()` and getting the callback to `updateSomeState()` (which does happen eventually, I think as the next command is handled).

In `EventSourcing.scala`, the reason is that the detecting of `pendingStashingPersistInvocations` isn't performed until the state reaches `processingCommands`. Perhaps a well-placed `changeState(persistingEvents)` inside `recoveryStarted(...)` or `recovering(...)` could make it work.

Otherwise, blow up if `persist()` is invoked during receiveRecover.

**Comment by jypma** [comment]
Workaround: Put the check inside `receiveCommand()` and stash there while the initial persist is happening.

**Comment by ktoso** [comment]
Not backporting, it's not critical to have this back in 2.4 I think

**Comment by patriknw** [comment]
I have backported it, because something else was depending on it
