### ISSUE TITLE
flatMapConcat/flatMapMerge do not propagate their attributes to internal stages

### ISSUE THREAD

**Issue by eiennohito** [akka/akka#21743]
[Documentation](http://doc.akka.io/docs/akka/2.4.11/scala/stream/stream-composition.html#Attributes) says that attributes should be propagated to internal stages.

**Comment by johanandren** [comment]
Duplicate or at least very closely related to #21681

**Comment by johanandren** [comment]
Note that "nested" in the sense mentioned in the docs is not the same thing as the inner materialization done in `flatMapConcat` and `flatMapMerge`.

Nesting here refers to when you combine a sink or a source with a flow and get a new sink or source and then set attributes for that.

**Comment by johanandren** [comment]
Let's discuss if the attributes actually should propagate to the inner streams in these cases, I'm not sure. If not we should probably document it more clearly. (ping @drewhk)

**Comment by eiennohito** [comment]
I do not know about built-in attributes, however user-defined ones definitely should be propagated in my opinion. I fail to see why "nesting" should differ from internal materialization here.

I was trying to implement tracing of RPC calls which are exposed as flows. In that case I would like streams to propagate my own attributes (not built-in ones) to internal ones because I think it is the most natural way to attach metadata for tracing.

**Comment by TanUkkii007** [comment]
+1 for propagate attributes to the inner streams.
In my case, blocking RPC call is exposed as a Source with dispatcher attribute and it is used with flatMapConcat. If flatMapConcat ignores substream's dispatcher, as reported in #21681, blocking operations are leaked to upstreams unless a caller explicitly specifies the dispatcher to the flatMapConcat stage.

**Comment by drewhk** [comment]
This is likely a breaking change though, so I am a bit unsure. It is likely not hard to propagate the Attributes of the host stage to the `subFusingMaterializer` as new top level Attributes, however this will be in discrepancy from manual materializations:

```scala
sourceOfSources.withAttributes(attr2).foreach(_.runWith(someSink))
```

In the above code, the running graph will *not* inherit the Attributes as foreach cannot propagate it to the implicit materializer in scope. I.e. it will work differently from the implicitly materializing flatten operators.

**Comment by eiennohito** [comment]
I think that not many people were using custom attributes (yet) otherwise this behavior would have surfaced earlier.

I believe in this case user explicitly says that he wants to materialize the graph himself. Also it is possible to override attributes for user in your example. 

For `flatMap` family this is not the case and there are no place where it is possible override or add attributes. Internal materialization inside `flatMap`s is something that is similar to implementation detail (I have this stream of sources here, so execute them somewhere, please) in contrast to explicit intent as per if your example.

**Comment by drewhk** [comment]
I am sold :)

**Comment by drewhk** [comment]
Fix is here: https://github.com/akka/akka/pull/21805
