### ISSUE TITLE
actor using actorOf not ready to use

### ISSUE THREAD

**Issue by Jaware** [akka/akka#21745]
i use a cluster router  to connect an actor of an akka cluster,but the actor need some time to be inited,is there some event which can use to show the actor is ready to use?

the code is:

```javascript
 ActorRef backend = (ActorRef) Await.result(Patterns.ask(supervisor,
				 new ClusterRouterGroup(new AdaptiveLoadBalancingGroup(
			    		  SystemLoadAverageMetricsSelector.getInstance(), Collections.<String> emptyList()),
			          new ClusterRouterGroupSettings(totalInstances, routeesPaths,
			              allowLocalRoutees, useRole)).props(), 5000), Duration.create(5, TimeUnit.SECONDS));
TimeUnit.SECONDS.sleep(5);//$$$$$$$$must sleep some time to be inited,or it is deadletter
backend.tell(n, ActorRef.noSender());//$$$$$$$$must sleep some time to be inited,or backend is deadletter
```

**Comment by johanandren** [comment]
Hi @Jaware please use the gitter channel or the mailing lists for questions and leave the bug tracker for bugs and feature tracking, thanks!

**Comment by Jaware** [comment]
where is the email address and gitter channel?

**Comment by patriknw** [comment]
https://gitter.im/akka/akka or https://groups.google.com/forum/#!forum/akka-user
