### ISSUE TITLE
Deprecate com.typesafe.sslconfig.akka classes in akka-stream

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21753]
AFAIK the purpose of the former ssl-config-akka (which is now part of akka-stream) were these:
- for akka-stream's TLS stage we needed some mechanism to configure an SSLEngine
- for HTTPS we'd like to have some configurable default TLS settings

The existing solution is this:
- introduce AkkaSSLConfig which serves as a singleton to access the ActorSystem-global default config
- reference AkkaSSLConfig in akka-stream's TLS stage to allow SSLEngine configuration

The solution has a few drawbacks:
- the TLS stage has a new dependency on AkkaSSLConfig "just" to configure an SSLEngine
- AkkaSSLConfig does more than it should, part of it is general enough to be moved to ssl-config, part of it seems to be quite specific for HTTPS
- it's somewhat unknown if ActorSystem-global configuration for _all_ TLS needs is useful at all because different usages will likely need different default settings (https, remoting, etc.)

Suggestion:
- in TLSActor (and public interface as well) replace SSLContext and AkkaSSLConfig parameters by single constructor function that directly creates an SSLEngine
- remove AkkaSSLConfig and replace by ActorSystem-global configuration for specific use cases like https only if needed and right at the point where needed

**Comment by jrudolph** [comment]
Merging TLSActor's `sslContext` and `sslConfig` into a single SSLEngine constructor function will also have the benefit of it allowing users to use netty's `SslContext` as an HTTP implementation. So, we might want to do the internal changes asap, keeping the public interface in `akka.stream.scaladsl.TLS` until 2.5 (but maybe deprecating it already now).

**Comment by jrudolph** [comment]
> the current setup allows people to override the settings per conecction/pool/server since they can get the AkkaSSLConfig and use the .withBlabla methods to change the settings programatically.

How would you do that?

**Comment by ktoso** [comment]
See here https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala

**Comment by jrudolph** [comment]
Ok, so that would mean there's a general default that can be overridden by more specific defaults in another module. But then I wonder why we would need the defaults live in Akka if they are specific to nothing? We could also move the defaults to ssl-config. Also, "inheriting" good defaults is nice for security on one hand but isn't enough to get good security. So, the "final default" for HTTPS including all overridings done in ConnectionContext would have to be reviewed as well in its entirety to be sure that it is really good. This is in conflict with distributing security settings across multiple modules.

**Comment by anilgursel** [comment]
I have some confusion around how SSL settings are configured.  By looking through the code, here is what I see happening:

Here is the API for [ConnectionContext](https://github.com/akka/akka-http/blob/v10.0.0/akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala#L36):

```scala
object ConnectionContext {
  //#https-context-creation
  // ConnectionContext
  def https(
    sslContext:          SSLContext,
    sslConfig:           Option[AkkaSSLConfig]         = None,
    enabledCipherSuites: Option[immutable.Seq[String]] = None,
    enabledProtocols:    Option[immutable.Seq[String]] = None,
    clientAuth:          Option[TLSClientAuth]         = None,
    sslParameters:       Option[SSLParameters]         = None) =
    new HttpsConnectionContext(sslContext, sslConfig, enabledCipherSuites, enabledProtocols, clientAuth, sslParameters)
  //#https-context-creation

  // for binary-compatibility, since 2.4.7
  def https(
    sslContext:          SSLContext,
    enabledCipherSuites: Option[immutable.Seq[String]],
    enabledProtocols:    Option[immutable.Seq[String]],
    clientAuth:          Option[TLSClientAuth],
    sslParameters:       Option[SSLParameters]) =
    new HttpsConnectionContext(sslContext, None, enabledCipherSuites, enabledProtocols, clientAuth, sslParameters)

  def noEncryption() = HttpConnectionContext
}
```

- In `HttpsConnectionContext`, a function is defined to create a `NegotiateNewSession` instance: [`def firstSession = NegotiateNewSession(enabledCipherSuites, enabledProtocols, clientAuth, sslParameters)`](https://github.com/akka/akka-http/blob/v10.0.0/akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala#L65) from the last 4 parameters.
- The above `ConnectionContext` ultimately goes to [TLS](https://github.com/akka/akka-http/blob/v10.0.0/akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala#L673).
- Looking at [TLS.scala](https://github.com/akka/akka/blob/v2.4.14/akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala#L78).  First, an `SSLEngine` is created from passed in `SSLContext`.
- Then, [`config.sslEngineConfigurator.configure(engine, sslContext)`](https://github.com/akka/akka/blob/v2.4.14/akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala#L84) is called to prepare overrides for protocols and ciphers.  Jumping in [`sslEngineConfigurator`](https://github.com/akka/akka/blob/v2.4.14/akka-stream/src/main/scala/com/typesafe/sslconfig/akka/AkkaSSLConfig.scala#L71), :
  - If `ssl-config.default`is:
     - `true`: Create an `SSLContext` from JVM default
     - `false`: Build an `SSLContext` according to `SSLConfigSettings` in `AkkaSSLConfig`.
  - Protocols and ciphers are retrieved from `SSLContext`, but re-ordered/filtered based on the configuration in `SSLConfigSettings` in `AkkaSSLConfig`.
- `enabledProtocols` and `enabledCipherSuites` in `SSLEngine` are overridden with the values retrieved from the previous step by calling [`config.sslEngineConfigurator.configure(engine, sslContext)`](https://github.com/akka/akka/blob/v2.4.14/akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala#L84).  Jumping in the `configure` method  [`DefaultSSLEngineConfigurator`](https://github.com/akka/akka/blob/v2.4.14/akka-stream/src/main/scala/com/typesafe/sslconfig/akka/SSLEngineConfigurator.scala#L21).
- Then, [`TlsUtils.applySessionParameters(engine, finalSessionParameters)`](https://github.com/akka/akka/blob/v2.4.14/akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala#L99) is called to override `enabledCipherSuites`, `enabledProtocols`, `clientAuth`, `sslParameters` if they are defined in `NegotiateNewSession`.  Please note, these values come from `ConnectionContext.https` parameters.  Between, `sslParameters` might have `cipherSuites`, `protocols` and `clientAuth` defined.  If so, they will ultimately override.

So, it looks like, the parameters of `ConnectionContext.https` are already in order of configuration override.  To summarize, here is what seems to be happennig to find out the ultimate value of `cipherSuites`, for instance:
  - If `cipherSuites` is defined in `sslParameters`, that's the ultimate value.  If not, go to next step.
  - If `enabledCipherSuites` parameter is not `None`, that's the ultimate value.  If not, go to next step.
  - If `sslConfig` is `None`, use the singleton `AkkaSSLConfig`.
    - Create an `SSLContext`.  If  `sslConfig.default` is true, create from JVM default; otherwise from the configuration in `sslConfig`. 
    -  Get the `enabledCipherSuites` from `SSLContext`.  Go to next step.
    - If `sslConfig.enabledCipherSuites` is not `None`, filter/order `enabledCipherSuites` from `SSLContext` accordingly, and this is the ultimate value.  If not, go to the next step.
    - Filter/order `enabledCipherSuites` from `SSLContext` based on default recommended ciphers in  `Ciphers.recommendedCiphers` of Typesafe SSLConfig project.

This many layers of configuration and fallback is quite confusing to me.  

I probably miss something to understand the reasoning behind this.  I will appreciate if you can please explain.  Or is this issue filed to simplify it overall?

**Comment by jrudolph** [comment]
Since we never deprecated any of this stuff I wonder if we can actually remove something in 2.6 already. If we agree on the approach outlined above we should deprecate AkkaSslConfig and all its usages in akka-stream and akka-http as a first step.

**Comment by patriknw** [comment]
We didn't talk about this one, but Johannes plan is probably accurate. Requiring deprecation. Since this is very tightly related to Akka HTTP I suggest that @jrudolph or @raboof takes a stab at it.

**Comment by patriknw** [comment]
This is my understanding of what should be done here:

* We already have API for `() => SSLEngine`. Docs need to be updated to express that it's *the* API

https://github.com/akka/akka/blob/35232cce04d9ed5a09169131fecf44a78dc43fac/akka-stream/src/main/scala/akka/stream/scaladsl/TLS.scala#L161-L164

* Deprecate the TLS.apply methods taking `AkkaSSLConfig` and `SSLContext` parameters

* Deprecate `AkkaSSLConfig` and `SSLEngineConfigurator`

* Update the [reference documentation sample](https://doc.akka.io/docs/akka/current/stream/stream-io.html#tls) to show how to create SSLEngine
  * for this it can be useful to look at [Artery TCP ConfigSSLEngineProvider](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala)
  * but we shouldn't create any new helpers or abstractions, Akka Streams TLS is supposed to be low level and such helpers can exist in higher layers (with more use case specific context) such as Akka HTTP and Artery TCP

* Update TlsSpec to not use the deprecated methods. Maybe keep test coverage by making a copy DeprecatedTlsSpec with some of it.

* Similar in javadsl

* note in migration guide
