### ISSUE TITLE
Document strategies on providing Akka Streams libs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21750]
There should be a small section for library authors how they should expose their Akka Streams operators.

There's a few styles:
- javadsl / scaladsl if it has to add API
- just provide `Graph[....]` which can be used by either api, either using `via` of `Source.fromGraph` etc. 

We don't really suggest these for authors so they're guessing what's best.
A nice example of showing this to users is in eventuate: http://rbmhtechnology.github.io/eventuate/adapters/stream.html

**Comment by ennru** [comment]
Some hints have been part of [CONTRIBUTING.md](https://github.com/akka/akka/blob/master/CONTRIBUTING.md#java-apis-in-akka) for a while.
Closing.
