### ISSUE TITLE
http: client connection pool with circuit breaker

### ISSUE THREAD

**Issue by svezfaz** [akka/akka#21752]
When using the low-level http client API, I would find convenient to have a circuit-breakable version of a client connection pool. In my specific case it would be for the `superPool` API, but the same could be applied to the `cachedHostConnectionPool`.
It could be something like

```
def superPoolWithBreaker[T](breaker: CircuitBreaker)(...) = ???
```

Pool flows return `Try[HttpResponse]` already, so they can wrap the CB exceptions.

The CB could be wired in `clientFlow` helper method and used when the `mapAsyncUnordered` is invoked. I can take care of the PR in case this is deemed useful.

**Comment by patriknw** [comment]
Please open this issue in https://github.com/akka/akka-http
