### ISSUE TITLE
please release a 2.3.15 build for scala-2.12

### ISSUE THREAD

**Issue by fommil** [akka/akka#21763]
As it stands, one must upgrade to java 8 for scala-2.10/scala-2.11 (akka 2.4.x) which isn't something we're prepared to do with our build because many ensime users are on java 7 in their work.

So I'm trying to find a matrix build that will work for cross building scala-2.{10,11,12}. It would help us a lot if you made a build for 2.3.15 available (we only use actors, testkit and slf4j).

**Comment by soc** [comment]
I think this is quite important for the overall health of the ecosystem. It would be extremely embarrassing to release Scala 2.12 with basically zero IDE/editor support from the community.

**Comment by patriknw** [comment]
Akka 2.3.x is end of life, but we have been kind to continue backporting critical issues an cutting releases (2.3.16 will be released in a few days). If you want a release of that for Scala 2.12 I would ask you to contribute with your time and do build adjustments (dependencies) and verify that it works.

If you only need akka-actor we are fine with only releasing that module when you have verified that it works.

**Comment by fommil** [comment]
What build dependencies do you have on scala 2.12 libraries? I thought you were zero dep.

Are there instructions for creating a build, the last time I tried to do anything with the akka build it was trying to resolve modules that weren't available to me.

**Comment by patriknw** [comment]
If it's only akka-actor it's only the scala dep (and typesafe config, but that is java lib). 

sbt akka-actor/publishLocal

I doubt you will be able to run any tests (in akka-actor-tests) due to old scalatest dependency.

**Comment by drewhk** [comment]
Yes, one of the things we had to do was to upgrade to Scalatest 3.0 in Akka
2.4

2016. okt. 30. 19:39 ezt írta ("Patrik Nordwall" <notifications@github.com
>):
>
> If it's only akka-actor it's only the scala dep (and typesafe config, but
that is java lib).
>
> sbt akka-actor/publishLocal
>
> I doubt you will be able to run any tests (in akka-actor-tests) due to
old scalatest dependency.

**Comment by fommil** [comment]
we also depend on `akka-testkit` and `akka-slf4k`

**Comment by johanandren** [comment]
I released 2.3.16 yesterday, spent a bit of time on trying to get artifacts out for 2.12-RC2 but reached the end of my timebox. If someone can PR changes on top of 2.3.16 that makes the needed modules compile on Scala 2.12 I can publish (untested) artifacts.

**Comment by fommil** [comment]
Hmm, I wonder if Bill could publish old scalatest for 2.12

**Comment by fommil** [comment]
we took a poll of users and decided to upgrade to Java 8, thanks for offering to publish!

**Comment by ktoso** [comment]
Wohoo, that's cool :-)
Nice to see all the various projects moving on to J8 and S2.12 so swiftly :-)

**Comment by fommil** [comment]
we already have java 6 compatible ensime 1.0, and we have a way of running ensime on java 8 for java 6 or 7 projects... the only problem is that it will not match sources up exactly to the source code. But even that might be fixable if anybody needs to do that. The beauty of being able to hack your tools.

**Comment by fommil** [comment]
(the real reason is that I was using java 7 at work until very recently)

**Comment by fommil** [comment]
reopening, there is no akka 2.4 for scala-2.10.
