### ISSUE TITLE
SerializationCompatibilitySpec tests bitwise equality but should test deserialization

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#21771]
There is a name change in a field in `Some` in Scala 2.12, and this changes the serialization bytes but no the ability to deserialize the bytes.

**Comment by patriknw** [comment]
+1

**Comment by ktoso** [comment]
This was solved in https://github.com/akka/akka/pull/21778/ I believe (includes that commit).

**Comment by bantonsson** [comment]
Yup, that's correct. Haven't had time to clean up my tickets. Thanks @ktoso
