### ISSUE TITLE
Stack frames can be missing file and line number crashing serialization `ThrowableSupport`

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#21772]
NPE

**Comment by patriknw** [comment]
Is this because lambdas are not java.io.Serializable, as explained by @rkuhn in https://github.com/scala/community-builds/pull/317#issuecomment-256744056 ?

**Comment by bantonsson** [comment]
Shouldn't have to be... I don't know why this is the case, and I can't seem to be able to reproduce it locally again...

**Comment by patriknw** [comment]
This was fixed in https://github.com/akka/akka/pull/21778
