### ISSUE TITLE
Offset issues

### ISSUE THREAD

**Issue by jroper** [akka/akka#21788]
A few issues with the new `Offset` class in Akka persistence query:

* There is no Java friendly way to use `NoOffset`, you have to say `NoOffset$.MODULE$`.
* Should the `Offset` trait be sealed?
* It would be convenient if there was an `Offset` companion object that offered constructors for `Sequence`, `TimeBasedUUID` and maybe even a reference to `NoOffset`, this will aid in discoverability from an IDE perspective (ctrl space will bring up the options for constructing an offset).

**Comment by johanandren** [comment]
* Java API - definitely
* I don't think the trait should be sealed, a persistence-query-implementation may introduce its own offset type(s), we just provide the common ones as far as I understand it. 
* factories for the three types - maybe, I'll play around with the idea

**Comment by johanandren** [comment]
Thanks @jroper for the ideas.
