### ISSUE TITLE
Fold behaviour on supervisor Resume

### ISSUE THREAD

**Issue by andy-hw-chung** [akka/akka#21794]
In `Fold` (https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala#L502) there is some unexpected behaviour when an error is thrown in the `onPush` method. When an error is thrown and the supervisor strategy decides to resume the stage, the behaviour of `onPush` resets the internal state of the stage to the initial state rather than keeping the accumulated state unchanged. Currently, the `onPush` reads:

```scala
override def onPush(): Unit = {
        try {
          aggregator = f(aggregator, grab(in))
          pull(in)
        } catch {
          case NonFatal(ex) ⇒ decider(ex) match {
            case Supervision.Stop ⇒ failStage(ex)
            case _ ⇒
              aggregator = zero
              pull(in)
          }
        }
      }
```

Shouldn't it read something like this instead?

```scala
override def onPush(): Unit = {
        try {
          aggregator = f(aggregator, grab(in))
          pull(in)
        } catch {
          case NonFatal(ex) ⇒ decider(ex) match {
            case Supervision.Stop ⇒ failStage(ex)
           case Supervision.Resume ⇒ pull(in) // leave the aggregator state as it is if resume
            case _ ⇒
              aggregator = zero
              pull(in)
          }
        }
      }
```

**Comment by johanandren** [comment]
Sounds like a bug with `Resume` doing `Restart`. Feel like sending in a pull request fixing it? (test coverage in addition to the fix would be good)

**Comment by andy-hw-chung** [comment]
Sure - I noticed something similar in Reduce as well. I'll include that as well

**Comment by johanandren** [comment]
Great!

**Comment by drewhk** [comment]
Thanks for the help!
