### ISSUE TITLE
akka-stream OSGi bundle has incorrect Import-Package

### ISSUE THREAD

**Issue by hlavki** [akka/akka#21791]
It looks like commit c9854e43503c20a2c5dfa9f8c73acfe27e07a3ee corrupted akka-stream OSGi bundle. It contains non-existing import in `Import-Package`:
```
scala.util.parsing.combinator;version="[2.11,2.12)
```
this namespace is part of `scala-parser-combinators_2.11` and akka uses version **1.0.4**

**Comment by patriknw** [comment]
@hlavki do you have a suggestion of how to fix it?

**Comment by hlavki** [comment]
I don't know how to fix this yet, but I know that it is result of adding `com.typesafe.sslconfig.akka.*` to export packages (line 88 of project/OSGi.scala)
