### ISSUE TITLE
Unable to load akka-remote in OSGi container

### ISSUE THREAD

**Issue by 2m** [akka/akka#21796]
Since 2.4.11 it depends on Aeron which is not OSGi ready.

**Comment by ktoso** [comment]
We should talk about this on monday I think... I guess only solution is fixing aeron artifacts or shading :(

**Comment by drewhk** [comment]
And discuss the timeline for deprecating OSGi again ;)

**Comment by drewhk** [comment]
And discuss the timeline for deprecating OSGi again ;)

**Comment by drewhk** [comment]
And discuss the timeline for deprecating OSGi again ;)

**Comment by patriknw** [comment]
Looks like it's in progress here: https://github.com/real-logic/Aeron/pull/288

**Comment by patriknw** [comment]
I assume it's fixed in Aeron 1.0.4 and then this should be fixed in Akka 2.4.14
