### ISSUE TITLE
Race condition in InputStreamSinkStage

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21804]
Parsing the entity of a http response to XML using the StreamConverters like so: `XML.load(entity.dataBytes.runWith(StreamConverters.asInputStream()))` 

sometimes fails with the following exception:
```
java.lang.IllegalArgumentException: requirement failed: First message must be Initialized notification
at scala.Predef$.require(Predef.scala:224)
at akka.stream.impl.io.InputStreamAdapter.waitIfNotInitialized(InputStreamSinkStage.scala:202)
at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:111)
at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:132)
at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:118)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2890)
...snip...
```

**Comment by johanandren** [comment]
It can only happen if `onPush`, `onUpstreamFinish` or `onUpstreamFailure` happens before `preStart` is called as far as I can understand, but how is that possible?

**Comment by drewhk** [comment]
That is not possible. Unless bug but that is unlikely here.

2016. nov. 8. 17:51 ezt írta ("Johan Andrén" <notifications@github.com>):

**Comment by johanandren** [comment]
As far as I can see there can not be any async callback going on from the `InputStreamAdapter` to the stage until the `InputStreamSinkStage`. It does nothing in the constructor and read directly calls `executeIfNotClosed` which calls `waitIfNotInitialized` where it finds out that `Initialized` is not the first message in the queue.

**Comment by drewhk** [comment]
Also, the `chaseCounter` starts with a zero value, so no chasing can happen in the initialization phase, only after we enter through `execute()`. So there is no bug there.

**Comment by drewhk** [comment]
Try to reproduce this somehow, maybe with fuzzing on, and enable debug logging on the interpreter.

**Comment by johanandren** [comment]
I have been running hundreds of thousands of requests with something looking like the original scenario (running the `InputStreamSinkStage` on the http response entity) with all kinds of varying parameters I can think of: fuzzing/no fuzzing, asynch boundaries/fusing, slow responses (throttling, delaying start), chunked responses, strict responses, input buffer size.

I have not been able to reproduce the bug a single time. Asking the person reporting it for more details.
