### ISSUE TITLE
TestActorRef race condition

### ISSUE THREAD

**Issue by cywattebled** [akka/akka#21806]
Greetings,

I'm currently working on a project that uses TestActorRef to test Asynchronous and Synchronous behavior of an actor. This is important because we have Mock Actors that we instanciate as TestActorRefs that are used during testing asynchronously and that we interrogate at the end of the tests using underlyingActor().

It mostly works just fine but we have randomly failing unit tests.
I narrowed it down the problem to the TestActorRef race condition on creation.

If I create an actor selection for the TestActorRef path right after creation with TestActorRef.create(), resolving the actor ref fails randomly, no matter what timeout I set. I have tested by running the test in Intellij until failure.
The same test using a regular actor created via system.actorOf runs just fine.

I have created a unit test to help reproducing the problem (attached).
[TestActorRefTest.java.zip](https://github.com/akka/akka/files/575639/TestActorRefTest.java.zip)

While testActorSelection runs just fine, no matter how long I run it, testTestActorRefSelection doesn't.

In my test, we have also noticed that while a new system is created for every test, the Test actor path seems to increment. I was expecting it to remain /user/$$a. TestActorRef seems to be a singleton.

I'm using Akka 2.4.12 with Java 1.8.0_112

Thanks for your help.

**Comment by johanandren** [comment]
Hi @cywattebled 
> This is important because we have Mock Actors that we instanciate as TestActorRefs that are used during testing asynchronously and that we interrogate at the end of the tests using underlyingActor().

Note that the docs [explicitly recommends to not use the sync TestActorRefs](http://doc.akka.io/docs/akka/2.4.12/java/testing.html#Synchronous_Unit_Testing_with_TestActorRef) whenever possible. `TestProbe` should cover all your needs for "interrogating" for received messages and "mocking" message exchanges. I strongly recommend you to do that over relying on `TestActorRefs` when there are multiple actors involved.

**Comment by patriknw** [comment]
I agree with @johanandren
