### ISSUE TITLE
FAILED akka.cluster.Stress (Artery)

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21810]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/255/consoleFull

```
[JVM-2] - must end routers that are running while nodes are joining *** FAILED *** (24 milliseconds)
[JVM-2]   125 did not equal 0 (StressSpec.scala:1225)
[JVM-2]   org.scalatest.exceptions.TestFailedException:
[JVM-2]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-2]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-2]   at akka.cluster.StressSpec$$anonfun$4$$anonfun$apply$mcV$sp$39$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41.apply$mcV$sp(StressSpec.scala:1225)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/260/consoleFull

**Comment by drewhk** [comment]
Another two of the "one-by-one" case, but now 

```
[JVM-3] - must join nodes one-by-one to small cluster *** FAILED *** (7 seconds, 60 milliseconds)
[JVM-3]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[JVM-3]   at scala.Predef$.assert(Predef.scala:170)
```

on both.

https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/265/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/263/consoleFull

**Comment by drewhk** [comment]
[JVM-11] - must join several nodes to seed nodes *** FAILED *** (42 seconds, 963 milliseconds)

https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/268/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/269/consoleFull

**Comment by drewhk** [comment]
These are after the comperssion fix, so that is not the culprit here.

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/270/consoleFull

**Comment by drewhk** [comment]
I stopped pinging this.

**Comment by patriknw** [comment]
Marked it as pending for Artery until we fix it https://github.com/akka/akka/pull/21869

**Comment by drewhk** [comment]
There were several new failures of the "one-by-one" kind but they all look the same.

**Comment by patriknw** [comment]
I have started a debug branch `wip-21810-StressSpec-patriknw` and will run it in the repeat job.

**Comment by ktoso** [comment]
Here: https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/313/console

**Comment by ktoso** [comment]
Note: this is to be closed when we re-enable the test.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/48/consoleFull

**Comment by johanandren** [comment]
Not sure if this one is related to artery, but I see the confusing path: 
`akka://StressSpec/remote/akka.tcp/StressSpec@localhost:53579/user/master-node-3/workers/c5` in there, mixing artery and old remoting?

https://jenkins.akka.io:8498/job/akka-nightly/4198/consoleFull

**Comment by patriknw** [comment]
the first `akka` is just that it's a local path, I think

**Comment by 2m** [comment]
Two failures this night:

https://jenkins.akka.io:8498/job/akka-multi-node/2017/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly-2.12/161/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4453/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/235/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/236/consoleFull

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4532/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/290/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5609/consoleFull
```
[info] [JVM-1] - must use routers with normal throughput (on node 'node-1', class akka.cluster.StressMultiJvmNode1) *** FAILED *** (30 seconds, 68 milliseconds)
[info] [JVM-1]   22 did not equal 0 (StressSpec.scala:1030)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2955/consoleFull

```
[info] [JVM-3] - must use routers with high throughput (on node 'node-3', class akka.cluster.StressMultiJvmNode11) *** FAILED *** (10 seconds, 161 milliseconds)
[info] [JVM-3]   33 did not equal 0 (StressSpec.scala:1030)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6432/log/?start=0

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5976/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/5978/consoleFull

**Comment by chbatey** [comment]
Running this on repeat: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/

One issue was that, for multi jvm (rather than multi node), the media driver was started many times in the same directory.

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2161/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/445/consoleText

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/453/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/487

**Comment by seglo** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/523/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7644/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7774/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7810/consoleText

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/591/consoleFull

**Comment by patriknw** [comment]
Probably similar or duplicate of https://github.com/akka/akka/issues/23511
