### ISSUE TITLE
A PersistentActor does not get the causing message to preRestart

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21824]
As described in this SO question:
http://stackoverflow.com/questions/40507142/how-to-get-message-causing-restart-in-akka-persistence

the `aroundPreRestart` of a `PersistentActor` does not pass the causing message to `preRestart` of the actor. Seems to be an oversight.

**Comment by naferx** [comment]
Hi @johanandren,
I would like to contribute with it.

**Comment by johanandren** [comment]
@naferx awesome, go ahead!
