### ISSUE TITLE
Use SimpleLinearGraphStage to reduce the boilerplate code

### ISSUE THREAD

**Issue by Hawstein** [akka/akka#21830]
Since we have `SimpleLinearGraphStage`, we can use it, instead of `GraphStage[FlowShape[T, T]]`, to reduce the boilerplate code.

```scala
  abstract class SimpleLinearGraphStage[T] extends GraphStage[FlowShape[T, T]] {
    val in = Inlet[T](Logging.simpleName(this) + ".in")
    val out = Outlet[T](Logging.simpleName(this) + ".out")
    override val shape = FlowShape(in, out)
  }
```

**Comment by hepin1989** [comment]
More consistence.

**Comment by naferx** [comment]
I think for Akka users, it would be very useful to have it in the akka streams public api and for consistency reasons something like this is needed.
 `abstract class SimpleSourceStage[T] extends GraphStage[SourceShape[T]] {
    val out = Outlet[T](Logging.simpleName(this) + ".out")
    override val shape = FlowShape(out)
  }`

@Hawstein WDYT ?

// c.c @ktoso

**Comment by ktoso** [comment]
I really wanted these `Simple[Source/Flow/Sink]Stage` at some point but it was voted down, as to have only a single API entry point. Up for another vote I guess or for @patriknw to decide.

**Comment by patriknw** [comment]
Could it be a factory method with a `() => GraphStageLogic` parameter instead?

**Comment by johanandren** [comment]
Wouldn't that make things impossible for the gearpump people, don't they depend on the stage types to figure out what stage is what?

**Comment by johanandren** [comment]
BTW I'm in the "three lines of saved code in a class isn't worth an abstraction camp".

**Comment by Hawstein** [comment]
> BTW I'm in the "three lines of saved code in a class isn't worth an abstraction camp".

I agree with @johanandren . I create this issue and PR just to simplify the existing build-in stage with the existing internal API, not for a new public API.

**Comment by naferx** [comment]
You're right @Hawstein. The discussion is out of the scope of this issue. I filed a ticket for keep the discussion [here](https://github.com/akka/akka/issues/21834).
