### ISSUE TITLE
Move AkkaSpec and StreamSpec to testkit(s) main 

### ISSUE THREAD

**Issue by agolubev** [akka/akka#21836]
As they really not testing anything but can be used for alpakka's stage testing

**Comment by johanandren** [comment]
They do contain a bunch of Akka internals specifics and tie into `ScalaTest` though, testkit should be test framework agnostic? 

I think it would be better to just copy whatever is needed to a common Alpakka test-module?
(cool new profile pic btw)

**Comment by patriknw** [comment]
I agree, not possible to have in testkit

**Comment by agolubev** [comment]
I see. My point is that StreamSpec is base class for testing Streams and Stages so akka-stream-testkit will be useful (as S3 does have some stages to test).
Still let me know if I need to close current ticket.

**Comment by drewhk** [comment]
I think this should be closed. While this means a bit of duplication, we tend to mess around with these traits  (adding stuff, usualyl) and hence it is not a good idea to expose it. What I can imagine is to provide a baseclass that can go to testKit, from which AkkaSpec inherits (likely not changing anything at this point).
