### ISSUE TITLE
ByteStringParser doesn't backpressure

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21838]
It uses `emit` which will buffer outgoing elements and will instantly call `pull` in a loop. It should instead properly propagate backpressure from the outgoing side to the input (with buffering input data as much needed).

**Comment by drewhk** [comment]
It seems like the case when the parser reports NeedMoreData we call pull() immediately, which does not wait on the pending emit chain. One simple fix is to have the pull() at the end of the emit() chain instead. The best fix is to remove emit() altogether and use the usual push()-onPull() dance.

**Comment by drewhk** [comment]
Er, this goes to akka-http instead...
