### ISSUE TITLE
Provide Simple[Source/Flow/Sink]Stage in the public API

### ISSUE THREAD

**Issue by naferx** [akka/akka#21834]
The discussion comes from https://github.com/akka/akka/issues/21830

//c.c @ktoso  @patriknw @johanandren

**Comment by johanandren** [comment]
Original discussion was #19156 

I stand by my point from then, providing many many "simplifiers" that actually saves so little boilerplate is much worse than having a clear more advanced abstraction to express all of them (like now with the shape type parameter and two graph stage types to build on).

**Comment by ktoso** [comment]
Here's a tangible reason for making it simpler: https://github.com/akka/akka-http/pull/512/files
The number of stages that had a different style in naming etc. in / out are good names for flow, otherwise people end up giving them inconsistent names, as whitnessed even by our own codebase (see above).

**Comment by ktoso** [comment]
To counter my own example, it'd be a pain to do java api for those... since all need a version with logging etc

**Comment by ktoso** [comment]
Or maybe they don't need those hm...

**Comment by ktoso** [comment]
Sorry, mis-clicked

**Comment by naferx** [comment]
Well, I don't have a stronger argument than just for saving a little code from the user perspective

**Comment by ktoso** [comment]
Closing for now due to inactivity (no more people jumped on it so let's consider it low priority, if it comes up again we can think again) :) Thanks for the ticket though!
