### ISSUE TITLE
weird exception when sending fast messages 

### ISSUE THREAD

**Issue by 123avi** [akka/akka#21832]
akka version   = "2.4.10"
scalaVersion  := "2.11.8"

I tried to run simple test 
```
case class Foo(id:String, d:DateTime, value:Int)

(1 to count).foreach{i =>
      actor ! FooMessage(Foo(id, d.plus(i), i))
    }
```
the Actor receive method: 
`  case FooMessage(foo) =>  sender() ! true`

I am getting: 
An exception or error caused a run to abort: 

> org.scalactic.Prettifier.apply(Ljava/lang/Object;)Ljava/lang/Object; 
> java.lang.NoSuchMethodError: org.scalactic.Prettifier.apply(Ljava/lang/Object;)Ljava/lang/Object;
> 	at org.scalatest.FailureMessages$.decorateToStringValue(FailureMessages.scala:31)
> 	at org.scalatest.FailureMessages$$anonfun$apply$1.apply(FailureMessages.scala:35)
> 	at org.scalatest.FailureMessages$$anonfun$apply$1.apply(FailureMessages.scala:35)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at org.scalatest.FailureMessages$.apply(FailureMessages.scala:35)
> 	at org.scalatest.Assertions$class.assertResult(Assertions.scala:1225)
> 

however if I add minimal delay it works fine: 
```
(1 to count).foreach{i =>
     Thread.sleep(5L)
      actor ! FooMessage(Foo(id, d.plus(i), i))
    }
```

**Comment by ktoso** [comment]
Does not seem like an akka issue - a missing method on scalactic - make sure you have all dependencies correct.
