### ISSUE TITLE
Issue using LeveldbStore with ProtobufSerializer

### ISSUE THREAD

**Issue by SubhraB** [akka/akka#21841]
I am facing issue using the below classes for serialization with actor persistence.

"akka.persistence.journal.leveldb.LeveldbStore" and "akka.remote.serialization.ProtobufSerializer"

In the ProtobufSerializer class, I noticed that a 'non-static' method called 'toByteArray' is expected for serialization and a 'static' method called 'parseFrom' is expected for deserialization.

Now I have a case class and a companion object something like below

```
case class Bar(name: String) {
   // non-static method
    def toByteArray(): Array[Byte] = {
        // logic to return some JSON String bytes
   }
}
case object Bar{
    // static method
    def parseFrom(bytes: Array[Byte]): Bar = {
        // logic to parse JSON and convert to Bar
    }
}
```

In application. conf I have the below setting.

```
actor {
        serializers {
            proto = "akka.remote.serialization.ProtobufSerializer"
    }
 
        serialization-bindings {
            "com.Bar" = proto
    }
}
```

While running the actor, I get the below error.

> java.lang.NoSuchMethodException: com.Bar.parseFrom([B)

I checked the class LeveldbStore and notice the below line for deserialization
`def persistentFromBytes(a: Array[Byte]): PersistentRepr = serialization.deserialize(a, classOf[PersistentRepr]).get`

I believe "classOf[PersistentRepr])" in the above line is returning the type of the case class and not the companion object, so it is not able to find the static method.

Please check. Let me know I am missing anything

**Comment by johanandren** [comment]
Hi @SubhraB, the `akka.remote.serialization.ProtobufSerializer` is an internal serializer, it knows how to serialize the internal messages used in Akka, it does not know how to serialize your own types, for this you will have to define your own serializer or use one of the third party serializers, see the docs for details: http://doc.akka.io/docs/akka/2.4/scala/serialization.html#External_Akka_Serializers


In general, please use the issue tracker only for bugs and feature requests and use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) or the [gitter channel](https://gitter.im/akka/akka) for question on how to use Akka, thanks!
