### ISSUE TITLE
Keep could define `other` function

### ISSUE THREAD

**Issue by rbudzko** [akka/akka#21844]
`Keep` could define fifth strategy called `other`. 

Signature could be:
```
def other[L, R, O](value: O): (L, R) ⇒ O = (left: L, right: R) ⇒ value
```

An example usage would be:
```
Source
   .fromIterator(somethingLongButFinishable)
   .toMat(somethingReturningFutureIOResult)(Keep.other(Future(Done)))
```
@ktoso mentioned that `Keep` is used to optimize stuff, but having `Future(Done)` returned when all stages completed (stream done) would be very convenient, but if optimized in a some way as `none` it would probably immediately return the `value`- that is not what one would probably expect by looking at the API.

**Comment by johanandren** [comment]
As the second parameter list takes a function `(L, R) => M` you can easily already pass do `(_, _) => Something` to it to achieve the same, I think it is really uncommon and not useful enough to warrant a shortcut.

Note that your sample `Future(Done)` will not complete when the stream is complete, it will materialize a future that completes right away.

**Comment by drewhk** [comment]
Yeah, this does not achieve what you want. Even if you want to just override a materialized value with something else (in rare occasions this might be necessary) it is better to use `mapMaterializedValue`.

**Comment by rbudzko** [comment]
I've read some more internals to water proof stuff on my own end and obviously you are right. Just to confirm, because while looking at `toMat` vs `to` it is not self explanatory:

`.toMat(fileSink)((left: NotUsed, right: Future[IOResult]) => right.map(_ => Done)` will be slower then `.to(fileSink)(Keep.right).mapMaterializedValue(_.map(_ => Done))`.

It seems like a very common situation that I want to unify few materialized types to `Future[CustomType]` when no failure occurred behind some `Sink` provider abstraction.

🍺 to you for looking into this ticket - thank you! I think my proposal does not make any valid sense in the end 😉  - please reject.
