### ISSUE TITLE
`ActorSystem.registerOnTermination` should document that it's important not to block on the `whenTerminated` future

### ISSUE THREAD

**Issue by oxbowlakes** [akka/akka#21840]
Welcome to Scala 2.12.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
    Type in expressions for evaluation. Or try :help.

    scala> import akka.actor._; import scala.concurrent._; import duration._
    import akka.actor._
    import scala.concurrent._
    import duration._

    scala> :paste
    // Entering paste mode (ctrl-D to finish)

    val s = ActorSystem("test")
    def onTerm = {
      println("Waiting...")
      Await.result(s.whenTerminated, Duration.Inf)
      println("Fin!")
    }
    s.registerOnTermination(onTerm)

    // Exiting paste mode, now interpreting.

    s: akka.actor.ActorSystem = akka://test
    onTerm: Unit

    scala> s.terminate
    res1: scala.concurrent.Future[akka.actor.Terminated] = Future(<not completed>)

    scala> Waiting...

At this point the application hangs indefinitely.

**Comment by johanandren** [comment]
I could have sworn`onTermination` was deprecated along with the `awaitTermination` methods. 
You up for a PR adding this to the two `onTermination` methods? 

(Additionally: It is important to not block any future unless running on an explicitly selected dispatcher for blocking. _never_ `Await.result`, and if you do _never_ use `Duration.Inf`)

**Comment by oxbowlakes** [comment]
These methods are not deprecated as far as I can see. As of 2.4, isTerminated was deprecated in favour of whenTerminated.

As for the blocking, I thought that Await used 'concurrent.blocking' internally do as to guarantee that you couldn't starve a thread pool. 

Chris

**Comment by johanandren** [comment]
Yeah, was thinking my surprise about it not being deprecated out loud there. :)

`Await` does use `blocking`, it is hovewer up to the `ExecutionContext` (defined by the `BlockContext` trait) to act on that, thread pool based execution contexts will just ignore the blocking - and starve the threadpool, fork join pool (the default dispatcher) will fork compensating threads, so with that you get unbounded new threads possibly being started which is not good - in this case however that compensation does not help much as we are blocking the actor system shutdown from completing.

This was more of a side note about best practice, I still think it would be good to say "the ActorSystem will not complete termination until the callback registered with onTermination completes" or something like that on the docs of those methods.
