### ISSUE TITLE
Add Java 8 Testkit API

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21858]
The Java testkit does all kinds of tricks to achieve what the Scala testkit does, we should make use of the Java 8 lambdas and introduce a nicer Java testkit.

**Comment by patriknw** [comment]
+1
I think this would be an excellent community contribution if someone is looking for something fun and very useful.

**Comment by patriknw** [comment]
also check that stream-testkit has a good api, e.g. lambda for `within`

**Comment by Hawstein** [comment]
I would like to take this issue. However I can not promise an ETA since I am very busy. Is it OK?

**Comment by patriknw** [comment]
That would be awesome. This will make a big difference for all Java users. Thanks.

**Comment by Hawstein** [comment]
So, As far as I know, what I am going to refactor is just `akka.testkit.JavaTestKit`. As for stream-testkit, the Java DSL is delegated to the Scala one.

**Comment by patriknw** [comment]
We must keep the old, deprecate it before removal. It might be best to create the new with a new name.

Is the old implemented in java? That is not a requirement if you prefer to implement it in Scala.

**Comment by Hawstein** [comment]
Finally, I got the time to work on this issue in Spring Festival, ah. Hope it is not too late :)
@patriknw @johanandren

**Comment by michaelom** [comment]
overlaps with/duplicate of  #18109

**Comment by johanandren** [comment]
Ah, thanks for pointing that out, I'll close this one then.
