### ISSUE TITLE
FAILED: sample.distributeddata.ReplicatedMetricsSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21870]
https://jenkins.akka.io:8498/job/akka-multi-node/1834/consoleFull

```[JVM-1] - must replicate metrics *** FAILED ***
[JVM-1]   2 was not equal to 3 (ReplicatedMetricsSpec.scala:67)```

**Comment by drewhk** [comment]
Can be related to: https://github.com/akka/akka/issues/21651 ?

**Comment by patriknw** [comment]
MetricsBasedResizerSpec is related to routers, ReplicatedMetricsSpec is distributed data

**Comment by drewhk** [comment]
I was thinking if the router depends on the replicated metrics. But if not then it is unrelated.

**Comment by patriknw** [comment]
One more https://jenkins.akka.io:8498/job/akka-nightly-2.12/68

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/601

**Comment by patriknw** [comment]
hm, interesting, I'll take a look

**Comment by patriknw** [comment]
Tonight's failures were not for the same reason as previously. I have created a fix for the latest failure in https://github.com/akka/akka/pull/22172, but let's keep this issue open for the original failures.
