### ISSUE TITLE
Change addr to address

### ISSUE THREAD

**Issue by bdtrunks** [akka/akka#21874]
I am new to the project and would like to begin contributing since I use akka at work. I have been looking through the source code to become more familiar with it and I noticed there are some areas where abbreviations are used instead of the fully spelled out name. This normally would not be an issue, however  both the abbreviation and the full spelling are used. I would like to update the abbreviated "addr" to the fully spelled "address" to the files where this applies.

**Comment by patriknw** [comment]
Hi @bdtrunks, your contributions are much welcome. Please open a pull request and we can discuss the details of addr.

**Comment by Chuwiey** [comment]
#in-progress

**Comment by ktoso** [comment]
Please link to the PR which is in progress with it so we don't have to re-do the search process :-)
Refs https://github.com/akka/akka/pull/21885/

**Comment by jiminhsieh** [comment]
@Chuwiey Do you still work on this?

**Comment by ktoso** [comment]
The previous PR seems to have died out of innactivity so I'd assume it's not active.
If you want to pick it up please do @jiminhsieh, thanks!

**Comment by Chuwiey** [comment]
@jiminhsieh did custodial on this to mark as "in progress" looks like the pr dropped.

**Comment by jiminhsieh** [comment]
@Chuwiey I simply thought you were working on this, then I would move on to others. :)

**Comment by ktoso** [comment]
>  did custodial on this to mark as "in progress" looks like the pr dropped.

Due to inactivity, yes as explained here after a few times of trying to reach out:
https://github.com/akka/akka/pull/21885#issuecomment-281342005

Thanks for picking it up again
