### ISSUE TITLE
Improve CircuitBreaker documentation

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21879]
CircuitBreaker documentation is very sparse. Especially, the concrete use-cases are only "documentated" by pasting examples.

Apart from the general introduction to circuit breakers it should more concretely explain (in addition to just show):
 * How to use it with an actor based API?
 * How to use it with a future based API?
 * How to use it with a synchronous API?
 * How to use the low-level features?

**Comment by richard-imaoka** [comment]
Hi @jrudolph, I was thinking to work on this, but could you tell me what " actor based API?" is?

I know, future, sync, and low-level APIs but am not aware of the actor based API. Or is it akka.contrib.circuitbreaker.sample under akka-contrib?

**Comment by Chuwiey** [comment]
looks like this is already implemented? or was the intent to go further than what is already documented here: http://doc.akka.io/docs/akka/current/common/circuitbreaker.html ?

The four questions are answered in the docs, but not as individual sections with their own headers..

**Comment by Chuwiey** [comment]
I've started working on this. Should be done soon.

**Comment by johanandren** [comment]
Refs #21298

However, could it be that it is not really needed with the graceful shutdown changes we are doing right now?

**Comment by Chuwiey** [comment]
please mark as in progress (or done) based on PR #22011
