### ISSUE TITLE
NoSuchMethodError when creating new ActorSystem

### ISSUE THREAD

**Issue by edenfisher** [akka/akka#21878]
Hello,
I'm trying to create a simple rest api with akka http(wrapping a spark job submission).
I just cant make the akka library seamlessly . I have 2.4.9 version of akka, scala 2.11.7 and JDK 1.8.
Right now, I get the following error:

> Execption in therad "main" java.lang.NoSuchMethodError: scala.runtime.BooleanRef.create(Z)Lscala/runtime/BooleanRef;

Any ideas?
Thanks

**Comment by drewhk** [comment]
What are the explicit versions that you use? This looks like a version mismatch somewhere.

**Comment by ktoso** [comment]
Very sure this will be about version mismatch - please make sure all akka modules have the same version.
Closing until provided with precise info.

**Comment by edenfisher** [comment]
I explicitly wrote the precise versions. Again, all akka jars are 2.11-2.4.9

**Comment by drewhk** [comment]
Can you try with Scala 2.11.8? Akka 2.4.9 was published against that version. It should not matter, but maybe the scala compiler introduced a binary compatibility break somehow. Btw, latest Akka version is now 2.4.12, please use that, there is no reason to use old patch versions.

**Comment by patriknw** [comment]
Are you sure that you are not running with Scala 2.10 for some reason?

**Comment by drewhk** [comment]
The stacktrace would likely also help

**Comment by edenfisher** [comment]
This is the stacktrace:
> at akka.util.SubclassifiedIndex.innerAddValue(SubclassifiedIndex.scala:120)
> at akka.util.SubclassifiedIndex.addValue(SubclassifiedIndex.scala:117)
> at akka.event.SubchannelClassification$class.subscribe(EventBus.scala:147)
> at akka.event.Eventstream.subscribe(EventStream.scala:57)
> at akka.event.Eventstream.subscribe(EventStream.scala:28)
> at akka.event.LoggingBus$$anonfun$setUpStdoutLogger$3.apply(Logging.scala:80)
> at akka.event.LoggingBus$$anonfun$setUpStdoutLogger$3.apply(Logging.scala:80)
> at akka.collection.Iterator$class.foreach(Iterator.scala:727)
> at akka.collection.AbstractIterator.foreach(Iterator.scala:1157)
> at akka.collection.IterableLike$class.foreach(IterableLike.scala:72)
> at akka.collection.AbstractIterable.foreach(Iterable.scala:54)
> at akka.event.LoggingBus$class.setUpStdoutLogger(Logging.scala:80)
> at akka.event.LoggingBus$class.setUpStdoutLogger(Logging.scala:91)
> at akka.event.EventStream.startStdoutLogger(EventStream.scala:28)
> at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
> at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)

This is most of it.

**Comment by edenfisher** [comment]
Hey,
I also tried using the scala 2.11.8 version with  no success.

**Comment by matsluni** [comment]
Hi,

you mentioned that you wrap a spark job submission. Do you have spark on the classpath? Which version of spark do you depend on (if so)?  I think it also brings in akka as a dependency.

**Comment by edenfisher** [comment]
I tried to create another project,without any spark and I'm facing the same issues.

**Comment by ktoso** [comment]
Please provide your dependencies - by full I mean also things that might have pulled in a different version of akka etc. Pasting your build.sbt for example. I still don't think it's something Akka broke - we see these errors once in a while, and it's always some mixed up dependencies :)

**Comment by edenfisher** [comment]
Thanks @ktoso
I had some dependencies broke akka some why..
Now works 😀

**Comment by ktoso** [comment]
![](https://www.colourbox.de/preview/8229259-case-closed-grunge-blue-stamp.jpg)

😎

**Comment by matsluni** [comment]
Just for the record there is: https://github.com/jrudolph/sbt-dependency-graph where you can output your whole classpath with all dependencies. There you can see which of your dependencies pulls in other dependencies transitively.
