### ISSUE TITLE
Add BalancingHub stream elements

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21880]
Similar to BroadcastHub but which balances elements according to a strategy to the current Subscribers.

**Comment by patriknw** [comment]
We also need `RouteHub` (similar to `partition`)

**Comment by inakov** [comment]
I would like to do that. I'll start with the RouteHub, because is something I needed once. I'll PR this week.

**Comment by patriknw** [comment]
excellent, much needed feature
