### ISSUE TITLE
API for ActorSystemSettings

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21894]
To support compile time [dependency injection of serializers](https://github.com/lagom/lagom/issues/272) in Lagom we need a programatic API to define serializers. There might be more such settings (in the future) so we should make a general solution.

We discussed a solution to add such settings to a new `ActorSystem.apply` method. They could be defined in a similar way as extensions so that there could for example be `SerializationSettings` and `RemoteSettings`.

**Comment by johanandren** [comment]
I'd like to pick this one up next week.

**Comment by talp-traiana** [comment]
Good idea. Another thing I would like to be able to configure at runtime would be dispatchers.
