### ISSUE TITLE
regression: noisy logging in akka 2.4.x

### ISSUE THREAD

**Issue by fommil** [akka/akka#21895]
when upgrading from akka 2.3 to 2.4 in https://github.com/ensime/ensime-server we get a **lot** of this kind of thing in our stdout in CI

```
[DEBUG] [11/27/2016 10:22:33.967] [default-akka.actor.default-dispatcher-10] [akka://default/system] received AutoReceiveMessage Envelope(Terminated(Actor[akka://default/user]),Actor[akka://default/user])
[DEBUG] [11/27/2016 10:22:33.967] [default-akka.actor.default-dispatcher-10] [EventStream] shutting down: StandardOutLogger started
```

this despite having set up slf4j and everything working nicely going to files before, e.g. 

- https://github.com/ensime/ensime-server/blob/2.0/core/src/main/resources/application.conf
- https://github.com/ensime/ensime-server/blob/2.0/core/src/test/resources/application.conf
- https://github.com/ensime/ensime-server/blob/2.0/core/src/it/resources/application.conf

there should be no output to stdout with the settings we are using. // @bwmcadams

**Comment by patriknw** [comment]
@fommil Are you sure that you don't use `akka.stdout-loglevel = "DEBUG"`?

When I try with `stdout-loglevel=DEBUG` I can see the two stdout log messages as expected, but otherwise I can't reproduce. Can you help us to create a minimized sample? This is what I tried:

```scala
package foo

import akka.actor.ActorSystem
import akka.actor.PoisonPill
import akka.testkit.TestActors
import com.typesafe.config.ConfigFactory

object MyApp extends App {
  val conf = ConfigFactory.parseString("""
    akka {
      log-config-on-start = off
      loggers = ["akka.event.slf4j.Slf4jLogger"]
      logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

      loglevel = "DEBUG"
      #stdout-loglevel = "OFF"

      actor {
        debug {
          receive = on
          autoreceive = on
          lifecycle = on
          #fsm = on
          event-stream = on
          unhandled = on
        }
      }
    }
    """)
  val system = ActorSystem("sys", conf)

  val a = system.actorOf(TestActors.echoActorProps)
  // auto receive message
  a ! PoisonPill

  Thread.sleep(10000)
  system.terminate()
}
```

with logback conf:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>SLF4J: %date{ISO8601} %-5level %logger %X{akkaSource} %X{sourceThread} - %msg%n</pattern>
    </encoder>
  </appender>
  <root level="error">
    <appender-ref ref="STDOUT" />
  </root>
</configuration>
```

**Comment by fommil** [comment]
Definitely using OFF. I'll try to minimise the problem, as it seems to be subtler than I thought. Might be a few days, busy week. Thanks for trying to repro.

**Comment by fommil** [comment]
hmm, I'm really struggling to minimise this. But what I can show is that if I do a

```
println(ConfigFactory.load())
```

during a test that exhibits the problem, it definitely has 

```json
        "stdout-loglevel": "OFF",
```

**Comment by patriknw** [comment]
Thanks for the update. It happens during the shutdown, right?

**Comment by fommil** [comment]
yeah, that's right

**Comment by patriknw** [comment]
and to be completely sure you should `println(system.settings)` where system is the ActorSystem

**Comment by fommil** [comment]
good point, but it is the same

```
        # application.conf @ file:/home/fommil/Projects/ensime-server/core/target/classes/application.conf: 9
        "stdout-loglevel" : "OFF",
```

**Comment by fommil** [comment]
I tried to repro here: https://github.com/fommil/akka-printlns with `sbt runMain foo.MyApp` but I can't get it to log out the printlns even if I don't have the stdout line in `resources.conf`

To minimise, I may have to start from an ensime spec that exhibits the problem and work backwards...

**Comment by fommil** [comment]
ok! I minimised it. No idea what is going on, but converting to a scalatest seems to have triggered it.

**Comment by fommil** [comment]
just run `sbt test` and see

```
> test
...
[info] MyTest:
[info] Akka
14:52:59.729 [default-akka.actor.default-dispatcher-2] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:52:59.734 [default-akka.actor.default-dispatcher-2] DEBUG akka.event.EventStream - logger log1-Slf4jLogger started
14:52:59.735 [default-akka.actor.default-dispatcher-2] DEBUG akka.event.EventStream - Default Loggers started
14:52:59.758 [default-akka.actor.default-dispatcher-4] DEBUG akka.event.EventStream - shutting down: StandardOutLogger started
[info] - should respond to echo
```

**Comment by fommil** [comment]
I could probably turn this into a failing test if it would help (e.g. capture the `Console.out` and grep for contents)

**Comment by patriknw** [comment]
Excellent, I'll take a look

**Comment by patriknw** [comment]
@fommil That is not the same log format as you initially reported.
Compare
```
[DEBUG] [11/27/2016 10:22:33.967] [default-akka.actor.default-dispatcher-10] [EventStream] shutting down: StandardOutLogger started
```
vs
```
14:52:59.758 [default-akka.actor.default-dispatcher-4] DEBUG akka.event.EventStream - shutting down: StandardOutLogger started
```

The latter is from the slf4j logger, which is as expected.
The former looks like the format of the `DefaultLogger` or `StandardOutLogger` (they use same format). I'm pretty sure it's from the `DefaultLogger`. For some reason `akka.loggers` maybe wasn't set in your original test?

You can see it if you use `#loggers ` in the application.conf of the minimized test.

You can also see that it's silent if you add `"ch.qos.logback" % "logback-classic" % "1.1.3"` dependency and logback.xml with `level="error"`.

**Comment by fommil** [comment]
oh damn, you're right... I haven't got a logback file in the "minimal repro" have I? I've updated the repo. Back to the drawing board...

**Comment by fommil** [comment]
FYI to reproduce with ensime-server, check out https://github.com/ensime/ensime-server/ and type `sbt core/testOnly *FileWatcherSpec`

**Comment by patriknw** [comment]
@fommil I found the issue when debugging FileWatcherSpec. The LoggingMailbox was new in 2.4 and it didn't check the loglevel when draining it's messages when shutting down. PR in progress https://github.com/akka/akka/pull/21949

**Comment by fommil** [comment]
awesome! I'd given up all hope. Thank you so much!

**Comment by fommil** [comment]
awesome, thank you so much! Looking forward to the release.

**Comment by patriknw** [comment]
you're welcome, thanks for reporting
