### ISSUE TITLE
Handle AbstractMethodError etc in the root guardian by writing "fix your akka version"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21891]
Since people often "blame Akka" if they see AbstractMethodError, whereas 99% of the cases are misconfigured dependencies. We can handle that by explaining in the log statememt

**Comment by drewhk** [comment]
I think https://docs.oracle.com/javase/7/docs/api/java/lang/IncompatibleClassChangeError.html covers all the relevant cases.

**Comment by ktoso** [comment]
Putting back as not entirely sure where to put the catch to be actually useful.
