### ISSUE TITLE
Unused private package for each module

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21899]
We somehow generate a Private-Package for each module with a package name based on the modules group-id:

```
[warn] bnd: Unused Private-Package instructions, no such package(s) on the class path: [com.typesafe.akka.distributed.data.experimental.*]
```

This can be seen for each module in the nightly builds: https://jenkins.akka.io:8498/job/akka-publish-nightly/574/consoleFull

We should get rid of this.

**Comment by helena** [comment]
I still see this issue, replicate with ```sbt akka-actor/package```

[info] Validating all packages are set private or exported for OSGi explicitly...
[warn] bnd: Unused Private-Package instructions, no such package(s) on the class path: [akka.osgi.impl]

**Comment by patriknw** [comment]
Obsolete, see https://github.com/akka/akka/issues/28304
