### ISSUE TITLE
akka-typed-experimental should depend on akka-testkit in scope "test"

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#21916]
currently:

https://repo1.maven.org/maven2/com/typesafe/akka/akka-typed-experimental_2.11/2.4.14/akka-typed-experimental_2.11-2.4.14.pom

`akka-typed-experimental` depends on `akka-testkit` in scope "compile"

**Comment by ktoso** [comment]
Whoop :O Would you submit a fix if possible?

**Comment by patriknw** [comment]
This is a duplicate of https://github.com/akka/akka/issues/21524
It's a bit more work than just changing the scope of the dependency, but it should be done.
Contribution to the other ticket is of course welcome.
