### ISSUE TITLE
Race condition in balancing dispatcher?

### ISSUE THREAD

**Issue by rsujak** [akka/akka#21914]
Hi,
I've encountered a problem in my application which is connected with balancing dispatcher. To me it seems to be a race condition between one actor which is sending a message via router to mailbox and other actor which ends processing message and checks if there is any more messages in mailbox to register for execution again.
I've wrote sample app to reproduce this bug. Here is the link to repo: https://github.com/rsujak/akka-balancing-test
Looking at the source code and running it would be better than trying to understand my explanation of the problem, but I'll try.
Pool of actors A communicate with pool of actors B via ask pattern and blocking waiting for response(I know it's not the best solution). Problem only occurs when 47/48 actors B are doing some time-consuming task or are blocked waiting for some resource e.g. db lock and 1 left actor B is processing other incoming messages. To simulate time-consuming tasks in this sample app actors B are waiting on semaphore. The problem is that sometimes message stuck in the mailbox of actor B and it isn't processed despite the fact that there is one actor waiting in execution service for a task. So in this scenario this sample application blocks until timeout elapsed and never respond to all of 1000 requests.

**Comment by patriknw** [comment]
Interesting, thanks for reporting

**Comment by johanandren** [comment]
I have taken a look at the sample, and as far as I can see it works as expected:

for every message to an actor of type A it sends `Lock` to a random actor B which acquires the semaphore, it then sends 5 workload messages to random actor Bs, and finally an `Unlock` to a random actor B which releases the semaphore. 

As you are using round-robin pools there is no guarantee you are sending the subsequent messages from A to the same instance of B. This means that all `Unlock` messages could end up in the same actor for example. So there is a risk that at some point you have acquired the semaphore on all Actor-Bs and then send subsequent `Lock` messages to them depleting the threadpool for your Bs at which point messages will start piling up and `asks` from A will start timing out. 

You can see this in a thread dump where most of the `b.pool-dispatcher` threads are `WAITING` on `java.util.concurrent.Semaphore.acquire` when your sample app has gotten stuck.

In general you should _never_ mix the Java concurrency primitives with Actors.
