### ISSUE TITLE
Allow java8 lambdas to be used in GraphStage#setHandler

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21917]
By providing some simpler api we could make it possible to use lambdas in GraphStage - if only overriding the onPull / onPush - and not needing to override the other ones.

E.g.

```java
{
  setHandler(in, () -> push(out, grab(in)));
}
```

This currently does not work. Will it work when the scala source was Scala 2.12? I think so, but am not completely sure.

Our examples in Java should make use of these if possible,
perhaps this means we need to compile using 2.12 "by default" and 2.11 "otherwise".

---

An alternative would be to allow "simple handlers"

```java
setSimpleHandler(Inlet, Runnable (which only delegates the onPush) // use setHandler if you need other callbacks.

**Comment by patriknw** [comment]
Please only assign open tickets to next patch release if it's known that it will be included or very urgent, e.g. critical bug. Otherwise we just get a pile of tickets that we shuffle in front of us. For most things I don't organize tickets by milestone until they are closed (good exception is 3.x)

**Comment by patriknw** [comment]
Compiling with 2.12 by default is not nice because then it's too easy to start using things in 2.12 (e.g. something new in library) that is not in 2.11, and then we must cross build everything (in PR validation).
