### ISSUE TITLE
Make NoMaterializer public, so Play does not have to reimplement it

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21926]
See this PR: https://github.com/playframework/playframework/pull/6767
Play was stuck on 2.4.12 because 2.4.14 changed materializer a bit.

They just need the `NoMaterializer` so we could open it up in Akka, it's akka private now,
which would avoid such issues in the future.

**Comment by ktoso** [comment]
Yes / no?
@patriknw @drewhk ?

**Comment by drewhk** [comment]
I don't think this is a good idea. What is the use case anyway?

**Comment by ktoso** [comment]
That we broke Play as they have a copy pasted NoMaterializer, and we changed materializer "SPI" (we should mark it as such somehow). Making it public would avoid breaking them like that.

Or, we look at it from the angle of we should not have broken it like that anyway...?

**Comment by ktoso** [comment]
I think it's more of an internal info that one should not expect stability of materializer API... people may be doing that.

**Comment by patriknw** [comment]
The only place we use this ourselves is in `IteratorInterpreter`, which I don't we use anywhere. Possibly in HTTP? I don't think this solves much. We don't have a stable API for `Materializer` yet, we should mention that in the scaladoc of the `Materializer` class.

**Comment by ktoso** [comment]
Yeah documenting this fact we should in any case - agreed.
That could be the outcome of this ticket, sounds ok to me.

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 1 December 2016 at 17:58:15, Patrik Nordwall (notifications@github.com)
wrote:

The only place we use this ourselves is in IteratorInterpreter, which I
don't we use anywhere. Possibly in HTTP? I don't think this solves much. We
don't have a stable API for Materializer yet, we should mention that in the
scaladoc of the Materializer class.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/21926#issuecomment-264229146>, or mute
the thread

**Comment by drewhk** [comment]
> The only place we use this ourselves is in IteratorInterpreter, which I don't we use anywhere. Possibly in HTTP?

HTTP used it in the past.

What did we break exactly? We didn't promise any stability to Materialzer implementations. We didn't broke any consumer interfaces tough.

**Comment by schmitch** [comment]
so no way of getting `NoMaterializer` public? could be final, so that it's impossible to override?

**Comment by ktoso** [comment]
Convince @patriknw and @drewhk ;)

**Comment by drewhk** [comment]
Why would you even want a NoMaterializer?

**Comment by schmitch** [comment]
Actually we use it in play, so that you can write tests without needing a materializer, (when you don't need to consume the body you don't need it).
See: https://github.com/playframework/playframework/blob/master/framework/src/play-test/src/main/scala/play/api/test/Helpers.scala#L314
