### ISSUE TITLE
InputStream from StreamConverters.asInputStream violates read() contract

### ISSUE THREAD

**Issue by noah10** [akka/akka#21943]
The [docs for InputStream.read()](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#read--) say, "The value byte is returned as an int in the range 0 to 255".  The read() method on the InputStream from StreamConverters.inputStream simply returns a raw (and therefore signed) byte, which will be in the range -128 to 127.  The following test demonstrates this:

```
import java.io.{IOException, InputStream}

import akka.stream.scaladsl._
import java.nio.file.Paths

import akka.actor.ActorSystem
import akka.stream.ActorMaterializer

object AkkaTester extends App {
  implicit val system = ActorSystem("system")
  implicit val materializer = ActorMaterializer()

  val filename = "/tmp/helloworld.txt.gz"
  var akkaInput: InputStream = _

  try {
    val path = Paths.get(filename)
    val sink = StreamConverters.asInputStream()
    akkaInput = FileIO.fromPath(path).runWith(sink)
    var akkaByte = akkaInput.read()
    while (akkaByte != -1) {
      if (akkaByte < -1) throw new IOException(s"Value $akkaByte out of range -1..255")
      println(akkaByte)
      akkaByte = akkaInput.read()
    }
  } finally {
    if (akkaInput != null) akkaInput.close()
    system.terminate()
  }
}
```

Running it throws the specified IOException. (I believe any binary data with bytes > 127 will trigger this exception. The gzip file I used was generated with "echo 'Hello, World' > /tmp/helloworld.txt; gzip /tmp/helloworld.txt". And yes, I know that in 2.4.14 Compression exists to handle gzip, but I discovered this while using 2.4.10 and verified that the problem still exists in 2.4.14.)

**Comment by drewhk** [comment]
This needs a backport to 2.4

**Comment by patriknw** [comment]
Backported in https://github.com/akka/akka/pull/21969

**Comment by patriknw** [comment]
Thanks @ortigali
