### ISSUE TITLE
Akka cluster events message classes inconsistency.

### ISSUE THREAD

**Issue by guidomedina** [akka/akka#21944]
I have a small complain about `akka-cluster's` `MemberEvent` vs `ReachabilityEvent` consistency:
- `MemberEvent` has a `member()` method.
- `ReachabilityEvent` doesn't have a `member()` method.

All subclasses of `ReachabilityEvent` have a `member()` method hence I don't see why the `member()` method can't be a the superclass, such inconsistency forces one to do typecasting like the following (where the comment states so):
```
protected void processMemberEvent(MemberEvent event) {
  if (event instanceof MemberUp) {
    registerKey(event.member());
  } else if (event instanceof MemberRemoved) {
    removeClusterMember(event.member(), true);
  }
}

protected void processReachabilityEvent(ReachabilityEvent event) {
  if (event instanceof ReachableMember) {
    // Had to cast to access member.
    registerKey(((ReachableMember) event).member());
  } else if (event instanceof UnreachableMember) {
    // Had to cast to access member.
    removeClusterMember(((UnreachableMember) event).member(), false);
  }
}
```

Maybe a further and wider investigation can be done and move up methods that are all obviously part of all subclasses?

**Comment by patriknw** [comment]
Makes sense. I'm fixing right away.

**Comment by ktoso** [comment]
Need to backport?

**Comment by patriknw** [comment]
I don't think it's critical to backport this (not a bug)
