### ISSUE TITLE
Materialized value combination does not work with identity Flows

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21955]
reproducer:

```
val ((pub, mat), sub) = TestSource.probe[Int].viaMat(Flow[Int])(Keep.both).toMat(TestSink.probe)(Keep.both).run()
```

Throws ClassCastException. The reason is simple, the DSL detects the identity Flow and simply converts viaMat(Keep.both) to a NOP. This is correct for the graph, but not for the materialized value which needs the NotUsed value coming from the empty Flow.

**Comment by ktoso** [comment]
Ouch, too smart for our own good it seems. To be fixed during your current materialization work I guess?

**Comment by drewhk** [comment]
No, I fix this right away. Not hard to do.
