### ISSUE TITLE
JsonObjectParser doesn't handle escape sequences properly

### ISSUE THREAD

**Issue by andrewrapp** [akka/akka#21961]
When the JsonObjectParser encounters a backslash it sets a state variable but does not unset it properly after the next character is handled. The bug arises when \\\\" is encountered. It does not reset isStartOfEscapeSequence to false on second \ so when it sees the double quote it assumes that it's the character being escaped and doesn't decrement the count. The net result is it will never reach completedObject = true.

**Comment by hhimanshu** [comment]
The issue is open while pull request is merged, anything else needed?

**Comment by ktoso** [comment]
No, seems to be done on master and backported to 2.4.16.
It seems we missed to close some issues in the recent backporting dances
