### ISSUE TITLE
OSGi - scala.util.parsing.combinator is imported with wrong version

### ISSUE THREAD

**Issue by domel8dp** [akka/akka#21966]
The `scala-parser-combinators` project is currently at version `1.0.4`, but `akka-stream` tries to import:
`scala.util.parsing.combinator;version="[2.12,2.13)"`

It looks like in `project/OSGi` this falls into `scala.*` import, which uses scala version.

**Comment by ktoso** [comment]
Thanks for reporting. Would you be able to submit a patch for this?

**Comment by domel8dp** [comment]
Yes, I'm working on it right now

**Comment by ktoso** [comment]
Awesome, thanks!

**Comment by briantopping** [comment]
Ha, I just built the same patch. Great to see some others using OSGi! 👍 

I had a comment on the patch, I think the version range should be up to 1.1.0 non-inclusive such that future SDKs that provide a later version can be used without issue. 

@ktoso: I'd also like to beg if this could be moved to 2.4.15? :)

**Comment by ktoso** [comment]
Sure @briantopping but please provide info or PR how exactly it should come in. We're not very expert on osgi :)

**Comment by briantopping** [comment]
Hi @domel8dp: Can you update your branch according to the.notes I made in the PR or reason why what you have is correct as it stands? I can help sign off on this and you'll be good to go!

**Comment by ktoso** [comment]
I can make the change, just wasn't sure what it's supposed to be - could you comment directly on the PR? I don't see where you mean the 1.1.0 change to be made.

**Comment by briantopping** [comment]
@ktoso: are the line notes on https://github.com/domel8dp/akka/commit/670c7ece8eb2a4a2554b0168d51f6f55c5b0b5eb Not visible on your end? Thanks!
