### ISSUE TITLE
Incoming connections not reused after re-association

### ISSUE THREAD

**Issue by jakub-vanek** [akka/akka#21979]
Akka remote 2.4.9 configured to reuse incoming connections (akka.remote.use-passive-connections = on).

Two actor systems, system A and system B. System B is behind NAT.

Both systems start up. System B sends a message to A, systems associate and messages are sent in both directions using the connection initiated from B. The connection fails (e.g. transport failure detector triggers), systems disassociate. B opens a connection by sending a message to A, systems re-associate, but when a message is sent from A to B, A attempts to establish new TCP connection instead of using the one already opened from B (as was the case right after the systems originally associated after start up).

**Comment by drewhk** [comment]
> Akka remote 2.4.9 configured to reuse incoming connections (akka.remote.use-passive-connections = on).

Please use 2.4.14 as it is the latest. 

> Two actor systems, system A and system B. System B is behind NAT.

NAT need special handling. Please read:
http://doc.akka.io/docs/akka/2.4/general/remoting.html#Peer-to-Peer_vs__Client-Server

> when a message is sent from A to B, A attempts to establish new TCP connection instead of using the one already opened from B (as was the case right after the systems originally associated after start up).

This can happen if there is a race between the message sent from A to B, then two connections will be open. In general `use-passive-connections` is just an optimization, it does not guarantee that connections will be reused. Akka remoting is not a client-server technology but a peer-to-peer technology. If you need client-server interactions use Akka IO or HTTP.
