### ISSUE TITLE
akka logging with marker

### ISSUE THREAD

**Issue by kcris** [akka/akka#21973]
Latest akka docs show the option of using Logging.withMarker.
http://doc.akka.io/docs/akka/current/scala/logging.html#Using_Markers

The Logging class does not have the withMarker member.

I cannot use this in an actor
`var log = Logging.withMarker(this)`

**Comment by ktoso** [comment]
You need to use:

```
// Logging.
def withMarker[T: LogSource](system: ActorSystem, logSource: T): MarkerLoggingAdapter = {
```

Good catch, the docs should explain that.

**Comment by kcris** [comment]
thanks, but where do I find withMarker?

**Comment by ktoso** [comment]
As I just pointed out, on `Logging`.

**Comment by kcris** [comment]
Indeed, on github I see withMarker

Looking at my local copy, I don't
...\m2\repository\com\typesafe\akka\akka-actor_2.11\2.4.11\akka-actor_2.11-2.4.11-sources.jar!\akka\event\Logging.scala

what am I missing?
Thanks a lot for your help

**Comment by ktoso** [comment]
Upgrade your dependency

**Comment by ktoso** [comment]
Latest is: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.typesafe.akka%22%20a%3A%22akka-actor_2.11%22

**Comment by kcris** [comment]
thanks, updated to 2.4.14 and withMarker is there (seems it was added in 2.4.12)

**Comment by ktoso** [comment]
Uhm, this was documented already. Closing as invalid:

```
Markers are available through the LoggingAdapters, when obtained via ``Logging.withMarker``.
The first argument passed into all log calls then should be a ``akka.event.LogMarker``. 
```
