### ISSUE TITLE
Connected Message get remoteAddress very slow

### ISSUE THREAD

**Issue by chongwuyang** [akka/akka#21982]
if (msg instanceof Connected) {
	      final Connected conn = (Connected) msg;

	      String key=conn.remoteAddress().getHostName();
}

the code conn.remoteAddress() very slow in lan. This cause the tcp connection timeout.

**Comment by patriknw** [comment]
`getHostName` is a potentially blocking call to a reverse dns lookup. We already have issue https://github.com/akka/akka/issues/21170 for this so I'm closing this ticket.
