### ISSUE TITLE
MongoDB close connection in Actor

### ISSUE THREAD

**Issue by LongIT644** [akka/akka#21984]
I get exception when interact with mongodb by plugin https://github.com/cloudinsights/play-salat/issues with play framwork for scala, in akka actor fir scheduler job.

`"exception":{"name":"class java.lang.IllegalStateException","message":"open","trace":[["org.bson.util.Assertions.isTrue(Assertions.java:36)","com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:375)","com.mongodb.Mongo.isMongosConnection(Mongo.java:622)","com.mongodb.DBCollection.findOne(DBCollection.java:936)","com.mongodb.DBCursor.one(DBCursor.java:807)"]]}`

**Comment by ktoso** [comment]
I don't see how this is an Akka issue, closing as invalid.
