### ISSUE TITLE
Solution for unreachable node getting stuck

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21999]
A three node cluster - A, B and C. A is the leader, and the following timeline:

1. Cluster has formed, all nodes are friends and things are merry
2. B becomes unreachable (paused with Ctrl+Z)
3. both A and C sees B as unreachable
4. C issues a leave
5. A has B as unreachable so cannot transition C from leaving to exiting
6. C kills itself (because it got tired of waiting on graceful leave)
7. B becomes reachable again (unpaused)
8. A see B as reachable, however, as last state gossipped from C is that it saw as B is unreachable the converged cluster state is that B is unreachable until C is downed

Question is: Could we provide a way to get B reachable before C is downed?

For example (@drewhk proposed):
> The leader should be able to DOWN nodes if it is only held back by nodes 
> that are only marked >unreachable by the nodes to be DOWNed
> i.e. the only unreachable nodes that are allowed are the ones to be leaving and 
> the ones that are > marked as unreachable by the leaving

ping @patriknw

**Comment by jgordijn** [comment]
This was a little bit confusing to me. Looking at 'http://doc.akka.io/docs/akka/2.4/common/cluster.html#State_Diagram_for_the_Member_States__akka_cluster_allow-weakly-up-members=on_' I wonder why there is a path from Leaving to Unreachable? If at least one node in the cluster knows that this node is leaving, it shouldn't this information lead to the node be removed when the cluster converges again? 

There is no way from Leaving to Up, right?

**Comment by johanandren** [comment]
Additional Endre-quote:
>  just to restate it in another way, the leader is allowed to do removals (down-ing? not sure about the proper terminology) even if there are unreachable nodes, _if_ the remaining set becomes fully reachable after removals

**Comment by patriknw** [comment]
@jgordijn `Unreachable` / `Reachable` is not a member status as `Up`, `Leaving`, `Down`. It is "only" an observation by the failure detector, i.e. orthogonal to the member status.

**Comment by patriknw** [comment]
It's an interesting case. I'm pretty sure it would be solved by downing `C`, but we should investigate if we can solve it automatically as @drewhk suggests.

**Comment by drewhk** [comment]
Yeah, DOWN-ing C works, and also DOWN-REJOIN B.
