### ISSUE TITLE
NPE in ClusterSingleton

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22004]
Seems to have happened in a live system.
Happens more than once.

```
[XXXX-akka.actor.default-dispatcher-32] () ERROR a.a.OneForOneStrategy - null
java.lang.NullPointerException
        at akka.cluster.singleton.ClusterSingletonProxy$$anonfun$receive$1.applyOrElse(ClusterSingletonProxy.scala:232)
        at akka.actor.Actor.aroundReceive(Actor.scala:484)
        at akka.actor.Actor.aroundReceive$(Actor.scala:484)
        at akka.cluster.singleton.ClusterSingletonProxy.aroundReceive(ClusterSingletonProxy.scala:132)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
```

It seems like the ActorRef in the Identity message is `null`

**Comment by patriknw** [comment]
Which version, so that we can know what `ClusterSingletonProxy.scala:232` is?

**Comment by ktoso** [comment]
I'll ask

**Comment by ktoso** [comment]
Seems to have been  2.4.14

**Comment by drewhk** [comment]
er what, so it was not null in ActorIdentity but Some(null).

**Comment by drewhk** [comment]
![](http://serif.hatelabo.jp/images/cache/e621b89923fdcfa92bc36aa87fc1f7fa92a320a8/082603d9025ca4f090797925de425d2a8e0efa6c.gif)

**Comment by patriknw** [comment]
wow, how did it end up as `Some(null)` - interesting

https://github.com/akka/akka/blob/v2.4.14/akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonProxy.scala#L232

**Comment by johanandren** [comment]
I can't think of another explanation than that one node was run with 2.12 and another with 2.11 and Java serialization was used. I'll try to confirm that causes the problem.

**Comment by johanandren** [comment]
I have confirmed that if you run cluster singleton on a 2.12 node and try to send `Identify` to it from a 2.11 node you get `null` for actorref back.

 ```
[info] [ERROR] [02/13/2017 12:47:25.690] [cluster-akka.actor.default-dispatcher-22] [akka://cluster/user/test/$a] null
[info] java.lang.NullPointerException
[info] 	at akka.cluster.singleton.ClusterSingletonProxy$$anonfun$receive$1.applyOrElse(ClusterSingletonProxy.scala:232)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:497)
[info] 	at akka.cluster.singleton.ClusterSingletonProxy.aroundReceive(ClusterSingletonProxy.scala:132)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
ok, so it's serializing `akka.actor.ActorIdentity` on 2.12 with Java serialization and that can't be correctly deserialized on 2.11. 

Can you write a unit test similar to https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/serialization/SerializeSpec.scala#L350
Then we can show that for Scala team and we'll see if they will fix it.

Otherwise I think we have to say that
* enable-additional-serialization-bindings must be used on both sides (or at least `"akka.actor.ActorIdentity" = akka-misc`
* or same scala version must be used on both sides

**Comment by patriknw** [comment]
perhaps you can even minimize the test to `scala.Some`

**Comment by johanandren** [comment]
Yep, it is, writing `Some(whatever)` in 2.12 deserializes to `Some(null)` in 2.11

**Comment by johanandren** [comment]
Damn, missed the part about a test :D
