### ISSUE TITLE
Websockets do not close socket (Akka stream)

### ISSUE THREAD

**Issue by mehdimousavi1995** [akka/akka#22036]
I'm using Akka stream for messagin project 
here is my code

```
    val updSource = Source.actorPublisher[(Int, Update)](UpdatesSource.props(botUserId, botAuthId, botAuthSid))
        .mapAsync(parallelLimit) {
          case (seq, update) ⇒ updBuilder(seq, update)
        }.collect {
        case Some(upd) ⇒ upd
      }

    val rqrspFlow = Flow[BotRequest]
      .mapAsync(parallelLimit) {
        case BotRequest(id, service, body) ⇒ handleRequest(botUserId, botAuthId, botAuthSid)(id, service, body)
      }
      .map(_.asInstanceOf[BotMessageOut])

    Flow.fromGraph(
      GraphDSL.create() { implicit b ⇒
        import akka.stream.scaladsl.GraphDSL.Implicits._
        val upd = b.add(updSource)
        val rqrsp = b.add(rqrspFlow)
        val merge = b.add(Merge[BotMessageOut](2))
        upd ~> merge
        rqrsp ~> merge
        FlowShape(rqrsp.in, merge.out)
      }
    ) 
```

when i want to merge two flows with each other `handleWebsocketMessages`
 causes the Websocket to not terminate appropriately when a client disconnects but when i use only one flow, every thing work just fine 
how can i solve this problem ?

**Comment by patriknw** [comment]
@mehdimousavi1995 This looks like an Akka HTTP ticket so please create that in https://github.com/akka/akka-http, but if you are not sure it is an issue you should first ask in the mailing list (we don't use the issue tracker for questions).
