### ISSUE TITLE
Cluster Sharding Coordinator just started in Oldest Node

### ISSUE THREAD

**Issue by marcoguillen123** [akka/akka#22034]
I have configured a Akka Cluster with Sharding with only 3 seed nodes. The Shard Coordinator is just started  on the first Node started (Oldest Node) showing this message (Sharding Coordinator was moved to the active state State(Map(),Map(),Set(),Set() ..)
The  issue is that Shard Coordinator is not started on any Younger Node by showing the message Trying to register to coordinator at [None], but no acknowledgement

 ClusterSharding(actorSystem).start(
      typeName = "MyShardActor",
      entityProps = aggregateProps(aggregateId),
      settings = ClusterShardingSettings.create(actorSystem),
      extractEntityId = extractEntityId,
      extractShardId = extractShardId)

    val shard = ClusterSharding(actorSystem).shardRegion("MyShardActor")

**Comment by patriknw** [comment]
Shard Coordinator is only supposed to start on one node, it's a cluster singleton. Perhaps the other nodes have not joined the cluster? Please use the mailing list for questions like this.
