### ISSUE TITLE
akka-stream concatenated Sources always evaluates first element in each Source.

### ISSUE THREAD

**Issue by ANorwell** [akka/akka#22042]
When concatenating Sources created via `Source.unfoldAsync`, the unfolding of every source begins immediately, rather than waiting for previous sources to be consumed.

This is problematic when using e.g. akka-http, because it allows a maximum number of concurrent outgoing requests, and a set of concatenated `Source.unfoldAsync` that make http requests will exceed this limit. It also means that a source that is later truncated (e.g. `take(5)`) will do un-necessary work.

Here is reproduction code:

```scala
object Test2 extends App {
  import akka.actor._
  import akka.stream.scaladsl._
  import akka.stream.ActorMaterializer
  import scala.concurrent._
  import scala.concurrent.duration._

  implicit val system = ActorSystem()
  implicit val mat = ActorMaterializer()

  val source = Source.unfoldAsync(0) {
    case 0 ⇒
      println("unfolding 0")
      Future.successful(Some((1, 0)))
    case 1 ⇒
      println("unfolding 1")
      Future.successful(None)
  }

  Await.result(source.concat(source).take(0).runWith(Sink.ignore), 5.seconds)
  system.terminate()
}
```

This will print "unfolding 0" twice, despite the fact that 0 elements are taken. Another example showing that this is not related to `take(0)`:

```scala
val concat = (0 until 100).foldLeft(Source.empty[Int])( (acc, _) => acc.concat(source))
concat.throttle(1, 1.second, 1, akka.stream.ThrottleMode.Shaping).runWith(Sink.ignore)
```
Would print "unfolding 0" many times immediately without throttling.

**Comment by ANorwell** [comment]
Note that `flatMapConcat` doesn't have this issue. The examples here can be fixed with `flatMapConcat`. I believe the reason `concat` has this issue is that it creates a multi-source graph, and uses backpressure to limit the subsequent sources, which does not stop the first element from being emitted.

**Comment by viktorklang** [comment]
I'm surprised that it prints anything at all—take(0) should make the concat operation a noop.

**Comment by drewhk** [comment]
@ANorwell 

>  I believe the reason concat has this issue is that it creates a multi-source graph, and uses backpressure to limit the subsequent sources, which does not stop the first element from being emitted.

Yes, this is the reason. Concat is translated to a graph containing a single `Concat` node that prefetches on both sides. This also means that the two sources are materialized together independently of the completion of the first. This is way more efficient than `flatMapConcat` and hence the default. If you need lazily materialized sources for concatenation purposes you must use `flatMapConcat`. Even if `concat` itself would not prefetch, there would be no guarantee that another stage like `mapAsync` does not prefetch. 

> I'm surprised that it prints anything at all—take(0) should make the concat operation a noop.

There is no such transformation as it would be extremely costly given it would require graph pattern matching to detect that. Also, there are side-effects of that transformation that are just as surprising. Btw, this has been discussed many times before, even back than when there was an office in Uppsala.

**Comment by viktorklang** [comment]
@drewhk I didn't mean as optimization step, but as implementation of take(0) (the GraphStage).

**Comment by drewhk** [comment]
it is not take, but concat that does the prefetch. I.e. it takes one element upfront without waiting for take(). All of our fan-in stages, including concat are prefetching because otherwise certain graphs will deadlock. Whether such deadlock is "expected" or not was a deep discussion back then. It is "expected" if you are an expert, but completely unintuitive if you are a newcomer. Intuitive was chosen over the "theoretically right" back then. Sometimes hard decisions need to be made :)

**Comment by drewhk** [comment]
In particular, the main issue was that deadlock was dependent on whether the graph was fused or not.

**Comment by viktorklang** [comment]
@drewhk Now I remember those conversations—yes! :-)

**Comment by drewhk** [comment]
Yeah, these tend to return. I am not sure now whether it was the "right" choice, but there is no way to go back now :)

**Comment by viktorklang** [comment]
With the mindset that each op is concurrent, and there's at least 1 element prefetch for pipeline  priming, I think most observed behaviours in this regard are self-explanatory. I'd venture guessing that a complicating factor is that both the prefetch and the concurrency is invisible in the code. :)

**Comment by drewhk** [comment]
When it comes to fused I always prefer prefetch-less wherewere possible, but graph stages are a bit special in this case because of cycles. Making these always-prefetch was something that we did right before the 2.0 release, when we enabled fusing by default. Without prefetch some cycles just don't start and keep being deadlocked.
