### ISSUE TITLE
run tests with Scala 2.12

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22045]
The jenkins job https://jenkins.akka.io:8498/job/akka-nightly-2.12 is not running with 2.12.

I have created a system property for the scalaVersion that we can use.
https://github.com/akka/akka/pull/22044/files#diff-0ecdbc5a001d52fb34f5eafb7cd1aaa6R21

There are also some tests that are not passing, e.g. `akka-remote-tests > multi-jvm:testOnly akka.remote.NewRemoteActor`

**Comment by johanandren** [comment]
Waiting for  #22218 to be merged

**Comment by johanandren** [comment]
Job configured but failing with "java.lang.IllegalArgumentException: pre-creation serialization check failed at" in some tests, something is not serializable with 2.12 that was with 2.11?

**Comment by bantonsson** [comment]
Is something happening with this ticket? I could pick it up if there are still problems since we would like to have this working for cinnamon nightlies as well.

**Comment by johanandren** [comment]
It is up and running, I think I just forgot closing the ticket, sorry!
