### ISSUE TITLE
incorrect documentation for akka persistence journal plugin

### ISSUE THREAD

**Issue by BertRobben** [akka/akka#22066]
There is a small bug in the documentation for the akka persistence journal plugin.

The documentation mentions:

> The journal plugin class must have a constructor with one of these signatures:
> 
> constructor with one com.typesafe.config.Config parameter and a String parameter for the config path
> constructor with one com.typesafe.config.Config parameter
> constructor without parameters
> The plugin section of the actor system's config will be passed in the config constructor parameter. The config path of the plugin is passed in the String parameter.

However the implementation only accepts a constructor with one Config parameter or a constructor without parameters. The config path of the plugin is never passed explicitly, but is available as the name of the journal actor.

Bert

PS: Due to company policy, I'm not able to provide a pull request.

**Comment by ktoso** [comment]
Please always provide which Akka version you're using when reporting things.
In this instance, you're using an old Akka version I bet, as in the latest 2.4.16 this is exactly what was added: https://github.com/akka/akka/commit/57e59c84966d982ac72cbbe3a839dcb70bebb373#diff-e96a567a5bb29479ebff5fc1a79acd4bR292

**Comment by BertRobben** [comment]
You're absolutely right. I'm using 2.4.9 and was looking at the current version's doc.

**Comment by ktoso** [comment]
No problem, happy hacking! Please upgrade though, it's all compatible so there's no reason to stay on older patch versions 👍
