### ISSUE TITLE
 Discrepancy Between Code and Documentation

### ISSUE THREAD

**Issue by jwair** [akka/akka#22070]
There seem to be a discrepancy between the code and the documentation of the Balancing Pool Router.

[The documentation states that](http://doc.akka.io/docs/akka/current/scala/routing.html#BalancingPool):
> The BalancingPool automatically uses a special BalancingDispatcher for its routees ...

However the JavaDoc comment of the constructor indicates that it [uses the dispatcher passed to its constructor](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/routing/Balancing.scala#L64#L66):
```
... 
   * @param routerDispatcher dispatcher to use for the router head actor, which handles
   *   supervision, death watch and router management messages
   */
@SerialVersionUID(1L)
final case class BalancingPool(
  override val nrOfInstances:      Int,
  override val supervisorStrategy: SupervisorStrategy = Pool.defaultSupervisorStrategy,
  override val routerDispatcher:   String             = Dispatchers.DefaultDispatcherId)
  extends Pool {
...
```

**Comment by patriknw** [comment]
Isn't this the dispatcher for the "head" router, not the dispatcher for the routees?
http://doc.akka.io/docs/akka/2.4/scala/routing.html#Configuring_Dispatchers

**Comment by raboof** [comment]
I agree there doesn't seem to be a discrepancy (there's intentionally a different dispatcher for the head actor than there is for the routees), but I do agree the docs are a bit dense here. Might be a good place to try and come up with a diagram?
