### ISSUE TITLE
Source.fromFunction / Source.continually - shortcut to eval a function for every emit

### ISSUE THREAD

**Issue by svezfaz** [akka/akka#22074]
Not sure if this has been asked already. I find it very common to construct a Source along the lines of `Source.repeat`, but with the need of evaluating a function and producing a new element every time the source emits.

I usually end up writing `Source.cycle(() => Iterator(Random.nextInt()))` . I'm writing here to check if anyone might deem useful to have a shortcut in `Source.scala` - with a meaningful name (e.g. `Source.fromFunction`, or `Source.continually`).

**Comment by ktoso** [comment]
As it's effectively just `Source.repeat(NotUsed).map(_ => new Thing)` I'm not sure it warrants a special operator.

**Comment by patriknw** [comment]
Sounds good to not add a special operator for this. Would be good to document it in the [cookbook](http://doc.akka.io/docs/akka/2.4/scala/stream/stream-cookbook.html). Can you create a pull request updating the documentation, @svezfaz ?

**Comment by svezfaz** [comment]
Makes sense to me. I'll create a PR in a few days.
