### ISSUE TITLE
akka cluster - observer nodes exposed via JMX

### ISSUE THREAD

**Issue by fflatorre** [akka/akka#22090]
The current CLI provides already a bunch of helpful commands :
http://doc.akka.io/docs/akka/2.4/scala/cluster-usage.html#cluster-command-line-scala

However, given there are some heuristics based on convergent behaviour of all the observes nodes (i.e. failure detection, reachable/unreachable tags etc), in order to facilitate the debug would be good to have in member-status and/or cluster-status, for each node, the list of its observer nodes, or even create a separate command.

**Comment by ktoso** [comment]
On a related note, have you seen: https://github.com/akka/akka-cluster-management ?

**Comment by fflatorre** [comment]
Thanks for pointing my out to this very interesting initiative, it looks very promising. 
I can see it as a long term solution and tooling integration enabler, either way very welcome !

Leveraging my little scala I can see the list of observers is only provided for unreachable nodes :
https://github.com/akka/akka-cluster-management/blob/master/cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala#L59

which makes perfectly sense and is a great start.
However would be good to always be able to know who observes who, especially in case you want to monitor (efficiently) the evolution of the transition reachable => unreachable, which is something we think is causing some troubles in one of our test scenario.

**Comment by raboof** [comment]
I think we're increasingly adding these kinds of features to https://github.com/akka/akka-cluster-management and they're not that interesting to add to JMX anymore. Closing for now, feel free to reopen if you have a strong use case for doing this in JMX.
