### ISSUE TITLE
RFE: expose aeron sink/source

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#22096]
1) Re: http://blog.akka.io/artery/2016/12/02/streams-in-artery
complete transport streams are too heavy for stream-centric applications:
`app-source -> artery -> aeron-sink > net > aeron-source -> artery -> app-sink`

2) it would help to expose bare aeron sink/source similar to [stream/scaladsl/Tcp](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala) for direct streaming use cases:
`app-source -> aeron-sink > net > aeron-source -> app-sink`
such that `akka-stream` can finally replace `kafka` :-)

**Comment by ktoso** [comment]
I'd argue that "too heavy" claims need to be backed up with data ;-)

Also, that'd be underestimating what Akka gives you, it's more than just "slap it onto Aeron".

What you're looking for is very likely more https://github.com/akka/alpakka/pull/69 than it is "expose aeron source/sink". We're aiming to provide a Reactive Socket sink/source eventually. That, in my opinion, will be much more useful and allow building more higher level things on top. The transport we'd use for Reactive Socket would be Aeron.

The Reactive Socket integration will be part of Alpakka, so I'd propose to close this ticket.

**Comment by Andrei-Pozolotin** [comment]
1) Re: "need to be backed up with data"  - here is the "data": with `artery` in the pipe, how can one avoid akka message `header` overhead plus the obligatory `serialize/deserialize` trip instead of direct `disk -> wire -> disk` zero-copy for kafka-like use case?

2) Re: "Reactive Socket integration" - looks like it may take "never" to materialize, while exposing aeron is "almost" there, as shown by [this little hack](https://gist.github.com/Andrei-Pozolotin/4dd4f86ae90efd648ca9708bc12be393): need only more generic `pool` , free `type` parameters and public `factory` for aeron `sink/source`.

![image](https://cloud.githubusercontent.com/assets/1622151/21620705/41627a80-d1bb-11e6-8ea2-84746b172cc8.png)

**Comment by patriknw** [comment]
We can't take on maintenance of everything. Almost there as an internal implementation compared to a fully supported API is completely different things. Sorry. Sounds like a nice little project by itself.

**Comment by unoexperto** [comment]
@Andrei-Pozolotin How did you end up implementing this ?

**Comment by Andrei-Pozolotin** [comment]
@unoexperto using akka internals directly
