### ISSUE TITLE
[cluster-sharding] Consistent hash shard allocation

### ISSUE THREAD

**Issue by haggy** [akka/akka#22107]
Hi there,

I've been reading and re-reading all the docs (and now digging through source) about how the `ShardCoordinator` allocates/routes messages to each shard region. The issue I have is each one of the messages is coming off a queue and has a "sender ID" on it that remains consistent for each sender. For a given sender ID, I want the messages to be consistently routed to the same shard region every time. This seems like it *_should_* already happen but I have a good amount of metrics built up that seem to indicate to me that it is not consistently routing to the same shard region for a given sender ID.

### ShardId resolver
```scala
val shardResolver: ShardRegion.ExtractShardId = {
    case fm: FreshMessage => 
      (math.abs(fm.senderId.hashCode) % ShardCount).toString
}
```

Based on this code alone, I would expect that if we have sender ID of `ABCD` which resolves to a shard ID of `2`, then every message from that sender should be consistently routed to the same shard region. Is my understanding of how this _should_ work correct?

**Comment by patriknw** [comment]
Your understanding is correct. Please use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) for questions, we don't use the issue tracker for questions.

**Comment by haggy** [comment]
Ah OK well thank you for clarifying and I'll use the mailing list for questions from now on.
