### ISSUE TITLE
Memory leak in Play akka.actor

### ISSUE THREAD

**Issue by bidhu007** [akka/akka#22100]
I am performance testing (@100 RPS) an app built using Playframework and observed memory leak.
The Playframework version I have tested with are 2.5.5, 2.5.6, 2.5.7 and 2.5.8 and all these versions are showing same memory issue.
Monitored the load runs with JvisualVM and JMC, found that GC runs but overall memory footprint keeps on increasing and after reaching max heap, the server throws OOO message and GC overhead limit error.
![image](https://cloud.githubusercontent.com/assets/23099642/21644757/086ac232-d2b5-11e6-9166-a9f35324ff0c.png)

Heap dump analysis through Eclipse MAT is showing " "akka.actor.LocalActorRef" loaded by "play.runsupport.NamedURLClassLoader" as the prime suspect of memory leak.
![image](https://cloud.githubusercontent.com/assets/23099642/21644828/7da8a000-d2b5-11e6-8498-4ea96711d245.png)

Further drill down is showing some red-black tree is accumulating memory with time.
![image](https://cloud.githubusercontent.com/assets/23099642/21644866/a51c7c7e-d2b5-11e6-88ce-34d24a065ae0.png)

Need help to get to root cause and resolve issue.

**Comment by ktoso** [comment]
This could be anything, including you leaking your own actors and never stopping them.
Please find out what actor (their names) is leaking, otherwise I'm inclined to close this as it's very likely not an Akka issue.

**Comment by bidhu007** [comment]
1. How can we find the actors which are leaking.
2. How can we close akka actors explicitly.

**Comment by ktoso** [comment]
> How can we find the actors which are leaking.

Use some kind of monitoring (lightbend monitoring, kamon). or find the names in the profiler - browse around the tree, you'll find the names in actor cell.

> How can we close akka actors explicitly.

Actors live as long as you don't stop them. As simple as that, please read the documentation (github issues is *not* a support channel):  http://doc.akka.io/docs/akka/2.4.16/scala/actors.html

**Comment by bidhu007** [comment]
I used monitoring tools like JvisualVM and JMC and both are showing redblack tree is retaining heap memory. 
Let me do some more analysis and test after closing actors explicitly.

**Comment by ktoso** [comment]
It's not the tree's fault - it's just the container ;-) Figure out which actors that are.
Closing for now. Please open if this can be tracked to an issue in Akka itself, if not then it's not an issue that should be on this issue tracker.
