### ISSUE TITLE
Node can not join to the cluster 

### ISSUE THREAD

**Issue by lwsbox** [akka/akka#22114]
the akka version is 2.3.14

we found that cluster node does not send "join" to seed node after receives the "InitJoinAck", so 
the node can't join the cluster.

Further work, we found that TcpClientHandler receives the "InitJoinAck" datagram, but ClusterCoreDaemon can't get the "InitJoinAck" message.

If we reset the socket (such as reboot the seednode), everything would be done well.

we add some log info to source code, you can track info in akka.txt as follows:

	keyword: "send initJoin to"  and "73, 110, 105, 116, 74, 111, 105, 110, 65, 99, 107"

	"73, 110, 105, 116, 74, 111, 105, 110, 65, 99, 107"  is  the encoding of "InitJoinAck"		

It is hard to reappear this bug, but has came out several time. (keep rebooting one node randomly for a long time)

[akka.txt](https://github.com/akka/akka/files/692597/akka.txt)

**Comment by patriknw** [comment]
Sounds strange.

Is "send initJoin to" a logging you have added yourself? Note that you can enable logging of sent and received messages: http://doc.akka.io/docs/akka/2.4/scala/logging.html#Auxiliary_remote_logging_options

**Comment by lwsbox** [comment]
Is "send initJoin to" a logging you have added yourself?    
>> yes，[ClusterDaemon.scala.txt](https://github.com/akka/akka/files/695047/ClusterDaemon.scala.txt)  

 Note that you can enable logging of sent and received messages: http://doc.akka.io/docs/akka/2.4/scala/logging.html#Auxiliary_remote_logging_options
>> thanks.  this option would be usefull.
