### ISSUE TITLE
TimerBasedThrottler rate limit should be applied to a moving window

### ISSUE THREAD

**Issue by VRanga000** [akka/akka#22119]
TimerBasedThrottler currently measures the rate at each timer tick within the window since the last tick. This could cause wide variations in instantaneous message throughput (as noted in the code comments by the authors). This makes the throttler unsuitable for rate limiting messages, especially to external services. Using a moving window to measure the rate would mitigate this limitation.

**Comment by drewhk** [comment]
Use Streams and the `.throttle()` combinator instead.

**Comment by drewhk** [comment]
Ah, I see there is a fix https://github.com/akka/akka/pull/22121/files
