### ISSUE TITLE
LengthFieldFramingStage decrement length by offset bytes

### ISSUE THREAD

**Issue by prettynatty** [akka/akka#22129]
In my case ByteString frame looks like:
```
<5 bytes header><4 bytes body length><body>
```
If I use `LengthFieldFramingStage` with offset it reads body length, but in resulting frame body is expectedly truncated by 5 bytes from its end.
My idea is to add an option `countOffsetBytes` (default true) to `LengthFieldFramingStage` indicating that length is length of bytes after the `length` bytes only. Am I thinking in right direction? If yes, I'll contribute.

**Comment by prettynatty** [comment]
Ah, after some sleep I've figured out that the problem is a bit different.
It truncates 4 bytes from the end of body which means that in my case I need `LengthFieldFramingStage` to include `length` field count to the actual frame size.

**Comment by prettynatty** [comment]
So, to cover all cases, I'd add an option `lengthTransformer: Int => Int`.

**Comment by oseval** [comment]
I think `lengthTransformer: Option[(Array[Byte] /* offset bytes */, Int) => Int]` will be better
