### ISSUE TITLE
FAILED: akka.typed.PerformanceSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22125]
[info] akka.typed.PerformanceSpec *** ABORTED *** (17 seconds, 305 milliseconds)
[info]   java.lang.IllegalStateException: cannot enqueue after timer shutdown
[info]   at akka.actor.LightArrayRevolverScheduler.scheduleOnce(LightArrayRevolverScheduler.scala:137)
[info]   at

**Comment by patriknw** [comment]
Probably same reason as for https://github.com/akka/akka/issues/22127

**Comment by 2m** [comment]
#22127 has already been fixed and had the same error message. Therefore closing this as well.

**Comment by raboof** [comment]
Hmm, saw it again at https://jenkins.akka.io:8498/job/akka-release-2.4/330/consoleFull: 
```
[info] akka.typed.PerformanceSpec *** ABORTED *** (17 seconds, 46 milliseconds)
[info]   java.lang.IllegalStateException: cannot enqueue after timer shutdown
[info]   at akka.actor.LightArrayRevolverScheduler.scheduleOnce(LightArrayRevolverScheduler.scala:137)
```

**Comment by johanandren** [comment]
That was in the 2.4 branch though, so we probably didn't backport the fix.
