### ISSUE TITLE
Combining multiple `ReadEventAdapter` throws `IllegalStateException`

### ISSUE THREAD

**Issue by by-dam** [akka/akka#22136]
When there is a event-adapter-binding declared with multiple read-event-adapters like so

```
akka.persistence.journal {
  plugin = "akka.persistence.journal.inmem"
  inmem {
    event-adapters {
      reader  = akka.persistence.journal.ReaderAdapter
      another-reader = akka.persistence.journal.AnotherReaderAdapter
    }
    event-adapter-bindings = {
      "akka.persistence.journal.ReadMeEvent" = [reader, another-reader]
    }
  }
```
it throws `IllegalStateException("CombinedReadEventAdapter must not be used when writing (creating manifests) events!")` whereas it works fine when the binding uses a single `ReadEventAdapter`.
 
The reason is that multiple event-adapters are combined into a `CombinedReadEventAdapter` which throws an `IllegalStateException` from its `toJournal` method.

Unlike the `ReadEventAdatper`, the `CombinedReadEventAdapter` is not wrapped into a `NoopWriteEventAdapter` (which avoids `toJournal` calls).

**Comment by patriknw** [comment]
@by-dam Thanks for reporting. Seems you know what should be changed, would you like to open a pull request fixing the issue?

**Comment by by-dam** [comment]
Hi @patriknw there is actually one such PR https://github.com/akka/akka/pull/22137

**Comment by patriknw** [comment]
ah, thanks
