### ISSUE TITLE
FAILED: ReplicatedDataSerializer

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22140]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/389/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/388/consoleFull

```
[info] - must be compatible with old LWWMap serialization *** FAILED *** (24 milliseconds)
[info]   Array(31, -117, 8, 0, 0, 0, 0, 0, 0, 0, -29, -14, -25, 82, -31, 82, -30, -110, -29, 18, -30, -30, 45, -50, -49, 77, -43, -53, -56, 47, 46, -47, -53, 47, 74, 23, 120, -82, 34, -54, -56, -64, -64, 32, 11, -60, 12, 2, -46, 66, 68, -87, -110, 98, 76, 20, -78, -32, 2, 18, -58, 28, 51, -82, 93, -97, -69, 36, 76, -120, -128, 22, 41, 46, 46, -74, -78, -60, -100, -46, 84, 67, 1, 17, 0, 63, 122, -2, -105, -117, 0, 0, 0) did not equal Array(31, -117, 8, 0, 0, 0, 0, 0, 0, 0, -29, -14, -25, 82, -31, 82, -30, -110, -29, 18, -30, -30, 45, -50, -49, 77, -43, -53, -56, 47, 46, -47, -53, 47, 74, 23, 120, -82, 34, -54, -56, -64, -64, 32, 11, -60, 12, 2, -46, 66, 68, -87, -110, 98, 76, 20, -78, -25, 2, 18, 86, 28, 51, -82, 93, -97, -69, 36, 76, -120, -128, 22, 41, 65, 46, -34, 53, 111, 25, 88, 75, 24, -40, -54, 18, 115, 74, 83, 13, 5, 24, 1, -75, 43, -3, -43, -110, 0, 0, 0) (ReplicatedDataSerializerSpec.scala:49)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6716)
[info]   at akka.cluster
```

**Comment by patriknw** [comment]
Interesting, I thought that was a completely deterministic unit test.
Can you take a look @jgordijn ?

**Comment by jgordijn** [comment]
Hi, that's strange. I'll take a look at it.

**Comment by jgordijn** [comment]
It only seems to be failing in the `akka-artery-cluster-tests`. Is there something specific about this build? I have run these tests numerous times and they never failed, nor do they seem to be failing in the nightly builds.

The test itself is quite simple. Find the serializer based on the manifest for the object. Deserialize the given data, then serialize again and check if the data is different. If I use the serializer and deserialize both byte arrays in the log it gives me the same LWWMap. I'll try look further.

**Comment by jgordijn** [comment]
seems that in the test the newly serialized "value" is in the binary file as: "value1" while it expects "\254\355\000\005t\000\006value1" 

(found using: `protoc --decode_raw < /tmp/newblob` after persisting the byte array to file)

So it serialized string differently, but I don't know why.

**Comment by jgordijn** [comment]
it uses a different serializer for the string. I overlooked the field `serializerId`

So apparently it uses the JavaSerializer to serialize String, but during the artery test, it uses the `"akka.remote.serialization.StringSerializer" = 20` from akka-remote. This is where the difference comes from.

Now the question arises why this is different in different builds. I guess that in production it would always use the `StringSerializer`, because akka.remote would be in scope, right?

**Comment by patriknw** [comment]
Thanks for investigating, @jgordijn. Then I know the reason. When `akka.remote.artery=on` we enable the [akka.actor.additional-serialization-bindings](https://github.com/akka/akka/blob/master/akka-actor/src/main/resources/reference.conf#L593) which includes a different [String serializer](https://github.com/akka/akka/blob/master/akka-remote/src/main/resources/reference.conf#L73).

I suggest that you add `akka.actor.enable-additional-serialization-bindings=on` in the test (and regenerate the old test data with that also). This will be default in 2.5.0 (with possibility to set to off for compatibility).

By the way, is it a key or a value field that is using the String serializer? Value is fine, but key should not.

**Comment by jgordijn** [comment]
@patriknw will do. 

It is in the value of a LWWMap.

**Comment by patriknw** [comment]
thanks

**Comment by jgordijn** [comment]
and here it is: https://github.com/akka/akka/pull/22144
