### ISSUE TITLE
PersistentActor don't change behavior during recovery

### ISSUE THREAD

**Issue by dos65** [akka/akka#22151]
If there is calls of `context.become` during PersistentActor recovery it has no effect.
After receiving `RecoveryComplete` actor don't switch to `receiveCommand`
behavior.

[Example gist](https://gist.github.com/dos65/2ba9fcd4c26d5dbed13d1f49a93dfd58)

**Comment by patriknw** [comment]
From [docs](http://doc.akka.io/docs/akka/2.4/scala/persistence.html)

> Note
> It's also possible to switch between different command handlers during normal processing and recovery with context.become() and context.unbecome(). To get the actor into the same state after recovery you need to take special care to perform the same state transitions with become and unbecome in the receiveRecover method as you would have done in the command handler. Note that when using become from receiveRecover it will still only use the receiveRecover behavior when replaying the events. When replay is completed it will use the new behavior.
