### ISSUE TITLE
Support rememberingEntities with sharding ddata mode

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22154]
With the durable storage this is possible.

This is a prerequisite for #17963

**Comment by ktoso** [comment]
Would be nice to make this a default mode indeed in 2.5.
I'm not sure deprecating the persistence mode is required, it still is useful (at least until we prove that everything is better using the ddata way) :)

**Comment by patriknw** [comment]
Yes, that's my thinking as well, since Cluster Sharding is so widely used
