### ISSUE TITLE
Update canonical ref links to latest page (http in old docs etc)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22162]
We have canonical links which help search engines, we should make sure they link to the new http location etc

**Comment by hhimanshu** [comment]
@ktoso, what is the action item? I can pick this task

**Comment by richard-imaoka** [comment]
Wasn't this already done in #22132 ?

**Comment by hhimanshu** [comment]
hmm, looks like it. @ktoso , does this ticket talks about anything else?

**Comment by ktoso** [comment]
No. For this to have any actual effect it has to be applied to all old documentation that was already published, from aeons ago. 

Only someone with access to doc.akka.io can do this, so I'll remove the community tag.

**Comment by hhimanshu** [comment]
Thank you @ktoso for the background.

**Comment by patriknw** [comment]
Superseded by tasks in https://github.com/akka/akka.github.com/projects/1
