### ISSUE TITLE
`PersistentFSM` misinterprets `Duration.Inf` to disable timeout for state.

### ISSUE THREAD

**Issue by TimSoethout** [akka/akka#22166]
Given ```when(MyState, someDuration) {...}```
When using `goto(MyState) forMax Duration.Inf` in a `PersistentFSM`, I was expecting that the StateTimeout event was not received.

It turns out that this is converted to a `None` value for the `timeout` for `State` (see https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala#L303).

In `FSM` there seems to be some special logic to deal with this (see https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/FSM.scala#L169). I guess this should be ported to `PersistentFSM` to make this work as the documentation specifies:

```
/**
     * Modify state transition descriptor to include a state timeout for the
     * next state. This timeout overrides any default timeout set for the next
     * state.
     *
     * Use Duration.Inf to deactivate an existing timeout.
     */
```

Related to #17140, but for `PersistentFSM` instead of `FSM`

**Comment by TimSoethout** [comment]
I guess a workaround is to introduce an extra State without timeout, and goto that one instead of "reusing" `MyState` without timeout.

**Comment by patriknw** [comment]
At a first glance it looks like we should be able to do the same for PersistentFSM.

**Comment by johanandren** [comment]
not backported to 2.4 yet
