### ISSUE TITLE
Http request completes successfully emitting truncated response

### ISSUE THREAD

**Issue by kstokoz** [akka/akka#22177]
During our production run of our system under high load we experience truncated http responses emitted successfully what results into subsequent json parsing error.

For this particular request we are using single request and connect to https url like this:

```
     final def responseEntityAsString(entity: ResponseEntity)(implicit executionContext: ExecutionContext, materializer: Materializer): Future[String] =
      entity.dataBytes.runWith(Sink.fold(ByteString.empty)(_ ++ _))
        .map(_.utf8String)

    Http().singleRequest(HttpRequest(uri = uri))
    .flatMap { response =>
      responseEntityAsString(response.entity)
        .map { data =>
          if (!(data.endsWith("}") || data.endsWith("]")))
            println(s"Got data [${data.length}] contentLength:[${response.entity.contentLengthOption}] response: [${response.headers.mkString(",")}, $response]")
        }
```

It took me a while to get to the bottom of the issue, it is reprodusable only when running over https and using http pools (like Http().singleRequest)
Here are key aspects which contribute to observe wrong behavior:

1. Http response should be fully read into memory receiving end of stream from server
2. Processing of response later the pipeline is slow which would trigger idle timeout on tcp selector
  causing it to abort connection
3. Response is not fully streamed via sslengine and TLSActor shutsdown still having remaining data to unwrap
4. Tls actor shutsdown TransportOut channel.

In logs below i`m working with file in S3 with expected length of 696137 bytes, we are not using any gzip or other encoding.

Here is an example of mentioned above key points in tracing output:

        [2017-01-20 15:03:47.670 +0000] INFO  - [akka://test/system/IO-TCP/selectors/$a/0] Read [131072] bytes, total so far [330134].
        ....
        [2017-01-20 15:03:55.143 +0000] INFO  - [akka://test/system/IO-TCP/selectors/$a/0] Read [53] bytes, total so far [703452].
        [2017-01-20 15:03:58.609 +0000] INFO  - [akka://test/system/IO-TCP/selectors/$a/0] Read [-1] bytes, total so far [703452].
        [2017-01-20 15:03:58.610 +0000] INFO  - [akka://test/system/IO-TCP/selectors/$a/0] Read returned end-of-stream, our side not yet closed
        [2017-01-20 15:04:05.569 +0000] DEBUG - Aborting tcp connection because of upstream failure: No elements passed in the last 10 seconds.
        [2017-01-20 15:04:09.805 +0000] INFO  - [akka://test/system/IO-TCP/selectors/$a/0] Got Abort command. RESETing connection.
        ....
        [2017-01-20 15:04:44.002 +0000] DEBUG - flushToUser
        [2017-01-20 15:04:44.002 +0000] DEBUG - bidirectional continue
        [2017-01-20 15:04:44.002 +0000] DEBUG - bidirectional
        [2017-01-20 15:04:44.003 +0000] DEBUG - chopping from old chunk of 14587 into TransportIn (1215)
        [2017-01-20 15:04:44.038 +0000] DEBUG - unwrap: status=BUFFER_UNDERFLOW handshake=NOT_HANDSHAKING remaining=15802 out=0
        ....
        [2017-01-20 15:04:52.509 +0000] DEBUG - unwrap: status=BUFFER_UNDERFLOW handshake=NOT_HANDSHAKING remaining=1556 out=0
        [2017-01-20 15:04:52.510 +0000] DEBUG - flushToUser
        [2017-01-20 15:04:52.512 +0000] DEBUG - bidirectional continue
        [2017-01-20 15:04:52.513 +0000] DEBUG - shutting down because TransportOut is cancelled
        [2017-01-20 15:04:57.940 +0000] DEBUG - STOP Outbound Closed: false Inbound closed: false total processed: 678494
        [2017-01-20 15:04:57.940 +0000] DEBUG - postStop
        ...
        [2017-01-20 15:05:15.116 +0000] INFO  - [150]: onUpstreamFinish - expectedLength [696137] - actual [678494] - MISMATCH
        [2017-01-20 15:05:15.131 +0000] INFO  - Got 150 data [678494] contentLength:[Some(696137)]

To achieve relaible reproducability i tried to increase direct buffer size to get response faster into memory and added into snitch stage sleep after certain size to trigger idle exception on tcp selector:

    object Test extends App {

      val actorSystemConfig = ConfigFactory.parseString(
        s"""
          akka {
            loglevel = "DEBUG"
            loggers = ["akka.event.slf4j.Slf4jLogger"]
            logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
            logger-startup-timeout = 1m
            io.tcp.trace-logging = on
            io.tcp.direct-buffer-size = 1024 KiB

            actor {
              default-dispatcher {
                executor = "fork-join-executor"
                fork-join-executor {
                  parallelism-min = 8
                  parallelism-factor = 2.0
                  parallelism-max = 32
                }
              }
            }

            http {
              server.max-connections = 10000
              server.parsing.max-content-length = infinite
              client.parsing.max-content-length = infinite
              server.parsing.max-uri-length = 32k

              server.remote-address-header = on

              host-connection-pool {
               max-connections = 256
               max-retries = 5
               client.idle-timeout = 10 s
               max-open-requests = 512
             }
           }
        }
        """
      )

      implicit val actorSystem = ActorSystem("test", actorSystemConfig)
      implicit val ec = actorSystem.dispatcher
      implicit val materializer = ActorMaterializer()

      def getUri: Uri = ???

      Await.result(
        Source.fromIterator(() => (150 to 150).iterator)
          .mapAsyncUnordered(1) { index =>
            println(index)
            Http().singleRequest(HttpRequest(uri = getUri))
              .flatMap { response =>
                println(s"response for $index")
                HttpUtils.responseEntityAsString(response.entity.dataBytes.via(new SnitchingStage[ByteString](s"[$index]", response.entity.contentLengthOption getOrElse  0L, actorSystem.log)))
                  .map { data =>
                    actorSystem.log.info(s"Got $index data [${data.length}] contentLength:[${response.entity.contentLengthOption}]")
                  }
          }.recover {
              case e: Throwable => println(s"error ${e.getMessage}")
            }
      }.runWith(Sink.ignore), 1.hour)

    }

    case class SnitchingStage[A <: ByteString](name: String, expectedLength: Long, log: LoggingAdapter) extends GraphStage[FlowShape[A, A]] {
      val in = Inlet[A]("in")
      val out = Outlet[A]("out")
      override val shape: FlowShape[A, A] = FlowShape(in, out)

      override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) {
        var counter = 0L

        setHandler(in, new InHandler {
          override def onPush(): Unit = {
            val bytes = grab(in)
            counter += bytes.length
            log.info(s"$name: onPush current [${bytes.length}] total so far [$counter]")
            push(out, bytes)
          }

          override def onUpstreamFinish(): Unit = {
            log.info(s"$name: onUpstreamFinish - expectedLength [${expectedLength}] - actual [${counter}] - ${if (expectedLength != counter) "MISMATCH" else ""}")
            super.onUpstreamFinish()
          }

          override def onUpstreamFailure(ex: Throwable): Unit = {
            log.info(s"$name: onUpstreamFailure: ${ex.getMessage}")
            super.onUpstreamFailure(ex)
          }
        })
        setHandler(out, new OutHandler {
          override def onPull(): Unit = {
            log.info(s"$name: onPull")
            if (counter < 390000) {
              pull(in)
            } else {
              Thread.sleep(4000)
              pull(in)
            }
          }

          override def onDownstreamFinish(): Unit = {
            log.info(s"$name: onDownstreamFinish")
            super.onDownstreamFinish()
          }
        })
      }
    }

As i said above i think this is a combination of several bugs.
In case when response entity stream completes producing truncated content last element received from parser in ResponseParsingMerge.onUpstreamFinish (https://github.com/akka/akka-http/blob/5932237a86a432d623fafb1e84eeeff56d7485fe/akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala#L326) is an *stream truncation error*, unfortunatelly this error cannot be pushed to `out` port as it is not available (it is not closed) and stream truncation error is just added to followUps of EmittingSingle (https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L739) and goes into dev/null when stage completes.

Attached you will find logs with ssl tracing on and with full akka stream graph tracing

[ssl-trace.txt](https://github.com/akka/akka/files/721078/ssl-trace.txt)
[stream-tracing.txt](https://github.com/akka/akka/files/721079/stream-tracing.txt)

.

Other Info:
I`m running on akka 2.4.14 + akka-http 2.4.11, issue also is reproducable with akka 2.4.16 + akka-http 10.0.1

I`ve created issue in akka project as key issue is IMHO related to TLSActor which is in this repo, maybe some fixes would need to go to http repo as well.

**Comment by johanandren** [comment]
Thanks for the detailed report @kstokoz 
Akka HTTP has its own issue tracker, I have copied the ticket over there and will therefore close this one.

**Comment by kstokoz** [comment]
Hi,

As i said in original issue, i think main issue comes from tlsactor which is in akka project, thats why i created issue here. In the end i don't mind where issue is if it would be addressed. ;)

**Comment by johanandren** [comment]
Ah, my bad not reading carefully enough, my apologies.

**Comment by jrudolph** [comment]
@kstokoz, thanks for the report and the great analysis so far.

Can you explain why you think the TlsActor is the main problem here?

**Comment by kstokoz** [comment]
@jrudolph It is only my feeling and maybe i`m wrong, but i would say that TLSActor should not shut down TransportOut while there is still data remaining in transportInBuffer which can be unwrapped and pushed to userOutBuffer.

In this particular case whole response was consumed and chopped into TransportIn, somehow (maybe aborted connection cause it) TLSActor shuts down not finishing processing of data.

**Comment by kstokoz** [comment]
I understand that remaining data in transportInBuffer can be partial data which cannot be unwrapped in this case it should generate response truncation error. as i mentioned error is properly generated but not properly pushed (consumed). This is another issue, which probably related to akka-http.

**Comment by jrudolph** [comment]
I see, thanks.

I'd say it is somewhat unexpected that there is data in input buffers when the idle timeout triggers because the application should have had 10 seconds time to read that data. But as you say under high load it may happen.

So, without having looked into it any deeper, we need to:
 * Decide what an idle-timeout should mean for higher-level stages. So far, I considered it basically the same as a connection error (e.g. like "connection reset by peer"). Which would mean that it is expected that some buffers are dropped.
 * In TLSActor, treat the idle-timeout like a connection error, which would mean that it is fine to drop buffers. We should send an error out to the user stream when that happens (which doesn't seem to be the case for some reason).
 * In HTTP, make sure that errors are actually delivered and not stuck in buffers.

Would you agree?

**Comment by kstokoz** [comment]
Yes, this looks reasonable.

Just to mention: TLSActor is not shuts down immediately on tcp connection abort, from observations, it still able to process buffered data and emit chunks to out for sometime. 

After a while `outputBunch.isCancelled(TransportOut)` set to true and actor goes into completePhase, it is unclear to me why `TransportOut` is cancelled though.

In any case your suggestion would fix issue for us, if truncation error would be properly delivered which would result in failure on our side, which we can recover by resuming download.

**Comment by kstokoz** [comment]
I think this actually was fixed with properly handling entity truncation errors in https://github.com/akka/akka-http/issues/1899

**Comment by ktoso** [comment]
True, very likely so – if you could sanity check once 10.1.1 is out (we're having issues with bintray since a few days so the release keep slipping...) that'd be cool :) I'll close for now
