### ISSUE TITLE
less verbose debug logging in ddata

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22170]
The logging in the `Replicator` is using toString of the messages, which can become a performance problem in production. Reduce to print class names (or similar) instead.

**Comment by ortigali** [comment]
May I take this one?

**Comment by patriknw** [comment]
@ortigali  Yes, that would be great, but it must be done after https://github.com/akka/akka/pull/22331 to avoid merge conflicts.

**Comment by patriknw** [comment]
@ortigali The other PR has been merged now
