### ISSUE TITLE
Coexistence of untyped and typed actors (akka-typed)

### ISSUE THREAD

**Issue by dbolotin** [akka/akka#22174]
I am relatively new to akka. After several days experimenting with pure akka-typed actors I finally decided that I can express whole internal logic of my project in terms of typed actors, and such model, surprisingly, fits very well. (+1 for current akka-typed architecture)

The real stumbling block is absence of clear way to interact with untyped actors. As @rkuhn writes here https://github.com/akka/akka-meta/issues/26#issuecomment-255528579 :

> ... Currently the following are possible:
> 
> - messaging from typed to untyped
> - messaging from untyped to typed
> - creating untyped from a typed parent (but NOT the opposite!)

The question is "how"?

I can't find the answer in docs, also no issues that I manage to find here can't provide any clue on this matter.

I want to interact with akka-http, and [rediscala](https://github.com/etaty/rediscala) library.

Am I right that that there is currently no way to achieve such interactions the right way? Anyway, I would be happy with some reasonable workaround to start writing my `Behaviour`s and run them on `Adapter` system with some bridging actors on the boundaries of my typed system that will interact with untyped world, and then, someday, migrate this code onto fully typed environment, when all required integrations will be available.

I am writing this after I finally came up with a solution, but it looks too ugly for me.

Namely, I need to have an access to untyped system inside typed actors running on `akka.typed.adapter.ActorSystemAdapter`. Something like:

```
case Sig(ctx, PreStart) =>
  val untypedSystem = ctx.system.asInstanceOf[ActorSystemAdapter[Nothing]].untyped
```

But this will not compile as `ActorSystemAdapter` is private, and, yes, this solution as really bad.

For example, having untyped system in scope, I will be able to instantiate `rediscala` [client](https://github.com/etaty/rediscala/blob/master/src/main/scala/redis/Redis.scala#L78) inside my bridge actor. Or even create untyped `ActorMaterializer` to compose and start HTTP server using `akka-http`.

My current solution is to create untyped system, wrap it using `akka.typed.ActorSystem#wrap`, and pass the reference to original untyped system to typed behaviour:

```
import akka.{actor => u}
import akka.{typed => t}
...
def myBehaviour(implicit untypedSystem: u.ActorSystem) = ... Behaviour that e.g. instantiate rediscala client using untyped system ...
...
val untypedSystem = u.ActorSystem("my-system")
val typedSystem = t.ActorSystem.wrap(untypedSystem)
typedSystem.systemActorOf(myBehaviour(untypedSystem), "my-actor")
```

Practical problem in this case is that I can't pass typed `guardianBehavior` to original system.

Questions:
- How bad is this solution? May it introduce some runtime problems?
- Is there a better way to do this?

Thanks!

**Comment by patriknw** [comment]
cc @rkuhn

**Comment by rkuhn** [comment]
Yes, sorry for the delay, you’ll see some updates around Akka Typed next week.

**Comment by dbolotin** [comment]
Thanks! Really looking forward to see it!

**Comment by rkuhn** [comment]
I have just updated akka/akka-meta#26 with a proposal on how to move forward in general. The gist is that what you want to do should be the appropriate solution for migrating to the typed world.

You raise a good point with the problems connected to needing an untyped ActorSystem—this will in general not be possible, there are several aspects that the typed ActorSystem cannot support. The use-cases that you cite are not in principle problematic, though; we should be able to provide an ActorMaterializer for Akka Typed without too much effort (although probably not trivial) and we should also be able to provide a implementation of `akka.typed.ActorSystem.systemActorOf` that allows the creation of untyped actors (for your redis example).

**Comment by dbolotin** [comment]
@rkuhn Thanks for your answer!

The part about ActorMaterializer and akka-streams / akk-http now looks pretty clear to me. Though, things like described [here](http://doc.akka.io/docs/akka/2.4/scala/stream/stream-integrations.html#Integrating_with_Actors) will require their typed versions.

What would you suggest for now? Is it a good idea to go with some solution I came up with (passing reference to `untypedSystem` into bridge `Behaviour`), or wait until some standard solution will be available?

**Comment by rkuhn** [comment]
Sorry for the delay: I think your current approach will be needed for a bit longer, the standard solution might take a few months to finalise.

**Comment by mirmasej** [comment]
My case is similar to the one described by dbolotin. I use akka-http as an entry point for simple HTTP service and akka typed for the rest of the project. I wanted to have one AkkaSystem to rule it all, so I `wrap`ped system created by akka-http, but after calling

    typedSystem.systemActorOf(behavior, name)

I got runtime exception: 
> adapted untyped ActorRefs permissible. 

The issue is - I'm only interested in creating typed actors. 
I tried also `ActorSystemOps.spawn` but here problem is that my typed system after `wrap` is of type `ActorSystem[Nothing]` so it doesn't accept `Behavior[MyType]` as a parameter in `spawn`. Am I missing something?

**Comment by rkuhn** [comment]
@michaelom What you see is a bug (that I cannot pinpoint right now, unfortunately), would you please open a dedicated ticket for it? Thanks!

**Comment by mirmasej** [comment]
@rkuhn I've created [a bug report](https://github.com/akka/akka/issues/22640) for the first issue.

The good news is the second case works, that is:
```scala
case class AMessage(replyTo: ActorRef[String])
val behavior = Stateless[AMessage] { (_, msg) ⇒ msg.replyTo ! "OK" }
val untypedSystem = UntypedSystem("untyped")
import akka.typed.adapter._
val typedActorRef = untypedSystem.spawn(behavior, "typedActor")
```
produces valid typed actor. I guess I was trying to combine both approaches at once :confused: .

**Comment by patriknw** [comment]
I define the scope of this ticket to be the adapter approach. I have completed it in PR https://github.com/akka/akka/pull/22681

Later we can look into the other approach of running untyped actors in the new typed actor system, but that is probably much more complicated. That is covered by ticket https://github.com/akka/akka/issues/22271
