### ISSUE TITLE
delta-CRDT for ORSet

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22188]
After #21875

**Comment by gosubpl** [comment]
Looking into this

**Comment by patriknw** [comment]
thanks

**Comment by gosubpl** [comment]
`multi-jvm:testOnly akka.cluster.ddata.ReplicatorChaosSpec` passes OK (as well as all other tests) but `multi-jvm:testOnly akka.cluster.ddata.JepsenInspiredInsertSpec` fails consistently for random reasons.
Next step -> take a closer look what happens with the delivery of the deltas inside during partition.

**Comment by gosubpl** [comment]
Deltas work, but cannot be merged out-of-order. I expect this is why `JepsenInspiredInsertSpec` fails. This probably can be improved upon just by modifying the `ORSet` itself. Working on this.

**Comment by gosubpl** [comment]
Unfortunately, it seems that despite I managed to make deltas mergeable out-of-order, such merges may result in `ORSet` with holes that work as deletes when merged with another `ORSet`. Hence `WriteLocal`/`ReadLocal` works (usually) fine but `WriteMajority`/`ReadMajority` fails. Adding causal order in merging deltas is possible without changing Replicator itself but needs modifications to `protobuf` wire protocol for `ORSet`. The same is needed to avoid sending full state with delete deltas. I am working on this now.

**Comment by patriknw** [comment]
Thanks for working on this and keeping us updated. I have very little time for reviewing and advicing now and next week.

I have not looked at what would be needed for ORSet deltas, but I find it strange that deltas would have these properties, since a delta is a ORSet by itself. Full state ORSet doesn't have these problems (unless there is a bug). I'm probably missing the details (and will not be able to look at it now anyway).

**Comment by patriknw** [comment]
I have started on the causal delivery protocol and will continue with that today.
