### ISSUE TITLE
Convert remaining UntypedActor in docs

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22182]
Converted most UntypedActor to AbstractActor in https://github.com/akka/akka/pull/22003 but left some due to lack of time. Follow up and convert the remaining (~45).

**Comment by ktoso** [comment]
Sounds like a great ticket for a community effort! :-)

**Comment by ortigali** [comment]
I want to take it

**Comment by patriknw** [comment]
Excellent, thanks @ortigali
