### ISSUE TITLE
about UntypedPersistentActor and subscriber of Cluster 

### ISSUE THREAD

**Issue by beliefer** [akka/akka#22196]
My Actor subscribing the MemberUp event when I use UntypedActor in a Cluster. No matter how much instance of this Actor will work corretly in different member node.
But when I change to UntypedPersistentActor, only one instance of this Actor will receive msg of MemberUp, other instance not.
I want use Akka persistence and each instance of this Actor still receive event of MemberUp.
Please help me ,find out the way!

version:2.4.16

**Comment by patriknw** [comment]
There should be no difference. Please use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) for questions.

**Comment by beliefer** [comment]
I will retry it.
