### ISSUE TITLE
Deprecate, remove or promote things in akka-contrib

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22198]
We must take a closer look. Opinions are welcome, e.g. something that you think is particularly useful.

**Comment by patriknw** [comment]
@johanandren  This is what akka-contrib contains:

* CircuitBreakerProxy
* JavaLogging, JavaLogger, JavaLoggingAdapter
* PeekMailbox ("Mailbox with Explicit Acknowledgement")
* Aggregator
* ReceivePipeline
* ReliableProxy
* TimerBasedThrottler

Some of this looks pretty good. I'd fine with just removing ReliableProxy and PeekMailbox, but the other things should probably stay (or be deprecated). WDYT?

**Comment by johanandren** [comment]
+1 on `PeekMailbox`, not sure about `ReliableProxy` isn't that useful for cases when you want less risk of loosing messages but don't want the ops overhead of introducing persistence?

I'd vote for deprecating `Aggregator` and `ReceivePipeline` doesn't look very useful to me and would probably be better as samples to start from than part of the library.

Is there maybe some overlap with the contrib circuitbreaker stuff now that we have the imperative circuitbreaker API in akka.pattern?

**Comment by patriknw** [comment]
`ReliableProxy` was originally a quick example of how to write a contrib, I think. Don't know of anyone using it. It relies on remote deployment and doesn't have real serialization. We have been fixing its tests over and over again. In summary, not my favorite.

**Comment by johanandren** [comment]
Alright, throw it out then! :)

**Comment by patriknw** [comment]
Looking at `CircuitBreakerProxy`. I can't see when it adds value compared to using the ordinary `CircuitBreaker` together with `ask`. Target actor must still reply to sender, since `ask` is used under the hood. I might be missing something?

**Comment by patriknw** [comment]
`TimerBasedThrottler` can replaced by something like
```scala
  val throttle: RunnableGraph[ActorRef] =
    Source.actorRef(bufferSize = 1000, OverflowStrategy.dropNew)
      .throttle(100, 1.second, 10, ThrottleMode.Shaping)
      .to(Sink.actorRef(target, NotUsed))
```
