### ISSUE TITLE
Deprecate ExtensionKey

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22208]
I don't like `ExtensionKey` since it doesn't work with Java and the added convenience for the few cases when it can be used is not worth it.

wdyt?

**Comment by johanandren** [comment]
I agree 👍

**Comment by ktoso** [comment]
Yeah good. Though it'll need some replacement I guess?

**Comment by patriknw** [comment]
Replacement is the ordinary extension, as documented

**Comment by ktoso** [comment]
Ok cool :)
