### ISSUE TITLE
Akka Stream shutdowns ActorSystem

### ISSUE THREAD

**Issue by damianbl** [akka/akka#22222]
I have the Play application (play 2.4) with Akka 2.4.16. The problem I face is that the actor system shutdowns when I add dependency to Akka Streams (2.4.16) in my application.

This is the error message:

akka.actor.ActorSystemImpl - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-3] shutting down ActorSystem [application]
I do not have any other changes except dependency defined in my build.sbt file.

Do I need anything else to use Akka Streams?

Thank you for any help.

**Comment by ktoso** [comment]
What version of Akka is Play 2.4 using?

This sounds more like a Play question, could you ask over there?
