### ISSUE TITLE
Split Brain Resolver docs should redirect to latest page

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22230]
We should redirect from http://doc.akka.io/docs/akka/rp-current/scala/split-brain-resolver.html
http://doc.akka.io/docs/akka/rp-current/scala/split-brain-resolver.html 
to 
http://doc.akka.io/docs/akka/akka-commercial-addons-1.0/scala/split-brain-resolver.html

since people get confused what the latest one is.

Adding ticket here, hope we don't mind.

**Comment by patriknw** [comment]
Funny, but the latest link is actually http://developer.lightbend.com/docs/akka-commercial-addons/current/

**Comment by ktoso** [comment]
So confusing :(
We need to fix all these links in the next sprint, same with akka http etc, the moving around of stuff has really hurt googlability

**Comment by ktoso** [comment]
Found some more people who had the same struggle, definitely need to fix this soon...

**Comment by patriknw** [comment]
I guess we can't really create redirect from the old HTML pages?

**Comment by patriknw** [comment]
@ktoso Shall we consider this done, or is it such a big problem with the old docs that we have to add some redirect javascript in them?

**Comment by ktoso** [comment]
I think it's worth doing the javascript - esp since we do in open source, and if we don't here then customers using commercial things actually get a worse experience.

Other option is to simply delete the old pages, people get to them via googling or our pages anyway so they'd find the right URLs.

**Comment by patriknw** [comment]
sounds good to delete them, let's rename the directories for now (in case I'm missing something)
I'll fix that.

**Comment by patriknw** [comment]
I have renamed old akka-commercial-addons. Leaving rp docs as is, because that doesn't have a replacement

**Comment by ktoso** [comment]
Great thanks!
