### ISSUE TITLE
Expand snapshot documentation

### ISSUE THREAD

**Issue by rrodseth** [akka/akka#22233]
The examples of snapshotting in the documentation define a message "snap" and send it to the actor. More likely, an actor will have internal logic like

```      
    persist(eventHandledSuccessfully) { e =>
        updateState(e)
        if (eventCount % snapShotInterval == 0) {
          saveSnapShot(...)
        }
      }
```
I initially mistakenly assumed that the actor would have to do `self ! "snap"`, but saveSnapShot is already async, so the above is better. Konrad asked me to submit this ticket. I'd suggest highlighting the different ways snapShotting might be triggered, or choosing an example like the above.

**Comment by rrodseth** [comment]
Also, Patrik points out:

There is already a counter (the sequence number) that you can use.

`if (lastSequenceNr % snapShotInterval == 0 && lastSequenceNr != 0)`

**Comment by patriknw** [comment]
I agree. It would be great if you could improve it in a pull request.

**Comment by richard-imaoka** [comment]
If @rrodseth is busy and cannot update the doc, can I do that on behalf? 
Otherwise, if @rrodseth can actually do it, of course please do and I would like to see it ! 😃

**Comment by rrodseth** [comment]
Please go ahead. One of these days I should learn the process, but I tend to be behind schedule on the day job :)
