### ISSUE TITLE
Tcp.outgoingConnection fails when to use a source of BroadcatHub

### ISSUE THREAD

**Issue by mbesida** [akka/akka#22245]
Having following apps 
```
object test1 extends App {
  implicit val sys = ActorSystem("test1")
  implicit val mat = ActorMaterializer()
  import sys.dispatcher

  val source = Source(1 to 10)
  val bSource = source.toMat(BroadcastHub.sink)(Keep.right).run()
  bSource.map(x => ByteString(s"$x")).via(Tcp().outgoingConnection("localhost", 22001)).runForeach(println).onComplete {
    case Success(x) => println(x)
    case Failure(e) => println(e)
  }
}
object test2 extends App {
  implicit val sys = ActorSystem("test2")
  implicit val mat = ActorMaterializer()

  Tcp().bindAndHandle(Flow[ByteString], "localhost", 22001)
}
```

When to run test2 first and then test1 app I continiously get next output
```
Done
[INFO] [02/01/2017 13:51:18.399] [test1-akka.actor.default-dispatcher-3] [akka://test1/system/IO-TCP/selectors/$a/0] Message [akka.io.Dns$Resolved] from Actor[akka://test1/system/IO-DNS/inet-address/$b#-1697728275] to Actor[akka://test1/system/IO-TCP/selectors/$a/0#-599351886] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

However if I add throttling to the initial source ```val source = Source(1 to 10).throttle(1, Duration.apply(100, "millis"), 1, ThrottleMode.Shaping)``` I get expected output, smth like next 
```
ByteString(49)
ByteString(50)
ByteString(51)
ByteString(52)
ByteString(53)
ByteString(54)
ByteString(55)
ByteString(56)
ByteString(57)
ByteString(49, 48)
Done
```
```BroadcastHub``` documentaion says that 
>Consumers can only be attached once the Sink has been materialized(i.e. the producer has been started)

In mentioned examples consumer is attached after, ```bSource``` is materialized value of BroadcatsHub stream.

**Comment by patriknw** [comment]
@mbesida You are interested in the materialized value of `outgoingConnection` and in above example you are discarding it and therefore it looks like the stream is completed with `Success` (materialized value of runForeach). Instead you should do something like:

```scala
  bSource.map(x ⇒ ByteString(s"$x")).viaMat(Tcp().outgoingConnection("localhost", 22001))(Keep.right)
    .map(println).toMat(Sink.ignore)(Keep.left).run()
    .onComplete {
      case Success(x) ⇒ println(s"Success: $x")
      case Failure(e) ⇒ println(s"Failure: $e")
    }
```

Then you will see `Failure: akka.stream.StreamTcpException: Connection failed.`

Next time, please use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) for questions.
