### ISSUE TITLE
StreamConverters.fromJavaStream doesn't close the stream after completion

### ISSUE THREAD

**Issue by liff** [akka/akka#22241]
[`StreamConverters.fromJavaStream`](https://github.com/akka/akka/blob/v2.4.16/akka-stream/src/main/scala/akka/stream/scaladsl/StreamConverters.scala#L194) does not have any logic for closing the stream after completion. This makes it unsuitable for working with IO-backed streams such as a [`DirectoryStream`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/DirectoryStream.html).

A simple demonstration (should work on macOS or Linux with lsof installed). It should print:

```
before: 0
after: 0
```

if the directory handle was properly closed after completion.

```scala
import java.nio.file.{Files, Paths}
import scala.concurrent.Await
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.Duration
import scala.sys.process._
import akka.actor.ActorSystem
import akka.stream.scaladsl.StreamConverters
import akka.stream.{ActorMaterializer, Materializer}


object DirectorySource {
  def main(args: Array[String]): Unit = {
    val pid = java.lang.management.ManagementFactory.getRuntimeMXBean.getName.split('@')(0)
    implicit val system: ActorSystem = ActorSystem("DirectorySource")
    implicit val materializer: Materializer = ActorMaterializer()

    print("before: ")
    (s"lsof -p $pid" #| "fgrep -c /usr/local/bin").!

    val src = StreamConverters.fromJavaStream(() => Files.list(Paths.get("/usr/local/bin")))

    val program = for {
      _ <- src.runForeach(_ => ())
      _ <- system.terminate()
    } yield ()

    Await.result(program, Duration.Inf)

    print("after: ")
    (s"lsof -p $pid" #| "fgrep -c /usr/local/bin").!
  }
}
```

**Comment by johanandren** [comment]
`Source.unfoldResource` seems to be a better fit than the adapter in the case of `DirectoryStream`. Do you have more examples of such streams?

**Comment by liff** [comment]
Since the Java `BaseStream` doesn't make a distinction between resource-backend streams and regular(?) streams, it seems like it might be a bit surprising to get a resource leak from using `fromJavaStream` in any case?

Another example would be [`Files.lines`](http://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#lines-java.nio.file.Path-) but I the same issue would apply, for example, to some library that provides streams of database rows.

All that said, though, it occurred to me that in any kind of resource-backed Java stream the  operations are most likely blocking and should be wrapped in a `Future`, right? In that sense, wrapping the stream using `unfoldResourceAsync` would perhaps be the way to go. It should be possible to avoid the allocation of a per-element `Option` by writing a proper adapter.

So I suggest:
 - add a note to `fromJavaStream` documentation warning that it will not call `close` on stream completion and
 - optionally add `StreamConverters.fromJavaStreamAsync` or `.fromJavaStreamResourceAsync` (bit of a mouthful) based on either an adapter or `unfoldResourceAsync`, which takes care of resource management.

What do you think?

**Comment by johanandren** [comment]
Do you know of other examples than `DirectoryStream` doing this or is it a special hack?

**Comment by johanandren** [comment]
What I am getting at is that if it is a special hack for one or two streams then I'm not sure we need to do anything but if it would be common practice to have streams that are also `AutoCloseable` we should probably include support for that out of the box.

**Comment by liff** [comment]
But all Java 8 streams are `AutoCloseable`, since [`BaseStream`](http://docs.oracle.com/javase/8/docs/api/java/util/stream/BaseStream.html) is `AutoCloseable`?

Also, the API documentation for `Files.lines` says:

> The returned stream encapsulates a Reader. If timely disposal of file system resources is required, the try-with-resources construct should be used to ensure that the stream's close method is invoked after the stream operations are completed.

**Comment by johanandren** [comment]
Ah, didn't know, well then I guess it would make sense to always close them, is it a no-op on the streams that aren't dealing with resources?

**Comment by liff** [comment]
Probably not quite exactly a no-op since you can attach [`onClose` handlers](http://docs.oracle.com/javase/8/docs/api/java/util/stream/BaseStream.html#onClose-java.lang.Runnable-) to any `Stream` implementation.

**Comment by johanandren** [comment]
Then I definitely think we should add closing to the stage, if there may be registered hooks that expect to run when the stream is closed/completed/failed (or not all of them?).

**Comment by liff** [comment]
The hooks are only called on `close()`, it seems.
