### ISSUE TITLE
akka.actor.remote.artery.large-message-destinations has to match among all actor systems?

### ISSUE THREAD

**Issue by toaditoad** [akka/akka#22256]
Am I correct that the `akka.actor.remote.artery.large-message-destinations` array has to match among all involved actor systems? Using it the first time and following the [documentation](http://doc.akka.io/docs/akka/2.4/scala/remoting-artery.html#Dedicated_subchannel_for_large_messages), I thought that I only have to specify the destination on the sender's side. I don't know what exactly happens then but the message is not sent and there is no warning. After specifying the destination on the receiving actor system as well, it works fine. If that is correct, a hint in the documentation would be helpful.

**Comment by patriknw** [comment]
It's right that you must configure the same on both sides. Documentation improvement would be great. Would you be able to create a pull request for that @toaditoad ?

**Comment by toaditoad** [comment]
@patriknw, I hope that I followed all guidelines correctly and added the hint at all relevant places. My first real contribution to a public project..

**Comment by patriknw** [comment]
@toaditoad Thanks
