### ISSUE TITLE
Publisher/Source from Callback

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [akka/akka#22250]
is there is a way to attach publisher to this callback, for something like that

```
AsyncCallback asyncCallback = new AsyncCallback(Publisher publisher) {
  public void handleResult(XmlRpcRequest xmlRpcRequest, Object o) {
    publisher.publish(o.getBody())
  }
  public void handleError(XmlRpcRequest xmlRpcRequest, Throwable throwable) {
    publisher.failure(throwable)
  }
}

``

**Comment by ktoso** [comment]
You're going about it in the inverse way. It should be a Source.queue into which you can send elements from the `handle` methods.

You should also read http://blog.akka.io/integrations/2016/08/29/connecting-existing-apis and other posts on the blog.

Please do not use the issue tracker for questions about using Akka, use gitter.im/akka/akka or https://groups.google.com/forum/#!pendingmsg/akka-user instead. The issue tracker is only for issues.
