### ISSUE TITLE
Proper logging for root causes of disassociation in old remoting

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22277]
Right now it seems error are usually not propagated which makes it very hard to understand why a system gets disassociated at a certain point in time.

**Comment by ktoso** [comment]
Assign milestones when closing please :)

**Comment by jrudolph** [comment]
Yes, sorry missed that one. Changed to 2.4.18 as the change was backported.

**Comment by ktoso** [comment]
When we backport we do this:
- original issue can keep 2.5
- the PR of the backport gets assigned to the milestone it was backported to 2.4.18

This way the feature shows up in both lists when people check "what is in 2.5" as well as "what is in 2.4.18". So this PR should be 2.5.0, and the backport issue (already is) 2.4.18.

**Comment by jrudolph** [comment]
Hmm, I understand that this would make sense for 2.5.1, i.e. when 2.5 and 2.4 really had diverged. 

I don't think it makes sense, though, to include any changes into the 2.5.0 release announcement that have already been announced before on one of the 2.4 announcements. Or in other words, why do we replicate changes from 2.4.16 on (or whatever you suggest) in the 2.5.0 release notes but not older ones? From the view of the users that would seem completely arbitrary.

**Comment by ktoso** [comment]
No strong feelings here, let's check with @patriknw

**Comment by patriknw** [comment]
I have done it in the opposite way. The ticket is marked with 2.4.16, and the corresponding PR for master with 2.5.0.

I agree that it makes more sense to start doing this after 2.5.0, but I don't think it hurts.
