### ISSUE TITLE
Retry Pattern

### ISSUE THREAD

**Issue by jangoolie** [akka/akka#22276]
I find I occasionally want to retry a future so I wrote this helper that lives in a common Library I maintain:

```scala
import scala.concurrent.{ ExecutionContext, Future } 
import scala.concurrent.duration.FiniteDuration
import akka.actor.Scheduler
import akka.pattern.after

def retry[T](
  attempt: () => Future[T],
  attempts: Int,
  delay: FiniteDuration,
  scheduler: Scheduler
)(implicit ec: ExecutionContext): Future[T] = if (attempts > 0) { 
  attempt() recoverWith { 
    case _ => after(delay, scheduler){ retry(attempt, attempts - 1, delay, scheduler) } 
  } 
} else after(delay, scheduler){ attempt() } 
```

Is this the sort of thing that could live in akka.pattern?

**Comment by patriknw** [comment]
@jangoolie  looks useful, please create PR

**Comment by jangoolie** [comment]
Created a PR for this https://github.com/akka/akka/pull/23050

**Comment by patriknw** [comment]
There is a start of this in (closed) https://github.com/akka/akka/pull/23050 if someone would like to pick it up.

**Comment by danielkman** [comment]
I'd like to try and finish this issue, based on #23050
