### ISSUE TITLE
Flow.fromSinkAndSource with "attached" cancelation/completion

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22297]
I've seen a couple of questions here and there where people get stuck on `Flow.fromSinkAndSource(sink, source)` breaking the cancelation/completion signaling chain, so that when sink cancels, source will still be running, or when source completes the sink will keep consuming. 

Could we introduce a version of it that will complete the source when the sink cancels, and cancel the sink when the source completes? Something like `Flow.fromSinkAndSource(sink, source, doTheCompletionThing = true)`

**Comment by ktoso** [comment]
Duplicate of https://github.com/akka/akka/issues/21549

**Comment by johanandren** [comment]
Ah, sorry. I had a nagging feeling this had been up before...
