### ISSUE TITLE
Exclude docs package from API docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22296]
Currently we include the `docs.` package in the Java/Scaladoc 

Should be possible to fix using `-skip-packages`, see https://github.com/lagom/lagom/blob/master/project/Doc.scala#L87

**Comment by 2m** [comment]
We use sbt-unidoc for aggregating java/scaladoc. And that plugin has support for filtering out projects: https://github.com/akka/akka/blob/b545fb18ac2a5222b13d680be747e70d2e3acacf/project/Doc.scala#L121-L124 We should add a filter for the docs project there.

**Comment by athieriot** [comment]
That can probably be close now?

**Comment by patriknw** [comment]
thanks

**Comment by athieriot** [comment]
No thank you !
