### ISSUE TITLE
Feature request: Circuit breaker should allow user specify what is considered failure

### ISSUE THREAD

**Issue by buaya91** [akka/akka#22295]
Current async circuit breaker assume `Failed future` is failure, which is a reasonable, but not flexible enough.

It would be nice if we allow user to express what should be consider a failure, by passing in a function with signature

```
Try[_] => Boolean
```

I am going to submit a PR, however if this use case does not make sense, please comment 

Cheers ~

**Comment by buaya91** [comment]
One potential problem is where to pass the predicate function , passing from constructor would be too restrictive, passing from the `withCircuitBreaker` and it's variant seems to make more sense, but this might change the api (in a backward compatible way thought, we could either overload of use default params) , could maintainer comment if this should be avoided?

**Comment by patriknw** [comment]
@buaya91 Isn't it enough to do `.recover` or `.recoverWith`?

**Comment by buaya91** [comment]
@patriknw that's what we did as a workaround, but it's clunky as we need to flatmap it back to failed future after returning from `withCircuitBreaker` clause. This leads to some amount of code that convert Failed future to success back and forth

Do you think this is a valid reason?

**Comment by patriknw** [comment]
Thanks @buaya91
