### ISSUE TITLE
Reword Experimental to "API May Change"

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22305]
In documentation and source code comments

**Comment by ortigali** [comment]
would like some clarification

**Comment by ktoso** [comment]
What's confusing?

**Comment by ortigali** [comment]
only replace "Experimental" to "API May Change"

**Comment by ktoso** [comment]
Hm... if you're thinking about contributing that one I guess this one may be better left to us so the wording is really what we intend to say and guarantee down the line.

Not sure I understood correctly though?

**Comment by patriknw** [comment]
We should also make sure that no artifact names contain `-experimental`. I'm thinking of `akka-typed`, so that we can promote it in a 2.5.x patch release if/when we feel it's ready. (cc @rkuhn)
