### ISSUE TITLE
Documented, not existing FSM matcher? FSM convenience matcher - Ev

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22302]
> The FSM JavaDoc mentions a convenience matcher called Ev for matching events without the data, but I can't find the actual matcher (or any reference to it in the main docs). Does it actually exist, or is it a "bug" in the JavaDoc?

via @talp-traiana on akka-user

I was not able to find the mentioned docs, what do you mean specifically Tal?

**Comment by talpr** [comment]
I'm referring to this:
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/FSM.scala#L241

I might have a few spare moments today, I'll try to open a PR.
