### ISSUE TITLE
Update samples moved into docs to new Java API

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22308]
When #22288 gets merged we need to update the included in that PR to be `AbstractActor` rather than `UntypedActor`

**Comment by patriknw** [comment]
@ortigali would you be interested in fixing this ticket also, since you did such a great job with https://github.com/akka/akka/pull/22258

**Comment by ortigali** [comment]
I am glad to take it

**Comment by patriknw** [comment]
thanks
