### ISSUE TITLE
Refine Take and TakeWhile to be simpler

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22310]
To track the PR https://github.com/akka/akka/pull/21871

change InHandler to avoid unnecessary condition check
remove unnecessary local variable
fix typo

**Comment by Hawstein** [comment]
Ah, thanks for creating the ticket. 😄

**Comment by ktoso** [comment]
It's good to have issues for them so we can track in case a bug was introduced etc
Thanks for the cleanup!
