### ISSUE TITLE
java.lang.VerifyError with sbt-assembly plugin

### ISSUE THREAD

**Issue by pomadchin** [akka/akka#22319]
I receive a `VerifyError` when I use [sbt-assembly](https://github.com/sbt/sbt-assembly) shading feature on any library and Akka 2.4.x+.
With Akka 2.3.x everything works. 

I prepared a small project to reproduce error: https://github.com/pomadchin/shading-issue
It has only two deps: `akka-core` and `com.github.scopt` (just random library to shade, without transitive deps).

Main.scala implements [this](http://doc.akka.io/docs/akka/current/scala/actors.html#Recommended_Practices) example from Akka docs.

Is it `Akka` or `sbt-assembly` issue / feature? What can you recommend? Current workaround to use `-noverify flag`.

**Comment by ktoso** [comment]
Likley duplicate of https://github.com/akka/akka/issues/21596 please read that and confirm?
It's nothing to do with Akka but the shading impl in sbt-assembly, we can't help with that.

**Comment by pomadchin** [comment]
@ktoso I whish to say yes, but i figured out that this issue appeared on `Akka 2.4-M1`, I'll attach `build.sbt`: 

```scala
name := "shading-issue"
version := "0.1.0-SNAPSHOT"
scalaVersion := "2.11.8"
crossScalaVersions := Seq("2.12.0", "2.11.8")
organization := "com.azavea"
scalacOptions ++= Seq(
  "-deprecation",
  "-unchecked",
  "-Yinline-warnings",
  "-language:implicitConversions",
  "-language:reflectiveCalls",
  "-language:higherKinds",
  "-language:postfixOps",
  "-language:existentials",
  "-feature"
)

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.5-M1",
  "com.github.scopt" %% "scopt" % "3.5.0" // random library to shade (has no transitive deps)
)

// Since Akka 2.4-M1: (2.3.16 would work with shading)
// 1. not to shade = everything works OR
// 2. to shade and to use -noverify jar flag = everything works
// otherwise stackmap exception

assemblyShadeRules in assembly := {
  val shadePackage = "com.azavea.shaded.demo"
  Seq(
    ShadeRule.rename("com.github.scopt.**" -> s"$shadePackage.com.github.scopt.@1").inAll
  )
}

test in assembly := {}
```

**Comment by ktoso** [comment]
As I just said, it's not about spark, please read that ticket, the last comment there is:

> Seems to be a bug in sbt-assembly. See https://github.com/sbt/sbt-assembly/issues/205 . It's easy to reproduce by using sbt-assembly on a project that uses sbt-assembly and defines an arbitrary shading rule.

It's an sbt-assembly issue and we can't do anything about it in Akka itself.
Please chime-in in the https://github.com/sbt/sbt-assembly/issues/205 thread I guess

**Comment by pomadchin** [comment]
@ktoso thx for this pointer!
