### ISSUE TITLE
Patterns and PatternsCS naming and package

### ISSUE THREAD

**Issue by guidomedina** [akka/akka#22316]
I found out by accident that `PatternsCS` is the Java counterpart of `Patterns`, hard to guess with the CS at the end and no package like `japi` or `javadsl`, my suggestion is to deprecate the current `Patterns` and create a copy on each corresponding package (for Java and Scala) with the name Patterns.

There were other suggestions like create `Ask`, etc, but I don't think is worth because there are several patterns there:
- ask
- pipe
- gracefulStop

Maybe just split the Patterns?

**Comment by ktoso** [comment]
Moving Patterns does not sound beneficial enough to warrant the breakage.

PatternsCS is ugly yeah - deprecating and introducing better place for java part sounds interesting.
Specific suggestions would be welcome. Splitting out Ask etc seems bad timing, we don't need to introduce more breakage than really needed. `akka.actor.japi.Patterns` would be enough I guess.

**Comment by ktoso** [comment]
Marked as 2.5.0 but as `new` so we discuss it before 2.5.0 lands, not triaged yet.

**Comment by guidomedina** [comment]
Yeap, I agree that even introduccing a `akka.actor.japi.Patterns` will automatically show for IDE completion imports etc, should make it more evident and easy to find which is the real intention of this ticket.

**Comment by patriknw** [comment]
It's a valid point that this is not a very good API design. However, moving things around will be more annoying than the value it adds, since we will not be able to create a consistent API convention for all things after the fact. I'm moving this to Akka 3.0.

**Comment by patriknw** [comment]
Solved by https://github.com/akka/akka/issues/26000
