### ISSUE TITLE
remove stateless behavior

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#22325]
Stateless actors do not need to change their behavior, so requiring them to return `Same` just because they may want to voluntarily terminate seems a little inconvenient. Proposed usage:
~~~java
// Java
Actor.<String>stateless((ctx, msg) ->
  if (msg.equals("stop")) throw Actor.stop();
  else { ... });
~~~

~~~scala
// Scala
Actor.stateless[String]((ctx, msg) =>
  if (msg == "stop") throw Actor.stop
  else { ... })
~~~

**Comment by patriknw** [comment]
I don't like this much and question the need for a different api for `stateless`. `Unhandled` is another example that `stateless` can't handle.

**Comment by rkuhn** [comment]
We can of course leave out `stateless` for now and see who complains—it is just a bit ugly to read `Same` so many times in a match.

**Comment by patriknw** [comment]
Actors are by definition stateful, with some rare exceptions. Let's remove `stateless`. Symmetry is nice and therefore I suggest that we rename stateful to immutable. Then we have two different styles for `immutable` and `mutable., and they are so different that they deserve different APIs.
We will promote the `immutable` style but the `mutable` style still has it's place.

**Comment by hepin1989** [comment]
`stable`

**Comment by hepin1989** [comment]
I　more like `variant` and `constant`

**Comment by rkuhn** [comment]
Do I understand correctly that both kinds (mutable and immutable) then always need to return the next behavior? That would leave most flexibility, I agree. Okay, then, but we should document that MutableBehavior normally returns `this` and not `Actor.same()`, to make semantics perfectly clear.

**Comment by patriknw** [comment]
yes, both return next behavior and can therefore be mixed as needed.

Returning `this` for the mutable is an excellent convention.

**Comment by patriknw** [comment]
Eclipse Scala IDE shows warning:
```
Type safety: The expression of type MutableIntroTest.ChatRoom.ChatRoomBehavior needs unchecked 
 conversion to conform to Behavior<MutableIntroTest.ChatRoom.Command>
```

but that can be turned off: "Unchecked generic type operation".

**Comment by rkuhn** [comment]
Ouch, yes, JDT sometimes is that kind of stupid—does javac also show this warning?

**Comment by patriknw** [comment]
nothing shown when compiling with sbt, I think this is Eclipse trying to be helpful

**Comment by jrudolph** [comment]
This has been marked "Done" in the project but wasn't closed here. Can we close it here now?

**Comment by patriknw** [comment]
done

**Comment by ktoso** [comment]
Should it be on milestone 2.5.1?

**Comment by patriknw** [comment]
no, nothing of the typed will be in the 2.5.1, so we will change from 2.5.x to the right milestone when we release it
