### ISSUE TITLE
Oversize payload exception sending ddata gossip

### ISSUE THREAD

**Issue by abesanderson** [akka/akka#22327]
I'm seeing the following exception quite a bit when running a mid-sized cluster(10 nodes) with distributed data and legacy remoting.  

'akka.remote.OversizedPayloadException: Discarding oversized payload sent to Actor[akka.tcp://smart-comfort@10.34.0.22:2552/system/sharding/replicator#-280172874]: max allowed size 512000 bytes, actual size of encoded class akka.cluster.ddata.Replicator$Internal$Gossip was 565664 bytes.'

I bumped up the max frame size from the default of 128k but it just seemed to delay the problem.  I saw a post on the mailing list that mentions a known issue with pruning when members are removed, but the cluster topology wasn't changing during this time.

**Comment by patriknw** [comment]
How many keys are you updating? What data types are you using? How many elements do you add to these?

**Comment by abesanderson** [comment]
This is just the cluster sharding data.  There are 10 nodes, each node has about 30 shards, each shard has about 40k entities.  There are 8 separate cluster shard regions, but it seems like there is a single replicator for all cluster sharding information.   My understanding of the map CRDT is that it only sends updates, rather than an atomic representation of the whole data structure.  If it's attempting to gossip the whole structure, that would easily exceed the max message size.

**Comment by patriknw** [comment]
Two more questions, and the it should be possible for us to reproduce. What akka version? Are you using "remember entities" for all those entities?

**Comment by abesanderson** [comment]
This is akka 2.5-M1, and there is one cluster shard region with remember entities on, the others should just be sending data about shard home.

**Comment by patriknw** [comment]
@abesanderson I have simulated the problem in a test. 

The way it works is that the identifiers of the active entities are stored in 5 `ORSet` per shard (simple hashing across 5 different). The size of the entity identifiers matters, I used `UUID.randomUUID` (36 character string). Smaller is better.

Increasing the frame-size to 256 KiB should be alright. That is also what we use as default in Artery.

    akka.remote.netty.tcp.maximum-frame-size = 256 KiB

With 10000 entities in one shard I see Gossip size of 204463 bytes. That contains all 5 `ORSet`. The single `Write` message is 49456 bytes and that contains one `ORSet` with around 2000 ids.

The first thing you should do is to set

    akka.cluster.sharding.distributed-data.max-delta-elements = 5

We should set this as the default value for this. You can even use a smaller number.

40k entities per shard might be too much when using "remember entities". You could use more shards (perhaps also more nodes) to have less entities per shard.

Note that the "remember entities" feature has a rather high performance cost, when starting/stopping entities and when failing over / rebalancing. Do you really need to use that feature for that many entities, or is there something more lightweight that you can use?

**Comment by abesanderson** [comment]
Thanks for taking a look at this.  I took another look, as the 40k number did seem high, it turns out that it was in fact 40k per region, so closer to 1.5k entities per shard.  I'll try with the recommended settings and test again.

**Comment by patriknw** [comment]
Good. I think we should be able manage something like 10k entities per shard. What kind of identifiers are you using? Keep us updated with the new test results.

**Comment by patriknw** [comment]
I changed the defaults of `max-delta-elements` and added note in documentation. I'm closing this ticket now, but I'm still interested in the results of your testing. Please reopen or create a new issue if you find something new.
