### ISSUE TITLE
Handle system property "java.net.preferIPv6Addresses"

### ISSUE THREAD

**Issue by jpuerto** [akka/akka#22330]
Hello,

We are working in [akka-social-stream](https://github.com/becompany/akka-social-stream) project to aggregate the social feeds to a common stream. The project works perfectly in my local machine but our server is IPv6 only and the application was not able to resolve the URLs of the social providers properly.

Finally, after some troubles we think that we have located the source of the problem. After enabling the Akka debug log, we realised that the URLs was being resolved as IPv4. A closer look to the code shows that the [Dns](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/Dns.scala#L29) object prefer IPv4 addresses always.

`val addrOption: Option[InetAddress] = ipv4.headOption orElse ipv6.headOption`

Akka should instead read the system property "java.net.preferIPv6Addresses" and [handle it correctly](http://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html). We have created a patch but it has not been tested yet.

We have created a patch in our fork: https://github.com/jpuerto/akka/commit/2167cc720f790087ef1946ad158fb6ccd71cbcc5#diff-d9e29ae782089731101db344dc5fe1c7

Best regards.

**Comment by jpuerto** [comment]
A patch has been created. This time the patch has been tested and it is working fine in our IPv6 only server. I have included also test specs for the change.

**Comment by ktoso** [comment]
Thanks, marked as in progress
