### ISSUE TITLE
Switch off Java serialization for remoting by default

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22333]
This mostly requires that there's a viable, seamless alternative we could people point to and that is supported by akka with helpers etc.

Changing the default would not stop anyone from updating as you will still be able to use Java serialization by turning the flag "on" if required.

(fwiw. I don't think there will ever be a good point in time to do the change. The longer we keep it "on" by default the longer people will start new projects that still use Java serialization.)

**Comment by ktoso** [comment]
For incorporating Kryo support we should collaborate with the best integration out there which is https://github.com/romix/akka-kryo-serialization I think. 

It's both used a lot, and the maintaining people have been in touch with us once in a while,
I think we could use a lot of the work already made there.

**Comment by patriknw** [comment]
I'm positive to changing the default, but we need to provide that seamless alternative. Kryo is probably best, but still some work to incorporate it. Not sure if we "have time" for doing it for 2.5.0. Let's think about it.

**Comment by patriknw** [comment]
Related to #24526
