### ISSUE TITLE
delta-CRDT for ORSet friends

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22350]
The remaining CRDTs that are building on top of `ORSet`.

* `ORMap`
* `LWWMap`
* `PNCounterMap`
* `ORMultiMap`

**Comment by patriknw** [comment]
@gosubpl I created a separate ticket for these

**Comment by gosubpl** [comment]
@patriknw thanks! I am all over it like a rash (what a nice English idiom).

**Comment by gosubpl** [comment]
I made significant progress on this. Most of the work in recent days was concentrated on the case of delta-delta updates, i.e. where the type of value in the `ORMap` is `DeltaReplicatedData` type itself. In that case it would be beneficial to send only pairs of `(key-delta, value-delta)` but this is a bit tricky and requires resolving some anomalous behaviours. Initial implementation requires removal tombstones, which at the moment are not being pruned (but adding pruning capacity would not be too hard). I am targeting getting to draft-PR stage soon.

**Comment by patriknw** [comment]
Perhaps it's easier to implement it for the more specific types, such as `LWWMap` and `PNCounterMap`, `ORMultiMap`?

**Comment by gosubpl** [comment]
@patriknw thanks for the tip, however I think I have nailed it in the `ORMap` itself :)
The commit above (`95751fa`) is a draft of the PR which I expect to submit really soon. Even code coverage values are pretty decent. It needs some more tests to cover even more sneaky edge cases related to delta-delta application for `ORMap` of `ORSet` case and handling of pruning (which is easy).

**Comment by patriknw** [comment]
great, looking forward to reviewing

**Comment by gosubpl** [comment]
@patriknw ready for review

**Comment by patriknw** [comment]
thanks, I'll review tomorrow
