### ISSUE TITLE
GraphInterpreter leak when a submaterialized flow throws during materialization

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22358]
Found while working on completing #21363 

When the stage subFusingMaterializer is used and the materialized stream throws an exception during materialization this will cause the `ActorGraphInterpreter` to leak, as the stage is added to `newShells` but never completes initialization.

Adding to that list happens in `ActorGraphInterpreter.registerShell` which is passed to the materializer as the `subflowFuser` parameter but I have not quite figured out why/how this happens even though there is an exception materializing.

**Comment by ktoso** [comment]
More info from Johan:

> Did you see https://github.com/akka/akka/blob/c3c058b6bba3aa3099c788ec119a8c330fba4224/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FutureFlattenSourceSpec.scala#L153
> My conclusion about why may be wrong, but it surfaced through assertAllStagesStopped causing the stage to fail as the actor stayed alive

**Comment by patriknw** [comment]
it would be a bug in 2.4 (and possibly also in 2.5) if it's a bug, seems like tests are passing with 2.5
