### ISSUE TITLE
Fix akka-osgi, akka-slf4j, and akka-stream Import-Package manifest header version ranges

### ISSUE THREAD

**Issue by michael-smith** [akka/akka#22363]
In akka-osgi v2.5-M1, the Import-Package manifest header has imports for both akka-actor and akka-event which specify a range of `[2.4,2.5)` which essentially excludes the use of this library with any 2.5 version of akka-actor akka-event.

**Comment by michael-smith** [comment]
I just noticed this problem exists in other bundles as well.  
`akka-slf4j` and `akka-stream` v2.5-M1 both import a number of akka packages from other bundles where the range is `[2.4,2.5)` so they will have the same problem.

**Comment by patriknw** [comment]
Thanks for reporting @michael-smith.
What is the purpose those ranges with the family of akka bundles. One must use the exact same patch version of all akka bundles anyway.

**Comment by michael-smith** [comment]
Sorry for the delay.. to answer your question, the purpose of the ranges tells the OSGi framework what version range of library is required for this bundle.  So by excluding anything equal to or above 2.5, the OSGi container is unable to find a matching bundle even when the 2.5-M1 bundles are loaded into the container.
