### ISSUE TITLE
Rename PersistentActor.receiveRecover to receiveEvent

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#22372]
`receiveRecover` implies to be applied during recovery (only), but the method is used for any events. I suggest to rename the method `receiveEvent` and add a deprecated alias with the old name which can later be removed.

**Comment by patriknw** [comment]
What do you mean? It's only called by Akka during the recovery.

**Comment by hseeberger** [comment]
Once an event has been persisted via `persist` it needs to be applied to the state the exact same way as during recovery. Therefore it's an idiomatic implementation pattern to call `receiveRecover` as the first thing in the event handler given to `persist`. 

Here's an example: https://github.com/hseeberger/gabbler/blob/master/gabbler-user/src/main/scala/de/heikoseeberger/gabbler/user/UserRepository.scala#L86

I know that the Akka docs don't use this pattern, but I have seen it often, also by Martin Krasser.

**Comment by patriknw** [comment]
receiveRecover may handle more than just events, such as snapshot and RecoveryCompleted. I'd probably delegate to a applyEvent from both places.

**Comment by hseeberger** [comment]
IMHO RecoveryCompleted is just another event.

**Comment by patriknw** [comment]
It would be rather confusing to explain that `receiveEvent` also has to handle snapshots. There are many nice DSLs that can be built on top of the raw PersistentActor API, e.g. [Lagom PersistentEntity](http://www.lagomframework.com/documentation/1.3.x/scala/PersistentEntity.html#Full-Example).

In your example I would put it into the state.

```scala
final case class State(users: Map[String, User]) {
  def apply(event: UserEvent): State = event match {
    case UserAdded(user)   => copy(users.updated(user.username, user))
    case UserRemoved(user) => copy(users - user.username)
  }
}

override def receiveRecover = {
  case evt: UserEvent => state = state(evt)
}

def remove(user: User): Unit = {
  persist(UserRemoved(user)) { evt => 
    state = state(evt)
  }
}
```

In practice we can't even add a new method, because it's a trait. :(

**Comment by hseeberger** [comment]
Alright then ;-)
