### ISSUE TITLE
[Docs] Java documentation regarding 'ask' referencing Scala API instead of Java API

### ISSUE THREAD

**Issue by talpr** [akka/akka#22373]
The documentation on the Java ['Actors'](http://doc.akka.io/docs/akka/2.4/java/lambda-actors.html#Ask__Send-And-Receive-Future) page uses the Scala version of 'ask' instead of the one in PatternsCS.

**Comment by jlprat** [comment]
AFAIR, the one used in the docs is the one for Java before it existed `CompletionStage` (which came in Java 8). So I guess, you could rephrase it as use the newer variant of Patterns (PatternsCS) instead of the old one for the Java examples.

**Comment by patriknw** [comment]
It would be great to update docs to use the CS versions. PR welcome.

**Comment by talpr** [comment]
Uhmm, sorry, I must no be fully awake yet... I can't seem to find the "lambda" versions of docs anywhere. Didn't there used to be files named `lambda-actors.rst` etc. for it?

**Comment by ktoso** [comment]
On `master` there's no `-lambda` anymore since "lambda is the new default", so the samples in `actors.rst` should use the new things and should be amended.

**Comment by patriknw** [comment]
Solved by https://github.com/akka/akka/issues/26000 and https://github.com/akka/akka/pull/26069
