### ISSUE TITLE
Improve performance and design of the materializer

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22387]
Materialization speed is slow and that becomes a bottleneck for short lived streams.

**Comment by hepin1989** [comment]
I currently is want to make use of akka-stream's Source as a value holder,eg,Reactor's Mono,but I think that may be slow,so have not start yet.

My senario is using akka stream to produce a graphql's query (maybe subscription in the future).

Looking forward to this.

**Comment by patriknw** [comment]
congrats @drewhk
