### ISSUE TITLE
[cluster-sharding] Don't black-hole message if entity ID or shard ID extractor is undefined for message type

### ISSUE THREAD

**Issue by haggy** [akka/akka#22395]
https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L445

In the code above, the message sent to the shard region will simply be dropped with no indication of what the issue is if a shard/entity ID extractor is not defined for the message type. This makes it extremely hard to debug what's going on if your messages don't seem to be getting processed by the region or other places in a larger codebase. 

I can put a PR together that will throw an exception if an extractor is undefined for a given type (can make it configurable too maybe?). I did that in my code that using cluster sharding and it has saved me __many__ times!

**Comment by patriknw** [comment]
Sounds like a good suggestion. Please PR. No need for config. Log at warning level would be good.

**Comment by haggy** [comment]
@patriknw https://github.com/akka/akka/pull/22401
I need to sign the CLA since this is my first contribution but all tests pass and `validatePullRequest` is all clear.

**Comment by haggy** [comment]
CLA signed
