### ISSUE TITLE
Akka streams: Connecting generic flow shapes

### ISSUE THREAD

**Issue by fhalde** [akka/akka#22412]
Hi. I have a requirement that makes use of akka streams API. 

Basically rather than having typed shapes such as `Source[Int]` `Flow[Int, Int, _]` `Sink.foreach[Int]`, I wanted to created their untyped counterparts.

This is because I have to write a function that takes a source flow and sink of generic type (we are guaranteeing type safety at a higher level)

I tried the following but it resulted in a compilation error

```scala

val so = Source[_, NotUsed] = Source[Int](1 to 10)
val fl = Flow[Int].map(_ * 2)
val si = Sink.foreach[Int](println)

and connect using

s.via(f).to(si)

/* type mismatch error */
```

Any workaround to create untyped flow shapes ?

**Comment by johanandren** [comment]
Hi @fhalde 

Please use the gitter channel (https://gitter.im/akka/akka) or the mailing list (https://groups.google.com/forum/#!forum/akka-user) for questions and only use the issue tracker for bugs and features, thanks!
