### ISSUE TITLE
A potentially useful akka-stream stage for time-window processing

### ISSUE THREAD

**Issue by marcin-rzeznicki** [akka/akka#22420]
I couldn't find any existing stage to accomplish simple time-window processing where data is aggregated for predefined amount of time and the computed aggregate is emitted once per this time. While `conflateWithSeed` fits the "aggregation" part of processing very nicely, I couldn't find any element that could steer the back-pressure to pull the aggregate once in a while and push it downstream. `delay` is close, but since it needs at least one element input buffer, one ends up with situation where, conceptually: at t0 data is pulled from `conflate` stage and put into buffer to be emitted at t1, at t1 the next element is pulled (aggregate of ]t0, t1]) to be emitted at t2 and so on, which means unnecessary delay of at least one "window". `groupedWithin` might be used for this case, but it keeps elements in memory till time-window expires, which is unnecessary in my case, as all I care about is aggregated data which can be computed incrementally. Therefore I ended up writing a custom stage called `Pulse` which can be seen as backpressuring `delay` with no buffering.

```scala
final class Pulse[T](val interval: FiniteDuration, val initiallyOpen: Boolean = false) extends SimpleLinearGraphStage[T] {
    override def createLogic(inheritedAttributes: Attributes): GraphStageLogic =
      new TimerGraphStageLogic(shape) with InHandler with OutHandler {

        setHandlers(in, out, this)

        override def preStart(): Unit = if (!initiallyOpen) pulse()
        override def onPush(): Unit   = push(out, grab(in))
        override def onPull(): Unit = if (!pulsing) {
          pull(in)
          pulse()
        }

        override protected def onTimer(timerKey: Any): Unit = {
          if (!isClosed(in) && !hasBeenPulled(in)) pull(in)
        }

        private def pulse() = {
          pulsing = true
          schedulePeriodically("PulseTimer", interval)
        }
        private var pulsing = false
      }
  }
```

It can be used with `conflateWithSeed` like this:

```scala
  def window[A, S](of: FiniteDuration, eager: Boolean = true)(seed: A => S)(aggregate: (S, A) ⇒ S): Flow[A, S, NotUsed] =
    Flow[A].conflateWithSeed(seed)(aggregate).via(new Pulse(of, eager))
```

I thought it might be useful for others, so I could contribute this small stage to `akka-stream`, if you found it worthy. I'm looking forward to hearing your opinions.

**Comment by manonthegithub** [comment]
You may use conflateWithSeed() and then zip it with Source.tick instead, as in following example:
```scala
val res = Source
        .repeat(1)
        .conflateWithSeed[Int](a => a)(_ + _)
        .zipWith(Source.tick(0 seconds, 100 millis, None))(Keep.left)
        .runWith(TestSink.probe[Int])
        .request(5)
        .expectNextN(5)
      res.foreach(println)
```

**Comment by marcin-rzeznicki** [comment]
@manonthegithub nice trick, I didn't think of that, thank you.
Do you think that the custom stage I'm proposing is needless then? For one think I think it can be used in other scenarios as well - also, it is somehow cleaner to use in this scenario - you do not have to generate and discard some pointless values.

**Comment by ktoso** [comment]
I suggest to put this to https://github.com/akka/akka-stream-contrib/ which collects various useful stages like this :) WDYT, could you PR over there @marcin-rzeznicki ?

**Comment by manonthegithub** [comment]
@marcin-rzeznicki agree with you.
 
@ktoso Won't it be great to add this logic in existing Delay stage and delay() method of FlowOps as additional parameter?

**Comment by marcin-rzeznicki** [comment]
@ktoso Sure, makes sense - thanks for the advice
@manonthegithub - if you guys agree on this, I can do both if needed

**Comment by marcin-rzeznicki** [comment]
Ping @ktoso @manonthegithub ⬆️

**Comment by manonthegithub** [comment]
@marcin-rzeznicki ktoso is maintainer, he better knows, I just made suggestion.

**Comment by ktoso** [comment]
Hmm, I would prefer to put it into the extras for now and we can move it in to Akka main if enough people use it. Seems useful but not common enough to put onto FlowOps - we on purpose try to put as "minimal" API as we possibly can onto it to keep the number of ops relatively small.

**Comment by marcin-rzeznicki** [comment]
Well, yes, we all agreed to that. When poinitng ⬆️ I tried to kindly draw your attention to a PR to `contrib`. Can't you see it? https://github.com/akka/akka-stream-contrib/pull/88

**Comment by ktoso** [comment]
That's not how I understood the messages here ;)
Thanks, will get to it soon, we're planning the next months of devleopment now so will be slow to review this week.

**Comment by marcin-rzeznicki** [comment]
Excuse me - my fault obviously :-) Thanks for explanations. Happy planning!

**Comment by 2m** [comment]
Merged to akka-stream-contrib.
