### ISSUE TITLE
Review the materializer's and the GraphStagePhase's uses of arrays (ArrayList, ArrayDeque, etc)

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22429]
For simplicity I just made this fixed size, but these will fail on larger graphs. These have to be fixed by resizing wherever/whenever necessary.

**Comment by drewhk** [comment]
see also https://github.com/akka/akka/pull/22264#discussion_r104368750

**Comment by patriknw** [comment]
feel free to continue with this now, @2m

**Comment by drewhk** [comment]
I recommend to change the default size of those arrays to `1` and then add resize logic. Tests should not break (if resize would not work basically all tests would fail with `1`). Then set the default array size so that 99% of our tests pass without a resize (I think `16` will be fine as a default).
