### ISSUE TITLE
Add mergePreferred to FlowOps trait in streams

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka#22422]
I've seen lack of method in FlowOps merging two flows with MergePreferred GraphStage. 
If it will be useful, I can try to implement this.

**Comment by patriknw** [comment]
Does mergePreferred deserve its own method? Wdyt @ktoso @jrudolph @johanandren @drewhk @2m ?

**Comment by johanandren** [comment]
I don't think so. Special case plus most useful in GraphDSL with loops etc.

**Comment by ktoso** [comment]
I'm also against adding it onto FlowOps, however I would be in favor of making it simple to use as a Source: 
See issue: https://github.com/akka/akka/issues/23032 
and proposal PR: https://github.com/akka/akka/pull/23033

**Comment by nadavwr** [comment]
Given two sources, I see how I can have them merged: `s1.merge(s2)`. I also see how I can use `Source.combine` to apply `MergePreferred` instead. If instead I had a flow&source pair—then I'd be in for trouble: I can use `myFlow.merge(mySource)`, but I can't use `Source.combine`. I'll have to drop to GraphDSL and duplicate code similar to `Flow.mergeGraph`.

Regarding the usefulness of MergePreferred, off the top of my head, it'd be useful for implementing the Rx combinator [TakeUntil](http://reactivex.io/documentation/operators/takeuntil.html). I'd use it if it became available.
