### ISSUE TITLE
Harden layout classes error handling

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22432]
There are some cases where better error reporting might be needed. This is most likely affecting the GraphDSL where someone attempts to miswire things (not wire a port, or try to wire a port twice). Please check if proper, meaningful errors are reported, and fix if necessary.

**Comment by johanandren** [comment]
Didn't @jrudolph fix this already?

**Comment by jrudolph** [comment]
Yep, @2m and me improved this. Didn't see the ticket back then.

Fixed here:
https://github.com/akka/akka/pull/22483
https://github.com/akka/akka/pull/22492
