### ISSUE TITLE
Restore debug statements in `ActorGraphInterpreter` and `GraphInterpreter`

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22433]
Some internal debug messages have been changed, or disabled, because they relied on the existence of `GraphAssembly`, or other things that are now gone due to refactorings. Investigate what changes must be done to restore these debug statements (or have something similar).

Error reporting in `GraphInterpreter` should also be fixed, when a user exception is encountered and logged. Since the original stage is no longer available, only the `GraphStageLogic`, investigate how to make it accessible again (maybe an extra `var` in `GraphStageLogic`).

**Comment by johanandren** [comment]
There still might be something that could be done for `akka.stream.impl.fusing.ActorGraphInterpreter.ActorOutputBoundary` and `akka.stream.impl.fusing.ActorGraphInterpreter.BatchingActorInputBoundary` but I couldn't quite figure out how/what would be useful. Save that as a possible future improvement and close this perhaps?
