### ISSUE TITLE
Investigate attributes semantics

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22436]
I think there were some changes in how attributes work. These discrepancies should be investigated and decided:

 - if the new approach is better/more consistent. Then this will be a breaking change that needs be mentioned in migration guide
 - if the new approach is wrong/confusing. Then it must be fixed.

**Comment by patriknw** [comment]
Something wrong with attributes as can be seen with failing `FileSinkSpec`. See comment https://github.com/akka/akka/pull/22465#pullrequestreview-25310144
