### ISSUE TITLE
Java API - an abstract actor class for PersistentFsm and AtLeastOnceDelivery traits 

### ISSUE THREAD

**Issue by rotomer** [akka/akka#22457]
_This issue tracks the request mentioned in the following Akka user list topic - https://groups.google.com/forum/#!topic/akka-user/mJTjpClYjbw_

For the benefit of the Java API users it would be beneficial to add an abstract class that implements the traits PersistentFSM & AtLeastOnceDelivery. 

Konrad Malawski mentioned that mixing in the two Scala traits PersistentFSM & AtLeastOnceDelivery should work in theory. I hope to perform testing on how such mixin works out within the next month or two.

As mentioned in the user list topic - it seems there are others that found such an abstract actor to be a desired feature as well. See http://www.google.com/url?q=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F39374797%2Fcan-i-mix-persistenct-fsm-and-at-least-once-message-delivery-in-akka&sa=D&sntz=1&usg=AFQjCNGeoz-VVnrBiDdcxAdaCJgAoOcyAQ

**Comment by amirhmd** [comment]
hi guys, I am totally new to open source ,is it a good place to start contributing in this project? for me it doesn't matter I am looking for something easy to get the idea and contribute... if you think that there might be some other thing which is much more convenient for a starter please guide me I am all in.

**Comment by amirhmd** [comment]
There are several warning during SBT project import such as SBT project import module not found: com.typesafe.akka#akka-stream_2.11;2.5-SNAPSHOT, and so on..

**Comment by raboof** [comment]
Hi Amir, welcome! We'll try to help you out ;). Generally the best place to start would be a small issue that you care about as a user yourself - this one might be as good as any other :).

As for the sbt warnings, I don't think I've seen that. This issue doesn't seem like the proper place to discuss this, though - perhaps join us on gitter at https://gitter.im/akka/dev?

**Comment by patrox** [comment]
hi @rotomer, I read the mention user list topic, where @ktoso suggested to mix in the `AtLeastOnceDelivery` to the `PersistentFSM` and I ended up with sth like:

```scala
abstract class AbstractPersistentFSMWithAtLeastOnceDelivery[S <: FSMState, D, E] extends AbstractPersistentFSM[S, D, E] with AtLeastOnceDelivery
```

Do you think it's what you were after ?

**Comment by rotomer** [comment]
Hi @patrox, 

Thanks for handling this 👍 

Yes, I believe that was it. I didn't had the chance yet to test it due to a shift in priorities between my projects.

Would you like to create a PR with this Java API actor for the Akka core team to review?

**Comment by patrox** [comment]
@ktoso Can you please check if my proposal two comments above makes sense ?
Long story short: we would like to have a one base java class for `Persistent`, `FSM` actor with `AtLeastOnceDelivery`.

If my proposal is fine, then could you please advise how it could be tested, as I imagine it should pass both `[PersistentFSMSpec](https://github.com/akka/akka/blob/master/akka-persistence/src/test/scala/akka/persistence/fsm/PersistentFSMSpec.scala)` and `[AtLeastOnceDeliverySpec](https://github.com/akka/akka/blob/master/akka-persistence/src/test/scala/akka/persistence/AtLeastOnceDeliverySpec.scala) test suites, right ?

Is there some way to reuse those tests without duplicating them ?

**Comment by ktoso** [comment]
I think that could work.

Yes, tests can be shared, you would have to refactor them into a Base class and make all test which need them extend them - and provide a hook for starting actors in the specific test. Though I'm not sure that will be the best here, since it may differ quite a bit - I'd propose just testing some of the cases and if those work others will too.

(the method for sharing tests is seen in for example `LeveldbAtLeastOnceDeliverySpec`)

**Comment by patrox** [comment]
OK, that sound a bit like what I had already in mind - pick some specific tests to `PersistentFSM` and to `AtLeastOnceDelivery` and make sure that they pass. So, I'll follow up with this like that.

Thanks for you input.

**Comment by harnitbakshi** [comment]
Hi sorry any updates on this please? We are looking for something similar to this as well

**Comment by patriknw** [comment]
feature is deprecated
