### ISSUE TITLE
akka-stream uses `Predef.conforms` which is removed in Scala 2.13

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#22451]
this came up in the Scala 2.13 community build, where akka now fails to compile because we have started actually removing deprecated stuff in 2.13

in akka-stream/src/main/scala/akka/stream/impl/ConstantFun.scala we see:

```scala
def scalaIdentityFunction[T]: T ⇒ T = conforms
```

this was introduced by @rkuhn in 1500d1f36d18cc3fd5a0240924e32de73575c419; the commit message says "This commit also changes all uses of Predef.identity to use `conforms`", but I don't know why, so I hesitate to just revert the change.

**Comment by ktoso** [comment]
It's a sneaky trick to avoid allocations - identity used to allocate a new
function, conforms used a cached one.
Nowadays we have a special object which cached functions for this, so we
can remove the conforms usages. Thanks for opening the ticket Seth, we'll
remove those

-- 
Konrad Malawski

**Comment by SethTisue** [comment]
see also #22486

**Comment by patriknw** [comment]
@bantonsson did you fix this?

**Comment by bantonsson** [comment]
I think that @SethTisue Already fixed it in his PR.
