### ISSUE TITLE
Document internals of the new materializer

### ISSUE THREAD

**Issue by drewhk** [akka/akka#22458]

**Comment by jrudolph** [comment]
Please also document a bit about the design constraints and how the current solution fits in, where the complexities come from etc.

**Comment by drewhk** [comment]
Yes, agreed. I was thinking on writing up some separate doc, because sprinkling all this information in various scaladoc/code comments will make it hard to understand it.

**Comment by patriknw** [comment]
I think it should be documented close to the source code so in a scaladoc for the impl package (even though this is not public docs) or in a readme.md  in that directory (perhaps not good to include in jars).

**Comment by drewhk** [comment]
package is fine

**Comment by richard-imaoka** [comment]
Hi, just for housekeeping, I assume this was already fixed by #22699 ?

**Comment by patriknw** [comment]
Yes, thanks
