### ISSUE TITLE
Docs problem with Actors and shared mutable state code

### ISSUE THREAD

**Issue by fancellu** [akka/akka#22453]
http://doc.akka.io/docs/akka/2.4/general/jmm.html

https://github.com/akka/akka/blob/4a7cd147313404eb8137e56163e54f06c23640d0/akka-docs/rst/general/jmm.rst

``` Future { expensiveCalculation() } onComplete { f => self ! f.value.get }```

won't compile.

onComplete gives a Try

do you mean foreach?

e.g.

```Future { expensiveCalculation() } foreach { value => self ! value }```

**Comment by ktoso** [comment]
Oh wow, we usually never have in-line code snippets in docs to avoid such an issue (we include actual compiled source files usually), seems you found a bug there. Thanks!

Would you like to submit a fix PR?

**Comment by fancellu** [comment]
Sorry, rather busy.

The supplied code should work fine, I guess.

Dino.

**Comment by jlprat** [comment]
I can do it 😉
