### ISSUE TITLE
Failing tests for new materializer

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22463]
* [x] akka.stream.io.TlsSpec
* [x] akka.stream.scaladsl.AttributesSpec
* [x] akka.stream.DslFactoriesConsistencySpec
* [x] akka.stream.scaladsl.SinkSpec
* [x] akka.stream.actor.ActorSubscriberSpec
* [x] akka.stream.io.OutputStreamSourceSpec
* [x] akka.stream.io.FileSourceSpec
* [x] akka.stream.scaladsl.FlowScanAsyncSpec (#22474)
* [x] akka.stream.scaladsl.FlowSectionSpec
* [x] akka.stream.javadsl.SinkTest
* [x] akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec
* [x] akka.stream.scaladsl.FlowSpec
* [x] akka.stream.scaladsl.UnfoldResourceSourceSpec
* [x] akka.stream.scaladsl.FlowRecoverWithSpec
* [x] akka.stream.scaladsl.SinkAsJavaStreamSpec
* [x] akka.stream.scaladsl.ReverseArrowSpec
* [x] akka.stream.scaladsl.FlowScanSpec (#22474)
* [x] akka.stream.scaladsl.ActorRefSourceSpec
* [x] akka.stream.scaladsl.GraphMergePreferredSpec
* [x] akka.stream.io.FileSinkSpec
* [x] akka.stream.io.TcpSpec
* [x] akka.stream.actor.ActorPublisherSpec
* [x] akka.stream.io.InputStreamSinkSpec
* [x] akka.stream.scaladsl.RunnableGraphSpec
* [x] akka.stream.scaladsl.GraphDSLCompileSpec

New ones:

 * [x]  akka.stream.impl.GraphStageLogicSpec
 * [x] akka.stream.FusingSpec

**Comment by patriknw** [comment]
TcpSpec sometimes fails

**Comment by patriknw** [comment]
I'll grab akka.stream.DslFactoriesConsistencySpec

**Comment by jrudolph** [comment]
I'll take `GraphDSLCompileSpec`.

**Comment by johanandren** [comment]
Picking up `akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec` and `akka.stream.scaladsl.UnfoldResourceSourceSpec`

**Comment by patriknw** [comment]
I think `OutputStreamSourceSpec` and `InputStreamSinkSpec` are related to the actor naming, so I'm picking those

**Comment by patriknw** [comment]
Here is a stacktrace of failing `TcpSpec`:
```
[WARN] [03/08/2017 10:39:22.313] [default-akka.actor.default-dispatcher-2] [akka://default/system/IO-TCP/selectors/$a/1] received dead letter from Actor[akka://default/system/IO-TCP/selectors/$a/1#-2015483522]: akka.io.SelectionHandler$ChannelRegistryImpl$$anon$4$$anon$5@720f400c
[INFO] [03/08/2017 10:39:22.313] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/1] Message [akka.io.SelectionHandler$ChannelRegistryImpl$$anon$4$$anon$5] from Actor[akka://default/system/IO-TCP/selectors/$a/1#-2015483522] to Actor[akka://default/system/IO-TCP/selectors/$a/1#-2015483522] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
--- Stream actors debug dump ---
Stream is completed. No debug information is available
[info] - must handle when connection actor terminates unexpectedly *** FAILED *** (7 seconds, 54 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 50 times, sleeping 100 milliseconds between each query. (TcpSpec.scala:415)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$22.apply$mcV$sp(TcpSpec.scala:415)
[info]   at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$22.apply(TcpSpec.scala:402)
[info]   at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$22.apply(TcpSpec.scala:402)
```

**Comment by jrudolph** [comment]
I'll have a look at `GraphStageLogicSpec`

**Comment by patriknw** [comment]
This is what is remaining

**SinkSpec** related to attributes
**RunnableGraphSpec** related to attributes

**GraphStageLogicSpec**
```
[info] - must not double-terminate a single stage *** FAILED *** (2 seconds, 27 milliseconds)
[info]   java.lang.ArrayIndexOutOfBoundsException: -1
[info]   at akka.stream.stage.GraphStageLogic.setHandler(GraphStage.scala:353)
[info]   at akka.stream.impl.fusing.GraphInterpreterSpecKit$Builder$Upstream$.<init>(GraphInterpreterSpecKit.scala:199)
[info]   at akka.stream.impl.fusing.GraphInterpreterSpecKit$Builder.Upstream$lzycompute(GraphInterpreterSpecKit.scala:195)
[info]   at akka.stream.impl.fusing.GraphInterpreterSpecKit$Builder.Upstream(GraphInterpreterSpecKit.scala:195)
[info]   at akka.stream.impl.GraphStageLogicSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anon$15.<init>(GraphStageLogicSpec.scala:190)
[info]   at akka.stream.impl.GraphStageLogicSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(GraphStageLogicSpec.scala:177)
[info]   at akka.stream.impl.GraphStageLogicSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(GraphStageLogicSpec.scala:177)
```

**TcpSpec**, [see](https://github.com/akka/akka/issues/22463#issuecomment-284994034)

**GraphMergePreferredSpec** Expected exception java.lang.IllegalArgumentException to be thrown, but java.util.NoSuchElementException was thrown (GraphMergePreferredSpec.scala:67)

**Comment by johanandren** [comment]
"be able to handle Subscriber spec violations without leaking"  in `ActorGraphInterpreterSpec` also

**Comment by drewhk** [comment]
@2m is doing MergePreferredSpec AFAIR

**Comment by patriknw** [comment]
I'll grab SinkSpec and SinkSpec - I just love Attributes ;-)

**Comment by drewhk** [comment]
I bet ;) What is not to love about 'em.

**Comment by drewhk** [comment]
Taking GraphStageLogicSpec
