### ISSUE TITLE
AbstractActor missing variants and naming convention

### ISSUE THREAD

**Issue by guidomedina** [akka/akka#22462]
There is no combination for `AbstractLoggingActorWithStash` and while at it, I think should be like the following for IDE auto completion's sake:
- Rename `AbstractLoggingActor` to `AbstractActorWithLogging`
- Add `AbstractActorWithLoggingAndStash`
- Add `AbstractActorWithLoggingAndUnlimitedStash`
- Add `AbstractActorWithLoggingAndUnrestrictedStash`

**Comment by guidomedina** [comment]
I'm now not to bias towards one convention or the other, maybe `AbstractLoggingActorWith...` isn't too bad.

**Comment by patriknw** [comment]
Then someone want similar for persistence, fsm, ... hm, the number of combinations will explode.  
The `WithLogging` doesn't save much code, since the only thing needed is:

    LoggingAdapter log = Logging.getLogger(getContext().system(), this);

**Comment by guidomedina** [comment]
I guess you have a point, I didn't think about it, I only looked at one class and noticed these were missing so I guess there is no point on adding more, closing.

**Comment by patriknw** [comment]
Thanks
