### ISSUE TITLE
Potential bug when building a Replicator.receiveStatus response

### ISSUE THREAD

**Issue by Horusiath** [akka/akka#22487]
While working on .NET implementation of distributed data plugin we've hit the bug that probably also affects JVM implementation. Problem lies [here](https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala#L1561). 

In case, when there's a chunked gossip to be send, we're relying on assumption that `_.hashCode % totChunks == chunk` will eventually reach one of the chunks (i.e. if `totChunk` is 3, valid `chunk` values will be 0, 1, 2). However it is possible, that this expression will return a negative number, which means that correlated key will never be enclosed into any of chunks.

To compare, when [producing](https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala#L1533) a Status message, hashCode is being `math.abs`ed, so we'll never deal with negative values.

**Comment by patriknw** [comment]
ah, good observation, that is indeed a bug

**Comment by johanandren** [comment]
Thanks for letting us know @Horusiath !
