### ISSUE TITLE
how to use hystrix with akka ?

### ISSUE THREAD

**Issue by shivani147** [akka/akka#22491]
I am using akka http which is returning the Future object, while executing the run method is is not throwing any exception but at later point it is throwing connection refused exception, how to handle this?

**Comment by johanandren** [comment]
Hi @shivani147, please use the mailing list (https://groups.google.com/forum/#!forum/akka-user) or the gitter channel (https://gitter.im/akka/akka) for questions! The issue tracker is only for for bugs and feature tracking, thanks!
