### ISSUE TITLE
Nested attributes need another thought

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22523]
`asJavaStream` is created as:

```scala
Sink.fromGraph(new QueueSink[T]())
  .withAttributes(DefaultAttributes.asJavaStream)
```

The expected name is "asJavaStream", but it becomes "queueSink" (before in the attr list).

Similar if adding a custom `name`, "queueSink" is still more specific (first in attr list).

A workaround is to remove the inner name.

```scala
Sink.fromGraph(new QueueSink[T]().withAttributes(Attributes.none))
```

**Comment by patriknw** [comment]
Another workaround that doesn't work fully is
```scala
Sink.fromGraph(new QueueSink[T]()
  .withAttributes(DefaultAttributes.asJavaStream))
```

That doesn't work with custom `name` or `dispatchers`.
For example:
```scala
StreamConverters.asJavaStream().named("myJavaStream").addAttributes(ActorAttributes.dispatcher("mydisp"))
```
when materialized the attributes are 
```
Attributes(List(Dispatcher(akka.stream.default-blocking-io-dispatcher), Name(asJavaStream), Dispatcher(mydisp), Name(myJavaStream), Dispatcher(akka.test.stream-dispatcher), InputBuffer(4,16), SupervisionStrategy(<function1>)))
```

I think we might have this problem at more places, e.g. `head` is created as 
```scala
Sink.fromGraph(new HeadOptionStage[T]).withAttributes(DefaultAttributes.headSink)
```

**Comment by jrudolph** [comment]
(Dumping thoughts that already lingered for a while)

To fix this we need to consider two aspects:

 * What are the current usages of attributes and what semantics are needed for each single attribute type we know (especially dispatcher, name, async, and supervisionStrategy)
   * It should be checked for different forms of combining flows:
     * `Source.via(flow).withAttributes`().to(Sink)`
     * `Source.withAttributes.to(flow.to(Sink))`
     * `Source.to(flow.withAttributes.to(Sink))`
     * etc.
  * What general set of semantics are reasonable and unsurprising without looking at the actual type of the attribute? I.e. looking again at different ways of combining a flow what would be reasonable ways how `inheritedAttributes` in stages should look like. Is inheriting from composites to components needed at all?

When we have done that we should be able to see whether we can even achieve the needed semantics for the particular attribute types by implementing unsurprising semantics for attributes in general.

**Comment by ktoso** [comment]
Related issues:
- Streams's `withAttributes` doesn't override default attributes #23649

**Comment by johanandren** [comment]
#24000 fixes the issue that `fromGraph(graphStage)` causes nesting which in turn makes the initial attributes of the stage being sealed off from overriding.

What that PR does not change is when you are setting attributes on a nested graph, for example in `Source.via(flow).addAttribute()` the attribute are set on the composed graph, and since the most specific attribute "wins" any attribute already on the source or the flow cannot really be changed after the fact. This is fine for example for `Name` but stops us from modifying `Dispatcher`for a whole subgraph, when it is set in the `initialAttributes` of stages in the subgraph.

**Comment by johanandren** [comment]
We have decided to not change the way the attributes works. While investigating this we tried out the following ideas:

 * Change order of attributes and materializer setting attributes #24014
 * Introduce a `defaultAttributes` on graph stages that is sandwiched between materializer setting attributes and the graph attributes #24054  
 * A more flexible way of locking/unlocking attributes #24007
 * Mimicing `important!` from CSS for attributes #24018

**Comment by patriknw** [comment]
@johanandren Shall we close this ticket? You fixed the original problem, right? Or shall we have this lingering as reference for the additional ideas/attempts?

**Comment by johanandren** [comment]
I think we can close it given that we made a decision for now. It will still be here for the future historians.
