### ISSUE TITLE
debug logging of ClusterSingletonProxy

### ISSUE THREAD

**Issue by chaosky** [akka/akka#22533]
[ClusterSingletonProxy line 257](https://github.com/akka/akka/blob/v2.4.17/akka-cluster-tools/src/main/scala/akka/cluster/singleton/ClusterSingletonProxy.scala#L257)

```scala
if (log.isDebugEnabled)
            log.debug(
              "Forwarding message of type [{}] to current singleton instance at [{}]: {}",
              Logging.simpleName(msg.getClass.getName), s.path)
```

`Logging.simpleName(msg.getClass.getName)` always returns String, whether it should return the type of message, and the number of parameters is not right.

**Comment by ktoso** [comment]
Looks to be a mistake, should just be simpleName from the object. Could you PR a fix?

**Comment by patriknw** [comment]
yes, please fix

**Comment by chaosky** [comment]
I am confused about the third parameter, it is the identity of the message (eg: `Object.toString()`, `getClass().getName() + '@' + Integer.toHexString(hashCode())`) or the sender's path, or something else?
