### ISSUE TITLE
Pool Router for workers with different attribute value 

### ISSUE THREAD

**Issue by mladendinev** [akka/akka#22549]
I was trying to create a RoundRobinPool router for my application, but I realized that I can't provide different properties for my routees. What am I supposed to do if my Worker has for instance `property `"timestamp" which as you may infer is different for each worker and which is provided dynamically?

```
    context.actorOf(
      ClusterRouterPool(RoundRobinPool(7,Some(resizer)),
        ClusterRouterPoolSettings(
          totalInstances = Int.MaxValue,
          maxInstancesPerNode = 10,
          allowLocalRoutees = false,
          useRole = Some("worker")
        )
      ).props(Worker.props(???)])
```

**Comment by patriknw** [comment]
The constructor parameters must be known and serializable when you create the router Pool.
Where would the `timestamp` come from? If it's the timestamp of when the actor is created you can just put it in the constructor or in the factory of Props that creates the actor instance.

We don't use GitHub issues for questions, so please use [akka-user](https://groups.google.com/forum/#!forum/akka-user) if you have more questions.
