### ISSUE TITLE
AbstractPersistentFSM should extend AbstractActor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22541]
I think this was mentioned by @johanandren.

Not because of `createReceive` but for other Java API such as `getContext()`

**Comment by ortigali** [comment]
May I take this?

**Comment by patriknw** [comment]
@ortigali yes, excellent

**Comment by johanandren** [comment]
I'll update the docs before we close this ticket!

**Comment by johanandren** [comment]
Actually, that I was talking about was AbstractFSM which lacks the corresponding methods. I'll open a new ticket for that.
