### ISSUE TITLE
Discuss cluster "rolling upgrade mode" / special configuration for first seed node

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22548]
Currently, the first seed node in the list is special as it is the only one which has the power to create a new cluster. This is currently only specified by the order of nodes in the seed nodes list.

Also, during a rolling update of the cluster, even the first seed node usually shouldn't be able to create a new cluster "accidentally", i.e. when it isn't able to make contact with any other nodes during the (by default somewhat short 5 second) `seed-node-timeout` period.

The question is how to introduce this configuration change in a compatible way.

Here's a suggestion:

Introduce a new setting `cluster-creation-node` that specifies which node is allowed to create a new cluster. It would need to be set to one of those settings:
 * `first-seed-node`, the default which would fall back to the current behavior
 * `<actor-system-address>`, this node will create the cluster immediately if its address is the same as the given one (or alternatively, just use this address as the first seed node using the existing scheme, i.e. checking the other seed nodes for an existing cluster before recreating a new one)
 * `off`, no node is allowed to (re)create the cluster, used for rolling upgrades under the assumption that the cluster must already be up

Creating a new cluster and making a rolling upgrade would need different configurations but accidentally creating new clusters would be prevented.

**Comment by patriknw** [comment]
> `<actor-system-address>`, this node will create the cluster immediately if its address is the same as the given one (or alternatively, just use this address as the first seed node using the existing scheme, i.e. checking the other seed nodes for an existing cluster before recreating a new one)

I think it should be the latter. If you really want to start a new cluster without trying to join others first the `seed-nodes` list should be empty and set this new property.

It could also be useful to support `on`, meaning that this specific node is the one that can join itself, but you don't have to know the `actor-system-address`.

I like this suggestion and I think it can be introduced in a compatible way as suggested.

**Comment by swsnider** [comment]
What about clusters where `min-nr-of-members` is set to `(n/2)+1`, so there is no danger of island clusters? This is causing us issues when the first seed node in the list is down for hardware failure, so the cluster just refuses to form.

**Comment by eugenemiretsky** [comment]
Hi @swsnider, how is your situation different than a regular situation where the first node is down? Why would restarted nodes fail to join the cluster?

**Comment by helena** [comment]
Revisit or close in light of newer work?

**Comment by raboof** [comment]
I agree should now be an akka-management concern, so let's close it here?

**Comment by patriknw** [comment]
I agree. While it's still would be better to have more clear config for `seed-nodes` it's not worth changing, since that is also trouble for existing users.

**Comment by helena** [comment]
It's now labeled with the [rolling upgrades](https://github.com/akka/akka/labels/t%3Arolling-updates) tag so we won't loose track of the original idea in relation to rolls.
