### ISSUE TITLE
Akka Scala Documentation - PDF - Section 2.5.2 Native Packager instructions don't work

### ISSUE THREAD

**Issue by AkkaScalaDev** [akka/akka#22545]
Hello,

Document: Akka Scala Documentation (PDF)
Release: 2.4.17

In Section 2.5.2 the Native Packager instructions are meant to allow the user to create a standalone Hello World example; unfortunately this doesn't work because the instructions overlook writing the actual code. Following the instructions as they stand results in a ClassNotFoundException when the following command is run:

akka-sample-main-scala-2.4.17/bin/akka-sample-main-scala sample.hello.Main

Thanks,

Martin.

**Comment by johanandren** [comment]
Hi Martin, this is intentionally, you are not meant to learn how to write an Akka application by reading that section, only how to package the application you already wrote using the native packager. How to write an application with Akka is covered in other parts of the documentation, for example here: http://doc.akka.io/docs/akka/2.4/scala/hello-world.html

I'll therefore close this ticket.
