### ISSUE TITLE
[Documentation] Akka Cluster/Remote with SSL 

### ISSUE THREAD

**Issue by jjlopezm** [akka/akka#22566]
I was trying to use ssl in an akka cluster. To do that, I follow the doc...  http://doc.akka.io/docs/akka/2.4/scala/remoting.html#Configuring_SSL_TLS_for_Akka_Remoting

IMHO, it could be a good idea to include that its necessary to specify the hostname and port of the ssl connection actor. The problem is, if you don't specify those parammeters, the cluster node will be started at 127.0.0.1 always, and it's is possible that it can't discover itself due to the seed nodes maybe won't be at 127.0.0.1. 

Example:
akka {
  remote {
    netty.ssl.security {
      hostname = myHosy
      port = 12345
      key-store = "/example/path/to/mykeystore.jks"
      trust-store = "/example/path/to/mytruststore.jks" 
      key-store-password = "changeme"
      key-password = "changeme"
      trust-store-password = "changeme" 
      protocol = "TLSv1.2" 
      enabled-algorithms = [TLS_DHE_RSA_WITH_AES_128_GCM_SHA256] 
      random-number-generator = "AES128CounterSecureRNG"
    }
  }
}

**Comment by patriknw** [comment]
Sounds like a valid point, thanks. Would you be able to open a pull request with the improvement?

**Comment by raboof** [comment]
Fixed in #22591
