### ISSUE TITLE
Flow.map(???).mapConcat(???) may deadlock

### ISSUE THREAD

**Issue by alexeevg** [akka/akka#22585]
Deadlock occurs depending on whether stream fusing is turned on and "surrounding context" (for the lack of a better term).
Here's the code demonstrating the problem:
```scala
object StreamDeadlock extends App {
  import akka.actor._
  import akka.stream._
  import akka.stream.scaladsl._
  import scala.concurrent.Await

  implicit val system = ActorSystem()

  val noFusingMaterializer = ActorMaterializer(ActorMaterializerSettings(system).withAutoFusing(false))
  val fusingMaterializer = ActorMaterializer(ActorMaterializerSettings(system).withAutoFusing(true))

  val source = Source(1 to 20)
  val thisCanDeadlockSometimes = Flow[Int].map(_ + 1).mapConcat(x => List(x))
  val printFlow = Flow[Int].map(println)
  val sink = Flow[Int].via(thisCanDeadlockSometimes).via(printFlow).toMat(Sink.ignore)(Keep.right)

  println("Running inlined stream without fusing: OK")
  Await.result(source.via(thisCanDeadlockSometimes).via(printFlow).runWith(Sink.ignore)(noFusingMaterializer), Duration.Inf)

  println("Running composite stream with fusing: OK")
  Await.result(source.runWith(sink)(fusingMaterializer), Duration.Inf)

  println("Running composite stream without fusing: DEADLOCK")
  Await.result(source.runWith(sink)(noFusingMaterializer), Duration.Inf)

  system.terminate()
}
```

Expected output:
```
Running inlined stream without fusing: OK
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
Running composite stream with fusing: OK
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
Running composite stream without fusing: DEADLOCK
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
```

Actual output:
```
Running inlined stream without fusing: OK
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
Running composite stream with fusing: OK
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
Running composite stream without fusing: DEADLOCK
(wait indefinitely)
```
Tested on akka 2.4.17 / Scala 2.12.1

**Comment by ktoso** [comment]
Please note, the `withAutoFusing` option do nothing on current `master`.
PR here: https://github.com/akka/akka/pull/22530/files#diff-9d42185f80bc3bc7ce18fb21bb83152cR436

**Comment by alexeevg** [comment]
Also note that the bug can be reproduced with `statefulMapConcat as well`:
```scala
val thisCanDeadlockSometimes = Flow[Int].map(_ + 1).statefulMapConcat(() => x => List(x))
```

**Comment by johanandren** [comment]
`mapConcat` and `statefulMapConcat` actually are implemented using the same stage, so that is not so surprising.

Here's the most minimal reproducer I can come up with, if I change any of the stream building steps, or remove one of these stages, not using the identity flow for example, it fixes the deadlock O.o
```
val noFusingMaterializer = 
  ActorMaterializer(ActorMaterializerSettings(system).withAutoFusing(false))

val sink = Flow[Int]
  .via(Flow[Int].map(_ + 1).mapConcat(x ⇒ List(x)))
  .toMat(Sink.ignore)(Keep.right)

Source.empty[Int].runWith(sink)(noFusingMaterializer).futureValue
```

While debugging I can see that `onUpstreamFinish` is never called, so something with the interpreter perhaps.

**Comment by jrudolph** [comment]
@johanandren Did you get anywhere with this one?

I was curious, so I had a look at that one as well. (https://github.com/akka/akka/compare/release-2.4...jrudolph:jr/w/22585-source-deadlock?expand=1 contains the extra debugging output I looked at) It seems what happens is that the stream ends up with one Publisher / Subscriber pair being never connected so that completion is never propagated to the end.

It could be an issue of the old materializer. I also suspected it to be a race condition in one of the boundary stages but that seems unlikely as the test seems to fail non-deterministically.

**Comment by jrudolph** [comment]
Another sign that this is related to the old materializer is that it requires the strange `source.runWith(Flow.via.toMat)` structure to happen.

**Comment by johanandren** [comment]
I have a repeating test, but haven't really gotten anywhere figuring it out. Looking at the debug output of the interpreter it seems as the upstream actor/stages complete but that information never reaches the flatMapConcat stage actor.

**Comment by johanandren** [comment]
The repeating test fails consistently, on every run, on both my machines though, could still be race ofc.

**Comment by johanandren** [comment]
Some tracing/debugging conclusions:

The interpreter that runs Map shuts down its actor, but downstream of that the FlatMapConcat and the Ignore actors stay alive. Traces of the boundaries show that for the Map interpreter actor:

* `BatchingActorInputBoundary.onComplete` is executed
* the `GraphStageLogic` completes
* `ActorOutputBoundary.complete` is executed, at this time there is an `exposedPublisher` which is shutdown, but the `subscriber` is null.

With interpreter debug logging on, this is the last that happens, no more events at all until the timeout hits and the fail tears the stream down.

**Comment by johanandren** [comment]
I'm not getting anywhere with this, heres a run with very verbose debug outputs added:
[MapConcat-deadlock-output.txt](https://github.com/akka/akka/files/867953/MapConcat-deadlock-output.txt)

Repeater can be found in this commit: https://github.com/johanandren/akka/commit/576295112f7235f519d701cd62bd4353b0b435b5

**Comment by jrudolph** [comment]
A few points why I think it might be a bug in the old materializer:

 * it depends on the internal structure of the stream graph and traversal
 * auto-fusing was switched on a long time ago and regular materialization (especially wiring of publishers and subscribers) has probably not been exercised a lot
 * it looks as if the subcriber-side of `flatMapConcat` is never subscribed to its upstream publisher (i.e.  the `subscribe` method of the upstream publisher is never called, though I might have overlooked something here)
 * while surrounding behavior is non-deterministic, the failure itself happens deterministically

**Comment by bantonsson** [comment]
@jrudolph I think that I can corroborate that the `flatMapConcat` is never connected to the `map` that is just in front of it. Looks like the `Map.out` and the `StatefulMapConcat.in` are never connected 😞 I have no real idea why yet though.

**Comment by bantonsson** [comment]
Just noticed another funny thing. Whatever I put first in the `Flow[Int].X` never gets its `out` connected to the next part of the flow. The out port seems to be missing from the `outlets` when you exit the scope of that module.

**Comment by jrudolph** [comment]
Yeah, I tried adding a few printlns to the wiring methods in `StreamLayout` and what it does seems pretty messed up with some things wired multiple times and others seem to be wired in the wrong scope, etc. 

I wonder if it really makes sense to fix it or we should people steer away from using `withAutoFusing(false)` in 2.4.

**Comment by johanandren** [comment]
Isn't it strange that the elements flow through the stream like expected though (my sample fail was `Source.empty` but the original was `Source(0 to 20)`) if it is wired wrong?

**Comment by bantonsson** [comment]
I've had several different `Source` statements to test things, and I don't get a single element in the first `map` operation with `.withAutoFusing(false)`, but everything works fine with `.withAutoFusing(true)`.

**Comment by bantonsson** [comment]
I can't see anything really wrong in the `wiring` calls in this small test, and the `Modules` look ok (but what do I know). It feels like something breaks when we **_materialize_** the different parts and hook them up.

**Comment by johanandren** [comment]
Hm. Maybe I remembered that incorrectly, I thought i was only about completion not happening.

**Comment by bantonsson** [comment]
So this seems to have something to do with how a `CompositeModule` inside a `CompositeModule` is connected (via assignPorts) during materialization.

I currently have this sink that is attached to a `Source.empty[Int]`:
`Flow[Int].via(Flow[Int].map(_ + 1).filter(_ ⇒ true)).toMat(Sink.ignore)(Keep.right)`

The map and the filter are inside a `CompositeModule` (`67844474 `) and the `Map.out` is never properly hooked up to `Filter.in` since when `assignPort` is called, the `currentLayout` points to the outer `CompositeModule` (`3ba48c4a`) that doesn't have anything useful in the `upstreams` and `downstreams`.

If I push and pop the `moduleStack` around handling a `CompositeModule` then this test works fine, but lots of other tests start to fail (yes, I tried to run all stream tests with `auto-fusing = off` and there are failures normally, but not that many).

So I've tried to minimize the noise from my debugging, and here is a full output:
```
beginning materialization of CompositeModule [35434a23]
  Name: unnamed
  Modules:
    (lazySource) GraphStage(EmptySource) [51a18594]
    (unnamed) [3ba48c4a] copy of CompositeModule [48b90d12]
      Name: unnamed
      Modules:
        (unnamed) CompositeModule [67844474]
          Name: unnamed
          Modules:
            (map) GraphStage(Map(<function1>)) [3ad4e035]
            (unnamed) [250dedf9] copy of GraphStage(Filter) [255cb5d7]
          Downstreams:
            Map.out -> Filter.in
          Upstreams:
            Filter.in -> Map.out
          MatValue: Ignore
        (unnamed) [60bef2ec] copy of GraphStage(akka.stream.impl.fusing.GraphStages$IgnoreSink$@37de2bf4) [7d766386]
      Downstreams:
        Filter.out -> Ignore.in
      Upstreams:
        Ignore.in -> Filter.out
      MatValue: Atomic(akka.stream.impl.StreamLayout$CopiedModule[60bef2ec])
  Downstreams:
    EmptySource.out -> Map.in
  Upstreams:
    Map.in -> EmptySource.out
  MatValue: Atomic(akka.stream.impl.StreamLayout$CopiedModule[3ba48c4a])
entering module [35434a23] (StreamLayout$CompositeModule)
materializing GraphStage(EmptySource) [51a18594]
+++ Port assigned (out) 0 for EmptySource.out with empty downstream
+++ currentLayout.downstreams: Map(EmptySource.out -> Map.in)
entering scope [3ba48c4a]
entering module [3ba48c4a] (StreamLayout$CopiedModule)
entering module [48b90d12] (StreamLayout$CompositeModule)
entering module [67844474] (StreamLayout$CompositeModule)
materializing GraphStage(Map(<function1>)) [3ad4e035]
+++ Port assigned (in) 0 for Map.in without upstream
+++ currentLayout.upstreams: Map(Ignore.in -> Filter.out)
+++ Port assigned (out) 0 for Map.out without downstream
+++ currentLayout.downstreams: Map(Filter.out -> Ignore.in)
entering scope [250dedf9]
entering module [250dedf9] (StreamLayout$CopiedModule)
materializing GraphStage(Filter) [255cb5d7]
+++ Port assigned (in) 0 for Filter.in without upstream
+++ currentLayout.upstreams: Map()
+++ Port assigned (out) 0 for Filter.out without downstream
+++ currentLayout.downstreams: Map()
resolving module [250dedf9] computation Atomic(filter[255cb5d7])
  matValSrc = {}
  matVals =
    255cb5d7 -> NotUsed
  Atomic(filter[255cb5d7])
  result = NotUsed
exiting module [250dedf9]
exiting scope [250dedf9]
  subscribers = {Filter.in=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@6a00fa50}
  publishers = {Filter.out=akka.stream.impl.fusing.ActorGraphInterpreter$BoundaryPublisher@173b2fd5}
+++ Port assigned (in) -1 for Filter.in without upstream
+++ currentLayout.upstreams: Map(Ignore.in -> Filter.out)
+++ Port assigned (out) -1 for Filter.out with empty downstream
+++ currentLayout.downstreams: Map(Filter.out -> Ignore.in)
resolving module [67844474] computation Ignore
  matValSrc = {}
  matVals =
    3ad4e035 -> NotUsed
    250dedf9 -> NotUsed
  Ignore
  result = NotUsed
exiting module [67844474]
entering scope [60bef2ec]
entering module [60bef2ec] (StreamLayout$CopiedModule)
materializing GraphStage(akka.stream.impl.fusing.GraphStages$IgnoreSink$@37de2bf4) [7d766386]
+++ Port assigned (in) 0 for Ignore.in without upstream
+++ currentLayout.upstreams: Map()
resolving module [60bef2ec] computation Atomic(ignoreSink[7d766386])
  matValSrc = {}
  matVals =
    7d766386 -> List()
  Atomic(ignoreSink[7d766386])
  result = List()
exiting module [60bef2ec]
exiting scope [60bef2ec]
  subscribers = {Ignore.in=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@5c4cb3bb}
  publishers = {}
+++ Port assigned (in) -1 for Ignore.in with publisher
+++ currentLayout.upstreams: Map(Ignore.in -> Filter.out)
resolving module [48b90d12] computation Atomic(akka.stream.impl.StreamLayout$CopiedModule[60bef2ec])
  matValSrc = {}
  matVals =
    67844474 -> NotUsed
    60bef2ec -> List()
  Atomic(akka.stream.impl.StreamLayout$CopiedModule[60bef2ec])
  result = List()
exiting module [48b90d12]
resolving module [3ba48c4a] computation Atomic(akka.stream.impl.StreamLayout$CompositeModule[48b90d12])
  matValSrc = {}
  matVals =
    48b90d12 -> List()
  Atomic(akka.stream.impl.StreamLayout$CompositeModule[48b90d12])
  result = List()
exiting module [3ba48c4a]
exiting scope [3ba48c4a]
  subscribers = {Filter.in=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@6a00fa50, Ignore.in=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@5c4cb3bb, Map.in=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@2b35ac11}
  publishers = {Filter.out=akka.stream.impl.fusing.ActorGraphInterpreter$BoundaryPublisher@173b2fd5, Map.out=akka.stream.impl.fusing.ActorGraphInterpreter$BoundaryPublisher@125d03a7}
+++ Port assigned (in) -1 for Map.in with publisher
+++ currentLayout.upstreams: Map(Map.in -> EmptySource.out)
resolving module [35434a23] computation Atomic(akka.stream.impl.StreamLayout$CopiedModule[3ba48c4a])
  matValSrc = {}
  matVals =
    3ba48c4a -> List()
    51a18594 -> NotUsed
  Atomic(akka.stream.impl.StreamLayout$CopiedModule[3ba48c4a])
  result = List()
exiting module [35434a23]
```

**Comment by bantonsson** [comment]
The underlying issue was that `viaMat` on an identity flow (`Flow[T].via(...)`) clobbered the upstreams and downstreams of the flow that you passed in, so that we couldn't hook up the pieces to each other.
