### ISSUE TITLE
take misbehaves at ByteIterator

### ISSUE THREAD

**Issue by Yeitijem** [akka/akka#22597]
bi == bi.take(2) results in true

**Comment by ktoso** [comment]
that depends on what `bi` is ;-)

Full reproducer please?

**Comment by Yeitijem** [comment]
bi is iterator from ByteString.

e.g.
val bi = ByteString(Array[Byte](3,6,7,8,9,0)).iterator

**Comment by johanandren** [comment]
This is according to the api of `Iterator` which is mutable, so when you call `take(2)` you mutate it and it is not safe to use the original iterator reference. See the scaldocs here:
http://www.scala-lang.org/api/current/scala/collection/Iterator.html#take(n:Int):Iterator[A]
