### ISSUE TITLE
[Docs] Ambiguous explanation of Distributed Data vs. Persistence Mode

### ISSUE THREAD

**Issue by markusjura** [akka/akka#22600]
The documentation page http://doc.akka.io/docs/akka/2.5/scala/cluster-sharding.html#Distributed_Data_vs__Persistence_Mode describes the differences of using Distributed Data vs. Persistence mode in Akka Cluster Sharding. The following text in the section is ambiguous:

> The state of the coordinator and the state of Remembering Entities of the shards are persistent (durable) to survive failures. Distributed Data or Persistence can be used for the storage. Distributed Data is used by default.

The state of the coordinator is not durable in ddata mode.

> The state of the ShardCoordinator will be replicated inside a cluster by the Distributed Data module with WriteMajority/ReadMajority consistency. The state of the coordinator is not durable, it's not stored to disk. When all nodes in the cluster have been stopped the state is lost and not needed any more.

> The state of Remembering Entities is also durable, i.e. it is stored to disk. The stored entities are started also after a complete cluster restart.

The "also" is misleading here. Only the state of the Remembering Entities is durable in ddata mode.

**Comment by helena** [comment]
Thanks @markusjura. Several have noted this. Will bump it up in priority.

**Comment by helena** [comment]
This issue needs to include an explanation for when running on K8 - that is what most of the questions are around.

**Comment by patriknw** [comment]
I think the documentation of this has been improved
