### ISSUE TITLE
How to controll the speed of replaying logs in recovering? ][akka-persistent]

### ISSUE THREAD

**Issue by lwsbox** [akka/akka#22601]
logs  in mailbox may hold-up too much memory in mailbox
Thanks.

![Uploading 111.png…]()

**Comment by patriknw** [comment]
There is no flow control of that part. The journal will read as quickly as it can from the db and send that to the persistent actor. It assumes that processing the events in the actor is quick (much quicker than reading from the db and deserializing). What do you do in receiveRecovery?

That said, I don't think it would be too complicated to add some flow control to the journal protocol, but so far we have not seen the need for it.

**Comment by raboof** [comment]
You can use [akka.persistence.max-concurrent-recoveries](https://doc.akka.io/docs/akka/current/persistence.html?language=scala#recovery) to limit the number of concurrent recoveries. If you still run into memory problems even when using that, you might want to make sure to snapshot more often.

These 2 countermeasures should be sufficient for practical cases, it does not appear to be worth the extra complexity to backpressure recovery any further. Does that make sense?

Closing the issue for now, feel free to reopen if necessary.
