### ISSUE TITLE
short path for Source.fromFuture and fromFutureSource

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#22602]
Could go with a short path when the `future` is complete.

**Comment by johanandren** [comment]
I don't think this is needed, I think the stages already handles when the future already is completed so it duplicates that code.

**Comment by hepin1989** [comment]
The stage don't could move the code to the FutureStage and FlattenFutureStage.

**Comment by johanandren** [comment]
Weird I could have sworn that `onFutureSourceCompleted` was called if the future was already completed in `FutureFlattenSource` preStart but I'm obviously wrong. I think the optimization should go in the stages, yes.

**Comment by hepin1989** [comment]
@johanandren I have updated the PR,PTAL
