### ISSUE TITLE
Incorrect symbols in akka-doc

### ISSUE THREAD

**Issue by lashchenko** [akka/akka#22611]
- `naïve` on [java cluster usage](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/cluster-usage.rst), [scala cluster usage](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/cluster-usage.rst) and [scala stream graphs](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/stream/stream-graphs.rst) pages.
- `façade` on [scala typed](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/typed.rst) page.

**Comment by ktoso** [comment]
What do you mean? That's "overly correct" even :)

**Comment by ktoso** [comment]
- A façade (/fəˈsɑːd/)[1] is generally one exterior side of a building, usually, but not always, the front. It is a foreign loan word from the French façade, which means "frontage" or "face". https://en.wikipedia.org/wiki/Facade
- Naivety (or naïvety or naïveté) is the state of being naïve, that is to say, having or showing a lack of experience, understanding or sophistication, often in a context where one neglects pragmatism in favor of moral idealism. One who is "naïve" may be called a naïf. https://en.wikipedia.org/wiki/Naivety

**Comment by lashchenko** [comment]
@ktoso could you please clarify why [scala-stream-graphs](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/stream/stream-graphs.rst) contains `naïve` (umlaut), but [java-stream-graphs](https://github.com/akka/akka/blob/master/akka-docs/rst/java/stream/stream-graphs.rst) contains `naive` (not umlaut)?

**Comment by ktoso** [comment]
That's an  then, do you want to submit a PR to fix it? Thanks in advance :-)

**Comment by ktoso** [comment]
Thanks :-)
