### ISSUE TITLE
The `chatroom-gabbler`'s related document is not up to date

### ISSUE THREAD

**Issue by floating-cat** [akka/akka#22610]
1. `Total` case class was replaced by `Stateful` [here](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/code/docs/akka/typed/IntroSpec.scala#L100), but the related [document](https://github.com/akka/akka/blame/f485be2bf5c38d78f59108c0d6086675d337d48f/akka-docs/rst/scala/typed.rst#L223-L231) is not updated.
 > This is why this Actor uses a different behavior constructor named :class:`Total`.
> The behavior is named “total” (as opposed to “partial”) because the declared function must handle all values of its input type function must handle all values of its input type.

2.
> Since :class:`SessionEvent` is a sealed trait the Scala compiler will warn us if we forget to handle one of the subtypes; in this case it reminded us that alternatively to :class:`SessionGranted` we may also receive a :class:`SessionDenied` event.

The current [example](https://github.com/akka/akka/blob/master/akka-docs/rst/scala/code/docs/akka/typed/IntroSpec.scala#L102) has already included the `SessionGranted` subtypes in the pattern match, so the last part of this sentence is incorrect. It may better remove this whole sentence or remove the last part of this sentence.

Thanks.

**Comment by ktoso** [comment]
We are currently in the middle of redesigning many of those classes, while we do this things may not be fully consistent on the `master` branch - thanks for your patience. They will be made consistent once 2.5 ships.

cc @rkuhn
