### ISSUE TITLE
Investigate on 2.4: GraphInterpreter leak when a submaterialized flow throws during materialization 

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22646]
The issue #22358 is fixed on 2.5 however it may manifest on 2.4.
See details: *GraphInterpreter leak when a submaterialized flow throws during materialization #22358*

**Comment by johanandren** [comment]
Can repeat failure with Source.lazy on 2.4, although, now I'm not so sure anymore that it has anything to do with the submaterializer but rather belongs in the error handling of the stage using it.
