### ISSUE TITLE
Fix docs redirects oldDocs.js

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22659]
This will require some manual preparation work, as the simple "replace with new number" does not work since:

http://doc.akka.io/docs/akka/2.4.9/scala/http/client-side/request-level.html

should redirect to 

http://doc.akka.io/docs/akka-http/current/scala/http/client-side/request-level.html

**Comment by ktoso** [comment]
Putting it here since it means we have to touch old akka/akka deployed docs.

**Comment by ktoso** [comment]
See also https://github.com/akka/akka-http/issues/809

**Comment by jonas** [comment]
Looking into this.

The fix would be to update `akka-docs/_sphinx/themes/akka/static/warnOldDocs.js` to match `/http/` in the path and redirect.

**Comment by jonas** [comment]
Alternatively we can just patch the 2.4.9 version of that file and live happily ever after.

**Comment by jonas** [comment]
Updated version of `warnOldDocs.js` for 2.4.9 can be found [here](https://gist.githubusercontent.com/jonas/ca8cc328be5bc2d67f686051a1c8d28f/raw/9f096a7c327ac25f2d0004ec63acea22f32605bd/warnOldDocs.js) ([diff](https://gist.githubusercontent.com/jonas/ca8cc328be5bc2d67f686051a1c8d28f/raw/9f096a7c327ac25f2d0004ec63acea22f32605bd/warnOldDocs.js.2.4.9.patch))

<img width="620" alt="screen shot 2017-03-31 at 11 26 38 am" src="https://cloud.githubusercontent.com/assets/8417/24557219/f2cbc50a-1604-11e7-82f0-8f14ed3bb5ef.png">

**Comment by ktoso** [comment]
Oh, interesting - looking into it!

**Comment by ktoso** [comment]
Oh pretty neat, I guess we should do just that then as first step.
Please submit a PR and I'll take care of getting that script into all old versions of the docs.

**Comment by jonas** [comment]
Should I make the PR against the akka version after the HTTP code was removed, assuming this is not something we want to merge?

**Comment by ktoso** [comment]
I think this was addressed
