### ISSUE TITLE
Make Deferred compose better

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22658]
Currently Deferred can only be used as the outermost Behavior as it expects a PreStart as the first message. Roland mentions in akka/akka-meta#46 that it should be fixable.

**Comment by patriknw** [comment]
Possibly related: #20205

**Comment by patriknw** [comment]
Possibly related: #22661

**Comment by rkuhn** [comment]
Fixing this is implicit to the removal of the PreStart signal, there is no fundamental reason for the assertion that currently makes composition harder than it should be.

**Comment by johanandren** [comment]
@rkuhn Yes, maybe the name of the ticket is somewhat misleading, but that's the end result we want to end up with and I wasn't entirely sure what needed to be done to get there. I will start with the "interpreter" ticket and see if removing PreStart follows naturally in the work there.
