### ISSUE TITLE
use PartialFunction for signals

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22662]
See discussion in https://github.com/akka/akka-meta/issues/46

Also, see if we can improve the syntax for the two parameters in `Stateful`, Signal trait should not be sealed

**Comment by rkuhn** [comment]
Just for rationale: the reason why Unhandled exists is primarily to support DeathPactException when a Terminated is not handled—which I find very valuable to have. Perhaps this rationale should be documented.

(Anecdote: previously Unhandled also was needed to support the Or combinator, but that was a failed experiment as far as I can see, to be superseded by a process DSL for actors.)

**Comment by patriknw** [comment]
Just for clarification: unhanded `Terminated` shall still result in `DeathPactException`
