### ISSUE TITLE
Rename DeploymentConfig to Props

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22660]
see discussion in https://github.com/akka/akka-meta/issues/46

**Comment by johanandren** [comment]
I also have my doubts on whether it should be a linked list, to make bincomp easier?

**Comment by patriknw** [comment]
Other modules (e.g. akka-cluster) should be able to define other settings, so it must be "open", but for some of the most common we must probably optimize it (e.g. by caching the access to dispatcher)

**Comment by johanandren** [comment]
Ok. I think we should hide the fact that is is a hierarchy/list as much as possible in the user APIs though, `Props()` or `Props.empty` over `EmptyProps` in user code/APIs for example.

**Comment by patriknw** [comment]
I agree, we don't want to do the same as with stream attributes
