### ISSUE TITLE
hide message and management methods in Behavior

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22661]
See discussion in https://github.com/akka/akka-meta/issues/46

`sealed abstract class Behavior` that does not have message handling methods, plus a non-final abstract class `ExtensibleBehavior` extends Behavior that is the current Behavior. Then we formalize the small helper methods at the bottom of Behavior.scala into a tiny stateless static interpreter that executes each behavior as appropriate, where ExtensibleBehavior just gets its methods invoked (and the results canonicalized) to allow efficient custom behaviors.

**Comment by johanandren** [comment]
I will also throw out ScalaDSL here, there is just too much work to keep the old API.

**Comment by johanandren** [comment]
Just one test failing now, WIP pushed in this branch but not ready for PR yet: https://github.com/johanandren/akka/tree/wip-22661-make-typed-more-interpreted-johanandren
