### ISSUE TITLE
properly shutdown ArteryTransport using CoordinatedShutdown

### ISSUE THREAD

**Issue by sirocchj** [akka/akka#22671]
In http://doc.akka.io/docs/akka/2.5.0-RC2/scala/actors.html#Coordinated_Shutdown it is mentioned that you should registered JVM shutdown hooks so that they are performed before akka’s internal ones. Artery is mentioned explicitly but it would probably be useful to add a snippet showing what/how to avoid
```
Exception in thread "Thread-0" java.util.concurrent.TimeoutException: Futures timed out after [23000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:123)
	at akka.remote.artery.ArteryTransport$$anon$1.run(ArteryTransport.scala:470)
```

**Comment by patriknw** [comment]
Then the question is what you did to get that exception. Something is blocking the shutdown of Artery. This is after waiting for other jvm hooks. Do you have any more logs or a reproducer?

**Comment by sirocchj** [comment]
Sorry @patriknw I should have mentioned that: SIGTERM/INT when using artery in remote/cluster (leaving `run-by-jvm-shutdown-hook=on` as per default).

I guess what I am looking for is the correct way one is expected to shutdown the artery transport if you want to avail of coordinated shutdown.

`org.agrona.concurrent.SigInt.register(new Runnable { override def run(): Unit = cluster.leave(cluster.selfAddress) })`

seems to do the trick for me but... is this the right way? Is there another way? I feel that part of the documentation would benefit for some further clarification :)

**Comment by patriknw** [comment]
The intention is that Coordinated Shutdown should perform the leaving for you. You should not have to register anything for that to work. `org.agrona.concurrent.SigInt` should not be needed.

Note that `SIGINT ctrl-c doesn't work`, you have to use `kill SIGTERM`.

**Comment by sirocchj** [comment]
Thanks for clarifying! Um, then there's something not working for me... Here's the minimised project that exposes the issue https://gist.github.com/sirocchj/eca106585d8f2135982bb92660f9ccdc

**Comment by patriknw** [comment]
Thanks for an excellent reproducer. I can confirm that I see the same problem. I'm investigating.

**Comment by patriknw** [comment]
@sirocchj It was a bug, thanks for reporting.

**Comment by sirocchj** [comment]
@patriknw glad you found it! :)
