### ISSUE TITLE
Incorrect supervisor strategy in withSupervisorStrategy signature

### ISSUE THREAD

**Issue by haggy** [akka/akka#22688]
I caught this while trying to use the `BackoffSupervisor`:
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/pattern/BackoffOptions.scala#L171
```scala
/**
   * Returns a new BackoffOptions with the supervisorStrategy.
   * @param supervisorStrategy the supervisorStrategy that the back-off supervisor will use.
   *   The default supervisor strategy is used as fallback if the specified supervisorStrategy (its decider)
   *   does not explicitly handle an exception.
   */
  def withSupervisorStrategy(supervisorStrategy: OneForOneStrategy): BackoffOptions
```

The above method does not allow you to specify the `AllForOneStrategy` since it's explicitly accepting only `OneForOneStrategy`. Unless Im missing something, I believe that method should be:

```scala
def withSupervisorStrategy(supervisorStrategy: SupervisorStrategy): BackoffOptions
```

**Comment by haggy** [comment]
Oh upon looking at the `BackoffOptionsImpl` class, it is explicitly accepting only `OneForOneStrategy` there as well. Is this intentional?

**Comment by patriknw** [comment]
That is intentional as far as I can see. Backoff supervision is not ordinary parental supervision. It's a separate actor that handles the backoff process when a specific child fails. It, can't influence siblings (children one level up from the backoff actor).

**Comment by ktoso** [comment]
Sounds intentional to me as well, closing for now.
