### ISSUE TITLE
Do we want to support serialize-messages = on + allow-java-serialization = off

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22680]
Users may set the setting `serialize-messages = on` together with `allow-java-serialization = off`.
Which addmitably is a bit weird, but causes internal Akka messages to show up in serialization errors.

Is this something we should either:
- **document as not supported idea**, since internal tests pass messages and thus "serialize all" also means those that never cross actual remote boundary, so the checks fail in this combination of settings.
- **actually detect this setting combination** and silence the failures? I think this would lead to a lot of complication when we actually disable the serializers etc so I'm not in favour of this solution.

WDYT @patriknw

**Comment by ivanopagano** [comment]
If I may add to the discussion, the docs seemed to imply that any internal message not expected to cross the vm boundaries have a marker trait to identify them and preventing warning by setting

`warn-on-no-serialization-verification = off`

So I would expect that this takes care of all internal messages when I turn on the serialize-message switch.

The idea here behind this specific switch combination is that java ser is inherently unsafe in many ways in production code, so turning them off is pretty expected at some point.  
Also if I need to check on my integration or unit tests that my custom messages have a properly configured serializer, I expected to just force serialization locally as a mean to catch any rogue message type.

This is what led to exposing the internal akka messaging. I'm interested to know if my line of reasoning is somewhat missing the point or making wrong assumption, so any comment is gladly welcome.

**Comment by patriknw** [comment]
Improvement in progress: https://github.com/akka/akka/pull/22682

**Comment by wsargent** [comment]
I just did this so I could demo an akka cluster with several nodes inside a single JVM using protobuf.  It exploded.

**Comment by johanandren** [comment]
For reference I did add something tangential recently, a test-serializer `akka.testkit.TestMessageSerializer` to selectively enable Java serialization for example for messages only used in tests when Java serialization is disabled for the actor system.

**Comment by raboof** [comment]
@wsargent to be able to demo an Akka cluster with several nodes (even inside a single JVM) you shouldn't need to set `serialize-messages = on` though - the messages travelling over remoting will be serialized regardless.

**Comment by wsargent** [comment]
Works!  https://github.com/playframework/play-scala-secure-session-example/tree/SNAPSHOT
