### ISSUE TITLE
Unable to send negative acknowledgement upon LoadSnapshotFailed

### ISSUE THREAD

**Issue by Sukesh-Alluri** [akka/akka#22689]
Hi, I'm using akka-persistence 2.5.16 version and ran into this issue of unable to send a negative ack back to the original sender of the message to PersistentActor in the overridden onRecoveryFailure method where sender has a reference to SnapshotStore actor rather than to the actor which originally sent the message to the PersistentActor.

Is there no way we can do this or am I mis reading something here, please advise.

**Comment by raboof** [comment]
Hello Sukesh, thanks for your question!

Indeed during recovery you don't have access to the original sender, as that party could be long gone by then: remember persistent actors are often used for long-running processes, and recovery is intended to build up the state based on all past events.

In general I would consider it a bug when recovery can fail, and essentially I'd say the only place this can be solved is by fixing the code.

Does that make sense in your situation? If not, could you elaborate on what your actor looks like?

**Comment by raboof** [comment]
(closing as this likely isn't really an issue with akka, just a question)

**Comment by Sukesh-Alluri** [comment]
@raboof thanks for the confirmation. We'll try take another route to handle these failures for now as we too don't expect rehydration to fail ever, but seems due to side effects in the rehydration process, we do see these issues occasionally.

**Comment by raboof** [comment]
Sounds good, good luck!

In general it's best to try and avoid side effects inside the event handling. If anything you might want to collect a list of 'planned' side effects during recovery and then perform them after recovery has completed. This is also how `AtLeastOnceDelivery` works.
