### ISSUE TITLE
Failed: DriverTimeoutException: CnC file not found: cnc.dat

### ISSUE THREAD

**Issue by 2m** [akka/akka#22693]
Looks like started after https://github.com/akka/akka/pull/22690

https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/561/consoleFull

**Comment by patriknw** [comment]
ok, I guess this is the same as reported by @guidomedina 

@2m please revert the version change until we have investigated this

**Comment by 2m** [comment]
Created https://github.com/akka/akka/pull/22694
