### ISSUE TITLE
Docs for Sink.last(Option) are wrong about failure

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#22691]
The docs for `Sink.lastOption` and `Sink.last` indicate that if at least a single element was processed this will be used for the mat value, even in case of failure. That doesn't reflect reality (code): in the case of failure, the mat value is a `Failure`.

**Comment by raboof** [comment]
The question is what do we *want* the reality to be... though it might be a bit too late to change semantics now, so probably lowest-friction to just update the docs indeed.

**Comment by patriknw** [comment]
An upstream failure can always overtake ordinary elements (elements may be "stuck" because of no demand from downstreams). 

If a single element is processed by the sink, that will be the materialized value.

Anyway, sounds like some kind of clarification of docs is needed.

**Comment by hseeberger** [comment]
@patriknw what you write is what the docs tell. But that's not true: even if a single element has been processed by the sink and then a failure occurs, the materialized value will be that failure. Regardless of the "speed" of the failure signal. I have a "test case" for that below, but a quick look at `LastOptionStage` and its `onUpstreamFailure` implementation should suffice.

``` scala
import akka.actor.ActorSystem
import akka.stream.QueueOfferResult.Enqueued
import akka.stream.scaladsl.{ Keep, Sink, Source }
import akka.stream.{ ActorMaterializer, OverflowStrategy }
import scala.util.{ Failure, Success }

object Main {

  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem()
    implicit val mat    = ActorMaterializer()

    import system.dispatcher

    val ((queue, head), last) =
      Source
        .queue[Int](42, OverflowStrategy.fail)
        .map(42 / _)
        .alsoToMat(Sink.head)(Keep.both)
        .toMat(Sink.lastOption)(Keep.both)
        .run()

    val l =
      for {
        r1 <- queue.offer(1) if r1 == Enqueued
        h  <- head if h == 42 // should make sure that Sink.lastOption has processed an element before moving on
        r2 <- queue.offer(0) if r2 == Enqueued // 0 leads to failure
        _ = queue.complete()
        l <- last
      } yield l

    l.andThen {
        case Success(x) => println(x)
        case Failure(c) => println(s"Failure: $c")
      }
      .andThen { case _ => system.terminate() }
  }
}
```

**Comment by hseeberger** [comment]
Ah, and of course I want the sink to behave like written in the docs, i.e. recover from failure if an element has been processed.

**Comment by patriknw** [comment]
Sorry, I was thinking of Sink.head when I wrote that.

Shouldn't the recover behaviour be with a separate recover stage in front of the Sink.last, if that is the desired behaviour?

**Comment by hseeberger** [comment]
I agree, that will make (leave) last and lastOption more consistent.

**Comment by patriknw** [comment]
so what was the conclusion? the documentation should be updated to match current implementation (and perhaps add a comment that a recover stage can be used in front)? can you PR that, @hseeberger?

**Comment by hseeberger** [comment]
@patriknw yes i can ;-)

**Comment by hseeberger** [comment]
@patriknw here you are: #22796
