### ISSUE TITLE
Agent send with implicit executioncontext fails with nullpointer

### ISSUE THREAD

**Issue by awouda** [akka/akka#22700]
When having an implicit ec enabled in the code below, I get a NPE in the SerializedSuspendableExecution context. I think this should not happen. Using the commented global execution context, the behaviour is as expected. 

Akka v 2.4.16
Scala 2.12.1
```
import akka.actor.Actor
import akka.agent.Agent

import scala.concurrent.ExecutionContext

trait StorageCount {

  implicit val ec: ExecutionContext
  //  import scala.concurrent.ExecutionContext.Implicits.global
  val agent = Agent(0)
}
class ShipmentActor extends Actor with StorageCount {

  implicit val ec = context.dispatcher

  override def receive: Receive = {
    case s: String ⇒
      val value = agent()
      println(s"storage in agent is now ${value}")
      agent send scala.util.Random.nextInt(100)
  }
}
```

**Comment by johanandren** [comment]
It is because of initialization order, when the agent is contstructed `ec` is still `null`/not initialized yet, and that is passed to the Agent. Change `ec` to be a `def` and it will work.

**Comment by awouda** [comment]
Ah, ok I see, stupid; already fell into that earlier....

I'll make it lazy val, or it keeps resetting the Agent to 0.

**Comment by johanandren** [comment]
Note that the Agents will be deprecated in Akka 2.5 which will be released really really soon.
