### ISSUE TITLE
Akka Typed:EffectfulActorContext ability to poll an effect with a max timeout

### ISSUE THREAD

**Issue by stanislav-chetvertkov** [akka/akka#22714]
when I using `EffectfulActorContext` for testing, sometimes I wan't to poll an Effect that is eventually available with some delay, for example

```
val testBehavior = ContextAware { ctx =>
        Static {
          case Message =>
            Future {
                // some code
                ctx.schedule(delay, ctx.self, Message)
            }
        }
      }
```

if I call

```
val effect = context.getEffect()
```

effect won't be instantly available and NoSuchElementException will be thrown, so I have to call `Thread.sleep(100)` in my test and only then the effect becomes available

**solution**

use LinkedBlockingQueue
`private val effectQueue = new LinkedBlockingQueue[Effect]`
and add `def pollEffect(): Effect = effectQueue.poll(timeout.toMillis, TimeUnit.MILLISECONDS)` to get an effect with maximal delay specified (timeout can be an implicit parameter)

**Comment by stanislav-chetvertkov** [comment]
:t typed

**Comment by johanandren** [comment]
We are currently reworking the APIs, the entire `ScalaDSL` and `ContextAware` is going away I'm afraid. I'm don't immediately see if this is still relevant with the new API, but I'm pretty sure we will end up having tools to do assertions like the current actor testkit on eventual changes (`awaitAssert` and such).

Note that you cannot safely close over the `ctx` and access/use it in a different thread (the `Future`) like in the sample you provided.

**Comment by stanislav-chetvertkov** [comment]
@johanandren I see... its just there is not much documentation available on it, I guess I need to start collaborating because I really like the Idea of having typed API. So is `EffectfulActorContext` also going away?
Could you point me to where the discussion of the new API is happening?

**Comment by johanandren** [comment]
Not sure what will happen with `EffectfulActorContext` you can see a few discussions in akka-meta , most of those has already landed at conclusions though and we in the core team are working on such tickets, which you can find under the akka-typed tag and pick next/in progress in the akka issue tracker.

**Comment by patriknw** [comment]
I don't think we should add such things to `EffectfulActorContext`. It's intended for synchronous testing. For asynchronous, "real", testing we should have another testkit similar to the classic actor testkit, see https://github.com/akka/akka/issues/22764
