### ISSUE TITLE
Downloadable docs for Akka 2.5.0

### ISSUE THREAD

**Issue by Kapeli** [akka/akka#22728]
Before Akka 2.5.0 the standalone versions included a `doc` folder (e.g. inside [akka_2.12-2.4.17.zip](http://downloads.typesafe.com/akka/akka_2.12-2.4.17.zip)). Starting with Akka 2.5.0 there's no longer an archive to download so the docs are no longer available. Could they be added back?

**Comment by ktoso** [comment]
Hi Kapeli, I understand those make supporting Akka in Dash much simpler. 
I think we should look into it then, will discuss with the team once they wake up :-)

**Comment by ktoso** [comment]
cc @patriknw @2m something we should check btw.

**Comment by patriknw** [comment]
We will not bring back the full distribution zip, but we can maybe publish a zip of the docs.
The [EPUB](http://doc.akka.io/docs/akka/2.5/Akka.epub) is pretty much that, without styling. I don't know if that could be useful for you?

**Comment by Kapeli** [comment]
@patriknw Unfortunately not. A zip of the docs would be great.

**Comment by ktoso** [comment]
Ah I see, it's dropped because the distribution zip - yeah that did not make sense.
Bringing back just a zip with the docs sounds ok to me.

**Comment by Kapeli** [comment]
An alternative would be to set up a repo like https://github.com/playframework/play-generated-docs/releases and publish the docs there.

**Comment by wachag** [comment]
Unfortunately the EPUB link is broken. Is there a documented way to generate one from the sources?

**Comment by 2m** [comment]
Currently the documentation tool that we use ([Paradox](https://github.com/lightbend/paradox)) does not support EPUB generation. There are talks about having [support for it](https://github.com/lightbend/paradox/issues/98) and we could really use some help from anyone that might be willing to make it happen.

**Comment by Kapeli** [comment]
Any chance downloadable API docs will be available anytime soon? As far as I can tell all that is required is archiving the folders at https://doc.akka.io/api/akka/ and making the archives available somewhere?

**Comment by raboof** [comment]
@Kapeli would you be interested in taking a look? `project/scripts/release` and `project/Release.scala` should be good starting points.

**Comment by Kapeli** [comment]
Made a (probably bad) attempt at this in https://github.com/akka/akka/pull/24211.

Thanks for pointing me in the right direction. I'm able to generate the docs for my own needs now.

**Comment by patriknw** [comment]
I suggest that we bring back the zip from 2.4 https://github.com/akka/akka/blob/release-2.4/project/Dist.scala#L112 and upload that to doc.akka.io alongside the html pages. Help welcome.

**Comment by patriknw** [comment]
for the record, we had another request for this

**Comment by sitepodmatt** [comment]
It's relatively easy to do already.

sudo apt-get -y install httrack
mkdir ~/akkadocs
cd ~/akkadocs
httrack https://doc.akka.io/docs/akka/2.5.4/java/guide/index.html +https://doc.akka.io/docs/akka/2.5.4/java/*
xdg-open index.html
# voila

(replace java with scala for scala version)

**Comment by NightMachinary** [comment]
Epub is readable on e-readers which is way easier on the eyes than an iPad. It’d be good if it was offered.

**Comment by raboof** [comment]
If anyone wants to move this forward https://github.com/lightbend/paradox/issues/310 might be a good starting point for packaging up the reference docs. The API docs would need something separate/similar.

**Comment by raboof** [comment]
> Epub is readable on e-readers which is way easier on the eyes than an iPad. It’d be good if it was offered.

I see you already found https://github.com/lightbend/paradox/issues/98 ;)

**Comment by xieyuheng** [comment]
I really need this tonight.
I just `httrack`ed one: https://github.com/xieyuheng/akka-docs-offline

PRs are welcome, for examples:
- updating scripts
- clear git history
- separate zip for akka and akka-http

**Comment by raboof** [comment]
Thanks for the initiative! I'd still love it if someone could help make this part of our build, but for now this seems very helpful!

**Comment by Captain1653** [comment]
The issue has the long story :) . Is it still needed? I can try to do it if you point the direction.

**Comment by patriknw** [comment]
Let's close this. I'm not sure the published html docs can be used as is for local consumption. Cookies and gdpr approval and such?
