### ISSUE TITLE
Some serializers don't throw recommended exception in fromBinary

### ISSUE THREAD

**Issue by naferx** [akka/akka#22720]
According to the docs:

> It's recommended to throw java.io.NotSerializableException in fromBinary if the manifest is unknown. This makes it possible to introduce new message types and send them to nodes that don't know about them...

Does it apply only for implementations of SerializerWithStringManifest ?

**Comment by naferx** [comment]
https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/serialization/ArteryMessageSerializer.scala#L94

**Comment by patriknw** [comment]
Artery doesn't have same problem at all as the classic remoting with exceptions from deserialization. Artery will catch all exceptions, drop the message, and keep the connection alive.

**Comment by patriknw** [comment]
but we can change it to `java.io.NotSerializableException` to be consistent with other implementations.
Could you create a PR for that @naferx ?

**Comment by naferx** [comment]
Thanks for the previous info.

Absolutely !. In addition to that,  I'll adjust the following examples of serializers: 
-  `SimplestPossiblePersonSerializer` 
 - `AddedFieldsSerializerWithProtobuf`

**Comment by patriknw** [comment]
thanks
