### ISSUE TITLE
[Docs] example in docs persists one event, while in text two events are mentioned

### ISSUE THREAD

**Issue by bassmake** [akka/akka#22726]
in docs:
```
  val receiveCommand: Receive = {
    case Cmd(data) =>
      persist(Evt(s"${data}-${numEvents}")) { event =>
        updateState(event)
        context.system.eventStream.publish(event)
        if (lastSequenceNr % snapShotInterval == 0 && lastSequenceNr != 0)
          saveSnapshot(state)
      }
    case "print" => println(state)
  }
```
and also `a command is handled by generating two events`, which is not true.

The code snippet should probably look like 
```
    case Cmd(data) =>
      persist(Evt(s"${data}-${numEvents}"))(updateState)
      persist(Evt(s"${data}-${numEvents + 1}")) { event =>
        updateState(event)
        context.system.eventStream.publish(event)
      }
```
which can be seen in downloaded `akka-samples-persistence-scala`

**Comment by patriknw** [comment]
I think we changed that example at some point snd decided that we should keep it simple with only one event. Seems like the text should be updated.

**Comment by richard-imaoka** [comment]
Sorry that was my oversight. I simplified the example in #22419, but I did not update the text.

Let me fix that.

**Comment by ktoso** [comment]
Typo fixed by @richard-imaoka , thanks
