### ISSUE TITLE
Missing ResourceFlatMapConcat stage

### ISSUE THREAD

**Issue by filosganga** [akka/akka#22730]
Hi,
I need to apply a transformation to a `Flow[I,O]` that involves opening a resource and release it when the stream is closed. Something similar to fs2 `bracket`:

At the moment I cannot find any way to do that without implementing a custom `GraphStage`.

Would be very good to have a stage that can be used like this:
```scala
Flow[T].resourceFlatMapConcat(
  () => new Resource /* Acquire the resource */, 
  resource => t => /* Use resource and current element */ Source.single(int),
  _.release() /* Release the resource*/)
```

I am not sure if the acquire and release resource should be asynchronous. 

On top of this stage I guess will be possible to define `resourceMap` and `resourceMapAsync`. I am not sure if a `resourceFlatMapMerge` stage will make any sense.

Is there any way to implement it at the moment? The only similar stage I have seen is the `resourceUnfold`. You can use in this way:

```scala
Flow[T].flatMapConcat { t =>
   Source.resourceUnfold(...)
}
```

But as far as I have understood, in this case the resource is created and released for each element of the flow, while I want it to be created when the Flow is materialized and released when it completes (successfully or not).

Another alternative seems using the `statefulMapConcat` where you can acuire the resource at materialization time, but there is no callback to release it.

I am happy to contribute if this stage makes any sense.

**Comment by ktoso** [comment]
Isn't that just: 

```scala
      val typed: Source[String, NotUsed] =
        Source.unfoldResource[Source[String, NotUsed], BufferedReader](
          () ⇒ new BufferedReader(new FileReader("")),
          reader ⇒ Some(Source.single(reader.readLine)),
          reader ⇒ reader.close()
        ).flatMapConcat(identity)
```

?

**Comment by filosganga** [comment]
@ktoso It is Source. I need a transformation stage, a `Flow[A, B, _]` that uses a resource. Unless I am missing something, I cannot use `Source.unfoldResource` for that.

**Comment by weihsiu** [comment]
what i end up doing for case like yours is to zip a Source.unfoldResourceAsync() with my existing flow.  that way, the resource i opened in unfoldResourceAsync() can be used in my flow.  the only problem i've experienced with such approach is the timing when the resource is closed: the resource gets closed before my flow is done with it.

i think we need something to manage the resources better and is easier to deal with than writing our own GraphStage.

**Comment by hepin1989** [comment]
@weihsiu @filosganga Hi ,I have updated with a PR to take a try, would you like to give some input? thanks

**Comment by patriknw** [comment]
@He-Pin Did the PR https://github.com/akka/akka/pull/31330 solve this issue as well?

**Comment by johanandren** [comment]
I think #31330 only prepared for creating a factory like this (composed through statefulMapConcat with pre-set io-dispatcher)

**Comment by He-Pin** [comment]
I will continue it with https://github.com/akka/akka/issues/31355
