### ISSUE TITLE
Should we put same() on Behaviour?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22736]
A random thought while working with typed:

```
return Actor.stateful((ctx, command) -> { return Actor.same(); });
```

Since our wording here is "we return the same behaviour" users are lead to look in Behaviour for a "the same", we we only have it on Actor nowadays. Which seems a bit weird "the same actor? I mean the same behaviour!".

WDYT about exposing Same() / same() on Behavior, given the above line of thinking?

cc @rkuhn

**Comment by ktoso** [comment]
Note that I just came back from a week offline and this surprised me.
Perhaps it's fine since we tell people about Actor being all the things they need hmm...

Wanted to make note of it anyway since suprised me.

**Comment by rkuhn** [comment]
We can certainly make `Behavior.same()` visible to user code. On the other hand I quite like the separation of the Actor-DSL from the Behavior implementation details. A compromise would be to keep it in both places so that `import static akka.typed.javadsl.Actor.*;` still brings in everything that is needed.

**Comment by rkuhn** [comment]
(re-reading: that is probably what you proposed as well, i.e. no real compromise)

**Comment by hepin1989** [comment]
I would more like `Behaviour.SAME`

**Comment by ktoso** [comment]
Yes it would be in the two places I think.
It has to be a method, so "javadsl": `Behavior.same()` and "scaladsl" `Behavior.Same`

**Comment by rkuhn** [comment]
To be consistent, that should then apply to unhandled and stopped as well, I think.

**Comment by ktoso** [comment]
Yes, absolutely.

To think a bit more about the "Actor.same() + Behavior.same()" vs. "move to Behavior.same()", are we sure having it on Actor _as well_ is helpful? I see that having all those in Actor allows `import static Actor.*` which is nice, but having things in two places is a bit iffy hm... I guess one could say Actor is the "DSL", so yeah it has copies of Behavior methods since it's more convienient to do so.

I'm ok with either, as long as Behavior gets those :)

**Comment by patriknw** [comment]
Pretty much everything in `Actor` is about creating/getting the behaviors so they should absolutely be there. I don't mind having `Same`, `Unhandled` and `Stopped` duplicated in `Behavior` also.

**Comment by ktoso** [comment]
Summing up:
- Keep on Actor
- Expose on Behavior too

Sounds very good, I'll PR that later in some free time :)

**Comment by hepin1989** [comment]
Make the `Actor.Same` return `Behavior ,Same`:)

**Comment by ktoso** [comment]
This causes some collateral renames, but the change will be good I think.
