### ISSUE TITLE
typed message matching builders for javadsl

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22748]
Similar to `AbstractActor`. I think @johanandren started something for this.

We should consider if we need the full pattern matching features or if we should only match on exact message class type, which can also be much more efficient than the partial function chaining.

**Comment by hepin1989** [comment]
I really love the VAVR one 
![image](https://cloud.githubusercontent.com/assets/501740/25181825/5d4cd9ce-2545-11e7-8b70-c9b24d147168.png)
http://www.vavr.io/vavr-docs/#_pattern_matching

**Comment by hepin1989** [comment]
![image](https://cloud.githubusercontent.com/assets/501740/25181987/d09d2a28-2545-11e7-9504-967fd78d3cab.png)

**Comment by patriknw** [comment]
@hepin1989 We have an example with classic actors using javaslang (vavr) https://github.com/akka/akka-samples/tree/master/akka-sample-javaslang

**Comment by johanandren** [comment]
The work I did is available in this branch: https://github.com/johanandren/akka/tree/play-around-with-typed-pre-2.5-rc1

Was pre team typed API discussions, but maybe parts of it can be salvaged. I think the current style of Java builders should be continued on, to make it familiar and nice for the Java devs who already used the old actor APIs.

**Comment by raboof** [comment]
Let's stick with the approach also found in `AbstractActor` for consistency in the main tree, but I agree the vavr stuff is cool - let's see if we can create a vavr sample for akka-typed as well later.

**Comment by raboof** [comment]
First sketch in https://github.com/akka/akka/compare/wip-akka-typed-dev...akka-typed-javadsl-behaviour-build
