### ISSUE TITLE
should the javadsl be implemented in java or scala?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22749]
I'm not sure I see the advantage of implementing it in java.

**Comment by hepin1989** [comment]
If it can't be implemented in Scala with friendly to Java , then in Scala, otherwise a simpler Java proxy would be great:)

**Comment by johanandren** [comment]
My vote: Scala with Java tests to verify that there are no problems accessing any part of the API.

**Comment by patriknw** [comment]
I take this one. Have some other refactoring ideas I want to try out at the same time. I probably have to wait for https://github.com/akka/akka/issues/22662
