### ISSUE TITLE
Rename akka.typed.ActorContext

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22750]
```
akka.typed.ActorContext
akka.typed.scaladsl.ActorContext
akka.typed.javadsl.ActorContext
```

It's one too many ActorContext, e.g. problem when 
```
akka.typed._
akka.typed.scaladsl._
```

**Comment by patriknw** [comment]
I don't have a good name suggestion yet

**Comment by hepin1989** [comment]
`UnitedActorContext`

for 
```
@DoNotInherit
@ApiMayChange
trait ActorContext[T] extends javadsl.ActorContext[T] with scaladsl.ActorContext[T]
```

**Comment by patriknw** [comment]
I'm not sure if this is such a big problem

**Comment by patriknw** [comment]
I suggest that we close this until we think it's actually disturbing enough or we have a good alternative name (I'm not sure I like `UnitedActorContext`, but thanks for the suggestion)
