### ISSUE TITLE
Akka cluster sharding should not create durable data files if not needed

### ISSUE THREAD

**Issue by jroper** [akka/akka#22759]
Since upgrading to Akka 2.5.0, every time I run tests, I get a whole bunch of `ddata-*` directories in the working directory (the root folder of my project).  This is in spite of the fact that I don't have remember entities turned on - the documentation I think is a bit misleading here, when I read:

> The state of Remembering Entities is also durable, i.e. it is stored to disk. The stored entities are started also after a complete cluster restart.

I assumed that that means if you don't have remembering entities turned on, that nothing would be stored to disk, but that's obviously not the case. I'm guessing if you're not using remember entities, and you don't want anything persisted to disk, that you should turn durability off.  This should probably be mentioned in the documentation.

I'd also question whether it's a good default to use the working directory for durability, since in a typical microservice deployment scenario, the working directory itself can rarely be trusted to be durable, and so default to it is potentially dangerous.  And defaulting to the working directory for tests is never a good idea because it pollutes your projects root directory.  I can't think of any situation where the working directory is a good default.  A better default, I think, would be to fail if no directory is explicitly configured.

**Comment by patriknw** [comment]
Thanks for reporting, @jroper. It was an oversight. It should not create those directories/files if remember entities are not used. I have fixed that now.

Default values can always be discussed and there will never be something that fits everyone all the time (e.g. first time user experience vs. production). Leaving that as is.
