### ISSUE TITLE
testkit for asynchronous testing

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22764]
EffectfulActorContext / StubbedActorContext is great for unit testing of behaviors, but for more real integration style testing, e.g. real interactions between actors (e.g. children) we should provide something similar to the classic actor testkit.

**Comment by patriknw** [comment]
I have added a subset of scaladsl testkit in https://github.com/akka/akka/pull/22765 (40fa079071afb40371e5e73330954dec2e49d959). This ticket is now about completing the remaining parts of scaladsl and javadsl.

We should be selective when porting the classic testkit and leave out things that we don't think are useful (e.g. auto pilot, only probe style).

**Comment by chbatey** [comment]
I'll do a pass over this when doing the sync stuff

**Comment by patriknw** [comment]
@chbatey What is remaining here? Is it possible to create additional tickets so that this can be closed?

**Comment by chbatey** [comment]
I'll take a look through the untyped one and see what's missing that we want in typed

**Comment by chbatey** [comment]
I think the TestProbe is complete compared to the untyped version. However it doesn't contain everything that the Testkit does for receiving messages. I think we can add them as we miss them tho?

Things we're missing:

* Implicit sender (not applicable)
* [ ] Autopilot (maybe don't port? It can be useful the odd time)

Testkit missing:
* [ ] within

**Comment by patriknw** [comment]
Added https://github.com/akka/akka/issues/24489 for `within`.

I don't think we need autopilot. I think it's easy enough to create another ordinary forwarding actor.

**Comment by patriknw** [comment]
Closing, and let's create separate tickets for other missing things, or simply add them when we need them.
