### ISSUE TITLE
Document ORMultiMap.emptyWithValueDeltas

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22771]
@gosubpl before we forget. Please describe what it does and the tradeoffs.

At the same time, could you update the rst documentation with a sentence for each type if it supports deltas. Something like https://github.com/akka/akka/commit/3e7ffd6b960ed6be7d1e2cc6fba82588ef77de28#diff-80fc82aa9c9e88753302d17fa883fabeR328

**Comment by gosubpl** [comment]
Absolutely. On it :)

**Comment by gosubpl** [comment]
Will PR after making sure Paradox compiles (need to get hands on my Linux box - see https://github.com/akka/akka/pull/22988 )
