### ISSUE TITLE
UnsupportedTemporalTypeException: Unsupported field: MonthOfYear

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22774]
https://github.com/akka/akka/pull/22716 broke something in multi-jvm tests (that are not run by pr validation):

```
[JVM-2]   java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: MonthOfYear
[JVM-2]   at java.time.Instant.getLong(Instant.java:603)
[JVM-2]   at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
[JVM-2]   at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2540)
[JVM-2]   at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
[JVM-2]   at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
[JVM-2]   at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
[JVM-2]   at akka.event.Logging$StdOutLogger$class.timestamp(Logging.scala:882)
[JVM-2]   at akka.event.Logging$StandardOutLogger.timestamp(Logging.scala:988)
[JVM-2]   at akka.event.Logging$StdOutLogger$class.warning(Logging.scala:923)
[JVM-2]   at akka.event.Logging$StandardOutLogger.warning(Logging.scala:988)
```

**Comment by guidomedina** [comment]
The only way a test could break this could be because the `long` value in millis passed by some test was wrong, maybe you should had looked at how such `long` is obtained/generated.

**Comment by guidomedina** [comment]
Nvm, I see what you did there.

**Comment by guidomedina** [comment]
@ktoso @patriknw 
As for porting back, I think one of the places I refactored could had fixed a concurrency issue where `SimpleDateFormat` was not synchronized in `AeronErrorLog`, which might be hard to produce unless such formatter would never be used concurrently.

**Comment by patriknw** [comment]
that part of AeronErrorLog is not used concurrently

**Comment by guidomedina** [comment]
So, what was the issue at the end? the time zone needed to be the default instead of UTC?
