### ISSUE TITLE
Typed: Behavior that waits for children to stop and then does cleanup

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22776]
As explained in comments:

```
/*		
 -   * TODO write a Behavior that waits for all child actors to stop and then		
 -   * runs some cleanup before stopping. The factory for this behavior should		
 -   * stop and watch all children to get the process started.		
 -   */		
  
```

**Comment by gosubpl** [comment]
What name would you suggest for this behaviour ?

**Comment by patriknw** [comment]
`gracefulStop` ?

**Comment by ktoso** [comment]
Yeah, sounds good

**Comment by gosubpl** [comment]
Do you have something like that in mind:
```
  private[akka] final case class GracefulStop[T](cleanup: SAC[T] => Behavior[T]) extends ExtensibleBehavior[T] {
    def apply(ctx: SAC[T]): Behavior[T] = {
      ctx.children.foreach(ctx.watch)
      Behavior.stopped[T]
    }
    override def receiveMessage(ctx: ActorContext[T], msg: T) = ???

    override def receiveSignal(ctx: ActorContext[T], msg: Signal): Behavior[T] = {
      msg match {
        case Terminated(_) =>
          if (ctx.asScala.children.isEmpty) {
            cleanup(ctx)
          } else
            Behavior.same
      }
    }
  }
```
or am I completely off?

**Comment by patriknw** [comment]
perhaps this can be written using ordinary `Actor.deferred` and `Actor.immutable`?

It shouldn't switch to `stopped` immediately, but to a behavior that ignores everything except Terminated, and when reaching empty children it should change to `stopped`.

Note that `stopped` has an optional `postStop` parameter. I don't remember exactly how that works. First thing to check might be that one. Perhaps it does exactly what is needed, i.e. the `PostStop` signal is passed to that `postStop` behavior when all children has been terminated?

**Comment by gosubpl** [comment]
@patriknw a bit of this is unclear for me. How do I stop children actors if I don't switch to stopped?

I agree with `Actor.deferred`, and am currently investigating `postStop` - which should work (maybe with some minor mod), but still cannot see how to initiate the process without moving to `stopped`.

**Comment by patriknw** [comment]
There is ctx.stop(child) and ctx.children

**Comment by gosubpl** [comment]
@patriknw I've pushed a commit https://github.com/gosubpl/akka/commit/e092f701852303c2fff27d24caecc1a8567ba8c7 . Let me know if this roughly ok and I will add a PR.
One thing I am definitely not sure about is the Java side.
`PostStop` won't cut it so easily, as it needs also the actor to stop, not only its children.

**Comment by hseeberger** [comment]
Hey guys, there is already `Actor.def stopped[T](postStop: Behavior[T])`. Why would we need something else?

**Comment by hseeberger** [comment]
![stopping](https://user-images.githubusercontent.com/41911/34100293-4ab79b4e-e3e2-11e7-94be-6aff0001194b.jpg)

**Comment by gosubpl** [comment]
Right, now I get it. The code in `ActorCell` does the following:
```
        case s: StoppedBehavior[T] ⇒
          // use StoppedBehavior with previous behavior or an explicitly given `postStop` behavior
          // until Terminate is received, i.e until finishTerminate is invoked, and there PostStop
          // will be signaled to the previous/postStop behavior
          s.postStop match {
            case OptionVal.None ⇒
              // use previous as the postStop behavior
              behavior = new Behavior.StoppedBehavior(OptionVal.Some(behavior))
            case OptionVal.Some(postStop) ⇒
              // use the given postStop behavior, but canonicalize it
              behavior = new Behavior.StoppedBehavior(OptionVal.Some(Behavior.canonicalize(postStop, behavior, ctx)))
          }
          self.sendSystem(Terminate())
```
Which means that new behavior waiting for the `postStop` signal is installed and shutdown is initiated. This behavior will be activated just before the actor is terminated itself, effectively running the cleanup.

I will add some tests to validate and depending on the outcome close the PR.

thanks @hseeberger and @patriknw for the discussion.
