### ISSUE TITLE
Rewrite MaybeSource as a GraphStage

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22789]
The surprise when I noticed that it is a `SourceModule`: 7/10

**Comment by gosubpl** [comment]
Also: `SubscriberSource`, `PublisherSource` and `ActorPublisherSource`.
Can I try tackling all of them?

**Comment by johanandren** [comment]
I have rewritten maybe already, but waiting for another one to merge before I can PR that, I'm not sure about the other three

**Comment by gosubpl** [comment]
@johanandren You are too fast for the poor community contributors to keep up. Let me know, if you will _not_ be doing the other three :)

**Comment by johanandren** [comment]
I will not be doing the other three, and I am unsure it if it is a good idea to rewrite those, `ActorPublisherSource` is deprecated (since `ActorPublisher` is), `{Subscriber,Publisher}Source` sounds like they could belong as lower level modules.

**Comment by gosubpl** [comment]
ok, ack, thanks for clarifying.
