### ISSUE TITLE
Contradictory documentation on backpressure for throttle methods

### ISSUE THREAD

**Issue by greenrd** [akka/akka#22791]
[The Scaladoc for the throttle methods](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L1598) says `'''Backpressures when''' downstream backpressures` but the Quick Start documentation says "when the incoming rate is higher than one per second the throttle combinator will assert back-pressure upstream." This is contradictory. (I think the latter is correct - it makes more sense.)

**Comment by raboof** [comment]
I'd expect backpressure to be applied in either of those 2 situations - good observation, let's check and fix the docs!

**Comment by richard-imaoka** [comment]
I created a PR, and here is my [gist](https://gist.github.com/richard-imaoka/83d49a08aacc25659cad8e0daca3461d) to check the backpressure behavior of a `throttle` stage.

By the way I found [`buffer`](https://github.com/akka/akka/blob/b7d7316c1c63a9476d9c3e39d7a870331750bc99/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L1338L1341) has the following description. 

```
   * '''Backpressures when''' depending on OverflowStrategy
   *  * Backpressure - backpressures when buffer is full
   *  * DropHead, DropTail, DropBuffer - never backpressures
   *  * Fail - fails the stream if buffer gets full
```

Shouldn't it be as follows?:
```
   * '''Backpressures when''' downstream backpressures or depending on OverflowStrategy
   *  * ...
   *  * ...
   *  * ...
```
