### ISSUE TITLE
[cluster-singleton] Akka 2.5 Cannot disable auto downing and on by default

### ISSUE THREAD

**Issue by haggy** [akka/akka#22790]
Apologies in advance if this has been mentioned elsewhere. I've looked on the mailing list and gitter.  I have a fairly sophisticated distributed service utilizing cluster sharding, persistence and a custom quorum-based downing provider (auto downing disabled). The issue is that I recently updated to akka 2.5 and now auto downing seems to not only be enabled but I cannot figure out how to disable it. In order to further troubleshoot and isolate the problem, I removed my custom downing logic and just left auto downing disabled using the config `akka.cluster.auto-down-unreachable-after = off`. Here is the difference between akka `2.4.17` and `2.5.0`:

Setup is a 4 node cluster, 3 seeds, 1 non-seed. To test this, I fire up all 4 nodes, then shut off the non-seed node.

Akka 2.4.17 with auto downing disabled and no downing logic:
```
WARN  akka.cluster.ClusterCoreDaemon - Cluster Node [akka.tcp://Jupiter@127.0.0.1:2551] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://Jupiter@127.0.0.1:2554, status = Up)]. Node roles [seed-node]
WARN  akka.remote.ReliableDeliverySupervisor - Association with remote system [akka.tcp://Jupiter@127.0.0.1:2554] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://Jupiter@127.0.0.1:2554]] Caused by: [Connection refused: /127.0.0.1:2554]
WARN  akka.remote.ReliableDeliverySupervisor - Association with remote system [akka.tcp://Jupiter@127.0.0.1:2554] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://Jupiter@127.0.0.1:2554]] Caused by: [Connection refused: /127.0.0.1:2554]
WARN  akka.remote.ReliableDeliverySupervisor - Association with remote system [akka.tcp://Jupiter@127.0.0.1:2554] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://Jupiter@127.0.0.1:2554]] Caused by: [Connection refused: /127.0.0.1:2554]
... ReliableDeliverySupervisor logs continue to spam due to no auto downing (good thing!) ...
```

Akka 2.5.0:
```
...
akka.cluster.singleton.ClusterSingletonManager - Member removed [akka.tcp://System@127.0.0.1:2554]
```

In akka `2.5.0` I do not see any messages for Unreachable nodes via `ClusterEvent` and no logs from the `ReliableDeliverySupervisor`... it always goes straight to Down->Removed when I shut off the 4th node. Any thoughts? Hoping this is just a new config option/change instead of a bad regression failure.

**Comment by patriknw** [comment]
It was cluster leaving because of coordinated shutdown, as expected. Explained in gitter https://gitter.im/akka/dev?at=58ff8183881b89e101850f15

**Comment by haggy** [comment]
This is due to the new Coordinated Shutdown functionality in akka 2.5. For more information see:
http://doc.akka.io/docs/akka/2.5/project/migration-guide-2.4.x-2.5.x.html#Cluster
