### ISSUE TITLE
CoupledTerminationFlow should take Graph[Sink...] etc

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22808]
CoupledTerminationFlow takes the precise types Sink/Source,
which makes it not usable for SubSinkInlet.sink since that exposes as `def sink: Graph[SinkShape[T], NotUsed] = _sink`

The type should be: 

```
  def fromSinkAndSource[I, O, M1, M2](
      in: Graph[SinkShape[I], M1], 
      out: Graph[SourceShape[O], M2]): Flow[I, O, (M1, M2)] =
```

I'm not sure we can just add the overload hm ...

**Comment by 2m** [comment]
Started to look into this one, and an overload is not enough. We need a separate method to fix the types.

What is more, I noticed that `CoupledTerminationFlow.fromSinkAndSource` lacks its `...Mat` variant which `Flow.fromSinkAndSource` has. What is even more, `CoupledTerminationFlow.fromSinkAndSource` does `Keep.both` and conversely `Flow.fromSinkAndSource` does `Keep.none`.

Therefore I propose to unify these two APIs by the following:

* add `Flow.coupledFromSinkAndSource` with the same signature as `Flow.fromSinkAndSource`
* add `Flow.coupledFromSinkAndSourceMat` with the same signature as `Flow.fromSinkAndSourceMat`
* deprecate `CoupledTerminationFlow.fromSinkAndSource` with a deprecation message to refactor to `Flow.coupledFromSinkAndSourceMat(...)(Keep.both)`

**Comment by patriknw** [comment]
Ok, looks like mostly a naming issue. We need to invent a new name.
`coupledFrom` doesn't read to good, I associate it with "decoupled from".

`coupledSinkAndSource` ?

Shall we still let it be in the separate `CoupledTerminationFlow` to not bloat the Flow API too?

**Comment by 2m** [comment]
It is quite similar to `Flow.fromSinkAndSource` therefore it is not really adding a new concept to `Flow` factory, just a variant of an already existing one. What about `Flow.fromSinkAndSourceCoupled`?

**Comment by patriknw** [comment]
I'm just thinking that the original author (I don't know who it is) must have put some thought into placing it where it is. How often is it used?

I like `fromSinkAndSourceCoupled`.

**Comment by 2m** [comment]
Actually it looks that it is used quite rarely. I was able to find that too specific type signature (the issue that this ticket is for) prevented it from being used in akka-http. Also there is https://github.com/akka/akka-http/issues/860 which is about documenting on how to use coupled sink and source to handle websocket flow. This would put coupled sink and source in quite a bit of user code.

**Comment by patriknw** [comment]
Ok, let's move it to flow

**Comment by ktoso** [comment]
> I'm just thinking that the original author (I don't know who it is) must have put some thought into placing it where it is. How often is it used?

That'd be me :-) I think there was some push back on "putting stuff on flow" back then, so I put it separately. 

It is *very* useful when people do anything with the "from sink and source" style in akka http - most notably the websocket apis. So definitely good to make it more visible to people by putting it on flow (they're confused why thigns dont terminate if it's not a coupled one in WS).
