### ISSUE TITLE
Explain (move) blocking on fork join pool better in new docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22803]
We have this page in akka http which is pretty good: http://doc.akka.io/docs/akka-http/current/scala/http/handling-blocking-operations-in-akka-http-routes.html we could make it less HTTP specific and show off in the new docs.

It would extend the "blocking needs careful management" things

Help welcome :)

**Comment by jrudolph** [comment]
That page is already a superb resource. Let's make sure it gets the place it deserves in the new documentation.

**Comment by richard-imaoka** [comment]
I am going to pick this up if no one else started working on it.

Does the below "**new docs**" mean

>we could make it less HTTP specific and show off in the new docs.

the paradox version of the akka (not akka-http) doc?

**Comment by ktoso** [comment]
Hm, not sure if this is the best timing to port it over - let's wait until we ship the new docs?

Yes, there will be a paradox akka docs page to replace the current one, along with a new theme etc - very soon.

**Comment by richard-imaoka** [comment]
http://doc.akka.io/docs/akka/snapshot/scala/dispatchers.html

I see the new docs are available as snapshot. Let me work on this then.

**Comment by patriknw** [comment]
Thanks, CONTRIBUTING.md contains instructions of how to build docs locally
