### ISSUE TITLE
Provide style guide for Typed actors and apply it everywhere

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22805]
For example:
- Instead of `import Actor._` and then saying `def myActor: Behavior[A] = Immutable` we should prefer `def myActor: Behavior[A] = Actor.Immutable`
- do prefer `import Actor._` and `Same` instead `Actor.Same`
- do not use `Behavior.Same` in user-code, use the Actor contained DSL
- do use Behavior.Same and friends when building a custom specialised behavior (by extending it)

Add more like these so we can build a style guide by the end of the sprint.

**Comment by johanandren** [comment]
Not really style, but: I think factories should be lowercase and return `Behavior` rather than the behavior implementation type (where possible).

**Comment by patriknw** [comment]
I have started on the rename to lower case, but didn't complete it yet.

**Comment by johanandren** [comment]
Updated list plus some thoughts:

* Import `a.a.t.s.Behaviors` and use `Behaviors.factorNnn` rather than importing all factories into the scope with `Behaviors._` 
* not use `a.a.t.Behavior.BehImp` in user-code, use the respective language DSL
* do use `Behavior.Same` and friends when building a custom specialised behavior (by extending it)

Not sure about these
* Use `MutableState` for Java rather than `Behaviors.setup` (to make it easier to grasp for OO people?)
* Prefer behavior factory methods capturing state as parameters rather than closing over a var or mutable data structure with `Behaviors.setup` (on the fence here, I often find the closing one easier to read)

Things we may want to cover
 * Standard place to put behavior and messages (like the "always put a props and messages in companion" for untyped. `MyActor.behavior`?

**Comment by ktoso** [comment]
1) Avoid the pyramid of doom:

```
    Behaviors.setup { context ⇒
      val mdc = mdcFor(context, setup)
      Behaviors.withMdc(_ ⇒ mdc, {
        Behaviors.withTimers { timers ⇒
          Behaviors.immutable {
            case (_, JournalResponse(r))          ⇒ onJournalResponse(setup, r)
```

2) Passing around context / timers / other state is find in an "state" or "setup object" that is only to be used by the given behaviors etc.


3) if mdc init is once for an actor and does not change, avoid messy in-line definitions:

```
    Behaviors.setup { context ⇒
      val mdc = Map(
        "contextStuff" → contextStuffHere
      )
      Behaviors.withMdc(_ ⇒ mdc, Behaviors.immutable {
        case (_, c) ⇒ onCommand(setup, c)
      })
    }
```

Make a mini DSL for readability:

```
  def apply[Command, Event, State](setup: EventsourcedSetup[Command, Event, State]): Behavior[Command] = {
      startRecoveryTimer(setup)

    withMdc(setup) { ... } 
  }

  def withMdc[C, E, S](setup: EventsourcedSetup[C, E, S])(b: Behavior[C]): Behavior[C] = {
    val mdc = Map(
      "persistenceId" → setup.persistenceId,
      "phase" → "recover-snap"
    )
    Behaviors.withMdc(_ ⇒ mdc, b)
  }

```

**Comment by ktoso** [comment]
Document the `widen+narrow` pattern for internal/external protocols:

https://github.com/akka/akka/commit/abaf1b4dc64b572080320cccd20e54e70c270612#diff-9da2ed336b4afbc3d16e6ebdb7a212f9R155

```
 override def apply(context: typed.ActorContext[Command]): Behavior[Command] = {
    Behaviors.setup[EventsourcedBehavior.InternalProtocol] { ctx ⇒
      Behaviors.withTimers[EventsourcedBehavior.InternalProtocol] { timers ⇒
        val setup = EventsourcedSetup(
          ctx,
          timers,
          persistenceId,
          initialState,
          commandHandler,
          eventHandler)
          .withJournalPluginId(journalPluginId)
          .withSnapshotPluginId(snapshotPluginId)

        EventsourcedRequestingRecoveryPermit(setup)
      }
    }.widen[Any] {
      case res: JournalProtocol.Response           ⇒ InternalProtocol.JournalResponse(res)
      case RecoveryPermitter.RecoveryPermitGranted ⇒ InternalProtocol.RecoveryPermitGranted
      case res: SnapshotProtocol.Response          ⇒ InternalProtocol.SnapshotterResponse(res)
      case cmd: Command @unchecked                 ⇒ InternalProtocol.IncomingCommand(cmd)
    }.narrow[Command]
}

```

**Comment by ktoso** [comment]
Provide examples and guidance that "mixing mutable and not mutable" styles is perfectly fine.

**Comment by patriknw** [comment]
Document the "capture context parameters in enclosing class" as we did for the persistence impl setup param.

In scala you can get far without this because you can create inline methods, e.g. all within the `setup` block, but for "bigger" actors it's nice to have a class and traits for mixing in different things. For java it's almost immediately necessary if using the `immutable`.

**Comment by ktoso** [comment]
Document avoiding pyramids of doom when sharing a signal handler:

Not like this:

```
    withMdc {
      returnPermitOnStop {
        Behaviors.immutable {
          case (_, SnapshotterResponse(r))      ⇒ onSnapshotterResponse(r)
          case (_, JournalResponse(r))          ⇒ onJournalResponse(r)
          case (_, RecoveryTickEvent(snapshot)) ⇒ onRecoveryTick(snapshot)
          case (_, cmd: IncomingCommand[C])     ⇒ onCommand(cmd)
        }
      }
    }
  }
```

but like this 

```
    withMdc {
      Behaviors.immutable {
        case (_, SnapshotterResponse(r))      ⇒ onSnapshotterResponse(r)
        case (_, JournalResponse(r))          ⇒ onJournalResponse(r)
        case (_, RecoveryTickEvent(snapshot)) ⇒ onRecoveryTick(snapshot)
        case (_, cmd: IncomingCommand[C])     ⇒ onCommand(cmd)
      }.onSignal(returnPermitOnStop)
    }

```

**Comment by ktoso** [comment]
Sharing onSignal is may be tricky:

```
Behaviors.immutable {
        case (_, JournalResponse(r))      ⇒ onJournalResponse(state, r)
        case (_, SnapshotterResponse(r))  ⇒ onSnapshotterResponse(r)
        case (_, RecoveryTickEvent(snap)) ⇒ onRecoveryTick(state, snap)
        case (_, cmd: IncomingCommand[C]) ⇒ onCommand(cmd)
      }.onSignal({ case (c, s) ⇒ returnPermitOnStop(c → s) })
```

results in 

```
[error] Expected type was: (akka.actor.typed.scaladsl.ActorContext[?], ?) => akka.actor.typed.Behavior[?]
[error]       Behaviors.immutable {
[error]                           ^
[error] /Users/ktoso/code/akka/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedRecoveringEvents.scala:75:55: type mismatch;
[error]  found   : (Any, Any)
[error]  required: (akka.actor.typed.scaladsl.ActorContext[akka.persistence.typed.internal.EventsourcedBehavior.InternalProtocol], akka.actor.typed.Signal)
[error]       }.onSignal({ case (c, s) ⇒ returnPermitOnStop(c → s) })
[error]                                                       ^
```

One has to type hint the `Behaviors.immutable[InternalProtocol] {` for inference not to panic

**Comment by ktoso** [comment]
Document that one has to handle both PostStop and PreRestart if some shared cleanup logic is there:

See: https://github.com/akka/akka/pull/24681#discussion_r173383818

**Comment by ktoso** [comment]
In case of a protocol that is handled by many protocol, and may get additional messages; should we recommend explicitly handling the "other cases" or tell people to `case _ => Behaviors.unhandled`?

The latter turns off exhasutivity checks so if we add a new message, the new class still ignores it, but perhaps one should think about what the behavior should be doing in case it receives such mesassage?

I opted for the `case _ => ` in persistence, but alternative would have been:

```scala
// explicitly ignore other messages; these should not happen in this phase:
        case _: LoopMessageSuccess ⇒
          // ignore, should never happen as there is no persistAsync in typed
          Behaviors.unhandled
        case RecoverySuccess(_) ⇒
          Behaviors.unhandled
        case ReplayMessagesFailure(_) ⇒
          Behaviors.unhandled
        case ReplayedMessage(_) ⇒
          Behaviors.unhandled
```

**Comment by johanandren** [comment]
There is also `Behaviors.immutablePartial` for that case.

**Comment by ktoso** [comment]
Yeah, true -- could be that `case _ =>` should be discouraged then

**Comment by patriknw** [comment]
If you want to be careful and keep the exhaustiveness check it's probably better to add the explicit messages `=> unhandled`. The drawback is more code, probably in several places.

In protocols with many messages one can add sub-traits to reduce number of such unhandled cases.

**Comment by johanandren** [comment]
In this discussion thread a very nice solution to doing mutable state with Java came up, maybe even so nice we can recommend it over `MutableBehavior` for Java users:

To sum it up, encapsulate state in a class with private constructor, have static behavior factories inside of the class that creates the actual instance inside of a `setup` lambda.

https://discuss.lightbend.com/t/java-akka-typed-immutable-behavior-can-we-safely-mix-with-mutable-arguments/213/8

**Comment by patriknw** [comment]
Added by @TimMoore, https://github.com/akka/akka/pull/25728#discussion_r222290522

> Separating command handlers into individual methods makes it more obvious what is purely dispatch logic and what is relevant to the domain. It also reduces some of the syntax soup that might be unfamiliar to some Java developers who haven't used lambdas much. Method handles might still be new, but maybe a little easier to intuit.

Same for ordinary message handlers.

**Comment by patriknw** [comment]
Added by @TimMoore , 
https://github.com/akka/akka/pull/25728#discussion_r222289480

This idiom of using enum for a singleton object is recommended in "Effective Java".

```
public enum Increment implements Command {
    INSTANCE
}
```

**Comment by patriknw** [comment]
note that the enum idom can be used for things like this also:
```
  public enum EmptyAccount implements Account {
     INSTANCE;

     @Override
     public Account created(AccountCreated event) {
       return new OpenedAccount(0.0);
     }
   }
```

**Comment by dwijnand** [comment]
It's common to have the public interface above the private implementation details in classes/files.

So for typed actors, it looks similar to have the public interface of message classes at the top of the object and the `val behavior` implementation detail at the bottom.

**Comment by patriknw** [comment]
For Scala yes, but for Java it becomes so bloated.

**Comment by dwijnand** [comment]
Yeah my comment was for Scala, in response to

> I'm on the fence if it's better to have a separate object

(I'm going to continue to assume you're _NOT_ looking to find the same style for both Scala and Java)

**Comment by patriknw** [comment]
Use
```
ref.ask(Foo(1, _))
```

because parens are needed and `ref ? (Foo(1, _))` is somewhat weird syntax.
Also aligns with context.ask which doesn’t have a symbol.

**Comment by patriknw** [comment]
When sending messages to an other actor or receiving responses they should have the full name rather than import of the short message class, like `TheOtherActor.DoIt` rather than `DoIt`.

In the implementation of the Behavior it's fine to use short name, via import.

**Comment by patriknw** [comment]
Where to define the message classes?

For Java:
static classes inside the "actor" class.
If messages shared between several actors then inside a separate class/interface, MyActorProtocol. 

For Scala:
In the companion.
If messages shared between several actors then inside a separate object, MyActorProtocol.

**Comment by patriknw** [comment]
Especially for Java it's useful to have an enclosing class capturing the (immutable) "constructor" parameters. Useful for the functional style because then you don't have to pass everything around. Also useful for oo-style when switching behaviors. See examples in training materials.

**Comment by patriknw** [comment]
Note that guards in pattern matching result in loss of exhaustiveness check, so better to do if-else inside the case.

**Comment by patriknw** [comment]
Always use a factory method for the initial Behavior.

Naming:
* in Java: `create`
* in Scala: `apply`

**Comment by patriknw** [comment]
Return `this` rather than `Behaviors.same` in OO style.

**Comment by patriknw** [comment]
Use mostly OO style in Java docs and functional in Scala docs. Also for the shorter snippets.

**Comment by patriknw** [comment]
Use flat class hierarchies for the messages and simple ADT/enum classes.

**Comment by patriknw** [comment]
Initialize things from the user guardian instead of doing it from the outside. Often via `Behaviors.setup` of the user guardian.

**Comment by patriknw** [comment]
Testing with child actors that are replaced by stubs/probs by creating them via methods that can be overridden by the test. (probably mention in testing docs instead of style guide)

**Comment by patriknw** [comment]
How to structure private and public messages is also a topic.

There are two ways.

1. private visibility of the private commands, but top level exposed trait is public
1. only expose the public commands via `narrow`

```scala
object ChatRoom {
    private sealed trait PrivateCommand
    sealed trait Command extends PrivateCommand

    final case class GetSession(screenName: String, replyTo: ActorRef[SessionEvent]) extends Command
    private final case class PublishSessionMessage(screenName: String, message: String) extends PrivateCommand

    def apply(): Behavior[Command] =
      chatRoom(List.empty).narrow

    private def chatRoom(sessions: List[ActorRef[SessionCommand]]): Behavior[PrivateCommand] =
      Behaviors.receive { (context, message) =>
```

vs.

```scala
object ChatRoom {
    sealed trait Command
    final case class GetSession(screenName: String, replyTo: ActorRef[SessionEvent]) extends Command
    private final case class PublishSessionMessage(screenName: String, message: String) extends Command

    def apply(): Behavior[Command] =
      chatRoom(List.empty)

    private def chatRoom(sessions: List[ActorRef[SessionCommand]]): Behavior[Command] =
      Behaviors.receive { (context, message) =>
```

I think the latter is more straight forward, but the former is not wrong so maybe good to mention that both are valid approaches.

**Comment by dwijnand** [comment]
A, perhaps, more familiar modelling is where `Message`s that divide in public API `Command` messages and private, internal `Event` messages:

```scala
sealed trait InventoryMessage
sealed trait InventoryCommand extends InventoryMessage
sealed trait InventoryEvent extends InventoryMessage

def mkInventory: Behavior[InventoryCommand] =
  Behaviors.setup[InventoryMessage] { context =>
    ...
  }.narrow
```

**Comment by patriknw** [comment]
First version of this is done. Didn't update all doc snippets to follow the guide yet. That is now a task in #24717.

**Comment by patriknw** [comment]
For the impatient it’s published in snapshot docs: https://doc.akka.io/docs/akka/snapshot/typed/style-guide.html
