### ISSUE TITLE
move ConstantFun to akka-actor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22813]
It's in akka-stream and we might need similar in akka-typed

**Comment by ktoso** [comment]
Ah, good catch, yeah definitely useful for actor and other places.

**Comment by Hawstein** [comment]
Since `ConstantFun` is private to `akka`, it seems that it's safe to move it to `akka.util` which is a good place for ConstantFun.  If that is OK, i will create a PR for it.

**Comment by ktoso** [comment]
Yes that sounds good to me; no one other than Akka itself should have touched those functions so we can move it. `akka.util` sounds like a good place for it - please to keep it `InternalApi` though

**Comment by ktoso** [comment]
Oh wait, Patrik may have done this already - checking.

**Comment by Hawstein** [comment]
OK, thanks. Not in #22801 though.

**Comment by ktoso** [comment]
Right, it seems not done in any of the PRs I checked. Go ahead with the move then :)
Thanks!

**Comment by Hawstein** [comment]
Created PR for it and change some `un-exposed` variables to `private`.

Also include the `nullFun` which is used in #22801
