### ISSUE TITLE
There is no catalog number in Akka Java Document

### ISSUE THREAD

**Issue by MingJunDuan** [akka/akka#22812]
I downloaded **Akka Java Document** from "http://doc.akka.io/docs/akka/2.5/AkkaJava.pdf". I found there was no catalog number when reading it with Adobe PDF Reader. I not sure it was done on purpose or not. Hope to hear from you.

**Comment by ktoso** [comment]
Why do you need one in it?

-- 
Konrad Malawski

**Comment by MingJunDuan** [comment]
Just used to that way   :)

**Comment by ktoso** [comment]
What would it help with? It's not a published book so it can't have an ISBN
number if that's what you're asking for hm.

Propose we close the ticket?

-- 
Konrad Malawski

**Comment by hepin1989** [comment]
@ktoso He wants the name of sections or chapters  have the preceding number show up in the navigation bar.
eg
```
1.1 Why Akka? 
```

And then he could do a quick jump after a quick glance.

**Comment by ktoso** [comment]
Ah I see, I did not get what catalog numbers meant.
Not sure what we'll do with the pdf in the new docs, will keep it in mind - thanks
