### ISSUE TITLE
Clarify use of org.iq80.leveldb:leveldb dependency in akka-persistence documentation

### ISSUE THREAD

**Issue by victornoel** [akka/akka#22816]
Hi,

I don't understand why `akka-persistence` depends on `org.iq80.leveldb:leveldb`:
 - as `leveldbjni` states in its [README](https://github.com/fusesource/leveldbjni#using-as-a-maven-dependency):
> Lastly, another project unrelated to this project separately provides a (less mature) pure Java implementation of LevelDB, see `dain/leveldb`. Note that both that and this project share the same Maven artefact for the Level DB API interface (`org.iq80.leveldb:leveldb-api`).
 - `akka-persistence` seems to use one class from `org.iq80.leveldb:leveldb` but it is from its tests, no the main code.

~~I would thus recommend (if I am not mistaken :):~~
 - ~~removing any mention of `org.iq80.leveldb:leveldb` in the documentation~~
 - ~~removing any non-test dependency to `org.iq80.leveldb:leveldb` in `akka-persistence`~~

EDIT: see comment below

**Comment by victornoel** [comment]
Hm, I see there is two modes of operation, native and non-native. I understand better why there is this dependency then.

It should be better documented maybe? I thinnk `org.iq80.leveldb:leveldb` is not meant to be used in production...

Also version 0.9 of it is out :)

**Comment by johanandren** [comment]
I thought this was pretty clear (but maybe it can be improved):
> A shared LevelDB instance is a single point of failure and should therefore only be used for testing purposes. ...
http://doc.akka.io/docs/akka/2.5.1/scala/persistence.html#Shared_LevelDB_journal

**Comment by victornoel** [comment]
@johanandren my issue is not about shared LevelDB but about non-native LevelDB implementation.

In other words:
 - if someone uses native leveldb, only leveldbjni is needed
 - if someone uses non-native leveldb, only org.iq80.leveldb:leveldb is needed

But never both, so I was thinking about documenting that fact :)

**Comment by johanandren** [comment]
Ah, good point, you up for doing a PR adding that?

**Comment by victornoel** [comment]
I will try to do it, ok :)
