### ISSUE TITLE
Refine Gossip convergence conditional statement

### ISSUE THREAD

**Issue by Hawstein** [akka/akka#22815]
Currently it is

```scala
    unreachable.forall(m ⇒ Gossip.convergenceSkipUnreachableWithMemberStatus(m.status)) &&
      !members.exists(m ⇒ Gossip.convergenceMemberStatus(m.status) &&
        !(seenByNode(m.uniqueAddress) || exitingConfirmed(m.uniqueAddress)))
```

IMO, the statement `!members.exists(m ⇒ Gossip.convergenceMemberStatus(m.status) && !(seenByNode(m.uniqueAddress) || exitingConfirmed(m.uniqueAddress)))` is not quite straightforward. Instead, I think the following expression is easier to understand:

```scala
members.forall(m => if (Gossip.convergenceMemberStatus(m.status)) seenByNode(m.uniqueAddress) || exitingConfirmed(m.uniqueAddress) else true)
```

Just personal opinion, WDYT @patriknw

**Comment by raboof** [comment]
@Hawstein  Hmm I don't think the `if (..) .. || .. else true` notation is that easy to read either though...

**Comment by patriknw** [comment]
I think we rewrote this somewhat in the `wip-multi-dc-dev` branch.
