### ISSUE TITLE
Scala in some Java documentation

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka#22811]
While reading the Java version of Remoting (codename Artery) I came across a few bits of SBT and Scala. Nothing major, the rest of the page seems to be all using Java examples.
http://doc.akka.io/docs/akka/2.5.0/java/remoting-artery.html#Acquiring_references_to_remote_actors

In the Preparing your ActorSystem for Remoting section, the dependency is not Maven but build.sbt.
http://doc.akka.io/docs/akka/2.5.0/java/remoting-artery.html#Preparing_your_ActorSystem_for_Remoting

In the Looking up Remote Actors section, the example tell is in Scala syntax.
http://doc.akka.io/docs/akka/2.5.0/java/remoting-artery.html#Looking_up_Remote_Actors

In the Untrusted Mode section, there is a problem with a configuration setting.
http://doc.akka.io/docs/akka/2.5.0/java/remoting-artery.html#Untrusted_Mode

Is: akka.remote.artery..trusted-selection-paths = ["/user/receptionist", "/user/namingService"]
Should be: akka.remote.trusted-selection-paths = ["/user/receptionist", "/user/namingService"]

**Comment by ktoso** [comment]
Thanks, we'll fix those (or someone from the community could pick it up)

**Comment by zaharidichev** [comment]
@ktoso Can I take that one ?

**Comment by ktoso** [comment]
This was done already
