### ISSUE TITLE
The generated docs for scala akka-streams skips the "Design Principles Chapter"

### ISSUE THREAD

**Issue by ivanopagano** [akka/akka#22826]
The [Design Principles](http://doc.akka.io/docs/akka/2.5/general/stream/stream-design.html) chapter is general and shared between both api versions. Still, using the navigation links on the top right, only the java documentation is actually linked.

To access this Chapter you need to find it in the Scala Table of contents and even then, after reading it, you have to get back to the scala ToC if you don't want to inadvertently continue reading the java documentation.

This is quite confusing and doesn't serve well the use case of people reading the akka-docs as a linear manual.  
In this case the DRY principle doesn't seem to work out well

**Comment by raboof** [comment]
I see what you mean: this page is under 'general', and even when you landed there from the scala docs, the next/previous navigation links at the top right point to the java version of the docs.

The bad news is I'm not sure I have a quick fix.

The good news is we're in the process of moving to a new docs system ('paradox') that should make the scala/java co-existence a lot nicer, see http://pi.bzzt.net/akka-docs-new/ for a sneak peek. This will take a while to complete though...

**Comment by ivanopagano** [comment]
This is good news. Let's see what the new docs will bring about.

To be honest I liked the current docs visuals better  =D

**Comment by raboof** [comment]
There's a new style coming up actually ;)

**Comment by patriknw** [comment]
This is fixed in new docs
