### ISSUE TITLE
Failed: jdocs.stream.ActorSubscriberDocTest

### ISSUE THREAD

**Issue by 2m** [akka/akka#22839]
https://jenkins.akka.io:8498/job/akka-nightly/4379/consoleFull

Full GC messed up the test timings. Fix with increasing the timeout.

<details>
<pre>
[DEBUG] [05/04/2017 02:49:36.082] [pool-7-thread-23] [EventStream(akka://ActorSubscriberDocTest)] logger log1-TestEventListener started
[DEBUG] [05/04/2017 02:49:36.082] [pool-7-thread-23] [EventStream(akka://ActorSubscriberDocTest)] Default Loggers started
5554.150: [Full GC (Metadata GC Threshold)  1987M->573M(3072M), 4.6487028 secs]
   [Eden: 745.0M(1368.0M)->0.0B(1843.0M) Survivors: 121.0M->0.0B Heap: 1987.9M(3072.0M)->573.5M(3072.0M)], [Metaspace: 501952K->479027K(1492992K)]
 [Times: user=6.31 sys=0.09, real=4.65 secs] 
[info] - demonstrateActorPublisherUsage *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) while expecting 117 messages (got 0)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$$anonfun$receiveN_internal$1.apply(TestKit.scala:698)
[info]   at akka.testkit.TestKitBase$$anonfun$receiveN_internal$1.apply(TestKit.scala:695)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:160)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[info]   at akka.testkit.TestKitBase$class.receiveN_internal(TestKit.scala:695)
[info]   at akka.testkit.TestKitBase$class.receiveN(TestKit.scala:686)
[info]   at akka.testkit.TestKit.receiveN(TestKit.scala:828)
[info]   at akka.testkit.javadsl.TestKit.receiveN(TestKit.scala:378)
[info]   at jdocs.stream.ActorSubscriberDocTest$1.<init>(ActorSubscriberDocTest.java:231)
[info]   at jdocs.stream.ActorSubscriberDocTest.demonstrateActorPublisherUsage(ActorSubscriberDocTest.java:212)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:497)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
</pre>
</details>

**Comment by johanandren** [comment]
Whoa, 4 seconds of gc!?

**Comment by johanandren** [comment]
I wonder if we should lower the metadata space size to make GC pauses more often -> shorter? Currently we have it set to `-XX:MetaspaceSize=512M`

**Comment by patriknw** [comment]
We have struggled with that many times and never found a way around just increasing the meta space. We don't want full gc, and smaller meta space will trigger more full gc, if I recall my previous attempt correctly.

**Comment by johanandren** [comment]
Did some profiling yesterday, just to check there was no leaking we had started with recently but couldn't see anything obvious. Still don't quite get how it can be 4 seconds of gc. Maybe it is because we are reaching the upper limit on metaspace and g1gc really spent some time trying to free more of it?

Not sure I  think it feels right to increase the timeout more than 3 seconds in a single case, we probably have a large amount of 3 second timeouts in the test code base.

**Comment by 2m** [comment]
Yup. After seeing your comment regarding metaspace usage after GC I think increasing metaspace (given there is no obvious leak) instead of increasing the timeouts is a better option.

**Comment by 2m** [comment]
Increased MetaSize to 768. Closing this one and https://github.com/akka/akka/issues/22888 and see if that happens more.
