### ISSUE TITLE
Cannot use FiniteDuration with Parameter

### ISSUE THREAD

**Issue by dubeejw** [akka/akka#22838]
When trying to use a scala.concurrent.duration.FiniteDuration as a parameter value, I get the following error:

```
too many arguments for method parameter: (pdm: akka.http.scaladsl.server.directives.ParameterDirectives.ParamMagnet)pdm.Out
```

Example:
```
parameter(time: 60 seconds) { (wait) =>
...
}
```

**Comment by ktoso** [comment]
What are you trying to achieve? (`parameter(time: 60 seconds)` is not valid scala syntax btw?)

**Comment by ktoso** [comment]
Also, Akka HTTP lives in github.com/akka/akka-http, please open the ticket over there.
