### ISSUE TITLE
always signal PostStop

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22840]
I noticed that PostStop is not signaled when voluntarily stopping the behavior. It seems to be a conscious decision, and I can understand that one reason is that you might not expect anything more after stopping. However, it's different from what we have in streams and untyped, where you know that postStop is always the last thing and the place to put cleanup. Wonder if this difference would be too surprising for users? Thoughts?

**Comment by ktoso** [comment]
I'm much in favour of PostStop always firing, since it's great to have "one spot" to have cleanup things. It's very useful and also consistent with the rest of Akka, including Streams and untyped.

**Comment by patriknw** [comment]
One note from [discussion](https://gitter.im/akka/dev?at=590b21388e4b63533d2f8a68) is that if we do this change it would be useful to pass in next behavior to `Actor.stopped(postStopBehavior)`, so that the `PostStop` can be handled by another behavior if needed.

**Comment by patriknw** [comment]
I'll give this a try
