### ISSUE TITLE
cleanup canonical

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22841]
There are quite a few `canonical` methods spread out in various places. See if those can be refactored, including `undefer`, to make things more DRY.

**Comment by johanandren** [comment]
For the `undefer` part, you mean that we should avoid calling it (from a quick look it seems it is mostly used like so: `Behavior.validateAsInitial(Behavior.undefer(d, c))`. I wonder if it could just always be done inside `validateAsInitial`?
