### ISSUE TITLE
Documentation build guidelines are missing required tex packages

### ISSUE THREAD

**Issue by zaharidichev** [akka/akka#22850]
[Docs guidelines](http://doc.akka.io/docs/akka/current/dev/documentation.html) are specifying a list of tex packages that need to be installed. However there are two more that are required. Therefore docs need to be updated. The missing ones from the list are: 

    sudo tlmgr install fncychap
    sudo tlmgr install tabulary

**Comment by johanandren** [comment]
We are replacing sphinx as tool for building docs soon anyways, so no need to spend time on updating the old instructions.

**Comment by ktoso** [comment]
As Johan said, we're replacing the docs infra - closing this ticket.

**Comment by ktoso** [comment]
(exactly this or next week btw)
