### ISSUE TITLE
Typed: Terminate child actors

### ISSUE THREAD

**Issue by daniel-shuy** [akka/akka#22853]
In Akka Typed 2.5.1:

Does `ActorContext.stop` still work for terminating child actors in Akka Typed? Or do I have to create a new message for the child actors to change their `Behavior` to `Stopped`?

**Comment by johanandren** [comment]
Hi @daniel-shuy please use the gitter channel or the mailing list (linked from the readme: https://github.com/akka/akka#community) for questions and leave the issue system for bugs and feature improvements, thanks!

**Comment by daniel-shuy** [comment]
I did ask on Gitter before opening this issue (2 questions in fact), but got no reply

**Comment by johanandren** [comment]
There is a milestone of the latest work we have been doing on typed that was released friday, if you are meaning to test typed to report back, try that milestone, `2.5.99-TYPED-M1`, not 2.5.1.

**Comment by ktoso** [comment]
To follow up to what Johan just said, here's additional reading materials:
- http://blog.akka.io/typed/2017/05/05/typed-intro
- http://blog.akka.io/typed/2017/05/06/typed-coexistence

**Comment by daniel-shuy** [comment]
@johanandren ok, I'll test with that instead, thanks.

@ktoso Thanks for the links.
