### ISSUE TITLE
Can merging of multiple sources be prioritized?

### ISSUE THREAD

**Issue by arpanchaudhury** [akka/akka#22865]
Hi, 

I am creating this issue to discuss further about **PR-22864**. The idea behind `MergePrioritize` is similar to `MergePreferred` stage. MergePreferred combines several streams, taking elements as they arrive from input streams and picking from preferred when several have elements ready. But there is a risk that the elements in auxiliary streams are never picked up if preferred stream continually pushes. Where as we might need some stage which takes priorities along with the sources and try to consume incoming data in the ratio defined by their priorities. 

Let us take an example of two sources **S1** and **S2** and we want to merge these input streams giving 80% percent priority to elements in **S1** and 20% to **S2**. These priorities can be used to define the ratio of elements we want to consume from each of the streams provided all of them have elements ready. `MergePrioritize` will allow us to perform this. The signature is as follows - 
```
MergePrioritized(val inputPorts: Int, val priorities: immutable.Seq[Int], val eagerComplete: Boolean)  
```
Here inputPorts define the number of inlets and priorities define the ratio of elements taken from each of the inlets to merge. So in above scenario we define the stage as follows -
```
Source.combine(s1, s2)(MergePrioritized(_, immutable.Seq(8, 2)))
```
A real world use-case would be having different kind of jobs to be processed in different sources and we want to schedule them considering their priorities.

**Comment by johanandren** [comment]
With 3 inputs, and elements on 1 and 2 but not three, would that then lead to using the relative priorities of just 1 and 2?

**Comment by arpanchaudhury** [comment]
Yes it will. For example if we have priorities in ratio 5 :: 3 :: 1 and Source 1 doesn't have elements ready then it will consume from Source 2 and 3 in 3 :: 1 ratio. I have a test case covering the same scenario.

**Comment by arpanchaudhury** [comment]
Hi @johanandren, I have refactor the code and incorporated all suggested changes. Can you kindly take a look?

**Comment by arpanchaudhury** [comment]
Hi, request repository owners to kindly conclude this issue. I have updated the PR already.

**Comment by johanandren** [comment]
Hi @arpanchaudhury, sorry for the slow feedback on this. The PR need one more review from the core team. We will do that as soon as we can, it has not been forgotten, we are just very busy. :)

**Comment by fxlae** [comment]
I would like to express that the suggested feature has a lot of use cases and is much more flexible than the existing `MergePreferred`, besides removing the danger of starving input streams. It even could replace `MergePreferred` completely when introducing a zero priority ("only take me if other inputs don't have elements ready").

Example: the priorities `5 :: 3 :: 1 :: 0 :: 0` would mean that the first three inputs are consumed with a ratio of 5 : 3 : 1. Input four and five are only consumed (and only then) if none of the first three inputs have elements ready.
