### ISSUE TITLE
Sharding entities not restarting after full cluster restart in Distributed Data mode

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka#22868]
I am using Cluster Sharding with rememberEntities in Akka 2.5.1. For this test I am using a cluster of one node. If I use distributed data mode (`akka.cluster.sharding.state-store-mode = ddata`), the running entities are not recovered when I crash and then restart the node. So:

1. I start the single node cluster.
2. I start a couple of entities.
3. I kill the node.
4. I restart the node.
5. The entities are not restarted.

If I repeat the same test, with Persistence mode (`akka.cluster.sharding.state-store-mode = persistence`), the entities are restarted in step 5.

Rebalancing of Shards works correctly (the entities are started on the new node) in a multi node cluster.

I think the problem is that the Shards are not restarted on a full cluster restart, so the containing entities are not restarted either. I checked this by sending (after step 5) a single entity in a shard a message, and the result was that all entities in that shard were started.

Is this a bug? The documentation does say that "state of the coordinator is not durable", but it also says "The stored entities are started also after a complete cluster restart."

**Comment by johanandren** [comment]
Remember entities require the shard state to be there to work, so if you use ddata and cycle your cluster the behavior you describe is expected.

**Comment by lukas-phaf** [comment]
But is it desired? As it is not consistent with this part of the documentation:
"The functionality when using the two modes is the same. If your sharded entities are not using Akka Persistence themselves it is more convenient to use the Distributed Data mode, since then you don't have to setup and operate a separate data store (e.g. Cassandra) for persistence. Aside from that, there are no major reasons for using one mode over the the other."

**Comment by johanandren** [comment]
If you are not keeping the cluster sharding state there is no possible way to figure out where to run shards, and therefore impossible to start the entities that was running inside a shard. You can run the ddata mode with durable store, that will store the state locally on the nodes, that could work in a non-virtualised environment, if you have immutable machines/replace them ddata is not an option if you want to be able to restart the entire cluster and use remember entities.

Not sure but maybe it could be documented more clearly.

**Comment by lukas-phaf** [comment]
Thanks for explanations.

So for a non-virtualised cluster, I can make it work by adding "${typeName}CoordinatorState" to `akka.cluster.sharding.distributed-data.durable.keys` (where typename is the name I am using for the shard)?

The point I was trying to make is that the documentation implies that Distributed Data mode and Persistence mode can be used interchangeable, but Persistence mode stores the cluster sharding state in a durable way, while the Distributed Data mode does not.

**Comment by patriknw** [comment]
@johanandren You are describing how it works in Akka 2.4 but in 2.5 the remember entities are stored with durable ddata so they should be started on cluster restart. No configuration should be needed to enable that.

@lukas-phaf One thing to note is that the lmdb directory is by default derived from the hostname:port so when you restart you have to use the same port, or change that directory setting.

> When Distributed Data mode is used the identifiers of the entities are stored in Durable Storage of Distributed Data. You may want to change the configuration of the akka.cluster.sharding.distributed-data.durable.lmdb.dir`, since the default directory contains the remote port of the actor system. If using a dynamically assigned port (0) it will be different each time and the previously stored data will not be loaded.

http://doc.akka.io/docs/akka/2.5/scala/cluster-sharding.html#Remembering_Entities

Let us know if that was the problem or how you reproduce the problem. We have tests for this so it should work.

**Comment by lukas-phaf** [comment]
@patriknw I am using the same hostname:port after a restart, so the correct lmdb data is used. This is also shown that, by after a cluster restart, all entities in a shard are restarted if I send a single entity in that shard a message.

I also tried forcing that the coordinator state is persisted by using:
```
akka.cluster.sharding.state-store-mode = ddata
akka.cluster.sharding.distributed-data.durable.keys += "CalculationCoordinatorState"
```
That indeed makes all the entities restart after a cluster restart (although some dead letters are produced).

I do have a question on how the Shards are supposed to be started on a cluster restart. In the config, I see:
```
distributed-data {
    # minCap parameter to MajorityWrite and MajorityRead consistency level.
    majority-min-cap = 5
    durable.keys = ["shard-*"]
```

From this I conclude only the 'shard-*' keys are durable. From the code in Shard.scala, this is just a set of entity id's. And it is only used in the Shard.scala file itsself. So how does the system know which shards/entities to start?

I couldn't find a test in Akka that restarts the whole cluster (instead of a node/region/shard, which is working fine for me as well), but I am probably not looking in the right place.

There are some rough instructions on how to reproduce the problem in my original post. If the information in this post is not enough to reproduce, I'll look into putting together a simple example, but that will take some time.

**Comment by patriknw** [comment]
ah, I see. That is a bug then. The set of shards are not durable. Thanks for reporting.
