### ISSUE TITLE
IO DNS: Reverse lookups of IPs

### ISSUE THREAD

**Issue by domdorn** [akka/akka#22878]
Hi,

I'm in need of doing reverse lookups of IPs, e.g. 
  `IO(Dns).tell(Dns.Resolve("66.249.80.30"), inbox.getRef())`
or at least
  `IO(Dns).tell(Dns.Resolve("30.80.249.66.in-addr.arpa"), inbox.getRef())`

a DNS server will respond with a PTR record for these cases. 

I created a patch for https://github.com/ilya-epifanov/akka-dns but I'm not sure on how to progress, as it looks like reverse lookups are not supported in the built-in akka-dns client-spec ?
 
at the moment, the built-in akka-dns extension for

```
  val inbox = Inbox.create(system)
  IO(Dns).tell(Dns.Resolve("66.249.80.30"), inbox.getRef())
  println(inbox.receive(5.seconds))

  IO(Dns).tell(Dns.Resolve("30.80.249.66.in-addr.arpa"), inbox.getRef())
  println(inbox.receive(5.seconds))

```
just returns
```
Resolved(66.249.80.30,Vector(/66.249.80.30),Vector())
Resolved(30.80.249.66.in-addr.arpa,List(),List())
```

unix dig returns

> ⇒  dig ptr 30.80.249.66.in-addr.arpa
> 
> ; <<>> DiG 9.8.3-P1 <<>> ptr 30.80.249.66.in-addr.arpa
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22204
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;30.80.249.66.in-addr.arpa.	IN	PTR
> 
> ;; ANSWER SECTION:
> 30.80.249.66.in-addr.arpa. 85978 IN	PTR	google-proxy-66-249-80-30.google.com.
> 
> ;; Query time: 0 msec
> ;; SERVER: 172.31.0.17#53(172.31.0.17)
> ;; WHEN: Tue May  9 15:09:53 2017
> ;; MSG SIZE  rcvd: 93

In general I'm not particularly happy with the answer class "Resolved"
https://github.com/akka/akka/blob/0850fe328f4f83b959aaa86d0de08921c4400314/akka-actor/src/main/scala/akka/io/Dns.scala#L28
as it lacks (imho) vital information like
 - was the dns-lookup successful? 
 at the moment, there's no way to specify, that a dns server did not return a answer (because it could not be  resolved - NXResult ) or the server just didn't answer in time. Also its not possible to get a hold on the underlying answers returned by the DNS Server, as the answer types are abstracted away into the Seq[Inet4Address] and Seq[Inet6Address] 
 - what type are the responses received? what are their TTLs ? 

Please let me know if there are any plans or ideas on improving akka-io dns. I'm fine with just having my own patched version in my project, but having good DNS support in Akka out of the box seems preferable. 

Thanks,
Dominik

**Comment by johanandren** [comment]
We do not have any current plans of doing anything around the DNS support from the Akka team. I agree it has a few shortcomings but I'm not quite sure we'd like to extends the scope of it to a more general purpose DNS client compared to the current one which is more targeted at providing simple-no-toggles-resolution.

**Comment by domdorn** [comment]
thanks for clarifying.
