### ISSUE TITLE
Add examples to Sink.actorRefWithAck and Source.queue docs

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22874]
Clarify how Sink.actorRefWithAck and Source.queue are supposed to be used by adding example code.
http://doc.akka.io/docs/akka/2.5/scala/stream/stream-integrations.html#Integrating_with_Actors

**Comment by patriknw** [comment]
cc @lutzh

**Comment by atiqsayyed** [comment]
@patriknw I wanna pick this up.. It'll be a good thing to start for a beginner like me !

**Comment by patriknw** [comment]
Excellent, thanks

**Comment by BillOTei** [comment]
Any updates on this pls?

**Comment by atiqsayyed** [comment]
@BillOTei I completed this but now when i see the examples I used i'm really not happy with what i did.
I'll improve those docs in next few days, sorry for dragging this.

**Comment by BillOTei** [comment]
thanks, here is a working example using it https://stackoverflow.com/questions/48447646/akka-stream-to-actor-issue/48448043

**Comment by atiqsayyed** [comment]
@BillOTei I've already did something but now after sometime it doesn't look good to me 👎 
I'll try to improve the examples

**Comment by akauppi** [comment]
One realization I had today is "Sink first". 

Too many times I've tried to wrench `Source.queue` to my liking, feeling that something's just not right (it's the need to materialize the source that hurts). By providing a `Sink` parameter (non-materialized), instead, made my code simpler and gave me peace.

I'm not experienced enough to say how often that "upside down" attitude would be right, but it may be worth mentioning in relation to `Source.queue`.

**Comment by ktoso** [comment]
I'll work on the docs today for this 👍

**Comment by ktoso** [comment]
1/2 PRed, the rest soon. Was pulled into other tasks too much this week

**Comment by BillOTei** [comment]
well dumb question but are you checking anything in your receive `receiver` actor method?
here is a working ex with http response https://stackoverflow.com/questions/48447646/akka-stream-to-actor-issue/48448043
do you need the thread sleep?

**Comment by missourian55** [comment]
Thank you for the example, here is my actor code

`@Component
@Scope(SCOPE_PROTOTYPE)
public class AckingReceiver extends AbstractActor {

    private final LoggingAdapter log = Logging.getLogger(getContext().getSystem(), this);

    @Override
    public Receive createReceive() {
        return receiveBuilder()
            .match(StreamInitialized.class, init -> {
                log.info("Stream initialized");
                sender().tell(new Ack(), self());
            })
            .match(String.class, element -> {
                log.info("Received element: {}", element);
                sender().tell(new Ack(), self());
            })
            .match(StreamCompleted.class, completed -> {
                log.info("Stream completed");
            })
            .match(StreamFailure.class, failed -> {
                log.error(failed.getCause(), "Stream failed!");
            })
            .build();
    }

}`

**Comment by missourian55** [comment]
Anyone? If it is a known problem I will move on to a different strategy.

**Comment by raboof** [comment]
@missourian55 interestingly though, your implementation is pretty close to the example at https://doc.akka.io/docs/akka/current/stream/stream-integrations.html?language=scala#sink-actorrefwithack - and I just noticed that has the same problem... so it might in fact be a problem with `actorRefWithAck` (or with the documentation).

**Comment by raboof** [comment]
@missourian55 The problem is that we do `new Ack()` every time, which produces a new, different 'Ack' object each time. Because of that the `new Ack()` from the `AckingReceiver` is not recognized as an acknowledgement and the stream is stuck there. We should definitely update the docs - would you be interested in giving that a try?

**Comment by missourian55** [comment]
Sorry if this is a dump question, so the **Ack** instance at the time if initializing the Sink and one return from **AckingReceiver** should be the same?
You can post the answer in this topic https://discuss.lightbend.com/t/sink-actorrefwithack-not-working/917

**Comment by missourian55** [comment]
@raboof Thanks, your suggestion worked. I maintain a singleton instance of "Ack" for my application.

**Comment by ktoso** [comment]
Solved for 2.5.13

**Comment by raboof** [comment]
Source.queue examples and extra links to Sink.actorRefWithAck added in #25079
