### ISSUE TITLE
Typos in CONTRIBUTING.md and scala/java docs for testing

### ISSUE THREAD

**Issue by iffyio** [akka/akka#22883]
* Item 9 in the "General workflow" section of the contributing guide, "slip though" should be "slip through" while "more lose" should be "more loose"

* In the "Asynchronous Integration Testing with TestKit" section of the testing docs, "ranging for" should be "ranging from"

**Comment by iffyio** [comment]
I have signed the CLA

**Comment by richard-imaoka** [comment]
@iffyio the new docs are ready under the akka-docs directory.

**Comment by Philippus** [comment]
the second bullet was fixed by @raboof in https://github.com/akka/akka/pull/23055

**Comment by raboof** [comment]
All typo's reported in this ticket are indeed now fixed, thanks for the ping!
