### ISSUE TITLE
mapAsync can both failStage and completeStage with a race condition for which will complete the stage

### ISSUE THREAD

**Issue by jrduncans** [akka/akka#22880]
`mapAsync` stage completion doesn't check if a failure (with `Supervision.stoppingDecider`) has occurred, so it can both attempt to `failStage()` and `completeStage`. As far as I can tell there is then a race condition for completing the stream as success or failure, as demonstrated in this program:

```scala
import java.util.concurrent.atomic.AtomicInteger

import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Sink, Source}

import scala.concurrent.duration._
import scala.concurrent.{Await, Future}
import scala.util.{Failure, Success}

object Main extends App {
  implicit val system = ActorSystem("Main")
  implicit val materializer = ActorMaterializer()
  implicit val ec = system.dispatcher

  val successes = new AtomicInteger(0)
  val failures = new AtomicInteger(0)

  for (_ <- 1.to(100)) {
    val input = Seq("a", "b", "c", "d", "e", "f", "g")

    val streamFuture = Source.fromIterator(() => input.iterator)
      .mapAsync(5)(l => Future { if(l == "b") sys.error("no b") else l.toUpperCase })
      .runWith(Sink.seq)

    val f = Await.ready(streamFuture, 10.seconds)

    f.onComplete {
      case Success(_) => successes.incrementAndGet()
      case Failure(_) => failures.incrementAndGet()
    }
  }

  println(s"Successes: ${successes.get()}; Failures: ${failures.get()}")

  system.terminate()
}
```

Running this I get: `Successes: 90; Failures: 10`

**Comment by jrduncans** [comment]
The above pattern of `Source.fromIterator(...).mapAsync(parallelism)(...).runWith(Sink.seq)` is a common replacement for `Future.sequence(list.map(someFutureOp))` to provide bounded parallelism, but given this issue, it doesn't provide the same guarantees in the face of failed futures.

**Comment by ktoso** [comment]
Hi, sorry for the delay and thanks for opening the ticket with reproducer!
I dug into it and you're absolutely correct, it's a failure handling bug.

I have a fix and will submit a PR right away.
