### ISSUE TITLE
Intermittent problem with Distributed Data ORSet and delta-CRDT

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka#22890]
I am using a Distributed Data ORSet on a physical 4 node cluster with Akka 2.5.1.

I am using the ORSet to keep track of which actors (which are sharding entities) are 'alive'. So when the entity receives its first message, it adds its id (a UUID string) to the ORSet:
```replicator ! Replicator.Update(DataKey, ORSet.empty[String], WriteLocal)(_ + id)```
When it gets a shutdown message, it removes the id again:
```replicator ! Replicator.Update(DataKey, ORSet.empty[String], WriteLocal)(_ - id)```

I read the ORSet in two places. One is a local read:
```replicator ! Replicator.Get(DataKey, ReadLocal)```
The other is a ReadAll:
```replicator ! Replicator.Get(DataKey, ReadAll(timeout = 5 seconds))```

Every 5 minutes, I am starting and stopping 30 entities, so spread over the cluster, removing 30 keys from the ORSet, and adding another 30.

This all works fine for a couple of 5 minute periods, but usually after about 15 minutes, for one of the nodes, all the updates (specifically the adds) start failing. The UpdateSuccess message is still sent out, but the value does not show up in the Get's, not even for the ReadLocal on the node on which the Update was performed.

I have reproduced this problem a couple of times on a cluster with 4 physical nodes. I have **not** managed to reproduce the problem on a cluster where all Akka nodes run on the same machine.

The problem goes away if I switch off the delta-CRDT's using:
```akka.cluster.distributed-data.delta-crdt.enabled=off```

**Comment by patriknw** [comment]
@lukas-phaf Thanks for reporting, that is very interesting. It would be very useful if you can reproduce it with `akka.loglevel=DEBUG` enabled. Could generate rather much logs, but we might be able to see what is going on.

Also logs at INFO level could be interesting as a start, if you already have that.

**Comment by lukas-phaf** [comment]
@patriknw, I reproduced the problem with DEBUG log level. But I am afraid I am not comfortable sharing the full log. I have used grep to get just the log output of ddataReplicator and where I add, remove and check the ORSet (these are marked with DDD).

An example where everything is working is storing the ID `8f7b106f-bbae-489a-9ccd-a3f811811d05`, testing it, and later removing it:
```
[INFO] 2017-05-16 13:15:15,566  60050 akka.tcp://dae@sutoldev11673.petrolink.net:2551/system/sharding/Calculation/0/8f7b106f-bbae-489a-9ccd-a3f811811d05 - DDD: Adding 8f7b106f-bbae-489a-9ccd-a3f811811d05
[INFO] 2017-05-16 13:15:15,582  60066 akka.tcp://dae@sutoldev11673.petrolink.net:2551/system/sharding/Calculation/0/8f7b106f-bbae-489a-9ccd-a3f811811d05 - DDD: Update success
[INFO] 2017-05-16 13:19:20,277  304761 akka.tcp://dae@sutoldev11673.petrolink.net:2551/user/supervisor/monitor - DDD: GetSucces, 30 elements: Set(2c3755eb-4313-4c2b-853c-b7667bf47563, fc443cc6-c378-47a6-93a3-8cecfb46884c, 93ff7f37-0794-4d55-96a9-5f0f7fd1069e, e3f92892-a511-4a41-b6b7-d5cef22d1ebd, 5e0930f4-2fe8-4d04-a9f7-b6df9dc7bb54, 9344016c-7022-42ec-b0b4-5d4b9ad1765d, b2da8b0a-07d6-4030-b425-32a81cc709f3, 83b57268-4c8b-412c-b47e-ea9192899e76, 6790f9db-d4fa-4fa6-9047-d296927b3f18, dfb48f4f-77f7-4d52-afb7-a6198a1ff2b3, 524f6dfa-d96b-4081-a8db-4540d824d1f1, 7761e2b2-ec80-4c77-8cf1-2fc4684170d2, 2438ea23-8031-4fbc-add1-da10c2d10f30, 3c8920af-5a56-4e34-9334-1eef607c392b, fdcb4de4-2281-40d6-855b-474ff94bb486, 590b6149-a32e-4de9-8837-961a0bf9c921, 48c954c3-4216-4659-82d3-692b02870861, 8f7b106f-bbae-489a-9ccd-a3f811811d05, 72e1adb4-f6d4-407b-b22a-8c88c86dd5f9, 2767bf64-65e2-41e1-a07a-9f8b73eb01ee, d126b5aa-0443-4b88-8252-bd9eac1e16f8, 470e0f71-79b9-48ad-a0b2-5f855f7cf373, b633b555-ad61-4712-8307-2997cd6f33be, d5d639ac-a568-450c-b712-ce3a59a77083, fbba3bda-efb8-4d60-ad71-1da0733533db, a95d5b66-3700-46f0-a91b-546ca8b4c44c, 9756c94a-9176-4bd6-be90-a858b395c38a, 97bb5d1c-a2bd-4fc5-88b3-ce783c74b20c, b62fc14b-b323-4e98-9d71-2c49c714d69f, 55dac996-224f-497b-94c2-5ae5b429409b)
[INFO] 2017-05-16 13:20:13,827  358311 akka.tcp://dae@sutoldev11673.petrolink.net:2551/system/sharding/Calculation/0/8f7b106f-bbae-489a-9ccd-a3f811811d05 - DDD: Removing 8f7b106f-bbae-489a-9ccd-a3f811811d05
[INFO] 2017-05-16 13:20:13,827  358311 akka.tcp://dae@sutoldev11673.petrolink.net:2551/system/sharding/Calculation/0/8f7b106f-bbae-489a-9ccd-a3f811811d05 - DDD: Update success
```
The `DDD: Update success` message is produced when the actor receives `UpdateSuccess(DataKey, _)`. The `DDD: GetSucces` is produced when the actor receives `GetSuccess(DataKey, _)` as a result of the call `replicator ! Replicator.Get(DataKey, ReadLocal)`. So, in the example above, the id is added to the ORSet, and indeed it shows up when we do a `Get` on the same node. 


If you look in the log extract for the id `a80d8261-72c5-487e-8efe-02a7eecb6ec2`, you will see the update success, but on the next `Get` (4 minutes later), it is not there, even though it was not deleted. You can also see the `ddataReplicator` log messages there. I checked the logs of the other nodes to make sure it is not deleted there (and they shouldn't, as they are shard entities adding their own id's). I see nothing obvious that is wrong compared to the example above where everything is working.

I apologize for not being able to post the full log. I can of course provide output from other actors and/or nodes if needed. If that is not enough, I can try to reproduce in an independent project, but I am afraid that will be rather time consuming.

[akka-11673.log.txt](https://github.com/akka/akka/files/1004888/akka-11673.log.txt)

**Comment by patriknw** [comment]
Thanks, I'll take a look.

Log messages containing "Cluster Node" are usually also good to get some context about things going on in the cluster.

**Comment by lukas-phaf** [comment]
@patriknw Added those.

[akka-11673_2.log.txt](https://github.com/akka/akka/files/1006705/akka-11673_2.log.txt)

**Comment by lukas-phaf** [comment]
Adding a simple example program that shows the problem.

[deltaCRDT.zip](https://github.com/akka/akka/files/1138175/deltaCRDT.zip)

**Comment by lukas-phaf** [comment]
The code above is the simplest example that I could think of that demonstrates the problem with delta-CRDT. It is based on the DataBot example in the Distributed Data documentation. 

It adds and removes letters from an ORSet using WriteLocal. Immediately after the add/remove, it does a ReadLocal, where we expect to get the ORSet including the last operation ('you always read your own writes'). I pass the expected set as the context for the DD Get, so it can easily be compared with the actual response.

I run up to 3 databot nodes in a cluster. Each only touches 8 letters of the alphabet. So even though the nodes share and ORSet, they each have there own elements that they manipulate. For the first node, this is 'a'-'h'. When we check the result of the DD Get, we only look at the letters in the range that the current node is working on. If a difference is detected, and error is logged. I expect the program to run without errors.

The program has a command line argument, which should be 1, 2 or 3. This is used to set the port (2551, 2552 or 2553), and also as input to the DataBot actor to define which letters is should use.

So the test is run by running the application 3 times, using the following commands:
```
sbt "run 1"
sbt "run 2"
sbt "run 3"
```

Using this program, I did some testing to isolate the problem:
- the problem only occurs if delta-CRDT's are used (the default for ORSet). If delta-CRDT's are turned of, there are no errors.
- the problem only occurs if there are at least 3 nodes, I don't see any problems with 2 or less
- it doesn't matter if all nodes are running on a single machine, or on separate machines
- the problem occurs with both Akka 2.5.2 and 2.5.3
- the problem occurs both on Windows and Linux (Rasberry Pi 3 in my testing)
- it looks like the problem is always related to an 'add', not a 'remove'.
- the current test does 100 updates per second per node. The error also occurred with a slower rate of 1 update per second, but it took quite long before it happened (more than 1 hour)

In my testing, and error can occur within 1 minute, or can take up to 20 minutes.
An example is:
```
Port: 2551
[INFO] [07/11/2017 09:28:31.392] [main] [akka.remote.Remoting] Starting remoting
[INFO] [07/11/2017 09:28:31.507] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://deltaCRDT@127.0.0.1:2551]
[INFO] [07/11/2017 09:28:31.514] [main] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Starting up...
[INFO] [07/11/2017 09:28:31.573] [main] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [07/11/2017 09:28:31.573] [main] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Started up successfully
This node uses these letters: Set(e, f, a, b, g, c, h, d)
[INFO] [07/11/2017 09:28:31.594] [deltaCRDT-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Node [akka.tcp://deltaCRDT@127.0.0.1:2551] is JOINING, roles []
[INFO] [07/11/2017 09:28:31.603] [deltaCRDT-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Leader is moving node [akka.tcp://deltaCRDT@127.0.0.1:2551] to [Up]
[INFO] [07/11/2017 09:28:35.498] [deltaCRDT-akka.actor.default-dispatcher-21] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Received InitJoin message from [Actor[akka.tcp://deltaCRDT@127.0.0.1:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#-1545545712]] to [akka.tcp://deltaCRDT@127.0.0.1:2551]
[INFO] [07/11/2017 09:28:35.498] [deltaCRDT-akka.actor.default-dispatcher-21] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Sending InitJoinAck message from node [akka.tcp://deltaCRDT@127.0.0.1:2551] to [Actor[akka.tcp://deltaCRDT@127.0.0.1:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#-1545545712]]
[INFO] [07/11/2017 09:28:35.522] [deltaCRDT-akka.actor.default-dispatcher-21] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Node [akka.tcp://deltaCRDT@127.0.0.1:2552] is JOINING, roles []
[INFO] [07/11/2017 09:28:35.629] [deltaCRDT-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Leader is moving node [akka.tcp://deltaCRDT@127.0.0.1:2552] to [Up]
[INFO] [07/11/2017 09:28:38.204] [deltaCRDT-akka.actor.default-dispatcher-28] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Received InitJoin message from [Actor[akka.tcp://deltaCRDT@127.0.0.1:2553/system/cluster/core/daemon/joinSeedNodeProcess-1#816659886]] to [akka.tcp://deltaCRDT@127.0.0.1:2551]
[INFO] [07/11/2017 09:28:38.204] [deltaCRDT-akka.actor.default-dispatcher-28] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Sending InitJoinAck message from node [akka.tcp://deltaCRDT@127.0.0.1:2551] to [Actor[akka.tcp://deltaCRDT@127.0.0.1:2553/system/cluster/core/daemon/joinSeedNodeProcess-1#816659886]]
[INFO] [07/11/2017 09:28:38.219] [deltaCRDT-akka.actor.default-dispatcher-22] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Node [akka.tcp://deltaCRDT@127.0.0.1:2553] is JOINING, roles []
[INFO] [07/11/2017 09:28:38.588] [deltaCRDT-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://deltaCRDT)] Cluster Node [akka.tcp://deltaCRDT@127.0.0.1:2551] - Leader is moving node [akka.tcp://deltaCRDT@127.0.0.1:2553] to [Up]
[ERROR] [07/11/2017 09:47:35.485] [deltaCRDT-akka.actor.default-dispatcher-4] [akka.tcp://deltaCRDT@127.0.0.1:2551/user/databot] Inconsistent set, DD: Set(f), local: Set(f, c)
[ERROR] [07/11/2017 10:07:55.714] [deltaCRDT-akka.actor.default-dispatcher-21] [akka.tcp://deltaCRDT@127.0.0.1:2551/user/databot] Inconsistent set, DD: Set(e, a, b, c, d), local: Set(e, f, a, b, c, h, d)
[ERROR] [07/11/2017 10:07:55.724] [deltaCRDT-akka.actor.default-dispatcher-33] [akka.tcp://deltaCRDT@127.0.0.1:2551/user/databot] Inconsistent set, DD: Set(e, a, b, c, d), local: Set(e, f, a, b, c, h, d)
[ERROR] [07/11/2017 10:07:55.734] [deltaCRDT-akka.actor.default-dispatcher-33] [akka.tcp://deltaCRDT@127.0.0.1:2551/user/databot] Inconsistent set, DD: Set(e, b, c, d), local: Set(e, f, b, c, h, d)
```

I hope this will help to find the cause of the problem.

**Comment by gosubpl** [comment]
Thanks for the reproducer @lukas-phaf . I will take a look soon.

**Comment by patriknw** [comment]
Thanks for logs and reproducer, @lukas-phaf 
Sorry that it took so long to investigate this, I'll try to give it some attention now.
I have an "Inconsistent set" output from running the app.

**Comment by patriknw** [comment]
Sharing some observations from today's debugging. I was able to reproduce with some additional logging that is interesting.

For one run f and d are gone missing:
```
[ERROR] [08/21/2017 15:32:02.224] [deltaCRDT-akka.actor.default-dispatcher-27] [akka.tcp://deltaCRDT@127.0.0.1:2551/user/databot] Inconsistent set, DD: Set(e, a, g), local: Set(e, f, a, g, d)
```

Right before the update it Received gossip from akka.tcp://deltaCRDT@127.0.0.1:2553. The incoming gossip contains:
```
ORSet(Map(
  e -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46020), 
  s -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45743), 
  x -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45739), 
  u -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45744),
  f -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46021), >>> NOTE f included here
  a -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46018), 
  m -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45880), 
  v -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45742), 
  q -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45741), 
  c -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46015), 
  w -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45738), 
  k -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45881)), 
VersionVector(
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46039, 
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45881, 
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45744))
```
The existing local data is:
```
ORSet(Map(
  e -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46040), 
  f -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46033), >>> NOTE f included here
  a -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46041), 
  m -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45880), 
  q -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45722), 
  g -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46042), 
  h -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46036), 
  k -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45881), 
  d -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46035)), >>> NOTE d included here
VersionVector(
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46042, 
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45881, 
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45725))
```
Merging those result in loss of `d` and `f`:
```
ORSet(Map(
  e -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46040), 
  s -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45743), 
  x -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45739), 
  u -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45744), 
  a -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46041), 
  m -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45880), 
  v -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45742), 
  q -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45741), 
  g -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46042), 
  w -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45738), 
  k -> VersionVector(UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45881)), 
VersionVector(
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46042, 
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2552,-407935375) -> 45881, 
  UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2553,230956674) -> 45744))
```

Note that the the vvector entry in the incoming is 46039, but I think the elements `f` and `d` are not included with the "right" dot.

The test is only adding/removing these entries `e, f, a, b, g, c, h, d` in the set from one node, the 2551 node. Other nodes operate on other entries in the set.

**Comment by gosubpl** [comment]
@patriknw can you please share the test code you have used to reproduce this?

**Comment by patriknw** [comment]
@gosubpl It's the deltaCRDT.zip that @lukas-phaf attached above.
Added akka.loglevel=DEBUG to application.conf and changed dependency to akka 2.5.4.

My additional logging is in branch: https://github.com/akka/akka/tree/wip-22890-deltaCRDT-debug-patriknw
akka `publishLocal` and the dependency in example app changed to 2.5-SNAPSHOT

**Comment by gosubpl** [comment]
Yes, this should not be possible, as the `vvector` is `UniqueAddress(akka.tcp://deltaCRDT@127.0.0.1:2551,1242250038) -> 46039`, then `f` should have a version of `46033` and `d` should be present. Also `h` is missing. The histories must have diverged earlier, as since `46039` the only operations were additions of `e` (`40640`), `a` (`40641`) and `g` (`40642`) (and possibly some removals). For me there is something wrong with the `vvector` version of `46039` in the incoming gossip. Logging the "birth" and removal dots should shed more light on it. I will investigate.

**Comment by patriknw** [comment]
thanks for investigating, Sherlock

**Comment by gosubpl** [comment]
thanks :) `println` to the rescue!

**Comment by gosubpl** [comment]
@lukas-phaf would be great if you could check if this solves the problem with your real application, not the toy example :)

**Comment by lukas-phaf** [comment]
Thanks for looking into this. I will try to test with the real application as soon as possible.

**Comment by lukas-phaf** [comment]
Short answer: Yes, it solves the problem in the real application as well.

Long answer:
All testing done on a four node cluster of physical machines.

I started with Akka master branch (gosubpl's fork to be precise), and built our code against that. I first ran this with deltaCRDT's turned **off**, to make sure our code runs against Akka master. I ran this for an hour, everything was fine.

I then changed the config to turn **on** deltaCRDT's. It failed within 5 minutes. This confirmed that the problems still exists in the master branch.

I then switched Akka to the 'gosubpl:wip/22890-fix-orset-mergeremovedelta' branch, rebuilt Akka, and built our application against it. Then I ran this with deltaCRDT's turned **on**. This is running fine for an hour now.

It does 400 adds and 400 removes per 5 minutes, distributed over the 4 nodes. I'll leave this running for a couple of days just to make sure, but so far I can conclude the fix from @gosubpl works.

Thanks a lot!

**Comment by gosubpl** [comment]
@lukas-phaf many thanks for checking this so quickly. Let me know how things worked out in longer run.

Additionally, a great many thanks for being early adopter of deltaCRDTs and unfortunately shouldering some pain. Also, thank you for excellent bug report and a reproducer.

**Comment by lukas-phaf** [comment]
Still fine after 24 hours...

**Comment by patriknw** [comment]
Thanks for testing, very valuable.

**Comment by lukas-phaf** [comment]
Still fine after 6 days. I am calling this test successful..
