### ISSUE TITLE
cluster-sharding: tiny memory leak in akka.cluster.sharding.Shard.idByRef

### ISSUE THREAD

**Issue by nikitapecasa** [akka/akka#22893]
Hi,

From the source code it looks like there is a tiny memory leak in `akka.cluster.sharding.Shard.idByRef` map.
It happens when `rememberEntities` is enabled and entity is stoped unintentionally (e.g.: persistent failure stoped the actor), then entity is restarted with `Shard.RestartEntity` command, and `Shard.getEntity` is called, which won't remove terminated `ActorRef` from `idByRef` map.

As for the fix, may be it would make sense to always remove old ActorRef in `Shard.getEntity` method.

I might be missing something here, as I haven't tested the issue explicitly, so please correct me if I'm wrong.

Regards,
Nikita.

**Comment by patriknw** [comment]
@nikitapecasa Thanks for reporting. I think that is an oversight. I see no reason why it should linger around after termination. Suggested fix in PR https://github.com/akka/akka/pull/22951
