### ISSUE TITLE
Rewrite the quickstart part of Getting Started

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22900]
http://doc.akka.io/docs/akka/new-docs-snapshot/scala/guide/quickstart.html

Should use/link to https://github.com/akka/akka-scala-seed.g8/pull/4
probably via http://developer.lightbend.com/start/?group=akka

Note that the guide in akka-scala-seed will be published at developer.lightbend.com, e.g. http://developer.lightbend.com/guides/hello-akka/

**Comment by patriknw** [comment]
cc @henrikengstrom

**Comment by patriknw** [comment]
I'm taking a stab at this

**Comment by henrikengstrom** [comment]
Great.
