### ISSUE TITLE
failed: DeviceGroupTest

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22918]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9141/testReport/junit/jdocs.tutorial_4/DeviceGroupTest/testListActiveDevicesAfterOneShutsDown/

**Comment by raboof** [comment]
Looks like a proper race condition to me: there's no guarantee that the groupActor has receives the termination before the test receives the termination and sends the `RequestDeviceList`.

We could cheat and use an 'eventually' block or insert a sleep but that's not very nice.

It might be nice to be able to ask the dispatcher (perhaps a custom one?) to make sure we don't continue before it becomes idle. Is that currently possible?
