### ISSUE TITLE
Bug in sharding snapshot deletion code

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka#22916]
When running an actor system using sharding, after some time I get the following crash:
```[ERROR] [05/12/2017 02:27:28.282] [dae-akka.actor.default-dispatcher-62] [akka.actor.LocalActorRefProvider(akka://dae)] guardian failed, shutting down system
scala.NotImplementedError: extractEntityId: DeleteSnapshotsSuccess(SnapshotSelectionCriteria(999,9223372036854775807,0,0))
```

I think the problem is in Shard.scala (and also in ShardCoordinator.scala):
```
case DeleteMessagesSuccess(toSequenceNr) ⇒
      log.debug("PersistentShard messages to {} deleted successfully", toSequenceNr)
      deleteSnapshots(SnapshotSelectionCriteria(maxSequenceNr = toSequenceNr - 1))

    case DeleteMessagesFailure(reason, toSequenceNr) ⇒
      log.warning("PersistentShard messages to {} deletion failure: {}", toSequenceNr, reason.getMessage)

    case DeleteSnapshotSuccess(m) ⇒
      log.debug("PersistentShard snapshots matching {} deleted successfully", m)

    case DeleteSnapshotFailure(m, reason) ⇒
      log.warning("PersistentShard snapshots matching {} deletion falure: {}", m, reason.getMessage)
```

After a `DeleteMessagesSuccess`, `deleteSnapshots` (plural) is called, but only `DeleteSnapshotSucces` (singular) message is handled. I think this should be `DeleteSnapshotsSuccess` (plural). The same holds for `DeleteSnapshotFailure`. If I understand correctly, this is why the message leaks out.

Can someone confirm this is the problem? I can make a PR if that helps.

I think the above explains the message leaking out. The reason that I get a guardian failure is that I have:
```
  val extractEntityId: ShardRegion.ExtractEntityId = {
    ...
    case unknown => throw new NotImplementedError(s"extractEntityId: $unknown")
  }
```
Probably not a good idea...

**Comment by patriknw** [comment]
Sounds like a bug and you know how to fix it. Would you be able to open a pull request @lukas-phaf ?

**Comment by lukas-phaf** [comment]
Yes, will do that.
