### ISSUE TITLE
RecoverWith should recover for maximumRetries == 0

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#22917]
When calling `recoverWithRetries` it is valid to pass 0 for `maximumRetries`. Which makes total sense if one doesn't want to retry but just recover. Yet if one passes 0, recovery doesn't take place:

``` scala
    Source
      .failed[Int](new Exception("BOOM"))
      .recoverWithRetries(0, { case _ => Source.single(42) })
      .runForeach(println)
      .onComplete { t =>
        println(s"done: $t")
        system.terminate()
      }
```

This doesn't print "42" and "done: Success(Done)" but "done: Failure(java.lang.Exception: BOOM)".

Inspecting the code of `RecoverWith` it seems that `attempt < maximumRetries` should be `attempt <= maximumRetries`.

**Comment by hseeberger** [comment]
Thanks to @johanandren for bringing this up!

**Comment by johanandren** [comment]
do you still think we should fix something here @hseeberger (I'm thinking return identity stage or possibly require retries to be > 0)

**Comment by hseeberger** [comment]
I think I was wrong, not understanding that recovery (once or more times) means evaluating the given PF and using the potential result. So given that it is valid to use -1 as a parameter I suggest to allow any parameter less than 1 for `maximumRetries`, e.g. 0, -1 or -42, to indicate infinite retries.

**Comment by johanandren** [comment]
ah, currently that is specifically only `-1` it seems. I agree making 0 and less infinite sounds reasonable.

**Comment by ktoso** [comment]
I'll give this a look then
