### ISSUE TITLE
Blocked script execution in jenkins preview

### ISSUE THREAD

**Issue by 2m** [akka/akka#22931]
Code snippets are [separate blocks](https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9153/artifact/akka-docs/target/paradox/site/main/java/guide/tutorial_1.html#structure-of-an-actorref-and-paths-of-actors).

**Comment by raboof** [comment]
Hmm this worked locally, but when served apparently we're running into:
```
Blocked script execution in 'https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9153/artif…in/java/guide/tutorial_1.html#structure-of-an-actorref-and-paths-of-actors' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

**Comment by patriknw** [comment]
yes, this rendering fine for me locally

**Comment by raboof** [comment]
http://stackoverflow.com/questions/34315723/blocked-script-execution-in-url-because-the-documents-frame-is-sandboxed-and looks like this might be jenkins configuration, looking at it

**Comment by 2m** [comment]
Ahh, I see that it is like this everywhere not only in Getting Started guide. Also syntax highlighting is gone because of the same reason.

**Comment by 2m** [comment]
I have set the system property recommended in the SO answer from the Jenkins init file.
