### ISSUE TITLE
Show introduction on a topic after clicking top level link from TOC

### ISSUE THREAD

**Issue by 2m** [akka/akka#22930]
When clicking on *Streams* top level link a [TOC page opens](https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9153/artifact/akka-docs/target/paradox/site/main/java/stream/index.html). Instead the [introduction chapter](https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9153/artifact/akka-docs/target/paradox/site/main/java/stream/stream-introduction.html) could open.

**Comment by patriknw** [comment]
I think that was on purpose and I think it's nice

but it's strange that there are no such boxes for Getting Started Guide

**Comment by 2m** [comment]
Yea. Also noticed that.

On the other hand this would make it impossible to go directly to a topic that is deeper than 2nd level. I guess I need to get a bit more time with the new docs.
