### ISSUE TITLE
Avoid empty pages when user clicks on a main "chapter"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22949]
For example if someone goes to main docs site for scala, and then clicks "yeah getting started, that sounds good!" and clicks it they'll get: http://doc.akka.io/docs/akka/snapshot/scala/guide/index.html an empty page.

We should perhaps have those include something to not look so blank?

**Comment by patriknw** [comment]
It should show toc boxes as the other chapters, it was missing toc depth tag.

**Comment by ktoso** [comment]
Cool, thanks for fixing right away!

**Comment by patriknw** [comment]
it annoyed me too
