### ISSUE TITLE
add SupervisionStrategy.stop

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22943]
For completeness we should add `Supervision.stop`. Can be useful when nesting several strategies, e.g. `stop` for `IllegalStateException` and `restart` for all other `RuntimeException`.

**Comment by chbatey** [comment]
I'll add this but i think it is just a noop given it is the same as the default? Some may prefer to see it explicitly

**Comment by johanandren** [comment]
This is done, right?

**Comment by chbatey** [comment]
Yep
