### ISSUE TITLE
Source.combine method should keep Materialized Values

### ISSUE THREAD

**Issue by synox** [akka/akka#22950]
Source.combine() does not keep the Materialized Values Attributes, it always returns 
    Source[U, NotUsed]. It forces me to use the GraphDSL even for such a simple Graph. 

I would like to use Source.combine()  and be able to define how to handle the Materialized Values. 

Example actual: 

        Source<Integer, SourceQueueWithComplete<Integer>> queuePrimary = Source.queue(2000, OverflowStrategy.backpressure());
        Source<Integer, SourceQueueWithComplete<Integer>> queueSecondary = Source.queue(2000, OverflowStrategy.backpressure());

        Source<Integer, NotUsed> oneQueue = Source.combine(queuePrimary, queueSecondary, new ArrayList<>(), i -> Merge.<Integer> create(i));
                        ^^^^^^^^ 

Example expected: 

        Source<Integer, Pair<SourceQueueWithComplete<Integer>,SourceQueueWithComplete<Integer>>> oneQueue = Source.combine(queuePrimary, queueSecondary, i -> Merge.<Integer> create(i), Keep.both());
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See also #22452 for more API changes.

**Comment by johanandren** [comment]
Combine is a varargs method and can combine any number of sources, which each of can have a separate materialised value type so that would not be possible. 

Maybe we could follow the pattern of `FlowOpsMat` though and add `combineMat(s1, s2)((M1, M2) => M)` specifically for combining two sources.

**Comment by richardimaoka** [comment]
Working on this
