### ISSUE TITLE
Long GC pauses while running tests on jenkins

### ISSUE THREAD

**Issue by raboof** [akka/akka#22979]
Let's track build problems due to long GC pauses on jenkins here.

For example: https://jenkins.akka.io:8498/job/akka-nightly/4399/consoleFull

```
[Full GC (Metadata GC Threshold)  1858M->616M(3072M), 4.9998215 secs]
[Eden: 491.0M(618.0M)->0.0B(1484.0M) Survivors: 47.0M->0.0B Heap: 1858.2M(3072.0M)->616.1M(3072.0M)], [Metaspace: 503452K->480555K(1490944K)]
 [Times: user=6.34 sys=0.41, real=5.00 secs] 
[info] - demonstrate programmatic deployment *** FAILED *** (5 seconds, 272 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorRef
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4405/consoleFull

```
[Full GC (Metadata GC Threshold)  2395M->587M(3072M), 4.7383619 secs]
   [Eden: 1056.0M(1240.0M)->0.0B(1619.0M) Survivors: 41.0M->0.0B Heap: 2395.7M(3072.0M)->587.2M(3072.0M)], [Metaspace: 503419K->481159K(1490944K)]
 [Times: user=6.41 sys=0.03, real=4.74 secs] 
[info] - demonstrate programmatic deployment *** FAILED *** (4 seconds, 817 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorRef
```

**Comment by patriknw** [comment]
We set the `-XX:MetaspaceSize=768M`, which is the initial size. Strange that it have to do Full GC.

Maybe we have to set more flags to "turn off" any dynamic shrinking?

```
-XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=1024m -XX:MinMetaspaceFreeRatio=0 -XX:MaxMetaspaceFreeRatio=100
```

http://stackoverflow.com/questions/25251388/what-is-the-metadata-gc-threshold-and-how-do-i-tune-it

**Comment by johanandren** [comment]
Trying to go for forked tests to avoid this class-loader-leakage-related problems all together

**Comment by johanandren** [comment]
When the forked tests are merged we should remember to remove the print-gc-stat flags to sbt because we don't really care about how much time sbt spends in gc anymore when the tests are separate.

**Comment by johanandren** [comment]
I have updated all needed jenkins jobs now.
