### ISSUE TITLE
Flow tuple projections

### ISSUE THREAD

**Issue by jroper** [akka/akka#22975]
There is a common scenario that we've encountered in Lagom, where either we (the framework) or the user needs to project a flow of tuples to the left or right side, perform an operation on it, and then merge back with the other side. A common use case for this is when you want to process a flow of messages and offset tuples, and you need to emit the offset such that offset tracking can be done. It's not hard to implement this, however there is a serious but non obvious bug that most naive implementations would have (in fact Lagom had this in its own code).

There is a generalised form of this operation which works at a level higher than tuples, but for simplicity, let's just make it about tuples.

So, say we created a `projectLeft` method on Flow, it might look like this (excluding materialized value type parameters for brevity):

```scala
def projectLeft[LA, LB, R](projectionFlow: Flow[LA, LB]): Flow[(LA, R), (LB, R)]
```

The easiest way to implement this is to unzip the `(LA, R)` tuple, send the `LA` side through `projectionFlow`, and then zip up the `(LB, R)` tuple. It looks like this:

```scala
def projectLeft[LA, LB, R](projectionFlow: Flow[LA, LB]): Flow[(LA, R), (LB, R)] = {
  Flow.fromGraph(GraphDSL.create(projectionFlow) { implicit builder => projectionFlow =>
    import GraphDSL.Implicits._

    val unzip = builder.add(Unzip[LA, R])
    val zip = builder.add(Zip[LB, R])

    unzip.out0 ~> projectionFlow ~> zip.in0
    unzip.out1 ~> zip.in1
    FlowShape(unzip.in, zip.out)
  })
}
```

Simple enough, perhaps a little too much boilerplate for a common operation, but the real problem is that there is a major bug in the above code, can you see it?

What if I do one of the following:

```
projectLeft(Flow.mapAsync(8)(Future.successful))

projectLeft(Flow.grouped(8).mapConcat(identity))
```

What's wrong with these two bits of code? The first one will only execute with a parallelism of 1 (ie, the passed in parallelism to `mapAsync` is effectively ignored), and the second will hang, it will backpressure after receiving the first element and never emit any elements. The reason for the bug is that there is no buffer between the out of the unzip, and the in of the zip on the right side. And so the problem here is that I think this is a common use case, and because the bug is non obvious, it will be a very common bug that developers will inject into their own code, and it won't be obvious what the problem is when they try to debug it.

So I think Akka streams should offer `projectLeft` and `projectRight` methods on `Flow` for tuples (easy to do in Scala directly on `FlowOps` using type constraints, may need to be implemented as static methods using a similar signature to the method above in Java). The methods would take a buffer parameter to specify how much the opposite side of the projection should buffer before back pressuring. It may also make sense to allow passing an overflow strategy, not sure.

**Comment by jroper** [comment]
Related: https://github.com/lagom/lagom/pull/752

**Comment by jroper** [comment]
A generalized `project` method could also be created, which could be easily used to implement `projectLeft` and `projectRight`:

```scala
trait FlowOps[Out] {
  def project[A, B, T](buffer: Int, project: Out => A, unproject: (B, Out) => T)(projectionFlow: Flow[A, B]): Repr[T]

  // Then projectLeft would be implemented like:
  def projectLeft[LA, LB, R](buffer: Int)(projectionFlow: Flow[LA, LB])(implicit ev Out <:< (LA, R)): Repr[(LB, R)] = 
    project(buffer, _._1, (b, out) => (b, out._2))(projectionFlow)
}
```

**Comment by johanandren** [comment]
Discussed previously in #15957 and akka/akka-streams-contrib#50

**Comment by johanandren** [comment]
I think this is now solved by the `WithContext` APIs
