### ISSUE TITLE
with test transport plugin distributed-data throws exception on getting a port in LmdbDurableStore

### ISSUE THREAD

**Issue by kpbochenek** [akka/akka#22977]
With configuration used for testing:
```
  akka {
  remote {
    enabled-transports = ["akka.remote.test"]
    test {
      transport-class = "akka.remote.transport.TestTransport"
      local-address = "test://ActorSystemTest"
      applied-adapters = []
      registry-key = "test-transport-registry"
      maximum-payload-bytes = 320000
      scheme-identifier = "test"
    }
  }
}
```

There is no port defined as it is not needed.
But in LmdbDurableStore:
https://github.com/akka/akka/blob/3ab101039fd14d7bea92c4e14d2c809a60b00229/akka-distributed-data/src/main/scala/akka/cluster/ddata/DurableStore.scala#L128

We explicitly call `.get` on Option which is None in this case.
This throws exception and causes distributed-data not to initialize correctly.

**Comment by patriknw** [comment]
You can't use distributed data without a cluster so I'm not sure what you are trying to do here. I would not set the test transport manually, but only use that together with multi-jvm tests, as we do in many of Akka's tests. E.g. https://github.com/akka/akka/blob/master/akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata/ReplicatorChaosSpec.scala#L30

**Comment by kpbochenek** [comment]
I am using sharding but for some tests I want to have just single node and ignore all clustering.

That's why I provide this configuration for testing and also
```
akka.cluster.seed-nodes = ["akka://ActorSystemTest"]
akka.cluster.client.initial-contacts = ["akka://ActorSystemTest/user/receptionist"]
```

Worked perfectly for akka 2.4 but when I try to migrate to 2.5 I hit mentioned issues.

I also tried to set `lmdb.dir` to different value which should be a workaround but for some strange reason this is not picked up, I have to investigate.

Or is there an alternative store that keeps data only in memory?

**Comment by patriknw** [comment]
Using a real single node cluster seems more safe to me.

Setting the `lmdb.dir` to something not ending with "ddata" should avoid the issue. Make sure you use 2.5.1, we fixed something here.

Also note that if you are using cluster sharding, it is using it's own ddata replicator with another config path, see reference.conf in cluster-sharding.

**Comment by kpbochenek** [comment]
thanks!
I changed `lmdb.dir` to be in scope of cluster-sharding and it helped :D
