### ISSUE TITLE
Rename Actor.restarter to Actor.supervisor

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#22970]
Why? Well, `Actor.restarter[Foo](SupervisorStrategy.resume)` doesn't make sense, right?

**Comment by hseeberger** [comment]
Or maybe `Actor.supervise[...](...)`

**Comment by patriknw** [comment]
I was also thinking about naming it something like that, but never decided. Thanks for feedback.

**Comment by patriknw** [comment]
I think `supervise` reads best

**Comment by ktoso** [comment]
supervise reads great, thanks for the suggestion - on it.
