### ISSUE TITLE
Download failures during jenkins builds

### ISSUE THREAD

**Issue by raboof** [akka/akka#22980]
Let's track build problems due to download failures here.

It seems some jobs were using the artifactory at https://proxy-ch.typesafe.com:8082 (via `-Dsbt.override.build.repos=true` and `~/.sbt/repositories.conf`), but without also configuring credentials, which means it'd successfully fetch resources already known to artifactory but not add new ones.

For now I've configured `akka-nightly` to use `-Dsbt.override.build.repos=false` just like pr-validation.

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2088/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-publish-nightly/675/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4417/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/211

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-sigar/608/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4418/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4418

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4419/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4918

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4420

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2091

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4421

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-publish-nightly/676

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4920

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/212

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-sigar/609

**Comment by raboof** [comment]
Etc:

https://jenkins.akka.io:8498/job/akka-nightly/4422
https://jenkins.akka.io:8498/job/akka-nightly/4423
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4921
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4922
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/626
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/627

Sorry about the notification spam :).

Thinking about this: perhaps there is one jenkins node/job on which artifactory does work for new artifacts (and is that the reason why this wasn't such a big problem before), but won't that one find the resources in @2m's repo either, causing all builds to fail.

**Comment by patriknw** [comment]
@raboof is this fixed now?

**Comment by raboof** [comment]
I think so, let's close and re-open when we see problems in this area again.

**Comment by johanandren** [comment]
For the record I today completely disabled jenkins sbt using the proxy now, since the cert has passed best before and there no longer is a public DNS record so no longer possible to use letsencrypt for the cert.
