### ISSUE TITLE
Paradox page generation not working on Windows, due to Linux-style symlinks

### ISSUE THREAD

**Issue by richard-imaoka** [akka/akka#22986]
[akka-docs/src/main/paradox/java](https://github.com/akka/akka/tree/8f2de2a0ac9133f5b7c11e66fb17c6e1f84df697/akka-docs/src/main/paradox/java) has symlinks like common, general, etc.

However, they don't work on Windows, so I got errors like below.

> akka-docs > paradox
> [trace] Stack trace suppressed: run last akka-docs/compile:paradoxMarkdownToHtml for the full output.
> [error] (akka-docs/compile:paradoxMarkdownToHtml) com.lightbend.paradox.markdown.Index$LinkException: **Unknown page [common/cluster.md] linked from [java/index-network.md]**
> [error] Total time: 9 s, completed May 20, 2017 5:57:00 AM

**Comment by richard-imaoka** [comment]
As discussed with @raboof in the above [commit](https://github.com/richard-imaoka/akka/commit/b341e127f3c7e74cc81f4eba5bc208a53256c4bd#commitcomment-22215622), when moving the following directories under paradox/scala to one level upper, the `@@toc` directives did not work.

- additional
- common
- general
- guide
- project
- security 

I think we need to duplicate the above directories in paradox/java too. Otherwise, I need some advice from paradox experts.

**Comment by patriknw** [comment]
Could we/you add corresponding windows symlinks? I don't know the command, perhaps mklink?

**Comment by richard-imaoka** [comment]
Hmm does that mean the steps to generate paradox pages on Windows would be:

1.  git pull akka
2. run some script to replace symlinks created from Linux with Windows symlinks
3. sbt akka-docs/paradox

am I correct? 

I briefly looked at [this question in StackOverflow](http://stackoverflow.com/a/16754068) which we might be able to use for the step 2. 

If we do this, for new comers to akka, it might be little unclear and they might be tempted to raise questions or GitHub issues when they skip 2. unknowingly, and encounter paradox errors.

**Comment by raboof** [comment]
Perhaps we should add a note to `CONTRIBUTING.md` describing how to build the docs on windows for now?

The longer-term goal here is to stop duplicating documentation entirely, and use switches to include both the Java and Scala variations in the same markdown files (with [groups](http://developer.lightbend.com/docs/paradox/latest/features/groups.html)).

**Comment by richard-imaoka** [comment]
Okay for now let me try to add description for Windows in contributing.md. 

Are we switching to paradox entirely in ver. 2.5.2? Wondering if there is a chance combining Java and Scala with groups **before** switching to paradox from rst, which I think might make the consolidation bit easier.

**Comment by raboof** [comment]
Yes, 2.5.2 will be released from master which as you've seen has been moved to paradox. We can now gradually, on a page-by-page basis, start merging Java and Scala pages using groups (for example [this page](http://doc.akka.io/docs/akka/snapshot/java/guide/tutorial_2.html) has already been set up like this). Switching between Java and Scala (also when generated from the same markdown) will remain a page refresh until we've finished moving everything to groups.

Merging pages will be quite a bit of work, and this approach allows us to do it step by step. The (admittedly kind-of-awkward) symlinks seem to be a relatively small price to pay for this ability. Help is certainly welcome!

**Comment by patriknw** [comment]
Yes, we have already switched, and it will be released with 2.5.2. No way we the windows symlinks can be checked in to git? Otherwise we can perhaps run the script from sbt when on windows, or have the bat script create the symlinks and then run sbt akka-docs/paradox, so that there is just one command to build the docs.

**Comment by johanandren** [comment]
What about the support for symlinks in `git scm` for windows described here? http://stackoverflow.com/a/42137273

**Comment by richard-imaoka** [comment]
Thanks all for the quick feedback and advice! 

I submitted the above PR with a link to the StackOverflow page which @johanandren gave.

**Comment by richard-imaoka** [comment]
One suggestion - for combining Java and Scala pages one by one, what if we crate a master issue like #20466 **Great getting started ticket: write example snippets for Akka HTTP Java DSL** ? The the community people would feel easier to work on.

If that sounds ok, I can try to create the description of the master issue, explaining steps to convert `.md` files under `/java` to the unified scala/java page.
