### ISSUE TITLE
Memory leak in the Artery actor ref cache

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22990]
I can't remember if this was something we decided to live with or if we missed the fact that the `ActorRef` cache keeps actor refs in memory after they have terminated. Was reported by @bitsofinfo here: https://gitter.im/akka/akka?at=591d01872b926f8a6767c524 and here https://gitter.im/akka/akka?at=591f196500efc2bb3e84151d as a leak of the `ClusterRouterGroup`.

This is a screenshot of the heap dump view @bitsofinfo provided (here: https://github.com/bitsofinfo/akka-debugging/tree/master/20170519a-question)
<img width="1576" alt="screen shot 2017-05-21 at 11 23 51" src="https://cloud.githubusercontent.com/assets/666915/26282762/0990f27a-3e18-11e7-8f3d-9be05fb91f8c.png">

**Comment by patriknw** [comment]
The cache is bounded (oldest will be evicted) and the references are not supposed to hold on to much memory after termination so I'm not sure this is a problem.

**Comment by johanandren** [comment]
@bitsofinfo could you tell us if you really observed memory problems because of this or just was confused that it was kept alive?

**Comment by bitsofinfo** [comment]
Not yet determined if the causing of my issue (OOM) I've since turned off akka clustering to cut the issue in half..... but I noticed these are not being cleaned up after GCs... and it caught my eye. Why retain this stuff in memory? Over time eventually this would grow.

**Comment by johanandren** [comment]
The cache is a LRU of the remote actorrefs so eventually those will be evicted as messages are sent to other remote actors. Evicting earlier is complicated since the refs are remote and watching each one of them would introduce considerable overhead.

**Comment by patriknw** [comment]
It should also be noted that there should not be any references left to instances of your `Actor` classes. The remaining `ActorRef` instances should be shallow and not consume much memory.

**Comment by patriknw** [comment]
closing, doesn't seem to be a real problem
