### ISSUE TITLE
Stateful Split in streams

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka#23005]
I've discovered little flaw in splitting stream, as I think. I suggest to make it to be able to accept stateful trait that can be implemented be its users. something like:
```scala
trait Splitter[T]{
 //all elements go through this method, allowing Splitter to accumulate the state
 def splitAtThisElem(elem: T): Boolean
}
```
This can cover scenarios where you need to compare next element with previous to make split decision and other where you need to accumulate state.

If you will agree that it will be useful, I can try to implement it.

**Comment by raboof** [comment]
Hi @manonthegithub, where did you see a flaw?

The easiest way to 'split' a stream might be to use the partitioning `GraphStage`, http://doc.akka.io/api/akka/current/akka/stream/scaladsl/Partition.html . Does that solve your problem?

**Comment by manonthegithub** [comment]
@raboof by splitting I meant using `FlowOps.splitWhen` or `FlowOps.splitAfter`, which return `SubFlow`. You supply `(elem) => boolean` to `splitWhen`/`splitAfter` to do splitting, but if it is stateful it's not safe because it will be shared between different materialisations.

**Comment by raboof** [comment]
I see what you mean. Perhaps this would be one for https://github.com/akka/akka-stream-contrib ?

**Comment by manonthegithub** [comment]
Yep, I agree
