### ISSUE TITLE
distributed-data: VersionVector using in memory counter

### ISSUE THREAD

**Issue by shangd** [akka/akka#23008]
Hi, I got a question regarding the VersionVector implementation in distributed-data
https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/VersionVector.scala#L76

The VersionVector gets incremented using a global static in-memory AtomicLong, my understanding is that this ensures the total ordering of updates at the same address so that conflicts can be merged. 

My question is that what happens if the JVM gets restarted? The counter would get reset and further increment calls could actually reset the version? Wouldn't this cause the merge with previous versions incorrect?

**Comment by patriknw** [comment]
It's always used together with the UniqueAddress of the node, which is hostname:port:UID. After restart it will be different, i.e. a new node.

**Comment by eli-jordan** [comment]
@patriknw I'm curious why this approach is preferred over simply incrementing the counter in the versions map for the current node.

**Comment by patriknw** [comment]
Because it must also survive restarts (and stop/start) of the `Replicator` actor without starting from zero when just restarting that actor and not the whole ActorSystem.

**Comment by eli-jordan** [comment]
Thanks or the reply @patricknw . I'm not sure if what I said was clear though... what I was referring to, is why does the version vector in distributed data use a different counter increment strategy than in the vector clock in akka cluster I.e. https://github.com/akka/akka/blob/master/akka-cluster/src/main/scala/akka/cluster/VectorClock.scala#L79

The vector clock in akka-cluster simply increments the value in the slot for the current node, whereas the version vector in distributed data uses a jvm global counter. The akka cluster version seems more inline with the literature, and I was curious about the reason for having a global counter.

**Comment by patriknw** [comment]
Thanks for clarifying. The reason is still what I already said. The `ClusterDaemon` can't be restarted, so there it's no problem.

For ddata you might update a `GCounter` to A-3, and then stop the `Replicator` and start it again, and then increment the counter which would then get A-1 but there is already another A-3 out there on another node and when those are merged the last update (A-1) would be lost.

**Comment by eli-jordan** [comment]
Thanks for being patient, I'm a noob with this stuff ;-)

I get the problem now, thanks for clarifying. I was assuming that the data was persisted. So in your example the GCounter would still be at A-3 after actor restart, or jvm restart. But upon further reading I realise this is only the case for specifically configured keys.

**Comment by patriknw** [comment]
cool, I guess we can close this then

**Comment by shangd** [comment]
@patriknw Thanks for the replies, makes sense to me now. 

I was thinking from a concurrency perspective that maybe the global atomic counter was necessary because otherwise 2 concurrent updates may create 2 different data values with the same version and then the merge will become non-deterministic. I guess the akka cluster `VectorClock` which uses local instance counter won't have this problem since there is only one actor updating it and there is no concurrency?

**Comment by patriknw** [comment]
Good thinking. It's not needed for concurrency reasons. In cluster it's only used by the ClusterDaemon actor and in ddata only by the Replicator actor (the modify function of the Update message is invoked by the Replicator actor)
