### ISSUE TITLE
Link to conductor from deployment options page in the docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23022]
I think we should have a short text about conductr being an option for deployment, and a link to their docs, in the Use-case and deployments section of the docs.

**Comment by johanandren** [comment]
This is the page I'm talking about:
http://doc.akka.io/docs/akka/2.5.1/intro/deployment-scenarios.html

Could be nice with other deployment options mentioned as well.

**Comment by ktoso** [comment]
Let's just link to https://conductr.lightbend.com/docs/2.0.x/DevQuickStart for now
