### ISSUE TITLE
Provide an easy way to switch to the most recent version of the docs

### ISSUE THREAD

**Issue by raboof** [akka/akka#23027]
We used to have `warnOldDocs.js`, but that got lost with our move to paradox.

We should either reuse `warnOldDocs.js` or find another way to achieve this functionality.

May need #23024 to be reintroduced.

**Comment by RvanderLaan** [comment]
Is it alright if I pick this one up? It shouldn't be too hard, but I might need to introduce a modified version of the default Paradox page template to insert the JavaScript code on every page.

**Comment by raboof** [comment]
done in #25254
