### ISSUE TITLE
[akka-typed] Move the behavior factories to Behavior?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#23020]
Why are `immutable`, `deferred`, etc. defined on `Actor`? Do we need `Actor` at all?

**Comment by ktoso** [comment]
It is "the DSL".
The other bits are "the raw things".

**Comment by hseeberger** [comment]
For me it's confusing. I'd rather keep things simple and unique. And you know what happened to the current ActorDSL ...

**Comment by johanandren** [comment]
`javadsl.Actor` and `scaladsl.Actor` _are_ the APIs. So that is definitely not comparable to `ActorDSL`. Maybe we should remove the factories in  `Behavior`, just keep the shared singletons, and mark those internal to avoid confusion though?

**Comment by hseeberger** [comment]
Yeah, that sounds good.

**Comment by patriknw** [comment]
the only factories that exists in `Behavior` are for `same`, `unhandled`, `stopped` and such and those are needed to be able to write an `ExtensibleBehavior` without depending on language specifics. That is power user api. The one-stop-shop for normal users are `Actor.<ctrl-space>`.

**Comment by hseeberger** [comment]
OK, I'll speak up one last time before I give up.

Although I follow the development of Akka closely, I'm not working on Akka itself, but I'm a user, i.e. one of those guys you are developing Akka for. As a user (who has proven to pay a lot attention to good API design and good code style) I naturally have a different perspective than you guys and from my perspective the current API is a little confusing and could be improved. 

Just look at `val behavior: Behavior = Actor.immutable ...`. Names matter and here names mismatch, at least for fresh users who are currently discovering this API.

I'd be very happy if you could take a user's feedback and try to be creative about it instead of just defending the current state.

**Comment by patriknw** [comment]
I have read this again and I'm not sure I understand what the issue or suggestion is?

Would you like the factory methods to be on Behavior instead. Then we would need scaladsl.Behavior and javadsl.Behavior and the interop would be problematic.

Or is it just the word Actor that you don't like because it is actually factories of Behavior. I like that Actor is part of the naming. Behavior can mean just about anything without additional context. ActorBehavior might be a good name, but that is kind of mouthfull.

Actor.immutable: Behavior

I read that as create an immutable actor behavior.

**Comment by hseeberger** [comment]
Currently `Actor` "only" defines methods to create `Behavior`s. Why not move these to `Behavior`? For me the context and hence the meaning of "behavior" should be pretty clear for anyone using Akka.

**Comment by patriknw** [comment]
> Would you like the factory methods to be on Behavior instead. Then we would need scaladsl.Behavior and javadsl.Behavior and the interop would be problematic.

"currently" is also important in your suggestion. It might not only be `Behavior` factories there in the future, it might be other things related to actors.

**Comment by hseeberger** [comment]
OK
