### ISSUE TITLE
regression in sharding in akka 2.5.2 with `StartEntity`

### ISSUE THREAD

**Issue by 412b** [akka/akka#23030]
`StartEntity` leaks to userspace, to be precise to extractors. In our case it lands in our `MessageExtractor`, which is really strict and is throwing an exception.

**Comment by 412b** [comment]
the problem appears because [here](https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L725) `deliverMessage` is called, which in turn calls `extractShardId` [here](https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L750) and for `StartEntity` can be undefined or like in our case even throw, when an unexpected message is passed.

**Comment by patriknw** [comment]
Sorry for the inconvenience, but that is the intention. The `extractShardId` function must now understand `StartEntity`. 

From [announcement](http://akka.io/blog/news/2017/05/24/akka-2.5.2-released):

> If you are using Cluster Sharding with "remembering entities" there is one important change that requires that you make a change to your code when updating to 2.5.2. To solve a [critical issue #22289](https://github.com/akka/akka/issues/22289) that could result in duplicate entities when the extractShardId function is changed (e.g. between deployments) there is now a new message `Shard.StartEntity(entityId)` that the `extractShardId` must understand. See example in [Scala](http://doc.akka.io/docs/akka/current/scala/cluster-sharding.html#remembering-entities) or [Java](http://doc.akka.io/docs/akka/current/java/cluster-sharding.html#remembering-entities).

**Comment by raboof** [comment]
This is expected: when upgrading from 2.5.1 to 2.5.2 you will have to update your `extractShardId` function as described in the release notes. See http://akka.io/blog/news/2017/05/24/akka-2.5.2-released#akka-252 for an explanation of what to change and references to read up on why this change was necessary.

We typically make the upgrade as painless as possible, but in this case we didn't see a way to properly fix the issue without requiring application-specific changes upon upgrading.

**Comment by 412b** [comment]
@patriknw while I agree that it's outlined in the announcement (my fault that I wasn't reading the announcement), but that means that 2.5.2 is not a drop-in-replacement for 2.5.1, though my expectation was that minore releases are to be drop-in-replacements.

**Comment by patriknw** [comment]
That is our goal. At the same time we must be allowed to fix bugs and that can mean changed behavior. The alternative in this case would have been to live with an issue that could result in critical problems in running production systems. Several incidents have already been reported.
