### ISSUE TITLE
The actors page of the documentation contradicts itself in regards to "incarnations"

### ISSUE THREAD

**Issue by eyalroth** [akka/akka#23035]
The actors page of the documentation contradicts itself in regards to "incarnations".

From the [actor lifecycle section](http://doc.akka.io/docs/akka/2.5.2/scala/actors.html#actor-lifecycle):

> A restart only swaps the Actor instance defined by the Props but the incarnation and hence the UID remains the same.

From the [initialization patterns section](http://doc.akka.io/docs/akka/2.5.2/scala/actors.html#initialization-patterns):

> During the lifetime of an ActorRef, an actor can potentially go through several restarts, where the old instance is replaced by a fresh one, invisibly to the outside observer who only sees the ActorRef.
> 
> One may think about the new instances as “incarnations”.

The former claims that multiple instances of the same actor-ref are in fact of the same incarnation, while the latter claims that each of these instances is its own incarnation. Which is true?

**Comment by ktoso** [comment]
Good point, would you want to reword the first one? Thanks for the PR in advance!

**Comment by eyalroth** [comment]
I'm relatively new to Akka, which explains why I read the documentation, and I really am unsure which is the right definition.

There seem to be [other](http://doc.akka.io/docs/akka/2.5.2/scala/general/addressing.html#what-is-an-actor-path-) [mentions](http://doc.akka.io/docs/akka/2.5.2/scala/general/addressing.html#actor-reference-and-path-equality) of the term in the documentation -- along with the actor life-cycle diagram -- all of which seem to coincide with the first definition. With this in mind, looks like the second section ("initialization patterns") is the one that should be revised.

**Comment by patriknw** [comment]
You are right, a restart doesn't bump the "incarnation". It's the same
actor from the outside.

Stop followed by a start will result in new incarnation, i.e. ActorRef
pointing to the old incarnation is useless, messages sent via old ActorRef
will not be delivered to the new Actor incarnation.

/Patrik
lör 27 maj 2017 kl. 16:03 skrev eyalroth <notifications@github.com>:

**Comment by eyalroth** [comment]
In that case, I don't think I can revise the second section. My knowledge of the framework and its internals is fairly minimal, hence I would have to guess what is the right description of its functionality.

**Comment by patriknw** [comment]
No problem. We'll take this one. Thanks for spotting. Other PRs for more obvious thinks are welcome when you read the rest of the docs.

**Comment by richard-imaoka** [comment]
I submitted a pull req. When the core team has time, please see if that makes sense?

@eyalroth FYI I create [a gist](https://gist.github.com/richard-imaoka/28d8e754bdba21f6d485b163c6767e7c) demonstrating the behavior of restart and stop followed by actor re-creation.

**Comment by eyalroth** [comment]
@richard-imaoka nice!

I think you'd want to add a `println` for the second child at [this part of the gist](https://gist.github.com/richard-imaoka/28d8e754bdba21f6d485b163c6767e7c#file-myactorincarnation-scala-L140) to demonstrate the ID of the newly created incarnation.

**Comment by richard-imaoka** [comment]
Ah, thanks. Fixed my gist 😃

**Comment by ktoso** [comment]
Thanks!

**Comment by anilkumble** [comment]
Hi Am new to Akka. What is the difference between incarnation and UID ? What is the usage of incarnation and UID ? When it is being created ?

**Comment by patriknw** [comment]
UID is created when the actor is first started, it's stable for the ActorRef. With incarnation we mean that an actor is stopped and then a new actor is started with the same actor path. A new incarnation has a new UID, and the old ActorRef is no longer valid (messages will not be delivered if sent via the old ActorRef).

**Comment by anilkumble** [comment]
Thanks @patriknw. 
What is the purpose of having UID and Incarnation ?
I didn't get a clear picture on this

**Comment by anilkumble** [comment]
Hi, am trying to setup a cluster in my machine. So cluster is nothing but a no of ActorSystems. 
After making the cluster, my use case is to **send a message to cluster(not to actor)** so that it will forward the msg to any of the actor which is currently available..

Give me tips to achieve this use case

**Comment by raboof** [comment]
@anilkumble this is starting to digress from the original topic of this issue, perhaps it would be better to start a topic at https://discuss.akka.io ?

**Comment by anilkumble** [comment]
okay.
I'll discuss it in the link

**Comment by anilkumble** [comment]
How to specify different host names in .config file

**Comment by raboof** [comment]
@anilkumble that question doesn't have anything to do with 'incarnations', please take it to https://discuss.akka.io, stackoverflow or https://gitter.im/akka/akka

**Comment by anilkumble** [comment]
Am referring Lightbend tutorial for akka cluster. 

What is the meaning of the below line ?

getContext().actorOf(
      FromConfig.getInstance().props(Props.create(StatsWorker.class)),
      "workerRouter")

Is it creating new actor in type of StatsWorker  or it is referring  the actor which already created

**Comment by anilkumble** [comment]
> @anilkumble that question doesn't have anything to do with 'incarnations', please take it to https://discuss.akka.io, stackoverflow or https://gitter.im/akka/akka

Thanks 😄

**Comment by raboof** [comment]
(continued at https://discuss.lightbend.com/t/doubt-on-lightbend-akka-cluster-tutorial-example/4156/2)
