### ISSUE TITLE
Surprising behavior of concat 

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23044]
Given this code:
```
  val first = Source.single("first")
    .delay(10.seconds)
    .map { n => println("end of delay"); n }
  val second =
    Source.lazily { () =>
      println("second materialized")
      Source.single("second")
    }
  first.concat(second).runForeach(println)
```
I'd expect the following order of the two first printlns:
```
end of delay
second materialized
```

But it turns out because of #19271 that `Source.concat` and `Concat()` (but not `new Concat()`) eagerly pulls both inputs because of this: https://github.com/akka/akka/blob/b3d00afdd1e607c2d227f3ab559c11978d366c68/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala#L897 which was added in #19271

This is completely surprising to me, why would the factory sneak in eager pull of one element, isn't detaching something the user themselves should do explicitly if that is what they want?

**Comment by jrudolph** [comment]
There was this ticket before https://github.com/akka/akka/issues/18683 which was about laziness of subscription (which seems to be a slightly different topic).

**Comment by johanandren** [comment]
This issue makes lazy subscription (through Source.lazy) impossible with concat as well, as it pulls right away, which would materialize the lazy source.

**Comment by 2m** [comment]
Also check if the exhausted sources are still kept around in the graph interpreter. Would the lazy subscription fix that?

**Comment by johanandren** [comment]
Could the exhausted part be solved by #23440 perhaps?

**Comment by johanandren** [comment]
Found this where there was discussions about the same thing previously #22042

**Comment by OlegYch** [comment]
stumbled on this as well
https://scastie.scala-lang.org/Dg2Z4MsSSpG5xoxzDou0NA

this is a solution i found:
```scala
implicit class SourceLazyOps[E, M](val src: Source[E, M]) {
  def concatLazy[M1](src2: => Source[E, M1]): Source[E, NotUsed] =
    Source(List(() => src, () => src2)).flatMapConcat(_())
}
```
any reason why this is not the default behavior or not available as an option?

**Comment by johanandren** [comment]
As mentioned in #22042 it could lead to deadlock in graphs with cycles, so if we changed the default (which is what I would wish for) we would/could be breaking existing user code, which isn't so nice. Otoh I really dislike this, and you could easily add a detach manually to solve the deadlock cases.

**Comment by yufei-cai** [comment]
+1 for an extra `concatLazy` method. My use case involves a lazily materialized source at the end of a stream for bookkeeping tasks on the persistence, and also has a cycle in the stream for negative feedback control.

**Comment by johanandren** [comment]
Example of where the hidden detach can, perhaps surprisingly, affect performance in a stream: https://github.com/akka/akka-grpc/issues/1349

**Comment by johanandren** [comment]
Example of where the hidden detach can, perhaps surprisingly, affect performance in a stream: https://github.com/akka/akka-grpc/issues/1349

**Comment by jrudolph** [comment]
> Example of where the hidden detach can, perhaps surprisingly, affect performance in a stream: [akka/akka-grpc#1349](https://github.com/akka/akka-grpc/issues/1349)

In that case the cost was in calling `concat` not in running the stream.

**Comment by patriknw** [comment]
We are creating `fastConcat`, `cheapConcat` in various places. We should add something in Akka instead if existing `concat` can't be improved without breaking semantics.

We should also look into if we can optimize cases where Source.empty and Source.singe are used.
