### ISSUE TITLE
search is not working properly

### ISSUE THREAD

**Issue by 123avi** [akka/akka#23049]
Tried to use search with the most basic query ("future") , see attached image
<img width="1078" alt="screen shot 2017-05-29 at 4 29 48" src="https://cloud.githubusercontent.com/assets/3158849/26533919/b4c2e012-4427-11e7-8ab0-7dc11943a802.png">

**Comment by raboof** [comment]
Thanks for reporting! We're aware of the issue, it's because the Algolia indexer configuration got confused by our new documentation layout. They're updating the configuration and search results should be back soon - let's close this issue when that happens.

**Comment by raboof** [comment]
Should be fixed!

**Comment by 123avi** [comment]
Yeap looks good, thanks
