### ISSUE TITLE
format error in documentation

### ISSUE THREAD

**Issue by pepegar** [akka/akka#23054]
I think that the new design is not aware of this kind of substitutions that worked previously:

![screen shot 2017-05-29 at 10 44 51](https://cloud.githubusercontent.com/assets/694179/26542882/e5b42b8e-445b-11e7-9047-2acd64b1bb53.png)

This can be found in [Testing Actor Systems page](http://doc.akka.io/docs/akka/current/scala/testing.html).

I think something is trying to expand that to an email address because of the `@`. 

BTW, I don't know if this is related to my browser. It's Chrome 58.0.3029.110.

**Comment by raboof** [comment]
Hmm actually these substitutions are new, but it looks like I made a mistake there.

**Comment by raboof** [comment]
Looks like you can't use a directive directly after 'normal' text - good to be aware :).

I shortened the intro and removed the switch entirely here.

**Comment by raboof** [comment]
Thanks for the heads-up!
