### ISSUE TITLE
LazySourceSpec - "propagate attributes to inner streams" tests flatMapMerge

### ISSUE THREAD

**Issue by Silv3rcircl3** [akka/akka#23065]
probably copy paste mistake 

from
https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlattenMergeSpec.scala#L199

to
https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazySourceSpec.scala#L107

**Comment by patriknw** [comment]
@Silv3rcircl3 Would you be able to create a pull request to fix this?

**Comment by Silv3rcircl3** [comment]
@patriknw nop, sorry, I'm working on the .Net port and therefore don't have any scala/java dev environment
