### ISSUE TITLE
Message is None in Java serialization warning

### ISSUE THREAD

**Issue by 2m** [akka/akka#23067]
Incoming message attempted to use Java Serialization even though 'akka.actor.allow-java-serialization = off' was set! Message class was: [None]

This could be if the `fromBinary(buf: ByteBuffer, manifest: String)` of the `DisabledJavaSerializer` is called [here](https://github.com/akka/akka/blob/7a0e5b31f8105aaff75e71f130048545c9edffe1/akka-actor/src/main/scala/akka/serialization/Serializer.scala#L354).

It would be good to log the value of `manifest` in this case. However I am not sure if that is going to contain anything.

**Comment by patriknw** [comment]
Duncan is working on this

**Comment by patriknw** [comment]
According to my classification this is not a `bug` but an improvement. Bugs are things that can cause incorrect behavior or degradation of performance in production.
