### ISSUE TITLE
cannot access PersistentFSM.StateChangeEvent from PersistentQuery streams

### ISSUE THREAD

**Issue by mizerlou** [akka/akka#23072]
i would expect to be able to do something like:
```scala
PersistenceQuery(system)
        .readJournalFor[ScalaDslMongoReadJournal](MongoReadJournal.Identifier)
        .eventsByPersistenceId("id", 0, Long.MaxValue)
        .collect[String] {
          case StateChangeEvent(name, _) => name
        }
```
however, since StateChangeEvent is private to the persistence package (and rightly so), this can't be done.

maybe an extractor could be useful here?

**Comment by patriknw** [comment]
@mizerlou That is a valid point. Could you create a pull request to make `StateChangeEvent` public?
