### ISSUE TITLE
TraversalBuilder.printTraversal() has inconsistent indentation for Concat?

### ISSUE THREAD

**Issue by richard-imaoka** [akka/akka#23076]
With this code:

```scala
TraversalBuilder.printTraversal(Concat(Pop, PushNotUsed))
```

`Pop `and `PushNotUsed` inside the same `Concat` get inconsistent indentation.

```
 | pop mat
push NotUsed 
```

I think we should either:

1. Not indent anything at all,  as [`Concat `is only to represent a linear list of commands](https://github.com/akka/akka/blob/ce7a7a2148517bf219799f472fc190b206b1ede8/akka-stream/src/main/scala/akka/stream/impl/package.scala#L47#L55)
2. Otherwise, put `first `and `second` from `Concat(first, second)` at the same indent level

Does that make sense?

**Comment by drewhk** [comment]
The identation implicitly encodes the concat nodes. I found it the best compromise between being explicit with concats or completely ignoring them. Identation is useful as it reflects the depth of the stack the materializer needs to traverse, and also usually corresponds to composition boundaries. (try embedding a flow in a larger flow and see the printout)

**Comment by richard-imaoka** [comment]
Closing this as discussed in #23077
