### ISSUE TITLE
Merged the document from akka-docs scala/stream/stream-composition and java/stream/stream-composition

### ISSUE THREAD

**Issue by atiqsayyed** [akka/akka#23086]

**Comment by Captain1653** [comment]
The issue is really old. There is only one file `stream-composition.md` in the project now. 
<img width="890" alt="Screenshot 2022-05-31 at 19 17 57" src="https://user-images.githubusercontent.com/4740207/171223252-2b1963ab-fc16-4e0d-a2a5-de30f268d781.png">

Is it make sense to close the issue?

**Comment by johanandren** [comment]
Let's close it
