### ISSUE TITLE
Docs for Source.queue incorrectly state that the materialized source is for single thread usage only

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#23081]
According to a lot of smart Akka team members this is not the case: "SourceQueue that current source is materialized to is for single thread usage only."

**Comment by johanandren** [comment]
Actually I think the reason why that comment was in there was just discovered in #23078 :)

**Comment by muuki88** [comment]
Thanks @hseeberger for creating this issue :) 
Related question on Stackoverflow: https://stackoverflow.com/questions/44241920/akka-http-host-level-client-side-api-source-queue-pattern

**Comment by patriknw** [comment]
Closing this and let's investigate the other issue.
