### ISSUE TITLE
Akka-Camel Producer does not forward result if the Camel endpoint is slow

### ISSUE THREAD

**Issue by slowenthal** [akka/akka#23099]
Although the Camel endpoint is or should be non-blocking, it is possible for the Producer Child actor to effectively block when working with a slow SQL database or with queries that bring back large result set.  Although we should never bring back large result set, and preferably page the database reads using multiple smaller queries, sometime users will create large result sets. 

This may prevent the result set from being sent to the producer.

In general, an application extends the Producer Support actor (or trait).   The producer create an producer child actor to process the camel message.   When the producer receives a message, it sends it to the mailbox of the Producer Child.  It then calls the Camel endpoint and receives a future.  When the future completes, it sends the results back into the mailbox of the producer child actor.  When that actor receives results, it forwards it up to its parent (the producer), so it can perform the application's code.

If the camel endpoint is slow, or otherwise blocks, there is a potential for a large number of new requests to land in the mailbox ahead of the result set.  Therefore the result set never gets forwarded up to the parent. 

The fix in the associated pull request has the Camel callback produce results directly to the parent's mailbox.  This prevents co-mingling of new work and results in the same mailbox.  

Another solution considered was to use a priority mailbox where MessageResult and Failure result have high priority, but there still may be a lag to forward them to the parent, even if they are first in line.  In addition, it is more complex a change.

**Comment by johanandren** [comment]
Note that the camel module is deprecated since 2.5 and will go away in 2.6

**Comment by patriknw** [comment]
For reference, this is how to configure a separate dispatcher for the producers:

```
akka.camel.producer.use-dispatcher = blocking-io-dispatcher

blocking-io-dispatcher {
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 32
  }
  throughput = 1
}
```
