### ISSUE TITLE
ePub version of Akka 2.5.x documentation

### ISSUE THREAD

**Issue by softwareklinic** [akka/akka#23094]
Any plans to release/publish the epub or pdf version of akka 2.5.x documentation? -- its really convenient to read on smaller devices.

**Comment by softwareklinic** [comment]
http://doc.akka.io/docs/akka/2.5/Akka.epub

**Comment by raboof** [comment]
You think so? In fact the new stylesheet seems to work quite well on my mobile, much better than a PDF. epub might be cool though - I'm afraid the link you found still (incorrectly) pointed to the 2.5.1 version, updating that now. http://doc.akka.io/docs/akka/2.5.2/Akka.epub might of course still be useful.

That said it might indeed be cool to bring back the pdf/ebook versions. The logical place to introduce that would probably be in paradox (the new docs system we moved to, e.g. pandoc, see https://github.com/lightbend/paradox/issues/98) - there might be some extra work needed to support the 'grouping' used to switch between java and scala versions of the documentation.

**Comment by softwareklinic** [comment]
Can't agree more it's quite readable - still offline reading would be a
good idea -:)

Who is offline these days?


On Sun, Jun 4, 2017 at 4:05 PM Arnout Engelen <notifications@github.com>
wrote:

> You think so? In fact the new stylesheet seems to work quite well on my
> mobile, much better than a PDF. epub might be cool though - I'm afraid the
> link you found still (incorrectly) pointed to the 2.5.1 version, updating
> that now. http://doc.akka.io/docs/akka/2.5.2/Akka.epub
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__doc.akka.io_docs_akka_2.5.2_Akka.epub&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=T4s2zFCwO_ENWalfn7xKlH22j1OF7UNQaDqCoaR341c&s=PeWpbdkgAN8d2wfyAHyWoXqoMJsB-ygOnCpCVJapXHo&e=>
> might of course still be useful.
>
> That said it might indeed be cool to bring back the pdf/ebook versions.
> The logical place to introduce that would probably be in paradox (the new
> docs system we moved to, e.g. pandoc, see lightbend/paradox#98
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lightbend_paradox_issues_98&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=T4s2zFCwO_ENWalfn7xKlH22j1OF7UNQaDqCoaR341c&s=w0-iaXMaan1R1fCxXkd8TaewIaAqpo5IqsguOr9dP1k&e=>)
> - there might be some extra work needed to support the 'grouping' used to
> switch between java and scala versions of the documentation.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_akka_akka_issues_23094-23issuecomment-2D306066907&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=T4s2zFCwO_ENWalfn7xKlH22j1OF7UNQaDqCoaR341c&s=DZz_Rrlp-6zkz895hPtyC2O43AzWmH05l8vkFqC8DZM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCibqIOpKnKg0LAmOuy-2DgxXEjNny9gks5sAxwNgaJpZM4NvfRR&d=DwMFaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=T4s2zFCwO_ENWalfn7xKlH22j1OF7UNQaDqCoaR341c&s=htPUGFjCqWSPGv_Y3LYe0mCk90An2B0Y5W4UkMFa8TA&e=>
> .
>
-- 
Regards,
Keyur
Cell: 2147845203

**Comment by patriknw** [comment]
For offline we have ticket https://github.com/akka/akka/issues/22728
can we close this issue (it has to be developed in Paradox)?

**Comment by softwareklinic** [comment]
Will do / yes
On Wed, Jun 7, 2017 at 7:59 AM Patrik Nordwall <notifications@github.com>
wrote:

> For offline we have ticket #22728
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_akka_akka_issues_22728&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=Z8rjM_fU1prKMkR5TmrN6AhetHTM42WAHg_VNfYdyKE&s=13qafGhbezpi-f1plfg_sQ-HWamSSd5loySgPjgcAqQ&e=>
> can we close this issue (it has to be developed in Paradox)?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_akka_akka_issues_23094-23issuecomment-2D306786876&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=Z8rjM_fU1prKMkR5TmrN6AhetHTM42WAHg_VNfYdyKE&s=8d82T3ECH36UugkeUpJPbrw63OEWbmPCj97aCNl6d-I&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHMCiRped793hLfwnIBYiUb3Gxz-5FQ0zsks5sBp6dgaJpZM4NvfRR&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=jE0nj8mYWFLxOa6KDmmXBmmwqzThJ1FTJw0CAx3FXrI&m=Z8rjM_fU1prKMkR5TmrN6AhetHTM42WAHg_VNfYdyKE&s=kCdFe8Ax_GOYRh6tHnWvhc5Nin5kFRDMYVyRy_PxHeI&e=>
> .
>
-- 
Regards,
Keyur
Cell: 2147845203

**Comment by LeifW** [comment]
That above .epub link is 404. Are there any currently available .epub versions of the docs?

**Comment by raboof** [comment]
@LeifW no, we currently don't have a pipeline to publish the docs as .epub.

**Comment by patriknw** [comment]
if the purpose offline documentation you could clone or download https://github.com/akka/doc.akka.io
