### ISSUE TITLE
Improve doc for TestKitBase.expectTerminated

### ISSUE THREAD

**Issue by huntc** [akka/akka#23091]
`TestKitBase.expectTerminated` requires the actor to be watched. This is not made explicit in the API doc.

**Comment by richard-imaoka** [comment]
I was going to raise a pull request for this, but realized:

* other methods in [TestKitBase](https://github.com/akka/akka/blob/15b166765b3810c793b8b1a387255bcb46ffc176/akka-testkit/src/main/scala/akka/testkit/TestKit.scala#L391L400) also do not have all the parameters explained
* and [the user doc](http://doc.akka.io/docs/akka/2.5.2/scala/testing.html#watching-other-actors-from-probes) already explains how to use this with the target actor parameter. 

So this issue can be closed without a fix?

![image](https://user-images.githubusercontent.com/7414320/27259523-0634a416-5450-11e7-94e5-8d59b8cb90f1.png)

**Comment by raboof** [comment]
I do think it's useful to (briefly) document this in the API documentation, for easier browsing from an IDE.

**Comment by richard-imaoka** [comment]
OK, what about other methods in `TestKitBase` or do we only think about `expectTerminated` for now?

**Comment by raboof** [comment]
Most methods pretty much speak for themselves, perhaps start with just `expectTerminated` because it's indeed a bit subtle?

**Comment by ktoso** [comment]
+1, let's start from that one. Though to be honest documenting the other ones would likely be also a good idea, can be done separately though (new ticket). It could help newcomers to akka figure out things more easily I guess
