### ISSUE TITLE
Make sure the build is sbt 1.0 ready

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23093]
We should make sure we can try the 1.0 milestones.
We'll get help in speeding up the build then, a friendly bird told me. 🐦

**Comment by ktoso** [comment]
Note to self: we need to make sure all plugins are ready.

**Comment by ktoso** [comment]
Letting @jvican know about this issue, we'll work on it soon :)

**Comment by jvican** [comment]
This is great @ktoso, thanks for the ticket :smile:. I'm looking forward to using akka as the baseline for our performance work in sbt, so the sooner this is ready the better for us!

**Comment by patriknw** [comment]
We discussed this today and decided that we will create a branch where we remove the plugins that are not necessary for an ordinary build (most are for releasing), because it's probably unrealistic to update all plugins for the milestones/RCs.

**Comment by jvican** [comment]
Sure, that sounds good.

**Comment by 2m** [comment]
Here is a branch from the latest Akka master which starts with sbt 1.0.0-M6: https://github.com/2m/akka/tree/wip-sbt-1.0.0-2m

**Comment by jvican** [comment]
Thank you @2m, I'm having a look at it now.

**Comment by raboof** [comment]
Our work in progress on moving to sbt1 for real is in the `jdk9-build` branch.

Let's tag them [t:sbt1](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3At%3Asbt1)

**Comment by raboof** [comment]
We're on 1.0.2/1.0.3 now ;)
