### ISSUE TITLE
AsyncCallbacks to just-finishing stages can be lost

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23111]
AsyncCallbacks work in a fire-and-forget fashion by sending messages to the underlying `ActorGraphInterpreter`. While the message is in-flight a stage can shut down concurrently. When the queued asynchronous signals are executed later, they are silently discarded if the stage has gone in the meantime. This might be acceptable for some use cases but others rely on no asynchronous signals being lost. Especially, the `CallbackWrapper` infrastructure tries to "gracefully" handle those cases but will still miss asynchronously enqueued async signals that were scheduled before the `stopCallback` was called.

I think we should at least add DEBUG logging when an async signal is dropped here: https://github.com/akka/akka/blob/87b28d0dc53d236168b00dab0f443886f0f11853/akka-stream/src/main/scala/akka/stream/impl/fusing/GraphInterpreter.scala#L436-L436

We should also think about how to improve the handling, e.g. in the `CallbackWrapper` by notifying the `CallbackWrapper` when the async callback has actually be executed. All in-flight async signals should be buffered (similar to the `NotInitialized` state) so that they can be handled when stopCallback was called.

/cc @agolubev who contributed `CallbackWrapper`.

**Comment by patriknw** [comment]
Related https://github.com/akka/akka/issues/20503

**Comment by jrudolph** [comment]
Indeed, this comment https://github.com/akka/akka/issues/20503#issuecomment-259255543 seems to describe the same issue.

**Comment by agolubev** [comment]
Let me look into this on the weekend. Will try to do buffering for `CallbackWrapper`

**Comment by agolubev** [comment]
almost there - trying to optimize my solution now.

**Comment by ktoso** [comment]
Great, thanks for looking into it :) Marking as in progress then

**Comment by patriknw** [comment]
Let's follow up in related tickets next week.
