### ISSUE TITLE
SourceQueue.watchCompletion scaladoc is misleading

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23119]
It says `Method returns future that completes when stream is completed and fails when stream failed` but in reality downstream failures will likely reach the `QueueSource` through `onDownstreamFinish` so it cannot fulfil that promise (to fail the promise).

The true behaviour is that it will fail if `SourceQueueWithComplete.fail` is called, there is an internal error in `QueueSource` but for other cases it will just complete with `Done`.

**Comment by ktoso** [comment]
PR was merged, assigned milestones.
