### ISSUE TITLE
HttpServer Post request entity have HTTPEntity.strict and HTTPEntity.default type(the probability of 1/5000 ) 

### ISSUE THREAD

**Issue by kejiawu** [akka/akka#23128]
I found a problem.
Create Httpserver and send Post request . not keep-alive
The request content length is 594. Usually HttpRequestEntity type is strict, but the probability of 1/5000 will be HttpRequestEntity default type, and I read entity content timeout(3s).

When request content length is 465,  HttpRequestEntity default type didn't appear.
Does anyone know how to solve the problem.
Please help me.
Thanks.

Request HttpEntity object toString, the result is:
HttpEntity.Default(text/xml; charset=UTF-8,594 bytes total)

**Comment by ktoso** [comment]
Please read http://doc.akka.io/docs/akka-http/10.0.6/java/http/implications-of-streaming-http-entity.html which explains what's happening here.
Akka HTTP is streaming by nature, so yeah, requests don't have to be strict - they are often streaming. simply consume the entity stream using streaming (`entity.runWith...`) or use directives to convert into case classes. you can also call `toStrict` on it which will give you a strict entity - it  will however be loaded in full into memory then

**Comment by ktoso** [comment]
As this does not look to be an issue, but more of a question, closing - feel free to add more details if you think this is a bug and we can reopen it. Generally github is only used for issues / bugs, not asking questions You can ask on [community mailing list](https://groups.google.com/forum/#!forum/akka-user) if you have more questions about using akka

**Comment by ktoso** [comment]
Also please note that the right repo for Akka HTTP things is: https://github.com/akka/akka-http

**Comment by kejiawu** [comment]
I use entity.toStrict(2300, materializer).whenComplete((strict, th) -> {});
The result is timeout exception.  

The code is:
entity.toStrict(2300, materializer).whenComplete((strict, th) -> {
					if (strict != null) {
						String data = strict.getData().decodeString(HttpCharsets.UTF_8.value());
						sender.tell(setResult(ResultCode.SUCCESS, ResultCode.SUCCESS_DESC, data), self);
					} else {
						logOut("Get content length :"+len);
						logOut(LogUtil.printExceptionToString(th));
						sender.tell(setResult(ResultCode.FAILED, ResultCode.FAILED), self);
					}
				});

What's the problem with this??

**Comment by ktoso** [comment]
what's the request though

**Comment by kejiawu** [comment]
Post request :


POST http://192.168.99.203:8080/

POST data:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:gg="http://www.ggggggggggg.com/ggg/">
   <soapenv:Header>
      <hss:PassWord>boss@123</hss:PassWord>
      <hss:UserName>boss1</hss:UserName>
   </soapenv:Header>
   <soapenv:Body>
      <hss:AAA_BBBB>
         <hss:HLRSN>1</hss:HLRSN>
         
         
         
         <hss:BBBB>0000000000000</hss:BBBB>
         
      
      </hss:AAA_BBBB>
   </soapenv:Body>
</soapenv:Envelope>

Request Headers:
Connection: close
Content-Type: text/xml; charset="utf-8"
Accept-Encoding: gzip,deflate
Content-Length: 594
Host: 192.168.99.203:8080
User-Agent: Apache-HttpClient/4.2.6 (java 1.5)

**Comment by kejiawu** [comment]
POST http://192.168.99.203:8080/

POST data:
[no cookies]

Request Headers:
Connection: close
Content-Type: text/xml; charset="utf-8"
Accept-Encoding: gzip,deflate
Content-Length: 594
Host: 192.168.99.203:8080
User-Agent: Apache-HttpClient/4.2.6 (java 1.5)

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:gg="http://www.ggggggggggg.com/ggg/">
   <soapenv:Header>
      <hss:PassWord>boss@123</hss:PassWord>
      <hss:UserName>boss1</hss:UserName>
   </soapenv:Header>
   <soapenv:Body>
      <hss:AAA_BBBB>
         <hss:HLRSN>1</hss:HLRSN>
         
         
         
         <hss:BBBB>0000000000000</hss:BBBB>
         
      
      </hss:AAA_BBBB>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by ktoso** [comment]
Should just work, you may be doing something weird somewhere else?
Please prepare a reproducer in case you think it's Akka at fault so we can reproduce the issue

**Comment by ktoso** [comment]
Moved this issue over to akka/akka-http where it belongs more, though I find it not really actionable without reproducer.
