### ISSUE TITLE
Changing type of merged java docs to symlinks

### ISSUE THREAD

**Issue by arpanchaudhury** [akka/akka#23125]
After merging Java and Scala docs the Java docs need to be removed

1. https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/java/stream/stages-overview.md
2. https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/java/stream/stream-flows-and-basics.md
3. https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/java/stream/stream-composition.md

**Comment by raboof** [comment]
Ah - these should have been replaced with symlinks in d5155755dbd, but indeed it seems they were replaced with almost-empty files instead - good catch

**Comment by arpanchaudhury** [comment]
@raboof Thanks. I will create a PR shortly to resolve it.
