### ISSUE TITLE
Copy CoordinatedShutdown phases' docs from config docs to sources

### ISSUE THREAD

**Issue by tkroman** [akka/akka#23131]
There is a lengthy list of phases in the `CoordinatedShutdown` object and each time I have to choose the right one, I find myself opening browser and going through the docs (http://doc.akka.io/docs/akka/2.5.2/scala/actors.html#coordinated-shutdown). It would be nice to have these descriptions as a scaladoc for each phase. The only drawback is that the compact list of phases will blow up vertically, but i think the gain is more significant. 

If you (the Akka team) OK this, I'll prepare the PR right now.

**Comment by patriknw** [comment]
@tkroman Sounds good to copy the descriptions to Scaladoc. PR is welcome.
