### ISSUE TITLE
Diamond flow for akka-stream

### ISSUE THREAD

**Issue by filosganga** [akka/akka#23136]
What is a diamond flow?

Many times I have to create myself a diamond flow:  it is a flow that splits into two branches and then merges again in the same branch.

The splitting can be either a broadcast, partition or a bit of both. It is heavily inspired by the [fs2 diamond pipe](https://github.com/functional-streams-for-scala/fs2/blob/series/0.10/core/shared/src/main/scala/fs2/Stream.scala#L1507)

It is very useful in all the cases when you need to piggyback something. for example in akka-stream-kafka project, the producer flow, let pass a `passthrough` object, with the diamond flow, it was unnecessary as the passthrough was following a different branch.

During my experience with akka-stream I have created this flow many times, so I thought it makes sense to have as built-in into Akka.

**Comment by ktoso** [comment]
Thanks for the ticket, though a bit vague in destruction still I think.
It sounds to me like it is very similar, or even the same as "project" or "bypass" that was discussed a few times: https://github.com/akka/akka/issues/15957 would you give that one a read and chime in there if it would address your use cases, and if not, why not?

**Comment by johanandren** [comment]
I'll close this as we are already tracking it in another issue.
