### ISSUE TITLE
Proposal: actor ref equivalent for sharded entities

### ISSUE THREAD

**Issue by Horusiath** [akka/akka#23132]
## Motivation

At this moment when one wants to send a message to actors living under supervision of cluster sharding module, he/she needs to:

1. Define custom message. 
2. Define custom shard-id/entity-id/payload extraction logic from that custom message type .
3. Obtain a shard region for a given type name.
4. Wrap an actual message payload with a custom message and send it via shard region.

Example:

```scala
// sending a message to an actor ref
ref ! "hello"
// sending a message to actor selection
selection ! "hello"
// sending a message to sharded entity
ClusterSharding(system).shardRegion("Entity") ! ShardEnvelope("entity-id", "shard-id", "hello")
```

This approach has a number of issues:

1. There's no common way to communicate with entities. Each team using cluster sharding must define its own message wrapper + message extractor. I bet that 90% of the time those will fit into one of two cases:
    - Envelope which takes message payload, entity id and a shard id.
    - Envelope which takes message payload, entity id and computes shard id from entity id.
2. Every time a user wants to send the message to the same entity, it must wrap it into envelope and send it by using shard region. This differs from telling a message to an `ActorRef` while conceptually it's the same thing.
3. Since there's no equivalent of `ActorRef` for sharded entities, if we want to send an info about which entity we want to communicate with as part of message payload, we must create a one more type (that will contain an info about type name, shard id and entity id, but without payload). This also means that there's no common denominator between normal actors and entities i.e. there's no way to send a message to a sharded entity using at-least-once delivery API.

## Proposal

Idea here is simple: having a dedicated, serializable equivalent of `ActorRef` for sharded entities i.e.:

```scala
object EntityRef {
  case class ShardEnvelope(shardId: String, entityId: String, payload: Any)
  case class Extractor extends MessageExtractor { ... }
}

abstract class EntityRef(val typeName: String, val shardId: String, val entityId: String) 
  extends Serializable {
    private[akka] val shardRegion: ActorRef
    def tell(msg: Any, sender: ActorRef): Unit = ???
    def !(message: Any)(implicit sender: ActorRef = Actor.noSender): Unit = ???
}

// example
val sharding = ClusterSharding(system)
val shardRegion = sharding.shardRegion("Entity")
val ref: EntityRef = shardRegion.entity("shard-id", "entity-id")
ref ! "hello"
ref ! "world"
```
This way `EntityRef`, just like an `ActorRef` could be used as part of a message payload. Behavior to think about is to figure out a correct reaction for deserializing such message on a system with no capabilities for routing messages to shards of that type.

Second part of this proposal is to extract a shared root trait for both `ActorRef` and `EntityRef`. For example on .NET side we use `ICanTell` interface which is common for both actor refs and actor selections. This way we could update provide a common approach to both actor and entity communication in other parts of the API that are now restricted to use only `ActorRef` or `ActorPath`.

I'm willing to implement this if this proposal makes sense for you.

**Comment by patriknw** [comment]
Such API can be implemented on top of the Akka Cluster Sharding API. I did something similar in Lagom, which has more limited and opinionated API. https://www.lagomframework.com/documentation/1.3.x/scala/PersistentEntity.html#Usage-from-Service-Implementation

I'm not sure it's such a big problem that it deserves another API in Akka. Having two APIs would not be good.

One thing we could provide to reduce boilerplate is the ShardEnvelope, and extractors for that. It should only contain the `entityId` and the shardId should be derived from that using something similar to [HashCodeMessageExtractor](https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L123)

Regarding, passing around the reference, the entityId is what you pass around. Nothing more is needed. That is typically part of the domain anyway so passing that in messages is not strange.

**Comment by Horusiath** [comment]
@patriknw if you can derive shardId from entityId (which is not possible in every approach), you still need to have some way of resolving shard region type name. Ofc you could derive it too based of domain-specific message type. 

However here's the problem: everything is custom and domain specific, so you cannot create or apply any kind of generic operations on it:

- The simplest example is replying to a sender, which is sharded entity. This is basically asking for trouble and probably an anti-pattern. You could resolve a sharded sender back based on custom messages, but again: this is something that must be done on per-case basis and requires from a recipients knowledge about the implementation of the sender - something that should be abstracted away.
- At the current state you cannot use `AtLeastOnceDelivery` with sharded entities. 
- Sharded entities cannot make use of distributed pub/sub mechanism.
- Other example would be to have a reminder (works like scheduler, but for long living schedules): while this can work on `ActorPath`, it's really limited usage.

While all of those could be overcomed, this would require a *hakking* around the solution. Having a common abstraction over similar concepts like `ActorRef`, `ActorSelection` and (proposed) `EntityRef` can provide even more advantages. Think of it as a next level of location transparency.

**Comment by patriknw** [comment]
Making and abstraction that is to be used instead of `ActorRef` or `ActorSelection` is not interesting. `ActorRef` and `ActorSelection` have different semantics and should not be confused. `EntityRef` would probably have a third slightly different behavior.

Several of the cases you mention can be solved by having an actor in-between, e.g. subscribes to pub/sub and delegates to sharding.

**Comment by Horusiath** [comment]
> Several of the cases you mention can be solved by having an actor in-between, e.g. subscribes to pub/sub and delegates to sharding.

@patriknw going with this line of reasoning, we could give up on abstracting local and remote actor refs, since their use cases can be solved by having remote proxy in-between.

While `ActorRef` and `EntityRef` could have different semantics, their core purpose remains the same: allowing location transparency. The major difference is that while `ActorRef` allows to abstract actors location in space, `EntityRef` could allow to also abstract its location in time.

**Comment by patriknw** [comment]
So you are suggesting that we should introduce an `AnythingRef` and that should be used in all places in Akka where we currently use `ActorRef`. `EntityRef` and `ActorRef` would be an `AnythingRef`. That's rather unrealistic considering that we would have to be compatible.

Or, do you suggest that `EntityRef` is an `ActorRef`. That's not good because it's not. They have different semantics, e.g. lifecycle aspects.

To make different things work together you need an adapter in my opinion.

Looking at your examples again:

> The simplest example is replying to a sender, which is sharded entity. This is basically asking for trouble and probably an anti-pattern. You could resolve a sharded sender back based on custom messages, but again: this is something that must be done on per-case basis and requires from a recipients knowledge about the implementation of the sender - something that should be abstracted away.

This is a somewhat valid example. Passing the entity id (and explicit or implicit knowledge of the entity type) is not such a big problem, though. I can see the benefit of having an `EntityRef` that could be passed around transparently, but serialization would not be automagic since it would typically be passed inside other messages, which are serialized with e.g. protobuf. 

> At the current state you cannot use AtLeastOnceDelivery with sharded entities.

Why not, works fine as far as I can see. The `region` is the destination.

> Sharded entities cannot make use of distributed pub/sub mechanism.

Why not? The entity can subscribe directly itself, or you can have another actor that subscribes if you want to do smarter filtering before sending to the entity.

> Other example would be to have a reminder (works like scheduler, but for long living schedules): while this can work on ActorPath, it's really limited usage.

Why not? Just schedule the message to the region ActorRef.

**Comment by Horusiath** [comment]
> Or, do you suggest that EntityRef is an ActorRef. That's not good because it's not. They have different semantics, e.g. lifecycle aspects.

No `EntityRef` should not be an `ActorRef`, but they could share common root type, as they root purpose is the same: a proxy which abstracts away message transport details for a given actor. 

While this may not be compatible at this moment, it still can be implemented in limited use cases eg. I see that at-least-once delivery and distributed pub/sub could be probably extended to make use of it. At the same time, you're already working on breaking changes in the future (aka. akka typed), so why not to include this as a part of API there?

> Why not, works fine as far as I can see. The region is the destination.

> Why not? Just schedule the message to the region ActorRef.

Well, using that perspective you don't need `ActorRef` either. You could just create custom envelope with an `ActorPath` and pass `ActorSystem` back and forth every time you want to send the message to an actor ;)

**Comment by patriknw** [comment]
We are not breaking anything with Akka Typed, we are adding another API. Let's consider this again when we design the Sharding API for Akka Typed. Thanks for input.

**Comment by ktoso** [comment]
FYI: We're currently exploring this and possibly adding to Akka Typed's Sharding. An early preview should be available soon for feedback

**Comment by patriknw** [comment]
Done in Typed
