### ISSUE TITLE
Bug in new QuickStart Guide

### ISSUE THREAD

**Issue by rstento** [akka/akka#23149]
In the section that describes how to run Hello World, it says:
To run Hello World:

In a console, change directories to the top level of the unzipped project.

For example, if you extracted the project to your root directory, from the root directory, enter: cd akka-scala-seed

The default name is now akka-quickstart-scala, so the previous text should be changed to:

For example, if you *used the default project name, akka-quickstart-scala,* and extracted the project to your root directory, from the root directory, enter: cd *akka-quickstart-scala*

I assume the same is true for the Java example but I haven't tested it yet.

**Comment by ktoso** [comment]
Thanks Ruth, will fix that!

**Comment by ktoso** [comment]
It's in the other repo, moving over
