### ISSUE TITLE
syntax Error in Akka Http Document (JAVA)

### ISSUE THREAD

**Issue by ChoJunKyu** [akka/akka#23162]
hi, im studying akka http module and making a sample codes in the Akka Http Reference(version 10.0.7)

i think i find syntax Error in "Starting and Stopping" which is in "Low-Level-Server-Side-API".
here is the codes.

/*************** Here is the Codes *******************/

ActorSystem system = ActorSystem.create();
Materializer materializer = ActorMaterializer.create(system);

Source<IncomingConnection, CompletionStage<ServerBinding>> serverSource =
  Http.get(system).bind(ConnectHttp.toHost("localhost", 8080), materializer);

CompletionStage<ServerBinding> serverBindingFuture =
  serverSource.to(Sink.foreach(connection -> {                  <<==== Sink.foreach(connection->{}) this part
      System.out.println("Accepted new connection from " + connection.remoteAddress());
      // ... and then actually handle the connection
    }
  )).run(materializer);

/***************************************************/

i marked the part which makes the Error.
im using Eclipse java neon(jdk1.8) and that part makes a Red line on it.

hoping your help. thanks

**Comment by ktoso** [comment]
Please note that akka http lives in: https://github.com/akka/akka-http/
If the issue exists still please open the issue there, thanks!

The source of truth should be the compiler, eclipse can sometimes show good code incorrectly as red and there's nothing we can do about eclipse's java support :)
