### ISSUE TITLE
Streams: InputStreamSink is blocked when used mapMaterializedValue

### ISSUE THREAD

**Issue by agolubev** [akka/akka#23187]
Currently, there is a possibility to send a message to not yet initialized stream.

following snippet fails with timeout error
```
Source.single(ByteString(1)).toMat(StreamConverters.asInputStream().mapMaterializedValue { stream ⇒
        stream.read()
        stream.close()
      })(Keep.both).run()
```

this relates to Ref #23111 and Ref #21866 that seems still to be an issue according to https://github.com/playframework/playframework/issues/6743

**Comment by francisdb** [comment]
For us both in and outputstream handling fails now with 2.5.3
Do we have to mark the code inside the mapMaterializedValue as blocking?

**Comment by francisdb** [comment]
Hmm, as I understand from https://github.com/akka/akka/issues/23279 you have to return a Future that handles the stream in the mapMaterializedValue for this to work properly?
This is not really documented in the api docs?
Could somebody from the team shed some light on this?

**Comment by agolubev** [comment]
>Do we have to mark the code inside the mapMaterializedValue as blocking?

No, it should not fix the case

>as I understand from #23279 you have to return a Future that handles the stream in the mapMaterializedValue for this to work properly?

As InputStream is blocking API - we are blocking read while some data is available. In this case, we need to block while initialization has happened

Let me triage this in next few days to know the exact reason. Now I can see that waiting for init finish mechanism is there - pehaps some bug in a code.

**Comment by agolubev** [comment]
Ok, so the problem here is that InputStreamAdapter is polling from sharedBuffer (data channel between sink and stream) in a blocking way. Apparently, this block is happening in the same thread that does materialization.

**Comment by agolubev** [comment]
I can materialize with Future[InputStream] however it requires API change. Need Akka core team guidelines here.

**Comment by johanandren** [comment]
This has been reported multiple times. If you block materialization the stream will not start running, and if the blocking depends on the stream running you will either get deadlock or some form of timeout will hit. We cannot really do anything on the Input/Outputstream being blocking, so I think if anything should be done it is a warning in the docs of the stream adapters - since people have gotten stuck with those repeatedly.

**Comment by johanandren** [comment]
Here's some more duplicates: #23279, https://github.com/akka/akka/issues/21504#issuecomment-248528568

**Comment by agolubev** [comment]
I see, let me add this to docs

**Comment by johanandren** [comment]
Thanks!

**Comment by francisdb** [comment]
I'm still confused. Is there an example of how to correctly use these adapters?

**Comment by johanandren** [comment]
Pretty much _any_ usage is correct, except for using the old Java streams directly inside of `mapMaterializedValue` of their own stream, which is the point of this ticket. That is however true for any kind of logic that blocks the creation of the stream while also depending on it running. For example something like `Source.maybe.mapMaterializedValue(p => Await.result(p.future, timeout)).run()` would have the same problem.

We don't have good examples of using them in the docs as far as I can find, except for in the test coverage, but the "normal" way would be to `val inputstream = asInputStream.do().stuff().run()` and _then_ interact with the materialized value.

**Comment by francisdb** [comment]
thanks @johanandren, that makes sense

**Comment by agolubev** [comment]
@johanandren  related PR is merged - could you close this ticket?

**Comment by ktoso** [comment]
Thanks for the reminder :)
