### ISSUE TITLE
Allow actorRefWithAck to materialize a value

### ISSUE THREAD

**Issue by forty** [akka/akka#23194]
I think it would be nice if it was possible to materialize a value with `Sink.actorRefWithAck`. This could be done either by registering a callback on the init message, or by waiting for a response to the complete message. One on the simple use case I have in mind is just to be able to simply wait for completing of the sink (so a Future[Done] could be enough), but I guess having a value is even better (only problem I can think of is type safety, so I think the materialized value will have to be Future[Any] in this case)
What do you think?

**Comment by 2m** [comment]
You can get a `Future` which is completed when the stream completes by adding `watchTermination` anywhere in the stream definition.

Do you have another usecase for materialized value for that sink?

**Comment by forty** [comment]
How does `watchTermination` know that the sink actor has finished it's processing?I guess it's only watching the `ack` of the last element of the stream? In my case the actor is waiting for some async tasks to complete before I can consider the stream complete.

That said I might be completely misusing `actorRefWithAck` and maybe I should just use something completely different: basically what I am trying to achieve is very similar (if I understand properly) to what groupBy does (ie I send element of the stream to different substreams according to some criteria) but the sink of each substream depends on the stream content (the goal is to output a stream of JSON documents to several file `propertyvalue.json` where propertyvalue is the value of one common property of the JSON documents).
Since I have not found a better way, what I do is sending the whole flow to `Sink.actorRefWithAck` and the actor creates new substreams when needed, starting with a `Source.queue` with back pressure when required. Ideally I would like to complete the main stream, when all the substreams have completed.

**Comment by 2m** [comment]
> How does watchTermination know that the sink actor has finished it's processing?

`watchTermination` completes the materialized future either if the stream is completed (from the upstream), or the stream is cancelled (from the downstream). When the `actorRefWithAck` actor stops, then the stream is going to be cancelled and materialized future by `watchTermination` is completed.

Regarding your usecase it looks like it could be solved with [BroadcastHub](http://doc.akka.io/docs/akka/current/scala/stream/stream-dynamic.html#using-the-broadcasthub), but this is another discussion, and it should be taken to the [akka-user mailing list](https://groups.google.com/forum/#!forum/akka-user) or the [gitter channel](https://gitter.im/akka/akka).

**Comment by raboof** [comment]
Another place to discuss this further might be https://discuss.akka.io
