### ISSUE TITLE
failed: FanOutThroughputSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23198]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/745

**Comment by patriknw** [comment]
seems like FanInThroughputSpec is also failing in nightly tests, marking them as pending now and will harden them

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/827/consoleFull

**Comment by jrudolph** [comment]
Failed again 2 days ago, should that have been fixed by then? 

https://jenkins.akka.io:8498/job/akka-multi-node/2401/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5446

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/896

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5448
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5449

**Comment by patriknw** [comment]
It was marked as pending. I unlocked that when merging my PRs because I thought they fixed this one also. I'll take a look at this today.

**Comment by patriknw** [comment]
ah, the reason is
```
[JVM-1] [DEBUG] [11/14/2017 11:05:04.283] [FanOutThroughputSpec-akka.actor.default-dispatcher-11] [akka.remote.artery.Association(akka://FanOutThroughputSpec)] Dropping message [[B] from [Actor[akka://FanOutThroughputSpec/deadLetters]] to [Actor[akka://FanOutThroughputSpec@a5.moxie:35696/user/warmup-rcv#932815418]] due to overflow of send queue, size [3072]
```

**Comment by jrudolph** [comment]
Failed a few times more tonight.

**Comment by patriknw** [comment]
should be fixed now, fingers crossed

**Comment by patriknw** [comment]
it's not, still overflow of send queue

**Comment by patriknw** [comment]
The flow control was not correct, it was only using one of the targets. I'll run for a while in my repeat job before creating PR.
