### ISSUE TITLE
[Docs] Add note explaining Akka-Typed dependency needs to be added for Akka Typed

### ISSUE THREAD

**Issue by jlprat** [akka/akka#23222]
Even though it is somewhat obvious that in order to run Akka Typed, one need to add the akka-typed dependency to the project, this is not said anywhere in the documentation.
Furthermore, the dependency itself is not listed anywhere on the docs page (or at least I could not find it).

**Comment by patriknw** [comment]
Yes, please :)

**Comment by jlprat** [comment]
I can take this and do a PR later today 😃

**Comment by raboof** [comment]
closed via #23223
