### ISSUE TITLE
Multi DC failure detection: different heartbeating within and between data centers

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23229]
* Separate failure detector config (to accustom for higher latency etc) between cluster groups
* Limit the number of nodes in a cluster group that heartbeat other cluster groups (n oldest perhaps?)
* Limit the number of nodes in a cluster group that gossip with other cluster groups (n oldest perhaps?)

**Comment by ktoso** [comment]
Within a DC heartbeating should work as usual, however across cluster teams (datacenters) heartbeating should be done by a subset of nodes so we don't end up sending way too much traffic by just heartbeating everyone in the other cluster.

For example, if a cluster has 10 nodes in each DC, 3 or so nodes could be designated to be the heartbeaters. They should pick some nodes and heartbeat to them.

This task ends at that, and having that configurable perhaps. The next step is: https://github.com/akka/akka/issues/23245

**Comment by ktoso** [comment]
Why removed the pick next?

**Comment by raboof** [comment]
Sorry, GitHub UI confused me, I meant to add it but somehow removed it for some of the issues :confused:

**Comment by ktoso** [comment]
ok, no problem :-)
