### ISSUE TITLE
[typed] Asymmetry btw ActorSystem.apply and ActorContext.spawn

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#23241]
Confusing for simple minds like me:

``` scala
ActorSystem("name", behavior)
context.spawn(behavior, "name")
```

I suggest we switch the order of the parameters on `ActorSystem.apply`.

**Comment by patriknw** [comment]
Good suggestion, please PR

**Comment by hseeberger** [comment]
OK ... stay tuned.

**Comment by hseeberger** [comment]
See #23244.

**Comment by johanandren** [comment]
The string parameter in `ActorSystem.apply` is the name of the actor system, not the root actor, while the string parameter to `spawn` is the name of the actor. Having them in the same order kind of implies that I'm naming the root actor to me.

**Comment by hseeberger** [comment]
I think the difference btw an actor system and an actor is a little blurred in Akka Typed, at least from the user's perspective.

First, the ActorSystem is an ActorRef, you can send it messages. Second you create the system by passing props, so it feels like creating the root actor (which indeed happens).

**Comment by johanandren** [comment]
True, but it won't have a path based on the name, which is very different. OTOH the path isn't really that important in typed, so maybe it does not matter.

**Comment by hseeberger** [comment]
One could also argue that the system doesn't have a name. But these are indeed questions with a very small surface area from the user's perspective.

**Comment by patriknw** [comment]
even if they are not the same I think the change is good, `Props` is more important than `name` (and `name` could perhaps even be optional (or somehow read from config))
