### ISSUE TITLE
Plan for rolling update from non DC aware cluster

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23243]
Old version will not include the required team role. We could solve that by adding the default role in deserialization. Would it be better to represent default team as "no role"? Might be more special cases then?

We should document how a rolling upgrade can be performed:
* from old version without this feature
* when changing from one (default) team to multiple teams

**Comment by raboof** [comment]
Representing the default team as "no role" might make seamlessly upgrading simpler, but indeed produce more special cases in the long run - so probably best to keep the `team-default` role.

Rolling upgrade from old version without this feature should be as seamless as possible, good idea to use this issue to think about if there's any gaps. Indeed things like adding the default role in deserialization might help a lot (and be needed), let's list those in this issue and add PR's for each measure.

Describing how to go from 1 (default) team to using multiple teams will become a PR against the docs.

**Comment by raboof** [comment]
* Cluster Singleton: 
  * The `Manager`s on the pre-team nodes will accept messages from post-team nodes
  * The `Manager`s on the post-team nodes will correctly hold off starting a singleton instance until the last pre-team node has shut down if we make sure the pre-team `Member`s will be marked with the `team-default` role on the post-team nodes.
  * The `Proxy`s on the pre-team nodes will correctly forward messages to the oldest member, whether or not that is a pre-team or post-team node
  * The `Proxy`s on the post-team nodes will correctly forward messages to the oldest member, whether or not that is a pre-team or post-team node, if we make sure all pre-team nodes are marked with the `team-default` role on the post-team nodes
* Cluster Sharding
  * TODO
* Availability/SBR
* TODO more DC-aware cluster components here.

**Comment by patriknw** [comment]
Good analyzis. Sounds like we are good to go for the Singleton if we add the role in deserialization.

**Comment by patriknw** [comment]
I think you are right in that sharding will also work for the old to new version. I was first thinking that the change to ddata was needed, but that should be fine with the added default team role.
