### ISSUE TITLE
javadsl API oversight when using primitive types in collections or functions

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23251]
e.g.
```
def create[T](outputCount: Int, partitioner: function.Function[T, Int]): Graph[UniformFanOutShape[T, T], NotUsed]
```

becomes `Function<T, Object>`

must use `Integer`

Might be similar problems in many places, strange that none has been reported.

**Comment by patrox** [comment]
@patriknw I was curious about this bug, so I had a look and checked it a bit deeper and I already found another problematic spot:

https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala#L590-L592

The `costFn` which is declared there:

```scala
def limitWeighted(n: Long)(costFn: function.Function[Out, Long]): javadsl.Flow[In, Out, Mat]
```

will result in `Function[Object, Object]`.

I confirmed that changing the type from scala's `Int` to java's `Integer` would fix the initial problem,
as when I changed it, the signature became:

```java
create(int outputCount, Function<T, Integer> partitioner);
```

I can submit a PR, which will address the above issues.

**Comment by patriknw** [comment]
@patrox Thanks for picking this up. PR very welcome.

I think it's all places where we use primitives as type parameters (of functions or collections).
`Long` -> `java.lang.Long`
`Int` -> `Integer`
`Double` -> `java.lang.Double`
... ?

**Comment by patrox** [comment]
OK, so I'll create a PR where I'll address such cases.

BTW, do you think that the issue title should be changed, as right now it's only about `Int`s ?

**Comment by patriknw** [comment]
changed title

**Comment by patrox** [comment]
@patriknw If you'll have some time, can you please have a look at: https://github.com/akka/akka/pull/23265 ?
