### ISSUE TITLE
Using serializer [akka.serialization.JavaSerializer] for message [akka.cluster.sharding.ShardRegion$ShardRegionStats]

### ISSUE THREAD

**Issue by muller** [akka/akka#23250]
Hi,

Apparently there is no serializer for `akka.cluster.sharding.ShardRegion$ShardRegionStats`.

This would be nice to have one as the JavaSerializer could potentially not perform well.

Looking at the [reference.conf](https://github.com/akka/akka/blob/f528e67422bfdb4ed223caa86f1bda1c4140f5fb/akka-cluster-sharding/src/main/resources/reference.conf#L158) it includes only one serializer. This [serializer](https://github.com/akka/akka/blob/86aa42cf6c99fb605d66a11d6e1bbb3a52b9de24/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/protobuf/ClusterShardingMessageSerializer.scala#L29) doesn't make any reference to `ShardRegionStats `.

The [type](https://github.com/akka/akka/blob/f528e67422bfdb4ed223caa86f1bda1c4140f5fb/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardRegion.scala#L248) only defines one `map[string, int]` so serialization for this  type should be straightforward enough to implement.

Looking forward to hear your opinion on it.

Regards,
Leo

**Comment by raboof** [comment]
Thanks for noticing - that might be an oversight. It looks like it'd make sense to add this class to that serializer (and to `ClusterShardingMessages.proto`)

**Comment by patriknw** [comment]
I think the intention was that this is only used in interactions with the local `region` so there is no need for serialization. I don't mind adding protobuf serialization for it. One challenge might be wire compatibility, i.e. in a rolling upgrade scenario and it's sent to a node that doesn't have the new serializer. Perhaps we can get away by claiming that it was not intended to be sent over the wire?

**Comment by raboof** [comment]
Hmm yes it would fail for messages travelling from the version with the new serializer to the version still without it (though it'd work the other way around, right?).

**Comment by patriknw** [comment]
Right, the other way around works as long as java serialization is enabled. The reason is that the old serialization id is included in the message envelope.

**Comment by muller** [comment]
@patriknw I get your point, it makes sense that this shouldn't go over the wire. 

What happened here is that I have two systems in the same JVM instance. One provider=remote and other provider=cluster and I have the first asking the second for state. Probably I shouldn't be getting this statuses anyway.

**Comment by johanandren** [comment]
I think we should document that it is only meant for local interaction on the message.

**Comment by patriknw** [comment]
yes, let's solve this issue by documenting that

**Comment by danischroeter** [comment]
The same problem actually also exists for ShardRegionCommand and ShardRegionQuery (they do not extend ClusterShardingSerializable). Especially the commands Passivate and GracefulShutdown should be serializable.

Since the recommendation for akka is still to disable java serialization... I would opt to take the pill and add proper serialization to those messages.  We can document that for mixed running akka versions one needs to override the serializer for the affected types to use java serializer.

**Comment by patriknw** [comment]
Both those are also only intended as local messages, otherwise you are doing something very wrong. You are welcome to submit PR adding `NoSerializationVerificationNeeded` to these if the reason for trouble is the testing utility `serialize-messages = on`.

**Comment by patriknw** [comment]
I think this is supposed to be solved by now.
