### ISSUE TITLE
StreamConverters.asOutputStream does not work on 2.5.3

### ISSUE THREAD

**Issue by schmitch** [akka/akka#23279]
Hello, when creating a OutputStream converter on 2.5.3 the program blocks forever.

Currently the following snippet works on 2.4.15, but not on 2.5.3:
```scala
    implicit val system = ActorSystem()
    implicit val materializer = ActorMaterializer()
    implicit val ec = system.dispatcher

    val q = Await.result(StreamConverters.asOutputStream().mapMaterializedValue(os => {
      for (_ <- 1 to 10000) {
        os.write("Hello World".getBytes())
      }
      os.close()
    }).runWith(Sink.reduce((v1:ByteString, v2:ByteString) => v1 ++ v2)).map(_.utf8String), 10.minutes)

    println(q)

    Await.ready(system.terminate(), 10.minutes)
```

I have a smiliar problem with the asInputStream pendant, but could not yet track it down.

**Edit:** Looks like the mapMaterializedValue behavior changed and needs to be wrapped inside a `Future`.

**Comment by ktoso** [comment]
So it does, comment plz? :)

**Comment by ktoso** [comment]
I see, missed the addition as `Edit:` - thanks:)

**Comment by schmitch** [comment]
well, it works, but differently? I'm not sure if it's a bug or not.
It works with:

```
StreamConverters.asOutputStream().mapMaterializedValue(os => Future {
      for (_ <- 1 to 10000) {
        os.write("Hello World".getBytes())
      }
      os.close()
    }
```

is this expected?

**Comment by ktoso** [comment]
Not sure who was digging into those recently @patriknw or @johanandren ?

**Comment by johanandren** [comment]
If you block materialization on writing to the materialized `InputStream` the stream will never start consuming from the other end meaning that an internal buffer fills up and then `write`, being a blocking API, will block forever. So forking off that work on a different thread through a `Future` is probably the way to go.

**Comment by johanandren** [comment]
Here is a previous ticket where we discussed the same thing: #21504
I think this behavior is just something that isn't obvious until you think about it a bit, I'll close this ticket.

**Comment by schmitch** [comment]
This is a different issue, since I fixed that issue. https://github.com/akka/akka/pull/21866

**Comment by johanandren** [comment]
Yes, I see now that it was just a comment where I describe the same problem a bit down: https://github.com/akka/akka/issues/21504#issuecomment-248528568
