### ISSUE TITLE
Inaccurate documentation on Flow.fromSinkAndSource

### ISSUE THREAD

**Issue by larghir** [akka/akka#23274]
Read this in the documentation and was initially thinking I am obviously not getting it (I'm in the learning phase) but input and output are clearly mixed up here:

> Flow.fromSinkAndSource
> Creates a Flow from a Sink and a Source where the Flow’s input will be sent to the Sink and the Flow ’s output will come from the Source.

**Comment by raboof** [comment]
This is actually OK: a `Flow` is something that has one input and one output. This function creates a `Flow` from 'something that takes input' (a `Sink`) and 'something that can produce output' (a `Source`).

Indeed sending something to flow input should typically be able to cause something to be emitted from the flow output - that's not guaranteed by `fromSinkAndSource` though, that's up to you. I guess better pictures in the documentation should make this easier to see.

**Comment by larghir** [comment]
I still find the language confusing. I would expect that the **output** of the Flow be sent to the Sink (which takes an input) and the **input** of the Flow be coming from the Source (which produces output).

**Comment by raboof** [comment]
Think of it this way: a `Flow` has an output, which 'on the outside' can be connected to another element: to a `Sink`, or another `Flow`, etc.

On the 'inside', the `Flow` output has to be connected to something that produces elements (so they will be consumed by whatever is attached to the output later). In case of `Flow.fromSinkAndSource`, the `Source` parameter is connected to the output 'on the inside', so the user can connect the Flow output to some other `Sink` (or `Flow` etc).

**Comment by ktoso** [comment]
I do agree that this is one of those a-little-bit-mind-bending things for people who are getting started with composing things like that as it's somewhat "outside out". 

I noticed that the scaladoc is lacking pictures (ascii) that we did for other methods like this.
Perhaps we should add the following:


```
   * {{{
   *     +----------------------------------------------+
   *     | Resulting Flow                               |
   *     |                                              |
   *     |  +---------+                  +-----------+  |
   *     |  |         |                  |           |  |
   * I  ~~> | Sink[I] | [no-connection!] | Source[O] | ~~> O
   *     |  |         |                  |           |  |
   *     |  +---------+                  +-----------+  |
   *     +----------------------------------------------+
   * }}}
```

to all `Flow.fromSinkAndSOurce...` methods. What do you think?

The no connection is interestin there, because on the Coupled one we could show `<~<coupled termination>~>`

**Comment by larghir** [comment]
Cool, thanks for the explanation, that makes sense :)

**Comment by ktoso** [comment]
Added more diagrams to the javadoc/scaladoc :)
