### ISSUE TITLE
Can Member.isOlderThan enforce (throw or return Option or something) if used with diff DC member

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23307]
The `Member` method `isOlderThan` should only be used within the same DC, otherwise it's a bit unsafe since the same upNumbers can be used in those different DCs.

I think we should deprecate that version of the method and perhaps introduce a throwing or Try returning version?

Discussion: https://github.com/akka/akka/pull/23294/files#r126077787

**Comment by patriknw** [comment]
not sure we would need to deprecate, it will work the same for the default settings, and if someone moves to multi-dc they will test it before pushing to production and should see the exception if used in that way. We should try it with our own tests first, might be some consequence I haven't thought of.

**Comment by ktoso** [comment]
Yeah, overly careful phrasing there... Hope we can just make-it-so :)

**Comment by patriknw** [comment]
I'll give this a try.
