### ISSUE TITLE
move data-center config property

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23312]
Shouldn't `data-center = "default"` be moved into the new `multi-data-center` section?

I'm not sure what a good name would be

`multi-data-center.data-center` is kind of repeating itself?

`multi-data-center.self-data-center` ?

cc @johanandren

**Comment by johanandren** [comment]
`multi-data-center.name` ?

**Comment by patriknw** [comment]
could work, I was thinking that we already have `cluster.selfDataCenter` that is defined by exactly this property

**Comment by johanandren** [comment]
Good point. I vote for that one.
