### ISSUE TITLE
Create zero-copy constructor to create ByteString from external Array

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23320]
In many cases, you want to create a `ByteString` from an Array without extra copying. This is less safe than the default version because a user can pass in an array and mutate it afterwards. I'd suggest to create these methods in `object ByteString`:

```scala
def fromArrayUnsafe(bytes: Array[Byte]): ByteString = ByteString.ByteString1C(bytes)
def fromArrayUnsafe(bytes: Array[Byte], start: Int, len: Int): ByteString = ByteString.ByteString1(bytes, start, len)
```
In spray we had this extra accessors to get access to those methods:

https://github.com/spray/spray/blob/master/spray-util/src/main/scala/akka/spray/package.scala

**Comment by ktoso** [comment]
I'd be ok with adding them with such names (`Unsafe`) - the questions comes up every now and then, and is pretty understandable. Such method names would explain well enough what it's doing and "you're on your own", so +1 from me.

**Comment by jrudolph** [comment]
Yeah we should also add documentation that further explains why they are unsafe and what not to do.
