### ISSUE TITLE
FlightRecorder event ID 91 used twice in artery

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23323]
It seems one of the IDs is used twice: https://github.com/akka/akka/blob/dcd8cea32e253e0eb0017cec92d5ef7863ca0513/akka-remote/src/main/scala/akka/remote/artery/FlightRecorderEvents.scala#L48-L49

As it isn't documented in any way I guess that's a bug?

**Comment by johanandren** [comment]
Looks like a mistake yes
