### ISSUE TITLE
Doc emitting a ByteString over TCP isn't one to one with reading it

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23325]
Seen in the [gitter channel](https://gitter.im/akka/akka?at=596342d3329651f46e707a8c): users expecting that if they emit one byte string from the stream TCP server or client they would get that same `ByteString` on the other side. It hadn't occurred to me before but maybe we should try to document this more clearly somewhere. API docs or manual, not sure.

**Comment by cuzfrog** [comment]
Thanks for the attention.

I think there are several points that need to be made clear:
1. Is it possible or practical to preserve elements barrier (or frame) of those through tcp flow?
2. If point 1 cannot/should not be achieved, what deserve to be written into doc or manual:
a. What will lead/contribute to frame concatenation. (buffer, communication quality, etc?)
b. In which situation should which delimiter be recommended. (reserved unicode bytes?)

I'd like to contribute, though I have little idea about underlying implementation, could anyone offer some quick hints to help start out?

**Comment by johanandren** [comment]
Framing is what already is in the docs, because that is how you _have_ to do it, TCP is just a stream of bytes (there is flow control, buffers, packet size limitations etc.), that you emit a chunk of bytes (`ByteString`) does not mean that chunk of bytes will arrive on the other side at the same time and become a corresponding chunk, the incoming bytes will be emitted in the stream as soon as they arrive.

To achieve elements over a byte stream _you always_ have to do some kind of framing, which is exactly what all the examples in the docs does already, so that is definitely doable:
http://doc.akka.io/docs/akka/current/scala/stream/stream-io.html#working-with-streaming-io

**Comment by cuzfrog** [comment]
Yes they are dable, including `Framing.lengthField` which could be easily used to build a bidi-framing-protocol, which is what I did.

But those in current doc point towards text new line, not so clear. The inconsistency mentioned above
sort of makes flows unconfortable.

As far as I know. Tcp should be rather low level in this question, as by `actor-remote`, probably, elements boundary could be preserved inside akka stream implementation. Chunk(element) size could be much
larger than tcp packet. You comment did not make these points(proposed above) clear. Later I may have a look at implementation detail. Thanks anyway.

**Comment by cuzfrog** [comment]
So, framing info is faded "naturally" in `TcpConnection`:

```scala
def doRead(info: ConnectionInfo, closeCommander: Option[ActorRef]): Unit =
  if (!readingSuspended) {
    @tailrec def innerRead(buffer: ByteBuffer, remainingLimit: Int): ReadResult =
      ...
      buffer.limit(maxBufferSpace)
      val readBytes = channel.read(buffer)
      ...
      if (readBytes > 0) info.handler ! Received(ByteString(buffer))
```

now, to make communication synchronous seems less practical here. So a more detailed doc may help.

**Comment by johanandren** [comment]
Thanks @cuzfrog !
