### ISSUE TITLE
DDataShardCoordinator does not cooperate between 2.4.18 and 2.5.3 nodes

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23338]
Instead, there are dead letters and recurring log messages like this:

```
[ERROR] [07/11/2017 13:05:08.016] [ActorSystem-akka.actor.default-dispatcher-2] [akka.tcp://ActorSystem@127.0.0.1:2551/system/sharding/CounterCoordinator/singleton/coordinator] The ShardCoordinator was unable to get an initial state within 'waiting-for-state-timeout' (was retrying): 5000 millis
```

The [migration guide](http://doc.akka.io/docs/akka/current/scala/project/migration-guide-2.4.x-2.5.x.html) seems to imply that this kind of rolling upgrade / migration should be possible.

**Comment by jrudolph** [comment]
According to http://doc.akka.io/docs/akka/current/scala/project/migration-guide-2.4.x-2.5.x.html#distributed-data only ddata keys of type `String` are wire-compatible between 2.4 and 2.5. The `DDataShardCoordinator` uses keys of type `ShardCoordinator.internal.State` which might be the reason that it breaks. I'll try to verify that hypothesis.

**Comment by jrudolph** [comment]
It seems (one of) the reason is that 2.4.x DDataShardCoordinator used the default replicator while 2.5.x uses a dedicated replicator per role.

**Comment by jrudolph** [comment]
Using the default replicator in 2.5.3 seems to fix this for me but I don't know about potential further incompatibilities. We might be able to add a legacy mode (e.g. by adding a relay actor at the path of the default replicator) but I'm not sure if it's worth it.

@patriknw wdyt?

**Comment by patriknw** [comment]
I would just add a note in migration guide that rolling upgrade from 2.4 sharding with ddata mode to 2.5 is not supported. Full restart required.

**Comment by jrudolph** [comment]
Ok, thanks.

**Comment by jrudolph** [comment]
Outdated by now.
