### ISSUE TITLE
Additional test for active multi-dc heartbeatsender to activate on other node if oldest goes away

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23340]
Add a multi-dc test wherein a node that was monitoring the other DC now goes away (leave is fine) and then we check that a different node (e.g. 3rd oldest, if config was 2 oldest nodes monitoring) steps up and becomes active in monitoring

**Comment by johanandren** [comment]
Hmmm, isn't that covered by the `MultiDcFewCrossDcSpec`?

**Comment by ktoso** [comment]
Oh, did not review that, will look

**Comment by ktoso** [comment]
Uff, you had me worried there - it's a bit similar indeed, not quite the same though.
What I want to test specifically is the "back then not oldest node" which has a heartbeat-sender in "dormant" state, that it becomes "active" when it notices that an old member has lest left its dc and suddenly it now is the top-n-oldest itself. It's a specific state transition there that currently does not really have test coverage :)
