### ISSUE TITLE
Need support for custom trust manager implementations in akka-remote

### ISSUE THREAD

**Issue by mnordie** [akka/akka#23358]
Need to be able to load a custom TrustManager extending X509ExtendedTrustManager and initialize the SSLEngine to perform hostname validation.
This would solve the hostname verification from #13874" SSL/TLS: Add client-side certificate verification to akka-remote" and #21669 "Provide support (and/or documentation) for TLS certificate pinning with (old) akka-remote".

**Comment by jrudolph** [comment]
Thanks for the ticket, @mnordie. I think we talked about that before and agreed that we need that functionality.

**Comment by mnordie** [comment]
Hey @jrudolph, when/if you have the opportunity, please have a look at my feeble attempt at solving this.
I added a java interface as we use java exclusively and to my understanding I can't implement scala traits in java.

Another issue is mutual authentication. At the moment the server side will not get a remoteAddress so the hostname validation will be disable for that side regardless of the value of require-mutual-authentication.

As you can see it's not done but I wanted to get it up to get some feedback.

**Comment by raboof** [comment]
I think the general approach looks OK, though not quite sure yet about the exact `CustomTrustManagerFactory`/`TrustManagerReflectionHelper` types and implementation.

Could we split support for hostname verification and support for custom trust manager implementations into 2 separate issues?

**Comment by jrudolph** [comment]
I agree with @raboof, let's split it up into two issues. I created https://github.com/akka/akka/issues/23565 to track hostname validation.

@mnordie, could you split your changes up? You can already open up a PR with the changes even if it's done yet, just mark it as WIP. Commenting is easier to do on a PR than on individual commits of a branch.

**Comment by mnordie** [comment]
Split up the commit so the custom trust manager is here only, and the hostname validation is in  #23565.
We need both though as our custom trust manager depends on hostname validation.

**Comment by andrewkerr9000** [comment]
Related, more general issue #23732

**Comment by johanandren** [comment]
Fixed by #24932
