### ISSUE TITLE
Mandatory preStart implementation in Custom GraphStage of type SinkShape

### ISSUE THREAD

**Issue by fhalde** [akka/akka#23350]
Would it make sense to have the `preStart` as an abstract method in `GraphStageLogic`

The reason why is because, we had created a custom `Sink GraphStage` but had forgotten to do a `preStart`. Because of this there was no demand and we kept trying to figure out what went wrong.

Now it makes sense not to have the `preStart` for `Source and Flow` always, but for `Sink` it is important to have a first pull.

Had the `preStart` been an abstract method, a compilation error would've been thrown making the developer aware of something being missed

**Comment by ktoso** [comment]
Using the same logic all callbacks would have to be abstract making it somewhat bloated. The hooks are also like the current Actors so they should be somewhat familiar. 

> Now it makes sense not to have the preStart for Source and Flow always, but for Sink it is important to have a first pull.

And GraphStage is the single abstraction underlying all of them - so as you see, 2 out of 3 don't need to initially do stuff :-) A first pull also does not have to happen in starting - some Sinks only pull once external conditions, or time has passed, so it's not as universally true that all sinks will do the pull - thinking about where to pull is part of implementing the Stage (for better or worse :-))

Such change would be also binary and source breaking so we can not introduce it without calling Akka 3.0, so not quite enough weight in this one to call such big change.

I'd vote for closing, thanks for your feedback but I don't think this is one we can take action on, sounds fair?

**Comment by johanandren** [comment]
I agree with Konrad.

**Comment by ktoso** [comment]
I'm going to close this for now, but thanks for your feedback - please don't be discouraged by us closing this specific one, keep it coming - thanks!

**Comment by fhalde** [comment]
Sure thing :)
