### ISSUE TITLE
Java API of scheduler should use java.time.Duration instead of scala.concurrent.duration.FiniteDuration

### ISSUE THREAD

**Issue by synox** [akka/akka#23351]
In Akka 2.5.3, as a Java developer I can not directly use the scheduler api, because Scala-Duration is exptected instead of Java-Duration. 

Example: 

```
context().system().scheduler().scheduleOnce(
  scala.concurrent.duration.Duration.fromNanos(config.getDuration("interval").toNanos()), self(),
  new LoadCodes(), context().dispatcher(), self());
```

That is not very intuitive. It would be great if the akka.actor.Scheduler#schedule* Methods would be overloaded with the Java equivalent.

**Comment by johanandren** [comment]
Thanks for the suggestion but we have discussed this a couple of times and decided not to, latest time was #20988

**Comment by johanandren** [comment]
At some point I opened a ticket and PR in the scala-java8-compat for a packaged converter though, you can see it here: https://github.com/scala/scala-java8-compat/issues/85 (doesn't seem like anything has happened there in a while though)

**Comment by patriknw** [comment]
Converter would be good, but we haven't changed previous decision about the API
