### ISSUE TITLE
[Typed Docs] Provide documentation on how to Unit Test Behavior

### ISSUE THREAD

**Issue by jlprat** [akka/akka#23362]
In order to help early adopters of Akka Typed, we should provide some documentation on how to write Unit tests for Behaviors.

**Comment by farnoy** [comment]
:+1: There seem to be examples on how to test akka.typed here: https://github.com/akka/akka/blob/master/akka-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala

But the package `akka-typed-test` does not publish any of these utilities (like TypedSpec)

**Comment by hseeberger** [comment]
+1
I'm utterly confused.

**Comment by patriknw** [comment]
Closing, will be covered by #23667
