### ISSUE TITLE
Akka.io broken link for migration guide

### ISSUE THREAD

**Issue by dluc** [akka/akka#23368]
Page: http://akka.io/blog/news/2017/04/13/akka-2.5.0-released

Page text:
> When migrating a code base to Akka 2.5 please refer to the migration guide in order to profit from some of the improvements.

Broken link: http://doc.akka.io/docs/akka/2.5/project/migration-guide-2.4.x-2.5.x.html
Correct link: http://doc.akka.io/docs/akka/2.5/scala/project/migration-guide-2.4.x-2.5.x.html

**Comment by johanandren** [comment]
Thanks for letting us know!
