### ISSUE TITLE
Document what stages implement supervision

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23376]
Currently there isn't really a way to know what stages care about the supervision strategy attribute. 

We should document clearly that it isn't omnipresent like it is with actors here, and also update the "these are the three stages that doesn't support supervision yet": http://doc.akka.io/docs/akka/current/scala/stream/stream-error.html#error-handling

We should also add in the scaladoc on for each stage if it does heed the supervision strategy or not.

**Comment by ktoso** [comment]
Yes, let's do this and also document the ways to restart otherwise
