### ISSUE TITLE
Cookbook sample of shutdown source on backpressure

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23375]
@jroper opened akka/akka-stream-contrib#110 about having upstream canceled after a back pressure timeout and then restart a source when there is demand again, and described how it is possible to do the same using `backpressureTimeout`. I think this would be an excellent example for the streams cookbook section.

**Comment by ktoso** [comment]
Sounds good, I agree - may even have someone who wants to contribute this ;)

**Comment by richardimaoka** [comment]
Let me work on this
