### ISSUE TITLE
Akka 2.4.10 Consumer Threads in each node after split brain dont merge after cluster nodes merge

### ISSUE THREAD

**Issue by VaishaliDP** [akka/akka#23388]
I am currently using Akka 2.4.10 in my product. I am facing the cluster split brain scenario. After the cluster merges the consumerThreads in the nodes dont merge and act separately. The singleton in cluster is lost.
The threads are not acting in singleton.

**Comment by johanandren** [comment]
This doesn't quite make sense to me, you think you can try and describe what happened more detailed? 
 
 * Are you using `auto-down-unreachable-after`?
 * How did the cluster merge if you had a split brain scenario? 
 * What are "consumerThreads" and what do you mean with them merging? (It is not an Akka concept)
 * What do you mean with the "threads are not acting in singleton"?

Also, note that regardless of this Akka 2.4.10 is relatively old, you should try to upgrade to 2.5.3. If you must stay on the 2.4 branch you should try to move to the latest version of that, which is 2.4.19.

**Comment by johanandren** [comment]
Closing this as there was no further communication in a few days. Feel free to reopen and comment on the questions.
