### ISSUE TITLE
CoordinatedShutdown does not remove jvm shutdown hook

### ISSUE THREAD

**Issue by merlijn** [akka/akka#23384]
We found that in unit tests when we create multiple actor systems after we exit sbt (the jvm) there are multiple console outputs like this. 

```[INFO] [07/20/2017 10:52:56.423] [Thread-23] [CoordinatedShutdown(akka://default)] Starting coordinated shutdown from JVM shutdown hook```

This, even tough we make sure the actor systems are terminated after each test. After a brief look at the CoordinatedShutdown class we think this is because the jvm shutdown hook is never removed after the actor system it shutdown.

**Comment by johanandren** [comment]
As a workaround you can disable the JVM hook by setting `akka.coordinated-shutdown.run-by-jvm-shutdown-hook = off` in your tests.

**Comment by johanandren** [comment]
Actually, after looking at this, it does check if the actor system is terminated, so that probably is a leak in your test suite. I'd recommend that you name your actor system per test, rather than using "default" so you can figure out where it leaks.

**Comment by johanandren** [comment]
To clarify, that the log entry appears means there was an actor system that was not terminated (one for each log entry). 

The problem that is there is related but not the same:

As the JVM hook closes overa reference to the actor system (and the extension which in turn references the system), this will effectively stop the terminated actor system from being garbage collected when `run-by-jvm-shutdown-hook` is on, which it is by default.

I wonder if we could get around this by keeping weak references instead.

**Comment by patriknw** [comment]
Looks valid to try to cleanup references (and perhaps deregister the `initJvmHook`) when the actor system is terminated.

We should try to do that without weak references. Just the existence of weak references can be bad for GC.

**Comment by johanandren** [comment]
I'll give this one another try.
