### ISSUE TITLE
Add support for org.slf4j.Marker 

### ISSUE THREAD

**Issue by 2m** [akka/akka#23409]
Current implementation of logging with actors allow creating markers [only with a name](https://github.com/akka/akka/blob/b80ee5e3d380e0b3cbd7b4b6144cfc89cd0cd22e/akka-actor/src/main/scala/akka/event/Logging.scala#L1411).

We should consider adding an API that allows passing in markers that implement [org.slf4j.Marker](https://www.slf4j.org/api/org/slf4j/Marker.html) Java interface. This interface allows hierarchical relations between markers which is not reflected in the current marker support in akka-slf4f.

**Comment by 2m** [comment]
Documentation on Play's take on logging Markers: https://www.playframework.com/documentation/2.6.x/Highlights26#Logging-Marker-API

**Comment by 2m** [comment]
Initial marker support was added with https://github.com/akka/akka/pull/21707

**Comment by jrudolph** [comment]
I think the current string-based marker scheme was chosen to prevent pulling in a dependency to slf4j. It is probably tough to change the `LogMarker` class to support more than that in a compatible way.

**Comment by ktoso** [comment]
Correct, if the ticket intended to include slf4j things in akka-actor then we cannot do that.
One way we could get around things is to allow Any and some sneaky mechanisms around matching provide by akka-slf4j... at which point one should ask - is it worth the complexity? 

Why not use slf4j directly? Which we often do recommend in any case? Esp. with a nice logback asnyc appender, there is no downside to using it directly - unless I'm missing some interaction with the cinnamon monitoring stack about mdc propagation?

**Comment by ktoso** [comment]
Was able to pull it off, wasn't that difficult actually - I was overworrying that it would have to touch actor :)

**Comment by wsargent** [comment]
@ktoso I'm a bit confused by `StringWithSlf4jMarkerMDC` -- wouldn't you be able to set both a marker and MDC both for a single log event?

**Comment by ktoso** [comment]
I think I don't understand the question? It's just a class in testing, perhaps I was lazy hm

**Comment by wsargent** [comment]
So at https://github.com/akka/akka/commit/00e7f21d66c45a4bcfad6fff0a63a9d37204ab61#diff-cf18908f04a27baba42f3522cb530f8aR31 you can set a marker... but you can't set MDC. But it's called MarkerMDC.
