### ISSUE TITLE
gracefulStop documentation broken

### ISSUE THREAD

**Issue by laszlovandenhoek** [akka/akka#23415]
http://doc.akka.io/docs/akka/current/scala/actors.html#graceful-stop

Two code snippets get glued together (in 4 tabs), which doesn't work and is quite confusing.

This corresponds to /akka-docs/src/main/paradox/scala/actors.md:1018.

**Comment by jrudolph** [comment]
@richard-imaoka any idea what happened here?

**Comment by richard-imaoka** [comment]
Yeah I overlooked that when making my last change to actors.md.
Opened the above pull request to fix the issue.
