### ISSUE TITLE
Scala Kill Documentation

### ISSUE THREAD

**Issue by Brideau** [akka/akka#23421]
In the Actors documentation for [Killing an Actor](http://doc.akka.io/docs/akka/2.5.3/scala/actors.html#killing-an-actor), the code example for Scala is given as:

```
victim ! "kill"
expectMsg("finished")
```
This is just a plain text message that's handled explicitly by receive, and doesn't convey the use of the Kill instance that is the purpose of that section: http://doc.akka.io/api/akka/current/akka/actor/Kill$.html

I would update this myself, but the example snippet seems to be part of the Akka tests, and I'm not familiar enough with the test suite to make the changes.

**Comment by ktoso** [comment]
Good point, and also the kill docs perhaps should be less prominent anyway so I'll move them around.
Thanks for reporting, you can have a look here what the change would have been: https://github.com/akka/akka/pull/23429

We have docs on contributing here: https://github.com/akka/akka/blob/master/CONTRIBUTING.md
Hope this helps and you could submit a PR next time :-)

Thanks for reporting
