### ISSUE TITLE
Java API: AbstractPersistentLoggingFSM should use AbstractPersistentFSM instead of AbstractPersistentFSMBase

### ISSUE THREAD

**Issue by synox** [akka/akka#23436]
In Akka 2.5.3 `AbstractPersistentLoggingFSM` is not java-friendly, because the method `domainEventClassTag()` has to be implemented. 

We did that like this: (or is there a better way?)

```
  @Override
    public ClassTag<EreignisEvent> domainEventClassTag() {
        return ClassTag$.MODULE$.apply(EreignisEvent.class);
    }
```

If it would extend `AbstractPersistentFSM` instead of `AbstractPersistentFSMBase` `domainEventClassTag` would be wrapped.

**Comment by johanandren** [comment]
Ouch, thanks for letting us know. It sounds like an oversight.

**Comment by johanandren** [comment]
Not quite sure if we should break bin comp here as it is obviously wrong, or figure out some way around it. @ktoso wdyt?

**Comment by johanandren** [comment]
@patriknw your input on this would be nice.

**Comment by synox** [comment]
Any news on that? We would like to use it.
