### ISSUE TITLE
Docs: Akka Community links to Scaladex don't return results

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka#23460]
On the following page:

http://akka.io/community/

There are a series of links to Scaladex. These links are currently returning zero results. This gives the impression that there are no community plugins for Akka.

This returns no results:
https://index.scala-lang.org/search?q=keywords:akka-persistence-plugin

However the following will return results:
https://index.scala-lang.org/search?q=akka+persistence+plugin

Seems that the syntax being used for these links is not supported.

**Comment by ktoso** [comment]
Thanks for reporting, closing as duplicate though as it's reported over here for the website: https://github.com/akka/akka.github.com/issues/455 

Would you like to submit a PR fixing the search queries?
It seems scaladex broke compatibility on the query syntax.
