### ISSUE TITLE
Does Akka directive "fileUpload" copies the entire input entity file into memory? 

### ISSUE THREAD

**Issue by mahadev-khapali** [akka/akka#23467]
Does Akka directive "fileUpload" copies the entire input entity file into memory? Is there a way to do multipart upload of large file as 1 GB without consuming 1 GB of memory?

My below code to upload 300MB is consuming 300MB of memory.  Is this expected behavior with "fileUpload" directive?

curl -k -i -X PUT --header --form "csv=@myfile300MB.txt" https://abc/uploadContent

        val uploadFile = File.createTempFile("uploadFile", ".txt")
        extractRequestContext { ctx =>
        implicit val materializer = ctx.materializer
        implicit val ec = ctx.executionContext
        fileUpload("csv") {
          case (metadata, byteSource) =>
            val sumF = byteSource.runFold(ByteString.empty) { case (acc, i) => acc ++ i }.map(s => s.utf8String)

            onSuccess(sumF) { sum =>
              Files.write(Paths.get(uploadFile.getAbsolutePath), sum.toString.getBytes)
              logger.info(StatusCodes.OK + "Successfully completed fileUpload ")
              complete(s"Successfully completed fileUpload") }}
        }

**Comment by johanandren** [comment]
Hi @mahadev-khapali, we use the issue tracker for bugs and feature requests, please use the mailing list https://groups.google.com/forum/#!forum/akka-user or the gitter chat https://gitter.im/akka/akka for questions like this, thanks!

(And yes, if you use fold like that you are collecting the entire upload into memory, you should instead stream it directly to a file sink if you want to avoid that)

**Comment by mahadev-khapali** [comment]
Thanks @johanandren

**Comment by mahadev-khapali** [comment]
@johanandren . Sorry to trouble you here again.  I have posted query in "akka-user" forum but its not yet posted, may be screening for spams.  I am block, your quick suggestion would help me:

With below "extractDataBytes" directive to file sink, I am unable to upload a file greater than 1 KB size.  Where as below "fileUpload" directive to file sink is successful in uploading 700MB file! with same akka-server configuration.   What is wrong with extractDataBytes code?  Any specific configuration for "extractDataBytes" is required? Please assist. 

**extractDataBytes:**

**curl -k -i -X PUT --header token -d @myfile700MB.tar https://abc/uploadContent**

 put {

            implicit val system = ActorSystem("RepositoryService")
            implicit val materializer = ActorMaterializer()
            implicit val executionContext: ExecutionContextExecutor = system.dispatchers.lookup("akka.stream.default-blocking-io-dispatcher")

           withoutSizeLimit {
            (extractDataBytes & extractMaterializer) { (bytes,mat) =>

              val uploadTmp = File.createTempFile("uploadTMP", ".txt")
              logger.info(" Temp absolute path is : " + Paths.get(uploadTmp.getAbsolutePath) + " " +
                Paths.get(uploadTmp.getAbsolutePath).toString)
              try {

                import scala.concurrent.duration._
                import akka.stream.scaladsl.FileIO
                
                  val action = bytes.runWith(FileIO.toPath(uploadTmp.toPath)
                    .withAttributes(ActorAttributes.dispatcher("akka.stream.default-blocking-io-dispatcher")))(mat).map {
                  case ior if ior.wasSuccessful => {
                    val end = System.currentTimeMillis
                    logger.info(StatusCodes.OK + s"${ior.count}" + "bytes written")
                    complete(StatusCodes.OK, "Successfully written to FILE. ")
                  }
                  case ior => complete(StatusCodes.EnhanceYourCalm, ior.getError.toString)
                }
                Await.result(action, 30.seconds)
            
              } catch {
                case ex: Throwable => {
                  logger.info("Exception in writing to file: " + ex.getMessage)
                  complete(StatusCodes.OK, "Exception in writing to file:  ")
                }
            }
          }
        }


**fileUpload**

**curl -k -i -X PUT --header token--form "csv=@myfile700MB.tar" https://abc/uploadContent**
        

 put {
           val uploadFile = File.createTempFile("uploadFile", ".txt")
          (extractRequestContext & extractMaterializer) { (ctx,mat)  =>
            implicit val materializer = ctx.materializer
            implicit val ec = ctx.executionContext

            fileUpload("csv") {
              case (metadata, byteSource) =>

                try {
                  import scala.concurrent.duration._
                  import akka.stream.scaladsl.FileIO

                  val action = byteSource.runWith(FileIO.toPath(uploadFile.toPath))(mat).map {
                    case ior if ior.wasSuccessful => {
                      val end = System.currentTimeMillis
                      logger.info(StatusCodes.OK + s"${ior.count}" + "bytes written")
                      complete(StatusCodes.OK, "Successfully written to FILE. ")
                    }
                    case ior => complete(StatusCodes.EnhanceYourCalm, ior.getError.toString)
                  }
                  Await.result(action, 30.seconds)
                } catch {
                  case ex: Throwable => {
                    logger.info("Exception in writing to file: " + ex.getMessage)
                    //stream.write(s"Exception in writing to file: ${ex.getMessage}".getBytes)
                    complete(StatusCodes.OK, "Exception in writing to file:  ")
                  }
                }
                }

              }
            }
