### ISSUE TITLE
Eventsourced only recovers partially if offered snapshot is not handled

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#23469]
The Eventsourced trait does update the sequence number to the snapshotedt even if the snapshot is not handled by the actor and then continues recovering from there.

This may lead to only partially recovered actors. If the snapshot is not handled the actor should recover from scratch (or fail - would be another option) to prevent such corrupted states.

**Comment by johanandren** [comment]
Thanks @nvollmar !
