### ISSUE TITLE
The docs around GracefulStop seem to be incomplete and/or broken

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka#23468]
The docs on this page appear to have some issues.

http://doc.akka.io/docs/akka/current/scala/actors.html#graceful-stop

Notice that the tabs on the code window are duplicated. There are two Scala tabs and two Java tabs.

Also, the content that shows in the tabs doesn't seem to be related to the gracefulStop technique. They don't seem to show how to use it.

**Comment by sebastianharko** [comment]
I can fix this :-)

**Comment by ktoso** [comment]
Thanks a ton! :-)
