### ISSUE TITLE
Failed: ArteryRemoteNodeDeathWatch

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23481]
https://jenkins.akka.io:8498/job/akka-nightly/4625/consoleFull

```
[JVM-3] *** 1 TEST FAILED ***
[JVM-1] - must cleanup when watching node crash (on node 'first', class akka.remote.ArteryRemoteNodeDeathWatchFastMultiJvmNode1) *** FAILED *** (3 seconds, 19 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for hello7
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:386)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:372)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:831)
[JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23$$anonfun$apply$mcV$sp$25.apply$mcV$sp(RemoteNodeDeathWatchSpec.scala:441)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:355)
[JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply$mcV$sp(RemoteNodeDeathWatchSpec.scala:437)
[JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply(RemoteNodeDeathWatchSpec.scala:425)
[JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply(RemoteNodeDeathWatchSpec.scala:425)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by chbatey** [comment]
We also get: 

[JVM-3] - must cleanup when watching node crash (on node 'third', class akka.remote.ArteryRemoteNodeDeathWatchFastMultiJvmNode3) *** FAILED *** (36 milliseconds)
[JVM-3]   java.util.NoSuchElementException: None.get
[JVM-3]   at scala.None$.get(Option.scala:347)
[JVM-3]   at scala.None$.get(Option.scala:345)
[JVM-3]   at akka.remote.RemoteNodeDeathWatchSpec.identify(RemoteNodeDeathWatchSpec.scala:115)
[JVM-3]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23$$anonfun$apply$mcV$sp$24.apply$mcV$sp(RemoteNodeDeathWatchSpec.scala:430)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:355)
[JVM-3]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply$mcV$sp(RemoteNodeDeathWatchSpec.scala:426)
[JVM-3]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply(RemoteNodeDeathWatchSpec.scala:425)
[JVM-3]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply(RemoteNodeDeathWatchSpec.scala:425)
[JVM-3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-3]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[JVM-3]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)

**Comment by chbatey** [comment]
This looks to be a race where multiple nodes in a multi jvm test get the same port by using:

```
def autoSelectPort(hostname: String): Int = {
    val socket = DatagramChannel.open().socket()
    socket.bind(new InetSocketAddress(hostname, 0))
    val port = socket.getLocalPort
    socket.close()
    port
  }
```

Where JVM 1 gets a port, closes it, then JVM  2 gets the same port before JVM 1 starts its actor system.

**Comment by patriknw** [comment]
That's an interesting finding. Could you check what the default value of `DatagramSocket.getReuseAddress` is? I thought it was `false` by default, perhaps we have to `setReuseAddress(false)`.

**Comment by chbatey** [comment]
It is false by default but we close it in `autoSelectPort` before again re-opening it in aeron. I think SO_REUSEADDR is only applicable if we wanted to bind to the same port at the same time.
