### ISSUE TITLE
Stream throttle not a complete replacement for the TimerBasedThrottle

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23485]
We write in the [migration guide](http://doc.akka.io/docs/akka/current/scala/project/migration-guide-2.4.x-2.5.x.html#timerbasedthrottler), that the `TimerBasedThrottle` can be replaced with:

```
val throttler: ActorRef =
  Source.actorRef(bufferSize = 1000, OverflowStrategy.dropNew)
    .throttle(100, 1.second, 10, ThrottleMode.Shaping)
    .to(Sink.actorRef(target, NotUsed))
    .run()
```

However this does not keep the original sender, so if the destination actor expects to reply something, that message ends up with the internal Sink actor.

(Sprung from this SO question: https://stackoverflow.com/questions/45419519/akka-stream-throttle-and-ask-pattern)

**Comment by patriknw** [comment]
Can't foreach and ordinary tell be used?
Perhaps Sink.actorRef should have a sender parameter?

**Comment by johanandren** [comment]
Foreach and tell is quite a simple solution, I was also thinking along the lines of making `Sink.actorRef` more featureful, but maybe simpler is better in this case.
