### ISSUE TITLE
server-side idle timeout should not fire with active requests for socket

### ISSUE THREAD

**Issue by rdmoore** [akka/akka#23486]
If request-timeout exceeds idle-timeout - e.g., 

>  akka.http.server.request-timeout=10 minutes 
> akka.http.server.idle-timeout=60 seconds

client will get a socket disconnect `Recv failure: Connection reset by peer` while waiting for a long running response from the server.
This seemed to tie these two parameters together in an undesirable way. I would prefer that a socket for which there are outstanding, not-yet-timed-out requests being processed to be busy, not idle.

**Comment by jlprat** [comment]
Hi @rdmoore thanks for the report. This repository is, however, for Akka. Akka HTTP has moved, since some months, to its own repository: https://github.com/akka/akka-http

**Comment by ktoso** [comment]
Moved the issue, please open issues Akka HTTP issues on akka/akka-http.
