### ISSUE TITLE
Ambiguous method call. both error in java8

### ISSUE THREAD

**Issue by guange2015** [akka/akka#23494]
![image](https://user-images.githubusercontent.com/222455/29103106-3cc0363a-7cf0-11e7-8b56-d62fb05353d4.png)

Cluster cluster = Cluster.get(getContext().getSystem());

akka cluster version: akka-cluster_2.12 2.5.3

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by ktoso** [comment]
But it compiles fine, doesn't it?
This looks like an intellij bug in not understanding the override correctly - please open a ticket there: https://youtrack.jetbrains.com/issues/IDEA?q=good%20code%20red%20akka

**Comment by ktoso** [comment]
It's the same issue as: https://github.com/akka/akka-http/issues/1296 which is an intellij issue.
Please upvote this: https://youtrack.jetbrains.com/issue/SCL-12302 (and add a comment)

**Comment by KhalidShah999** [comment]
I found a simple solution for the problem. Simply install the Scala plugin from JetBrains:
File -> Settings... -> Plugins -> Install JetBrains plugin... -> search for Scala.
After restarting the IDE the failure is gone.

**Comment by mmkonrad** [comment]
@KhalidShah999 what are your settings concerning jdk, maven and idea version?
Just installing Scala and restarting does not work at all...at least for me :/

I am looking forward to get additional information about this problem aka possible solutions
