### ISSUE TITLE
API changes review for Akka Actor

### ISSUE THREAD

**Issue by lvc** [akka/akka#23508]
The review of API changes for Akka Actor library since 2.3.2 version: https://abi-laboratory.pro/java/tracker/timeline/akka-actor/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker

Thank you.

![akka-1](https://user-images.githubusercontent.com/1517837/29175950-89ff65cc-7dfb-11e7-96d3-0e81903aa07d.png)

![akka-2](https://user-images.githubusercontent.com/1517837/29175944-864ea65e-7dfb-11e7-8ae2-d7f14eb8709f.png)

### See also:

- https://abi-laboratory.pro/java/tracker/timeline/akka-remote/
- https://abi-laboratory.pro/java/tracker/timeline/akka-stream/
- https://abi-laboratory.pro/java/tracker/timeline/akka-testkit/

**Comment by ktoso** [comment]
Oh, cool report :-)
We're using our own tooling to check binary compatibility too btw, MiMa: https://github.com/typesafehub/migration-manager/

In general releases are aimed to be 100% compatible, with the exception of `@ApiMayChange` and internal methods. I guess the above tool does not know which methods are internal (we mark them as `@InteralApi` or with `private[akka]` etc), but very interesting one definitely, thanks for sharing :)

Not sure what to do with the ticket though, not really actionable other than good info for us that such tool exists hm :)

**Comment by patriknw** [comment]
Thanks for the info. Closing since there is no more action from our side.
