### ISSUE TITLE
Java PubSub Put sample is incorrect

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23503]
The first sample in this section http://doc.akka.io/docs/akka/current/java/distributed-pub-sub.html#send incorrectly implies that there should be a `SubscribeAck` to a `Put` (the corresponding Scala sample is correct).

**Comment by johanandren** [comment]
This is really strange though, because the sample Java code was actually fixed 2017-01-23, so why is there an old code snippet in the docs?

**Comment by johanandren** [comment]
Regenerated the docs from the 2.5.3 tag, and they look correct, so must be some cached generated content somehow leaking into the published docs. We will soon release 2.5.4 let's keep an eye on this sample in the newly published docs.

**Comment by patriknw** [comment]
strange, since releases are cut from clean git repo

**Comment by johanandren** [comment]
Closing this as we didn't see this happening again.
