### ISSUE TITLE
A problematic Akka cluster orchestrator startup scenario

### ISSUE THREAD

**Issue by huntc** [akka/akka#23502]
A problematic scenario for Akka cluster under the influence of orchestration:

1. An Akka cluster service starts and registers itself with an orchestrator such that it has started successfully.
2. The orchestrator kicks off a second instance of the service whereupon it resolves the location of the first for the purposes of seeding.
3. Prior to the second instance contacting the first in order to join the cluster, the first instance terminates for some reason (let’s say some error occurred).

We now have a situation where the second service cannot join any cluster.

I think the ultimate solution to this problem is away from orchestration. Orchestration itself can provide guarantees in terms of the order of startup, but it isn’t aware of what it is coordinating the startup of.

A configurable option could be for Akka to shut down fast if all of its list of seed nodes are "invalid". This would then have the effect of causing the orchestrator to re-schedule the Akka cluster process and again join with any newly known seed nodes.

Note that an "invalid" node could be considered one where a connection is obtained, but the reply is unexpected e.g. the reply could be a valid Akka remote port but for an entirely different system.

**Comment by patriknw** [comment]
Detecting "invalid" nodes can be difficult, since we don't want to require a specific order of starting the nodes, i.e. some attempts will result in no reply. 

A simple solution that I think should solve the problem is to add a timeout => shutdown to the join seed nodes process. If it's still not a member after retried attempts to join the timeout should result in shutdown, and orchestration tool can restart with new set of seed nodes.

**Comment by huntc** [comment]
> A simple solution that I think should solve the problem is to add a timeout => shutdown to the join seed nodes process. If it's still not a member after retried attempts to join the timeout should result in shutdown, and orchestration tool can restart with new set of seed nodes.

Orchestration won't know whether to restart with an empty set of seed nodes unless the second instance (in my example) shuts down relatively quickly. This implies to me that the timeout would have to be short.

Also, this is something we observed at a customer site:

> Note that an "invalid" node could be considered one where a connection is obtained, but the reply is unexpected e.g. the reply could be a valid Akka remote port but for an entirely different system.

i.e. orchestration had delivered an IP and port that was no longer valid, but became the IP and port of another Akka remoting based service.

**Comment by patriknw** [comment]
Talked to @huntc and the conclusion is that we (Akka team) implement the suggested timeout for the joining process. It will be off by default to not change behavior in patch version. Recommended timeout when used together with orchestration will be tested and documented by Christopher's team.
