### ISSUE TITLE
Allow per-usage configuration of LoggingReceive’s logging level

### ISSUE THREAD

**Issue by danielyli** [akka/akka#23518]
Oftentimes when I’m creating a supervisor–pooled workers actor pattern, I find it’s useful to log message receipts both for the supervisor and the workers, but at different logging levels.  The supervisor would log message receipts at `INFO` level while the workers would log at `DEBUG` level.

Right now all message receipts are `DEBUG` level.  It’d be convenient to have something like this:

```scala
// Logging at `INFO` level
def receive = LoggingReceive(LogLevel.Info) {
  ...
}

// Logging level defaults to `DEBUG` if not specified
def receive = LoggingReceive {
  ...
}
```

**Comment by danielyli** [comment]
As a bonus, it’d be convenient to specify what the default logging level is for receipts, in case some project would like it to be something other than `DEBUG`:

```hocon
akka {
  actor {
    default-receive-loglevel = INFO
  }
}
```

**Comment by patriknw** [comment]
@danielyli `LoggingReceive` already has a `logLevel` parameter so I'm not sure I understand what you are missing.

**Comment by danielyli** [comment]
Ah, totally missed that. Thanks.
