### ISSUE TITLE
[Docs] Actors page has broken link

### ISSUE THREAD

**Issue by jlprat** [akka/akka#23517]
http://doc.akka.io/docs/akka/current/scala/actors.html#identifying-actors-via-actor-selection
has a broken link named akka.actor.ActorNotFound  pointing to http://doc.akka.io/docs/akka/current/scala/akka.actor.ActorNotFound.html

**Comment by patriknw** [comment]
@jlprat have you fixed this, or will you?

**Comment by jlprat** [comment]
I will later today 😊
