### ISSUE TITLE
Failed: akka.cluster.StressSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23511]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5165/consoleFul

Note: this ticket is *not* for Artery but classic remoting.

```
[JVM-3] - must use many actors with high throughput (on node 'node-3', class akka.cluster.StressMultiJvmNode11) *** FAILED *** (10 seconds, 184 milliseconds)
[JVM-3]   42 did not equal 0 (StressSpec.scala:1029)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1029)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1016)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1016)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/373/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5009/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/967/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5739/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6260/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5859/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-multi-node-nightly/detail/akka-multi-node-nightly/6495/pipeline

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly2/runs/1256/log/?start=0

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly2/runs/1276/log/?start=0

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3120/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6418/consoleText

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6506/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.5-2.11/56/consoleText

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.5/188/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7371/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7488/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7746

```
failure while attaching new conductor
```

**Comment by ignasi35** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/415/display/redirect?page=changes

Another `StressSpec` failure:

```
use routers with high throughput
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4164

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7918/consoleFull

**Comment by seglo** [comment]
On akka-release-2.5

https://jenkins.akka.io:8498/job/akka-release-2.5/290/consoleText

**Comment by patriknw** [comment]
Let's create a new issue if this happens again in non 2.5 branch
