### ISSUE TITLE
[Docs] Streams "Working with streaming IO" has broken snippet

### ISSUE THREAD

**Issue by jlprat** [akka/akka#23513]
The page uses inline language switch for multi-line code snippets, rendering verbatim the `@scala[...` directives.

Instead of using:
```
@scala[
``` ...
    ...```
]@java[
```...
   ...```
]
```
One could use:
```
@@@ div { .group-scala }
......
@@@
@@@ div { .group-java }
....
@@@
```

See screen shot: ![selection_006](https://user-images.githubusercontent.com/3337739/29207481-933446cc-7e86-11e7-9de2-eed219214ee6.png)

**Comment by johanandren** [comment]
Very unclear why it needs to be separate for Java and Scala. I think we should just use the same port number in both Java and Scala sample code and then have a single echo box.

**Comment by jlprat** [comment]
Yes, that makes sense

**Comment by jlprat** [comment]
If nobody is working on this one, I'll take it. I'll also look around for more occurrences of wrong usage of the inline snippet directive
