### ISSUE TITLE
Akka Streams: Utility function for side effects

### ISSUE THREAD

**Issue by htimur** [akka/akka#23512]
For the moment for performing side effects without value transformation, the only possibility is to use `map`:
```scala
mySource
  .map { elem => println(elem); elem }
  .via(TranformationFlow)
  .map { elem => println(elem); elem }
```
If this is done in multiple places, the code starts looking ugly with all the repetition.

What if we will implement something like [`doto`](http://highlandjs.org/#doto) function in `Highland.js`, which performs the side effect operation and reemits the value downstream.

For example:
```scala
mySource
  .doto(println)
  .via(TranformationFlow)
  .doto(println)
```

**Comment by ktoso** [comment]
I personally wanted this a few times as well. In our terminology terms it'd be a `foreach` IMHO

**Comment by johanandren** [comment]
What about `.alsoTo(Sink.foreach(sidefect))`?

**Comment by ktoso** [comment]
On one hand yeah that does it, on the other though - when actually working on things I never thought of doing this and I hope I know the APIs we'll.. I'd do a map with side effecting inside, as many do. So I do think it would be useful enough to include. Esp tfor newcomers

**Comment by johanandren** [comment]
One counter argument could be that we shouldn't encourage sideffecting as that needs to be thread safe. For debug logging like in these samples, which is the case here, there already is `.log`, no?

**Comment by htimur** [comment]
`.log` is good enough for logging, but in my case I often have the need to report metrics between multiple stream stages and not couple metrics reporting with the logic of the flow, therefore the proposed solution is more flexible.

I agree that we should not encourage side effecting, but flexibility and usability of the api is more important in my opinion, as you already should thing about thread safety on any stage performing side effects, including `map` or any other operation.

**Comment by patriknw** [comment]
I'm on the fence. On one hand `foreach` is already a known concept, but on the other hand the amount of operations might grow a lot if we start to add such convenience.

Someone will probably want `foreachAsync` also.

**Comment by LukeDefeo** [comment]
+1 i would like this for the purpose of reporting metrics

**Comment by ktoso** [comment]
While for metrics actual metrics tools should be used rather, I do agree that "do some side effect" is popular enough, be it report into some metrics or do something else...

I think foreachAsync would not be needed since that then requires a thing to be returned anyway, and that's the "hassle" we have with mapAsync so we'd direct people to there then.

**Comment by huntc** [comment]
Something I'm trying out - please let me know if I'm missing something, but this should be pretty much as efficient as `map` i.e. no context switching... right?

```scala
val receivedPacketsMetric = metricsRegistry.counter("lora-server.received-packets")
val receivedPacketsCounter = Flow.fromFunction[Udp.Received, Udp.Received] { message =>
  receivedPacketsMetric.inc()
  message
}
```

...and then in my stream:

```scala
Source
  .actorRef[Udp.Received](receiveBufferSize, OverflowStrategy.dropHead)
  .via(receivedPacketsCounter) // My 'via's are where metrics are dealt with
```

WDYT?

**Comment by ktoso** [comment]
That is exactly a `map`... :P 

In other news, seen this quite a lot in user code recently so would like to revive the idea of this (can contribute later today), `foreach`.

People use this to emit metrics or events to the event stream, I've seen it enough in the wild to be convienced it's an useful addition

**Comment by fatihcataltepe** [comment]
@ktoso are you working on this ticket, or can I start on it?

**Comment by ktoso** [comment]
There is an existing PR as you can see above your comment ;-)

![akka_streams__utility_function_for_side_effects_ _issue__23512_ _akka_akka](https://user-images.githubusercontent.com/120979/37573283-7fe291ca-2b59-11e8-984a-9d95f7aca89b.png)

**Comment by ktoso** [comment]
I noticed you're looking for some ticket to work on :) You can try going over the https://github.com/akka/akka/labels/help%20wanted and https://github.com/akka/akka/labels/good%20first%20issue tickets though the ones that are not in progress :)

**Comment by ktoso** [comment]
The new operator is called `wireTap` and will be in 2.5.13
