### ISSUE TITLE
Don't mark Actor.aroundReceive as internal API

### ISSUE THREAD

**Issue by fbe** [akka/akka#23525]
In Akka 2.5 the protected around* methods in akka.actor.Actor are designed for adding own interceptors - except the aroundReceive method which is marked as "INTERNAL API".

Shouldn't be the aroundReceive method "public" api, too? Writing own message interceptor chains is, as far as i know, not possible without overriding aroundReceive - especially because Akka 2.5 dropped the ReceivePipeline.    

Is there any reason why the aroundReceive method has to stay as internal api?

**Comment by patriknw** [comment]
All `around` methods are `protected[akka]` and should have the INTERNAL API (and `@InternalApi`) markers.

The reason we have them internal is that we have considered it too easy to shoot oneself in the foot with this powerful tool. I think that position still stands and we haven't hear much requests for making it public.

**Comment by johanandren** [comment]
Clarified in API-docs, so closing this.

**Comment by epitka** [comment]
So how would one go about implementing some code that needs to be run after each receive of specific type of message, without requiring developer to call base method.  I am trying to write some frameworkish code that would not require implementors to know about Akka.Net.
