### ISSUE TITLE
akka.io.TcpConnectionSpec.An outgoing connection must report failed connection attempt when target is unreachable

### ISSUE THREAD

**Issue by raboof** [akka/akka#23528]
expected `CommandFailed(Connect(/127.0.0.1:43368,None,List(),None,false))`, found `Connected(/127.0.0.1:43368,/127.0.0.1:43368)`

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5176/testReport/junit/akka.io/TcpConnectionSpec/An_outgoing_connection_must_report_failed_connection_attempt_when_target_is_unreachable/

**Comment by raboof** [comment]
Looks like binding on port '0' isn't very good at avoiding collisions:

```
import java.nio.channels._
import java.net._
def another() = {
            val serverSocket = ServerSocketChannel.open().socket()
            serverSocket.bind(new InetSocketAddress("127.0.0.1", 0))
            val port = serverSocket.getLocalPort
            serverSocket.close()
            port }

Array.fill(150)(another()).groupBy(identity).filter { case (port, occ) => occ.size > 1 }
res21: scala.collection.immutable.Map[Int,Array[Int]] = Map(42677 -> Array(42677, 42677), 38637 -> Array(38637, 38637))
```
So it appears to 'wrap around' faster than we'd expect

**Comment by raboof** [comment]
Hm might just be 'birthday paradox'-style bad luck. One trick might be to use the fact that generally all of `127.0.0.0/8` is reserved for loopback addresses, perhaps we should choose from a wider pool of addresses.

**Comment by johanandren** [comment]
Closing this as it was merged.
