### ISSUE TITLE
Restart-Source,Sink,Flow add a way to track restart Events

### ISSUE THREAD

**Issue by schmitch** [akka/akka#23532]
Currently there is no way to know if a restart happened.
If a stream failed due to an error, one can just issue use a Supervision Strategy.
However that does not work if the stream closed without any errors at all, considering a Tcp.outgoingConnection, whenever the tcp stream closes, there is no way to check if a restart happened, because Tcp.outgoingConnection won't fail the stage on a clean shutdown.

Well it would be great to return maybe a `Try[Done]` which will either return the failed message or the successfuly close.

**Comment by raboof** [comment]
I'm not sure I understand what situation you are looking for here. Would this be fixed with https://github.com/akka/akka/issues/23908 ? Closing since this ticket is kind of old, feel free to reopen with more details when you are still interested.
