### ISSUE TITLE
FAILED: camel ActorProducerTest

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23549]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/301/testReport/akka.camel.internal.component/ActorProducerTest/ActorProducer_when_synchronous_when_manualAck_when_response_is_Ack_must_process_the_exchange/
https://jenkins.akka.io:8498/job/akka-nightly-2.12/301/consoleFull

```
[info]       - must process the exchange *** FAILED *** (10 seconds, 13 milliseconds)
[info]         java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
[info]         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:183)
[info]         at scala.concurrent.Await$.$anonfun$ready$1(package.scala:169)
[info]         at scala.concurrent.Await$$$Lambda$3981/1901305470.apply(Unknown Source)
[info]         at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]         at scala.concurrent.Await$.ready(package.scala:123)
[info]         at akka.camel.internal.component.ActorProducerTest.$anonfun$new$12(ActorProducerTest.scala:80)
[info]         at akka.camel.internal.component.ActorProducerTest$$Lambda$10492/233875926.apply(Unknown Source)
```

Previously, in https://github.com/akka/akka/issues/16406, the same test failed apparently because of GC, this time there was some GC as well but not enough to explain a 10 second delay.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/418/testReport/junit/akka.camel.internal.component/ActorProducerTest/ActorProducer_when_synchronous_when_manualAck_when_response_is_Ack_must_process_the_exchange/

**Comment by raboof** [comment]
(closing as outdated rare failure)
