### ISSUE TITLE
DeadLetterSuppression for Replicator.UpdateSuccess in distributed data

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka#23553]
In my code, I do a Replicate.Update directly before I stop the actor doing the update. This means I tend to get the Replicator.UpdateSuccess as a dead letter.

Is Replicator.UpdateSuccess a good candidate for DeadLetterSuppression? If people agree with this, I can make the pull request.

**Comment by patriknw** [comment]
I think that would be fine. If the message is not handled in a running actor it would be wrapped in UnhandledMessage so that will still be seen (afaik)
