### ISSUE TITLE
Add hostname validation to akka-remote netty TLS/SSL backend

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23565]
Continuation from https://github.com/akka/akka/issues/13874#issuecomment-253551091.

The question is still how valuable that is and how to make it fool-proof to work in both directions as discussed in the above linked comments.

**Comment by mnordie** [comment]
PR for this https://github.com/akka/akka/pull/23568

**Comment by patriknw** [comment]
It's supported by Artery TLS/TCP so I'd say that we'll close this one and recommend Artery if hostname verification is needed.
