### ISSUE TITLE
Docs - Nice to have reference to `AtLeastOnceDeliverySnapshot` on the Persistence - Snapshots section

### ISSUE THREAD

**Issue by joantune** [akka/akka#23564]
Hi!

This would be nice to have a reference to the `AtLeastOnceDeliverySnapshot` in the Persistence -> Snapshots section in the documentation.  
I almost repeated the `AtLeastOnceDeliverySnapshot` 'manually' until I found out via the methods that such a Snapshot already exists.

PS:
In general the documentation of Akka is a bit discouraging, it isn't as concise as Play's (it's more of a Reference one) and one has to wonder if that happens because LightBend sells support to Akka - although I would argue that encouraging a better documentation would actually help to use Akka more and of course the enterprises will have a budget for the support and for the enterprise products.

I would actually open up the Lagom quite like Play is opened, and then simply have an offer to SMBs for access to services and products, instead of locking Lagom to a useless 3 nodes (!) if you want microservices and actors, you're expected to use more than 3, I understand the need to make money out of this, but I think that somehow there's a better way forward. 
Also, you don't know what is the pricing for unlocking Lagom i.e. what's the lightbend subscription and if that value will uphold itself in the future - whenever I see a sales form I guess it's going to be way expensive (and it probably shouldn't for projects that don't make that much money yet, and for the others I'm sure they will be happy to pay more).
This way you guys are setting yourselves up to becoming irrelevant once easier to use and better documented solutions like Microsoft Orleans are ported to Java

**Comment by joantune** [comment]
PPS: Add a coding example of a typical `AtLeastOnceDeliverySnapshot` using a `UntypedPersistentActorWithAtLeastOnceDelivery` - it's probably easy to miss the `setDeliverySnapshot` call when receiving a snapshot in recovery or similar stuff, so why not add an example?

**Comment by raboof** [comment]
Thanks for the suggestion - you might have noticed `AtLeastOnceDeliverySnapshot` is documented under the [At-Least-Once Delivery section of that page](http://doc.akka.io/docs/akka/current/scala/persistence.html#at-least-once-delivery), but indeed it might deserve its own separate subsection, a code example and a forward-link from the general Snapshots section. Would you be interested in contributing?

As for your PS: I'm sad to hear you find the Akka documentation lacking. We spend quite a lot of effort on improving its quality and making it easy to contribute (recently: moving to the markdown-based Paradox, unifying the Java and Scala variations, and adding more tutorial-style 'quickstart' guides), and agree wholeheartedly that in the long run improving the public Akka documentation is the right strategy for attracting support customers as well. As for Lagom, unless I'm mistaken this is also completely free and open source, and it's only the ConductR deployment platform that is indeed proprietary (but free up until 3 nodes mostly for evaluation purposes).

**Comment by joantune** [comment]
@raboof: I will try to get some time after I hit the milestone that I wanted with a system that I have, but I cannot promise anything as it's basically a one man show ATM. 

It's good to know that Akka's trying to better the documentation.
Maybe what is needed is some sprinkling of general use cases - like using actors for batch long running jobs, using actors for <insert typical example - REST API (?)> etc, documented, and then the docs as is as reference documentation.

I didn't know that detail about Lagom. Maybe the glue between Play and Lagom and Akka might be that documentation of Typical use cases and a reference to them from the Play's documentation. Akka is very barebones and has a steep learning curve, which is quite the opposite of Play. Akka can be great but you need to point out the typical use cases and let people figure out the rest.
 One of the reasons why I moved away from Spring and into Play was that the docs that I found were of older versions or very 'reference' like. I remember configuring Spring security, and some months later wanted to change something and struggle again to find out how to do that.

**Comment by johanandren** [comment]
I'll close this as it hasn't seen any activity for a long time (and we have done a lot of work on the docs since)
