### ISSUE TITLE
Documentation:Scala Guide: why var is used instead of val?

### ISSUE THREAD

**Issue by AlexanderArendar** [akka/akka#23581]
I am reading [this](http://doc.akka.io/docs/akka/2.5.4/scala/guide/tutorial_4.html) and in the following piece of code
```
class DeviceGroup(groupId: String) extends Actor with ActorLogging {
  var deviceIdToActor = Map.empty[String, ActorRef]
```
I cannot understand why the `deviceIdToActor` is declared as variable but not as a value. It's a mutable map and after reading this chapter of the guide I cannot see a reason of `var` usage here.

**Comment by ktoso** [comment]
It's an *immutable map*, so it has to be a var.
Watch my talk about what style to prefer: https://youtu.be/vgFoKOxrTzg?t=9m41s (zen of akka, 9th minute)

**Comment by AlexanderArendar** [comment]
Sorry, I am inattentive. Thanks.

**Comment by ktoso** [comment]
No problem :) Welcome to immutable-by-default land :)

**Comment by AlexanderArendar** [comment]
+= made me think it's a mutable map. I use var-s seldom, so forgot that += syntax can be applied to any var.
