### ISSUE TITLE
useRoles ignored for local routee

### ISSUE THREAD

**Issue by mzalewski82** [akka/akka#23602]
similar to [#15042](https://github.com/akka/akka/issues/15042) but happens when useRoles is used, not deprecated useRole

**Comment by johanandren** [comment]
I can't reproduce this with a test in master, neither initial local routees nor created and added after the fact when the roles are missing are used as routees. Additionally there is logic checking exactly this.

Do you have any more details about how/when you have observed this? What Akka version etc?

**Comment by mzalewski82** [comment]
I'm using 2.5.1 but you're right, in 2.5.4 bug is fixed. Thanks
