### ISSUE TITLE
It's very easy to make an akka http routing typo 

### ISSUE THREAD

**Issue by l15k4** [akka/akka#23610]
```
val scalaVersion = "2.12.3"
val akkaVersion = "2.4.20"
val akkaHttpVersion = "10.0.9"
```
I was hunting down an issue where request `http://localhost:8080` or `http://localhost:8080/` for some reason wasn't routed correctly and it turned out that the problem was missing `~` to connect the last Route ` path("health")(complete(StatusCodes.OK))`. It compiled fine though. See the snippet : 
```
  get {
    log.info("IT GOES HERE")
    pathSingleSlash {
        log.info("BUT NOT HERE ???")
        getFromResource("index.html")
   } ~
    path("index.css")(getFromResource("index.css")) ~
    path("ui-fastopt.js")(getFromResource("ui-fastopt.js")) ~
    path("ws")(handleWebSocketMessages(WebSocket.connectWsClient(context.system, m)))
    path("health")(complete(StatusCodes.OK))
   }
```
Supplying the missing `~` solved the problem but it took me a long time to figure that out.

**It's actually not a compiler problem as the last statement is a `Route` itself. But is there any idiomatic way to prevent these things from happening?**

**Comment by johanandren** [comment]
Hi @l15k4, there is a separate issue tracker for akka-http over here: https://github.com/akka/akka-http/issues and additionally this has been adressed with the `Route.concat` directive. Couldn't find that original ticket that lead to `concat` being added with a quick search but I, remember it was someone having the same problem you describe. 

Found this ticket that may be interesting though: https://github.com/akka/akka-http/issues/1020

**Comment by ktoso** [comment]
> Supplying the missing ~ solved the problem but it took me a long time to figure that out.



Which is why all docs are being changed to show `concat(route1, route2, route3)`.

Please open tickets in akka-http though, as Johan said 😉
