### ISSUE TITLE
Java AbstractActor documentation issues

### ISSUE THREAD

**Issue by checat** [akka/akka#23614]
http://doc.akka.io/docs/akka/2.5.4/java/actors.html

> setting the “initial behavior” in the constructor by calling the receive method in the AbstractActor.

> The argument to the receive method is

> there is a builder named ReceiveBuilder that you can use.

> Please note that the Akka Actor receive message loop is exhaustive

> The argument to the receive method is

> The AbstractActor class defines a method called receive, that is used to set the “initial behavior” of the actor.

Above lines were not updated in 2.5, while the provided example is updated.

> provide factory methods on the companion object of each Actor

Above line is copied from Scala. Java example uses static method.

Also, I assume the example in "Recommended Practices" could be rewritten with varargs method (as it's mentioned as more safe):
`return Props.create(DemoActor.class, magicNumber);` instead of  `return Props.create(DemoActor.class, () -> new DemoActor(magicNumber));`

**Comment by johanandren** [comment]
Thanks for noticing and letting us know. Would you be up for a PR fixing it?

**Comment by agolubev** [comment]
As other PRs are in review let me start this one.
