### ISSUE TITLE
FAILED akka.cluster.singleton.ClusterSingletonProxySpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23619]
https://jenkins.akka.io:8498/job/akka-nightly/4745/testReport/junit/akka.cluster.singleton/ClusterSingletonProxySpec/The_cluster_singleton_proxy_must_correctly_identify_the_singleton/

25 second timeout O.o

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/830/testReport/junit/akka.cluster.singleton/ClusterSingletonProxySpec/The_cluster_singleton_proxy_must_correctly_identify_the_singleton/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/325/testReport/junit/akka.cluster.singleton/ClusterSingletonProxySpec/The_cluster_singleton_proxy_must_correctly_identify_the_singleton/

**Comment by johanandren** [comment]
Something merged recently messing with the singleton proxy?

**Comment by raboof** [comment]
I wonder if this has to do with the fact that there's a handover in progress: getting some salient details from https://jenkins.akka.io:8498/job/akka-nightly-2.12/325/consoleText (`https://jenkins.akka.io:8498/job/akka-nightly-2.12/325/consoleText`) shows:

```
36985 [Start -> Oldest]
53930 [Start -> Younger]
33964 [Start -> Oldest]
49742 [Start -> Younger]
36985 [Oldest -> WasOldest]
36985 [WasOldest -> HandingOver]
36985 [HandingOver -> End]
57601 [Start -> Younger]
```
It was a bit unexpected to me that 33964 starts out as `Oldest` - shouldn't it start out as `BecomingOldest`?

**Comment by raboof** [comment]
`53930` was the original seed node so should deterministically become `Oldest`, but is moved to `Up` exactly at the same time as `36985`:
```
[INFO] [09/12/2017 00:41:58.677] [ClusterSingletonProxySystem-akka.actor.default-dispatcher-16] [akka.cluster.Cluster(akka://ClusterSingletonProxySystem)] Cluster Node [akka.tcp://ClusterSingletonProxySystem@127.0.0.1:36985] - Leader is moving node [akka.tcp://ClusterSingletonProxySystem@127.0.0.1:36985] to [Up]
[INFO] [09/12/2017 00:41:58.677] [ClusterSingletonProxySystem-akka.actor.default-dispatcher-16] [akka.cluster.Cluster(akka://ClusterSingletonProxySystem)] Cluster Node [akka.tcp://ClusterSingletonProxySystem@127.0.0.1:36985] - Leader is moving node [akka.tcp://ClusterSingletonProxySystem@127.0.0.1:53930] to [Up]
```

Might be related to the fact that cluster joins are initiated manually rather than through the `seed-nodes` configuration?

**Comment by raboof** [comment]
(another instance of this error but that was before merging the above PR https://jenkins.akka.io:8498/job/akka-nightly/4779/testReport/junit/akka.cluster.singleton/ClusterSingletonProxySpec/The_cluster_singleton_proxy_must_correctly_identify_the_singleton/)

**Comment by raboof** [comment]
(and another https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/836/testReport/junit/akka.cluster.singleton/ClusterSingletonProxySpec/The_cluster_singleton_proxy_must_correctly_identify_the_singleton/)
