### ISSUE TITLE
Not up to date ActorSystem name in Guide

### ISSUE THREAD

**Issue by sajmmon** [akka/akka#23629]
In the description of:
https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/scala/guide/tutorial_1.md

there is consistently used "testSystem" whereas sources use just "test" in:

https://github.com/akka/akka/blob/f38b928e139a11cb92605b496adf1d76fab60e29/akka-docs/src/test/java/jdocs/tutorial_1/ActorHierarchyExperiments.java#L116

**Comment by raboof** [comment]
Hi, thanks for your observation! The Scala version of the example doesn't do any better, either.

I do like `testSystem` a bit better though - perhaps we should make sure to use that everywhere? Would you be interested in contributing?

**Comment by sajmmon** [comment]
sure, I will update source of the example

**Comment by ktoso** [comment]
Thanks!
