### ISSUE TITLE
Typed package and module names

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23632]
Should it be `akka.typed.scaladsl.persistence` or `akka.typed.persistence.scaladsl` ?
At some point we probably want to move persistence (and cluster stuff) to separate artifact, and then I think it has to be `akka.typed.persistence.scaladsl`, which also is similar to what we have for `akka.stream`.

Then we should probably rename `akka.typed.scaladsl` to `akka.typed.actor.scaladsl`.

The artifact names could be:
* akka-typed-actor
* akka-typed-persistence
* akka-typed-cluster

**Comment by ktoso** [comment]
On the deeper package names I think that `akka.typed.[what].[what-lang]` probably makes most sense. It follows the current style of akka streams too.

Also +1 on renaming typed to `typed.actor.`

**Comment by patriknw** [comment]
Another alternative is `akka.actor.typed.scaladsl`, `akka.cluster.typed.javadsl` and that would match artifact names akka-actor-typed, akka-cluster-typed.

A third approach would be to change root package name to `io.akka` and use `io.akka.actor.scaladsl`, `io.akka.cluster.scaladsl` and use `com.lightbend.akka` as artifact group.name.

**Comment by chbatey** [comment]
I don't think we fully agreed on `akka.actor.typed` vs `akka.typed.actor`, the last one we discussed which I thought we were beginning to get consensus on was akka.actor.typed `akka.persistence.typed` etc then have all the typed removed for the next major version / maybe go to lightbend / akka.io

For now i'll go with `akka.actor.typed` etc and we can argue in the PR :)

Do we definitely want separate modules for the scala / java dsl? It makes it a nicer experience in the IDE etc but we will end up with a lot of modules. I won't do that right away but can do it in the same PR if we definitely want it.

**Comment by gosubpl** [comment]
Since we are discussing naming here, can we please include https://github.com/akka/akka/issues/24071 ?
I think it would be good to clarify that area too, as currently it is hard for newcomers which is hurting 'adoption'.
/cc @hseeberger

**Comment by patriknw** [comment]
I vote for akka.actor.typed, akka.persistence.typed. The root pkg chg fits better in a major release, and we will anyway not hide the fact that there will be untyped and typed that coexist.

We should not make separate modules for javadsl, scaladsl. That would explode nr of modules and adapter/common/impl classes would be more difficult.
akka-actor-typed
akka-persistence-typed
akka-cluster-typed

ddata must be in akka-cluster since we use it for receptionist impl.

sharding and singleton could go in separate modules as in untyped, unless we think they are so fundamental that we place them all in akka-cluster?

**Comment by hseeberger** [comment]
I agree with Mr Cluster @patriknw.

I never understood the split of the cluster modules except for DD, because almost every system I build used Sharding and Singleton. PubSub could be moved out, but why?

**Comment by chbatey** [comment]
Okay i'll go with:
```
akka-actor-typed
akka-persistence-typed
akka-cluster-typed
akka-cluster-sharding-typed
akka-testkit-typed
```

I'll leave singleton in cluster for now

**Comment by patriknw** [comment]
+1

sharding is ”big” enough to deserve separate module (it also has dep to persistence)

**Comment by hseeberger** [comment]
Nice!
