### ISSUE TITLE
Akka-remote: netty configuration

### ISSUE THREAD

**Issue by tolikr** [akka/akka#23637]
I used akka-remote version "com.typesafe.akka" % "akka-agent_2.10" % "2.3.14", And one of my project uses netty "io.netty" % "netty-all" % "4.0.13.Final". This project start server inside and listen to some port. This project also starts akka-remote on different port and listen for remote connections to other actor systems. Everything works fine.

But i tried to update scala version to 2.12.2 and akka to "com.typesafe.akka" % "akka-remote_2.12" % "2.5.2". Netty version doesn't changed. And i have notice that settings akka.remote.netty.tcp.maximum-frame-size overrides settings of netty server started by my project. I see this warnings in console:

`2017-09-14 16:11:53,634 [] WARN [akka.remote.transport.netty.NettyTransport] Remote connection to /10.84.34.31:57014 failed with org.jboss.netty.handler.codec.frame.TooLongFrameException: Adjusted frame length exceeds 256000: 1634167139 - discarded`

For remote  i used next settings:
```
akka {
   actor {
       provider = remote
   }
  remote {
    enabled-transports = ["akka.remote.netty.tcp"]
    netty.tcp {
      hostname = "127.0.0.1" 
      port = 4579             
      send-buffer-size = 1024000b
      receive-buffer-size = 1024000b
      maximum-frame-size = 256000b #512000b
    }
  }
}

```

**Comment by johanandren** [comment]
Akka can only use Netty 3, you cannot upgrade that, however as far as I remember, Netty 4 should happily coexist with Netty 3 on the same class path so this should not be a problem.

The Netty used inside of Akka will use the Akka configuration, as you see from the log entry, it does not come from the net server you started in your project but from Akka remoting.

Please use the mailing list or the gitter channel for questions like this and keep the issue tracker for tracking bugs and new features, thanks!

**Comment by tolikr** [comment]
My mistake, the server ports were confused and the request was sent to the wrong port.
