### ISSUE TITLE
Typed cluster / remote receptionist

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23634]
We need a typed replacement for `ActorSelection` (which is seen as an anti-pattern). The idea is to provide a remote "receptionist", a service registry, where parties can get to know of services in the cluster.

Idea:

 * a service is tagged by a typed `ServiceKey`
 * a service provider registers with its local receptionist (which can be an extension)
 * receptionists distribute registrations in the cluster using distributed-data (using the untyped API for now)
 * service users can either ask once or in a subscription for providers using the shared typed `ServiceKey`

**Comment by TisonKun** [comment]
In untyped world, for remote discovery, we lookup actors by `ActorSelection` which doesn't involve a `Cluster`. I'd like to learn whether it is possible to discover remote actors in typed world without launch a `Cluster`.

Besides, I am not sure on "ActorSelection (which is seen as an anti-pattern)". Could you explain it a bit more?
