### ISSUE TITLE
[akka-typed] How to easily create an empty behavior which handles signals?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#23640]
I'm struggling with creating an empty behavior (i.e. one which doesn't handle any messages) which handles signals. 

My first naive approach was `Actor.empty[Nothing].onSignal(...)`, but `onSignal` in only available for immutable and mutable behaviors.

So should I really extend `ExtensibleBehavior`? I guess this use case is quite common, e.g. for the root actor which doesn't handle any messages but watches its child actors. Therefore some easier way would be appreciated.

**Comment by patriknw** [comment]
Looks like we should add `Actor.signal`

```
def signal(onSignal: PartialFunction[(ActorContext[T], Signal), Behavior[T]]): Behavior[T]
```

Contribution is welcome

**Comment by hseeberger** [comment]
OK, I'll give it a try ...

**Comment by hseeberger** [comment]
(can't assign me, but never mind)

**Comment by hseeberger** [comment]
See #23644.

**Comment by hseeberger** [comment]
I haven't found any tests for the DSL in `akka.typed.scala/javadsl.Actor`.

**Comment by patriknw** [comment]
tests are in the akka-typed-tests project, because of dependencies to testkit

**Comment by hseeberger** [comment]
I know, but there are no tests for the DSL. Or am I missing something?

**Comment by patriknw** [comment]
ok, there is a mix of different styles there. Perhaps `DeferredSpec` is a good example. There you see both `StubbedTests` and `RealTests`. For this small feature you don't have to write both, pick one of them that, your choice.

**Comment by hseeberger** [comment]
Hmm ... looking at the tests, I guess the new tests should be added to `BehaviorSpec`, right? But that class utterly confuses me.

**Comment by patriknw** [comment]
that one is not easy to understand (I don't unless I read up on it)
you can create a new `SignalSpec` based on `DeferredSpec`

**Comment by hseeberger** [comment]
@patriknw do we really need all that ceremony? Ain't it enough to use `EffectfulActorContext` like in https://github.com/hseeberger/learning-akka-typed/blob/master/src/test/scala/de/heikoseeberger/learningakkatyped/SeqNoGeneratorSpec.scala#L23?

**Comment by patriknw** [comment]
that would be fine if you can test watch+termination with EffectfulActorContext

**Comment by hseeberger** [comment]
I think I can't :-(

**Comment by hseeberger** [comment]
OK, created a spec according to `DeferredSpec`.
