### ISSUE TITLE
Typed synchronous testing

### ISSUE THREAD

**Issue by chbatey** [akka/akka#23667]
`EffectfulActorContext` / `StubbedActorContext` already allow testing of most things synchronously. 
- [x] Document how to test sync
- [x] Evaluate the different ways to test typed actors
- [ ] Add `expectSpawned` etc methods to the behavior test kit
- [x] Remove all mkCtx from stubbed tests

One use case that is hard to test is when wrapping an asynchronous resource (e.g. DB driver that returns futures) and want use the context ExecutionContext for continuations.

**Comment by johanandren** [comment]
Sounds reasonable to me but OTOH if that is an asynchronous resource then maybe a synchronous test doesn't make much sense?

**Comment by chbatey** [comment]
For the initial pass i'll add a docs page and create an sync testing testkit for behaviours based on the effectful actor context

**Comment by patriknw** [comment]
@chbatey Same here, what is remaining? Is it possible to create additional tickets so that this can be closed?

**Comment by patriknw** [comment]
Closing, and let's create separate tickets for other missing things, or simply add them when we need them.
