### ISSUE TITLE
Consider if watchWith should deliver all custom messages and not just the last registered

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23668]
`ctx.watchWith` can be used to define a user-defined message when watching another ActorRef. However, if you use `watchWith` or `watch` another time for that same actor, the original message gets overwritten.

That's a bit unfortunate because it means you cannot use that feature if watching multiple times with different context is needed. In that case you need to go back to track it manually (which probably isn't worse as the `watchWith` implementation also uses a map to do the association).

On the other hand, what would be the behavior of `unwatch` in that regard?

**Comment by jrudolph** [comment]
I'm now using this workaround in akka-typed code:

```scala
    def watchWith(ctx: ActorContext[AllCommands], other: ActorRef[_], msg: AllCommands): Unit =
      ctx.spawnAnonymous[Nothing](Actor.deferred[Nothing] { innerCtx ⇒
        innerCtx.watch(other)
        Actor.immutable[Nothing]((_, _) ⇒ Actor.same)
          .onSignal {
            case (_, Terminated(`other`)) ⇒
              ctx.self ! msg
              Actor.stopped
          }
      })
```

**Comment by johanandren** [comment]
I think if we do not allow for multiple "watchWith" we should throw an exception on second one or at least make some log noise, now it's like a hidden internal state :/

**Comment by huntc** [comment]
I remain a little confused having read this issue and the API doc...

If I use `watchWith` for the same actor multiple times, but with differing message objects, then will all `watchWith` messages fire when that actor stops?

**Comment by jrudolph** [comment]
No, only the first `watchWith` is allowed, further ones will fail.

**Comment by huntc** [comment]
Thanks for the clarification
