### ISSUE TITLE
Akka Typed: slf4j logging

### ISSUE THREAD

**Issue by francisdb** [akka/akka#23663]
Akka typed comes with this config

```
"akka": {
    "typed" : {
        "loggers" : [
            "akka.typed.DefaultLogger"
        ],
        "logging-filter" : "akka.typed.DefaultLoggingFilter"
    }
}
```

but there is no slf4j implementation available, using `akka.event.slf4j.Slf4jLogger` does not work

From #23326 I understand that users should just be using slf4j directly in typed actors? But I guess `ctx.system.log.[info,warning,...]` is in use by the system itself and would preferably also end up in slf4j?

**Comment by ktoso** [comment]
Periodic reminder that akka typed simply is not done or ready for general consumption yet, and you simply found a thing that is not yet implemented. Thanks for opening the ticket.

Similar as with normal "Untyped" Actors, Akka's logger is simply just a facade and it'd use whichever logger will be configured for it. We'll get to these tickets and solve these questions before Akka Typed will be stable of course.

**Comment by francisdb** [comment]
@ktoso totally aware of that but it's such a great api compared to untyped actors that it's hard to resist using it :-)

**Comment by ktoso** [comment]
Please be warned that things may change then in it still. We welcome early feedback, but want you to be aware that it's not final/stable API yet.

**Comment by johanandren** [comment]
This has changed now, as we pulled out the typed actor system, so I'll close this for now.
