### ISSUE TITLE
Native internal typed ActorRef cannot be watched in adapted actor system

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23678]
As observed in https://github.com/akka/akka/issues/23669.

More generally, there should be a way to adapt ActorRefs both ways. Right now, the implicit assumption is that in an AdaptedActorSystem every typed ActorRef is necessarily a wrapped adapted untyped one that just need to be unwrapped. However, this is not true like for the `FutureRef`.

**Comment by patriknw** [comment]
Not relevant if we do #24149
