### ISSUE TITLE
Provide a serializer for the Receptionist service keys

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23687]
Currently we have made sure it works with Java serialization, but we should have an actual serializer for these.

**Comment by richardimaoka** [comment]
I was looking at this and came up with a couple of questions:

1. Are we using MiscMessageSerializer? If so, `fromBinary` returns `ActorRef[Any]` which should be changed.

https://github.com/akka/akka/blob/034d6c6e6a8dce6bb20fbd17890a1eafd3532b02/akka-actor-typed/src/main/scala/akka/actor/typed/internal/MiscMessageSerializer.scala#L32

3. Like `ActorRef[T]`, in `toBinary` do we convert `ServiceKey[T]` to `String`, and call `getBytes`? 

https://github.com/akka/akka/blob/034d6c6e6a8dce6bb20fbd17890a1eafd3532b02/akka-actor-typed/src/main/scala/akka/actor/typed/internal/MiscMessageSerializer.scala#L27

If yes, we should come up with a string representation from which we can restore the key and type information, assuming `fromBinary` returns an instance of `DefaultServiceKey[T]` as it is currently the only implementation of `ServiceKey`

https://github.com/akka/akka/blob/034d6c6e6a8dce6bb20fbd17890a1eafd3532b02/akka-actor-typed/src/main/scala/akka/actor/typed/internal/receptionist/ReceptionistImpl.scala#L32

**Comment by patriknw** [comment]
The `typeName` of the `DefaultServiceKey` is only used in `toString` and I don't think it's worth keeping that at all.

We can add a serializer for `DefaultServiceKey`, simply represented as the `id: String` in protobuf.

**Comment by jrudolph** [comment]
We could also use the `typeName` to detect incompatible setups. But for now you are right, that it's not needed.

@richardimaoka is that something you want to work on? Seems simple enough. The strategy would be the same as for `ActorRef`, i.e. we don't even need a protobuf wrapper but just serialize the string verbatim. We can still compatibly change the format later on by creating another manifest for a new version.

**Comment by richardimaoka** [comment]
Sure, if you can give me a couple of days, say up to a week, I'm happy to work on this! 😃
