### ISSUE TITLE
Akka Typed Cluster Sharding - what about multi-dc value

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23689]
The normal sharding has a multi-dc option:

```scala
untypedSharding.startProxy(
          typeName,
          settings.role,
          dataCenter = None, // TODO what about the multi-dc value here?
          extractShardId = extractor,
          extractEntityId = extractor
        )
```

We should expose this in the typed APIs. Thinking about making this a setting rather than an additional param though

**Comment by patriknw** [comment]
I think we should support this in the same way as in untyped, you can have multiple proxies pointing to different DCs. We can add that in next iteration of the api.
