### ISSUE TITLE
Typed cluster sharding, handoff message riddle - what of the entityId

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23686]
Consider such domain:

```scala
  sealed trait IdTestProtocol { def id: String }
  final case class IdReplyPlz(id: String, toMe: ActorRef[String]) extends IdTestProtocol
  final case class IdWhoAreYou(id: String, replyTo: ActorRef[String]) extends IdTestProtocol
  final case class IdStopPlz(id: String) extends IdTestProtocol
```
The actor is simply:

```scala
val behaviorWithId: Actor.Immutable[IdTestProtocol]
```

We're not using any envelopes, so the sharding is defined as follows:

```scala
      val ref = sharding.spawn(
        behaviorWithId,
        Props.empty,
        "example-02",
        ClusterShardingSettings(adaptedSystem),
        ShardingMessageExtractor.noEnvelope[IdTestProtocol](10, _.id),
>>>         IdStopPlz("ID") // that's weird... but yeah, would work... <<<
      )
```

Notice the `handOffStopMessage` here. It's pretty weird, because we have to force it into having an ID, yet this message would be created internally and sent "we know where, because we are the sharding manager" etc.

Should we allow doing `id => Message(id, ...)` for those cases?

Note that the `id =>` style is of course not needed when envelopes are used.

**Comment by johanandren** [comment]
Same problem as #23679 ?

**Comment by johanandren** [comment]
Ah, not quite.

**Comment by ktoso** [comment]
Yeah, slightly different - it's about what API to expose in the spawn methods.
The `id =>` maybe isn't too scary and we should "just do it" hm...

**Comment by ktoso** [comment]
Though then perhaps would we need scaladsl/javadsl already? Technically java lambdas will work ok with Scala 2.12 here, but yeah the type would be a Scala function hm...

**Comment by johanandren** [comment]
Should it maybe go as a method in the extractor? That way we can easily provide a default for the envelope one

**Comment by ktoso** [comment]
Hm.. smart idea, would also unclutter the spawn method a bit and one would declare all message things in that type... Could work nicely - what would we call the extractor; it's not quite "extractor" then. Not really an adapter as well..

**Comment by johanandren** [comment]
`EntityProtocol` and then `EnvelopedEntityProtocol` or something in that direction?

**Comment by ktoso** [comment]
Note also: Then we can't make the extractor optional; it would have to be defined even here (which maybe is fine actually):

```
def spawn[A](
    behavior:           Behavior[A],
    props:              Props,
    typeName:           String,
    settings:           ClusterShardingSettings,
    maxNumberOfShards:  Int //,
    /*handOffStopMessage: A*/): ActorRef[ShardingEnvelope[A]]
```

**Comment by patriknw** [comment]
Another related thing is that we should change `behavior: Behavior[A]` to `behaviorFactory: String => Behavior[A]`. We added that in untyped.
