### ISSUE TITLE
Rewrite PersistentActorImpl as a real typed actor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23694]
The first implementation is running the `Behavior` as an untyped `PersistentActor` to be able to use the difficult implementation from untyped EventSourced trait. This has a major limitation. The behavior can't be wrapped in things like `Actor.deferred`, `Actor.supervise`, or `Actor.withTimers`. Because of that limitation this will not be the final approach. I think we have to re-implement the needed parts of `EventSourced` in a real typed Behavior.

**Comment by patriknw** [comment]
Let's start out simple here, without persistAsync and friends.

**Comment by ktoso** [comment]
Okey 👍
