### ISSUE TITLE
Akka Typed Cluster Sharding - use typed keys to store ShardRegion refs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23690]
1. we could keep the shard regions in a typed map like the receptionist does
2. perhaps they should just register in the receptionist!

This would allow the current simple API: `override def entityRefFor[A](typeName: String, entityId: String): ShardedEntityRef[A] = {` to be type-safe, when used with ShardedEntity.key or somethinglike that.

or it would not be needed at all “just use the receptionist with the ShardedEntity.key plz”

**Comment by ktoso** [comment]
Hm, we can't use the receptionist because it's for ActorRefs... But the TypedMap idea still holds, and the receptionist being able to keep those still could be interesting subject to debate.

**Comment by patriknw** [comment]
intesting to explore more
I don't think they belong in the Receptionist though, because you should only talk to the local shard region, and the purpose of the receptionist is the opposite

**Comment by ktoso** [comment]
> I don't think they belong in the Receptionist though, because you should only talk to the local shard region, and the purpose of the receptionist is the opposite

Oh good observation. Perhaps a similar mechanism but "that knows about sharding" could be built... Interesting stuff.

**Comment by patriknw** [comment]
Perhaps just having `entityTypeName` as a real type with `[A]` and the string, instead of only a string, might be a good start. You use the same `entityTypeName` key for both `spawn` and `entityRefFor`.

**Comment by ktoso** [comment]
> You use the same entityTypeName key for both spawn and entityRefFor.

Yeah that's the key and would likely be good enough :)

**Comment by patriknw** [comment]
Looks like we are happy with the EntityTypeKey solution, but I created issue #23708 for additional fail fast check.
