### ISSUE TITLE
FAILED: FlowInterleaveSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23724]
https://jenkins.akka.io:8498/job/akka-multi-node/2321/consoleFull

```
[info] - must eagerClose = true, other stream closed *** FAILED *** (24 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnComplete, found OnNext(2)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:378)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:882)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectComplete(StreamTestKit.scala:414)
[info]   at akka.stream.scaladsl.FlowInterleaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$5.apply(FlowInterleaveSpec.scala:62)
[info]   at akka.stream.scaladsl.FlowInterleaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$5.apply(FlowInterleaveSpec.scala:56)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.scaladsl.FlowInterleaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(FlowInterleaveSpec.scala:56)
[info]   at akka.stream.scaladsl.FlowInterleaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(FlowInterleaveSpec.scala:56)
```

**Comment by patriknw** [comment]
I think that eagerClose PR was merged yesterday

**Comment by jrudolph** [comment]
Another: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5306/consoleFull

**Comment by jrudolph** [comment]
Right, probably related to this PR: https://github.com/akka/akka/pull/22754/files

@evis could you have a look at that one?

**Comment by evis** [comment]
@jrudolph Ok, I will try to look at this at today's evening (at UTC+3).

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4815/testReport/junit/akka.stream.scaladsl/FlowInterleaveSpec/An_Interleave_for_Flow_must_eagerClose___true__other_stream_closed/

**Comment by johanandren** [comment]
@evis I'm guessing you didn't have time to look at this? I'm going to dig into it now, so if you have some insights please let me know, thanks!

**Comment by evis** [comment]
Actually I looked at this, but couldn't fix it still :( I debugged a bit and noticed, that due to some reasons GraphInterpreter#processEvent() method process push event first, and only then processes complete event (you may see it with `debug` variable changed to `true`). I thought, that maybe, it's due to event processing ordering inside `processEvent` (first push and pulls, then completions). So, I tried to move completion block (`if code & ... == OutClosed`) to be above push block (`if code & ... == Pushing`), but that didn't help.

**Comment by johanandren** [comment]
There is a race between the completion of the second input and the next element emitted by the first input. The test tests something we cannot guarantee, I'll update the test to be deterministic.

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5325/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5328/consoleFull
