### ISSUE TITLE
Add log() as an example on handling errors page in Akka Streams

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23722]
As otherwise people often say "akka swallows exceptions" http://doc.akka.io/docs/akka/2.5.4/scala/stream/stream-error.html

**Comment by ktoso** [comment]
Relates to making it louder via https://github.com/akka/akka/issues/23501

**Comment by richardimaoka** [comment]
Will work on this.

Is this a good place to add it?
https://doc.akka.io/docs/akka/current/scala/stream/stream-quickstart.html

([stages-overview.html](https://doc.akka.io/docs/akka/current/scala/stream/stages-overview.html) already has a section for the `log` stage.)

**Comment by ktoso** [comment]
Great, thanks!
