### ISSUE TITLE
recoverWithRetries does not execute alternative source properly

### ISSUE THREAD

**Issue by Sebruck** [akka/akka#23727]
I have a problem where recoverWithRetries shows a surprising behaviour. I am not sure if it is a bug or I am doing something wrong.

My goal is to retry a failing http request if the request or the connection fails.

Consider the following example:

```scala
    def httpConnection: Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] =
      Http().outgoingConnection("127.0.0.1", 13377) // be sure nothing listens on the port

    def fakeConnection: Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] = Flow[HttpRequest]
      .map(_ => throw new StreamTcpException("Fake error from `map`"))
      .mapMaterializedValue(_ => Future.failed(new StreamTcpException("Fake error from `mapMaterializedValue`")))

    val source = Source.single(HttpRequest())
    val f = source
      .via(httpConnection)
      .recoverWithRetries(
        3, {
          case NonFatal(e) =>
            println(System.currentTimeMillis() + s" - Retrying failed request: " + e.getMessage)
            source
              .initialDelay(3.seconds)
              .map(r => {
                println("Emitting request")
                r
              })
              .via(httpConnection)
//              .via(fakeConnection)
        }
      )
      .runWith(Sink.head)

    println(Await.result(f, Duration.Inf))
```

This results in 

```
1506416867888 - Retrying failed request: Tcp command [Connect(127.0.0.1:13377,None,List(),Some(10 seconds),true)] failed because of Connection refused
1506416867911 - Retrying failed request: Tcp command [Connect(127.0.0.1:13377,None,List(),Some(10 seconds),true)] failed because of Connection refused
1506416867917 - Retrying failed request: Tcp command [Connect(127.0.0.1:13377,None,List(),Some(10 seconds),true)] failed because of Connection refused
```  

Please notice that it neither does the delay of 3 seconds nor prints `Emitting request`.

If i now change `.via(httpConnection)` with `.via(fakeConnection)` (which have the identical signature and throw a similar exception), it works as expected:

```
1506417081299 - Retrying failed request: Tcp command [Connect(127.0.0.1:13377,None,List(),Some(10 seconds),true)] failed because of Connection refused
Emitting request
1506417084333 - Retrying failed request: Fake error from `map`
Emitting request
1506417087352 - Retrying failed request: Fake error from `map`
Emitting request
```

Is this an intended behaviour or a bug?

**Comment by johanandren** [comment]
`Http.outgoingConnection` will connect to the server upon materialization, regardless if you wait with feeding it requests. If that connection fails, it will fail the stream, triggering a new `recoverWithRetries`. 

I'd recommend that you carefully read the Akka HTTP docs about the different client level APIs and understand how they work: http://doc.akka.io/docs/akka-http/current/scala/http/client-side/request-level.html

**Comment by johanandren** [comment]
Closing this as it is expected behavior.

**Comment by ktoso** [comment]
I think you may rather be interested in https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/Retry.scala than the stages in Akka core.

At some point we'll pull it in, I think.

I agree this should be closed; for questions like that please use the mailing list, thanks! 
https://groups.google.com/group/akka-user/

**Comment by Sebruck** [comment]
@johanandren @ktoso thanks for the answers! Next time I'll use the mailing list
