### ISSUE TITLE
Make it clear in the documentation, how to acquire a global-scoped address using `Actor.self`

### ISSUE THREAD

**Issue by zzvara** [akka/akka#23742]
I'm stuck currently in acquiring a global address from within an `Actor`, using `self`. The `Actor` sits in a cluster and can receive messages.

The use-case is practically to send the global address through a different system, where, on the other side of that system, an `Actor` in the same cluster would like to send a message back to the original `Actor`. Without a global address I failed to resolve the original `Actor`.

As far as I can tell, I never saw a global address so far. In what circumstances can an `Actor` provide its global address?

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on the gitter channel or the mailing list?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

**Comment by zzvara** [comment]
I think there is still an issue that is code-related, which is that the two optional fields within `Address` is not clear, when and how `Some` or `None` is returned. Probably a `GlobalAddress` or `LocalAddress` would be clear, then the user would be able to look up how to acquire a `GlobalAddress`.

Anyway, I will ask around on other channels, thank you.
