### ISSUE TITLE
Build with jdk9 (but against the jdk8 standard library)

### ISSUE THREAD

**Issue by raboof** [akka/akka#23755]
When building with jdk9, it is not sufficient to pass in `-target 1.8`: this leads to problems such as 

`java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer`

when running under jdk8, because on jdk8 there is no `clear()` on `ByteBuffer`, only on its supertype `Buffer`.

It'd be nice if we could build the entire release (for jdk8 and jdk9) from one sbt invocation.

This particular problem can be fixed by explicitly calling `clear()` on the supertype (as implemented in #23753), but then we'd somehow need to make sure such problems do not occur in other places.

Alternatively we could try and set up sbt so that it builds everything against the 1.8 standard library (with `-bootclasspath`), and only build the jdk9-specific classes without that flag.

**Comment by patriknw** [comment]
I think you are right that it's too risky to build for jdk8 with the jdk9 library. Even if we run all tests it wouldn't mean that we are sure that there aren't any more calls that we haven't exercised in tests.

**Comment by raboof** [comment]
This basically depends on building with sbt 1 (#23093), WiP on that is in the `jdk9-build` branch

**Comment by ktoso** [comment]
Having watched the tooling update at J1 https://youtu.be/VrI6rJNO2x4?t=20m7s reminded me that we should be using the http://openjdk.java.net/jeps/247 "Compile for Older Versions" JEP here.

It's `--target 8` and manages the bootclasspath for us, so it's not as scary as manually handling that (as mentioned on opening post). The "jdk9-only" sources then need to be without that option, we'll figure that out though. Seems to be the recommended way as well.

**Comment by patriknw** [comment]
Done
