### ISSUE TITLE
Actor registered with TestActorRef failed to be found in actor system

### ISSUE THREAD

**Issue by oleg-smith** [akka/akka#23752]
If an actor is created using `TestActorRef.apply()`, it might be failed to resolve by calling actorSystem.actorSelection.resolveOne within a Future.The doc for TestActorRef says it can be used in single-threaded environment, but I wonder what is the certain reason for the following test to fail - because I think it should at least be able to find successfully registered actor in actorSystem.

Akka version: 2.5.4

Minimal test that fails, if run 1000 times with error `akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://test-system/), Path(/user/test-actor)]:`

```
import akka.actor.{Actor, ActorSystem, Props}
import akka.testkit.TestActorRef
import akka.util.Timeout
import org.junit.runner.RunWith
import org.scalatest._
import org.scalatest.junit.JUnitRunner

import scala.concurrent.Await
import scala.concurrent.duration._

@RunWith(classOf[JUnitRunner])
class TestActorRefTest extends FunSuite with Matchers with BeforeAndAfterAll {

  implicit val actorSystem = ActorSystem("test-system")
  implicit val timeout = Timeout.durationToTimeout(3.seconds)

  override def afterAll(): Unit = actorSystem.terminate()

  test("find just created actors") {

    val actorRef = TestActorRef(Props(new TestActor()), "test-actor")
    val timeout = Timeout.durationToTimeout(3.seconds)

    val findFuture = actorSystem.actorSelection(actorRef.path).resolveOne()(timeout)
    Await.result(findFuture, 10.seconds)
  }
}

private class TestActor extends Actor {
  override def receive: Receive = {
    case _ =>
  }
}
```

**Comment by patriknw** [comment]
I don't think we have any guarantees that actorSelection will immediately find a created actor. If you put a Thread.sleep(500) before the `actorSelection` you can probably not reproduce it.

You can use `awaitAssert` retrying such things.

By the way, I would recommend against using TestActorRef and agree with this blog post: https://hseeberger.gitlab.io/2017/09/13/how-to-use-akka-testkit.html

**Comment by johanandren** [comment]
For reference, cross posted (and answered) here on SO: https://stackoverflow.com/questions/46469153/actors-created-with-testactorref-cannot-be-resolved-sometimes/46490861?noredirect=1#comment79979312_46490861

**Comment by richardimaoka** [comment]
Should this issue be closed as the doc already says `TestActorRef` is NOT recommended?

https://doc.akka.io/docs/akka/current/scala/testing.html#synchronous-testing-testactorref

>Note
>It is highly recommended to stick to traditional behavioural testing (using messaging to ask the Actor to reply with the state you want to run assertions against), instead of using TestActorRef whenever possible.

**Comment by johanandren** [comment]
I think so, but wanted to see what if you would come back with something to change our minds :)

Closing then.
