### ISSUE TITLE
Java DSL is missing Compression.gzip and deflate

### ISSUE THREAD

**Issue by jypma** [akka/akka#23766]
[Scala DSL](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/Compression.scala) has `Compression.gzip` and `Compression.deflate`, but these are missing from the [Java DSL](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/javadsl/Compression.scala).

**Comment by agolubev** [comment]
This will be a quick fix. I can take it if no one did

**Comment by jypma** [comment]
Sure, thanks a lot! :)

**Comment by richardimaoka** [comment]
This issue is closed?

**Comment by jypma** [comment]
yupp! Closed by https://github.com/akka/akka/pull/23779
