### ISSUE TITLE
"Delayed restarts with the BackoffSupervisor pattern" section of documentation should show BackoffOnRestartSupervisor

### ISSUE THREAD

**Issue by jasongoodwin** [akka/akka#23767]
https://doc.akka.io/docs/akka/snapshot/scala/general/supervision.html

I believe the section of the documentation "Delayed restarts with the BackoffSupervisor pattern" should actually demonstrate the _BackoffOnRestartSupervisor_ not the _BackoffSupervisor_.

The section describes delayed restarts but the supervision strategy depicted actually won't delay restarts. Further, the behaviour requires _stop_ for the backoff qualities which causes the actors mailbox to be destroyed and makes it unavailable until it starts again so the BackoffOnRestartSupervisor might be the more common use case.

**Comment by johanandren** [comment]
`BackoffOnRestartSupervisor` does the same however. The child gets stopped on failure, and then restarted later, there is no machinery inside of Akka that would allow the actual supervision strategy directive to be restart-but-a-bit-later. (In Akka typed we can likely improve however)

I think I may have mislead you a bit by mentioning the specific class on Gitter, you create both through the same factory object `Backoff.{onFailure,onStop}` so which concrete actor class is used is an implementation detail.

**Comment by jasongoodwin** [comment]
Ah okay. I'll close this then. Thanks.
