### ISSUE TITLE
Avoid risk of resource leak for spawnAdapter

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23770]
When writing [examples for new typed APIs](https://github.com/patriknw/akka-typed-blog/blob/master/src/main/scala/blog/typed/cluster/scaladsl/Counter.scala#L30) I see that spawnAdapter is needed all the time to map message types, e.g. for replies. That is a lot of boilerplate.

New message classes are needed to mirror the external protocol.

The adapters also have a lifecycle so it's not like a stateless function that you can just create inline and throw away if not used. That would leak resources. Therefore it's typically created at the top `deferred` section (far from where it is used).

It would also be nice if the adapter could capture conversational state (to be a better alternative to ask), but that is currently not possible due to the stateful nature of the adapters. If there is no reply it would leak resources if a temporary adapter was created for each request.

**Comment by patriknw** [comment]
Another small thing, sometimes you don't care about the reply, and it would be nice to have an `ActorRef` that just ignores all messages (without sending to `deadLetters`).

**Comment by patriknw** [comment]
One idea for single message request-response would be to have a convenience api that "ask+mapReply+pipeToSelf"

**Comment by dwijnand** [comment]
> One idea for single message request-response would be to have a convenience api that "ask+mapReply+pipeToSelf"

#25966 😄

**Comment by hepin1989** [comment]
refs:https://github.com/akka/akka/pull/25921

**Comment by patriknw** [comment]
@dwijnand i’m not following. Isn’t that ActorContect.ask?

The purpose of pipeToSelf is when the value doesn’t come from an actor, e.g. a gRPC call returning a Future.

**Comment by patriknw** [comment]
That is possible, but I’d recommend context.ask

**Comment by dwijnand** [comment]
Oh, right.  Sorry.
