### ISSUE TITLE
Source code formatter

### ISSUE THREAD

**Issue by raboof** [akka/akka#23778]
When moving to sbt1 we'll have to upgrade scalariform, which unfortunately apparently appears to mean changing some of the formatting rules.

If we're going to do that, then now would be the time to consider another formatter, such as scalafmt.

**Comment by raboof** [comment]
@2m I noticed you filed https://github.com/sbt/sbt-scalariform/issues/72 - do we want different configuration for different subprojects?

**Comment by raboof** [comment]
Ah we have `formattingPreferences` and `docFormattingPreferences`

**Comment by raboof** [comment]
I looked into scalafmt a bit, it seems kind of slow and I'm not sure I liked its formatting better than scalariform. It might be interesting to have a 'scalariform-style' formatter in scalafmt (as alluded to in [this thread](https://www.reddit.com/r/scala/comments/60tygk/scalariform_needs_a_new_maintainer/df9c8z6/), but perhaps it'd be easier to fix sbt/sbt-scalariform#72 instead

**Comment by dwijnand** [comment]
4) Tweak the scalafmt options until it gives you a formatting you like.

Also, you should know there's also https://github.com/lucidsoftware/neo-sbt-scalafmt.
