### ISSUE TITLE
Failed: docs.routing.RouterDocSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#23774]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/851/testReport/junit/docs.routing/RouterDocSpec/demonstrate_broadcast_of_Kill/

**Comment by johanandren** [comment]
4+ seconds of GC just before it `[Times: user=6.85 sys=0.14, real=4.23 secs]` so not so surprising that the 3 second timeout hit. The forked tests that should avoid such monster GC pauses was merged one or two days later, so let's close this one and re-open in the case that it happens again.
