### ISSUE TITLE
Failed: akka.cluster.MultiDcSplitBrain

### ISSUE THREAD

**Issue by 2m** [akka/akka#23775]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5316/consoleFull

<details><pre>
[JVM-4] - must be able to have data center member restart (same host:port) while there is inter data center split (on node 'fourth', class akka.cluster.MultiDcSplitBrainMultiJvmNode4) *** FAILED *** (40 seconds, 39 milliseconds)
[JVM-4]   java.lang.RuntimeException: barrier failed: restarted-fifth-removed
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:222)
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:197)
[JVM-4]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-4]   at akka.actor.FSM$class.processEvent(FSM.scala:665)
[JVM-4]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:157)
[JVM-4]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:801)
[JVM-4]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:157)
[JVM-4]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:659)
[JVM-4]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
[JVM-4]   at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
[JVM-4]   at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:157)
[JVM-4]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
[JVM-4]   at akka.actor.ActorCell.invoke(ActorCell.scala:496)
[JVM-4]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-4]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-4]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-4]   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-4]   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-4]   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-4]   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
</pre></details>

**Comment by chbatey** [comment]
Looking at the barrier logs JVM-2 never enters the `restarted-fifth-removed` barrier causing all the other JVMs to timeout on that barrier.


```
[JVM-2] [DEBUG] [09/30/2017 05:30:07.300] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode2] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] passed barrier fifth-re-joined
[JVM-1] [DEBUG] [09/30/2017 05:30:07.300] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode1] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] passed barrier fifth-re-joined
[JVM-4] [DEBUG] [09/30/2017 05:30:07.301] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode4] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] passed barrier fifth-re-joined
[JVM-3] [DEBUG] [09/30/2017 05:30:07.305] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode3] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] passed barrier fifth-re-joined
[JVM-4] [DEBUG] [09/30/2017 05:30:12.305] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode4] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] entering barriers (restarted-fifth-removed)
[JVM-3] [DEBUG] [09/30/2017 05:30:15.327] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode3] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] entering barriers (restarted-fifth-removed)
[JVM-1] [DEBUG] [09/30/2017 05:30:17.333] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode1] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] entering barriers (restarted-fifth-removed)
``` 

The last thing that the JVM-2 did was the previous barrier then run:

```
 runOn(first, second, third) {
        awaitAssert(clusterView.members.map(_.address) should ===(Set(address(first), address(second), address(third))))
      }
```

So assuming that it was stuck waiting to see all of the nodes in its DC. The awaitAssert never ends as the other JVMs timeout and shut down.

**Comment by chbatey** [comment]
```
[JVM-1] [DEBUG] [09/30/2017 05:30:07.300] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode1] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] passed barrier fifth-re-joined
[JVM-4] [DEBUG] [09/30/2017 05:30:07.301] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode4] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] passed barrier fifth-re-joined
[JVM-3] [DEBUG] [09/30/2017 05:30:07.305] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode3] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] passed barrier fifth-re-joined
[JVM-4] [DEBUG] [09/30/2017 05:30:12.305] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode4] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] entering barriers (restarted-fifth-removed)
[JVM-3] [DEBUG] [09/30/2017 05:30:15.327] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode3] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] entering barriers (restarted-fifth-removed)
[JVM-4] - must be able to have data center member restart (same host:port) while there is inter data center split (on node 'fourth', class akka.cluster.MultiDcSplitBrainMultiJvmNode4) *** FAILED *** (40 seconds, 39 milliseconds)
[JVM-4]   java.lang.RuntimeException: barrier failed: restarted-fifth-removed
[JVM-1] [DEBUG] [09/30/2017 05:30:17.333] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode1] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] entering barriers (restarted-fifth-removed)
[JVM-3] - must be able to have data center member restart (same host:port) while there is inter data center split (on node 'third', class akka.cluster.MultiDcSplitBrainMultiJvmNode3) *** FAILED *** (40 seconds, 63 milliseconds)
[JVM-3]   java.lang.RuntimeException: barrier failed: restarted-fifth-removed
[JVM-1] - must be able to have data center member restart (same host:port) while there is inter data center split (on node 'first', class akka.cluster.MultiDcSplitBrainMultiJvmNode1) *** FAILED *** (40 seconds, 78 milliseconds)
[JVM-4] *** 1 TEST FAILED ***
[JVM-3] *** 1 TEST FAILED ***
[JVM-2] [DEBUG] [09/30/2017 05:30:18.273] [ScalaTest-main-running-MultiDcSplitBrainMultiJvmNode2] [akka.actor.ActorSystemImpl(MultiDcSplitBrainSpec)] entering barriers (restarted-fifth-removed)
[JVM-2] - must be able to have data center member restart (same host:port) while there is inter data center split (on node 'second', class akka.cluster.MultiDcSplitBrainMultiJvmNode2) *** FAILED *** (41 seconds, 16 milliseconds)
[JVM-2] *** 1 TEST FAILED ***
[JVM-1] *** 1 TEST FAILED ***
```

JVM-2 enters the barrier 5s later, barrier timeout is 30s by default so I can only see this failing because of the global test withIn

**Comment by chbatey** [comment]
https://github.com/akka/akka/pull/23882
