### ISSUE TITLE
Docs Http- Server-Sent Events Support

### ISSUE THREAD

**Issue by gastonlucero** [akka/akka#23782]
In [SSE-Support](https://doc.akka.io/docs/akka-http/current/scala/http/sse-support.html ) , scala marshalling and unmarshalling examples are the same, java examples are ok.

**Comment by ktoso** [comment]
Thanks for the ticket; I realise I linked you to here to open the ticket, it should be in http://github.com/akka/akka-http though so I've moved it now. 

Thanks for reporting

**Comment by ktoso** [comment]
Moved to: [Docs Http- Server-Sent Events Support #1454](https://github.com/akka/akka-http/issues/1454)
