### ISSUE TITLE
Observe if server is still bound on ServerBinding

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23798]
Currently it is only possible to stop the a TCP server through `ServerBinding.unbind()`, would be nice with a `ServerBinding.whenUnbound: Future[Done]` (matching `ActorSystem.whenTerminated`)

**Comment by agemooij** [comment]
It would be great if the same method would be added to the akka-http version of `ServerBinding`.

**Comment by johanandren** [comment]
Ah, it's actually the not the same one. Good that you mentioned that. I'll open a ticket over there as well.
