### ISSUE TITLE
Changed osgi.ee requirement in Akka 2.5.6

### ISSUE THREAD

**Issue by oheger** [akka/akka#23795]
When updating to Akka 2.5.6 I noticed that there was a change in the OSGi manifests for the artifacts: The Require-Capability header now has the value:
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8.0_141))"

Note the specific version. Earlier versions just set this value to 1.8. OSGi frameworks may have trouble to process this requirement. Apache Felix (which I am using) fails to resolve the Akka bundles.

Therefore, it would be good to go back to the versioning used by previous versions.

**Comment by johanandren** [comment]
This will involve some investigation, there is no place where we explicitly changed this/where "1.8" AFAIK, so for some reason it was generated to be an exact Java release upon release.

We have no OSGi expertise in the team, so help from the community would be very welcome.

**Comment by collymy** [comment]
I don't have any expertise in the akka build system but I have had a look into OSGi.scala in akka/project which uses sbt-osgi. sbt-osgi has a requireCapability setting which uses the code below to set the default: -

  def requireCapabilityTask(): String = {
    val version = System.getProperty("java.version")
    "osgi.ee;filter:=\"(&(osgi.ee=JavaSE)(version=%s))\"".format(version)
  }

which is where the header Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8.0_141))" is coming from in the akka 2.5.x bundles. I can't see how this changed between the akka 2.4.x releases and the 2.5.x releases. However adding a requireCapability setting in OSGi.scala by extending osgiSettings in object OSGi as below should fix the problem. So the current version: -

  def osgiSettings = defaultOsgiSettings ++ Seq(
    packagedArtifact in (Compile, packageBin) := ((artifact in (Compile, packageBin)).value, OsgiKeys.bundle.value),
    // This will fail the build instead of accidentally removing classes from the resulting artifact.
    // Each package contained in a project MUST be known to be private or exported, if it's undecided we MUST resolve this
    OsgiKeys.failOnUndecidedPackage := true,
    // By default an entry is generated from module group-id, but our modules do not adhere to such package naming
    OsgiKeys.privatePackage := Seq())

becomes: -

  def osgiSettings = defaultOsgiSettings ++ Seq(
    packagedArtifact in (Compile, packageBin) := ((artifact in (Compile, packageBin)).value, OsgiKeys.bundle.value),
    // This will fail the build instead of accidentally removing classes from the resulting artifact.
    // Each package contained in a project MUST be known to be private or exported, if it's undecided we MUST resolve this
    OsgiKeys.failOnUndecidedPackage := true,
    // Specify the version of JavaSE required
    OsgiKeys.requireCapability := "osgi.ee;filter:=\"(&(osgi.ee=JavaSE)(version=1.8))\"",
    // By default an entry is generated from module group-id, but our modules do not adhere to such package naming
    OsgiKeys.privatePackage := Seq())

Given the arrival of JavaSE 9 it might better to specify a more general requirement as below: -
OsgiKeys.requireCapability := "osgi.ee;filter:=\"(&(osgi.ee=JavaSE)(version>=1.8))\""

Note the >=1.8 which makes the requirement JavaSE 1.8 or any later version including JavaSE 1.9.

**Comment by johanandren** [comment]
Thanks for the investigation, ">= 1.8" sounds like the way to go, would you be up to make a PR with that change, and also if possible do a package and use the built artifacts to verify this fixes the problem?

**Comment by collymy** [comment]
Johan,
Hi. I am afraid that I don't know how to do a PR nor how to build Akka.

kind regards
Colly 

    On Saturday, 14 October 2017, 13:23:31 GMT+1, Johan Andrén <notifications@github.com> wrote:  
 
 
Thanks for the investigation, ">= 1.8" sounds like the way to go, would you be up to make a PR with that change, and also if possible do a package and use the built artifacts to verify this fixes the problem?

**Comment by ktoso** [comment]
Fixed, thanks a lot @oheger !

**Comment by oheger** [comment]
Many thanks for fixing this and for this great framework!
