### ISSUE TITLE
Routers with Remote destinations without knowing the remote host address

### ISSUE THREAD

**Issue by Swaypreet** [akka/akka#23799]
Hi,

I am trying to implement router and routes configuration in cluster in such a way that Router will know the host address of the routes at run time.
My scenario is as below:
1. Seed Main Project with below conf file:

remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "127.0.0.1"
      port = 2541
       }
  }

  cluster {
    seed-nodes = [
      "akka.tcp://application@127.0.0.1:2541"]
      }

2.  AccountMain Project - which is connects to the seed main

3. Checkout Main project - which connects to the seed main

Now AccountMain and CheckoutMain may run on different machines. I want to send messages from  accountMain actors to CheckoutMain actor. The AccountMain actor doesn't know the IP addresses of the CheckoutMain actor. How we can achieve that ?

How i am trying to do is as below
AccountMain conf file
remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "127.0.0.1"
      port = 9031
       }
  }

  cluster {
    seed-nodes = [
      "akka.tcp://application@127.0.0.1:2541"]

  }

}

akka.actor.deployment {
  /checkoutDetailRouter = {
    router = consistent-hashing-group
    routees.paths = ["/user/checkoutDetail"]       #this belongs to the 
    cluster {
      enabled = on
      use-role = backend
      allow-local-routees = off
    }
  }
}

In accountMain actor trying to create actor ref for the checkoutMain.
Could you please help here ?

Regards,
Sway

**Comment by patriknw** [comment]
We don’t use the issue tracker for questions, so please ask in akka-user google group, or read the documentation about cluster aware routers.
