### ISSUE TITLE
Merge akka-contrib-extra into akka-contrib ?

### ISSUE THREAD

**Issue by MasseGuillaume** [akka/akka#23793]
I came across https://github.com/typesafehub/akka-contrib-extra#akka-contrib-extra

In the README it says the following:

> The contents of this project are intended as an incubator for Akka related things that Reactive Runtime has discovered useful in the course of its development. The intent is that these things will ultimately become PRs against the actual akka-contrib project.

Is there anything I can do to make this happen? I would be happy to do the PR and write the user guide.

**Comment by raboof** [comment]
In fact we've decided to deprecate akka-contrib itself as well, and instead have separate repo's for smaller satellite projects - so the best way forward would be to move the various logical components of akka-contrib-extra into their own projects.

Is there a specific component you're be interested in?
