### ISSUE TITLE
[typed] Rename applyEvent to eventHandler

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#23807]
In `PersistentActor.immutable` and `PersistentActor.persistentEntity`.

**Comment by ktoso** [comment]
Any rationale to back this?
As you know we think long and hard about names and apply event is pretty
good as that exactly explains what you should do there, rather than a
generic “handle”. One should not side effect from therefor example etc

-- 
Konrad Malawski

**Comment by hseeberger** [comment]
In Event Sourcing terminology this thing is called event handler. Likewise in Patrik‘s blog post (headline). Why invent new terms?

**Comment by patriknw** [comment]
I don't have a very strong opinion about that name but the thinking is that it should not be abused as a general callback emitting side effects and such. It's only purpose is to update the state based on the event (apply the event to the state).

btw, `actions: Actions` will be renamed to `commandHandler: CommandHandler`, and a command handler is much more powerful.

**Comment by hseeberger** [comment]
Heh, I was already thinking about Actions -> CommandHandler, but because of the signals I was not 100% sure. But yes, thumbs up for that change.

With that change I think applyEvent really must be renamed eventHandler, because then the API nicely and consistently resembles its EventSourcing origin. Please notice that neither `apply` nor `handle(r)` nor any other name forces the users to think about the absence of side-effects. This very important detail is left for the comments.

**Comment by patriknw** [comment]
agreed, we are changing this
