### ISSUE TITLE
Matching typed adapter actor name with wildcards inside large-message-destinations

### ISSUE THREAD

**Issue by dbolotin** [akka/akka#23812]
`akka.typed.scaladsl.ActorContext#spawnAdapter` method creates adapter actor with a random prefix, which makes it impossible to match it with wildcards.

We are using Artery for communication between remote systems. One of adapter actors inside our hierarchy receives bulky messages (this is the reason we switched to Artery), so we are using large message channel for it. The problem is that we can't define appropriate selector in `large-message-destinations` that would include exclusively our target adapter without other children of the base actor.

So I have two questions:
1. How does `large-message-destinations` affects performance of networking? After I read [this](https://github.com/akka/akka/issues/22257#issuecomment-279948250), I got a feeling that one should set `large-message-destinations` as narrow as possible, but, on the other hand, as I understand  it, only oversized messages exceeding `maximum-frame-size` are transmitted through the large message channel, right (?), so even if I include all actors into `large-message-destinations` only transmission of oversized messages will be affected?

2. Is it possible to match adapter actors using some other wildcard syntax? I failed to find other syntax descriptions except [this](https://doc.akka.io/docs/akka/2.5/java/general/addressing.html).

Thanks.

**Comment by johanandren** [comment]
Hi @dbolotin 

We try to reserve use of the issue tracker for bugs and tracking features, please use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) or [the user gitter channel](https://gitter.im/akka/akka) for questions such as this, thanks!

(You will figure out the answer by looking at reference.conf in akka-remoting where the setting is defined)
