### ISSUE TITLE
Document that we maintain the Cassandra persistence plugin

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23833]
Cassandra plugin should be mentioned in https://doc.akka.io/docs/akka/current/scala/persistence.html?storage-plugins#storage-plugins as recommended storage engine in prod.

Esp. since we maintain and recommend it anyway

**Comment by chbatey** [comment]
Should this wait till we 1.0 it?

**Comment by ktoso** [comment]
Good point, removing pick next

**Comment by Captain1653** [comment]
The issue is really old. I have found these pages: [Other Akka modules](https://doc.akka.io/docs/akka/current/common/other-modules.html) and [Akka Persistence Cassandra](https://doc.akka.io/docs/akka-persistence-cassandra/current/index.html). Is it still needed?

**Comment by patriknw** [comment]
thanks
