### ISSUE TITLE
Document that "who created materializer shall terminate it, for all ethernity"

### ISSUE THREAD

**Issue by rrodseth** [akka/akka#23837]
I'm not certain about this, but it came up because I learned about shutdown and happened to have an actor with injected materializer of type Materializer rather than ActorMaterializer. Konrad asked me to submit this ticket for the team's consideration. 

https://groups.google.com/forum/#!topic/akka-user/hg14tPcGhws

**Comment by ktoso** [comment]
Thanks for the ticket 👍

**Comment by patriknw** [comment]
I'd say that if you didn't create the materializer you should also not be responsible for shutting it down. When using a shared materializer and anyway have a stream that is bound to an actor's lifecycle it's best to use a KillSwitch from `postStop` to stop the things that the actor itself started.

**Comment by ktoso** [comment]
Yeah good points, I think I should include those hints in the lifecycle section I am working on now: https://github.com/akka/akka/pull/23836

**Comment by ktoso** [comment]
We should add that info to the docs then

**Comment by ennru** [comment]
With the Actor system providing the Materializer in Akka 2.6, this is not important anymore.
Closing.
