### ISSUE TITLE
Make sbt-api-mappings work with jdk9

### ISSUE THREAD

**Issue by raboof** [akka/akka#23843]
Upstream issue: https://github.com/ThoughtWorksInc/sbt-api-mappings/issues/8

**Comment by larsrh** [comment]
I've published a fork: https://github.com/larsrh/sbt-api-mappings. Version 3.0.1 should work correctly, otherwise please let me know.

**Comment by raboof** [comment]
Good to know! Upstream master should now be OK, so once they do a post-2.0.0 [release](https://github.com/ThoughtWorksInc/sbt-api-mappings/releases) we can use them again.

**Comment by 2m** [comment]
Fixed in #24157
