### ISSUE TITLE
FAILED: sbt 1.0.2 javac compile issue

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23859]
This is an issue to track failures like this one: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10520/console

```
[error] Caused by: java.lang.NullPointerException
[error] 	at com.sun.tools.javac.util.DiagnosticSource.findLine(DiagnosticSource.java:163)
[error] 	at com.sun.tools.javac.util.DiagnosticSource.getColumnNumber(DiagnosticSource.java:92)
[error] 	at com.sun.tools.javac.util.JCDiagnostic$SourcePosition.<init>(JCDiagnostic.java:380)
[error] 	at com.sun.tools.javac.util.JCDiagnostic.getLineNumber(JCDiagnostic.java:519)
```

Which seem to be caused by sbt 1.0.2 which we merged today.

The relevant sbt issue is: https://github.com/sbt/sbt/issues/3623

**Comment by johanandren** [comment]
Seeing a bunch of these each night

**Comment by ktoso** [comment]
I wanted to update java on the boxes but did not get to it, no idea if it would help though.
Would it have a chance to help this @dwijnand ?

**Comment by dwijnand** [comment]
I have no idea.

**Comment by ktoso** [comment]
Thanks, we're on the same page then 🤣  We'll try updating java's anyway hm

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10576/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5420/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/952/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/886/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4931/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4935/console

**Comment by 2m** [comment]
It is strange how this does not happen on our local machines, but only on CI. I would still like to see newer version of java8 in our workers.

**Comment by ktoso** [comment]
It did happen on my box I think at least once or twice. `Java(TM) SE Runtime Environment (build 1.8.0_144-b01)`
Sure you're not on JDK10 or something when trying to reproduce @2m?

**Comment by 2m** [comment]
I hope not. :D 

I am on: 
```
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by gosubpl** [comment]
My local setup:
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by johanandren** [comment]
This probably is sbt/sbt#3623

**Comment by ktoso** [comment]
For people observing this ticket, @jrudolph found the root cause and explained in https://github.com/sbt/sbt/issues/3623#issuecomment-344269502

**Comment by 2m** [comment]
Fixed in https://github.com/akka/akka/pull/24181
