### ISSUE TITLE
Missing serializer for `akka.Done`

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#23854]
It's quite common in Lagom to send `akka.Done` over the wire. [There is no serializer](https://github.com/akka/akka/blob/32f0936d1730f09ac3201dec29c357cb0549d9cb/akka-remote/src/main/resources/reference.conf) for that object at the moment.

**Comment by ignasi35** [comment]
Related https://github.com/akka/akka/pull/21912

**Comment by ktoso** [comment]
Someone's already on it btw @ignasi35

**Comment by jroper** [comment]
More context in https://github.com/akka/akka/issues/20507.
