### ISSUE TITLE
Artery does not appear to remove its shutdown hook

### ISSUE THREAD

**Issue by huntc** [akka/akka#23856]
Akka's Artery support does not appear to remove the shutdown hook [that it adds](https://github.com/akka/akka/blob/70ad537af53d739a50bb87c1558639c0144f89d5/akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala#L408). Under OSGi-like environments that rely on dynamic classloading and removal, I imagine that the lack of removal for Artery would lead to a reference within a class loader such that the classloader could never be garbage collected.

Other parts of Akka appear to [remove](https://github.com/akka/akka/blob/da0cfa577b0d135170a6bde48ad89cd9ea08f448/akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala#L481) shutdown hooks that have been [added](https://github.com/akka/akka/blob/da0cfa577b0d135170a6bde48ad89cd9ea08f448/akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala#L476).

**Comment by patriknw** [comment]
Would you be able to create a PR fixing this?

**Comment by huntc** [comment]
Absolutely. Thanks!
