### ISSUE TITLE
Add some mechanism to dynamically mark/unmark nodes in Cluster

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka#23851]
Currently I have scenario, where I dynamically start and stop different types of actors on different nodes of the cluster. I need to know which nodes currently hold which types of actors because I do not know this in advance, so I think the best solution is to mark/unmark the node somehow that it holds one or other kind of actor. It can be particularly useful in combination with distributed pub-sub.

So I suggest to add some mechanism for adding/removing some mark to node, probably ability to mutate `selfRoles`.

**Comment by patriknw** [comment]
I suggest that you implement that in the application with [Distributed Data](https://doc.akka.io/docs/akka/current/scala/cluster-usage.html).

**Comment by manonthegithub** [comment]
@patriknw yeah. I did it, right as you suggest. It just seems to me redundant to implement register/derigister and subscribing for `MemberRemoved` when I need to know about who is where in cluster.

**Comment by manonthegithub** [comment]
I think this would be great to be able to say to the cluster `I'm here` and ask it `Where is/are this actor/actors?` out of the box...

**Comment by johanandren** [comment]
That sounds exactly like `Receptionist` in Akka typed cluster. Perhaps such a receptionist would be useful for untyped as well?

**Comment by ktoso** [comment]
I and Arnout agree with Patrik and Johan :-)
This can indeed be implemented in ddata or better even, by backporting the receptionist from akka typed. You can do that as a library if you want. See the receptionist here: https://github.com/akka/akka/blob/master/akka-typed/src/main/scala/akka/typed/receptionist/Receptionist.scala

**Comment by manonthegithub** [comment]
@ktoso as I see (or probably I misunderstood something), Receptionist is implemented on top of DistributedData itself:).

**Comment by manonthegithub** [comment]
I've already implemented something similar, If you think this will be useful, I can create a PR with it after some polishing, probably in `akka-cluster-tools`
