### ISSUE TITLE
Failed: Not a valid key: clean-files

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23863]
https://jenkins.akka.io:8498/job/akka-nightly/4911/console

Something with the sbt upgrade likely:
```
[error] Not a valid command: clean-files (similar: load-failed)
[error] Not a valid project ID: clean-files
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: clean-files (similar: cleanFiles, cleanKeepFiles, clean)
[error] clean-files
[error]           
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5406/console
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5407/console

**Comment by patriknw** [comment]
why do we use cleanFiles? what is it supposed to do, that `clean` doesn't`?

**Comment by 2m** [comment]
The dash syntax for keys is no more in sbt 1.x. So to reach that task, we would need to use `cleanFiles`. But what is more, is that `cleanFiles` just returns a list of files that would be cleaned when `clean` is run. So I am not sure why we are running this task on Jenkins. We can safely remove it from the Jenkins actions in nightlies and elsewhere.

**Comment by johanandren** [comment]
Thanks @2m, I've gone through all nightlies and removed it where it was used now.
