### ISSUE TITLE
Failed: MultiDcSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23864]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/880/consoleFull

```
[JVM-4] [INFO] [10/30/2017 08:24:56.068] [MultiDcSpec-akka.remote.default-remote-dispatcher-6] [akka.trttl.gremlin.tcp://MultiDcSpec@a5.moxie:44224/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[JVM-1] [ERROR] [10/30/2017 08:24:56.077] [MultiDcSpec-akka.actor.default-dispatcher-18] [akka://MultiDcSpec/user/controller/barriers] unannounced disconnect of RoleName(fourth) (akka.remote.testconductor.BarrierCoordinator$ClientLost: unannounced disconnect of RoleName(fourth))
[JVM-5] - must be able to have data center member changes while there is unreachability in another data center (on node 'fifth', class akka.cluster.MultiDcMultiJvmNode5) *** FAILED *** (428 milliseconds)
```

**Comment by johanandren** [comment]
Same, but with artery (I think):
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/943/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/944/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2365/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2369/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/2370/consoleFull

**Comment by chbatey** [comment]
No new instances added since https://github.com/akka/akka/commit/511180ef39da11e3ddfeca47a8f990cd1a4395d1

Closing for now
