### ISSUE TITLE
Missing letter "a" in stream-flows-and-basics documentation

### ISSUE THREAD

**Issue by RaymondKlass** [akka/akka#23876]
Sentence reads "Means that a certain operation does not hinder the progress of the calling thread, even if it takes long time to finish the requested operation."

and should probably read "Means that a certain operation does not hinder the progress of the calling thread, even if it takes a long time to finish the requested operation."

**Comment by ktoso** [comment]
Thanks for spotting, please submit a PR :)
It's this file: https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/stream/stream-flows-and-basics.md :)

**Comment by ktoso** [comment]
Was done
