### ISSUE TITLE
Failed: MultiDcHeartbeatTakingOverSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23879]
https://jenkins.akka.io:8498/job/akka-multi-node/2366/consoleFull

```
[JVM-1] - must other node must become oldest when current DC-oldest Leaves (on node 'first', class akka.cluster.MultiDcHeartbeatTakingOverSpecMultiJvmNode1) *** FAILED *** (1 second, 980 milliseconds)
[JVM-1]   java.util.concurrent.TimeoutException: Client timed out while waiting for barrier member-shutdown
[JVM-1]   at akka.remote.testconductor.Player$$anonfun$enter$1.apply(Player.scala:111)
[JVM-1]   at akka.remote.testconductor.Player$$anonfun$enter$1.apply(Player.scala:98)
[JVM-1]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[JVM-1]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[JVM-1]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[JVM-1]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[JVM-1]   at akka.remote.testconductor.Player$class.enter(Player.scala:98)
[JVM-1]   at akka.remote.testconductor.TestConductorExt.enter(Extension.scala:52)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.enterBarrier(MultiNodeSpec.scala:382)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMemberRemoved$1.apply$mcV$sp(MultiNodeClusterSpec.scala:323)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMemberRemoved$1.apply(MultiNodeClusterSpec.scala:315)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMemberRemoved$1.apply(MultiNodeClusterSpec.scala:315)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
[JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:882)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:373)
[JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:882)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$class.awaitMemberRemoved(MultiNodeClusterSpec.scala:315)
[JVM-1]   at akka.cluster.MultiDcHeartbeatTakingOverSpec.awaitMemberRemoved(MultiDcHeartbeatTakingOverSpec.scala:67)
[JVM-1]   at akka.cluster.MultiDcHeartbeatTakingOverSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(MultiDcHeartbeatTakingOverSpec.scala:148)
[JVM-1]   at akka.cluster.MultiDcHeartbeatTakingOverSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(MultiDcHeartbeatTakingOverSpec.scala:136)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5412/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5413/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/882/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/947/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/948/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5416/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5415/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5414/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/2377/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/949/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2380/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2381/consoleFull

**Comment by raboof** [comment]
Basically consistently:
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5418/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5419/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5421/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5422/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5423/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5424/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5425/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5426/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5427/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5428/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/951/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/953/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/954/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/955/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/956/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/957/consoleFull
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/958/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/885/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/887/consoleFull

**Comment by raboof** [comment]
The tests appears to work fine as a multi-jvm test, but started to fail consistently when ran as a multi-node-test - it seems since 82ca8a2cc73f26005e161692b70edd33df7577f1, but I don't see how that could be related, so that might just have been timing
