### ISSUE TITLE
Failed: benchmarks does not compile on 2.12

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23880]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/374/console

This, and more:
```
[error] /localhome/jenkinsakka/workspace/akka-nightly-2.12/akka-bench-jmh/src/main/scala/akka/actor/ActorBenchmark.scala:93:28: annotation argument needs to be a constant; found: ActorBenchmark.totalMessages
[error]   @OperationsPerInvocation(totalMessages)
```

**Comment by 2m** [comment]
The error is actually from the `doc` task.

**Comment by 2m** [comment]
It errors out with Scala 2.11.11 as well as with 2.12.4

I think we are stepping on this one: https://github.com/scala/bug/issues/10426

And the error is for the constants which in the definition site use arithmetic.

**Comment by johanandren** [comment]
Still happening
https://jenkins.akka.io:8498/job/akka-nightly-2.12/375/console

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/376/consoleFull

**Comment by raboof** [comment]
Doesn't seem to be fixed?

https://jenkins.akka.io:8498/job/akka-nightly-2.12/377/console
https://jenkins.akka.io:8498/job/akka-nightly-2.12/378/console
https://jenkins.akka.io:8498/job/akka-nightly-2.12/379/console
https://jenkins.akka.io:8498/job/akka-nightly-2.12/380/console

**Comment by 2m** [comment]
This is not even funny anymore...

There is something else going on there when testing this. I just started up this branch and `akka-jmh-bench/doc` completed successfully. But then it failed after `clean`. Investigating.
