### ISSUE TITLE
Allow RestartSource.withBackoff to restart only on failures

### ISSUE THREAD

**Issue by unoexperto** [akka/akka#23881]
Per conversation with @ktoso in gitter who suggested submitting this request.

Could you guys please make option for `RestartSource.withBackoff` to restart only on failures ?

Before `RestartSource.withBackoff` I was solving this problem by having function that returns `Future` of materialized stream which I invoke recursively in case of exception. `RestartSource` made it much easier but I have no way to complete stream when wrapped stream is done.

**Comment by johanandren** [comment]
This was discussed when in the original PR but was scoped out of it. A PR adding this is welcome. :)

**Comment by nachinius** [comment]
Let me know if this is what you were looking for.
