### ISSUE TITLE
Supervision.Decider called twice when mapAsync throws exception in a Future

### ISSUE THREAD

**Issue by adkafka** [akka/akka#23888]
While writing tests around error handling in an Akka Stream, we observed that the `Supervision.Decider` we provide to a materializer can get called multiple times for a single exception in the flow. Specifically, we noticed this occur when an exception is thrown in a Future within a `mapAsync`. We were using the `Supervision.Decider` to manage statistics about how often exceptions are thrown in our flow.

Attached is an example test that demonstrates the behavior. We expect the counter to be incremented exactly once, but it is incremented twice instead.

It would be ideal if either this behavior was documented in an obvious location (I would suggest https://doc.akka.io/docs/akka/2.5/scala/stream/stream-error.html#errors-from-mapasync), or even better, if this issue was fixed, and it was safe to assume that a `Supervision.Decider` is only called once per exception thrown in a flow.

```
import akka.actor.ActorSystem
import akka.stream.scaladsl.{Flow, Sink, Source}
import akka.stream.{ActorMaterializer, ActorMaterializerSettings, Supervision}
import org.scalatest.{AsyncFreeSpec, Matchers}

import scala.concurrent.{ExecutionContext, Future}

class Test extends AsyncFreeSpec with Matchers {
  val decider: Supervision.Decider = {
    case exception: StringIndexOutOfBoundsException =>
      counter += 1
      println(s"Received an out of bounds exception : $exception")
      Supervision.Resume
  }

  implicit val system = ActorSystem("test")
  implicit val ec = ExecutionContext.Implicits.global
  implicit val materializer = ActorMaterializer(
    ActorMaterializerSettings(system).withSupervisionStrategy(decider)
  )

  var counter = 0

  val testFlow = Flow[String].mapAsync(1) { string =>
    Future { string.charAt(10) }
  }

  "should increment counter by only one" in {
    val preTestCounterValue = counter
    preTestCounterValue shouldBe 0

    val flatBuffersFlowTest =
      Source.single("shortStr")
        .via(testFlow)
        .runWith(Sink.seq)

    flatBuffersFlowTest.map { _ =>
      counter shouldBe (preTestCounterValue + 1) //Fails
    }
  }
}
```

Scala version: 2.11.8
Akka version: 2.5.6

**Comment by adkafka** [comment]
We have traced it to the function handleFailureOrPushElem being called twice, for the example provided.
https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala#L1150-L1153

**Comment by johanandren** [comment]
You up for PR:ing a fix @adkafka ?

**Comment by breckcs** [comment]
@johanandren, @adkafka and I will try and contribute a fix for this. We will have to work through the necessary approvals before committing and opening a PR.

**Comment by johanandren** [comment]
Great!

**Comment by johanandren** [comment]
@breckcs Any news about this one?

**Comment by breckcs** [comment]
@johanandren we can try and submit a PR this week or next, but if you want to pick it up you can go for it.
