### ISSUE TITLE
multi-jvm tests fail under jdk9 on jenkins

### ISSUE THREAD

**Issue by raboof** [akka/akka#23898]
https://jenkins.akka.io:8498/job/akka-nightly-jdk9/34/consoleFull
```
[JVM-2] java.lang.ClassCastException: [B cannot be cast to [C
[JVM-2] 	at akka.util.Unsafe.fastHash(Unsafe.java:47)
[JVM-2] 	at akka.remote.serialization.ActorRefResolveCache.hash(ActorRefResolveCache.scala:61)
```

**Comment by ktoso** [comment]
Looks like a bug... we specifically fixed this in our Unsafe didn't we?

**Comment by raboof** [comment]
Yes, looks like it's using `akka-actor/src/main/java/akka/util/Unsafe.java` rather than `akka-actor/src/main/java-jdk9/akka/util/Unsafe.java`.

**Comment by ktoso** [comment]
Hm, since it's not forking... But I thought I reverted the change since we don't to multi release jars yet?

**Comment by ktoso** [comment]
I see, the jdk9 branch perhaps stil has that commit which we decided to revert because mr-jar was not completely working for all cases yet...

**Comment by ktoso** [comment]
See here https://github.com/akka/akka/pull/23746

**Comment by ktoso** [comment]
Weird but that IS that branch... perhaps when you rebased that commit came back?
We currently can't do mr-jars because of that reason (that our own code is not aware about this thing yet when running tests)

**Comment by raboof** [comment]
Right, make sense to revert it here too (and do mr-release jars in a separate PR, perhaps on top of this one or perhaps later)

**Comment by ktoso** [comment]
Yeah. There's edge cases like this sadly... where we need to somehow modify classpath during running tests such that the "override class" however one may want to call it is used instead of the "normal" class. I think this will be possible by ordering classpaths apropriately... we'll see, but for now please revert it on the branch.

**Comment by raboof** [comment]
reverted on that branch, let's bring it back as a separate issue
