### ISSUE TITLE
Provide cause for cancelation in stream

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23908]
Cancellation is often quite hard to track down. We are free to extend reactive streams in a compatible way to provide a cause when a stream is cancelled.

The idea is to provide an extended subscription that has a method `def cancel(cause: Throwable)`. If such a subscription is detected (`isInstanceOf`), the new cancellation method should be used. The cause should be threaded through our implementation layer to ensure that cancellation causes are propagated end-to-end.

**Comment by patriknw** [comment]
First step merged so closing this ticket. #27472 with the next steps
