### ISSUE TITLE
Akka Http: Problem with connecting http server to outgoing tcp server throught nginx

### ISSUE THREAD

**Issue by 4repaXXX** [akka/akka#23906]
Hello!
Condition:
Start http server, which responsibility only to get json request from the client and send message on Tcp server through nginx, take response from it and send response back to the client. So, only like proxy.
Problem:

- Http server try to response before tcp server response. But when I remove nginx proxy between http and tcp servers everything all right. In tcp level http server send RST packet and right after that get RST from nginx.

- And when I try to connect from outside the local network and send big(more 1500 bytes) json I get an error with json parsing, because of only part of json get from request.

Akka version 2.4.17, akka http 10.0.5
The code below

```
val connections: Flow[ByteString, ByteString, Future[Tcp.OutgoingConnection]] =
Tcp().outgoingConnection(new InetSocketAddress(settings.tcpServerHost, settings.tcpServerPort))
def start(): Unit ={
  val requestHandler: HttpRequest => Future[HttpResponse] = {
  case HttpRequest(POST, uri@Uri.Path("/v1/doc"), _, entry, _) =>
  proxyTcp(100, uri, entry)
  case HttpRequest(POST, uri@Uri.Path("/v5/doc"), _, entry, _) =>
  proxyTcp(105, uri, entry)
  case _ => Future(HttpResponse(status = StatusCodes.NotFound))
}

  Http().bind(settings.host, settings.port).runForeach(connection => {
  connection.handleWithAsyncHandler(requestHandler)
}) }
  private def proxyTcp(version: Short, uri: Uri, entry: RequestEntity): Future[HttpResponse] = {
  val transform = Transformations(connections, version)
  entry.withoutSizeLimit().dataBytes
  .via(transform.json2tlv)
  .via(transform.connectionGraph)
  .runWith(Sink.head)
  .map(result => HttpResponse(status = StatusCodes.OK, entity = HttpEntity(ContentTypes.`application/json`, result.get)))
}
```
I'm not sure that this is a bug and not my wrong actions.
Thanks in advance for the answer.

**Comment by johanandren** [comment]
Hi @4repaXXX, Akka HTTP has its own issue tracker over at https://github.com/akka/akka-http/issues , but before you re-post there, try to create a minimal reproducer with as few transformations and moving parts as possible to make sure there isn't something with your logic, skip the TCP server part and serve a static 1500+ bytes stream of data etc.

Closing this issue for now, but feel free to reopen in the Akka HTTP tracker!

**Comment by 4repaXXX** [comment]
@johanandren Thank you, you are right with bytes. I remove outgoing connection to tcp and all is fine now. But with response from tcp still no result. Thanks.
