### ISSUE TITLE
java.lang.UnsupportedOperationException in VarForm.getMemberName

### ISSUE THREAD

**Issue by raboof** [akka/akka#23901]
In `IndexSpec`:
```
[info] - must remove values *** FAILED *** (3 milliseconds)
[info]   java.lang.UnsupportedOperationException:
[info]   at java.base/java.lang.invoke.VarForm.getMemberName(V
arForm.java:92)
[info]   at java.base/java.lang.invoke.VarHandleGuards.guard_L
L_V(VarHandleGuards.java:49)
[info]   at java.base/java.util.concurrent.ConcurrentSkipListS
et.setMap(ConcurrentSkipListSet.java:512)
[info]   at java.base/java.util.concurrent.ConcurrentSkipListS
et.clone(ConcurrentSkipListSet.java:177)
[info]   at akka.util.Index.remove(Index.scala:142)
```

This is an upstream issue: https://bugs.openjdk.java.net/browse/JDK-8185830

It is supposedly resolved and is tagged `9-bp` which presumably means this fix has been or will be backported to jdk9, but it's unclear to me how to find out in which version to expect that.

**Comment by ktoso** [comment]
Ok, so we'll see if it's really fixed in JDK

**Comment by raboof** [comment]
The [change for jdk10](http://hg.openjdk.java.net/jdk10/jdk10/jdk/rev/3792401c9b8a) does not seem to be [in jdk9u](http://hg.openjdk.java.net/jdk-updates/jdk9u/jdk/file/fa3b1c07db05/src/java.base/share/classes/java/util/concurrent/ConcurrentSkipListSet.java) yet (linked to a specific revision, not sure if it is possible to link to that file on a branch)

**Comment by raboof** [comment]
Seems to be in 9.0.6 (unreleased though)

**Comment by johanandren** [comment]
If this is fixed in JDK 10, and JDK 9 is EOL now, how do we deal with this? Close it?

**Comment by ktoso** [comment]
If fixed on 10 we can indeed not care about 9 (due to it's EOLish status nowadays anyway AFAIK)

**Comment by johanandren** [comment]
Verified the test passes in JDK 10 (`Java(TM) SE Runtime Environment 18.3 (build 10+46)`)
