### ISSUE TITLE
NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by raboof** [akka/akka#23903]
In `SerializeSpec.scala:354` we use `javax.xml.bind.DatatypeConverter.parseHexBinary` to parse a hex-encoded binary.

This class has moved to the `java.xml.bind` module which is no longer loaded by default. We could load that module, but it'd probably be better to find another way to parse hex binaries (or even switch to base64).

**Comment by johanandren** [comment]
In other tests we use `import org.apache.commons.codec.binary.Hex.{ encodeHex, decodeHex }` so maybe we could just switch to those here as well?

**Comment by raboof** [comment]
Giving it a try!
