### ISSUE TITLE
Sink.seq can generalize to other collection types

### ISSUE THREAD

**Issue by S11001001** [akka/akka#23917]
```scala
// this signature
def seq[T]: Sink[T, Future[immutable.Seq[T]]]

// generalizes to this one
def gseq[T, That](implicit cbf: CanBuildFrom[Nothing, T, That]): Sink[T, Future[That]]
```

It's a few lines of changes, propagating the CBF to `SeqStage` and using it to instantiate the builder instead of creating a `Vector` builder directly.

The current `seq` signature can be implemented, preserving its type and dynamic behavior for backward compatibility, by calling `gseq[T, Vector[T]]`.

`gseq` isn't a great name, maybe you have a better one.

This gives you "anything CBF-able". I don't fully understand the invariants `SeqStage` must satisfy, but one example might be that only immutable collections ought to be produced; this can be enforced by locking down the implicit:

```scala
import collection.{immutable => im}
CanBuildFrom[Nothing, T, That with Immutable]         // marker trait, not very safe
                         That with im.Traversable[_]] // must be within c.i hierarchy
```

(This has the effect of upper-bounding `That` but is a little/a lot nicer from a higher-order perspective. A `@usecase` might mention an upper bound in lieu of the CBF.)

**Comment by patriknw** [comment]
Sounds like a good addition for the scaladsl. Sink.collection might be a good name. Limiting it to immutable would be good. Will you be able to create a PR, @S11001001 ? Thanks

**Comment by S11001001** [comment]
I can share the branch (indeed, I tried it before making this issue). However, I won't sign the CLA.

Please let me know if you'd still like to see the change.

**Comment by patriknw** [comment]
Ok, then we don't want to see your code (for legal reasons). Thanks for a good suggestion, and this ticket is open for someone else to implement.
