### ISSUE TITLE
Thread.currentThread.interrupt typo?

### ISSUE THREAD

**Issue by Abrasha** [akka/akka#23918]
As always, I was looking through source code and found some strange code.

All we know, that it is recommended to call `Thread.currentThread.interrupt`**ed**`()` if our thread was interrupted and we handled `InterruptedException`. But the following code seems to interrupt self one more time. Isn't it a typo? Shouldn't it be:

    try Thread.sleep(sleepMs) catch {
      case _: InterruptedException ⇒ Thread.currentThread.interrupted()
    }

Code reference: [_akka.actor.LightArrayRevolverScheduler#waitNanos_](https://github.com/akka/akka/blob/f8b4fb55ca3c4d20a503e99ad774f74a3ee36c11/akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala#L86)

<img width="957" alt="screen shot 2017-11-04 at 23 00 37" src="https://user-images.githubusercontent.com/11317222/32409407-0901d3a4-c1b4-11e7-907c-7a8fc960498a.png">

**Comment by patriknw** [comment]
`isInterrupted` or `interrupted` is not used elsewhere in `LightArrayRevolverScheduler` so I think you are right, but I'm not sure about the original intentions there. Please create a pull request.

**Comment by gosubpl** [comment]
https://stackoverflow.com/questions/4906799/why-invoke-thread-currentthread-interrupt-in-a-catch-interruptexception-block/4906814

**Comment by ktoso** [comment]
As @gosubpl explains via the link, the `interrupt` is correct AFAICS making this ticket invalid.

@viktorklang loves the interrupt API so may confirm doubly so I guess ;-)

**Comment by viktorklang** [comment]
Yes, `interrupt()` is the correct behavior.

**Comment by ktoso** [comment]
Thanks for confirming! Ah, the lovely interrupts API... 🙉
