### ISSUE TITLE
Provide access to known shard types

### ISSUE THREAD

**Issue by danischroeter** [akka/akka#23912]
We want to provide a simple stats overview of sharding. The current sharding statistics are fine but there is no way to generically know all shard entity types.
The Sharding Extension internally stores this and could safely be exposed.

**Comment by patriknw** [comment]
Sounds good to add, will you be able to create a PR?

**Comment by danischroeter** [comment]
Thx for considering. I already created a pr: https://github.com/akka/akka/pull/23913
