### ISSUE TITLE
GraphInterpreter chaos mode

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23936]
The execution order of signals in the `GraphInterpreter` is not guaranteed. Every stage should be seen as its own execution island with signals being exchanged asynchronously. In reality, the execution order of signals is often still mostly deterministic, especially in short running test. This means that race conditions between signals can go unnoticed (or implementations even start to rely on orderings).

The idea is to add a new `GraphInterpreter` mode that executes signals not in the (arbitrary) order they are queued but for each step choose a random signal to execute from the queue. (To keep the ring-buffer, you could randomly swap one signal with the one which would otherwise be executed next.)

**Comment by jrudolph** [comment]
It would be even more useful in addition with a `GraphInterpreter` tracer (flight recorder) that would allow to analyze the execution order of signals in cases of test failures.

**Comment by jrudolph** [comment]
Oops, I see that's exactly how the fuzzing mode works.

**Comment by ktoso** [comment]
:-)
