### ISSUE TITLE
Issue while setting mediatype to multipart/form-data for Multipart.FormData.BodyPart.fromPath

### ISSUE THREAD

**Issue by Akhil201** [akka/akka#23935]
Hi Team, 

I am trying to upload a file to external server of media type multipart/form-data. So I configured the request as follows 

def createEntity(file: File): Future[RequestEntity] = {
    
    val foo: Path = Paths.get("""C:\Users\akhilesh\Desktop\test12345720170521-41925-lzxwhi.kml""")
    require(file.exists())
    val formData =
      Multipart.FormData(
        akka.stream.scaladsl.Source(
          List(
            Multipart.FormData.BodyPart.fromPath(
              "file",MediaTypes.`multipart/form-data`,foo),
            Multipart.FormData.BodyPart("name", "akhil"))))
    Marshal(formData).to[RequestEntity]
  }

Here I set media type to ( MediaTypes.`multipart/form-data`) so here I am facing the error as type mismatch; found : akka.http.scaladsl.model.MediaType.Multipart required: akka.http.scaladsl.model.ContentType

Please help me out how to configure my multipart request with mediatype as 'multipart/form-data' in akka.

**Comment by ktoso** [comment]
Please open issues about Akka HTTP in its repository -- https://github.com/akka/akka-http/

I moved this ticket, let's discuss over there https://github.com/akka/akka-http/issues/1519
