### ISSUE TITLE
ClusterSharding: lack of ability to automatically choose start or startProxy by a node role

### ISSUE THREAD

**Issue by sergiy0** [akka/akka#23934]
`start` method of `ClusterSharding` throws an `IllegalArgumentException` in case there is no match between cluster node roles and the role specified in the `ClusterShardingSettings` passed to this method.
But it may be handy to have a method which will start a `ShardRegion` in proxy mode on nodes without this role (rather then just throwing an exception). Also this may allow to change `role` in `ClusterShardingSettings` without changing the application code.

This issue probably depends on #23472

**Comment by ktoso** [comment]
I think what you describe is already implemented in akka-typed's sharding; See here https://github.com/akka/akka/blob/master/akka-typed/src/main/scala/akka/typed/cluster/sharding/ClusterSharding.scala#L287

So we agree it's a good idea and perhaps would be able to back-port it to classic sharding

**Comment by patriknw** [comment]
to-be-backported? we will not backport this to 2.4. I guess you mean "from Akka Typed", but I find that a bit confusing usage of that tag

**Comment by patriknw** [comment]
So the suggestion is to change the behavior of `start` to be like startRegionOrStartProxy, depending on the role. I think such change could be acceptable. Would be strange if someone relied on the exception being thrown.

**Comment by sergiy0** [comment]
I may PR that.

**Comment by ktoso** [comment]
> I guess you mean "from Akka Typed", but I find that a bit confusing usage of that tag

Yeha I meant that, perhaps too overloaded use of the tag indeed :)

**Comment by ktoso** [comment]
Excellent, thanks

**Comment by patriknw** [comment]
Seems we found an issue with how this was solved and reverted, but I can't remember what it was. Would be good to have a note here. Do you remember @ktoso ?

**Comment by ktoso** [comment]
Looking at the actual state of code and what the revert commit is it seems git just did an a bit over zealous commit message as it was actually only reverting the https://github.com/akka/akka/commit/5a59a7b362b362fbae4a8cc22786ba6374572942 failing test that we had merged to have it reproduce a failure for a while.

**Comment by ktoso** [comment]
In other words, this issue is resolved in 2.5.12
