### ISSUE TITLE
Add Automatic-Module-Name to manifest

### ISSUE THREAD

**Issue by raboof** [akka/akka#23931]
we should reserve a jdk9 module name, so users can use our not-yet-modular-jars as-if-modular. This is pretty simple, we just need to add metadata to the manifest:

```
Automatic-Module-Name: akka.actor
```

The module name should be reverse domain (like package names), so `io.akka.`/`akka.` and then followed by akka sub-project name I guess, the names can't have `-` AFAIR, so I guess we should explicitly make up the names or just automatically derive them from subproject name by removing `-`?

See also:

> The naming issues are well-explained on Stephen Colebourne's blog:
> - http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html
> - http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html <- the explanation of module hell problem

Esp. read the module hell one ☝️ 

via https://github.com/mockito/mockito/issues/1189

**Comment by ktoso** [comment]
Yup, I'll give it a shot tomorrow once I get the stops working then :)

**Comment by ktoso** [comment]
I'll try this before tomorrow's standup so we can discuss if there's anything to talk about there

**Comment by ktoso** [comment]
Mark's guide on the topic http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-February/000582.html
