### ISSUE TITLE
[test-kit] Add `expectFailureMessage`

### ISSUE THREAD

**Issue by mentegy** [akka/akka#23949]
when actor replies with a failure, e.g.
```scala
sender() ! akka.actor.Status.Failure(new RuntimeException("w/e"))
```
test kit does not allow easy way to test it, user should do something like:
```scala
val e = expectMsgType[Status.Failure].cause
e.isInstanceOf[RuntimeException] shouldBe true
e.getMessage shouldBe "w/e"
```
However it would be great to have `expectFailureMessage` method which will work like scalatest's `intercept`:

```scala
 expectFailureMessage[RuntimeException].getMessage shouldBe "w/e"
```

**Comment by ktoso** [comment]
I don't think this is a good idea, special casing a special type of message into the testing utilities will encourage this pattern, which by itself is not a good one I think.

-1 from me

**Comment by mentegy** [comment]
@ktoso Thanks for reply, I've prepare PR for this in #23950. We already have this feature as internal utility, hence I decided to share this with community.
I'm not trying to convince you, however `Status.Failure` is not a special type but exceptional, since it's the only the way to achieve failed `Future` of `ask` pattern. Since latest is very common we have many test cases with `expectFailureMessage` usage.
Hence taking into account the `ask` pattern, your quote "special casing a special type of message" doesn't play well here.

**Comment by ktoso** [comment]
Which leads people to build request/response ask based actors which are not that nice, is what I meant about not making it even more helpful in doing this.

If rest of the team agrees with this addition I'm ok with it, but not a fan of it on my own

**Comment by ktoso** [comment]
cc @patriknw @johanandren maybe?

**Comment by johanandren** [comment]
I'd also say -1, we don't want to encourage design your actor protocols using generic types like this.

**Comment by mentegy** [comment]
@ktoso @johanandren I'm sorry but I still cannot get your point. You're providing `ask pattern` feature but not an easy way to test it by saying that this test util will encourage people use the `ask pattern`, which is bad. 

On the other hand, docs says that "actors are fully encapsulated and internal state cannot be accessed/modified" however there's test utility `TestActorRef` which completely breaks that statement.

**Comment by ktoso** [comment]
`TestActorRef ` - Yet another one of those tools which we'd like to remove, yes.

**Comment by johanandren** [comment]
In a test you don't need to use ask, because expectNnn has a timeout.

**Comment by mentegy** [comment]
@johanandren Exactly! But there's no easy way to test failure of ask using existing `expect*` helpers.

**Comment by mentegy** [comment]
@ktoso @johanandren anyways, feel free to close it if that test helper doesn't play well with your design goals :confused:

**Comment by johanandren** [comment]
Thanks for taking the time to discuss it with us!

**Comment by patriknw** [comment]
If the purpose is to test ask req-rsp, you can easily do that from a test with Await.result. Await is highly discouraged but from a test it can be valid.
