### ISSUE TITLE
Follow up work for AsyncCallback.invokeWithFeedback

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23953]
Follow up to https://github.com/akka/akka/pull/23185. 

Too late PR review: https://github.com/akka/akka/pull/23185#pullrequestreview-75442824

Some things that might need addressing (sorry for spotting them too late before merging):

 * [x] add tests for `invokeWithFeedback`
 * [x] add tests that verify that all stages that now use `invokeWithFeedback` have fixed behavior
 * [x] Verify whether never completing promise is correct behavior (i.e. whether it is ok that `onFailure` will be invoked for every single callback run through `invokeWithFeedback` eventually).
 * [ ] Smaller issues around matching state

/cc @agolubev

**Comment by johanandren** [comment]
I just ran into problems with number three, trying to fix the merge hub cancellation ticket (#23205), I think that it must be very clearly documented that the future is always failed at some future point.

**Comment by jrudolph** [comment]
I think it's a bug. How would you distinguish if a callback was processed or not if it is always failed in the end?

**Comment by johanandren** [comment]
Yes, you are right, they must be completed successfully when the invoke did succeed.

**Comment by johanandren** [comment]
I'm sneaking a bit of this into that bchub PR.

**Comment by patriknw** [comment]
@johanandren I merged your PR https://github.com/akka/akka/pull/23970, but I guess this ticket is more than that. Please tick the boxes above.
