### ISSUE TITLE
[typed] Some suggestions for Effect method names. 

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#23964]
These are some suggestions for the `Effect` factory methods. I can send a PR for that if you guys agree.

# persist and persistAll
As of today, there is two persist methods `Effect.persist` and `Effect.persistAll`. 

https://github.com/akka/akka/blob/c8748e8cf0c69efe059bde39df05a396a88c96d3/akka-typed/src/main/scala/akka/typed/persistence/scaladsl/PersistentActor.scala#L43-L48

I think it would be better to have the following instead:

```scala
   def persist[Event, State](event: Event, events: Event*): Effect[Event, State] =
      new PersistAll[Event, State](im.Seq(event) ++ events)

   def persist[Event, State](eventOpt: Option[Event]): Effect[Event, State] =
      new PersistAll[Event, State](eventOpt.toIndexedSeq)

    def persist[Event, State](events: im.Seq[Event]): Effect[Event, State] =
      new PersistAll[Event, State](events)
```

This would allow more convenient and homogenous syntax:

```scala
// exactly one event
persist(ItemAdded(id = 1))

// one or more events using varargs
persist(ItemAdded(id = 1), ItemAdded(id = 2))

// Option variation
persist(state.items.find(_ == itemId).map(RemoveItem)) 

// Seq variation
persist(generateSeqOfEvents())

```
# unhandled
There is also an `unhandled` method.
https://github.com/akka/akka/blob/c8748e8cf0c69efe059bde39df05a396a88c96d3/akka-typed/src/main/scala/akka/typed/persistence/scaladsl/PersistentActor.scala#L58-L61

`Unhandled` sounds more like something that is not being supported or an error. What about calling it `ignore`? I think it expresses better the fact that we are consciously not handling it.

# done
I may not have understood the motivation of `done`, but it reads weird to have `Effect.done`. 

If the goal is to express that we are not producing any effect, isn't it better to have `Effect.nothing` or `Effect.none`?

**Comment by patriknw** [comment]
The background for persist and persistAll comes from untyped PersistentActor wher you can emit several events using several calls to these methods, with the semantical difference that persistAll is atomic. For Akka Typed I agree that we can simplify it as you suggest. Always atomic if more than one event.

Unhandled concept already exists in ordinary typed actors so we should keep the same here. Intentionally not supported message (in current state). Effect.done can be used for the silent ignore case.

I agree that Effect.none is better than done.

Please PR

**Comment by ktoso** [comment]
Good ideas!

+1 on the `persist` change
+1 on the `Effect.none`, was also reading weird to me to say done there.
The unhandled should remain as it's the same as in Actors I think, has specific semantics.

**Comment by renatocaval** [comment]
Actually, credits to @ignasi35 that point me out the possibility to have overloaded `persist` methods. 

I'm working on the PR
