### ISSUE TITLE
Compile errors in Getting Started guide (Java)

### ISSUE THREAD

**Issue by moogpwns** [akka/akka#23966]
Nice tutorial, but in Part 4, under **Adding registration support to device group actors**, the first 2 code snippets for the `DeviceGroup` class include the `onDeviceList` and `onTerminated` message handlers, and the corresponding matchers in the `receiveBuilder`.

These shouldn't be introduced until the third snippet for the `DeviceGroup` class (when the message definitions for `RequestDeviceList` and `ReplyDeviceList` are added, the `actorToDeviceId` map is added and `getContext.watch(deviceActor)` is called.

The same two snippets are also missing the `groupId` field, the constructor and the `LoggingAdapter` declaration.

**Comment by ktoso** [comment]
Thanks for reporting, would you be able to help out fixing this by submitting a PR?
https://github.com/akka/akka/tree/master/akka-docs/src/main/paradox/guide

**Comment by moogpwns** [comment]
Sure, submitted https://github.com/akka/akka/pull/23978

**Comment by ktoso** [comment]
Awesome, thanks :)
