### ISSUE TITLE
[typed] Actor.immutable docs are not correct wrt. mutable state

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#23977]
The docs: "This constructor is called immutable because the behavior instance doesn't have or close over any mutable state."

But of course it's possible to close over a var like this:

``` scala
def behavior(): Behavior[Any] = {
  var n = 0
  Actor.immutable {
    case (_, _) =>
      n += 1
      println(n)
      Actor.same
  }
}
```

So I guess the docs should be changed. Or even the name (but I like it)?

I suggest to change the docs along these lines: "This constructor is called immutable because the behavior instance typically doesn't need to use mutable variables, but instead returns a potentially different behavior encapsulating any state changes".

**Comment by patriknw** [comment]
I'd say it's a bad smell to write a behavior like that. You should be able to use a `val` and spawn it several times:
```
val behavior: Behavior[Any] = {
  var n = 0
  Actor.immutable {
    case (_, _) =>
      n += 1
      println(n)
      Actor.same
  }
}

ctx.spawnAnonymous(behavior)
ctx.spawnAnonymous(behavior)
```
which is obviously wrong. Then you should use `deferred` instead.

That said, the documentation clarification sounds good. Please PR.

**Comment by hseeberger** [comment]
It's a terrible smell, of course. But you know that all possible things will happen eventually, smelling or not ...

PR will be filed soon.
