### ISSUE TITLE
Bad link in IoT tutorial

### ISSUE THREAD

**Issue by citizen12** [akka/akka#23996]
https://doc.akka.io/docs/akka/2.5/java/guide/tutorial_2.html

"The source code for this page can be found here" points to http://github.com/akka/akka/tree/master/akka-docs/src/main/paradox/java/guide/tutorial_2.md which is a bad link.

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by ktoso** [comment]
(I know we don't use bug for marking those usually, but marking so we don't lose track of it and do it soon)

**Comment by johanandren** [comment]
Something about the docs being folded into one and there isn't a java subdirectory of paradox in the sources anymore. Could it be that we changed that after 2.5.6 was released and it will just work when we release 2.5.7?

**Comment by raboof** [comment]
As yes that's exactly it... this is essentially due to documentation being generated from a tag, but linking to master. I think it generally makes sense to link to master though...

**Comment by johanandren** [comment]
I'll close this as it will fix itself with the release coming up.
