### ISSUE TITLE
whitesource does not report violations on master

### ISSUE THREAD

**Issue by raboof** [akka/akka#24005]
when running `whitesourceCheckPolicies` on master, no errors are reported. However, when running `whitesourceCheckPolicies` on the same commit but switched to a different branch, it correctly reports failures (that should be suppressed, but that is another issue, #24004 ).

We should figure out why it doesn't appear to check the policies when on master. Perhaps this has to do with the value for `whitesourceAggregateProjectName` being set to `akka-adhoc` for a branch, and `akka-master` for master?

**Comment by raboof** [comment]
Turns out by default `whitesourceCheckPolicies` only reports *new* violations compared to the report published to whitesource.

We want to enable `whitesourceForceCheckAllDependencies` to make sure each dependency is checked each time.

**Comment by johanandren** [comment]
This got fixed by that PR, right?

**Comment by raboof** [comment]
Jup!
