### ISSUE TITLE
Make it possible to find out when `Source` returned by `BroadcastHub` subscription is completed.

### ISSUE THREAD

**Issue by cleverdeveloper** [akka/akka#24017]
One very common use case for `BroadcastHub` is to attach `Sink.ignore` as one of the subscribers to ensure it does not backpressure if there are no subscribers.

The use case is even described in the official Akka documentation:
https://doc.akka.io/docs/akka/2.5/scala/stream/stream-dynamic.html#combining-dynamic-stages-to-build-a-simple-publish-subscribe-service

The problem of this approach, though, is that it is very hard to test such a graph properly.

Imagine the following code:

    val sink = BroadcastHub.sink(...) mapMaterializedValue { source =>
       source.runWith(Sink.ignore)
    }
    val source = Source.queue(...)
    val (queue, subsriptions) = source.toMat(sink)(Keep.both).run()
    val result = subscriptions.runWith(Sink.seq)
    queue.offer(TestElement)
    // ISSUE: Mail fail here as subscription may happen later than "offer"
    result must be (Seq(TestElement))
  
Some possible solutions for that could be:
- Make sure that the `BroadcastHub.sink` returns `Sink[Source[T, Future[Done]]]` instead of `Sink[Source[T, NotUsed]]` and the future is only completed when subscription have happened.
- Return `Sink[Future[Source[T, NotUsed]]]` when subscription have happened (might be awkward).
- Keep signature, but make sure that subscription is guaranteed if materialization have already happened.
- Leave everything as it is, and try to work around it without touching `BroadcastHub`.

If I do one of the things above with `BroadcastHub`, would such contribution be considered?

**Comment by johanandren** [comment]
If you instead use the streams testkit, with the `Test{Publisher,Subscriber}` you can wait for subscription on the sink side before sending any element through.

**Comment by cleverdeveloper** [comment]
Well, if I modify the code to use `TestProbe` I still get the same issue with a subscriber, which is slow enough and uses `flatMapConcat`.

Could it be, if I ensure that there are no `flatMapConcat` inside of a graph I am testing, then calling `probe.ensureSubscription()` will be enough?

    val sink = BroadcastHub.sink(...) mapMaterializedValue { source =>
       source.runWith(Sink.ignore)
    }
    val source = Source.queue(...)
    val (queue, subsriptions) = source.toMat(sink)(Keep.both).run()
    val slowSubscriptions = Source.single(NotUsed) flatMapConcat { _ =>
       Thread.sleep(1000)
       source
    }
    val result = slowSubscriptions.runWith(TestSink.probe(system))
    result.ensureSubscription()
    queue.offer(TestElement)
    // ISSUE: May fail here as subscription may happen later than "offer"
    result.expectNext()

**Comment by johanandren** [comment]
If you use a stage that does some form of detached-lazy-subscription like that, you will need to wait for that inner source to be subscribed rather than the outer one. The outer one will subscribe right away. This seems like a weird test case however. If you want to delay subscription in a test you can just sleep in the test thread and then subscribe?

**Comment by cleverdeveloper** [comment]
I did not want to delay subscription just for sake of it. I just wanted to simulate the typical integration test we have.

I.e. we have the large graph with a lot of stages in it, and there are integration tests on the whole graph. In some rare cases (when CI server slows down?), the `offer` seem to happen faster than the subscriptions inside the graph. I.e. slow down of the server works like that `Thread.sleep(1000)` of mine.

But your answer did help me to understand how to deal with it. I have the following plan:
1. Get rid of `flatMapConcat` in that large graph.
2. Use `ensureSubscription` to make sure the subscription happens, really.

By the way, while I think we can get rid of `flatMapConcat`, I imagine there could be a way to pass subscription up to the chain (with some custom graph stage?).

**Comment by johanandren** [comment]
In the case of an integration test like you describe, if you have a `BroadcastHub.sink` that always has a downstream `Sink.ignore` you are just observing exactly the indeterminism in what you have built, if a new subscriber comes in at some point you cannot be certain that an event that comes in at roughly the same point in time is seen by the subscriber. You cannot expect to make a test that sees a different behaviour than how the thing you built actually works. ;)

One way we usually deal with this in the Akka test suites are by using [`awaitAssert`](https://doc.akka.io/docs/akka/current/scala/testing.html#built-in-assertions) from the Akka testkit which will allow you to retry a block of code until it fails or if it does not succeed within a timeout fails the test.

**Comment by cleverdeveloper** [comment]
I am happy at this stage of affairs, so I am closing the issue.
