### ISSUE TITLE
[Akka-Streams] a case where mapAsync prevents backpressure

### ISSUE THREAD

**Issue by fbessadok** [akka/akka#24011]
Hi,

I have a problem with backpressure when I use mapAsync, it forces me to use throttle instead to make it work (without mapAsync) but in my use case I think it's an unclean way to solve my problem. Here is what I need to do:

I have a file with thousands of urls, I need to stream that file (I used alpakka fs connector), make a HEAD request and save the status code for each url. Some urls answer faster than others, and some can stay many minutes before answering, I've put a timeout on akka http client in the configuration to prevent this.

Here are my dependencies' versions:

```
  "com.typesafe.akka" %% "akka-actor" % "2.5.6",
  "com.typesafe.akka" %% "akka-stream" % "2.5.6",
  "com.typesafe.akka" %% "akka-http" % "10.0.10",
  "com.lightbend.akka" %% "akka-stream-alpakka-file" % "0.14",
```

Here is my not-working code:

```
object Main {
  implicit val system: ActorSystem = ActorSystem()
  implicit val materializer: ActorMaterializer = ActorMaterializer()

  def main(args: Array[String]): Unit = {

    val lines: Source[String, NotUsed] = akka.stream.alpakka.file.scaladsl.FileTailSource.lines(
      path = FileSystems.getDefault.getPath("urls.txt"),
      maxLineSize = 8192,
      pollingInterval = 250.millis
    )

    val flow = Flow[String].mapAsync(5)(url => {
      Http()
        .singleRequest(HttpRequest(uri = url, method = HttpMethods.HEAD))
        .map(response => (url, response.status.intValue()))
    })

    lines via flow runWith Sink.foreach[Future[(String, Int)]](_.onComplete {
      case Success(r) => println(r)
      case Failure(ex) => println(ex)
    })
  }
}
```

This streams the urls at a very fast pace and causes the http client to crash for most of urls due to saturated http client pool. Instead, if I understand well, it should tell the source to slow down while the pool is full.

What did I do wrong ? Is this a problem with akka streams, akka http, the connection between them, or is it a problem in my code ? And If so what should I change to make it work ?

Thank you

**Comment by ktoso** [comment]
Please note that when opening the issue you've seen this request: `For general questions and discussion please use https://groups.google.com/group/akka-user/ or https://gitter.im/akka/akka instead.` Please use the mailing list for design and general questions such as this.

---

You're not using the right API for the use case.
The right one is the Flow based variant which does only pull once the pull is ready -- the singleRequest submissions are not backpressured by the pool - it's plain method calls after all.

Please read the docs: https://doc.akka.io/docs/akka-http/10.0.10/scala/http/client-side/host-level.html#using-a-host-connection-pool
