### ISSUE TITLE
Website documentation links appear to be broken

### ISSUE THREAD

**Issue by enzeart** [akka/akka#24026]
When I click on the "API" links at [https://akka.io/docs/](https://akka.io/docs/), the scala links return a "NOT FOUND" response and the java ones bring me to the scala documentation.

**Comment by raboof** [comment]
Oops! I fixed it manually, will dive into what went wrong here while releasing 2.5.7 next. Thanks for the heads-up!

**Comment by ktoso** [comment]
Thanks, merged the fix. It's not in 2.5.7 though, what do we do about that?
