### ISSUE TITLE
Flow.scanAsync does not complete after the initial value has been pulled.

### ISSUE THREAD

**Issue by skorikov** [akka/akka#24036]
# The Problem
The `Flow.scanAsync` stage does not propagate completion to downstream stages after the initial value (zero) has been pulled.

# Test
```scala
implicit val system: ActorSystem =
  ActorSystem()

implicit val mat: Materializer =
  ActorMaterializer()

val flow: Flow[Int, Int, NotUsed] =
 Flow[Int].scanAsync(0)((acc, in) => Future.successful(acc + in))

val (pub, sub) = TestSource
 .probe[Int]
 .via(flow)
 .toMat(TestSink.probe)(Keep.both)
 .run()

sub.request(10) // signal demand
sub.expectNext(0) // expect initial value
pub.sendComplete() // signal completion
sub.expectComplete() // fails due to time out!
```
This test fails with:
`java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for OnComplete`

# Possible cause
The class `akka.stream.impl.fusing.ScanAsync` overrides the default implementation of the `onUpstreamFinish` method with an [empty implementation](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala#L510).

**Comment by johanandren** [comment]
Thanks for the reproducer and detailed report. Would you be willing to take a stab a PR fixing it as well?
