### ISSUE TITLE
andThen callbacks must be defensive

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#24034]
In Akka Typed Persistence, we can use the `andThen` callbacks to register side-effects to be executed after the command is handled. 

The current implementation will stop callbacks processing in the occurrence of failures. 
For example:

```scala
Effect
  .persist(SomeEvent(...))
  .andThen { 
    methodCallThatThrowsException()
  }
  .andThen { 
    someOtherCall()
  }
```

If `methodCallThatThrowsException` throws an exeception, `someOtherCall` will never be called. 

I believe that `andThen` callbacks should not affect each other and we must keep going even in the occurrence of failures. We probably must log the failure otherwise it will be totally lost. 

If the user wants to make sure that callbacks impact each other, then they must be added together on the same `andThen`. 
For example: 

```scala
Effect
  .persist(SomeEvent(...))
  .andThen { 
    methodCallThatThrowsException()
    someOtherCall()
  }
```

**Comment by johanandren** [comment]
I think we must discuss failures in `andThen` some more, shouldn't they be seen as failures for the actor (and if so, how could we possible execute another one)?

**Comment by renatocaval** [comment]
The problem that I see with `andThen` callbacks is that, in the context of persistence, that's pretty much a best-effort thing. 
When it fails, the events are already persisted and there is no reliable way to recover or revert it. 

That's all very tricky because it is not always obvious to the users that an `andThen` call may fail and that this happens after state transition (persisted events + apply).

We constantly see users in the Lagom community struggling with it and making the wrong assumptions about the callbacks. 

What would be the goal of considering it an actor failure?

Assuming that I'm using an `ask`. If I send a command and the events get persisted, but one of the side-effects are not run, should I get a failure? 
If so, what can we do next? Re-send the command and re-trigger the side-effects? 

This gets even more tricky because events are already persisted and the state transitioned. It's possible that the command is not valid anymore or isn't idem-potent or some of the side-effects should not be retried. 

@johanandren, do you have any use case in mind where a failure of callback should be considered a genuine actor failure?

**Comment by johanandren** [comment]
My reasoning is that it is logic that is run in the context of the actor and that the usual supervision should be used for failures in logic run in the context of the actor.

**Comment by patriknw** [comment]
Perhaps it would be confusing to have different semantics for exceptions thrown by andThen callbacks compared to exceptions thrown elsewhere in the actor, e.g. when receiving a command.

As a convenience for try-catch-log-ignore we could have `.andThenTry` ?

**Comment by raboof** [comment]
I like the idea of failing the actor when a callback fails. As @renatocaval correctly identifies you can never really guarantee that the callbacks run after persisting, making them a best-effort thing, and if you really cared about the side effect long-term you should take care of it during recovery - this is basically an at-least-once vs at-most-once choice. Being 'defensive' against failures in callbacks seems to obscure that fact.

This is also basically consistent with how it works in 'classical' akka-persistence, right?

**Comment by raboof** [comment]
Oops sorry to 'pile on', didn't see the other 2 replies before mine yet 😄

**Comment by renatocaval** [comment]
Ok, let's not add it. 

About the `andThenTry`, maybe we just can let it to the user. 

```
Effect
  .persist(SomeEvent(...))
  .andThen { 
    Try(methodCallThatThrowsException())
  }
```

I'm closing it for now. Feel free to reopen if we should pursue the `andThenTry` path.

**Comment by patriknw** [comment]
ok, I don't mind adding the convenience, but might be good to wait until someone more asks for it
