### ISSUE TITLE
Streams GraphDSL create with Seq[Graph[A,B]]

### ISSUE THREAD

**Issue by tg44** [akka/akka#24067]
The GraphDsl now give enought flexibility for things like this: https://gist.github.com/tg44/cd8eacb5b522e51674fc10e44d78504f

The problem with this approach is that I cant give back materialized value from the components created inside the graph. We have another "create" API so I can "inject" precreated components inside the graph and then the graph can materialize these precreated components mat value (by a combinator func.). But the linked example can't use that api because it has no info about how many element will be in the map.

So my suggestion is that we can create an another "create" function which can "inject" a sequence of precreated component.

I tried to implement it myself but I had problems...

    "be possible to use with generated components" in {
      implicit val ex = materializer.system.dispatcher

      val sinks = (0 to 10).map(_ ⇒ Sink.seq[Int])

      val matList: Seq[Future[immutable.Seq[Int]]] = RunnableGraph.fromGraph(GraphDSL.create(sinks) { implicit b ⇒ sinkList ⇒
        val broadcast = b.add(Broadcast[Int](sinkList.size))

        Source(List(1, 2, 3)) ~> broadcast
        sinkList.foreach(sink ⇒ broadcast ~> sink)

        ClosedShape
      }).run()

      val result: Seq[immutable.Seq[Int]] = Await.result(Future.sequence(matList), 3.seconds)

      result.size shouldBe 10
      result.foreach(_ shouldBe List(1, 2, 3))
    }

This is the test I want to be green.

    def create[S <: Shape, IS <: Shape, Mat](graphs: Seq[Graph[IS, Mat]])(buildBlock: GraphDSL.Builder[Seq[Mat]] ⇒ Seq[IS] ⇒ S): Graph[S, Seq[Mat]] = {
      val builder = new GraphDSL.Builder
      val sList = graphs.map(g => builder.add(g, Keep.right))
      val s = buildBlock(builder)(sList)

      createGraph(s, builder)
    }
And this is the patch I wrote to the [GraphApply.scala.template](https://github.com/akka/akka/blob/master/akka-stream/src/main/boilerplate/akka/stream/scaladsl/GraphApply.scala.template). The test's run() function give back a huge error :( My other problems are; can't patch the java generator file (I can of course but it's not compile :( ), it's broke binary compatible...

**Comment by johanandren** [comment]
Sounds like it could make sense to add if it is possible.

**Comment by tg44** [comment]
I try to do it myself but I have not enought experience with the codebase yet. If sb can point possible problems to my linked snippets that would be helpful.

Can the binary compatible breaking skipped in this type of mods?

**Comment by johanandren** [comment]
Make a PR and we'll see if the bincomp failures are safe to ignore or not.

**Comment by Sebruck** [comment]
Shouldn't this be labeled as "in progress"?
