### ISSUE TITLE
Actor.immutable et al confusing, why not Behavior.immutable?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24071]
We already discussed this once, because it confused me when learning Akka Typed: Why are the "easy to use" behavior factories in the `Actor` object? 

Recently I gave a talk to some 30 attendees of the Scala User Group Munich. Some of them spoke up and told me that they find it utterly confusing that `Actor.immutable` does not create an actor, but "just" a behavior.

I would like to suggest once more to move this DSL which is for creating behaviors into `akka.typed.scala/javadsl.Behavior` (doesn't yet exist).

**Comment by ktoso** [comment]
I made the topic of the ticket describe what it's about.

**Comment by patriknw** [comment]
I think it would be strange have a toolkit for the Actor Model without having the word "actor" in these classes. The word "behavior" doesn't tell anything about what it is about. Many things can have a behavior and that is not in anyway unique for actors or Akka Typed. Someone new reading a source file defining such a behavior wouldn't immediately see that it is an actor.

(ActorRef is not visible in the definition of a behavior.)

I think a correct name would be `ActorBehavior`, in both places. That is somewhat long though.

Perhaps renaming `Behavior` to `Actor` would clear up things, even though I'm sure some would argue against that also.

**Comment by hseeberger** [comment]
@patriknw, I disagree: behavior is a well known term in the actor domain. And the docs should mention it early anyway.

But regardless such thoughts, just look at this signature:

``` scala
Actor.same[T]: Behavior[T]
```

So you are calling `same` on "an actor" and get back a behavior. Even if you were only interested in actors and ignored behaviors so far, now it's the time you have to get your head around the behavior.

So in the end the current state not only confuses some people, but also mixed the terms.

**Comment by gosubpl** [comment]
IMHO there has been a change when transitioning from Untyped to Typed Actors. Typed is for me more like FSM, so the Actor is just the "machinery" to run Behaviours. And the class (type, object) `Actor` is now no longer the "Actor", but rather a `BehaviorFactory`. So in my head the code sample above in @hseeberger post reads:
```
BehaviorFactory.same[T]: Behavior[T]
```
The same for `immutable`, `deferred`, etc.

In the `gracefulStop` story ( https://github.com/akka/akka/issues/22776 ) even those exact words are used "the factory for this behavior" when describing what `Actor.gracefulStop[T] : Behavior[T]` is supposed to be doing.

**Comment by hseeberger** [comment]
@gosubpl I doubt that anyone else is able to use your head when reading Akka Typed code ... 😂

**Comment by gosubpl** [comment]
What I was trying to say is that I completely agree with you Heiko, and would suggest moving Behaviour factories away from the `Actor` type.

**Comment by gosubpl** [comment]
Also, for me the "deferredness" is not a part of Behaviour but rather how the Behaviour is run. So this would be on the `Actor` part -> like `Actor.immediate` or `Actor.deferred` constructors taking relevant Behaviour. But maybe I am missing something.

**Comment by notxcain** [comment]
Agreed, even implementation-wise untyped Akka became a runtime for pure typed behaviors.

**Comment by manuelbernhardt** [comment]
Having finally had the time to play with Akka Typed as opposed to simply skimming through the doc, I must say that I also find the naming a bit confusing. Especially `Actor.deferred` and `Actor.immediate` look quite odd at first sight, because it absolutely isn't the actor that is deferred or immediate, but the execution of its behaviour, and reading `Actor.deferred` looked at first as though this was a mechanism for scheduling things.

I think it is entirely possible to get used to it, but I can already see myself having to do an extra bit of explanation when teaching this API in a few months / years.

I would therefore also lean towards moving these methods into `Behavior`.

**Comment by patriknw** [comment]
Regarding `deferred`, it's not only about runtime creation time. It's also the way to have access to ActorContext when the Behavior is started, e.g. for spawning children or watching other actors.

**Comment by patriknw** [comment]
I gave this a try. There is actually a technical reason for not naming it Behavior. It would be duplicate import conflicts of   `akka.actor.typed.Behavior` and `akka.actor.typed.scaladsl.Behavior`

For example this would not work:
```scala
import akka.actor.typed.ActorRef
import akka.actor.typed.Behavior
import akka.actor.typed.scaladsl.Behavior

object ChatRoom {

  val behavior: Behavior[Command] =
    chatRoom(List.empty)

  private def chatRoom(sessions: List[ActorRef[SessionEvent]]): Behavior[Command] =
    Behavior.immutable[Command] { (ctx, msg) ⇒
```

I have renamed it to `ActorBehavior` in https://github.com/akka/akka/pull/24331

**Comment by hseeberger** [comment]
You could also add 
type Behavior = akka.typed.actor.Behavior
In the scaladsl Package object to avoid the conflict.

**Comment by patriknw** [comment]
Will not work for `javadsl`.

**Comment by hseeberger** [comment]
Damn Java 😉

**Comment by hseeberger** [comment]
Sorry, but `ActorBehavior` is even worse than `Actor`, because it indicates a special kind of behavior just for actors. Like `Set` and `SortedSet` or `List` and `ArrayList`.

What about `Behaviors`? This naming pattern is also used in Akka HTTP, e.g. `StatusCodes`.

**Comment by patriknw** [comment]
What do you mean with "just for actors"? Where would you use it elsewhere? It's already tied to actors via `ActorContext` and `ActorRef`.

**Comment by hseeberger** [comment]
`ActorContext` and `ActorRef` are different. A context and a ref(erence) are general purpose concepts which don't occur by themselves in Akka. They need the actor prefix to give them a clear meaning, e.g. "this is the ref for an actor".

`Behavior` on the other hand is a special construct / a well defined term in the actor domain. There is no need to use the actor prefix. And like in my examples (`List`/`ArrayList`) adding the `Actor` prefix is confusing, because it indicates that `Behavior` is somehow specialized/refined for the given prefix, i.e. for actors. Which is nonsense and not the case.

So what about `Behaviors`?

**Comment by patriknw** [comment]
I find the analogy with `ArrayList` somewhat weak, but `Behaviours` should work so I'll give that a try instead.

**Comment by patriknw** [comment]
`Behaviors` it is!
