### ISSUE TITLE
Should CompositeEffect have single or many side-effects?

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#24072]
On a previous PR I have added a [comment](https://github.com/akka/akka/pull/23973#discussion_r150809288) about a `persist` method variant that receives a `Seq[Event]` and a `Seq[ChainableEffect]`.

https://github.com/akka/akka/blob/84e68380a526eca82fcf66c1e4710a85dc99aefe/akka-typed/src/main/scala/akka/typed/persistence/scaladsl/PersistentActor.scala#L60-L61

This is the only method that creates a `CompositeEffect` using a `Seq[CompositeEffect]`. In all other places, the chain is built much like a linked list. Each `CompositeEffect` references another `CompositeEffect` and so one. 
We can chain them by using the `andThen` method, but at the end, we a have chained structure with each node holding a `Seq` with only one element. 

Moreover, the method mentioned above is only used on a test. 

https://github.com/renatocaval/akka/blob/b89b021e5b67e5bca29a7582b12cd53660b88fd1/akka-typed-tests/src/test/scala/akka/typed/persistence/scaladsl/PersistentActorCompileOnlyTest.scala#L380-L384

The main goal seems to be able to define some common side-effects that must always be prepended or appended to the final `Effect`. This is a valid case, but my first impression is that we are offering two kinds of APIs to deal with `Effect`.

The fragment below comes from the test I just mentioned:

```scala
def changeMoodIfNeeded(currentState: Mood, newMood: Mood): Effect[Event, Mood] =
      if (currentState == newMood) Effect.none
      else Effect.persist(MoodChanged(newMood))

...

case Remember(memory) ⇒
  // A more elaborate example to show we still have full control over the effects
  // if needed (e.g. when some logic is factored out but you want to add more effects)
  val commonEffects = changeMoodIfNeeded(state, Happy)
  Effect.persist(commonEffects.events :+ Remembered(memory), commonEffects.sideEffects)
```

It seems that what we want here is to define a command `Effect` (changeMoodIfNeeded) and augment it with one more events and optionally some more side-effects. 

So instead, I would like to suggest the following variant:

```scala
  val commonEffects = changeMoodIfNeeded(state, Happy)
   commandEffects.append(Remembered(memory))
```

And if extra side-effects are required, one could write:

```scala
  val commonEffects = changeMoodIfNeeded(state, Happy)
  
   commandEffects
      .append(Remembered(memory))
      .andThen(...)
```

This would offer an API that is always discoverable because of it's fluent style and we would be able to remove the `Seq[CompositeEffect]` that seems to exist only to support this use case.

**Comment by raboof** [comment]
AFAICS this would mean we would allow something like:

    Effect.persist(evt1)
      .andThen(someSideEffect())
      .append(evt2)

If we allow this, the user would reasonably expect that `evt2` would only be persisted after the side effect was successfully performed. Our current implementation doesn't: it first persists both `evt1` and `evt2`, and only then performs the side effects.

I'm not sure we should allow that form of chaining, it opens up the question of what to do when you want `someSideEffect()` to be asynchronous, and what to do with messages that come in while working through a chain like this. If we decide to support such chains I think it makes a lot of sense to allow this API style - but if we choose not to then I'm afraid it will confuse users.

**Comment by renatocaval** [comment]
That's true. So, let's abandon this idea. I'm closing this one.
