### ISSUE TITLE
Source/Flow is missing a filterF method

### ISSUE THREAD

**Issue by asarkar** [akka/akka#24085]
It appears that `Source`/`Flow` doesn't have any method that allows to filter on `Future`. This forces premature resolution of the `Future`. A `filterF(p: Out ⇒Future[Boolean])` would be very useful.

**Comment by patriknw** [comment]
Isn’t mapAsync followed by filter enough?

**Comment by ktoso** [comment]
Have you seen the above suggestion @asarkar ?
Closing for now -- we try to keep the number of operators low
