### ISSUE TITLE
Failed: HubSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24104]
This has failed before but it was some time ago so raising a new issue:

https://github.com/akka/akka/issues/21391

```
[info] - must properly signal error to consumers *** FAILED *** (2 seconds, 20 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(1), found OnNext(3)
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:402)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:378)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:378)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:882)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.$anonfun$expectNextN$1(StreamTestKit.scala:387)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$Lambda$823/1297969700.apply(Unknown Source)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:929)
```

**Comment by ktoso** [comment]
I'll give this one a look I guess then

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10897/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5539/testReport/junit/akka.stream.scaladsl/HubSpec/PartitionHub_must_properly_signal_error_to_consumers/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5045/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/421/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5549/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5105/testReport/junit/akka.stream.scaladsl/HubSpec/PartitionHub_must_properly_signal_error_to_consumers/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11189/testReport/junit/akka.stream.scaladsl/HubSpec/BroadcastHub_must_properly_signal_error_to_consumers/
