### ISSUE TITLE
Failed: UnfoldResourceAsyncSourceSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24119]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10946/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

```
java.util.concurrent.TimeoutException: Timeout of 3 seconds with time factor of 1.0
	at akka.testkit.TestLatch.ready(TestLatch.scala:41)
	at akka.testkit.TestLatch.ready(TestLatch.scala:26)
	at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
	at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.ready(package.scala:169)
	at akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(UnfoldResourceAsyncSourceSpec.scala:281)
	at akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(UnfoldResourceAsyncSourceSpec.scala:263)
```

**Comment by johanandren** [comment]
Took a look at this and it does some stuff that is incorrect. In `onStop`, calls `setKeepGoing(true)` and thinks that will cancel the stop of the stage and then schedules an async callback on the stopping stage.

**Comment by jrudolph** [comment]
Maybe we can just call `if (close) f()` in `postStop`?

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5040/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11048/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/936/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5072/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5074/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5075/testReport/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5571/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5082/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by jrudolph** [comment]
AkkaHttpEngineNoNetwork

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5080/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5095/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

**Comment by ktoso** [comment]
Again here https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11216/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/
