### ISSUE TITLE
Add max number of retries to restartWithBackoff

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24129]
Any objections?

**Comment by patriknw** [comment]
Sounds good if it is max restarts within a duration.

**Comment by hseeberger** [comment]
Hm ... why duration? We have an increasing delay between retries anyway because of backoff.

**Comment by patriknw** [comment]
Why would it suddely stop when one failure occurs after a year in production? (One failure per month, max retries = 12)

**Comment by hseeberger** [comment]
I was thinking it should reset the new counter – just like the ﻿existing exponential back-off counter – if the actor is not terminated within the minBackoff duration. That would avoid the scenario you described. And it would fit into the existing logic more naturally than adding some other duration.

**Comment by patriknw** [comment]
Ok, my only point is that there must be a reset of the counter (after some time)

**Comment by Sebruck** [comment]
Currently having a look into it. Maybe it will be my first contribution :-)

**Comment by hseeberger** [comment]
@Sebruck cool! Let me know if you need help.
