### ISSUE TITLE
onPersistRejected default implementation swallows exception

### ISSUE THREAD

**Issue by asarkar** [akka/akka#24133]
The default implementation of `onPersistRejected` is as follows:
```
protected def onPersistRejected(cause: Throwable, event: Any, seqNr: Long): Unit = {
  log.warning(
    "Rejected to persist event type [{}] with sequence number [{}] for persistenceId [{}] due to [{}].",
    event.getClass.getName, seqNr, persistenceId, cause.getMessage)
}
```
It ignores to log the `cause`, thus making it very difficult to troubleshoot what actually caused the failure. Please add the cause to the warning log such that the stacktrace is printed.

**Comment by johanandren** [comment]
Sounds reasonable, we'd have to make it an `error` though, because there is no warning signature that takes an exception parameter.

**Comment by greenhat** [comment]
Here is #24263 my take on it. It's still a `warning` with added stacktrace to the message.

**Comment by ktoso** [comment]
@raboof please make sure to assign milestones when closing/merging -- 2.5.10 here
