### ISSUE TITLE
Provide a higher level API to do TLS over TCP

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24153]
Currently there is a relatively tricky dance of combining BidiFlows with the TCP connection (while diminished in comparison to the SSLConfig setup needed I think that we cannot do much about). We could provide a `Tcp.outgoingTlsConnection(host, port, sslConfig, firstSession): Flow[ByteString, ByteString]`.

Potentially we could also do this for the server side, but that I haven't looked into yet.

WDYT @ktoso, @jrudolph, did I miss something that is really hard to abstract here?

**Comment by patriknw** [comment]
I agree that it would be great to have convenience for tcp+tls.
