### ISSUE TITLE
TestKit improvement "stop and make sure Actor is stopped"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24165]
As we know, the "stop child and know it REALLY is stopped" only works when the parent stops the child. It would be nice to introduce some utility in testkit that would be able to enforce this. It could do nasty things to enforce this, but it's tricky to tell people to make the "stopping dance" manually.

**Comment by ktoso** [comment]
Do you thing the expectStopped you implemented in typed could also do this?

@johanandren

**Comment by johanandren** [comment]
I'm not sure I understand what it means, could you explain it again but like you were talking to a five year old?

**Comment by ktoso** [comment]
Sure,

- You know when we had a goldfish called "bob"? 
- Then bob died, so we bought you a new "bob" goldfish! 
- Yet then it turned out that bob-1 was not REALLY dead, he was just sleeping 
  - *still in the process of shutting down, because it was a child actor, of some other actor, and there we do not have a guarantee about that we can start the actor right away again with the same name; only when the its parent does stop + start a new one we can be sure that the new one will indeed be safely started after the first one is really stopped*
- so you got an actor name not unique exception when we have you the new fish! 
- Wouldn't it be nice if we could make sure the "bob" really was dead before we bought a new one? (*regardless if the stop or poison pill is called from its parent, or from the outside*)

**Comment by johanandren** [comment]
So you're saying that I may get an actor name not unique error if I trigger a new child with the same name when I get the `Terminated(child) message`? (this was a surprise for me)

**Comment by ktoso** [comment]
Yeah AFAIR; It is only safe if the Terminated is received by the Parent of that actor. If someone else gets it it's not yet safe
