### ISSUE TITLE
Akka typed document structure

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24166]
We discussed this but not sure we had a conclusion what was best.

One proposal was to have a separate tree that mirrors `Actors` that we slowly build up as we implement each feature for akka typed with links added from each of the untyped sections to say go here to do this typed.

The downside being it would be a lot of work to restructure any docs sections while we have both of these trees as well as clustering is in a separate location.

Another proposal is to have a typed section in each part of the docs where it is relevant and maybe have one TypedActors under Actors. I think this one will be the smallest change for now.

We can use this as a placeholder  for other doc related things:
* [x] Review docs now that typed actor system has gone. Make sure all still accurate
* [x] Document typed modules
* [ ] Put a note in the akka typed blogs saying that the API / packaging has changed, perhaps update the typed blog code but not the blogs

List of things still to be documented:
* [ ] Supervision strategy

**Comment by chbatey** [comment]
Summarizing a discussion on this:
* Mixing the documentation isn't useful for classic users or typed users as the pages will be huge and how to do things will be very different
* We want to be able to build a structure for the docs that is similar but with improvements so if we do a new tree it doesn't need to match the old one
* End goal is for the typed tree to become the main docs (in a galaxy far far away)

Outcomes
* [ ] Create a separate tree and put all typed things under it
* [ ] Link back to large sections that aren't different for akka typed  
* [ ] Move all relevant content from blogs

**Comment by patriknw** [comment]
thanks for writing it down
