### ISSUE TITLE
Difficult to find maven artifacts / latest versions in the new docs

### ISSUE THREAD

**Issue by rcoh** [akka/akka#24177]
I was starting a new akka project and wanted to add the latest versions of akka and akka-streams as dependencies. But In the new docs (2.5.8), it's very difficult to find the library dependencies to add to SBT. It's not in the [Getting Started Guide](https://doc.akka.io/docs/akka/2.5.4/scala/guide/index.html) or [How to get started](https://doc.akka.io/docs/akka/2.5.4/scala/guide/introduction.html#how-to-get-started) or even in the [quickstart guide](https://developer.lightbend.com/guides/akka-quickstart-scala/). I apologize if this was located somewhere, but my difficulty in finding them would seem to indicate that it's not as obvious as it could be.

I finally found it here:
https://developer.lightbend.com/guides/akka-quickstart-scala/running-the-application.html

Later on, I finally stumbled upon https://akka.io/docs/ which was what I was looking for. For whatever, it's not easy to google.

**Comment by ktoso** [comment]
All latest dependencies are listed here https://akka.io/docs/

How could we help you discover that page even more?
Do you think linking back to it from all pages as "get akka" or something or what would you suggest?

**Comment by rcoh** [comment]
Yeah I just stumbled upon that page. I would include links to it from all of the introduction documents under something like `Installation` or `Get the latest Akka Dependencies`

**Comment by ktoso** [comment]
Hmm, it's not really installation, we're "just a library" ™ but I understand the frustration for newstarters trying to find the way to the deps from docs they googled. I like your wording proposal on "get latest akka dependencies", maybe that would help indeed.

Thanks for opening the ticket

**Comment by johanandren** [comment]
There is actually a link in https://doc.akka.io/docs/akka/2.5.4/scala/guide/tutorial.html (the 5 subsection of the getting started guide before the "Part 1: ...") saying "You should have already followed the instructions in the Akka Quickstart with Scala guide to download and run the Hello World example. " with a link to the complete downloadable example project.

**Comment by ktoso** [comment]
I guess this could be done as top level topic "Dependencies" which would just redirect to the docs page with all the things. As I understand it, the problem was that he started reading from some random docs page, so could not find the dependencies or any link to them from there

**Comment by patriknw** [comment]
Even though we have that overview page with dependencies it would be good if each "main" page for a feature showed what dependency is needed. E.g. what is needed for Cluster Singleton? We have that in several places but not in a consistent location and style.

**Comment by rcoh** [comment]
@johanandren yes but "the complete downloadable project" doesn't directly contain the library dependencies. I don't want to download the whole project, just add it to my build.

**Comment by chbatey** [comment]
+1 to a dependencies section at the top of each main page, otherwise you have to go searching each time

**Comment by richardimaoka** [comment]
Working on this

**Comment by ktoso** [comment]
Awesome, I think we want it in all pages even... Including the guide as well.

Duplicate ticket: https://github.com/akka/akka/issues/24939 I'll close that one

**Comment by satansk** [comment]
I think putting all dependencies in one page and other pages have links to it would be nice.
