### ISSUE TITLE
CoordinatedShutdown settings improvements

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#24183]
`CoordinatedShutdown` allows [configuring](https://github.com/akka/akka/blob/master/akka-actor/src/main/resources/reference.conf#L1046-L1053) whether the actor system should be terminated or the JVM shut down.

There are scenarios where these settings, or even a single configuration, could not be enough. For instance, a clustered application should be able to override the `exitStatus` if `exit-jvm = on` so that the scheduler (ConductR, k8s) knowns the difference and restarts the process.

Since [`Reason` was added](https://github.com/akka/akka/issues/24048) it is possible to distinguish what caused the termination. It could be useful to extend the settings so that defaults can be overridden depending on the `Reason`. For example:

```
  coordinated-shutdown {
    default-phase-timeout = 5 s
    terminate-actor-system = on
    exit-jvm = off
    # exit-code defaults to '0' (only used when 'exit-jvm = on')
    exit-code = 0

    overrides {
       cluster-downing {
          terminate-actor-system = on
          exit-jvm = on
          exit-code = -1
       } 
    }
  }
```

**Comment by patriknw** [comment]
That is a good idea. To make it completely configurable we would have to use class names:
something like:

```
exit-code = 0

reason-overrides {
  "akka.actor.CoordinatedShutdown$ClusterDowningReason" {
    exit-code = -1
  }
}
```

**Comment by ktoso** [comment]
Sidenote, please don't use acronyms like CS in ticket titles, that's a bit cryptic ;)

**Comment by ignasi35** [comment]
I'm about to start this task. I'll follow @patriknw's suggestion and build:

```
exit-code = 0

reason-overrides {
  "akka.actor.CoordinatedShutdown$ClusterDowningReason" {
    exit-code = -1
  }
}
```

The original motivation was to make the exit code configurable per `Reason` which requires adding `exit-code` on the settings. I think `terminate-actor-system` and `exit-jvm`, out of the existing settings, could be overridable too.
