### ISSUE TITLE
sun.net.inetaddr.* dns ttl properties are not respected

### ISSUE THREAD

**Issue by lorenzhawkes** [akka/akka#24188]
The legacy system properties, sun.net.inetaddr.ttl and sun.net.inetaddr.negative.ttl, are looked up incorrectly using Security.getProperty instead of with System.getProperty as it is done with sun.net.InetAddressCachePolicy.

Adding and changing a line in /etc/hosts for 'test-host' and running the following code highlights the issue that the a lookup with InetAddress.getByName returns different results than the response from IO(Dns)

```scala
import java.net.InetAddress

import akka.actor.ActorSystem
import akka.io.{ Dns, IO }
import akka.pattern.ask
import akka.util.Timeout

import scala.concurrent.ExecutionContext
import scala.concurrent.duration._
import scala.util.{ Failure, Success, Try }

object Temp {

  def main(args: Array[String]): Unit = {
    System.setProperty("sun.net.inetaddr.ttl", "0")
    implicit val actorSystem: ActorSystem = ActorSystem()
    implicit val ec: ExecutionContext = actorSystem.dispatcher
    implicit val timeout: Timeout = Timeout(3.seconds)
    val name = "test-host"
    (0 until 1000).foreach { _ =>
      (IO(Dns) ? Dns.Resolve(name)).onComplete {
        case Success(Dns.Resolved(_, ipv4, _)) => println(s"Akka resolved $name -> ${ipv4.mkString(",")}")
        case Success(r) => println(s"Akka failed to resolve, with unknown response $r")
        case Failure(e) => println(s"Akka failed to resolve, with exception ${e.getMessage}")
      }

      Try(InetAddress.getByName(name)) match {
        case Success(address) => println(s"Java resolved $name -> $address")
        case Failure(e) => println(s"Java failed to resolve, with exception ${e.getMessage}")
      }

      Thread.sleep(1000.toLong)
    }
  }

}
```

**Comment by johanandren** [comment]
Good catch, `networkaddress.cache.ttl` and `networkaddress.cache.negative.ttl` are read with `Security.getProperty` while `sun.net.inetaddr.negative.ttl` and `sun.net.inetaddr.ttl` are read using `System.getProperty` (through `sun.security.action.GetIntegerAction` see: http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/net/InetAddressCachePolicy.java )
