### ISSUE TITLE
Some documentation links result in redirect loop

### ISSUE THREAD

**Issue by agam** [akka/akka#24185]
Steps to reproduce:

1. Go to the [top-level page](https://doc.akka.io/docs/akka/2.5.8/)

2. Click on the _Introduction to Akka_ [link](https://doc.akka.io/docs/akka/2.5.8/guide/introduction.html) -- this works.

3. Go back, click on the _Actor Systems_ [link](https://doc.akka.io/docs/akka/2.5.8/general/actor-systems.html?language=scala) -- this results in a "too many redirects" error.

(Curiously, I tried several links on the page and everything under `guide/` seemed to work, while everything under `general/` resulted in the redirect-loop !)

**Comment by raboof** [comment]
Thanks for the heads-up! We've restructured the documentation a bit recently and added redirects to make sure links keep working, but evidently missed this. Should be fixed now - please let us know if you run into any further issues!

**Comment by agam** [comment]
Yep, works now!
