### ISSUE TITLE
Re-write FlatSpec tests using WordSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24186]
We use 99% WordSpec but there are a few lingering WordSpecs. Inconsistency :-1:

**Comment by ktoso** [comment]
I don't mind too much, but could be a contrib for someone to get started indeed.

// please mark as triaged

**Comment by ktoso** [comment]
Thanks Łukasz :) Give it a shot then! ask us here in case you have any questions

**Comment by ldrygala** [comment]
Is there anything i can help you with ?

**Comment by johanandren** [comment]
I think we just forgot to close it, thanks for pinging!
