### ISSUE TITLE
Sharded message left buffered until next retry

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#24191]
I can see often the situation in sharding mechanism that the message which came in the middle of hand off process (caused by rebalance) is stuck in the `shardBuffers` until next `Retry extends ShardRegionCommand` which is by default set to `akka.cluster.sharding.retry-interval = 2 s`. 

We have workaround this issue by lowering the `retry-interval`.

But would be nice to have it properly fixed by delivering buffered message upon hand off completed

Akka 2.5.6

**Comment by t3hnar** [comment]
@patriknw I can confirm that issue is fixed by your changes

**Comment by ktoso** [comment]
Was resolved in https://github.com/akka/akka/pull/24209
To be released today in 2.5.9
