### ISSUE TITLE
implicit Scheduler in typed ask

### ISSUE THREAD

**Issue by talpr** [akka/akka#24219]
The typed version of `AskPattern` requires an implicit `Scheduler` to work. The equivalent untyped method doesn't require this, but instead obtains the `Scheduler` from the `ActorSystem`.

@patriknw suggested the typed version should do the same as the untyped version, and @rkuhn mentioned that would mean that creating typed `ActorRef`s would now require an actor system.

If the API isn't changed, the documentation should be fixed to show the Scheduler import.

Original discussion:
https://groups.google.com/forum/#!topic/akka-user/DNCxBuFb9pE

**Comment by ktoso** [comment]
Sounds like docs should be fixed for now, as we do want to have refs without an actor system

**Comment by patriknw** [comment]
I’ll have to look at this in the context of the new testkits.

**Comment by jrudolph** [comment]
Isn't that a hack in the untyped implementation as well? The implementation runs it on the scheduler of the system of the target actor ref provider.

> we do want to have refs without an actor system

What would that mean? Isn't an actor ref always an instance of an actual actor that has been created in some ActorSystem? What else than an ActorSystem would create a ref?

**Comment by rkuhn** [comment]
One example are tests or the main app thread: no ActorSystem required for an Inbox. It is also quite unclean to expose the not yet constructed ActorSystem to the guardians—untyped is a complete mess in this regard. I’d qualify magically using the target ActorRef’s system’s scheduler as unprincipled (and hence inappropriate) convenience. An alternative would be to decouple the timeout from the ask pattern, offering a generic timeout for Future.

**Comment by rkuhn** [comment]
And yes, this is a confession for my own sins from the past :-)

**Comment by jrudolph** [comment]
Yep, I agree that it could make sense for top-level asks from (though, not sure how to actually use an explicitly given scheduler in the current adapter implementation of typed). 

For the asks insides of actors it seems natural to use the originating scheduler.

**Comment by rkuhn** [comment]
Exactly, the scheduler of the actor doing the asking, not the one who is being asked. Hence picking it up from the lexical scope via an implicit. Implicit functions would be soooo nice 😀

**Comment by patriknw** [comment]
Just one clarification.

> system of the target actor ref

If the ask is from inside an actor that target system is the local system, because then the ref is a RemoteActorRef. Otherwise, you would have passed actor refs around between systems in the same jvm in an invalid way.

**Comment by bilal-fazlani** [comment]
This is a question out of curiosity and I my apologies if this not the right place to ask this question. 

![image](https://user-images.githubusercontent.com/3396271/81579028-3f6c6780-93c9-11ea-8ff4-1c34f31538c6.png)

How will having a scheduler help when you finally move to native typed runtime? The scheduler provides apis such as `scheduleAtFixedRate` , `scheduleWithFixedDelay`, etc. Will the `ask` implementation be based on polling where it will continuously poll of a reply ?

Or is it already poll based and I am not aware of it..? 🤔

**Comment by bilal-fazlani** [comment]
Ahh I see. Thanks for the helpful clarification!
