### ISSUE TITLE
Any ways to set priority for distributed subscribers?

### ISSUE THREAD

**Issue by yangguang760** [akka/akka#24225]
Hi,
Are there any ways to set priority for distributed subscribers?
Thx

**Comment by ktoso** [comment]
What would that mean?
Do you mean in pub sub?

**Comment by johanandren** [comment]
Hi @yangguang760, we try to use the issue tracker only for bugs and feature tracking, please use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) or the [user gitter channel](https://gitter.im/akka/akka) for questions like this, thanks!
