### ISSUE TITLE
Add method ActorSystem.terminatIn()？

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24234]
With 
```
  def terminateIn(duration:FiniteDuration):Future[Terminated]
```

we could write 
```
    system.terminate()
    Await.ready(system.whenTerminated, 15.seconds)
```

to 

```
system.terminateIn(15.seconds)
```

**Comment by ktoso** [comment]
What's the rationale for this?
You can schedule the same with just a scheduler or futures.
It's also inherently racy with whatever you're doing until those 15 seconds pass... so why such method?

**Comment by hepin1989** [comment]
I think the pattern is just everywhere:)

**Comment by ktoso** [comment]
where exactly?

**Comment by johanandren** [comment]
`terminate()` already returns the same `Future[Done]` as `whenTerminated`, so you can simply do `Await.result(system.terminate(), 15.seconds)`.

I don't think it would simplify things to have that blocking hidden in a method.

**Comment by hepin1989** [comment]
@ktoso in the test, using find usages :)

@johanandren Yes, that's a hiding

**Comment by ktoso** [comment]
What do you mean, specifically please ;-)
In tests we shut down using TestKit.shutdown, and if we don't, we should

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/34524110-405f17d0-f0d5-11e7-93b7-5dbdeb2697ba.png)

**Comment by johanandren** [comment]
If it is in code pulled into the docs like that we can't use Testkit because it is meant to show how to do it in an actual application. In the tests that are not docs we should use Testkit.shutdown though.

**Comment by patriknw** [comment]
I agree with the questions here. I don’t see the point of adding this.

**Comment by hepin1989** [comment]
Okay:) So I opened the issue first:)

**Comment by hepin1989** [comment]
feel free to close:)
