### ISSUE TITLE
FunctionRefs must work over remoting (for Typed and StreamRefs)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24231]
Currently FunctionRefs seem not to work over remoting, at least my trying it shows that.
We need them to work just as any ActorRef since Adapters in Akka Typed are those and may be freely sent around anywhere, and it would simplify implementing StreamRefs as well.

FYI in case you remember things about FunctionRefs vs. remoting @rkuhn :)

**Comment by rkuhn** [comment]
Yes, I do remember: they need the same treatment as AskActorRef regarding registration with the ActorSystem upon serialization.

**Comment by ktoso** [comment]
Thanks for the hint, I'll investigate that :-)

**Comment by ktoso** [comment]
Hmmm, I seem to be blind. Dur around the children container and noticed the similar one for function refs but did not find any special treatment of the PromiseActorRef or AskableActorRef hm. Maybe more luck tomorrow after some sleep.

**Comment by ktoso** [comment]
It seems they just work, perhaps they did not in the native system?
(As witnessed by the stream refs implementation)
