### ISSUE TITLE
akka.actor.ActorSelectionTest#testResolveOneCS will fail when CPU is busy

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24235]
When my CPU is busy, sometimes it fails.
```
    FiniteDuration timeout = new FiniteDuration(10, TimeUnit.MILLISECONDS);
    CompletionStage<ActorRef> cs = selection.resolveOneCS(timeout);
```

**Comment by johanandren** [comment]
Likely because it takes more than 10 milliseconds, which is the timeout you gave it, this is mentioned in the scaladoc of `resolveOneCS`

**Comment by hepin1989** [comment]
@johanandren Yes, I am compiling when I was running the tests, so would we increase it a little?

**Comment by johanandren** [comment]
Yes, definitely. 10 ms sounds very tight, you could easily have GC pauses longer than that.

I'll close this issue now since it was more of a question, please use the akka user mailing list or the gitter channel for questions like this in the future!
