### ISSUE TITLE
Add askFor[T] as an alias of ask(...).mapTo[T] to ask pattern?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24259]
with it 

```java 
ask(老板Ref, new 命令.煎饼果子来一个(), 最多等你两分钟)
                .toCompletableFuture()
                .thenApply(煎饼果子.class::cast)
```

could be

```java
askFor(老板Ref, new 命令.煎饼果子来一个(), 最多等你两分钟,煎饼果子.class)
                .toCompletableFuture()
```

and  for Scala ```ask(...).mapTo[T]``` could be ```askFor[T](...)```

When without it :(

![image](https://user-images.githubusercontent.com/501740/34628524-95647a1a-f29f-11e7-9fca-af6d09742e71.png)

![image](https://user-images.githubusercontent.com/501740/34628545-acce34de-f29f-11e7-83f9-7a5c3b6d27fa.png)

![image](https://user-images.githubusercontent.com/501740/34628590-d7191c04-f29f-11e7-84bc-47977be08c0c.png)

**Comment by neomaclin** [comment]
I am not sure the Chinese characters used here actually makes the problem easier for the team to understand, or harder...

**Comment by youngce** [comment]
His meaning like this in English


-----------
with it
```java
ask(bossRef new Command.GiveMeAHamburger(), WaitForYouMost2Min)
                .toCompletableFuture()
                .thenApply(Hamburger.class::cast)

```
could be
```java
askFor(bossRef, new Command.GiveMeAHamburger(), WaitForYouMost2Min,Hamburger.class)
                .toCompletableFuture()
```
-------------

**Comment by johanandren** [comment]
The proposed solution is pretty much just as verbose as the existing explicit cast. I don't think it is worth it.

**Comment by patriknw** [comment]
I agree. It's not worth adding more API for that small benefit. Message types will be better in general in Akka Typed.
