### ISSUE TITLE
Akka Streams: add collectType operator for easier casting in streams

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24254]
with cast we could write :

```
cast(食材.class)
```

instead of 

```
map(食材.class::cast)
```

**Comment by ktoso** [comment]
Please please please be more specific in your issues @hepin1989 😉 
I'm guessing you mean such operator for Akka Streams? I've thought of it a few times... 
Worth considering 👍 

Would you PR it?

**Comment by johanandren** [comment]
When is it that you need to cast? 

Shouldn't it rather be a filter+map based on type then, like a Java-version of what you can do in Scala with `.collect { case t: Type => t }`?

**Comment by ktoso** [comment]
Yeah what you propose would be nice; like a `filterType[]` / `filterType(clazz)`.
The other one could be seen like a fail fast -- it's basically the `mapTo` isn't it?

**Comment by hepin1989** [comment]
I am sorry,it's for the Java api .

https://github.com/hepin1989/N-ways-to-cook-JianBingGuoZi/blob/master/src/main/java/reactive/akkastream/JBGZ.java

I was demonstrating 7 ways to cook a pancake and found sometimes the API of Akka stream's Java API could improve a little.

**Comment by hepin1989** [comment]
@johanandren in Java you can't assign an Source<Apple> to Source<Fruit> , so that's why I need it.

![image](https://user-images.githubusercontent.com/501740/34624464-62f776a4-f290-11e7-9014-30079c7882bb.png)

**Comment by ktoso** [comment]
Merged `collectType`

**Comment by ktoso** [comment]
Oh, thanks for closing
