### ISSUE TITLE
Rename ActorContext in javadsl and scaladsl to ActorDSLContext or just rename ActorContext lives in typed

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24260]
`ActorDSLContext` is a better name and I think 
import ...ActorContext => AC and TAC smell like `WC`.

**Comment by ktoso** [comment]
No. It's not a DSL context, it's the Actor's context, possesive.

What WC do you mean... please explain more when you open these tickets ;)

**Comment by ktoso** [comment]
Eh.. found that you mean https://github.com/akka/akka/pull/24251/files#r159982358

Please don't make us do such detective work for each new ticket, link between comments and tickets.

**Comment by ktoso** [comment]
If anything, then we should avoid the AC type alias

**Comment by hepin1989** [comment]
WC means public toilet, and we should not use shortcut name like `AC` `TAC` which will make code hard to understand. even it's inner implement, cause someone there may want to contribute.

And I know it's an ActorContext but there are three ActorContext, it would help greatly to make the one lives in `typed` and the ones live in `*dsl` have the different name. 

![image](https://user-images.githubusercontent.com/501740/34637154-a774453c-f2ea-11e7-88c1-3a4a8f9baa14.png)

**Comment by hepin1989** [comment]
And must `akka.actor.typed.ActorContext` live ?Why not itjust named as ActorContextConvertor?

**Comment by johanandren** [comment]
I disagree that an abbreviation-type alias is a problem when we have two types of the same name to distinct in internal code. If it was public API it would be a different matter.

**Comment by ktoso** [comment]
Good, if it's internal indeed then the aliases are fine.

**Comment by johanandren** [comment]
I'll close this as the alias is entirely internal and I don't think we will act on it. Thanks for taking it up for discussion @hepin1989.
