### ISSUE TITLE
expectNoMessage should consume the message from the queue

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24270]
In the recent PR https://github.com/akka/akka/commit/dfd94d3aeabab5e352f9330f4b7386afddaf92fa the implementation was changes such that it dopes not consume the not-expected-message.

I think this was rather accidental so fixing it.

The peek + sleep is fine, though we also should pop after that.

Refs https://github.com/akka/akka/issues/23224 which was the rewrite

**Comment by johanandren** [comment]
Hmm, does it matter, when it will fail the test anyway?

**Comment by ktoso** [comment]
I think it was an unintended change in semantics.
Use cases is a bit weird but reasonable, see `[akka-user] expectNoMessage keeps unexpected message in the queue`

**Comment by johanandren** [comment]
Ah, yes, https://groups.google.com/forum/#!topic/akka-user/NXHxu2sWFTU

Thanks for clarifying.

**Comment by ktoso** [comment]
Sorry for lack of direct link :)
