### ISSUE TITLE
Consider config way of excluding classes from serialize-messages=on

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24273]
Sometimes libraries did not mark their types that they send around as `NoSerializationVerificationNeeded` yet they should have in order for other users to easily be able to use `serialize-messages`. Such users then are in trouble, as there's no retroactive way to add such class to the ignored list. They need to wait for the library to include the marker, or avoid that check in their build entirely.

WDYT?

Since the feature is aimed for testing anyway, that check if one is in such bad place sounds like not too bad.

**Comment by johanandren** [comment]
I think `serialize-messages` is one of the more useless features in Akka, and I have seen people stumble when trying to use it so many times (we have it disabled in most of our own tests for example). I'd rather see that we deprecated and provided some other tool to verify that messages that will go over the wire are serializable.

**Comment by patriknw** [comment]
I agree, and it's rarely a reality that all actor can be running anywhere. It's often part of the design that some actors will always be local to other actors.

**Comment by patriknw** [comment]
This becomes even more relevant now when we disable Java serialization by default. There will be many complaints about Akka internal classes that are not marked with `NoSerializationVerificationNeeded`, and we can't really sprinkle that everywhere.

The minimum we need to do is to always exclude all classes from `akka` package.
