### ISSUE TITLE
[akka-testkit] naming consistency: expectMsg vs expectNoMessage

### ISSUE THREAD

**Issue by cornerman** [akka/akka#24288]
I have recently updated akka to version `3.5.8` and now get a new deprecation warning about `expectNoMsg` being deprecated in favor of `expectNoMessage`. I was expecting that methods like `expectMsg` or `expectMsgAllOf` would be renamed to use the word Message instead Msg as well. Any reason for introducing this inconsistency in naming these methods?

**Comment by ktoso** [comment]
I don't think it's worth deprecating *all* the methods and cause people a lot of headache, where in reality we only needed to address an issue in the "one different one" which is the `expectNo...`

**Comment by cornerman** [comment]
I agree that renaming/deprecating so many methods could cause some headache. But why didn't we just keep the common Msg abbreviation for the `expectNoMsg` method?

Anyway, this is just minor nitpick. I was just curious, because when I saw the deprecation warning, I immediately renamed everything else, too; so I would have expected this renaming ;)

**Comment by raboof** [comment]
There is some background in issue #20255: in short we decided `expectNoMsg` had the wrong semantics, but just changing the semantics of `expectNoMsg` might make a lot of existing tests fail. For that reason we introduced `expectNoMessage` with the 'fixed' semantics, and are telling people to switch to that on their own pace.

**Comment by ktoso** [comment]
Thanks for the details @raboof, I propose we close this ticket :)

**Comment by cornerman** [comment]
ah ok. thanks for the explaination!
