### ISSUE TITLE
akka-stream FileIO uses synchronous (fsynced) writes regardless of file open options

### ISSUE THREAD

**Issue by ANorwell** [akka/akka#24299]
The `FileIO.toPath` method, which writes a stream of ByteStrings to a file, always uses synchronous file writes, i.e. calls fsync after it has finished writing the file. I found this unexpected, because I hadn't provided the `SYNC` open option [1]. To me, more natural default behaviour would be:
1. If SYNC is set, always sync after every new set of bytes.
2. If SYNC is not set, never sync, including after all bytes are written.

Applications that write lots of files would be negatively impacted by this behavior due to the many calls to fsync, and I think this is unexpected to most users (and not documented).

The implementation that causes this may be seen here:

https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/io/FileSubscriber.scala#L70

Under the hood, a `FileChannel` is used. It would be sufficient to just not call `force`. 

[1] https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardOpenOption.html#SYNC

**Comment by johanandren** [comment]
I can see why not syncing on every chunk makes sense from a performance point of view, but why would it be important to not sync on stream completion?

**Comment by ANorwell** [comment]
It has a huge impact on performance, especially for spinning disks. By delaying the write, the OS can sequence multiple writes in a way that is optimized.

I have benchmarked this using a setup that matches our environment and use-case. I use `FileIO` to write 72kb files in parallel to disk, using the ZFS filesystem and a pool of mirrored spinning disks. With the fsync, write throughput is 7.8MB/s. Without fsyncing after every file, write throughput is 1700.0 MB/s -- a factor of over 200x!

(Because ZFS has a setting to ignore file sync operations, it's possible to test fsync vs no fsync with no code changes at all, using `FileIO`. Disk utilization was observed to be maximum during the tests.)

**Comment by johanandren** [comment]
Very surprising to users when the streams completed successfully and the sync failed later though? If we don't care about data then `Sink.ignore` is super fast ;)

**Comment by johanandren** [comment]
What I'm saying is reasonable performance plus safety is a good default (unless I misunderstood something about the problem), but we can definitely have a no-safety-belt-blazing-fast as an opt in.

**Comment by ANorwell** [comment]
Exposing this as an option sounds great. Backwards-compatibility concerns aside, I think it makes sense for the default to change.

I don't think defaulting to not fsync-ing is surprising. This matches java file I/O interfaces work:
- Calling `flush` on a outputstream does not trigger a fsync -- see https://docs.oracle.com/javase/6/docs/api/java/io/OutputStream.html#flush%28%29. It only flushes java's buffer. To flush using old IO, you have to get the file descriptor and call `sync` on it. This is not something you see discussed often and I don't think most java/scala devs are aware of the distinction.
- `FileChannel` provides a separate `force` method that you have to call for force a fsync. Calling `close` does not generate a `fsync`.
- `java.nio.file.Files.write` will not sync unless the `SYNC` flag is passed.

The way I interpret java file interfaces is basically: either you provide the `SYNC` flag, in which case you are saying that your application needs a guarantee that writes are completed to durable media immediately, or you don't provide the `SYNC` flag -- the default! -- indicating that you want to let the OS confirm the write when appropriate. I think the reason that at both the java level and the OS level, fsyncs are explicit, is because the performance impact they have is so large.

**Comment by johanandren** [comment]
Alright, you have convinced me. Up for a PR fixing it?

**Comment by ANorwell** [comment]
Sure

**Comment by ktoso** [comment]
Sounds good, I agree on the sync rather should-be-ing opt-in, thanks for noticing, looking forward to the PR!

**Comment by jrudolph** [comment]
Fixed by #24314. Thanks for raising and fixing this issue, @ANorwell.
