### ISSUE TITLE
Unclear error message from cluster sharding when no cluster has formed

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#24295]
When starting an application that uses Akka Cluster Sharding, if no cluster has been joined (e.g., because of forgotten seed node configuration) there is a cryptic error message:

```
Trying to register to coordinator at [None], but no acknowledgement.
```

This doesn't communicate the underlying issue, which is usually a misconfiguration.

## Reproduction

1. Clone the akka-samples repo and `cd` to [`akka-sample-sharding-scala`](https://github.com/akka/akka-samples/tree/2.5/akka-sample-sharding-scala)
2. Edit `src/main/resources/application.conf` and delete the `seed-nodes` setting
3. sbt "runMain sample.sharding.ShardingApp 2551"
4. It logs an INFO-level message saying "Cluster Node [akka.tcp://ShardingSystem@127.0.0.1:2551] - No seed-nodes configured, manual cluster join required", but because the application continues normally and the message is at INFO level, it is easy to miss this.
5. Eventually, you will begin to see "Trying to register to coordinator at [None], but no acknowledgement." warnings logged. It isn't clear that this is connected to the fact that the actor system hasn't joined a cluster.

## References
- https://groups.google.com/d/topic/akka-user/VDsHEM2Sxx0/discussion
- https://groups.google.com/d/topic/akka-user/Qf5b9ii4-Z4/discussion
- https://groups.google.com/d/topic/akka-user/JOQLWAI8Zvc/discussion
- https://github.com/lagom/lagom/issues/500

**Comment by patriknw** [comment]
I agree. It should be possible to give a much better warning both for the case when there is no members in the cluster and when the expected member is unreachable.
