### ISSUE TITLE
Stream materialization and custom guardian in typed

### ISSUE THREAD

**Issue by 2m** [akka/akka#24298]
A typed actor system is normally started providing a behaviour which is converted to guardian props before starting the untyped actor system.

Using such actor system with stream materializer is a problem because then the materialized top-level stream actor cannot be attached to the custom guardian: https://github.com/akka/akka/blob/a3ae494325e9c8f1511e01b6c204d62e7a49c66f/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L717-L724

**Comment by johanandren** [comment]
Ah, now I see that/how it is different from (but also a little bit related to) #24279

**Comment by johanandren** [comment]
Typed actor materializer perhaps spawn its actors under system instead?

**Comment by ktoso** [comment]
Keeping them under system sounds a bit weird at first but... 

Since the streams hierarchy is kind of flat anyway so perhaps could make sense, esp since their failure handling is also not really the same as the actor one. WDYT, should I attempt that?

**Comment by patriknw** [comment]
Sounds ok to me
