### ISSUE TITLE
Actors are not unsubscribed from DistributedPubSub on termination

### ISSUE THREAD

**Issue by naiello** [akka/akka#24294]
Hi all. I hit a problem today where it appears the DistributedPubSub system is not automatically unsubscribing actors from topics when they terminate (which is contrary to the [PubSub documentation](https://doc.akka.io/docs/akka/current/distributed-pub-sub.html#publish)). I have a snippet demonstrating this behavior [here](https://gist.github.com/naiello/f97a77398e5bce8fe9937dad5171a999). Since references to the ActorRef instances are retained by the DistributedPubSubMediator, the JVM can't garbage collect them and they accumulate on the heap.

After investigating the issue, I found [this](https://github.com/akka/akka/blob/master/akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala#L350) (L350). It appears the Terminated message handler in TopicLike removes the dead subscriber from the set, but the Terminated handler is overridden via .orElse in the Topic class, and the behavior is not replicated in Topic.

I'd be happy to submit a pull request against this tomorrow.

**Comment by patriknw** [comment]
@naiello Thanks for finding this. It must be regression. PR is much welcome.

**Comment by jbergfi** [comment]
We've struck into the exact same issue and I created another PR #24485 before noticing this issue and PR.
There might be other similar bugs with the TopicLike & Topic class, might be worth for someone with better knowledge than me to have a look over the other messages that are overriden.
