### ISSUE TITLE
ActorSystem.terminate for Java API returns Scala Future

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka#24303]
When working with Akka in Java, it seems that the ActorSystem.terminate returns a Scala Future.

It would be preferred that this return a Java CompletableFuture instead.

See here:
https://doc.akka.io/japi/akka/current/akka/actor/ActorSystem.html#terminate--

**Comment by johanandren** [comment]
We can't change the signature, because that would break binary compatibilty and we would still want one returning `Future` for the Scala users. 

What we could introduce a new method that returns a `CompletionStage` instead, we have previously called such methods `nnnCS`.

**Comment by patriknw** [comment]
We could add `def getWhenTerminated: CompletionStage`, and the convention for Java would be:
```
system.terminate();
CompletionStage<Terminated> terminated = system.getWhenTerminated();
```

**Comment by ktoso** [comment]
This proposal sounds good :+1:

**Comment by evis** [comment]
I'd like to implement this. I think, I will send PR today or tomorrow.

BTW, seems like we should add such method to `akka.actor.typed.ActorSystem` too.

**Comment by patriknw** [comment]
Thanks.

Wonder if we should change the typed ActorSystem to not be biased by returning `Unit` from `terminate()` and the Future/CS is accessed via `whenTerminated` and `getWhenTerminated`?
