### ISSUE TITLE
Stream Cookbook example for digest refers to Trigger

### ISSUE THREAD

**Issue by ochrons** [akka/akka#24317]
https://doc.akka.io/docs/akka/2.5.5/scala/stream/stream-cookbook.html#calculating-the-digest-of-a-bytestring-stream

This example defines `override def onPull(): Trigger` and `override def onPush(): Trigger`. Both methods should return `Unit` instead of `Trigger`.

**Comment by johanandren** [comment]
Heh, weird `Trigger` is a type alias for `Unit`. Would be great if you can make a PR and change those!

**Comment by ochrons** [comment]
Looks like the only place that `Trigger` alias is defined is in https://github.com/akka/akka/blob/644050dc3342f5888afdcd959da496c4b194633b/akka-docs/src/test/scala/docs/stream/cookbook/RecipeSpec.scala :)

**Comment by johanandren** [comment]
Must be some left over from before the API stabilized.
