### ISSUE TITLE
Missing address in serialized path of EmptyLocalActorRef actorRef when no currentTransportInformation is available.

### ISSUE THREAD

**Issue by gbrd** [akka/akka#24321]
akka-persistence-mongo plugin  (https://github.com/scullxbones/akka-persistence-mongo/) chooses to have a custom serialization of PersistentRepr (I guess it's allowed ?). Thus when serializing an actorRef (in the context of ClusterShardingMessageSerializer for example)  in serializedActorPath method  in  akka.serialization.Serialization, currentTransportInformation is not available, and EmptyLocalActorRef are serialized without address. 
Proposal: in serializedActorPath when actorRef is a EmptyLocalActorRef, uses it's provider.getDefaultAddress for toSerializationFormatWithAddress.

I can provide more details, information to reproduce if necessary.

**Comment by patriknw** [comment]
That would be wrong if passing around ActorRef that is not local. Better that the MongoDB plugin sets the currentTransportInformation, as it's supposed to do.

Here is example code from Cassandra plugin:

https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L419

https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/package.scala#L50

**Comment by gbrd** [comment]
Hi @patriknw 
Thanks for this quick answer.
I will look at this in mongodb plugin code.

Just to understand : 
- can it really be "not local" if it is an EmptyLocalActorRef ? (in my case, it was deserialized from database and had (in database) an address which matches the local system). 
- Would it be a good idea to add "transportInformation" in ClusterShardingMessageSerializer directly ?

**Comment by patriknw** [comment]
The intention is that the `transportInformation` should always be set by the surrounding callers of the serializers to avoid having to deal with that in each an every serializer. For example that is done by Akka remoting for serialization of remote messages. Here, it must be done by the Persistence plugin.

**Comment by gbrd** [comment]
Do you think it could be documented more explicitly here : https://doc.akka.io/docs/akka/current/persistence.html?language=scala#journal-plugin-api ?

**Comment by patriknw** [comment]
Good point. I think we should add API in `Serialization`:

```scala
def withTransportInformation(system: ExtendedActorSystem)(f: () => Unit): Unit = {
  val address = system.provider.getDefaultAddress
  if (address.hasLocalScope) 
    f()
  else 
    Serialization.currentTransportInformation.withValue(Serialization.Information(address, extendedSystem)) {
        f()
      }
}
```

Then we don't need to expose that `Serialization.Information` and it can be used from such persistence plugins.

**Comment by gbrd** [comment]
I sounds better to me.
... even if my very personal opinion (and without mastering this piece of code) is that passing "implicit" parameters though DynamicVariable is a little bit confusing. I understood it's a kind of trick/optimisation... but it can easily be forgotten because it is not needed explicitly. 

Maybe using some implicit parameter would help ? without being explicit ;) code would not compile if not provided.

**Comment by gbrd** [comment]
May I propose this signature :
```scala
def withTransportInformation[T](system: ExtendedActorSystem)(f: => T): T = {
    val address = system.provider.getDefaultAddress
    if (address.hasLocalScope) {
      f
    } else {
      Serialization.currentTransportInformation.withValue(Serialization.Information(address, system)) {
        f
      }
    }
  }
```

**Comment by ktoso** [comment]
Sounds good, but `() => T` please to signify the lambda there explicitly

**Comment by patriknw** [comment]
sounds good, would you be able to create a PR @gbrd ?

**Comment by gbrd** [comment]
sure, ASAP

**Comment by gbrd** [comment]
PR #24515
