### ISSUE TITLE
Typed Scala testkit should be in package scaladsl

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24334]
Is currently directly in `akka.testkit.typed` while the javadsl `TestKit` is under `akka.testkit.typed.javadsl` (and possibly more of the test types as well)

**Comment by johanandren** [comment]
Oh, wait, maybe it is meant for both Java and Scala?

**Comment by chbatey** [comment]
I hadn’t seen a reason to separate them out yet, I don’t think we have anything in javadsl.

We might  want to have separate ones anyway before api May change is removed

**Comment by johanandren** [comment]
Related to #24542

**Comment by chbatey** [comment]
I'm going to leave fixing the junit tests until we rework the java testkit, which i won't look at until this is done

**Comment by johanandren** [comment]
Alright, thanks for letting me know.
