### ISSUE TITLE
Typed props accept unsupported ExecutionContext/Executor

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24337]
`Props.empty.withDispatcher.withExecutionContext/withExecutor`
Which wont really work with the adapter untyped actor system. I think we should remove those.

**Comment by patriknw** [comment]
There are also some other things that should be removed or adjusted, such as mailbox capacity (getMailboxCapacity in ActorContext)

**Comment by jrudolph** [comment]
I see so the problem right now is that in untyped the only way to specify dispatchers is via a named to reference a config section. I think being able to provide custom dispatchers (or run on ExecutionContexts directly) seems like a useful feature for both typed and untyped. This was previously filed as https://github.com/akka/akka/issues/17568 so I added a comment there no to forget adding it to typed back as well.
