### ISSUE TITLE
Akka Streams Source Java DSL uses Scala's Finite Duration

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka#24339]
`Source.tick` takes Scala's `FiniteDuration` as parameters.  Would it be better to use Java constructs instead (such as `java.time.duration`)?

https://doc.akka.io/japi/akka/current/akka/stream/javadsl/Source.html#tick-scala.concurrent.duration.FiniteDuration-scala.concurrent.duration.FiniteDuration-O-

**Comment by hepin1989** [comment]
Yes，we could add an API for Duration:)

**Comment by patriknw** [comment]
We discussed this and are willing to give it to try to add java duration.

**Comment by patriknw** [comment]
Related https://github.com/akka/akka/issues/24646
