### ISSUE TITLE
Complete TestEventListener in typed testkit

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24348]
It seems `akka.testkit.typed.TestEventListener` was started on but it is not complete (or I'm missing something on how to use it)

**Comment by johanandren** [comment]
We cut that out since it was tightly coupled with the new typed actorsystem which was ripped out. Most important now would be a way to create the untyped TestEventListener with a wrapped actorsystem without having to do the unwrapping ourselves. Maybe just provide a subclass for the event listener to use in the config to get future-proofing.

**Comment by johanandren** [comment]
Would be good to also improve the Java side in typed compared to the untyped event filter, make use of lambdas, allow custom event filtering for example.

**Comment by TisonKun** [comment]
@johanandren is there a branch work on this?

**Comment by johanandren** [comment]
No, as far as I know nobody started any work on it.

**Comment by patriknw** [comment]
One consideration is that perhaps we should investigate #26537 before doing this so that we don't implement this first and have to throw away or completely rewrite.

**Comment by patriknw** [comment]
This was done as part of #26537

**Comment by patriknw** [comment]
It's named javadsl.LoggingEventFilter / scaladsl.LoggingEventFilter and is part of akka-actor-testkit-typed.
