### ISSUE TITLE
LoggingReceive not outputting enough context in some cases

### ISSUE THREAD

**Issue by mvdstam** [akka/akka#24351]
Hey all,

I am encountering the following case.

I am sending messages to my actors which are encoded using Protobuf3. Many of these messages do not have any fields but are solely used as commands, e.g.:

```protobuf
message GetCurrentUrl {
    option (scalapb.message).extends = "DomainEvt";
}
```

When sending these messages, I see the following output in my logs:

`[debug] a.f.c.MyActor - received handled message  from Actor`

This is because `LoggingReceive.scala` simply interpolates the message by casting it to string:

```scala
val message = "received " + (if (handled) "handled" else "unhandled") + " message " + o + " from " + context.sender() +
        (label match {
          case Some(l) ⇒ " in state " + l
          case _       ⇒ ""
        })
```

Since my message in this case casts to an empty string, my log contains too little context to actually make sense.

I propose that the default value used here is simply the className of the object, if the object string value equates to an empty string. For example:

```scala
val oStr = Some(o.asInstanceOf[String]).filter(_ != "").getOrElse(o.getClass)
val message = "received " + (if (handled) "handled" else "unhandled") + " message " + oStr + " from " + context.sender() +
        (label match {
          case Some(l) ⇒ " in state " + l
          case _       ⇒ ""
        })
```

**Comment by johanandren** [comment]
Given that `LoggingReceive` is just 20 lines or so, just copying it and modifying it for your use case is probably the second best path here, if you can't get the generated protobuf classes to have any reasonable toString.

Closing this for now as it was lying around for so long, sorry about the long delay. Please reopen if you disagree.
