### ISSUE TITLE
Disallow remote deployment in typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24352]
Since we don't want to support it for typed actors we should make sure that it's not technically possible. I think it currently is, with configuration.

**Comment by nickpoorman** [comment]
@patriknw - What's the reason for disallowing remote deployment in Typed? Is there some place that explains this?

I'm trying to figure out how one would go about creating a pool of Remote Deployed Routees (or something similar) (see: https://doc.akka.io/docs/akka/2.5/cluster-usage.html?language=scala#router-example-with-pool-of-remote-deployed-routees) while trying to stick to Akka Typed.
