### ISSUE TITLE
GroupBy pulls upstream while a substream for a new group is waiting to be materialized

### ISSUE THREAD

**Issue by anilgursel** [akka/akka#24353]
When an element for a new group (per `groupBy` condition) is received and downstream (`out`) is not available, then that element is saved in a `var` named `substreamWaitingToBePushed`.  If any of the `SubStreamSource`s is pulled, the demand should not be propagated to upstream as there is an available element that  a substream needs to be materialized for.  However, it propagates the demand, and a new element comes to `groupBy`.  If the next element is again for a new group and downstream is still not available,  it overrides the `substreamWaitingToBePushed` with the new one.  This causes the previous element to be lost without materializing the substream.  Here is the code https://github.com/akka/akka/blob/v2.5.9/akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala#L369 where substream pulls.

PR is on the way to add another condition to `needToPull`.  

We are able to reproduce this issue in an internal code; however, having a hard time reproducing it in a simple example.

**Comment by jrudolph** [comment]
Fixed by #24354.
