### ISSUE TITLE
Failed: TimerSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24360]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11371/testReport/junit/

**Comment by johanandren** [comment]
I'm not sure if I can trust the log output but, if these two belongs to the same test case:

```
[DEBUG] [01/19/2018 12:21:44.809] [TimerSpec-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(TimerSpec)] Start timer [T] with generation [1]
[DEBUG] [01/19/2018 12:21:47.329] [TimerSpec-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(TimerSpec)] Cancel timer [T] with generation [1]
```

Then it is more than one second between starting the timer and cancelling it, meaning we should see more `Tock(1)`s than one.
