### ISSUE TITLE
Hard to merge Sources in sorted order, except 2 sources of same type

### ISSUE THREAD

**Issue by tonicsoft** [akka/akka#24369]
Use case: merging multiple Sources of different types, sorting by some user specified criteria (e.g. a timestamp)

Suggested Java API:

    Source<String, NotUsed> stringSource = Source.from(asList("1", "12", "123"));
    Source<Integer, NotUsed> intSource = Source.from(asList(1, 2, 3));
    
    // sort strings and integers by number of characters, or the integer itself
    Source<Object, NotUsed> merged = MergeSorted.builder(Integer::compare)
            .add(stringSource, String::length)
            .add(intSource, Function.identity())
            .build();
    // outputs "1", 1, "12", 2, "123", 3

To implement this I was faced with two choices: 
1. put each stream element in a wrapper object, and use existing mergeSorted functionality, then unwrap
2. implement a custom graph stage which of course is not trivial

I implemented both and neither was very pleasant. 

In case you are interested in the production use case, it involved combining many (>5) sources of different types of business events, and producing a single stream ordered by timestamps. It was not possible to make each type extend a common interface such as "HasTimestamp".

Use case 2: sort >2 streams of the same type:

    Source<Integer, NotUsed> source1;
    Source<Integer, NotUsed> source2;
    Source<Integer, NotUsed> source3;

    Source<Integer, NotUsed> merged = MergeSorted.builder()
            .add(source1)
            .add(source2)
            .add(source3)
            .build();

**Comment by johanandren** [comment]
The same can relatively easy be achieved through composition of `fold` (into a sorted collection) and `flatMapConcat` (the collection elements into the stream).

This could work well for your use case but it's not a great fit for a special stage within Akka Streams as any of the Sources can produce an infinite amount of elements, and this would collect all that close to infinite elements in memory before emitting anything downstream.

**Comment by johanandren** [comment]
Ah, ok, I see that was the missing piece of the puzzle, just sorting between the next element from `n` sources rather than ensuring the downstream will see _all_ elements sorted.

If I don't misunderstand you that is already available in `akka.stream.scaladsl.MergeSorted` (may be missing a Java API though)  but you have to use it with the GraphDSL to have `n` inputs. In general the "Flow API" does not (and is not meant to) nicely allow for more complicated graphs.

**Comment by tonicsoft** [comment]
Ok I will have a try in the next few days, and perhaps suggest an improvement to the docs.

**Comment by tonicsoft** [comment]
Apologies if I'm missing something here but the class you mentioned `extends GraphStage[FanInShape2[T, T, T]]` therefore I don't think it can be used for more than 2 streams. The handlers are hard coded as `left` and `right` so even with the GraphDSL I don't think it could support sorting n streams.

**Comment by johanandren** [comment]
Indeed, I missed that. Then it would indeed be good adding a `UniformFanInShape` version of it. Note that we cannot change the existing one as that would break binary compatibility.

**Comment by tonicsoft** [comment]
Cool, makes sense to not change the existing one. I would like to have a go at this - any objections to me starting to work on a PR?

**Comment by ktoso** [comment]
Yes, sounds good -- please have a go at it! Thanks

**Comment by kstokoz** [comment]
You can merge arbitrary number of streams with reduce:


```
 def mergeWithSorter[A](originSources: Seq[Source[A, NotUsed]]): Source[A, NotUsed] =
    merge(originSources, sorter[A])

  private def merge[A](originSources: Seq[Source[A, NotUsed]], f: (Source[A, NotUsed], Source[A, NotUsed]) => Source[A, NotUsed]): Source[A, NotUsed] = 
    originSources match {
      case Nil     =>
        Source.empty[A]
  
      case sources =>
        @tailrec
        def reducePairs(sources: Seq[Source[A, NotUsed]]): Source[A, NotUsed] =
          sources match {
            case Seq(s) =>
              s
  
            case _      =>
              reducePairs(sources.grouped(2).map {
                case Seq(a)    => a
                case Seq(a, b) => f(a, b)
              }.toSeq)
          }
  
        reducePairs(sources)
    }

  private def sorter[A](s1: Source[A, NotUsed], s2: Source[A, NotUsed])(implicit ord: Ordering[A]): Source[A, NotUsed] =
    combineSources(new MergeSorted[A], s1, s2){ (_, _) => NotUsed }

  private def combineSources[A, MatIn0, MatIn1, Mat](combinator: GraphStage[FanInShape2[A, A, A]], s0: Source[A, MatIn0], s1: Source[A, MatIn1])(combineMat: (MatIn0, MatIn1) => Mat): Source[A, Mat] =
    Source.fromGraph(GraphDSL.create(s0, s1)(combineMat) { implicit builder => (s0, s1) =>
      val merge = builder.add(combinator)
      s0 ~> merge.in0
      s1 ~> merge.in1
      SourceShape(merge.out)
    })
  ```

**Comment by tonicsoft** [comment]
@kstokoz thanks for the suggestion. For me it felt more natural to implement a new stage and I had already started working on it when you posted your suggestion. The result of my efforts is in the above PR, review welcome.

**Comment by tonicsoft** [comment]
this is now ready for review.

**Comment by johanandren** [comment]
Closing this since we never got there, and there is a workaround.
