### ISSUE TITLE
Local-only receptionist is started in cluster

### ISSUE THREAD

**Issue by dilation** [akka/akka#24379]
If the `akka.actor.provider` is `"akka.cluster.ClusterActorRefProvider"`, then the receptionist started in the typed actor system is local-only. Because [`hasCluster`](https://github.com/akka/akka/blob/master/akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala#L19) only checks for `"cluster"`.

**Comment by ktoso** [comment]
Good catch, will you send in a PR fixing this? Should be simple :)

**Comment by dilation** [comment]
See #24391.
