### ISSUE TITLE
Get rid of the Future in Future[SourceRef[_]] stream refs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24372]
In the stream refs proposal we found that it it difficult to expose things as materialized value without wrapping as a `Future` even if it is known that that future is immediately completed once the `preStart` of the stage logic executes.

One proposal to making this simpler, is making the materializer aware of such special values, that it should wait to be completed before completing materialization.

Alternative proposals were specific to the stream refs, and are similar to `FutureRef` of Akka Typed, however that would not work as we need to serialize the reference and it has to be targetable by remoting, so it can not be just a plain object, so it has to be registered with the Actor System.

Another idea is to register proxies in the local stream refs master, which could manage the proxies while things are being initialized, and otherwise just forward things to them directly?

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/pull/24230

**Comment by patriknw** [comment]
> SourceModule (soon to be deprecated)

That is not up for deprecation. It is ActorPublisher that is deprecated.

`MaterializationContext` is something that we would like to keep internal, but it's only the `Materializer` that is needed, right?

**Comment by nachinius** [comment]
> MaterializationContext is something that we would like to keep internal, but it's only the Materializer that is needed, right?

yes, we could pass just the materializer and would work.

**Comment by patriknw** [comment]
I think this is possible now, in the way that was introduced when rewriting `Source.actorRef` as a `GraphStage`, see `ActorRefSource` that is using the stage.ref as materialized value.

Let's attempt doing this for Akka 2.6 and then remove the ApiMayChange.
