### ISSUE TITLE
Running akka application using a bash script

### ISSUE THREAD

**Issue by jplvck** [akka/akka#24381]
Hello, 
I'm trying to run a Play+Akka application on AWS EC2 instance using `user-data` script (it is run when instance boots up). However, everytime I try to run the application using this bash script, actor wont join to cluster members group. (note that run configuration is passed as string variable to application)

`run.sh`
```
RUN_CONFIG="-Dakka.remote.netty.tcp.port=2552 -Dakka.remote.netty.tcp.hostname=public_ip -Dakka.remote.netty.tcp.bind-hostname=private_ip -Dakka.cluster.seed-nodes.0=akka.tcp://application@public_ip:2552"
my-application "$RUN_CONFIG" 
```
To check whether node is within cluster members I'm using Akka Management and the response for `cluster/members` is following:
```
{"selfNode":"akka.tcp://application@127.0.0.1:2552","members":[],"unreachable":[]}
```
On the other hand, when I ssh to EC2 instance, take exactly the same run config and pass it directly to application

```
my-application -Dakka.remote.netty.tcp.port=2552 -Dakka.remote.netty.tcp.hostname=public_ip -Dakka.remote.netty.tcp.bind-hostname=private_ip -Dakka.cluster.seed-nodes.0=akka.tcp://application@public_ip:2552
```
everything works perfectly and after checking management console I get
```
{"selfNode":"akka.tcp://application@public_ip:2552","leader":"akka.tcp://application@public_ip:2552","oldest":"akka.tcp://application@public_ip:2552","unreachable":[],"members":[{"node":"akka.tcp://application@public_ip:2552","nodeUid":"-298881852","status":"Up","roles":["frontend","dc-default"]}]}r
```

The reason I need to have application parameters in variable is that I need to dynamically generate appropriate number of arguments (`akka.cluster.seed-nodes`) based on number of already running nodes within an architecture.

Any suggestions how to solve this issue?
I dont know whether this issue is directly related to akka, but I would appreciate any help as I got stuck on this for quite a long time.

Thank you in advance!

**Comment by johanandren** [comment]
Hi @jplvck we try to use the issue tracker only for issues and feature-tracking (additionally there is a separate tracker for the akka-management project: https://github.com/akka/akka-management/issues ) and I think this is more of a question, please use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) or the [gitter channel](https://gitter.im/akka/akka) for questions, thanks!
