### ISSUE TITLE
StopReading existing EndpointReader on outbound association in EndpointManager#handleInboundAssociation may cause restarted node cannot re-join the cluster

### ISSUE THREAD

**Issue by ykq-zte** [akka/akka#24393]
EndpointManager#handleInboundAssociation will send StopReading message to ReliableDeliverSupervisor and its EndpointWriter/EndpointReader sub-actor on the outbound association when InboundAssociation event comes after the outbound association has alreay setup all its endpoint/protocol-state actors. 

The StopReading message will cause the EndpointReader on outbound association enter notReading receiving state and so it will discard all messages sent by peer to it through this association SILENTLY.

If the endpoint/protocol-state actors on inbound association stop or not correctly setup, inbound association will stop its working though its TCP connection still keep in stable ESTABLISHED state.

On this case, all the messages from peer will be received through outbound association and be discarded SILENTLY by the notReading EndpointReader on outbound association and won't arrive its destination actor.  Especially the InitJoinAck message won't arrive to the JoinSeedNodeProcess actor, and the restarted node won't re-join the akka cluster.

We've reproduced this issue on akka-2.3.10 and akka-2.4.8 by setting up a two-node cluster with OpenDaylight controller on the AKKA. Let the first-seed node stay unchanged, and let the other node down, wait a few seconds and restart again. In most times, the other node can re-join the cluster managed by the first-seed node successfully. But occasionly it cannot re-join the cluster due to above issue.

Why do we need StopReading? Can we do NOT StopReading? If we don't StopReading, we have two associations to read/write which is more safe. 

However I don't figure out why the endpoint/protocol-state actors on inbound association stop or not correctly setup until now. I've worked on this issue one week and above analysis is where I've arrived. Now I need your help.

**Comment by ykq-zte** [comment]
I've found the root cause of this problem. The EndpointWriter of outbound association on the leader node maybe occasionally stop due to the association exception or message send failure, and it won't be created again because of the akka.remote.use-passive-connections is on on default. So the leader node has only the inbound association to communicate with peer node who try to join the cluster. And such association is often set to notReading on the node restarted to join the cluster.

**Comment by patriknw** [comment]
That is a very interesting finding. We will absolutely look into this. Next week will be busy with physical meetings. If you know how to fix or have a way to reproduce in a test that is much welcome. This area is very difficult so np if you can’t.

That is another data point of why we should perhaps not have passive connections (by default).

**Comment by ykq-zte** [comment]
Yes, you're right, Patrik. I also think that turning off passive connection can prevent this problem from happening to become a user-aware fault. 

I'll try to reproduce this problem in a unit-test at first.  This is the first and fundamental step to fix a bug.

**Comment by patriknw** [comment]
Added some logging in https://github.com/akka/akka/pull/25127

* this is an area of the classic remoting that there is a high risk that we
will break more than we would fix by trying to harden this race condition
* it's tempting to change use-passive-connections=off by default
but we don't know what other issues that might reveal, for example is it completely safe to do a rolling upgrade with this setting to be different on different nodes?

I'd recommend using Artery TCP.

**Comment by patriknw** [comment]
The new logging appears in a test failure of ClusterStressSpec: https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1114

**Comment by patriknw** [comment]
The logging is in other tests also, perhaps investigate if that is expected and consistent over test runs. SystemMessageDeliveryStressTest in https://jenkins.akka.io:8498/job/akka-nightly/5771/consoleText

**Comment by jbergfi** [comment]
We are seeing a lot of the new message (several each minute) in our production logs (from the leader node) but we can't see any visible problems with the cluster. Should we be alarmed or can we ignore it? We are using Akka 2.5.16

**Comment by patriknw** [comment]
It hurts me to close an issue like this without being able to fix it, but given the difficulties of reproducing, tracking down the root cause, and fix this without introducing other regression I think that is what we have to do. Artery TCP is ready for production since 2.5.22 and I would recommend updating to that if this is still causing trouble.
