### ISSUE TITLE
Persistence query with multiple persistence plugins

### ISSUE THREAD

**Issue by omj** [akka/akka#24394]
I use akka persistence with leveldb (multiple plugins configuration)

```
akka {
  persistence {
    module1.journal {
      class = "akka.persistence.journal.leveldb.LeveldbJournal"
      native = on
      fsync = on
      dir = "target/persistence/module1-journal"
      checksum = off
      compaction-intervals = {
        "*" = 250
      }
    }

    module2.journal {
      class = "akka.persistence.journal.leveldb.LeveldbJournal"
      native = on
      fsync = on
      dir = "target/persistence/module2-journal"
      checksum = off
      compaction-intervals = {
        "*" = 250
      }
    }
  }
}
```

When I try to use persistence query
```
import system.dispatcher
import akka.persistence.query.PersistenceQuery
import akka.persistence.query.journal.leveldb.scaladsl.LeveldbReadJournal

implicit val materializer = ActorMaterializer()
implicit val timeout = Timeout(20.seconds)

val queries = PersistenceQuery(system).readJournalFor[LeveldbReadJournal](
"akka.persistence.module1.journal")

val src: Source[String, NotUsed] =
queries.currentPersistenceIds()
```
I get 

> Unable to create read journal plugin instance for path [akka.persistence.module1.journal], class [akka.persistence.journal.leveldb.LeveldbJournal]! 
[info] java.lang.IllegalArgumentException: Unable to create read journal plugin instance for path [akka.persistence.module1.journal], class [akka.persistence.journal.leveldb.LeveldbJournal]!
[info] 	at akka.persistence.query.PersistenceQuery$$anonfun$akka$persistence$query$PersistenceQuery$$createPlugin$4.applyOrElse(PersistenceQuery.scala:96)
[info] 	at akka.persistence.query.PersistenceQuery$$anonfun$akka$persistence$query$PersistenceQuery$$createPlugin$4.applyOrElse(PersistenceQuery.scala:93)
[info] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
[info] 	at scala.util.Failure.recoverWith(Try.scala:232)
[info] 	at akka.persistence.query.PersistenceQuery.akka$persistence$query$PersistenceQuery$$createPlugin(PersistenceQuery.scala:93)
[info] 	at akka.persistence.query.PersistenceQuery$$anon$1.createExtension(PersistenceQuery.scala:64)
[info] 	at akka.persistence.query.PersistenceQuery$$anon$1.createExtension(PersistenceQuery.scala:62)
[info] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:880)
[info] 	at akka.actor.ExtensionId.apply(Extension.scala:78)
[info] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
[info] 	at akka.persistence.query.PersistenceQuery$$anon$1.apply(PersistenceQuery.scala:62)
[info] 	at akka.persistence.query.PersistenceQuery.readJournalPluginFor(PersistenceQuery.scala:60)
[info] 	at akka.persistence.query.PersistenceQuery.readJournalFor(PersistenceQuery.scala:46)
[info] 	at mypackage.MyActor$$anonfun$receive$1.applyOrElse(MyActor.scala:52)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
[info] 	at mypackage.MyActor.aroundReceive(Reindexer.scala:24)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] Caused by: akka.actor.ActorInitializationException: You cannot create an instance of [akka.persistence.journal.leveldb.LeveldbJournal] explicitly using the constructor (new). You have to use one of the 'actorOf' factory methods to create a new actor. See the documentation.
[info] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:194)
[info] 	at akka.actor.Actor.$init$(Actor.scala:472)
[info] 	at akka.persistence.journal.leveldb.LeveldbJournal.<init>(LeveldbJournal.scala:23)
[info] 	at akka.persistence.journal.leveldb.LeveldbJournal.<init>(LeveldbJournal.scala:26)
[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info] 	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:32)
[info] 	at scala.util.Try$.apply(Try.scala:209)
[info] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:27)
[info] 	at akka.persistence.query.PersistenceQuery.akka$persistence$query$PersistenceQuery$$instantiate$1(PersistenceQuery.scala:83)
[info] 	at akka.persistence.query.PersistenceQuery$$anonfun$akka$persistence$query$PersistenceQuery$$createPlugin$3.applyOrElse(PersistenceQuery.scala:92)
[info] 	at akka.persistence.query.PersistenceQuery$$anonfun$akka$persistence$query$PersistenceQuery$$createPlugin$3.applyOrElse(PersistenceQuery.scala:92)
[info] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
[info] 	at scala.util.Failure.recoverWith(Try.scala:232)
[info] 	at akka.persistence.query.PersistenceQuery.akka$persistence$query$PersistenceQuery$$createPlugin(PersistenceQuery.scala:92)

Only when I add default configuration
```
akka {
  persistence {
    journal { // bugfix for persistence query
      plugin = "akka.persistence.journal.leveldb"

      leveldb {
        dir = "target/persistence/module1-journal"
      }
    }
  }
}
```
and use default persistence identifier
```
val queries = PersistenceQuery(system).readJournalFor[LeveldbReadJournal](LeveldbReadJournal.Identifier)
```
it starts working (I can see events from module1-journal). 

BTW, LeveldbReadJournal.Identifier resolves to "akka.persistence.query.journal.leveldb" which I can't find in reference.conf

So what is the correct way to configure leveldb persistence query for use with multiple plugins?

(In my case I simultaneously read events from persistence query and write new events to same persistence plugin and my workaround fails because in result I have 3 configured plugins and two of them point to same database. And because plugin locks database for exclusive access I got "IO error: lock .../module1-journal/LOCK: already held by process")

**Comment by Captain1653** [comment]
This issue is quite old. LevelDb was deprecated in [this PR](https://github.com/akka/akka/pull/30213).

Should this issue be closed?

**Comment by johanandren** [comment]
Yes, let's close
