### ISSUE TITLE
weird compression, sent for old incarnation

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24400]
When testing Artery TCP I noticed that the something is weird with compression table.
Using the SimpleClusterApp, two nodes 2551 and 2552.
After a while `kill` of the 2552 process, which triggers graceful shutdown and cluster leaving.
Restart 2552 again before it has been quarantined (that is delayed for leaving).

In log of the restarted 2552:
```
[info] [DEBUG] [01/23/2018 17:40:30.570] [ClusterSystem-akka.remote.default-remote-dispatcher-5] [akka.remote.artery.ArteryTcpTransport(akka://ClusterSystem)] Discarding incoming ActorRef compression advertisement from [akka://ClusterSystem@127.0.0.1:2551#-6044862425511568538] that was prepared for another incarnation with uid [-3056538787284814204] than current uid [6116925288239264813]
```

[log-2251.txt](https://github.com/akka/akka/files/1656811/log-2251.txt)
[log-2552.txt](https://github.com/akka/akka/files/1656812/log-2552.txt)

If I instead wait with restarting until it has been fully quarantined then it is ok, but I think it should be able to use the right uid incarnation (remove old when new arrives).

**Comment by ktoso** [comment]
Didn't notice during bugfixing days, should we add the tag bug for this so I pick it up next time?

**Comment by patriknw** [comment]
I'll try to fix this while working on the cleanup of resources.
