### ISSUE TITLE
Document thread-safe aspect of typed.ActorContext

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24410]
We should add a comment to each method in Typed ActorContext telling if it's thread-safe or not. Perhaps break out the thread-safe methods into a separate trait `ThreadSafeActorContext`.

e.g. `self` is thread-safe, and `spawn` is not

Something like:
```
This field is thread-safe and can be accessed from other threads than the ordinary 
actor message processing thread, such as Future/CompletionStage callbacks.
```

```
Warning: This method is not thread-safe and must not be accessed from other threads
than the ordinary actor message processing thread, such as Future/CompletionStage callbacks.
```

**Comment by ktoso** [comment]
Good idea, I like the superclass idea as well 👍

**Comment by johanandren** [comment]
I disagree on the supertype because I think that encourages passing the context around outside of the actor which I think is not a good idea, regardless of thread safety.

**Comment by patriknw** [comment]
Yes, I was not thinking of exposing it (too much) to users. Mostly for our internal structure. But I can agree with your point. Documentation was my primary intention.

**Comment by ktoso** [comment]
I don't think it incentivizes that all that much but I'm fine with either, just for documenting it anyway :)
