### ISSUE TITLE
add Flow.lazyInit mirroring Sink.lazyInit

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#24427]
Sink.lazyInit allows the construction of a Sink in response to the beginning of the stream. Flows can be constructed using the method as well by closing them for example with a Sink.actorRef and wiring that up in `.mapMaterializedValue` with a fresh Source, using Sink.lazyInit for the first part. It would be nice to take this ceremony and associated runtime overhead from the users into the library, with obvious optimization opportunities.

An open question might be whether it is possible to switch out flows while the stream is running, similar to RxJava’s `switchMap` operator, but this may be challenging to the point of uselessness due to the multi-threaded Akka Streams runtime environment.

**Comment by ktoso** [comment]
Sounds useful. 

The switch one is absolutely possible to do, in fact the interpretater enables this pretty easily.. let’s keep this ticket about the init one though. :)

**Comment by gosubpl** [comment]
On it.

**Comment by ktoso** [comment]
Thanks guys :)

**Comment by hepin1989** [comment]
FYI, the rxjava's `switchIfEmpty` is useful too.

**Comment by gosubpl** [comment]
What would be the preferred API? Do we need the Future Factory
```
def lazyInit[I, O, M](flowFactory: I ⇒ Future[Flow[I, O, M]], fallback: () ⇒ M): Flow[I, O, Future[M]]
```

or is the standard immediate factory enough?
```
def lazyInit[I, O, M](flowFactory: I ⇒ Flow[I, O, M], fallback: () ⇒ M): Flow[I, O, M]
```

The implementation might do the one with futures, whereas there would be an adapter with interface for immediate one just wrapping it in `Future.succesful()`.

The strong point for having the immediate API anyway is that in most usages the Flow has signature `Flow[I, O, NotUsed]`, so there is no place for future there.

I don't know though, if the 'future' version has any potential advantages over the 'immediate' one, as the `futureFactory` is delayed initialisation, anyway.

**Comment by patriknw** [comment]
@gosubpl I think it should be `Future[Flow]` to be consistent with `Sink.lazyInit` and it's more flexible without adding much more internal complexity. I think `Future.succesful` is simple enough for end users if they don't need the future.

Incidentally I was also looking for this feature the other day, for using in Artery. In other words I'm very interested in getting this done and looking forward to the PR.

**Comment by gosubpl** [comment]
Almost there. Expect PR real soon.
