### ISSUE TITLE
confusion in tutorial_5

### ISSUE THREAD

**Issue by sweetIan** [akka/akka#24435]
I am new to akka and confused with tutorial_5.

In https://doc.akka.io/docs/akka/current/guide/tutorial_5.html , the snippet in section "Adding query capability to the group" goes like

```
private void onAllTemperatures(RequestAllTemperatures r) {
    getContext().actorOf(DeviceGroupQuery.props(
            actorToDeviceId, r.requestId, getSender(), new FiniteDuration(3, TimeUnit.SECONDS)));
}
```

actorToDeviceId (a HashMap object) is shared by the group actor and the query actor.

consider this case:
1. a group actor G has 1 device actor D1.
2. G creates a query actor Q, a ReadTemperature message are sent to D1.
3. before D1 respond to Q, another device actor D2 is added to G.
4. (my guess) D2 never receives a ReadTemperature message from Q, but Q waits for its response until timeout.

maybe the snippet should be
```
private void onAllTemperatures(RequestAllTemperatures r) {
    getContext().actorOf(DeviceGroupQuery.props(
            new HashMap<>(actorToDeviceId), r.requestId, getSender(), new FiniteDuration(3, TimeUnit.SECONDS)));
}
```

Sorry if my understanding is wrong.

**Comment by sweetIan** [comment]
I just wrote a test that verified my guess. Maybe you should fix it. 
So using mutable objects while creating an actor is not a good practice in akka, right?

**Comment by ktoso** [comment]
Using mutable objects in messages is in fact an anti pattern, you're right.
We always have the problem with java docs since java does not include any immutable collections, and it's a pain to work with copying all the time... We could pull in guava or other immutable collections into the docs, but then it'd be seen as endorsing one but not some other library...

Personally I'd be ok with using guava's collections in our docs, but I wonder what the rest of the team thinks @akka/akka-committers

**Comment by sweetIan** [comment]
@ktoso Thanks for reply. I reviewed the scala snippets. It's absolutely clearer.

**Comment by patriknw** [comment]
We should absolutely do safe copies of java collections, if that is missing in the tutorial. I'm not sure we should bring in Guava. There will be debate on what collections library to use. There are better alternatives than Guava. For example you have to copy when "modifying" a Guava collection also.

**Comment by ktoso** [comment]
I'll fix this with copying java collections for now

**Comment by ktoso** [comment]
Thanks a ton for reporting @sweetIan ! Opened a PR
