### ISSUE TITLE
Failed: BasicClusterConfigSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24444]
https://jenkins.akka.io:8498/job/akka-nightly/5185/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/5186/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5688/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/978/consoleFull

```
[info] - must init cluster *** FAILED *** (552 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 6 times, sleeping 15 milliseconds between each query. (BasicClusterExampleSpec.scala:70)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at docs.akka.cluster.typed.BasicClusterConfigSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(BasicClusterExampleSpec.scala:70)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11557/

**Comment by johanandren** [comment]
90ms sounds like a pretty tight cluster init timeout.

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11568/testReport/junit/docs.akka.cluster.typed/BasicClusterConfigSpec/Cluster_API_must_init_cluster/

Yep should increase this

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11567/testReport/junit/docs.akka.cluster.typed/BasicClusterConfigSpec/Cluster_API_must_init_cluster/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11573/

**Comment by ennru** [comment]
It's back! Current Akka version is 2.6.10

https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2514/

```
sbt.ForkMain$ForkError: org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2: A timeout occurred waiting for a future to complete. Waited 10 seconds.
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
	at docs.akka.cluster.typed.BasicClusterConfigSpec.$anonfun$new$2(BasicClusterExampleSpec.scala:133)
```

**Comment by chbatey** [comment]
https://mail.google.com/mail/u/2/#inbox/FMfcgxwKjKkDSsJVbPCLcDgWKRhDlNGX

**Comment by chbatey** [comment]
^ This is different failure

**Comment by patriknw** [comment]
closing as old
