### ISSUE TITLE
AbstractPersistentFSM onTransition gets stuck in infinite loop

### ISSUE THREAD

**Issue by m0** [akka/akka#24448]
I am facing an issue with AbstractPersistentFSM `onTransition` being stuck in an infinite loop. This might be related to #22887 which [should have been fixed since milestone 2.5.2](https://github.com/akka/akka/issues/22887#event-1091831712). My project uses Java8 (openjdk version "1.8.0_151"), akka 2.5.8 and scala 2.12 artifacts. I put an example project on [github](https://github.com/m0/akka-persistence-transitionlogger-issue) reproducing the issue.

**Comment by patriknw** [comment]
I think that other issue was incorrectly closed without any action.

**Comment by filipmatusak** [comment]
I would like to solve it

**Comment by ktoso** [comment]
Thanks, please! :) Marked in progress

**Comment by patriknw** [comment]
great, thanks

**Comment by 2m** [comment]
Fixed in #24608
