### ISSUE TITLE
Actor fails with - java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher

### ISSUE THREAD

**Issue by vardhanv** [akka/akka#24452]
Hi, 

When testing the new AWS JDK for AWS S3 with Async support (see [here](https://github.com/aws/aws-sdk-java-v2)), I get a random stack trace as detailed below. This is original caused and much more predictable in the Streams code i had. I was able to isolate the behavior down to an Akka Actor. The trace is as follows:

```
 [aws-java-sdk-NettyEventLoop-0-0] ERROR software.amazon.awssdk.http.nio.netty.internal.ResponseHandler - Exception processing request: software.amazon.awssdk.http.DefaultSdkHttpFullRequest@10341627
[error] java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher
[error] 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1089)
[error] 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:443)
[error] 	at com.typesafe.netty.http.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:328)
[error] 	at com.typesafe.netty.http.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:189)
[error] 	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:165)
[error] 	at com.typesafe.netty.http.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:148)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[error] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
[error] 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
[error] 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[error] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[error] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[error] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
[error] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
[error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
[error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
[error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
[error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[error] 	at java.lang.Thread.run(Thread.java:745)

```

This can be replicated using the following code fragment (you may need to try this a couple of times)

```
// tests the v2 version of the AWS SDK

import software.amazon.awssdk.services.s3.S3AsyncClient
import software.amazon.awssdk.services.s3.model._
import software.amazon.awssdk.core.async._
import scala.compat.java8.FutureConverters._
import java.util.concurrent.atomic.AtomicLong
import java.nio.ByteBuffer
import org.reactivestreams.{ Subscription, Subscriber }
import akka.actor.{Actor, ActorLogging, Props, ActorSystem}


object TestS3Actor {
  val props = Props[TestS3Actor]
}

class TestS3Actor extends Actor with ActorLogging {
  val lc = S3AsyncClient.create()
  val b  = "YOUR_S3_BUKCET"
  
  def receive = {
    case obj: Int =>       
      if (obj % 100 == 0 ) println(obj)
      val p = PutObjectRequest.builder().bucket(b).key("test-Obj" + obj.toString()).build()
      lc.putObject(p,  new MyPublisher(100019) ).toScala
      ()
  }
}


object Hello extends App {
  val myActor = ActorSystem("mySystem").actorOf(TestS3Actor.props)
  for { i <- 1 to 200 }  myActor ! i
}

// Used to generate an infinite stream if required
class MyPublisher(streamSz: Long) extends AsyncRequestProvider {
    
  def contentLength: Long = streamSz
  def subscribe(s: Subscriber[_ >: ByteBuffer]): Unit = {
    s.onSubscribe(new MySubscription(s, streamSz)) 
  }

  object MySubscription {
    val SIZE: Int = 1024;
    val initBuf: Array[Byte] = (for (i <- 0 to (SIZE - 1)) yield 'b'.toByte).toArray
  }

  class MySubscription(s: Subscriber[_ >: ByteBuffer], sz: Long) extends Subscription {

    var currPos: Long = 0
    val localBuf = ByteBuffer.allocate(sz.toInt) 
    var complete = false

    def cancel = {}
    def request(b: Long) = {
      this.synchronized { readData(b) }
    }
    
  def readData(d: Long) : Unit = if (currPos != sz) {

        val c = localBuf.capacity()
        val r = if ((sz - currPos) < c) (sz - currPos).toInt else c

        localBuf.position(0)
        localBuf.limit(r)
        currPos += r

        s.onNext(localBuf)

        if (d > 1) readData(d-1)
      } else {
        if (complete == false) {
          s.onComplete()
          complete = true
        }
      }
  }
}

```

**Comment by raboof** [comment]
Thanks for reporting this issue and providing a reproducer!

One thing that stands out is that you're implementing `org.reactivestreams.Subscription` directly, this is not recommended as it's nontrivial to implement the associated [requirements](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#3-subscription-code) - it might be better to use Akka Streams. You mentioned you used Akka Streams before and could reproduce the problem predictably when you were using Akka Streams, do you by any chance have that reproducer available somewhere as well?

**Comment by raboof** [comment]
On a related note, have you seen the S3 connector in Alpakka (https://developer.lightbend.com/docs/alpakka/current/s3.html)?

**Comment by raboof** [comment]
Boiling this example down to:
```
  val system = ActorSystem("mySystem")
  for { obj ← 1 to 200 } {
    if (obj % 100 == 0) println(obj)
    val p = PutObjectRequest.builder().bucket(b).key("test-Obj" + obj.toString()).build()
    val response = lc.putObject(p, AsyncRequestProvider.fromString("B" * 10000)).toScala
    implicit val ec = system.dispatcher
    response.onComplete {
      case Success(_) ⇒ //OK
      case Failure(f) ⇒ system.log.error(f, "NOK")
    }
  }
```
I still got this error:
```
akka-stream [ERROR] [01/31/2018 14:59:58.055] [mySystem-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(mySystem)] NOK
akka-stream java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: java.util.NoSuchElementE
xception: HttpStreamsClientHandler#0-body-publisher
akka-stream 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
akka-stream 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
akka-stream 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
akka-stream 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
akka-stream 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
akka-stream 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handle(AsyncRetryableStage.java:13
0)
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableSta
ge.java:111)
akka-stream 	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
akka-stream 	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
akka-stream 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
akka-stream 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.exceptionOccurred(MakeAsyn
cHttpRequestStage.java:172)
akka-stream 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.lambda$exceptionCaught$0(ResponseHandler.java:118)
akka-stream 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:154)
akka-stream 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.exceptionCaught(ResponseHandler.java:116)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
akka-stream 	at com.typesafe.netty.HandlerSubscriber.exceptionCaught(HandlerSubscriber.java:157)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
akka-stream 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHa
ndler.java:438)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
akka-stream 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
akka-stream 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
akka-stream 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
akka-stream 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
akka-stream 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
akka-stream 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
akka-stream 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
akka-stream 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
akka-stream 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
akka-stream 	at java.lang.Thread.run(Thread.java:748)
akka-stream Caused by: software.amazon.awssdk.core.exception.SdkClientException: java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handle(AsyncRetryableStage.java:125)
akka-stream 	... 53 more
akka-stream Caused by: java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher
akka-stream 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1089)
akka-stream 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:443)
akka-stream 	at com.typesafe.netty.http.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:328)
akka-stream 	at com.typesafe.netty.http.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:189)
akka-stream 	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:165)
akka-stream 	at com.typesafe.netty.http.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:148)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	... 33 more
```

while there is some `com.typesafe.netty` in that trace, to me it starts to look like this might have nothing to do with Akka, right?

**Comment by vardhanv** [comment]
I filed an issue with the AWS SDK folks (below), but I think that issue is invalid - taking Akka out of the picture results in a clean run. 
I have not been able to reproduce this without Akka. Will try again. 
Many concurrent async requests cause "NoSuchElementException: HttpStreamClientHandler#0-body-publisher" · Issue #202 · aws/aws-sdk-java-v2 

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Many concurrent async requests cause "NoSuchElementException: HttpStreamClientHandler#0-body-publisher" · Issue #202 · aws/aws-sdk-java-v2
 
I'm creating many short-lived requests concurrently using the *AsyncClient, and this fails with: java.util.concurrent.CompletionException: java.util.NoSuchElementException: HttpStreamsClientHandler...
  |   |

  |

  |

 



Sent from Yahoo Mail for iPhone


On Wednesday, January 31, 2018, 6:04 AM, Arnout Engelen <notifications@github.com> wrote:


Boiling this example down to:
  val system = ActorSystem("mySystem")
  for { obj ← 1 to 200 } {
    if (obj % 100 == 0) println(obj)
    val p = PutObjectRequest.builder().bucket(b).key("test-Obj" + obj.toString()).build()
    val response = lc.putObject(p, AsyncRequestProvider.fromString("B" * 10000)).toScala
    implicit val ec = system.dispatcher
    response.onComplete {
      case Success(_) ⇒ //OK
      case Failure(f) ⇒ system.log.error(f, "NOK")
    }
  }

I still got this error:
akka-stream [ERROR] [01/31/2018 14:59:58.055] [mySystem-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(mySystem)] NOK
akka-stream java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: java.util.NoSuchElementE
xception: HttpStreamsClientHandler#0-body-publisher
akka-stream 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
akka-stream 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
akka-stream 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
akka-stream 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
akka-stream 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
akka-stream 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handle(AsyncRetryableStage.java:13
0)
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableSta
ge.java:111)
akka-stream 	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
akka-stream 	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
akka-stream 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
akka-stream 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.exceptionOccurred(MakeAsyn
cHttpRequestStage.java:172)
akka-stream 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.lambda$exceptionCaught$0(ResponseHandler.java:118)
akka-stream 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:154)
akka-stream 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.exceptionCaught(ResponseHandler.java:116)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
akka-stream 	at com.typesafe.netty.HandlerSubscriber.exceptionCaught(HandlerSubscriber.java:157)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
akka-stream 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHa
ndler.java:438)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
akka-stream 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
akka-stream 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
akka-stream 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
akka-stream 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
akka-stream 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
akka-stream 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
akka-stream 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
akka-stream 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
akka-stream 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
akka-stream 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
akka-stream 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
akka-stream 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
akka-stream 	at java.lang.Thread.run(Thread.java:748)
akka-stream Caused by: software.amazon.awssdk.core.exception.SdkClientException: java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher
akka-stream 	at software.amazon.awssdk.core.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handle(AsyncRetryableStage.java:125)
akka-stream 	... 53 more
akka-stream Caused by: java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher
akka-stream 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1089)
akka-stream 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:443)
akka-stream 	at com.typesafe.netty.http.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:328)
akka-stream 	at com.typesafe.netty.http.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:189)
akka-stream 	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:165)
akka-stream 	at com.typesafe.netty.http.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:148)
akka-stream 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
akka-stream 	... 33 more

while there is some com.typesafe.netty in that trace, to me it starts to look like this might have nothing to do with Akka, right?

**Comment by raboof** [comment]
I could reproduce it with https://github.com/raboof/awssdk-async, no Akka at all there.. so closing the issue here, but it still thanks for finding it, I hope we'll be able to get to the bottom of it and fix it in the right place ;)
