### ISSUE TITLE
handle exceptions from messageAdapter and ask adapter

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24456]
Currently an exception from the adapter function is thrown out to the ActorAdapter before involving the Behavior. That means stopping. I think it's confusing that the Behavior's supervision strategy is not used for this case. It would be difficult to involve the Behavior, since this happens before.

I suggest that we catch, log and resume for such exceptions. One can think of the adapter as happening before receiving the actual message. One would have to do something terribly bad in the adapter function to corrupt the actor state so resume should be alright.

**Comment by jrudolph** [comment]
> One would have to do something terribly bad in the adapter function to corrupt the actor state so resume should be alright.

I agree it's unlikely that you corrupt the actor state. But can we really make this assumption? If we forbid side-effects from the adapter function, than we should maybe also forbid throwing out of them and stopping is the right behavior after all?

> It would be difficult to involve the Behavior, since this happens before.

To clarify, typed supervision is defined as a wrapping Behavior while message adapters are instead a feature of the ActorAdapter. So, message adapter code is run outside of supervision. One way I could imagine to circumvent this is by creating a `DeferredMessage(() => T)` and interpreting this in `Behavior.interpret` to make this code execute in the right context as well.

**Comment by jrudolph** [comment]
I'll have a try at this because I think using the supervisor would be the more consistent and safer behavior in general.

**Comment by patriknw** [comment]
good idea

**Comment by jrudolph** [comment]
> One way I could imagine to circumvent this is by creating a DeferredMessage(() => T) and interpreting this in Behavior.interpret to make this code execute in the right context as well.

I tried that in #24462 however it cannot be interpreted inside of `Behavior.interpret` but it must be signal instead that has to be supported by all `ExtensibleBehavior`s. At least all leaf behaviors that don't delegate to another one. Not sure if that's really worth the effort.

I still think that stopping the actor in cases like this is the safer behavior so I'd suggest to maybe document the behavior but don't change the current behavior.
