### ISSUE TITLE
Support ShardRegionQuery in Typed 

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24466]
To retrieve the various stats.

Do we also need GracefulShutdown message, or only rely on coordinated shutdown?

The ClusterSharding extension can expose more typed `ActorRef` for these additional messages that are not part of the entities protocol.

**Comment by ralphlaude** [comment]
Hey, i would like to work on this issue. First of all i like to understand the context. Thanks for an answer

**Comment by patriknw** [comment]
@ralphlaude That would be great. See https://doc.akka.io/docs/akka/current/cluster-sharding.html?language=scala#inspecting-cluster-sharding-state for info about the corresponding queries (messages) in untyped Sharding. Corresponding should be exposed as typed ActorRef in the typed ClusterSharding.

**Comment by ralphlaude** [comment]
@patriknw thanks for the hints. I will read and do it.

**Comment by ralphlaude** [comment]
@patriknw i have red the doc but i still don't understand the context very well. I look in the classes ```akka.cluster.sharding.ClusterSharding```, ```akka.cluster.sharding.Shard```, ```akka.cluster.sharding.Shard.SharQuery```and ```akka.cluster.sharding.ShardCoordinator```.  Please i need more explanation. thanks

**Comment by patriknw** [comment]
@johanandren can you assist here, next week

**Comment by chbatey** [comment]
Hi @ralphlaude if you still want to work on this i've started it in PR https://github.com/akka/akka/pull/25409 to give you an idea of how to do it. 

For Typed Cluster we add new APIs via exposing a Typed Actor user code can interact with. I've done one query and the other to do is `GetClusterShardingStats`.

If you work on this before my PR is merged you can branch of that to get going. 

Any questions let me know.

**Comment by ralphlaude** [comment]
Hi @chbatey,
yes, i still want to work on this issue.

Thanks for your PR, now i have an idea of what should be done. I will get into this with the only query ```GetClusterShardingStats```.

I don't understand very well the point concerning the merging of your PR. But i will wait until your PR is merged and the start from there. Is that ok?

**Comment by ralphlaude** [comment]
Hi @chbatey, something new here?

**Comment by patriknw** [comment]
What is the status and next step here? Started in https://github.com/akka/akka/pull/25409

**Comment by chbatey** [comment]
Hey @ralphlaude sorry for the delay. The PR is merged for one of the queries, do you want to do the other one?
