### ISSUE TITLE
missing serializer for GetShardRegionStats

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24465]
When using `ClusterShardingStats` the coordinator sends `GetShardRegionStats` to the remote regions. It's currently falling back to java serialization.

**Comment by barcahead** [comment]
Hi @patriknw, I want to work on this one.

**Comment by patriknw** [comment]
Excellent, thanks

**Comment by Captain1653** [comment]
There is a similar issue https://github.com/akka/akka/issues/25348 . That issue is closed.

Is this issue a duplicate? Should it be closed?
