### ISSUE TITLE
Rethink how to handle persist failures in Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24479]
In untyped we unconditionally stop on persist failures, because we can't know if the event was persisted or not so there must be a new recovery. resume would be wrong. restart would typically result in restart loop. Intended to be used with backoff supervision.

In Typed we have restart with backoff so perhaps we should rethink the stopping for Typed. Perhaps we can always add a restart with backoff around PersistentBehavior that handles the persist failure exceptions.

**Comment by chbatey** [comment]
I think we should at least have it throw rather than stop then users can add their own. Otherwise we'd need to make it configurable/overridable.
