### ISSUE TITLE
Support Passivate in Typed Sharding

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24478]
Parent is unknown, so I think we must add it in the `ClusterSharding` extension by exposing another `ActorRef[Passivate]` that then entities can use.

**Comment by Horusiath** [comment]
Maybe this could be implemented as a Behavior? Just like we have `Actor.stopped` to stop an actor, use something like `Entity.passivate` to start passivation process?

**Comment by patriknw** [comment]
We discussed solutions for this and the conclusion was that we would add another parameter to the behavior factory:

```
  trait ShardCommand
  case object Passivate extends ShardCommand

behavior:           (ActorRef[ShardCommand], String) ⇒ Behavior[A],
```

When sending `Passivate` to that `ActorRef` the message would be converted into the untyped Passivate message and sent to the Shard (parent) with the `handOffStopMessage` as the stop message.

**Comment by patriknw** [comment]
We should probably not release this without the other changes to the sharding API, to avoid breaking API more times than necessary. https://github.com/akka/akka/pull/25539
