### ISSUE TITLE
Add support for `def` in LineNumbers

### ISSUE THREAD

**Issue by jlprat** [akka/akka#24480]
Currently LineNumbers utility works only in the case lambda's are defined in `val`s.
It would be beneficial to be able to trace down line numbers for lambda's defined behind a `def`.

**Comment by ktoso** [comment]
Yes very nice idea and simple to add as well. Will think about implications

-- 
Konrad Malawski

**Comment by jlprat** [comment]
I have a PR with a naive approach. Pushing it in a second
