### ISSUE TITLE
Doc Typed Serialization Java example

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24493]
in typed/cluster.md the Java example of serialization is missing

**Comment by richardimaoka** [comment]
will have a look

**Comment by patriknw** [comment]
@richardimaoka what is the status here, are you working on this?

**Comment by patriknw** [comment]
no worries, I was just currious if we should put it back in the queue

**Comment by richardimaoka** [comment]
Well, I realized it's already done but I linked a wrong issue from the PR that's why this issue was not closed. It's ok to close the issue now.

**Comment by raboof** [comment]
:+1: thanks!

**Comment by patriknw** [comment]
thanks
