### ISSUE TITLE
Refactoring of Typed ActorContextSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24490]
Split up in smaller tests.

Write as a test that is easier to understand, without using StepWise.

**Comment by kelebra** [comment]
Do you mind if I take care of this issue?

**Comment by ktoso** [comment]
Please, thanks a ton!

**Comment by patriknw** [comment]
Great, I guess it will also be a good exercise of what is missing in current testkit.

**Comment by ktoso** [comment]
Solved, thanks @kelebra !
