### ISSUE TITLE
Failed: whitesourceUpdate

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#24499]
https://jenkins.akka.io:8498/job/akka-nightly/5198/console

```
[error] sbtwhitesource.WhiteSourceException: Error communicating with service: Unexpected error. Response data is: Gateway Time-out
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5196/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5197/console

**Comment by raboof** [comment]
I wonder if we should ignore these kinds of failures... so fail when whitesource encounters a configuration error or forbidden dependency, but not when it fails due to an 'intermittent' failure. WDYT?

**Comment by jrudolph** [comment]
I guess for the nightlies that would make a lot of sense.

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5220/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5226/console

**Comment by 2m** [comment]
Validation of https://github.com/akka/akka/pull/24573 failed with `[error] sbtwhitesource.WhiteSourceException: Error communicating with service: Unexpected error. Response data is: Gateway Time-out`

**Comment by jrudolph** [comment]
akka-http travis build hanging for >10 minutes: https://travis-ci.org/akka/akka-http/builds/343821793?utm_source=github_status&utm_medium=notification

**Comment by johanandren** [comment]
Hasn't happened for a long while. Let's close this.
