### ISSUE TITLE
release for Scala 2.13.0-M3?

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#24507]
akka-actor, at least, if a full release is problematic for whatever reason?

**Comment by raboof** [comment]
depends on https://github.com/scala/scala-java8-compat/issues/98

unfortunately because we don't have #23755 yet our release process currently includes some manual steps and adding 2.13.0-M3 will make that a little worse..

**Comment by patriknw** [comment]
we also need to publish com.typesafe#ssl-config-core_2.13.0-M3;0.2.2

**Comment by SethTisue** [comment]
ssl-config-core and scala-java8-compat are published now, so this might be ready for action again...?

**Comment by ktoso** [comment]
Did you try this @2m? I saw some ticket. Please keep me in the loop if yes, so I don't duplicate work tomorrow

**Comment by 2m** [comment]
I think you saw this: https://github.com/akka/akka/issues/24535

I was just asking @SethTisue whether that is a regression in Scala, or should we refactor and get rid of eta expansion there.

**Comment by 2m** [comment]
Note that there is one more problem while building akka-actor with 2.13: https://github.com/scala/scala-dev/issues/467

**Comment by SethTisue** [comment]
#24535 is a regression in Scala (I commented there), but it's easy to work around temporarily until the fix lands in 2.13.0-M4

**Comment by SethTisue** [comment]
if scala/scala-dev#467 is a roadblock, feel free to bug Miles about it

**Comment by 2m** [comment]
@SethTisue here is a branch fresh of the master that compiles with 2.13.0-M3: https://github.com/akka/akka/tree/wip-scala-2.13-2m

You could use this in the community build. :)
