### ISSUE TITLE
FAILED: release-2.4 branch does not manage to finish in 150 minutes any more

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#24504]
Most builds fail by now: https://jenkins.akka.io:8498/job/akka-release-2.4/

It seems this nightly hasn't worked reliably for quite a while.

Potential actions:

 * increase timeout for now
 * find out the reason for the slowdown between run 435 and 436 which increased running time from ~ 1:45 to ~ 2:30

**Comment by jrudolph** [comment]
Increased the timeout to 180 minutes for now.

**Comment by patriknw** [comment]
That's insane. Last commit to release-2.4 branch was Nov 15. The master branch also increased at about the same time.

**Comment by jrudolph** [comment]
It seems the ssh issues of multi-jvm tests are a major factor in adding time to builds.

**Comment by patriknw** [comment]
Yup, let’s get on top of that problem. Feel free to merge your PR adding more diagnostics.

**Comment by 2m** [comment]
This is a fallback from the workaround of the issue where I and @cunei were working on diagnosing.

The problem is an intermittent authentication issue where a node cannot successfully connect to a5 or a6 using public key authentication at the beginning of the multi-node test. The workaround is to try again with a backoff which increases the total job times.

**Comment by 2m** [comment]
a5 and a6 now have an `akka` user with a non-nfs mounted homedir. I reconfigured multi-node tests to use this user and removed the retry ssh script.

**Comment by patriknw** [comment]
@2m Thanks. What was the reconfiguration for multi-node tests, so that we all know for setting up other jenkins jobs?

**Comment by 2m** [comment]
Added `akka@` to the hosts listed in the `multi-node-test.hosts` file. And changed `-Dakka.test.multi-node.targetDirName=` to `/localhome/akka/<job_name>`.

We should also start using https://wiki.jenkins.io/display/JENKINS/SCM+Sync+configuration+plugin to track Jenkins configuration in a more principled manner.

**Comment by jrudolph** [comment]
> We should also start using https://wiki.jenkins.io/display/JENKINS/SCM+Sync+configuration+plugin to track Jenkins configuration in a more principled manner.

That would be good. I'm tracking it in a semi-manual way rsync'ing the config files before I do (major) changes and committing them to a local repo but automatic would be better.
