### ISSUE TITLE
[Akka-Streams] Want to always receive latest element in Sink

### ISSUE THREAD

**Issue by skvithalani** [akka/akka#24509]
Hello,

We are having a requirement that if a consumer is slower than producer then discard all the elements that cannot be consumed and whenever the consumer gets ready, feed the latest element from producer.

We tried an approach as follows:

```
Source.actorRef(0, OverflowStrategy.dropHead)       // actor receives data at every 10 milliseconds
.runWith {
   println("data received")
   Thread.sleep(1000)               // mimic consumer processing data in every 1 second
}
```

We shrank the buffer size to 1 (minimal possible) with following settings

`private val actorMaterializerSettings = ActorMaterializerSettings(actorSystem).withInputBuffer(1, 1)`

With this buffer size, Sink pulls data 1 to consume and data 2 to put in buffer at initialization.

While data 1 is getting processed we are dropping data from producer.

When data 1 gets processed after 1000 milliseconds (1 second) ideally we should receive data 10 (and drop 2 - 9 as consumer is slow) but instead we receive data 2 from the buffer. data 2 in our domain is extremely useless as it is stale.

So, it seems that we might end up having our own Sink stage that keeps draining all data until the processing is going on and once the processing is done it picks the latest received data and starts the processing again.

So, is this the correct way to approach the problem ? And if yes, should a Sink like latest be provided by default with Akka streams library?

**Comment by johanandren** [comment]
Hi @skvithalani we try to use the issue tracker only for issues and feature-tracking, please use the [mailing list](https://groups.google.com/forum/#!forum/akka-user) or the [gitter channel](https://gitter.im/akka/akka) for questions like this, thanks!

You should be able to do this using something `expand(elem => Iterator.repeat(elect))`, also note, that you should never ever do `Thread.sleep` in a lambda passed to streams as they are fused (potentially into a single actor) and this may stop processing of any element in the entire stream, in addition to starving the default dispatcher.
