### ISSUE TITLE
akka-stream `FileIO.fromPath` API change for file not found

### ISSUE THREAD

**Issue by ANorwell** [akka/akka#24512]
The `FileIO.fromPath` method, for files that do not exist, has started returning (and logging at ERROR level)  an `IllegalArgumentException`, instead of the `NoSuchFileException` that used to be returned. I think this changed between 2.5.1 and 2.5.8.

Is this intentional? This is a very scary looking error for something that is often not an error condition, and the lack of a special error makes it harder to handle this condition.

```
java.lang.IllegalArgumentException: requirement failed: Path <path>
  at scala.Predef$.require(Predef.scala:224)
  at akka.stream.impl.io.FileSource$$anon$1.preStart(IOSources.scala:73)
  at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:293)
```

**Comment by patriknw** [comment]
It was probably changed in the rewrite to use NIO in #21732
Would you be interested in creating a PR to bring back the previous behavior?

**Comment by ANorwell** [comment]
I can look but no guarantees. I see this changed in 2.5.5 when `FilePublisher` was removed. The new implementation does this explicitly:


```
          // this is a bit weird but required to keep existing semantics
          require(Files.exists(path), s"Path '$path' does not exist")
          require(Files.isRegularFile(path), s"Path '$path' is not a regular file")
          require(Files.isReadable(path), s"Missing read permission for '$path'")
```

but it's not clear why -- I don't think this is keeping the existing semantics.

**Comment by ANorwell** [comment]
It's not clear to me that these `require`s are a good idea at all. They probably impact performance for small files since they would generate extra syscalls. I'm inclined to think they should just be removed.

@agolubev @raboof any insight, since I see you participated in https://github.com/akka/akka/pull/21801?
