### ISSUE TITLE
Using typed `ask` with Receptionist is too verbose

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24511]
This is way to verbose, as the inference does not seem to work and I had to type the `[]` types:`ctx.ask[Receptionist.Subscribe[AlarmMessage], Receptionist.Listing[AlarmMessage]](receptionist)(repl ⇒ Receptionist.Subscribe(alarmKey, repl))(res ⇒ AlarmListing(res.get.serviceInstances))`

How can we improve this?

**Comment by johanandren** [comment]
#24492 is somewhat related

**Comment by johanandren** [comment]
Note that `ask(subscribe)` doesn't really make sense, as subscribe is one req to many responses (so that case could perhaps be a case of bad sample code I dumped in your lap)
