### ISSUE TITLE
add lazilyAsync?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24519]
I want this because I need something like 
```
Source.fromSupplier(() -> callServiceReturnCompletionStage())
.flatmap(Source::fromCompletionStage)`
....
```
I have to call 
```
Source.lazily(() -> Source.fromCompletionStage( callServiceReturnCompletionStage())
```

currently

**Comment by ktoso** [comment]
I'd be ok with adding lazilyAsync (please stick to established names, from supplier does not fit existing naming). Main reason being that all those combinations of "i want a source from [weird situation description]" are a stopper for people adopting streams and learning about them for the first time, so I agree with having more than the bare minimum of overloads for such things

**Comment by johanandren** [comment]
I'm on the fence, the current way to do it doesn't look _that_ bad to me, so it would be about discoverability for newcomers as Konrad pointed out.

**Comment by ktoso** [comment]
I triaged it, would be a nice PR

**Comment by kelebra** [comment]
Do you guys mind if I prepare PR for this?

**Comment by ktoso** [comment]
Sure, that'd be nice! Make sure to cover javadsl as well as add it to the docs places :)

**Comment by ktoso** [comment]
Nice little operator, thanks for it

**Comment by hepin1989** [comment]
Finally I miss this operator again:) thank you @kelebra .
