### ISSUE TITLE
[PersistentFSM] andThen() documentation

### ISSUE THREAD

**Issue by synox** [akka/akka#24532]
As a user I expect andThen to ADD a side effect, instead of replacing the previous side effect. Just like scala.concurrent.Future#andThen. 

The Docs should specify that andThen() replaces the previous side effect. Or better, they should be run in the defined order. 

    /**
     * Register a handler to be triggered after the state has been persisted successfully
     */
    def andThen(handler: D ⇒ Unit): State[S, D, E] = {
      copy(afterTransitionDo = handler)
    }
(https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/fsm/PersistentFSM.scala#L399)

**Comment by ktoso** [comment]
Thanks for reporting, I think PersistentFSM is on it's way to deprecation I think.

The bahaviour you describe is currently implemented in typed persistence though, so that's good -- and totally agreed on the behaviour.
