### ISSUE TITLE
2.13 compile errors (eta-expansion related?)

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#24535]
the Scala 2.13 community build already includes the akka-actor module. I would like to re-add the rest of Akka. but I'm getting these compile errors:

```
[akka-more] [error] /Users/tisue/community.213/target-0.9.10/project-builds/akka-more-ef1713dfa7b54aee62ec26b3dfe5c4c5b475534e/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala:808:46: type mismatch;
[akka-more] [error]  found   : Unit
[akka-more] [error]  required: () => ?
[akka-more] [error]     emitMultiple(out, elems.asScala, andThen.apply _)
[akka-more] [error]                                              ^
[akka-more] [error] /Users/tisue/community.213/target-0.9.10/project-builds/akka-more-ef1713dfa7b54aee62ec26b3dfe5c4c5b475534e/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala:862:29: type mismatch;
[akka-more] [error]  found   : Unit
[akka-more] [error]  required: () => ?
[akka-more] [error]     emit(out, elem, andThen.apply _)
[akka-more] [error]                             ^
```

in order for you to reproduce this outside of dbuild, a possible prerequisite is https://github.com/lightbend/ssl-config/issues/73

**Comment by ktoso** [comment]
Thanks, fill fix!

**Comment by ktoso** [comment]
We only need the compat lib now

**Comment by 2m** [comment]
For the record, in the error log `andThen` has type [`Effect`](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/japi/function/Function.scala#L41).

We can replace `andThen.apply _` to  `() => andThen.apply())`, but shouldn't this be registered as a regression in scala instead?

**Comment by SethTisue** [comment]
yes, it is a regression in Scala, actually. https://github.com/scala/scala/pull/6177 will fix it for 2.13.0-M4

**Comment by patriknw** [comment]
@2m are we working on this or just waiting for next milestone?

**Comment by 2m** [comment]
Changes needed to release for 2.13.0-M3 are in https://github.com/akka/akka/commits/wip-scala-2.13-2m

When 2.13.0-M4 is out some of these will be not relevant anymore. But we will also have to do more changes due to new collections. Therefore, I say lets wait for the next milestone release.

**Comment by patriknw** [comment]
got it, thanks

**Comment by chbatey** [comment]
Also M4 is out with the new collections and @ennru did some work here: https://github.com/ennru/akka/tree/newCollections

**Comment by SethTisue** [comment]
closing this one since there's also #25105 and #25267
