### ISSUE TITLE
affinity-pool-executor gives threads less descriptive names than other executors

### ISSUE THREAD

**Issue by RafalSumislawski** [akka/akka#24544]
fork-join-executor and thread-pool-executor follow a common convention of naming threads with `<actorSystemName>-<dispatcherName>-<threadCounter>`. affinity-pool-executor uses `<actorSystemName>-<threadCounter>`. This is confusing. Especially if more than one dispatcher uses affinity-pool-executor.

The names of the threads are configured in `ForkJoinExecutorConfigurator.createExecutorServiceFactory`, and `ThreadPoolConfig.createExecutorServiceFactory`. Adding similar code to `AffinityPoolConfigurator.createExecutorServiceFactory` could solve this issue.

I can provide a PR for this.

**Comment by johanandren** [comment]
Sounds good, please PR
