### ISSUE TITLE
Include stack trace when Java unit tests fail in sbt

### ISSUE THREAD

**Issue by raboof** [akka/akka#24546]
When running Java testkit tests under sbt, test failures do not appear to contain the stack trace leading up to the error (tested with the akka-sample-supervision-java sample).

It would be very useful if we could somehow make the stack trace visible there.

**Comment by johanandren** [comment]
Maybe also input to the issue @chbatey is looking into: #24540  (If the junit reporter does this better)

**Comment by jrudolph** [comment]
Ping @chbatey, do you know if using the junit test reported fixed this?

**Comment by renatocaval** [comment]
I did a quick test using the akka-quick-start template and the tests are not run, at all. 

They run if they implement `org.scalatestplus.junit.JUnitSuite`. I guess this is more an issue of sbt and junit integration. 


I will check further with all existing samples.
Please, let me know if there are other places were this was observed (akka-sample-supervision-java doesn't exist anymore).

**Comment by patriknw** [comment]
Java examples are typically targeting maven.

**Comment by renatocaval** [comment]
> Java examples are typically targeting maven. I mean, stanalone samples outside akka/akka

Yes, but they also have a sbt build. 

I will first check any junit test inside Akka and make sure they run correctly. We can then see which samples are having the same issue.

**Comment by renatocaval** [comment]
We decided to remove the sbt builds from java samples to decrease the maintenance cost (see https://github.com/akka/akka-samples/pull/210). 

We only kept it when we have multi-jvm test. All projects using multi-jvm test do not have junit tests. They do have a pom, but the tests are alas not run from mvn.

**Comment by raboof** [comment]
:+1:
