### ISSUE TITLE
Remove the dependency on ssl-config-akka (the cyclic one)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24543]
We should remove the dependency on ssl-config-akka, the cyclic thing is silly and I'm sorry for having created it :P 

The dependency is likely not REALLY needed, and we could even get rid of it in 2.5 perhaps, but 2.6 sounds more sane? Not sure on opinions here.

**Comment by jrudolph** [comment]
ssl-config-akka is gone for a long while. We solved it back then by including the sources of it completely in akka-stream. The remaining work is already described in #21753.
