### ISSUE TITLE
stashed timer messages are discarded

### ISSUE THREAD

**Issue by 412b** [akka/akka#24557]
I've recently bumped into a case that messages scheduled with timer and stashed via `stash()` will be discarded. It comes into play with any class that has `StashSupport` in the traits.
What happens is:
1. `Timers.aroundReceive` calls `super.aroundReceive` [here](https://github.com/akka/akka/blob/14bb878da17231bf0713bd636d2bc64aa0f04641/akka-actor/src/main/scala/akka/actor/Timers.scala#L40) with *unwrapped* message.
2. In case of a call to `stash`, the message is taken [here](https://github.com/akka/akka/blob/14bb878da17231bf0713bd636d2bc64aa0f04641/akka-actor/src/main/scala/akka/actor/Stash.scala#L157) and it's `actorCell.currentMessage`, so it's efficiently `Envelope` with `message` set to `TimerSchedulerImpl.TimerMsg` being stashed.
3. When unstashed the message gets discarded as it was already processed by `Timers`.

imho, supersedes #24076, because of being a more generic `Timers` and `StashSupport` problem.
somewhat related to #24080 as well.

**Comment by antoon-r** [comment]
Was it really fixed in 2.5.10?

It is still reproducible with com.typesafe.akka:akka-actor_2.12:2.5.14

Try yourself: https://gist.github.com/antoon-r/eae5c69715f49254dfbebcff23307577

**Comment by johanandren** [comment]
We have test coverage for this issue (https://github.com/akka/akka/blob/2b6997b7a04d1c085b0c6d0741e555c6fb28df04/akka-actor-tests/src/test/scala/akka/actor/TimerSpec.scala#L318) so pretty sure it was fixed. That's when doing a regular `Actor` and mixing in timer and stash though. 

I wonder if what you are seeing isn't a separate issue with the timers and or stashing in FSM (could you please open up a separate issue for it if so?)
