### ISSUE TITLE
intermittent test failure in MinMembersBeforeUpMultiJvmNode1

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#24566]
seen in the Scala 2.12 community build at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2616/consoleFull

```
[akka-more] [JVM-1] - must wait with moving members to UP until minimum number of members have joined (on node 'first', class akka.cluster.MinMembersBeforeUpMultiJvmNode1) *** FAILED *** (5 seconds, 4 milliseconds)
[akka-more] [JVM-1]   Removed did not equal Joining (MinMembersBeforeUpSpec.scala:125)
[akka-more] [JVM-1]   org.scalatest.exceptions.TestFailedException:
[akka-more] [JVM-1]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[akka-more] [JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6804)
[akka-more] [JVM-1]   at akka.cluster.MinMembersBeforeUpBase.$anonfun$testWaitMovingMembersToUp$3(MinMembersBeforeUpSpec.scala:125)
```

I don't recall having seen this failure before

**Comment by ktoso** [comment]
MultiJvm tests could be pretty prone to timing issues.
I'll give it a look but for those perhaps it'd be good to exclude from dbuild?

cc @patriknw

**Comment by SethTisue** [comment]
> MultiJvm tests could be pretty prone to timing issues.
> perhaps it'd be good to exclude from dbuild

I can disable running tests (we can compile them but not run them) on a per-subproject basis.

I've been kinda interested in doing that anyway, actually, because running everything takes so long, considerably longer than any other project in the community build. (recurring thought: maybe Lightbend should have its own dbuild-based Akka/Play/Lagom centric über-build)

does this look like the right list of projects to disable test runs in? akka-cluster, akka-cluster-metrics, akka-cluster-sharding, akka-cluster-tools, akka-distributed-data. I'd also be open to starting with a shorter list and expanding if it proves needed.

**Comment by johanandren** [comment]
`akka-remote-tests` also contains multi-jvm tests.

**Comment by johanandren** [comment]
Btw I think you can disable just the multi-node tests by setting the sys prop `akka.test.multi-in-test` to  `false`

**Comment by patriknw** [comment]
@SethTisue I'd recommend to start with the same subset that we use in PR validation: `-Dakka.test.tags.exclude=performance,timing,long-running -Dakka.test.multi-in-test=false`

**Comment by SethTisue** [comment]
nice, glad I asked! I'll try it.

**Comment by SethTisue** [comment]
good so far in the community build. up to y'all whether to leave this open or not.

**Comment by ktoso** [comment]
Naisu, closing 👍
