### ISSUE TITLE
Directives style, extensive docs for all operators AND stages

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24572]
We have our "stages overview" page https://doc.akka.io/docs/akka/current/stream/stages-overview.html#queue but it's not easy to navigate and has no examples: 
![overview_of_built-in_stages_and_their_semantics_ _akka_documentation](https://user-images.githubusercontent.com/120979/36417232-ae900d18-166e-11e8-89ba-c76363fbfa13.png)

In similar style to: https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/alphabetically.html
and the directive page:

![extracthost_ _akka_http](https://user-images.githubusercontent.com/120979/36417695-f37c0034-166f-11e8-8b9a-d229a70112fe.png)

We should do such same pages for all our stages and operators. 

If a new operator is added to Flow/Source/Sink etc, tests should check that a file exists with docs for them, this makes it easier for contributors to realise they may need to add such doc.

----

Steps:

- [x] move all stages-overview docs onto separate pages for each stage
- [x] add a test similar to DslConsistencySpec that checks that all stages / operators have docs
- [ ] add examples to each of them (they have already in tests most likely, reuse them) https://github.com/akka/akka/issues/24933
- [ ] add diagrams showing how operators work (optional, but very nice)  https://github.com/akka/akka/issues/24933

**Comment by patriknw** [comment]
cc @agemooij @RayRoestenburg one idea related to our discussion the other day

**Comment by agemooij** [comment]
:+1: That is exactly what I would love to see.

I'd like to add that it will be important to try to make the examples as meaningful and "real world" as possible and that some more complex operators will require multiple examples. 

For instance: in the past I've seen some very contrived examples for using something more complex like `statefulMapConcat` or even `groupBy`, which can be a powerful tool but only if you really have a good example that makes sense to actual users. 

Sometimes it is also very helpful to show how the output of an operator can be further processed. For instance I think  that many beginning users (me included) will have a problem conceptualizing how to deal with the output of `groupBy`, e.g. what code would look like that would do something useful with sub flows, `mergeBack`, etc.

**Comment by ktoso** [comment]
Let's start small, I of course understand your question, but first we need to start things off.

**Comment by ktoso** [comment]
Step 1 and 2 will be completed by https://github.com/akka/akka/issues/23748 👍 
Then we will ask the community to help with examples and diagrams in: https://github.com/akka/akka/issues/24933

**Comment by raboof** [comment]
Should we perhaps close this one since the remaining tasks are in separate issues (#24933, #25466, #25467, #25468)? Not sure if there's value in this 'parent' issue anymore.

**Comment by ktoso** [comment]
Yes, okey

**Comment by ktoso** [comment]
The initial task I would argue is done even, since we have the structure in place now
