### ISSUE TITLE
The Source.actorRef docs on stream-integrations need an example

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24595]
This: https://doc.akka.io/docs/akka/2.5.5/scala/stream/stream-integrations.html#source-actorref

needs an example on how to use Source.actorRef, it's non trivial for people new to streams and actors, esp. since involves materialized value dance.

**Comment by raboof** [comment]
:+1: perhaps also add an example for `ActorRef.queue` to highlight pros/cons?

**Comment by ktoso** [comment]
Sounds good

**Comment by ktoso** [comment]
Thanks a lot :)

You can also look at https://github.com/akka/akka/pull/24854 in which I added docs for `actorRefWithAck`.

**Comment by ktoso** [comment]
> what about fusing for Source.actorRef? It calls actorOf of ActorMeterializer(Impl) so it looks like there is an async boundary between Source.actorRef and following graph stages?

The stage itself can be fused, the actor is actually "the stage (actor ref)", and it will receive events asynchronously, but the stage itself can be fused I believe

**Comment by ktoso** [comment]
> difference and similarity in overflow strategy

Yes, but note that `    require(overflowStrategy != OverflowStrategies.Backpressure, "Backpressure overflowStrategy not supported")`

**Comment by richardimaoka** [comment]
oh ok sure. thanks for the info.

**Comment by nvollmar** [comment]
Added PR #26485 with code example for `Source.actorRef`
