### ISSUE TITLE
Current timeout handling leaves to perceived excessive delay

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#24616]
[akka streams] 

The [`idleTimeoutCheckInterval`](https://github.com/akka/akka/blob/2a9c0370e0a446f1cdc0cabafa37d6e9df5e0699/akka-stream/src/main/scala/akka/stream/impl/Timers.scala#L30-L32) implementation can lead the check interval to be `1/8th` of the actual timeout. This can be a huge gap when timeouts are in the [tens](https://github.com/akka/akka-http/blob/7c8b4ff4c61eb32f9365c6e3365f22c7ddaaa1c1/akka-http-core/src/main/resources/reference.conf#L34) or [hundreds](https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/resources/reference.conf#L25) of seconds.

This was found thanks to a Lagom-Chirper user spotting timeouts of [`85s` when the setup is `75s`](https://github.com/lagom/lagom-java-chirper-example/issues/108#issuecomment-367517695).

Instead of a periodic check interval, the idle timeout could schedule checks depending on how close the timeout is down to a precision of `1s`.

**Comment by johanandren** [comment]
Ok, so for 100 seconds we get 12.5s, I agree maybe above 1 second we could have the check every second, or something along those lines. The overhead won't be that bad, the important thing is to not run the check too often for lower timings, so maybe keep those as is.

**Comment by ignasi35** [comment]
@johanandren I have something drafted, mind if I PR it?

Unfortunately testing this is not so _easy_. Any ideas?

**Comment by johanandren** [comment]
Make a unit test just for the calculation method?
