### ISSUE TITLE
failed: LineNumberSpec with jdk9

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24617]
https://jenkins.akka.io:8498/job/akka-nightly-jdk9/84/

@jlprat Perhaps something for you to follow up on?

**Comment by jlprat** [comment]
Yes I can follow up, but unfortunately not this weekend.

**Comment by 2m** [comment]
We had one more failure when on jdk8: https://jenkins.akka.io:8498/job/akka-nightly-2.12/493/consoleFull

**Comment by ktoso** [comment]
Separate ticket I’d suggest since this was about jdk9?

-- 
Konrad Malawski

**Comment by jlprat** [comment]
It's funny that it fails now with jdk8, the PR build and at least a couple of nightlies were successful?
Did anything else change, like Scala version?
Because the failures happen only for the Scala part, not the Java one.

**Comment by jlprat** [comment]
Then, I'm wondering how come did it pass on the PR validation...
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11670/consoleFull

**Comment by jrudolph** [comment]
PR validation runs on Scala 2.11.

**Comment by jlprat** [comment]
OK, that might be some explanation.
I did some runs on my machine with Scala 2.12. Or at least I asked sbt to do it: `++2.12.3`

I'll take a look at it

**Comment by jlprat** [comment]
BTW, would it make sense to revert these changes till we find the solution?

**Comment by jrudolph** [comment]
Maybe some things were fixed/changed in Scala 2.12.4? I think in any case it might make sense to use less strict assertions, maybe just check that the version ranges overlap at least?

**Comment by jlprat** [comment]
For the error, it looks like we can't get the lines at all:
`LineNumberSpecCodeForScala.scala:12 did not equal NoSourceInfo (LineNumberSpec.scala:25)`

I'll take a look

**Comment by jrudolph** [comment]
> For the error, it looks like we can't get the lines at all:

I think it's the other way round: That's a line guarded with `isScala212` which expects no information but now seems to get line information with Scala 2.12.4.

**Comment by 2m** [comment]
A couple of more failures during this night:

https://jenkins.akka.io:8498/job/akka-nightly-jdk9/88/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly-2.12/494/consoleFul

**Comment by jlprat** [comment]
I don't know if I can work on this before next Wednesday. Is it OK?

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk9/89/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly-2.12/495/consoleFull

**Comment by jlprat** [comment]
Strangely enough, if I now re-run the tests for Scala 2.12.3 it fails as well on my system. Maybe I had a problem with sbt when I was testing it locally...
