### ISSUE TITLE
Unexpected actor hierarchy when using IndirectActorProducer

### ISSUE THREAD

**Issue by legatoo** [akka/akka#24629]
I implement a springActorProducer to create actor, please check the gist at the bottom. 
Here is the case: 

    @Component
    @Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
    public class ActorA extends AbstractActor{{
    	final SpringBean bean;
    	private ActorRef actorB;
    
    	//constructor
    	@Inject
    	public ActorA(@Named("springBean") SpringBean bean) {
    		this.bean = bean;
    
    		//create actorB
    		this.actorB = getContext().actorOf(
                        FromConfig.getInstance()
                	        .props(SpringExtProvider.get(getContext().getSystem()).props("actorB"))
                            .withDispatcher("akka.actor.rpc-pool"), "actorB");
    	}
    	
    }

actorB's configuration is defined in `application.conf`:

    akka.actor.deployment {
      /actorA/actorB {
        router = round-robin-pool
        resizer {
          lower-bound = 5
          upper-bound = 15
          rampupRate = 1
          backoffThreshold = 0.3
          backoffRate = 0.1
          messages-per-resize = 1
        }
      }
    }

Because I create actorB in actorA, I think the hierarchy should be `/actorA/actorB`, but when I run the application, akka told me 

> Configuration missing for router
> [akka://demo-akka-system/user/actorA/$b/actorB] in 'akka.actor.deployment' section

please pay attention to the log. the hierarchy akka detected is `/actorA/$b/actorB`. So I change the conf to `"/actorA/*/actorB"`, and problem disappears.

My question is:

1) why the hierarchy changes when using customed IndirectActorProducer? what is the $b actor?

2) how does this change effect akka supervision system?

FYI: 

I'm using `akka 2.5.8`

[SpringExtension.java][1]

[SpringActorProducer.java][2]

  [1]: https://gist.github.com/legatoo/66ff6a6b209fb5311a0764ffc393b3fe
  [2]: https://gist.github.com/legatoo/74588362e9e16b58ea85edc4ba12c967

**Comment by chbatey** [comment]
Hi @legatoo , we try to use the issue tracker only for issues and feature-tracking, and I think this more of a question for helping out understanding the APIs. Please use the Akka forums for questions like this, thanks!
