### ISSUE TITLE
Misaligned accesses in FlightRecorder cause JVM coredumps on SPARC

### ISSUE THREAD

**Issue by alanbur** [akka/akka#24639]
From a discussion in https://groups.google.com/forum/#!topic/akka-user/lHxjzuDRMsk:

OK, debugging has actually uncovered another bug in the flight recorder. I enabled the debug options you suggested and some others that seemed useful, including:

```
akka.remote.artery.advanced.flight-recorder.enabled = on
```

With that option set and Aeron UDP enabled, here's what happens:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0xffffffff7b978e30, pid=16182, tid=0x0000000000000002
#
# JRE version: Java(TM) SE Runtime Environment (8.0_141-b15) (build 1.8.0_141-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.141-b15 mixed mode solaris-sparc compressed oops)
# Problematic frame:
# V  [libjvm.so+0xd78e30]  Unsafe_SetLong+0x168
#
# Core dump written. Default location: /tmp/demo/core or core.16182
```
and:

```
siginfo: si_signo: 10 (SIGBUS), si_code: 1 (BUS_ADRALN), si_addr: 0xffffffff7db10004

Stack: [0xffffffff7f1f0000,0xffffffff7f2f0000],  sp=0xffffffff7f2ee310, free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xd78e30]  Unsafe_SetLong+0x168
j  sun.misc.Unsafe.putLong(Ljava/lang/Object;JJ)V+863513888
j  sun.misc.Unsafe.putLong(Ljava/lang/Object;JJ)V+0
j  org.agrona.concurrent.MappedResizeableBuffer.putLong(JJ)V+24
j  akka.remote.artery.FlightRecorder.init()V+28
j akka.remote.artery.FlightRecorder.<init>(Ljava/nio/channels/FileChannel;)V+228
j akka.remote.artery.ArteryTransport.initializeFlightRecorder()Lscala/Option;+72
j akka.remote.artery.ArteryTransport.<init>(Lakka/actor/ExtendedActorSystem;Lakka/remote/RemoteActorRefProvider;)V+35
j akka.remote.artery.aeron.ArteryAeronUdpTransport.<init>(Lakka/actor/ExtendedActorSystem;Lakka/remote/RemoteActorRefProvider;)V+3
j akka.remote.RemoteActorRefProvider.init(Lakka/actor/ActorSystemImpl;)V+205
j  akka.actor.ActorSystemImpl.liftedTree2$1()Lakka/actor/ActorSystemImpl;+15
j akka.actor.ActorSystemImpl._start$lzycompute()Lakka/actor/ActorSystemImpl;+13
j  akka.actor.ActorSystemImpl._start()Lakka/actor/ActorSystemImpl;+8
j  akka.actor.ActorSystemImpl.start()Lakka/actor/ActorSystemImpl;+1
j akka.actor.ActorSystem$.apply(Ljava/lang/String;Lakka/actor/setup/ActorSystemSetup;)Lakka/actor/ActorSystem;+88
j akka.actor.ActorSystem$.apply(Ljava/lang/String;Lscala/Option;Lscala/Option;Lscala/Option;)Lakka/actor/ActorSystem;+34
j akka.actor.ActorSystem$.apply(Ljava/lang/String;Lcom/typesafe/config/Config;)Lakka/actor/ActorSystem;+15
j  com.oracle.labs.remoting.Main$.main([Ljava/lang/String;)V+244
j  com.oracle.labs.remoting.Main.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub
V  [libjvm.so+0x743ae4]  void JavaCalls::call_helper(JavaValue*,methodHandle*,JavaCallArguments*,Thread*)+0x744
V  [libjvm.so+0x7dc94c]  jni_CallStaticVoidMethod+0x7a8
C  [libjli.so+0x7404]  JavaMain+0x7e4
C  [libc.so.1+0x1e1c58]  _lwp_start+0x8
```

This is a straightforward alignment bug, the faulting address is 4-byte aligned instead of 8-byte aligned. I believe the culprit is this, from `FlightRecorder.init()`:

```
  private def init(): Unit = {
    globalSection.putInt(0, MagicString)
    globalSection.putLong(StartTimeStampOffset, System.currentTimeMillis())
  }
```
so that's a 4-byte value followed immediately by an 8-byte value - misaligned access - bang. The fix is either to add padding or to increase `MagicString` to be a 64-bit value. However the same Int/Long pattern occurs elsewhere in the code so it will all need fixing, and that's going to need changes in the buffer format and result in a binary incompatibility - perhaps requiring a change in the `MagicString` value?

**Comment by patriknw** [comment]
@alanbur Thanks for reporting. Would you be able to create a pull request fixing this?

**Comment by alanbur** [comment]
As I said in the bug, fixing this would require introducing binary incompatibility in the flight recorder buffer layout. I don't know enough about how it is implemented/used to make an informed assessment of what impact that would have.

**Comment by patriknw** [comment]
ok, that is fine. The flight recorder is not heavily used yet, and therefore I don't think preserving the format is critical.

**Comment by alanbur** [comment]
Sure, I can look at this but I'll have to slot it in when I have time - please feel free to ping me if I forget :-)

**Comment by patriknw** [comment]
Thanks, we'll also ping here in case we start working on it.

**Comment by patriknw** [comment]
Yes, flight recorder is independent of Aeron, ie also used for Artery TCP.

**Comment by chbatey** [comment]
FYI Sparc is now supported for Aeron. Tho we haven't fixed flight recorder https://github.com/akka/akka/pull/25743

**Comment by patriknw** [comment]
The Artery flight recorder has been replaced by JDK flight recorder
