### ISSUE TITLE
Akka Typed Logger missing log() method

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24648]
The new Logger trait is excellent, it misses the `log()` method though :)

It is super useful when loglevel comes from config:

```
if (logLevel != Logging.OffLevel) context.log.log(logLevel, "Stashing message: {}", msg)
```

**Comment by txsmith** [comment]
Hi, I might want to pick this up. Do you think this is suitable as a first contribution?

**Comment by ktoso** [comment]
Sure! Thanks a lot :) it should be fairly simple, if not sure about anything please ask

**Comment by ktoso** [comment]
See the log method on the untyped LoggerAdapter for what the signature should be. It might need more overloads due to the Marker
