### ISSUE TITLE
Consideration: Impossible to provide LogSource for Typed ActorContext's .log

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24647]
The .log is nice to have on context, however it is not possible to provide it with a custom `LogSource` as far as I can see. Can we find a way of making that happen with some Behavior decorator?

I've found the following log source invaluable during persistence debugging:

```
  implicit object PersistentBehaviorLogSource extends LogSource[EventsourcedBehavior[_, _, _]] {
    override def genString(b: EventsourcedBehavior[_, _, _]): String = {
      val behaviorShortName = b match {
        case _: EventsourcedRunning[_, _, _]                  ⇒ "running"
        case _: EventsourcedRecoveringEvents[_, _, _]         ⇒ "recover-events"
        case _: EventsourcedRecoveringSnapshot[_, _, _]       ⇒ "recover-snap"
        case _: EventsourcedRequestingRecoveryPermit[_, _, _] ⇒ "awaiting-permit"
      }
      s"PersistentBehavior[id:${b.persistenceId}][${b.context.self.path}][$behaviorShortName]"
    }
  }

```

paging @johanandren

**Comment by ktoso** [comment]
I guess with immutable style this would not be doable in any case perhaps? :-(

**Comment by johanandren** [comment]
the logger is a mutable field in context, so it may be doable but the semantics could prove surprising?

**Comment by johanandren** [comment]
Did you consider what I mentioned in the other PR, do it with ctx.log but provide mdc with the extra values?

**Comment by ktoso** [comment]
I must have missed that comment, will try with MDC! That may be better since catchable by tools then hm...

**Comment by johanandren** [comment]
That'd be `Behaviors.withMdc` if you haven't seen it.

**Comment by ktoso** [comment]
Yeap got it, will try

**Comment by ktoso** [comment]
the MDC solves it, opened related tickets
