### ISSUE TITLE
Typed; Does withMdc really need ClassTag?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24664]
Does it really need a classtag? It's implemented using the Intercept which does, but that makes using withMdc not so nice in generic settings:

`[error] /Users/ktoso/code/akka/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedRunning.scala:191:22: No ClassTag available for C`
`[error]     Behaviors.withMdc(_ ⇒ mdc, wrapped)`

A specialized impl that does not need class tag would be more user friendly

**Comment by patriknw** [comment]
sounds good, probably do together with #24665
