### ISSUE TITLE
withMdc API changes

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24665]
Two things about the API to discuss:

--------

1) 

I found that most things are nice to "wrap" like directives:

```
setup { 
  wrapped
```

withMdc has a different style: `withMdc(_ => mdc, wrapped)`

It would be more consistent to provide `withMdc(_ => mdc) { wrapped }`

Since then one can continue the "same style":

```

setup { 
  withMdc { 
    immutable {}
```

rather than 

```
setup {
  withMdc(..., immutable {
  })
}
```

-------

2) often the mdc carries things about what behavior we are, so `withMdc(mdc) {}` without the function would be nice.

**Comment by johanandren** [comment]
Both sounds good to me.

**Comment by patriknw** [comment]
looks good
