### ISSUE TITLE
Behaviors.receive

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24683]
Introduce a simplified 1 parameter version of Behaviors.immutable.

It's purpose is to:
- avoid repetition and forcing of `immutable { (_, m) => m match {` when not interested in context
- avoid repetition of context presence if already a context is in scope, like in `setup { ctx => immutable (context, m) =>`
- "feel like akka actor's receive", since people like / associate the `receive = { case Msg => ` style very much with Akka, now it is still available, so Typed has a bit more similar things to old style.

Note, context is very likely needed by real world actors, however, often you'd have the context from a setup, or enclosing class already.

This is a follow up from https://github.com/akka/akka/issues/24643

**Comment by patriknw** [comment]
Let's rename `immutable` to `receive` and add `receiveMessage`.
And remove `mutable` in favor of `setup`.

**Comment by ktoso** [comment]
These renames sound excellent; back to classic naming <3 love it, what actors are all about - receiving, messages etc.

**Comment by patriknw** [comment]
`immutablePartial` becomes `receivePartial` and adding `receiveMessagePartial`

**Comment by hepin1989** [comment]
This recalls me the `channelRead0` in Netty's `SimpleChannelInboundHandler` and will rename back to `messageReceived` then.

**Comment by ktoso** [comment]
It's plain old Akka naming... nothing to do with Netty 😉

**Comment by hepin1989** [comment]
Naming is hard, harder than coding.

**Comment by johanandren** [comment]
Nice, 👍 on these names and simplification!

**Comment by ktoso** [comment]
Tackling this so code examples on a meetup on thursday I have use the latest API

**Comment by hseeberger** [comment]
Nice names, guys!

**Comment by ktoso** [comment]
👍
