### ISSUE TITLE
add more tests for Typed Persistence

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24687]
Since the new Typed Persistence implementation is not using the untyped implementation we must port many of the untyped tests to Typed.

RecoveryPermitterSpec is one of the most important.

**Comment by ktoso** [comment]
👍 Thanks for ticket, yeah I guess best to port the entire testsuite class by class

**Comment by kelebra** [comment]
Do you mind if I work on this one?

**Comment by patriknw** [comment]
That wouldbe great.
Perhaps port them somewhat selectively, for example I’m not sure there is much value in running all with leveldb and inmem. Prefer inmem then. Let me know ifquestions aling the way. Splitting up in several PRs might be good.

**Comment by kelebra** [comment]
Am I missing something or `AtLEastOnceDelivery` functionality was not ported to typed API? I am asking this because tests `AtLeastOnceDeliveryCrashSpec`, `AtLeastOnceDeliveryFailureSpec` and `AtLeastOnceDeliverySpec` are all about it :-)

**Comment by ktoso** [comment]
Yes functionality is still missing in the typed port. AFAIK the same with deleting events and snapshots.

**Comment by kelebra** [comment]
Checklist:

- [ ] `AtLeastOnceDeliveryCrashSpec` (`akka.persistence.AtLeastOnceDelivery` not implemented) - skipped
- [ ] `AtLeastOnceDeliveryFailureSpec` (`akka.persistence.AtLeastOnceDelivery` not implemented) - skipped
- [ ] `AtLeastOnceDeliverySpec` (`akka.persistence.AtLeastOnceDelivery` not implemented) - skipped
- [ ] `EndToEndEventAdapterSpec` (`akka.persistence.journal.EventAdapter` not used in typed API) - skipped
- [ ] `EventAdapterSpec` (`akka.persistence.journal.EventAdapter` not used in typed API) - skipped
- [ ] `LoadJournalSpec` (`akka.persistence.journal.inmem.InmemJournal` not used in typed API) - skipped
- [ ] `ManyRecoveriesSpec` - transferred
- [ ] `OptionalSnapshotStoreSpec` - transferred
- [ ] `PerformanceSpec` - transferred, issue opened
- [ ] `PersistentActorBoundedStashingSpec` - should be implemented
- [ ] `PersistentActorDeleteFailureSpec` (`akka.persistence.Eventsourced#deleteMessages` not used in typed) - skipped
- [ ] `PersistentActorFailureSpec` - should be transferred
- [ ] `PersistentActorJournalProtocolSpec` - not yet sure about this one
- [ ] `PersistentActorRecoveryTimeoutSpec` - not yet sure about this one

**Comment by johanandren** [comment]
Checking of a few in the list and providing explanation here: 

* `EndToEndEventAdapterSpec` - persist and recover with adapter covered by `EventSourcedBehaviorSpec` `adapt events`, `adapter multiple events with persist all`, `adapt and tag events`
* `EventAdapterSpec` - tests tagging - covered by `EventSourcedBehaviorSpec` `tag events`

I'll pick up
* `PersistentActorBoundedStashingSpec` - possibly covered by `EventSourcedBehaviorStashSpec` and `StashStateSpec` but can't find any tests covering going over the `stashCapacity`
* `TimerPersistentActorSpec`

**Comment by patriknw** [comment]
Here is what I think is remaining (not listing things that are covered by separate tickets, such as deletes):
* [ ] Some more failure testing, maybe some inspiration from EventSourcedActorFailureSpec
* [ ] A few things from PersistentActorSpec
  * "fail fast if persistenceId is null"
  * "fail fast if persistenceId is an empty string"
  * "be able to persist events that extend AnyVal"
  * "support calling persistAll with Nil"
* [ ] PersistentActorRecoveryTimeoutSpec
* [ ] withTimers, something exists already in EventSourcedBehaviorSpec but see if that is enough coverage or more is needed. Probably good to break out that to a separate Spec. Combination with the interceptor and stash could cause trouble. Inspiration from TimerPersistentActorSpec

**Comment by patriknw** [comment]
I'll take the ones from PersistentActorSpec now

**Comment by patriknw** [comment]
I'll take PersistentActorRecoveryTimeoutSpec now

**Comment by patriknw** [comment]
I take withTimers now

**Comment by patriknw** [comment]
I have completed this with several PRs. I also used Scoverage to find missing test coverage.
