### ISSUE TITLE
Typed Logger, provide lightweight way to pass MDC directly

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24684]
Outcome of a typed dicussion call... we found that one may want to pass MDC directly in the new Logger in Typed, let's make sure this API exists.

This is for when you can't or don't want to use the wrapper `withMdc`; methods should be directly on Logger

**Comment by johanandren** [comment]
So that would mean something like `log.withMdc(mdc).info("msg")`? 

I don't think we should make a public API for a stateful MDC in the context as that is too easy to leak between messages by mistake (this is the core reason for the `withMdc` design).

**Comment by patriknw** [comment]
I think the suggestion was to simply provide a mdc: Map parameter overload in all `info`, `error`...
if overload doesn't work it might be ok with `infoWithMdc`, `errorWithMdc`

**Comment by johanandren** [comment]
Uff, that is a lot of work though, ~70 methods we need overloads of. Should we limit combinations? Just `{debug,info,warning,error}(mdc, String)` rather than all possible arities of arguments and tags and exceptions? Or just go with the idea I had above with `log.withMdc(mdc).whicheverMethod`?

**Comment by patriknw** [comment]
If withMdc works that is great

**Comment by ktoso** [comment]
withMdc looks good, thanks @johanandren !
