### ISSUE TITLE
Documentation on auto downing should be more explicit about the consequences of using it.

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka#24696]
The documentation on auto downing (https://doc.akka.io/docs/akka/2.5.3/scala/cluster-usage.html#auto-downing-do-not-use-) provides some detail on the consequences of using it, but this should be more explicit.

> We recommend against using the auto-down feature of Akka Cluster in production. This is crucial for correct behavior if you use Cluster Singleton or Cluster Sharding, especially together with Akka Persistence. For Akka Persistence with Cluster Sharding it can result in corrupt data in case of network partitions.

This part is good. It explicitly mentions that with Akka Persistence it can result in data corruption, but there are other consequences.

The docs should explicitly mention the following:

- It breaks the contract of Singleton and Sharding by allowing multiple instances to be active in separate parts of a partitioned cluster (split brain scenario).

- Even in a more simple cluster scenario (eg. Cluster Aware Routers), a network partition will cause separate clusters to form which will then be unable to merge back into a single cluster after the partition has been resolved. While this may not break any functionality immediately, it will likely cause the cluster performance to degrade. To resolve this you will have to restart parts of the cluster.

**Comment by patriknw** [comment]
sounds excellent, would you be able to create a PR?

**Comment by WadeWaldron** [comment]
Done: https://github.com/akka/akka/pull/24697
