### ISSUE TITLE
shoud we add `(lenth:Long,timeUnit:java.util.concurrent.TimeUnit)` method to where `FiniteDuration` is used?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24720]
eg:

```
scheduleOnce(delay: FiniteDuration)


scheduleOnce(delay:Long,timeUnit:TimeUnit)
```

When two `FiniteDuration`s is used, it seems awkward.

**Comment by patriknw** [comment]
wat? isn't this covered by adding `java.time.Duration` (https://github.com/akka/akka/issues/24646)?

**Comment by hepin1989** [comment]
```
scheduleOnce(delay: FiniteDuration)

scheduleOnce(delay: java.time.Duration)

scheduleOnce(delay:Long,timeUnit:TimeUnit)
```

**Comment by ktoso** [comment]
No, this would cause an even larger exponential explosion of overloads where not proving all that much gain - the Java api exists and is simply the Java duration.

**Comment by patriknw** [comment]
That is a clear no go. `Duration` and `FiniteDuration` are good, but adding more options will just be causing questions "when to use what?, are they the same?". When would we stop, there could be many more signatures that could be "convenient":

```
scheduleOnce(delayInIsoFormat: String)
scheduleOnce(delayInMillis: Int)
scheduleOnce(delayBetween: Pair<Calendar, Calendar>)
```
