### ISSUE TITLE
Tests for BoundedBlockingQueue and AffinityPool

### ISSUE THREAD

**Issue by txsmith** [akka/akka#24733]
From coverage analysis, we found that both `BoundedBlockingQueue` and `AffinityPool` do not have any tests by themselves, and their behavior is also hardly covered by other tests. 

Would you accept a PR adding some tests for either of these?

**Comment by patriknw** [comment]
Sounds good, thanks

**Comment by txsmith** [comment]
Cool, I'll submit a PR later today.
