### ISSUE TITLE
Most efficient way to process data with akka-steams

### ISSUE THREAD

**Issue by Sammers21** [akka/akka#24732]
The issue is related to `akka-streams` project.

To begin with, I would like to describe a problem I m trying to solve: You have a lot of numbers and for each number, you should receive(the process takes some time) an additional information, approximately 1 MB in weight and then proceed it. We also may assume that the heap size is 512mb. How can you process all the numbers in the most efficient way?

To model this situation, here is example:
```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Sink, Source}

import scala.concurrent.Promise
import scala.concurrent.duration._
import scala.util.{Random, Try}

object Hello extends App {

  implicit val as = ActorSystem()
  implicit val am = ActorMaterializer()

  import as.dispatcher

  Source(1 to 1000000)
    .mapAsync(100) { element =>
      val promise = Promise[Array[Byte]]()
      as.scheduler.scheduleOnce((ThreadLocalRandom.current().nextInt() % 2000 + 3000).millis) {
        promise.complete(Try {
          val arr = new Array[Byte](1024 * 1024)
          Random.nextBytes(arr)
          arr
        })
      }
      promise.future
    }
    .runWith(Sink.foreach((each: Array[Byte]) => {
      val hello = each.mkString(",").size
      println(hello)
    })
    )
}
```

In this case, the list of numbers is the list consisted of numbers from 1 to 1000000, and the process of receiving an additional information takes from 3 to 5 seconds. After receiving we do processing by printing a size of a string containing all bytes of information.

The main problem I faced in the example is limiting the number of units of additional information. How can I control it? 

If I place `.buffer(100, OverflowStrategy.backpressure)` directly after the Source declaration, can I guarantee, that at the same time at any point there are will be only 100 units of additional information in memory?

**Comment by johanandren** [comment]
Hi @Sammers21, we try to use the issue tracker only for issues and feature-tracking, please use the [brand new forums](https://discuss.akka.io) or the [gitter channel](https://gitter.im/akka/akka) for questions like this, thanks!
