### ISSUE TITLE
FSM: State timeout doesn't work for an initial state

### ISSUE THREAD

**Issue by LukaszMarchewka** [akka/akka#24738]
There isn't option to set a state timeout for an initial state. Following code shows the issue:

```
import akka.actor.{FSM, Props}
import io.scalac.akka.demo.FsmTest._

import scala.concurrent.duration._

class TestFsm extends FSM[State, Data] {

	startWith(Idle, EmptyData)

	when(Idle, 1.second) {
		case Event(StateTimeout, _) =>
			println("timeout")
			stop()
	}
}

object FsmTest {
	def props: Props = Props(new TestFsm)

	sealed trait State
	case object Idle extends State

	sealed trait Data
	case object EmptyData extends Data
}

```
The text `timeout` wouldn't be printed. Solutions like:
- `startWith(Idle, EmptyData, StateTimeout(1.second))`
- `setStateTimeout(Idle, StateTimeout(1.second))`
don't work too.

Akka version: 2.5.11

**Comment by johanandren** [comment]
The code is missing a call to `initialize()` in the end of the constructor, with that in place the timeout is triggered.
