### ISSUE TITLE
Missing example on how to use `TestFSMRef` from java

### ISSUE THREAD

**Issue by hekmekk** [akka/akka#24756]
There is no documentation on how to use [TestFSMRef](https://doc.akka.io/api/akka/current/akka/testkit/TestFSMRef.html) from java. Specifically there is no hint available on how to satisfy the parameter `implicit ev: T <:< FSM[S, D]`.

**Comment by johanandren** [comment]
I think it is simply missing a Java API. Using the existing API and providing the type evidence from Java will not be possible (that is put in there by the Scala compiler to transfer type knowledge from compile time to runtime).

**Comment by Camsteack** [comment]
Is there any work planned on that ? Not being able to test our FSM properly is quite a problem for us

**Comment by ktoso** [comment]
`Test*Ref` are discouraged in general, simply test FSMs just as you would test any other actor -- via sending messages.

As it's tagged as a `help wanted` -- if you want to see this solved, the best way is to contribute a fix, as we are not planning to work on this in the near term

**Comment by Camsteack** [comment]
Thanks a lot for the quick answer, I will have a look at that and if it's simple enough for me to contribute :)

**Comment by hekmekk** [comment]
Thanks for clarifying that `Test*Ref` is discouraged @ktoso. Our approach was doing exactly what you suggested and it felt like a natural thing to do.

**Comment by Captain1653** [comment]
This issue is quite old. It was mentioned before:

> Test*Ref are discouraged in general, simply test FSMs just as you would test any other actor -- via sending messages.

Should this issue be closed?

**Comment by johanandren** [comment]
Yep
