### ISSUE TITLE
timestamped snapshots not published

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24752]
https://jenkins.akka.io:8498/job/akka-publish-nightly/

**Comment by 2m** [comment]
Fixed `stampVersion` and reran nighly publish job:

https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.11/2.5-20180405-163301/
https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.12/2.5-20180405-164721/
