### ISSUE TITLE
Stream groupBy retaining memory and disallowing key reuse?

### ISSUE THREAD

**Issue by huntc** [akka/akka#24758]
I've just noticed something odd with Akka stream's `groupBy` - it appears that once my substream has been closed, it isn't possible for the same group by key to appear again subsequently.

[Looking through the code](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala#L227), I notice that `closedSubstreams` does not appear to ever have its elements removed. Not only is this preventing my program from working, but I'd imagine that it would result in unwanted memory retention.

Any thoughts? I'm unsure how to mitigate this issue.

**Comment by ktoso** [comment]
That's how it works. Do not cancel such substream.

**Comment by huntc** [comment]
So you're stating that `groupBy` should be used where only where the set of key values are known at the time of writing the program? I've not seen that mentioned anywhere. 

The API doc also states:

> Substream mode is exited either by closing the substream (i.e. connecting it to a Sink)...

Which says to me that if a subsequent stage closed the substream then this is acceptable.

**Comment by huntc** [comment]
It would also be great to understand why `closedSubstreams` is important to be maintained by the `GroupBy` stage. Its only use appears to consume data for any key that it has previously consumed. Why do we need this in place of doing what we would do if there was no previous key i.e. run a new substream?

**Comment by ktoso** [comment]
You ignored the suggestion about not closing such substream -- why do you cancel such substream, if you expect it to get back and DO want to read from it then again?

It is simply a guarantee provided by the specific implementation -- once cancelled, does not come back.

**Comment by huntc** [comment]
My particular use case is that I bind to a UDP port. Any number of clients can connect to that port.

I have a custom stage that is responsible for framing. It is quite possible for multiple clients to connect to the UDP port at around the same time. I use groupBy on the source IP/Port so that subsequent packets are routed to the correct framing state.

The framing stage is completed when:

* there is no further data having processed a valid frame, so we assume that we may never hear from the client again and free up substream state after a timeout
* we receive an incomplete frame with no further data from the client after a timeout

FYI I've just tested the `GroupBy` stage without the `closedSubstreams` field. My program is behaving as I expect. I'd be happy to create a PR if we can agree that `closedSubstreams` is of no utility.

**Comment by ktoso** [comment]
Only because one case you have does not want that guarantee does not mean that the guarantee should be removed, potentially breaking people who rely on this.

It can be introduced as an option though, feel free to work on such proposal

**Comment by huntc** [comment]
I did enquire as to the utility of `closedStreams` - it does not appear useful - please advise on what I could be providing an option to.

**Comment by huntc** [comment]
I should also add, `activeSubstreamsMap` is checked against `maxSubstreams`. So, given that `closedStreams` grows continuously, I believe we may have a memory retention issue.

**Comment by ktoso** [comment]
It implements the "1 uniquely created substream per key" guarantee that this stage has. 
It is not useful in your use case, thus, the suggestion above -- as if you would provide an option where the uniqueness is not guaranteed. Please focus on the discussion rather than posting the same observation discarding any proposals made.

**Comment by huntc** [comment]
I have re-read your replies. In the spirit of retaining focus:

* `closedSubstreams` only ever grows and is not included in the `maxSubstreams` check, possibly leading to memory retention
* `closedSubstreams` appears to serve no utility and behaves contrary to "Substream mode is exited either by closing the substream (i.e. connecting it to a Sink)..."

On the second point, I'd appreciate a pointer to the "1 uniquely created substream per key" documentation where it states that a key may never be subsequently re-used. In the absence of this documentation, I would be happy to provide it in my PR.

**Comment by huntc** [comment]
Are there further thoughts? I’m reluctant to raise a PR on the back of this dialogue so far.

**Comment by huntc** [comment]
@agolubev - Just wondering if you have thoughts on this issue given your involvement with https://github.com/akka/akka/pull/20344

**Comment by ktoso** [comment]
Relax please, 5 hours ago was 5AM here...

**Comment by ktoso** [comment]
> closedSubstreams only ever grows and is not included in the maxSubstreams check, possibly leading to memory retention

That's what it does, yes; in order to guarantee the uniqueness guarantee that these stages hold.
I already mentioned that providing an option to not use these sets `reOpenSubStreamsForCancelledOnes = true` can be added and would not need that set then.

> closedSubstreams appears to serve no utility and behaves contrary to 
This is an misunderstanding of:  
  
> "Substream mode is exited either by closing the substream (i.e. connecting it to a Sink)..." 

```
  Source.single("")
    .groupBy(1, _.head)
    .to( // "closing the substream with a Sink"
      Sink.ignore
    )   // "exits the substream mode"
    .run() // normal operations, not substream operations
```

Wording is not _explicit_ in javadoc about the guarantee, but it is there when you read the words precisely:

> The key is computed for each element using the given function. When a new key is encountered for the **first time a new substream** is opened and subsequently fed with all elements belonging to that key.

Re opening a stream is simply not something this operation does; It is something we can add as a mode of it though; since changing existing behavior on this level likely is not a good idea.

@patriknw

**Comment by markusthoemmes** [comment]
Looking into implementing @ktoso's latest proposal.
