### ISSUE TITLE
404 links in our documentation

### ISSUE THREAD

**Issue by raboof** [akka/akka#24751]
The link to 2.5.11 at the bottom of https://doc.akka.io/docs/akka/2.4.20/scala/cluster-usage.html does not work.

Probably good to review how those links get generated, and see if there's any other 404's that show up a lot in our logs.

**Comment by johanandren** [comment]
A nightly job crawling the docs for 404s would be nice.

**Comment by raboof** [comment]
:+1: (fwiw I added a redirect for some URL's including the example above last friday, but let's keep this issue open to find some way to monitor 404's)

**Comment by Captain1653** [comment]
This issue is quite old. The link validator was added [in this PR](https://github.com/akka/akka/pull/31086).

Should this issue be closed?
