### ISSUE TITLE
Allow defining data ownership in Persistence?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24760]
Either a String or a Set[String] field likely in PersistentRepr and API to update this in writes would need to be provided.

**Comment by ktoso** [comment]
I'm playing around with how this might work

**Comment by patriknw** [comment]
I'm not sure how valuable this would be since the underlying data store typically only has one primary key anyway. I think such domain key must be mapped to a persistenceId by the application, in the end.

**Comment by patriknw** [comment]
Let's try to use tags for this
