### ISSUE TITLE
Do we do need `Duration` in Testkit?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24761]
I think as it would always be used in tests, so do really we need a `Duration` which may be Infinite?

```scala
  def receiveOne(max: Duration): AnyRef = tp.receiveOne(max)
```
I think let the `Duration` be `FiniteDuration` would be OK too.

**Comment by ktoso** [comment]
Not sure if this is worth changing API for.

Note that Duration created from a string is a Duration, not a finite one, so this would break users who used that style.

**Comment by patriknw** [comment]
I agree, not worth changing the API

**Comment by hepin1989** [comment]
thanks for that information
