### ISSUE TITLE
Provide interfaces for service objects like CoordinatedShutdown, HttpExt, EventsByPersistenceIdQuery, etc.

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24775]
The intent of this feature request is to facilitate testing with mocks. See this discussion for more context: https://discuss.lightbend.com/t/provide-interfaces-to-facilitate-testing-mocking/431.

**Comment by patriknw** [comment]
Interfaces were added for Typed extension, but or existing untyped extensions I don't think we can introduce that in a binary compatible way. Application code would have to define it's own abstractions for such things to be able to stub them.

I don't think there is much we can do about this, but let's use interfaces for any new extensions.
