### ISSUE TITLE
MergeLatest List[Source[T]] => Source[List[T]] #1959 

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24778]
Moved from https://github.com/akka/akka-http/issues/1959 opened by @fmasion

Add MergeLast 

transform List[Source[T]] => Source[List[T]] 
The same way Future.sequence does with Future but while keeping the streaming nature of sources

A picture worth 1000 words :
https://blogs.endjin.com/wp-content/uploads/2014/05/combine-latest.png

here is the discussion on [gitter](https://gitter.im/akka/akka?at=5ab2ffb1458cbde55760b573)

here is a very naïve implementation [exemple gist](https://gist.github.com/fmasion/24707eaeb728ddaec8522989ed7d9b4d) (with no generic Traversable, canBuildfrom....)

Hope you find it useful

**Comment by filipmatusak** [comment]
I want to try it

**Comment by ktoso** [comment]
Sure, please give it a shot 👍

**Comment by filipmatusak** [comment]
Can it be something like this?

`  def mergeLast[A, M[X] <: TraversableOnce[X]](in: M[Source[A, _]])(implicit cbf: CanBuildFrom[M[Source[A, _]], A, M[A]]): Source[M[A], _] = {
    in
      .toSeq
      .zipWithIndex
      .map { case (source, index) => source.map(value => (index, value)) }
      .reduce(_.merge(_))
      .scan(Map.empty[Int, A]) { case (acc, (index, value)) => acc.updated(index, value) }
      .dropWhile(_.size < in.size)
      .map { x =>
        val b = cbf.apply()
        b ++= x.values
        b.result()
      }
  }`

**Comment by filipmatusak** [comment]
@ktoso , could it be something like this?
https://github.com/filipmatusak/akka/blob/a20fcc6c594deb614d5311e219800e1e7610dd04/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L676

**Comment by ktoso** [comment]
Please note that it is not about `mergeLast`, but `mergeLatest`. "Last" means "last element of a stream", which would imply waiting for completion.

It should also likely be implemented using `combine` ;

```
  /**
   * Combines several sources with fan-in strategy like `Merge` or `Concat` and returns `Source`.
   */
  def combine[T, U](first: Source[T, _], second: Source[T, _], rest: Source[T, _]*)(strategy: Int ⇒ Graph[UniformFanInShape[T, U], NotUsed]): Source[U, NotUsed] =
```

I suggest starting out working on a PR with some tests (see above image to see what we mean semantics wise)

**Comment by filipmatusak** [comment]
I implemented GraphStage for this functionality, it can be used as strategy in combine()
