### ISSUE TITLE
Typed behavior testkit improvements

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24781]
Some improvements:

* [ ] Support getting the TestInbox of an anonymously spawned actor
* [x] ExpectPF to go along with expectType for effects
* [ ] Don't record spawnAdapter now it is a private api 
* [x] add a hasEffects as it reads nicer than retrieveEffects.isEmpty

I have most of these locally for scaladsl

**Comment by chbatey** [comment]
expectPF and hasEffects done in  #24800

**Comment by johanandren** [comment]
For reference, some new additional things for behavior testkit listed by Roland:
* #24826
* #24825 
* #24824

**Comment by patriknw** [comment]
@chbatey Is this done or in progress elsewhere now?

**Comment by chbatey** [comment]
Last bit is in #25146 which i just need to update to remove the compat library changes
