### ISSUE TITLE
Custom behavior decoration API

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24792]
While implementing the WithMdc behavior it struck me that all decorating stages will need to do the same dance to keep the inner behavior updated/wrapped. Not 100% sure but maybe we could provide an API that simplifies such usage. Could also be that it is uncommon enough to do that so that an abstraction isn't needed though.

**Comment by patriknw** [comment]
The new `BehaviorInterceptor` in https://github.com/akka/akka/pull/25575 solves this
