### ISSUE TITLE
Behaviors.withMdc overloads

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24798]
are bad for type inference (and compilation error messages), for example:

```
      def behavior3: Behavior[String] =
        Behaviors.withMdc(msg ⇒ Map("a" -> msg)) {
          Behaviors.receive {
            case (ctx, msg) ⇒
              ctx.log.info(msg.toUpperCase())
              Behaviors.same
          }
        }


[error] /Users/patrik/dev/akka/akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorLoggingSpec.scala:323:27: missing parameter type
[error]         Behaviors.withMdc(msg ⇒ Map("a" -> msg)) {
```

Removing all overloads except `def withMdc[T](staticMdc: Map[String, Any], mdcForMessage: T ⇒ Map[String, Any])(behavior: Behavior[T]): Behavior[T]` might be inconvenient, and adding more names is ... well, overkill

~~I suggest that we let the `Behaviors.withMdc` be only for the `mdcForMessage` function, and static MDC should be done with `context.log.withMdc`. Those should of course still be merged if both are used.~~

**Comment by johanandren** [comment]
The neat thing with the behavior decorator is that the inner behavior does not have to know about it in any way, so you can add a static mdc (tx-id for a session actor for example) without changing it. While if we only provide `context.log.withMdc` the behavior would have to accept a logger parameter or construct it itself.

I'm not sure how important that use case is, just wanted to mention it. If we don't care about that, we could maybe just as well get rid of the behavior decorator all together hand only provide `log.withMdc`, for per-message as well?

**Comment by patriknw** [comment]
Good point, didn't think about that.

**Comment by johanandren** [comment]
How about just skipping the overloads and keeping the three-param version, providing a `noMdcForMessage` constant function as part of the public API? 

I don't think that would be *that* inconvenient.

**Comment by patriknw** [comment]
works for me

**Comment by johanandren** [comment]
Even with no overload the type inference doesn't work as expected and has to be explicitly provided in places. I think this is because the inference works from left to right, so it will always see the message => mdc parameter first, and use the type it inferred from that.

Only solution I see to that is to put the inner behavior in parameter list 1 and the function in a subsequent parameter list, which isn't nice.

**Comment by johanandren** [comment]
Noticed this especially for the case of _not_ providing the per message one, but having a single method like so:

```
def noPerMessageMdc[T]: T => Map[String, Any] = ...

def withMdc[T](staticMdc: Map[String, Any], mdcForMessage: T ⇒ Map[String, Any])(behavior: Behavior[T]): Behavior[T] = ...
```

means that

```
withMdc(Map(something), noPerMessageMdc)(behavior)
```

Will always infer the wrong type unless explicitly put on `withMdc` or `noPerMessageMdc`

**Comment by ktoso** [comment]
This looks rather complicated and horrible to require the 2 params always though?
It does not really hurt all that much to keep the overloads IMHO and it is much more usable and less scary to new people "ok i can pass a map" "oh cool, i can make that a function from the message.. nice"

**Comment by johanandren** [comment]
Playing around with this some more, the big issue is having a type parameter that is used in the first parameter list that should be inferred from the second parameter list.

Maybe a different API would work better, something like:
```
Behaviors.addMdc(behavior)
 .perMessage(t => ...)
 .static(Map)
```

**Comment by johanandren** [comment]
Meh. Tried that last idea, and for example this case from the logging tests still doesn't infer types as I hoped for:

```
val behavior: Behavior[Protocol] =
        Behaviors.withMdc(
          Behaviors.setup { ctx ⇒
            Behaviors.receiveMessage { msg ⇒
              ctx.log.withMdc(Map("mdc" -> "inner")).info("Got message log.withMDC!")
              // after log.withMdc so we know it didn't change the outer mdc
              ctx.log.info("Got message behavior.withMdc!")
              Behaviors.same
            }
          }
        ).withStaticMdc(Map("mdc" -> "outer"))
```

So given that I think it isn't worth introducing an API that works "the other way" from the other behavior factories.

**Comment by johanandren** [comment]
As far as I can see the only option to avoid an explicit type parameter would be to have a unique name for the static mdc, the message one will likely always require explicit type either for the factory method, the for-message lambda or the decorated behavior.

**Comment by johanandren** [comment]
After experimenting with it a bit I don't think there is a way to completely avoid having to use an explicit type parameter, so I'm voting for leaving this be as is. (MDC is after all likely not the feature most of the users will use)

**Comment by patriknw** [comment]
ok, sounds good
