### ISSUE TITLE
Akka cluster sharding docs need improvement

### ISSUE THREAD

**Issue by anilkumarmyla** [akka/akka#24801]
https://doc.akka.io/docs/akka/2.5/cluster-sharding.html?language=scala 

There are few places in the docs which are either ambiguous or confusing or duplicated. Some things which are of concern to me while reading this

>In this context sharding means that actors with an identifier, so called entities, can be automatically distributed across multiple nodes in the cluster. Each entity actor...

Is the identifier an entity or the actor an entity? Wording can be adjusted here to reflect the same

>class Counter extends PersistentActor...

Combining cluster sharding with persistent actors is a bit confusing and is a not a good sample to start with cluster sharding, maybe start with a normal actor

>The ShardCoordinator decides which ShardRegion shall own the Shard and informs that ShardRegion. The region will confirm this request and create the Shard supervisor as a child actor. The individual Entities will then be created when needed by the Shard actor. Incoming messages thus travel via the ShardRegion and the Shard to the target Entity.

This paragraph is entremely confusing regarding who is creating child actor and which is the supervisor, and the parent-child relationship between actors. Can possibly be explained simpler with a diagram

>4. R1 creates child actor for the entity E1 and sends buffered messages for S1 to E1 child

E1 jumps into the picture from nowhere and is reader is left guessing what E1 is

**Comment by johanandren** [comment]
Sounds like good improvements. The combination with persistence is the canonical and most common use case so I think that should stay. Would you be up for making a PR with the other things?

**Comment by helena** [comment]
I'll take this to get into the release, since we've done quite a lot of changes since this issue was created.
