### ISSUE TITLE
Add Java deprecated annotation to all existing Scala deprecated

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24813]
To make the experience for Java devs nicer, since Java IDEs may not have a Scala plugin installed and therefore not get warnings in IDE when using deprecated methods and classes.

**Comment by johanandren** [comment]
Maybe hold on this, could be something we think Scala should add automagically

**Comment by ktoso** [comment]
> Maybe hold on this, could be something we think Scala should add automagically

Not sure betting on scalac adding this is a good strategy (time wise);
We should just do it.

**Comment by patriknw** [comment]
I'm not sure that this is very important because the annotation is in the class files. Tried with an Akka java sample.

```
public static abstract class Foo extends akka.actor.UntypedActor {

  }
```

```
mvn compile

[WARNING] /Users/patrik/dev/akka-samples/akka-sample-main-java/src/main/java/sample/hello/Greeter.java:[7,53] [deprecation] UntypedActor in akka.actor has been deprecated
```

**Comment by ktoso** [comment]
Yes there it works, because:

```
@Deprecated <<<<<
@deprecated("Use AbstractActor instead of UntypedActor.", since = "2.5.0")
abstract class UntypedActor extends Actor {
```

**Comment by patriknw** [comment]
ok, that was a really bad pick of me. Tried again with `ActorIdentity.getRef`, which doesn't have the `@Deprecated`.

It still works as expected with javac.

```
[WARNING] /Users/patrik/dev/akka-samples/akka-sample-main-java/src/main/java/sample/hello/Greeter.java:[17,9] [deprecation] getRef() in ActorIdentity has been deprecated
```

Note that one must enable `-Xlint` or `-Xlint:deprecation`.

**Comment by johanandren** [comment]
Closing this then if it in fact does work already and we shouldn't do it.
