### ISSUE TITLE
Akka Cluster connection error

### ISSUE THREAD

**Issue by nurbekm7** [akka/akka#24814]
I have the following error when starting akka cluster in kubernetes, only with akka version > 2.4.16. Can anybody help me with this pls ?

`[DEBUG] [03/27/2018 16:56:13.362] [New I/O worker #4] [NettyTransport(akka://InvoicesClusterSystem)] Remote connection to [/172.17.0.1:52788] was disconnected because of [id: 0x9426620d, /172.17.0.1:52788 :> /172.17.0.4:2552] DISCONNECTED
[DEBUG] [03/27/2018 16:56:13.363] [InvoicesClusterSystem-akka.remote.default-remote-dispatcher-7] [akka.tcp://InvoicesClusterSystem@invoices-seed-0.invoices-seed:2552/system/transports/akkaprotocolmanager.tcp0/akkaProtocol-tcp%3A%2F%2FInvoicesClusterSystem%40172.17.0.1%3A52788-10] Association between local [tcp://InvoicesClusterSystem@invoices-seed-0.invoices-seed:2552] and remote [tcp://InvoicesClusterSystem@172.17.0.1:52788] was disassociated because the ProtocolStateActor failed: Unknown`

$ifconfig
docker0: flags=4099 mtu 1500 inet 172.17.0.1 ...

$kubectl get po -o wide
NAME                     READY         STATUS RESTARTS AGE IP NODE
invoices-seed-0 1/1 Running 0 19m 172.17.0.4 minikube

invoices-seed-1 1/1 Running 0 19m 172.17.0.5 minikube

 kubernetes - v1.9.0

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on http://discuss.akka.io?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug. Please add clear information in that case about what behavior you expected and what you experienced instead. Adding a reproducer will help a lot as well.

BTW, Akka 2.4.x is end of life and you should update to 2.5.11.
