### ISSUE TITLE
allow Behavior.interpretMessage to be used with DSL ActorContext

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#24823]
Currently, users who write behavior decorators are forced to extend ExtensibleBehavior as there is otherwise no way to obtain an `akka.actor.typed.ActorContext`. With the previous refactorings of the ActorContext type hierarchy it might be possible to have the DSL ActorContexts extend the basic one; otherwise we should add overloads that accept the DSL ActorContext in the Behavior helper methods.

**Comment by johanandren** [comment]
Related to or duplicate of #24792

**Comment by johanandren** [comment]
What I was thinking was that if there was a smoother API for decoration, we wouldn't need to change `interpretMessage`, but I'm not sure, maybe this would be good regardless.
