### ISSUE TITLE
Memory leak: memory not released after actor system shutdown

### ISSUE THREAD

**Issue by puvanenthiran** [akka/akka#24832]
Hi,

I am using akka stream and akka-stream-alpakka-s3_2.12 for download file from s3, process the data and upload new processed data in new s3 files.

For each customer request, we perform below steps.
- create Actor system and ActorMaterializer
- down the file using S3Clinet.download API
- process the file line by line
- upload the processed data into new S3 file
- Wait for the process to complete ( using done.toCompletableFuture().join() call)
- shutdown ActorMaterializer and terminate Actor system

After shutdown, we noticed that the memory is keep increasing and it is never released. Finally, it reaches 100% memory usage of the system. We shutdown ActorMaterializer and terminate Actor system after each request.   

Here is code to reproduce the issue:

  BasicAWSCredentials awsCreds = new BasicAWSCredentials ("mykey", "secretkey");
  AWSCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider (awsCreds);

  final S3Settings settings = new S3Settings (
    MemoryBufferType.getInstance (),
    Option.empty (),
    credentialsProvider,
    regionProvider ("us-east-1"),
    true,
    Option.empty (),
    ListBucketVersion2.getInstance());

  ActorSystem system = ActorSystem.create ("parsingsystem");
  ActorMaterializer materializer = ActorMaterializer.create (system);

  S3Client client = new S3Client (settings, system, materializer);
  AmazonS3URI awsURI = new AmazonS3URI ("s3://mybucket/performtest/data_4Gb.json");

  final Pair<Source<ByteString, NotUsed>, CompletionStage<ObjectMetadata>> sourceAndMeta=client.download (awsURI.getBucket (), awsURI.getKey ());

  Source<ByteString, NotUsed> in = sourceAndMeta.first ();
  Source<ByteString, NotUsed> sourceLineByLine = in.via (
    Framing.delimiter (ByteString.fromString ("\n"), Integer.MAX_VALUE, FramingTruncation.ALLOW));

  Sink<ByteString, CompletionStage<MultipartUploadResult>> sink = client
    .multipartUpload ("mybucket", "performtest/Combined_" + name +".csv");

  CompletionStage<MultipartUploadResult> done = sourceLineByLine
    .map (ByteString::utf8String)
    .map (content -> JsonToCsvConverter.parse (content, config, ",", true))
    .map (ByteString::fromString)
    .runWith (sink, materializer);

  MultipartUploadResult result = done.toCompletableFuture ().join ();

  System.out.println ("Result -" + result);

   materializer.shutdown ();
  system.terminate ();

  System.out.println ("done");

Please help to resolve the issue.

**Comment by ktoso** [comment]
Please report issues about alpakka components in the alpakka repository: https://github.com/akka/alpakka

> After shutdown, we noticed that the memory is keep increasing and it is never released. 

I don't understand how "after shutdown" you could observe any such event, what do you mean with "after shutdown"? Please add more information about this when opening the ticket in it's right place (the link above)

**Comment by puvanenthiran** [comment]
Thank Ktoso. I have reported in alpakka also. But, I am not getting enough help in alpakka.

To clarify, we have a Spring Rest Application, for each user request, we create ActorSystem &  materializer, process the request using akka stream and then shutdown materializer & terminate akka system at the end of the request.  

We observed the JVM memory keep increasing, not coming down after each request. How do we make akka stream release the memory after request processing?.

**Comment by ktoso** [comment]
> To clarify, we have a Spring Rest Application, for each user request, we create ActorSystem & materializer, process the request using akka stream and then shutdown materializer & terminate akka system at the end of the request.

This is a *terrible* terrible idea. Please read about actor basics: 

> We observed the JVM memory keep increasing, not coming down after each request. How do we make akka stream release the memory after request processing?.

Do not start so many actor systems to begin with! You never need many of them. Just one.

Just call terminate on it.

Please do not cross post questions.
