### ISSUE TITLE
Cluster state diagram has small mistakes (in what is and isnt a leader action)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24848]
The diagram on https://doc.akka.io/docs/akka/2.5/common/cluster.html
has slight mistakes in what is marked a leader action and what isn't.

- the move from Joining to WeaklyUp is marked as leader action but that's false; 
  - it explicitly is designed to NOT be a leader action, since that move needs to happen during unreachability existing -- `Joining members will be promoted to WeaklyUp and become part of the cluster if convergence can’t be reached. Once gossip convergence is reached, the leader will move WeaklyUp members to Up. ` https://doc.akka.io/docs/akka/2.5/cluster-usage.html#weaklyup-members 
- the move from Down to Exiting is NOT marked as leader action but SHOULD BE

**Comment by patriknw** [comment]
Well, it’s a leader action but doesn’t require convergence (unreachable are ok). Note that during net partition there is a leader in each partition, but no convergence.

**Comment by ktoso** [comment]
Hmm... I see, don't document this well enough :-\
