### ISSUE TITLE
[typed, persistence] Add `type EventHandler[State, Event] = (State, Event) ⇒ State`

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24856]
Just to be in sync with `CommandHandler` ...

**Comment by ktoso** [comment]
I would propose making them in sync by removing the `CommandHander` alias,
it makes it seem more advanced than it is -- it is just a "boring plain function", and introducing these aliases makes people think and look for those as actual types -- then being confused that they can't find such class -- we went through this confusion a lot with people in Akka HTTP and it's Route in ScalaDSL

**Comment by hseeberger** [comment]
Actually I like the alias for `CommandHandler`, because it's such a "huge" real type. But I have no strong opinions (other than consistency).

**Comment by ktoso** [comment]
Yeah, I think that's why the type alias was introduced, and I guess opinions will be split in the team, we'll see. Knowing the confusion that `Route` causes I was thinking avoiding an alias would be better.

We'll see what rest of team thinks
