### ISSUE TITLE
Add type alias to ActorMaterializer to typed ActorMaterializer

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24868]
Else the following is not possible:

``` scala
implicit val mat: akka.stream.typed.ActorMaterializer = // Using `Materializer` here doesn't give `shutdown`
  akka.stream.typed.ActorMaterializer()(context.system)
// later
mat.shutdown()
```

**Comment by patriknw** [comment]
ok, makes sense

Would still be somewhat ugly for Java API. One of them must be fqcn.

**Comment by patriknw** [comment]
Migration guide:

Scala:
import akka.stream.typed.ActorMaterializer -> akka.stream.typed.scaladsl.ActorMaterializer

Java:
import akka.stream.typed.ActorMaterializer -> akka.stream.typed.javadsl.ActorMaterializerFactory

**Comment by Dollyg** [comment]
@patriknw 

Is there a way to bind a stream's materialization to an Actor's lifecycle in Typed Actors?

Something like this 
`implicit val mat: ActorMaterializer       = scaladsl.ActorMaterializer()(ctx)`

**Comment by patriknw** [comment]
@Dollyg I think that is missing. Created issue https://github.com/akka/akka/issues/25536
You are welcome to contribute.

**Comment by Dollyg** [comment]
Thanks @patriknw . Will definitely try to contribute.
