### ISSUE TITLE
RateLimiter patterns

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#24879]
There are needs for RateLimiter pattern support lives in `akka.pattern.Patterns`

**Comment by johanandren** [comment]
When we deprecated the contrib rate limiter we decided that you can do rate limiting easily enough with streams. See https://doc.akka.io/docs/akka/current/project/migration-guide-2.4.x-2.5.x.html#timerbasedthrottler

I think we should add a sample like that in the regular docs though, it was a bit hard to find.

**Comment by Captain1653** [comment]
This issue is quite old. It was mentioned before:

> I think we should add a sample like that in the regular docs though, it was a bit hard to find.

I've found [this rate limit example](https://doc.akka.io/docs/akka/current/stream/stream-cookbook.html#globally-limiting-the-rate-of-a-set-of-streams).

Should this issue be closed?
