### ISSUE TITLE
support unary function in match

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24876]
```
      .match(Tick.class,(msg) -> handleTick())
```

I have to write code like that above, but I do want to write
```
      .match(Tick.class,() -> handleTick())
```
or 
```
      .match(Tick.class,XXX::handleTick)
```
when the message is just a `Tick` singleton object.

**Comment by johanandren** [comment]
That would be a lot of extra API surface compared to the minor inconvenience/slight syntax overhead it would avoid in my opinion, I don't think we should do that.

**Comment by patriknw** [comment]
I agree, not worth it. I would guess that compilation error messages will also become more difficult to understand.

Note that you can use `__` (2 underscore) as a convention for unused.

```java
.match(Tick.class, __ -> handleTick())
```
