### ISSUE TITLE
Fail if ALPN agent is missing

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24872]
We have a nice section in the docs explaining how to get the Jetty ALPN agent, but since it will never work without it (when running "normal" HTTP2) could we perhaps fail or log an error if the ALPN agent is missing?

**Comment by patriknw** [comment]
@johanandren wrong repo? should be akka-http?

**Comment by johanandren** [comment]
Ah, yes, too many tabs open. Sorry.
