### ISSUE TITLE
add description about message passing latency.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#24903]
we need message passing latency on the same box `ping-pong` vs method invocation, means the time between sending a message to another actor and the time just before starting to handle it.

the other actor has an empty mailbox.

**Comment by hepin1989** [comment]
The mailboxs pages could some performance benchmarks there?

**Comment by patriknw** [comment]
Thanks for suggesting, but we will not include benchmark results in docs. Such would quickly become outdated or not relevant for real use cases. If we would publish such results it would be in blog posts.
