### ISSUE TITLE
should metion `akka.scheduler.tick-duration` 's default value is 10ms.

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#24901]

**Comment by patriknw** [comment]
Default values are in reference.conf and included in the configuration doc section. We avoid duplication the values into written text because then they will soon become outdated and can’t be trusted.

**Comment by hepin1989** [comment]
via paradox including

**Comment by patriknw** [comment]
Reference conf are included in https://doc.akka.io/docs/akka/current/general/configuration.html#listing-of-the-reference-configuration

**Comment by raboof** [comment]
It might be neat if we could create a paradox directive that finds the relevant entry in the reference.conf and includes it, including default value and comment. So in the `.md` something like

```
  @@reference[akka.scheduler.tick-duration]
```

Could automatically turn into:
```
akka {
  # Used to set the behavior of the scheduler.
  # Changing the default values may change the system behavior drastically so make
  # sure you know what you're doing! See the Scheduler section of the Akka
  # Documentation for more details.
  scheduler {
    # The LightArrayRevolverScheduler is used as the default scheduler in the
    # system. It does not execute the scheduled tasks on exact time, but on every
    # tick, it will run everything that is (over)due. You can increase or decrease
    # the accuracy of the execution timing by specifying smaller or larger tick
    # duration. If you are scheduling a lot of tasks you should consider increasing
    # the ticks per wheel.
    # Note that it might take up to 1 tick to stop the Timer, so setting the
    # tick-duration to a high value will make shutting down the actor system
    # take longer.
    tick-duration = 10ms
}
```

**Comment by ktoso** [comment]
That would be an excellent directive, please ticketify it specifically @raboof

**Comment by raboof** [comment]
Added as #24965

**Comment by raboof** [comment]
So to re-cap: having the default in the docs can be useful, but it's not _that_ useful that we want to do it by introducing duplication or littering the reference.conf with paradox markers everywhere. Somehow including it automatically could be interesting (but is not something we're currently planning to do so contributions welcome).

**Comment by richardimaoka** [comment]
Should this issue be closed as #24965 was raised?

**Comment by ktoso** [comment]
No, since this ticket is about a docs improvement; and the other one is about a paradox feature

**Comment by Captain1653** [comment]
This is a quite old issue. The PR was closed.

There is an explanation in the `reference.conf`:
<img width="853" alt="Screenshot 2023-08-24 at 20 11 38" src="https://github.com/akka/akka/assets/4740207/36fb93a3-d669-4175-baea-08364812624f">

Should this issue be closed?
