### ISSUE TITLE
Nodes not rejoining after cluster spilt

### ISSUE THREAD

**Issue by makesh91** [akka/akka#24914]
Hi,

We use akka v2.4.10 and have 4 nodes in an akka cluster (ex. A, B, C, D) and we observe the below cluster split scenario.

    When the actor system from a node (i.e D) gets restarted, we received “Associate timed out after [15000 ms]” message when tried connecting with other nodes.
    The cluster.state().members() contains only node D when the actor system is completely started.

    Is there a way to get the node D back into the cluster (where A, B and C present) ?

    We receive “Associate timed out after [15000 ms]” message during Association failure for a node from akka.remote.ReliableDeliverySupervisor.

    Guess, the timeout value is set as default by Akka, is there any setting to configure this time out value manually (i.e from configuration file) ?

Thanks,
Makesh

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).
