### ISSUE TITLE
I can't find   AbstractActorWithTimers in package

### ISSUE THREAD

**Issue by avzlobin79** [akka/akka#24919]
Hello.Version:2.5.12
I use code:
`public class MyActor extends AbstractActorWithTimers {
    
    private static Object TICK_KEY = "TickKey";
    private static final class FirstTick {
    }
    private static final class Tick {
    }

    public MyActor() {
      getTimers().startSingleTimer(TICK_KEY, new FirstTick(), Duration.ofMillis(500));
    }

    @Override
    public Receive createReceive() {
      return receiveBuilder()
        .match(FirstTick.class, message -> {
          // do something useful here
          getTimers().startPeriodicTimer(TICK_KEY, new Tick(), Duration.ofSeconds(1));
        })
        .match(Tick.class, message -> {
            // do something useful here  
        })  
        .build();
    }
  }`
But He dont work.I can't find class AbstractActorWithTimers  in akka.actor

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on the gitter channel or https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

**Comment by ktoso** [comment]
Make sure you use the latest version of akka
