### ISSUE TITLE
Source.unfoldResource runs `close` twice.

### ISSUE THREAD

**Issue by Idorobots** [akka/akka#24924]
Consider the following snippet:

```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Sink, Source}
import akka.stream.testkit.scaladsl.TestSink

object Test extends App {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()

  var count = 0

  def makeSource = {
    Source.unfoldResource[Int, Int](
      () => {
        count = count + 1
        println("obtaining: " + count)
        count
      },
      c => if(c > 5) {
        println("Limit reached!")
        throw new Exception("")
      } else {
        Some(c)
      },
      c => {
        println("releasing: " + c)
        count = count - 1
      }
    ).map(_ * 2)
     .recover { case e => 23 }
  }

  1.to(10).map(_ => makeSource).foreach { s =>
    val p = s.runWith(TestSink.probe)
    p.request(1) // Generate demand.
  }

}
```

Output:

```
obtaining: 1
obtaining: 2
obtaining: 3
obtaining: 4
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
releasing: 6
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
releasing: 6
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
releasing: 6
```

The code creates 10 streams, each of which tries to obtain a resource using `Source.unfoldResource`, does some processing (here a `map`) and `recovers` from any errors. The resource is limited, so after a certain point some of these streams fail to obtain the resource  resulting in `close` passed to `Source.unfoldResource` being called twice in every such case.

Is this the expected and correct behaviour? I would expect it to relese the resource only once and the correct output to be the following:

```
obtaining: 1
obtaining: 2
obtaining: 3
obtaining: 4
obtaining: 5
obtaining: 6
Limit reached!
releasing: 6
obtaining: 6
Limit reached!
releasing: 6
obtaining: 6
Limit reached!
releasing: 6
...
```

Also, moving the `if` further downstream as in the following snippet makes it work as expected:

```scala
// ...
  def makeSource = {
    Source.unfoldResource[Int, Int](
      () => {
        count = count + 1
        println("obtaining: " + count)
        count
      },
      Some(_),
      c => {
        println("releasing: " + c)
        count = count - 1
      }
    ).map { c =>
      if(c > 5) {
        println("Limit reached!")
        throw new Exception("")
      } else {
        c * 2
      }
    }
    .recover { case e => 23 }
  }
// ...
```

**Comment by johanandren** [comment]
There could potentially be a bug in the stage, but note that your reproducer for sure has a bug - you must not have mutable state that you touch from multiple threads, which is exactly what is happening with the `count` var, additionally `+=` and `-=` are not atomic operations, to create a correct reproducer you should use an `AtomicInteger`. Please update the reproducer and see if you can still see multiple closes.

**Comment by johanandren** [comment]
Sounds like a bug then, thanks for verifying. Would you be up for giving submitting a fix a chance?
