### ISSUE TITLE
Stream fold and friends are not usable with mutable collections

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24971]
Created from this forum question: https://discuss.lightbend.com/t/beginner-question-regarding-splitwhen-groupby-followed-by-fold/804

`fold`, `foldAsync`, `scan` and `scanAsync` all take a zero element that is expected to be immutable, for `scan` this makes sense as the aggregate-object is passed downstream for every element, but for fold where it is only passed downstream when done, a mutable aggregate may make sense (`ArrayList` in the forum question).

For `scan` and `scanAsync` we should make a clear warning in the docs that the zero value must not be mutable.

For fold I'm not sure, should we provide a factory version as well? `fold(() => T)((T, Out) => T)`, especially for the Java side of things where immutable collections require a third party library this would be nice. If not we should clearly document that this zero should be immutable as well.

**Comment by markoutso** [comment]
This should be part of the documentation.

**Comment by johanandren** [comment]
I agree, let's start with that.
