### ISSUE TITLE
Artery/TCP compession actor/memory leak

### ISSUE THREAD

**Issue by luben** [akka/akka#24973]
I have noticed that after an actor is stopped and remove system association is closed, the compression tables still hold a strong reference to the dead actor preventing its garbage collection. This leads to memory leaks.

Please see reproduction code at: https://gist.github.com/luben/b78043f54708e746c5e32cd466b36af0

The behaviour is observed if you start the "LeakyServer" and "LeakClient". If compression is disabled (start the "NonLeakyServer" instead) the leak is not observed anymore.

**Comment by patriknw** [comment]
It holds `ActorRef` instances either by the compression tables (which will be replaced) or by the LRU cache `ActorRefResolveCache`. Or do you see something else?

Also, note that the `ActorRef` is a rather small object when the actor has been terminated. It doesn't reference the `Actor` itself anymore.

**Comment by patriknw** [comment]
ok, sounds good to investigate

**Comment by patriknw** [comment]
See also https://github.com/akka/akka/issues/24972
