### ISSUE TITLE
Messages scheduled with Timers mix in ignore NotInfluenceReceiveTimeout trait 

### ISSUE THREAD

**Issue by alatvian** [akka/akka#24989]
akka version: Found in 2.5.6 (and up)

Actor messages that extend the trait `NotInfluenceReceiveTimeout` do influence the Receive Timeout when sent from an actor to itself when scheduled using the `Timers` mix in. 

I would expect that Actor messages that extend `NotInfluenceReceiveTimeout` scheduled with the `Timers` mix in would not reset the actor Receive Timeout based on the documentation [here](https://doc.akka.io/docs/akka/2.5.11/actors.html#receive-timeout), "Messages marked with NotInfluenceReceiveTimeout will not reset the timer. This can be useful when ReceiveTimeout should be fired by external inactivity but not influenced by internal activity, e.g. scheduled tick messages."

I created an example failing test created to show this based on the examples within [ReceiveTimeoutSpec.scala](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ReceiveTimeoutSpec.scala):

```
"get timeout while receiving NotInfluenceReceiveTimeout messages scheduled with Timers" taggedAs TimingTest in {
      val timeoutLatch = TestLatch()

      class ActorWithTimer() extends Actor with Timers {
        timers.startPeriodicTimer("transparenttick", TransperentTick, 100.millis)
        timers.startPeriodicTimer("identifyTick", Identify(None), 100.millis)

        context.setReceiveTimeout(1 second)
        def receive: Receive = {
          case ReceiveTimeout  ⇒ timeoutLatch.open
          case TransperentTick ⇒
        }
      }

      val timeoutActor = system.actorOf(Props(new ActorWithTimer()))

      Await.ready(timeoutLatch, TestLatch.DefaultTimeout)
      system.stop(timeoutActor)
    }
```

I believe the root cause of the issue is that all messages scheduled with the `Timers` trait are wrapped in a `TimerMsg` case class and this masks and ignores the `NotInfluenceReceiveTimeout` trait of the original message, seen [here](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/dungeon/TimerSchedulerImpl.scala#L49-L54). I think a fix would be to create another `TimerMsg` like case class that also extends `NotInfluenceReceiveTimeout` and use that instead if the original message does extend `NotInfluenceReceiveTimeout`. I can help with a PR if this seems appropriate.

Thanks!

**Comment by patriknw** [comment]
@alatvian Great finding. Would you be able to create a pull request fixing this issue?

**Comment by alatvian** [comment]
@patriknw Here's a PR: https://github.com/akka/akka/pull/24994

**Comment by ktoso** [comment]
Merged in https://github.com/akka/akka/commit/028937f52fce26c4145e1c9ecf7d5567878f981a for 2.5.14
