### ISSUE TITLE
Easing into Streams APIs: Consider Source.run() == Source.runWith(Sink.ignore)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24986]
Topic reminded by @raboof 

> Random topic of the day: is `Sink.ignore` a good name? It of course describes what it does, but that's not _why_ you use it. Not quite sure what to call it instead though :wink:.

After some silly naming ideas, (Sink.nomnomnom 😉), we considered also: 
though just being able to run() on a Source which means Sink ignore would also be fine

For consideration. 

It could shield newcomers from the "I need to ignore to run a source?" confusion, which is a small one, but in first few minutes can build up to "another thing to learn right away".

In teaching, we can ease into "well, now you know `run()` but that's just sugar for `runWith(Sink.ignore)`, there's other kinds of useful sinks".

**Comment by patriknw** [comment]
I like that
