### ISSUE TITLE
Docs: naming consistency on "levels": operators, graphs, stages

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24995]
Nowadays in docs we refer to operators as stages, and to even linear flows as "linear graphs".
All of this is true of course, however it exposes newcomers to the "advanced words" (graph, (graph)stage), while they're only looking at the simple operators.

Proposal:
- **Whenever we talk about operators,** also the "stages overview" etc, we **should only use the word operator.** While it may feel a bit weird to us at first, for newcomers it is what they're both seeing, and looking for in any case.
- **de-emphasise the focus on the word graph** -- again, it scares newcomers and gives impression that akka is geared towards "only the complex graph cases", while in reality it is the very rare case, that we do handle well as well. The word graph should not appear most of the time in any simple linear things, or operator explanations. And if it does, we should link to a page about what a graph is **always**.
- Same about `GraphStage`, we should avoid the term stage and graphstage when talking only about simple operators. The word stage should always link to a doc page that explains "well, all operators are actually stages! and here's the api. You'd use it for custom stuff"

Thanks @agemooij for great proposal around this!

**Comment by ktoso** [comment]
- Also, the words "linear graphs" etc, should be simply "streams"

**Comment by patriknw** [comment]
Merged another PR, any more remaining?

**Comment by richardimaoka** [comment]
I believe #25426 is the last one to go.

**Comment by ktoso** [comment]
Thanks for the help @richardimaoka ! We're done here now, yay :)
