### ISSUE TITLE
doc Move Persistence pages to a dedicated group, similar to stream, cluster, and typed

### ISSUE THREAD

**Issue by richardimaoka** [akka/akka#25011]
Currently "persistence" pages are under the "Actors" grouping.

![image](https://user-images.githubusercontent.com/7414320/39406035-4f400f5e-4beb-11e8-9394-4e3b8a9fda70.png)

I think they deserve a separate group (or is it called directory?) like stream and cluster, so what I suggest are:

- split persistence.md into a few separate pages as it is 1500 lines currently
- move persistence related pages to a new directory src/main/paradox/persistence
- set up index.md in the new directory

Does that make sense?

**Comment by ktoso** [comment]
They are actors though hm... I get the suggestion but would suggest waiting with any restructuring here for a while, we may want to restructure persistence some more later on, due to typed, multidc etc etc.

**Comment by johanandren** [comment]
I like the idea and I think it is a reasonable category, but as Konrad says, let's wait until the soon-to-be-worked-on persistence related things are done.

**Comment by richardimaoka** [comment]
I see, thanks for the info. Let me close the issue for now, and if needed, let's reopen this later.
Will keep eyes on other persistence related stuff and will take up some when I can.
