### ISSUE TITLE
Source.flattenConcat and Source.flattenMerge(breadth: Int)

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#25024]
Today I realised that there is no `flatten` method on `Source`. I had a `Source[Source[O, M]]` and my first reaction was to look for a `flatten` method. I end up using `flatMapConcat(identity)`.  

I had short chat with @johanandren and it seems that the main reason for that is because there are two `flatMap` variations in Source, `flatMapConcat` and `flatMapMerge`. So, I would like to suggest two new operators: 

```scala
def flattenConcat[T, M](): Repr[T] = flatMapConcat(identity)
def flattenMerge[T, M](breadth: Int): Repr[T] = flatMapMerge(breadth, identity)
```
I believe that `flatten` is a well-know concept. Users not familiar with it can learn it very easily. It's less obvious, especially for beginners, that you can define `flatten` in terms of `flatMap` and `identity`. Therefore I think it makes sense to have it in the library.

I'm happy to send a PR.

**Comment by patriknw** [comment]
What would it do when `T` is not a `Source`?

**Comment by renatocaval** [comment]
Well, the same way it is done with `Future`: 
`def flatten[S](implicit ev: T <:< Future[S]): Future[S]`

**Comment by renatocaval** [comment]
For the same reason it was introduced in `Future`, for the reason I mentioned above, not everybody knows or understands that `flatten` can be defined in terms of `flatMap` and `identity` and because it's a common thing to have whenever there is a `flatMap` or similar method.

Moreover, there is not a huge complexity fee to add it. Like many other operators, it's just a convenience. `flatMapConcat` is also defined in terms of `flatMapMerge`. It's a convenience when we want to merge using breadth 1, no?
