### ISSUE TITLE
Handle a negative value returned by Math.abs()

### ISSUE THREAD

**Issue by piotrromanski** [akka/akka#25034]
`Math.abs(Integer.MIN_VALUE)` returns a negative value. It can negatively impact how bucket indexes are calculated, for example: `(Math.abs(x.hashCode()) % size)` can return a negative bucket index. To fix it we need to, for example, either
1. change order of operations: `(Math.abs(x.hashCode() % size))`
2. or just remove first bit: (x.hashCode() & 0x7FFFFFFF) % size - this will change the current semantics

**Comment by patriknw** [comment]
@piotrromanski  That's an interesting observation. For cluster sharding we can't change the end result of for example `HashCodeMessageExtractor`. That would be a disaster when doing a rolling upgrade. So I don't see how we could change this? What is the practical implication? It could be one more shard than specified (the size) and it will only contain the entities that hash to Int.MinValue?
