### ISSUE TITLE
Upgrading Homebrew formula

### ISSUE THREAD

**Issue by ilovezfs** [akka/akka#25046]
The current version in Homebrew is
https://downloads.typesafe.com/akka/akka_2.11-2.4.17.zip
https://github.com/Homebrew/homebrew-core/blob/master/Formula/akka.rb#L4

This repo says the latest is actually 2.5.12

What is the new url for 2.5.12?

**Comment by patriknw** [comment]
We don't have a zip download for Akka 2.5.x because we recommend using Akka with a build tool. It doesn't make much sense to me to have a Homebrew forumula of Akka since it's not something you install.

**Comment by ilovezfs** [comment]
@patriknw we could consider removing it. It has been in Homebrew since 2012 though https://github.com/Homebrew/legacy-homebrew/pull/12042

**Comment by patriknw** [comment]
If it would be anything I think it would be better that it just "installed" the Quickstart example project: https://developer.lightbend.com/guides/akka-quickstart-scala

The direct download URL of such example zip is: https://example.lightbend.com/v1/download/akka-quickstart-scala?name=akka-quickstart-scala

Perhaps it can include sbt and java dependencies?

**Comment by chbatey** [comment]
I don't think it is worthwhile putting anything in homebrew. We already have gitter8 / techhub
