### ISSUE TITLE
Clearer delineation between effects and side-effects

### ISSUE THREAD

**Issue by debasishg** [akka/akka#25041]
Looks like we need to be a bit more consistent in differentiating between effects and side-effects. We have the following hierarchy:

```scala
abstract class ChainableEffect[Event, State] extends EffectImpl[Event, State]

private[akka] case class SideEffect[Event, State](effect: State ⇒ Unit) extends ChainableEffect[Event, State]

private[akka] case object Stop extends ChainableEffect[Nothing, Nothing]
```

And then in `EffectImpl` we have 

```scala
override def sideEffects[E >: Event]: im.Seq[ChainableEffect[E, State]] = Nil
```
Why `sideEffects` return a collection of `ChainableEffect` and not `SideEffect` ? Looks like we don't have any other `ChainableEffect` in the implementation. And it's not meant for user extension as well. Can we make `Stop` a `SideEffect` as well and get rid of this hierarchy ? Also then we have the base class as `SideEffect`, which makes it a completely different entity than an `Effect`.

**Comment by raboof** [comment]
I agree this is confusing.

I don't think we can have `SideEffect` and `Effect` as completely separate base classes: we'd like to allow both `input => Effect.stop` and `input => (...); Effect.persist(evt)`, so `Stop` and `Persist` need to have a common supertype.

Do you think it would be reasonable to allow:

```
Effect.persist(foo)
  .andThen(Effect.sideEffect(_ => println("hi"))
  .andThen(Effect.persist(bar))
  .andThen(Effect.sideEffect(_ => println("ho"))
  .andThen(Effect.stop))
```
? So far we've discouraged this, and made it impossible to 'mix' the 'persist' effects and other ('chainable') effects. If we allow the above we could simplify the types, otherwise we should probably just improve naming in a couple of places?

**Comment by debasishg** [comment]
@raboof I have one concern with the code snippet that u mentioned .. `Effect.sideEffect` sounds like an oxymoron to me. Effect is something algebraic, side effect is NOT. And `Stop` looks like a side-effect to me.

**Comment by raboof** [comment]
We use `Effect` here in the meaning of 'description of an action to be interpreted by an interpreter later'. 

when interpreting `Persist`, the interpreter persist the event (which is included as a parameter)
when interpreting `Stop`, the interpreter stops the actor
when interpreting `SideEffect`, the interpreter executes some code (which is included as a parameter).

I agree `SideEffect` might not be a good name (though I can't quite come up with something better, `Callback`, `Do`, `Run`, `Execute` all seem to have other unintended associations), but it doesn't seem too far-fetched to consider it an `Effect`.

This naming aside, if we rename 'sideEffect' to 'do' for the sake of argument, I wonder if it makes sense to allow:
```
Effect.persist(foo)
  .andThen(Effect.do(_ => println("hi"))
  .andThen(Effect.persist(bar))
  .andThen(Effect.do(_ => println("ho"))
  .andThen(Effect.stop))
```

So far we have discouraged users from creating such chains, instead nudging users to move logic to the `eventHandler` (as this is still the `commandHandler`) or sending messages. Do you think the above (mixing persisting and 'custom' effects in a chain) is something we should support?

**Comment by raboof** [comment]
We don't support parallel effects - and I don't think we should: this is a persistent actor, so modeling parallel actions should be done using mechanisms native to actor systems: message passing. I suspect making the effect system too powerful here would lead to people writing hard to understand actors.

With respect to handling exceptions, I think they are considered as actor failures, and as such passed to the supervisor (which will most likely throw away the state, restart the actor and recover the state from the journal, and then resume processing at the next command).

**Comment by debasishg** [comment]
@raboof 👍 so long we are clear on the semantics ..

**Comment by patriknw** [comment]
I'm trying to understand what we should do here. Here is my thoughts (not sure I have covered everything).

I don't think we should support multiple chained `persist`. I fear callback api hell.
```
Effect.persist(foo)
  .andThen(Effect.do(_ => println("hi"))
  .andThen(Effect.persist(bar))
  .andThen(Effect.do(_ => println("ho"))
```

It should only be allowed to start with one of `persist`, `persistAll`, `none`, `unhandled` or `stop`. After that these should not be allowed to use again. All those should be of type `Effect` (meaning that `stop` should change.

Those can then be chained with zero or more `andThen(State => Unit)` or `andThenStop`.

I don't think it has to be more advanced than that.

`ChainableEffect` is in the `internal` package but still exposed in public API at a few places. Isn't the name `Chainable` confusing. It's more `ChainedEffect`? Something you add after initial `persist` effect.

So in public API we only have `Effect` and `ChainedEffect`.

There is one more for advanced usage:
```
 def persist[Event, State](events: im.Seq[Event], sideEffects: im.Seq[ChainableEffect[Event, State]]): Effect[Event, State]
```

Usage is illustrated in `PersistentActorCompileOnlyTest`, see `val commonEffects`. This seems to be for very advanced usage, but we could leave it for that purpose (although I doubt that it will ever be used).

**Comment by patriknw** [comment]
cc @renatocaval

**Comment by debasishg** [comment]
a few thoughts .. (cc @renatocaval, @patriknw, @raboof)   

- I am just wondering if we should rename `Effect` to `SideEffect` because that's what they are `(State => Unit)`
- Since we only plan to support sequential chaining, why not add `flatMap` to `SideEffect` and allow sequential composition through for-comprehensions. Seems more natural.
- Some refactoring of packages (I discussed this earlier). Any abstraction in `internal` should NOT depend on the respective `dsl` packages. The general dependency should be "dsls depend on internal packages" and not the other way around. The dsl packages should provide a thin veneer of APIs over the underlying implementation in `internal`. All implementations in `internal` should be shared between the Java and Scala DSLs.

**Comment by patriknw** [comment]
> I am just wondering if we should rename Effect to SideEffect because that's what they are (State => Unit)

You mean `ChainableEffect` (`ChainedEffect`). We can do that, but we still need the internal distinction between `andThen(state => Unit)` and `andThenStop` since those are interpreted differently.

**Comment by debasishg** [comment]
I was thinking more in terms of implementing a very lightweight IO monad (something like cats-effect IO, but much simpler). And execute all side-effects (`persist`, `none`, `stop`, `unhandled` etc.) within the IO monad. Being a monad, we will have `flatMap` which can be used to chain all side-effect invocations. Then we can get rid of all classes like `Effect`, `EffectImpl`, `EffectFactories`, `ChainableEffect`, `CompositeEffect` etc.

Just thinking aloud .. cc @patriknw ..

**Comment by patriknw** [comment]
I'm in favor of keeping it limited and not support chaining in arbitrary ways.

I think it will mostly be used like this:
```
Effect.persist(evt)
  .andThen(state => cmd.replyTo ! Handled(state.id))
```

**Comment by renatocaval** [comment]
I agree that we should keep it limited. The main reason for me is that being part of the persistence API, it should focus on its main purpose, the fact that something is about to be persisted (or not).

That said, I agree that it should start with `persist`, `none` or `unhandled` and these can't be repeated. It's like a branching, we choose what we want and we go for it. 

In case of `stop` what we want to express is that after handling the incoming command we want to stop the actor, therefore I think it makes more sense to write one of the following.

```
Effect.persist(myEvent).andThenStop()
Effect.unhandled.andThenStop()
Effect.none.andThenStop()
Effect.stop()  // suggar for Effect.none.andThenStop()
```

Preferably, `andThenStop()` should be the last in the chain. If we can enforce it, that will be great.  

This will produce a very declarative style:

```
Effect
  .persist(evt)
  .andThen(state => cmd.replyTo ! Handled(state.id))
  .andThenStop()
```

This makes it clear the order that things will happen. We persist and then we do stuff.

**Comment by renatocaval** [comment]
@raboof can you clarify this:
> ...instead nudging users to move logic to the `eventHandler`

I don't think this is what we should do, if I'm understanding you correctly. The `eventHandler` should be pure and only modify the state. We don't want to run side-effects over and over again on each actor re-instantiation, right?

**Comment by raboof** [comment]
The complete sentence was:

> nudging users to move logic to the `eventHandler` (as this is still the `commandHandler`) or sending messages

With 'logic' I meant updating the state - I completely agree side-effects should not be part of the `eventHandler`.

**Comment by renatocaval** [comment]
On the topic of naming things, I like `Effect`, but this discussion made me wonder if that name will be clear to everybody. In the end, we are declaring the actions to be taken: 'persist this', 'run this side-effect', 'stop the actor', etc.

Would it be better to call it `Actions` instead and avoid the confusion with effect and side-effect?

```
Actions
  .persist(evt)
  .andThen(state => cmd.replyTo ! Handled(state.id))
  .andThenStop()
```

or 

```
Actions.none
```

Does it the intention become clearer? WDYT?

**Comment by debasishg** [comment]
I was trying to avoid the name `Effect` as by definition, an `Effect` is supposed to be algebraic. While the way we define things here. it's obviously not algebraic, rather side-effecty. `Actions` can be a better name as it has a conveniently overloaded connotation.

However in the above chaining, what happens if the entire sequence succeeds *partially* ? Suppose the `persist` goes through, but the next action in chain fails ..

**Comment by renatocaval** [comment]
That's the thing. `persist` is the main operation. If `persist` fails, for instance, DB not reachable, the whole fails. If `persist` succeeds, but one of the side-effects fails, too bad. Basically, `andThen` is best-effort and has at-most-once semantics. The core is the `persist` operation. 

This is an important point, in my opinion, and I have seen people getting misled by this. Not in akka persistence typed, but in Lagom. Lagom has a `persist` method to which you can pass an `afterPersist` callback to be executed, well, after persisting. 

I once had someone that took a hard time to accept that publishing something in Kafka in the `afterPersist` method was **not** happening on a transaction together with the events in the journal and that the event could be persisted, but the `afterPersist` could fail.

We should make it clear from the docs that whatever happens in the `andThen` is not guaranteed and has at-most-once semantics.

What is not clear to me is if the actor should stop if an `andThen` fails. My first guess is no, it should not stop. It should not stop because the main operation succeeded. The incoming command was validated and produced one or more events. That's what counts. Once the events are in the journal we have facts that will affect the system further on. Whatever was added to an `andThen` that was not executed is part of the past and can't be recovered.

**Comment by chbatey** [comment]
Going to make a subset of the changes discussed while doing https://github.com/akka/akka/issues/25042

I won't rename Effect to Action, I think either work well. Given the context of this being Akka I don't think many users will interpret Effect as with its usage in Haskell/Scalaz/Cats.

The two public types become:
`Effect` - The "main effect, typically persist, none, stop or unhadles` No change but will make a chained effect not an effect to clear things up.
`ChaninedEffect` - Currently a callback/side effect and Stop.

Chained effects can be added to run sequentially after an Effect. Effects can not be added to an Effect i.e. just one persist.

The weird case is `Effect.stop` which is both a "main effect" and chained after. I plan to type Effect.stop to `Effect`. If users want to store away some chained effects that include stop we can add another factory method `ChainedEffect.stop` which types it as a `ChanedEffect`

**Comment by chbatey** [comment]
Actually after re-reading all of this `Stop` doesn't need to be a special case it can just be `none.andThenStop` as suggested by @renatocaval
