### ISSUE TITLE
Log a message when a node receives or loses leadership status

### ISSUE THREAD

**Issue by raboof** [akka/akka#25047]
Akka clusters are masterless during regular operation, but there is a 'leader' role which identifies a node that will perform some administrative tasks when the gossiped cluster membership information is converged. This role can move from node to node as members join or leave the cluster. More details at https://doc.akka.io/docs/akka/current/common/cluster.html#leader

It might be nice to keep track of whether the current node is the leader in ClusterDaemon.scala, and log a message when a node receives or loses leadership status, to help when analyzing logs.

**Comment by patriknw** [comment]
sounds good, can probably be added to [def leaderActions](https://github.com/akka/akka/blob/master/akka-cluster/src/main/scala/akka/cluster/ClusterDaemon.scala#L1020)
