### ISSUE TITLE
Ordering of Side-effects in akka-persistence-typed

### ISSUE THREAD

**Issue by debasishg** [akka/akka#25042]
In https://github.com/akka/akka/blob/master/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EffectImpl.scala#L19 we have a collection of SideEffect being returned, which will be executed downstream. 

Is the client free to execute these in any order ? Or do we need to enforce any semantics on ordering of side-effects ? e.g. we have `Seq[SideEffect]`, which means the client is free to invoke the side-effects in any order. They may chain them in sequence (monadic) or they may want to apply them in parallel (applicative). Is this the intention ? The ordering is left to the user to decide. But in our implementations do we have any assumption that the side-effects will have to be invoked in sequence ?

Also what happens if any of these side-effects throws ?

**Comment by raboof** [comment]
We intend to run these side effects sequentially - though this is indeed not obvious, so we should definitely make that more clear.

When one of the side-effects throws I'd expect this to be treated like an actor faliure, to be handled by the supervisor. I would have to verify whether that is indeed the case, though - and document it as well ;).
