### ISSUE TITLE
Contradictory OSGi meta data for akka-stream (2.5.12)

### ISSUE THREAD

**Issue by oheger** [akka/akka#25055]
Hi,

I am having trouble deploying akka-stream_2.12-2.5.12.jar in an Apache Felix OSGi container because of a version conflict for scala.util.parsing.combinator. In the Import-Package declaration a version range of [1.0.4,1.1.0) is declared, so the version must be before 1.1.0. However, the sslconfig bundle (which is explicitly referenced in version 0.2.3 via a Require-Bundle header) also imports this package, but in a version that must be >= 1.1.0.

While OSGi may be able to handle this, I have failed so far to get this working. Even if I deploy the parsing combinator module in both versions 1.1.0 and 1.0.6, Felix reports a mismatch with packages and their uses relationship.

I was able to work around the problem by changing the import declaration for scala.util.parsing.combinator in akka-stream to also accept a version >= 1.1.0. This seems to be compatible. So maybe the conflict can be resolved by referencing the new version directly?

**Comment by patriknw** [comment]
Can you please open a PR fixing the issue?

**Comment by oheger** [comment]
I will try to come up with a PR.

However, it is not clear to me why there is this Require-Bundle header; normally the package imports should be sufficient. I guess it is there for a specific reason, as this is normally not considered best practice in OSGi. Could somebody give me a hint before I break something?

**Comment by ktoso** [comment]
> I guess it is there for a specific reason, as this is normally not considered best practice in OSGi. Could somebody give me a hint before I break something?

We're not really experts in OSGi and its support is mostly contributed by external contributors, so it may well be that it was added just so... This also kind of explains the state of OSGi in Akka, it is fixed when people fix it -- not actively maintained or tested by us.
