### ISSUE TITLE
Allow for different overflow strategies for `BroadcastHub.sink`

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#25069]
Currently the upstream source is implicitly backpressured once the buffer is full. It would be useful to have different overflow strategies, e.g. failing the slow consumer(s).

**Comment by johanandren** [comment]
Could the use case with failing too slow consumers be handled by putting a backpressure timeout first in the consumers perhaps?

**Comment by Captain1653** [comment]
This issue is quite old and had not any updates for 5 years.

Should this issue be closed?

**Comment by johanandren** [comment]
Let's close since an upstream back pressure timeout is a reasonable solution
