### ISSUE TITLE
StreamRefsProtocol inherit from Serializable?

### ISSUE THREAD

**Issue by dispalt** [akka/akka#25073]
I am running into a multiple serializer issue with `StreamsRef` using the vanilla `chill-akka` settings, and I was looking through other protocols (artery, cluster, etc) and they all seem to inherit from `Serializable`.  Is this potentially the source of the issue?

The error:

```
Multiple serializers found for [akka.stream.impl.streamref.StreamRefsProtocol$SequencedOnNext], choosing first of: [com.twitter.chill.akka.AkkaSerializer, akka.stream.serialization.StreamRefSerializer]
```

**Comment by dispalt** [comment]
Sure thing.

**Comment by dispalt** [comment]
I actually completely spaced on it, im probably 2 weeks out from being able to work on it.

**Comment by brabo-hi** [comment]
Same issue:
`serializers {
            kryo = "com.twitter.chill.akka.AkkaSerializer"
        }
     ` 
` serialization-bindings {
            "java.io.Serializable" = kryo
        }`

> Multiple serializers found for [akka.stream.impl.streamref.StreamRefsProtocol$OnSubscribeHandshake], choosing first of: [com.twitter.chill.akka.AkkaSerializer, akka.stream.serialization.StreamRefSerializer]
