### ISSUE TITLE
Add Scoverage to the build

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25075]
Probably not run it always, but we can have one of the nightly jobs do it.

See https://github.com/lightbend/cinnamon/pull/1134

When I quickly tried it a few weeks ago there was some streams stress test that didn't work with Scoverage.

One challenge might be to also enable it for multi-jvm tests and preferably get one single report when all tests have been run.

**Comment by helena** [comment]
@patriknw I added Scoverage to the original PR for https://github.com/akka/akka/issues/26206, which in this new WIP will be a separate commit.

**Comment by helena** [comment]
Also for jenkins versus just the SBT additions
* https://wiki.jenkins.io/display/JENKINS/Scoverage+Plugin
* https://plugins.jenkins.io/scoverage

**Comment by helena** [comment]
1. Finish configuring new Jenkins job: akka-nightly-scoverage
2. Push changes and test in CI on working branch

**Comment by helena** [comment]
Resolved in https://github.com/akka/akka/issues/26206 by [its PR](https://github.com/akka/akka/commit/3f12d356942107913c8ebe0054a19d89ece41632)

**Comment by helena** [comment]
Also resolved by https://github.com/akka/akka/issues/26445
