### ISSUE TITLE
Add a Done.done() convenience API for Java

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#25083]
[`akka.Done`](https://doc.akka.io/japi/akka/current/akka/Done.html) is quite convenient to use from Scala as a singleton object. In Java, you need to use `Done.getInstance()` instead, which is rather verbose. Statically importing the `getInstance()` method loses clarity.

Proposal: add a `Done.done()` static method that is equivalent to `Done.getInstance()`. Even fully-qualified, it is shorter, and it is friendly to static import.

Question: as part of this, should `Done.getInstance()` be deprecated, or kept as an equal alternative?

**Comment by TimMoore** [comment]
I can send a PR when I get spare time for this... just wanted to record an issue for discussion first. I already discussed briefly with @patriknw.

**Comment by TimMoore** [comment]
Might as well do the same for `NotUsed` and other singleton objects... searching through the code, there are quite a few of these.

**Comment by ktoso** [comment]
Sounds okey to apply to Done and NotUsed byt not sure about globally applying it all over the place, sounds good? :)

**Comment by patriknw** [comment]
I agree, let's do it for `Done` and `NotUsed`.

Regarding deprecation; while I dislike having multiple APIs for the same thing it might hurt too many users to deprecate `getInstance` without a motivating value.

When not using static import I think `Done.getInstance()` reads better, so I don't think we should update documentation examples. If there is some specific example that benefits from using the static import it's fine to update that.

**Comment by TimMoore** [comment]
Sounds good. Thanks for the feedback!
