### ISSUE TITLE
Behavior.wrap does not match StoppedBehavior(OptionVal.Some(behavior))

### ISSUE THREAD

**Issue by kyal** [akka/akka#25082]
When using an intercepted behavior and returning `stopped(postStop)` the call to Behavior.wrap will not pass the `StoppedBehavior(OptionVal.Some(postStop))` through to `ActorAdapter.next(...)` and instead will re-wrap it as if it were not a terminal behavior. As a result `context.stop` is never invoked and it does not work as designed. The error is in Behavior.scala line 250:
```
private[akka] def wrap[T, U](currentBehavior: Behavior[_], nextBehavior: Behavior[T], ctx: ActorContext[T])(f: Behavior[T] ⇒ Behavior[U]): Behavior[U] =
    nextBehavior match {
      case SameBehavior | `currentBehavior` ⇒ same
      case UnhandledBehavior                ⇒ unhandled
      case StoppedBehavior                  ⇒ stopped // ERROR: only matches if no post stop behavior is specified. needs to match the the type instead of the singleton
      case deferred: DeferredBehavior[T]    ⇒ wrap(currentBehavior, start(deferred, ctx), ctx)(f)
      case other                            ⇒ f(other)
    }
```

**Comment by patriknw** [comment]
Thanks for reporting. Feel free to open PR if you know how to fix it.
