### ISSUE TITLE
Distributed data docs typo

### ISSUE THREAD

**Issue by Camsteack** [akka/akka#25111]
Hi,

While going through the 2.5.12 docs for distributed data, there seem to be a typo around the `write-behind` property. In the documentation we can read :

`akka.cluster.distributed-data.lmdb.write-behind-interval = 200 ms`

Where I believe it should be

`akka.cluster.distributed-data.durable.lmdb.write-behind-interval = 200 ms`

I got stuck on that for a bit so I think it could be useful and easy to fix, except if I am mistaken.

Cheers.

**Comment by raboof** [comment]
Hi - that seems to be missing there indeed - good catch, thanks!

Would you be interested in PR'ing against https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/distributed-data.md ?

**Comment by Camsteack** [comment]
Will do !

**Comment by Camsteack** [comment]
This issue has been fixed by #25246 and can be closed.
Thanks

**Comment by raboof** [comment]
Thanks again for the PR!
