### ISSUE TITLE
Missing an actor context in typed Java receive builder

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25118]
Building a `MutableBehavior` that want's to use the context (log for example) requires having a context field and bootstrapping the behavior with a `Behaviors.setup` which is a bit boilerplatey. Would be nice if we could have overloads or something that injects context per message.

Didn't think too long about if this would conflict or cause some form of type chaos, but wishing for something like:
```
receiveBuilder()
  .onMessage(MyMessage.class, (ctx, message) -> ...)
  .build()
```

**Comment by patriknw** [comment]
The thinking was that since `MutableBehavior` should anyway be created via a `setup` it should take the context as constructor parameter and then everything inside has it in scope.

**Comment by johanandren** [comment]
Ah, alright, I had a feeling I had seen/talked about this before but couldn't remember. Thanks for having a better memory than me.
