### ISSUE TITLE
lastSequenceNr accessible from PersistentBehavior

### ISSUE THREAD

**Issue by pawelkaczor** [akka/akka#25113]
While `lastSequenceNr` is exposed by the untyped PersistentActor, it is missing in the typed PersistentBehavior.   

For logging purposes I would like to access `lastSequenceNr` from within a callback function registered as a side Effect in PersistentBehavior:

```java
public abstract class Eventsourced<C, E, S> extends PersistentBehavior<C, E, S> {
	protected Effect<E, S> persist(ActorContext<C> ctx, E event) {
		return Effect().persist(event).andThen(s -> logEvent(ctx, event));
	}
}
```

**Comment by patriknw** [comment]
That's a good point. Wonder how we should support that? Do we have to make a special `PersistentActorContext`?

**Comment by ktoso** [comment]
Separate `PersistentActorContext`may be some additional "meh" work but would feel the most natural 👍

**Comment by pawelkaczor** [comment]
Thanks :-)
