### ISSUE TITLE
Failed: UnfoldResourceSourceSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25121]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5991/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/

https://jenkins.akka.io:8498/job/akka-nightly/5506/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/

https://jenkins.akka.io:8498/job/akka-multi-node/2767/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/

https://jenkins.akka.io:8498/job/akka-nightly/5495/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/

```
Error Message

java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class akka.stream.testkit.Utils$TE,None,Left(),false)
Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class akka.stream.testkit.Utils$TE,None,Left(),false)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:114)
	at akka.stream.scaladsl.UnfoldResourceSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$9.apply(UnfoldResourceSourceSpec.scala:194)
	at akka.stream.scaladsl.UnfoldResourceSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$9.apply(UnfoldResourceSourceSpec.scala:182)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:29)
	at akka.stream.scaladsl.UnfoldResourceSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(UnfoldResourceSourceSpec.scala:182)
	at akka.stream.scaladsl.UnfoldResourceSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(UnfoldResourceSourceSpec.scala:182)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by johanandren** [comment]
I wonder if this is related to #25114
@svezfaz any chance you could take a look given that you contributed that PR?

**Comment by svezfaz** [comment]
@johanandren not sure if I'm not reading this page right https://jenkins.akka.io:8498/job/akka-nightly/
but last failure for this nightly spec seems to be on 16-May. The `UnfoldResourceSource` change was merged on 17-May. Only blue balls from then on. Do you see any more recent failures?

**Comment by johanandren** [comment]
Ah, I was working through a backlog of failures, so maybe that PR in fact rather fixed the test then. Sorry and thanks for taking a peek at it.

**Comment by johanandren** [comment]
Nope: https://jenkins.akka.io:8498/job/akka-multi-node/2788/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1094/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/
https://jenkins.akka.io:8498/job/akka-nightly-jdk9/184/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/587/testReport/junit/akka.stream.scaladsl/UnfoldResourceSourceSpec/Unfold_Resource_Source_must_fail_when_close_throws_exception/
