### ISSUE TITLE
Behaviors.supervise cause java.lang.StackOverflowError

### ISSUE THREAD

**Issue by shejnowicz** [akka/akka#25128]
If we create behaviour recursively with supervising then it will blow with java.lang.StackOverflowError
after some time. Similar issue I observed in akka 2.5.11 for Behaviors.withMdc (seems to be fixed in 2.5.12)

(pseudocode)

```
def errorCauseBehaviour(state: Int) =
    Behaviors.supervise[SomeMessageType] {
        Behaviors.receive { (ctx, msg) =>
           msg match {
              case _ => errorCauseBehaviour(state + 1)
           }
        }
    } onFailure resume
```

**Comment by ktoso** [comment]
Thanks for reporting

**Comment by chbatey** [comment]
@shejnowicz you should only supervise once so just supervise the initial creation.
However we should defect this and fail fast or unwrap it

**Comment by chbatey** [comment]
Made a note in the docs: https://github.com/akka/akka/pull/25163
