### ISSUE TITLE
all-contributors overview

### ISSUE THREAD

**Issue by raboof** [akka/akka#25147]
It might be cool to acknowledge all kinds of contributors with something like https://www.npmjs.com/package/all-contributors-cli - though the table generated there is not super pretty. Perhaps could be a cool contribution :smile: ?

**Comment by qwefgh90** [comment]
A contributors frame would be better in github.

**Comment by Captain1653** [comment]
This issue is quite old. Is it still needed?  https://github.com/akka/akka/graphs/contributors looks really cool :) .

**Comment by johanandren** [comment]
Yes, on top of what github gives us I don't think we need anything.
