### ISSUE TITLE
[error] 402 errors found : (akka-actor-typed-tests / Test / compileIncremental) Compilation failed

### ISSUE THREAD

**Issue by liaolunhui** [akka/akka#25149]
] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:9:19: object testkit is not a member of package akka.actor
[error] import akka.actor.testkit.typed.scaladsl.{ ActorTestKit, TestProbe }
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:62:41: not found: type ActorTestKit
[error] abstract class ActorContextSpec extends ActorTestKit with TypedAkkaSpecWithShutdown {
[error]                                         ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:82:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:100:19: not found: value spawn
[error]       val actor = spawn(behavior)
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:112:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:124:19: not found: value spawn
[error]       val actor = spawn(behavior)
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:130:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:141:19: not found: value spawn
[error]       val actor = spawn(behavior)
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:147:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:178:23: not found: value spawn
[error]       val parentRef = spawn(parent)
[error]                       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:189:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:206:23: not found: value spawn
[error]       val parentRef = spawn(parent)
[error]                       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:213:19: not found: value TestProbe
[error]       val probe = TestProbe[Int]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:226:19: not found: value spawn
[error]       val actor = spawn(behavior)
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:235:19: not found: value TestProbe
[error]       val probe = TestProbe[Int]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:248:19: not found: value spawn
[error]       val actor = spawn(behavior)
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:257:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:269:26: not found: value spawn
[error]       val actorToWatch = spawn(behavior)
[error]                          ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:270:40: not found: value spawn
[error]       val watcher: ActorRef[Command] = spawn((
[error]                                        ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:292:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:293:20: not found: value spawn
[error]       val victim = spawn(Behaviors.empty[Command])
[error]                    ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:294:19: not found: value spawn
[error]       val actor = spawn(Behaviors.receivePartial[Command] {
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:315:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:320:38: not found: value spawn
[error]       val actor: ActorRef[Command] = spawn(
[error]                                      ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:342:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:347:19: not found: value spawn
[error]       val actor = spawn(
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:373:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:378:19: not found: value spawn
[error]       val actor = spawn(
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:408:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:417:19: not found: value spawn
[error]       val actor = spawn(
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:451:19: not found: value TestProbe
[error]       val probe = TestProbe[Info]
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:452:19: not found: value spawn
[error]       val actor = spawn(Behaviors.receivePartial[String] {
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:463:19: not found: value TestProbe
[error]       val probe = TestProbe[Children]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:464:19: not found: value spawn
[error]       val actor = spawn(Behaviors.receivePartial[String] {
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:487:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:488:19: not found: value spawn
[error]       val actor = spawn(Behaviors.receivePartial[Command] {
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:503:19: not found: value TestProbe
[error]       val probe = TestProbe[String]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:504:19: not found: value spawn
[error]       val actor = spawn(Behaviors.receivePartial[String] {
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:528:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:529:19: not found: value spawn
[error]       val actor = spawn(Behaviors.receivePartial[Command] {
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:540:22: not found: value TestProbe
[error]       val messages = TestProbe[Envelope]()
[error]                      ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:541:19: not found: value TestProbe
[error]       val probe = TestProbe[ActorRef[String]]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:542:19: not found: value spawn
[error]       val actor = spawn(Behaviors.receivePartial[String] {
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:559:19: not found: value spawn
[error]       val actor = spawn(Behaviors.empty[Null].decorate)
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:566:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:567:19: not found: value spawn
[error]       val actor = spawn(
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\TypedAkkaSpec.scala:7:19: object testkit is not a member of package akka.actor
[error] import akka.actor.testkit.typed.scaladsl.{ TestInbox, ActorTestKit }
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\TypedAkkaSpec.scala:34:9: not found: type ActorTestKit
[error]   self: ActorTestKit 閳�
[error]         ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\ActorContextSpec.scala:587:35: not found: value shutdownTestKit
[error]   override def afterAll(): Unit = shutdownTestKit()
[error]                                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:13:19: object testkit is not a member of package akka.actor
[error] import akka.actor.testkit.typed.scaladsl.{ ActorTestKit, TestProbe }
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:28:23: not found: type ActorTestKit
[error] class AskSpec extends ActorTestKit
[error]                       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:36:5: not found: value system
[error]     system.executionContext
[error]     ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:49:17: not found: value spawn
[error]       val ref = spawn(behavior)
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:51:19: not found: value TestProbe
[error]       val probe = TestProbe()
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:60:17: not found: value spawn
[error]       val ref = spawn(behavior)
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:66:19: not found: value spawn
[error]       val actor = spawn(Behaviors.empty[Foo])
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:76:40: not found: value system
[error]       val noSuchActor: ActorRef[Msg] = system match {
[error]                                        ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:120:19: not found: value TestProbe
[error]       val probe = TestProbe[AnyRef]("probe")
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:138:17: not found: value spawn
[error]       val ref = spawn(behv)
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\AskSpec.scala:153:9: not found: value system
[error]       }(system.toUntyped)
[error]         ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:15:19: object testkit is not a member of package akka.actor
[error] import akka.actor.testkit.typed.scaladsl.{ BehaviorTestKit, TestInbox }
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:72:53: not found: type TestInbox
[error]     case class Init(behv: Behavior[Command], inbox: TestInbox[Event], aux: Aux) {
[error]                                                     ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:74:23: not found: value BehaviorTestKit
[error]         val testkit = BehaviorTestKit(behv)
[error]                       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:79:31: not found: type BehaviorTestKit
[error]     case class Setup(testKit: BehaviorTestKit[Command], inbox: TestInbox[Event], aux: Aux)
[error]                               ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:79:64: not found: type TestInbox
[error]     case class Setup(testKit: BehaviorTestKit[Command], inbox: TestInbox[Event], aux: Aux)
[error]                                                                ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:82:19: not found: value TestInbox
[error]       val inbox = TestInbox[Event]("evt")
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:88:19: not found: value TestInbox
[error]       val inbox = TestInbox[Event]("evt")
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:122:25: not found: type TestInbox
[error]     override type Aux = TestInbox[Command]
[error]                         ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:125:11: value receiveAll is not a member of Siphon.this.Aux
[error]       aux.receiveAll() should ===(command :: Nil)
[error]           ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:130:25: not found: type TestInbox
[error]     override type Aux = TestInbox[Either[Signal, Command]]
[error]                         ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:133:11: value receiveAll is not a member of SignalSiphon.this.Aux
[error]       aux.receiveAll() should ===(Right(command) :: Nil)
[error]           ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:137:11: value receiveAll is not a member of SignalSiphon.this.Aux
[error]       aux.receiveAll() should ===(Left(signal) :: Nil)
[error]           ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:224:34: not found: value TestInbox
[error]         mkCtx().check(Terminated(TestInbox("x").ref)(null))
[error]                                  ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:228:49: not found: value TestInbox
[error]         mkCtx().check(GetSelf).check(Terminated(TestInbox("x").ref)(null))
[error]                                                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:232:34: not found: value TestInbox
[error]         mkCtx().check(Terminated(TestInbox("x").ref)(null)).check(GetSelf)
[error]                                  ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:276:34: not found: value TestInbox
[error]     private implicit val inbox = TestInbox[State]("state")
[error]                                  ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:312:46: not found: value TestInbox
[error]         mkCtx().check(Swap).check(Terminated(TestInbox("x").ref)(null))
[error]                                              ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:316:61: not found: value TestInbox
[error]         mkCtx().check(Swap).check(GetSelf).check(Terminated(TestInbox("x").ref)(null))
[error]                                                             ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:320:46: not found: value TestInbox
[error]         mkCtx().check(Swap).check(Terminated(TestInbox("x").ref)(null)).check(GetSelf)
[error]                                              ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:487:17: not found: value TestInbox
[error]     val inbox = TestInbox[Command]("widenedListener")
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:493:23: not found: type TestInbox
[error]   override type Aux = TestInbox[Done]
[error]                       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:496:17: not found: value TestInbox
[error]     val inbox = TestInbox[Done]("deferredListener")
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:504:9: value receiveAll is not a member of DeferredScalaBehaviorSpec.this.Aux
[error]     aux.receiveAll() should ===(Done :: Nil)
[error]         ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:509:17: not found: value TestInbox
[error]     val inbox = TestInbox[Either[Signal, Command]]("tapListener")
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:584:17: not found: value TestInbox
[error]     val inbox = TestInbox[Command]("widenedListener")
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:593:23: not found: type TestInbox
[error]   override type Aux = TestInbox[Done]
[error]                       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:596:17: not found: value TestInbox
[error]     val inbox = TestInbox[Done]("deferredListener")
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:604:9: value receiveAll is not a member of DeferredJavaBehaviorSpec.this.Aux
[error]     aux.receiveAll() should ===(Done :: Nil)
[error]         ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\BehaviorSpec.scala:609:17: not found: value TestInbox
[error]     val inbox = TestInbox[Either[Signal, Command]]("tapListener")
[error]                 ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:8:19: object testkit is not a member of package akka.actor
[error] import akka.actor.testkit.typed.TestKitSettings
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:9:19: object testkit is not a member of package akka.actor
[error] import akka.actor.testkit.typed.scaladsl._
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:29:28: not found: type ActorTestKit
[error] class DeferredSpec extends ActorTestKit with TypedAkkaSpecWithShutdown {
[error]                            ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:32:31: not found: value TestKitSettings
[error]   implicit val testSettings = TestKitSettings(system)
[error]                               ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:32:47: not found: value system
[error]   implicit val testSettings = TestKitSettings(system)
[error]                                               ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:36:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]("evt")
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:42:7: not found: value spawn
[error]       spawn(behv)
[error]       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:48:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]("evt")
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:61:7: not found: value spawn
[error]       spawn(behv)
[error]       ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:67:19: not found: value TestProbe
[error]       val probe = TestProbe[Event]("evt")
[error]                   ^
[error] D:\scalaProject\akka\akka-actor-typed-tests\src\test\scala\akka\actor\typed\DeferredSpec.scala:77:7: not found: value spawn
[error]       spawn(behv)
[error]       ^

**Comment by ktoso** [comment]
What are you doing specifically? 
Things should just work, including on windows.
I'll close for now but if you can provide details what exactly you are doing that does not work we can help a bit.
