### ISSUE TITLE
Add ability to log unhandled messages at a different log level than DEBUG

### ISSUE THREAD

**Issue by eyalroth** [akka/akka#25158]
I'd love it if there was an option to configure akka to log unhandled messages at a different level than _DEBUG_; for instance, _ERROR_.

Why would i want to do this? well, as I see it, unhandled messages are bugs much like invoking a method with illegal arguments. It should not happen normally, and should be fixed ASAP.

Currently, one could completely override `aroundReceive` to achieve this, but it's not quite a public API and I'd rather have a builtin solution to this.

**Comment by raboof** [comment]
For catching unhandled messages globally, you might subscribe to the dead letter queue as described at https://doc.akka.io/docs/akka/2.5/general/message-delivery-reliability.html#dead-letters

For catching unhandled messages for a specific actor, you might override `unhandled` as mentioned in https://doc.akka.io/docs/akka/current/actors.html#actor-api

Those 2 features combined might be sufficient to cover your needs?

**Comment by eyalroth** [comment]
Right, I missed the `unhandled` method; though, this requires enforcing that every actor inherits a certain behavior, which is prone to human error (and in general I believe that inheriting behaviors is a bad practice).

Unhandled messages have nothing to do with dead letter as I see it. They are bugs, plain and simple. I would love to have a way to at least make those cases more visible with a single configuration.

**Comment by raboof** [comment]
Ah, you're right, I misremembered: the default implementation of `Unhandled` puts those messages on the event stream as `UnhandledMessage` (with sender and recipiant `ActorRef`s as metadata) rather than dead letters. You can make them more visible by listening for those events on the event stream and highlighting them.

**Comment by eyalroth** [comment]
That's basically re-implementing what is already built into the framework; i.e, [Logging.scala:131](https://github.com/akka/akka/blob/d986c7b6bb8423e2084b0184ee0f1669c3df55fe/akka-actor/src/main/scala/akka/event/Logging.scala#L131):
```scala
subscribe(system.systemActorOf(Props(new Actor {
def receive = {
  case UnhandledMessage(msg, sender, rcp) ⇒
    publish(Debug(rcp.path.toString, rcp.getClass, "unhandled message from " + sender + ": " + msg))
}
}), "UnhandledMessageForwarder"), classOf[UnhandledMessage])
```
Only replacing `Debug` with `Error` or what not (and giving the actor a different name).

Sure, this is possible, but I find the whole approach flawed. It feels as if Akka treats those messages as a mere nuisance rather than an actual problem; not only that it logs it as _DEBUG_ exclusively, but it doesn't even do that by default (one has to configure that feature on).

Unhanded messages are bugs, and should be treated as ones. Perhaps this is not the place to discuss this.

**Comment by johanandren** [comment]
It is a pretty common pattern to have multiple behaviors, where not every behavior does anything for all messages, so unhandled message are not by definition bugs. 

Perhaps they are always bugs _your_ actors though, and that is why you can override `unhandled` to do something that is more suitable to your use case (fail the actor, log error, etc).

In Akka typed we have the additional possibility of having a sealed trait as message type and using a complete function as message handler which will give you compiler warnings if not all subtypes are handled.

**Comment by johanandren** [comment]
You could also mimic the sealed supertype pattern in the untyped actors by first matching on the sealed supertype, and then deferring to a total function/method moving the problem to compile time from runtime.

**Comment by eyalroth** [comment]
@johanandren 

> It is a pretty common pattern to have multiple behaviors, where not every behavior does anything for all messages, so unhandled message are not by definition bugs.

This is basically multiple inheritance for the sake of implementation, and I'm a big fan of "composition over inheritance" so therefore this a very bad practice in my book. To be honest, I believe most experienced OOP developers would say the same.

I have to say that I've been developing my first big project with actors for the past few months and I have a lot of criticism towards it, especially since it is quite the go-to framework for Scala developers. I've also taken a look at the (new) Akka typed and I haven't seen many improvements to the issues I was concerned with in the first place. Again, this is probably not the place to discuss this, and I sure hope I'll have the time to put these thoughts someplace public.

> You could also mimic the sealed supertype pattern in the untyped actors by first matching on the sealed supertype, and then deferring to a total function/method moving the problem to compile time from runtime.

I actually ended up with something like this:
```scala
object ReceiveHelper {

  /* --- Constants --- */

  private val RUNTIME_MIRROR = runtimeMirror(getClass.getClassLoader)

  /* --- Inner Classes --- */

  /**
    * A receive-function that only accepts parameters of the given type.
    *
    * @tparam A The given type.
    */
  type CustomReceive[A] = PartialFunction[A, Unit]

  /**
    * An implicit conversation of a custom-receive into a general receive.
    */
  implicit def customReceiveToGeneric[A: TypeTag](pf: CustomReceive[A]): Receive = new Receive {

    override def isDefinedAt(x: Any): Boolean = x match {
      case customValue: A if RUNTIME_MIRROR.classSymbol(x.getClass).selfType <:< typeOf[A] =>
        pf.isDefinedAt(customValue)
      case _ =>
        false
    }

    override def apply(v1: Any): Unit = pf.apply(v1.asInstanceOf[A])
  }

  /**
    * An implicit conversation of any kind of a partial function to a receive.
    */
  implicit def pfToReceive[A: TypeTag](pf: PartialFunction[A, _]): Receive =
    customReceiveToGeneric(pf.andThen(_ => ()).asInstanceOf[CustomReceive[A]])

  /**
    * Joins the given receive-functions into one receive function, and returns it.
    *
    * @param receives The given receive-functions.
    * @return The joined receive function.
    */
  def join(receives: Receive*): Receive = receives.reduce(_.orElse(_))
}
```
Which allows me to do something like this:
```scala
class MyActor extends Actor {
  override def receive: Receive = join(instructions(), workIsDone())

  def instructions(): CustomReceive[MyActorInstruction] = {
     case Start => ...
     case Suspend => ...
     case Resume => ...
     case Abort => ...
  }

  def workIsDone(): CustomReceive[WorkIsDone] = {
    case WorkIsDone(result) => ...
  }
}
```

This actually doesn't move the problem to compile time, since I still want to have the option of using pattern match for filtering some of the messages in certain states of the actor--hence, I'm still using partial functions--but IMHO it makes it easier to read the actor code.

**Comment by raboof** [comment]
We're getting into topics that might be more suitable for https://discuss.akka.io indeed ;).

I think it's good to be careful about comparing Actors and OOP: they're different models, and mapping OOP concepts directly to actors makes actors look like 'weird objects' indeed (while smalltalk did talk about 'message passing' that was completely synchonous which changes the game a bit). That said, some concepts indeed apply to both and rest assured we're typically big proponents of "composition over inheritance" as well ;).

**Comment by johanandren** [comment]
Closing this as it ended up more of a discussion than anything we will act on. Feel free to continue in a topic in the forums @eyalroth
