### ISSUE TITLE
Can't "ask" Akka Typed TestInbox.ref()

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25164]
It type checks it is a ActorRefAdapter. We should move FunctionRef back from the testkit, maybe keeping it internal for now, so that tests can use TestInboxes

**Comment by patriknw** [comment]
You mean s/FunctionRef/TestInbox/ ?
We can have something internal, but I don't think the public API for TestInbox should be moved.
Not sure how much well ask works with the synchronous testing, but we can give it a try.

**Comment by chbatey** [comment]
I think this should just be done with TestProbe / async testing rather than TestInboxes

**Comment by patriknw** [comment]
ok, let's start there
