### ISSUE TITLE
Implementation of akka.util.Unsafe is JVM specific (fails on IBM J9)

### ISSUE THREAD

**Issue by thjaeckle** [akka/akka#25161]
I tried using Akka 2.5.12 together with artery udp remoting together with the [OpenJ9 JVM](https://github.com/eclipse/openj9).
There an Akka-cluster is not able to form as there is an `ArrayIndexOutOfBoundsException` happening in `akka.util.Unsafe#copyUSAsciiStrToBytes`:

```
18-05-29 09:19:53,705 ERROR [] a.r.artery.Encoder Encoder(akka://ditto-cluster) - Failed to serialize message [ActorSelectionMessage(akka.cluster.InternalClusterAction$InitJoin)].
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 95
	at akka.util.Unsafe.copyUSAsciiStrToBytes(Unsafe.java:54)
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 95
	at akka.remote.artery.EnvelopeBuffer.writeLiteral(EnvelopeBufferPool.scala:530)
	at akka.util.Unsafe.copyUSAsciiStrToBytes(Unsafe.java:54)
	at akka.remote.artery.EnvelopeBuffer.writeHeader(EnvelopeBufferPool.scala:426)
	at akka.remote.artery.EnvelopeBuffer.writeLiteral(EnvelopeBufferPool.scala:530)
	at akka.remote.MessageSerializer$.serializeForArtery(MessageSerializer.scala:65)
```

The problem is that the OpenJ9 JVM has a different internal representation of the `String` `value` when being built from a `StringBuilder` which was created with a larger capacity then used. I guess that is for performance reasons.
See also the issue I created in OpenJ9 for a deeper insight: https://github.com/eclipse/openj9/issues/2000

As this is a JVM internal decision to optimize that way (`String.length()` and `String.toCharArray().length` return the correct length) and Akka's `Unsafe` uses internas of the `String` it is quite hard to argue that OpenJ9 should adopt their internal behavior of handling Strings.

By the way: The "legacy" remoting in Akka 2.5.12 with Netty 3.10 works with OpenJ9 JVM and it is impressive what it can do for the memory footprint of an Akka application.

**Comment by johanandren** [comment]
This is a performance hack to benefit from JVM specifics (and given that this didn't surface until now I don't think we have many non-hotspot users), it would be nice to have some performance numbers with the hack removed vs used to know if it is worth it. If it is worth having the hack there maybe we could detect JVM and use a slower version for other JVMs?

**Comment by ktoso** [comment]
In general I'd agree that such things should degrade nicely rather than blow up on different JVM. I suppose this could be done as static initialization during which we try to perform a task using this API and if it fails we replace with a "normal" implementation. It is a question of priorities though -- a contribution in form of a pull request would get this solved the fastest I believe, if you'd like to help on this?

First, I'd like to ask you to try the https://doc.akka.io/docs/akka/2.5/remoting-artery.html#selecting-transport tcp mode of the new artery transport as documented here. With it you'd be able to exclude the netty 3 dependency as well.

**Comment by thjaeckle** [comment]
Thanks Konrad, I didn't think about using the tcp remoting.
I guess I assumed that it would use the same code for serializing the actor path.

Will try that first.

**Comment by fjeremic** [comment]
FYI there is a rather simple one line patch in https://github.com/eclipse/openj9/issues/2000#issuecomment-392531393 which should alleviate the issue for OpenJ9 at basically zero cost to OpenJDK. This change makes akka more robust w.r.t. the JVM used. Would this be an acceptable patch?

**Comment by ktoso** [comment]
Interesting... the diff is only about getting the length from the string and not char array... if you believe this is safe please PR. 

I don't think we have J9 available at hand to try it as part of the build though hm... So that we would have to try then

**Comment by patriknw** [comment]
> With artery transport "tcp" the problem remains.

Yes, that is used for the compressed ActorRef and manifest string, which is the same for tcp and aeron-udp.

Thanks for fixing!
