### ISSUE TITLE
akka-remote: switch netty/aeron dependencies to optional in maven pom

### ISSUE THREAD

**Issue by fbe** [akka/akka#25169]
Akka remote has an transitive dependency to netty and aeron (which pulls in agrona). As I understood, both of them are optional dependencies, depending on what kind of transport you want to use.

In the maven world there is the option to mark dependencies as optional (not provided!), they will not be pulled in automatically.
I think it would be much better to mark this transport dependencies as optional instead of forcing maven users to add dependency exclusions if they want to keep their classpath clean (which is necessary especially for netty  which is a really often used dependency).

I don't know if SBT / Ivy support a feature like optional dependencies, but as maven does - exactly for that case. It would be great if you could implement this in your publishing process =)

**Comment by patriknw** [comment]
I don't think we can change this in a patch release of Akka 2.5.x, but we should for 2.6.0. Also, I'm not quite sure everything is optional yet, so it will require some testing and possibly adjustments.

Thanks for creating the ticket.

**Comment by hepin1989** [comment]
@feb Yeah, nice issue, thanks for opening this issue up.
Are you using special in-house transport implementation?

**Comment by fbe** [comment]
Hi @hepin1989 , no, we are not using special in-house transports, but we are doing active and strict library management (to avoid license issues, unexpected classpath errors and incompabilities and so on). Therefore, a clean dependency tree is important for us and we want to avoid dependency exclusions whenever possible (because they need to be checked on each lib upgrade again)
