### ISSUE TITLE
Add akka.japi.Either to Akka Java API helpers

### ISSUE THREAD

**Issue by laszlovandenhoek** [akka/akka#25181]
As far as I can tell, `scala.util.Either` is not used anywhere in the public Java API of core Akka (or Akka Streams). However, it _is_ used in akka-stream-contrib, particularly `PartitionWith`. Constructing a `scala.util.Either` from Java code is inconvenient; for example, `Either.cond` takes two by-name arguments but these are eagerly evaluated when called from Java, which often defeats the purpose of using `Either` at all.

I came up with this bit to scratch that particular itch:

```
import java.util.function.Supplier

object Either {
  def cond[A, B](condition: Boolean,
                 getB: Supplier[B],
                 getA: Supplier[A]): scala.Either[A,B] = {
    scala.Either.cond(condition, getB.get(), getA.get())
  }
}
```
...but I guess this is a bit light to include as a central library component as it stands. I think it could be a valuable addition, opening up new possibilities, but before fleshing it out and submitting a PR, I figured I'd open this issue as an RFC. In particular, I'm curious if the Akka team is open to adding an `Either` to the `akka.japi` package (in akka-actor), and if so, what features it should have and/or lack.

**Comment by patriknw** [comment]
@laszlovandenhoek  I think it would be better if you contribute a proper Java API to akka-stream-contrib. We don't have good experience with exposing Scala classes in Java APIs. E.g. Scala's Duration, Future, Option. They may seem harmless from a Scala developers perspective but just the fact that they have scala in the package name seems to scare Java developers. Therefore we try to not use such classes in Java APIs.

**Comment by hepin1989** [comment]
There is a vavr out there:)
But I have to agree with @patriknw, it's always scary for who don't know Scala much.

**Comment by laszlovandenhoek** [comment]
I'll close this and continue here: https://github.com/akka/akka-stream-contrib/issues/135
