### ISSUE TITLE
ClusterSharding: Improve startup time

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25191]
It is common for a ShardRegion's first Register message to be ignored due to the shard coordinator not having left its initial state `watingForState`. The default retry is 2s which results in a 2s delay before sharded messages are processed. We could ramp up to the timeout e.g 0.2, 0.4 0.8 .. 2s or stash Register messages.

**Comment by patriknw** [comment]
exponential increase of the retry delay sounds good
