### ISSUE TITLE
Quickstart - mention the sample project close to first test

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25193]
It has come up twice now (https://discuss.lightbend.com/t/akka-getting-started-tutorial/1177/3 #25086 ) that new users miss out on that they have a complete setup with ScalaTest in the sample project that you are meant to download before starting the quickstart, and are wondering how they should get tests wired up.

Maybe we should just mention the sample project again next to the first example test, or refer back to the https://doc.akka.io/docs/akka/current/guide/introduction.html?language=scala#how-to-get-started section where we link to it?

**Comment by olimination** [comment]
Hi @johanandren 

I have tried a first PR addressing this issue.

Feel free to feedback :)
