### ISSUE TITLE
Persistence typed: disable / customize recovery

### ISSUE THREAD

**Issue by svroonland** [akka/akka#25216]
The non-typed persistence offers recovery customization. Would be nice to have this in the typed persistence as well.

The `PersistenceBehaviorImpl` already seems to have a parameter of type `Recovery` from the untyped persistence library. Should be a matter of adding a method like `withRecovery(recovery: Recovery)` to `PersistentBehavior`.

**Comment by johanandren** [comment]
I think we may have intentionally left it out in the new API (but I may also misremember that). Can you describe your use case for doing a partial recovery?

**Comment by chbatey** [comment]
Skipping snapshots is an option we might want

**Comment by svroonland** [comment]
@johanandren My use case is to use akka persistence as a simple event journal which I can use with persistence query. So the actors have no state, they are just a mechanism to write incoming events to a journal. 

Guess you could argue it's a use case that akka persistence was not really meant for.

**Comment by patriknw** [comment]
It must anyway recover the sequence number so that next written event has the correct number.

**Comment by an-tex** [comment]
Hi @patriknw , isn't that the responsibility of the JournalPlugin as in here https://github.com/akka/akka/blob/6bf20f4117a8c27f8bd412228424caafe76a89eb/akka-persistence/src/main/scala/akka/persistence/journal/AsyncRecovery.scala#L70 ? Such that the Actor doesn't have to potentially run through millions of messages just to get the sequence number? I've just started migrating an application using PersistentActor where we sometimes need to define a custom recovery with a different toSequenceNr. With the current API it's not possible any more.

**Comment by patriknw** [comment]
Recover the right sequence number but don't replay any snapshot and events sounds like a valid recovery strategy. A PR for that with possibility to add more recovery strategies in the future would be welcome.

**Comment by an-tex** [comment]
Ok I'll look into it next week
