### ISSUE TITLE
Akka Typed top level behavior and spawning

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25223]
Top level behaviors for an Actor System have the benefit of initial setup being internal rather than external but it makes certain scenarios (e.g. spawning session and request level actors) harder. This becomes apparent when trying to write simple Akka Typed examples. 

It would be nice to retain the benefit of `actorOf` for these use cases.

One possible solution would be to have a defined protocol for Spawning actors (like in the BehaviorTestKit) and then helpers that would allow an ActorRef[SpawnProtocol] to be used like an untyped ActorSystem actorOf. This would need something like FutureActorRef/RepointableActorRef that buffers messages until the ActorRef is ready.

**Comment by patriknw** [comment]
and we would provide a default implementation of a `Behavior` of this `SpawnProtocol` that can be used as the `/user` top actor or as:
```
Behaviors.setup { ctx =>
  ctx.spawn(...)
  ctx.spawn(...)

  SpawnProtocol.behavior
}
```

**Comment by ktoso** [comment]
More clarification about the concepts:

```
sealed trait ActorSystemProtocol
object ActorSystemProtocol { def behavior: Behavior[ActorSystemProtocol] = ??? }
final case class Spawn[T](behavior: Behavior[T], name: String, props: Props)(val replyTo: ActorRef[ActorRef[T]]) extends ActorSystemProtocol


class x {

  // protocol is ActorSystemProtocol or could be called ActorSystemGuardianProtocol
  val system1: ActorRef[ActorSystemProtocol] = ActorSystem("system")

  // is the same as:
  val system2: ActorRef[ActorSystemProtocol] = ActorSystem(ActorSystemProtocol.behavior, "system")

  // allows on "startup" etc
  val system3: ActorRef[ActorSystemProtocol] = ActorSystem(Behaviors.setup { context ⇒
    context.log.info("Starting...")
    ActorSystemProtocol.behavior
  }, "system")

  // allows full custom one as well
  val system4: ActorRef[ActorSystemProtocol] = ActorSystem(Behaviors.setup { context ⇒
    Behaviors.receiveMessage[ActorSystemProtocol] {
      case spawn @ Spawn(behavior, name, props) ⇒
        spawn.replyTo ! context.spawn(behavior, name, props)
        Behavior.same
    }
  }, "system")
  
  
  // enables:
  
  system4.spawn(Behaviors.empty, "hello")
}

  def spawn[T](b: Behavior[T], name: String, props: Props = Props.empty)(implicit timeout: Timeout): ActorRef[T] = {
    val a: Future[ActorRef[T]] = guardian ? Spawn(b, name, props)
    FutureActorRef(a)
  }
```
```

**Comment by johanandren** [comment]
Making it `SpawnProtocol` rather than `ActorSystemProtocol` would make the behavior less weird to use for other thing than `/user`, that could make sense for example in a HTTP route where you inject a root actor which will spawn children for actor-per-workload but don't necessarily want that to be the actor system root.

**Comment by patriknw** [comment]
Leaving the FutureActorRef for later https://github.com/akka/akka/issues/25305
