### ISSUE TITLE
Cluster sharding remember entities creates redundant journals

### ISSUE THREAD

**Issue by jpeel** [akka/akka#25261]
There isn't a check whether the entity is already remembered when creating an entity from a non-StartEntity message. The constant-rate recovery method of remembered entities makes this more likely to happen. When using persistence for remembering entities, this can cause the journal to grow with every restart of a Shard. Long-term this can cause major performance issues because more journals will need to be replayed. Also, the redundant journaling slows the overall processing of messages.

The fix is simple:

```
diff --git a/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala b/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
index 71b2cf263a..d408e77643 100644
--- a/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
+++ b/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
@@ -455,11 +455,14 @@ private[akka] trait RememberingShard { selfType: Shard ⇒
     context.child(name) match {
       case Some(actor) ⇒
         actor.tell(payload, snd)
-
       case None ⇒
-        //Note; we only do this if remembering, otherwise the buffer is an overhead
-        messageBuffers.append(id, msg, snd)
-        processChange(EntityStarted(id))(sendMsgBuffer)
+        if (state.entities.contains(id)) {
+          getEntity(id).tell(payload, snd)
+        } else {
+          //Note; we only do this if remembering, otherwise the buffer is an overhead
+          messageBuffers.append(id, msg, snd)
+          processChange(EntityStarted(id))(sendMsgBuffer)
+        }
     }
   }
```

**Comment by patriknw** [comment]
Thanks for reporting @jpeel . Would you be able to create a pull request?

**Comment by jpeel** [comment]
I opened a PR for this. I would add a test if I could think of a good way to test it. It is tricky because the message for the entity needs to be processed before StartEntity. It is relatively easy to test with a full-scale system which is how I found this issue.

**Comment by chbatey** [comment]
Thanks @jpeel
