### ISSUE TITLE
Akka HTTP server graceful shutdown incorrect behaviour

### ISSUE THREAD

**Issue by fr3akX** [akka/akka#25262]
Current behaviour:
1. When shutdown is triggered any open connection will remain open, and will be able to make new requests where server will respond with 503.
1. Inflight requests are handled by leaving connections open, thus user may issue new request and server will respond with 503.
1. All connections are closed only after deadline exceeds, and emits final response with 503 code even if no request are made.

Expected behaviour:
1. When shutdown is triggered all idle connections are terminated immediately.
1. Inflight requests are handled, and final response is sent with Connection: close, and connection is terminated.
1. Idling connections are terminated without final response, as no requests was made.

pull request https://github.com/akka/akka-http/pull/2089

**Comment by ktoso** [comment]
Issue opened in wrong repo, I'll move it to https://github.com/akka/akka-http/ where it should be.
I agree that we can improve the order of doing things a bit; I don't agree that it is incorrect now though ;-)

**Comment by ktoso** [comment]
moved to https://github.com/akka/akka-http/issues/2090
