### ISSUE TITLE
ClusterSingletonManager does not handle event OldestChanged in state End

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#25274]
When the cluster singleton manager receives an OldestChanged in state End it goes unhandled
```WARN    akka.cluster.singleton.ClusterSingletonManager    six    unhandled event OldestChanged(Some(UniqueAddress(...,-2122401574))) in state End```

**Comment by johanandren** [comment]
When the singleton is in the end state it is just waiting for the cluster node it lived on to have left the cluster, as soon as that happens the manager stops itself. This is a harmless warning, but maybe it would be good to silently discard any other messages in that state.

**Comment by nvollmar** [comment]
I thought the same, discarding silently would then probably a better solution than having a warning in the logs.

**Comment by patriknw** [comment]
sounds good, would you be able to create a PR @nvollmar ?

**Comment by nvollmar** [comment]
@patriknw I can look into it
