### ISSUE TITLE
Broken link and inconsistent footers in Streams documentation

### ISSUE THREAD

**Issue by DanielGGordon** [akka/akka#25280]
The bottom link in the [Streams/Basics and Working with Flows"](https://github.com/akka/akka-http/issues ) has a broken link at the bottom. Link is supposed to point to source code. Last link on the bottom as seen below:

![image](https://user-images.githubusercontent.com/11824880/42050589-fe23c292-7ace-11e8-837a-ef62db565d54.png)

In addition, the footer does not match the footer in ["Streams/Streams Quickstart Guide"](https://doc.akka.io/docs/akka/2.5/stream/stream-quickstart.html). The footer looks like:

![image](https://user-images.githubusercontent.com/11824880/42050850-b1885b7c-7acf-11e8-803a-70e6b20865f6.png)

Is this type of footer (where readers are directed to go to Github and make pull requests), only for the quickstart guide, or should it be everywhere?

I will make my own pull request after that question is answered.

**Comment by ktoso** [comment]
Would you be able to show a link to the first page? Your link currently is ` [Streams/Basics and Working with Flows"](https://github.com/akka/akka-http/issues )`.

I do expect these to simply be for different versions of the page -- i.e. 2.5.2 and 2.5.13, so yeah, things change and move on and they are not expected to be the exact same.

**Comment by johanandren** [comment]
Hopefully the re-added "this is not the latest version of the docs" banner will help a bit with this

**Comment by ktoso** [comment]
Closing, please reopen if the above comments did not explain the issue
