### ISSUE TITLE
`Source.actorRef` not completed by `Status.Success` or `PoisonPill`

### ISSUE THREAD

**Issue by giftig** [akka/akka#25285]
I've been struggling to get my stream to complete while testing a `SourceShape` component, and have just reduced it to its simplest form and identified `Source.actorRef` as the culprit; the documentation suggests that sending either `Status.Success` or `PoisonPill` to the actor ref materialised from `Source.actorRef` should complete the stream, however my stream never completes with either message:

```scala
  "Simple test" should "work" in {
    val src = Source.actorRef[Int](100, OverflowStrategy.dropNew)
    val (ref: ActorRef, done: Future[Done]) = src.toMat(Sink.ignore)(Keep.both).run()
    ref ! Status.Success("")
    ref ! PoisonPill

    done.futureValue should be(Done)
  }
```
failure message:
```
[info] Simple test
[info] - should work *** FAILED ***
[info]   A timeout occurred waiting for a future to complete. Queried 41 times, sleeping 50 milliseconds between each query. (ClusterHandlingSpec.scala:71)
```
Akka versions:

```
[info]   | +-com.typesafe.akka:akka-stream_2.12:2.5.11 [S]
[info]   |   +-com.typesafe.akka:akka-actor_2.12:2.5.11 [S]
```

Replacing `Source.actorRef` with a simple `Source(List(1,2,3,4,5))` results in a completed stream with the expected value. My first suspicion was that my messages weren't actually reaching the actor; I could understand a `Success` failing to complete the stream but it's surprising that a `PoisonPill` could fail since that should kill the actor. However setting `akka.loglevel = DEBUG` and `log-dead-letters = 100` shows me nothing of interest, and I confirmed both that the dead letter logging was working and that the `PoisonPill` was reaching its target by sending additional messages after the `PoisonPill`, which hit dead letters as expected.

All my testing points to something holding the source open even though the actor is gone.

**Comment by giftig** [comment]
I see you do have several tests for this behaviour in `akka.stream.ActorRefSourceSpec` so I'll try to see how my test differs from those; looks like the only real difference is your tests hook up an actor ref probe and check for an `OnComplete` message, whereas I'm hooking it up to `Sink.ignore` and waiting for the `Done`. That leaves some room for there to be a bug in the `TestSubscriber`, as I _think_ my test is simpler and just as valid, but I'll need to root around in ` StreamTestKit` a bit to figure out if that's true.

**Comment by ktoso** [comment]
Please update to latest akka - 2.5.13.
You can send in a PR with the reproducer if you want, seems suprising that it would not work..

Thanks

**Comment by giftig** [comment]
Same behaviour in `2.5.13`. I've added a similar test to `ActorRefSourceSpec` and I'll submit a PR once I've confirmed it's working (or indeed not working)
