### ISSUE TITLE
Cluster Distributed Data: Too slow writes in 2 or more cluster nodes

### ISSUE THREAD

**Issue by tolikr** [akka/akka#25310]
I use ORMap as distributed data between nodes of akka cluster. On each node this data may be modified: add elements, remove, modify. 
To be sure that majority nodes applies changes i use Update with strategy WriteMajority and await for UpdateSuccess msg to reply, that modification was successful.
Problem occurs if i add to cluster more that 1 node. Receiving a message UpdateSuccess becomes a long process. 
I written simple test case. [ddata-test.zip](https://github.com/akka/akka/files/2164908/ddata-test.zip) It illustrates a problem. I note if i turn of "akka.cluster.distributed-data.delta-crdt.enabled = off" and test became faster. But on real application my data is larger and that trick doesn't help.

**Comment by tolikr** [comment]
I change my test case. Now it uses all solutions above. But it executes same time. Please take a look.
[ddata-test.zip](https://github.com/akka/akka/files/2165808/ddata-test.zip)

**Comment by tolikr** [comment]
For test purposes i changed LWWMap to GCounter. Test completed in 2 seconds. With LWWMap it take 80 seconds to complete. Maybe i should try to use my own data structure instead LWWMap?

**Comment by patriknw** [comment]
The main bottleneck is probably that you emit the requests one-by-one and wait for the response before next, but it's still interesting to see why it's slow. I'll test your sample.

**Comment by tolikr** [comment]
LWWRegister, GSet pass test in 2 and 3 seconds accordingly. I think there is something in Map implementation, that makes replication slower than others.

**Comment by patriknw** [comment]
I started looking at this and understand what is going on, and have some ideas of what we can do to improve. The sequence numbers of the deltas gets out of sync and then we fall back to resending after a timeout.

**Comment by patriknw** [comment]
@tolikr Thanks for reporting. I have a solution in https://github.com/akka/akka/pull/25315

**Comment by tolikr** [comment]
@patriknw I will wait for some release to test it with my real data, thank you.

**Comment by patriknw** [comment]
After merging the PR there will be a nightly timestamped version, it would be great if you can try that. See https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository

**Comment by tolikr** [comment]
@patriknw i build your branch by myself. Test passed in 5 second instread 84 seconds. It's looking good. But i still wait for your nightly build to test it.

**Comment by tolikr** [comment]
I've tested nightly build. Thanks for fixing this behaviour.
