### ISSUE TITLE
Add guide on disable suggesting javadsl/scaladsl in docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#25312]
As seen on https://twitter.com/lteqgt/status/1014581098204954624 by @sebastianharko

**Comment by ktoso** [comment]
Technically stream, but also applies to typed and other things such as akka http

**Comment by patriknw** [comment]
How big will the note be? One sentence or full screen shot? Perhaps place the full description with example screen shot in a new page under [Additional Information](https://doc.akka.io/docs/akka/current/additional/index.html). I can't find any existing page where it would belong.

Then one sentence with link to above where we have the Dependency, e.g. https://doc.akka.io/docs/akka/current/typed/actors.html#dependency

We could also introduce a new "Useful imports" section after Dependency, listing the most relevant imports for that feature and mentioning this.

**Comment by sebastianharko** [comment]
I can't imagine the note being very long (more like a sentence) so your idea sounds about right @patriknw :-0
