### ISSUE TITLE
OSGi headers missing for akka typed

### ISSUE THREAD

**Issue by atooni** [akka/akka#25327]
Hello, 

we are using Akka within an OSGi based application and wnated to experiment with akka typed to see whether it could help us for furture releases. 
It seems the akka-actor-typed OSGi headers are missing from the manifest. 

Best regards 
Andreas

**Comment by raboof** [comment]
Hello Andreas,

Thanks for bringing this up. Unfortunately OSGi is outside of the expertise of most of the core team, so indeed this hasn't always been in the best state.

For akka-http we've even temporarily removed OSGi support (more details at https://github.com/akka/akka-http/issues/1852) though there has been community interest in resurrecting and supporting it (https://github.com/akka/akka-http/pull/2030).

As such, we'd very much value it when you could lend a hand here!


Arnout

**Comment by atooni** [comment]
Hi Arnout, 
I can certainly give it a go. Are there existing tests to validate the OSGi settings which I could use as guide to validate my setup or would I have to write those from scratch ?

Best regards 
Andreas

**Comment by raboof** [comment]
We have no OSGi tests in Akka, though there was a proposal in https://github.com/akka/akka-http/pull/2030 that seemed interesting and which might be possible to apply to Akka as well.

**Comment by atooni** [comment]
Yes I have seen that. It's kind of an implicit test by using the expected bundle.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Arnout Engelen <notifications@github.com> Date: 11/07/2018  18:17  (GMT+01:00) To: akka/akka <akka@noreply.github.com> Cc: Andreas Gies <andreas@wayofquality.de>, Author <author@noreply.github.com> Subject: Re: [akka/akka] OSGi headers missing for akka typed (#25327) 
We have no OSGi tests in Akka, though there was a proposal in akka/akka-http#2030 that seemed interesting and which might be possible to apply to Akka as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/akka/akka","title":"akka/akka","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/akka/akka"}},"updates":{"snippets":[{"icon":"PERSON","message":"@raboof in #25327: We have no OSGi tests in Akka, though there was a proposal in https://github.com/akka/akka-http/pull/2030 that seemed interesting and which might be possible to apply to Akka as well."}],"action":{"name":"View Issue","url":"https://github.com/akka/akka/issues/25327#issuecomment-404228160"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/akka/akka/issues/25327#issuecomment-404228160",
"url": "https://github.com/akka/akka/issues/25327#issuecomment-404228160",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [akka/akka] OSGi headers missing for akka typed (#25327)",
"sections": [
{
"text": "",
"activityTitle": "**Arnout Engelen**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@raboof",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"akka/akka\",\n\"issueId\": 25327,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"akka/akka\",\n\"issueId\": 25327\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/akka/akka/issues/25327#issuecomment-404228160"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 354363272\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by patriknw** [comment]
Obsolete https://github.com/akka/akka/issues/28304
