### ISSUE TITLE
Akka persistence tck

### ISSUE THREAD

**Issue by giena** [akka/akka#25321]
Hello,

In the optional part of the akka-persistence-tck/src/main/scala/akka/persistence/journal/JournalSpec.scala, there's this line:
receiverProbe.expectMsg(RecoverySuccess(highestSequenceNr = 6L))
I think, it's a problem to consider that the highestSequenceNr is predictable.
For me, the implementation layer is the only one to decide which will be the highestSequenceNr after a recovery.
I take an example with kafka. I 'm developing a new version of the akka persistence for kafka, an i use the transactional producer to create atomic batches. The usage of transactions in kafka producer introduces some skip in the kafka offsets, because the transactions are stored in the topics, and so takes an offset. But it's not a user data. If i store 6 events in the journal and i commit this batch, the next offset will be 7, not 6.
My issue is valid with kafka with transactions, but it could be valid for other implementation.

**Comment by patriknw** [comment]
I think this is a valid point. The sequence numbers must be >= 1 and increasing but apart from that the implementation should have some freedom. Would you be able to contribute to change the TCK?

**Comment by giena** [comment]
I'm ok with that and i will pull a request in the next days

**Comment by patriknw** [comment]
thanks
