### ISSUE TITLE
Provide Sink.takeLast(n) operator ?

### ISSUE THREAD

**Issue by naferx** [akka/akka#25322]
I've written a custom Sink.takeLast(n) operator a couple of times. Maybe it'd be helpful for others too
but not sure if deserves to live in the core.

Here's the signature:
```
/**
 * A `Sink` that materializes into a a `Future` of `Seq[T]` containing the last `n` collected elements.
 * If the stream completes before signaling at least n elements, the Future will complete with the number
 * of elements taken at that point.
 */
 def takeLast[T](n: Int): Sink[T, Future[immutable.Seq[T]]]
```

**Comment by patriknw** [comment]
I think `Sink.fold` can be used for that and there is no need for a special operator.

```
Source(List(1, 2, 3, 4, 5))
  .runWith(Sink.fold(Vector.empty[Int]) { (acc, elem) => (acc :+ elem).takeRight(3) })
  .foreach(println)
```

Perhaps you could add it to the [Cookbook](https://doc.akka.io/docs/akka/current/stream/stream-cookbook.html) or as an example in the [fold page](https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/fold.html) ?

**Comment by naferx** [comment]
sounds good. I will take care of it over the weekend

**Comment by patriknw** [comment]
thanks

**Comment by ktoso** [comment]
Discussed internally and for the sake of symmetry we'd like to add the `takeLast` operator after all. 
Would you want to PR it @naferx ? Please rememeber JavaDSL as well, let us know if you'd need help there.

**Comment by naferx** [comment]
Absolutely! I'll take care of it.
