### ISSUE TITLE
Two links of CRDTs materials in "Learn More about CRDTs" are broken

### ISSUE THREAD

**Issue by satansk** [akka/akka#25338]
The links of CRDTs materials in [Learn More about CRDTs](https://doc.akka.io/docs/akka/current/distributed-data.html#learn-more-about-crdts) are broken, and more specifically, the first and the third one are broken:

* The Final Causal Frontier talk by Sean Cribbs
* Eventually Consistent Data Structures talk by Sean Cribbs
* Strong Eventual Consistency and Conflict-free Replicated Data Types talk by Mark Shapiro
* A comprehensive study of Convergent and Commutative Replicated Data Types paper by Mark Shapiro et. al.

**Comment by patriknw** [comment]
@satansk thanks for reporting. Have you found new links, and if so would you be able to create a pull request fixing this?

**Comment by satansk** [comment]
Hi @patriknw , I have found the same video of the third one on youtube which is provided by Microsoft Research, [here](https://www.youtube.com/watch?v=oyUHd894w18&feature=youtu.be) is it.

But as the first one, I can only find the [original slides](https://speakerdeck.com/seancribbs/the-final-causal-frontier), and it seems there is no video on the internet.

Can we just put the slides on?

**Comment by patriknw** [comment]
then we can remove the link, it was a nice presentation but probably not understandable from only slides

**Comment by satansk** [comment]
Thanks, get it, I'll send a PR soon.
