### ISSUE TITLE
Terminated.failure is always None

### ISSUE THREAD

**Issue by IainHull** [akka/akka#25345]
When the root actor in an akka typed system fails with an exception this is never passed back by the future return from `ActorSystem.whenTerminated`.  The `Terminated` case class has a value called `failure` for this purpose but its always empty.

This feature would be very useful for services to return their exit status to the operating system or for for failing tests wrapped in an actor system.

**Comment by IainHull** [comment]
I would be happy try to add this myself.  I have created a unit test to reproduce this, but I am struggling to figure out the best way to pass the exception back from the guardian. I am happy to have a go at this if you folks think it should be straight forward to add to the untyped adapter implementation.

```
diff --git a/akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala b/akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
index 73cf63c9e3..1e4989b905 100644
--- a/akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
+++ b/akka-actor-typed-tests/src/test/scala/akka/actor/typed/internal/ActorSystemSpec.scala
@@ -66,6 +66,20 @@ class ActorSystemSpec extends WordSpec with Matchers with BeforeAndAfterAll
       }
     }

+    "shutdown with exception if guardian throws" in {
+      object MyException extends Exception("test throw")
+
+      val throwing =
+        Behaviors.receive[Done] {
+          case (ctx, Done) ⇒ throw MyException
+        }
+      withSystem("shutdown", throwing, doTerminate = false) { sys: ActorSystem[Done] ⇒
+        sys ! Done
+        val terminated = sys.whenTerminated.futureValue
+        terminated.failure shouldBe Some(MyException)
+      }
+    }
+
     "terminate the guardian actor" in {
       val inbox = TestInbox[String]("terminate")
       val sys = system(
```

**Comment by johanandren** [comment]
I think it could end up having to be too invasive and complex to be worth it, but if you are willing to dig deeper to see if there is a way, please do and report back!

**Comment by IainHull** [comment]
I have looked into it a little. I have solved my local case using a behavior wrapper that completes a promise when the behavior stops or terminates unexpectedly.  I will look to see if it can be extended to use `Behavior#wrap` so it sticks to the behavior like a `Behaviors.supervise`

This is an example of the utility I am using at the moment (Using `Done` because client code cannot create instances if `Terminated`):

```
/**
  * Companion used to construct `WhenDone` instances
  */
object WhenDone {
  def apply(): WhenDone = new WhenDone()

  /**
    * Wrap a behavior and complete a promise when that behavior stops or terminates.
    *
    * @param wrapped
    * @param completionPromise
    * @tparam T
    */
  final private class WrappedBehavior[T](wrapped: Behavior[T], completionPromise: Promise[Done]) extends ExtensibleBehavior[T] {
    override def receive(ctx: ActorContext[T], msg: T): Behavior[T] = {
      try {
        Behavior.interpretMessage(wrapped, ctx, msg)
      } catch {
        case NonFatal(t) =>
          completionPromise.complete(Failure(t))
          throw t
      }
    }

    override def receiveSignal(ctx: ActorContext[T], msg: Signal): Behavior[T] = {
      if (msg === PostStop && !completionPromise.isCompleted) {
        completionPromise.complete(Success(Done))
      }
      Behavior.interpretSignal(wrapped, ctx, msg)
    }
  }
}
```

**Comment by patriknw** [comment]
Superseded by https://github.com/akka/akka/issues/25647

**Comment by IainHull** [comment]
That is fine, I am going to try managing the return value with a parent actor and hopefully document it.

I am very busy at the moment, but could look at #25647 week after next (I will check no one else is looking at it before I start).
