### ISSUE TITLE
Serializer missing for GetShardRegionStats$

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25348]
`GetShardRegionStats` and the response message is missing a protobuf serializer, which means that with Java serialization disabled you cannot use `GetClusterShardingStats` which uses `GetShardRegionStats` to collect node information.

**Comment by patriknw** [comment]
Ok, I think it was originally intended to only be used with the local region actor, but then it was used in the `GetClusterShardingStats` query from the coordinator.

Serializers can be added in a 2-step process:
* add the serializers in 2.5.15 but don't active the binding in reference.conf
* add the binding in 2.5.16

Then rolling upgrade can be done from 2.5.14 -> 2.5.15, and then 2.5.15 -> 2.5.16

**Comment by johanandren** [comment]
I think `ClusterShardingStats` is fine, since it is just a summary - number of entities per shard, the dangerous one is `CurrentShardRegionState` which returns all entity ids in all shards in the region - that one we should not provide a serializer for.

**Comment by btomala** [comment]
I can do it. I'm guessing this will be a blocker for this story https://github.com/akka/akka-management/issues/290

**Comment by patriknw** [comment]
Thanks @btomala

**Comment by btomala** [comment]
Hi, I review the code and few related issues https://github.com/akka/akka/issues/23250 and https://github.com/akka/akka/issues/24465 the second one is duplicate. I start work from looking on the [ClusterShardingGetStatsSpec.scala](https://github.com/akka/akka/blob/2b6997b7a04d1c085b0c6d0741e555c6fb28df04/akka-cluster-sharding/src/multi-jvm/scala/akka/cluster/sharding/ClusterShardingGetStatsSpec.scala). I turn on warnings on java serialisation in this test, but doesn't work, so I start digging and found this [Serialization.scala#L509](https://github.com/akka/akka/blob/2b6997b7a04d1c085b0c6d0741e555c6fb28df04/akka-actor/src/main/scala/akka/serialization/Serialization.scala#L509). It was surprising for me but understand that every library has nasty secrets. 
Anyway, I manage to run this test with disabled JavaSerialization. To get this we need to implement protobuf serialization for `GetShardRegionStats`, `GetShardRegionStats`, `GetClusterShardingStats` and `ClusterShardingStats`. IMHO we should implement all of them or none. The decision is up to you. Do you want to keep them for local usage only?

**Comment by patriknw** [comment]
can't hurt to add protobuf for all of them, with the rolling upgrade strategy that I mentioned

**Comment by patriknw** [comment]
The serializer was added in 
https://github.com/akka/akka/pull/2562 5, but not added to `serialization-bindings` configuration yet to be able to support rolling updates. In  2.5.19 we can add the configuration and make a note in the rolling-updates.md doc. Leaving this ticket open until then.

**Comment by patriknw** [comment]
Missed this for 2.5.19, let's do it for 2.5.20

**Comment by johanandren** [comment]
Missed again, let's enable in 2.5.21

**Comment by chbatey** [comment]
Missed again, let's enable in 2.5.22

**Comment by btomala** [comment]
Finally :smile:  :+1:
