### ISSUE TITLE
Source.queue has cases where it can not be completed

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#25349]
Looking at the implementation and running some simple tests, `SourceQueueWithComplete.complete` does not “complete the stream normally” as written in the ScalaDoc.

Calling `SourceQueueWithComplete.offer` after calling `complete` can still succeed, i.e. result in an `OfferQueueResult.Enqueued`. All you need to do is use `bufferSize` > 1 and call `offer` continuously, i.e. prevent the buffer from becoming empty. This will prevent the stream from being completed.

Is this really the desired behavior? For my usecase I would like the stream to “really” complete, i.e. calling `offer` should always result in `OfferQueueResult.Dropped`.

**Comment by hseeberger** [comment]
Also see https://discuss.lightbend.com/t/source-queue-cannot-be-completed/1559.

**Comment by hseeberger** [comment]
If the @akka/akka-team agrees, I will create a PR which changes the behavior to drop offers after `complete` has been called.

**Comment by ktoso** [comment]
Agree with your findings Heiko. Please give it a shot.

**Comment by hseeberger** [comment]
Took me some time to get back to this, but finally here we go: https://github.com/akka/akka/pull/25552
