### ISSUE TITLE
Broken link in akka-stream docs on Flow.ask

### ISSUE THREAD

**Issue by agemooij** [akka/akka#25358]
The current (2.5.14) [docs page on `Flow.ask` in streams](https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/ask.html) contains a broken link to docs on `ActorAttributes.SupervisionStrategy`, e.g. the URL https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/ActorAttributes.SupervisionStrategy.html does not exist. 

I also did not see a docs page in that same directory that looked like a good candidate to be the correct page.

**Comment by johanandren** [comment]
Thanks for reporting!

It's meant to link to the API docs, but he markup used for those is not correct to link to the scaladocs: `` [[akka.pattern.AskTimeoutException]]``

The markup should be `@unidoc[classname]`
