### ISSUE TITLE
Release 2.5.14 for 2.13.0-M3

### ISSUE THREAD

**Issue by raboof** [akka/akka#25350]
Like in #25255, further considerations:
- cherry-pick 697c0c98b79a37e76cc5fc020054ff10edbbb85b
- use jdk8

**Comment by raboof** [comment]
Done, on its way to maven central. Had to disable another test due to https://github.com/scala/bug/issues/10762

**Comment by ktoso** [comment]
Ah, thanks a lot @raboof for noticing and releasing!
