### ISSUE TITLE
JDK is not discovered on Windows

### ISSUE THREAD

**Issue by brightonk** [akka/akka#25368]
When running SBT on Windows, it did not find the JDK:

```
[error] java.util.NoSuchElementException: key not found: 8
[error]         at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:98)
[error]         at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:96)
[error]         at akka.AkkaBuild$.$anonfun$defaultSettings$6(AkkaBuild.scala:104)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

The JDK was manually installed in a custom location. The `JAVA_HOME` environment variable correctly pointed to it, so perhaps we should take into account the `JAVA_HOME` or look at the `PATH` when discovering JDK's.

**Comment by shshankar1** [comment]
It will be helpful if you can put down github url with sample code replicating scenario above.

**Comment by richardimaoka** [comment]
You can git clone this akka repository, try sbt compile on Windows and you see the same issue.

> [error]         at akka.AkkaBuild$.$anonfun$defaultSettings$6(AkkaBuild.scala:104)

The error was thrown from this line in AkkaBuild. `CrossJava.Keys.fullJavaHomes.value("8")` caused ` java.util.NoSuchElementException: key not found: 8`

```
 javacOptions in compile ++= DefaultJavacOptions ++ Seq("-source", "8", "-target", "8", "-bootclasspath", CrossJava.Keys.fullJavaHomes.value("8") + "/jre/lib/rt.jar"),
```

I think this problem is related to #24711 and #25302.
Looking at the change in 25302, no Windows discovery is defined.

```scala
+    val configs = Vector(
+      new JabbaDiscoverConfig,
+      new LinuxDiscoverConfig(file("/usr") / "java"),
+      new LinuxDiscoverConfig(file("/usr") / "lib" / "jvm"),
+      new MacOsDiscoverConfig,
+    )
```

And doing `fullJavaHomes` gave me empty `ListMap()`.

```
akka > inspect fullJavaHomes
[info] No entry for key.
[info] Description:
[info]  Combines discoveredJavaHomes and custom javaHomes.
[info] Delegates:
[info]  fullJavaHomes
[info]  ThisBuild / fullJavaHomes
[info]  Global / fullJavaHomes
[info] Related:
[info]  akka-contrib / fullJavaHomes
[info]  akka-actor-typed / fullJavaHomes
[info]  akka-docs / fullJavaHomes
[info]  akka-cluster-sharding / fullJavaHomes
[info]  akka-cluster-sharding-typed / fullJavaHomes
[info]  akka-osgi / fullJavaHomes
[info]  akka-actor-tests / fullJavaHomes
[info]  akka-stream / fullJavaHomes
[info]  akka-persistence-shared / fullJavaHomes
[info]  akka-cluster-tools / fullJavaHomes
[info] ...

akka > fullJavaHomes
[info] akka-stream-tests-tck / javaHomes
[info]  ListMap()
[info] akka-cluster-metrics / javaHomes
[info]  ListMap()
[info] akka-actor-testkit-typed / javaHomes
[info]  ListMap()
...
...
```

**Comment by shshankar1** [comment]
@richardimaoka Can you please check below steps if I am missing something? sbt compile was successful with some warning but at least compile was not failing.

shashi@shashi-PC MINGW64 /e
$ git clone https://github.com/akka/akka.git
Cloning into 'akka'...
remote: Counting objects: 374916, done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 374916 (delta 196), reused 182 (delta 163), pack-reused 374565
Receiving objects: 100% (374916/374916), 207.80 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (177896/177896), done.

shashi@shashi-PC MINGW64 /e
$ sbt compile
[info] Updated file E:\project\build.properties: set sbt.version to 1.0.0
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from C:\Users\shashi\.sbt\1.0\plugins
[info] Updating {file:/C:/Users/shashi/.sbt/1.0/plugins/}global-plugins...
[info] Done updating.
[info] Loading project definition from E:\project
[info] Updating {file:/E:/project/}root-build...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to Simple Scala Spark Project (in build file:/E:/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating {file:/E:/}root...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * commons-net:commons-net:2.2 is selected over 3.1
[warn]      +- org.apache.spark:spark-core_2.11:1.5.1             (depends on 3.1)
[warn]      +- org.apache.hadoop:hadoop-common:2.2.0              (depends on 3.1)
[warn]  * javax.activation:activation is evicted completely
[warn]      +- javax.xml.bind:jaxb-api:2.2.2                      (depends on 1.1)
[warn]  * com.google.guava:guava:14.0.1 is selected over 11.0.2
[warn]      +- org.tachyonproject:tachyon-underfs-local:0.7.1     (depends on 11.0.2)
[warn]      +- org.apache.curator:curator-recipes:2.4.0           (depends on 11.0.2)
[warn]      +- org.tachyonproject:tachyon-client:0.7.1            (depends on 11.0.2)
[warn]      +- org.apache.curator:curator-client:2.4.0            (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-hdfs:2.2.0                (depends on 11.0.2)
[warn]      +- org.apache.curator:curator-framework:2.4.0         (depends on 11.0.2)
[warn]      +- org.tachyonproject:tachyon-underfs-hdfs:0.7.1      (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-common:2.2.0              (depends on 11.0.2)
[warn]  * com.google.code.findbugs:jsr305:1.3.9 is selected over 2.0.1
[warn]      +- com.google.guava:guava:11.0.2                      (depends on 1.3.9)
[warn]      +- org.apache.spark:spark-core_2.11:1.5.1             (depends on 1.3.9)
[warn]      +- org.apache.spark:spark-unsafe_2.11:1.5.1           (depends on 1.3.9)
[warn]      +- com.fasterxml.jackson.module:jackson-module-scala_2.11:2.4.4 (depends on 2.0.1)
[warn] Run 'evicted' to see detailed eviction warnings
[success] Total time: 25 s, completed Jul 26, 2018 8:17:30 AM

shashi@shashi-PC MINGW64 /e
$ sbt sbtVersion
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from C:\Users\shashi\.sbt\1.0\plugins
[info] Loading project definition from E:\project
[info] Loading settings from build.sbt ...
[info] Set current project to Simple Scala Spark Project (in build file:/E:/)
[info] 1.0.0

shashi@shashi-PC MINGW64 /e
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
shashi@shashi-PC MINGW64 /e

$ where java
C:\Java\jdk1.8.0_151\bin\java.exe
C:\Windows\System32\java.exe

**Comment by ktoso** [comment]
Thanks @richardimaoka !
