### ISSUE TITLE
FlowOps.recoveWith a failed source never completes

### ISSUE THREAD

**Issue by jroper** [akka/akka#25382]
Using Akka 2.5.14:

```scala
Source.failed(new Exception("failed"))
  .recoverWith { case t => Source.failed(new Exception("second failed")) }
  .runWith(Sink.ignore)
```

This never completes. It should fail with `Exception("second failed")`.

**Comment by jroper** [comment]
Sorry, I just read the docs properly and saw this behaviour is expected - it's infinitely retrying.

**Comment by ktoso** [comment]
Yes, also: `  @deprecated("Use recoverWithRetries instead.", "2.4.4")`
