### ISSUE TITLE
type inference broken for Effect.persist().andThen.andThen

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#25383]
Consider the following:

        val behavior: CommandHandler[Command, Event, State] =
            Effect.persist(SomeEvent)
                  .andThen((state: State) => doStuff())
                  .andThenStop

Note the type ascription: without it, compilation fails with a “missing argument type”. Not sure exactly whether this can be fixed or is a Scala limitation; in principle the type should flow back from the expected type of the expression.

**Comment by patriknw** [comment]
The problem occur with the chained `andThen.andThen`. Works by just splitting it up, but that is not something we would recommend.
```
val x = Effect.persist(SomeEvent).andThen((state: State) => doStuff())
x.andThenStop
```

Not sure if we can do anything about this. Good thing is that such chain shouldn't be that common and once you hit it the instructions from the compiler is pretty clear.

**Comment by rkuhn** [comment]
Yes, the instructions are clear; a workaround that is not suggested by the compiler just occurred to me:

```scala
val behavior: CommandHandler[Command, Event, State] =
        Effect.persist[Event, State](SomeEvent)
              .andThen(state => doStuff())
              .andThenStop
```

This could be documented. The syntax could even be improved by adding an `apply[]` method on the `Effect` object that allows the specification of these types before the `.persist` call. Which one do you prefer?

**Comment by patriknw** [comment]
ok, thanks. I'd still prefer `state: State =>`

if too much complaints about this we could introduce `def thenRunAndThenStop(callback: State ⇒ Unit)` to minimize the need for using chained effects

**Comment by patriknw** [comment]
Closing, since there is no better alternative and the drawbacks aren't too bad.
