### ISSUE TITLE
CoordinatedShutdown.runSync

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#25384]
Both Play and Lagom have found it necessary to await shutdown of the actor system using `CoordinatedShutdown`. It calculates a timeout using `CoordinatedShutdown(actorSystem).totalTimeout()` plus a small (5s) buffer.

You can see the implementation here (copied below): https://github.com/playframework/playframework/blob/d6537a140625232d311d9411d8b921ba75c06ed2/framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L273-L294

```scala
  /**
   * Shuts down the provided `ActorSystem` synchronously, starting from the configured phase. This method blocks until
   * the actor system has fully shut down, or the duration exceeds timeouts for all coordinated shutdown phases.
   *
   * @param actorSystem the actor system to shut down
   * @param reason      the reason the actor system is shutting down
   * @throws InterruptedException if the current thread is interrupted while waiting
   * @throws TimeoutException if after waiting for the specified time `awaitable` is still not ready
   */
  @throws(classOf[TimeoutException])
  @throws(classOf[InterruptedException])
  def syncShutdown(actorSystem: ActorSystem, reason: CoordinatedShutdown.Reason): Unit = {
    // The await operation should last at most the total timeout of the coordinated shutdown.
    // We're adding a few extra seconds of margin (5 sec) to make sure the coordinated shutdown
    // has enough room to complete and yet we will timeout in case something goes wrong (invalid setup,
    // failed task, bug, etc...) preventing the coordinated shutdown from completing.
    val shutdownTimeout = CoordinatedShutdown(actorSystem).totalTimeout() + Duration(5, TimeUnit.SECONDS)
    Await.result(
      asyncShutdown(actorSystem, reason),
      shutdownTimeout
    )
  }
```

Maybe this would be useful for other Akka users. Would you consider adding it as a convenience method to the `CoordinatedShutdown` API? (I can send a pull request.)

**Comment by TimMoore** [comment]
`asyncShutdown(actorSystem, reason)` above can be read as `CoordinatedShutdown(actorSystem).run(reason)`. Currently, it also loads a configurable `runFromPhase` from config, but we're planning to remove that.

**Comment by patriknw** [comment]
I don’t think we want to have convenience for blocking (better to have it explicit with Await if really needed). It can easily be used in wrong place, e.g. Inside an actor which will prevent the ActorSystem from shutting down.

**Comment by ktoso** [comment]
Yeah in general we try to not provide such APIs... people are being thought to use Await and get on the Java APIs. Can we agree on that or do you think this really is very needed? (vote to close)

**Comment by ktoso** [comment]
Added the reopen if necessary tag :)

**Comment by TimMoore** [comment]
That's fine. Not a lot of code to copy for those who need it.
