### ISSUE TITLE
FixedSizeBuffer isEmpty return false when buffer is empty

### ISSUE THREAD

**Issue by guiCarlier** [akka/akka#25387]
The method `isEmpty` in class `FixedSizeBuffer` return true only when `used == 0`. But the method `used` can return a negative value when you `dequeue` more than `enqueue`.
This break sometime the Balance stage in the OutHandler logic for example.

**Comment by guiCarlier** [comment]
So, in `Balance`, it's necessary to test `!noPending` before calling recursively `dequeueAndDispatch()` when the current `Outlet` is closed.

**Comment by johanandren** [comment]
I think you are right, would you be up for making a PR with the fix?
