### ISSUE TITLE
Stream hang with concatted lazy failed source fed into lazy inited sink

### ISSUE THREAD

**Issue by jroper** [akka/akka#25410]
The following is a very round about way of achieving not much, but it's the best minimizer that I've been able to come up with:

```scala
  case object MyException extends Exception
  Await.result(
    Source(List(1, 2, 3))
      .concat(Source.lazily(() => Source.failed(MyException)))
      .runWith(Sink.lazyInitAsync(() => Future.successful(Sink.seq[Int])))
      .flatMap {
        case Some(future) => future
        case None => Future.successful(Seq())
      }.recover {
        case MyException => Seq()
      },
    1.second
  )
```

I expect the above program to finish with no error due to the `Future.recover` from `MyException`. However, it fails with a `TimeoutException` in Akka 2.5.14 on Scala 2.12.

**Comment by johanandren** [comment]
Haven't figured it out yet, but it could be related to the IMO very surprising behavior of `concat` #23044 (pulling eagerly on all inputs, so the `Source.lazily` is in fact not lazy in this case)
