### ISSUE TITLE
Typed persistence: register multiple onRecoveryCompleted callbacks

### ISSUE THREAD

**Issue by svroonland** [akka/akka#25428]
This is a request for the typed persistence API to make the `PersistentBehavior` a bit more composable. 

Currently, calling `onRecoveryCompleted` replaces any existing callback, so something like the following is not possible:
```scala
val behavior = PersistentBehaviors.receive { ... }
  .onRecoveryCompleted(...)

// Somewhere else, decorate the behavior with another recovery callback
behavior.onRecoveryCompleted(...)
```

Having `onRecoveryCompleted` chain  existing callbacks would be really nice to support this. I suppose the same applies to `onSnapshot`.

**Comment by patriknw** [comment]
Those callbacks have been nagging me for another reason. They are a different kind of API than we have for ordinary actors (we don't use much callbacks). I wonder if we should make them look more like signals, i.e. a signal message you receive.

```scala
      EventSourcedBehavior[Command, Event, State](
        persistenceId = PersistenceId(id),
        emptyState = State(Nil),
        commandHandler = commandHandler,
        eventHandler = eventHandler)
        .receiveSignal {
          case RecoveryCompleted(state) => ...
          case RecoverFailed(ex) =>
          case SnapshotCompleted(meta, result) =>
        }
```

Composition would be possible in similar way as Johan suggests, i.e. that the registered signal handler is accessible and can be delegated to with for example `.orElse`.

That would also make it easier to add more such signals in the future in the javadsl, which is an abstract class where we can't really add more methods.

**Comment by johanandren** [comment]
I think that's a pretty neat idea

**Comment by patriknw** [comment]
Then it could also support ordinary `Terminated` message this way.
BTW I recently added preRestart and postPost hooks and those should ofc also be like this.
