### ISSUE TITLE
[Docs] Testing docs has some broken links

### ISSUE THREAD

**Issue by jlprat** [akka/akka#25421]
Classic Actor testing page has some broken links:
- References to the Config doc page
- Reference to Ray Roestenburg blog (which is now returning 404)

**Comment by jlprat** [comment]
I'm providing a PR in a sec

**Comment by ktoso** [comment]
Thanks :)

**Comment by jlprat** [comment]
Closed via https://github.com/akka/akka/commit/545160e107fd2bf5762e09b1ff08d421706d4f3d
