### ISSUE TITLE
Reduce DDataShardCoordinator memory usage during unreachability

### ISSUE THREAD

**Issue by raboof** [akka/akka#25444]
During unreachability, the `DDataShardCoordinator` will stash any `GetShardHome` commands for shards that have not yet been loaded.

Due to retry mechanisms, when a node is unreachable for a longer time this can lead to many duplicate `GetShardHome` messages in the stash. When a large number of shards is used this amplifies the problem.

It would be a nice optimization to explicitly keep a `Set[(ActorRef, ShardId)]` with pending requests, so we can make sure they still get serviced when the update is complete, but keeping duplicates in memory will be avoided.

**Comment by fsat** [comment]
@raboof - can I get this a shot?

**Comment by ktoso** [comment]
Sure, tickets are up for grabs after all :)
Thanks!

**Comment by fsat** [comment]
Thanks @ktoso - good to hear from you :)

**Comment by fsat** [comment]
Wip branch - https://github.com/akka/akka/compare/master...fsat:wip/issue-25444 - still need to think about how to test this.

**Comment by ktoso** [comment]
Send in a PR later on, a diff gets lost like that :)

**Comment by fsat** [comment]
I will definitely, thanks! Once I figured out how to test my changes, I will raise a proper PR to be reviewed.
