### ISSUE TITLE
akka-stream not compiling on JDK 10 in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#25461]
at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk10-integrate-community-build/147/consoleFull, I'm seeing

```
[akka-stream] [info] Compiling 2 Scala sources and 1 Java source to /home/jenkins/workspace/scala-2.12.x-jdk10-integrate-community-build/target-0.9.14/project-builds/akka-stream-33aa0b38db01060eb9a348d80331bac73fa0cc09/akka-stream/target/CompileJdk9-classes ...
[akka-stream] [error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[akka-stream] [error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[akka-stream] [error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[akka-stream] [error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[akka-stream] [error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[akka-stream] [error] 5 errors found
[akka-stream] [error] (akka-stream / CompileJdk9 / compileIncremental) Compilation failed
```

doesn't happen on JDK 9, seems to be a new problem on JDK 10...?

**Comment by chbatey** [comment]
We have a build against JDK10 with 2.12.6 which is passing: https://jenkins.akka.io:8498/job/akka-nightly-jdk10/ so this looks to be an issue with something added for 2.12.7

**Comment by SethTisue** [comment]
let's test that by trying a run with vanilla 2.12.6: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk10-integrate-community-build/163/ (404 for now)

**Comment by SethTisue** [comment]
same error.

**Comment by SethTisue** [comment]
there's https://github.com/scala/bug/issues/10959, but that report says it doesn't happen unless the optimizer is enabled

**Comment by SethTisue** [comment]
can we revisit this...? this is now the most important failure in the Scala community build on JDK 10 (it's blocking 15 downstream projects)

**Comment by SethTisue** [comment]
another with the same error message is https://github.com/scala/bug/issues/10717

**Comment by patriknw** [comment]
@johanandren can you look into this?

**Comment by johanandren** [comment]
Looking into it now.

**Comment by johanandren** [comment]
Have been trying to reproduce this on my MacOS machine as well as a Linux machine with various combinations of openjdk/oracle jdk but not been able to repeat the failure.

I do remember struggling with setting the CI job though, with weird errors we never quite could explain. ( #25330 )

**Comment by SethTisue** [comment]
(perhaps this ticket shouldn't stay open given the existence of https://github.com/akka/akka/pull/25675)

**Comment by johanandren** [comment]
Yep. We also have a JDK 11 job running now https://jenkins.akka.io:8498/job/akka-nightly-jdk11/16/console (which compiles fine, but have test issues)
