### ISSUE TITLE
Support for CompletionStage<Void> in streams

### ISSUE THREAD

**Issue by jroper** [akka/akka#25475]
`CompletionStage<Void>` is quickly becoming the de facto standard for signalling completion of an operation with no return value. This doesn't integrate well into Akka Streams, since such `CompletionStage`'s will always be redeemed with `null`, and Akka Streams doesn't allow nulls. For example, it's very common to see this kind of API for committing transactions or messages:

```java
CompletionStage<Void> commit();
```

If you want to use this from Akka Streams `mapAsync`, you need to:

```java
.mapAsync(1, message ->
  message.commit().thenApply(n -> Done.getInstance())
);
```

It's even worse if you want to convert a completion signal into a source that completes when the completion stage redeems:

```java
Source.fromCompletionStage(
  message.commit().thenApply(n -> Done.getInstance())
).filter(d -> false);
```

As much as Akka doesn't like nulls, `CompletionStage` does like nulls, and I think good integration with `CompletionStage` should take this into account.

My thoughts are that `mapAsync` and `fromCompletionStage` should support nulls, converting `null` to no signal in the case of `mapAsync`, or to just the complete signal with no element in the case of `fromCompletionStage`. Another alternative is to offer `fromCompletionStageNullable` and `mapAsyncNullable`.

**Comment by patriknw** [comment]
@jroper Thanks for suggesting this compatibility convenience. I think mapAsync and fromCompletionStage could support null and do the right thing.
