### ISSUE TITLE
Docs for example Typed Persistent FSM

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25473]
For Typed `PersistentFSM` will be deprecated.

We have an example showing how Typed Actors are FSMs: https://doc.akka.io/docs/akka/current/typed/fsm.html

One for persistence would also be useful as it it'll be quite different and liley use a `byState` command handler.

**Comment by patriknw** [comment]
We can probable use a variant of the example in the migration guide: https://github.com/akka/akka/pull/27336
