### ISSUE TITLE
Avoid 'iff' in scaladoc

### ISSUE THREAD

**Issue by raboof** [akka/akka#25486]
In some places (i.e. "including the first failed element iff inclusive is true" in the javadsl Flow), we use 'iff'. This is not a typo but a 'math-ism' (https://en.wikipedia.org/wiki/If_and_only_if).

It would be nice to use simpler language. Perhaps really spell it out, like: "Terminate processing (and cancel the upstream publisher) after predicate returns false for the first time. When 'inclusive' is true, also include the element for which the predicate returned 'false'."

**Comment by raboof** [comment]
@Anjali2019 yes that would be great!

**Comment by Prsna23** [comment]
Is this issue still open? If no one is working on it, I would like to make changes.

**Comment by patriknw** [comment]
@Prsna23 That would be great, looks like there are some occurrences when searching for iff

**Comment by Prsna23** [comment]
@patriknw Cool. I will check JavaDSL Flow file and make the changes.
