### ISSUE TITLE
Confirmation messages for sharding persistent actor?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25482]
When using EntityRef.ask you expect a confirmation (`Done`) reply from the persistent actor when it has successfully persisted. Some time ago @renatocaval raised the concern that it's too much boilerplate to use this common pattern.

The `replyTo: ActorRef[Done]` must be defined in the command messages. The persistent actor must do `.andThen(_ => cmd.replyTo ! Done)`.

Previously I did an experiment of this in https://github.com/akka/akka/pull/24964

**Comment by jboner** [comment]
I think this would be very helpful.

**Comment by viktorklang** [comment]
Side-note: I would prefer a `andThenReply` effect to make this pattern less brittle and more easily discoverable.

**Comment by patriknw** [comment]
I also prefer the more explicit reply, like `andThenReply` effect. Others have argued that the problem is that users forget to reply and then get ask timeouts and therefore the completely automatic replies would be preferred. I'm worried that such might be seen as convenient at first but actually becomes too much magic. Especially since replying with `Done` is only one of many message protocols. In other cases you would need to reply with "real" values.

**Comment by renatocaval** [comment]
@viktorklang that solution means that the commands need to have an `ActorRef` and the user needs to explicitly handle the reply. That's what we were aiming to remove with the idea of auto-confirmation.

**Comment by patriknw** [comment]
enforcing `ReplyEffect` would have to be done based on the type of the incoming command, getting the type inference working for that isn't easy

**Comment by viktorklang** [comment]
@patriknw That's true—however somewhere the protocol needs to be encoded, right? I've seen some solutions requiring the response type in the command, but that leads to problems with erasure (assuming that you don't extend and provide the types statically.

@renatocaval If you can confirm without having somewhere to reply to you could have a DoneEffect. But OTOH the semantical difference between that and just doing after successful execution of returned effects is rather slim, don't you agree?

**Comment by renatocaval** [comment]
The original idea was to wrap the original command in an envelope and take care of the `replyTo` actor for the user. Something like:

**Comment by renatocaval** [comment]
This requires a type like `PersistentEntityRef` that is not the same as `EntityRef` or `ActorRef` and in which the semantics of `?` is slightly different. 

That's what Lagom has today, but the reply type is not bound to `Done`, but each command defines its own reply type using type projectiong (in Scala) or passing the .class to the ask method (verbose Java).

**Comment by viktorklang** [comment]
@renatocaval Ah, ok. Then I guess I'm leaning towards Auto Confirmation. But there's still an issue with async effects, right?

**Comment by renatocaval** [comment]
yes, there is still this issue, but again we should think of the semantics of async effects and why we want/need them. 

If an async effect fails, should I persist the events? What does that mean for the command handler? THe auto-confirmation can only happen if we clearly define what is considered `Done`. 

My understanding is that a PersistentEntity has one main purpose and that is to model a consistency boundary. Whatever we do after persisting an event, being it a sync or an async computation, is a best effort thing. If it fails, it's too late, the events are already persisted. 

In that sense, whatever happens, after persist should not impact the definition of `Done`.

**Comment by viktorklang** [comment]
@renatocaval Well, technically storing the events is an asynchronous effect, since we'd want to avoid having threads blocked for IO.

**Comment by patriknw** [comment]
> however somewhere the protocol needs to be encoded

That is about defining message protocols and all semantics can't be expressed in types. In "normal" Akka Typed messages where you expect a reply you include an `ActorRef[ReplyMessage]` in the request message. Then the receiver of the request may of course choose to ignore that reply, but then it's not following the protocol semantics (which has to be agreed upon, and documented).

**Comment by renatocaval** [comment]
That said, and looking into that with other eyes now, I think it would have been better to require a `ReplyWith[ReplyMessage]` instead of `ActorRef[ReplyMessage]`. 

It's not really an `ActorRef` that is needed, but something to express an intention that we can use to complete a `Future[ReplyMessage]`. I guess it's an actor because of historical reasons. It's replacing the old `sender`. 

Of course, what I'm saying here is only valid when calling `?` from outside an actor. For intra-actors communication, it makes lots of sense to pass an `ActorRef`.

**Comment by viktorklang** [comment]
@renatocaval I was talking about async effects, it could be calling something which returns a Future etc. And just like the persisting of Events, you want to defer processing (or declare processing successful) until the asynchronous "workflow" has completed. Does that make more sense?

@patriknw Agreed. I guess I'm saying that there's a "Command Protocol" that needs to be observed and obeyed in this case, and the option is to make part of it automatic?

**Comment by patriknw** [comment]
> It's not really an ActorRef that is needed, but something to express an intention that we can use to complete a Future[ReplyMessage]. I guess it's an actor because of historical reasons. It's replacing the old sender.

The recipient shouldn't care about if the message was sent via ask or tell. Interactions between actors are done via `ActorRef`. The request-response interaction is only one of many possible protocols and treating it special would introduce a special case (increased API surface, more to learn). That said, adding sugar for it the very common `Done` acknowledgments in persistent actors might be ok.

An anecdote is that in Akka 1.0 you had to reply in a special way when it was a request from an ask. That turned out to be a bad idea.

**Comment by patriknw** [comment]
@viktorklang Thanks for bringing up the async effects. I created a separate issue for that https://github.com/akka/akka/issues/25650 (and I don't think we need any special effect type for that). 

Such interactions are also relevant for the discussion of the auto confirmations. How would we know when to send the `Done` in that case, since it's not supposed to be sent after the first event?

**Comment by renatocaval** [comment]
> How would we know when to send the Done in that case, since it's not supposed to be sent after the first event?

Indeed, we can't know it. 

Maybe we should not have auto-confirmation as a default thing, but something that can be added when we want to use a `PersistentBehaviour` in a context where it makes sense. 

Maybe the only proper way to achieve it is to have a `PersistentEntityRef` that glues a `PersistentBehavior` with `EntityRef` and provides this functionality. 

If I don't want this functionality, then I can just use an `EntityRef`.

**Comment by patriknw** [comment]
@viktorklang I think we all have left the idea of `andThenReply` but I would like to add one more strong argument against it. I don't want to introduce several different ways of sending messages because that would violate the principle of "explicit message passing", which is the important differentiator between "location transparency" and "transparent remoting".

I have created a proposal for the automatic replies in https://github.com/akka/akka/pull/25688

**Comment by viktorklang** [comment]
That's fine. I think `andThenReply` makes sense as an effect though, because right now knowing how/when to reply requires reading reference docs.

**Comment by patriknw** [comment]
merged PR https://github.com/akka/akka/pull/25692 but keeping the ticket open until javadsl has been completed

**Comment by patriknw** [comment]
Note that this should not be started before the new javadsl builders have been completed, since I think this will also require some rework of the builders. See #25749

**Comment by patriknw** [comment]
New builders merged, so I'll continue this ticket.
