### ISSUE TITLE
Enclosing class for scaladsl.PersistentBehavior

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25484]
Should we introduce an abstract class that must be implemented for the scaladsl.PersistentBehavior? This would probably make it possible to reduce boilerplate of repeated type parameters for command and event handlers (when defining several of them).

This already exists for javadsl.

**Comment by rkuhn** [comment]
The removal of enclosing classes and the transition to function values was a deliberate decision at the core of the Akka Typed design: we achieve more safety and better compiler guarantees by removing a common source of mistakes, in particular of the kind that is hard to diagnose. Therefore I do not understand why embedding behavior functions within an enclosing class is considered at all.

An argument from first principles is that the availability of a stable scope around behavior functions is _not essential_ to the actor paradigm, hence it should not be provided. The addition of expressiveness always comes at the price of lost guarantees or invariants.

**Comment by patriknw** [comment]
Thanks for input. Usability/convenience vs first principles may be in conflict here.

**Comment by rkuhn** [comment]
If the principles are lost, usability becomes irrelevant. I also don’t buy the argument that an enclosing `Behavior.setup` is in any way less usable or less composable than requiring the enclosing class—quite the opposite.

**Comment by johanandren** [comment]
I think the decision was to not do this, so we can close this issue now?

**Comment by chbatey** [comment]
:+1:

**Comment by patriknw** [comment]
yes, that's the decision

I will still see what examples of my experiments PR still makes sense to include, but that's unrelated
