### ISSUE TITLE
More examples of Persistence Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25485]
Come up with more examples, both in Java and Scala.
The purpose is:
* to exercise the api and find shortcomings
* input to discussions to evaluate api alternatives
* some may make it into the documentation

**Comment by patriknw** [comment]
We currently have:
* https://github.com/akka/akka/tree/master/akka-persistence-typed/src/test/scala/docs/akka/persistence/typed
* https://github.com/akka/akka/blob/master/akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala
* https://github.com/akka/akka/tree/master/akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed
* https://github.com/akka/akka/blob/master/akka-persistence-typed/src/test/java/akka/persistence/typed/javadsl/PersistentActorCompileOnlyTest.java

**Comment by patriknw** [comment]
Examples for inspiration:
* https://developer.lightbend.com/docs/akka-commercial-addons/current/persistence-dc/examples.html
* https://github.com/lagom/online-auction-scala/blob/master/bidding-impl/src/main/scala/com/example/auction/bidding/impl/AuctionEntity.scala
* https://github.com/lagom/online-auction-java/blob/master/bidding-impl/src/main/java/com/example/auction/bidding/impl/AuctionEntity.java
* https://github.com/fun-cqrs/fun-cqrs/blob/develop/samples/raffle/src/main/scala/raffle/domain/model/Raffle.scala
* http://newicom.pl/akka-ddd/docs/aggregate-root/implementation#complete-examples

**Comment by patriknw** [comment]
Try things like event handlers in the state, ADT/OO style.

**Comment by johanandren** [comment]
I'm doing a more OO style thing based on the FunCQRS Raffle example.

**Comment by patriknw** [comment]
Here is a starting point by @johanandren for the Raffle sample in Java with mutable state: 
https://github.com/johanandren/akka/commit/75a60d7f6543c5d1f72fe46aeefc7485d8d5d7b9

**Comment by patriknw** [comment]
I think we have enough examples now, and we could show some more in blog posts/videos.
