### ISSUE TITLE
Scalafiddle example in akka-streams documentation doesn't compile

### ISSUE THREAD

**Issue by Prithvirajbilla** [akka/akka#25493]
scala fiddle example contains `+` char instead of `space` char, which makes it not usable. 

link: https://doc.akka.io/docs/akka/2.5.3/scala/stream/stream-quickstart.html

<img width="856" alt="screen shot 2018-08-17 at 3 38 08 pm" src="https://user-images.githubusercontent.com/1584221/44285498-931d4180-a233-11e8-898c-1b327c5e315d.png">

**Comment by ktoso** [comment]
Please browse the _current_ and not outdated documentation: 
https://doc.akka.io/docs/akka/2.5/scala/stream/stream-quickstart.html

it works, closing as we wont retroactively go back to fix this in all old published docs versions.
We will work on SEO so the new pages result as top pages in google results though.
