### ISSUE TITLE
How to use resizer with remote actors?

### ISSUE THREAD

**Issue by AnthonyJacob** [akka/akka#25519]
I want resizer to start remote routees instead of local ones. Documentation does not mention this use case. Is it even possible?

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).
