### ISSUE TITLE
Change default scalaVersion in build to 2.12

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25514]
* Would integrate better with IntelliJ.
* Better and more warnings that we would see and fix more often

We should add compile with 2.11 in the Travis PR validation job. There is a risk that one uses something new from 2.12.

Change Jenkins job that currently tests with 2.12 to test with 2.11.

**Comment by patriknw** [comment]
@chbatey I created an issue for what we talked about the other day

**Comment by chbatey** [comment]
Looks like we already compile with both in travis: https://travis-ci.org/akka/akka/builds/419981434

**Comment by chbatey** [comment]
Set nighlty 2.12 to be the nightly 2.11: https://jenkins.akka.io:8498/job/akka-nightly-2.11/
