### ISSUE TITLE
Distributed data is inconsistence

### ISSUE THREAD

**Issue by tolikr** [akka/akka#25529]
I try to use Distributed data LWWMap. My goal is keep and modify some data in between nodes.
1. Add entry if it doesn't exist.
2. If entry exist - remove it(including some custom actions), then add new entry.
3. If application replies failed on remove, trying to add entry again.

In real application i received high load and out of memory.

I created test case. It does not reproduce a problem as is, but it cannot complete without errors. 
If you need logs from real application i can load them.

[ddata-test.zip](https://github.com/akka/akka/files/2322749/ddata-test.zip)

**Comment by tolikr** [comment]
Do not close issue, please. I will try to reproduce it, and i will add logs from real application later(10 or 11 septemder).

**Comment by tolikr** [comment]
I tried to reproduce and i think i have a success:
[ddata-test.zip](https://github.com/akka/akka/files/2360346/ddata-test.zip)

I increased amount of data and add more realistic data structure.
In logs i see:

> [JVM-1] [WARN] [09/07/2018 11:58:03.261] [LWWMapCounterSpec-akka.actor.default-dispatcher-2] [akka.remote.PhiAccrualFailureDetector@374b799b] heartbeat interval is growing too large for address akka://LWWMapCounterSpec@localhost:32801: 3847 millis
> [JVM-1] [WARN] [09/07/2018 11:58:07.874] [LWWMapCounterSpec-akka.actor.default-dispatcher-4] [akka.remote.PhiAccrualFailureDetector@374b799b] heartbeat interval is growing too large for address akka://LWWMapCounterSpec@localhost:32801: 2355 millis
> [JVM-2] [WARN] [09/07/2018 11:58:08.506] [LWWMapCounterSpec-akka.actor.default-dispatcher-3] [akka.remote.PhiAccrualFailureDetector@18421927] heartbeat interval is growing too large for address akka://LWWMapCounterSpec@localhost:44401: 3318 millis
> [JVM-1] [WARN] [09/07/2018 11:58:10.604] [LWWMapCounterSpec-akka.actor.default-dispatcher-4] [akka.remote.PhiAccrualFailureDetector@374b799b] heartbeat interval is growing too large for address akka://LWWMapCounterSpec@localhost:32801: 2730 millis
> [JVM-2] [WARN] [09/07/2018 11:58:11.339] [LWWMapCounterSpec-akka.actor.default-dispatcher-21] [akka.remote.PhiAccrualFailureDetector@18421927] heartbeat interval is growing too large for address akka://LWWMapCounterSpec@localhost:44401: 2832 millis
> [JVM-2] [WARN] [09/07/2018 11:58:14.931] [LWWMapCounterSpec-akka.actor.default-dispatcher-9] [akka://LWWMapCounterSpec@localhost:32801/system/cluster/core/daemon/heartbeatSender] Cluster Node [akka://LWWMapCounterSpec@localhost:32801] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [2662] ms ago, expected interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
> [JVM-2] [WARN] [09/07/2018 11:58:15.384] [LWWMapCounterSpec-akka.actor.default-dispatcher-2] [akka.remote.PhiAccrualFailureDetector@18421927] heartbeat interval is growing too large for address akka://LWWMapCounterSpec@localhost:44401: 2901 millis
> [JVM-1] [WARN] [09/07/2018 11:58:15.735] [LWWMapCounterSpec-akka.actor.default-dispatcher-21] [akka.remote.PhiAccrualFailureDetector@374b799b] heartbeat interval is growing too large for address akka://LWWMapCounterSpec@localhost:32801: 3309 millis
> 

Timeout was increased up to 10 seconds.
Please take a look.

**Comment by tolikr** [comment]
Process load was 100 percent on my Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz.

**Comment by tolikr** [comment]
> The test kicks off all 2000 requests at the same time without any flow control. Is that realistic?

Client has own timeout on request, it equals 5 seconds by default. If they doesn't receive response on request, they will send request again.

Everything works fast when storage is simple Map(Throughoutput is limited by actor mailbox). But when i trying to add LWWMap, count of same clients cannot work with my service(When count of nodes is 2 or more).
Is overhead of exchanging between nodes so slow? Maybe it cannot be used in that manner?

**Comment by tolikr** [comment]
You may change count of nodes to 1 and see that test passed in  6 s. If nodes count is 2 or more test passed in  66 s.

**Comment by patriknw** [comment]
In this test it's faster to turn off the delta replication because there are many concurrent updates and when such deltas arrive out of order (LWWMap requires causal delivery) the deltas are skipped and fallback to full state.

If you want best performance here you should write at consistency WriteLocal. (End in 3 seconds on my machine)

Instead of creating lots of rather stateless actors like in this test it's probably better to just use one or a few that handles all requests. The main bottleneck is the Update request to the Replicator though, which will require an ack from a majority of nodes (at least 2) with your current consistency level.

**Comment by tolikr** [comment]
> The main bottleneck is the Update request to the Replicator though, which will require an ack from a majority of nodes (at least 2) with your current consistency level.

It seems like many updates require send full state. Full state is large and artery slows down. I saw feature to make artery use different channel to send big message. Maybe it will help to improve throughoutput in such cases as my?

**Comment by patriknw** [comment]
If you have many entries in the LWWMap you can try to split it up in several Maps and
In that way you get less risk of deltas arriving out of order for concurrent updates, and sending full state also becomes more manageable. For inspiration https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala#L605
