### ISSUE TITLE
Issue appearing in Akka docs, source partially left-truncated

### ISSUE THREAD

**Issue by zbeckman** [akka/akka#25564]
I'm seeing an issue in Akka docs where some source samples are partially left-truncated (the first few columns of text are missing, inconsistently, in different example code). Attaching an image as example.
<img width="1404" alt="part_1__actor_architecture_ _akka_documentation" src="https://user-images.githubusercontent.com/5351337/45009575-c09d1580-afbd-11e8-834d-c8289edc8e08.png">

**Comment by johanandren** [comment]
This is that page in the screenshot: file:///Users/johan/Code/Lightbend/Akka/akka-master/akka-docs/target/paradox/site/main/guide/tutorial_1.html#the-akka-actor-hierarchy

Confirmed that it gets rendered the same locally.

**Comment by johanandren** [comment]
Can also confirm that it isn't the pretty printing doing it, looking at the raw HTML sources it is already truncated there.

**Comment by johanandren** [comment]
Downgraded to Akka paradox plugin 0.9 (paradox 0.3.2) from 0.10 (paradox 0.4.0) and that makes the sources not truncated anymore.

**Comment by johanandren** [comment]
Manually dissecting I see that between 0.3.3 and 0.3.5 (0.3.4 doesn't work) the truncation is introduced.

**Comment by johanandren** [comment]
Two other places where it happens (trying to see the pattern): 
https://doc.akka.io/docs/akka/current/guide/tutorial_4.html#handling-the-registration-request (Scala and Java both)
https://doc.akka.io/docs/akka/current/guide/tutorial_4.html#keeping-track-of-the-device-actors-in-the-group (Scala and Java both)
https://doc.akka.io/docs/akka/current/fault-tolerance.html#test-application (third sample, Scala and Java both)

Both of those are a little bit longer, and feature a single referenced anchor name (#that-thing) in the markdown, but the handle then occurs multiple times in the actual source file so something related to "multi-snippets".

**Comment by patriknw** [comment]
@ennru is working on this

**Comment by patriknw** [comment]
current docs patched: 
https://doc.akka.io/docs/akka/current/guide/tutorial_1.html
