### ISSUE TITLE
Feature request: fast-starting ActorSystem

### ISSUE THREAD

**Issue by dsilvasc** [akka/akka#25569]
ActorSystem creation can take multiple seconds as of Akka 2.5.x.  This makes the Akka HTTP client unusable for scenarios like AWS Lambda, where cold starts are frequent.

It also slows down unit tests if they're not carefully written to all share the same actor system.

It would be nice to have a way of using the Akka HTTP client or the Akka HTTP server without the current delay that creating an ActorSystem incurs.

**Comment by dsilvasc** [comment]
References to ActorSystem startup being slow:

https://stackoverflow.com/questions/10396552/do-i-need-to-re-use-the-same-akka-actorsystem-or-can-i-just-create-one-every-tim

https://grokbase.com/t/gg/akka-user/148pvpzzt2/multiple-actorsystems-weight-uses-etc

https://stackoverflow.com/questions/17670630/scala-and-akka-lifecycle-again

**Comment by patriknw** [comment]
What is your definition/expectation of fast?

Have you profiled what is taking most time?

**Comment by dsilvasc** [comment]
I was hoping for under 100ms cold start after being AOT compiled with either Excelsior JET or GraalVM native-image.

Seems like what takes the most time are:
- `ActorSystem.Settings`, which calls `ConfigFactory.defaultReference`, which eventually calls `ConfigDocumentParser.parse`.  Do we need a defaultReference even if we pass in a Config object to `ActorSystem.apply`?
- `ActorSystem.Settings` also calls a function from object `akka.util.Helpers`.  The static initializer for Helpers calls `java.time.ZoneId.systemDefault`, which takes a bit of time.
- `ActorSystem.Settings` also calls `ReflectiveDynamicAccess.createInstanceFor`

I'll add screenshots here of the call tree from JProfiler.

**Comment by dsilvasc** [comment]
<img width="916" alt="screen shot 2018-09-05 at 17 26 20" src="https://user-images.githubusercontent.com/24484414/45122268-40141b80-b15b-11e8-8887-bbaec61e5b69.png">

<img width="575" alt="screen shot 2018-09-05 at 17 34 59" src="https://user-images.githubusercontent.com/24484414/45122284-499d8380-b15b-11e8-8964-6f0f89ada6f7.png">

<img width="642" alt="screen shot 2018-09-05 at 17 36 41" src="https://user-images.githubusercontent.com/24484414/45122343-72be1400-b15b-11e8-8898-aa0e50b0d67d.png">
<img width="728" alt="screen shot 2018-09-05 at 17 37 14" src="https://user-images.githubusercontent.com/24484414/45122346-7487d780-b15b-11e8-9483-7d853d384028.png">
<img width="752" alt="screen shot 2018-09-05 at 17 38 22" src="https://user-images.githubusercontent.com/24484414/45122353-7782c800-b15b-11e8-9532-feb9fc317205.png">
<img width="622" alt="screen shot 2018-09-05 at 17 39 01" src="https://user-images.githubusercontent.com/24484414/45122365-7d78a900-b15b-11e8-917d-d7fadaf74bf9.png">
<img width="756" alt="screen shot 2018-09-05 at 17 39 29" src="https://user-images.githubusercontent.com/24484414/45122367-7f426c80-b15b-11e8-91d9-e6c4db5e8cc8.png">
<img width="581" alt="screen shot 2018-09-05 at 17 39 56" src="https://user-images.githubusercontent.com/24484414/45122369-81a4c680-b15b-11e8-9e1e-e2529fa8189f.png">


<img width="704" alt="screen shot 2018-09-05 at 17 40 41" src="https://user-images.githubusercontent.com/24484414/45122374-879aa780-b15b-11e8-8c73-1c9ee5fc7b7c.png">
<img width="678" alt="screen shot 2018-09-05 at 17 41 00" src="https://user-images.githubusercontent.com/24484414/45122380-8bc6c500-b15b-11e8-9792-e154521c8a2d.png">
<img width="564" alt="screen shot 2018-09-05 at 17 41 27" src="https://user-images.githubusercontent.com/24484414/45122385-8ec1b580-b15b-11e8-9097-8b81235d7bd0.png">
<img width="627" alt="screen shot 2018-09-05 at 19 45 13" src="https://user-images.githubusercontent.com/24484414/45122389-91240f80-b15b-11e8-83be-93d8e7260a19.png">

**Comment by patriknw** [comment]
A quick unsigntific test:
```scala
      (1 to 1000).foreach { n ⇒
        val t0 = System.nanoTime()
        val sys = ActorSystem(s"Test-$n")
        val durMicros = (System.nanoTime() - t0) / 1000
        println(s"# $n took $durMicros us") // FIXME
        shutdown(sys)
      }
```

First iterations take 27 ms and then drops down to 5 - 20 ms.


> Do we need a defaultReference

All default values must be included and we can't expect that is done by user, and I think loading of that is cached so shouldn't matter too much if it's done twice (must be done at least once).

**Comment by raboof** [comment]
Thanks again for this discussion! There has been some progress in making it possible/easier to run Akka-based systems as a Graal native-image. It's still early days, but there's progress at https://github.com/vmencik/akka-graal-config. See also #25090 .

Of course it would still be good if starting an ActorSystem on the JVM would be as fast as possible, but it's not our top priority as a typical Actor System would be a long-running process. Perhaps we should close this one and open new tickets if there are specific things that can be improved?

**Comment by relgames** [comment]
I'm looking for the same, trying to use my akka based service in Google Cloud Run (which is like AWS Lambda). But `ActorSystem.create()` takes 1.5 seconds:

```
    public static void main(String[] args) {
        long time0 = System.nanoTime();
        var actorSystem = ActorSystem.create();
        long time1 = System.nanoTime();
        System.out.println(TimeUnit.NANOSECONDS.toMillis(time1 - time0));
    }
```
Outputs 1557

**Comment by relgames** [comment]
> Perhaps we should close this one and open new tickets if there are specific things that can be improved?

Is there a way to start Akka in 100ms? 1.5 seconds seems like a lot.

**Comment by relgames** [comment]
@patriknw I tested it on MacBook Pro (i7 2.8 GHz).

Sample project: https://github.com/relgames/akka-start-time
This one starts in ~1s, probably because it's empty project with no dependencies.

**Comment by patriknw** [comment]
tried your example, and it's indeed pretty slow the very first time. I don't think it's much we can do about that since that's probably due to that the jvm is cold. When starting and terminating in a loop my results are:
```
560
18
17
15
14
```

so you can see that already the second time it's much better (but that doesn't help you)

**Comment by relgames** [comment]
Thanks @patriknw . 
So I guess I will try with GraalVM next.
