### ISSUE TITLE
Miss character in Akka Documentation version 2.5.16

### ISSUE THREAD

**Issue by id55503** [akka/akka#25573]
Official website Akka Documentation version 2.5.16->Scala->Streams->Working With Graphs->Constructing Sources, Sinks and Flows from Partial Graphs
 **miss 'pa' behind "irUpWithToString.runWith(Source(List(1)), Sink.head)"**

**Comment by johanandren** [comment]
I think this is the same as #25564

**Comment by ktoso** [comment]
Yes, it's the same I believe. Closing as duplicate, please track that other issue @id55503. We have a fix and will release soon
