### ISSUE TITLE
Invalid OSGi bundle imports depending on com.typesafe.sslconfig.akka [0.2.3,1.0.0)

### ISSUE THREAD

**Issue by skitt** [akka/akka#25579]
The com.typesafe.akka.stream bundle ends up importing com.typesafe.sslconfig.akka with a version range of [0.2.3,1.0.0), because of the range associated with com.typesafe.sslconfig.* in the OSGi setup.

A patch is forthcoming to fix this.

**Comment by ktoso** [comment]
Thanks for offering the patch!
