### ISSUE TITLE
failed: WriteAggregator with delta: must timeout when less than required acks

### ISSUE THREAD

**Issue by raboof** [akka/akka#25581]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6346/consoleFull
```
[info] WriteAggregator with delta
[info] - must timeout when less than required acks *** FAILED *** (29 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.cluster.ddata.Replicator$Internal$DeltaPropagation, found class akka.cluster.ddata.Replicator$Internal$Write (Write(B,DataEnvelope(ORSet(a, b, c),Map(),VersionVector())))
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:510)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:482)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:896)
[info]   at akka.cluster.ddata.WriteAggregatorSpec$$anonfun$2$$anonfun$apply$mcV$sp$7.apply(WriteAggregatorSpec.scala:252)
[info]   at akka.cluster.ddata.WriteAggregatorSpec$$anonfun$2$$anonfun$apply$mcV$sp$7.apply(WriteAggregatorSpec.scala:240)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6972/consoleText

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6784/display/redirect

**Comment by johanandren** [comment]
Two failed test cases: https://jenkins.akka.io:8498/job/akka-nightly/6910/

```
akka.cluster.ddata.WriteAggregatorSpec.WriteAggregator with delta must timeout when less than required acks
akka.cluster.ddata.WriteAggregatorSpec.Durable WriteAggregator must timeout when less than required acks
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2127/testReport/junit/akka.cluster.ddata/WriteAggregatorSpec/WriteAggregator_with_delta_must_timeout_when_less_than_required_acks/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/314/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/352/testReport/junit/akka.cluster.ddata/WriteAggregatorSpec/WriteAggregator_with_delta_must_timeout_when_less_than_required_acks/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/7094/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2163/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/343/
