### ISSUE TITLE
Check deduplicate in BehaviorImpl

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25599]
I'm not sure what this means: "FIXME does this same/stopped/unhandled really belong here? Also, it does not work"
https://github.com/akka/akka/pull/25575/files#diff-d27a4c1f83bd3dcf60a300a814635a25R74

Perhaps also follow up on

**Comment by johanandren** [comment]
I think it was about whether it rather belongs in Behavior since that's where the other methods interpreting behaviors are placed.
