### ISSUE TITLE
BroadcastHub initialization race condition

### ISSUE THREAD

**Issue by fcrimins** [akka/akka#25608]
Some of my BroadcastHub consumers are occasionally missing the first message produced by the hub.  This appears to be caused by a race condition during BroadcastHub initialization.

Here's how my code works:
1. Construct stream producer
2. Construct BroadcastHub from producer
3. Attach 2 consumers to hub
4. Commence producer data streaming

Typically, in step 3, when the consumers are attached to the hub, their GraphStageLogic.preStarts (which registers them with the hub) are called right away.  So when data starts flowing in step 4 all of the necessary consumer registrations with the hub have already occurred.

In about 1 out of 10 (of my) cases however, the data streaming starts first, before the consumers' preStarts are called.  Then, as soon as the first consumer's preStart is called and hub registration occurs, the BroadcastHub is notified of the downstream demand and sends along the first producer message.  The second consumer is then registered but has already missed the first message.

One possible solution to this might be to register consumer callbacks during consumer GraphStageLogic construction rather than during preStart.

**Comment by fcrimins** [comment]
https://github.com/fcrimins/akka/tree/wip-hub-deadlock-akka-stream

**Comment by raboof** [comment]
Thanks for raising this concern! This issue has also been reported as #27163 and there is progress towards an API that makes this stable. Would that approach also work for your situation?

**Comment by fcrimins** [comment]
Yes, it would indeed.  Thank you.

**Comment by fcrimins** [comment]
Same issue as https://github.com/akka/akka/issues/27163
