### ISSUE TITLE
Akka-typed testkit's Probe.fishForMessage throws NPE on timeout instead of a timeout exception.

### ISSUE THREAD

**Issue by markehammons** [akka/akka#25616]
I was tearing my hair out trying to find where I introduced a null value into my code, when it turns out that's what ```probe.fishForMessage``` returns when it times out.

Specifically I had some code like this:

```scala
        val lockResults = probe.fishForMessage(Duration.create(10000, "ms"))(l => {
          println("got a message")
          r += 1
          if(r < 5) {
            println(s"${5 - r} left")

            try {
              l.lock.beginUse()
              l.lock.finishUse()
            } catch {
              case e: Exception =>
                e.printStackTrace()
                throw e
            }

            FishingOutcomes.continue
          } else {
            l.lock.use(()) //NPE error points here as the source!?
            FishingOutcomes.complete
          }
        })
```

I was getting 4 messages instead of 5 because of a bug in my code, so FishingOutcomes.complete was never reached. Instead of throwing something like ```TimeoutException``` it throws ```NullPointerException``` with no explanation of the result. Naturally, I assumed I was messing up (and I was in a way), not that the NPE originated from fishForMessage method timing out. Worse, the stacktrace for the NPE points at the line of code commented.

I am using the following traits in my scalatest spec: WordSpec, ActorTestKit, Assertions, DiagrammedAssertions, BeforeAndAfterAll

**Comment by patriknw** [comment]
@markehammons Thanks for reporting. Would you be able to contribute a fix?

**Comment by markehammons** [comment]
I'm not sure. I can try to hunt down where the NPE is being thrown today.

**Comment by markehammons** [comment]
I've created a rough pull request. It may not solve the problem in the fashion you'd like, but I think it makes it pretty clear what the problem is (```receiveOne(timeout)``` in fishForMessage_internal returning ```null``` if the timeout is hit). I haven't tested that my pull request works or compiles as I unfortunately do not have the time at the moment to build akka.
