### ISSUE TITLE
type inference problems with ActorContext.ask

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25611]
Is the implicit ClassTag difficult to use?

It works fine when there is a single parameter apply, but trouble when more parameters and this doesn't compile
```scala
          ctx.ask(aliceRef)(x => WhoAreYou(x)) {
            case Success(name) ⇒ TheReply(name)
            case Failure(ex)   ⇒ TheReply(ex.getMessage)
          }
```

One would have to add both request and response types
```scala
          ctx.ask[WhoAreYou, String](aliceRef)(x => WhoAreYou(x)) {
            case Success(name) ⇒ TheReply(name)
            case Failure(ex)   ⇒ TheReply(ex.getMessage)
          }
```

**Comment by johanandren** [comment]
The problem persists without the classtag so it is rather something with inferring the param type from inside of a lambda calling a method vs eta expansion of that actual method (which works).

**Comment by johanandren** [comment]
Talked to the Scala team and it seems like, if we are lucky, the partial eta-expansion will work in a future Scala version (hopefully 2.12.8)

**Comment by johanandren** [comment]
Fixed in 2.13-RC1, hopefully we'll get a backport to 2.12.8 as well: https://github.com/scala/scala/pull/7333

**Comment by adriaanm** [comment]
Backport submitted as https://github.com/scala/scala/pull/7340

**Comment by maxcom** [comment]
I tried 2.12.8 and still see the same compile error:

```
[error] XXX/Service.scala:45:55: missing parameter type for expanded function ((x$2: <error>) => statusRepo.$qmark(GetState(hostname, x$2)))
[error]     val stateF = statusRepo ? GetState(hostname, _)
[error]                                                       ^
[error] XXX/Service.scala:45:44: type mismatch;
[error]  found   : xxx.Repository.GetState
[error]  required: akka.actor.typed.ActorRef[?] => xxx.Repository.Protocol
[error]     val stateF = statusRepo ? GetState(hostname, _)
[error]                                            ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed

```

**Comment by johanandren** [comment]
It now (with 2.12.8) kind of works but not quite as good as we'd want, with this:

```Scala
final case class Foo(s: String, replyTo: ActorRef[String])
```

This works:
```Scala
ref ? (ref ⇒ Foo("bar", ref))
```

and this:
```Scala
ref ? (Foo("bar", _))
```

but this fails:
```Scala
ref ? Foo("bar", _)

[error] /Users/johan/Code/Lightbend/Akka/akka-master/akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala:59:28: missing parameter type for expanded function ((x$1: <error>) => ref.$qmark(Foo("bar", x$1)))
[error]           ref ? Foo("bar", _)
[error]                            ^
[error] /Users/johan/Code/Lightbend/Akka/akka-master/akka-actor-typed-tests/src/test/scala/akka/actor/typed/AskSpec.scala:59:20: type mismatch;
[error]  found   : akka.actor.typed.AskSpec.Foo
[error]  required: akka.actor.typed.ActorRef[?] => akka.actor.typed.AskSpec.Msg
[error]           ref ? Foo("bar", _)
```

**Comment by adriaanm** [comment]
The last expression is equivalent to `x => ref ? Foo("bar", x)` -- I guess that's not what you meant?

**Comment by johanandren** [comment]
Strange, shouldn't that work then, when `ref ? (ref ⇒ Foo("bar", ref))` works?

**Comment by adriaanm** [comment]
No, because the lambda now includes the call to ref.?, which itself is illtyped because it expects a lambda but gets a Foo

**Comment by johanandren** [comment]
Double checked on 2.12.8: 

```
ref ? x ⇒ Foo("bar", x) // fails with "not a legal formal parameter."
ref ? (x ⇒ Foo("bar", x)) // fails with "missing parameter type" and "missing argument list for method apply in object"
ref ? Foo("bar", _) // fails with "missing parameter type for expanded function"
ref ? (Foo("bar", _)) //  fails with "missing parameter type for expanded function"
```

**Comment by johanandren** [comment]
@adriaanm is it expected that none of these should work?

**Comment by johanandren** [comment]
For completeness, the ask method signature is: 
```
def ?[U](replyTo: ActorRef[U] ⇒ T)(implicit timeout: Timeout, @unused scheduler: Scheduler): Future[U]
```

**Comment by johanandren** [comment]
Oh, I think I see now, how would it know what `U` is supposed to be...

**Comment by adriaanm** [comment]
No, the key problem is that you’re calling ? with an argument of type Foo instead of a function that returns one. Look closely at the scope of the parameter of the expanded function. It’s a common source of confusion with _, when it creates a function that “spans” too much of your code.

**Comment by johanandren** [comment]
Sorry, I was thrown off by the message in the middle here which is not the same as the actual issue. I get the parenthesis and the spanning now that I think about it.

I have verified that the original issue with `ActorContext.ask` is resolved, thanks for bearing with me @adriaanm !

**Comment by dwijnand** [comment]
I tried seeing if there's a more ergonomic way to do the ask pattern.  Generally, I think `ref ? (Foo(1, _))` is just about the best option.

The alternative you could do is that rather than `?` taking strictly a `ActorRef[U] ⇒ T` you could make it take an abstract type, for which there is a typeclass instance defined for it.  Then you'd retrofit `Function1` to have an instance for the typeclass out the box.  That would allow someone to do `ref ? PartFoo(1)` and `AskPattern` would know how to give `PartFoo` and `replyTo` to make a full `Foo`.  But I'm not sure how well type inference would work.

In Scala 3 we're getting some interesting typelevel programming things, and maybe then it'll make more sense to have this.  For right now with case classes we have to either hand-roll those typeclass instances, use shapeless or macros.  I think we can live a few more years with making sure to put parens around `Foo(1, _)` to have it work.

**Comment by patriknw** [comment]
Added to style guide ticket 
https://github.com/akka/akka/issues/22805#issuecomment-458612691

**Comment by maxcom** [comment]
There is no `ask` in scaladsl, only `?`.

**Comment by dwijnand** [comment]
It would be added.

**Comment by patriknw** [comment]
@maxcom That's a funny oversight. Added issue https://github.com/akka/akka/issues/26306
