### ISSUE TITLE
StreamConverters.asInputStream sometimes swallows Source failures and reports them as timeouts

### ISSUE THREAD

**Issue by G-r-F** [akka/akka#25614]
It looks like `StreamConverters.asInputStream` sometimes silently swallows exceptions thrown inside the Source it's running with, blocks for a while and fails with an `IOException("Timeout on waiting for new data")`. I've originally encountered it while streaming AkkaHttp's `ResponseEntity.dataBytes` into a database blob, but was able to reproduce it with a much simpler case:
```
object AsInputStreamBug extends App {

  override def main(args: Array[String]): Unit = {
    val decider: Supervision.Decider = Supervision.stoppingDecider
    implicit val system = ActorSystem("default")
    implicit val materializer = ActorMaterializer(ActorMaterializerSettings(system).withSupervisionStrategy(decider))
    val blockingDispatcher = system.dispatchers.lookup("akka.stream.default-blocking-io-dispatcher")

    val f = Future {
      val errSource = Source(1 to 10)
        .map(i => {
          println(i);
          if (i == 9) throw new RuntimeException("failed") else ByteString(i)
        })
      val inputStream = errSource.runWith(StreamConverters.asInputStream(10 seconds))

      IOUtils.copy(inputStream, new ByteArrayOutputStream(), 32)
    }(blockingDispatcher)

    def logAndShutDown(result: Try[Long]): Unit = {
      result match {
        case Success(value) => println("Success")
        case Failure(ex) => ex.printStackTrace()
      }
      system.terminate()
    }

    f.onComplete(logAndShutDown)(blockingDispatcher)
  }
}
```
While I would expect it to fail with a `RuntimeException("failed")`, possibly wrapped in an `IOException`, it most often fails with `java.io.IOException: Timeout on waiting for new data
	at akka.stream.impl.io.InputStreamAdapter.$anonfun$read$5(InputStreamSinkStage.scala:167)`. However, there seems to be a timing factor involved, because every once in a while, it does propagate the original error correctly.

After a bit of debugging, the issue might be `InputStreamAdapter::grabDataChunk`, which polls the sharedBuffer, but doesn't match a `Failure` explicitly and re-throw like `read()` does.

**Comment by patriknw** [comment]
@G-r-F Thanks for reporting and providing reproducer. Would you be able to create a pull request fixing the problem?

**Comment by G-r-F** [comment]
Sure, I should be able to come up with a PR with a fix sometime later this week. However, I might need some guidance on how to write unit tests for it, as I have no experience with TestKit and reproducing the race condition on sharedBuffer polling might be non-trivial.

**Comment by helena** [comment]
@G-r-F I have initially tried to replicate and can not. It may have been fixed since your findings but I am still looking.
