### ISSUE TITLE
High memory consumption using Grouped operator in Akka Streams

### ISSUE THREAD

**Issue by dembol** [akka/akka#25623]
I’ve noticed a serious problem with high memory consumption while using streams terminated by SinkRef and `grouped` operator somewhere in a stream topology. The `grouped` operator is backed by a VectorBuilder which is cleared when `onPush` or `onUpstreamFinish` callbacks are executed. Unfortunately clearing the vector in Scala 2.12 means allocating new root node but still keeping hard references to the obsolete nodes on the higher levels of a tree which cannot be Garbage Collected. I see that some additional cleaning has been added in Scala 2.13 which will eliminate the problem in the future -  https://github.com/scala/scala/commit/845b0f0ffc59392b3dd59979f89d4f101e598236#diff-59f3462485b74027de4fd5e9febcc81bR627

The situation can be very dangerous when somebody wants to use `grouped` operator with high number of grouped elements, connect it to the sink produced by `StreamRefs.sourceRef()` and send materialized `SourceRef` over the network. Why it’s so dangerous? `SourceRefImpl` and `SinkRefImpl` start watching their partners what causes sending a WATCH SystemMessage with watchee and watcher remote paths. Those paths are deserialized by `SystemMessageSerializer.deserializeSystemMessage` which in turn calls `RemoteActorRefProvider.resolveActorRef` which uses `ActorRefResolveThreadLocalCache` backed by `LruBoundedCache`. If we have `grouped` stage with lots of heavy elements we may observe OutOfMemoryErrors in short time if we materialize many such streams.

Here are screenshots from profiler:

![telemetry](https://user-images.githubusercontent.com/1668056/45560536-b1cc2380-b845-11e8-93bc-0aec639a4669.png)

![heap_walker](https://user-images.githubusercontent.com/1668056/45561114-3d927f80-b847-11e8-89c1-b60085133bbf.png)

The quick fix is to use modified `grouped` operator using a List instead of a Vector (https://gist.github.com/dembol/b69d205ca35af7ec19453e66affbb10c) or use `grouped` operator with less than 32 elements.

**Comment by patriknw** [comment]
That's an interesting finding. Wouldn't an appropriate solution be to create a new `VectorBuilder` instead of clearing it?

We use `clear` in one other place, in [ByteStringBuilder#clear](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/util/ByteString.scala#L1193). Perhaps we should change there also to be on the safe side?

**Comment by patriknw** [comment]
@dembol would you be able to create a pull request?

**Comment by dembol** [comment]
Sure, it would be nice to start contributing :) I'll investigate a ByteStringBuilder#clear too and prepare a PR this week.

**Comment by jrudolph** [comment]
That seems to be also a candidate for an upstream fix in Scala itself. Might make sense to check if that is a known issue for `VectorBuilder`?

**Comment by hepin1989** [comment]
@dembol Are you still plan to contribute to this?

**Comment by hepin1989** [comment]
I updated the it in https://github.com/scala/scala/pull/10019

**Comment by johanandren** [comment]
If it is fixed upstream I think we can close it already now since Akka does not affect the Scala patch version of consuming project?

**Comment by jrudolph** [comment]
I agree. Fixed by scala/scala#10019 due for Scala 2.12.16, thanks for following up on that, @hepin1989!

**Comment by jrudolph** [comment]
(Not adding a milestone since nothing seems appropriate, technically it's a "will not fix (here)".)
