### ISSUE TITLE
quarantining can break akka cluster

### ISSUE THREAD

**Issue by BertRobben** [akka/akka#25632]
When a node is quarantined, it will be automatically downed and removed from the cluster. If this happens at a time when other nodes are unreachable this can lead to a split-brain situation. Problem is that the downing provider is not consulted / aware of the issue and as such can't prevent the split-brain from happening.

I explained this in more detail in 
https://discuss.lightbend.com/t/quarantine-breaks-cluster-abstraction/2141

and provided a detailed example in

https://discuss.lightbend.com/t/erroneous-split-brain-situation-in-cluster-with-properly-working-sbr/2058

As far as I understand, this issue is present in both 2.4 and 2.5

**Comment by patriknw** [comment]
I agree that we should remove that downing. I see no theoretical downsides. It will remain as Unreachable (Terminated, which means that it can't go back to Reachable) and then the ordinary downing provider has to act on that.
