### ISSUE TITLE
ClusterSingletonManager does not handle event TakeOver in state Younger

### ISSUE THREAD

**Issue by 412b** [akka/akka#25639]
**What happens**
especially when using `CoordinatedShutdown` I've observed a lot of `Ignoring TakeOver request in [Younger] from`, when oldest is shutting down, which means that handover takes way more time than it should. the reason is that new singleton holder gets aware of the oldest shutting down later than oldest has started the handover.

**What happens (detailed)** 
starting up:
> [INFO] [09/18/2018 15:38:56.744] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-19] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] Singleton manager starting singleton actor [akka://ClusterSingletonRestartSpec/user/echo/singleton]
> [INFO] [09/18/2018 15:38:56.745] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-19] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] ClusterSingletonManager state change [Start -> Oldest]
> [INFO] [09/18/2018 15:38:57.584] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/echo] ClusterSingletonManager state change [Start -> Younger]
> [INFO] [09/18/2018 15:38:57.618] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/proxy2] Singleton identified at [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo/singleton]

shutting down:
> [INFO] [09/18/2018 15:38:58.532] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] - Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] dc [default] is no longer the leader
> [INFO] [09/18/2018 15:38:58.566] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-15] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471] - Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471] dc [default] is the new leader
> [INFO] [09/18/2018 15:38:58.637] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-19] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] - Marked address [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] as [Leaving]
> [INFO] [09/18/2018 15:38:58.644] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] Exited [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553]

start of the handover:
> [INFO] [09/18/2018 15:38:58.647] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-17] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] Oldest observed OldestChanged: [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553 -> Some(akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471)]
> [INFO] [09/18/2018 15:38:58.649] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-17] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] ClusterSingletonManager state change [Oldest -> WasOldest]

new singleton holder haven't yet seen change of the oldest:
> [INFO] [09/18/2018 15:38:58.651] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-16] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/echo] Ignoring TakeOver request in [Younger] from [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553].
> [INFO] [09/18/2018 15:38:59.567] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-16] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471] - Leader is moving node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] to [Exiting]

and now new holder is aware:
> [INFO] [09/18/2018 15:38:59.573] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-3] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/echo] Younger observed OldestChanged: [Some(akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553) -> myself]
> [INFO] [09/18/2018 15:38:59.575] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-3] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/echo] ClusterSingletonManager state change [Younger -> BecomingOldest]
> [INFO] [09/18/2018 15:38:59.577] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] ClusterSingletonManager state change [WasOldest -> HandingOver]
> [INFO] [09/18/2018 15:38:59.578] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] Singleton terminated, hand-over done [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553 -> Some(akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471)]
> [INFO] [09/18/2018 15:38:59.579] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] ClusterSingletonManager state change [HandingOver -> End]
> [INFO] [09/18/2018 15:38:59.579] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/echo] Hand-over in progress at [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553]
> [INFO] [09/18/2018 15:38:59.581] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/echo] Singleton manager starting singleton actor [akka://ClusterSingletonRestartSpec/user/echo/singleton]
> [INFO] [09/18/2018 15:38:59.581] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471/user/echo] ClusterSingletonManager state change [BecomingOldest -> Oldest]
> [INFO] [09/18/2018 15:39:00.541] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-19] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] - Exiting, starting coordinated shutdown
> [INFO] [09/18/2018 15:39:00.542] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] - Exiting completed
> [INFO] [09/18/2018 15:39:00.546] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] - Shutting down...
> [INFO] [09/18/2018 15:39:00.550] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553] - Successfully shut down
> [INFO] [09/18/2018 15:39:00.551] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471] - Exiting confirmed [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553]
> [INFO] [09/18/2018 15:39:00.558] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-16] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553/user/echo] Self removed, stopping ClusterSingletonManager
> [INFO] [09/18/2018 15:39:00.566] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-19] [akka.cluster.Cluster(akka://ClusterSingletonRestartSpec)] Cluster Node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45471] - Leader is removing confirmed Exiting node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:45553]

the problem here is that in bigger real-life cluster (like we have) handover happens many `TakeOverFromMe` later, it can even give up trying.

the fix can be pretty trivial, I can submit PR right away, the main question is if going from `Younger` to `BecomingOldest` without seeing `OldestChanged` is acceptable. WDYT?

**Comment by patriknw** [comment]
Currently we trigger the `OldestChanged` by the `MemberExited` event. The problem I can see with triggering the transition earlier is that there might be a risk that the leaving process is not completed in time (e.g. unreachable nodes halting it) and then new singleton is started up too early, via `ClusterSingletonManagerIsStuck`.

I think changing this logic is far from a trivial change. I agree that we have a successful hand-over exchange we should be able to use that as evidence for that the old singleton was stopped and ok to start new. The problems are around all failure cases.

Just curious, how many seconds delay are we talking about? What cluster size? Have you tried to reduce the gossip interval?

**Comment by 412b** [comment]
@patriknw, for a cluster size of 20-30 with gossip interval of 1s it's about 20 seconds (twice the removal margin for singleton).
I've got some occasions, when it went into handover restry, when the previous oldest was already gone.

**Comment by patriknw** [comment]
That sounds very strange. Would you be able to share logs for such a real scenario? INFO level of log messages containing "Cluster Node" and the logs from the singleton managers would be interesting.

**Comment by 412b** [comment]
I wasn't lucky to get a handover timeout, but got 6 retries anyway:
new singleton owner:
> 2018-09-25T12:53:07.085Z [lp-akka-cluster-stg-akka.actor.default-dispatcher-49] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/system/cluster/core/daemon/downingProvider] c.s.c.akka.StaticQuorumDown - Received event: LeaderChanged(Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.136:2552))
> 2018-09-25T12:59:24.505Z [lp-akka-cluster-stg-lp-dispatcher-54] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Ignoring TakeOver request in [Younger] from [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552].
> 2018-09-25T12:59:25.512Z [lp-akka-cluster-stg-lp-dispatcher-54] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Ignoring TakeOver request in [Younger] from [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552].
> 2018-09-25T12:59:26.518Z [lp-akka-cluster-stg-lp-dispatcher-54] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Ignoring TakeOver request in [Younger] from [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552].
> 2018-09-25T12:59:27.527Z [lp-akka-cluster-stg-lp-dispatcher-55] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Ignoring TakeOver request in [Younger] from [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552].
> 2018-09-25T12:59:28.535Z [lp-akka-cluster-stg-lp-dispatcher-73] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Ignoring TakeOver request in [Younger] from [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552].
> 2018-09-25T12:59:29.542Z [lp-akka-cluster-stg-lp-dispatcher-55] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Ignoring TakeOver request in [Younger] from [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552].
> 2018-09-25T12:59:30.550Z [lp-akka-cluster-stg-lp-dispatcher-55] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Ignoring TakeOver request in [Younger] from [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552].
> 2018-09-25T12:59:30.822Z [lp-akka-cluster-stg-lp-dispatcher-78] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Younger observed OldestChanged: [Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552) -> myself]
> 2018-09-25T12:59:30.824Z [lp-akka-cluster-stg-lp-dispatcher-78] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - ClusterSingletonManager state change [Younger -> BecomingOldest]
> 2018-09-25T12:59:30.825Z [lp-akka-cluster-stg-lp-dispatcher-78] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Hand-over in progress at [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552]
> 2018-09-25T12:59:46.829Z [lp-akka-cluster-stg-lp-dispatcher-53] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Previous oldest [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552] removed
> 2018-09-25T12:59:46.829Z [lp-akka-cluster-stg-lp-dispatcher-53] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - Singleton manager starting singleton actor [akka://lp-akka-cluster-stg/user/master/feeds]
> 2018-09-25T12:59:46.829Z [lp-akka-cluster-stg-lp-dispatcher-53] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552/user/master] a.c.s.ClusterSingletonManager - ClusterSingletonManager state change [BecomingOldest -> Oldest]

previous singleton owner:
> 2018-09-25T12:59:24.501Z [lp-akka-cluster-stg-cluster-dispatcher-106] INFO [akka.cluster.Cluster(akka://lp-akka-cluster-stg)] a.c.Cluster(akka://lp-akka-cluster-stg) - Cluster Node [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552] - Marked address [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552] as [Leaving]
> 2018-09-25T12:59:24.504Z [lp-akka-cluster-stg-lp-dispatcher-202] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - Exited [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552]
> 2018-09-25T12:59:24.504Z [lp-akka-cluster-stg-lp-dispatcher-202] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - Oldest observed OldestChanged: [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552 -> Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552)]
> 2018-09-25T12:59:24.506Z [lp-akka-cluster-stg-lp-dispatcher-202] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - ClusterSingletonManager state change [Oldest -> WasOldest]
> 2018-09-25T12:59:25.512Z [lp-akka-cluster-stg-lp-dispatcher-297] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - Retry [1], sending TakeOverFromMe to [Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552)]
> 2018-09-25T12:59:26.518Z [lp-akka-cluster-stg-lp-dispatcher-294] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - Retry [2], sending TakeOverFromMe to [Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552)]
> 2018-09-25T12:59:27.527Z [lp-akka-cluster-stg-lp-dispatcher-294] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - Retry [3], sending TakeOverFromMe to [Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552)]
> 2018-09-25T12:59:29.542Z [lp-akka-cluster-stg-lp-dispatcher-294] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - Retry [5], sending TakeOverFromMe to [Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552)]
> 2018-09-25T12:59:30.550Z [lp-akka-cluster-stg-lp-dispatcher-155] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - Retry [6], sending TakeOverFromMe to [Some(akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.137:2552)]
> 2018-09-25T12:59:30.825Z [lp-akka-cluster-stg-lp-dispatcher-180] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/master] a.c.s.ClusterSingletonManager - ClusterSingletonManager state change [WasOldest -> HandingOver]
> 2018-09-25T12:59:31.741Z [lp-akka-cluster-stg-cluster-dispatcher-188] INFO [akka.cluster.Cluster(akka://lp-akka-cluster-stg)] a.c.Cluster(akka://lp-akka-cluster-stg) - Cluster Node [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552] - Exiting, starting coordinated shutdown
> 2018-09-25T12:59:34.511Z [lp-akka-cluster-stg-akka.actor.default-dispatcher-190] WARN [CoordinatedShutdown(akka://lp-akka-cluster-stg)] akka.actor.CoordinatedShutdown - Coordinated shutdown phase [cluster-exiting] timed out after 10000 milliseconds
> 2018-09-25T12:59:34.511Z [lp-akka-cluster-stg-cluster-dispatcher-45] INFO [akka.cluster.Cluster(akka://lp-akka-cluster-stg)] a.c.Cluster(akka://lp-akka-cluster-stg) - Cluster Node [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552] - Exiting completed
> 2018-09-25T12:59:34.516Z [lp-akka-cluster-stg-cluster-dispatcher-45] INFO [akka.cluster.Cluster(akka://lp-akka-cluster-stg)] a.c.Cluster(akka://lp-akka-cluster-stg) - Cluster Node [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552] - Shutting down...
> 2018-09-25T12:59:34.517Z [lp-akka-cluster-stg-akka.actor.default-dispatcher-91] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/system/cluster/core/daemon/downingProvider] c.s.c.akka.StaticQuorumDown - Shutting down...
> 2018-09-25T12:59:34.517Z [lp-akka-cluster-stg-cluster-dispatcher-45] INFO [akka.cluster.Cluster(akka://lp-akka-cluster-stg)] a.c.Cluster(akka://lp-akka-cluster-stg) - Cluster Node [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552] - Successfully shut down
> 2018-09-25T12:59:34.519Z [lp-akka-cluster-stg-lp-dispatcher-155] INFO [akka.tcp://lp-akka-cluster-stg@xxx.xxx.xxx.138:2552/user/lcoo-downloader] a.c.s.ClusterSingletonManager - Self removed, stopping ClusterSingletonManager

unfortunately there was a timeout stopping the singleton there due to faulty component, but it's anyway about retries.
cluster size was around 40 nodes, gossip interval was 1 s and it took around 6 s for new singleton owner to get the trigger.

**Comment by patriknw** [comment]
6 seconds for 40 nodes sounds more reasonable than 20 seconds for 20 nodes

you can try to change the gossip interval to 500 ms

I'll get back to this in more detail on Monday

**Comment by patriknw** [comment]
Here are my notes, structured around coordinated shutdown phases. Probably not useful for anyone else:
```
- cluster-sharding-shutdown-region // Emit the leave command for the node that is shutting down.
  - GracefulShutdown of shard region
- cluster-leave // Emit the leave command for the node that is shutting down.
  - cluster.leave, wait until MemberLeft (or MemberRemoved)
- cluster-exiting // Shutdown cluster singletons
  - "wait-exiting" wait until selfStatus == Exiting (also coordShutdown.run if initiated via leaving)
  - singleton-exiting-1"
    - remove self in OldestChangedBuffer
      - send TakeOverFromMe
        - TakeOverFromMe is ignored on new oldest until in BecomingOldest state, i.e. Younger sees itself as oldest which happens when it sees MemberExited of previous oldest
      - goto WasOldest
      - receive HandOverToMe => stop singleton instance, then send HandOverDone
    - not waiting for anything (other than the ask)
  - "wait-singleton-exiting"
    - wait for memberExitingProgress, which is when handOverDone, which is when singleton instance has terminated 
  - "singleton-exiting-2"  
- cluster-exiting-done // Wait until exiting has been completed
- cluster-shutdown // Shutdown the cluster extension
```
