### ISSUE TITLE
Remove scaladsl CommandHandler.byState

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25655]
No real value over using plain pattern matching.

This is already done in javadsl, or replaced by something else in javadsl builders.

**Comment by johanandren** [comment]
I'll do that right away the ActorContext PR, since I'm anyways deleting stuff.

**Comment by patriknw** [comment]
sounds good to get rid of the cruft in preparation for next week

**Comment by patriknw** [comment]
that's unrelated

The purpose of `byState` was to pick a command handler based on the given state, but that can be done with an ordinary function as far as I can see.

Example:
```scala
  private def commandHandler: CommandHandler[AccountCommand, AccountEvent, Account] =
    CommandHandler.byState {
      case EmptyAccount     ⇒ initialHandler
      case OpenedAccount(_) ⇒ openedAccountHandler
      case ClosedAccount    ⇒ closedHandler
    }
```

vs

```scala
  private val commandHandler: CommandHandler[AccountCommand, AccountEvent, Account] =
    (state, cmd) => state match {
      case EmptyAccount     ⇒ initialHandler(state, cmd)
      case OpenedAccount(_) ⇒ openedAccountHandler(state, cmd)
      case ClosedAccount    ⇒ closedHandler(state, cmd)
    }
```

or 

```scala
  private val commandHandler: CommandHandler[AccountCommand, AccountEvent, Account] =
    {
      case (state @ EmptyAccount, cmd)     ⇒ initialHandler(state, cmd)
      case (state @ OpenedAccount(_), cmd) ⇒ openedAccountHandler(state, cmd)
      case (state @ ClosedAccount, cmd)    ⇒ closedHandler(state, cmd)
    }
```

plain Scala, nothing new to learn, and more powerful if needed, such as using the substateCommandHander that I sketched in https://github.com/akka/akka/pull/25503/files#diff-33ab95bda9811733ceba30ab72e2090dR93

**Comment by johanandren** [comment]
No real need to keep `CommandHandler.command` either? All it does is `_`:ing the state parameter.

**Comment by patriknw** [comment]
let's leave that for now, I think it's fairly common with command handlers that don't care about the state

we had similar discussion about `Behaviors.receive` and `receiveMessage` and it's indeed nice with the single param one

**Comment by patriknw** [comment]
Done in https://github.com/akka/akka/pull/25654
