### ISSUE TITLE
akka cluster sharding formation problem

### ISSUE THREAD

**Issue by alanngai** [akka/akka#25658]
opening this bug to follow up on https://github.com/akka/akka-management/issues/306

I reran the application and this time the cluster didn't form properly at all.  Here are the debug logs

[node2-debug.log](https://github.com/akka/akka/files/2402763/node2-debug.log)
[node1-debug.log](https://github.com/akka/akka/files/2402764/node1-debug.log)

**Comment by alanngai** [comment]
closing this bug.  looks like cluster sharding regions need to be created for each node, and since I'm creating it within a singleton actor, only one region on one node gets created, explaining the errors around propagating shard state to other nodes.  The alternative way to do this is to create the shard regions within a non-singleton actor (and therefore a region would be created on each node), and then use a singleton actor to initialize the entities

**Comment by patriknw** [comment]
Sharding should be initialized on all nodes. Do it as early as possible, typically at the same place where you start the `ActorSystem`, not from inside an actor that might be started or started later.

Documented as:

> When using the sharding extension you are first, typically at system startup on each node in the cluster, supposed to register the supported entity types with the ClusterSharding.start method.
