### ISSUE TITLE
Add better automatic checking for mismatched Akka module versions

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#25652]
This can happen on two axes:
 * akka version itself
 * when used from Java, also the Scala version

We already have the `akka.Version` object and `akka.AkkaVersion` for checking but that way of doing things will fail e.g. if jars for both `akka-actor_2.11` and `akka-actor_2.12` will be on the classpath at the same time.

One solution would be to add a section to the config of each module which contains metainformation about each module, e.g. a section

```
akka.modules += {
  name = "akka-actor"
  version = "2.5.16"
  scala-version = "2.12.5"
  scala-binary-version = "2.12"
}
```

We could auto-generate that section in the build and write it to a `version.conf` file that is or is not included from the main `reference.conf`.

The advantage of using this scheme is that using HACON is well-known to us, we don't have to enumerate the classpath to find modules, but can just read those entries from the config and check it for any mismatched versions. The other advantage is that common jar packers like sbt-assembly already know how to aggregate those files (though we need to be careful with includes in that case).

**Comment by ktoso** [comment]
I think it would be worth asking the Scala team if they would consider adding into MANIFEST the scala version itself somehow -- for the scala library. WDYT @retronym ?

**Comment by jrudolph** [comment]
Added a comment that we already have `akka.Version` and `akka.AkkaVersion` and why I think it isn't enough.

**Comment by patriknw** [comment]
Somewhat related to https://github.com/akka/akka/pull/25563
