### ISSUE TITLE
module not found: com.typesafe.akka#akka-cluster-singleton_2.12;2.5.16

### ISSUE THREAD

**Issue by JohnReedLOL** [akka/akka#25676]
I am trying to import this into my SBT project:

https://i.imgur.com/dkfq22u.png

My build.sbt file looks like this:

https://gist.github.com/JohnReedLOL/348e32bccaf85b725fd3c9bea53b5e81

And I am getting this error message:

https://i.imgur.com/l5jGHM2.png

Full text:

https://gist.githubusercontent.com/JohnReedLOL/04f626d27929ba88164fd5e51a49245c/raw/9a0bfd1bf12ab9fd6aca6f66f429235e112584b6/Error.txt

The error appears ever time I uncomment this line in build.sbt and save:

`// libraryDependencies += "com.typesafe.akka" %% "akka-cluster-singleton" % "2.5.16"`

The code is taken from: 

https://developer.lightbend.com/start/?group=akka&project=akka-quickstart-scala

IntelliJ Version: https://i.imgur.com/JVlQQcb.png

akka-quickstart-scala/project/build.properties file: https://i.imgur.com/1o39n0L.png

**Comment by johanandren** [comment]
There is no separate module for cluster singleton, it is in the module `akka-cluster-tools`.

Please use the forums (https://discuss.akka.io) or gitter for questions like this and only use the issue tracker for bugs and feature tracking. Thanks!
