### ISSUE TITLE
Akka Typed: Logger not using class name when logging in Behavior

### ISSUE THREAD

**Issue by herzrasen** [akka/akka#25677]
Hi,

when using ctx.log to log inside a Behavior, the Logger is always  `akka.actor.typed.Behavior` and not the Class the Behavior is implemented in, which is quite misleading and does not allow filtering the logs on class level.

**Comment by patriknw** [comment]
ok, let's see what we can improve here.
However, note that there is not always a class, only a function.

**Comment by patriknw** [comment]
Good idea.

**Comment by johanandren** [comment]
The "name" for different instances should already be covered by the default behavior which is to use the actor path as logger source which will be different for different instances, so I think this is just a question of enabling that getting included in your logging infra and no need for additional API.

I'm looking into the class aspect, leaning towards that we'd need something like what you proposed for the the  `withLoggerClass` but also exploring other more automagic ideas.

**Comment by danbim** [comment]
> The "name" for different instances should already be covered by the default behavior which is to use the actor path as logger source which will be different for different instances, so I think this is just a question of enabling that getting included in your logging infra and no need for additional API.

Without being able to double-check ATM the behavior I last observed was that my logging had the class name as logger name (`akka.actor.typed.Behavior`). According to the Akka docs (https://doc.akka.io/docs/akka/2.5/logging.html) this is to be expected:

> The SLF4J logger selected for each log event is chosen based on the Class[_] of the log source specified when creating the LoggingAdapter, unless that was given directly as a string in which case that string is used (i.e. LoggerFactory.getLogger(c: Class[_]) is used in the first case and LoggerFactory.getLogger(s: String) in the second).

Could you provide some guidance on how to get the "logger source" (I believe you mean `LogEvent.logSource` here, right?) being used as the logger name? Maybe as part of the Akka (Typed) docs?

**Comment by johanandren** [comment]
It depends a bit on the logger implementation you use, there's an example for logback in the docs here: https://doc.akka.io/docs/akka/current/logging.html#logging-thread-akka-source-and-actor-system-in-mdc
