### ISSUE TITLE
The api doc should meet the Scala 2.12 style.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#25702]
The current api style is sit in the old style see [this](https://doc.akka.io/api/akka/current/index.html), hope it regenerated in the 2.12 style:).

![image](https://user-images.githubusercontent.com/501740/46252873-af063b00-c4a1-11e8-9d8a-174ed5c3d9f3.png)
![image](https://user-images.githubusercontent.com/501740/46252878-c80eec00-c4a1-11e8-87f7-0a628aae44ce.png)

**Comment by raboof** [comment]
I re-generated and uploaded the API docs - they look strange right now but I think that's the cloudflare cache, so it should recover in a while. If not then there's more work to do ;)

**Comment by hepin1989** [comment]
666，thanks。

**Comment by raboof** [comment]
Seems good now indeed
