### ISSUE TITLE
application-test.conf for typed testkit

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25708]
In a recent discussion: https://github.com/akka/akka/pull/25669#discussion_r219506855
we talked about that it would be nice if the typed testkit would load an `application-test.conf` config file for setup you want in all your tests, and that you wouldn't want it to load the default `application.conf` since that would be production settings (for example, if you are using cluster, but you may want most of your tests to run on a local actorsystem only since it just tests actors)

**Comment by patriknw** [comment]
right, and currently it's very confusing because it loads application.conf if no `Config` parameter is used, but not otherwise
