### ISSUE TITLE
Fix fallback DNS name server resolution using reflection in DnsSettings

### ISSUE THREAD

**Issue by carlosrogue** [akka/akka#25701]
From Akka Team [tweet](https://twitter.com/akkateam/status/1045624340786630662) to 2.5.17 release [announcement](https://akka.io/blog/news/2018/09/27/akka-2.5.17-released) to 2.5.17 [milestone](https://github.com/akka/akka/milestone/133?closed=1) to this issue #25635 and to this pull request #25636, while checking `DnsSettings`, I found this:

https://github.com/akka/akka/blob/d7c463e033a17a0f7c06997ee768d406c1359c33/akka-actor/src/main/scala/akka/io/dns/DnsSettings.scala#L120

**Comment by carlosrogue** [comment]
Also, I found this similar issue (_regarding failing on JDK9+ comment_): https://issues.apache.org/jira/browse/HADOOP-15764

**Comment by Captain1653** [comment]
This issue is already fixed and should be closed.

<img width="1622" alt="Screenshot 2023-08-28 at 21 23 26" src="https://github.com/akka/akka/assets/4740207/c875d727-ff9d-4a1c-b3c7-a076cd05a8d9">
