### ISSUE TITLE
andThen vs thenRun

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25706]
@chbatey In scaladsl we introduced `thenRun` for the callback side effect. Any reason for not doing the same in javadsl?

**Comment by chbatey** [comment]
From my sketchy memory we only renamed it to thenRun so that you could pass in a partial function to andThen in the scaladsl. The compiler did not like them being the same name when doing that. So no reason not to rename the Java one.

**Comment by patriknw** [comment]
ok, but perhaps good to keep them consistent anyway, makes it easier when documenting and teaching

**Comment by patriknw** [comment]
another inconsistency in the scaladsl is use of `()` or not, for example

```
def stop[Event, State]: Effect[Event, State]
def andThenStop(): Effect[Event, State]
```
