### ISSUE TITLE
Akka Typed ActorContext and child types

### ISSUE THREAD

**Issue by huntc** [akka/akka#25712]
I was wondering if consideration had been given to `ActorContext` being able to return specific types of children e.g.:

```scala
def children: Iterable[ActorRef[Nothing]]
```

to become

```scala
def children[T]: Iterable[ActorRef[T]]
```

As it presently stands, I found myself doing things like:

```scala
context.children.foreach {
  case child if child.path.name.startsWith(SomePrefixConvention) =>
   child.upcast ! SomeAcceptableMessage
}
```

**Comment by hepin1989** [comment]
So to collect a sub-collection of children who support a dedicated protocol?

**Comment by huntc** [comment]
> So to collect a sub-collection of children who support a dedicated protocol?

Yes.

**Comment by patriknw** [comment]
The `ActorRef` itself doesn't know, that info is erased. Adding a `Class` or `ClassTag` would make serialization/deserialization difficult. Then we would have to keep track of the types separately in the `children` collection, making it more heavyweight and more difficult to `spawn` children.

I suggest that you keep track of such children in your own collection in your Behavior when you need this.

**Comment by huntc** [comment]
Thanks for the explanation, Patrik. I'll close the issue.

**Comment by patriknw** [comment]
Thanks for raising the question. Glad to see that you are using Typed. Let us know if you find other things.
