### ISSUE TITLE
Rename ClusterSharding.start to init in Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25711]
Some uncertainties about what `start` means. What is started?

`init` is good since it conveys that it's something that should be done once early when the system is started up

**Comment by hepin1989** [comment]
Yes,it should be initializating and initialized.

**Comment by dwijnand** [comment]
Fixed in #25867.

**Comment by dwijnand** [comment]
Oh right, that didn't target master.

While I'm here, is there a reason you don't use the "Fixes #25711" to auto-close PRs?  https://help.github.com/articles/closing-issues-using-keywords/

**Comment by patriknw** [comment]
@dwijnand it's perfectly ok to use Fixes but then you have to anyway check that the issue has the right milestone assigned (since we use the milestones for our release notes)
