### ISSUE TITLE
deprecate Props.create without actorClass parameter

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25718]
It can't be used with lambdas and I can't imagine someone crafting a Creator themselves nowadays and if so the additional class parameter wouldn't hurt much.

**Comment by hepin1989** [comment]
Yes, this is troublesome.

**Comment by dwijnand** [comment]
Fixed in https://github.com/akka/akka/pull/25713, part of 2.5.18.

**Comment by dwijnand** [comment]
Close and assign milestone?

**Comment by patriknw** [comment]
Thanks
