### ISSUE TITLE
Rename PersistentBehavior

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25721]
@viktorklang suggested that we should rename `PersistentBehavior` because it's not the Behavior that is stored.

I think the background of the name is from PersistentActor and PersistentEntity.

One suggestion is `PersistingBehavior`.

**Comment by viktorklang** [comment]
PersistanceBehavior?
EntityBehavior?

**Comment by johanandren** [comment]
I think we should keep the current name to make it easy to find for existing users of `PersistentActor`, even if there could potentially be more correct names.

**Comment by TimMoore** [comment]
How about `EventSourcedBehavior`? It describes that the behavior is dependent on the event stream. It would also open up an opportunity for other kinds of persistence to be added in the future.

I take your point @johanandren but there are enough differences between the way that `PersistentActor` and `PersistentBehavior` are used that people are going to need to read the migration docs regardless.

**Comment by johanandren** [comment]
Fair enough. Then I like EventSourced/ing best since Persisting could be done in more ways than eventsourcing.

**Comment by viktorklang** [comment]
I think EventSourcedBehavior makes sense (if we decide not to unify the CRUD and CRUD+EL in the same thing).

**Comment by chbatey** [comment]
I like EventSourcedBehavior, and we could rename akka-persistence-typed to akka-event-sourcing to prevent the misinterpretation that it is the only way to do persistence with akka.

**Comment by WadeWaldron** [comment]
> I think EventSourcedBehavior makes sense (if we decide not to unify the CRUD and CRUD+EL in the same thing).

Perhaps we need to figure out our plans for CRUD/CRUD+EL before we make the decision then. What we do there might dictate what we do here.

I actually think that `EventSourcedBehaviour` isn't really any better than `PersistentBehaviour`. It's not really the `Behaviour` that is Event Sourced. It's the state. Or perhaps more accurately it's actually the state and behaviour.

This is actually one of my biggest concerns with the Typed API in general. By eliminating the concept of an Actor and/or Entity we have created a gap in the terminology. Actors encapsulate state and behaviour so the term Actor would work well here, but we don't have that term to draw on.

**Comment by patriknw** [comment]
> CRUD and CRUD+EL

I think it would be enough if that API is (source) similar and not necessarily **the** same. The implementation would anyway be very different and doesn't make much sense to have an instance that is both event sourced and CRUD.

**Comment by viktorklang** [comment]
@patriknw I'm not sure I agree. Being able to programmatically (Effect) store the state as a part of the command processing makes a ton of sense, for instance when you have made an expensive calculation and want to make sure that it doesn't need to get replayed. It would be my personal preference to see if it is possible to fit it under the same API.

One possible way of dealing with the EventSourcing part is to have that be a demarcation on the State type. Since, it is as @WadeWaldron says: the state which is event sourced. Then the State could have an applyEvent method.

**Comment by TimMoore** [comment]
Even if there is some unification of the event-sourced, CRUD, and event-log APIs, I would expect that there would still be some differences, too. For one thing, they wouldn't all have event handlers. So to me it makes sense to start with what we know we have (`EventSourcedBehavior`) and then extract out any commonalities once we start to introduce new ones.

**Comment by TimMoore** [comment]
@WadeWaldron my understanding is that in Akka Typed, the behavior is considered to encapsulate state. In the case of immutable behavior, it closes over it and returns a new behavior to transition state. It seems to me like the behavior _is_ event-sourced, as the command handler that is in effect depends on the state (i.e., the result of replaying events from the last snapshot).

I suppose this is a new concept for people already used to Akka Untyped, but OTOH, it's a different enough model that reusing the same terminology could be more confusing. For new users, I'm not sure it will make much difference.

**Comment by patriknw** [comment]
I like `EventSourcedBehavior`

**Comment by helena** [comment]
Currently in akka-persistence-typed there exists [object EventsourcedBehavior](https://github.com/akka/akka/blob/master/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventsourcedBehavior.scala#L17)

**Comment by patriknw** [comment]
That is internal, and can be renamed to EventSourcedBehaviorImp, or whatever
