### ISSUE TITLE
Java documentation for Typed Actors references Scala features

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#25731]
In the section titled ["A More Complex Example"](https://doc.akka.io/docs/akka/current/typed/actors.html?language=java#a-more-complex-example), the Java version includes this bullet point that is intended for Scala:

> Using a sealed trait and case class/objects to represent multiple messages an actor can receive

Maybe for Java the equivalent would be something like "Using immutable classes to represent multiple messages an actor can receive".

**Comment by TimMoore** [comment]
There are some Scala-isms in this section, too: https://doc.akka.io/docs/akka/current/typed/actors.html?language=java#relation-to-akka-untyped-actors

**Comment by patriknw** [comment]
Thanks for reporting

**Comment by johanandren** [comment]
Looks like this was already fixed in other docs reworks https://doc.akka.io/docs/akka/2.6/typed/actors.html?language=java#a-more-complex-example
