### ISSUE TITLE
Support know subtype of state in thenRun Effect

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25737]
Sometimes you know that the concrete state is of a certain subtype of the `State`, but `thenRun` only has `State` as parameter type.

Scala example:
```scala
          Effect
            .persist(Withdrawn(amount))
            .thenRun {
              case OpenedAccount(balance) ⇒
                // do some side-effect using balance
                println(balance)
              case _ ⇒ throw new IllegalStateException
            }
```

Java example:
```java
          return Effect().persist(new Withdrawn(cmd.amount))
            .andThen(acc2 -> {
              // we know this cast is safe, but somewhat ugly
              OpenedAccount openAccount = (OpenedAccount) acc2;
              // do some side-effect using balance
              System.out.println(openAccount.balance);
            });
```

**Comment by patriknw** [comment]
I tried this for Java:
```
final def andThen[NewState <: State](callback: function.Procedure[NewState]): Effect[Event, State]
```

That seems to work fine, if the parameter type is added:
```java
          return Effect().persist(new Withdrawn(cmd.amount))
            .andThen((OpenedAccount acc2) -> {
              // do some side-effect using OpenAccount.balance
              System.out.println(acc2.balance);
            });
```

If it's not added it falls back to `Account` as desired.

Other types cannot be used, e.g. `String acc2`.

It will of course blow up in runtime if it's not the given type.

**Comment by patriknw** [comment]
In Scala that trick doesn't work well:
```
final def thenRun[NewState <: State](callback: NewState ⇒ Unit): Effect[Event, State]
```

It works if the type is specified:
```scala
          Effect
            .persist(Withdrawn(amount))
            .thenRun { newAccount: OpenedAccount ⇒
              // do some side-effect using balance
              println(newAccount.balance)
            }
```

and also with 
```scala
.thenRun[OpenedAccount] { newAccount =>
```

but if the type is not specified it is inferred to `Nothing`.

**Comment by patriknw** [comment]
In Scala it's probably alright to use pattern matching instead of the extra type, but then it might be worth changing this to a partial function, to avoid exhaustiveness check warnings?

**Comment by johanandren** [comment]
If you changed your apply though, so that it would return a new state, and forgot to update the command handler, wouldn't you rather want to know that then silently have it ignored?

**Comment by patriknw** [comment]
I was thinking that we would throw IllegalStateException if th PF is not defined.

**Comment by TimMoore** [comment]
@patriknw all of this sounds good to me

**Comment by johanandren** [comment]
After some experiments my conclusion is that this is not possible to do nicely in the Scala API, but the Java API idea worked.

**Comment by patriknw** [comment]
I'd say that ordinary pattern match is sufficient for scaladsl
