### ISSUE TITLE
Rename akka.actor.typed.ActorContext

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25734]
Name conflicts when defining ExtensibleBehavior or BehaviorInterceptor in same file as ordinary javadsl.ActorContext is used.

Noticed by @TimMoore here https://github.com/akka/akka/pull/25728#discussion_r222559651

**Comment by TimMoore** [comment]
@patriknw do you have a preferred new name?

**Comment by patriknw** [comment]
@TimMoore I don't have a good naming suggestion. The only that comes to my mind are `ActorContextBase` or `CommonActorContext`.

**Comment by dwijnand** [comment]
`GenericActorContext`? `AbstractActorContext`?

**Comment by patriknw** [comment]
I don't like any of the names, but in lack of better suggestions I'd say `ActorContextBase`. This shouldn't be much visible to end users.

**Comment by helena** [comment]
This is a reoccurring symptom of a larger design problem in the Akka Typed implementation overall - in actor, cluster, Sharding, Singleton, DD. We're all aware of it and feeling the pain points, during expansion. I've been looking into [#25746](https://github.com/akka/akka/issues/25746) and noticed these issues, making the api - internal and external - overly confusing and not clean. I am guessing it is too late for a redesign but I think we could benefit from a compromise of design change, to help resolve and prevent these, and compatibility, something acceptable. This just seems like growth that's expanding along many paths with too little structure to ensure sanity. I may make a base proposal in the course of starting [#25746](https://github.com/akka/akka/issues/25746)'s design change.

**Comment by helena** [comment]
Back to the issue at hand, given:
1. We have:
```
akka.actor.ActorContext
akka.actor.typed.javadsl.ActorContext
akka.actor.typed.scaladsl.ActorContext
``
2. We don't want everyone to have to sprinkle things like this around as a work-around
`import akka.actor.typed.scaladsl.{ ActorContext ⇒ SAC }`
 
3. I don't advocate going down the naming road offered above (*Base*, *Common* and friends) outside of a testkit, for reasons

I suggest, and would event expect
`ActorContextT` - T for typed. It's 
* Easy to identify what it is - same name just a suffix T
* Won't get 

`A

My concern in my design sentiments above is the growing amount of boilerplate being written and tested to work around the base, the typed and its java and Scala apis for all typed modules - current and future.

**Comment by helena** [comment]
I looked at existing Akka naming conventions and nothing made sense until I saw TypedActor, which I like in the context (no pun intended) of the akka.actor.typed.ActorContext[_] =>  TypedActorContext[_] for simplicity. Which additionally coincides with conventions like ActorRefProvider, ClusterActorRefProvider, RemoteActorRefProvider and so forth.
