### ISSUE TITLE
On stopping an Actor chain (parent-> child->child) CPU consumption shoots up.

### ISSUE THREAD

**Issue by pranavkapoorr** [akka/akka#25745]
On stopping actor chain, CPU consumption shoots to 100%.

Here is the link to the original issue inside my repo:

https://github.com/pranavkapoorr/AltaPay-Link_Service/issues/1#issue-366608337

**Comment by raboof** [comment]
Hi @pranavkapoorr ,

This seems more like a question for help with your application than an issue with the library itself. As such it might fit better at https://discuss.akka.io. 

If you are convinced this is an issue with Akka itself, feel free to reopen this issue with a minimal reproducer showing the problem. Thanks!

**Comment by pranavkapoorr** [comment]
Hi @jrudolph 

thank you for sparing some time on my issue.
I have tried it on Windows, MacOs as well as Ubuntu. Same result.

:(
