### ISSUE TITLE
Typed Distributed Data requires untyped Cluster

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25746]
Since we use the original replicated datatypes and operations on those require a Cluster, would be good if we could have some nicer solution for using them in typed.

**Comment by patriknw** [comment]
I have wanted to introduce some cluster independent type and perhaps this is the moment we should. The only thing that is needed in the end is the `selfUniqueAddress`. `UniqueAddress` isn't unique enough as type to use as an implicit so we would have to add a new more specific type for this.

I don't know if it's possible to do in a compatible way. In java it's probably ok to add overloaded methods. In scala it's an implicit in second param list so overload will probably not work?

**Comment by helena** [comment]
@patriknw can you elaborate a bit on this?

>  UniqueAddress isn't unique enough as type to use as an implicit so we would have to add a new more specific type for this.

Thanks

**Comment by patriknw** [comment]
Currently the API is based on `implicit node: Cluster`, which should be the self node, i.e. `Cluster(system)`. E.g. in `ORSet`:

```
def +(element: A)(implicit node: Cluster): ORSet[A]
```

It's only the `UniqueAddress` that we need in the end, `node.selfUniqueAddress`.

Implicit parameter types should be rather specific, and I think `UniqueAddress` itself is not specific enough so we need to introduce another type, something like
```
final case class SelfUniqueAddress(uniqueAddress: UniqueAddress)
```

For the non-implicit parameter (Java API) we can use `UniqueAddress`.

**Comment by helena** [comment]
Ah, that `implicit`, in its current form it is an overly heavy weight pattern and agree that specifying is an improvement. `SelfUniqueAddress ` sounds good.

**Comment by patriknw** [comment]
What we are trying to fix is that `akka.cluster.Cluster` is the untyped `Cluster`, and that can be confusing since other cluster things are using `akka.cluster.typed.Cluster`. 

There is another challenge here. It's not possible to add an overloaded method that is only different in second parameter list. We can't have:
```
def +(element: A)(implicit node: Cluster): ORSet[A]
def +(element: A)(implicit node: SelfUniqueAddress): ORSet[A]
```

**Comment by patriknw** [comment]
@helena What do you think about adding overloaded methods replacing the `Cluster` parameter with `SelfUniqueAddress` and make that the way we want it to be used for both Typed and Untyped. Deprecating the methods with `Cluster`.

For the `+` method we have to use another name, which could be `:+`.

Something like this:

```scala
  def :+(element: A)(implicit node: SelfUniqueAddress): ORSet[A] = add(node, element)
  
  @deprecated("Use `:+` that takes a `SelfUniqueAddress` parameter instead.", since = "2.5.19")
  def +(element: A)(implicit node: Cluster): ORSet[A]

  def add(node: SelfUniqueAddress, element: A): ORSet[A]
  
  @deprecated("Use `add` that takes a `SelfUniqueAddress` parameter instead.", since = "2.5.19")
  def add(node: Cluster, element: A): ORSet[A] = add(node.selfUniqueAddress, element)
```

**Comment by helena** [comment]
@patriknw Thanks, just seeing your suggestion, this looks great - adding.

**Comment by helena** [comment]
Additionally, [I created this related task](https://github.com/akka/akka/issues/26080) assigned to self.
