### ISSUE TITLE
both method get(ActorSystem) in Cluster and method get(ActorSystem) in Cluster match

### ISSUE THREAD

**Issue by oryjk** [akka/akka#25777]
https://github.com/scala/bug/issues/11198<p>
code repository<p>
https://github.com/oryjk/scala_build_with_jdk11.git<p>

**Comment by johanandren** [comment]
This is a known problem (although I don't think we had an issue tracking it), it is caused by how Scala generates static forwarders, it will be solved by the upgrade of Scala we did recently, so in the next release.

**Comment by johanandren** [comment]
Oh, I see now that your reproducer was already using Scala 2.12.7, let's keep this open to track it then.

**Comment by oryjk** [comment]
Ok, thank you, look forward to the new version.

**Comment by johanandren** [comment]
Ah, I didn't think clear about this: it doesn't matter if _you_ use 2.12.7, the issue is caused by Akka 2.5.17 and earlier being compiled with Scala 2.12.6 and earlier, so the Akka bytecode has those forwarders which conflicts.

**Comment by hepin1989** [comment]
Refs:https://github.com/scala/scala/pull/6531

**Comment by oryjk** [comment]
@hepin1989 thanks hepin1989

**Comment by Yannic92** [comment]
So will 2.5.18 be built on scala 2.12.7?
I tried to use jdk 11 with the akka snapshot version: 2.5-20181024-232234, but still experiencing this bug.

**Comment by raboof** [comment]
@Yannic92 it will. it is surprising that the problem persists for you on 2.5-20181024-232234. Are you sure you're using the `akka-xxx_2.12` artifacts rather than the `akka-xxx_2.11` artifacts?

**Comment by Yannic92** [comment]
@raboof Yes, I am. Should I open a new Issue where I add more details about the problem?
