### ISSUE TITLE
create a controlable flow, the pull method does not work.

### ISSUE THREAD

**Issue by Zhangjk2012** [akka/akka#25788]
here is my main code:
`
  lazy val logic = new GraphStageLogic(shape) with StageLogging {

    @volatile var state = false

    def changeState(s: Boolean): Unit = {
      if (s) {   
        pull(in)
      }
      state = s
    }

    setHandler(in, new InHandler {
      override def onPush(): Unit = {
        val i = grab(in)
        push(out, i)
      }
    })

    setHandler(out, new OutHandler {
      override def onPull(): Unit = {
        if (state) {
          pull(in)
        }
      }
    })

  }
}`
i use the `logic.changeState(true)`  to change the work state, and the flow start pull a element.  but it does not work and no error throw.

Did I use it wrong?  anybody can help me?

**Comment by johanandren** [comment]
Hi @Zhangjk2012, we try to use the issue tracker only for issues and feature-tracking, please use the [brand new forums](https://discuss.akka.io) or the [gitter channel](https://gitter.im/akka/akka) for questions like this, thanks!

**Comment by Zhangjk2012** [comment]
ok
