### ISSUE TITLE
Support DNS search domains in the async DNS provider

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#25825]
Most DNS resolver implementations support a configurable search list of suffixes that will be appended to relative hostnames to qualify them.

This can be used with [Kubernetes DNS service discovery](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#what-things-get-dns-names) to allow services to be queried using only the service name, without making the client qualify it with the namespace and cluster domain suffix. This is good for portability.

Here's how it's handled in various other clients:

- **Netty**: https://github.com/netty/netty/blob/1cc692dd7de54bfffa05813a90b14670b4eb50d1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java#L125-L157 https://github.com/netty/netty/blob/5650db582607a8eb95022cd73cdc490cc94c0e1c/resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java#L202
- **Java 8**: http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/net/dns/ResolverConfiguration.java#l70 http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/solaris/classes/sun/net/dns/ResolverConfigurationImpl.java http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/windows/classes/sun/net/dns/ResolverConfigurationImpl.java
- **JNDI Resolver**: [not supported](https://bugs.openjdk.java.net/browse/JDK-8170306)
- **dnsjava**: https://github.com/dnsjava/dnsjava/blob/90da2c27803015fe1e7dcd3ba84b0ce4d03fa4cf/org/xbill/DNS/ResolverConfig.java

**Comment by chbatey** [comment]
The search domains on Linux end up in /etc/resolve.conf

For example in Kubernetes this is populated in a container with something like:

```
search akka-bootstrap.svc.cluster.local svc.cluster.local cluster.local
```

Where `akka-bootstrap` is the namespace the pod is running in.

**Comment by jroper** [comment]
This feature is pretty important to run on Kubernetes. Without it, you need to have a different discovery configuration for every different namespace that you might deploy a service to, for example, this makes the configuration a lot more complex when having different namespaces for test, staging and production environments.
