### ISSUE TITLE
`MergePrioritized` never fully uses allocated buffers?

### ISSUE THREAD

**Issue by andersstorhaug** [akka/akka#25823]
Out of curiosity I was trying to understand how `MergePrioritized` was implemented and I noticed that its buffers appear to contain at most one element -- the inlet for the respective priority/source.

However it looks like the buffers are sized [based on priority](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala#L319):

```scala
private val allBuffers = Vector.tabulate(priorities.size)(i ⇒ FixedSizeBuffer[Inlet[T]](priorities(i)))
```

Is there an optimization to be made around this?

**Comment by johanandren** [comment]
That looks fishy, why would an inlet with higher priority have a larger buffer than one with a lower prio, if anything one with a lower prio would more likely buffer multiple elements. @arpanchaudhury you remember why you designed it like that, am I missing something?

**Comment by arpanchaudhury** [comment]
@johanandren  don't remember this correctly. I will check.

**Comment by hepin1989** [comment]
@andersstorhaug @arpanchaudhury I have updated a pr to address this, can you please check, thanks.
