### ISSUE TITLE
Custom build JVM detection logic duplicated

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25830]
Martynas told me that the logic we have for finding the JVM installation (which also does not work with jabba on my MacOS machine) exists in sbt nowadays so we should get rid of our own logic to find installed JVMs (in `project/CrossJava.scala`) and use that instead.

**Comment by raboof** [comment]
We still have some (https://github.com/akka/akka/blob/master/project/CrossJava.scala#L160) that have not made it into sbt 1.2.6 yet (https://github.com/sbt/sbt/blob/v1.2.6/main/src/main/scala/sbt/internal/CrossJava.scala#L370) though they are in the `develop` branch (https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/CrossJava.scala#L400, https://github.com/sbt/sbt/pull/4313).

So I guess we should wait until sbt 1.2.7 comes out?

**Comment by 2m** [comment]
The `develop` branch is for the upcoming `1.3.x` series.

**Comment by raboof** [comment]
Ah, so this is pending a release of sbt 1.3.0 (which is due in january, https://discuss.lightbend.com/t/memo-sbt-1-3-release-schedule/2453) or we should backport it to 1.2.x.

**Comment by patriknw** [comment]
sbt 1.3.2 is used in master now
