### ISSUE TITLE
JVM detection logic and Jabba on MacOS

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25835]
When I try to build akka-streams on adopt JDK 11 installed with `jabba` (also have adopt JDK 8) the build doesn't wind the 8 version:

```
[error] java.util.NoSuchElementException: key not found: 8
[error] 	at scala.collection.immutable.Map$Map4.apply(Map.scala:204)
[error] 	at akka.AkkaBuild$.$anonfun$defaultSettings$6(AkkaBuild.scala:109)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
```

Weird thing is, that it is listed among the detected java versions:
```
akka > show discoveredJavaHomes
[info] akka-distributed-data / discoveredJavaHomes
[info] 	ListMap(adopt@1.11 -> /Users/johan/.jabba/jdk/adopt@1.11.0-0/Contents/Home, adopt@1.8 -> /Users/johan/.jabba/jdk/adopt@1.8.181-13/Contents/Home)

akka > show fullJavaHomes
[info] akka-distributed-data / fullJavaHomes
[info] 	Map(adopt@1.11 -> /Users/johan/.jabba/jdk/adopt@1.11.0-0/Contents/Home, adopt@11 -> /Users/johan/.jabba/jdk/adopt@1.11.0-0/Contents/Home, adopt@1.8 -> /Users/johan/.jabba/jdk/adopt@1.8.181-13/Contents/Home, adopt@8 -> /Users/johan/.jabba/jdk/adopt@1.8.181-13/Contents/Home)
```

**Comment by raboof** [comment]
The key in the map is `adopt@8` where it AFAICS should be simply '8'. I suspect we're failing to strip the `vendor@` prefix from the Jabba version. I think there's one vendor for which Jabba does not have a vendor prefix (probably oracle or openjdk?), perhaps we didn't test with any other vendors through Jabba?

**Comment by johanandren** [comment]
We spent some time trying to fix it in Montreal, but didn't manage, I'll give it another stab.

**Comment by raboof** [comment]
I wonder if we should remove the `withVendor` from https://github.com/akka/akka/blob/master/project/CrossJava.scala#L139.

I guess it's ill-defined whether the keys in the `javaHomes: Vector[(String, File)]` should contain the vendor or not. AFAICS currently https://github.com/akka/akka/blob/master/project/CrossJava.scala#L139 does put the vendor in there, but https://github.com/akka/akka/blob/master/project/AkkaBuild.scala#L102 expects no vendor in there. sbt also puts the vendor in there though, but unfortunately doesn't include it as a testcase in https://github.com/sbt/sbt/blob/develop/main/src/test/scala/sbt/internal/CrossJavaTest.scala

**Comment by johanandren** [comment]
Yeah, that's what I'm trying now.
