### ISSUE TITLE
Cluster event listener that logs all events

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25832]
Would be useful when troubleshooting to be able to enable more verbose logging of all cluster events.

Perhaps even something we should make possible to turn on/off in runtime, and provide action of it in Akka Management.

**Comment by patriknw** [comment]
* Logging can be added to `ClusterReadView`
* It should be at INFO level, but enabled via config property, we already have `akka.cluster.log-info` so perhaps this one should be `akka.cluster.log-verbose-info`? disabled by default
* The log messages should follow the same format as other cluster logging, i.e. prefixed with "Cluster Node"

**Comment by helena** [comment]
@patriknw Some thoughts for feedback:

1. +1 disabled by default, opt-in
2. I imagine, given the potential load, it would need its own dispatcher
3. akka.cluster.log-info-verbose ('info' seems implicit/redundant however given this is an extension of the existing behavior, keeping the naming convention makes sense)

**Comment by patriknw** [comment]
> I imagine, given the potential load, it would need its own dispatcher

I don't think it will be much load, actually. It's only when the membership changes and when unreachability.

Note my suggestion to add it to the existing actor that is already listening to most of these events: https://github.com/akka/akka/blob/master/akka-cluster/src/main/scala/akka/cluster/ClusterReadView.scala#L55
In that way we don't generate more actor messages, but only some additional logging.

I think we should skip logging of `SeenChanged`, because that is not very interesting and happens frequently.

**Comment by helena** [comment]
Re: adding to ClusterReadView, +1 on not generating more actor messages. Originally I was thinking would it be cleaner to not add logging to the read view, which is log free. Will add there.

**Comment by patriknw** [comment]
When starting working on an issue you can also select the label "in progress".
