### ISSUE TITLE
Broken link to the Lagom framework website

### ISSUE THREAD

**Issue by balteo** [akka/akka#25843]
There's a broken link to the Lagom framework here in the docs: https://doc.akka.io/docs/akka/current/persistence.html?language=scala#scaling-out

The correct URL is: https://www.lagomframework.com/

**Comment by raboof** [comment]
Thanks for noticing! There is a link at the bottom of the page to the markdown sources, would you be interested in creating a PR or would you prefer me to do it?

**Comment by balteo** [comment]
Hi Arnout,
I am going to do it.
Cheers

Le mer. 31 oct. 2018 à 10:51, Arnout Engelen <notifications@github.com> a
écrit :

**Comment by balteo** [comment]
Here is the link to the PR: https://github.com/akka/akka/pull/25844

**Comment by dwijnand** [comment]
Fixed in #25844

**Comment by Captain1653** [comment]
The issue is really old. Looks like it was fixed - PR was merged. Is it still needed?
