### ISSUE TITLE
AsyncDnsResolverIntegrationSpec: "" did not include substring "all zones loaded". (DockerBindDnsService.scala:59)

### ISSUE THREAD

**Issue by raboof** [akka/akka#25855]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-nightly-2.11/detail/akka-nightly-2.11/739/pipeline

Apparently we only waited 5 seconds for the DNS server to start up, which was too little. Though it seems like in that time it did not start producing any logging at all? Suspicious.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-nightly-2.11/detail/akka-nightly-2.11/749/tests

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-nightly-2.11/runs/751/log/?start=0

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3032/testReport/junit/akka.io.dns/AsyncDnsResolverIntegrationSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by chbatey** [comment]
Will take a look at this
