### ISSUE TITLE
Source. unfoldResourceAsync should call close on read failure

### ISSUE THREAD

**Issue by huntc** [akka/akka#25862]
I believe `Source. unfoldResourceAsync` does not call its `close` function when the `read` function returns a failed future. I read the use of `Source. unfoldResourceAsync` as a streams version of a `try`/`finally` block.

What is the view here on whether the `close` function should always be called, regardless of failure given that `create` was performed with success?

**Comment by huntc** [comment]
Sorry for the noise. On closer inspection, I don't think there is an issue.

**Comment by johanandren** [comment]
Covered by tests now (and did not happen to start with) but looking through it revealed another issue that is now fixed :)
