### ISSUE TITLE
.groupedWithin can omit the last element from the source

### ISSUE THREAD

**Issue by alf239** [akka/akka#25875]
Hi, I think I've bumped into a bug very similar to #20232: sometimes, the last element of the original stream gets skipped. I'll try to get an isolated reproduction, but here's a bit of guesswork so far:

Looking at the fix and the code, it would seem as if there was a race condition between `onTimer` and `onStreamFinish` — note that according to the [GraphStageLogic documentation](https://doc.akka.io/japi/akka/current/akka/stream/stage/GraphStageLogic.html), `onTimer` is not thread safe with regard to the internal state  (emphasis is mine):

>  * Possible mutable state, accessible from the `InHandler` and `OutHandler` callbacks, **but not from anywhere else (as such access _would not be thread-safe_)**

**Comment by raboof** [comment]
Thanks for your report! A reproducer would indeed be helpful, but indeed it is hard to achieve for these kinds of problems.

**Comment by johanandren** [comment]
The `onTimer` is called through an asyncCallback so it is safe to mutate state from in there. I'll look into the idea that it is a race between onStreamFinish and the timer.

**Comment by johanandren** [comment]
I spent quite a while today trying to trace possible states but I can't find any way the buffer or an element in `pending` is lost when upstream completes, are you sure it is not some other operator upstream dropping the element @alf239 ?

**Comment by patriknw** [comment]
@alf239 would you be able to provide more information here, otherwise closing as obsolte
