### ISSUE TITLE
PersistentBehavior can't be used together with widen

### ISSUE THREAD

**Issue by dwijnand** [akka/akka#25887]
The implementation of [`PersistentBehavior`](
https://github.com/akka/akka/blob/v2.5.18/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/PersistentBehaviorImpl.scala#L98) depends on `widen`, so it's unavailable in user code.

... but then perhaps my use case is weird.

I split my message type hierarchy like usual:

```scala
sealed trait InventoryMessage
sealed trait InventoryCommand extends InventoryMessage
sealed trait InventoryEvent extends InventoryMessage
```

and I want to define my behavior as such:

```scala
def mkInventory: Behavior[InventoryCommand] =
  Behaviors.setup[InventoryMessage] { context =>
    ...
  }.narrow
```

The reason is I want to have my context defined as a `ActorContext[InventoryMessage]` so I can refine the event stream to `InventoryEvent`.

Similar to #25318, which is about `TimerScheduler`.

**Comment by patriknw** [comment]
Thanks for reporting, perhaps we can use a raw BehaviorInterceptor in the persistent impl.

**Comment by sarahgerweck** [comment]
The inability to compose `widen` seems like a major issue. As I'm building out prototypes in Akka Typed, I'm running into a lot of use cases that are triggering issues like this one and #25318. There doesn't really seem to be a reasonable workaround for mixing in behavior—the only real alternative I see is to spawn child actors with the original behavior, which is a lot of overhead.

#25318 is marked as NiceToHave, but I'm not sure composition of `widen` is properly in that category. I think this will be a significant problem for lots of use cases where you have a nontrivial actor system.
