### ISSUE TITLE
Memory leak with RepointableActorRef

### ISSUE THREAD

**Issue by JohnMcGreevy** [akka/akka#25888]
We have a single object consuming >7GB memory, looks like a single actor is consuming all the available memory. Analysing usage it appears that memory gets added to the heap until it hits a critical mass where the GC cpu usage spikes and this leads to a JVM crash
Akka v. 2.5.4
Akka HTTP v. 10.0.10

YourKit profiler shows this

- The BlackTree/RedTree seem go on
- The actor appears to be a Flow / ignoreSink (highlighted)
- Class found is akka.stream.impl.StreamSupervisor (see StreamSupervisor-9)

![image](https://user-images.githubusercontent.com/1464633/48195492-b2fe6600-e347-11e8-9284-b68b24ae2d36.png)
![image](https://user-images.githubusercontent.com/1464633/48195498-b85bb080-e347-11e8-9a4b-bcb333394187.png)

Eclipse Memory Analyzer
> One instance of "akka.actor.RepointableActorRef" loaded by "sun.misc.Launcher$AppClassLoader @ 0x5a1826500" occupies 7,457,128,496 (98.92%) bytes. The memory is accumulated in one instance of "scala.collection.immutable.RedBlackTree$BlackTree" loaded by "sun.misc.Launcher$AppClassLoader @ 0x5a1826500".
> 
> Keywords
> akka.actor.RepointableActorRef
> scala.collection.immutable.RedBlackTree$BlackTree
> sun.misc.Launcher$AppClassLoader @ 0x5a1826500

![image](https://user-images.githubusercontent.com/1464633/48195044-8d249180-e346-11e8-97ed-c3ba18700a81.png)

My guess would be that something in the stream isn't closing correctly (possibly the materilizer) but any guidance would be appreciated

**Comment by JohnMcGreevy** [comment]
Memory increase was due to a List as the value inside a Map increasing exponentially
Not sure how it manifests as this heap dump

**Comment by xmeng1** [comment]
I encountered the same issue and I am working on resolving it. I think the reason may be the Flow is not closed. (I am using the Stream Flow to handle WebSocket, and only stop the actor without close the Flow.)

**Comment by jadhavj** [comment]
Is there an update on this? I've upgraded to Akka-Http 10.1.8 and Akka 2.5.22 but still facing the same issue.

**Comment by ivantopo** [comment]
Hey @xmeng1 / @jadhavj, just in case you were using Kamon in your apps when you got this issue: we had a bug in the instrumentation that would cause the exact same behavior described here, and a fix was just released with Kamon `2.1.11`. Hope it helps :wave:

**Comment by paradoxon82** [comment]
I have the same issue, not using Kamon. Why is this closed? Is it resolved?

**Comment by johanandren** [comment]
Original issue was turned out to be a leak in user code as I understand it.

If you can provide a minimal reproducer for a leak in Akka, in a project without Kamon, please open a new issue and share the reproducer @paradoxon82
