### ISSUE TITLE
InvalidActorNameException despite child actor being terminated

### ISSUE THREAD

**Issue by huntc** [akka/akka#25899]
I'm observing an `InvalidActorNameException` situation with Akka Typed where:

1. A watch message is being received by a parent given child actor termination.
2. A new child actor is created with the same name.

My understanding is that upon the parent actor receiving a termination message from a child actor, I should be able to generate a new child actor with the same name as the terminated child actor.

Relevant code (L346 fails): https://github.com/akka/alpakka/blob/master/mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala#L325-L360

Related (but not child actors): https://github.com/akka/akka/issues/21195

**Comment by patriknw** [comment]
That is a bug, if it's true. Thanks for reporting.

**Comment by huntc** [comment]
Good to know. I shall work on a test case for you. Thanks.

**Comment by huntc** [comment]
This could be a false alarm. On further investigation, it could be that the following sequence is occurring in my code:

1. prl received, producer actor created
2. producer actor terminates and sends a termination message
3. prl received before termination message is received, the parent actor creates another producer
4. the termination message is received and then attempts to create another producer with the same name

I'll close this out. Sorry for the alarm.
