### ISSUE TITLE
rename `upcast` to `unsafeUpcast`

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#25896]
`ActorRef[Apple]` should keep only do accept Apples after it's widened/upcasted to `ActorRef[Fruit]`.which means making upcast a seems safe method.
The other type of message which is Apple should be dropped to dead letters.

If I have an `ActorRef[Apple]` and then upcast it to `ActorRef[Fruit]`, when I send an Orange to it, the Orange should be sent to dead letters.

**Comment by hepin1989** [comment]
And the `upcast` name is not that good as `unsafeWiden`. cc @rkuhn

**Comment by patriknw** [comment]
`upcast` is a pretty well know terminology so I think we should keep that. We could change it to `unsafeUpcast`.

Trying to keep around the original type would be difficult, e.g. serialization, and also defeat the purpose of being a power tool that can be used when you know that it's ok to send other types of messages than what the signature says, e.g. when retrieving `ctx.getChildren` or for some Akka internal things.

**Comment by rkuhn** [comment]
Not sure I understand the full background: we have a statically safe method `.widen` that entails proof of its safety (by having to write a function that does the translation), and we have a cast—this word always implies lack of safety. We need both methods, so what is the proposal?

**Comment by dwijnand** [comment]
`widen`'s on `Behavior`, not typed `ActorRef`.

👍 for `unsafeUpcase`.

**Comment by hepin1989** [comment]
if we change the signature of `upcast` to 
```scala
upcast[U >: T @uncheckedVariance](implicit ev: ClassTag[T @uncheckedVariance])
```
We could do some filtering. but as what @patriknw just said, that maybe too verbose, So I vote for `unsafeUpcase`.

**Comment by rkuhn** [comment]
The proposed signature with ClassTag does _not_ make the method safe (due to erasure) so I’d definitely vote for an unsafe cast. I’m wary of calling it `unsafeUpcast`, though, since the JVM and its languages include a ton of features that are unsafe without bearing that in their name—at the very least we’d need UnsafeByteBuffer ;-) . Why is it unreasonable to remain with the established terminology, namely that “cast” implies that you know what you are doing?

**Comment by dwijnand** [comment]
In Java "upcasting" means casting to a supertype, which is safe.  Here's we're changing the `T` the contravariant type parameter of `ActorRef` to a supertype, which isn't safe.  The fact `ActorRef` is contravariant isn't obvious (IMO) so I think adding "unsafe" is a good idea.  You're right there are footguns everywhere in the JDK, but I wouldn't add to them 😄.

**Comment by hepin1989** [comment]
Why can't？after capture the current T's runtime class ,it does work.

**Comment by hepin1989** [comment]
> @hepin1989 For generic types like `List<T>` this will not work, T is not known at runtime.

Oh, Yes, I forgot about that,`Classtag` will not be sufficient for that, Thanks.

**Comment by johanandren** [comment]
Looking at use sites in typed there's only 7 of them, should we maybe remove that method instead and just do the manual ugly cast in those places? Or have some internal utility for it?

**Comment by patriknw** [comment]
but in rare cases it might be needed by users, e.g. when using `ctx.getChildren` or `ctx.child` and wanting to send messages to them (because you know type they are)

I think we should just leave it as is.

**Comment by johanandren** [comment]
Fair enough, I think the scaladoc is quite clear, but maybe we should also add some description/warning about what happens if you send the new ref something it cannot actually handle?

**Comment by dwijnand** [comment]
The scaladoc doesn't help you when reviewing usage.

I think it's fair to have the utility around, but with a less innocuous name. `actorRef.upcast[..]` just looks too innocent and safe for what it actually is, especially given that the way "upcasting" is usually meant it _is_ safe, while here it's not.  @patriknw why the change of heart?

**Comment by patriknw** [comment]
> especially given that the way "upcasting" is usually meant it is safe

That is a good point. The first google hit on upcast java confirms that.
https://stackoverflow.com/questions/23414090/what-is-the-difference-between-up-casting-and-down-casting-with-respect-to-class

Let's rename it to `unsafeUpcast` then.
