### ISSUE TITLE
Typed EventStream

### ISSUE THREAD

**Issue by dwijnand** [akka/akka#25893]
There are two interesting types on EventStream that would be nice to be able to define:

* the type of events to publish, and
* the type of events to subscribe to

But I'm not sure if it should be two type parameters or two wrappers.

As always the benefit is to help the typechecker catch type errors.

Additionally it might be also be helpful to have a wrapper that always subscribes `context.self` (no specifying the subscriber in the method call), again to avoid subscribing to events that self can't handle. Similar to how `TimerScheduler` only sends to self.

**Comment by dwijnand** [comment]
Also the API could intially return an EventStream for `Any` types, that you could `narrow`.

**Comment by dwijnand** [comment]
More thoughts about a typed event stream in #21525.

**Comment by hepin1989** [comment]
I was wondering this yesterday:)

**Comment by patriknw** [comment]
@dwijnand Is this ticket needed when we have #21525?

> the type of events to publish

`eventStreamRef.narrow` ?

> the type of events to subscribe to

That would be part of the subscription message that you would sent to the `eventStreamRef`, something like

```
case class Subscribe[M](channel: Class[M], subscriber: ActorRef[M])
```

Ordinary `ActorContext.messagAdapter` can be used to convert `M` to the message protocol of `self`.

**Comment by dwijnand** [comment]
@patriknw I see this ticket as being a more general request, that would be satisfied if #21525 were resolved.  But if #21525 is rejected or too difficult for any reason, perhaps this ticket could still be resolved (like with the wrapper ideas I've been experimenting with).

**Comment by patriknw** [comment]
Ok, added a note in the other ticket, and closing this for now. We can reopen if #21525 is rejected.

**Comment by dwijnand** [comment]
Hmm, ok, sounds reasonable.
