### ISSUE TITLE
Consider relocating the receptionist docs

### ISSUE THREAD

**Issue by dwijnand** [akka/akka#25895]
I discovered the receptionist by accident, and I wonder if it should be documented under "Actor discovery", seeing as you can use it for bootstrapping too.

I never looked into "Actor discovery" because I didn't have the need to "discover" (or lookup) any actors, but its other features (subscribe, register, listing) are useful to know.

Perhaps mention together with the spawn protocol? Or cross-link?

**Comment by patriknw** [comment]
thanks for good suggestion

**Comment by dwijnand** [comment]
By "Actor discovery" I mean the page in typed: https://doc.akka.io/docs/akka/current/typed/actor-discovery.html#dependency

And the spawn protocol, which I had found is in the Actor lifecycle page of typed:
https://doc.akka.io/docs/akka/current/typed/actor-lifecycle.html#spawnprotocol

Thank you for taking care of this, @helena!

**Comment by helena** [comment]
@dwijnand It looks like the [Receptionist](https://doc.akka.io/docs/akka/current/typed/actor-discovery.html#receptionist) doc is already under the [Actor Discovery doc](https://doc.akka.io/docs/akka/current/typed/actor-discovery.html#receptionist). Did you mean something else?

**Comment by helena** [comment]
I'm missing why a cross-link between Spawn Protocol and Receptionist is needed, can you elaborate? 
Spawn Protocol, dealing with typed actor **creation** and what behavior, does appear to be aptly located. Discovery could be argued as being part of Lifecycle but isn't always. I suspect you were doing something with `spawn` and the `receptionist` specifically that perhaps could be used as a sample and linked to the doc for this.

**Comment by dwijnand** [comment]
Oh wow, I really failed to communicate properly here, @helena.  (Probably because I communicated it first internally and then tried to summarise the idea here (and failed).)

I meant that while the Receptionist doc _is_ under Actor Discovery and I wonder whether it should be, seeing as it can also be used for bootstrapping the system.  The reference to the spawn protocol was indeed for typed actor creation, and so also an interesting available tool for bootstrapping.

The point is I was migrating some untyped code to typed, didn't need actor discovery but I _did_ need idea/options on how to rewrite the bootstrapping code.  I'd found the spawn protocol but I would've never have found the receptionist if I hadn't eventually accidentally found it.  So I wondered whether we could surface it some other way.

**Comment by helena** [comment]
Thanks @dwijnand, I re-read the initial proposal so many times thinking - I must be misunderstanding it ;)
