### ISSUE TITLE
Access logged messages in BehaviorTestKit

### ISSUE THREAD

**Issue by jlprat** [akka/akka#25905]
It would be good to be able to write some tests like the following one:
```
val testKit = BehaviorTestKit(Guard.initialBehavior)
testKit.run(Start(0))
testKit.logEntries should contain CapturedLogEvent(InfoLevel, "Started")
```

Currently everything is captured, but there is no way to get to the stored log entries from the `BehaviorTestKit`

**Comment by patriknw** [comment]
sounds good, thanks

**Comment by jlprat** [comment]
I will provide a PR for it 🙂
