### ISSUE TITLE
add receiveOne to TestProbe in Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25914]
I often find that I do 
```
val registeredProbe = createTestProbe[DeviceRegistered]()
// ...
val registered1 = registeredProbe.expectMessageType[DeviceRegistered]
```

That would be better as
```
val registeredProbe = createTestProbe[DeviceRegistered]()
// ...
val registered1 = registeredProbe.receiveOne()
```

**Comment by dwijnand** [comment]
Sounds good.

I think it should have type signature:

```scala
def receiveOne(implicit t: scala.reflect.ClassTag[M]): M
```

Are you still working on this, @patriknw, or can I take it?

**Comment by helena** [comment]
Resolved by [25994](https://github.com/akka/akka/pull/25994)

**Comment by patriknw** [comment]
@helena and also remember to assign the milestone when closing the ticket. We use the milestone for tracking what issues were solved in which Akka release.

(I assigned 2.5.19 for this one)
