### ISSUE TITLE
Group router not work as expect if using remote actor path

### ISSUE THREAD

**Issue by EdisonXu** [akka/akka#25935]
Hello,

As mentioned in the [document](https://doc.akka.io/docs/akka/current/routing.html), group router could support full remote path of remote actors.

>The paths may contain protocol and address information for actors running on remote hosts. Remoting requires the akka-remote module to be included in the classpath.
```
akka.actor.deployment {
  /parent/remoteGroup {
    router = round-robin-group
    routees.paths = [
      "akka.tcp://app@10.0.0.1:2552/user/workers/w1",
      "akka.tcp://app@10.0.0.2:2552/user/workers/w1",
      "akka.tcp://app@10.0.0.3:2552/user/workers/w1"]
  }
}
```
But when I changed the path to the remote path, it throws
```
Exception in thread "main" java.lang.IllegalArgumentException: routeesPaths [akka.tcp://ClusterSystem@127.0.0.1:2551/user/statsWorker] is not a valid actor path without address information
```
error.

PS: `akka-remote` module has already been included.

You can using the sample project https://github.com/akka/akka-samples/tree/2.5/akka-sample-cluster-java and change the `src\main\resources\stats1.conf` file to reproduce this issue.

**Comment by patriknw** [comment]
That is because that example is using Akka Cluster, and then the paths should be without address information, since that is retrieved dynamically from the cluster membership.
https://doc.akka.io/docs/akka/current/cluster-routing.html

To use paths with addresses you have to use the remoting module, without cluster, but that is not something I would recommend.

**Comment by EdisonXu** [comment]
@packtpartner thank you for quick response. 

> As remoting is the underlying module that allows for Cluster, it is still useful to understand details about it though

Since cluster is based on remoting module, I suggest add some clarification on this part, or it's easy to think full paths are also working in cluster.

Meanwhile, could you please check another issue [25946](https://github.com/akka/akka/issues/25946)? Appreciated a lot.

**Comment by patriknw** [comment]
Would you be able to contribute such a note/warning to the documentation?
