### ISSUE TITLE
Failed: ClusterShardingPersistenceSpec: handle PoisonPill after persist effect

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25936]
```
Error
java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMessage while waiting for recoveryCompleted:1
Stacktrace
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMessage while waiting for recoveryCompleted:1
at scala.Predef$.assert(Predef.scala:170)
at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:137)
at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(
```

https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-nightly-2.11/detail/akka-nightly-2.11/758/tests

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.11/759/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6588/log/?start=0

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6589/log/?start=0

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.11/770/testReport/junit/akka.cluster.sharding.typed.scaladsl/ClusterShardingPersistenceSpec/Typed_cluster_sharding_with_persistent_actor_must_handle_PoisonPill_after_persist_effect/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1284/testReport/junit/akka.cluster.sharding.typed.scaladsl/ClusterShardingPersistenceSpec/Typed_cluster_sharding_with_persistent_actor_must_handle_PoisonPill_after_persist_effect/
