### ISSUE TITLE
QueueSource should include pendingOffer in exception message

### ISSUE THREAD

**Issue by baltiyskiy** [akka/akka#25930]
`QueueSource.bufferElem()` throws `IllegalStateException` if the buffer is full, there is some `pendingOffer` and the overflow strategy is `Backpressure`. 

The problem is that it doesn't include the element in `pendingOffer`. It should do so, because it can help identify the offender. This is a simple problem to fix if there's only one place where you place offers into the queue, but if there are many, you might want to know from where comes the pending offer.

**Comment by patriknw** [comment]
Including the element class name in the IllegalStateException message sounds good. Would you be able to create a pull request?

**Comment by baltiyskiy** [comment]
Can’t we include the element itself though? After all, they all have mostly
the same class.

**Comment by johanandren** [comment]
The reason we tend to avoid including `toString` on elements/messages is that those could be arbitrary long (depending on the element) and if they are really long that will be problematic for performance and logs.

**Comment by patriknw** [comment]
Isn't usage of `Source.queue` with `Backpressure` from more than one place invalid usage, so I'm not sure I understand why we should provide anything more advanced than the existing error message: "You have to wait for previous offer to be resolved to send another request".

**Comment by baltiyskiy** [comment]
There’s a trade off here: not logging elements hurts observability and
debuggabiluty of the system, in favor of use cases with poorly defined
toString(). In my opinion, it’s a part of a good engineering culture to
have sane toString() that limits its output. If one absolutely must have
the whole thing printed out somewhere, there can be something like
toFullString() - but that should be a conscious decision, not the default.

**Comment by baltiyskiy** [comment]
Without external coordination, it is indeed invalid. In my case, I didn’t
realize that I had to make this coordination work properly, and instead
spent some time thinking what was wrong with my handling of the Future
returned by offer(). The problem is that you can’t distinguish between the
two cases by observing the system.

(As an aside - now I realize that I’d be better off having separate sources
and then merging them together. )

**Comment by patriknw** [comment]
>  In my opinion, it’s a part of a good engineering culture to
have sane toString() that limits its output.

I agree, but since we can't trust that and will get the blame for bad performance and customers will call us when production systems go down I'd rather continue to avoid `toString` of unknown objects.

I don't think it's much more we can do here.

Merging separate sources is an excellent idea.
