### ISSUE TITLE
Add variant of RestartSource/Flow/Sink.withBackoff that takes a Future returning factory

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#25934]
Currently `RestartSink` (and accordingly `RestartFlow` and `RestartSource`) require the argument of `withBackoff` to be a factory for `Sink`s. 

Would it be possible to also add a variant that accepts a factory for `Future[Sink]`?

```
  def withBackoff[T](minBackoff: FiniteDuration, maxBackoff: FiniteDuration, randomFactor: Double)(
      sinkFactory: () ⇒ Future[Sink[T, _]]
  ): Sink[T, NotUsed] = ???```

**Comment by patriknw** [comment]
Could you also provide an example usage so that we understand the feature request better?

The `Source` case is already covered by `Source.fromFutureSource`.

**Comment by hseeberger** [comment]
Thanks for the pointer to `Source.fromFutureSource`, I did not know that.

The use case is getting a `SinkRef` via actor messaging, e.g. for a stream that is managed by a sharded actor which runs the stream and lets `SinkRef` be obtained via `GetSinkRef` commands. When using the ask pattern for the messaging we get a `Future[SinkRef]` and we want to use that in `RestartSink.withBackoff` to get an effectively endless (with short periods of unavailability due to rebalancing of shards) running `Sink`. Does that make sense? If not I could share some code.

**Comment by patriknw** [comment]
I think the use case sounds reasonable. Don't know how difficult it is to implement.

**Comment by iosven** [comment]
@hseeberger Has this Issue here been resolved for you via the introduced `Sink.futureSink`?

PS: I was led here via a revisit to your ScalaDays 2019 talk. I do not have an immediate need for this aspect of the solution, but I was wondering.

**Comment by hseeberger** [comment]
Hi @iosven, thanks for reaching out to me. I was not aware of `Sink.futureSink`, must have missed it. It should definitely do the job.
