### ISSUE TITLE
Default value for `send-to-dead-letters-when-no-subscribers` is wrong

### ISSUE THREAD

**Issue by rdubois** [akka/akka#25942]
The default value for the `akka.cluster.pub-sub.send-to-dead-letters-when-no-subscribers` is wrong in https://github.com/akka/akka/blob/master/akka-cluster-tools/src/main/resources/reference.conf#L33. This issue appeared when the new configuration key has been added in https://github.com/akka/akka/issues/23462.

According to the implementation in https://github.com/akka/akka/blob/master/akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala#L59, the parameter value must be a boolean, while it is set to `on` by default.

**Comment by rdubois** [comment]
It was actually not an issue.

**Comment by raboof** [comment]
Thanks for checking and reporting back in any case!
