### ISSUE TITLE
ActorRefSourceActor with custom log levels

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#25949]
We'd like to have more noticeable log level when dropping items/buffer in cases of an overflow:
https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-stream/src/main/scala/akka/stream/impl/ActorRefSourceActor.scala#L76

If you have some opinions/preferred way to do this I could prepare a pull request.

**Comment by raboof** [comment]
Would it be an option to use `Source.queue` instead? That way you have full control over how to handle the situation that the offer is dropped (https://doc.akka.io/docs/akka/current/stream/operators/Source/queue.html)

**Comment by nvollmar** [comment]
Might be possible, but `Source.actorRef` is very straight forward and simple solution for our use case. Switching to `Source.queue` would probably add a lot complexity since we need to register the actor source as listener.

**Comment by patriknw** [comment]
Perhaps we could introduce a log level in `OverflowStrategy` to be able to customize the logging for dropped elements.

**Comment by nvollmar** [comment]
Thanks for the feedback, I'll look into it

**Comment by nvollmar** [comment]
See pull request #25976
