### ISSUE TITLE
Deprecate Serialization.deserialize that takes `clazz: Option` parameter

### ISSUE THREAD

**Issue by dominics** [akka/akka#25945]
[`MiscMessageSerializer` implements `SerializerWithStringManifest`](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/serialization/MiscMessageSerializer.scala#L25) - however it doesn't(/can't) override the `final def fromBinary(bytes: Array[Byte], manifest: Option[Class[_]]): AnyRef` method contained in that trait.

The upshot is that serialization will proceed as normal, but if a user calls the [deserialize method in the Serialization extension](https://github.com/akka/akka/blob/caec209bf68c6f2c3005d96d590c4f549769a51e/akka-actor/src/main/scala/akka/serialization/Serialization.scala#L282) (`def deserialize[T](bytes: Array[Byte], clazz: Class[T]): Try[T]`), the manifest eventually passed to the `MiscMessageSerializer` will not be the expected string (i.e. it won't be the one in the [`fromBinaryMap`](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/serialization/MiscMessageSerializer.scala#L311) of manifest strings to deserializers, but instead will be the `Class[_].getName` of the type-hint)

[Here's an example](https://github.com/KarelCemus/play-redis/issues/191) of something that uses Akka serialization failing as soon as akka-remote adds a serialization binding for `Option` -> `MiscMessageSerializer` (manifest is expected to be `"C"`, but ends up being `"scala.Some"`). The eventual failure is:

> java.io.NotSerializableException: Unimplemented deserialization of message with manifest [scala.Some] in [akka.remote.serialization.MiscMessageSerializer]

**Comment by raboof** [comment]
Can you show the rest of that stack trace?

I *think* `def deserialize[T](bytes: Array[Byte], clazz: Class[T]): Try[T]` is the legacy API kept for binary compatibility, and we'd now typically use `def deserialize(bytes: Array[Byte], serializerId: Int, manifest: String): Try[AnyRef]` or `def deserializeByteBuffer(buf: ByteBuffer, serializerId: Int, manifest: String): AnyRef` instead. Not entirely sure though, perhaps we should clarify in the method comments.

**Comment by patriknw** [comment]
That is right, use:
```
def deserialize(bytes: Array[Byte], serializerId: Int, manifest: String): Try[AnyRef]
```

It will also take care of serializers that don't implement `SerializerWithStringManifest` and then use the `manifest: String` as a class name and pass that class as the manifest.

I'm renaming this issue to deprecate the other deserialize method.
