### ISSUE TITLE
Provide more examples of the state parameter in side effects in the Typed Persistence documentation

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#25953]
In the [Akka Typed Persistence documentation](https://doc.akka.io/docs/akka/current/typed/persistence.html#replies), most of the examples of side effects after persisting an event (`thenRun`, `thenReply`) ignore their parameter.

Examples:

```scala
Effect.persist(evt).thenRun { _ ⇒
  // After persist is done additional side effects can be performed
  cmd.replyTo ! AddPostDone(cmd.content.postId)
}
```

```scala
    Effect.persist(Withdrawn(cmd.amount))
      .thenReply(cmd)(_ ⇒ Confirmed)
```

Because of this, it's not obvious what the the argument is (the updated state). It's often useful to reply with the updated state, so this should be mentioned explicitly in the guide and demonstrated in the examples.

Currently, the only place the state parameter is used is in the section on [Accessing the ActorContext](https://doc.akka.io/docs/akka/current/typed/persistence.html#accessing-the-actorcontext), which is not that related.

It might also help to link from the method names to API documentation where each method is first introduced.

**Comment by TimMoore** [comment]
I eventually found this sentence in the ["Command handler"](https://doc.akka.io/docs/akka/current/typed/persistence.html#command-handler) section.

> In the example below a reply is sent to the `replyTo` ActorRef. Note that the new state after applying the event is passed as parameter to the `thenRun` function.

I still think it's worth reiterating this information in the ["Effects and Side Effects"](https://doc.akka.io/docs/akka/current/typed/persistence.html#effects-and-side-effects) and ["Replies"](https://doc.akka.io/docs/akka/current/typed/persistence.html#replies) sections for clarity.

**Comment by patriknw** [comment]
sounds good to clarify more
