### ISSUE TITLE
Should RestartFlow and friends log stream failure conditionally?

### ISSUE THREAD

**Issue by huntc** [akka/akka#25952]
I was just wondering if the `RestartFlow` and friends should log stream failure optionally given that failure is the reason for it in the first place. The logs can get quite noisy.

Perhaps we could have a `log` parameter on `RestartFlow`'s functions which is enabled by default. Thoughts?

[There was a PR](https://github.com/akka/akka/issues/25019) that reduced the logging level, but I'm looking to silence it entirely.

**Comment by patriknw** [comment]
I think I did something for MergeHub or BroadcastHub to silence it with the ordinary LogLevel attribute. Perhaps we can do the same here?

**Comment by huntc** [comment]
I did wonder about that later. I'll close and investigate further. Meanwhile if you do have an example at hand then that'd be wonderful. Thanks!

**Comment by SkyTrix** [comment]
Has this been looked into further? Or are there any other ways to prevent the logging of these errors? Specifically I'm using `RestartSource.onFailuresWithBackoff` to poll an HTTP endpoint to check whether some task is already complete. Depending on the size of the task I could expect 1-10 errors, which is also why I'm using the backoff strategy in my polling. Because these aren't really errors to me, I'd like to hide them. Am I using the wrong tool for the job?

**Comment by huntc** [comment]
> Has this been looked into further? Or are there any other ways to prevent the logging of these errors? Specifically I'm using `RestartSource.onFailuresWithBackoff` to poll an HTTP endpoint to check whether some task is already complete. Depending on the size of the task I could expect 1-10 errors, which is also why I'm using the backoff strategy in my polling. Because these aren't really errors to me, I'd like to hide them. Am I using the wrong tool for the job?

I don't think this has been looked at. If I follow the `RestartSource` with:

```
.withAttributes(Attributes
  .logLevels(onElement = Logging.DebugLevel, onFinish = Logging.DebugLevel, onFailure = Logging.DebugLevel))
```

...then there's no difference.

Any other ideas @patriknw ?

**Comment by huntc** [comment]
Actually, to keep `RestartSource` happy, catch the error and recover:

```scala
val _ = RestartSource
  .withBackoff(minBackoff, maxBackoff, backoffRandomFactor)(
    () =>
      SomeSource // Does some http connecting
        .recover {
          case _: StreamTcpException => Source.empty
      })
  .runWith(Sink.ignore)
```

Closing as recovering as per above solves the original issue I reported.
