### ISSUE TITLE
Failed: InactiveEntityPassivationSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#25964]
https://jenkins.akka.io:8498/job/akka-artery-tcp-cluster-tests/514/testReport/junit/akka.cluster.sharding/InactiveEntityPassivationSpec/Passivation_of_inactive_entities_must_passivate_entities_when_they_haven_t_seen_messages_for_the_configured_duration/

```
Error Message

java.lang.AssertionError: assertion failed: received unexpected message RealMessage(1 passivating,Actor[akka://InactiveEntityPassivationSpec/system/sharding/myType/1/1#1403380725]) after 966 millis

Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: received unexpected message RealMessage(1 passivating,Actor[akka://InactiveEntityPassivationSpec/system/sharding/myType/1/1#1403380725]) after 966 millis
	at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:696)
	at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:661)
	at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:660)
	at akka.testkit.TestKit.expectNoMessage(TestKit.scala:896)
	at akka.cluster.sharding.InactiveEntityPassivationSpec.$anonfun$new$2(InactiveEntityPassivationSpec.scala:89)
	at akka.cluster.sharding.InactiveEntityPassivationSpec$$Lambda$1368/2105805110.apply(Unknown Source)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/82/testReport/junit/akka.cluster.sharding/InactiveEntityPassivationSpec/Passivation_of_inactive_entities_must_passivate_entities_when_they_haven_t_seen_messages_for_the_configured_duration/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/149/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6831/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/160/testReport/junit/akka.cluster.sharding/InactiveEntityPassivationSpec/Passivation_of_inactive_entities_must_passivate_entities_when_they_haven_t_seen_messages_for_the_configured_duration/
