### ISSUE TITLE
In Typed Java ask/adapt/pipe run the function by the actor

### ISSUE THREAD

**Issue by dwijnand** [akka/akka#25972]
> That must be an oversight. Should be implemented in same way, as in scala impl

_Originally posted by @patriknw in https://github.com/akka/akka/pull/24335#issuecomment-441385922_

**Comment by hepin1989** [comment]
It is delegated to the Scala one.

**Comment by johanandren** [comment]
Ah, sorry I didn't find this when merging that PR (searched for pipeTo)

**Comment by patriknw** [comment]
This has not been solved, AdaptMessage isn't used in the Java API see https://github.com/akka/akka/blob/master/akka-actor-typed/src/main/scala/akka/actor/typed/internal/ActorContextImpl.scala#L98-L111

I think @dwijnand wanted to follow up on this.

**Comment by johanandren** [comment]
Ups, misunderstood what it was about, I see now.
