### ISSUE TITLE
feature request: akka.pattern.RetrySupport#retry lack backoff support.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#25996]
I was trying to implement something like this, but When I looked into it, I saw it currently lack backoff support.

```scala
  def retry[T](attempt: () ⇒ Future[T], attempts: Int, delay: FiniteDuration)(implicit ec: ExecutionContext, scheduler: Scheduler): Future[T] = ???

```

**Comment by hepin1989** [comment]
So does the `recoverWithRetries` on stream.

**Comment by hepin1989** [comment]
refs https://github.com/akka/akka/pull/25827/files

**Comment by jasonqu** [comment]
Seems be done https://gist.github.com/viktorklang/9414163

**Comment by johanandren** [comment]
Refs #25996

**Comment by johanandren** [comment]
Refs #25996
