### ISSUE TITLE
Convert Quickstart to Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25997]
* [ ] https://github.com/akka/akka-quickstart-scala.g8
* [ ] https://github.com/akka/akka-quickstart-java.g8

I think the existing Hello World in the docs is pretty similar: https://doc.akka.io/docs/akka/current/typed/actors.html#introduction

Use OO style for familiarity points.

**Comment by yuuri111** [comment]
@patriknw 
Hi.
Do you think we should rename at this time?
I'd like to confirm if we should fix these name to document.
ex) 
- Greeter → Greet
- Greeting → Greeted
- Printer → HelloWorld

**Comment by xmeng1** [comment]
The hello sample in this section: https://doc.akka.io/docs/akka/2.5/typed/guide/tutorial_1.html#the-akka-actor-hierarchy was not run properly. Because only create an actor, not send any message to it. 

I think it should be changed to 

```scala
object ActorHierarchyExperiments extends App {
  val system = ActorSystem(Main(), "testSystem")
  system ! "start"
}
```

**Comment by patriknw** [comment]
The latest (not released) documentation can be found here: https://doc.akka.io/docs/akka/snapshot/typed/guide/tutorial_1.html#the-akka-actor-hierarchy

Could you see if that works for you or if there is still some mistake?

**Comment by xmeng1** [comment]
The latest one works ~

**Comment by patriknw** [comment]
thanks for confirming

**Comment by patriknw** [comment]
When doing this ticket, note that we have a similar HelloWorld example in the reference docs that can be used as inspiration: https://doc.akka.io/docs/akka/current/typed/actors.html#introduction
