### ISSUE TITLE
merge PatternsCS into Patterns for Java API?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26000]
I think this is worth to do.with the leverage of `Duration` etc thing ,it's easy to distinct the API for Scala or Java.
 `PatternsCS` is not much findable.

or ,in 2.6 we could do `akka.patten.javadsl.Patterns` and `akka.patten.scaladsl.Patterns` like thing.
refs:https://github.com/akka/akka/issues/22316

**Comment by patriknw** [comment]
I agree, with the `java.time.Duration` distinction it's possible.

**Comment by hepin1989** [comment]
There is no way to handle these kind of:)
```scala
  def ask(selection: ActorSelection, message: Any, timeoutMillis: Long): CompletionStage[AnyRef]
```

**Comment by hepin1989** [comment]
if that could be done,then seems like all `PatternsCS` could go,and then just deprecated it and update the document.

**Comment by hepin1989** [comment]
As https://github.com/akka/akka/issues/26015 just did ,I think it would be a best move to merge both Scala api and Java api when we are not using `time:Long,timeUnit:TimeUnit` like thing in the API.
