### ISSUE TITLE
Problems with rebalance-threshold

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26012]
Given the recommendation of using 10x shards than number of nodes the default `rebalance-threshold=10` is too hight.

It can result in one node hosting  ~2 times the number of shards of other nodes. Example: 1000 shards on 100 nodes means 10 shards per node. One node may have 19 shards and others 10 without a rebalance occurring.

There is also a bug possibly causing continuous rebalance if `rebalance-threshold=1`.
Here is a reproducer test that can be added to `LeastShardAllocationStrategy`:
```
    "not rebalance one" in {
      val allocations = Map(regionA → Vector("shard1"), regionB → Vector("shard2"), regionC → Vector.empty)
      val strategy = new LeastShardAllocationStrategy(rebalanceThreshold = 1, maxSimultaneousRebalance = 2)
      strategy.rebalance(allocations, Set.empty).futureValue should ===(Set.empty[String])

      val allocations2 = Map(regionA → Vector.empty, regionB → Vector("shard2"), regionC → Vector("shard1"))
      strategy.rebalance(allocations2, Set.empty).futureValue should ===(Set.empty[String])
    }
```

**Comment by patriknw** [comment]
Thanks @WadeWaldron for bringing this to our attention.

**Comment by patriknw** [comment]
The workaround for the `rebalance-threshold=1` until this is fixed is to use at least 2

**Comment by eloots** [comment]
Note that with `rebalance-threshold=2`, something odd happens. With that setting applied, we have one node (one region) that has two shards in it. Adding a second node will trigger a rebalance ending in each node holding one shard. This is correct.
When rebalancing the shards, the rebalancing process should stop one of the shards on the first node and re-start it on the second node, thereby leaving the second shard on the first node untouched.
What is weird though is that instead, _both shards_ are stopped on the first node, followed by the re-start of one shard on the second node and another on the first node.

**Comment by WadeWaldron** [comment]
@eloots Do you know if behaves that way with other `rebalance-threshold` values? I.E. Is this a problem that only occurs with a `rebalance-threshold=2` or is this the behaviour no matter what value is used?

**Comment by eloots** [comment]
I just tried it with `rebalance-threshold=3`. On the first rebalance (after adding a second node), all 3 shards are stopped on the first node after which two are re-started on that node (and one shard is started on the second node).
When a third node is added, rebalancing takes place from the first node (2 shards) to the third node (0 shards). Again, on the first node, the two shards are stopped and one on these shards is re-started on that node.
So, there's seems to be a pattern here...

**Comment by WadeWaldron** [comment]
It seems like the way the rebalance algorithm works is probably to choose a node to rebalance and then stop all shards on that node, regardless of whether or not they will be migrated.

It does seem like it would be more efficient to first decide which ones to rebalance, and then only stop those.

**Comment by WadeWaldron** [comment]
@eloots I would suggest creating a separate issue around the efficiency of the sharding algorithm.

**Comment by patriknw** [comment]
I will look into this on Monday

**Comment by eloots** [comment]
@patriknw I tested https://github.com/akka/akka/commit/bbae1ecdb6b0510f8b05ac57ad175e877b58ad74 on [akka-sample-cqrs-scala](https://github.com/akka/akka-samples/tree/2.5/akka-sample-cqrs-scala) which depends on setting `least-shard-allocation-strategy.rebalance-threshold = 1` and it now shows the expected behaviour:
- No unnecessary stopping and restarting of shards when all shards are fully spread across nodes (1 shard per node) and additional nodes are added (which will not host any shard).
- In the case of a rebalance, no unnecessary stopping and restarting of shards that stay on the same node.

Thanks!

**Comment by t3hnar** [comment]
@patriknw we also had some fixes to this strategy, maybe you could find them useful.

https://github.com/evolution-gaming/sharding-strategy/blob/master/src/main/scala/com/evolutiongaming/cluster/sharding/LeastShardsStrategy.scala#L3

**Comment by patriknw** [comment]
thanks
