### ISSUE TITLE
Should the ActorRef[Nothing] and ActorRef[Void] be unified to one?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26025]
I think the current Scala and Java of Akka typed's `ActorContext` should change a little.
At first for the return type of Java and Scala's API is not unified, which respectively return `ActorSystem[Void]`,`ActorSystem[Nothing]]` 
`Iterable[ActorRef[Nothing]]`,`Option[ActorRef[Nothing]]`
 `java.util.List[ActorRef[Void]]` , `Optional[ActorRef[Void]]`

Just as what we did in Akka-Streams.

At first, They are not accepting a `Void` or a `Nothing` but something more like I don't know what they are currently accepting, some kind of `Un(/Not)defined`.
second, from the user perspective, I do expect both of Java and Scala API to be unified.

with the current API, the Java API's return type is `ActorSystem<Void>` emphasize that you can send it a `null` but the Scala API will forbid you to do that.

//scala 
```scala
context.system.tell(null)//error
context.system.tell(???)//ok
```
//java
```java
context.getSystem().tell(null)//ok
context.getSystem().tell(scala.Predef$.MODULE$.$qmark$qmark$qmark())//error
```
cc @rkuhn @chbatey 
cc @dwijnand

**Comment by hepin1989** [comment]
refs old friend :https://github.com/akka/akka/issues/19442

**Comment by hepin1989** [comment]
Refs:https://github.com/scala/scala-java8-compat/issues/58

**Comment by rkuhn** [comment]
`Nothing` is the more correct type—we cannot permit sending to the ref at all—but Java does not know this concept, so the Java type is less precise. `???` is not a value, so being “allowed” in the Scala case is a red herring. Passing `null` into this method is indeed an error that results in an exception, but unfortunately Java cannot prevent this at the moment. I think instead of unification we should retain the best possible solution in either case, as we have right now.

**Comment by hepin1989** [comment]
Then how about the `getChild` which return `Optional[ActorRef[Void]]`? So what do we expected to send to an `ActorRef[Void]`? It means *don't send any message* or *I don't know which message the child takes*?

I could live with the `ActorSystem<Void>` and `ActorSystem[Nothing]`, but not that considerable for `Option[ActorRef[Nothing]]` and  `Optional[ActorRef[Void]]`.

Back to the children part, They do accept some type of messages and back to their unified type, I have no idea why it became `Iterable[ActoRef[Nothing]]` and `java.util.List[ActorRef[Void]]`. You know what。 

As a metaphor, We have American who hear American English, Britisher who hear British English and
Chinese who hear Chinese, when we reference them as Earthman, then they are all deaf, then that may be hard for the alien who tries to communicate with us.

**Comment by rkuhn** [comment]
An `ActorRef` has two purposes: it describes the identity of an actor, and it may allow sending messages to that actor. The ref from `getChild` only conveys identity, not the ability to send, so `Nothing` would be correct—`Void` is the best approximation we can do for Java. Yes, these actors typically do process messages, but using this API there is no way to find out which ones that are, so we cannot return a different type.

**Comment by rkuhn** [comment]
Please don’t: existential types like the ones you propose _may_ be technically correct, but types are not only for the compiler but also for the programmer, and programmers will likely not understand the types that follow from using such a signature—and will be very confused by arcane compiler error messages.

**Comment by hepin1989** [comment]
Is there anychangethat change the Java api like to `java.util.List<ActoRef<?>>` and `Optional<ActorRef<?>>`. The current api do confused me, because the typesafe `ActorRef[T]` reads as "this ActorRef accept any message of type T`.

I do not have another better solution for the `getChild` and `getChildren` one, but the current one is confusing.

For the `getSystem` which return `ActorSystem<Void>` and `ActorSystem[Nothing]` is totally fine.

**Comment by hepin1989** [comment]
I want to raise these issues before it's to late, I program in Java mostly at work these days, really hope the API to be more Javalish for Java developers.

**Comment by patriknw** [comment]
I agree that we should not change this.

`null` as message is always invalid, although the compiler might not catch it (as many other cases of using `null`)

**Comment by hepin1989** [comment]
@patriknw So is there any reason that the original design is not going to `java.util.List<ActorRef<?>>`?
