### ISSUE TITLE
Make SideEffect internal

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26044]
Every time I look at code related to Effect and SideEffect in Persistence Typed I wonder if we need to have `SideEffect` in the public API.

As far as I can see it's only exposed in `andThen`, and the preferred way is to use the other `thenRun`, `thenStop`.

Should we make it internal?

**Comment by patriknw** [comment]
One example of `commonChainedEffects` is given in the docs which is the motivation for having the type. https://doc.akka.io/docs/akka/current/typed/persistence.html#effects-and-side-effects

Is that going to be used?

**Comment by johanandren** [comment]
That sample doesn't make sense at all to me, as you can just pass a function instead. I'll pick this up.
