### ISSUE TITLE
sbt 1.2.7 broke unidoc/javadoc with jdk9

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26057]
The update to sbt 1.2.7 in https://github.com/akka/akka/commit/6ba4c341f5d2a090c28e9ec92d0ea05f7188de61 broke unidoc/javadoc

Reproduce with sbt 1.2.7:
```
sbt -Dakka.genjavadoc.enabled=true
> clean
> unidoc
...
javadoc exited with exit code 1
```

I have verified that it was not the `classpath 4.4.12` update that caused it.

**Comment by patriknw** [comment]
@eed3si9n what do you think about this issue? Shall I open an issue in sbt or unidoc?

**Comment by patriknw** [comment]
I have added unidoc to one of the nightly builds. It takes long to run so don’t want to slow down every PR validation.

**Comment by dwijnand** [comment]
https://github.com/sbt/zinc/pull/612?

**Comment by eed3si9n** [comment]
Dale's theory sounds plausible.
@patriknw Could you open an issue on sbt-unidoc, and see if we can workaround it.

**Comment by eed3si9n** [comment]
Looking at https://github.com/akka/akka/pull/26050, I wonder if this is just exposing Java errors.

```java
[error] /Users/patrik/tmp/akka/akka-actor-typed/target/java/akka/actor/typed/DispatcherSelector.java:34:1:  error: illegal combination of modifiers: abstract and static
[error]   static public abstract  akka.actor.typed.Props next ()  ;
[error]                                                  ^
```

**Comment by eed3si9n** [comment]
Opened an issue on genjavadoc - https://github.com/lightbend/genjavadoc/issues/154

**Comment by patriknw** [comment]
> Looking at #26050, I wonder if this is just exposing Java errors.

Those "errors" exists also in a successful build, so that is unrelated. Has been like that since the early days of genjavadoc and has not been a problem for the end result.

**Comment by patriknw** [comment]
I should also mention that I used JDK 9.

**Comment by patriknw** [comment]
That makes sense, then I understand the problem. I agree that we should look into the genjavadoc issue.
