### ISSUE TITLE
 Feature request:Add ThreadLocalPropagationActor?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26056]
I think it would be nice that there is a new Actor type which supports ThreadLocal transmission.
Our inner tracing/rpc system huge depends on this behavior, we have some kind of code like this.

```java
    public final static class EagleEyeFutureTask<T> extends FutureTask<T> {
        // save the current context, and propagate it to the worker thread.
        private final RpcContext_inner rpcContext = EagleEye.getRpcContext();
        private final Thread submitThread = Thread.currentThread();

        public EagleEyeFutureTask(Callable<T> callable) {
            super(callable);
        }

        public EagleEyeFutureTask(Runnable runnable, T result) {
            super(runnable, result);
        }

        @Override
        public void run() {
            if (submitThread != Thread.currentThread()) {
                EagleEye.setRpcContext(rpcContext);
            }
            try {
                super.run();
            } finally {
                if (submitThread != Thread.currentThread()) {
                    EagleEye.clearRpcContext();
                }
            }
        }
    }
```

If we want to leverage the Actor more directly, a better way is adding another kind of `Actor`, maybe 
`ThreadLocalPropagationActor` and override both the `aroundReceive` and the `send` method, I open up here maybe there is someone else in the community depends need this behavior too?

User could achieve this by custom Actor subclass too, so maybe this a won't fix?

**Comment by patriknw** [comment]
This is not something we would like to include in Akka itself, but you should be able to do it on your side. Although `aroundReceive` is marked as internal API it's not something we will change so it would be safe for you to override that from Java:
```
    @Override
    public void aroundReceive(PartialFunction<Object, BoxedUnit> receive, Object msg) {
      super.aroundReceive(receive, msg);
    }
```

In Typed it should be possible to do with a `BehaviorInterceptor`.

PS. Full MDC and trace propagation is supported by Cinnamon.

**Comment by hepin1989** [comment]
@patriknw Yes, that what I was thinking about,  this should not be included in Akka itself, thank you for that information.

**Comment by hepin1989** [comment]
Let me close this issue and let as it for a record.
