### ISSUE TITLE
akka.actor.typed.internal.StashBufferImpl.unstash doesn't provide the correct semantics

### ISSUE THREAD

**Issue by briangordon** [akka/akka#26065]
The `unstash` implementation doesn't exactly provide the semantics described in the scaladoc for `akka.actor.typed.scaladsl.StashBuffer.unstash`:

```
   * It's allowed to stash messages while unstashing. Those newly added
   * messages will not be processed by this call and have to be unstashed
   * in another call.
```

https://github.com/akka/akka/blob/fafc59b/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/StashBuffer.scala#L118

The only time you'd run into the situation described in the scaladoc is if you call `unstash` with a `numberOfMessages` which is greater than the current size of the stash. But in that case, the iterator in `akka.actor.typed.internal.StashBufferImpl.unstash` will keep pulling messages out as  long as the buffer is nonempty. So it seems like in fact the scaladoc is lying!

**Comment by patriknw** [comment]
The scenario referred to is if you unstash all, and then stash some of them again while the previous unstash is in progress.

I think that works as intended, but there could be something else that should be improved or documented.

**Comment by briangordon** [comment]
@patriknw Yes that makes sense for the unstashAll method but I'm referring to specifically the `unstash` method I linked to where you provide the number of messages that you want to unstash. Since you're specifying the exact number, and the queue is FIFO, you would never expect newly added messages to be processed by the call unless `numberOfMessages` is greater than `size`.

**Comment by patriknw** [comment]
I think that method should cap the `numberOfMessages` to at most the current `size` of the buffer, i.e. `min(numberOfMessages, size)`.

@briangordon Would you be able to create a pull request for that?
