### ISSUE TITLE
Java example with @lombok?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#26072]
```java
@Data
@AllArgsConstructor
@Builder
public class AgooPushedEvent implements MetricsEvent {
  private final MsgSingleDTO msgSingleDTO;
  private final AgooParamDTO agooParamDTO;
  private final ClientPlatformEnum clientPlatformEnum;
  private final MessageSendDTO messageSendDTO;
  private final boolean sendSuccess;
}
```
Something like this could make the code snips shorter? or at least recommend it? even I am not a fun of Lombok its self but it does help when programming with plain old Java immutable objects.

**Comment by hepin1989** [comment]
Another good one is the https://immutables.github.io, maybe there could be a `with Lombok` and `with immutables` sections in the Java reference.

**Comment by hepin1989** [comment]
Yes, I saw most developer is using the Lombok in my company, The only drawback for Lombok is debugging, but that's fine for a data object.

**Comment by satansk** [comment]
That's good, Lombok is a good friend for Java guys, it's been widely used.

**Comment by mghildiy** [comment]
Is this issue open to be worked upon?

**Comment by patriknw** [comment]
Yes, contribution of this would be useful

**Comment by mghildiy** [comment]
Where can I find code snippets which need to be modified?

**Comment by patriknw** [comment]
I think it should be a new page. We can steal most of Lagom's documentation for this (skipping Immutables section): https://www.lagomframework.com/documentation/current/java/Immutable.html#Using-immutable-objects

**Comment by mghildiy** [comment]
I have a question. 
While any change done at https://github.com/lagom/lagom/tree/master/docs would be reflected at site https://www.lagomframework.com/documentation, where are the changes done here(https://github.com/akka/akka/tree/master/akka-docs) reflected?I it at https://akka.io/docs/?

**Comment by patriknw** [comment]
Yes, for example, the source for https://doc.akka.io/docs/akka/current/typed/actors.html is in https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/typed/actors.md

**Comment by mghildiy** [comment]
I would name the file Immutable.md. 
Where I should I insert it in the order defined in index.md?

**Comment by patriknw** [comment]
Good question. I'm haven't decided yet, but you can start with adding it to the Actors index and we can discuss in the PR where it should be. https://doc.akka.io/docs/akka/current/typed/index.html

**Comment by mghildiy** [comment]
https://github.com/akka/akka/pull/28539

**Comment by Captain1653** [comment]
This issue is quite old. PR was merged. Should It be closed?

**Comment by johanandren** [comment]
Looks like an oversight yes, thanks.
