### ISSUE TITLE
FIXME leaked to online document.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26076]
![image](https://user-images.githubusercontent.com/501740/49662182-1c2be300-fa86-11e8-873b-6031dda54344.png)
https://doc.akka.io/docs/akka/current/typed/guide/introduction.html#how-to-get-started

**Comment by patriknw** [comment]
Well, that was on purpose. The referenced quickstart is wrong, because the new doesn’t exist yet. Good that the reader sees that.
