### ISSUE TITLE
Publish Java API docs for 2.5.19

### ISSUE THREAD

**Issue by raboof** [akka/akka#26108]
https://doc.akka.io/japi/akka/2.5.19/ is empty

**Comment by patriknw** [comment]
Strange, how come?

**Comment by patriknw** [comment]
Something wrong with the build?

I thought it worked when reverting to sbt 1.2.6 in #26057 , but perhaps it just silently passed?

For now I changed the `current` symlink to point to 2.5.18

**Comment by raboof** [comment]
I did a `clean unidoc` and it does appear to generate `javaunidoc` content. Perhaps something (an empty directory?) remained from the 1.2.7 build and sbt incorrectly assumed there was cached content there?

**Comment by patriknw** [comment]
1.2.7 issue was found on my dry-run. Release was cut by @chbatey

Good that it works.

**Comment by raboof** [comment]
I'm guessing some one-off problem then... added https://github.com/sbt/zinc/pull/625 to make sure it doesn't go unnoticed so easily and manually uploaded the japi docs for 2.5.19. https://doc.akka.io/japi/akka/current/ still looks a bit weird but that's probably a caching issue.
