### ISSUE TITLE
Add mention of @Deprecated for Java APIs to CONTRIBUTING.md

### ISSUE THREAD

**Issue by helena** [akka/akka#26107]
Because scala @deprecated will not show up in Java IDE's and javadocs, add a note in the appropriate section of `CONTRIBUTING.md` to add @Deprecated when something is @deprecated for Java usage, e.g. not using implicits.

**Comment by patriknw** [comment]
Strange, I think I have verified this before and genjavadoc adds it to javadoc. Let me check again.

**Comment by helena** [comment]
Automated from the build? Would be so much better 👍 Thanks for the check.

**Comment by patriknw** [comment]
It's included by Genjavadoc, see for example `ActorIdentity.getRef`: https://doc.akka.io/japi/akka/2.5.18/akka/actor/ActorIdentity.html#getRef--

and it's shown as deprecated in IDEA:
<img width="549" alt="screen shot 2018-12-11 at 18 43 30" src="https://user-images.githubusercontent.com/336161/49819177-06176e80-fd75-11e8-9dc7-d1663ddd9c78.png">
