### ISSUE TITLE
When using EagerClose on a TLS connection, the handshake may fail if one of the sides completes before the handshake is complete

### ISSUE THREAD

**Issue by raboof** [akka/akka#26104]
It appears that when either side completes before the handshake is complete, the SSLEngine goes into ERROR/CLOSED state and is no longer valid for processing data on the other half of the connection.

This problem occurs under JDK8. In later JDK's it appears this code was rewritten and no longer shows the problem.

**Comment by jrudolph** [comment]
I.e. `SSLEngine.closeOutbound` has been called before the handshake is complete (which is not forbidden by the SSLEngine documentation).

The solution for JDK 8 would therefore be to defer calling `closeOutbound` until the handshake has been finished.

**Comment by jrudolph** [comment]
The same seems to happen if you cancel the other port, i.e. call `closeInbound` before the handshake has finished.
