### ISSUE TITLE
Add replacement for untyped TestActor to typed ActorTestKit

### ISSUE THREAD

**Issue by magro** [akka/akka#26116]
Starting with akka typed I wanted to rewrite a former implementation using `TestActor` (+ `AutoPilot`) to akka typed. I.e. I wanted to specify a behavior / actor that I could pass to some component while being able to observe messages received by the behavior / actor.
Looking at `ActorTestKit` and `TestProbe` it wasn't immediately obvious to me how to do this.

I found that I could achieve the same with a combination of a behavior monitored by a `TestProbe`:
```scala

class TestActor[M](val probe: TestProbe[M], val ref: ActorRef[M])

object TestActor {

  implicit class RichActorTestKit(testKit: ActorTestKit) {

    def createTestActor[M](behavior: Behavior[M]): TestActor[M] =
      TestActor(behavior, testKit)

  }

  def apply[M](behavior: Behavior[M], testKit: ActorTestKit): TestActor[M] = {
    val probe = testKit.createTestProbe[M]()
    val actorRef = testKit.spawn(Behaviors.monitor(probe.ref, behavior))
    new TestActor(probe, actorRef)
  }

}
```

Would you be open for such a contribution, i.e. adding `createTestActor` to `ActorTestKit`?
Alternatively I'd suggest to extend the typed testing documentation so that it shows how to achieve observable behavior / replace untyped `TestActor`.
If there are other/better ways to achieve this or if I missed s.th. please let me know.

**Comment by patriknw** [comment]
We have challenged if all features of the untyped testkit are needed, and the AutoPilot is one of them that we haven't been able to motivate to add. It looks like what you are asking for can be done with 2 lines of code

```
    val probe = testKit.createTestProbe[M]()
    val actorRef = testKit.spawn(Behaviors.monitor(probe.ref, behavior))
```

I think it's better to keep that in user land than introducing a new utility/concept. Documentation of the pattern would be welcome.

**Comment by magro** [comment]
Thanks, that's exactly what I'm using. I'll submit a PR for the docs.
