### ISSUE TITLE
Cluster Aware Router with Group of Routees losses random messages

### ISSUE THREAD

**Issue by ekpar** [akka/akka#26118]
Hi, we are working on an Akka Cluster project (Java API version 2.5.19, integrated with Spring) where some Router routee's (Cluster Aware Route with Group) are lossing random messages (no error and no deadletters in logs and generally in the middle of the total process)

We are scraping a big csv file and sending rows to a Router (Cluster Aware Route with Group) with RowProcessor routees that do processing and finally reports to a ScraperReducer.

The RowProcessor routees get and process all rows aware each node, but generally one or two messages not arrive back to the ScraperReducer with no deadletter and not error en logs.

**IMPORTANT: if we replace Cluster Aware Route Group with local Router Pool in each node, and do routing manually/random to each node the process completes sucessfully without losses.**

Config:

akka {  
  loglevel = "DEBUG"
  actor {
    provider = "cluster"
  }
  remote {
    netty.tcp {
      hostname = "10.0.0.22"
      port = 2551
    }
    artery {
      enabled = on
      canonical.hostname = "10.0.0.22"
      canonical.port = 2551
    }
  }
  cluster {
    seed-nodes = [
      "akka://V12System@10.0.0.23:2551",
      "akka://V12System@10.0.0.24:2551"]
  }
  actor.deployment {
    /theRouter/routees {
      router = round-robin-group
      routees.paths = ["/user/rowProcessor"]
      cluster {
        enabled = on
        allow-local-routees = on
        use-roles = ["seed"]
      }
    }
  }
}

**Comment by javierpajaro** [comment]
More on this:

# of messages sent to router (over TCP) do not exceed 200. 

each message weighs at most 20MB.

messages are serialized using akka.serialization.JavaSerializer

**Comment by johanandren** [comment]
Closing this since it has been around for a long while with no action, please re-open if it was never solved or if someone can provide a minimal repeater.
