### ISSUE TITLE
Update documentation for Type Persistence to use EventSourcedEntity instead of PersistentEntity

### ISSUE THREAD

**Issue by RomanIakovlev** [akka/akka#26120]
Looking at https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html#persistence-example, the term `PersistentEntity` is used a couple of times in the textual description, while the code examples refer to the `EventSourcedEntity`. Due to renaming of `PersistentEntity` to `EventSourcedEntity` in https://github.com/akka/akka/pull/26048, I believe the correct term to use there would be the `EventSourcedEntity`.

**Comment by raboof** [comment]
Yes indeed!
