### ISSUE TITLE
PreRestart signal when exception from unstashAll

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26148]
If an exception is thrown when processing stashed messages the PreStart signal should be emitted to the `Behavior` that threw. Since the unstashing may change behavior for each message the supervisor strategy doesn't have the "right" Behavior.

Similar for the unstash that may happen after waiting for children to stop when parent is restarted, https://github.com/akka/akka/pull/26137

This could be of importance if the `PreRestart` is used for resource cleanup (similar to a `PostStop`).

**Comment by patriknw** [comment]
This is difficult because the StashBuffer and SupervisorStrategy are completely decoupled. One way might be that the StashBuffer wraps the exception in a special UnstashException that carries the Behavior that threw and the original exception. Then the SupervisorStrategy could be aware of this and "install" the right Behavior.

**Comment by patriknw** [comment]
We discussed two alternatives

1) StashBuffer catches exception wraps the exception in a special UnstashException that carries the Behavior that threw and the original exception. Then the SupervisorStrategy could be aware of this and "install" the right Behavior.

2) StashBuffer mutates the "current behavior" via the ActorContext after processing each message. Something similar is in progress in https://github.com/akka/akka/pull/26261

Alternative 2 might be less bad.

**Comment by helena** [comment]
Thanks @patriknw -"less bad" is an interesting way to put it. My concern there is mutating the current behavior - what unintended behavior or state changes can occur, what has to be guarded against, or if something is already doing that. Will investigate soon.

**Comment by patriknw** [comment]
In the end the `ActorAdapter` has the `var behavior` that is changed after each message. Conceptually it's not wrong to change it also after unstashing of a message. There could be implementation details I haven't thought of though.
