### ISSUE TITLE
Expose our Jenkins on a standard port

### ISSUE THREAD

**Issue by raboof** [akka/akka#26143]
Our Jenkins server is available on a non-standard port (http://jenkins.akka.io:8498/), which in some networks can be blocked. It might be nice to serve it on port 443 so it is easier to access from such networks.

**Comment by Captain1653** [comment]
The issue is old. Akka uses Github Actions now (I have found #30595 ). Is it still needed?

**Comment by raboof** [comment]
Nope, thanks!
