### ISSUE TITLE
Why typedActors are deprecated. 

### ISSUE THREAD

**Issue by politrons** [akka/akka#26144]
Good morning,

I read that typeActor it's deprecated and it will replace by the akka typed. But I dont understand why one have to replace the other, when they are doing things completely different. In our case, we use typedActors since we have a Framework where using reflection in the initialization of the service, the consumer of the framework that create Java POJO are used to create typedActor, so those consumers have an actorSystem even without know Akka. They use just the POJO, and behind the communication is using Akka mailbox with Dispatcher for Bulkheading and so on.
So in case you deprecate this technology in favor of Akka typed, how can I have similar feature with the current Akka stack?.

Regards

**Comment by patriknw** [comment]
We think transparent remoting is a bad idea. Transparent remoting is when you try to make remote method invocations look like local calls. In contrast we belive in location trancparency with explicit messaging between actors (same type of messaging for both local and remote actors). You can read more about it in Roland Kuhn’s book.

That said, the implementation is encapsulated in one file so it shouldn’t be difficult for you to move it to your framework. https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/TypedActor.scala

**Comment by politrons** [comment]
Hi, thanks for the response. Maybe I did not understand well,  but you’re telling me that using typedActors I don’t have location transparency right now if I configure my actor system in Cluster mode?. As far as I know that’s not correct and you can use Typed actor in Cluster mode. 
Sorry again but the only different that I see between normal actor message and typed actor is that once the actor recieve a message, it must use reflection to invoke the method with the argument received in the message.   But apart from that the message system
Is exactly the same. Please correct me if I’m wrong 

Regards

**Comment by patriknw** [comment]
It is about ”transparent remoting” vs ”location transparency”. Read this https://livebook.manning.com/#!/book/reactive-design-patterns/chapter-5/

**Comment by patriknw** [comment]
See also discussion in https://github.com/akka/akka/issues/25516
