### ISSUE TITLE
Create one SBT general task to run locally before pushing a PR

### ISSUE THREAD

**Issue by helena** [akka/akka#26157]
This is about efficiency.

I run a handful of build tasks manually, for each PR, before pushing and would prefer to automate locally with one combined SBT task vs run one or two tasks, push the PR, then go knit a sweater, plot world domination, write a new programming language while all the Jenkins validations and tasks run.

Thus, I'd like to add one that you can run locally combining:
clean
module-changed/test
module-changed/mimaReportBinaryIssues
akka-docs/paradox
 
and as usual if I do a change across >1 module this really simplifies things. My laptop may melt down or take flight but at least my SBT tasks are handled all at once, roughly.

This of course is not all one would have to run. And some changes touch main or test classes in other modules, this is where, per the above, you need to run in all modules.

The primary justification is Jenkins round trips take forever. Would prefer to catch more locally first, it's easy to forget to run docs* and mima*

**Comment by patriknw** [comment]
The PR validation sbt has some intelligence to find what modules have changed and only test those and downstream modules. Maybe that can be run locally too?

There is a proposed new PR validation task, which we haven’t dared to merge yet, but we should probably base any additional work (if needed) on that instead: https://github.com/akka/akka/pull/25264
