### ISSUE TITLE
Feature request:Add Source.empty which take Clazz just as Flow.of for Java API.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26160]
Currently:
![image](https://user-images.githubusercontent.com/501740/50547163-990a4100-0c6f-11e9-896c-ac0987f7a1e5.png)

It would be nice to:

```java
    Source.empty(DataElement.class)
        .map(new Inject<>(p, "p"))
        .filter(new Filter("price > p"))
        .to(
            Sink.fold(
                Collections.emptySet(), 
                new DistinctValues<Pair<String, String>>("make", "model")));
```

**Comment by raboof** [comment]
I'm not sure I understand what this would do - would `Source.of(DataElement.class)` be equivalent to `Source.<DataElement>empty()`? Then running this graph would always produce an empty list, right?

**Comment by hepin1989** [comment]
Ok ,`of` is not a good name.then how about `Source.empty(DataElement.class)`?

**Comment by Seetaramayya** [comment]
created [pull request](https://github.com/akka/akka/pull/26166). 

This issue is not picked up by anyone so I created tiny pull request.
