### ISSUE TITLE
Deprecate Persistent mode of Cluster Sharding

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26177]
In favor of only maintaining ddata mode

**Comment by patriknw** [comment]
We might have to add a pluggable API for the state storage of rembered entities since file based storage isn't very cloud friendly. Could be another implementation of DData durable storage.

**Comment by patriknw** [comment]
@tunesmith asked:

> Hi, can you share more explanation on the reasoning behind deprecating/removing the persistence mode of sharding? I was under the impression that sharding persistence scaled out better than ddata.

This has not been fully decided yet but this is my current thinking.

The reason is mostly to reduce maintenance footprint and simplify the implementation of Cluster Sharding. 

The Persistence mode is also more difficult to operate, especially if an application is not using Akka Persistence for other reasons but anyway wants to use Cluster Sharding. When running without proper downing provider it's easy to end up with the problem described in https://doc.akka.io/docs/akka/current/cluster-sharding.html#removal-of-internal-cluster-sharding-data

The scalability of "remembered entities" has feature has limitations, especially for the DData mode and that's why I suggested supporting another storage backend for that. However, that part is also what makes the effort of completing this ticket large.

Scalability of the DData mode with regards to number of nodes and sharding should be ok, but it's a good point that we might want to think about that. E.g. majority writes/reads in a 500 nodes cluster might not be great.

**Comment by helena** [comment]
One argument in support of this is in the context of duplicate/similar logic coming in #24698, where one would leverage that instead.

**Comment by helena** [comment]
I'll take this unless someone else beats me to it.

**Comment by helena** [comment]
There is the case where one would want to leverage cluster sharding and have their own persistence requirements and not need it via this module.

**Comment by helena** [comment]
Starting with team discussion and I'll compile a doc to prep

**Comment by patriknw** [comment]
Notes from discussion today.

For the shard coordinator state ddata is fine, no scalability problems on that level.
It's when using remember entities that ddata could be limiting since id of each active entity must be stored. Also file storage that is used for durable ddata can be problematic in K8 environments.

A solution for remember entities would be to not use ddata for that state. Instead define a pluggable data access API, backed by implementations for Cassandra and JDBC. DData implementation could also be an option for when not using too many entities and for development mode.

At the same time we should clean up the implementation of the inheritance based `Shard`, `DDataShard`, `PersistentShard` classes that have become rather complicated. Better would be to separate the remember entities concern in a separate "entity tracker" actor (or class), which would be responsible for that part, and the interaction with the DB access API.

**Comment by helena** [comment]
Depends on https://github.com/akka/akka/issues/27763. The basic deprecation is merged. This can track the deprecation completion and rationale. Needed separate for docs.

**Comment by patriknw** [comment]
So the remaining of this ticket is to mention in migration guide, which was missing from https://github.com/akka/akka/pull/27585/files

That must be done before 2.6.0 final, since it's already deprecated.

The replacement is covered in #27763.
