### ISSUE TITLE
Disable remote watch and remote deployment outside Cluster

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26176]
Disable remote watch and remote deployment (or system messages in general) when Cluster is not used. Should still be possible to opt-in.

**Comment by kpritam** [comment]
Similar to question posted here on issue [26491](https://github.com/akka/akka/issues/26491),
would like to know how that architecture will work with these changes?
Architecture summary:
1. Each machine has one JVM which takes part of cluster
2. Other JVM's from that machine registers themeself by sending HTTP request to JVM which is part of cluster
3. Then that JVM starts watching all remote actor refs which are registered with them.
4. Also we have many `PubSub` actors which are spawned with remoting and not part of real akka cluster
5. Forcing All the JVM's from single machine to take part of akka cluster does not seem to be good idea as we will be having lots of them on each machine
6. We do not want to flood network with gossip messages and having lots of JVM taking part of cluster makes it hard to manage when one of them gets shutdown. Then cluster becomes inconsistent and causes other problems like new members can not join or they join with weekly up status.

**Comment by patriknw** [comment]
I'll look into your questions early next week

**Comment by patriknw** [comment]
@kpritam Looking at the drawing at https://github.com/akka/akka/issues/26491#issuecomment-471497736

Is the communication between JVM-1 and JVM-2 on Machine 1 using Akka remoting, HTTP or both? I interpret it as the registration is done with HTTP (for some reason) and then Akka remoting is used.

The main problem with Akka remoting without cluster is remote death watch and remote deployment. As soon as the failure detector triggers it will quarantine the other side and that can't heal without restarting one of the ActorSystems. https://doc.akka.io/docs/akka/current/remoting-artery.html#quarantine

One way is to not use the features watch and remote deployment between JVM-1 and the other local JVMs (that is what this issue is about). Another option is to detect the problem and restart JVM-2 when there is such situation between JVM-1 and JVM-2.

I think your design is valid. There could be good reasons for why you don't want all JVMs to be part of the cluster.

It will still be possible to use Akka remoting, like this, but it should be seen as a power user feature that can be used when you know what you are doing and are aware of the consequences.

Thanks for input.

**Comment by kpritam** [comment]
We started with the design you suggested (every JVM taking part of akka cluster).
Reasons for migrating to above architecture:

1. Our domain will have 100-200 JVM's spread across 10-20 physical machines
2. We also have short running CLI's which used to take part of `akka-cluster`
     - This caused us very bad user experience
     - It used to take lot of time to `join the existing cluster -> perform action -> leave cluster`
     - we used to see lot of errors in CLI's some times if cli does not gracefully 
        leaves cluster (even though using `CoordinatedShutdown`)
     - this made us to rethink our design
3. Hence we started to spawn a light weight service called `location service` on every machine like a agent which exposes HTTP interface for other JVM's from that machine and does gossiping with other location service agents running on other machines
4. Now all CLI's just make HTTP rest call to local location agent to query information and terminates
5. Considering we have 100-200 JVM's, if any of them goes down in worst cases, cluster works just fine because they are not part of cluster. 
6. location agent also does death watching, so if any of the JVM goes down, all the interested party gets notified.

And this seems to be working out very well for us.
Please do let us know if there are any gotchas we should be aware of.

**Comment by patriknw** [comment]
I think that sounds reasonable and as long as you are aware of the death watch and quarantining issues when used outside the cluster it should work fine.

**Comment by helena** [comment]
And add to migration guide.

**Comment by helena** [comment]
Do we want to fall back to a local Deployer in the case that Cluster is not used and a (new) `RemoteSettings.UseRemoteDeploymentWithoutCluster` is `off`? And perhaps we should log that case, as a warn?

**Comment by patriknw** [comment]
It's an interesting question in general how we should report violations. We can't throw exception since it's typically an async operation happening elsewhere.

For deployments I think it sounds good to fall back to local, i.e. it's created as a normal local child actor. Warning logging ofc.

For watch I'm uncertain. Just skip the watch?

**Comment by helena** [comment]
I have it currently skipping watch in this case. For deployer, I'd want to be alerted that a local deployer is in play but it would not be an error - assuming the settings are what the user intended. Good for them to know with a log warn in case.

**Comment by helena** [comment]
Initially I started with two separate configs but we really just want one, to disallow an opt-in watch that doesn't match deploy
```
watch {

      # If Cluster is not used, remote watch is disabled.
      # To optionally use remote watch while not using Cluster, set to 'on'.
      use-without-cluster = "off"
    }

    # remote deployment configuration section
    deployment {

      # If Cluster is not used, remote deployment is disabled.
      # To optionally use remote deployment while not using Cluster, set to 'on'.
      use-without-cluster = "off"
```

**Comment by patriknw** [comment]
I agree it should be one setting.
```
use-unsafe-remote-features-without-cluster = off
```

?

**Comment by helena** [comment]
Yes, `use-unsafe-remote-features-without-cluster` is much better than `use-watcher-and-deployment-without-cluster`
