### ISSUE TITLE
Migration guide for Cluster Client to Akka gRPC

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26175]
We recommend using Akka gRPC over using Cluster Client and we should document this migration path. When doing this and thinking more about it we can evaluate if it's enough with documenting the replacement or if we still find some of the Cluster Client features useful and should be provided as convenience, implemented on top of Akka gRPC.

Some things that Cluster Client currently supports and brief thoughts about replacement:

- contact points replaced by service discovery?
  - initiial contact points
  - select, consistent hashing on server side so that same choice independent on where the client connects
  - refresh list of contact points from cluster
- heartbeats and establish new connection to the cluster
- Send to one (routing) or all actors that have registered as a service
  - integration with Typed Receptionist
  - maybe a subset of all actors registered to Receptionist should be exposed to clients
  - local affinity
- Publish to named topic, can be replaced by the Send to Receptionist key
- manage sender, replyTo ActorRef, in Typed part of the messages
- replies to client should find their way back via the same Cluster node that the client is connected to
- convenience of ordinary actor messages, and serialization
- the "connection" between client and cluster could be bidirectional gRPC stream
  - end-to-end backpressure not needed since actor messages

**Comment by helena** [comment]
@patriknw And note deprecation of Cluster Client?

**Comment by patriknw** [comment]
I have create an example that can be used to illustrate how to migrate from Cluster Client: https://github.com/patriknw/akka-cluster-client-grpc/pull/2

Remaining tasks (don't have to be done by me):
- [ ] Review https://github.com/patriknw/akka-cluster-client-grpc/pull/2
- [ ] Maybe add the service discovery "config" to the example
- [ ] Create corresponding in Java, since it's intended for copy-paste usage
- [ ] Decide where to host the examples. GitHub repo in akka org?
- [ ] Deprecate Cluster Client in Akka

**Comment by helena** [comment]
@patriknw We could separate the remaining tasks into two, aside from the review, because half relate to examples, the other to deprecating and modifying the migration guide.

Created https://github.com/akka/akka/issues/27242

**Comment by helena** [comment]
Additionally we should re-assess https://github.com/akka/akka/issues/17720, close or mark in other way.

**Comment by patriknw** [comment]
ok, closed second ticket

**Comment by helena** [comment]
As for where to host [the migration sample](https://github.com/patriknw/akka-cluster-client-grpc/pull/2#pullrequestreview-267446390) 

I can debate this two ways
1. I'd suggest moving this to a new repo under https://github.com/akka though Akka gRPC is a separate project under the akka org, so does the migration sample even belong in the  `akka-samples` repo
2. Cluster client is a module _in_ Akka and the purpose of the sample is for helping users migrate, and a bit for us to see what to keep that it does functionally, elsewhere (AFAICT). So it makes sense, being a migration from Akka CC to Akka gRPC to be under the  `akka-samples` repo.

Given that outlook, I'd go with 2 - host it under `akka-samples`.

**Comment by helena** [comment]
See `git mv` PR https://github.com/akka/akka-samples/pull/116 against the 2.6 branch 
from @patriknw's https://github.com/patriknw/akka-cluster-client-grpc/tree/wip-spike2-patriknw

**Comment by helena** [comment]
Pending:
- [ ] PR: guide and sample in https://github.com/akka/akka-samples/pull/116 (from https://github.com/patriknw/akka-cluster-client-grpc/tree/wip-spike2-patriknw)
   - [ ] Pending above PR: Mention in migration guide, with links to the examples
  - [ ] [Deprecate Cluster Client in Akka](https://github.com/akka/akka/pull/27419)

**Comment by patriknw** [comment]
Samples have been merged to the akka-samples repo 2.6 branch.
Additional documentation ticket in Akka gRPC https://github.com/akka/akka-grpc/issues/697
