### ISSUE TITLE
Make Artery TCP default

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26179]

**Comment by patriknw** [comment]
Run some scalability tests, especially with Artery TCP

**Comment by chbatey** [comment]
* Review configuration 
* Leave configuration in `akka.remote.artery`
* Move classic remoting configuration to `akka.remote.classic`

**Comment by chbatey** [comment]
Should we also remove Netty UDP? It was deprecated since 2.5.0

**Comment by chbatey** [comment]
For advanced configuration that is specific to aeron-udp should we put it in a aeron-udp block to make that clear?

**Comment by patriknw** [comment]
Remove netty udp: yes

aeron-udp config section: probably good if all are in the advanced section otherwise it’s strange to have aeron-upd specifics at two levels.

**Comment by helena** [comment]
I think it's ok to remove it as well, it's been documented as deprecated in favor of... for a long time in multiple places.
