### ISSUE TITLE
Remove support for Scala 2.11

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26182]
Akka 2.6 should be released for 2.12 and 2.13

**Comment by dmi3zkm** [comment]
Any ETA of Akka 2.6 ?

**Comment by patriknw** [comment]
@dmi3zkm We haven't a detailed plan yet, and it's always difficult to give any reliable ETA for these things since other "more important" things pop in all the time. I hope we can make it before end of Q2.

**Comment by dmi3zkm** [comment]
@patriknw noted, many thanks!
