### ISSUE TITLE
Update internal Protobuf version in akka-protobuf

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26181]
Make use of the support for ByteBuffers in Protobuf 3. Not sure this can be done in a compatible way?

**Comment by jrudolph** [comment]
Maybe use the sbt-assembly shading instead of shading the source code like in https://github.com/akka/akka/pull/26481?

**Comment by mkurz** [comment]
Would be good to update to protobuf 3.7.0, see [release notes](https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.0).
[Includes a fix](https://github.com/protocolbuffers/protobuf/issues/3781) for better JDK 9+ support.

**Comment by patriknw** [comment]
Reading https://www.ben-morris.com/handling-protocol-buffers-backwards-compatibility-between-versions-2-and-3-using-c/ it seems that the wire format is compatible, but API has changed. That is good.

**Comment by patriknw** [comment]
Since it seems to be wire compatible we should give it a try.

* [ ] Make ProtobufSerializer work with proto3, or provide a new serializer for that
  * this is if users send protobuf messages as actor messages (or persistent events) without translation layer
  * it is not used internally
* [ ] shading the source code like in #26481 
  * make sure it's clear that the shaded is for internal use only
* [ ] update Akka's internal protobuf messages and serializers
* [ ] keep the old akka-protobuf module around in case it is used, but deprecate it (and remove the dependency)

**Comment by patriknw** [comment]
Merged the PR, but keeping the issue open until we have added:
- [ ] Document that akka-protobuf is deprecated and should move to their own protobuf
- [ ] Document that akka-protobuf-v3 is internal

**Comment by jroper** [comment]
I think this is going to be very helpful for Graal native image usage - the protobufs that Akka currently includes in 2.5.x don't implement hashCode/equals, which means it falls back to the reflection based implementations on the protobuf they extend, which means every protobuf Akka uses we need to include a reflection config for (technically only necessary if Akka uses equals/hashCode/toString on it, but it's not practical to know, sometimes toString is only invoked when debug is turned on). Not sure if there was a way to turn this on in Protobuf 2.x, but Protobuf 3 generates hashCode/equals/toString by default, so doesn't have this problem.
