### ISSUE TITLE
Remove duplicate code in Cluster Sharding Typed HashCode*MessageExtractor 

### ISSUE THREAD

**Issue by helena** [akka/akka#26197]
[ShardingMessageExtractor](https://github.com/akka/akka/blob/master/akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/ShardingMessageExtractor.scala) should be simplified with a re-usable function which the multiple Hash extractors can call (versus how they are doing it now - duplicating code):

Modified to @johanandren's suggestion
```scala
def shardId(entityId, numberOfShards): String =
    math.abs(entityId.hashCode % numberOfShards).toString
```

**Comment by helena** [comment]
Originally added in [#26174](https://github.com/akka/akka/pull/26174), move out to its own.

**Comment by johanandren** [comment]
Wouldn't it be even cleaner as just a pure method `shardIdFrom(entityId, numberOfShards)` than a mixin?
