### ISSUE TITLE
Expose materializer, attributes or actor system to Source/Flow/Sink

### ISSUE THREAD

**Issue by 2m** [akka/akka#26192]
There are quite a few connectors in Alpakka where the implementation needs access to a Materializer, Actor System or Attributes. These are currently exposed to custom GraphStages but are not easily available for simple Sources Flows or Sinks.

For example the S3 connector uses akka-http therefore it needs access to Actor System. It also has some inner flows that are run in the implementation for which it needs access to Materializer.

Current S3 connector takes these resources as parameters in the factory methods. However that makes created Sources Flows or Sinks not freely sharable because they are tied to a particular Actor System or Materializer.

We have a [WIP Alpakka PR](https://github.com/akka/alpakka/pull/1395) which exposes Materializer to arbitrary Source Flow or Sink. Here is how the typical S3 factory looks like currently:

```scala
final class S3Client(val s3Settings: S3Settings)(implicit system: ActorSystem, mat: Materializer) {
  ...
  def listBucket(bucket: String, prefix: Option[String]): Source[ListBucketResultContents, NotUsed] = ...
  ...
}
```

First user needs to instantiate `S3Client` giving the `S3Settings`, `ActorSystem` and `Materializer` as parameters. Then instance of `S3Client` can be used to create Source Flow and Sinks, which are tied to these parameters.

After the refactoring in the before mentioned PR, factories are converted to be real static factories:

```scala
object S3 {
  ...
  def listBucket(bucket: String, prefix: Option[String]): Source[ListBucketResultContents, NotUsed] = ...
  ...
}
```

The implementation of `listBucket` after the refactoring uses `lazySource` to expose the Materializer:

```scala
object MaterializerAccess {
  def source[T, M](factory: ActorMaterializer => Source[T, M]): Source[T, Future[M]] =
    Source
      .lazily(() => {
        factory(extractMat(GraphInterpreter.currentInterpreterOrNull))
      })
}
```

This approach has two downsides:
  * materialized value is wrapped into a `Future`
  * `lazySink` does not materialize the inner Sink if the stream does not emit an element. This is a problem in the S3 upload use-case where creating an empty file, which is encoded by a `Source.empty[ByteString]`, is supported.

This ticket is about discussing a supported way to expose Materializer.

One approach would be to modify the traversal logic and add a possibility to expose Materializer which would make it possible to materialize factories of `Materializer => Source/Flow/Sink`.

Another approach would be to implement a custom `GraphStage` that would wrap the Source Flow or Sink and provide Materializer and Attributes, since these are already available to the implementation of custom Graph Stages. However materialized value of the inner Source Flow or Sink would still be wrapped into a `Future` using this approach.

Let me know what you think.

**Comment by hepin1989** [comment]
Great!How about adding a method like `preMaterialize` to `GraphStageWithMaterializedValue`?
like ：
```scala
abstract class GraphStageWithMaterializedValue{
 def preMaterialize(materializer:Materializer):Unit
}
```

**Comment by 2m** [comment]
@hepin1989, yes, but such method would be useful only for side-effects (method return value is `Unit`) and only when extending `GraphStageWithMaterializedValue`. I would like to come up with something that could be used together with any Source Flow or Sink.

**Comment by 2m** [comment]
I have arrived at a clean solution to expose `ActorMaterializer` and `Attributes` by wrapping a Source, Flow or Sink with a GraphStage. Inside of the custom GraphStage it uses `Sub{SourceOutlet,SinkInlet}` to wire and run the original graph from `preStart`. You can find the [implementation in the before mentioned S3 refactoring PR](https://github.com/akka/alpakka/pull/1395/files#diff-acbd0ed1a3717eaa41f90a76888c679c).

The materialized value is still wrapped in a `Future` but that was not a problem for S3 connector, because all materialized values are wrapped in `Future` anyway.

Eventualy we will want `Setup.{source,flow,sink}` to be moved to `akka-stream` sub-project as it will be used across many Alpakka connectors.
