### ISSUE TITLE
Source.from method listed in documentation, but does not exist

### ISSUE THREAD

**Issue by jciskey** [akka/akka#26196]
Compile Error: 
> value from is not a member of object akka.stream.scaladsl.Source

The stream operators documentation lists `Source.from` as a valid ScalaDSL operator, but that method does not exist on the Scala `Source` companion object, and produces a compile error when you attempt to use it. It appears to have been subsumed by the `apply` method.

Should we modify the source code to include that `from` method, or should we modify the documentation to state that the `from` method is JavaDSL only, and ScalaDSL needs to use the `apply` method?

**Comment by jciskey** [comment]
I think that's reasonable to do. I'm not familiar with the documentation generation system being used, but can poke around and work up a patch eventually if no-one else can handle it quicker.

**Comment by raboof** [comment]
Sure! You could take inspiration from https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameterSeq.md which does something similar for `parameterSeq`/`parameterList` in Akka HTTP. Don't hesitate to ask if you have any problems!

**Comment by ignasi35** [comment]
This was already fixed and `from` (Java) and `apply` (Scala) are now served from the same [HTML page](https://doc.akka.io/docs/akka/current/stream/operators/Source/from.html)
