### ISSUE TITLE
failed: AsyncDnsResolverIntegrationSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26203]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-nightly/runs/6168/log/?start=0

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14673/testReport/junit/akka.io.dns/AsyncDnsResolverIntegrationSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6786/testReport/akka.io.dns/AsyncDnsResolverIntegrationSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6787/testReport/akka.io.dns/AsyncDnsResolverIntegrationSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by patriknw** [comment]
@chbatey This is still failing after merging your PR
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6790/consoleText

```
[info] akka.io.dns.AsyncDnsResolverIntegrationSpec *** ABORTED *** (1 second, 835 milliseconds)
[info]   com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create?name=akka-test-dns-akka.io.dns.AsyncDnsResolverIntegrationSpec: 409, body: {"message":"Conflict. The container name \"/akka-test-dns-akka.io.dns.AsyncDnsResolverIntegrationSpec\" is already in use by container \"dafb1607bdac056b723c108631fa745f9558202db014e66e5c77cfca55396524\". You have to remove (or rename) that container to be able to reuse that name."}
[info]   at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2820)
```

**Comment by chbatey** [comment]
Closed by https://github.com/akka/akka/pull/26378
