### ISSUE TITLE
AtLeastOnceDelivery: only tick when there are unconfirmed deliveries?

### ISSUE THREAD

**Issue by raboof** [akka/akka#26216]
`AtLeastOnceDelivery` currently uses a scheduled 'tick' message to periodically check if there are any messages to be redelivered.

If you have a lot of actors that mix in `AtLeastOnceDelivery`, this could cause some CPU load even if there are currently no messages to be redelivered. It might be interesting to be a bit more subtle about when to trigger a `RedeliveryTick`: either scheduling it for the moment the next unconfirmed message is supposed to be redelivered, or at least only ticking when the set of `unconfirmed` messages is nonEmpty.

**Comment by patriknw** [comment]
Should be easier to implement nowadays with the `Timers` support.
