### ISSUE TITLE
log all messages for typed actor

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26226]
For untyped we have `akka.actor.debug.receive` + `LoggingReceive` would be good if we had a counterpart for typed, perhaps a `Behaviors.logMessages(behavior)` for opting in, or provide something in the actor adapter to have it always available.

**Comment by patriknw** [comment]
I think it's good to be able to enable it on specific actors and therefore I think`Behaviors.logMessages` (impl via `BehaviorInterceptor`) is good.

**Comment by seglo** [comment]
I'll take a crack at this.

**Comment by patriknw** [comment]
great, thanks
