### ISSUE TITLE
Support nowrap=true in inflate flow

### ISSUE THREAD

**Issue by KarlSjostrand** [akka/akka#26227]
Issue https://github.com/akka/akka/pull/23845 included added support for skipping header and checksum bytes when deflating byte streams. The same is as far as I can understand not available in `Compression.inflate`.  I am working on a streaming reader for a file format (DICOM) where the body of a file may be deflated in this format (corresponding to `nowrap=true` in `java.util.zip.Inflater`). As a workaround, I had to copy the akka internal classes `DeflateDecompressor`, `DeflateDecompressorBase` and `ByteStringParser` into my project to be able to set `nowrap=true`. 

If there is general interest for exposing the nowrap parameter in `Compression.inflate` to match the API of `Compression.deflate`, I can submit a PR.

**Comment by johanandren** [comment]
Sounds good to add, please PR!
