### ISSUE TITLE
Improved experience when jdk8 is not found

### ISSUE THREAD

**Issue by raboof** [akka/akka#26222]
For releases, we explicitly compile against the JDK8 classpath of an actually-installed JDK8.

When no JDK8 is installed, we produce a relatively cryptic error message (`java.util.NoSuchElementException: key not found: 8`). That is not great for contributors who do not have JDK8 installed.

We should give a better error message in this case, and perhaps also introduce an option to ignore this issue and build with the system JDK classpath?

**Comment by nvollmar** [comment]
I've add PR #26789 with better warning and flag. Though Akka does currently not compile with OpenJDK 11 due to deprecation warnings:

```
[error] /Users/nvo/Development/git/akka/akka-actor/src/main/scala/akka/io/Dns.scala:125:105: method newInstance in class Class is deprecated: see corresponding Javadoc for more information.
[error]           val provider = system.dynamicAccess.getClassFor[DnsProvider](settings.ProviderObjectName).get.newInstance()
[error]                                                                                                         ^
[error] /Users/nvo/Development/git/akka/akka-actor/src/main/scala/akka/io/Dns.scala:172:84: method newInstance in class Class is deprecated: see corresponding Javadoc for more information.
[error]     system.dynamicAccess.getClassFor[DnsProvider](Settings.ProviderObjectName).get.newInstance()
[error]                                                                                    ^
[error] /Users/nvo/Development/git/akka/akka-actor/src/main/scala/akka/util/Reflect.scala:46:15: method newInstance in class Class is deprecated: see corresponding Javadoc for more information.
[error]     try clazz.newInstance
[error]               ^
[error] three errors found
```

**Comment by myfear** [comment]
Another place where the `java.util.NoSuchElementException: key not found: 8` shows up is the documentation generation process as described in:
https://github.com/akka/akka/blob/master/CONTRIBUTING.md#documentation

**Comment by patriknw** [comment]
@raboof Do you know if there is a requirement to have have jdk8 installed when building docs with jdk11? Can we remove that obstacle so that users can build the documentation locally without requiring a valid jdk8 installation. Would be good for contributors in general to be able to build most things without having jdk8 installed.

For releasing it's a different matter.

**Comment by raboof** [comment]
Related to #25330

**Comment by raboof** [comment]
I think #27083 is the best we can do until we somehow achieve #27079

**Comment by raboof** [comment]
When jdk8 is not found the developer can now:
* target the system jdk (#27083, though that comes with caveats)
* specify the jdk8 installation with a `JDK_8_HOME` environment variable (#28107)
* specify the jdk8 installation with a `jdk8Home` sbt setting (#28107)

That seems sufficient to close this issue.
