### ISSUE TITLE
ClusterShardingPersistenceSpec.Typed: cluster sharding with persistent actor must handle PoisonPill after persist effect

### ISSUE THREAD

**Issue by raboof** [akka/akka#26230]
https://jenkins.akka.io:8498/job/akka-nightly-2.11/802/testReport/junit/akka.cluster.sharding.typed.scaladsl/ClusterShardingPersistenceSpec/Typed_cluster_sharding_with_persistent_actor_must_handle_PoisonPill_after_persist_effect/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14621/testReport/junit/akka.cluster.sharding.typed.scaladsl/ClusterShardingPersistenceSpec/Typed_cluster_sharding_with_persistent_actor_must_handle_PoisonPill_after_persist_effect/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14632/testReport/junit/akka.cluster.sharding.typed.scaladsl/ClusterShardingPersistenceSpec/Typed_cluster_sharding_with_persistent_actor_must_handle_PoisonPill_after_persist_effect/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6259/testReport/junit/akka.cluster.sharding.typed.scaladsl/ClusterShardingPersistenceSpec/Typed_cluster_sharding_with_persistent_actor_must_handle_PoisonPill_after_persist_effect/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.11/834/testReport/junit/akka.cluster.sharding.typed.scaladsl/ClusterShardingPersistenceSpec/Typed_cluster_sharding_with_persistent_actor_must_handle_PoisonPill_after_persist_effect/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6784/consoleText
