### ISSUE TITLE
DData merge class check too strict

### ISSUE THREAD

**Issue by dilation** [akka/akka#26231]
If we have a CRDT like this:
```scala
  sealed abstract class MyCrdt extends ReplicatedData {

    final type T = MyCrdt

    final override def merge(that: MyCrdt): MyCrdt = (this, that) match {
      case (True, _) => True
      case (_, True) => True
      case _ => False
    }
  }

  final case object False extends MyCrdt
  final case object True extends MyCrdt
```

Updating may result in errors like this:
```
[DEBUG] [01/11/2019 13:00:18.928] [foo-akka.actor.default-dispatcher-4] [akka.tcp://foo@127.0.1.1:2552/system/ddataReplicator] Received Update for key [myKey], failed: Wrong type, existing type [com.example.test.ReprSpec$False$], got [com.example.test.ReprSpec$True$]
```

This is due to [here](https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/Replicator.scala#L797) directly comparing the result of `getClass`, which obviously will be different for `False` and `True`.

**Comment by patriknw** [comment]
Thanks for reporting. I think there are more such checks because it's intended to detect mistakes of using different ReplicatedData types for the same key from different nodes.

You can get around that limitation by having the two types as a value inside `MyCrdt` instead:
```
final case class(value: Value) MyCrdt extends ReplicatedData {
...
}

sealed trait Value
final case object False extends Value
final case object True extends Value
```
