### ISSUE TITLE
Cluster Usage documentation uses netty

### ISSUE THREAD

**Issue by BillyAutrey** [akka/akka#26232]
The cluster usage documentation [(here)](https://doc.akka.io/docs/akka/current/cluster-usage.html) provides a sample configuration at the top.  It includes the following:

```
    netty.tcp {
      hostname = "127.0.0.1"
      port = 0
    }
```

However, the links to examples all use artery.  This causes new users to have conflicting information when it comes to configuring a simple example of Akka cluster.

**Comment by patriknw** [comment]
Good point. We wan't to switch to Artery TCP #26179 as default in Akka 2.6.0 and before that I don't think we should update all reference documentation to Artery. Perhaps we have to revert the samples to use classic remoting again? (I wanted to sneakily lead new users into using Artery)

**Comment by BillyAutrey** [comment]
Changing the samples back would be the safest option.

Another option would be to add the netty config (commented out) in your application.conf file.  This would allow users to see the difference, in case they had that configuration and were confused as to the difference.

The only issue I see with leaving artery in is the potential for a user to copy the netty config from the documentation into their code, and then copy this line from the sample:
```java
            Config config = ConfigFactory.parseString(
                    "akka.remote.artery.canonical.port=" + port)
                    .withFallback(ConfigFactory.load());
```
This would result in no port overrides, resulting in cluster members joining on default (random) ports.

**Comment by patriknw** [comment]
Ok, can you do the changes to the samples?

Note that it's possible to have both configurations, but that might also be confusing?

```
akka.remote.remote {
    netty.tcp {
      hostname = "127.0.0.1"
      port = 0
    }

    artery {
      # change this to enabled=on use Artery, see https://doc.akka.io/docs/akka/current/remoting-artery.html
      enabled = off
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 0
    }
  }
```

One more change is needed to switch to Artery and that is to use "akka" instead of "akka.tcp" in addresses such as `seed-nodes` configuration.

**Comment by BillyAutrey** [comment]
Yeah sure, I can work on that.

I think it could be a little confusing to see both options, yeah.  But if the goal is to get people to start trying artery, the examples are a decent place to start.  Is it worth having a separate example for artery, to limit confusion?

**Comment by patriknw** [comment]
fixed in samples
