### ISSUE TITLE
Broken links to samples

### ISSUE THREAD

**Issue by Philippus** [akka/akka#26269]
It seems that a lot of links to sample projects are broken in the documentation, f.e. these pages all contain broken links:

https://doc.akka.io/docs/akka/current/multi-node-testing.html
https://doc.akka.io/docs/akka/current/camel.html
https://doc.akka.io/docs/akka/current/actors.html (link to vavr project)
https://doc.akka.io/docs/akka/current/persistence.html (link to source code)

**Comment by johanandren** [comment]
Yeah, something changed with the urls over at developer.lightbend.com and I think the redirect doesn't work as it is meant to so we better just fix the links.

**Comment by Philippus** [comment]
in the sentence 'The source code of this sample can be found in the Akka Samples Repository.'

**Comment by johanandren** [comment]
Thanks for clarifying!
