### ISSUE TITLE
Automate catching in compile time any new compiler warnings

### ISSUE THREAD

**Issue by helena** [akka/akka#26279]
Related to https://github.com/akka/akka/issues/26239

**Comment by dwijnand** [comment]
What kind of catching do you mean?  What's the behaviour you're looking for?

**Comment by patriknw** [comment]
Since there is no way to suppress warnings and we will not be able to get to zero warnings the idea was to count the number of warnings and fail the build if it increases from the known number of accepted warnings.

**Comment by helena** [comment]
@dwijnand I have a possible fix for this, just getting to it today or tomorrow. Will add you to the review.

**Comment by dwijnand** [comment]
> count the number of warnings and fail the build if it increases from the known number of accepted warnings

Interesting idea!

**Comment by helena** [comment]
Closing in favor of https://github.com/akka/akka/issues/26389
