### ISSUE TITLE
Release with jdk11

### ISSUE THREAD

**Issue by raboof** [akka/akka#26278]
We currently release with jdk9, supporting jdk8 and some extra features on jdk9

Since jdk9 and jdk10 are not LTS, it would make sense to release with jdk11, supporting jdk8 and some extra features on jdk11.

This would entail:

- [ ] move 'jdk9+' things to 'jdk11+'
- [ ] use '-release 11' rather than '-release 9' for post-jdk8 features
- [ ] update release script to require releasing with jdk11

Possibly depends on #26057 
Related to #26264

**Comment by johanandren** [comment]
FYI I did create the latest release (2.5.20) on JDK 11 without issues.
