### ISSUE TITLE
Cluster receptionist looses service keys on new node joining

### ISSUE THREAD

**Issue by senia-psm** [akka/akka#26284]
In some configurations (~2-20 cluster nodes, ~30-50 typed actors on each node registered using actor receptionist) joining of a new node kicks all ServiceKeys registered by some other node or several nodes.

Checking receptionist for registered service keys and republishing helps.

The issus might be somehow related to #26283 since I'm getting #26283 on the same environment with minor changes in actor structure (adding additional ServiceKeys triggers #26283 )

**Comment by johanandren** [comment]
Is this on the latest Akka version or some older one? Before 2.5.19 this issue was not yet addressed: https://github.com/akka/akka/issues/24887 and that sounds like it could be related.

**Comment by johanandren** [comment]
Ok, thanks for verifying, sharding should not matter in this case (note though that you should never mix different version of akka-modules)

**Comment by johanandren** [comment]
Would be great if you could share a minimal reproducer

**Comment by senia-psm** [comment]
@johanandren I'll try to create a reproducer this weekend, though it might be not a simple task. It is hard to reproduce it even on the same environment with the same source code.
For instance today I received a worse version of this issue: republishing of service key on one node was kicking service keys from another node and vice versa (there might be more than 2 nodes involved), so non of them worked for more than a couple of seconds. And cluster restart helped (same addresses, same `ServiceKey`s, same jars, etc). So it might be related to cluster's history (development environment => lots of nodes redeployment).

In case I'll fail to create a reproducer - would akka debug log from all nodes (with obfuscated class names and `ServiceKey`s) be of any help?

**Comment by johanandren** [comment]
Debug logs would be great, if you cannot create a reproducer.

**Comment by johanandren** [comment]
I spent some time trying to reproduce this today but couldn't get it to happen.

**Comment by senia-psm** [comment]
@johanandren I couldn't reproduce it on my local environment as well. I'll collect akka debug logs with this issue tomorrow.

**Comment by senia-psm** [comment]
@johanandren I've collected logs. Unfortunately I can't share logs with real class names and service keys, so I have to obfuscate all names. You can find logs here: https://drive.google.com/open?id=1nsWbrAtrx2ly0rT17VySetbdbrvlX96x

All application have been started at around 09:58. The issue appears at 10:32. In app6.log you can find this message:

> 2019-02-12 10:32:01.916 DEBUG 859 --- [ClusterSystem-akka.actor.default-dispatcher-2] akka.actor.typed.Behavior                : Change from replicator: [Map()], changes: [(obfuscatedKey149,[]), (obfuscatedKey54,[]), (obfuscatedKey136,[]), (obfuscatedKey17,[]), (obfuscatedKey146,[]), (sso,[]), (obfuscatedKey79,[]), (obfuscatedKey32,[]), (obfuscatedKey103,[]), (obfuscatedKey104,[]), (obfuscatedKey80,[]), (obfuscatedKey97,[]), (obfuscatedKey118,[]), (obfuscatedKey111,[]), (obfuscatedKey50,[]), (obfuscatedKey67,[]), (obfuscatedKey157,[]), (obfuscatedKey43,[]), (obfuscatedKey12,[]), (obfuscatedKey39,[]), (obfuscatedKey87,[]), (obfuscatedKey9,[]), (obfuscatedKey148,[])], tombstones []

`ServiceKey[obfuscated.package.ObfuscatedClass54](obfuscatedKey54)` was published by app6 at startup and never stopped.
Right before the issue there were 4 restarts:

> app4.log:2360:2019-02-12 10:31:04.943  INFO 6697 --- [ClusterSystem-akka.actor.default-dispatcher-4] akka.event.slf4j.Slf4jLogger             : Slf4jLogger started
> app7.log:2425:2019-02-12 10:30:55.395  INFO 6187 --- [ClusterSystem-akka.actor.default-dispatcher-4] akka.event.slf4j.Slf4jLogger             : Slf4jLogger started
> app7.log:2497:2019-02-12 10:31:05.523  INFO 6797 --- [ClusterSystem-akka.actor.default-dispatcher-7] akka.event.slf4j.Slf4jLogger             : Slf4jLogger started
> app8.log:2537:2019-02-12 10:31:38.989  INFO 11991 --- [ClusterSystem-akka.actor.default-dispatcher-3] akka.event.slf4j.Slf4jLogger             : Slf4jLogger started

app15 is not in cluster, so app15.log is useless.
Unfortunately app3 got broken at 10:20, so it was out of cluster as well.

I also have similar logs, but with an infinite loop of republishing: once per minute actor republishes it's service key, but it is kicked out every time. Unfortunately that logs are not from startup. I can share that logs as well.

**Comment by senia-psm** [comment]
Please note that we got a new leader right before the issue:

> app2.log:2832:2019-02-12 10:31:59.158  INFO 7848 --- [ClusterSystem-akka.actor.default-dispatcher-18] a.cluster.Cluster(akka://ClusterSystem)  : Cluster Node [akka.tcp://ClusterSystem@obfuscated-host3:2562] - Cluster Node [akka.tcp://ClusterSystem@obfuscated-host3:2562] dc [default] is the new leader
> app2.log:2876:2019-02-12 10:32:01.129  INFO 7848 --- [ClusterSystem-akka.actor.default-dispatcher-6] a.cluster.Cluster(akka://ClusterSystem)  : Cluster Node [akka.tcp://ClusterSystem@obfuscated-host3:2562] - Cluster Node [akka.tcp://ClusterSystem@obfuscated-host3:2562] dc [default] is no longer the leader
> app7.log:2728:2019-02-12 10:32:01.134  INFO 6797 --- [ClusterSystem-akka.actor.default-dispatcher-3] a.cluster.Cluster(akka://ClusterSystem)  : Cluster Node [akka.tcp://ClusterSystem@obfuscated-host1:2578] - Cluster Node [akka.tcp://ClusterSystem@obfuscated-host1:2578] dc [default] is the new leader

`obfuscated-host3:2562` is `app2`
`obfuscated-host1:2578` is `app7`

**Comment by senia-psm** [comment]
Logs for an infinite loop of republishing: https://drive.google.com/open?id=1z7ht8Y4I74SWuMb6YLz-xt4SVffR_lnw
There are only logs for app3 (with an issue) and app1 (leader at that moment). I can attach other logs on demand.
app3 restored at 11:25:30, but all it's service keys are rejected by cluster.
For instance:

2019-02-12 11:28:35.048 DEBUG 963 --- [ClusterSystem-akka.actor.default-dispatcher-15] 

> akka.actor.typed.Behavior                : Actor was registered: [ServiceKey[obfuscated.package.ObfuscatedClass171](obfuscatedKey171)] [akka://ClusterSystem/user/obfuscatedKey171#-1083808739]
> ...
> 2019-02-12 11:28:42.698 DEBUG 963 --- [ClusterSystem-akka.actor.default-dispatcher-3] akka.actor.typed.Behavior                : Change from replicator: [Map(...)], changes: [..., (obfuscatedKey171,[]), ...], tombstones []

The only way to resolve this state (as I know) is to restart the entire cluster.

There where no leader changes during this incident. The closest leader change:

> app1.log.2019-02-12.0.gz:2019-02-12 10:34:06.682  INFO 8603 --- [ClusterSystem-akka.actor.default-dispatcher-3] a.cluster.Cluster(akka://ClusterSystem)  : Cluster Node [akka.tcp://ClusterSystem@obfuscated-host1:2560] - Cluster Node [akka.tcp://ClusterSystem@obfuscated-host1:2560] dc [default] is the new leader

**Comment by senia-psm** [comment]
@johanandren I can't create a reproducer, but I can run experimental akka version with additional logging on the same environment with the same applications.

**Comment by patriknw** [comment]
Thanks for logs, we are looking into this

**Comment by patriknw** [comment]
Do I understand it correctly that the question is why obfuscatedKey54 is removed? The actor for obfuscatedKey54 is running on host4:2563 (app6.log) but it's not stopped. The "change from replicator" logging says `(obfuscatedKey54,[])`, i.e. it was removed.

**Comment by senia-psm** [comment]
@patriknw Yes. Actor is not stopped, `ActorSystem` is in cluster, but lots of `ServiceKey`s are removed for no obvious reason. Republishing `ServiceKey` helps, but sometimes we are getting an "infinite loop of republishing", ie it takes ~7 seconds for republished `ServiceKey` to get removed again (see "Logs for an infinite loop of republishing" above).

**Comment by patriknw** [comment]
I'm narrowing in on this now. Something strange on host1:2578 (app7.log) from 10:31:05. It's restarted and joined host3:2562.

At 2019-02-12 10:32:00.775 it is removing obfuscatedKey54 because it thinks host4:2563 (app6.log) has been removed.

I suspect that two separate clusters have been formed and they are talking to each other, replicating the receptionist data across.

I'll continue investigating...

**Comment by senia-psm** [comment]
@patriknw I can add cluster members logging once per minute on every node if it can help.

**Comment by patriknw** [comment]
I have a way to reproduce the problem and fix in progress. More logging not needed right now, but I would appreciate if you can test a snapshot when I have it ready.

**Comment by patriknw** [comment]
@senia-psm You can see 2 `is JOINING itself (with roles [dc-default]) and forming new cluster` in app2.log, that is an indication of that after that restart it is forming a new cluster at 10:31:59.158 while there is an existing running. My fix will handle this situation, but it might be something you want to look into on your side anyway because you probably don't want to have multiple clusters running.

**Comment by senia-psm** [comment]
@patriknw thank you! I've missed the second `is JOINING itself`.
The first one is correct: `app2` is the first one in `seed-nodes` list (`app2`, `app3`, `app7`).
So all seed nodes were down.

I've just checked logs for our kubernetes environment with `akka-discovery-kubernetes-api` instead of `seed-nodes` and this issue is a lot less frequent there, though we are still getting ~200 deleted `ServiceKey`s per day. Unfortunately I can find no `is JOINING itself` in that logs.

**Comment by patriknw** [comment]
@senia-psm I have published a snapshot with version number `2.5-20190221-135934` of PR https://github.com/akka/akka/pull/26421 
Please take that for a spin by using that version instead `2.5.21` or what you currently have and setup the snapshot repository in your build as described in https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository

I'd like to know if you still see any of your registered but not stopped actors being removed. Ultimately that shouldn't happen, i.e. your re-adding workaround shouldn't be needed.

It would be good if you add this config to enable some additional logging for cluster membership changes:
```
akka.cluster.log-info-verbose = on
```

**Comment by senia-psm** [comment]
@patriknw I'm collecting logs with snapshot version.
Unfortunately I can see this issue even without brain split:
I've restarted one of our kubernetes environments yesterday at ~14:37. I can see only one "JOINING itself" message: 

> log:
>     2019-02-21 11:37:48.959 INFO 1 --- [t-dispatcher-16] a.cluster.Cluster(akka://ClusterSystem) : Cluster Node [akka.tcp://ClusterSystem@100.98.0.2:2552] - Node [akka.tcp://ClusterSystem@100.98.0.2:2552] is JOINING itself (with roles [dc-default]) and forming new cluster 
> time:
>     February 21st 2019, 14:37:48.959

An yet I can see ~200 deleted `ServiceKey`s since the last cluster restart.

**Comment by senia-psm** [comment]
For now I have ~17 hours of logs for cluster started with snapshot akka version without a single appearance of the issue. I seems like it's gone.
I'll keep collecting logs for another 3-5 days to make sure.

**Comment by patriknw** [comment]
Thanks for testing

**Comment by senia-psm** [comment]
@patriknw  unfortunately I have to stop testing with snapshot version.
Results at the moment:
1. Cluster with `seed-nodes`: no incidents even after manual brain split.
2. Cluster with `akka-discovery-kubernetes-api`: 59 deleted `ServiceKey`s since environment restart 4 days ago. No additional `JOINING itself` messages (1 `JOINING itself` right after environment startup). This is lower than before (~50-100 deleted `ServiceKey`s per day) on the same environment, but it might be due to lower nodes restart frequency.

**Comment by patriknw** [comment]
Thanks for testing. It would be valuable if you can share the logs since there still seems to be some remaining problem. I guess I don’t need 4 days of logs but up to a few of the first unexpected deleted keys would be good.

I’m on vacation this week, and will not be able to look into it until next week.

**Comment by patriknw** [comment]
@senia-psm I fixed the scenario that I could reproduce in https://github.com/akka/akka/pull/26421
You mentioned that you still saw some issues. Please try upcoming Akka 2.5.22 (ETA 3rd April) and report back by opening a new issue if you still see something that is not expected. Re-adding because of unexpected removals shouldn't be needed and if that is still a problem we would like to fix that.
