### ISSUE TITLE
Nodes stuck leaving akka cluster and new nodes cannot fully join

### ISSUE THREAD

**Issue by epot** [akka/akka#26290]
We have an Akka cluster of ~1000 nodes with ~10 different roles. Version used: `2.5.17`.
We started to have an issue for the past few days. It started when a dozen nodes try to leave the cluster because they were shut down. We did not notice the issue first, but those nodes never really left the cluster and are stuck in `leaving` state. Now, each node that is restarted has the issue: it never disappears from the cluster, and if we try to restart Akka on the same node, it fails to join, getting some `Received InitJoinAck message from` a seed node but are never up.

If we start Akka on new nodes (with addresses the cluster never saw) then they are weakly up but never up. We also lost Akka cluster singletons on a few role and they never get reassigned even if we spin up new machines.

It really looks likes the cluster leadership is broken somehow, but we can't find any logs giving some insights into this. We would really prefer to restart completely the cluster. An important process run on seed nodes so we are also reluctant to restart them (as we are not sure we are not going to lose the singleton ion this role). It seems the cluster leader runs on another role, so we could try to restart it. 

I tried looking into the opened issues, but it does not seem to be a known issue, not sure if it rings a bell to anyone?

**Comment by patriknw** [comment]
It sounds like there are some nodes that are unreachable but not downed. Look for the log message "Leader can currently not perform its duties", it includes information about unreachable nodes.

**Comment by epot** [comment]
Unfortunately we do not have such log, and we cannot see any unreachable node if we look at the cluster state (only `Leaving`, `Up` or `WeaklyUp`).

**Comment by patriknw** [comment]
Then we need log files to understand what is going on, at least "Cluster Node" log entries at INFO, WARN, ERROR level.

Do you have a way to reproduce it at smaller scale?

Auto-down is a bad idea for other reasons, but you probably know that already.

**Comment by epot** [comment]
So logs do not help, we only get `akka.cluster.GossipEnvelope` going to dead letters on new nodes joining the cluster (as weaklyup).

**Comment by patriknw** [comment]
Sounds strang. Do you have any logs that you can share? I can take a quick look but my time for full production support is limited to Lightbend customers.

**Comment by Captain1653** [comment]
This issue is quite old. There are no updates for 4 years.

Should this issue be closed?

**Comment by johanandren** [comment]
Let's close. Please re-open if any new details or a way to reproduce surfaces.
