### ISSUE TITLE
Compile on Windows 10 OoME

### ISSUE THREAD

**Issue by kastoestoramadus** [akka/akka#26319]
Hi,
I struggle to compile akka on Windows.

https://stackoverflow.com/questions/54400669/sbt-and-command-line-parameters-in-powershell-problem

I got no problems in doing it on Ubuntu.
Could have a look and advice me what is different on Windows?

**Comment by johanandren** [comment]
Did you try assigning the sbt jvm more memory? We lately added a .sbtopts that should give sufficient heap to build out of the box, but maybe something else on that windows machine limits it?

**Comment by johanandren** [comment]
BTW, we try to use the issue tracker for bugs and feature request, and this is more a question for help, so please use the [forums](https://discuss.akka.io) or the [gitter channel](
https://gitter.im/akka/dev) instead for queries like this @kastoestoramadus, thanks!

**Comment by kastoestoramadus** [comment]
Hi,
I'm a Senior Scala Developer and I searched a lot to resolve this problem on Windows.
I've shown my issue to many colleges and none of them is able to solve this.

In this issue tracker I've chosen the category "Question" so I don't get your comment about different tool.if you advice using other communication channels then I suggest to rename or to remove the "Question" category.
After long time on working on Ubuntu I wanted to use Windows but I'm block by so little thing.
FYI: my blog post: https://blog.ww86.eu/os/2019/01/22/wsl-linux-windows-marriage.html

Waldemar Wosiński

**Comment by johanandren** [comment]
I'm not up to speed on GitHub features but I think it may be because it's not currently possible to get rid of that category, which is why we have this text next to the button:

<img width="750" alt="screen shot 2019-02-01 at 11 49 13" src="https://user-images.githubusercontent.com/666915/52118756-7a54ec80-2617-11e9-845f-cc3ed321cd04.png">
