### ISSUE TITLE
Upgrade Paradox and leverage file inclusion to simplify the typed docs

### ISSUE THREAD

**Issue by helena** [akka/akka#26322]
https://developer.lightbend.com/docs/paradox/current/directives/includes.html

**Comment by helena** [comment]
This will help make these cleaner and should probably be done first
* https://github.com/akka/akka/issues/27061
* https://github.com/akka/akka/issues/25624
* https://github.com/akka/akka/issues/26487

**Comment by ennru** [comment]
Those directives are available. Akka-paradox pulls in Paradox 0.5.3
Beware of this one: https://github.com/lightbend/paradox/issues/309

**Comment by helena** [comment]
@ennru So this doesn't need to be done then and I should close the ticket?
