### ISSUE TITLE
Distributed pub sub for typed

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26338]
The receptionist allows something like distributed pub sub by seing the receptionist registration as a subscription to a topic, it does however not do deduplication, when there are multiple "subscribers" on one node a message for that "topic" will go to all of them.

Could it be worth it to introduce an inbetween-topic-actor that does what distributed pub sub does for a single topic (registering to the receptionist when there are any subscribers, forwarding incoming messages to the subscribers).

**Comment by helena** [comment]
I can pick this up when the time comes.

**Comment by chbatey** [comment]
Descoping typed pubsub compared to untyped, what's left:
* Service key describing the topic
* An agent running on each node that handles subscriptions to topics and sending to all the other agents that have subscribed to the topic
* Depends on de-register as agent should de-register when there are no local subscribers for the topic
