### ISSUE TITLE
statefulMapConcat in WithContext APIs is dangerous

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26330]
As it can re-order elements and in general re-combine the context with an arbitrary set of output elements.

Remove or add a warning? The idea with a separate API was to _not_ have the dangerous operators.

https://github.com/johanandren

**Comment by patriknw** [comment]
cc @RayRoestenburg

**Comment by agemooij** [comment]
👍 for removing it

**Comment by patriknw** [comment]
Agreed, @jrudolph will remove it
