### ISSUE TITLE
Take cluster unreachability info into account in routers

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26355]
A nice addition to the routers in Typed would be to subscribe to unreachable events and avoid routing to those, as described in https://akka.io/blog/2017/09/28/typed-cluster

It would be cool if we don't have to have a special type of routers in cluster. Would it make sense to add the facility to subscribe to unreachability via the Receptionist, and then the ClusterReceptionist would hook into cluster events? Should it be part of the ordinary `Listing` subscription or a separate subscription?

The routers probably want to avoid sending to unreachable, but if there are no reachable it's probably best to try to send to an unreachable than not at all.

**Comment by johanandren** [comment]
Maybe it should always provide that information, so you subscribe, and then the `Listing` `unapply` provides only reachable, and you could get the reachable ones with a separate method on the listing message. This would mean that the cluster receptionist may need to send out more listing messages (every time reachability changes) but perhaps that is fine?
