### ISSUE TITLE
Most of Javadoc links are broken as of now.

### ISSUE THREAD

**Issue by vijaybverma** [akka/akka#26377]
Most of the Java API doc links are broken. Scala API doc links are working fine:

https://doc.akka.io/japi/akka/current/index.html?akka/cluster/package-summary.html&_ga=2.160463229.1131255053.1550110945-447729046.1550107126

https://doc.akka.io/japi/akka/current/index.html?akka/cluster/sharding/package-summary.html&_ga=2.68394577.1131255053.1550110945-447729046.1550107126

So on...

Regards,

Vijay.

**Comment by chbatey** [comment]
These are fixed now, thanks for reporting.
