### ISSUE TITLE
Leverage @silent to enable xfatal-warnings 

### ISSUE THREAD

**Issue by helena** [akka/akka#26389]
We can carefully leverage `@silent` on them, **allowing us to enable fatal warnings**. Huge gain.
 
See Eugene's post http://eed3si9n.com/stricter-scala-with-xlint-xfatal-warnings-and-scalafix and https://github.com/akka/alpakka/pull/1486/files from @2m

**Comment by patriknw** [comment]
That's very interesting. Does it mean that we can silence all kind of warnings and don't need the "count known warnings" feature?

**Comment by helena** [comment]
Yes I see it as another option.

**Comment by chbatey** [comment]
Nice, hadn't seen this before. It would be great to work on each module and supress / remove.

**Comment by patriknw** [comment]
I guess we are closing this ticket now, and then actually fixing warnings or silence them is handled elsewhere.
