### ISSUE TITLE
-release 11 flag

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26381]
When releasing there are compilation errors for the CompileJdk9 sources in some environments.

```
[info] Compiling 2 Scala sources and 1 Java source to /Users/patrik/tmp/akka/akka-stream/target/CompileJdk9-classes ...
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] 5 errors found
...
[error] (akka-stream / CompileJdk9 / compileIncremental) Compilation failed
```

This can be reproduced with `sbt akka-streams/publishLocal`.

It works for @chbatey but not for @patriknw and @jrudolph . We haven't understood what is causing it. Tried to remove jdk installations to match what Christopher had but didn't help.

It is solved by changing the `-release` flag to 11 instead of 9. That would probably mean that the JavaFlow classes in akka-stream will require jdk11 and can't be used from jdk9. That is ok.

**Comment by jrudolph** [comment]
See also @SethTisue's explanation here: https://github.com/akka/akka/pull/25675#issuecomment-463394933

And the explanation of what `-release` does in https://github.com/scala/scala/pull/6362.

We should just change to `-release 11` and get over with it.
