### ISSUE TITLE
How to deal with shared memory in Akka？

### ISSUE THREAD

**Issue by guobinhit** [akka/akka#26390]
I'm sorry post a question in here, because I visit https://discuss.lightbend.com/c/akka/ is difficult.

I want to know how to deal with shared memory in Akka？Or, how is Akka's shared memory implemented?

**Comment by patriknw** [comment]
We don't use the issue tracker for questions. What is difficult with the discuss forum?

I think you need to be more specific in your question. What shared memory are you referring to? Artery with the Aeron transport?

**Comment by guobinhit** [comment]
Thank you for your reply! My network is bad, below It's my network condition  shown in Chrome Inspect:

![visitAkka](https://img-blog.csdnimg.cn/20190218100848372.png)

I'm sorry my question is vague.In a other word, has shared memory been used in Akka? If so, how?

**Comment by guobinhit** [comment]
![akka-error](https://img-blog.csdnimg.cn/20190218101847309.png)

**Comment by patriknw** [comment]
Let's continue in Gitter. I don't have a clue of what you are asking about.
