### ISSUE TITLE
fail build when multi-jvm sources don't compile

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26395]
See https://github.com/akka/akka/pull/26394

Compilation error is logged, but doesn't fail the build.

It's something wrong with the usage of `triggeredBy` because it works from `multi-jvm:compile` but not `test:compile`.

**Comment by chbatey** [comment]
https://github.com/sbt/sbt/issues/1187

**Comment by chbatey** [comment]
This is tricky as multi-jvm typically depends on test so if we have test depend on multi jvm we end up in an infinite loop. Perhaps PR validation should run something other than `test:compile`?

**Comment by patriknw** [comment]
PR validation could do `multi-jvm:compile` and that might not be so bad given how many times we have struggled with this and only noticed far later that it doesn't work.
However, it would be good for contributors and ourselves if `test:compile` also compiled and failed as expected.

**Comment by dwijnand** [comment]
I agree.  It would be good to have the tests _defined_ in test scope, but run in MultiJVM scope.  It would be easier for IntelliJ integration too.

**Comment by patriknw** [comment]
I think this was done in https://github.com/akka/akka/pull/26400
added separate `validateCompile`
