### ISSUE TITLE
failed: StreamRefSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26392]
https://jenkins.akka.io:8498/job/akka-nightly/6292/consoleText

```
[info] [JVM-3] - must stop stream with SinkRef after downing and removal (on node 'third', class akka.cluster.StreamRefMultiJvmNode3) *** FAILED *** (10 seconds, 489 milliseconds)
[info] [JVM-3]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for failed-system-42-tmp
[info] [JVM-3]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:402)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:379)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:379)
[info] [JVM-3]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info] [JVM-3]   at akka.cluster.StreamRefSpec.$anonfun$new$27(StreamRefSpec.scala:251)
[info] [JVM-3]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:371)
[info] [JVM-3]   at akka.cluster.StreamRefSpec.$anonfun$new$14(StreamRefSpec.scala:251)
[info] [JVM-3]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-3]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info] [JVM-3]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info] [JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info] [JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info] [JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info] [JVM-3]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1075)
[info] [JVM-3]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info] [JVM-3]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info] [JVM-3]   at akka.cluster.StreamRefSpec.akka$cluster$MultiNodeClusterSpec$$super$withFixture(StreamRefSpec.scala:136)
[info] [JVM-3]   at akka.cluster.MultiNodeClusterSpec.withFixture(MultiNodeClusterSpec.scala:193)
[info] [JVM-3]   at akka.cluster.MultiNodeClusterSpec.withFixture$(MultiNodeClusterSpec.scala:189)
```

**Comment by chbatey** [comment]
I can't see anything wrong here. Running it with some more logging on repeat here: https://jenkins.akka.io:8498/job/akka-multi-node-repeat-3/

**Comment by chbatey** [comment]
I ran this 5k times https://jenkins.akka.io:8498/job/akka-multi-node-repeat-3/ and unable to reproduce

**Comment by patriknw** [comment]
Here it is again: https://jenkins.akka.io:8498/job/akka-nightly/6433/consoleText

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.5-2.13/14

**Comment by johanandren** [comment]
Theory: the test only asserts stream materialization on the sending side, which doesn't prove the partner actor on the receiving side has been found. When the test splits the network that means the sending side will wait for `akka.stream.materializer.subscription-timeout.timeout` which by default is `5s` - the same as the upper limit for the `streamLifecycle3.expectMsg("failed-system-42-tmp")`. Two races in one makes it fail very seldom.

Not quite sure which scenario it makes most sense to test though:
 
 *  we can assert we saw at least one element on the receiving side so we know the partner has been received 
 * increase the expect timeout to make sure it succeeds on subscription timeout as well
 * change the subscription timeout
 * assert explicitly on the failure so we know it is the expected `RemoteStreamRefActorTerminatedException`
