### ISSUE TITLE
SourceWithContext / FlowWithContext withAttributes should be overridden to return concrete type

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#26411]
This was removed accidentally during a refactoring but tests were missing so I didn't notice.

**Comment by skyluc** [comment]
@jrudolph `SourceWithContext` and `FlowWithContext` extend `GraphDeletgate` which defines `withAttributes` as `final`.
So it cannot be overridden without extra change.

Any advice ? My basic idea would be to extend only `Graph`, and to implement the 3 functions of `GraphDelegate`.

**Comment by jrudolph** [comment]
I'd say just remove the `final` modifier and override it in `SourceWithContext` and `FlowWithContext` with a more accurate result type. I guess it can then be removed from `GraphDelegate`. It's probably not useful there.

**Comment by skyluc** [comment]
Oh right. I didn't notice it was used only in the `WithContext` code.
