### ISSUE TITLE
Akka Docs -> Akka Architecture -> Failure Handling Example missing code

### ISSUE THREAD

**Issue by smurfzilla** [akka/akka#26429]
File:
akka/akka-docs/src/test/scala/tutorial_1/ActorHierarchyExperiments.scala
line 68: ``` //#supervise```

should be moved above
line 63:``` object SupervisingActor {```

 I believe.

object does not show up on the docs page to copy and paste to your sample project:\
https://doc.akka.io/docs/akka/current/guide/tutorial_1.html

```
...
//#start-stop

object SupervisingActor {
  def props: Props =
    Props(new SupervisingActor)
}

//#supervise
class SupervisingActor extends Actor {
  val child = context.actorOf(SupervisedActor.props, "supervised-actor")

  override def receive: Receive = {
    case "failChild" ⇒ child ! "fail"
  }
}

object SupervisedActor {
  def props: Props =
    Props(new SupervisedActor)
}

class SupervisedActor extends Actor {
  override def preStart(): Unit = println("supervised actor started")
  override def postStop(): Unit = println("supervised actor stopped")

  override def receive: Receive = {
    case "fail" ⇒
      println("supervised actor fails now")
      throw new Exception("I failed!")
  }
}
//#supervise
```

**Comment by patriknw** [comment]
Thanks for reporting @smurfzilla 
Would you be able to create a pull request fixing the problem?

**Comment by hungaikev** [comment]
I can pick this up. @patriknw

**Comment by smurfzilla** [comment]
> Thanks for reporting @smurfzilla
> Would you be able to create a pull request fixing the problem?

Shoot - just saw this comment - I would have if @hungaikev would not have beaten me to it!
