### ISSUE TITLE
Sharding GracefulShutdownReq DeadLetterSuppression but logged 

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26436]
Seems like GracefulShutdownReq is logged (when it comes from another node) that it goes to dead letters even though it is marked with DeadLetterSuppression. Not sure if this is on purpose.

**Comment by johanandren** [comment]
This is likely because it is sent through actor selection rather than to an actorref.

**Comment by patriknw** [comment]
I think this is solved via the `WrappedMessage`
