### ISSUE TITLE
Align lazy and future stream operators

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26446]
Sparked by https://github.com/akka/akka/pull/26442

Current situation:
```scala
Source.single(T): Source[T, NotUsed]
Source.fromFuture(Future[T]): Source[T, NotUsed]
Source.fromFutureSource(Future[Source[T, M]]): Source[T, Future[M]]
Source.lazily(() => Source[T, M]): Source[T, M]
Source.lazyAsync(() =>T): Source[T, NotUsed]

// missing lazy future source - in progress in #26442
// Source.something(() => Future[Source[T, M]]): Source[T, Future[M]]

// note the difference in matval here
Flow.lazyInitAsync[I, O, M](flowFactory: () ⇒ Future[Flow[I, O, M]]): Flow[I, O, Future[Option[M]]]
// potentially missing just lazily and fromFuture(flow) although those can be achieved through lazyInitAsync

Sink.lazyInitAsync[T, M](sinkFactory: () ⇒ Future[Sink[T, M]]): Sink[T, Future[Option[M]]]
// potentially missing just lazily and fromFuture(flow) although those can be achieved through lazyInitAsync
```

There's a few overlapping issues here:
 * naming is not consistent
 * granularity of the operators are not the same
 * dealing with materialized value is not the same (failing the future vs having a `Future[Option[M]]` and completing that with `None` if a lazy thing was never materialized)

**Comment by johanandren** [comment]
The `lazyInitAsync` signature can be achieved through composition (`Source.lazily(() => Source.fromFutureSource)`), but this is a bit tricky to realize, and it may make sense to have prepackaged factories that does the composition.

I think we should provide those smallest building blocks for `Source`, `Flow` and `Sink` and introduce common naming. Suggestion:

```
// exists
Source.single(T): Source[T, NotUsed]
Source.fromFuture(Future[T]): Source[T, NotUsed]
Source.fromFutureSource(Future[Source[T, M]]): Source[T, Future[M]]
// renamed
Source.lazySource(() => Source[T, M]): Source[T, M]
Source.lazySingle(() =>T): Source[T, NotUsed]
Source.lazyFutureSingle(() => Future[T]): Source[T, NotUsed]
// new
Source.lazyFutureSource(() => Future[Source[T, M]]): Source[T, Future[M]]

// new
Flow.fromFuture(Future[Flow[I, O, M]]): Source[T, Future[M]]
Flow.lazyFlow(() => Flow[I, O, M]): Flow[I, O, M]
// renamed
Flow.lazyFutureFlow(() => Future[Flow[I, O, M]]): Flow[I, O, M]

// new
Sink.fromFuture(Future[Sink[T, M]]): Sink[T, Future[M]]
Sink.lazySink(() => Sink[T, M]): Sink[Future[M]]
// renamed
Sink.lazyFutureSink(() => Future[Sink[T, M]]): Sink[Future[M]]
```

Where the `lazyFutureNnn` is a composition of `fromFuture` and `lazyNnn` for each.

**Comment by 2m** [comment]
Great suggestion. There is one more inconsistency in the proposal: `Source.lazyFutureSingle` should be `Source.lazyFuture` to be consistent with the current `Source.fromFuture`.

**Comment by johanandren** [comment]
Or `fromFuture` should be more consistent as `fromFutureSingle`?

**Comment by 2m** [comment]
Yup. That would also make it consistent, but a bit longer.

Getting rid of `from` might also be a possibility. That would make it more consistent with `Source.single`.

**Comment by swachter** [comment]
Note that may implementation of Source.lazyInitAsync #26442 has the signature: 

```
def lazyInitAsync[T, M](sourceFactory: () ⇒ Future[Source[T, M]]): Source[T, Future[Option[M]]]
```

i.e. it matches Flow.lazyInitAsync and Sink.lazyInitAsync. (BTW, I was involved in their implementation, too).

The lazyInitAsync constructors are the most general ones. All other variants can be implemented based on these.

**Comment by johanandren** [comment]
As I mentioned above, I think returning a `Future[Option[T]]` is less powerful than returning a `Future[T]` since you can easily recover+map `Future[T]` into `Future[Option[T]]` but if you go the other way you have to make up the exception details (which could potentially between cancelation, failure, abrupt termination, or failure to materialize the lazy graph).

**Comment by swachter** [comment]
I do not understand how `Future[T]` can express that a source/sink/flow has not been materialized because there was not need in doing so. The only way I can think of is using `Future.failed(new NoSuchElementExcpeption))` or leaving the future uncompleted. Both alternatives do not seem desirable to me. Having `Future[None]` makes this situation explicit.

**Comment by johanandren** [comment]
It uses a `StreamDetachedException`, look at `Source.fromFutureSource` which existed before `lazyInitAsync` and is probably the reason `lazyInit` that you deprecated followed the same semantics.

**Comment by swachter** [comment]
The ScalaDoc of StreamDetachedException is:

```
/**
 * This exception signals that materialized value is already detached from stream. This usually happens
 * when stream is completed and an ActorSystem is shut down while materialized object is still available.
 */
```

I think this description does capture a situation where something gets not materialized at all.

In addition, I would not use an exception to signal something that is completely fine considering the contract of the functionality. The main point of being lazy is that something happens only "on demand", i.e. sometimes never.

**Comment by johanandren** [comment]
Not getting materialized at all can be for three reasons: downstream cancelled without producing any demand, downstream failed (does not travel upstream yet but there are plans), the materializer was terminated (abrupt termination), so that means that two of the cases where it did not get materialized still are failures.

I'd expect that when you are actually interested in that materialized value, it is when it is completed with a value that you want to use for something, which means that unwrapping the `Option` is just extra boilerplate.

In the general case I agree about signalling something with an exception is sub optimal, but I think in this case it fits fine. We can certainly improve _what_ exceptions are used so that it makes more sense though.

I'm sure we both have made our respective standpoints clear here by now, so let's see what the rest of the team thinks. Ping @akka/akka-team

**Comment by swachter** [comment]
If the materializer or the future that provides the thing to materialize fails then the Future[Option[M]] fails. If Downstream cancels or upstream errors before materialization does events should just be propagated.

**Comment by jphelp32** [comment]
@johanandren It's disappointing that #26600 was not addressed during this refactor. Are there any plans to support a `(first element) => Flow` factory?
I'm still having to use `Flow.lazyInit()` but I know that won't be around forever.
The `prefixAndTail()` workaround didn't work for me at the time that I tried to use that instead.

**Comment by johanandren** [comment]
No, no plans to do that since it can be composed through `prefixAndTail`.

**Comment by SattaiLanfear** [comment]
Just because something can be done a certain way doesn't mean it should be.  I could avoid using `GraphDSL` by using `alsoTo` and `StreamRefs` to manually construct and materialize every split path, that doesn't mean I wouldn't be an idiot and just directly using `Broadcast` etc with `GraphDSL` wouldn't be objectively superior, but it could be composed that way.

The `prefixAndTail` solution is clumsy and confusing to look at even as the person who wrote the code using it; for people not intimately familiar with the workaround being performed (say, reviewers on my team) it's positively arcane, and seems to result in wasted extra processing to perform the needed logic.

The old `lazyInit` was very clear, its interface may have deserved some tweaking but just at a glance at its signature it showed it created a sink/flow (optionally) based on the first item to come along.

I just implemented a prefixAndTail based version and I still look at it and go "wtf is going on here?" every time I pass by that code block.

**Comment by johanandren** [comment]
There's some work in progress on a prefix => flow which additionally allows for keeping matval in #28380 that could be closer to what you wish for.

**Comment by SattaiLanfear** [comment]
Good to know, that does seem more intuitive.
Thanks
