### ISSUE TITLE
Typed PoisonPill is not universal

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26448]
The typed `PoisonPill` currently lives in `akka.actor.typed.internal.PoisonPill` but it is in fact not a general poison pill like the untyped one, and it is only used in the cluster tools hosting user provided behaviors, so therefore does it rather belong in `akka-cluster-typed`?

**Comment by patriknw** [comment]
It's also used in persistence so the common dominator is akka-actor-typed.

**Comment by johanandren** [comment]
Ah, that explains it. I'll add something in the Scaladoc for clarification if you don't mind.
