### ISSUE TITLE
TCP Connection not closed for http server

### ISSUE THREAD

**Issue by JeansHH** [akka/akka#26453]
After a client has disconnected the TCP connection is not closed on the server side until the idle-timeout has been received.If there are so many request that the tcp connection limit is reached the tcp socket of the http server is closed leading to dead http server. Even when the limit is not reached the long living tcp connection are not necessary, aren't they?

Maybe I am mistaken and this behaviour is necessary. In that case please close this issue and if you have the time to enlighten me, I would be very pleases.

I will provide a PL to show the code snippet I am talking about.

Thank you very much

**Comment by raboof** [comment]
Hi @JeansHH - thanks for bringing up this question and illustrating it with a PR. It might also have fit well on https://discuss.akka.io, as it's not necessarily directly a bug/feature request, but fair enough ;).

They way TCP works is that a 'TCP connection' consists of 2 streams: one from the client to the server, and one from the server back to the client. These are basically independent: it is perfectly fine to have a protocol where the server keeps sending data long after the client has closed the stream from client to server. This is called 'half-closed' operation (as you already saw).

Of course many protocols describe that when the client closes its side of the connection, that should trigger the server to also close its side. That is not universal, though.

Can you share anything about the server implementation you were testing against?

There is also a way for the client to 'forcefully' cause the server to close its return connection: by aborting the connection by sending a RST. That is often not what you want, though, as it is really meant for non-orderly closes and allows throwing away any data that might still have been queued.

In the PR, you propose carrying the `halfClose` parameter from `Inbound` over to the `keepOpenOnPeerClosed` of the `Register`. At face value that makes sense: if we don't allow half-closed connections, we shouldn't keep the connection open when the peer closes it. Looking a bit further I'm not completely sure, though: `Inbound.halfClose` comes from the parameter on `Tcp.bind()`, and is documented as: "Controls whether the connection is kept open even after writing has been completed to the accepted TCP connections. If set to true, the connection will implement the TCP half-close mechanism, allowing the client to write to the connection even after the server has finished writing". In other words, it controls whether or not the server is allowed to half-close the connection. Using the same value to determine whether the client is allowed to half-close the connection might be surprising - perhaps we need to allow the user to control those 2 aspects separately? WDYT?

**Comment by JeansHH** [comment]
Ho  @raboof ,
thank you very much for your answer and the good explanation. I will close the issue (well I am not sure whether I can do or if you have to do it). Never the less I would like to solve my problem: Is there any way to start a http server that closes the tcp connection when the peer closes its side?

**Comment by JeansHH** [comment]
When there is no way to do that yo can consider this as a feature request :). The long living tcp connections are a waste of resources and can cause the http server to die if there are more requests within the idle timeout than the amount of allowed simultaneous tcp connections.

**Comment by raboof** [comment]
@JeansHH can you show a bit more of what your server side implementation looks like? Even without a setting to eagerly close at the 'tcp level', it seems like it should be possible to achieve this behavior at your 'protocol level'.

**Comment by JeansHH** [comment]
@raboof you are right. I added a "Connection: close" to the response header if there is no "keep-alive" in the request header. This causes the tcp connection to be closed. But why is this necessary?

**Comment by jrudolph** [comment]
See also https://discuss.lightbend.com/t/tcp-connection-not-closed-for-http-server/3588/3
