### ISSUE TITLE
Documentation structure for Typed docs

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26487]
and relation to untyped docs

**Comment by patriknw** [comment]
Related to #26322 and #24717

**Comment by patriknw** [comment]
also look for pages that are too long and see if they can be broken up to smaller, persistence.md might be a candidate

**Comment by chbatey** [comment]
* Switch typed and untyped around at the top level
* Move typed sections to the appropriate top level e.g. clustering
* Move persistence to the top level and call it event sourcing

* Getting started is really getting started with actors
* Make getting started link to try akka and getting started guides for actors, streams, etc

**Comment by johanandren** [comment]
Useful comment from Tim: https://github.com/akka/akka/pull/27220#issuecomment-507978816

**Comment by patriknw** [comment]
Closing this, and will create more specific tickets (also based on Tim's comments)
