### ISSUE TITLE
Ordering of unstashAll and side effect in typed persistence

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26489]
https://github.com/akka/akka/pull/26347/files/39b7db36064facad21dcce0647e4321c46c2d9f9#diff-032187146a93167944a6a9f14b37eaffR517

```
....thenUnstashAll().thenRun(_ => something)
```

Executes the thenRun part first rather than after unstashing all the commands in the stash.

**Comment by patriknw** [comment]
Hm, I think it would be very complicated to implement that the `thenRun` that is defined after `thenUnstashAll` would be kept around and then finally executed when all unstashing is done. Probably complicated for user to reason about as well, suddenly a callback is executed from an old command although several other commands (that were stashed/unstashed) have been processed inbetween.

Maybe we need something in the types to declare such effect as terminal, i.e. it would not have the `thenRun` method.

Need to discuss/ponder this, and it should not be started before we have merged https://github.com/akka/akka/pull/26520
