### ISSUE TITLE
Don’t document remoting as a separate thing

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26491]
but only to be used with Akka Cluster

Maybe deprecate (log warning) for RemoteActorRefProvider

**Comment by kpritam** [comment]
We are extensively using akka cluster, remoting and CRDT's, our current architecture looks like below:

![cluster](https://user-images.githubusercontent.com/17781757/54118710-b1d66600-4419-11e9-835d-1e195f60cbb1.png)


- As depicted in diagram, every machine has one JVM which takes part in akka cluster which has registry store (CRDT's) which gets replicated in akka cluster.
- Same JVM also exposes HTTP end points for other local JVM's to register themself with cluster.
- Note that only one JVM from single machine takes part in akka cluster and responsible for replication and we do not want every JVM to take part in cluster.
- Other JVM's uses `remoteActorRefProvider` to spawn actors which eventually gets registered with cluster via HTTP end point

As this ticket enforces to use `clusterActorRefProvider` everywhere. We tried changing provider from `remote` to `cluster` and everything seems to be working as expected functionally.

But would like to know from akka team, will there be any implications/unknowns which we will face by doing so in above architecture?
Will this cause any performance hit, gossip overhead, lot of cluster logs etc...?

**Comment by patriknw** [comment]
I'll look into your questions early next week

**Comment by patriknw** [comment]
Answered in https://github.com/akka/akka/issues/26176#issuecomment-473820007
