### ISSUE TITLE
FIXME: WrappingBehavior

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26504]
see if we can completely eliminate this with the help of BehaviorInterceptor instead

**Comment by johanandren** [comment]
Since `InterceptorImpl` is the only impl of that trait we just can let the behavior interpreter know about the interceptor instead.

**Comment by patriknw** [comment]
sounds like a good first approach to simplify it slightly

**Comment by TisonKun** [comment]
Hi @johanandren @patriknw do you mean that we, at first, replace `WrappingBehavior` with directly access of `InterceptorImpl`?

FWIW I give it a try on https://github.com/TisonKun/akka/tree/GH-26504
