### ISSUE TITLE
Javadoc generation fails for jdk8

### ISSUE THREAD

**Issue by raboof** [akka/akka#26502]
On jdk8, javadoc generation fails with `[warn] Unexpected javac output: javadoc: error - invalid flag: --frames.`

This does not fail the sbt command because https://github.com/sbt/zinc/pull/625 won't make it in until sbt 1.3.0.

Perhaps we should explicitly fail the build when `-Dakka.genjavadoc.enabled` is passed on jdk <9, since we aim to release with jdk 9+ anyway?

**Comment by patriknw** [comment]
agreed, we don't have to be able generate javadoc on jdk8
