### ISSUE TITLE
Akka Typed Behavior.orElse appears does not propagate termination signals

### ISSUE THREAD

**Issue by huntc** [akka/akka#26518]
We have some code that receives into its behaviour and uses `orElse` so that another behaviour's signal handler can continue handling signals i.e.:

```
      Behaviors
        .receive[T] {...}
        .orElse(behavior) // handle signals immediately
```

What we're seeing is that the signal handling of `behavior` isn't called. The specific signal in use here is `Terminated`.

The API doc for `orElse` states:

>  Composes this `Behavior with a fallback `Behavior` which is used when this `Behavior` doesn't handle the message or signal...

However, in the case of the `Terminated` signal, this isn't the case. Looking at the code of `Behavior`, I see the following:

```
  def interpretSignal[T](behavior: Behavior[T], ctx: TypedActorContext[T], signal: Signal): Behavior[T] = {
    val result = interpret(behavior, ctx, signal)
    // we need to throw here to allow supervision of deathpact exception
    signal match {
      case Terminated(ref) if result == UnhandledBehavior ⇒ throw DeathPactException(ref)
      case _ ⇒ result
    }
  }
```

This appears to handle the termination signal especially, as the comment states. However, it also appears that the `orElse` behavior doesn't get the opportunity to execute.

Relevant code example: https://github.com/akka/alpakka/pull/1577/files#diff-a2dfb01266e608741b917c05b6a7e07aR26

**Comment by huntc** [comment]
Thanks!

**Comment by huntc** [comment]
Thanks again for fixing this problem.

Is there an idea when we may get another Akka release? We are keen to see the fix for an Alpakka PR. Thanks for your further assistance.

**Comment by patriknw** [comment]
Probably Wednesday next week

**Comment by huntc** [comment]
Thanks.
