### ISSUE TITLE
Adverse impact of quarantine-after-silence exceeding the allowed limit

### ISSUE THREAD

**Issue by h2kids** [akka/akka#26512]
At a production system we observed a node quarantining others after quarantine-after-silence interval is reached (#26426). To overcome this issue we tried to set the quarantine-after-silence to a large enough number (e.g. 800d). This value was initially accepted by configuration but later when a scheduler job is created by ActorSystem this value was rejected.

2019-02-25 10:09:00,632 | ERROR | lt-dispatcher-55 | Remoting                         | 207 - com.typesafe.akka.slf4j - 2.5.19 | Task scheduled with [69120000] seconds delay, which is too far in future, maximum delay is [21474835] seconds
java.lang.IllegalArgumentException: Task scheduled with [69120000] seconds delay, which is too far in future, maximum delay is [21474835] seconds

So what happens here? a job is scheduled with default value (2d/48h) or 21474835s (approx 248d)?

**Comment by patriknw** [comment]
I would expect that the system wouldn't start at all with an invalid config value like that. We'll look into this, and more important investigate and fix #26426.

**Comment by patriknw** [comment]
@h2kids Do you have any more information about how the quarantine-after-silence is triggered, see my questions in https://github.com/akka/akka/issues/26426#issuecomment-473855584
