### ISSUE TITLE
Request message with 2 parameters doesn't compile with ctx.ask (Scala 2.13)

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26514]
The following doesn't compile with Scala 2.13.0-M5 (works with 2.12.8) in ClusterShardingSpec:
```
      Behaviors.setup[TheReply] { ctx =>
	        ctx.ask(aliceRef)(WhoAreYou2(17, _)) {
	          case Success(name) => TheReply(name)
	          case Failure(ex)   => TheReply(ex.getMessage)
	        }
	
	        Behaviors.empty
	      }
```

```
[error] /home/travis/build/akka/akka/akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala:358:42: missing parameter type for expanded function ((x$6: <error>) => WhoAreYou2(17, x$6))
[error]         ctx.ask(aliceRef)(WhoAreYou2(17, _)) {
[error]                                          ^
[error] /home/travis/build/akka/akka/akka-cluster-sharding-typed/src/test/scala/akka/cluster/sharding/typed/scaladsl/ClusterShardingSpec.scala:359:42: type mismatch;
[error]  found   : Any
[error]  required: String
[error]           case Success(name) => TheReply(name)
[error]     
```

**Comment by patriknw** [comment]
@johanandren similar to the other ask issue you investigated?

**Comment by johanandren** [comment]
Yes, similar indeed. That is strange if it does not compile on 2.13 because we have one that is very similar test coverage in https://github.com/akka/akka/blob/master/akka-actor-typed-tests/src/test/scala/akka/actor/typed/scaladsl/ActorContextAskSpec.scala#L88 that seems to compile fine.

**Comment by patriknw** [comment]
but that one doesn't have two parameters?

**Comment by patriknw** [comment]
The signature is here: https://github.com/akka/akka/blob/76492649987baa9838674bc91b1b4bb48d9779db/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala#L290-L291

**Comment by patriknw** [comment]
Note that it works with single parameter:
```
        ctx.ask(aliceRef)(WhoAreYou) {
          case Success(name) => TheReply(name)
          case Failure(ex)   => TheReply(ex.getMessage)
        }
```

```
  final case class WhoAreYou(replyTo: ActorRef[String]) extends TestProtocol
  final case class WhoAreYou2(x: Int, replyTo: ActorRef[String]) extends TestProtocol
```

**Comment by adriaanm** [comment]
Ah hehe, this is also fixed in RC1. https://github.com/scala/scala/pull/7340 was backported tot 2.12.8 between M5 and RC1.

**Comment by patriknw** [comment]
Great, thanks for looking into it.

**Comment by patriknw** [comment]
Leaving this ticket open until we have switched to RC1 and then we should include that example in ClusterShardingSpec
