### ISSUE TITLE
SupervisorStrategy negative maxNrOfRetries  do not work as described

### ISSUE THREAD

**Issue by andrievskya** [akka/akka#26527]
Description says  that negative value of maxNrOfRetries paremeter mean no limit for restart count. 
In reality it just stops failed actor instead of restarting it.

As far s I understand, code at FaultHandling.scala:46  means that for any maxNrOfRetries<1 restart is not permitted, which is not a desired outcome

**Comment by patriknw** [comment]
Have you tried/tested? Default value in `OneForOneStrategy` is `-1` and that is most certainly restarting forever. Here is a test for that https://github.com/akka/akka/blob/48a43e1e74e9be97d85a628d2fde460a982fec6f/akka-actor-tests/src/test/scala/akka/actor/SupervisorSpec.scala#L522

**Comment by andrievskya** [comment]
I've made a little test in java, that shows behaviour in question:

[Main.zip](https://github.com/akka/akka/files/2966031/Main.zip)

It creates a single actor, that spawns a child, who produces an error during message processing. When maxNrOfRetries (line 40) is positive, it restarts chid exactly maxNrOfRetries times, and this is what I expected. When maxNrOfRetries<0, it restarts child only 2 times, while I expected that it will restart as many times as possible as it can during 1000 ms test duration (> 8K times)

**Comment by andrievskya** [comment]
By the way, in your own test  starting at line 539 when a duration is not infinite, but retry count is negative  tested actor restarted only once, and this must be the source of my confusion: I expected, that actor would be restarted infinitely many times.

I suggest to clarify this case in scaladocs, and also add no-args constructors to java api, just for convenience.

**Comment by chbatey** [comment]
I believe the Java API is here: https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/FaultHandling.scala#L590 which allows you to pass in just the Decider without number of retires or duration as there's no need to pass a duration if you want infinite retries. Good to add a note to the scala/java doc. Thanks @andrievskya
