### ISSUE TITLE
Promote ApiMayChange features

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26532]
Look for ApiMayChange that should be promoted in 2.6

**Comment by helena** [comment]
@patriknw what is the criteria for promotion, those marked and related to our 2.6 additions?

**Comment by patriknw** [comment]
We might not promote the following in 2.6:
* `MaterializerState.streamSnapshots` because it hasn't been used much yet
* AffinityPool because it hasn't proven to be better yet

Let's wait with the following until we are closer to RC:
* Typed
* Lease.

Other things can be promoted now, I think.

**Comment by helena** [comment]
Other possibly relevant usages in these, should we promote?
* actor-typed (8)
* persistence-typed (2)
* testkit-typed (2)
* remote.artery (3)
* stream (11)

**Comment by patriknw** [comment]
We will promote the `-typed` for 2.6.0, but my thinking is that we should wait with that until we are closer to the final so that there is no misunderstanding that some 2.6-milestone is fully stable.

**Comment by helena** [comment]
Sorry I forgot the typed, updated:
remote.artery (3)
stream (11)
