### ISSUE TITLE
Make typed test probe a RecipientRef

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26531]
Making the typed TestProbe a `RecipientRef` that forwards to `.ref` gives a tiny little bit less boilerplate in tests, (and also, that has tripped me up a couple of times before I remember to do `probe.ref ! msg` over `probe ! msg`)

**Comment by patriknw** [comment]
nice idea

**Comment by johanandren** [comment]
Wasn't as easy as I imagined because of the `InternalRecipientRef` self-type

**Comment by leviramsey** [comment]
I think I got the `InternalRecipientRef` issue cleared up: https://github.com/leviramsey/akka/pull/1/files

**Comment by patriknw** [comment]
@leviramsey please open a PR at akka/akka and we can discuss the details there. Thanks.
