### ISSUE TITLE
Typed Persistence: Replace SnapshotSelectionCriteria

### ISSUE THREAD

**Issue by helena** [akka/akka#26536]
Initial discussion in: Typed Persistence: Implement deleting snapshots / events #24698

**Comment by patriknw** [comment]
It's only `SnapshotSelectionCriteria` and `SnapshotMetadata` that we expose from untyped persistence in typed user APIs. To make the typed APIs independent of untyped persistence I think we should do this (and it's a low effort).

`SnapshotMetadata` too.

To find this I used:
```
find akka-persistence-typed/src/main/scala/akka/persistence/typed/ -name "*.scala" | xargs grep "akka.persistence" | grep -v "internal/" |  grep -v "akka\.persistence\.typed" | grep -v "SnapshotProtocol" | grep -v "JournalProtocol"
```
