### ISSUE TITLE
Typed Persistence: snapshotEvery vs RetentionCriteria

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26544]
Example:
```
counterWithSnapshotAndRetentionProbe(ctx, pid, snapshotProbe.ref, retentionProbe.ref)
	              .snapshotEvery(2)
	              .withRetention(
	                RetentionCriteria(snapshotEveryNEvents = 2, keepNSnapshots = 2, deleteEventsOnSnapshot = false))))
```

It's this `.snapshotEvery(2)` and `snapshotEveryNEvents = 2` redundancy that we must eliminate. It must always be the same value. We have to discuss which way to go, either the retention need to get it from `snapshotEvery` or the opposite.

One way could be to let the `RetentionCriteria` also define when to save snapshots, i.e. move `snapshotEvery` to the `RetentionCriteria`.

Then we also have the more flexible `snapshotWhen`. Should that still remain as is?

**Comment by helena** [comment]
If we do not want a pluggable size/count/TTL algorithm option then we should remove
```RetentionCriteria(snapshotEveryNEvents``` 
add
```. keepNSnapshots```

However if we do want to, then remove
```.snapshotEvery```

**Comment by helena** [comment]
Starting once https://github.com/akka/akka/pull/26603 is merged, so the samples and doc can be updated.

**Comment by helena** [comment]
It may be better to table the - what about `.snapshotWhen` for https://github.com/akka/akka/issues/26545 so it is clearer what/where is best for it.
