### ISSUE TITLE
Typed Persistence: docs / sample for deleting snapshots and events

### ISSUE THREAD

**Issue by helena** [akka/akka#26543]
Relates to [Issue](#24698) and [PR](https://github.com/akka/akka/pull/26533)

**Comment by helena** [comment]
Untyped persistence docs are slightly broken out and in looking at the typed docs I see a way to logically separate the typed which IMO would be helpful to readers. Currently all usage concepts and lifecycle are in the same huge file. I'd recommend creating a new doc `persistence-lifecycle` which would have
* Recovery
* Replay
* Retention/Deletion (stash?)
And the existing one remain with Effects and Side Effects, Event adaptors, etc.

**Comment by patriknw** [comment]
Sounds good to break up into more pages
