### ISSUE TITLE
Use BenchTestSource in Streams JMH benchmarks

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26563]
`BenchTestSource ` or `BenchTestSourceSameElement`.

The `syncTestPublisher` will introduce async boundary.

**Comment by VladKopanev** [comment]
Hi, I would like to help with this issue. Please clarify a few things for me e.g. in which tests you want this source to be used? I only see we can use it in `FlatMapMergeBenchmark` of `akka.stream` package of `akka-bench-jmh` module, there are couple more usages across this package, but I don't see more places where we can use it.

**Comment by patriknw** [comment]
@VladKopanev Thanks for helping. It's right, that is the package.

For example:

* FlowMapBenchmark, instead of the syncTestPublisher
* FlatMapMergeBenchmark, instead of repeat (will be interesting to see if it's faster, maybe not?)
* FlatMapConcatBenchmark is already using it
* FramingBenchmark instead of repeat
* SourceRefBenchmark instead of that Publisher

Another thing that such sources/streams should avoid is to use `Int` elements since those will be boxed (creating many allocations). Instead java.lang.Integer should be used, which is what BenchTestSource does.
