### ISSUE TITLE
Outlet routing component for GraphDSL

### ISSUE THREAD

**Issue by derolf** [akka/akka#26573]
I'd like to propose a component for GraphDSL with the following semantics.

We define a routable packet that contains a payload and a target outlet number.

`case class RouteTo1[A](payload: A)`
`case class RouteTo2[B](payload: B)`
`...`

Now, we would like to have a `Switch[A, B]` with:
`in` : consumes message of type `RouteTo1[A]` and `RouteTo2[B]`
`out1` : emits the `payload` of `RouteTo1[A]` packages
`out2` : emits the `payload` of `RouteTo2[B]` packages
`...`

**Comment by johanandren** [comment]
I think this is relatively easy to compose using the existing `switch` and a element super type with a `outletNumber` getter and then a map downstream to extract the payload. I don't think it is something that should be a part of core Akka Streams.

**Comment by Captain1653** [comment]
This issue is quite old. There are no comment for 4 years.

Should this issue be closed?
