### ISSUE TITLE
MergePrioritized should select the nearest priority.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26591]
I think this is a bug.
![image](https://user-images.githubusercontent.com/501740/54752283-75c0b380-4c18-11e9-8eed-2987c6aea01a.png)

the priorities should be sorted.

**Comment by johanandren** [comment]
No, because `priorities` contain one priority per input, indexed with the index of the input, if we'd resort that it would change the priorities per input.

**Comment by hepin1989** [comment]
randomGen.nextInt(tp) should be `randomGen.nextInt(tp + 1)`
