### ISSUE TITLE
Akka streams: missing overloads for lazyInitAsync where factory takes first stream element

### ISSUE THREAD

**Issue by ilyazolotarov** [akka/akka#26600]
I was very surprised when I did not find these overloads. Of course, this behavior remains in lazyInit but they are marked as obsolete and it makes me feel not very confident using them. The documentation recommends using lazyInitAsync because they supposedly return a better materialized value, but the ability to dynamically initialize a stage based on the first element in the stream is a very good feature which now is gone. Is this by design? If so, then it may be worthwhile to add a workaround to the documentation for those who used the first element in lazyInit, and now want to migrate to not obsolete lazyInitAsync.

**Comment by johanandren** [comment]
I agree this is unfortunate. There's a somewhat related discussion in slow progress in #26446 

I don't think this particular aspect is covered though. And I can also not think of a way to achieve `Sink(firstElement => ActualSinkForRest)` with composition today.

**Comment by johanandren** [comment]
Actually, I just thought of a way to compose:

```
  Source(1 to 100)
    .prefixAndTail(1)
    .runForeach {
      case (Seq(head), tail) =>
        println(s"Based on $head")
        tail.runWith(Sink.foreach(println))
    }
```

**Comment by seblm** [comment]
This example works well even if you only have `Flow`. For instance my code is using a `Flow.groupBy` to have substreams. Thank you so much for this `prefixAndTail()` trick 👍

**Comment by johanandren** [comment]
Closing this since it can be achieved through composition.
