### ISSUE TITLE
Make paradox signature inclusion throw instead of produce invalid output

### ISSUE THREAD

**Issue by raboof** [akka/akka#26659]
When our paradox signature generator fail, it sometimes inserts a 'Broken signature inclusion' message into the docs (e.g. https://doc.akka.io/docs/akka/snapshot/stream/operators/Flow/fromSinkAndSourceCoupled.html)

We should see if we can make the directive throw (and fix the errors).

**Comment by johanandren** [comment]
Wasn't this done as part of #26669 @raboof ?

**Comment by raboof** [comment]
Yes it was!
