### ISSUE TITLE
Consider sbt-dynver

### ISSUE THREAD

**Issue by raboof** [akka/akka#26675]
Using sbt-dynver may remove the need for some custom code, including `stampVersion` and the `find-replace` that happens as part of a release.

I think we considered sbt-dynver before but don't remember why we didn't introduce it at the time.

**Comment by 2m** [comment]
The main reason is because when a new version of Akka is released, we branch off from the master and create a new commit (with all of the version strings replaced) and git tag that.

So until we use sbt-dynver for the first release, it will not find an existing tag in history and will not be able to derive a meaningful version from git history.

Here is the output of `git describe` on the current master:

```
akka ─╼ git describe                                                                        
v1.1-M1-20193-gf798481de5
```

**Comment by raboof** [comment]
looking at a70667481fddd1ae7311d1458b9fb6508790984c, the new commit that replaces versions only replaces versions it in 2 places that don't seem very essential - so perhaps we should remove this step? Then after the first release without this step consider sbt-dynver again?

**Comment by 2m** [comment]
Yes, and the second place is the one that will be handled by sbt-dynver. Only that test-case will need to be updated to handle the new version format that is derived by sbt-dynver.

**Comment by dwijnand** [comment]
You can use sbt-buildinfo to pipe that version from the build to the test.

:automate_all_the_things:

**Comment by raboof** [comment]
(sbt-dynver is now used on master, but can still be overridden by the custom property `-Dakka.build.version`.

Let's keep this issue open to remove our reliance on `-Dakka.build.version` and then finally remove it. It is currently used:

* [ ] nightly builds published for play (perhaps also lagom and cinnamon?)

**Comment by dwijnand** [comment]
I don't have time right now, but there was once an issue with snapshot releases publishing different timestamps for different target scala versions, so watch out not to regress there.

**Comment by raboof** [comment]
Yes - now we would be publishing under the sbt-dynver-generated version number, so that should be stable (not including a timestamp) again.

**Comment by renatocaval** [comment]
This is already in place. Any reason for this issue to be open? Are we missing anything?

**Comment by renatocaval** [comment]
oh, should have read it a bit.

> Let's keep this issue open to remove our reliance on -Dakka.build.version and then finally remove it. It is currently used

Well, as far I can tell, this is also solved, no?

**Comment by raboof** [comment]
You are completely right
