### ISSUE TITLE
DistributedPubSub send will ask first to replicate registry actor in cluster

### ISSUE THREAD

**Issue by vksaran843** [akka/akka#26688]
I observerd one problem in DistributedPubSub peer to peer send message.

I am explaining my scenario.

I created one actor(A1) on Node1 and register to local mediator. within milliseconds I am sending message to A1 from Node2. but local mediator of Node1 didn't replicate registry actors in cluster. so local mediator of Node2 doesn't find actor A1. 

so there is some my questions:- 

How much time take to replicate registry actors in cluster ??

Can there is any way to sync registry actors before sending message to Actor A1 ??

is there any mechanism to retry after sometime if no matching actor found ??

Thanks Akka Team.

**Comment by johanandren** [comment]
Hi @vksaran843, we try to use the issue tracker only for issues and feature-tracking, please use the [forums](https://discuss.akka.io) or the [gitter channel](https://gitter.im/akka/akka) for questions like this, thanks!
