### ISSUE TITLE
Unused halfClose parameter in Javadsl bindTls

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26689]
The Javadsl Tcp.bindTls has a halfClose parameter that is not passed on anywhere, the corresponding Scaladsl does not accept such a parameter but always provide `true` for the internal halfClose value. 

Not quite sure if halfClose can be used server side with TLS or if it is just an oversight. We need to investigate and decide.

**Comment by patriknw** [comment]
Parameter not included in new API in https://github.com/akka/akka/pull/27766
Closing this until there is a reason to investigate.
