### ISSUE TITLE
Signature inclusion broker in the `current` docs

### ISSUE THREAD

**Issue by 2m** [akka/akka#26698]
For example here: https://doc.akka.io/docs/akka/current/stream/operators/Source/combine.html#combine

![image](https://user-images.githubusercontent.com/422086/55714028-6942a600-59e1-11e9-8e65-c3e62b59a8a4.png)

//cc @raboof

**Comment by 2m** [comment]
The [issue itself](https://github.com/akka/akka/issues/26659) was fixed, but the `current` docs need a redeployment.

**Comment by raboof** [comment]
Updated the 2.5.22 docs with cc1138523e
