### ISSUE TITLE
Reduce default akka.cluster.sharding.waiting-for-state-timeout

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26710]
Try with rolling update, especially with small cluster, when coordinator node (oldest) is restarted. Shouldn't be any problems retrying more quickly and often.

**Comment by chbatey** [comment]
This is used in two places. For remembered entities getting the DDataShard to get which entities it is responsible for, and more commonly for the ShardCoordinator to get the state for shard allocation.

For RE shards the shard is stopped and restarted with backoff by the ShardRegion, seems okay.

For the ShardCoordinator we keep retrying, do we want this to be permanently lower or start off low, say 250ms and exponentially increase to 5s?

**Comment by helena** [comment]
> For the ShardCoordinator we keep retrying, do we want this to be permanently lower or start off low, say 250ms and exponentially increase to 5s?

I like the idea of exponential if the algorithm will factor in the cluster size or be sensitive to actual conditions.

**Comment by chbatey** [comment]
I spent some time re-creating the issue of a small cluster having nodes constantly restarting i.e. when a rolling re-deploy happened. It quite frequently took 2-3 retries. I think setting this to 2s is sufficient, I don't think it is worth adding any more complexity as this is only on start up of the shard coordinator. WDYT?

**Comment by helena** [comment]
2s, 2-3 retries, small cluster, no exponential increase? OK for not small cluster as well?

**Comment by chbatey** [comment]
For large clusters it doesn't need to talk to every node so is unlikely to timeout

**Comment by chbatey** [comment]
And it'll retry indefinitely, there's no need to stop unless the node stops being the oldest

**Comment by helena** [comment]
Sounds good

**Comment by chbatey** [comment]
> Sounds good, the retry indefinitely though doesn't though.

Why?

**Comment by helena** [comment]
`Indefinitely` can be a long time, I was assuming network activity related to it and some amount of resource usage.
