### ISSUE TITLE
Should be make Behavior.same/empty/etc. private?

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#26730]
Currently there are a lot of redundant definitions of behavior factories in Behaviors and Behavior. This is confusing and not necessary. As fas as I understand, Behaviors is meant to be the public facing API here.

**Comment by patriknw** [comment]
I agree that this option doesn't add any value and would be better to only have scaladsl/javadsl for those. The thinking might have been that `Behavior` is the language agnostic type that a library can use to define a behavior that can be used from both Java and Scala, but the implementation of such can still use scaladsl/javadsl.Behaviors.same etc without that leaking to the public.

API change for 2.6.
