### ISSUE TITLE
ActorContext.watchWith should (also) take a function from terminated ActorRef to custom message

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#26744]
Typed watchWith drops the ActorRef of the terminated actor, but it might be interesting to know this and pass it to the custom message. We could either provide an overload of watchWith or change the API.

**Comment by patriknw** [comment]
but that ref is known when you initialize the watchWith so you can add it to the custom message

**Comment by hseeberger** [comment]
Agreed. A student of an Akka training course was suggesting this and I did not think enough before raising this. Sorry for the noise.

**Comment by patriknw** [comment]
no problem
