### ISSUE TITLE
Create release-2.5 branch

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26755]
For the record and future simple lookup, make a note of the commit and date when the branch was created in this ticket.

The backporting strategy:

  - master continues as dev branch for 2.6
  - `release-2.5` branch for backporting
  - For issues that should be backported
    - Mark issue with 2.5.23 (next upcoming) milestone
    - PR to master, mark with 2.6.0-M1 (next upcoming) milestone
    - PR to release-2.5 with the backport (typically cherry-pick) when master PR has been reviewed. Backport should be done immediately.
    - Don’t close issue until both PR and backport merged

Next step on master 

- cleanup build
  - MiMa for 2.5, but not 2.4
  - remove support for Scala 2.11

**Comment by chbatey** [comment]
And create a jenkins job to build the new branch?

**Comment by patriknw** [comment]
`release-2.5` branch was created from f9c3c3622c 2019-04-18 (between 2.5.22 and 2.5.23)

**Comment by SethTisue** [comment]
using it in Scala community build: scala/community-builds@9461ce462863fd031a7657e4d033c8e6d38c46c5
