### ISSUE TITLE
Release for 2.13.0

### ISSUE THREAD

**Issue by raboof** [akka/akka#26764]
* [ ] update master to release with it
* [ ] manually release the latest 2.5 version with it
* [ ] update `project/MiMa.scala` to check binary compatibility of 2.13 artifacts against 2.5 as well

Depends on:
* [x] https://github.com/lightbend/ssl-config/pull/178
* [x] https://github.com/etorreborre/specs2/issues/745
* [x] https://github.com/scalatest/scalatest/issues/1601

**Comment by SethTisue** [comment]
specs2 and scalatest have both published

**Comment by raboof** [comment]
2.5.23 for Scala 2.13.0 is on its way to Maven Central now

**Comment by SethTisue** [comment]
should this remain open? will the work be merged onto the release-2.5 branch?

**Comment by raboof** [comment]
Perhaps we should leave it open until we have merged #27109, after which all 2.5 and 2.6 will include 2.13 artifacts without further ado

**Comment by SethTisue** [comment]
makes sense to me. I'm subscribed there now

**Comment by chbatey** [comment]
Unless I am mistaken this is all done now
