### ISSUE TITLE
Did we overlook Akka-discovery internal serializable messages

### ISSUE THREAD

**Issue by helena** [akka/akka#26788]
It seems like we did? If yes, let's fix that. For example ServiceDiscovery.Resolved.

**Comment by chbatey** [comment]
They don't need to be serialized as they are only used locally, but we should add the no verification marker, i'll do that now

**Comment by helena** [comment]
That is what I thought, but was confused why a user would see the Ser exception raised. Thanks.

**Comment by helena** [comment]
Moving forward, per @patriknw's comment elsewhere let's add the marker to solve the issue right now. For future tracking: https://github.com/akka/akka/issues/26802
