### ISSUE TITLE
Wrong link in doc, directs to old URL

### ISSUE THREAD

**Issue by helena** [akka/akka#26823]
If you are a few lines above here https://doc.akka.io/docs/akka/current/cluster-routing.html#router-with-pool-of-remote-deployed-routees 

In section:
> The easiest way to run Router Example with Group of Routees example yourself is to download the ready to run Akka Cluster Sample with Scala together with the tutorial. It contains instructions on how to run the Router Example with Group of Routees sample. The source code of this sample can be found in the Akka Samples Repository.

The link at `Akka Samples Repository` directs to https://developer.lightbend.com/start/?group=akka&project=akka-sample-cluster-scala with a page that shows:

> This example cannot be found.
> 
> Please use the button to the right to view all of the available examples.

But I think what was desired to link to is
* https://github.com/akka/akka-samples/tree/2.5/akka-sample-cluster-scala
* https://github.com/akka/akka-samples/tree/2.5/akka-sample-cluster-java

**Comment by raboof** [comment]
I think it was intended to link to
https://developer.lightbend.com/start/?group=akka&project=akka-samples-cluster-java

**Comment by helena** [comment]
@raboof thanks
