### ISSUE TITLE
Source/FlowWithContext lack `mapMaterializedValue`

### ISSUE THREAD

**Issue by ennru** [akka/akka#26836]
The `SourceWithContext` and `FlowWithContext` APIs do not contain `mapMaterializedValue`. That operator is required in many situations and does not interfere with the "with context" concept.

**Comment by tayvs** [comment]
Hi. Just need add mapMaterializedValue as in ordinary Source/Flow and all? Sound not hard. Can I try?

**Comment by johanandren** [comment]
Please go ahead, thanks!
