### ISSUE TITLE
Cluster client and typed receptionist cannot co-exist

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26848]
Both starts an actor at `/system/receptionist`, so if typed-cluster is on the class path it will always fail starting its receptionist by default.

Can be worked around by setting `akka.cluster.client.receptionist.name` to some other name than `receptionist`

**Comment by patriknw** [comment]
ouch, rename Cluster Client name to `clientReceptionist`?

**Comment by patriknw** [comment]
> rename Cluster Client name to clientReceptionist?

no, that will not work because contact points is defined by users and contains the name

**Comment by johanandren** [comment]
Yeah, maybe safer to rename the typed receptionist instead.

**Comment by patriknw** [comment]
yes, I think we have to do that
