### ISSUE TITLE
Whether to stop children on parent's restart should not be a concern of parent's supervisor

### ISSUE THREAD

**Issue by TomasMikula** [akka/akka#26846]
Currently, whether to stop children when parent is being restarted is done from parent's supervisor:

```scala
Behaviors.supervise(Parent.behavior)
  .onFailure(SupervisorStrategy.restart.withStopChildren(false))
```

However, the supervisor cannot make this decision without knowing `Parent`'s internals. Consequently, `Behavior` is not a good unit of encapsulation.

The decision whether to stop children should be done by `Parent` itself.

I would imagine a method like

```scala
val child = ctx.spawnResilient(Child.behavior, "child")
```

which spawns a child that will not be stopped on parent's restart. On subsequent invocations (after restart), it will not spawn a new child, but looks it up among surviving children.

Also note that such a method would make the decision per-child, not globally for all children.

**Comment by johanandren** [comment]
I disagree that it belongs somewhere else.

Supervision in general is not safe without knowing the behavior/actor internals: is it safe to resume on failure or will the state be in an inconsistent state, does the state need to be re-initialized - children is just a different kind of internal state that the actor owns/manages. In addition to this if the strategy is `stop`, which is the default, the children cannot survive - implicitly decided by the parent supervision.
