### ISSUE TITLE
GetCurrentRegions can't be sent to proxy shard region

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26853]
A proxy tries to forward it instead of reply to it with the known shard regions (and it does not have a serializer). I think the proxy should respond immediately with what it knows.

**Comment by patriknw** [comment]
I think it's correct. Why would proxy work differently than a normal region? Serialization was missing though, and I have added it in https://github.com/akka/akka/pull/27306

**Comment by johanandren** [comment]
I think this was backported in #27331
