### ISSUE TITLE
TimeoutException while creating stage actor under certain circumstances

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#26850]
The recent fix of the startup race between `ActorMaterializer` and `GraphStage` materialization in #26720 can lead to a (temporary) deadlock and `TimeoutException` afterwards when thread pools are small or already starved.

For simple cases, and default configuration it will only rarely happen and will probably be prevented by idle pool threads and FJP creating spare threads when Await is used (and in 2.6 probably by the internal thread pool). However, shouldn't we follow our own mantra and don't block on principle and not depend on circumstances to prevent crashes / deadlocks?

It seems the ultimate original problem is that the `StreamSupervisors` are created as children of the system guardian which are created with `async = true` leading to the `RepointableActorRefs` we see here. Could we somehow create a new top-level actor above the stream supervisors that can be already be instantiated during `ActorSystem` startup. So, that the `StreamSupervisors` would be normal children created with `async = false` leading to normal `LocalActorRefs`, so that we could remove all the code dealing with the race condition?

<details>
<summary>Reproducer</summary>

```scala
package akka.stream

import akka.actor.ActorRef
import akka.stream.scaladsl.Keep
import akka.stream.scaladsl.Sink
import akka.stream.scaladsl.Source
import akka.stream.testkit.StreamSpec
import org.reactivestreams.Publisher

import scala.concurrent.Await
import scala.concurrent.Future
import scala.concurrent.duration._

class PotentialStreamDeadlock extends StreamSpec(
  """
     akka.actor.creation-timeout = 3s
     akka.actor.default-dispatcher.executor = "thread-pool-executor"
     akka.actor.default-dispatcher.thread-pool-executor.fixed-pool-size = 1
     akka.stream.materializer.dispatcher = "akka.actor.default-dispatcher"
     akka.actor.default-mailbox.mailbox-type = "akka.dispatch.UnboundedMailbox"
  """
){
  "be possible to run immediately, reproducer of #26714" in {
    val res =
    Future {
      val mat = ActorMaterializer()
      val source: Source[String, ActorRef] = Source.actorRef[String](10000, OverflowStrategy.fail)
      val (_: ActorRef, _: Publisher[String]) =
        source.toMat(Sink.asPublisher(false))(Keep.both).run()(mat)
      mat.shutdown()
    }(system.dispatcher)
    Await.result(res, 10.seconds)
  }
}
```

fails with

```
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3000 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:108)
[info]   at scala.concurrent.Await$.result(package.scala:146)
[info]   at akka.stream.stage.GraphStageLogic$StageActor.<init>(GraphStage.scala:245)
[info]   at akka.stream.stage.GraphStageLogic.getEagerStageActor(GraphStage.scala:1242)
[info]   at akka.stream.impl.ActorRefSource$$anon$1.<init>(ActorRefSource.scala:54)
[info]   at akka.stream.impl.ActorRefSource.createLogicAndMaterializedValue(ActorRefSource.scala:39)
[info]   at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:674)
[info]   at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:491)
[info]   at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:450)
[info]   at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:443)
[info]   at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:620)
[info]   at akka.stream.PotentialStreamDeadlock.$anonfun$new$2(PotentialStreamDeadlock.scala:33)
```
</details>

**Comment by patriknw** [comment]
The thinking was that one shouldn't create many materializers and it can only happen if you quickly run a stream after creating the materializer. We have more such initialization assumptions requiring more than one thread.

It would also be mitigated by having one global materializer that can be initialized on ActorSystem startup. Related to https://github.com/akka/akka/issues/25559

Sharing a pre-created top-level actor is also an interesting thought.

**Comment by jrudolph** [comment]
See also https://github.com/akka/akka/issues/26857
