### ISSUE TITLE
MiMa didn't detect API change of StreamRefs

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26852]
Why https://github.com/akka/akka/pull/26847/files#diff-4f5a9552394f69771dfd695c5297c1a9R66 ?

**Comment by raboof** [comment]
Is that an instance of https://github.com/lightbend/migration-manager/issues/40?

**Comment by patriknw** [comment]
ah, good catch, that explains it

**Comment by raboof** [comment]
PR'ed https://github.com/lightbend/migration-manager/pull/299/files
