### ISSUE TITLE
Consider also offering a simplification of the general API, cleaner and for those not familiar with actor `Props`

### ISSUE THREAD

**Issue by helena** [akka/akka#26869]
I had a snippet of code for a talk and it occurred to me that we might consider also offering a simplification of the general api for those not familiar with actor `Props` to just be a regular constructor, via apply, and it's cleaner

Current - just using singleton as an example
```scala
system.actorOf(
  ClusterSingletonManager.props(
    singletonProps = CounterActor.props(),
    terminationMessage = PoisonPill,
    settings = ClusterSingletonManagerSettings(system)
  ), “counter-singleton-manager“)
```

Proposed sample: e.g. if default termination and settings
```scala
ClusterSingletonManager(system, singletonProps, “counter-singleton-manager“)
ClusterSingletonManager(system, singletonProps, “counter-singleton-manager“, terminationMessage = TerminateFu) 
``` 
Current
```scala
val proxy = system.actorOf(
  ClusterSingletonProxy.props(
    singletonManagerPath = ”/user/counter-singleton-manager“,
    settings = ClusterSingletonProxySettings(node)
  ), “counter-singleton-proxy")
```

Proposed sample
```scala
val proxy = ClusterSingletonProxy(system, singletonManagerPath, “counter-singleton-proxy")
```

**Comment by patriknw** [comment]
In Typed we have simplified the API so if we would change we would backport that to untyped, but that is not in line with our strategy. Suggesting to close without action, keeping untyped as it is, and refer to Typed if you want something nicer.

**Comment by helena** [comment]
Forgot about that ;) thanks.
