### ISSUE TITLE
Behavior.narrow is not always safe

### ISSUE THREAD

**Issue by fabianishere** [akka/akka#26867]
Hi, 

I have found that `Behavior.narrow()` (in conjunction with `Behavior.orElse`) can be used to construct type-unsafe behavior that causes a `ClassCastException` during runtime. See the example below:

```java
import akka.actor.typed.ActorSystem;
import akka.actor.typed.Behavior;
import akka.actor.typed.javadsl.Behaviors;

public class Main {
    public static void main(String[] args) {
        final Behavior<Object> a = Behaviors.setup(ctx -> {
            ctx.getSelf().tell(1);
            return Behaviors.empty();
        });

        final Behavior<String> b = Behaviors.receiveMessage(msg -> {
           System.out.println(msg.toLowerCase());
           return Behaviors.same();
        });

        final Behavior<String> behavior = a.<String>narrow().orElse(b);
        final ActorSystem<String> system = ActorSystem.create(behavior, "hello");
    }
}
```
Resulting in:
```
[ERROR] [05/04/2019 15:13:33.103] [hello-akka.actor.default-dispatcher-4] [akka.actor.LocalActorRefProvider(akka://hello)] guardian failed, shutting down system
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
```

This is in contrast with the documentation of `Behavior.narrow()`, which states that it is always a safe operation. Perhaps it might be an idea to document this corner case?

**Comment by johanandren** [comment]
Yes, sounds good to document, we've seen this when combining narrow with the interceptor as well.

**Comment by jrudolph** [comment]
I guess you could alternatively say that sending to self can lead to issues in combination with composition. And that is not only with regard to the types but also with regard to the behavior because a behavior used as argument in `orElse` might not receive all messages sent to `self`.

I wonder if we really want to treat this as a feature or if using or sending out `self` rather breaks encapsulation of Behaviors (especially of functional style behaviors).

What could be the alternatives?

**Comment by patriknw** [comment]
Maybe we should remove `narrow`?
Above example could be handled with `widen`.

```
      val b1 = Behaviors.setup[Any] { ctx =>
        ctx.self ! 1
        Behaviors.empty
      }

      val b2 = Behaviors.receiveMessage[String] { msg =>
        println(s"# received $msg")
        Behaviors.same
      }

      val b3 = b1.orElse(b2.widen { case s: String => s})
      val ref = spawn(b3)
      ref ! "ok"
```

In cases you really need it (and know what you are doing), and can't pay the overhead of widen, there is always `unsafeCast` instead of `narrow`.

**Comment by patriknw** [comment]
Here is another somewhat related example where it breaks down with `widen` (and not using narrow nor orElse).

```
      val behavior = Behaviors.receive[String] { (ctx, msg) =>
        println(s"Received $msg")

        if (msg == "test") {
          ctx.self ! "works"
        }

        Behaviors.same
      }.widen[Option[String]] {
        case Some(x) => x
      }

      val ref = spawn(behavior)
      ref ! Some("test")
```

Can't that be solved by adding a ClassTag to widen and ignore messages that are not of the given type (same as they didn't match in the PF)? Didn't we have a ClassTag there at some point?

**Comment by johanandren** [comment]
I think that'd require having a classtag for any interceptor, since at any point in that behavior stack you could introduce an interceptor. For Java that means passing a Class to timers, supervision, intercept, monitor etc. not very nice.

**Comment by jrudolph** [comment]
> Can't that be solved by adding a ClassTag to widen and ignore messages that are not of the given type (same as they didn't match in the PF)? Didn't we have a ClassTag there at some point?

That doesn't solve the problem that it is still allowed to use `ctx.self ! "works"` even if it doesn't work. Supporting narrow/widen and at the same time allowing to send to self seems fundamentally wrong to me.

**Comment by jrudolph** [comment]
Maybe one problem of `widen` is that it doesn't even do what it says? Shouldn't the type given be a subtype of what it was before?

**Comment by johanandren** [comment]
I think it is still problematic with a class tag on widen because:

```
val behavior = Behaviors.receive[String] { (ctx, msg) =>
  println(s"Received $msg")

  if (msg == "test") ctx.self ! "boom"
  Behaviors.same
}.widen[Option[String]] { // could deal with getting String by ignoring/just passing messages based  a classtag
   case Some(x) => x
}.supervise // wouldn't know about being able to accept String from self
```

**Comment by jrudolph** [comment]
So in 

```scala
      val behavior = Behaviors.receive[String] { (ctx, msg) =>
        println(s"Received $msg")

        if (msg == "test") {
          ctx.self ! "works"
        }

        Behaviors.same
      }
```

wouldn't you expect that `"works"` is received here as a message regardless of the later `widen`?

Maybe I don't have good intuitions about what to expect. Even if we changed widen to ignore messages of the wrong type (and give it a new name) how would you explain the behavior? The type of `ctx.self` would still be wrong if doesn't represent the same type as the final one of the actor.

**Comment by jrudolph** [comment]
> `}.supervise // wouldn't know about being able to accept String from self`

Why would supervise need to know?

**Comment by fabianishere** [comment]
Just to throw some ideas in the wild: what if you also require `BehaviorInterceptor` to have a function for mapping messages sent to `self` to the proper (widened/narrowed) type.

Alternatively, although a bit invasive, `self` could also be removed from `ActorContext`, with it only being supplied at the top-level in the `ActorContext.spawn` call:

```scala
ctx.spawn((self) => Behaviors.receive[String] { (ctx, msg) =>
    ...
    Behaviors.same
}, "test")
```

**Comment by johanandren** [comment]
@jrudolph specifically supervise was a bad sample, but anything that is implemented as an interceptor and that looks at the message somehow, will not expect the type of message.

**Comment by patriknw** [comment]
I will think more about this (next week). We should take a step back and think about the use cases for `widen`, `narrow`, and `orElse`.

As pointed out by others, In its current shape the name `widen` is misleading. Transform or similar would be better for such O => I conversion.

**Comment by dwijnand** [comment]
> As pointed out by others, In its current shape the name `widen` is misleading. Transform or similar would be better for such O => I conversion.

Even the example doesn't make sense as "widen": https://github.com/akka/akka/blob/759673569a503fda416e3563627fcc306d9babea/akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala#L128-L135

But, yes, Behavior isn't contravariant (and therefore its `narrow` isn't safe) if you can also send to self - that's invariant.

**Comment by patriknw** [comment]
Conclusion is that we remove `Behavior.orElse`.

Still keep `Behavior.narrow` to support hiding an internal message type as in the example in https://github.com/akka/akka/issues/25887

Another example of that with ChatRoom:
```scala
  object ChatRoom {
    private sealed trait RoomCommand
    sealed trait PublicRoomCommand extends RoomCommand

    final case class GetSession(screenName: String, replyTo: ActorRef[SessionEvent]) extends PublicRoomCommand
    private final case class PublishSessionMessage(screenName: String, message: String) extends RoomCommand

    def apply(): Behavior[PublicRoomCommand] =
      chatRoom(List.empty).narrow

    private def chatRoom(sessions: List[ActorRef[SessionCommand]]): Behavior[RoomCommand] =
      Behaviors.receive[RoomCommand] { (context, message) =>

...
```

Explore other alternatives of composing behaviors for reuse, e.g. using the SpawnProtocol together with some application specific messages.
