### ISSUE TITLE
Make Artery failure logging less verbose

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26865]
repeated logging of "Restarting graph due to failure", e.g. Connection refused

**Comment by patriknw** [comment]
I think this was what you also mentioned @eloots

**Comment by eloots** [comment]
Indeed. It is very visible in combination with Akka Cluster: if a cluster is running with one or more of the seed need being unreachable, a LOT of logging is generated. Do I add a sample to illustrate?

**Comment by patriknw** [comment]
Not needed, easy to reproduce.
