### ISSUE TITLE
Filter for Java optional

### ISSUE THREAD

**Issue by gabriel-ntuc** [akka/akka#26876]
A common use case that I have found requires some boilerplate right now is "unwrapping" Java optionals. There doesn't seem to be a concise way to both filter out and unwrap Java optionals.

Assuming that we have some arbitrary source of optional elements such as:
```java
Source<Optional<Integer>, NotUsed> numbers = Source.range(1, 10)
  .map(x -> Optional.of(x).filter(n -> n % 2 == 0))
```

Currently the alternatives are:

**filter + get**

```java
numbers
  .filter(Optional::isPresent)
  .map(Optional::get)
```

**collect**
```java
numbers
  .collect(new PFBuilder<Optional<Integer>, Integer>()
    .matchUnchecked(
        Optional.class,
        (FI.TypedPredicate<Optional<?>>) Optional::isPresent,
        (FI.Apply<Optional<Integer>, Integer>) Optional::get
    )
    .build());
```

**flatMapConcat (≥ JDK 9 only)**
```java
numbers
  .flatMapConcat(x -> StreamConverters.fromJavaStream(x::stream))
```

The latter is the shortest way of doing it but besides the limitation on JDK version it is also incredibly inefficient, benchmarking it with 10 million elements resulted in 50x longer running time compared to the other two alternatives, I am not too familiar with Akka stream internals but I am guessing that this will materialize a stream for every element.  

It seems to me like such a common use case that it could warrant its own operator something like `filterOptional` or similar that could be added to the Java DSL would reduce a lot of unnecessary boilerplate.

**Comment by johanandren** [comment]
Sounds like it could make sense and is useful enough on one hand but on the other hand since it is quite simple to create in your own code base, and you could define it in one place and re-use that one like so:

```java
private final static Flow<Optional<Object>, Object, NotUsed> singleInstance =
    Flow.<Optional<Object>>create().filter(Optional::isPresent).map(Optional::get);

@unchecked
public static <A> Flow<Optional<A>, A, NotUsed> flattenOptional() {
  return ((Flow<Optional<A>, A, NotUsed>)((Flow) singleInstance));
}
```

That'd be `flattenOptional` rather than filter though, since it also flattens, and it'd need the corresponding operation for Scala `Option` in the Scaladsl. 

Let's see what the rest of the team thinks about it being useful enough to add to the API.

**Comment by gabriel-ntuc** [comment]
> but on the other hand since it is quite simple to create in your own code base, and you could define it in one place and re-use that one

I understand what you are saying, but couldn't this argument be applied to many other currently existing operators? Like `filterNot` for example which is even simpler to define in your own codebase.

**Comment by johanandren** [comment]
Indeed it could, that one is probably there to align with the Scala collection APIs that has the same method name. 

When we have added a new operator we will have to maintain it and keep it bincomp forever(tm) so that's why we don't just jump on every operator idea, even if they have merit ;)

**Comment by johanandren** [comment]
BTW if that was unclear I'm leaning towards that we should add it.

**Comment by patriknw** [comment]
I agree that this would be useful (since collect is not nice). Let’s add it. Would you like to create a PR, @gabriel-ntuc ?

**Comment by johanandren** [comment]
Ah, yes, for Scala we have `.collect` so ignore the part about needing to add something for Scala option.

**Comment by asureshraja** [comment]
@johanandren @patriknw 
I raised PR for this, can you guys check it  PR #27350

**Comment by hepin1989** [comment]
@asureshraja How about :

```scala
  def collectWith[T](predicate:java.util.function.Predicate[Out],
                                 function:java.util.function.Function[Out,T]) :javadsl.Source[T,Mat]
```

**Comment by hepin1989** [comment]
@gabriel-ntuc Are you OK with this kind of `collectWith`?

**Comment by johanandren** [comment]
@hepin1989 I don't think that adds any value over `filter` + `map` so let's go with this specific one for `Optional`.

**Comment by hepin1989** [comment]
@johanandren I think this can be closed now.

**Comment by johanandren** [comment]
Yep, thanks for the ping and (the PR)

**Comment by hepin1989** [comment]
I am using the Java API :)
