### ISSUE TITLE
private[akka] or private modifier does not work for case-class in scala 2.11+

### ISSUE THREAD

**Issue by ShutaoTang** [akka/akka#26886]
Consider the following code in **akka-actor** module

```  scala
   package akka.dispatch

   final case class Envelope private (val message: Any, val sender: ActorRef)

   object Envelope {
     def apply(message: Any, sender: ActorRef, system: ActorSystem): Envelope = {
        if (message == null) throw InvalidMessageException("Message is null")
        new Envelope(message, if (sender ne Actor.noSender) sender else system.deadLetters)
    }
  }
```

The purpose of `private` is to enforce using 3-parameters constructor `applay()` to create instances via a in companion object.

```scala
  package akka.actor

  @SerialVersionUID(1L)
  final case class InvalidMessageException private[akka] (message: String) extends AkkaException(message)

  @SerialVersionUID(1L)
  class ActorInterruptedException private[akka] (cause: Throwable) extends AkkaException(cause.getMessage, cause)

```
 The aim of `private[akka`]  is that only package `akka` can access the constructor of `InvalidMessageException` or `ActorInterruptedException `

However, I notice that it doesn't work for `case-class` in the version scala 2.11+. Please see the following test of client-code

``` scala
import akka.actor.{Actor, ActorInterruptedException, ActorSystem, InvalidMessageException, Props}
import akka.dispatch.Envelope

class PrinterActor extends Actor {
  override def receive = {
    case "XX" => println("hello")
  }
}

object TestPrivate extends App {
  val system = ActorSystem("hello")
  val printerActor = system.actorOf(Props[PrinterActor])

  val e = Envelope(1, printerActor)
  println(e.toString)

  val x = InvalidMessageException("xxx")
  println(x.toString)

  // val y = new ActorInterruptedException("yyy")    (1)
 
   system.terminate()
}
```
Then console output: 

>  Envelope(1,Actor[akka://hello/user/$a#1281497313])
akka.actor.InvalidMessageException: xxx

If I uncomment the code of (1), then the compiler gives the error

> Error:(24, 11) constructor ActorInterruptedException in class ActorInterruptedException cannot be accessed in object TestPrivate
  val y = new ActorInterruptedException("yyy")

#### Summary

So I guess the `private` modifier just work for class rather than case-class

**Comment by johanandren** [comment]
Calling the constructor of `Envelope` would be `new Envelope(1, printerActor)`,
the code you shared calls `Envelope(1, printerActor)` which is sugar for `Envelope.apply(printer, actor)`.

`private (` makes the constructor private not the `apply` factory method.

**Comment by ShutaoTang** [comment]
@johanandren Thanks a bunch for your explanation. Maybe I have a misunderstanding of this topic.
