### ISSUE TITLE
New ReceiveTimeout not applied if it was set while handling a `NotInfluenceReceiveTimeout` message

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#26880]
If the receive timeout timeout is changed during handling a `NotInfluenceReceiveTimeout` message, the new timeout is not applied immediately but only after a regular message has been handled. It is certainly an edge case and probably not well-specified (from where should the timeout count if the current message shouldn't reset the timeout?).

We could either

 * specify and fix it
 * document and test the current behavior (or explicitly leave it as unspecified)
 * disallow changing the timeout during handling a `NotInfluenceReceiveTimeout` message

**Comment by patriknw** [comment]
yup, sorry for typo
