### ISSUE TITLE
failed: LargeMessageClusterSpec should not run with classic remoting

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26889]
LargeMessageClusterSpec is another test that shouldn't run with classic, when overriding `akka.remote.artery.enabled=off` from jenkins job

https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/6

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/10/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/12/consoleFull
