### ISSUE TITLE
Convert some Lagom sample

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26894]
Maybe get more involved in the [Shopping Cart sample](https://github.com/renatocaval/shopping-cart-scala/pull/1).

Look for things that would be inconvenient for Lagom users and if we can do better.

**Comment by TimMoore** [comment]
I think @renatocaval has already done some work here

**Comment by patriknw** [comment]
> I think @renatocaval has already done some work here

Absolutely, and that is the link I included above. Should also look at javadsl, and second opinion about Renato's approach and what he thinks is not nice.

**Comment by patriknw** [comment]
I took a first stab at converting the Java ShoppingCart to Akka Typed: https://github.com/renatocaval/lagom-1.6-playground/pull/1
