### ISSUE TITLE
PreRestart missing from typed docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26899]
We haven't mentioned PreRestart in the lifecycle or the fault tolerance parts of the docs, we probably should.

**Comment by mtsokol** [comment]
Hi, I just came across this issue and I really couldn't find example of PreRestart in Akka Actor Typed anywhere.   

How can I write a typed behavior where I can get `case (reason: Throwable, message: Option[Any]) => ` inside my `Behaviors.receive` for handling exception for concrete messages? 
The docs are really short on this case.

**Comment by michkhol** [comment]
Also not clear how one can use PreRestart in deferred behaviors. Would be nice to accompany the signal with the actual exception thrown. Because wrapping every behavior in try-catch block just to see what‘s happened looks ugly.

**Comment by mtsokol** [comment]
Ok, so for now I ended up with introducing `StashBuffer` for my behavior:

```scala
val act = Behaviors.setup {
  ctx => 
  val buffer = StashBuffer[Domain](capacity = 10)
  Behaviors.receiveMessage {
    msg =>
    // in case of failure within Try:
    buffer.stash(msg)
    //...
  }.receiveSignal {
    case (actor, PreRestart) =>
      ctx.self ! buffer.head
      act
  }
}
```
So here the issue is that `msg` is not removed from buffer which leads to overflow. 
Although when using `unstash` instead of `head`, in case when this message still leads to failure during first restart, the message is permanently removed from stash which misses the point of restarting for e.g. 5 times with some backoff.

**Comment by jrudolph** [comment]
(Partially answered at https://stackoverflow.com/questions/56207474/how-to-use-prerestart-in-akka-typed/56256475#56256475.)

> So here the issue is that `msg` is not removed from buffer which leads to overflow.
> Although when using `unstash` instead of `head`, in case when this message still leads to failure during first restart, the message is permanently removed from stash which misses the point of restarting for e.g. 5 times with some backoff.

**Comment by michkhol** [comment]
Here is the use case. We have a bunch of "silent" microservices that stream data to and from Kafka. The only way of knowing _in time_ if something wrong happened is to make them signal us one way or another. The best way is to send the cause of restart - the concrete exception. 
The deliberate decision not to inform the user about restart exceptions leaves us the only way - inspecting the logs. Ironically, the supervisor knows every cause of restart and dutifully reports them. Why it cannot embed them into the prerestart signal (as in typed Actors) is beyond my understanding.
