### ISSUE TITLE
Hostname verification should be set on Client role only

### ISSUE THREAD

**Issue by rohitkumbhar** [akka/akka#26905]
Setting the flag `akka.remote.artery.ssl.config-ssl-engine.hostname-verification=on` sets hostname verification on both client and server SSLEngine instances by setting the endpoint identification algorithm to HTTPS. However this causes the server ssl engine to look for the server name ( bindHost value ) in the cert chain provided by the client. This is very unlikely to pass as the client would not offer any cert with the server name.

Possible fix: https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala#L167
Change the condition to` if (HostnameVerification && role == akka.stream.Client)`

If the expected behavior is that the client should offer a cert containing the server name in Subject Alternate Names, then its probably best to call it out in the documentation.

**Comment by jrudolph** [comment]
With `require-mutual-authentication` I would expect that hostname in the certificate would be checked in both directions. In that case, the same certificate would be used for both directions, right?

How does it fail without the fix? You can only define one set of certificates which will be used in both roles, so the hostname should be in there anyway if you want to enable HostnameVerification.

**Comment by rohitkumbhar** [comment]
There are at least 2 certificates involved. One with extended key attributes set to `clientAuth` and another other with `serverAuth`. 

Let say in a scenario with node1 and node2:
`node2` has discovered `node1` and wants to connect to `node1`.  `node2` finished a ClientHello and `node1` offers its certificate with `serverAuth` set. `node2` checks this certificate for the extended key attribute and the CN is actually set to `node1`. `node2` then offers its own certificate to `node1` since we need mutual authentication. The TLSActor is still using the SSLEngine instance returned by the `createServerSSLEngine()`. `node1` may or may not know (according to the [RFC 2818](https://tools.ietf.org/html/rfc2818#section-3.2) the hostname of the client. In the implementation of `sun.security.ssl.X509TrustManagerImpl` it  ignores the hostname of the client. The trust manager checks that the extended key attribute `clientAuth` is set in the cert offered by `node2` AND the **hostname is set to its own name** `node1`. 

A (reasonable, imo) PKI setup would not provide(or allow) a host to serve a certificate that does not have some other host's name as CN unless it was explicitly marked for server cert. In this case its a client cert and hence has the name of the client. So the certs provided in each node are going to be different and the expectation for all of them serve the same name is not going to be possible.


With this change, `node1` would not verify the hostname in the client cert offered by `node2`. However, after the first handshake has finished, `node1` now acts as a client to `node2`.  This allows `node1` to verify the server cert with name provided by `node2`. As far as security goes, both nodes have verified each others' hostnames acting as clients in turn.

**Comment by jrudolph** [comment]
> There are at least 2 certificates involved. One with extended key attributes set to `clientAuth` and another other with `serverAuth`.

Is that extended attribute needed to make it work properly? E.g. Github's certificate has "Extended Key Usage" set to both "TLS Web Server Authentication (1.3.6.1.5.5.7.3.1)" and "TLS Web Client Authentication (1.3.6.1.5.5.7.3.2)" so it's certainly possible to use one certificate for both roles.

In akka, there are no clients and servers but remoting is peer-to-peer. With Artery TCP, there will be a pair of TCP connections (each only unidirectionally used) between two hosts. For one connection of a pair, the roles are this way and for the other connection it will be the other way round. In the Akka config, you can only define a single KeyStore which will be used for both directions. Afaik this worked fine so far if `require-mutual-authentication` is set.

> node1 may or may not know (according to the RFC 2818 the hostname of the client.

>  In the implementation of `sun.security.ssl.X509TrustManagerImpl` it ignores the hostname of the client.

The question is if that is a problem or not. Since we always have this pair of connections, one direction *will* fail if one of the nodes uses a wrong certificate.

**Comment by rohitkumbhar** [comment]
You are right, the extended key attributes have no bearing on this other than the fact that they are required and my PKI doesn't issue a cert with both set.

Also, I'm sorry I should have mentioned this before. I'm working with Akka 2.5.22 and Artery enabled with protocol tls-tcp.

The [SSLEngineProvider trait](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala#L38) does require a server and client sslEngine instances even if the remoting is logically peer to peer. mTLS requires that the certs are trusted on either side.  The hostname verification requirement on server side causes the failure which is addressed in the related PR.

**Comment by raboof** [comment]
Perhaps we should change the `akka.remote.artery.ssl.config-ssl-engine.hostname-verification` setting so `on` performs hostname verification on both sides of the connection (current behaviour), but a new setting such as `on-client` configures it so the client will check the servers' hostname but not vice-versa?

(out of curiousity: what kind of PKI infrastructure are you using here? do all nodes have different client and server certificates, or do they share a set?)

**Comment by jrudolph** [comment]
> The SSLEngineProvider trait does require a server and client sslEngine instances even if the remoting is logically peer to peer. mTLS requires that the certs are trusted on either side. The hostname verification requirement on server side causes the failure which is addressed in the related PR.

I see, I didn't think about that customization API.

> Perhaps we should change the `akka.remote.artery.ssl.config-ssl-engine.hostname-verification` setting so `on` performs hostname verification on both sides of the connection (current behaviour), but a new setting such as `on-client` configures it so the client will check the servers' hostname but not vice-versa?

I think the question is whether it is possible at all to implement the server-side hostname verification properly. You have to know with whom you *want to* talk to do hostname verification. On the server side, you don't know whom you are talking to when hostname verification is done. You only know after the akka-level handshake what host the remote ActorSystem claims to be (but even then: couldn't it just claim to be the hostname it has stolen a certificate for?). In any case, a connection attempt to create the other direction of the channel would still fail if certificates don't match up (or if network traffic / routing has been tampered with to spoof another host).

So, after this discussion I tend to accept #26906 as is.

**Comment by raboof** [comment]
> even then: couldn't it just claim to be the hostname it has stolen a certificate for?

hmm, good point, for this to be useful at all the server would need to have some kind of whitelist of expected clients, that seems like a rabbit hole.

> a connection attempt to create the other direction of the channel would still fail if certificates don't match up

true, though accepting the client connection already potentially opens up some vectors (e.g. attacking serialization?)

> So, after this discussion I tend to accept #26906 as is.

sounds reasonable :+1:

**Comment by rohitkumbhar** [comment]
> (out of curiousity: what kind of PKI infrastructure are you using here? do all nodes have different client and server certificates, or do they share a set?)

Every instance gets its own client and server certificate from a intermediate CA for the instance. A root CA for the region provides these on instance launch. These are provided as pem files since we can't (or don't want to) distribute the password for the key store. The certs are also rotated aggressively. 

Thank you for the code review.

**Comment by raboof** [comment]
Thanks!!
