### ISSUE TITLE
FromConfig Java API docs do not show up in javadoc html

### ISSUE THREAD

**Issue by raboof** [akka/akka#26900]
I would hope to find the documentation at https://doc.akka.io/japi/akka/current/akka/routing/FromConfig.html, but this just says `INTERNAL API` - not sure where that comes from.

**Comment by johanandren** [comment]
Seems like it is not the class/trait docs, but from some method inside. Also, compare https://doc.akka.io/japi/akka/current/akka/routing/RouterConfig.html with the actual scaladoc on [RouterConfig](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/routing/RouterConfig.scala#L42)

**Comment by patriknw** [comment]
Let's use `bug` for production bugs. This looks like a documentation improvement

**Comment by johanandren** [comment]
Looks like the Scaladoc does not end up in the right place in the Javadoc for any place where there is a class:

https://doc.akka.io/japi/akka/current/akka/actor/typed/javadsl/AbstractBehavior.html
https://doc.akka.io/japi/akka/current/akka/actor/typed/javadsl/PoolRouter.html
https://doc.akka.io/japi/akka/current/akka/actor/typed/javadsl/Behaviors.html

**Comment by raboof** [comment]
This reminds me of https://github.com/lightbend/genjavadoc/issues/220 and #23756

**Comment by patriknw** [comment]
This is important to fix. Looking at AbstractBehavior it's completely messed up. Why is that "Implement this to define how messages..." the class comment?

Javadoc: https://doc.akka.io/japi/akka/current/akka/actor/typed/javadsl/AbstractBehavior.html
Scaladoc: https://doc.akka.io/api/akka/current/akka/actor/typed/javadsl/AbstractBehavior.html

**Comment by patriknw** [comment]
https://doc.akka.io/japi/akka/2.6.4/akka/routing/FromConfig.html
