### ISSUE TITLE
UDP Connected actor stops when UDP server is unavailable.

### ISSUE THREAD

**Issue by devlaam** [akka/akka#26903]
The Akka documentation allows for a simple [client / server demo](https://doc.akka.io/docs/akka/current/io-udp.html). If I build two applications accordingly with 'connected UDP' on the client size,  and let them talk over a the internal  network, for example the localhost (but an IP number reacts the same, dns is not used in this case), this works as long as the server remains available. If that is manually stopped, and just one packet is send from the client side to the now absent server, the [UdpConnection Actor](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/UdpConnection.scala#L23) that manages the transmission dies without sending the expected ```UdpConnected.Disconnected``` message. If i activate a firewall in between (so that packets are silently dropped) the actor keeps running. 

Would the following not be better: if the underlying transport layer is aware of a problem to send a ```UdpConnected.Unavailable``` message and keep running? UPD should be 'send and forget' as much as possible and leave problem solving to the layers above. 

Even if a ```UdpConnected.Disconnected``` was send, that behaviour is probably not intended too. 
I switched on logging on UDP level and got this after trying to send a packet:

```
[DEBUG] [05/10/2019 10:47:57.128] [base-akka.actor.default-dispatcher-13] [akka://base/system/IO-UDP-CONN/selectors/$a/4] null
[DEBUG] [05/10/2019 10:47:57.130] [base-akka.actor.default-dispatcher-10] [akka://base/system/IO-UDP-CONN/selectors/$a/4] Closing DatagramChannel after being stopped
 ...
[INFO]  [05/10/2019 10:48:01.543] [base-akka.actor.default-dispatcher-4] [akka://base/system/IO-UDP-CONN/selectors/$a/4] Message [akka.io.UdpConnected$Send] 
        from Actor[akka://base/user/$c/Connector:system:0:1/topicWorker:error#2117057478] to Actor[akka://base/system/IO-UDP-CONN/selectors/$a/4#-1205848350] 
         was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://base/system/IO-UDP-CONN/selectors/$a/4#-1205848350]] 
         may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 
         'akka.log-dead-letters-during-shutdown'.
```
The logging of just a `null` is suspicious, i could not find the source of that message. The next log message stems from the overridden ```postStop()``` in de [```private class UdpSender```](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/UdpConnection.scala#L148)

The [instruction](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/WithUdpSend.scala#L80) in the code that handles the actual writing:
```Scala
  val writtenBytes = channel.send(buffer, pendingSend.target) 
```

probably raises some kind of [IO exception](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/DatagramChannel.html#write-java.nio.ByteBuffer:A-) which is not (properly) handled.  

I would appreciate comments, this behaviour *may* qualify as a bug.

**Comment by johanandren** [comment]
What happens is that there is a `java.net.PortUnreachable` exception thrown from `channel.read` in `UdpConnection.doRead()` and that is not handled correctly. It's a bug, since UDP is connectionless I think this should basically be ignored like you say. I don't think we should introduce any new message to inform about the fact that it is unavailable.

**Comment by raboof** [comment]
Even though UDP is connectionless, if this information is available (through ICMP I guess?) it might make sense to expose it to the user somehow. That would be a separate feature though - for this issue I think fixing the bug should be sufficient ;)

**Comment by kalou** [comment]
Hi there, I was playing around UDP.Send and we have the same issue when encountering a NoRouteToHostException - It looks like the same bug and I thought I'd let you know here.

```
[DEBUG] [08/29/2019 21:31:24.896] [test-akka.actor.internal-dispatcher-3] [akka://test/system/IO-UDP-FF/selectors/$a/0] No route to host
[DEBUG] [08/29/2019 21:31:24.906] [test-akka.actor.internal-dispatcher-2] [akka.tcp://test@.../system/IO-UDP-FF/selectors/$a/0] Closing DatagramChannel after being stopped
```
