### ISSUE TITLE
New Java API for ByteString.empty()

### ISSUE THREAD

**Issue by raboof** [akka/akka#26926]
The current Java API for creating an empty `akka.util.ByteString` is `ByteString.empty()`. This works because `object ByteString` has a `val empty: ByteString`, and scalac creates a static forwarder on `class ByteString` to call this method from Java.

Scala 2.13 introduces the `empty()` method on `Iterable`, and because `ByteString` is `Iterable` this means `empty()` on `ByteString` is now that non-static method, and no static forwarder is generated any more (https://github.com/scala/bug/issues/11509).

The easiest way to get out of this tricky situation would be to introduce a new Java API for getting an empty `ByteString` instance. This would be binary and source compatible as long as people use the `2.11` or `2.12` artifacts, but we can immediately start recommended the newly introduced API going forward so this will keep working on `2.13` onward.

What should this API be called? `ByteString.emptyString()` is descriptive but verbose. `ByteString.ofEmpty()` looks weird. `ByteString.nil()` seems neat but might be a bit of a Scala-ism. Other ideas?

**Comment by jrudolph** [comment]
Maybe just `Empty`? :)

**Comment by dwijnand** [comment]
`ByteString.emptyString()` is bad because it doesn't return an empty string, but an empty byte string.

Ideas:
* `ByteString.of()` (using `@varargs`, just make sure to dodge https://github.com/scala/bug/issues/10683)
* `ByteString.EMPTY()` (still no way to declare a static final val in Scala 🙁)

But I'm also looking at the existing API, and here are some ideas:
* `ByteString.fromInts()` (weird name)
* `ByteString.fromString("")` (okish-name, extra param)

**Comment by patriknw** [comment]
ByteString.zeroBytes or ByteString.emptyBytes ?

**Comment by TimMoore** [comment]
Something verbose but straightforward such as `ByteString.emptyByteString()` has the advantage that it is still clear with a static import: `emptyByteString()`. Is this really so commonly used that verbosity is a big problem?

**Comment by dwijnand** [comment]
Yeah, Tim's solution works both as a workaround for the problem and as a legit Java API as a nice static import.

**Comment by raboof** [comment]
Let's go with `ByteString.emptyByteString()` - it's used pretty often when dealing with streams of bytes, but the static import makes it succinct enough :+1:

**Comment by TimMoore** [comment]
It even saves a character! 😄
