### ISSUE TITLE
Publish version-coherent snapshots

### ISSUE THREAD

**Issue by dwijnand** [akka/akka#26958]
Yesterday I un-misconfigured Play and Lagom's nightly builds so this isn't specifically about any change from yesterday, but one of last night's cron job failures for Play's master branch has to do with incoherent versions being used for different modules of Akka.

The investigation notes are in https://github.com/playframework/play-meta/issues/77, but the symptom is that our job was using the version 2.6-20190516-231020 to look for akka-stream_2.13.0-M5, which instead has version 2.6-20190516-233030.

As @patriknw said, probably because it's re-timestamping between 2.12 and 2.13 publishes.

**Comment by patriknw** [comment]
Understood that it would be good to align the version. I think that can be done rather easily by letting the jenkins job pick the timpstamp and pass it in to the build with `-Dakka.version`. I can try to fix this today.

**Comment by patriknw** [comment]
@dwijnand I'm stuck on that I can't set the property from the jenkins job. In the end I want to pass in this to the sbt launcher:
```
sbt -Dakka.build.version=`date +"%Y%m%d-%H%M%S"`
```

or via an environment variable
```
AKKA_VERSION=`date +"%Y%m%d-%H%M%S"`
sbt -Dakka.build.version=$AKKA_VERSION
```

What I have tried that don't work:
- shell build step before the sbt step
- Jenkins Environment Injector Plugin
- custom Jenkins sbt tool, trying to add this as launch parameter

**Comment by patriknw** [comment]
https://github.com/akka/akka/issues/26675 might be a way if we can't solve this stupid thing in Jenkins.

**Comment by patriknw** [comment]
Solved it by letting shell step write it to a file, which then the Jenkins Environment Injector Plugin can make into an environment variable that can be used in following sbt build step. 😁

**Comment by dwijnand** [comment]
Try allocating a `val currentDateTime = java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss").format(java.time.ZonedDateTime.now(java.time.ZoneOffset.UTC))` in `AkkaBuild` and using that.

```scala
scala> java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss").format(java.time.ZonedDateTime.now(java.time.ZoneOffset.UTC))
res12: String = 20190517-123346
```

Won't work if you invoke sbt multiple time, of course.

**Comment by dwijnand** [comment]
Yeah using the filesystem state was my next suggestion 🙂

**Comment by patriknw** [comment]
Creating it in the build is much better, thanks. It works.
I had the wrong assumption that it was reloaded or something when using `+publish`.

**Comment by dwijnand** [comment]
Well, now I'm confused too.

From experimenting, I've disproven two things I believed true:

1. I thought during `reload` objects aren't re-initialised, while they actually are (so `reload` will give different `currentDateTime`)

2. I thought `+` would have the same semantics of `reload`, instead it seems that `+` doesn't do the re-initialising `reload` does, so `currentDateTime` is stable.

So a more stable solution might be

```scala
  val currentDateTime = sys.props.getOrElseUpdate(
    "akka.build.version",
    java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss").format(
      java.time.ZonedDateTime.now(java.time.ZoneOffset.UTC)
    )
  )
```

**Comment by patriknw** [comment]
Ok, what is the reason? to be stable for reloads (which we don't need for snapshots) or to be more future proof in case this behavior of `+` changes?

**Comment by dwijnand** [comment]
I'm concerned about both reasons, so both.

**Comment by patriknw** [comment]
ok, I'll update

**Comment by patriknw** [comment]
I have updated the Jenkins jobs for master and release-2.5

**Comment by dwijnand** [comment]
So this looks fixed for 2.5.x releases:

* https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.12/2.5-20190529-210038/
* https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.13.0-M5/2.5-20190529-210038/

but not for master releases:

* https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.12/2.6-20190530-210101/
* https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.13.0-RC2/2.6-20190530-211636/

(I can report as a new issue if you prefer.)

**Comment by patriknw** [comment]
@dwijnand My bad, misconfigured the Jenkins job so it used `-Dakka.build.version=timestamp` in the second step (2.13). Changed now to `file`, so it should be ok from tomorrow.

**Comment by dwijnand** [comment]
Whoops!

https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.13.0-RC2/file/

**Comment by patriknw** [comment]
That's weird. We publish those in two steps:
```
-Dakka.build.version=timestamp -Dakka.build.scalaVersion=2.12.8
-Dakka.build.version=file -Dakka.build.scalaVersion=2.13.0-RC2
```

Similar is done for Akka 2.5 and there it's correct.

Ah, the "file" thing was only included in 2.5 branch. I'll fix.

**Comment by dwijnand** [comment]
* https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.13.0-RC2/2.6-20190604-210100/
* https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.12/2.6-20190604-210100/

🎉 Thank you, Patrik

**Comment by patriknw** [comment]
Thanks, sorry for the iterations.
