### ISSUE TITLE
Upgrade to Scala 2.13.0-RC2

### ISSUE THREAD

**Issue by raboof** [akka/akka#26964]
Continuation of #26691

See also https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md

Depends on:
* [x] https://github.com/ghik/silencer/pull/26
* [x] https://github.com/scala/scala-java8-compat/issues/145
* [x] https://github.com/lightbend/ssl-config/issues/168
* [x] https://github.com/rickynils/scalacheck/issues/471
* [x] https://github.com/lightbend/genjavadoc/issues/172
* [x] spray-json
* [x] scalatest 3.0.x (ended up not using https://github.com/scalatest/scalatestplus-junit/issues/3, https://github.com/scalatest/scalatestplus-mockito/issues/3, https://github.com/scalatest/scalatestplus-testng/issues/3 and https://github.com/scalatest/scalatestplus-scalacheck/issues/6, moving that to #26989)

**Comment by SethTisue** [comment]
ScalaCheck has now published

**Comment by raboof** [comment]
Akka 2.5.23 for Scala 2.13.0-RC2 is on its way to Maven Central now

**Comment by SethTisue** [comment]
(maybe this should be closed but #26992 kept open?)
