### ISSUE TITLE
Typed scheduler leaks untyped ActorRef

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26971]
In typed `system.scheduler` is the untyped `Scheduler` and has message signatures like `def scheduleOnce(delay: FiniteDuration, receiver: ActorRef, message: Any)`. 

Shouldn't there be a specific typed scheduler without any untyped types in the signatures?

**Comment by patriknw** [comment]
I dont' see `Scheduler` as end user API. Timers should be used, or `ActorContext.scheduleOnce` if you want to send a message to someone else after a delay.

**Comment by johanandren** [comment]
I agree. Should we enforce (typed specific trait with no or fewer methods?) or at least document that somehow?

**Comment by patriknw** [comment]
> Should we enforce (typed specific trait with no or fewer methods?) or at least document that somehow?

Ok, we can add another interface exposing only the relevant methods.
