### ISSUE TITLE
failed: AkkaProtocolSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26974]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/236

```
[info] - must in outbound mode delay readiness until hadnshake finished *** FAILED *** (4 milliseconds)
[info]   false did not equal true (AkkaProtocolSpec.scala:233)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6859)
[info]   at akka.remote.classic.transport.AkkaProtocolSpec.$anonfun$new$10(AkkaProtocolSpec.scala:233)

```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/239/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/240/testReport/junit/akka.remote.classic.transport/AkkaProtocolSpec/ProtocolStateActor_must_in_outbound_mode_delay_readiness_until_hadnshake_finished/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/261/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/263/testReport/junit/akka.remote.classic.transport/AkkaProtocolSpec/ProtocolStateActor_must_in_outbound_mode_delay_readiness_until_hadnshake_finished/
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/264/testReport/akka.remote.classic.transport/AkkaProtocolSpec/ProtocolStateActor_must_in_outbound_mode_delay_readiness_until_hadnshake_finished/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/268/testReport/junit/akka.remote.classic.transport/AkkaProtocolSpec/ProtocolStateActor_must_in_outbound_mode_delay_readiness_until_hadnshake_finished/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/280/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/279/testReport/junit/akka.remote.classic.transport/AkkaProtocolSpec/ProtocolStateActor_must_in_outbound_mode_delay_readiness_until_hadnshake_finished/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/290/testReport/junit/akka.remote.classic.transport/AkkaProtocolSpec/ProtocolStateActor_must_in_outbound_mode_delay_readiness_until_hadnshake_finished/

**Comment by chbatey** [comment]
https://github.com/akka/akka/issues/26974

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/302/
