### ISSUE TITLE
Change PartialFunction in typed.javadsl.ActorSource

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26970]
PartialFunction shouldn't be used in javadsl. Use something like this instead:

```
java.util.Function[T, Optional[Throwable]]
```

**Comment by nvollmar** [comment]
There's a `akka.japi.JavaPartialFunction` (which is quite old - last changes in 2012)?

**Comment by patriknw** [comment]
it's just difficult to use and a foreign concept for Java developers (I think it was introduced even before there were lambdas in Java)

**Comment by nvollmar** [comment]
But I can use it to convert the java function into a partial function :) (See #26972)

**Comment by patriknw** [comment]
There is still an open PR for master but closing ticket so that it's included in today's 2.5.23 milestone.
