### ISSUE TITLE
failed: ForkJoinPoolStarvationSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26973]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/236

```
[info] AkkaForkJoinPool
[info] - must not starve tasks arriving from external dispatchers under high internal traffic *** FAILED *** (39 seconds, 735 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for All fine
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:395)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:395)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
[info]   at akka.dispatch.ForkJoinPoolStarvationSpec.$anonfun$new$6(ForkJoinPoolStarvationSpec.scala:64)
[info]   at akka.dispatch.ForkJoinPoolStarvationSpec.$anonfun$new$6$adapted(ForkJoinPoolStarvationSpec.scala:61)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:155)
[info]   at akka.dispatch.ForkJoinPoolStarvationSpec.$anonfun$new$2(ForkJoinPoolStarvationSpec.scala:61)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/237/

**Comment by patriknw** [comment]
Looks like this is failing every time in the JDK 11 job after merging the FJP PR.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/240/testReport/junit/akka.dispatch/ForkJoinPoolStarvationSpec/AkkaForkJoinPool_must_not_starve_tasks_arriving_from_external_dispatchers_under_high_internal_traffic/

**Comment by jrudolph** [comment]
Interestingly, it doesn't fail on my machine but the test may run for minutes in some cases.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/244/testReport/akka.dispatch/ForkJoinPoolStarvationSpec/AkkaForkJoinPool_must_not_starve_tasks_arriving_from_external_dispatchers_under_high_internal_traffic/

**Comment by jrudolph** [comment]
Hmm, it seems that the JDK11 FJP has a similar optimization than our own in that was reverted after #17341 was found. I.e. if a task is scheduled from a FJP thread, there's a fast-lane to submit that job to the local queue. The alternative method `externalPush` is not public. Accessing it through reflection seems to avoid the issue but reflection may or not be too slow for general usage.

**Comment by jrudolph** [comment]
We have these alternatives to go forward:

 * Use reflection to use `externalPush` explicitly on JDK 11 which should revert to behavior which is more like the one with the old FJP
 * Make the tasks lighter in the test here (`throughput` and `akka.actor.serialize-messages = off`) to make the tasks pass.

When we test the new BatchingExecutor in #26383 we could revisit this task and see if that changes anything.

**Comment by johanandren** [comment]
For option 2: #27035

**Comment by viktorklang** [comment]
Using a MethodHandle to call `externalPush` is also an option.

**Comment by johanandren** [comment]
I think there is quite some overhead for `externalPush` compared to the `WorkQueue.push` that happens from JFP threads, so always going through `externalPush` could improve fairness but at a cost of throughput.

**Comment by johanandren** [comment]
I think we can close this since option 2 was implemented, if anyone wants to take a stab at nasty reflect-access to FJP internals that's fine but not urgent.
