### ISSUE TITLE
Better indicator of ActorRefProvider implementation selection

### ISSUE THREAD

**Issue by helena** [akka/akka#27009]
Multiple places needing the same logic:
* FixMe: better indicator that cluster is enabled: https://github.com/akka/akka/blob/master/akka-actor-typed/src/main/scala/akka/actor/typed/receptionist/Receptionist.scala#L31
* and the in-progress https://github.com/akka/akka/issues/26176

I will push an idea for this first before proceeding further with https://github.com/akka/akka/issues/26176

**Comment by patriknw** [comment]
this was not backported (and shouldn't be backported) so setting milestone to 2.6.0-M3 instead of 2.5.23

**Comment by helena** [comment]
Ah, right, thank you.
