### ISSUE TITLE
Persistence typed examples have no tests

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#27002]
E.g. in `AccountExampleWithCommandHandlersInState` the following simple usage of the actor does not compile:

```scala
val behavior = AccountExampleWithCommandHandlersInState.AccountEntity.behavior("1")
  val ref = spawn(behavior)
  val probe = TestProbe[AccountCommandReply]
  ref.tell(CreateAccount()(probe.ref))
```

None of the given examples have any tests, so they might or might not work correctly.

**Comment by patriknw** [comment]
I'm adding tests in https://github.com/akka/akka/pull/26813 but not sure if it covers this specifically.

**Comment by jrudolph** [comment]
> I'm adding tests in #26813 but not sure if it covers this specifically.

Probably yes, you seem to have fixed the problem here: https://github.com/akka/akka/pull/26813/files#diff-48118ba2afb905ffbb7aa89ab9783afeR136

**Comment by dwijnand** [comment]
Added that code snippet and the necessary changes in https://github.com/akka/akka/pull/27001, but it needs cleaning up.

**Comment by jrudolph** [comment]
@patriknw do you remember why we need `ExpectingReply` at all? I.e. why do we have to pass the command to `Effect.reply` and not just the `replyTo` ref?

**Comment by jrudolph** [comment]
FTR: it was introduced here: https://github.com/akka/akka/pull/25692 but afaics there was no discussion about introducing `ExpectingReply`.

**Comment by patriknw** [comment]
@jrudolph It was added on request from Lagom team to get help from the compiler to not forget to send a reply to a command. In Lagom the persistent entities are used with a `ask` from the service and the commands should always have an ack reply of some sort. Lagom users have run into the mistake of not sending a reply and then have difficulties understanding the reason for the problem.

Lagom already has a concept of replies defined by the commands, but it was not enforced like this solution with `EventSourcedEntity.withEnforcedReplies`.

**Comment by patriknw** [comment]
I added test for the case mentioned in the description of this ticket here https://github.com/akka/akka/pull/26813/commits/d231e3c9f6b214532205f282dbc29441a99f7dff

In Java it doesn't work, but I'm not sure that is something that is needed. One can use `ActorRef.narrow()` in Java.

```java
    EntityRef<AccountCommand> ref = sharding().entityRefFor(AccountEntity.ENTITY_TYPE_KEY, "2");
    TestProbe<AccountCommandReply> probe = testKit.createTestProbe(AccountCommandReply.class);
    ref.tell(new CreateAccount(probe.getRef().narrow()));
    probe.expectMessage(Confirmed.INSTANCE);
```

Other tests also added in https://github.com/akka/akka/pull/26813 so I believe when that is merged this ticket is fixed.

**Comment by jrudolph** [comment]
> @jrudolph It was added on request from Lagom team to get help from the compiler to not forget to send a reply to a command. In Lagom the persistent entities are used with a `ask` from the service and the commands should always have an ack reply of some sort. Lagom users have run into the mistake of not sending a reply and then have difficulties understanding the reason for the problem.
> 
> Lagom already has a concept of replies defined by the commands, but it was not enforced like this solution with `EventSourcedEntity.withEnforcedReplies`.

I see how that can be useful. I only find it somewhat of a heavy-weight solution because it requires that those reply types need to be explicit part of the command type when calling `withEnforcedReplies` which can cause some headache in setting up the command ADT. But I guess it's to late to change this particular aspect.

(As an experiment I tried to convert the type parameter of `ExpectingReply` to an abstract type to remove part of the boilerplate but that doesn't work with the current structure because then `ExpectingReply` cannot be implemented from Java, so separate types would need to be introduced.)
