### ISSUE TITLE
Upload Whitesource report from Travis tag build

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27015]
That way it's no longer in the critical path, can be retried when it fails, and we can set up the regex in the travis config to skip milestones.

It has currently been removed from the release script to avoid upload for milestones, see https://github.com/akka/akka/issues/26866

**Comment by raboof** [comment]
Checked with tag 2.6.0-M2: it will upload for aggregate project name `akka-adhoc`, so that is OK. Still updating travis to use stages and make it more easily controllable what is executed when, though.
