### ISSUE TITLE
Enable Scala 2.13 build for akka-serialization-jackson

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27019]
Had to exclude it from build because of missing dependency for the Jackson Scala module.

Depends on https://github.com/FasterXML/jackson-module-scala/issues/414

**Comment by patriknw** [comment]
Search for `FIXME #27019`

**Comment by patriknw** [comment]
Note from @dwijnand :
Make the crossScalaVersions of the root project Nil. For some reason that makes + correctly use project's different crossScalaVersions values.

**Comment by patriknw** [comment]
Seems like `+` doesn't work anyway. Can be reproduced with 
```
sbt -Dakka.genjavadoc.enabled=true -Dakka.build.version=timestamp +publishLocal
```

It's building with 2.13 but in `akka-serialization-jackson` it's looking for a 2.12 project dependency:
```
[error] (akka-serialization-jackson / update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor_2.12;2.6-20190527-061824: not found
[error] unresolved dependency: com.typesafe.akka#akka-actor-tests_2.12;2.6-20190527-061824: not found
[error] unresolved dependency: com.typesafe.akka#akka-testkit_2.12;2.6-20190527-061824: not found
```

I also tried to Nil crossScalaVersions in root project without any difference:
```
   lazy val rootSettings = Def.settings(
    crossScalaVersions := Nil,
```

We have another workaround, so it's not critical to be able to use `+` now.

**Comment by patriknw** [comment]
Change `akka-publish-nightly` to `+publish` again, when this issue has been fixed.

**Comment by raboof** [comment]
It looks like adding `crossScalaVersions := Nil` does not work when a subproject that doesn't support 2.13 (here: `akka-serialization-jackson`) depends on a subproject that does (here: `akka-actor`). (refs https://github.com/sbt/sbt/issues/3465, /cc @dwijnand).

**Comment by patriknw** [comment]
I have changed https://jenkins.akka.io:8498/job/akka-publish-nightly/ to use `+publish`
