### ISSUE TITLE
akka 2.5.23 (scala 2.13.0-RC2) doesn't work with Java 8

### ISSUE THREAD

**Issue by pjfanning** [akka/akka#27029]
Looks like akka was built using Java 11.

```
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.13.0-RC2/2.5.23/akka-actor_2.13.0-RC2-2.5.23.jar ...

[info] Running (fork) com.example.akka.Main 
[error] Exception in thread "main" java.lang.UnsupportedClassVersionError: akka/http/javadsl/model/RequestEntity has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
```

**Comment by patriknw** [comment]
Thanks for reporting, it is Akka HTTP not Akka core. We’ll look into if we have to release a new Akka HTTP but then it probably have to be a new patch version of all of it.

**Comment by raboof** [comment]
Indeed akka-http and spray-json RC2 artifacts only work with Java 11 at this point. We hope to support Java 8 again in the next release (either Scala 2.13.0 or Akka HTTP 10.1.9).

For Akka HTTP, for the time being you can use a snapshot version from https://bintray.com/akka/snapshots/com.typesafe.akka%3Aakka-http_2.11/ (don't mind the '2.11' in the URL).

**Comment by pjfanning** [comment]
Thanks for the prompt replies.
