### ISSUE TITLE
Migrate all SBT dependency configs in Dependencies.scala to LibraryManagementSyntax type vs string

### ISSUE THREAD

**Issue by helena** [akka/akka#27040]

**Comment by chbatey** [comment]
Might be good for hackathon instead

**Comment by jrudolph** [comment]
@helena Can you clarify or give an example in the description?

**Comment by helena** [comment]
@jrudolph 

from
`val commonsMath = "org.apache.commons" % "commons-math" % "2.2" % "test"`

to
`val commonsMath = "org.apache.commons" % "commons-math" % "2.2" % Test`

e.g. Test, Optional, Provided, whatever is the non string type version of a given dependency configuration.
It's a small change, not hackathon worthy IMO.

**Comment by jrudolph** [comment]
Ah, thanks, didn't know this syntax so far. Might still make a good thing for someone to get started with setting up Akka.

**Comment by jakeashdown** [comment]
Hi guys, I haven't contributed to Akka before and I'd like to take this ticket. That okay?

**Comment by jakeashdown** [comment]
Cool, I'll take a look

**Comment by helena** [comment]
The thing to consider here you'll have to rename a bit due to the internal `Dependencies.Test` object and sbt `Test` config.

**Comment by jakeashdown** [comment]
Sorry it's taken me a while to look at this - I'm working on an underpowered laptop which is unable to run sbt and intellij for this project at the same time. I'm now using `sbt -mem 6144` and editing with Atom, which works okay. Should have this done soon.

**Comment by sakshiganeriwal** [comment]
Hello everyone, 
Is someone already working on this?
I'd like to take this issue if no one is currently working. is that okay?

**Comment by helena** [comment]
Hi @sakshiganeriwal, thanks for your interest in it! We somehow let the current PR for it slide in review cycles but it's almost complete. We hope you find another that sounds good to contribute :)

**Comment by sakshiganeriwal** [comment]
sure. thanks. do you have any suggestions ?
it's my first time.

**Comment by helena** [comment]
One of these would be great:
https://github.com/akka/akka/issues/25468
https://github.com/akka/akka/issues/25467
Labels to look for are: good first issue, hackathon, help wanted (that are not marked in progress)

**Comment by GKuldeepak-Knoldus** [comment]
Hi Everyone, 
Have the issues been resolved, if not, can I pick this one?

**Comment by johanandren** [comment]
Someone was working on it in https://github.com/akka/akka/pull/27422 but that was never finished, so go ahead and pick it up.
