### ISSUE TITLE
Docs: Akka Typed Add example of how to java `getSelf` for persistence typed 

### ISSUE THREAD

**Issue by helena** [akka/akka#27061]
For usage of untyped `getSelf` migration to typed.

**Comment by helena** [comment]
@johanandren's input:
> more idiomatic: https://github.com/akka/akka/blob/v2.5.23/akka-persistence-typed/src/test/java/jdocs/akka/persistence/typed/BasicPersistentBehaviorTest.java#L331

> Make your persistent behavior have a context field and pass that from a static factory method using Behaviors.setup

**Comment by johanandren** [comment]
This should perhaps be extended outside of persistence to cover getting an `ActorContext` when using `AbstractBehavior` and then reference that from the persistence docs? And both for Scala and Java.

**Comment by johanandren** [comment]
Indeed. Not sure how we missed that.

**Comment by helena** [comment]
@patriknw That is the link I gave to someone inquiring on how to do this from Java. They'd not found it in the docs, maybe we need to make it more obvious? IDK.

**Comment by patriknw** [comment]
What I think we should do here is to document `ActorContext` more clearly in both Actor and EventSourcedBehavior documentation. How to access ActorContext and what things it provides, such as the `self` ref.

Regarding learning Typed for those that know Untyped we should have a guide (page) for that. Covered by https://github.com/akka/akka/issues/25624
Please add findings to that ticket (I added the `self` thing`)
