### ISSUE TITLE
Unit test always run the cluster and remoting service

### ISSUE THREAD

**Issue by xmeng1** [akka/akka#27076]
Please use https://discuss.akka.io for questions instead of posting them to the issue tracker.

When I run `sbt test`, the unit test always run the cluster:

```
akka.event.slf4j.Slf4jLogger - Slf4jLogger started
15:31:31.589 [com-deepnetsecurity-dcs-channel-ChannelRoutesSpec-akka.actor.default-dispatcher-2] [xin-deepnet] INFO  akka.remote.Remoting - Starting remoting
15:31:31.719 [com-deepnetsecurity-dcs-channel-ChannelRoutesSpec-akka.actor.default-dispatcher-4] [xin-deepnet] INFO  akka.remote.Remoting - Remoting started; listening on addresses :[akka.tcp://com-deepnetsecurity-dcs-channel-ChannelRoutesSpec@0.0.0.0:1600]
```

Then the test will fail by the Port already used, is there any method to prevent the remoting and cluster in the unit tests? or Just need to make the cluster port random when doing the unit test?

**Comment by chbatey** [comment]
@xmeng1 please use https://discuss.akka.io for questions instead of posting them to the issue tracker...
