### ISSUE TITLE
Convenience for including an actors termination in coordinated shutdown

### ISSUE THREAD

**Issue by jroper** [akka/akka#27089]
It would be nice to have a convenience method for including an actors termination in coordinated shutdown. Eg, something like this:

```scala
def addActorTerminationTask(phase: String, taskName: String, actor: ActorRef, stopMsg: Option[Any])
```

The idea would be the given `stopMsg` would be sent to the actor on shutdown if provided (in some cases, you might want to send the stop message in an earlier phase, but do the wait in a later phase, that's why the stop message should be optional), and then the given actor would be watched, and when it terminated, the task would be complete.

This saves needing to implement anything in the actor itself (eg, to hold a reference to the actor that sent the stop message and then send done in postStop to it), or having to write another actor to watch the termination if you don't want to pollute the stopping actors code.

**Comment by patriknw** [comment]
Excellent proposal. Would you be able to create a PR?

**Comment by jroper** [comment]
I can probably take a look at it. What should do the watching? A single actor that is shared between all actor termination shutdown tasks, or an actor instantiated per task? If a shared actor, how should it be managed? lazy val? Always instantiate it in the coordinated shutdown extension?

**Comment by patriknw** [comment]
What should do the watching? A single actor that is shared between all actor termination shutdown tasks, or an actor instantiated per task?

One shared actor sounds best.

 If a shared actor, how should it be managed? lazy val? Always instantiate it in the coordinated shutdown extension?

Can be created (lazy val) on first `addActorTerminationTask` call.
