### ISSUE TITLE
akka stream throws NPE when throttle a stream with delay

### ISSUE THREAD

**Issue by ChanglinZhou** [akka/akka#27095]
Exception:
[ERROR] [06/06/2019 16:09:22.900] [delay-akka.actor.default-dispatcher-4] [akka://delay/system/StreamSupervisor-0/flow-0-0-ignoreSink] Error in stage [Delay]: null
java.lang.NullPointerException
	at akka.stream.impl.fusing.Delay$$anon$7.nextElementWaitTime(Ops.scala:1724)
	at akka.stream.impl.fusing.Delay$$anon$7.onPull(Ops.scala:1704)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:422)

Code to reproduce:
```
import java.time.Instant

import akka.actor.ActorSystem
import akka.stream.{ActorMaterializer, DelayOverflowStrategy, OverflowStrategy}
import akka.stream.scaladsl.{Sink, Source}

import scala.concurrent.duration._

object DelayTest extends App {
  implicit val system = ActorSystem("delay")
  implicit val mat = ActorMaterializer()

  Source(1 to 2000)
    .throttle(100, 2 seconds)
    .map(x => {
      val now = Instant.now()
      println(s"n1 -- ${now} ${x}")
      x
    })
    //.buffer(10000, OverflowStrategy.backpressure)
    //.delay(5 seconds, DelayOverflowStrategy.backpressure)
    .delay(5 seconds, DelayOverflowStrategy.emitEarly)
    .map(x => {
      val now = Instant.now()
      println(s"n2 -- ${now}: ${x}")
      x
    })
    .throttle(50, 1.5 seconds)
    .runWith(Sink.ignore)
}
```

**Comment by johanandren** [comment]
Thanks for reporting and providing a reproducer!
