### ISSUE TITLE
akka streams API is missing a zipAll method

### ISSUE THREAD

**Issue by eyalfa** [akka/akka#27103]
akka stream's API does have zip and zipWith methods, however it lacks the zipAll operator.
as a reference scala's IterableLike has this method with this signature:

def zipAll[B, A1 >: A, That](that: GenIterable[B], thisElem: A1, thatElem: B)(implicit bf: CanBuildFrom[Repr, (A1, B), That]): That

it basically performs a zip operations, right-padding the shorter side with a default value.

I'd like to see such an operator on akka streams (I was quite surprised not to see it) as it'd follow the API scala developers are used to get from collections (which seems to be a design principle in stream's API design).

**Comment by eyalfa** [comment]
This implementation 'almost' works, seems to be functioning but it confuses idea + scala compiler, forcing me to cast the resulting stream (otherwise it treats it like an escaped local type)
```
implicit class FlowZipAllSupport[Out, Mat](val self : FlowOps[Out, Mat]){
    def zipAll[U, A1 >: Out](that: Graph[SourceShape[U], _], thisElem: A1, thatElem: U) : self.Repr[(A1, U)] = {
      def infSrc[T](x : T) = Source.repeat(Right(x) : Either[T, T])
      val selfExtended = self.map(Left.apply/*[A1, A1]*/ _).concat( infSrc(thisElem) )
      val otherExtended = Source.fromGraph(that).map(Left.apply _).concat( infSrc(thatElem) )

      selfExtended
        .zip(otherExtended)
        .takeWhile{
          case (l,r) => l.isLeft || r.isLeft
        }
        .map{
          case (l,r) => (l.merge, r.merge)
        }
    }
  }
```

if this is acceptable by the maintainer, I'm willing to submit a PR introducing this in FlowOps.

**Comment by eyalfa** [comment]
cc @ktoso

**Comment by johanandren** [comment]
We aim to cover what is useful in a stream scenario, and make those behave/have names like the collection APIs, rather than try to be complete covering all methods. 

I think this could make sense though. Can you give some concrete use case when this operator is useful?

If we decide we need it, we should probably avoid the allocation of two extra Left/Right per element.

**Comment by eyalfa** [comment]
my use case involves slick,
we have a db schema with several one-to-many relations, in order to simplify the data-access-layer we've decided to convert some of our joins into 'client-side' joins. 
when querying by PK this is rather easy,  however when querying for multiple records it becomes a bit tricky as we rely on sort-order and zip everything together. we've used slick's stream ability to implement the second kind of records (followed by `splitWhen` and some logic on the subflow).
I hope this explains the need for `zip`, in this case `zipAll` is a safer version of `zip` as it'd allow us to identify error scenarios.

**Comment by johanandren** [comment]
Thanks for describing a use case. I think we should add such an operator. Would you be up for contributing it? 

I think it'd require a custom graph stage rather than combining existing operators.

**Comment by eyalfa** [comment]
@johanandren , I'm up to it but I think reusing existing stages is a better approach. 
I can already think of a way to get rid of the Left/Right objects allocations per item.

I'd craft an initial PR and in case the 'indirect' approach doesn't cut it I'll give a stub at a custom graph stage (that'd be my first).

**Comment by johanandren** [comment]
Sounds good!
