### ISSUE TITLE
Memory Leak in Long running stream related to MergeHub(AbstractNodeQueue)

### ISSUE THREAD

**Issue by architmmmec** [akka/akka#27111]
Memory Leak in Long running stream related to AbstractQueueNode in MergeHub.
![image](https://user-images.githubusercontent.com/37949198/59174153-d6072780-8b6d-11e9-89d9-afa2af5b4279.png)

![image](https://user-images.githubusercontent.com/37949198/59174156-d99aae80-8b6d-11e9-88a8-b54981ade4c9.png)

Can someone help here?

**Comment by patriknw** [comment]
@architmmmec Thanks for reporting. Do you have a way to reproduce the problem that we can try? A sample application or test? The smaller the better.

**Comment by architmmmec** [comment]
val source: Source[T, Sink[T, NotUsed]] = MergeHub.source[T]
  val sink = Sink.ignore
  val flowGraph: Flow[T, T, NotUsed]
  override def streamGraph: RunnableGraph[(Sink[T, NotUsed], Future[Done])] = 
  RunnableGraph.fromGraph(
    GraphDSL.create(source, sink)((_, _)) { implicit builder =>
      (mergeHubSource, sink) =>
        import GraphDSL.Implicits._

        mergeHubSource ~> killSwitch.flow[T] ~> unBatch ~> flowGraph ~> sink

        ClosedShape
    })

**Comment by architmmmec** [comment]
@patriknw Please see the code, you can reproduce using it

**Comment by patriknw** [comment]
thanks, we will look into it

**Comment by johanandren** [comment]
I'm afraid that is not a complete reproducer, it would be good if you could share something complete that compiles and runs and reproduces the memory leak.

If you can't do that, answering these questions would be useful:
 * How many materialized upstreams did you have when you saw this OOM?
 * Were the upstreams short lived?
 * Where the upstreams still alive (could there be a leak of upstreams in your app rather)?

**Comment by patriknw** [comment]
@architmmmec will you be able to provide more information?

**Comment by johanandren** [comment]
Closing this because lack of feedback, we can open it up again if a runnable reproducer is provided.
