### ISSUE TITLE
Akka Http Stream errorakka.stream.StreamTcpException: Tcp command [Connect(url:80,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired

### ISSUE THREAD

**Issue by ashishsahuGitHub** [akka/akka#27113]
Hi ,
I am using the Akka Http Single request to get the json data from rest service and post this data to another service.
akka_actor='2.4.16', akka_http='10.1.8', akka_stream='2.5.22'.

val responseFuture: Future[HttpResponse] =   Http(actorSystem).singleRequest(  HttpRequest(
          HttpMethods.POST, xyzUrl,  List(auth),  entity = HttpEntity(ContentTypes.`application/json`, geoJsonFeatures).withoutSizeLimit(),  ), settings = settings  )

To handle this tcp timeout issue below settings is provided in singleRequest
  val orig = ConnectionPoolSettings(actorSystem.settings.config).copy(idleTimeout = 60 seconds)
  val clientSettings = orig.connectionSettings.withIdleTimeout(60 seconds)
  val settings = orig.copy(connectionSettings = clientSettings)

Below is error log

 ERROR[ClsToXyzProSpaceActor-akka.actor.default-dispatcher-34] AkkaConsumerGeoJsonXYZProSpace$ - Stream errorakka.stream.StreamTcpException: Tcp command [Connect(xyzUrl:80,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired
akka.stream.StreamTcpException: Tcp command [Connect(xyzUrl:80,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired
Caused by: akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired

Can anyone Pls let me know what else i can do so i can overcome from this issue

**Comment by johanandren** [comment]
Hi @ashishsahuGitHub, we try to use the issue tracker only for issues and feature-tracking, please use the [forums](https://discuss.akka.io) or the [gitter channel](https://gitter.im/akka/akka) for questions like this, thanks!
