### ISSUE TITLE
Mailbox selector props in Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27124]
Missing a way to select mailbox via `Props`. Would be good to provide a few simple choices such as `MailboxSelector.bounded(capacity = 1000)`.

**Comment by johanandren** [comment]
The original unadapted typed actors defaulted to bounded, could it make sense to go with that as a default again when you can change it to unbounded with props? I think that was a pretty good idea, but maybe it is too big a change of default behavior?

**Comment by patriknw** [comment]
It’s a nice idea but I don’t think it’s practically possible to have to always think about that messages can be lost also for local actors. What would a good mailbox capacity be when you have thousands of actors?

**Comment by johanandren** [comment]
Good point
