### ISSUE TITLE
Allow to specify log level in SupervisorStrategy.withLoggingEnabled in Akka Typed

### ISSUE THREAD

**Issue by JakubKahovec** [akka/akka#27133]
Currently when logging gets enabled on the SupervisorStrategy  in Akka Typed all exceptions are being logged with the error level. It would be pretty useful to allow specifying a log level as an argument of the method withLoggingEnabled e.g `SupervisorStrategy.restart.withLoggingEnabled(true, Logging.WarningLevel)`

**Comment by patriknw** [comment]
Good idea. Maybe it should be a separate method from `withLoggingEnabled`, such as `withLogLevl(level: LogLevel)`?

@JakubKahovec Would you be able to create a pull request for this feature?

**Comment by JakubKahovec** [comment]
Ok, will create a pull request with the separate `withLogLevel(level: LogLevel)`  method
