### ISSUE TITLE
PersistAsync effect for Akka Persistence Typed

### ISSUE THREAD

**Issue by RibleStrype** [akka/akka#27132]
Currently "Akka Persistence Typed" doesn't seem to have an analogue for `persistAsync()` functionality of untyped "Akka Persistence". Such feature would be very nice to have

**Comment by patriknw** [comment]
That is by design, because `persistAsync` is very difficult to reason about correctly. We'll not add that feature to `EventSourcedBehavior`. If we would add something similar it would probably have a completely different shape and purpose than `EventSourcedBehavior` such as Stream persistence.
