### ISSUE TITLE
Docs around roles in typed sharding 

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27149]
For typed sharding we created a simpler api where it is always started with `ClusterSharding.init` and looking at the specified role to decide if the node should have a shard region or a proxy. We missed out on adding docs for that though: 
https://doc.akka.io/docs/akka/2.6.0-M3/typed/cluster-sharding.html

**Comment by patriknw** [comment]
While doing this we should see if we can add a shortcut for defining the `role`, since that is probably the most common reason for needing to grab for settings.

Instead of:
```
      Entity(AccountEntity.TypeKey, ctx => AccountEntity(ctx.entityId))
        .withSettings(ClusterShardingSettings(system).withRole("MyRole")))
```

maybe:
```
      Entity(AccountEntity.TypeKey, ctx => AccountEntity(ctx.entityId))
        .withRole("MyRole")))
```
