### ISSUE TITLE
Publish akka-stream-typed 2.5.23 for Scala 2.11

### ISSUE THREAD

**Issue by liff** [akka/akka#27143]
The `akka-stream-typed` has not seen releases for Scala 2.11 [since 2.5.21](https://search.maven.org/search?q=g:com.typesafe.akka%20AND%20(a:akka-actor_2.11%20OR%20a:akka-slf4j_2.11%20OR%20a:akka-camel_2.11%20OR%20a:akka-remote_2.11%20OR%20a:akka-contrib_2.11%20OR%20a:akka-stream_2.11%20OR%20a:akka-stream-typed_2.11%20OR%20a:akka-testkit_2.11)).

Could the module be published for 2.11 as well, to align with recent release of modules [for Scala 2.13](https://search.maven.org/search?q=a:akka-stream-typed_2.11%20OR%20a:akka-stream-typed_2.13)?

I ran `++2.11.12! akka-stream-typed/test` on v2.5.23 tag and it seems to pass.

**Comment by chbatey** [comment]
Hi @liff we're not supporting akka typed on 2.11
