### ISSUE TITLE
Change in default behavior for ssl-config library on Scala 2.13

### ISSUE THREAD

**Issue by chbatey** [akka/akka#27142]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/196/consoleFull

```
[info] - must verify hostname *** FAILED *** (82 milliseconds)
[info]   Expected exception java.lang.Exception to be thrown, but no exception was thrown (TlsSpec.scala:517)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
[info]   at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:61)
[info]   at org.scalatest.Assertions.intercept(Assertions.scala:824)
[info]   at org.scalatest.Assertions.intercept$(Assertions.scala:804)
[info]   at akka.testkit.AkkaSpec.intercept(AkkaSpec.scala:61)
[info]   at akka.stream.io.TlsSpec.$anonfun$new$37(TlsSpec.scala:517)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.io.TlsSpec.$anonfun$new$36(TlsSpec.scala:505)
```

**Comment by chbatey** [comment]
Confirmed that his only fails on 2.13 and it fails consistently

**Comment by chbatey** [comment]
Failing on 2.13 because the behaviour of ssl-config changed between 0.3.7 (one we use for 2.12.x) and 0.4.0 (one for 2.13.x) in that now the default is to do no hostname verification by default

**Comment by chbatey** [comment]
Calling this a bug for now (feel free to remove) as changing TLS options based on Scala version is very surprising

**Comment by chbatey** [comment]
I'll revert this to go back to 0.3.8 for both 2.5 and 2.6 and we'll need to add something to the release notes for 2.5.24 to say that it is the first version that binary backward compat is supported for 2.13

**Comment by raboof** [comment]
If I understand https://github.com/lightbend/ssl-config/issues/100 correctly `DefaultHostnameVerifier` was retired because it should be replaced with `sslParams.setEndpointIdentificationAlgorithm("HTTPS")` I didn't realize that needs to be done in user code. I have added a note to https://github.com/lightbend/ssl-config/releases/tag/v0.4.0 .

Perhaps we should 'roll forward' and use `sslParams.setEndpointIdentificationAlgorithm("HTTPS")` for this in Akka as well?

**Comment by chbatey** [comment]
> Perhaps we should 'roll forward' and use sslParams.setEndpointIdentificationAlgorithm("HTTPS") for this in Akka as well?

The TLS flow is also for non-HTTP so not sure we can do this

Given that DefaultHostnameVerifier in ssl-config version 0.4.0 has been removed I think we should stick on 0.3.7 until we decide what to do as default for TLS.

**Comment by raboof** [comment]
ssl-config 0.4.x is OK since #27766
