### ISSUE TITLE
Missing reply for InitJoin message

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27169]
`IntiJoin` message changed from companion message to case class with config parameter when the join compat check was added. Some `case InitJoin =>` were not changed. Resulting in unhandled `InitJoin` and no `InitJoinNack` replies. This may result in that it takes longer time to join than necessary.

Detected by failing `DeterministicOldestWhenJoiningSpec`

**Comment by helena** [comment]
Sorry forgot to add milestone and close after merge.
