### ISSUE TITLE
Cluster sharding state warmup with health check

### ISSUE THREAD

**Issue by chbatey** [akka/akka#27168]
When a new node is added to a cluster using cluster sharding, if user requests are initially routed to it then each of them will incur a latency penalty as the `ShardRegion` gets the `Shard` location from the `ShardCoordinator`. This is for all `Shard`s, not just the ones that will be moved.

The `ShardCoordinator` could instead send the current regions per shardId to the `ShardRegion` when it registers and a health check could be exposed (https://doc.akka.io/docs/akka-management/current/healthchecks.html) to prevent user traffic being routed to the node in environments like Kubernetes until this has happened.

This might help #30315.

/cc @jroper

**Comment by jroper** [comment]
I think this would be really helpful in elastic environments, thanks for raising!

**Comment by milanvdm** [comment]
Is there any progress on this? Since we deploy on ECS (which shuts down the oldest containers first), we have a lot of movement of our ShardCoordinator during a redeploy.
We would like to find a way to know when to route requests to the new nodes.

**Comment by patriknw** [comment]
One way would be to reply with all shard locations when the region register to the coordinator. I think it's better to add a separate message for this. Then it can maybe be used in other situations like https://github.com/akka/akka/issues/29589

It could be many shards, and might not fit in one single message, but we can split it several smaller.

**Comment by patriknw** [comment]
The health check was added in https://github.com/akka/akka/pull/29638
