### ISSUE TITLE
Typed StashBuffer, allign with other factory methods on Behaviors?

### ISSUE THREAD

**Issue by chbatey** [akka/akka#27198]
We have `Behaviors.withTimer`, `Behaviors.setup` etc where as stash buffers are instantiated independently and the `ActorContext` passed into `unstash`. The stash buffer isn't thread sage and isn't meant to be shared across different `ActorContext`s so passing it in multiple times is misleading. A few alternative options:

* Align with other parts of the API e.g. `Behaviors.withStashBuffer`
* Have a method on ctx to create it
* Pass ctx into the apply/ctr

**Comment by patriknw** [comment]
I vote for Behaviors.withStash to align with other things.
