### ISSUE TITLE
Persist-and-forget API for PersistentActor

### ISSUE THREAD

**Issue by enzief** [akka/akka#27197]
It could be useful and more intuitive to have API that only persists Actor events without handlers. For the current API we'll have to pass a no-op `() => ()` as the event handler for this usecase which creates unwanted garbage and unnatural code.
Suggestions:
- Add fire-and-forget variants to `persist`*, which don't queue up no-op handlers
```scala
def persistAndForget[A](a: A): Unit
def persistAllAndForget[A](as: List[A]): Unit
...
```
- On par with those, remove the obligatory event argument in `defer`* as they're not useful:
```scala
def defer(f: () => Unit): Unit
```

**Comment by johanandren** [comment]
I agree, however we won't change or add things to the `PersistentActor` API moving forward. With the new typed API, `EventSourcedBehavior` you can simply return a `Effect.persist(event)` without providing any no-op functions.
