### ISSUE TITLE
Add WatchedWith effect in akka typed BehaviorTestkit

### ISSUE THREAD

**Issue by kpritam** [akka/akka#27190]
Currently Akka actor typed testkit support Watched effect but this does not cover a use case of `watchWith[T](msg: T)` API.

should there exist new effect called `WatchedWith[T](msg: T)`?

**Comment by johanandren** [comment]
Indeed. Would you be up for doing a PR adding it?

**Comment by kpritam** [comment]
Sure, ll submit PR.
