### ISSUE TITLE
Typed: remote actor discovery without cluster

### ISSUE THREAD

**Issue by TisonKun** [akka/akka#27203]
In the untyped world, developers can set up a remote actor provider and build systems on multi machines without involving akka-cluster.

If one wants to discovery remote actors, he can use `actorSelection` for looking up an untyped actor by its address.

However, in the typed world, actors discovery is implemented with `Receptionist` mechanism. And for remote scenario, `Receptionist` only works in a cluster. Thus one cannot discovery remote actors without involving akka-cluster. This is worse when application maintains its own cluster and does not want to build on akka-cluster requiring maintaining two cluster abstractions.

Roughly thinking, in such scenario one can still look up actors by its address and an additional type checking phase(which, seems be announced as anti-pattern). Anyway it would be better for an actor discovery mechanism in with "remote" provider and without "cluster" involved.

cc @jrudolph @patriknw @hepin1989 

references
[1] https://github.com/akka/akka/issues/23634
[2] https://doc.akka.io/docs/akka/current/typed/actor-discovery.html

**Comment by patriknw** [comment]
One idea is that we would provide a way to identify a Receptionist ActorRef at a given remote address. Then the ordinary message protocol of the Receptionist can be used from there.

**Comment by TisonKun** [comment]
@patriknw In this way there is a problem that different Receptionist on different actor system has different actors registered. In akka-cluster-typed we use distributed data for a consistent view of actor registered among actor systems. If we just identify a remote Receptionist and communicate to it, we should also carefully handle that which actor has registered on which Receptionist.

Let's say if actor-1 want to look up actor-2 remotely, since actor-2 only receive MsgType2, we can expand actor selection protocol a field, the message type. When identify an actor, also verify the type matched, and if mismatched, do not include the actor in the selection. WDYT?

**Comment by TisonKun** [comment]
@patriknw any thoughts?

**Comment by patriknw** [comment]
I don't have cycles for this now. We are wrapping up for the 2.6 release. I will come back to this in a few weeks.

**Comment by TisonKun** [comment]
Thanks for your reply :-)

**Comment by TisonKun** [comment]
Now I think I get your idea that we provide a mechanism that only verify `Receptionist` so that we keep type safe without runtime checker. It works like we firstly known where the `Receptionist` is, as we know the address of target actor in actor selection; connect to the `Receptionist` and send `Find` or other message to the `Receptionist` for working as we do in local scenario.

**Comment by patriknw** [comment]
Thinking some more about this I think my previous proposal makes sense:

> One idea is that we would provide a way to identify a Receptionist ActorRef at a given remote address. Then the ordinary message protocol of the Receptionist can be used from there.

Maybe with an additional limitation to only support `Receptionist.Find`, and not `Receptionist.Subscribe`. The reason for that is that we recommend against using watch outside of the Cluster boundary (it's even disabled for that by default in Akka 2.6), and watch is needed to avoid subscription leaks.

**Comment by patriknw** [comment]
Since we recommend against using Akka remoting without Akka Cluster we shouldn't add API to encourage that usage. If you still want to use it like that you can use:
```
system.toClassic.actorSelection
```

That can even be used for sending the `Receptionist.Find` message to the known address and path.

**Comment by TisonKun** [comment]
Thanks for your update! I think then this issue can be closed. One more question, how to build address of Receptionist of ActorSystem-B in ActorSystem-A?

**Comment by patriknw** [comment]
> how to build address of Receptionist of ActorSystem-B in ActorSystem-A?

Given a Typed ActorContext, something like this:
```
import akka.actor.AddressFromURIString
import akka.actor.typed.scaladsl.adapter._
val otherAddress = AddressFromURIString("akka://OtherSystem@otherHost:2552")
val otherReceptionistPath = context.system.receptionist.path.toStringWithAddress(otherAddress)
context.toClassic.actorSelection(otherReceptionistPath) ! Receptionist.Find(key, context.self)
```

**Comment by TisonKun** [comment]
Verified. Thanks for your information @patriknw!

Closed as won't do.

**Comment by TisonKun** [comment]
@patriknw it seems we cannot get classic context from type context since the `classicActorContext` method is private now?

**Comment by TisonKun** [comment]
Well, `import akka.actor.typed.scaladsl.adapter._` would make it work.
