### ISSUE TITLE
Cluster Sharding: Ensure shard optimization and availability

### ISSUE THREAD

**Issue by helena** [akka/akka#27215]
Ensure shard optimization and availability 
* shard assignment / allocation to nodes are optimal
* maximum number of shards are available for a data type at any given time
* verify capacity
   - if enough to add new shards on a node
   - remaining capacity of a node

**Comment by chbatey** [comment]
Shard allocation is pluggable do we need to do more? I think we should convert this issue to a very specific new shard allocator or close.

**Comment by helena** [comment]
@chbatey Ok. Originally I had something specific in mind but don't recall.

**Comment by helena** [comment]
Closing for new more specific.
