### ISSUE TITLE
Docs cleanup for 2.6

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27223]
* [x] Delete Utilities/Duration https://github.com/akka/akka/pull/27450
* [x] Move Coordination to Cluster https://github.com/akka/akka/pull/27451
* [x] Collapse Project Information and Additional Information https://github.com/akka/akka/pull/27484
* [x] Remove HowTo: Common Patterns https://github.com/akka/akka/pull/27485
* [x] Move things to new Package/Deploy/Run section https://github.com/akka/akka/pull/27550
* [x] Mention Telemetry in Package/Deploy/Run. https://github.com/akka/akka/pull/27486
* [x] Move Cluster Specification to main Cluster section (not specific to Classic) https://github.com/akka/akka/pull/27451
* [x] Mailboxes https://github.com/akka/akka/pull/27493 and Dispatchers https://github.com/akka/akka/pull/27494 to main Actors section (not specific to Classic)
* [x] https://github.com/akka/akka/pull/27593 Setting the dispatcher for an Actor section
* [x] 'Blocking needs careful management' section https://github.com/akka/akka/pull/27498
* [x] https://github.com/akka/akka/pull/27593 'CallingThreadDispatcher' section?
* [x] Move Persistence Query, Schema Evolution, Storage backend to main Persistence section (not specific to Classic) https://github.com/akka/akka/pull/27451
* [x] "Persistence" comes before "Akka Cluster" (and therefore "Cluster Sharding") in the ToC, but references how it's used with Cluster Sharding. Maybe better to present in the reverse order? https://github.com/akka/akka/pull/27451

**Comment by raboof** [comment]
> Move things to new Package/Deploy/Run section

Hmm, what 'things' were we thinking of?

**Comment by patriknw** [comment]
> Move things to new Package/Deploy/Run section

I think we had things spread out in different sections, but maybe most of it has already been moved. One remaining might be "Rolling Updates and Versions" in "Project Information", but maybe that belongs together with migration guides now.

**Comment by helena** [comment]
> One remaining might be "Rolling Updates and Versions" in "Project Information", but maybe that belongs together with migration guides now.

Yes that part is there still be design, it should only specify version-specific changes (e.g. wire protocol changes) related to rolling updates from overall rolling update information and strategies.

@raboof I was wondering the same, and there were, for instance, a few rolling update mentions last I checked here are there, I think in persistence, sharding, and perhaps serialization? But the ones in the migration guide IMO should remain OR perhaps be linked to. Hrm, I like that actually, will PR it to see what we think.

**Comment by helena** [comment]
@patriknw @raboof one idea regarding Move things to new Package/Deploy/Run section: https://github.com/akka/akka/pull/27550

**Comment by helena** [comment]
One idea: schema evolution topic by consolidation 
https://github.com/akka/akka/pull/27551

**Comment by patriknw** [comment]
> CallingThreadDispatcher' section?

Not sure what was intended here. I think it should be only be mentioned in Classic test kit docs (maybe that is already the case?)
