### ISSUE TITLE
Consider adding Scala Steward

### ISSUE THREAD

**Issue by helena** [akka/akka#27228]
https://github.com/fthomas/scala-steward to keep Scala projects up-to-date
Came up here: https://github.com/akka/akka/pull/27225#pullrequestreview-254916810

**Comment by fthomas** [comment]
You can see a preview of the pull requests Scala Steward would create here in my own Akka fork: https://github.com/fthomas/akka/pulls

**Comment by raboof** [comment]
Thanks for that! Huh, it seems like it's not picking up any of our dependencies in `project/Dependencies.scala`. In this case that's actually what we want (only automatically update `project/plugins.sbt` and perhaps test dependencies), but should we add some configuration to exclude `project/Dependencies.scala` in case it gets improved in the future?

**Comment by fthomas** [comment]
It hasn't created PRs for dependencies in `project/Dependencies.scala` because `sbt dependencyUpdates` (from sbt-updates) didn't report any updates for those. This is strange. I've looked at the build, but couldn't figure out why it doesn't report any updates except ones for `scala-*`. @raboof Does `sbt dependencyUpdates` reports updates for you?

**Comment by 2m** [comment]
It depends on the subproject. For example `akka-actor` does not report anything more than Scala updates:
```
akka > akka-actor/dependencyUpdates
[info] Found 2 dependency updates for akka-actor
[info]   org.scala-lang.modules:scala-java8-compat : 0.8.0  -> 0.9.0
[info]   org.scala-lang:scala-library              : 2.12.8 -> 2.13.0
```

But, for example, `akka-stream` reports more:
```
akka > akka-stream/dependencyUpdates
[info] Found 3 dependency updates for akka-stream
[info]   com.typesafe:ssl-config-core : 0.3.8           -> 0.4.0
[info]   org.scala-lang:scala-library : 2.12.8          -> 2.13.0
[info]   org.scalatest:scalatest:test : 3.0.7  -> 3.0.8
```

Does scala-steward run for all sub-projects?

**Comment by fthomas** [comment]
Not for me:
```
akka > akka-stream/dependencyUpdates
[info] Found 1 dependency update for akka-stream
[info]   org.scala-lang:scala-library : 2.12.8 -> 2.13.0
[success] Total time: 16 s, completed Jul 17, 2019 12:29:20 PM
```
I guess your environment is different from mine. Does the build requires credentials that I haven't set, but which are set in your environment?

**Comment by 2m** [comment]
Interesting. I am using quite an old `sbt-updates` plugin (`0.3.4`) in my local setup. It looks like the latest version of `sbt-updates` (`0.4.1`) do not report those updates anymore.

**Comment by fthomas** [comment]
I can confirm that. Version 0.3.4 reports updates but 0.4.0 and 0.4.1 doesn't. @rtimush, do you have any idea why this is happening?

**Comment by rtimush** [comment]
It looks like a bug introduced when implementing https://github.com/rtimush/sbt-updates/issues/42 the idea was to exclude dependencies added by other sbt plugins, but apparently, it also excluded dependencies defined in `project/*.scala` files. I will fix it.

**Comment by rtimush** [comment]
@fthomas I just published `sbt-updates` 0.4.2 that detects updates for dependencies defined in `project/Dependencies.scala` correctly.

**Comment by fthomas** [comment]
Many thanks for the quick fix, @rtimush!

https://github.com/fthomas/akka/pulls has now 17 more PRs. :-)

**Comment by helena** [comment]
I see (as of yesterday) `sbt dependencyUpdates` reporting updates though for example strange output for Kamon Sigar loader, which has it's own oddities in versioning.

**Comment by raboof** [comment]
Yeah we might want to exclude that one.

**Comment by helena** [comment]
I think it is time to close this - we've added Scala Steward.
