### ISSUE TITLE
Allow shutting down children created using SpawnProtocol

### ISSUE THREAD

**Issue by kpritam** [akka/akka#27227]
We have `ActorSystem[SpawnProtocol]` which is used to spawn actors in user space.
But currently there is no way for me to shutdown actors created using `Spawn` message.
Should `SpawnProtocol` include other messages like below ?

- `ShutdownChild(actorRef: ActorRef[T])` - shutdowns provided actorRef
- `ShutdownChild(actorName: String)` - shutdowns actor matching provided name
- `ShutdownChildren()` - shutdowns all the children created in user namespace

**Comment by patriknw** [comment]
Can't you send a stop message to the actors themselves and they can stop when receiving that message?

**Comment by kpritam** [comment]
We are building framework where we expect different parts of code will spawn required actors.
Every such a piece of code will take care of Actor's lifecycle.

But ultimately in the end we want to shutdown everything, there we want to stop all the actors created using this actor system.
With the approach you have suggested, we have to introduce `Stop` message and every actor needs to handle that. We might not have control over enforcing that constraint.
It is fine in this case, if we shutdown all the children as system is going down and it is ok if actor gets terminated even though it has some messages left in its inbox.

**Comment by patriknw** [comment]
if it's only about stopping all actors when the ActorSystem is shutting down then that is already done automatically

**Comment by kpritam** [comment]
What if one of the actor is processing some message, does this wait for actor to finish processing that message and also invokes stop signals of terminating actors?

**Comment by patriknw** [comment]
Current message is processed before the actor can be stopped, and that will also "delay" the shutdown of the ActorSystem. Messages in the actor's mailbox will not be processed. PostStop signals will be emitted.

**Comment by kpritam** [comment]
Thanks @patriknw, this will help us.
Still feels `ShutdownChild` API is missing from `SpawnProtocol`.
Feel free to close this if you think giving `ShutdownChild` API is risky.

**Comment by johanandren** [comment]
I think we rather keep the spawn protocol as simple as possible and recommend users to have graceful stop messages as part of their protocols. If you have more advanced requirements and or disagree about the stop messages, I think it is easy enough to build your own spawn protocol behavior that you can adapt to whatever requirements you have. Take a look at the implementation, it is no more than somewhere around 30 lines of code so easy to grasp and take inspiration from https://github.com/akka/akka/blob/4729a80e7e6f2923a7e6369b21b2693f82c64589/akka-actor-typed/src/main/scala/akka/actor/typed/SpawnProtocol.scala

Thanks for taking the time to discuss though!
