### ISSUE TITLE
Missed line in documentation's snippet

### ISSUE THREAD

**Issue by demwis** [akka/akka#27232]
Hi, guys.

I think, there is missed a code line in the documentation snippet.
https://github.com/akka/akka/blob/v2.5.23/akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java#L57-L59
(https://doc.akka.io/docs/akka/current/typed/guide/tutorial_1.html):
```
  private StartStopActor1() {
    System.out.println("first started");
  }
```

There should be presented a line, which spawns StartStopActor2, I guess.

Best regards,
Dmitriy

**Comment by johanandren** [comment]
It is created in the snippet below it, which calls the static `createBehavior()` method.
