### ISSUE TITLE
Akka Remote fails to discover Serializer in complex production projects with many dependencies

### ISSUE THREAD

**Issue by degloff** [akka/akka#27238]
I described this problem already on [Stackoverflow](https://stackoverflow.com/questions/56819983/akka-remote-producing-weird-java-lang-abstractmethoderror).

To understand more what is going on I analyzed our project more with the maven dependency tool and debugged into it. Here my findings:

We have dependencies to several Apache big data projects, including Apache Beam, which pulls in Akka in version 2.4.x. However the dependency tree shows me that everywhere Akka 2.5.23 is choosen. This seems to be fine. Comments welcome. 

Then I debugged side by side two projects, a minimal one that works with only the required Akka dependencies and I moved the same working code into our production project, with exact same Akka configs. 

The main difference happens here where a RemoteActorRefProvider in ActorSystem.scala is created:

```
  val provider: ActorRefProvider = try {
    val arguments = Vector(
      classOf[String] -> name,
      classOf[Settings] -> settings,
      classOf[EventStream] -> eventStream,
      classOf[DynamicAccess] -> dynamicAccess)

    dynamicAccess.createInstanceFor[ActorRefProvider](ProviderClass, arguments).get
  } catch {
    case NonFatal(e) =>
      Try(stopScheduler())
      throw e
  }

```

In the minimal project that works the RemoteActorRefProvider has a field `serializationInformationCache` (but still set to null, I guess it is loaded later). However this field is entirely missing in the large project that fails. 

This points me to the hypothesis that there is some weird dependency problem going on. How can I debug that? Is there a way to see what Akka is loading? I also stepped through the code 

````
 override def createInstanceFor[T: ClassTag](clazz: Class[_], args: immutable.Seq[(Class[_], AnyRef)]): Try[T] =
    Try {
      val types = args.map(_._1).toArray
      val values = args.map(_._2).toArray
      val constructor = clazz.getDeclaredConstructor(types: _*)
      constructor.setAccessible(true)
      val obj = constructor.newInstance(values: _*)
      val t = implicitly[ClassTag[T]].runtimeClass
      if (t.isInstance(obj)) obj.asInstanceOf[T]
      else throw new ClassCastException(clazz.getName + " is not a subtype of " + t)
    }.recover { case i: InvocationTargetException if i.getTargetException ne null => throw i.getTargetException }
```

in ReflecitveDynamicAccess.scala, line 27, but did not get any further understanding. 

Any help to sort out the problem is greatly appreciated.

**Comment by chbatey** [comment]
> We have dependencies to several Apache big data projects, including Apache Beam, which pulls in Akka in version 2.4.x. However the dependency tree shows me that everywhere Akka 2.5.23 is choosen. This seems to be fine. Comments welcome.

Also worth checking this holds true for your runtime environment. How do you package and deploy the app and what is its classpath. Mixed versions aren't supported and will cause issues that are hard to diagnose. The latest Akka checks versions loaded have the same module version unless that information is lost due to creating a fat jar (it is in each jar's manifest).

> In the minimal project that works the RemoteActorRefProvider has a field serializationInformationCache (but still set to null, I guess it is loaded later). However this field is entirely missing in the large project that fails.

At runtime in a debugger? 

Another thing that could be going wrong is config merging.  You can set `akka.log-config-on-start = on` to check that your serializer config has made it as well as all of akka's defaults.

I think this issue is better discussed at https://discuss.lightbend.com/c/akka and we can create an issue if we find an issue in Akka.
