### ISSUE TITLE
Flow[Int].map doesn't resolve in IntelliJ

### ISSUE THREAD

**Issue by pascalwhoop** [akka/akka#27235]
When copying the code [from here](https://doc.akka.io/docs/akka/current/stream/stream-composition.html#composing-complex-systems) and importing all the dependencies, `Flow[T].map` doesn't work.

![image](https://user-images.githubusercontent.com/2284951/60286097-56b87880-990f-11e9-99c9-841a02d7b98e.png)

I've been trying to build a composite sink but can't get it to work so I thought I'd try to just C/P the code from the example. But that also doesn't work. So, no idea what's going on

**Comment by pascalwhoop** [comment]
Careful for anyone else who stumbles on this: IntelliJ offers always the JavaDSL and ScalaDSL. I apparently accidentially imported the javaDSL `Flow`.

**Comment by pascalwhoop** [comment]
closing but not deleting in case someone hits this on Google

**Comment by patriknw** [comment]
I’d recommend setting up filters in the IDE: https://doc.akka.io/docs/akka/current/additional/ide.html
