### ISSUE TITLE
Retry flow promotion from akka-stream-contrib

### ISSUE THREAD

**Issue by 2m** [akka/akka#27230]
This ticket is to collect various requests around `Retry` flow API and for the discussion on the promotion of [`Retry.concat`](https://github.com/akka/akka-stream-contrib/blob/master/src/main/scala/akka/stream/contrib/Retry.scala#L84) with some modifications to akka-stream module.

There are a couple of features that are missing in the current implementation:

* back-off (implemented ad-hoc in an [open Alpakka DynamoDb PR](https://github.com/akka/alpakka/pull/1712/files) and [request ticket in akka/akka](https://github.com/akka/akka/issues/27044)). Improved `Retry` flow could support the same back-off parameters as `RestartSource/Flow`: `minBackoff`, `maxBackoff` and `randomFactor`.
* expose the whether to retry or not logic to the API ([requested for Alpakka DynamoDb connector](https://github.com/akka/alpakka/issues/767) and for [Alpakka Google Fcm connector](https://github.com/akka/alpakka/issues/923)). This would need a change in the `retryWith` function to take `Try[O]` as well as `S` as arguments.
* support for `FlowWithContext` for simple flows, where propagated state is request to be retried and possibly a counter ([requested in akka-stream-contrib](https://github.com/akka/akka-stream-contrib/issues/58)). Using context for such state reduces the boilerplate needed to adapt simple flows to a flow that fits in the `Retry`. 

Having all of those improvements in mind, the API could look something like this:

```scala
def retry[I, O, S, M](parallelism: Int,
                      minBackoff: FiniteDuration,
                      maxBackoff: FiniteDuration,
                      randomFactor: Double,
                      flow: FlowWithContext[I, S, Try[O], S, M])(
    retryWith: (Try[O], S) => Option[immutable.Iterable[(I, S)]]
): FlowWithContext[I, S, Try[O], S, M] = ???
```

The intention is to have composable API that could be easily used with any Alpakka connector that exposes API with the same shape as `flow` above. For example Akka Http already expose such API for client pools.

**Comment by ennru** [comment]
#27742 adds a `RetryFlow` which is not as powerful as the original in akka-stream-contrib, but considered useful enough to become part of Akka Streams.
