### ISSUE TITLE
Changed variable substitution in config library

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27249]
It's currently scary that config loading has different semantics in Akka and Play.

By default the config library will only substitute variables in reference.conf properties with values loaded from reference.conf, and not from values defined in application.conf.

Akka is using this default behavior and Play has a loading approach which allows users to override such substitutions with values from application.conf.

Look into @jroper 's suggested change in https://github.com/lightbend/config/pull/619

If we are to do this change it should happen for Akka 2.6.0, otherwise the train has left the station.

**Comment by patriknw** [comment]
Personally I think it's a good change, and would be acceptable as a documented change of behavior.

**Comment by patriknw** [comment]
@raboof or @jrudolph could you look into impact for Akka HTTP?

**Comment by raboof** [comment]
This seems OK for Akka HTTP:
* The approach where `akka.http.server.parsing` uses defaults from `akka.http.parsing` is done in code, so doesn't seem impacted
* I did a `publishLocal` from lightbend/config#619 and ran the akka-http tests with that, seems to work.

Tried Akka Management as well, no immediate problems there either.

**Comment by patriknw** [comment]
Thanks for looking into it @raboof

**Comment by johanandren** [comment]
Public RC of config with the changed behavior is now in, this ticket will be kept open until we are depending on a final release of the config lib, and have an entry in the migration guide though.

**Comment by patriknw** [comment]
@johanandren I think it should have been 1.4.0-RC1 since it's probably to risky to change behavior in a patch release. Let's make it 1.4.0-RC2 or 1.4.0 next time we release it.

**Comment by johanandren** [comment]
We should also got through config and perhaps mention in docs if there is any place where this changes config behavior.

**Comment by chbatey** [comment]
@johanandren didn't close this in case you have anything else to do

**Comment by johanandren** [comment]
I think everything is done here!
