### ISSUE TITLE
Error upgrading to scala 2.13 when using ByteString

### ISSUE THREAD

**Issue by AuspeXeu** [akka/akka#27243]
I am using import `akka.util.ByteString` in my project which I now tried to upgrade to Scala 2.13. However I am getting now the following error when re-compiling my project.

```
Symbol 'type scala.collection.IndexedSeqOptimized' is missing from the classpath.
[error] This symbol is required by 'class akka.util.ByteString'.
[error] Make sure that type IndexedSeqOptimized is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'ByteString.class' was compiled against an incompatible version of scala.collection.
[error] import akka.util.ByteString
[error]        ^
[error] one error found
```

I am on the latest akka version from maven central.

**Comment by raboof** [comment]
Interesting. Are you sure you're using the `akka-actor_2.13` artifact with Scala 2.13?

**Comment by AuspeXeu** [comment]
You are absolutely right of course. Hadn't realised that the scala version is part of the artifact name. Is there a reason for this? Other packages seem to be ok without doing so.

**Comment by raboof** [comment]
This is a very common approach for Scala libraries, as Scala does not promise binary compatibility between minor releases. It is so common that sbt has 'special syntax' for it to make it easier: the `%%` that is documented in more detail at https://www.scala-sbt.org/release/docs/Library-Dependencies.html#Getting+the+right+Scala+version+with .

I'll close this issue for now, we use github issues for bug reports and feature requests, and use https://discuss.akka.io for further discussion. Feel free to open a thread there to discuss this further if needed!
