### ISSUE TITLE
WidenedInterceptor should not use `null` as a special idicator.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#27254]
```scala
  def aroundReceive(ctx: TypedActorContext[O], msg: O, target: ReceiveTarget[I]): Behavior[I] = {
    matcher.applyOrElse(msg, any2null) match {
      case null        => Behaviors.unhandled
      case transformed => target(ctx, transformed)
    }
  }
```
it should be 
```scala
    matcher.isDefinedAt(msg) match {
      case false       => Behaviors.unhandled
      case true        => target(ctx, matcher.apply(msg))
    }
```
or use any2SpecialIdicator

**Comment by patriknw** [comment]
The reason is that `applyOrElse` can do optimizations to avoid evaluating the partial function twice. See Scaladoc of `applyOrElse`.

**Comment by hepin1989** [comment]
@patriknw I know that, what I want to point out is should not use `any2null` but `any2SpecialObject`.  how do you distinguish a null returned by `matcher` or `any2null`？

```scala
 private[this] val missMatched = new Object();

  def aroundReceive(ctx: TypedActorContext[O], msg: O, target: ReceiveTarget[I]): Behavior[I] = {
    matcher.applyOrElse(msg, any2MissMatched) match {
      case missMatched        => Behaviors.unhandled
      case transformed => target(ctx, transformed)
    }
  }
```

**Comment by hepin1989** [comment]
`Message is null` is not the same as unmatching. when the matcher itself return null, I expect an exception with `Message is null` but not silently unhandled it.

**Comment by patriknw** [comment]
ok, we can change to that. would you like to open a PR?

**Comment by hepin1989** [comment]
@patriknw Will do。
