### ISSUE TITLE
[akka-actor_2.12 2.5.21] AbstractNodeQueue is not getting garbage collected even after multiple full GC

### ISSUE THREAD

**Issue by Dharmendra-Agrawal** [akka/akka#27255]
**[Using akka version akka-actor_2.12 2.5.21]
Not duplicate of AbstractNodeQueue Nepotism as using akka 2.5.21**

we are using MergeHub in our project for dynamic fan in. everything works well except when we have lot of requests, we are seeking memory leaks.

Frequent Full GCs(65+times) not able to reclaim the memory required for new allocation.
 
One instance of "akka.stream.scaladsl.MergeHub$MergedSourceLogic" loaded by "sun.misc.Launcher$AppClassLoader @ 0x7112f6d00" occupies 2,620,862,200 (82.95%) bytes. 
 
A Linked List Data Structure Detected.
3,413,794,416 bytes (86.62 %) of Java heap is used by 245,455 instances of akka/dispatch/AbstractNodeQueue$Node
Contains 3 types of the following objects:
- 81,823 instances of akka/stream/scaladsl/MergeHub$Deregister holding 2,618,336 bytes
- 81,819 instances of akka/stream/scaladsl/MergeHub$Element holding 242,190,312 bytes
- 81,812 instances of akka/stream/scaladsl/MergeHub$Register holding 3,161,118,360 bytes
<img width="1053" alt="Screenshot 2019-07-03 at 2 46 09 PM" src="https://user-images.githubusercontent.com/16594785/60579739-57cf2700-9da1-11e9-8fc0-4a700f22507d.png">
<img width="1666" alt="Screenshot 2019-07-03 at 2 45 08 PM" src="https://user-images.githubusercontent.com/16594785/60579740-57cf2700-9da1-11e9-955b-89a061bcdef2.png">

**Code**
```
  val source: Source[T, Sink[T, NotUsed]] = MergeHub.source[T]
  val sink = Sink.ignore
  val flowGraph: Flow[T, T, NotUsed]
  override def streamGraph: RunnableGraph[(Sink[T, NotUsed], Future[Done])] = 
  RunnableGraph.fromGraph(
    GraphDSL.create(source, sink)((_, _)) { implicit builder =>
      (mergeHubSource, sink) =>
        import GraphDSL.Implicits._

        mergeHubSource ~> killSwitch.flow[T] ~> unBatch ~> flowGraph ~> sink

        ClosedShape
    })
```

**Comment by johanandren** [comment]
I can't reproduce this, please try to minimize what you have and share a minimal reproducer that can be run to reproduce.

**Comment by Dharmendra-Agrawal** [comment]
we were able to reproduce the issue in 15-20 mins, when we ran 60K constant throughput on single cpu machine. We are connecting small running streams with large processing streams. 
All the HTTP requests on different REST calls come to our system which are streamed to MergeHub
mergeHubSource ~> killSwitch.flow[T] ~> unBatch ~> flowGraph ~> sink
merge helps us connecting to unbatch, which will extract events from the Batch and connects to long processing streams (flowGraph).

following is code snippet from Akka framework

private[akka] class MergeHub[T](perProducerBufferSize: Int) extends GraphStageWithMaterializedValue[SourceShape[T], Sink[T, NotUsed]] {
final class MergedSourceLogic(_shape: Shape, producerCount: AtomicLong) extends GraphStageLogic(_shape) with OutHandler {
    private val queue = new AbstractNodeQueue[Event] {} 
}
}

Above queue keeps growing and does not allow to reclaim memory even after full GC happens multiple times. this leads to memory leaks.

Is there any way where we can avoid memory leaks?

**Comment by johanandren** [comment]
If you can repeat it with a more complete app (including Akka HTTP), can you minimize that into something that just materialises small streams and repeates the issue and share that?

**Comment by jrudolph** [comment]
The most likely reason is that the sink is too slow to service all the incoming elements. Since attaching new producers to a hub is not backpressured or limited you can run into OOM if you continuously attach an unlimited number of new producers to the hub.

I created a new issue for discussing potential remedies.

https://github.com/akka/akka/issues/29299

**Comment by SalithaUCSC** [comment]
Any update on this @jrudolph ?? We are also experiencing the same. When actors are killed, still MergeHub, BroadcastHub and AbstractNodeQueue and not cleaning in the heap area. They are keeping growing more and more. But Flow is getting cleared though.
Code for creating hub sink.
`       Pair<Sink<JsonNode, NotUsed>, Source<JsonNode, NotUsed>> sinkSourcePair =
                MergeHub.of(JsonNode.class, 16).toMat(BroadcastHub.of(JsonNode.class, 256), Keep.both()).run(getContext().getSystem());

        this.hubSink = sinkSourcePair.first();
        Source<JsonNode, NotUsed> hubSource = sinkSourcePair.second();

        adminResponseQueue = hubSink.runWith(Source.queue(1, OverflowStrategy.dropHead()), getContext().getSystem());

        Sink<JsonNode, CompletionStage<Done>> jsonSink = Sink.foreach(this::messageReceivedFromClient);

        this.clientFlow = Flow.fromSinkAndSourceCoupled(jsonSink, hubSource)
            .watchTermination((n, stage) -> {
                // When the flow shuts down, make sure this actor also stops.
                stage.whenComplete((__, error) -> {
                    if(error != null) {
                        logger.error("Sink completed with exception", error);
                    }
                    context().stop(self());
                });
                return NotUsed.getInstance();
            }
        );`
