### ISSUE TITLE
Ability to turn off shard region forwarding debug logs

### ISSUE THREAD

**Issue by jroper** [akka/akka#27276]
The cluster sharding debug logs are very useful for debugging and understanding how cluster sharding is working. However, enabling it in a loaded production system is not a good idea, because a log message is emitted every time a message is forward from one region to another - so if you enable it on a system that is handling 1000s of requests a second, your logs are going to be completely overwhelmed.

That said, I wouldn't get rid of the forwarding message entirely, there are certainly times when its useful. It would just be good to have more control over when it's logged.

If we were using slf4j, my solution would be to use a sub logger of `ShardRegion`, eg `akka.cluster.sharding.ShardRegion.trace`. This is a common pattern used, where you use a particular logger for handling logging that is done in the hotpath of request handling, because it's easy to see how to turn it off, and it's also easy to apply specific configuration to them, eg you could apply a sampling filter that only logged 1% of the messages.

Akka's logging abstraction doesn't seem to allow creating sub loggers from a given logger, and I'm not sure what might be lost if I were to create one from a hard coded string.

**Comment by chbatey** [comment]
In other areas we've put very verbose logging that you often don't want when DEBUG is on behind a flag so we can do that at least for sharding.

**Comment by patriknw** [comment]
We should also put the additional logging added in https://github.com/akka/akka/pull/27446 under the verbose flag.
