### ISSUE TITLE
EventSourcedBehavior Effect.stop().thenRun runs before the actor is completely stopped

### ISSUE THREAD

**Issue by francisdb** [akka/akka#27295]
Akka `2.5.23`

I'm writing some tests for our EventSourcedBehavior and I wanted to test a manual restart of the actor. Below my test.

```scala
      sealed trait Command
      final case class Shutdown(promise: Promise[Unit]) extends Command

      sealed trait Event

      val commandHandler: (String, Command) => Effect[Event, String] = { (state, command) =>
        command match {
          case Shutdown(p) =>
            Effect.stop().thenRun { _ =>
              println("stopped")
              p.trySuccess(())
            }
        }
      }

      val eventHandler: (String, Event) => String = { (state, event) => state }

      val behavior: Behavior[Command] =
        EventSourcedBehavior[Command, Event, String](
          persistenceId = PersistenceId("testid"), // TODO make this unique per runtime and stable
          emptyState = "state",
          commandHandler,
          eventHandler)

      // adds support for typed actors to an untyped actor system and context
      import akka.actor.typed.scaladsl.adapter._
      val system = untypedSystem.toTyped
      val actor = untypedSystem.spawn(behavior, "foo")

      def stop(): Future[Unit] = {
        val promise = Promise[Unit]
        actor ! Shutdown(promise)
        promise.future
      }

      for{
        _        <- stop()
        //_        <- pattern.after(1.millis, untypedSystem.scheduler)(Future.unit).map(_ => println("waited"))
        restored <- Future.successful{println("restart"); untypedSystem.spawn(behavior, "foo")}
      }yield{
        ()
      }
```

But this fails with `akka.actor.InvalidActorNameException: actor name [foo] is not unique` which indicates foo is still not fully stopped. Uncommenting the wait will fix this

I would expect  Effect.stop().thenRun{ ... } to only be run once the actor is fully stopped since the thenRun is supposed to be sequential?

maybe related to #15571

**Comment by johanandren** [comment]
Note that this is aligned with how `PostStop` works for actors in general where the signal handler also has access to the `ActorContext`, there is no guarantee the actor system has removed the actor from the tree yet when the post stop hook is executed. The only way you can be certain an actor was removed is by watching it and receiving the `Terminated` message.

I don't think that this is something we should change, but maybe it is something we should document better?

**Comment by francisdb** [comment]
Is there at that time a guarantee that all database transactions have completed for that `persistenceId`? In other words is it safe to start a new actor with the same `persistenceId`?

**Comment by johanandren** [comment]
Both stop and the `thenRun` callback are side effects and are executed "right away", the persistent actor will not process commands, but stash, if the previous write has not completed yet. However I'd still recommend that you put such flow-control logic about restarting the actor outside of the persistent actor rather than inside of itself.
