### ISSUE TITLE
Add version/awareness for in-progress rolling update

### ISSUE THREAD

**Issue by helena** [akka/akka#27300]
Add a deploy version to track old versus new nodes.

Use case e.g. in Cluster Sharding as a new node joins the cluster, check if the joining member has a higher version to:

Dependency of:
* Only allocate shards on new nodes when a rolling update is in progress #27368
* Disable rebalance during in-progress rolling update #27367

**Comment by helena** [comment]
Some good earlier cluster join conversation in https://github.com/akka/akka/issues/22548 related to end usage of this.

**Comment by chbatey** [comment]
Try and add triaged if it is fully fleshed out and ready for someone to work on or discuss for new issues when you create them

**Comment by helena** [comment]
Prior to bringing up in planning?

**Comment by patriknw** [comment]
This is the foundation for other features built on top of this information, so we should start here.

I see two alternatives for adding the appVersion to Member.

1. Put the version in the `roles` Set.
2. Add a new appVersion field to Member and some of the join messages. Can be exchanged in same way as `roles`, i.e. only included in initial join messages (and not in every gossip).

Second option is more clean, but some more work. I vote for this.

appVersion is something like `Version(major: Int, minor: Int, patch: Int)`, which can be compared. See `ManifestInfo.Version` for implementation.

**Comment by johanandren** [comment]
I like option 2 better as well 👍

**Comment by raboof** [comment]
> See `ManifestInfo.Version` for implementation.

Looks like that would even work for dynver-like versioning - but I wonder if we should provide a way for users to customize this when they some other particular scheme?

**Comment by ignasi35** [comment]
We should be careful to make the deployment version independent of the version of the artifact deployed. A new rolling update where the user still deploys the same binary but uses different settings may require version (as in "deployed version") bump.
