### ISSUE TITLE
Improve typed actorRefWithAck docs

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27317]
Deciphering what the type parameters `T`, `M` and `A` are is a bit hard. We should improve docs or perhaps give the type parameters better names.

**Comment by PrettyCities** [comment]
I can take a look at this.

**Comment by patriknw** [comment]
thanks

**Comment by mghildiy** [comment]
If no one is working on it, I can take it up.

**Comment by johanandren** [comment]
Please do!

**Comment by mghildiy** [comment]
https://doc.akka.io/japi/akka/current/akka/stream/javadsl/Sink.html#actorRefWithAck(akka.actor.ActorRef,java.lang.Object,java.lang.Object,java.lang.Object,akka.japi.function.Function)

This is the documentation to be improved, I guess.

**Comment by johanandren** [comment]
Oh, sorry, looks like it has been renamed to `actorRefWithBackpressure` since this issue was created, and the old name has been deprecated. 

The docs would rather be the reference docs than the API javadoc/scaladoc, and it looks like they were perhaps improved when the new name was introduced: https://doc.akka.io/docs/akka/current/stream/operators/Source/actorRefWithBackpressure.html#actorrefwithbackpressure
https://doc.akka.io/docs/akka/current/stream/operators/Sink/actorRefWithBackpressure.html#actorrefwithbackpressure

Looking at the deprecated methods I can't find one with type parameters `T`, `M` and `A` so perhaps that aspect was also already improved.

Closing this for now, sorry to mislead you to dig into an issue that was already fixed!

**Comment by mghildiy** [comment]
No issues.
