### ISSUE TITLE
Task cancellation in coordinated shutdown

### ISSUE THREAD

**Issue by SmedbergM** [akka/akka#27335]
Akka's `CoordinatedShutdown` utility provides cancellable JVM shutdown hooks, but not cancellable shutdown phase tasks. This means that it is memory-unsafe to register tasks on behalf of an actor class unless one knows that only N instances of that class will ever be instantiated during an application's lifetime.

Example use case: our application is a daemon responsible for running some kind of long-running task. Each task is managed by a `LRTActor`. We want to include a `CoordinatedShutdown` hook that cleans up a task's database state in the event of shutdown in the middle of the task's run. The natural approach to this is for each `LRTActor` to register a task in phase `PhaseServiceUnbind` which performs this cleanup if the task is not yet complete; however, since tasks cannot be unregistered (and once registered are never garbage-collected), this will cause a memory leak.

One can work around this only by having a root singleton actor keep track of which tasks are running and need to be cleaned up on shutdown, which is ugly IMHO.

Proposal:
Add a method `CoordinatedShutdown.addCancellableTask(phase: String, taskName: String)(task: () => Future[Done]): Cancellable` which on cancellation guarantees that all references to `task` are released.

**Comment by johanandren** [comment]
I'm on the fence, on one hand such a method would be neat, on the other hand having a coordinator singleton actor of some kind registering with coordinated shutdown once and then dealing with whatever set of tasks is needed is more along the lines of what coordinated shutdown was designed for.

**Comment by SmedbergM** [comment]
I'd argue that `CoordinatedShutdown(actorSystem)` *already* acts as such a singleton.
