### ISSUE TITLE
Allow for custom ActorSystem when creating typed ActorTestkit

### ISSUE THREAD

**Issue by Reklund3** [akka/akka#27338]
Feature Request,

Use Case: Enhance the ActorTestKit (typed) to allow for creating and/or passing an Actor
System. Additionally, this would allow for testing Typed Actor Systems and their corresponding
interaction with Lagom Persistent Entites.

This request is for the following:
- A method that takes an ActorSystemSetup
- A method that takes an ActorSystem

Reference Discussion: https://discuss.lightbend.com/t/typed-actor-testkit/4569/2

Regards,
_Robert_

**Comment by johanandren** [comment]
I think we only need a factory to create it with a custom `ActorSystem` as that would also cover creating the actor system with custom `ActorSystemSetup`

**Comment by Reklund3** [comment]
I concur, I think this approach will accomplish our goal.
