### ISSUE TITLE
Mention rolling update from Classic to Typed Sharding in docs

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27342]
Not sure it belongs in the 2.5 -> 2.6 migration guide, since it's not at all a mandatory migration.

Probably best to mention in Cluster Sharding reference docs.

I don't think we should spend time on writing a full guide, if not requested by customers. The commits and descriptions in https://github.com/akka/akka-samples/pull/110 should be enough.

**Comment by helena** [comment]
Or this can go in after https://github.com/akka/akka/issues/27192 where there is a new section for Cluster Sharding and untyped to typed.

**Comment by helena** [comment]
Now this could go here https://doc.akka.io/docs/akka/snapshot/additional/rolling-updates.html#cluster-sharding
