### ISSUE TITLE
Incorporate Data Replication Scenarios in Cluster Sharding 

### ISSUE THREAD

**Issue by mridulv** [akka/akka#27345]
Currently the `akka-cluster-sharding` module does not deal with replication and `akka-distributed-data` deals with replication with sharding. My use case is simple to have replicated shards. Currently with my limited set of knowledge it is not possible for `shards` created via `akka-cluster-sharding` are replicated within the cluster. So make it possible we might need to introduce the concept of replication within each and every shards.

**Comment by johanandren** [comment]
Cluster Sharding is designed for consistency, to make sure that a certain entity is never alive on more than one node at the same time and can make reliable business decision based on its state, having replicated actors running on N nodes is a very different thing and I don't think we'd want to try to shoehorn that into sharding.

It could be possible to achieve replication by running several instances of sharding with some custom shard allocation strategy, or by combining sharding with the module Distributed Data.

We also have a commercial module, that may be interesting, somewhat related to this topic, eventually consistent persistent entities: https://doc.akka.io/docs/akka-enhancements/current/persistence-dc/index.html
