### ISSUE TITLE
Disable rebalance during in-progress rolling update

### ISSUE THREAD

**Issue by helena** [akka/akka#27367]
Depends on: Add awareness for in-progress rolling update #27300
Peer of: Only allocate shards on new nodes when a rolling update is in progress #27368
Related to: https://github.com/akka/akka/issues/26501

And update https://doc.akka.io/docs/akka/current/cluster-sharding.html#shard-rebalancing

**Comment by helena** [comment]
Related to https://github.com/akka/akka/pull/27736

**Comment by johanandren** [comment]
I thought this would end up as logic in the allocation strategy but I realize now it is rather something to change in the coordinator.

**Comment by patriknw** [comment]
> I thought this would end up as logic in the allocation strategy but I realize now it is rather something to change in the coordinator.

I think it can be part of the allocation strategy. Probably rather related to https://github.com/akka/akka/issues/27368
The allocation strategy can return empty list to skip rebalance. Then we don't have to bloat the coordinator with this concern.
