### ISSUE TITLE
Custom equals/hashCode for GSet/ORSet/ORMap

### ISSUE THREAD

**Issue by jroper** [akka/akka#27363]
If using classes where you don't control the actual class implementation (such as generated classes, like the recommended approach of using protobufs), and you want a custom `equals`/`hashCode` for `GSet`, `ORSet`, `ORMap`, the only way to implement it currently is to define a custom class, and therefore a custom serializer.

One use case for custom `equals`/`hashCode` is if the value contains an embedded serialized value, using an encoding that is not stable (ie, two equal values don't necessarily serialize to identical bytes, json and protobuf are both examples of this, since fields can be in any order). In such a case, equality may be based on a user defined key, from which `equals`/`hashCode` are implemented (with the assumption that if two keys are equal, then the serialized values associated with them must be semantically equal).

To support this, I guess the `equals`/`hashCode` implementations would have to be defined as part of the distributed data key.

**Comment by patriknw** [comment]
@jroper Not sure I understand your suggested solution?

Note that the serialized representation must be stable for another reason also. It's used for creating SHA-1 digests to detect which entries that have changed.

**Comment by Captain1653** [comment]
This issue is quite old. There are no comments for 4 years.

Should this issue be closed?

**Comment by patriknw** [comment]
yes, doesn't look like we make any changes of this
