### ISSUE TITLE
DataDeleted should extend GetResponse and UpdateResponse

### ISSUE THREAD

**Issue by jroper** [akka/akka#27371]
`DataDeleted` extends `DeleteResponse`, but can also be sent in response to a `Get` or `Update`, and hence should also extend `GetResponse` and `UpdateResponse`. Without this, it's not safe to use `Future.mapTo[GetResponse[...]]` or `Future.mapTo[UpdateResponse[...]]` when sending `Get` or `Update` messages to the replicator using the `ask` pattern.

**Comment by jroper** [comment]
Ah I just noticed, while `DeleteResponse` is a trait, `GetResponse` and `UpdateResponse` are abstract classes, so this won't work. And `DataDeleted`'s root class is `RuntimeException` (why? seems like a leaking implementation detail).

Is converting to an interface too big a breaking change? I guess the danger lies in anything trying to invoke, for example `GetResponse.key` using `invokevirtual` - does that throw a `LinkageError` since `GetResponse.key` would now be an interface method requiring `invokeinterface`? Or is the JVM kind and automatically switches to `invokeinterface`?

**Comment by helena** [comment]
Looking into this to assign label other than `0 - new`

**Comment by patriknw** [comment]
This is indeed messy. It will also break things for Typed.

Maybe a somewhat compatible solution would be to add new messages

```
case class UpdateDataDeleted extends UpdateFailure
case class GetDataDeleted extends GetFailure
```

Another one that is strange (and not work with Typed) is `Deleted`, which is used for `subscribe`.

The naming of `ReplicationDeleteFailure` is also not following the same convention as other messages. Should be `DeleteFailure`
