### ISSUE TITLE
FSM StateTimeout feature improments

### ISSUE THREAD

**Issue by wpc009** [akka/akka#27374]
The current `StateTimeout`  in the `FSM`'s implementation is more like an idle timeout rather than a state timeout. The `StateTimeout` message will be triggered only if the actor does not receive anything within the duration.

 Some times we need the `FSM` to stay in certain `state` no more than a duration that we defined. This requirement can not be fulfilled using current `StateTimeout` feature. 

It will be nice to have a real state timeout besides with the idle timeout.

**Comment by chbatey** [comment]
Hi @wpc009 you can implement that with `startSingleTimer`. Going forward we plan to put development into the Akka Typed APIs rather than the FSM (but it won't go away). We have a docs page for how to use Akka Typed to implement FSMs: https://doc.akka.io/docs/akka/current/typed/fsm.html
