### ISSUE TITLE
Add clarification to doc on cluster cross boundary use of DeathWatch

### ISSUE THREAD

**Issue by helena** [akka/akka#27376]
See discussion https://discuss.lightbend.com/t/akka-2-6-0-m4-can-not-reproduce-documented-behaviour-for-remote-watch-disabled-changes/4574/14

**Comment by helena** [comment]
Adding triaged, I think this is helpful.

**Comment by skvithalani** [comment]
As suggested by @patriknw in this [discussion](https://discuss.lightbend.com/t/akka-2-6-0-m4-can-not-reproduce-documented-behaviour-for-remote-watch-disabled-changes/4574/17), we should also capture renaming `use-unsafe-remote-features-without-cluster` to `use-unsafe-remote-features-outside-cluster` in this issue.

**Comment by helena** [comment]
Yes, that is part of it thanks.

**Comment by helena** [comment]
Jenkins multi-jvm tests pass for 
akka-remote/test 
akka-remote-tests/test 
akka-cluster/test
 akka-cluster-sharding/test
