### ISSUE TITLE
Sink.seq doesn't capture elements when used multiple times

### ISSUE THREAD

**Issue by KaoruDev** [akka/akka#27370]
## ENV
- Scala: `2.13.0`, `2.12.8`
- Akka Version: `2.5.23`, `2.5.21`

## Problem
`Sink.seq` doesn't add elements when the sink is used multiple times.

## Example

```scala
  val (evenNumbersAndThree, evenSink) = Sink.seq[Int].preMaterialize()

  Source(List(1,2,3,4,5,6)).divertTo(evenSink, i => i % 2 == 0)
    .divertTo(evenSink, i => i % 3 == 0)
    .runWith(Sink.ignore)

  evenNumbersAndThree.map(numbers => println(s"Numbers: $numbers")).onComplete(_ => system.terminate())
```

Result:

```
Numbers: Vector()
```

Expected:

```
Numbers: Vector(2, 3, 4, 6)
```

As a sanity check:

```scala
  val list = scala.collection.mutable.ListBuffer[Int]()
  val evenSink = Sink.foreach[Int](list += _)

  Source(List(1,2,3,4,5,6)).divertTo(evenSink, i => i % 2 == 0)
    .divertTo(evenSink, i => i % 3 == 0)
    .runWith(Sink.ignore)
    .map(_ => println(s"Numbers: $list"))
    .onComplete(_ => system.terminate())
```

Result:

```
Numbers: ListBuffer(2, 3, 4, 6)
```

**Comment by raboof** [comment]
> Numbers: Vector(2, 3, 4, 6)

Actually I'm not sure that is what I would expect. I don't think `preMaterialize` was designed to allow multiple materializations. It would be hard to say what the semantics would have to be in that case: some sinks listen to the end of the stream, but if the sink can be materialized multiple times, which 'end of the stream' should it listen to?

We should definitely document this better. That said, `Vector()` is surprising to me as well: I would have expected at least either `Vector(2,4,6)`.

**Comment by KaoruDev** [comment]
I'm not super familiar with how elements flow through streams. That said,

>  I don't think preMaterialize was designed to allow multiple materializations.

It doesn't appear to me that `Sink.seq` is being materialized multiple times since the `Sink` `preMaterialize` returns a type of: `Sink[T, NotUsed]`, a wrapper around the already initialized `Sink.seq`

I think the question might be whether it is expected for an instance of a `Sink` to be plugged into multiple times within a given graph. 

For additional context, I'm using `Sink.seq` to collect results in a test and how I got around this is by using a `mutable.ListBuffer` I fear this is not the correct way to go about it.

**Comment by raboof** [comment]
> It doesn't appear to me that `Sink.seq` is being materialized multiple times since the `Sink` `preMaterialize` returns a type of: `Sink[T, NotUsed]`, a wrapper around the already initialized `Sink.seq`

Right, but the returned `evenSink` is materialized twice, once for each `divertTo`

> I think the question might be whether it is expected for an instance of a Sink to be plugged into multiple times within a given graph.

In general this should be fine, but in case of a sink produced by `preMaterialize` I don't think that is the intended usage.

> For additional context, I'm using `Sink.seq` to collect results in a test and how I got around this is by using a `mutable.ListBuffer` I fear this is not the correct way to go about it.

In a test, it is pretty common to test just the `Flow` and add a `Sink.seq` at the end of it to capture the resulting elements. Without more context on what kind of code you want to test it is hard to give advice here though - and that would perhaps be better-suited for a topic at https://discuss.akka.io ?

**Comment by KaoruDev** [comment]
> In a test, it is pretty common to test just the Flow and add a Sink.seq at the end of it to capture the resulting elements. 

The graph in question is similar to the one I posted. During the test I want to capture all ints that made it to the sink to make sure I'm not dropping elements from the stream.

> In general this should be fine, but in case of a sink produced by preMaterialize I don't think that is the intended usage.

Is there an alternative way to collect elements that made it to the final sink and any elements sent by `divertTo`?

**Comment by raboof** [comment]
Ah, so the `divertTo` calls are not just there for testing, but also functionally necessary in your production code?

In that case perhaps:
```
val (evenNumbers, evenNumbersSink) = Sink.seq[Int].preMaterialize()
val (three, threeSink) = Sink.seq[Int].preMaterialize()
```
?

**Comment by KaoruDev** [comment]
Sorry, I wasn't clear. `Sink.seq` is only used in tests. In the production code, I do use `divertTo` with a handful of flows leading to `Sink.ignore`. In the test, I switch out the `Sink.ignore` for `Sink.seq` hoping to capture the results.

Your suggest does work:

```scala
  val (evenNumbers, evenSink) = Sink.seq[Int].preMaterialize()
  val (three, threeSink) = Sink.seq[Int].preMaterialize()

  val endStream = Source(List(1,2,3,4,5,6)).divertTo(evenSink, i => i % 2 == 0)
    .divertTo(threeSink, i => i % 3 == 0)
    .runWith(Sink.ignore)

  (for {
    even <- evenNumbers
    threes <- three
  } yield (even, threes))
    .map(list => println(s"Numbers: $list"))
    .onComplete(_ => system.terminate())

// STDOUT: Numbers: (Vector(2, 4, 6),Vector(3))
```

But given a graph large enough, this seems less ideal. I fear we're diverting (no pun intended) from the original problem, I don't think `Sink.seq` can be used multiple times. If this is expected, it should be clearly stated. If it is unexpected, it should be fixed.

---

Here's another example where it doesn't work as expected _without_ using `preMaterialize`

```scala
  val collectSink = Sink.seq[Int]

  Source(List(1,2,3,4,5,6)).divertTo(collectSink, i => i % 2 == 0)
    .divertTo(collectSink, i => i % 3 == 0)
    .toMat(collectSink)(Keep.right)
    .run()
    .map(list => println(s"Numbers: $list"))
    .onComplete(_ => system.terminate())

// STDOUT: Numbers: Vector(1, 5)
```

**Comment by raboof** [comment]
>  `Sink.seq` is only used in tests. In the production code, I do use `divertTo` with a handful of flows leading to `Sink.ignore`.

My suggestion would be to test the elements coming out of your `Flow`, without introducing `divertTo` branches in the middle of it just for testing. If you want to test different parts of your `Flow` independently, make them separate `Flow`s.

> I don't think Sink.seq can be used multiple times

`Sink.seq` can be used multiple times just fine, it's the sink returned by `preMaterialize` that is not intended to work that way.

> If this is expected, it should be clearly stated

Yes, I think we should improve the documentation of `preMaterialize`.

> Here's another example where it doesn't work as expected without using `preMaterialize`

This works as expected: 3 sequences are materialized, the first contains 2,4,6, the second contains 3, and the final one (of which you print the materialized value) contains 1,5.

To get all 3 sequences (though this example is getting pretty contrived), you could do something like:

```
val ((seq1, seq2), seq3) = Source(List(1,2,3,4,5,6))
  .divertToMat(collectSink, i => i % 2 == 0)(Keep.right)
  .divertToMat(collectSink, i => i % 3 == 0)(Keep.both)
  .toMat(collectSink)(Keep.both)
  .run()

seq1.map(println)
seq2.map(println)
seq3.map(println)
```
(though I'm not proposing that's a good idea in your case, just showing how materialization works ;) )

**Comment by KaoruDev** [comment]
Ah I see, the issue is I'm misunderstanding of how `Materialize` works in general. Thanks for walking me through this. I'd be happy to close this issue unless you'd like to keep it open until the documentation is updated.
