### ISSUE TITLE
Productionize CurrentShardRegionState

### ISSUE THREAD

**Issue by helena** [akka/akka#27406]
Currently this is only used by tests and not added to the internal protobufs for users. 
If this is ever bumped up to gathering from the `ShardCoordinator` or Akka Management HTTP cluster routes, this needs to be added to the protos  and extend `ClusterShardingSerializable`, and with this https://github.com/akka/akka/pull/27395 merged it can also include the `ShardId` set of any that may have failed in the ask.

**Comment by chbatey** [comment]
Sounds useful as this is a public type but doesn't seem a priority for 2.6/typed.

**Comment by helena** [comment]
Agree, not important ATM, worth considering later.

**Comment by raboof** [comment]
Can this be closed now #28645 is merged?

**Comment by helena** [comment]
It is merged, closing.
