### ISSUE TITLE
Typed systemActorOf unnecessarily wraps ActorRef in a Future

### ISSUE THREAD

**Issue by 2m** [akka/akka#27437]
The only current implementation of `systemActorOf` wraps `ActorRef` with `Future.successful`. Therefore it could be removed and return `ActorRef` instead.

https://github.com/akka/akka/blob/89e269d5d89b78ba950af9cbcef49e6b38a335b4/akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala#L114-L118

**Comment by chbatey** [comment]
This is there due to the native typed actor system's old implementation. I think we should remove the Future as re-introducing the native typed actor system isn't likely to become a priority any time soon.

**Comment by raboof** [comment]
Would that make it harder to build the native typed AS later without breaking bincompat?

**Comment by patriknw** [comment]
It's right that the reason for the Future was to "prepare" for a world without classic RepointableActorRef. However, I think we can change this to return a strict `ActorRef` and later introduce a Future based one if needed. The naming is anyway more "classic", and we can save `spawn` for the future.

That would also solve the problem that there is currently no Java API for this (returning CompletionStage).
