### ISSUE TITLE
Behaviors.empty vs Behaviors.unhandled

### ISSUE THREAD

**Issue by dwijnand** [akka/akka#27443]
The current scaladocs for them are:

```scala
  /**
   * Return this behavior from message processing in order to advise the
   * system to reuse the previous behavior, including the hint that the
   * message has not been handled. This hint may be used by composite
   * behaviors that delegate (partial) handling to other behaviors.
   */
  def unhandled[T]: Behavior[T] = BehaviorImpl.unhandled

  /**
   * A behavior that treats every incoming message as unhandled.
   */
  def empty[T]: Behavior[T] = BehaviorImpl.empty
```

I feel with those definitions `unhandled` is the more natural name for the current "empty" method.  Which leave a problem for the current `unhandled` method.  Either it should have a new name ("pop"? "undefined" 🙁) or perhaps they should be merged into one.

From a user perspective is there any reason for these to be distinct behaviors?  Are there situations where both are legitimate choices but a user might choose one over the other?  In those situations if there were only one method could Akka derive which behavior is desired?

Perhaps the docs just need some refining.

**Comment by patriknw** [comment]
`unhandled` means that the current message is not handled (resulting in some standardized logging of that) but it doesn't change behavior for next message.

`empty` switches to a new behavior that will treat every new incoming message as unhandled. Useful for example when waiting for a signal before stopping.

Those are for different purposes and can't be combined into one.

We could have different opinions about naming but I don't think current naming is bad.
Compare `Behaviors.empty` with `PartialFunction.empty`.

**Comment by dwijnand** [comment]
Is it observable that messages sent to `empty` are unhandled?  Or is it more like a black hole for messages?

**Comment by patriknw** [comment]
Messages received to `empty` are handled by returning `unhandled`, i.e. they are observable.
The black hole is called `Behaviors.ignore`.

**Comment by dwijnand** [comment]
So `Behaviors.empty` is built on top of `Behaviors.unhandled`?

**Comment by patriknw** [comment]
yes, kind of: https://github.com/akka/akka/blob/a87edc601d6d75fade4424670ab20db220b3d3d1/akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala#L267-L268

**Comment by patriknw** [comment]
@dwijnand does this answer your questions or anything we should discuss more that you would like us to change?

**Comment by dwijnand** [comment]
Nope, I think I understand now.  I think the parallels and differences between empty and unhandled (and maybe even ignore) should be feature in the docs.

**Comment by patriknw** [comment]
ok, keeping this ticket then for improving docs
