### ISSUE TITLE
Nightly versions are hard to use from gradle

### ISSUE THREAD

**Issue by raboof** [akka/akka#27453]
We publish nightly builds to https://repo.akka.io/snapshots/ with versions like 2.5-20190801-210045.

Unfortunately, these are hard to use from Gradle: Gradle by default chooses the 'highest' version when multiple versions are found in the dependency tree, and considers '2.5.23' 'higher' than 2.5-20190801-210045. If there's transitive dependencies on 2.5.x versions, to depend on 2.5-20190801-210045 you would need to [add potentially many exclusions](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:enforcing_dependency_version) or [use other non-standard techniques](https://gist.github.com/hlship/9117680)

Might be fixed by #27042 ?

**Comment by johanandren** [comment]
These are now the style `2.6.1+148-a614f0be` did that perhaps resolve the issue.

**Comment by johanandren** [comment]
Let's close and re-open if it did in fact not help.
