### ISSUE TITLE
Race condition when binding to arbitrary port with artery

### ISSUE THREAD

**Issue by raboof** [akka/akka#27455]
When binding Artery TCP to an arbitrary port (by configuring port '0'), we first select a port with `ArteryTransport.autoSelectPort` and then bind to it.

However, the port is released between selecting it and binding to it, so there is a race condition if there is something else that is also binding to an arbitrary port. This may be more likely to happen when starting a number of actor systems, for example when running tests.

**Comment by helena** [comment]
Merged and back ported.
