### ISSUE TITLE
Can you tell me how to pass the http request in postman or Advanced REST Client??

### ISSUE THREAD

**Issue by senthurRam33** [akka/akka#27466]
Can you tell me how to pass the Http request for this websocket in postman or Advanced REST Client??

**Comment by raboof** [comment]
Hi! I'm not sure what websocket you are talking about. Could you give some more context and ask at https://discuss.akka.io? We're using the github issues only for bugs and feature requests.

**Comment by senthurRam33** [comment]
The websocket that I'm talking about is in scala.           https://stackoverflow.com/questions/57375015/i-was-trying-to-insert-websocket-apis-in-a-project-that-uses-rest-apis-using-s . U can find the extension of the problem in the above link
