### ISSUE TITLE
multi-node testing without using separate classes

### ISSUE THREAD

**Issue by kanishka-azimi** [akka/akka#27480]
The multi-node testing requires that you define one class for each node. Since you can filter actions to run on specific nodes, usually one will only define a single base class and inherit from it repeatedly. It would be convenient if you did not need to define one class per node.

**Comment by patriknw** [comment]
Maybe something to consider for #26930, but not in core team's priorities. You are welcome to contribute.

**Comment by kanishka-azimi** [comment]
Agreed on priority
