### ISSUE TITLE
Update to Jackson 2.10

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27508]
Hopefully the Jackson 2.10 release will be ready when we are to release Akka 2.6.0

**Comment by plokhotnyuk** [comment]
Are you going to be mentioned in CVEs like these? https://github.com/FasterXML/jackson-core/issues/554

**Comment by patriknw** [comment]
I don't how that work, but the main reason for using the latest 2.10.x is that security patches will in latest Jackson version. Sometimes they are backported, but not always.

**Comment by plokhotnyuk** [comment]
Are you going to share "Darwin award for IT security" (c) @jroper with them? https://github.com/FasterXML/jackson-databind/issues/2258

**Comment by patriknw** [comment]
Tried 2.10.0.pr1, see [release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10).

Only one test related to duration format failed, and that is mentioned in release notes (WRITE_DURATIONS_AS_TIMESTAMPS).

We might want to support the new [feature configuration](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10#separation-of-general--json-specific-features)

Maybe we should use the new `JsonMapper` instead of `ObjectMapper`?

Not sure if we need to support the new `PolymorphicTypeValidator` given that we recommend against default typing? Can probably be added later?

cc @marcospereira
