### ISSUE TITLE
Stream quickstart fiddle and 2.6

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27510]
After #27491 the stream-quickstart.md fiddle will not work anymore until we have released 2.6 and there is a corresponding Akka.js release and update of the fiddle.

**Comment by patriknw** [comment]
cc @andreaTP

**Comment by andreaTP** [comment]
On vacation at the moment, I was planning to try out a release cross compiling for Scala 2.13 as well. Let's plan about this early next week.

**Comment by patriknw** [comment]
thanks, no rush

**Comment by patriknw** [comment]
@andreaTP what is the status of this?

**Comment by andreaTP** [comment]
Started to work on the port here:
https://github.com/akka-js/akka.js/tree/update2.6.1

Unfortunately I have a blocker in the stream module:
https://github.com/akka-js/akka.js/blob/update2.6.1/akka-js-actor-stream/js/src/main/scala/akka/stream/SystemMaterializer.scala#L98

`SystemMaterializer.materializer` is eagerly evaluated into the creation of `ActorMaterializer`, this makes the creation of an `ActoiMaterializer` impossible with less than 2 threads (the `Await`s there are a symptom of it, IIUC).
We probably need to change the API to be unblocking or find a workaround to be able to run on a single thread.

**Comment by johanandren** [comment]
Yeah, that's a tricky one, it was changed to a tiny bit of initial blocking to avoid a whole set of bugs, not sure it will be possible to come up with a solution to that. I'll think a bit about it and see if I come up with something.

I'm sure there are other blocking things during startup, how have those been worked around for akka.js?

**Comment by andreaTP** [comment]
A first snapshot version of Akka.js on top of Akka 2.6.1 is out to be tested!
`1.2.6.1-RC1-SNAPSHOT`
(add the resolver `resolvers += Resolver.sonatypeRepo("snapshots")`)
reference:
https://github.com/akka-js/akka.js/issues/103

**Comment by andreaTP** [comment]
Akka.Js `1.2.6.1` is out!
Fiddles are good (tested on the snapshot): https://github.com/andreaTP/akka-fiddles
PR to scalafiddle is open https://github.com/scalafiddle/scalafiddle-io/pull/42

**Comment by johanandren** [comment]
Cool, thanks for the work on this @andreaTP

**Comment by andreaTP** [comment]
:+1: 
currently blocked by this:
https://github.com/scalafiddle/scalafiddle-core/issues/38

**Comment by andreaTP** [comment]
Scalafiddle is fine now and this: https://github.com/akka/akka/pull/28424
is ready to go in on my side.
