### ISSUE TITLE
EventSourcedBehavior doesn't allow to handle recovery failures when in ReplayingSnapshot behavior

### ISSUE THREAD

**Issue by s4nk** [akka/akka#27526]
I'm not sure if this is an intentional behavior or a bug, but the recovery failure handling logic in persistent actors differs significantly between the second behavior of `EventSourcedBehavior`, the `ReplayingSnapshot`, and the third behavior, the `ReplayingEvents`. In `ReplayingEvents` everything works as expected, when there's a failure the `onRecoveryFailure` method calls the signal handler with a `RecoveryFailure` signal, does a bunch of other things and finally throws a `JournalFailureException`, which is then handled according to the specified supervision strategy, in `EventSourcedBehaviorImpl`. The `ReplayingSnapshot` behavior does things completely differently, it doesn't send the `RecoveryFailure` signal, it doesn't throw a `JournalFailureException`, it simply stops. As a result it's impossible to handle recovery failures that happen during snapshot replay the same way as failures during event replay, the only option is to watch the persistent actor from its parent actor.

**Comment by patriknw** [comment]
I agree, this must be an oversight that should be fixed. Without JournalFailureException it will not use backoff supervision if that is given.
