### ISSUE TITLE
ReceiveBuilder: documentation issue

### ISSUE THREAD

**Issue by krnkhanna1989** [akka/akka#27536]
ReceiveBuilder documentation says to create a ReceiveBuilder as: 
```
ReceiveBuilder.match(Double.class, d -> {
    getSender().tell(d.isNaN() ? 0 : d, self());
})
```

However, I think the match is not static anymore.

**Comment by johanandren** [comment]
Where is that, the API docs or the reference docs, what Akka version?

**Comment by patriknw** [comment]
It's in Javadoc. I'll fix it right away.
