### ISSUE TITLE
Actor starvation, customized dispatcher doesn't work

### ISSUE THREAD

**Issue by maodou** [akka/akka#27572]
An actor with customized dispatcher doesn't consume any message, doesn't work.

Akka version: 2.5.13
I have created an actor for dispatching event to backend actors, and customized a dispatcher for this actor, as below
****-dispatcher {
  type = "Dispatcher"
  executor = "thread-pool-executor"
  thread-pool-executor {
    core-pool-size-min = 5
    core-pool-size-factor = 2.0
    core-pool-size-max = 10
  }
  throughput = 10
}
And using the default dispatcher for other actors.
actor {
    default-dispatcher {
      type = "Dispatcher"
      executor = "thread-pool-executor"
      thread-pool-executor {
        core-pool-size-min = 200
        core-pool-size-factor = 3.0
        core-pool-size-max = 400
      }
      throughput = 1
    }
  }

After about a month running, the server didn't work as usual. After some dig, I found
1. The actor for dispatching event doesn't consume any message, as there's no log of this actor after issue happens.
2. The mailbox is normal and have many message accumulated, and the total number of threads dropped from 210 (200 for default dispatch, 10 for the actor) to 200, I would conclude that 210-200=10 is the thread pool for the actor. 
3. The server's memory and cpu load was normal as usual, and the requests is normal too.
We have kamon to monitor the system.

BTW, we have almost the same issue when we use "fork-join" executor. After changing to  "thread-pool-executor", the issue didn't happen for half a year.

**Comment by raboof** [comment]
Do you have a stack dump at the time of the stall? It sounds like somehow all the threads in your customized dispatcher were occupied, a stack dump might help explain by what.

Without further information this doesn't sound like a bug in Akka, (especially given you indeed see 200+10=210 threads, so it looks like your custom dispatcher is used as you expect), so I'll close this for now. If you would like help further analyzing the problem https://discuss.akka.io might be a better place. If further analysis does point into the direction of an Akka bug then of course please do reopen this issue (or open a new one).

**Comment by maodou** [comment]
@raboof sorry, maybe I don't express correctly. I mean the total number of threads dropped from 210 to 200.
<img width="363" alt="屏幕快照 2019-08-28 下午8 30 43" src="https://user-images.githubusercontent.com/5620325/63855984-3cfce580-c9d3-11e9-9d4a-5fbe273501bc.png">
<img width="364" alt="屏幕快照 2019-08-28 下午8 32 27" src="https://user-images.githubusercontent.com/5620325/63855992-41c19980-c9d3-11e9-8d17-248aedcef08f.png">
Thx for replying!

**Comment by raboof** [comment]
Ah, that might indeed be surprising then! A stack dump would still be interesting.

Are you running exactly 1 actor on this custom dispatcher, or multiple actors?

**Comment by maodou** [comment]
Exactly 1 actor.  
I'm trying to get a stack dump, but this issue is hard to reproduce. The server is running OK for almost half a year.

**Comment by maodou** [comment]
Let me add a little more, some actors on the default dispatcher were still working.
Thanks ^_^

**Comment by raboof** [comment]
OK, so it sounds like your system is somehow deadlocked while processing a messages on that one actor that is running on a custom dispatcher. A stack dump will reveal more.

**Comment by maodou** [comment]
@raboof thanks, I'll try reproducing the issue.
