### ISSUE TITLE
Failed: ArteryUpdSendConsistencyWithThreeLanesSpec - send messages with actorSelection concurrently preserving order

### ISSUE THREAD

**Issue by helena** [akka/akka#27580]
akka.remote.artery.ArteryUpdSendConsistencyWithThreeLanesSpec.Artery must be able to send messages with actorSelection concurrently preserving order

https://jenkins.akka.io:8498/job/akka-nightly/6877/testReport/junit/akka.remote.artery/ArteryUpdSendConsistencyWithThreeLanesSpec/Artery_must_be_able_to_send_messages_with_actorSelection_concurrently_preserving_order/

related to https://github.com/akka/akka/issues/23150

**Comment by patriknw** [comment]
Corrected Jenkins link: https://jenkins.akka.io:8498/job/akka-nightly-jdk8/6877/

Before the test fails there is a:
```
outbound connection to [akka://systemB@localhost:35685], message stream] Upstream failed, cause: StreamTcpException: The connection closed with error: Connection reset by peer
```

No clue of what could be causing that. Both systems running on same host. I guess we have to close if it doesn't repeat.

**Comment by patriknw** [comment]
Closing as old
