### ISSUE TITLE
BackoffOnRestartSupervisor do not respect OneForOneStrategy withinTimeRange setting

### ISSUE THREAD

**Issue by CatTail** [akka/akka#27590]
BackoffOnRestartSupervisor use [supervisorStrategy to handle child crash](https://github.com/akka/akka/blob/acee1b41853c6c882a6fbeba588aa6700c8da883/akka-actor/src/main/scala/akka/pattern/internal/BackoffOnRestartSupervisor.scala#L48-L54), the following is how it handle `strategy.withinTimeRange`, when `restartCount == 0` we will send a `ResetRestartCount(0)` message, 

```scala
  case Restart =>
    if (strategy.withinTimeRange.isFinite && restartCount == 0) {
      // If the user has defined a time range for the maxNrOfRetries, we'll schedule a message
      // to ourselves every time that range elapses, to reset the restart counter. We hide it
      // behind this conditional to avoid queuing the message unnecessarily
      val finiteWithinTimeRange = strategy.withinTimeRange.asInstanceOf[FiniteDuration]
      system.scheduler.scheduleOnce(finiteWithinTimeRange, self, ResetRestartCount(restartCount))
    }
```

However [when supervisor receive that message](https://github.com/akka/akka/blob/acee1b41853c6c882a6fbeba588aa6700c8da883/akka-actor/src/main/scala/akka/pattern/HandleBackoff.scala#L50-L53), we only reset the counter when `current == restartCount`, note `current` is 0, the restartCount will never reset after `withinTimeRange`,

```scala
    case ResetRestartCount(current) =>
      if (current == restartCount) {
        restartCount = 0
      }
```

Here is the [reproduce snippet](https://github.com/CatTail/scala-playground/blob/96da504ce0db4b3b85afc5b95e5cc4defe91d22f/src/test/scala/com/example/playground/AkkaActorSpec.scala#L76-L97) that `withinTimeRange` not working even with a very small value.

**Comment by johanandren** [comment]
Thanks for the reproducer. Would you be up for trying out PR:ing a fix?

**Comment by CatTail** [comment]
Hey, do you mean create an PR to fix this issue?

**Comment by johanandren** [comment]
Yep, no pressure though :)
