### ISSUE TITLE
Deprecate akka-actor-typed methods in release-2.5 that were removed in master

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#27606]
* [ ] `akka.actor.typed.Behavior.same` and similar ones are gone in 2.6 in favor of `akka.actor.typed.scaladsl.Behaviors.same` etc. (Those were not marked `@ApiMayChange` before?)

**Comment by patriknw** [comment]
Everything `-typed` are `ApiMayChange` and we have made rather many API changes that will all be released in 2.6.0, and mentioned in migration guide. We will not deprecate in 2.5.x.

**Comment by jrudolph** [comment]
Yeah, that's right. I was a bit confused because we have some `@ApiMayChange` markers in 2.5 akka-actor-typed but they were not applied consistently.

**Comment by patriknw** [comment]
I can imagine that they have been used at a few top places but not sprinkled to each and every member.
