### ISSUE TITLE
deprecate UntypedAbstractActor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27630]
Has served its purpose as migration utility from UntypedActor to AbstractActor.

**Comment by helena** [comment]
I had this deprecated in my PR but it was asked to be reverted. Shall I do the same (what I added then removed per review feedback) for this in a separate PR?

**Comment by patriknw** [comment]
Yes, please deprecate it.

My objection in the other PR was that it was renamed, and deprecating it was also unrelated to untyped -> classic.

**Comment by helena** [comment]
Thanks for clarrifying.

**Comment by helena** [comment]
Did we want to also add the Classic version to suggest using instead, which was also in the other PR?

**Comment by patriknw** [comment]
> Did we want to also add the Classic version

no, replacement is to use plain `AbstractActor`

The purpose of this was to provide a smooth migration path from UntypedActor to AbstractActor, but enough time has passed for that now.

**Comment by patriknw** [comment]
well, I misremembered. Reading the ScalaDoc the purpose was to be an optimization.

Anyhow, we shouldn't introduce a new class just for renaming it. Either we deprecate it and say that AbstractActor is the replacement, or we keep it as is.

**Comment by johanandren** [comment]
I think we should keep it for the optimization and close this ticket.

**Comment by patriknw** [comment]
I'm fine with that
