### ISSUE TITLE
backport some toClassic methods to 2.5 branch

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27649]
Causing trouble for downstream projects to not have the same methods in 2.5 and 2.6, for example in Akka Http.

We could add some (all?) of the toClassic methods in 2.5 and then start using that.

When this is done we should also update the doc sample code in Akka Http, see https://github.com/akka/akka-http/pull/2687

**Comment by johanandren** [comment]
Backport merged, waiting for a 2.5 release so we can update Akka HTTP  dep. and sample
