### ISSUE TITLE
Failed: FlowGroupBySpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27662]
https://jenkins.akka.io:8498/job/akka-nightly/6908/testReport/junit/akka.stream.scaladsl/FlowGroupBySpec/groupBy_must_work_with_random_demand/

One of the tests leaking streams somehow.

I thought I fixed this in one of the materializer PRs but apparently not.

**Comment by johanandren** [comment]
Managed to repeat it locally once in like 50 runs

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/354/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6920/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/17413/
