### ISSUE TITLE
Adapter support for snapshots

### ISSUE THREAD

**Issue by jchapuis** [akka/akka#27671]
It would be awesome if it was possible to define adapters for snapshots in Akka Typed Persistence, as is possible for events. 

This would allow for a single generic snapshot serializer implementation (`ScalaPbSerializer` typically for protobuf) and domain-to-proto mapping code in the adapter, instead of tackling both concerns in the serializer (which thus has to be specific).

**Comment by patriknw** [comment]
That's already supported, see `snapshotAdapter` in 2.6.0-M7.
Let us know if that is what you are looking for, and we can close the issue.

**Comment by jchapuis** [comment]
great, exactly what we needed, thanks Patrik!
