### ISSUE TITLE
Rename LoggingEventFilter

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27702]
@raboof mentioned that we should consider renaming `LoggingEventFilter`.

The background is that classic `EventFilter` wasn't only about testing expected logging but also a way to silence logging output. LoggingEventFilter is not for that latter concern. It's not filtering the output.

Therefore, a name that would fit the purpose better might be `ExpectLogging` (similarity to `expectMessage`).

On the other hand LoggingEventFilter is a way to define a criteria, a filter, and then `intercept` is asserting the expected events. That might be a too "how it's implemented" view though.

**Comment by johanandren** [comment]
Perhaps align with the other testkit things `LoggingTestKit.info().intercept { ... }` 

If we're going to repaint we might as well repaint the whole bikes her? `.intercept {}` when it isn't really about intercepting but rather `.expect {}` or `.assertLogged {}`?

**Comment by chbatey** [comment]
I like `LoggingTestKit`, it makes it more clear (at least to me) that it is for testing logs

> .expect {}

:+1:
