### ISSUE TITLE
Consistent hashing router in Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27729]
I have got votes from this from several persons so I think we should add it. Not critical for 2.6.0 though.

**Comment by navaro1** [comment]
@patriknw Could you provide few links to the resources and short description what actually needs to be done?

**Comment by patriknw** [comment]
The API for defining such router would be added in https://github.com/akka/akka/blob/master/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/Routers.scala

**Comment by navaro1** [comment]
I will take it then! :)

**Comment by patriknw** [comment]
Thanks, feel free to create a draft PR for early feedback when you have some first implementation in place

**Comment by navaro1** [comment]
@patriknw, just to be sure - this should be added as a class implementing `RoutingLogic[T]`, not `Behaviour[T]`, right?

I mean - it should not be a _new_ router next to existing `GroupRouter[T]` or `PoolRouter[T]`? It should be a routing logic next to existing `RandomLogic[T]` and `RoundRobinLogic[T]`? Or am I wrong and/or missing something?

**Comment by patriknw** [comment]
@navaro1 yes, that sounds right. new RoutingLogic, that can be used with existing GroupRouter  and PoolRouter

**Comment by navaro1** [comment]
@patriknw Very basic and minimal implementation (basically an early draft) is available here: https://github.com/akka/akka/pull/28064/files

Looking forward to getting any tips.

**Comment by navaro1** [comment]
@patriknw I have one more question about how to proceed with testing: https://github.com/akka/akka/pull/28064#discussion_r341281319

**Comment by navaro1** [comment]
@patriknw https://github.com/akka/akka/pull/28141 <- PR is ready to be reviewed.
