### ISSUE TITLE
Add full package path or api-doc-link to a type in docs that uses `@scala` `@java`?

### ISSUE THREAD

**Issue by helena** [akka/akka#27739]
Suggestion: https://github.com/akka/akka/pull/27708#discussion_r325235632
 
```
@scala[`ActorRef[ClusterCommand]`]@java[`ActorRef<ClusterCommand>`] where a `ClusterCommand` is a command such as: `Join`, `Leave` and `Down`
```

**Comment by helena** [comment]
Probably good to chat about before 2.6 release with all the docs changes.

**Comment by johanandren** [comment]
We do have the `@apiDoc[type]` directive for those, so makes sense to use?

**Comment by helena** [comment]
Yes, shall I close this? I think not needed.
