### ISSUE TITLE
Replacement for Persistence mode with Sharding rememberEntities

### ISSUE THREAD

**Issue by helena** [akka/akka#27763]
Breakout (for doc link reasons) of the larger replacement work for pluggable storage with `rememberEntities` (the `ShardCoordinator` state is fine with ddata mode) https://github.com/akka/akka/issues/26177
 
* With K8 environments file storage used for durable ddata can be problematic
* With remember entities ddata mode could be limiting since id of each active entity must be stored

https://github.com/akka/akka/issues/26177#issuecomment-470904515
> We might have to add a pluggable API for the state storage of rembered entities since file based storage isn't very cloud friendly. Could be another implementation of DData durable storage.

- [x] A solution for remember entities would be to not use ddata for that state. Instead define a pluggable data access API, backed by implementations for Cassandra and JDBC. DData implementation could also be an option for when not using too many entities and for development mode. https://github.com/akka/akka/issues/26177#issuecomment-505538584
- [x] At the same time we should clean up the implementation of the inheritance based Shard, DDataShard, PersistentShard (now deprecated) classes that have become rather complicated. Better would be to separate the remember entities concern in a separate "entity tracker" actor (or class), which would be responsible for that part, and the interaction with the DB access API. https://github.com/akka/akka/issues/26177#issuecomment-505538584

**Comment by patriknw** [comment]
Problems with current solution:
* High latency overhead for starting and stopping entities. This is especially a problem for short lived entities, for example representing payment transactions.
* The implementation of the inheritance based `Shard`, `DDataShard`, `PersistentShard` classes that have become rather complex. Difficult to understand and change.
* File based durable storage (with lmdb) doesn't work well in in Kubernetes.
* Scalability. Number of started entities is restricted by ddata limitations.
* Some users have tried to enable it to reduce latency for the first message after rebalance. Thinking that the entity would already be started when the first message arrives. The other performance problems have probably caused more trouble than what this solved. Using it without durability was a recommendation in those cases.

**Comment by patriknw** [comment]
Information that must be stored:
* Active entities for each shard. Updated by the Shard when an entity is started and passivated.
* All shards. Updated by the Coordinator when a new shard is allocated. When coordinator is started it must startup known shards, which will start the entities.

**Comment by patriknw** [comment]
Non-solutions:
* Store the Set of active entities in one single blob from each Shard. The amount of data to store for each change will be too large when using many entities.
* Guarantee both started and stopped. I think it's most important to ensure that started entities are started up again, and in certain edge cases start entities that have been stopped. The entity should be able to know itself that it should stop again.
* One question is if we can always update the durable state before starting the entity or if that still adds too much latency? If we store this as write-behind, i.e. start the entity before confirmation that the durable update has completed, we need some other redundancy to ensure that the durable state update is performed even though the node of the shard is crashing.

**Comment by patriknw** [comment]
A possible storage SPI without generalizing it:

```
def addEntity(shardId: String, entityId: String): Future[Done]

def removeEntity(shardId: String, entityId: String): Future[Done]

def getAllShards(): Future[Set[String]]

def getEntities(shardId: String): Future[Set[String]]
```

When seeing it like that I amend my previous comment about that the Coordinator would update the allShards. The coordinator needs `getAllShards`, but the updates of that can be done by the Shard via `addEntity`.

**Comment by patriknw** [comment]
Maybe we can even start by having an implementation of that SPI using event sourcing, to leverage existing Akka Persistence plugins instead of having DB specific implementations.

Another implementation could be with ddata, which can be good when the full cluster shutdown durability isn't needed, and for development environments.

**Comment by johanandren** [comment]
Breaking parts we know out in a few smaller items and created a project over in https://github.com/akka/akka/projects/8

**Comment by helena** [comment]
Nice!
