### ISSUE TITLE
thenNoReply is problematic

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#27769]
I realised that the method `thenNoReply` is problematic. The documentation states two cases where one could use that method: 1) when you consciously decide that you don't want to send a reply; 2) when you are going to send a reply later.

Case 2 makes sense, but I think case 1 problematic because we are breaking the contract. 

The contract is established when we decide to use enforced replies. That forces all incoming commands to extend `ExpectingReply`. That means that any command will have a `replyTo`, so the contract is establishing that there will be a reply, but that maybe never happen. 

Of course, the "later reply" case can also never happen. 
If that's a timeout because of 2, meaning the "reply later" took too long, it's just how it is. However, if that's because of 1 we are just breaking the contract. And when this is done between two actors, it's less visible. The message is never send to the `replyTo` mailbox. When sending commands from outside the actor system, ie: using `ask`, that will result in Future timeouts because we are not fulfilling the contract.

I find it unlikely that for one same command type, we were going to sometimes use case 1 and sometimes case 2. When I decide to use `thenNoReply` for case 2, that's a valid situation. The case 1 will only happen when we actually don't want to send replies, but we are forced to encode it because we are extending `ExpectingReply`. In other words, becasue some messages require a reply I'm now oblied to have a `replyTo` in all commands and I have to break the contract for the messages that should not have a reply. And I force the user to use `ask` while we are not planning to fulfill the contract.

I think we can solve this issue with following changes.

- remove `ExpectingReply`, we keep `ReplyEffect` and `withExpectingReplies`
- users add `replyTo` whenever they want, but can have commands without it. They choose. 
- redefine signature to `thenReply(ActorRef[T])(State  => T)`
- Commands without a `replyTo` are explicitly not to be used with a `ask`. We just `tell`, and the behaviour correctly calls `thenNoReply` to fill the contract.

There is the risk that a user uses another `ActorRef[T]` and not the one passed via command, but that risk exists already. If someone wants to trick the system they can still do it, for instance `cmd.copy(replyTo = anotherActorRef)` and then use this copy on the `thenReply`. 

There  is also a positive side on that change, we will not need to write the following anymore:

```scala
case cmd @ Deposit(amount, _) =>
	Effect
		.persist(Deposited)
		.thenReply(cmd)(_ => Accepted)
```

Instead, we will be able to write:

```scala
case Deposit(amount, replyTo) =>
	Effect
		.persist(Deposited)
		.thenReply(replyTo)(_ => Accepted)
```

The pattern matching becomes much more idiomatic.

Also, we have less API and therefore less things to learn. A user only needs to understand they need to add a `replyTo`, choose for `ReplyEffect` and call `thenReply`. That's all. 

I can send a PR if we agree with this proposal.

**Comment by patriknw** [comment]
I think the original intention was that all commands should have replies when using `withEnforcedReplies` to make it very guarded and guided.

I'm in favor of loosing it up and your suggestion sounds good to me.

**Comment by patriknw** [comment]
Just mentioning that an alternative might be to keep everything as is apart from changing the signature:
```
def withEnforcedReplies[Command <: ExpectingReply[_], Event, State](
```
to not require that all commands must implement ExpectingReply:
```
def withEnforcedReplies[Command, Event, State](
```

However, the `ExpectingReply` is not adding anything other than forcing the commands to be defined in a certain way, and that might also be seen as a negative aspect.

I'm in favor of removing ExpectingReply, but just wanted to mention the possibility.

**Comment by renatocaval** [comment]
@patriknw, I think I have done the same path. I first thought about changing only the signature of `withEnforcedReplies` to then realise that `ExpectingReply` is not adding much.

It also looses the usage of `thenReply`. We won't need to a `ExpectingReply` anymore. We can use it whenever we have a `replyTo: ActorRef[T]` in scope.

**Comment by patriknw** [comment]
Good, will you PR the changes?

**Comment by renatocaval** [comment]
yes, I'm busy already
