### ISSUE TITLE
AtLeastOnceDelivery SetDeliverySnapshot not consistent with piecemeal recovery

### ISSUE THREAD

**Issue by juanavelez** [akka/akka#27786]
I am using Akka version 2.5.21 with Akka Persistence with AtLeastOnceDelivery. I am in the process of testing a Persistent Actor when doing recovery both piecemeal and from a snapshot. I found out that if my actor dies before there is a chance to perform a snapshot when the persisted messages are recovered (and these messages call deliver), upon recoveryComplete, all the unconfirmed messages are "resent" because their timestamp is before the "now" considered within redeliverOverdue., However if I test recovering from a snapshot, no "deliver"s are called. I tracked it to this 

in internalDeliver

```
    val deliveryId = nextDeliverySequenceNr()
    val now = if (recoveryRunning) { System.nanoTime() - redeliverInterval.toNanos } else System.nanoTime()
    val d = Delivery(destination, deliveryIdToMessage(deliveryId), now, attempt = 0)
```

but in setDeliverySnapshot (which I call when I received a SnapshotOffer)

```
  /**
   * If snapshot from [[#getDeliverySnapshot]] was saved it will be received during recovery
   * in a [[SnapshotOffer]] message and should be set with this method.
   */
  def setDeliverySnapshot(snapshot: AtLeastOnceDeliverySnapshot): Unit = {
    deliverySequenceNr = snapshot.currentDeliveryId
    val now = System.nanoTime()
    unconfirmed = scala.collection.immutable.SortedMap.from(snapshot.unconfirmedDeliveries.iterator.map(d ⇒
      d.deliveryId → Delivery(d.destination, d.message, now, 0)))
  }
```

The difference is the now is set differently for a piecemeal recovery than for a snapshot but the redeliverOverdue is based off the piecemeal. I am not sure which one should be correct.

BTW, In my tests I changed the default redeliver interval from 5 seconds (default) to 2 minutes for my actor being tested

**Comment by patriknw** [comment]
@juanavelez Thanks for reporting. The issue fell between the cracks. We'll look into it. Sounds like it should be consistent for least surprise.

**Comment by juanavelez** [comment]
> @juanavelez Thanks for reporting. The issue fell between the cracks. We'll look into it. Sounds like it should be consistent for least surprise.

Almost a year since reporting the issue, wondering if there is any progress making it consistent for both? Ty!

**Comment by patriknw** [comment]
We have focused on the new [Reliable Delivery](https://doc.akka.io/docs/akka/current/typed/reliable-delivery.html), which has many improvements of AtLeastOnceDelivery. For example flow control based on consumer demand, also when redelivering messages after restart.

The only thing needed here is to change the `now` in setDeliverySnapshot:
```
val now = System.nanoTime() - redeliverInterval.toNanos
```

The reason for "faking" the time by reducing by the redeliverInterval is that then it will be sent on next tick.

I can fix that next week, or you can open a pull request yourself if you like?

**Comment by juanavelez** [comment]
> We have focused on the new [Reliable Delivery](https://doc.akka.io/docs/akka/current/typed/reliable-delivery.html), which has many improvements of AtLeastOnceDelivery. For example flow control based on consumer demand, also when redelivering messages after restart.
> 
> The only thing needed here is to change the `now` in setDeliverySnapshot:
> 
> ```
> val now = System.nanoTime() - redeliverInterval.toNanos
> ```
> 
> The reason for "faking" the time by reducing by the redeliverInterval is that then it will be sent on next tick.
> 
> I can fix that next week, or you can open a pull request yourself if you like?

Thank you for the update and letting us know about the new Reliable Delivery mechanism. We can wait until next week.
