### ISSUE TITLE
Serializer missing for ShardRegion$RestartShard

### ISSUE THREAD

**Issue by RibleStrype** [akka/akka#27782]
I encountered the following error messages in logs today:
`ERROR a.r.EndpointWriter Failed to serialize remote message [class akka.cluster.sharding.ShardRegion$RestartShard] using serializer [class akka.serialization.DisabledJavaSerializer]. Transient association error (association remains live)`
We are using `2.5.25` version of akka with java serialization disabled.
Shouldn't this message be handled by `ClusterShardingMessageSerializer`? apparently now it isn't.

**Comment by patriknw** [comment]
Thanks for reporting. It's surprising because `RestartShard` should only be sent to the local `self` so it shouldn't be sent with remoting and being serialized. We need to investigate how that can happen.

**Comment by helena** [comment]
Logic around this is if: 
1. a watched shard terminates
1. and that shard is not `handingOff`
1. and `rememberEntities` is enabled
a `RestartShard(terminatedShardId)` is sent to `self` (the `ShardRegion`).

But there's this interesting comment in `ShardRegion`: 
```
// must drop requests that came in between the BeginHandOff and now,
// because they might be forwarded from other regions and there
```

**Comment by helena** [comment]
Found it, just need to replicate.

**Comment by helena** [comment]
There is a `foreach`where it was re-sending all buffered messages, but now we will filter out any `RestartShard` messages from those sent. We need to decide what we want to do with those:
* Direct elsewhere and send, and if so, where
* Drop (does not sound like an option)
* other
