### ISSUE TITLE
Akka Sharding Proxy is unable to contact with Shard Coordinator

### ISSUE THREAD

**Issue by satyanjosyula** [akka/akka#27816]
I'm building an application with node roles on Akka 2.5.13. The shard initialisation is as follows..

    ClusterSharding(system).start(
      typeName = regionName(processType.oid),
      entityProps = ProcessManager.props,
      settings = ClusterShardingSettings(system).withRole(role),
      extractEntityId = extractEntityId,
      extractShardId = extractShardId,
      allocationStrategy = allocationStrategy,
      handOffStopMessage = handOffStopMessage )

In config, it is defined, 

 akka.cluster.roles = {"A"}

It is expected that, each node with the given role("A") is expected to create a shard region with the given role("A")  and a proxy region on the node where that role("A") is not defined.  

The proxy node is giving the following message and unable to deliver the message to shard..

10:47:57.443 [SYSTEST1-akka.actor.default-dispatcher-30] WARN  akka.cluster.sharding.ShardRegion - Retry request for shard [shard-4] homes from coordinator at [Actor[akka.tcp://SYSTEST1@127.0.0.1:2553/system/sharding/region-SYSTEST1-10247707Coordinator/singleton/coordinator#-88087379]]. [1] buffered messages.

Help would be really appreciated. Many Thanks   SJo

**Comment by patriknw** [comment]
If you are still looking for help with this question I'd recommend asking at https://discuss.akka.io.

Hi, we use github issues just for bugs and feature requests. That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).
