### ISSUE TITLE
Framing.lengthField with computed frame sizes

### ISSUE THREAD

**Issue by ecartner** [akka/akka#27884]
I was asked to open an issue here following a post I made on [Disscuss Lightbend](https://discuss.lightbend.com/t/stream-framing-without-delimiter-or-length-field/5172/3).

I'm using the `akka.stream.scaladsl.Framing.lengthField` variant that takes a `computeFrameSize` function as an argument. The data I'm working with has a four byte header at the start of every frame. Each header consists of a 12 bit sync word (0xFFF) followed by 20 bits containing a number of fields.

`lengthField()` calls my frame size calculation function and it passes in the values I expect to see. I've also verified I'm returning the number of bytes in the frame excluding the four bytes of the header. However, `lengthField()` then fails, reporting a negative frame size. The value it reports is the value of the four byte header when treated as a 32 bit big endian integer. For example, given a four byte header of FF F8 00 00 the frame size in the error message is -524288 even though my frame size calculation returned the correct value (12 in the simplified tests I was running).

It seems like when `lengthField()` is provided a function to calculate a frame size it shouldn't be concerned about the value of the header/field it passes to that function.

I've created a simple project to demonstrate this behavior on placed it on [GitHub](https://github.com/ecartner/akka-stream-framing).

**Comment by johanandren** [comment]
Thanks for fixing this @ecartner !
