### ISSUE TITLE
Revisting type hint for PersistenceId

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#27924]
When we discussed the changes on the `PersistenceId` [here](https://github.com/akka/akka/pull/27725#discussion_r326573212) I thought we would go for 

```scala
PersistenceId(entityId)

PersistenceId(entityId, entityEntityHint)

PersistenceId(entityId, entityEntityHint, separator)
```

But I just realised that we actually have

```scala
PersistenceId(entityId)

PersistenceId(entityEntityHint, entityIdj)

PersistenceId(entityEntityHint, entityId, separator)
```

I don't know if that was intentional or not, but I find it confusing to have `entityId` appearing at first position (first constructor) and then on the second position. Can we reconsider the ordering?

At some point, I have also suggested a fluent API to avoid swapping the arguments without realising that the state of `PersistenceId` is only one single string and such a fluent API would require a complex builder. 

If we reconsider ordering of the constructors, I would like to drop a new variation of the fluent API. Instead we could have the following:

```scala
class PersistenceId(id: String) {
	def withTypeHint(hint:String) = new PersistenceId(s"$hint|$id")
	def withTypeHint(hint:String, sep: String) = 
		new PersistenceId(s"$hint$sep$id")
}
```

That won't require a complex builder but will guide the user in doing the right thing. It makes the API declarative e non error-prone.

**Comment by chbatey** [comment]
:+1:  to the `withTypeHint` and avoiding having the multi string ctr

**Comment by patriknw** [comment]
The single String parameter is the raw persistenceId String, not the entityId. `PersistenceId(id)`.
We could clarify by naming the parameter `rawId`.

The problem with the builder approach is that then users will not see that they should use the `with` methods and will only specify the entityId as the raw persistenceId.

We could rename `apply(id)` to something more clarifying. `ofRawId`. Not sure if the word raw is very good. Then `apply` (and `of` for java) becomes the normal case, and the rawId is special power user api.

**Comment by patriknw** [comment]
s/rawId/uniqueId/

**Comment by renatocaval** [comment]
@patriknw, I agree with your point about users not immediately seeing that they should call `withTypeHint`. 

If I understand you correctly, your proposal is to have two constructors, ie: `(hint: String, uniqueId: String)` and `(hint: String, uniqueId: String, sep: String)`. 

And then a method on the companion object called `ofUniqueId(id: String)` that would set the `typeHint` to an empty string.

That looks a better approach compared to the current implementation. I can send a PR by the end of the week.

**Comment by patriknw** [comment]
agreed, apart from that the parameters should still be named `entityTypeHint: String, entityId: String`.

`ofUniqueId(id: String)` is fine.

I can do this change tomorrow if you are busy.

**Comment by renatocaval** [comment]
@patriknw, I will only have time for it tomorrow. Feel free to pick if you want.
Thanks.
