### ISSUE TITLE
Potential stream memory leak

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27948]
Repeater and details in https://discuss.lightbend.com/t/memory-leak-of-repointableactorref-due-to-race-condition/3073

I haven't verified but we should look into it, so creating this to not forget doing that.

**Comment by patriknw** [comment]
Marking this as `bug` so that we don't forget to investigate it. Seems serious if it's true.

**Comment by johanandren** [comment]
Should be fixed in 2.6.0 since we have eliminated `RepointableActorRef` usage for the materializer there, but possibly still a problem in 2.5 (and therefore playframework 2.6, 2.7)

**Comment by johanandren** [comment]
I could not repeat a memory leak with the provided reproducer on 2.5, stopping with the investigation for now.

**Comment by johanandren** [comment]
Closing this as we got no new information about it happening for half a year.
