### ISSUE TITLE
StreamRefSpec failure on 2.5 branch

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27957]
Something partially backported around the cancellation propagation perhaps?

There were changes to the same spec in master.

https://jenkins.akka.io:8498/job/akka-release-2.5-2.11/64/consoleText

```
java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for failed-system-42-tmp
at scala.Predef$.assert(Predef.scala:170)
at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:418)
at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:395)
at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
at akka.cluster.StreamRefSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StreamRefSpec.scala:246)
at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:383)
at akka.cluster.StreamRefSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply$mcV$sp(StreamRefSpec.scala:245)
```

**Comment by patriknw** [comment]
Looks like the backport in https://github.com/akka/akka/pull/27962 wasn't enough. Failed again in `akka-release-2.5-2.13` job.

```
[info] [JVM-3]   java.lang.AssertionError: assertion failed: timeout (7 seconds) during expectMsg while waiting for failed-system-42-tmp
[info] [JVM-3]   at scala.Predef$.assert(Predef.scala:282)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:404)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:404)
[info] [JVM-3]   at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
[info] [JVM-3]   at akka.cluster.StreamRefSpec.$anonfun$new$27(StreamRefSpec.scala:254)
[info] [JVM-3]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:383)
[info] [JVM-3]   at akka.cluster.StreamRefSpec.$anonfun$new$14(StreamRefSpec.scala:246)
```

https://jenkins.akka.io:8498/job/akka-release-2.5-2.13/71/consoleText

**Comment by johanandren** [comment]
Here's a debug log with a failure. I see no `OnSubscribeHandshake` being received on the side where the stream is not failed, which should then trigger a subscription timeout roughly 5 seconds after `Allocated receiver` at 17:04:23.931, that never happens so I wonder if this is perhaps because of the timeout scheduling getting lost because of `TimerGraphStage` calling `getAsyncCallback` on the wrong thread #27999

[streamrefs-fail.txt](https://github.com/akka/akka/files/3730220/streamrefs-fail.txt)
