### ISSUE TITLE
Make typed.ActorSystem.scheduler implicit

### ISSUE THREAD

**Issue by jroper** [akka/akka#27968]
Since a typed ask requires an implicit scheduler, could we make `akka.actor.typed.ActorSystem.scheduler` implicit? This just makes a very minor improvement to code, it means you can:

```scala
import system.scheduler`
```

instead of having to

```
implicit val scheduler = system.scheduler
```

**Comment by jroper** [comment]
An alternative could be to offer:

```
implicit def schedulerFromActorSystem(system: typed.ActorSystem): typed.Scheduler = system.scheduler
```

on `AskPattern`, then using the ask pattern would only require making an implicit `ActorSystem` available.

**Comment by patriknw** [comment]
I think both options are good, and we can also factor in that the recommended way to run streams is with an `implicit ActorSystem` so maybe the second is better, but we could do both.

We already have `implicit def executionContext` in ActorSystem.

wdyt @johanandren ?

**Comment by johanandren** [comment]
The implicit conversion sounds like a good idea to me. Perhaps not future proof (Scala 3) but I think that is fine.

**Comment by patriknw** [comment]
ok, could you add that @johanandren ?
