### ISSUE TITLE
Cannot instantiate typed scaladsl replicator consistencies without new keyword

### ISSUE THREAD

**Issue by jroper** [akka/akka#27997]
I assume its the intention that the following should be possible with the typed scaladsl `Replicator` API:

```scala
val writeMajority = Replicator.WriteMajority(timeout)
```

That doesn't compile, because `Replicator.WriteMajority` is a type, and so can't be used to refer to the `WriteMajority` companion object `apply` method. So this compiles:

```scala
val writeMajoriy = new Replicator.WriteMajority(timeout)
```

To allow `WriteMajority` to be instantiated as if it were a case class, the following method needs to be defined on the typed `Replicator`:

```scala
def WriteMajority(timeout: FiniteDuration, minCap: Int = DefaultMajorityMinCap) = dd.Replicator.WriteMajority(timeout, minCap)
```

or alternatively:

```scala
object WriteMajority {
  def apply(timeout: FiniteDuration, minCap: Int = DefaultMajorityMinCap) = dd.Replicator.WriteMajority(timeout, minCap)
}
```

**Comment by patriknw** [comment]
Thanks, that's an oversight. I'll fix right away.
