### ISSUE TITLE
Publish lifecycle events for Artery

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28003]
Requested in https://discuss.lightbend.com/t/remotinglifecycleevent-with-artery/4915 and maybe related to our other discussions about how to publish more structured events than plain logging.

**Comment by patriknw** [comment]
Pull request for the structured log events is in https://github.com/akka/akka/pull/28209

Those log events are published to the `eventStream` as `LogEventWithMarker` and it's possible to subscribe to them with an Actor like this:

```
  class ConnectedListener extends Actor {

    context.system.eventStream.subscribe(self, classOf[LogEventWithMarker])

    override def receive: Receive = {
      case event: LogEventWithMarker =>
        if (event.marker.name == "akkaConnected")
          println(s"# Connected to ${event.marker.properties("akkaRemoteAddress")}")
        else if (event.marker.name == "akkaDisconnected")
          println(s"# Disconnected ${event.marker.properties("akkaRemoteAddress")}")
    }
  }
```

The specific Artery TCP connected/disconnected event that was requested here are included, but note that it's logged at DEBUG level so enabling that level is required for consuming them with the listener shown above.

I understand that this might be seen as a not so nice stringly typed api, but the design has been driven by the primary purpose of consuming these events via logging backend infrastructure such as ELK-stack.

The marker and property names are documented in PR #28209, see the addition in logging.md

**Comment by igorfialko** [comment]
So if I want to use it in production but don't want debug level logging then it doesn't work? In meanwhile I just ping target actor to see if it's up or down to adjust state of this actor accordingly. Doesn't artery do it internally already?

**Comment by patriknw** [comment]
Our general recommendation is to use Slf4j/Logback for production logging and then the `akka.loglevel` should be set to `DEBUG` and then more fine grained filtering can be done with the logging backend configuration (logback.xml). https://doc.akka.io/docs/akka/current/typed/logging.html#slf4j-backend
