### ISSUE TITLE
PersistenceQuery.get(actorSystem) with typed ActorSystem

### ISSUE THREAD

**Issue by olijaun** [akka/akka#28054]
Currently it seems not to be possible to get a PersistenQuery (or a ReadJournal) with a typed ActorSystem:

`readJournal = PersistenceQuery.get(actorSystem).getReadJournalFor((Class<ReadJournal>) Class.forName(readJournalClassName), readJournalIdentifier);`

I think this should be possible.

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

I'm pretty sure this is possible by using the toClassic adapter, but please ask over there and I can elaborate.

**Comment by olijaun** [comment]
OK, thanks, I'm sorry.
