### ISSUE TITLE
Replicator$Unsubscribe MatchError in ReplicatorBehavior

### ISSUE THREAD

**Issue by dwijnand** [akka/akka#28061]
In porting akka-sample-distributed-data-scala to the typed API I've seen scala.MatchError when using the unsubscribe feature of the ReplicatorAdater.

See https://github.com/akka/akka-samples/pull/134#issuecomment-546099443

**Comment by patriknw** [comment]
Thanks for finding and reporting this. Looks like a bug. Let's fix for RC2.
