### ISSUE TITLE
akka-slf4j Slf4jLogger removes all MDC properties not set by Akka

### ISSUE THREAD

**Issue by atooni** [akka/akka#28077]
Hello, 

we are using SLF4J as a loging framework in our Akka application. Now we are moving towards capturing all our log output in splunk and therefore have set some properties on the applications MDC context, so that we can tell different instances of the application apart. 

Our problem is, that the SLF4J logger removes ALL keys from the MDC context, not only the ones that have been set by akka itself. Therefore, after the first log that Akka pereforms, our own properties are lost. 

The line in SLF4JLogger is 
https://github.com/akka/akka/blob/master/akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala#L118

Best regards 
Andreas

**Comment by patriknw** [comment]
I think this is a misunderstanding of how MDC is supposed to be used.

Those MDC values come from the LogEvent, which you emit from your code with LoggingAdapter.info and similar methods. That doesn't mean that those will stay in MDC forever. They are specific for that LogEvent.

Also, in general without considering what Akka does the MDC is a ThreadLocal that is supposed to be populated for a specific request and and then cleared afterwards. You can't put things and in MDC and then later expect that those values are to be used by another Thread.

In the context of an actor, such request is for processing a single message in a specific actor.
