### ISSUE TITLE
Expose hint and entityId on PersistenceId

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#28082]
A possible solution to https://github.com/lagom/lagom/issues/2346 would be to make`entityId` available in `PersistenceId` instances (optionally we could also expose `entityTypeHint` and `separator` but these are not necessary for https://github.com/lagom/lagom/issues/2346 and are optional arguments to build `PersistenceId`).

I just realized `PersistenceId` was recently [turned into a _plain_ `class`](https://github.com/akka/akka/pull/27953/files#r333023816) so I think this could be achieved in a backwards compatible way.

I apologize for the terrible timing as Akka `2.6.0-RC2` was just released.

**Comment by ignasi35** [comment]
Please note https://github.com/lagom/lagom/issues/2346 is not a blocker for Lagom `1.6.0-GA` and could be part of a patch release of Lagom. What I mean by that is this issue might as well be on a patch release of Akka `2.6`.

**Comment by ignasi35** [comment]
cc @renatocaval

**Comment by patriknw** [comment]
if this is only for compatibility with Lagom, in the `AkkaTaggerAdapter`, can't that adapter split up the entityTypeHint and entityId  from the PersistenceId.id. It knows about possible separator formats.

**Comment by ignasi35** [comment]
> if this is only for compatibility with Lagom, in the `AkkaTaggerAdapter`, can't that adapter split up the entityTypeHint and entityId from the PersistenceId.id. It knows about possible separator formats.

There's a case where the separator is a `"|"` but there's a case where the separator is non existent. :-(

**Comment by patriknw** [comment]
I know, that why I wrote plural "formats". 2 is still a very small set that can be tried.
