### ISSUE TITLE
Failed: akka-artery-perf and akka-artery-tcp-perf

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28086]
https://jenkins.akka.io:8498/job/akka-artery-tcp-perf/1198/
https://jenkins.akka.io:8498/job/akka-artery-perf/2515/consoleFull

These started failing after a moxie update / restart.

The symptom is that the message rate drops down after the initial batches.

They can be reproduced reliably by running the failing tests on a4. These tests run on jenkins with `-Dmultinode.Daeron.mtu.length=16384`. With the default MTU of 1500 this leads to rampant UDP datagram fragmentation which probably leads to enough loss that the Aeron throughput drops down to almost zero.

The guess is that before the restart jumbo frames might have been enabled on the link. Even so these would only allow an MTU up to 9000 and not to 16384 but it would decrease fragmentation to two packets per datagram which might still work.

The solution is 
 * to either make permanent changes to moxie configurations to use jumbo frames and then configure a suitable aeron mtu for that configuration (e.g. 8992, must be multiple of 32)
 * or to keep the default MTU of 1500 in moxies and use the defaul mtu in aeron of 1402 (or increase it to 1472 which is the highest which seems to work without fragmentation in our network setup).

**Comment by patriknw** [comment]
Thanks for great detective work. The increased mtu is from [Aeron docs](https://github.com/real-logic/aeron/wiki/Performance-Testing#throughput-testing) but you are probably right that it was never made persistent. (somewhat strange that it haven't failed more often)

Let's first try with the default and see if we notice any difference in the graphs. Could be interesting in itself. I can change the jenkins jobs now.

**Comment by jrudolph** [comment]
I also found this https://github.com/real-logic/aeron/issues/202:

> With UDP the datagram can be larger than the Ethernet MTU. UDP will fragment the datagram and reassemble it again. This is done in the kernel and saves on system calls. If one fragment is lost then the whole datagram must be retransmitted but this does not tend to happen often on local networks that are not congested. The main cause of loss is incorrectly sized socket buffers. Aeron will flow control and so loss is not common with properly sized socket buffers.

And we have this in the logs as well:

```
[error] [JVM-1] WARNING: Could not get desired SO_SNDBUF, adjust OS to allow aeron.socket.so_sndbuf: attempted=2097152, actual=212992
[error] [JVM-1] WARNING: Could not get desired SO_RCVBUF, adjust OS to allow aeron.socket.so_rcvbuf: attempted=2097152, actual=212992
[error] [JVM-2] WARNING: Could not get desired SO_SNDBUF, adjust OS to allow aeron.socket.so_sndbuf: attempted=2097152, actual=212992
[error] [JVM-2] WARNING: Could not get desired SO_RCVBUF, adjust OS to allow aeron.socket.so_rcvbuf: attempted=2097152, actual=212992
```

So, that might be another setting to tweak if we want max performance.

**Comment by patriknw** [comment]
Things are working good with the mtu change, but let's keep this ticket open until we have tried tweaking a few more settings. Letting it run for a few more days with only the mtu change so we are sure the results are stable.

Looking at the first two days there are some noticeable difference.

**Comment by patriknw** [comment]
Results are looking good.

Now I have also removed `-Dmultinode.Daeron.socket.so_sndbuf=2097152 -Dmultinode.Daeron.socket.so_rcvbuf=2097152`

**Comment by patriknw** [comment]
all good, closing
