### ISSUE TITLE
Unable to override executor for pinned-dispatcher

### ISSUE THREAD

**Issue by ssgao** [akka/akka#28117]
Akka allows `PinnedDispatcher` to have a custom executor via https://github.com/akka/akka/blob/master/akka-actor/src/main/resources/reference.conf#L842-L845. Though this custom executor has to be of type `ThreadPoolExecutorConfigurator`. In reality, the value provided here is getting ignored. The reason is that `PinnedDispatcherConfigurator` uses the raw `threadPoolConfig` instead of the value returned by `configureExecutor()`. See https://github.com/akka/akka/blob/v2.5.12/akka-actor/src/main/scala/akka/dispatch/Dispatchers.scala#L284-L306.

**Comment by johanandren** [comment]
Given that the `PinnedDispatcher` runs a dedicated thread per actor configured I'm not sure that what a configured executor would do. Can you describe the use case or is it just an inconsistency you have noted?

**Comment by ssgao** [comment]
I had a custom executor that passes MDC context from thread to thread (save the one before and restore that after) so we are able to get request ID logging across all actors that are involved in processing the request.

I have noticed that selector runs in its own thread in a loop, and using a shared memory model to accept new events, but it does send messages to other actors, which breaks my attempt of propagating MDC context because the one coming from it (empty) will remove the context that I've been passing.

Any suggestions on how I can achieve this? What I'm currently doing is just put another wrap of MDC context saving/restoring around downstream request filing point in my code, but I'd much prefer it to be at a lower level if possible.

If it's not something akka should support, maybe remove this from reference.conf? since it's not really configurable.

**Comment by johanandren** [comment]
Thanks for the details.

There is support for context propagation for SLF4J as a part of of Lightbend commercial offerings: https://developer.lightbend.com/docs/telemetry/current/extensions/mdc.html

I don't think we can remove the setting since it is partially used, but we could certainly document that only parts of the configuration is actually used.

**Comment by patriknw** [comment]
It's not supposed to be possible to change the executor of PinnedDispatcher.

It's possible to plugin in your own dispatcher type, so if you need the low level powers it should be possible. See doc comment for `default-dispatcher.type` in reference.conf. At that level some digging into source code is expected to see what is needed.
