### ISSUE TITLE
Persisting a command is conceptually wrong

### ISSUE THREAD

**Issue by PavelKarasev** [akka/akka#28115]

**Comment by johanandren** [comment]
Yes, we agree. Did you find an example in the docs or some code doing that?

**Comment by PavelKarasev** [comment]
Paragraph in akka-typed docs, "Accessing the ActorContext".

https://doc.akka.io/docs/akka/2.6/typed/persistence.html?_ga=2.253425098.277358697.1572868100-1902149126.1572018710#accessing-the-actorcontext

BasicPersistentBehaviorCompileOnly.scala:203

----
commandHandler = CommandHandler.command { cmd =>
context.log.info("Got command {}", cmd)
Effect.persist(cmd).thenRun { state =>
context.log.info("event persisted, new state {}", state)
}
}

**Comment by johanandren** [comment]
Thanks, probably an oversight since the only purpose of that sample is to show how to access the actor context, not really how to implement an EventSourcedBehavior. Makes sense to be consistent though.

**Comment by YikSanChan** [comment]
is this covered by https://github.com/akka/akka/pull/28157 and can we close this?

**Comment by raboof** [comment]
Yes, thanks for the reminder!
