### ISSUE TITLE
Failed: JavaUdpMulticastTest.testUdpMulticast

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28147]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18060/testReport/junit/jdocs.io/JavaUdpMulticastTest/testUdpMulticast/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18061/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18069/

**Comment by patriknw** [comment]
Strange that this started failing suddenly. Could there be something wrong with `a4`?

```
[INFO] [11/07/2019 16:38:02.117] [JavaUdpMulticastTest-akka.actor.default-dispatcher-8] [akka://JavaUdpMulticastTest/user/$a] Bound to /0:0:0:0:0:0:0:0:60953
2019-11-07 16:38:02,118 INFO  jdocs.io.JavaUdpMulticast$Listener akka://JavaUdpMulticastTest/user/$a JavaUdpMulticastTest-akka.actor.default-dispatcher-8 - Bound to /0:0:0:0:0:0:0:0:60953
2019-11-07 16:38:02,122 INFO  jdocs.io.JavaUdpMulticast$Sender akka://JavaUdpMulticastTest/user/$b JavaUdpMulticastTest-akka.actor.default-dispatcher-7 - Sending message to /ff02:0:0:0:0:0:f2d5:ed71%eth0:60953
[INFO] [11/07/2019 16:38:02.121] [JavaUdpMulticastTest-akka.actor.default-dispatcher-7] [akka://JavaUdpMulticastTest/user/$b] Sending message to /ff02:0:0:0:0:0:f2d5:ed71%eth0:60953
2019-11-07 16:38:05,120 INFO  akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(JavaUdpMulticastTest) pool-1-thread-1 - Failed to run test on interface eth0
[INFO] [11/07/2019 16:38:05.120] [pool-1-thread-1] [akka.actor.ActorSystemImpl(JavaUdpMulticastTest)] Failed to run test on interface eth0
2019-11-07 16:38:05,123 INFO  jdocs.io.JavaUdpMulticast$Listener akka://JavaUdpMulticastTest/user/$c JavaUdpMulticastTest-akka.actor.default-dispatcher-7 - Bound to /0:0:0:0:0:0:0:0:56788
[INFO] [11/07/2019 16:38:05.122] [JavaUdpMulticastTest-akka.actor.default-dispatcher-7] [akka://JavaUdpMulticastTest/user/$c] Bound to /0:0:0:0:0:0:0:0:56788
2019-11-07 16:38:05,125 INFO  jdocs.io.JavaUdpMulticast$Sender akka://JavaUdpMulticastTest/user/$d JavaUdpMulticastTest-akka.actor.default-dispatcher-10 - Sending message to /ff02:0:0:0:0:0:add7:fbfd%eth0:56788
[INFO] [11/07/2019 16:38:05.125] [JavaUdpMulticastTest-akka.actor.default-dispatcher-10] [akka://JavaUdpMulticastTest/user/$d] Sending message to /ff02:0:0:0:0:0:add7:fbfd%eth0:56788
2019-11-07 16:38:08,124 INFO  akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(JavaUdpMulticastTest) pool-1-thread-1 - Failed to run test on interface eth0
[INFO] [11/07/2019 16:38:08.124] [pool-1-thread-1] [akka.actor.ActorSystemImpl(JavaUdpMulticastTest)] Failed to run test on interface eth0
2019-11-07 16:38:08,126 INFO  jdocs.io.JavaUdpMulticast$Listener akka://JavaUdpMulticastTest/user/$e JavaUdpMulticastTest-akka.actor.default-dispatcher-8 - Bound to /0:0:0:0:0:0:0:0:45416
[INFO] [11/07/2019 16:38:08.126] [JavaUdpMulticastTest-akka.actor.default-dispatcher-8] [akka://JavaUdpMulticastTest/user/$e] Bound to /0:0:0:0:0:0:0:0:45416
2019-11-07 16:38:08,128 INFO  jdocs.io.JavaUdpMulticast$Sender akka://JavaUdpMulticastTest/user/$f JavaUdpMulticastTest-akka.actor.default-dispatcher-8 - Sending message to /ff02:0:0:0:0:0:bf8f:e11b%eth0:45416
[INFO] [11/07/2019 16:38:08.128] [JavaUdpMulticastTest-akka.actor.default-dispatcher-8] [akka://JavaUdpMulticastTest/user/$f] Sending message to /ff02:0:0:0:0:0:bf8f:e11b%eth0:45416
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18089/testReport/junit/jdocs.io/JavaUdpMulticastTest/testUdpMulticast/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18090/console

**Comment by raboof** [comment]
I looked a bit as well, some observations:
* The test seems to succeed on a2 but fail on a4 (I think?). Both of these are on linux 4.15.0-66-generic
* I can reproduce it on my laptop. I do see the message in wireshark, but when listening for it I don't see it in 'socat' either (assuming I'm using that tool correctly)

**Comment by johanandren** [comment]
a4 has a "minikube" label on it, which a2 doesn't, are we doing some kubernetes testing on that machine, could there be some networking config change related to that?

**Comment by johanandren** [comment]
Giving up on this. Scala test passes because of a missing assertion that some multicast did in fact happen, so tests work the same.

Spent some time looking at config on a2 vs a4 without finding any difference in sysctl settings etc.

**Comment by johanandren** [comment]
Verified that it works on a2 but not a4:

* a2 https://jenkins.akka.io:8498/job/udp-multicast-test/3/console
* a4 https://jenkins.akka.io:8498/job/udp-multicast-test/1/console

**Comment by jrudolph** [comment]
Multicast itself seems to work using latest `socat` on a2 and a4 for me, basically following the instructions at http://www.dest-unreach.org/socat/doc/socat-multicast.html adapted for ipv6.

Unfortunately, socat has a bug until the very latest version 1.7.3.3 that prevents it from actually executing `ipv6-add-membership`, so I built socat 1.7.3.3 on a2 and put it into /tmp/socat on a2 and a4.

Run the listener on some hosts:

```
/tmp/socat UDP6-RECVFROM:6666,ipv6-add-membership=[FF12::1234]:eth0 EXEC:hostname
```


On one host, run

```
socat STDIO UDP6-DATAGRAM:[FF12::1234]:6666
```

and type a message on the console. After a newline, it should be acknowledged by all the hosts that listened on the group.

```
$ socat STDIO UDP6-DATAGRAM:[FF12::1234]:6666
Test
a2
a4
```

Not sure that helps, though. At least it seems to verify that multicast seems to work on both nodes in general.

**Comment by jrudolph** [comment]
Latest run on a4 seems to be successful: https://jenkins.akka.io:8498/job/udp-multicast-test/4/console

**Comment by johanandren** [comment]
So something updated in the last package update of the machine helped then I guess. I'll PR a re-enable of the tests.

**Comment by jrudolph** [comment]
Either that or just a reboot was necessary.
