### ISSUE TITLE
JsonFraming with context propagation

### ISSUE THREAD

**Issue by dcereijodo** [akka/akka#28158]
Context propagation is a quite common requirement when working with Akka Streams (#25394). On the other hand, the `JsonFraming` is very useful when working on JSON streams. For example, when streaming from JSON data on S3 I'd do something like this

```scala
import akka.stream.alpakka.s3.scaladsl.S3

val source = S3.download(bucketName, key)
source // simplified
  .collect { case Some(succesful) => succesful.bytestring }
  .via(JsonFraming.objectScanner(defaultBufferSize))
  .runForeach(println(_))
``` 

This will work as long as I don't need to print metadata from the request as well, in which case I have no way to propagate the context through the object scanner. A new method `objectScannerWithContext` with a signature `def objectScannerWithContext[Ctx](maximumObjectLength: Int): Flow[(ByteString,Ctx), (ByteString,Ctx), NotUsed]` would be useful to support the propagation of the metadata through the framing stage.

```scala
import akka.stream.alpakka.s3.scaladsl.S3

val source = S3.download(bucketName, key)
source // simplified
  .collect { case Some(succesful) => (successful.bytestring, successful.metadata) }
  .via(JsonFraming.objectScannerWithContext(defaultBufferSize))
  .runForeach(println(_))
```

**Comment by johanandren** [comment]
You can probably achieve this with something like 
```scala
source.prefixAndTail(1)
  .map { case (Seq(metadata), tail) =>
    tail.via(JsonFraming).map(obj => (obj, metadata))
  }.flatMapConcat(identity)
```

**Comment by dcereijodo** [comment]
Maybe I oversimplified my code snippet. This is how the whole thing looks like
```scala
// a flow that implements JSON framing with context
val framingWithContext: Flow[(ByteString, ObjectMetadata), (ByteString, ObjectMetadata), NotUsed] =
  JsonFramingWithContext.objectScanner(maximumFrameLength)

// a flow that maps S3 object keys to a tuple (contents, metadata)
val keyFlow: Flow[String, (ByteString, ObjectMetadata), NotUsed] = Flow[String].map(
  key =>
    S3 // akka.stream.alpakka.s3.scaladsl.S3
      .download(bucketName, key)
      .collect { // take successful downloads
        // first element in the tuple contains the actual byte string as a source, second element is metadata
        case Some((bytestream, metadata)) =>

          val context = ObjectMetadata(
            key,
            metadata.versionId,
            metadata.lastModified.toIsoDateTimeString
          )
          bytestream.map((_, context))

      }
      .flatMapConcat(p => p.via(framingWithContext))
  ).flatMapConcat(p => p)
```
Maybe I am missing something, but I don't see how you can solve this `prefixAndTail`.

**Comment by johanandren** [comment]
In that case it looks like you don't need `prefixAndTail` because you already have a context that is closing over the metadata. You can compose `bytestream.via(objectscanner).map((_, metadata))` inside of the `collect` scope.

**Comment by johanandren** [comment]
I should add: `WithContext` APIs are meant for the case where you have a unique context with each element rather than combining a number of elements with one context thing. The canonical use case is for kafka where you have an element and an offset that you want to commit in the end after potentially transforming the element.

**Comment by johanandren** [comment]
Closing this as I think it is not a good solution, please start a thread over at https://discuss.akka.io if you want to discuss it further!
