### ISSUE TITLE
Example in documentation Introduction to Actors does not work

### ISSUE THREAD

**Issue by SirMullich** [akka/akka#28169]
[First example](https://doc.akka.io/docs/akka/2.6/typed/actors.html#first-example) in documentation does not work, presumably because of missing dependencies and/or logging.

`akka.actor.testkit.typed.scaladsl.LogCapturing` in 

```
import akka.actor.testkit.typed.scaladsl.LogCapturing
import akka.actor.typed.scaladsl.Behaviors
import akka.actor.typed.scaladsl.LoggerOps
import akka.actor.typed.{ ActorRef, ActorSystem, Behavior }
```
cannot be imported. 

Steps to reproduce (on personal machine):
1) Create a new sbt (sbt version 1.3.3 and scala version 2.13.1) project and add dependency as per documentation:
`libraryDependencies += "com.typesafe.akka" %% "akka-actor-typed" % "2.6.0"`
2) Create objects (actors) from First example
3) Delete `import akka.actor.testkit.typed.scaladsl.LogCapturing` as a workaround (because it cannot be imported). 
4) Run the project
Error:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
```

Code in ScalaFiddle also fails to run in browser. Steps to reproduce in browser (Mozilla Firefox 70.0.1):
1) Press Run for [code](https://doc.akka.io/docs/akka/2.6/typed/actors.html#here-is-another-example-that-you-can-edit-and-run-in-the-browser-)

Error:
```
Errors

ScalaFiddle.scala:1: error: object testkit is not a member of package akka.this.actor
import akka.actor.testkit.typed.scaladsl.LogCapturing
                  ^
ScalaFiddle.scala:3: error: object LoggerOps is not a member of package typed.this.scaladsl
import akka.actor.typed.scaladsl.LoggerOps
```

Presumable solution: maybe some additional dependencies for logging and/or config are needed to run this example? Only akka-typed dependency is stated in documentation

**Comment by johanandren** [comment]
Thanks for reporting!

I think LogCapturing snuck in there because of automatic import sorting or something, it is not needed for the sample so should just not be in the list of imports.

For the logger impl we should probably just add a `to get any outpout you'll also need to add a logger dependency: ...`

For the Scala fiddles there is a related ticket already: https://github.com/akka/akka/issues/27510
