### ISSUE TITLE
The config `akka.loglevel` doesn't affect internal logging of `EventSourcedBehavior`

### ISSUE THREAD

**Issue by taeguk** [akka/akka#28161]
The config `akka.loglevel` doesn't affect internal logging of `EventSourcedBehavior`.
In other words, the logs by akka persistence (for example, `Received Journal response:`) doesn't be affected by the config `akka.loglevel`.

**Comment by johanandren** [comment]
All logging of the typed actors go directly through Slf4j and is controlled by the logger config only while the pre-existing parts, (persistence journal for example) will still adhere to the `akka.loglevel`. It makes sense to enable slf4j filtering and leave `akka.loglevel` at `DEBUG` and control all levels from the logger backend config (see https://doc.akka.io/docs/akka/current/logging.html#slf4j )

**Comment by taeguk** [comment]
@johanandren Okay, I understand. But if I depend on only slf4j filtering, I can't differentiate each log level for akka internal log and my log.
let me say in detail. There is the function `LoggerClass.detectLoggerClassFromStack`. Due to that function, logs by akka library (for example, `Received Journal response: ~~~`) are logged with my logger. And it is also used for logging my logs. So, I can't set different log levels for akka internal log and my log.
If I define logger in `log4j2.xml` like:
```xml
<Logger name="com.mycompany.myproject" level="DEBUG" additivity="false">
  ~~~
</Logger>
```
This logger is used for both akka internal log and my log because of the function `LoggerClass.detectLoggerClassFromStack`.
It is impossible to set `DEBUG` as log level for my logs and `INFO` as log level for akka internal logs.

**Comment by johanandren** [comment]
If what you want is separating the out-of-the box logging of your event sourced behavior, you can use `ctx.setLoggerName` to customize the internal logger name and create your own `Logger` and use for your user level logging rather than use `ctx.log`.

**Comment by taeguk** [comment]
@johanandren yes. You're right in normal cases. But in case of `EventSourcedBehavior`, it doesn't work because `ctx.setLoggerName` is called with a name got by `LoggerClass.detectLoggerClassFromStack`.
https://github.com/akka/akka/blob/d4ed47f3091c48f708bfc4a4327c4933e4390e2b/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala#L84-L86
So, if I want to change internal logger name, I must call `ctx.setLoggerName` in `commandHandler` or `eventHandler`, parameters of `EventSourcedBehavior.apply`. But it seems a little weird because:
```scala
Behaviors.setup[Message] { context =>
  ~~~
  // It doesn't work because logger name is overwritten in `EventSourcedBehaviorImpl.apply()`
  context.setLoggerName("changedLoggerName")
  ~~~
  EventSourcedBehavior[Message, Event, State](
    persistenceId,
    emptyState,
    commandHandler,
    eventHandler
  )
}
```

**Comment by patriknw** [comment]
Your example with the Behaviors.setup is the right way to define a custom logger name.

However, I can see that it some rare cases it would be nice to have a separate logger name for the logging that Akka's EventSourcedBehaviorImpl is doing compared to the logging that the application is doing with `context.log.info(...)`. On the other hand, in many cases it's nice that those are using the same logger (and mdc contextual information). Difficult.

**Comment by taeguk** [comment]
@patriknw Now I'm okay to have same logger name for the logging that Akka's EventSourcedBehaviorImpl is doing and the logging that the application is doing with `context.log.info(...)`.
And I know the solution is that changing logger name with `context.setLoggerName` for internal logging and using another logger name for user level logging rather than `context.log`.
But, a problem is remained in case of `EventSourcedBehavior` as I described above.

**Comment by patriknw** [comment]
Could you repeat (rephrase) the problem you see with EventSourcedBehavior. I don’t see exacly what you mean.

**Comment by taeguk** [comment]
@patriknw The problem is that "logger name" is overwritten by internal of `EventSourcedBehaviorImpl`. Even though I change a logger name, it will be overwritten soon.

https://github.com/akka/akka/blob/d4ed47f3091c48f708bfc4a4327c4933e4390e2b/akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/EventSourcedBehavior.scala#L47-L54 Above, a logger class is gotten from `LoggerClass.detectLoggerClassFromStack`.

https://github.com/akka/akka/blob/d4ed47f3091c48f708bfc4a4327c4933e4390e2b/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/EventSourcedBehaviorImpl.scala#L84-L86 And, `EventSourcedBehaviorImpl` overwrite logger name with `ctx.setLoggerName(loggerClass)`.

This is simple code for describing the problem:
```scala
// Assumes the class name this codes belong to is `a.b.c`.
Behaviors.setup[Message] { context =>
  ~~~
  context.log.debug("11111111111") // logger class : a.b.c
  context.setLoggerName("changedLoggerName")
  context.log.debug("22222222222") // logger class : changedLoggerName
  ~~~
  val commandHandler: (State, Message) => Effect[Event, State] = { (state, message) =>
    context.log.debug("33333333333") // logger class : a.b.c (Overwritten!)
    Effect.none
  }
  ~~~
  EventSourcedBehavior[Message, Event, State](
    persistenceId,
    emptyState,
    commandHandler,
    eventHandler
  )
}
```

**Comment by patriknw** [comment]
Ah, that is wrong. It should ofc keep the logger name if set. Thanks for reporting and explaining. If you know how to fix a PR is welcome.
