### ISSUE TITLE
Reconsider cluster.role.<role-name>.min-nr-of-members fallback

### ISSUE THREAD

**Issue by raboof** [akka/akka#28177]
`cluster.role.<role-name>.min-nr-of-members` can be used to postpone shard allocation until at least this number of nodes with this role have joined the cluster. This is useful to avoid 'flooding' nodes with entities when there are few nodes, for example during startup or when an update is in progress.

However, when `cluster.role.<role-name>.min-nr-of-members` is not defined, this setting falls back to `cluster.min-nr-of-members`. Since it is unlikely that all nodes of the cluster have the same role, this seems too strict.

I'm proposing to remove this fallback, and default `cluster.role.<role-name>.min-nr-of-members` to 1.

**Comment by patriknw** [comment]
I agree with this reasoning.

**Comment by helena** [comment]
Relatedly, here is a suspicious case I'm testing: 

Issue found where 
* 5 node cluster
* 2 cluster roles: 3 nodes with role R1, 2 nodes with role R2 
* `akka.cluster.min-nr-of-members = 2` 
* no per role min set

The question is why do nodes of role R2 log not all regions registered yet, but think all have with a third node of that role.

1. Attempt to access R2 from one of the proxy nodes shows:
    :2551/system/sharding/X2Proxy - X2: Request shard [16] home. Coordinator [Some(Actor[akka://system@127.0.0.1:2555/system/sharding/X2Coordinator/singleton/coordinator#757556079])]
2. Several retries follow, after which code times out:
    2551/system/sharding/X2Proxy -X2: Retry request for shard [16] homes from coordinator at [Actor[akka://system@127.0.0.1:2555/system/sharding/X2Coordinator/singleton/coordinator#757556079]]. [1] buffered messages.
3. On node 2555 hosting the shard the logs show the above triggers 20+ messages:
    :2555/system/sharding/X2Coordinator/singleton/coordinator - GetShardHome [16] request ignored, because not all regions have registered yet.
4. But adding a 6th node to the cluster, with role R2 and starting both entities, node 2555 logs:
    :2555/system/sharding/X2Coordinator/singleton/coordinator - ShardRegion registered: [Actor[akka://system@127.0.0.1:2556/system/sharding/X2#697707116]]
    :2555/system/sharding/X2 - X2: Starting shard [16] in region
