### ISSUE TITLE
Missng code in Java tutorial code

### ISSUE THREAD

**Issue by vadimjouk** [akka/akka#28171]
Hello, 
during working through akka example tutorial i found out that some code is missing in Java example:

**context.spawn(StartStopActor2.create(), "second");**

To get example to produce the expected output, i added this line into constructor of StartStopActor1.

Related example source with missing code is here:
https://github.com/akka/akka/blob/v2.6.0/akka-docs/src/test/java/jdocs/typed/tutorial_1/ActorHierarchyExperiments.java#L49-L94

**Comment by patriknw** [comment]
this was merged, thanks
