### ISSUE TITLE
LoggingTestKit expect vs intercept

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28194]
In scaladsl it's named `intercept` but in javadsl it's `expect`. I think we intended to change it to `expect` but must be an oversight that it wasn't done in scaladsl?

* Leave it as is?
* Deprecate `intercept` and add `expect`?

**Comment by johanandren** [comment]
:+1: on deprecate and add

**Comment by chbatey** [comment]
> Deprecate intercept and add expect?

:+1:

**Comment by patriknw** [comment]
ok, I'll fix that then
