### ISSUE TITLE
add access address in ActorSystem

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28206]
Would be useful to have direct access to the `Address` of the ActorSystem, to avoid things like `system.toClassic.asInstanceOf[ExtendedActorSystem].provider.getDefaultAddress)`, which will not work with BehaviorTestKit.

**Comment by navaro1** [comment]
@patriknw I'd like to take this in order to finish up what I started :)

**Comment by patriknw** [comment]
thanks

**Comment by navaro1** [comment]
I will probably create two PRs as part of this issue:

1. First - containing actual implementation.
2. Second - finding and replacing usage of existing verbose code.

**Comment by patriknw** [comment]
sounds good, or two commits in same pr would also be alright

**Comment by navaro1** [comment]
@patriknw, could you please provide (simplified) example of what do you mean by:
> which will not work with BehaviorTestKit.

**Comment by patriknw** [comment]
@navaro1 BehaviorTestKit: https://doc.akka.io/docs/akka/current/typed/testing-sync.html
Casting to ExtendedActorSystem will not work there. By adding this to ActorSystem we can also implement it in StubbedActorSystem.

**Comment by navaro1** [comment]
This PR is ready to be reviewed: https://github.com/akka/akka/pull/28232
