### ISSUE TITLE
Add documentation for Sink.collection stream operator

### ISSUE THREAD

**Issue by ticofab** [akka/akka#28208]
Hey @raboof , I am giving a go at this operator and didn't want to pollute the umbrella issue https://github.com/akka/akka/issues/25467 with this discussion :)

After having added the `/Sink/collection.md` file, running `sbt paradox` gives the following error:

```[error] Unexpected top-level pages (pages that do no have a parent in the Table of Contents).
[error] If this is intentional, update the `paradoxRoots` sbt setting to reflect the new expected roots.
[error] Current ToC roots: [camel.html, fault-tolerance-sample.html, index.html, stream/operators/Sink/collection.html]
[error] Specified ToC roots: [camel.html, fault-tolerance-sample.html, index.html]
[error] Paradox failed with 1 errors
[error] (akka-docs / Compile / paradoxMarkdownToHtml) com.lightbend.paradox.sbt.ParadoxPlugin$ParadoxException
[error] Total time: 19 s, completed Nov 20, 2019 12:20:24 PM
```

The only thing changed in the repository is adding a md file:

```
➜  akka git:(add-collection-sink-docs) ✗ git status
On branch add-collection-sink-docs
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   akka-docs/src/main/paradox/stream/operators/Sink/collection.md
```

It seems the new file is automatically added to the top-pages list and I need to manually exclude it? In case, how? Or am I missing something?

**Comment by raboof** [comment]
Did you already remove it from the 'pending' list at https://github.com/akka/akka/blob/master/project/StreamOperatorsIndexGenerator.scala#L78 ?

In general, new files are considered 'roots' when they do not belong to any index files. In this case we would want this file to be part of the index file in `/stream/operators/index.md`, which is auto-generated by `StreamOperatorsIndexGenerator`.

**Comment by ticofab** [comment]
That was the missing step! Will go ahead on this :) Thanks.
