### ISSUE TITLE
Doc link to github broken for akka typed

### ISSUE THREAD

**Issue by robstoll** [akka/akka#28213]
The link at the bottom of this page:
https://doc.akka.io/docs/akka/2.5.5/scala/typed.html
Points to github but to a site which does not exist:
https://github.com/akka/akka/tree/master/akka-docs/src/main/paradox/scala/typed.md

**Comment by ennru** [comment]
Thank you for reporting. 

We've reorganised the documentation lately.
Refer to the latest Akka 2.5 documentation and you'll find the source for that page: https://doc.akka.io/docs/akka/2.5/typed/index.html?language=scala

**Comment by robstoll** [comment]
@ennru sorry but your explanation does not help. How I am supposed to know the file in github based on this overview? Can you please give an example

**Comment by ennru** [comment]
Sorry, I did point to the wrong page. 
You're looking for this https://doc.akka.io/docs/akka/2.5/typed/actors.html

**Comment by patriknw** [comment]
Or https://doc.akka.io/docs/akka/current/typed/actors.html, which is the latest 2.6 version.

**Comment by robstoll** [comment]
google brought me to https://doc.akka.io/docs/akka/2.5.5/scala/typed.html 
I actually wanted the latest version

**Comment by patriknw** [comment]
We have been trying to make good understand us better, so it would be interesting to know what you googled to end up at 2.5.5.

**Comment by robstoll** [comment]
I think I used typed akka and then used the link on the page which pointed to akka typed

**Comment by patriknw** [comment]
thanks, mysterious

**Comment by robstoll** [comment]
Maybe it makes sense to point always to the latest version of akka typed? That's the page Google brought me to: https://doc.akka.io/docs/akka/2.5.5/scala/typed-actors.html#:~:targetText=Akka%20Typed%20Actors%20is%20an,way%20since%20Smalltalk%20came%20out.

**Comment by raboof** [comment]
For newer (but still outdated) versions of the documentation we have added a warning box: https://doc.akka.io/docs/akka/2.5.20/typed-actors.html

It's surprising google would point you to that 2.5.5 page though, and with that weird `targetText` as well. I can't reproduce that...

**Comment by raboof** [comment]
One 'manual' improvement we could do here is to change the canonical link from https://doc.akka.io/docs/akka/current/typed-actors.html to https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html#typedactor . That might convince google to rate that 2.5.5 page lower and link to either the migration guide or the new API's

**Comment by ennru** [comment]
I don't think canonical work like that. They require the target page to be roughly the same as the page that points to it. Otherwise that hint will be ignored.
