### ISSUE TITLE
Contravariant SinkRef and covariant SourceRef

### ISSUE THREAD

**Issue by enzief** [akka/akka#28233]
Please make `trait SinkRef[-In]` and `trait SourceRef[+T]` for they should be so.

**Comment by johanandren** [comment]
I can't see a use case where variance matters for those two traits, they are not for user extension so should have no other implementations than the built in ones and when use they do return `Sink` and `Source` which have variance annotated correctly.

**Comment by hepin1989** [comment]
As it interactives with serialization, invariance seems ok.

**Comment by johanandren** [comment]
Closing because lack of feedback
