### ISSUE TITLE
ReceiveTimeout not triggered after actor restart

### ISSUE THREAD

**Issue by georgeyanev** [akka/akka#28266]
If the parent actor's strategy is 'restart' then the following snippet does not work as expected.
The ReceiveTimeout message is triggered only on first actor creation, but not after actor restarts

```
  @Override
  public void preStart() {
    getContext().setReceiveTimeout(Duration.create(10, TimeUnit.SECONDS));
  }

  @Override
  public Receive createReceive() {
    return receiveBuilder()
        .match(ReceiveTimeout.class, m -> processMessage())
        .build();
  }

  private void processMessage() {
    getContext().setReceiveTimeout(Duration.Undefined()); // turn off timer
    throw new RuntimeException("Test exception");
  }
```

This is tested on latest akka 2.5 and akka 2.6

**Comment by johanandren** [comment]
Do you have an override of `postRestart()` in that actor? If so, if it doesn't call `super.postRestart()` it needs to call `preStart()` or else a restarted actor will never execute `preStart()` which would explain no receive timeout being set.

**Comment by georgeyanev** [comment]
@johanandren thanks for your response! Actually the preStart method is called after restart but the ReceiveTimeout message is not received.

**Comment by johanandren** [comment]
Thanks for verifying, that sounds surprising indeed.
