### ISSUE TITLE
Please bump scalatest to 3.1.0

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#28289]
I've upgraded scalatest from `3.0.8` to `3.1.0` and start getting `java.lang.NoClassDefFoundError: org/scalatest/WordSpecLike` 
It was traced down to `PluginSpec` in `akka-persistence-tck`

Could you please bump scalatest to `3.1.0` in akka in order to unblock all dependent projects.
Thanks.

**Comment by johanandren** [comment]
So, is `WordSpecLike` removed in 3.1.0? Looks like we use it in more places than that so it would be more work than just a dependency bump.

As a workaround you should be able to skip `PluginSpec` and use `akka.testkit.TestKitBase` yourself with some minimal glue.

**Comment by patriknw** [comment]
`PluginSpec` is part of the `akka-persistence-tck`, for example via `JournalSpec` so I think it's a valid request.

**Comment by patriknw** [comment]
release notes of 3.1.0: http://www.scalatest.org/release_notes/3.1.0

**Comment by raboof** [comment]
So since scalatest did not keep binary compatibility we have the choice between forcing users to stay on 3.0.x or forcing users to update to 3.1.x .

Indeed since this only affects the testkit/tck projects it seems :+1: to move to 3.1.x

**Comment by limansky** [comment]
Hi, I tried to use Scalafix as proposed in ScalaTest migration guide, was not able to add it to the project without changes in the build. Is there any good reason to use such old sbt version? Would it be ok, if I try to migrate to the latest sbt-0.13.x (I suppose this must be easier) or sbt-1.x in scope of this issue?

**Comment by johanandren** [comment]
@limansky Not sure if this relates to this issue? Akka is on sbt 1.3

**Comment by raboof** [comment]
#26989 can serve as some inspiration (though it probably has too many merge conflicts to be useful code-wise)

**Comment by limansky** [comment]
@johanandren oh, stupid me. I didn't realized that I already had a fork and it was pretty old.

**Comment by limansky** [comment]
Hi! I've created pull request on master, but possible it also have to be ported to version 2.5.x and to akka-http. I'm not really sure about that.

**Comment by patriknw** [comment]
Users of `ScalaTestWithActorTestKit` in `akka-actor-testkit` need to migrate, or create their own copy of the 2.6.1 version of [ScalaTestWithActorTestKit](https://github.com/akka/akka/blob/v2.6.1/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ScalaTestWithActorTestKit.scala).
