### ISSUE TITLE
Dead letters not delivered

### ISSUE THREAD

**Issue by chris-hardcastle** [akka/akka#28290]
Hi, I'm presently receiving an error in our CI/CD pipeline.

Kindly advise on the meaning of this error?
> [INFO] [12/02/2019 10:22:23.790] [typescript-parser-akka.actor.default-dispatcher-4] [akka://typescript-parser/deadLetters] Message [jdk.nashorn.api.scripting.ScriptObjectMirror] from Actor[akka://typescript-parser/user/parser-worker/$d#1149965784] to Actor[akka://typescript-parser/deadLetters] was not delivered. [10] dead letters encountered, no more dead letters will be logged. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug. Please add clear information in that case about what behavior you expected and what you experienced instead. Adding a reproducer will help a lot as well.
