### ISSUE TITLE
Java Optional.of works in mysterious ways

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28298]
Surprisingly enough Java `Optional.of` throws on `null` rather than returning empty, we should check our usage throughout the code base if it is used in such places where the value could be null.

**Comment by patriknw** [comment]
and then use `Optional.ofNullable` instead

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/70037731-03e79900-15f2-11ea-8478-4a750918f15d.png)

**Comment by raboof** [comment]
To be fair, the approach in Scala, where there is a difference between `None` and `Some(null)`, is not so clearly superior... it makes sense to me to have both `Optional.of` and `Optional.ofNullable`, like we have `Some(foo)` and `Option(foo)`

**Comment by patriknw** [comment]
@johanandren Have you seen any invalid usage in Akka sources? I searched for `Optional.of(` and apart from tests we have very few of them and I can't see that they are wrong.

**Comment by johanandren** [comment]
The one in circuitbreaker was what caught my eye and made me open this ticket but I did not investigate further.

**Comment by fagossa** [comment]
Hello, maybe is not high priority but I checked the existing code and replace all occurrences of `Optional.of` by `Optional.ofNullable` (actually only found 3!)

**Comment by johanandren** [comment]
Thanks to @fagossa we now know all three usages of `of` are reasonable.
