### ISSUE TITLE
ActorSystem hangs on startup with custom serializer loading SerializationExtension

### ISSUE THREAD

**Issue by olijaun** [akka/akka#28301]
Hi

I have a problem with custom serializers that load the SerializationExtension.

The ActorSystem .create() always hangs on startup. This can easily be reproduced like this:

```
public class MyActor {

    public static void main(String[] args) {

        ActorSystem system = ActorSystem.create(Behaviors.<Object>empty(), "my-cluster");
        System.out.println("started");
    }
}
```

application.conf:

```
akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = DEBUG
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

  actor {

     serializers {
       my-serializer = "test.MySerializer"
     }
  }
}
```

MySerializer:

```
public class MySerializer extends SerializerWithStringManifest {

    public MySerializer(ExtendedActorSystem extendedActorSystem) {
        // here it hangs!!!
        SerializationExtension.get(extendedActorSystem);
    }

    @Override
    public int identifier() {
        return 11232131;
    }

    @Override
    public String manifest(Object o) {
        return null;
    }

    @Override
    public byte[] toBinary(Object o) {
        return new byte[0];
    }

    @Override
    public Object fromBinary(byte[] bytes, String manifest)
            throws NotSerializableException, NotSerializableException {
        return null;
    }
}
```

I tried with Akka 2.5.23, 2.5.26 and 2.6.0. I think it only hangs when you try to access the SerializerExtension in the Constructor.

Somehow it seems to have to do something with the CountDownLatch in ActorSystem (here from 2.5.23):

```
@tailrec
  private def findExtension[T <: Extension](ext: ExtensionId[T]): T = extensions.get(ext) match {
    case c: CountDownLatch =>
      c.await(); findExtension(ext) //Registration in process, await completion and retry
    case t: Throwable => throw t //Initialization failed, throw same again
    case other =>
      other.asInstanceOf[T] //could be a T or null, in which case we return the null as T
  }
```

Regards
Oliver

**Comment by patriknw** [comment]
Serializers are initialized by the  SerializationExtension so that will introduce a cyclic dependency in the initialization that will result in deadlock. You have to access the SerializationExtension later (not in constructor). Either via `SerializationExtension.get(extendedActorSystem)`, which is a lookup in a ConcurrentHashMap, or some lazy init.

**Comment by olijaun** [comment]
Yes I thought about this when I wrote this issue but then I had to leave. I will try that tomorrow at work. However I think it's quite unfortunate that it just hangs without a timeout and without any log written. It took me some time to find this issue, partly because I firstly thought it had to do something with my cluster bootraping. It's very simple to do it wrong because if I see something like `Extension.get()` I assume that it will cause some overhead and I try to do it once in the constructor.

**Comment by olijaun** [comment]
It works. Thanks for the hint. I still think this is not ideal because a "user of akka" has to know about "akka-internals". At least a note in the docs could be helpful for others.

**Comment by patriknw** [comment]
I agree. We should be able to have a timeout there and provide a useful error message, and mention in docs about the serializer constructor.

**Comment by olijaun** [comment]
great, thanks!
