### ISSUE TITLE
BroadcastHub doesn't wait for first materialization of Source

### ISSUE THREAD

**Issue by artur-jablonski** [akka/akka#28327]
This is what _Akka Streams_ documentation states about `Source` materialized from `BroadcastHub` `Sink` ([link][1]):

> The resulting Source can be materialized any number of times, each materialization effectively attaching a new subscriber. If there are no subscribers attached to this hub then it will not drop any elements but instead backpressure the upstream producer until subscribers arrive.

Therefore I would expect that this:

```java
 Source<String, NotUsed> bcast =
            Source.from(Arrays.asList("1", "2", "3"))
                  .log("before broadcasting")
                  .runWith(BroadcastHub.of(String.class), materializer);

 bcast.log("after broadcasting")
      .runWith(Sink.ignore(), materializer);
```

would effectively backpressure the upstream of the `BroadcastHub` `Sink` until the `bcast` `Source` is materialized at least once, but it is not the case. If I run the above, the output is:

```
[before broadcasting] Element: 1
[before broadcasting] Element: 2
[before broadcasting] Element: 3
[before broadcasting] Upstream finished.
[after broadcasting] Upstream finished.
```

which is contrary to the documentation, as the elements are effectively dropped and never broadcasted. If I limit the buffer of the `Broadcast` `Sink` like this:

```
        Source<String, NotUsed> bcast =
            Source.from(Arrays.asList("1", "2", "3"))
                  .log("before broadcasting")
                  .runWith(BroadcastHub.of(String.class, 2), materializer); //buffer smaller than number of events

```

then all the elements are broadcasted:

```
[before broadcasting] Element: 1
[before broadcasting] Element: 2
[after broadcasting] Element: 1
[after broadcasting] Element: 2
[before broadcasting] Element: 3
[before broadcasting] Upstream finished.
[after broadcasting] Element: 3
[after broadcasting] Upstream finished.
```

The way I see it it's either a bug or the documentation is misleading?

originally posted at SO: 

https://stackoverflow.com/questions/58974630/broadcasthub-doesnt-wait-for-first-materialization-of-source

  [1]: https://doc.akka.io/docs/akka/current/stream/stream-dynamic.html

**Comment by patriknw** [comment]
I tried this and can confirm the reported behavior. If the upstream is completed before the first subscriber the hub will complete (stop).

I don't know if there is a reason for pulling from upstream before the first subscriber, but otherwise that would maybe be a more intuitive behavior?

**Comment by artur-jablonski** [comment]
I was looking at the tests in `akka.stream.scaladsl.HubSpec.scala`

I found that the tests actually set the size of the buffer to be smaller than the number of
items from the input `Source`. Like this one for example:

```
  "work in the happy case" in assertAllStagesStopped {
      val source = Source(1 to 10).runWith(BroadcastHub.sink(8))
      source.runWith(Sink.seq).futureValue should ===(1 to 10)
    }

```

I've also looked at the source code of the `BroadcastHub`, but I am new to the codebase and I
didn't understand it enough to understand if the current behaviour is intentional or not. 

Perhaps someone from the core team could push me in the right direction?

**Comment by artur-jablonski** [comment]
I guess this ticket is related: https://github.com/akka/akka/issues/27163

**Comment by jypma** [comment]
I'm having the same issue, and was able to work around it my replacing `BroadcastHub` with a `PartitionHub` of size 1, i.e. 
```
PartitionHub.sink[T]((_, _) => 0, 1, 256)
```

**Comment by He-Pin** [comment]
@artur-jablonski Would you like to take a review at #31890 ?
