### ISSUE TITLE
Further clarify "incompatible versions on the classpath" error

### ISSUE THREAD

**Issue by raboof** [akka/akka#28329]
When we detect incompatible Akka versions on the classpath, we produce an error like:

```
Detected possible incompatible versions on the classpath. Please note that a given $productName version MUST be the same across all modules of $productName that you are using, e.g. if you use [$highestVersion] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries. Possibly conflicting versions [$conflictingVersions] in libraries [$fullInfo]"
```

The remedy typically is to explicitly add dependencies on the `$highestVersion` for all artifacts, which should be no problem because they are typically binary compatible.

Recently we've seen a couple of instances where this was not clear. Perhaps we should further clarify the message, something like.

**Comment by johanandren** [comment]
Could we link to the docs page instead of adding more text in the error perhaps?https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed

**Comment by patriknw** [comment]
and the doc page could have dependencies that can be copied. Corresponding to that example and and mention to replace the version.

**Comment by patriknw** [comment]
I was also thinking that we should add such typical dependencies to the documentation of other projects, such as what is needed for Multi-DC Persistence to be used with Akka 2.6.0. Similar could be added to the Akka Management modules.
