### ISSUE TITLE
Source.actorRef sends down onSubscribe in Akka 2.6.1

### ISSUE THREAD

**Issue by cullender-skew** [akka/akka#28351]
Thanks for all the great work done with Akka, really exciting to see where it is going.

When I upgraded to akka 2.6.1, I am seeing an `onSubscribe` message coming through when using  `Source.actorRef`. For example, my tests cases, which use akka test kit, now break since they are receiving an unexpected message:

`java.lang.AssertionError: expected OnNext, found OnSubscribe(BoundarySubscription[Actor[akka://service/system/Materializers/StreamSupervisor-23/flow-0-0-futureFlattenSource#-497765268], FutureFlattenSource.out(392136094)])`

Normally I would expect to see my application message only, now I am seeing the above `onSubscribe`. 

Besides updating some API's which use materializer, the code base has not changed. Is this intended behaviour for `Source.actorRef` for akka 2.6?

Thanks
Daniel

**Comment by cullender-skew** [comment]
if it helps, the source is from an akka grpc service.

**Comment by cullender-skew** [comment]
seems to an issue elsewhere, will investigate more

**Comment by raboof** [comment]
Thanks, let us know if you find out more!

**Comment by cullender-skew** [comment]
seems to be the if I use the `.expectNext()` call from the teskit on a source. using `.request(...)` works 100%. This was the same with the previous version of Akka as well (2.5), I thought I left all the code untouched, but this seemed to have changed which caused the issue.

Thanks again!

**Comment by raboof** [comment]
Good to hear, have fun!
