### ISSUE TITLE
flattened prefixAndTail operator

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28364]
Many use cases for `prefixAndTail` will be a `map` to choose some additional operators based on the prefix and then a `flatMapConcat` flattening the single downstream into the surrounding stream.

This has a few problems

 * Since you could forget materializing the tail it needs to schedule a timeout
 * The materialized value is lost since `flatMapConcat` is generic and expects multiple streams - there is no single materialized value
 * Potential other optimization possibilities knowing that there is a single stream to flatten rather than a stream of streams are missed out on.

Suggested signature:

```
.flatMapPrefixAndTail[O, Mat2](n: Int)((Seq[Out], Source[Out, NotUsed]) => Source[O, Mat2]): Source[O, Future[Mat2]]
```

May need a `Mat` version as well for allowing combination of the upstream materialized value with the inner stream one. 

Somewhat related to #28334

**Comment by eyalfa** [comment]
@johanandren , I think the non-mat version should retain the original mat value, hence the signature should be:
`.flatMapPrefixAndTail[O, Mat2](n: Int)((Seq[Out], Source[Out, NotUsed]) => Source[O, Mat2]): Source[O,Mat]`

and the mat version should be something like:

`.flatMapPrefixAndTailMat[O, Mat2, Mat3](n: Int)((Seq[Out], Source[Out, NotUsed]) => Source[O, Mat2])(combMat : (Mat, Future[Mat2]) => Mat3): Source[O, Mat3]`

**Comment by johanandren** [comment]
Hmm, ok, yeah, sounds like it make sense.

**Comment by eyalfa** [comment]
@johanandren , I'll have a stub at this during the weekend

**Comment by viktorklang** [comment]
Or `prefixAndTailMat`?

**Comment by johanandren** [comment]
The materialized value is "lost" when flattening, not from the `prefixAndTail` operation, this operator would basically combine `prefixAndTail().map((prefix, tail) => tail).flatMapConcat` so I think it makes sense to give it a slightly different name than `prefixAndTail`.

**Comment by viktorklang** [comment]
@johanandren That makes sense! But I think Concat needs to be in the name, to clarify semantics.

**Comment by johanandren** [comment]
It won't actually concat though, it will rather just "flatten", as it is a single tail that goes downstream rather than concatenating many.

**Comment by viktorklang** [comment]
@johanandren True.

**Comment by eyalfa** [comment]
@johanandren , I think we can simplify things a bit if the signature takes a function from `Seq[Out] `to `Flow[Out,O,Mat2]`, this way the flow is always materialized and the hassle of making sure the tail stream is materializd gets out of the way:

`.flatMapPrefixAndTailMat[O, Mat2, Mat3](n: Int)(f : Seq[Out] => Flow[Out, O, Mat3])(combMat : (Mat, Future[Mat2]) => Mat3): Source[O, Mat3]`

semantics become: up to n elements are consumed from upstream, accumulated and fed to f. the flow resulting from the function application is then materialized and connected to the remainder of the upstream (`via` semantics), consuming the rest of the available upstream elements.

this way, if the user wants to discard the elements she can be simply devise a flow that forwards the elements to Sink.ignore/Sink.cancelled/take(0) or alike. Notice the graph stage controls materialization this way, preventing the 'source not materialized' scenario.

@viktorklang , re. naming, if we choose this path I think this operator will no longer do anything similar to concat. it basically reads the prefix and decides on the downstream flow to be applied, I think it falls somewhere between the existing prefixAndTail and flatMap (though it's a different beast as f isn't applied to each element  in the source).

**Comment by eyalfa** [comment]
@jru\, can u please resolve the issue?

**Comment by jru** [comment]
You mean @jrudolph, right? :)
