### ISSUE TITLE
Support for custom logging for supervision failure in akka typed

### ISSUE THREAD

**Issue by taeguk** [akka/akka#28389]
https://github.com/akka/akka/blob/9e0fd9451ca4328d9f6d2b39bf76e96c416224ae/akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala#L86-L100
Currently, the logging message for supervision failure is fixed: `Supervisor $this saw failure: ${unwrapped.getMessage}`
But, it doesn't contain detail informations like actor path, stack trace , and `unwrapped.cause`.

So I want to suggest to support custom logging for it.
One way to support it is adding custom log function to `abstract class SupervisorStrategy`.
If we want much general-purpose way, it can be the way to add callback function for unhandled exception to `abstract class SupervisorStrategy`.

**Comment by taeguk** [comment]
Note that it is possible in akka classic:
```scala
OneForOneStrategy(maxNrOfRetries = 10, withinTimeRange = 1 minute, loggingEnabled = false) {
  case e: Exception =>
    // Do somethings like logging.
    Stop
}
```

**Comment by johanandren** [comment]
Actor path should be available from the logger (since that is the actor specific logger that comes from the actorcontext), stacktrace should go in log event since it is passed to the log call. The only thing you'd be able to change then that isn't already in the log event now is a custom text. 

That doesn't sound like it is worth a custom pluggable API to me. If either of those two above isn't true I think it is a bug and should be fixed.

**Comment by taeguk** [comment]
@johanandren Hmm, could you let me know how to print stack trace, actor path, and `unwrapped.cause` when unhandled exception exists and a supervisor see it?

**Comment by johanandren** [comment]
I expect that since it passes the unwrapped exception to the logger in `logger.error(logMessage, unwrapped)` it should end up in the log by default unless the exception type tries to hide the cause or the cause is `null`?

**Comment by patriknw** [comment]
actor path is in the `akkaSource` MDC value. You might need to add `%mdc` to your logback.xml
https://doc.akka.io/docs/akka/current/typed/logging.html

**Comment by johanandren** [comment]
Is anything still unclear here @taeguk or could we close this ticket as the requested info is already available in the logs with some config?

**Comment by taeguk** [comment]
@johanandren Now, I'm okay :) If I have some issue, I'll re-open this issue. Thanks.
