### ISSUE TITLE
Is it possible to deprecate akka/pattern/extended/package.scala

### ISSUE THREAD

**Issue by ShutaoTang** [akka/akka#28381]
The comment of `extended` package says:
```
/**
 * == Extended Versions Of Akka Patterns ==
 *
 * This subpackage contains extended versions of Akka patterns.
```

So I think this package has been superseded by `akka.pattern` package.

**Comment by johanandren** [comment]
I don't think the explicit ask is available from anywhere else so we'd need to provide the same functionality (`ExplicitAskSupport` - asking and providing what actor ref should be used as a sender) first to deprecate it.
