### ISSUE TITLE
Replicas for Entities in Cluster Sharding

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#28395]
When some Entities are very popular we may want them to replicate across multiple nodes , or better can dynamically increase or shrink the number of replicates. 
```scala
def entityRefFor[M](
   typeKey: EntityTypeKey[M], 
   entityId: String, 
   minReplicas:Int = 1, 
   maxReplicas:int = 1): EntityRef[M]
```

**Comment by patriknw** [comment]
Having multiple replicas for an entity doesn't align with the primary purpose of Cluster Sharding, which is to have one and only one instance of a specific entity in the cluster. If multiple are allowed the whole machinery of Cluster Sharding is not needed.

It might be another useful, new feature, but it's not Cluster Sharding, as I see it.

**Comment by chbatey** [comment]
Closing for now and can be re-opened describing a new feature.
