### ISSUE TITLE
[doc] update link text from `Persistence` to `Event Sourcing`

### ISSUE THREAD

**Issue by robstoll** [akka/akka#28405]
See link in the introduction section here:
https://doc.akka.io/docs/akka/current/persistence.html

At first it seems the link is broken as it points to `Event Sourcing` and not `Persistence`. Furthermore, `Persistence` is currently about the classic Persistence (see url above).

There are other links (on other pages) using Persistence but pointing to Event Sourcing

**Comment by raboof** [comment]
I agree, we should change the link text to 'Event Sourcing'.

(the reason we've been using the names 'Event Sourcing' and 'event sourced persistence' where we previously just said 'persistence' is because akka-persistence is about this particular type of persistence)
