### ISSUE TITLE
Make Distributed Data Replicator Gossip more resilient and data aware

### ISSUE THREAD

**Issue by helena** [akka/akka#28421]
To prevent unreasonably large sized data cached and added to a Gossip and sent. 
  
Currently if there are qualified keys
```
val keys = (otherDifferentKeys ++ otherMissingKeys).take(maxDeltaElements)
```
 
 a `Gossip` is sent, e.g.:
```
val updateData = keys.iterator.map(k => k -> getData(k).get).toMap
val g = Gossip(updateData, sendBack = otherDifferentKeys.nonEmpty, fromSystemUid, selfFromSystemUid)
replyTo ! g
```

### What constitutes the bound 
Given:

* varying data structure for eventual gossip: `Map.empty[KeyId, DataEnvelope]` 
* appended per: `key -> getData(key)` 
* and value: ```DataEnvelope(data: ReplicatedData, pruning: Map[UniqueAddress, PruningState] ,deltaVersions: VersionVector)```

The algo could consider:
* bytes of memory occupied per KeyId -> DataEnvelope 
* total element count
* envelope count per key (would be interesting to know the topK key -> envelope count to also suggest a change in user strategy?)
* total bytes (keys + envelopes)

Additionally, what is a performant way to get the bytes of a DataEnvelope? Several options here.

### Add configurable bound not to exceed
* Set a valid default

### Pre-calculate the known vs the entire Gossip
Add a final val of `Gossip` message size with no keys, no envelopes to provide a base message size as though the options are defined since they are small with/without.

Without the `updatedData` (keys -> envelopes), a `Gossip` consists of 
* 1 Boolean 
* 2 Option[Long] 

```
final case class Gossip(
        updatedData: Map[KeyId, DataEnvelope],
        sendBack: Boolean,                                          
        toSystemUid: Option[Long],
        fromSystemUid: Option[Long])
        extends ReplicatorMessage
        with DestinationSystemUid
```

## Awareness
What constitutes `knowing` if it has been exceeded?

#### If the bound is reached 
* Log warning - the counts, size and more info on the data itself
* Gossip smaller diffs 
* Decrease the gossip time until stabilized (?)

Follow-up tickets:
When messages are hit because of the maximum-frame-size 
*  Provide a way for the user to know what's in the message, e.g.  a way to offload to disk for later processing, versus drop the message, and timestamp the offload event with the node address
* Enable large messages to degrade gracefully - large messages are often just a problem of an underlying issue, so don't pass the buck

**Comment by patriknw** [comment]
It is about automatically and dynamically finding a `max-delta-elements` based on the payload size, instead of configuring a fixed `max-delta-elements`. Do I understand the ticket correctly?

**Comment by patriknw** [comment]
We could make use of the collected data sizes from https://github.com/akka/akka/pull/29740 to decide how much to include in each gossip message.

**Comment by jroper** [comment]
Breaking up gossip messages by total bytes to fit within Akka remotings max message size would definitely be a useful feature.

In Akka serverlesses backend systems, we have a situation where we are using ORMaps as a session cache, these maps can grow very large, to facilitate that, we shard them so that we don't have a single CRDT that is too large to send as a message, but that still leaves the problem that by default, all these shards are going to end up in the same gossip message which will be too big. To work around this, we have to set `max-delta-elements` to something very low, eg, 1. If the replicator could be smart enough to split gossip messages up by how many bytes they consume, then we wouldn't have to do that, plus, it would allow for more efficient gossipping as we could fill the gossip messages instead of having to set `max-delta-elements` to something far lower than will fill it to be safe.

**Comment by jroper** [comment]
There is a related feature, but probably somewhat more involved and perhaps not the direction we want to go, but it would be nice if large CRDT structures such as ORMaps didn't have to be sharded. In theory, this is straight forward, you can split up an ORMap as many times as you like, and send it in chunks that get merged at the other end. In practice it would likely be very complex to implement, you'd have to make ORMap implement something that could do the splitting, and it may have to be aware of its own size when serialized (which currently, the ORMap itself has no idea about) if it's going to make a good decision about how to split itself up. It's probably not worth the complexity.
