### ISSUE TITLE
LevelDB live persistence query stream should no complete for empty id

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#28428]
The live stream provided by `LeveldbReadJournal` completes if there are no persisted events for a given persistence id.

`akka-persistence-cassandra` on the other hand does keep the stream open (https://github.com/akka/akka-persistence-cassandra/pull/608).

**Comment by nvollmar** [comment]
@johanandren Is there an ETA for Akka 2.6.2? We're still waiting to get this fix in :)

**Comment by patriknw** [comment]
it will be released early next week
