### ISSUE TITLE
False alarm about hostname verification TLS

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28437]
Quoting @jroper 

> When in a dynamic environment like Kubernetes will it ever be possible to enable hostname verification? you're never going to have one certificate issued per pod in the replica set, it just won't work that way, it will be one per deployment, the hostname in the certificate won't match the hostname of the pod. I don't think that warning makes sense.

> hostname verification is designed for situations where things locate each other by hostname, but in a Kubernetes scenario, Akka pods don't locate each other by hostname, they locate each other using the kubernetes API, and then connect to each other using a hostname that is unknown at deployment time (when you configure the certificate). I can imagine there may be some deployment scenarios where hostname verification might make sense, but in an elastic environment like Kubernetes, the warning is a big false alarm 

https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/tcp/SSLEngineProvider.scala#L88-L96

**Comment by raboof** [comment]
> in a Kubernetes scenario, Akka pods don't locate each other by hostname, they locate each other using the kubernetes API, and then connect to each other using a hostname that is unknown at deployment time (when you configure the certificate).

When you're using a system like Vault, might it not be possible to get the certificate at a point where the hostname is known?

That's probably pretty rare though, so I agree it'd make sense to introduce a way to disable hostname verification (do we have that already?) and documenting in which cases this can be reasonable.

**Comment by jroper** [comment]
> When you're using a system like Vault, might it not be possible to get the certificate at a point where the hostname is known?

No. The point where the hostname is known is when the Kubernetes replica set controller creates a new pod, which could be triggered by many things, for example, a node crashing, a partition, a rolling upgrade, a node being removed from the Kubernetes cluster, or scaling up. These events can happen many times per minute even during normal operation. It's not how things like Vault are designed to be used, and even if you did find a way to plug in to make Vault issue new certificates every time a new pod was created, you would introduce a single point of failure on Vault, where if Vault was not running or partitioned, it would be impossible to create a new pod - ie, make it impossible to automatically recover from failures, and so it would mean any small failure in your system would have a high chance of catastrophically snowballing into a system wide outage.

> so I agree it'd make sense to introduce a way to disable hostname verification (do we have that already?)

We do have it already, but if you disable it, a warning is output to the logs telling you that you have done the wrong thing and you should re-enable it.

**Comment by renatocaval** [comment]
Fixed in #28593
