### ISSUE TITLE
Typo in Akka tutorial

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [akka/akka#28430]
In https://doc.akka.io/docs/akka/current/typed/guide/tutorial_2.html first code snippet 
`@Override
  public Receive<Void> createReceive() {
    return newReceiveBuilder().onSignal(PostStop.class, signal -> onPostStop()).build();
  }
`

`newReceiveBuilder` should be new `ReceiveBuilder` isn't it?

**Comment by raboof** [comment]
This refers to https://doc.akka.io/japi/akka/current/akka/actor/typed/javadsl/AbstractBehavior.html#newReceiveBuilder()

**Comment by harshajayaweeraXHJ** [comment]
Ah, Got it thanks!
