### ISSUE TITLE
Support for log marker in akka streams API dsl

### ISSUE THREAD

**Issue by anshulbajpai** [akka/akka#28450]
At the moment, the Akka logging API has support for log markers but that support is missing in the akka-streams API (https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L2503)

Is it possible to add this feature so we could add markers while using the Akka streams logging API?

**Comment by johanandren** [comment]
Sounds like it makes sense to support that, but not obvious how to add such support in a binary compatible way since the existing flow API uses default params. Will require some thinking to get it right. Please open up a PR if you are interested in trying to add support @anshulbajpai
