### ISSUE TITLE
Failed: ByteStringSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28465]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/406/testReport/junit/akka.util/ByteStringSpec/A_ByteString_must_be_equal_to_the_original_when_compacting/

Something not quite right with the 2.13 optimization done in #28419

**Comment by SethTisue** [comment]
I'm seeing this in the Scala community build as well

**Comment by SethTisue** [comment]
I'm curious how this got past your own CI...?

**Comment by johanandren** [comment]
Yes, that is strange indeed. We haven't looked into it yet.

**Comment by johanandren** [comment]
It's because the PR validation only compiles on 2.13 (travis), actually running tests are still done on 2.12 (jenkins). It was caught by our nightly 2.13 test run though. Not sure if we can should do something about that without overloading the CI environments. @raboof @patriknw wdyt?

**Comment by SethTisue** [comment]
> It was caught by our nightly 2.13 test run though

ah, okay, well that lowers my concern level

note that the community build uses frozen SHAs these days, that I only advance intermittently (every few weeks, something like that). so it was just bad luck that I even ran into this
