### ISSUE TITLE
[Suggestion] By-Name Parameters In Scala Stream DSL Operators, Not By-Value

### ISSUE THREAD

**Issue by otto-dev** [akka/akka#28474]
I suggest to use By-Name (`xx: => T`) parameters in Akka's Source/Flow [operators](https://doc.akka.io/docs/akka/current/stream/operators/index.html), instead of By-Value parameters. This allows the operators to contain mutable state across multiple materialization and utilize the actor-provided single-threaded illusion, as in the following example:

```scala
   val stream = Source(0 to 10)
      .map {
        var counter = 0
        { (n: Int) =>
          counter = counter + 1 // currently bad
          n + counter
        }
      }.to(Sink.ignore)

  stream.run()
  stream.run()
```

Or, as another more practical example, splitting the stream whenever a key changes:

```scala
     // ...
    .splitWhen(SubstreamCancelStrategy.drain) {
        var lastKey: Option[String] = None
        item =>
          lastKey match {
            case Some(item.key) | None =>
              lastKey = Some(item.key)
              false
            case _ =>
              lastKey = Some(item.key)
              true
          }
      }
     // ...
```

Or, as another example, it would allow mutable collections in [fold](https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/fold.html), which currently has

> **Warning:** Note that the zero value must be immutable, because otherwise the same mutable instance would be shared [...] running the stream more than once.

Currently, with By-Value parameters, only the following two types of operators are supported:

- stateless/pure operations
- stateful operations, if the flow is not materialized more than once

By-Name parameters won't break either of those cases. And, for the same reason, it won't lead to unexpected results, if no re-evaluation of the operator expressions is assumed (due to the implicit syntax). You could say, it’s not breaking the Liskov Substitution Principle.

It would make mutable state on a per-operator basis possible, irrespective of number of materializations, analogous to an Actor Behavior with the single-threaded illusion. I believe this is the intuitive behavior.

Personally I miss this a lot, since I end up implementing my own `GraphStage` for most things that contain mutable state, unless `statefulMapConcat` is a better fit.

I expect that there are probably good reasons why this hasn’t been done, and can't be done now, but I’m still throwing this out for possible consideration.

**Comment by otto-dev** [comment]
Closing this, the issue is too broad. There are only a handful of operators that would benefit from statefulness

**Comment by patriknw** [comment]
I agree that this would be an unrealistic change, due to binary and sematical backwards compatibility constraints.

**Comment by patriknw** [comment]
Original discussion in https://discuss.lightbend.com/t/state-inside-of-flow-operators/5717
