### ISSUE TITLE
ReproducibleBuildsPlugin slows down sbt re-compilation

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28485]
akka-docs takes 21 seconds to re-compile without any changes.

akka-stream is quick, but akka-stream-tests is slow (7s). Something related to ReproducibleBuildsPlugin and the assembly of protobuf?

Problem disappear when disabling the ReproducibleBuildsPlugin.

We could consider to abandon the automatic assembly of protobuf and instead add sources to git. A manual sbt task to update it when the dependency changes would still be nice.

**Comment by patriknw** [comment]
cc @raboof

**Comment by johanandren** [comment]
Since it doesn't follow the Akka release cadence at all, wouldn't it be better to publish the shaded protobuf jar from a separate project and have a normal dependency on that from Akka?

**Comment by patriknw** [comment]
Wouldn't that encourage external usage of that shaded jar, which kind of defeats the purpose?

**Comment by raboof** [comment]
> Wouldn't that encourage external usage of that shaded jar

I'm not sure it would, as that's already possible. It does mean it is not checked by the version checker anymore. 

On the other hand, removing it would make a full build a bit lighter and simpler.

Not needed for this particular issue though ;)
