### ISSUE TITLE
missing method mapMaterializeValue on class akka.stream.Graph

### ISSUE THREAD

**Issue by eyalfa** [akka/akka#28501]
`akka.stream.Graph` lacks the `mapMaterializeValue` method which is available on specialized subclasses such as `Source`, `Sink` and `Flow`.

This lacking forces me to use the graph DSL which takes a mat-val-combiner function when building a graph of two or more components, I usually simply use the identity flow (`Flow.apply[A]`) and pipe one of my graph's ports through it. I'd really like to avoid this workaround though.

is this lacking intentional? will you accept a PR introducing this API to `akka.stream.Graph` ?

**Comment by johanandren** [comment]
Gut feeling is that it makes sense to have an abstract mapMaterialized value on `Graph` since that's the top type that defines the mat val type. `Graph` is documented as not intended for user extension so adding things can be done without breaking binary compatibility.

**Comment by eyalfa** [comment]
I had a fleeting concern since all gaph-stages implement the Graph trait so I had a look at how they all implement `withAttribute` and came across `akka.stream.scaladsl.GenericGraphWithChangedAttributes` which seems like the most reasonable place to add `mapMaterializeValue` support for all of graph-stages.

**Comment by johanandren** [comment]
I don't think having a single impl is the most important aspect of this (although perhaps nice), it's more about the user API of being able to map the materialized value on any `Graph`?

**Comment by jrudolph** [comment]
I wouldn't object to add `mapMaterializedValue` to `Graph` in general. Will it clash with the implementations in Flow, Sink, etc.?

> I had a fleeting concern since all gaph-stages implement the Graph trait so I had a look at how they all implement `withAttribute` and came across `akka.stream.scaladsl.GenericGraphWithChangedAttributes` which seems like the most reasonable place to add `mapMaterializeValue` support for all of graph-stages.

The declaration has to go `Graph` itself, the other classes are implementation details. Even if that is `@DoNotInherit` we should probably provide a default implementation right there which return an instance of `GenericGraph` taking a changed `traversalBuilder`.

**Comment by johanandren** [comment]
Please go ahead and try this out in a PR if you like @eyalfa !

**Comment by eyalfa** [comment]
my concern was about introducing a breaking change.
users can write their own graph stages hence there are already such classes out there, so if adding this method now makes these classes un-instantiable it will be bad.

**Comment by eyalfa** [comment]
> Please go ahead and try this out in a PR if you like @eyalfa !

will do!

**Comment by jrudolph** [comment]
> my concern was about introducing a breaking change.
users can write their own graph stages hence there are already such classes out there, so if adding this method now makes these classes un-instantiable it will be bad.

Yes, binary compatibility needs to be kept. A `GraphStage` is a subclasses of `Graph`, people shouldn't subclass `Graph` directly so that might help to find a solution.

**Comment by eyalfa** [comment]
I've started working on this but it seems my first approach hit a wall in the Java API.
I've basically [added](https://github.com/eyalfa/akka/pull/2/files#diff-d4fe7153284deedf37b4c9871bae9a2eR71-R77) a `mapMaterializedValue` to the `Graph` trait.
However, this fails calls to the Java DSL's `Source.mapMaterializedValue` method. The reason for this is that both methods take one arg of a functional interface type; one takes an `akka.japi.Function` while the other takes a `scala.Function1`, this becomes a problem when invoked with a lambda.

Since there's already such code out there, (even in the [akka project](https://github.com/eyalfa/akka/pull/2/files#diff-acfef16adeccbebbf0c34ebca248af70L68-L74))  this is a major issue for this approach.

I currently see two options moving forward:
1. renaming the method in the `Graph` trait (and overriding with a more specific return type for specialized interfaces such as `Flow`, `Source`, `Sink`...).
2. move this to an extension method (via an implicit conversion), this should work as expected for scala as it'd have a lower priority than the already existing methods (such as `Flow.mapMaterializedValue` and alike). However it'd mean a noticeably different API for java (either a static method or differently named method in the `Graph` trait).

btw, do we still need `akka.japi.Function` and friends? it seems `scala.Function1` is a functional type, so it supports Java's lambda OOTB. or am I missing anything?

**Comment by eyalfa** [comment]
[second attempt](https://github.com/eyalfa/akka/pull/3) using an extension method (via an implicit conversion) works perfectly for scala, still need to figure out how to expose this for the Java API.

**Comment by johanandren** [comment]
As I mentioned in 1:1 chat, I think that if it isn't possible to add to the top level `Graph` type I think we'll rather skip this improvement than add it through an extension method.

**Comment by eyalfa** [comment]
@johanandren , this functionality is currently lacking and since `GenericGraph` is a package private class, one can not implement this in 'user-land', at least not without directly deriving `Graph` which is forbidden.

few options I see here:
1. Adding this to the graph class with a slightly different name in order to avoid the colliding overloads.
2. Adding this as a method on the companion object, or package object, or something alike.
3. make GenericGraph public?
4. somehow add this to the graph dsl?

**Comment by johanandren** [comment]
I don't expect it is very common for people to end up with a generic toplevel type (we have had no prior complaints about it) so I don't think it is worth it doing some implicit extension, and I don't see how we can get away from the differing lambda types in a nice way. 

An extension method you can add in your own project will work around the issue. I suggest we close the issue and revisit this if more people have end up asking about it over time.

**Comment by eyalfa** [comment]
@johanandren , I can't really add this extension method in 'user-land':
1. it'd require directly inheriting Graph, which is forbidden.
2. even if I'm willing to accept the risk of this newly introduced Graph derived class I'd still need to implement `traversalBuilder` which is package private.

so basically, it seems blocked.

another approach I'm thinking about now might be deriving a GraphStage (which addresses the first issue), but I'd still need access to the traversal builder.

**Comment by jrudolph** [comment]
> This lacking forces me to use the graph DSL which takes a mat-val-combiner function when building a graph of two or more components, I usually simply use the identity flow (`Flow.apply[A]`) and pipe one of my graph's ports through it. I'd really like to avoid this workaround though.

Maybe we could go back to the initial issue and see if there's a workaround we could document?

You say you are forced to go back to the Graph DSL but wouldn't you have to use the Graph DSL anyway if we are talking about composing generic graphs?

I see usually two cases:
 * either, you are a library writer and want to provide a stream component as a custom graph, often it makes sense not to expose the graph as is but provide some kind of simpler API that uses the Graph DSL internally to already connect some stages and then expose a Flow/Sink/Source interface. Even if not, the additional overhead to use Graph DSL to map the materialized value doesn't seem too bad for a library
 * or, you have the graph in your own code in which case you must connect it using Graph DSL in which case transforming the materialized value is a bit of hassle syntax-wise but still possible easy enough.

WDYT?

**Comment by eyalfa** [comment]
I'd say the first bullet better describe my position, I'm writing an execution engine on top of akka-streams so yeah, I compose graphs together.
Thing is that even the graph DSL has limitations:
1. when using the create overload accepting a zero or single graph - you don't get access to the materialized value
2. when using the overload taking a Seq of graphs you also don't have access to the materialized value.
3 generally speaking, as far as the graph dsl concerns, materialized values are only combined, not mapped.

in my scenario sinceI build the graph from the bottom up I also need a 'zero' graph, and yes I need it to have the appropriate materialized value so It can be combined with other graphs gradually added to the graph.
I hope this sheds some light on the use-case.

btw, as a workaround I created the empty graph by combining an empty source and a cancelled sink, however I do have other 'dark corners' where I have an intermediate graph of an arbitrary shape whose matVal needs to be mapped.

I generally think that that this operation should be available to all graphs, not jut Source, Flow, Sink and Runnable and I think @johanandren agreed with me. Java interop currently blocks us from adding it directly on Graph so we have to seek an alternative implementation , extension method was one suggestion, we can also consider others.

**Comment by jrudolph** [comment]
Thanks for the explanation.

I think the extension method approach could work. Maybe, in the first step, let's add a regular `Graph.mapMaterializedValue` method to the companion object that can be used from Scala and Java. Then, add the extension method to provide syntax sugar for Scala.

**Comment by eyalfa** [comment]
so the companion will have a method with this signature?
`def mapMaterializedValue[S <: Shape, M1, M2] mapMaterializedValue(g : Graph[S, M1])(f : M1 => M2) : Grpah[S, M2]`

and then the implicit class will be available under the companion or do you want in nested in an `Implicits` object?

what about java support? the companion can have an additional method:
`def mapMaterializedValue[S <: Shape, M1, M2] mapMaterializedValue(g : Graph[S, M1], f : akka.japi.Function[M1, M2]) : Grpah[S, M2]`

unless having these two overloads side by side breaks javac...

**Comment by jrudolph** [comment]
> what about java support? the companion can have an additional method:
> `def mapMaterializedValue[S <: Shape, M1, M2] mapMaterializedValue(g : Graph[S, M1], f : akka.japi.Function[M1, M2]) : Grpah[S, M2]`
> 
> unless having these two overloads side by side breaks javac...

I guess it will be ambiguous, could we only have one of those?

I'm actually not sure if we need functions taking `akka.japi.Function` at all for new methods or only for backwards-compatibility reasons? @johanandren do you know?

**Comment by johanandren** [comment]
Not sure how the ergonomics are with Scala functions from Java, I know that the other way around could be fine though (Scala supporting SAMs since a while)

**Comment by eyalfa** [comment]
it actually got me quite curious as scala Functions classes are SAM types which means they support java lambdas OOTB, Y did akka have to introduce japi.Function ?

**Comment by eyalfa** [comment]
I'll play with this a bit and c what's working.

another way is introducing the extension method as a primary API (for scala) and then add a java compatible 'static' method delegating to the extension method.
will this be acceptable?

**Comment by jrudolph** [comment]
> it actually got me quite curious as scala Functions classes are SAM types which means they support java lambdas OOTB, Y did akka have to introduce japi.Function ?

As far as I remember, it might be because Java 6 and Scala XYZ didn't support SAM methods.

> another way is introducing the extension method as a primary API (for scala) and then add a java compatible 'static' method delegating to the extension method.
> will this be acceptable?

If that's the only possibility, it might. Would be better if a single method with a Scala function type would work from Java.

**Comment by eyalfa** [comment]
@johanandren , @jrudolph ,
I'd appreciate if you could take another look at [this](https://github.com/eyalfa/akka/pull/3#commits-pushed-b7f8af9).

I've basically added a single method on Graph's companion taking a grapgh and a scala function, a java dsl test proved this to be callable from java.
I've also left the extension method in place (implemented by delegation to the newly introduced companion method) because I believe this should have been an instance method to begin with.
I'm also quite convinced the akka.japi.Function and friends can be retired by now as scala functions are available for java clients. an intermediate state to retiring these can be modifying them to extend the correlating scala traits, this way both clients using java lambdas and explicitly deriving the existing classes will not be broken.

**Comment by jrudolph** [comment]
> I've basically added a single method on Graph's companion taking a grapgh and a scala function, a java dsl test proved this to be callable from java.
> I've also left the extension method in place (implemented by delegation to the newly introduced companion method) because I believe this should have been an instance method to begin with.
> I'm also quite convinced the akka.japi.Function and friends can be retired by now as scala functions are available for java clients. an intermediate state to retiring these can be modifying them to extend the correlating scala traits, this way both clients using java lambdas and explicitly deriving the existing classes will not be broken.

Looks promising. I agree with your arguments. I wonder if we are missing something regarding Java compat. It might be that it was more complicated with Akka 2.5 because of Scala 2.11 compat which has been dropped in Akka 2.6 but there we couldn't change the Java signatures any more because of Akka binary backwards compatibility. But for new code it might just work like this?

**Comment by johanandren** [comment]
That sounds like a correct explanation @jrudolph 
Tricky part will then be which shared SAM to use, the Scala one, the Java one (which doesn't allow throwing) or the japi one. There's probably corner cases where the ergonomics aren't great using a shared SAM (let's say you define the lambda elsewhere for example, then you'd probably expect to be able to pass either languages function type, but not sure this is big enough an inconvenience to care about)

**Comment by jrudolph** [comment]
> Tricky part will then be which shared SAM to use, the Scala one, the Java one (which doesn't allow throwing) or the japi one.

Good point. Least useful one in that regard seems to be the japi one because no one will have objects of that type lying around. The Java one is not powerful enough because of the exception, so the Scala one sounds fine to me :) The Java usage is already clunky because we cannot easily add an extension method.

**Comment by eyalfa** [comment]
@jrudolph , @johanandren ,
1. are there any points in time where binary-compat may be compromised? i.e. between major releases?
2. same question for source compat.

BTW, regarding @johanandren concern: I've suggested making the japi types extend the corresponding scala types. this combined with dropping the overloads taking japi types should be at least source compatible:
1. if call site used lambda (99% ?) then the lambda will simply be bound to the scala type instead.
2. if for some reason the call site used an explicit japi instance then this instance noe complies with the required scala type.
3. not sure what this does to bin-compat, pretty sure it's src-compat.

aside from this, can I promote my diff to an actual PR

**Comment by jrudolph** [comment]
> * are there any points in time where binary-compat may be compromised? i.e. between major releases?
> 
> * same question for source compat.

Yes, in new minor releases with a full deprecation cycle. Until 2.7 it will be quite a while. A method that is not yet deprecated will only be removed in 2.8 which will be years out.

> BTW, regarding @johanandren concern: I've suggested making the japi types extend the corresponding scala types. this combined with dropping the overloads taking japi types should be at least source compatible:
> 
>     1. if call site used lambda (99% ?) then the lambda will simply be bound to the scala type instead.
> 
>     2. if for some reason the call site used an explicit japi instance then this instance noe complies with the required scala type.
> 
>     3. not sure what this does to bin-compat, pretty sure it's src-compat.

Often, binary compatibility is more important. So, I'd say let's keep it simple here and use your change as it is.

**Comment by eyalfa** [comment]
@jrudolph , thanks for the feedback, will soon open a PR

**Comment by jrudolph** [comment]
Implemented in #28610.
