### ISSUE TITLE
Logging in akka - improve docs

### ISSUE THREAD

**Issue by jewertow** [akka/akka#28529]
Hi, I have some thought. 
The most common issue I see in akka systems written by Java programmers is they always use string interpolation in log statements, like:
```
log.debug(s"Some message: ${someObject}")
```
instead of:
```
log.debug("Some message: {}", someObject)
```
I would like to add short information to the docs about consequences of writing such code.
What do you think? Could I prepare pull request?

**Comment by patriknw** [comment]
Sounds good. It's mentioned briefly in https://doc.akka.io/docs/akka/current/typed/logging.html#placeholder-arguments but feel free to expand or clarify.

**Comment by jewertow** [comment]
Ok, I didn't read documentation of Akka Typed. Documentation of Akka Classic has no this information.
