### ISSUE TITLE
PromiseActorRefs leak in the Artery ActorRef resolver cache

### ISSUE THREAD

**Issue by TJSomething** [akka/akka#28521]
If I use the ask pattern to request large responses many times in sequence, the JVM begins to use a large amount of RAM. It seems that the `ActorRefResolveCacheWithAddress` in Artery is holding onto the `PromiseActorRef`s, which are holding onto the resolved promises.

I'm guessing that the `ActorRefResolveCacheWithAddress` implementation is assuming that every `InternalActorRef` is small enough that it doesn't matter. However, `PromiseActorRef`s can be arbitrarily large.

I don't know Akka's internals well enough to know what the best solution is. Maybe `PromiseActorRef` only needs to hold onto a weak reference to its promise, since `ask` should return a strong reference to any user that actually needs to access the value?

**Comment by patriknw** [comment]
Thanks for reporting. This is something we should fix immediately.

I think easiest would be to not cache PromiseActorRef, and that also makes sense since they are only used one time (for the reply of `ask`) so there is no benefit of caching them.
