### ISSUE TITLE
EventEnvelope unapply is broken in 2.6.2 and 2.5.28

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#28532]
EventEnvelope's unapply for backwards compatibility is currently broken:
https://github.com/akka/akka/blob/44ad322a56b4edc40105c4ac8423e35a0bb41a90/akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala#L12-L23

The last parameter provided by `unapply` should be arg.event to be backwards compatible with Akka 2.6.1

@patriknw I think this is major bug as it breaks persistence query when the unapply is used and will not be catched by the compiler

**Comment by johanandren** [comment]
Ouch.

**Comment by patriknw** [comment]
um, that is really bad - thinking that we might have to cut a 2.6.3 right away

**Comment by patriknw** [comment]
2.5.28 is equally broken because we backported that change. Will release 2.5.29 without announcing 2.5.28
