### ISSUE TITLE
akka-persistence-tck doesn't cover support of defer/deferAsync

### ISSUE THREAD

**Issue by fredfp** [akka/akka#28541]
The akka-persistence plugin TCK fails to test support for `defer` and `deferAsync`.

As a result, the following akka-persistence plugins (at least) do not properly handle `defer` and `deferAsync`:
- akka-persistence-cassandra
- akka-persistence-jdbc

I assume this was never noticed because the symptoms are usually hidden until one has enough consecutive `defer/deferAsync` calls to trip akka-persistence's circuit-breaker (10 calls in succession are needed for this to happen given the default `max-failures` configuration). At this point the first call to `persist/persistAsync` will fail with a `CircuitBreakerOpenException` which is very hard to understand as no previous error was ever emitted or logged.

**Comment by renatocaval** [comment]
Fixed by #28542
