### ISSUE TITLE
Broadcast does not parallelize using the snippet from documentation

### ISSUE THREAD

**Issue by phiSgr** [akka/akka#28583]
https://doc.akka.io/docs/akka/current/stream/operators/Broadcast.html
The documentation added in https://github.com/akka/akka/pull/28091 suggested a way to parallelize processing in the `broadcast-async` snippet.

The method suggested is to add `Flow[A].async` between the `Broadcast` operator and the sinks.

I tried that but the processing is still sequential. Reproducer and write-up in this [repo](https://github.com/phiSgr/akka-streams-broadcast).

**Comment by johanandren** [comment]
Thanks for letting us know, that is a correct observation, would you be interested in PR:ing a fix?

**Comment by patriknw** [comment]
Great finding.

The repo suggests that the fix is to use `Flow.fold.async`. Why doesn't an empty `Flow[Int].async` introduce an async boundary?

**Comment by phiSgr** [comment]
> Why doesn't an empty `Flow[Int].async` introduce an async boundary?

There is indeed an async boundary, otherwise the execution would not jump threads.
The question is then: why those async boundaries do not make execution parallel?

> Thanks for letting us know, that is a correct observation, would you be interested in PR:ing a fix?

If I knew the answer I would be very happy to create a PR. But I don't.

**Comment by johanandren** [comment]
There is a boundary, but it is only around the `map(e => e)` (identity map) introduced by `Flow[Int]`, not the next operator, which instead end up in the same graph "island" as the broadcast (I think at least). To run the entire right hand part you would have to construct a graph and add an async boundary around that, so `~> Flow[Int].to(counS).async` or `~> countS.async`.

**Comment by patriknw** [comment]
but if there is a boundary, how can the later operator (sink) be fused together with the earlier broadcast?

is there an optimization of removing empty Flow entirely?

Is it same result with:
```
broadcast.out(0) ~> Flow[Int].map(a => a).async ~> countS
```

**Comment by phiSgr** [comment]
I think the mental model behind the wrong example is
- "an async boundary 'cutting' up the graph", and
- the pieces operate independently.

Instead it probably should be
- `something.async` colours the `something` part of the graph differently.
- groups of different colours operate independently.

`broadcast.out(0) ~> Flow[Int].map(a => a).async ~> countS`
`broadcast`, `countS`, and the other two sinks all have the same colour, so they won't be run by different threads.

**Comment by johanandren** [comment]
Sounds about right, `a.b.c.async` means "make an actor running a, b and c", so for `Flow[Int].async` that means only the flow identity operator. It would have worked if the `countS` operator in the sample was part of that graph, but that is not really possible to do and have a `.async` method in the graph builder API since `countS` is a `Shape` there, not a `Graph`.

**Comment by phiSgr** [comment]
Closed by #28589.
