### ISSUE TITLE
DistributedDataDocSpec: use multi-jvm test instead?

### ISSUE THREAD

**Issue by YikSanChan** [akka/akka#28606]
To verify custom ddata type and its serializer is working, I believe multi-jvm test is helpful otherwise it does not exercise the remote messaging path. However, https://github.com/akka/akka/blob/6bf20f4117a8c27f8bd412228424caafe76a89eb/akka-docs/src/test/scala/docs/ddata/DistributedDataDocSpec.scala is not running a multi-jvm test. Does it actually exercise the remote messaging path? If not, can we add multi-jvm test?

**Comment by raboof** [comment]
The test in akka-docs isn't a multi-jvm test, but we do have such tests in https://github.com/akka/akka/tree/6bf20f4117a8c27f8bd412228424caafe76a89eb/akka-distributed-data/src/multi-jvm/scala/akka/cluster/ddata . Do you think anything relevant is missing there?

**Comment by YikSanChan** [comment]
@raboof

question, are we able to tell the correctness of a custom ddata serializer without having a multi-jvm test?

yah, there are tests for some built-in ddata types, but I think it would be helpful to be explicit in the doc "you can verify your custom ddata serializer work by adding a multi-jvm test such as [some link]", if the answer to above question is "no"

thoughts?

**Comment by patriknw** [comment]
I think it is overkill to include that in this documentation example. Testing serialization, of application messages, is something that developers have to do, and so custom ddata types.

If we still are uncertain if the example is correctly serializing these types we could add a serialization test, but that should be more like a standalone unit test (as we have in several other places).

It would indeed be nice to have better utilities for testing serialization. We have issue https://github.com/akka/akka/issues/24623
