### ISSUE TITLE
Provide Flow.flatMapPrefixMat to expose inner materialized value to the outside

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28608]
The signature might look like this:

```scala
def flatMapPrefixMat[Out2, Mat2, Mat3](n: Int)(f: immutable.Seq[Out] => Flow[Out, Out2, Mat2])(combineMat: (Mat, Future[Mat2]) => Mat3): ReprMat[Out2, Mat3]
```

This could then be used as a building block for an alternative implementation of `Flow.lazyFutureFlow`.

/cc @eyalfa

**Comment by eyalfa** [comment]
?
didn't you notice [this](https://github.com/akka/akka/pull/28380/files#diff-d25227230bef7fd44d678521a8f07f1cR3150-R3158) when reviewing #28380

**Comment by jrudolph** [comment]
Woops, sorry, you have us covered already, must be blind :)
