### ISSUE TITLE
Strong consistency on read side

### ISSUE THREAD

**Issue by antoinesauray** [akka/akka#28627]
It would be great to have the choice between strong and eventual consistency for read sides. In my experience, eventual consistency is one of the things that scares away some teams and organizations.

This feature exists in elixir commanded https://github.com/commanded/commanded

**Comment by chbatey** [comment]
Hi @antoinesauray akka persistence is strongly consistent (by that I mean you can always read what you just wrote) on the read side for a persistent actor.

For persistence query it is up to the journal implementation and is per query. For example, for eventsByPersistenceId all journals AFAIK are atomic. For eventsByTag the JDBC journal is as it is just an index where as the Cassandra and Couchbase ones aren't as they use a separate table / async index.

Any view build from persistence query will be eventually consistent but that isn't something akka is involved in.
