### ISSUE TITLE
Possible race condition in Akka Persistence that can lead to lost events when using persistAsync()

### ISSUE THREAD

**Issue by RibleStrype** [akka/akka#28629]
We use Akka Persistence (v 2.5.27) with Cassandra plugin. Recently during Cassandra hardware upgrade (during which Cassandra was flaky) we encountered gaps in sequence numbers in the journal for several actors making them unable to recover. These actors save events using `persistAsync()`.
During investigation the following issue was found:

The `EventSourced` trait uses method `flushJournalBatch` to write a batch of events to the journal. This is "guarded" by `writeInProgress` flag with the intention to make sure that only one batch is being written at a time.
The interesting thing happens on persistence failure. The journal signals the failure to an actor by sending multiple messages: one `WriteMessagesFailed` and one or more `WriteMessageFailure`.
`WriteMessagesFailed ` clears the `writeInProgress ` flag and the first `WriteMessageFailure` stops the actor. So it makes it possible for the actor to persist more events in between the `writeInProgress` flag is cleared and the actor is stopped. This scenario may lead to gaps in journal sequence numbers.

**Comment by patriknw** [comment]
Yes, that is a reason I often say when people ask me if they should use persistAsync. I guess we should document this and other drawbacks more clearly. I think the Cassandra plugin has a config for `gap-free-sequence-numbers`, but I'm not sure that is enough. eventsByTag will definitely not work with gaps.

**Comment by RibleStrype** [comment]
I see that in general `persistAsync` is tricky, but speaking of the use case described above: is there any reason why persistence failure is signalled by the journal to an actor with multiple messages?
What if we don't reset the `writeInProgress` flag on `WriteMessageFailed` and just let the persistent actor stop itself on `WriteMessageFailure `?
I think it could fix this particular issue. Should I do a PR?

**Comment by patriknw** [comment]
I don’t have the code in front of me now, but stopping sounds good. Surprised that it doesn’t, since that is the normal error handling. pr welcome

**Comment by fredfp** [comment]
As it seems the PR is ready, could this be added to the akka 2.6.4 milestone (https://github.com/akka/akka/milestone/162) ? That milestone already contains a critical fix for those using `deferAsync`: https://github.com/akka/akka/issues/28541

**Comment by johanandren** [comment]
@fredfp the PR is still awaiting a second review before it can be merged, we usually don't set milestone on the issue until we merge the PR and are sure it will go in that release (it's however very likely it will end up in 2.6.4)
