### ISSUE TITLE
LazyFlowSpec and/or FlowFlatMapPrefixSpec frequently fail

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#28620]
or so I am finding in the Scala 2.13 community build

example of a recent run where they both failed: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk11-integrate-community-build/1198/

I have seen `LazyFlowSpec` fail on both JDK 8 and 11. `FlowFlatMapPrefixSpec` I have only seen fail on JDK 11, but I don't think I have enough data to be sure that the problem is 11+ specific.

**Comment by raboof** [comment]
That's interesting, we haven't seen them failed in our CI (since otherwise we'd have created issues for those), and we do have a nightly 2.13 build (https://jenkins.akka.io:8498/job/akka-nightly-2.13/), though that always runs on jdk8. Let's look into this.

**Comment by johanandren** [comment]
Details: 

```
[akka-stream] [info] - must complete normally when upstream completes BEFORE the stage has switched to the inner flow *** FAILED *** (5 seconds, 47 milliseconds)
[akka-stream] [info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnNext(1)
[akka-stream] [info]   at scala.Predef$.assert(Predef.scala:282)
[akka-stream] [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:419)
[akka-stream] [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:396)
[akka-stream] [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:396)
[akka-stream] [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:929)
[akka-stream] [info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:380)
[akka-stream] [info]   at akka.stream.scaladsl.LazyFlowSpec.$anonfun$new$57(LazyFlowSpec.scala:261)
[akka-stream] [info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[akka-stream] [info]   at akka.stream.scaladsl.LazyFlowSpec.$anonfun$new$56(LazyFlowSpec.scala:251)
```

and 

```
[akka-stream] [info] - must downstream cancellation is propagated via the materialized flow *** FAILED *** (2 seconds, 14 milliseconds)
[akka-stream] [info]   Some(Success(NotUsed)) was not empty (FlowFlatMapPrefixSpec.scala:264)
[akka-stream] [info]   org.scalatest.exceptions.TestFailedException:
[akka-stream] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[akka-stream] [info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
[akka-stream] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6834)
[akka-stream] [info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.$anonfun$new$74(FlowFlatMapPrefixSpec.scala:264)
[akka-stream] [info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[akka-stream] [info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.$anonfun$new$73(FlowFlatMapPrefixSpec.scala:250)
```

**Comment by johanandren** [comment]
@eyalfa could you take a look at the `FlowFlatMapPrefix` failure and see if it is something obvious (given that you recently contributed it)

**Comment by johanandren** [comment]
The `LazyFlowSpec` failure is likely #28497 which a fix is in progress for. 

Taking a look at the other one.

**Comment by SethTisue** [comment]
https://github.com/scala/community-build/pull/1100

**Comment by SethTisue** [comment]
`LazyFlowSpec` still fails frequently:

* April 5 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/819/artifact/logs/akka-stream-build.log
* April 5 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/818/artifact/logs/akka-stream-build.log
* April 5 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/817/artifact/logs/akka-stream-build.log
* April 2 https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3345/artifact/logs/akka-stream-build.log
* March 29 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/801/artifact/logs/akka-stream-build.log
* March 20 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/771/artifact/logs/akka-stream-build.log
* March 19 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/768/artifact/logs/akka-stream-build.log
* March 19 https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3308/artifact/logs/akka-stream-build.log
* March 7 https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3276/artifact/logs/akka-stream-build.log

many of these failures are on JDK 14, but some of them are on JDK 8

**Comment by eyalfa** [comment]
@SethTisue , do u c newer failures of flatMapPrefix? glanced over the last log and could only find warnings regarding the coroner thread.
I'd appreciate if u could pint me to a flatMapPrefix related issue so I could take a look and hopefully come up with a fix.

**Comment by johanandren** [comment]
@eyalfa if you search for *** in the logs you will find it.

Here's one from April 5:

```
[akka-stream] Stream is completed. No debug information is available
[akka-stream] [info] - must complete normally when upstream completes BEFORE the stage has switched to the inner flow *** FAILED *** (5 seconds, 37 milliseconds)
[akka-stream] [info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnNext(1)
[akka-stream] [info]   at scala.Predef$.assert(Predef.scala:282)
[akka-stream] [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:419)
[akka-stream] [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:396)
[akka-stream] [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:396)
[akka-stream] [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:929)
[akka-stream] [info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:380)
[akka-stream] [info]   at akka.stream.scaladsl.LazyFlowSpec.$anonfun$new$57(LazyFlowSpec.scala:261)
[akka-stream] [info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[akka-stream] [info]   at akka.stream.scaladsl.LazyFlowSpec.$anonfun$new$56(LazyFlowSpec.scala:251)
```

**Comment by eyalfa** [comment]
> complete normally when upstream completes BEFORE the stage has switched to the inner flow

that's lazy flow's spec. some of the issues there should be fixed by #28729  .
are there any issues with flatMapPrefix's tests?

**Comment by johanandren** [comment]
Ah, sorry, I misread your comment @eyalfa

**Comment by SethTisue** [comment]
`FlowFlatMapPrefixSpec` still sometimes fails as well. examples:

* April 4 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1334/artifact/logs/akka-stream-build.log
* April 2 https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3349/artifact/logs/akka-stream-build.log

**Comment by eyalfa** [comment]
@johanandren , since we are aware of some race conditions in the current impl and there's some work in progress to replace the impl, do u think it makes sense to disable this test at the moment?

**Comment by johanandren** [comment]
Sure, just that we remember looking into that they are gone once the rewrite completes

**Comment by eyalfa** [comment]
> `FlowFlatMapPrefixSpec` still sometimes fails as well. examples:
> 
> * April 4 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1334/artifact/logs/akka-stream-build.log
this one looks like a mistaken assert in the test at akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:379, the assert races with the materialization of the nested flow which is not guaranteed to be delayed. this assertion (`notUsedF.value should be(empty)`) should be removed
> * April 2 https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3349/artifact/logs/akka-stream-build.log
seems like the exact same issue

**Comment by SethTisue** [comment]
perhaps related, I've also seen `akka.stream.scaladsl.FlowPrefixAndTailSpec` fail, e.g. at https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/992/artifact/logs/akka-stream-build.log

**Comment by SethTisue** [comment]
some recent `FlowFutureFlowSpec` failures:

**akka-stream** fail Oct 12
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1286/artifact/logs/akka-stream-build.log
  akka.stream.scaladsl.FlowFutureFlowSpec
**log4cats** hang Oct 9
  https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk8-integrate-community-build/3791/
**scalatest-tests** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.11.x-jdk11-integrate-community-build/903/artifact/logs/scalatest-tests-build.log
  org.scalatest.concurrent.ConductorFixtureDeprecatedSuite
**sttp** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1978/artifact/logs/sttp-build.log
  loader constraint violation
**akka-more** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1976/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec
**sbt-librarymanagement** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.12.x-jdk8-integrate-community-build/6113/artifact/logs/sbt-librarymanagement-build.log
  sbt.internal.librarymanagement.ModuleResolversTest
**akka-more** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1974/artifact/logs/akka-more-build.log
  akka.actor.typed.delivery.ReliableDeliveryChunkedSpec
**akka-more** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1972/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec
**akka-more** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1971/artifact/logs/akka-more-build.log
  akka.cluster.sharding.StartEntitySpec
**log4cats** timeout Oct 8
  https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk15-integrate-community-build/1269/console
**akka-more** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1970/artifact/logs/akka-more-build.log
  akka.cluster.sharding.StartEntitySpec
**akka-more** fail Oct 8
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1969/artifact/logs/akka-more-build.log
  akka.actor.typed.delivery.ReliableDeliverySpec
**akka-stream** fail Oct 7
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1265/artifact/logs/akka-stream-build.log
  akka.stream.snapshot.MaterializerStateSpec, akka.stream.scaladsl.FlowFutureFlowSpec
**akka-stream** fail Oct 7
  https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk15-integrate-community-build/1264/console
  akka.stream.scaladsl.FlowPrefixAndTailSpec
**akka-more** fail Oct 7
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk8-integrate-community-build/3777/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec
**akka-stream** fail Oct 6
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1263/artifact/logs/akka-stream-build.log
  akka.stream.scaladsl.FlowFutureFlowSpec
**akka-stream** fail Oct 6
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk15-integrate-community-build/1262/artifact/logs/akka-stream-build.log
  akka.stream.scaladsl.FlowFutureFlowSpec

I'm going to disable the test.

**Comment by johanandren** [comment]
The FlowFutureFlowSpec should be fixed by #29899

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/21682/testReport/junit/akka.stream.scaladsl/FlowFlatMapPrefixSpec/A_PrefixAndDownstream_with_akka_stream_Attributes$NestedMaterializationCancellationPolicy_4205394f_must_downstream_failure_is_propagated_via_the_materialized_flow/

**Comment by patriknw** [comment]
FlowFlatMapPrefixSpec should be fixed by https://github.com/akka/akka/pull/30490 and we have fixed something for LazyFlowSpec (or have another issue open for that).

**Comment by SethTisue** [comment]
I'm trying re-enabling a number of tests over at https://github.com/scala/community-build/pull/1468
