### ISSUE TITLE
Merge language-specific operator docs

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#28641]
Some operators only make sense in Java or Scala as each implementation has a variant that's specific to the programming language. Take for example scaladsl's `apply` vs javadsl's `from()`.

Other examples of these language-specific operators are:

 - [ ] `Source.future` vs `Source.completionStage`
 - [ ] `Source.futureSource` vs `Source.completionStageSource`
 - [ ] (others?)

We could merge the language-specific pages into a single one similar to what's been done in the [docs for `apply` and `from](https://doc.akka.io/docs/akka/current/stream/operators/Source/from.html).

Refs #25468

**Comment by johanandren** [comment]
Was this a decision or a suggestion? (If suggestion, maybe hold off on the "NICE FIRST CONTRIB" until decided).

IMO having them separate but cross linking between the ones that correspond is better so that there is a path to each of them through the toc etc.

**Comment by ignasi35** [comment]
@johanandren this was a [suggestion](https://github.com/akka/akka/pull/28639#discussion_r383301753). I've edited the subject for the time being.

**Comment by raboof** [comment]
> there is a path to each of them through the toc etc

the toc will already show the 'right' variation based on the java/scala toggle - but perhaps it is a bit too 'clever' and we should just show them both.

**Comment by johanandren** [comment]
Yeah, I think we should avoid magic-switching the toc structure.

**Comment by Captain1653** [comment]
It's the old issue. Looks like I'm doing it in #22904.  Is it make sense to close it?

**Comment by johanandren** [comment]
Let's close it.
