### ISSUE TITLE
Incorrect decodeString in ByteString1

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28652]
It's starting from the beginning and ignoring the `startIndex`:

```
  override def decodeString(charset: String): String =
    new String(if (length == bytes.length) bytes else toArray, charset)
  override def decodeString(charset: Charset): String = // avoids Charset.forName lookup in String internals
    new String(if (length == bytes.length) bytes else toArray, charset)`
```

**Comment by viktorklang** [comment]
@johanandren This might actually work due to implication: if length == bytes.length then startIndex must be 0, and toArray will do the right thing since it will slice off from the startIndex.

So I might have jumped the shark on this one!
