### ISSUE TITLE
akka.stream.scaladsl.LazySourceSpec has repeatedly failed in the community build

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#28689]
latest occurrence: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/743/artifact/logs/akka-stream-build.log

```
[akka-stream] [info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 20 milliseconds)
[akka-stream] [info]   true did not equal false (LazySourceSpec.scala:139)
[akka-stream] [info]   org.scalatest.exceptions.TestFailedException:
[akka-stream] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[akka-stream] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[akka-stream] [info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$35(LazySourceSpec.scala:139)
[akka-stream] [info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[akka-stream] [info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$34(LazySourceSpec.scala:127)
[akka-stream] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

it has failed about 10 times in the last three months, which isn't super super often, but it's not super rare either

it has failed on JDK 11, 13, and 14. I haven't seen it fail on 8, but I don't think it's enough data to be sure either way whether it's 11+ specific.

all the failures have been on Scala 2.13, but the 2.12 build is still on Akka 2.5, so it's possibly 2.6-specific, possible 2.13-specific, possibly both.

**Comment by jrudolph** [comment]
Now failed in our nightlies as well:

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7775/testReport/junit/akka.stream.scaladsl/LazySourceSpec/Source_lazyFutureSource_must_never_construct_the_source_when_there_was_no_demand/

**Comment by pvlugter** [comment]
Another failure in nightlies, for JDK 11:

https://jenkins.akka.io:8498/job/akka-nightly-jdk11/1000/testReport/junit/akka.stream.scaladsl/LazySourceSpec/Source_lazySource_must_never_construct_the_source_when_there_was_no_demand/

**Comment by patriknw** [comment]
Hopefully fixed by https://github.com/akka/akka/pull/30493
