### ISSUE TITLE
MaterializerState.streamSnapshots does not work with TLS

### ISSUE THREAD

**Issue by raboof** [akka/akka#28691]
When using MaterializerState.streamSnapshots while there is a stream running that uses TLS, the call fails.

This is because TlsModulePhase uses materializer.actorOf to create the TLSActor, but StreamSupervisor.takeSnapshotsOfChildren expects all children to understand the ActorGraphInterpreter.Snapshot message.

I'm not sure if the problem here is that TlsModulePhase should be creating the actor elsewhere in the hierarchy, or that TLSActor should also support the ActorGraphInterpreter.Snapshot message, or that StreamSupervisor should be more selective in picking what actors to ask for snapshots.

Reproducer at https://github.com/raboof/akka/pull/new/snapshot-stream-with-tls

**Comment by johanandren** [comment]
Time to rewrite that `TLSModule`! ;)

**Comment by jrudolph** [comment]
Ran into the same thing and debugged it for a long time...
