### ISSUE TITLE
Emit system startup log event with marker

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28711]
Can include information like:
* versions
* address uid
* configured downing provider (sbr)

**Comment by jewertow** [comment]
I was trying to find what should be the source of this event but I am not sure. Could you give me more context? I am interested in doing this.

**Comment by patriknw** [comment]
We are not quite sure about the requirements for this ourselves. The background context is that this would be useful to show in the Lightbend Console. This might not be the best ticket to work on right now. I'm sure you find something else.

**Comment by patriknw** [comment]
An alternative is to add more to Cinnamon versions event.
