### ISSUE TITLE
Dynamically adjust the retry frequency in ConsumerController

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28720]
ConsumerControllerImpl is sending the Request messages periodically with a fixed delay. Would be nice to avoid sending those when new SequenceMessage are arriving as expected. Reduced frequency (maybe with exponential backoff) when completely idle.

One consideration is  that it might be too much overhead to reschedule of each after each incoming SequenceMessage.

**Comment by hepin1989** [comment]
how about try to adjust it periodically?
