### ISSUE TITLE
InputStreamAdapter does not allow to read a length of 0

### ISSUE THREAD

**Issue by DarkDrek** [akka/akka#28751]
The `read` method of `InputStreamAdapter` requires a length > 0
https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala#L151

but the java documentation of the method specifies that in this case it should not read any bytes and return 0.

https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/InputStream.html#read(byte%5B%5D,int,int)

> If len is zero, then no bytes are read and 0 is returned

**Comment by raboof** [comment]
That's a good find, would you like to PR a fix?
