### ISSUE TITLE
Java Optional vs. Scala Option as message field

### ISSUE THREAD

**Issue by MarcinNowak-codes** [akka/akka#28781]
Hi,

I've just started to learn Akka. In the documentation I noticed that in Java example Optional (not serializable) is used as message field:

https://github.com/akka/akka/blob/ad0f19a694bfb97197113952f7beceae51a76df1/akka-docs/src/test/java/jdocs/typed/tutorial_3/inprogress1/Device.java#L25

But in Scala example Option (serializable) is used:

https://github.com/akka/akka/blob/ad0f19a694bfb97197113952f7beceae51a76df1/akka-docs/src/test/scala/typed/tutorial_3/DeviceInProgress.scala#L41

Would such code work in cluster?

Kindly regards,
Marcin

**Comment by raboof** [comment]
(This might be better as a question on https://discuss.akka.io)

This would work fine in a cluster: `Serializable` is about Java serialization, and Java serialization is not recommended in a cluster anyway. Rolling upgrades are difficult to do safely with Java serialization, it is inefficient and there are security concerns. You can read more at https://doc.akka.io/docs/akka/current/serialization.html .
