### ISSUE TITLE
code fragment in tutorial does not seem to work

### ISSUE THREAD

**Issue by schirmacher** [akka/akka#28787]
I worked through your tutorial (https://doc.akka.io/docs/akka/current/typed/guide/tutorial_1.html) and I could not get this code fragment to work:

    And create a ‘main’ class like above to start the actors and then send them a "stop" message:

    ActorRef<String> first = testKit.spawn(StartStopActor1.create(), "first");
    first.tell("stop");

The variable testKit is not defined in the tutorial.

What works for me is this code, similar to other tutorial code:

    public static void main(String[] args) {
    //        ActorRef<String> testSystem = ActorSystem.create(Main.create(), "testSystem");
    //        testSystem.tell("start");
            ActorRef<String> first = ActorSystem.create(StartStopActor1.create(), "first");
            first.tell("stop");
        }

As I am not an Akka expert my code might not be correct though.

**Comment by johanandren** [comment]
Indeed, that looks like some test code snuck into the Java sample. Thanks for letting us know!

**Comment by ennru** [comment]
Fixed with #28793
