### ISSUE TITLE
Doc generation nightly failing

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28784]
https://jenkins.akka.io:8498/job/akka-docs/3628/

and manually triggered repeating the failure:
https://jenkins.akka.io:8498/job/akka-docs/3629/

```
[info] Main Java API documentation to /localhome/jenkinsakka/workspace/akka-docs/target/javaunidoc...
[error] /localhome/jenkinsakka/workspace/akka-docs/Loading source file /localhome/jenkinsakka/workspace/akka-docs/akka-actor-testkit-typed/target/java/akka/actor/testkit/typed/CapturedLogEvent$.java...
[error] Loading source file /localhome/jenkinsakka/workspace/akka-docs/akka-actor-testkit-typed/target/java/akka/actor/testkit/typed/CapturedLogEvent.java...
[error] Loading source file /localhome/jenkinsakka/workspace/akka-docs/akka-actor-testkit-typed/target/java/akka/actor/testkit/typed/Effect$.java...
[error] Loading source file /localhome/jenkinsakka/workspace/akka-docs/akka-actor-testkit-typed/target/java/akka/actor/testkit/typed/Effect.java...
[error] Loading source file /localhome/jenkinsakka/workspace/akka-docs/akka-actor-testkit-typed/target/java/akka/actor/testkit/typed/FishingOutcome$.java...
```

**Comment by raboof** [comment]
Ugh, I'll look into these.

(the 'Loading source file' look like errors but aren't, I suspect the actual problem is the 'illegal start of type' errors hidden between them, but I'll bisect to verify)

**Comment by johanandren** [comment]
Still failing after this was merged: https://jenkins.akka.io:8498/view/Docs/job/akka-docs/3631/console

**Comment by raboof** [comment]
that build was b1346ad7a7225ff0dc164c8178a4c90c1e43e971, while the fix wasn't introduced to akka in 4b782e54b8a9a050913719f728bc9dc813bbaedb, one commit later

**Comment by johanandren** [comment]
Ah, I must have compared timestamps wrong. Good then, I triggered an immediate rebuild here.

**Comment by johanandren** [comment]
Fixed indeed. Thanks @raboof!
