### ISSUE TITLE
[2.6.x] FanoutProcessorImpl leaks SubscriptionTimeout message schedule (dead-letter pollution)

### ISSUE THREAD

**Issue by nktpro** [akka/akka#28810]
[On this line](https://github.com/akka/akka/blob/bf6576ce79bde15385ea90304e1af43dd25444f3/akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala#L127), `FanoutProcessorImpl` schedules a `SubscriptionTimeout` message to `self`, but never cancels the schedule if the actor terminates before the timeout duration (defaults to 5s).  As a consequence, it becomes a dead-letter and the application will be heavily polluted with dead-letter warnings that look like this:

`[INFO] [akkaDeadLetter][03/25/2020 18:54:12.585] [reproducer-akka.actor.default-dispatcher-5] [akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink] Message [akka.stream.impl.ActorProcessorImpl$SubscriptionTimeout$] from Actor[akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink#-553970889] to Actor[akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink#-553970889] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://reproducer/system/Materializers/StreamSupervisor-0/flow-0-1-fanoutPublisherSink#-553970889] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.`

This becomes severe when an application has a high frequency of short-lived streams, with each stream lasts less than 5 seconds.

Here's a simple reproducer:

```
import akka.actor.ActorSystem
import akka.stream.scaladsl.Source

object Reproducer {
  def main(args: Array[String]): Unit = {
    implicit val as: ActorSystem = ActorSystem("reproducer")
    val (_, s) = Source
      .single(1)
      .preMaterialize()
    s.runForeach(println)
    // Dead-letter log will print out 5s later
  }
}
```

**Comment by hepin1989** [comment]
@nktpro Will come up an improvement? for short live stream yes.

**Comment by johanandren** [comment]
Sounds good to fix, please PR
