### ISSUE TITLE
Open up `ClassicActorSystemProvider.classicSystem` as public API?

### ISSUE THREAD

**Issue by ennru** [akka/akka#28818]
Should the method `ClassicActorSystemProvider.classicSystem` become public API?

## Background

The `ClassicActorSystemProvider` is an interface to allowing the use of both classic `akka.actor.ActorSystem` and `akka.actor.typed.ActorSystem[_]` without any adapters.

https://github.com/akka/akka/blob/bf6576ce79bde15385ea90304e1af43dd25444f3/akka-actor/src/main/scala/akka/actor/ClassicActorSystemProvider.scala#L16-L21

Originally, the accessor is intended for Akka internal use only.

This discussion [started](https://github.com/akka/akka/pull/28765#discussion_r398018479) in the backport PR to make the actor system implementations in Akka 2.5 implement the provider interface.

### Use cases

Akka Extensions need access to the actor system and should allow creation from a typed actor system.

The interface is important for other libraries (such as Alpakka) to make the API accept both classic and typed actor systems when internally a classic actor system is required (eg. to use Akka HTTP).

**Comment by jrudolph** [comment]
I guess the disadvantage is that a migration to a potential native typed ActorSystem might become harder. But de facto, we are already somewhat dug into that hole.

**Comment by patriknw** [comment]
+1 to making it public

I doubt there is any usefulness of ClassicActorContextProvider outside the original streams materializer thing so we can leave that as is.
