### ISSUE TITLE
Add retry on exception and retry on result support.

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#28824]
With the current retry implementation, it will retry on any exception.

https://github.com/akka/akka/blob/37d87811b5c0622f55e0c07dd0c2e09665cfbff9/akka-actor/src/main/scala/akka/pattern/RetrySupport.scala#L166

A better way is to add support with RetryDirective, and then can implement retry on exceptions or retry on results from it, as `resilience4j-retry` does.
```java
RetryConfig config = RetryConfig.custom()
  .maxAttempts(2)
  .waitDuration(Duration.ofMillis(1000))
  .retryOnResult(response -> response.getStatus() == 500)
  .retryOnException(e -> e instanceof WebServiceException)
  .retryExceptions(IOException.class, TimeoutException.class)
  .ignoreExceptions(BunsinessException.class, OtherBunsinessException.class)
  .build();

```

**Comment by hepin1989** [comment]
Then the API will be more complicated, maybe with an `RetryOpts` then.

**Comment by renatocaval** [comment]
Do you mean with an overloaded version that receives a `RetryOpts`? That's a good option as we can't change the existing API. Extending it with a overload method is OK though.

**Comment by hepin1989** [comment]
Yes, then the current method could delegate to it.

**Comment by patriknw** [comment]
Retry on result can be done via `map` or `flatMap` of the result Future, turning it into a failed Future.

Retry on selected exceptions can be done via `recover` or `recoverWith`, turning it into a non-failed Future.

**Comment by Captain1653** [comment]
This issue is quite old. There are not new comments for 3 years.

The solution was mentioned above:

> Retry on result can be done via map or flatMap of the result Future, turning it into a failed Future.
> 
> Retry on selected exceptions can be done via recover or recoverWith, turning it into a non-failed Future.

Should this issue be clsoed?
