### ISSUE TITLE
Behaviors.same is not using correct current behavior for repeated unstash(same) calls

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28831]
When using `stashBuffer.unstash(Behviors.same, ...)` the current behavior is looked up via the context. That doesn't work if `unstash(same)` is called when a previous unstash is already in progress (in same call stack), and previous unstash has switched behavior. It will still lookup the original current behavior from the context.

I noticed this when working on https://github.com/akka/akka/pull/28775

**Comment by renatocaval** [comment]
Fixed in #28832
