### ISSUE TITLE
Add Source.fromStream for javadsl

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#28839]
```scala
  def fromStream[O](f:java.util.function.Supplier[java.util.stream.Stream[O]]):javadsl.Source[O, NotUsed]

```

**Comment by johanandren** [comment]
That's already present in `akka.stream.javadsl.StreamConverters#fromJavaStream`, did you miss that one or are you suggesting to add it in `Source` as well?

**Comment by hepin1989** [comment]
@johanandren I want them to be added directly to Source for user friendly.

**Comment by ennru** [comment]
Added with #28881
