### ISSUE TITLE
Invoking Akka typed actor from outside actorSystem or from Untyped Actor

### ISSUE THREAD

**Issue by politrons** [akka/akka#28836]
Hi all, 

I´m trying to follow documentation of how to interact from outside of actorSystem to an actor typed, or from an old untyped actor, but I cannot see from where do you get this `cookieFabric` to make the `ask` call

https://doc.akka.io/docs/akka/current/typed/interaction-patterns.html#request-response-with-ask-from-outside-an-actor

Also I cannot make it compile the call using ask pattern since how suppously I´m going to have 

`implicit val ec = system.executionContext
`
out of an Actor

Maybe I'm missing something here. Any chance to get the whole source to check what I'm missing.

Regards.

**Comment by patriknw** [comment]
Was there something missing in the documentation that should be improved?

**Comment by politrons** [comment]
Hi, 

In the documentation you should specify that you get all implicit values from the ActorSystem that you obtain once you create the reference of the typed actor you're going to invoke
