### ISSUE TITLE
rsync errors don't fail the build

### ISSUE THREAD

**Issue by raboof** [akka/akka#28850]
Noticed while testing #28828: when we rsync (for publishing paradox, api or japi docs) an rsync failure doesn't fail the build.

A simple way to fix this would be by merging https://github.com/lightbend/sbt-publish-rsync/pull/3 and https://github.com/lightbend/sbt-publish-rsync/pull/2 and then switching to that (instead of the embedded plugin) in the Akka build.

**Comment by patriknw** [comment]
I think this has been done

**Comment by raboof** [comment]
(Indeed, in #28868)
