### ISSUE TITLE
Create remember entities benchmark(s)

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28876]
Given the ambition to make remember entities scale better and or have less latency impact, we need benchmarks to measure.

We should probably also add some flight recorder events to help figure out what is going on.

**Comment by chbatey** [comment]
We have `ClusterShardingRememberEntitiesPerfSpec` that does a good job of showing the throughput of starting entities

**Comment by chbatey** [comment]
One missing benchmark is to record latency. The current perf spec only records throughput.

For instance i just tested a throughput scenario where we stop entities and it is faster than not stopping them (fewer things in the datastructures). But we get logs for the buffers filling up so the latency must be getting worse but that isn't reflected in the current perf spec.

**Comment by patriknw** [comment]
@chbatey can we close this?

**Comment by johanandren** [comment]
This benchmark is in `akka.cluster.sharding.ClusterShardingRememberEntitiesPerfSpec`, we can close this.
