### ISSUE TITLE
TestActorRef with Akka actor typed

### ISSUE THREAD

**Issue by politrons** [akka/akka#28870]
Hi all,

I recently migrate from Untyped actor to typed, but the Useful Test framework is not working anymore. 

I cannot find any documentation of how to make works `TestProbe` and `TestActorRef`with Akka actor Typed

Regards

**Comment by johanandren** [comment]
`TestActorRef` functionality is, at least partially, covered by the `BehaviorTestKit` ([docs here](https://doc.akka.io/docs/akka/current/typed/testing-sync.html#synchronous-behavior-testing)).

A good resource for migrating is this page in the docs, where the `BehaviorTestKit` also mentioned: https://doc.akka.io/docs/akka/current/typed/from-classic.html

**Comment by politrons** [comment]
Thanks! I could not find that docu.

**Comment by politrons** [comment]
Sorry but using the `BehaviorTestKit` it cannot be used if you need to send as part of the message the ActorRef with the type that you expect.

Having this code before

     ```
 val statusDistributedActorMock = TestProbe()
      val getStatusService: ActorSystemTyped[GetStatus] = ActorSystemTyped(PlatformStatusService(StatusDistributedActor(statusDistributedActorMock.ref)), "platformStatusGetService")
      implicit val timeout: Timeout = 5.seconds
      implicit val ec: ExecutionContextExecutor = getStatusService.executionContext
      implicit val scheduler: typed.Scheduler = getStatusService.scheduler

      val future: Future[Set[PlatformStatusPayload]] = getStatusService.ask(ref => GetStatus(connectorStateKey, ref))
      val payloads: Set[PlatformStatusPayload] = Await.result(future, 10 seconds)
      assert(!payloads.isEmpty)
      statusDistributedActorMock.expectMsg(FiniteDuration(0, "millis"), GetStatusDistributed(connectorStateKey))
      statusDistributedActorMock.reply(StatusStore(Set(oracleClosed)))
      expectMsg(mockResponseOracleCloseStatus1)
```

When I invoke the service `getStatusService` from a non Akka Actor, I need the `ActorRef` that I pass as part of my message where I specify the type that I expect in return.

But using the `BehaviorTestKit`

```
    val serviceTestKit: BehaviorTestKit[PlatformStatusService.PlatformStatus] =
        BehaviorTestKit(PlatformStatusService(StatusDistributedActor(statusDistributedActorMock.ref)))
      serviceTestKit.run(GetStatus(connectorStateKey, WHERE I GET THE REF?))
```

**Comment by johanandren** [comment]
Doing async stuff, messaging with other actors (ask), dealing with futures, etc. is not something we intend to cover with the `BehaviorTestKit` even if that was possible with the `TestActorRef`. 

A lot of the more async things that was possible with `TestActorRef` was just too much of a hack and it is strongly recommended to do such things with an async test instead (so that means using the `ActorTestKit` instead)

**Comment by johanandren** [comment]
Would probably be good to mention that in the migration guide.

**Comment by politrons** [comment]
Hi again,

But as long as I tried before the ActorTestKit with a Behavior, it was not working. At least the TestProve that I was using inside it was not working properly. Maybe I’m missing something here.
The first code that I paste, I’m passing to my Behavior class constructor the TestProve statusDistributedActorMock. But Creating the Behavior using the ActorSystem as I do, the invocations to TestProve are not working

**Comment by johanandren** [comment]
That is more a request for help on writing tests, please use the forums https://discuss.lightbend.com/c/akka to get help for such things rather than the issue tracker.
