### ISSUE TITLE
Prefer @apidoc over @signature for stream operator docs

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#28901]
As more checkboxes in https://github.com/akka/akka/issues/25466 are being worked on, there's a side task to replace the use of [`@@signature`](https://github.com/akka/akka/blob/3eb9b3a1a6cc9060c8fe455c70aa48aa99e91716/akka-docs/src/main/paradox/stream/operators/ActorFlow/ask.md#L21) (often only used in the `scala` version of the docs) with [`@apidoc`](https://github.com/akka/akka/blob/f683241c40592faec7b0f91eb4e4c6d5282fc085/akka-docs/src/main/paradox/stream/operators/StreamConverters/fromOutputStream.md#L9).

The current status in docs for stream operators is inconsistent (some still use `@@signature`) and should be refactored.

**Comment by ennru** [comment]
Fixed with #29032
