### ISSUE TITLE
akka-serialization-jackson is NEVER using CBOR

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#28918]
When selecting jackson-cbor, serialization nevertheless uses JSON instread of CBOR. 

The reason seems to be related in the use of the Jackson API. For a "reproducer" and a potential fix see https://github.com/hseeberger/try-akka-jackson/blob/master/src/main/scala/tryakkajackson/Main.scala#L57.

/cc @jroper

**Comment by patriknw** [comment]
I can confirm that this is a bug. Cbor was lost in the refactoring for updating to Jackson 2.10 https://github.com/akka/akka/pull/27814. Tests were only verifying that the right serializer was selected and that it could do the serialization roundtrip, but not checking the format.

**Comment by hseeberger** [comment]
Nice!
