### ISSUE TITLE
akka-persistence leveldb-shared documentation not updated properly in akka 2.6.4 as showing older way of creating akka and initiating leveldb store

### ISSUE THREAD

**Issue by vg02111989** [akka/akka#28913]
Hi @patriknw 

I am using Akka - 2.6.4 and trying to implement Akka Cluster Sharding with Akka persistence so as to remember entities in case of node crash or any other failures to persist the state of the entity actor and user should not face any issue in case node will goes down.
I am running two instances of the application in two different JVM of same system as as I am using leveldb to write the journals, but for same system I should use leveldb-shared journal.
For using leveldb-shared journals I should inject the SharedLeveldbJournal from application which I am not able to do by following the way it should be injected mentioned in the docs

https://github.com/akka/akka/blob/v2.6.4/akka-docs/src/test/java/jdocs/persistence/LambdaPersistencePluginDocTest.java#L40

kindly have a look and provide with some support

**Comment by johanandren** [comment]
Note that for a distributed application leveldb backed persistence is not a good idea, the `SharedLevelDbJournal` is for testing only, and even for testing the proxy plugin may be a better idea.

Instead using ddata as sharding store and enabling durable store (backed by LMBD) is the way to go if you want to avoid introducing the operational complexity of a separate database. See docs here: https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html#behavior-when-enabled

**Comment by vg02111989** [comment]
Thanks Johanandren.

Got my issue and able to resolve.

Thanks for your valuable feedback

**Comment by vg02111989** [comment]
Thanks Johanandren.

Got my issue and able to resolve.

Thanks for your valuable feedback
