### ISSUE TITLE
Cleanup jenkins jobs

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28922]
Since we will have to move our jenkins instances soon, we should clean up existing jobs.

For akka-http jobs I either removed the task if it was clearly not needed any more. For others that we might still want to look into for reference, I used a `(legacy)` prefix in the name to note that they don't need to be migrated right now. When the main migration is done we should look at the `(legacy)` tasks again and see if anything needs to be salvaged.

**Comment by patriknw** [comment]
I renamed a bunch more. Should be rather complete now. Maybe a few more that are not important.

cc @adriaanm

**Comment by adriaanm** [comment]
Thanks! I’ll dump the configs and start the move next week.

**Comment by Captain1653** [comment]
This issue is quite old. Now akka uses GitHub Actions. Should it be closed?
