### ISSUE TITLE
Actor consistently dropping ask message

### ISSUE THREAD

**Issue by enzeart** [akka/akka#28936]
I've implemented an extension that creates an actor and holds a reference to it. The first message I send to this actor with the **ask** pattern always times out, no matter how long I wait to send it after the actor system starts up. If I **tell** the actor a dummy message after creating it, the problem goes away:

```scala
package io.magus

import akka.actor.typed.{ActorRef, ActorSystem, Extension, ExtensionId}
import io.magus.session.SessionManager
import akka.actor.typed.scaladsl.adapter._
import io.magus.session.SessionManager.Ping

object EngineExtension extends ExtensionId[EngineExtension] {

  override def createExtension(system: ActorSystem[_]): EngineExtension = new EngineExtension(system)
}

class EngineExtension(system: ActorSystem[_]) extends Extension {
  val sessionManager: ActorRef[SessionManager.Command] = {
    val ref = system.toClassic.spawn(SessionManager(), name = "session-manager")
    ref ! Ping // Remove this and the initial ask always fails
    ref
  }
}

...
 LoginAttempt(sessionDescriptor) <- engineExtension.sessionManager.ask[LoginAttempt](Login(session, _))
...
```

Akka Version: 2.6.3
Operating System: macOS Mojave 10.14.6

**Comment by raboof** [comment]
Thanks for reaching out! I tried to reproduce this problem, but with a simple system like https://github.com/raboof/akka-reproduce-28936/blob/master/src/main/scala/Main.scala it seems to work for me. Apparently there is still something relevant different between that project and yours. Could you try to narrow down what triggers the problem?

**Comment by johanandren** [comment]
As a side note, probably not related to the issue you are seeing, calling spawn like that will blow up if the original system is a typed actor system since for those the user has provided the user guardian and it is not possible to spawn arbitrary children in that. You should use `systemActorOf` for actors started from extensions .

**Comment by enzeart** [comment]
@raboof The extension is being created via configuration inside of a play 2.8.1 server. I adapt the typed extension to a classic one with the code below. The extension is then accessed elsewhere in the application via dependency injection

```scala
package io.magus

import akka.actor.{ActorSystem, ExtendedActorSystem, Extension, ExtensionId, ExtensionIdProvider}
import akka.actor.typed.scaladsl.adapter._

object ClassicEngineExtension extends ExtensionId[ClassicEngineExtension] with ExtensionIdProvider {

  override def createExtension(system: ExtendedActorSystem): ClassicEngineExtension = new ClassicEngineExtension(system)

  override def lookup(): ExtensionId[_ <: Extension] = ClassicEngineExtension
}

class ClassicEngineExtension(system: ActorSystem) extends Extension {
  val engineExtension: EngineExtension = new EngineExtension(system.toTyped)
}
```

**Comment by raboof** [comment]
@enzeart even when introducing your ClassicEngineExtension to the https://github.com/raboof/akka-reproduce-28936 that still doesn't reproduce the issue, unfortunately. Could you distill an example project showing the problem?

**Comment by enzeart** [comment]
@raboof I'm working on a sample project to try and capture the issue. I'm not able to reproduce the failure yet, so there must be some subtle details of my original application contributing to it. I'll get back to you once I've isolated the proper conditions.

**Comment by enzeart** [comment]
@raboof I think I've isolated the issue. It seems to be related to `Behaviors.setup`. I've created an example [here](https://github.com/enzeart/akka_issue)

I suspect the issue might have something to do with the "deferred" nature of Behaviors.setup. From what I've tested, the first message is missed, and subsequent messages are picked up by the behavior.

**Comment by raboof** [comment]
Ah, spotted it! The problem is in the `SessionManager` actor. It looks like this:

```
private class SessionManager(context: ActorContext[Command]) extends AbstractBehavior[Command](context) {

  override def onMessage(msg: Command): Behavior[Command] = Behaviors.receiveMessage {
    case Login(session, replyTo) =>
      replyTo ! LoginAttempt(s"Hi $session!")
      Behaviors.same
  }
}
```

When called, `onMessage` should handle the message and return the behavior to be used for the next message. In this case, you do nothing except returning a behavior created with `Behaviors.receiveMessage`. This neatly explains why the first message is always 'lost'.

So the fix is simple: instead of creating a new behavior in `onMessage`, directly process the message and return `Behaviors.same`:

```
private class SessionManager(context: ActorContext[Command]) extends AbstractBehavior[Command](context) {

  override def onMessage(msg: Command): Behavior[Command] = msg match {
    case Login(session, replyTo) =>
      replyTo ! LoginAttempt(s"Hi $session!")
      Behaviors.same
  }
}
```

**Comment by patriknw** [comment]
ah, using both functional and oo styles at the same time

**Comment by raboof** [comment]
I think this establishes this is not a bug, so let's move any follow-on discussion to https://discuss.akka.io . Thanks for getting in touch!

**Comment by enzeart** [comment]
Ahhhh, I see. Thank you for your help!
