### ISSUE TITLE
akka-protobuf-v3 exposes protobuf-java as a dependency

### ISSUE THREAD

**Issue by nick-nachos** [akka/akka#28939]
`akka-protobuf-v3` is supposed to shade `protobuf-java` in order to avoid causing versioning issues to the application layer. However, a quick look at Maven central shows that for some reason `akka-protobuf-v3` exposes `protobuf-java` as a compile dependency whereas `akka-protobuf` (which isn't shaded) doesn't.

See for example the following published POMs:

- https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf-v3_2.12/2.6.4/akka-protobuf-v3_2.12-2.6.4.pom
- https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.6.4/akka-protobuf_2.12-2.6.4.pom

I came across this issue while upgrading from Akka 2.5 -> 2.6 (specifically 2.6.4 for Scala 2.12) which broke some protobuf dependent code of ours. However, after a quick look on the Maven repo it seems that the issue is there for Scala 2.13 and other minor versions of Akka 2.6 as well.

It is possible to work around this for now (e.g. having Gradle force the `protobuf-java` version) but it seems like something that should be fixed.

**Comment by chbatey** [comment]
Thanks for reporting

**Comment by patriknw** [comment]
ouch, thanks for reporting
