### ISSUE TITLE
[Artery] Setting compression.actor-refs.max = 0 causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nodefactory-bk** [akka/akka#28967]
When setting
```
akka.remote.artery.advanced.compression {
  actor-refs.max = 0
}
```
artery won't communicate and drops messages with ArrayIndexOutOfBoundsException
```
[WARN] [04/24/2020 08:54:03.193] [dh-localhost-akka.remote.default-remote-dispatcher-10] [Decoder(akka://dh-localhost)] Dropping message due to: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
```

Tested with akka 2.5.31

**Comment by johanandren** [comment]
Confirmed on master (2.6)

**Comment by patriknw** [comment]
Ok, we I thought that was the (undocumented) way to disable it. We have
```
private[akka] final val Enabled = ActorRefs.Max > 0 || Manifests.Max > 0
```

We should make it possible to disable (since it's almost already implemented)

**Comment by patriknw** [comment]
A workaround is to set both manifests and actor-refs to 0.
```
     akka.remote.artery.advanced.compression {
        actor-refs.max = 0
        manifests.max = 0
      }
```

I will add a proper way to disable them, though,

**Comment by nodefactory-bk** [comment]
Would this disable the caching of actor refs with ActorRefResolveCacheWithAddress aswell?

**Comment by patriknw** [comment]
> Would this disable the caching of actor refs with ActorRefResolveCacheWithAddress aswell?

That is something else. I guess you ask because of https://github.com/akka/akka/issues/28959
We should rather fix that problem than trying to workaround by not caching.
