### ISSUE TITLE
Couchbase for Akka Persistence - Event Sourcing in Akka-2.6.4 version

### ISSUE THREAD

**Issue by vg02111989** [akka/akka#28971]
Hi,

I am using the latest version of Akka i.e. 2.6.4, also is using couchbase in my application and the same want to use for persisting event while using Akka persistence - event sourcing.
For attaching Akka Persistence Couchbase plugin, it seems only compatible with Akka-2.5.x version as mentioned here...
https://doc.akka.io/docs/akka-persistence-couchbase/current/overview.html#project-info

Kindly let us knew how we can use this plugin with Akka - 2.6.4

**Comment by patriknw** [comment]
Yes, it can be used with Akka 2.6.4.

We use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

**Comment by vg02111989** [comment]
Hi Patrik,

I had mentioned here thinking this as a feature request, but will put it discuss.akka.io also.

Will it be possible to provide some documentation which I can refer while using couchbase to store persistent entities

**Comment by patriknw** [comment]
I agree that the documentation can be clarified. Created issue https://github.com/akka/akka-persistence-couchbase/issues/238
