### ISSUE TITLE
Warning: ClusterSingletonManager unhandled event HandOverToMe in state Start

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#28979]
Might be similar to #25274, #26793

As the Handling in state Younger comments this might be from a quick restart.
Could this be safely suppressed in state Start?
```
    case Event(HandOverToMe, _) =>
      val selfStatus = cluster.selfMember.status
      if (selfStatus == MemberStatus.Leaving || selfStatus == MemberStatus.Exiting)
        logInfo("Ignoring HandOverToMe in Younger from [{}] because self is [{}].", sender().path.address, selfStatus)
      else {
        // this node was probably quickly restarted with same hostname:port,
        // confirm that the old singleton instance has been stopped
        sender() ! HandOverDone
      }
```

**Comment by patriknw** [comment]
@nvollmar in `Start` I don't think it should respond yet. It would be fine to handle and ignore the message (maybe log debug). It will quickly move to Younger, and then the retry of HandOverDone will be acknowledged.

**Comment by nvollmar** [comment]
@patriknw Thanks, I've reverted the pull request back to a simple ignore.
