### ISSUE TITLE
CompileJdk9  sortImports

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28982]
When running `sortImports`

```
[error] Expected ';'
[error] CompileJdk9:scalafix SortImports
```

Also, is it necessary to include the tasks at the end of the alias: `scalafmtAll;test:compile;multi-jvm:compile;reload` ?

@hepin1989 Could you follow up on this?

**Comment by hepin1989** [comment]
Let me do it.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/80403521-4b98f500-88f2-11ea-8b90-56b7c682265f.png)
`scalafmtAll;test:compile;multi-jvm:compile;reload ` is to make sure the code do compile.

**Comment by patriknw** [comment]
but isn’t it better to compile separately, so sortImports can be as quick as possible

**Comment by hepin1989** [comment]
@patriknw How about keeping the `scalafmtAll`
