### ISSUE TITLE
Invalid sanitize of ActorSystem name in TestKitUtils

### ISSUE THREAD

**Issue by andrii-r** [akka/akka#28994]
In akka.actor.ActorSystemImpl there is validation of name that allows the following pattern: `^[a-zA-Z0-9][a-zA-Z0-9-_]*$` and it is allowed to use hyphen in names, but according to logic in https://github.com/akka/akka/blob/master/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestKitUtils.scala
( and later this logic was moved to akka-testkit/src/main/scala/akka/testkit/TestKitUtils.scala in this commit
https://github.com/akka/akka/commit/1dbc54b28a0da5bc519b2203a1572de9950c875e#diff-5c099ba6a094171d9104fc162233f0c1 ) sanitization of ActorSystem name was narrowed and now it is not prossible to use hyphen in name anymore as it is being replaced with underscore.

So that if I have ActorSystem name called 'c-wallet' and it is running on production for a long time, I should rename it to 'c_wallet' if I want my tests work properly. 

I would suggest that sanitization should be more weak and do not replace hyphen in ActorSystem name.

**Comment by patriknw** [comment]
The purpose of using that `scrubActorSystemName` is when creating a name from a test class, via `testNameFromCallStack`. I see that it's also used in the `ActorTestKit.apply(name: String)`. That must be an oversight. No reason to sanitize that name if it's given by the user as a String.

@andrii-r Would you be up for creating a pull request fixing that?

**Comment by andrii-r** [comment]
Ok, I will create pull request. 
@patriknw  But just co clarify, I thinks we can leave calling scrubActorSystemName(name) in ActorTestKit.apply(name) for backward compatibility, if someone is already using it in tests with some weird name of actor system. And I would just fix logic inside scrubActorSystemName(), what do you think?

**Comment by patriknw** [comment]
works for me

**Comment by andrii-r** [comment]
should this issue be closed? since changes were already released in 2.6.8

**Comment by raboof** [comment]
Yes, thanks for the ping, sorry for missing that!
