### ISSUE TITLE
A way to verify tags with persistence testkit

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29063]
Currently the persistence testkit only gives the user access to the user events but it would be good if it was possible to also look at and verify tags for the events.

**Comment by manonthegithub** [comment]
#28519 
im working on PersistentQuery support for the testkit, changes I made there should address that

**Comment by johanandren** [comment]
Great, had not seen that. 👍

**Comment by johanandren** [comment]
No need to track this separately then.
