### ISSUE TITLE
Add GroupedWeighted GraphStage and FlowOp

### ISSUE THREAD

**Issue by michaeljmarshall** [akka/akka#29066]
### Request
Add a `GroupedWeighted` `GraphStage` and associated `FlowOps` method to the Akka Streams library.

### Possible Implementation
The class definition for the Graph Stage would be:

```Scala
class GroupedWeighted[T](maxWeight: Long, costFn: T => Long) extends GraphStage[FlowShape[T, immutable.Seq[T]]]
```

The stream semantics would be: 

1. **emits** when the specified weight limit has been reached or upstream has completed
2. **backpressures** when a group has been assembled and downstream backpressures
3. **completes** when upstream completes

### Context
Akka streams already has Graph Stages for `Grouped`, `GroupedWithin`, and `GroupedWeightedWithin`. The `GroupedWeighted` would naturally fit in as the unbounded (by time) version of `GroupedWeightedWithin`. It would also fit in as the analogue to `Grouped`, especially because `Grouped` is essentially `GroupedWeighted` with a constant cost function of 1.

### Example Use Case
When uploading individual parts of a multipart upload to S3, each part, except for the last one, must have a size greater than 5 MiB. In building a stream that uploads parts to S3 and then completes the upload upon stream completion, I need to make sure that only the final element is allowed a size of less than 5 MiB. `GroupedWeighted` fulfills these requirements.

I could consider using `GroupedWeightedWithin` for the stream mentioned above. However, that introduces unnecessary overhead by keeping track of a timer that should never trigger, and there is a chance that the upload will fail if the `Within` condition is met before the end of the stream. Instead, I would prefer to buffer indefinitely until the final element in the stream, as that part can be fewer than 5 MiB.

### Implementation
If this new feature gains traction, I'm be happy to help implement it.

**Comment by hepin1989** [comment]
This feature would be very helpful.

**Comment by michaeljmarshall** [comment]
> Alternatively, `groupedWeightedWithin` could be changed to allow for indefinite durations.

Yes, that would be equivalent. Although, I don't think it would be consistent with the usage of the word `Within` in the rest of akka streams api. In all of the cases I can find, whenever a flow or a graph ends with the word `Within`, the framework takes a `FiniteDuration` to measure the time. Unless there is a plan to change this pattern, I think it would be more consistent to add `groupedWithin`.

**Comment by ennru** [comment]
`groupedWeighted` seems OK to me, but it should reuse the `GroupedWeightedWithin` stage if possible.

**Comment by hepin1989** [comment]
Yes, we can implement it with that one, or named with `groupWeightedWithin` and `groupWeighted`?

**Comment by michaeljmarshall** [comment]
I've completed my initial work to add the `GroupedWeighted` graph stage and flow op. The PR has the code changes, additional documentation, and new tests. The PR failed the binary compatibility check because I removed the `Grouped` graph stage class/object. It was private, so I am pretty sure all that is needed is to update the filters appropriately. My outstanding question is how the community feels about the usage of `minWeight` instead of `maxWeight` for the `GroupedWeighted` graph stage. I think the right choice is `minWeight`, but I'm happy to entertain the alternative. This is my first time contributing to the project, so please let me  know what is needed next. Thanks!
