### ISSUE TITLE
Change sentence in   

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka#29060]
In the Gossip Convergence section of the Cluster Specification doc page, 2nd sentence = "This is when a node can prove that the cluster state he is observing has been observed by all other nodes in the cluster." Change the word "he" to "it".

Path to doc page - akka-docs/src/main/paradox/typed/cluster-concepts.md

**Comment by patriknw** [comment]
Thanks @mckeeh3, would you like to open a PR fixing it, or shall I take care of it?
