### ISSUE TITLE
Add akka/akka to Dotty Community build

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#29084]
Just like what endpoint just did(refs:refs :https://github.com/lampepfl/dotty/pull/8979), I would love to see akka/akka join the dotty community build.
depends: https://github.com/akka/akka/issues/28835

**Comment by patriknw** [comment]
In progress here https://github.com/akka/akka/pull/29956 but much more will be needed after that PR

**Comment by hepin1989** [comment]
this is done
