### ISSUE TITLE
Extend backoff supervision reply while stopped

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#29082]
Instead of a fixed reply while stopped we'd need a more flexible approach for a more custom handling.

**Comment by Karasiq** [comment]
It would also be nice if it were possible to stash all incoming messages until the actor restarts.

**Comment by johanandren** [comment]
With the merged changes you could achieve that by having the stand by actor always stash/buffer messages, and let the supervised actor tell the stand by it has started responding with the stashed/buffered messages.
