### ISSUE TITLE
Point to 2.6 from the 2.5 docs

### ISSUE THREAD

**Issue by raboof** [akka/akka#29087]
When browsing the 2.5 documentation, it would be good to show a warning pointing people to the 2.6 docs.

We have some infrastructure for this in place: akka-docs/src/main/paradox/assets/js/warnOldDocs.js reads https://akka.io/versions.json and shows a warning accordingly.

When a version is marked 'outdated', the warning shows "This version of Akka is outdated and not supported! Please upgrade to version 2.6.5 as soon as possible". That is too strong for Akka 2.5. Perhaps when an 'instead' is found but 'obsolete' is false, we could show a milder warning?

**Comment by renatocaval** [comment]
Makes total sense to show a milder warning for versions that are still maintained.

I wouldn't call it 'obsolete'. I think the distinction is which is the recommended version ('instead') and if the version is being maintained.


2.4.x =>  maintained = false, instead = 2.6
2.5.x =>  maintained = true, instead = 2.6
2.6.x =>  maintained = true

We can change `outdated` to `maintained`. Then we will have only two flagged with `maintained = true` and omit in all the others.

**Comment by raboof** [comment]
> We can change `outdated` to `maintained`.

I agree that would be better, but I'm not sure it's worth changing. Keep in mind if we change that we also have to go back and change it for old docs.



2.4.x => obsolete = true, instead = 2.6
2.5.x => instead = 2.6
2.6.x =>

might be good enough

**Comment by raboof** [comment]
This has already been done, see https://doc.akka.io/docs/akka/2.5/
