### ISSUE TITLE
Take terminated into account in ShardCoordinator.RebalanceWorker

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29093]
This would be a performance optimization for sharding rebalance.

If a region is terminated (e.g. downing of node) while the RebalanceWorker is waiting for the BeginHandOffAck it will not notice that and will timeout (after 1 minute). No harm, but would be faster to be able to continue the rebalance also for such case.

The parent ShardCoordinator can notify the RebalanceWorker when region is terminated. That can also be used instead of the extra watch of the `shuttingDownRegions`.

**Comment by chbatey** [comment]
This can cause a 60s outage for a shard for new ShardRegions as GetShardHome requests are deferred
