### ISSUE TITLE
MatchError in StreamOfStreams

### ISSUE THREAD

**Issue by fredfp** [akka/akka#29095]
I am getting the following error when working with actors and akka-http websocket clients.

I think that whatever is happening in my code is not the issue here, I rather believe a `MatchError` should never happen in akka-stream and is the issue here.

> scala.MatchError: OnError(akka.stream.impl.SubscriptionTimeoutException: Substream Source(SplitSource) has not been materialized in 5000 milliseconds) (of class akka.stream.impl.ActorSubscriberMessage$OnError)
> 	at akka.stream.impl.fusing.SubSource.failSubstream(StreamOfStreams.scala:779)
> 	at akka.stream.stage.GraphStageLogic$SubSourceOutlet.fail(GraphStage.scala:1531)
> 	at akka.stream.impl.fusing.Split$$anon$9$SubstreamHandler.onUpstreamFailure(StreamOfStreams.scala:631)
> 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
> 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:56)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:52)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnError.execute(ActorGraphInterpreter.scala:77)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
> 	at akka.actor.Actor.aroundReceive(Actor.scala:535)
> 	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
> 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:575)
> 	at akka.actor.ActorCell.invoke(ActorCell.scala:545)
> 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
> 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by raboof** [comment]
Thanks for the report, that indeed doesn't look right: it seems this source somehow didn't get materialized within 5 seconds, and on top of that its upstream failed (while the source still wasn't materialized).

I guess what should happen is that we pick one of the errors, and when the source is materialized fail it with the selected error.
