### ISSUE TITLE
Deploy implementation of Product interface is breaking Product iterator

### ISSUE THREAD

**Issue by klappvisor** [akka/akka#29104]
`Product` iterator fails on `Deploy` with the following error:

```
scala.MatchError: 0 (of class java.lang.Integer)
	at akka.actor.Deploy.productElement(Deployer.scala:122)
	at scala.Product$$anon$1.next(Product.scala:41)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
...
```

I see that Deploy is using 1 based index ([see here](https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-actor/src/main/scala/akka/actor/Deployer.scala#L122-L130
)) for its fields which is breaking contract and default implementation of `Product` iterator that expects 0 based index:

https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Product.scala#L21-L28

**Comment by johanandren** [comment]
Ouch. For reference it is handcoded to keep binary compatibility. Up for PR:ing a fix?

**Comment by klappvisor** [comment]
Absolutely, just `-1`-ing them should do?

**Comment by johanandren** [comment]
I think so 👍
