### ISSUE TITLE
Detect duplicate serializer identifiers

### ISSUE THREAD

**Issue by huntc** [akka/akka#29100]
When declaring a `SerializerWithStringManifest` class, I was caught out by thinking that I could use my class's `hashCode` function to provide an identifier:

```
    @Override
    public int identifier() {
        return MySerde.class.hashCode();
    }
```

This turned out pretty ugly and caused us to spend a lot of time trying to understand why our clustering wasn't working well.

I guess I should have known better than to use `hashCode` as it appears to change even between class loaders.

The Akka documentation doesn't really help though and suggests to choose any number so long as it isn't between 0 and 40 (which are reserved for Akka).

Generating a number in relation to a mnemonic representing an identifier should lead to less of a chance for collision. This is what Apple used to do (might still do?) when choosing 32 bit ids e.g. in C:

```
int identifier = 'msrd’;
```

In the spirit of the above, I'd like to suggest using [Base36](https://en.wikipedia.org/wiki/Base36) as a convention e.g.:

```
    @Override
    public int identifier() {
        return Integer.parseInt("MYSERD",36);
    }
```

...where "MYSERD" can be replaced with one's own identifier using the characters, 0-9 and A-Z and upto 6 characters in length (the max length for a 32 bit value).

It might also be useful to enforce such behaviour with a new method and deprecate the existing one.

**Comment by johanandren** [comment]
I'm not sure I see why that would be better than choosing a number and sticking with that?

**Comment by huntc** [comment]
> I'm not sure I see why that would be better than choosing a number and sticking with that?

Generating a number in relation to a mnemonic representing an identifier should lead to less of a chance for collision. This is what Apple used to do (might still do?) when choosing 32 bit ids e.g. in C:

```
int identifier = 'msrd’;
```

**Comment by patriknw** [comment]
but it means that there is a risk of collision even for the serializers defined within your own application.

What do we try to solve with this? Do you have so many serializers with different ids that it is difficult to define them all? Ids can be defined in config, to have them all in one place.

I don’t know if Akka checks for duplicate serializer ids from the configured serializers. That’s something we could do if it isn’t already.

**Comment by huntc** [comment]
> but it means that there is a risk of collision even for the serializers defined within your own application.

True. But I think this further minimises the risk. 
> What do we try to solve with this? Do you have so many serializers with different ids that it is difficult to define them all?

The implication of getting the id wrong caused our team a lot of confusion over a few days. In our case, it wasn’t collision, it was that each node yielded a different value given the use of `hashCode`.

Whether it is Base36, or the config suggestion below, stronger guidance on how this identifier can be determined might be helpful.

> Ids can be defined in config, to have them all in one place.

That could also be a good practice the docs may benefit from stating.

> I don’t know if Akka checks for duplicate serializer ids from the configured serializers. That’s something we could do if it isn’t already.

That might be a nice runtime check.

**Comment by patriknw** [comment]
Opened PR https://github.com/akka/akka/pull/29112 for the runtime check and improved documentation.

**Comment by johanandren** [comment]
#29112 merged but since this Issue is not 1:1 with that change I didn't close this.

**Comment by huntc** [comment]
I'm ok if you'd like to close this issue. Hopefully, the discussion was at least interesting. :-)

**Comment by patriknw** [comment]
Changed title to the main feature added: Detect duplicate serializer identifiers
Also clarified documentation.
Base32 can be used, but that is up to the application.

Thanks @huntc
