### ISSUE TITLE
Built in pattern for failable asks

### ISSUE THREAD

**Issue by jroper** [akka/akka#29133]
In Akka classic, you can send `Status.Failure` to a sender, and if that sender was an ask actor ref, this will cause the associated future to be redeemed with a failure.

This doesn't work in Akka typed because Akka typed is strongly typed, so if you have an `ActorRef[MyReply]`, you can't send a `Status.Failure` to it. Instead, if you want to be able to send failures (as is very common in akka persistence for validation), you have to represent failures in your reply type, so you might have:

```scala
sealed trait MyAbstractReply
case class MyReplySuccess(reply: MyReply) extends MyAbstractReply
case class MyReplyFailure(error: String) extends MyAbstractReply
```

Typically, after doing an ask, you will want `Future[MyAbstractReply]` to be flattened to `Future[MyReply]` with failures converted to failed futures, so every time you invoke your command, you need to have something like this:

```scala
myReplyFuture.transform {
  case Success(MyReplySuccess(reply)) => Success(reply)
  case Success(MyReplyFailure(error)) => Failure(new RuntimeException(error))
  case Failure(t) => Failure(t)
}
```

So that's just for one reply. If you have lots of commands (as typically you do with doing event sourcing), all with different reply types, you're going to either need to repeat all the above ADT and transformation boilerplate for each reply type, or much better, you're going to create an abstraction. Here's the abstraction I created for my project:

```scala
sealed trait Reply[+R <: JacksonSerializable] extends Cborable {}

object Reply {

  final case class Success[R <: JacksonSerializable](
      @JsonTypeInfo(
        use = JsonTypeInfo.Id.CLASS,
        property = "class",
        include = JsonTypeInfo.As.EXTERNAL_PROPERTY
      )
      value: R,
  ) extends Reply[R]

  final case class Failure(message: String) extends Reply[Nothing]
}
```

And then to support flattening futures of replies, I have this:

```scala
  implicit class FutureOfReply[R <: JacksonSerializable](future: Future[Reply[R]]) {
    def flattenReply(implicit ec: ExecutionContext): Future[R] = future.transform {
      case Success(Reply.Success(r)) => Success(r)
      case Success(Reply.Failure(message)) => Failure(new RuntimeException(message))
      case f: Failure[Nothing] @unchecked => f
    }
  }
```

So then I can just do:

```scala
val result: Future[MyReply] = actorRef
  .ask[Reply[MyReply]](replyTo => MyCommand(replyTo))
  .flattenReply
```

And I get an experience somewhat similar to Akka classic, but with strong typing.

I anticipate, every time I use Akka peristence typed, the first thing I do will always be to copy the above pattern into my project. And I can't imagine anyone else using Akka persistence in anger without implementing a similar abstraction. So I think a pattern like this should be built in to Akka. A few considerations:

* The above uses Jackson, but there's no reason it needs to do this, it could (and probably should) use a custom Akka serializer that uses Akka serialization to serialize the reply, and puts the bytes, serializer id and manifest in a protobuf, then serializes that. For me, since I was using Jackson everywhere anyway, it was far simpler to solve the question of how to carry type information for the wrapped reply by just adding a few annotations as shown above, rather than write a custom serializer and underlying protobuf types etc.
* Ideally, the failure type should be parameterizable too, so you can have richer errors than just strings (I've actually simplified the above from what I actually do, which also includes a gRPC status code). When flattening to a future, this could be implemented by requiring a `ToThrowable[T]` typeclass that can be used to convert the failure type to a `Throwable`. Don't know how this would be addressed in Java - the Java equivalent of typeclasses would either be to add an annotation to the type which listed a class that can be used to convert it to a `Throwable`, or to require that the type extends a `ToThrowableable` interface that has a `toThrowable` method. The latter would prevent simple types like `String` to be used for communicating errors, whereas Akka can have built in support for converting strings to exceptions if an annotation based approach was used.

**Comment by jroper** [comment]
`akka.actor.Status` might seem like an option, but isn't really because `akka.actor.Status.Success` is not typed, the message it wraps is `Any`, so doesn't make sense to use with Akka typed.

The failure type could just wrap `Throwable`. This again undermines typing somewhat, but is not as bad because the intent is to convert it to a `Throwable` anyway for the failed future. Users will just need to be careful to ensure they define a serializer for their exception type if it can't otherwise be deserialized by the built in Akka support.

**Comment by renatocaval** [comment]
Relates to https://github.com/akka/akka/issues/25781

**Comment by patriknw** [comment]
This has been discussed in https://github.com/akka/akka/issues/25781 and I have had the opinion that also errors (especially validation errors) should be part of the message protocol and not loose the type by turning into failed Future.

Seems like I should adjust my opinion since I know several people (not only @jroper) has expressed the need for this convenience. I'll give it a try.

**Comment by jroper** [comment]
Note that I agree errors are best expressed in the protocol, this proposal is about assisting that.

**Comment by johanandren** [comment]
What about having a single response message and instead expressing that it could be a failure by using `Try` (or some other validation type) so `Reply(result: Try[Value])`, then if you want to fail the future a `.map(_.result.get)` would "flatten" the failure up to the future without any required marker interfaces etc.

A tangent: for the `context.ask` and `messageAdapter` which I'd hope are more common than the `Future`-asks you can throw an exception from the adapter and it will be as though it was thrown inside the actor (fixed in 2.6.4 #28592)

**Comment by jroper** [comment]
> A tangent: for the context.ask and messageAdapter which I'd hope are more common than the Future-asks

Depends on the app, but for example, if you have an Akka gRPC interface that you're implementing, backed by a persistent actor, you'll be using future asks, same if you're calling from Akka HTTP, or if you're doing a mapAsync in Akka streams. I would expect that future asks are far more common, because future asks are the entry point from pretty much any ingest - eg Akka HTTP, Akka gRPC, Alpakka - into Akka.

Do we have built in serializers for `Try`? If so that could work - though does force you to represent failures in the protocol using exceptions.

**Comment by johanandren** [comment]
Good point about the "border of the system", you are right about that.

I don't think we have a built in serializer for Try, and when thinking a bit more about it, that leads to always needing to be able to serialize exceptions for validation error replies which has its own set of serialization problems. 

Deciding on a suitable datatype for representing that should probably be left as an application decision (Either, scalactic Or, whatever is available in Javaland, application specific), so if we try to make some form of abstraction it should cover any of those. I'll take a shot at that.
