### ISSUE TITLE
ClusterShardingLeaseSpec: cluster sharding with lease should not start until lease is acquired NPE

### ISSUE THREAD

**Issue by raboof** [akka/akka#29145]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7698/consoleFull

```
[info]   java.lang.NullPointerException:
[info]   at akka.cluster.sharding.ClusterShardingLeaseSpec.$anonfun$new$2(ClusterShardingLeaseSpec.scala:104)
[info]   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3319258651?check_suite_focus=true#step:5:32556

**Comment by pvlugter** [comment]
Took a moment to see what this one actually is. The line throwing the NPE is:

```scala
testLease.initialPromise.complete(Success(true))
```

but it's not the `testLease` that's null, it's the `initialPromise`. In the `TestLease` class:

```scala
TestLeaseExt(system).setTestLease(settings.leaseName, this)

val initialPromise = Promise[Boolean]()
```

so the test lease is publishing itself before the promise is initialised. Test failure reproducible with a small sleep between those.
