### ISSUE TITLE
Docs: show async-DNS enable in DNS Discovery docs

### ISSUE THREAD

**Issue by ennru** [akka/akka#29151]
The docs for DNS Discovery discuss details about the `async-dns` implementation, but do not tell the user to enable that by
```
akka.io.dns.resolver = "async-dns"
```
as the default is still `inet-address`
https://github.com/akka/akka/blob/24f2b2e6177704af81f8ae570c52d6395e58a3f1/akka-actor/src/main/resources/reference.conf#L1069

Refs #28931, https://github.com/akka/akka-http/issues/92#issuecomment-614491680

**Comment by ennru** [comment]
Current docs https://doc.akka.io/docs/akka/current/discovery/index.html#discovery-method-dns

**Comment by chbatey** [comment]
I don't think we should tell users to set akka.io.dns.resolver as it changes all dns look ups. DNS discovery uses its own resolver if the system one isn't set to async-dns

**Comment by ennru** [comment]
Ok, @chbatey showed me that Akka DNS discovery always selects the async DNS. 

https://github.com/akka/akka/blob/24f2b2e6177704af81f8ae570c52d6395e58a3f1/akka-discovery/src/main/scala/akka/discovery/dns/DnsServiceDiscovery.scala#L79-L85
