### ISSUE TITLE
Allow arbitrary random number generators

### ISSUE THREAD

**Issue by raboof** [akka/akka#29188]
Currently we support the default SecureRandom random generator and SHA1PRNG. We could also allow any generator accepted by `SecureRandom.getInstance`.

**Comment by raboof** [comment]
See also https://github.com/akka/akka/pull/29152#discussion_r434994878

**Comment by itssunilsid** [comment]
Can i work on this?

**Comment by raboof** [comment]
Sure, go for it! Let us know if you run into any trouble.

**Comment by itssunilsid** [comment]
Sorry for getting back late.

`SecureRandomFactory` has a method `createSecureRandom` which returns default `SecureRandom` object on passing a  invalid algorithm. Since we need arbitrary RNG and if user gives a typo in configuration, `SecureRandom.getInstance(typoed-string)` fails with an exception. How to deal with an exception in this case? Should I Log it and return the default SecureRandom?

**Comment by raboof** [comment]
> How to deal with an exception in this case? Should I Log it and return the default SecureRandom?

i think for the other crypto initialization code we just throw/crash in case of such problems, so it might make sense to follow that approach here as well.

**Comment by itssunilsid** [comment]
https://github.com/akka/akka/blob/c287fff034b598c06ef87bda78dc9851a51da94f/akka-remote/src/main/scala/akka/remote/artery/tcp/ssl/RotatingKeysSSLEngineProvider.scala#L107

just like this?

**Comment by ignasi35** [comment]
> just like this but instead throw `NoSuchAlgorithmException`?

That would work, yeah.

**Comment by itssunilsid** [comment]
Should I be removing any one of the SecureRandomFactorySHA1Spec, SecureRandomFactoryNativePRNGSpec? Becuase both of them tests the same just using different alogrithm.

**Comment by raboof** [comment]
> Shall I remove one of the `SecureRandomFactorySHA1Spec`, `SecureRandomFactoryNativePRNGSpec`? Becuase both of them tests the same just using different alogrithm.

I think it's OK to keep them, that way we're reminded that whatever refactorings we might do in the future we don't want to break those particular cases.

**Comment by ennru** [comment]
Implemented with #29246
