### ISSUE TITLE
release dry run publishes artifacts

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29199]
Noticed while releasing 2.6.6, running a dry run with the release script actually pushed the signed artifacts to sonatype. Probably not what we want. May not be important given that we want to move to tag-to-release, but perhaps good to note.

**Comment by patriknw** [comment]
yes, seems important to fix. I probably didn't notice in 2.6.5 because I skipped dry run.

**Comment by raboof** [comment]
This was broken post-2.6.5, in #28815.

The release procedure has become a lot simpler, and the different steps (tagging, building/uploading jars, building/uploading docs, pushing the tag) can more easily be retried/fixed.

I wonder if having a dry-run option at all is still useful/needed?

**Comment by johanandren** [comment]
RELEASING.md still talks about the dry run, I'll remove that
