### ISSUE TITLE
Failed: LeveldbJournalNativePerfSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29196]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7730/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/

```
timeout (10 seconds) during expectMsg while waiting for 100
	at scala.Predef$.assert(Predef.scala:223)
	at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)
	at akka.testkit.TestKitBase.expectMsg(TestKit.scala:445)
	at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:445)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:969)
	at akka.persistence.journal.JournalPerfSpec.feedAndExpectLast(JournalPerfSpec.scala:137)
	at akka.persistence.journal.JournalPerfSpec.$anonfun$new$7(JournalPerfSpec.scala:186)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7811/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/

**Comment by johanandren** [comment]
Looks as though the persistent actor used in that benchmark ended up in some really weird state because (at least I think) it got sent the `PersistentRepr`:

```
[INFO] [akkaDeadLetter][06/07/2020 05:19:58.455] [JournalSpec-akka.actor.default-dispatcher-4] [akka://JournalSpec/user/$a] Message [akka.persistence.PersistentImpl] to Actor[akka://JournalSpec/user/$a#-16635130] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by jrudolph** [comment]
jenkins.akka.io:8498/job/akka-nightly-jdk8/8000/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__recovering_100_events

and

jenkins.akka.io:8498/job/akka-nightly-jdk8/8000/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8084/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/

**Comment by johanandren** [comment]
Same as I noted earlier with the latest failure:

```
[akka://JournalSpec/user/$b] Message [akka.persistence.PersistentImpl] to Actor[akka://JournalSpec/user/$b#-2075457247] was unhandled. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by johanandren** [comment]
Looks like that was a herring, the reason for the unhnalded is that the `JournalSpec` always writes 5 string events to the journal for the test-unique persistence id before each test that the BenchActor then does not handle during its recovery (worth fixing but not causing the failure).

**Comment by johanandren** [comment]
The jenkins disk is really insanely slow, looking at the numbers, the slowest persistAsync there is ~16ms per written event. Curiously though, if I try to simulate such slow writes in the leveldb journal I still don't get the test to timeout.

Since this turned out to be only about the Leveldb journal (which is not a prod journal) and not a general issue like I feared I'll drop this issue.

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8168/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8273/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/

and

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8273/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__recovering_100_events/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8462/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/

I'd suggest that we remove this test, and spend our efforts on real journals and inmem testing journals.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8714/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/
