### ISSUE TITLE
ClusterSingletonManager unhandled event HandOverDone in state Oldest

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#29215]

**Comment by chbatey** [comment]
@nvollmar could you share some logs for this, from the new oldest and the previous oldest?

**Comment by nvollmar** [comment]
@chbatey We're already rolled out of those logs. I'll keep an eye out if it happens again.

**Comment by ollyw** [comment]
I am seeing related issues when running some multi-jvm tests on a project with Akka 2.5.29:
```
[WARN]  ClusterSingletonManager - unhandled event HandOverToMe in state HandingOver
[WARN]  ClusterSingletonManager - unhandled event HandOverToMe in state HandingOver
.... 9 more repeats
[WARN]  ClusterSingletonManager - unhandled event OldestChanged(None) in state HandingOver
[WARN]  ClusterSingletonManager - unhandled event OldestChanged(None) in state HandingOver
... 9 more repeats
```
It does look like the ClusterSingletonManager state machine in the master branch won't handle these events in the Handle these events. Not sure if it is a bug though, or whether thee warn should be there
