### ISSUE TITLE
Failed: akka.remote.artery.tcp.ssl.RotatingProviderWithStaticKeysSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#29221]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/20087/testReport/akka.remote.artery.tcp.ssl/RotatingProviderWithStaticKeysSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

```
sbt.ForkMain$ForkError: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.$anonfun$afterTermination$1(RotatingKeysSSLEngineProviderSpec.scala:267)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.afterTermination(RotatingKeysSSLEngineProviderSpec.scala:265)
```

**Comment by jrudolph** [comment]
Occured in #29213, might have a chance of actually being caused by that.

**Comment by jrudolph** [comment]
No, seems like a genuine failure, cannot reproduce it locally.

**Comment by ignasi35** [comment]
Again in https://jenkins.akka.io:8498/job/akka-nightly-2.13/564/testReport/junit/akka.remote.artery.tcp.ssl/

**Comment by ignasi35** [comment]
Extra info: it seems the timeout happens terminating the [`systemB-rebuild`](https://github.com/akka/akka/blob/c287fff034b598c06ef87bda78dc9851a51da94f/akka-remote/src/test/scala/akka/remote/artery/tcp/ssl/RotatingKeysSSLEngineProviderSpec.scala#L45-L66):

```
[WARN] [06/14/2020 20:57:55.953] [pool-1-thread-1-ScalaTest-running-RotatingProviderWithStaticKeysSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
[info] - must keep existing connections alive (no new SSLEngine's created after cache expiration) (2 seconds, 671 milliseconds)
[info] akka.remote.artery.tcp.ssl.RotatingProviderWithStaticKeysSpec *** ABORTED *** (15 seconds, 316 milliseconds)
[info]   java.util.concurrent.TimeoutException: Future timed out after [10 seconds]

...

[info]   at java.lang.Thread.run(Thread.java:748)
[WARN] [06/14/2020 20:58:08.639] [systemB-rebuild-akka.actor.internal-dispatcher-29] [CoordinatedShutdown(akka://systemB-rebuild)] Coordinated shutdown phase [actor-system-terminate] timed out after 10000 milliseconds
```

**Comment by ignasi35** [comment]
That's from https://github.com/sbt/sbt/blob/9b931c4bf80bd7078701abc9eb120007fb5d31c9/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala#L132

**Comment by jrudolph** [comment]
A sibling test failed here with similar stacktrace: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/20142/

**Comment by ignasi35** [comment]
Again in : https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7759/display/redirect

**Comment by ignasi35** [comment]
And again in https://jenkins.akka.io:8498/job/akka-nightly-jdk11/636/

**Comment by raboof** [comment]
(not entirely confident that we found the real cause, but let's close this until it pops up again :crossed_fingers: )
