### ISSUE TITLE
JsonFraming throw error on completion with fragment

### ISSUE THREAD

**Issue by dave-handy** [akka/akka#29228]
I would like to add a new parameter to `akka.stream.scaladsl.JsonFraming.objectScanner(maximumObjectLength: Int, errorOnFragment: Boolean = false)`. Setting the new parameter to true would simply check `buffer.insideObject` before calling `completeStage()` on line 72, and throw an exception if it is inside an object.

I am happy to contribute a PR for this, I just want some sign off that this is a good approach. I can't think of a way to do this at all, much less efficiently, without access to the private API internals.

**Comment by johanandren** [comment]
Shouldn't it rather _always_ fail if it completes with a fragment in the buffer? You could always recover that failure downstream if you want to achieve the current behavior. I can't think about a scenario where you'd want it though?

**Comment by dave-handy** [comment]
I'm game for that, I guess I just assumed that the API should maintain the current behavior and the new behavior would be opt-in. There is some cost of throwing that exception too.

**Comment by johanandren** [comment]
If that is an issue we can always skip the stack trace on the exception to make it more like a regular object alloc, but I doubt completing with incomplete data is the hot path in may applications?

A PR sounds good if you feel up to it! 👍

**Comment by dave-handy** [comment]
Good point. I'll try to have something up in the next few days. Thanks!
