### ISSUE TITLE
Deal with out of order events from other replicas

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29259]
In multi dc we validated that the replicated event was at least greater than the last seen for that dc. Shouldn't it always be the next one?

What cases can we see out or order events, if any?

**Comment by patriknw** [comment]
Might be for the speculative replication, which may loose messages?

**Comment by chbatey** [comment]
👍 in that case we should drop the event

**Comment by johanandren** [comment]
I think we got this covered in #29289 if an old speculative event comes in and #29265 if an old event comes from the query
