### ISSUE TITLE
Support for mocking/verifying EntityRefs

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#29267]
Currently the only way I found to mock and validate `EntityRef`s is the following hack (see the package):

```
package akka.actor.testkit.typed.scaladsl

import akka.actor.typed.{ ActorRef, Scheduler }
import akka.actor.typed.internal.InternalRecipientRef
import akka.actor.ActorRefProvider
import akka.cluster.sharding.typed.scaladsl.EntityRef
import akka.util.Timeout
import scala.concurrent.Future

final class TestProbeEntityRef[A](testProbe: TestProbe[A])(implicit scheduler: Scheduler)
    extends EntityRef[A]
    with InternalRecipientRef[A] {

  override def tell(msg: A): Unit =
    testProbe.ref.tell(msg)

  override def ask[Res](f: ActorRef[Res] => A)(implicit timeout: Timeout): Future[Res] = {
    import akka.actor.typed.scaladsl.AskPattern.Askable
    testProbe.ref.ask(f)
  }

  override def provider: ActorRefProvider =
    throw new UnsupportedOperationException("Hoping we do not need the provider here ... ;-)")

  override def isTerminated: Boolean =
    false
}
```

I suggest to either not require the self type `InternalRecipientRef` for `EntityRef` which seems to be not used at all in `EntityRef` itself. Or provide something like `TestProbe` for `EntityRef`s.

**Comment by chbatey** [comment]
+1 to being able to stub out an entity ref / test against an entity ref

**Comment by patriknw** [comment]
Sounds good to add that testing facility.

So the probe should receive the original message, not the ShardingEnvelope?

We don't have a testkit for Sharding and this is too small to motivate creating that. I think we could just add it in ordinary `akka-cluster-sharding-typed` with a clear naming such as `TestEntityRef.apply(...): EntityRef`. It would delegate to an ActorRef, not a TestProbe.

I think it's rather common, for example in a gRPC server implementation, to always "lookup" the EntityRef for each request using `ClusterSharding.entityRefFor`. For such testing you would have to create a test stub of `ClusterSharding` but I think that is already possible.
