### ISSUE TITLE
BehaviorTestKit fails to process concurrent messages since akka 2.6.6

### ISSUE THREAD

**Issue by kpritam** [akka/akka#29277]
Following test used to work just fine prior to akka 2.6.6 but after migrating started failing.

```scala
test("BehaviorTestKit should process two messages concurrently") {
    import typedSystem.executionContext

    case class Echo(msg: String, replyTo: ActorRef[String])

    val echoBeh = Behaviors.receiveMessage[Echo] { msg =>
      println(s"Rec: $msg")
      msg.replyTo ! msg.msg
      Behaviors.same
    }

    val testkit = BehaviorTestKit(echoBeh)
    val replyTo = TestProbe[String]

    Future(testkit.run(Echo(s"Hello 1", replyTo.ref)))
    Future(testkit.run(Echo(s"Hello 2", replyTo.ref)))

    replyTo.expectMessageType[String]
    replyTo.expectMessageType[String]
  }
```

**Comment by johanandren** [comment]
Hi @kpritam, the `BehaviorTestKit` was never meant to handle concurrent messages or any other form of concurrency, it is basically an in thread, synchronous engine to execute behavior and verify what happens. If that worked before you can consider that accidental.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for almost 3 years. 

Should this issue be closed?

**Comment by patriknw** [comment]
yes, looks like invalid usage from threads
