### ISSUE TITLE
Snapshot support for active active 

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29286]
We need to store the metadata

**Comment by johanandren** [comment]
Here it may be more suitable with a wrapper including the metadata, than it is for the events given that the snapshots are never consumed by anything else but replay?

**Comment by patriknw** [comment]
> snapshots are never consumed by anything else but replay

The main reason I don't want to wrap is to allow transparency in the database, so that people can inspect **their** data with ordinary db tool chain.
