### ISSUE TITLE
failed: RotatingKeysSSLEngineProviderSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29298]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7777

```
[info] akka.remote.artery.tcp.ssl.RotatingProviderWithStaticKeysSpec *** ABORTED *** (13 seconds, 508 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [8 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.result(package.scala:146)
[info]   at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.$anonfun$beforeTermination$1(RotatingKeysSSLEngineProviderSpec.scala:275)
[info]   at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.$anonfun$beforeTermination$1$adapted(RotatingKeysSSLEngineProviderSpec.scala:272)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.beforeTermination(RotatingKeysSSLEngineProviderSpec.scala:272)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/20233/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/576/consoleFull

**Comment by ignasi35** [comment]
@raboof I've assigned this to you since it's (very likely) a duplicate of #29331 (different test failure but same cause and code)

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4156/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/606/testReport/junit/akka.remote.artery.tcp.ssl/RotatingProviderWithStaticKeysSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7883/testReport/junit/akka.remote.artery.tcp.ssl/RotatingProviderWithStaticKeysSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8023/

**Comment by patriknw** [comment]
Closing as old
