### ISSUE TITLE
ChildFailed not sent in Akka Typed?

### ISSUE THREAD

**Issue by bjchambers** [akka/akka#29293]
Based on https://doc.akka.io/docs/akka/current/typed/fault-tolerance.html, it seems like in cases where a child fails (either within a message handler or during setup) a parent watching it should receive a `ChildFailed` signal, instead of `Terminated`.

I have noticed that I'm not observing this behavior, and when I wrote a quick test to check it seems to confirm it isn't performing as expected:

```
object AkkaTest {
  final case class ParentReceivedSignal(signal: Signal)

  sealed trait ParentProtocol
  final case class SpawnChild(replyTo: ActorRef[ActorRef[ChildProtocol]]) extends ParentProtocol
  final case class SpawnFailingChild(throwable: Throwable) extends ParentProtocol

  sealed trait ChildProtocol
  final case object CompleteChild extends ChildProtocol

  final case class FailChild(throwable: Throwable) extends ChildProtocol
}

class AkkaTest extends ScalaTestWithActorTestKit with AnyFunSpecLike {

  import AkkaTest._

  def parentBehavior(signalRef: ActorRef[ParentReceivedSignal]): Behavior[ParentProtocol] =
    Behaviors.setup { context =>
      Behaviors
        .receiveMessage[ParentProtocol] {
          case SpawnChild(replyTo) =>
            val child = spawn(childBehavior())
            context.watch(child)
            replyTo ! child
            Behaviors.same
          case SpawnFailingChild(error) =>
            val child = spawn(failingChildBehavior(error))
            context.watch(child)
            Behaviors.same
        }
        .receiveSignal {
          case (_, signal) =>
            signalRef ! ParentReceivedSignal(signal)
            Behaviors.same
        }
    }

  def childBehavior(): Behavior[ChildProtocol] = Behaviors.receiveMessage {
    case CompleteChild =>
      Behaviors.stopped
    case FailChild(error) =>
      throw error
  }

  def failingChildBehavior(error: Throwable): Behavior[ChildProtocol] = Behaviors.setup { _ =>
    throw error
  }

  describe("Signals received by parent") {
    // This fails, because it receives Terminated instead of ChildFailed
    it("receives ChildFailed when the child fails after setup") {
      val signalProbe = TestProbe[ParentReceivedSignal]
      val parent = spawn(parentBehavior(signalProbe.ref))

      val spawnProbe = TestProbe[ActorRef[ChildProtocol]]
      parent ! SpawnChild(spawnProbe.ref)
      val child = spawnProbe.expectMessageType[ActorRef[ChildProtocol]]

      val exception = new IllegalArgumentException("Expected exception")
      child ! FailChild(exception)
      signalProbe.expectMessage(ParentReceivedSignal(ChildFailed(child, exception)))
    }

    // This passes, because it receives Terminated
    it("receives ChildFailed when the child fails during setup") {
      val signalProbe = TestProbe[ParentReceivedSignal]
      val parent = spawn(parentBehavior(signalProbe.ref))

      val exception = new IllegalArgumentException("Expected exception")
      parent ! SpawnFailingChild(exception)
      val message = signalProbe.expectMessageType[ParentReceivedSignal]
      message.signal match {
        case ChildFailed(_, actualException) => assert(actualException == exception)
        case Terminated(_)                   => fail("Received terminated instead of ChildFailed")
      }
    }

    // This passes, because it receives Terminated
    it("receives Terminated when the child shutsdown normally") {
      val signalProbe = TestProbe[ParentReceivedSignal]
      val parent = spawn(parentBehavior(signalProbe.ref))

      val spawnProbe = TestProbe[ActorRef[ChildProtocol]]
      parent ! SpawnChild(spawnProbe.ref)
      val child = spawnProbe.expectMessageType[ActorRef[ChildProtocol]]

      child ! CompleteChild
      val message = signalProbe.expectMessage(ParentReceivedSignal(Terminated(child)))
      assert(!message.signal.isInstanceOf[ChildFailed])
    }
  }
}
```

**Comment by johanandren** [comment]
That's curious, we do have test coverage for child failing on message here https://github.com/akka/akka/blob/master/akka-actor-typed-tests/src/test/scala/akka/actor/typed/WatchSpec.scala#L152 but nothing for failure during setup. 

Would be good if you could see if you can spot how your test is different from the existing one wrt failure when processing a message.

**Comment by bjchambers** [comment]
Aha. I think I figured out the difference, but I'm a bit confused as to whether or not it should actually be causing this difference.

In the `WatchSpec.scala` test, the parent creates the child using `context.spawn`. In the example test I posted, it is created using the TestKit `spawn` (so I guess it's actually a sibling).

So maybe it's a documentation question -- if you `watch` an actor created elsewhere in the hierarchy, do you *only* receive `Terminated`, whereas if you `watch` an actual child actor, you may receive the added `ChildFailed` refinement?

**Comment by johanandren** [comment]
Yes, a test case is not an actor so the testkit spawn could not possibly spawn a child but your actors will be siblings, that explains it. 

I would have thought that it is sufficiently clear in the docs that only the parent will get a `ChildFailed`:

https://doc.akka.io/docs/akka/current/typed/fault-tolerance.html#bubble-failures-up-through-the-hierarchy
> For a parent to be notified when a child is terminated it has to watch the child. If the child was stopped because of a failure the ChildFailed signal will be received which will contain the cause. 

But if you have some idea to make it more clear that is only about parent-child please PR!

Would be good if we also added test coverage for `ChildFailed` in the case the child fails during setup.

**Comment by bjchambers** [comment]
Knowing the problem and reading the docs, I think you're right -- it is pretty clear. I guess I was hoping there was an easier way to handle it. I worry that there is a lot of room for error in having to manually bubble things up, and it seems to defeat some of the benefits of having the hierarchy of actors at all.

I have some lingering concerns that these nuances may make it easy to fail to even find out about failures, somewhat defeating the benefits of actors for handling errors. For instance, if you didn't both `context.spawn` and `context.watch` the actor, you'll never hear about the termination, which means you won't be able to take any actions. If you `context.watch` an actor, but didn't spawn it, you'll receive a `Terminated` message, which may make you think it succeeded, when in fact it failed but didn't tell you.

I wonder if the fault-tolerance page could be extended to include some guidelines for how to actually use these in a way that ensures there aren't any accidentally dropped problems? I'm thinking:

1. If you `context.spawn` an actor, you should `context.watch` it. This ensures that you'll be notified of terminations.
2. If you do that, then every actor in the hierarchy should receive a `ChildFailed` message with either the root cause, or a DeathPact exception.
3. If you need the cause to bubble up, then every actor on the path between the handler and the point of failure needs to have a signal handler that re-throws the cause of the `ChildFailed` (note that the actor in the signal at the end is not the point-of-failure, but the direct descendent on the path to the point-of-failure).

**Comment by patriknw** [comment]
I would expect bubble up (escalate) strategy to be used rather rarely. From what you say it sounds like you use it everywhere? Instead, I would expect the supervision with strategies such as restart and restartWithBackoff to be much more common.

**Comment by bjchambers** [comment]
In many cases we spawn actors for specific workflows or parts of a workflow. In these cases we would like to bubble up failures to the root of the workflow to reply to the initial request with a failure. 

We've found this pattern (using several simple actors) easier to develop and test than having a single actor for a complex workflow.

In other places actors are used more like a service, handling multiple requests. In these cases we do use supervision to restart the actors.
