### ISSUE TITLE
notification of replicated event

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29314]
I didn't see any ticket related to the notification table.

**Comment by johanandren** [comment]
We thought we can do without it but perhaps we missed something.

**Comment by patriknw** [comment]
Relying on the direct replication messages only?

It would indeed be nice to not have that "dependency". I'm not sure if it's needed for something else. I think it's used by the hot standby mechanism https://github.com/akka/akka/issues/29319, but maybe the direct replication messages are enough for that also?

https://doc.akka.io/docs/akka-enhancements/current/persistence-dc/cassandra.html#notifications

**Comment by chbatey** [comment]
We discussed this quite a bit and thought we could get away with just an infrequent poll + the direct replication. 
Let's put this in the backlog

**Comment by patriknw** [comment]
I'm fine with closing if we think it's not needed.
