### ISSUE TITLE
Hot-standby keep alive for sharding

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29319]
https://doc.akka.io/docs/akka-enhancements/current/persistence-dc/index.html#hot-standby

**Comment by johanandren** [comment]
I think this will either become documentation, or if we introduce an API routing across N sharding proxies we can support it there (#29283)

**Comment by patriknw** [comment]
It's difficult for user to implement, because it's based on reading from the notification table (I think).
Related to #29314

**Comment by johanandren** [comment]
For hot standby isn't there either so that you know up front what ids you have or if they are appearing over time you'd start one in each replica at the first event? (Potentially together with remember-entities)

**Comment by patriknw** [comment]
You "almost never" know the ids up front. I think we wanted it to work with sharding passivation, and then wake up on the other side when something happened.

Maybe the direct replication messages are enough for this?

**Comment by johanandren** [comment]
Yeah, I think having each event persisted in other replicas lead to a message passed through sharding should do the trick.

**Comment by chbatey** [comment]
>Yeah, I think having each event persisted in other replicas lead to a message passed through sharding should do the trick.

👍

**Comment by chbatey** [comment]
That will keep them alive. I think we need some documentation for the pattern of failing over.

**Comment by johanandren** [comment]
@chbatey also related is #29283

**Comment by patriknw** [comment]
Ok, seems we don't have to implement anything here, but we can keep the ticket for documentation purposes.

Note that when I say hot standby here I don't necessarily mean strictly that only one is active and others are passive until the active fails. It can also be that there is no traffic for an entity in a DC for a while, and when it starts up it can be bad to have to read all the replicated events in one go, to catch up.
