### ISSUE TITLE
add verbose logging option for distributed data

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#29324]
I've seen some ask timeout using the actor ask pattern with replicators.

It would help debug a lot if we can enable (in the config file) verbose logging from the ddataReplicator actors.

**Comment by chbatey** [comment]
Assuming you're using logback or similar you can do this with <logger name="akka.cluster.ddata" level="DEBUG"/> in your logback.xml

**Comment by Zhen-hao** [comment]
thanks for the tip! @chbatey 

However, it doesn't seem to work after adding that line to my `logback.xml`. 

```
[info] [2020-06-29 13:46:04,234] [DEBUG] [com.nt.TestApp] [] [my-app-akka.actor.default-dispatcher-21] - GetFromCache command received {}
[info] [2020-06-29 13:46:04,240] [DEBUG] [com.nt.TestApp] [] [my-app-akka.actor.default-dispatcher-21] - NotFound response received {}
```
I don't see any logs between receiving a get command (first logline, which will cause my actor to send a `Get` request to the replicator) and receiving a `GetResponse` from the replicator (second logline). 
I want to see everything the replicator does internally. Most importantly, I need to know if it is up or down in the case of ask timeout. 

am I missing anything here?

**Comment by chbatey** [comment]
Have you set akka.loglevel to DEBUG?

**Comment by Zhen-hao** [comment]
@chbatey 
that works!
now I can see this log in between
```
[info] [2020-06-30 10:05:46,572] [DEBUG] [akka.cluster.ddata.Replicator] [] [nt-ui-akka.actor.default-dispatcher-17] - Received Get for key [cache-device31]. {akkaAddress=akka://nt-ui@127.0.0.1:2551, sourceThread=nt-ui-akka.actor.internal-dispatcher-16, akkaSource=akka://nt-ui@127.0.0.1:2551/system/ddataReplicator, sourceActorSystem=nt-ui, akkaTimestamp=08:05:46.572UTC}
```

Let me close this one.
but it would be great if we can select which parts of Akka have debug level logging in the config.

**Comment by patriknw** [comment]
> but it would be great if we can select which parts of Akka have debug level logging in the config.

That is done via your logback.xml

**Comment by chbatey** [comment]
Thanks for confirming @Zhen-hao 

We're trying to move towards using loggers that make sense for turning parts on/off rather than flags in config.

**Comment by Zhen-hao** [comment]
> > but it would be great if we can select which parts of Akka have debug level logging in the config.
> 
> That is done via your logback.xml

my concern was that if I only want to see one part of the Akka logs I would have to add a line in `logback.xml` to turn off each other part of Akka internals that I don't want to see the logs of.

**Comment by patriknw** [comment]
you can have the root logger at INFO and then enable DEBUG for one specific logger name, such as `akka.cluster.ddata`

**Comment by Zhen-hao** [comment]
@patriknw thanks! but I also want to see Debug logs from my own code. So setting root to INFO would mean I need to add lines for my code. 
This is not a big deal at all. I can live with it. My questions are more for my own understanding.
Akka is among the best documented open source libraries that I know of. So I'm already very happy :)
