### ISSUE TITLE
Scala LogCapturing doesn't clear after successful tests

### ISSUE THREAD

**Issue by bjchambers** [akka/akka#29339]
The Java version of LogCapturing calls `clear` in a `finally` block, so it always clear after each test:

https://github.com/akka/akka/blob/master/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/javadsl/LogCapturing.scala#L63

The scala version, only calls clear after *all* tests have been run:

https://github.com/akka/akka/blob/master/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/LogCapturing.scala#L48

This leads to the following problem -- if a test suite in Scala has 5 tests, and the 5th one fails, logs from *all 5 tests* will be shown.

Proposed solution (I can send a PR) would be to call `capturingAppender.clear()` at the end of `withFixture`.

**Comment by chbatey** [comment]
Thanks for reporting. A PR would be great
