### ISSUE TITLE
DeathWatchNotificationSpec: receive Terminated after ordinary messages when system is shutdown

### ISSUE THREAD

**Issue by raboof** [akka/akka#29349]
https://jenkins.akka.io:8498/job/akka-multi-node/4129/consoleFull

Seems related to #28695/#28940?

```
java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg: Terminated Actor[akka://other@localhost:43915/user/sender2#-1681320542]
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:477)
[info]   at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:474)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:969)
[info]   at akka.testkit.TestKitBase.expectTerminated(TestKit.scala:492)
[info]   at akka.testkit.TestKitBase.expectTerminated$(TestKit.scala:491)
[info]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:969)
[info]   at akka.remote.artery.DeathWatchNotificationSpec.$anonfun$new$2(DeathWatchNotificationSpec.scala:107)
```

**Comment by patriknw** [comment]
Yup, that is related. Note that it's the remote test without cluster. Could be some race between failure detector/quarantine/shutdown and the flushing. If not obvious what is wrong we should revert or disable the flushing for rermote without cluster (and then this test must be disabled).

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7807/testReport/junit/akka.remote.artery/DeathWatchNotificationSpec/receive_Terminated_after_ordinary_messages_when_system_is_shutdown/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7815/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7820/

**Comment by chbatey** [comment]
Looked into this.

Note that there are two flushes going on here. The shutdown flush and the watching flush.

What happens is the shutdown flush sends an ActorSystemTerminating / receives a ActorSystemTerminatingAck to flush all of the channels on shutdown. The flush part replies on the messages being ordered, but with the flush on deathwatch the ActorSystemTerminating overtakes the deathwatches as they are waiting for the watching flush to finish.

Once the shutdown flush is complete it calls internalShutdown on the transport which then quarantines the other side as it is shutdown with 1-3 of the death watch notifications in the system queue.

Some options:
1. Do as P suggests and disable/revert death watch flush for remoting, so you only get the guarantee when using cluster
2. Extend the shutdown flush to take into account on going watch flushes
3. Trigger terminated somehow on the other side based on the ActorSystemTerminated message?

I think 2/3 will add quite a bit of complexity given how flushes are currently implemented. As we don't recommend using remoting directly i suggest we do 1.
