### ISSUE TITLE
Incorrect write consistency timeout used for DData Shard coordinator

### ISSUE THREAD

**Issue by mgutmanis** [akka/akka#29344]
Once upgraded Akka from 2.6.4 to 2.6.5 it was noticed that supposedly `updating-state-timeout` has changed. It was noticed that `akka.cluster.sharding.DDataShardCoordinator#stateWriteConsistency` is using `waiting-for-state-timeout` property and not `updating-state-timeout` which is hinted by error message, documentation describes it as timeout for write consistency.

Either documentation and write timeout error message is out of sync or wrong property is used.

**Comment by johanandren** [comment]
Thanks for letting us know, that sounds wrong.

**Comment by patriknw** [comment]
one log statement is using wrong order of the parameters
```
    log.debug(
      "Starting up DDataRememberEntitiesStore, write timeout: [{}], read timeout: [{}], majority min cap: [{}]",
      settings.tuningParameters.waitingForStateTimeout.pretty,
      settings.tuningParameters.updatingStateTimeout.pretty,
      majorityMinCap)
```

**Comment by patriknw** [comment]
and I guess the stateWriteConsistency should use the updatingStateTimeout
```
  private val stateWriteConsistency = settings.tuningParameters.coordinatorStateWriteMajorityPlus match {
    case Int.MaxValue => WriteAll(settings.tuningParameters.waitingForStateTimeout)
    case additional   => WriteMajorityPlus(settings.tuningParameters.waitingForStateTimeout, majorityMinCap, additional)
  }
```
