### ISSUE TITLE
CoordinatedShutdown.addActorTerminationTask doesn't work due to ask

### ISSUE THREAD

**Issue by bjchambers** [akka/akka#29355]
When using CoordinatedShutdown.addActorTerminationTask, I'm noticing the following errors during shutdown:

```
[WARN] [07/06/2020 20:30:28.496] [CoordinatedShutdown(akka://MyTest)] Task [shutdown-my-actor] in phase [before-service-unbind] threw an exception before its future could be constructed: cannot create children while terminating or terminated
```

My task doesn't spawn any actors (it just sends a message), so this has me a bit surprised. Looking at the implementation of `addActorTerminationTask`, I notice that it uses `ask`, which I believe spawns an actor. As a result, it seems my termination tasks aren't running.

Looking at the tests, I don't think it's *actually* initiating a shutdown when testing `addActorTerminationTask`, so that may explain why tests aren't seeing the "cannot create children while terminating". I'm trying to add such a test to confirm, but having some trouble getting it to run at all (will update if I can get it working).

**Comment by johanandren** [comment]
The observation is correct, that won't work, thanks for reporting @bjchambers
