### ISSUE TITLE
Relax version check to support forward-one migrations

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#29422]
When using `JacksonMigration`'s for schema evolution, the `JacksonDeserializer` is strict and fails when the received byte string has a manifest with a version greater than the version that process supports. The code:

https://github.com/akka/akka/blob/1e9e98472761be93302302e3881a7e7584addc68/akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonSerializer.scala#L322-L325

When running a rolling deployment of a feature that includes schema evolution, new nodes will produce data with a version N+1 (where N is the version supported by older nodes). This causes a service degradation that's generally acceptable. 

There are scenarios, though, where the migration is trivial or where the service degradation is not acceptable in which cases a forward-one compatible migration strategy should be useable. The code above forbids forward-one migration strategies since old nodes will not accept data with a manifest on version N+1.

**Comment by ignasi35** [comment]
There are three versions in volved: the `fromVersion` (or version in the manifest for `ByteString` we're deserializing), the `transformer.currentVersion` (or version we're adding to the manifest when serializing new content) and the _new_ `acceptedFromVersion` (which could be `transformer.currentVersion+1` or  `transformer.currentVersion` depending on user's choice to support or not forward-one migrations).

**Comment by patriknw** [comment]
It's a good point that we should support rolling updates better in the serialization migration.

For rolling updates I think it should be solved with two rolling update steps. First rolling out the new deserialization code, but still serialize with old format. Then roll out the new serialization code. In the second step we would still need something like what is described above to accept version + 1.
