### ISSUE TITLE
Corrupt jars on publishLocal

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29433]
Last week when I did a publishLocal I consistently (I think at least) ended up with a corrupt jarfile in my local repo.

Trying to use it gave me:

```
jar:file:/Users/johan/.ivy2/local/com.typesafe.akka/akka-persistence_2.12/2.6.8+28-ac03c1fc/jars/akka-persistence_2.12.jar!/reference.conf: read error: ZipFile invalid LOC header (bad signature)
```

On @raboof s recommendation I then disabled the reproducible builds plugin which seemed to fix the issue.

**Comment by raboof** [comment]
I don't have commit ac03c1fc, but I tried:
* `sbt publishLocal` on Akka 2.6.8+36-0d51b6e7
* `sbt new akka/akka-quickstart-scala.g8`
* set the scala version to 2.12.12, akka version to 2.6.8+36-0d51b6e7 and add akka-persistence as a dependency
* `sbt run`

This didn't reproduce the problem for me, though I'd say it should get the reference.conf from akka-persistence_2.12.jar. Does this still happen for you?

**Comment by johanandren** [comment]
Tried with current master (9b709df2d0) and can't repeat, let's close this for now.
