### ISSUE TITLE
Naming of ReplicatedShardingSettings

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29447]
Not sure I like the name `ReplicatedShardingSettings`.
Settings is what we typically use to represent configuration, but this is more like a builder/init utility.

`ReplicaSettings` could be `ReplicatedEntity` and `ReplicatedShardingSettings` could be `ReplicatedEntityProvider` ?

**Comment by chbatey** [comment]
I like ReplicaSettings becoming ReplicatedEntity

The ReplicatedShardingSettings i don't mind either way. It does contain the two bits of config needed, but also that factory function so it is settings and a provider.

I'll rename both
