### ISSUE TITLE
pipeTo for arbitrary typed actorref

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29440]
We currently have pipeToSelf on the ActorContext, which is likely the most common thing you'd want to do - call some future-API and get the result into the actor self to process, but I think there is a reasonable use case in forwarding the completed future value to any actor as well, for example if a request triggers some async work, you want to pipe the future response back to the requestee but you don't really want to define a message just to accept and forward to sender, do you?

Did we skip this because it increases the risk of closing over mutable state in the actor or did we just miss implementing something? Does the new StatusReply type help in turning failed future into something an actor would accept without a user provided transformation?

**Comment by patriknw** [comment]
This was considered in https://github.com/akka/akka/pull/25966#issuecomment-441259737

Sending to an ActorRef is perfectly fine to do in a Future callback. I don't see a compelling reason for adding another way of doing that.

**Comment by johanandren** [comment]
Let's close for now then.
