### ISSUE TITLE
Switch in lockUtil can extends AtomicBoolean

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#29445]
![image](https://user-images.githubusercontent.com/501740/89142413-f10ad700-d579-11ea-8cd8-09fcd1afd02b.png)
For memory usage optimize

**Comment by patriknw** [comment]
That wouldn't be binary backwards compatible. The `Switch` is not adding much functionality compared to using plain `AtomicBoolean`, so I would recommend using `AtomicBoolean` instead.

We could even consider deprecating `Switch` in 2.7.0. Not used at many places in the Akka internals.
