### ISSUE TITLE
entityTypeHint in ReplicationContext.persistenceId

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29458]
Looks like the `ReplicationContext.persistenceId` is always `PersistenceId.replicatedUniqueId` and support for the entityTypeHint is missing. Using `entityTypeHint` to make it unique is the recommended approach for EventSourcedBehavior so we should have the same for replicated.

**Comment by chbatey** [comment]
Let's make it mandatory, the consequences of not using an entity type and having a conflicting persistence id are worth avoiding
