### ISSUE TITLE
enable withEventPublishing by default

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29451]
One less thing to "forget". Typical usage defined by default.

There is some overhead of publishing the events if not needed, but maybe not a big deal compared to other things going on.

Also, should direct replication be enabled by default. Primary usage will be with sharding?

**Comment by chbatey** [comment]
I keep forgetting to turn this on when using direct replicatin so i think this is a good idea!

**Comment by chbatey** [comment]
I also think that direct replication could be on by default.
