### ISSUE TITLE
SplittableRandom canbe ThreadLocalSplittableRandom in MergePrioritized

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#29464]
I think cache it should be better.

**Comment by patriknw** [comment]
You mean `ThreadLocalRandom`, I guess.

Why would that be better? `SplittableRandom` is not thread safe, but that's fine from the GraphStage, and that probably means that it has faster acces than ThreadLocalRandom. 

ThreadLocalRandom and SplittableRandom use same random algorithm.

SplittableRandom doesn't hold much state so having many instances of it in case you have many MergePrioritized instances shouldn't be a big deal.

**Comment by hepin1989** [comment]
Yes , as we run it in Actor itself is ThreadSafe.
