### ISSUE TITLE
Make sure silencer-lib works for all potential scala versions

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#29480]
The Akka build support overriding the Scala version using `-Dakka.build.scalaVersion=2.13.1` and that's used in downstream CI. However, it isn't prepared that different Scala versions require different versions of `silencer-lib`.

E.g. see Cinnamon integration build fail with:

https://github.com/lightbend/cinnamon/issues/2515

```
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.ghik:silencer-lib_2.13.1:1.7.0

[error]   Not found

[error]   Not found

[error]   not found: /home/ec2-user/.ivy2/local/com.github.ghik/silencer-lib_2.13.1/1.7.0/ivys/ivy.xml

[error]   not found: http://172.30.1.152:8081/artifactory/reactive-platform/com.github.ghik/silencer-lib_2.13.1/1.7.0/ivys/ivy.xml

[error]   not found: http://172.30.1.152:8081/artifactory/reactive-platform/com/github/ghik/silencer-lib_2.13.1/1.7.0/silencer-lib_2.13.1-1.7.0.pom
```

Hard to say if it should really be fixed here but it is a bit annoying.

Also filed an issue for silencer to avoid CrossVersion.full publishing for the library:

https://github.com/ghik/silencer/issues/59

**Comment by jrudolph** [comment]
Our own nightlies are affected as well:

https://jenkins.akka.io:8498/job/akka-nightly-2.13/620/console

**Comment by raboof** [comment]
> Hard to say if it should really be fixed here

I think we should stick to one supported Scala patch-version - perhaps update `akka.build.scalaVersion` to take `major.minor` rather than `major.minor.patch`?

**Comment by jrudolph** [comment]
> > Hard to say if it should really be fixed here
> 
> I think we should stick to one supported Scala patch-version - perhaps update `akka.build.scalaVersion` to take `major.minor` rather than `major.minor.patch`?

That would at least be a good solution in theory but will probably fail flat because it would be incompatible with current usages? Or we could just strip away the minor version suffix.

**Comment by raboof** [comment]
> it would be incompatible with current usages? Or we could just strip away the minor version suffix.

Or perhaps update the current usages one 'final' (famous last words) time after this change?

**Comment by chbatey** [comment]
I updated out 2.13 build in the mean time
