### ISSUE TITLE
Remove access to sharding refs for replicated event sourcing

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29508]
ReplicatedShardingExtension exposes sharding region ref and entity refs per replica.
The entity ref handles constructing the correct sharding entity id including the entity type name and the replica whereas the sharding region ref that would be up to the user. I think this is possible too sharp an edge

**Comment by patriknw** [comment]
I agree, let's not expose those sharp knives to begin with. A requirement might be to be able to use a custom ShardingEnvelope, but let's deal with that if it comes up.
