### ISSUE TITLE
failed: cluster.StressSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29512]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7950

This is after the reduced scope #29472 

Many log message from remoting, but also note 
```
[InboundActorRefCompression(akka://Stress)] Inbound message from originUid [-6027048747651744337] is using unknown compression table version. It may have been sent with compression table built for previous incarnation of this system. Versions activeTable: 0, nextTable: 1, incomingTable: 1[0m
```

I don't know if that is causing it or a symptom.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7964/

https://jenkins.akka.io:8498/job/akka-multi-node/4182/consoleText

**Comment by seglo** [comment]
Error message for searchability

```
[info] [JVM-3] - must exercise join/remove/join/remove (on node 'node-3', class akka.cluster.StressMultiJvmNode11) *** FAILED *** (1 minute, 17 seconds)
[info] [JVM-3]   15 did not equal 13 (MultiNodeClusterSpec.scala:310)
[info] [JVM-3]   org.scalatest.exceptions.TestFailedException:
```

https://jenkins.akka.io:8498/job/akka-multi-node/4183/consoleFull

**Comment by renatocaval** [comment]
And gain 
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7968/

**Comment by renatocaval** [comment]
And again
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7969/

**Comment by ennru** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/639

**Comment by raboof** [comment]
seems to fail consistently on akka-multi-node now: https://jenkins.akka.io:8498/job/akka-multi-node/4184/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7903/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4185/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7906/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7906/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7912/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8007/consoleFull

**Comment by ennru** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8014/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8018

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/506

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8024

**Comment by patriknw** [comment]
Test failures here are because of https://github.com/akka/akka/issues/29540
I'll try to look into that.

**Comment by seglo** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4205/consoleFull
