### ISSUE TITLE
[Doc] Make "deal with blocking APIs within actors" more prominent or visible

### ISSUE THREAD

**Issue by jlprat** [akka/akka#29544]
As discussed in https://gitter.im/akka/dev?at=5f4656dc59ac794e02c92058 I open this ticket to help and persist the discussion.

# Problem Statement
One of the arguably most common mistakes that occur when using Akka is using blocking code within the actors. Almost every talk or best practices website points this one out and puts lots of stress signalling this problem and how to overcome it.
While the official docs do have this section, I believe it is a bit hidden and not "in the way" of the reader.
Currently, the only place where I could find this information is under the Dispatcher section: https://doc.akka.io/docs/akka/current/typed/dispatchers.html#blocking-needs-careful-management

# Proposal
Link to this section from more introductory pages, so people can easily access this information.
Pages that could have a link to the aforementioned section:
- Actor Systems -> Actor Best Practices: https://doc.akka.io/docs/akka/current/general/actor-systems.html#actor-best-practices
- Terminology -> Non-Blocking vs. Blocking: https://doc.akka.io/docs/akka/current/general/terminology.html#non-blocking-vs-blocking

**Comment by johanandren** [comment]
Sounds like an excellent idea to link and point out in more places.

**Comment by jlprat** [comment]
I will prepare a PR for this in the following days :smiley:
