### ISSUE TITLE
Deprecation warning for Props[AnotherActor] on latest scala version

### ISSUE THREAD

**Issue by AuspeXeu** [akka/akka#29559]
I am getting the following deprecation warning for the latest version of akka in combination with scala (latest version).

```
Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method apply,
[warn] or remove the empty argument list from its definition (Java-defined methods are exempt).
[warn] In Scala 3, an unapplied method like this will be eta-expanded into a function.
[warn]   val actor = system.actorOf(Props[StashTest])
```

I wonder what the best practice conversion of that code to a deprecation free version would be.

**Comment by raboof** [comment]
> I wonder what the best practice conversion of that code to a deprecation free version would be.

You can write `system.actorOf(Props[StashTest]())`.

I see we use the `actorOf(Props[...])` notation in our documentation. I think we should make sure our documentation is deprecation-free for Scala 2.13.

I prefer `actorOf(Props[StashTest])` over `actorOf(Props[StashTest]())` - but unfortunately dropping the `()` is not possible without breaking source-compatibility.

**Comment by AuspeXeu** [comment]
Yup. That's exactly why I wanted to open an issue for this, since your documentation only asks for `actorOf(Props[StashTest])` (which I also prefer to be honest).
