### ISSUE TITLE
add Restart[Source|Flow|Sink].lifetimeMaxRestarts

### ISSUE THREAD

**Issue by laszlovandenhoek** [akka/akka#29550]
the `maxRestarts` parameter of `RestartSource` / `RestartFlow` / `RestartSink` does not do what I thought it did, and I'm not alone:

https://discuss.lightbend.com/t/restart-sources/2592

What I expected was that the Flow would cease to restart after `maxRestarts` restarts, and then stop. However, this only happens until a period of `minDuration` has elapsed; after that point, the Flow becomes effectively immortal. In the end, we had Kafka brokers run out of disk space...

What I'd like to add is another (optional) attribute, `lifetimeMaxRestarts`, which does what it says on the tin: once you hit that number of restarts, the Flow stops, in the same way it would have for `maxRestarts` during starting.

**EDIT**: Originally, I was planning to add this as an extra method parameter, but because `maxRestarts` already is an optional parameter, this gets kinda kludgy, especially in the Java DSL. Ideally I'd also want to get rid of `maxRestarts` because it is prone to misinterpretation. All in all, I'm thinking of creating a separate class à la `akka.pattern.BackoffOnFailureOptions`, but specifically for the three parameters of this method:

```
case class RestartOptions(
  onlyOnFailures: Boolean = false,
  maxRestartsDuringStart: Int = -1, //default infinite restarts
  maxRestartsTotal: Long = -1 //debatable whether this is a sane default, we can discuss
)
```

Another option is to include `minBackoff`, `maxBackoff` and `randomFactor` in there too, although they feel like a separate set of options.

Thoughts?

**EDIT 2**: taking Patrik's insightful comment into consideration, I think we should stick to adding a version that takes a revamped `RestartOptions`, parameter naming inspired by `Flow.throttle`:

```
case class RestartOptions(
  maxRestarts: Int,
  per: FiniteDuration,
  onlyOnFailures: Boolean = false,
)
```

Then:

```
RestartFlow.withBackoff(
  minBackoff: FiniteDuration, 
  maxBackoff: FiniteDuration,
  randomFactor: Double, 
  restartOptions: Option[RestartOptions] = None
)
```

Not sure about what that means for combinatorial explosion on the Java API, though.

**Comment by patriknw** [comment]
> this only happens until a period of minDuration has elapsed; after that point, the Flow becomes effectively immortal

I thought it would reset the count after the minDuration?

```
@param maxRestarts the amount of restarts is capped to this amount within a time frame of minBackoff.
```

Let say `minDuration = 1.second` and `maxRestarts = 5`.
If 4 restarts happen within 1 second and then 3 more restarts within next second it would survive.
but If 4 restarts happen within 1 second and then 6 more within next second it would stop.

Having a total cap isn't that useful in my opinion. Let's say that it is configured to 100. There is 1 restart each day, then it would suddenly stop after 100 days even though there isn't a big problem.

I think the main problem with the API is that the reset duration is tied to the `minBackoff`. Would be better to have a separate `maxRestartsWithin: FiniteDuration`. That would also effectively support a max total by setting the maxRestartsWithin to a very long duration (i.e. never reset the count).

**Comment by patriknw** [comment]
Very related, or duplicate of https://github.com/akka/akka/issues/29291

**Comment by laszlovandenhoek** [comment]
> I think the main problem with the API is that the reset duration is tied to the `minBackoff`. Would be better to have a separate `maxRestartsWithin: FiniteDuration`. That would also effectively support a max total by setting the maxRestartsWithin to a very long duration (i.e. never reset the count).

Thanks for the feedback! That sounds just right. Now, the next question would be which method signature(s) to add and which one(s) (if any) to deprecate.

**Comment by laszlovandenhoek** [comment]
Continuing at #29591.
