### ISSUE TITLE
Failed: akka.persistence.journal.leveldb.LeveldbJournalNativePerfSpec.A PersistentActor's performance must measure: recovering 100 events

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#29564]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8000/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__recovering_100_events/

and

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8000/testReport/junit/akka.persistence.journal.leveldb/LeveldbJournalNativePerfSpec/A_PersistentActor_s_performance_must_measure__persist___ing_100_events/

**Comment by johanandren** [comment]
Duplicate of #29196 ?

**Comment by jrudolph** [comment]
Yep, probably.
