### ISSUE TITLE
[Docs] Code under Routers seems incomplete

### ISSUE THREAD

**Issue by jlprat** [akka/akka#29578]
Traditionally, Akka documentation contains code snippets that are, as far as possible, "copy-paste-able". This means, one could copy the code snippets and run them.

Under the [Routers](https://doc.akka.io/docs/akka/current/typed/routers.html) page, the examples for both Java and Scala APIs have a strange formatting and the code itself it's not runnable, as for instance, `ctx` is never defined.

**Comment by jlprat** [comment]
If you find this issue appropriate I could contribute a PR to it

**Comment by johanandren** [comment]
Yeah, I think the problem with the first sample is that it tries to showcase both the routee (not really _that_ relevant) and the logic for using it in a pool, and the second is just trying to focus on the routing setup and not where that would happen. Please PR improvements if you want to, thanks!

**Comment by jlprat** [comment]
As #29860 is merged, shall this one be closed as well?

**Comment by patriknw** [comment]
Thanks

**Comment by patriknw** [comment]
ha ha

**Comment by jlprat** [comment]
Double closed! :boom:
