### ISSUE TITLE
Include links to release notes in GitHub releases

### ISSUE THREAD

**Issue by exoego** [akka/akka#29571]
I am using [Scala Steward](https://github.com/scala-steward-org/scala-steward) to update dependencies, including akka.
It would be helpful if akka's GitHub release page (e.g. [v2.5.31](https://github.com/akka/akka/releases/tag/v2.5.31)) contains a link to [release notes/news on akka.io (e.g. v2.5.31)](https://akka.io/blog/news/2020/03/31/akka-2.5.31-released).
Because [PRs made by Scala Steward can include a link to GH release page](https://github.com/cornerman/mycelium/pull/58), so Scala Steward users can easily reach a release note and understand what are changes.

**Comment by raboof** [comment]
> I am using [Scala Steward](https://github.com/scala-steward-org/scala-steward) to update dependencies, including akka.

We use it too, it's a lovely tool!

> It would be helpful if akka's GitHub release page (e.g. [v2.5.31](https://github.com/akka/akka/releases/tag/v2.5.31)) contains a link to [release notes/news on akka.io (e.g. v2.5.31)](https://akka.io/blog/news/2020/03/31/akka-2.5.31-released).

I agree that would be nice! For most recent 2.6 releases we've actually done this (e.g. [v2.6.8](https://github.com/akka/akka/releases/tag/v2.6.8)), but it looks like we haven't added it to the release procedure yet. Will do that now.
