### ISSUE TITLE
Add support for specifying a predicate function (instead of a fixed message) as `ackMessage` in `ActorSink#actorRefWithBackpressure`

### ISSUE THREAD

**Issue by odd** [akka/akka#29586]
This would allow the predicate to only consider a subset of the fields of a specific `ackMessage` (we use correlation ids in all our messages which makes it impossible to have a predefined `ackMessage` since the correlation id will be different for each `ackMessage`).

**Comment by patriknw** [comment]
I don't fully understand. ActorSink.actorRefWithBackpressure sends each stream element to the actor and expects an ackMessage for each stream element. It only sends one message and then waits for the ack before it sends next. Therefore, I don't see why correlation id would be needed in the ackMessage. What did I miss?

**Comment by odd** [comment]
Thanks for the quick reply. I will try to state our usage a little more clearly: we have a typed actor that for each command it receives, sends a reply message back to the specified `replyTo` of the command. The returned reply message contains a command specific payload (or `Done` if no payload is needed) and the correlation id of the corresponding command. The problem is that when a stream created with `ActorSink.actorRefWithBackpressure` feeds commands (each having a different correlation id) to the actor, the single reply message instance supplied as `ackMessage` will not be equal to the actual reply message received in the stream since the correlation ids will not match. As a workaround we have defined special commands for this called-from-stream use case and those commands do not include a correlation id in their reply message. If the `ackMessage` where a predicate function instead of a value, we could supply a function that only checks the equality of the payload part of reply messages (and disregards the correlation id part).

**Comment by johanandren** [comment]
Sounds like a somewhat narrow use case but I think it would be useful if it was possible without having to change the unique-message-ack:ing actor or put an adapter of some kind inbetween.

**Comment by patriknw** [comment]
ok, you are using the actor from two different senders.
The signature of `actorRefWithBackpressure` is already rather difficult to understand so adding another variant with a predicate would add some more confusion.

Adding an overloaded method with `isAckMessage: A => Boolean` would raise questions like, "when will it return false?", "what is A if it's not an ack?"

Then it's probably better to have signature without the `ackMessage: A` parameter. Meaning that any reply is treated as an ack. Could that work?

**Comment by odd** [comment]
Yes, an overload without an explicit `ackMessage` which would treat any reply as an ack would work nicely indeed. Thanks for looking in to the problem and finding an even simpler solution.

**Comment by johanandren** [comment]
Would you be up for taking a stab at adding it @odd?

**Comment by odd** [comment]
Sure, might take a couple of days until I can give it a shot though :)

**Comment by patriknw** [comment]
Thanks
