### ISSUE TITLE
`EventSourcedBehaviorTestKitSpec` has failed repeatedly in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#29609]
**akka-more** fail Sep 11
  https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3711/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec
**akka-more** fail Sep 10
  https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3709/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec
**akka-more** fail Sep 9
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/1189/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec
**akka-more** fail Sep 9
  https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/1188/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec
**akka-more** fail Sep 1
  https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3676/artifact/logs/akka-more-build.log
  akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKitSpec

the commit we're using is 7368e134582f0324437991c75619368eae4f24c5

**Comment by patriknw** [comment]
@SethTisue this should be fixed in master now
