### ISSUE TITLE
GCounter merge function: what if this state and that state have different keys?

### ISSUE THREAD

**Issue by YikSanChan** [akka/akka#29616]
Imagine

gc1.state={node1:1, node2:2}
gc2.state={node2:3}

According to the current logic, gc1.merge(gc2) => state={node2:3}

However, node1=1 is not merged.

The code doesn't handle this case - is it because we are ok to assume different GCounter (or more generally, ReplicatedData) must have the same keys?

**Comment by patriknw** [comment]
How did you see that result?
I added a test in https://github.com/akka/akka/pull/29624 and it works as expected.

**Comment by YikSanChan** [comment]
@patriknw thx, my bad, I thought it was like that from reading the code, but I didn't add the test to test it.

I will close.
