### ISSUE TITLE
It seems CrossDcHeartbeatSender does not use akka.cluster.multi-data-center.failure-detector.heartbeat-interval

### ISSUE THREAD

**Issue by RicardoGascaGarcia** [akka/akka#29614]
Test a cluster with two nodes:

- Node 1: akka.cluster.multi-data-center.self-data-center = "A"
- Node 2: akka.cluster.multi-data-center.self-data-center = "B"

I add to my application.conf the following configuration:

> akka.cluster.debug.verbose-heartbeat-logging = on 
> **akka.cluster.multi-data-center.failure-detector.heartbeat-interval = 3 s**
> akka.cluster.multi-data-center.failure-detector.acceptable-heartbeat-pause = 10 s
> akka.cluster.multi-data-center.failure-detector.expected-response-after = 5 s
  
When review my log, the CrossDcHeartbeatSender shows a hearthbeat every second:

> 2020-09-17 08:45:27.117|[DEBUG]|[akka.tcp://ccm@10.124.13.29:2701/system/cluster/core/daemon/crossDcHeartbeatSender]|Cluster Node [B][akka.tcp://ccm@10.124.13.29:2701] - (Cross) Heartbeat to [akka.tcp://ccm@sfed-01-rgasca:2701]|
> 2020-09-17 08:45:27.120|[DEBUG]|[akka.tcp://ccm@10.124.13.29:2701/system/cluster/core/daemon/crossDcHeartbeatSender]|Cluster Node [B][akka.tcp://ccm@10.124.13.29:2701] - (Cross) Heartbeat response from [akka.tcp://ccm@sfed-01-rgasca:2701]|

> 2020-09-17 08:45:28.107|[DEBUG]|[akka.tcp://ccm@10.124.13.29:2701/system/cluster/core/daemon/crossDcHeartbeatSender]|Cluster Node [B][akka.tcp://ccm@10.124.13.29:2701] - (Cross) Heartbeat to [akka.tcp://ccm@sfed-01-rgasca:2701]|
> 2020-09-17 08:45:28.111|[DEBUG]|[akka.tcp://ccm@10.124.13.29:2701/system/cluster/core/daemon/crossDcHeartbeatSender]|Cluster Node [B][akka.tcp://ccm@10.124.13.29:2701] - (Cross) Heartbeat response from [akka.tcp://ccm@sfed-01-rgasca:2701]|

However, if I change my application.conf with this new entry (heartbeat in main cluster section not multi-data-center) :

> akka.cluster.failure-detector.heartbeat-interval = 3 s

crossDcHeartbeatSender shows (Cross) Heartbeat every 3 s.

Is the system working properly with the value configured at entry "akka.cluster.failure-detector.heartbeat-interval" or should it work with the value configured in section "akka.cluster.multi-data-center.failure-detector.heartbeat-interval"?

**Comment by patriknw** [comment]
Thanks for reporting. The bug is here: 
https://github.com/akka/akka/blob/e3dadd981fb64872dfeefd3b2e7c212d6a340ef7/akka-cluster/src/main/scala/akka/cluster/CrossDcClusterHeartbeat.scala#L81

It should use `crossDcSettings.HeartbeatInterval`.

Would you like to create a pull request for fixing the problem?

**Comment by RicardoGascaGarcia** [comment]
@patriknw, I don't have enough experience to pull request for fixing problems, at least for now.  I´m sorry.

**Comment by patriknw** [comment]
No problem. I'll fix this.
