### ISSUE TITLE
VectorClock implementation seems very complicated

### ISSUE THREAD

**Issue by YikSanChan** [akka/akka#29629]
I am looking into "How Akka Cluster work" and deep-diving the code. During the process, I find VectorClock#compareOnlyTo is kinda hard to reason about, after PR https://github.com/akka/akka/pull/1705. May someone helps suggest if we can simplify the implementation with a simple `forall`?

**Comment by patriknw** [comment]
It's working and not often (if ever) changed so I don't see a strong reason for changing it. If you come up with an alternative proposal it must be tested thoroughly for performance regressions.

**Comment by chbatey** [comment]
Let's close this, feel free to open again with a more specific suggestion or a PR
