### ISSUE TITLE
EventSourcedBehavior snapshot creation right after state recovery in case of missing snapshots

### ISSUE THREAD

**Issue by dope9967** [akka/akka#29631]
In some use cases it can be useful to have an option to delete all snapshots and let the entity recover it's state fully from events instead of implementing migrations. When entity has a lot of events the recovery can throw a timeout exception. Issue with this is that timeouts will continue to be thrown on every recovery until either `snapshotWhen` encounters an event that triggers snapshot creation or there are enough of events persisted for `currentSequenceNr % snapshotEveryNEvents == 0`. What if state recovery could detect that more than `snapshotEveryNEvents` were recovered without encountering a saved snapshot and start snapshot creation as a first thing after state is recovered?

**Comment by patriknw** [comment]
> When entity has a lot of events the recovery can throw a timeout exception.

There is config `akka.persistence.journal-plugin-fallback.recovery-event-timeout`, but that is max time between each event and that shouldn't be influenced by how many events there are, unless the system is overloaded by the many events.
Which journal plugin is this?

> What if state recovery could detect that more than snapshotEveryNEvents were recovered without encountering a saved snapshot and start snapshot creation as a first thing after state is recovered?

Sounds like a good idea.

**Comment by dope9967** [comment]
That's what I eventually figured out - increased all recovery related timeouts and the entity recovered, then set snapshots to save after each event and forced some commands to same some dummy data for several huge entities.

I could work on implementing snapshot saving after recovery. Do you think it should be default behavior for `EventSourcedBehavior` or toggleable/configurable?

**Comment by patriknw** [comment]
Thanks. I think it can be the default when snapshotting is enabled.
