### ISSUE TITLE
Akka-Persistence: Ease migration path from Java to Scala: Allow easy access to akka.persistence.typed.javadsl.EffectFactories from Scala

### ISSUE THREAD

**Issue by domdorn** [akka/akka#29659]
I'm in the middle of migrating a Java Akka-Persistence-Typed project to Scala. 

The client has Command-Handlers that take an `EffectFactories<Event, State>` as parameter to separate different command handlers out into helper classes. 

Now, when trying to create a new Scala EventSourcedBehavior, I need to reuse as much of the existing code as possible. 
This is already possible for EventHandlers, as I have access to `EventHandlerBuilder.builder()` as well as `CommandHandlerBuilder.builder()`. 

To get access to a instance of EffectFactories, I had to create a helper like this: 
```
object BehaviorAdapater {

  private class DummyBehavior[E, S] extends EventSourcedBehavior[Done, E, S](PersistenceId.of("", "")) {
    override protected def emptyState: S                                = ???
    override protected def commandHandler(): CommandHandler[Done, E, S] = ???
    override protected def eventHandler(): EventHandler[S, E]           = ???

    def getEffectFactory: EffectFactories[E, S] = Effect
  }

  def getEffectFactory[E, S](): EffectFactories[E, S] =
    new DummyBehavior[E, S].getEffectFactory
}
```

then I was able to reuse their existing code that leveraged the EffectFactories, e.g. by using code like 
```
    val effectFactories = BehaviorAdapater.getEffectFactory[ScenarioEvent, State]()
    val initialStateCommandHandler = new InitialStateCommandHandler(
      clock,
      effectFactories,
      akka.persistence.typed.javadsl.CommandHandlerBuilder.builder())
```

It should be possible to create a `EffectFactory[E,S]` as easy as it is with the `EventHandlerBuilder` and `CommandHandlerBuilder`

**Comment by octonato** [comment]
@domdorn, I'm closing this one as well for the same reasons we closed #29660. Such a edge case is better solved on user's code base. 

Thanks.
