### ISSUE TITLE
akka-cluster-sharding-typed does not support lease

### ISSUE THREAD

**Issue by horvath-martin** [akka/akka#29662]
Hello!
I am trying to setup a kubernetes lease for Cluster Sharding (typed system).
I have added the following dependencies for this:
* "com.lightbend.akka.management" %% "akka-lease-kubernetes" % "1.0.8"
* "com.typesafe.akka" %% "akka-coordination" % "2.6.9"

Based on the documentation, I have added the _akka.cluster.sharding.use-lease_ config to the actor.conf with the value _"akka.lease.kubernetes"_ and filled the config keys under _"akka.lease.kubernetes"_.

When I tested it, it did not seem to have any effect.
I thought first that I have configured it incorrectly, so I tried it with obviously invalid values and still nothing changed.

I have checked where the "use-lease" key is read for Cluster Sharding and I think a found the source of the problem.
In _akka.cluster.sharding.ClusterShardingSettings.apply(config: Config)_ the lease is correctly read from the config.
This is always called from _akka.cluster.sharding.typed.ClusterShardingSettings.fromConfig(config: Config)_ and passed to _akka.cluster.sharding.typed.ClusterShardingSettings.fromClassicSettings(numberOfShards: Int, classicSettings: ClassicShardingSettings)_ where the lease object is not used and not passed further.

Could it be that the lease feature is not implemented for akka typed or am I missing something?

**Comment by johanandren** [comment]
Looks like an oversight and it is indeed not passing that along in the typed config. Would you be up for PR:ing a fix?

**Comment by chbatey** [comment]
Oh this should be 2.6.11 now. I'll follow up
