### ISSUE TITLE
Akka-Persistence: Ease migration path from Java to Scala: Allow to convert between effects

### ISSUE THREAD

**Issue by domdorn** [akka/akka#29660]
This is a follow up issue of https://github.com/akka/akka/issues/29659: 

As mentioned in the other ticket, I'm in the process of migrating a Java Akka-Persistence Typed project to Scala. 
The existing code of the client is using the Java-Effects, e.g. `akka.persistence.typed.javadsl.Effect` or `akka.persistence.typed.javadsl.ReplyEffect`. 

Currently, it is not as straightforward to use these in a Scala EventSourcedBehavior. Fortunatelly, the "Java-Effect" builds on top of `akka.persistence.typed.internal.EffectImpl` which itself mixes in the `akka.persistence.typed.scaladsl.ReplyEffect` allowing me to simply cast the Java-Effect to a Scala-Effect. 
For convenience, I wrote this code: 
```
import akka.persistence.typed.javadsl.{
  CommandHandler,
  EffectFactories,
  EventHandler,
  EventSourcedBehavior,
  Effect => JEffect
}
import akka.persistence.typed.scaladsl.{Effect => SEffect}

import scala.reflect.ClassTag

object EffectConverters {

  implicit class ToScalaConverter[E, S](javaEffect: JEffect[E, S]) {
    def asScala(
      implicit event: ClassTag[E],
      state: ClassTag[S]): SEffect[E, S] = javaEffect.asInstanceOf[SEffect[E, S]]
  }

}
```

which allows me to do 

`myJavaEffect.toScala`

It would be good if the library would already provide `asScala` and `asJava` conversion methods

**Comment by renatocaval** [comment]
@domdorn, we have this kind of methods in many places in Akka, but it's often used by internal code when we need to move from one API to another.k

The question is how likely it is for another users to walk that same path you are walking. I personally don't think that it's common to migrate from Akka Persistence Typed Java to Scala. And if so, why not simply refactor the code to use Scala?

**Comment by patriknw** [comment]
I agree with Renato. It's not intended to be able to use javadsl from scaladsl here. I think you are looking for more trouble by doing this migration step than rewriting it to use the scaladsl.

**Comment by domdorn** [comment]
We've managed to get the customer to allow us (the developers) to use Scala (in an existing Java codebase). 
The need comes from a business/developer side: Migrating the quite huge akka-persistence-typed java actor (including all tests etc) to scala would take more than one sprint (we have over 40 command handlers + event handlers + serialization + tests ) and not give the customer any business value (= expensive, for no obvious gain). 
However, when developers can say "we can reuse all the existing code and just write new code in Scala" its easy for the customer to say "ok, if it doesn't cost me much/anything and is not risky, just do as you like". 

If you say that's just an edge case, I'm fine with that, as I found my way around the issue. 
For the current project, getting Akka into the (spring boot) project was ok as we were able to say "it has a Java API and can be used with Java by all the Java Developers" (e.g. it is not a risky choice as the developers we already have can use it with their Java knowhow).. now 4 months in, we see the differences in API comfort beween Java and Scala and try to get the customer to switch to Scala / allow us to use Scala. This is only possible if it can be done with little effort. Incrementally moving from a Java codebase to a Scala codebase by making it possible to reuse the existing code allows this and removes pressure (e.g. I have to finish this migration soon to not block others), cost (I can reuse the already existing code) and risk ( will the application run the same / better after this migration or will we have new unknown bugs because everything had to be written from scratch). Having Akka as an approved technology in the project allows as to gradually move away from spring as well. 

Seen from this point, Akka for Java was a doorway technology which now allows us developers to move away from spring to akka-http and from Java to Scala (e.g. "scala is already in the classpath, we just need to enable the gradle plugin") and maybe later even from gradle to sbt/something else (e.g. "its way more comfortable to use sbt with scala than gradle"). 

As already said, I'm fine if you decide to not support this, as I've already managed my way around it. The statement "if any of our Java developers doesn't feel comfortable writing in Scala, he/she can still do it in Java" helped us to convince project management to allow this switch.

**Comment by octonato** [comment]
Thanks for understanding. 

This kind of situation is better solved by adding converters in the project itself, like you did already, instead of adding it in Akka. You don't need to wait for a release and we don't need maintain an edge case on our side. 

I will close the this ticket. Thanks.
