### ISSUE TITLE
Include Akka Projections on the Akka modules list

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#29710]
The Akka modules page in the docs (https://doc.akka.io/docs/akka/current/typed/guide/modules.html) doesn't include Akka Projections:

https://github.com/akka/akka/blob/294c534d1533e1bcf1c425af6137d51bdbc25e6f/akka-docs/src/main/paradox/typed/guide/modules.md#L7-L15

**Comment by ignasi35** [comment]
The main module list (https://akka.io/docs/) doesn't include projections either.

**Comment by raboof** [comment]
> The main module list (https://akka.io/docs/) doesn't include projections either.

Could you create an issue at https://github.com/akka/akka.io/ for that?

**Comment by muskan3006** [comment]
Hey @ignasi35, do we have to add akka projection in list and then a small description in the end?

**Comment by raboof** [comment]
> do we have to add akka projection in list and then a small description in the end?

That sounds good to me!

**Comment by ignasi35** [comment]
> Hey @ignasi35, do we have to add akka projection in list and then a small description in the end?

Instead of adding the description at the end, I would keep Akka Projection as close as possible to anything related to Akka Persistence. That's the criteria we used when adding the section on the main scree (https://akka.io/docs/).

Other than this detail, LGTM.

**Comment by ignasi35** [comment]
I think this issue is complete already:

- in https://github.com/akka/akka.io/pull/765 we closed https://github.com/akka/akka.io/pull/749
- https://doc.akka.io/docs/akka/current/common/other-modules.html already lists projections
