### ISSUE TITLE
akka.pattern.StatusReply support in akka-serialization-jackson

### ISSUE THREAD

**Issue by AndreasPresthammer** [akka/akka#29720]
Package: akka-serialization-jackson

When trying to use akka-serializiation-jackson for message serialization in cluster mode I observed that the built-in akka type akka.pattern.StatusReply (https://doc.akka.io/api/akka/2.6/akka/pattern/StatusReply.html) was not supported by the jackson serializer.

Would you consider adding support for this, since it would have a natural place in many akka messages as part of the reply parameter.

**Comment by johanandren** [comment]
It already has an optimized protobuf serializer defined, do you have a scenario where that cannot be used for some reason?

**Comment by AndreasPresthammer** [comment]
I was following this guide (https://doc.akka.io/docs/akka/current/serialization-jackson.html) to setup cluster mode with jackson serialization of the messages.
I have messages on this form:
case class MyMessage(reply: ActorRef[StatusReply[SomeReply]])

The MyMessage case class will be jackson serialized. I was hoping the StatusReply would also have a serializer/deserializer provided from the akka-serialization-jackson package.

Hope that made sense.

**Comment by johanandren** [comment]
For that case, the built in serializer for `StatusReply` (which is available out of the box) will use whatever serializer you defined for `SomeReply`, so jackson for example, and wrap that with as little extra data it can to be able to deserialize it on the receiving side. It should not be important that the wrapping `StatusReply` uses a different serializer.

**Comment by patriknw** [comment]
I don't think this is an issue. Please open question at https://discuss.akka.io if you need further assistance.
