### ISSUE TITLE
How to take care of High availability in  Cluster aware group router with remote routees , if router get fail in Akka. 

### ISSUE THREAD

**Issue by rajofraj01** [akka/akka#29739]
Please use https://discuss.akka.io for questions instead of posting them to the issue tracker.

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug. Please add clear information in that case about what behavior you expected and what you experienced instead. Adding a reproducer will help a lot as well.
