### ISSUE TITLE
ActorGraphInterpreter enter limbo state when interpreter completes but a new shell registration is pending

### ISSUE THREAD

**Issue by eyalfa** [akka/akka#29730]
we've recently deployed a new version of our service, after half a day we've observed unusual heap size and gc activity.

while analyzing a heap dump from our production environment we saw a lot of ActorCell instances, closer look shows that great portion of them were `ActorGraphInterpreter`s.

Examining these actors internal state (as visible in the heap dump) revealed that all of them were in a limbo state where `activeInterpreters` was empty and `newShells` was not and contained a single shell with three logics: SubSource, identity flow and SubSink.
furthermore, the SubSink's internal state was `CancelScheduledBeforeMaterialization` and SubSource's internal state was `ActorSubscriberMessage.OnComplete`.

since the SubSource object's name was referring to `flamMapPrefix` it was obvious this new shell was materialized by `FlatMapPrefix`.
going over our change log between the two deployments we were able to track a new indirect usage of `flatMapPrefix` via `Flow.lazyFutureFlow` which uses the identity flow when upstream completes without producing any elements.

The SubSource's internal state (onComplete message) suggests that `flatMapPrefix`'s upstream actually completed without producing any elements, the internal state of the SubSink also suggest that it was closed prior to being registered (right after materialization).

it seems that `flatMapPrefix` handled both upstreamFinished and downstream cancellation before the materialized internal flow was registered, then when the actor graph interpreter regained control it saw that the current interpreter completed but somehow missed the newShell (speculating here) which put it in a limbo state where it await messages that will never come but not stopped either.

looking at the code I can see two potential issues in the source code:
1. `flatMapPrefix` doesn't set `keepGoing' to true, so once both its ports are closed, the interpreter considers it closed as well.
2. there seems to be a bug in the condition in `akka.stream.impl.fusing.ActorGraphInterpreter#shortCircuitBatch` which doesn't consider `newShells`:
```
while (!shortCircuitBuffer.isEmpty && currentLimit > 0 && activeInterpreters.nonEmpty)
```
notice that in case all current interpreters are complete but there is one pending newShell, this condition will prevent the actor from seeing the `Resume` message in the `shortCircuitBuffer` which puts the actor int the limbo state described above.

**Comment by eyalfa** [comment]
cc: @johanandren , @jrudolph , @seglo  (all participated reviewing the `flatMapPrefix` feature).

**Comment by johanandren** [comment]
As said in 1:1 chat, some form of minimal reproducer would be great

**Comment by eyalfa** [comment]
thinking about it, I think I might be able to leverage akka streams tests verifying the lack of pending materializer actors when the test completes

**Comment by eyalfa** [comment]
ok, I've got a repro and a fix, will open a pr shortly.

test code:
```
"repro" in assertAllStagesStopped {
        @volatile var closeSink : () => Unit = null

        val (fNotUsed, qOut) = Source.empty[Int]
          .flatMapPrefixMat(1){ seq =>
            println("waiting for closer to be set")
            while (null == closeSink) Thread.sleep(50)
            println("closing sink")
            closeSink()
            println("sink closed")
            //closing the sink before returning means that it's higly probably
            //for the flatMapPrefix stage to receive the downstream cancellation before the actor graph interpreter 
            //gets a chance to complete the new interpreter shell's registration.
            //this in turn exposes a bug in the actor graph interpreter when all active flows complete
            //but there are pending new interpreter shells to be registered.
            Flow[Int]
              .prepend(Source(seq))
          } (Keep.right)
          .toMat(Sink.queue(10))(Keep.both)
          .run

        println("assigning closer")
        closeSink = () => qOut.cancel()

        println("closer assigned, waiting for completion")
        //Thread.sleep(10000000)
        fNotUsed.futureValue should be (NotUsed)
      }
```

and the fix (in actor graph interpreter's `shortCircuitBatch` method)"
`while (!shortCircuitBuffer.isEmpty && currentLimit > 0 && (activeInterpreters.nonEmpty || newShells.nonEmpty))`

**Comment by jrudolph** [comment]
Great catch, you seem to be right. Really surprising that this never came up before.

**Comment by plzakj** [comment]
Hello @jrudolph, does this issue also affect 2.5.32 branch? Will the fix be merged to 2.5.X?

**Comment by jrudolph** [comment]
> does this issue also affect 2.5.32 branch?

Yes, though 2.5.x didn't yet have the `flatMapPrefix` operator that run into the issue. Though, it's not really exclusive to `flatMapPrefix` and may show in other scenarios.

> Will the fix be merged to 2.5.X?

It's currently not planned, 2.5.x is only updated very infrequently at this point. Do you have a case where you observe the behavior also with 2.5.x?

**Comment by plzakj** [comment]
>  Do you have a case where you observe the behavior also with 2.5.x?
No, no observation with 2.5.x. We started to use Akka-http in SW which uses Actors 2.5.x so We just analyzed the current open tickets.

**Comment by jrudolph** [comment]
> No, no observation with 2.5.x. We started to use Akka-http in SW which uses Actors 2.5.x so We just analyzed the current open tickets.

Thanks for the additional info. You can (and should) use Akka HTTP 10.2.x with Akka 2.6, so you will get the latest fixes for Akka as well.
