### ISSUE TITLE
Akka teskit.spawn to return ActorSystem

### ISSUE THREAD

**Issue by politrons** [akka/akka#29743]
Hi all,

I'm using AkkaTestFramework with Akka typed, and I cannot find a way to create an ActorSystem mock for one of my typed Actor.

I found this way 

`    val pinger: ActorRefTyped[ItAssetRequest] = testKit.spawn(ItAsset(), "itAssetMock")
`
But this `ActorRefTyped` does not contain a `schedule` which I need internally in my class to use `ask pattern`

In my class where I receive this ActorSystem

```
    class RegisterConsumerStream(itAsset: ActorSystemTyped[ItAssetRequest]){
    
    
      implicit val schedule: typed.Scheduler = itAsset.scheduler
    
    
      itAsset ? (ref => ItAssetRequest(connectorState, ref)
    
    
    }
```

If I pass a `ActorRefTyped[ItAssetRequest]` there's no schedule so I cannot use the ask pattern since it needs the schedule implicit.

Any idea?

**Comment by johanandren** [comment]
Hi @politrons , `AkkaTestFramework` is not a type Akka provides, are you using some third party testing library that provides that perhaps?

**Comment by politrons** [comment]
Sorry by `AkkaTestFramework` I mean your Akka Test Kit 😄

**Comment by jlprat** [comment]
Maybe you can take a look at https://doc.akka.io/docs/akka/current/typed/testing-async.html#asynchronous-testing vs https://doc.akka.io/docs/akka/current/typed/testing-sync.html#synchronous-behavior-testing.
The later doesn't support many asynchronous actions like the `Scheduler`. While the former is a "full-fledged" testing actor system.

**Comment by johanandren** [comment]
We try to use the issue tracker for bug reports and feature requests, but this looks more like a question, so please do ask again over in the forums at https://discuss.akka.io if you do not figure this out.

I'll close this for now.

**Comment by politrons** [comment]
@johanandren ok, but just in case you guys want to remove the option. When you open an issue, is a section to mark as question.

**Comment by johanandren** [comment]
I'm afraid that is some default that is not possible to remove from github, or at least wasn't when we last looked at it. I'll see if perhaps it is possible nowadays.
