### ISSUE TITLE
Can't activate logging of line numbers with logback

### ISSUE THREAD

**Issue by longliveenduro** [akka/akka#29750]
We are using Akka 2.4.19 with Scala 2.12.12. If I configure logback to log line numbers I only see: 

`Slf4jLogger.scala:83`

which is a class in the akka library. How do I get the real location of the issued log statement or what am I doing wrong?

See also https://stackoverflow.com/questions/64355775/how-to-log-filename-and-linenumber-in-akka-classic-actor

I do use the following pattern:

`<pattern>%d{HH:mm:ss.SSS} %-5level [%thread] [%logger] [%F:%L] [%mdc{akkaSource:-}] %msg [%mdc]%n</pattern>`

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Short answer is that Akka's logging is asynchronous so Slf4jLogger is expected. You can create your own slf4j Logger with the  LoggerFactory and then you will see your own source code.

**Comment by longliveenduro** [comment]
Cheers @patriknw. Sorry for the noise. I had a long look a the FAQ of akka and around the doc for Akka, but couldn't find a mailing list link. Maybe make it a little bit more prominent in the docs?

**Comment by patriknw** [comment]
> couldn't find a mailing list link

Sorry for the inconvenient. It's in https://akka.io/get-involved/ and in the footer of akka.io. Also in reference docs https://doc.akka.io/docs/akka/current/project/links.html and mentioned in the issue template. No worries.

**Comment by raboof** [comment]
> I had a long look a the FAQ

Makes sense to add a link from https://doc.akka.io/docs/akka/current/additional/faq.html to https://akka.io/get-involved/ I guess - I'll PR
