### ISSUE TITLE
deserialization error of HandshakeReq

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29753]
```
"a.r.a.Deserializer" | Failed to deserialize message from [unknown] with serializer id [17] and manifest [d]. java.lang.IllegalArgumentException: newPosition > limit: (603980120 > 348) 
```

That is HandshakeReq in ArteryMessageSerializer.

Don't know if it's related but there were also problems with oversized messages in this application.

**Comment by ranglang** [comment]
happen to Kamon initiation

**Comment by patriknw** [comment]
> happen to Kamon initiation

@ranglang please open an issue in Kamon if you think it's causing this problem.
