### ISSUE TITLE
provide an ExtendedActorSystem instance in TestKit

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#29765]
I have my own serializer like `class AvroSerializer(system: ExtendedActorSystem) extends SerializerWithStringManifest`
I'd like to write some unit tests for it but couldn't find a way to provide an `ExtendedActorSystem` instance.

**Comment by Zhen-hao** [comment]
related discussion on Gitter: https://gitter.im/akka/akka?at=5f8d7ec3bbffc02b58275944

**Comment by raboof** [comment]
Does it really need a `ExtendedActorSystem`? IIRC we moved some of the methods that used to be only available on `ExtendedActorSystem` to `ActorSystem` in 2.6

**Comment by patriknw** [comment]
> Does it really need a ExtendedActorSystem?

`SerializerWithStringManifest` takes a `ExtendedActorSystem` as constructor parameter.

Do we talk about the typed or classic TestKit here?

Maybe we should provide a convenience in akka.actor.ActorSystem to convert it to ExtendedActorSystem? In practice an ActorSystem is always an ExtendedActorSystem. It was intended as a way to "hide" some power features.

**Comment by raboof** [comment]
> > Does it really need a ExtendedActorSystem?
> 
> `SerializerWithStringManifest` takes a `ExtendedActorSystem` as constructor parameter.

Ah of course (https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/serialization/Serialization.scala#L390). Perhaps we should also support ActorSystem constructors here?

> Maybe we should provide a convenience in akka.actor.ActorSystem to convert it to ExtendedActorSystem? In practice an ActorSystem is always an ExtendedActorSystem. It was intended as a way to "hide" some power features.

Might be reasonable.

Until that time, @Zhen-hao another workaround perhaps might be to use `ActorSystem` in your implementation, and have a constructor taking a `ExtendedActorSystem` that just calls your `ActorSystem` ctor (adapting the argument if necessary)?

**Comment by patriknw** [comment]
> Perhaps we should also support ActorSystem constructors here?

Doesn't help much, since it should be akka.actor.typed.ActorSystem but that's not possible since Serialization API/creation is in akka-actor.

**Comment by Zhen-hao** [comment]
thanks for looking into it!

I would prefer to use a typed API. but now I have to convert my typed actor system to classic in order to use this serializer interface.
unfortunately, I don't have much time recently to dive deep to figure out how to make it better.

**Comment by patriknw** [comment]
> but now I have to convert my typed actor system to classic

Just to be clear, that is not a "bad" thing. It is designed so that [Classic and Typed can coexist](https://doc.akka.io/docs/akka/current/typed/coexisting.html).

**Comment by Zhen-hao** [comment]
@patriknw of course. but wouldn't it be even better if there is also a typed interface?

**Comment by chbatey** [comment]
It would be nice but the loading is done from `akka-actor` which doesn't have the typed actor system

**Comment by Zhen-hao** [comment]
I actually need the typed-to-classic conversion in multiple places in my codebase to integrate better with another library. I guess the coexisting will be there for a long time. 
Closing since it is not any blocker for me.

**Comment by gervaisb** [comment]
Hello there. I'm restarting this old issue. 

How can we test a custom serializer since we cannot get an ExtendedActorSystem ?

**Comment by patriknw** [comment]
@gervaisb We have added constructor alternatives with `akka.actor.ActorSystem` and `akka.actor.ClassicActorSystemProvider`, which will be included in Akka 2.8.2
See https://github.com/akka/akka/pull/31936
