### ISSUE TITLE
"Unsupported access to ActorContext" with BehaviorTestKit.signal()

### ISSUE THREAD

**Issue by aumann** [akka/akka#29779]
Akka version: 2.6.10

Using BehaviorTestKit.signal() there seems to be a false alarm w.r.t. unsupported context access.

The following test snippet currently throws an exception (`Unsupported access to ActorContext from the outside of Actor[...]. No message is currently processed by the actor, but ActorContext was called from Thread[ScalaTest-run-running-UnsupportedContextTest,5,main].`):

```scala
package org.example.test

import akka.NotUsed
import akka.actor.testkit.typed.scaladsl.{BehaviorTestKit, ScalaTestWithActorTestKit, TestInbox}
import akka.actor.typed.{Behavior, Terminated}
import akka.actor.typed.scaladsl.Behaviors
import org.scalatest.wordspec.AnyWordSpecLike

class UnsupportedContextTest extends ScalaTestWithActorTestKit with AnyWordSpecLike {

  "BehaviorTestKit" should {
    "not fail" in {
      val dying   = TestInbox()
      val testKit = BehaviorTestKit(UnsupportedContextTest.behavior)
      testKit.run(NotUsed)                  // works
      testKit.signal(Terminated(dying.ref)) // throws
    }
  }
}

object UnsupportedContextTest {
  def behavior: Behavior[NotUsed] =
    Behaviors
      .receive[NotUsed] {
        case (ctx, NotUsed) =>
          ctx.log.info("Received message")
          Behaviors.same
      }
      .receiveSignal {
        case (ctx, Terminated(_)) =>
          ctx.log.info("Received termination signal") // throws here
          Behaviors.same

      }
}
```
I would expect this snippet not to throw an exception (as the usage of ctx.log happens from within normal signal handling code):

The method implementations in BehaviorTestKitImpl are slightly different, which probably causes this problem: 
The `run()` method sets the current thread, the `signal()` method does not.

**Comment by patriknw** [comment]
@aumann Thanks for reporting. That must be an oversight in the `signal` method, as you spotted. Would you like to contribute a fix with a PR?
