### ISSUE TITLE
Inconsistent behaviour with SnapshotTestKit related to RetentionCriteria (keepNSnapshots)

### ISSUE THREAD

**Issue by sebastian-alfers** [akka/akka#29772]
The `SnapshotTestKit.expectNextPersisted` maintains a stateful, growing index in order to access a certain snapshot that was created within an actor.

Using `RetentionCriteria` causes snapshots to be deleted which causes that index to get out of sync with the storage.

**Comment by johanandren** [comment]
@sebastian-alfers was this completely fixed by #29769 or are there additional fixes needed?

**Comment by patriknw** [comment]
This was fixed, we just forgot to close the issue.

**Comment by sebastian-alfers** [comment]
@johanandren To my knowledge there are is nothing left to be fixed
