### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by sash-a** [akka/akka#29781]
The link to the supervision example project seems to be broken [on your docs](https://doc.akka.io/docs/akka/2.5.32/general/supervision.html). Here is what it is pointing to https://developer.lightbend.com/start/?group=akka&project=akka-samples-supervision-java. Not sure what the correct link is or if there is a correct one

**Comment by johanandren** [comment]
That sample is not published (nor maintained anymore) but you can find the sources here: https://github.com/akka/akka-samples/tree/2.5/akka-sample-supervision-java

**Comment by sash-a** [comment]
Thanks!
