### ISSUE TITLE
relax statefulMapConcat and mapConcat requirements on f's return type

### ISSUE THREAD

**Issue by eyalfa** [akka/akka#29784]
`statefulMapConcat` and `mapConcat` operators take a function that (eventually) returns an `immutable.Iterable`.
I believe the return type can be relaxed to `scala.collection.IterableOnce` which is already a super class of `immutable.Iterable`.

Doing so will enable providing a function returning an Iterator which is sometimes simpler and introduces a far smaller memory footprint.

Observing `StatefulMapConcat`'s implementations it seems it immediately extracts an iterator out of the returned `Iterable` and in cases or restart (after failure, according to the specified decider) it re-applies the given function.
This combined with `Iterable' extending `IterableOnce' - hence not a breaking change, suggests this change doesn't carry any compatibility issues while extending and simplifying the operators' usage.

**Comment by raboof** [comment]
Sounds reasonable to me, assuming this change would indeed be binary compatible (which I agree I expect it is, since the return type is a generic on the Function type). Worth a double-check though, also with the Java API.

**Comment by eyalfa** [comment]
@cool, I'll sketch a PR and how far it gets us.
I guess there's always the possibility of adding a second set of methods taking different parameter types.

btw, the Java API has slightly different signatures based on `java.lang.Iterable[T]]` and I'm not sure if Java has an equivalent type for `IterableOnce`. so supporting something like this in java may require adding overloads (probably new methods) based on `Iterator`.

**Comment by eyalfa** [comment]
@raboof , there's an issue with scala version 2.12 as it doesn't have the `IterableOnce` trait in the collections library.
is scala still supporting 2.12 builds?

2.12 has `TraveersableOnce` whiuch doesn't cut it as it doesn't have an `iterator` method.

assuming 2.12 is still 'alive' I think the better approach would be adding a couple of new methods, i.e. `statefulMapConcatI[T](f : () => Out => Iterator[T]` (and a similar `mapConcatI` variant.

**Comment by raboof** [comment]
> the Java API has slightly different signatures

Ah yes, it probably doesn't apply there

> is akka still supporting 2.12 builds

Yes, we do (indeed 'formal' support for 2.12 ended in June, but in practice we still support and publish for it).

> I think the better approach would be adding a couple of new methods

Perhaps we can do better: if you import `akka.util.ccompat._`, on 2.12 you will get a type alias converting `IterableOnce` into `TraversableOnce`. Since `Iterable` also extends `TraversableOnce`, that might actually be compatible. It does increase the number of things that need to be tested, though :)

**Comment by eyalfa** [comment]
> > the Java API has slightly different signatures
> 
> Ah yes, it probably doesn't apply there
> 
> > is akka still supporting 2.12 builds
> 
> Yes, we do (indeed 'formal' support for 2.12 ended in June, but in practice we still support and publish for it).
> 
> > I think the better approach would be adding a couple of new methods
> 
> Perhaps we can do better: if you import `akka.util.ccompat._`, on 2.12 you will get a type alias converting `IterableOnce` into `TraversableOnce`. Since `Iterable` also extends `TraversableOnce`, that might actually be compatible. It does increase the number of things that need to be tested, though :)

how does this help me in 2.12? `TravesableOnce` doesn't have an `iterator` method which effectively means its traversal can't be suspended and resumed which is what the `StatefulMapConcat` requires.
it might be possible to pattern match on the traversable-once instance, if its an `Iterator` we're cool, if it's an `Iterable` we're also good, but what if it's another form of traversable which doesn't support the `iterator` method?

wait... `scala.collection.GenTraversableOnce#toIterator` might be the answer! WDUT about that?

**Comment by eyalfa** [comment]
@raboof , what would you suggest regarding javadsl? separate methods? an overload taking a subclass of function.Function?
i.e. something like:

```
trait FunctionReturningIterator[A,B] extends Function[A, Iterator[B]]

def mapConcat[T](f: function.FunctionReturningIterator[Out, java.lang.Iterable[T]]): javadsl.Flow[In, T, Mat]
```

hmm, I see `statefulMapConcat` takes a `Creator` so even if this trick works for `mapConcat` it'd have to be duplicated for `statefulMapConcat`

I think this leads to a separate methods pair in the java dsl, WDUT?

**Comment by raboof** [comment]
> I think this leads to a separate methods pair in the java dsl, WDUT?

I'm not sure there's a strong reason to change the Java side, perhaps it is OK the way it is?

**Comment by eyalfa** [comment]
> > I think this leads to a separate methods pair in the java dsl, WDUT?
> 
> I'm not sure there's a strong reason to change the Java side, perhaps it is OK the way it is?

java can also benefit from this functionality

**Comment by johanandren** [comment]
Let's close this and if there is interest track Java iterable support in a new issue.
