### ISSUE TITLE
Build tool assistence for keeping Akka version in sync

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29791]
We currently have checks at runtime. This ticket is for adding build tool support to override all Akka dependencies to the same version

**Comment by johanandren** [comment]
For maven and gradle we have discussed publishing a "bill of materials", but not sure that helps for sbt projects. Not sure if there currently is any support for generating such a dependency-list-pom from sbt.

**Comment by ignasi35** [comment]
Lagom produces a bill-of-materials (BOM) using some custom sbt code that produces XML.

See https://github.com/lagom/lagom/blob/master/build.sbt#L1395-L1470

**Comment by raboof** [comment]
There has been some previous brainstorming on this topic at https://github.com/lightbend/akka-platform-meta/issues/64

**Comment by ennru** [comment]
For the record: We produce Maven Bill-of-materials (BOM) files for all modules in Akka core per Scala version:
- https://central.sonatype.com/artifact/com.typesafe.akka/akka-bom_2.13
- https://central.sonatype.com/artifact/com.typesafe.akka/akka-bom_2.12
- https://central.sonatype.com/artifact/com.typesafe.akka/akka-bom_3

Our docs show how to use the BOM file from Maven, e.g. see the Maven and Gradle tabs at https://doc.akka.io/docs/akka/current/typed/guide/modules.html#actor-library

This sbt plugin supports consuming BOM files
- https://github.com/heremaps/here-sbt-bom

**Comment by johanandren** [comment]
I also built and published this sbt plugin a couple of years ago: https://github.com/johanandren/sbt-akka-version-check
