### ISSUE TITLE
Document how to compose two (or more) partial Behaviors

### ISSUE THREAD

**Issue by jlprat** [akka/akka#29832]
As per https://github.com/akka/akka/pull/27252 the method `Behavior.orElse` got removed. In that same PR there are some examples on how to successfully compose different Behaviors together.

I think it would be beneficial to document this on the documentation, it would suffice to add the examples present in https://github.com/akka/akka/blob/master/akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala with some explanation grouping them.

**Comment by johanandren** [comment]
Sounds good, for the two first ones (function and partial function composition) at least, not entirely sure we should encourage the interceptor one though. I think that would be a bit of a foot-shooting trap for beginners browsing the docs.

**Comment by jlprat** [comment]
Agree with the Interceptor bit, it might be too much.
I'll try to provide a PR for this in the next days
