### ISSUE TITLE
akka-actor-typed: nested supervision with pipeToSelf

### ISSUE THREAD

**Issue by aherrmann** [akka/akka#29841]
Consider an actor with supervision set up as follows:
```
Behaviors.supervise(
    Behaviors.supervise(actor)
      .onFailure[SpecificException](SupervisorStrategy.stop))
  .onFailure(SupervisorStrategy.restart)
```
It should stop when a `SpecificException` is thrown and restart on any other exception.
This does not seem to work if the exception is thrown after receiving a message from a `pipeToSelf` call. In that case the actor is restarted rather than stopped.
This is the case for `pipeToSelf` called within `Behaviors.setup` as well as for `pipeToSelf` called within `Behaviors.receive`.

**To Reproduce**
I've tried to create a minimal reproduction in the akka test suite. The diff is available [here](https://github.com/akka/akka/compare/master...aherrmann:repro-2.6.10#diff-d6f8c3f2ad0a2ae0ebe86c5878f20c9968bf7514215c99624ac1818c2a3afc74R380). Checkout that [commit](https://github.com/aherrmann/akka/commit/9918478089ec58a0b443e3ba20d0e2ce0ec600ee) and execute the following commands to run the failing test case.
```
$ sbt
akka > project akka-actor-typed-tests
sbt:akka-actor-typed-tests> testOnly **.SupervisionSpec -- -z "support nesting exceptions with different strategies with pipeToSelf"
...
[info] - must support nesting exceptions with different strategies with pipeToSelf *** FAILED *** (123 milliseconds)
[info]   java.lang.AssertionError: expected ReceivedSignal(PostStop), found ReceivedSignal(PreRestart)
...
```

**Expected Behavior**
The stop supervisor should trigger and stop the actor. The test case should pass accordingly.

**Futher Information**
The diff contains a few commented out alternative code paths.
* One that fails as well, calling `pipeToSelf` within `receive` instead of `setup`.
* Two that pass: One using the `Throw` message i.e. not using `pipeToSelf`, another using a broader `.onFailure[RuntimeException]` for the stop supervision strategy. I.e. there seems to be some interplay between the specific type constraint on `.onFailure` and `pipeToSelf`.

I had to add an additional case for `MessageAdaptionFailure` to the `targetBehavior`'s `.receiveSignal` to construct this test case. This was not necessary in the original use-case where the issue occurred, since we don't have a catch-all `receiveSignal` in that case.

**Comment by johanandren** [comment]
Thanks for reporting and the detailed reproducer. Looks like a bug to me.
