### ISSUE TITLE
Serialization verification doesn't verify replies on external ask

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#29851]
The current implementation of serialization verification doesn't exercise de/serialization on replies of an `ask` operation produced from the outside of the ActorSystem.

The de/serialization verification happens when dispatching the message to the actor cell so a reply (e.g a message to respond to an ask) may not be de/serialized if the sender was synthetic.

In general, a message sent back to complete an `ask` works as expected because it's generally combined with `pipeTo`. The problem comes when `ask` is invoked from outside the actor system. In that case, there's no actor to dispatch to. There's only a synthetic ActorRef with a Promise to complete and, in that case, the de/serialization doesn't kick in. 
As a consequence, the serialization verification leads to unverified messages.

**Comment by patriknw** [comment]
We should not improve that utility, since it should be removed. #24623 is more interesting.

**Comment by ignasi35** [comment]
There's no real task to follow-up on this issue since the general plan is to retire the actual feature.
