### ISSUE TITLE
Work pulling pattern: unexpected RequestNext messages

### ISSUE THREAD

**Issue by manuelp** [akka/akka#29854]
Given the following scenario:

* One node
* One producer, with a `WorkPullingProducerController` backed by a durable queue
* One worker

When I submit a (long running) job to the producer, but the worker can't complete the job (for example because it crashes or the actor systems is shutting down and there is no `WorkPullingProducerController` to receive and manage the `ConsumerController.Confirm` message), I see a behavior that seems to me a bug somewhere.

Let's assume that the actor system has been stopped before the running job had the chance to complete. When the underlying process has been stopped, I think the `WorkPullingProducerController` has been already stopped so the possible `ConsumerController.Confirm` is lost. This is the easiest way I could reliably reproduce this behavior.

## Expected behavior
1. The node is restarted
2. The producer restarts, spawing the companion `WorkPullingProducerController`.
3. The worker starts, spawing its `ConsumerController`.
4. The `WorkPullingProducerController`, since it's backed by a durable queue reloads an unconfirmed message. When the worker registers itself as ready since there is an unconfirmed message it's directly sent to that worker. Since there are no other workers, _the producer won't receive any `RequestNext`_ message until the worker completes the pending job.
5. After the worker processed the saved unconfirmed message, the producer received _a single `RequestNext`_.

## Actual behavior
1. The node is restarted
2. The producer restarts, spawing the companion `WorkPullingProducerController`.
3. The worker starts, spawing its `ConsumerController`.
4. **The producer received a `RequestNext` message**
5. The unconfirmed message is delivered to the worker.
6. **Another `RequestNext` message is sent to the producer** (the job is still in progress).

Given:

* The [documentation](https://doc.akka.io/docs/akka/current/typed/reliable-delivery.html#work-pulling).
* The [extensive code sample](https://github.com/akka/akka-samples/tree/2.6/akka-sample-distributed-workers-scala).
* The `WorkPullingProducerController.RequestNext[A]` scaladoc string:
    > The `WorkPullingProducerController` sends `RequestNext` to the producer when it is allowed to send one message via the `sendNextTo` or `askNextTo`. Note that only one message is allowed, and then it must wait for next `RequestNext` before sending one more message.

So, as far as I understand, this should never happen. The producer should receive only one `RequestNext` at a time, new ones should be sent to the producer only when the first one is used to send a reply to the `RequestNext.sendNextTo` `ActorRef` (or `askNextTo`)

For a more in depth description see [this discussion](https://discuss.lightbend.com/t/work-pulling-unexpected-requestnext-messages/7552).

I suspect this could be a bug in Akka. If it's not, I'd like to understand what I'm doing wrong.

**Comment by patriknw** [comment]
Thanks for reporting.

> The producer should receive only one RequestNext at a time, new ones should be sent to the producer only when the first one is used to send a reply to the RequestNext.sendNextTo ActorRef (or askNextTo)

That is correct and would be a bug. I'll look into it but will probably not have time until next week.

**Comment by manuelp** [comment]
Thank you very much.

For the time being in my code I removed the exception in the producer, so that it does not fail (and restarts), but ignores the spurious `RequestNext` messages. Since I noticed that with many jobs to process the producer gets many more `RequestNext` messages than available workers, I figured as a workaround it could work anyway and the producer would get new `RequestNext` messages for the same worker even if previous ones have been ignored.

Unfortunately, even with just one node after some time I start to get dead letters like the following:

```
[INFO] [2020-12-03 12:55:15,668] | [saas-akka.actor.default-dispatcher-15] | a.r.RemoteActorRefProvider$RemoteDeadLetterActorRef: Message [java.lang.Long] to Actor[akka://saas/deadLetters] was not delivered. [15] dead letters encountered. If this is not an expected behavior then Actor[akka://saas/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

Every time with bursts to 100. As far as I can see in the logs all workers are working, but after some restarts some jobs seems to have been losed along the way.

**Comment by manuelp** [comment]
Making some more tests, I noticed something else:

* One node
* Multiple workers
* Sent a bunch of long running (up to 10 seconds) jobs

Increasing the number of workers, after at certain threshold (in my case around 10, maybe this is related to the number of actual cores/threads available?), when I stop the system while some jobs are in progress and restart the system I get persistence errors. For example:

```
[WARN] [2020-12-03 17:17:43,875] | [saas-akka.actor.default-dispatcher-5] | a.a.t.d.WorkPullingProducerController: StoreMessageSent seqNr [32] failed, attempt [1], retrying.
[...]
[ERROR] [2020-12-03 17:22:33,650] | [saas-akka.actor.default-dispatcher-22] | a.a.t.d.WorkPullingProducerController: StoreMessageSentFailed seqNr [60] failed after [10] attempts, giving up.
[ERROR] [2020-12-03 17:22:33,672] | [saas-akka.actor.default-dispatcher-4] | a.a.t.s.TimerScheduler: StoreMessageSentFailed seqNr [60] failed after [10] attempts, giving up.
java.util.concurrent.TimeoutException: StoreMessageSentFailed seqNr [60] failed after [10] attempts, giving up.
	at akka.actor.typed.delivery.internal.WorkPullingProducerControllerImpl.receiveStoreMessageSentFailed(WorkPullingProducerControllerImpl.scala:665)
	at akka.actor.typed.delivery.internal.WorkPullingProducerControllerImpl.$anonfun$active$19(WorkPullingProducerControllerImpl.scala:626)
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:152)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:57)
	at akka.actor.typed.internal.WithMdcBehaviorInterceptor.aroundReceive(WithMdcBehaviorInterceptor.scala:78)
	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:85)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:129)
	at akka.actor.typed.internal.adapter.ActorAdapter.$anonfun$aroundReceive$2(ActorAdapter.scala:99)
	at akka.actor.typed.internal.adapter.ActorAdapter.$anonfun$aroundReceive$2$adapted(ActorAdapter.scala:95)
	at akka.actor.typed.internal.adapter.ActorAdapter.withSafelyAdapted(ActorAdapter.scala:189)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:95)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

I don't know if those errors are related to this issue. I apologize if they are not.

**Comment by patriknw** [comment]
@manuelp You could try increasing config `akka.reliable-delivery.producer-controller.durable-queue.request-timeout`. It's by default 3 seconds.

**Comment by manuelp** [comment]
The fix seems to work, but I noticed two things.

## Dead letters

I still get _dead letter warnings_:

```
[INFO] [2020-12-09 15:21:04,878] | [saas-akka.actor.default-dispatcher-5] | a.r.RemoteActorRefProvider$RemoteDeadLetterActorRef: Message [java.lang.Long] to Actor[akka://saas/deadLetters] was not delivered. [77] dead letters encountered. If this is not an expected behavior then Actor[akka://saas/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

Even with just one node and one worker, despite setting `akka.reliable-delivery.producer-controller.durable-queue.request-timeout` up to 30 seconds. It seems that I get those warnings when workers are occupied running their job for more than 10-15 seconds or so. The workers execute the job synchronously but on a separate thread pool than the one used by actors for message dispatches.

## Consumer window?
Testing the system with multiple nodes and restarts, after a certain point I noticed that some workers were idle even if there were still job to execute. Maybe this is due to consumers' flow control window? 

There is a way to configure the mechanism so that a new `RequestNext` for a given worker is sent to the producer only when the previous message for that worker has been completed? Maybe by setting `akka.reliable-delivery.consumer-controller.flow-control-window` to 1 or 0?

**Comment by patriknw** [comment]
ok, I have created a separate issue for that https://github.com/akka/akka/issues/29878

**Comment by manuelp** [comment]
OK, thank you.
