### ISSUE TITLE
Include name attribute in GraphStageLogic to string

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29852]
For exceptions etc it would be nice if the default toString could include the name attribute if set, together with the impl class name, to help identify which instance/flow it is from.

**Comment by nitikagarw** [comment]
Hi @johanandren, 
I looked through the code for the fix, we need to override the `toString` method of this [class](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L295). 
If that's correct, Can I please pick this issue? 
I will need some help with the exact string that we want to form. 
Example: `${implName}-${nameAttribute}-super.toString` ?

**Comment by johanandren** [comment]
I think since most if not all built in operators has a name attribute defined going with just the attribute when present and only class (like now) when no name attribute set (for a custom operator) makes sense. No need to include `super.toString`.

Since a custom GraphStageLogic can have its own toString it would also be good to look through if there are any already and if having a better default makes them superflous.

Please go ahead if you want to PR this! 👍

**Comment by nitikagarw** [comment]
@johanandren I have opened https://github.com/akka/akka/pull/29877 with the changes. Please review the PR.

**Comment by johanandren** [comment]
This will have added benefit from #29874 with lamda source and line numbers for operators such as map/filter etc.
