### ISSUE TITLE
make "durable" an option per key in distributed data

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#29864]
If I understand correctly, the durable option is global for all keys, which is configured in the configuration file.

I have a use case where some keys need durable storage and some don't. 
It makes sense to allow users to specify on the key level whether to use the durable storage or not.

**Comment by patriknw** [comment]
That’s already possible:
https://github.com/akka/akka/blob/8b71fac817f2743e47e19e0989dc047ff1f4f28d/akka-distributed-data/src/main/resources/reference.conf#L83-L86

**Comment by Zhen-hao** [comment]
@patriknw thanks! 
I accept this as a solution. 
I still hope we can do it in code, say add a parameter to the `Key` constructor.

**Comment by hepin1989** [comment]
@Zhen-hao a PR is welcome

**Comment by patriknw** [comment]
Thanks for the suggestion, but I don't think it would be good to make it possible to specify programmatically via the Key. That would open up a lot of questions about how dynamic that setting is, such as:
* is a Key with durable the same as a Key without durable?
* is it only durable for this operation?
* will it be durable when receiving updates from another node that haven't defined it as durable in the Key?
* ...

**Comment by Zhen-hao** [comment]
@patriknw good points.
I had actually thought about your last point. My observation is that the "durable" setting is itself a CRDT on the key. to make it safer, we can make it `case class Durable(enable: Boolean, timestamp: Long)` where `timestamp: Long` can also be `version: Int`.
so, on your first point, the answer is yes. but we need to add the above CRDT as a kind of metadata of the key. 

The benefit of this approach is to avoid the common situation where programmers add/change d-data keys in Scala code but forget to update the configuration file accordingly, which is also hard to discover during code reviews.
