### ISSUE TITLE
StashBufferImpl: wrong message order when invoke unstashAll recursive

### ISSUE THREAD

**Issue by youenough** [akka/akka#29863]
mailbox message order:
m1
m2
m3
m4
m5
m6
m7
...

startBehavior
m1 -- StashBuffer.stash
m2 -- StashBuffer.stash
m3 -- StashBuffer.stash
m4 -- StashBuffer.stash
m5 -- StashBuffer.stash
m6 -- StashBuffer.unstashAll(behaviorB)

behaviorB
m1 -- StashBuffer.stash
m2 -- StashBuffer.stash
m3 -- StashBuffer.unstashAll(behaviorC)
m4 -- notProcessButInStashBuffer
m5 -- notProcessButInStashBuffer

behaviorC
m4 --
m5 --
m1 --
m2 --

in `behaviorC` `m4` `m5` was before `m1` `m2`, the original order of messages has been changed.

**Comment by johanandren** [comment]
It would be good if you could share a code snippets that repeats this scenario, thanks

**Comment by patriknw** [comment]
This is how the StashBuffer is implemented. By design.
When you stash m1 the second time it will be appended to the end of the buffer.
When you unstashAll(behaviorC) m3 has still not been processed by the previous unstashAll and are therefore considered first in the buffer.

You could maybe create a new StashBuffer if you want another order.

```
startBehavior
m1 -- buffer1.stash
m2 -- buffer1.stash
m3 -- buffer1.stash
m4 -- buffer1.stash
m5 -- buffer1.stash
m6 -- 
  create buffer2
  buffer1.unstashAll(behaviorB)

behaviorB
m1 -- buffer2.stash
m2 -- buffer2.stash
m3 -- 
  buffer1.foreach(buffer2.stash)
  buffer2.unstashAll(behaviorC)
```

**Comment by youenough** [comment]
Thank you for your reply
Is it possible to integrate this behavior into `StashBufferImpl` in the future?
Some actors need to handle a lot of request-response type messages, so it's too much of a psychological burden to worry about recursion every time `unstashAll` is needed when using the FSM. What's more, it's not always easy to find out when FSM has too much Behavior.
