### ISSUE TITLE
Akka get context with Behaviors.withTimers

### ISSUE THREAD

**Issue by politrons** [akka/akka#29897]
Using **Behaviors.withTimers** any idea how can we obtain the context, to use the **context.log** of Akka?

Normally I use when I define the Behavior with 

`    Behaviors.setup { context =>
`
But with 

`    Behaviors.withTimers
`
It seems it cannot be combined. 

Any suggestion? 

Regards

**Comment by jlprat** [comment]
This page in the documentation will help you: https://doc.akka.io/docs/akka/current/typed/style-guide.html#nesting-setup

```
Behaviors.setup[Command](context =>
    Behaviors.withStash(100)(stash =>
      Behaviors.withTimers { timers =>
        context.log.debug("Starting up")

        // behavior using context, stash and timers ...
      }))
```

**Comment by politrons** [comment]
Great it was because I was not passing the type in the `Behaviors.setup` but in the` Behaviors.withTimers[T]`

Thanks
