### ISSUE TITLE
No alternative for RemotingLifecycleEvent in Artery

### ISSUE THREAD

**Issue by makesh91** [akka/akka#29892]
We use akka Classic Remoting and have subscribed to the RemotingLifecycleEvent.
Now we are in process of migrating to Artery, but we see only the below information for that class
"Classic remoting is deprecated, use Artery"

We can't see any alternate events to subscribe in Artery  .i.e. AssociationErrorEvent

Please assist.

Regards,
Makesh

**Comment by johanandren** [comment]
There are no corresponding events published in Artery, what is the use case you have for observing them?

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for almost 3 years.
Should this issue be closed?

**Comment by patriknw** [comment]
👍
