### ISSUE TITLE
MergeSequence race condition

### ISSUE THREAD

**Issue by Marcus-Rosti** [akka/akka#29908]
re: @jroper 

I think there's a race condition in MergeSequence although I can't quite put my finger on it.

I have this Source of sequences 
```scala
Source(
  Seq(a, b, c, d, e),
  Seq(a, b, c, d, e),
  Seq(a, b, c, d, e)
)
```
I want to make an http call for consonants but skip vowels.
I split the source into subflows for each sequence and then map this stage below.

```scala
GraphDSL.create() {
...
val httpFlow = http.cachedConnectionPool 
val partition = b.add(Partition[...](2, isVowel)
val merge = b.add(MergeSequence[...](getIndex)
partition.out(0) ~> httpFlow ~> merge
partition.out(1) /*skip http*/ ~> merge
        FlowShape(partition.in, merge.out)

}
```

So I've mocked everything up and written a test but the test is very flaky in that I'll intermittently get the IllegalStateException for all input ports have pushed or are complete.

I'm curious what your thoughts are

**Comment by Marcus-Rosti** [comment]
I think it's because 
```
val httpFlow = http.cachedConnectionPool 
```
doesn't necessarily return req -> resp in order

**Comment by raboof** [comment]
> I think it's because
> 
> ```
> val httpFlow = http.cachedConnectionPool 
> ```
> 
> doesn't necessarily return req -> resp in order

`cachedConnectionPool` indeed doesn't preserve the ordering. Perhaps you could use a `statefulMapConcat` to put the elements back in order before passing them to the `MergeSequence`? (obviously that would introduce head-of-line blocking, but if you want the elements to remain ordered then that is essentially unavoidable)

**Comment by johanandren** [comment]
Closing this as it seems more like a question than a bug or feature request. Please use the forums over at https://discuss.akka.io for asking questions (and perhaps re-ask this again if you are stuck) or let us know if you have a repeater without the re-ordering `cachedConnectionPool` involved and we'll re-open this. Thanks!
