### ISSUE TITLE
add Behaviours.withTimers support to BehaviorTestKit 

### ISSUE THREAD

**Issue by eyalfa** [akka/akka#29900]
BehaviorTestKit currently relies on `akka.actor.typed.internal.TimerSchedulerImpl` in order to provide a `TimerScheduler', this impl relies on the actual scheduler in the actor system which is not present for stubbed actor system hence no support for timers.
I suggest introducing a stubbed implementation of `TimerScheduler' that introduces an effect similar (if not the same) to the exiting `Effect.Scheduled`, I also suggest that cancelling a timer will introduce a `Cancelled` effect.
Introducing this functionality will enable tests to simulate and fully control timers related behaviour.

in order to achieve this:
1. provide an 'effectfull' `TimerScheduler' implementation.
2. either introduce a new `Effect` class or extend the existing `Effect.Scheduled`.
3. introduce a `Cancelled` effect
4. override akka.actor.typed.internal.ActorContextImpl#timer in akka.actor.testkit.typed.internal.EffectfulActorContext

this is somewhat related to #24686 but introduces a slightly different approach to the issue.

**Comment by eyalfa** [comment]
CC: @johanandren

**Comment by johanandren** [comment]
Sounds good 👍
