### ISSUE TITLE
[Docs] Provide example for Consistent Hashing Typed Router

### ISSUE THREAD

**Issue by jlprat** [akka/akka#29919]
Similarly to the Classic Routing docs, where there is an example for such routing strategy: https://doc.akka.io/docs/akka/current/routing.html#consistenthashingpool-and-consistenthashinggroup.

It would be nice for documentation readers to find a descriptive example on how to use the Consistent Hashing strategy.

**Comment by johanandren** [comment]
Sounds good, but not super important.

One thought is that it would be somewhat strange to have that but not for the round robin and random ones (which are generally more useful) though.

**Comment by jlprat** [comment]
I didn't mention the RoundRobin and Random ones, because I thought they weren't controversial, meanwhile with the consistent hashing some might disagree.

**Comment by johanandren** [comment]
Yeah, maybe they are obvious enough to not need examples.

**Comment by jlprat** [comment]
Technically, Pool uses RoundRobin and Group Random so they do have an example :laughing:

**Comment by patriknw** [comment]
To clarify, the example we are looking for would cover `withConsistentHashingRouting` in `PoolRouter` and `GroupRouter`. Maybe it's not necessary to have two examples, but just one for `GroupRouter` and mention in the text that similar is supported by the `PoolRouter`.

**Comment by jlprat** [comment]
Would an example like the one in classic docs suffice? Or should it be something more elaborated?

**Comment by johanandren** [comment]
I think even simpler than the classic sample would be good, a single message type and logging in the routee or something like that.

**Comment by octonato** [comment]
Done in #30036
