### ISSUE TITLE
enhance Routers.pool such that it supports broadcasting messages to all children

### ISSUE THREAD

**Issue by eyalfa** [akka/akka#29924]
I propose enhancing `PoolRouter` with a user provided predicate that determines whether a certain message should be broadcasted to all children or not.
when the predicate is not provided the pool behaves normally - messages are dispatched to one of the workers according to the pools policy (round-robin, random).
when provided, the pool will invoke this predicate on each incoming message, messages for which the predicate returned `false` are dispatched to one of the workers. messages for which the predicate returned `true` will be dispatched to all children.

**Comment by eyalfa** [comment]
cc: @johanandren

**Comment by johanandren** [comment]
Sounds like a great idea. 👍

**Comment by eyalfa** [comment]
I'll sketch a PR for this
