### ISSUE TITLE
failed: WorkPullingWithEventSourcedProducerQueueSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29949]
https://jenkins.akka.io:8498/job/akka-multi-node/4332/testReport/junit/akka.persistence.typed.delivery/WorkPullingWithEventSourcedProducerQueueSpec/WorkPulling_with_EventSourcedProducerQueue_must_deliver_messages_after_full_producer_and_consumer_restart/

Some kind of race condition in the test that was introduced by https://github.com/akka/akka/pull/29873

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8395/testReport/junit/akka.persistence.typed.delivery/WorkPullingWithEventSourcedProducerQueueSpec/WorkPulling_with_EventSourcedProducerQueue_must_deliver_messages_after_full_producer_and_consumer_restart/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8403/testReport/junit/akka.persistence.typed.delivery/WorkPullingWithEventSourcedProducerQueueSpec/WorkPulling_with_EventSourcedProducerQueue_must_deliver_messages_after_full_producer_and_consumer_restart/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8406/testReport/junit/akka.persistence.typed.delivery/WorkPullingWithEventSourcedProducerQueueSpec/WorkPulling_with_EventSourcedProducerQueue_must_deliver_messages_after_full_producer_and_consumer_restart/
