### ISSUE TITLE
FishingOutcomes.continue() cannot be used in Java code due to reserved word

### ISSUE THREAD

**Issue by AustinHash** [akka/akka#29951]
"continue" is a reserved word in Java. As such any attempt to use FishingOutcomes.continue() from akka.actor.testkit.typed.javadsl.FishingOutcomes in Java code will cause compile failures.

Current workarounds are to use FishingOutcomes.continueAndIgnore() (prevents showing a list of processed messages in the fishForMessage failure output) or reflection to invoke the method (nasty but gives desirable behavior).

**Comment by johanandren** [comment]
Ouch, thanks for reporting! Would you be up for PR:ing a fix?

**Comment by hepin1989** [comment]
ContinueAndCollect?

**Comment by Captain1653** [comment]
How can it be fixed? I can try. Can we rename the method, right? We don't need to keep backward compatibility because it didn't compile in java. @johanandren  Am I wrong? Which name should be preferable?

**Comment by johanandren** [comment]
`continueAndCollect` sounds good to me.
