### ISSUE TITLE
Akka SBR acting on decision at every tick

### ISSUE THREAD

**Issue by DennisVDB** [akka/akka#29950]
During rolling updates it happens that some nodes are detected as unreachable while being in the exiting state. When that happens, the SBR is triggered every tick (1 second) until the unreachable members are removed. In our case it acts on the decision 3 times in a row.

It happens only when the unreachable nodes are exiting:
`SBR took decision AcquireLeaseAndDownUnreachable(0 days) and is downing [], [1] unreachable of [3] members`.

Is this an expected behaviour or should the `stableDeadline` also be reset when there are `nodesToDown` is empty in `actOnDecision` in order to allow the leader the time to remove the unreachable+exiting nodes?

**Comment by patriknw** [comment]
@DennisVDB can you share some more complete Akka logs? I would expect that after the first downing of the unreachable SBR shouldn't repeat that action if the member status was changed to Down.

Even if it repeated the same down action on members that are already Down that would  be an idempotent operation, but SBR should still avoid that to reduce noise in the logs.

**Comment by DennisVDB** [comment]
Here are the logs https://gist.github.com/DennisVDB/053f941c3f025150dffbe83a6650230c

> Even if it repeated the same down action on members that are already Down that would be an idempotent operation, but SBR should still avoid that to reduce noise in the logs.
It doesn't down any node in this case as the unreachable node is "exiting". The SBR isn't doing anything bad, it's just a bit noisy in the logs for no good reason. The decision is essentially a noop.

**Comment by DennisVDB** [comment]
@patriknw addendum on my first message: "During rolling updates it happens that some nodes are detected as unreachable while being in the exiting state". What I'm observing in the logs is not Akka detecting the exiting node as unreachable but the SBR interpreting an exiting member as unreachable [1]. 

Is there a reason to interpret downed and exiting members as unreachable in the SBR? Can't they be ignored completely (at the end the SBR never ends doing anything with members in that state) as the leader will remove then independently of their reachability?

[1] https://github.com/akka/akka/blob/146944f99934557eac72e6dc7fa25fc6b2f0f11c/akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala#L271
[2] https://github.com/akka/akka/blob/146944f99934557eac72e6dc7fa25fc6b2f0f11c/akka-cluster/src/main/scala/akka/cluster/sbr/SplitBrainResolver.scala#L472

**Comment by patriknw** [comment]
I think you are right that this should be improved. It was intentionally introduced in a bug fix so I have to dig deeper into what the reason was. A comment from that [PR in private repo](https://github.com/lightbend/akka-enhancements/pull/441):

> I agree it does not make sense to Down nodes that are already Exiting.
>
> However, the current/previous implementation keeps considering them Up and reachable even when they they have been observed as being unreachable already. That leads to incorrect/inconsistent downing decisions, so that is not good either.
>
> I think we should mark them as unreachable here, but indeed add a safeguard after making the downing decision to make sure we leave Exiting nodes alone.
