### ISSUE TITLE
Akka stream 2.6.11 memory leak?

### ISSUE THREAD

**Issue by markarasev** [akka/akka#29977]
I'm dumping a database to a file using akka-stream and since I upgraded to 2.6.11 memory grows indefinitely while the stream is running. 

When the stream is finished, a call to the garbage collector effectively cleans-up the memory to its anterior state (before the stream was run), but while its running it can't stay at a stable level.

Downgrading to akka 2.6.10 solved the problem.

Here are some screenshots of runs with `-Xmx1G`:

Akka 2.6.11 (ends in out of memory exception):
![before](https://user-images.githubusercontent.com/3638968/105739489-71623180-5f38-11eb-9edf-ef005e643a53.png)

Akka 2.6.10 (ends properly in approx. 12 minutes):
![after](https://user-images.githubusercontent.com/3638968/105739503-77581280-5f38-11eb-9743-1735fa66f39d.png)

To properly run the stream I need more than 5GB of memory in 2.6.11 while I need only 250MB in 2.6.10.

Unfortunately I can't come up with a reproducer soon, but if some additional metrics are needed I can try to provide them. 

For instance, here's the top 5 classes by memory footprint in 2.6.11:
 - `byte[]` (only one that is also in 2.6.10 top 5)
 - `Object[]`
 - `scala.collection.immutable.$colon$colon`
 - `java.util.concurrent.atomic.AtomicReference`
 - `akka.stream.impl.fusing.GraphInterpreter$Connection`

And if I zoom on `scala.collection.immutable.$colon$colon`:
<img width="927" alt="Capture d’écran 2021-01-25 à 17 47 34" src="https://user-images.githubusercontent.com/3638968/105741606-ca32c980-5f3a-11eb-9cc9-9bf77d92766a.png">

**Comment by markarasev** [comment]
Just ran into https://github.com/akka/akka/issues/29966 and https://github.com/akka/akka/pull/29967, this issue seems to be a duplicate since my graph uses substreams too.

**Comment by USHPINDER** [comment]
@markarasev  We are facing same issue with our application...Can you let us know if you able to resolve it?

**Comment by markarasev** [comment]
This issue was related to Akka 2.6.11, upgrading Akka solved the issue (I use 2.6.20).

**Comment by USHPINDER** [comment]
@markarasev  We are using 2.7.0...Still we are facing problem. Can you suggest something?

By doing a quick memory leak check we see below two possible memory leaks:

Suspect 1 | 250,481 instances of "akka.persistence.cassandra.journal.TagWriters$TagWritersSession", loaded by "jdk.internal.loader.ClassLoaders$AppClassLoader @ 0x70497f610" occupy 711,363,232 (64.01%) bytes.

Suspect 2 | 250,524 instances of "akka.actor.ActorCell", loaded by  "jdk.internal.loader.ClassLoaders$AppClassLoader @ 0x70497f610" occupy  123,229,864 (11.09%) bytes.

**Comment by markarasev** [comment]
I did not face this issue since I upgraded to 2.6.12 (currently using 2.6.20). Also, I don't use akka-persistence nor Cassandra so perhaps your problem is a new / another one and related to these components? If you can't find any related ticket, I'd suggest to create one.

**Comment by USHPINDER** [comment]
@markarasev  Thank you for the response.

Yes..We are using akka persistence with Cassandra along with Sharding...

I have opened a issue https://github.com/akka/akka/issues/32013 but Can you suggest something?
![image](https://github.com/akka/akka/assets/90985835/98fec0e9-b8b3-4694-a943-720305df1603)

**Comment by USHPINDER** [comment]
@markarasev We have tried using 2.8.3 also...yet same problem.

Adding some more links https://stackoverflow.com/questions/76667809/akka-2-7-0-memory-leak
