### ISSUE TITLE
ActorRef.! for Scala 3

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29985]
The implicit for `!` isn't  automatically in scope with Scala 3. It requires
```
import akka.actor.actorRef2Scala
```

which isn't nice because `!` is the most essential method (together wiith `tell`) of an `ActorRef`.

The name `actorRef2Scala` is also rather cryptic.

Perhaps we could add an explicit `!` to `ActorRef` instead? If that would be difficult to add in a binary compatible way for 2.12 and 2.13 we could have separate ActorRef source for Scala 3.

**Comment by johanandren** [comment]
I think I said it in a comment already, but👍 on explicit `!` method on `ActorRef` for Scala 3.

**Comment by smarter** [comment]
If you're worried about how `!` will appear from Java's point of view, note that you can use `@targetName` to give it whatever bytecode name you want: https://dotty.epfl.ch/docs/reference/other-new-features/targetName.html
