### ISSUE TITLE
Give BehaviorTestKit-spawned actors access to a real configuration

### ISSUE THREAD

**Issue by leviramsey** [akka/akka#29994]
It's reasonably common for actors to leverage configuration via `context.system.settings.config` (which avoids every actor/class doing its own calls to `ConfigFactory.load`; this trick was taught to me by an ELE on a consulting engagement some years ago :) ).  When run by the `BehaviorTestKit`, however, `context.system.settings.config` is a config that's solely the `reference.conf` files from the classpath.

For testing a behavior in full isolation, this is fine: a pattern of

    def behaviorFor(fixture: Fixture, state: State): Behavior[Command] = ???

    def apply(...): Behavior[Command] =
      Behaviors.setup { ctx =>
        // assemble values from config etc., build into a fixture/state instance
        behaviorFor(...)
      }

lets you build fixtures and states in your test (maybe even using property-based testing...) and build the behavior under test with `behaviorFor`.

This gets complicated when the behavior under test spawns another actor defined with this pattern: the `spawn` will be via `apply`, which will pull in a config which is unlikely to be suitable (and if you want things to fail-fast on bad config, the spawn itself will probably fail)

In asynchronous testing, the `ActorTestKit`'s `ActorSystem` loads `application-test.conf`, so it makes sense (to me) to have `BehaviorTestKit`'s `ActorSystemStub` do likewise.

**Comment by johanandren** [comment]
I think both making the behavior testkit pick up `application-test.conf` (although a bit scary because will likely break some user tests) and to provide a way to give a specific `Configuration` to a `BehaviorTestKit` as returned by the stubbed actorsystem settings/config makes sense.

**Comment by eyalfa** [comment]
@johanandren , do u think the right way to go is to change the default behaviour (picking reference cfg => picking test cfg) or alternatively:
keep the existing behaviour and add parameterized constructors and factories that allows users to inject additional configuration ?

I thins adding the parameterized constructors and factories are required anyway, the open question is about the default behaviour

**Comment by eyalfa** [comment]
furthermore, `akka.actor.testkit.typed.internal.StubbedActorContext#spawnAnonymous` and `akka.actor.testkit.typed.internal.StubbedActorContext#spawn` currently (indirectly) create new stubbed actor systems. doesn't it make more sense to use the same one for spawned actors as well? this seems to better model real world scenarios.

**Comment by eyalfa** [comment]
another issue, `ActorSystemStub` loads the reference configuration using: `ConfigFactory.defaultReference(classLoader)`.
this looks up reference.conf files in the given class loader which may be different than the one used to load the test-suite class, hence it may not load reference configuration for some of the tested classes. 
TypesafeConfig provides a better default for this when **not** providing a class loader (it relies on the context class loader which is usually the system class loader).

**Comment by johanandren** [comment]
I think the correct testkit behavior would be to load `application-test.conf` so that it aligns with the typed testkit, however, that could break existing user tests so I'm not entirely sure it's worth changing that in a patch release.

Adding some way to explicitly inject config could be done without breakage so doing that as a first separate PR would be a good idea.
