### ISSUE TITLE
EventSourcedBehavior logging on behalf of users

### ISSUE THREAD

**Issue by octonato** [akka/akka#30005]
The `EventSourcedBehavior` internal classes have a few logs in debug level that uses the logger defined for the user behavior. 

For instance, the logger for the shopping cart sample will be `shopping.cart.ShoppingCart$`. 

That's the same logger that will be available for users when they use 

```scala
Behaviors.setup { context =>
	context.log.debug("starting behavior...")	 
	EventSourcedBehavior ...
}
```

It would be better if we had another logger for the Akka internal logging. Something like: `shopping.cart.ShoppingCart$Internal`.

An alternative is to add a flag to enable/disable the internal logging, but I'm less convinced by this as it increases the amount of tweaks needed. 

Enabling/disabling a logger with 

```xml
<logger name="shopping.cart.ShoppingCart$Internal" level="DEBUG" />
```

is the standard, so better to introduce a new logger, IMO.

**Comment by patriknw** [comment]
I think a separate logger is good. Could be more difficult to correlate those logs with the actor, but I think we already have rather much additional info in MDC for EventSourcedBehavior.
