### ISSUE TITLE
failed: ClusterShutdownSpec - ReadyForShutdown

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30026]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8480

```
[info] [JVM-2] - should prepare for shutdown (on node 'second', class akka.cluster.ClusterShutdownSpecMultiJvmNode2) *** FAILED *** (9 seconds, 927 milliseconds)
[info] [JVM-2]   members: TreeSet(Member(akka://ClusterShutdownSpec@localhost:41913, Up), Member(akka://ClusterShutdownSpec@localhost:42773, Up), Member(akka://ClusterShutdownSpec@localhost:45403, Up)) Up did not equal ReadyForShutdown (ClusterShutdownSpec.scala:53)
[info] [JVM-2]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-2]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
[info] [JVM-2]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6860)
[info] [JVM-2]   at akka.cluster.ClusterShutdownSpec.$anonfun$new$7(ClusterShutdownSpec.scala:53)
[info] [JVM-2]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[info] [JVM-2]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[info] [JVM-2]   at akka.cluster.ClusterShutdownSpec.withClue(ClusterShutdownSpec.scala:33)
[info] [JVM-2]   at akka.cluster.ClusterShutdownSpec.$anonfun$new$6(ClusterShutdownSpec.scala:53)
```

**Comment by patriknw** [comment]
Similar in ClusterShardingPreparingForShutdownSpec https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8479

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8478
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/8070
https://jenkins.akka.io:8498/job/akka-nightly-2.13/808
https://jenkins.akka.io:8498/job/akka-multi-node/4358
and several more

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8486/consoleText
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8485/consoleText
and more

**Comment by johanandren** [comment]
This is failing pretty much all nightlies, since we merged the cluster shutdown. @chbatey can you look into it?

**Comment by patriknw** [comment]
He is out today, so you or I should probably look into it today

**Comment by johanandren** [comment]
I'll pick it up then!

**Comment by chbatey** [comment]
Doh, I didn't check the repeat job after the i pushed the last review feedback and I am not getting emails from jenkins for some reason
