### ISSUE TITLE
Extend GroupedWeightedWithin to accept maxWeight and maxNumber simultaneously

### ISSUE THREAD

**Issue by alex-ninja** [akka/akka#30020]
### Request
Add capability to group elements by both _max weight_ and _max number_ of elements simultaneously to `GroupedWeightedWithin`.

### Proposed implementation
Extend capabilities of `GroupedWeightedWithin` class to accept both `maxWeight` and `maxNumber`, add the corresponding method to `Flow`:
```scala
def groupedWeightedWithin(maxWeight: Long, 
                          maxNumber: Int, 
                          d: FiniteDuration)(costFn: Out => Long): Repr[immutable.Seq[Out]] =
    via(new GroupedWeightedWithin[Out](maxWeight, maxNumber, costFn, d))
```
and update _javadsl_ classes to expose this functionality to Java API.

### Context
The use case that I struggle with is pushing data to _AWS Kinesis Data Streams_. I use _Akka Streams_ to prepare batches for sending data to _Kinesis Data Streams_ via `PutRecords` API. The API has a [limitation](https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html) to accept batches of at most 500 elements and 5 MB. The current implementation does not allow to handle these requirements out of the box (I can whether limit by number or by weight of elements). As a workaround, I had to implement this functionality manually. It has been working fine for me for a few months and now I want to contribute the changes.

### Implementation
I have the implementation in place and I would be happy to raise a PR if the idea is approved.

**Comment by alex-ninja** [comment]
@johanandren @ennru 
Gentlemen, could you, please, check this issue and let me know if the idea makes sense to you.

**Comment by johanandren** [comment]
Sorry for the delay, busy days. I think this could be a nice addition.
