### ISSUE TITLE
Copy instead of go to snippet

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30045]
Heard this complaint yesterday. The top right icon is typically copy-code but we have go to github source.

@johanandren Do you think this is worth fixing, and would you know how?

**Comment by johanandren** [comment]
I don't have an opinion but I can sure look into changing that.

**Comment by patriknw** [comment]
See also https://github.com/akka/akka-paradox/issues/18

**Comment by johanandren** [comment]
If this is good enough I'll do the dance of PR:ing a change to paradox, paradox-theme-akka and finally Akka.

<img width="706" alt="Screenshot 2021-02-18 at 14 43 52" src="https://user-images.githubusercontent.com/666915/108365753-dafff380-71f7-11eb-99aa-eb73fb98cbd0.png">

**Comment by patriknw** [comment]
That looks great to me. Some may prefer icons but this is good to me.
FYI Richard is adding similar copy functionality for Antora https://github.com/lightbend/antora-supplemental-ui-lightbend-theme/issues/25

**Comment by ignasi35** [comment]
> That looks great to me. Some may prefer icons but this is good to me.

We can add icons later. Plus, the icons we had were confusing so moving to text will be helpful.
