### ISSUE TITLE
Mock Scheduler for BehaviorTestKit

### ISSUE THREAD

**Issue by leviramsey** [akka/akka#30047]
It should be possible to implement a mock scheduler for `BehaviorTestKit`-run behaviors with an API along the lines of:

```
val tk = BehaviorTestKit(someBehavior)
tk.run(someMsg)  // handler for this does something which schedules a task
tk.advanceClockBy(10.seconds)  // scheduled tasks within the next 10 billion nanos happen
```

This should, among other things, enable the `BehaviorTestKit` to test the ask pattern along the lines of:

```
val askTarget = TestInbox[TargetCmd]()
val someBehavior: Behavior[Command] = ???  // behavior that can ask askTarget.ref
val tk = BehaviorTestKit(someBehavior)
tk.run(someMsg)  // handler asks askTarget.ref
// Assert things about the ask of askTarget and send response
tk.selfInbox.expectMessage(expectedSuccessResponse)

// alternatively, to test timeout case
val tk = BehaviorTestKit(someBehavior)
tk.run(someMsg)
tk.advanceClockBy(longerThanAskTimeout)
tk.selfInbox.expectMessage(expectedFailureResponse)
```

Thoughts, or is this deeply impractical for some reason not yet apparent to me?

**Comment by johanandren** [comment]
Some previous discussions and related tickets: 
* #24686
* #25709
* #24731
* #25391

My personal opinion is that such support in BehaviorTestKit is going to far away from synchronous/single thread behavior unit testing and becomes something that is close enough to async that it is better tested with the ActorTestKit.

**Comment by leviramsey** [comment]
Addressing #25709 is the main motivation for this.  I don't think that validating that an ask was initiated in response to a message falls outside of `BehaviorTestKit`'s scope (I'd argue it's more in-scope than spawning a child actor, which oddly enough, is what one is likely to do as part of working around this limitation).

I'd been debating whether it made more sense to provide a mock scheduler or to reify the ask as an effect, so I'll close this as a duplicate of #25709
