### ISSUE TITLE
Extend the info when ManifestInfoCheck fails

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30044]
The ManifestInfo check displays an error message that's partially helpful: (https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/util/ManifestInfoSpec.scala#L19-L21):

```
        "You are using version 2.6.4 of Akka, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. " +
        "You can solve this by adding an explicit dependency on version 2.6.4 of the [akka-persistence, akka-cluster] artifacts to your project. " +
        "See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed")
```

That output is the expectation when the input to the manifest info check is:

```
        "akka-actor" -> new ManifestInfo.Version("2.6.4"),
        "akka-persistence" -> new ManifestInfo.Version("2.5.3"),
        "akka-cluster" -> new ManifestInfo.Version("2.5.3"),
```

Instead, the output could detail the name and version of all artifacts considered in the check:

```
        "Detected version 2.6.4 of Akka, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. " +
        "You can solve this by adding an explicit dependency on version 2.6.4 of the [akka-persistence, akka-cluster] artifacts to your project. " +
        "Here's a complete collection of detected artifacts: (2.6.4 -> [akka-actor]), (2.5.3 -> [akka-persistence, akka-cluster])." +
        "See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed")
```

This is helpful when the ~oldest~ _highest_ version is the undesired one but was brought in transitively. In that case users will have to solve that in some other way (downgrading the dependency that brought it the oldest akka artifact).

PS: It's also helpful for maintainers testing with nightly builds and fine-tuning builds. ;-)

**Comment by raboof** [comment]
> This is helpful when the oldest version is the undesired one

You mean the newest? I'm not sure I understand how it helps.

Leaving out this information was kind of intentional, since we observed rather many people misinterpret the message and try to downgrade to the older version (or ask/wait for dependencies to update their transitive versions).

**Comment by johanandren** [comment]
I also think the current is good and says just enough about what is wrong

**Comment by ignasi35** [comment]
> You mean the newest? I'm not sure I understand how it helps.

I meant _highest_. Fixed the description.

**Comment by ignasi35** [comment]
> Leaving out this information was kind of intentional, since we observed rather many people misinterpret the message and try to downgrade to the older version (or ask/wait for dependencies to update their transitive versions) - where we'd basically always prefer them to upgrade to the newer version instead.

I think that's a problem of copy, then. IMHO the message should provide as much information as possible and the documentation linked should include options so the user can decide if they want to upgrade to highest or force a particular version.


In my current issue, I'm trying to list all existing versions mixed on my classpath. I _already_ know which is the highest. Unfortunately, I can't use any build tools like `sbt-dependency-graph` because: (1) it doesn't work on the sbt version I'm stuck on, and (2) it would not list valid information because the build does some version manipulation because _cinnamon_.

**Comment by johanandren** [comment]
Looking at the example in the slack discussion, I have changed my mind and think grouping the mismatches on version is a good improvement.

**Comment by johanandren** [comment]
Not sure if you want to do some additions to the docs as well before we close this one @ignasi35 ?

**Comment by octonato** [comment]
Done in #30046

**Comment by octonato** [comment]
Oh, reopening. I didn't see Johan's comment about docs.

**Comment by ignasi35** [comment]
> Not sure if you want to do some additions to the docs as well before we close this one @ignasi35 ?

Raised a PR with small imrpovements.
