### ISSUE TITLE
Draining control support for MergeHub

### ISSUE THREAD

**Issue by nivox** [akka/akka#30057]
Currently the only way to complete a `MergeHub` source is to cancel it from downstream. While this is fine most of the time, there are situation where the source should complete only after all the messages produced by the streams attached to the `MergeHub` have been processed and the stream are completed.

One such scenario happens for example during shutdown where the various sources attached to the `MergeHub` are completed and we need to wait for the messages to be consumed in order to cleanly stop the process. 

At the moment the API exposed by `MergeHub` doesn't offer any support for this and you need to come up with custom code to try and obtain the same result, however it's not trivial as we have no way to inspect the `MergeHub` state in order to understand when all the currently connected sources have been completed.

I'd like to propose to implement support for some sort of draining control directly into `MergeHub` with the following logic:
1.  During materialization a `DrainingControl` object is materialized alongside the sink
2. Once the `DrainingControl` is invoked, no new source can be connected to the `MegeHub` sink: attempting such an operation would fail the materialization with a dedicated exception (something like `ProducerMaterializationDuringDraining`)
3. As soon as all the currently connected sources complete (i.e. `MergedSourceLogic.demands` is empty) the `MergeHub` source is completed as well.

In terms of exposed API I was thinking something on the line of:

```scala
object MergeHub {
  // ...

  trait DrainingControl {
      def drainAndComplete(): Future[Unit]
  }

  def source[T](perProducerBufferSize: Int): Source[T, Sink[T, NotUsed]] =
    Source.fromGraph(new MergeHub[T](perProducerBufferSize))


  def sourceWithDraining[T](perProducerBufferSize: Int): Source[T, (Sink[T, NotUsed], DrainingControl)] = ???

  // ...
}
```

If this proposal is of interest I'd like to work on a PR as recently I had to juggle around this problem a couple of times and I'd like for a more integrated solution than the custom wrappers I had to come up with to make it work.

**Comment by johanandren** [comment]
Sound like a reasonable addition to me. Important that it does not add overhead to the `MergeHub` when not used though as it is used in a few performance critical places in Artery (akka-remoting).
