### ISSUE TITLE
Performance degradation from 2.6.10 to 2.6.12

### ISSUE THREAD

**Issue by danischroeter** [akka/akka#30055]
Hi there. We struggle with a performance issue since upgrading from akka 2.6.10 to akka 2.6.12.
Our application is heavily stream based. What we do is read data in parallel from cassandra (akka-persistence-cassandra), transform it and then store it to disk. There are no dependencies between the streams other than that we wait until all streams have completed.

Since the upgrade to akka 2.6.12 the same job with the same amount of data suddenly takes ~40m instead of ~15m. This happens reproducible in different deployments.
We tried to identify the cause and know that:
- Our application code did not change
- The cassandra driver and akka-persistence-cassandra are the same
- We have no warnings etc in the logs
- We use about the same amount of memory
- The cpu usage of the application stays at at about 60% compared to before. The overall cpu consumption is higher since it takes much longer

 It's hard to figure out what could have caused the issue and we would be very happy to get some hints on where/what to research...
 https://github.com/akka/akka/compare/v2.6.10...v2.6.12

Maybe there are others with the same issue?

**Comment by johanandren** [comment]
Can you try with a nightly snapshot (https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository) and see if it is the same as fixed in https://github.com/akka/akka/issues/30022 ?

**Comment by patriknw** [comment]
Related to that is also https://github.com/akka/akka/pull/30039, which hasn't been merged yet.

**Comment by danischroeter** [comment]
> Can you try with a nightly snapshot (https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository) and see if it is the same as fixed in #30022 ?

@johanandren thx! sure - i'll test that

**Comment by johanandren** [comment]
If you know that you use `flatMapPrefix` or `Flow.future` in your stream, that's the additional fix that was in #30039 so won't be in the nightly until tomorrow, but if it you do not use either of those it is good if you test with the current nightly.

**Comment by patriknw** [comment]
@danischroeter I have published another snapshot that includes #30039. Version: `2.6.12+32-8dfb4a7a`
Would be great if you can try that before we release Akka 2.6.13.

**Comment by danischroeter** [comment]
@patriknw awesome thx! I should be able to finish the test today... :running_man:

**Comment by danischroeter** [comment]
@patriknw @johanandren Awesome! I verified our application with akka `2.6.12+32-8dfb4a7a` using a test sample which was 3 times faster than with 2.6.12 :+1:  (63s vs 180s)

**Comment by patriknw** [comment]
Thanks, we will release 2.6.13 today (or asap).
This issue was fixed by #30022 and #30039
