### ISSUE TITLE
[bug] Java API getContext().findChild is not returning a child, whereas scala API context().child does

### ISSUE THREAD

**Issue by kuba-tyburski** [akka/akka#30053]
Hey,
Bug regards akka 2.5.32 and from what I checked is still present in 2.6.12. 
In message processor I try to forward message to child if it already exists or spawn a new one if there is non.

```
getContext().findChild("name")
    .orElse(getContext().actorOf(SomeActor.props(), "name"))
    .forward("message", getContext());
```

What is happening is that trying to process subsequent messages, even though  `getContext().getChildren()` with second time returns the actor created in first flow. `findChild()` seems to cannot lookup child actor by name and goes to `orElse` flow.

There is a simple workaround with usage of Scala API:

```
context().child("name")
    .getOrElse(() -> context().actorOf(SomeActor.props(), "name"))
    .forward("message", context())
```

**Comment by johanandren** [comment]
Curious, the implementation of both is the same deferring to `getChild(String)` and the only difference is the wrapping in `Option` for Scala vs `Optional` for Java: https://github.com/akka/akka/blob/da70e0ccd410d430a93bc66dd616817b11f46a66/akka-actor/src/main/scala/akka/actor/dungeon/Children.scala#L43

**Comment by kuba-tyburski** [comment]
Haven't checked the internals but applying both codes ive different result.
Java one gives me:
`akka.actor.InvalidActorNameException: actor name [name] is not unique`

**Comment by kuba-tyburski** [comment]
Ugh... forget about it... I should've use supplier API of Optional ... not the immediate actorOf evaluation...
Sorry, my bad.

Proper construct:
getContext().findChild("name")
    .orElseGet(() -> getContext().actorOf(SomeActor.props(), "name"))
    .forward("message", getContext());
