### ISSUE TITLE
Upgrade to Scala 2.13.5

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30060]
I started on this, but it will require some work because of the improved exhaustiveness checks catching a lot of trixery in the Akka internals. Pattern match on OptionVal seems broken wrt exhaustiveness for some reason.

**Comment by johanandren** [comment]
After a discussion with @dwijnand there is no current alternative to get `OptionVal` matching complete except for an additional `case _ =>` or `case _: OptionVal[_] =>`. Looking into if we can make completeness check warnings _not_ fail the build since we do so many of those.

**Comment by dwijnand** [comment]
> an additional

It would be in alternative to `case OptionVal.None =>`, not in addition, IMO.

**Comment by johanandren** [comment]
One tricky case for our users I found will be receptionist and `case serviceKeyInstance.Listing(topics) =>` which will give exhaustiveness check warning.

**Comment by johanandren** [comment]
Another user facing one found we'll need to look into is the custom extractors used for `StatusReply.{Success, Failure}`

**Comment by dwijnand** [comment]
@ignasi35 and I spotted some parts of Akka's API in https://github.com/playframework/play-samples/pull/125#discussion_r532856843 too, which you might want to review and extrapolate from.
