### ISSUE TITLE
Add Flow.preMaterialize similar to Source/Sink

### ISSUE THREAD

**Issue by makkarpov** [akka/akka#30074]
One of the use-cases of such pre-materialization is Akka HTTP WebSocket requests on server side. When you return a flow, they consume materialized value with no way to get it back.

Something like this:
```scala
  implicit class FlowUtils[I, O, M](val f: Flow[I, O, M]) extends AnyVal {
    def preMaterialize()(implicit materializer: Materializer): (M, Flow[I, O, NotUsed]) = {
      val (sub, mat, pub) = Source.asSubscriber[I]
        .viaMat(f)(Keep.both)
        .toMat(Sink.asPublisher(false)){ case ((sub, mat), pub) => (sub, mat, pub) }
        .run()
      
      (mat, Flow.fromSinkAndSource(Sink.fromSubscriber(sub), Source.fromPublisher(pub)))
    }
  }
```

**Comment by johanandren** [comment]
Sounds like it could make sense to add.

Note that you can also work around this by side effecting from `mapMaterializedValue` into for example a promise/future to react on the websocket flow being materialized. This has the benefit of not adding any additional stream overhead like a `preMaterialize` will (async boundary etc).
