### ISSUE TITLE
add an option to ignore deserialization failures from the snapshot store

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#30077]
The current behavior is that a persistent actor keeps retrying if there is a deserialization exception when loading states from the snapshot store. 
when breaking changes in schemas are unavoidable, I have to use both `eventAdapter` and `snapshotAdapter`,  while `eventAdapter` should be enough because states can always be built on events. 

With this new option, it can save a lot of work when dealing with breaking changes in schemas.

**Comment by octonato** [comment]
hi @Zhen-hao

Have you seen this option? 
https://doc.akka.io/docs/akka/current/persistence.html#recovery-customization

It allows you to not load the snapshots and start from scratch. Though this is for the classic API. The typed API mention that it's possible but don't show how. Either is a missing feature or undocumented.

**Comment by octonato** [comment]
I was wrong, it is documented for typed. 

`withRecovery(Recovery.withSnapshotSelectionCriteria(SnapshotSelectionCriteria.none))` 

You can find it here: https://doc.akka.io/docs/akka/current/typed/persistence-snapshot.html#snapshot-failures

**Comment by Zhen-hao** [comment]
hi @octonato, 
yes, I'm aware of it. I actually use it for my cluster singletons where there is a breaking change. 

The tricky part with `SnapshotSelectionCriteria.none` is that in many cases you can't know when a certain sharded persist actor is going to replay. for example, it can be triggered by user log-in, or some business process.
Because of those cases, you can't go back to using snapshots ever again. 

Unless there is a way to trigger replay on all persistent actors. If that's possible, it is also a performance risk in a production system.

**Comment by octonato** [comment]
I see your point. With a configuration flag we could say: if it fails, fallback to `SnapshotSelectionCriteria.none` otherwise just read what you have there. 

We will need to look further if that would be possible. `SnapshotSelectionCriteria.none` is implemented a selection criteria for each the starting point is the beginning of the journal. In any case, that looks a good addition to me.

**Comment by patriknw** [comment]
Sounds good to add.

I think Akka Persistence Cassandra already tries older snapshots if serialization fails and maybe fallback to events if none works. I'm not quite sure. Anyway, good to have the possibility at this layer.

**Comment by Zhen-hao** [comment]
In my test, failed snapshot loading won't trigger recovering with events only. I think it is documented somewhere that a runtime exception in snapshot loading stops the recovering actor. it would be awesome if users can define in a config what exception classes (can be user-defined) can be safely ignored during snapshot deserialization.

**Comment by octonato** [comment]
for the record, this is being added as a configuration option here https://github.com/akka/akka/pull/30238

**Comment by Captain1653** [comment]
This issue is quite old. The PR  https://github.com/akka/akka/pull/30238 .
There are no new comments for 2 years.
Should this issue be closed?

**Comment by patriknw** [comment]
Looks like the PR implemented this.
