### ISSUE TITLE
Guardian Actor with custom Mailbox - Documentation missing

### ISSUE THREAD

**Issue by FlorianSchaetz** [akka/akka#30108]
When trying to set a [custom mailbox](https://doc.akka.io/docs/akka/current/typed/mailboxes.html) for the guardian actor via...

`ActorSystem.create(Behaviors.setup(ctx -> someBehavior(ctx)), "system", ConfigFactory.load("application.conf"), MailboxSelector.fromConfig("my-app.my-special-mailbox")); `

...I noticed that this simply doesn't work - but it also does not throw an error. It works perfectly fine for any child actor, but it seems to be completely ignored for the user guardian actor.

I'm not fluent in scala, so please forgive my lack of understanding there, but to me it seems that in `ActorRefProvider override lazy val guardian`, the mailbox for the user guardian is always set to the default mailbox, thus ignoring any custom mailbox.

I assume there are good reasons for this, but this does not seem to be documented (or at least, I could not find it). Would it be possible to update the mailboxes documentation to include the fact that the guardian actor always uses a default mailbox and cannot be configured otherwise? Additionally it would be nice to throw an error in such case instead of silently ignoring this.

Alternatively, if there are no good reasons and this is simply a bug, please fix ;-)

**Comment by patriknw** [comment]
Thanks for reporting, it should use the mailbox defined with the Props parameter.
