### ISSUE TITLE
Add size() to BoundedSourceQueue

### ISSUE THREAD

**Issue by alex-ninja** [akka/akka#30124]
### Request
Add `size()` method to `BoundedSourceQueue`.

### Proposed implementation
The implementation is pretty straightforward, we just need to get the size from the underlying queue:
```scala
override def size(): Integer = queue.size()
```

### Context
Currently I'm struggling to understand how much queue capacity is utilized in production. Having a way to expose the size would be pretty useful from monitoring standpoint. It might shed the light onto the following questions:
- do I need to increase the queue size to ensure stream is able to handle short term traffic spikes?
- is stream capable to process all incoming events with minimal queuing (minimal latency)?

I plan to use it through `Gauge`:
```java
meterRegistry.gauge("boundedSourceQueue", queue, BoundedSourceQueue::size());
```
so the size is automatically and periodically being reported.

### Implementation
If the idea makes sense, then I'd love to raise a PR.

**Comment by alex-ninja** [comment]
@johanandren @patriknw 
Gentlemen, could you, please, check this issue and let me know if the idea makes sense to you.

**Comment by patriknw** [comment]
I think that can be added if we are clear about that it's just a approx hint of the size, since that is what is provided by the underlying AbstractBoundedNodeQueue

**Comment by alex-ninja** [comment]
@patriknw 
Correct, that's mentioned in the javadoc. However, we can call the method `approximateSize()` instead of `size()` to make it more emphatic. What do you think on such approach?
