### ISSUE TITLE
Make ActorContext.system implicit

### ISSUE THREAD

**Issue by makkarpov** [akka/akka#30132]
Currently, when you use ask pattern inside of actor, you need to redeclare actor system each time you use ask, e.g.

```
implicit val system: ActorSystem[_] = context.system
ref.ask(...)
```

I think that it would be much cleaner if `context.system` would be implicit, e.g. just `import context.system`.

**Comment by johanandren** [comment]
Avoid using ask pattern inside of an actor, instead use context.ask.

**Comment by makkarpov** [comment]
These are different asks. My usage pattern is like this:

```scala
case GetSomething(replyTo) =>
  val future = for {
    a <- child1.ask(...)
    b <- child2.ask(...)
  } yield SomethingComposite(a, b)
  Utils.pipeTo(future, replyTo)
```

BTW `pipeTo` to different actor is also here.

**Comment by johanandren** [comment]
That requirement/need is fine, but implementing it inline in the actor, closing over actor internals with the `map` and `flatMap`, is very prone to writing code that is not thread safe. In general the recommendation is to put such future composition in a static/companion object method, to avoid any risk of accidentally getting it wrong, which means you anyway have to take the `ActorSystem` as a parameter and can mark it as implicit in that parameter list.

**Comment by johanandren** [comment]
To point out one good example of a bug like that in the shared snippet, the second ask accesses both `child2` and implicitly the `ActorContext` which are both internal fields of the actor, which may be stopped, or running on another thread by then. If `child2` is a `var` it also has additional thread visibility issues.

**Comment by patriknw** [comment]
> general the recommendation is to put such future composition in a static/companion object method

I agree, and that can have an second parameter list with (implicit system), but when calling it I'd say that it's good to be explicit:

```
externalStuff(params)(context.system)
```

**Comment by johanandren** [comment]
Closing this as no new discussion surfaced for a long while, please re-open if you have some further arguments.
