### ISSUE TITLE
Add overloaded versions of `typed.AskPattern.ask` with explicit timeouts

### ISSUE THREAD

**Issue by makkarpov** [akka/akka#30133]
Same kind of issue like explicit actor system: implicit timeouts are too verbose when there are few ask's.

Something like `askT[R](f: RecipientRef[R] => T, timeout: FiniteDuration): Future[R]` and corresponding `askWithStatusT` would be very useful in one-liners.

**Comment by johanandren** [comment]
The reason for not using the current signature and just passing the timeout explicitly is that you'd have to provide the `Scheduler` (or the `Classtag` for `ActorContext#ask`) as well?

**Comment by makkarpov** [comment]
Yes, scheduler (actually actor system) should stay implicit

**Comment by johanandren** [comment]
So that'd means that if you don't want to define an implicit timeout, you can currently use `actorRef.ask(Request(_, "reqdata"))(3.seconds, implicitly[Scheduler])`, I don't see that as verbose enough to warrant adding additional overloads.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for 2 years.

Should this issue be closed?
