### ISSUE TITLE
entity constant recovery strategy not working as expected

### ISSUE THREAD

**Issue by AkshayaJayamani** [akka/akka#30153]
We have following configuration in our project to enable remember entities and to recover actor in a constant rate. But all actors got created up on forming cluster. With following config we expect to load each entity at constant rate of 2 mins.
```
akka.cluster.sharding {
        entity-recovery-strategy = "constant"
        entity-recovery-constant-rate-strategy {
        number-of-entities = 1
        frequency = 120000 ms
        }
      }
```

**Comment by octonato** [comment]
Would you be able to provide a small reproducer for this issue? 

We do have tests that exercise it though. So it may be a configuration issue in your project. Can you verify that this configuration is effectively being loaded?

**Comment by sreekesh93** [comment]
The configurations are loaded as part of tuning parameters in ClusterShardingSettings, We have enabledRemember entities too. All shard informations are store as part of postgres. 
```
  persistence.journal.plugin = "pg-journal"
  persistence.snapshot-store.plugin = "pg-snapshot"
```


It would be helpful if you share some working example.

**Comment by johanandren** [comment]
Debug logs from sharding, especially from `akka.cluster.sharding.internal.RememberEntityStarter` would be interesting to see if you can share.

**Comment by sreekesh93** [comment]
any updates?

**Comment by johanandren** [comment]
The recovery is per shard, not per region, in your application you have a single entity per shard so it doesn't help much.

**Comment by sreekesh93** [comment]
@johanandren can you please elaborate more on the above comment `in your application you have a single entity per shard `?

**Comment by johanandren** [comment]
In the logs you shared it shows that each shard only has a single sharded actor/entity in it. The recovery strategy is applied to the set of actors in the same shard. Starting the first and only actor in each shard is therefore immediate. 

I created a PR with a small clarification to the reference.conf around this: https://github.com/akka/akka/pull/30167

**Comment by sreekesh93** [comment]
Thanks @johanandren  that helps to understand.
