### ISSUE TITLE
Docs: Misinformation in RestartSource.onFailuresWithBackoff(RestartSettings)?

### ISSUE THREAD

**Issue by arbitrary-dev** [akka/akka#30176]
https://github.com/akka/akka/blob/1ff2950ab6eee20db0b6d3a1f2e7b2fe0126a386/akka-stream/src/main/scala/akka/stream/scaladsl/RestartSource.scala#L165

>This [[Source]] will not emit a complete or failure as long as maxRestarts is not reached, since the completion
>or failure of the wrapped [[Source]] is handled by restarting it.

Isn't this particular method wraps only failures and upstream completion will actually complete the result?

**Comment by johanandren** [comment]
That sounds incorrect, I agree.
