### ISSUE TITLE
Prevent journal from growing too large with remember entities

### ISSUE THREAD

**Issue by AkshayaJayamani** [akka/akka#30186]
When the remember entities is enabled, journal keeps growing too large. To prevent this, is there a way to avoid journal or delete shard information from it ? We use postgres persistence journal.

      persistence.journal.plugin = "pg-journal"
      persistence.snapshot-store.plugin = "pg-snapshot"

**Comment by ignasi35** [comment]
Hi @AkshayaJayamani this issue sounds more like a request for help than a discussion for an improvement. I think discuss.akka.io/ is a better forum for this kind of conversations and you are more likely to obtain the help you seek.

Cheers,

PS: I'll close this issue, feel free to reopen.
