### ISSUE TITLE
Graphing tool for actors

### ISSUE THREAD

**Issue by redkhalil** [akka/akka#30198]
We're working on a few projects with a fairly large number of actors and the original developers are not on the team anymore. We find it's pretty difficult to follow through the message flow. I was wondering if we have some graphing tool to generate a diagram of the interaction among actors. I've googled for this and stumbled across https://stackoverflow.com/questions/41552609/diagram-tool-for-actors. This post is a few years old, do we have newer solutions (or maybe akka has this feature integrated)?

**Comment by Lukah0173** [comment]
This may be interesting (also mentioned in your link):

https://developer.lightbend.com/docs/telemetry/current/visualizations/vizceral.html

I'm not sure of the current level of support. An integration with Kiali or something would be nifty too.

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).
