### ISSUE TITLE
Actualization of docs for "Resumable projections"

### ISSUE THREAD

**Issue by ihostage** [akka/akka#30191]
I was re-reading Akka docs and caught on [Resumable projections](https://doc.akka.io/docs/akka/current/persistence-query.html#resumable-projections) paragraph.
But Akka already has an Akka Projection module for these cases and I think that this information is already not actual.
How about creating a cross-link to Akka Projections in this or even complete removal of this part?

**Comment by patriknw** [comment]
@ihostage I agree that this page hasn't been updated to the existence of Akka Projections. Would you be up to making PR improving that?
