### ISSUE TITLE
Lease is not supported by typed cluster singleton

### ISSUE THREAD

**Issue by zhxiaogg** [akka/akka#30208]
I think it's similar to https://github.com/akka/akka/issues/29662, the lease configuration is not passed to the classic ClusterSingleton settings when creating a typed cluster singleton.

**Comment by patriknw** [comment]
@zhxiaogg Thanks for reporting, would you be able to create a PR fixing it?

**Comment by zhxiaogg** [comment]
@patriknw just opened the pr, need your help review it, thanks!
