### ISSUE TITLE
groupBy improperly throws too many substreams exception when maxStreams used and element comes in on closed substream

### ISSUE THREAD

**Issue by bdoyle0182** [akka/akka#30205]
So first the bug is that when groupBy has the max number of streams open and one is subsequently closed, if a new element comes in on that closed sub stream; then groupBy is going to throw `TooManySubstreamsOpenException`. Which I believe the behavior should be that if a new element comes in on a closed substream, the element should be dropped like occurs if `maxSubstreams` is not opened. The way we hit this is that we have strictly defined maxSubstreams based on the number of partitions in our kafka source. 1 partition per substream running infinitely. And somehow one substream seemingly ends up closing,

The issue is with this line

https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/fusing/StreamOfStreams.scala#L354

```      
override def onPush(): Unit =
        try {
          val elem = grab(in)
          val key = keyFor(elem)
          require(key != null, "Key cannot be null")
          val substreamSource = activeSubstreamsMap.get(key)
          if (substreamSource != null) {
            if (substreamSource.isAvailable) substreamSource.push(elem)
            else {
              nextElementKey = key
              nextElementValue = elem
            }
          } else {
            if (activeSubstreamsMap.size + closedSubstreams.size == maxSubstreams)
              throw tooManySubstreamsOpenException
            else if (closedSubstreams.contains(key) && !hasBeenPulled(in))
              pull(in)
            else runSubstream(key, elem)
          }
        } catch {
          case NonFatal(ex) =>
            decider(ex) match {
              case Supervision.Stop                         => fail(ex)
              case Supervision.Resume | Supervision.Restart => if (!hasBeenPulled(in)) pull(in)
            }
        }
```

In the onPush, if the key does not have an active substream it goes to the else. But if this key is in the `closedSubstreams` set , it does the check on if you have too many substreams open first. You're not really trying to open a "new" substream past the limit because this element is tied to an already closed substream. 

**FIX**: Put the `else if (closedSubstreams.contains(key) && !hasBeenPulled(in))` statement before the check on too many substreams.

Also a couple quick questions on `groupBy` guarantees. So as I can see if a substream is somehow closed, any new elements  tied to that group that come in on it are just swallowed and never emitted down stream. I ask because in the documentation (https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/groupBy.html), it makes it sound like by setting `allowClosedSubstreamRecreation` to true you're losing a guarantee that is there if it is set to false. But if it's set to false and a substream is closed and an element comes in on the closed substream, that element is also lost. So is there really any more risk in setting `allowClosedSubstreamRecreation` or not because both can seemingly silently lose elements.

Going off that, this bug is actually kind of helping us because we always have the max streams open so if any substream closes it will throw this exception ultimately recreating the entire stream instead of eating any elements and silently losing elements. Continuing to process off the same kafka partition after missing something is bad for us. But that's an us problem, I still think this is a bug.

**Comment by johanandren** [comment]
I agree it sounds like a bug, not sure if it is because it is hard to hit with a repeatable test or just something missed in #24831 

Would you be up for PR:ing a fix (and test coverage ofc)?

**Comment by thomasschoeftner** [comment]
+1 we are experiencing the same issue.

In our case a sub-stream runs into an HTTP timeout while more load is coming in.
We do see the HTTP timeout exception on the log and briefly afterwards the `TooManySubstreamsOpenException`...

**Comment by hepin1989** [comment]
Is there any update？
