### ISSUE TITLE
[Artery] TopHeavyHitters keeps PromiseActorRefs resulting in memory leak

### ISSUE THREAD

**Issue by nodefactory-bk** [akka/akka#30212]
PromiseActorRefs and their related result value are kept around within the topHeavyHitters in InboundActorRefCompression.

This leads to a memory leak since they may hang around long after the value received has been used and would have been freed. 
I suggest PromiseActorRefs and other temporary actors should never be kept in topHeavyHitters.

This is slightly similar to #28822 and #28959.

A heap dump of a severely memory constrained app that crashed shows lots of PromiseActorRef's referenced from TopHeavyHitters.
![116200201-57530d80-a738-11eb-889a-d196964d6564](https://user-images.githubusercontent.com/16016450/116879654-30597780-ac21-11eb-93ac-a1dbfcdbff3d.png)

**Comment by johanandren** [comment]
I agree this would be good to fix. I expected that we covered that with the previous optimizations keeping promiserefs out of caches, but I see now that we don't do that anywhere.

**Comment by patriknw** [comment]
The "new" way of checking is via `InternalActorRef.isTemporaryRef`

**Comment by octonato** [comment]
Fixed in #30214
