### ISSUE TITLE
EventSourcedRememberEntitiesShardStore only updates internal state on recovery

### ISSUE THREAD

**Issue by jneumaier** [akka/akka#30215]
In our project we encountered an issue during recovery of shards with remembered entities using state-store-mode persistent.

The code issue is quite clear in EventSourcedRememberEntitiesShardStore:

https://github.com/akka/akka/blob/031886a7b32530228f34176cd41bba9d344f43bd/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/internal/EventSourcedRememberEntitiesShardStore.scala#L104

The internal state of the actor is never updated. The internal state is only updated on actor recovery if there are updates in the journal. Snapshots from the internal state will be empty if no recovery happened. The default snapshotting will only take place after 1000 (batched) updates.

Updating the internal state fixes the issue (added `state = `):
  
`state = state.copy(state.entities.union(started).diff(stopped))`
  
I found no clean way to test the snapshotting in itself waiting for a SaveSnapshotSuccess on the store. I added snapshotting to the corresponding Spec file anyway which causes some tests to fail without the fix.

To make the regression test more clear I added a test checking internal state is updated.

I will add a PR in a minute.

**Comment by jneumaier** [comment]
@johanandren I think you are a major contributor for this store. Maybe you can have a look at the fix.

**Comment by johanandren** [comment]
Thanks @jneumaier !
