### ISSUE TITLE
Remove usage of Java assert in tests

### ISSUE THREAD

**Issue by octonato** [akka/akka#30220]
As founded out here... 

_Originally posted by @octonato in https://github.com/akka/akka/issues/30165#issuecomment-831126790_

@Captain1653 searched the code base and discovered a few more case.

**Comment by Captain1653** [comment]
@octonato Maybe it shouldn't be closed. There are one assert in the code `RemoteDeploymentDocTest.demonstrateDeployment`. I told about it [here](https://github.com/akka/akka/pull/30227#issue-630816320) . I didn't fix it yet. Should I create some different issue?

**Comment by raboof** [comment]
> Should I create some different issue or just create separated PR later?

I think it's fine to do that under this issue, I'll reopen ;)
