### ISSUE TITLE
Fallback recovery to replay all events if snapshot loading fails

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30234]
If snapshot deserialization fails it would be useful to automatically fall back to replaying all events instead. This aligns with the claim that snapshots are supposed to be used as an optimization. It's useful because then serialization schema of snapshots can be changed without having to make it compatible.

We can't have this enabled by default because it would be wrong if events were deleted. It should be an explicit configuration option with warning that it shouldn't be used if events are deleted. Maybe even log warning if that combination is used.

Akka Typed is first priority for this feature, but if not too much work it would be nice to include in classic also (so that it can be used with classic Lagom Persistent Entity).

**Comment by octonato** [comment]
What about fallback to the before last snapshot and eventually fallback to replaying all events? 

It will certainly add extra delays, but given that this an edge case I don't see as a major problem. 

I may have time next week to pick this. Unless you pick it this week. ;-)

**Comment by patriknw** [comment]
> What about fallback to the before last snapshot and eventually fallback to replaying all events?

That is already implemented in the Cassandra plugin. I tries a few snapshots back in history before giving up.
