### ISSUE TITLE
scala3: use our 2.13.x artifacts on scala 3

### ISSUE THREAD

**Issue by raboof** [akka/akka#30242]
There are 2 ways Akka can support Scala 3: by making sure our 2.13.x artifacts work from Scala 3 (using cross-dependencies as documented at https://scala-lang.org/blog/2021/04/08/scala-3-in-sbt.html#using-scala-213-libraries-in-scala-3), and by publishing our own Scala 3 artifacts.

This is an 'umbrella issue' to track progress and issues with the first: making sure our 2.13.x artifacts work from Scala 3. The perhaps more long-term goal of publishing our own Scala 3 artifacts is tracked in #30243.

The blog post at https://blog.lunatech.com/posts/2020-02-19-using-dotty-union-types-with-akka-typed-part-II on using Akka with Dotty might be an interesting starting point.

**Comment by raboof** [comment]
To be clear: there are currently no known problems with using the Akka 2.13 artifacts on Scala 3, and we've heard some promising reports. If you do find any problems, do feel free to report them.

**Comment by patriknw** [comment]
Not much more to do here, I guess.
