### ISSUE TITLE
SupervisorStrategy: flexible failure logging

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#30267]
We want to restart actors in certain cases which do not warrant an error log. For that `SupervisorStrategy` would need to be opened up in some way as `OneForOneStrategy` is a case class and cannot be just extended to overwrite `handleFailure`.

Some options to achieve this would be having simething like a log level decider or providing a trait that can be mixed into exceptions. Or maybe someone has a better idea.

**Comment by johanandren** [comment]
`OneForOneStrategy` is not final nor marked with "do not inherit" though so it might be perfectly possible to do without any API changes, even if extending case classes in general is a bad idea (tm)

**Comment by johanandren** [comment]
Also note that if possible to use typed APIs it already has a `logLevel` on `SupervisionStrategy`.

**Comment by nvollmar** [comment]
Thanks for the hint, I quickly had a look at the typed API. We only want to override the log level for a specific exception, not all failures in general.

**Comment by nvollmar** [comment]
I'm investigating to do an extension similar to the `OverflowStrategy`, I might get that backwards compatible.
