### ISSUE TITLE
OptionVal instances in jfr

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30264]
Why does OptionVal show up in JFR recording? I thought we wouldn't allocate instances of it?

<img width="999" alt="Screenshot 2021-05-26 at 16 05 13" src="https://user-images.githubusercontent.com/336161/119674154-403d3380-be3c-11eb-8d33-6ff4d5d48cce.png">

cc @johanandren

**Comment by johanandren** [comment]
Hmm. Maybe we are putting it in some collection causing boxing? Do I interpret that view right that all those allocations boils down to the `LinearTraversalBuilder.append` method?

**Comment by patriknw** [comment]
> Do I interpret that view right that all those allocations boils down to the LinearTraversalBuilder.append method?

I'm not sure how to read it, but I think you are right. There are also other paths:

<img width="699" alt="Screenshot 2021-05-26 at 18 52 59" src="https://user-images.githubusercontent.com/336161/119700699-d3ce2e80-be53-11eb-9080-1263e503bb12.png">

**Comment by johanandren** [comment]
Looking at the bytecode of `Attributes.getMandatoryAttribute` it looks like it is allocating a `OptionVal` instance:

```
      public <T extends akka.stream.Attributes$MandatoryAttribute> T getMandatoryAttribute(java.lang.Class<T>);
    descriptor: (Ljava/lang/Class;)Lakka/stream/Attributes$MandatoryAttribute;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=5, locals=6, args_size=2
         0: aload_0
         1: aload_0
         2: invokevirtual #235                // Method attributeList:()Lscala/collection/immutable/List;
         5: aload_1
         6: invokespecial #365                // Method find$1:(Lscala/collection/immutable/List;Ljava/lang/Class;)Lakka/stream/Attributes$Attribute;
         9: astore_3
        10: new           #79                 // class akka/util/OptionVal
        13: dup
        14: aload_3
        15: invokespecial #366                // Method akka/util/OptionVal."<init>":(Ljava/lang/Object;)V
        18: ifnull        69
        21: getstatic     #369                // Field akka/util/OptionVal$Some$.MODULE$:Lakka/util/OptionVal$Some$;
        24: aload_3
        25: invokevirtual #371                // Method akka/util/OptionVal$Some$.unapply:(Ljava/lang/Object;)Ljava/lang/Object;
        28: checkcast     #32                 // class akka/stream/Attributes$Attribute
        31: astore        4
        33: getstatic     #376                // Field akka/util/OptionVal$.MODULE$:Lakka/util/OptionVal$;
        36: aload         4
        38: invokevirtual #379                // Method akka/util/OptionVal$.isEmpty$extension:(Ljava/lang/Object;)Z
        41: ifne          66
        44: getstatic     #376                // Field akka/util/OptionVal$.MODULE$:Lakka/util/OptionVal$;
        47: aload         4
        49: invokevirtual #382                // Method akka/util/OptionVal$.get$extension:(Ljava/lang/Object;)Ljava/lang/Object;
        52: checkcast     #32                 // class akka/stream/Attributes$Attribute
        55: astore        5
        57: aload         5
        59: checkcast     #56                 // class akka/stream/Attributes$MandatoryAttribute
```

https://github.com/akka/akka/blob/0a226eb3ea0123ac55dd7fc20b708c73e24619c5/akka-stream/src/main/scala/akka/stream/Attributes.scala#L123

**Comment by lrytz** [comment]
Created https://github.com/scala/bug/issues/12405 about that

**Comment by viktorklang** [comment]
@johanandren @patriknw I think I've addressed everything from akka/akka in the image you posted.

**Comment by johanandren** [comment]
Local fix applied thanks to @viktorklang , but let's keep this issue open to track reverting that once a Scala version with a fix for https://github.com/scala/bug/issues/12405 is out

**Comment by patriknw** [comment]
> but let's keep this issue open to track reverting

ah, I already created another issue for that https://github.com/akka/akka/issues/30278
Can be good to have this included in release notes.
