### ISSUE TITLE
ActorSource is terminated before draining finished if graph contains async stage

### ISSUE THREAD

**Issue by chessman** [akka/akka#30336]
When `ActorSource` is terminated using `completionMatcher`, I expect that it will emit `Terminated` signal when the stream is fully drained, i. e. all processing has been finished. But I noticed that if a graph contains `mapAsync`, it processes the last message even when the actor is already terminated.
```
  case object Done
  val actorSource = ActorSource
    .actorRef[Any](
      completionMatcher = { case Done => CompletionStrategy.draining },
      failureMatcher = PartialFunction.empty,
      bufferSize = 2,
      overflowStrategy = OverflowStrategy.dropHead
    )
    .mapAsync(1) { case _ =>
      Future {
        println("before")
        Thread.sleep(100)
        println("after")
      }
    }
    .to(Sink.ignore)

    val parent = testKit.spawn(Behaviors.setup[Any] { context =>
      implicit val mat: Materializer = Materializer(context)
      val actor = actorSource.run()
      context.watch(actor)
      actor ! "message"
      actor ! Done
      Behaviors.receiveSignal { case (context, Terminated(_)) =>
        println("stopped")
        Behaviors.stopped
      }
    })

  testKit.createTestProbe().expectTerminated(parent)
  Thread.sleep(100)
```

It prints
```
before
stopped
after
```

I expect
```
before
after
stopped
```

Is there a good workaround for that behavior?

**Comment by johanandren** [comment]
Operators in a stream can complete without the entire stream completing, so it is perfectly fine for the source to complete if there for example is a buffer downstream, an async boundary introduces such a buffer. If you want to act on downstream completion, you will have to observe it downstream - either through a materialized value from the sink or a `watchTermination` operator just before it (which will then not know if the sink actually completed or not).

We use the issue tracker for features and bug tracking, please use the forums https://discuss.akka.io for questions like this in the future, thanks!
