### ISSUE TITLE
CoordinatedShutdownSpec fails on JDK 17

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#30339]
this came up at https://github.com/scala/community-build/issues/1432 but is reproducible independently

on JDK 17-ea+27-2476, `akka-actor-tests/testOnly akka.actor.CoordinatedShutdownSpec` fails with multiple errors like

```java.lang.reflect.InaccessibleObjectException:
  Unable to make field private static java.util.IdentityHashMap java.lang.ApplicationShutdownHooks.hooks accessible:
    module java.base does not "opens java.lang" to unnamed module @5346e58b
```

attempting to work around the problem by starting sbt with `-J--illegal-access=permit` results in:

```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
```

oh Oracle why won't you let us be naughty

**Comment by johanandren** [comment]
We're only naughty in the test here at least, not the actual coordinated shutdown logic.

**Comment by johanandren** [comment]
Test now rewritten to do less messing around with JDK stdlib internals
