### ISSUE TITLE
Replace ByteString.size with ByteString.length

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#30342]
`ByteString.size` turns up with small percentages in profiles. It's implemented by `length` ultimately but goes through some intermediate frames in the Scala collections lib. Unfortunately, Scala collections mark it `final` so that `ByteString` cannot directly implement it.

We should go through the code base and do the replacement.

See also https://github.com/akka/akka-http/pull/3853.

**Comment by johanandren** [comment]
Ah, yes, just forgot closing this one, thanks for ping!
