### ISSUE TITLE
Is this a bug of akka cluster?

### ISSUE THREAD

**Issue by kulinux** [akka/akka#30358]
In the image attached, there is a akka cluster with localMember with the same address in Down and Weakly Up states (10.124.12.204:8976)

When trying to put the node down, never works, because in ClusterDaemon.scala::downing only use the first address found. So the cluster never get healed and the only solution is restart all akka system.

    localMembers.find(_.address == address) match {
      case Some(m) if m.status != Down =>
        if (localReachability.isReachable(m.uniqueAd

![image](https://user-images.githubusercontent.com/8877900/124256600-c891b100-db2b-11eb-9e79-85ff5ff986c4.png)

**Comment by johanandren** [comment]
Hi @kulinux, do you have a way to repeat this, or was it something you only saw once? Was it with the latest Akka version?

**Comment by patriknw** [comment]
It shouldn't be possible to have a duplicate member with same address like that. Indead something we should look into. What version of Akka is this?

**Comment by kulinux** [comment]
Hi,

Akka Version is 2.5.12.

I can reproduce in our environment always. Test case is.

- Three seed enviroment.
- A cluster of 25 nodes.
- One node in loop doing: akka connect, wait for 1 second and terminate akka system.

Best Regards, Thank for your attention

**Comment by patriknw** [comment]
At minimum I would recommend updating to latest 2.5.x patch version, which is 2.5.32.

I can't make any promise of investigating this issue unless we see the same with latest Akka 2.6.x version.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for 2 years.

Should this issue be closed?

**Comment by patriknw** [comment]
👍
