### ISSUE TITLE
Gracefully terminating shard region unnecessarily delays further rebalancing

### ISSUE THREAD

**Issue by raboof** [akka/akka#30401]
When a ShardRegion gracefully shuts down, this happens in a few phases:
* Sends a GracefulShutdownReq to the coordinator to let it know it intends to shutting down, to avoid the coordinator from allocating new shards on that region
* The coordinator initiates hand-off of all shards on this region
* When all shards have been successfully shut down, the ShardRegion actor stops itself
* The coordinator picks up the Terminated notification, and removes the region

This works. However, because of https://github.com/akka/akka/pull/29502/files#diff-2e992dd812c3468ad38d603de1dd4c99b36d5a8d0e60908fc3df24d43aaf5946R375 , the 'Terminated' notification is not sent immediately when the actor stops, but relies on the removal of the node from the cluster for this. Since this can take a while (i.e. 6 seconds), during this time the region is somewhat in limbo: the actor has stopped, but the Coordinator does not know this yet.

This impacts rebalances of other shards: to rebalance a shard, its registration must be removed from all regions before actually shutting it down (and bringing it up again elsewhere). This also includes the regions that are in the process of performing a graceful shutdown (if they are still in the middle of it). However, when the ShardRegion actor is actually already stopped, it can no longer acknowledge that it received the handoff notification for the newly rebalanced shard, meaning now the rebalance is delayed until the leaving cluster node is actually removed.

I think the cleanest way to avoid these delays would be to actively send a 'shard region terminated' message from the shard region to the coordinator, rather than relying on only `Terminated`. It is possible that this message gets lost, so for those cases we should still keep the `Terminated` trigger as well.

Related to #30315

**Comment by johanandren** [comment]
Sounds like a good idea to explicitly send (but not rely only on it being delivered)
