### ISSUE TITLE
large-message-destinations not supported for response to ask

### ISSUE THREAD

**Issue by an-tex** [akka/akka#30413]
[Large message destinations](https://doc.akka.io/docs/akka/current/remoting-artery.html#dedicated-subchannel-for-large-messages) can be configured to send larger messages (by default >256KB and <2MB) to remote actors. This does not work in combination with ClusterSharding.

I've created a [minimal test case](https://github.com/an-tex/akka-samples/blob/2.6/akka-sample-cluster-scala/src/multi-jvm/scala/sample/cluster/stats/LargeMessageSpec.scala) reproducing the issue using a multi jvm test with a three node cluster. It's based on this [existing test case](https://github.com/akka/akka-samples/blob/2.6/akka-sample-cluster-scala/src/multi-jvm/scala/sample/cluster/stats/StatsSampleSpec.scala).

Inside this repo run `sbt multi-jvm:testOnly *.LargeMessageSpec` and you'll see the error

`[JVM-3] akka.remote.OversizedPayloadException: Discarding oversized payload sent to Some(Actor[akka://LargeMessageSpec@127.0.0.1:61038/system/sharding/largeMessageTypeKey#-806848135]): max allowed size 262144 bytes. Message type [akka.cluster.sharding.typed.ShardingEnvelope].`

even though there's a [large destination configured](https://github.com/an-tex/akka-samples/blob/2.6/akka-sample-cluster-scala/src/main/resources/application.conf#L23) like this:

```
akka.remote.artery.large-message-destinations = [
  "/system/singletonManagerlargeMessageSingleton/*",
  "/system/sharding/largeMessageTypeKey*"
]
```

Note: This error occurs only on two of the nodes as serialization occurs only between JVM boundaries 

To make sure the `large-message-destinations` are actually working at all there's a separate test case using a ClusterSingleton where no issues occur.

Versions:
```scala
val akkaVersion = "2.6.14"
scalaVersion := "2.13.5"
```

**Comment by johanandren** [comment]
Adding `akka.remote.artery.large-message-destinations = [ "/system/sharding/largeMessageTypeKey"]` to the `commonConfig` makes the reproducer pass. I think this is because of the behavior of the wildcard matching working in a somewhat surprising way, not matching `*` against empty suffix.

**Comment by patriknw** [comment]
Note that there is both `*` and `**` syntax for the wildcards

**Comment by an-tex** [comment]
Thanks @johanandren ! That did help indeed, somehow I though the hash part of the actor path (largeMessageTypeKey#-**806848135**) needs to be matched as well. Still odd behaviour of not matching empty though ;) 

@patriknw thanks for the hint, the `**` didn't help in this case as I guess it's rather for matching multiple subpaths `actor/child/child/...`

**Comment by johanandren** [comment]
Note that it isn't about the children, all cross node communication _to_ the sharded actors go through the region actor. Note that replies goes right back to the sender (or potentially the temporary ask actor) so those would need a separate match to also go over the large message channel.

**Comment by an-tex** [comment]
Hi @johanandren , sorry for following up on a closed issue but I've encountered the original problem again regarding a temporary ask actor you mentioned in your last reply.

I've updated my [reproducing test case](https://github.com/an-tex/akka-samples/blob/2.6/akka-sample-cluster-scala/src/multi-jvm/scala/sample/cluster/stats/LargeMessageSpec.scala) to send a large reply to a temporary ask actor. I'm also getting a 

`Message [java.lang.String] to Actor[akka://LargeMessageSpec@127.0.0.1:56012/temp/singletonProxylargeMessageResponseSingleton-no-dc$a] was dropped. Discarding oversized payload sent to Some(Actor[akka://LargeMessageSpec@127.0.0.1:56012/temp/singletonProxylargeMessageResponseSingleton-no-dc$a]): max allowed size 262144 bytes.` 

even though the large message destinations are configured like this:

```
    akka.remote.artery.large-message-destinations = [
      ## none of these match the temporary ask actor /temp/singletonProxylargeMessageResponseSingleton-no-dc$a
      "/temp/singletonProxy*",
      "/temp/singletonProxylargeMessageResponseSingleton*",
      "/temp/singletonProxylargeMessageResponseSingleton**",
      "/temp/singletonProxylargeMessageResponseSingleton-no-dc",
      "/temp/singletonProxylargeMessageResponseSingleton-no-dc$**",
      "/temp/singletonProxylargeMessageResponseSingleton-no-dc$*",
      "/temp/singletonProxylargeMessageResponseSingleton-no-dc**",
      "/temp/singletonProxylargeMessageResponseSingleton-no-dc*",
      "/temp/singletonProxylargeMessageResponseSingleton-no-dc/*",
      "/temp/singletonProxylargeMessageResponseSingleton-no-dc/**",
      ## only full wildcard
      #"/temp/*",
      ## or hardcoding like this works :(
      #"/temp/singletonProxylargeMessageResponseSingleton-no-dc$a",
    ]
```

**Comment by johanandren** [comment]
Thanks for the added details, the update is correct, wildcards needs to be separate path segments and cannot be inside a segment.

Not entirely sure what would be the best solution here but the options as I see it would be to figure out a way to get more specific paths for ask or improve the matching, since it is done using the underlying wildcard index used for actor path selections we'd have to be very careful about changing that logic and look into the consequences of it. I guess a third option would be to not use the wildcard index but some more specific (but very performant, it is applied to every outgoing message if I don't remember wrong) matching.

Note that us in the team won't be having any time to spend on this in the nearest future. If you want this fixed further investigation and suggested a fix in a PR is much welcome.
