### ISSUE TITLE
Invalid rule in Event Sourcing sample code does prevent the State list store any item

### ISSUE THREAD

**Issue by vagtsi** [akka/akka#30418]
The implementation of the `State` class within the [Event Sourcing example code](https://doc.akka.io/docs/akka/current/typed/persistence.html#completing-the-example) has obviously a bug in the method `addItem()`. The goal is to maintain a list of the recent 5 data items but the logic of the following line does clear the list always as long the list has not more than one item:  
```java
    List<String> latest = newItems.subList(0, Math.min(4, newItems.size() - 1));
```

Since the items (data) are added one by one, the list will always be cleared and newer grow, as `Math.min()` will figure out zero as lowest value. Complete `addItem()` method sample code:
```java
public State addItem(String data) {
    List<String> newItems = new ArrayList<>(items);
    newItems.add(0, data);
    // keep 5 items
    List<String> latest = newItems.subList(0, Math.min(4, newItems.size() - 1));
    return new State(latest);
  }
```

**Comment by octonato** [comment]
Good catch. It should be `Math.min(5, al.size)` instead.

**Comment by vagtsi** [comment]
Wow that's a fast response and fit as well! I'm glad  to help.
