### ISSUE TITLE
Delete durable state

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30446]
See #30277

Delete API wasn't included in the initial implementation. This is a feature request to support deletes.

-----------------

If Durable State feature introduces `def deleteObject` we should also consider how that becomes visible in projections. The usual implementation on plugins for that operation is to physically delete the entity from the database (as a regular CRUD operation would do). 

This hard delete has implications from a projections point of view. By storing multiple revisions of the same entity in-place and then deleting the following can happen:

```
...
entity123-rev7 <--- last value read when polling via changes(tag,offset)
entity123-rev8
entity123-rev9
(deleted row)
```

From a query point of view (e.g. `changes(tag, offset)`), imagine an iteration reads rev7, then rev8, rev9 and the deletion happens. In that case, the information on rev8, rev9 and the actual deletion are lost on the projection side.

-----------------

For a CRUD-minded user point of view first arriving into CQRS-like (durable-state with akka-projections) the case above is likely to lead to corrupted projections.

A potential solution would be to require all implementations to implement `deleteObject` as a soft deletion and include a `def hardDelete` on the API. Another option would be to replace the `payload` on the database with a `case object Tombstone`. Still another option is to document this situation and recommend users to model deletion as a domain command that doesn't remove data from the database and warn about the implications of invoking `deleteObject` when using durable state in combination with projections.

**Comment by ignasi35** [comment]
A similar thing happens when using Event Sourcing if a user deletes the events from the journal before they are consumed by the projections. 

In event sourcing, though, hard deletion is more rare and, in general, users are more aware of the implications of deleting and the existence of projections since ES and CQRS go hand in hand very often.

**Comment by patriknw** [comment]
There is no API for deletes yet, so I changed the title and some of the issue description.

**Comment by jausmann-wc** [comment]
We have implemented our own persistence plugin and could really make use of a delete Effect to delete an entity in the db. Is there any chance to give this issue higher priority?
