### ISSUE TITLE
[Persistence] Expose type_hint and entity_id

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30447]
It's been already a source of issues in downstream plugins (https://github.com/akka/akka-persistence-spanner/issues/146) and an actual long-standing request to expose the `typeHint` and the `entityId` or a [`PersistenceId`](https://github.com/akka/akka/blob/master/akka-persistence-typed/src/main/scala/akka/persistence/typed/PersistenceId.scala#L37).

IIUC, `PersistenceId` was introduced only on Akka Persistence Typed and so it can't be accessed from the Akka Persistence TCK (which may still need to serve both the classic and the typoed APIs?).

It would be very useful to turn the `typeHint` and `entityId` into first class citizens. That would reduce the need for tags since certain queries over the journal and stateStore would no longer use tags but the typeHint.

**Comment by patriknw** [comment]
Would you also store those parts in separate columns? That would be a major change that I don't think is realistic to pursue.

The idea has been that those parts can be reconstructed from the persistenceId String when using a known separator.
