### ISSUE TITLE
Improved log hygiene in backoff supervisors

### ISSUE THREAD

**Issue by jroper** [akka/akka#30445]
Backoff supervisors are very often used for the purpose of ignoring "normal" errors (such as expected race conditions and transient network failures etc) by retrying, without exacerbating real problems, by backing off. It is therefore assumed that most failures they deal with can be classed into two classes, transient failures that can be ignored, and terminal failures that must not be ignored, and that the chance of a given failure being one or the other is a function on the number of retries attempted.

The problem is that a backoff supervisors logging treats these two classes of errors the same, they both get logged with the same severity, even though they have different severities.

This feature request is to be able to log these different classes of errors with different severities. If this feature is provided, it will allow monitoring of an Akka service based on logs and their severity to more reliably raise alerts with less false positives.

One way that this could be done is to provide a callback to do the logging which, among other details of the error, passes the number of retries. Another option could be that a callback takes the number of retries and returns the severity is used.

**Comment by patriknw** [comment]
Sounds good.
