### ISSUE TITLE
Setup PR labelling from GH workflows

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30459]
Jenkins builds for pr validation used to rely on a scripts (see `scripts/build/github-tagging.sh`).

When moving to GHActions in #30449 this may no longer be necessary or maybe we can already adopt 3rd party tooling (e.g. probot, mergify,...)

_Originally posted by @ignasi35 in https://github.com/akka/akka/issues/30449#issuecomment-892015645_

**Comment by patriknw** [comment]
What was the purpose of those tags? Do we need them?

**Comment by ignasi35** [comment]
> What was the purpose of those tags? Do we need them?

`validating`, `tested` and `needs-attention` were the most common (if not the only tags) used by this script. With the move to GH Actions and the existing ❌ and ✅ in the GH UI, the labels only make sense for non GitHub UIs and other tooling (akka-minion?). I think we can live without those labels.

**Comment by octonato** [comment]
Done in #30459
