### ISSUE TITLE
HubSpec: MergeHub must immediately cancel new producers while draining

### ISSUE THREAD

**Issue by raboof** [akka/akka#30464]
https://github.com/akka/akka/pull/30451/checks?check_run_id=3233793800

```
must immediately cancel new producers while draining *** FAILED *** (2 seconds, 41 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnNext, found class akka.stream.testkit.TestSubscriber$OnComplete$ (OnComplete)
[info]   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:572)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:159)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:438)
[info]   at akka.stream.scaladsl.HubSpec.f$proxy13$1$$anonfun$1(HubSpec.scala:218)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.HubSpec.f$proxy13$2(HubSpec.scala:223)
[info]   at akka.stream.scaladsl.HubSpec.$init$$$anonfun$16$$anonfun$13(HubSpec.scala:202)```

**Comment by ignasi35** [comment]
In another GHACtions run (https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:20256) a different test in HubSpec failed:

(yet another case of a different test on an already reported flaky suite)

```

[info] - must complete after draining control is invoked and all connected producers complete *** FAILED *** (2 seconds, 22 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnNext, found class akka.stream.testkit.TestSubscriber$OnComplete$ (OnComplete)
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:572)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:438)
[info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$29(HubSpec.scala:198)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$28(HubSpec.scala:188)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
```

**Comment by raboof** [comment]
> In another GHACtions run (https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:20256) a different test in HubSpec failed:
> 
> (yet another case of a different test on an already reported flaky suite)
> 
> ```
> 
> [info] - must complete after draining control is invoked and all connected producers complete *** FAILED *** (2 seconds, 22 milliseconds)
> [info]   java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnNext, found class akka.stream.testkit.TestSubscriber$OnComplete$ (OnComplete)
> [info]   at scala.Predef$.assert(Predef.scala:279)
> [info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:572)
> [info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
> [info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
> [info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
> [info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:438)
> [info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$29(HubSpec.scala:198)
> [info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
> [info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$28(HubSpec.scala:188)
> [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
> [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
> [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
> [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
> ```

That indeed looks very similar, and likely the same fix has to be applied to that test.
