### ISSUE TITLE
Docs for Sink.combine formatting is off

### ISSUE THREAD

**Issue by chhil** [akka/akka#30518]
Something seems off with the docs generated for 
https://doc.akka.io/docs/akka/current/stream/operators/Sink/combine.html

![image](https://user-images.githubusercontent.com/1119439/128973824-9fded9c5-880d-4a9a-99fe-06cd8eea8683.png)

**Comment by raboof** [comment]
Thanks for reporting! Looks like this was already fixed on the main branch (
https://doc.akka.io/docs/akka/snapshot/stream/operators/Sink/combine.html) in #30433, so that'll make it to the `current` docs with the next release
