### ISSUE TITLE
Cluster sharding tries to connect to non-existent nodes

### ISSUE THREAD

**Issue by nvollmar** [akka/akka#30512]
We have an Akka cluster deployed in Kubernetes running Akka 2.6.15

Certain cluster shardings seem to be in a weird state, messaging through them produces warn logs like this 
```
Outbound message stream to [akka://main@10.50.89.5:9999] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://main@10.50.89.5:9999] did not complete within 20000 ms
```
Though this IP does not exist in the cluster, which has been stable for over two weeks (and the cluster was deployed from scratch). The only thing I can think of carrying through the deployment would be the SBR.

The setting `remember-entities` is off, and the Akka pods don't have any direct persistent storage.

**Comment by patriknw** [comment]
Interesting. What could that be?

Does it repeat that log message periodically?

Since it says "message stream" and not "control stream" it must be some message that is sent to it?

> The only thing I can think of carrying through the deployment would be the SBR.

What makes you think that? SBR is not sending any messages directly to other nodes.

Do you see any other log messages that could be related?

**Comment by nvollmar** [comment]
Those logs always appear each day when a specific job sends messages to actors in that sharding. Some of the Warnings also have a trace id belonging to that job.

**Comment by patriknw** [comment]
I see, that means that the ShardingCoordinator has an allocation for that shard pointing to a node (10.50.89.5) that has been shutdown. That node is probably removed from the cluster membership, but still remains in the ShardCoordinator state.

That is indeed not good and strange that can happen. It might resolve itself if you do another rolling update (or shutdown the oldest node where the coordinator is running).

I assume this is in a running production system and you have no way to reproduce it again? To figure out how it ended up like this we would have to analyze logs from previous rolling update.

Do you use ddata mode for Cluster Sharding (that is default)? Any other sharding configuration?

**Comment by nvollmar** [comment]
Yep, it resolved after a restart. We have observed this on two systems (production and a testing one). We observed this state for about two weeks.

For cluster sharding we use the default settings for the most part, we customized some timings/intervals.

**Comment by patriknw** [comment]
It would be great if you can collect logs from a rolling update that caused the issue and share. I'm not sure it will be enough with INFO level, we might need DEBUG for akka.cluster and akka.cluster.sharding.

Is this something that started recently after an update of Akka version?

**Comment by nvollmar** [comment]
I'l try to get the logs once I see that happen again.

I can't remember seeing that issue ever until recently, we were already on the latest Akka release for some time.

**Comment by nvollmar** [comment]
We didn't encounter this for some time, either an Akka update or config change has fixed it.
