### ISSUE TITLE
Use WARN level instead of ERROR for abrupt termination logging

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#30564]
When terminating an actor system abruptly, Akka Streams issues logging like this at ERROR level:

```
Error:
akka.stream.AbruptStageTerminationException: GraphStage [akka.stream.impl.fusing.GraphStages$IgnoreSink$$anon$10-ignoreSink] terminated abruptly, caused by for example materializer or actor system termination.
```

Abrupt termination is not ideal, but nevertheless a normal production case, in particular in cloud/k8s environments. Therefore this kind of logging (which usually is not interesting at all) should not report ERRORs, but at most WARNINGs.

**Comment by johanandren** [comment]
Isn't that something logged by a future callback on the materialized completion of the Sink.ignore though, are you sure it is Akka logging that error?

**Comment by hseeberger** [comment]
Let me check that ...

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for 2 years.

Should this issue be closed?

**Comment by johanandren** [comment]
Let's close and re-open if someone still finds such logging.
