### ISSUE TITLE
Broken links in documentation - Java Serialization

### ISSUE THREAD

**Issue by Captain1653** [akka/akka#30589]
I have found some link about Java Serialization https://community.hpe.com/t5/Security-Research/The-perils-of-Java-deserialization/ba-p/6838995 . It used five times.
<img width="1127" alt="java serialization" src="https://user-images.githubusercontent.com/4740207/131196341-ff61cf58-1d73-4f5f-93e2-2cf3ceb5e12e.png">

I try to go, but I see the broken link:
<img width="621" alt="browser" src="https://user-images.githubusercontent.com/4740207/131196467-c5d4d691-5751-4b41-b375-c51cfff58919.png">

I can create PR  and change the link, but I don't know the content of the original page.

Kind regards

**Comment by johanandren** [comment]
It was a whitepaper about deserialization vulnerabilities by Alvaro Muñoz in 2016, but it seems to have disappeared completely, I can't find it anywhere online right now.

**Comment by octonato** [comment]
I found this link: https://community.microfocus.com/cyberres/fortify/f/fortify-discussions/317555/the-perils-of-java-deserialization

**Comment by octonato** [comment]
And it includes a link to the pdf. 
@Captain1653, a PR to fix the link is welcome. 😉
