### ISSUE TITLE
Update CONTRIBUTING.md about CI

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30591]
It mentions Jenkins a couple of times that should be updated to describe the new github actions based CI solution.

I think we should also add something about inheriting all github actions jobs if cloning the repository and a hint about how to disable that.

**Comment by ennru** [comment]
> I think we should also add something about inheriting all github actions jobs if cloning the repository and a hint about how to disable that.

Can we limit that by requiring the correct repo on the actions?

**Comment by marcospereira** [comment]
> Can we limit that by requiring the correct repo on the actions?

We are doing that for some of the new jobs already:

https://github.com/akka/akka/blob/5e9965a12985f8da7760f42e00de883da7789bcc/.github/workflows/multi-node.yml#L16

https://github.com/akka/akka/blob/5e9965a12985f8da7760f42e00de883da7789bcc/.github/workflows/nightly-builds.yml#L12

But this is only a short-circuit and a build is still triggered. So we should also point to Github docs about how to disable Actions entirely when forking: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository

**Comment by andreaTP** [comment]
The build is not triggered the execution is completely skipped:
https://github.com/andreaTP/akka/runs/3443664147?check_suite_focus=true
