### ISSUE TITLE
Log warning then error for "The ShardCoordinator was unable to update a distributed state"

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30608]
https://github.com/akka/akka/blob/fbaaf5bfca8acf87923f6cc96d3a37e1f0ad1ee7/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala#L1594

Similar to what was done in https://github.com/akka/akka/pull/30488

**Comment by patriknw** [comment]
It could be that "normal" occurrences of this is actually fixed by Akka 2.6.16 https://github.com/akka/akka/pull/30328

**Comment by muskan3006** [comment]
Can I pick it?

**Comment by johanandren** [comment]
Feel free @muskan3006 , but note that it might not be an issue anymore after 2.6.16 and the change to exclude exiting members in the set of nodes when doing that distributed data update as Patrik mentioned.
