### ISSUE TITLE
Failed: gcloud command fails - account not set

### ISSUE THREAD

**Issue by octonato** [akka/akka#30623]
Got this in two builds: 
https://github.com/akka/akka/runs/3452474679?check_suite_focus=true and https://github.com/akka/akka/runs/3456991183?check_suite_focus=true

Builds dates from 30/08 and 31/08. We haven't seen it since them. Maybe already solved? Leaving here for reference. We can close if we don't get it in the coming days.

```
Run gcloud config set compute/region us-central1
Updated property [compute/region].
ERROR: (gcloud.config.set) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Error: Process completed with exit code 1.
```

**Comment by andreaTP** [comment]
I forgot to add the secrets but is fixed now:
![Screenshot 2021-09-02 at 14 08 21](https://user-images.githubusercontent.com/5792097/131849093-65d5c0cd-5681-4bab-bc10-c75bb67eaf77.png)
