### ISSUE TITLE
I set differency remote port for 2 programs, but when I run the 2 programs in same PC, actorSystem.create throws 25520 port is bind by fitst program

### ISSUE THREAD

**Issue by zhangqi-ulua** [akka/akka#30627]
first run program

remote {
    enabled-transports = ["akka.remote.netty.tcp"]
    netty.tcp {
      hostname = "127.0.0.1"
      port = 14001
    }
    log-sent-messages = on
    log-received-messages = on
  }

second:

  remote {
    enabled-transports = ["akka.remote.netty.tcp"]
    netty.tcp {
      hostname = "127.0.0.1"
      port = 14002
    }
    log-sent-messages = on
    log-received-messages = on
  }

so, why port conflict ?

**Comment by patriknw** [comment]
You use the wrong config property. Use latest Akka 2.6.16 and see documentation https://doc.akka.io/docs/akka/current/remoting-artery.html

Next time...

We use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

**Comment by zhangqi-ulua** [comment]
Thank you very much. But where can I find akka remote config sample use netty ? This doc only artery  
https://doc.akka.io/docs/akka/current/remoting-artery.html

**Comment by patriknw** [comment]
That is https://doc.akka.io/docs/akka/current/remoting.html (but if you are starting something new you should absolutely not use that)

**Comment by zhangqi-ulua** [comment]
Thanks very much.
