### ISSUE TITLE
ConfigServiceDiscovery does not support service names with dots

### ISSUE THREAD

**Issue by regiskuckaertz** [akka/akka#30672]
The config discovery will blow up when parsing the following: 
```
services {
  "myapp.mydomain.com" {
    endpoints = []
  }
}
```
because of [this line](https://github.com/akka/akka/blob/master/akka-discovery/src/main/scala/akka/discovery/config/ConfigServiceDiscovery.scala#L30). You can see it here 

https://scastie.scala-lang.org/SyyQddmmTCm8KjgJc24Xkw

~~Replacing `getConfig` with `atKey` solves the problem~~ wow I totally misunderstood `atKey` which is not returning the config at the given key.

**Comment by johanandren** [comment]
Looks like a shortcoming, would you be up for PR:ing an improvement to support it? 

We do support dotted config paths for the serialization infrastructure so perhaps looking at that could give some hint about how to solve it.

**Comment by regiskuckaertz** [comment]
Yes! I planned on doing so as soon as I can.

**Comment by regiskuckaertz** [comment]
@johanandren before I open a PR, do I need to add anything to the documentation? seems like a trivial change:

https://github.com/akka/akka/compare/master...regiskuckaertz:rk-fix-config-service-discovery?expand=1

**Comment by regiskuckaertz** [comment]
@johanandren done, my good sir. Let me know if I need to do anything else.
