### ISSUE TITLE
Murmur2 implementation fails for inputs with lengths being a multiple of 4

### ISSUE THREAD

**Issue by coertel-yw** [akka/akka#30696]
`Murmur2.murmur2(byte[])` fails on inputs with lengths being a multiple of 4 due to `length % 4 match { ... }` not handling the case of 0.

**Comment by johanandren** [comment]
Note that this is not a general purpose murmur2 impl, you are not expected to call this yourself, it is a very specific internal port of the murmur2 hash impl used by Kafka, it is there to tie shards to the same node where a Kafka partition ends up (see docs https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html#external-shard-allocation and https://akka.io/blog/news/2020/03/18/akka-sharding-kafka-video). Did you see it failing when using it in this exact circumstance?

**Comment by coertel-yw** [comment]
That was exactly our use-case, trying to align Kafka partitions and Akka shards (in different services/JVMs).

**Comment by johanandren** [comment]
Alright, thanks for letting us know. 

Curious, if it breaks on the Akka side but not already on the Kafka side (maybe there is some non-obvious little difference in the algo): https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/utils/Utils.java#L500

**Comment by johanandren** [comment]
Oh, ofc, Java switch vs Scala switch 🤦

**Comment by coertel-yw** [comment]
yes, exactly. I have a little MR ready, just waiting for some collaboration legal stuff.
