### ISSUE TITLE
Doc: Validate external links

### ISSUE THREAD

**Issue by Captain1653** [akka/akka#30697]
I have done some search and found many `http` ( maybe deprecated) links in the project. 
<img width="1123" alt="Снимок экрана 2021-09-17 в 23 47 55" src="https://user-images.githubusercontent.com/4740207/133853348-7466abfa-6a98-4f02-a670-9411fdd75f10.png">

I can create PRs and replace them on `https`. [Play Framework](https://github.com/playframework/playframework) has some solutions for it - sbt-task. You can see  [the definition](https://github.com/playframework/playframework/blob/53e55f017f508f0dcdf2a70327bd73153fe87e5e/dev-mode/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala#L46) . The task can check each link for every build or something like that (broken links, redirects, etc.).

Will it be useful for Akka?

Kind regards

**Comment by patriknw** [comment]
@Captain1653 It would be great if you can fix the links.

Regarding link checker we should ask @ennru ? The Play link checker might not be "state of the art"? I don't think we wan't it on PR validation, but in some nightly job could be fine.

**Comment by ennru** [comment]
For checking links in docs with our common setup, I earlier created this JSoup and Akka HTTP-based project https://github.com/ennru/site-link-validator

We run that from a scheduled GitHub action in Alpakka Kafka: https://github.com/akka/alpakka-kafka/blob/master/.github/workflows/link-validator.yml

**Comment by Captain1653** [comment]
@octonato It is too early to close the issue :). I didn't fix all these links. I didn't add the validator to nightly builds

**Comment by octonato** [comment]
Oh, sorry. Reopening...

**Comment by GKuldeepak-Knoldus** [comment]
Hi @Captain1653  @patriknw ,
Can I also work on this issue, if possible?

**Comment by Captain1653** [comment]
@GKuldeepak-Knoldus Yes, you can. I'm working #22904

**Comment by purvaagrawal25** [comment]
Hi @Captain1653  @patriknw ,
Can I also work on this issue, if possible?

**Comment by GKuldeepak-Knoldus** [comment]
Hi @johanandren ,
I believe this is the last iteration where all the external links have been fixed. Please review it.

**Comment by Captain1653** [comment]
I'm not sure. This task about some automatic links check . I'll work for it soon.

**Comment by GKuldeepak-Knoldus** [comment]
Hi @Captain1653 ,
Thanks for confirming me back for the same. But for now, could you please review the PR I have raised, so that we can continue further.

**Comment by ennru** [comment]
Created #31086

**Comment by ennru** [comment]
Documentation links are now checked weekly with a scheduled action.

**Comment by ennru** [comment]
Added scheduled link validation with #31086.
