### ISSUE TITLE
failed: DistributedPubSubRestartSpec - handle restart of nodes with same address

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30699]
https://github.com/akka/akka/runs/3627192603?check_suite_focus=true#step:5:24670

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/4146239242?check_suite_focus=true#step:9:29507

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/4159419758?check_suite_focus=true#step:9:29980
