### ISSUE TITLE
use Timers with PersistentActor, instead of PersistentActor with Timers

### ISSUE THREAD

**Issue by raboof** [akka/akka#30711]
On Scala 3, akka-cluster-sharding tests fail with `use Timers with PersistentActor, instead of PersistentActor with Timers`. Are traits ordered differently between Scala 2 and 3?

Needed for #30243

**Comment by patriknw** [comment]
I think we historically had some problem with ordering them in a different way, so we should be careful with changing this.

**Comment by raboof** [comment]
Looking closer, one of the classes this triggers for is `PersistentShardCoordinator`. On Scala 2.13, that class only implements `PersistentActor`, but on Scala 3, it also directly `implements` the interfaces belonging to transitive superclasses/traits. So it *might* just be our detection mechanism that triggers, not an actual difference in ordering/stacking. Needs more investigation though.

**Comment by smarter** [comment]
> So it might just be our detection mechanism that triggers, not an actual difference in ordering/stacking

Seems likely, there is no known difference in linearization between Scala 2 and 3, but there is no guarantee that you can recover the linearization order from bytecode-level information.
