### ISSUE TITLE
Typed ActorTestKit stop() method does not respect max timeout parameter

### ISSUE THREAD

**Issue by barrett122** [akka/akka#30715]
The `max` parameter provided to the testkit `stop()` method is not respected if it is larger than the default timeout.
Here's an example to reproduce:
```scala
@RunWith(classOf[JUnitRunner])
class QuickTest extends ScalaTestWithActorTestKit() with AnyFlatSpecLike {
  "this" should "reproduce the issue" in {
    val testBehavior = Behaviors.receiveSignal[Unit] {
      case (context, PostStop) =>
        context.log.info("Stopping")
        Thread.sleep(10.seconds.toMillis)
        context.log.info("Stopped")
        Behaviors.same
    }
    val testActor = testKit.spawn(testBehavior)
    testKit.stop(testActor, max = 20.seconds) // Should have plenty of time to stop but fails after the default timeout elapses
  }
}
```

Reason appears to be that in the `stop()` implementation, the `max` parameter is used for the timeout of `Await.result()` but not also for `ask` so the default timeout is used implicitly. Screenshot with IntelliJ implicit hints enabled to show what I mean:

![Screenshot 2021-09-24 at 13 35 37](https://user-images.githubusercontent.com/2222658/134675131-e1451e18-2f3c-4ba1-a1af-baec9884a0ff.png)

Should be an easy fix, happy to open a PR if someone can confirm I'm not missing something here 😅

**Comment by johanandren** [comment]
Hi @barrett122 thanks for detailed report/reproducer. Please go ahead and PR a fix if you want to, thanks!
