### ISSUE TITLE
SplitWhen skips the first element.

### ISSUE THREAD

**Issue by pedromdias** [akka/akka#30723]
In an attempt to aggregate a Source we created a groupWhile method. Note: This method assumes the Stream is sorted.
It works well, except in the scenario where the first element is its own group of just one element, because SplitWhen does not evaluate the first element.
If you uncomment the _println_ in the _groupWhile_ example below, you'll see that the first element is never evaluated. This leads to the first element always being grouped with the second element. 

For example: A list of ints (1,2,3,4,5), with the number as the key, would group the 1 with the 2.
Expected: ((1, (1)) (2,(2)), (3,(3)), (4,(4)), (5,(5))) 
Result:       ((1, (1,2)), (3,(3)), (4,(4)), (5,(5))) 

Below you will find the code to reproduce this issue.
```
def groupWhile[I, K](key: I => K): Flow[I, (K, Seq[I]), NotUsed] = {
    Flow[I]
      .splitWhen(SubstreamCancelStrategy.drain) {
        var lastKey: Option[K] = None
        item =>
          //println(item)
          val currentItemKey        = key(item)
          val shouldTriggerNewGroup = lastKey.exists(current => current != currentItemKey)
          lastKey = Some(currentItemKey)
          shouldTriggerNewGroup
      }
      .fold(Seq.empty[I])((acc, interest) => acc :+ interest)
      .filterNot(_.isEmpty)
      .map(filteredItems => (key(filteredItems.head), filteredItems))
      .mergeSubstreams
  }

//
Source(List(1,2,3,4,5))
          .via(groupWhile(identity))
          .runWith(Sink.seq)
//Expected: Vector((1,List(1)), (2,List(2)), (3,List(3)), (4,List(4)), (5,List(5)))
//Result: Vector((1,List(1, 2)), (3,List(3)), (4,List(4)), (5,List(5)))

val result = Source(List(1,2,2,3,3,4,5))
          .via(groupWhile(identity))
          .runWith(Sink.seq)
//Expected: Vector((1,List(1)), (2,List(2, 2)), (3,List(3, 3)), (4,List(4)), (5,List(5)))
//Result: Vector((1,List(1, 2, 2)), (3,List(3, 3)), (4,List(4)), (5,List(5)))

val result = Source(List(1,1,2,3,3,4,5))
          .via(groupWhile(identity))
          .runWith(Sink.seq)
//Expected : Vector((1,List(1, 1)), (2,List(2)), (3,List(3, 3)), (4,List(4)), (5,List(5)))
//Result: Vector((1,List(1, 1)), (2,List(2)), (3,List(3, 3)), (4,List(4)), (5,List(5)))
`

```

For clarity, we ended up working around this by using statefulMapConcat() with a similar logic.

**Comment by johanandren** [comment]
Note that it is not safe to create mutable state like the `lastKey` like that without synchronization so maybe that can explain the issue. In addition to that, multiple materializations of a `Flow` created by calling your `groupWhile` once will share the same var across threads.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for almost 2 years.

Should this issue be closed?
