### ISSUE TITLE
Do nothing, but server offer show this log, and user connection may interrupt

### ISSUE THREAD

**Issue by newcoder7777** [akka/akka#30791]
[INFO] [10/15/2021 11:18:03.710] [gm-akka.actor.default-dispatcher-729] [Association(akka://gm)] Stopping idle outbound stream [2] to [akka://gateway_1@172.24.67.44:14002]
[WARN] [10/15/2021 11:18:03.716] [gm-akka.remote.default-remote-dispatcher-9] [akka.stream.Log(akka://gm/system/Materializers/StreamSupervisor-1)] [outbound connection to [akka://gateway_1@XXX.XXX.XXX.XXX(my server ip):14002], message stream] Upstream failed, cause: StreamTcpException: The connection has been aborted

**Comment by newcoder7777** [comment]
many issues like it , but not solve

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug. Please add clear information in that case about what behavior you expected and what you experienced instead. Adding a reproducer will help a lot as well.
