### ISSUE TITLE
FoldWithin operator as a more general version of GroupedWeightedWithin

### ISSUE THREAD

**Issue by yongjiaw** [akka/akka#30797]
We need to write akka stream, such as kafka source, into blob store such as GCS.
This requires chunking the stream into groups represented by onepass Iterator which can be too big to fit into memory if represented by Seq as in the variants of existing grouped methods.
Does this sound like a natural/useful feature? Does it already exist? 
This alpakka library only supports single bounded upload.
https://doc.akka.io/docs/alpakka/current/google-cloud-storage.html

It seems the more general pattern is to chunk stream into aggregators, where Seq is just a special case of aggregator.

**Comment by hepin1989** [comment]
Hi, @yongjiaw , Thanks for this operator. What if we want to change the aggration time after a harvest?
Would it be more useful we change the `emitOnTimer: Option[(Agg => Boolean, FiniteDuration)]` to `emitOnTimer: Option[Agg => (Boolean, FiniteDuration)]`

**Comment by yongjiaw** [comment]
This is a fixed interval timer with recurring invocations, as opposed to be "scheduled once" after every invocation.
This is for performance consideration.
The signature you proposed would be for the second case since it implies the interval for next invocation is determined by the `Agg` function.
I remember we briefly discussed these 2 choices in the thread. It's very expensive to schedule after every Agg.

**Comment by hepin1989** [comment]
Ok thanks @yongjiaw , I have a case where the next interval maybe change, I will write an custom stage for that。Your current AggregateWithBoundary is very flexibale and powerful too, thanks again.
Where my case is depends on the current concurrent user of Taobao live ,then some message send to a live room may need to send in batchs, like in 1/3 ，1/3 ，1/3, or 1/4 ，1/4 ，1/4 ，1/4 ，1/4 .

**Comment by yongjiaw** [comment]
Scheduling a timer event for every stream stream element is going to be a significant performance hit.
The `AggregateWithBoundary` operator allows you to keep track of arbitrary state for next emit, including changing the emit interval. The `emitOnTimer` part can be used to determine the time resolution. I believe it's the more efficient implementation based on my limited understanding of the akka stream framework. It should be able to simulate the behavior you want with reasonable error. I recommend you do some benchmark, and I'm interested to learn about it.

**Comment by hepin1989** [comment]
Not for every element ,If I want to change the batches from 3 to 4, I only need to reschedule the same timerkey at a 4s delay.And I can't see how to change the interval onTimer event is triggered, the  `interval` is ignored after `emitOnTimer` call.
![image](https://user-images.githubusercontent.com/501740/158118665-b0064a5e-17b4-42b4-88b3-b068002d69cf.png)

Maybe we can reschedule a new timer when the duration is changed and harvest done?

My current impelmentation is based on a custom stage, where for messages that do not need sending in batches, it passing thought, for the messages that need to batches, I will aggrate them up to N seconds and send them after the downstream is avaialble, there is another downstream system sending this aggreated message to the users with 1/N step,each with a 1seconds delay. The user case for this is the where the cascaded system which will be accessed after a user click the promotioncard or goods can not endure such a high concurrency.

**Comment by yongjiaw** [comment]
Ok, I'm trying to better understand the use case.
It seems you want to "smooth" the streaming elements in some custom window of up to N seconds (probably limited by buffering capacity), and the emit interval will depend on the actual Agg duration dynamically.
Is the "downstream system" you mentioned just another GraphStage/operator that splits the batch and emit with 1/N grouped elements each with 1 second delay? You want to "stretch" the elements back to the same original time scale as opposed to let the elements through ASAP? 
If my understanding is correct, it does sound like a custom use case of the timer.
It could potentially become another reusable operator (by composition), since existing operators are mostly for maximizing throughput limited by downstream back pressure.

**Comment by Roiocam** [comment]
> The downstream is another system, the stage passes ...
> ....
> The logic maybe a little complex but we do need that in our system， as the messages I circled out below.

I'm not sure if the other two cases from me are duplicated.

My implementation uses `groupedWithin`.

## case 1

> When Source emits an element with 1 tps/s  rate, then each element has a fixed delay of window time.

I use `groupedWeightedWithin` to fix this:

```java
// when the element is far away from prev window, using an eager emit pattern.
if ((now - lastHandledElement) > timeWindow){
   return maxWeight;
}
// else using normal mode.
return 1L;
```
That should speed up each element when the flow is low frequency.

but this is not perfect, because we don't know what happened next. 

if this element is just one of many from a large flood, then the grouping was not doing right.

## case 2

> base case 1 fix. If the client using the synchronization way waits for the sink of the stream.
>
> The stream is a ring, the next element must wait until prev element had been handled and reply to the client then the client (also source) is able to emit the next element.

in this case, I had no idea how to fix it, the only way is to decrease the time window duration.

Case 2 sounds kind of weird. But it just uses Kafka to implement RPC, and the client uses synchronization way gain sequence behavior.
