### ISSUE TITLE
ChildFailed event doesn't come when child is restarted via SupervisorStrategy.restart

### ISSUE THREAD

**Issue by SavtechSolutions** [akka/akka#30836]
This means that if you want the child actors to be restarted automatically, then you're unable to get a hold on the exception that downed the child (which might have important info, e.g., the message that caused the exception)

**Comment by johanandren** [comment]
We have the style guide in the docs, https://doc.akka.io/docs/akka/current/typed/style-guide.html , it is perhaps more about code style and structure than higher level patterns though.

**Comment by johanandren** [comment]
I'll close this as it ended up more of a discussion, please open up a new more concrete issue around what is missing for docs around this if you think that's needed, thanks!
