### ISSUE TITLE
Add note to classic logging docs about auto sl4j with akka-actor-typed

### ISSUE THREAD

**Issue by francisdb** [akka/akka#30848]
I found this unexpected as it is not mentioned in the documentation

```scala
val akkaVersion = "2.6.17"

libraryDependencies ++= Seq(
  "com.typesafe" % "config" % "1.4.1",
  "com.typesafe.akka" %% "akka-actor"               % akkaVersion,
  "com.typesafe.akka" %% "akka-actor-typed"         % akkaVersion
)
```

```scala
object Main extends App{
  val config = ConfigFactory.load()
  println(config.getList("akka.loggers"))
  val as = ActorSystem("test", config)
  println(as.settings.config.getList("akka.loggers"))
  as.terminate()
}
```

output

```scala
[info] running Main
SimpleConfigList(["akka.event.Logging$DefaultLogger"])
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SimpleConfigList(["akka.event.slf4j.Slf4jLogger"])
```

**Comment by johanandren** [comment]
I don't think it is mentioned in the reference docs, but there is some config docs and a toggle here:

https://github.com/akka/akka/blob/main/akka-actor-typed/src/main/resources/reference.conf#L66

**Comment by johanandren** [comment]
Oh, actually it is mentioned in the reference docs: https://doc.akka.io/docs/akka/current/typed/logging.html#event-bus

**Comment by francisdb** [comment]
I see, maybe a pointer from the non-typed docs would be helpful but feel free to close this.

**Comment by johanandren** [comment]
Yeah, is worth a small mention in the classic docs. 👍

**Comment by francisdb** [comment]
maybe here?

https://github.com/akka/akka/blob/8c9b6f3608ac25c511aaa59775a5da091b06267a/akka-docs/src/main/paradox/logging.md?plain=1#L318-L320

**Comment by johanandren** [comment]
Sounds good!
