### ISSUE TITLE
add QueueOfferResult.isSuccess/isEnqueued method

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#30853]
current ` return queueOfferResult == QueueOfferResult.enqueued();`

**Comment by utkarshup11** [comment]
Hi @hepin1989 you did not mentioned the File location where the issue needs to be solved. Can you please mention that.
Thanks

**Comment by johanandren** [comment]
You can find it here: https://github.com/akka/akka/blob/d703a2afe0e0c6dc8f1c0321b0f4652600e2ae99/akka-stream/src/main/scala/akka/stream/QueueOfferResult.scala

**Comment by utkarshup11** [comment]
@johanandren  I am not able to find that QueueOfferResult.enqueued(); method is used anywhere in this above shared scala class.

**Comment by johanandren** [comment]
https://github.com/akka/akka/blob/d703a2afe0e0c6dc8f1c0321b0f4652600e2ae99/akka-stream/src/main/scala/akka/stream/QueueOfferResult.scala#L34

What @hepin1989 suggests is to add an abstract method on the `QueueOfferResult` base returning a boolean to identify if it was enqueued, rather than having to compare a result to the `enqueued` singleton/constant.

**Comment by GKuldeepak-Knoldus** [comment]
Hi @johanandren , could you please elaborate a bit more or by an example and I would like to pick this issue!

**Comment by johanandren** [comment]
Hi, @GKuldeepak-Knoldus, not sure what more to add, current API is that you have to compare the result from enqueuing an element with one of the possible outcome objects, the suggestion is that there would also be a `isEnqueued: Boolean` method on `QueueOfferResult` so you can call that to see if the element was successfully enqueued. 

Please go ahead and pick it up if you like.

**Comment by GKuldeepak-Knoldus** [comment]
Hi @johanandren ,
I have added a new method as you suggested and also raised a PR for the same. Please lemme know if anything further is required.
