### ISSUE TITLE
Fix the example of `mergeSorted` and etcs

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#30851]
![image](https://user-images.githubusercontent.com/501740/140005753-516577a9-28ac-453d-8682-cfec538372f5.png)
which gives you `110220304034`.
need add the lines below to get the prints
```
            .map(String::valueOf)
            .intersperse(",")
```

**Comment by johanandren** [comment]
just `foreach(e -> System.out.println(e))` would be good enough imo (and what I think we do in other samples)

**Comment by muskan3006** [comment]
Hey, as I understand this is just to change the output in much readable format right? So as @johanandren saying println would be good. If so I would like to pick it
