### ISSUE TITLE
Add some diagram to the MergeHub and BroadcastHub

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#30864]
![image](https://user-images.githubusercontent.com/501740/140605925-76035d6b-8f55-4757-b120-c8afe765c5fd.png)
like something from [here](https://www.oreilly.com/library/view/scala-reactive-programming/9781787288645/22d1a175-d0d0-4233-954e-fdb8e7024816.xhtml)

The current [document](https://doc.akka.io/docs/akka/current/stream/stream-dynamic.html#using-the-mergehub) is not that intuitionistic.

**Comment by Captain1653** [comment]
This issue is quite old. 

If it is still needed, I can try to add the diagram in the doc. Only  this one?
