### ISSUE TITLE
The comment attached with  `maximum-large-frame-size` is ambiguous.

### ISSUE THREAD

**Issue by mbairagi85** [akka/akka#30893]
[In reference.conf](https://github.com/akka/akka/blob/bdb46d16fd1006412d8a1d1d467765ceb4a2c0b6/akka-remote/src/main/resources/reference.conf#L855), following comment is attached with `akka.remote.artery.advance.maximum-large-frame-size`
` # Maximum serialized message size for the large messages, including header data.
        # It is currently restricted to 1/8th the size of a term buffer that can be
        # configured by setting the 'aeron.term.buffer.length' system property.
        # See 'large-message-destinations'.`

It seems ambiguous since `aeron config` is only applicable when `transport=aeron-udp`. If `transport=tcp/tls-tcp` then is there any restriction imposed?

**Comment by patriknw** [comment]
@mbairagi85 Thanks for reporting. You are right, that 1/8th is only for `aeron-udp`.

Would you be able to create a pull request clarifying that?

**Comment by mbairagi85** [comment]
Sure @patriknw . I will create a pull request for that.
