### ISSUE TITLE
Various Actor Tutorial clarifications

### ISSUE THREAD

**Issue by plouj** [akka/akka#30948]
While reading the extended Actor tutorial (https://doc.akka.io/docs/akka/current/typed/guide/tutorial.html) I found some things that weren't very clear to me. I can't submit a pull request, but here are the things I found in case it helps someone:

* https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/main/paradox/typed/guide/tutorial_5.md?plain=1#L82
There's no mention of `DeviceGroupQueryMessage` in the code. Should this say `DeviceGroupQuery.Command`?

* https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/main/paradox/typed/guide/tutorial_5.md?plain=1#L90
Seems like there's a word missing, maybe it should say "We keep track of state with"?

* https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/main/paradox/typed/guide/tutorial_5.md?plain=1#L48
Should this say "device group actor"?

* https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/test/scala/typed/tutorial_1/ActorHierarchyExperiments.scala#L40
What's the difference between returning `this` and `Behaviors.same` in `onMessage` (that's what the pre-requisite tutorial uses: https://github.com/akka/akka-quickstart-scala.g8/blob/229c61b510fd13a688be9d79fa6a600d9e7177d3/src/main/g8/src/main/scala/%24package%24/AkkaQuickstart.scala#L21)?

* https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/main/paradox/typed/guide/tutorial_4.md?plain=1#L130
https://github.com/akka/akka/blob/v2.6.17/akka-docs/src/test/scala/typed/tutorial_4/DeviceGroup.scala#L72
What is the reason for ignoring the `groupId` here? Is it not possible or is it intentionally for the simplicity of the tutorial? In the latter case, I think it would be nice to explicitly mention that in a note to ease comprehension for noobie readers. I'm a little confused why a `DeviceGroup` actor would not at least warn about dealing with a different `groupId` than its own?

* https://github.com/akka/akka/blob/v2.6.17/akka-docs/src/test/scala/typed/tutorial_4/DeviceGroup.scala#L59
A bit of a nit pick, but I feel that it might be more helpful to for the readers to see:
 > Ignoring TrackDevice request for group ID 1234. This actor is responsible for group ID 7890.

Instead of just
 > Ignoring TrackDevice request for 1234. This actor is responsible for 7890.

* https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/main/paradox/typed/guide/tutorial_4.md?plain=1#L127
Should this say "We need the actor’s device ID to remove it..."? It's not immediately clear from the context.

* https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/main/paradox/typed/guide/tutorial_4.md?plain=1#L127
Wouldn't maintaining a parallel `actorRefToDeviceId: Map[ActorRef[DeviceMessage], String]` avoid the need to introduce a new type of message?

Thanks for writing this very helpful introduction!

**Comment by octonato** [comment]
done in #30949
