### ISSUE TITLE
Multiple references to misssing variable: FoldSink

### ISSUE THREAD

**Issue by plouj** [akka/akka#30967]
All of the following spots seem to refer to a variable named `FoldSink` which doesn't actually appear in any of the example code that I found:
- [x] https://github.com/akka/akka/blob/70120060b8b6de66d2944f88e8fe316c9ca4191c/akka-docs/src/main/paradox/stream/stream-flows-and-basics.md?plain=1#L107
- [x] https://github.com/akka/akka/blob/v2.6.17/akka-docs/src/main/paradox/stream/stream-flows-and-basics.md?plain=1#L122
- [x] https://github.com/akka/akka/blob/v2.6.17/akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala#L44
- [x] https://github.com/akka/akka/blob/v2.6.17/akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala#L67
- [x] Small typo: `Sinks materialized value` should be `Sink's materialized value` https://github.com/akka/akka/blob/v2.6.17/akka-docs/src/test/scala/docs/stream/FlowDocSpec.scala#L55

Cheers!

**Comment by utkarshup11** [comment]
I will take up the last one small typo. Can I ? @plouj

**Comment by plouj** [comment]
> I will take up the last one small typo. Can I ? @plouj

I don't have a problem with that!

**Comment by utkarshup11** [comment]
Hi @plouj  and @johanandren  can anyone please review the above PR, and please tell me what can I do better as I am new here and just learning how to do contributions.
Thanks in advance for you your each and every suggestions.

**Comment by raboof** [comment]
> can anyone please review the above PR, and please tell me what can I do better as I am new here and just learning how to do contributions. Thanks in advance for you your each and every suggestions.

Excellent first contribution, thank you! Good description of the change, cross-referenced with this issue... I have no suggestions :)

**Comment by muskan3006** [comment]
Hi, I would like to fix the FlowDocSpec? can I pick it?

**Comment by nitikagarw** [comment]
Hi, Can I work on the first two bullets?

**Comment by GKuldeepak-Knoldus** [comment]
Hi Everyone,
Is someone working on the first two bullets or should I pick them ?

**Comment by nitikagarw** [comment]
Hi @GKuldeepak-Knoldus, 
I missed the acknowledgment from @johanandren (no notifications are sent for reactions :D ).
I have created the PR now. 
Thanks.
