### ISSUE TITLE
scala3: loading an extension needs an explicit `system`

### ISSUE THREAD

**Issue by raboof** [akka/akka#30973]
On Scala 3, loading a 'classic' extension like `Tcp()` does not work:

```
[error] -- [E134] Type Error: /home/aengelen/dev/akka/akka-docs/src/test/scala/docs/stream/operators/flow/FromSinkAndSource.scala:54:4 
[error] 54 |    Tcp().bind("127.0.0.1", 9999).runForeach { incomingConnection =>
[error]    |    ^^^
[error]    |None of the overloaded alternatives of method apply in trait TcpImplicitExtensionIdApply with types
[error]    | (implicit system: akka.actor.ActorSystem): akka.stream.scaladsl.Tcp
[error]    | (system: akka.actor.ClassicActorSystemProvider): akka.stream.scaladsl.Tcp
[error]    |match arguments ()
```

Explicitly providing the ActorSystem, like `Tcp(system)`, does work.

Strangely, recreating the pattern in isolation:

```
trait ExtensionId[T] {
  def apply(i: Int): T = (new Tcp(i)).asInstanceOf[T]
  def apply(l: Long): T = (new Tcp(l.intValue)).asInstanceOf[T]
}
trait TcpImplicitExtensionIdApply extends ExtensionId[Tcp] {
  def apply()(implicit i: Int): Tcp = super.apply(i)
}
object Tcp extends ExtensionId[Tcp] with TcpImplicitExtensionIdApply {
}
class Tcp(i: Int) {
  def bind(): Unit = ()
}
object Main {
  implicit val i: Int = 42
  Tcp().bind()
}
```

... actually works fine.

**Comment by johanandren** [comment]
I think requiring it explicitly could be fine though? (Looking at our tests we already do that in a lot of the extension lookups)

**Comment by raboof** [comment]
> Looking at our tests we already do that in a lot of the extension lookups

I suspect we started adding that to our tests to be able to run them on scala 3 ;).

I agree it doesn't look *that* bad, so we could simply start recommending that style.

**Comment by patriknw** [comment]
I'd say that the implicit in Tcp is the odd one compared to all other extension, like `Cluster(system)`, which requires an explicit system.

**Comment by raboof** [comment]
:+1: let's just recommend `Tcp(system)` going forward then
