### ISSUE TITLE
Inconsistent OSGi metadata regarding scala-java8-compat

### ISSUE THREAD

**Issue by oheger** [akka/akka#31024]
In commit 8468e6ae the dependency to `scala-java8-compat` has been updated to version 1.0.0. `Dependencies` contains code to define the version based on the version of Scala in use; for Scala 3 and Scala 2.13, the version is now set to 1.0.0.

In `OSGi`, however, the version range to this dependency is still set to the interval [0.8.0, 1.0.0) - excluding version 1.0.0. This means that in order to fulfill this requirement, in an OSGi environment a 0.x version of `scala-java8-compat` needs to be deployed, which is inconsistent with the dependency declaration.

To make the OSGi metadata consistent with the dependency declaration, the version range in `OSGi` could be increased to include 1.x versions of the library. Alternatively, the range could also be computed dynamically based on the Scala version.

Note: The constellation worked before upgrading to version 1.0.0, because then the versions 0.8.0 and 0.9.x were used for Scala 2.12 and Scala 2.13 respective. Both of these versions are included in the range [0.8.0, 1.0.0) defined within `OSGi`.

**Comment by patriknw** [comment]
Thanks for reporting. We rely on the community to keep the OSGi definitions up to date. Please open a PR with the extended version range.
