### ISSUE TITLE
High cpu usage when scheduler.tick-duration is default 10ms

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#31023]
with deafult 10ms
![lQLPDhsCIKYJE6DNAZzNClew2J5OEJHf0LsB1CixVEAvAA_2647_412](https://user-images.githubusercontent.com/501740/147731916-7b35b2e1-2cf7-4405-9b23-ca0676105efb.png)
after change it to 50ms

![image](https://user-images.githubusercontent.com/501740/147731987-cd8f07b7-6331-4005-a0b1-041d57bde9d2.png)

![image](https://user-images.githubusercontent.com/501740/147732100-b9c92a09-0476-47e9-9c33-d91f3208aeb2.png)

**Comment by hepin1989** [comment]
with the using of  `throttle` and `groupedWithin`.

**Comment by patriknw** [comment]
What interval do you use for throttle and groupedWithin?

**Comment by hepin1989** [comment]
@patriknw 900ms

**Comment by hepin1989** [comment]
I have nearly 10,000 concurrent streams
