### ISSUE TITLE
Persistence plugin-dispatcher defaults to pinned dispatcher

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31058]
Would be better to use the default dispatcher as default. Would it be too risky to change that in a patch version?

**Comment by johanandren** [comment]
Is it the dispatcher where the actual plugin is running (and if it is badly written and blocks it will starve the dispatcher) or is it only used for the persistence internals interacting with the plugin?

**Comment by patriknw** [comment]
The Journal and SnapshotStore actors are started with this dispatcher.

>  if it is badly written and blocks it will starve the dispatcher

yes, that's the risk

Maybe we have to leave it as in for 2.6.x and add the plugin-dispatcher config in the plugins we care about.

**Comment by johanandren** [comment]
Sound like the safe path to take, and then change this in Akka 2.7.
