### ISSUE TITLE
ActorSystem local registry for topics

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31053]
The current topic API expects users to spawn and keep track of their topics themselves (multiple instances of the same topic in the same actor system is allowed). 

Often when using topics, in a clustered app, I expect that you are after one topic actor instance per node and topic. Implementing that isn't a lot of work but it could be nice with an extension spawning topics making sure the same topic only spawns one actor, and that the protocol is the same (at runtime), something like:

```
val topic: ActorRef[T] = PubSubTopics(system).topic[T](name)
```

**Comment by patriknw** [comment]
I think that would be nice.

**Comment by johanandren** [comment]
Another use case where this would be useful: 

Imagine a HTTP or gRPC endpoint where clients subscribe and publish to a topic with more or less dynamic topic names (let's say potentially infinite over time) sent by the clients. We'd want many clients subscribing for the same topic to only mean a published message is sent to the node twice. We also don't want each client connecting to do a one off publish to have to wait for the list of subscribers from the receptionist before publishing.

For this we'd need such a registry _and_ a also add Topic actor TTL, counted after last subscriber unsubscribes or a message is published. That way the short lived topic can stay around a while for additional incoming publish or subscribers but go away if not used.

**Comment by johanandren** [comment]
Waiting for review in https://github.com/akka/akka/pull/32262
