### ISSUE TITLE
Why is scala-java8-compat limited to 0.8.0 in Scala 2.12?

### ISSUE THREAD

**Issue by etspaceman** [akka/akka#31064]
Seems that this build has a specific restriction on scala-java8-compat to be 0.8.0 for the Scala 2.12 artifacts. Why is this the case? scala-java8-compat's newest versions are all offered for 2.11, 2.12, 2.13 and 3. 

Some of our internal libraries depend on scala-java8-compat and are running into issues when updating due to the semver differences.

**Comment by patriknw** [comment]
Akka has binary compatibility guarantees and therefore we can't bump the transitive dependencies when those are not compatible. `scala-java8-compat` has not been compatible between the minor versions.

That said, it might work if you override the dependency in your application.

**Comment by SethTisue** [comment]
a useful workaround is

```
ThisBuild / libraryDependencySchemes +=
  "org.scala-lang.modules" %% "scala-java8-compat" % VersionScheme.Always
```

we bumped the scala-java8-compat version to 1.0 not because we broke something, but to communicate our intent around possible _future_ breakage. as far as I know, it's completely safe to swap 1.0.2 in whenever 0.8.0 is expected.

**Comment by SethTisue** [comment]
Incidentally, I'm not convinced by Patrik's interpretation of semver in this case.

I believe that Akka is free to move to 1.0.2 even in a patch version, as per this text on https://semver.org :

> What should I do if I update my own dependencies without changing the public API?

> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. We would usually expect additional code for the latter instance, in which case it’s obviously a minor level increment.

**Comment by patriknw** [comment]
> What should I do if I update my own dependencies without changing the public API?

Here, the transitive dependency is public API, since an application or 3rd library built on top of Akka may also use scala-java8-compat

Great if 1.0.2 is also completely compatible with 0.8.x but I think we'll stick with the conservative approach of not changing the dependency for Scala 2.12
