### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by aaabramov** [akka/akka#31068]
Source file: https://github.com/akka/akka/blob/v2.6.18/akka-docs/src/main/paradox/typed/choosing-cluster.md

Page: https://doc.akka.io/docs/akka/current/typed/choosing-cluster.html#distributed-monolith
Link: https://www.microservices.com/talks/dont-build-a-distributed-monolith/
![image](https://user-images.githubusercontent.com/11317222/149636484-07e8645b-16dc-4eca-932e-308a6c7c61bb.png)

**Comment by johanandren** [comment]
For me the link works, video page with transcript and description is there but video is "unavailable". Looks like it was deleted from youtube for whatever reason, can't find it there either.

**Comment by Captain1653** [comment]
Maybe it will be useful to add at least [some slides](https://www.slideshare.net/datawire/avoid-distributed-monoliths) ?

**Comment by johanandren** [comment]
Not sure that is great either, you'd have to look at slides in one tab and read through transcript in another. Maybe we should just drop that link.

**Comment by Captain1653** [comment]
I can drop if it's needed  . :)
