### ISSUE TITLE
On upstream end for statefulMapConcat

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31077]
In many use cases where `statefulMapConcat` could be useful the fact that it can only react on element coming from upstream and not upstream completing is a show stopper, think some form of batching/caching/grouping, when the stream ends the in-progress aggregate is lost.

Would be nice with an added lambda `() => Seq[Out]` that is invoked when the upstream ends, where the returned seq is emitted downstream before the statefulMapConcat completes.

**Comment by hepin1989** [comment]
@johanandren How can the below singature closing over the state inside `f`
```scala
  def statefulMapConcat[T](f: () => Out => IterableOnce[T],
                           onComplete: () => IterableOnce[T]): Repr[T]
```
should we define the current f as:
```scala
 trait StatefulMapConcatFunction[-In, +Out] extends (In => IterableOnce[Out]) {
    def onComplete(): IterableOnce[Out] = Nil
  }
```

**Comment by hepin1989** [comment]
Yes I was trying to something like:
```scala
trait StatefulMapConcatMapper[In, Out] {
  def emit(in:In): IterableOnce[Out]
  def onComplete():IterableOnce[Out]
}
```
and 
```scala
def statefulMapperConcat[T](f: StatefulMapConcatMapper[Out,T]): Repr[T]
```

**Comment by hepin1989** [comment]
How about name it with statefulCollect？and define it with
```scala
trait StatefulEmitter[In, Out] {
  def onStart():Unit
  def emit(in:In): IterableOnce[Out]
  def onComplete():IterableOnce[Out]
}
```

and 
```scala
def statefulMapperConcat[T](factory: StatefulEmitterFactory[Out,T]): Repr[T]
```

**Comment by hepin1989** [comment]
https://github.com/akka/akka/issues/22730 Keep in mind

**Comment by johanandren** [comment]
I think having an `onStart` will lead users to share the same object and doing unsafe things. I think the `onStart` should instead the construction of the stateful object and not a separate method.

Perhaps something closer to `unfoldResource` would cover both this need and #22730.

```scala
def statefulMap[State](
  create: () => State, 
  mapElement: (In, State) => (Out, State), 
  onComplete: (State) => Option[Out])
```

`State` could of course also be mutable, but to handle both mutable and immutable cases I think we'd have to pass next state along like this rather than have the per-element call only return out like `unfoldResource`

Optionally emitting can be done by using `Option`/`Optional` and composing with a flattening operator.
The current `statefulMapConcat` emit zero to many/`concat` part can also be achieved with composition, with `.statefulMap(...emit seq...).mapConcat(identity)`.

Looking through the doc sources I see we actually already have a sample for composing such a stateful map using existing operators, second sample here: https://doc.akka.io/docs/akka/current/stream/operators/Flow/lazyFlow.html It does not show `onComplete` but that is also possible by composing with `concat`.

Might still be worth a separate factory/operator though.

**Comment by hepin1989** [comment]
I have updated with a pr to take a try but the original issue of the `statefulMapConcat` is still there.

**Comment by johanandren** [comment]
Once we have a way to achieve that same behavior with statefulMap I think we can close this, possibly adding a mention of the way to compose it to the statefulMapConcat docs.

**Comment by hepin1989** [comment]
Update with a test which shows the origin problem
```scala
    "test statefulMapConcat lost when grouped in 3" in {
      Source(1 to 10)
        .statefulMapConcat(() =>{
          var buffer = List.empty[Int]
          x => {
            buffer = x :: buffer
            if (buffer.size == 3) {
              val result = buffer.reverse
              buffer = List.empty
              result
            } else List.empty[Int]
          }
        })
        .alsoTo(Sink.foreach(println))
        .runWith(TestSink.probe[Int])
        .request(10)
        .expectNextN(List(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
        .expectComplete()
    }
```
