### ISSUE TITLE
ByteStrings apply traverses Vector multiple times

### ISSUE THREAD

**Issue by desmondyeung** [akka/akka#31070]
The `apply` method for scala's Vector is logarithmic. 

For fragmented ByteStrings, the `apply` method will call `bytestrings(pos)` multiple times, re-performing the logarithmic lookup. 
```scala
    def apply(idx: Int): Byte = {
      if (0 <= idx && idx < length) {
        var pos = 0
        var seen = 0
        while (idx >= seen + bytestrings(pos).length) {
          seen += bytestrings(pos).length
          pos += 1
        }
        bytestrings(pos)(idx - seen)
      } else throw new IndexOutOfBoundsException(idx.toString)
    }
 ```

I actually ran into this because I was writing some custom HTTP parsing fairly similar to this [method](https://github.com/akka/akka-http/blob/main/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala#L283-L293) in akka-http which performs repeated indexed lookups as  it traverses down the ByteString and was running into performance issues on really fragmented ByteStrings.

I have changes in the following [commit](https://github.com/desmondyeung/akka/commit/e9fa730cf20f8ff659f9eb3063c140b7b91f029e) which includes a JMH benchmark with the following results:
```
    akka-bench-jmh/jmh:run -f 1 -wi 3 -i 3 .*ByteString_apply_Benchmark.*

    2.12 original
    ByteString_apply_Benchmark.bss_apply_best_case   thrpt    3  204261596.303 ± 94507102.894  ops/s
    ByteString_apply_Benchmark.bss_apply_worst_case  thrpt    3     170359.149 ±   102901.206  ops/s

    2.12 optimized
    ByteString_apply_Benchmark.bss_apply_best_case   thrpt    3  206985005.270 ± 7855543.098  ops/s
    ByteString_apply_Benchmark.bss_apply_worst_case  thrpt    3     437929.845 ±   27264.190  ops/s

    2.13 original
    ByteString_apply_Benchmark.bss_apply_best_case   thrpt    3  206854021.793 ± 81500220.451  ops/s
    ByteString_apply_Benchmark.bss_apply_worst_case  thrpt    3     237125.194 ±   128394.832  ops/s

    2.13 optimized
    ByteString_apply_Benchmark.bss_apply_best_case   thrpt    3  209266780.913 ± 6821134.296  ops/s
    ByteString_apply_Benchmark.bss_apply_worst_case  thrpt    3     430348.094 ±   24412.915  ops/s
 ```

Let me know if this makes sense and I can open a PR.

**Comment by ennru** [comment]
Optimised with #31075
