### ISSUE TITLE
EventSourcedBehaviorTestKit initial state setup

### ISSUE THREAD

**Issue by ptrdom** [akka/akka#31074]
Lagom's `PersistentEntityTestDriver` has the `initialize(snapshotState: Option[S], events: E*)` method that allows simplified setup for initial `PersistentEntity` state in tests - no need to run a bunch of commands to achieve it. Is there a good reason why such method was skipped for `EventSourcedBehaviorTestKit`, and if not, would it be a good idea to implement it?

**Comment by johanandren** [comment]
Sounds like it could be a nice addition to the testkit, please PR if you like!
