### ISSUE TITLE
javadsl.ClusterSharding Typed : withRole also sets datacenter

### ISSUE THREAD

**Issue by Vicopol** [akka/akka#31098]
`Entity.of(...).withRole("backend") `:

1. sets entity's role with "backend" value : OK
2. but ALSO sets datacenter with "backend" : NOT OK !

As a result, my shard region is always running as a proxy.

I think there is a typo in method Entity#copy at line 331 of akka.cluster.sharding.typed.javadsl.ClusterSharding.scala in version 2.6.18. Instead of
`dataCenter: Optional[String] = role): Entity[M, E] = {`

It should be
`dataCenter: Optional[String] = datacenter): Entity[M, E] = {`

akka.cluster.sharding.typed.scaladsl.ClusterSharding.scala looks OK.

**Comment by patriknw** [comment]
@Vicopol Thanks for reporting. Would you be able to open a PR to fix the issue?
