### ISSUE TITLE
Add attributes method to `Graph`?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#31142]
I think this will be helpful when want to read some attributes from graph when compose it.

**Comment by johanandren** [comment]
Do you have some more concrete use case of when you'd want to read those attributes and not inside of a custom graph stage, would it be for debugging?

**Comment by hepin1989** [comment]
Like if I have a group of `Source` which has statictly priority associated via `addAttributes(Attributes.Priority)` , then when I combile then with GraphDSL ,I can read the attributes from it directly .

**Comment by johanandren** [comment]
Ok, so it is to inspect attributes, not from inside a graph stage but from "the outside" when composing graphs, seems like a reasonable use case.
