### ISSUE TITLE
Expose `akka.stream.impl.io.ByteStringParser$ParsingException` as public

### ISSUE THREAD

**Issue by JustinPihony** [akka/akka#31245]
Play can throw [the following exception](https://github.com/akka/akka/blob/7abc41cf4e7e8827393b181cd06c5f8ea684e696/akka-stream/src/main/scala/akka/stream/impl/io/ByteStringParser.scala#L180) while processing data:

> akka.stream.impl.io.ByteStringParser$ParsingException: Parsing failed in step inflating

And, as this is an internal exception it cannot be handled at that level. It ends up requiring catching the higher level exception (ie `java.util.zip.DataFormatException`), which is not good for all cases.

**Comment by jrudolph** [comment]
Maybe we can provide a way to offer a custom exception for each stage using/implementing ByteStringParser? That could then be public. After all the ParsingException really is internal and exposing it might not help in general case to understand or handle an error in an accurate way.

**Comment by will-sargent-eero** [comment]
I don't see how the ParsingException (or any exception really) can be internal in this situation, since it's a stage failure.  As soon as you materialize it, 

```

**Comment by jrudolph** [comment]
For now we removed the extra wrapping in `ParsingException` so that will never thrown. Stages using `ByteStringParser` should still make sure to throw meaningful exceptions.

Would that be enough for your use case, @will-sargent-eero ?

**Comment by jrudolph** [comment]
:+1: so let's close this issue for now.
