### ISSUE TITLE
Add statefulMap？

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#31269]
I find it sometime useful, currently I can implement it as :
```scala
  implicit class FlowOpsExt [In, Out, Mat](val flow:Flow[In, Out, Mat]) extends AnyVal {
    def statefulMap[Out2](f: () => Out => Out2): Flow[In, Out2, Mat] = {
      flow.statefulMapConcat(() => {
        val f2 = f()
        elem => List(f2(elem))
      })
    }
  }
```

**Comment by johanandren** [comment]
On the fence if this is worth a dedicated factory, relatively easy compose yourself and also to just use `statefulMapConcat` directly with the slight added syntactic overhead.
