### ISSUE TITLE
Support behavior like API in stageActor?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31268]
Currently the Stage actor's receive api is more lke the classical one, and is not easy to change the behavior of it. I think it would be great to support a subset of the the current typed behavior like api when get a stageActor, which can change its behavior after processing a message

**Comment by johanandren** [comment]
That would be nice but I don't think the value of that outweighs the complexity it would require to implement (which I think would be a lot). The stage actor is quite a super user feature and while a public API I don't expect wide usage outside of Akka internals.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for more than 1 year.

Should this issue be closed?

**Comment by patriknw** [comment]
Let's close. Stage API is anyway very low level.
