### ISSUE TITLE
Failed: ReliableDeliveryShardingSpec

### ISSUE THREAD

**Issue by pvlugter** [akka/akka#31263]
https://github.com/akka/akka/runs/5608122450?check_suite_focus=true#step:5:35271

```
[info] - must deliver unconfirmed if ShardingConsumerController is terminated *** FAILED *** (1 second, 730 milliseconds)
[info]   Job(msg-3) did not equal Job(msg-4) (ReliableDeliveryShardingSpec.scala:402)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.$anonfun$new$15(ReliableDeliveryShardingSpec.scala:402)
```

Similar to #30664, but failing at the check after the one fixed in #31234.

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5669097311?check_suite_focus=true#step:5:35286

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5802654121?check_suite_focus=true#step:5:35402

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5842952320?check_suite_focus=true#step:5:5821

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5842968102?check_suite_focus=true#step:5:34760

**Comment by hepin1989** [comment]
https://github.com/akka/akka/runs/6046259746?check_suite_focus=true#step:5:33745

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/6121259066?check_suite_focus=true#step:5:36593

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5999495589?check_suite_focus=true#step:5:36098

**Comment by jrudolph** [comment]
https://github.com/akka/akka/runs/6167388221?check_suite_focus=true#step:5:36778

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/6250668284?check_suite_focus=true

Happened again despite fix in #31370

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6431289361?check_suite_focus=true#step:5:36907

```
[05-14 01:11:44.026] [info] - must illustrate sharding usage with several producers *** FAILED *** (4 seconds, 664 milliseconds)
[05-14 01:11:44.026] [info]   Set("p1-2-entity-1", "p2-2-entity-1", "p1-2-entity-2", "p2-2-entity-2") did not equal Set("p1-2-entity-2", "p1-2-entity-1", "p2-2-entity-2", "p1-2-entity-0", "p2-2-entity-0", "p2-2-entity-1") (ReliableDeliveryShardingSpec.scala:161)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6437741361?check_suite_focus=true#step:5:36099

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/6480649003?check_suite_focus=true#step:5:31061

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/6765306742?check_suite_focus=true#step:5:36086

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/6803964312?check_suite_focus=true

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/7014727780?check_suite_focus=true#step:5:36579

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/7014727895?check_suite_focus=true#step:5:36881

**Comment by guiwoda-inviu** [comment]
Is this issue absolutely required for 2.6.20?
We're currently using 2.6.19 and still waiting for the vulnerability fixes that were introduced in April regarding jackson. It'd be great to have a patch release with that vuln fixed asap.

**Comment by octonato** [comment]
@guiwoda-inviu, this issue is for tracking a flaky test and has nothing to do with jackson. 

About the vulnerability in Jackson, you should not wait for an Akka release. You should bump the Jackson version in your project. In case you find any Akka related issue while bumping the Jackson version, please open an new issue describing the problem.

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/7551108836?check_suite_focus=true#step:5:37003

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/8061594648?check_suite_focus=true#step:5:35993

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/8180351694?check_suite_focus=true#step:5:36528

**Comment by He-Pin** [comment]
https://github.com/akka/akka/actions/runs/3050597628/jobs/4917861326#step:5:34164

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3066558532/jobs/4951869225#step:5:36320

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3132012759/jobs/5083927996#step:5:37435

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3193592614/jobs/5212304750#step:5:36778

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3223208446/jobs/5273039067#step:5:36517
