### ISSUE TITLE
CompletionStage#join should not be used in docs

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#31302]
![image](https://user-images.githubusercontent.com/501740/161053291-133830fe-4ea7-43bf-b278-247c56f484f6.png)
Even it's used after the `allOf` call, but that can be replaced without any `join`。

**Comment by patriknw** [comment]
Good catch. That is indeed a terrible example to show in docs.

**Comment by uazw** [comment]
Hi Guys, I'd like to fix this one as my first PR to akka, but it seems I need approved to run the workflows, not sure if you can help me?

**Comment by octonato** [comment]
@uazw, approved!
