### ISSUE TITLE
Fallback `copyUSAsciiStrToBytesAlgorithm` to 0 

### ISSUE THREAD

**Issue by gervaisb** [akka/akka#31323]
This relates to this discussion: https://github.com/akka/akka/pull/23710#issuecomment-1091817062 where Akka-actor, and more precisely `akka.util.Unsafe` fail on Android because `String` has no `value` filed on Android.

Falling back to `copyUSAsciiStrToBytesAlgorithm = 0` in such cases will make the system a bit more tolerant.

**Comment by hepin1989** [comment]
@gervaisb Will you make a pr about it?

**Comment by gervaisb** [comment]
I would like yes. But cannot provide any estimates.
