### ISSUE TITLE
More detail in `akka.actor.ActorInitializationException`?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#31348]
From https://discuss.lightbend.com/t/actorcell-changing-recreate-into-create-after-akka-actor-actorinitializationexception/9686

How about adjust it a little, like:
```scala
akka.actor.ActorInitializationException: akka://FaultHandlingTest/user/supervisor/$a: exception during creation, root cause message:[Boom!] at line:[jdocs.actor.FaultHandlingTest$Child.<init>(FaultHandlingTest.java:126)]
```

**Comment by patriknw** [comment]
Sounds good to include the cause message, but probably not the line number. The original cause should (I don't know if it is)  be included as `cause` of the ActorInitializationException and then it should be included in the logged stack trace.
