### ISSUE TITLE
Akka Streams has transitional dependency to 2.13 library in Scala 3 version

### ISSUE THREAD

**Issue by OndrejSpanel** [akka/akka#31359]
Note following `dependencyTree` report  from a Scala 3 SBT project using `"com.typesafe.akka" %% "akka-stream" % "2.6.19"`. It shows the library is linked against 2.13 version of _scala-parser-combinators_, while Scala 3 version exists.

```text
[info]   +-com.typesafe.akka:akka-stream_3:2.6.19
[info]   | +-com.typesafe.akka:akka-actor_3:2.6.19
[info]   | | +-com.typesafe:config:1.4.2
[info]   | | +-org.scala-lang.modules:scala-java8-compat_3:1.0.0
[info]   | | | +-org.scala-lang:scala3-library_3:3.0.0 (evicted by: 3.1.2)
[info]   | | | +-org.scala-lang:scala3-library_3:3.1.2 [S]
[info]   | | |
[info]   | | +-org.scala-lang:scala3-library_3:3.1.1 (evicted by: 3.1.2)
[info]   | | +-org.scala-lang:scala3-library_3:3.1.2 [S]
[info]   | |
[info]   | +-com.typesafe.akka:akka-protobuf-v3_3:2.6.19
[info]   | +-com.typesafe:ssl-config-core_2.13:0.4.3 [S]
[info]   | | +-com.typesafe:config:1.4.0 (evicted by: 1.4.2)
[info]   | | +-com.typesafe:config:1.4.2
[info]   | | +-org.scala-lang.modules:scala-parser-combinators_2.13:1.1.2 [S]
[info]   | |
[info]   | +-org.reactivestreams:reactive-streams:1.0.3
[info]   | +-org.scala-lang:scala3-library_3:3.1.1 (evicted by: 3.1.2)
[info]   | +-org.scala-lang:scala3-library_3:3.1.2 [S]
```

It seems this is because of [ssl-config-core](https://mvnrepository.com/artifact/com.typesafe/ssl-config-core), which is used in 0.4.3, and this version does not have a Scala 3 version.

I undestand the PR updating ssl-config-core https://github.com/akka/akka/pull/31046 was reverted again in https://github.com/akka/akka/pull/31252.

If ssl-config-core 0.6.1 cannot be used, could at least its transitional dependency to 2.13 parser-combinators be replaced with their 3.x counterparts for Scala 3 version?

**Comment by raboof** [comment]
I think this should already be fixed on the main branch, though indeed not yet in 2.6.19 . Could you try with a nightly build?

**Comment by hepin1989** [comment]
@OndrejSpanel https://doc.akka.io/docs/akka/current/project/links.html#snapshots-repository
https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/akka/akka-actor_2.13/

**Comment by OndrejSpanel** [comment]
I confirm this is fixed. The akka-stream dependency tree now looks like this:

```text
[info]   +-com.typesafe.akka:akka-stream_3:2.6.19+52-00c1da99-SNAPSHOT
[info]   | +-com.typesafe.akka:akka-actor_3:2.6.19+52-00c1da99-SNAPSHOT
[info]   | | +-com.typesafe:config:1.4.2
[info]   | | +-org.scala-lang:scala3-library_3:3.1.2 [S]
[info]   | |
[info]   | +-com.typesafe.akka:akka-protobuf-v3_3:2.6.19+52-00c1da99-SNAPSHOT
[info]   | +-com.typesafe:ssl-config-core_3:0.6.1
[info]   | | +-com.typesafe:config:1.4.2
[info]   | | +-org.scala-lang:scala3-library_3:3.0.2 (evicted by: 3.1.2)
[info]   | | +-org.scala-lang:scala3-library_3:3.1.2 [S]
[info]   | |
[info]   | +-org.reactivestreams:reactive-streams:1.0.3
[info]   | +-org.scala-lang:scala3-library_3:3.1.2 [S]
```

It seems ssl-config-core 0.6.1 is no longer using parser-combinators at all, which is confirmed by looking a compile dependencies at https://mvnrepository.com/artifact/com.typesafe/ssl-config-core_3/0.6.1
