### ISSUE TITLE
Operator to pass element through resource

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31355]
An operator `withResource`/`mapWithResource` that delegates to `statefulMap` but correctly sets the safe blocking io dispatcher.

_Originally posted by @johanandren in https://github.com/akka/akka/pull/31330#discussion_r854957331_

**Comment by hepin1989** [comment]
What if the resource's creation and release is an asynchronous operation?

**Comment by johanandren** [comment]
For resource we have a specific operator for that, `unfoldResourceAsync`, but a corresponding operator can't be composed with `statefulMap` as far as I can see, so that would be a bigger task (and/or need a `statefulMapAsync` first).

**Comment by hepin1989** [comment]
I see, maybe that can be built with the blocks from https://github.com/akka/akka/pull/28674
