### ISSUE TITLE
Add Flux#transform like operator?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31363]
refs: https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#transform-java.util.function.Function-
This will make the syntax more fluent

**Comment by johanandren** [comment]
Please describe the use case you have and how an operator API would look to cover that use case.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for more than 1 year.

Will it be better to add some use cases or close it?
