### ISSUE TITLE
Add Sink.collect which accepts a java.util.stream.Collector for Javadsl?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31362]
The current API is great with `fold` and `reduce` but I think it can be simpler with direct collector support.
```scala
def collect[In, A, T](() => collector: java.util.stream.Collector[In, A, T]): Sink[In, CompletionStage[T]]
```

**Comment by hepin1989** [comment]
it can be achieved with StreamConverters

**Comment by patriknw** [comment]
Sounds like a good idea.

**Comment by hepin1989** [comment]
refs: https://github.com/akka/akka/issues/27298

**Comment by He-Pin** [comment]
I think this is done.
