### ISSUE TITLE
Akka Actor: ActorContext.stop() does not cancel previously scheduled receiveTimeout

### ISSUE THREAD

**Issue by akilegaspi** [akka/akka#31396]
We've encountered a bug in our application where a stopped Actor that has previously invoked `setReceiveTimeout` is still receiving a `ReceiveTimeout` message.

Upon inspection of the codebase I've noticed that on 1/19/22, this change was introduced to `akka.actor.dungeon.ReceiveTimeout`:

```
private def cancelReceiveTimeoutTask(): Unit =
    if (receiveTimeoutData._2 ne emptyCancellable) {
      receiveTimeoutData._2.cancel()
      receiveTimeoutData = (receiveTimeoutData._1, emptyCancellable)
    }
```

This function was previously named as `cancelReceiveTimeout()`, which I believe was the function being called in `akka.actor.dungeon.FaultHandling`'s termination functions like `terminate()` or `faultCreate()` et al.

It was expected that `cancelReceiveTimeout()` would cancel the scheduled job but upon taking a closer look into the code it executes, it references directly to the function `AbstractActor.ActorContext.cancelReceiveTimeout()`

Here is a minimum project that demonstrates the bug
https://github.com/akilegaspi/akka-receivetimeout-bug

**Comment by He-Pin** [comment]
Ok ,I will take a look at it tomorrow。

**Comment by He-Pin** [comment]
@akilegaspi Sorry about that, I will add a test to cover this soon.
