### ISSUE TITLE
Jackson serializer doesn't support scala3 enum

### ISSUE THREAD

**Issue by liutaon** [akka/akka#31399]
We are trying to migrate the scala2 project to scala3, and use the enum of scala3 to define the message of akka, but there is a serialization runtime error when calling, as shown below

```
Versions:
Scala: 3.1.2
Akka: 2.6.19
SBT: 1.6.2
```

```scala
enum Command extends Jackson:
  case ToUpper(value: String, replyTo: ActorRef[StatusReply[String]])
```

```
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: 
Cannot construct instance of `Command$ToUpper`, problem: Cannot reflectively create enum objects
```

**Comment by johanandren** [comment]
I think that should be reported upstream in the https://github.com/FasterXML/jackson-module-scala

**Comment by johanandren** [comment]
Upstream existing issue, with link to separate module supporting Scala 3 enums: https://github.com/FasterXML/jackson-module-scala/issues/501

**Comment by patriknw** [comment]
Agree with Johan
