### ISSUE TITLE
akka.stream.Tcp outgoing connection flow restart for broken connection

### ISSUE THREAD

**Issue by syspulse** [akka/akka#31400]
The following snippets for outgoing Tcp connection:
`val flowTcp = Tcp().outgoingConnection("127.0.0.1",1883).log("TCP")
 val flowTcpRestart = RestartFlow.onFailuresWithBackoff(restartSettings)(() => flowTcp)`

1. Works for initial connection when tcp server is not available: keeps restarting the flow
2. Does not restart the flow when tcp server was shutdown or restarted.

**Comment by raboof** [comment]
> Does not restart the flow when tcp server was shutdown or restarted

When the TCP server shuts down, does it complete gracefully or abort the connection?

If it completes gracefully, but you want your flow to reconnect anyway, you might want `RestartFlow.withBackoff` rather than `RestartFlow.onFailuresWithBackoff`?

**Comment by syspulse** [comment]
> When the TCP server shuts down, does it complete gracefully or abort the connection?
I checked with tcpdump and realized my connection tests for server kill (RST) were after shutdown (FIN, RST) 
You suggestion works as expected thank you!
