### ISSUE TITLE
Add official support for JDK 17

### ISSUE THREAD

**Issue by JustinPihony** [akka/akka#31414]
This is a ticket to officially support [the newest long term Java version, 17](https://www.oracle.com/news/announcement/oracle-releases-java-17-2021-09-14/).

**Comment by He-Pin** [comment]
I think this would be very cool, in the Kalix, the JDK version bump to 11.

**Comment by He-Pin** [comment]
https://openjdk.java.net/jeps/410 ,some documents about the AOT in the Akka doc should be removed too.

**Comment by johanandren** [comment]
One thing missing before we can do that is #31087
