### ISSUE TITLE
Warnings in multinode tests - gcp auth plugin deprecated

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31411]
```
2022-05-16T04:07:53.4971796Z To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
2022-05-16T04:07:53.6939472Z [error] W0516 04:07:53.693601  104660 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
```

**Comment by ankitg1984** [comment]
I fixed this problem by adding the correct export in .bashrc

`export USE_GKE_GCLOUD_AUTH_PLUGIN=True
`After sourcing .bashrc with . ~/.bashrc and reloading cluster config

**Comment by ankitg1984** [comment]
> ```
> 2022-05-16T04:07:53.4971796Z To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
> 2022-05-16T04:07:53.6939472Z [error] W0516 04:07:53.693601  104660 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
> ```

I fixed this problem by adding the correct export in .bashrc

`export USE_GKE_GCLOUD_AUTH_PLUGIN=True `
After sourcing .bashrc with . ~/.bashrc and reloading cluster config

**Comment by bczoma** [comment]
@ankitg1984 the export solution worked for me, wondering where you got this fix from? Maybe I was googling at the wrong places but couldn't find anything that worked for me before I came across you post, Thank you!
