### ISSUE TITLE
TLS session is updated too late for TLS 1.3

### ISSUE THREAD

**Issue by raboof** [akka/akka#31419]
When acting as a TLS server, in `TLSActor.doUnwrap`, the `currentSession` is updated when `engine.unwrap`'s `result.getHandshakeStatus` is `FINISHED`.

However, at least with TLS 1.3, it is possible for `engine.unwrap` to return `NEED_TASK` after receiving the client authentication, then `NEED_WRAP` after reading the first chunk of application data, and only then `FINISHED`. This leads to the first chunk of application data to be delivered to the user code with the 'old', unauthenticated session.

(this not a security concern: when the client authentication fails this application data will not be consumed at all).

~It would be nice if we could just assume any application data will come in after the client certificate is checked, but I'm not yet confident this is the case.~

This is the root cause of https://github.com/akka/akka-http/issues/4122, see that issue for a reproducer.

**Comment by jrudolph** [comment]
TLS 1.3 allows [0-RTT early client data](https://www.rfc-editor.org/rfc/rfc8446#section-2.3) which is not secured against replay attacks (because it is encrypted using a fixed PSK before DHE is finished). Auth data will only be sent in the second client packet (see [Figure 1](https://www.rfc-editor.org/rfc/rfc8446#section-2)).

Could it be that we see a 0-RTT early data packet here?

**Comment by jrudolph** [comment]
I can rule out a 0-RTT case, it seems to happen if the first data arrives in the same TCP packet as the `Finished` TLS handshake packet.

**Comment by jrudolph** [comment]
0-RTT doesn't even seem to be implemented in the JVM: https://bugs.openjdk.org/browse/JDK-8049402

**Comment by adibaranga** [comment]
@jrudolph  @raboof  is this ticket (potentially) fixed? Thanks!

**Comment by raboof** [comment]
> @jrudolph @raboof is this ticket (potentially) fixed? Thanks!

No, we have a tentative fix in the works at #31433 though. If you want to avoid the issue you could either configure your server to only do TLSv1.2, or perhaps build a local snapshot of the Akka artifacts from #31433

**Comment by adibaranga** [comment]
@raboof thanks for your quick response. Unfortunately, downgrading to  TLSv1.2 is not an option for us, we will wait for the fix to be released.
