### ISSUE TITLE
ActorAdapter logging can't be controlled

### ISSUE THREAD

**Issue by alanbur** [akka/akka#31428]
When an exception is thrown by an Actor, `ActorAdapter.scala` always logs an error even if the exception is subsequently handled by a `onSignal` method.  If `onSignal` handles and logs the error, it ends up being logged twice. There seems to be no way of overriding this unwanted behaviour.

```
245          // log at Error as that is what the supervision strategy would have done.
246          ctx.log.error(logMessage, ex)
```

**Comment by johanandren** [comment]
`.spawn(Behaviors.supervise(Periscope(..))..., "Periscope")` if you want to define it at spawn site, or inside of the `apply` method if you want to define it together  with the actor behavior.

**Comment by johanandren** [comment]
I think it is covered fairly well in the doc page linked up top about "For details on how that translates into real code, please refer to [supervision](https://doc.akka.io/docs/akka/current/typed/fault-tolerance.html)."

**Comment by patriknw** [comment]
Looks like this is covered
