### ISSUE TITLE
keep InternalStableApi stable between 2.6.19 and 2.6.20

### ISSUE THREAD

**Issue by raboof** [akka/akka#31431]
In https://github.com/akka/akka/pull/31129/files#diff-693b35aa5ba7e2352142084356adf38dff2a42906b7433871ee39069754ffe1aR661-R662 we changed a method marked `InternalStableApi`, perhaps we should keep that parameter (and ignore it)?

**Comment by johanandren** [comment]
Worth checking if that original PR broke it with the new third parameter and the revert maybe fixed it rather than broke anything.
