### ISSUE TITLE
Akka-stream overlaps elements processing and implicitly changes processing thread

### ISSUE THREAD

**Issue by sergeypiachonik** [akka/akka#31443]
Hi. Looks like very dangerous bug introduced somewhere between 2.13:2.6.0(not affected) and 2.13:2.6.10 (I didn't check intermediate versions), latest version 2.13:2.6.19 is also affected.

Running of code below leads to next effects:
1) Flow from chainAsyncWrapped() may be stopped at any random point, then other element processing starts by chainAsyncWrapped() , then flow returns to the first one. So elements processing overlaps each other within one flow. This is reproducible permanently 
2) Processing stop/start can change processing thead and as a result not synchronized objects (basically means almost all object) may be damaged. This is hard to reproduce, I was able to reproduce this only once with code below, but able to reproduce this regularly on real codebase

Issue on stackoverflow with additional details:
https://stackoverflow.com/questions/72686826/akka-stream-implicitly-change-execution-thread

Environment: 
java version: 
openjdk zulu 11.0.12
os version: 
Mac OS X 10.15.7
architecture:
x86_64

```
package foo.bar;

import akka.Done;
import akka.NotUsed;
import akka.actor.ActorSystem;
import akka.japi.function.Predicate;
import akka.stream.ActorAttributes;
import akka.stream.OverflowStrategy;
import akka.stream.Supervision;
import akka.stream.javadsl.Flow;
import akka.stream.javadsl.Keep;
import akka.stream.javadsl.Sink;
import akka.stream.javadsl.Source;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.mutable.MutableInt;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.atomic.AtomicReference;

@Slf4j
@RequiredArgsConstructor
public class ThreadingIssueExample {
  private static ActorSystem actorSystem;

  static {
    Map<String, Object> properties = new HashMap<>();
    properties.put("akka.stream.materializer.initial-input-buffer-size", 4);
    properties.put("akka.stream.materializer.max-input-buffer-size", 16);
    Config customConf = ConfigFactory.parseMap(properties);
    actorSystem = ActorSystem.create("test", customConf);
    actorSystem.logConfiguration();
  }

  public static void main(String... args) throws ExecutionException, InterruptedException {
    getStreamCf(20).get();
  }

  public static CompletableFuture<Done> getStreamCf(int count) {
    CompletionStage<Done> completionStage = Source
        .range(0, count)
        .map(param -> new FooBarEntity(param, new MutableInt(param)))
        .async()
        .buffer(200, OverflowStrategy.backpressure())
        .async()
        .map(param -> {
          log.info("main start. {}", param);
          return param;
        })
        .via(chainAsyncWrapped())
        .map(param -> {
          log.info("main end. {}", param);
          return param;
        })
        .toMat(Sink.ignore(), Keep.right())
        .withAttributes(ActorAttributes.supervisionStrategy(t -> {
          log.error("Supervision strategy received an error. Stopping", t);
          return (Supervision.Directive) Supervision.stop();
        }))
        .run(actorSystem);
    return completionStage.toCompletableFuture();
  }

  public static Flow<FooBarEntity, FooBarEntity, NotUsed> chainAsyncWrapped() {
    AtomicReference<Integer> id = new AtomicReference<>(null);

    Flow<FooBarEntity, FooBarEntity, NotUsed> chainAsyncWrapped = Flow.<FooBarEntity>create().map(param -> {
      log.info("async start. {}", param);
      if (Objects.isNull(id.get())) {
        id.set(param.getId());
      } else {
        log.error("Thread ovelap detected. Current: {}, cannot start: {}", id.get(), param.getId());
      }
      return param;
    }).via(createChainFlow()).map(param -> {
      if (!param.getId().equals(id.get())) {
        log.error("Thread ovelap detected. Current: {}, cannot end: {}", id.get(), param.getId());
      } else {
        id.set(null);
      }
      log.info("async end. {}", param);
      return param;
    });
    return chainAsyncWrapped.async();
  }


  public static Flow<FooBarEntity, FooBarEntity, NotUsed> createChainFlow() {
    Flow<FooBarEntity, FooBarEntity, NotUsed> fullFlow = Flow.create();

    for (int i = 0; i < 4; i++) {
      Flow<FooBarEntity, FooBarEntity, NotUsed> filter = Flow
          .<FooBarEntity>create()
          .filter((Predicate<FooBarEntity>) fooBarEntity -> {
            spinAndUpdate(fooBarEntity);
            return true;
          });
      fullFlow = fullFlow.via(filter);
    }

    return Flow.<FooBarEntity>create().map(param -> {
      log.info("chain start. {}", param);
      return param;
    }).via(fullFlow).map(param -> {
      log.info("chain end. {}", param);
      return param;
    });
  }

  public static void spinAndUpdate(FooBarEntity fooBarEntity) {
    long start = System.currentTimeMillis();

    while (System.currentTimeMillis() - start < 300) {
      long n = 0;
      for (int i = 0; i < 10000; i++) {
        n = n + i;
      }
    }
    fooBarEntity.getValue().increment();
  }

  @Data
  @AllArgsConstructor
  @RequiredArgsConstructor
  public static class FooBarEntity {
    private Integer id;
    private MutableInt value;
  }
}
```

```
plugins {
    id "java"
}

group = "foo.bar"
sourceCompatibility = "11"

repositories {
    mavenLocal()
    mavenCentral()
}


dependencies {
    implementation "com.typesafe.akka:akka-stream_2.13:2.6.19"
    implementation "org.apache.commons:commons-lang3:3.11"
    implementation "org.slf4j:slf4j-api:1.7.2"
    implementation "ch.qos.logback:logback-classic:1.0.9"
    implementation "ch.qos.logback:logback-core:1.0.9"
    compileOnly "org.projectlombok:lombok:1.18.24"
    annotationProcessor "org.projectlombok:lombok:1.18.24"
}
```

**Comment by johanandren** [comment]
There is no guarantee that a flow with a sequence of operators will be executed by passing one element through each step, like a for loop, before starting with the next one. The only guarantee is ordering, that if element n1 entered the flow before n2 and neither of them are dropped, n1 will come out of the flow before n2 on the other end. 

What you log as "error: Thread orvelap detected" has nothing to do with threads and is as expected.

The actor executing a stream "island" will process a certain number of operations (1000 by default) before handing off the thread back to the threadpool, this means that operations will stop and continue on a potentially different thread, this is also expected and nothing that has changed in a very long while.

Non synchronized mutable shared objects has never been safe with Akka Streams (or Actors for that part). Mutable elements is fine as long as no operator holds on to them after passing them through (elements between asynchronous islands are passed as a message between the actors so there is a happens-before). Since guaranteeing that no operator/stream operation holds on to an object can be tricky the general recommendation would be to go for immutable stream elements when possible.

**Comment by sergeypiachonik** [comment]
Hi @johanandren Thanks for your answer. Answer is clear, but
could you please give final confirmation for "Mutable elements is fine as long as no operator holds on to them after passing them through (elements between asynchronous islands are passed as a message between the actors so there is a happens-before)" a little bit. 

I'm a little bit confused after reading https://doc.akka.io/docs/akka/current/general/jmm.html because there is happens-before for "same actor" mentioned, but for different sender and receiver actors "it would be possible for the receiver to see partially initialized data structures"
At the same time this answer https://stackoverflow.com/a/15851743/19370198 tells that there is "happen-before" relation between actors

Any thread change (implicit or explicit) creates happens-before relation for element
Means if operator A(or actor in other words) changes element and then pass element to operator B(or actor in other words)  with implicit or explicit thread change between them then there will be happens-before relation and changes in element made by operator A will be visible by operator B
Is it correct?
Thanks

**Comment by johanandren** [comment]
Since messages passing an Akka Stream boundary are passed in an actor message between the actors executing the stream operators behind the scenes, the actor send happens-before rule applies.

**Comment by johanandren** [comment]
I'd still recommend to go for immutable messages whenever possible though, to completely avoid a lot of pitfalls.

**Comment by sergeypiachonik** [comment]
> I'd still recommend to go for immutable messages whenever possible though, to completely avoid a lot of pitfalls.

Sure, but sometimes it is just not convenient or will produce a lot of garbage. Thanks for help. I'm closing this issue
