### ISSUE TITLE
new Behavior API or Behaviors DSL like Behavior.interpret but handling Behaviors.same and Behaviors.unhandled correctly like it be used in StashBufferImpl.interpretOne

### ISSUE THREAD

**Issue by GreyPlane** [akka/akka#31466]
## Motivation
receive message from a behavior and execute it in another then switch to that behavior can be done by using Behavior.interpret, but if the interpreter behavior return Behaviors.same or Behaviors.unhandled, it will need extra logic to handle it correctly for this scenario(mostly like interpretOne in StashBufferImpl).
this extra logic is not complicate and probably bcs lack of bit understanding of how Behavior works if anyone did it wrong(no offense, i just did it wrong few days ago). but still, for a pretty common scenario(as my opinion) it requires too much knowledge for the underlying implementation.

## Requested Feature
i made a prototype implementation for clarifying the concept.
https://github.com/GreyPlane/akka/commit/35fc6cc2d72917114b0d414e59c2616afd9b51ca

but there is still a question i want to have more guidance, is there should be a Behavior DSL that do the forward/interpret thing that completely same as StashBufferImpl, or just mimic interpretMessage/interpretSignal that give two respective API.

## Alternative
stash message and unstash it immediately will do the same work.
or just use Behavior.interpret but with caution to make sure not messed up with returned behavior.

**Comment by patriknw** [comment]
The added feature is `ActorContext.forward`
