### ISSUE TITLE
Use SingleConsumerOnlyUnboundedMailbox for stream ActorGraphInterpreter

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31463]
In https://github.com/akka/akka/issues/27125 we saw that SingleConsumerOnlyUnboundedMailbox was slightly faster than the default classic mailbox and set it as default for typed actors, since no balanced pool API is available there. 

Stream actors are also never balanced even though the actor is classic, could be worth trying out our benches with the ActorGraphInterpreter always using SingleConsumerOnlyUnboundedMailbox and see if it makes a difference.

**Comment by He-Pin** [comment]
This would be handy, Will take a try once find time.
