### ISSUE TITLE
Run StreamRefs on top of reliable delivery

### ISSUE THREAD

**Issue by an-tex** [akka/akka#31470]
As suggested by @patriknw in https://github.com/akka/akka/issues/24276#issuecomment-589637748 (and clarified by @johanandren in [discuss.lightbend](https://discuss.lightbend.com/t/current-state-of-bulk-stream-references/9863/2?u=antex)) it makes sense to implement the current StreamRefs (or provide a separate implementation) on top of the new [reliable delivery](https://doc.akka.io/docs/akka/current/typed/reliable-delivery.html#chunk-large-messages). This would allow to use StreamRefs for [large messages](https://doc.akka.io/docs/akka/current/stream/stream-refs.html#stream-references).

This is a follow up ticket to https://github.com/akka/akka/issues/24276 which has been closed.

**Comment by johanandren** [comment]
Duplicate of https://github.com/akka/akka/issues/30103 ?

**Comment by an-tex** [comment]
Oh right, sorry somehow that slipped through
