### ISSUE TITLE
Not very clean examples in docs

### ISSUE THREAD

**Issue by Donzz** [akka/akka#31505]
Hi!

In docs describing event sourcing and persistence you have examples where new command and event handlers are built every time in commandHandler() and eventHandler() methods.
But these methods are invoked for every command and event has come.
So it's better to clarify examples and build command and event handlers once in constructor or somewhere else and use them in pointed methods.
Yes, building up these objects are very simple operations but anyway it needs little bit more resources and, that most important, such code style misleads developers as they can think that commandHandler() and eventHandler() methods are invoked once.

**Comment by johanandren** [comment]
I think the constant re-creation was an oversight, let's see if we can instead switch it over to create the command and event handler once.

**Comment by octonato** [comment]
Fixed in #31507
