### ISSUE TITLE
Add `expectCancellationWithNoMoreElementsNeeded`?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31510]
Which will help distinguishing with the `expectCancellationWithCause` one.

**Comment by johanandren** [comment]
Doesn't `expectCancellationWithCause[NoMoreElementsNeeded]` work?

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for more than 1 year.

Should some context be added or should this issue be closed?
