### ISSUE TITLE
unsafeDataVia doesn't work with Flows which cannot truncate (i.e. gzip compression)

### ISSUE THREAD

**Issue by mdedetrich** [akka/akka#31522]
In PR https://github.com/akka/akka/pull/31123 `unsafeDataVia` was added to `FlowWithContext`/`SourceWithContext` and the implementation was further simplified with https://github.com/akka/akka/pull/31440. Although `unsafeDataVia` works fine in normal cases it doesn't seem to work with `Flow`'s that are sensitive to truncation, such as gzip compression. To illustrate this, the following test

```scala
"unsafeDataVia works with flows which isn't compatible with truncation (i.e. gzip-compression)" in {
  val data = List(("1", 1), ("2", 2), ("3", 3), ("4", 4)).map {
    case (string, int) =>
      (ByteString(string, "UTF-8"), int)
  }

  val compressed = Await.result(SourceWithContext
    .fromTuples(Source(data))
    .unsafeDataVia(Compression.gzip)
    .runWith(Sink.seq), Duration.Inf)
    .map{ case (byteString, _) => byteString}
    .foldLeft(ByteString.empty)(_ ++ _)

  Await.result(Source
    .single(compressed)
    .via(Compression.gunzip())
    .runFold(ByteString.empty)(_ ++ _), Duration.Inf) shouldBe ByteString("1234")
}
```

fails with

```
[info] - must unsafeDataVia works with flows which isn't compatible with truncation (i.e. gzip-compression) *** FAILED *** (2 seconds, 64 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnComplete, found OnError(java.util.zip.ZipException: Truncated GZIP stream
[info] 	at akka.stream.impl.io.compression.GzipDecompressor$$anon$1$Step.onTruncation(GzipDecompressor.scala:28)
[info] 	at akka.stream.impl.io.compression.GzipDecompressor$$anon$1$Step.onTruncation$(GzipDecompressor.scala:28)
[info] 	at akka.stream.impl.io.compression.GzipDecompressor$$anon$1$inflating$.onTruncation(GzipDecompressor.scala:30)
```

The same version using a standard Source with `.via` works as expected, i.e.

```scala
"unsafeDataVia works with flows which isn't compatible with truncation (i.e. gzip-compression)" in {
  val data = List(("1", 1), ("2", 2), ("3", 3), ("4", 4)).map {
    case (string, int) =>
      (ByteString(string, "UTF-8"), int)
  }

  val compressed = Await
    .result(
      Source(data.map { case (string, _) => string })
        .via(Compression.gzip)
        .runWith(Sink.seq),
      Duration.Inf)
    .foldLeft(ByteString.empty)(_ ++ _)

  Await.result(Source
    .single(compressed)
    .via(Compression.gunzip())
    .runFold(ByteString.empty)(_ ++ _), Duration.Inf) shouldBe ByteString("1234")
}
```

**Comment by johanandren** [comment]
> The given flow *must* not re-order, drop or emit multiple elements for one incoming element

Which is something gzip does (flushing and emitting chunks at its own will, not 1:1 with incoming data elements), so expected behavior?

**Comment by mdedetrich** [comment]
Yes evidently I didn't think this through properly when initially implementing `unsafeDataVia` and I didn't realize the internals of gzip compression (i.e. it adds extra chunks because it needs a trailing element etc etc).

Do you know what the ideal way to solve this problem would be? On the top of my head I am thinking of some buffering mechanism whereby for each single element in the data portion of the stream you do the entire gzip compression and then only omit the gzipped element once its fully ready, i.e. just doing `GzipCompressor().compressAndFinish(bytes)` on each element of the stream.

**Comment by johanandren** [comment]
No good idea how to deal with it. Mapping via non streaming compression maybe, or sub materializing a stream per incoming event and then folding that into a single response chunk perhaps, neither seems ideal.

**Comment by raboof** [comment]
So the use case is you have a stream of serialized objects with contexts attached to them, and you want to compress them, presumably send them over the network (?), and decompress them with contexts still attached to the same elements on the 'other side'?

Since this means you have to serialize the contexts anyway, perhaps a solution might be to 
explicitly serialize both the payload and the context before compressing. To be able to deserialize again after decompressing you'll have to use some form of framing to make sure you get the same slices again, so perhaps something like (pseudocode):

```
def serialize(in: (ByteString, Int)): ByteString = ???
def deserialize(in: ByteString): (ByteString, Int) = ???

val flowWithContext: FlowWithContext[ByteString, Int, _]] = ???
flowWithContext
  .asFlow
  .map(serialize)
  .via(Framing.simpleFramingProtocolEncoder(maximumMessageLength))
  .via(Compression.gzip)
  .via(sendToNetwork)

val fromNetwork: Source[ByteString, _]] = ???
fromNetwork
  .via(Compression.gunzip)
  .via(Framing.simpleFramingProtocolDecoder(maximumMessageLength))
  .map(deserialize)
  .via(destinationFlowWithContext)
```

**Comment by mdedetrich** [comment]
> So the use case is you have a stream of serialized objects with contexts attached to them, and you want to compress them, presumably send them over the network (?), and decompress them with contexts still attached to the same elements on the 'other side'?

So in my use case for the outgoing flow the context is not serialized, its actually a Kafka cursor which get committed after the data is persisted into an S3 object (more accurately the cursor gets committed after a successful chunk is persisted in a multipart upload). For the incoming flow (i.e. `fromNetwork`) the decompression is a non issue since its just raw bytestring data coming from a serialized S3 object (there is no context here so its just a standard `Flow`).

I think for my case just doing `FlowWithContext.map` with `GzipCompressor().compressAndFinish(bytes)` is okay for an initial solution. Its not pure streaming but I am also not expecting an individual element in the `FlowWithContext` to be very large so its not a big problem.

**Comment by mdedetrich** [comment]
Okay so I managed to solve the problem fairly easily, created a helper function like so

```scala
def flattenFlow[T](flow: Flow[T, T, NotUsed], zero: T, foldFunc: (T, T) => T) =
  Flow[T].flatMapConcat { single =>
    Source
      .fromMaterializer { case (mat, _) =>
        implicit val m: Materializer = mat
        Source.future {
          Source.single(single).via(flow).runFold(zero)(foldFunc)
        }
      }
      .mapMaterializedValue(_ => NotUsed)
  }
```

And then you can just simply put this directly into `unsafeDataVia` i.e.

```scala
val flowWithContext: FlowWithContext[ByteString, Int, _]] = ???
flowWithContext.unsafeDataVia(flattenFlow[ByteString](Compression.Gzip, ByteString.empty, _ ++ _))
```

And its working as expected!

@johanandren @raboof Do you think it makes sense to contribute `flattenFlow` to akka and also update the documentation of `unsafeDataVia` to mention `flattenFlow` so that people have a helpful helper function incase they are dealing with flows that can emit more than one element? And if so from an API design perspect, does it make sense to have the `flattenFlow` function on the `Flow` object, i.e. `Flow.flattenFlow(myFlow, zero, fold)` or OO style on an existing flow i.e. `myFlow.flatten(zero, fold)`?

**Comment by johanandren** [comment]
I don't think it adds anything improving much on `flatMapConcat` (which I think makes the sub materialization a bit more obvious)?

**Comment by mdedetrich** [comment]
How about adding a `flowWithContext.dataVia` which just uses `flatMapConcat` internally?

**Comment by mdedetrich** [comment]
I will close this issue since this is a case of RTFM but I will open a PR in the future implementing https://github.com/akka/akka/issues/31522#issuecomment-1232958596 which is a better place to discuss any improvements.

@johanandren Thanks for the time.
