### ISSUE TITLE
Java OO Typed Behavior not depending on Receive

### ISSUE THREAD

**Issue by leviramsey** [akka/akka#31531]
Prompted by [this SO question](https://stackoverflow.com/questions/69361006/remove-duplication-with-abstractbehavior-createreceive)

Conceptually, all a `Behavior<T>` is is a function from `T` to `Behavior<T>` (along with a (potentially partial) function from a `Signal` to a `Behavior<T>`).  In the Scala API, `AbstractBehavior` captures this with (in Java notation) `Behavior<T> onMessage(T msg)`.

In the Java API, though, an `AbstractBehavior` has to first define a different `Behavior` which is constrained to be a `Receive`.  Perhaps this is down to Java not having pattern matching (and partial functions for signal handling) and also to ape the classic API.

We can see this in the implementations of `scaladsl.AbstractBehavior.receive(TypedActorContext[T], T)` and `javadsl.AbstractBehavior.receive(TypedActorContext[T], T)` after inlining:

```scala
// scaladsl
checkRightContext(ctx)
onMessage(msg)

// javadsl
checkRightContext(ctx)
_receive match {
  case OptionVal.Some(r) => r.receive(ctx, msg)
  case _ =>
    val r = createReceive
    _receive = OptionVal.Some(r)
    r.receive(ctx, msg)
}
```

The scaladsl is pretty clearly a more direct encoding.

Goal:

```java
public class AccumulatorBehavior extends AbstractBehaviorWithoutReceive<AccumulatorBehavior.Command> {
  public interface Command;

  public static final class Add implements Command {
    public final int n;

    public Add(int n) {
      this.n = n;
    }
  }

  public AccumulatorBehavior(ActorContext<Command> context) {
    context.setLoggerName("Accumulator")
    super(context);
    value = 0;
  }

  public Behavior<Command> onMessage(Command cmd) {
    // pre-Java 16
    if (cmd instanceof Add) {
      value += ((Add)cmd).n;
      getContext().getLog().info("value is now {}", Integer.valueOf(value));
    }
    return this;

    // Java 16: instanceof and cast (JEP 394)
    if (cmd instanceof Add add) {
      value += add.n;
      getContext().getLog().info("value is now {}", Integer.valueOf(value));
    }
    return this;
  }

  private int value;
}
```

I'm not that familiar with Java 17 onwards pattern matching (e.g. can you have blocks), so not confident enough to provide an example, but that would likely make any ergonomic advantage of a builder even less.

**Comment by leviramsey** [comment]
A sort of related observation is that it's not at all clear what the difference between a `Receive` and a `Behavior` is.  A `Receive` seems to just be a `Behavior` that's built via the `ReceiveBuilder`.

Meanwhile, comparing the `ReceiveBuilder` and `BehaviorBuilder`, the only apparent difference is that one is an immutable builder and the other is a mutable builder, which seems tenuous as a basis for distinction.

**Comment by patriknw** [comment]
The background reason for this structure is that BehaviorBuilder should only be created once for performance reasons. Therefore the `createReceive` is called once. With later Java versions the ReceiveBuilder might not be needed and I agree that the it could just be `onMessage` and `onSignal` as in the scaladsl.

To support that we would have to add another class in addition to the existing AbstractBehavior.
