### ISSUE TITLE
>How would light bend enforce the pricing in a variable workload environment?

### ISSUE THREAD

**Issue by nate100guess** [akka/akka#31580]
>How would light bend enforce the pricing in a variable workload environment? 

I have an idea: there will be a daemon running in akka, which will phone home with actual number of available CPU cores every minute or so and Lightbend will send a bill for max reported number during the year :) 

With rolling updates it will be even more fun - instead of regular X instances we will run X+\<maxSurge\> instances!

_Originally posted by @mr-git in https://github.com/akka/akka/issues/31561#issuecomment-1244994777_

**Comment by patriknw** [comment]
We will not do this.
