### ISSUE TITLE
Avoid name collisions in MessageFormats.proto in non-Java, non-Scala languages

### ISSUE THREAD

**Issue by t5kaji** [akka/akka#31583]
Hi, we've used akka-persistence to construct a system based on event sourcing, and we've adopted Rust to implement an application to consume event data from journal database.
In order to consume persistent message data from journal database and decode it, we compile MessageFormats.proto and generate some Rust codes for serialization/deserialization because event data contains bytes serialized via MessageFormats.proto.

Currently, MessageFormats.proto's only defined java_package, which prevents non-Java, non-Scala users from compiling this file with namespace attached to it (https://github.com/akka/akka/blob/main/akka-persistence/src/main/protobuf/MessageFormats.proto#L7)
Since it's recommended to "still define a normal package as well to avoid name collisions in the Protocol Buffers name space as well as in non-Java languages" according to official document on Protocol Buffer (https://developers.google.com/protocol-buffers/docs/javatutorial#defining-your-protocol-format), I'd like to define "package" as well in MessageFormats.proto.

Could I add "package" to it?

**Comment by patriknw** [comment]
Which Akka Persistence plugin are you using? It's better if the plugin is not wrapping the event playload with PersistentRepr (MessageFormats).

**Comment by t5kaji** [comment]
@patriknw 
Thank you for the reply.
We've used a community dynamodb plugin, not the official one.
So it's not mandatory for a Akka Persistence plugin to have data that's some bytes serialized through MessageFormats.proto?(I thought each plugin should've contained it)
If so, I would agree with the idea that MessageFormats.proto doesn't have to include "package" definition👍

**Comment by patriknw** [comment]
Alla plugins that we maintain don't wrap in PersistentRepr (MessageFormats). Probably some old reasons for doing that in that dynamo plugin. My point is that `MessageFormats.proto` isn't really public api. If you really need that package definition you should be able to add it yourself, since I assume you copy the MessageFormats.proto anyway when generating the rust client.

**Comment by t5kaji** [comment]
@patriknw 
Thank you so much for your explanation.
I understood that `MessageFormats.proto` is not public api. So we're gonna deal with `package` problem by coping, modifying it and maintaining it within our place.
I'm gonna close this issue, thanks!
