### ISSUE TITLE
SupervisedGraphStageLogic allocates `Some` per element

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31589]
![image](https://user-images.githubusercontent.com/501740/190140697-ea5d6836-6dff-4d7c-be0c-09684c38669e.png)

**Comment by johanandren** [comment]
Called and value matched/used in calling method, never returned, so I suspect the allocation _may_ be eliminated by the JIT. Didn't investigate that further though. 

Seems easy enough to optimize away with an OptionVal instead though
