### ISSUE TITLE
slf4j 2.0.1 and logback 1.4.1

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31593]
Logback 1.4.1 depends on slf4j 2.0.1 and that is not fully compatible with 1.7.36 that we are currently using.

In the StubbedActorContext that is used in the BehaviorTestKit it is capturing the markers from `SubstituteLoggingEvent`, but `getMarker` has been replaced with `getMarkers`.

I don't think we want to force an upgrade to slf4j 2.0 yet?

**Comment by ennru** [comment]
The breaking change in slf4j got introduced during the work for the fluent API in [this commit](https://github.com/qos-ch/slf4j/commit/1f3b8726d160c51befdf57ec42c6bafbd8b8652c#diff-5b807b828a4ae210a6bd640c50e64b21eb15f1477fe640aec36d947ef2372c82R16).

Refs 
- https://github.com/qos-ch/slf4j/discussions/326
- https://www.slf4j.org/manual.html#compatibility states
  "However, from the client's perspective all versions of slf4j-api are compatible. Client code compiled with slf4j-api-N.jar will run perfectly fine with slf4j-api-M.jar for any N and M."

**Comment by ennru** [comment]
From the Slf4j authors: "this is considered internal API" :-(

https://jira.qos.ch/browse/SLF4J-577

**Comment by ennru** [comment]
I guess the way forward is to bump slf4j (together with the requirement to bump logback) and change the code in `StubbedActorContext` to use `getMarkers` instead.

**Comment by patriknw** [comment]
That was very unclear "internal api".

I'm not convinced that Akka should enforce all downstream projects to bump to later slf4j yet.

If this is a problem we should make it work with both slf4j 1 and 2 by using reflection for this problematic method.

**Comment by ennru** [comment]
Ok, we are lucky enough that only the testkit is affected. Let's put some reflection magic in place so it doesn't blow up when people use it with an slf4j > 2 version, but stay on the version we have now.

**Comment by patriknw** [comment]
I'll fix this. Should be simple.
