### ISSUE TITLE
backport to release-2.6: Fix statefulMap to not call onComplete twice.

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31628]
As I noticed when handle with `mapWithResource` https://github.com/akka/akka/pull/31361, this is a bug, so I try to backport it to release 2.6.otherwise user need to do a try catch even the exception we do not expected.

I think it's not a new feature but fix, so hope it can be accepted.

a new need to backport: https://github.com/akka/akka/pull/31630

**Comment by patriknw** [comment]
Thanks for following up @He-Pin. We will only backport critical bugs, and this doesn't qualify as such. The impact is low and should be fairly easy to workaround.
