### ISSUE TITLE
Link errors

### ISSUE THREAD

**Issue by ennru** [akka/akka#31641]
The link validator discovered some 404s that look legit: https://github.com/akka/akka/actions/runs/3171947397/jobs/5165898120#step:8:59

## HTTP failure response
[`https://doc.akka.io/api/akka/0.0.0+1-77d757c4-SNAPSHOT/StageLogging.html`](https://doc.akka.io/api/akka/0.0.0+1-77d757c4-SNAPSHOT/StageLogging.html) status 404 Not Found
 - stream/stream-customize.html
 

[`https://doc.akka.io/japi/akka/2.7/akka/actor/typed/javadsl/AbstractOnMessageBehavior.html`](https://doc.akka.io/japi/akka/2.7/akka/actor/typed/javadsl/AbstractOnMessageBehavior.html) status 404 Not Found
 - typed/actors.html
 

[`https://doc.akka.io/japi/akka/2.7/akka/cluster/sharding/ShardRegion.ClusterShardingStats.html`](https://doc.akka.io/japi/akka/2.7/akka/cluster/sharding/ShardRegion.ClusterShardingStats.html) status 404 Not Found
 - typed/cluster-sharding.html

[`https://doc.akka.io/japi/akka/2.7/akka/cluster/sharding/ShardRegion.CurrentShardRegionState.html`](https://doc.akka.io/japi/akka/2.7/akka/cluster/sharding/ShardRegion.CurrentShardRegionState.html) status 404 Not Found
 - typed/cluster-sharding.html

[`https://www.lightbend.com/contribute/cla/akka/current`](https://www.lightbend.com/contribute/cla/akka/current) status 404 Not Found
 - project/licenses.html

**Comment by johanandren** [comment]
Done in https://github.com/akka/akka/pull/31688
