### ISSUE TITLE
akka-stream_2.13:2.5.32 stream.materializer.subscription-timeout not work?

### ISSUE THREAD

**Issue by lfygh** [akka/akka#31646]
akka-stream_2.13:2.5.32 stream.materializer.subscription-timeout not work? is ture?

**Comment by johanandren** [comment]
There has been fixes since 2.5.32, for example https://github.com/akka/akka/issues/19980 

If you are experiencing problems around subscription-timeouts upgrade to latest Akka 2.6 to see if the problem still exists.

**Comment by patriknw** [comment]
Closing since we will not fix this in 2.5.x
