### ISSUE TITLE
Broken links in 2.7

### ISSUE THREAD

**Issue by ennru** [akka/akka#31650]
The link validator is unhappy about some links. Some look like wrong `@scaladoc` notations.

https://github.com/akka/akka/actions/runs/3217255524/jobs/5260014882#step:8:56

## HTTP failure response
`https://doc.akka.io/api/akka/0.0.0+1-a6863e9e-SNAPSHOT/StageLogging.html` status 404 Not Found
 - stream/stream-customize.html

`https://doc.akka.io/japi/akka/2.7/akka/actor/typed/javadsl/AbstractOnMessageBehavior.html` status 404 Not Found
 - typed/actors.html

`https://doc.akka.io/japi/akka/2.7/akka/cluster/sharding/ShardRegion.ClusterShardingStats.html` status 404 Not Found
 - typed/cluster-sharding.html

`https://doc.akka.io/japi/akka/2.7/akka/cluster/sharding/ShardRegion.CurrentShardRegionState.html` status 404 Not Found
 - typed/cluster-sharding.html

`https://www.lightbend.com/contribute/cla/akka/current` status 404 Not Found
 - project/licenses.html

**Comment by patriknw** [comment]
Is this a duplicate of https://github.com/akka/akka/issues/31641, or what is the difference?

**Comment by ennru** [comment]
Ooops, it is.
