### ISSUE TITLE
Remove deprecations since 2.5.x

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31664]
Since 2.7.x is on the way, I think it should be better to remove methods those deprecated since 2.5.x
![image](https://user-images.githubusercontent.com/501740/195759598-60b6ea08-4c26-4aac-aebb-12177029ca4a.png)

**Comment by patriknw** [comment]
We will not remove these in Akka 2.7 but the ticket is (probably) valid for 2.8.
