### ISSUE TITLE
High resolution ticker support?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31705]
In current Akka, the default timer is from `System.nano...` or `System.currentTimeInMillis`, how about change add a Clock interface for that?
https://github.com/OpenHFT/Chronicle-Ticker seems providing lower latency.
![image](https://user-images.githubusercontent.com/501740/198505521-ed90ee41-69b4-4fce-ba0c-20be8b2eced0.png)

**Comment by patriknw** [comment]
I don't think this is needed in Akka.
