### ISSUE TITLE
persistence delete event version calculate make integer overflow.

### ISSUE THREAD

**Issue by Roiocam** [akka/akka#31717]
check    akka.persistence.typed.internal.RetentionCriteriaImpl.scala#deleteUpperSequenceNr

[ math.max(0, lastSequenceNr - (keepNSnapshots * snapshotEveryNEvents))](https://github.com/akka/akka/blob/43d94bd42afae22f22e4d62563b2b65d11f3747f/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RetentionCriteriaImpl.scala#L29)

when I am using configuration that `keepNSnapshots = Integer.MAX_VALUE`

it will complain log like this, the debug result it was Integer overflow, make the result `deleteEventsToSeqNr` is negative.

<img width="1086" alt="截屏2022-11-03 15 05 16" src="https://user-images.githubusercontent.com/26020358/199663781-d19fdaf8-a862-40d3-b381-0c2373f2569a.png">

**Comment by johanandren** [comment]
Sure it is an overflow, but why are you setting `keepNSnapshots` to `Integer.MAX_VALUE`?

**Comment by Roiocam** [comment]
> Sure it is an overflow, but why are you setting `keepNSnapshots` to `Integer.MAX_VALUE`?

keep everything, but use a snapshot for faster event souring.

**Comment by aludwiko** [comment]
Why do you need old snapshots?

**Comment by Roiocam** [comment]
> Why do you need all old snapshots?

We don't need it, It was just a mistake in coding, The warning happened on my testing, So I decided to figure it out.

**Comment by johanandren** [comment]
The functionality of keeping of multiple snapshots is mostly intended for databases with weaker consistency where writing a snapshot might not immediately be visible for reads on all database nodes. 

So therefore it would be interesting for us to know why you want to keep all.

**Comment by johanandren** [comment]
Thanks for clarifying it wasn't really a use case we had missed :)
