### ISSUE TITLE
Akka Discovery fails on SRV Lookup

### ISSUE THREAD

**Issue by steffenhaak** [akka/akka#31724]
**Expected**
`akka.discovery.ServiceDiscovery.lookup("_cql._tcp.cassandra.default.svc.cluster.local", resolveTimeout)` will use SRV lookup and provide nodes with ports.

**Actual**
A/AAAA lookup is used and fails. Instead
`akka.discovery.ServiceDiscovery.lookup(Lookup("cassandra.default.svc.cluster.local", Some("cql"), Some("tcp") ), resolveTimeout)` would have to be used.

**Problem**
Neither Alpakka Cassandra nor Alpakka Kafka recognize the SRV pattern in the service name. So Akka Persistence Cassandra and Akka Projection Kafka currently are not able to discover Kubernetes services through Akka DNS.

**Proposed Change**
Changing lines 106 to 111 in akka.discovery.dns.DnsServiceDiscovery from

```
  override def lookup(lookup: Lookup, resolveTimeout: FiniteDuration): Future[Resolved] = {
    if (lookup.portName.isDefined && lookup.protocol.isDefined)
      lookupSrv(lookup, resolveTimeout)
    else
      lookupIp(lookup, resolveTimeout)
  }
```
to

```
  override def lookup(lookup: Lookup, resolveTimeout: FiniteDuration): Future[Resolved] = {
    if (lookup.portName.isDefined && lookup.protocol.isDefined)
      lookupSrv(lookup, resolveTimeout)
    else {
      if (Lookup.isValidSrv(lookup.serviceName)) {
        lookupSrv(Lookup.parseSrv(lookup.serviceName), resolveTimeout)
      } else {
        lookupIp(lookup, resolveTimeout)
      }
    }
  }
```

would fix the issue.

**Comment by johanandren** [comment]
`ServiceDiscovery.lookup(String, FiniteDuration)` says " * Convenience for when only a name is required.", so it could be a change in behavior to make it automagically parse port out of the string. 
Maybe it is safe though, because a "normal" name would never accidentally look like a srv?

If we decide it is safe I think we should introduce a new `parse` method in `Lookup` that does the suggested guesswork and then use that  from `ServiceDiscovery.lookup` and not change `DnsServiceDiscovery`.

**Comment by steffenhaak** [comment]
First of all, thank you for your quick response!

Methods `Lookup.isValidSrv` and `Lookup.parseSrv` are already existing and URLs of type `_Service._Proto.Name` are defined in [RFC 2782](https://datatracker.ietf.org/doc/html/rfc2782), so this should definitely be safe. Lagom is actually handling it like that.

One could also introduce a config variable `resolveSrvUrls` which defaults to `false`. This way, it would not be a breaking change and neither Alpakka Cassandra nor Alpakka Kafka would require to be changed. What do you think of that approach?

**Comment by johanandren** [comment]
What I wondered was if there could ever be a dns name matching `_aaa._bbb.ccc` not being a srv record (as that was always a legal dns name?). I think the risk is minimal however, lets change the convenience lookup method.
