### ISSUE TITLE
Update Algolia key to use the commercial one

### ISSUE THREAD

**Issue by JustinPihony** [akka/akka#31769]
We should also have this as an environment variable.

**Comment by johanandren** [comment]
The key is generated into the doc site html so doesn't seem to gain anything from an env variable.

Was the indexing set up for the commercial key? I think the algolia team did quite some work setting up the current indexing for us, so it is probably not only about switching keys on our side. (Configs on their side: https://github.com/search?q=org%3Aalgolia+akka&type=code )

**Comment by patriknw** [comment]
Is this done?

**Comment by johanandren** [comment]
No progress as far as I have heard (and was never working on it, just mentioned that it wasn't just about changing some account key)

**Comment by johanandren** [comment]
Now done, via #31868, #31873 and https://github.com/akka/akka-http/pull/4240
