### ISSUE TITLE
Improve groupBy stream example

### ISSUE THREAD

**Issue by giena** [akka/akka#31776]
Hi,

I think the function is a bad idea in this example: https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/groupBy.html#example

https://github.com/akka/akka/blob/7abc41cf4e7e8827393b181cd06c5f8ea684e696/akka-docs/src/test/scala/docs/stream/operators/sourceorflow/GroupBy.scala#L16

Since 

.groupBy(maxSubstreams = 8, _ % 8 == 0) // create two sub-streams with odd and even numbers
will still create 2 substreams.

.groupBy(maxSubstreams = 2, _ % 2) // create two sub-streams with odd and even numbers
is better IMHO.

**Comment by johanandren** [comment]
I agree having the grouping function returning a number makes slightly more sense than a boolean in that samples. Would you be up for doing a PR improving on it?

**Comment by giena** [comment]
@johanandren In the actual context of licence, I think that it's already helpful that i create an issue.
