### ISSUE TITLE
Failed: removed gcp auth plugin

### ISSUE THREAD

**Issue by octonato** [akka/akka#31788]
This has been reported before when we notice the deprecation warnings. 

Not it's failing the build.
https://github.com/akka/akka/actions/runs/3672078501/jobs/6207914656#step:6:10

**Comment by johanandren** [comment]
Superseedes the warning issue then: https://github.com/akka/akka/issues/31411

**Comment by octonato** [comment]
Yep, sorry. I was planning to close the warning issue, but forgot it.

**Comment by johanandren** [comment]
Now working when manually triggered, full diff of changes https://github.com/akka/akka/compare/e2c3f787b5ba92a1385fa16f4c85306c14f1bec6...b7b79a2da1231520fe66532b7af53179d1714952
