### ISSUE TITLE
Misbehaving failure handling for messages in backoff stash buffer

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31814]
Reported in SO: https://stackoverflow.com/questions/75065817/akka-why-are-stashed-messages-with-backoff-supervision-lost

Short: messages stashed in the internal supervision stash during backoff may be lost if one of them triggers a new error when unstashing once backoff completes and restarts.

**Comment by havenwang-plenty** [comment]
To add specifics, it appears that the `StashBuffer` used to hold messages is re-init during the `prepareRestart` phase of the restart as seen [here](https://github.com/akka/akka/blob/main/akka-actor-typed/src/main/scala/akka/actor/typed/internal/Supervision.scala#L356). 

Thus, any unprocessed messages once a backoff completes and restarts will no longer be accessible during the next restart.
