### ISSUE TITLE
Drop AkkaSSLConfig and transitive ssl-config dependency

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31822]
I _think_ it is deprecated since 2.6.0 everywhere, could we drop it completely by now? (parser combinators versions is a head ache)

**Comment by ennru** [comment]
In case it is decided to keep it, Akka should use ssl-config version 0.6.1 even for Scala 2 just as for Scala 3.
Version 0.6.0 dropped the unused Scala Parser Combinators dependency. https://github.com/lightbend/ssl-config/releases/tag/v0.6.0

**Comment by patriknw** [comment]
Is it used in Akka HTTP? Can it be removed there?

Anyway, bumping to the later version should be fine.

**Comment by johanandren** [comment]
Deprecated since Akka HTTP 10.2.0 so I think that should be ok

**Comment by johanandren** [comment]
Took another look at Akka HTTP and it does provide a few deprecated APIs based on ssl-config but it does not directly depend on it, instead it gets it as a transitive dep from akka-stream, so we'd have to start with the Akka side.

**Comment by sebastian-alfers** [comment]
Is it everything in [here](https://github.com/akka/akka/tree/main/akka-stream/src/main/scala/com/typesafe/sslconfig/akka) that needs removed? Or only `AkkaSSLConfig.scala` itself?

**Comment by johanandren** [comment]
Dropping it for Akka in https://github.com/akka/akka/pull/31831
