### ISSUE TITLE
Invalid configuration?

### ISSUE THREAD

**Issue by franciscolopezsancho** [akka/akka#31830]
Aren't these lines incompatible with`akka-diagnostics`

https://github.com/akka/akka/blob/7f1e439032cd5ee3163ba6d1ab80829fbf30b1d5/akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala#L93

https://github.com/akka/akka/blob/7f1e439032cd5ee3163ba6d1ab80829fbf30b1d5/akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala#L134-L136

Meaning. They are creating invalid configuration such as https://github.com/akka/akka-guide/actions/runs/4074859245/jobs/7020504974#step:6:91

**Comment by johanandren** [comment]
I think akka-diagnostics should just ignore anythning under `akka.persistence.testkit`

**Comment by patriknw** [comment]
I don't think we have to ignore everything under `akka.persistence.testkit`. There are still some reference.conf values there that can be good to check.

The problem, if I understand it correctly, is that the `class` property isn't included in the reference.conf. I can't understand why it's not included there.

I suggest that we add the following to diagnostics disabled-typo-sections
```
"akka.persistence.testkit.journal.class",
```

The testkit snapshot config is even more weird https://github.com/akka/akka/blob/7f1e439032cd5ee3163ba6d1ab80829fbf30b1d5/akka-persistence-testkit/src/main/scala/akka/persistence/testkit/PersistenceTestKitPlugin.scala#L125-L137

That's beyond repair, so let's ignore all for that
```
"akka.persistence.testkit.snapshotstore.pluginid"
```

**Comment by franciscolopezsancho** [comment]
Okay. Ignoring them makes sense. How about I ignore any `"akka.persistence.testkit.snapshotstore.*"` as there is no entry for `snapshotstore` in the conf, and I ignore `"akka.persistence.testkit.journal.*"` as there is not entry for `journal` either?

**Comment by franciscolopezsancho** [comment]
fixed in https://github.com/akka/akka-diagnostics/pull/32
