### ISSUE TITLE
Fossa scanning akka-bench-jmh and failing

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31869]
https://github.com/akka/akka/actions/runs/4328275999/jobs/7557789150

jmh uses gpl libraries, but we only use the tool, so we should be fine.

It barks even though we have an exclude for akka-bench-jmh in .fossa.yml

**Comment by pvlugter** [comment]
Still failing. I don't actually see a `.fossa.yml` at all, or am I missing where it is?

**Comment by pvlugter** [comment]
Adding a `.fossa.yml` with a path exclude in #31877. Unclear where it was previously, or why this starts failing now.
