### ISSUE TITLE
Link for quick guide is broken.

### ISSUE THREAD

**Issue by ricrsantos** [akka/akka#31880]
Hello everyone.
Sorry, I don't if it's the correct place to put this information. I would like to inform you that the link to access the quick guide: https://developer.lightbend.com/guides/akka-quickstart-java/?_ga=2.61186410.792724676.1678725944-735189854.1678725944, is broken. 

Thank you for your job guys!

**Comment by johanandren** [comment]
Thanks for letting us know!

**Comment by johanandren** [comment]
It was some infrastructure issues. Now it is sorted and the quickstart is accessible again.
