### ISSUE TITLE
Naming conflicts in cluster singleton leases

### ISSUE THREAD

**Issue by mbrito-yieldstreet** [akka/akka#31925]
The naming schemes for leases acquired by `ClusterSingletonManager` can easily hit the 63-character limit imposed by Kubernetes, causing multiple leases to end up with the name sanitized name.

For example, this is from one of our applications:

> Original lease name [deal-ledger-singleton-akka://deal-ledger/user/readSideGlobalPrepare-DistributionToJsonEventProcessor-singleton] sanitized for kubernetes: [deal-ledger-singleton-akkadeal-ledgeruserreadsideglobalprepare]
>
> Original lease name [deal-ledger-singleton-akka://deal-ledger/user/readSideGlobalPrepare-DealEventProcessor-singleton] sanitized for kubernetes: [deal-ledger-singleton-akkadeal-ledgeruserreadsideglobalprepare]

Granted, my actor names are somewhat long (thanks, Lagom), but it would help if the name scheme didn't repeat the actor system name twice and included the probably useless `akka://` prefix. A pattern like `${context.system.name}-singleton-${self.name}` is probably appropriate for most applications; alternatively, using `self.path.toStringWithoutAddress` will at least remote the system name duplication.

**Comment by johanandren** [comment]
I'll close this, please comment in the akka-management issue if you have some ideas or details missing from there.
