### ISSUE TITLE
projection r2dbc documentation broken

### ISSUE THREAD

**Issue by Canislupax** [akka/akka#31937]
Since 2.8.1 the documentation for the projection-r2dbc after movement from the akka-persitence module broken. 
-> https://doc.akka.io/docs/akka-projection/current/r2dbc.html

**Comment by johanandren** [comment]
Hi, sorry for the inconvenience, the reason is that we have not yet released Akka projection 1.4.0 with the R2DBC module moved, you can find a snapshot of the docs here until we have released it (we will release very soon): https://doc.akka.io/docs/akka-projection/snapshot/r2dbc.html

**Comment by johanandren** [comment]
Now out and fixed for a while already.
