### ISSUE TITLE
Backport akka-cluster SBR to earlier revisions particularly for those that rely on Scala 2.11 (Akka 2.5.x)

### ISSUE THREAD

**Issue by taepyongyang** [akka/akka#31946]
I'm seeking guidance for appetite to allow backport of the open sources SBR (Split Brain Resolver) released in akka/akka 2.8.x to earlier Akka versions. In my case, particular to the version of Scala I'm using 2.11 and am relying on Akka 2.5.x. 

I'm happy to test and submit if maintainer would be willing accept PR to be built for distribution through existing distribution channels.

**Comment by He-Pin** [comment]
This 2.5.x is EOL, but if your company has a subscription from Lightbend that may not be a problem.

And you can upgrade to a new version as it is binary-compatible.

**Comment by patriknw** [comment]
Thanks for the request, but we will not do this. You should update to later supported versions of Akka and Scala.
