### ISSUE TITLE
Bump or replace Netty in akka-multi-node-testkit

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31974]
akka-multi-node-testkit depends on an old Netty version (3.10.6) which has one or more CVEs attached, possibly firing off warnings in vulnerability scanners. I don't think there are any valid issues since the Netty usage is pretty minimal but who knows.

Bumping to Netty 4 is not a drop in replacement, might be just as much work to simply drop it completely.

Mostly noting this down for history keeping, this is a testkit and not something that should be on the production classpath of an app built with Akka. I don't expect we will make this a priority.

**Comment by He-Pin** [comment]
I think I would like to rewrite it with Netty 4, if its is acceptable :)

**Comment by patriknw** [comment]
That would be welcome, thanks
