### ISSUE TITLE
Akka Persistence with multi-tenant (ReadJournal)

### ISSUE THREAD

**Issue by gael-ft** [akka/akka#31976]
Building a persistence plugin where each customer have its own database but the backend is shared.

For `AsyncWriteJournal` and `SnapshotStore` plugin APIs, current Akka Persistence API fits well as we can use the `PersistenceId` to map to the correct database.
For example, the strategy could be `[customerName]/[entityTypeKey]|[entityId]`.

But for `ReadJournal` it is more complicated.
For example `CurrentPersistenceIdsQuery` trait defines `def currentPersistenceIds(): Source[String, NotUsed]`.
As no arguments is given, we have no way to perform the logic.

I know that child traits of `ReadJournal` are optional so I could add my own methods but I submit this request as doing so, I won't be able to some of the tools in [Event Sourced Akka Projection](https://doc.akka.io/docs/akka-projection/current/eventsourced.html).
Once again, we could define our own ways to create `akka.projection.scaladsl.SourceProvider`.
But that would be nice if we could reuse existing classes in Akka Projection.

I was thinking about providing overloaded methods in child traits of `ReadJournal` (which support should be documented by plugin authors as it's the case already with others methods):

```scala
// Plugin authors could extends it as they want
trait QueryOptions

// In my case
final case class TenantQueryOptions(customer: String) extends QueryOptions

// Adding a overloaded method to child traits of ReadJournal (here CurrentPersistenceIdsQuery)
trait CurrentPersistenceIdsQuery extends ReadJournal {
  def currentPersistenceIds(): Source[String, NotUsed]
  
  def currentPersistenceIds(options: QueryOptions): Source[String, NotUsed]
}
```

Do you think it would be acceptable ?

**Comment by leviramsey** [comment]
A possibility that preserves the shared backend would be to have a function which returns a read journal with the query options applied:

```scala
def journalForTenant(customer: String): ReadJournal with CurrentPersistenceIdsQuery with EventsByTagQuery =
  new ReadJournal with CurrentPersistenceIdsQuery with EventsByTagQuery {
    def currentPersistenceIds(): Source[String, NotUsed] = baseJournal.currentPersistenceIds(customer)
    def eventsByTag(tag: String, offset: Offset): Source[EventEnvelope, NotUsed] = baseJournal.eventsByTag(customer, tag, offset)
  }
```

And then in Projections:

```scala
def sourceForCustomer(customer: String): SourceProvider[Offset, EventEnvelope[ShoppingCart.Event]] =
  EventSourcedProvider.eventsByTag(
    system,
    journal.journalForTenant(customer),
    "special-tag"
  )
```

You could then build a projection behavior per `customer x tag` and distribute those via sharding (you could use sharded daemon process if you use `customer` as the name of the sharded daemon process, though this is specific to the particular "`customer` is a string" aspect of this example... if that didn't hold, adding query options would likewise not work well with sharded daemon process... one could roll their own sharded daemon process implementation that loosened this).

**Comment by patriknw** [comment]
Is `CurrentPersistenceIdsQuery` just an example and what you really want to use with Projections is `EventsByTagQuery` or `EventsBySliceQuery`? In that case I would recommend that you build things on `EventsBySliceQuery`, which we use for many of the new features. It has an `entityType: String` parameter and it looks like you will encode the tenant in the entityType.

**Comment by gael-ft** [comment]
Well I think with both of your answers I can manage Akka Projection thanks !
