### ISSUE TITLE
Failed: AeronStreamLatencySpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32008]
https://github.com/akka/akka/actions/runs/5459886326/jobs/9936318017#step:10:1666

```
[info] [JVM-1] - must be low for rate-10000-size-100, at 10000 msg/s, payloadSize = 100 (on node 'first', class akka.remote.artery.aeron.AeronStreamLatencySpecMultiJvmNode1) *** FAILED *** (3 seconds, 793 milliseconds)
[info] [JVM-1]   sendQueue full (AeronStreamLatencySpec.scala:283)
[info] [JVM-1]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-1]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
[info] [JVM-1]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
[info] [JVM-1]   at akka.remote.artery.aeron.AeronStreamLatencySpec.newAssertionFailedException(AeronStreamLatencySpec.scala:73)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5571154175/job/15084865823#step:10:1678

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5780262840/job/15663679850#step:10:1609

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/5851050126/job/15861265964#step:10:1612

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6044589550/job/16403381058

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6243121881/job/16948044896#step:10:1657

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/6451560944/job/17512334969#step:10:1669

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6528138026/job/17723901110#step:10:1674

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6714794809/job/18248531274#step:10:1682

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6687455016/job/18168114485#step:10:1671

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/6740459259/job/18323565793#step:10:1675

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6792853414/job/18466767286#step:10:1674

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6872046806/job/18689873315#step:10:1601

**Comment by patriknw** [comment]
Probably fixed by https://github.com/akka/akka/pull/32242
