### ISSUE TITLE
Akka remote TCP configuration are overwritten when SSL is enabled

### ISSUE THREAD

**Issue by naval2608** [akka/akka#32018]
Seeing this bug in version 2.6.20 

- using https://doc.akka.io/docs/akka/2.6/project/migration-guide-2.5.x-2.6.x.html#remaining-with-classic-remoting-not-recommended- to move to version 2.6.20 from 2.5
- https://doc.akka.io/docs/akka/2.6/project/migration-guide-2.5.x-2.6.x.html#config-library-resolution-change is not working as expected where tcp configs should be copied over to ssl : _**akka.remote.classic.netty.ssl = ${akka.remote.classic.netty.tcp}**_

Repro:
- setup ssl using https://docs.oracle.com/cd/E19509-01/820-3503/6nf1il6er/index.html and get akka ssl working.
- set the following remote configs:
  -  akka.remote.classic.netty.tcp.maximum-frame-size="512m"
- add breakpoint https://github.com/akka/akka/blob/v2.6.20/akka-remote/src/main/scala/akka/remote/RemoteSettings.scala#L183

**Comment by patriknw** [comment]
classic remoting is deprecated and removed
