### ISSUE TITLE
Update the gitter channel?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#32064]
Seems no one is chatting on gitter, should it be replaced to discord room/channel?

**Comment by johanandren** [comment]
I don't think anyone in the core team is interested/has time for hanging out in chats though, so it is more of a community place. Seems to be some activity now and then in the gitter, if the community moved over to discord I'd be fine with pointing to that but I don't know it did.

**Comment by He-Pin** [comment]
I see.
