### ISSUE TITLE
Reintroduce a way to specify default config for custom materialisers

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32088]
With the deprecation of the ActorMaterializer API we expected that they canonical way of configuring for example dispatchers would be per stream, but it can definitely be convenient to be able to define default attributes for a separate materializer. I imagine we could do something like allowing a set of default attributes to the additional create/apply factories in `Materializer`

**Comment by He-Pin** [comment]
Maybe a `VirtualThreadMaterializer`?

**Comment by johanandren** [comment]
It would only be about providing an easier way to define default settings/attributes, not a new type of materializer.

**Comment by jphelp32** [comment]
Hi- I was asked by our Lightbend technical acct manager to comment here describing one of our Akka use cases that would potentially make use of this feature. Currently we are reliant upon the now deprecated methods pertaining to ActorMaterializerSettings.
Our API gateway is implemented w/akka-http and uses a pluggable architecture to support plugging in independent "Transports" for handling groups of API requests. Some examples of the various transports are SOAP, REST, Reports, etc. Basically grouping of various APIs based upon the processing logic necessary for each type of API. The processing w/in each Transport makes heave use of Akka Streams. All the Transports live within the same API Gateway service, but we try to achieve isolation between them in terms of their resource usage. One way this is achieved is by giving each Transport its own thread pool for all it processing. And so to achieve that we currently give each transport its own Materializer. With the changes that took place in Akka 2.6, we are now reliant upon some deprecated methods, and are looking for a way forward before these are ultimately removed. Our ask would be that methods are provided to still allow the creation of custom Materializers that accept a dispatcher other than the default system dispatcher for running streams. The PR associated here does appear to solve that issue. However we'd additionally like to be able to configure the custom Materializers to use the given dispatcher as its executionContext. Looks like w/this PR the Materializer can take in default attributes that include a Dispatcher, but it would still use the system default dispatcher as its executionContext. Is that something that could be supported here?

**Comment by johanandren** [comment]
Defining a different default dispatcher that the streams will run on would look like this with the current PR:

Scala:
```scala
val materializer = Materializer(system, ActorAttributes.dispatcher("my-stream-dispatcher"))
```

Java:
```java
var materializer = Materializer.create(system, ActorAttributes.dispatcher("my-stream-dispatcher"))
```

If you want to "inherit" the dispatcher from the actor context, you should be able to pick up the dispatcher name from the props of the actor. 

With classic actor APIs `context.props.dispatcher` gives you access to the name of the current dispatcher, but with typed we don't currently have a direct API for picking it up and you'd have to go through the context adapter to find the name (Scala `context.toClassic.props.dispatcher` or Java `akka.actor.typed.javadsl.Adapter.toClassic(context).props.dispatcher`).

**Comment by jphelp32** [comment]
@johanandren is there a way to provide not only the dispatcher for running streams (via the defaultAttributes), but also the executionContext to a custom materializer? Our use case for custom Materializers is such that we'd like to keep the executionContext and stream dispatcher the same. If I am reading the merged commits correctly, the custom Materializer will always have the same executionContext as the system default materializer.

**Comment by johanandren** [comment]
The actors running the materialised stream will execute on the specified dispatcher, the return value of `Materializer#materializer` will also be that same dispatcher (picked up from the attributes).

**Comment by jphelp32** [comment]
ah, I think you meant `Materializer#executionContext`? And yes, I had overlooked this:
https://github.com/akka/akka/blob/a459e84bb98033d9a06ccdd6f2e1043ceeb35368/akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala#L420C2-L421C2
This does provide what I was looking for. Thank you.
