### ISSUE TITLE
Update to Scala 3.3 in all projects

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32093]
The Scala 3 version is one of those that we should align across all Akka modules, at least the minor version 3.3.x.

**Comment by johanandren** [comment]
Open PRs bumping to 3.3 in our projects:

 - [ ] https://github.com/akka/akka-http/pull/4276
 - [ ] https://github.com/akka/akka-grpc/pull/1807
 - [ ] https://github.com/akka/akka-persistence-r2dbc/pull/405
 - [ ] https://github.com/akka/akka-projection/pull/926
 - [ ] https://github.com/akka/akka-management/pull/1173
 - [ ] https://github.com/akka/akka-persistence-cassandra/pull/1033
 - [ ] https://github.com/akka/alpakka-kafka/pull/1651
 - [ ] https://github.com/akka/alpakka/pull/3010 (mixed with other bumps)
 - [ ] akka-diagnostics (nothing yet)
 - [ ] akka-persistence-jdbc no support for 3

**Comment by johanandren** [comment]
Should now all be 3.3.1 instead

**Comment by patriknw** [comment]
that's all done
