### ISSUE TITLE
Additional cleanup after dropping Scala 2.12

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32126]
We should make this cleanup later, probably in Akka 2.10.

- [x] ccompat and akka.compat
- [x] #32511
- [x] `unused` shouldn't be needed
- [x] #32500
- [ ] and there could be some more, search for 2.12
- [x] drop scala-java8-compat (https://github.com/lightbend/akka-meta/issues/440)
- [x] #32501
- [x] drop scala.collection.JavaConverters

**Comment by sebastian-alfers** [comment]
I see we use `import scala.collection.JavaConverters._` which is noted as deprecated.

@patriknw Do you plan to refactor that usage as well for the next `2.10.0`?

**Comment by patriknw** [comment]
That would be good

**Comment by ennru** [comment]
Is this done done?

**Comment by patriknw** [comment]
yes, as far as we know
