### ISSUE TITLE
Misleading shard handoff timeout message

### ISSUE THREAD

**Issue by lychko** [akka/akka#32172]
Shard handoff timeout message says (see ShardRegion.scala)
`s"Waiting additional [${handoffTimeout.toCoarsest}] before stopping the remaining entities.")`
while at that moment `StopTimeoutWarningAfter `seconds has already passed.
It took me some time to figure out why actual stop happens 5 seconds before the time that message predicts.

Suggestion is to change message accordingly (to `entityHandOffTimeout - StopTimeoutWarningAfter`)

**Comment by johanandren** [comment]
I agree, using `entityHandOffTimeout - StopTimeoutWarningAfter` for that log entry sounds more correct.
