### ISSUE TITLE
Failed: RemoteConnectionSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32182]
https://github.com/akka/akka/actions/runs/6554326968/job/17801126975#step:5:905

Related to the latest changes @patriknw ?

```
[info] - should handle uid collision when connection FROM two systems with same uid *** FAILED *** (7 seconds, 181 milliseconds)
[info]   UidUnknown was not equal to UidKnown (RemoteConnectionSpec.scala:177)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7539)
[info]   at akka.remote.artery.RemoteConnectionSpec.$anonfun$new$5(RemoteConnectionSpec.scala:177)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6540725194/job/17761137463#step:5:935

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6527316872/job/17722007449#step:5:845

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6520726406/job/17708562431#step:5:892

**Comment by patriknw** [comment]
I'll take a look

**Comment by patriknw** [comment]
some of these are:
```
timeout (1 second) during expectMsg while waiting for ping1a
```

and that must have been before the other fix, so I'm ignoring those

**Comment by patriknw** [comment]
Temporary pending for Aeron (https://github.com/akka/akka/pull/32190)
I'll try to get back to this when more urgent things have settled.
