### ISSUE TITLE
Cleanup in labels

### ISSUE THREAD

**Issue by Captain1653** [akka/akka#32197]
I have found many unused and unnecessary labels in the project:
* [Merge After 2.6.0 Release](https://github.com/akka/akka/labels/Merge%20After%202.6.0%20Release)
* [reviewed](https://github.com/akka/akka/labels/reviewed)
* [tested](https://github.com/akka/akka/labels/tested)
* [validating](https://github.com/akka/akka/labels/validating)
* [wip](https://github.com/akka/akka/labels/wip) (can be used Draft PR)
* [stashed PR](https://github.com/akka/akka/labels/stashed%20PR)

Is it worth removing them and maybe some others?

**Comment by johanandren** [comment]
If we remove them they are also removed from issues where they were once used. I think it is worth keeping for historical reason (not that it exactly is amazing value but it is also not a big problem with the now unused labels).

**Comment by Captain1653** [comment]
Ok. Thank you for your explanation.
