### ISSUE TITLE
Actor system cannot be terminated when scheduling 0 delay task

### ISSUE THREAD

**Issue by Roiocam** [akka/akka#32271]
akka version:  2.6.20

I am currently know why it will be a deadlock, but i am wonder why `terminate` won't destory a spin timer, and scheduler willing accept a spin task.

case gist link: https://gist.github.com/Roiocam/d317683d54bdbf3afe75b1b945c7f115

and simplified code below(plz ignore those adapter...).

```java
public class DeadlockCase {

    ActorSystem classicSystem;

    @Before
    public void setUp() {
        classicSystem = ActorSystem.create("test");
    }

    @After
    public void tearDown() throws InterruptedException, TimeoutException {
        Await.ready(
            classicSystem.terminate(),
            scala.concurrent.duration.Duration.create("Inf"));
    }


    @Test
    public void dead_lock_case(){
        // unexpected assign with 0
        long heartbeatInterval = 0L;

        // create an actor and a probe
        akka.actor.ActorRef actorRef = classicSystem.actorOf(
            Adapter.props(() -> EchoActor.create(heartbeatInterval)));
        TestProbe probe = TestProbe.apply(classicSystem);

        // mock echo
        String msg = "msg";
        EchoCmd echoCmd = new EchoCmd(msg, Adapter.toTyped(probe.ref()));
        actorRef.tell(echoCmd, akka.actor.ActorRef.noSender());

        // assert
        String reply = probe.expectMsgClass(FiniteDuration.apply(100, TimeUnit.MILLISECONDS),String.class);
        // this line never reach
        Assert.assertEquals(msg, reply);
    }

}
```

AFAIK, java `ScheduledThreadPoolExecutor` will refuse the zero period task.

**Comment by johanandren** [comment]
That is interesting, thanks for reporting. Not obvious why actor system shutdown is blocked from a quick look. Could it be filling up the dispatcher queues with runnables perhaps? eventually kills the JVM because running out of memory (all those 0-delay messages piling up I guess).

We should probably fail fast on `startTimerWithFixedDelay` and `startTimerAtFixedRate` with a 0 delay anyway.
