### ISSUE TITLE
Stackoverflow in ByteString

### ISSUE THREAD

**Issue by luzhongjian** [akka/akka#32272]
I have developed and run a project with akka 2.6, scala 2.12, java 1.8 for several years. Recently the load of the system has been getting heavier, I would want to improve the performance by upgrading to more modern akka: akka 2.9.1, scala 2.13, java 17. After I changed some codes to pass compilation to adapt the new version configuration and run the project in production environment. It  crashes every few minutes. The log shows a stackoverflow exception raised. The log has a huge amount of lines repeating as below.

```
at akka.util.ByteStringBuilder.addAll(ByteString.scala:1076)
at scala.collection.mutable.Growable.$plus$plus$eq(Growable.scala:69)
at scala.collection.mutable.Growable.$plus$plus$eq$(Growable.scala:69)
at akka.util.ByteStringBuilder.addAll(ByteString.scala:1187)
at akka.util.ByteStringBuilder.addAll(ByteString.scala:1076)

```
Unfornately, the log file does not show the exact place in my code where the exception is raised.
[build.sbt.txt](https://github.com/akka/akka/files/13784609/build.sbt.txt)

I attached a build.sbt for you to bettern understand what versions of componets I am using.

Thanks for your talented work.

**Comment by johanandren** [comment]
Thanks for letting us know, there is a slight difference with the (now dropped) 2.12 specific ByteString implementation so I think there could be a bug lurking here. I don't see an obvious mistake though, so it would be great if you could identify a way to reproduce.

**Comment by johanandren** [comment]
Figured out how to reproduce, `builder ++= (Seq[Byte](1,2,3))` triggers an infinite loop between `++=` and `addAll`.
