### ISSUE TITLE
Simplify flight recorder interactions

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32309]
When we still supported JDK 8 we had to dynamically avoid interacting with JFR APIs since not always available, now that we don't anymore we can simplify and just use JFR APIs directly (or with less in-between glue). In akka-actor-typed, akka-remote, and akka-cluster-sharding.

**Comment by patriknw** [comment]
Yes, there are probably much additional cleanup after dropping JDK 8 and Scala 2.12 that we can do when we are sure there is no way back, which I'm pretty sure is the case already.

See also https://github.com/akka/akka/issues/32126
