### ISSUE TITLE
Set Jackson USE_PROPERTIES_BASED to no longer need @JsonCreator

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32328]
While digging into native image Jackson stuff I stumbled over `ObjectMapper#setConstructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)` which seems to behave as you'd expect/want for single field classes out of the box, so no annotation needed for `case class Example(singleField: String)`.

We'd need to investigate but seems convenient if it doesn't have any negatives for normal usage.

Source article: https://cowtowncoder.medium.com/jackson-2-12-most-wanted-3-5-246624e2d3d0

**Comment by patriknw** [comment]
Interesting, we should make use of that somehow. Might be dangerous in a patch release, but we could make it an opt-in and document it. I haven't ready the article in detail, so don't know if we need to add anything.
