### ISSUE TITLE
Scaladoc description of Source.cycle is confusing and should be clarified

### ISSUE THREAD

**Issue by dodnert** [akka/akka#32367]
The current Scaladoc description of `Source.cycle` is as follows:

> Creates [[Source]] that will continually produce given elements in specified order. Starts a new 'cycled' `Source` from the given elements. The producer stream of elements will continue infinitely by repeating the sequence of elements provided by function parameter.

This is confusing documentation because it is unclear whether the intended behavior is that the function `f` passed to `cycle` will be called just once to produce an `Iterator` and that particular order will be cycled repeatedly, or is `f` invoked repeatedly after the elements from the previous invocation have been exhausted. I see that the implementation does the latter.

Also, it would be helpful to explicitly add that if `f` returns an empty `Iterator`, then the `Source` is terminated with an error.

Here is my suggested replacement for the function description.

> Create a [[Source]] that will continually produce elements in the order they are provided.
The elements in the stream are determined by invoking the given function `f` to obtain an iterator. The function `f` is invoked repeatedly, as elements from the previous invocation are exhausted. The [[Source]] fails if `f` returns an empty iterator.

**Comment by johanandren** [comment]
Agree, that can be improved. Please PR if you want to.
