### ISSUE TITLE
Update to slf4j 2.0

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32364]
Sl4fj 2.0 is not fully backwards compatible. We made a workaround in https://github.com/akka/akka/pull/31825 to make it work with both. We have been holding back to update the dependency to 2.0 so that Akka wouldn't enforce all downstream projects to bump to later slf4j.

Sooner or later we will have to update, but no decision on when we will do that yet. Important that we make that change in all Akka projects at the same time to avoid confusion.

We have already seen that 2.0 is brought in by transitive dependencies of external libraries. akka-persistence-jdbc and the Slick dependency is one such, and we pinned slf4j to 1.7.36. Remember to remove that when we update.

**Comment by patriknw** [comment]
another pin in Akka Projections due to the Slick dependency

**Comment by johanandren** [comment]
And one more in akka-persistence-r2dbc (only migration tool tests though)

**Comment by ennru** [comment]
Alpakka Kafka benchmarks and tests have dependencies on `org.slf4j:log4j-over-slf4j` and `org.slf4j:jul-to-slf4j` that are currently locked to 1.7.36.
