### ISSUE TITLE
Source.fromJavaStream can use SplitIterator directly

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#32380]
Motivation:
The current Source.fromJavaStream should be using `stream.iterator`, as the code in pekko, I think it can be updated to make use of the splitIterator directly, because the `stream.iterator` just a wrapper around the `splititerator`.

Result:
Less allocation.

If this is acceptble in akka I would like to send a PR.

**Comment by octonato** [comment]
Done in #32382 

Thanks for bring this up, @He-Pin

**Comment by He-Pin** [comment]
@octonato yeah :) cool to have this in.
