### ISSUE TITLE
Allow initial timer delay to be 0

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32415]
This works, but why do we need single+concat? Wouldn't an initial delay of 0 be enough? Alright, initial delay isn't allowed to be 0? Wonder if we shouldn't allow initial 0 and also allow 0 for scheduleOnce?

_Originally posted by @patriknw in https://github.com/akka/akka-persistence-jdbc/pull/834#discussion_r1594094489_

In https://github.com/akka/akka/pull/32275 we changed so that both initial and subsequent delay must be > 0, but the problem of busy-looping is only for the subsequent, we could allow the initial delay to be 0 still.

**Comment by patriknw** [comment]
and by 0 I mean `<= 0`. there could be applications that calculate the delay as a diff between two timestamps and that could become < 0, meaning that it should be executed immediately. I assume we previously supported < 0?

**Comment by johanandren** [comment]
This is actually probably already as we want, the check in `akka.actor.LightArrayRevolverScheduler#schedule` is only on the `delay`, not the `initialDelay`

**Comment by patriknw** [comment]
good, and it's not on scheduleOnce
