### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [akka/akka#32603]
## Description  

For aarch64 platform, I have built " Akka" from source.  

## Steps   

Following "STEPS (https://doc.akka.io/docs/akka/current/typed/guide/index.html)" were used for building and installing Akka. 
```
sudo apt install openjdk-21-jdk -y 
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-arm64 
export PATH=$PATH:$JAVA_HOME/bin 
echo $PATH 
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list 
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add 
sudo apt-get update 
sudo apt-get install sbt 
Wget https://github.com/akka/akka/archive/refs/tags/v2.10.0.tar.gz 
tar xvf v2.10.0.tar.gz 
cd akka-2.10.0 
sbt 
```
## Outcome  

The next steps after starting the sbt server using sbt command is to interact with the project. 
```
[info] started sbt server 
akka > version 
> [info] Akka version: 2.10.0 
```
 
All this information was also added to Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by johanandren** [comment]
There is no need for a separate build for arm64, you can use the same jars from the repository as when running on x86. We do not continuously test on arm64 but we have not heard any reports of problems. If you find any please open up new specific issues for any error you see.
