### ISSUE TITLE
[Akka-actor] cannot create children while terminating or terminated] with root cause

### ISSUE THREAD

**Issue by liuweiGit** [akka/akka#32618]
exception is java.lang.IllegalStateException: cannot create children while terminating or terminated] with root cause
java.lang.IllegalStateException: cannot create children while terminating or terminated
	at akka.actor.dungeon.Children.makeChild(Children.scala:298)
	at akka.actor.dungeon.Children.attachChild(Children.scala:53)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:23)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:410)
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:914)

Hello, how can I solve this problem? Run it for a while and it will look like this.

**Comment by patriknw** [comment]
What actor is it trying to create? Is it expected that the ActorSystem is terminating or is it terminating already when it's starting?

**Comment by liuweiGit** [comment]
> What actor is it trying to create? Is it expected that the ActorSystem is terminating or is it terminating already when it's starting?

It works fine once the system starts up, but after running for a while it automatically terminates, and I want it to keep running until I get the abort command. But I couldn't find anything to cause it to stop automatically. Is there a configuration setting?

**Comment by liuweiGit** [comment]
> What actor is it trying to create? Is it expected that the ActorSystem is terminating or is it terminating already when it's starting?

It works fine once the system starts up, but after running for a while it automatically terminates, and I want it to keep running until I get the abort command. But I couldn't find anything to cause it to stop automatically. Is there a configuration setting?

**Comment by patriknw** [comment]
It should continue running unless there is a fatal error, or you terminate it explicitly. It will also stop if the root actor is terminated, the Behavior you defined when starting the ActorSystem.

**Comment by liuweiGit** [comment]
> It should continue running unless there is a fatal error, or you terminate it explicitly. It will also stop if the root actor is terminated, the Behavior you defined when starting the ActorSystem.
Thank you very much for your help. After I replaced the other version, it was fine and could run stably without automatic termination. I suspect that the version I used has a bug

**Comment by yuanpli** [comment]
> > It should continue running unless there is a fatal error, or you terminate it explicitly. It will also stop if the root actor is terminated, the Behavior you defined when starting the ActorSystem.
> > Thank you very much for your help. After I replaced the other version, it was fine and could run stably without automatic termination. I suspect that the version I used has a bug

Could you kindly share that which version you used to fix this issue? Thanks!
